### ISSUE TITLE
[BUG] targetBlobClient.beginCopy really slow

### ISSUE THREAD

**Issue by daolis** [Azure/azure-sdk-for-java#10018]
**Description**
1.
First we used `BlockBlobClient.copyFromUrlWithResponse` to trigger the copy process in azure.
Was really fast and worked well, except for files bigger than 256M.
(see https://docs.microsoft.com/en-us/rest/api/storageservices/put-blob#remarks)
This call also failed if the target Client was a BlockBlobClient and a source Blob was of type AppendBlob.

2. 
Then we changed the call to `BlockBlobClient.beginCopy`: Can handle different blob types, and files bigger than 256MB.
BUT...
...it's much slower than `copyFromUrlWithResponse`. (We need more than 1 day for some storage account)

**Test setup**
Copy a Storage Account with 3 Files
```
                      | copyFromUrlWithResponse   | beginCopy
----------------------------------------------------------------------------------
file1 (1MB)     |  219 ms                                  | 1.2 sec
file2 (1MB)     |  232 ms                                  | 15 sec
file3 (250MB) |  7557 ms                                | 37 sec
```

Any ideas what could be the reason?

**Comment by rickle-msft** [comment]
@daolis Apologies for the delay. The main difference in performance between copyFromFurl and begin copy is that the former is sync and the latter is not, which becomes particularly noticeable when copying across accounts. Because begin copy is async, there can be all kids of other factors that might play into this slow behavior like where the accounts are located and how busy they are. Still, 37s does seem long for copying 250mb, so let me double check with the service team and see if there are any other extenuating circumstances that may cause such a delay.

In the meantime, have you tried adjusting the polling interval on the `SyncPoller` you get back?

**Comment by rickle-msft** [comment]
So what I'm hearing is that this is indeed dependent on how much load the network and accounts are experiencing. Async copies actually only have a guarantee of completing within 2 weeks. While that is certainly atypical, there just aren't really any guarantees on the speed of this copy operation.

**Comment by daolis** [comment]
Right now, the polling interval is set to 1sec. Should i increase the value?

**Comment by daolis** [comment]
Tried also with higher polling interval values, but time for 250MB is always ~30sec

**Comment by rickle-msft** [comment]
@daolis As mentioned, with async copies, the service itself doesn't make any guarantees on how fast the copy will complete within a maximum of two weeks, so unfortunately there isn't much we can do in the sdk to assist with the slow copy time. Depending on you account locations and network configurations, you may be able to tweak those for better results, but again it's not guaranteed.

**Comment by daolis** [comment]
Could you send me the documentation link where i can find the information about the 2 week?

**Comment by rickle-msft** [comment]
The [REST Docs](https://docs.microsoft.com/en-us/rest/api/storageservices/copy-blob) have the following in the "Remarks" section:

"A pending Copy Blob operation has a 2 week timeout. A copy attempt that has not completed after 2 weeks times out and leaves an empty blob with the x-ms-copy-status field set to failed and the x-ms-copy-status-description set to 500 (OperationCancelled). Intermittent, non-fatal errors that can occur during a copy might impede progress of the copy but not cause it to fail. In these cases, x-ms-copy-status-description describes the intermittent errors."

**Comment by daolis** [comment]
Thank you!
So, there nothing what can be done on java api side...
Closing...
