### ISSUE TITLE
[BUG] Management POM does not build test JAR for azure-arm-client-runtime

### ISSUE THREAD

**Issue by vcolin7** [Azure/azure-sdk-for-java#10035]
Running `mvn install pom.management.xml` does not produce a test JAR for the aforementioned artifact, which is required by `azure-mgmt-keyvault`.

**Comment by yungezz** [comment]
hi  @ChenTanyi could you pls have a look? thanks.

**Comment by ChenTanyi** [comment]
@vcolin7 Can you provide a clearer command you have run?
If you just run the `mvn install -f pom.management.xml` (which currently under `sdk/parents/azure-arm-parent`), it just install a pom, no any jar in this pom.
If you want to install any `azure-mgmt-***` please run install under its folder. 

If you still have any problem, please add more detail about it. Thanks!

**Comment by vcolin7** [comment]
If I recall correctly, I was trying to fix an issue on a library that depends on `azure-arm-client-runtime`. I was trying to make changes on `azure-arm-client-runtime`, generate the JAR and use it as a dependency, however, I was not able to find the JAR anywhere in my local Maven repository.

One thing to note is that I probably didn't use the `-f` parameter before the POM file I intended to use. I will try to reproduce this problem the following week and if I'm not able to I will just close this issue :)

**Comment by ChenTanyi** [comment]
@vcolin7 Do you mean you want to install the `azure-arm-client-runtime` package? It should be `https://github.com/Azure/autorest-clientruntime-for-java` rather than `pom.management.xml`.

**Comment by vcolin7** [comment]
Thank you, that must have been the problem then. I will be closing this issue :)
