### ISSUE TITLE
Unable to set permissions to folder/file for AD user in azure storage file shares java SDK

### ISSUE THREAD

**Issue by niranjanbandi** [Azure/azure-sdk-for-java#10053]
I am using following statements.
CloudFileShare share = fileClient.getShareReference(storageShare);
CloudFileDirectory dir = share.getRootDirectoryReference();
dir.createIfNotExists();

I found below statement to set permissions. but didn't found to construct that string.
dir.setFilePermission("");

Is that proper way to reach my requirement. Or is there any other way to set permissions for specific AD user?

Thanks in advance.

**Comment by rickle-msft** [comment]
Hi, @niranjanbandi. Thanks for your question. That is the correct api to set permissions on a file depending on who the owner/group you want to set permissions for are. 

You can find more documentation [here](https://docs.microsoft.com/en-us/rest/api/storageservices/datalakestoragegen2/path/update) and then search for `x-ms-permission` and read the header description to understand how to construct the permissions string. You may also want to take a look at the x-ms-owner, x-ms-group, and x-ms-acl headers as well for more control over permissions. 

Please let me know if you have further questions.

**Comment by niranjanbandi** [comment]
> Hi, @niranjanbandi. Thanks for your question. That is the correct api to set permissions on a file depending on who the owner/group you want to set permissions for are.
> 
> You can find more documentation [here](https://docs.microsoft.com/en-us/rest/api/storageservices/datalakestoragegen2/path/update) and then search for `x-ms-permission` and read the header description to understand how to construct the permissions string. You may also want to take a look at the x-ms-owner, x-ms-group, and x-ms-acl headers as well for more control over permissions.
> 
> Please let me know if you have further questions.

Thanks for reply.

But I am able to view the uploaded file in https://portal.azure.com/ with other user.
Following is the code with constructed string.
dir.setFilePermission("user::rwx,user:niranjan.bandi@excelra.com:rwx,group::---,other::---,mask=rwx");

**Comment by niranjanbandi** [comment]
> > Hi, @niranjanbandi. Thanks for your question. That is the correct api to set permissions on a file depending on who the owner/group you want to set permissions for are.
> > You can find more documentation [here](https://docs.microsoft.com/en-us/rest/api/storageservices/datalakestoragegen2/path/update) and then search for `x-ms-permission` and read the header description to understand how to construct the permissions string. You may also want to take a look at the x-ms-owner, x-ms-group, and x-ms-acl headers as well for more control over permissions.
> > Please let me know if you have further questions.
> 
> Thanks for reply.
> 
> But I am able to view the uploaded file in https://portal.azure.com/ with other user.
> Following is the code with constructed string.
> dir.setFilePermission("user::rwx,user:[niranjan.bandi@excelra.com](mailto:niranjan.bandi@excelra.com):rwx,group::---,other::---,mask=rwx");

**Comment by niranjanbandi** [comment]
> > > Hi, @niranjanbandi. Thanks for your question. That is the correct api to set permissions on a file depending on who the owner/group you want to set permissions for are.
> > > You can find more documentation [here](https://docs.microsoft.com/en-us/rest/api/storageservices/datalakestoragegen2/path/update) and then search for `x-ms-permission` and read the header description to understand how to construct the permissions string. You may also want to take a look at the x-ms-owner, x-ms-group, and x-ms-acl headers as well for more control over permissions.
> > > Please let me know if you have further questions.
> > 
> > 
> > Thanks for reply.
> > But I am able to view the uploaded file in https://portal.azure.com/ with other user.
> > Following is the code with constructed string.
> > dir.setFilePermission("user::rwx,user:[niranjan.bandi@excelra.com](mailto:niranjan.bandi@excelra.com):rwx,group::---,other::---,mask=rwx");

I am using File Shares Storage Account. The document you have given it seems Data Lake Storage Gen2. Can you please help me for FileShares Storage Account.

**Comment by niranjanbandi** [comment]
> > > > Hi, @niranjanbandi. Thanks for your question. That is the correct api to set permissions on a file depending on who the owner/group you want to set permissions for are.
> > > > You can find more documentation [here](https://docs.microsoft.com/en-us/rest/api/storageservices/datalakestoragegen2/path/update) and then search for `x-ms-permission` and read the header description to understand how to construct the permissions string. You may also want to take a look at the x-ms-owner, x-ms-group, and x-ms-acl headers as well for more control over permissions.
> > > > Please let me know if you have further questions.
> > > 
> > > 
> > > Thanks for reply.
> > > But I am able to view the uploaded file in https://portal.azure.com/ with other user.
> > > Following is the code with constructed string.
> > > dir.setFilePermission("user::rwx,user:[niranjan.bandi@excelra.com](mailto:niranjan.bandi@excelra.com):rwx,group::---,other::---,mask=rwx");
> 
> I am using File Shares Storage Account. The document you have given it seems Data Lake Storage Gen2. Can you please help me for FileShares Storage Account.

I found few links related to set permission string in azure file shares account are followed.
https://docs.microsoft.com/en-us/rest/api/storageservices/create-file
https://docs.microsoft.com/en-us/rest/api/storageservices/get-permission

Are these correct links. If these are correct, Can you please help me that how to construct that string.

Thanks in Advance.

**Comment by rickle-msft** [comment]
@niranjanbandi I'm sorry. I think I completely misread some parts of your description, and I didn't realize we were talking about v8, which is again my bad. 

Yes those are the correct links for working with permissions in the file service. Creating a file with permissions like that is not currently supported in v8. If you want to be able to use that feature, the current guidance is to upgrade to v12.

**Comment by rickle-msft** [comment]
I am going to close this issue as there has been no response for some time after the last offered guidance.

Please feel free to reopen this issue if you need further support.
