### ISSUE TITLE
Readme content of Azure Key Vault Keys is unclear and inconsistencey

### ISSUE THREAD

**Issue by FredGao-new** [Azure/azure-sdk-for-java#10055]
1.
Section [Link](https://github.com/Azure/azure-sdk-for-java/tree/master/sdk/keyvault/azure-security-keyvault-keys#azure-key-vault-key-client-library-for-java)
![image](https://user-images.githubusercontent.com/52488926/78974061-48b5aa80-7b65-11ea-8eb3-11a366343242.png)
Suggestion:
Modify to "Azure Key Vault Keys client Library" 

2.
Section [Link](https://github.com/Azure/azure-sdk-for-java/tree/master/sdk/keyvault/azure-security-keyvault-keys#authenticate-the-client)
![image](https://user-images.githubusercontent.com/52488926/78974358-e90bcf00-7b65-11ea-995a-dba122a5b42e.png)
Suggestion:
Modify to "client secret"

3.
Section [Link](https://github.com/Azure/azure-sdk-for-java/tree/master/sdk/keyvault/azure-security-keyvault-keys#create-key-client)
![image](https://user-images.githubusercontent.com/52488926/78974486-35570f00-7b66-11ea-9ce6-cdf480b9db80.png)
Suggestion:
Add package import
`import com.azure.security.keyvault.keys.KeyClientBuilder;`

4.
Section [Link](https://github.com/Azure/azure-sdk-for-java/tree/master/sdk/keyvault/azure-security-keyvault-keys#create-cryptography-client)
![image](https://user-images.githubusercontent.com/52488926/78974702-a8f91c00-7b66-11ea-9487-af84216ad3a6.png)
Suggestion:
Add package import
`import com.azure.security.keyvault.keys.cryptography.CryptographyClientBuilder;`

5.
Section [Link](https://github.com/Azure/azure-sdk-for-java/tree/master/sdk/keyvault/azure-security-keyvault-keys#create-a-key)
![image](https://user-images.githubusercontent.com/52488926/78974853-03927800-7b67-11ea-83e7-b340277e3c9b.png)
Suggestion:
Remove unused package import
`import com.azure.security.keyvault.keys.models.Key;`
Add package import
`import com.azure.security.keyvault.keys.models.CreateEcKeyOptions;`
`import com.azure.security.keyvault.keys.models.CreateRsaKeyOptions;`
`import com.azure.security.keyvault.keys.models.KeyCurveName;`
`import com.azure.security.keyvault.keys.models.KeyVaultKey;`
`import com.azure.security.keyvault.keys.KeyClientBuilder;`

6.
Section [Link](https://github.com/Azure/azure-sdk-for-java/tree/master/sdk/keyvault/azure-security-keyvault-keys#delete-a-key)
![image](https://user-images.githubusercontent.com/52488926/78975261-da261c00-7b67-11ea-88b6-cb22a9ec8dd8.png)
Suggestion:
Add note
`// only works for SoftDelete Enabled Key Vault`

7.
Section [Link](https://github.com/Azure/azure-sdk-for-java/tree/master/sdk/keyvault/azure-security-keyvault-keys#create-a-key-asynchronously)
![image](https://user-images.githubusercontent.com/52488926/78975469-4274fd80-7b68-11ea-9936-f1dbe9ff243d.png)
Suggestion:
Remove unused package import
`import com.azure.security.keyvault.keys.models.Key;`
Add package import
`import com.azure.security.keyvault.keys.KeyClientBuilder;`
`import com.azure.security.keyvault.keys.models.CreateEcKeyOptions;`
`import com.azure.security.keyvault.keys.models.CreateRsaKeyOptions;`

8.
Section [Link](https://github.com/Azure/azure-sdk-for-java/tree/master/sdk/keyvault/azure-security-keyvault-keys#authenticate-the-client)
![image](https://user-images.githubusercontent.com/52488926/78979088-36d90500-7b6f-11ea-82c7-41859136d623.png)
Suggestion:
In the first line
Add permission
`update encrypt decrypt`
In the second line
Add permission
`update encrypt decrypt import wrapkey unwrapkey verify sign`

**Comment by jongio** [comment]
Please PR.

**Comment by vcolin7** [comment]
Left a bunch of comments on the PR. Also, I have more suggestions and corrections for this README but I'm not sure if I should create my own PR or add to the existing one, what do you think @joshfree?

**Comment by vcolin7** [comment]
Thanks for giving me access to the branch @FredGao-new, just pushed some more changes.

**Comment by vcolin7** [comment]
Waiting on Check Enforcer before merging.
