### ISSUE TITLE
Readme content of Azure Key Vault Certificates is unclear and inconsistencey

### ISSUE THREAD

**Issue by FredGao-new** [Azure/azure-sdk-for-java#10057]
1. 
Section [Link](https://github.com/Azure/azure-sdk-for-java/tree/master/sdk/keyvault/azure-security-keyvault-certificates#authenticate-the-client)
![image](https://user-images.githubusercontent.com/52488926/78977693-ab5e7480-7b6c-11ea-9c35-5620694554af.png)
Suggestion:
Modify to 
"client secret"
`DefaultAzureCredential`
"client secret"

2.
Section [Link](https://github.com/Azure/azure-sdk-for-java/tree/master/sdk/keyvault/azure-security-keyvault-certificates#createget-credentials)
![image](https://user-images.githubusercontent.com/52488926/78980548-34c47580-7b72-11ea-8fef-658ed24bcc5a.png)
Suggestion:
Add permission
`update`

3.
Section [Link](https://github.com/Azure/azure-sdk-for-java/tree/master/sdk/keyvault/azure-security-keyvault-certificates#create-certificate-client)
![image](https://user-images.githubusercontent.com/52488926/78980651-735a3000-7b72-11ea-8771-42156b21f64c.png)
Suggestion:
Add package import
`import com.azure.security.keyvault.certificates.CertificateClientBuilder;`

4.
Section [Link](https://github.com/Azure/azure-sdk-for-java/tree/master/sdk/keyvault/azure-security-keyvault-certificates#create-a-certificate)
![image](https://user-images.githubusercontent.com/52488926/78981055-36db0400-7b73-11ea-9e38-6cc28cf5cced.png)
Suggestion:
Change to the following package import
`import com.azure.core.util.polling.LongRunningOperationStatus; `
`import com.azure.core.util.polling.SyncPoller; `
`import com.azure.identity.DefaultAzureCredentialBuilder; `
`import com.azure.security.keyvault.certificates.CertificateClient; `
`import com.azure.security.keyvault.certificates.CertificateClientBuilder; `
`import com.azure.security.keyvault.certificates.models.CertificateOperation; `
`import com.azure.security.keyvault.certificates.models.CertificatePolicy; `
`import com.azure.security.keyvault.certificates.models.KeyVaultCertificate; `
`import com.azure.security.keyvault.certificates.models.KeyVaultCertificateWithPolicy; `

5.
Section [Link](https://github.com/Azure/azure-sdk-for-java/tree/master/sdk/keyvault/azure-security-keyvault-certificates#create-a-certificate-asynchronously)
![image](https://user-images.githubusercontent.com/52488926/78981245-a0f3a900-7b73-11ea-96e1-c392c5cb374f.png)
Suggestion:
Change to the following package import:
`import com.azure.identity.DefaultAzureCredentialBuilder; `
`import com.azure.security.keyvault.certificates.CertificateAsyncClient; `
`import com.azure.security.keyvault.certificates.models.CertificatePolicy; `

6.
Section [Link](https://github.com/Azure/azure-sdk-for-java/tree/master/sdk/keyvault/azure-security-keyvault-certificates#list-certificates-asynchronously)
![image](https://user-images.githubusercontent.com/52488926/78981371-e912cb80-7b73-11ea-9062-fabd1ebb81d7.png)
Suggestion:
Change to the following code snippet:
`certificateAsyncClient.getCertificate(certificateProperties.getName()) `

7.
Section [Link](https://github.com/Azure/azure-sdk-for-java/tree/master/sdk/keyvault/azure-security-keyvault-certificates#sync-api)
![image](https://user-images.githubusercontent.com/52488926/78981520-3000c100-7b74-11ea-9499-8294b5ee6cfa.png)
Suggestion:
Change "Key" to "Certificate"

8.
Section [Link](https://github.com/Azure/azure-sdk-for-java/tree/master/sdk/keyvault/azure-security-keyvault-certificates#async-api)
![image](https://user-images.githubusercontent.com/52488926/78981629-6c342180-7b74-11ea-8e13-084b4f6032f3.png)
Suggestion:
Change "Key" to "Certificate"

9.
Section [Link](https://github.com/Azure/azure-sdk-for-java/tree/master/sdk/keyvault/azure-security-keyvault-certificates#create-a-certificate)
![image](https://user-images.githubusercontent.com/52488926/78981756-b87f6180-7b74-11ea-8a40-cda427eda1e3.png)
Suggestion:
Change "Certificate" to "certificate"
Change "key vault" to "Azure Key Vault"

10.
Section [Link](https://github.com/Azure/azure-sdk-for-java/tree/master/sdk/keyvault/azure-security-keyvault-certificates#create-a-certificate-asynchronously)
![image](https://user-images.githubusercontent.com/52488926/78981911-1613ae00-7b75-11ea-8499-725eba9b9e4e.png)
Suggestion:
Change "Certificate" to "certificate"
Change "key vault" to "Azure Key Vault"

**Comment by jongio** [comment]
Please PR.
