### ISSUE TITLE
Readme content of Azure Key Vault Secrets is unclear and inconsistencey

### ISSUE THREAD

**Issue by Luyunmt** [Azure/azure-sdk-for-java#10054]
1
Section [Link](https://github.com/Azure/azure-sdk-for-java/tree/master/sdk/keyvault/azure-security-keyvault-secrets#azure-key-vault-secret-client-library-for-java)
![image](https://user-images.githubusercontent.com/53427149/78973331-455cf780-7b42-11ea-9fe3-3da494a635ec.png)

Comments: Correct it as Azure Key Vault Secrets client library 

2
Section [Link](https://github.com/Azure/azure-sdk-for-java/tree/master/sdk/keyvault/azure-security-keyvault-secrets#secret)
![image](https://user-images.githubusercontent.com/53427149/78978819-2a43b500-7b4d-11ea-91f7-4ba68324ee1e.png)

Comments: Correct it as Azure Key Vault

3
Section [Link](https://github.com/Azure/azure-sdk-for-java/tree/master/sdk/keyvault/azure-security-keyvault-secrets#delete-a-secret)
![image](https://user-images.githubusercontent.com/53427149/78974562-d765ff80-7b44-11ea-9ae9-72aa201cf311.png)

Comments: Add comments: only works for SoftDelete Enabled Key Vault.

4
Section [Link](https://github.com/Azure/azure-sdk-for-java/tree/master/sdk/keyvault/azure-security-keyvault-secrets#create-a-secret)
![image](https://user-images.githubusercontent.com/53427149/78974720-2b70e400-7b45-11ea-8e14-828f9437585b.png)

Comments: Add import com.azure.security.keyvault.secrets.models.KeyVaultSecret; 

5
Section [Link](https://github.com/Azure/azure-sdk-for-java/tree/master/sdk/keyvault/azure-security-keyvault-secrets#createget-credentials)
![image](https://user-images.githubusercontent.com/53427149/78974873-873b6d00-7b45-11ea-9bef-fb6453e972ce.png)

Comments: Add Id

6
Section [Link](https://github.com/Azure/azure-sdk-for-java/tree/master/sdk/keyvault/azure-security-keyvault-secrets#create-a-secret)
![image](https://user-images.githubusercontent.com/53427149/78975132-0892ff80-7b46-11ea-9942-08bc66d41251.png)

Comments: Secret to secret and Correct it as Azure Key Vault

**Comment by jongio** [comment]
Also add space around parenthesis: AZURE_CLIENT_SECRET (password)

Please PR.

**Comment by g2vinay** [comment]
@vcolin7, 
can you ensure this is fixed in the ongoing Secrets README update PR ?

**Comment by vcolin7** [comment]
@g2vinay I'm on it, already made some suggestions on the PR associated with this issue.
