### ISSUE TITLE
Java aggregate-reports are failing after the removal of the site:site site:stage

### ISSUE THREAD

**Issue by JimSuplizio** [Azure/azure-sdk-for-java#10087]
The site:stage goal from the [maven-site-plugin](http://maven.apache.org/plugins/maven-site-plugin/usage.html) is what was creating the target/staging directory that 'Copy reports to artifact staging' step [eng/pipelines/aggregate-reports.yml](https://github.com/Azure/azure-sdk-for-java/blob/master/eng/pipelines/aggregate-reports.yml#L55) is trying to copy. Also, it's unclear with the current set of changes from https://github.com/Azure/azure-sdk-for-java/pull/9435 if we're producing the same artifacts.

**Comment by mitchdenny** [comment]
Thanks Jim.

**Comment by mitchdenny** [comment]
This will be fixed when this PR merges: https://github.com/Azure/azure-sdk-for-java/pull/10220
