### ISSUE TITLE
[BUG] Clarify Error Message on Identity Creation

### ISSUE THREAD

**Issue by mrm9084** [Azure/azure-sdk-for-java#10136]
**Describe the bug**
It is hard to tell the difference between a connection timeout between creating a System Assigned Identity to authenticate with and a timeout connecting with the service.

**To Reproduce**

1. Create a SecretClientBuilder
2. Add a ManagedIdentityCredential
3. Run locally instead of from Azure
4. The stack trace is hard to point at what was the issue.

**Expected behavior**
Someone who isn't super familiar with Azure should be able to understand what went wrong.

**Comment by g2vinay** [comment]
Thanks @mrm9084 for posting this issue.
Investigating this and will post updates here.

**Comment by g2vinay** [comment]
@mrm9084, This issue has been resolved in the latest stable release of azure-identity:1.1.2

If the connection to Managed Identity times out, you'll see an error with the following message, indicating that the credential is unavailable for use as the connection timed out.
```
ManagedIdentityCredential authentication unavailable. Connection to IMDS endpoint cannot be established, connect timed out.
```

Let us know, if you've any further questions, or would like to reopen this issue.
