### ISSUE TITLE
ResourceUtils relies on case of "securityGroups", fails to extract value

### ISSUE THREAD

**Issue by grnadav** [Azure/azure-sdk-for-java#1014]
Hello

When using ResourceUtils to extract resource-group name from the resource id (explicitly or when other classes rely on it to do so), it fails to do so for some resources where their id has "resourcegroups" instead of "resourceGroups" , e.g. for a (real) NSG in my account:
/subscriptions/<redacted-subscription-id-here>/resourcegroups/Default-WestEurope/providers/Microsoft.Network/networkSecurityGroups/nsg-to-delete-10

Relevant code here:
https://github.com/Azure/azure-sdk-for-java/blame/master/azure-mgmt-resources/src/main/java/com/microsoft/azure/management/resources/fluentcore/arm/ResourceUtils.java#L24

Thanks

**Comment by grnadav** [comment]
Just noting that none of the above "mentions" detected by Github are references to this issue, but to another (?) with same id.
This issue is still unhandled...

**Comment by jianghaolu** [comment]
@grnadav yeah those commits are not helpful from the subtree merges. 
This is a valid issue and will be addressed in an upcoming pull request.

**Comment by jianghaolu** [comment]
Fixed in beta3.
