### ISSUE TITLE
Is there a way to encrypt the VM useraccount password passed during Azure provisioning

### ISSUE THREAD

**Issue by nihalnaik25** [Azure/azure-sdk-for-java#1016]
Is there a way to encrypt the VM useraccount password passed during Azure provisioning in Azure API understandable format

As of now , we need to pass password in plain text for password to get set correctly which is security issue

I need to know is there is some Azure Beta1 API available for password encryption

**Comment by anuchandy** [comment]
Your password will be sent over https so payload itself is encrypted, later if we do a VM GET password will not be returned. Looking at the documentation, i don't see azure support doing additional encryption of password on PUT.
