### ISSUE TITLE
Readme content of Azure Identity is unclear and inconsistencey

### ISSUE THREAD

**Issue by FredGao-new** [Azure/azure-sdk-for-java#10173]
1.
Section [Link](https://github.com/Azure/azure-sdk-for-java/tree/master/sdk/identity/azure-identity#azure-identity-shared-library-for-java)
![image](https://user-images.githubusercontent.com/52488926/79203268-e7584900-7e8e-11ea-9684-dedb5f21e0fb.png)
Suggestion:
Azure Identity client Library

2.
Section [Link](https://github.com/Azure/azure-sdk-for-java/tree/master/sdk/identity/azure-identity#credentials)
![image](https://user-images.githubusercontent.com/52488926/79203429-21c1e600-7e8f-11ea-87fe-d163e2b88173.png)
Suggestion:
Space before "Azure Identity"

**Comment by jongio** [comment]
I think we can remove "shared" and not replace with client.  @g2vinay - Can you review?

**Comment by joshfree** [comment]
@FredGao-new if you'd like, please send a PR and tag @g2vinay and @jianghaolu for review.  Thank you so much!

**Comment by jianghaolu** [comment]
Before we make any changes, @alzimmermsft I believe this was part of a bigger README improvement effort? I believe there's a reason why we added the "shared" keyword?

**Comment by jianghaolu** [comment]
This was changed as part of this PR: https://github.com/Azure/azure-sdk-for-java/pull/9930

**Comment by alzimmermsft** [comment]
@jianghaolu, yes this change was made in response to a discussion I had with our technical writers. The discussion was targeted at the inflexibility of only allow for `client library` to be used, this is more restrictive in Java where we have optional implementation libraries we release. Outcome from the discussion was allowance to also use `plugin library` and `shared library`, where `plugin` is for an interface implementation (such as Netty HTTP) and `shared` is for common logic (such as Azure Core). In the mentioned PR it was decided to move Identity away from `client library` as it was felt it wasn't a true client and felt more like a common logic library, hence the decision to use `shared`; if we want to revert this change it would be trivial.

@jongio @joshfree

**Comment by joshfree** [comment]
@g2vinay can you please address this as part of next week's out-of-band Identity preview release?

**Comment by Melanie-Ma** [comment]
@jongio - Hi, If using `shared` in the `README ` title for java, should it be consistent with JS & .NET & Python?
Javascript:
![image](https://user-images.githubusercontent.com/64007802/88785820-433ba900-d1c4-11ea-8087-226fbca341c2.png)
.NET:
![image](https://user-images.githubusercontent.com/64007802/88785850-4fc00180-d1c4-11ea-9cc7-863f95bd9e90.png)
Python:
![image](https://user-images.githubusercontent.com/64007802/88785883-5d758700-d1c4-11ea-83c7-627c98bd2572.png)

**Comment by tzhanl** [comment]
Close for PR merged.
