### ISSUE TITLE
Readme content of Event Hub is unclear and inconsistencey

### ISSUE THREAD

**Issue by Luyunmt** [Azure/azure-sdk-for-java#10174]
1
Section [Link](https://github.com/Azure/azure-sdk-for-java/tree/master/sdk/eventhubs/azure-messaging-eventhubs#consume-events-from-an-event-hub-partition)
![image](https://user-images.githubusercontent.com/53427149/79205346-5ffbdd00-7e70-11ea-97f9-825b577c71a1.png)

Comments: Add Note : You should add "System.in.read()" or "Thread.Sleep()" after the function calls in the main class/thread to allow Async functions/operations to execute and finish before the main application/thread exits. 

2
Section [Link](https://github.com/Azure/azure-sdk-for-java/tree/master/sdk/eventhubs/azure-messaging-eventhubs#consume-events-from-an-event-hub-partition)
![image](https://user-images.githubusercontent.com/53427149/79204479-2f677380-7e6f-11ea-9de9-fbc9a3ded252.png)

Comments: Add comments： //{@link com.azure.messaging.eventhubs.models.EventPosition} is Position within the Event Hub partition to begin consuming events. 

3
Section [Link](https://github.com/Azure/azure-sdk-for-java/tree/master/sdk/eventhubs/azure-messaging-eventhubs#consume-events-using-an-eventprocessorclient)
![image](https://user-images.githubusercontent.com/53427149/79204758-a00e9000-7e6f-11ea-87c1-0cd74c257d19.png)

Comments: Change class name InMemoryCheckpointStore to SampleCheckpointStore.
InMemoryCheckpointStore looks like a class name of SDK, makes people confusing while people need to create a class. SampleCheckpointStore would not have this problem.

**Comment by jongio** [comment]
@ramya-rao-a - Can you please review?

**Comment by ramya-rao-a** [comment]
Assigned to @srnagar, the Java repo in the EH SDK crew
