### ISSUE TITLE
Discussion: How user gets access to the created related resources

### ISSUE THREAD

**Issue by anuchandy** [Azure/azure-sdk-for-java#1018]
User can compose a set of creatables. We allow user to provide them explicitly `e.g. VM::withNewStorageAccount(Creatable<StorageAccount> creatable)` or specify creatable implicltiy `e.g. VM::withNewStorageAccount(string name)`.

When user call `Create` we return only the top-level resource. e.g. VM.Create(..) return `VirtualMachine`. Sometimes user might want to access the other created resources that composes VM, as of now there is no way user can get them. This is useful if user want to create another resource and want to use the previously created resource via `withExisting*****` wither.

If we want to address this, one thought is to let `Resource` interface expose two methods 

`Resource createdRelatedResource(string key)`
`List<Resource> createdRelatedResources()`

This can be implemented in `CreatableImpl` so all resources get it free.

With this user can do:

``` java

Creatable<StorageAccount> storageCreatable = storageAccounts().define()....

Creatable<VirtualMachine> vmCreatable = virtualMachines()
  .define()
  ...
  .withNewStorageAccount(storageCreatable);

VirtualMachine vm = vmCreatable.Create();

// Gets the created storage account
StorageAccount createdStorageAccount = vm.createdRelatedReosurce(storageCreatable.key())

// update the storage account
createdStorageAccount.update()
   ..
   .apply();

createdStorageAccount.regenerateKeys();

```

**Comment by anuchandy** [comment]
Or another interface 'SupportGettingRelatedCreatedResource' that exposes above two methods.

**Comment by anuchandy** [comment]
Discussed this in the weekly sync up.

We will prototype this by adding an overload for create() that takes a list `List<Reosurce`> from the user and create will populate it with all created resources when it returns. 

We don't want individual resource interfaces (e.g. `StorageAccount`) to expose createdRelatedResource or createdRelatedResources.

**Comment by martinsawicki** [comment]
shipped support for this scenario a while back so closing
