### ISSUE TITLE
[QUERY] Deleting a blob in Java SDK v12

### ISSUE THREAD

**Issue by srideviaishwariya** [Azure/azure-sdk-for-java#10180]
**Query/Question**
Its unclear how to delete a single blob from a given container. 

What is the purpose of `blobItem.setDeleted(true);` does this queue the blob for deletion? when will the actual deletion happen? 

***Why is this not a Bug or a feature Request?***
The older SDK supported delete on the blob level, looking for something similar in SDK 12

**Setup (please complete the following information if applicable):**
OS: Windows 10
IDE : IntelliJ IDEA
Azure Storage Blob SDK v12

**Comment by rickle-msft** [comment]
@srideviaishwariya Thank you for your question. Your confusion is understandable. The correct means of deleting a blob are actually to use the name on the BlobItem to construct a BlobClient pointing to said blob. You can then use that BlobClient instance to call deleteBlob() which will issue a network request to delete the resource.

The deleted property on a BlobItem is actually just a field which tells you whether or not the blob has been deleted under a soft delete policy and therefore may be "undeleted". The getter is really the only thing useful to you as the setter is only used for deserialization and unfortunately leaks into the public API. Setting that value won't actually have any effect on the blob, though.

**Comment by srideviaishwariya** [comment]
Thanks.
