### ISSUE TITLE
Cleanup - Remaining "Legacy" Packages

### ISSUE THREAD

**Issue by scbedd** [Azure/azure-sdk-for-java#10186]
We recently moved the entire [Azure/azure-docs-sdk-java](https://github.com/azure/azure-docs-sdk-java) to Maven based. 

However, there is still a set of packages that we need to finish migrating. We are in a _fine_ state for repeatability and manual update, but we'd prefer to be entirely done.

Some of these "un-migratable" packages are `AAR` instead of `JAR`, as they are Android packages. That will require CI work to resolve. Ann Meng is actively going after those.

For the rest, it will be a case of reaching out to owners and having them correct their deployed snippets.

There is has an excel with the checklist of packages. Check for attached .xlsx under `Azure SDK - Engineering System` OneNote ->  `Testing` -> `Remaining "Legacy" Java Packages` -> find `Paths.xlsx` on the page.

**Comment by sima-zhu** [comment]
Finished the first round of cleaning. Keep working on a more maintainable solution. Closed this one and will follow with another issue.
