### ISSUE TITLE
How to validate connection which have Object level access only with "azure-storage-5.5.0"

### ISSUE THREAD

**Issue by abhikt48** [Azure/azure-sdk-for-java#10181]
How to validate connection for **Container** And **Object** level access with "azure-storage-5.5.0" ?

```
CloudBlobClient cloudBlobClient = new CloudBlobClient(new URI(sharedAccessSignature));
//throws StorageException for Invalid Credential
if (cloudBlobClient.downloadServiceProperties() != null) { 
	//Connection Success
}else{
	//Failed
}
```

At this moment we are validating connection with the help of _**downloadServiceProperties()**_ operation, but this operation require **Service** level access. 

Our application is in prod from couple of years, that's why we don't want use latest SDK due to backward compatibility.

RootCause - We got a requirement to access blob with  **Container** And **Object** level access only. So we can't verify connection without performing any lower level operation.

I tried to find alternate solution with below code, but it requires service level access only.

```
Iterable<CloudBlobContainer> listContainers = cloudBlobClient.listContainers();
		for(CloudBlobContainer cloudBlobContainer : listContainers) {
			System.out.println("** cloudBlobContainer **" + cloudBlobContainer);
		}
```

Could you please provide any alternate way to check connection status. Please let me know if you need any information.

***Setup (please complete the following information if applicable):**
 - OS: Windows, Linux
 - azure-storage-5.5.0
 - Java8
 
 Refer - below screen shot for access rights.
<img width="797" alt="resource_types" src="https://user-images.githubusercontent.com/22897837/79242965-e9a9ab80-7e6c-11ea-873e-2e2cb17a732f.PNG">

**Comment by rickle-msft** [comment]
@abhikt48 Thank you for your question. Typically the simplest way to ensure a valid connection is to perform a getProperties call on the object you're trying to connect to. It's light weight and simple and only requires read permissions. Please let me know if you need further support here.

**Comment by abhikt48** [comment]
@rickle-msft  Thanks a lot for quick response. _**CloudBlobClient**_ does not have **getProperties** operation in **azure-storage-5.5.0** library. 

Can you please tell me, how can i access **getProperties**  operation and from which library?

<img width="1146" alt="CloudBlobClient_Operations" src="https://user-images.githubusercontent.com/22897837/79254769-1d8ccd00-7e7d-11ea-8b76-01d989a9c8be.png">

**Comment by rickle-msft** [comment]
In the version you're using, you'll need to create a CloudBlobContainer or CloudBlob object in order to call get properties. Because your sas token provides object or container level access, you won't be able to perform any operations on the account itself (which is what CloudBlobClient represents), hence the need for a container or blob to check. Depending on your application architecture, you may be able to do this check once with a single container or blob, or you may need to do this check each time you create a new reference to a remote object.

**Comment by abhikt48** [comment]
@rachel-msft  - Thanks for details 👍
