### ISSUE TITLE
[BUG] listBlobsByHierarchy incorrect behavior in SDK v12 

### ISSUE THREAD

**Issue by srideviaishwariya** [Azure/azure-sdk-for-java#10190]
**Describe the bug**
listBlobsByHierarchy lists all the blobs and prefixes (directories) which is not under the given prefix (directory).

***Exception or Stack Trace***
Add the exception log and stack trace if available

**To Reproduce**
Create a new Blob with the SDK
Add Metadata to the new Blob
Retrieve the Blob and try to read the metadata using listBlobsByHierarchy

***Code Snippet***
`for(String directory: directoryList){
             System.out.printf("\n ===========>> Directory String = %s", directory);
            ListBlobsOptions options = new ListBlobsOptions().setDetails(new BlobListDetails().setRetrieveMetadata(true));
            for (BlobItem blobItem : containerClient.listBlobsByHierarchy(directory,options,null)) {
                System.out.printf("\nDirectory = %s, prefix = %b",blobItem.getName(),blobItem.isPrefix());
             }
        }`

**Actual behavior**
 ===========>> Directory String = foobar/
Directory = dev24/1586892019856_1.js, prefix = false
Directory = dev24/1586892024303_1.js, prefix = false
Directory = dev25/1586887505622_1.js, prefix = false
Directory = dev26/1586887512175_1.js, prefix = false
Directory = dev26/1586887547791_1.js, prefix = false

 ===========>> Directory String = dev24/
Directory = dev25/1586887505622_1.js, prefix = false
Directory = dev26/1586887512175_1.js, prefix = false
Directory = dev26/1586887547791_1.js, prefix = false
Directory = dev24/, prefix = true

 ===========>> Directory String = dev25/
Directory = dev24/1586892019856_1.js, prefix = false
Directory = dev24/1586892024303_1.js, prefix = false
Directory = dev26/1586887512175_1.js, prefix = false
Directory = dev26/1586887547791_1.js, prefix = false
Directory = dev25/, prefix = true

 ===========>> Directory String = dev26/
Directory = dev24/1586892019856_1.js, prefix = false
Directory = dev24/1586892024303_1.js, prefix = false
Directory = dev25/1586887505622_1.js, prefix = false
Directory = dev26/, prefix = true

**Expected behavior**
 ===========>> Directory String = foobar/

 ===========>> Directory String = dev24/
Directory = dev24/1586892019856_1.js, prefix = false
Directory = dev24/1586892024303_1.js, prefix = false
Directory = dev24/, prefix = true

 ===========>> Directory String = dev25/
Directory = dev25/1586887505622_1.js, prefix = false
Directory = dev25/, prefix = true

 ===========>> Directory String = dev26/
Directory = dev26/1586887512175_1.js, prefix = false
Directory = dev26/1586887547791_1.js, prefix = false
Directory = dev26/, prefix = true

**Screenshots**

**Setup (please complete the following information):**
OS: Windows 10
IDE : IntelliJ IDEA
Azure Storage Blob SDK v12

**Comment by rickle-msft** [comment]
@srideviaishwariya Thank you for posting your question. There's a subtle detail here that is easy to get tripped up on. There are two overloads of `listBlobsByHierarchy`. The first one takes the name of the directory you want to list and gives you all blobs and directories immediately under that directory. The second one, which you are using, takes the _delimiter_ as the first argument and then you have to include the prefix in the `ListBlobOptions`. This is why you are seeing strange results. If you update your options to set the directory you want to list under and then pass "/" as your delimiter, you should see correct results. 

Please let me know if this doesn't resolve your issue.

**Comment by srideviaishwariya** [comment]
Thanks for the help. Would be great to have some more sample for the V12 SDK.
