### ISSUE TITLE
[BUG] Discriminator with "." in json is not handled correctly with FlatteningSerializer

### ISSUE THREAD

**Issue by weidongxu-microsoft** [Azure/azure-sdk-for-java#10217]
**Describe the bug**
If a discriminator value with "." e.g. `odata.type` from monitor, and one of the class using it has `@JsonFlatten` annotation, the FlatteningSerializer would break that ".".

If I instead escape it as `property = "odata\\.type"`. The serialization is good, but de-serialization would then fail (subclass not serialized correctly).

***Exception or Stack Trace***
Add the exception log and stack trace if available

**To Reproduce**
```
    @JsonFlatten
    @Fluent
    public static class Foo {
        @JsonProperty(value = "properties.criteria", required = true)
        private MetricAlertCriteria criteria;

        public MetricAlertCriteria criteria() {
            return this.criteria;
        }

        public Foo withCriteria(MetricAlertCriteria criteria) {
            this.criteria = criteria;
            return this;
        }
    }

    @JsonTypeInfo(use = JsonTypeInfo.Id.NAME, include = JsonTypeInfo.As.PROPERTY, property = "odata.type", defaultImpl = com.azure.management.monitor.MetricAlertCriteria.class)
    @JsonTypeName("MetricAlertCriteria")
    @JsonSubTypes({
        @JsonSubTypes.Type(name = "Microsoft.Azure.Monitor.SingleResourceMultipleMetricCriteria", value = MetricAlertSingleResourceMultipleMetricCriteria.class),
        @JsonSubTypes.Type(name = "Microsoft.Azure.Monitor.MultipleResourceMultipleMetricCriteria", value = MetricAlertMultipleResourceMultipleMetricCriteria.class)
    })
    @Fluent
    public static class MetricAlertCriteria {

    }

    @JsonTypeInfo(use = JsonTypeInfo.Id.NAME, include = JsonTypeInfo.As.PROPERTY, property = "odata.type")
    @JsonTypeName("Microsoft.Azure.Monitor.SingleResourceMultipleMetricCriteria")
    @Fluent
    public static final class MetricAlertSingleResourceMultipleMetricCriteria extends MetricAlertCriteria {

    }

    @Test
    public void testSerialization() throws Exception {
        SerializerAdapter adapter = new AzureJacksonAdapter();

        Foo foo = new Foo();
        foo.withCriteria(new MetricAlertSingleResourceMultipleMetricCriteria());
        String fooJson = adapter.serialize(foo, SerializerEncoding.JSON);
        Assertions.assertTrue(fooJson.contains("odata.type"));
    }
```

Produce
```
{"properties":{"criteria":{"odata":{"type":"Microsoft.Azure.Monitor.SingleResourceMultipleMetricCriteria"}}}}
```

***Code Snippet***
Add the code snippet that causes the issue.

**Expected behavior**
Should be
```
{"properties":{"criteria":{"odata.type":"Microsoft.Azure.Monitor.SingleResourceMultipleMetricCriteria"}}}
```

**Screenshots**

**Setup (please complete the following information):**
 - OS : Windows
 - IDE : IntelliJ
 - Version of the Library used : com.azure.azure-core 1.4.0-beta.1

**Additional context**
Relate to but not same as https://github.com/Azure/azure-sdk-for-java/issues/8372

**Information Checklist**
Kindly make sure that you have added all the following information above and checkoff the required fields otherwise we will treat the issuer as an incomplete report
- [x] Bug Description Added
- [x] Repro Steps Added
- [x] Setup information Added

**Comment by joshfree** [comment]
@anuchandy could you please assist here?

**Comment by anuchandy** [comment]
@weidongxu-microsoft - you're right that any dot in a discriminator property name in typeId has to be escaped e.g. "swagger `odata.type`" to "java `odata\\.type`.

I will validate the deserialization and sent out a PR. Thank you for sharing the repro code!

**Comment by anuchandy** [comment]
@weidongxu-microsoft - The PR is opened, I'm running a few more tests. 

Please make sure the following constraints are met when using this version:

1. The dot "." in the discriminator name must be escaped e.g. "swagger `odata.type`" to "java `odata\\.type`
2. If a type `Foo` is annotated with `JsonTypeInfo` with discriminator containing dot then we also need to apply `JsonFlatten` annotation to the same type `Foo`. 

Please refer the tests in the PR for the usage.

**Comment by weidongxu-microsoft** [comment]
Fixed by https://github.com/Azure/azure-sdk-for-java/pull/10310

Verified on latest 1.5.0-beta.1
