### ISSUE TITLE
Test Gap: FileNames, URIs, Resources with non-enu unicode character ranges

### ISSUE THREAD

**Issue by joshfree** [Azure/azure-sdk-for-java#10228]
Tracking Issue: We should increase azure-core test coverage for CJK and additional non-ENU unicode character ranges

Related reported issue https://github.com/Azure/azure-sdk-for-java/issues/10216

Various test resources for reference

- http://www.madore.org/~david/misc/unitest/
- https://www.ltg.ed.ac.uk/~richard/unicode-sample-3-2.html
- https://jrgraphix.net/research/unicode_blocks.php
- (CJK in Unicode 13.0) http://www.unicode.org/versions/Unicode13.0.0/ch18.pdf

**Comment by aComanche** [comment]
Hey @joshfree, do you mind if I work on this?

**Comment by alzimmermsft** [comment]
Hi @aComanche, I'll assign you as the issue owner if you still want to work on this item.

**Comment by aComanche** [comment]
@alzimmermsft Yes Alan, I would like to work on it
