### ISSUE TITLE
Event hub consumer implementation

### ISSUE THREAD

**Issue by ughorai** [Azure/azure-sdk-for-java#10222]
**Query/Question**
I am using azure event hub SDK version 2.2.0 and event-hub-eh version 2.4.0. while running the consumer some time I get invalid offset ERROR, some time get connection time out error.
--- azure-eventhubs 2.2.0
-- azure-eventhubs-eph 2.4.0
-- Java 1.7
Is it due to using those older version?

***Why is this not a Bug or a feature Request?***
A clear explanation of why is this not a bug or a feature request?

**Setup (please complete the following information if applicable):**
 - IDE : [e.g. IntelliJ]
 - Version of the Library used
 
 **Information Checklist**
 Kindly make sure that you have added all the following information above and checkoff the required fields otherwise we will treat the issuer as an incomplete report
- [ ] Query Added
- [ ] Setup information Added

**Comment by joshfree** [comment]
@srnagar can you please follow up with @ughorai on the question above?

**Comment by srnagar** [comment]
@ughorai Are you still having this issue? If so, could you please provide a repro sample for us to check.
