### ISSUE TITLE
Create multiple virtual machines at a time

### ISSUE THREAD

**Issue by grinkarthi** [Azure/azure-sdk-for-java#1024]
Azure SDK will be more flexible if the following features were added,
**Features to be added:** 
1. Create multiple virtual machines at a time by getting the number of instances.
2. This virtual machines should have same features.

**Comment by grinkarthi** [comment]
@anuchandy Thanx for your response
If we create virtual machines by using loop it takes more time.
We are suppose to create 100 VMSS at a time. Just think if we use loop to create virtual machines , then how much time we need to spend for its completion.

**Comment by martinsawicki** [comment]
note that the point of Anu's suggestion is that you only *define* your VMs in a loop (which takes no time, since there is no communication with the cloud), and then call that new `VirtualMachines#create()`, which takes your *definitions* as an array and parallelize their creation internally, with asynch.

**Comment by grinkarthi** [comment]
@anuchandy when i tried the above code it shows the following errors,
1.ResourceGroup.DefinitionStages cannot be resolved to a type
2.The method create(creatableVirtualMachines.toArray(new VirtualMachine.DefinitionStages.WithCreate[vmCount])) is undefined for the 
 type VirtualMachines

**Comment by jianghaolu** [comment]
Which version are you using @grinkarthi ?

**Comment by martinsawicki** [comment]
with VMSS support and further improvements in VirtualMachines.create(), i think the core need here has been addressed.
