### ISSUE TITLE
How to Get Started Contributing to Azure SDK for Java?

### ISSUE THREAD

**Issue by balajimurugesan2016** [Azure/azure-sdk-for-java#10255]
I'm new to the opensource world. 
How do I start understanding how to use the Azure SDK for Java. I read the docs. I'm unable to find a starting point.  I'm willing to contribute to the project. Please help.

**** CONTRIBUTING QUESTIONS *****

**Comment by rickle-msft** [comment]
@balajimurugesan2016 Thank you for your interest in this project! I think your starting part will largely depend on what sort of application you'd like to write. Once you determine what application or service you'd like to build, we can help point you at which sdks in this repo will be most useful for you.

**Comment by joshfree** [comment]
Hi @balajimurugesan2016 thanks for posting the question.

Here are some getting started guides with how to use Azure SDK for Java.

- https://docs.microsoft.com/en-us/azure/java/java-azure-tools
- https://docs.microsoft.com/en-us/azure/app-service/containers/quickstart-java?toc=/azure/java/toc.json&bc=/azure/java/breadcrumb/toc.json
- https://aka.ms/azuresdk
- https://azure.github.io/azure-sdk-for-java/

Additionally, you asked about contributing to the azure/azure-sdk-for-java project.  The contributing.md is a good place to start along with the Wiki.  A good first step would be to fork, clone, and then build the repo sources locally. 

- https://github.com/Azure/azure-sdk-for-java/blob/master/CONTRIBUTING.md
- https://github.com/Azure/azure-sdk-for-java/wiki

 Issues labeled `up for grabs` are good first issues for new contributors - there's currently more than 30 up for grabs issues.  Is there a specific area of Azure SDK for Java that you're most interested in?  Which SDKs are you using in your own projects day to day?

- https://github.com/azure/azure-sdk-for-java/issues?q=is%3Aissue+is%3Aopen+label%3A%22up+for+grabs%22

**Comment by balajimurugesan2016** [comment]
Hi Guys,
Thanks for your swift reply. I would like to explore more on the Virtual machine service in Microsoft azure. Where should I start with? at least with respect to programs running them.

**Comment by balajimurugesan2016** [comment]
I could also contribute to increasing the unit test coverage of the services. Is there anyway I can  run the application/service locally in linux and test?

**Comment by srnagar** [comment]
@balajimurugesan2016 we have curated some tasks that are a good starting point for contributors. All these tasks are labeled as "Up for grabs". If you are interested in any of these tasks, please let us know and we can assign the task to you.

You can find these tasks here - https://github.com/Azure/azure-sdk-for-java/issues?q=is%3Aopen+is%3Aissue+label%3A%22up+for+grabs%22

**Comment by joshfree** [comment]
Hi @balajimurugesan2016 please let us know if you have any other questions regarding getting started.  It might be best to choose one of the `up for grabs` issues I linked above and then comment on that specific issue that you're interested in; and we can go from there. 😄 

Since this issue hasn't had activity for three months, I'm closing it as resolved now.  Please feel free to reactivate or open a new issue as needed too.  Thank you again!
