### ISSUE TITLE
Search: Proposed model and property renames

### ISSUE THREAD

**Issue by heaths** [Azure/azure-sdk-for-java#10272]
This is a list of proposed changes for models and properties. Some of these changes may have already been done in one or more languages, but I wanted to start an issue to track all of them and, when agreed, will replicate across the different language repos.

Model | Property | Proposal | Notes
--- | --- | --- | ---
Analyzer | | LexicalAnalyzer
AnalyzerName | | LexicalAnalyzerName
AzureActiveDirectoryApplicationCredentials | | *remove* | Just uplift ApplicationId and ApplicationSecret to SearchIndexEncryptionKey
DataContainer | | SearchIndexerDataContainer
DataSource | | SearchIndexerDataSource
DataSource | Credentials | ConnectionString (string) | See notes below for DataSourceCredentials
DataSourceCredentials | | *remove* | Just uplift ConnectionString to SearchDataSource
DataSourceType | | SearchIndexerDataSourceType
DataType | | SearchFieldDataType
EncryptionKey | | SearchResourceEncryptionKey
EncryptionKey | KeyVaultUri | VaultUri | Corresponds with Key Vault naming.
EncryptionKey | KeyVaultName | KeyName | Corresponds with Key Vault naming.
EncryptionKey | KeyVaultVersion | KeyVersion | Corresponds with Key Vault naming.
Field | | SearchField
FieldBase | | SearchFieldTemplate | Probably specific to .NET - base class for convenience classes.
Index | | SearchIndex
Indexer | | SearchIndexer
IndexerExecutionInfo | | SearchIndexerStatus | Corresponds to SearchServiceClient.GetIndexerStatus
IndexerLimits | | SearchIndexerLimits
ItemError | | SearchIndexerError
ItemWarning | | SearchIndexerWarning
LengthTokenFilter | Max | LengthTokenFilter.MaxLength
LengthTokenFilter | Min | LengthTokenFilter.MinLength
Skill | | SearchIndexerSkill
Skillset | | SearchIndexerSkillset
StandardAnalyzer | | LuceneStandardAnalyzer
StandardTokenizer | | LuceneStandardTokenizer
StandardTokenizerV2 | | LuceneStandardTokenizerV2
TokenInfo | | AnalyzedTokenInfo
Tokenizer | | LexicalTokenizer
TokenizerName | | LexicalTokenizerName

On a related note, other models should be hidden and their sole collection properties uplifted as return values. Names below reflect proposed renames above.

Method | Model | Return
--- | --- | ---
SearchServiceClient.ListDataSources | ListDataSourcesResult | DataSource[]
SearchServiceClient.ListIndexers | ListIndexersResult | SearchIndexer[]
SearchServiceClient.ListIndexes | ListIndexesResult | SearchIndex[]
SearchServiceClient.ListSkillsets | ListSkillsetsResult | SearchSkillset[]
SearchServiceClient.ListSynonymMaps | ListSynonymMapsResult | SynonymMap[]

**Comment by heaths** [comment]
Added `StandardTokenizerV2` -> `LuceneStandardTokenizerV2`

**Comment by sima-zhu** [comment]
Model | Property | Proposal | Notes
--- | --- | --- | ---
AzureActiveDirectoryApplicationCredentials | | *remove* | Just uplift ApplicationId and ApplicationSecret to SearchIndexEncryptionKey
DataSource | Credentials | ConnectionString (string) | See notes below for DataSourceCredentials
DataSourceCredentials | | *remove* | Just uplift ConnectionString to SearchDataSource
EncryptionKey | | SearchResourceEncryptionKey
EncryptionKey | KeyVaultUri | VaultUri | Corresponds with Key Vault naming.
EncryptionKey | KeyVaultName | KeyName | Corresponds with Key Vault naming.
EncryptionKey | KeyVaultVersion | KeyVersion | Corresponds with Key Vault naming.
ItemError | | SearchIndexerError
ItemWarning | | SearchIndexerWarning
LengthTokenFilter | Max | LengthTokenFilter.MaxLength
LengthTokenFilter | Min | LengthTokenFilter.MinLength
TokenizerName | | LexicalTokenizerName

On a related note, other models should be hidden and their sole collection properties uplifted as return values. Names below reflect proposed renames above.

Method | Model | Return
--- | --- | ---
SearchServiceClient.ListDataSources | ListDataSourcesResult | DataSource[]
SearchServiceClient.ListIndexers | ListIndexersResult | SearchIndexer[]
SearchServiceClient.ListIndexes | ListIndexesResult | SearchIndex[]
SearchServiceClient.ListSkillsets | ListSkillsetsResult | SearchSkillset[]
SearchServiceClient.ListSynonymMaps | ListSynonymMapsResult | SynonymMap[]

**Comment by sima-zhu** [comment]
https://github.com/Azure/azure-sdk-for-java/pull/11540
