### ISSUE TITLE
Azure-Identity SDK 1.0.4 incompatible with JDK 1.6

### ISSUE THREAD

**Issue by JimmyLS** [Azure/azure-sdk-for-java#10279]
We tried below versions and found it was incompatible with JDK 1.6. Want to confirm if any Azure-Identity SDK version supports running on JDK 1.6? 

•	Azure-Identity 1.0.0
•	Azure-Identity 1.0.2
•	Azure-Identity 1.0.4

Thanks in advance!

**Comment by jianghaolu** [comment]
Hi @JimmyLS! I'm sorry to tell you all the libraries we are releasing since June 2019 require Java 8+. In fact, we started requiring Java 7+ since 2016.

**Comment by joshfree** [comment]
Hi @JimmyLS as @jianghaolu mentioned the Azure Unified SDK for Java (sometimes referred to informally as "Track 2") requires Java 8. See https://aka.ms/azuresdk for more details.

I'm closing this issue now, however please feel free to file a new issue or to reactivate this existing issue if there are more questions, comments, or feedback.  Thank you again!

**Comment by JimmyLS** [comment]
Thank you all for the clarification!
