### ISSUE TITLE
[QUERY] Proactive authorization header for http requests?

### ISSUE THREAD

**Issue by magooster** [Azure/azure-sdk-for-java#10287]
**Query/Question**
Is the Azure SDK supposed to proactively populate all http requests with the Authorization header? When testing with azure-security-keyvault-keys and azure-identity, I see two requests for each operation with the same instance of a client (the first returns a 401, and the second succeeds as the access token is added in response to the 401). The seems to be a reactive approach, once an access token had been generated I expected this to be used proactively on all subsequent requests for the same scope.

***Why is this not a Bug or a feature Request?***
Need to determine if the SDK is working as expected

**Setup (please complete the following information if applicable):**
 - Version of the Library used azure-identity 1.0.4, azure-security-keyvault-keys 4.1.1 with okhttp httpClient
 
 **Information Checklist**
 Kindly make sure that you have added all the following information above and checkoff the required fields otherwise we will treat the issuer as an incomplete report
- [ x] Query Added
- [ x] Setup information Added

**Comment by joshfree** [comment]
@vcolin7 can you please follow up on this question from @magooster?

/cc @g2vinay

**Comment by vcolin7** [comment]
The current KeyVault implementation does cache a token obtained the way described here and should request for a new one once the first has expired. I will do some testing to verify this behavior and come back with an answer later today or on Monday.

**Comment by vcolin7** [comment]
I did some testing and debugging and corroborated the following:

- The first time a new KeyClient makes an API call it sends a request to get a challenge that will be used to to obtain an access token, which will be then cached by the client.
- Any subsequent calls will use this token until it expires, at which point a new one will be obtained through the same mechanism.
- In the current challenge-based authentication implementation, we always first make a naive call to obtain a challenge, even if we end up using a cached token.

**Comment by vcolin7** [comment]
I'm closing this issue for the time being. Feel free to open a new issue or reopen this one in case I misunderstood part of the question or there is something you would like to further discuss :)

**Comment by magooster** [comment]
Thanks for the confirmation, any reason why a naive call is made if an access token is available? Does add an overhead to every operation due to the extra call... obviously impact is dependant on the use-case...

**Comment by vcolin7** [comment]
I don't think there is a particular reason this was done this way when the class was originally written. I agree that there is room for improvement checking the cache for the access token's existence or expiration before going for the challenge.

Thanks for bringing this to our attention :)
