### ISSUE TITLE
Readme content of Storage Blob Batch is unclear and inconsistencey

### ISSUE THREAD

**Issue by Luyunmt** [Azure/azure-sdk-for-java#10282]
1
Section [Link](https://github.com/Azure/azure-sdk-for-java/tree/master/sdk/storage/azure-storage-blob-batch#getting-started)
![image](https://user-images.githubusercontent.com/53427149/79424505-d294c600-7ff2-11ea-8d9b-a3b1850fbe4e.png)

Suggestion: 
Links are not availble . Add following links: 
Java Development Kit (JDK) 
https://docs.microsoft.com/en-us/java/azure/jdk/?view=azure-java-stable 

2
Section [Link](https://github.com/Azure/azure-sdk-for-java/tree/master/sdk/storage/azure-storage-blob-batch#create-a-storage-account)
![image](https://user-images.githubusercontent.com/53427149/79424696-23a4ba00-7ff3-11ea-8a0c-1dacd64d24a4.png)

Suggestion: 
Add Link： Azure Portal 
https://docs.microsoft.com/en-us/azure/storage/common/storage-account-create?tabs=azure-portal 
 
3
Section [Link](https://github.com/Azure/azure-sdk-for-java/tree/master/sdk/storage/azure-storage-blob-batch#create-a-storage-account)
![image](https://user-images.githubusercontent.com/53427149/79424870-6d8da000-7ff3-11ea-87f8-e52ef7f2f36c.png)

Suggestion:
Group-name's colour is black 

4
Section [Link](https://github.com/Azure/azure-sdk-for-java/tree/master/sdk/storage/azure-storage-blob-batch#creating-blobbatchclient)
![image](https://user-images.githubusercontent.com/53427149/79425117-c9f0bf80-7ff3-11ea-948a-f9c8cacb467e.png)

Suggestion: 
Wrong link. True link is https://github.com/Azure/azure-sdk-for-java/tree/master/sdk/storage/azure-storage-blob#create-a-storage-account

5
Section [Link](https://github.com/Azure/azure-sdk-for-java/tree/master/sdk/storage/azure-storage-blob-batch#bulk-deleting-blobs)
![image](https://user-images.githubusercontent.com/53427149/79425300-11774b80-7ff4-11ea-9976-83830680b5d2.png)

Suggestion: 
Add code 
List<String> blobUrls = new ArrayList<>(); 
blobUrls.add(blobClient1.getBlobUrl()); 
blobUrls.add(blobClient2.getBlobUrl()); 
blobUrls.add(blobClient3.getBlobUrl());

**Comment by tzhanl** [comment]
PR merged.
