### ISSUE TITLE
Readme content of Storage Queue is unclear and inconsistencey

### ISSUE THREAD

**Issue by Luyunmt** [Azure/azure-sdk-for-java#10281]
1
Section [Link](https://github.com/Azure/azure-sdk-for-java/tree/master/sdk/storage/azure-storage-queue#queueclient)
![image](https://user-images.githubusercontent.com/53427149/79443351-4d1e0f80-800c-11ea-8184-0e692ef32f3d.png)

Suggestion:  
https://%s.queue.core.windows.net/%s%s --> https://%s.queue.core.windows.net/%s?%s
add Comments:Only one "?" is needed here. If the sastoken starts with "?", please removing one "?".

Reason:Sastoken from Azure Cli doesn't start with "?". But in Azure portal, sastoken starts with "?". Current code snippet not work with the first one.

2
Section [Link](https://github.com/Azure/azure-sdk-for-java/tree/master/sdk/storage/azure-storage-queue#queueclient)
![image](https://user-images.githubusercontent.com/53427149/79443644-ad14b600-800c-11ea-97ca-cb6f6b7bd622.png)

Suggestion: 
https://%s.queue.core.windows.net/%s --> https://%s.queue.core.windows.net/?%s  
add Comments:Only one "?" is needed here. If the sastoken starts with "?", please removing one "?".

Reason:Sastoken from Azure Cli doesn't start with "?". But in Azure portal, sastoken starts with "?". Current code snippet not work with the first one.

**Comment by joshfree** [comment]
Thanks for reviewing content and samples for consistency across SDKs and filing this issue @Luyunmt

**Comment by tzhanl** [comment]
PR merged.
