### ISSUE TITLE
Readme content of StorageBlob is unclear and inconsistencey

### ISSUE THREAD

**Issue by Luyunmt** [Azure/azure-sdk-for-java#10280]
1
Section [Link](https://github.com/Azure/azure-sdk-for-java/tree/master/sdk/storage/azure-storage-blob#create-a-blobserviceclient)
![image](https://user-images.githubusercontent.com/53427149/79423097-9496a280-7ff0-11ea-81e0-165a5463d7eb.png)
![image](https://user-images.githubusercontent.com/53427149/79423172-b728bb80-7ff0-11ea-82ce-adf4057ec3a0.png)
![image](https://user-images.githubusercontent.com/53427149/79423243-da536b00-7ff0-11ea-885a-c5230c5fa436.png)

Suggestion: 
Add comments :  Only one "?" is needed here. If the sastoken starts with "?", please removing one "?".

Reason:Sastoken from Azure Cli doesn't start with "?". But in Azure portal, sastoken starts with "?". Current code snippet not work with the later one

**Comment by rickle-msft** [comment]
@Luyunmt Thank you for suggesting each of these updates to our readmes. We will take a look and consider modifying them accordingly.

**Comment by tzhanl** [comment]
PR merged.
