### ISSUE TITLE
Add AzureServiceClientCredentials

### ISSUE THREAD

**Issue by jianghaolu** [Azure/azure-sdk-for-java#1028]
The existing interface `ServiceClientCredentials` has been working fine for most management plane libraries. However, when it comes to Graph RBAC client, the `resourceId` field sent in the authorization request is different the other management plane libraries. Thus we would have to use a different credentials for Graph, which requires us to use a different `RestClient` as well.
To fix this, `AzureServiceClientCredentials` is introduced to extend `ServiceClientCredentials`. It
- is still immutable
- requires an `AzureEnvironment`
- matches the request base URL to the entries in `AzureEnvironment` to figure out where to authenticate and which `resourceId` to send.

This does not only solve the problem for Graph RBAC, but also supports Azure stack scenarios. Developers can create custom `AzureEnvironment` instances and the implementation of `AzureServiceClientCredentials` is able to log into public Active Directory service with on-premise resource IDs.

**Comment by solvingJ** [comment]
Is there any chance of also adding one other class that extends ServiceClientCredentials type that works with the Storage API (SAS Tokens), which are retrieved from the Insights API?

This would enable the direct retrieval of Azure VM metrics from Azure Storage Tables using only the RestClient from this library (rather than requiring the whole storage SDK).

**Comment by jianghaolu** [comment]
Thanks for the feedback @solvingJ  I'll look into it.

**Comment by jianghaolu** [comment]
Hi @solvingJ  it feels to me that even if we add a credentials class that works with storage - you would still need storage SDK to access the tables. Are you accessing the tables through direct REST calls?

**Comment by solvingJ** [comment]
Yes, directly through rest calls and we've made it work now without the storage SDK.  

Still, the fact remains that the azure rest client runtime libraries and and authentication libraries together simply can't authenticate to a number of major Azure services.  From a user point of view, it would be better if this package handled authentication/authorization for all Azure services.  There are only a handful of authentication schemes across all the web services, so it seems like a reasonable expectation.

**Comment by jianghaolu** [comment]
It's added and called `AzureTokenCredentials`. 

For now we have no plan to unify the authentication methods across services since there are just too many different needs and requirements.
