### ISSUE TITLE
[QUERY] Copy data from one storage account to another storage account across subscription

### ISSUE THREAD

**Issue by saralpa** [Azure/azure-sdk-for-java#10288]
**Query/Question**
Copy data from one storage account to another storage account across subscription using azure java sdk.

***Why is this not a Bug or a feature Request?***
We need to copy a virtual directory content to another storage account through code. AzCopy provides this option by using this : 
azcopy copy 'https://source-storage-account-name.blob.core.windows.net/container-name/directory-path SAS-token' 
'https://destination-storage-account-name.blob.core.windows.net/container-name' --recursive

Is the same option available in azure java sdk. Currently we are using startCopy . 
Limitation of this method is we need to pass files in directory one by one. 
It is time consuming process. We want to avoid looping through the files and just copy all the data from virtual directory in recursive way to destination.

**Setup (please complete the following information if applicable):**
 - IDE : STS
 - Version of the Library used : 

<dependency>
  <groupId>com.azure</groupId>
  <artifactId>azure-storage-blob</artifactId>
  <version>12.6.0</version>
</dependency>
 
 **Information Checklist**
 Kindly make sure that you have added all the following information above and checkoff the required fields otherwise we will treat the issuer as an incomplete report
- [ ] Query Added
- [ ] Setup information Added

**Comment by rickle-msft** [comment]
The sdk does not have a method to bulk copy a directory from one location to another, and there are not plans to add such a method. As you mentioned, azcopy includes this feature, and our recommendations in these scenarios is always to use azcopy as it is finely tuned for exactly this workload. If you want this feature within Java, it will be up to you to build the solution as you mentioned.

**Comment by rickle-msft** [comment]
Closing this issue as it is not a feature we plan to add and it has been left idle for a while.
