### ISSUE TITLE
Grouping secrets in azure key-vault 

### ISSUE THREAD

**Issue by sndp2693** [Azure/azure-sdk-for-java#10316]
I am trying store secrets in azure vault. I used azure sdk apis and i can successfully store/retrieve using those. I wanted to know if it's possible to categorise/group set of secrets under same tag and store them in some path.

I want to group some secrets used by one service store them is one path. Same way for other services is separate paths. I couldn't find any way for doing that. Is that possible in azure vault?

**Comment by joshfree** [comment]
@vcolin7 could you please follow up with @sndp2693 on the keyvault question above?
/cc @g2vinay

**Comment by vcolin7** [comment]
As far as I know there is no feature to group secrets inside the same KeyVault, I dig a bit deeper into this today though. As a workaround, something you can do to group secrets is have them in different KeyVaults, this way you can also have different access permissions for each group.

**Comment by vcolin7** [comment]
I'm closing this issue for the time being. Feel free to open a new issue or reopen this one in case I misunderstood part of the question or there is something you would like to further discuss :)
