### ISSUE TITLE
Readme content of Search is unclear and inconsistencey

### ISSUE THREAD

**Issue by Luyunmt** [Azure/azure-sdk-for-java#10319]
1
Section [Link](https://github.com/Azure/azure-sdk-for-java/tree/master/sdk/search/azure-search-documents#prerequisites)
![image](https://user-images.githubusercontent.com/53427149/79552254-6044e400-80cd-11ea-9148-98c35a705599.png)

Suggestion:  
Links are not availble. Add following links: 
Java Development Kit (JDK) 
https://docs.microsoft.com/en-us/java/azure/jdk/?view=azure-java-stable 

2
Section [Link](https://github.com/Azure/azure-sdk-for-java/tree/master/sdk/search/azure-search-documents#create-an-index)
![image](https://user-images.githubusercontent.com/53427149/79550683-46a29d00-80cb-11ea-8cec-bbaf0efca5e8.png)

Suggestion: 
SearchIndexClient --> SearchServiceClient   
The link is unavaliable. Change link to https://github.com/Azure/azure-sdk-for-java/tree/master/sdk/search/azure-search-documents#create-a-searchserviceclient 

3
Section [Link](https://github.com/Azure/azure-sdk-for-java/tree/master/sdk/search/azure-search-documents#create-a-searchserviceclient)
![image](https://user-images.githubusercontent.com/53427149/79551052-bd3f9a80-80cb-11ea-96ce-5da523d00412.png)

Suggestion: 
client--> searchServiceClient   
client--> searchServiceAsyncClient 
client--> searchIndexClient    
client--> searchIndexAsyncClient 
Also change it in code snippet

**Comment by sima-zhu** [comment]
https://github.com/Azure/azure-sdk-for-java/pull/10672

This is fixed by above PR. 

Thanks @Luyunmt for reporting this!

Close the issue. Feel free to reopen if you have any questions.
