### ISSUE TITLE
[BUG] ManagementClient does not support connecting via proxy

### ISSUE THREAD

**Issue by giventocode** [Azure/azure-sdk-for-java#10311]
We have tried several approaches without any luck:
-  Setting  global proxy settings in the JVM and in code  (```https.proxyHost``` and ```https.proxyPort```)
-  Implement a custom ```ProxySelector``` and set it as a default. 

Through traces we have verified that the calls to the Service Bus endpoint are not going through the proxy.

**Comment by giventocode** [comment]
Further looking into this, it seems like the issue is how the management client is instantiating the underlying http client.

```
 public ManagementClientAsync(URI namespaceEndpointURI, ClientSettings clientSettings) {
        this.namespaceEndpointURI = namespaceEndpointURI;
        this.clientSettings = clientSettings;
        DefaultAsyncHttpClientConfig.Builder clientBuilder = Dsl.config()
                .setConnectTimeout((int) CONNECTION_TIMEOUT.toMillis())
                .setRequestTimeout((int) this.clientSettings.getOperationTimeout().toMillis());
        this.asyncHttpClient = asyncHttpClient(clientBuilder);
    }
```

By default the ```asyncHttpClient``` does not use the standard Java ```ProxySelector```. 

https://github.com/AsyncHttpClient/async-http-client/blob/ac2d4bdf46abf96aeb5a61d56bc5718ac005184a/client/src/main/resources/org/asynchttpclient/config/ahc-default.properties#L18

This capability should be enabled by default in the library or it should expose a config mechanism to enable it.

**Comment by joshfree** [comment]
Thanks for reporting this @giventocode.  @xccc-msft as part of moving the Managment Plane to the new azure-core (track 2) you'll get Proxy support (/cc @alzimmermsft)  - could you please follow up with @giventocode

**Comment by xccc-msft** [comment]
@giventocode Would you share more details regarding which SDK and version you are using?

**Comment by giventocode** [comment]
We are using version, 3.1.3. 

Also, we have found a workaround. It is possible to set the underlying HTTP client configuration in maven.

```
mvn ... -Dorg.asynchttpclient.useProxySelector=true
``` 

However, the ideal scenario is allowing us to set these setting programmatically. 

So a few options come to mind: 

1. Add proxy configuration settings to ```ClientSettings```
2. Expose the HTTP client builder.

For option 2, I have an implementation, link below, and I can submit a PR if that helps.

https://github.com/giventocode/azure-sdk-for-java/commit/d6846fdc617efed97c358407b17e8d49b9f64019

Let me know your thoughts.

**Comment by xccc-msft** [comment]
@giventocode what's the SDK artifact id? It seems not our mgmt SDK.

**Comment by giventocode** [comment]
https://mvnrepository.com/artifact/com.microsoft.azure/azure-servicebus/3.1.3

**Comment by xccc-msft** [comment]
@joshfree Can you please help assign to the owner of service bus above?

**Comment by yungezz** [comment]
hi @joshfree , will remove `mgmt` label since `azure-servicebus` sdk is owned by data plane team , let us know if owner is not right.

**Comment by giventocode** [comment]
@joshfree , any update on this? Thank you!

**Comment by xccc-msft** [comment]
@giventocode Does the merged PR work for you?

**Comment by giventocode** [comment]
Yes thank you!
