### ISSUE TITLE
[BUG]Clients of Azure File Share Client Library can not operate some exmples on README.md

### ISSUE THREAD

**Issue by FredGao-new** [Azure/azure-sdk-for-java#10317]
**Describe the bug**
When using clients created by `SASToken` to complete some examples mentioned on README.md, there is an exception.
However, when using clients created by `connection string` to complete the examples, there are no exceptions.
Links for the examples are given below:
https://github.com/Azure/azure-sdk-for-java/tree/master/sdk/storage/azure-storage-file-share#copy-a-file
https://github.com/Azure/azure-sdk-for-java/tree/master/sdk/storage/azure-storage-file-share#get-a-share-access-policy
https://github.com/Azure/azure-sdk-for-java/tree/master/sdk/storage/azure-storage-file-share#set-a-share-access-policy 

***Exception or Stack Trace***
**Exception of "copy a file"**:
Exception in thread "main" com.azure.storage.file.share.models.ShareStorageException: Status code 404, "﻿<?xml version="1.0" encodin
g="utf-8"?><Error><Code>CannotVerifyCopySource</Code><Message>The specified resource does not exist.
RequestId:b7433745-901a-000a-6292-14f742000000

**Exception of "get a share access policy" and "set a share access policy"**:
Exception in thread "main" com.azure.storage.file.share.models.ShareStorageException: Status code 403, "﻿<?xml version="1.0" encodin
g="utf-8"?><Error><Code>AuthorizationFailure</Code><Message>This request is not authorized to perform this operation.
RequestId:1d9dcb7a-d01a-0056-5692-14a21a000000

**Expected behavior**
There are no exceptions with both clients.

**Setup (please complete the following information):**
Windows
 - IDE : [e.g. IntelliJ] 
VSCode
 - Version of the Library used 
  <artifactId>azure-storage-file-share</artifactId>
  <version>12.5.0-beta.1.dev.20200415.1</version>
JDK 1.8

**Additional context**

**Information Checklist**
Kindly make sure that you have added all the following information above and checkoff the required fields otherwise we will treat the issuer as an incomplete report
- [ ] Bug Description Added
- [ ] Repro Steps Added
- [ ] Setup information Added

**Comment by Luyunmt** [comment]
@rickle-msft How is this issue going?

**Comment by rickle-msft** [comment]
We have not yet begun working on this, but it is still in our backlog

**Comment by Luyunmt** [comment]
@rickle-msft These 3 samples mentioned above shows two kinds of operations: copy file and get/set AccessPolicy. For clients created with SASToken, copy file should work, get/set AccessPolicy should not work as SASToken can't be used for such purpose. 

**1. Copy a file**

While copy file with SASToken, the SASToken should be appended to the source file url. 
![image](https://user-images.githubusercontent.com/53427149/90609440-9ab6bd00-e236-11ea-8c68-e3d12d496ce8.png)

Copy file would **fail**.

![image](https://user-images.githubusercontent.com/53427149/90609503-b9b54f00-e236-11ea-8942-33b1e848eef9.png)

Copy file would **successful**.

**Suggestion**: In method `beginCopy`, if the client created with sastoken, append the sastoken to source URL.

**2.  get/set AccessPolicy**

SAStoken can’t be used to update access policy. It is better to have some description about this in readme, sample, and the sdk code comments.

**Suggestion**: Add  description  about this in readme, sample, and the sdk code comments.

**Readme**:
![image](https://user-images.githubusercontent.com/53427149/90609556-d2be0000-e236-11ea-8da8-8e84cb7cd45a.png)

**Sample**:
![image](https://user-images.githubusercontent.com/53427149/90609624-ed907480-e236-11ea-811f-3196e484c5b4.png)

code comments:
![image](https://user-images.githubusercontent.com/53427149/90609689-ff721780-e236-11ea-9f3d-ce24fc3b48f4.png)

**Comment by Luyunmt** [comment]
Now the operation copy file problem were fixed. And we push pr https://github.com/Azure/azure-sdk-for-java/pull/18470 to fix the operation  get/set AccessPolicy problem.

**Comment by gapra-msft** [comment]
Closing as PR has been merged
