### ISSUE TITLE
Readme content of Azure Storage File Data Lake is unclear and inconsistencey

### ISSUE THREAD

**Issue by FredGao-new** [Azure/azure-sdk-for-java#10325]
1.
Section [Link](https://github.com/Azure/azure-sdk-for-java/tree/master/sdk/storage/azure-storage-file-datalake#create-a-storage-account)
![image](https://user-images.githubusercontent.com/52488926/79554908-e0317500-80f2-11ea-9ca8-ccaedb484e1b.png)
Suggestion:
Add CLI command:
`--enable-hierarchical-namespace true`
according to https://docs.microsoft.com/en-us/cli/azure/storage/account?view=azure-cli-latest#az-storage-account-create

2.
Section [Link](https://github.com/Azure/azure-sdk-for-java/tree/master/sdk/storage/azure-storage-file-datalake#url-format)
![image](https://user-images.githubusercontent.com/52488926/79556001-8fbb1700-80f4-11ea-81d1-64b2c35c0e00.png)
Suggestion:
url should be displayed in code format

3.
Section [Link](https://github.com/Azure/azure-sdk-for-java/tree/master/sdk/storage/azure-storage-file-datalake#url-format)
![image](https://user-images.githubusercontent.com/52488926/79556132-c5600000-80f4-11ea-8f0d-f6ac01662ab6.png)
Suggestion:
Change to the following format:
`${myaccount}`
`${myfilesystem}`
`${mypath}`

4.
Section [Link](https://github.com/Azure/azure-sdk-for-java/tree/master/sdk/storage/azure-storage-file-datalake#examples)
![image](https://user-images.githubusercontent.com/52488926/79557162-38b64180-80f6-11ea-933c-03c20ee91054.png)
![image](https://user-images.githubusercontent.com/52488926/79557270-600d0e80-80f6-11ea-99d3-e9a3c9660216.png)
Suggestion:
Remove unused links
Add links for the missing sample code titles:
[Rename a file](https://github.com/Azure/azure-sdk-for-java/tree/master/sdk/storage/azure-storage-file-datalake#rename-a-file)
[Rename a directory](https://github.com/Azure/azure-sdk-for-java/tree/master/sdk/storage/azure-storage-file-datalake#rename-a-directory)
[Get file properties](https://github.com/Azure/azure-sdk-for-java/tree/master/sdk/storage/azure-storage-file-datalake#get-file-properties)
[Get directory properties](https://github.com/Azure/azure-sdk-for-java/tree/master/sdk/storage/azure-storage-file-datalake#get-directory-properties)

5.
Section Links:
https://github.com/Azure/azure-sdk-for-java/tree/master/sdk/storage/azure-storage-file-datalake#create-a-datalakeserviceclient
https://github.com/Azure/azure-sdk-for-java/tree/master/sdk/storage/azure-storage-file-datalake#create-a-datalakefilesystemclient
https://github.com/Azure/azure-sdk-for-java/tree/master/sdk/storage/azure-storage-file-datalake#create-a-datalakefileclient
https://github.com/Azure/azure-sdk-for-java/tree/master/sdk/storage/azure-storage-file-datalake#create-a-datalakedirectoryclient
![image](https://user-images.githubusercontent.com/52488926/79557645-05c07d80-80f7-11ea-8daf-832572391f8f.png)
![image](https://user-images.githubusercontent.com/52488926/79557658-0a853180-80f7-11ea-9ad0-25699a42324a.png)
![image](https://user-images.githubusercontent.com/52488926/79557671-0d802200-80f7-11ea-960a-468a8d858d8a.png)
![image](https://user-images.githubusercontent.com/52488926/79557677-107b1280-80f7-11ea-8aa4-472f8ce81bab.png)
Suggestion:
Add comments : 
`// Only one "?" is needed here. If the sastoken starts with "?", please removing one "?".
The sastoken created by azure portal starts with "?". Using it in Code Snippet to create client will fail.`
Reason:
SASToken from Azure Cli doesn't start with "?". But in Azure portal, sastoken starts with "?". Current code snippet not work with the later one.

6.
Section Links:
https://github.com/Azure/azure-sdk-for-java/tree/master/sdk/storage/azure-storage-file-datalake#rename-a-file
https://github.com/Azure/azure-sdk-for-java/tree/master/sdk/storage/azure-storage-file-datalake#rename-a-directory
Suggestion:
Add comment:
`//you need to authenticate with azure identity and add role assignment "Storage Blob Data Contributor" to do the following operation.`
Reason:
The sample will fail if client is constructed with `SASToken`.

**Comment by tzhanl** [comment]
pr merged.
