### ISSUE TITLE
Readme content of Azure Storage Blobs Cryptography is unclear and inconsistencey

### ISSUE THREAD

**Issue by FredGao-new** [Azure/azure-sdk-for-java#10323]
1.
Section [Link](https://github.com/Azure/azure-sdk-for-java/tree/master/sdk/storage/azure-storage-blob-cryptography#getting-started)
![image](https://user-images.githubusercontent.com/52488926/79552144-bd9d5d00-80ee-11ea-8ab3-d19fae961f04.png)
Suggestion:
Add the following links:
[Java Development Kit (JDK)](https://docs.microsoft.com/en-us/java/azure/jdk/?view=azure-java-stable)
[Azure Subscription](https://azure.microsoft.com/en-us/free/)
[Create Storage Account](https://docs.microsoft.com/en-us/azure/storage/common/storage-account-create?tabs=azure-portal)

2.
Section [Link](https://github.com/Azure/azure-sdk-for-java/tree/master/sdk/storage/azure-storage-blob-cryptography#create-a-storage-account)
![image](https://user-images.githubusercontent.com/52488926/79552765-96935b00-80ef-11ea-8f25-b7d51e29b259.png)
Suggestion:
Add link:
[Azure Portal](https://docs.microsoft.com/en-us/azure/storage/common/storage-account-create?tabs=azure-portal)
[Azure CLI](https://docs.microsoft.com/en-us/azure/storage/common/storage-account-create?tabs=azure-cli)

3.
Section [Link](https://github.com/Azure/azure-sdk-for-java/tree/master/sdk/storage/azure-storage-blob-cryptography#authenticate-the-client)
![image](https://user-images.githubusercontent.com/52488926/79553615-dc9cee80-80f0-11ea-9fcb-5b491524eb61.png)
Suggestion:
Add Link:
[SAS Token](https://docs.microsoft.com/en-us/azure/storage/common/storage-sas-overview)

4.
Section [Link](https://github.com/Azure/azure-sdk-for-java/tree/master/sdk/storage/azure-storage-blob-cryptography#get-credentials)
![image](https://user-images.githubusercontent.com/52488926/79554145-c3e10880-80f1-11ea-8f40-2899d4118b6e.png)
![image](https://user-images.githubusercontent.com/52488926/79554216-dd825000-80f1-11ea-9a43-58e1025e9cd0.png)
Suggestion:
The "Get Credentials" section should follow format of the following link:
https://github.com/Azure/azure-sdk-for-java/tree/master/sdk/storage/azure-storage-blob#get-credentials

5.
Section [Link](https://github.com/Azure/azure-sdk-for-java/tree/master/sdk/storage/azure-storage-blob-cryptography#examples)
![image](https://user-images.githubusercontent.com/52488926/79850709-682bbd80-8418-11ea-98fd-35e1dc8a748a.png)
Suggestion:
Incomplete examples section

**Comment by tzhanl** [comment]
PR merged.
