### ISSUE TITLE
Readme content of Azure Storage File Share is unclear and inconsistencey

### ISSUE THREAD

**Issue by FredGao-new** [Azure/azure-sdk-for-java#10326]
1.
Section [Link](https://github.com/Azure/azure-sdk-for-java/tree/master/sdk/storage/azure-storage-file-share#handling-exceptions)
![image](https://user-images.githubusercontent.com/52488926/79559179-62bd3300-80f9-11ea-8959-7c0d894a07d8.png)
Suggestion:
Change to the following:
`shareServiceClient`
[shareServiceClient](https://github.com/Azure/azure-sdk-for-java/tree/master/sdk/storage/azure-storage-file-share#share-services)

2.
Section [Link](https://github.com/Azure/azure-sdk-for-java/tree/master/sdk/storage/azure-storage-file-share#share-services)
![image](https://user-images.githubusercontent.com/52488926/79559756-6bfacf80-80fa-11ea-9c69-1bb6fc467305.png)
Suggestion:
·shareServiceClient·
`shareServiceURL`

3.
Section [Link](https://github.com/Azure/azure-sdk-for-java/tree/master/sdk/storage/azure-storage-file-share#directory )
![image](https://user-images.githubusercontent.com/52488926/79560382-a0bb5680-80fb-11ea-8c48-f58b143bd398.png)
Suggestion:
Change to the following code:
`String directoryURL = String.format("https://%s.file.core.windows.net", accountName); 
ShareDirectoryClient directoryClient = new ShareFileClientBuilder().endpoint(directoryURL) 
    .sasToken(sasToken).shareName(shareName).resourcePath(directoryPath).buildDirectoryClient(); `

4.
Section [Link](https://github.com/Azure/azure-sdk-for-java/tree/master/sdk/storage/azure-storage-file-share#file)
![image](https://user-images.githubusercontent.com/52488926/79560707-322ac880-80fc-11ea-89d4-954b8f81fed2.png)
Suggestion:
Change to the following code snippet:
`ShareFileClient fileClient = new ShareFileClientBuilder().endpoint(fileURL) 
.sasToken(sasToken).shareName(shareName).resourcePath(directoryPath + "/" + fileName).buildFileClient();`

5.
Section Links:
https://github.com/Azure/azure-sdk-for-java/tree/master/sdk/storage/azure-storage-file-share#create-a-share 
https://github.com/Azure/azure-sdk-for-java/tree/master/sdk/storage/azure-storage-file-share#create-a-snapshot-on-share 
https://github.com/Azure/azure-sdk-for-java/tree/master/sdk/storage/azure-storage-file-share#list-all-shares 
https://github.com/Azure/azure-sdk-for-java/tree/master/sdk/storage/azure-storage-file-share#get-a-file-service-properties 
https://github.com/Azure/azure-sdk-for-java/tree/master/sdk/storage/azure-storage-file-share#set-a-file-service-properties
![image](https://user-images.githubusercontent.com/52488926/79561084-d3b21a00-80fc-11ea-92a9-3fa43ada95ce.png)
Suggestion:
Change to `${shareServiceClient}`

6.
Section [Link](https://github.com/Azure/azure-sdk-for-java/tree/master/sdk/storage/azure-storage-file-share#create-a-directory)
![image](https://user-images.githubusercontent.com/52488926/79561236-1ecc2d00-80fd-11ea-81f3-d9a8d35b33f5.png)
Suggestion:
Change to following:
${shareClient}(#create-a-snapshot-on-share) initialized above, [`${shareClient}`](https://github.com/Azure/azure-sdk-for-java/tree/master/sdk/storage/azure-storage-file-share#share).

7.
Section [Link](https://github.com/Azure/azure-sdk-for-java/tree/master/sdk/storage/azure-storage-file-share#upload-file-to-storage)
![image](https://user-images.githubusercontent.com/52488926/79561967-55ef0e00-80fe-11ea-8ce1-36fdd7daf0ef.png)
Suggestion:
Change to `${myLocalFilePath}`

8.
Section [Link](https://github.com/Azure/azure-sdk-for-java/tree/master/sdk/storage/azure-storage-file-share#download-data-from-file-range)
![image](https://user-images.githubusercontent.com/52488926/79562166-b1210080-80fe-11ea-9cc2-83379dcd40da.png)
Suggestion:
Change to the following:
file range 0 to 2048
`ShareFileRange fileRange = new ShareFileRange(0L, 2048L); 
        OutputStream stream = new ByteArrayOutputStream(); 
        fileClient.downloadWithResponse(stream, fileRange, false, null, Context.NONE); `
Reason:
The file range will lead to following exception:
![image](https://user-images.githubusercontent.com/52488926/79562423-2db3df00-80ff-11ea-8cc8-1146287d5813.png)

9.
Section [Link](https://github.com/Azure/azure-sdk-for-java/tree/master/sdk/storage/azure-storage-file-share#download-file-from-storage)
![image](https://user-images.githubusercontent.com/52488926/79562503-56d46f80-80ff-11ea-9711-10494e8bfe60.png)
Suggestion:
`${myLocalFilePath}`

10.
Section Links:
https://github.com/Azure/azure-sdk-for-java/tree/master/sdk/storage/azure-storage-file-share#get-a-file-service-properties 
https://github.com/Azure/azure-sdk-for-java/tree/master/sdk/storage/azure-storage-file-share#set-a-file-service-properties 
![image](https://user-images.githubusercontent.com/52488926/79562666-85eae100-80ff-11ea-92df-1885c2d5b8ee.png)
![image](https://user-images.githubusercontent.com/52488926/79562685-88e5d180-80ff-11ea-8dff-211958af4aa2.png)
Suggestion:
share service
ShareServiceClient

11.
Section [Link](https://github.com/Azure/azure-sdk-for-java/tree/master/sdk/storage/azure-storage-file-share#set-a-file-service-properties)
![image](https://user-images.githubusercontent.com/52488926/79562835-c2b6d800-80ff-11ea-92b3-14594a3aabb4.png)
Suggestion:
Change to the following:
share service
ShareServiceClient
`properties.getMinuteMetrics().setEnabled(true).setIncludeApis(true); 
properties.getHourMetrics().setEnabled(true).setIncludeApis(true); `
Reason:
The sample code will produce the follwoing exception:
![image](https://user-images.githubusercontent.com/52488926/79563166-58eafe00-8100-11ea-84cb-14e2fa7109e1.png)

12.
Section [Link](https://github.com/Azure/azure-sdk-for-java/tree/master/sdk/storage/azure-storage-file-share#set-a-share-access-policy)
![image](https://user-images.githubusercontent.com/52488926/79563242-8172f800-8100-11ea-84b1-977a04790ea6.png)
Suggestion:
Change to the following code snippet:
`ShareAccessPolicy accessPolicy = new ShareAccessPolicy().setPermissions("r") 
        .setStartsOn(OffsetDateTime.now(ZoneOffset.UTC)) 
        .setExpiresOn(OffsetDateTime.now(ZoneOffset.UTC).plusDays(10)); `
 `ShareSignedIdentifier permission = new ShareSignedIdentifier().setId("mypolicy").setAccessPolicy(accessPolicy); `
      ` shareClient.setAccessPolicy(Collections.singletonList(permission)); `

13.
Section [Link](https://github.com/Azure/azure-sdk-for-java/tree/master/sdk/storage/azure-storage-file-share#force-close-handles-on-handle-id)
![image](https://user-images.githubusercontent.com/52488926/79563325-b97a3b00-8100-11ea-815c-d00613709a23.png)
Suggestion:
Change to the following code snippet: 
`directoryClient.forceCloseHandleWithResponse(handleId, Duration.ofSeconds(30), Context.NONE);`

14.
Section [Link](https://github.com/Azure/azure-sdk-for-java/tree/master/sdk/storage/azure-storage-file-share#set-file-httpheaders) 
![image](https://user-images.githubusercontent.com/52488926/79563428-e9c1d980-8100-11ea-9a3c-6b3391f36cfb.png)
Suggestion:
Change to the following code: 
 `ShareFileHttpHeaders httpHeaders = new ShareFileHttpHeaders().setContentType("text/plain"); `
 `long newFileSize = 1024; `
 ` fileClient.setProperties(newFileSize, httpHeaders, null, null); `

**Comment by tzhanl** [comment]
PR merged.
