### ISSUE TITLE
Readme content of App Configuration is unclear and inconsistencey

### ISSUE THREAD

**Issue by Luyunmt** [Azure/azure-sdk-for-java#10320]
1
Section [Link](https://github.com/Azure/azure-sdk-for-java/tree/master/sdk/appconfiguration/azure-data-appconfiguration#getting-started)
![image](https://user-images.githubusercontent.com/53427149/79552378-866a8400-80cd-11ea-889c-ca15b59ab774.png)

Suggestion:  
Links are not availble. Add following links: 
Java Development Kit (JDK) 
https://docs.microsoft.com/en-us/java/azure/jdk/?view=azure-java-stable 

2
Section [Link](https://github.com/Azure/azure-sdk-for-java/tree/master/sdk/appconfiguration/azure-data-appconfiguration#create-an-app-configuration-store)
![image](https://user-images.githubusercontent.com/53427149/79552481-aa2dca00-80cd-11ea-8c78-36459bef023e.png)

Suggestion: 
Group-name's color is black

**Comment by joshfree** [comment]
@mssfang can you please follow up?

**Comment by joshfree** [comment]
Here's an example of a newer readme.md that's been scrubbed and is consistent with the format we'd like all readmes to generally be in: https://github.com/Azure/azure-sdk-for-java/blob/master/sdk/search/azure-search-documents/README.md

**Comment by mssfang** [comment]
@Luyunmt  For 1) any distribution is compatible, so we should not include a specific distribution in the README. I have update 2) in #10353
