### ISSUE TITLE
Readme content of Text-Analytics is unclear and nconsistency

### ISSUE THREAD

**Issue by JerryPei1997** [Azure/azure-sdk-for-java#10322]
1
Section [Link](https://github.com/Azure/azure-sdk-for-java/blob/master/sdk/textanalytics/azure-ai-textanalytics/README.md#prerequisites)
![image](https://user-images.githubusercontent.com/49467823/79553071-85862200-80ce-11ea-8bba-c18c671962e3.png)

**Comment**: 
Don't have Link for JDK.

**Suggestion**:
Add following links:
Java Development Kit (JDK) https://docs.microsoft.com/en-us/java/azure/jdk/?view=azure-java-stable

2
Section [Link](https://github.com/Azure/azure-sdk-for-java/tree/master/sdk/textanalytics/azure-ai-textanalytics#option-1-create-textanalyticsclient-with-api-key-credential)
![image](https://user-images.githubusercontent.com/49467823/79553354-f0cff400-80ce-11ea-9214-ee1cc298d412.png)

**Comment**:
The description is unclear.

**Suggestion**:
Update to:
"This can be found in the [Azure Portal](https://portal.azure.com) under the "Quickstart" section 
**in your created Text Analytics resource** or by running the following Azure CLI command:"

3
Section [Link](https://github.com/Azure/azure-sdk-for-java/tree/master/sdk/textanalytics/azure-ai-textanalytics#input)
![image](https://user-images.githubusercontent.com/49467823/79553631-5a500280-80cf-11ea-816c-9ce5847b319b.png)

**Comment**:
Inconsistency.

**Suggestion**:
Update "Text Analytics client" to "`TextAnalyticsClient`".
Just like:
![image](https://user-images.githubusercontent.com/49467823/79553711-7a7fc180-80cf-11ea-9a7d-510236556141.png)

4
Section [Link](https://github.com/Azure/azure-sdk-for-java/blob/master/sdk/textanalytics/azure-ai-textanalytics/README.md#operation-on-multiple-documents)
![image](https://user-images.githubusercontent.com/49467823/79553771-97b49000-80cf-11ea-8047-89531c39895b.png)

**Comment**:
Inconsistency.

**Suggestion**:
Update "Text Analytics client" to "`TextAnalyticsClient`".
Just like:
![image](https://user-images.githubusercontent.com/49467823/79553711-7a7fc180-80cf-11ea-9a7d-510236556141.png)

5
Section [Link](https://github.com/Azure/azure-sdk-for-java/blob/master/sdk/textanalytics/azure-ai-textanalytics/README.md#operation-on-multiple-documents)
![image](https://user-images.githubusercontent.com/49467823/79553882-c9c5f200-80cf-11ea-920b-a330739155be.png)

**Comment**:
Wrong link alias.

**Suggestion**:
Update "[supported languages][**supported_languages**]" 
to 
"[supported languages][**supported_language**]"

6
Section [Link](https://github.com/Azure/azure-sdk-for-java/tree/master/sdk/textanalytics/azure-ai-textanalytics/src/samples#contributing)
![image](https://user-images.githubusercontent.com/49467823/79966460-0b83dd80-84c0-11ea-9900-8da9d06677c8.png)

**Comment**:
The file pointed to by the link [Contribution Guidelines](https://github.com/Azure/azure-sdk-for-java/blob/master/sdk/textanalytics/azure-ai-textanalytics/CONTRIBUTING.md) doesn't exist.

**Comment by mssfang** [comment]
@JerryPei1997  For 1) any distribution is compatible, so we should not include a specific distribution in the README. 

I have fixed rest of readme feedbacks in #11129

**Comment by mssfang** [comment]
@JerryPei1997  For TextAnalyticsClient change, since we have both “TextAnalyticsClient” for synchronous client and "TextAnalyticsAsyncClient" for asynchronous client. So we should still use 
Text Analytics client to have no preference in between sync and asycn client.
