### ISSUE TITLE
[FEATURE REQ] [core]  com.azure.core.exception.AzureException should support stackless constructor for improved performance

### ISSUE THREAD

**Issue by David-Noble-at-work** [Azure/azure-sdk-for-java#10339]
Exceptions with stacks are slow in Java and sometimes the stack adds no value. This is true, for example, when mapping status codes to exceptions in a transport client (e.g., the Cosmos Direct TCP transport client). In these cases the value of the exception is the error that it reports. The stack does not help to understand the problem. The exception message is enough to understand the problem. Java's `Throwable` class adds such a constructor to cover this use case:
```java
protected | Throwable​(String message, Throwable cause, boolean enableSuppression, boolean writableStackTrace)
``` 

This is a request for a protected `AzureException` constructor for creating a stackless exception hierarchy based on `AzureException`. 

The constructor should have this signature:
```java
protected AzureException​(String message, Throwable cause, boolean enableSuppression, boolean writableStackTrace)
```

It should construct a new throwable with the specified detail message, cause, suppression enabled or disabled, and writable stack trace enabled or disabled.

## References
1. [The Exceptional Performance of Lil' Exception](https://shipilev.net/blog/2014/exceptional-performance/)
2. [Throwable class](https://docs.oracle.com/javase/9/docs/api/java/lang/Throwable.html)

**Comment by joshfree** [comment]
Thanks for filing this request @David-Noble-at-work.  @alzimmermsft can you please include this in your azure-core backlog planning?

**Comment by alzimmermsft** [comment]
Added this issue to the backlog, also read through the articles you mentioned @David-Noble-at-work and this change makes a lot of sense to make. I'll make sure to prioritize it relatively high on the backlog.

**Comment by alzimmermsft** [comment]
Didn't mean to close issue, just to comment.
