### ISSUE TITLE
[TA] Remove output type public constructors

### ISSUE THREAD

**Issue by mssfang** [Azure/azure-sdk-for-java#10346]
***DocumentResult types have public constructors. It should be hide from user. We doing it internally.

**Comment by mssfang** [comment]
The new properties in responses can be added after GA. Keeping the constructor as public API are breaking APIs, which can't be the path forward.

 As the non-public constructor is required, such as `ExtractKeyPhraseResult` 

```
    public ExtractKeyPhraseResult(String id, TextDocumentStatistics textDocumentStatistics,
        TextAnalyticsError error, IterableStream<String> keyPhrases) {
        super(id, textDocumentStatistics, error);
        this.keyPhrases = keyPhrases == null ? new IterableStream<>(new ArrayList<>()) : keyPhrases;
    }
```

we will remove the `public` modifier, but keep it package-private will not be helpful because any class in the parent package of this package will not be able to see it.

Looking for a way to make `ExtractKeyPhraseResult` hide from user and still be able to initialize from internal.


@JonathanGiles @srinathnarayanan

**Comment by anuchandy** [comment]
@mssfang, the apporach team agreed on is below:


Declare these models as a contract - as an interface and keep them in `com.azure.<service>.models` package. We will have the implementation of such a contract.

[`interface` is preferred over `abstract class` given it is clean and easy to mock by test frameworks]

The implementation of these models can reside: in `com.azure.<service>.implementation.models` package, with the public constructor. This the pattern we've been following for client types as well i.e., all implementations stay under implementation package.

The implementation class name should have a suffixed `Impl`.  For example: If the model type name is `PageBlobItem`, then the implementation will be `PageBlobItemImpl`.

example:

##### Contract type that user consumes:

```java
// com.azure.storage.blob.models

public interface PageBlobItem {
  String getFirst();
  String getSecond();
 }
```

##### Internal implementation of the contract:

```java
// com.azure.storage.blob.implementation.models

final class PageBlobItemImpl implements PageBlobItem {
  private final String first;
  private final String second;
 
  PageBlobItemImpl(String first, String second) {
     this.first = first;
     this.second = second;
  }
 
  @Override
  public String getFirst() { return first; }
 
  @Override
  public String getSecond() { return second; }
}
```

**Comment by anuchandy** [comment]
Also, use this approach (interface based) only if necessary, in this specific case, to hide the constructor.

**Comment by mssfang** [comment]
As discussed offline, interface approach will no longer needed, but maintain a constructor for required parameters and setter for optional parameters.
