### ISSUE TITLE
Discussion: State transitions for lifecycle of a VM

### ISSUE THREAD

**Issue by gkapagunta** [Azure/azure-sdk-for-java#1036]
The `powerState`and the `provisioningState`codes in the `instanceView.getStatuses` are pretty much encrypted, and no documentation is available to understand the possible combinations. I need to monitor the states of a VM which is being dynamically created and deleted on-demand. Would like to understand how to interpret the codes and it's values returned.

**Comment by petergardfjall** [comment]
I'm also in a state of total confusion about these states and how they, together, represents the state of a VM. I've tried to find some official documentation of Azure VM lifecycle and state transitions but I haven't been able to find _anything_, which I find quite remarkable.

**Comment by anuchandy** [comment]
We have an enum for [PowerState](https://github.com/Azure/azure-sdk-for-java/blob/master/azure-mgmt-compute/src/main/java/com/microsoft/azure/management/compute/PowerState.java).

`ProvisioningState` is not a fixed set of values, different RPs has their own values specific to the service.

**Comment by anuchandy** [comment]
Ok, the question is about documentation for various power state and provisioning state combinations, you can find this info here https://docs.microsoft.com/en-us/rest/api/compute/virtualmachines/virtualmachines-state

**Comment by martinsawicki** [comment]
the docs are there now
