### ISSUE TITLE
Try to support activityId for single partition calls when running them through cross partition pipeline.

### ISSUE THREAD

**Issue by mbhaskar** [Azure/azure-sdk-for-java#10373]
Currently, even single partition queries run through cross partition pipeline due to which they may not have the activityId in the feedresponse. This should be validated to see if we can support having an activityId in case of single partition query.

**Comment by kushagraThapar** [comment]
@mbhaskar - I believe this addressed already, please update it.

**Comment by kushagraThapar** [comment]
This has been completed.
