### ISSUE TITLE
[FEATURE REQ] Add support for AZURE_CLIENT_ID environment variable to ManagedIdentityCredential

### ISSUE THREAD

**Issue by jongio** [Azure/azure-sdk-for-java#10372]
**Library or service name.**
Azure Identity
 
**Is your feature request related to a problem? Please describe.**
Developers need to be able to specify which AZURE_CLIENT_ID Managed Identity Credential with an environment variable. 

#5967
#7117

**Comment by jongio** [comment]
Please follow up with @schaabs before implementing.

**Comment by joshfree** [comment]
@jianghaolu @g2vinay please take a look this week and follow up.

**Comment by jongio** [comment]
@schaabs - Had a comment about potentially not supporting this as an ENV, so please do sync with him.  Thanks a lot, Jon

**Comment by g2vinay** [comment]
yeah, from the discussion which happened last.
The stance was to limit the use of environment variables outside Environment credential as much as possible.

**Comment by jongio** [comment]
I personally think we should support AZURE_CLIENT_ID env var for Managed Identity as I have 2 customer cases where they could have used it, but had to manually set it.  They thought the env var would work because they used it in other Credentials, but it didn't.  They wasted time researching and then more time coding a solution around it.

The customer benefit is worth the effort IMO.

**Comment by jianghaolu** [comment]
I agree. Also we already rely on environment variables elsewhere like SharedTokenCacheCredential. Supporting this environment variable allows many users to use `DefaultAzureCredential` with managed identities, instead of calling different credentials explicitly. This will make their code more maintainable, with better logging we are adding, and more secure.

**Comment by joshfree** [comment]
We discussed this offline today and will be moving this to next semester.

**Comment by g2vinay** [comment]
Closing this issue, 
as we had discussed to MI client id setter on DAC and not add this env var across all languages.
