### ISSUE TITLE
Failed to create package using mvn

### ISSUE THREAD

**Issue by ks2882** [Azure/azure-sdk-for-java#1037]
I am trying to create package using mvn but while running both mvn test and mvn package ; the process is getting hanged while testing. There is no error given , it just failed to return anything. I had changed testconfiguration.xml to reflect my blob account name. Below is the log files I am getting. 

Is there something else that needs to be done to get jre ?

[INFO] Scanning for projects...
[INFO]
[INFO] ------------------------------------------------------------------------
[INFO] Building Microsoft Azure Storage Client SDK 4.3.0
[INFO] ------------------------------------------------------------------------
[INFO]
[INFO] --- maven-resources-plugin:2.5:resources (default-resources) @ azure-storage ---
[debug] execute contextualize
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] skip non existing resourceDirectory /home/adminhorton/kspark/azure-storage-java-master/src/main/resources
[INFO]
[INFO] --- maven-compiler-plugin:2.3.2:compile (default-compile) @ azure-storage ---
[INFO] Nothing to compile - all classes are up to date
[INFO]
[INFO] --- maven-resources-plugin:2.5:testResources (default-testResources) @ azure-storage ---
[debug] execute contextualize
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] Copying 2 resources
[INFO]
[INFO] --- maven-compiler-plugin:2.3.2:testCompile (default-testCompile) @ azure-storage ---
[INFO] Compiling 52 source files to /home/adminhorton/kspark/azure-storage-java-master/target/test-classes
[INFO]
[INFO] --- maven-surefire-plugin:2.13:test (default-test) @ azure-storage ---
[INFO] Surefire report directory: /home/adminhorton/kspark/azure-storage-java-master/target/surefire-reports

-------------------------------------------------------
 T E S T S
-------------------------------------------------------
parallel='classes', perCoreThreadCount=true, threadCount=2, useUnlimitedThreads=false
Running com.microsoft.azure.storage.StorageAccountTests
Tests run: 33, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.057 sec
Running com.microsoft.azure.storage.StorageUriTests
Tests run: 6, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.071 sec

[com.microsoft.azure.storage.StorageAccountTests.txt](https://github.com/Azure/azure-sdk-for-java/files/439879/com.microsoft.azure.storage.StorageAccountTests.txt)
[com.microsoft.azure.storage.StorageUriTests.txt](https://github.com/Azure/azure-sdk-for-java/files/439878/com.microsoft.azure.storage.StorageUriTests.txt)

[com.microsoft.azure.storage.StorageAccountTests.txt](https://github.com/Azure/azure-sdk-for-java/files/439881/com.microsoft.azure.storage.StorageAccountTests.txt)
[com.microsoft.azure.storage.StorageUriTests.txt](https://github.com/Azure/azure-sdk-for-java/files/439882/com.microsoft.azure.storage.StorageUriTests.txt)

**Comment by jianghaolu** [comment]
Looks like an issue in the storage blob sdk. Please file an issue in https://github.com/azure/azure-storage-java. Thanks!
