### ISSUE TITLE
Revisit GPG signing

### ISSUE THREAD

**Issue by mitchdenny** [Azure/azure-sdk-for-java#10388]
We need to revisit GPG signing for the Java pipeline. At the moment we are using the Maven GPG plugin version 1.6 which has a number of compatibility issues with more recent versions of GNU GPG. What I'd like to do is upgrade to version 1.7 of the plug-in that was just recently released which has fixes to address some of these compatibility issues.

At the same time I would like to change the way that the GPG signing key is supplied to the pipeline and how the passphrase is handled.

**Comment by weshaggard** [comment]
cc @JimSuplizio 

This seems to have hit a lot this last release. Maybe one mitigation we can try is to add a retry loop if the connection fails. I couldn't find any options on gpg-connect-agent that allow us to increase the 5 second connection timeout but if we can figure out how to do that it could also work.

**Comment by mitchdenny** [comment]
Someone from another team reached out to me today to learn more about the way we sign and publish. I explained our hacky workaround to the way the tools work here and in the process learned that the Maven GPG Signing plugin has not been updated (there are commits, but not updated package).  So as yet there is no 1.7 version of the plugin.

I'm going to close this down because looking at our telemetry I'm not seeing any instances of this failure in our pipelines anymore. The current hack we have right now is as good as any other hack until Maven GPG 1.7 ships.

**Comment by JimSuplizio** [comment]
//CC @weshaggard @mikeharder 

I created a [tools PR](https://dev.azure.com/azure-sdk/internal/_git/azure-sdk-build-tools/pullrequest/734) to retry the reloadagent up to 5x, waiting 10 seconds in between each attempt. I'm running [java template release](https://dev.azure.com/azure-sdk/internal/_build/results?buildId=2613067&view=results) using a temporary PR to update the tools ref to point to my tools PR.
