### ISSUE TITLE
Add more tests and verify behaviour of settlement methods.

### ISSUE THREAD

**Issue by conniey** [Azure/azure-sdk-for-java#10412]
There are some test gaps and behaviour we have to verify in Service Bus.
- [x] Add tests for error scenarios
  - When we try to send a session message to a non-sessionful entity
  - When we try to create a session receiver from a non-session entity
- [ ] ServiceBusReceiverClient
   - [x] Unit Tests
   - [x] Integration tests are missing 
- [x] ServiceBusReceiverAsyncClient
  - Integration tests occasionally pass. Need to make them more stable. (ie. if one test case fails, the others are thrown off because we compare message ids.)
  - Verify that we can continuously send and fetch messages. (ie. have a message sender that sends a message every 250ms and verify that we keep receiving those messages after the creation of our receiver).
- [x] Shared connection
  - Verify that we can create multiple senders and receivers from the same connection
- [x] Verify the settlement methods on receiver link
  - For subscriptions, sometimes the settlements do not match. For example, completing the message on a non-session Topic keeps it alive. And on a sessionful Topic, will put it in the DLQ.

**Comment by hemanttanwar** [comment]
When we try to send a session message to a non-sessionful entity  : I tested in track 1 and this is not a error scenario.
