### ISSUE TITLE
Identity's changelog needs an unreleased entry for the current version

### ISSUE THREAD

**Issue by JimSuplizio** [Azure/azure-sdk-for-java#10426]
Identity's [changelog.md](https://github.com/Azure/azure-sdk-for-java/blob/master/sdk/identity/azure-identity/CHANGELOG.md#110-beta3-2020-04-07) only has an entry for the latest released version and needs an entry for the next unreleased version which should be.

## 1.1.0-beta.4 (Unreleased)

**Comment by g2vinay** [comment]
This is resolved.
