### ISSUE TITLE
Search: ListIndexes operation should return a pageable collection

### ISSUE THREAD

**Issue by heaths** [Azure/azure-sdk-for-java#10434]
The ListIndexes operation, because it can return up to 3000 entities for P3 plans and because indexes can be large and may grow in size, could be returned in pages in the future. To accomodate this now instead of making breaking changes later or adding "overloads" that return different objects, ListIndexes should be made pageable now.

**Comment by sima-zhu** [comment]
Java is using PageIterable API for all list operations.
Quote from team channel:
"In Java, paging infrastructure in a "get only one page" fashion where there is no get next page function, adding the get next page function would be an implementation code change."

Give the nature of Java paging, we would like to keep what currently have. Please feel free to reopen if you have strong feeling about this.
