### ISSUE TITLE
Azure storage file data lake Sample code is wrong

### ISSUE THREAD

**Issue by Luyunmt** [Azure/azure-sdk-for-java#10448]
1
Section : 
[Link](https://github.com/Azure/azure-sdk-for-java/blob/78e10d761b8abc5a36e829ce4fd8e46636ff4a0f/sdk/storage/azure-storage-file-datalake/src/samples/java/com/azure/storage/file/datalake/AppendFlushExample.java#L44)
[Link1](https://github.com/Azure/azure-sdk-for-java/blob/78e10d761b8abc5a36e829ce4fd8e46636ff4a0f/sdk/storage/azure-storage-file-datalake/src/samples/java/com/azure/storage/file/datalake/GetSetAccessControlExample.java#L47)
![image](https://user-images.githubusercontent.com/53427149/80073445-611cc080-857a-11ea-9644-65722989a868.png)

Suggestion:  
http--> https

2
Section : 
[Link](https://github.com/Azure/azure-sdk-for-java/blob/78e10d761b8abc5a36e829ce4fd8e46636ff4a0f/sdk/storage/azure-storage-file-datalake/src/samples/java/com/azure/storage/file/datalake/DirectoryExample.java#L29)
[Link1](https://github.com/Azure/azure-sdk-for-java/blob/78e10d761b8abc5a36e829ce4fd8e46636ff4a0f/sdk/storage/azure-storage-file-datalake/src/samples/java/com/azure/storage/file/datalake/DirectoryExample.java#L32)
![image](https://user-images.githubusercontent.com/53427149/80073698-b9ec5900-857a-11ea-9eab-9c90b19ec679.png)

Suggestion: 
![image](https://user-images.githubusercontent.com/53427149/80073939-13ed1e80-857b-11ea-879d-29f58a82e08a.png)

3
Section : 
[Link](https://github.com/Azure/azure-sdk-for-java/blob/78e10d761b8abc5a36e829ce4fd8e46636ff4a0f/sdk/storage/azure-storage-file-datalake/src/samples/java/com/azure/storage/file/datalake/DirectoryExample.java#L63)
![image](https://user-images.githubusercontent.com/53427149/80074407-b0afbc00-857b-11ea-9f24-8803db5c0ee4.png)

Suggestion: 
StorageErrorException--> DataLakeStorageException

**Comment by rickle-msft** [comment]
Hi, @Luyunmt. Thank you for these suggestions. We'll work on cleaning this up.

**Comment by parth704131** [comment]
What is sasToken ?@Luyunmt

**Comment by Luyunmt** [comment]
> What is sasToken ?@Luyunmt
DataLakeFileSystemClient dataLakeFileSystemClient = new DataLakeFileSystemClientBuilder().endpoint(ENDPOINT)
.sastoken("<your sastoken>")
.fileSystemName(fileSystemName).buildClient();

**Comment by tzhanl** [comment]
PR merged.
