### ISSUE TITLE
Azure storage blob cryptography Sample code is wrong

### ISSUE THREAD

**Issue by Luyunmt** [Azure/azure-sdk-for-java#10447]
1
[Link](https://github.com/Azure/azure-sdk-for-java/blob/78e10d761b8abc5a36e829ce4fd8e46636ff4a0f/sdk/storage/azure-storage-blob-cryptography/src/samples/java/com/azure/storage/blob/specialized/cryptography/JavaDocCodeSnippetsHelpers.java#L13)

![image](https://user-images.githubusercontent.com/53427149/80072416-c96aa280-8578-11ea-8025-7520d5905b18.png)

Reason:
![image](https://user-images.githubusercontent.com/53427149/80072496-e3a48080-8578-11ea-9982-938c10e91629.png)

Suggestion:
add value to key or keyresolver.

**Comment by tzhanl** [comment]
@jongio please review this issue.

**Comment by tzhanl** [comment]
PR merged.
