### ISSUE TITLE
[QUERY] Discussion on whether azure-core could/should unify read timeout exception

### ISSUE THREAD

**Issue by weidongxu-microsoft** [Azure/azure-sdk-for-java#10449]
**Query/Question**

Currently, netty and okhttp has different approach to configure read timeout.

netty uses `Mono/Flux.timeout` https://github.com/reactor/reactor-netty/issues/26#issuecomment-420372792 (alternatively `ReadTimeoutHandler`)

okhttp configures it in builder https://github.com/Azure/azure-sdk-for-java/blob/master/sdk/core/azure-core-http-okhttp/src/main/java/com/azure/core/http/okhttp/OkHttpAsyncHttpClientBuilder.java#L174

It is fine for different configuration on different http client implementation. (though desirable to have a unified configure, not the goal of this query.)

---

However in runtime, the exception would be different for different http client.

netty with `Mono/Flux.timeout` produces `java.util.concurrent.TimeoutException`

okhttp produces `java.net.SocketTimeoutException`

Tested with read timeout = 5 sec with following code (for netty, uses `httpClient.send(request).timeout(Duration.ofSeconds(5)).block()` to simulate [TimeoutPolicy](https://github.com/Azure/azure-sdk-for-java/blob/master/sdk/core/azure-core/src/main/java/com/azure/core/http/policy/TimeoutPolicy.java)).
```
        HttpRequest request = new HttpRequest(HttpMethod.GET, "https://httpbin.org/delay/10");
        HttpResponse response = httpClient.send(request).block();
```

This could be confusing for customer. Ideally the interaction on Azure Cloud with SDK should be agnostic to the choice of http client implementation.

---

***Why is this not a Bug or a feature Request?***
A clear explanation of why is this not a bug or a feature request?

**Setup (please complete the following information if applicable):**
 - IDE : [e.g. IntelliJ]
 - Version of the Library used : azue-core 1.4.0
 
 **Information Checklist**
 Kindly make sure that you have added all the following information above and checkoff the required fields otherwise we will treat the issuer as an incomplete report
- [x] Query Added
- [ ] Setup information Added

**Comment by alzimmermsft** [comment]
Related to #10396 and #10397 

@weidongxu-microsoft I'm planning on looking into this area around timeouts in the next week or so and I'm more than happy to discuss potential solutions. Another issue with the different timeout mechanisms is the Reactor's `timeout` is looking for an element to be emitted in the stream before triggering the timeout once it is subscribed, but this runs into issues with uploads where the heavy portion of the operation is request time and not response time.

**Comment by alzimmermsft** [comment]
@weidongxu-microsoft, #13845 and #13941 should trend us in the direction to resolve this issue.

**Comment by weidongxu-microsoft** [comment]
@alzimmermsft Great work. Now the netty would be much easier to configure.
