### ISSUE TITLE
Azure storage file share Sample code is wrong

### ISSUE THREAD

**Issue by Luyunmt** [Azure/azure-sdk-for-java#10450]
1
Section : 
[Link](https://github.com/Azure/azure-sdk-for-java/blob/78e10d761b8abc5a36e829ce4fd8e46636ff4a0f/sdk/storage/azure-storage-file-share/src/samples/java/com/azure/storage/file/share/AsyncSample.java#L26)
[Link1](https://github.com/Azure/azure-sdk-for-java/blob/78e10d761b8abc5a36e829ce4fd8e46636ff4a0f/sdk/storage/azure-storage-file-share/src/samples/java/com/azure/storage/file/share/DirectorySample.java#L29)
[Link2](https://github.com/Azure/azure-sdk-for-java/blob/78e10d761b8abc5a36e829ce4fd8e46636ff4a0f/sdk/storage/azure-storage-file-share/src/samples/java/com/azure/storage/file/share/DirectorySample.java#L32)
[Link3](https://github.com/Azure/azure-sdk-for-java/blob/78e10d761b8abc5a36e829ce4fd8e46636ff4a0f/sdk/storage/azure-storage-file-share/src/samples/java/com/azure/storage/file/share/ShareSample.java#L29)
[Link4](https://github.com/Azure/azure-sdk-for-java/blob/78e10d761b8abc5a36e829ce4fd8e46636ff4a0f/sdk/storage/azure-storage-file-share/src/samples/java/com/azure/storage/file/share/ShareSample.java#L73)
[Link5](https://github.com/Azure/azure-sdk-for-java/blob/78e10d761b8abc5a36e829ce4fd8e46636ff4a0f/sdk/storage/azure-storage-file-share/src/samples/java/com/azure/storage/file/share/ShareSample.java#L87)
![image](https://user-images.githubusercontent.com/53427149/80075095-bc4fb280-857c-11ea-95b0-bb035b801f63.png)

Suggestion:  
![image](https://user-images.githubusercontent.com/53427149/80075116-c4a7ed80-857c-11ea-8fa4-a626c467541b.png)

2
Section : 
[Link](https://github.com/Azure/azure-sdk-for-java/blob/78e10d761b8abc5a36e829ce4fd8e46636ff4a0f/sdk/storage/azure-storage-file-share/src/samples/java/com/azure/storage/file/share/FileSample.java#L40)
[Link1](https://github.com/Azure/azure-sdk-for-java/blob/78e10d761b8abc5a36e829ce4fd8e46636ff4a0f/sdk/storage/azure-storage-file-share/src/samples/java/com/azure/storage/file/share/FileSample.java#L47)
[Link2](https://github.com/Azure/azure-sdk-for-java/blob/78e10d761b8abc5a36e829ce4fd8e46636ff4a0f/sdk/storage/azure-storage-file-share/src/samples/java/com/azure/storage/file/share/FileSample.java#L67)
![image](https://user-images.githubusercontent.com/53427149/80075660-a2fb3600-857d-11ea-9431-4489a87a0bc0.png)

Suggestion: 
![image](https://user-images.githubusercontent.com/53427149/80075690-abec0780-857d-11ea-8f4b-68995dc0b1bc.png)

3
Section : 
[Link](https://github.com/Azure/azure-sdk-for-java/blob/78e10d761b8abc5a36e829ce4fd8e46636ff4a0f/sdk/storage/azure-storage-file-share/src/samples/java/com/azure/storage/file/share/FileSample.java#L74)
![image](https://user-images.githubusercontent.com/53427149/80076247-7e538e00-857e-11ea-9917-8f19d239eea9.png)

Suggestion: 
![image](https://user-images.githubusercontent.com/53427149/80076273-8a3f5000-857e-11ea-94a2-64909d69e77c.png)
  
4
Section : 
[Link](https://github.com/Azure/azure-sdk-for-java/blob/78e10d761b8abc5a36e829ce4fd8e46636ff4a0f/sdk/storage/azure-storage-file-share/src/samples/java/com/azure/storage/file/share/FileSample.java#L100)
![image](https://user-images.githubusercontent.com/53427149/80076589-02a61100-857f-11ea-8a21-148170870ebb.png)

Reason:
![image](https://user-images.githubusercontent.com/53427149/80076652-1487b400-857f-11ea-86e5-717b0ca3f8fa.png)
Suggestion:  
![image](https://user-images.githubusercontent.com/53427149/80076706-2406fd00-857f-11ea-9927-ca8a07f12cfb.png)

5
Section : 
[Link](https://github.com/Azure/azure-sdk-for-java/blob/78e10d761b8abc5a36e829ce4fd8e46636ff4a0f/sdk/storage/azure-storage-file-share/src/samples/java/com/azure/storage/file/share/ShareSample.java#L33)
![image](https://user-images.githubusercontent.com/53427149/80076896-5fa1c700-857f-11ea-95db-a07142436dee.png)

Suggestion: 
![image](https://user-images.githubusercontent.com/53427149/80077062-924bbf80-857f-11ea-9298-74834885ccd0.png)

**Comment by tzhanl** [comment]
@jongio please review this issue.

**Comment by tzhanl** [comment]
PR merged.
