### ISSUE TITLE
Azure storage blob Sample code is wrong

### ISSUE THREAD

**Issue by Luyunmt** [Azure/azure-sdk-for-java#10452]
1
Section : 
[Link](https://github.com/Azure/azure-sdk-for-java/blob/78e10d761b8abc5a36e829ce4fd8e46636ff4a0f/sdk/storage/azure-storage-blob/src/samples/java/com/azure/storage/blob/FileTransferExample.java#L87)
![image](https://user-images.githubusercontent.com/53427149/80078830-06876280-8582-11ea-97e4-279ecd429c63.png)

Reason:
![image](https://user-images.githubusercontent.com/53427149/80079043-549c6600-8582-11ea-8524-22d12c86e855.png)

Suggestion: 
Add code under line 87 as follow
![image](https://user-images.githubusercontent.com/53427149/80079225-90cfc680-8582-11ea-8426-4959f6a4bae6.png)

**Comment by tzhanl** [comment]
@jongio please review this issue.

**Comment by tzhanl** [comment]
PR merged.
