### ISSUE TITLE
Tracing OpenTelemetry  Sample code is wrong

### ISSUE THREAD

**Issue by Luyunmt** [Azure/azure-sdk-for-java#10453]
1
Section : 
[Link](https://github.com/Azure/azure-sdk-for-java/blob/master/sdk/core/azure-core-tracing-opentelemetry/src/samples/AsyncListKeyVaultSecretsSample.md)
![image](https://user-images.githubusercontent.com/53427149/80079544-0340a680-8583-11ea-90c7-00c312149fac.png)

Suggestion: 
Change code as follow:
![image](https://user-images.githubusercontent.com/53427149/80079580-0cca0e80-8583-11ea-9675-56fa972b7429.png)

2
Section : 
[Link](https://github.com/Azure/azure-sdk-for-java/blob/master/sdk/core/azure-core-tracing-opentelemetry/src/samples/CreateConfigurationSettingTracingSample.md)
![image](https://user-images.githubusercontent.com/53427149/80079853-6599a700-8583-11ea-8152-ebfcd3b770bb.png)

Suggestion: 
Change code as follow:
![image](https://user-images.githubusercontent.com/53427149/80079910-777b4a00-8583-11ea-876c-7cd6d3a4ca90.png)

3
Section : 
[Link](https://github.com/Azure/azure-sdk-for-java/blob/master/sdk/core/azure-core-tracing-opentelemetry/src/samples/ListKeyVaultSecretsTracingSample.md)
![image](https://user-images.githubusercontent.com/53427149/80080000-9548af00-8583-11ea-878a-71d9846acb16.png)

Suggestion: 
Change code as follow:
![image](https://user-images.githubusercontent.com/53427149/80080055-a2659e00-8583-11ea-848a-e6d62238479e.png)

4
Section : 
[Link](https://github.com/Azure/azure-sdk-for-java/blob/master/sdk/core/azure-core-tracing-opentelemetry/src/samples/PublishEventsTracingSample.md)
![image](https://user-images.githubusercontent.com/53427149/80080172-d2ad3c80-8583-11ea-8cac-f86f76a82f99.png)

Suggestion: 
Change code as follow:
![image](https://user-images.githubusercontent.com/53427149/80080199-dd67d180-8583-11ea-9191-a771388cf115.png)

**Comment by tzhanl** [comment]
@jongio please review this issue.
