### ISSUE TITLE
Azure storage blob batch Sample code is wrong

### ISSUE THREAD

**Issue by Luyunmt** [Azure/azure-sdk-for-java#10451]
1
Section : 
[Link](https://github.com/Azure/azure-sdk-for-java/blob/master/sdk/storage/azure-storage-blob-batch/src/samples/java/com/azure/storage/blob/batch/BlobBatchAsyncClientJavaDocCodeSnippets.java#L21)
[Link1](https://github.com/Azure/azure-sdk-for-java/blob/master/sdk/storage/azure-storage-blob-batch/src/samples/java/com/azure/storage/blob/batch/BlobBatchClientBuilderJavaDocCodeSnippets.java#L14)
[Link2](https://github.com/Azure/azure-sdk-for-java/blob/master/sdk/storage/azure-storage-blob-batch/src/samples/java/com/azure/storage/blob/batch/BlobBatchClientBuilderJavaDocCodeSnippets.java#L15)
[Link3](https://github.com/Azure/azure-sdk-for-java/blob/master/sdk/storage/azure-storage-blob-batch/src/samples/java/com/azure/storage/blob/batch/BlobBatchClientJavaDocCodeSnippets.java#L24)
[Link4](https://github.com/Azure/azure-sdk-for-java/blob/master/sdk/storage/azure-storage-blob-batch/src/samples/java/com/azure/storage/blob/batch/BlobBatchJavaDocCodeSnippets.java#L16)
![image](https://user-images.githubusercontent.com/53427149/80077601-4ea58580-8580-11ea-951c-8c1976176c75.png)

Suggestion:  
Add .endpoint().sastoken()

**Comment by tzhanl** [comment]
@jongio please review this issue.

**Comment by tzhanl** [comment]
PR merged.
