### ISSUE TITLE
Introduce JDK 17 to live test matrix

### ISSUE THREAD

**Issue by sima-zhu** [Azure/azure-sdk-for-java#10465]
Java need JDK 12 to test JDK httpclient in live run. We need a new VM (Win + Jdk 12) in devOp matrix.

@JimSuplizio Could you help look into this?

**Comment by JimSuplizio** [comment]
/CC @mitchdenny @danieljurek 
@sima-zhu, you're going to end up having to Java 12 to the test matrix though unless there's a limiting factor it'll run for everything. I'm assuming that along with the live run you're also going to need to run normally, against the recordings. You're going to need to add the configuration to templates [archetype-sdk-client.yml](https://github.com/Azure/azure-sdk-for-java/blob/master/eng/pipelines/templates/jobs/archetype-sdk-client.yml) and [archetype-sdk-tests.yml](https://github.com/Azure/azure-sdk-for-java/blob/master/eng/pipelines/templates/jobs/archetype-sdk-tests.yml). If only the httpclient library needs this JDK 12 run then you're going to have to define something in it's ci.yml that you can key off of so only it would run this extra run in the matrix.

**Comment by sima-zhu** [comment]
This is needed for archetype-sdk-tests.yml. We can have it in archetype-sdk-client.yml as well if everything runs fine.

The question is whether it is supported by devOp. What's the setting for java 12?

**Comment by sima-zhu** [comment]
https://github.com/Azure/azure-sdk-for-java/pull/10459

**Comment by mitchdenny** [comment]
The value for Java 12 should be ```1.12``` in the matrix.

**Comment by JimSuplizio** [comment]
> The value for Java 12 should be `1.12` in the matrix.

@mitchdenny, I don't think there is a Java 12 yet. @sima-zhu was already using [1.12 in her PR](https://github.com/Azure/azure-sdk-for-java/pull/10459/files#diff-2c092bb34841b77838298f0d852da820R53) and [it doesn't look like devops supports that version yet](https://dev.azure.com/azure-sdk/internal/_build/results?buildId=369647&view=logs&j=364de821-210b-596e-0928-4e0d2b619091&t=82906b44-a4da-5f72-954a-e176d503904e).

**Comment by mitchdenny** [comment]
@JimSuplizio correct. And I just had a look at the virtual environments repo and they haven't loaded it into the image yet. We can probably submit a PR but it would take ~1 month to get that through the pipeline.

**Comment by weshaggard** [comment]
If we need to get ahead of the DevOps image we could update their script (https://github.com/actions/virtual-environments/blob/master/images/win/scripts/Installers/Install-JavaTools.ps1) and use it to install Java 12 on our runs.

**Comment by sima-zhu** [comment]
Thanks for advice! I will try to update the above script.

**Comment by sima-zhu** [comment]
https://github.com/actions/virtual-environments/pull/795

This is the PR requested to add Java 13 since I cannot found Java 12 from download list. 
https://www.azul.com/downloads/azure-only/zulu/?os=windows&architecture=x86-64-bit&package=jdk

@mitchdenny @JimSuplizio @weshaggard Do you know how to fast track the PR? Any person of contact?

**Comment by JimSuplizio** [comment]
@sima-zhu You've already got someone looking at your PR, I think that's some goodness. I find it odd that there's no Java 12 build though.

**Comment by sima-zhu** [comment]
The code has merged into virtual-environments.

It will take 1~2 week to propagate to all VMs.

Will continue work on this in the middle of next release.

**Comment by sima-zhu** [comment]
Java 13 does not compatible with  mockito extension mechanism which failed our tests. Open an issue to mockito team.
https://github.com/mockito/mockito/issues/1969

**Comment by kurtzeborn** [comment]
@alzimmermsft, it looks like this needs input from the Java team, so reassigning to you for follow up.

**Comment by alzimmermsft** [comment]
This will target the latest version and will then be removed for Java 17 when that comes out

**Comment by alzimmermsft** [comment]
Resolved by #27938
