### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by saralpa** [Azure/azure-sdk-for-java#10461]
**Describe the bug**
Java v12 version, list blob is not working as expected. It doesn't give the result blob list. It returns null. But sometimes, it returns value. I am experiencing a weird behavior.  

***Exception or Stack Trace***
ListBlobs returns null 

**To Reproduce**

***Code Snippet***
`StorageSharedKeyCredential credential = new StorageSharedKeyCredential(getAccountName(), AccountKey);
BlobServiceAsyncClient storageClient = new BlobServiceClientBuilder().endpoint(endpoint).sasToken(sasSource).credential(credential).buildAsyncClient();
			
BlobContainerAsyncClient blobContainerClient= new BlobContainerClientBuilder().endpoint(endpoint).sasToken(sasSource).containerName(sourceAccountConnectionVo.getContainerName()).buildAsyncClient();

List<String> results = new ArrayList<>();
ListBlobsOptions options = new ListBlobsOptions().setDetails(new BlobListDetails().setRetrieveMetadata(true));
List<String> results = new ArrayList<>();
blobContainerClient.listBlobs(options) .subscribe(response ->{
	        	results.add(response.getName());
	        });`

**Expected behavior**
In results we should get list of blobs in container

**Screenshots**

**Setup (please complete the following information):**
 - IDE :  STS
 - Version of the Library used - V 12.0.6

**Additional context**

**Information Checklist**
Kindly make sure that you have added all the following information above and checkoff the required fields otherwise we will treat the issuer as an incomplete report
- [  ] Bug Description Added
- [ ] Repro Steps Added
- [ ] Setup information Added

**Comment by anuchandy** [comment]
@saralpa - could you check if this is the case? - https://github.com/Azure/azure-sdk-for-java/wiki/Frequently-Asked-Questions#my-app-uses-the-async-client-libraries-but-it-never-seems-to-get-any-results

**Comment by saralpa** [comment]
I have added block now, but it has not found.

`PagedFlux<BlobItem> result = container.listBlobs();
	  result.subscribe(response -> {
	      System.out.println(response.getName());
	  }).block;`

It gives me error : block cannot be resolved or is not a field
I checked  I have added only this dependency :
 <dependencies>
    <dependency>
    <groupId>com.azure</groupId>
    <artifactId>azure-storage-blob</artifactId>
    <version>12.6.0</version>
</dependency>

Do I need to add any other dependency as well for block.

**Comment by rickle-msft** [comment]
@saralpa `block` is a method, not a field, so you need to call it as `block()`.

**Comment by saralpa** [comment]
I tried using block() as a method also. Still the issue remains the same. I checked the azure folder also, It has dependency added of v12 version  only. Here is my dependency tree.

`[INFO] PocBulkExport:PocBulkExport:jar:0.0.1-SNAPSHOT
[INFO] +- com.azure:azure-storage-blob:jar:12.6.0:compile
[INFO] |  +- com.azure:azure-core:jar:1.4.0:compile
[INFO] |  |  +- com.fasterxml.jackson.datatype:jackson-datatype-jsr310:jar:2.10.1:compile
[INFO] |  |  +- com.fasterxml.jackson.dataformat:jackson-dataformat-xml:jar:2.10.1:compile
[INFO] |  |  |  +- com.fasterxml.jackson.module:jackson-module-jaxb-annotations:jar:2.10.1:compile
[INFO] |  |  |  |  +- jakarta.xml.bind:jakarta.xml.bind-api:jar:2.3.2:compile
[INFO] |  |  |  |  \- jakarta.activation:jakarta.activation-api:jar:1.2.1:compile
[INFO] |  |  |  +- org.codehaus.woodstox:stax2-api:jar:4.2:compile
[INFO] |  |  |  \- com.fasterxml.woodstox:woodstox-core:jar:6.0.2:compile
[INFO] |  |  +- org.slf4j:slf4j-api:jar:1.7.28:compile
[INFO] |  |  +- io.projectreactor:reactor-core:jar:3.3.3.RELEASE:compile
[INFO] |  |  |  \- org.reactivestreams:reactive-streams:jar:1.0.3:compile
[INFO] |  |  \- io.netty:netty-tcnative-boringssl-static:jar:2.0.27.Final:compile
[INFO] |  \- com.azure:azure-storage-common:jar:12.6.0:compile
[INFO] |     \- com.azure:azure-core-http-netty:jar:1.5.0:compile
[INFO] |        +- io.netty:netty-handler:jar:4.1.45.Final:compile
[INFO] |        |  +- io.netty:netty-common:jar:4.1.45.Final:compile
[INFO] |        |  +- io.netty:netty-transport:jar:4.1.45.Final:compile
[INFO] |        |  |  \- io.netty:netty-resolver:jar:4.1.45.Final:compile
[INFO] |        |  \- io.netty:netty-codec:jar:4.1.45.Final:compile
[INFO] |        +- io.netty:netty-handler-proxy:jar:4.1.45.Final:compile
[INFO] |        |  \- io.netty:netty-codec-socks:jar:4.1.45.Final:compile
[INFO] |        +- io.netty:netty-buffer:jar:4.1.45.Final:compile
[INFO] |        +- io.netty:netty-codec-http:jar:4.1.45.Final:compile
[INFO] |        +- io.netty:netty-codec-http2:jar:4.1.45.Final:compile
[INFO] |        +- io.netty:netty-transport-native-unix-common:jar:4.1.45.Final:compile
[INFO] |        +- io.netty:netty-transport-native-epoll:jar:linux-x86_64:4.1.45.Final:compile
[INFO] |        \- io.projectreactor.netty:reactor-netty:jar:0.9.5.RELEASE:compile
[INFO] +- org.springframework.boot:spring-boot-starter-web:jar:2.2.6.RELEASE:compile
[INFO] |  +- org.springframework.boot:spring-boot-starter:jar:2.2.6.RELEASE:compile
[INFO] |  |  +- org.springframework.boot:spring-boot:jar:2.2.6.RELEASE:compile
[INFO] |  |  +- org.springframework.boot:spring-boot-autoconfigure:jar:2.2.6.RELEASE:compile
[INFO] |  |  +- org.springframework.boot:spring-boot-starter-logging:jar:2.2.6.RELEASE:compile
[INFO] |  |  |  +- ch.qos.logback:logback-classic:jar:1.2.3:compile
[INFO] |  |  |  |  \- ch.qos.logback:logback-core:jar:1.2.3:compile
[INFO] |  |  |  +- org.apache.logging.log4j:log4j-to-slf4j:jar:2.12.1:compile
[INFO] |  |  |  |  \- org.apache.logging.log4j:log4j-api:jar:2.12.1:compile
[INFO] |  |  |  \- org.slf4j:jul-to-slf4j:jar:1.7.30:compile
[INFO] |  |  +- jakarta.annotation:jakarta.annotation-api:jar:1.3.5:compile
[INFO] |  |  +- org.springframework:spring-core:jar:5.2.5.RELEASE:compile
[INFO] |  |  |  \- org.springframework:spring-jcl:jar:5.2.5.RELEASE:compile
[INFO] |  |  \- org.yaml:snakeyaml:jar:1.25:runtime
[INFO] |  +- org.springframework.boot:spring-boot-starter-json:jar:2.2.6.RELEASE:compile
[INFO] |  |  +- com.fasterxml.jackson.datatype:jackson-datatype-jdk8:jar:2.10.3:compile
[INFO] |  |  \- com.fasterxml.jackson.module:jackson-module-parameter-names:jar:2.10.3:compile
[INFO] |  +- org.springframework.boot:spring-boot-starter-tomcat:jar:2.2.6.RELEASE:compile
[INFO] |  |  +- org.apache.tomcat.embed:tomcat-embed-core:jar:9.0.33:compile
[INFO] |  |  +- org.apache.tomcat.embed:tomcat-embed-el:jar:9.0.33:compile
[INFO] |  |  \- org.apache.tomcat.embed:tomcat-embed-websocket:jar:9.0.33:compile
[INFO] |  +- org.springframework.boot:spring-boot-starter-validation:jar:2.2.6.RELEASE:compile
[INFO] |  |  +- jakarta.validation:jakarta.validation-api:jar:2.0.2:compile
[INFO] |  |  \- org.hibernate.validator:hibernate-validator:jar:6.0.18.Final:compile
[INFO] |  |     +- org.jboss.logging:jboss-logging:jar:3.3.2.Final:compile
[INFO] |  |     \- com.fasterxml:classmate:jar:1.3.4:compile
[INFO] |  +- org.springframework:spring-web:jar:5.2.5.RELEASE:compile
[INFO] |  |  \- org.springframework:spring-beans:jar:5.2.5.RELEASE:compile
[INFO] |  \- org.springframework:spring-webmvc:jar:5.2.5.RELEASE:compile
[INFO] |     +- org.springframework:spring-aop:jar:5.2.5.RELEASE:compile
[INFO] |     +- org.springframework:spring-context:jar:5.2.5.RELEASE:compile
[INFO] |     \- org.springframework:spring-expression:jar:5.2.5.RELEASE:compile
[INFO] +- org.apache.commons:commons-lang3:jar:3.10:compile
[INFO] \- com.fasterxml.jackson.core:jackson-databind:jar:2.11.0.rc1:compile
[INFO]    +- com.fasterxml.jackson.core:jackson-annotations:jar:2.11.0.rc1:compile
[INFO]    \- com.fasterxml.jackson.core:jackson-core:jar:2.11.0.rc1:compile
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS`

**Comment by rickle-msft** [comment]
Sorry, I misread your code earlier and stopped after seeing `block`. You cannot call both `subscribe()` and `block()`. When you call `subscribe()` you get back a `Disposable` which allows you to cancel the async operation, but you cannot block on this object. If you want to ensure the method in question blocks, you simply call `block()` on the operation (the type which has a `block()` method is a `Mono` or possibly a `Flux`). Calling `block()` will also subscribe internally and then wait for completion.

**Comment by joshfree** [comment]
Hi @saralpa, it looks like @rickle-msft has followed up and answered your question, so I'm now closing this issue.

Feel free to reactivate and provide more details or open a new issue if there's additional topics.

Thanks again for filing the GitHub issue!
