### ISSUE TITLE
[BUG] Revisit ReactorNettyHttpResponse::close()

### ISSUE THREAD

**Issue by anuchandy** [Azure/azure-sdk-for-java#10467]
It looks like there are cases where when `ReactorNettyHttpResponse::close()` is called the connection is in the disposed state but the underlying body is not drained, which can result in leak warnings from netty. 

Need to followup with the reactor-netty team to understand the behavior of connection disposal.

This is not impacting the majority of the cases since almost all cases either we subscribe to the body in RestPoxy or by the user when downloading as raw ByteBuf. One case in key-vault revealed this issue where it was not disposing the body inside the policy and was expecting close() to do it

**Comment by krishgeeneuron** [comment]
Hi,

We are facing the same issue with azure keyvault 4.1.5. Please could someone help us identify the right version the below leak issue is fixed. Is there any azure key vault version below 4.2.0 which has the fix ?

{
"timestamp": 1625580889173,
"status": 500,
"error": "Internal Server Error",
"message": "Request processing failed; nested exception is java.lang.RuntimeException: Max retries 3 times exceeded. Error Details: failed to allocate 16777216 byte(s) of direct memory (used: 486539271, max: 501743616)"
}

**Comment by trask** [comment]
We ran across this when porting from from Apache HttpClient to Azure SDK HttpClient.

Here's a small repro in case it helps with investigation: https://github.com/trask/netty-bytebuf-leak-repro

In the meantime, always consuming the response (even in cases where we don't require it) prevents the issue from occurring.

**Comment by alzimmermsft** [comment]
Thank you for the reproduction of this @trask!

**Comment by alzimmermsft** [comment]
@krishgeeneuron, unfortunately there are no versions of KeyVault Keys `4.1.x` that contain of fix for the error you've seen. Any version later than `4.2.3` should contain a fix where retried exceptions consume the error response body before retrying, resolving the `ByteBuf` leak issue.

**Comment by alzimmermsft** [comment]
@anuchandy, is the goal of this issue to resolve `ByteBuf` leaks when using Azure SDKs with the Netty `HttpClient` implementation or to resolve any usage of the Netty `HttpClient` implementation? If it is the former this has already be resolved as `azure-core` will handle consuming the response body on an error retry attempt, if it is the latter the Netty `HttpClient` implementation assumes that the caller will handle the consumption of the body.

**Comment by anuchandy** [comment]
Hi @alzimmermsft - At that time, it was that - 

1. Get Netty `HttpResponse` object (that composes the `Flux(ByteBuf>` body object)
2. Directly call `close()` on the parent `HttpResponse` object without consuming its body object.
3. Then this was leaking the body.
