### ISSUE TITLE
[QUERY] Accessing secondary site of RA-GRS storage account

### ISSUE THREAD

**Issue by AGT89** [Azure/azure-sdk-for-java#10489]
**Query/Question**
How can we read from the secondary site of a storage account configured using RA-GRS using the v12 SDK? Previous versions had awareness of the `LocationMode`, but this version doesn't appear to.

***Why is this not a Bug or a feature Request?***
Request for information on how to do something that was possible in previous SDK versions (e.g. the sample here: https://github.com/Azure-Samples/storage-java-ha-ra-grs/blob/master/RAGRS/src/main/java/AzureApp/App.java)

**Comment by rickle-msft** [comment]
Hi @AGT89. Thanks for your question. At the moment, secondaries are treated no different from primaries in the sense that you simply create a client with an endpoint pointing to a secondary location. So instead of setting a field saying which location you'd like to target, you create a different client with the url to the secondary. You can then use that client to perform any operations that are available on a secondary. 

Please let me know if you have further questions.

**Comment by AGT89** [comment]
Thanks @rickle-msft, that's exactly what I tried, however I can't get it working with the token based credentials we're using.

The following works with the primary endpoint but fails with a 403 when talking to the secondary endpoint.
```
        TokenCredential credential = new ClientSecretCredentialBuilder()
                .clientId(clientId)
                .clientSecret(clientSecret)
                .tenantId(tenant)
                .build();

        BlobServiceClient secondaryBlobServiceClient = new BlobServiceClientBuilder()
                .credential(credential)
                .endpoint("https://<account>-secondary.blob.core.windows.net/")
                .httpClient(client)
                .buildClient();
```

The error is:
```
Exception in thread "main" com.azure.storage.blob.models.BlobStorageException: Status code 403, "﻿<?xml version="1.0" encoding="utf-8"?><Error><Code>AuthenticationFailed</Code><Message>Server failed to authenticate the request. Make sure the value of Authorization header is formed correctly including the signature.
RequestId:...
Time:...</Message><AuthenticationErrorDetail>Audience validation failed. Audience did not match.</AuthenticationErrorDetail></Error>"
```

Are we meant to do something differently with the credentials to talk to the secondary endpoint?

**Comment by rickle-msft** [comment]
I'm not familiar with the "Audience validation failed" message. It looks like it might have something to do with the permissions your token has? But let me ask around and get back to you.

**Comment by rickle-msft** [comment]
@AGT89 Are you able to successfully use this token to access the secondary in any other context? An initial thought is that perhaps this is coming from doing cross-tenant operations, and the token is signed on your home tenant, not on the guest account for the destination tenant? 

I'm still asking around, too

**Comment by AGT89** [comment]
@rickle-msft I believe the token has the correct permissions as it works fine when talking to the primary endpoint for the account. I don't think I'm doing any cross-tenant operations.

I've looked into this further and it appears the the SDK is passing the incorrect scope for the bearer token when talking to the secondary endpoint. When using a `TokenCredential`, `BuilderHelper` sets the scope to be `<endpoint>/.default` but it appears this should always be the primary endpoint, so is incorrect when talking to the secondary. 

Can you confirm if this is a bug? Should I report it as such?

**Comment by rickle-msft** [comment]
Thank you for continuing your investigation. That sounds like a bug. The TokenCredential interface is not owned by Storage. Can you please share which implementation of TokenCredential you are using and I can track down the right team to help us make further progress.

**Comment by AGT89** [comment]
Thanks @rickle-msft. We're using it as in the code example above using `ClientSecretCredentialBuilder` from com.azure:azure-identity version 1.0.4. Where it appears to pass the incorrect scope is in `BuilderHelper` in com.azure:azure-storage-blob version 12.5.0. Is that the information you're after?

**Comment by rickle-msft** [comment]
Sorry I missed that in your earlier comment. Thanks! @g2vinay can you please take a look at what's going on with the scope in the TokenCredential implementation?

**Comment by AGT89** [comment]
@rickle-msft @g2vinay any update on this or ETA for a fix? Any workaround?

**Comment by g2vinay** [comment]
@AGT89 
if we need to pass the primary endpoint as the scope even when targeting secondary end points.
Then we'll need to update this logic in the Storage SDK. @rickle-msft 
I am just reproducing this and double-checking this behavior.
cc: @jianghaolu

**Comment by AGT89** [comment]
Thanks @g2vinay.

@rickle-msft do you have an ETA on when this bug in the storage SDK will be fixed?

**Comment by rickle-msft** [comment]
@AGT89 I am double checking with Vinay offline that the behavior did in fact reproduce and on next steps from there. We typically release at the beginning of each month, so our next scheduled release is the beginning of June. It looks like there's also an internal thread that is discussing this issue that may influence that date a bit.

**Comment by rickle-msft** [comment]
@AGT89 Out of curiosity, is there a particular reason you're accessing the secondary directly rather than setting the secondary on your retry options and letting the client automatically try the secondary in appropriate cases?

**Comment by AGT89** [comment]
@rickle-msft because that's what you suggested was the way to do it:

> At the moment, secondaries are treated no different from primaries in the sense that you simply create a client with an endpoint pointing to a secondary location. So instead of setting a field saying which location you'd like to target, you create a different client with the url to the secondary. You can then use that client to perform any operations that are available on a secondary.

**Comment by AGT89** [comment]
@rickle-msft We're trying to make use of RA-GRS, for example as outlined in https://docs.microsoft.com/en-us/azure/storage/common/storage-designing-ha-apps-with-ragrs but the SDK no longer supports LocationMode. In case of error on the primary, we don't want to try all requests to the primary and let them fail before trying the secondary.

**Comment by rickle-msft** [comment]
I see. Thank you for sharing. As I said, I was just curious. And thank you again for bringing this to our attention. 

It looks like we perhaps do need to update our builder logic. The request should be signed as though it is going to the primary, and we are simply using the url passed in, which is a secondary in your case. I'm not sure if we need to check if it's a secondary and strip "-secondary" or request that customers still pass in the primary if they are passing in a secondary. We'll have some discussion over here and figure out the best way to support this scenario.

**Comment by rickle-msft** [comment]
@AGT89 When you build your credential, are you passing in the secondary account url or the primary?
