### ISSUE TITLE
Improve client annotations for better tooling support

### ISSUE THREAD

**Issue by JonathanGiles** [Azure/azure-sdk-for-java#10486]
Client libraries are split into multiple layers, and it is very easy for them to get out of sync. It is also very difficult to ensure that full coverage of the backing service is reached. Today, when building a new client library, it is very difficult to have a high degree of certainty that everything is correctly implemented. Therefore, this issue aims to improve our confidence that client libraries are always meeting our high expectations of consistency and 100% service coverage.

There are two potential paths that could be taken, and it could be we end up using parts from both paths. The first path is to introduce additional annotations that client library developers will add to their client libraries, that annotate the relationships between builders, service clients, service methods, and service interfaces. The second path is to do without these annotations and make use of source code or byte-code analysis to determine code pathways. As mentioned, it may be that some source code / byte-code analysis can be done, with annotations or other means used to guide where necessary.

## API Changes:

The following changes outline what could be done for Java to improve annotations:

`@ServiceClient`:
 * Make the `builder()` field have a default null parameter. Making this nullable is to enable us to have child clients that are not directly buildable by the builder, but which will be referenced by the `childClients` and `@ReturnsClient` property and annotation instead.
 * Add a `Class<?>[] childClients()` to reference clients that this client can build.
 * Add a `Class<?> parentClient()` to reference the parent client that can create this client.
 * Add a `Class<?> siblingClient()` to reference the sibling of the client (i.e. the async variant for the sync client, and vice versa).

`@ServiceMethod`:
 * Add a `String[] serviceInterfaceMethods()` to reference the name(s) of the method in the service interface that this method directly calls. If a method annotated with `@ServiceMethod` does not specify any service interface methods, the service method must be an overload of a method that does, and this can be validated by code analysis.
 * Add a `minSupportedVersion()` and `maxSupportedVersion()` to reference the service version supported by the method. Min is required, but max can be null (to represent the latest version is supported).
 * Add a `String siblingMethod()` to reference the equivalent method in the other client (sync / async). This will only need to be specified when standard lookup rules when going between sync and async clients will fail to find the matching method.

`@ServiceInterface`:
 * Add a reference to the swagger URL.

Additional considerations:
 * Consider introducing a `@ReturnsClient` annotation for methods on service clients that return a child client. This same annotation can be used on the `build*()` methods on builder classes for the same reason.

Expected Outcome:
==========================
1) Introduce tooling that can create a model that represents all specified projects and inter-relationships, including:
   * Which client libraries are being represented (these are read in from a config file)
   * For each client library, its builders.
   * For each builder, which clients it can build.
   * For each client, which child clients it can build.
   * For each client, which service interface methods it implements.
   * For each client service method, which sibling methods they map to.
   * For all service clients, all service interface methods that are specified.
 
2) Export this model in a language-neutral JSON format.

3) Write a tool that can read in the model and validate expectations, including:
   * That all @ServiceClient's can be built - from a builder down to all other children.
   * Are all service interface methods being called in both an async and sync client?
   * Ensure that each service client has equivalent API with its sibling. This may be done based on the 'siblingMethod' property if specified, otherwise it should be done based on naming patterns.
   * Introduce support for suppressions to ignore some failures (when they are acceptable for a certain reason).
   * That all ServiceClient 'childClients' have a method that will return them (annotated with `@ReturnsClient`).
    * *(and so on and on...)*

4) Integrate this tooling into a Maven plugin, so that validation can occur as part of a build run.

5) Visualise the hierarchy from top-to-bottom in a generated HTML report by uploading the language-neutral JSON file into a tool such as APIView. This will obviously need improvements to be made to that tooling as well, to support this new data type.

**Comment by alzimmermsft** [comment]
> Make the `builder()` field have a default null parameter (we should only have ServiceClients that are buildable from a builder list the builder.)

Should this have no default value as we want these to have something set?

> Add a `String[] serviceInterfaceMethods()` to reference the name(s) of the method in the service interface that this method calls.

I'm not sure how I feel about adding this since the interface is in `implementation` when the client is using codegen, thoughts on slightly changing this to be links to the REST APIs a method would be calling? It is sometime still hard to make the jump from interface method to REST API call as some REST endpoints are split into multiple interface methods.

- Where would we use the `ServiceInterface` annotation? If this is going to be used in the generated code we should see if this could be added as part of codegen.
- Should a third parameter be added to the `minSupportedVersion` and `maxSupportedVersion` set which is `versionType`, an indicator of which `ServiceVersion` extension is being used.

**Comment by astubbs** [comment]
Why don't the implementations extend the interface directly? I.e. why doesn't KeyClient implement KeyService?

**Comment by JonathanGiles** [comment]
Correct - you can't have a common interface for sync and async clients where the APIs differ between sync and async. It would be nice if it were possible.
