### ISSUE TITLE
SearchServiceClient should expose a getSearchIndexClient instead of getIndexClient

### ISSUE THREAD

**Issue by heaths** [Azure/azure-sdk-for-java#10491]
Following general guidelines of naming methods containing the model on which they act or return, `SearchServiceClient.getIndexClient` should probably be `SearchServiceClient.getSearchIndexClient` (or whatever corresponds to what we end up naming `SearchIndexClient`.

**Comment by sima-zhu** [comment]
This has been addressed by https://github.com/Azure/azure-sdk-for-java/pull/11475
