### ISSUE TITLE
[Design] Java Guideline around the InputStream reset expectation

### ISSUE THREAD

**Issue by anuchandy** [Azure/azure-sdk-for-java#10499]
So far, sending a stream to service was limited to storage SDK. Given the storage service supports uploading streams in chunks, the SDK takes advantage of this and uses multiple HttpRequest to send the stream. Because of chunking, the seekable stream was not a requirement. 

Now, as we add support for more services, sending the stream to the service becomes a more common scenario. Many of these service API does not support chunking and those don't expect large streams either; hence we are required to send the stream in a single request.

The Sync client delegates API calls to Async client, as part of this, the user-provided `InputStream` is converted to `Flux<ByteBuffer>`. The azure-core retry policies assume that the `Flux<ByteBuffer>` is replayable, which requires the source `InputStream` to support reset.

#### Questions:

1. Should we make it clear in the Java guideline that we expect the user to provide a resettable stream? 
2. If InputStream reset is not a requirement, then what should be our story around generic retry policies that get applied to such APIs.

#### Example service:

Form Recognization is one of the services where we take InputStream from user
https://github.com/Azure/azure-sdk/issues/962

The FR guideline says:

```
Streams would need to be seekable to support retries.
```

#### Related discussions:

https://github.com/Azure/azure-sdk-for-java/pull/9953#discussion_r411589700

**Comment by JonathanGiles** [comment]
@srnagar and I spoke about this the other week. I believe he was going to look into an azure-core abstraction for exactly this kind of scenario. Srikanta - did you file an issue on this already, if not we can use this to discuss.

**Comment by anuchandy** [comment]
Closing this staled issue, will reopen if this is still an open item.
