### ISSUE TITLE
Unreachable code in SessionTokenHelper.java line 159

### ISSUE THREAD

**Issue by mshikaji** [Azure/azure-sdk-for-java#10493]
https://github.com/Azure/azure-sdk-for-java/blob/cd464cfe7c217332e1d02a29b7a78c3ff04ef9b6/sdk/cosmos/azure-cosmos/src/main/java/com/azure/cosmos/implementation/SessionTokenHelper.java#L158-L159

Line 159 is unreachable because the call to `getLocalSessionToken` in line 158 will always result in an `java.lang.IllegalStateException` due to the hard-coded empty string in the 3rd parameter.

https://github.com/Azure/azure-sdk-for-java/blob/cd464cfe7c217332e1d02a29b7a78c3ff04ef9b6/sdk/cosmos/azure-cosmos/src/main/java/com/azure/cosmos/implementation/SessionTokenHelper.java#L64-L73

We are experiencing the same issue in version 2.6.5 (`com.microsoft.azure.cosmosdb.internal.SessionTokenHelper`).

**Comment by joshfree** [comment]
Thanks for reporting this issue in Cosmos v2 @mshikaji.  I'm assigning this issue to @kushagraThapar to follow up.

@mshikaji please note that there are newer versions of the Cosmos SDK available for use (v3 and v4-beta) (https://mvnrepository.com/artifact/com.azure/azure-cosmos)

**Comment by kushagraThapar** [comment]
@mshikaji I will investigate this. Thanks for reporting.

**Comment by kushagraThapar** [comment]
This has been fixed in v4 SDK.
