### ISSUE TITLE
[BUG]There was an error using Storage SDK v11.0

### ISSUE THREAD

**Issue by 123Jun321** [Azure/azure-sdk-for-java#10517]
**Describe the bug**
Our App deployed in the Azure VM, and when the app ran 3 days or longer, it will report the error:
java.util.concurrent.TimeoutException: The source did not signal an event for 60 seconds and has been terminated.
If we restarted the VM, the app will run normally.

***Exception or Stack Trace***
[main.log](https://github.com/Azure/azure-sdk-for-java/files/4535020/main.log)

***Code Snippet***
`package com.hanshow.iotp.common.blobstorage.azure.v1;

import com.hanshow.iotp.common.http.header.HttpHeader;
import com.hanshow.iotp.common.http.header.Range;
import com.hanshow.iotp.common.util.Utils;
import com.hanshow.iotp.common.blobstorage.*;
import com.hanshow.iotp.common.blobstorage.azure.AzureStorageAccount;
import com.hanshow.iotp.common.util.DownloadStream;
import com.hanshow.iotp.common.util.TempFile;
import com.microsoft.azure.storage.blob.*;
import com.microsoft.azure.storage.blob.models.BlobGetPropertiesHeaders;
import com.microsoft.azure.storage.blob.models.BlobHTTPHeaders;
import com.microsoft.azure.storage.blob.models.BlobItem;
import com.microsoft.azure.storage.blob.models.BlobProperties;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

import javax.ws.rs.core.MediaType;
import javax.ws.rs.core.Response;
import java.io.*;
import java.nio.channels.AsynchronousFileChannel;
import java.nio.file.StandardOpenOption;

public class AzureBlobStorage implements BlobStorage {
    private final static Logger logger = LoggerFactory.getLogger(AzureBlobStorage.class);
    private final static int BLOCK_LENGTH = 8 * 1024 * 1024;
    private final static int MAX_RECORDS_PER_PAGE = 1000;

    private AzureStorageAccount account;
    private TempFile tempFile;

    public AzureBlobStorage(AzureStorageAccount account, TempFile tempFile) {
        this.account = account;
        this.tempFile = tempFile;
    }

    /**
     * 把名字转换为符合Azure规范的container name，规则如下:
     * 1. Container names must start with a letter or number, and can contain only letters,
     * numbers, and the dash (-) character.
     * 2. Every dash (-) character must be immediately preceded and followed by a letter or number;
     * consecutive dashes are not permitted in container names.
     * 3. All letters in a container name must be lowercase.
     * 4. Container names must be from 3 through 63 characters long.
     *
     * @param origin 原container name
     * @return 转换后符合Azure规则的container name
     */
    private String convertContainerName(String origin) {
        String name = origin
                .toLowerCase() // 转小写
                .replaceAll("[^a-z\\d]", "-") // 所有非英文字母和数字的字符转为dash(-)
                .replaceAll("[-]{2,}", "-"); // 所有连续两个及以上的dash转为1个dash

        // 删除头部的dash
        if (name.startsWith("-")) {
            name = name.substring(1);
        }

        // 删除尾部的dash
        int len = name.length();
        if (name.endsWith("-")) {
            name = name.substring(0, len - 1);
        }

        // 判断长度
        len = name.length();
        if (len > 63) {
            throw new IllegalArgumentException("container name too long");
        } else if (len < 3) {
            throw new IllegalArgumentException("container name too short");
        }

        return name;
    }

    private ContainerURL getContainer(String containerName) {
        String realName = convertContainerName(containerName);
        return account.getContainer(realName);
    }

    @Override
    public void getBlob(String containerName, String blobName, Range range, Callback callback)
            throws IOException {

        File file = tempFile.getTempFile("GET", ".blob");
        AsynchronousFileChannel fileChannel = AsynchronousFileChannel.open(file.toPath(),
                StandardOpenOption.CREATE, StandardOpenOption.TRUNCATE_EXISTING, StandardOpenOption.WRITE);
        ContainerURL containerURL = getContainer(containerName);
        BlobURL blobURL = containerURL.createBlobURL(blobName);

        BlobRange blobRange = null;
        if (range != null && range.isSpecified()) {
            blobRange = new BlobRange().withOffset(range.getStart());
            if (range.getEnd() != -1) {
                blobRange.withCount(range.getSize());
            }
        }

        TransferManager.downloadBlobToFile(fileChannel, blobURL, blobRange, null)
                .subscribe(headers -> {
                    fileChannel.close();
                    Response.Status status = range != null && range.isSpecified() ?
                            Response.Status.PARTIAL_CONTENT : Response.Status.OK;
                    BlobInfo blobInfo = new BlobInfo()
                            .withName(blobName)
                            .withETag(headers.eTag())
                            .withContentType(headers.contentType())
                            .withRange(headers.contentRange())
                            .withLength(headers.contentLength())
                            .withMD5(headers.blobContentMD5())
                            .withLastModified(headers.lastModified());
                    BlobStorageResponse bsr = new BlobStorageResponse(status, blobInfo, file);
                    callback.onSucceed(bsr);
                }, throwable -> {
                    fileChannel.close();
                    file.delete();
                    Response.Status status = Response.Status.INTERNAL_SERVER_ERROR;
                    if (throwable instanceof StorageException) {
                        StorageException se = (StorageException) throwable;
                        if (se.statusCode() == Response.Status.NOT_FOUND.getStatusCode()) {
                            status = Response.Status.NOT_FOUND;
                        } else {
                            logger.error("Failed to GET BLOB from Azure storage", throwable);
                        }
                    }
                    callback.onFailure(status, status.getReasonPhrase());
                });
    }

    @Override
    public void putBlob(String containerName, String blobName, InputStream inputStream, String contentType, Callback callback)
            throws IOException {

        File file = tempFile.getTempFile("PUT", ".blob");
        try (OutputStream outputStream = new FileOutputStream(file)) {
            DownloadStream.copy(inputStream, outputStream);
        } catch (Throwable t) {
            logger.warn("Failed to read BLOB body", t);
            file.delete();
            Response.Status status = Response.Status.BAD_REQUEST;
            callback.onFailure(status, status.getReasonPhrase());
            return;
        }

        AsynchronousFileChannel fileChannel = AsynchronousFileChannel.open(file.toPath());
        ContainerURL containerURL = getContainer(containerName);
        BlockBlobURL blobURL = containerURL.createBlockBlobURL(blobName);

        // Uploading a file to the blobURL using the high-level methods available in TransferManager class
        // Alternatively call the PutBlob/PutBlock low-level methods from BlockBlobURL type
        BlobHTTPHeaders headers = new BlobHTTPHeaders();
        if (contentType != null) {
            headers.withBlobContentType(contentType);
        } else {
            headers.withBlobContentType(MediaType.APPLICATION_OCTET_STREAM);
        }

        TransferManagerUploadToBlockBlobOptions options = new TransferManagerUploadToBlockBlobOptions(null, headers, null, null, null);
        TransferManager.uploadFileToBlockBlob(fileChannel, blobURL, BLOCK_LENGTH, null, options)
                .subscribe(response -> {
                    try {
                        fileChannel.close();
                        BlobInfo blobInfo = new BlobInfo()
                                .withName(blobName)
                                .withContentType(headers.blobContentType())
                                .withLength(file.length())
                                .withETag(response.eTag())
                                .withLastModified(response.lastModified())
                                .withMD5(response.response().rawHeaders().get(HttpHeader.CONTENT_MD5).toString());
                        BlobStorageResponse bsr = new BlobStorageResponse(Response.Status.CREATED, blobInfo);
                        callback.onSucceed(bsr);
                    } finally {
                        file.delete();
                    }
                }, throwable -> {
                    try {
                        fileChannel.close();
                        logger.error("Failed to PUT BLOB to Azure storage", throwable);
                        Response.Status status = Response.Status.INTERNAL_SERVER_ERROR;
                        callback.onFailure(status, status.getReasonPhrase());
                    } finally {
                        file.delete();
                    }
                });
    }

    @Override
    public void deleteBlob(String containerName, String blobName, Callback callback) {
        ContainerURL containerURL = getContainer(containerName);
        BlobURL blobURL = containerURL.createBlobURL(blobName);
        blobURL.delete().subscribe(
                response -> {
                    BlobStorageResponse bsr = new BlobStorageResponse(Response.Status.ACCEPTED);
                    callback.onSucceed(bsr);
                }, throwable -> {
                    Response.Status status = Response.Status.INTERNAL_SERVER_ERROR;
                    if (throwable instanceof StorageException) {
                        StorageException se = (StorageException) throwable;
                        if (se.statusCode() == Response.Status.NOT_FOUND.getStatusCode()) {
                            status = Response.Status.NOT_FOUND;
                        } else {
                            logger.error("Failed to DELETE BLOB from Azure storage", throwable);
                        }
                    }
                    callback.onFailure(status, status.getReasonPhrase());
                }
        );
    }

    @Override
    public void infoBlob(String containerName, String blobName, Callback callback) {
        ContainerURL containerURL = getContainer(containerName);
        BlobURL blobURL = containerURL.createBlobURL(blobName);
        blobURL.getProperties().subscribe(
                response -> {
                    BlobGetPropertiesHeaders headers = response.headers();
                    BlobInfo blobInfo = new BlobInfo().withName(blobName)
                            .withContentType(headers.contentType())
                            .withLength(headers.contentLength())
                            .withMD5(headers.contentMD5())
                            .withLastModified(headers.lastModified())
                            .withETag(headers.eTag());
                    BlobStorageResponse bsr = new BlobStorageResponse(Response.Status.OK, blobInfo);
                    callback.onSucceed(bsr);
                }, throwable -> {
                    Response.Status status = Response.Status.INTERNAL_SERVER_ERROR;
                    if (throwable instanceof StorageException) {
                        StorageException se = (StorageException) throwable;
                        if (se.statusCode() == Response.Status.NOT_FOUND.getStatusCode()) {
                            status = Response.Status.NOT_FOUND;
                        } else {
                            logger.error("Failed to INFO BLOB from Azure storage", throwable);
                        }
                    }
                    callback.onFailure(status, status.getReasonPhrase());
                }
        );
    }

    private boolean inDuration(long timestamp, Long min, Long max) {
        if (min == null && max == null) {
            return true;
        } else if (min == null) {
            return timestamp < max;
        } else if (max == null) {
            return timestamp >= min;
        } else {
            return timestamp >= min && timestamp < max;
        }
    }

    @Override
    public void listBlobs(String containerName, String prefix, String pagingMarker, Integer maxResults,
                          Long minLastModified, Long maxLastModified, Callback callback) {

        ListBlobsOptions options = new ListBlobsOptions()
                .withMaxResults((maxResults == null || maxResults <= 0 || maxResults > MAX_RECORDS_PER_PAGE) ? MAX_RECORDS_PER_PAGE : maxResults)
                .withPrefix(prefix);
        BlobStorageResponse bsr = new BlobStorageResponse(Response.Status.OK);
        BlobList blobList = bsr.getBlobList();
        ContainerURL containerURL = getContainer(containerName);
        containerURL.listBlobsFlatSegment(pagingMarker, options).subscribe(
                response -> {
                    int count = 0;
                    if (response.body().segment() != null) {
                        count = Utils.sizeof(response.body().segment().blobItems());
                    }

                    if (count > 0) {
                        for (BlobItem item : response.body().segment().blobItems()) {
                            BlobProperties props = item.properties();
                            long lastModified = props.lastModified().toInstant().toEpochMilli();
                            if (inDuration(lastModified, minLastModified, maxLastModified)) {
                                blobList.getBlobs().add(new BlobInfo()
                                        .withName(item.name())
                                        .withContentType(props.contentType())
                                        .withLength(props.contentLength())
                                        .withMD5(props.contentMD5())
                                        .withETag(props.etag())
                                        .withLastModified(lastModified));
                            }
                        }

                        if (response.body().nextMarker() != null) {
                            blobList.setNextMarker(response.body().nextMarker());
                        }
                    }

                    callback.onSucceed(bsr);

                }, throwable -> {
                    logger.error("Failed to LIST BLOB from Azure storage", throwable);
                    Response.Status status = Response.Status.INTERNAL_SERVER_ERROR;
                    callback.onFailure(status, status.getReasonPhrase());
                }
        );
    }
}
`

**Expected behavior**
There was no error.

**Setup (please complete the following information):**
 - Version of the Library used -compile group: 'com.microsoft.azure', name: 'azure-storage-blob', version: '11.0.1'

**Comment by rickle-msft** [comment]
@123Jun321 Thank you for reporting this issue. Unfortunately we are not doing any active investigations into v11 at this time, and our recommendation is to upgrade to v12 which is more stable and has a similar interface. Issues like this related to reliability are known to exist in v11, and we are not moving to resolve them at this time. I apologize for any inconvenience this may cause, and we will be happy to assist you in the upgrade effort if you need support.

**Comment by youtaya** [comment]
Is any suggestion of how to immigrate from SDK v11 to v12 smoothly? As we look over v12 and find  it so different from v11 , it's hard work for us to port from v11 to v12.

**Comment by rickle-msft** [comment]
There's not a way that will just make it work. It is an API break, so some code will have to be reworked in order to upgrade, but it should be mostly a difference in type/method names and how you construct clients. The programming patterns are otherwise the same as it is not a paradigm change as it was from v8 to v11. We recognize that this can be a painful and unwelcome experience for customers, and we are sensitive to their business needs. Hence, as I mentioned, we are happy to help how we can with this upgrade, but upgrading is necessary to mitigate problems like this timeout.

**Comment by rickle-msft** [comment]
I am going to close this issue for now as I don't believe there is anything more to discuss here, but please let me know if you need support on this work.
