### ISSUE TITLE
Investigate Form Recognizer Live test failures on Linux env 

### ISSUE THREAD

**Issue by samvaity** [Azure/azure-sdk-for-java#10526]
[Form Recognizer live tests](https://dev.azure.com/azure-sdk/internal/_build?definitionId=1684&_a=summary) recently started failing with `Temporary failure in name resolution` error only on Linux setup env.

Would it be caused by the recent update to update the Linux OS images to Ubuntu 18.04 for the tests pipeline done in this #10469 .

**Comment by samvaity** [comment]
cc: @mitchdenny @JimSuplizio @weshaggard

**Comment by danieljurek** [comment]
One difference between recently passing and recently failing runs appears to be that the ubuntu version changed. One would expect DNS resolution to work fairly consistently between versions of ubuntu. 

However, in a test example running ubuntu 16 today the Linux jobs succeed and note no DNS failures: https://dev.azure.com/azure-sdk/internal/_build/results?buildId=371880&view=logs&j=4d5db6ce-0b7f-527e-b115-2367ee6e1fef&t=57e6bea7-024e-5230-7282-6992d68e7015

Running against master (ubuntu 18) just now (in the hopes of this issue being transient) shows the same DNS failures: https://dev.azure.com/azure-sdk/internal/_build/results?buildId=371919&view=logs&j=4d5db6ce-0b7f-527e-b115-2367ee6e1fef&t=57e6bea7-024e-5230-7282-6992d68e7015

**Comment by samvaity** [comment]
Closed with #10576
