### ISSUE TITLE
connecting to azure storage blob thru HTTP proxy

### ISSUE THREAD

**Issue by sjyang18** [Azure/azure-sdk-for-java#10540]
**Query/Question**
We used to set proxy thru com.microsoft.azure.storage.OperationContext.setProxy in the legacy azure-storage SDK v8. What is the equivalent call in azure-storage-blob v12? I have a legacy code to migrate and the existing code supports connection thru HTTP proxy. I need an equivalent solution.

***Why is this not a Bug or a feature Request?***
I don't know the equivalent call to make. If this is missing and no way to do that, I will file a feedback.

**Setup (please complete the following information if applicable):**
 - OS: Ubuntu 18.04
 - IDE : Visual Studio code
 - Version of the Library used

`<dependency>
         <groupId>com.azure</groupId>
            <artifactId>azure-storage-blob</artifactId>
            <version>12.6.0</version>
 </dependency>
`

 **Information Checklist**
 Kindly make sure that you have added all the following information above and checkoff the required fields otherwise we will treat the issuer as an incomplete report
- [X] Query Added
- [X] Setup information Added

**Comment by rickle-msft** [comment]
HI, @sjyang18. Thank you for posting your question. In v12, you will set a proxy when you build your client. In particular, all client builders can accept an instance of an HttpClient. We recommend using the NettyAsyncHttpClient, the builder for which allows you to set a proxy on the client. Please let me know if you need further support here.

**Comment by sjyang18** [comment]
I am not clear about your suggestion. Can you give an example code that shows how I pass proxy info and create an BlobClient? You mentioned NettyAsyncHttpClient.  How do I pass Proxy info to V12 Blob API?

**Comment by rickle-msft** [comment]
Sure. You can see the way we setup the HttpClient [here](https://github.com/Azure/azure-sdk-for-java/blob/master/sdk/storage/azure-storage-blob/src/test/java/com/azure/storage/blob/APISpec.groovy#L414) and you can see the way we add that http client to a client builder [here](https://github.com/Azure/azure-sdk-for-java/blob/master/sdk/storage/azure-storage-blob/src/test/java/com/azure/storage/blob/APISpec.groovy#L303). If it's not clear how those pieces fit together, I can also write a condensed sample

**Comment by rickle-msft** [comment]
I am going to close this issue as it looks like the provided answer was sufficient. Please let us know if you need more support.
