### ISSUE TITLE
[BUG] SqlQuerySpec fails for Order By with Offset Query

### ISSUE THREAD

**Issue by jyotsnaravikumar** [Azure/azure-sdk-for-java#10578]
Describe the bug
SqlQuerySpec fails for Order By with Offset Query
To Reproduce
Steps to reproduce the behavior.

```
com.microsoft.azure
spring-data-cosmosdb
2.2.2

String queryText =
String.format(
"select m.id, m.partitionKey, m.actorId, m.type , m.name, m.birthYear, "
+ "m.deathYear, m.profession, m.textSearch, m.movies "
+ "from m where m.type = @type offset @offset limit @limit "
+ "order by m.textSearch, m.actorId ");
querySpec.queryText(queryText);

SqlParameterList parameterList = new SqlParameterList();
parameterList.add(new SqlParameter("@type", actorDocumentType));
parameterList.add(new SqlParameter("@offset", 0));
parameterList.add(new SqlParameter("@limit", 100));
querySpec.parameters(parameterList);
```

{
"timestamp": 1588049672505,
"path": "/api/actors",
"status": 500,
"error": "Internal Server Error",
"message": "Gateway Failed to Retrieve Query Plan: Message: {"errors":[{"severity":"Error","location":{"start":176,"end":181},"code":"SC1001","message":"Syntax error, incorrect syntax near 'order'."}]}\r\nActivityId: 885297e3-777d-4fdc-bacc-0b06c8ef2474, Microsoft.Azure.Documents.Common/2.10.0, Microsoft.Azure.Documents.Common/2.10.0, StatusCode: BadRequest",
"requestId": "4102b2ac"
}

Expected behavior
Order By should have been honored in parameterized query as in String query

Actual behavior
Provide a description of the actual behavior observed.

Environment summary
SDK Version: Provided above
Java JDK version: 8
OS Version (e.g. Windows, Linux, MacOSX) MacOS

Additional context
Individually as a Order By query or as a Offset query works. Combination of Offset and Order By fails.

**Comment by kushagraThapar** [comment]
@jyotsnaravikumar Thanks Jyotsna for creating this issue, we will look into this soon.

**Comment by kushagraThapar** [comment]
@jyotsnaravikumar - Since the error code here is 500, this error is coming from Gateway (backend) and has nothing to do with the SDK. I will get someone from backend team to look into this.

**Comment by kushagraThapar** [comment]
@jyotsnaravikumar - can you please provide complete stack trace of the error thrown by cosmos SDK. 500 status code seems to be thrown by your code, and not cosmos SDK.

**Comment by jyotsnaravikumar** [comment]
The interesting find over here is the "order" of "order by"

This query throws the same error from the portal as well :

```
select m.id, m.partitionKey, m.actorId, m.type , m.name, m.birthYear, 
m.deathYear, m.profession, m.textSearch, m.movies
from m where m.type = @type offset @offset limit @limit 
order by m.textSearch, m.actorId
```

Failed to query item for container movies: {"code":400,"body":{"code":"BadRequest","message":"Gateway Failed to Retrieve Query Plan: Message: {\"errors\":[{\"severity\":\"Error\",\"location\":{\"start\":170,\"end\":175},\"code\":\"SC1001\",\"message\":\"Syntax error, incorrect syntax near 'order'.\"}]}\r\nActivityId: bbb37e1f-6272-4d01-889a-b2a6873e5afb, Microsoft.Azure.Documents.Common/2.10.0, Microsoft.Azure.Documents.Common/2.10.0"},"headers":{"access-control-allow-credentials":"true","access-control-allow-origin":"https://cosmos.azure.com","content-type":"application/json","strict-transport-security":"max-age=31536000","x-ms-activity-id":"bbb37e1f-6272-4d01-889a-b2a6873e5afb","x-ms-gatewayversion":"version=2.10.0","x-ms-throttle-retry-count":0,"x-ms-throttle-retry-wait-time-ms":0},"activityId":"bbb37e1f-6272-4d01-889a-b2a6873e5afb"}


However if I put the order by before offset and limit results are returned  as:

```
select m.id, m.partitionKey, m.actorId, m.type , m.name, m.birthYear, 
m.deathYear, m.profession, m.textSearch, m.movies
from m where m.type = 'Actor' order by m.textSearch, m.actorId offset 0 limit 100 
```

This seems to be the back end behavior.
