### ISSUE TITLE
Add error property to deployment so that I can get the deployment error

### ISSUE THREAD

**Issue by vivin** [Azure/azure-sdk-for-java#10572]
**Is your feature request related to a problem? Please describe.**

I am able to get a list of deployments using the SDK. I can see that some of the deployments have a provisioning state of "Failed". I want to be able to retrieve the error for these deployments. In the API documentation [here](https://docs.microsoft.com/en-us/rest/api/resources/deployments/listbyresourcegroup#deploymentlistresult) I can see that `error` is part of `DeploymentPropertiesExtended`, and contains the deployment error. When I use the Azure portal, I can also click on "Error Details" next to the status on a failed deployment to get the errors.

Looking at the source for [`DeploymentPropertiesExtended.java`](https://github.com/Azure/azure-sdk-for-java/blob/master/sdk/resources/mgmt/src/main/java/com/azure/management/resources/DeploymentPropertiesExtended.java), I don't see an `error` property. Could this be added?

**Describe the solution you'd like**
It would be nice if `Deployment` had a method that returns the error on a failed deployment.

**Describe alternatives you've considered**
I could retrieve all the operations for the deployment and get the errors out of that, but that means making an additional call.

**Additional context**

**Information Checklist**
Kindly make sure that you have added all the following information above and checkoff the required fields otherwise we will treat the issuer as an incomplete report
- [ * ] Description Added
- [ * ] Expected solution specified

**Comment by joshfree** [comment]
@yungezz could you please assist @vivin with how to programmatically retrieve the extended error details during failed provisioning?

**Comment by yungezz** [comment]
hi @vivin could you pls share version of SDK you're using, I'm supposing you're using `azure-mgmt-resources` SDK based on description, pls share your SDK if it's not. Thanks.

**Comment by ChenTanyi** [comment]
@vivin Currently SDK uses the resources with api-version 2019-08-01, which has no `error` field in it. It will need to update the api-version to add such field.

**Comment by weidongxu-microsoft** [comment]
2.2.0 of the new Java SDK already have 2020-06 api-version.
https://aka.ms/azsdk/java/mgmt

Also added a PR to expose the `error()` method. https://github.com/Azure/azure-sdk-for-java/pull/19478

**Comment by weidongxu-microsoft** [comment]
1.39.1 also have 2020-06 api-version, with `error` method in inner object.
