### ISSUE TITLE
Azure Core failure in Smoke Tests

### ISSUE THREAD

**Issue by danieljurek** [Azure/azure-sdk-for-java#10588]
I'm seeing a failure in Smoke Tests that presents as: 

```
[reactor-http-nio-3] WARN reactor.netty.http.client.HttpClientConnect - [id: 0x96d9032b, L:/10.1.0.4:50267 - R:kv-smk-tce82228e48d34fd6.vault.azure.net/13.66.230.241:443] The connection observed an error 
com.azure.core.exception.UnexpectedLengthException: Request body emitted 82 bytes, more than the expected 41 bytes. 
 ```

Source build: https://dev.azure.com/azure-sdk/internal/_build/results?buildId=373818&view=logs&j=49400574-4c50-5d31-7174-432d6b5afe93&t=973946ac-769d-532f-9b59-c156eec84e9d&l=60

To get more context I tried rolling `azure-core` back to `1.5.0-beta.1.dev.20200422.1`. Smoke tests succeed when running all other packages at the latest available version and with that version of core.

**Comment by joshfree** [comment]
@alzimmermsft PTAL
