### ISSUE TITLE
Update vulnerable dependencies of azure-core-http-netty

### ISSUE THREAD

**Issue by yiliuTo** [Azure/azure-sdk-for-java#10595]
**Describe the bug**
While running `mvn org.owasp:dependency-check-maven:check`, several vulnerable dependencies in the `com.azure.azure-core-http-netty` can be found, they exist in several versions including the latex **1.5.0**. The vulnerable dependency report is shown below: 
![1](https://user-images.githubusercontent.com/63028776/80564742-3a023b00-8a21-11ea-9a2b-9f8b12250ddc.jpg)

And the vulnerabilities are:
![2](https://user-images.githubusercontent.com/63028776/80564783-6027db00-8a21-11ea-98f9-8c3db9654015.jpg)

**To Reproduce**
- include _azure-core-http-netty_ in your _pom.xml_.
- run mvn org.owasp:dependency-check-maven:check
- check results in console and a report in target/dependency-check-report.html

**Possible solution**
It seems the imported Netty version should be equal or higher than 4.1.46 to avoid the vulnerability. Update libraries if possible without breaking the current logic

**Screenshots**

**Setup (please complete the following information):**
 - OS: Windows
 - IDE: IntelliJ
 - Version of the Library used: azure-core-http-netty

**Comment by alzimmermsft** [comment]
This should be resolved when #10531 is merged in as it will be upgrading the Netty versions.

**Comment by yiliuTo** [comment]
OK, thank you.
