### ISSUE TITLE
[BUG]Cosmos client throwing 409 on upsert

### ISSUE THREAD

**Issue by merric-rocketpartners** [Azure/azure-sdk-for-java#10600]
**Describe the bug**
Attempting an upsert on 
compile "com.microsoft.azure:azure-documentdb:2.4+"
and I'm getting a 409 which goes against the upsert contract (meaning that if there is a conflict I clearly want to update that row).
***Exception or Stack Trace***
com.microsoft.azure.documentdb.DocumentClientException: Entity with the specified id already exists in the system.,
RequestStartTime: 2020-04-29T13:58:13.5298355Z, RequestEndTime: 2020-04-29T13:58:13.5298355Z,  Number of regions attempted:1
ResponseTime: 2020-04-29T13:58:13.5298355Z, StoreResult: StorePhysicalAddress: rntbd://dm5prdddc01-docdb-1.documents.azure.com:14128/apps/a8955ea6-38e2-4f3d-b7ae-bcbfaea92dce/services/730de375-bd04-42fc-a7f3-94eb34626553/partitions/4afd492a-3c42-4014-a020-0021600b6d24/replicas/132305339029504459p/, LSN: 2, GlobalCommittedLsn: 2, PartitionKeyRangeId: 0, IsValid: True, StatusCode: 409, SubStatusCode: 0, RequestCharge: 1.67, ItemLSN: -1, SessionToken: -1#2, UsingLocalLSN: False, TransportException: null, ResourceType: Document, OperationType: Upsert
, Microsoft.Azure.Documents.Common/2.10.0, StatusCode: Conflict
	at com.microsoft.azure.documentdb.internal.ErrorUtils.maybeThrowException(ErrorUtils.java:74)
	at com.microsoft.azure.documentdb.internal.GatewayProxy.performPostRequest(GatewayProxy.java:284)
	at com.microsoft.azure.documentdb.internal.GatewayProxy.doUpsert(GatewayProxy.java:88)
	at com.microsoft.azure.documentdb.internal.GatewayProxy.processMessage(GatewayProxy.java:354)
	at com.microsoft.azure.documentdb.DocumentClient$6.apply(DocumentClient.java:3054)
	at com.microsoft.azure.documentdb.internal.RetryUtility.executeDocumentClientRequest(RetryUtility.java:73)
	at com.microsoft.azure.documentdb.DocumentClient.doUpsert(DocumentClient.java:3068)
	at com.microsoft.azure.documentdb.DocumentClient.access$200(DocumentClient.java:87)
	at com.microsoft.azure.documentdb.DocumentClient$3.apply(DocumentClient.java:896)
	at com.microsoft.azure.documentdb.internal.RetryUtility.executeCreateDocument(RetryUtility.java:199)
	at com.microsoft.azure.documentdb.DocumentClient.upsertDocument(DocumentClient.java:901)

**To Reproduce**
create document as below with custom id. Send another request using that same id with same or different payload. 

***Code Snippet***
      ResourceResponse<Document> response = getDocumentClient().upsertDocument(cosmosCollectionUri, document, new RequestOptions(), true);

**Expected behavior**
When using upsert I expect a document upload using an existing id to update the given row. 

**Screenshots**

**Setup (please complete the following information):**
 - OS: OSX and Linux (Using AKS)
 - IDE : Intellij
 - Version of the Library used: 2.4+

**Additional context**
As above this is in AKS and the logs are from that system.
**Information Checklist**
Kindly make sure that you have added all the following information above and checkoff the required fields otherwise we will treat the issuer as an incomplete report
- [J ] Bug Description Added
- [ J] Repro Steps Added
- [ J] Setup information Added

**Comment by merric-rocketpartners** [comment]
More info. 

We found that the container was actually restricting on partition key. I'll say that again, I was only allowed to have one document per partition key! I stripped everything else out and used every possible "id" value, but nothing would allow a save until I changed the partition key (or removed it and i was allowed a SINGLE record with an empty partition key). 

SOOOOOOOO, that's pretty awful. 

We ended up having to delete the PROD container and rebuild it as a last resort test. AND LOW AND BEHOLD! With the same configuration the container started working and I was able to place records and use upsert again.

**Comment by milismsft** [comment]
@merric-rocketpartners First sorry for the delay in the response... I see that you were able to solve the initial issue but I would like to follow up to better understand what was the cause of it. 
In normal scenarios you should be allowed to have multiple documents, that is unless your partition key might be set to "/id", which might explain the behavior you experienced.
Could you let us investigate this further by providing us with the following:
 - the configuration of your account policy, Cosmos client mode and policy
 - the container settings, especially the partition key settings
 - an example of the document that was used during the upsert op (Json string will do).
