### ISSUE TITLE
[BUG] "Contains" returns empty response from SqlQuerySpec

### ISSUE THREAD

**Issue by jyotsnaravikumar** [Azure/azure-sdk-for-java#10607]
**Describe the bug**

This query works from Azure Portal and returns results:
```
select m.id, m.partitionKey, m.actorId, m.type , m.name, m.birthYear,
                m.deathYear, m.profession, m.textSearch, m.movies
                from m where m.type = 'Actor'
                and contains(m.textSearch, 'tom') 
                order by m.textSearch, m.actorId 
                offset 0 limit 100

```

However the same returns empty response from SqlQuerySpec 
```
logger.info("before passing sqsActorQuerySpec " + sqlQuerySpec);

    SqlQuerySpec querySpec = new SqlQuerySpec();
    String queryText =
        String.format(
            "select m.id, m.partitionKey, m.actorId, m.type , m.name, m.birthYear, "
                + "m.deathYear, m.profession, m.textSearch, m.movies "
                + "from m where m.type = @type "
                + "and contains(m.textSearch, @query) "
                + "order by m.textSearch, m.actorId "
                + "offset @offset limit @limit ");
    querySpec.queryText(queryText);

    SqlParameterList parameterList = new SqlParameterList();
    parameterList.add(new SqlParameter("@type", actorDocumentType));
    parameterList.add(new SqlParameter("@query", query));
    parameterList.add(new SqlParameter("@offset", pageNumber));
    parameterList.add(new SqlParameter("@limit", pageSize));
    querySpec.parameters(parameterList);

    logger.info("before passing querySpec " + querySpec);
```

**Expected behavior**
"Contains" should have been honored in parameterized query as it does in case of String queries

**Setup (please complete the following information):**
 - OS: [e.g. iOS] MacOS
 - IDE : [e.g. IntelliJ]IntelliJ
 - Version of the Library used 
 ```
<dependency>
            <groupId>com.microsoft.azure</groupId>
            <artifactId>spring-data-cosmosdb</artifactId>
            <version>2.2.2</version>
 </dependency>

```

**Information Checklist**
Kindly make sure that you have added all the following information above and checkoff the required fields otherwise we will treat the issuer as an incomplete report
- [X] Bug Description Added
- [X] Repro Steps Added
- [X]Setup information Added

**Comment by anfeldma-ms** [comment]
Hi @jyotsnaravikumar , can you please try this suggestion - set up a test where you do not use ``querySpec`` at all (or temporarily comment out the ``querySpec`` code above) and try executing your query directly in the Java SDK by providing the query string as an argument to ``queryItems()`` as shown below:

```
    String queryText =
        String.format(
            "select m.id, m.partitionKey, m.actorId, m.type , m.name, m.birthYear, "
                + "m.deathYear, m.profession, m.textSearch, m.movies "
                + "from m where m.type = 'Actor' "
                + "and contains(m.textSearch, 'tom') "
                + "order by m.textSearch, m.actorId "
                + "offset 0 limit 100 ");

      Iterator<FeedResponse<CosmosItemProperties>> feedResponseIterator = 
                container.queryItems(query, queryOptions);

      //...the rest of your code...
```

can you please report back if your issue persists where you try this? Thanks.

**Comment by jyotsnaravikumar** [comment]
@anfeldma-ms : The String Query works, we have that solution working. We wanted to use SqlQuerySpec for protecting against SQL Injection.

**Comment by anfeldma-ms** [comment]
@jyotsnaravikumar Would it be possible to share some information about your data model? For example, if you could respond with the text of one of the JSON documents in your container (please filter out any sensitive info or PII). Would that be possible? Thanks.

**Comment by jyotsnaravikumar** [comment]
@anfeldma-ms  : Here is our ddadtamodel - https://github.com/retaildevcrews/imdb

**Comment by jyotsnaravikumar** [comment]
This issue is fixed.
