### ISSUE TITLE
[QUERY] when creating a vm, how often does polling occur? 

### ISSUE THREAD

**Issue by erzads** [Azure/azure-sdk-for-java#10601]
**Query/Question**
I am using com.azure.management.Azure to create virtual machines. 
I understand that the sdk keeps polling azure to know when the creation ended. 
I am need to know how often this polling occurs and increase it. 

**Setup (please complete the following information if applicable):**
 - OS: [windows]
 - IDE : [ IntelliJ]
 - Version of the Library used 1.31.1
 
 **Information Checklist**
 Kindly make sure that you have added all the following information above and checkoff the required fields otherwise we will treat the issuer as an incomplete report
- [x ] Query Added
- [ x] Setup information Added

**Comment by joshfree** [comment]
@yungezz could you please assist @erzads with the Compute MGMT plane polling interval?

**Comment by yungezz** [comment]
hi @xccc-msft could you pls have a look? thanks

**Comment by xccc-msft** [comment]
@erzads Regarding the polling, it's decided by the value of header `Retry-After` returned in the response. 
For example, it's `Retry-After: 15` in the response then SDK client will send next request after 15 second to check status of the operation requested.

**Comment by erzads** [comment]
Can this be changed? I wish to increase it.

**Comment by xccc-msft** [comment]
@erzads You might want to customize an interceptor to change the value manually from your end. Here is [example of interceptor](https://github.com/Azure/azure-libraries-for-java/blob/master/azure-mgmt-resources/src/main/java/com/microsoft/azure/management/resources/fluentcore/utils/ProviderRegistrationInterceptor.java) you can follow. After creation, you need to add it inside the RestClient.

**Comment by erzads** [comment]
How would I add an interceptor to the rest client used by Azure? This looks very cumbersome. Could be a simple parameter.

**Comment by xccc-msft** [comment]
@erzads It's more like hacking to increase the Retry-After value. So you have to insert an interceptor to complete the hacking. 
Sample code if you don't want to configure the whole rest client:
```java
ResourceManager resourceManager = ResourceManager.configure()
                .withInterceptor(interceptor)
                .withLogLevel(LogLevel.NONE)
                .authenticate(credentials);
```

**Comment by weidongxu-microsoft** [comment]
@erzads 
Sample code to have fine-control over polling with new SDK. https://github.com/Azure/azure-sdk-for-java/blob/master/sdk/resourcemanager/docs/DESIGN_PREVIEW.md#fine-control-over-long-running-operation

SDK https://aka.ms/azsdk/java/mgmt

**Comment by weidongxu-microsoft** [comment]
Short survey for us to hear you:
https://microsoft.qualtrics.com/jfe/form/SV_ehN0lIk2FKEBkwd?Q_CHL=ISSUES
