### ISSUE TITLE
Incorrect Use of Body Annotation

### ISSUE THREAD

**Issue by alzimmermsft** [Azure/azure-sdk-for-java#10613]
The interface layer for KeyVault is using the `BodyParam` annotation incorrectly. It is setting the annotation value to `"body"`, the expected use of this value is to set the `Content-Type` of the body. This should be updated to use `application/json` as the annotation value to match that KeyVault is using JSON.

Luckily this is getting self corrected since the APIs are also passing a `Content-Type` through the `HeaderParam` annotation which is applied after the body `Content-Type`, but this should still be resolved.

**Comment by g2vinay** [comment]
Adding @vcolin7 to take a look.

**Comment by vcolin7** [comment]
Created a PR to address this: #10648.

**Comment by alzimmermsft** [comment]
Fixed by #10648
