### ISSUE TITLE
Move deep copy of buffer in buffered upload to be its own step in the pipeline. 

### ISSUE THREAD

**Issue by gapra-msft** [Azure/azure-sdk-for-java#10639]

**Comment by gapra-msft** [comment]
In the 73 branch, we currently do this in PayloadSizeGate

**Comment by rickle-msft** [comment]
We also need to re-add the copy in the UploadBufferPool for the same safety guarantees.

**Comment by rickle-msft** [comment]
This has been addressed by #18598.
