### ISSUE TITLE
[FEATURE REQ] Add support for uncaught exceptions handler

### ISSUE THREAD

**Issue by asm0dey** [Azure/azure-sdk-for-java#10635]
**Is your feature request related to a problem? Please describe.**
Currently we're facing following problem: User creates connection to Azure with incorrect credentials. Every time we're trying to list content of blob storage container we encounter exception which have no way to handle

**Describe the solution you'd like**
I would like to have ability to set uncaught exception handler 

**Describe alternatives you've considered**
I don't see alternatives

**Information Checklist**
Kindly make sure that you have added all the following information above and checkoff the required fields otherwise we will treat the issuer as an incomplete report
- [X] Description Added
- [X] Expected solution specified

**Comment by joshfree** [comment]
@asm0dey thank you for posting the question.  @anuchandy could you please assist with guidance (and updated Java repo wiki entry) on configuring UncaughtExceptionHandler?

**Comment by anuchandy** [comment]
@asm0dey are you using async reactor-based APIs? Is the issue that exceptions are bypassing the 
reactor `onError` or other error operators?

**Comment by asm0dey** [comment]
@anuchandy I'm using blocking client and in my environment somehow exceptions aren't being caught by Uncaught exception handler. 
My environment is pretty complex - it's plugin for JetBrains Idea with separate Classloader and I absolutely believe it can be impact of environment
