### ISSUE TITLE
 FieldBuilder phase 2 improvement

### ISSUE THREAD

**Issue by sima-zhu** [Azure/azure-sdk-for-java#10647]
1. Give field builder unsupported type a default value instead of throw error.
https://github.com/Azure/azure-sdk-for-java/pull/10500#discussion_r416946182

1. Use collection base class. + Fix the array type.
https://github.com/Azure/azure-sdk-for-java/pull/10500#discussion_r418753877

1. Name property override.
https://github.com/Azure/azure-sdk-for-java/pull/10500#discussion_r418773038

1. Fixed the problem of not taking inner class.

**Comment by conniey** [comment]
Is a whitelist easier to maintain than a blacklist?

**Comment by heaths** [comment]
Regarding the name override, instead to align with mapping actual fields from a document payload (from a query) to index names, we should instead support our respective frameworks' attributes that would already be used. For example, in .NET we use (in track 2) `JsonPropertyName` from the built-in System.Text.Json. That way, we're not duplicating (or forcing devs to duplicate, rather) property<-> field renames. Since, IIRC, you're using Jackson maybe it's a `BeanProperty` given a different name that you use.

**Comment by sima-zhu** [comment]
> Give field builder unsupported type a default value
> #10500 (comment)

@conniey Regarding this question, FieldBuilder will convert property without annotation to complex field. This is recursive call.
If customer use the following code:
```
private char something;
```
Our logic will fall into parsing all properties in char.class. Whitelist is not enough as we do not know if this is a real complex type or the type we do not parse.

**Solutions:**
1.   Map all blacklist to search `DataType`.
@heaths what's your proposal on this?

**Comment by sima-zhu** [comment]
> Regarding the name override, instead to align with mapping actual fields from a document payload (from a query) to index names, we should instead support our respective frameworks' attributes that would already be used. For example, in .NET we use (in track 2) `JsonPropertyName` from the built-in System.Text.Json. That way, we're not duplicating (or forcing devs to duplicate, rather) property<-> field renames. Since, IIRC, you're using Jackson maybe it's a `BeanProperty` given a different name that you use.

This might introduce complexity in near future.  Java is working on adding plugin layer for json library. Customer will have the choice of which library to use. 
In this case, we can either only allow Jackson library user to override the name. Or use some other complex helper to get the overridden property name.

**Comment by heaths** [comment]
Maybe it's a progression, then: we support name overrides in our attributes, then check common ones, then fall back to the name as-is. It's important to remember that Search is case-sensitive. Probably not an issue for Java or JavaScript if people use Java/Script-like field names (examples show this, so probably most common), but an issue for .NET (CamelCase) and Python (snake_case).

As for the `DataType` question, I'm not sure what you mean.

**Comment by sima-zhu** [comment]
Fixed bugs for preview 4.
https://github.com/Azure/azure-sdk-for-java/pull/11532

**Comment by sima-zhu** [comment]
Move to preview 5 for additions.

**Comment by sima-zhu** [comment]
Will continue working on @JsonProperty (or Gson annotation) to rename the field name

**Comment by sima-zhu** [comment]
Closed by PR: https://github.com/Azure/azure-sdk-for-java/pull/13496
