### ISSUE TITLE
[BUG] com.microsoft.azure.management.resources.fluentcore.arm.ResourceUtils.defaultApiVersion() selects wrong API version for some resource types

### ISSUE THREAD

**Issue by wzur-r3** [Azure/azure-sdk-for-java#10681]
**Describe the bug**
`defaultApiVersion()` can selects wrong API version for child resources, specifically for an image in a shared gallery.

For example with id: `/subscriptions/[SUBSCRIPTION_ID]/resourceGroups/[RESOURCE_GROUP_NAME]/providers/Microsoft.Compute/galleries/[GALLERY_NAME]/images` it picks up "2020-06-01" version from `images` type.

The actual API version for the `galleries/images` is "2019-12-01"

This is even worse for `galleries/images/versions`, because it returns API version for `sharedVMImages/versions`.

This is because `defaultApiVersion() never looks for the full resource type, which is provided by `ResourceId.fullResourceType()`.

This issue can be masked when there is the same API version for `images` and `galleries/images`, but of this weekend that is not the case for now.

***Code Snippet***

```java
String id = "/subscriptions/[SUBSCRIPTION_ID]/resourceGroups/[RESOURCE_GROUP_NAME]/providers/Microsoft.Compute/galleries/[GALLERY_NAME]/images";
String apiVersion = ResourceUtils.defaultApiVersion(id, provider);
```

apiVersion returns "2020-06-01", which is for resource type `images` in `Microsoft.Compute` namespace and it should return "2019-12-01", which is for resource type `galleries/images` in the same namespace.

**Expected behavior**

Function should search for the full resource type.

**Setup (please complete the following information):**
 - OS: N/A
 - IDE : N/A
 - Version of the Library used: 1.31.0

**Additional context**
I found that tracking managed image validation problems in Jenkins' Azure VM plugin.

**Comment by yungezz** [comment]
hi @weidongxu-microsoft could you pls have  a look? thanks

**Comment by weidongxu-microsoft** [comment]
@xccc-msft Any idea?

**Comment by xccc-msft** [comment]
@wzur-r3 In the response, it will return a list of [API versions](https://github.com/Azure/azure-rest-api-specs/blob/master/specification/resources/resource-manager/Microsoft.Resources/stable/2019-10-01/resources.json#L4543-L4547) by array. In `ResourceUtils`, the `defautApiVersion()` will pick [the first one](https://github.com/Azure/azure-libraries-for-java/blob/master/azure-mgmt-resources/src/main/java/com/microsoft/azure/management/resources/fluentcore/arm/ResourceUtils.java#L154-L176) in the returned array.
You are getting `2020-06-01` as the service team updated this array for the related resource type. So I'm not sure what you mean by `the actual API version should be '2019-12-01'`.

**Comment by wzur-r3** [comment]
@xccc-msft `defaultApiVersion` *wrongly* assumes the resource type is of a simple type (for example `images` or `versions`) when in fact it could be `galleries/images` or `galleries/images/versions` or something else.

The result of this is it could select *wrong* type in a provider when it looks for API version, for example it will use `images` instead of `galleries/images` and as it happens these two have different API versions now.

**Comment by xccc-msft** [comment]
@wzur-r3 Thanks for clarifying this. I have created a [PR](https://github.com/Azure/azure-libraries-for-java/pull/1179) to fix this. Please feel free to review and share your comments.
