### ISSUE TITLE
[QUERY] [Blob Storage] Turn off verbose logging from reactor and netty

### ISSUE THREAD

**Issue by SukruthKS** [Azure/azure-sdk-for-java#10684]
**Query/Question**
I'm using Azure Blob Storage SDK (v12.6.0) which has a dependency on Reactor and Netty frameworks. These dependencies generate a ton of logging at runtime, could be because our system uses SLF4J set at `DEBUG` trace level. Is there a way to turn off logging for these dependencies?

***Why is this not a Bug or a feature Request?***
Trying to understand if there is already a way to do this

**Setup (please complete the following information if applicable):**
 - OS: Linux
 - IDE : NA
 - Version of the Library used: 12.6.0
 
 **Information Checklist**
 Kindly make sure that you have added all the following information above and checkoff the required fields otherwise we will treat the issuer as an incomplete report
- [x] Query Added
- [x] Setup information Added

**Comment by alzimmermsft** [comment]
Hi @SukruthKS, do you have any logs you could show to better tell if the superfluous logging is coming from Reactor, Reactor Netty, or Netty?

For a few quick things to check around logging:

- Do any of the Reactor operation chains use the `log` operator?
- Is the `HttpClient` setting `wiretap` to `true`?

Depending on the underlying SLF4J implementation, could the log level for Reactor, Reactor Netty, and Netty be restricted to more important log levels such as `WARNING` or `ERROR`?

**Comment by SukruthKS** [comment]
Hi @alzimmermsft , here are some logs:
```
19:44:00.389 [reactor-http-epoll-1] DEBUG r.n.r.PooledConnectionProvider - [id: 0xb64fd7ea] Created a new pooled channel, now 1 active connections and 0 inactive connections
19:44:00.412 [reactor-http-epoll-1] DEBUG i.n.util.ResourceLeakDetectorFactory - Loaded default ResourceLeakDetector: io.netty.util.ResourceLeakDetector@1f862c63
19:44:00.418 [reactor-http-epoll-1] DEBUG reactor.netty.tcp.SslProvider - [id: 0xb64fd7ea] SSL enabled using engine OpenSslEngine and SNI sfcdev1.blob.core.windows.net:443
19:44:00.429 [reactor-http-epoll-1] DEBUG r.netty.channel.BootstrapHandlers - [id: 0xb64fd7ea] Initialized pipeline DefaultChannelPipeline{(reactor.left.sslHandler = io.netty.handler.ssl.SslHandler), (reactor.left.sslReader = reactor.netty.tcp.SslProvider$SslReadHandler), (BootstrapHandlers$BootstrapInitializerHandler#0 = reactor.netty.channel.BootstrapHandlers$BootstrapInitializerHandler), (reactor.left.httpCodec = io.netty.handler.codec.http.HttpClientCodec), (reactor.right.reactiveBridge = reactor.netty.channel.ChannelOperationsHandler)}
19:44:00.493 [reactor-http-epoll-1] DEBUG r.n.r.PooledConnectionProvider - [id: 0xb64fd7ea, L:/10.211.55.16:54308 - R:<redacted>.blob.core.windows.net/<redacted_ip>:443] Registering pool release on close event for channel
19:44:00.493 [reactor-http-epoll-1] DEBUG r.n.r.PooledConnectionProvider - [id: 0xb64fd7ea, L:/10.211.55.16:54308 - R:<redacted>.blob.core.windows.net/<redacted_ip>:443] Channel connected, now 1 active connections and 0 inactive connections
19:44:00.645 [reactor-http-epoll-1] DEBUG io.netty.handler.ssl.SslHandler - [id: 0xb64fd7ea, L:/10.211.55.16:54308 - R:<redacted>.blob.core.windows.net/<redacted_ip>:443] HANDSHAKEN: TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384
```

I also see logs like this, but probably just during start up:

```
19:43:59.600 [main] DEBUG i.n.util.internal.PlatformDependent0 - java.nio.DirectByteBuffer.<init>(long, int): unavailable
19:43:59.600 [main] DEBUG i.n.util.internal.PlatformDependent - sun.misc.Unsafe: available
19:43:59.600 [main] DEBUG i.n.util.internal.PlatformDependent - maxDirectMemory: 5219811328 bytes (maybe)
19:43:59.601 [main] DEBUG i.n.util.internal.PlatformDependent - -Dio.netty.tmpdir: /tmp (java.io.tmpdir)
19:43:59.601 [main] DEBUG i.n.util.internal.PlatformDependent - -Dio.netty.bitMode: 64 (sun.arch.data.model)
19:43:59.601 [main] DEBUG i.n.util.internal.PlatformDependent - -Dio.netty.maxDirectMemory: -1 bytes
19:43:59.601 [main] DEBUG i.n.util.internal.PlatformDependent - -Dio.netty.uninitializedArrayAllocationThreshold: -1
...
...
19:44:00.285 [parallel-1] DEBUG io.netty.util.Recycler - -Dio.netty.recycler.linkCapacity: 16
19:44:00.285 [parallel-1] DEBUG io.netty.util.Recycler - -Dio.netty.recycler.ratio: 8
19:44:00.307 [parallel-1] DEBUG i.n.handler.ssl.CipherSuiteConverter - Cipher suite mapping: TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256 => ECDHE-ECDSA-AES128-GCM-SHA256
19:44:00.307 [parallel-1] DEBUG i.n.handler.ssl.CipherSuiteConverter - Cipher suite mapping: SSL_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256 => ECDHE-ECDSA-AES128-GCM-SHA256
19:44:00.307 [parallel-1] DEBUG i.n.handler.ssl.CipherSuiteConverter - Cipher suite mapping: TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256 => ECDHE-RSA-AES128-GCM-SHA256
19:44:00.307 [parallel-1] DEBUG i.n.handler.ssl.CipherSuiteConverter - Cipher suite mapping: SSL_ECDHE_RSA_WITH_AES_128_GCM_SHA256 => ECDHE-RSA-AES128-GCM-SHA256

```

> Do any of the Reactor operation chains use the log operator?

We are only using the sync version of the storage SDK so no direct use of Reactor.

> Is the HttpClient setting wiretap to true?

We are using the default pipeline provided by the SDK and don't make any changes to the HttpClient. If that setting can change depending on the env and other runtime configuration, I can hunt that down.

> Depending on the underlying SLF4J implementation, could the log level for Reactor, Reactor Netty, and Netty be restricted to more important log levels such as WARNING or ERROR?

That's a good suggestion and I will explore that. It'd be preferable to have a programmatic way to control logging like with the storage SDK.

**Comment by alzimmermsft** [comment]
Did some research on Netty and Reactor Netty logging, it appears the logs are happening due to `DEBUG` being set as the log level. As an example this is where some of the startup logs are happening, https://github.com/netty/netty/blob/4.1/common/src/main/java/io/netty/util/Recycler.java#L97.

I believe the best path forward would be updating the logging configuration to restrict the Netty and Reactor Netty logging levels. Updating the configuration for `io.netty` and `reactor.netty` loggers to a different log level, or turning them off, should be sufficient to prevent these logs from happening.

**Comment by SukruthKS** [comment]
Thanks for looking into it @alzimmermsft! I will make changes to the logging config.
