### ISSUE TITLE
[QUERY] increasing memory usage - am I doing something wrong? 

### ISSUE THREAD

**Issue by erzads** [Azure/azure-sdk-for-java#10693]
**Query/Question**
What is the correct way to use the sdk? 
Currently, I instantiate com.microsoft.azure.management.Azure once and keep using it. 
Should I instantiate it every time I need to make a request do azure? 

I am experiencing a very weird issue. My app gets increasing its memory usage as the system gets used. I have no cache. All I do is go to azure, fetch, create, shutdown and alter vms. 

Edit* I am pro filling the application and it seems that there is a big memory usage in deserializing the response from resource skus api. 

**Setup (please complete the following information if applicable):**
 - OS: [windows]
 - IDE : [ IntelliJ]
 - Version of the Library used 1.33.0
 
 **Information Checklist**
 Kindly make sure that you have added all the following information above and checkoff the required fields otherwise we will treat the issuer as an incomplete report
- [x ] Query Added
- [x ] Setup information Added
![IMG_20200504_173608366](https://user-images.githubusercontent.com/699344/81011140-d23b5e00-8e2d-11ea-945e-27925c0a890e.jpg)

**Comment by joshfree** [comment]
@yungezz could you please follow up?

**Comment by yungezz** [comment]
hi @weidongxu-microsoft could you pls have a look? thanks

**Comment by weidongxu-microsoft** [comment]
@erzads 

Yes, creating one Azure object and keep reusing it is the usual approach.

For memory, usually String takes large part of memory for common app, and JVM itself may have great influence as well (GC, etc.).

If you do expect certain limit on memory usage, would you try to set max heap memory (-Xmx) and see if `OutOfMemoryError` happens.

**Comment by erzads** [comment]
My application was fine with 2gb ram (usually never went past 1gb). After using the skus api, it increased to more then 10gb. I am not sure why, but something with the resource skus api might make it keep references that can't be GCed.

**Comment by weidongxu-microsoft** [comment]
10GB appears much too large.

My test:

```
            long mem = Runtime.getRuntime().totalMemory() - Runtime.getRuntime().freeMemory();
            System.out.println("memory: " + mem);

            PagedList<ComputeSku> skus = azure.computeSkus().list();

            System.out.println("size: " + skus.size());

            skus = null;

            for (int i = 0; i < Integer.MAX_VALUE; ++i) {
                mem = Runtime.getRuntime().totalMemory() - Runtime.getRuntime().freeMemory();
                System.out.println("memory: " + mem);
                Thread.sleep(10000);
                System.gc();
            }
```

Output:

```
memory: 37404400
[pool-1-thread-1] INFO com.microsoft.aad.adal4j.AuthenticationAuthority - [Correlation ID: 42746dfd-83f2-477f-a029-2b194efbf5f8] Instance discovery was successful
[com.microsoft.azure.azuresdktest.Main.main()] INFO com.microsoft.azure.management.compute.ResourceSkus list - --> GET https://management.azure.com/subscriptions/ec0aa5f7-9e78-40c9-85cd-535c6305b380/providers/Microsoft.Compute/skus?api-version=2017-09-01
[com.microsoft.azure.azuresdktest.Main.main()] INFO com.microsoft.azure.management.compute.ResourceSkus list - <-- 200  https://management.azure.com/subscriptions/ec0aa5f7-9e78-40c9-85cd-535c6305b380/providers/Microsoft.Compute/skus?api-version=2017-09-01 (1135 ms, unknown-length body)
size: 9782
memory: 90319968
memory: 43813920
memory: 43768192
memory: 43768080
memory: 43768080
memory: 43768080
memory: 43767584
```

From what I saw, it peaked at 90319968 for 9782 items, then go back to 43767584 after GC, which is not much different from 37404400 before the task.
