### ISSUE TITLE
[QUERY] how can I fetch a vm vpcus and memory values? 

### ISSUE THREAD

**Issue by erzads** [Azure/azure-sdk-for-java#10697]
**Query/Question**
I need to fetch all vms with their vcpu and memory values. I couldn't find these values in the VirtualMachine so I have to query the skus to get these values which is annoying and consumes resources and time. 
I know I can get the size info in the VirtualMachine object, but just in the format of "Standard_D8s_v3". 

**Setup (please complete the following information if applicable):**
 - OS: [windows]
 - IDE : [ IntelliJ]
 - Version of the Library used 1.33.0
 
 **Information Checklist**
 Kindly make sure that you have added all the following information above and checkoff the required fields otherwise we will treat the issuer as an incomplete report
- [x ] Query Added
- [x ] Setup information Added

**Comment by joshfree** [comment]
@yungezz could you please follow up?

**Comment by yungezz** [comment]
hi @xccc-msft could you pls  have a look? thanks.

**Comment by xccc-msft** [comment]
@erzads Are you looking for [vm.size()](https://github.com/Azure/azure-libraries-for-java/blob/master/azure-mgmt-compute/src/main/java/com/microsoft/azure/management/compute/VirtualMachine.java#L321), which is in format of [Standard_D8s_v3](https://github.com/Azure/azure-libraries-for-java/blob/master/azure-mgmt-compute/src/main/java/com/microsoft/azure/management/compute/VirtualMachineSizeTypes.java#L173) as you mentioned.

**Comment by erzads** [comment]
I am looking for vcpu count and ram memory. I found my answer.
Azure.virtualMachines().sizes() has it all.
