### ISSUE TITLE
[BUG] Unable to Set the Eviction Policy of VMScaleSet without setting the Priority to LOW

### ISSUE THREAD

**Issue by sandeepkv93** [Azure/azure-sdk-for-java#10706]
**Describe the bug**
In Azure-sdk-for-Java, during creation Spot VirtualMachine ScaleSet, there is semantic bug where if the customer wants to set the EvictionPolicy to DELETE/DEALLOCATE for SPOT Priority VMScaleSets, first the Priority needs to be set as LOW, then set the Eviction Policy and then again change the Priority to SPOT.

***Exception or Stack Trace***
Add the exception log and stack trace if available

**To Reproduce**

***Code Snippet***
```java
scaleSet
.withLowPriorityVirtualMachine(VirtualMachineEvictionPolicyTypes.DELETE)
.withVirtualMachinePriority(VirtualMachinePriorityTypes.SPOT)
```

**Expected behavior**
The expected snippet should be like this 
```java
scaleset
.withVirtualMachinePriority(VirtualMachinePriorityTypes.SPOT)
.withVirtualMachineEvictionPolicy(VirtualMachineEvictionPolicyTypes.DELETE)
```

**Screenshots**

**Setup (please complete the following information):**
 - IDE : IntelliJ
 - azure-sdk-for-java version 1.33.0

**Additional context**
The issue is due to the following definitions.
https://github.com/Azure/azure-sdk-for-java/blob/252366a5ad9432c7dfb29c89547b0d24d18c3e2d/sdk/compute/mgmt/src/main/java/com/azure/management/compute/VirtualMachineScaleSet.java#L1514-L1537

https://github.com/Azure/azure-sdk-for-java/blob/252366a5ad9432c7dfb29c89547b0d24d18c3e2d/sdk/compute/mgmt/src/main/java/com/azure/management/compute/implementation/VirtualMachineScaleSetImpl.java#L2369-L2380

**Information Checklist**
Kindly make sure that you have added all the following information above and checkoff the required fields otherwise we will treat the issuer as an incomplete report
- [x] Bug Description Added
- [x] Repro Steps Added
- [ ] Setup information Added

**Comment by yungezz** [comment]
Per email, we'll work on this on Track1 SDK.

**Comment by xccc-msft** [comment]
@sandeepkv93 I just create a [PR](https://github.com/Azure/azure-libraries-for-java/pull/1177) to support your request. Please feel free to review and share your comments.
As expected, you can use either
```java
scaleset
.withVirtualMachinePriority(VirtualMachinePriorityTypes.SPOT)
.withVirtualMachineEvictionPolicy(VirtualMachineEvictionPolicyTypes.DELETE)
```
or
```java
scaleset
.withSpotPriorityVirtualMachine(VirtualMachineEvictionPolicyTypes.DELETE)
```

**Comment by weidongxu-microsoft** [comment]
From FAQ of https://azure.microsoft.com/en-us/pricing/spot/

> The preview of Azure low-priority VMs on scale sets has been discontinued and has been retired as of February 3, 2020. Spot VMs have replaced Azure low-priority VMs and will include new capabilities, such as variable pricing. Spot pricing is also available on both single VMs and VMSS.

Maybe we should deprecate `withLowPriorityVirtualMachine` and replace it with `withSpotVirtualMachine`, and continue the flow with `withVirtualMachineEvictionPolicy`.

So this might not be a good idea, since REGULAR follow by DELETE probably is not valid.
```
scaleset
.withVirtualMachinePriority(VirtualMachinePriorityTypes.SPOT)
.withVirtualMachineEvictionPolicy(VirtualMachineEvictionPolicyTypes.DELETE)
```

**Comment by xccc-msft** [comment]
Thanks @weidongxu-microsoft for sharing this.

I just checked [swagger changes](https://github.com/Azure/azure-rest-api-specs/pull/7748/files) and find the updated descriptions as below
> Specifies the priority for a standalone virtual machine or the virtual machines in the scale set. <br><br> 'Low' enum will be deprecated in the future, please use 'Spot' as the enum to deploy Azure Spot VM/VMSS.

It was updated on Nov 2019. Not sure if we need to remove `LOW` from `VirtualMachinePriorityTypes` as it has been retired as of Feb 3, 2020. Otherwise we just add deprecate annotation on each `LOW priority` related place.

**Comment by weidongxu-microsoft** [comment]
If we can still create LOW priority VM then it might not be totally disabled, so Deprecate might be valid here. If we cannot even create it then we could delete it at all.

**Comment by xccc-msft** [comment]
After running the test, low-priority VM still can be created. So it would be better to add `Deprecate` for now. I have updated both vm and vmss.

**Comment by sandeepkv93** [comment]
@xccc-msft LGTM. Approved the PR.
