### ISSUE TITLE
Key Vault live tests do not readily support other clouds

### ISSUE THREAD

**Issue by danieljurek** [Azure/azure-sdk-for-java#10707]
As written today the KV live tests have hardcoded values like [KEY_VAULT_SCOPE](https://github.com/Azure/azure-sdk-for-java/blob/master/sdk/keyvault/azure-security-keyvault-secrets/src/main/java/com/azure/security/keyvault/secrets/SecretAsyncClient.java#L62) which can cause breaks in live tests using a different value for the scope. 

Example error:

```
Max retries 3 times exceeded. Error Details: AADSTS500011: The resource principal named https://vault.azure.net was not found in the tenant named ****. This can happen if the application has not been installed by the administrator of the tenant or consented to by any user in the tenant. You might have sent your authentication request to the wrong tenant.
```

([source](https://dev.azure.com/azure-sdk/internal/_build/results?buildId=374372&view=ms.vss-test-web.build-test-results-tab&runId=10588582&resultId=100076&paneView=debug))

**Comment by jongio** [comment]
This will also block Stack as the SCOPE will be different.
