### ISSUE TITLE
TokenResolver Documentation in Cosmos DB SDK

### ISSUE THREAD

**Issue by prasadanair** [Azure/azure-sdk-for-java#10732]
Library in use : com.microsoft.azure:azure-cosmos:3.7.2

Please refer method signature
https://azuresdkdocs.blob.core.windows.net/$web/java/azure-cosmos/3.7.2/com/azure/data/cosmos/TokenResolver.html#getAuthorizationToken(java.lang.String,java.lang.String,com.azure.data.cosmos.CosmosResourceType,java.util.Map)

for parameter 
resourceIdOrFullName - ResourceID or resource full name.

What does "ResourceID or resource full name" refer to for a collection, partition and document? An example for each will help.

**Comment by kushagraThapar** [comment]
Assigning this to @milismsft - He has more context on this. 
@milismsft  feel free to discuss this in our next meeting.

**Comment by milismsft** [comment]
A resource ID or resource full name is the full addressable path of the resource associated with this token. For more details please take a look at https://docs.microsoft.com/en-us/rest/api/cosmos-db/access-control-on-cosmosdb-resources#constructkeytoken
