### ISSUE TITLE
[BUG] BlobInputStream exceptions violate JDK interface

### ISSUE THREAD

**Issue by rickle-msft** [Azure/azure-sdk-for-java#10740]
BlobInputStream and BlobOutputStream only ever throw RuntimeExceptions, even in cases where the JDK javadocs specify they should be throwing IOExceptions. This causes consuming code to handle IOExceptions to satisfy the compiler and RuntimeExceptions to handle actual errors. This type should be fixed to behave in accordance with the JDK contract. 

This will require either a suppression of throwing errors that aren't a direct return value of a logger method or better ClientLogger support from core.

**Comment by gapra-msft** [comment]
Closed on account of breaking changes

**Comment by JonathanGiles** [comment]
@gapra-msft You say this is closed but the issue remains open - did you intend to also close this issue?

**Comment by gapra-msft** [comment]
That's my bad, I didnt press close with comment.
