### ISSUE TITLE
Smoke tests found bug in DefaultAzureCredential in sovereign clouds

### ISSUE THREAD

**Issue by danieljurek** [Azure/azure-sdk-for-java#10774]
Nightly smoke test runs found an issue with Identity when setting an authority host for `DefaultAzureCredential`. 

Sample code: 

```java
// ...
                new DefaultAzureCredentialBuilder()
                    .authorityHost(authorityHost)
                    .build()

// other operations using that credential 
```

Expected: Authenticated scenarios work

Actual: Error message

```
com.microsoft.aad.msal4j.MsalServiceException: AADSTS900382: Confidential Client is not supported in Cross Cloud request.
```

([example pipeline execution](https://dev.azure.com/azure-sdk/internal/_build/results?buildId=381435&view=logs&j=6d116950-13b5-52a2-6d23-0d409786ac26&t=e002ea45-caca-5732-1fc3-142e28eedc83&l=225))

This error is frequently seen when running against sovereign clouds when the Identity library is using the default authority host instead of the authority host of the cloud in use.

**Comment by joshfree** [comment]
@g2vinay @jianghaolu PTAL

**Comment by g2vinay** [comment]
This issue should be resolved now,

**Comment by g2vinay** [comment]
@danieljurek can you verify the smoke tests build ?

**Comment by danieljurek** [comment]
Smoke test successful run with the identity package from today's dev feed: https://dev.azure.com/azure-sdk/internal/_build/results?buildId=384751&view=logs&j=f3570516-c8fe-5ce9-92b2-b737df25d5ea&t=7460d86d-d1d5-5469-882a-96eb8925a41c&l=140

Verified smoke tests locally with the 1.1.0-beta.4 version as well.
