### ISSUE TITLE
Support for async delete methods in ResourceGroupsImpl

### ISSUE THREAD

**Issue by amitarali** [Azure/azure-sdk-for-java#1078]
Below way of implementation only support delete() method on ResourceGroup which is a blocking/sync call, beginDelete() or deleteAsync() methods are not supported. With the following approach of Azure client initialization, is there a way to use async delete methods which are part of class ResourceGroupsInner?

Azure azure = Azure.configure()
               .withLogLevel(HttpLoggingInterceptor.Level.NONE)
               .authenticate(appTokenCreds)
               .withSubscription(subscriptionId);
			   
azure.resourceGroups().delete(rgName);

**Comment by jianghaolu** [comment]
Will add at the end-of-month release.

**Comment by jianghaolu** [comment]
Supported and released with beta3.
