### ISSUE TITLE
PublicIpAddressImpl.java java.lang.NullPointerException on fqdn()

### ISSUE THREAD

**Issue by masarlabs** [Azure/azure-sdk-for-java#1079]
Hi,
on  azure-sdk-for-java/azure-mgmt-network/src/main/java/com/microsoft/azure/management/network/implementation/PublicIpAddressImpl.java 

the function 
 public String fqdn() {
        return this.inner().dnsSettings().fqdn();
    }

should check for dnsSettings() == null as in:
 @Override
    public String leafDomainLabel() {
        if (this.inner().dnsSettings() == null) {
            return null;
        } else {
            return this.inner().dnsSettings().domainNameLabel();
        }
    }

I think that it should be done also for:

@Override
    public String reverseFqdn() {
        return this.inner().dnsSettings().reverseFqdn();
    }

**Comment by martinsawicki** [comment]
can't argue with that.
fixed in a pending PR https://github.com/Azure/azure-sdk-for-java/pull/1065/commits/8ec142efb3ed2f1a55f73c210bf2bc167ae4e26e
thanks for catching.
