### ISSUE TITLE
[QUERY] Why are Integration Tests and Unit Tests set up this way?

### ISSUE THREAD

**Issue by ShahmirAhmed** [Azure/azure-sdk-for-java#10842]
**Query/Question**
I wanted to ask why both your Integration and Unit Tests send logs instead of using the Unit Tests to check that the producers are built properly and then the Integration Tests are used to test whether logs are/are not sent?

**Setup (please complete the following information if applicable):**
 - OS: macOSX
 - IDE : IntelliJ
 - Version of the Library used: 5.0.2
 
 **Information Checklist**
 Kindly make sure that you have added all the following information above and checkoff the required fields otherwise we will treat the issuer as an incomplete report
- [x] Query Added
- [x] Setup information Added

**Comment by JimSuplizio** [comment]
@ShahmirAhmed can you please give some more information. I'm not entirely sure what the context of your question is or even what library you're referring to.

**Comment by ShahmirAhmed** [comment]
Hi @JimSuplizio, sorry about that. I'm referring to azure-messaging-eventhubs version 5.0.2. Specifically the classes I am looking at are the `EventHubProducerClientIntegrationTest.java` and `EventHubProducerClientTest.java`. I'm also looking at the Asynchronous Producers as well. 

What I noticed is that in both your integration and unit tests, you 1) build out your producer and 2) send logs with those producers. I would have thought that the unit tests would solely assert and check to see that the producers were built BUT NOT send logs. Then the integration tests would build the producers and actually send logs. I was curious as to why you are sending logs in both types of tests.

**Comment by srnagar** [comment]
@ShahmirAhmed Thank you for providing more details. Unit tests use mock instances for sending. So, they don't send the events to the Event Hubs service but mimic the send operation. Unit tests then assert to see if the mocked send was called. 

On the other hand, integration tests use real instances that actually send events to the Event Hubs service. 

Hope that answers your question. Please let me know if you need additional details.
