### ISSUE TITLE
[FEATURE REQ][Blob Storage] Scrub SAS tokens in IllegalArgumentException

### ISSUE THREAD

**Issue by SukruthKS** [Azure/azure-sdk-for-java#10887]
**Is your feature request related to a problem? Please describe.**
When there are any invalid components in a blob URL like invalid container or blob names, the storage SDK throws an `IllegalArgumentException`. This checking is done at a much later phase and by then, SAS token is already attached to the URL. But the signature is not redacted before the URL is appended to the error message and since the message field is immutable, the application cannot scrub it either without modifying the stack.

Here's a piece of code to reproduce this:

```
String endpoint = "https://doesntmatter.blob.core.windows.net";
String containerName = "bad cont";
String blobName = "myfile.txt";

BlobServiceClient client = new BlobServiceClientBuilder()
    .endpoint(endpoint)
    .sasToken("?sv=2019-10-10&ss=b&srt=sco&sp=rwdlacx&se=2020-06-04T12:04:58Z&st=2020-05-04T04:04:58Z&spr=https&sig=h%2FBk5c07LGZnaqkbtnNqz259Mw3B9ChU21w%2BFsxn3TE%3D")
    .buildClient();

try
{
    client.getBlobContainerClient(containerName)
        .getBlobClient(blobName)
        .getProperties();
}
catch (IllegalArgumentException ex)
{
    System.out.println(ex.getMessage());
}
```

Output:
```
Illegal character in path at index 25: https://doesntmatter.blob.core.windows.net/bad cont/myfile.txt?sv=2019-10-10&ss=b&srt=sco&sp=rwdlacx&se=2020-06-04T12:04:58Z&st=2020-05-04T04:04:58Z&spr=https&sig=h%2FBk5c07LGZnaqkbtnNqz259Mw3B9ChU21w%2BFsxn3TE%3D
```

**Describe the solution you'd like**
Redact the signature in the SAS token before throwing the exception.

**Describe alternatives you've considered**
NA

**Additional context**
NA

**Information Checklist**
Kindly make sure that you have added all the following information above and checkoff the required fields otherwise we will treat the issuer as an incomplete report
- [x] Description Added
- [x] Expected solution specified

**Comment by rickle-msft** [comment]
Hi @SukruthKS. Thanks for reporting this. That is indeed not great. It looks like this is coming from when we try to append the bad container name to the path. I think in that case the safest thing to do would be to strip or redact the entire query in the url we return since it's clearly an issue with the path at that point and trying to track what we should and shouldn't redact from the query is going to be very error prone to duplicate from our actual logging.

**Comment by sfc-gh-skomarla** [comment]
Yeah, makes sense to strip the query string.

**Comment by SukruthKS** [comment]
Yeah, makes sense to strip the query string.

**Comment by SukruthKS** [comment]
Hi @rickle-msft, I wanted to check if this will make it for the June release. Without this, I won't be able to use v12 SDK to keep the credentials from leaking through logging.
