### ISSUE TITLE
[BUG] SSLHandshakeException: General SSLEngine Problem when attempting to connect to servicebus

### ISSUE THREAD

**Issue by wcom939** [Azure/azure-sdk-for-java#11027]
**Describe the bug**
Created a new servicebus standard namespace, created a new topic, with new publish only key, received a handshake error in Java

***Exception or Stack Trace***
Add the exception log and stack trace if available

`aused by: com.microsoft.azure.servicebus.primitives.ServiceBusException: Error{condition=proton:io, description='javax.net.ssl.SSLHandshakeException: General SSLEngine problem', info=null}
	at com.microsoft.azure.servicebus.primitives.ExceptionUtil.toException(ExceptionUtil.java:74) ~[azure-servicebus-3.2.0.jar:na]
	at com.microsoft.azure.servicebus.primitives.MessagingFactory.onConnectionError(MessagingFactory.java:414) ~[azure-servicebus-3.2.0.jar:na]
	at com.microsoft.azure.servicebus.amqp.ConnectionHandler.onTransportError(ConnectionHandler.java:170) ~[azure-servicebus-3.2.0.jar:na]
	at org.apache.qpid.proton.engine.BaseHandler.handle(BaseHandler.java:191) ~[proton-j-0.33.2.jar:na]
	at org.apache.qpid.proton.engine.impl.EventImpl.dispatch(EventImpl.java:108) ~[proton-j-0.33.2.jar:na]
	at org.apache.qpid.proton.reactor.impl.ReactorImpl.dispatch(ReactorImpl.java:324) ~[proton-j-0.33.2.jar:na]
	at org.apache.qpid.proton.reactor.impl.ReactorImpl.process(ReactorImpl.java:291) ~[proton-j-0.33.2.jar:na]
	at com.microsoft.azure.servicebus.primitives.MessagingFactory$RunReactor.run(MessagingFactory.java:556) ~[azure-servicebus-3.2.0.jar:na]
	at java.lang.Thread.run(Thread.java:748) ~[na:1.8.0_251]`

**To Reproduce**
Create a new servicebus namespace, attempt to connect to it using Java, version 3.2.0 of the azure-servicebus library

***Code Snippet***
Add the code snippet that causes the issue.
    @Bean
    TopicClient createServiceBusClient() throws ServiceBusException, InterruptedException {
        return new TopicClient(new ConnectionStringBuilder(serviceBusConnectionString));
    }

**Expected behavior**

Should connect to service bus

**Screenshots**
![image](https://user-images.githubusercontent.com/16446451/81481273-d0421800-91fc-11ea-9c30-ff33cd477b6f.png)

**Setup (please complete the following information):**
 - OS: Win 10
 - IDE : Intellij
 - Version of the Library used 3.2.0
-JDK Oracle 1.8 and Zulu 1.8 both report same issue

**Information Checklist**
Kindly make sure that you have added all the following information above and checkoff the required fields otherwise we will treat the issuer as an incomplete report
- [X ] Bug Description Added
- [ X] Repro Steps Added
- [ X] Setup information Added

**Comment by joshfree** [comment]
@yvgopal could you please take a look?

/cc @hemanttanwar @conniey

**Comment by yvgopal** [comment]
The error suggests there is likely an issue with your application setup. Just looking at the exception, I can't say what is causing the issue. It is very likely that your trust store or the default trust store doesn't have the common certificates. ServiceBus uses a certificate chain where the issuing certificate is one of the few universally trusted public certificates.
This the most common use case of every servicebus sample. We have never seen this error with any sample. Could you just check your application  setup once again? If the issue persists, could you capture more info by enabling java ssl tracing?

**Comment by conniey** [comment]
@wcom939 Were you able to resolve this issue? If not, please feel free to reopen this.

**Comment by trycatchkamal** [comment]
@wcom939 Hope you found what was causing the issue at your end. I have encountered very same issue few days back in my local environment and the stack trace thrown by the sdk was not getting me anywhere. Eventually I figured out you need to have `Microsoft Azure TLS Issuing CA *` from https://www.microsoft.com/pkiops/Docs/Repository.htm in your keystore. So, you would need to figure out which keystore is configured with your web server and then import these above mentioned certs on your keystore and that sorts it out
