### ISSUE TITLE
Snapshot publishing for Azure Spring Boot

### ISSUE THREAD

**Issue by mitchdenny** [Azure/azure-sdk-for-java#11029]
The Spring team wants to publish snapshots of their packages to the SonaType repository. We need to go through the pipeline and make sure that its capable of doing this. It will probably need changes in the artifact upload logic and publishing logic.

We also need to think through how this would work with our versioning infrastructure and the impact in terms of build reliability.

**Comment by mitchdenny** [comment]
Adding @JonathanGiles  @jialindai and @JimSuplizio to discuss.

**Comment by JonathanGiles** [comment]
Ideally this would be a no-friction process that is simply an automated aspect of the nightly CI run that is published as a snapshot release into Maven Central if the build successfully passes.

**Comment by mitchdenny** [comment]
We run one scheduled pipeline each night for each ```sdk/[service]``` directory, plus one more for live tests (where appropriate). To do this we would need to run two, or add another build leg just for Spring Boot to produce the snapshots. We don't produce snapshots anywhere else in the engineering system.

I think it'd mostly be a process of changing the versioning scripts to inject the snapshot version into the various POM files, as well as update any of the internal dependencies to use the snapshot. Then carry that duplicate set of artifacts through the pipeline to where we publish.

Given we already publish strongly versioned nightly packages to [this feed](https://dev.azure.com/azure-sdk/public/_packaging?_a=feed&feed=azure-sdk-for-java), I'm really wondering what benefits this added complexity would provide?

**Comment by JimSuplizio** [comment]
I have the same question as @mitchdenny. We already publish the nightly dev builds to a publicly accessible stream, as documented in [CONTRIBUTING.md](https://github.com/Azure/azure-sdk-for-java/blob/master/CONTRIBUTING.md#nightly-package-builds). I'm also wondering what the benefit is publishing to Maven and also what that means in terms of support.

**Comment by weshaggard** [comment]
I would also like to avoid snapshots. We originally had snapshots for daily dev versioning but we (@JonathanGiles @mitchdenny and myself) meet and decided to update the guidance document (https://github.com/Azure/azure-sdk/pull/585/files#r315810459) to not use snapshots any longer. In general snapshots cause issues with the most common one being reliability issues which is why we decided to avoid them.

**Comment by mitchdenny** [comment]
At this point I don't think we've come up with a compelling reason to do snapshot publishing. Are we good to close this issue down?
