### ISSUE TITLE
Should Azure Spring Boot have BOM?

### ISSUE THREAD

**Issue by mitchdenny** [Azure/azure-sdk-for-java#11030]
Discussion from team chat. The Azure Spring Boot team wants to have a parent (?) POM file which has a ```dependencyManagement``` section. In the existing engineering system we don't have dependency management sections because they interfere with the ability to release individual modules at a separate cadence where their dependencies might differ (even in temporarily). It limits our ability.

The team has cited the fact that the Azure SDK BOM has a ```dependencyManagement``` section. However the Azure SDK BOM is a special case because[ non of the modules that we ship directly reference it](https://github.com/Azure/azure-sdk-for-java/search?q=azure-sdk-bom&unscoped_q=azure-sdk-bom).

It sounds like the desire of the Azure Spring Boot team is for their parent to have a ```dependencyManagement``` section which would have some broad ranging implications for our release process.

**Comment by joshfree** [comment]
@hemanttanwar can you please add this as an agenda item for the next sync up?

**Comment by jialindai** [comment]
The motivation is to allow Spring modules to reference bom provided by spring, could be one of them:
- spring-framework-bom
- spring-boot-dependencies
- spring-security-bom
- spring-data-releasetrain

If having different module share the same bom is one concern, can we allow each individual module to include such bom?

**Comment by mitchdenny** [comment]
In our engineering system, the benefits of a BOM for internal modules is diminished because we mandate that each module should specify the version of its dependency (not relying in the parent to bring it in). Our build pipelines enforce this. So in this case the BOM isn't really adding any value for internal dependencies.

(the same argument can be made for ```azure-sdk-bom``` which isn't really used within our modules at all, its just for external consumption).

Now ... if you want it to make external consumption of Azure Spring Boot modules easier that is fairly straight forward. You would add the BOM to the sdk/boms folder and then you'd have a release train for doing BOM updates if/when you got a stable set of libraries.

**Comment by JimSuplizio** [comment]
Part of the automation for centralized versioning purposely disallows dependencyManagement sections because they directly counteract the centralized versioning. If there needs to be a dependencyManagement section then it should be in a BOM file inside of the [sdk/boms](https://github.com/Azure/azure-sdk-for-java/tree/master/sdk/boms) directory beside the track 2 bom file

**Comment by chenrujun** [comment]
Conclusion:
1. The dependency for internal use, we still use centralized versioning by version tag like `x-version-update`.
2. The dependency for external use, we can release a bom. And we already did in in [azure-spring-boot-bom](https://github.com/Azure/azure-sdk-for-java/blob/master/sdk/boms/azure-spring-boot-bom/pom.xml)

I'll close this issue.
