### ISSUE TITLE
[FEATURE REQ] Cosmos | publish shaded jar for com.microsoft.azure:azure-cosmos

### ISSUE THREAD

**Issue by David-Noble-at-work** [Azure/azure-sdk-for-java#11146]
**Is your feature request related to a problem?

A number of our customers use this package within environments like Spark, Spring Boot, and Tomcat and include a large number of build and runtime dependencies. Sometimes these dependencies conflict with the ones required by com.microsoft.azure:azure-cosmos. The main offender is Guava and we've mitigated that. We've removed our dependency on Guava in v4.

**Solution
To eliminate dependency conflicts that can't be removed (e.g., netty) we should produce and publish a shaded jar. This--we expect--will improve customer satisfaction and reduce support costs.

We should consider back porting this solution to prior version of the SDK. This work should follow v4 GA.

**Comment by kushagraThapar** [comment]
This work is not required anymore as V3 has been deprecated and all the customers have already been moved to V4 Java SDK.
