### ISSUE TITLE
[Storage] SharedKey and SAS query parameters multivalue sort improvement.

### ISSUE THREAD

**Issue by kasobol-msft** [Azure/azure-sdk-for-java#11147]
During implementation of https://github.com/Azure/azure-sdk-for-java/pull/11101 we discovered that order of query parameters when computing SAS or Shared Key signatures matter (per https://docs.microsoft.com/en-us/rest/api/storageservices/authorize-with-shared-key#shared-key-format-for-2009-09-19-and-later ). 
Ideally this should happen at https://github.com/Azure/azure-sdk-for-net/blob/7086132896588ffa6480009a4166d163c63b913c/sdk/storage/Azure.Storage.Common/src/Shared/StorageSharedKeyPipelinePolicy.cs#L131-L142 instead of relying on each feature implementation to sort them.

**Comment by alzimmermsft** [comment]
Per discussions today, this is still an active issue

**Comment by alzimmermsft** [comment]
Closing as this has been completed
