### ISSUE TITLE
Spring Boot: Ensure that the groupId for libraries changes from com.microsoft.azure to com.azure before the libraries go from Hybrid to GA.

### ISSUE THREAD

**Issue by JimSuplizio** [Azure/azure-sdk-for-java#11153]
The initial releases of the Spring Boot libraries out of the azure-sdk-for-java repository are going to be in a hybrid mode and the groupIds are going to be com.microsoft.azure. This work item is so that we remember to change the groupId to com.azure when the libraries are fully Client.

As part of this work, eng/jacoco-test-coverage/pom.xml's maven-enforcer-plugin entry needs to be removed as azure-client-sdk-parent include of com.azure:* would be sufficient.

**Comment by hemanttanwar** [comment]
This will be done in September release.

**Comment by saragluna** [comment]
Done, closing this issue. FYI, spring modules' group id is now `com.azure.spring`. #16148
