### ISSUE TITLE
Co-locate the spring code with the service library prior to GA

### ISSUE THREAD

**Issue by JimSuplizio** [Azure/azure-sdk-for-java#11155]
This issue is fully discussed [here](https://github.com/Azure/azure-sdk/issues/892):  At first everything is is going to be under the sdk/spring directory but it is desirable to co-locate the spring code with the service library prior to GA.

**Comment by saragluna** [comment]
We now put below spring integration modules with service library:
- azure-spring-data-cosmos with sdk/cosmos
- azure-spring-cloud-appconfiguration-xxx with sdk/appconfiguration

For the others, the plan is to keep them under sdk/spring.

**Comment by saragluna** [comment]
Closing this issue now.
