### ISSUE TITLE
Ensure that any SpingSkip issues have been cleaned up before GA

### ISSUE THREAD

**Issue by JimSuplizio** [Azure/azure-sdk-for-java#11154]
This is primarily related to relaxing or omitting code coverage numbers in the individual Spring Boot pom files that will most certainly need to be done when Spring is moving into master. I've asked that a tag similar to the following:
`<!-- SpringSkip - Needed temporary values to 10% not fail. -->`
be added to every pom file that has coverage percentages intentionally lowered or skipped as part of the initial checkins.

**Comment by saragluna** [comment]
Spring modules have been GAed, closing this issue now.
