### ISSUE TITLE
CosmosAsyncContainer / CosmosContainer APIs and Docs

### ISSUE THREAD

**Issue by kushagraThapar** [Azure/azure-sdk-for-java#11191]
Add performance note on the class -> For performance reasons - it is better to cache the containers instead of re-creating it every time . 

`CosmosAsyncContainer` - 
Docs feedback - 
General - remove all “document” words, and check docs for all APIs. 
delete() -> deletes this container. 
queryItems() -> query for items in a container. 

API removal -  
* `readAllItems()` - 2 APIs - make it non-public
* Get rid of all APIs which take int throughput . 
Add another API - createContainerIfNotExists - ThroughputProperties

Remove readProvisionedThroughput API
Remove replaceProvisionedThroughput API

`CosmosContainer` -
 Docs feedback - 
General - remove all “document” words, and check docs for all APIs. 
delete() -> deletes this container. 
queryItems() -> query for items in a container. 

API removal -  
* `readAllItems()` - 2 APIs - make it non-public
* Get rid of all APIs which take int throughput . 
Add another API - createContainerIfNotExists - ThroughputProperties

Remove readProvisionedThroughput API
Remove replaceProvisionedThroughput API

1. `createItem()` -> Force the partition key to the first param ? add another API which takes partition key ? create helper method to extract partition key ?
2. `readAllItems()`, `queryItems()` -> `feedOptions` -> should it be at last, or in middle. 
3. `readItem()` -> partitionKey should come first ?

**Comment by allenhumphreys** [comment]
@kushagraThapar Why is `readAllItems` API removed? Is the recommendation to just do a query and select all?

**Comment by kushagraThapar** [comment]
> @kushagraThapar Why is `readAllItems` API removed? Is the recommendation to just do a query and select all?

@allenhumphreys - Yes, for now the recommendation is just to do a query and select all, as `readAllItems` was doing the same internally. 
Once SDK supports read feed behavior on items, then this will be added back.

**Comment by allenhumphreys** [comment]
Thank you @kushagraThapar , I would argue that it'd be better to leave it public until the new replacement is available. The adoption scenario will go like:

1. Work around missing API by doing query
2. New SDK version supports more performant approach but with different API
3. I will forget to go back and switch back to the new API

**Comment by kushagraThapar** [comment]
@allenhumphreys - That's a valid point, but the reason we can't add it back is because currently `readAllItems()` consume same RUs as select all query, which is incorrect behavior at first place. Due to compliance reasons, we would like to keep it hidden. Nevertheless, let me discuss this again with my team as we are planning GA next week. 

Regarding your concern, I am making a note of informing you guys once read feed behavior is out. We will also document it well in release notes and changelog so that it is easier for customers to notice the change and make the change on their end. 

Meanwhile, please take a look at this changelog for v4 so far and let me know if you have more concerns: https://github.com/Azure/azure-sdk-for-java/blob/master/sdk/cosmos/azure-cosmos/CHANGELOG.md
