### ISSUE TITLE
Smoke Tests Should Run All OSes Against All Clouds

### ISSUE THREAD

**Issue by alzimmermsft** [Azure/azure-sdk-for-java#11206]
Currently the smoke tests are only configured to run Windows against all clouds with all Java version permutations, Linux and MacOS permutations only run on the Azure Cloud and not China Cloud or US Gov cloud.

Add the following permutations if possible:

- [ ] Linux Java 8 on China Cloud
- [ ] Linux Java 11 on China Cloud
- [ ] Linux Java 8 on Gov Cloud
- [ ] Linux Java 11 on Gov Cloud
- [ ] MacOS Java 8 on China Cloud
- [ ] MacOS Java 11 on China Cloud
- [ ] MacOS Java 8 on Gov Cloud
- [ ] MacOS Java 11 on Gov Cloud

**Comment by kurtzeborn** [comment]
@weshaggard and I think that this is a good request, but we should use a sparse matrix like we've done in other test pipelines.

**Comment by kurtzeborn** [comment]
Haven't gotten to this in 3+ years.  Not a priority.

(also java 8 is no longer supported anyway :))
