### ISSUE TITLE
Maven  repository

### ISSUE THREAD

**Issue by pditommaso** [Azure/azure-sdk-for-java#11214]
**Query/Question**

I wanted to give a try to the Blob NIO module however the JAR coordinates published in the README are not available on Maven central: 

https://search.maven.org/search?q=azure-storage-blob-nio

From which repository the library can be downloaded?

**Comment by srnagar** [comment]
@pditommaso Thanks for your interest in using Storage Blob NIO. This library is not yet released to Maven central. 
https://github.com/Azure/azure-sdk-for-java/blob/master/sdk/storage/azure-storage-blob-nio/CHANGELOG.md

@rickle-msft Do you know when this will be released?

**Comment by rickle-msft** [comment]
We don't have an exact date. I have one or two more items to add before we preview, so we're hoping this month. If you're comfortable doing so, you can install the master branch and start using what's available. The last thing I really need to add before preview is support for FileSystemProvider.newOutputStream

**Comment by pditommaso** [comment]
Understandable. Maybe I could make sense to publish a SNAPSHOT version so that early adopters can start to experiment with it?

**Comment by rickle-msft** [comment]
We unfortunately have a publishing process that prohibits snapshots, so I can't offer a snapshot version, but I'll let you know when the official preview is released! :)

**Comment by rickle-msft** [comment]
Hi, @pditommaso. Please refer to my comments on #7158. We have officially released and it should be available through maven now!
