### ISSUE TITLE
Revert the Java $latestJava11Install variable fix once the DevOps images are fixed

### ISSUE THREAD

**Issue by JimSuplizio** [Azure/azure-sdk-for-java#11215]
To work around the Azure DevOps setting the Java 11 environment variable being set to the Java 13 location, the following [PR](https://github.com/Azure/azure-sdk-for-java/pull/11211) was created. The updated Azure DevOps images should be out the week ending 5/22 and, after we verify things are OK, the PR changes need to be reverted.

**Comment by JimSuplizio** [comment]
@weshaggard I know we'd chatted about turning this step into some kind of verification however in the [PR that fixed the virtual environment issue](https://github.com/actions/virtual-environments/pull/887) the install validation was revamped. I don't think re-validation on our end is something that's worth it here.

**Comment by weshaggard** [comment]
While it might be fixed not it would still be nice to essentially have an assert that verifies we are running on a machine with the version of java we expect to be running on.

**Comment by JimSuplizio** [comment]
Just to close out the discussion on here because @weshaggard and I chatted about this over teams. Additional verification isn't necessary for this because the Maven task already runs `maven --version`, before the actual command, which does a version dump for maven that include the Java version as well as the runtime location before running the actual Maven command. This is a good enough breadcrumb to track down if something isn't quite right with the version of Java in the image.
