### ISSUE TITLE
[BUG] Add `TextAnalyticsServiceException` model in TA

### ISSUE THREAD

**Issue by samvaity** [Azure/azure-sdk-for-java#11225]
- [x] Currently, in TA we are converting the TextAnalyticsErrorException to a HttpResponseException and ignoring the ErroCodeValue sent in the TA Exception.

Consider  introducing a `TextAnalyticsServiceException` similar to service side’s `TextAnalyticsErrorException`to correctly represent the ErrorCodeValues.

- [x] Resolve the TODO here - https://github.com/Azure/azure-sdk-for-java/blob/master/sdk/textanalytics/azure-ai-textanalytics/src/main/java/com/azure/ai/textanalytics/ExtractKeyPhraseAsyncClient.java#L160

- [x] Update SDK README to mention the service version support.

- [x] Update old cognitive-services/textanalytics readme to mention about new package location( Confirm with Mayuri and Kate)

**Comment by mssfang** [comment]
Instead of creating a new type, `TextAnalyticsServiceException` we can use 
```
    public HttpResponseException(String message, HttpResponse response, Object value) {}
```
which take `TextAnalyticsError` from model package.

For Resolve the TODO: the service will do that by July. so we will keep it as it is for now.

**Comment by samvaity** [comment]
>For Resolve the TODO: the service will do that by July. so we will keep it as it is for now.

Could you open an issue to track this TODO and add it to the comments?

**Comment by mssfang** [comment]
(1) Offline discussion `TextAnalyticsServiceException` type will not be introduced. Choosed HttpResponseException overload constructor, `HttpResponseException(String message, HttpResponse response, Object value)`.
(2) https://github.com/Azure/azure-sdk-for-java/issues/10962
(3) addressed in https://github.com/Azure/azure-sdk-for-java/pull/11318/files#diff-120a7e45ac3baf2e0719201e59beb2e4R21
