### ISSUE TITLE
[FEATURE REQ][BLOB STORAGE] Multi-part block blob upload using input stream

### ISSUE THREAD

**Issue by SukruthKS** [Azure/azure-sdk-for-java#11231]
**Is your feature request related to a problem? Please describe.**
Azure storage has a limit of 256MB for blob upload using a single PUT request. For larger files, it requires doing a [multi-part upload](https://docs.microsoft.com/en-us/rest/api/storageservices/put-blob#remarks). The storage SDK automatically does this multi-part upload for large files when using the `uploadFromFile` API but not when using `uploadWithResponse` which accepts an InputStream. 

**Describe the solution you'd like**
Use multi-part upload for large files when uploading blobs using an InputStream. I haven't yet checked if `EncryptedBlobClient` uses multi-upload for this API. If it doesn't, please add support for that client too.

**Describe alternatives you've considered**
It's not a viable option for us to save the content to a local disk file and perform the upload. So no other valid alternatives.

**Additional context**
NA

**Information Checklist**
Kindly make sure that you have added all the following information above and checkoff the required fields otherwise we will treat the issuer as an incomplete report
- [x] Description Added
- [x] Expected solution specified

**Comment by rickle-msft** [comment]
Hi, @SukruthKS. Thanks for making this request. BlobClient does have a multi-part [upload method](https://github.com/Azure/azure-sdk-for-java/blob/master/sdk/storage/azure-storage-blob/src/main/java/com/azure/storage/blob/BlobClient.java#L169). If you don't know the length, you can copy to a BlobOutputStream directly, which is what we do internally anyway. Does this method suit your needs at all?

**Comment by SukruthKS** [comment]
Hi @rickle-msft, I was using that same API you mentioned above, but I was still getting the `Request body too large` error.  Here's the sample code to reproduce it:

```
final String containerName = "<container_name>";
final String blobName = "LargeBlob.txt";

File file = new File("/tmp/dummy.txt");

try (InputStream inStream = new FileInputStream(file))
{
    BlockBlobClient blobClient = new BlobClientBuilder()
        .endpoint(client.getAccountUrl())
        .pipeline(client.getHttpPipeline())
        .containerName(containerName)
        .blobName(blobName)
        .buildClient()
        .getBlockBlobClient();

    Response<BlockBlobItem> response = blobClient.uploadWithResponse(
        inStream, file.length(), null, null, null, null, null, null, null);
}
```

and the error I got uploading a 300 MB file:

```
Status code 413, 

<?xml version="1.0" encoding="utf-8"?>
<Error>
    <Code>RequestBodyTooLarge</Code>
    <Message>The request body is too large and exceeds the maximum permissible limit.
RequestId:fd8634a4-601e-0004-3b47-2dc5f4000000
Time:2020-05-18T19:09:55.3552127Z</Message>
    <MaxLimit>268435456</MaxLimit>
</Error>
```

**Comment by rickle-msft** [comment]
It looks like you're using BlockBlobClient. Can you try the one on just BlobClient and see if that's any different?

**Comment by SukruthKS** [comment]
It works with `BlobClient`! Should we use that or are you planning to support it in BlockBlobClient as well?

Btw I wanted to test this with `EncryptedBlobClient` too and encountered a strange behavior. The API  (`uploadWithResponse`) returns immediately before uploading the blob!

**Comment by rickle-msft** [comment]
For this operation, you should use BlobClient. The reason being BlockBlobClient is supposed to map directly to the rest API, so we won't put any composite operations on that client. BlobClient is where higher level things like uploading a large stream will live.

@gapra-msft Can you please take a look at what's going on with EncryptedBlobClient?

**Comment by sfc-gh-skomarla** [comment]
Found the reason for the `EncryptedBlobClient` issue. I forgot to set an Id when creating the encryption key. But shouldn't this throw an error instead of silently returning?

```
JsonWebKey webKey =
    JsonWebKey.fromAes(
        new SecretKeySpec(keyBytes, "AES"),
        Collections.singletonList(KeyOperation.WRAP_KEY))
    .setId("symmkey1"); // missed this line earlier
```

Btw I can also upload large blobs using this client.

**Comment by SukruthKS** [comment]
Found the reason for the EncryptedBlobClient issue. I forgot to set an Id when creating the encryption key. But shouldn't this throw an error instead of silently returning?

```
JsonWebKey webKey =
    JsonWebKey.fromAes(
        new SecretKeySpec(keyBytes, "AES"),
        Collections.singletonList(KeyOperation.WRAP_KEY))
    .setId("symmkey1"); // missed this line earlier
```

Btw I can also upload large blobs using this client.

**Comment by rickle-msft** [comment]
Good to hear you can upload large blobs. 

Off the bat, I agree that silent failure seems like the wrong behavior. I'm not super familiar with JsonWebKey, so we'll have to look into why that is happening. I presume you are then passing this JsonWebKey as the key to the EncryptedBlobClient?

**Comment by SukruthKS** [comment]
Sorry I didn't share the full code earlier. The JsonWebKey then gets wrapped in `AsyncKeyEncryptionKey` which is passed to the encrypted blob client. This is the [approach](https://github.com/Azure/azure-sdk-for-java/issues/6569) I got from the KeyVault team for using a local symmetric key for client side encryption.

```
JsonWebKey webKey =
    JsonWebKey.fromAes(
        new SecretKeySpec(keyBytes, "AES"),
        Collections.singletonList(KeyOperation.WRAP_KEY))
    .setId("symmkey1");

AsyncKeyEncryptionKey kek = new LocalKeyEncryptionKeyClientBuilder()
    .buildAsyncKeyEncryptionKey(webKey)
    .block();

EncryptedBlobClient blobClient = new EncryptedBlobClientBuilder()
    .endpoint(client.getAccountUrl())
    .pipeline(client.getHttpPipeline())
    .containerName(containerName)
    .blobName(blobName)
    .key(kek, KeyWrapAlgorithm.A256KW.toString())
    .buildEncryptedBlobClient();
```

**Comment by gapra-msft** [comment]
Hi @SukruthKS I followed up with the Keyvault team and it sounds like the best step forward for the LocalKey id issue is for keyvault to add an explicit check when a user calls buildAsyncKeyEncryptionKey. 

I've created issue #11336 to track the work for this.

**Comment by sfc-gh-skomarla** [comment]
Thanks @gapra-msft!

**Comment by rickle-msft** [comment]
@SukruthKS Can you please confirm whether all components of this issue have been addressed and if so close it?
