### ISSUE TITLE
[FEATURE REQ] Provide option to load client certificates from InputStream, instead of just String path

### ISSUE THREAD

**Issue by guaranadev** [Azure/azure-sdk-for-java#11243]
**Is your feature request related to a problem? Please describe.**
There is no easy way to load certificate files to REST client from classpath resource (from inside JAR archive), because ClientCertificateCredentialBuilder takes a path (as String) parameter, and Azure Identity library uses it to create a FileInputStream

**Describe the solution you'd like**
Make alternative versions of pemCertificate and pfxCertificate methods in ClientCertificateCredentialBuilder, that take `InputStream certificateStream` as first parameter, instead of `String certificatePath`, so that Java's Classloader.getResourceAsStream() method may be used

**Describe alternatives you've considered**
To load a keystore that is bundled with JAR, one must copy it to a temp file, which is cumbersome

**Additional context**
None

**Information Checklist**
Kindly make sure that you have added all the following information above and checkoff the required fields otherwise we will treat the issuer as an incomplete report
- [ ] Description Added
- [ ] Expected solution specified

**Comment by Petermarcu** [comment]
Thanks for making this feature request!

**Comment by joshfree** [comment]
@jianghaolu could you look into prototyping a solution for this later this semester?

**Comment by guaranadev** [comment]
Thank you for providing this functionality, looking forward to its release

**Comment by kokmok** [comment]
Since the builder's method is not public how are we supposed to use it ? Have I missed something in the doc ?
