### ISSUE TITLE
Export `ProxyOptions` from CosmosClientBuilder API instead of `InetSocketAddress`

### ISSUE THREAD

**Issue by kushagraThapar** [Azure/azure-sdk-for-java#11316]
* Export `ProxyOptions` from CosmosClientBuilder API instead of `InetSocketAddress`
* Currently cosmos only supports `HTTP` proxy through reactor netty client. 
* `ProxyOptions` from azure-core enables end user to setup proxy for `HTTP`, `SOCK4`, and `SOCK5`
* Short term plan is to support `HTTP` proxy but open the API to all types of proxy using `ProxyOptions`
* Long term plan is to update the implementation of reactor netty client to support all 2 types of proxies.

**Comment by anuchandy** [comment]
There is also an implementation of Digest Proxy auth in azure-core-netty [module](https://github.com/Azure/azure-sdk-for-java/tree/master/sdk/core/azure-core-http-netty/src/main/java/com/azure/core/http/netty/implementation). Given cosmos has its own azure-core HttpClient, probably this package is something that could be vendor-ed in cosmos impl package if there is an ask for it in cosmos.

**Comment by kushagraThapar** [comment]
This is done.
