### ISSUE TITLE
[BUG]PartitionBasedLoadBalancer can not work properly

### ISSUE THREAD

**Issue by whzayj1314** [Azure/azure-sdk-for-java#11327]
**Describe the bug**
8 partition on eventhub, but only 0,1,2,4,7 can receive event data , blobContainerAsyncClient can not update information on blob, 0,1,2,4,7 five files on folder checkpoint but no data in them. 

***Exception or Stack Trace***
[pool-6-thread-1] c.a.m.e.PartitionBasedLoadBalancer       : Load balancing for event processor failed - errorCondition[amqp:connection:framing-error]. description[org.apache.qpid.proton.engine.TransportException: connection aborted], errorContext[NAMESPACE:]

**Setup (please complete the following information):**
 - OS: osx
 - IDE : IntelliJ
 - azure-messaging-eventhubs 5.1.0 
 - azure-messaging-eventhubs-checkpointstore-blob 1.1.0

**Comment by whzayj1314** [comment]
https://github.com/Azure/azure-sdk-for-java/blob/master/sdk/eventhubs/azure-messaging-eventhubs/src/samples/java/com/azure/messaging/eventhubs/EventProcessorClientWithBatchReceiveSample.java

**Comment by srnagar** [comment]
@whzayj1314 Could you please provide more details? Was there a connection outage when this error happened? Are you using a proxy? Also, it would be great if you could provide us with a minimal reproducible sample.

Note - the blobs do not contain any data. The ownership details are in the metadata of the blob but that's an implementation detail that applications should not use in any form.

**Comment by whzayj1314** [comment]
here is more details:
1.i have 3 types of iot devices, The problem occurs on the largest number of devices，it has 5 instances using java sdk ,more than 100000 devices.two others has 1 instance
2.the blob checkpoint information:
{"PartitionId":"0","Owner":"-6903-491c-b4d7-92820f4f1171","Token":"","Epoch":5723,"Offset":"793422196221584","SequenceNumber":6294846860}  when i use the 3.0.0 .net sdk
now i use the java sdk, and no information in partition file on blob.

**Comment by whzayj1314** [comment]
> @whzayj1314 Could you please provide more details? Was there a connection outage when this error happened? Are you using a proxy? Also, it would be great if you could provide us with a minimal reproducible sample.
> 
> Note - the blobs do not contain any data. The ownership details are in the metadata of the blob but that's an implementation detail that applications should not use in any form.

here is more details:
1.i have 3 types of iot devices, The problem occurs on the largest number of devices，it has 5 instances using java sdk ,more than 100000 devices.two others has 1 instance
2.the blob checkpoint information:
{"PartitionId":"0","Owner":"-6903-491c-b4d7-92820f4f1171","Token":"","Epoch":5723,"Offset":"793422196221584","SequenceNumber":6294846860} when i use the 3.0.0 .net sdk
now i use the java sdk, and no information in partition file on blob.

**Comment by whzayj1314** [comment]
> @whzayj1314 Could you please provide more details? Was there a connection outage when this error happened? Are you using a proxy? Also, it would be great if you could provide us with a minimal reproducible sample.
> 
> Note - the blobs do not contain any data. The ownership details are in the metadata of the blob but that's an implementation detail that applications should not use in any form.

thx I found the data in blob file properties

**Comment by srnagar** [comment]
Thanks for the update!

**Comment by vchernogorov** [comment]
I don't understand the solution here. How do I get rid of such errors in my logs? What is the cause?
