### ISSUE TITLE
Support new Azure Compute API "SimulateEviction" for both Standalone VM and VMSS VM via Java SDK

### ISSUE THREAD

**Issue by sandeepkv93** [Azure/azure-sdk-for-java#11320]
**Is your feature request related to a problem? Please describe.**
We released new API "SimulateEviction" in Azure Compute. We want JAVA SDK support for it. There are two APIs with the same API name. One for Standalone VM and another for VMScaleSet VM. 

https://docs.microsoft.com/en-us/rest/api/compute/virtualmachines/simulateeviction
https://docs.microsoft.com/en-us/rest/api/compute/virtualmachinescalesetvms/simulateeviction

**Describe the solution you'd like**
Supporting this Compute API via JAVA SDK

**Describe alternatives you've considered**

**Swagger Links**
https://github.com/Azure/azure-rest-api-specs/pull/8929
https://github.com/Azure/azure-rest-api-specs/pull/9102

**Additional context**

**Information Checklist**
Kindly make sure that you have added all the following information above and checkoff the required fields otherwise we will treat the issuer as an incomplete report
- [x] Description Added
- [x] Expected solution specified

**Comment by yungezz** [comment]
HI @xccc-msft this is a feature request. let's talk offline is it necessray to be in Track2

**Comment by yungezz** [comment]
supported in PR https://github.com/Azure/azure-libraries-for-java/pull/1199. SDK released is 1.35.0 https://github.com/Azure/azure-libraries-for-java/releases/tag/v1.35.0
