### ISSUE TITLE
[FEATURE REQ] LocalKeyEncryptionKeyClientBuilder should throw if no key id is present

### ISSUE THREAD

**Issue by gapra-msft** [Azure/azure-sdk-for-java#11336]
Generally we expect the service to throw in case there is no id present, but in the case of local keys we need to do this validation client side. 

Spoke to @jianghaolu offline and it sounds like this check should exist in the LocalKeyEncryptionKeyBuilder before building a local key. 

See comments in this thread about unexpected behavior due to not seeing the keyId on a JsonWebKey

https://github.com/Azure/azure-sdk-for-java/issues/11231#issuecomment-630510145

**Comment by g2vinay** [comment]
@vcolin7 PTAL.

**Comment by vcolin7** [comment]
The LocalKeyEncryptionKeyClientBuilder ultimately calls for [CryptographyAsyncClient](https://github.com/Azure/azure-sdk-for-java/blob/6c3de53594408372e390c5fff26a1a00b5b63e1e/sdk/keyvault/azure-security-keyvault-keys/src/main/java/com/azure/security/keyvault/keys/cryptography/CryptographyAsyncClient.java#L77)'s constructor, where other parts of the JsonWebKey are validated, so I think we should check for the presence of an ID there. What do you think? @jianghaolu @g2vinay

**Comment by vcolin7** [comment]
Created a PR with the proposed change in the meantime.
