### ISSUE TITLE
[BUG] BlobOutputStream exception handling

### ISSUE THREAD

**Issue by rickle-msft** [Azure/azure-sdk-for-java#11347]
BlockBlobOutputStream currently specifically catches BlobStorageException in onErrorResumeNext. If other exceptions are thrown, they are not handled by the stream and may end up getting swallowed. There should be other catch clauses on this stream to ensure that all errors are handled appropriately.

**Comment by gapra-msft** [comment]
Modify to follow FluxInputStream error handling
