### ISSUE TITLE
MSDoc publishing for Track1 Azure Cognitive Computer-Vision Client SDK

### ISSUE THREAD

**Issue by anuchandy** [Azure/azure-sdk-for-java#11344]
We need to update: https://docs.microsoft.com/en-us/java/api/com.microsoft.azure.cognitiveservices.vision.computervision.computervision?view=azure-java-stable using the javadoc jar here: https://repo1.maven.org/maven2/com/microsoft/azure/cognitiveservices/azure-cognitiveservices-computervision/1.0.4-beta/

**Comment by scbedd** [comment]
[Onboarded,](https://github.com/Azure/azure-docs-sdk-java/commit/c68c7e17e7f526525fb4a7a2778a06c232712ac4) CI is failing with the following error:

```
javadoc: error - Please file a bug against the javadoc tool via the Java bug reporting page
(http://bugreport.java.com) after checking the Bug Database (http://bugs.java.com)
for duplicates. Include error messages and the following diagnostic in your report. Thank you.
java.util.regex.PatternSyntaxException: Illegal/unsupported escape sequence near index 83
\a\1\s\target_repo\src\docs-ref-autogen\azure-cognitiveservices-computervision\src\main\java\microsoft\azure\cognitiveservices\vision\computervision\ComputerVision.java
```

Looks like there is an encoding handling problem with the

**Comment by scbedd** [comment]
Resolved issues, reviewable [here.](https://review.docs.microsoft.com/en-us/java/api/overview/azure/cognitiveservices/client/computervision?view=azure-java-stable&branch=smoke-test)

**Comment by scbedd** [comment]
Merging to prod [today](https://github.com/Azure/azure-docs-sdk-java/pull/1023)
