### ISSUE TITLE
Update the common versions of io.micrometer* instead of having spring specific versions

### ISSUE THREAD

**Issue by JimSuplizio** [Azure/azure-sdk-for-java#11378]
As part of this [PR](https://github.com/Azure/azure-sdk-for-java/pull/11031), there were two spring specific dependencies declared in the external_dependencies file. 
spring_io.micrometer:micrometer-registry-azure-monitor;1.3.0
spring_io.micrometer:micrometer-core;1.3.0

Whenever possible it's recommended to update the common dependency rather than declare area specific dependencies. The common [io.micrometer* external_dependencies](https://github.com/Azure/azure-sdk-for-java/blob/master/eng/versioning/external_dependencies.txt#L25) should all three be updated to 1.3.0 instead of having spring specific ones. Since Cosmos is the only other one using this, @kushagraThapar had [commented on the PR](https://github.com/Azure/azure-sdk-for-java/pull/11031#discussion_r428824921) this OK to update but wasn't a blocker to get the PR in.

**Comment by saragluna** [comment]
Closing this issue by this PR #13447.

**Comment by JimSuplizio** [comment]
Thank you @saragluna and @chenrujun for doing this.
