### ISSUE TITLE
[BUG] DefaultAzureCredential doesn't work in beta4

### ISSUE THREAD

**Issue by jongio** [Azure/azure-sdk-for-java#11373]
0. az login
1. create keyvault
2. assign permissions to your azure cli objectId

`az ad signed-in-user show --query objectId -o tsv`

`az keyvault set-policy -n {key vault name}--object-id {object id} --secret-permissions get list set delete --key-permissions create decrypt delete encrypt get list unwrapKey wrapKey update`

3. create java app

4. add this to pom

```xml
<dependency>
      <groupId>com.azure</groupId>
      <artifactId>azure-security-keyvault-keys</artifactId>
      <version>4.2.0-beta.3</version>
    </dependency>
    <dependency>
      <groupId>com.azure</groupId>
      <artifactId>azure-identity</artifactId>
      <version>1.1.0-beta.4</version>
    </dependency>
```

5. add this code

```java
import com.azure.identity.DefaultAzureCredential;
import com.azure.identity.DefaultAzureCredentialBuilder;
import com.azure.identity.KnownAuthorityHosts;
import com.azure.security.keyvault.keys.KeyClientBuilder;
import com.azure.security.keyvault.keys.models.*;
import com.azure.security.keyvault.keys.KeyClient;
import java.time.OffsetDateTime;

DefaultAzureCredential cred = new DefaultAzureCredentialBuilder().build();

                KeyClient keyClient = new KeyClientBuilder().vaultUrl("key vault url")
                                .credential(cred).buildClient();

KeyVaultKey rsaKey = keyClient.createRsaKey(new CreateRsaKeyOptions("CloudRsaKey")
                                .setExpiresOn(OffsetDateTime.now().plusYears(1)).setKeySize(2048));
                System.out.printf("Key is created with name %s and id %s \n", rsaKey.getName(), rsaKey.getId());

```

You'll get this error:

`SEVERE: Cannot create any credentials with the current environment variables   `

> This code works in beta3, so it's  regression with beta4.  

When you do fix this, please add a test to ensure it doesn't regress in the future.  Thanks

azsdke2e

**Comment by jongio** [comment]
Likely a problem with MICRED since doing this solves the issue

`DefaultAzureCredential cred = new DefaultAzureCredentialBuilder().excludeManagedIdentityCredential().build();`

**Comment by g2vinay** [comment]
Fixed and Released.
