### ISSUE TITLE
Spring boot artifactIds need to follow the naming guidance in the Java guidelines.

### ISSUE THREAD

**Issue by JimSuplizio** [Azure/azure-sdk-for-java#11374]
This is the track the artifactId issues to get the Spring PRs in now.
The guidelines are still in the process of being reviewed however the naming convention of the artifacts should be 
`azure-spring-boot-starter-<group>-<service>[-<feature>]`, for example, azure-spring-boot-starter-storage-blob or azure-spring-boot-starter-security-keyvault-secrets. Also, the directory names should match the artifact name except in cases where it'll go past max path and even then something will be abbreviated (see sdk/cognitiveservices)

- azure-active-directory-spring-boot-starter should be azure-spring-boot-starter-active-directory
- azure-active-directory-b2c-spring-boot-starter should be azure-spring-boot-starter-active-directory-b2c
- azure-servicebus-jms-spring-boot-starter should be azure-spring-boot-starter-servicebus-jms
- azure-spring-boot-metrics-starter, I'm not sure what this actually is supposed to be since metrics isn't currently a service
- azure-keyvault-secrets-spring-boot-starter should be azure-spring-boot-starter-keyvault-secrets

**Comment by jialindai** [comment]
Hi @JimSuplizio,

The artifact id `azure-spring-boot-starter-<group>-<service>[-<feature>]` is the guideline for spring modules to be track 2.

We are planning to change the artifact id (together with group id) in one major release. However, before that, we need to keep starters' current group id and artifact id.

Let me know if this will cause problem in engineer system.

**Comment by JimSuplizio** [comment]
> We are planning to change the artifact id (together with group id) in one major release. However, before that, we need to keep starters' current group id and artifact id.

@jialindai, that's exactly why this work item was created, so it wouldn't be overlooked.

**Comment by chenrujun** [comment]
To support both spring-boot 2.2.x and 2.3.x, I want to split one starter module into 2 modules:

For example: split
> azure-spring-boot-starter-active-directory

to 
> azure-spring-boot-2.2-starter-active-directory

and 
> azure-spring-boot-2.3-starter-active-directory

`2.2` is the version of spring-boot,  so I put `2.2` behind `spring-boot`. 
@JimSuplizio , Do you have any concern?

**Comment by JimSuplizio** [comment]
Adding @JonathanGiles @weshaggard @mitchdenny @jialindai @saragluna 
@chenrujun this particular type of change requires more than just my approval/denial. It was never decided how we were going to support multiple spring boot versions within the azure-sdk-for-java repository.

**Comment by chenrujun** [comment]
Reminder to myself: change artifactIds in `sdk/appconfiguration/azure-spring-cloud-xxx`

**Comment by hemanttanwar** [comment]
This should be taken care of in September release.

**Comment by saragluna** [comment]
PR merged, closing this issue now.
