### ISSUE TITLE
Second application instance does not automatically take over event processing when EventProcessorClient is used

### ISSUE THREAD

**Issue by AlainBrazeau** [Azure/azure-sdk-for-java#11419]
We have a Java application that processes events from an Azure IoT Hub.  Since we would like to load balance event processing across multiple instances of this Java application, we are using EventProcessorClient.  However, in a two instance test environment, things are not working as we would expect.  Here is a description of the test we are doing as well as the behavior we are seeing:

-Instance 1 and 2 are both started at the same time.
-Instance 1 proceses events from partition 1.  
-Instance 1 is shutdown
-Instance 2 does not automatically take over processing events from partition 1
-Instance 2 is shutdown and restarted
-Only at that point does instance 2 take over processing events from partition 1.  The first event that it processes is the one we expect, proving that the checkpoint saving mechanism works. 

In the scenario described above, we are expecting not to have to restart Instance 2 in order for it to take over processing events from partition 1.  We have even tried letting instance 2 run for over
an hour after instance 1 is shutdown and it still did not take over processing events from partition 1.

Attached is a text file with the relevant source code from our Spring Boot application.

Any help/advice would be greatly appreciated!

- Azure IoT Hub Pricing and scale tier:  S1 - Standard
- Azure IoT Hub Number of IoT Hub units:  1
- OS:  Windows 10 Enterprise
- IDE: Eclipse
- App server: Tomcat 9.0.16
- Maven dependencies:
[relevant_code.txt](https://github.com/Azure/azure-sdk-for-java/files/4678121/relevant_code.txt)

		<dependency>
		    <groupId>com.azure</groupId>
		    <artifactId>azure-messaging-eventhubs</artifactId>
		    <version>5.1.0</version>
		</dependency>
		<dependency>
		    <groupId>com.azure</groupId>
		    <artifactId>azure-messaging-eventhubs-checkpointstore-blob</artifactId>
		    <version>1.1.0</version>
		</dependency>

**Comment by srnagar** [comment]
@AlainBrazeau Thanks for reporting the issue. The 2nd instance is expected to take over the processing of partition 1 without requiring a restart. Could you please provide the logs for both instance 1 and instance 2?

**Comment by AlainBrazeau** [comment]
As requested, here are the log files.

[instance1.log](https://github.com/Azure/azure-sdk-for-java/files/4689025/instance1.log)
[instance2.log](https://github.com/Azure/azure-sdk-for-java/files/4689031/instance2.log)
[instance2_after_restart.log](https://github.com/Azure/azure-sdk-for-java/files/4689033/instance2_after_restart.log)

**Comment by srnagar** [comment]
@AlainBrazeau I checked the logs for both instance 1 and instance 2. Looks like instance 1 was shut down at around `27-05-2020 08:41:07.438` (that's the last log I see). At this point, only instance 2 is running and after a minute, all 6 partitions are owned by instance 2.
`27-05-2020 08:42:17.202 INFO  c.a.m.e.PartitionBasedLoadBalancer.performLogging - Load is balanced with this event processor owning 6 partitions`.

I also noticed that at 08:45 the connection was closed because the connection was idle for some time and then recovered after retries and instance 2 owning all 6 partitions again until `08:51` when it was stopped and restarted.

It would also be great if you could enable verbose level logging and share it to understand what is happening on the checkpointstore.

**Comment by AlainBrazeau** [comment]
As requested, here are new log files with the logging level set to debug.

[debug_instance1.log](https://github.com/Azure/azure-sdk-for-java/files/4696807/debug_instance1.log)
[debug_instance2.log](https://github.com/Azure/azure-sdk-for-java/files/4696812/debug_instance2.log)
[debug_instance2_after_restart.log](https://github.com/Azure/azure-sdk-for-java/files/4696814/debug_instance2_after_restart.log)

**Comment by AlainBrazeau** [comment]
Do you have any idea what is going on based on the last set of log files?  Is there any other information I can provide?

**Comment by srnagar** [comment]
@AlainBrazeau Thanks for providing the logs. I will take a look at the logs and have an update soon. I don't need any other information at this time!
