### ISSUE TITLE
[BUG] Azure-Core cannot encode with some character in query param

### ISSUE THREAD

**Issue by ChenTanyi** [Azure/azure-sdk-for-java#11451]
**Describe the bug**
Azure-Core cannot encode with some character in query param like $, /

**To Reproduce**
run the following code, it will request with `http://httpbin.org/get?$filter=a/b`

***Code Snippet***
```java
public class App {
    public static void main(String[] args) {
        try {
            HttpClient client = new NettyAsyncHttpClientBuilder().build();
            Service proxy = RestProxy.create(Service.class, new HttpPipelineBuilder().policies(new UrlPolicy()).httpClient(client).build());

            proxy.get("http://httpbin.org/", "a/b")
                    .doOnNext(System.out::println)
                    .block();

        } catch (Exception e) {
            System.out.println(e.getMessage());
            e.printStackTrace();
        }
    }


    @Host("{$host}")
    @ServiceInterface(name = "Service")
    private interface Service {
        @Get("/get")
        Mono<Map<String, Object>> get(@HostParam("$host") String host, @QueryParam("$filter") String filter);
    }

    private static class UrlPolicy implements HttpPipelinePolicy {

        @Override
        public Mono<HttpResponse> process(HttpPipelineCallContext context, HttpPipelineNextPolicy next) {
            System.out.println(context.getHttpRequest().getUrl());
            return next.process();
        }
    }
}
```

**Expected behavior**
It should request with `http://httpbin.org/get?%24filter=a%2Fb` instead.

**Setup (please complete the following information):**
 - OS:  Windows 10
 - IDE : Java 1.8.0_231
 - Version of the Library used 
    - Azure-core, Azure-core-http-netty 1.5.0

**Information Checklist**
Kindly make sure that you have added all the following information above and checkoff the required fields otherwise we will treat the issuer as an incomplete report
- [x] Bug Description Added
- [x] Repro Steps Added
- [x] Setup information Added

**Comment by YijunXieMS** [comment]
@ChenTanyi 
'/' and '?' can be used in query param values according to RFC 3986. Please refer to this [stackoverflow post].(https://stackoverflow.com/questions/2322764/what-characters-must-be-escaped-in-an-http-query-string/31300627#31300627)

Azure core doesn't encode query param names ("$filter" in you example) because we assume no azure service uses a param name that has a space that breaks. Unencoded "$" in param name should work.
Are you aware of any problems caused by this encoding design?

**Comment by ChenTanyi** [comment]
@YijunXieMS Yes, in the PR I mentioned above. The azure SQL database `listMetrics` will fail due to the encoding. You could see the code sample in https://github.com/azure/azure-sdk-for-java/blob/4bb437c58cdf2c7645fa6932862507c931d47b21/sdk/resourcemanager/azure-resourcemanager-samples/src/main/java/com/azure/resourcemanager/sql/samples/GettingSqlServerMetrics.java#L199 while the track 1 code with encoding will succeed.

**Comment by ChenTanyi** [comment]
After discussing, the SQL request error is due to the time format instead of encoding. So close it.
