### ISSUE TITLE
Receiving 404 when creating resource groups using the Azure class

### ISSUE THREAD

**Issue by miklopz** [Azure/azure-sdk-for-java#1145]
Using a code such as this:

```
public static void main(String[] args) {
    try {
            File credentialsFile = new File("... Real file path ...");
            
            Azure azure = Azure.configure()
                    .authenticate(credentialsFile)
                    .withDefaultSubscription();
            
                azure.resourceGroups()
                .define("TestResourceGroup")
				// Withheld location for this example, but it is specified in the real repro
                .withRegion("")
                .create();
        } catch (Exception e) {
            e.printStackTrace();
        }
    }
```

I was debugging and noticed the requests were going out to management.azure.com instead of management.usgovcloudapi.net, this results in a 404 because it couldn't find the subscription. The configuration file looks as follows with regards to endpoints:

```
subscription=XXXXXXXX-XXXX-XXXX-XXXX-XXXXXXXXXXXX
client=XXXXXXXX-XXXX-XXXX-XXXX-XXXXXXXXXXXX
key=XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
tenant=XXXXXXXX-XXXX-XXXX-XXXX-XXXXXXXXXXXX
managementURI=https\://management.core.usgovcloudapi.net/
baseURL=https\://management.usgovcloudapi.net/
authURL=https\://login.microsoftonline.com/
graphURL=https\://graph.windows.net/

```
After attempting to debug the issue, I noticed that Configure() creates the RestClient based on the AzureEnvironment.AZURE value, once authenticate() is invoked, it doesn't reconfigure the RestClient, causing the RestClient to remain pointing to management.azure.com. 

Afterwards, I decided to change as follows:

```
RestClient client = AzureEnvironment.AZURE_US_GOVERNMENT.newRestClientBuilder().build()
Azure azure = Azure.authenticate(client, "subscriptionId");

```
And, while this method does seem to correctly point to management.usgovcloudapi.net, it seems to have issues authenticating and was returning a 401 because the Authorization header was missing.

**Comment by jianghaolu** [comment]
Thanks @miklopz, I can reproduce.

@martinsawicki No credentials outside public cloud can be authenticated at this moment. Need to be fixed before release.

**Comment by jianghaolu** [comment]
We fixed the authentication in `configure()` and will be coming in the next release (this week). For your second flow, you simply need to call `.withCredentials()` to add the credentials to the rest client.

**Comment by jianghaolu** [comment]
Fixed and released with beta3.
