### ISSUE TITLE
Cannot assign existing public IP during load balancer creation

### ISSUE THREAD

**Issue by jkubrynski** [Azure/azure-sdk-for-java#1146]
When I try to assign existing public IP to load balancer's frontend IP configuration it breaks with below exception. It looks like PublicIPAddressInner is a problem due to `JsonProperty.Access.WRITE_ONLY` property set on `id`

```
  "error": {
    "code": "InvalidRequestFormat",
    "message": "Cannot parse the request.",
    "details": [
      {
        "code": "MissingJsonReferenceId",
        "message": "Value for reference id is missing. Path properties.frontendIPConfigurations[0].properties.publicIPAddress."
      }
    ]
  }
```

**Comment by martinsawicki** [comment]
could you pls provide your code sample that reveals this issue?

**Comment by jkubrynski** [comment]
I'm doing something like this during creation. I'll be also great if I could just create `SubResource` and set known ID.
```
PublicIPAddressInner publicIPAddress = azure.publicIpAddresses().getById(publicAddressId);
frontendIPConfiguration.withPublicIPAddress(publicIPAddress);
```

**Comment by martinsawicki** [comment]
if the goal is to assign an existing PIP to an LB you're creating, the following test shows one quick and dirty way to do that -- look at [TestLoadBalancer.InternetMinimal#createResource()](https://github.com/Azure/azure-sdk-for-java/blob/master/azure/src/test/java/com/microsoft/azure/TestLoadBalancer.java#L378). This approach assumes the PIP will be added to a frontend IP config called "default".

If you want to assign the PIP to a specific frontend named "foo", then you'd just use the expanded form for defining the frontend, like this:
```java
LoadBalancer lb = resources.define("mylb")
    .withRegion(TestLoadBalancer.REGION)
    .withExistingResourceGroup(TestLoadBalancer.GROUP_NAME)

    // Frontends
    .definePublicFrontend("foo")
        .withExistingPublicIpAddress(publicIpAddress)
        .attach()
  .... etc
```
The above is actually an excerpt from a longer test at [TestLoadBalancer.InternetWithNatRule](https://github.com/Azure/azure-sdk-for-java/blob/master/azure/src/test/java/com/microsoft/azure/TestLoadBalancer.java#L209). Overall, if you look at our tests, they may be helpful in understanding the pattern.

**Comment by jkubrynski** [comment]
@martinsawicki that looks great, but unfortunately `azure.loadBalancers()` method is not available in 1.0.0-beta2.

**Comment by martinsawicki** [comment]
yes, beta3 - Master - will ship maven binaries in a couple of days :-)

**Comment by martinsawicki** [comment]
closing as this is addressed in beta3
