### ISSUE TITLE
[BUG] DataLakeLeaseClient releaseLease is not changing the lease status

### ISSUE THREAD

**Issue by Anusarani** [Azure/azure-sdk-for-java#11460]
**Describe the bug**
After writing a file in datalake, I was calling the DataLakeLeaseClient's releaseLease method for releasing the acquired lease. After the release lease operation, the lease state is correctly updated as  'Available' but the  '**Lease status**' property of the file is showing as '**Locked**'. 

**Expected behavior**
After the releaseLease operation, the Lease Status property should be updated to Unlocked state.

**Setup (please complete the following information):**
Dependency version - azure-storage-file-datalake 12.1.0

**Comment by rickle-msft** [comment]
Hi, @Anusarani. Thank you for reporting this issue. We'll do some work to verify this behavior, but I suspect this might actually be a service bug. In any case, lease state is the recommended way of working with leases at the moment, and lease status is mostly kept around for backwards compatibility, so I hope you aren't blocked on this?

**Comment by Anusarani** [comment]
We are not blocked due to this issue. We are able to perform read, delete and write operation on this file even if the lease status is shown as Locked. But not sure if any other datalake operations will be impacted due to this lease status. Can you please confirm?

**Comment by rickle-msft** [comment]
We have confirmed the behavior you are seeing, and it does look like a service issue. We will engage with the appropriate teams and ensure this behavior does not negatively impact any other apis.

**Comment by rickle-msft** [comment]
I am going to close this issue as it should be fixed for free when the service fixes its bug and therefore there is no active work for the client here.
