### ISSUE TITLE
getRequestCharge() / Properties types / getResourceId() APIs

### ISSUE THREAD

**Issue by kushagraThapar** [Azure/azure-sdk-for-java#11483]
1. getRequestCharge() API - update docs for this API across SDK
2. Remove no-arg constructors across properties types across SDK. 
3. Add constructors with id and body where necessary (CosmosTriggerProperties, CosmosUserProperties, CosmosStoredProcedureProperties, etc.) 
4. Remove getResourceId() API - package private across SDK

**Comment by milismsft** [comment]
@kushagraThapar 2. and 3. cannot be implemented because there's a constructor that takes a JSON payload which is used to create the resource object underneath.

**Comment by kushagraThapar** [comment]
This is done.
