### ISSUE TITLE
Configure DiagnosticsProfile on VM creation

### ISSUE THREAD

**Issue by jkubrynski** [Azure/azure-sdk-for-java#1149]
Currently, it's not possible to setup `DiagnosticsProfile` when using `Azure.virtualMachines().define()` method.

**Comment by anuchandy** [comment]
@jkubrynski 

`DiagnosticsProfile` can be enabled by adding an extension for the same to the virtual machine. Refer this https://github.com/Azure/azure-sdk-for-java/pull/1160/files unit test to see how to define this extension for a linux virtual machine.

It looks like it it make sense to have a convenience layer to enable this for a virtual machine, we'll add that if it is feasible.

The unit test adds the extension as a part of VM update (`Update`). We can do that during VM creation time as well (`Define`), we need to find the id of the to be created VM to do this. The format of the id is: `/subscriptions/{subscription_id}/resourceGroups/{resourceGroup_name}/providers/Microsoft.Compute/virtualMachines/{vm_name}`

**Comment by jkubrynski** [comment]
Thanks @anuchandy - this extension works like a charm. But as I understand it's not the same as BootDiagnostics which could be set in DiagnosticProfile?

**Comment by anuchandy** [comment]
@jkubrynski the wither to enable boot diagnostics is not implemented, created a work item to track this https://github.com/Azure/azure-sdk-for-java/issues/1163

Seems boot diagnostics cannot be enabled via extensions, only runtime diagnostics can be configured through extensions.

**Comment by anuchandy** [comment]
This support is added and will be available as part of 1.2 release.

**Comment by anuchandy** [comment]
Feature is available as of v1.2 hence closing this.
