### ISSUE TITLE
[FormRecognizer] make `useTrainingLabels` parameter required

### ISSUE THREAD

**Issue by jeremymeng** [Azure/azure-sdk-for-java#11522]
Per discussion in internal Teams channel we will make useTrainingLabels parameter required for preview.3

Related: https://github.com/Azure/azure-sdk-for-net/issues/12079

**Comment by samvaity** [comment]
`useTrainingLabels` is always required parameter in Java.
[FormTrainingClient](https://github.com/Azure/azure-sdk-for-java/blob/master/sdk/formrecognizer/azure-ai-formrecognizer/src/main/java/com/azure/ai/formrecognizer/training/FormTrainingClient.java#L75) and [FormTrainingAsyncClient](https://github.com/Azure/azure-sdk-for-java/blob/master/sdk/formrecognizer/azure-ai-formrecognizer/src/main/java/com/azure/ai/formrecognizer/training/FormTrainingAsyncClient.java#L131)
