### ISSUE TITLE
NoClassDefFoundError for com.azure.core.http.policy.HttpLoggingPolicy

### ISSUE THREAD

**Issue by suhas9844** [Azure/azure-sdk-for-java#11556]
**Describe the bug**
This is related to Azure Blob storage Java SDK version 12.6.1.
Gives NoClassDefFoundError
***Exception or Stack Trace***
When using blob storage sdk with com.microsoft.azure.sdk.iot iot device client sdk, I get the below NoclassDefError.

java.lang.NoClassDefFoundError: Could not initialize class com.azure.core.http.policy.HttpLoggingPolicy

When trying to connect to blob storage account like below:
BlobServiceClient blobServiceClient = new BlobServiceClientBuilder().connectionString(connectionString).buildClient(); BlobContainerClient containerClient = blobServiceClient.getBlobContainerClient(blobContainername);

**To Reproduce**
Use azure blob storage SDK 12.6.1 with azure iot device client sdk version 1.17.5 and run the below code snippet..
BlobServiceClient blobServiceClient = new BlobServiceClientBuilder().connectionString(connectionString).buildClient(); BlobContainerClient containerClient = blobServiceClient.getBlobContainerClient(blobContainername);

***Code Snippet***
BlobServiceClient blobServiceClient = new BlobServiceClientBuilder().connectionString(connectionString).buildClient(); BlobContainerClient containerClient = blobServiceClient.getBlobContainerClient(blobContainername);

**Expected behavior**

**Screenshots**

**Setup (please complete the following information):**
Used  arm32v7/openjdk:8-jdk-slim docker image to run the Java jar..
**Additional context**

**Information Checklist**
Kindly make sure that you have added all the following information above and checkoff the required fields otherwise we will treat the issuer as an incomplete report
- [ Yes] Bug Description Added
- [Yes ] Repro Steps Added
- [ Yes] Setup information Added

**Comment by joshfree** [comment]
@alzimmermsft could you please assist?

**Comment by rickle-msft** [comment]
@suhas9844 Thank you for reporting this issue. Can you please refer to [this](https://github.com/Azure/azure-sdk-for-java/wiki/Frequently-Asked-Questions#im-getting-a-nosuchmethoderror-or-noclassdeffounderror) entry in the FAQ and see if that resolves your issue?

**Comment by suhas9844** [comment]
@rickle-msft Thanks for response.Please find the output of the mvn depenedency tree..

[INFO] com.edgemodule:SimulatorModule:jar:1.0.0-SNAPSHOT
[INFO] +- com.microsoft.azure.sdk.iot:iot-device-client:jar:1.17.5:compile
[INFO] |  +- com.github.jnr:jnr-unixsocket:jar:0.23:compile
[INFO] |  |  +- com.github.jnr:jnr-ffi:jar:2.1.10:compile
[INFO] |  |  |  +- com.github.jnr:jffi:jar:1.2.19:compile
[INFO] |  |  |  +- com.github.jnr:jffi:jar:native:1.2.19:runtime
[INFO] |  |  |  +- org.ow2.asm:asm:jar:7.1:compile
[INFO] |  |  |  +- org.ow2.asm:asm-commons:jar:7.1:compile
[INFO] |  |  |  +- org.ow2.asm:asm-analysis:jar:7.1:compile
[INFO] |  |  |  +- org.ow2.asm:asm-tree:jar:7.1:compile
[INFO] |  |  |  +- org.ow2.asm:asm-util:jar:7.1:compile
[INFO] |  |  |  +- com.github.jnr:jnr-a64asm:jar:1.0.0:compile
[INFO] |  |  |  \- com.github.jnr:jnr-x86asm:jar:1.0.2:compile
[INFO] |  |  +- com.github.jnr:jnr-constants:jar:0.9.12:compile
[INFO] |  |  +- com.github.jnr:jnr-enxio:jar:0.21:compile
[INFO] |  |  \- com.github.jnr:jnr-posix:jar:3.0.50:compile
[INFO] |  +- org.apache.qpid:proton-j:jar:0.30.0:compile
[INFO] |  +- com.microsoft.azure.sdk.iot:iot-deps:jar:0.8.4:compile
[INFO] |  |  +- org.bouncycastle:bcmail-jdk15on:jar:1.61:compile
[INFO] |  |  |  \- org.bouncycastle:bcpkix-jdk15on:jar:1.61:compile
[INFO] |  |  +- org.bouncycastle:bcprov-jdk15on:jar:1.61:compile
[INFO] |  |  \- org.glassfish:javax.json:jar:1.0.4:compile
[INFO] |  +- com.microsoft.azure:azure-storage:jar:2.2.0:compile
[INFO] |  |  +- com.fasterxml.jackson.core:jackson-core:jar:2.2.3:compile
[INFO] |  |  \- org.apache.commons:commons-lang3:jar:3.3.2:compile
[INFO] |  +- org.eclipse.paho:org.eclipse.paho.client.mqttv3:jar:1.2.0:compile
[INFO] |  +- com.microsoft.azure.sdk.iot.provisioning.security:security-provider:jar:1.3.0:compile
[INFO] |  +- commons-codec:commons-codec:jar:1.10:compile
[INFO] |  \- org.slf4j:slf4j-api:jar:1.7.25:compile
[INFO] +- com.google.code.gson:gson:jar:2.8.5:compile
[INFO] +- org.apache.httpcomponents:httpclient:jar:4.5.12:compile
[INFO] |  +- org.apache.httpcomponents:httpcore:jar:4.4.13:compile
[INFO] |  \- commons-logging:commons-logging:jar:1.2:compile
[INFO] +- org.slf4j:slf4j-log4j12:jar:1.7.25:compile
[INFO] |  \- log4j:log4j:jar:1.2.17:compile
[INFO] \- com.azure:azure-storage-blob:jar:12.6.1:compile
[INFO]    +- com.azure:azure-core:jar:1.5.0:compile
[INFO]    |  +- com.fasterxml.jackson.datatype:jackson-datatype-jsr310:jar:2.10.1:compile
[INFO]    |  |  +- com.fasterxml.jackson.core:jackson-annotations:jar:2.10.1:compile
[INFO]    |  |  \- com.fasterxml.jackson.core:jackson-databind:jar:2.10.1:compile
[INFO]    |  +- com.fasterxml.jackson.dataformat:jackson-dataformat-xml:jar:2.10.1:compile
[INFO]    |  |  +- com.fasterxml.jackson.module:jackson-module-jaxb-annotations:jar:2.10.1:compile
[INFO]    |  |  |  +- jakarta.xml.bind:jakarta.xml.bind-api:jar:2.3.2:compile
[INFO]    |  |  |  \- jakarta.activation:jakarta.activation-api:jar:1.2.1:compile
[INFO]    |  |  +- org.codehaus.woodstox:stax2-api:jar:4.2:compile
[INFO]    |  |  \- com.fasterxml.woodstox:woodstox-core:jar:6.0.2:compile
[INFO]    |  +- io.projectreactor:reactor-core:jar:3.3.5.RELEASE:compile
[INFO]    |  |  \- org.reactivestreams:reactive-streams:jar:1.0.3:compile
[INFO]    |  \- io.netty:netty-tcnative-boringssl-static:jar:2.0.29.Final:compile
[INFO]    \- com.azure:azure-storage-common:jar:12.6.1:compile
[INFO]       \- com.azure:azure-core-http-netty:jar:1.5.1:compile
[INFO]          +- io.netty:netty-handler:jar:4.1.49.Final:compile
[INFO]          |  +- io.netty:netty-common:jar:4.1.49.Final:compile
[INFO]          |  +- io.netty:netty-resolver:jar:4.1.49.Final:compile
[INFO]          |  +- io.netty:netty-transport:jar:4.1.49.Final:compile
[INFO]          |  \- io.netty:netty-codec:jar:4.1.49.Final:compile
[INFO]          +- io.netty:netty-handler-proxy:jar:4.1.49.Final:compile
[INFO]          |  \- io.netty:netty-codec-socks:jar:4.1.49.Final:compile
[INFO]          +- io.netty:netty-buffer:jar:4.1.49.Final:compile
[INFO]          +- io.netty:netty-codec-http:jar:4.1.49.Final:compile
[INFO]          +- io.netty:netty-codec-http2:jar:4.1.49.Final:compile
[INFO]          +- io.netty:netty-transport-native-unix-common:jar:4.1.49.Final:compile
[INFO]          +- io.netty:netty-transport-native-epoll:jar:linux-x86_64:4.1.49.Final:compile
[INFO]          \- io.projectreactor.netty:reactor-netty:jar:0.9.7.RELEASE:compile


I can only see azure-core-1.5.0.jar once (which contains com.azure.core.http.policy.HttpLoggingPolicy).


Below is my dependencies in pom.xml..

 <properties>
        <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
        <maven.compiler.source>1.8</maven.compiler.source>
        <maven.compiler.target>1.8</maven.compiler.target>
        <azure.iot.device.client.version>1.17.5</azure.iot.device.client.version>
    </properties>

    <dependencyManagement>
        <dependencies>
             <dependency>
                <groupId>com.microsoft.azure.sdk.iot</groupId>
                <artifactId>iot-device-client</artifactId>
                <version>${azure.iot.device.client.version}</version>
             </dependency>
        </dependencies>
    </dependencyManagement>

    <dependencies>
        <dependency>
            <groupId>com.microsoft.azure.sdk.iot</groupId>
            <artifactId>iot-device-client</artifactId>
        </dependency>
        <dependency>
		  <groupId>com.google.code.gson</groupId>
		  <artifactId>gson</artifactId>
		  <version>2.8.5</version>
		</dependency>
		<dependency>
		    <groupId>org.apache.httpcomponents</groupId>
		    <artifactId>httpclient</artifactId>
		    <version>4.5.12</version>
		</dependency>
		<dependency>
			<groupId>org.slf4j</groupId>
			<artifactId>slf4j-log4j12</artifactId>
			<version>1.7.25</version>
		</dependency>
		<dependency>
		    <groupId>com.azure</groupId>
		    <artifactId>azure-storage-blob</artifactId>
		    <version>12.6.1</version>
		</dependency>

	
    </dependencies>
    

    <build>
        <pluginManagement>
            <plugins>
                <plugin>
                    <artifactId>maven-jar-plugin</artifactId>
                    <version>3.0.2</version>
                </plugin>
                <plugin>
                    <artifactId>maven-shade-plugin</artifactId>
                    <version>2.4</version>
                </plugin>
            </plugins>
        </pluginManagement>
        <plugins>
            <plugin>
                <artifactId>maven-jar-plugin</artifactId>
                <configuration>
                    <archive>
                        <manifest>
                            <addClasspath>true</addClasspath>
                            <mainClass>com.edge.Application.App</mainClass>
                        </manifest>
                    </archive>
                </configuration>
            </plugin>
            <plugin>
                <artifactId>maven-shade-plugin</artifactId>
                <executions>
                    <execution>
                        <phase>package</phase>
                        <goals>
                            <goal>shade</goal>
                        </goals>
                        <configuration>
                            <filters>
                                <filter>
                                    <artifact>*:*</artifact>
                                    <excludes>
                                        <exclude>META-INF/*.SF</exclude>
                                        <exclude>META-INF/*.RSA</exclude>
                                    </excludes>
                                </filter>
                            </filters>
                            <shadedArtifactAttached>true</shadedArtifactAttached>
                            <shadedClassifierName>with-deps</shadedClassifierName>
                        </configuration>
                    </execution>
                </executions>
            </plugin>
        </plugins>

**Comment by alzimmermsft** [comment]
Hi @suhas9844, I used your configuration locally and was able to get a runtime exception that was slightly different from the `NoClassDefFoundError` that you are seeing, this is the exception:

```
java.lang.NoSuchMethodError: 'boolean com.fasterxml.jackson.core.JsonFactory.requiresPropertyOrdering()'
```

I believe this is the true root of this issue, as the IOT module transitively adds `com.fasterxml.jackson.core:jackson-core:jar:2.2.3` to the class path through the `com.microsoft.azure:azure-storage:jar:2.2.0` it has. The `azure-storage-blob` module uses Jackson 2.10.1 which will attempt to transitively add the correlating version of `jackson-core` to the class path, but due to how Maven will resolve dependencies the older version will be used. This is a reduced `dependency:tree -Dverbose` output which shows the outcome:

```xml
org.example:HttpLoggingPolicyNoClassDef:jar:1.0-SNAPSHOT
+- com.azure:azure-storage-blob:jar:12.6.1:compile
|  +- com.azure:azure-core:jar:1.5.0:compile
|  |  +- com.fasterxml.jackson.datatype:jackson-datatype-jsr310:jar:2.10.1:compile
|  |  |  +- com.fasterxml.jackson.core:jackson-annotations:jar:2.10.1:compile
|  |  |  +- (com.fasterxml.jackson.core:jackson-core:jar:2.10.1:compile - omitted for conflict with 2.2.3)
|  |  |  \- com.fasterxml.jackson.core:jackson-databind:jar:2.10.1:compile
|  |  |     +- (com.fasterxml.jackson.core:jackson-annotations:jar:2.10.1:compile - omitted for duplicate)
|  |  |     \- (com.fasterxml.jackson.core:jackson-core:jar:2.10.1:compile - omitted for duplicate)
|  |  +- com.fasterxml.jackson.dataformat:jackson-dataformat-xml:jar:2.10.1:compile
|  |  |  +- (com.fasterxml.jackson.core:jackson-core:jar:2.10.1:compile - omitted for duplicate)
|  |  |  +- (com.fasterxml.jackson.core:jackson-annotations:jar:2.10.1:compile - omitted for duplicate)
|  |  |  +- (com.fasterxml.jackson.core:jackson-databind:jar:2.10.1:compile - omitted for duplicate)
|  |  |  +- com.fasterxml.jackson.module:jackson-module-jaxb-annotations:jar:2.10.1:compile
|  |  |  |  +- (com.fasterxml.jackson.core:jackson-annotations:jar:2.10.1:compile - omitted for duplicate)
|  |  |  |  +- (com.fasterxml.jackson.core:jackson-core:jar:2.10.1:compile - omitted for duplicate)
|  |  |  |  +- (com.fasterxml.jackson.core:jackson-databind:jar:2.10.1:compile - omitted for duplicate)
|  |  |  |  +- jakarta.xml.bind:jakarta.xml.bind-api:jar:2.3.2:compile
|  |  |  |  |  \- (jakarta.activation:jakarta.activation-api:jar:1.2.1:compile - omitted for duplicate)
|  |  |  |  \- jakarta.activation:jakarta.activation-api:jar:1.2.1:compile
|  |  |  +- org.codehaus.woodstox:stax2-api:jar:4.2:compile
|  |  |  \- com.fasterxml.woodstox:woodstox-core:jar:6.0.2:compile
|  |  |     \- (org.codehaus.woodstox:stax2-api:jar:4.2:compile - omitted for duplicate)
+- com.microsoft.azure.sdk.iot:iot-device-client:jar:1.17.5:compile
|  +- com.microsoft.azure:azure-storage:jar:2.2.0:compile
|  |  +- com.fasterxml.jackson.core:jackson-core:jar:2.2.3:compile
|  |  +- (org.slf4j:slf4j-api:jar:1.7.5:compile - omitted for conflict with 1.7.28)
|  |  \- org.apache.commons:commons-lang3:jar:3.3.2:compile
```

`HttpLoggingPolicy` throws this exception as it uses an `ObjectMapper` internally which will throw `NoSuchMethodError` on this line of code which was added after the Jackson 2.2.3 release, https://github.com/FasterXML/jackson-databind/blob/jackson-databind-2.10.1/src/main/java/com/fasterxml/jackson/databind/ObjectMapper.java#L622.

One solution to this issue is explicitly including jackson-core 2.10.1 in your POM so that Maven resolves that as the dependency to use, the other solution as @rickle-msft is the shade certain dependencies so they no longer conflict in the class path.

**Comment by suhas9844** [comment]
@alzimmermsft Thanks for the explanation, will try the suggested solutions.
