### ISSUE TITLE
Deployment resource's beginCreateAsync does not create resource group and fail with resource group not found.

### ISSUE THREAD

**Issue by anudeepsharma** [Azure/azure-sdk-for-java#1156]
Deployment deployment = azure.deployments().define(deploymentName)
                            .withNewResourceGroup(rgName, Region.US_WEST)
                            .withTemplate(templateJson)
                            .withParameters("{}")
                            .withMode(DeploymentMode.INCREMENTAL)
                            .beginCreate();

Fails with {"error":{"code":"ResourceGroupNotFound","message":"Resource group 'rgrsat99535645dc199' could not be found."}}

**Comment by jianghaolu** [comment]
Fixed and released with beta3.
