### ISSUE TITLE
Support virtual network peerings

### ISSUE THREAD

**Issue by jkubrynski** [Azure/azure-sdk-for-java#1166]
Currently, it's not present in the fluent interface - only on `NetworkManagementClientImpl`

**Comment by martinsawicki** [comment]
correct, on my to-do list for the next wave (beta4).

**Comment by jkubrynski** [comment]
Is there any roadmap available? It would save us many issues :)

**Comment by martinsawicki** [comment]
priorities can change with evolving circumstances, but right now, the aspiration for the next wave (beta4)  ETA by end of this calendar year -- is to finish the coverage of Azure networking (app gateways, peering, cdn, dns, vpn, express route, traffic mgr, and whatever else is under networking) and WebApp mgmt. Maybe Azure SQL and managed disks, but that's more of a maybe.
Overall, the aspiration is to finish the "big 5": Compute, Storage, Networking, SQL and WebApps asap, before expanding to other Azure services. 
Occasionally, there are quick opportunities for us to cover something outside the "big 5", like in beta3, we'll have Azure Batch mgmt, and in Beta4 we'll have Azure Redis mgmt. covered.

What services specifically are you looking forward to having covered?

**Comment by jkubrynski** [comment]
Peering and app gateway sound great. CDN would be great, but currently it doesn't support custom SSL certificates so it's useless :) Document DB and SQL would be great

**Comment by martinsawicki** [comment]
great, good to know this, thanks.
pls keep the feedback and questions coming - it's really appreciated and helpful.
dzięki.

**Comment by jkubrynski** [comment]
:+1:

**Comment by jkubrynski** [comment]
Any progress here? In 1.1.2 it is still unavailable

**Comment by ynmanware** [comment]
Really, keen to have this feature on fluent Interface....
It has been quite a some time that Azure has Peering feature, but not having on the interface makes it unusable in most of the cases. 
Any plans on implementing it in the near future?

**Comment by yogesh-insta** [comment]
Really, keen to have this API on the fluent Interface....
It has been quite a some time that Azure has Peering feature, but not having on the interface makes it unusable in most of the cases.
Any plans on implementing it in the near future?

**Comment by martinsawicki** [comment]
sorry about the delay. I attempted to put a fluent face on top of this a few months ago expecting it to be maybe a week or two of work, but after digging deeper, it became apparent that to wrap the model exposed by the REST API in a way that actually adds value (i.e. makes it significantly more usable/intuitive) on the "fluent" side will take quite a bit more thought and work, as the REST API model/logic, as you've probably noticed, is quite a bit more complicated than the relatively simple concept it is intended to represent. So we needed to postpone until a bigger timeslot opens up.

Your inquiries help put it higher up on the priority stack though, and I'd really like us to be able to get to it in the release after the upcoming v1.2.

In the meantime, as you probably know, there is a way to get to the auto-generated "inner" API for vnet peering -- `NetworkManager.inner()` provides access to the top level auto-gen'd networking mgmt client which has the vnet peering APIs, as auto-gen'd from the REST model, available in their full (undocumented) "glory".

(Note though that anything involving the `.inner()` methods should be considered as a *temporary* fallback workaround until the SDK has a more user-friendly fluent API face on top of the given functionality).

**Comment by yogesh-insta** [comment]
Thanks for the quick response and workaround @martinsawicki!

**Comment by martinsawicki** [comment]
now addressed with https://github.com/Azure/azure-sdk-for-java/pull/1894

**Comment by martinsawicki** [comment]
done for v1.3
