### ISSUE TITLE
[FEATURE REQ] Add Support for custom logging logic / transforms.

### ISSUE THREAD

**Issue by g2vinay** [Azure/azure-sdk-for-java#11660]
we need to add support for users to specify custom logging logic and the two techniques which can achieve this are:

1. Function based hooks (passed via HttpLogOptions) 
2. Ability to Extend HttpLoggingPolicy / AbstractBase and override logRequest and logResponse methods.

Option 1 is preferred currently (given the requests and use cases we've been seeing from the users.)

**Comment by alzimmermsft** [comment]
Appears to be a duplicate of #11477.

**Comment by alzimmermsft** [comment]
Closing as duplicate of #11477
