### ISSUE TITLE
Connect to storage account using Key Vault 

### ISSUE THREAD

**Issue by impothnis** [Azure/azure-sdk-for-java#11671]
**Query/Question**
How to create a Blob client using key Vault 

***Why is this not a Bug or a feature Request?***
we are looking if it is already there or not as it should have been supported as per documentation

Our customers are not ready to share Access key for us to create a blob client. We are looking for Key Vault where user will create a secret for access key. But I am unable to find any resource in Java on how to connect to blob container using it. 

please guide me to right resource where I can access the the secret value and authenticate user using Client ID and Secret

**Comment by joshfree** [comment]
@vcolin7 could you please assist?

**Comment by vcolin7** [comment]
There are multiple ways to authenticate and connect to a [Storage Account](https://github.com/Azure/azure-sdk-for-java/blob/master/sdk/storage/azure-storage-blob/README.md#create-a-blobserviceclient), specific [Container](https://github.com/Azure/azure-sdk-for-java/blob/master/sdk/storage/azure-storage-blob/README.md#create-a-blobcontainerclient) or [Blob](https://github.com/Azure/azure-sdk-for-java/blob/master/sdk/storage/azure-storage-blob/README.md#create-a-blobclient):

- [SAS (Shared Access Signature) token](https://docs.microsoft.com/azure/storage/common/storage-dotnet-shared-access-signature-part-1):

    ```java
    BlobServiceClient blobServiceClient = new BlobServiceClientBuilder()
        .endpoint("<your-storage-account-url>")
        .sasToken("<your-sas-token>")
        .buildClient();
    ```

    To generate a SAS Token you can use the [Azure CLI](https://github.com/Azure/azure-sdk-for-java/blob/master/sdk/storage/azure-storage-blob/README.md#sas-token) or the Azure Portal.

- Storage Account's access key:
    ```java
    StorageSharedKeyCredential credential = new StorageSharedKeyCredential("<account-name>", "<account-key>");

    BlobServiceClient blobServiceClient = new BlobServiceClientBuilder()
        .endpoint("<your-storage-account-url>")
        .credential(credential)
        .buildClient();
    ```

- Use the [Azure Identity library](https://github.com/Azure/azure-sdk-for-java/blob/master/sdk/storage/azure-storage-blob/README.md#authenticate-with-azure-identity):
    ```java
    BlobServiceClient blobServiceClient = new BlobServiceClientBuilder()
        .endpoint("<your-storage-account-url>")
        .credential(new DefaultAzureCredentialBuilder().build())
        .buildClient();
    ```

	Keep in mind that for this method to work you would need to include some environment variables like AZURE_CLIENT_ID, AZURE_CLIENT_SECRET & AZURE_TENANT_ID. More details about this [here](https://github.com/Azure/azure-sdk-for-java/tree/master/sdk/keyvault/azure-security-keyvault-secrets#createget-credentials).

For more info on how to get different credential types please refer to [this link](https://github.com/Azure/azure-sdk-for-java/blob/master/sdk/storage/azure-storage-blob/README.md#get-credentials).

Now, as for [getting a secret](https://github.com/Azure/azure-sdk-for-java/tree/master/sdk/keyvault/azure-security-keyvault-secrets#retrieve-a-secret) using a SecretClient, you can use something like the following::

```java
SecretClient client = new SecretClientBuilder()
    .vaultUrl(<your-vault-url>)
    .credential(new DefaultAzureCredentialBuilder().build())
    .buildClient();

KeyVaultSecret secret = secretClient.getSecret("<secret-name>");
```

The simplest way to authenticate to an Azure Key Vault, in my opinion, is by [following the same steps for using the Azure Identity library mentioned above](https://github.com/Azure/azure-sdk-for-java/tree/master/sdk/keyvault/azure-security-keyvault-secrets#authenticate-the-client).

Here are [some more resources](https://github.com/Azure/azure-sdk-for-java/tree/master/sdk/keyvault#sample-code) about additional ways to authenticate to an Azure Key Vault.

**Comment by vcolin7** [comment]
I will be closing this issue for the time being but feel free to let me know if you have any further questions or if there's something I might have misunderstood about your query :)
