### ISSUE TITLE
Support for deleting resources in deployments.

### ISSUE THREAD

**Issue by sam3984** [Azure/azure-sdk-for-java#1167]
Azure azure = Azure.configure()
               .withLogLevel(HttpLoggingInterceptor.Level.NONE)
               .authenticate(appTokenCreds)
               .withSubscription(subscriptionId);

We do have delete() call for deployments but it does not delete the actual resources. Is there any support in Azure ARM to delete all resources within deployment instead of deleting individual resources.
azure.deployments().delete() does not work as it is not deleting the resources.

Individual delete calls on actual resource are working "azure.virtualMachines().delete()." but how to enumerate exact list of removable resources in a deployment and find their dependencies ?

We are looking for some general delete call which we can invoke on specific deployments rather than deleting whole resource group.

**Comment by martinsawicki** [comment]
Azure offers two choices as far as deletion goes:
- delete the resource group
- delete the individual resources
There isn't a way to "undo" a specific ARM template.
There is a good discussion of this issue on the Python side: https://github.com/Azure/azure-sdk-for-python/issues/585
