### ISSUE TITLE
[text analytics] update readme

### ISSUE THREAD

**Issue by iscai-msft** [Azure/azure-sdk-for-java#11752]
- [x] Consider renaming "Client" section in Key Concepts to "TextAnalyticsClient"
- [x] Consider adding a key concept on DocumentErrorHandling (python's is [here](https://github.com/Azure/azure-sdk-for-python/blob/master/sdk/textanalytics/azure-ai-textanalytics/README.md#document-error-handling), but java's would tell the user to check the .errors of batch)
- [x] Make sample links in readme absolute, not relative. This is potentially causing problems when being uploaded to docs.microsoft.com

cc @czubair

**Comment by samvaity** [comment]
@mssfang Could this be a part of : #11754?

**Comment by mssfang** [comment]
(1) change to `Text Analytics client` since java has `TextAnalyticClient` and `TextAnalyticsAsyncClient`
(2) this info included in our `Result value` section.
(3) other Java GA SDKs are stay with relative links. I don't think TA want to be outstanding in the Java repo.
