### ISSUE TITLE
Cross language test scenario consistency

### ISSUE THREAD

**Issue by samvaity** [Azure/azure-sdk-for-java#11774]
Get testing scenario parity cross languages for FormRecognizer.
Make sure to cross-check testing scenarios from here : https://microsoft.sharepoint.com/:x:/t/AzureDeveloperExperience/ERwfsXEb42RJt1WPS1bBUwUBnvwdAtJPAGDhekRAxwoCIw

edit:
Also, consider updating the test framework to not poll when running in PLAYBACK mode.

**Comment by mssfang** [comment]
fixed in #12400
