### ISSUE TITLE
Make AzureJacksonMapperAdapter injectable and implement an interface for RestClient

### ISSUE THREAD

**Issue by aidanmorgan** [Azure/azure-sdk-for-java#1179]
I am trying to use the Azure Data Lake library from a Storm cluster and am repeatably running into issues with the Jackson version that is used in the AzureSDK not being compatible with the version that is provided in Storm.

It would be much easier if the use of jackson was injected via an interface, allowing me to change the implementation of the serialization/deserialization to avoid this problem.

**Comment by aidanmorgan** [comment]
I have previously had the same issue around Jackson dependencies and storm when using the swagger codegen (due to it's dependencies on retrofit/okhttp).

**Comment by jianghaolu** [comment]
Which version is being used in Storm? I can look into the methods that are potentially incompatible that see if I can use alternatives.

We are actually taking a dependency on retrofit and jackson version is defined by them.

**Comment by aidanmorgan** [comment]
According to mvn central the dependency for Storm is on 2.3.1 for Jackson.

I do know that Retrofit allows the mapper to be pluggable, is it possible to expose this through the Azure API as well?

The line that appears to be causing the problem is in the Jackson Mapper Adapter here:

`        mapper.setVisibility(mapper.getSerializationConfig().getDefaultVisibilityChecker().withFieldVisibility(Visibility.ANY).withSetterVisibility(Visibility.NONE).withGetterVisibility(Visibility.NONE).withIsGetterVisibility(Visibility.NONE));
`

**Comment by aidanmorgan** [comment]
I think the other challenge is that the AzureJacksonMapper is initialised in the build() method of the Buildable class, if it was possible to make this injectable then I would be able to work around the issue I am having.

**Comment by praries880** [comment]
@jianghaolu is this still an issue?

**Comment by yungezz** [comment]
hi @weidongxu-microsoft could you pls have a look? thanks.
