### ISSUE TITLE
Get label of Region

### ISSUE THREAD

**Issue by selevt** [Azure/azure-sdk-for-java#1180]
For regions it's possible to get back the name with the toString, but the label is not accessible. Would be nice to be able to get that, when only the region name / object is available.

**Comment by jianghaolu** [comment]
Seems like a low hanging fruit. Will add.

**Comment by davidbairdala** [comment]
I worked around this with the following:

`    private static String extractLabel(Region region) {
        String label = region.toString()
        try {
            Field f = region.getClass().getDeclaredField("label")
            f.setAccessible(true)
            label = (String) f.get(region)
        } catch (Exception ex) {
            log.warn("Failed to extract label from Azure region: ${region.toString()}: ${ex.message}")
        }
        return label
    }
`

**Comment by martinsawicki** [comment]
addressed in upcoming 1.0.0-beta4
