### ISSUE TITLE
 Address Feedback from JS/Java User Studies

### ISSUE THREAD

**Issue by samvaity** [Azure/azure-sdk-for-java#11888]
Java and Js UX study feedback

- [x] Add readme code snippet pointers for statements in key concepts.
uses it extensively and users have not seen/known how to use it before this in other SDK's?
- [ ] Should consider having a  helper method to shortcut `getFields().get("FieldName")` - _rather than helper method, we will leave it as is and update unlabeled samples to show efficient way of getting fields by name._
- [ ] For Copy, hard to find resource id and region. Add docstrings to clarify this more. 
_Add in the documentation how/where to get the region for Copy and the list of available regions_
- [x] Consider adding a mix of fromUrl and stream overload code snippets in the main readme.
- [x] Add documentation about how to create the training blob and the type of files and etc. 
_Add link to service documentation for creating training data storage containers._ 
- [x] getText and getTextContent – _clarify ref docs_  
- [x] Make sure sync and async links are clearly represented in samples list - _All language to cross-check_ 
- [x] Add to documentation description about what SAS Url is – _Add links to service docs about training_ 

To follow up:
- [ ] Should consider having a `getRow()` or similar not natural to have a `getCells()` and diving into the cell information to find the row it belongs to. Also, it could use a better data structure here. [constant pain point to get to the field] - _Follow up (Mariana/Anne) Table indexer issue - https://github.com/Azure/azure-sdk-for-net/issues/9975_ **NOT IN PREVIEW 4**
- [ ] 2/5 users attempted and were hopeful that they could pass in the local File URL for the `fromUrl` and that should have worked. Circling back to if we should consider adding an overload that takes in a file input.  - _(Waiting to know Johan's thoughts, Issue - https://github.com/Azure/azure-sdk-for-java/issues/12402#issue-643410189)_ 
- [ ] Add documentation to clarify getFieldValue() and getValueText() - 
_Deferred discussion to Architecture board. Consider if renaming fields to `labelData` or `labelTextInformation` should help ?_

Only Java
- [x] [Java] Add a FormTraining client building example in the README  
- [x] [Only Java] Rename fieldValue to Value
- [x] [Java] Nullable params to be called out in documentation
- [ ] [Java] Models like `BoundingBox` and `Points` to have `toString()` override?
- [ ] [Java] Consider updating samples to better show the polling mechanism as this library
- [x] [Java] Rename `getFieldMap()` to `getFields()` in CustomFormSubmodel [including documentation] 
- [x] [Java] requires `length` for inputstream overloads , not required for other languages. - Client side optimization in Java

**Comment by kristapratico** [comment]
- Confusion by several users that `getLabelText()` and `getValueText()` would return text value and not object. Consider renaming - Python uses `label_data` and `value_data` but open to other suggestions. Perhaps this can be solved by a toString() method?
- Users do not expect the model to be created if the entire operation fails. Follow up with service team to understand this
- One user asked for more clarity on error conditions and exceptions to be clearly explained in docs
- One user said "no rhyme or reason" for order of fields and didn't understand why fields were ordered the way they were. Do we need to pre-sort fields, or is this just how the service returns fields?

**Comment by annelo-msft** [comment]
for 
> Should consider having a getRow() or similar not natural to have a getCells() and diving into the cell information to find the row it belongs to. Also, could use a better data structure here. [constant pain point to get to the field]

We have [this work item](https://github.com/azure/azure-sdk-for-net/issues/9975) in .NET.  Not sure what would be idiomatic to other languages.

**Comment by annelo-msft** [comment]
> 2/5 users attempted and were hopeful that they could pass in the local File URL for the fromUrl and that should have worked. Circling back to if we should consider adding an overload that takes in a file input.

There's a thread on this on our FR Teams channel - @johanste  shared his perspective there.

**Comment by johanste** [comment]
A local file URL is ambiguous. Is it relative to the server or relative to the client? This is particularly ambiguous in the context of containers (again, relative to the container or relative to the client). Any alternate solution we would propose will have to make it very clear as to what happens here - and it is an absolute requirement that we can tell the service the location of the document rather than trying to get the document from the client and put it in the request body itself.

**Comment by samvaity** [comment]
>and it is an absolute requirement that we can tell the service the location of the document rather than trying to get the document from the client and put it in the request body itself.

@johanste To clarify on the above statement isn't the `InputStream` overload doing the exact same thing except that the user is responsible for providing the stream but the client still puts it in the request body and sends it to the service.
