### ISSUE TITLE
EventHubs macOS - Java 8 test failure 

### ISSUE THREAD

**Issue by joshfree** [Azure/azure-sdk-for-java#11884]
Dashboard: https://dev.azure.com/azure-sdk/internal/internal%20Team/_dashboards/dashboard/d2224fd5-beee-47a0-90df-b24b73fdc8e7

Direct Link: https://dev.azure.com/azure-sdk/internal/_build/results?buildId=413960&view=logs&j=27eb5d14-7214-5d9c-6bac-653552bd18b3&t=a005fe46-c79b-5f07-8646-28339b1448ad&l=9418

> 2020-06-05 15:16 [parallel-4] [INFO] com.azure.messaging.eventhubs.PartitionBasedLoadBalancerTest - Processing event: Event Hub name = test-event-hub; consumer group name = test-consumer-group; partition id = 3; sequence number = 13
> 2020-06-05 15:16 [parallel-4] [INFO] com.azure.messaging.eventhubs.SampleCheckpointStore - Updated checkpoint for partition 3 with sequence number 13
> 2020-06-05 15:16 [parallel-4] [INFO] com
> .azure.messaging.eventhubs.PartitionBasedLoadBalancerTest - Processing event: Event Hub name = test-event-hub; consumer group name = test-consumer-group; partition id = 2; sequence number = 13
> 2020-06-05 15:16 [parallel-4] [INFO] com.azure.messaging.eventhubs.SampleCheckpointStore - Updated checkpoint for partition 2 with sequence number 13
> [ERROR] Failures: 
> **[ERROR]   EventHubConsumerAsyncClientIntegrationTest.receivesMultiplePartitions:450 Expected messages to be received from all partitions. There are: 1 ==> expected: <true> but was: <false>
> [ERROR] Tests run: 270, Failures: 1, Errors: 0, Skipped: 10**
> [ERROR] Failed to execute goal org.apache.maven.plugins:maven-surefire-plugin:3.0.0-M3:test (default-test) on project azure-messaging-eventhubs: There are test failures.
> [ERROR] 
> [ERROR] Please refer to /Users/runner/runners/2.169.1/work/1/s/sdk/eventhubs/azure-messaging-eventhubs/target/surefire-reports for the individual test results.
> [ERROR] Please refer to dump files (if any exist) [date].dump, [date]-jvmRun[N].dump and [date].dumpstream.
> [ERROR] -> [Help 1]
> [ERROR] 
> [ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
> [ERROR] Re-run Maven using the -X switch to enable full debug logging.
> [ERROR] 
> [ERROR] For more information about the errors and possible solutions, please read the following articles:
> [ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException
> The process '/usr/local/bin/mvn' failed with exit code 1
> Could not retrieve code analysis results - Maven run failed.
> ##[error]Build failed.
> Finishing: macOS - Java 8

**Comment by conniey** [comment]
Seems fixed in recent builds. I think a larger issue is to understand why it periodically fails (ie. underlying flakiness in azure-core-amqp?)
