### ISSUE TITLE
When using "az login" to log in, the web page give a "xxx@fit2cloud.partner.onmschina.cn" isn't in our system 

### ISSUE THREAD

**Issue by baochunliu** [Azure/azure-sdk-for-java#1197]
When I want to use azure-sdk-for-java 1.0.0-beta3 to create a virtual machine, I need to create a Service Principal in Azure by following https://github.com/Azure/azure-sdk-for-java/blob/master/AUTH.md. 
1. Azure CLI is downloaded, and run "az login".
2. Follow the order from "az login", I open "https://aka.ms/devicelogin" and input the code to authenticate. 
3.Then the web page is directed to https://login.microsoftonline.com/common/oauth2/deviceauth, I input my account like "zhimin@fit2cloud.partner.onmschina.cn", and password. (I make sure the account and password are correct. For I can login www.azure.cn with the accunt and password.)  But the page give me a hint "zhimin@fit2cloud.partner.onmschina.cn isn't in our system ". 

So I do not know how to solve this issue.

**Comment by jianghaolu** [comment]
Hi @baochunliu 
Azure CLI 2.0 doesn't support logging with environment settings right now. It will be supported in a few weeks. You can use Azure Xplat CLI (Node.JS based instead of Python based) to do similar things:

1. Make sure you install Node.JS 4+
2. Run `npm install azure-cli`.
3. Login in the same way, except, with `--environment` parameter.
4. After you logged in, run `azure ad sp create -n myspn -p MyPassWord!123`. This will give you a service principal. Copy out the object ID of the service principal.
5. Run `azure role assignment create --objectId &lt;Object ID from previous command&gt; --roleName Owner --scope "/subscriptions/&lt;subscription Guid&gt;"

This will give you a service principal. Thanks.

**Comment by baochunliu** [comment]
Hi @jianghaolu 
  Thanks for your help. 
  After consulting China Azure Support, we can past the compute-java-manage-vm test cases. 
  The steps are:
1.azure account clear
2.azure login -u <account> -p <password> -e AzureChinaCloud
3. Switch to ARM mode.
azure config mode arm
4.Create an application  
azure ad app create -n create-for-rbac -p Fit2Cloud* -m 'http://localhost/index.html'  -i http://localhost/index.html 
5.Create a service principal for the application
azure ad sp create -a 264c12a9-0643-4bea-87f7-7a4027b0325d 
  ###-a is the application id, which is get from the step 4.
6.Authorize the principal in step 5. Assign a role to the principal. 
azure role assignment create --objectId 42d447ff-7539-4325-9fb8-0f4c60a8f304 --roleName Contributor
  ### the --objectID is the ObjectID of step 5. 
7.Get the subscription id and the tenant id. 
azure account  show -s <your sub name>
8.
azure provider register Microsoft.Compute
azure provider register Microsoft.Network
azure provider register Microsoft.Storage

9.Execute the test cases
export AZURE_AUTH_LOCATION=/Users/brent/azure/brent_china.properties
cd compute-java-manage-vm/
mvn clean compile exec:java

############
subscription=xxxxxxxx
client=xxxxxxxxxxxx
key=xxxxxxxxxx
tenant=xxxxxxxxxxxxxx
managementURI=https\://management.core.chinacloudapi.cn/
baseURL=https\://management.chinacloudapi.cn/
authURL=https\://login.chinacloudapi.cn/
graphURL=https\://graph.chinacloudapi.cn/

**Comment by jianghaolu** [comment]
Cool! Please continue to provide feedback as it will be greatly appreciated.

**Comment by baochunliu** [comment]
Hi,
  I run into an issue, when I use the azure-sdk-java 1.0.0-beta3.
  After :
Azure azure = Azure
.configure()
    .withLogLevel(HttpLoggingInterceptor.Level.NONE)
    .authenticate(credFile)
    .withDefaultSubscription();

1.my account is from CHINA.
2.I want to know which LOCATIONS or Region I can choose by SDK JAVA API.
For example in China, there are two regions chinaeat and chinanorth, how
can I get chinaeast and chinanorth by SDK api?

Thanks,
Brent



2016-10-18 11:01 GMT+08:00 Jianghao Lu <notifications@github.com>:
