### ISSUE TITLE
[BUG] Need better documentation on how to add new module

### ISSUE THREAD

**Issue by JianpingChen** [Azure/azure-sdk-for-java#11998]
**Describe the bug**
Documentation in the template folder of the SDK didn't provide enough information for creating a new module

**To Reproduce**
Try to create a new module based on the template folder and add to build pipeline. It is very easy to miss some necessary steps

**Expected behavior**
Ideally, the template should contain enough information to get people started. Currently, it doesn't have a module-info.java to remind people a module definition is required.

The steps for adding a new module properly should clearly specify the steps. The details probably better belong to a wiki page, e.g. https://github.com/Azure/azure-sdk-for-java/wiki/Adding-a-Module.

To me, the first step is to create the package group folder and add and merge ci.yml file to start a build pipeline before anything else.

Step 2 should include

1. Create required folder structure, add the pom files, CHANGELOG.md, and README.md
2. Add some trivial code to have something to build. Copy the code from template folder is just fine. But the template code folder should contain module-info.java in the correct folder. Be noticed that the folder structure should match package naming.
3. Modify pom.xml in the root to add the new module folder
4. Modify eng/versioning/version_client.txt to include the new module
5. Modify eng/jacoco-test-coverage/pom.xml to include the new module if test coverage is needed

README.md in the template is missing a section "## Contributing".

**Setup (please complete the following information):**
 - OS: [e.g. iOS] Windows
 - IDE : [e.g. IntelliJ] Microsoft Code
 - Version of the Library used: 1.6.0

**Comment by joshfree** [comment]
@alzimmermsft please add this to your azure-core Iron semester epic
