### ISSUE TITLE
Block Integration Test - In Spring Integration Test run in CI pipeline

### ISSUE THREAD

**Issue by hemanttanwar** [Azure/azure-sdk-for-java#12000]
**Spring Integration Test run in CI pipeline**

**Problem** : For most of the SDK, The CI pipeline can run integration test because these test can run using PLAY_BACK, where it replay pre recorded service HTTP responses and azure resources are not needed.

But the integration test for Spring are little bit different in following way for example.

1. For the key vault integration tests, IT test create an app service first 
2. And then deploy jar. 
3. Restart the app service and visit the endpoint . 

This can not be achieved using current PLAY_BACK of HTTP request.

**Ask** : Need some way to block the test execution then in CI pipeline

**Comment by hemanttanwar** [comment]
@saragluna @JimSuplizio @mitchdenny @jialindai

**Comment by kurtzeborn** [comment]
@hemanttanwar, why would we try to solve this in a pipeline?  This seems like something the test code should block on until the resources are ready and available to run against.

We have also standardized the rest of our live tests using a resource provisioning script which leverages ARM templates.  Are we not using that there?

CC: @danieljurek

**Comment by JimSuplizio** [comment]
@hemanttanwar is issue this still necessary? The [PR](https://github.com/Azure/azure-sdk-for-java/pull/11796) that added spring integration tests has them disabled for spring - ci builds. This was done by disabling the tests by default through a variable in added tot he POM files, `<skipSpringITs>true</skipSpringITs>`, which is set as part of their maven options in [sdk/spring/tests.yml](https://github.com/Azure/azure-sdk-for-java/blob/master/sdk/spring/tests.yml#L9)

**Comment by hemanttanwar** [comment]
Yes this problem is solved as you mentioned above, so closing it.
