### ISSUE TITLE
Enable test against distinct patch spring dependencies

### ISSUE THREAD

**Issue by hemanttanwar** [Azure/azure-sdk-for-java#12020]
**Requirement**
Capability to test against variable sets of patch spring dependencies (e.g. Spring Boot 2.3.0 vs. Spring Boot 2.3.1 to determine compatibility ).

**What to consider**:
Having more test running in pipeline, will require more Azure resources and there is quota against each language which is limited.

**Some options**
1. Consider Monthly or weekly run of these additional test.

**Spring versioning scheme** : Spring uses MAJOR.MINOR.PATCH[-MODIFIER] versioning scheme. More about it here https://spring.io/blog/2020/04/30/updates-to-spring-versions 

There is similar work done in JS repo to enable min-max testing https://github.com/Azure/azure-sdk-for-js/pull/8919

**Comment by hemanttanwar** [comment]
@jialindai @JimSuplizio @mitchdenny @JonathanGiles @saragluna

**Comment by kurtzeborn** [comment]
There is no specific quota for machine usage in pipelines.  We just expect pipelines to not be wasteful and overuse machines unnecessarily.  We've also implemented sparese matricies to limit the number of machines used by broad test pipelines.  The bottom line here is don't let some percieved quota stand in the way of you getting these tests running the way you want.  Get it working, and then before we turn it on to run daily, we should review the pipeline together to determine if we can reduce the number of execution legs or run it less often (weekly or monthly).

**Comment by jialindai** [comment]
In near future, we may have one Spring module support multiple minor versions, for example, support:
- Spring boot 2.2.x
- Spring boot 2.3.x

In each minor Spring boot version, there could be several patch versions (sometimes up to 10).

One possible approach is to test for lowest and highest patch version on each supported minor version.

**Comment by chenrujun** [comment]
> support multiple minor versions

I'll do it after first release in this repo.

**Comment by hemanttanwar** [comment]
@jialindai  Please provide few combination of version numbers which need to be tested. For example  "Spring 2.2 and Linux and java 11"
			
Data point : Spring team can take ownership to maintain a file in repo which note list of spring version and that needs to be tested.

**Comment by chenrujun** [comment]
Now our integration test supports:
 - spring-boot-2.3.x and spring-boot-2.2.x
 - Java 8 and Java 11
 - Windows, Linux and MacOS.
