### ISSUE TITLE
PartitionPumpManager seems to not be able to clean-up effectively

### ISSUE THREAD

**Issue by Duncol** [Azure/azure-sdk-for-java#12035]
**Describe the bug**
PartitionPumpManager seems to not be able to clean-up effectively

**To Reproduce**
- Preload hub with events (preferably 1000+)
- Read the events using azure-messaging-eventhubs
- Block the consumer thread for 60+ seconds (I've used SoapUI with sleep(70000) to match the env behaviour as much as possible)
- Let it consume
- See some ERRORs/WARNings from ReactorReceiver, but no cleanup executed (?)

***Code Snippet***
```java
eventHubConsumer.receiveFromPartition(claimedOwnership.getPartitionId(), startFromEventPosition, receiveOptions).windowTimeout(this.maxBatchSize, this.maxWaitTime).flatMap(Flux::collectList).subscribe((partitionEventBatch) -> {
                        this.processEvents(partitionContext, partitionProcessor, eventHubConsumer, partitionEventBatch);
                    }, (ex) -> {
                        this.handleError(claimedOwnership, eventHubConsumer, partitionProcessor, ex, partitionContext);
                    }, () -> {
                        partitionProcessor.close(new CloseContext(partitionContext, CloseReason.EVENT_PROCESSOR_SHUTDOWN));
                        this.cleanup(claimedOwnership, eventHubConsumer);
                    });
```
**Expected behavior**
```java
this.cleanup(claimedOwnership, eventHubConsumer);
```
 to be excecuted (no logs present; locally debugger omitts it as well, no matter if error)

**Setup (please complete the following information):**
Regarding service, that uses the library:
 - OS: Alpine Linux 3.8 (docker container in the cloud) / Windows 10 1709 (localhost)
 - IDE : e.g. IntelliJ 2020.1
 - Version of the Library used: v5.1.0

**Additional context**
Memory leak, which seems to come along with PartitionPumpManager errors.
EDIT:
Heap dump told us, that:
```
637 instances of "org.apache.activemq.artemis.core.protocol.openwire.OpenWireConnection", loaded by "java.net.URLClassLoader @ 0x80003f68" occupy 1,805,456,792 (96.77%) bytes.
```
I saw, that there is some RetryUtil, which does four retries. Perhaps it is related?

**Comment by Duncol** [comment]
> Can you please let us know why you are blocking the consumer for 60+ seconds?
To mitigate, as close as possible, the cloud environment (sometimes, simply there are no events in a 60s time-frame)

**Comment by srnagar** [comment]
@Duncol Do you still see this issue? Could you please provide a reproducible sample and include any relevant logs to help us investigate this issue?

**Comment by srnagar** [comment]
Closing this as there are no updates. Please reopen if you are still seeing this issue.
