### ISSUE TITLE
Support 'Delete' eviction policy for Azure Spot Standalone VMs

### ISSUE THREAD

**Issue by rakeshakkera** [Azure/azure-sdk-for-java#12031]
**Is your feature request related to a problem? Please describe.**
Currently Azure Spot standalone VMs only support eviction policy of 'Deallocate'. We have made changes in the CRP service for standalone Spot VMs to support 'Delete' eviction policy as well. Changes need to be made in JAVA SDK should to support this.

**Describe the solution you'd like**
Currently JAVA SDK blocks choosing 'Delete' eviction policy for Standalone Spot VMs. Changes need to be made to support this. Here is the link to the swagger PR for this change: https://github.com/Azure/azure-rest-api-specs/pull/9743

**Describe alternatives you've considered**
NA

**Additional context**
Swagger PR: https://github.com/Azure/azure-rest-api-specs/pull/9743

**Information Checklist**
Kindly make sure that you have added all the following information above and checkoff the required fields otherwise we will treat the issuer as an incomplete report
- [ ] Description Added
- [ ] Expected solution specified

**Comment by xccc-msft** [comment]
@rakeshakkera Thanks for the update. I have added [new commit](https://github.com/Azure/azure-libraries-for-java/pull/1199/commits/8a4e0efa311688bd9bfde5c166fe02045c5a23da) with the mentioned changes.

**Comment by xccc-msft** [comment]
Close this as supported.
