### ISSUE TITLE
Need an API to delete blob files

### ISSUE THREAD

**Issue by Patzolino** [Azure/azure-sdk-for-java#1207]
Hello,

We found that in some old Azure libraries, it's been possible to delete blob files. In the latest SDK, however, there is absolutely no way to achieve that. Since the disks cost pretty much money and even though the VM is deleted, they are left in the subscription and can drive your account to bankruptcy. That's why we need a mechanism to delete those files once the VM has been deleted.
The perfect API would be to pass the disk URI as input parameter as this is all we have in the context of a VM. I know we can extract Storage Account name from that URI, but since there is no API that returns StorageAccount by a given name, we are still facing some difficulties in that way.

Thanks,
Plamen Dimitrov, 
Member of Technical Staff, VMware Inc.

**Comment by jianghaolu** [comment]
Hi @Patzolino I think you may be interested in this repo: https://github.com/azure/azure-storage-java.

**Comment by Patzolino** [comment]
Hi @jianghaolu,

Thank you for your response. We are aware of that library and we are currently using it as a workaround. What we don't like in that approach are the following cons:
 - In order to use this library, we need to maintain another client, which uses HTTPS connection with its own authentication and certificate stuff
 - In order to be able to call this library's "deleteBlob" method, we need to load the StorageAccount (where the blob resides) in order to get the AccessKeys. Since the only thing we have is the StorageAccount's name and since there is no getStorageAccountByName API in your SDK (something that I consider as a mandatory, moreover that the StorageAccount name is unique throughout the whole Azure portal, so is good enough to be used as identifier), we are forced to go through all resource groups and lookup the StorageAccount's name in each group. Once we find it, we can get its AccessKeys in order to create the credentials needed by 'deleteBlob' method.
 - We introduce one more library that we refer in our codebase.

We have done that, since we have no other choice at that moment, but you can imagine how bad performing our code will be, when we need to go through hundreds of ResourceGroups in order to lookup the StorageAccount that is referred in the blob URI we want to process.

I hope that this shed more light on the problem we face. Let me know if you have more questions or you need more details about our use case.

Regards,
Plamen Dimitrov

**Comment by praries880** [comment]
@alzimmermsft can you take a look at this and triage it appropriately?

**Comment by alzimmermsft** [comment]
Hi @Patzolino,

You may be interested in this repository: https://github.com/Azure/azure-sdk-for-java/tree/master/storage/client/blob 

The reference repository is the latest client SDKs, still under preview, for working with the Storage service. Their aim is to make working with Azure service easier and more fluent and hopefully they should address some of your concerns mentioned previously.

Best Regards,
Alan Zimmer

**Comment by zhusijia26** [comment]
Close this issue since answer provided. Please reopen if there is any question.
