### ISSUE TITLE
Beta3: azure.virtualMachines().list() java.lang.RuntimeException: com.fasterxml.jackson.core.JsonParseException: Unexpected character 

### ISSUE THREAD

**Issue by masarlabs** [Azure/azure-sdk-for-java#1208]
Hi,
with beta3 the call
   azure.virtualMachines().list()
gives the exception
   java.lang.RuntimeException: com.fasterxml.jackson.core.JsonParseException: Unexpected character ('<' (code 60))

With debug enabled I see the two query
   INFO: --> GET https://management.azure.com/subscriptions/9bf80712-ea01-4ee9-b119-821915e971d8/providers/Microsoft.Compute/virtualMachines?api-version=2016-03-30 http/1.1
   INFO: --> GET https://management.azure.com/subscriptions/9bf80712-ea01-4ee9-b119-821915e971d8/providers/Microsoft.Compute/virtualMachines%3Fapi-version=2016-03-30&$skiptoken=7bf70969-6862-421b-8d35-24416494e8ba!/Subscriptions/9bf80712-ea01-4ee9-b119-821915e971d8/ResourceGroups/WFDVGAZ-RG/VMs/WFDVGAZGLU11 http/1.1

The second one seems wrong, it incorrectly escapes '?' to '%3F'

With Beta2 it works as expected:
   INFO: --> GET https://management.azure.com/subscriptions/9bf80712-ea01-4ee9-b119-821915e971d8/providers/Microsoft.Compute/virtualMachines?api-version=2015-06-15 http/1.1
   INFO: --> GET https://management.azure.com/subscriptions/9bf80712-ea01-4ee9-b119-821915e971d8/providers/Microsoft.Compute/virtualMachines?api-version=2015-06-15&$skiptoken=bc1c48ac-66e3-43f7-b239-345cba1bedbf!/Subscriptions/9bf80712-ea01-4ee9-b119-821915e971d8/ResourceGroups/WFDVGAZ-RG/VMs/WFDVGAZGLU11 http/1.1
   INFO: --> GET https://management.azure.com/subscriptions/9bf80712-ea01-4ee9-b119-821915e971d8/providers/Microsoft.Compute/virtualMachines
?api-version=2015-06-15&$skiptoken=bc1c48ac-66e3-43f7-b239-345cba1bedbf!/Subscriptions/9bf80712-ea01-4ee9-b119-821915e971d8/ResourceGroups/WFPPWPS-RG/VMs/WFPPWPSAPF11 http/1.1
   ...

**Comment by jianghaolu** [comment]
Thanks @masarlabs this is a known bug, will fix this in the next couple weeks

**Comment by masarlabs** [comment]
Hi,
the problem is still present in BETA4:

INFO: <-- 400 Bad Request https://management.azure.com/subscriptions/9bf80712-ea01-4ee9-b119-821915e971d8/providers/Microsoft.Compute/virtualMachines%3Fapi-version=2016-03-30&$skiptoken=d8b6b639-04ce-4eb8-8b6d-352e5bb5317e!/Subscriptions/9bf80712-ea01-4ee9-b119-821915e971d8/ResourceGroups/WFCXSYTMLR-RG/VMs/WFCXSYTMLR02 (132ms)

**Comment by masarlabs** [comment]
Problem fixed in 4.1.

Thanks
