### ISSUE TITLE
[BUG] Investigate sync retries on timeout

### ISSUE THREAD

**Issue by rickle-msft** [Azure/azure-sdk-for-java#12106]
Currently I don't think timeouts are retried in sync for two reasons:

- Our retry policy looks for TimeoutException, which is what gets thrown when you call `.timeout()`, but calling `.block(timeout)` throws an IllegalStateException.
- I'm not sure that the IllegalStateException actually goes up the reactive-stream stack through the onError operators anyway.

A couple ideas to experiment with:
- Change `blockWithOptionalTimeout` to `operation.timeout(Duration).block()` to use the async timeout mechanism
- Passing the timeout duration using Context into the retry policy and setting the timeout there. This will ensure the timeout is bound where we know retry is guaranteed to happen and removes the code path of block with timeout

**Comment by alzimmermsft** [comment]
Adding the `common` tag as the option for passing per method call timeouts through the pipeline using `Context` could apply to all libraries.

@JonathanGiles @srnagar
