### ISSUE TITLE
Mixed up method names for get/setResponseContinuationTokenLimitInKb?

### ISSUE THREAD

**Issue by armaansood** [Azure/azure-sdk-for-java#12115]
I'm not 100% sure if this is a bug, but based on a quick glance it seems that these two methods are mixed up: 

![image](https://user-images.githubusercontent.com/15119386/84447808-ed07ac00-abfd-11ea-98b3-63ba21c2216a.png)

I might be missing something, but why does setResponseContinuationTokenLimitInKb get the response continuation token?

**Comment by kushagraThapar** [comment]
@armaansood - this is definitely a mix up issue. 
Great find. I will work on this to get it fixed.

**Comment by kushagraThapar** [comment]
This is done and will be out in next release.
