### ISSUE TITLE
AccessPolicyImpl.forServicePrincipal(String) parameter name is misleading

### ISSUE THREAD

**Issue by milismsft** [Azure/azure-sdk-for-java#1215]
The current name for the parameter is "servicePrincipalName" but in fact this is the service principal's clientId value.

**Comment by jianghaolu** [comment]
Fix this after Graph RBAC is implemented.

**Comment by martinsawicki** [comment]
@jianghaolu can we address this for v1.2 if still relevant?

**Comment by jianghaolu** [comment]
This is actually by design. client id is one of the two service principal names a service principal has. If this is confusing to customers, they can always call the `forServicePrincipal(ServicePrincipal sp)` overload.
