### ISSUE TITLE
Beta3: Unable to use async methods for resources

### ISSUE THREAD

**Issue by dtretyakov** [Azure/azure-sdk-for-java#1217]
Currently we're unable to use most of async methods from underlining *inner resource implementation.

```
Azure azure = Azure.authenticate(credFile).withDefaultSubscription();
azure.virtualMachines().list()
```

But actually `VirtualMachinesInner` provides lots of *async methods hidden by `VirtualMachinesImpl`.

**Comment by dtretyakov** [comment]
We need a following methods in sdk classes.

**com.microsoft.azure.management.resources**
*SupportsListing#listAsync(ListOperationCallback<T> serviceCallback)*
*GroupableResourcesImpl#getByGroupAsync(String groupName, String name, ServiceCallback<T> serviceCallback)*
*SubscriptionImpl#listLocationsAsync(String subscriptionId, ServiceCallback<List<LocationInner>> serviceCallback)*

**com.microsoft.azure.management.compute**
*VirtualMachineSizesImpl#listByRegionAsync(String regionName, ListOperationCallback<T> serviceCallback)*
*VirtualMachineImpl#startAsync(ServiceCallback<Void> serviceCallback)*
*VirtualMachineImpl#restartAsync(ServiceCallback<Void> serviceCallback)*
*VirtualMachineImpl#stopAsync(ServiceCallback<Void> serviceCallback)*

**Comment by anuchandy** [comment]
Following async methods (that return ServiceFuture and takes callback) are supported 

[VM::startAsync](https://github.com/Azure/azure-sdk-for-java/blob/37a48229a518c585a227908d78cf048cb7a1ed06/azure-mgmt-compute/src/main/java/com/microsoft/azure/management/compute/VirtualMachine.java#L144)

[VM::restartAsync](https://github.com/Azure/azure-sdk-for-java/blob/37a48229a518c585a227908d78cf048cb7a1ed06/azure-mgmt-compute/src/main/java/com/microsoft/azure/management/compute/VirtualMachine.java#L124)

[VM:: stopAsync() a.k.a.s VM::poweroffAsync](https://github.com/Azure/azure-sdk-for-java/blob/37a48229a518c585a227908d78cf048cb7a1ed06/azure-mgmt-compute/src/main/java/com/microsoft/azure/management/compute/VirtualMachine.java#L104)

[GroupableResourcesImpl#getByGroupAsync()](https://github.com/Azure/azure-sdk-for-java/blob/37a48229a518c585a227908d78cf048cb7a1ed06/azure-mgmt-resources/src/main/java/com/microsoft/azure/management/resources/fluentcore/arm/collection/implementation/GroupableResourcesImpl.java#L123)

Support for fluent `list` method that takes call-back is something that needs to be discussed in the team.

```java
SupportsListing#listAsync(ListOperationCallback serviceCallback)
SubscriptionImpl#listLocationsAsync(String subscriptionId, ServiceCallback<List> serviceCallback)
```

**Comment by martinsawicki** [comment]
async is supported as per above, that's the scope of the SDK's coverage for async.
