### ISSUE TITLE
The user, group or application does not have secrets set permission on key vault??

### ISSUE THREAD

**Issue by ajaysethi8789** [Azure/azure-sdk-for-java#12175]
I'm trying to set and get the secret keys on Azure key vault and I'm following the below document to implement the same

https://docs.microsoft.com/en-us/azure/key-vault/secrets/quick-create-java#sample-code

I have followed the complete process mentioned on the above doc but getting the below error while i run the sample code using java to set the secret key on Azure Key vault

**Servlet.service() for servlet [dispatcherServlet] in context with path [] threw exception [Request processing failed; nested exception is com.azure.core.exception.HttpResponseException: Status code 403, "{"error":{"code":"Forbidden","message":"The user, group or application 'appid=;oid=;iss=https://sts.windows.net/tenantid/' does not have secrets set permission on key vault 'kv;location=uksouth'. For help resolving this issue, please see https://go.microsoft.com/fwlink/?linkid=123455","innererror":{"code":"AccessDenied"}}}"] with root cause**

Can anyone help me out with this.

**Comment by joshfree** [comment]
@vcolin7 could you please assist?

**Comment by vcolin7** [comment]
Hi @ajaysethi8789, I ran the code in a test environment I have and encountered no issues. Based on the error message you got, I believe the problem might rely on the configuration for the service principal you are using for this example. Make sure the `--secret-permissions` section of the following command included the `set` permission, as laid out [here](https://docs.microsoft.com/en-us/azure/key-vault/secrets/quick-create-java#give-the-service-principal-access-to-your-key-vault):

`az keyvault set-policy -n <your-unique-keyvault-name> --spn <clientId-of-your-service-principal> --secret-permissions delete get list set --key-permissions create decrypt delete encrypt get list unwrapKey wrapKey`

You can also verify the service principal's permissions on the Azure Portal under {your key-vault-name} > Access Policies.

**Comment by vcolin7** [comment]
Hi @ajaysethi8789, can you kindly make sure the service principal you are trying to use has the correct permissions? Please refer to my previous reply :)
