### ISSUE TITLE
UXStudy - peek should return ServiceBusReceivedMessageContext

### ISSUE THREAD

**Issue by hemanttanwar** [Azure/azure-sdk-for-java#12171]
All the peek API  should return ServiceBusReceivedMessageContext instead of ServiceBusReceivedMessage

**Comment by ramya-rao-a** [comment]
It is not clear to me why peek() or receivedDeferredMessage() should pass in the context. Symmetry between these and the receive apis is not enough reason to tag along other things that make up a context.

cc @conniey, @srnagar, @JonathanGiles

**Comment by hemanttanwar** [comment]
Deemed not necessary. Closing this.
