### ISSUE TITLE
[text analytics] add support for optional string-index-type query param

### ISSUE THREAD

**Issue by iscai-msft** [Azure/azure-sdk-for-java#12173]
support will be added for this on TA v3.0 API

**Comment by mssfang** [comment]
@iscai-msft mind that give an example of it?

**Comment by iscai-msft** [comment]
it's the encoding parameter that they're deploying (going to be retroactively applied to v3.1-preview.1, rolling it out with v3.1-preview.2). [Here](https://github.com/Azure/azure-rest-api-specs/blob/89ff1fe1c88cdc34628f4b0d6e689b414d43e589/specification/cognitiveservices/data-plane/TextAnalytics/preview/v3.1-preview.2/TextAnalytics.json#L1447) is the swagger spec for it
