### ISSUE TITLE
VaultsImpl.wrapModel() - check for this.tenantId != null before using it...

### ISSUE THREAD

**Issue by milismsft** [Azure/azure-sdk-for-java#1218]
... and issue a proper exception it tenantId is found to be null. Otherwise the code triggers a java.lang.NullPointerException which is hard to pinpoint what was causing it (there's no useful stack for it):

e = {NullPointerException@3166} "java.lang.NullPointerException"
 detailMessage = null
 cause = {NullPointerException@3166} "java.lang.NullPointerException"
 stackTrace = {StackTraceElement[0]@3168} 
 suppressedExceptions = {Collections$UnmodifiableRandomAccessList@3169}  size = 0

**Comment by martinsawicki** [comment]
presumably fixed
