### ISSUE TITLE
[FEATURE REQ] LRO error reporting/failing.

### ISSUE THREAD

**Issue by samvaity** [Azure/azure-sdk-for-java#12200]
Currently LRO Poller never throws on failed status of the Long-running Operation. 
Here - https://github.com/Azure/azure-sdk-for-java/blob/master/sdk/core/azure-core/src/main/java/com/azure/core/util/polling/PollerFlux.java#L225

In the usage context of Pollers in Form Recognizer, nothing much is gained out of `LongRunningOperationState.FAILED.`

LRO current implementation fail state usage:
```java
recognizePoller.map(asyncPollResponse -> {
    if (asyncPollResponse.getStatus() == LRO.FAILED) {
       // inspect error or may be cancel server side op if it make sense.
       // user will need to handle the LRO failed status at their end
    } else if (asyncPollResponse.getStatus() == LRO.SUCCEEDED) {
        Mono<> finalResult = asyncPollResponse.getFinalResult();
    }
});

// In this case, if the user doesn't check for failed status and handle accordingly, they are still able to call in the `fetchOperation()`
// only to get an erroneous result back.
```

LRO allowing throwing of exception usage:
```java
recognizePoller.map(asyncPollResponse -> {
    if (asyncPollResponse.getStatus() == LRO.SUCCEEDED) {
        Mono<> finalResult = asyncPollResponse.getFinalResult();
    }
});

// User doesn't have to deal with failing LRO status's and will only be able to fetch the result on a non-failed LRO state.
```

**Comment by mssfang** [comment]
Do we rise the error as PollerError?

**Comment by samvaity** [comment]
>Do we return the error as PollerFluxError?

For FormRecognizer use case, we would want to return the exception when a polling operation returns a failed status https://github.com/Azure/azure-sdk-for-net/blob/master/sdk/formrecognizer/Azure.AI.FormRecognizer/src/RecognizeCustomFormsOperation.cs#L214

**Comment by samvaity** [comment]
Also, look into https://github.com/Azure/azure-sdk-for-java/pull/13025/files/a0ea7f8d7ae4a7959c76c00b2e4fdf31337e4dc4#r455294052
