### ISSUE TITLE
Region.GOV_US_VIRGINIA does not pass correct string to region calls

### ISSUE THREAD

**Issue by paulojohnj** [Azure/azure-sdk-for-java#1220]
when Region.GOV_US_VIRGINIA is used setting regions fails stating: 

The provided location 'usgoveast' is not available for resource group. List of available regions is 'usgoviowa,usgovvirginia'."}

**Comment by miklopz** [comment]
Neither of them do actually. It should be usgovvirginia and usgoviowa

**Comment by jianghaolu** [comment]
For now, please use the string overload. This  will be fixed in the next build.
I didn't have a government environment to test out. A simple dns look up on https://management.usgovcloudapi.net/ gives me back https://usgoveast.management.usgovcloudapi.net/ so that's what I assumed.

**Comment by martinsawicki** [comment]
already implemented
