### ISSUE TITLE
Does Beta3 Azure SDK support for certificate based authentication?

### ISSUE THREAD

**Issue by DanyangLinda** [Azure/azure-sdk-for-java#1223]
In Beta3, Azure can only be authenticated using ApplicationTokenCredentials or credentialsFile. However, none of them is certificate based. Has certificated based authentication been deprecated ?

**Comment by jianghaolu** [comment]
Are you using a management certificate or a service principal certificate?

**Comment by DanyangLinda** [comment]
I am using a service principal certificate

**Comment by nwarriorch** [comment]
any follow up regarding this ?

**Comment by martinsawicki** [comment]
already implemented
