### ISSUE TITLE
Super level API

### ISSUE THREAD

**Issue by sura2k** [Azure/azure-sdk-for-java#1224]
Is there a way to 
- Retrieve tenant information (i.e tenant id)
- Get VM information by passing tenant id (or any other way)
- Get storage details by tenant 

Via super level API (with super level API access key)?

My requirement is to view/show usage details by tenant for managing level people.
Can I do that using this SDK? If not, does Azure Server support this facility?

**Comment by jianghaolu** [comment]
Assuming you are using 1.0.0-beta2 onward.
1) before call `.withSubscription()` you will get an `Azure.Authenticated` object. You can call `.tenants()` on it.
2, 3) Storage accounts and VMs are under subscriptions and resource groups. You will need at least subscription information to list them.

So you will need to 
1) list all the tenants
2) For each tenant, create a credential and login and list subscriptions
3) For each subscription, you can list all the resources you want

Let me know if you need further help. I may be able to write a sample in a few weeks.

**Comment by sura2k** [comment]
> 2) For each tenant, create a credential and login and list subscriptions

What is meant by "create a credential and login"? A tenet already has a login, right?


> I may be able to write a sample in a few weeks.

Which is Great :+1: 

The above mentioned 3 operations, list tenants, get vm info, get storage info are just few from the actual requirements. These are for a read only application.

Still little bit unclear about the authentication.
I except to have some sort of a login/API Key which has access to all tenant related operations.
By looking at the following code snippet, I can see a `tenant `parameter is getting passed into the API.
So the tenant I'm referring here is some kind of a SUPER tenant?

```
ApplicationTokenCredentials credentials = new ApplicationTokenCredentials(client, tenant, key, AzureEnvironment.AZURE);
Azure azure = Azure.authenticate(credentials);
```


Thanks for your quick response :)

**Comment by sura2k** [comment]
Also I found this: Using a `RestClient` I can get `Azure `object by `tenantId`.
I'm looking something similar to this. 
So my questions are,

1. That `super ` (the variabale) really returns all the tenet Ids?
2. If I know the tenet id list, following code will work?

```
Authenticated super= Azure.authenticate(...);

for(Tenant tenant: super.tenants().list()){
    String tenantId = tenant.inner().tenantId();
            	
    RestClient restClient = AzureEnvironment.AZURE.newRestClientBuilder().build();
    Authenticated restAuth = Azure.authenticate(restClient, tenantId);
    Azure azureTenent = restAuth.withDefaultSubscription();
                
    //process each tenant
 }
```

**Comment by yungezz** [comment]
hi @weidongxu-microsoft could you pls have a look? thanks.

**Comment by weidongxu-microsoft** [comment]
I think current Java SDK does not support multi-tenant as usual authentications.

However if one have a Azure CLI logged-in, one can use `AzureCliCredentials` to list available multi-tenants.

```
            Azure.Authenticated authenticated = Azure.configure()
                    .withLogLevel(LogLevel.BASIC)
                    .authenticate(AzureCliCredentials.create());
            PagedList<Tenant> tenants = authenticated.tenants().list();
            for (Tenant tenant : tenants) {
                ...
            }
```

However for each tenant, one likely still need separate credentials to authenticate again.

**Comment by yungezz** [comment]
hi @sura2k does above info helpful? let us know if you met issue when using it.

**Comment by yungezz** [comment]
hi @sura2k pls try above AzureCliCredentials  and feel free to create new issue if met any error. Will close the issue for now. thanks.
