### ISSUE TITLE
Beta3: Unable to set proxy with authentication credentials

### ISSUE THREAD

**Issue by dtretyakov** [Azure/azure-sdk-for-java#1225]
Currently with a fluent API we unable to use proxy server which requires authentication.
It would be great to provide something like that to set proxy authenticator:

``` java
Azure.configure().withProxy(proxy).withProxyAthenticator(authenticator)
```

where `authenticator` is instance of `okhttp3.Authenticator`.

**Comment by dtretyakov** [comment]
Look at the following PRs:
https://github.com/Azure/autorest/pull/1529
https://github.com/Azure/azure-sdk-for-java/pull/1232

**Comment by martinsawicki** [comment]
should be fixed by now
