### ISSUE TITLE
[FEATURE REQ] Cosmos v4 - Provide ability to specify ObjectMapper instance

### ISSUE THREAD

**Issue by allenhumphreys** [Azure/azure-sdk-for-java#12269]
**Is your feature request related to a problem? Please describe.**
When using the Cosmos SDK from Kotlin, we need to register the Kotlin module with the `ObjectMapper` that will deserialize the Cosmos document or else it does not work correctly. We also choose specific serialization/deserialization options to meet our needs.

More specifically, in the context of Spring Boot, the serialization across the application is controlled by the instance of `ObjectMapper` that is configured via Spring's auto-configuration.

As it currently stands with v4 of the SDK, I don't see any obvious hooks into (de)serialization. As a result, I have to first deserialize into an intermediate representation (I'm using `CosmosItemProperties` since that is effectively what v3 did, but I could use `Map<String, Any?>`), and then I convert that value to the Kotlin data class using my fully customized `ObjectMapper` instance. On the outbound code path, I do something similar.

This double (de)serialization results in highly unnecessary CPU usage in our applications. For an SDK revision that claims to be focusing on optimization [https://devblogs.microsoft.com/cosmosdb/java-sdk-v4-ga/], not providing abstract code paths for one of the most CPU intensive parts of the SDK is very regrettable.

**Describe the solution you'd like**
We would like hooks to either provide a custom configured instance of `ObjectMapper`, or to configure the `ObjectMapper` that is used by the SDK. Currently, the hard coded (de)serialization uses `Utils.getSimpleObjectMapper()` to use a lightly customized `ObjectMapper`. I'd like to be able to provide an `ObjectMapper` to the SDK during initialization that will be used to (de)serialize documents when upserting or querying.

**Describe alternatives you've considered**
You could go further, and provide fully customizable entry points for (de)serialization so that (de)serialization isn't tied directly to Jackson at all. Such an API might be functional and provide a `T` for serialization and a byte array for deserialization.

**Information Checklist**
Kindly make sure that you have added all the following information above and checkoff the required fields otherwise we will treat the issuer as an incomplete report
- [x] Description Added
- [x] Expected solution specified

**Comment by kirankumarkolli** [comment]
Thanks @allenhumphreys for the great feedback. 
We have a backlog item to support/enable custom serializer's and it will enable above scenario.

@kushagraThapar can you please create/share the backlog reference.

**Comment by kushagraThapar** [comment]
@allenhumphreys - thanks for raising this issue. 
I am wondering why there is a need for intermediate conversion. `CosmosItemProperties` is no longer present in V4 - because we wanted the APIs to be completely of type `<T>` 

You can checkout the samples here : https://github.com/Azure-Samples/azure-cosmos-java-sql-api-samples

Can you please provide a sample code snippet showing the intermediate conversion code ?

As for the `alternatives that you have considered` section -> we are planning to introduce Streaming APIs soon and with hooks for custom serialization and deserialization mechanism.

**Comment by allenhumphreys** [comment]
@kushagraThapar `CosmosItemProperties` was present in v4.0.1, it was removed in v4.1.0 and renamed to `InternalObjectNode`. The `ObjectMapper` instance used internally cannot deserialize Kotlin data classes. I need to register the Kotlin module with `ObjectMapper` in order to correctly deserialize the response with the SDK.

If I use the simple code and let the SDK attempt to deserialize the response:

```kotlin
val result = cosmosContainer
    .readItem(id, PartitionKey(id), UserDTO::class.java)
    .awaitFirstOrNull()
```

`ObjectMapper` throws the following exception because it doesn't have the Kotlin module.

> com.fasterxml.jackson.databind.exc.InvalidDefinitionException: Cannot construct instance of `com.package.user.dto.UserDTO` (no Creators, like default construct, exist): cannot deserialize from Object value (no delegate- or property-based Creator)
 at [Source: (byte[])"{...}"

As a result, we have to do the following instead:

```kotlin
// POJO map, but with concrete type arguments
class IntermediateType : HashMap<String, Any?>()

// The SDK converts the response into a map
val result = cosmosContainer
    .readItem(id, PartitionKey(id), IntermediateType::class.java)
    .awaitFirstOrNull()
// Then we have to convert it to our target class with our own ObjectMapper
val converted = result?.item?.let { objectMapper.convertValue<UserDTO>(it) }
```

I don't know that we need Streaming APIs, to be honest, since we are using Kotlin I don't think they're really relevant. Customizing the `ObjectMapper` for the current APIs is far more interesting to us for performance as well as ergonomics.

It's also worth noting that we customize timestamp conversions as well.

**Comment by kushagraThapar** [comment]
@allenhumphreys - is there a way we can add the module for now in Cosmos SDK code ?
@moderakh would this be an okay approach or doesn't make sense at all ?

**Comment by allenhumphreys** [comment]
I'm ok with waiting for a full implementation. Everything works, it's just less than ideal.

**Comment by moderakh** [comment]
til custom serializer/deserializer is read, one possible workaround I see is that instead of passing POJO to cosmosContainer.create and reading as POJO you write and read ObjectNode (jackson type).

```java
ObjectNode objectNode = cosmosContainer.readItem(id, PartitionKey(), ObjectNode.class).getItem()
```

and then do the conversion from ObjectNode to POJO at your side.

**Comment by allenhumphreys** [comment]
@moderakh that's pretty much what we do.

**Comment by kushagraThapar** [comment]
Above mentioned workaround is the only way right now, closing this issue now.

**Comment by apescione** [comment]
Unfortunately, this workaround doesn't work in my case. In case in you pojo you have a Java 8 Time Field as below:
`   @JsonProperty("created_at")
    private ZonedDateTime createdAt;`

The conversion to ObjectNode node fails all the same.
