### ISSUE TITLE
VirtualMachine.capture() returns illegal argument exception

### ISSUE THREAD

**Issue by paulojohnj** [Azure/azure-sdk-for-java#1227]
VirtualMachine.capture("containername", true) returns: vhdPrefix is required and cannot be null, but does not appear to take in any info around prefix.

**Comment by anuchandy** [comment]
This is fixed in the `1.0.0.beta4-snapshot` (master branch) but even though you can initiate the capture API with this fix you will still get NPE due this issue https://github.com/Azure/azure-sdk-for-java/issues/1230

**Comment by martinsawicki** [comment]
presumably fixed in 1.0.0-beta4.1 since https://github.com/Azure/azure-sdk-for-java/issues/1230 is fixed.
