### ISSUE TITLE
[FEATURE REQ] Close the open page after InteractiveBrowserCredential completes auth

### ISSUE THREAD

**Issue by xccc-msft** [Azure/azure-sdk-for-java#12276]
**Is your feature request related to a problem? Please describe.**
After InteractiveBrowserCredential completes auth, the page for localhost:port will keep open.

**Describe the solution you'd like**
It would be better if it can be closed by code instead of manual click.

**Describe alternatives you've considered**
It looks the cmd can be wrapped into a process with open url. And later destroy the process then the page will be closed.

**Additional context**

**Information Checklist**
Kindly make sure that you have added all the following information above and checkoff the required fields otherwise we will treat the issuer as an incomplete report
- [x] Description Added
- [x] Expected solution specified

**Comment by g2vinay** [comment]
The interactive authentication is controlled via msal4j library.
I believe, programmatically we cannot command the browser to close a specific tab/window.
Plus, it is better if the user acknowledges the authentication message and closes the browser tab/window.
