### ISSUE TITLE
md5 verifications for blob uploads using EncryptedBlobClient

### ISSUE THREAD

**Issue by markhoughton-microfocus** [Azure/azure-sdk-for-java#12291]
**Is your feature request related to a problem? Please describe.**
When using BlockBlobClient, there is an option to include an md5sum when uploading a blob, which is used to verify that what arrived in Azure was what was sent. There is no such option when using the EncryptedBlobClient.

**Describe the solution you'd like**
I'd like EncryptedBlobClient to provide an option to verify md5s when uploading blobs. Since the encryption would obviously change the md5, the md5 would have to be calculated after encryption, which means the SDK would have to take care of it instead of having one provided.

**Describe alternatives you've considered**
None

**Additional context**
None

**Information Checklist**
Kindly make sure that you have added all the following information above and checkoff the required fields otherwise we will treat the issuer as an incomplete report
- [*] Description Added
- [*] Expected solution specified

**Comment by rickle-msft** [comment]
@markhoughton-microfocus Thank you for the suggestion. I will discuss with my team the possibility of adding this feature and let you know how we plan to proceed.

**Comment by rickle-msft** [comment]
After some conversation, I think we're willing to add support for this feature and will work on getting it in soon. Thanks again for the request!

**Comment by gapra-msft** [comment]
Dev Notes: Add to buffered upload, add an options to options bag (bool verifyMd5) and calculate and send if set.
