### ISSUE TITLE
Beta3: Unable to get instanceView data for virtual machine

### ISSUE THREAD

**Issue by dtretyakov** [Azure/azure-sdk-for-java#1231]
New Fluent API does not provide methods to request instance view data for virtual machine like:

```
azure.virtualMachines().getAsync(groupName, vmName, instanceView)
```

Instead of that we need to use 2 rest api calls:

```
VirtualMachine machine = azure.virtualMachines().getByGroup(groupId, name);
machine.refreshInstanceView();
```

**Comment by martinsawicki** [comment]
@anuchandy  I believe this was by design, no? We wouldn't expose a collection of instance views...

**Comment by anuchandy** [comment]
This is by design, we don't want the default implementation of `getByGroup` of VM to retrieve the instance views. Fetching instance view is costly, so we made it explicit using `machine.refreshInstanceView()`

**Comment by dtretyakov** [comment]
@martinsawicki, @anuchandy in this case we need a method `VirtualMachine#refreshInstanceViewAsync`.

**Comment by anuchandy** [comment]
VM. refreshInstanceViewAsync is now available.
