### ISSUE TITLE
[FEATURE REQ][Blob Storage] Rewrap UnknownHostException before throwing

### ISSUE THREAD

**Issue by SukruthKS** [Azure/azure-sdk-for-java#12321]
**Is your feature request related to a problem? Please describe.**
When storage endpoints cannot be resolved by the blob storage SDK (v12), it throws an `UnknownHostException` wrapped in `ReactiveException` but that exception type is not public so it cannot be handled directly and will have to do a catch all.

**Describe the solution you'd like**
It would be nice if exceptions wrapped in `ReactiveException` are rewrapped with  `RuntimeException` or something similar that is accessible and that the SDK generally uses for such runtime errors.

**Describe alternatives you've considered**
Do a catch all exceptions.

**Additional context**
NA

**Information Checklist**
Kindly make sure that you have added all the following information above and checkoff the required fields otherwise we will treat the issuer as an incomplete report
- [x] Description Added
- [x] Expected solution specified

**Comment by rickle-msft** [comment]
Hi, @SukruthKS. I think this is a fair request and would be good for us to update. We'll look into why ReactiveExceptions aren't getting wrapped in this case and work on fixing that. The only possible catch I can foresee is that sometimes our architecture board is not comfortable with changing exception types that get thrown as it might be thought of as a break, but I think we will be able to consider this a bug fix

**Comment by rickle-msft** [comment]
There are also a couple places in our tests when we explicitly check for ReactiveExceptions, I believe mostly in query tests. We should be sure to update those exception types as well.

**Comment by rickle-msft** [comment]
Hi, @SukruthKS. Quick question about this. You asked that ReactiveExceptions be unwrapped and re-wrapped as RuntimeExceptions. However, ReactiveException does extend RuntimeException, so I'm wondering what the difference will be if we re-wrap? Will you not be catching a RuntimeException either way?

**Comment by SukruthKS** [comment]
Oh, I did not realize that it was extending `RuntimeException`. It should be good then. Thanks!

**Comment by rickle-msft** [comment]
Sounds good! I am going to close this issue, then. Let us know if you need anything else.
