### ISSUE TITLE
[FEATURE REQ] Cosmos per-request consistency level

### ISSUE THREAD

**Issue by allenhumphreys** [Azure/azure-sdk-for-java#12355]
**Is your feature request related to a problem? Please describe.**
We're getting ready to start using different levels of consistency based on what type of work we're doing. It does not seem like I can specify the level on the operation, though.

**Describe the solution you'd like**
It would be nice to be able to override the level for specific operations while still maintaining a default level at the client level.

**Describe alternatives you've considered**
In the absence of this feature, I will probably be using multiple clients which is not advisable for performance reasons according to you own documentation.

**Information Checklist**
Kindly make sure that you have added all the following information above and checkoff the required fields otherwise we will treat the issuer as an incomplete report
- [x] Description Added
- [x] Expected solution specified

**Comment by kirankumarkolli** [comment]
@allenhumphreys Cosmos SDK do allow overriding to weaken the account consistency. Currently its [scoped to the client instance](https://docs.microsoft.com/en-us/java/api/com.azure.cosmos.cosmosclientbuilder.consistencylevel?view=azure-java-stable#com_azure_cosmos_CosmosClientBuilder_consistencyLevel_com_azure_cosmos_ConsistencyLevel_). 

As a work-around application can can maintain per consistency client instances and use appropriately.

**Comment by allenhumphreys** [comment]
> As a work-around application can can maintain per consistency client instances and use appropriately.

@kirankumarkolli Yes, I know that. That's what I said in my post. This feature request is specifically to support per-request specification of the consistency level.

**Comment by kushagraThapar** [comment]
@allenhumphreys - Can you please explain more on your scenario with an example ?

Also, on a side note, SDK can only weaken the consistency which is specified at the account level.

**Comment by allenhumphreys** [comment]
@kushagraThapar We have applications that need to make both strongly consistent requests as well as session based consistent requests.

The split is between HTTP/user client operations and asynchronous events operations. The asynchronous event chains can cross regions resulting in a situation where the previous steps actions will not be available to the current step. However, for HTTP calls, the users location is static and will generally always be routed to the same region. For those calls, we'd like to lower our RU cost.

To achieve this in code, I was hoping to use the same CosmosAsyncClient instance but with different request options. That would be the most convenient for our code.

Thank you for letting me know that SDK can only weaken consistency levels, that seems like a pretty major limitation of the service, no? You might want to call that out in the documentation here https://docs.microsoft.com/en-us/azure/cosmos-db/consistency-levels since you have to choose account-level strong consistency in order to use strong consistency anywhere.

**Comment by kirankumarkolli** [comment]
@allenhumphreys thanks for the feedback. 

We shall update/refresh the documentation.

**Comment by kushagraThapar** [comment]
@allenhumphreys - we do mention it here : https://docs.microsoft.com/en-us/azure/cosmos-db/how-to-manage-consistency?tabs=portal%2Cdotnetv2%2Capi-async#override-the-default-consistency-level

We are also planning to update the consistency level docs, thanks for your input.

**Comment by kushagraThapar** [comment]
@anfeldma-ms - I started an internal conversation with you and @SnehaGunda, Can you please follow up on this ?

**Comment by kirankumarkolli** [comment]
@kushagraThapar are the docs refreshed?

**Comment by kushagraThapar** [comment]
@kirankumarkolli - yes the main conceptual doc now refers to the updated docs which highlight the part that account consistency can only be weaken through clients.

**Comment by kushagraThapar** [comment]
Since docs are refreshed, closing this issue now.
