### ISSUE TITLE
azure-sdk-bom Release Fails on Version Check

### ISSUE THREAD

**Issue by alzimmermsft** [Azure/azure-sdk-for-java#12361]
I attempted to release the `azure-sdk-bom` using our unified pipelines and it failed on validating versions.

**Comment by JimSuplizio** [comment]
Here's an example of the failing pipeline: https://dev.azure.com/azure-sdk/internal/_build/results?buildId=432922&view=logs&j=adf1d365-c641-58b5-a58e-90f029aca966&t=88386d81-ae0f-5985-8936-932e8d36617e
