### ISSUE TITLE
Learn about Event Grid

### ISSUE THREAD

**Issue by bsiegel** [Azure/azure-sdk-for-java#12377]
Things to learn / explore / try out:
- [x] Cloud computing as a general concept
- [x] The Azure portal
- [x] Relevant foundational Azure services such as compute, storage, and functions
- [x] Event Grid service basics: event sources, topics, event subscriptions
- [x] Azure SDK for Java - structure, organization, etc. documented in the [wiki](https://github.com/Azure/azure-sdk-for-java/wiki)
- [x] [Project Reactor](https://projectreactor.io/learn) / reactive programming as a general concept
- [x] Azure Core library and the HTTP pipeline ([source code / documentation](https://github.com/Azure/azure-sdk-for-java/tree/master/sdk/core/azure-core))
- [x] The existing Event Grid client library ([documentation](https://docs.microsoft.com/en-us/java/api/overview/azure/eventgrid?view=azure-java-stable), [source code](https://github.com/Azure/azure-sdk-for-java/tree/master/sdk/eventgrid/microsoft-azure-eventgrid))
- [x] Create a sample project using the existing client library and perform some basic interaction with Event Grids such as creating a topic, publishing an event, subscribing to a topic, and receiving an event.

**Comment by Soreloser2** [comment]
Sample project here: https://github.com/Soreloser2/azure-eventgrid-function-examples
