### ISSUE TITLE
[FEATURE REQ] AzureCliCredential and all new credentials need to be added to docs

### ISSUE THREAD

**Issue by jongio** [Azure/azure-sdk-for-java#12372]
**Library or service name.**
Azure Identity
 
**Is your feature request related to a problem? Please describe.**
Cannot find docs on how to use AzureCliCredential or any of the new credentials, i.e. VSCodeCredential, etc

azsdke2e

**Comment by joshfree** [comment]
@jianghaolu can you please follow up?

**Comment by jianghaolu** [comment]
Thanks @jongio and @joshfree. Will be adding them for July release.

**Comment by joshfree** [comment]
Adding `blocking-release` label
