### ISSUE TITLE
Add unit and integration tests for Event Grid generated code

### ISSUE THREAD

**Issue by bsiegel** [Azure/azure-sdk-for-java#12379]
- [x] Add unit tests for the code generated by AutoRest
- [x] Add integration tests for the code generated by AutoRest

**Comment by YijunXieMS** [comment]
@bsiegel I assume generally autorest-generated code doesn't need unit test or integration test code. The convenience layer does.
Is there any special reason for this issue?

**Comment by bsiegel** [comment]
I believe we have tests for the autorest layer so that if the service behavior diverges from their swagger (or if our swagger doesn't match the service's actual API layer) our nightly live tests will catch it.

**Comment by YijunXieMS** [comment]
Close since it's done.
