### ISSUE TITLE
KeyVault Keys Readme and Samples issues

### ISSUE THREAD

**Issue by Melanie-Ma** [Azure/azure-sdk-for-java#12388]
1.
Section [Link](https://github.com/Azure/azure-sdk-for-java/blob/2296ce2bf8e61ff835da31685baaf8ac3b35ef76/sdk/keyvault/azure-security-keyvault-keys/src/samples/java/com/azure/security/keyvault/keys/KeyAsyncClientJavaDocCodeSnippets.java#L44):
![image](https://user-images.githubusercontent.com/64007802/85271380-51075b80-b4ad-11ea-8b1f-d0d855a86a47.png)

Reason:
![image](https://user-images.githubusercontent.com/64007802/85271455-67adb280-b4ad-11ea-9f84-0bcb4e7af172.png)

Suggestion:
```
.vaultUrl("https://myvault.azure.net/")
.credential(new DefaultAzureCredentialBuilder().build())
.httpLogOptions(new HttpLogOptions().setLogLevel(HttpLogDetailLevel.BODY_AND_HEADERS))
.httpClient(HttpClient.createDefault())
.buildAsyncClient();
```
2.
Section [Link](https://github.com/Azure/azure-sdk-for-java/tree/azure-security-keyvault-keys_4.1.4/sdk/keyvault/azure-security-keyvault-keys#authenticate-the-client):
![image](https://user-images.githubusercontent.com/64007802/85271714-be1af100-b4ad-11ea-8131-65f7636e1878.png)

Suggestion:
Update `client key`  to `client  secret`.
3.
Section [Link](https://github.com/Azure/azure-sdk-for-java/tree/azure-security-keyvault-keys_4.1.4/sdk/keyvault/azure-security-keyvault-keys#async-api):
![image](https://user-images.githubusercontent.com/64007802/85271870-f91d2480-b4ad-11ea-8073-b3cc2b261bfb.png)

Reason:
Click on 'Encrypt Asynchronously' is unresponsive.

Suggestion:
It's should jump to the link: https://github.com/Azure/azure-sdk-for-java/tree/azure-security-keyvault-keys_4.1.4/sdk/keyvault/azure-security-keyvault-keys#encrypt-asynchronously

**Comment by Melanie-Ma** [comment]
@jongio , for notification.

**Comment by joshfree** [comment]
@vcolin7 PTAL

**Comment by vcolin7** [comment]
1. I tested the suggested code and it doesn't work. The correct code would need to remove the `addPolicy()` line and keep the call to `credential()`:

    ```java
    .vaultUrl("https://myvault.azure.net/")
    .credential(new DefaultAzureCredentialBuilder().build())
    .httpLogOptions(new HttpLogOptions().setLogLevel(HttpLogDetailLevel.BODY_AND_HEADERS))
    .httpClient(HttpClient.createDefault())
    .buildAsyncClient();
    ```

Since the given `Credential` object will be added to the pipeline in a `KeyVaultCredentialPolicy` by the `Builder`.

2. Agreed.
3. Agreed.

**Comment by vcolin7** [comment]
The same issue from point number 2 is present in the Certificates [README](https://github.com/Azure/azure-sdk-for-java/tree/azure-security-keyvault-certificates_4.0.4/sdk/keyvault/azure-security-keyvault-certificates#authenticate-the-client) but both have already been corrected in master.
