### ISSUE TITLE
Live Branch in Doc Repo is Failing

### ISSUE THREAD

**Issue by scbedd** [Azure/azure-sdk-for-java#12401]
Even after the very last [verification build](https://opbuildstorageprod.blob.core.windows.net/report/2020%5C6%5C21%5C5de83821-f44b-0e93-473e-c19393f102fe%5CCommit%5C202006210545108871-master%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=Xo5uQIh3mlqsgGUM1cf%2FwMjD5KR7jgDvDioC1%2FFjdAM%3D&st=2020-06-22T21%3A44%3A47Z&se=2020-07-23T21%3A49%3A47Z&sp=r)  run against `master`, whatever happened with the merge is now failing.

Have a test branch that _passes build_ [here](https://review.docs.microsoft.com/en-us/java/api/overview/azure/?branch=live_fix_attempt&view=azure-java-stable), but still do not fully understand where the error is.

**Comment by joshfree** [comment]
@samvaity could you complete the first pass investigation?

**Comment by scbedd** [comment]
[This PR](https://github.com/Azure/azure-docs-sdk-java/pull/1052) resolved the failures.
