### ISSUE TITLE
CosmosAsyncContainer , is it thread-safe?

### ISSUE THREAD

**Issue by jaisonpjohn** [Azure/azure-sdk-for-java#12407]
**Query/Question**
CosmosAsyncContainer , is it thread-safe? 
Is this `database.getContainer("containerName")` an expensive operation? What's the best practice. Can I use it as singleton object?

 
 **Information Checklist**
 Kindly make sure that you have added all the following information above and checkoff the required fields otherwise we will treat the issuer as an incomplete report
- [x] Query Added
- [x] Setup information Added

**Comment by jaisonpjohn** [comment]
@kushagraThapar , @anuchandy bump!

**Comment by kushagraThapar** [comment]
@jaisonpjohn - yes, you should be able to use it as a singleton object for a specific container.
