### ISSUE TITLE
Approach to smoke testing application frameworks

### ISSUE THREAD

**Issue by mitchdenny** [Azure/azure-sdk-for-java#12419]
This purpose of this issue is to discuss/resolve how we are going to handle testing validation of modules which are extensions to application frameworks. The trigger for creating this issue was a discussion with the Azure Spring team on how to handle validating the Azure Spring Data libraries for Cosmos DB against version Azure Spring Boot 2.2.x and 2.3.x.

Tests for application frameworks are more like integration tests in that the test harness itself is a full blown application that needs to be build and run, and somehow tested for correctness. They also tend to need access to real Azure resources to validate that they work. Samples are also very similar.

My proposal is that for application frameworks and full blown application samples we adopt a different approach for building and validating them. Instead of referencing them in the ```sdk/[service]/pom.xml``` file and testing them using the ```mvn verify``` command, we instead declare the list of smoke tests/samples in the ```ci.yml``` (or ```test.yml```) file, and then we execute a script in a well known location for each sample. This script can do whatever it wants but the pipeline will interpret a non-zero exit code as a failure.

This model could be applied to all of our repos, not just Java and grant ultimate flexibility when it comes to testing application frameworks. We would also leverage the rest resource creation model that we already have in place.

Example layout:

```
sdk/
  cosmos/
    smoketests/
      spring-22-cosmosdb/
        run.ps1 (or .sh)
      spring-23-cosmosdb/
        run.ps1 (or .sh)
```

Inside the ```ci.yml``` or ```test.yml``` file we would declare the smoke tests:

```
StandaloneTests:
  - name: spring-22-cosmosdb
  - name: spring-23-cosmosdb
```

Then for each one of those we would generate a step in the pipeline to run the script (after test resources were created). Interested in getting folks input on this model.

/cc @danieljurek @JimSuplizio @weshaggard @jialindai @hemanttanwar @kushagraThapar

**Comment by jialindai** [comment]
Thanks @mitchdenny, 

One question I have is how to automate the resource provision / deletion in this model. Does a Azure resource template still work in this case?

**Comment by mitchdenny** [comment]
That would be part of what we would need to work out. If we plugged this into our live test model then I guess we would just use the same resources. If we plugged into the CI pipelines we would need to port that across.

**Comment by danieljurek** [comment]
Today the resource deployment script walks the directory tree at `sdk/{ServiceDirectory}` and deploys any `test-resources.json` files it finds. Deploying these standalone tests will be easy enough: just specify a specific directory under `sdk` (e.g. `spring/spring-22-cosmosdb` ) and it will deploy the ARM templates it finds there. 

What we don't account for today, however, is the possibility of there being both live tests and standalone tests in the same service directory. That is, in a hypothetical situation with a directory structure like: 

```
sdk/
  spring/
    tests.yml
    test-resources.json
    ...
    some-spring-package-with-live-tests/
    ...
    spring-22-cosmosdb/
      test-resources.json
    ... 
```

Running the deployment script with a service directory value of `spring` will cause the script to find and deploy `sdk/spring/test-resources.json` and `sdk/spring/spring-22-cosmosdb/test-resources.json`. 

This could cause too many resources to be unnecessarily deployed if the testing job were scoped to a single scenario (like live tests, or testing just `spring-22-cosmosdb`)

**Comment by mitchdenny** [comment]
Thanks Daniel. I think what I'm proposing with the above is that we still just have the single ```test-resources.json``` file in the ```sdk/[area]``` path, but we, within the context of each live test leg execute zero or more scripts which can avail themselves of those resources.

**Comment by mitchdenny** [comment]
Circling back on this issue. A few weeks ago I was on a call and I think the approach that was going to be taken was that teams (like Spring) that need to test application frameworks can take advantage of the Pre/Post RunSteps in live tests. I think using this existing mechanism which is already well supported probably makes more sense. As a result I'm going to close this down.
