### ISSUE TITLE
[FEATURE REQ] azure-storage-file-share should have a way to expose file created/updated timestamp

### ISSUE THREAD

**Issue by nanda-kumar-office1** [Azure/azure-sdk-for-java#12432]
**Is your feature request related to a problem? Please describe.**
While querying the api to get list of files from a share folder, the ShareFileItem object does not have created or updated date of the file.

**Describe the solution you'd like**
Kindly requesting to add the required method in ShareFileItem to get the created or updated timestamp of the file.

**Describe alternatives you've considered**
-none

**Additional context**
-none

**Information Checklist**
Kindly make sure that you have added all the following information above and checkoff the required fields otherwise we will treat the issuer as an incomplete report
- [yes ] Description Added
- [ yes] Expected solution specified

**Comment by nanda-kumar-office1** [comment]
Above request is based on Azure file share.
<dependency>
    <groupId>com.azure</groupId>
    <artifactId>azure-storage-file-share</artifactId>
    <version>12.5.0</version>
</dependency>

**Comment by rickle-msft** [comment]
Hi, @nanda-kumar-office1. You can see [here](https://docs.microsoft.com/en-us/rest/api/storageservices/list-directories-and-files#response-body) that the service doesn't actually return these properties when listing files in a share. Unfortunately, that means that we don't have a way to offer those values in the SDK.

**Comment by nanda-kumar-office1** [comment]
Yes Rick, I see that. It is strange that, Azure blob api provides all three, i.e filename, size and updated date in the list api, but not with Azure file share.
If not here, where do I file a request for this.

**Comment by rickle-msft** [comment]
I have routed it to the appropriate people for consideration as a new service feature

**Comment by rickle-msft** [comment]
I am going to close this issue as it is not a request for the sdks and will not be effectively tracked here.
