### ISSUE TITLE
How to query allowed cores and NICs in a subscription?

### ISSUE THREAD

**Issue by puneet101** [Azure/azure-sdk-for-java#1243]
Looks like there are cores, NIC and other quotas. 

-Puneet

**Comment by jianghaolu** [comment]
They are available through the usages for each individual services. But they are not exposes through Java SDK today. Only storage usage is exposed through `Azure.storageUsages()`.

We should add them considering they are useful and low-hanging fruits. @anuchandy @martinsawicki

**Comment by martinsawicki** [comment]
this should have been done as part of the aforementioned PR
