### ISSUE TITLE
Define vm with custom data

### ISSUE THREAD

**Issue by paulojohnj** [Azure/azure-sdk-for-java#1246]
Is it possible to define (or update) a vm with custom data. I am seeing this field/setter in osProfile but do not know how to set it during vm definition or update. Looking to store configuration / data with this field then leverage the subsequent /var/lib/waagent/ovf-env.xml or /var/lib/waagent/CustomData
or /var/lib/cloud/instance/user-data.txt file from an extension

**Comment by anuchandy** [comment]
@paulojohnj this is addressed in the PR - https://github.com/Azure/azure-sdk-for-java/issues/1249, will be merged in couple of days.


Usage: https://github.com/anuchandy/azure-sdk-for-java/blob/bb730c376420f440777c2f4b609424037115cca2/azure/src/test/java/com/microsoft/azure/management/TestVirtualMachineCustomData.java#L57

**Comment by paulojohnj** [comment]
Great! Thanks for the quick response, looking to use the custom data to store configuration information or a script to then leverage from a CSE. Is custom data only definable for known images as opposed to stored images ?

**Comment by anuchandy** [comment]
custom data can be specified for both known (a.k.a platform) image and stored (a.k.a generalized) image.

**Comment by anuchandy** [comment]
Closing - This feature has been added https://github.com/Azure/azure-sdk-for-java/pull/1249
