### ISSUE TITLE
Core Samples issues

### ISSUE THREAD

**Issue by Melanie-Ma** [Azure/azure-sdk-for-java#12486]
1. 
Section [Link](https://github.com/Azure/azure-sdk-for-java/blob/master/sdk/core/azure-core/src/samples/java/com/azure/core/http/rest/PagedFluxBaseJavaDocCodeSnippets.java#L119):
![image](https://user-images.githubusercontent.com/64007802/85532697-80030600-b642-11ea-8fb2-1e24eb045be3.png)
![image](https://user-images.githubusercontent.com/64007802/85532746-8a250480-b642-11ea-8bd3-bcda2ac150c6.png)
Question:
The type `PagedFluxBase<T,P>` is deprecated, so whether the method `byTSnippet()` of the sample still needs?
2. 
Section [Link](https://github.com/Azure/azure-sdk-for-java/blob/master/sdk/core/azure-core/src/samples/java/com/azure/core/http/rest/PagedIterableBaseJavaDocCodeSnippets.java#L80):
![image](https://user-images.githubusercontent.com/64007802/85534993-6236a080-b644-11ea-90fe-b9b628e605ae.png)
![image](https://user-images.githubusercontent.com/64007802/85535049-6c589f00-b644-11ea-912f-f84094ebe249.png)
Question:
The method `createCustomInstance()` returns null which caused null point exception for the method `iterableByPageWhileSnippet()` . So what kind of results do you want for this sample?

**Comment by Melanie-Ma** [comment]
@jongio , for notification.

**Comment by alzimmermsft** [comment]
Given this is a codesnippet for the deprecated class it is fine that it warns about deprecation. I'll update the example to use a more real world scenario to resolve the `NullPointerException`.
