### ISSUE TITLE
unicode is not supported in ResourceGroupOperations

### ISSUE THREAD

**Issue by xizhousheng** [Azure/azure-sdk-for-java#1250]
ResourceGroupOperationsImpl

 if (Pattern.matches("^[-\w\._]+$", resourceGroupName) == false) {
            throw new IllegalArgumentException("resourceGroupName");
        }

'w' indicates only ascii codes and you may have to involve the code pages of non-ascii in regex if you'd like to search them.

The code example involves the most of Unicode characters:
    boolean valid = Pattern.matches("^[\u0080-\u9FFF_\uFB00-\uFFFDh\w\._]+$", "表ポあA中Œé鷗停B逍Üßàùªñ");

**Comment by jianghaolu** [comment]
👍  Thanks for the feedback.
I didn't even know unicode characters are allowed!

**Comment by xizhousheng** [comment]
ppl working with resource group name in East-Asia and West-Euro sometimes:)

**Comment by praries880** [comment]
@jianghaolu is this issue still relevant?

**Comment by yaohaizh** [comment]
@ChenTanyi could you help take a look to see whether this issue is still existing?

**Comment by ChenTanyi** [comment]
I did not find ResourceGroupOperations, maybe it had been changed.
And I test it successful to create a resource group with UTF-8 characters.
I think it has been fixed.
