### ISSUE TITLE
Leaking Implementation in Public API

### ISSUE THREAD

**Issue by alzimmermsft** [Azure/azure-sdk-for-java#12502]
A few APIs are leaking `implementation` classes into public API.

https://github.com/Azure/azure-sdk-for-java/blob/master/sdk/search/azure-search-documents/src/main/java/com/azure/search/documents/util/SearchPagedResponse.java#L43

https://github.com/Azure/azure-sdk-for-java/blob/master/sdk/search/azure-search-documents/src/main/java/com/azure/search/documents/util/SuggestPagedResponse.java#L43

**Comment by JonathanGiles** [comment]
How did this get past the checkstyle checks?

**Comment by alzimmermsft** [comment]
> 
> 
> How did this get past the checkstyle checks?

It appears that the custom rule doesn't extract generic types, since these leaks are `SimpleResponse<T>` they bypass the check.

**Comment by JonathanGiles** [comment]
Good catch - we need to update our checkstyle rule to catch this! And Sima, this needs to be resolved prior to shipping GA.

**Comment by sima-zhu** [comment]
Thanks for catching this! Does this count as a breaking change? I have to write an email for approval, right?

**Comment by JonathanGiles** [comment]
yes, it is a breaking change to API.

**Comment by alzimmermsft** [comment]
Fixed in #12504
