### ISSUE TITLE
[BUG] EventHub's BeginSequenceNumber is not getting updated

### ISSUE THREAD

**Issue by abhishekpandey003** [Azure/azure-sdk-for-java#12511]
**Describe the bug**
The EventHub's BeginSequenceNumber, fetched from com.microsoft.azure.eventhubs.PartitionRuntimeInformation is not showing the correct Consumer count. It has stopped moving since Monday, June 22nd, 2020, even though the data is getting pushed and processed from EventHub.

Check the PartitionRuntimeInformation stats:
PartitionId: 0, LastEnqueuedOffset: 196216, **BeginSequenceNumber: 0,** LastEnqueuedSequenceNumber: 5, LastEnqueuedTimeUtc: 2020-06-24T10:37:40.557Z
PartitionId: 1, LastEnqueuedOffset: 308320, **BeginSequenceNumber: 0**, LastEnqueuedSequenceNumber: 5, LastEnqueuedTimeUtc: 2020-06-24T10:37:40.312Z

Here, the BeginSequenceNumber is stuck at zero no matter how much of data you push & process.

**To Reproduce**
Push and Process some data from EventHub
1. Create a Storm topology using Apache Storm 1.2.2 to read from EventHub.
2. Use org.apache.storm.eventhubs.spout.EventHubSpout to read data from EventHub.
3. And a single bolt to ACK the data.
4. Push some data to the EventHub.
5. Let the bolts process and ACK the data.

Check BeginSequenceNumber
1. Connect to EventHub using EventHub Client.
2. Fetch PartitionRuntimeInformation.
3. Check for the value of BeginSequenceNumber.

***Code Snippet***
Code snippet to fetch PartitionRuntimeInformation

final ApplicationTokenCredentials applicationTokenCredentials = new ApplicationTokenCredentials(
            clientId, domain, secret, AzureEnvironment.AZURE);

EventHubManagementClientImpl eventHubManagementClient = new EventHubManagementClientImpl(applicationTokenCredentials)
            .withSubscriptionId(subscriptionId)
            .withLongRunningOperationRetryTimeout(1);

String sasKey = eventHubManagementClient.namespaces().
            listKeys(resourceGroupName, eventHubNameSpace, sasKeyName).
            primaryKey();

final ConnectionStringBuilder connectionStringBuilder = new ConnectionStringBuilder().
            setNamespaceName(eventHubNameSpace).
            setEventHubName(eventHub).
            setSasKeyName(sasKeyName).
            setSasKey(sasKey);

final ExecutorService executorService = Executors.newScheduledThreadPool(1);

PartitionRuntimeInformation partition = EventHubClient.createSync(connectionStringBuilder.toString(), executorService)
               .getPartitionRuntimeInformation("0")
               .get();
System.out.printf("PartitionId: %s, LastEnqueuedOffset: %s, BeginSequenceNumber: %d, " +
                     "LastEnqueuedSequenceNumber: %d, LastEnqueuedTimeUtc: %s\n",
               partition.getPartitionId(), partition.getLastEnqueuedOffset(), partition.getBeginSequenceNumber(),
               partition.getLastEnqueuedSequenceNumber(), partition.getLastEnqueuedTimeUtc().toString());

**Expected behavior**
When Topology has ACKed the EventHub data, the BeginSequenceNumber should reflect the correct Consumer count.

**Setup (please complete the following information):**
 - OS: Linux
 - IDE : IntelliJ
 - Version of the Library used
storm-eventhubs-1.2.2
azure-eventhubs-1.0.2

**Additional context**
This behavior is the same across different versions and flavors (java/python) of Azure EventHub client.

**Information Checklist**
Kindly make sure that you have added all the following information above and checkoff the required fields otherwise we will treat the issuer as an incomplete report
- [x] Bug Description Added
- [x] Repro Steps Added
- [x] Setup information Added

**Comment by srnagar** [comment]
@JamesBirdsall could you please take a look?

**Comment by JamesBirdsall** [comment]
BeginSequenceNumber is the sequence number of the oldest message still available in the partition. It will not change until the retention period kicks in and messages start getting expired. It is unrelated to where your application(s) are consuming from.

**Comment by abhishekpandey003** [comment]
Is this a recent change in behavior? Because earlier, we have seen BeginSequenceNumber getting updated with each record after processing.

**Comment by JamesBirdsall** [comment]
No, this is not new behavior. By design, message consumption in an event hub is nondestructive, The only thing that has ever removed messages from a partition is the retention period check, and even that is generally done lazily, when a receiver is opened on the partition.
To be honest, I don't know what you were seeing. The behavior you describe now is the expected behavior. If you used to see something different, that would be the bug.

**Comment by abhishekpandey003** [comment]
Thanks @JamesBirdsall for the clarification. So the BeginSequenceNumber is not what we were expecting it to be. Probably you can close this bug. 
One quick question if you can answer, What is the easiest way to find the equivalent sequence number for an offset?

**Comment by JamesBirdsall** [comment]
Each message in a partition has a sequence number and offset, and the correspondence is known only to the service. At a user level, the only way to look is to receive a message and check the system properties, which include the sequence number and offset of that message.
What problem are you trying to solve by converting an offset to a sequence number?

**Comment by abhishekpandey003** [comment]
We are migrating from AMQP protocol to Kafka protocol, so after migration, we want to make sure that Kafka client starts from the point where AMQP client stopped. To achieve that we need to commit the last consumed offset (in terms of sequence) into the Kafka consumer group. Currently, we are storing only the offsets in our checkpoint store so we were looking for a way to find the equivalent sequence number of an offset. And the workaround you mentioned above works for us, as I am able to find both the offset and sequence within a message. Only thing is that I need to read again the last consumed message.
