### ISSUE TITLE
OS disk vhd not stored in storageAccount when coming from a stored image

### ISSUE THREAD

**Issue by paulojohnj** [Azure/azure-sdk-for-java#1252]
When a vm is defined with a stored image (from one account: account A) and an existing storage account (another account: account b) the os disk vhd is still stored in the original account: account a

**Comment by anuchandy** [comment]
This is a restriction of Azure, where both stored image (custom image) and OS disk vhd of VM based on it needs to be in the same storage account. The storage account specified via optional argument will be used as the default storage account for data disks (if any).

**Comment by anuchandy** [comment]
Closing  - this behavior is due to server design
