### ISSUE TITLE
whitelistgenerator-maven-plugin needs to be updated to look at the correct xpath for the banned dependency includes

### ISSUE THREAD

**Issue by JimSuplizio** [Azure/azure-sdk-for-java#12535]
The allowlist report has been broken since mid-April and it initially thought that the pom restructuring was the cause but that's not the case. The [original PR for the maven-enforcer-plugin](https://github.com/Azure/azure-sdk-for-java/pull/9743) had everything overriding the execution that was defined in pom.client.xml which required every pom file to have duplicate configuration. This was [refactored as part of this PR](https://github.com/Azure/azure-sdk-for-java/pull/9884) and this is when the allowlist report was actually broken.

The whitelistgenerator-maven-plugin is only searching for banned dependencies with a particular [xpath](https://github.com/JonathanGiles/whitelistgenerator/blob/master/core/src/main/java/net/jonathangiles/tools/maven/whitelistgenerator/Main.java#L68) which is defined as 
`/project/build/plugins/plugin/executions/execution/configuration/rules/bannedDependencies/includes/include` 
When the refactoring was done this changed the xpath to the bannedDependencies to
`/project/build/plugins/plugin/configuration/rules/bannedDependencies/includes/include`

This should probably be fixed at the same time the plugin is renamed. 

Also, on the same note the [client parent pom's configuration for the plugin](https://github.com/Azure/azure-sdk-for-java/blob/master/sdk/parents/azure-client-sdk-parent/pom.xml#L441) should probably be changing baseDir configuration entry from
`<baseDir>.</baseDir>`
to
`<baseDir>${project.basedir}</baseDir>`

**Comment by JonathanGiles** [comment]
I've fixed the XPath expression and renamed the output from whitelist to allowList. At this stage I'm not going to rename the library itself so I'm marking this as resolved. Upgrading to 1.0.2 of the library, and updating the report html to use 'fullAllowList' and 'allowList' instead of the existing code should get this working again.

**Comment by JimSuplizio** [comment]
@JonathanGiles, are you planning on updating the external dependency so the build system picks up this new version?
