### ISSUE TITLE
List virtual machines within scale set

### ISSUE THREAD

**Issue by kingferiol** [Azure/azure-sdk-for-java#1260]
Hi all.

I'm new to Azure and I'm starting to make experience with java-ask.

Is there a way to get the list of VMs contained in a scale set.

Thanks

**Comment by anuchandy** [comment]
@kingferiol - I can see instances in portal but I don't see an API in the service spec to get that information. We are checking with service team about the availability of API for fetching instance ids.

**Comment by kingferiol** [comment]
Also using API to list VM within a Resource Group this kind of VM are not there

**Comment by anuchandy** [comment]
Yes, this type of virtual machines exists in the context of parent scale set. They are not  included in the resource group virtual machine list.

**Comment by anuchandy** [comment]
@kingferiol this feature is in, see the [unit test] (https://github.com/Azure/azure-sdk-for-java/blob/master/azure-mgmt-compute/src/test/java/com/microsoft/azure/management/compute/VirtualMachineScaleSetOperationsTests.java#L207) for usage.

**Comment by anuchandy** [comment]
Closing this - supported starting from 1.0.0-beta4.
