### ISSUE TITLE
Fix broken links

### ISSUE THREAD

**Issue by KarishmaGhiya** [Azure/azure-sdk-for-java#12630]
Here is a list of broken links in the java repo with 404 error - that I couldn't fix - (will keep adding to list) -
- [x] Found 1 link on page file:///home/vsts/work/1/s/sdk/batch/microsoft-azure-batch/README.md
WARNING: Link to file does not exist /home/vsts/work/1/s/sdk/batch/microsoft-azure-batch/AUTH.md

- [x] Found 1 link on page file:///home/vsts/work/1/s/sdk/cosmos/azure-cosmos/README.md
WARNING: [404] broken link https://projectreactor.io/docs/core/release/api/

- [ ] Found 3 links on page file:///home/vsts/work/1/s/sdk/cosmos/azure-spring-data-cosmosdb/README.md
WARNING: Link to file does not exist /home/vsts/work/1/s/sdk/cosmos/azure-spring-data-cosmosdb/QueryPartitionedCollection.md
WARNING: Link to file does not exist /home/vsts/work/1/s/sdk/cosmos/azure-spring-data-cosmosdb/samplecode
WARNING: Link to file does not exist /home/vsts/work/1/s/sdk/cosmos/azure-spring-data-cosmosdb/src/test/java/com/microsoft/azure/spring/data/cosmosdb/repository/integration/AddressRepositoryIT.java

- [ ] Found 3 links on page file:///home/vsts/work/1/s/sdk/cosmos/dev.md
WARNING: Link to file does not exist /home/vsts/work/1/s/sdk/cosmos/examples/src/test/java/com/microsoft/azure/cosmosdb/rx/examples/TestConfigurations.java
WARNING: Link to file does not exist /home/vsts/work/1/s/sdk/cosmos/sdk/
WARNING: Link to file does not exist /home/vsts/work/1/s/sdk/cosmos/sdk/src/test/java/com/microsoft/azure/cosmosdb/rx/TestConfigurations.java

- [x] Found 1 link on page file:///home/vsts/work/1/s/sdk/eventhubs/microsoft-azure-eventhubs-eph/README.md
WARNING: Link to file does not exist /home/vsts/work/1/s/sdk/eventhubs/readme.md

- [ ] Fix broken links in management/docs/SAMPLES.md (#13332)

- [ ] Found 1 link on page file:///home/vsts/work/1/s/sdk/search/azure-search-documents/src/test/README.md
WARNING: Link to file does not exist /home/vsts/work/1/s/sdk/search/azure-search-documents/src/samples/java/com/azure/search/CreateTestResources.java

- [ ] Found 1 link on page file:///home/vsts/work/1/s/sdk/spring/azure-spring-boot-starter-cosmosdb/README.md
WARNING: Link to file does not exist /home/vsts/work/1/s/sdk/spring/azure-spring-boot-starter-cosmosdb/test/java/com/microsoft/azure/spring/data/cosmosdb/repository/AddressRepositoryIT.java

- [ ] Found 1 links on page file:///home/vsts/work/1/s/sdk/storage/azure-storage-blob-nio/CHANGELOG.md
WARNING: Link to file does not exist /home/vsts/work/1/s/sdk/storage/azure-storage-blob-nio/LINK

- [ ] Found 1 link on page file:///home/vsts/work/1/s/sdk/storage/azure-storage-queue/README.md
[405] while requesting https://myaccount.queue.core.windows.net/images-to-download

- [ ] Found 2 links on page file:///home/vsts/work/1/s/sdk/storage/microsoft-azure-storage-blob/README.md
WARNING: [404] broken link https://docs.microsoft.com/en-us/java/api/overview/azure/storage_stable?view=azure-java-legacy
WARNING: [404] broken link https://docs.microsoft.com/en-us/java/api/overview/azure/storage/queue?view=azure-java-preview

**Comment by joshfree** [comment]
@conniey could you break this apart into multiple issues (one per SDK team) and also handle fixing the ones common to the central Azure SDK team?

**Comment by KarishmaGhiya** [comment]
Fixed all broken links as part of the PR https://github.com/Azure/azure-sdk-for-java/pull/13989
