### ISSUE TITLE
[QUERY] Java SDK Samples for setup Private Endpoint on Storage Blob Programmatically

### ISSUE THREAD

**Issue by hambster** [Azure/azure-sdk-for-java#12646]
**Query/Question**
Is there any document/samples for Private Endpoint on Storage Blob setup and creation?

***Why is this not a Bug or a feature Request?***
Request for sample.

**Setup (please complete the following information if applicable):**

 
 **Information Checklist**
Lack of sample for Java SDK to create Private Endpoint on Storage Blob.

**Comment by rickle-msft** [comment]
Hi, @hambster. Thank you for your question. From what I can see in [this article](https://docs.microsoft.com/en-us/azure/storage/common/storage-private-endpoints), everything should work as though the endpoint were a normal endpoint. The article states: "Applications in the VNet can connect to the storage service over the private endpoint seamlessly, using the same connection strings and authorization mechanisms that they would use otherwise."

I think you should be able to configure your clients like normal and be just fine.

Please let us know if you have any trouble with this or any further questions.

**Comment by hambster** [comment]
Hi @rickle-msft ,

I'm looking for sample code with Java SDK to create private endpoint/link to Storage Account programmatically.
Just want to know whether you have sample for reference.
Thank you.

**Comment by rickle-msft** [comment]
@hambster Creating such an endpoint is done through the management sdk, which is all generated and so doesn't have any samples at the moment unfortunately. If you have any problems piecing it together, you can let me know and I'll do my best to support

**Comment by rickle-msft** [comment]
@joshfree can you please comment on the possibility of adding samples to the management plane sdks?

**Comment by nickzhums** [comment]
@rickle-msft you are very welcome to contribute sdk samples to management plane sdk, please follow up with me on the details. 

@hambster which java SDK are you using ? could you let us the package name and version? thanks

adding @yungezz for awareness

**Comment by yungezz** [comment]
In Java management SDKs user need to use inner to access privateendpointConnection. @xccc-msft will share code samples to it.

**Comment by xccc-msft** [comment]
@hambster If you are using Java management SDKs, you may setup Private Endpoint on Storage Blob by below sample code.
```java
        PrivateLinkServiceConnection privateLinkServiceConnection = new PrivateLinkServiceConnection()
                .withName(plsName)
                .withPrivateLinkServiceId(storageAccount.id())
                .withPrivateLinkServiceConnectionState(new PrivateLinkServiceConnectionState().withStatus("Approved"))
                .withGroupIds(Arrays.asList("blob"));

        PrivateEndpointInner privateEndpointInner = new PrivateEndpointInner()
                .withPrivateLinkServiceConnections(Arrays.asList(privateLinkServiceConnection))
                .withSubnet(network.subnets().get(subnetName).inner());

        privateEndpointInner.withLocation(Region.US_WEST.toString());

        networkManager.inner().privateEndpoints().createOrUpdate(rgName, pedName, privateEndpointInner);
        // fetch storage account again and find the private endpoint connections
        storageAccount.refresh();
        storageAccount.inner().privateEndpointConnections();
```

**Comment by hambster** [comment]
> @hambster If you are using Java management SDKs, you may setup Private Endpoint on Storage Blob by below sample code.
> 
> ```java
>         PrivateLinkServiceConnection privateLinkServiceConnection = new PrivateLinkServiceConnection()
>                 .withName(plsName)
>                 .withPrivateLinkServiceId(storageAccount.id())
>                 .withPrivateLinkServiceConnectionState(new PrivateLinkServiceConnectionState().withStatus("Approved"))
>                 .withGroupIds(Arrays.asList("blob"));
> 
>         PrivateEndpointInner privateEndpointInner = new PrivateEndpointInner()
>                 .withPrivateLinkServiceConnections(Arrays.asList(privateLinkServiceConnection))
>                 .withSubnet(network.subnets().get(subnetName).inner());
> 
>         privateEndpointInner.withLocation(Region.US_WEST.toString());
> 
>         networkManager.inner().privateEndpoints().createOrUpdate(rgName, pedName, privateEndpointInner);
>         // fetch storage account again and find the private endpoint connections
>         storageAccount.refresh();
>         storageAccount.inner().privateEndpointConnections();
> ```

Hi @xccc-msft thank you for your help.
I will test whether it works.
Thank you.

**Comment by lilyjma** [comment]
Hi @hambster, I'm closing the issue for now. If you're still experiencing the issue please feel free to reopen it. Thanks!
