### ISSUE TITLE
Perf testing for pipeline

### ISSUE THREAD

**Issue by gapra-msft** [Azure/azure-sdk-for-java#12656]
Can we get some data around how much extra time the pipeline adds to individual network requests?

I've been doing some testing of my own by adding some basic log options to the azure storage datalake clients as well as timers around individual methods and I'm seeing that the total time of the method looks to take around 200 - 250ms * # of network requests in addition to the sum of the individual network request time. 

```
long t1 = System.currentTimeMillis();
dataLakeFileClient.uploadFromFile(inputPaths.get(i).toString(), true);
long t2 = System.currentTimeMillis();
LOGGER.info(String.format("Upload took: %.02f seconds", ((double) (t2 - t1))));
```

For example, with this code, I'm seeing the upload network requests take 688ms + 582ms + 60ms (create, append and flush respectively) but the logger indicate the upload takes 2081 ms

I've done some similar testing with a method like getProperties (only one network request) and it takes approx 250ms more than the HEAD request time.

**Comment by joshfree** [comment]
@anuchandy could you assist with this investigation this week?

**Comment by anuchandy** [comment]
Just finished adding a perf module to instrument DataLake (G1 and G2):
 
https://github.com/anuchandy/azure-sdk-for-java/tree/dlake-perf

**Comment by alzimmermsft** [comment]
Closing as an investigation was completed on this. The root issue was that each request was instantiating a new service client without sharing a common `HttpClient`. This resulted in a new `HttpClient` being created per service call, resulting in the additional overhead observed outside of the network I/O time.

For future reference, if an issue is observed where network I/O time isn't roughly equivalent to total API call time, create service clients using a pattern similar to the following:

```java
DataLakePathClientBuilder dataLakePathClientBuilder = new DataLakePathClientBuilder()
    .endpoint("<YOUR ENDPOINT>")
    .fileSystemName("<YOUR FILE SYSTEM>")
    .credential(yourCredential)
    .httpClient(yourSharedHttpClient);

// Then for each time a new DataLakeFileClient is needed do the following
DataLakeFileClient aDataLakeFileClient = dataLakePathClientBuilder.pathName("<PATH TO FILE>")
    .buildFileClient()
```

Additionally, there is [this tracking issue](https://github.com/Azure/azure-sdk-for-java/issues/21134) which discusses using a shared `HttpClient` instance by default when one isn't provided.
