### ISSUE TITLE
[BUG] EncryptedBlobAsyncClient uses block() in async method

### ISSUE THREAD

**Issue by weidongxu-microsoft** [Azure/azure-sdk-for-java#12689]
**Describe the bug**
EncryptedBlobAsyncClient uses block() in async method
https://github.com/Azure/azure-sdk-for-java/blob/master/sdk/storage/azure-storage-blob-cryptography/src/main/java/com/azure/storage/blob/specialized/cryptography/EncryptedBlobAsyncClient.java#L448-L449

It would cause runtime error
```
block()/blockFirst()/blockLast() are blocking, which is not supported in thread reactor-http-nio-5
```

***Exception or Stack Trace***
Add the exception log and stack trace if available

**To Reproduce**
Config with `AsyncKeyEncryptionKey` and upload some file.
```
encryptedBlobClient.uploadFromFile(file2Path);
```

***Code Snippet***
Add the code snippet that causes the issue.

**Expected behavior**

**Screenshots**

**Setup (please complete the following information):**
 - OS: [e.g. iOS] Windows
 - IDE : [e.g. IntelliJ] IntelliJ
 - Version of the Library used 12.7.0

**Additional context**

**Information Checklist**
Kindly make sure that you have added all the following information above and checkoff the required fields otherwise we will treat the issuer as an incomplete report
- [x] Bug Description Added
- [x] Repro Steps Added
- [x] Setup information Added

**Comment by rickle-msft** [comment]
@weidongxu-microsoft Thank you for pointing this out. It looks like you are correct that we are blocking in an async context. We'll work on getting a fix out for this soon.
