### ISSUE TITLE
[Discussion] Returning to different parent stage from different child definition forks

### ISSUE THREAD

**Issue by anuchandy** [Azure/azure-sdk-for-java#1269]
#### Problem:
We want to enable returning to different parent stages from different child definition forks

#### What we have today: The child def models we encountered so far return to same stage in parent

Suppose we have a fluent implementation of child type (FooBarChildResourceImpl), which implements interfaces for different flavours of children (Foo and Bar). So far when we fork definition of children (Foo or Bar) from the parent defintion, both definitions return to the same stage of parent (in below example `ParentDefinitionStages.WithCreateState`) once attach() is called.

##### Parent Stages

```java
interface ParentDefinitionStages {
  interface WithChildResource {
     ChildDefintionStages.WithFooBlank<WithCreateState> defineChildResourceFoo(String name);
     ChildDefintionStages.WithBarBlank<WithCreateState> defineChildResourceBar(String name);
  }

  interface WithCreateState {
  }
}
```

##### Child stages

```java
interface ChildDefintionStages {
  interface WithFooBlank<Parent> {
    ChildDefintionStages.WithAttach<Parent> withPropertyX(value);  
  }

  interface WithBarBlank<Parent> {
    ChildDefintionStages.WithAttach<Parent> withPropertyY(value);  
  }

  interface WithAttach<Parent> extends Attachable.InDefintion<ParentT> {
  }
}
```

##### Entierity of Child stages

```java
interface DefintionFoo<ParentT> 
    extends 
        ChildDefintionStages.WithFooBlank<Parent>, 
        ChildDefintionStages.WithAttach<Parent> {
}

interface DefintionBar<ParentT> 
    extends 
        ChildDefintionStages.WithBarBlank<Parent>, 
        ChildDefintionStages.WithAttach<Parent> {
}
```

##### Child impl

```java
FooBarChildResourceImpl 
	extends 
		DefintionFoo<ParentDefinitionStages.WithCreateState>
		DefintionBar<ParentDefinitionStages.WithCreateState> {}
```

Both `DefintionFoo<T1>` and `DefintionBar<T2>` derive from `Attachable.InDefintion<T>`. In the `FooBarChildResourceImpl` both T1 and T2 are same `ParentDefinitionStages.WithCreateState`.
i.e. the type argument of Attachable.InDefinition<ParentT> is `WithCreateState`.

#### What we want (in addition to above): 

Now consider the following setup, where different fork of child resource definition return to different stage in the parent (`ParentDefinitionStages.WithChildResourceFooAndCreate` and `ParentDefinitionStages.WithChildResourceBarAndCreate` )

##### Parent Stages

```java
interface ParentDefinitionStages {
  interface WithFooOrBar {
    WithChildResourceFoo withFoo();
    WithChildResourceBar withBar();
  }
  
  interface WithChildResourceFooAndCreate extends WithCreate {
     ChildDefintionStages.WithFooBlank<WithChildResourceFooAndCreate> defineChildResourceFoo(String name);
  }

  interface WithChildResourceBarAndCreate extends WithCreateState {
     ChildDefintionStages.WithBarBlank<WithChildResourceBarAndCreate> defineChildResourceBar(String name);
  }

  interface WithCreate {
    Parent create();
  }
}
```

##### Child stages

```java
interface ChildDefintionStages {
  interface WithFooBlank<Parent> {
    WithFooAttach<Parent> withPropertyX(value);  
  }

  interface WithBarBlank<Parent> {
    WithBarAttach<Parent> withPropertyY(value);  
  }

  interface WithFooAttach<Parent> extends Attachable.InDefinition<ParentT> {
  }

  interface WithBarAttach<Parent> extends Attachable.InDefinition<ParentT> {
  }
}
```

##### Entierity of Child stages

```java
interface DefintionFoo<ParentT> extends WithFooBlank<Parent>, WithFooAttach<Parent> {
}

interface DefintionBar<ParentT> extends WithBarBlank<Parent>, WithBarAttach<Parent> {
}
```

##### Child impl

When we try to implement the child resource as below:

```java
FooBarChildResourceImpl 
	extends 
		DefintionFoo<ParentDefinitionStages.WithChildResourceFooAndCreate>
		DefintionBar<ParentDefinitionStages.WithChildResourceBarAndCreate> {}
```

This usage result in compile time error, due to implementing Attachable.InDefinition interface with two different type arguments `Attachable.InDefinition<ParentDefinitionStages.WithChildResourceFooAndCreate>` and  `Attachable.InDefinition<ParentDefinitionStages.WithChildResourceBarAndCreate>`

#### Proposal

To handle these type of forks, proposal is to define different inner interfaces in Attachable for different forks.

```java
interface Attachable {
  // Current inner interfaces
 ...

  // new inner interfaces (definitions)

  interface InDefinitionFork1<ParentT> {
    ParentT attach();
  }

  interface InDefinitionFork2<ParentT> {
    ParentT attach();
  }

  interface InDefinitionFork3<ParentT> {
    ParentT attach();
  }

  interface InDefinitionFork4<ParentT> {
    ParentT attach();
  }

  interface InDefinitionFork5<ParentT> {
    ParentT attach();
  }

  ...
}
```

With this child stages can be redefined as:

```java
interface ChildDefintionStages {
  interface WithFooBlank<Parent> {
    WithFooAttach<Parent> withPropertyX(value);  
  }

  interface WithBarBlank<Parent> {
    WithBarAttach<Parent> withPropertyY(value);  
  }

  interface WithFooAttach<Parent> extends Attachable.InDefinitionFork1<ParentT> {
  }

  interface WithBarAttach<Parent> extends Attachable.InDefinitionFork2<ParentT> {
  }
}
```

**Comment by anuchandy** [comment]
@martinsawicki @jianghaolu This is a problem that @hovsepm encountered while implementing CDN profile and endpoints. // cc @anudeepsharma

**Comment by jianghaolu** [comment]
I encountered something similar and have an implementation in my latest PR.

**Comment by martinsawicki** [comment]
simple solution could be to have a base abstract child impl which has all the common settings between the two child types and derive concrete (and mostly empty) child impls from that for each flavor of the child. Have those derived impls implement the different flavors of `WithAttach<ParentT`. But even `.attach()` itself can still be implemented on that base child class.

Example: 
Suppose `ParentY` and `ParentX` are the two different stages we want the `.attach()` to return to depending on the child type. Then the `WithAttach` flavors would be:

```java
    interface WithAttachX extends WithAttach<ParentStageX> {
        WithAttachX withWhatever();
    }
    
    interface WithAttachY extends WithAttach<ParentStageY> {
        WithAttachY withWhatever();
    }
```
So the impls could simply be:

```java
    abstract class ChildBaseImpl<ParentT, ImplT> {
        public ParentT attach() {
            return (ParentT) parent;
        }
        
        @SuppressWarnings("unchecked")
        public ImplT withWhatever() {
            return (ImplT) this;
        }

        class ChildXImpl extends ChildBaseImpl<ParentStageX, ChildXImpl> implements WithAttachX {}
        class ChildYImpl extends ChildBaseImpl<ParentStageY, ChildYImpl> implements WithAttachY {}
    }
```

**Comment by martinsawicki** [comment]
issue closed
