### ISSUE TITLE
Azure Tables Sprint 3

### ISSUE THREAD

**Issue by eboyd23** [Azure/azure-sdk-for-java#12707]

**Comment by horns-k** [comment]
Given that only alternative right now for Table API connections for CosmosDB and Azure Table Storage is using v8 of the SDK, which is also formally declared as Legacy, is there a more concrete estimate / planning commitment for having this released?

**Comment by eboyd23** [comment]
Hello! Thank you for your interest in this SDK. We are planning on August but this is only an estimate so we will keep you posted about how development progresses.
