### ISSUE TITLE
Numerous Tests Failing due to FeatureNotEnabled

### ISSUE THREAD

**Issue by alzimmermsft** [Azure/azure-sdk-for-java#12710]
Multiple tests began failing on 2020-07-01 with `FeatureNotEnabled` exceptions. Previously, these tests were passing without issue.

Is this an issue with the Storage account being used in testing? My concern is if these APIs would begin failing when used with older Storage accounts that don't have this feature enabled, effectively being a breaking change causing an upgrade in Storage account features (unless this feature is enabled by default).

```java
Status code 400, "<Error>FeatureNotEnabled<Message>A required feature for this operation is not enabled on the account.
RequestId:a3bbfa1d-c01e-003f-2bae-4f574e000000
Time:2020-07-01T13:47:24.4901152Z</Message><FeatureName>BlobIndex</FeatureName></Error>"
```

**Comment by gapra-msft** [comment]
This issue is due to our subscription not having these features enabled. Working on getting most of the live tests for STG 73 features to pass here. https://github.com/Azure/azure-sdk-for-java/pull/12728

**Comment by alzimmermsft** [comment]
This has been fixed.
