### ISSUE TITLE
DocumentBulkExecutor support for bulk delete and update

### ISSUE THREAD

**Issue by kushagraThapar** [Azure/azure-sdk-for-java#12719]
https://github.com/microsoft/spring-data-cosmosdb/issues/407

**Comment by kushagraThapar** [comment]
New bulk / batch APIs are being built currently by IDC team (India) - which will expose these APIs in Cosmos. Once they are present in cosmos SDK, then azure-spring-data-cosmos can use them in its implementation.
Timeline is end of this semester.

**Comment by kushagraThapar** [comment]
Given Bulk / Batch / Patch is going to GA soon, we can have the support in spring-data-cosmos

**Comment by mrabhishek** [comment]
Any timeline on when this will be available?

**Comment by kushagraThapar** [comment]
@mrabhishek  - it is currently not in plan for this semester, should be available sometime early next year.

**Comment by bhattacharyyasom** [comment]
@kushagraThapar  Is the Bulk Operation support available yet in spring-data-cosmos ?
I have a need for the same.

**Comment by kushagraThapar** [comment]
@bhattacharyyasom - it is in our backlog now, prioritizing it for our next semester. We plan to deliver it in next couple of months.

**Comment by kushagraThapar** [comment]
cc - @trande4884

**Comment by kushagraThapar** [comment]
This is done.
