### ISSUE TITLE
deadLetterQueue not working 

### ISSUE THREAD

**Issue by Dipanshu007** [Azure/azure-sdk-for-java#1271]
Hello I tried to access deadLetterQueue using java api but its throwing null pointer exception.

ServiceBusContract service = ServiceBusService.create(config);
..
..
..
ReceiveMessageOptions RECEIVE_AND_DELETE_60_SECONDS = new ReceiveMessageOptions().setReceiveAndDelete().setTimeout(60);

ReceiveQueueMessageResult resultQM = service.receiveQueueMessage("queueName/$DeadLetterQueue",RECEIVE_AND_DELETE_60_SECONDS);

Please let me know how to do it if possible.

**Comment by martinsawicki** [comment]
the ServiceBus SDK is here: https://github.com/azure/azure-service-bus-java
