### ISSUE TITLE
IgnoreCase and AllIgnoreCase don't appear to function properly

### ISSUE THREAD

**Issue by kushagraThapar** [Azure/azure-sdk-for-java#12721]
https://github.com/microsoft/spring-data-cosmosdb/issues/362

**Comment by kushagraThapar** [comment]
@mkaczor we have a PR out - can you please take a look ?

**Comment by mkaczor** [comment]
@kushagraThapar looks good to me

**Comment by kushagraThapar** [comment]
This has been fixed and will be released with azure-spring-data-cosmos preview release v3.0.0-beta.1
