### ISSUE TITLE
Is azure-spring-boot-starter-active-directory on Maven Central?

### ISSUE THREAD

**Issue by justbert** [Azure/azure-sdk-for-java#12755]
I'm trying to get the azure-spring-boot-starter-active-directory artifact, however I can't seem to find it in Maven Central. Am I missing something?

https://repo1.maven.org/maven2/com/azure/

**Comment by justbert** [comment]
Aha! Found the issue. The [docs](https://github.com/Azure/azure-sdk-for-java/blob/master/sdk/spring/azure-spring-boot-starter-active-directory/README.md#add-maven-dependency) point to **com.azure** as the groupId instead of **com.microsoft.azure**.

**Comment by chenrujun** [comment]
@justbert , Thank you very much for your work, I'll close this issue.
