### ISSUE TITLE
Flaky Test lroTimeout

### ISSUE THREAD

**Issue by alzimmermsft** [Azure/azure-sdk-for-java#12786]
Azure Core Management has a test `LROPollerTests.lroTimeout` which sporadically fails. This forces pipelines to re-run.

```java
org.opentest4j.AssertionFailedError: expected: <5> but was: <6>
	at com.azure.core.management@1.0.0-beta.2/com.azure.core.management.implementation.polling.LROPollerTests.lroTimeout(LROPollerTests.java:477)

org.opentest4j.AssertionFailedError: expected: <4> but was: <5>
	at com.azure.core.management@1.0.0-beta.2/com.azure.core.management.implementation.polling.LROPollerTests.lroTimeout(LROPollerTests.java:477)
```

**Comment by JimSuplizio** [comment]
@ChenTanyi 
This is something that needs to be fixed sooner rather than later. Today it was impacting releases. Also, the CODEOWNERS really needs to be updated.

**Comment by ChenTanyi** [comment]
@JimSuplizio I'll see the test right now. @weidongxu-microsoft Please also take a look at it for the test.

**Comment by ChenTanyi** [comment]
@alzimmermsft @JimSuplizio Could you show how you run the test? I have reinstalled and tested it in IntelliJ with success (Java 11).
![image](https://user-images.githubusercontent.com/15213781/86424507-57030500-bd15-11ea-9f70-d3e62f6759af.png)

**Comment by weidongxu-microsoft** [comment]
That assertion had a bit dependency on timing within the test, I will disable it. https://github.com/Azure/azure-sdk-for-java/pull/12793

**Comment by ChenTanyi** [comment]
@alzimmermsft Will it be able to continue release the azure-core-management? Thanks! (I saw the other PR of azure-core version bump, not sure it matter the core-management release or not)

**Comment by alzimmermsft** [comment]
@ChenTanyi `azure-core-management` will continue to be able to be released. These type of issues just make releasing a little more difficult as pipelines need to pass and random test failures will force re-runs, just making it more time consuming.
