### ISSUE TITLE
[QUERY] create and fetch the secrets stored in KV behind corp network

### ISSUE THREAD

**Issue by ashwinnatty** [Azure/azure-sdk-for-java#12792]
**Query/Question**
Does the azure key vault Java SDK have provision to connect via a proxy?

***Why is this not a Bug or a feature Request?***
I tried the sample on an open internet and i was able to successfully use the SDK. Whereas when i was behind my corporate firewall, it gave an "UnknownHostException" . Tried searching for ways to set up proxy But in vain. Hence decided to get it clarified here

**Setup (please complete the following information if applicable):**
 - OS: Windows 10
 - IDE : Eclipse
 - Latest

**Comment by yungezz** [comment]
hi @ashwinnatty could you pls be specific what operations you'd like to achieve? To create a Keyvault or using keyvault?  thanks.

**Comment by ashwinnatty** [comment]
I tried the Java SDK to create and fetch the secrets stored in KV. Trying to understand how I need to achieve the same behind a corporate firewall. Is there a way to set the proxy ? Kindly throw some light. Thanks a lot.

**Comment by yungezz** [comment]
thanks @ashwinnatty for the info. HI @joshfree could you pls take care of this? thanks.

**Comment by Petermarcu** [comment]
@ashwinnatty can you confirm the name and version of the KeyVault library you are using?

**Comment by ashwinnatty** [comment]
4.1.2 is the version of library

**Comment by vcolin7** [comment]
Hi @ashwinnatty,

You can configure a proxy for the Azure SDK clients by creating a new `HttpClient` that includes the desired proxy options and giving it to the `SecretClientBuilder`:

- For Netty:
    ```java
    HttpClient nettyClient = new NettyAsyncHttpClientBuilder()
        .proxy(new ProxyOptions(ProxyOptions.Type.HTTP, new InetSocketAddress("<host-address>", <port>)))
        .build();

    SecretClient secretClient = new SecretClientBuilder()
        .vaultUrl("<your-key-vault-url>")
        .credential(new DefaultAzureCredentialBuilder().build()) // You can use other types of authentication too
        .httpClient(nettyClient)
        .buildClient();
    ```

- For OkHttp:
    ```java
    HttpClient okHttpClient = new OkHttpAsyncHttpClientBuilder()
        .proxy(new ProxyOptions(ProxyOptions.Type.HTTP, new InetSocketAddress("<host-address>", <port>)))
        .build();

    SecretClient secretClient = new SecretClientBuilder()
        .vaultUrl("<your-key-vault-url>")
        .credential(new DefaultAzureCredentialBuilder().build()) // You can use other types of authentication too
        .httpClient(okHttpClient)
        .buildClient();
    ```

Hope this solves your problem and sorry for the late reply. Don't hesitate about contacting me if there's anything else I can be of help with :)

**Comment by sjain3097** [comment]
How to figure out what proxy to use and where to find it?

**Comment by vcolin7** [comment]
Hi @sjain3097, here's [our documentation](https://docs.microsoft.com/en-us/azure/developer/java/sdk/proxying) on how to use different types of proxies and their characteristics.
