### ISSUE TITLE
Remaining issues before GA

### ISSUE THREAD

**Issue by sima-zhu** [Azure/azure-sdk-for-java#12790]
* IndexDocumentsBatch:
1. remove varargs
2. Remove constructor overload that takes a list of actions and add addActions(Iterable<IndexAction<T>> actions)
* Varargs or Iterable for setters:
1. Input models can just have varargs
2. Input-ouput models should have both overloads - varargs and List<T>
* Model builders:
1. Remove SimpleFieldBuilder, SearchableFieldBuilder and ComplexFieldBuilder 
2. Re-implement the SimpleField, SearchableField and ComplexField.

**Comment by alzimmermsft** [comment]
Removing varargs and constructor in `IndexDocumentsBatch` is being resolved in #12791.

**Comment by alzimmermsft** [comment]
Changes to `SearchField` building is being resolved in #12796.

**Comment by alzimmermsft** [comment]
Updating models to use varargs instead of `List` in some scenarios is being explored in #12878.

**Comment by sima-zhu** [comment]
Closed as all issues listed have been addressed.
