### ISSUE TITLE
Java library for CosmosDb + private endpoint support

### ISSUE THREAD

**Issue by jagadish-v0** [Azure/azure-sdk-for-java#12813]
Created a private endpoint for my CosmosDb storage account and trying to connect to the CosmosDb through it. I'm getting a ConnectTimeOutException..

```
io.netty.channel.ConnectTimeoutException: connection timed out: cosmos-account-41895-eastus.documents.azure.com/10.3.168.11:21226
```

If I try to connect to the CosmosDb account using the azure cli from the same machine, it works fine.

```
az cosmosdb sql database create --account-name cosmos-account-41895 --name testdb --resource-group rg-name
```

If I try to connect to the account using a service endpoint (instead of using a private endpoint), that works fine too.

For context, I'm using the java library: com.azure:azure-cosmos:4.0.1-beta.1. Does the Java client support private endpoints yet?

**Comment by jagadish-v0** [comment]
For reference, @kushagraThapar recommended that I created the issue here when I opened an issue in https://github.com/Azure/azure-cosmosdb-java/issues/346.

**Comment by kushagraThapar** [comment]
@jagadish-v0 - continuing the conversation here : 

I misunderstood the private endpoint feature, here is what I found in the docs: 
https://docs.microsoft.com/en-us/azure/private-link/create-private-endpoint-cosmosdb-portal?toc=/azure/cosmos-db/toc.json&bc=/azure/cosmos-db/breadcrumb/toc.json

As the docs mention, you can connect to private endpoints using a VM created specifically for the private endpoint Cosmos account through Data Explorer. Were you able to do that ?

Meanwhile, I will get more information on how to connect it through SDK.

**Comment by kushagraThapar** [comment]
@jagadish-v0 - were you able to connect the way I mentioned above ?
Which connection mode are you using to connect to private endpoints, DIRECT or GATEWAY ?
