### ISSUE TITLE
Add README.md for spring-data-cosmosdb project

### ISSUE THREAD

**Issue by yiliuTo** [Azure/azure-sdk-for-java#12812]
In order to pass pipeline, the README.md is emptied temporarily. This would be restored after the Javadoc issue that Javadoc plugin checking cannot recognize annotation symbol in README.md is fixed.

**Comment by saragluna** [comment]
Same for the `spring-data-gremlin` README.md.

**Comment by hemanttanwar** [comment]
We can close this
