### ISSUE TITLE
Analytical storage(cosmos sample) issue

### ISSUE THREAD

**Issue by Melanie-Ma** [Azure/azure-sdk-for-java#12811]
Section [Link](https://github.com/Azure/azure-sdk-for-java/blob/master/sdk/cosmos/azure-cosmos/src/samples/java/com/azure/cosmos/AnalyticalStorageCodeSnippet.java#L23):
![image](https://user-images.githubusercontent.com/64007802/86549374-0b996280-bf72-11ea-9c43-1ed38837f47d.png)
Reason:
![image](https://user-images.githubusercontent.com/64007802/86549384-1522ca80-bf72-11ea-9e94-6f4cfd938c0b.png)
Suggestion:
Remove this code: `cosmosContainerProperties.setAnalyticalStoreTimeToLiveInSeconds(-1);`

**Comment by Melanie-Ma** [comment]
@jongio,  for notification.

**Comment by moderakh** [comment]
It is not an issue in the SDK. you need to enable the feature on the service side before attempting to use it.
@srchi is the PM who can help on enabling analytical store in the account.

**Comment by Melanie-Ma** [comment]
@moderakh - I have enabled the feature on the service side and the sample worked. Can we add some comments like this :
You should refer to this [link ](https://docs.microsoft.com/en-us/azure/cosmos-db/configure-synapse-link#create-analytical-ttl) to enable the feature on the service side before setting the param 'TimeToLive'. What's more, I found that  setting this parameter `TimeToLiveI`does not work in the Track2 package, but in Track1 package. Please refer to the [issue](https://github.com/Azure/azure-sdk-for-java/issues/12862).
