### ISSUE TITLE
Create Load Balancer for only NAT

### ISSUE THREAD

**Issue by paulojohnj** [Azure/azure-sdk-for-java#1283]
Mechanism to create a load balancer with frontend, backend and NAT rules, but no probe or load balancing rule(s). This type of load balancer can be created from the portal but appears to only be create-able in the SDK by creating LB with probe and LB rules, and then updating to remove.

Update: it appears the LB probe and load balancing rule cannot be removed (updated to without that rule or probe) if they are the last rule or probe ( though the update returns with success)

**Comment by paulojohnj** [comment]
Update: it appears the LB probe and load balancing rule cannot be removed (updated to without that rule or probe) if they are the last rule or probe ( thought the update returns with success)

**Comment by antonio-rodriges** [comment]
I think this issue must be reopened: it should be possible to create LoadBalancer only with NAT rules and without actually load balancing
