### ISSUE TITLE
Remove the unnecessary intermediate parent/aggregator in sdk/spring/azure-spring-boot-tests/pom.xml

### ISSUE THREAD

**Issue by JimSuplizio** [Azure/azure-sdk-for-java#12868]
[sdk/spring/azure-spring-boot-tests/pom.xml](https://github.com/Azure/azure-sdk-for-java/blob/master/sdk/spring/azure-spring-boot-tests/pom.xml) is setup as both a parent and aggregator pom. First, there should be no superfluous parent poms. This causes problems with tooling and verification which looks, specifically, at parents. Second, everything building for a given area needs to be in that area's sdk/**area**/pom.xml. While there's still the ongoing question of the subdirectory, that does not change what needs to get done here.

1. com.microsoft.azure:azure-spring-boot-tests needs to be removed from version_client.txt
2. Every one of these test libraries under azure-spring-boot-tests needs to have azure-sdk-client-parent as its parent, needs to have a groupId and version as none of the libraries parenting off of azure-spring-boot-tests had one.
3. Every library that was previously parented by azure-spring-boot-tests needs to be added to version_client. The current and dependency versions of these library should be the same. These libraries are similar to com.azure:perf-test-core, they're test only and not shipping, there shouldn't be different dependency/current versions as no other library outside of sdk/spring should ever be taking dependencies on them.
4. Every library needs to be added to the module list of sdk/spring/pom.xml. If, at the time, these are still in the azure-spring-boot-tests subdirectory then the module entry in sdk/spring/pom.xml will have <module>azure-spring-boot-tests/**LibraryName**</module>
5. You will have to move the following property from azure-spring-boot-tests/pom.xml into the individual pom files, that was only thing this intermediate parent provided outside of aggregation
`  <properties>
    <skipSpringITs>true</skipSpringITs>`

**Comment by saragluna** [comment]
Removed.
