### ISSUE TITLE
License header missing in some DNS java files

### ISSUE THREAD

**Issue by jianghaolu** [Azure/azure-sdk-for-java#1286]
e.g.
https://github.com/Azure/azure-sdk-for-java/blob/master/azure-mgmt-dns/src/main/java/com/microsoft/azure/management/dns/DnsRecordSet.java
https://github.com/Azure/azure-sdk-for-java/blob/master/azure-mgmt-dns/src/main/java/com/microsoft/azure/management/dns/DnsZone.java

etc.

Also some in resources:
https://github.com/Azure/azure-sdk-for-java/blob/master/azure-mgmt-resources/src/main/java/com/microsoft/azure/management/resources/fluentcore/arm/collection/implementation/ExternalChildResourceCollectionImpl.java
https://github.com/Azure/azure-sdk-for-java/blob/master/azure-mgmt-resources/src/main/java/com/microsoft/azure/management/resources/fluentcore/arm/collection/implementation/ExternalChildResourcesNonCachedImpl.java

**Comment by anuchandy** [comment]
This is done as part of above PR, closing.
