### ISSUE TITLE
Remove the unnecessary intermediate parent/aggregator in sdk/spring/azure-spring-boot-samples/pom.xml

### ISSUE THREAD

**Issue by JimSuplizio** [Azure/azure-sdk-for-java#12869]
[sdk/spring/azure-spring-boot-samples/pom.xml](https://github.com/Azure/azure-sdk-for-java/blob/master/sdk/spring/azure-spring-boot-samples/pom.xml) is setup as both a parent and aggregator pom. First, there should be no superfluous parent poms. This causes problems with tooling and verification which looks, specifically, at parents. Second, everything building for a given area needs to be in that area's sdk/area/pom.xml. While there's still the on going question of the subdirectory, that does not change what needs to get done here.

The spring samples are special in that they need the [spring-boot-starter-parent](https://github.com/Azure/azure-sdk-for-java/blob/master/sdk/spring/azure-spring-boot-samples/pom.xml#L7), which is BOM, and they should be parenting off this directly. [There's tooling that's been created to deal with this special case that also had to deal with the special case of the superfluous parent](https://github.com/Azure/azure-sdk-for-java/pull/12784). Since that's still in PR I'd like this change to go in so I can update that to look for the spring-boot-starter-parent directly. 

Each of the modules in [azure-spring-boot-samples](https://github.com/Azure/azure-sdk-for-java/blob/master/sdk/spring/azure-spring-boot-samples/pom.xml#L64) should be directly referenced in the modules in the area pom file [sdk/spring/pom.xml](https://github.com/Azure/azure-sdk-for-java/blob/master/sdk/spring/pom.xml#L11)

**Comment by jialindai** [comment]
hi @JimSuplizio, to make sure I understand correctly, you are suggesting:

- Remove /sdk/spring/azure-spring-boot-samples/pom.xml
- Make each sample project's pom parent directly from org.springframework.boot:spring-boot-starter-parent

I think we can do the above. 

I am not very clear about your suggestion on folder structure here.

**Comment by JimSuplizio** [comment]
@jialindai there is no suggestion as of yet for folder structure as that discussion is still ongoing. My comment was that this work does not depend on that.

**Comment by saragluna** [comment]
Removed.
