### ISSUE TITLE
[Cosmos] CosmosContainerProperties.setAnalyticalStoreTimeToLiveInSeconds not working

### ISSUE THREAD

**Issue by Melanie-Ma** [Azure/azure-sdk-for-java#12862]
Run this code:
` CosmosAsyncClient client = new CosmosClientBuilder().endpoint(TestConfigurations.HOST)
                .key(TestConfigurations.MASTER_KEY).buildAsyncClient();
        client.createDatabaseIfNotExists(DATABASE_NAME).block();
        CosmosContainerProperties cosmosContainerProperties = new CosmosContainerProperties(CONTAINER_NAME, "/id");
        cosmosContainerProperties.setAnalyticalStoreTimeToLiveInSeconds(0);
        client.getDatabase(DATABASE_NAME).createContainer(cosmosContainerProperties).block();
        client.close();`

I have set the value of the parameter 'TimeToLive' ` cosmosContainerProperties.setAnalyticalStoreTimeToLiveInSeconds(0); `to -1. However, as the pictures show, the setting of ‘Time to live’ on the portal is not consistent with the value of - 1 shown on the [document](https://docs.microsoft.com/en-us/azure/cosmos-db/how-to-time-to-live?tabs=dotnetv2%2Cjavav3):
![image](https://user-images.githubusercontent.com/64007802/86733741-06b4db80-c064-11ea-99b2-3d87a5f1ec2c.png)
![image](https://user-images.githubusercontent.com/64007802/86735497-6fe91e80-c065-11ea-9a1f-6625f8eb21fc.png)
What‘s more, I tried to change the package of cosmos from track2 to track1 and set the value of 'TimeToLive' to -1, it worked on the portal.

**Comment by tzhanl** [comment]
@jongio for notification.

**Comment by kushagraThapar** [comment]
@moderakh - can you please take a quick look at this issue ?

**Comment by moderakh** [comment]
This is not SDK issue. Please note:

1. setAnalyticalStoreTimeToLiveInSeconds controls Analytical Store Time to Live not Time To Live.
2. when you create a container you should set the correct value at the creation time, setting the ttl in the response won't do anything.

Issue can be closed from SDK perspective.

@anfeldma-ms our PM to follow up with the user/customer.

**Comment by anfeldma-ms** [comment]
Melanie - as Mo pointed out, setAnalyticalStoreTimeToLiveInSeconds() is not a feature that applies to your Cosmos DB container. We actually have another service called Synapse Analytical Store, which can be set up to automatically sync data from your Cosmos DB container. setAnalyticalStoreTimeToLiveInSeconds() is setting the TTL for data in the analytical store that is sync'd from Cosmos DB; it is not setting TTL for Cosmos DB itself.

Just in case it is helpful, I will clarify how TTL works in Cosmos DB. You can configure TTL at the container level, or the item level. An item can have a TTL if you give it a "ttl" field specifying a number of seconds. However, even if you add a TTL field, TTL will only be enforced on items if TTL is enabled on the container. Additionally, when TTL is enabled on a container, containers can optionally be configured with a default item TTL which is applied to items that do not have a TTL field - however, if you add a TTL field to an item, that still takes precedence over the container default TTL.

So with that in mind, here are the config options for TTL:

1. containerProperties.setDefaultTimeToLiveInSeconds(null) will disable TTL on a container (portal shows "TTL off"). This means items have no TTL even if you add a TTL field. 

2. containerProperties.setDefaultTimeToLiveInSeconds(-1) will enable TTL on a container (portal shows "TTL on") with no default TTL. This means documents with TTL field will have TTL enforced.

3. containerProperties.setDefaultTimeToLiveInSeconds(<some int>) will enable TTL on a container and make <some int> the default item TTL (portal shows "TTL on" and lists the default TTL). This means items have a default TTL of <some int> unless you explicitly add a TTL field

So the key is that you want to be using the containerProperties.setDefaultTimeToLiveInSeconds() method, not the analytical store TTL method.

I will clarify/correct this in the docs.

**Comment by anfeldma-ms** [comment]
Sorry, my last comment had a typo - option #3 should have read as follows

3. containerProperties.setDefaultTimeToLiveInSeconds(some_integer) will enable TTL on a container and make the default item TTL some_integer (portal shows "TTL on" and lists the default TTL). This means items have a default TTL of some_integer unless you explicitly add a TTL field

**Comment by Melanie-Ma** [comment]
@anfeldma-ms - Thank you for your explanation，I will close the issue.
