### ISSUE TITLE
[QUERY] How to get all partition information available for an EventHub?

### ISSUE THREAD

**Issue by moarychan** [Azure/azure-sdk-for-java#12900]
**Query/Question**
How to get all partition information available for an EventHub？

I want to customize the event position for each partition. I will process this mapping before creating com.azure.messaging.eventhubs.EventProcessorClientBuilder object, these mapping relationships are intended to be passed to 
Map<String, EventPosition> initialPartitionEventPosition. Thanks

**Setup (please complete the following information if applicable):**
 - IDE : IntelliJ
 - Version of the Library used com.azure:azure-messaging-eventhubs:5.0.2
 
 **Information Checklist**
 Kindly make sure that you have added all the following information above and checkoff the required fields otherwise we will treat the issuer as an incomplete report
- [ ] Query Added
- [ ] Setup information Added

**Comment by srnagar** [comment]
@moarychan here's a sample that demonstrates how to get partition ids from Event Hubs.

https://github.com/Azure/azure-sdk-for-java/blob/master/sdk/eventhubs/azure-messaging-eventhubs/src/samples/java/com/azure/messaging/eventhubs/GetEventHubMetadata.java

**Comment by moarychan** [comment]
@srnagar thank you.
