### ISSUE TITLE
Network from VirtualMachine

### ISSUE THREAD

**Issue by davidbairdala** [Azure/azure-sdk-for-java#1294]
Is it possible to get the Network (VNET) and subnet for a virtual machine?

For example, the following groovy code...
```Groovy
azure.virtualMachines().list().each { VirtualMachine vm ->
  // Cannot see a way to get the Network or Subnet information for the vm   
}
```
I can see that I can get specific network information, like IP address etc, but cannot seem to link back to the actual network.

Also, is it possible, or would it be possible to query for all virtual machines for a network?

e.g.

```
...
azure.networks().list().each { Network network ->
    def vms = network.listVirtualMachines()
}
```

**Comment by anuchandy** [comment]
The VNET of a VM can be retrieved using:

```java
        VirtualMachine vm = azure.virtualMachines().getByGroup(RG_NAME, VMNAME);
        Network network = vm.getPrimaryNetworkInterface()
                .primaryIpConfiguration()
                .getNetwork();
```

**Comment by davidbairdala** [comment]
Ah! Thankyou - I don't know how I missed that.

Also, before I raise another spurious issue, I can't see a way on the 'VirtualMachine' interface to delete/terminate a VM, although I see it is possible via the REST api docs. Is there a way to terminate a single virtual machine? I guess it's just not where I expect it should be.

**Comment by anuchandy** [comment]
delete is available only in virtual machine collection not in virtual machine. 

```java
azure.virtualMachines()
    .deleteById(vm.id());
```

**Comment by davidbairdala** [comment]
Awesome, thank you!
