### ISSUE TITLE
Read device to cloud messages

### ISSUE THREAD

**Issue by omersalam** [Azure/azure-sdk-for-java#12963]
I am unable to find device to cloud reading messages sketch.
Where i provide endpoint connection string, event hub name and start monitoring the data. 
I am successfully running this in python. But i am unable to find the sketch in java.

**Comment by joshfree** [comment]
Hi @omersalam, thank you for posting the question.

You can find our developer documentation linked from the repos root README.md, which points to https://azure.github.io/azure-sdk-for-java/index.html.

The Event Hub SDK documentation, including examples of how to connect and start consuming events from event hubs is available here: 

https://azuresdkdocs.blob.core.windows.net/$web/java/azure-messaging-eventhubs/5.1.2/index.html 

I'm resolving this issue as closed, but feel free to reactivate or post a new issue if I misunderstood your original question or if you have any new questions/issues, respectively.

Thanks,
Josh
