### ISSUE TITLE
Improve download speeds for Cosmos Emulator

### ISSUE THREAD

**Issue by danieljurek** [Azure/azure-sdk-for-java#12970]
For some reason the Cosmos Emulator is taking a long time to download on Java hosts (>10 minutes) and very little time to download on Python and JS hosts (<1 minute)... These figures are anecdotal and collected from arbitrary samplings of the step run times. 

We've seen several instances where Emulator tests have timed out in Java and have had to increase the timeout.

**Comment by mitchdenny** [comment]
Done, download and start is now combined into one though. But we use the same logic from across Python, JS and Java.
