### ISSUE TITLE
Cosmos Client Builder overrides direct connection config idleConnectionTimeout with gateway connection config

### ISSUE THREAD

**Issue by kushagraThapar** [Azure/azure-sdk-for-java#12971]
This is a bug which popped up in this ICM: https://portal.microsofticm.com/imp/v3/incidents/details/194516399/home

In the below code -> 

```
if (this.directConnectionConfig != null) {

    this.connectionPolicy = new ConnectionPolicy(directConnectionConfig);

    //  Check if the user passed additional gateway connection configuration

    if (this.gatewayConnectionConfig != null) {

        this.connectionPolicy.setMaxConnectionPoolSize(this.gatewayConnectionConfig.getMaxConnectionPoolSize());

        this.connectionPolicy.setRequestTimeout(this.gatewayConnectionConfig.getRequestTimeout());


       //  gateway config overrides direct config right here
        this.connectionPolicy.setIdleConnectionTimeout(this.gatewayConnectionConfig.getIdleConnectionTimeout());

    }
```

If both `directConnectionConfig` and `gatewayConnectionConfig` are present, then idleConnectionTimeout will always be overriden by `gatewayConnectionConfig`

**Comment by allenhumphreys** [comment]
Excellent! Thanks @kushagraThapar

**Comment by kushagraThapar** [comment]
This is done and will be released in 4.2.0 release tentatively next week.

**Comment by allenhumphreys** [comment]
@kushagraThapar It seems that the requestTimeout suffers the same fate.

**Comment by kushagraThapar** [comment]
@allenhumphreys Not really, as requestTimeout is not public API and it is hardcoded internally at 5 seconds.

**Comment by allenhumphreys** [comment]
I see. I didn't realize it wasn't public. Spring properties binding has no problem setting the values 😬. So public or private, I have set the value to 2 seconds. Is that inadvisable?

**Comment by kushagraThapar** [comment]
Hahaha, not really, I think that should be fine - although you are already aware of the fact that requestTimeout only indicates the I/O timeout - so I think 2 seconds should be fine. I don't see a problem with that. 

@moderakh - do you see any issue with Allen setting the requestTimeout to 2 seconds ?

**Comment by moderakh** [comment]
our P99 latency for items of size 1KB is < 10ms however for some corner case scenario (query payload being huge, etc), the server side contract is to respond in 5 seconds, this is the reason the SDK default is 5 seconds.

I don't think this will be hit on the normal path though. You can set it to 2 seconds provided that you are aware of the above.
