### ISSUE TITLE
[BUG] active-directory-groups property is deprecated and yet is required by a @ConditionalOnProperty in ADOAuth2AutoConfiguration

### ISSUE THREAD

**Issue by hamishlawson** [Azure/azure-sdk-for-java#12986]
**Describe the bug**
The `azure.activedirectory.active-directory-groups` property is deprecated, but using the replacement `azure.activedirectory.user-group.allowed-groups` causes an application that makes use of `AADOAuth2AutoConfiguration.oidcUserService()` to fail to start, as [that has a `@ConditionalOnProperty`](https://github.com/Azure/azure-sdk-for-java/blob/e7be51b20f8bdd77dedfc235285e921aa6f9733e/sdk/spring/azure-spring-boot/src/main/java/com/microsoft/azure/spring/autoconfigure/aad/AADOAuth2AutoConfiguration.java#L55) that requires the deprecated property.

***Exception or Stack Trace***
```
***************************
APPLICATION FAILED TO START
***************************
Description:
Field oidcUserService in com.microsoft.azure.aad.security.AADOAuth2LoginSecurityConfig required a bean of type 'org.springframework.security.oauth2.client.userinfo.OAuth2UserService' that could not be found.
The injection point has the following annotations:
	- @org.springframework.beans.factory.annotation.Autowired(required=true)
The following candidates were found but could not be injected:
	- Bean method 'oidcUserService' in 'AADOAuth2AutoConfiguration' not loaded because @ConditionalOnProperty (azure.activedirectory.active-directory-groups) did not find property 'active-directory-groups'
```

**Comment by einue** [comment]
I have the same issue!

**Comment by joshfree** [comment]
@jianghaolu could you please take a look?

**Comment by saragluna** [comment]
It looks like a Spring AAD issue, @hamishlawson are you using the `azure-active-directory-spring-boot-starter`?

**Comment by hamishlawson** [comment]
Yes. I discovered it while playing with the `azure-spring-boot-sample-active-directory-backend` sample.

**Comment by saragluna** [comment]
@hamishlawson I will look into it.
