### ISSUE TITLE
route table / route / subnet association

### ISSUE THREAD

**Issue by paulojohnj** [Azure/azure-sdk-for-java#1299]
Is there a path for managing route table / routes and their subnet association in beta3 ? The SDK points for route table creation, route management and subnet association in beta4 are great and are working perfectly. However, since I am currently required to use released or final code as dependencies, is there any way to manage these same things via beta3 or interaction with an ARM template (don't believe ARM templates allow for update only deploy)

**Comment by martinsawicki** [comment]
not easily - there may be a workaround via the use of .inner() of the various involved objects, but that approach will get very hairy very quickly.... 
beta4 is coming out in about 1-2 weeks though, so better just wait for that.

**Comment by paulojohnj** [comment]
Ahh beta4 is the answer I was hoping for and needed to know a timeline but was not sure where to ask. Thank you very much for the prompt respond, and I believe an ARM template can be used temporarily in the mean time.
