### ISSUE TITLE
Request Event Hubs Checkpoint Store implement using SQL Database

### ISSUE THREAD

**Issue by tsubasaxZZZ** [Azure/azure-sdk-for-java#13024]
**Is your feature request related to a problem? Please describe.**
I would like to use Checkpoint Store with SQL Database as backend.

**Describe the solution you'd like**
SQL Database is high availability even if use Event Hub as backend.
I would like to implement Checkpoint Store with SQL Database as backend.
I found out using blob storage, and I hope same implementation and sample.
https://github.com/Azure/azure-sdk-for-java/tree/55c23c6c4fe118fca384f0fd10a648569558659f/sdk/eventhubs/azure-messaging-eventhubs-checkpointstore-blob

**Comment by srnagar** [comment]
@tsubasaxZZZ Thank you for reaching out to us and requesting for this feature. We will look into the feasibility of implementing another checkpoint store backed by SQL database.

**Comment by tsubasaxZZZ** [comment]
@srnagar Thank you for your reply. I hope strongly implement this feature. I'm looking forward release!
My big customer would like to use strongly, if you need to know deal information, please contact me(alias: tsunomur).

**Comment by stliu** [comment]
I'm curious about this requirement, why need to use SQL for that kind of  availability (and ACID) for the checkpoint data, which is updated quickly within a high throughput messaging application?

isn't Redis a better choice?

**Comment by srnagar** [comment]
We are adding a checkpointstore backed by Redis. We do not have plans to add a checkpointstore for SQL database at the moment. We'll close this issue and if there's any plans in the future to add SQL DB support, we'll update this issue.
