### ISSUE TITLE
[FEATURE REQ] Add sendFile API to HttpClient

### ISSUE THREAD

**Issue by alzimmermsft** [Azure/azure-sdk-for-java#13099]
Investigate adding an API, or APIs, to `HttpClient` which is used to send a file. Adding this could offer the ability to perform zero copy requests when dealing with files.

**Comment by JonathanGiles** [comment]
@alzimmermsft This could make use of RequestContent?

**Comment by alzimmermsft** [comment]
Yes, right now `RequestContent` supports having a `File` as its content. I think this issue is meant to go a bit further with updating the `HttpClient` implementations to be able to read the `File` to the network directly rather than the current pattern used where it is loaded into heap.

**Comment by alzimmermsft** [comment]
Closing as a `sendFile` API doesn't need to be added to `HttpClient` as this is being handled by passing a `File`-based `BinaryData` request. This is now on to changing the interfacing layer to allow SDKs to pass `BinaryData` instead of only either `Flux<ByteBuffer>` or `InputStream`
