### ISSUE TITLE
[BUG] BlobClient.downloadToFile hangs under concurrent usage

### ISSUE THREAD

**Issue by donfai** [Azure/azure-sdk-for-java#13091]
**Describe the bug**
The BlobClient locks permanently when there is concurrent usage of downloadToFile within the JVM.

I went through the following stages until I arrived at my current working solution, which is to have NO concurrency at all of the Azure SDK.

In all cases below, the BlobContainerClient is created as follows:

`                final BlobContainerClient blobContainerClient = new BlobContainerClientBuilder()
                        .endpoint(azureEndpoint)
                        .sasToken(sasToken)
                        .containerName(containerName)
                        .buildClient();

                return blobContainerClient.getBlobClient(blobName);`

Approaches tried:
1) A long lived BlobContainerClient that produced BlobClient as needed within a Spring application. The BlobContainerClient was used to produce BlobClient as needed for different threads.
2) A BlobContainerClient created PER download which was used to create a single BlobClient. In this case there is no multi threaded access to the BlobContainerClient.
3) A BlobContainerClient created PER download that produces a single BlobClient where all requests are serialized so that there is only a single download via the Azure SDK at a time within the entire JVM.

Investigating a thread dump, I could see that the call to BlobClient.downloadToFile was blocked at the following location:

`com.azure.storage.common.implementation.StorageImplUtils.blockWithOptionalTimeout(StorageImplUtils.java:99)` 

The solution 3 is the  only working solution I have found. Within my application, the download is not the bottle neck so we are able to live with serializing all downloads.

***Exception or Stack Trace***
Add the exception log and stack trace if available

**To Reproduce**

This issue showed up when there was concurrent usage of the Azure SDK. The number of files that could have been downloaded at any given time would have been in the region of 12 to 36. The blob files were sized between 25MB and 60MB.

***Code Snippet***
Add the code snippet that causes the issue.

**Expected behavior**

**Screenshots**

**Setup (please complete the following information):**
Docker image running on a VM in Azure.
uname -a
Linux <hostname> 5.3.0-1031-azure #32~18.04.1-Ubuntu SMP Mon Jun 22 15:27:23 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux

 - Version of the Library used
        <dependency>
            <groupId>com.azure</groupId>
            <artifactId>azure-storage-blob</artifactId>
            <version>12.7.0</version>
        </dependency>

**Additional context**

**Information Checklist**
Kindly make sure that you have added all the following information above and checkoff the required fields otherwise we will treat the issuer as an incomplete report
- [x] Bug Description Added
- [x] Repro Steps Added
- [x] Setup information Added

**Comment by joshfree** [comment]
@gapra-msft @rickle-msft can you please take a look?

**Comment by rickle-msft** [comment]
@donfai Thank you for taking a look. We will look at this shortly

**Comment by rickle-msft** [comment]
Hi, @donfai. I spent some time investigating this today, and I have not yet been able to reproduce the issue. I've been running the following code snippet locally and have seen it complete successfully every time. If you are able to share a project that consistently reproduces the issue, that would go a long way towards us being able to diagnose and resolve the issue.

```
ExecutorService executor = Executors.newFixedThreadPool(25);
        AtomicInteger ai = new AtomicInteger(0);
        for (int i=0; i<35; i++) {
            System.out.println("Submitting " + i);
            executor.submit(() -> {
                System.out.println("Downloading file. Outstanding: " + ai.incrementAndGet());
                String fileName = UUID.randomUUID().toString();
                blob.downloadToFile(fileName);
                System.out.println("Downloaded file. Outstanding: " + ai.decrementAndGet());

                try {
                    //System.out.println("file num: " + fileNum + " " + Files.size(Paths.get(fileName)));
                    Files.delete(Paths.get(fileName));
                } catch (IOException e) {
                    e.printStackTrace();
                }

                //System.out.println("file num: " + fileNum + " " + Files.exists(Paths.get(fileName)));
            });
        }

        executor.shutdown();
        executor.awaitTermination(10, TimeUnit.MINUTES);
```

**Comment by donfai** [comment]
Hi @rickle-msft,

From your code snippet above, it's not clear what blob file you are downloading, what size it is and whether that file even exists on Azure storage.

`String fileName = UUID.randomUUID().toString();
blob.downloadToFile(fileName);`

The use of UUID gives me the impression that there is no real file in your code attempting to reproduce.

From my description I said that the files are 25MB to 60MB in size and that between 12 to 36 can be downloaded at a time. 
In my app, there is a long running application that is mulithreaded. The app is processing messages. When a message is being processed it may download between 1 to 3 files, process them and then repeat that process up to 60 more times. Within the app when the locking of the Azure SDK happens, there was 12 such processes running concurrently.

When the locking happens is variable, it can take a while to occur, but when it does, the thread dump of the JVM shows that my threads are blocked awaiting on the completion of Azure SDK threads, which are blocked at the line location shown above.

**Comment by donfai** [comment]
Hi @rickle-msft,

From your code snippet above, it's not clear what blob file you are downloading, what size it is and whether that file even exists on Azure storage.

It looks to me like you are downloading the same blob from multiple threads. This does not look close to what I described in the description.

From my description I said that the files are 25MB to 60MB in size and that between 12 to 36 can be downloaded at a time. These files are unique and each file is downloaded once and the files are not shared between threads.

In my app, there is a long running application that is mulithreaded. The app is processing messages. When a message is being processed it may download between 1 to 3 files, process them and then repeat that process up to 60 more times. Processing the files before more are downloaded can take between 1 and 20 minutes. Within the app when the locking of the Azure SDK happens, there was 12 such processes running concurrently.

When the locking happens is variable, it can take a while to occur, but when it does, the thread dump of the JVM shows that my threads are blocked awaiting on the completion of Azure SDK threads, which are blocked at the line location shown above.

**Comment by rickle-msft** [comment]
@donfai To fill in some of the gaps, the blob I'm downloading does indeed exist and is 36MB, which is right in the target range.  I'm downloading up to 25 blobs at a time, which is also in the target range for concurrency. 

While it's true I download the same blob every time, the issue is suspected to be on the client side, and to that end it really makes no difference if the blobs are distinct, at least initially. The point is that ~30MB is being processed by the client and written to separate files concurrently. The files on disk are indeed unique to each download operation and not shared between threads. 

In any case, given the complexity of your application, it might be more productive at this point if you could enable debug logging and share those results here. Then we can get more insight into the state of the async/networking stack and continue trying to repro from there. Would that be at all possible.

Thank you as well for the additional information.

**Comment by donfai** [comment]
Hi @rickle-msft,

I want to help but what you have requested will take some effort. I think for a better repo it would be better if you did use distinct blobs that are downloaded concurrently.

I will try to do a repo for you, but it is quite invasive as I need to deploy a temp build to our Azure environment to capture what you asked for. 

I cannot remember for sure whether this issue ever happened when running on my local using Azurite blob storage. For what it's worth, I don't think that it did. My local Azurite contains the same sets of files that are on the actual Azure Blob Storage.

**Comment by rickle-msft** [comment]
@donfai I will try using distinct blobs and get back to you on the results. 

Either a repro or if you could enable logging will be helpful next steps.

**Comment by rickle-msft** [comment]
I have confirmed that using different blobs still does not cause a hang

**Comment by donfai** [comment]
Your test above is short lived. In my description above I described an app that runs for a while and then encounters a problem. This happened repeatedly until it got to the point where the only solution was to serialize all requests through the Azure Blob SDK. I think it's very doubtful you will run into the issue that I described with 35 downloads, as in my experience this issue did not show up so quickly.

**Comment by rickle-msft** [comment]
Ok. I can modify the app to download continuously and see if it hangs after a few hours.

**Comment by donfai** [comment]
Sounds good. I will try reproduce at the end of my day. If it occurs, I'll send the logs.

**Comment by donfai** [comment]
Hi @rickle-msft ,

I was able to reproduce it again last night. I had enabled debug output for package com.azure.storage but none was produced.

This morning there are 6 threads blocked in the same location, here is 1 of them:

`"pool-1-thread-41" #508 prio=5 os_prio=0 tid=0x000055a992a2d000 nid=0x208 waiting on condition [0x00007f0e87fd4000]
   java.lang.Thread.State: WAITING (parking)
	at sun.misc.Unsafe.park(Native Method)
	- parking to wait for  <0x000000008ce37848> (a java.util.concurrent.CountDownLatch$Sync)
	at java.util.concurrent.locks.LockSupport.park(LockSupport.java:175)
	at java.util.concurrent.locks.AbstractQueuedSynchronizer.parkAndCheckInterrupt(AbstractQueuedSynchronizer.java:836)
	at java.util.concurrent.locks.AbstractQueuedSynchronizer.doAcquireSharedInterruptibly(AbstractQueuedSynchronizer.java:997)
	at java.util.concurrent.locks.AbstractQueuedSynchronizer.acquireSharedInterruptibly(AbstractQueuedSynchronizer.java:1304)
	at java.util.concurrent.CountDownLatch.await(CountDownLatch.java:231)
	at reactor.core.publisher.BlockingSingleSubscriber.blockingGet(BlockingSingleSubscriber.java:87)
	at reactor.core.publisher.Mono.block(Mono.java:1678)
	at com.azure.storage.common.implementation.StorageImplUtils.blockWithOptionalTimeout(StorageImplUtils.java:99)
	at com.azure.storage.blob.specialized.BlobClientBase.downloadToFileWithResponse(BlobClientBase.java:556)
	at com.azure.storage.blob.specialized.BlobClientBase.downloadToFile(BlobClientBase.java:487)
	at <my package>.AzureFileRetriever.lambda$downloadBlob$0(AzureFileRetriever.java:99)
	at <my package>.AzureFileRetriever$$Lambda$499/49424685.run(Unknown Source)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)`

**Comment by donfai** [comment]
I noticed that the downloads that blocked happened within 10 minutes of me starting the test and they remained blocked until I checked this morning.
Is there any chance that an initial flurry of requests could have caused some limit to have been exceeded either on client or in Blob Storage? When I started the application I had set up 12 messages to be processed and each would cause a distinct process to start which downloads between 1 and 3 files and processes them at variable speeds until the next set is requested for that process. At application start up all 12 processes would have requested their initial files are roughly the same time, after which time they would spread out as their processing times are variable.
Last night, 6 of the processes completed successfully. After I redeployed the dev branch to Azure this morning, the 6 that were blocked finished successfully.

**Comment by rickle-msft** [comment]
@anuchandy @alzimmermsft Have you guys ever seen reactor or netty freeze up like this? I think I've seen cases of hangs where an exception wasn't handled and it locked up a reactive process, so that could be happening here. Does anything else come to mind for you guys?

@donfai I think it's unlikely you're overwhelming the service and getting throttled. You'd have to really be hammering the service in a way that I don't think downloading three files would, and you'd be seeing 503 errors. That said, it still is possible to be hitting 503 errors (or any other error) or that we aren't handling some other exception correctly. That's also why getting logging up and running here would be helpful, so we can see if any of that is going on.

To enable logging, you also need to set httpLogOptions on the builder for your clients, so maybe if you turn that on we'll be able to see a bit more?

**Comment by donfai** [comment]
Hi @rickle-msft ,

I had tried to turn on logging but I did not know the specific log requirements that you needed. At this time I can't rerun this test unfortunately. 
I'm happy for you to close this as I have a work around and in new services I'm using the async client. If this issue starts happening again I'll turn on that logging and update you then.
Thanks for your time.

**Comment by rickle-msft** [comment]
@donfai That sounds good. I'm sorry we weren't able to diagnose the issue more effectively, but I'm happy you found a work around! Please do let us know if you hit any more issues and we will be happy to help.
