### ISSUE TITLE
[FEATURE REQ] Support URL with multiple query param with same name

### ISSUE THREAD

**Issue by weidongxu-microsoft** [Azure/azure-sdk-for-java#13124]
**Is your feature request related to a problem? Please describe.**
azure-core support for `collectionFormat=multi` in swagger 2.0
https://swagger.io/docs/specification/2-0/describing-parameters/

multi | Multiple parameter instances rather than multiple values. This is only supported for the in: query and in: formData parameters. | foo=value&foo=another_value
-- | -- | --

appplatform service in mgmt SDK requires this.
https://github.com/Azure/azure-rest-api-specs/blob/master/specification/appplatform/resource-manager/Microsoft.AppPlatform/preview/2019-05-01-preview/appplatform.json#L1745-L1756

I think generally speaking, it is a common feature.

**Describe the solution you'd like**
A preliminary decision on whether azure-core would support it, or not. Or maybe I missed an existing solution.

**Describe alternatives you've considered**

**Additional context**

**Information Checklist**
Kindly make sure that you have added all the following information above and checkoff the required fields otherwise we will treat the issuer as an incomplete report
- [x] Description Added
- [ ] Expected solution specified

**Comment by alzimmermsft** [comment]
Hi @weidongxu-microsoft, currently the `RestProxy` layer in `azure-core` will JSON encode the array type and pass that as the query parameter value. It should be relatively simple to verify the query parameter substitution type and if it is a list perform generation as you have mentioned, multiple key-value pairs concatenated with `&`.

Do we know how AutoRest will generate the linked Swagger? Also, do we know how/if other languages are supporting this (.NET, JS/TS, Python)?

CC: @jianghaolu @srnagar @JonathanGiles

**Comment by weidongxu-microsoft** [comment]
I see. Currently if query param is array, it will be serialized to json and send (`["value1","value2"]`).

---

Issue on modelerfour and testserver https://github.com/Azure/autorest.testserver/issues/197

---

Current Java generator is doing `key=value1,value2` (it is csv style, via `JacksonAdapter.serializeList`, which appears not suitable for extension to this case), which is wrong. Python is wrong as well, they are scheduling a fix. Not checked .NET.

Hence the feature request.

**Comment by alzimmermsft** [comment]
@weidongxu-microsoft what is the priority on getting this issue resolved so we can triage it appropriately.

**Comment by weidongxu-microsoft** [comment]
@alzimmermsft 

It is not high priority. The parameter is an optional parameter in appplatform service. And I seldom see other usage like this (for most services, they would use something like odata $filter or $expand, or just take the array in request body).

**Comment by alzimmermsft** [comment]
Resolved by #21203
