### ISSUE TITLE
support get image from VirtualMachineImages API endpoint

### ISSUE THREAD

**Issue by petergardfjall** [Azure/azure-sdk-for-java#1319]
The Java SDK entry point to the virtual machine image management API `com.microsoft.azure.management.compute.VirtualMachineImages` only supports listing of images.

I would like to see the [full API](https://docs.microsoft.com/en-us/rest/api/compute/virtualmachineimages) implemented, or at least a [get](https://docs.microsoft.com/en-us/rest/api/compute/virtualmachineimages#VirtualMachineImages_Get) method to retrieve meta data about a particular image (and, implicitly, find out if it exists).

**Comment by martinsawicki** [comment]
it's all there. See:
- [VirtualMachineImages#getImage(...)](https://github.com/Azure/azure-sdk-for-java/blob/master/azure-mgmt-compute/src/main/java/com/microsoft/azure/management/compute/VirtualMachineImages.java#L28)
- [VirtualMachineImages#publishers()](https://github.com/Azure/azure-sdk-for-java/blob/master/azure-mgmt-compute/src/main/java/com/microsoft/azure/management/compute/VirtualMachineImages.java#L33)
- [VirtualMachinePublisher#offers()](https://github.com/Azure/azure-sdk-for-java/blob/master/azure-mgmt-compute/src/main/java/com/microsoft/azure/management/compute/VirtualMachinePublisher.java#L25)
- [VirtualMachineOffer#skus()](https://github.com/Azure/azure-sdk-for-java/blob/master/azure-mgmt-compute/src/main/java/com/microsoft/azure/management/compute/VirtualMachineOffer.java#L30)
- [VirtualMachineSku#images()](https://github.com/Azure/azure-sdk-for-java/blob/master/azure-mgmt-compute/src/main/java/com/microsoft/azure/management/compute/VirtualMachineSku.java#L35)

**Comment by petergardfjall** [comment]
So it seems, indeed. I guess they've been added after `v1.0.0-beta3`, which is the version I'm using (the latest released version?). 

http://azure.github.io/azure-sdk-for-java/com/microsoft/azure/management/compute/VirtualMachineImages.html

**Comment by martinsawicki** [comment]
I see. Indeed. We're about to release beta4. What's in master right now is practically it.
