### ISSUE TITLE
Upgrade azure-identity msal4j from 1.3 to latest

### ISSUE THREAD

**Issue by joshfree** [Azure/azure-sdk-for-java#13201]
Tracking work item to investigate upgrading from the Jan 2020 (1.3.0) release of msal4j to a later release, which now has additional bug fixes and better support for throttling instructions

https://github.com/AzureAD/microsoft-authentication-library-for-java/blob/dev/changelog.txt

**Comment by joshfree** [comment]
Moving this back to August, per the 1.0.9 release plan

**Comment by g2vinay** [comment]
1.0.9 has been released.
