### ISSUE TITLE
java.lang.NoSuchMethodError: on resource group create

### ISSUE THREAD

**Issue by paulojohnj** [Azure/azure-sdk-for-java#1322]
I received the following error when attempting to create a resource group ( I see the same error via .create() or .createAsync().toBlocking().last() )

INFO   | jvm 1    | 2016/12/09 20:15:02 | java.lang.NoSuchMethodError: com.google.common.reflect.TypeToken.isAssignableFrom(Ljava/lang/reflect/Type;)Z
INFO   | jvm 1    | 2016/12/09 20:15:02 | 	at com.microsoft.rest.Validator.validate(Validator.java:52)
INFO   | jvm 1    | 2016/12/09 20:15:02 | 	at com.microsoft.azure.management.resources.implementation.ResourceGroupsInner.createOrUpdateWithServiceResponseAsync(ResourceGroupsInner.java:473)
INFO   | jvm 1    | 2016/12/09 20:15:02 | 	at com.microsoft.azure.management.resources.implementation.ResourceGroupsInner.createOrUpdateAsync(ResourceGroupsInner.java:445)
INFO   | jvm 1    | 2016/12/09 20:15:02 | 	at com.microsoft.azure.management.resources.implementation.ResourceGroupImpl.createResourceAsync(ResourceGroupImpl.java:120)
INFO   | jvm 1    | 2016/12/09 20:15:02 | 	at com.microsoft.azure.management.resources.fluentcore.model.implementation.CreateUpdateTask.executeAsync(CreateUpdateTask.java:34)
INFO   | jvm 1    | 2016/12/09 20:15:02 | 	at com.microsoft.azure.management.resources.fluentcore.dag.TaskGroupBase.executeAsync(TaskGroupBase.java:79)
INFO   | jvm 1    | 2016/12/09 20:15:02 | 	at com.microsoft.azure.management.resources.fluentcore.model.implementation.CreatableUpdatableImpl.executeTaskGroupAsync(CreatableUpdatableImpl.java:196)
INFO   | jvm 1    | 2016/12/09 20:15:02 | 	at com.microsoft.azure.management.resources.fluentcore.model.implementation.CreatableUpdatableImpl.createAsync(CreatableUpdatableImpl.java:127)
INFO   | jvm 1    | 2016/12/09 20:15:02 | 	at com.microsoft.azure.management.resources.fluentcore.model.implementation.CreatableUpdatableImpl.create(CreatableUpdatableImpl.java:147)

This error showed up around 5pm friday and has persisted since (when the above calls worked perfectly previously)

**Comment by paulojohnj** [comment]
The above error was due to the inclusion of google guava 20.0, a version of 19.0 works correctly.

**Comment by eric-wu** [comment]
Guava 19.0 fixed the issue. However, this issue really needs to be fixed on the Azure side. The fix on the user's side is ugly.  Not mentioning that it took some Googling to locate this fix.
