### ISSUE TITLE
[QUERY] Accessing key vault error "Request is missing a Bearer or PoP token"

### ISSUE THREAD

**Issue by gbedell** [Azure/azure-sdk-for-java#13238]
**Query/Question**
I am trying to access a secret from an Azure Key Vault through a private link endpoint. I am using the `azure-identity` and `azure-security-keyvault-secrets` SDK's. When I set up the credential and SecretClient and fetch a secret, I get the following error:

```
Response body:
{"error":{"code":"Unauthorized","message":"Request is missing a Bearer or PoP token."}}
```

Setup below:

```java
ClientSecretCredential credential = new ClientSecretCredentialBuilder()
	.clientId(clientId)
	.clientSecret(clientSecret)
	.tenantId(tenantId)
	.build();
		
final String vaultUrl = "https://<kv name>.vault.azure.net";
final String secretKey = "secret";
		
SecretClient secretClient = new SecretClientBuilder()
	.vaultUrl(vaultUrl)
	.credential(credential)
	.httpLogOptions(new HttpLogOptions().setLogLevel(HttpLogDetailLevel.BODY_AND_HEADERS))
	.buildClient();
		
KeyVaultSecret secret = secretClient.getSecret(secretKey);
```

I don't see anywhere in the documentation information about fetching the token prior to setting up the SecretClient with the application's information as credentials. I should note that I am behind a corporate proxy with strict firewall settings to/from Azure and on-prem. But I am able to connect to the key vault from behind the firewall. Just unable to fetch the secrets within my application.

***Why is this not a Bug or a feature Request?***
Not sure if this is a bug or just an incorrect configuration.

**Setup (please complete the following information if applicable):**
 - OS: [macOS]
 - IDE : [Eclipse]
 - Version of the Library used:
```xml
<dependency>
    <groupId>com.azure</groupId>
    <artifactId>azure-identity</artifactId>
    <version>1.0.8</version>
</dependency>
<dependency>
    <groupId>com.azure</groupId>
    <artifactId>azure-security-keyvault-secrets</artifactId>
    <version>4.1.5</version>
</dependency>
```
 
 **Information Checklist**
 Kindly make sure that you have added all the following information above and checkoff the required fields otherwise we will treat the issuer as an incomplete report
- [x] Query Added
- [x] Setup information Added

**Comment by joshfree** [comment]
@vcolin7 can you please take a look?

**Comment by vcolin7** [comment]
Hi @gbedell, our KeyVault clients use challenge-based authentication and do the following when authenticating for the first time:
1. The client sends a simple request with no `Authorization` header.
2. The server responds with status `401`, a challenge in the `WWW-Authenticate` header to be handled by the client and a message like the one you saw:
    `{"error":{"code":"Unauthorized","message":"Request is missing a Bearer or PoP token."}}`
3. The client uses the challenge to get an access token and sends another request to KeyVault, this time with a populated `Authorization` header containing the aforementioned token.
4. Assuming the credentials provided were correct when creating the client, the server sends a successful response with the desired data.

I suspect what you saw to be the response from point no. 2, however, if the call was never successful and your credentials are correct I could look into it. Seeing that you have enabled logging at the body and headers level, would you mind posting the logs that result from running this code?
