### ISSUE TITLE
Fold the management test framework into azure-core-test

### ISSUE THREAD

**Issue by JimSuplizio** [Azure/azure-sdk-for-java#13236]
The resourcemanager test infrastructure has some it's own recording/playback specifics. The recommendation is that these should be folded into azure-core-test, if possible and only creating a management specific test library if absolutely necessary. The general guidance is to reuse or extent as much existing infrastructure as possible.

There were a couple of open questions that came from the discussion on 7/15/2020.

- Investigate if it is feasible to roll the changes management needs into azure-core-test
- Potential circular dependency issue if azure-core-test depends on azure-core-management since azure-core-management already has a dependency on azure-core-test

**Comment by yungezz** [comment]
use the issue track the work

**Comment by xccc-msft** [comment]
For potential circular dependency issue
A question for @JonathanGiles: Can we remove azure-core-test from pom of azure-core-management? It seems azure-core-test not required there.

If so, we can plan to move our [AzureProfile](https://github.com/Azure/azure-sdk-for-java/blob/master/sdk/resources/mgmt/src/main/java/com/azure/resourcemanager/resources/fluentcore/profile/AzureProfile.java)/[SdkContext](https://github.com/Azure/azure-sdk-for-java/blob/master/sdk/resources/mgmt/src/main/java/com/azure/resourcemanager/resources/fluentcore/utils/SdkContext.java)/SdkContext related to azure-core-management. Then prepare to fold management test framework into azure-core-test by azure-core-management.
