### ISSUE TITLE
Periodic spike in latency in direct mode

### ISSUE THREAD

**Issue by simplynaveen20** [Azure/azure-sdk-for-java#13246]
**Describe the bug**
Periodic spike in latency in direct mode. During these spikes RNTBD requests spend most of their time in either the queued or pipelined state. Event spikes are in the range of 3-10 seconds. Time spent in the queued state indicates a problem in the `RntbdClientChannelPool`. Time spent in the pipelined state might indicate delays in initializing a channel. This could cause back pressure on the channel.

***Exception or Stack Trace***
Increasing P99 percentile of customer

**To Reproduce**
Create a document and in a for loop 1000 times read the same document, and count the number of reads taking more than 1 second.

**Expected behavior**
Their should be no periodic spike in latency.

**SDK:**  V4 [4.0.1]

**Comment by kirankumarkolli** [comment]
One more hit (from CX): Observations
- Queueing time: 73s :-(
- timecreated: Its really verbose and un-optimal. Lets fix it too.


{
	"args": {
		"transportRequestId": 3301075,
		"activityId": "d0d4a7fa-cacf-11ea-9a56-4b9ed269ae49",
		"origin": "....replicas/...",
		"timeCreated": {
			"offset": {
				"totalSeconds": 0,
				"id": "Z",
				"rules": {
					"fixedOffset": true,
					"transitions": [],
					"transitionRules": []
				}
			},
			"year": 2020,
			"month": "JULY",
			"dayOfMonth": 20,
			"dayOfWeek": "MONDAY",
			"dayOfYear": 202,
			"monthValue": 7,
			"hour": 21,
			"minute": 27,
			"second": 29,
			"nano": 886000000
		},
		"lifetime": "PT2M13.414890596S"
	},
	"requestLength": 509,
	"responseLength": -1,
	"status": {
		"done": false,
		"cancelled": false,
		"completedExceptionally": false
	},
	"timeline": [{
		"eventName": "created",
		"startTime": "2020-07-20T21:27:29.886Z",
		"durationInMicroSec": "0"
	}, {
		"eventName": "queued",
		"startTime": "2020-07-20T21:27:29.886Z",
		"durationInMicroSec": "73391000"
	}, {
		"eventName": "pipelined",
		"startTime": "2020-07-20T21:28:43.277Z",
		"durationInMicroSec": "18000"
	}, {
		"eventName": "transitTime",
		"startTime": "2020-07-20T21:28:43.295Z",
		"durationInMicroSec": "60006000"
	}, {
		"eventName": "received",
		"startTime": null,
		"durationInMicroSec": "0"
	}, {
		"eventName": "completed",
		"startTime": null,
		"durationInMicroSec": "0"
	}]
}

**Comment by xinlian12** [comment]
Fix merged in master. Target for release 4.3.0.
