### ISSUE TITLE
Resource Manager library adjustments for azure-client-sdk-parent parentage

### ISSUE THREAD

**Issue by JimSuplizio** [Azure/azure-sdk-for-java#13249]
Right now the resource manager libraries are parenting off of azure-resourcemanager-parent. When the updates are made to swap from azure-resourcemanager-parent to azure-client-sdk-parent we're going to hit issues with the differences in the way the following items are compiled or handled/verified by the track 2 pipelines:
- module_info
- javadoc generation
- sources
- checkstyle
- spotbugs
- revapi
- enforcer
- README/CHANGELOG verifications
The azure-resourcemanager-parent has its own sets of plugin definitions for many of the above and changes will need to be made to get things working with the azure-client-sdk-parent.

**Comment by JimSuplizio** [comment]
As part of the following [PR](https://github.com/Azure/azure-sdk-for-java/pull/13341) which is part of the centralized versioning I added the following tags:
1. In azure-client-sdk-parent there was one tag added to the javadoc genreation `RMDocs ` which is there because utils and samples were both added to the excludePackageNames. As part of this work either or both of those entries will stay or be removed.
2. Each resource manager pom file has `RMJacoco` in the properties where I set the coverage numbers low (both to 10%)
3. Each resource manager pom file has `RMfailOnWarning` above the `<failOnWarning>false</failOnWarning>`  maven-compiler-plugin setting. This was initially set to false in the resource manager parent, client parent sets it to true however there are a metric ton of warnings which I'm assuming will be cleaned up as part of this work.
4. Each resource manager pom file has `RMshowDeprecation` above the `<showDeprecation>true</showDeprecation>` maven-compiler-plugin setting. It's unclear if this is necessary or not but I left it in there.

There are a couple of unique external dependencies that were added to the external dependencies file because management's usage that differed from the common version
resourcemanager_com.jcraft:jsch;0.1.55, mgmt is using 0.1.55 in two places the common version is 0.1.53. The common version should probably be the one to get updated.
resourcemanager_com.microsoft.azure:azure-storage <-- version is nearly 3 years old and the common version is 8.0.0, we should probably update this version if and on if it is still necessary.

There were some management dependencies that were lower than the common versions but being patch level updates, they were relatively safe to move forward.
org.junit.jupiter:junit-jupiter-engine was 5.6.0, now 5.6.2
org.junit.jupiter:junit-jupiter-api was 5.6.0, now 5.6.2
commons-io:commons-io was 2.4, now 2.5
http://commons.apache.org/proper/commons-io/upgradeto2_5.html
Compatibility with 2.4:
  Binary compatible: Yes.
  Source compatible: Yes.
  Semantic compatible: Yes.

These are new dependencies added to the external_dependencies file
org.apache.commons:commons-compress;1.20
commons-net:commons-net;3.3
org.eclipse.jgit;org.eclipse.jgit;4.5.0.201609210915-r <-- this is old, september 2016
com.github.spotbugs:spotbugs-annotations;4.0.2  <-- only used as an optional dependency in 1 file

**Comment by conniey** [comment]
- [ ] Remove suppression of ServiceClientCheck on entire package. [checkstyle-suppressions.xml L484](https://github.com/Azure/azure-sdk-for-java/blob/feature/mgmt-engsys-convergence/eng/code-quality-reports/src/main/resources/checkstyle/checkstyle-suppressions.xml#L484)
