### ISSUE TITLE
Service Bus - Track 2 - Management client -MessageCountDetails flattening

### ISSUE THREAD

**Issue by hemanttanwar** [Azure/azure-sdk-for-java#13258]
> Flatten MessageCountDetails
> Rename MessageCount -> TotalMessageCount
> Size property should be in bytes

Related dotnet issue: https://github.com/Azure/azure-sdk-for-net/issues/13353

**Comment by conniey** [comment]
Closed in favour of https://github.com/Azure/azure-sdk-for-java/issues/13000
