### ISSUE TITLE
Service Bus - Track 2 - Management client model : Rename  QueueDescription

### ISSUE THREAD

**Issue by hemanttanwar** [Azure/azure-sdk-for-java#13257]
proposing using two separate types to model each entity - one for creation, and one for updating

 [ ] Input to Create* is Create*Options
[ ] Rename *Description -> *Properties (none of the properties are optional)
[ ] Rename *RuntimeInfo -> *RuntimeProperties

Related dotnet issue : https://github.com/Azure/azure-sdk-for-net/issues/13352

**Comment by conniey** [comment]
Closed in favour of https://github.com/Azure/azure-sdk-for-java/issues/13000
