### ISSUE TITLE
VM does not have a valid MAC address when it's de-allocated

### ISSUE THREAD

**Issue by puneet101** [Azure/azure-sdk-for-java#1328]
VM shows a valid MAC address but it is null when the VM is powered-off (de-allocted)

Is this by design or a bug?

**Comment by puneet101** [comment]
Any feedback?

**Comment by martinsawicki** [comment]
@anuchandy I believe that's just the server-side behavior

**Comment by anuchandy** [comment]
yes, this is the behavior of compute service. On de-allocate all the associated resources will be released.

**Comment by martinsawicki** [comment]
by design then
