### ISSUE TITLE
[BUG] NullPointerException when running metricDefinitions().listByResource() for a missing resource

### ISSUE THREAD

**Issue by OranShusterSpotinst** [Azure/azure-sdk-for-java#13316]
**Describe the bug**
When trying to fetch metric definition by resource the returned list of definitions is null and when trying to construct a TransformingSequentialList from it a null check is made and a NPE is thrown

***Exception or Stack Trace***
Replaced internal package names with *** and removed unrelated jetty method calls

```
java.lang.NullPointerException
	at com.google.common.base.Preconditions.checkNotNull(Preconditions.java:882)
	at com.google.common.collect.Lists$TransformingSequentialList.<init>(Lists.java:542)
	at com.google.common.collect.Lists.transform(Lists.java:526)
	at com.microsoft.azure.management.monitor.implementation.MetricDefinitionsImpl.listByResource(MetricDefinitionsImpl.java:44)
	at ***.getMetricByResourceId(MetricsDAO.java:46)
	at ***.getMetricStatistics(AzureMetricsResource.java:48)
        ....
```

**To Reproduce**
call `metricDefinitions().listByResource()` with a resource id that no longer exists

***Code Snippet***
While it is demonstrated on VMSS we also checked with normal VMs
```
        Azure             azureClient      = this.client.getAzureClient();
        String fullResourceId = "resourceGroups/OranResourceGroup/providers/Microsoft.Compute/virtualMachineScaleSets/missing_vm_standard_d1_low";
        List<MetricDefinition> metricDefinitions = azureClient.metricDefinitions().listByResource(fullResourceId);
```

**Expected behavior**
A concise internal azure sdk exception or an empty list

**Screenshots**
None

**Setup (please complete the following information):**
 - OS: Windows/mac/linux
 - IDE : Intellij
 - 1.32.1

**Comment by yungezz** [comment]
hi @weidongxu-microsoft could you pls have a look? thanks
