### ISSUE TITLE
[FEATURE REQ] Allow Setting Indexes in Include/Exclude Path.

### ISSUE THREAD

**Issue by neerajmangal** [Azure/azure-sdk-for-java#13315]
**Is your feature request related to a problem? Please describe.**
With Cosmos SDK 4.01., setting up the index's includePaths`DataType`, `IndexKind`, and `Precision` is no longer exposed to customize. `setIndexes()` function is no longer public so if we require to change the default values we can't. 
It seems like this is explicitly done via #11654

Is there any other way we can set `DataType, IndexKind, and Precision via SDK? Found https://github.com/Azure/azure-sdk-for-java/blob/master/sdk/cosmos/azure-cosmos/src/main/java/com/azure/cosmos/models/IndexingPolicy.java#L59 but this is also not exposed. 

**Describe the solution you'd like**
expose `{IncludePaths, ExcludePaths}.setIndexes()` function to customize. 

**Describe alternatives you've considered**
The alternative is to set Index's `IncludePaths` indexes `DataType`, `Kind`, and `Precision` manually in the portal.

**Additional context**

**Information Checklist**
Kindly make sure that you have added all the following information above and checkoff the required fields otherwise we will treat the issuer as an incomplete report
- [x] Description Added
- [x] Expected solution specified

**Comment by kushagraThapar** [comment]
@kushagraThapar - investigating this.

**Comment by kushagraThapar** [comment]
@neerajmangal  - I investigated this and the reason we didn't expose those APIs is because Cosmos db backend by default sets the dataType, precision, etc. and there was no way to change those through the APIs. 
For time being, manually updating them through portal is the only way.
