### ISSUE TITLE
[BUG] Need a way to inject partitionKey for CosmosContainer.queryItems method  

### ISSUE THREAD

**Issue by zahiritpro** [Azure/azure-sdk-for-java#13331]
**Description**
I'm trying to use the method `CosmosContainer.queryItems` to query db. 
However, I am not able to set partition key in CosmosQueryRequestOptions, as the setters is of default type.
Also, ModelBridgeInternal doesn't have a means to equip  CosmosQueryRequestOptions with partition key.

**Expected behaviour**
Need a way to inject partition key in` CosmosContainer.queryItems` method

**SDK version:**
 - 4.2.0

**Comment by kushagraThapar** [comment]
@zahiritpro - why can't you use `CosmosQueryRequestOptions#setPartitionKey(PartitionKey partitionKey)` API ?

/**
     * Sets the partition key used to identify the current request's target
     * partition.
     *
     * @param partitionkey the partition key value.
     * @return the CosmosQueryRequestOptions.
     */
    public CosmosQueryRequestOptions setPartitionKey(PartitionKey partitionkey) {
        this.partitionkey = partitionkey;
        return this;
    }

**Comment by zahiritpro** [comment]
@kushagraThapar  `CosmosQueryRequestOptions#setPartitionKey(PartitionKey partitionKey)` -- This setter method has `default` modifier. So is not accessible outside package.

Same issue with `CosmosItemRequestOptions` is solved by the method ModelBridgeInternal#setPartitionKey.

**CosmosQueryRequestOptions** might also need a similar setter in ModelBridgeInternal.

**Comment by kushagraThapar** [comment]
@zahiritpro - this code is from V4.2.0 - and I can see that it is `public`: https://github.com/Azure/azure-sdk-for-java/blob/azure-cosmos_4.2.0/sdk/cosmos/azure-cosmos/src/main/java/com/azure/cosmos/models/CosmosQueryRequestOptions.java#L281

Can you please make sure the version you are using ?

Also, you should never use `ModelsBridgeInternal` - as this is only for internal usage and not for customers.

**Comment by zahiritpro** [comment]
@kushagraThapar  Probably I had checked the  wrong version. I can see the setter public in V4.2.
Thank you. Will close the issue.

Also, I use `ModelsBridgeInternal.getInternalObjectNode(CosmosItemResponse)` to retrieve id and partition key from response.. Is it discouraged to use `ModelsBridgeInternal` for this  task..Is there an alternative ?

**Comment by kushagraThapar** [comment]
Yes, you should be able to call `CosmosItemResponse#getItem()` API - and that will return the saved response object in the same Object model that you provided it with initially. 
Make sure you enable this property `contentResponseOnWriteEnabled` in `CosmosClientBuilder` because SDK doesn't return full responses by default for write operations.

Read the docs and it should be clear on how and when to use it : https://github.com/Azure/azure-sdk-for-java/blob/azure-cosmos_4.2.0/sdk/cosmos/azure-cosmos/src/main/java/com/azure/cosmos/CosmosClientBuilder.java#L362
