### ISSUE TITLE
Add parameter for accepting userString in ServiceBusClientBuilder

### ISSUE THREAD

**Issue by conniey** [Azure/azure-sdk-for-java#13330]
Add support for customised user-agent string to follow with guidelines. https://azure.github.io/azure-sdk/general_azurecore.html#telemetry-policy
`[<application_id> ]azsdk-<sdk_language>-<package_name>/<package_version> <platform_info>`

* Python accepts an options bag in ctor that accepts "user_agent": string.
* JS/TS accepts `userAgent: UserAgentInfo` in constructor options bag.

Related: #9784

## Proposal 

Add method to builder.  If user specifies userAgent, then we prepend this as the `[application_id ]`.

```java
class ServiceBusClientBuilder {
    ServiceBusClientBuilder userAgent(String userAgent);
}
```

**Comment by hemanttanwar** [comment]
PR :  https://github.com/Azure/azure-sdk-for-java/pull/13697
