### ISSUE TITLE
Fix broken links in management/docs/SAMPLES.md

### ISSUE THREAD

**Issue by conniey** [Azure/azure-sdk-for-java#13332]
Fix broken links in SAMPLES.md. Taken from original issue #12630.

Found 10 links on page file:///home/vsts/work/1/s/sdk/management/docs/SAMPLE.md
WARNING: [404] broken link https://github.com/Azure-Samples/acs-java-deploy-image-from-acr-to-swarm
WARNING: [404] broken link https://github.com/Azure-Samples/acs-java-deploy-image-from-docker-hub-to-kubernetes
WARNING: [404] broken link https://github.com/Azure-Samples/acs-java-deploy-image-from-docker-hub-to-swarm
WARNING: [404] broken link https://github.com/Azure/azure-sdk-for-java/blob/master/sdk/management/samples/src/main/java/com/azure/resourcemanager/batch/samples/ManageBatchAccount.java
WARNING: [404] broken link https://github.com/Azure/azure-sdk-for-java/blob/master/sdk/management/samples/src/main/java/com/azure/resourcemanager/batchai/samples/ManageBatchAI.java
WARNING: [404] broken link https://github.com/Azure/azure-sdk-for-java/blob/master/sdk/management/samples/src/main/java/com/azure/resourcemanager/cdn/samples/ManageCdn.java
WARNING: [404] broken link https://github.com/Azure/azure-sdk-for-java/blob/master/sdk/management/samples/src/main/java/com/azure/resourcemanager/containerinstance/samples/ManageContainerInstanceWithAzureFileShareMount.java
WARNING: [404] broken link https://github.com/Azure/azure-sdk-for-java/blob/master/sdk/management/samples/src/main/java/com/azure/resourcemanager/containerinstance/samples/ManageContainerInstanceWithManualAzureFileShareMountCreation.java
WARNING: [404] broken link https://github.com/Azure/azure-sdk-for-java/blob/master/sdk/management/samples/src/main/java/com/azure/resourcemanager/containerinstance/samples/ManageContainerInstanceWithMultipleContainerImages.java
WARNING: [404] broken link https://github.com/Azure/azure-sdk-for-java/blob/master/sdk/management/samples/src/main/java/com/azure/resourcemanager/containerinstance/samples/ManageContainerInstanceZeroToOneAndOneToManyUsingContainerServiceOrchestrator.java

**Comment by yungezz** [comment]
hi @xccc-msft could you pls help to look at this?

**Comment by xccc-msft** [comment]
@conniey These links are already commented out when we prepare the SAMPLE.md so they are invisible for users. We plan to uncomment them after we add related services in the future. In this case, do we have to delete them first for the detection purpose and add later?

**Comment by conniey** [comment]
@xccc-msft Unfortunately, yes. This tool doesn't understand that these links aren't actually rendered.
