### ISSUE TITLE
Beta Four Tentative Release Date ? 

### ISSUE THREAD

**Issue by nwarriorch** [Azure/azure-sdk-for-java#1337]
We have a need to add Custom Data while creating a VM , the current release does not seem to have a "WithCustomData" in the VM builder. I see that you have added it since then. I was wondering when the tentative release date of the next release is ? since this is a blocking issue for us.

**Comment by jianghaolu** [comment]
@nwarriorch It's released today! Watch out for maven central as it takes a few hours to be live.

**Comment by nwarriorch** [comment]
Thank you, it looks like it became available over the weekend.
