### ISSUE TITLE
[BUG] Unable to get partitionIds from eventHubAsyncClient

### ISSUE THREAD

**Issue by Duncol** [Azure/azure-sdk-for-java#13380]
**Describe the bug**
We have two clients on two environments using same event hub on same consumer group. We encounter some "Receiver 'nil' with higher epoch..." warnings, but everything seems to run well... for a while... After some time (for unknown reasons), we encounter 'no partitions' error (see: screenshot).
NOTE: Application seems to be fine after aforementioned error, as there is second, Spring-scheduled feature which still works (just the part responsible for consuming events goes idle).
 
***Code Snippet***

Way, we build the client:
```
public EventProcessorClient eventProcessorClient(EventHubConfiguration eventHubConfig) {
        final CheckpointStore checkpointStore = getCheckpointStore(eventHubConfig);

        final EventHubConsumer processor = new EventHubConsumer();

        final String consumerGroup = eventHubConfig.getConsumerGroup();
        log.info("Building EventProcessorClient instance, [URI] - {}, [entityPath] - {}, "
                 + "[consumerGroup] - {}", connectionStringProperties.getEndpoint(),
                connectionStringProperties.getEntityPath(), consumerGroup);

        return new EventProcessorClientBuilder()
                .connectionString(eventHubConfig.getConnectionString())
                .consumerGroup(consumerGroup)
                .checkpointStore(checkpointStore)
                .processPartitionInitialization(processor::onOpen)
                .processPartitionClose(processor::onClose)
                .processEvent(processor::onEvent)
                .processError(processor::onError)
                .buildEventProcessorClient();
}

private CheckpointStore getCheckpointStore(EventHubConfiguration eventHubConfig) {
        final String storageContainerName = eventHubConfig.getContainerName();
        log.info("Building CheckpointStore instance: [containerName] - {}", storageContainerName);
        final BlobContainerAsyncClient blobClient = new BlobContainerClientBuilder()
                .connectionString(eventHubConfig.getContainerConnectionString())
                .containerName(storageContainerName)
                .buildAsyncClient();

        return new BlobCheckpointStore(blobClient);
    }
```

And the actual processor:
```
    void onEvent(EventContext context) {
        final EventData eventData = context.getEventData();
        final PartitionContext partitionContext = context.getPartitionContext();

        log.info("Consuming: Received event [sequence] - {}, [body] - {}, "
                 + "[eventHub] - {}, [namespace] - {}, [consumerGroup] - {}, [partitionId]"
                 + " - {}", eventData.getSequenceNumber(), eventData.getBodyAsString(),
                partitionContext.getEventHubName(), partitionContext.getFullyQualifiedNamespace(),
                partitionContext.getConsumerGroup(), partitionContext.getPartitionId());

        // HERE: sync call via Spring's RestTemplate (sometimes returning TimeoutException)

        setCheckpoint(context);
    }

    private void setCheckpoint(EventContext eventContext) {
        final EventData event = eventContext.getEventData();
        final PartitionContext partitionContext = eventContext.getPartitionContext();
        String format = Optional
                .ofNullable(event.getEnqueuedTime())
                .map(DateTimeFormatter.ISO_INSTANT::format)
                .orElse("[EMPTY_ENQUEUED_TIME]");
        try {
            eventContext.updateCheckpoint();
            log.info("Checkpoint successfully set on event: [sequence] - {}, [enqueuedAt] - "
                     + "{}, [partitionId] - {}, [consumerGroup] - {}", event.getSequenceNumber(),
                    format, partitionContext.getPartitionId(), partitionContext.getConsumerGroup());
        } catch (CancellationException | CompletionException ex) {
            log.error("Failed to set checkpoint on event: [sequence] - {}, [enqueuedAt] - {}, "
                      + "[partitionId] - {}, [consumerGroup] - {}", event.getSequenceNumber(),
                    format, partitionContext.getPartitionId(), partitionContext.getConsumerGroup(),
                    ex);
        }
    }
```
(Rest of the hooks just log the context)

**Expected behavior**
Load balancing mechanism to cope with such error by trying to reconnect anyways.
 
**Screenshots**
Exception chain, after which no further processing was observed
![image](https://user-images.githubusercontent.com/22201355/88059172-c4f85a80-cb64-11ea-8481-57c90d86db12.png)

**Setup (please complete the following information):**
(Dockerized in AKS)
 - OS: Alpine 3.11
 - JDK: OpenJDK 11
 - azure-messaging-eventhubs5.1.1
 - azure-messaging-eventhubs-checkpointstore-blob1.1.1

**Additional context**
I've tried to get 1:1 replication steps, but it is quite cumbersome, as this issue occurs only when having two parallel consumers (clients; same consumer group) working in the Azure env. When tried to (re/dis)connect n (n>1) local consumers, the ERRORs regarding 'New receiver 'nil'" occurred as well, but consumers managed to reestablish connection and fetch the partionId list

**Comment by srnagar** [comment]
@Duncol The error "Receiver 'nil' with higher epoch..." is expected when there are multiple instances of processor and the ownership of partition transfers from one instance to another instance. This should stop happening after the partitions are evenly distributed among all active instances.

Regarding the error with "no partitions in Event Hubs", this might be due to a network disconnection (it could be a transient failure but the error message is misleading and has been fixed in v5.1.2). When the network connection is restored, the processing should resume although it might take a few minutes before the processing begins depending on the retry policy used.

Could you please confirm that the processing does not resume even after some time? If so, could you please share the logs when this issue occurs?

**Comment by Duncol** [comment]
Here it starts, you can see logs indicating events parsed and sent ("Successfully sent...") 
![image](https://user-images.githubusercontent.com/22201355/88167070-8ae89080-cc18-11ea-8091-ba6e60c668a8.png)

and then there is IllegalStateException:
![image](https://user-images.githubusercontent.com/22201355/88167148-aa7fb900-cc18-11ea-838d-18ce510610fc.png)

After this event, only activity of the second service ("Pushing n signals...") can be observed.

Later on, it seemed to retry to rebalance itself:
![image](https://user-images.githubusercontent.com/22201355/88167455-27ab2e00-cc19-11ea-97c8-5506103a417c.png)

**But it had some quite gap there:**
![image](https://user-images.githubusercontent.com/22201355/88167781-a607d000-cc19-11ea-84ac-9d64b116e6c3.png)

But with no success up until the restart. From our perspective, EventHubs were fine.

**Comment by srnagar** [comment]
@duncol We updated the AMQP layer to improve reliability in the latest releases. Could you please try out the new versions?
azure-messaging-eventhubs - 5.2.0
azure-messaging-eventhubs-checkpointstore-blob - 1.2.0

If you are still seeing this issue, please re-open this ticket.
