### ISSUE TITLE
[BUG] Authenticated.subscriptions().list() only returns one subscription and returns different subscriptions on each repeated call

### ISSUE THREAD

**Issue by jkoe-r7** [Azure/azure-sdk-for-java#13407]
**Describe the bug**
Authenticated.subscriptions().list() loadAll() returns only one subscription, even though the application has permission to view multiple subscriptions. Furthermore, repeating the call returns a different single subscription each time even though the credential and endpoint values are all the same.

***Exception or Stack Trace***
Subscriptions list: --> GET https://management.azure.com/subscriptions?api-version=2016-06-01
Subscriptions list: <-- 200  https://management.azure.com/subscriptions?api-version=2016-06-01 (180 ms, 340-byte body)

**To Reproduce**

***Code Snippet***
```
Authenticated authenticated = Azure.configure()
          .withLogLevel(LogLevel.BASIC)
          .authenticate(new ApplicationTokenCredentials(client, tenant, key, AzureEnvironment.AZURE));
PagedList<Subscription> pagedList = authenticated.subscriptions().list();
pagedList.loadAll();
System.out.println(pagedList.size());
```

**Expected behavior**
Returning a list of more than one than one subscription if the application being used to create the credentials has permissions to view more than one subscription OR if application only has access to view one subscription return just that subscription.

**Screenshots**

**Setup (please complete the following information):**
 - OS: MacOS
 - IDE : Eclipse
 - 1.34.0

**Additional context**
Trying to use the SDK to dynamically discover all subscriptions available to an application/service principal, so if there's a better way to do this that would also be appreciated.

**Information Checklist**
Kindly make sure that you have added all the following information above and checkoff the required fields otherwise we will treat the issuer as an incomplete report
- [x] Bug Description Added
- [x] Repro Steps Added
- [x] Setup information Added

**Comment by yungezz** [comment]
hi @xccc-msft could you pls help to have a look? thanks

**Comment by xccc-msft** [comment]
@jkoe-r7 I cannot reproduce this issue. I tried with shared code snippet to list/loadAll/print with version of `1.34.0`. I'm able to get all subscriptions each time.
I just add label of `Service Attention` so the service team could help if any settings related on your application.

**Comment by jkoe-r7** [comment]
@xccc-msft Thanks. I am still seeing the issue (same credentials each time, authenticating against AzureEnvironment.AZURE) so mostly just very confused as to why it's a different subscription value getting returned each time. 
<img width="918" alt="Screen Shot 2020-07-22 at 8 28 55 AM" src="https://user-images.githubusercontent.com/39928554/88196398-fff69e80-cbf5-11ea-98c6-18bba2473c5e.png">
<img width="925" alt="Screen Shot 2020-07-22 at 8 29 14 AM" src="https://user-images.githubusercontent.com/39928554/88196393-fd944480-cbf5-11ea-97ee-bc6aad5520e8.png">
<img width="919" alt="Screen Shot 2020-07-22 at 8 29 36 AM" src="https://user-images.githubusercontent.com/39928554/88196397-ff5e0800-cbf5-11ea-8990-5bef1ed34071.png">

**Comment by jkoe-r7** [comment]
@xccc-msft Nevermind, I think I figured it out. Thanks for taking a look.
