### ISSUE TITLE
Add SNAPSHOT publishing support to Publish-MavenPackages.ps1

### ISSUE THREAD

**Issue by mitchdenny** [Azure/azure-sdk-for-java#13406]
Our release partners sometimes desire to publish ```SNAPSHOT``` packages through the partner release pipeline (this is something that we explicitly DO NOT support in our unified pipelines model, but we don't want to necessarily block it for partner pipelines. This issue is to track implementing ```SNAPSHOT``` publishing support in ```Publish-MavenPackages.ps1```.

**Comment by hallipr** [comment]
The account was already authorized, but the password contained a caret, `^`, that was being scrubbed by maven before the http auth header was formed.   The password was rotated and I've verified snapshot publishing is possible on the account.   I still need to update the yaml and powershelll scripts to enable snapshot publishing through the pipeline.
