### ISSUE TITLE
Form Recognizer sample issue

### ISSUE THREAD

**Issue by Luyunmt** [Azure/azure-sdk-for-java#13415]
Section [Link](https://github.com/Azure/azure-sdk-for-java/blob/master/sdk/formrecognizer/azure-ai-formrecognizer/src/samples/java/com/azure/ai/formrecognizer/AdvancedDiffLabeledUnlabeledData.java#L55)
 [Link1](https://github.com/Azure/azure-sdk-for-java/blob/master/sdk/formrecognizer/azure-ai-formrecognizer/src/samples/java/com/azure/ai/formrecognizer/AdvancedDiffLabeledUnlabeledDataAsync.java#L61)

![image](https://user-images.githubusercontent.com/53427149/88160432-373e6d00-cc41-11ea-8180-ab53ab0910fe.png)

Reason: 
The analyze file's type is jpg. 
Suggestion: 
Change  "FormContentType.APPLICATION_PDF"  to "FormContentType.IMAGE_JPEG".

**Comment by v-xuto** [comment]
@jongio for notification.

**Comment by samvaity** [comment]
Thanks for pointing this out. 
Will have a look!
cc: @mssfang

**Comment by Luyunmt** [comment]
PR merged
