### ISSUE TITLE
[QUERY] Why is AZURE_TENANT_ID required by azure-security-keyvault-secrets?

### ISSUE THREAD

**Issue by chris-j-h** [Azure/azure-sdk-for-java#13419]
**Query/Question**
I am currently migrating from the old `com.microsoft.azure:azure-keyvault` SDK to `com.azure:azure-security-keyvault-secrets`.  
When using `EnvironmentCredential`, the new SDK requires the `AZURE_TENANT_ID` environment variable to be set.  This was not the case with the old SDK, which required only `AZURE_CLIENT_ID` and `AZURE_CLIENT_SECRET`. 
From looking at the [authentication flow](https://github.com/Azure/azure-sdk-for-java/issues/13238#issuecomment-660776162), the [`/{tenant}/oauth2/token` API](https://docs.microsoft.com/en-us/azure/active-directory/azuread-dev/v1-protocols-oauth-code#use-the-authorization-code-to-request-an-access-token), and my local testing, I think the old SDK returns the `tenant-id` in the `WWW-Authenticate` header.

Does this mean that the authentication flow is different between the two SDKs?  Is there any way to use the new SDK to get/set Key Vault secrets without setting the `AZURE_TENANT_ID` env var?
 
***Why is this not a Bug or a feature Request?***
Trying to clarify my understanding.

**Setup (please complete the following information if applicable):**
 - macOS
- `com.azure:azure-security-keyvault-secrets:4.1.5`
- `com.azure:azure-identity:1.0.9`
 
 **Information Checklist**
 Kindly make sure that you have added all the following information above and checkoff the required fields otherwise we will treat the issuer as an incomplete report
- [x] Query Added
- [x] Setup information Added

**Comment by g2vinay** [comment]
@chris-j-h 
Our Track 2 KV package com.azure:azure-security-keyvault-secrets uses our Identity SDK com.azure:azure-identity.
Identity SDK offers AAD authentication support for all Azure SDKs. So, the `EnvironmentCredential` in our Identity SDK is designed to require AZURE_TENANT_ID, as this design works well for all azure SDKs using Service Principal authentication.

In your scenario, is there any concern with supplying the AZURE_TENANT_ID to the application?

**Comment by chris-j-h** [comment]
This means that migration from old to new SDK now requires additional configuration and as a result is something we cannot trivially move to.  

Given that `AZURE_TENANT_ID` is not required for the key vault is there any workaround for this?  I see in [this API doc](https://docs.microsoft.com/en-us/azure/active-directory/azuread-dev/v1-protocols-oauth-code#use-the-authorization-code-to-request-an-access-token) that `common` can sometimes be used for "tenant-independent tokens".

**Comment by g2vinay** [comment]
@chris-j-h 
I was investigating this.
There is a way to authenticate with azure-security-keyvault-secrets without tenantID.
To authenticate with KV SDK without the tenatID, currently a custom pipeline with a custom credential policy needs to be created.
I've attached a sample app that shows how to achieve this. The logic defined in the app will need to live in the user code.
[keyvaultauthsample.zip](https://github.com/Azure/azure-sdk-for-java/files/5147633/keyvaultauthsample.zip)

We will look into supporting this on the SDK side in the coming months.

CC: @schaabs

**Comment by g2vinay** [comment]
@chris-j-h, let me know if you've any further questions around this or would like reopen this issue.
Closing this issue.
