### ISSUE TITLE
[FEATURE REQ] [QUERY] When will bulk executor library be available for  SDKv4 

### ISSUE THREAD

**Issue by zahiritpro** [Azure/azure-sdk-for-java#13410]
**Query/Question**
I am upgrading my application from documentDb to cosmosDBV4.
I see bulk executor is the recommended solution for Java bulk support. 
However, it is not currently supported for  SDK 4.x.

Is there any plan for bulk executor support for SDK 4.x. in near  future ?
This would help us plan accordingly.

Reference used: https://docs.microsoft.com/en-us/azure/cosmos-db/bulk-executor-java

**Comment by joshfree** [comment]
Thanks for the question @zahiritpro, experts from the Cosmos team will follow up with you shortly.

**Comment by kirankumarkolli** [comment]
TransactionBatch and Bulk API's will be native part of V4 Java SDK. 
Tentative timeline is end-of-year.
