### ISSUE TITLE
[QUERY]  How can I inject partitionKey in CosmosItemRequestOptions for container.upsertItem method

### ISSUE THREAD

**Issue by zahiritpro** [Azure/azure-sdk-for-java#13441]
1. I'm trying to use the method CosmosContainer.upsertItem.
However, I am not able to set partition key in CosmosItemRequestOptions, as the setters is of default type.
As ModelBridgeInternal is internal, dont want to use it for this purpose.
Is there  any other way to inject  partition key for  `upsertItem` method ??

2. How can i get the **value** of paritionKey from crud operation response -  CosmosItemResponse.
I am currently using container.read().getProperties().getPartitionKeyDefinition() to parse the  document and find partition key value..Is there a better way.?

SDK version:
4.2.0

**Comment by kushagraThapar** [comment]
@zahiritpro - We are releasing a new overloaded API in v4.3.0 for `upsertItem` with `partitionKey`

**Comment by zahiritpro** [comment]
@kushagraThapar Thank you..

Can you help me on the 2nd item..

**Comment by kushagraThapar** [comment]
@zahiritpro - on the 2nd item, once you get `CosmosItemResponse` back - you can call `getItem()` API and you can get the Partition key value from there.
However to get partition key definition from CosmosContainerResponse, you are already doing it the right way.

**Comment by kirankumarkolli** [comment]
Please re-open with if-any needed.
