### ISSUE TITLE
[QUERY] azure-servicebus vs azure-messaging-servicebus 

### ISSUE THREAD

**Issue by bmtKIA6** [Azure/azure-sdk-for-java#13490]
**Query/Question**
I see that there are 2 sdk's for service bus. 

- com.microsoft.azure/azure-servicebus (currently at 3.4.0)
- com.azure/azure-messaging-servicebus (currently at 7.0.0-beta4)

As far as I can tell, they are both actively maintained and new versions are being released on a regular basis.

Questions:
- What is the difference?
- Which one to use?
- Is there an existing documentation outlining the decision path on what version to use?

**Comment by lilyjma** [comment]
@bmtKIA6 That's a great question! com.azure/azure-messaging-servicebus is our new service bus library that follows certain guidelines aimed to create a better developer experience (more consistency, more idiomatic, etc.) Please take a look at our [blog post](https://azure.github.io/azure-sdk/releases/2019-07-10/index.html) and/or [video](https://www.youtube.com/watch?reload=9&v=38RYIx7a2M4) that go deeper into this. That said, we expect to have a GA version of com.azure/azure-messaging-servicebus in the next few months.

**Comment by hemanttanwar** [comment]
Thanks @lilyjma 
@bmtKIA6 I hope you found answer to your questions. I will close this issue for now and If you have further questions,  you can reopen this issue or create new one.
