### ISSUE TITLE
Not able to connect with Azure china keyvault using azure-spring-boot-2.3.2.jar

### ISSUE THREAD

**Issue by sans30** [Azure/azure-sdk-for-java#13522]
Hello,

our application connects with key vault on startup and it uses following dependencies.
azure-spring-boot-2.3.2.jar
azure-identity-1.0.4.jar
msal4j-0.5.0-preview.jar

We are hosting the application in china and that will connect with keyvault in azure china. Since the azure-spring-boot library has authority url hard coded  as 'https://login.microsoftonline.com/', application is not able get oauth token.

could you please help us to fix the issue, so that we can get token from https://login.chinacloudapi.cn/{tenant-id}/oauth2/token

**Below is the configuration class:**
@Configuration
@EnableTransactionManagement
@EnableJpaRepositories(
    entityManagerFactoryRef = "entMgrFactory",
    basePackages = {"xxx.yyy.zzz"}
)
public class MyDataSourceConfig extends HikariConfig {

  @Bean("myDataSourceProperties")
  @Primary
  @ConfigurationProperties("spring.datasource")
  public DataSourceProperties myDataSourceProperties() {
    return new DataSourceProperties();
  }
} 

**keyvault related properties in application-local.yml**
azure:
  keyvault:
    uri: {key_vault-uri}
    client-id: {client_id}
    client-key: {client-key}
    tenant-id: {tenant-id}

**Error received on application statup:**
Caused by: com.microsoft.aad.msal4j.MsalServiceException: AADSTS90002: Tenant {tenant-id} not found. This may happen if there are no active subscriptions for the tenant. Check to make sure you have the correct tenant ID. Check with your subscription administrator.

Thanks in Advance!!!

**Comment by yiliuTo** [comment]
Hi @sans30 To use Azure China, have you added such entry in the application.properties?
```
azure.activedirectory.environment=cn
```

**Comment by sans30** [comment]
Hi @yiliuTo ,

Yes, I tried adding azure.activedirectory.environment=cn in application.properties, but it didn't work.

**Comment by yiliuTo** [comment]
Hi @sans30 , to pass the OAuth2 authentication in Azure China, I think you could reset the endpoint manually in application.properties by replacing `login.microsoftonline.com` with `login.chinacloudapi.cn`, and change `common` to your tenant-id if needed.
```
spring.security.oauth2.client.provider.azure.authorization-uri=https://login.microsoftonline.com/common/oauth2/authorize
spring.security.oauth2.client.provider.azure.token-uri=https://login.microsoftonline.com/common/oauth2/token
spring.security.oauth2.client.provider.azure.user-info-uri=https://login.microsoftonline.com/common/openid/userinfo
spring.security.oauth2.client.provider.azure.jwk-set-uri=https://login.microsoftonline.com/common/discovery/keys
```

**Comment by sans30** [comment]
Hi @yiliuTo , spring.security.oauth2 properties also didn't work. Problem is when application starts up the framework is trying to connect with keyvault to get keys. Since the IdentityClientOptions.java is referencing to DEFAULT_AUTHORITY_HOST = "https://login.microsoftonline.com/", my application fails. I was able to debug the library and the execution flows like below.

KeyVaultEnvironmentPostProcessor.postProcessEnvironment()->helper.addKeyVaultPropertySource("")->KeyVaultEnvironmentPostProcessorHelper.addKeyVaultPropertySource()->getCredentials(normalizedName)->ClientSecretCredentialBuilder.build()->new ClientSecretCredential(tenantId, clientId, clientSecret, identityClientOptions)

could you please generate spring boot project with above listed dependencies and try to debug the issue.

**Comment by yiliuTo** [comment]
Hi @sans30 , sorry that I misunderstood your case as a problem of application login error at first. Besides thanks to your clear and detalied debug info, we will investigate and fix this as soon.

**Comment by sans30** [comment]
Hi @yiliuTo , Do you have any timeline to fix this issue? Also I see there is a beta version (1.1.0-beta.3) which has a fix to configure azure authority host. I would like to know the relase plan of the actual version.

**Comment by yiliuTo** [comment]
Hi @sans30 , to fix this issue is added into our recent working schedule, but the release plan is not sure yet. Besides, could you provide a link to the beta version or the associated github fixing issue you mensioned? Thanks~

**Comment by sans30** [comment]
Hi @yiliuTo you can find it from release history. 
**Change log for azure-identity**: https://github.com/Azure/azure-sdk-for-java/blob/master/sdk/identity/azure-identity/CHANGELOG.md

**Release number**: 1.1.0-beta.3 (2020-04-07)

Please let me know if you need more information.

**Comment by yiliuTo** [comment]
Hi @sans30 , thanks to your help. We have tested with 1.1.0-beta.3 version of Azure-Identity and it works well to specify the authority host. However, we cannot update the dependency so far because it's a beta version, and we will perform the update once it releases a GA. Thanks again.

**Comment by sans30** [comment]
Hi @yiliuTo , I see that azure-identity 1.1.0 has been released, does this have fix for Azure Authority Host? and can you please let me know if this can be used with Spring-2.3?

**Comment by yiliuTo** [comment]
Hi @sans30 sorry for the late response, yes the 1.1.0 has fixed authority host issue. And I have tested it with key vault starter 2.3.2 which can work normally.

**Comment by saragluna** [comment]
FYI, our key vault starter also has a property to set the authority host now, check it here https://github.com/Azure/azure-sdk-for-java/tree/master/sdk/spring/azure-spring-boot-starter-keyvault-secrets#custom-settings.

Closing this issue now.
