### ISSUE TITLE
azure-spring-data-cosmos could not be found

### ISSUE THREAD

**Issue by eleckner** [Azure/azure-sdk-for-java#13543]
I added the maven dependency:
<dependency>
    <groupId>com.azure</groupId>
    <artifactId>azure-spring-data-cosmos</artifactId>
    <version>3.0.0-beta.1</version>
</dependency>

and I received the following error:

Cannot resolve com.azure:azure-spring-data-cosmos:3.0.0-beta.1

**Comment by lu-cheng** [comment]
@eleckner You can refer to this document: https://dev.azure.com/azure-sdk/public/_packaging?_a=connect&feed=azure-sdk-for-java

**Comment by eleckner** [comment]
Thanks, @lu-cheng

**Comment by kushagraThapar** [comment]
@eleckner  - you can find the dependency here - com.azure:azure-spring-data-cosmos:3.0.0-beta.2 - https://mvnrepository.com/artifact/com.azure/azure-spring-data-cosmos
