### ISSUE TITLE
Rework "com.microsoft.azure.management.resources.fluentcore.dag" core package

### ISSUE THREAD

**Issue by anuchandy** [Azure/azure-sdk-for-java#1354]
Rework "com.microsoft.azure.management.resources.fluentcore.dag" core package

- [x] Support for hot tasks
- [x] Support for different task group termination strategies on error
- [x] Treat exceptions as first-class citizen
- [x] Support for tasks that emit multiple onNext
- [x] Ensure the package has no coupling with any other package in the sdk
- [x] Unit tests with 90+% coverage
- [x] Zero warnings and no `@SuppressWarnings` annotations

#### Support for hot tasks

Since the underlying retrofit http client used by SDK returns cold observable, the autorest generated API also returns cold observables, but this package solves a general problem of optimizing the execution of a group of related tasks. This means the package should support a task group that contain hot and cold tasks (including mix of these two). 

#### Support for different task group termination strategies on error

As mentioned above, since package solves a general problem, not just specific to sdk - it turns out that there are mainly two ways to terminate group execution on error

* On 1 or more error, allow any already concurrently running tasks to finish and terminate the group 
execution gracefully. 
* On 1 or more error, make as much progress as can then terminate the group execution gracefully. In this setup, if there are tasks which are not directly or indirectly depends on the error-ed tasks then execute them and terminate the group when there is no more progress can be made.

First strategy is the fastest way to terminate the group and the default termination strategy set for sdk tasks is this.

#### Treat exceptions as first class citizen

So far, during group execution as soon as any error occur the final stream terminate with that exception. 

In reality due to concurrent execution of tasks, there are chances that multiple tasks fails at the same time, in this situation framework should terminate the final stream with [composite exception](http://reactivex.io/RxJava/javadoc/rx/exceptions/CompositeException.html). Note that depends on the selected termination stratey, the stream should terminate only after completion of other tasks choosen to for execution.

#### Support for tasks that emit multiple onNext

The Observable<T> returned by the AutoRest generated API emits onNext only once with the created or updated resource. This is fine, but the TaskGroup should be capable of handling tasks that emits multiple events (via multiple onNext). In this case, all the emitted values needs to be redirected to the downstream observable and a dependent task should start only after the task it depends on finish emitting all events i.e. after onComplete.

**Comment by jianghaolu** [comment]
Excellent!

**Comment by anuchandy** [comment]
Listed work items are done hence closing.
