### ISSUE TITLE
No examples for asynchronous VM creation on latest sdk

### ISSUE THREAD

**Issue by rajdeeprath** [Azure/azure-sdk-for-java#1357]
There are no examples whatsoever of  asynchronous Vm creation.following up from 1.0.0.
-Beta4 version, none of the createAsync calls work. How to create VM asynchronously with latest version of SDK ?

**Comment by anuchandy** [comment]
@rajdeeprath starting from 1.0.0-beta4, the `createAsync` call not just return the root resource but all the created resources that root resource directly or indirectly depends on as well. This means `createAsync` on virtual machine can now possibly stream resource group, network interface, virtual network, storage account and finally virtual machine.

If you are interested only in the final resource i.e. virtual machine, then you have to apply the rx `last` operator, for example:

```java
Creatable<VirtualMachine> virtualMachineCreatable = azure.virtualMachines()
    .define(ResourceNamer.randomResourceName("vm-", 10))
    .withRegion(Region.US_EAST)
    .withNewResourceGroup(ResourceNamer.randomResourceName("rg-", 10))
    .withNewPrimaryNetwork("10.0.0.0/28")
    .withPrimaryPrivateIpAddressDynamic()
    .withNewPrimaryPublicIpAddress(ResourceNamer.randomResourceName("pip-", 20))
    .withPopularLinuxImage(KnownLinuxVirtualMachineImage.UBUNTU_SERVER_16_04_LTS)
    .withRootUsername("tirekicker")
    .withRootPassword("BaR@12!#")
    .withNewStorageAccount(ResourceNamer.randomResourceName("stg", 20));
     VirtualMachine vm = (VirtualMachine) virtualMachineCreatable
                                          .createAsync()
                                          .toBlocking()
                                          .last();
```

On the other hand, following code shows how to see the resources as they gets created.

```java
Creatable<VirtualMachine> virtualMachineCreatable = azure.virtualMachines()
    .define(ResourceNamer.randomResourceName("vm-", 10))
    .withRegion(Region.US_EAST)
    .withNewResourceGroup(ResourceNamer.randomResourceName("rg-", 10))
    .withNewPrimaryNetwork("10.0.0.0/28")
    .withPrimaryPrivateIpAddressDynamic()
    .withNewPrimaryPublicIpAddress(ResourceNamer.randomResourceName("pip-", 20))
    .withPopularLinuxImage(KnownLinuxVirtualMachineImage.UBUNTU_SERVER_16_04_LTS)
    .withRootUsername("tirekicker")
    .withRootPassword("BaR@12!#")
    .withNewStorageAccount(ResourceNamer.randomResourceName("stg", 20));

VirtualMachine vm = (VirtualMachine) virtualMachineCreatable.createAsync().map(new Func1<Indexable, Indexable>() {
            @Override
            public Indexable call(Indexable createdResource) {
                if (createdResource instanceof Resource) {
                    Resource resource = (Resource) createdResource;
                    System.out.println("Resource: " + resource.id());
                    if (resource instanceof ResourceGroup) {
                        ResourceGroup resourceGroup = (ResourceGroup) resource;
                        System.out.println("Resource group:" + resourceGroup.id());
                    } else if (resource instanceof NetworkInterface) {
                        NetworkInterface networkInterface = (NetworkInterface) resource;
                        System.out.println("Network interface:" + networkInterface.id());
                    } else if (resource instanceof Network) {
                        Network network = (Network) resource;
                        System.out.println("Virtual Network:" + network.id());
                    } else if (resource instanceof PublicIpAddress) {
                        PublicIpAddress publicIpAddress = (PublicIpAddress) resource;
                        System.out.println("Public IP Address:" + publicIpAddress.id());
                    } else if (resource instanceof StorageAccount) {
                        StorageAccount storageAccount = (StorageAccount) resource;
                        System.out.println("Storage account:" + storageAccount.id());
                    } else if (resource instanceof VirtualMachine) {
                        VirtualMachine virtualMachine = (VirtualMachine) resource;
                        System.out.println("Virtual Machine:" + virtualMachine.id());
                    }
                }
                return createdResource;
            }
        }).toBlocking().last();
        System.out.println("VM:" + vm.id());
```

**Comment by anuchandy** [comment]
@martinsawicki @selvasingh it would be good if we can call-out `createAsync` behavior in general, may be in the Readme itself. I can add a simple sample showcasing this use-case.

**Comment by rajdeeprath** [comment]
Thank you. I will try this today and let you know. Please do add examples
in the read me as well it will help everyone a lot.

It's takes about 2 min to get a VM running. So async example is more
important than the sync one practically.

**Comment by rajdeeprath** [comment]
I tried your code but either it does not work as i think it should or
perhaps my question was not clear. Even when i use createAsync the code
blocks for 2 minutes before printing "Done". What am i missing ? I thought
async was suppose to be non blocking ?


Creatable<VirtualMachine> virtualMachineCreatable = azure.virtualMachines()
           .define(ResourceNamer.randomResourceName("vm-", 10))
           .withRegion(Region.US_EAST)
           .withNewResourceGroup(ResourceNamer.randomResourceName("rg-",
10))
           .withNewPrimaryNetwork("10.0.0.0/28")
           .withPrimaryPrivateIpAddressDynamic()

 .withNewPrimaryPublicIpAddress(ResourceNamer.randomResourceName("pip-",
20))

 .withPopularLinuxImage(KnownLinuxVirtualMachineImage.UBUNTU_SERVER_16_04_LTS)
           .withRootUsername("tirekicker")
           .withRootPassword("BaR@12!#")
           .withNewStorageAccount(ResourceNamer.randomResourceName("stg",
20));


        virtualMachineCreatable.createAsync().map(new Func1<Indexable,
Indexable>() {

public Indexable call(Indexable t) {
// TODO Auto-generated method stub
return null;
}

        }).toBlocking().last();


        System.out.println("Done");

**Comment by rajdeeprath** [comment]
If you use the AWS sdk or the google compute sdk you will notice that a VM
create operation results in a simple operation id which takes about  ~5 to
~8 seconds max. I can then monitor the progress of the VM in a  separate
thread. With azure it takes 2 minutes or more just to get past that one
step.


I also tried your code.

Creatable<VirtualMachine> virtualMachineCreatable = azure.virtualMachines()
           .define(ResourceNamer.randomResourceName("vm-", 10))
           .withRegion(Region.US_EAST)
           .withNewResourceGroup(ResourceNamer.randomResourceName("rg-",
10))
           .withNewPrimaryNetwork("10.0.0.0/28")
           .withPrimaryPrivateIpAddressDynamic()

 .withNewPrimaryPublicIpAddress(ResourceNamer.randomResourceName("pip-",
20))

 .withPopularLinuxImage(KnownLinuxVirtualMachineImage.UBUNTU_SERVER_16_04_LTS)
           .withRootUsername("tirekicker")
           .withRootPassword("BaR@12!#")
           .withNewStorageAccount(ResourceNamer.randomResourceName("stg",
20));



        VirtualMachine vm = (VirtualMachine)
virtualMachineCreatable.createAsync().map(new Func1<Indexable, Indexable>()
{

public Indexable call(Indexable createdResource) {
if (createdResource instanceof Resource) {
                    Resource resource = (Resource) createdResource;
                    System.out.println("Resource: " + resource.id());
                    if (resource instanceof ResourceGroup) {
                        ResourceGroup resourceGroup = (ResourceGroup)
resource;
                        System.out.println("Resource group:" +
resourceGroup.id());
                    } else if (resource instanceof NetworkInterface) {
                        NetworkInterface networkInterface =
(NetworkInterface) resource;
                        System.out.println("Network interface:" +
networkInterface.id());
                    } else if (resource instanceof Network) {
                        Network network = (Network) resource;
                        System.out.println("Virtual Network:" + network.id
());
                    } else if (resource instanceof PublicIpAddress) {
                        PublicIpAddress publicIpAddress = (PublicIpAddress)
resource;
                        System.out.println("Public IP Address:" +
publicIpAddress.id());
                    } else if (resource instanceof StorageAccount) {
                        StorageAccount storageAccount = (StorageAccount)
resource;
                        System.out.println("Storage account:" +
storageAccount.id());
                    } else if (resource instanceof VirtualMachine) {
                        VirtualMachine virtualMachine = (VirtualMachine)
resource;
                        System.out.println("Virtual Machine:" +
virtualMachine.id());
                    }
                }
                return createdResource;
}

        }).toBlocking().last();
        System.out.println("VM:" + vm.id());

1.  I got no intermedia outputs

2.   println executed after minutes. Is something broken in the sdk ?

**Comment by rajdeeprath** [comment]
I will try some more and try to send you an image of what i want the flow
to be. I think there is either an issue with how i am using it or the
sdk version ?

I am attaching the code that i have for testing your sdk. I also noted that
@override isn't appearing for me on the map Func.. I appreciate your
helping me  .!


Thank you


On Thu, Dec 29, 2016 at 2:58 AM, Anu Thomas Chandy <notifications@github.com

**Comment by rajdeeprath** [comment]
Here is the simple flow i wish to achieve with azure sdk. This already
works well with Amazon and Google cloud platforms.
https://gist.github.com/rajdeeprath/30ca4a17e6d08eb6011eb1907976f21d

**Comment by rajdeeprath** [comment]
I think got some stuff working using ServiceCallback instead of Observable.
I ill try to write a blog post once i am done. I have certain suggestions
to help improve the SDK for developers.

1. Documentation clarity

2. Remove any old examples / codebases that are not likely to work with new
sdk

3. Explain ComputeManager and stuff which is used in Tests => compute
samples

4. Explain Instance states cycling. There is no doc/image on VM states and
transition flow.

5. Add async examples for all resource operations in sdk Readme or Tests



I will post back if there are any more issues.Thank you.

**Comment by anuchandy** [comment]
Nice to hear that your use case is working. 

In parallel with sdk, we are also trying to improve samples and documentation. Your inputs regarding this is helpful. We will pass your feedback on vm states to azure doc team.

We had a look at your [work flow](https://gist.github.com/rajdeeprath/30ca4a17e6d08eb6011eb1907976f21), in case you want to know how to do this with observables, here is how. If your app is written based on Rx then there is better than this apporach. This code is just for educational purpose. 

```java
public void mainFunc() {
    Object obj = this.startNewInstance(null);
    if (obj == null) {
        System.out.println("startNewInstance returned: Request not initiated");
    } else {
        System.out.println("startNewInstance returned: Request initiated");
        //
        // TODO: Do the work you want to do concurrent with VM creation
        // Since I don't know what you want to do here, waiting below to block main thread from
        // exiting
        try {
            System.out.println("Waiting for 10 minutes");
            Thread.sleep(10 * 60 * 1000);
        } catch (InterruptedException ex) {
            System.out.println("Interrupted");
        }
    }
}
```

```java
public Object startNewInstance(Object[] params)
{
    System.out.println("Entering into - startNewInstance");
    ComputeManager computeManager;
    try {
        // Configure a VM => ComputeManager / Azure
        //
        ApplicationTokenCredentials credentials = new ApplicationTokenCredentials(
                System.getenv("client-id"),
                System.getenv("domain"),
                System.getenv("secret"),
                AzureEnvironment.AZURE);

        RestClient restClient = new RestClient.Builder()
                .withBaseUrl(AzureEnvironment.AZURE, AzureEnvironment.Endpoint.RESOURCE_MANAGER)
                .withCredentials(credentials)
                .withLogLevel(HttpLoggingInterceptor.Level.NONE)
                .build();

        computeManager = ComputeManager
                .authenticate(restClient, System.getenv("subscription-id"));

        final String rgName = ResourceNamer.randomResourceName("rg-", 10);
        final String vmName = ResourceNamer.randomResourceName("vm-", 10);
        // Prepare VM definition
        //
        Creatable<VirtualMachine> virtualMachineCreatable = computeManager.virtualMachines()
                .define(vmName)
                .withRegion(Region.US_EAST)
                .withNewResourceGroup(rgName)
                .withNewPrimaryNetwork("10.0.0.0/28")
                .withPrimaryPrivateIpAddressDynamic()
                .withNewPrimaryPublicIpAddress(ResourceNamer.randomResourceName("pip-", 20))
                .withPopularLinuxImage(KnownLinuxVirtualMachineImage.UBUNTU_SERVER_16_04_LTS)
                .withRootUsername("tirekicker")
                .withRootPassword("BaR@12!#")
                .withNewStorageAccount(ResourceNamer.randomResourceName("stg", 20));

        // Start creating VM asynchronously
        //
        startNewInstance(virtualMachineCreatable);
        System.out.println(Thread.currentThread().getName() + "- Async request to create VM and associated resources has been initiated:");
        //
        // TODO: tell method invoker that instance request was made => Return object
        //
        System.out.println("Returning from - startNewInstance");
        return new Object();

    } catch (Exception exception) {
        System.out.println(exception.getMessage());
        // TODO: tell method invoker an error occurred
    }
    System.out.println("Returning from - startNewInstance");
    return null;
}
```


```java
void startNewInstance(Creatable<VirtualMachine> virtualMachineCreatable) {
    final Action1<String> print = new Action1<String>() {
        @Override
        public void call(String message) {
            System.out.println("[" + Thread.currentThread().getName() + "] " + message);
        }
    };

    ConnectableObservable<Indexable> createVMObservable = virtualMachineCreatable
            .createAsync()
            .observeOn(Schedulers.computation())
            .doOnNext(new Action1<Indexable>() {
                @Override
                public void call(Indexable created) {
                    Resource resource = (Resource) created;
                    // Print id of each resource as they get created
                    print.call("Created resource: " + resource.id());
                }
            })
            .doOnCompleted(new Action0() {
                @Override
                public void call() {
                    print.call("Create VM finished.");
                    //
                    // TODO: Do whatever you want to do on success
                    //
                }
            })
            .onErrorResumeNext(new Func1<Throwable, Observable<? extends Indexable>>() {
                @Override
                public Observable<? extends Indexable> call(Throwable throwable) {
                    print.call("VM or associated resources creation failed: " + throwable.getMessage());
                    //
                    // TODO: Do whatever you want to do on failure
                    //
                    return Observable.empty();
                }
            }).publish();
    createVMObservable.connect();
}
```

```
Entering into - startNewInstance
main Async request to create VM and associated resources has been initiated:
Returning from - startNewInstance
startNewInstance returned: Request initiated
Waiting for 10 minutes

[RxIoScheduler-2] Created resource: /subscriptions/<sub-id>/resourceGroups/rg-25570b
[RxIoScheduler-5] Created resource: /subscriptions/<sub-id>/resourceGroups/rg-25570b/providers/Microsoft.Network/publicIPAddresses/pip92254992
[RxComputationScheduler-2] Created resource: /subscriptions/<sub-id>/resourceGroups/rg-25570b/providers/Microsoft.Network/virtualNetworks/vnet9711980ac7
[RxIoScheduler-2] Created resource: /subscriptions/<sub-id>/resourceGroups/rg-25570b/providers/Microsoft.Network/networkInterfaces/nic057713e3395
[RxComputationScheduler-3] Created resource: /subscriptions/<sub-id>/resourceGroups/rg-25570b/providers/Microsoft.Storage/storageAccounts/stg870637396bba
[RxComputationScheduler-1] Created resource: /subscriptions/<sub-id>/resourceGroups/rg-25570b/providers/Microsoft.Compute/virtualMachines/vm-38666b
[RxComputationScheduler-1] Create VM finished.
```

**Comment by nwarriorch** [comment]
do you have an update on the async examples , either using service call back or observable ?

**Comment by anuchandy** [comment]
please see the virtual machine async sample :- https://github.com/Azure-Samples/compute-java-manage-vm-async

**Comment by martinsawicki** [comment]
sample code now exists so closing
