### ISSUE TITLE
[BUG] PartitionBasedLoadBalancer.java does sometimes PING-PONG between 2 EventProcessorClients.

### ISSUE THREAD

**Issue by Piskous** [Azure/azure-sdk-for-java#13597]
Load balancing does not run always as expected. EventProcessorClients steal with PING-PONG the partitions. This PING-PONG is not fortunatelly endless.

Steps to reproduce the behavior (it is reproducible with 50%):
- Create event hub at least with 4 partitions. 
- Start the first EventProcessorClient and wait until it has all partitions as owner. 
- Start the second EventProcessorClient and wait until the load balancing is complete.
- See the logs. 

Example of Logs:
EventProcessorClient 1:
20/07/29 13:18:13 INFO eventhubs.PartitionBasedLoadBalancer: Attempting to claim ownership of partition 2 20/07/29 13:22:23 INFO eventhubs.PartitionBasedLoadBalancer: Attempting to claim ownership of partition 2
20/07/29 13:25:24 INFO eventhubs.PartitionBasedLoadBalancer: Attempting to claim ownership of partition 2
20/07/29 13:25:34 INFO eventhubs.PartitionBasedLoadBalancer: Attempting to claim ownership of partition 2
EventProcessorClient 2:
20/07/29 13:19:35 INFO eventhubs.PartitionBasedLoadBalancer: Attempting to claim ownership of partition 2
20/07/29 13:24:36 INFO eventhubs.PartitionBasedLoadBalancer: Attempting to claim ownership of partition 2
20/07/29 13:27:06 INFO eventhubs.PartitionBasedLoadBalancer: Attempting to claim ownership of partition 2

Possible problem (updating from checkpoint store could be the solution):
![image-2020-07-13-16-41-53-762](https://user-images.githubusercontent.com/68953001/88798298-fac0c300-d1a4-11ea-8586-40a876c771e6.png)

The new second EventProcessorClient steals partitions from the first EventProcessorClient. There is some delay until the first EventProcessorClient gets an error for stolen partitions in its event pumps. During this delay, it sometimes reclaims its (already lost) ownerships for the stolen partitions, because it reclaims ownership for all (still) existing event pumps instead of the ownerships according to the checkpoint store.

Setup :
 - OS: Windows 10, Java 11
 - IDE : IntelliJ
 - Maven code:
       <dependency>
            <groupId>com.azure</groupId>
            <artifactId>azure-messaging-eventhubs</artifactId>
            <version>5.1.1</version>
        </dependency>

**Comment by joshfree** [comment]
Thanks for filing the github issue @Piskous.  @srnagar can you please follow up?

**Comment by srnagar** [comment]
Thanks for reporting the issue. I will look into this and update my findings. Meanwhile, could you please enable DEBUG level logs and provide logs of both instances when this issue occurs?

**Comment by Piskous** [comment]
Test case: 32 partitions and 2 EventProcessorClients.
Here are the log files only with info log level. Text _Attempting to claim ownership of partition_ occurs in the second log file 23 times and not as expected 16 times.
[EventProcessorClient1.log](https://github.com/Azure/azure-sdk-for-java/files/5001755/EventProcessorClient1.log)
[EventProcessorClient2.log](https://github.com/Azure/azure-sdk-for-java/files/5001756/EventProcessorClient2.log)
If it is necessary I can run it with bug level.

**Comment by srnagar** [comment]
@Piskous I have submitted a [patch](https://github.com/Azure/azure-sdk-for-java/commit/665a605dd33f63d7914ac052a31cb79bdce6f02e) to fix this issue. It should be available in the next release but please let me know if you would be interested in trying out the devfeed version before the actual release.

**Comment by Piskous** [comment]
Thank you for the fix. I would like to test it.

**Comment by srnagar** [comment]
@Piskous Could you please try out the beta version that has the fix?

https://mvnrepository.com/artifact/com.azure/azure-messaging-eventhubs/5.2.0-beta.1
https://mvnrepository.com/artifact/com.azure/azure-messaging-eventhubs-checkpointstore-blob/1.2.0-beta.1
