### ISSUE TITLE
[BUG] Full JMS 2.0 parity over AMQP is a feature supported only by a Premium Messaging namespace.

### ISSUE THREAD

**Issue by cuizhanming** [Azure/azure-sdk-for-java#13644]
**Describe the bug**
Recently, We started to see exception with Service Bus integration by using `azure-servicebus-jms-spring-boot-starter`

***Exception or Stack Trace***
Caused by: org.apache.qpid.jms.provider.exceptions.ProviderConnectionRemotelyClosedException: Full JMS 2.0 parity over AMQP is a feature supported only by a Premium Messaging namespace. TrackingId:26696ea708944480b39ce0a5c1a7b235_G27, SystemTracker:gateway7, Timestamp:2020-07-30T10:30:41 [condition = amqp:not-implemented]

**To Reproduce**
Register a Service Bus **Basic** Tier

***Code Snippet***
```
@JmsListener(containerFactory = "topicJmsListenerContainerFactory", destination = "topic-name", subscription = "subscription-name")
public void receiveMessage(JmsMessage message) throws JsonProcessingException, JMSException {
        JmsMessageFacade messageFacade = message.getFacade();
        String messageBody = null;
        if(messageFacade instanceof AmqpJmsBytesMessageFacade) {
            messageBody = new String(((AmqpJmsBytesMessageFacade) messageFacade).copyBody());
        } else if (messageFacade instanceof AmqpJmsTextMessageFacade) {
            messageBody = ((AmqpJmsTextMessageFacade) messageFacade).getText();
        }
       System.out.println(messageBody);
}
```

**Expected behavior**
Receive message

**Screenshots**

**Setup (please complete the following information):**
 - OS: macOS
 - IDE :  Intellij
 - Version of the Library used
 azure-servicebus-jms-spring-boot-starter: 2.3.2

**Additional context**

**Information Checklist**
Kindly make sure that you have added all the following information above and checkoff the required fields otherwise we will treat the issuer as an incomplete report
- [ ] Bug Description Added
- [ ] Repro Steps Added
- [ ] Setup information Added

**Comment by joshfree** [comment]
Thanks for filing this issue @cuizhanming.  @conniey could you please assist?

**Comment by conniey** [comment]
Hey @cuizhanming , Thanks for reporting this issue! As a prerequisite, a Premium SKU is needed to use JMS 2.0, this is by design. The documentation is [under the "Prerequisites" section](https://docs.microsoft.com/azure/developer/java/spring-framework/configure-spring-boot-starter-java-app-with-azure-service-bus#prerequisites). JMS 1.x should be supported by both Standard and Premium SKUs.

**Comment by shankarsama** [comment]
@cuizhanming  Is this an existing application that started failing recently ?

**Comment by shankarsama** [comment]
Reopening this issue to understand further what's really happening here.

**Comment by cuizhanming** [comment]
@shankarsama Yeah, the error only started from this Thursday. We were able to consuming messages with same SDK before then.

**Comment by yvgopal** [comment]
We resolved the issue and rolled out the upgrade to production. Your application should start working now. As a reminder, JMS is supported only in Premium Messaging. In standard, JMS partially worked in some cases. That partial support will remain in Standard messaging, but full JMS support will only be available in Premium Messaging.

**Comment by duydao** [comment]
@yvgopal We have the same Problem, we can't connect to the Standard Tier Azure Service Bus anymore:

`2020-08-10 07:25:45.319 ERROR 1 --- [enerContainer-4] o.s.j.l.DefaultMessageListenerContainer  : Could not refresh JMS Connection for destination 'srp-masterdata-import/subscriptions/mobile-api' - retrying using FixedBackOff{interval=5000, currentAttempts=40268, maxAttempts=unlimited}. Cause: Full JMS 2.0 parity over AMQP is a feature supported only by a Premium Messaging namespace. TrackingId:118ddb2c3f264e55b650bdec1378bc9d_G13, SystemTracker:gateway7, Timestamp:2020-08-10T07:25:45 [condition = amqp:not-implemented]
2020-08-10 07:25:45.319  INFO 1 --- [dc3db7db7:40276] o.s.j.c.CachingConnectionFactory         : Encountered a JMSException - resetting the underlying JMS Connection`

- Does your upgrade also include the servers in west europe?
- How can we switch to JMS 1.1?

**Comment by carniwar** [comment]
Same problem here. We use Azure Spring boot starter for JMS (com.microsoft.azure:azure-servicebus-jms-spring-boot-starter:2.3.2). How can we configure it to use JMS 1.1?

**Comment by marianbendik** [comment]
Same issue as @carniwar mentioned above. How to continue using basic/standard tier with Azure Spring boot starter for JMS after the JMS 2.0 rolled out into premium only tier?

**Comment by carniwar** [comment]
@marianbendik I fixed it by using [https://github.com/amqphub/amqp-10-jms-spring-boot](https://github.com/amqphub/amqp-10-jms-spring-boot) with JMS 1.1 spec, azure-servicebus lib and only setting the connection string, the same way as in Azure Spring JMS module, like:
```
<dependency>
    <groupId>com.microsoft.azure</groupId>
    <artifactId>azure-servicebus</artifactId>
    <version>3.4.0</version>
</dependency>

<dependency>
    <groupId>org.amqphub.spring</groupId>
    <artifactId>amqp-10-jms-spring-boot-starter</artifactId>
    <version>2.3.3</version>
    <exclusions>
        <exclusion>
            <groupId>org.slf4j</groupId>
            <artifactId>log4j-over-slf4j</artifactId>
        </exclusion>
    </exclusions>
</dependency>

<dependency>
    <groupId>org.apache.geronimo.specs</groupId>
    <artifactId>geronimo-jms_1.1_spec</artifactId>
    <version>1.1.1</version>
</dependency>
```

I created `JmsConnectionFactory` with the following bean:
```
@Configuration
public class AzureServiceBusConfiguration {

  private final ConnectionStringBuilder connectionStringBuilder;

  public AzureServiceBusConfiguration(
      @Value("${spring.jms.servicebus.connection-string}") String connectionString) {
    connectionStringBuilder = new ConnectionStringBuilder(connectionString);
  }

  @Bean
  public JmsConnectionFactory jmsConnectionFactory(
      ObjectProvider<List<AMQP10JMSConnectionFactoryCustomizer>> factoryCustomizers) {
    var properties = new AMQP10JMSProperties();
    properties.setRemoteUrl(amqpRemoteUrl());
    properties.setUsername(amqpUsername());
    properties.setPassword(amqpPassword());
    return new AMQP10JMSConnectionFactoryFactory(properties, factoryCustomizers.getIfAvailable())
        .createConnectionFactory(JmsConnectionFactory.class);
  }

  private String amqpRemoteUrl() {
    return "amqps://" + connectionStringBuilder.getEndpoint().getHost();
  }

  private String amqpUsername() {
    return connectionStringBuilder.getSasKeyName();
  }

  private String amqpPassword() {
    return connectionStringBuilder.getSasKey();
  }
}
```

And `MessageListener` needs to use Message object from JMS 1.1 definition:
```
@Slf4j
@Component
public class TextMessageListener implements MessageListener {

  @Override
  public void onMessage(Message message) {
    try {
      var textMessage = (TextMessage) message;
      LOG.info(textMessage.getText());
  }
}
```

**Comment by vlavasa** [comment]
@carniwar Your fix works! Thanks you

**Comment by duydao** [comment]
The error only occurs with azure-servicebus-jms-spring-boot-starter:2.3.2, it's not thrown with 2.3.1

**Comment by Chuy288** [comment]
In case anyone needs to set JMS 1.1 this worked for me:

`@Bean
    public ConnectionFactory connectionFactory() {
        AzureServiceBusJMSProperties properties = new AzureServiceBusJMSProperties();
        properties.setConnectionString(connectionString);
        properties.setIdleTimeout(Integer.valueOf(idleTimeout));
        properties.setPricingTier(pricingTier); // set here "standard" or "basic"

        NonPremiumServiceBusJMSAutoConfiguration jmsAutoConfiguration = new NonPremiumServiceBusJMSAutoConfiguration(properties);
        return jmsAutoConfiguration.jmsConnectionFactory();
    }`

**Comment by Chuy288** [comment]
In case anyone needs to set JMS 1.1 here's a snippet:

```
    @Bean
    public ConnectionFactory connectionFactory() {
        AzureServiceBusJMSProperties properties = new AzureServiceBusJMSProperties();
        properties.setConnectionString(connectionString);
        properties.setIdleTimeout(Integer.valueOf(idleTimeout));
        properties.setPricingTier(pricingTier);

        NonPremiumServiceBusJMSAutoConfiguration jmsAutoConfiguration = new NonPremiumServiceBusJMSAutoConfiguration(properties);
        return jmsAutoConfiguration.jmsConnectionFactory();
    }
```
