### ISSUE TITLE
[Tables] Implement inheritance-based TableEntity for representing fields in the table

### ISSUE THREAD

**Issue by conniey** [Azure/azure-sdk-for-java#13692]
In the original track 1 SDK, users extend from the TableEntity class and decorate it with properties. Underneath, the library does magic to turn it into a map of properties, then publish it to the service.
In our current design, we just return them the `Map<String,Object>` . It may be more user-friendly to consider the approach the old library has taken.

Example is here, where they extend from TableServiceEntity. https://docs.microsoft.com/azure/cosmos-db/table-storage-how-to-use-java#add-an-entity-to-a-table

**Comment by bsiegel** [comment]
Ensure that serializing and deserializing enum properties also works as expected.
