### ISSUE TITLE
Update spring-boot-starter-storage README file after spring-cloud-azure migration is done

### ISSUE THREAD

**Issue by saragluna** [Azure/azure-sdk-for-java#13723]
Now in the [README.md](https://github.com/Azure/azure-sdk-for-java/tree/master/sdk/spring/azure-spring-boot-starter-storage) of spring-boot-starter-storage we only state that the starter is deprecated. We should make it clear that users could use another storage starter, which implements the Spring Resource abstraction, we provide instead.

**Comment by zhoufenqin** [comment]
closing the issue
