### ISSUE TITLE
[BUG]  Error in Event Hub SDK version 5.1.1 ("There are no partitions in Event Hub") 

### ISSUE THREAD

**Issue by padmja-huddar** [Azure/azure-sdk-for-java#13727]
Same issue reported in  #12797 is reproducible with following set of libraries
JAVA version: JAVA 8
Azure.Messaging.EventHubs version: 'com.azure:azure-messaging-eventhubs:5.1.1'
Azure.Messaging.EventHubs.Checkpointstore version: 'com.azure:azure-messaging-eventhubs-checkpointstore-blob:1.1.1'
Azure.Storage.Blob version: 'com.azure:azure-storage-blob:12.7.0'

#12797 is closed with comment that "This issue has been identified as a known issue with the StorageBlob SDK version 12.6.0.
Fixed issue after upgrading StorageBlob SDK to version 12.6.1."

But it is reproducible with higher version of azure-storage-blob.

**Comment by joshfree** [comment]
Thanks for filing this issue with exact SDK versions, @padmja-huddar; @conniey could you please assist here?

**Comment by srnagar** [comment]
@padmja-huddar Could you please let us know if this error `There are no partitions in Event Hub` is happening always and never recovers or is this something that occurs intermittently? 

Just a note on the error: This usually occurs when there is a network error and the client was not able to get partition information from the service. The error message has been updated in 5.1.2 to make it clear that there was a timeout error when communicating with the service. This should auto-recover when the network connection is reinstated.

**Comment by srnagar** [comment]
@padmja-huddar Could you please let us know if this issue still exists? Also, we updated the AMQP layer to improve reliability in the latest releases. Could you please try out the new versions? 
azure-messaging-eventhubs - 5.2.0
azure-messaging-eventhubs-checkpointstore-blob - 1.2.0

If you are still seeing this issue, please re-open this ticket.
