### ISSUE TITLE
Add groupBy query test in ReadMyWrites workflow test

### ISSUE THREAD

**Issue by xinlian12** [Azure/azure-sdk-for-java#13753]

**Comment by kushagraThapar** [comment]
@xinlian12  - are we planning to work on this ?

**Comment by kushagraThapar** [comment]
@xinlian12  what is the reason for adding groupBy query to ReadMyWrites workflow? Do we still need it now?
Please re-open this issue if we should still have it. (given we don't do ReadMyWrites testing anymore now).
