### ISSUE TITLE
[FEATURE REQ] Cosmos createItem accepts row level Time To Live (TTL)

### ISSUE THREAD

**Issue by JanneKataja-TomTom** [Azure/azure-sdk-for-java#13750]
**Is your feature request related to a problem? Please describe.**
Using Cosmos DB to store sessions, I wish to use the Time To Live (TTL) for removing expired data.
This is to use spare RU/s for clean-up and thus avoid running  out of capacity.
Currently TTL can be configured on container level using the Cosmos DB Java SDK v4, but not for individual rows.
I wish to use row level TTL to only have valid sessions in the database.

**Describe the solution you'd like**
Cosmos DB `createItem` and `upsert` accepts TTL for the item to be created.
Compare with the Dynamo DB Java API.

**Describe alternatives you've considered**
Setting Container TTL with maximum possible session validity time.
This requires additional capacity for the database.

**Comment by joshfree** [comment]
Thanks for filing this issue @JanneKataja-TomTom; someone from the `Cosmos` team will follow up with you shortly.

**Comment by kirankumarkolli** [comment]
TTL per document is part of the document/Item contract. 
Can the application include TTL in the input types?

ref: [https://docs.microsoft.com/en-us/azure/cosmos-db/time-to-live]()
[https://docs.microsoft.com/en-us/azure/cosmos-db/how-to-time-to-live?tabs=dotnetv2%2Cjavav4#set-time-to-live-on-an-item]()

**Comment by JanneKataja-TomTom** [comment]
Thanks for your response. I wasn't aware of being possible to set `ttl` field, I was only looking at the client library as well as the possible request and response headers. I would prefer not to change the data classes to set a database layer option. For example, also the consistency level is not set as a field in the request body, but in the headers. btw the links work when text is copied to browser but the link on both points to this ticket.

**Comment by kushagraThapar** [comment]
@kirankumarkolli  - any update on this ?

**Comment by kushagraThapar** [comment]
@JanneKataja-TomTom - currently the only option to set TTL on java SDK is this : https://docs.microsoft.com/en-us/azure/cosmos-db/how-to-time-to-live?tabs=dotnetv2%2Cjavav4#java-set-ttl-item
Closing this issue.
