### ISSUE TITLE
Beta4: azure.virtualMachines().list() java.lang.RuntimeException: com.fasterxml.jackson.core.JsonParseException: Unexpected character #1208

### ISSUE THREAD

**Issue by masarlabs** [Azure/azure-sdk-for-java#1375]
Hi 
the problem of Issue #1208 is still present in BETA4, incorrectly escapes '?' to '%3F'

INFO: --> GET https://management.azure.com/subscriptions/9bf80712-ea01-4ee9-b119-821915e971d8/providers/Microsoft.Compute/virtualMachines%3Fapi-version=2016-03-30&$skiptoken=d8b6b639-04ce-4eb8-8b6d-352e5bb5317e!/Subscriptions/9bf80712-ea01-4ee9-b119-821915e971d8/ResourceGroups/WFCXSYTMLR-RG/VMs/WFCXSYTMLR02 http/1.1

**Comment by jianghaolu** [comment]
Please find the beta4.1 release which contains a hotfix for this issue.

**Comment by masarlabs** [comment]
Problem fixed in 4.1.

Thanks
