### ISSUE TITLE
EventHubConsumerClient Apache Qpid memory leak

### ISSUE THREAD

**Issue by stevebasher** [Azure/azure-sdk-for-java#13775]
I am reading events from an Azure EventHub cluster synchronously via the receiveFromPartition method on the EventHubConsumerClient class.

I create the client once like so:

```
EventHubConsumerClient eventHubConsumerClient = new EventHubClientBuilder()
            .connectionString(eventHubConnectionString)
            .consumerGroup(consumerGroup)
            .buildConsumerClient());
```

I then just use a ScheduledExecutorService to retrieve events every 1.5s via:

```
IterableStream<PartitionEvent> receivedEvents = eventHubConsumerClient.receiveFromPartition(
                partitionId, 1, eventPosition);
```

The equivalent logic in V3 of the SDK worked fine (using PartitionReceivers), but now I am seeing OOMs in my JVM.

Running a profiler against a local version of the logic I see the majority of the heap (90%, mainly in OG) is being taken up by byte[]s, referenced by `org.apache.qpid.proton.codex.CompositeReadableBuffer`. This pattern is not present when I profile the V3 logic.

What could be causing a leak of the AMQP messages here, do I need to interact with the SDK further, for example close a connection that I'm not aware of after each call?

**Comment by stevebasher** [comment]
Heap dump classes:
<img width="1336" alt="Screen Shot 2020-08-04 at 10 27 18 AM" src="https://user-images.githubusercontent.com/8497007/89277824-3b08c100-d63d-11ea-8937-ce44eff4eaa1.png">

Reference paths for byte[] instances:
<img width="1327" alt="Screen Shot 2020-08-04 at 10 27 26 AM" src="https://user-images.githubusercontent.com/8497007/89277817-393efd80-d63d-11ea-91e4-423170459e56.png">

**Comment by srnagar** [comment]
@stevebasher Thanks for reporting the issue. We are looking into this and will have an update on our findings.

**Comment by stevebasher** [comment]
@srnagar thanks for fixing this! When can I expect a release to be cut and ready for consumption via maven containing this fix?

**Comment by srnagar** [comment]
@stevebasher Could you please try out the beta version that has the fix?

https://mvnrepository.com/artifact/com.azure/azure-messaging-eventhubs/5.2.0-beta.2

**Comment by stevebasher** [comment]
@srnagar Apologies for the delayed response, I've been able to test this and confirm this seems to have fixed the memory leak issue :) Any idea when this might be released into a non-beta version?

**Comment by srnagar** [comment]
@stevebasher This will be released as part of our September release cycle.
