### ISSUE TITLE
Network Security Group Tag(s): Azure Datacenter / Azure Storage for region

### ISSUE THREAD

**Issue by paulojohnj** [Azure/azure-sdk-for-java#1380]
This may not be the place to ask but was wondering if there is or will be tags for the ip ranges of azure storage or azure data-centers by region. There is no class for these tags, but values such as AzureLoadBalancer and VirtualNetwork, work in the SDK for NSGs the same way they work in the GUI. There does not appear to be any way to know the ip ranges to allow outbound traffic to (by region) for these services (which are required for VM extensions). Azure does publish the Ip ranges of their datacenters which can then be correlated, but this does not work for regions such as us gov virginia etc.

**Comment by martinsawicki** [comment]
no such feature on the service side is exposed
