### ISSUE TITLE
 Service or property not registered - Azure KeyVault

### ISSUE THREAD

**Issue by srinraghavan** [Azure/azure-sdk-for-java#1382]
I'm using the azure key vault plugin. It seems to run fine in eclipse. However, when I run via command line I get the following error:

Exception in thread "main" java.lang.RuntimeException: Service or property notegistered:  com.microsoft.azure.keyvault.KeyVaultClient class org.apache.http.pl.client.HttpClientBuilder

Specifically this maven plugin
[<dependency>
      <groupId>com.microsoft.azure</groupId>
      <artifactId>azure-keyvault</artifactId>
      <version>0.9.3</version>
</dependency>](url)

I tried shading my jar but this did not help. 

Any suggestions would be great. Thanks!

**Comment by dasbraja** [comment]
I am having same issues, I am reading secrets from KV and writing to eventHub. 

In runtime command line I have following error.

Exception in thread "main" java.lang.RuntimeException: Service or property not registered:  com.microsoft.azure.keyvault.KeyVaultClient interface com.microsoft.azure.keyvault.KeyVaultClient
	at com.microsoft.windowsazure.core.DefaultBuilder.build(DefaultBuilder.java:198)
	at com.microsoft.windowsazure.Configuration.create(Configuration.java:119)
	at com.microsoft.azure.keyvault.KeyVaultClientService.create(KeyVaultClientService.java:48)

I have following library dependency.

"com.microsoft.azure" % "azure-eventhubs" % "0.7.5",
  "com.microsoft.azure" % "azure-keyvault" % "0.9.3",

**Comment by dasbraja** [comment]
it fixes issue with following assembly strategy.

assemblyMergeStrategy in assembly := {
  case x if Assembly.isConfigFile(x) => MergeStrategy.concat
  case x if x.endsWith("io.netty.versions.properties") => MergeStrategy.first
  case x if x.endsWith("jersey-module-version") => MergeStrategy.last
  case PathList("META-INF", xs @ _*) => (xs map {_.toLowerCase}) match {
    case ("manifest.mf" :: Nil) | ("index.list" :: Nil) | ("dependencies" :: Nil) => MergeStrategy.discard
    case ps @ (x :: xs) if ps.last.endsWith(".sf") || ps.last.endsWith(".dsa") => MergeStrategy.discard
    case "plexus" :: xs => MergeStrategy.discard
    case "services" :: xs => MergeStrategy.filterDistinctLines
    case ("spring.schemas" :: Nil) | ("spring.handlers" :: Nil) => MergeStrategy.filterDistinctLines
    case _ => MergeStrategy.first
  }

**Comment by martinsawicki** [comment]
the KeyVault client library is not in this repo anymore, so if this is still an issue, it should go there:
https://github.com/azure/azure-keyvault-java
