### ISSUE TITLE
[QUERY] Database level  RU limit. doesn't work

### ISSUE THREAD

**Issue by Abhisar** [Azure/azure-sdk-for-java#13882]
**Query/Question**
Based on Cosmos document we can set RU limit on  database level which is in turn shared among all containers inside it.
So I manually created a database with setting through put of 400 .
But when i start my server , based on all the @Document annotations when it creates containers , each container is getting assigned by default a RU of 4000.  Which is wrong .

So how do i programatically config to limit containers RU to database level RU
 I found this in JAVA V4 Sdk but how do i do it using cosmos starter package:
  // Container and autoscale throughput settings
CosmosContainerProperties autoscaleContainerProperties 
        = new CosmosContainerProperties(containerName, "/lastName");
ThroughputProperties autoscaleThroughputProperties 
        = ThroughputProperties.createAutoscaledThroughput(4000); //Set autoscale max RU/s

***Why is this not a Bug or a feature Request?***
A clear explanation of why is this not a bug or a feature request?

**Setup (please complete the following information if applicable):**
 - IDE : [e.g. IntelliJ]
 - <dependency>
			<groupId>com.microsoft.azure</groupId>
			<artifactId>azure-cosmosdb-spring-boot-starter</artifactId>
			<version>2.3.2</version>
     </dependency>
 
 **Information Checklist**
 Kindly make sure that you have added all the following information above and checkoff the required fields otherwise we will treat the issuer as an incomplete report
- [x] Query Added
- [x] Setup information Added

**Comment by Abhisar** [comment]
Based on my understand i figured out that @Document annotation by default sets it to 4000 RU if we dont specify anything. So how do i stop it and force it to use the RU of database level ???

**Comment by Abhisar** [comment]
As you can see , here is the code of @Document annotation 

  `  private Integer getRequestUnit(Class<?> domainType) {
        Integer ru = Integer.parseInt(Constants.DEFAULT_REQUEST_UNIT);
        final Document annotation = domainType.getAnnotation(Document.class);

        if (annotation != null && annotation.ru() != null && !annotation.ru().isEmpty()) {
            ru = Integer.parseInt(annotation.ru());
        }
        return ru;
    }
`
Here it always forces to creates container with DEFAULT_REQUEST_UNIT  and there is no conf to ignore  and instead use shared RU of DB level.
Please help fixing or providing a option to do so

**Comment by joshfree** [comment]
Thanks for filing these questions, @Abhisar.  Someone from the `azure-spring` team will follow up on these azure-cosmosdb-spring-boot-starter specific questions

**Comment by kushagraThapar** [comment]
@Abhisar  - we have these features in our backlog. You can track them here: 
https://github.com/Azure/azure-sdk-for-java/issues/12711
https://github.com/Azure/azure-sdk-for-java/issues/12715

**Comment by Abhisar** [comment]
I see . Do we have an approximate timeline about when it's expected to get out ?

**Comment by kushagraThapar** [comment]
@Abhisar - not yet, this is still in our backlog, will update this issue when we plan to support it.

**Comment by kushagraThapar** [comment]
This issue has been fixed. @Abhisar , I am going to close this issue. If you still see the issue, please feel free to comment or re-open this.
