### ISSUE TITLE
[BUG] Documentation and setting not matched

### ISSUE THREAD

**Issue by laxmanc** [Azure/azure-sdk-for-java#13900]
**Describe the bug**
In the service-bus documentation in the example (https://github.com/Azure/azure-sdk-for-java/blob/master/sdk/servicebus/azure-messaging-servicebus/src/samples/java/com/azure/messaging/servicebus/ReceiveMessageAsyncSample.java)  every where it says  "fully-qualified-namespace" will look similar to "{your-namespace}.servicebus.windows.net"  if we give like this building of client is failing we need to prefix with "sb"  so correct docuementation should be "sb://{your-namespace}.servicebus.windows.net".

Failure is happening in class ServiceBusClientBuilder at 

 [return credential(properties.getEndpoint().getHost(), tokenCredential);]

getHost is failing

***Exception or Stack Trace***
Add the exception log and stack trace if available

**To Reproduce**

***Code Snippet***
Add the code snippet that causes the issue.

**Expected behavior**

**Screenshots**

**Setup (please complete the following information):**
 - IDE : [e.g. IntelliJ]
 - Version of the Library used

**Additional context**

**Information Checklist**
Kindly make sure that you have added all the following information above and checkoff the required fields otherwise we will treat the issuer as an incomplete report
- [ ] Bug Description Added
- [ ] Repro Steps Added
- [ ] Setup information Added

**Comment by hemanttanwar** [comment]
@laxmanc Thank you for reporting this. We are looking into this and fix it soon. We will update you when we release this fix.

**Comment by hemanttanwar** [comment]
@laxmanc We have fixed . If user do not specify `sb://`, the library will add this for you. This will be released in `7.0.0-beta.6` in September first week.
