### ISSUE TITLE
VirtualMachineSize does not show NIC data

### ISSUE THREAD

**Issue by paulojohnj** [Azure/azure-sdk-for-java#1390]
VirtualMachineSize displays cpu, ram, and disk info, but does not show any information about number of NICs supported.

**Comment by anuchandy** [comment]
Even though msdn doc shows number of NICs corresponds to each size, this property is not yet exposed in the rest api https://github.com/Azure/azure-rest-api-specs/blob/master/arm-compute/2016-03-30/swagger/compute.json#L2640. 

Let me check with compute team about their plan for exposing this property.

**Comment by paulojohnj** [comment]
Thank you. Being able to live query available sizes for a region and getting all information about the size is much more efficient than doing so and comparing to known data

**Comment by anuchandy** [comment]
Unfortunately `number of NIC supported` is still not exposed in the VirtualMachineSize model, latest swagger model is [here](https://github.com/Azure/azure-rest-api-specs/blob/c97a18ed775029207715b09c80761334724740b9/specification/compute/resource-manager/Microsoft.Compute/2017-03-30/compute.json#L3571)

**Comment by martinsawicki** [comment]
not actionable until the Compute service exposes access to this programmatically

**Comment by praries880** [comment]
[still](https://github.com/Azure/azure-rest-api-specs/blob/master/specification/compute/resource-manager/Microsoft.Compute/stable/2018-10-01/compute.json#L4492) not supported.

**Comment by Drewm3** [comment]
Cleaning up old issues from 2016 - 2018. Please reactivate this if it is still a problem.
