### ISSUE TITLE
[BUG]EvenHub eventProcessorClient when exception happened, it didn't resume as supposed it should be

### ISSUE THREAD

**Issue by 123Jun321** [Azure/azure-sdk-for-java#13924]
**Describe the bug**
Hi team, it seems that when some exceptions happened, the eventProcessorClient won't reconnect.

background: we found our client didn't consume the message as it was supposed to do, and from Azure technology support, we know that the Event Hub was upgrading during the time, so it seems that there were some connect exceptions but the eventProcessorClient didn't resume after that.

***Exception or Stack Trace***
{"time":"2020-08-03 03:56:48.063", "level":"ERROR", "thread":"elastic-30", "appName":"events-service", "traceId":"", "spanId":"", "url":"", "clientIp":"", "method":"", "elapse":"", "code":"", "message":"", "class":"c.h.socialhub.eventhub.EventHub", "line":"EventHub.java:120", "msg":"Error occurred while processing events The connection was inactive for more than the allowed 240000 milliseconds and is closed by container 'e9e9a440d5684a4e804091b8c14e372c_G1'., errorContext[NAMESPACE: shprod-market.servicebus.chinacloudapi.cn, PATH: $management, REFERENCE_ID: mgmt:sender, LINK_CREDIT: 46]"}
{"time":"2020-08-03 03:56:52.619", "level":"ERROR", "thread":"parallel-3", "appName":"events-service", "traceId":"", "spanId":"", "url":"", "clientIp":"", "method":"", "elapse":"", "code":"", "message":"", "class":"c.a.m.e.PartitionBasedLoadBalancer", "line":"ClientLogger.java:347", "msg":"There are no partitions in Event Hub memberinfo"}
{"time":"2020-08-03 03:56:52.619", "level":"ERROR", "thread":"parallel-2", "appName":"events-service", "traceId":"", "spanId":"", "url":"", "clientIp":"", "method":"", "elapse":"", "code":"", "message":"", "class":"c.a.m.e.PartitionBasedLoadBalancer", "line":"ClientLogger.java:347", "msg":"There are no partitions in Event Hub scoreandtiersyn2tmall"}
{"time":"2020-08-03 03:56:52.619", "level":"ERROR", "thread":"parallel-2", "appName":"events-service", "traceId":"", "spanId":"", "url":"", "clientIp":"", "method":"", "elapse":"", "code":"", "message":"", "class":"c.h.socialhub.eventhub.EventHub", "line":"EventHub.java:120", "msg":"Error occurred while processing events There are no partitions in Event Hub scoreandtiersyn2tmall"}
{"time":"2020-08-03 03:56:52.619", "level":"ERROR", "thread":"parallel-3", "appName":"events-service", "traceId":"", "spanId":"", "url":"", "clientIp":"", "method":"", "elapse":"", "code":"", "message":"", "class":"c.h.socialhub.eventhub.EventHub", "line":"EventHub.java:120", "msg":"Error occurred while processing events There are no partitions in Event Hub memberinfo"}
{"time":"2020-08-03 03:57:02.194", "level":"ERROR", "thread":"parallel-2", "appName":"events-service", "traceId":"", "spanId":"", "url":"", "clientIp":"", "method":"", "elapse":"", "code":"", "message":"", "class":"c.a.m.e.PartitionBasedLoadBalancer", "line":"ClientLogger.java:347", "msg":"There are no partitions in Event Hub couponstatussyn2sino"}
{"time":"2020-08-03 03:57:02.194", "level":"ERROR", "thread":"parallel-2", "appName":"events-service", "traceId":"", "spanId":"", "url":"", "clientIp":"", "method":"", "elapse":"", "code":"", "message":"", "class":"c.h.socialhub.eventhub.EventHub", "line":"EventHub.java:120", "msg":"Error occurred while processing events There are no partitions in Event Hub couponstatussyn2sino"}
{"time":"2020-08-03 03:57:48.066", "level":"ERROR", "thread":"single-1", "appName":"events-service", "traceId":"", "spanId":"", "url":"", "clientIp":"", "method":"", "elapse":"", "code":"", "message":"", "class":"c.a.c.a.i.ReactorReceiver", "line":"ClientLogger.java:347", "msg":"connectionId[MF_7f1ed6_1596401051494] linkName[2_264c04_1596401051495] entityPath[producecoupon/ConsumerGroups/$default/Partitions/2] Error occurred in link.
The connection was inactive for more than the allowed 240000 milliseconds and is closed by container '7e30972cab4047f79c77121dd75fe6cb_G31'., errorContext[NAMESPACE: shprod-market.servicebus.chinacloudapi.cn, PATH: producecoupon/ConsumerGroups/$default/Partitions/2, REFERENCE_ID: 2_264c04_1596401051495, LINK_CREDIT: 469]"}
{"time":"2020-08-03 03:57:48.067", "level":"ERROR", "thread":"elastic-43", "appName":"events-service", "traceId":"", "spanId":"", "url":"", "clientIp":"", "method":"", "elapse":"", "code":"", "message":"", "class":"c.h.socialhub.eventhub.EventHub", "line":"EventHub.java:120", "msg":"Error occurred while processing events The connection was inactive for more than the allowed 240000 milliseconds and is closed by container '7e30972cab4047f79c77121dd75fe6cb_G31'., errorContext[NAMESPACE: shprod-market.servicebus.chinacloudapi.cn, PATH: producecoupon/ConsumerGroups/$default/Partitions/2, REFERENCE_ID: 2_264c04_1596401051495, LINK_CREDIT: 469]"}
{"time":"2020-08-03 03:57:48.067", "level":"ERROR", "thread":"single-1", "appName":"events-service", "traceId":"", "spanId":"", "url":"", "clientIp":"", "method":"", "elapse":"", "code":"", "message":"", "class":"c.a.c.a.i.RequestResponseChannel<cbs>", "line":"ClientLogger.java:347", "msg":"Exception in RequestResponse links. Disposing and clearing unconfirmed sends.
The connection was inactive for more than the allowed 240000 milliseconds and is closed by container '7e30972cab4047f79c77121dd75fe6cb_G31'., errorContext[NAMESPACE: shprod-market.servicebus.chinacloudapi.cn, PATH: $cbs, REFERENCE_ID: cbs:sender, LINK_CREDIT: 73]"}
{"time":"2020-08-03 03:57:48.067", "level":"ERROR", "thread":"single-1", "appName":"events-service", "traceId":"", "spanId":"", "url":"", "clientIp":"", "method":"", "elapse":"", "code":"", "message":"", "class":"c.a.c.a.i.ReactorSession", "line":"ClientLogger.java:347", "msg":"[cbs-session] Error occurred in session error handler.
onSessionRemoteClose connectionId[MF_7f1ed6_1596401051494], entityName[cbs-session], condition[Error{condition=null, description='null', info=null}], errorContext[NAMESPACE: shprod-market.servicebus.chinacloudapi.cn, PATH: cbs-session]"}

**To Reproduce**

***Code Snippet***
```java
 eventProcessorClient = new EventProcessorClientBuilder()
                .consumerGroup(EventHubClientBuilder.DEFAULT_CONSUMER_GROUP_NAME)
                .connectionString(currentEventHubProperty.getConnectionString(), this.topic)
                .checkpointStore(new BlobCheckpointStore(blobContainerAsyncClient))
                .processEvent(eventContext -> {
                    // 异步登记偏移量：
                    eventContext.updateCheckpoint();
                    // 获取数据：
                    EventData event = eventContext.getEventData();
                    PartitionContext partitionContext = eventContext.getPartitionContext();

                    System.out.printf("Receive message from Partition id: %s. Sequence Number: %d. Contents: %s\n",
                            partitionContext.getPartitionId(), event.getSequenceNumber(),
                            new String(event.getBody(), Charset.defaultCharset()));

                })
                .processError(errorContext -> System.out.printf("Error occurred while processing events[%s] : %s\n ", this.topic,  errorContext.getThrowable().getMessage()))
                .buildEventProcessorClient();
```
**Expected behavior**

**Screenshots**

**Setup (please complete the following information):**
 - OS: [e.g. iOS] Windows 
 - IDE : [e.g. IntelliJ] Eclipse 
 - Version of the Library used
<dependency>
    <groupId>com.azure</groupId>
    <artifactId>azure-messaging-eventhubs</artifactId>
    <version>5.1.1</version>
</dependency>
<dependency>
    <groupId>com.azure</groupId>
    <artifactId>azure-messaging-eventhubs-checkpointstore-blob</artifactId>
    <version>1.1.1</version>
</dependency>

**Additional context**
We found there were some similar issues but this issue seemed wasn't fixed in 5.1.1

**Comment by srnagar** [comment]
@123Jun321 Thanks for reporting this issue. A similar issue has been reported and is currently being worked on. 

https://github.com/Azure/azure-sdk-for-java/issues/13420

**Comment by 123Jun321** [comment]
hi  @srnagar  thank you
