### ISSUE TITLE
BlobClient.upload fails when using CustomerProvidedKey

### ISSUE THREAD

**Issue by ChimneyCake** [Azure/azure-sdk-for-java#13936]
Hi,
I have tried uploading blob to azure storage BlobClient and BlobServiceClient using Azure SDK 12 for Java . I'd like to set CustomerProvidedKey, but when I build BlobServiceClient as `new BlobServiceClientBuilder().connectionString(connectionString).customerProvidedKey(customerProvidedKey).buildClient();` and then I try to upload blob as `blobClient.upload(new ByteArrayInputStream(content), content.length);` , but I am getting and exception

>java.lang.NoSuchMethodError: com.azure.core.util.CoreUtils.bomAwareToString([BLjava/lang/String;)Ljava/lang/String; at com.azure.core.http.netty.NettyAsyncHttpClient$ReactorNettyHttpResponse.lambda$getBodyAsString$4(NettyAsyncHttpClient.java:215) ~[azure-core-http-netty-1.5.1.jar:na] at reactor.core.publisher.FluxMap$MapSubscriber.onNext(FluxMap.java:100) ~[reactor-core-3.3.4.RELEASE.jar:3.3.4.RELEASE] at reactor.core.publisher.FluxDoFinally$DoFinallySubscriber.onNext(FluxDoFinally.java:123) ~[reactor-core-3.3.4.RELEASE.jar:3.3.4.RELEASE] at reactor.core.publisher.FluxHandle$HandleSubscriber.onNext(FluxHandle.java:112) ~[reactor-core-3.3.4.RELEASE.jar:3.3.4.RELEASE] at reactor.core.publisher.FluxMap$MapConditionalSubscriber.onNext(FluxMap.java:213) ~[reactor-core-3.3.4.RELEASE.jar:3.3.4.RELEASE] at reactor.core.publisher.FluxDoFinally$DoFinallySubscriber.onNext(FluxDoFinally.java:123) ~[reactor-core-3.3.4.RELEASE.jar:3.3.4.RELEASE] at reactor.core.publisher.FluxHandleFuseable$HandleFuseableSubscriber.onNext(FluxHandleFuseable.java:178) ~[reactor-core-3.3.4.RELEASE.jar:3.3.4.RELEASE] at reactor.core.publisher.FluxContextStart$ContextStartSubscriber.onNext(FluxContextStart.java:103) ~[reactor-core-3.3.4.RELEASE.jar:3.3.4.RELEASE] at reactor.core.publisher.Operators$MonoSubscriber.complete(Operators.java:1712) ~[reactor-core-3.3.4.RELEASE.jar:3.3.4.RELEASE] at reactor.core.publisher.MonoCollectList$MonoCollectListSubscriber.onComplete(MonoCollectList.java:121) ~[reactor-core-3.3.4.RELEASE.jar:3.3.4.RELEASE] at reactor.core.publisher.FluxPeek$PeekSubscriber.onComplete(FluxPeek.java:252) ~[reactor-core-3.3.4.RELEASE.jar:3.3.4.RELEASE] at reactor.core.publisher.FluxMap$MapSubscriber.onComplete(FluxMap.java:136) ~[reactor-core-3.3.4.RELEASE.jar:3.3.4.RELEASE] at reactor.netty.channel.FluxReceive.terminateReceiver(FluxReceive.java:421) ~[reactor-netty-0.9.6.RELEASE.jar:0.9.6.RELEASE] at reactor.netty.channel.FluxReceive.drainReceiver(FluxReceive.java:211) ~[reactor-netty-0.9.6.RELEASE.jar:0.9.6.RELEASE] at reactor.netty.channel.FluxReceive.onInboundComplete(FluxReceive.java:369) ~[reactor-netty-0.9.6.RELEASE.jar:0.9.6.RELEASE] at reactor.netty.channel.ChannelOperations.onInboundComplete(ChannelOperations.java:367) ~[reactor-netty-0.9.6.RELEASE.jar:0.9.6.RELEASE] at reactor.netty.channel.ChannelOperations.terminate(ChannelOperations.java:416) ~[reactor-netty-0.9.6.RELEASE.jar:0.9.6.RELEASE] at reactor.netty.http.client.HttpClientOperations.onInboundNext(HttpClientOperations.java:612) ~[reactor-netty-0.9.6.RELEASE.jar:0.9.6.RELEASE] at reactor.netty.channel.ChannelOperationsHandler.channelRead(ChannelOperationsHandler.java:90) ~[reactor-netty-0.9.6.RELEASE.jar:0.9.6.RELEASE] at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) [netty-transport-4.1.48.Final.jar:4.1.48.Final] at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) [netty-transport-4.1.48.Final.jar:4.1.48.Final] at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) [netty-transport-4.1.48.Final.jar:4.1.48.Final] at io.netty.channel.CombinedChannelDuplexHandler$DelegatingChannelHandlerContext.fireChannelRead(CombinedChannelDuplexHandler.java:436) [netty-transport-4.1.48.Final.jar:4.1.48.Final] at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:321) [netty-codec-4.1.48.Final.jar:4.1.48.Final] at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:295) [netty-codec-4.1.48.Final.jar:4.1.48.Final] at io.netty.channel.CombinedChannelDuplexHandler.channelRead(CombinedChannelDuplexHandler.java:251) [netty-transport-4.1.48.Final.jar:4.1.48.Final] at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) [netty-transport-4.1.48.Final.jar:4.1.48.Final] at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) [netty-transport-4.1.48.Final.jar:4.1.48.Final] at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) [netty-transport-4.1.48.Final.jar:4.1.48.Final] at io.netty.handler.ssl.SslHandler.unwrap(SslHandler.java:1486) [netty-handler-4.1.48.Final.jar:4.1.48.Final] at io.netty.handler.ssl.SslHandler.decodeNonJdkCompatible(SslHandler.java:1247) [netty-handler-4.1.48.Final.jar:4.1.48.Final] at io.netty.handler.ssl.SslHandler.decode(SslHandler.java:1284) [netty-handler-4.1.48.Final.jar:4.1.48.Final] at io.netty.handler.codec.ByteToMessageDecoder.decodeRemovalReentryProtection(ByteToMessageDecoder.java:498) [netty-codec-4.1.48.Final.jar:4.1.48.Final] at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:437) [netty-codec-4.1.48.Final.jar:4.1.48.Final] at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:276) [netty-codec-4.1.48.Final.jar:4.1.48.Final] at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) [netty-transport-4.1.48.Final.jar:4.1.48.Final] at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) [netty-transport-4.1.48.Final.jar:4.1.48.Final] at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) [netty-transport-4.1.48.Final.jar:4.1.48.Final] at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410) [netty-transport-4.1.48.Final.jar:4.1.48.Final] at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) [netty-transport-4.1.48.Final.jar:4.1.48.Final] at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) [netty-transport-4.1.48.Final.jar:4.1.48.Final] at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919) [netty-transport-4.1.48.Final.jar:4.1.48.Final] at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:163) [netty-transport-4.1.48.Final.jar:4.1.48.Final] at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:714) [netty-transport-4.1.48.Final.jar:4.1.48.Final] at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:650) [netty-transport-4.1.48.Final.jar:4.1.48.Final] at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:576) [netty-transport-4.1.48.Final.jar:4.1.48.Final] at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:493) [netty-transport-4.1.48.Final.jar:4.1.48.Final] at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989) [netty-common-4.1.48.Final.jar:4.1.48.Final] at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) [netty-common-4.1.48.Final.jar:4.1.48.Final] at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) [netty-common-4.1.48.Final.jar:4.1.48.Final] at java.lang.Thread.run(Thread.java:748) [na:1.8.0_221]

When there is no customerProvidedKey(customerProvidedKey) part, I can successfully upload a blob. Is there anything wrong with this way of setting CustomerProvidedKey?

**Comment by alzimmermsft** [comment]
Hi @ChimneyCake, thank you for reporting this issue. Having a quick look at the stack trace I'm wondering if this is due to a version mismatch between `azure-storage-blob` and `azure-core-http-netty`/`azure-core`. If possible could you include your Maven/Gradle dependencies to help troubleshoot this further.

**Comment by ChimneyCake** [comment]
Hi @alzimmermsft I am not even using azure-core-http-netty package. Here is list of dependencies I am using:
```
<dependency>
    <groupId>com.azure</groupId>
    <artifactId>azure-storage-blob</artifactId>
    <version>12.6.0</version>
</dependency>
<dependency>
    <groupId>com.azure</groupId>
    <artifactId>azure-storage-blob-cryptography</artifactId>
   <version>12.6.1</version>
</dependency>
<dependency>
    <groupId>com.azure</groupId>
    <artifactId>azure-security-keyvault-keys</artifactId>
    <version>4.1.5</version>
</dependency>
```

**Comment by alzimmermsft** [comment]
Looking at the dependencies being used they pull different versions of common libraries such as `azure-core` and `azure-core-http-netty`. What is causing the issue being reported is the different versions of `azure-core` being used, between versions `1.4.0` and `1.5.0` new APIs were added. Based on the tree below a version of `azure-core-http-netty` expecting these code changes will be used but a version of `azure-core` that doesn't have them is used to how Maven will resolve. I'm not exactly certain why using or not using `CustomerProvidedKey` triggers the exception to be thrown but upgrading `azure-storage-blob` to a higher version should resolve the problem. Another solution, due to how Maven resolves dependencies, is listing the KeyVault dependency first in the POM as Maven resolves using depth first, left most (first listed) resolution.

(Generated using command `mvn dependency:tree -D verbose`, removed superfluous output)
```
+- com.azure:azure-storage-blob:jar:12.6.0:compile
|  +- com.azure:azure-core:jar:1.4.0:compile
|  \- com.azure:azure-storage-common:jar:12.6.0:compile
|     +- (com.azure:azure-core:jar:1.4.0:compile - omitted for duplicate)
|     \- (com.azure:azure-core-http-netty:jar:1.5.0:compile - omitted for conflict with 1.5.1)
+- com.azure:azure-storage-blob-cryptography:jar:12.6.1:compile
|  +- (com.azure:azure-core:jar:1.5.0:compile - omitted for conflict with 1.4.0)
|  +- com.azure:azure-core-http-netty:jar:1.5.1:compile
|  |  +- (com.azure:azure-core:jar:1.5.0:compile - omitted for conflict with 1.4.0)
|  \- (com.azure:azure-storage-blob:jar:12.6.1:compile - omitted for conflict with 12.6.0)
\- com.azure:azure-security-keyvault-keys:jar:4.1.5:compile
   +- (com.azure:azure-core:jar:1.6.0:compile - omitted for conflict with 1.4.0)
   \- (com.azure:azure-core-http-netty:jar:1.5.3:compile - omitted for conflict with 1.5.1)
```

**Comment by alzimmermsft** [comment]
@ChimneyCake, were you able to resolve your issue?

**Comment by ChimneyCake** [comment]
Hi @alzimmermsft, I have listed KeyVault dependency first as you suggested and that solved my issue. Thank you

**Comment by alzimmermsft** [comment]
Closing as resolved, if any issues like this pop up again please re-open this issue.
