### ISSUE TITLE
[Design] How to define regions for resources?

### ISSUE THREAD

**Issue by jianghaolu** [Azure/azure-sdk-for-java#1393]
There are 3 types of resources out there today.

1) It has a region and is unrelated to any other resources or resource groups (most common)
2) It inherits the region from some other resources (web app, CDN profile)
3) It doesn't have a region or region has to be "global" (domain, certificate)

We need to come up with a pattern to address all these 3 scenarios.

**Comment by martinsawicki** [comment]
hasn't really been too big of an issue one year later...
