### ISSUE TITLE
[Service Bus] Throw error when Entity Path in connection string does not match what is passed to the builder that create senders & receivers

### ISSUE THREAD

**Issue by ramya-rao-a** [Azure/azure-sdk-for-java#13952]
In v7 of the Service Bus package, the ServiceBusClient builder takes connection string which can have the EntityPath specified in it if the user copied it from the policy created for a queue or topic.

The builder to create senders and receivers expect the queue/topic/subscription name to be passed to them.

This issue is to ensure that if there is a mismatch between the two, we should throw an error.

The reason is that a connection string from a policy from one queue/topic when used with a different entity gives a not so helpful error today. We can pre-empt this and throw a meaningful error ourselves instead.

If we are already doing this, please add a comment here sharing the error message and close this issue

**Comment by YijunXieMS** [comment]
@hemanttanwar @ramya-rao-a @conniey 

There is already validation with informative error message. Any concerns?
 - "Cannot build client without setting either a queueName or topicName."
 - "Cannot build client with both queueName (%s) and topicName (%s) set."
 - "queueName (%s) is different than the connectionString's EntityPath (%s)."
 - "topicName (%s) is different than the connectionString's EntityPath (%s)."

Code is here:
https://github.com/Azure/azure-sdk-for-java/blob/eaf0db9a7d387ed21a9e0476f25b543cf8a9bf02/sdk/servicebus/azure-messaging-servicebus/src/main/java/com/azure/messaging/servicebus/ServiceBusClientBuilder.java#L407

**Comment by hemanttanwar** [comment]
@YijunXieMS  Looks good , We can close this issue.

**Comment by ramya-rao-a** [comment]
Agreed
