### ISSUE TITLE
resourcemanager Tests Fail Randomly

### ISSUE THREAD

**Issue by alzimmermsft** [Azure/azure-sdk-for-java#13980]
There are random failures in `resourcemanager` which force CI to be re-ran until the test passes.

Here are a few examples:

https://dev.azure.com/azure-sdk/public/_build/results?buildId=490049&view=ms.vss-test-web.build-test-results-tab&runId=12521532&resultId=100685&paneView=debug

https://dev.azure.com/azure-sdk/public/_build/results?buildId=488102&view=ms.vss-test-web.build-test-results-tab&runId=12486452&resultId=101502&paneView=debug

**Comment by yungezz** [comment]
thanks for reporting this. We also noticed this. @ChenTanyi is helping on it.

**Comment by ChenTanyi** [comment]
@alzimmermsft The random failed test has been skip in https://github.com/Azure/azure-sdk-for-java/pull/13964. If there is any other failed test, please comment below, and I'll skip them for not blocking CI.
