### ISSUE TITLE
Provision of Disk snapshot in this API ? 

### ISSUE THREAD

**Issue by nwarriorch** [Azure/azure-sdk-for-java#1401]
I was wondering if there is a way I can get a disk snapshot in this API, similar to EBS snapshot on AWS. If so is there a way to take a diff snapshot as well.

**Comment by anuchandy** [comment]
@nwarriorch see this [test](https://github.com/Azure/azure-sdk-for-java/blob/master/azure-mgmt-compute/src/test/java/com/microsoft/azure/management/compute/ManagedDiskOperationsTests.java#L139)

Below code shows how to take snapshot of a disk.

```
        Disk disk = computeManager.disks()
                getByGroup(rgName, diskName);

        Snapshot snapshot = computeManager.snapshots()
                .define(snapshotName)
                .withRegion(region)
                .withExistingResourceGroup(resourceGroup)
                .withDataFromDisk(disk)
                .create();
```

**Comment by nwarriorch** [comment]
Awesome , thanks
