### ISSUE TITLE
[BUG] azure-security-keyvault-keys NOT export com.azure.security.keyvault.keys

### ISSUE THREAD

**Issue by xccc-msft** [Azure/azure-sdk-for-java#14010]
**Describe the bug**
`exports com.azure.security.keyvault.keys;` is missing in [module-info](https://github.com/Azure/azure-sdk-for-java/blob/master/sdk/keyvault/azure-security-keyvault-keys/src/main/java/module-info.java#L9-L11).

**Setup (please complete the following information):**
 - OS: Windows
 - IDE : IntelliJ
 - Version of the Library used: JDK 11

**Additional context**

**Information Checklist**
Kindly make sure that you have added all the following information above and checkoff the required fields otherwise we will treat the issuer as an incomplete report
- [ ] Bug Description Added
- [ ] Repro Steps Added
- [ ] Setup information Added

**Comment by alzimmermsft** [comment]
@vcolin7 this also looks to be an issue with Certificates as well.

**Comment by vcolin7** [comment]
Working on this atm.

**Comment by vcolin7** [comment]
This has been fixed for release [`4.2.0` of Key Vault Keys](https://github.com/Azure/azure-sdk-for-java/releases/tag/azure-security-keyvault-keys_4.2.0) and [`4.1.0` of Key Vault Certificates](https://github.com/Azure/azure-sdk-for-java/releases/tag/azure-security-keyvault-certificates_4.1.0).
