### ISSUE TITLE
[BUG] Cosmos Java SDK4 not returning correct RUs consumed for GroupBy Query

### ISSUE THREAD

**Issue by jai-deep** [Azure/azure-sdk-for-java#14021]
**Describe the bug**

I am running the following query using Java SDK4 and also using Cosmos Data Explorer :

```
SELECT c.groupByColumn, COUNT(1) totalCount FROM c WHERE c.partitionKey IN ('2320')
group by c.groupByColumn
```
Here partitionKey is my partition key.

When I use the following code to get RUs for the query using SDK :

```
CosmosQueryRequestOptions queryOptions = new CosmosQueryRequestOptions();
queryOptions.setQueryMetricsEnabled(true);

getCosmosAsyncContainer().queryItems(sql,queryOptions, JsonNode.class)
					     .byPage()
					     .collectList()
				        	.subscribe(
								sqlResult -> {
								double cost = sqlResult.stream().mapToDouble(fr->fr.getRequestCharge()).sum();
                                                                getLogger().info("Cost {} , query : {}",cost,sql);
},
// error handling code here 
)
```

The result I get from SDK is **0.0 RU** , which doesn't seems realistic at all.

But when I run the same query using Data Explorer of Cosmos:
The result I get is **790 RUs**

Note : using the same code snippet , I am running other queries as well. This issue is there only with GroupBy queries. 

***Exception or Stack Trace***
Add the exception log and stack trace if available

**To Reproduce**

1. Have around 10K records in a partition.
2. Run a groupBy query on partition on any field . In my case there were 10 unique values of the field, all equally distributed. So 1K records per unique value.
3. Measure the RUs from Data explorer and from Java SDK.

***Code Snippet***
Added above in bug description.

**Expected behavior**
RU consumed , returned from SDK, should be same and realistic.
 
**Screenshots**

**Setup (please complete the following information):**
 - OS: Windows
 - IDE : IntelliJ
 - Version of the Library used : azure-cosmos:4.2.0

**Additional context**

**Information Checklist**
Kindly make sure that you have added all the following information above and checkoff the required fields otherwise we will treat the issuer as an incomplete report
- [*] Bug Description Added
- [*] Repro Steps Added
- [*] Setup information Added

**Comment by joshfree** [comment]
Thanks for filing this issue, @jai-deep.  Someone from the `Cosmos` team will follow up with you shortly.

**Comment by kushagraThapar** [comment]
@jai-deep - We recently fixed issues with request charge calculation on new versions of the SDK. Can you please upgrade to 4.8.0 and retry and let us know if the issue still exists. 
Please re-open this github issue if the problem still exists.
