### ISSUE TITLE
[BUG] Performance of Cosmos Cross Partition Query using Async API 

### ISSUE THREAD

**Issue by jai-deep** [Azure/azure-sdk-for-java#14022]
**Describe the bug**
According to [performance-tips-java-sdk-v4-sql](https://docs.microsoft.com/en-us/azure/cosmos-db/performance-tips-java-sdk-v4-sql) 

> Azure Cosmos DB Java SDK v4 supports parallel queries, which enable you to query a partitioned collection in parallel

My Set up :->
Cosmos collection has 24 partitions. Each Partition has 10K records each. 
Physical partitions are 2 according to cosmos metrics dashboard.

I tried two cases :

**Case 1** :  Giving the following partition query to sdk, and relaying upon SDK to run the query in parallel in Background and do an aggregate and return the result.

Query is :
```
Select value count(1) from c
Where c.partitionKey in ('PK1','PK2','PK3','PK4')
and c.someField > 100
```
Here I am querying on four different partitions.

The result of load test I got, average time **475 ms** :

> 1000 Requests in 00:07:56 =    2.1/s Avg:   475 Min:   375 Max:  1038 Err:     0 (0.00%)

**Case 2** :  In this case I myself kept a Threadpool of 4 Threads in the application, And each thread was running query for one partition.
For example :
Thread 1 was running :
```
Select value count(1) from c
Where c.partitionKey in ('PK1')
and c.someField > 100
```
Thread 2 was running :
```
Select value count(1) from c
Where c.partitionKey in ('PK2')
and c.someField > 100
```
and so on.

The result of load test I got, average time **164 ms** :

> 1000 Requests in 00:02:46 =    6.0/s Avg:   164 Min:   121 Max:   836 Err:     0 (0.00%)

If we go with what doc states, there shouldn't be any difference between the performance of two cases.
As in the end, both the cases will be running queries in parallel across the partitions.

But from the load test results this does not looks like the case.

***Exception or Stack Trace***
Add the exception log and stack trace if available

**To Reproduce**

***Code Snippet***

Code Snippet of first case :

```
CountDownLatch countDownLatch = new CountDownLatch(1);
CosmosQueryRequestOptions queryOptions = new CosmosQueryRequestOptions();
queryOptions.setMaxDegreeOfParallelism(Integer.MAX_VALUE);
queryOptions.setMaxBufferedItemCount(100);  // results cant be more than 1, as it is a count

			int indexOfSqlFinal = indexOfSql;
			getCosmosAsyncContainer().queryItems(sql,queryOptions, JsonNode.class)
									.byPage()
									.collectList()
									.timeout(Duration.ofMillis(defaultTimeOutMillis))
									.subscribe(
											// result processing code
                                                                                      countDownLatch.countDown();
                                                                                       ,
                                                                                        // error handling code
                                                                                         countDownLatch.countDown(); );
		

		// waiting for results to compete
		boolean isCountedDown = countDownLatch.await(defaultTimeOutMillis, TimeUnit.MILLISECONDS);

```

For testcase 2:

Running the code snippet . But in 4 different Threads and each Thread have single partitions in the query specified.

Only difference is in CosmosQueryRequestOptions :

```
CosmosQueryRequestOptions queryOptions = new CosmosQueryRequestOptions();
queryOptions.setPartitionKey(new PartitionKey(partitionKey));

        List<JsonNode> resList = new ArrayList<>();
        CosmosPagedIterable<JsonNode> res = cosmosContainer.queryItems(sql, queryOptions, JsonNode.class);

        res.iterableByPage().forEach(tr -> {
            resList.addAll(tr.getResults());

        });
```
Everything else is same.

**Expected behavior**

**Screenshots**

**Setup (please complete the following information):**
 - OS: [Windows]
 - IDE : [IntelliJ]
 - Version of the Library used

**Additional context**

**Information Checklist**
Kindly make sure that you have added all the following information above and checkoff the required fields otherwise we will treat the issuer as an incomplete report
- [ ] Bug Description Added
- [ ] Repro Steps Added
- [ ] Setup information Added

**Comment by joshfree** [comment]
Thanks for filing this issue, @jai-deep.  Someone from the `Cosmos` team will follow up shortly.

**Comment by kushagraThapar** [comment]
@moderakh  did some investments on IN query clause performance optimizations. 
Mo, can you please check if the above code snippet represents the best possible performance throughput that we can get when running IN clause queries ?

**Comment by kushagraThapar** [comment]
Closing this issue because of in-activity. @jai-deep  please feel free to re-open this issue if this is still a problem.
