### ISSUE TITLE
azure-storage-file-datalake - Buffered cache / slabinfo not getting cleared after using the API. Container crashes after running for 0.15 million requests

### ISSUE THREAD

**Issue by zaabskr** [Azure/azure-sdk-for-java#14049]
**Describe the bug**
We are using running our java application in AKS. The application is containerized with base image mcr.microsoft.com/java/jre-headless:11-zulu-alpine. We upload close to 1 million files (total 100-200 GB) from instances of our applications.
We are observing that the if we use the sdk to connect to ADLS2 and upload these files, the linux cache is not getting cleared and hence the memory working set reported by AKS is consistently increasing, causing a final restart of the application.
Our application runs fine without this if we dont upload the files to ADLS2.

***Exception or Stack Trace***
N/A

**To Reproduce**

***Code Snippet***
Add the code snippet that causes the issue.

    @PostConstruct
    public void init()
    {
        ClientSecretCredential clientSecretCredential = new ClientSecretCredentialBuilder()
                .clientId(getClientId())
                .clientSecret(getClientSecret())
                .tenantId(getTenantId())
                .build();
        dataLakeServiceClient =  new DataLakeServiceClientBuilder().credential(clientSecretCredential)
                .endpoint(getAdls2StorageEndpoint())
                .buildClient();
    }

    public String uploadFileToBlobStorage(byte[] uploadedFileBytes) {
        Instant currentInstant = Instant.now();
        int year = currentInstant.atZone(ZoneOffset.UTC).getYear();
        int month = currentInstant.atZone(ZoneOffset.UTC).getMonthValue();
        int day = currentInstant.atZone(ZoneOffset.UTC).getDayOfMonth();
        int hour = currentInstant.atOffset(ZoneOffset.UTC).getHour();

        StringBuilder adls2FilePath = new StringBuilder(); // with path
        DataLakeFileSystemClient dataLakeFileSystemClient;
        DataLakeFileClient dataLakeFileClient;
        try (ByteArrayInputStream inputStream = new ByteArrayInputStream(uploadedFileBytes)){
            dataLakeFileSystemClient = dataLakeServiceClient.getFileSystemClient(storageContainerName);
            adls2FilePath.append(FORWARD_SLASH).append(year).append(FORWARD_SLASH).append(month).append(FORWARD_SLASH)
                    .append(day).append(FORWARD_SLASH).append(hour).append(FORWARD_SLASH));
            DataLakeDirectoryClient dataLakeDirectoryClient = dataLakeFileSystemClient.getDirectoryClient(adls2FilePath.toString());
            dataLakeFileClient = dataLakeDirectoryClient.createFile(uniquefileName);
            dataLakeFileClient.append(inputStream,0,uploadedFileBytes.length);
            dataLakeFileClient.flush(uploadedFileBytes.length);
        }
        catch (IOException ioe) {
        }
        catch (DataLakeStorageException e) {
            }
            throw e;
        }
        return dataLakeFileSystemClient.getFileSystemUrl() + FORWARD_SLASH + dataLakeFileClient.getFilePath();
    }

**Expected behavior**
We expect the cache/ streams to be cleared off once the data is flushed.

**Screenshots**

**Setup (please complete the following information):**
 - OS: mcr.microsoft.com/java/jre-headless:11-zulu-alpine base image
 - Azure Kubernetes Service
 - azure-storage-file-datalake 12.1.1

**Additional context**

**Information Checklist**
Kindly make sure that you have added all the following information above and checkoff the required fields otherwise we will treat the issuer as an incomplete report
- [x] Bug Description Added
- [x] Repro Steps Added
- [x] Setup information Added

**Comment by gapra-msft** [comment]
Hi @zaabskr Thank you for reporting this issue. 

We will start trying to repro your issue, and I will reach out in case I need any more info from you.

**Comment by gapra-msft** [comment]
Meanwhile, I noticed you are appending and flushing manually, do you see the same issue when you use our uploadFromFile API?

Could we also get some info on the specs of your VM?

**Comment by zaabskr** [comment]
We are not using the uploadFromFile API.
We are using mcr.microsoft.com/java/jre-headless:8-zulu-alpine
Is this related to https://github.com/Azure/azure-sdk-for-java/issues/10957

**Comment by gapra-msft** [comment]
I don't think this is related to that issue since you are calling append and flush separately, and that issue is related to our buffered upload methods.

**Comment by zaabskr** [comment]
Yea. After viewing the solution mentioned in that issue, I also don't think that is the root cause/ solution for the issue we are facing. 
**How did we reproduced the issue?**
The filesizes that we write to the storage is small ( 200KB - 5 MB). But the frequency is high. We reproduced this issue by running our application running for 2-3 hours at around 20-50 RPS with memory limits of 3GB. The heap memory was stable but the linux cache memory was constantly increasing. So working set memory constantly increased, and the container restarted after it hit the limits.

When we used the old blob client library the application was stable 
 			<groupId>com.microsoft.azure</groupId>
			<artifactId>azure-storage</artifactId>
			<version>8.6.0</version>
But as I understand, this API is now deprecated.
**workaround**
We are planning to check with azure-storage-blob api. The other users encountering OOM mentioned a workaround using the same.
I would like to also confirm if the azure-storage-file-datalake internally uses azure-storage-blob api.
		<dependency>
			<groupId>com.azure</groupId>
			<artifactId>azure-storage-blob</artifactId>
			<version>12.8.0</version>
		</dependency>

**Comment by zaabskr** [comment]
You can see the container cache logs attached under issue https://github.com/Azure/AKS/issues/1766

**Comment by gapra-msft** [comment]
Hi @zaabskr, Thank you for your patience while we we tried to repro your issue. I created a very basic test app with the exact code you provided and called the uploadFileToBlobStorage in a loop over 43k times. 

However, I was unable to reproduce the issue you are seeing. I noticed initially, the buffered cache size did increase a bit, but over a steady amount of time, I noticed the cache size came back down to the original value. 

I'm not aware of any code in our library that allocates or controls direct memory from the client. We mostly allocate from the heap and that is GCed immediately since we don't hold any references to it. And because we are working in Java, any issues with resource usage would typically show up as an issue in the JVM rather than on the system level.

It's possible that there could be other system environment errors that cause this state to occur. Besides what you mentioned about the difference between performing and skipping the uploads, do you have other reasons to believe that the issue you're seeing on your system is caused by the sdk?

**Comment by zaabskr** [comment]
Hi @gapra-msft We seems to have isolated the problem further to the netty.jar version. We have deployed an upgraded version. I will get back to you in 2-3 days after observing the same.

**Comment by zaabskr** [comment]
Hi @gapra-msft We have resolved the issue after the netty version was moved to 4.1.51 jars. 
The issue was reproduced with the set of jars in the attachment.
I will close the request since the issue has been resolved. Thanks!.

**Comment by gapra-msft** [comment]
Great to hear! If you hit any more issues, feel free to re-open this issue/open another issue, and we'd be happy to help.
