### ISSUE TITLE
[BUG] @Beta NOT exported by azure-core

### ISSUE THREAD

**Issue by xccc-msft** [Azure/azure-sdk-for-java#14053]
**Describe the bug**
[Beta.java](https://github.com/Azure/azure-sdk-for-java/blob/master/sdk/core/azure-core/src/main/java/com/azure/core/implementation/annotation/Beta.java) should be moved into `com.azure.core.annotation`

or

add export statement for `com.azure.core.implementation.annotation` in [module-info.java](https://github.com/Azure/azure-sdk-for-java/blob/master/sdk/core/azure-core/src/main/java/module-info.java).

**Setup (please complete the following information):**
 - OS: Windows
 - IDE : IntelliJ
 - Version of the Library used: JDK 11

**Additional context**

**Information Checklist**
Kindly make sure that you have added all the following information above and checkoff the required fields otherwise we will treat the issuer as an incomplete report
- [ ] Bug Description Added
- [ ] Repro Steps Added
- [ ] Setup information Added

**Comment by JonathanGiles** [comment]
We don't currently use the beta annotation and should firstly discuss whether it provides sufficient value.
