### ISSUE TITLE
[QUERY] how to swap storage-blob sdk download usage with azure cdn usage?

### ISSUE THREAD

**Issue by tysonnorris** [Azure/azure-sdk-for-java#14078]
**Query/Question**
Currently we use the storage-blob sdk (12.6.0) to download files in blob store using e.g.
```builder
          .endpoint(config.endpoint)
          .credential(new StorageSharedKeyCredential(config.accountName, config.accountKey))
```
then
```
blobClient.download()
```

Is there an equivalent sdk client for azure cdn fronted blobstore? or do we need to just implement a) a standard http client and b) required authentication.

For b): is there any *shared key* authentication options for securing azure cdn content? I only see docs for SAS or Token auth (with "Premium from Verizon").

Alternatively - is there a better way to optimize download latency from azure blob store to regionally disparate applications? (we are not attempting to improve redundancy, just the download latency)

***Why is this not a Bug or a feature Request?***
We are porting usage of aws cloudfront java sdk which has similar features, hoping there is a convenient client that supports authentication options for azure cdn.

**Setup (please complete the following information if applicable):**
 - IDE : [e.g. IntelliJ]
 - Version of the Library used: azure-storage-blob-12.6.0
 
 **Information Checklist**
 Kindly make sure that you have added all the following information above and checkoff the required fields otherwise we will treat the issuer as an incomplete report
- [x] Query Added
- [x] Setup information Added

**Comment by joshfree** [comment]
Thanks for posting the question @tysonnorris.  Someone from the `storage` team will follow up shortly

**Comment by amishra-dev** [comment]
The same SDK should work, please follow the steps here (https://docs.microsoft.com/en-us/azure/cdn/cdn-create-a-storage-account-with-cdn#:~:text=%20Enable%20Azure%20CDN%20for%20the%20storage%20account,it%20appears%20in%20the%20endpoint%20list.%20More%20)

Let us know if you run into any issues.
