### ISSUE TITLE
Attaching new data disk to VM always creates data disk in a new storage account. 

### ISSUE THREAD

**Issue by nwarriorch** [Azure/azure-sdk-for-java#1408]
Adding a new disk to the VM using the new API creates a disk in a brand new storage account, instead of using the VM's OS disk storage account. Unless storeAt() is used to define storage location. 
Asking because CLI attach disk command defines the new data disk in the VM storage account.

**Comment by anuchandy** [comment]
This is by design- on update, SDK creates new storage account for data disk unless `withExistingStorageAccount(..)` or `storeAt` is specified.
