### ISSUE TITLE
Async Java client for Azure Table Storage

### ISSUE THREAD

**Issue by dhruvasood** [Azure/azure-sdk-for-java#14084]
Is there an async Netty based Java client for azure table storage? Just browsing through the repo, it seems like azure-sdk-for-java/sdk/tables might be what I'm looking for but it hasn't been published yet it looks like. Can someone confirm or point me in the right direction. Thanks!

**Comment by bsiegel** [comment]
Hey there, thanks for the question. We're working on a new library that will provide both sync and async client options (with either Netty or OkHttp as the backend) and will interoperate with both the traditional Azure Table Storage service, and the Azure Table Storage APIs exposed by CosmosDB. Stay tuned for an announcement soon. You can track our work towards our first preview release in issue #13730. Going to mark this issue as resolved, feel free to re-open if you need further assistance on this topic.

Related-to: #7361
