### ISSUE TITLE
JMS for Service Bus standard AMQP session timeout

### ISSUE THREAD

**Issue by saragluna** [Azure/azure-sdk-for-java#14100]
Copied from https://github.com/microsoft/azure-spring-boot/issues/930.

hi Team,
We have a issue with JMS AMQP session timeout. And it make the system cannot get the message for a while.

the error message is :
```
Aug 01, 2020 11:25:50 AM org.springframework.jms.connection.SingleConnectionFactory onException
WARNING: Encountered a JMSException - resetting the underlying JMS Connection org.apache.qpid.amqp_1_0.jms.MessageConsumerException: Force detach the link because the session is remotely ended.
at org.apache.qpid.amqp_1_0.jms.impl.MessageConsumerImpl$1.run(MessageConsumerImpl.java:143)
at java.lang.Thread.run(Thread.java:745)

Aug 01, 2020 11:25:50 AM org.springframework.jms.listener.DefaultMessageListenerContainer handleListenerSetupFailure
WARNING: Setup of JMS message listener invoker failed for destination 'org.apache.qpid.amqp_1_0.jms.impl.QueueImpl@6c292189' - trying to recover. Cause: Force detach the link because the session is remotely ended
```
We checked the document from https://docs.microsoft.com/en-us/azure/developer/java/spring-framework/configure-spring-boot-starter-java-app-with-azure-service-bus
it only have
spring.jms.servicebus.idle-timeout | Specify the idle timeout in milliseconds. The recommended value for this tutorial is 1800000.

In addition, for this document https://docs.microsoft.com/en-us/azure/service-bus-messaging/service-bus-java-how-to-use-jms-api-amqp also don't have the session error information.

I checked online, there have one person said:
> The JMS Session instance can not be used concurrently by multiple threads, so the best advise is to create the JMS Session on each thread you are using and close the jms session when you have finished that unit of work (sending a message or a collection of messages in a transaction)

Is that correct? for this issue how we can do anything to prevent it.
Thank you

**Comment by Scarlettliuyc** [comment]
hi, any updates from this issue, do you have any documents, we can follow it, thank you

**Comment by chenrujun** [comment]
Hi, @Scarlettliuyc 

I can not reproduce this problem in my localhost.
Could you please reproduce the problem by our sample project?
Here is our sample project: https://github.com/Azure/azure-sdk-for-java/tree/master/sdk/spring/azure-spring-boot-samples

If you can reproduce it,
please folk the repo and share you github branch,
then we will investigate it by your branch.

**Comment by axisc** [comment]
@saragluna this may be related to service side disconnects and not to the timeouts in the connection string. Typically the client should automatically reconnect. 
We may be able to debug with your code repro.

**Comment by Scarlettliuyc** [comment]
hi team
thank you so much for your help, the issue has fixed. 
After change the session timeout time, the issue not happen any more.

we are grateful for all of yours help, you can close this issue first.

Best regards,
Scarlett

**Comment by chenrujun** [comment]
Hi, @Scarlettliuyc 
Thank you very much for your feedback.

Could you please tell us how to `change the session timeout time` ?
