### ISSUE TITLE
[FEATURE REQ] Support AppendBlobResource and PageableBlobResource in azure-spring-cloud-storage

### ISSUE THREAD

**Issue by zhoufenqin** [Azure/azure-sdk-for-java#14125]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**
Now the azure-spring-cloud-storage only support block blob, we should support pageable blob and append blob too

**Information Checklist**
Kindly make sure that you have added all the following information above and checkoff the required fields otherwise we will treat the issuer as an incomplete report
- [ ] Description Added
- [ ] Expected solution specified

**Comment by backwind1233** [comment]
Closing this, it's duplicated with https://github.com/Azure/azure-sdk-for-java/issues/14125
