### ISSUE TITLE
Change names of booleans to use "is"

### ISSUE THREAD

**Issue by conniey** [Azure/azure-sdk-for-java#14139]
Update names of booleans to use a question like name, "isRequiresSession" to make them more Java-esque?

API View https://apiview.dev/Assemblies/Review/64f40be9988242c9a8facc8a20c5e9e7

**Comment by YijunXieMS** [comment]
"isRequiresSession( )" isn't correct English. I suggest "isSessionRequired( )".
I kind of saw pattern like "doesRequireSession()" but not very often.
