### ISSUE TITLE
Reduce Time Taken to Run Analyze in CI

### ISSUE THREAD

**Issue by alzimmermsft** [Azure/azure-sdk-for-java#14132]
Investigate ways to reduce time taken to run analyze in CI, possible remedies would be:

- [x] Switch the OS to Linux from Windows as Linux has shown to have consistently better performance.
- [x] Parallelize the `Build and Install` step using `-T 1C`.
- [ ] Use targeted commands for `Run SpotBugs, Checkstyle, RevApi, and Javadoc` by using `javadoc:jar checkstyle:check spotbugs:check revapi:check`

**Comment by kurtzeborn** [comment]
Switching the label to "Client" since we use the "EngSys" and "Client" labels to indicate who's doing the work (not area the work is in).
