### ISSUE TITLE
Group by queries giving empty pages after first response

### ISSUE THREAD

**Issue by simplynaveen20** [Azure/azure-sdk-for-java#14142]
**Describe the bug**
Group by queries giving empty pages after first response

**Setup (please complete the following information):**
 - V4.3.1

**Additional context**
[This code](https://github.com/Azure/azure-sdk-for-java/blob/658b5d8c803687d8c74cae725b4d3ddafeb2ea24/sdk/cosmos/azure-cosmos/src/main/java/com/azure/cosmos/implementation/query/GroupByDocumentQueryExecutionContext.java#L93)  resulting in empty pages after successful response

**Comment by kushagraThapar** [comment]
@simplynaveen20 @mbhaskar  is this still a valid issue ?
Please close this if not.

**Comment by TheovanKraay** [comment]
@kushagraThapar looks like this was never investigated/closed?

**Comment by xinlian12** [comment]
This issue should have been fixed by https://github.com/Azure/azure-sdk-for-java/pull/14143
