### ISSUE TITLE
[BUG] Cosmos Range implementation overhead

### ISSUE THREAD

**Issue by kirankumarkolli** [Azure/azure-sdk-for-java#14168]
Azure Cosmos Range type implemented as JsonSerializable where each get/set requires JSON lookup/set, which are very expensive. 
This code path is in hot-path. Current profiles show around 1.2% CPU samples for it.

One option is to model it as regular type with Json serialization/-de-serialization compatible with wire format. 

![image](https://user-images.githubusercontent.com/6880899/90356418-2250d000-e06d-11ea-8a35-83a44d65f031.png)

**Comment by kushagraThapar** [comment]
@moderakh  - can you please update this issue with the various performance enhancements that you did on V4 GA library. 
If this issue no longer exists, please close it, thanks!

**Comment by moderakh** [comment]
all the perf improvements we did happened prior to GA version (2020-06-10). Kiran filed this after GA. so most likely these are still relevant. please check with Kiran with more context .
