### ISSUE TITLE
[BUG] Performance: Cosmos PathHelper.tryParsePathSegments taking CPU samples of ~2.66%

### ISSUE THREAD

**Issue by kirankumarkolli** [Azure/azure-sdk-for-java#14169]
![image](https://user-images.githubusercontent.com/6880899/90356663-e8cc9480-e06d-11ea-968f-fe42d80721d4.png)

**Comment by kushagraThapar** [comment]
@moderakh  - checking with you if this issue still is a problem.

**Comment by moderakh** [comment]
@kushagraThapar all the perf improvements we did happened prior to GA version (2020-06-10). Kiran filed this after GA. so most likely these are still relevant. you may want to check with Kiran on the context of the issue.
