### ISSUE TITLE
[QUERY] Azure storage async sdk supports http connection pooling ?

### ISSUE THREAD

**Issue by shettyh** [Azure/azure-sdk-for-java#14178]
**Query/Question**
Is there a way to enable HTTP connection pooling in azure storage reactor library ? Or is it already enabled ?

***Why is this not a Bug or a feature Request?***
This is just the question

**Comment by rickle-msft** [comment]
@anuchandy it's enabled by default, right?

**Comment by joshfree** [comment]
@alzimmermsft can you please follow up?

**Comment by alzimmermsft** [comment]
@shettyh, by default Reactor Netty will use connection pooling, https://projectreactor.io/docs/netty/release/reference/index.html#_connection_pool. In our SDKs you can leverage the APIs on [`NettyAsyncHttpClientBuilder`](https://github.com/Azure/azure-sdk-for-java/blob/master/sdk/core/azure-core-http-netty/src/main/java/com/azure/core/http/netty/NettyAsyncHttpClientBuilder.java) to further customize the backing Reactor Netty `HttpClient`.

**Comment by shettyh** [comment]
@alzimmermsft  Thanks for the quick response, wanted to know if all the clients will use same connection pool or not. For example
I will create `BlobServiceAsyncClient` and then i will make `BlobContainerAsyncClient` out of it, in this case both will use the same connection pool ?

**Comment by shettyh** [comment]
Also if you can point me to some samples that would be great

**Comment by alzimmermsft** [comment]
@shettyh, correct, using the APIs to get a container client from a service client, and same for getting a blob client from a container client, will share the same underlying HttpClient, therefore the same connection pool. In the codesnippet below all clients will share the same underlying HttpClient:

```java
BlobServiceAsyncClient serviceClient = ...

BlobContainerAsyncClient containerClient = serviceClient.getBlobContainerAsyncClient(containerName);

BlobAsyncClient blobClient = containerClient.getBlobAsyncClient(blobName);
```

Additionally, from doing some research into the underlying networking layer the default `HttpClient` instances will share a connection pool. So, using the builder pattern to create additional client should also use the same connection pool even though they will be using different `HttpClients`.

**Comment by shettyh** [comment]
Thanks @alzimmermsft .

One last clarification, So i assume doing this `BlobContainerAsyncClient containerClient = serviceClient.getBlobContainerAsyncClient(containerName);` every-time in a function call and having `BlobServiceAsyncClient` as a instance variable (or singleton) should not have any performance implications right ?

**Comment by alzimmermsft** [comment]
Aside from normal object instantiation, there won't be any performance implication for creating many, many `BlobContainerAsyncClients` from a `BlobServiceAsyncClient`. It'll share all heavy objects between the instances and have small overhead with instance specific objects such as the container name, new endpoint, etc.

**Comment by shettyh** [comment]
@alzimmermsft thanks a lot for all the clarifications
