### ISSUE TITLE
[SB-Track2-customerReported] Exception ERROR Schedulers: Scheduler worker in group main failed with an uncaught exception 

### ISSUE THREAD

**Issue by hemanttanwar** [Azure/azure-sdk-for-java#14199]
Customer reported bug is here : https://github.com/Azure/azure-sdk-for-java/issues/13328

Implementing async subscriber to receive messages, near copy from readme example, and running from custom thread from inside Microsoft Azure Workspace Spark Synapse, raises uncaught exception. The exception is raised at the time of setting up receiver. Further on, no messages can be received from the queue and a different exception is raised.

** Deliverable

- [ ] Look into the issue and report back to customer. And inform of initial investigation.
- [ ] Find out what needs to be done to fix the issue ?
- [ ] And  fix the issue .

**Comment by conniey** [comment]
Closed in favour of parent issue. #13328
