### ISSUE TITLE
[FEATURE REQ] [Diagnostics] Please include critical dependency information in diagnostics

### ISSUE THREAD

**Issue by kirankumarkolli** [Azure/azure-sdk-for-java#14202]
Please include critical dependency version information in the diagnostics (at-least when detected as un-expected).

**Comment by kushagraThapar** [comment]
Suggestions - We can do this at `CosmosClient` initialization. 

How to do it - This needs to be investigated.

**Comment by kushagraThapar** [comment]
Closing this as we have removed most of the dependencies from Java SDK, and are brought up by azure core SDKs, making them more compatible with each other.
