### ISSUE TITLE
[QUERY] Closing EventHubProducerAsyncClient connection after all threads have published events to EH

### ISSUE THREAD

**Issue by tejaswibm** [Azure/azure-sdk-for-java#14217]
**Query/Question**
We have created an async EH producer that can emit events to EH in reactive way using Flux and Mono as given in the sample - [https://github.com/Azure/azure-sdk-for-java/blob/master/sdk/eventhubs/azure-messaging-eventhubs/src/samples/java/com/azure/messaging/eventhubs/PublishEventsWithSizeLimitedBatches.java](url)

We are able to achieve the sending of events, but now we are not sure how and when to close the `EventHubProducerAsyncClient` since it's an ever running application which is emitting application logs to EH in json format. 

The application itself is built using play framework and GlobalSettings provide us an onStop() hook to close all the resources. 
We have followed a pub/sub model with `LinkedBlockingQueue` for pushing events and then publishing these events to EH via a consumer. But we cannot eager close the client since the messages might still be present in the queue.

The `subscribeOn()` is using `Schedulers.boundedElastic()` which uses multiple threads to publish events to EH.

How do we ensure that all the threads have finished publishing events which it already holds and then flush the remaining queue events and then shutdown the client. We are not able to find any way of ensuring this before closing the client.

***Why is this not a Bug or a feature Request?***
This is not a bug rather a query as to how this can be achieved.

**Setup (please complete the following information if applicable):**
 - OS: Ubuntu
 - IDE : Intellij
 - Version of the Library used: "com.azure" % "azure-messaging-eventhubs" % "5.1.2"

**Comment by joshfree** [comment]
Thanks for filing this question, @tejaswibm.  @YijunXieMS could you please follow up?

**Comment by YijunXieMS** [comment]
@tejaswibm @joshfree I'll look into it.

**Comment by YijunXieMS** [comment]
@tejaswibm I'm not yet familiar with play framework and GlobalSettings. So one simple question before I look into more details. How do you trigger the "onStop() hook"? Do you press Ctrl+C in the command line?

**Comment by tejaswibm-roposo** [comment]
@YijunXieMS - The simplest way to do this is to issue `kill <pid>` command on the pod where my web application is running.

**Comment by YijunXieMS** [comment]
@tejaswibm-roposo @tejaswibm 

You use a consumer to receive from a LinkedBlockingQueue and send the data to EH. So I guess you create a Flux to poll/take from the LinkedBlockingQueue and send to the EH.
I understand your requirement is to keep consuming data and sending to EH until the LinkedBlockingQueue is empty after the onStop hook is triggered.
You might be able to:
1. block the Flux to allow it to run endlessly.
2. Inside the onStop hook, you wait until the queue is empty. The created Flux will keep emitting data until the onStop hook tells it to stop.

In the following code snippet (not production ready code) I use Java's shutdown hook to simulate the onStop hook. I tested it in Windows. If I hit Ctrl-C early, the program will continue to consume the data in the LinkedBlockingQueue until it's empty. Would this possibly solve your problem?

```java
import reactor.core.publisher.Flux;
import reactor.core.scheduler.Scheduler;
import reactor.core.scheduler.Schedulers;

import java.util.concurrent.LinkedBlockingQueue;
import java.util.concurrent.TimeUnit;

public class GracefullyShutdownBlock {
    private final LinkedBlockingQueue<String> queue = new LinkedBlockingQueue<>();
    private boolean isRunning = false;

    public static void main(String[] args) {
        GracefullyShutdownBlock app = new GracefullyShutdownBlock();
        app.setRunning(true);
        Runtime.getRuntime().addShutdownHook(new Thread(() -> {
            try {
                while(!app.getQueue().isEmpty()) {
                    TimeUnit.SECONDS.sleep(1);
                }
            } catch (InterruptedException e) {
                e.printStackTrace();
            }
            app.setRunning(false);
            System.out.println("Everything has finished. Do clean up here.");
        }));
        // Scheduler scheduler = Schedulers.newParallel("new thread");
        Scheduler scheduler = Schedulers.boundedElastic();
        app.createReceiverFlux().subscribeOn(scheduler).doOnEach(x -> {
            System.out.println(x + " is processed");
            try {
                TimeUnit.SECONDS.sleep(1);  // do something time consuming
            } catch (InterruptedException e) {
                e.printStackTrace();
            }
        }).blockLast();
    }

    private Flux<String> createReceiverFlux() {
        for (int i = 0; i <= 10; i++) {
            queue.offer("SomeString-" + i);
        }
        return Flux.create(sink -> {
            while (this.isRunning()) {
                String value = queue.poll();
                if(value != null) {
                    sink.next(value);
                    System.out.println(value + " is emitted");
                }
            }
            sink.complete();
        });
    }

    public LinkedBlockingQueue<String> getQueue() {
        return queue;
    }

    public boolean isRunning() {
        return isRunning;
    }

    public void setRunning(boolean running) {
        isRunning = running;
    }
}
```

**Comment by srnagar** [comment]
@tejaswibm Have you tried the above solution @YijunXieMS  has posted?

**Comment by tejaswibm** [comment]
@srnagar - I have achieved this in a different way by providing custom executor service to the scheduler and using executor shutdown hooks to flush the remaining events in the queue and then closing it.!

**Comment by srnagar** [comment]
@tejaswibm - Thanks for the update! Looks like you have a solution 👍 

Closing this issue.
