### ISSUE TITLE
There doesn't appear to be a way to get the minimum disk required for a given ImageReference

### ISSUE THREAD

**Issue by davidbairdala** [Azure/azure-sdk-for-java#1424]
If you try and provision a new virtual machine with a virtual hard disk size less than what is required by a VHD image, an error is reported in the console saying that disks cannot be resized downwards, but there does not appear to be away to know what the minimum disk size should be.

**Comment by anuchandy** [comment]
Unfortunately, compute service does not provide us size via  `VirtualMachineImage.osDiskImage` property.  
Also after creating the virtual machine from such image, service won't include this information in the VM payload as well. Only option i am aware of is to check the size of OS vhd using storage data API.

**Comment by martinsawicki** [comment]
as per above, this is not actionable currently in the SDK beyond the suggested workaround.
