### ISSUE TITLE
Possible to use this SDK to send to Event Hubs?

### ISSUE THREAD

**Issue by redraven984** [Azure/azure-sdk-for-java#1427]
I would like to send to Azure Event Hubs from an Android Application. Is it possible to do this with the Azure SDK?

Something like this possibly: https://github.com/Azure/azure-sdk-for-java/wiki/Getting-Started

**Comment by vhvb1989** [comment]
Hello @redraven984 

I am sorry about you didn't get a sooner answer on this
Do you still need help on this? Let me know and I would be happy to help.

Note: As part of repository cleaning effort, this issue will be closed by Oct 4 if no response is received from submitter and/or not further action is required.

**Comment by redraven984** [comment]
I think at this point I dont need this anymore. I can close this for now.

Thanks for getting back to me.

**Comment by thhsam** [comment]
Hello @redraven984  
Did you have any success in using this Java SDK to produce events to eventhub?  I am facing the same question at the moment! 

Hello @vhvb1989  if you know it is possible? I have started working on this, but haven't had much success yet

Thanks 
Sam

**Comment by vhvb1989** [comment]
@thhsam happy to hear you are using the Azure SDK for Java.
Please take a look to this link: https://docs.microsoft.com/en-us/java/api/overview/azure/messaging-eventhubs-readme?view=azure-java-stable
