### ISSUE TITLE
[FEATURE REQ] Azure Cosmos DB SDK v4: Provide method / flag to replace throughput and wait until scaling has completed

### ISSUE THREAD

**Issue by dr-dolittle** [Azure/azure-sdk-for-java#14272]
Doing large scalings can take a while and sometimes it is necessary to be sure that all throughput is available (e.g. scale, bulk import, then scale back).

Currently only the method replaceThroughput is available. It would be great to have a method like replaceThroughputAndWaitUntilScalingCompleted or a flag for replaceThroughput to indicate to wait that returns a positive response (async / sync) as soon as the the scaling has completed and the whole throughput is available.

**Comment by joshfree** [comment]
Thanks for filing this feature request, @dr-dolittle.  Someone from the `cosmos` team will take a look and follow up shortly.

**Comment by xinlian12** [comment]
An alternative way:
In the readThroughput response, waiting for `throughputResponse.isReplacePending()` to return false

**Comment by kushagraThapar** [comment]
@dr-dolittle  - did you try the above workaround and did it work? Please re-open this issue if the problem still persists, thanks!
