### ISSUE TITLE
Add Performance Tests for Text Analytics SDK

### ISSUE THREAD

**Issue by g2vinay** [Azure/azure-sdk-for-java#14309]
We need to add performance tests for champion scenarios of TA SDK.

Instructions to setup performance tests can be found in this wiki:
https://github.com/Azure/azure-sdk-for-java/wiki/Writing-Performance-Tests

**Comment by mssfang** [comment]
closed in PR: https://github.com/Azure/azure-sdk-for-java/pull/20196
