### ISSUE TITLE
Add Performance Tests for Service Bus SDK

### ISSUE THREAD

**Issue by g2vinay** [Azure/azure-sdk-for-java#14314]
We need to add more performance tests for champion scenarios of SB SDK.

Instructions to setup performance tests can be found in this wiki:
https://github.com/Azure/azure-sdk-for-java/wiki/Writing-Performance-Tests

**Comment by conniey** [comment]
Closed in favour of https://github.com/Azure/azure-sdk-for-java/issues/9919
