### ISSUE TITLE
[FEATURE REQ] Support for setting application security groups on a network interface

### ISSUE THREAD

**Issue by jlouns** [Azure/azure-sdk-for-java#14322]
**Is your feature request related to a problem? Please describe.**
I can't assign an application security group to a network interface using the management SDK.

**Describe the solution you'd like**
I would like to be able to assign an application security group to a network interface using the SDK.

**Describe alternatives you've considered**
N/A

**Additional context**
The `properties.applicationSecurityGroups` parameter exists in the [REST API](https://docs.microsoft.com/en-us/rest/api/virtualnetwork/networkinterfaces/createorupdate#networkinterfaceipconfiguration) but not in the [Java API](https://github.com/Azure/azure-sdk-for-java/blob/master/sdk/resourcemanager/azure-resourcemanager-network/src/main/java/com/azure/resourcemanager/network/models/NetworkInterface.java)

**Information Checklist**
Kindly make sure that you have added all the following information above and checkoff the required fields otherwise we will treat the issuer as an incomplete report
- [x] Description Added
- [x] Expected solution specified

**Comment by xccc-msft** [comment]
@jlouns You may assign an application security group following below:
```java
       // create application security group
       ApplicationSecurityGroup applicationSecurityGroup = networkManager.applicationSecurityGroups().define("asg")
            .withRegion(Region.US_WEST)
            .withExistingResourceGroup("RG")
            .create();

        // prepare network interface inner
        NetworkInterfaceInner inner = new NetworkInterfaceInner();
        inner.withIpConfigurations(new ArrayList<>());
        inner.ipConfigurations().add(new NetworkInterfaceIpConfigurationInner().withApplicationSecurityGroups(new ArrayList<>()));

        // assign application security group to network interface via inner
        inner.ipConfigurations().get(0).applicationSecurityGroups().add(applicationSecurityGroup.inner());

        // send request by networkManager.networkInterfaces().inner().createOrUpdate()
        networkManager.networkInterfaces().inner().createOrUpdate("resourceGroupName", "networkInterfaceName", inner);
```

**Comment by jlouns** [comment]
Thanks, @xccc-msft. Looks like that will work.

Are there plans to add this functionality to the more traditional fluent interface used in the samples?

**Comment by xccc-msft** [comment]
@jlouns We may plan to have fluent interface in our new next-gen SDK for Java. Please find more details [here](https://aka.ms/azure-sdk-java-mgmt).

cc: @yungezz @nickzhums
