### ISSUE TITLE
SupportsListingInGroupByTag<GenericResource>#listByTag is stripping the resource tags

### ISSUE THREAD

**Issue by clguimanMSFT** [Azure/azure-sdk-for-java#1436]
I'm trying to fetch the resources with a specific tag from a resource group.
If I'm calling Azure.genericResource.listByTag then the resources in the list don't have any tags associated with them.
If I do the same thing but using listByGroup then the resources have the associated tags.
listByTag should just search for the specified tags, it should remove them.
I'm using 1.0.0-beta4.1

**Comment by praries880** [comment]
@clguimanMSFT are you still facing the issue or did you manage to move past it?

**Comment by clguimanMSFT** [comment]
I haven't used the SDK in a while, but you should investigate and see if the API behavior described is what users would expect
