### ISSUE TITLE
Broken link is causing appconfig and aggregate reports pipeline failures.

### ISSUE THREAD

**Issue by JimSuplizio** [Azure/azure-sdk-for-java#14377]
@saragluna 
[sdk/appconfiguration/azure-spring-cloud-feature-management/README.md](https://github.com/Azure/azure-sdk-for-java/blob/master/sdk/appconfiguration/azure-spring-cloud-feature-management/README.md#targeting-in-an-application) has a link to a demo, FeatureFlagDemo under the **Targeting in an Application** heading, which targets a sample that used to be in https://github.com/microsoft/spring-cloud-azure/tree/master/spring-cloud-azure-samples/feature-management-web-sample. Everything in the https://github.com/microsoft/spring-cloud-azure repository but was removed as part of https://github.com/microsoft/spring-cloud-azure/pull/754. 

Because of this the appconfig and aggregate reports pipelines have been failing the link checker.

**Comment by saragluna** [comment]
Thanks for pointing it out Jim. We broke the pipeline accidentally when deprecated our original repo and not aware of it. Here's my fix #14427.

**Comment by saragluna** [comment]
Ran the `java - aggregate-reports` and the link verification passed. Closing this issue now.
