### ISSUE TITLE
Spring Data Cosmos SDK support Java 11 

### ISSUE THREAD

**Issue by kushagraThapar** [Azure/azure-sdk-for-java#14378]
* Spring Data Cosmos support Java 11 
* Add module-info.java to spring-data-cosmos SDK. 
* Test with a sample spring data cosmos app to make sure Java 11 works fine. 
* We can use this sample: https://github.com/Azure-Samples/azure-spring-data-cosmos-java-sql-api-getting-started

**Comment by saragluna** [comment]
Completed by PR #14636.
