### ISSUE TITLE
Improving request retry options

### ISSUE THREAD

**Issue by gapra-msft** [Azure/azure-sdk-for-java#14388]
Currently the request retry policy in the pipeline is fixed to a single timeout, which isn't really productive when there are a variety of requests with different expected timeouts. 

A few ideas to make retries more granular

- Make an option like a dataTransfer timeout variable that gets multiplied by the amount of data being transferred to determine the timeout for that specific request. 
- Pass timeout information via context per request.

**Comment by alzimmermsft** [comment]
Closing as there is ways to pass timeouts to the `HttpClient` layer and the `HttpClient` layer has the more granular timeout mechanism mentioned here, which is always on by default.
