### ISSUE TITLE
Core Samples and Readme issues

### ISSUE THREAD

**Issue by Melanie-Ma** [Azure/azure-sdk-for-java#14406]
1.
Section [Link](https://github.com/Azure/azure-sdk-for-java/blob/master/sdk/core/azure-core/src/samples/java/com/azure/core/http/rest/PagedFluxJavaDocCodeSnippets.java#L93):
![image](https://user-images.githubusercontent.com/64007802/91130977-173a1780-e6df-11ea-9291-0bfedff1d584.png)
![image](https://user-images.githubusercontent.com/64007802/91130989-1e612580-e6df-11ea-89cb-1d6b19cc4412.png)
Suggestion:
The method `createCustomInstance()` returns null which caused null point exception.
What`s more, please check all the samples for the null point exception. Please notice the issue #12486.
2.
Section [Link](https://github.com/Azure/azure-sdk-for-java/tree/master/sdk/core/azure-core#http-pipelines-with-httppipeline):
![image](https://user-images.githubusercontent.com/64007802/91132846-e1e1f980-e6df-11ea-8253-aa12b0af4367.png)

Suggestion:
Change `an` to `a`.

@jongio for notification

**Comment by alzimmermsft** [comment]
The first issue will be fixed by updating the code samples to be similar to the fix for the issue you referenced. The second issue will remain as-is, while `HTTP` does begin with a consonant the pronunciation is `āch′tē-tē-pē′` which begins with a vowel.
