### ISSUE TITLE
[BUG] Authentication fails with "Invalid Client-Secret" whenever AppConfiguration is updated

### ISSUE THREAD

**Issue by alex-kuck** [Azure/azure-sdk-for-java#14429]
**Describe the bug**
Whenever the Azure AppConfiguration is updated via adding a new feature or updating the value of an existing one, every following request requiring authentication fails with an `Invalid Client Secret` error. This error disappears after restarting the server-side of the application.

**To Reproduce**
1. Generate an access token
1. Add a new feature in the AppConfiguration -> FeatureManager
1. Make an authenticated request containing the access token

**Expected behavior**
Updates to the AppConfiguration should have no impact on the authentication flow of the application.

**Setup (please complete the following information):**
We are using the Authentication flow via Adal4j in a Client-Server architecture developed with Spring Boot. We have recently added Azure AppConfiguration in order to manage feature flags. We are using the following versions:

```xml       
<dependency>
    <groupId>com.microsoft.azure</groupId>
    <artifactId>azure-spring-boot-starter</artifactId>
    <version>2.1.7</version>
</dependency>
<dependency>
    <groupId>com.microsoft.azure</groupId>
    <artifactId>azure-active-directory-spring-boot-starter</artifactId>
    <version>2.1.7</version>
</dependency>
<dependency>
    <groupId>com.microsoft.azure</groupId>
    <artifactId>spring-cloud-azure-appconfiguration-config-web</artifactId>
    <version>1.2.7</version>
</dependency>
<dependency>
    <groupId>com.microsoft.azure</groupId>
    <artifactId>spring-cloud-azure-feature-management-web</artifactId>
    <version>1.2.7</version>
</dependency>
```

**Information Checklist**
Kindly make sure that you have added all the following information above and checkoff the required fields otherwise we will treat the issuer as an incomplete report
- [x] Bug Description Added
- [x] Repro Steps Added
- [x] Setup information Added

**Comment by mrm9084** [comment]
@alex-kuck when the App Configuration client refreshes it updates all beans in the refreshable scope. It isn't clear from your description, but it sounds like the `Invalid Client Secret` error is coming from Adal4j. Can you verify if your usage of Adal4j is in Spring's refresh scope, and if so not properly being re-setup on a refresh.

**Comment by alex-kuck** [comment]
Thanks for the quick feedback, I will have a look into it and will let you know 👍

**Comment by alex-kuck** [comment]
Thank you again, that was definitely a pointer in the right direction 😄  We were using [Jasypt for Spring Boot](https://github.com/ulisesbocchio/jasypt-spring-boot) in order to encrypt the client secret and as it turned out, it was not re-decrypted after refreshing the scope. That did the trick for us. 🙏
