### ISSUE TITLE
Requests should throw the main cause exception rather than throw "RunTimeException"

### ISSUE THREAD

**Issue by Ahmad-Mahagna** [Azure/azure-sdk-for-java#1446]
My apologies if this issue already opened 

In case of authentication error ( e.g. invalid client secret ) Azure client throw RunTimeException 
rather than throws concrete Exception "AuthenticationException"  the main cause. 

would be useful if exceptions provide additional filed to hold error code, so end user can handle each issue separately.

**Comment by martinsawicki** [comment]
the inner exception should have what is needed here
