### ISSUE TITLE
Enable Configurable retry strategy Interceptor 

### ISSUE THREAD

**Issue by Ahmad-Mahagna** [Azure/azure-sdk-for-java#1447]
RestClient#build()  set hardCoded retry strategy interceptor 

>   public RestClient build() {
            AzureJacksonMapperAdapter mapperAdapter = new AzureJacksonMapperAdapter();
            UserAgentInterceptor userAgentInterceptor = new UserAgentInterceptor();
            if (userAgent != null) {
                userAgentInterceptor.withUserAgent(userAgent);
            }
            OkHttpClient httpClient = httpClientBuilder
                    .addInterceptor(userAgentInterceptor)
                    .addInterceptor(new RequestIdHeaderInterceptor())
                    .addInterceptor(new BaseUrlHandler())
                    .addInterceptor(customHeadersInterceptor)

##########################################################################
                    .addInterceptor(new RetryHandler(new ResourceGetExponentialBackoffRetryStrategy()))
                    .addInterceptor(new RetryHandler())
##########################################################################
                    .build();

            return new RestClient(httpClient,
                    retrofitBuilder
                            .baseUrl(baseUrl)
                            .client(httpClient)
                            .addConverterFactory(mapperAdapter.getConverterFactory())
                            .addCallAdapterFactory(RxJavaCallAdapterFactory.create())
                            .build(),
                    credentials,
                    customHeadersInterceptor,
                    mapperAdapter);
        }
    }<

**Comment by anuchandy** [comment]
@Ahmad-Mahagna sorry for the delay in responding. 

You can override the default retry strategy as follows:

```java
final File credFile = new File(System.getenv("AZURE_AUTH_LOCATION"));

 ApplicationTokenCredentials credentials = ApplicationTokenCredentials.fromFile(credFile);

 RestClient.Builder client = new RestClient.Builder()
        .withBaseUrl(AzureEnvironment.AZURE, AzureEnvironment.Endpoint.RESOURCE_MANAGER)
        .withSerializerAdapter(new AzureJacksonAdapter())
        .withResponseBuilderFactory(new AzureResponseBuilder.Factory())
        .withCredentials(credentials)
        .withRetryStrategy(<YOUR RETRY-STRATEGY-IMPLMENTATION>);

 Azure azure = Azure.authenticate(client.build(),  credentials.getClientId())
        .withDefaultSubscription();
```

You need to implement this interface https://github.com/Azure/autorest-clientruntime-for-java/blob/master/client-runtime/src/main/java/com/microsoft/rest/retry/RetryStrategy.java

Reference implementation https://github.com/Azure/autorest-clientruntime-for-java/blob/master/client-runtime/src/main/java/com/microsoft/rest/retry/ExponentialBackoffRetryStrategy.java

**Comment by martinsawicki** [comment]
closing, since guidance was provided above and no further questions came up.
