### ISSUE TITLE
custom images and managed disks are not available in azure us gov

### ISSUE THREAD

**Issue by paulojohnj** [Azure/azure-sdk-for-java#1448]
Is there a known date or api version / upgrade when these calls will become available within an Azure gov environment (They currently return 404 not found for /images and /disk endpoints). I am trying to keep interactions with Azure / Azure sdk the same across environments.

**Comment by anuchandy** [comment]
By now managed disk and custom image resources will be available across all azure env.

**Comment by martinsawicki** [comment]
closing, presumably this feature has been enabled across the gov cloud as well by now
