### ISSUE TITLE
[BUG] CryptographyAsyncClient calls Mono::block

### ISSUE THREAD

**Issue by glenn-ricaud** [Azure/azure-sdk-for-java#14482]
**Describe the bug**
In com.azure:azure-security-keyvault-keys, multiple methods of com.azure.security.keyvault.keys.cryptography.CryptographyAsyncClient have a first preliminary check "ensureValidKeyAvailable()"
This method unfortunately calls Mono::block to retrieve the key.

This is problematic when these methods (sign, verify, ...) are themselves called in a reactor thread as reactor will enforce that no "block()" is called

***Exception or Stack Trace***
```
java.lang.IllegalStateException: block()/blockFirst()/blockLast() are blocking, which is not supported in thread reactor-tcp-epoll-4
	at reactor.core.publisher.BlockingSingleSubscriber.blockingGet(BlockingSingleSubscriber.java:83)
	Suppressed: reactor.core.publisher.FluxOnAssembly$OnAssemblyException: 
Error has been observed at the following site(s):
	|_ checkpoint ⇢ Handler package.MyClass#methodUsedInReactorContext(String, ServerWebExchange) [DispatcherHandler]
	|_ checkpoint ⇢ org.springframework.boot.actuate.metrics.web.reactive.server.MetricsWebFilter [DefaultWebFilterChain]
	|_ checkpoint ⇢ HTTP POST \"/v1/accesstoken\" [ExceptionHandlingWebHandler]
Stack trace:
		at reactor.core.publisher.BlockingSingleSubscriber.blockingGet(BlockingSingleSubscriber.java:83)
		at reactor.core.publisher.Mono.block(Mono.java:1678)
		at com.azure.security.keyvault.keys.cryptography.CryptographyAsyncClient.ensureValidKeyAvailable(CryptographyAsyncClient.java:635)
		at com.azure.security.keyvault.keys.cryptography.CryptographyAsyncClient.sign(CryptographyAsyncClient.java:334)
		at com.azure.security.keyvault.keys.cryptography.CryptographyAsyncClient.lambda$sign$5(CryptographyAsyncClient.java:325)
```

***Work around***
I have been able to work around this problem by creating the async client and calling ONCE the sign method with a dummy value outside of a reactor thread.
Subsequent calls to CryptographyAsyncClient::sign work in a reactor thread as the key has already been retrieved

**Comment by alzimmermsft** [comment]
@vcolin7

**Comment by yangchengs** [comment]
@glenn-ricaud can you please provide your sample code of the work around?

**Comment by glenn-ricaud** [comment]
My problem is when using CryptographyAsyncClient.sign
This with returns Mono<SignResult> but that is doing a Mono.block the first time it is called.

My workaround was to call CryptographyAsyncClient.sign, after the client is created, with some dummy value outside of a reactor thread.

**Comment by glenn-ricaud** [comment]
I just saw your last comment @yangchengs 
I will check with version 4.2.1

**Comment by vcolin7** [comment]
Hi @glenn-ricaud, thanks for opening this issue and sorry about how long it took me to get back to you. I checked the issue @yangchengs mentioned and they are right that the latest version of Key Vault Keys does not block when calling `ensureValidKeyAvailable()`. This change [was introduced](https://github.com/Azure/azure-sdk-for-java/blob/d795fdaf0dd31e87afbeb225bfb2ca6982d16bc5/sdk/keyvault/azure-security-keyvault-keys/src/main/java/com/azure/security/keyvault/keys/cryptography/CryptographyAsyncClient.java#L631) in version `4.2.0`.

Let me know if you could successfully use the library by upgrading :)
