### ISSUE TITLE
[BUG] Delete Issue when UUID Type is passed as the Partition Key

### ISSUE THREAD

**Issue by precisemath** [Azure/azure-sdk-for-java#14485]
**Describe the bug**
My Partition Key is of Type UUID. When I try to delete a document using a UUID type, it throws an exception. But when I try to convert the partition value to a String (from UUID), it works perfectly.

***Exception or Stack Trace***
java.lang.IllegalArgumentException: Unable to construct PartitionKeyInternal from objects array
        at com.azure.cosmos.implementation.routing.PartitionKeyInternal.fromObjectArray(PartitionKeyInternal.java:137)
        at com.azure.cosmos.implementation.routing.PartitionKeyInternal.fromObjectArray(PartitionKeyInternal.java:100)
        at com.azure.cosmos.models.PartitionKey.<init>(PartitionKey.java:30)

**To Reproduce**
Delete any document with a UUID type as the Partition Key.

***Code Snippet***
private fun cleanup (id: String, partitionKeyValue: UUID)=
        try {
            val result = externalEventsConnection.container.deleteItem(id, PartitionKey(partitionKeyValue),CosmosItemRequestOptions())
            when (result.statusCode) {
                AZURE_COSMOS_STATUS_DELETE_OK -> Unit
                else -> throw Exception("Unexpected Exception on Cleanup of id=$id and rxId=$partitionKeyValue with statuscode=${result.statusCode}")
            }
        } catch (e:Exception) {
            throw e
        }

**Expected behavior**
No Exception is thrown!.

**Screenshots**

**Setup (please complete the following information):**
 - OS: Linux
 - IDE : IntelliJ
 - Version of the Library used - azure-cosmos 4.3.0

**Additional context**

**Information Checklist**
Kindly make sure that you have added all the following information above and checkoff the required fields otherwise we will treat the issuer as an incomplete report
- [x] Bug Description Added
- [x] Repro Steps Added
- [x] Setup information Added

**Comment by joshfree** [comment]
Adding the `cosmos` label so that someone from the Cosmos team will see this more easily and follow up

**Comment by kushagraThapar** [comment]
@precisemath - Java SDK V4 only supports `String` data type on partition key. Since JSON doesn't have a precision on numeric values, we don't allow using numeric values on partition key as that is dangerous. 

Please use `String` type.

**Comment by precisemath** [comment]
@kushagraThapar Is it unreasonable to expect that your answer will be updated in the partition key documentation?

**Comment by kushagraThapar** [comment]
@precisemath  - not unreasonable at all :) 
I will update it in the partition key documentation. @anfeldma-ms  - can we please take care of this from the java docs side ?
