### ISSUE TITLE
[QUERY] Is there an SDK that returns the Pricing Sheet / RateCard? Or any API in an existing SDK?

### ISSUE THREAD

**Issue by somanshreddy** [Azure/azure-sdk-for-java#14488]
**Query/Question**
Is there an SDK that returns the Pricing Sheet / Rate Card for Java? Or any API in an existing SDK? Preferably for Blob Storage 

I found a link for billing samples https://github.com/Azure-Samples/billing-java-ratecard-api but it doesn't exist anymore. So is the only available method now to make a REST call directly?

***Why is this not a Bug or a feature Request?***
Unsure of the existence of a feature hence it is neither a bug nor a feature request. 

**Setup (please complete the following information if applicable):**
- OS: Ubuntu 18.04
- IDE : IntelliJ 19.1.4
- SDK: azure-storage-blob v12.7.0
 
 **Information Checklist**
 Kindly make sure that you have added all the following information above and checkoff the required fields otherwise we will treat the issuer as an incomplete report
- [x] Query Added
- [x] Setup information Added

**Comment by yungezz** [comment]
hi @xccc-msft could you pls help to check if this is supported in Rest API then SDK? thanks

**Comment by xccc-msft** [comment]
@somanshreddy It looks the RateCard APIs is no longer supported [here](https://docs.microsoft.com/en-us/previous-versions/azure/reference/mt219005(v=azure.100)). You may want to check the [swagger](https://github.com/Azure/azure-rest-api-specs/blob/master/specification/commerce/resource-manager/Microsoft.Commerce/preview/2015-06-01-preview/commerce.json#L103-L150) and [sample](https://docs.microsoft.com/en-us/previous-versions/azure/reference/mt219004(v=azure.100)) of request and find out if it's retired or still available.

**Comment by somanshreddy** [comment]
Is the Pricing Sheet an updated version of the older Rate Card API? https://docs.microsoft.com/en-us/rest/api/consumption/pricesheet/get

**Comment by xccc-msft** [comment]
@somanshreddy I just add label of `Service Attention` so service team could help answer this.

**Comment by somanshreddy** [comment]
@xccc-msft Any updates? Could you follow up with the service team?

**Comment by xccc-msft** [comment]
@wilcobmsft Hi, I find your name on [CODEOWNERS of swagger](https://github.com/Azure/azure-rest-api-specs/blob/master/CODEOWNERS#L10) for Billing. Do you know who can help answer the question?

**Comment by anand-rengasamy** [comment]
@ramaganesan-rg - Can you loop in consumption team to help with this.

**Comment by somanshreddy** [comment]
@ramaganesan-rg Dropping another friendly reminder :)

**Comment by mumami** [comment]
@somanshreddy Did you try the Azure Retail Prices API? 
https://docs.microsoft.com/en-us/rest/api/cost-management/retail-prices/azure-retail-prices

**Comment by ramaganesan-rg** [comment]
hello Somansh, can you please take a look at the documentation Murali has shared and let us know if you have any further questions.

**Comment by somanshreddy** [comment]
Thanks @mumami @ramaganesan-rg 

This Retail Prices API looks like it returns the same pricing available on the Azure pricing website right? 

However, I noticed that this API https://docs.microsoft.com/en-us/rest/api/consumption/pricesheet/get takes the subscription id as well. So I presume this would have any discounts / customer specific costs?

**Comment by somanshreddy** [comment]
Thanks @mumami @ramaganesan-rg 

This Retail Prices API looks like it returns the same pricing available on the Azure pricing website right? 

However, I noticed that this API https://docs.microsoft.com/en-us/rest/api/consumption/pricesheet/get takes the subscription id as well. So I presume this would have any discounts / customer specific costs?

**Comment by somanshreddy** [comment]
Okay. So this looks to be the same. Thank you. 

So based on my understanding 
Public rates -> https://docs.microsoft.com/en-us/rest/api/cost-management/retail-prices/azure-retail-prices
Subscription specific -> https://management.azure.com/subscriptions/SubscriptionGuidHere/providers/Microsoft.Consumption/pricesheets/default?api-version=2020-01-01-preview

And there is no Java SDK for this. 

If the above is correct, then my query is answered and this issue can be closed. Thank you

**Comment by mumami** [comment]
@somanshreddy yes, that's correct. Please let me know if there are any further questions. Thanks.

**Comment by somanshreddy** [comment]
Cool, thank you

**Comment by ramaganesan-rg** [comment]
Thank you Somansh. Please reach out to us on any further questions.
