### ISSUE TITLE
[BUG] Cannot install extension on VM

### ISSUE THREAD

**Issue by esfomeado** [Azure/azure-sdk-for-java#14480]
**Describe the bug**
I'm trying to install a CustomScript extension using the sdk but It gives an error saying that the virtual machine does not support updates to the purchase plan.
If I use the azure cli or the website works fine.

The image that I'm using on the vm is bitnami wordpress.

***Exception or Stack Trace***

> 2020-08-26 11:55:18.437 ERROR 1116 --- [nio-8081-exec-1] o.a.c.c.C.[.[.[/].[dispatcherServlet]    : Servlet.service() for servlet [dispatcherServlet] in context with path [] threw exception [Request processing failed; nested exception is com.microsoft.azure.CloudException: The resource '/subscriptions/ae01d003-8509-415b-9c84-bf526ddd7d56/resourceGroups/storesResourceGroup/providers/Microsoft.Compute/virtualMachines/Loja07' of type 'Microsoft.Compute/virtualMachines' does not support updates to the purchase plan.: The resource '/subscriptions/ae01d003-8509-415b-9c84-bf526ddd7d56/resourceGroups/storesResourceGroup/providers/Microsoft.Compute/virtualMachines/Loja07' of type 'Microsoft.Compute/virtualMachines' does not support updates to the purchase plan.] with root cause
> 
> rx.exceptions.OnErrorThrowable$OnNextValue: OnError while emitting onNext value: retrofit2.Response.class
> 	at rx.exceptions.OnErrorThrowable.addValueAsLastCause(OnErrorThrowable.java:118) ~[rxjava-1.3.8.jar:1.3.8]
> 	at rx.internal.operators.OnSubscribeMap$MapSubscriber.onNext(OnSubscribeMap.java:73) ~[rxjava-1.3.8.jar:1.3.8]
> 	at retrofit2.adapter.rxjava.CallArbiter.deliverResponse(CallArbiter.java:120) ~[adapter-rxjava-2.6.4.jar:na]
> 	at retrofit2.adapter.rxjava.CallArbiter.emitResponse(CallArbiter.java:102) ~[adapter-rxjava-2.6.4.jar:na]
> 	at retrofit2.adapter.rxjava.CallExecuteOnSubscribe.call(CallExecuteOnSubscribe.java:46) ~[adapter-rxjava-2.6.4.jar:na]
> 	at retrofit2.adapter.rxjava.CallExecuteOnSubscribe.call(CallExecuteOnSubscribe.java:24) ~[adapter-rxjava-2.6.4.jar:na]
> 	at rx.Observable.unsafeSubscribe(Observable.java:10327) ~[rxjava-1.3.8.jar:1.3.8]
> 	at rx.internal.operators.OnSubscribeMap.call(OnSubscribeMap.java:48) ~[rxjava-1.3.8.jar:1.3.8]
> 	at rx.internal.operators.OnSubscribeMap.call(OnSubscribeMap.java:33) ~[rxjava-1.3.8.jar:1.3.8]
> 	at rx.Observable.unsafeSubscribe(Observable.java:10327) ~[rxjava-1.3.8.jar:1.3.8]
> 	at rx.internal.operators.OnSubscribeSingle.call(OnSubscribeSingle.java:81) ~[rxjava-1.3.8.jar:1.3.8]
> 	at rx.internal.operators.OnSubscribeSingle.call(OnSubscribeSingle.java:27) ~[rxjava-1.3.8.jar:1.3.8]
> 	at rx.internal.operators.SingleToObservable.call(SingleToObservable.java:39) ~[rxjava-1.3.8.jar:1.3.8]
> 	at rx.internal.operators.SingleToObservable.call(SingleToObservable.java:27) ~[rxjava-1.3.8.jar:1.3.8]
> 	at rx.Observable.unsafeSubscribe(Observable.java:10327) ~[rxjava-1.3.8.jar:1.3.8]
> 	at rx.internal.operators.OnSubscribeMap.call(OnSubscribeMap.java:48) ~[rxjava-1.3.8.jar:1.3.8]
> 	at rx.internal.operators.OnSubscribeMap.call(OnSubscribeMap.java:33) ~[rxjava-1.3.8.jar:1.3.8]
> 	at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:48) ~[rxjava-1.3.8.jar:1.3.8]
> 	at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:30) ~[rxjava-1.3.8.jar:1.3.8]
> 	at rx.Observable.unsafeSubscribe(Observable.java:10327) ~[rxjava-1.3.8.jar:1.3.8]
> 	at rx.internal.operators.DeferredScalarSubscriber.subscribeTo(DeferredScalarSubscriber.java:153) ~[rxjava-1.3.8.jar:1.3.8]
> 	at rx.internal.operators.OnSubscribeTakeLastOne.call(OnSubscribeTakeLastOne.java:32) ~[rxjava-1.3.8.jar:1.3.8]
> 	at rx.internal.operators.OnSubscribeTakeLastOne.call(OnSubscribeTakeLastOne.java:22) ~[rxjava-1.3.8.jar:1.3.8]
> 	at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:48) ~[rxjava-1.3.8.jar:1.3.8]
> 	at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:30) ~[rxjava-1.3.8.jar:1.3.8]
> 	at rx.Observable.unsafeSubscribe(Observable.java:10327) ~[rxjava-1.3.8.jar:1.3.8]
> 	at rx.internal.operators.OnSubscribeMap.call(OnSubscribeMap.java:48) ~[rxjava-1.3.8.jar:1.3.8]
> 	at rx.internal.operators.OnSubscribeMap.call(OnSubscribeMap.java:33) ~[rxjava-1.3.8.jar:1.3.8]
> 	at rx.Observable.unsafeSubscribe(Observable.java:10327) ~[rxjava-1.3.8.jar:1.3.8]
> 	at rx.internal.operators.OnSubscribeMap.call(OnSubscribeMap.java:48) ~[rxjava-1.3.8.jar:1.3.8]
> 	at rx.internal.operators.OnSubscribeMap.call(OnSubscribeMap.java:33) ~[rxjava-1.3.8.jar:1.3.8]
> 	at rx.Observable.unsafeSubscribe(Observable.java:10327) ~[rxjava-1.3.8.jar:1.3.8]
> 	at rx.internal.operators.OnSubscribeMap.call(OnSubscribeMap.java:48) ~[rxjava-1.3.8.jar:1.3.8]
> 	at rx.internal.operators.OnSubscribeMap.call(OnSubscribeMap.java:33) ~[rxjava-1.3.8.jar:1.3.8]
> 	at rx.Observable.unsafeSubscribe(Observable.java:10327) ~[rxjava-1.3.8.jar:1.3.8]
> 	at rx.internal.operators.OperatorSubscribeOn$SubscribeOnSubscriber.call(OperatorSubscribeOn.java:100) ~[rxjava-1.3.8.jar:1.3.8]
> 	at rx.internal.schedulers.CachedThreadScheduler$EventLoopWorker$1.call(CachedThreadScheduler.java:230) ~[rxjava-1.3.8.jar:1.3.8]
> 	at rx.internal.schedulers.ScheduledAction.run(ScheduledAction.java:55) ~[rxjava-1.3.8.jar:1.3.8]
> 	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515) ~[na:na]
> 	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264) ~[na:na]
> 	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:304) ~[na:na]
> 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) ~[na:na]
> 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) ~[na:na]
> 	at java.base/java.lang.Thread.run(Thread.java:834) ~[na:na]
> 

**To Reproduce**
1 - Create a VM and using the Wordpress image of bitnami.
2 - Try to install a extension using the following code.
3 - Error occurs.

***Code Snippet***
```
        final String linuxCustomScriptExtensionName = "CustomScript";
        final String linuxCustomScriptExtensionPublisherName = "Microsoft.Azure.Extensions";
        final String linuxCustomScriptExtensionTypeName = "CustomScript";
        final String linuxCustomScriptExtensionVersionName = "2.0";
        final List<String> linuxScriptFileUris = new ArrayList<>();
        linuxScriptFileUris.add("...");

            VirtualMachine vm = azure.virtualMachines().getByResourceGroup("storesResourceGroup",
                    storeName);

            vm.update()
                    .defineNewExtension(linuxCustomScriptExtensionName)
                    .withPublisher(linuxCustomScriptExtensionPublisherName)
                    .withType(linuxCustomScriptExtensionTypeName)
                    .withVersion(linuxCustomScriptExtensionVersionName)
                    .withMinorVersionAutoUpgrade()
                    .withPublicSetting("fileUris", linuxScriptFileUris)
                    .withPublicSetting("commandToExecute", "bash install.sh " + info.getUrl() + " " + info.getTitle() + " " + info.getLanguage())
                    .attach()
                    .apply();
```

**Expected behavior**
Should install the extension with success.

**Setup (please complete the following information):**
 - OS: Windows 10
 - IDE : Intellij
 - Version of the Library used: 1.36.1

**Additional context**

**Information Checklist**
Kindly make sure that you have added all the following information above and checkoff the required fields otherwise we will treat the issuer as an incomplete report
- [x] Bug Description Added
- [x] Repro Steps Added
- [x] Setup information Added

**Comment by esfomeado** [comment]
https://github.com/Azure/azure-libraries-for-java/issues/632

**Comment by yungezz** [comment]
hi @xccc-msft could you pls help to have a look? thanks

**Comment by xccc-msft** [comment]
@esfomeado You may try with below code:
```java
VirtualMachineExtensionInner inner = new VirtualMachineExtensionInner()
                .withPublisher(linuxCustomScriptExtensionPublisherName)
                .withVirtualMachineExtensionType(linuxCustomScriptExtensionTypeName)
                .withTypeHandlerVersion(linuxCustomScriptExtensionVersionName)
                .withAutoUpgradeMinorVersion(true)
                .withSettings(settingMap);
computeManager.inner().virtualMachineExtensions().createOrUpdate("rgName", "vmName", linuxCustomScriptExtensionName, inner);
```

**Comment by esfomeado** [comment]
@xccc-msft Sorry I don't have deep knowledge about the Azure SDK and I haven't found many examples. 
I did the following:

```
ApplicationTokenCredentials credentials = new ApplicationTokenCredentials(
		"xxx", "xxx", "xxx", AzureEnvironment.AZURE
);

ComputeManager computeManager = ComputeManager.authenticate(new RestClient.Builder()
		.withBaseUrl(credentials.environment(), AzureEnvironment.Endpoint.RESOURCE_MANAGER)
		.withResponseBuilderFactory(new AzureResponseBuilder.Factory())
		.withSerializerAdapter(new AzureJacksonAdapter())
		.withCredentials(credentials)
		.build(), "xxx");

Map<String, String> settingsMap = new HashMap<>();
settingsMap.put("commandToExecute", "ls");

VirtualMachineExtensionInner inner = new VirtualMachineExtensionInner()
		.withPublisher("Microsoft.Azure.Extensions")
		.withVirtualMachineExtensionType("CustomScript")
		.withTypeHandlerVersion("2.1")
		.withAutoUpgradeMinorVersion(true)
		.withSettings(settingsMap);

computeManager.inner().virtualMachineExtensions().createOrUpdate("storesResourceGroup", "xxx",
		"CustomScript", inner);
```

I get this error:

> java.lang.IllegalArgumentException: location is required and cannot be null.

If I try to add the _.withLocation()_ to the **VirtualMachineExtensionInner** it returns a Resource instead of a VirtualMachineExtensionInner. Not sure of how to proceed or if you have any other example.

Any input will be welcomed.

Thanks

**Comment by xccc-msft** [comment]
@esfomeado You can add below line before calling createOrUpdate()
```java
inner.withLocation(Region.US_WEST.name());
```

**Comment by esfomeado** [comment]
Works fine now.

Thanks

**Comment by xccc-msft** [comment]
@esfomeado As per the warning info, you may consider to report [here](https://github.com/Azure/autorest-clientruntime-for-java). Thanks.
