### ISSUE TITLE
[Tables] Don't raise an exception when deleting a table/entity that does not exist

### ISSUE THREAD

**Issue by bsiegel** [Azure/azure-sdk-for-java#14490]
Architects would like the delete method to swallow the 404 that occurs if the table/entity trying to be deleted is not found.

- fix deleteEntity method to not throw a 404: entity not found
- fix deleteTable method to not throw a 404: table not found

**Comment by vcolin7** [comment]
We will relegate this behavior to a `deleteIfExists` method instead of making it the default one for `delete` operations.
