### ISSUE TITLE
[BUG] KeyVault KeyProperties.getTags returns null

### ISSUE THREAD

**Issue by ian-barnes** [Azure/azure-sdk-for-java#14513]
**Describe the bug**

Calling `getTags()` on a `KeyProperties` object sometimes returns `null` when it should return the tags.

**To Reproduce**

1. Create a KeyVault key
2. Add tags to it (e.g. via the web interface)
3. Get a `CryptographyClient` for the key
4. Call `cryptographyClient.getKey().getProperties().getTags()` to get the tags. Result is null.
5. Get a `KeyClient` for the vault and call `listPropertiesOfKeys()`
6. Loop through to get the properties for the desired key and call `getTags()`. The tags are there.

***Code Snippet***

Assuming `VAULT_URL`, `KEY_NAME`, `KEY_VERSION` and `CREDENTIAL` are set and valid:

```
    System.out.println("First via CryptographyClient.getKey():");
    String keyId = VAULT_URL + "/keys/" + KEY_NAME + "/" + KEY_VERSION;
    CryptographyClient cryptographyClient = new CryptographyClientBuilder()
        .credential(CREDENTIAL)
        .keyIdentifier(keyId)
        .buildClient();
    Map<String, String> tags = cryptographyClient.getKey().getProperties().getTags();
    if (tags != null) {
      for (Map.Entry<String, String> entry : tags.entrySet()) {
        String key = entry.getKey();
        String value = entry.getValue();
        System.out.printf("%s -> %s\n", key, value);
      }
    } else {
      System.out.println("tags is null");
    }

    System.out.println("And now via KeyClient.listPropertiesOfKeys()");
    KeyClient keyClient = new KeyClientBuilder()
        .vaultUrl(VAULT_URL)
        .credential(CREDENTIAL)
        .buildClient();
    for (KeyProperties keyProperties : keyClient.listPropertiesOfKeys()) {
      if (keyProperties.getName().equals(KEY_NAME)) {
        tags = keyProperties.getTags();
        if (tags != null) {
          for (Map.Entry<String, String> entry : tags.entrySet()) {
            String key = entry.getKey();
            String value = entry.getValue();
            System.out.printf("%s -> %s\n", key, value);
          }
        } else {
          System.out.println("tags is null");
        }
      }
    }
```

**Expected behavior**

Both parts of the code snippet above should print

```
some-tag-name -> some-tag-value
another-tag-name -> another-tag-value
```

but the first one instead prints `tags is null`.

**Screenshots**

![Screenshot from 2020-08-27 16-31-32](https://user-images.githubusercontent.com/49684288/91456254-53a67880-e883-11ea-8908-f5a2d572294f.png)

**Setup:**
 - OS: Debian GNU/Linux bullseye/sid
 - Kernel: Linux 5.7.0-2-amd64
 - Architecture: x86-64
 - IDE : VSCode but running from command line via Gradle
 - Version of the library used: `com.azure:azure-security-keyvault-keys:4.2.0`

**Additional context**

- Possibly related to #10899?
- Possibly a bug in (or incorrect use of) `lazyValueSelection()`. See https://github.com/Azure/azure-sdk-for-java/blob/4becfc24f9a0b94af038c2ab9ec8f201a88a0ea6/sdk/keyvault/azure-security-keyvault-keys/src/main/java/com/azure/security/keyvault/keys/models/KeyProperties.java#L283

**Information Checklist**
Kindly make sure that you have added all the following information above and checkoff the required fields otherwise we will treat the issuer as an incomplete report
- [x] Bug Description Added
- [x] Repro Steps Added
- [x] Setup information Added

**Comment by joshfree** [comment]
Thanks for reporting this intermittent issue @ian-barnes, this is much appreciated.  @vcolin7 can you please follow up?

**Comment by vcolin7** [comment]
No problem, I will look into it :)

**Comment by ian-barnes** [comment]
Just to be clear, I don't think it's intermittent, it just depends on how you obtain the `KeyProperties` object.

**Comment by vcolin7** [comment]
It seems that if you retrieve a key using `KeyClient().getKey()` the same problem occurs, the tags are `null`. I suspect it is related to our Jackson annotations in the `KeyVaultKey` class.
