### ISSUE TITLE
Add connection stats to Cosmos Diagnostics

### ISSUE THREAD

**Issue by moderakh** [Azure/azure-sdk-for-java#14521]
* Add number of RNTBD connections to the targeted replica to Cosmos Diagnostics
* Add total number of RNTBD connections in the RNTBD Connection Pool to Cosmos Diagnostics.

**Comment by kushagraThapar** [comment]
We have captured this information as part of the below PR: 
```
"serviceEndpointStatistics": {
				"availableChannels": 1,
				"acquiredChannels": 0,
				"executorTaskQueueSize": 0,
				"inflightRequests": 1,
				"lastSuccessfulRequestTime": "2020-09-25T17:13:28.216Z",
				"lastRequestTime": "2020-09-25T17:13:28.215Z",
				"createdTime": "2020-09-25T17:13:26.312417Z",
				"isClosed": false
```

https://github.com/Azure/azure-sdk-for-java/pull/15564

Closing this issue, @moderakh  - please create a new issue for total number of RNTBD connection stats.
