### ISSUE TITLE
Integrate azure-spring-cloud-servicebus-queue-stream-binder with Spring Boot Health Check (under binders)

### ISSUE THREAD

**Issue by hirowla** [Azure/azure-sdk-for-java#14571]
**Is your feature request related to a problem? Please describe.**
When using the _azure-spring-cloud-servicebus-queue-stream-binder_ library, the "health" of the binder component is always "UNKNOWN". This should not be the case when a connection to ServiceBus is in fact available.  This is the current output.

```
{
	"status": "UP",
	"components": {
		"binders": {
			"status": "UNKNOWN",
			"components": {
				"servicebus-queue": {
					"status": "UNKNOWN"
				}
			}
		},
	}
}
```

**Describe the solution you'd like**
I'd like a health check on the connection to ServiceBus to give an UP/DOWN/STATUS depending on the status of the binder. This should be in a similar way to how it works for the RabbitMQ binder.

The output from the /actuator/health URL would be similar to the following (other pieces removed):
```
{
	"status": "UP",
	"components": {
		"binders": {
			"status": "UP",
			"components": {
				"servicebus-queue": {
					"status": "UP"
				}
			}
		},
	}
}
```
**Describe alternatives you've considered**
There's always a possibility of writing a manual health check, but this would be common for all users of this component so I suggest that it should be provided (like RabbitMQ provides)

**Additional context**

**Information Checklist**
Kindly make sure that you have added all the following information above and checkoff the required fields otherwise we will treat the issuer as an incomplete report
- [X ] Description Added
- [X ] Expected solution specified

**Comment by joshfree** [comment]
Hi @hirowla, someone from the `azure-spring` team will follow up with you shortly on this issue.

/cc @jialindai @hemanttanwar

**Comment by yiliuTo** [comment]
Hi @hirowla , thanks for your reporting. We will investigate this feature.

**Comment by seanli1988** [comment]
We've backlogged this ask and will provide an update by November this year.

**Comment by ArtyomGabeev** [comment]
hi,

we are interested in this feature as well!

**Comment by dma1979** [comment]
Looking forward for the solution.

**Comment by Manuel-Moya** [comment]
Any progress on this? It is a very important feature.

**Comment by yiliuTo** [comment]
@Manuel-Moya The health check for both Azured Spring Cloud Service Bus queue & topic binders are under development now, please stay tuned.

**Comment by ZhuXiaoBing-cn** [comment]
The PR of the service bus health indicator has been merged into the main branch, please wait for the next release.
