### ISSUE TITLE
[BUG] Send operation timed out when producing events to Azure eventhubs

### ISSUE THREAD

**Issue by madushajg** [Azure/azure-sdk-for-java#14589]
**Describe the bug**
I have a long-running application that uses azure eventhub SDK (5.1.0), continually publishing data to Azure event hub. The service threw the below exception after few days. What could be the cause of this and how we can overcome this?

StackOverflow post: https://stackoverflow.com/questions/63632202/send-operation-timed-out-when-producing-events-to-azure-eventhubs

***Exception or Stack Trace***
```
Exception in thread "SendTimeout-timer" reactor.core.Exceptions$BubblingException: com.azure.core.amqp.exception.AmqpException: Entity(abc): Send operation timed out, errorContext[NAMESPACE: abc-eventhub.servicebus.windows.net, PATH: abc-metrics, REFERENCE_ID: 70288acf171a4614ab6dcfe2884ee9ec_G2S2, LINK_CREDIT: 210]
	at reactor.core.Exceptions.bubble(Exceptions.java:173)
	at reactor.core.publisher.Operators.onErrorDropped(Operators.java:612)
	at reactor.core.publisher.FluxTimeout$TimeoutMainSubscriber.onError(FluxTimeout.java:203)
	at reactor.core.publisher.MonoFlatMap$FlatMapMain.secondError(MonoFlatMap.java:185)
	at reactor.core.publisher.MonoFlatMap$FlatMapInner.onError(MonoFlatMap.java:251)
	at reactor.core.publisher.FluxHide$SuppressFuseableSubscriber.onError(FluxHide.java:132)
	at reactor.core.publisher.MonoCreate$DefaultMonoSink.error(MonoCreate.java:185)
	at com.azure.core.amqp.implementation.ReactorSender$SendTimeout.run(ReactorSender.java:565)
	at java.util.TimerThread.mainLoop(Timer.java:555)
	at java.util.TimerThread.run(Timer.java:505)
Caused by: com.azure.core.amqp.exception.AmqpException: Entity(abc-metrics): Send operation timed out, errorContext[NAMESPACE: abc-eventhub.servicebus.windows.net, PATH: abc-metrics, REFERENCE_ID: 70288acf171a4614ab6dcfe2884ee9ec_G2S2, LINK_CREDIT: 210]
	at com.azure.core.amqp.implementation.ReactorSender$SendTimeout.run(ReactorSender.java:562)
	... 2 more
```

**Setup (please complete the following information):**
 - Version of the Library used is `5.1.0` (Azure eventhub java SDK)

**Information Checklist**
Kindly make sure that you have added all the following information above and checkoff the required fields otherwise we will treat the issuer as an incomplete report
- [x] Bug Description Added
- [x] Repro Steps Added
- [x] Setup information Added

**Comment by joshfree** [comment]
Thanks for filing this github issue, @madushajg.  Someone from the `Event Hubs` team will follow up with you shortly on this reliability issue.

/cc @conniey @srnagar @YijunXieMS

**Comment by conniey** [comment]
@madushajg Hey! Thanks for reporting this bug. I have a few questions:
- What happens when you encounter this error? 
    - Does the application stop working after the exception occurs? Or does it fail for that single send operation?
- Do you have a small snippet for how you are sending events? 

If it is that single operation, you can try to resend the event. The "SendTimeout-Timer" is a timer that waits for an ACK from the Event Hubs service saying that the message was successfully received. There are times where a TimeoutException can occur, in those cases, you should try to resend the message.

[Here is some documentation on possible Event Hubs exceptions.](https://docs.microsoft.com/azure/event-hubs/event-hubs-messaging-exceptions#timeoutexception)

**Comment by madushajg** [comment]
Hi @conniey, please find my answers.
 
> * What happens when you encounter this error?
>   * Does the application stop working after the exception occurs? Or does it fail for that single send operation?

My application stopped working after the exception

> * Do you have a small snippet for how you are sending events?

something similar to the following

```
        EventHubProducerClient producer = new EventHubClientBuilder().connectionString(
                "connection_string",
                "eventhub_name"
        ).buildProducerClient();

        EventDataBatch batch = producer.createBatch();
        EventData sendEvent;
        do {
            final byte[] payloadBytes = gson.toJson("sample_data").getBytes(UTF_8);
            sendEvent = new EventData(payloadBytes);
        } while (batch.tryAdd(sendEvent));
        producer.send(batch);
        }
```
> [Here is some documentation on possible Event Hubs exceptions.](https://docs.microsoft.com/azure/event-hubs/event-hubs-messaging-exceptions#timeoutexception)

I've gone through this. But seems this does not contain any clue :/

**Comment by conniey** [comment]
Hey,

1. The send timeout is a transient error. Does it work when you attempt to send the data again?
1. Can you enable logs when it fails? I'm curious to understand what happens to the AMQP connection.. if it closes or if it tries to reestablish itself.
   1. https://github.com/Azure/azure-sdk-for-java/wiki/Logging-with-Azure-SDK

For example:
```java
EventHubProducerClient producer = new EventHubClientBuilder()
    .connectionString("connection_string","eventhub_name")
    .buildProducerClient();

EventDataBatch batch = producer.createBatch();
EventData sendEvent;

do {
    final byte[] payloadBytes = gson.toJson("sample_data").getBytes(UTF_8);
    sendEvent = new EventData(payloadBytes);
} while (batch.tryAdd(sendEvent));

boolean isSent = false;
while (!isSent) {
    try {
        producer.send(batch);
        isSent = true;
    } catch (Exception e) {
        System.out.printf("Unable to send batch: %s%n.", e);
    }
}
```

Thanks!

**Comment by conniey** [comment]
Feel free to open this issue if my sample doesn't work for you or open a new issue if something else pops up. :)
