### ISSUE TITLE
Support Environment Variable "AZURE_RESOURCE_GROUP"

### ISSUE THREAD

**Issue by cxznmhdcxz** [Azure/azure-sdk-for-java#14583]
According to environment variables listed in https://github.com/Azure/azure-sdk/blob/master/_includes/tables/environment_variables.md

Add support for environment variable "AZURE_RESOURCE_GROUP"

</br>
@jongio

**Comment by alzimmermsft** [comment]
Hi @cxznmhdcxz, is this issue requesting adding this property or leveraging it?

**Comment by joshfree** [comment]
Closing; this work is tracked in https://github.com/Azure/azure-sdk-for-java/issues/27004
