### ISSUE TITLE
Support Environment Variable "AZURE_TRACING_DISABLED"

### ISSUE THREAD

**Issue by cxznmhdcxz** [Azure/azure-sdk-for-java#14584]
According to environment variables listed in https://github.com/Azure/azure-sdk/blob/master/_includes/tables/environment_variables.md

Add support for environment variable  "AZURE_TRACING_DISABLED"

</br> @jongio

**Comment by alzimmermsft** [comment]
Hi @cxznmhdcxz, is this issue requesting adding this property or leveraging it?
