### ISSUE TITLE
Azure hierarchial Directory listing with pagination token support

### ISSUE THREAD

**Issue by rajivml** [Azure/azure-sdk-for-java#14592]
HI,

This is the piece of code am using to list the files under a directory in a paginated fashion, but what I actually require is, I want to list the folders under a directory first followed by listing the files, exactly the output similar to that of Azure storage explorer or container explorer because that is what our end users prefer to see and this is supported by both google and aws storage clients and we are expecting similar behaviour with azure storage client as well.

I tried using listBlobsByHierarchy Method, but it does not accept paginationToken.

So, Can you guys please suggest what should be the way to go. If it's already supported by azure client and if am doing something wrong, then plz guide me or if it's not supported currently, then plz take it as an enhancement request 

`            BlobContainerClient blobContainerClient = storage.getBlobContainerClient(bucketName);
            List<BlobMetadata> blobMetadataList = new ArrayList<>();
            final String[] nextPageToken = {null};

            BlobListDetails blobListDetails = new BlobListDetails();
            blobListDetails.setRetrieveMetadata(true);

            ListBlobsOptions blobsOptions = new ListBlobsOptions();
            blobsOptions.setPrefix(directory);
            blobsOptions.setMaxResultsPerPage(pageSize);
            blobsOptions.setDetails(blobListDetails);

            List<BlobItem> results = getArrayListBlobs();

            // Fetch Only One Page and that page will have N records
            blobContainerClient.listBlobs(blobsOptions, pageToken, null)
                .streamByPage()
                .limit(1)
                .forEach(response -> {
                    results.addAll(response.getValue());
                    if (response.getContinuationToken() != null) {
                        nextPageToken[0] = response.getContinuationToken();
                    }
                });

            for (BlobItem blob : results) {
                BlobMetadata blobMetadata = new BlobMetadata();
                blobMetadata.setBucketName(storage.getAccountName());
                blobMetadata.setMediaLink(getMediaURL(storage.getAccountName(), bucketName, blob.getName()));
                blobMetadata.setBlobName(blob.getName());
                if (blob.getName().endsWith("/")) {
                    blobMetadata.setBlobType(BlobType.DIRECTORY);
                    blobMetadataList.add(blobMetadata);
                } else {
                    blobMetadata.setBlobType(BlobType.FILE);
                    blobMetadata.setContentType(blob.getProperties().getContentType());
                    blobMetadata.setBlobSize(blob.getProperties().getContentLength());
                    blobMetadata.setCreateTime(blob.getProperties().getLastModified().toEpochSecond());
                    blobMetadataList.add(blobMetadata);
                }
            }
            pageListingTokenBasedDto.setDataList(blobMetadataList);
            if (StringUtils.isNotEmpty(nextPageToken[0])) {
                pageListingTokenBasedDto.setNextPageToken(nextPageToken[0]);
            }`

**Comment by joshfree** [comment]
Hi @rajivml someone from the `Storage` team will follow up shortly on your github issue.  Thanks.

/cc @gapra-msft @rickle-msft @alzimmermsft

**Comment by gapra-msft** [comment]
Hi @rajivml Thank you for posting this issue. 

We actually do support a way to listBlobsByHierarchy with a continuationToken. 

The listBlobsByHierarchy method returns a PagedIterable type that allows you to specify a continuationToken with the iterableByPage(String continuationToken) method. I think there is also a streamByPage(continuationToken) method. 

Here is a [link ](https://github.com/Azure/azure-sdk-for-java/blob/2db109ba65cc5c90217efed75ac3c65b914f8da5/sdk/storage/azure-storage-blob/src/test/java/com/azure/storage/blob/ContainerAPITest.groovy#L1312) to a test (in Groovy) where you can see the method being used. 

If you need a more detailed Java sample, let me know and I'd be happy to provide it.

**Comment by rajivml** [comment]
@gapra-msft thanks for the reply, can you please share me an detailed example, I had a look at the tests, there is a way to get nextContinutationToken but there is no method which accepts pageToken as input

**Comment by rajivml** [comment]
Based on your suggestion, by modifying the code like this, am able to listBlobs using listBlobsByHierarchy method along with paginationToken.

Now the only missing piece is displaying folders first followed by rest of the blobs


`            // Fetch Only One Page and that page will have N records
            if (StringUtils.isEmpty(pageToken)) {
                blobContainerClient.listBlobsByHierarchy("/", blobsOptions, null)
                    .streamByPage()
                    .limit(1)
                    .forEach(response -> {
                        results.addAll(response.getValue());
                        if (response.getContinuationToken() != null) {
                            nextPageToken[0] = response.getContinuationToken();
                        }
                    });
            } else {
                blobContainerClient.listBlobsByHierarchy("/", blobsOptions, null)
                    .streamByPage(pageToken, pageSize)
                    .limit(1)
                    .forEach(response -> {
                        results.addAll(response.getValue());
                        if (response.getContinuationToken() != null) {
                            nextPageToken[0] = response.getContinuationToken();
                        }
                    });
            }`

**Comment by gapra-msft** [comment]
Hi @rajivml The listBlobsByHierarchy method returns the listed blobs in the same order as the service returns (alphabetical), and we do not support any other ordering. If you take a look at our [docs](https://azuresdkdocs.blob.core.windows.net/$web/java/azure-storage-blob/12.8.0/index.html) for the method, it specifies that a folder/directory can be identified by the isPrefix parameter on the BlobItem. Based on this information, I think isPrefix is the parameter to look at to order the elements properly before displaying them. 

Hope that helps.

**Comment by rajivml** [comment]
okay got it, in that case, only con is, I cannot ensure page size to always returns exactly N keys are returned. anyhow i have this problem with s3 client as well. you can resolve it.

Thanks for your assistance on this ticket

**Comment by gapra-msft** [comment]
Feel free to open a new issue if you hit any other issues/have other questions.
