### ISSUE TITLE
[QUERY] SharedAccessSignature not working for Event Hubs with Java SDK v5.1.2.

### ISSUE THREAD

**Issue by mattbalgeman** [Azure/azure-sdk-for-java#14595]
**Describe the bug**
SharedAccessSignatures aren't working for event hubs for v5.1.2 of the Java SDK.

***Exception or Stack Trace***
java.lang.IllegalArgumentException: Illegal connection string parameter name: SharedAccessSignature

**To Reproduce**
Generate a SharedAccessSignature for an event hub and attempt to use that Signature in the ConnectionString.
In previous versions of the SDK, that connection string would look something like this:
`Endpoint=sb://<namespacename>.servicebus.windows.net;EntityPath=<eventhubname>;SharedAccessSignature=SharedAccessSignature sr=sb%3A%2F%2F<namespacename>.servicebus.windows.net%2F<eventhubname>&sig=IciALS180<somecharsremoved>&se=159<somenumbersremoved>&skn=SendRule`

In the new version of the SDK, ConnectionStringProperties doesn't except the SharedAccessSignature option and throws an exception.  I was unable to find any other option that supports SharedAccessSignatures.

***Code Snippet***
Add the code snippet that causes the issue.

**Expected behavior**
I would expect the new SDK to have feature parity with the old version and support SharedAccessSignatures.  Also, it appears that ConnectionStringBuilder was removed?

**Screenshots**

**Setup (please complete the following information):**
 - IDE : IntelliJ
 - Version of the Library used
<dependency>
    <groupId>com.azure</groupId>
    <artifactId>azure-messaging-eventhubs</artifactId>
    <version>5.1.2</version>
</dependency>

**Additional context**

**Information Checklist**
Kindly make sure that you have added all the following information above and checkoff the required fields otherwise we will treat the issuer as an incomplete report
- [X] Bug Description Added
- [X] Repro Steps Added
- [X] Setup information Added

**Comment by joshfree** [comment]
Thanks for filing this github issue @mattbalgeman.  @conniey could you please follow up?

**Comment by conniey** [comment]
@mattbalgeman Thanks for filing this issue. This is not currently supported in Event Hubs or Service Bus... We do have an open Azure SDK issue to address this:
https://github.com/Azure/azure-sdk/issues/1701

Parent Discussion: https://github.com/Azure/azure-sdk/issues/1701
Related: https://github.com/Azure/azure-sdk-for-js/issues/10851

**Comment by mattbalgeman** [comment]
Thanks for the information.  Unfortunately, this means that will be need to stick with the old version of the Java SDK until this issue is resolved.  We'll watch the referenced discussion for further information.

**Comment by srnagar** [comment]
@mattbalgeman Support for including SharedAccessSignature in connection string was added in the latest [Event Hubs release](https://github.com/Azure/azure-sdk-for-java/blob/azure-messaging-eventhubs_5.2.0/sdk/eventhubs/azure-messaging-eventhubs/CHANGELOG.md#520-2020-09-11). Please try the new released version:

azure-messaging-eventhubs - `5.2.0`
