### ISSUE TITLE
SB Track2 : Creating new issue to track the suggestion to remove the message settlement overloads that take lock tokens 

### ISSUE THREAD

**Issue by hemanttanwar** [Azure/azure-sdk-for-java#14664]
Creating new issue to track the suggestion to remove the message settlement overloads that take lock tokens 

Discussion on this issue : https://github.com/Azure/azure-sdk-for-net/issues/10852#issuecomment-679859788

**Comment by ramya-rao-a** [comment]
Once the locktoken is replaced with message, we would not need the sessionId overloads because sessionId can be picked up from the message
