### ISSUE TITLE
Ship Key Vault Administration package as 4.0.0-beta.1

### ISSUE THREAD

**Issue by heaths** [Azure/azure-sdk-for-java#14672]
Based on discussion with architects, we'll want to ship the administration package as a 4.0 since it's branch new. It will not be in version lock-step with other Key Vault packages.

**Comment by vcolin7** [comment]
[Shipped](https://search.maven.org/artifact/com.azure/azure-security-keyvault-administration/4.0.0-beta.1/jar)!
