### ISSUE TITLE
When should SDK switch to Java 8 as min req?

### ISSUE THREAD

**Issue by martinsawicki** [Azure/azure-sdk-for-java#1468]
This issue is to track the question of when to base the Azure Management Libraries for Java on Java 8, collecting the pros and cons and eventually resulting in a decision.

Pros:
- **Lambda support** - which we'd take advantage of quite heavily in the SDK, as we already have the awkward Java-7 style equivalent of that in many places, and would also be able to remove a bunch of code
- **Java 7 "end-of-life'd"** (no public updates) as of [April 2015](https://java.com/en/download/faq/java_7.xml). It's been a while...
- **Enable users to cleanly compile SDK from sources with Java 8** - today, due to how annotation processors work, we have to have RELEASE_7 in our annotation impls, resulting in issue https://github.com/Azure/azure-sdk-for-java/issues/1653

Cons:
- about 28% of Java users are still on Java 7 still, [per RebellLabs](https://zeroturnaround.com/rebellabs/java-tools-and-technologies-landscape-2016/).

**Comment by RikkiGibson** [comment]
Pros: streams!

**Comment by RikkiGibson** [comment]
Also, CompletableFuture!

**Comment by MihaiBojin** [comment]
+1 for addressing this issue (https://github.com/Azure/azure-sdk-for-java/issues/1653 : `Supported source version 'RELEASE_7' from annotation processor 'com.microsoft.azure.management.apigeneration.LangDefinitionProcessor  less than -source '1.8'`)

If I can make a suggestion, you could take a gradual approach:
- first, release a new version of this SDK, compiled against 1.8 (only refactoring the absolute necessary)
- then, map out where newer JDK features fit into the project and refactor the library gradually

Thank you!

**Comment by Petermarcu** [comment]
We're making the switch as part of our conversion to new code generators and autorest v3. This will bring the management libraries in sync with the design guidelines. https://azure.github.io/azure-sdk/java_introduction.html. I'm going to close this issue as its tracked as part of the larger conversion.
