### ISSUE TITLE
Sample code suggestions

### ISSUE THREAD

**Issue by YijunXieMS** [Azure/azure-sdk-for-java#14689]
I'm thinking of some changes to the sample code to make it runnable out of the box. It will be easier for users to try the sample code. It will also benefit us when we want to run/test a sample code.

1. Use properties, OS environment variable, or a config file for the connection parameters. After a user configures these params, all samples of a service SDK will be runnable without any changes. azure-core has `com.azure.core.util.Configuration` and the Storage SDK samples use it. Some other SDKs haven't so a user needs to change the sample code to run it. We may use similar service-specific config class if service-specific params are not good to use azure core Configuration.
2. Add logging in the sample code and enable the logging. Most users enable the logging when they use our SDKs.
3. Some user server-side applications run forever until interrupted. We usually demo running for a certain period of time. Users may wonder how to gracefully shutdown, like close the client/connection at an appropriate time, when an interruption (Ctrl-C, kill, etc) is issued. So we can have some samples that run forever with graceful shutdown.

**Comment by joshfree** [comment]
Related https://github.com/Azure/azure-sdk-for-java/issues/14690
