### ISSUE TITLE
[BUG] Sample ServiceBusQueueMultiBindersApplication in wrong directory

### ISSUE THREAD

**Issue by jvalkeal** [Azure/azure-sdk-for-java#14686]
**Describe the bug**
Not sure how `azure-spring-cloud-servicebus-queue-multibinders-sample` even compiles but at least vscode can't find `ServiceBusQueueMultiBindersApplication` from its tests.

Directory `com.example` should be `com/example`.

https://github.com/Azure/azure-sdk-for-java/blob/master/sdk/spring/azure-spring-boot-samples/azure-spring-cloud-servicebus-queue-multibinders-sample/src/main/java/com.example/ServiceBusQueueMultiBindersApplication.java

**Comment by joshfree** [comment]
@hemanttanwar @jialindai can you please follow up on this issue reported by @jvalkeal

**Comment by yiliuTo** [comment]
@jvalkeal Thanks for your reporting, we will fix it soon.

**Comment by yiliuTo** [comment]
Hi @jvalkeal , now the PR has been merged, you can go with the sample. If there are no other problems then you can close this issue.

**Comment by yiliuTo** [comment]
Close this issue since it has been fixed.
