### ISSUE TITLE
missing locations from Region's maps

### ISSUE THREAD

**Issue by milismsft** [Azure/azure-sdk-for-java#1470]
"koreacentral" in not in the Region's maps (see com.microsoft.azure.management.resources.fluentcore.arm.Region)

**Comment by nwarriorch** [comment]
Is there an update on this?

**Comment by martinsawicki** [comment]
koreacentral was added in v1.0.0 release
https://github.com/Azure/azure-sdk-for-java/commit/73367fd6cd523f919ffb1e73f0963b2dd63b8bd7
