### ISSUE TITLE
retrieving vaults via vaults().list() does not return the full Vault object

### ISSUE THREAD

**Issue by milismsft** [Azure/azure-sdk-for-java#1471]
Looks like we make a REST call to Azure to list the resources only; instead we should list the resource groups first and for each resource group found list the vaults via vaults().listByGroup()

Repro:
Azure azureClient; // do some initialization here
for (Vault vault : azureClient.vaults().list()) {
  System.out.println(vault.vaultUri()); // this prints out "null"
}

**Comment by martinsawicki** [comment]
removed listing by subscription so this is moot now....
