### ISSUE TITLE
[BUG] Azure Storage Blob doesn't add external applicationID

### ISSUE THREAD

**Issue by yiliuTo** [Azure/azure-sdk-for-java#14729]
**Describe the bug**
when initiate an `HttpPipeline`, the BuilderHelper#buildPipeline function add the user agent policy from a default `HttpLogOptions` which dosen't read from the `HttpLogOptions` parameter from BuilderHelper#buildPipeline function, causing external applicationId failed to be added in `HttpPipeline`.

***Code Snippet***
```
    public static HttpPipeline buildPipeline(StorageSharedKeyCredential storageSharedKeyCredential,
        TokenCredential tokenCredential, SasTokenCredential sasTokenCredential, String endpoint,
        RequestRetryOptions retryOptions, HttpLogOptions logOptions, HttpClient httpClient,
        List<HttpPipelinePolicy> additionalPolicies, Configuration configuration, ClientLogger logger) {

        // Closest to API goes first, closest to wire goes last.
        List<HttpPipelinePolicy> policies = new ArrayList<>();

        policies.add(getUserAgentPolicy(configuration));
        policies.add(new RequestIdPolicy());
        ...
```
```
    private static UserAgentPolicy getUserAgentPolicy(Configuration configuration) {
        configuration = (configuration == null) ? Configuration.NONE : configuration;

        String clientName = PROPERTIES.getOrDefault(SDK_NAME, "UnknownName");
        String clientVersion = PROPERTIES.getOrDefault(SDK_VERSION, "UnknownVersion");
        return new UserAgentPolicy(getDefaultHttpLogOptions().getApplicationId(), clientName, clientVersion,
            configuration);
    } 
    public static HttpLogOptions getDefaultHttpLogOptions() {
        HttpLogOptions defaultOptions = new HttpLogOptions();
        BlobHeadersAndQueryParameters.getBlobHeaders().forEach(defaultOptions::addAllowedHeaderName);
        BlobHeadersAndQueryParameters.getBlobQueryParameters().forEach(defaultOptions::addAllowedQueryParamName);
        return defaultOptions;
    }
```

**Expected behavior**
When set the user agent of HttpPipelinePolicy, external applicationIds are expected to be added in the front.

**Setup (please complete the following information):**
 - OS: Windows
 - IDE : IntelliJ
 - Version of the Library used: 12.8.0

**Information Checklist**
Kindly make sure that you have added all the following information above and checkoff the required fields otherwise we will treat the issuer as an incomplete report
- [x] Bug Description Added
- [ ] Repro Steps Added
- [x] Setup information Added

**Comment by rickle-msft** [comment]
Hi, @yiliuTo. Thank you for reporting this. I need to confer with my team on whether this is expected behavior or not. Azure Core provides an alternate way to update the user agent string by either overriding it completely or appending more information to the end, and we may prefer that you use this approach. 

UserAgentPolicy defines some constants that you can use to set values on a Context that you pass to each method call which can modify the user agent accordingly

**Comment by saragluna** [comment]
@rickle-msft when we tried with 12.8.0 of storage blob sdk and logged the HTTP request headers sent by the sdk, our application id didn't show up in the UserAgent.

```xml
<dependency>
      <groupId>com.azure</groupId>
      <artifactId>azure-storage-blob</artifactId>
      <version>12.8.0</version> 
      <optional>true</optional>
    </dependency>
```

**Comment by gapra-msft** [comment]
@saragluna Could you please try 12.9.0-beta.1?
I believe the fix is in that release and onwards.

**Comment by saragluna** [comment]
@gapra-msft thanks, I'll try.

**Comment by saragluna** [comment]
@gapra-msft tried with version 12.9.0 and now it works! Thank you!
