### ISSUE TITLE
[QUERY] Azure blob MSI authentication example

### ISSUE THREAD

**Issue by shettyh** [Azure/azure-sdk-for-java#14730]
**Query/Question**
Looking for a way to authenticating to Azure storage account using MSI based authentication using `clientId,clientSecret, authorityUrl`. Is there any way to do this ?

Any sample would be great. Thanks in advance

**Comment by amishra-dev** [comment]
@shettyh 
Hi Manjunath,
Please look at https://github.com/Azure/azure-sdk-for-java/blob/6fb6fda3927c0e2af3bc890877e456ae8ea9d5e9/sdk/identity/azure-identity/README.md#defaultazurecredential

Here is a sample: https://github.com/Azure/azure-sdk-for-java/blob/8cf736e7e8d9904ffb9336da1d14e6062a70a518/sdk/storage/azure-storage-blob/src/samples/java/com/azure/storage/blob/AzureIdentityExample.java

**Comment by shettyh** [comment]
@amishra-dev  Thanks for the info. I was able to connect to blob using `ClientSecretCredential` like this

```java
ClientSecretCredential clientSecretCredential = new ClientSecretCredentialBuilder()
        .clientId("<clientId>")
        .clientSecret("<client secret>")
        .authorityHost("<authority url>")
        .tenantId("<tenet id>")
        .build();

```
