### ISSUE TITLE
Support for different cloud environments

### ISSUE THREAD

**Issue by sarintom** [Azure/azure-sdk-for-java#14738]
**Query/Question**
I'm using azure-keyvault-secrets-spring-boot-starter library to read our secrets from Key Vault. It works beautifully in our global environment which reads secrets from a KeyVault that resides in global Azure cloud. We also have the same application running in Azure China cloud and we have deployed another KeyVault there. Is it possible to configure the KeyVault starter so that it connects there via Chinese AAD? Currently it seems that it always connects to global Azure AD.

***Why is this not a Bug or a feature Request?***
It's a bit unclear if this is possible or not. There aren't documentation about this at least but some kind of enironment variables are available still.

**Setup (please complete the following information if applicable):**
Version 2.3.3
 
 **Information Checklist**
 Kindly make sure that you have added all the following information above and checkoff the required fields otherwise we will treat the issuer as an incomplete report
- [x] Query Added
- [x] Setup information Added

**Comment by joshfree** [comment]
Thanks for filing this question on `azure-keyvault-secrets-spring-boot-starter`.  @jialindai could you please assist?

/cc @vcolin7 @hemanttanwar

**Comment by yiliuTo** [comment]
Hi @sarintom , to visit Azure China AAD, you can set the authority host to Azure China url, which is to set the environment variable as below
`AZURE_AUTHORITY_HOST=https://login.chinacloudapi.cn`

**Comment by yiliuTo** [comment]
Hi @sarintom , this issue has been fixed in one of our underpinning libraries `azure-identity` 1.1.0 version and our next release of key vault starter will update this dependency to 1.1.0. So you can wait for our next release. 
And when update to the new release, you can configue key vault starter to Azure China by adding an environment variable as `AZURE_AUTHORITY_HOST=https://login.chinacloudapi.cn/`

**Comment by sarintom** [comment]
That is great! Thank you for quick reply
