### ISSUE TITLE
Share Cosmos SDK TransportClient instances with different ConnectionPolicy

### ISSUE THREAD

**Issue by kushagraThapar** [Azure/azure-sdk-for-java#14759]
**Is your feature request related to a problem? Please describe.**
* CosmosClient allows to share TransportClient which shares the I/O resources, but there is no way to update the ConnectionPolicy parameters on the shared Transport Client. 

**Describe the solution you'd like**
* Share TransportClient instances with different ConnectionPolicy, if `connectionPolicy` instance passed by the end user is different from the other `CosmosClient`.

**Comment by FabianMeiswinkel** [comment]
Can you elaborate in which scenarios customers would need two different connection policies for the same target account? I am wondering whether the right approach could be to expose the property/properties that need to be different in these cases as RequestOptions instead.

**Comment by kushagraThapar** [comment]
@FabianMeiswinkel - these are the cases where customer want to have different connection policy settings for different time period. 
Like for heavy traffic days, they would like to update `DirectConnectionConfig` and `GatewayConnectionConfig` params (specially IdleTcpTimeout, IdleEndpointTimeout, etc.) and have the new / shared client come up with those settings.

**Comment by kushagraThapar** [comment]
This is less relevant now, given we are moving towards adaptive connection settings going forward. Building smarter SDK.
