### ISSUE TITLE
I cannot check the backend-health using java sdk

### ISSUE THREAD

**Issue by atdi** [Azure/azure-sdk-for-java#1477]
How to check the health of application gateway using java sdk.
I need to perform a similar operation like below azure cli command using java sdk:

*azure network application-gateway backend-health show "$1" "$2" --json \ | jq -r '.backendAddressPools[].backendHttpSettingsCollection[].servers[] | select(.health == "Healthy") | .address'*

**Comment by martinsawicki** [comment]
This is not yet exposed in the fluent API of the Java management libraries directly. 
For the time being, a backdoor workaround that could be used would be to get to the auto-generated "Inner" client implementation of the application gateway service, and call `backendHealth()` directly. For example, see if this helps:
```java
ApplicationGateway ag = azure.applicationGateways().get(myAGresourceId);
ApplicationGatewayBackendHealthInner health = azure.applicationGateways().inner().backendHealth(ag.resourceGroupName(), ag.name());
for (ApplicationGatewayBackendHealthPool poolHealth : health.backendAddressPools()) {
  for (ApplicationGatewayBackendHealthHttpSettings configHealth : poolHealth.backendHttpSettingsCollection()) {
    for (ApplicationGatewayBackendHealthServer serverHealth : configHealth.servers()) {
      if (serverHealth.health() != null) {
        System.out.println(serverHealth.address() + ": " + serverHealth.health().toString());
      }
    }
  }
}
```

**Comment by martinsawicki** [comment]
Word of clarification: note the above workaround works in master, not in the released beta5, because beta5 did not yet expose `inner()` on collection objects or managers.

**Comment by martinsawicki** [comment]
in progress for v1.4: https://github.com/Azure/azure-sdk-for-java/pull/1945
