### ISSUE TITLE
CosmosDB SqlParameter does not implement equals

### ISSUE THREAD

**Issue by elhoo** [Azure/azure-sdk-for-java#14862]
**Query/Question**
Is there a reason that the SqlParameter does not implement equals?

I was writing a test:
```
    @Test
    public void shouldFindRecipes() {
        // Given
        RecipeSearchDto dto = new RecipeSearchDto(List.of("tag1"), List.of("category1"));
        // When
        SqlQuerySpec spec = recipeService.buildQueryForFindingRandomRecipes(dto);
        // Then
        assertThat(spec.getQueryText()).isEqualTo("SELECT c.id FROM c WHERE (ARRAY_CONTAINS(c.tags, @TAG0)) AND  c.category IN (@CATEGORY0)");
        assertThat(spec.getParameters()).contains(
                new SqlParameter("@TAG0", "tag1"),
                new SqlParameter("@CATEGORY0", "category1")
        );
    }
```
I was quite sure that the test should be green, but I got:
```
java.lang.AssertionError: 
Expecting ArrayList:
 <[com.azure.cosmos.models.SqlParameter@4983159f,
    com.azure.cosmos.models.SqlParameter@44e3a2b2]>
to contain:
 <[com.azure.cosmos.models.SqlParameter@732f29af,
    com.azure.cosmos.models.SqlParameter@d3957fe]>
but could not find the following element(s):
 <[com.azure.cosmos.models.SqlParameter@732f29af,
    com.azure.cosmos.models.SqlParameter@d3957fe]>
```

***Why is this not a Bug or a feature Request?***
It feels like a explicit choice that is isn't implementing equals() and I want to understand why.
Please change this to feature request if necessary

**Setup (please complete the following information if applicable):**
N/A

 **Information Checklist**
 Kindly make sure that you have added all the following information above and checkoff the required fields otherwise we will treat the issuer as an incomplete report
- [x] Query Added
- [x] Setup information Added

**Comment by joshfree** [comment]
Thanks for reporting this @elhoo -- @kushagraThapar from the `Cosmos` team will follow up

**Comment by kushagraThapar** [comment]
@elhoo - Thanks for creating this issue, no specific reason to not implement it. 
We can implement `equals` and `hashcode` in the next release. I will track it.

**Comment by elhoo** [comment]
Thank you!
