### ISSUE TITLE
[FEATURE REQ]Service Bus Binder Support Dead Letter Queue

### ISSUE THREAD

**Issue by chenghaoharvey** [Azure/azure-sdk-for-java#14860]
Refer to https://github.com/microsoft/spring-cloud-azure/issues/530

**Comment by joshfree** [comment]
Hi @chenghaoharvey thanks for filing this feature request for `Service Bus`.  Someone from the Service Bus team will follow up with you shortly.

/cc @ramya-rao-a

**Comment by ramya-rao-a** [comment]
@joshfree I believe the required consensus on the next steps here was concluded in https://github.com/microsoft/spring-cloud-azure/issues/530 which is for @chenghaoharvey to move their PR from https://github.com/microsoft/spring-cloud-azure to this repo.

Assigning this issue to @saragluna who is active in the linked issue and in the Spring Cloud Stream Binder for Service Bus project

@chenghaoharvey, you last mentioned in https://github.com/microsoft/spring-cloud-azure/issues/530#issuecomment-678803646 that you have an issue with installing "Microsoft Azure Java Core Library"  when working in this repo. Did the [contributing guide](https://github.com/Azure/azure-sdk-for-java/blob/master/sdk/spring/CONTRIBUTING.md#building-from-source) @saragluna shared help?

**Comment by chenghaoharvey** [comment]
yes, the contributing guide helped me solve the installing problems. Many thanks for you and @saragluna helping. Thanks

**Comment by saragluna** [comment]
Closing this now since PR's been merged.
