### ISSUE TITLE
Query on publishing VM image in Azure Marketplace with restricted access

### ISSUE THREAD

**Issue by amitarali** [Azure/azure-sdk-for-java#1487]
Hi,

We have a use case where we want to publish private/custom VM image in Azure Marketplace but with restricted access i.e. only specific users or specific subscriptions should access this offer and provision it.

Could you please let us know if this scenario is possible in Azure? If yes, any pointers to documentation details will help us.

I checked below link but could not find anything related to restricted access.
https://docs.microsoft.com/en-us/azure/marketplace-publishing/marketplace-publishing-getting-started

Thanks,
Amit

**Comment by anuchandy** [comment]
Hi Amit, 

I am not sure about Market place image but Azure recently started supporting user image where user can publish an image in a specific subscription and use it to spin up virtual machines. See below for details. [If the user image cannot handle your use case then i can ask compute team about private market place image, let me know.]

1. Once you prepare the generalized image (vhd) locally, upload it to a azure storage account in your subscription using this tool https://github.com/Microsoft/azure-vhd-utils  

```bash
   vhd upload [command options] [arguments...]

OPTIONS:
   --localvhdpath       Path to source VHD in the local machine.
   --stgaccountname     Azure storage account name.
   --stgaccountkey      Azure storage account key.
   --containername      Name of the container holding destination page blob. (Default: vhds)
   --blobname           Name of the destination page blob.
   --parallelism        Number of concurrent goroutines to be used for upload
```

2. Note down the VHD URL in the storage account 

```java
String URLToVhd = "http://" ; // URL to VHD 
```

2. Create a user image from this VHD as below

```java
String userImageName = "";  // name for the user image 
Region region = Region.US_EAST;
String newRgName = ""; // name for the new resource group 
VirtualMachineCustomImage virtualMachineCustomImage = azure.virtualMachineCustomImages()
     .define(userImageName)
     .withRegion(region)
     .withNewResourceGroup(rgName)
     .withLinuxFromVhd(URLToVhd, OperatingSystemStateTypes.GENERALIZED)
     .create();
```

If VHD is Windows image then use `.withWindowsFromVhd(URLToVhd, OperatingSystemStateTypes.GENERALIZED)` 

3. Create virtual machine using the image 

String userName = ""; // vm user name
String password = ""; //  vm password
```java

VirtualMachine linuxVM = azure.virtualMachines().define(linuxVmName)
     .withRegion(region)
     .withExistingResourceGroup(newRgName)
     .withNewPrimaryNetwork("10.0.0.0/28")
     .withPrimaryPrivateIpAddressDynamic()
     .withoutPrimaryPublicIpAddress()
     .withLinuxCustomImage(virtualMachineCustomImage.id())
     .withRootUsername(userName)
     .withRootPassword(password)
     .withSize(VirtualMachineSizeTypes.STANDARD_D3_V2)
     .create();
```

**Comment by anuchandy** [comment]
@amitarali we have addressed your query, closing this issue.
