### ISSUE TITLE
[QUERY] how to switch http library?

### ISSUE THREAD

**Issue by stefankaticec** [Azure/azure-sdk-for-java#14877]
**Query/Question**
Hello. 

On startup of the application, before any invocation of azure library code, a couple of threads spawn and they refuse to close immediately. Sometimes, it takes two minutes to close gracefully and you can imagine how irritating this is during development. 

Threads mentioned:
OkHttp ConnectionPool
OkHttp Http2Connection
OkHttp management.azure.com
OkHttp management.azure.com Writer

Since this OkHttp is probably not going away, how do I the implementation of the Http library being used?
Consider that okhttp is being used by other libraries in the code and excluding the dependency will make other parts of the system break.

***Why is this not a Bug or a feature Request?***
You didn't create Okhttp. 

**Setup (please complete the following information if applicable):**
 - OS: Ubuntu 18.04
 - IDE : IntelliJ
 - Version of the Library used
1.27.2

Thread dump on closing, shows OkHttp management.azure.com still being alive and refusing to close gracefully. 

 
 **Information Checklist**
 Kindly make sure that you have added all the following information above and checkoff the required fields otherwise we will treat the issuer as an incomplete report
- [x ] Query Added
- [ ] Setup information Added

**Comment by joshfree** [comment]
Hi @stefankaticec, thanks for posting this question on configuring HTTP Clients.  The instructions for replacing the default HTTP Client with any of the latest Unified SDKs for Azure (packages start with "com.azure" instead of "com.microsoft.azure") can be found here: https://github.com/Azure/azure-sdk-for-java/wiki/HTTP-clients#replacing-the-default-http-client.

Let us know if you have any other questions.

**Comment by stefankaticec** [comment]
Hi @joshfree Thanks for you answer. I do have questions though. How is the com.azure different from com.microsoft.azure? I see both are released on September 4. We are using com.microsoft.azure stuff. Does this mean this is only achievable for the com.azure and not for what we are using?

**Comment by joshfree** [comment]
@stefankaticec sorry for the late reply.  Yes, `com.azure` identifies client library components which are part of the new Unified Azure SDK.  Client libraries using `com.microsoft.azure` are the previous major release and do not benefit from the improvements made to the client libraries shipped under `com.azure`.

Here's some additional information, including a short youtube video describing this in more detail:

- https://azure.github.io/azure-sdk/releases/latest/index.html
- https://www.youtube.com/watch?v=38RYIx7a2M4

I'm going to close out this issue now, but feel free to reactivate it or file a new issue if there's an additional question or feedback.

Thanks again.
