### ISSUE TITLE
Enable Integration test KeyVaultIT.keyVaultWithVirtualMachineMSI

### ISSUE THREAD

**Issue by chenrujun** [Azure/azure-sdk-for-java#14871]
Related code: https://github.com/Azure/azure-sdk-for-java/blob/master/sdk/spring/azure-spring-boot-test-keyvault/src/test/java/com/microsoft/azure/test/keyvault/KeyVaultIT.java#L136

Related PR: https://github.com/Azure/azure-sdk-for-java/pull/14869

**Comment by chenrujun** [comment]
@lzc-1997-abel

**Comment by saragluna** [comment]
Could we close this issue now? https://github.com/Azure/azure-sdk-for-java/pull/15078
