### ISSUE TITLE
[QUERY] When do you plan on releasing a non-beta 5.2.0?

### ISSUE THREAD

**Issue by stevebasher** [Azure/azure-sdk-for-java#14902]
**Query/Question**
When can I expect a non-beta release of 5.2.0?

We are currently blocked on critical work due to the memory leak raised here: https://github.com/Azure/azure-sdk-for-java/issues/13775

A fix was released within 5.2.0-beta.2 and we have confirmed it works, but we require a standard release before we can upgrade our dependency within production and unblock ourselves.

Thanks for resolving the original issue once again!

Kind Regards,
Steve

**Comment by conniey** [comment]
Hey!

This is going to be GA'd in our September release. 

I hope this helps,
Connie

**Comment by stevebasher** [comment]
Ok great, thanks :)
