### ISSUE TITLE
Add mock support for the SDK users

### ISSUE THREAD

**Issue by kyle-wang-sd** [Azure/azure-sdk-for-java#1490]
When using Azure SDK for Java to do development, it's hard to write unit tests without requests to Azure Environment, like when using the virtual machines, I would like to mock some vms, but I cann't. 

Thanks,
Kyle.

**Comment by martinsawicki** [comment]
one thought is that since most of the types that user code interacts with in the SDK are interfaces (e.g. VirtualMachine) API, one could just implement that interface on their own... No special plans otherwise.

**Comment by wendingp** [comment]
Any updates on this?
