### ISSUE TITLE
ServiceBus - Management client NPE on queue description

### ISSUE THREAD

**Issue by andrewstevenson** [Azure/azure-sdk-for-java#14903]
Queue created in ServiceBus via the portal.

Call to managementClient.getQueueExists(queueName) results in an NPE. No description is set.

[31m  java.lang.NullPointerException: 'description' cannot be null.[0m
[31m  at java.util.Objects.requireNonNull(Objects.java:228)[0m
[31m  at com.azure.messaging.servicebus.implementation.EntityHelper.toModel(EntityHelper.java:172)[0m
[31m  at com.azure.messaging.servicebus.ServiceBusManagementAsyncClient.deserializeQueue(ServiceBusManagementAsyncClient.java:1739)[0m
[31m  at com.azure.messaging.servicebus.ServiceBusManagementAsyncClient.lambda$getQueueWithResponse$36(ServiceBusManagementAsyncClient.java:1326)[0m
[31m  at reactor.core.publisher.FluxHandle$HandleSubscriber.onNext(FluxHandle.java:96)[0m
[31m  at reactor.core.publisher.FluxOnErrorResume$ResumeSubscriber.onNext(FluxOnErrorResume.java:73)[0m
[31m  at reactor.core.publisher.Operators$MonoSubscriber.complete(Operators.java:1782)[0m
[31m  at reactor.core.publisher.MonoFlatMap$FlatMapInner.onNext(MonoFlatMap.java:241)[0m
[31m  at reactor.core.publisher.FluxSwitchIfEmpty$SwitchIfEmptySubscriber.onNext(FluxSwitchIfEmpty.java:67)[0m
[31m  at reactor.core.publisher.Operators$MonoSubscriber.complete(Operators.java:1782)[0m
[31m  ...[0m
[36mRun completed in 29 seconds, 35 milliseconds.[0m

com.azure:azure-messaging-servicebus:7.0.0-beta.5

**Comment by andrewstevenson** [comment]
So if I create a topic called `demo` and call getQueueExists(`demo`) I get the NPE and its the same vice versa.

**Comment by joshfree** [comment]
Thanks for trying out and reporting this code defect in the `Service Bus` beta.5 release, @andrewstevenson.  @hemanttanwar can you please follow up on this issue for the next monthly release?

**Comment by hemanttanwar** [comment]
@andrewstevenson Thank  you for the query. I have tried with "com.azure:azure-messaging-servicebus:7.0.2" version and this problem is no more present. Please use this library version and let us know if you face any issue.

I will close this issue but if  you have further question, please reopen this or create new issue.
