### ISSUE TITLE
Review HttpRequest Body Reading in HttpPipelinePolicies

### ISSUE THREAD

**Issue by alzimmermsft** [Azure/azure-sdk-for-java#14917]
Review `HttpPipelinePolicy` operations on how they consume `HttpRequest` bodies. Particularly, ensure that side-affect operations, such as authorization calculations, don't leave the `ByteBuffer` in a consumed state (where a call to `remaining()` is mutated). In cases where the body buffers need to be read a duplicate of the body buffer should be created and consumed to ensure the body is left in an unmodified state when the `HttpClient` goes to send the request.

**Comment by mssfang** [comment]
Checked all exisiting classes that implements `HttpPipelinePolicy`. All ByteBuffer that used in the request is in the unmodifiable state.

Report: 

Not ByteBuffer read operation Policies:
- AddDatePolicy, AddHeadersFromContextPolicy, AddHeadersPolicy, ArmChallengeAuthenticationPolicy,  AzureKeyCredentialPolicy, AzureSasCredentialPolicy, BearerTokenAuthenticationChallengePolicy,
BearerTokenAuthenticationPolicy,  CookiePolicy, HostPolicy, OpenTelemetryHttpPolicy, PortPolicy, ProtocolPolicy, RecordNetworkCallPolicy, RequestIdPolicy, TimeoutPolicy, UserAgentPolicy

Policies that use the ByteBuffer:
- HttpLoggingPolicy::writeBufferToBodyStream // already duplicate the ByteBuffer.
- RetryPolicy: 
```
  return httpResponse.getBody()
                            .ignoreElements() // since we ignore the elements, duplicate the byteBuffer doesn't needed here.
                            .then(attemptAsync(context, next, originalHttpRequest, tryCount + 1)
                                .delaySubscription(delayDuration));
```
