### ISSUE TITLE
[BUG] azure-storage-blob throws NPE when uploading

### ISSUE THREAD

**Issue by mxmxcz** [Azure/azure-sdk-for-java#14962]
**Describe the bug**
After updating the `azure-storage-blob` dependency in our app from `12.6.1` to `12.7.0` or `12.8.0`, we're getting a NPE when trying to upload a blob. The code remains unchanged and works perfectly fine on `12.6.1`.

***Exception or Stack Trace***
```
│ java.lang.NullPointerException: key                                                                                                                                                                             │
│     at java.base/java.util.Objects.requireNonNull(Objects.java:246)                                                                                                                                             │
│     at reactor.util.context.Context1.<init>(Context1.java:30)                                                                                                                                                   │
│     at reactor.util.context.Context.of(Context.java:159)                                                                                                                                                        │
│     at com.azure.core.util.FluxUtil.toReactorContext(FluxUtil.java:203)                                                                                                                                         │
│     at com.azure.storage.blob.BlobClient.uploadWithResponse(BlobClient.java:219)                                                                                                                                │
│     at com.azure.storage.blob.BlobClient.uploadWithResponse(BlobClient.java:185)                                                                                                                                │
│     at com.azure.storage.blob.BlobClient.upload(BlobClient.java:163)                                                                                                                                            │
│     at com.azure.storage.blob.BlobClient.upload(BlobClient.java:147)
```

**To Reproduce**
Steps to reproduce the behaviour:

1. Create an instance of `BlobContainerClient`
2. Get an instance of `BlobClient` - `containerClient.getBlobClient("blobName")`
3. Upload from a stream of any existing file: `blob.upload(inputStream, length)`

***Code Snippet***
```
File file = FileUtils.getFile("/tmp/file.txt");

try (InputStream stream = FileUtils.openInputStream(file)) {
  BlobServiceClient serviceClient = new BlobServiceClientBuilder()
                                      .endpoint("https://xyz.blob.core.windows.net")
                                      .credential(new StorageSharedKeyCredential("acc", "key"))
                                      .buildClient();

  BlobContainerClient containerClient = serviceClient.getBlobContainerClient("container");

  containerClient
    .getBlobClient("blob.txt")
    .upload(stream,FileUtils.sizeOf(file));
} catch (IOException e) {
  e.printStackTrace();
}
```

**Expected behaviour**
No exception to be thrown and the blob to be uploaded like in previous versions.

**Setup (please complete the following information):**
 - OS: Ubuntu 20.04.1 LTS, 5.4.0-45-generic, x86_64
 - IDE: IntelliJ IDEA 2020.2.1 (Community Edition) Build #IC-202.6948.69 (not IDE specific though)
 - Version of the Library used: 12.8.0

**Additional context**

- Happens also when running in Kubernetes, ie. is not specific to my machine.
- OpenJDK 11.0.8
- Apache Maven 3.6.3

**Information Checklist**
Kindly make sure that you have added all the following information above and check off the required fields otherwise we will treat the issuer as an incomplete report
- [x] Bug Description Added
- [x] Repro Steps Added
- [x] Setup information Added

**Comment by alzimmermsft** [comment]
Thank you for reporting this issue @mxmxcz, it appears that a `null` key value is being passed into a Reactor `Context` object triggering this `NullPointerException` to be thrown. Reviewing the code called in the exception stack trace shows that `null` keys should be getting rejected:

https://github.com/Azure/azure-sdk-for-java/blob/master/sdk/core/azure-core/src/main/java/com/azure/core/util/FluxUtil.java#L305
https://github.com/Azure/azure-sdk-for-java/blob/master/sdk/core/azure-core/src/main/java/com/azure/core/util/Context.java#L146

Do you mind listing additional dependencies included in this code snippet, possibly the output of `mvn dependency:tree`.

CC: @rickle-msft

**Comment by mxmxcz** [comment]
@alzimmermsft Thanks for the reply. I just got back to the issue and I can't reproduce it anymore. There must have been a temporary problem somewhere in there, therefore I am closing the issue.
