### ISSUE TITLE
[QUESTION] Blob Storage Availability?

### ISSUE THREAD

**Issue by dgpoulet** [Azure/azure-sdk-for-java#14978]
When using the Azure Storage BlobClient to write a blob to Azure Storage, once the call returns is that new blob _immediately_ available to other clients for reading or can there be a brief delay before it's available that developers may need to factor in?

This is not a bug, just a clarification request.

OS: Linux
JDK: 11
Azure Storage Blob 12.8.0 (August 2020) release

**Comment by joshfree** [comment]
@gapra-msft could you please assist @dgpoulet with this `Storage` question?

**Comment by rickle-msft** [comment]
@dgpoulet Write operations such as putBlob or commitBlockList are immediately consistent and should be available for read as soon as the service issues a successful response.
