### ISSUE TITLE
[BUG] Downloading of hdinsight-mgmt 1.3.5 via maven + ivy yields invalid zip

### ISSUE THREAD

**Issue by danrubenstein** [Azure/azure-sdk-for-java#14989]
**Describe the bug**

Hello! I am trying to use the Azure SDK for Java to use the hdinsight management library.

I specifically am looking to use version `1.3.5`, as it is the only version, as far as I can tell, with `com.microsoft.azure.management.hdinsight.v2018_06_01_preview.DiskEncryptionProperties`.

I download the sdk via maven + ivy, with the dependency specified as:
```xml
<ivy-module version="2.0" xmlns:m="http://ant.apache.org/ivy/maven"
   xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
   xsi:noNamespaceSchemaLocation="http://ant.apache.org/ivy/schemas/ivy.xsd">
    <info organisation="com.myorganization" module="application"/>
    <dependencies defaultconf="default->default">
        <!-- ... Other dependencies ....-->
        <dependency org="com.microsoft.azure.hdinsight.v2018_06_01_preview" name="azure-mgmt-hdinsight" rev="1.3.5"/>
    </dependencies>
</ivy-module>
```

When compiling code that references this dependency, I run into the following:
```shell
compile-base:
     [echo] *** Compiling application ***
    [javac] Compiling 178 source files to /path/to/application/build/classes
    [javac] error: error reading /path/to/application/lib/azure-mgmt-hdinsight-1.3.5.jar; zip END header not found

BUILD FAILED
/path/to/application/build.xml:115: Compile failed; see the compiler error output for details.
```

Additionally, running `unzip` produces the following:

```shell
% unzip -t lib/azure-mgmt-hdinsight-1.3.5.jar
Archive:  lib/azure-mgmt-hdinsight-1.3.5.jar
  End-of-central-directory signature not found.  Either this file is not
  a zipfile, or it constitutes one disk of a multi-part archive.  In the
  latter case the central directory and zipfile comment will be found on
  the last disk(s) of this archive.
unzip:  cannot find zipfile directory in one of lib/azure-mgmt-hdinsight-1.3.5.jar or
        lib/azure-mgmt-hdinsight-1.3.5.jar.zip, and cannot find lib/azure-mgmt-hdinsight-1.3.5.jar.ZIP, period.
%
```

I do not experience similar issues with 1.3.4, but it does not have the feature that I am looking for.

***Exception or Stack Trace***

Copied from description:

```
compile-base:
     [echo] *** Compiling application ***
    [javac] Compiling 178 source files to /path/to/application/build/classes
    [javac] error: error reading /path/to/application/lib/azure-mgmt-hdinsight-1.3.5.jar; zip END header not found

BUILD FAILED
/path/to/application/build.xml:115: Compile failed; see the compiler error output for details.
```

**To Reproduce**

A minimal reproduction (see above for full context)
1. download the 1.3.5 JAR from https://mvnrepository.com/artifact/com.microsoft.azure.hdinsight.v2018_06_01_preview/azure-mgmt-hdinsight/1.3.5
1. run `unzip -t` on the download
1. see error from `unzip`

***Code Snippet***

ivy.xml file copied from above:

```xml
<ivy-module version="2.0" xmlns:m="http://ant.apache.org/ivy/maven"
   xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
   xsi:noNamespaceSchemaLocation="http://ant.apache.org/ivy/schemas/ivy.xsd">
    <info organisation="com.myorganization" module="application"/>
    <dependencies defaultconf="default->default">
        <!-- ... Other dependencies ....-->
        <dependency org="com.microsoft.azure.hdinsight.v2018_06_01_preview" name="azure-mgmt-hdinsight" rev="1.3.5"/>
    </dependencies>
</ivy-module>
```

**Expected behavior**

I expect a valid zip from the repository.

**Screenshots**

**Setup (please complete the following information):**
 - OS: [e.g. iOS] MacOSX Catalina (10.15.6)
 - IDE : [e.g. IntelliJ] IntelliJ
 - Version of the Library used: 1.3.5

**Additional context**

**Information Checklist**
Kindly make sure that you have added all the following information above and checkoff the required fields otherwise we will treat the issuer as an incomplete report
- [x] Bug Description Added
- [x] Repro Steps Added
- [x] Setup information Added

**Comment by joshfree** [comment]
Thanks for providing the thorough details in this bug report @danrubenstein.  Someone from the `Mgmt` team will follow up with you shortly on this.

/cc @yungezz

**Comment by aim-for-better** [comment]
Hi @yungezz  I am from HDInsight service tooling team, could you please help investigate the zip issue? If you need any help please feel free to ping me.

**Comment by yungezz** [comment]
hi @xccc-msft could you pls help on this? thanks

**Comment by xccc-msft** [comment]
@danrubenstein Thanks for reporting this. It looks some issue happened during the release process. We just release a new version of [1.3.6](https://search.maven.org/artifact/com.microsoft.azure.hdinsight.v2018_06_01_preview/azure-mgmt-hdinsight/1.3.6/jar) to fix this. Please check. Thanks.

**Comment by aim-for-better** [comment]
Java SDK team has fixed this.

**Comment by danrubenstein** [comment]
All set here - thanks you all for the rapid turnaround!
