### ISSUE TITLE
SB Track2 - Verify - Batch Size calculated with correct overhead bytes - After adding AMQP Annotated Message

### ISSUE THREAD

**Issue by hemanttanwar** [Azure/azure-sdk-for-java#14980]
Since we have added `AmqpAnnotatedMessage`, the following lines of code does calculate overhead in `ServiceBusMessageBatch.java`. 

Ensure that after adding `AmqpAnnotatedMessage`,  this calculation is still correct.

We can consult from  service team and how dot net is doing.

        final org.apache.qpid.proton.message.Message amqpMessage = serializer.serialize(serviceBusMessage);
        int eventSize = amqpMessage.encode(this.eventBytes, 0, maxMessageSize); // actual encoded bytes size
        eventSize += 16; // data section overhead

https://github.com/Azure/azure-sdk-for-java/blob/master/sdk/servicebus/azure-messaging-servicebus/src/main/java/com/azure/messaging/servicebus/ServiceBusMessageBatch.java#L156 

Reference : https://github.com/Azure/azure-sdk-for-java/pull/14848#discussion_r485287426

**Comment by ramya-rao-a** [comment]
@YijunXieMS, Lets run some tests to see if creating a message with details in annotated message needs any extra calculation when adding to the batch.

**Comment by YijunXieMS** [comment]
Method `private int getSize(final ServiceBusMessage serviceBusMessage, final boolean isFirst)` already includes the extra size for the annotated message. `serviceBusMessage` is converted to protoj message incluing the annotated message.
So I don't think extra calculation is needed.

But there is huge difference of overhead estimation between Java and Python. Python's overhead estimation is 5 bytes per message if the message size <256 and 8 bytes if >=256. No other overheads. Adam (@yunhaoling) did a lot of test to get these two values.
Java's overhead estimation is:
- 1k for every 64k of the max size limit. If the frame size is 256k, this overhead will be 4k.
- plus an empty message's size for every batch.
- plus 16 bytes for every message.

I tried with Python's overhead 5 and 8 / message with Java. It works. So Java may not need that large overhead. But what I know is this is from track 1. So we may need to consult service team.

**Comment by ki1729** [comment]
Given that python is only adding 8bytes overhead, we should be good here.
