### ISSUE TITLE
com.microsoft.azure.management.sql.implementation.SqlServerManager.authenticate fails to build RestClient

### ISSUE THREAD

**Issue by romanjsonar** [Azure/azure-sdk-for-java#1500]
com.microsoft.azure.management.sql.implementation.SqlServerManager.authenticate() needs to set SerializerAdapter and ResponseFactory on RestClient.Builder before invoking build().

Reason: RestClient.Builder.build() throws an exception: "Please set response builder factory"

Expected behaviour: SqlServerManager.authenticate() returns normally, without an exception.

**Comment by martinsawicki** [comment]
great find, actually .authenticate() got broken across the board. Fixed with https://github.com/Azure/azure-sdk-for-java/pull/1602/commits/1dd456bb354b1cafca3962850ab74d47aa56f15a
