### ISSUE TITLE
[BUG] Cosmos | When a replica is moved or restarted requests to that replica should be retried on a different replica

### ISSUE THREAD

**Issue by David-Noble-at-work** [Azure/azure-sdk-for-java#15003]
**Description**

When a replica is moved or restarted by a management operation such as rolling upgrade, requests to that replica may linger in the Direct TCP transport client request queue. Under load the number of such requests may grow until the replica comes back on line.

Requests should never linger in the Direct TCP transport client's queue. Rather, all pending requests should be retried on a different replica.

***Exception or Stack Trace***
When this error occurs you will see a sequence of events in the logs:

- GoneException with sub-status code zero followed by
- GoneException with cause IOException (e.g., ClosedChannelException or ConnectTimeoutException), and then
- after a long pause, a ForbiddenException indicating that the session token used to complete a request has expired.

**To Reproduce**
Clone and run the app at: https://github.com/mbhaskar/cosmoslongtest.

**Expected behavior**
The RntbdTransportClient should recognize and flush the request queue when it is determined that the service is currently unavailable. A retry should be attempted in the consistency layer and the client-side address cache should be updated.

**Status**
We are actively working on a fix to this problem. A PR that adds a new feature (the `RntbdConnectionStateListener`) that is meant to address this issue is in flight. See https://github.com/Azure/azure-sdk-for-java/pull/14697.

**Comment by kushagraThapar** [comment]
This issue has been fixed on v4.5.0 release, here are the release notes : https://github.com/Azure/azure-sdk-for-java/blob/master/sdk/cosmos/azure-cosmos/CHANGELOG.md#450-2020-09-16
