### ISSUE TITLE
[BUG] - ServiceBus - Exception throw when calling peek on empty queue

### ISSUE THREAD

**Issue by andrewstevenson** [Azure/azure-sdk-for-java#15034]
Calling `peekMessages` on an empty queue results in an exception. Expected behaviour was to return an empty iterable.

[31m  com.azure.core.amqp.exception.AmqpException: errorCondition[com.microsoft:message-not-found]. description[null], errorContext[NAMESPACE: l.servicebus.windows.net, PATH: /$management, REFERENCE_ID: -mgmt:receiver, LINK_CREDIT: 0][0m
[31m  at com.azure.core.amqp.implementation.ExceptionUtil.toException(ExceptionUtil.java:42)[0m
[31m  at com.azure.messaging.servicebus.implementation.MessageUtils.toException(MessageUtils.java:225)[0m
[31m  at com.azure.messaging.servicebus.implementation.ManagementChannel.lambda$sendWithVerify$16(ManagementChannel.java:454)[0m
[31m  at reactor.core.publisher.FluxHandleFuseable$HandleFuseableSubscriber.onNext(FluxHandleFuseable.java:163)[0m
[31m  at reactor.core.publisher.Operators$MonoSubscriber.complete(Operators.java:1782)[0m
[31m  at reactor.core.publisher.MonoIgnoreThen$ThenAcceptInner.onNext(MonoIgnoreThen.java:296)[0m
[31m  at reactor.core.publisher.MonoCreate$DefaultMonoSink.success(MonoCreate.java:156)[0m
[31m  at com.azure.core.amqp.implementation.RequestResponseChannel.settleMessage(RequestResponseChannel.java:300)[0m
[31m  at com.azure.core.amqp.implementation.RequestResponseChannel.lambda$new$0(RequestResponseChannel.java:135)[0m
[31m  at reactor.core.publisher.LambdaSubscriber.onNext(LambdaSubscriber.java:160)[0m

**Version:**
com.azure:azure-messaging-servicebus:7.0.0-beta.5

**Comment by andrewstevenson** [comment]
same for topics, I have to check if the subscription or queue has messages before calling  :-(

**Comment by joshfree** [comment]
@conniey could you please follow up on this?  @andrewstevenson thanks for filing the github issue and providing feedback on `Service Bus` beta releases.

**Comment by conniey** [comment]
@andrewstevenson Thanks for reporting this issue! Definitely a test case we missed.
