### ISSUE TITLE
Using container SAS to store eventhub checkpoints in storage containers

### ISSUE THREAD

**Issue by ChaitanyaKandala** [Azure/azure-sdk-for-java#15036]
**Query/Question**
I am looking for a way to use ONLY a container SAS to create a BlobContainerClient/BlobContainerAsyncClient and send it to EventProcessorClientBuilder class. I dont/will not have access to get the entire storage account connection string.
How can I achieve this with just container SAS(Assuming that the container SAS has read, list and write permissions for the container in question)

I tried creating a connection string out of the SAS token and passing it to the connection string.
`

    private static final String STORAGE_CONNECTION_STRING = "BlobEndpoint=https://storageaccount1.blob.core.windows.net;\n" +
          "SharedAccessSignature=sv=2019-02-02&st=2020-09-10T14%3A24%3A30Z&se=2020-09-10T14%3A51%3A00Z&sr=c&sp=rcl&sig=OyO3onMBeghbbr7e8%3D";
    private static final String SAS_TOKEN_STRING = "https://storageaccount1.blob.core.windows.net/edev-export?sv=2019-02-02&st=2020-09-10T14%3A24%3A30Z&se=2022-09-10T14%3A51%3A00Z&sr=c&sp=rcl&sig=OyO3onMBeghbbr7e8%3D";
   

        BlobContainerAsyncClient blobContainerAsyncClient = new BlobContainerClientBuilder()
            .connectionString(STORAGE_CONNECTION_STRING)
            .containerName("edev-export")
            .sasToken(SAS_TOKEN_STRING)
            .httpLogOptions(new HttpLogOptions().setLogLevel(HttpLogDetailLevel.BODY_AND_HEADERS))
            .buildAsyncClient();

        EventProcessorClientBuilder eventProcessorClientBuilder = new EventProcessorClientBuilder()
            .connectionString(EH_CONNECTION_STRING)
            .consumerGroup("$Default")
            .processEvent(PARTITION_PROCESSOR)
            .processError(ERROR_HANDLER)
            .checkpointStore(new BlobCheckpointStore(blobContainerAsyncClient));

        EventProcessorClient eventProcessorClient = eventProcessorClientBuilder.buildEventProcessorClient();

`
but I keep getting errors for Authentication failed on com.azure.storage.blob.models.BlobStorageException

Sample I used is based of 
https://github.com/Azure/azure-sdk-for-java/blob/master/sdk/eventhubs/azure-messaging-eventhubs-checkpointstore-blob/src/samples/java/com/azure/messaging/eventhubs/checkpointstore/blob/EventProcessorBlobCheckpointStoreSample.java

***Why is this not a Bug or a feature Request?***
There are no samples which explain using just SAS. Every example shows how I can use a storage account and a SAS or just storage account. 
While I can access the container and perform operations with just a SAS key, why cannot I use the same SAS for checkpointing?

**Setup (please complete the following information if applicable):**
 - OS: Ubuntu 18
 - IDE : IntelliJ
 - Version of the Library used: azure-messaging-eventhubs-checkpointstore-blob 1.1.2
 
 **Information Checklist**
 Kindly make sure that you have added all the following information above and checkoff the required fields otherwise we will treat the issuer as an incomplete report
- [x] Query Added
- [x] Setup information Added

**Comment by alzimmermsft** [comment]
Hi @ChaitanyaKandala, thank you for raising this question. When setting a SAS token in `BlobContainerClientBuilder` you'll want to pass only the SAS URL query parameters, both with or without the leading `?` will work. From your example above you'll want to use `sv=2019-02-02&st=2020-09-10T14%3A24%3A30Z&se=2022-09-10T14%3A51%3A00Z&sr=c&sp=rcl&sig=****` as the `SAS_TOKEN_STRING`.

**Comment by ChaitanyaKandala** [comment]
Oh wow!! Didn't realize that. I just tried it appears to be working. I'll test it more.
Thank you very much @alzimmermsft !!!

**Comment by alzimmermsft** [comment]
I've filed this issue as a follow-up to update documentation to better explain the expected `String sasToken` value. https://github.com/Azure/azure-sdk-for-java/issues/15040

**Comment by alzimmermsft** [comment]
@ChaitanyaKandala, for now I'm going to close this issue as resolved. If you run into any more issues with SAS tokens please feel free to re-open this.
