### ISSUE TITLE
Revise the logic of marking types as Inner during generation.

### ISSUE THREAD

**Issue by hovsepm** [Azure/azure-sdk-for-java#1505]
proposal. Mark as Inner only types that are child of any other type.

**Comment by hovsepm** [comment]
this PR marks Inner only types that are derived from Resource and SubResource https://github.com/Azure/autorest/pull/1892

**Comment by martinsawicki** [comment]
Yes, this is based on our quick (and non-exhaustive) observation that it seems the things we really want to be Inners all derive from something -- usually `Resource` or `SubResource`. And the models that do not derive from something that we've looked at would make sense as "data structures" that do not need to be wrapped, and do not need to be in the `implementation` package. 
But that's just a hunch so far based on a quick look across a few services. It'd be worthwhile, when we have time, to try this as an experiment and see if the generated models match our expectations better.
