### ISSUE TITLE
[QUERY] Event Hubs needs life cycle listener to measure performance

### ISSUE THREAD

**Issue by lu-cheng** [Azure/azure-sdk-for-java#15077]
EventHubs needs life cycle listener, status: initialization is complete, start sending, end sending. Used to confirm when messages can be sent and performance monitoring.

>
>we have prospective Event Hubs customer with a very latency-sensitive use-case and they are using Spring. 
>
>To  check things out in parallel while they are trying Event Hubs with the Kafka binder, I’ve been trying to use the Spring Cloud Binder for Event Hubs and track the end-to-end latency. I’ve attached the app. I’m sure it looks quite clunky to Spring practitioners because I don’t know how to make the start of the sender sequence dependent on the listener being fully set up, so I have a sleep() there to deal with that.
>
>Just starting up the listener on an Event Hub with 4 partitions takes up more than a minute (I runs this ~12ms roundtrip latency away from West Europe) and it’s not effect of logging. An end-to-end passthrough of a single message takes ~1700ms where an equivalent end-to-end operation with an Azure C# client (also attached) takes less than 30ms end-to-end on average.
>
>I attached the output of one run. Start is at 13:50:17 and the listener reports being attached to all partitions at 13:51:21. The end-to-end timings are at the bottom.
>
>I urgently need to understand where all that extra time goes, both for startup and passthrough latency. I would expect for the listener to report ready after 5s max and for end-to-end latency to be more competitive (the C# is not using the Event Processor Host, but I expect that to be nearly as quick as the plain partition receiver) . I have also tried checkpointing set to manual and then  not checkpointing, at all, but that did not make a difference.

**Comment by joshfree** [comment]
@conniey @mikeharder could you please assist?

**Comment by lu-cheng** [comment]
I created a test project about eventhub, The test uses resources (VM, Eventhub) in the same region，and the round trip time through eventhub is 100-300 msec. Is this performance a normal expectation? I have a customer here and expect this result to be 50 msec. Can it be improved?

If my test code is incorrect, please help me correct it.
Repository: https://github.com/lu-cheng/eventhub-test

**Comment by mikeharder** [comment]
@lu-cheng: I am not sure offhand what is expected for round-trip latency, but do you know why the customer is expecting 50ms?  Is there a baseline which does deliver this performance, like a previous version of the Java EventHubs SDK, or the EventHubs SDK in a different language like .NET?

**Comment by YijunXieMS** [comment]
@lu-cheng Could you try not to update checkpoint (remove "eventContext.updateCheckpoint();"), which has an http round trip to the blob service.
BTW, you have a full connection string in the source code.

**Comment by lu-cheng** [comment]
@YijunXieMS The consumption of "EventContext.updateCheckpoint();" is not counted in time.

**Comment by lu-cheng** [comment]
@YijunXieMS About full connection string in the source code, I will delete related resources.

**Comment by samuelkoppes** [comment]
We are investigating this issue and will report back with an update by 11/4/2020.

**Comment by srnagar** [comment]
@lu-cheng Do you still have any questions regarding this issue? It looks like the code sample you shared above is still updating the checkpoint which is going to add additional latency to roundtrip. 
```
T1 -> receive event 1 -> measure latency (current time - send time) -> update checkpoint -> T2 -> receive event 2 -> measure latency (current time - send time) -> update checkpoint -> T3...
```

So, the `processEvent` handler for the next event is called only after the checkpoint is updated for the previous event. This adds to the roundtrip time measured for the next event.

**Comment by lu-cheng** [comment]
@srnagar The ‘eventContext.updateCheckpoint();’ logically does not interfere with timing. This is a customer's mail issue, and there is no problem on my side.

**Comment by srnagar** [comment]
@lu-cheng are you looking at the time for the first event only or for all events? It would be good to include what scenarios you are testing and expected latencies and the latencies you are noticing.

**Comment by srnagar** [comment]
@lu-cheng do you have any updates on this?

**Comment by conniey** [comment]
This looks related to the feature about adding performance metrics: #19391
