### ISSUE TITLE
[BUG] Multiple errors from PartitionBasedLoadBalancer after reconnection

### ISSUE THREAD

**Issue by wedmeed** [Azure/azure-sdk-for-java#15100]
**Describe the bug**
When I use EventProcessorClient for consuming from eventhubs, I need to stop and start processors on different instances (not because of EH but because of underlying resources). After restarting EventProcessorClient occasionally (not on every restart) clients start to report errors as below. The errors are repeating every minute and doesn't go out on new restarts.

An important note: I have an application that is running in multiple instances. All these instances are reusing the same consumer group (that shouldn't be a problem in accordance with the description in EventProcessorClient's javaDoc). Each instance is connecting to multiple topics (eventhubs) under the same EventHubs account.

***Exception or Stack Trace***
```
2020-09-10 18:01:34.853  WARN 68388 --- [       single-1] c.a.c.a.i.handler.ConnectionHandler      : onTransportError hostname[xxx-ehub.servicebus.windows.net:5671], connectionId[MF_9ff502_1599745296997], error[org.apache.qpid.proton.engine.TransportException: connection aborted]
2020-09-10 18:01:34.854 ERROR 68388 --- [       single-1] c.a.c.a.i.ReactorConnection              : connectionId[MF_9ff502_1599745296997] Error occurred in connection handler.
2020-09-10 18:01:36.413  WARN 68388 --- [     parallel-4] c.a.m.e.PartitionBasedLoadBalancer       : Load balancing for event processor failed - Did not observe any item or terminal signal within 60000ms in 'flatMapMany' (and no fallback has been configured)
```

**To Reproduce**
1. create а processor clients for 3-5 event hubs topics in the same account simultaneously from multiple instances:
```
EventProcessorClientBuilder eventProcessorClientBuilder = new EventProcessorClientBuilder()
                    .connectionString(
                            properties.getConnectionString(),
                            properties.getConsumers().get(hubName).getDestination())
                    .consumerGroup(consumer.getGroup())
                    .processEvent(this::onReceive)
                    .processError(this::onError)
                    .checkpointStore(new BlobCheckpointStore(blobContainerAsyncClient))
                    .processPartitionInitialization(this::onInitialize)
                    .processPartitionClose(this::onClose)
                    .trackLastEnqueuedEventProperties(true)
                    .initialPartitionEventPosition(positionMap);
```
2. after 5 minutes stop these clients:
```
                internalClient.stop();
```
3. after stopping create and start new clients as in step 1.
4. after 10-60 minutes you will see many errors as described above

**Expected behavior**
Recreating of clients doesn't produce errors. Newly created clients are working without errors.

**Setup (please complete the following information):**
 - OS: MacOS 10.14
 - IDE : IntelliJ IDEA 2020
 - Version of the Library used:
implementation 'com.azure:azure-messaging-eventhubs:5.1.2'
implementation 'com.azure:azure-messaging-eventhubs-checkpointstore-blob:1.1.2'

**Comment by joshfree** [comment]
Thanks @wedmeed for reporting this reliability issue.  @srnagar can you please investigate?

**Comment by YijunXieMS** [comment]
@wedmeed While I'm looking into the problem, one question to ask. Do you reuse `blobContainerAsyncClient` for either multiple clients or one client with start/stop/start...?

**Comment by wedmeed** [comment]
@YijunXieMS, everything is new at every time I start the processor:
- BlobContainerAsyncClient
- EventProcessorClient

**Comment by samuelkoppes** [comment]
We are investigating this issue and will report back with an update by 11/4/2020.

**Comment by YijunXieMS** [comment]
After upgrading to 5.2.0 and above, the logs have some transient connection error logged but event receiving has no problem and the event processor can recover from these transient errors.

**Comment by srnagar** [comment]
The latest version of Event Hubs librar `5.3.1` resolves this issue.
