### ISSUE TITLE
[AppConfiguration] Expose com.azure.core.util.ClientOptions via Builder and implement applicationId in UserAgent for telemetry

### ISSUE THREAD

**Issue by hemanttanwar** [Azure/azure-sdk-for-java#15113]
Expose com.azure.core.util.ClientOptions via Builder and implement applicationId in UserAgent for telemetry

- [x] Expose com.azure.core.util.ClientOptions via Builder and 
- [x] Take the Headers set by user in ClientOptions and set them on Http Request. We would have to make sure whatever the user passed in as Header, is not overwritten by the policies. So we should just add an AddHeadersPolicy after all other policies.
- [x] Implement applicationId in UserAgent for telemetry 
- [x] Unit Test
Example PR :  https://github.com/Azure/azure-sdk-for-java/pull/13697/files#diff-860f082a6593b9a09fa1a4d4fd0b5cf7R105

Look epic for detail : https://github.com/Azure/azure-sdk-for-java/issues/15107

**Comment by mssfang** [comment]
merge the changes in this PR. https://github.com/Azure/azure-sdk-for-java/pull/20182
