### ISSUE TITLE
[Storage] Expose com.azure.core.util.ClientOptions via Builder and implement applicationId in UserAgent for telemetry

### ISSUE THREAD

**Issue by hemanttanwar** [Azure/azure-sdk-for-java#15118]
Expose com.azure.core.util.ClientOptions via Builder and implement applicationId in UserAgent for telemetry

- [ ] Expose com.azure.core.util.ClientOptions via Builder and 
- [ ] Take the Headers set by user in ClientOptions and set them on Http Request. We would have to make sure whatever the user passed in as Header, is not overwritten by the policies. So we should just add an AddHeadersPolicy after all other policies.
- [ ] Implement applicationId in UserAgent for telemetry 
- [ ] Unit Test

Look into Epic for more detail:  https://github.com/Azure/azure-sdk-for-java/issues/15107

**Comment by hemanttanwar** [comment]
@gapra-msft @rickle-msft Can one of you look into this.

**Comment by gapra-msft** [comment]
Hi @hemanttanwar Is this different from what you are suggesting? https://github.com/Azure/azure-sdk-for-java/pull/14916

**Comment by hemanttanwar** [comment]
> Hi @hemanttanwar Is this different from what you are suggesting? #14916

@gapra-msft  This got decided in last 2 weeks. I understand that this is changing mid-way of your PR. 
And I commented on this PR about it just now. 
https://github.com/Azure/azure-sdk-for-java/pull/14916/files#r487260784
