### ISSUE TITLE
[KeyVault] Expose com.azure.core.util.ClientOptions via Builder and implement applicationId in UserAgent for telemetry

### ISSUE THREAD

**Issue by hemanttanwar** [Azure/azure-sdk-for-java#15117]
Expose com.azure.core.util.ClientOptions via Builder and implement applicationId in UserAgent for telemetry

- [x] Expose com.azure.core.util.ClientOptions via Builder and 
- [x] Implement applicationId in UserAgent for telemetry 
- [ ] Unit Test

**Comment by g2vinay** [comment]
@vcolin7 can you look into this feature req ?

**Comment by vcolin7** [comment]
Sure thing :)

**Comment by vcolin7** [comment]
Unit tests will be added in a later release.
