### ISSUE TITLE
Just a suggestion, please write a document to illustrate which api-version the sdk use for each resource provider

### ISSUE THREAD

**Issue by chenrui1988** [Azure/azure-sdk-for-java#1516]
please write a document to illustrate which api-version the sdk use for each resource provider, 
like Microsoft.Computer VirtualMachines  api-version 2016-04-30-preview

We need these messages. because the updates in china azure is more slow than global azure. some api-versions is not yet on-line, like VirtualMachines  api-version 2016-04-30-preview. So we can't use beta5 in china azure. if we know which api-version are used in sdk. Choose which version of SDK will become very simple for us.

**Comment by martinsawicki** [comment]
documented in release notes, for example: https://github.com/Azure/azure-sdk-for-java/releases/tag/v1.3.0
