### ISSUE TITLE
[BUG] Exception is thrown when uploading file to ADLS Gen 2 account

### ISSUE THREAD

**Issue by yangchengs** [Azure/azure-sdk-for-java#15171]
**Describe the bug**
This is a bug found by our customer.
Sample code in Microsoft document
https://docs.microsoft.com/en-us/azure/storage/blobs/data-lake-storage-directory-file-acl-java

static public void UploadFile(DataLakeFileSystemClient fileSystemClient) 
    throws FileNotFoundException{
        
    DataLakeDirectoryClient directoryClient =
        fileSystemClient.getDirectoryClient("my-directory");

    DataLakeFileClient fileClient = directoryClient.createFile("uploaded-file.txt");

    File file = new File("C:\\mytestfile.txt");

    InputStream targetStream = new FileInputStream(file);

    long fileSize = file.length();

    fileClient.append(targetStream, 0, fileSize);

    fileClient.flush(fileSize);
}

The line 

fileClient.append throws an exception mark/reset not supported.

***Exception or Stack Trace***
Add the exception log and stack trace if available

**To Reproduce**
Code file:

https://github.com/Azure/azure-sdk-for-java/blob/master/sdk/storage/azure-storage-common/src/main/java/com/azure/storage/common/Utility.java

Run the sample code with azure-sdk-for-java version 12.2.0
Note that this is regression because version 12.1.1 does not have this problem.

The root cause is the class com.azure.storage.common.Utility version 12.8.0. FileInputStream does not support reset.
com.azure.common.Utility version 12.6.1 does not have this try-catch block.
            try {
                data.reset();
            } catch (IOException e) {
                throw LOGGER.logExceptionAsError(new RuntimeException(e));
            }

azure-sdk-for-java version 12.2.0 depends on com.azure.storage.common version 12.8.0
azure-sdk-for-java version 12.1.1 depends on com.azure.storage.common version 12.6.1

***Code Snippet***

static public void UploadFile(DataLakeFileSystemClient fileSystemClient) 
    throws FileNotFoundException{
        
    DataLakeDirectoryClient directoryClient =
        fileSystemClient.getDirectoryClient("my-directory");

    DataLakeFileClient fileClient = directoryClient.createFile("uploaded-file.txt");

    File file = new File("C:\\mytestfile.txt");

    InputStream targetStream = new FileInputStream(file);

    long fileSize = file.length();

    fileClient.append(targetStream, 0, fileSize);

    fileClient.flush(fileSize);
}

**Expected behavior**

**Screenshots**

**Setup (please complete the following information):**
 - IDE : [e.g. IntelliJ]
 - Version of the Library used

**Additional context**

**Information Checklist**
Kindly make sure that you have added all the following information above and checkoff the required fields otherwise we will treat the issuer as an incomplete report
- [x] Bug Description Added
- [x] Repro Steps Added
- [ ] Setup information Added

**Comment by gapra-msft** [comment]
Hi @yangchengs 

Thank you for reporting this issue. This looks like its a docs issue. The upload method was modified to fix a bug where it would not be able to support retries properly when a non-resettable InputStream was passed in.

My suggestion would be to modify the code so that an InputStream that supports mark/reset is used. We can file a bug in the docs repo to get the upload method docs updated. 

Sorry for any inconvenience.

**Comment by yangchengs** [comment]
> Hi @yangchengs
> 
> Thank you for reporting this issue. This looks like its a docs issue. The upload method was modified to fix a bug where it would not be able to support retries properly when a non-resettable InputStream was passed in.
> 
> My suggestion would be to modify the code so that an InputStream that supports mark/reset is used. We can file a bug in the docs repo to get the upload method docs updated.
> 
> Sorry for any inconvenience.

I have suggested the cx to use BufferedInputStream to wrap the FileInputStream, please confirm that this is correct.

InputStream targetStream = new BufferedInputStream(new FileInputStream(file));

**Comment by gapra-msft** [comment]
Yes that should work. One thing to be careful about is using a large enough buffer if that is settable.

**Comment by gapra-msft** [comment]
Hi @yangchengs Since you've created an issue for the docs to be fixed, can we close this issue?
