### ISSUE TITLE
[BUG] Can't send events with azure-eventgrid:1.4.0-beta.1

### ISSUE THREAD

**Issue by Sarah-Aly** [Azure/azure-sdk-for-java#15176]
**Describe the bug**
Trying the new Event Grid SDK to send simple events to an Event Grid topic (Event Grid schema), it fails with 404 stating topic is not found.

***Exception or Stack Trace***
>Exception in thread "main" com.microsoft.azure.CloudException: Status code 404, {
    "error": {
        "code": "NotFound",
        "message": "No HTTP resource was found that matches the request URI '&lt;EVENT-GRID-TOPIC-ENDPOINT&gt;?api-version=2018-01-01'. Report '7e35aee8-8de7-452f-9b74-a8e2385a46a7:9/14/2020 5:07:37 AM (UTC)' to our forums for assistance or raise a support ticket.",
        "details": [{
            "code": "ResourceNotFound",
            "message": "No HTTP resource was found that matches the request URI '&lt;EVENT-GRID-TOPIC-ENDPOINT&gt;?api-version=2018-01-01'. Report '7e35aee8-8de7-452f-9b74-a8e2385a46a7:9/14/2020 5:07:37 AM (UTC)' to our forums for assistance or raise a support ticket."
    }]
  }

**To Reproduce**
- Create Event Grid topic with Event Grid schema
- Get endpoint of Event Grid topic `az eventgrid topic show --name $topicname -g $resourcegroupname --query "endpoint" --output tsv`
- Get SAS key of Event Grid topic `az eventgrid topic key list --name $topicname -g $resourcegroupname --query "key1" --output tsv`
- Use endpoint & key in client code to send simple events

***Code Snippet***
```java
static String endpoint = "<EVENT-GRID-TOPIC-ENDPOINT>";
static ServiceClientCredentials key = new TopicCredentials("<AEG-SAS-KEY>");
...
EventGridClient egPublisher = new EventGridClientImpl(key);
egPublisher.publishEvents(endpoint, getEventsList());

```

**Expected behavior**
Events to be send successfully to event grid topic.

**Setup (please complete the following information):**
 - IDE : IntelliJ
 - com.microsoft.azure:azure-eventgrid:1.4.0-beta.1

**Comment by joshfree** [comment]
Thanks for sharing feedback on the `Event Grid` preview release, @Sarah-Aly.  Please note that the beta above has been superseded by a much newer release, https://mvnrepository.com/artifact/com.azure/azure-messaging-eventgrid/2.0.0-beta.1 

@YijunXieMS can you work with @conniey to update the old  '**com.microsoft.azure**:azure-eventgrid' have a relocation message to point users to '**com.azure**:azure-messaging-eventgrid'
