### ISSUE TITLE
how can i get the list of volumes from sdk

### ISSUE THREAD

**Issue by shalir** [Azure/azure-sdk-for-java#1517]
hello everyone, i want to get a list of volume, but i did not find a api in this sdk. is there a way to list the volumes? does anyone know it? thinks
the sdk version i used like this:
```xml
<dependency>
        <groupId>com.microsoft.azure</groupId>
        <artifactId>azure</artifactId>
        <version>1.0.0-beta3</version>
</dependency>
```

**Comment by anuchandy** [comment]
are you looking for retrieving disks attached to a virtual machine ?

**Comment by shalir** [comment]
@anuchandy no, i want to get a list of my volumes under my account, which is not to attached to a virtual machine. thinks

**Comment by anuchandy** [comment]
OK, the managed disk instance has a boolean property `isAttachedToVirtualMachine`, you can list all the disks in your subscription using `Disks.list()` and can use this flag to filter out non-attached disks. 

```java
        PagedList<Disk> disks = computeManager.disks().list();
        for (Disk disk : disks) {
            if (!disk.isAttachedToVirtualMachine()) {
                // 
            }
        }
```

**Comment by shalir** [comment]
thinks for your help @anuchandy , i use Azure China, and it did not support beta5 yet, in beta3 there haven't disks() method, i have confirm whit  chinese engineer, maybe i need to waiting for beta5 in China Azure. haha
