### ISSUE TITLE
Failed to create a Network Interface with no much information except a CloudException

### ISSUE THREAD

**Issue by buamod** [Azure/azure-sdk-for-java#1519]
I used to have this piece of code and it used to work for a while ..suddenly I am having an issue with the Interface .create api call, it's throwing a Cloud exception with no further details .
At least what is the proper way to debug this.. ?! 

            NetworkInterface networkInterface = azure.networkInterfaces().define(netInterfaceName)
                    .withRegion(region)
                    .withExistingResourceGroup(resourceGroupName)
                    .withExistingPrimaryNetwork(azure.networks().getByGroup(resourceGroupName, network))
                    .withSubnet(networkSubnet)
                    .withPrimaryPrivateIpAddressDynamic()
                    .withNewPrimaryPublicIpAddress()
                   .withExistingNetworkSecurityGroup(azure.networkSecurityGroups().getByGroup(resourceGroupName, securityGroup))
                    .create();

                VirtualMachine automationVM = azure.virtualMachines().define(vmName)
                        .withRegion(region)
                        .withExistingResourceGroup(resourceGroupName)
                        .withExistingPrimaryNetworkInterface(networkInterface)
                        .withLatestWindowsImage(vmImage.publisher(), vmImage.offer(), vmImage.sku())
                        .withAdminUsername("ABC")
                        .withAdminPassword("XYZ!")
                        .withSize(azureCores.size())
                        .create();

**Comment by jianghaolu** [comment]
#1531 was fixed in 1.0.0. Can you verify if this is still an issue?

Thanks!

**Comment by buamod** [comment]
I will check it and tell you

**Comment by martinsawicki** [comment]
presumably fixed based on the lack of further response
