### ISSUE TITLE
Evaluate Optimal Data Structure to Store Multi-Value Headers

### ISSUE THREAD

**Issue by alzimmermsft** [Azure/azure-sdk-for-java#15219]
Currently, `HttpHeader` values are stored as a `String`, when the header has multiple values they are concatenated with a coma (`,`). We should evaluate whether this is the most optimal way to store such headers as this may result in a lot of string manipulation.

Evaluate the following data structures for storing header values:

- `List<String>`
- `String[]`
- `String`

Potentially review a combination of the above as there are APIs for returning the concatenated `String` and individual values (`String[]`).

**Comment by leoger** [comment]
It seems to me there's a large subjective element to this issue. There's going to be tradeoffs between cost of object allocation, cost of writes, and cost of reads. Given that, this would benefit from either some data or working assumptions.

@alzimmermsft @joshfree do you have any useful usage statistics from request logs for Azure services? Intuitively, I'd expect responses to be more interesting here. (i.e. a user seems less likely to want to read back the headers they themselves set on a Request before putting it out onto the wire.) 

So we'd be looking for something along the lines of: 
* of incoming **requests** to Azure where the User-Agent string begins with `azsdk-java`...
* looking at the corresponding **responses**
* how often is there at least one multi-valued header value?

Alternatively, this could be construed as an ecosystem survey task, where one goes through [apache/httpcomponents-core](https://github.com/apache/httpcomponents-core/), [google-api-java-client](https://github.com/googleapis/google-api-java-client), etc. and sees what the general community consensus currently is.
