### ISSUE TITLE
[QUERY] How to use EncryptedBlobClient and AsyncKeyEncryptionKey

### ISSUE THREAD

**Issue by yangchengs** [Azure/azure-sdk-for-java#15210]
**Query/Question**
A Microsoft customer wants to implement client side encryption while accessing Azure Blob Storage, they want to store the key at Azure Key Vault and fetch the Key while using EncryptedBlobClient object.

I checked the sample code but still don't know how to start from it because the getKeyId, wrapKey, unwrapKey are returning null.

https://github.com/Azure/azure-sdk-for-java/tree/azure-storage-blob-cryptography_12.7.0/sdk/storage/azure-storage-blob-cryptography/src/samples/java/com/azure/storage/blob/specialized/cryptography

I also read the two links below but still cannot run my java sample code successfully.
https://github.com/Azure/azure-sdk-for-java/issues/6536
https://github.com/Azure/azure-sdk-for-java/issues/6569

I want a step by step guide of how to,

1. Create secret in azure.
2. A runnable sample project with java code and pom.xml.

Thank you!

***Why is this not a Bug or a feature Request?***
A clear explanation of why is this not a bug or a feature request?

**Setup (please complete the following information if applicable):**
 - IDE : [e.g. IntelliJ]
 - Version of the Library used
 
 **Information Checklist**
 Kindly make sure that you have added all the following information above and checkoff the required fields otherwise we will treat the issuer as an incomplete report
- [ ] Query Added
- [ ] Setup information Added

**Comment by abhikt48** [comment]
Hi @yangchengs , 

I am also looking for solution of above problem. If you manage to solve above problem then can you please share sample code ? It will be so helpful.

Regards,
Abhishek Kumar

**Comment by yangchengs** [comment]
Do not use it, I found many problems of this class, for example, there is no decryption methods in the EncryptedBlobClient so you cannot use the same class to get the message decrypted.

**Comment by joshfree** [comment]
Reactivating based on unanswered follow up question

**Comment by joshfree** [comment]
@gapra-msft @rickle-msft could you please assist with this open question?  Thanks 😄

**Comment by yangchengs** [comment]
I opened another issue about downloading, @joshfree you can try my sample code with upload and download.

**Comment by gapra-msft** [comment]
Hi @yangchengs 

Thank you for your question. We have a few samples in this [repo](https://github.com/wastore/azure-storage-samples-for-java/tree/master/ClientEncryptionToCPKNMigrationSamples).

Please let me know if you have any questions about the samples. They show examples of how to upload/download any kind of client side encrypted blob (local key or key vault key)
