### ISSUE TITLE
[BUG] Document needs to be updated

### ISSUE THREAD

**Issue by yangchengs** [Azure/azure-sdk-for-java#15245]
**Describe the bug**
According to the discussion at https://github.com/Azure/azure-sdk-for-java/issues/15171

The following document needs to be updated,
https://docs.microsoft.com/en-us/azure/storage/blobs/data-lake-storage-directory-file-acl-java

The line will throw an exception "mark/reset not supported" with com.azure.storage.common.Utility version 12.8.0
InputStream targetStream = new FileInputStream(file);

It has to be wrapped with a InputStream implementation which supports mark/reset, for example, BufferedInputStream.

***Exception or Stack Trace***
Add the exception log and stack trace if available

**To Reproduce**

***Code Snippet***
Add the code snippet that causes the issue.

**Expected behavior**

**Screenshots**

**Setup (please complete the following information):**
 - IDE : [e.g. IntelliJ]
 - Version of the Library used

**Additional context**

**Information Checklist**
Kindly make sure that you have added all the following information above and checkoff the required fields otherwise we will treat the issuer as an incomplete report
- [ ] Bug Description Added
- [ ] Repro Steps Added
- [ ] Setup information Added

**Comment by amishra-dev** [comment]
Rick can you please take this.
