### ISSUE TITLE
[Tables] [BUG] azure-data-tables Can Not Create TableClientBuilder

### ISSUE THREAD

**Issue by lonpalmer** [Azure/azure-sdk-for-java#15294]
azure-data-tables    12.0.0-beta.1

The access modifier on the constructor for TableClientBuilder is "default" or Package Private, not Public.  Therefore I can not construct it.  In order to construct it my code would have to be in the com.azure.data.tables package, which is not possible.

**To Reproduce**
Simply "new TableClientBuilder()" from any package outside com.azure.data.tables.

**Expected behavior**
The access modifier on TableClientBuilder() should be public, not package private.

**Setup (please complete the following information):**
 IntelliJ IDEA
![image](https://user-images.githubusercontent.com/13160715/93395696-f70ffb00-f83b-11ea-95d0-0c30818e3e96.png)

**Comment by bsiegel** [comment]
Thank you for the report, I will get this fixed shortly. In the meantime, you can create a `TableClient` from an existing `TableServiceClient`:

```java
// Sync
TableClient client = new TableServiceClientBuilder()
                       .connectionString("<connection string>")
                       .buildClient()
                       .getTableClient("<table name>");

// Async
TableAsyncClient client = new TableServiceClientBuilder()
                            .connectionString("<connection string>")
                            .buildAsyncClient()
                            .getTableClient("<table name>");
```
