### ISSUE TITLE
Service Bus client library throws com.sun.jersey.api.client.ClientHandlerException: java.net.SocketTimeoutException: Read timed out after idle time and stops receiving Msgs

### ISSUE THREAD

**Issue by mikeppp** [Azure/azure-sdk-for-java#1529]
Hi all,

We have to ingrate our Java APP with Service Bus and are using the latest client library. We are having several issues:

a. As  long as messages keep flowing in everything is fine;
b. We have set the wait timeout as 5 min and have it in an infinite Rcv loop in a thread. That is if we get nothing got back and receive (wait).

NOW

The observed behaviour is:

a, After about 90 seconds it throws:
com.sun.jersey.api.client.ClientHandlerException: java.net.SocketTimeoutException: Read timed out

b. We gracefully catch this exception and then go back  and receive. HOWEVER once this happens no more messages are EVER received! 
b. We even tried recreating the service as if it was new but still it doesn't work!

Unfortunately due to library clashes we CANT use the qpid AMQP :(

Please help!

Mike

**Comment by anuchandy** [comment]
Seems data plane issue - please open issue in data plane repo https://github.com/Azure/azure-service-bus-java
