### ISSUE TITLE
ComputeManagementClientImpl - how to get powerState of VM

### ISSUE THREAD

**Issue by renutz** [Azure/azure-sdk-for-java#1530]
Hi,

I'm trying to get the PowerState() of a VM. If I use the Azure client class, it's fine:

```
for (VirtualMachine vm : azure.virtualMachines().list()) {
System.out.printlin("Powerstate: " + vm.powerState());
}
```

But when we use ComputeManagementClientImpl to list VMs, it returns VirtualMachineInner that doesn't expose powerState().

I'd like to use ComputeManagementClientImpl because the Azure client is too 'fat' for now. 

Are we missing something?

Thanks

**Comment by anuchandy** [comment]
PowerState is not an inline property of virtual machine, it is stored inside instance view, see [this code](https://github.com/Azure/azure-sdk-for-java/blob/master/azure-mgmt-compute/src/main/java/com/microsoft/azure/management/compute/implementation/VirtualMachineImpl.java#L328) that retrieve VM with instance view  and [this code](https://github.com/Azure/azure-sdk-for-java/blob/master/azure-mgmt-compute/src/main/java/com/microsoft/azure/management/compute/PowerState.java#L62)  that extract PowerState from instance view.

**Comment by renutz** [comment]
Understood! Thank you
