### ISSUE TITLE
ADLS gen2 official java code is not working

### ISSUE THREAD

**Issue by akshinde27** [Azure/azure-sdk-for-java#15338]
I am trying code for adls gen2 from following official website-
https://docs.microsoft.com/en-us/azure/storage/blobs/data-lake-storage-directory-file-acl-java

Getting following error:-
java.lang.IllegalArgumentException: Input byte array has wrong 4-byte ending unit

Update. Resolved. Thank You

**Comment by gapra-msft** [comment]
Hi @akshinde27 

Could you please provide more details for your issue? 

Which code snippet is specifically giving you that error? Could you provide a stack trace if possible?

**Comment by akshinde27** [comment]
Have tried all code samples listed on following page. for eg. downloading file, listing files. but it's throwing error for everything. I think the official ADLS gen2 java code is not working properly

**Comment by akshinde27** [comment]
> Hi @akshinde27 Thank you for posting your question.
> 
> Could you please provide more details for your issue?
> 
> Which code snippet is specifically giving you that error? Could you provide a stack trace if possible?

THank You for the efforts. It's Resolved
