### ISSUE TITLE
[BUG] Java Spring for ServiceBus, azure-servicebus-jms-spring-boot-starter, fails to load unless a second undocumented app setting is in place.

### ISSUE THREAD

**Issue by NickDrouin** [Azure/azure-sdk-for-java#15333]
**Describe the bug**
Follow the walkthrough at: 
https://docs.microsoft.com/en-us/azure/developer/java/spring-framework/configure-spring-boot-starter-java-app-with-azure-service-bus

This will fail unless the value for:
spring.jms.servicebus.connection-string
is replicated into:
azure.servicebus.jms.connection-string
in the configuration file.

Meanwhile, logged doc bug:
https://github.com/MicrosoftDocs/azure-dev-docs/issues/292

***Exception or Stack Trace***
Add the exception log and stack trace if available

**To Reproduce**

***Code Snippet***
Add the code snippet that causes the issue.

**Expected behavior**

**Screenshots**

**Setup (please complete the following information):**
 - IDE : [e.g. IntelliJ]
 - Version of the Library used

**Additional context**

**Information Checklist**
Kindly make sure that you have added all the following information above and checkoff the required fields otherwise we will treat the issuer as an incomplete report
- [ ] Bug Description Added
- [ ] Repro Steps Added
- [ ] Setup information Added

**Comment by chenrujun** [comment]
Hi, @NickDrouin .

Thank you for your detailed description.

In my understanding, `spring.jms.servicebus.connection-string` should be right, here is [related  java code](https://github.com/microsoft/azure-spring-boot/blob/2.1.7/azure-spring-boot/src/main/java/com/microsoft/azure/spring/autoconfigure/jms/AzureServiceBusJMSProperties.java#L16):

```
@ConfigurationProperties("spring.jms.servicebus")
public class AzureServiceBusJMSProperties {

    private String connectionString;

    private String topicClientId;
...
```

**Comment by NickDrouin** [comment]
That is as per the doc, but not what happens at runtime.
FYI: Doc bug https://github.com/MicrosoftDocs/azure-dev-docs/issues/292 (meanwhile).

**Comment by scgbear** [comment]
<details>
<summary>Internal Tracking</summary>
devdivcsef [387675]
</details>

**Comment by NickDrouin** [comment]
Found it:
    @PostConstruct
    public void validate() {

        if (!StringUtils.hasText(connectionString)) {
            throw new IllegalArgumentException("'**azure.servicebus.jms.connection-string**' " +
                    "should be provided");
        }

    }

**Comment by NickDrouin** [comment]
That is, when the config string is misconfigured, or not parsed by spring; it throws an Illegal Arg Exception that has the wrong setting.
https://github.com/microsoft/azure-spring-boot/blob/e28621035e06a142b67afad2aa4a74d344df5698/azure-spring-boot/src/main/java/com/microsoft/azure/spring/autoconfigure/jms/AzureServiceBusJMSProperties.java#L53

**Comment by NickDrouin** [comment]
Submitted:

**Comment by chenrujun** [comment]
Hi, @NickDrouin , Thank you very much for your PR, I merged it just now. 

We will release new version for 2.1.x few weeks later. 

Closing this issue.
