### ISSUE TITLE
[QUERY] Copy Blob in Azure Blob Storage using Java v12 SDK

### ISSUE THREAD

**Issue by vzhemevko** [Azure/azure-sdk-for-java#15358]
**Query/Question**

I haven't found any particular [recommendations or examples](https://github.com/Azure/azure-sdk-for-java/tree/master/sdk/storage/azure-storage-blob#examples) of how SDK should be used to do the blob copy.

What are the right ways to implement a copy blob using Java v12 SDK?

More details about an issue I'm having [here](https://stackoverflow.com/questions/63946587/copy-blob-in-azure-blob-storage-using-java-v12-sdk)

**Comment by rickle-msft** [comment]
Hi, @vzhemevko. Thanks for your question. Could you try attaching a sas token with appropriate permissions to the copy source url? That should allow you to successfully complete the copy. For more information, you can look at the [REST doc](https://docs.microsoft.com/en-us/rest/api/storageservices/copy-blob-from-url), which states: "The source blob must either be public or must be authorized via a shared access signature". Also note, "The value should be URL-encoded as it would appear in a request URI."

As far as the clarity of the error message, I believe that one is left intentionally vague for security reasons. 

Please let me know if you have any more questions or concerns

**Comment by vzhemevko** [comment]
Hi, @alzimmermsft. Thanks for your reply.

**Comment by rickle-msft** [comment]
@vzhemevko Thanks for the update! The code you linked to looks fine for Sas generation. The exception you're seeing is thrown when a service client is constructed without credentials (aka an anonymous client) and then a method is called which requires credentials. That leads me to believe that you are generating an account sas? In which case, please double check that you set a sharedKeyCredential on the builder. 

Thank you for your suggestion on adding samples to copy blob. We will look into adding more soon.

**Comment by rickle-msft** [comment]
I also just created a separate issue to track adding the copy samples so this thread can focus on answering your questions.

**Comment by vzhemevko** [comment]
@rickle-msft Thank you for the issue regarding updating the docs, I think that will be very useful. 
Sorry for the delay in response, was a bit busy with other activities. 

Thanks to your recommendations and this [answer ](https://stackoverflow.com/a/63986414/2046584) I finally managed to do the copy. My final solution looks something like this

```
        String sasToken = sourceBlobClient.generateSasToken();
        copyBlobClient.copyFromUrl(sourceBlobClient.getBlobUrl() + "?" + sasToken);
```

The `sourceBlobClient.generateSasToken();` has the implementation based on the link I shared earlier. 
However, I'm still not sure If I'm doing everything correctly since I'm doing copy in the same account and for  `BlobServiceClient` I'm using MSI so I was expecting It should work without SAS. Could you confirm that this is a normal situation and provide details on the necessity of adding the token in the same account? Perhaps I have misconfigured something.

**Comment by rickle-msft** [comment]
@vzhemevko I'm glad to hear you're having more success now. The [docs for copyFromUrl](https://docs.microsoft.com/en-us/rest/api/storageservices/copy-blob-from-url) state: "The source for a Copy Blob From URL operation can be any committed block blob in any Azure storage account which is either public or authorized with a shared access signature." So I think the behavior you're seeing is expected. If you start an async copy using the `beginCopy` method, you should be able to share authentication between the source and destination if they are in the same account.

**Comment by somanshreddy** [comment]
@rickle-msft I am seeing the same error when using `copyFromUrl()` 

```
Status code 404, "<?xml version="1.0" encoding="utf-8"?><Error><Code>CannotVerifyCopySource</Code><Message>The specified resource does not exist.
RequestId:5b0044e9-401e-009a-5483-a7390f000000
Time:2020-10-21T08:27:09.6583037Z</Message></Error>"
```

I am using the `StorageSharedKeyCredential` so I don't see why I would need the blob to be public or authorized via Sas since it is already authorized. 

Suprisingly, the same source and destination works with the `beginCopy()` method. Added a `waitForCompletion()` immediately afterwards to mimic the sync behaviour. And the docs here [https://docs.microsoft.com/en-us/rest/api/storageservices/copy-blob](url) say the same thing about authorization. 

Though I guess the 256 MB limit in `copyFromUrl()` would make the `beginCopy()` an inevitable choice for large blobs. So this issue isn't blocking as such.

**Comment by somanshreddy** [comment]
@rickle-msft Thanks for the examples. I had a question but the samples posted had answered that. 

On a somewhat side note, yet quite related to the `CopyBlob`, the aysnc version has a `SyncPoller` which would be querying the Copy Status of the Blob to determine when the operation should end. The docs mention the following under the billing section here [https://docs.microsoft.com/en-us/rest/api/storageservices/copy-blob#remarks](url) 

> The destination account of a Copy Blob operation is charged for one transaction to initiate the copy, and also incurs one transaction for each request to abort or request the status of the copy operation.

Seems like this pretty much answers my question but still wanted to confirm that the `SyncPoller` would be making requests that fall under the request status operation and would hence be _charged_ ?

If yes, then the default time of 1s to poll seems a bit aggressive. I would think it would be better for me to see how long these copy operations take on an average based on the blob size and maybe dynamically adjust the polling time to reduce the number of calls made. Thoughts?

**Comment by rickle-msft** [comment]
@somanshreddy Glad to hear the samples answered your question :)

Your understanding is correct. We make a getProperties call to check the status, so billing will be standard for that api. 

I think it is a fair claim that it is a rather aggressive default. The async copy only guarantees that the copy completes within two weeks, but most copies, especially for small blobs, complete very quickly, so it's frankly next to impossible to pick something that doesn't have major drawbacks in at least some scenarios.

Your idea is a good one. I'm not sure you'll be able to definitively predict how long a copy will take based on the size as it's not quite so deterministic, but collecting some data and tailoring your configurations based on your datasets is generally the right way to go. The tradeoffs of cost for more requests vs wasting time waiting for another poll operation when the copy is actually completed is something you'll have to determine for your scenario. If we can assist in determining that in any way, though do let us know.

**Comment by somanshreddy** [comment]
@rickle-msft Thank you. I think I'll try out a few datasets and see how things go. Yes, I agree that it isn't deterministic but a small adjustment can be made based on size. Running a few tests would make things concrete. Thanks for offering help, I think I have understood the situation and I can keep this thread posted regarding the developments if you or anyone else might be interested.

**Comment by somanshreddy** [comment]
@rickle-msft Also, I missed asking this. `CopyFromUrl` seems to have a restriction of 256 MB. Since my application would need to copy things in a sync manner, I think any copies below 256MB can be done via the `CopyFromUrl` to avoid the extra calls to poll right? And then the ones above 256 can be done via `beginCopy` with the poll time dynamically adjusted based on the results of some tests.

**Comment by rickle-msft** [comment]
That is correct!

**Comment by gapra-msft** [comment]
Closing since all questions have been resolved.
