### ISSUE TITLE
[FEATURE REQ] Appconfig default-context for each store

### ISSUE THREAD

**Issue by bilak** [Azure/azure-sdk-for-java#15364]
with current version `1.2.7` of `spring-cloud-azure-appconfiguration-config`  it's possible to define `default-context` only on level of entire application so each store is affected by that. 
I'd propose to create also `defaultContext` for each store and if it's not specified then get the context of parent configuration. This will provide more flexibility when selecting keys from app configurations. 

For example if we have stores:
* for storage accounts we have something like `/storage-accounts-cmmon...`
* for service bus `/service-bus-common...`

we share some of those settings between few services and it would be nice if we can specify for each store in which context are we interested.

Or maybe there is such configuration but I didn't found that.

**Comment by mrm9084** [comment]
@bilak In the 2.0.0 version we just released we redesigned how the contexts are loaded. You should be able to use it to `selects` configuration to load what you need. https://github.com/Azure/azure-sdk-for-java/tree/main/sdk/appconfiguration/azure-spring-cloud-starter-appconfiguration-config#supported-properties
