### ISSUE TITLE
[QUERY] Azure Spring Boot starter - AADB2CAuthorizationRequestResolver clearing Spring Security Context

### ISSUE THREAD

**Issue by R0st0s** [Azure/azure-sdk-for-java#15427]
**Query/Question**
This is related to the Azure AD B2C Spring Boot starter. It uses the AADB2CAuthorizationRequestResolver to construct the request to B2C, and as part of that, it clears the Spring Security context. See: [Source](https://github.com/Azure/azure-sdk-for-java/blob/b0e44ba80c89d7eb686a62991c0864f702530ca6/sdk/spring/azure-spring-boot/src/main/java/com/microsoft/azure/spring/autoconfigure/b2c/AADB2CAuthorizationRequestResolver.java#L89)
Whenever the logged in user cancels a flow, for example a profile edit or some custom policy that's not login or logout, you would expect to keep the user logged in.
Spring's DefaultOAuth2AuthorizationRequestResolver doesn't do that.

***Why is this not a Bug or a feature Request?***
There might be a valid reason for this behaviour.

**Setup (please complete the following information if applicable):**
 - OS: Windows
 - IDE : IntelliJ 
 - Version of the Library used 2.3.3
 
 **Information Checklist**
 Kindly make sure that you have added all the following information above and checkoff the required fields otherwise we will treat the issuer as an incomplete report
- [x] Query Added
- [x] Setup information Added

**Comment by joshfree** [comment]
@jialindai could you please follow up on this `azure-spring-aad-b2c` question

**Comment by saragluna** [comment]
@backwind1233 will help fix this issue, and we'll fix it by deleting this line:

https://github.com/Azure/azure-sdk-for-java/pull/18489/files#diff-8bd1fd1cfe71fa42206bb4ef48363ae942cc3a021c738e53384cac88574c784fL89

**Comment by yiliuTo** [comment]
Closing this issue because the PR has been merged
