### ISSUE TITLE
[BUG] TransportException#IsUserRequestSent logic is missing

### ISSUE THREAD

**Issue by moderakh** [Azure/azure-sdk-for-java#15432]
TransportException#IsUserRequestSent logic is missing.
As a result we may retry write request which was sent over the wire, but didn't get back a response from service.

not having this will result in retrying writes on failure incorrectly

**Comment by kushagraThapar** [comment]
Currently Java SDK decides on few Channel Exceptions if the request reached the server or not: 

// any network failure for which we are certain the request hasn't reached the service endpoint.
`ConnectException, UnknownHostException, SSLHandshakeException, NoRouteToHostException, SSLPeerUnverifiedException`
