### ISSUE TITLE
[QUERY] About eventhub sdk performance

### ISSUE THREAD

**Issue by lu-cheng** [Azure/azure-sdk-for-java#15478]
Hi, @conniey  @mikeharder 
I created a test project about eventhub, The test uses resources (VM, Eventhub) in the same region，and the round trip time through eventhub is 100-300 msec. Is this performance a normal expectation?  I have a customer here and expect this result to be 50 msec. Can it be improved?

If my test code is incorrect, please help me correct it.
Repository: https://github.com/lu-cheng/eventhub-test

**Comment by conniey** [comment]
This is a duplicate of https://github.com/Azure/azure-sdk-for-java/issues/15077
