### ISSUE TITLE
Event Hubs Readme issues

### ISSUE THREAD

**Issue by Melanie-Ma** [Azure/azure-sdk-for-java#15503]
1.
Section [Link](https://github.com/Azure/azure-sdk-for-java/tree/master/sdk/eventhubs/azure-messaging-eventhubs#table-of-contents):
![image](https://user-images.githubusercontent.com/64007802/93854389-3cbf3e80-fce8-11ea-8986-8972cd98a0ef.png)
Suggestion:
a.  Add hyperlink for `Including the package` https://github.com/Azure/azure-sdk-for-java/tree/master/sdk/eventhubs/azure-messaging-eventhubs#include-the-package
b.  Delete `Default SSL library`
2.
Section [Link](https://github.com/Azure/azure-sdk-for-java/tree/master/sdk/eventhubs/azure-messaging-eventhubs#prerequisites):
![image](https://user-images.githubusercontent.com/64007802/93855101-7f354b00-fce9-11ea-9aab-9132d541524d.png)
Suggestion:
Add hyperlink for  `Java Development Kit(JDK) ` https://docs.microsoft.com/en-us/java/azure/jdk/?view=azure-java-stable

@jongio for notification.

**Comment by joshfree** [comment]
Looks like the Default SSL Library link was already removed long ago; and @conniey recently fixed the package link https://github.com/Azure/azure-sdk-for-java/commit/5fa67a5c18d619f83e6a15e992c64f780627232a#diff-c582aeac546cea0e843017227f72b2d3
