### ISSUE TITLE
Event Grid Sample issues

### ISSUE THREAD

**Issue by Melanie-Ma** [Azure/azure-sdk-for-java#15508]
1.
Section [Link](https://github.com/Azure/azure-sdk-for-java/blob/master/sdk/eventgrid/azure-messaging-eventgrid/src/samples/java/com/azure/messaging/eventgrid/ReadmeSamples.java#L44):
![image](https://user-images.githubusercontent.com/64007802/93955537-8f4d3900-fd82-11ea-9919-25017d51b124.png)
![image](https://user-images.githubusercontent.com/64007802/93955546-9116fc80-fd82-11ea-90ea-4c8440d4e905.png)
Reason:
The number of parameters does not match.
Suggestion:
Delete the parameter `1` 

@jongio for notification.

**Comment by joshfree** [comment]
This PR updated both the EventGridEvent ctor and the readme sample code to take 4 params.  https://github.com/Azure/azure-sdk-for-java/commit/d43a520cd41044a2518ede6a51e65e6a2f66747b.  Closing this issue as I don't believe the inconsistency exists in the latest build.

Though looking at the EventGridEvent public ctor in C# and Python shows that the parameter ordering is different across the different SDK languages (/cc @ellismg).  I'll follow up on that offline.
