### ISSUE TITLE
Service Bus Sample issues

### ISSUE THREAD

**Issue by Melanie-Ma** [Azure/azure-sdk-for-java#15507]
1.
Section [Link1](https://github.com/Azure/azure-sdk-for-java/blob/master/sdk/servicebus/azure-messaging-servicebus/src/samples/java/com/azure/messaging/servicebus/ServiceBusSenderAsyncClientJavaDocCodeSamples.java#L97)，[Link2](https://github.com/Azure/azure-sdk-for-java/blob/master/sdk/servicebus/azure-messaging-servicebus/src/samples/java/com/azure/messaging/servicebus/ServiceBusSenderClientJavaDocCodeSamples.java#L83):
![image](https://user-images.githubusercontent.com/64007802/93953715-b1dd5300-fd7e-11ea-9570-ea4c831aefab.png)
Suggestion:
Update `getApplicationProperties()` to `getProperties()`.
2.
Section [Link](https://github.com/Azure/azure-sdk-for-java/blob/master/sdk/servicebus/azure-messaging-servicebus/src/samples/java/com/azure/messaging/servicebus/ReceiveNamedSessionSample.java#L59):
![image](https://user-images.githubusercontent.com/64007802/93953866-0385dd80-fd7f-11ea-90bc-f3a47f543cb0.png)
Suggestion:
Change the type `String` to `MessageLockToken`.
Waht`s more, please check all samples about receiving Message.

@jongio for notification.

**Comment by conniey** [comment]
@Melanie-Ma How did you open the samples solution? We compile the samples as part of our CI. So they compile on my machin and in CI.

**Comment by Melanie-Ma** [comment]
For the first issue: fixed by the PR #14848(The file of ServiceBusMessage.java)
For the second issue: fixed by the PR #15932
