### ISSUE TITLE
Spring Cloud Readme issues

### ISSUE THREAD

**Issue by Melanie-Ma** [Azure/azure-sdk-for-java#15505]
1. 
Section [Link](https://github.com/Azure/azure-sdk-for-java/tree/master/sdk/spring/azure-spring-cloud-autoconfigure#prerequisites):
![image](https://user-images.githubusercontent.com/64007802/93856716-05529100-fcec-11ea-94f4-3aebd9fa941b.png)
Suggestion:
Add hyperlink for  `Java Development Kit(JDK) ` https://docs.microsoft.com/en-us/java/azure/jdk/?view=azure-java-stable

@jongio for notification.

**Comment by saragluna** [comment]
The PR has been merged and I'm going to close this issue now.
