### ISSUE TITLE
Support for side-by-side versioning

### ISSUE THREAD

**Issue by mitchdenny** [Azure/azure-sdk-for-java#15512]
This issue is to track effort related to supporting side-by-side versioning. The Azure Spring team has indicated that they would like to be able to build and release multiple versions of the same package from the same branch in the repository.

This will require a number of changes and extensive testing to make sure all the features of the engineering continue to function as expected both for Azure Spring components, and all of the other components within the SDK. Here is a check-list of engineering system features that we need to validate (at a minimum).

- [ ] Maven builds, analysis tooling (checkstyle etc), testing incl. code coverage.
- [ ] Source builds
- [ ] Artifact publishing (into pipeline artifacts)
- [ ] Code signing logic
- [ ] Maven publishing
- [ ] Doc publishing
- [ ] nightly package publishing
- [ ] Versioning bumping logic

This probably represents an epic in its own right. We'll need to coordinate all this work on a feature branch (or see if we can break it up into _stable_ chunks).

**Comment by kurtzeborn** [comment]
This is a Java-specific issue/need, so labeling it "Client".  The EngSys team has a number of concerns with the request (primarily that this will take at least 2 months to implement).  There needs to be an investigation between the Spring and Java libraries team on whether or not the really want to support this.  Please consult with @mitchdenny and @JimSuplizio as needed to ensure this plugs into the overall system well.

**Comment by mitchdenny** [comment]
Looks like this request has bubbled to the top again. I was shown a trick with Maven yesterday which I think will be helpful in moving this forward, although significant rework of some parts of the engineering system still remain (with potentially destabilizing effects). What follows is a high level audit of areas that will need to be reworked to accommodate duplicated artifact names within the same build graph:

# Build
When we trigger a build, we target the Maven projects to build using the artifact coordinates (excluding version). This works because Maven uses the ```pom.xml``` file in the root of the repository to read all of the Maven projects and then find the targets and their dependencies to build using the coordinates provided. Example:

```bash
mvn -f pom.xml -pl com.azure.spring:azure-identity-spring [goal]
```

The issue with the side-by-side versioning challenge is that this might be ambiguous. Let's say you have two POM files that both contain an artifact named ```com.azure.spring:azure-identity-spring``` - if you execute the above command its going to return an error because it is ambiguous which one you mean. If you build everything it would be fine because both projects would be built, and dependencies are resolved using full coordinates which include version numbers.

To work around this there is a trick (which I've just learned about). Instead of providing Maven artifact coordinates, you can specify a path to a POM file. In this way you can side-step the ambiguity, here is an example:

```bash
mvn -f pom.xml -pl ./sdk/spring/azure-identity-spring [goal]
```

In this scenario it would build the version of the spring module contained within that service directory. But if you had another spring version, you could target it similarly (example):

```bash
mvn -f pom.xml -pl ./sdk/spring-2-3/azure-identity-spring [goal]
```

Of course you can do both as well:

```bash
mvn -f pom.xml -pl ./sdk/spring/azure-identity-spring,./sdk/spring-2-3/azure-identity-spring [goal]
```

This is a reasonable solution to the build ambiguity problem. What then remains to answer is how do we integrate this into the build stage. What modules are built in the Java pipelines is driven by the artifact list in the ```ci.yml``` file. Here is an example"

```yaml
Artifacts:
- name: azure-identity-spring
  groupId: com.azure.spring
```

This particular invocation would result in a failed build if the artifact names overlapped. To overcome this we could modify our templates to allow for an _optional_ ```path:``` attribute on the artifact (example):

```yaml
Artifacts:
- name: azure-identity-spring
  groupId: com.azure.spring
  path: sdk/spring/azure-identity-spring
```

Any time we iterated over the artifact list to build a command that is passed to Maven, we would detect if this attribute has a value and instead use that path instead of the Maven coordinates.

**Comment by mitchdenny** [comment]
Dev versioning is another area of automation that will need to be adjusted to support side-by-side versioning of Spring projects. This is primarily achieved via the ```eng/versioning/set_versions.py``` and ```eng/versioning/update_versions.py``` scripts.

Prior to running the build, if the ```SetDevVersion``` variable is set to true, we go through and update the versions of packages. This mechanism is not aware of multiple packages that share the same ```groupId:artifactId``` and would need to be adjusted, and could be a bit of a bug farm.

Currently when setting the ```--build-qualifier``` we provide the group ID and artifact ID. We would instead need to provide the file path. But we would also need to keep track of the versions to make sure we were updating the right one when they are referenced as dependencies. This could be one of the more complex parts of the work.

**Comment by mitchdenny** [comment]
When we publish artifacts into pipeline artifacts there is potential for conflict. At the moment we place each artifact in its own subdirectory based on the group ID and artifact ID. If we built multiple versions of the same spring module in the same service pipeline this would result in two versions being placed in the same directory, which means that when we went to publish the packages we would be forced to publish both at the same time.

The _hacky_ mitigation for this is for us to maintain two different service directories (e.g. ```spring-2-3``` and ```spring-2-4```) which means separate pipelines and no potential artifact overlap.

**Comment by mitchdenny** [comment]
Changelogs will be interesting conceptually. We'll have two different changelogs for the same artifact, but both with very different entries. Having said that I think that the ```Verify-Changelog.ps1``` and related plumbing should be fine since it takes a service directory which we would be using to disambiguate.

**Comment by mitchdenny** [comment]
Based on the conversations in the meeting with the Azure Spring team today, I think we are dropping plans to do SxS. Any servicing requirements for older versions would be done off hotfix branches which would be updated with a appropriate dependencies. Backporting new SDK features to previously released Azure Spring modules would be evaluated on a case by case basis should customers explicitly requested (and be treated like any other servicing release with due consideration given to the impact of the change on existing customers etc).
