### ISSUE TITLE
[KeyVault] KeyVaultClient not mockable

### ISSUE THREAD

**Issue by enc** [Azure/azure-sdk-for-java#1552]
The `KeyVaultClient` is the central class for interaction with the KeyVault.

For testing purposes it is the optimal place to mock responses, since I do not want to test the azure sdk.

Unfortunately this class is `final`. First for a good reason if you see is as a programming API. Second it makes nice testing hard/impossible.

Please trust developers using your SDK.

    Cannot mock/spy class com.microsoft.azure.keyvault.KeyVaultClient
    Mockito cannot mock/spy because :
     - final class

**Comment by martinsawicki** [comment]
@jianghaolu this needs to be moved to the new KeyVault client repo

**Comment by Petermarcu** [comment]
@schaabs @joshfree @JonathanGiles Do you know if the track 2 KeyVault client is mockable? If it is, we can close this?

**Comment by Petermarcu** [comment]
@g2vinay

**Comment by g2vinay** [comment]
> @schaabs @joshfree @JonathanGiles Do you know if the track 2 KeyVault client is mockable? If it is, we can close this?

@Petermarcu, @joshfree , @JonathanGiles, @schaabs 

Our Client classes (Secret, Keys, Certificates) are final in Track 2 as well.
So, Mockito by default should still throw this error when user tries to mock the clients.
But, Mockito 2 supports mocking final classes.
it can be done via the mockito extension mechanism by creating the file src/test/resources/mockito-extensions/org.mockito.plugins.MockMaker containing a single line:
mock-maker-inline

Power Mockito supports mocking final and static classes by default without any extra config like above.
