### ISSUE TITLE
Support for Recovery Services

### ISSUE THREAD

**Issue by renutz** [Azure/azure-sdk-for-java#1554]
Hi,

Is there any timeframe to support Recovery Services?

I'm trying to accomplish something like this with Java SDK

https://docs.microsoft.com/en-us/azure/backup/backup-azure-vms-automation

Thanks

**Comment by renutz** [comment]
Bump... any estimate?

Thanks

**Comment by jianghaolu** [comment]
@selvasingh Can you answer this question?

**Comment by renutz** [comment]
Bump....

**Comment by martinsawicki** [comment]
Recovery Services is on the backlog and will be scheduled based on overall priorities, TBD at this point.
IN the meantime, as of v1.3, there is a stub [ecoveryManager](http://search.maven.org/#artifactdetails%7Ccom.microsoft.azure%7Cazure-mgmt-recoveryservices%7C1.3.0-beta%7Cjar), whose `.inner(0` method provides access to the auto-gen'd intyernal impls for this service (i.e. no user-facing fluent yet, but as a temporary workaround, the Inner surface could be used in the meantime)
