### ISSUE TITLE
Release a shaded version of the SDK

### ISSUE THREAD

**Issue by clguimanMSFT** [Azure/azure-sdk-for-java#1555]
I'm trying to use the Azure SDK inside a Jenkins plugin, but unfortunately I'm hitting a dependency problem: The Jenskins war comes with guava 11 and the SDK depends on guava 18. At run-time the JVM decides to load the guava 11 so the SDK gets class not found exception when trying to access functionality not yet available in that version.
The best solution would be to also release a shaded version of the SDK that has all the dependencies embedded and the package is renamed so consumers can use both version side by side.
The shaded version is also useful for people that don't use Maven.

**Comment by linchan825** [comment]
We had a similar issue with fasterxml.jackson library. There is a -DrunShadePlugin profile already seems. However, we have to add our own relocate option to workaround this version conflict issue.

**Comment by martinsawicki** [comment]
as per earlier investigation, Jenkins is tied to guava 11 and that's the crux of the issue indeed.
@linchan825 feel free to submit a PR to the SDK pom for the shaded version that addresses this.
