### ISSUE TITLE
DiskInner is missing diskState

### ISSUE THREAD

**Issue by renutz** [Azure/azure-sdk-for-java#1556]
Hi,

On the REST response for Disks, properties contains "diskState", which is not mapped yet.

...
        "diskSizeGB": 8,
        "timeCreated": "2017-02-16T21:06:00.9095133+00:00",
        "provisioningState": "Succeeded",
        "diskState": "Unattached"
...

Thanks

**Comment by renutz** [comment]
Bump... We are listing all disks and without this field there is no way of knowning if they are attached or no.

for (Disk disk: azure.disks().list())...

thanks

**Comment by martinsawicki** [comment]
@anuchandy missing in Swagger?

**Comment by anuchandy** [comment]
@renutz you can use disk.virtualMachineId() getter, if it returns a non-null value then it is the resource id of the virtual machine the disk is attached to. If the disk is in detached state then this getter returns null.

@martinsawicki we don't see this property is documented in the swagger https://github.com/Azure/azure-rest-api-specs/tree/master/arm-compute/2016-04-30-preview/swagger Need to follow up with DiskRP.

**Comment by anuchandy** [comment]
Service team confirmed that this should not be a customer visible property, will be removed from the payload eventually.
