### ISSUE TITLE
azure-mgmt-datalake-store hasn't been updated in maven central

### ISSUE THREAD

**Issue by sodre90** [Azure/azure-sdk-for-java#1557]
azure-mgmt-datalake-store latest version is '1.0.0-beta1.3' in maven central, which is incompatible with latest com.microsoft.azure:azure ('1.0.0-beta5')

**Comment by martinsawicki** [comment]
@jianghaolu to be followed up with DataLake who will need to get more up to date it looks like

**Comment by praries880** [comment]
@jianghaolu has this been fixed?

**Comment by jianghaolu** [comment]
Sorry for the delay in response. Hopefully the newer versions have already been discovered as our latest release is 1.22.0 now.
