### ISSUE TITLE
[BUG] Appconfig + Kubernetes configmap

### ISSUE THREAD

**Issue by bilak** [Azure/azure-sdk-for-java#15620]
Hello, 
I've posted the issue [here](https://github.com/Azure/AppConfiguration/issues/409) and then realised that this would be better place. 

TLDR:
it's not possible to setup Appconfig when store's `connection-string` should be located from Kubernetes ConfigMap. 

If there is a simple way how to do that please let me know.

**Comment by mrm9084** [comment]
See response here: https://github.com/Azure/AppConfiguration/issues/409
