### ISSUE TITLE
Success callback called twice after async VM create

### ISSUE THREAD

**Issue by linchan825** [Azure/azure-sdk-for-java#1563]
We are using the code in master branch as of 3/29/16. We are creating VM using the createAsync API with the callback object passed in. We noticed that the success function in the callback object is called twice for every VM. This is breaking our assumption. Please let us know if our assumption is not correct.

**Comment by hovsepm** [comment]
@linchan825 could you provide a code sample?

**Comment by anuchandy** [comment]
`AnyResource::createAsync` returns `Observable<Indexable>` not `Observable<AnyResource>`. The onNext of the observer subscribed to `AnyResource::createAsync` can be called multiple times, each time a related resource is created and finally with the created main resource. Does this answer your question?

**Comment by martinsawicki** [comment]
@anuchandy not sure if your comment is answering the original question, which appears to be about Futures not Observables

**Comment by anuchandy** [comment]
@martinsawicki you are right. 

@linchan825 can you try with the latest SDK (v1.3)? Tried using callback based async it behaved as expected. The success call-back gets called only once.

```java
ServiceFuture<VirtualMachine> future = computeManager.virtualMachines()
.define(VMNAME)
    .withRegion(REGION)
    .withNewResourceGroup(RG_NAME)
    .withNewPrimaryNetwork("10.0.0.0/28")
    .withPrimaryPrivateIPAddressDynamic()
    .withoutPrimaryPublicIPAddress()
    .withPopularWindowsImage(KnownWindowsVirtualMachineImage.WINDOWS_SERVER_2012_DATACENTER)
    .withAdminUsername("user")
    .withAdminPassword("<password>")
    .withUnmanagedDisks()
    .withSize(VirtualMachineSizeTypes.STANDARD_D3)
    .withOSDiskCaching(CachingTypes.READ_WRITE)
    .withOSDiskName("javatest")
.createAsync(new ServiceCallback<VirtualMachine>() {
    @Override
    public void success(VirtualMachine vm) {
        System.out.println("Success called: " + vm.name());
    }
    @Override
    public void failure(Throwable t) {
        t.printStackTrace();
    }
});

future.get();
```

[output]

``` 
Success called: javavm
```

Closing this for now. If you still have the issue, feel free to re-open this with repro code.
