### ISSUE TITLE
Ensure all Key Vault models align correctly with the Swagger specification

### ISSUE THREAD

**Issue by vcolin7** [Azure/azure-sdk-for-java#15648]
Issue #14513 showed that the Key Vault Keys library had issues when deserializing a couple models (fixed by #15375), so it would be a worthwhile effort to further look into the rest of the models in Keys, Certificates and Secrets to ensure everything conforms to the service's Swagger specification.

**Comment by alzimmermsft** [comment]
Closing as KeyVault now uses code generation
