### ISSUE TITLE
[BUG] Dependency check failing

### ISSUE THREAD

**Issue by RobertButtigieg** [Azure/azure-sdk-for-java#15665]
**Description**
I am importing the azure-security-keyvault-keys (v 4.2.1) and the azure-identity (v 1.1.2) libraries and when I attempt to run the build which contains the OWASP dependency-check plugin, it is failing on a number of vulnerabilities (listed below in the exception section).

***Exception or Stack Trace***
![image](https://user-images.githubusercontent.com/42947829/94232805-13302e00-ff07-11ea-9834-430ae9ce543d.png)

**To Reproduce**
Import both libraries into this open source project (https://github.com/onelogin/java-saml/tree/v2.5.0) and run the build.

**Screenshots**
The imported dependencies in my project:
![image](https://user-images.githubusercontent.com/42947829/94234519-1e388d80-ff0a-11ea-8bb4-0f220e9ad009.png)

I am also attaching with this issue the dependency tree for my project and the report generated by the dependency check plugin.

[dependency-check.zip](https://github.com/Azure/azure-sdk-for-java/files/5280978/dependency-check.zip)

@isaacsgi

**Comment by alzimmermsft** [comment]
@g2vinay, the reported CVEs appear to be dependencies of `azure-identity`, mind taking a look?

**Comment by g2vinay** [comment]
@RobertButtigieg thank you for reporting this.
I will investigate and update here.

**Comment by joshfree** [comment]
Adding the `blocking-release` label to increase the priority of this investigation during the upcoming `November` coding milestone

**Comment by RobertButtigieg** [comment]
I have tried running the dependency-check plugin using the latest version (v1.1.3) for the azure-identity library and I still got the same list of vulnerabilities, except the one for the json-smart-1.3.1. I am also attaching the new error from the dependency-check plugin together with its report.

[azure-identity-1.1.3.zip](https://github.com/Azure/azure-sdk-for-java/files/5348441/azure-identity-1.1.3.zip)

Should you require more information from my end, kindly let me know.

**Comment by g2vinay** [comment]
@RobertButtigieg 
The issues flagged on KeePassJava2, database, json-smart, msal4j, oauth2-oidc-sdk appear to be false positives.

Simple-xml dependency seems to be coming from KeePassJava2 library.
To unblock yourself the simple-xml issue can be mitigated by excluding the dependency as follows:
```
<dependency>   
  <groupId>com.azure</groupId>   
  <artifactId>azure-identity</artifactId>   
  <version>1.1.2</version>   
  <exclusions>     
    <exclusion>       
     <groupId>org.simpleframework</groupId>       
     <artifactId>simple-xml</artifactId>     
    </exclusion>   
  </exclusions> 
</dependency>
```

Excluding the dependency will not create any negative impact on their production environment and will continue to work fine in the production environment. It will only impact dev-time scenarios where developers are using IntelliJ and <azure plugin> to build and test locally.

We will continue to investigate and get this issue fixed in the 3rd party KeePassJava2 library.

**Comment by RobertButtigieg** [comment]
Hi @g2vinay 

Thanks for your update on this. I have raised an [issue](https://github.com/jeremylong/DependencyCheck/issues/2912) with the dependency check plugin about those false positives.

**Comment by g2vinay** [comment]
The issue should be resolved/mitiagated now, let us know if it still persists.
