### ISSUE TITLE
Maven dependency reliability experiment

### ISSUE THREAD

**Issue by mitchdenny** [Azure/azure-sdk-for-java#15660]
Downloads from Maven Central (via our AFD proxy) has becoming increasingly unreliable. It is possible that using Azure Artifacts might improve overall reliability for artifact downloads. What we want to do is stand-up another AFD instance which instead of proxying Maven Central, proxies Azure Artifacts.

The problem is that public feeds in Azure Artifacts do not support "upstreams" to Maven Central. But in order to support both our public and internal pipelines we need to pull through Azure Artifacts to the Maven Central upstream.

To overcome this, in the new AFD instance we should use rules to inject an authorization header into the request. I've already verified that this is possible and works. What we need to do is try this with a few of our pipelines to see if it yields an improvement in build reliability.

**Comment by mitchdenny** [comment]
@weshaggard and @alzimmermsft I've proven that we can make this work technically (AFD in front of private Azure Artifacts feed with upstreaming enabled) and have a working example on this PR #15651.

**Comment by weshaggard** [comment]
Cool will it correctly pull in upstream packages?

**Comment by mitchdenny** [comment]
> Cool will it correctly pull in upstream packages?

Yes it does. There were a few instances of 503s coming back from Azure Artifacts but I suspect that this was Maven Central giving them a problem, once it is cached in Azure Artifacts it _should_ be more reliable.

Note that I don't think that this will be bullet proof. There will still be transient issues, ideally there will be less. I'm still experimenting.
