### ISSUE TITLE
tracking: fix flakey Service Bus CI tests

### ISSUE THREAD

**Issue by joshfree** [Azure/azure-sdk-for-java#15732]
SB test failures in unrelated Test Linux from Source - Java 11 run:

https://dev.azure.com/azure-sdk/public/_build/results?buildId=553031&view=logs&j=3d7a0212-45d0-5080-1981-6d6ef159b344&t=1d49eeab-37d7-5e10-e021-97c232608292&l=11909

Filing tracking issue to follow up on SB test issues

**Comment by hemanttanwar** [comment]
We have completed few PRs to fix the the test issues in last 2 months. So closing this.
