### ISSUE TITLE
azure-spring-boot traces don't show up in application insights

### ISSUE THREAD

**Issue by vibhuti99** [Azure/azure-sdk-for-java#15773]
**Describe the bug**
Upon updating azure-spring-boot version from 2.1.7 to 2.1.10 in pom.xml file, integration with azure monitor fails. The logs stop getting populated in application insights. 
The bean AzureMonitorMetricsExportAutoConfiguration is conditional on resource "metrics.enable.config" [(link to resource).](https://github.com/Azure/azure-sdk-for-java/blob/master/sdk/spring/azure-spring-boot-starter-metrics/src/main/resources/metrics.enable.config) This resource does not get added to classpath, and upon adding manually also the issue remains the same. 

***Exception or Stack Trace***
No exception is thrown

**To Reproduce**
1) Update azure-spring-boot version to 2.1.10 in pom.xml of module
2) Add log message and check in Traces table in application insights. The log message does not get added there.

***Code Snippet***
N/A

**Expected behavior**
Log messages should get reflected in Traces table in application insights, like with azure-spring-boot version 2.1.7

**Screenshots**
N/A

**Setup (please complete the following information):**
 - OS: Windows 10
 - IDE : IntelliJ
 - Version of the Library used: 2.1.10

**Additional context**

**Information Checklist**
Kindly make sure that you have added all the following information above and checkoff the required fields otherwise we will treat the issuer as an incomplete report
- [Yes] Bug Description Added
- [Yes] Repro Steps Added
- [Yes] Setup information Added

**Comment by joshfree** [comment]
Thanks for reporting this issue @vibhuti99.  @srnagar will follow up as he's currently working on a closely related area for Azure SDKs.

**Comment by chenrujun** [comment]
Hi, @joshfree ,

Did you want to @ @saragluna , not @srnagar ?

**Comment by saragluna** [comment]
Hi @vibhuti99, sorry for the late reply. We've deprecated the azure-spring-boot-starter-metrics, check it [here](https://github.com/Azure/azure-sdk-for-java/tree/master/sdk/spring/azure-spring-boot-starter-metrics). 

Please check https://github.com/Microsoft/ApplicationInsights-Java to see how to use Application Insights in Java.

**Comment by yiliuTo** [comment]
Closing this issure because no response from the customer.
