### ISSUE TITLE
[BUG] Disk partitions are not in correct order when it is created using SDK

### ISSUE THREAD

**Issue by Prudvidhard** [Azure/azure-sdk-for-java#15770]
**Describe the bug**
When we created a VM with unmanaged disk using SDK disk partitions are not in correct order. Below is the disk created using SDK. 1GB unallocated memory is at the end. Because of the recovery partition in the middle it is not easy allocating that 1GB to the C drive.
![DiskCreatedFromSDK](https://user-images.githubusercontent.com/42204140/94396817-5c3ee700-0180-11eb-953a-947f13d71c11.png)
Below is the code used to create disk.
azureInstance.virtualMachines().define("vmName")
				.withRegion(Region.fromName("region"))
				.withExistingResourceGroup("resourceGroupName")
				.withExistingPrimaryNetworkInterface(networkInterface)
				.withSpecificWindowsImageVersion((VirtualMachineImage)marketPlaceImage.imageReference())
				.withAdminUsername(adminUserName)
				.withAdminPassword(adminPassword())
				**.withUnmanagedDisks()**
				.withoutAutoUpdate()
				.withSize("Standard_DS2_v2")
				**.withOSDiskSizeInGB(128)**
				.withExistingStorageAccount(storageAccount)
				.withBootDiagnostics(diagnsoticStorageAccount)	
				.withTag(tagKey1, tagValue1)
                                .withTag(tagKey2, tagValue2)           
                                .defineNewExtension("ExtentionName")
		    	        .withPublisher("Microsoft.Compute")
		    	        .withType("CustomScriptExtension")
		    	        .withVersion("1.9")    
		                .withPublicSetting("fileUris", "Script urls to download to the VM")
		    	        .withProtectedSetting("commandToExecute", "Command to run on VM start up")		    	
		    	        .attach().create();

When the VM is created from azure portal partitions seems to be in correct order.
![CreatedFromAzurePortal](https://user-images.githubusercontent.com/42204140/94399220-990cdd00-0184-11eb-88bb-64ebded7eded.png)

We create vm with unmanaged disk so that we can use create more VMs with managed disk by cloning this unmanaged disk.
After correcting partition order for the unamanged disk using external utility, we created vms by cloning it. partitions for the new VMs also not in correct order.
![ClonedVMPartitions](https://user-images.githubusercontent.com/42204140/94399653-69120980-0185-11eb-9219-65564ba1c110.png)
Below is the code we use to create managed disk by cloning.
VirtualMachine templateVM = azureInstance.virtualMachines().getById(templateUuid);
String vhdPath = templateVM.osUnmanagedDiskVhdUri()
azureInstance.disks().define(diskName).withRegion(region)
.withExistingResourceGroup(rg).**withWindowsFromVhd(vhdPath)**
.withStorageAccountName(vhdStorageAccountName).withSizeInGB(size).withSku(diskSkuType).create();

***Exception or Stack Trace***
No exceptions

**To Reproduce**
Create VM with unamanaged disk using SDK. Code mentioned above. Partitions are not in correct order.
Create another VM by cloning the unamanaged disk after correcting the partitions. Partitions for managed disk are also not in correct order.

***Code Snippet***
Code snippet mentioned above.

**Expected behavior**
If there is unallocated disk space, it should be beside C drive so that it is easy to extend the drive.

**Screenshots**
Gave screenshots above.

**Setup (please complete the following information):**
 - OS: [e.g. iOS] - Our production setup
 - IDE : [e.g. IntelliJ] - Not applicable
 - Version of the Library used - com.microsoft.azure1.33.0

**Additional context**

**Information Checklist**
Kindly make sure that you have added all the following information above and checkoff the required fields otherwise we will treat the issuer as an incomplete report
- [x] Bug Description Added
- [x] Repro Steps Added
- [x] Setup information Added

**Comment by joshfree** [comment]
Thanks for filing this github issue @Prudvidhard.  @yungezz could you please follow up on this `Mgmt` client library issue?

**Comment by yungezz** [comment]
hi @xccc-msft could you pls have a look? thanks

**Comment by xccc-msft** [comment]
@Prudvidhard The `.withUnmanagedDisks()` will not help the disk 0 in the screenshot. What's the image version you are using?

I would add the `Service Attention` so the service team can help verify how the unallocated memory comes from. Thanks.

**Comment by axayjo** [comment]
@avirishuv can you take a look at this issue?

**Comment by Prudvidhard** [comment]
@xccc-msft  Disk is created using marketplace image.
marketplace image is passed in .withSpecificWindowsImageVersion((VirtualMachineImage)marketPlaceImage.imageReference()) in above code.

**Comment by Vaibhav-Agar** [comment]
Hi @Prudvidhard,
I am trying to better understand the issue here. The first screen shot has 2 partitions within disk 0 while the 2nd screenshot has 3 partitions. How did the 3rd partition (of size 534MB) got introduced? Separately, can you please share the marketplace image that you used and the external utility you used to extend the disks?

**Comment by Vaibhav-Agar** [comment]
Closing per the email conversation. Thanks!
