### ISSUE TITLE
Cosmos: consolidate auth header create/update to one method

### ISSUE THREAD

**Issue by milismsft** [Azure/azure-sdk-for-java#15777]
**Is your feature request related to a problem? Please describe.**
Consolidate all the auth refresh handling to one method, i.e. populateAuthorizationHeader()

**Describe the solution you'd like**
Currently auth header is updated/refreshed in several places making it more difficult to maintain.

**Describe alternatives you've considered**
na

**Additional context**
na

**Information Checklist**
Kindly make sure that you have added all the following information above and checkoff the required fields otherwise we will treat the issuer as an incomplete report
- [ ] Description Added
- [ ] Expected solution specified

**Comment by kushagraThapar** [comment]
@aayush3011  - pls take a look at this when you get chance, thanks!
