### ISSUE TITLE
readMany / readManyAsync APIs don't work in GATEWAY mode on azure-cosmos V4 Java SDK

### ISSUE THREAD

**Issue by kushagraThapar** [Azure/azure-sdk-for-java#15833]
* readMany / readManyAsync APIs don't work in GATEWAY mode on azure-cosmos V4 Java SDK
* If used in GATEWAY mode, we get this error:

```
CosmosException{userAgent=Windows10/10.0 JRE/1.8.0_202 cosmosdb-java-sdk/4.3.0, error={"code":"MethodNotAllowed","message":"RequestHandler.Post, StatusCode: MethodNotAllowed"
```

**Comment by lokijota** [comment]
Any update on this?

**Comment by kushagraThapar** [comment]
@lokijota - this is still being investigated. We will provide a fix soon. 
@mbhaskar - can you please share a rough ETA ?
