### ISSUE TITLE
SB teack-2 Remove BinaryData from azure-core-amqp(prep to release next week)

### ISSUE THREAD

**Issue by hemanttanwar** [Azure/azure-sdk-for-java#15835]
Since we need to release AMQP GA in October next week.

And BinaryData need more design work, so we are moving it into service bus temporarily to allow GA for core-amqp, after October release we will design it more and once design is approved for BinaryData, we can more it into core or core-amqp.

**Comment by ramya-rao-a** [comment]
Tasks:
- [ ] Move BinaryData to Azure.Core Experimental
- [ ] Get BinaryData reviewed by the board, and move it to Azure.Core
- [ ] Update Azure Core AMQP to use BinaryData from Azure.Core
- [ ] Update Service Bus to use the above BinaryData in both `body` and `amqpAnnotatedMessage`
