### ISSUE TITLE
Enable SDK Automation for new code generator 

### ISSUE THREAD

**Issue by weshaggard** [Azure/azure-sdk-for-java#15840]
The SDK Automation spec can be found at https://github.com/Azure/azure-rest-api-specs/blob/master/documentation/sdkautomation/sdk_customization.md. 

- [ ] Add [automation configuration](https://github.com/Azure/azure-rest-api-specs/blob/master/specificationRepositoryConfiguration.json) for new code generator in the specs repo 
- [ ] Add new swagger_to_sdk configuration file in the language repo
- [ ] Add generate script (./eng/scripts/generate_sdk) that will implement the [sdk automations spec](https://github.com/Azure/azure-rest-api-specs/blob/master/documentation/sdkautomation/sdk_customization.md).

**Comment by weidongxu-microsoft** [comment]
mgmt already onboarded it about half a year ago https://github.com/Azure/azure-sdk-for-java/blob/main/eng/mgmt/automation/swagger_to_sdk_config.json

**Comment by weidongxu-microsoft** [comment]
TODO: handle date-plane using the current LLC (data-plane) codegen.

**Comment by weidongxu-microsoft** [comment]
Test PR on openapi-env-test
https://github.com/openapi-env-test/azure-rest-api-specs/pull/3002
