### ISSUE TITLE
[BUG] Cannot create subscription on topic using azure-message-servicebus and azure-identity

### ISSUE THREAD

**Issue by aelmanaa** [Azure/azure-sdk-for-java#15889]
**Describe the bug**

1. When trying to create a subscription from my local environment. here is the code:

        
       TokenCredential defaultCredential1 = new DefaultAzureCredentialBuilder().build();

        ServiceBusClientBuilder serviceBusClientBuilder = new ServiceBusClientBuilder().credential(SB_NAME,
                defaultCredential1);

        ServiceBusAdministrationClient serviceBusAdminClient = new ServiceBusAdministrationClientBuilder().credential(SB_NAME,
                defaultCredential1).buildClient();

        serviceBusAdminClient.createSubscription(TOPIC_NAME, "test");`

***Exception or Stack Trace***
Azure Identity => ERROR in getToken() call for scopes [https://xx.servicebus.windows.net/xx/subscriptions/xx?api-version=2017-04]: AADSTS500011: The resource principal named https://xx.servicebus.windows.net/xx/subscriptions was not found in the tenant named xx. This can happen if the application has not been installed by the administrator of the tenant or consented to by any user in the tenant. You might have sent your authentication request to the wrong tenant.

**To Reproduce**

***Code Snippet***
Add the code snippet that causes the issue.

**Expected behavior**

**Screenshots**

**Setup (please complete the following information):**
 - IDE : [e.g. IntelliJ]
 - Version of the Library used

**Additional context**

**Information Checklist**
Kindly make sure that you have added all the following information above and checkoff the required fields otherwise we will treat the issuer as an incomplete report
- [ ] Bug Description Added
- [ ] Repro Steps Added
- [ ] Setup information Added

**Comment by aelmanaa** [comment]
and If I try to create a topic 

serviceBusAdminClient.createTopic("testetest");

I get a different error message:

Exception in thread "main" com.azure.core.exception.ClientAuthenticationException: DefaultAzureCredential authentication failed. ---> VisualStudioCodeCredential authentication failed. Error Details: AADSTS65002: Consent between first party application 'aebc6443-996d-45c2-90f0-388ff96faa56' and first party resource 'xxx' must be configured via preauthorization. Visit https://identitydocs.azurewebsites.net/static/aad/preauthorization.html for details
Trace ID: ca2d9f94-015a-4295-8d95-b3308ea85901

**Comment by joshfree** [comment]
@jianghaolu could you please follow up on the issue @aelmanaa has opened?

**Comment by jianghaolu** [comment]
@aelmanaa 

It seems like the service bus is created in a subscription from another tenant of your account logged in in your VS Code. In other words, your email address used to sign in in VS Code ends in @tenant_a.com while your service bus is owned by another organization @tenant_b.com.

Please confirm if this is the case.

If so, then you can either 1) try setting the environment variable "AZURE_TENANT_ID" to the tenant ID of the service bus's owner organization, that's **if** your account in VS Code has access to this tenant, like as a guest user 2) try logging in VS Code with an account from the same tenant as the service bus.

**Comment by aelmanaa** [comment]
@jianghaolu 

thanks for your response. No I don't agree, the service bus name and the account are in the same tenant. 

There are really weird things going on with the integraiton between TokenCredential and ServiceBusAdminClient.

I'm using the same project on VS code

1.  ServiceBusCLientBuilder works fine. I'm able to receive & send messages to a topic

1. ServiceBusAdministrationClient returns same exception (consent between first party application...). Not able to create a topic, a subscription..ETc. 

have you already tested integraiton between ServiceBusAdministrationClient and TokenCredential ?

**Comment by jianghaolu** [comment]
We do have tests located here for your reference: https://github.com/Azure/azure-sdk-for-java/blob/master/sdk/servicebus/azure-messaging-servicebus/src/test/java/com/azure/messaging/servicebus/administration/ServiceBusAdministrationClientTest.java

If your ServiceBusClient works fine then I think your credentials are valid and authentication is successful. @conniey and @YijunXieMS own the service bus SDK - maybe they can give you some pointers on what you need for ServiceBusAdministrationClient.

**Comment by YijunXieMS** [comment]
@aelmanaa What's the value of `SB_NAME` like?

**Comment by aelmanaa** [comment]
@YijunXieMS 

it contains the fqdn of the service bus:

static final String SB_NAME = "my-servicebus.servicebus.windows.net";


I think,  I might have a clue where the issue is coming from. I've activated the debug log and I noticed that :

- When I send messages to a topic, the oauth2.0 scope which is used is "https://servicebus.azure.net/.default" 

-  When I use the administration client to create a topic , the oauth2.0 scope is "https://my-servicebus.servicebus.windows.net/my-topic?api-version=2017-04"


Hence, I decided to directly use the identity SDK to retrieve a token using a dummy main method (you can replace "INSERT-SCOPE-HERE" by the right scope. Please test both scopes):

```
public static void main(String[] args) throws Exception, ServiceBusException {
		// TODO Auto-generated method stub
        System.out.println("START");
     
         HttpClient cli = new OkHttpAsyncHttpClientBuilder().build();

        TokenCredential defaultCredential = new DefaultAzureCredentialBuilder().httpClient(cli).build();
       

        TokenRequestContext tokenRequestContext = new TokenRequestContext();
		List <String> scopes = new ArrayList<String>();
		scopes.add("INSERT-SCOPE-HERE");
		tokenRequestContext.setScopes(scopes);

		Mono<AccessToken> token = defaultCredential.getToken(tokenRequestContext);
		token.subscribe(
				  value -> System.out.println(value.getToken()), 
				  error -> error.printStackTrace() ,
				  () -> System.out.println("completed without a value")
                );

                Thread.sleep(10000);
            //Print a message
            System.out.println("END");

	}

```
 
you will notice that when you test with:

-  `https://servicebus.azure.net/.default` , it works fine , you will be able to get a token and if you read it on `https://jwt.ms`, you will get the see the right audience in the claims.

- `https://my-servicebus.servicebus.windows.net/my-topic?api-version=2017-04` , azure identity sdk returns the error Consent between first party application...etc"

Are you able to reproduce the error on your side?

**Comment by YijunXieMS** [comment]
@aelmanaa Thanks for your detailed clue. There is a bug that uses the wrong scope. Will fix it in the next release some time in Nov.

**Comment by YijunXieMS** [comment]
@aelmanaa Code is merged to the repo. We'll release next week. It has the fix to this problem.
