### ISSUE TITLE
[BUG] Link to contribution guide is broken

### ISSUE THREAD

**Issue by jmonty42** [Azure/azure-sdk-for-java#15892]
**Describe the bug**
Line 8 of CONTRIBUTING.md links to http://azure.github.com/guidelines.html, which redirects to a 404 page.

***Exception or Stack Trace***
N/A

**To Reproduce**
Follow the link

***Code Snippet***
N/A

**Expected behavior**
Based on other azure projects, I'm assuming this should link to https://opensource.microsoft.com/collaborate.

**Screenshots**
N/A

**Setup (please complete the following information):**
N/A

**Additional context**
N/A

**Information Checklist**
Kindly make sure that you have added all the following information above and checkoff the required fields otherwise we will treat the issuer as an incomplete report
- [X] Bug Description Added
- [X] Repro Steps Added
- [X] Setup information Added

**Comment by sima-zhu** [comment]
We have migrated the link to our root contributing.md. https://github.com/Azure/azure-sdk-for-java/tree/master/sdk/core/azure-core-http-netty#contributing

Let us know if you have further questions. Thanks!
