### ISSUE TITLE
Aggregate reports are no longer being generated

### ISSUE THREAD

**Issue by JonathanGiles** [Azure/azure-sdk-for-java#15923]
The build pipeline was changed back in April in such a way that the aggregate build reports are no longer being generated. This means most of the documentation linked to from [here](https://azuresdkartifacts.blob.core.windows.net/azure-sdk-for-java/index.html) is currently out of date and last updated in April. This page is linked to from the front page of the repo, so it would ideally be continuing to be kept current.

Generally, the issue is that the [aggregate-reports.yml](https://github.com/Azure/azure-sdk-for-java/blob/f92b56c4956222f1ea5e04f02b563bae274b16d2/eng/pipelines/aggregate-reports.yml) file was modified back in April in such a way that the creation of the [Maven site generation step](https://github.com/Azure/azure-sdk-for-java/blame/f92b56c4956222f1ea5e04f02b563bae274b16d2/eng/pipelines/aggregate-reports.yml#L43) was removed. This means now that the only aggregate-reports step that is run actually [specifically skips running](https://github.com/Azure/azure-sdk-for-java/blob/master/eng/pipelines/aggregate-reports.yml#L29) most of the aggregate reporting steps for checkstyle, spotbugs, revapi, and javadoc.

Beyond this, the dependency-checker tooling also appears to no longer be configured properly. The `-Ddependency-checker` command is being applied to the pom.xml file, but the configuration exists in the /sdk/parents/azure-client-sdk-parent/pom.xml file instead. This used to exist in the pom.client.xml file before it was deleted. The end result of this is that there is confusion in the [aggregate reports file](https://github.com/Azure/azure-sdk-for-java/blob/master/eng/pipelines/aggregate-reports.yml#L71) about what a certain file is - that is the dependency checker output that no longer is created.

**Comment by alzimmermsft** [comment]
Discussed in stand-up, this is blocked on an external issue with Jacoco.

**Comment by srnagar** [comment]
Resolving as we now have aggregate reports running successfully.
Latest run: https://dev.azure.com/azure-sdk/internal/_build/results?buildId=1746193&view=results
