### ISSUE TITLE
[FEATURE REQ] Add support for AEAD with AES-GCM

### ISSUE THREAD

**Issue by thomasdarimont** [Azure/azure-sdk-for-java#15922]
**Is your feature request related to a problem? Please describe.**
In customer projects it is quite common to use a modern cryptographic function like AES with GCM in combination with AEAD (Authenticated Encryption with associated data) to add additional authenticated (and integrity protected) data or tags 
alongside the cipher-text to convey the context of the encryption.

The KMS facilities of AWS and GCP both supports AEAD:
AWS: [How to Protect the Integrity of Your Encrypted Data by Using AWS Key Management Service and EncryptionContext](https://aws.amazon.com/de/blogs/security/how-to-protect-the-integrity-of-your-encrypted-data-by-using-aws-key-management-service-and-encryptioncontext/)
GCP: [Cloud Key Management Service: Additional authenticated data](https://cloud.google.com/kms/docs/additional-authenticated-data)

**Describe the solution you'd like**

It would be great to see support for AEAD on Azure SDK for Java in case Azure Key Vault supports AEAD...
Then I'd like to see variants like:
- `AES128_GCM`
- `AES256_GCM`
listed in the `EncryptionAlgorithm` class.

The AAD information could be added via the `Context` parameter with a key like `add`.

The new API could be used like this for encryption:
```
Context context = new Context("aad", associatedData);
EncryptResult encryptionResult = cryptoClient.encrypt(EncryptionAlgorithm.AES128_GCM, plaintext, context);
```
... and for decryption:
```
Context context = new Context("aad", associatedData);
DecryptResult decryptResult = cryptoClient.decrypt(EncryptionAlgorithm.AES128_GCM, ciphertext, context);
```

where `associatedData` is a `byte[]`.

**Describe alternatives you've considered**
Currently one cannot use AEAD with the Azure Java SDK.

**Additional context**

Libraries like google's tink have support for integrating with external KMS systems (GCP, AWS, Android / iOS), see
https://github.com/google/tink/tree/master/java_src/src/main/java/com/google/crypto/tink/integration

**Information Checklist**
Kindly make sure that you have added all the following information above and checkoff the required fields otherwise we will treat the issuer as an incomplete report
- [x] Description Added
- [x] Expected solution specified

**Comment by joshfree** [comment]
Thanks for filing this feature-request on `Key Vault` @thomasdarimont.

@AlexGhiondea can you please include this in your KV planning?

**Comment by vcolin7** [comment]
Added support for AES GCM and AEAD in [4.3.0-beta.3](https://github.com/Azure/azure-sdk-for-java/blob/master/sdk/keyvault/azure-security-keyvault-keys/CHANGELOG.md#430-beta3-2020-11-19) :)
