### ISSUE TITLE
[FEATURE REQ] Add support for container Unique Key policies to azure-spring-data-cosmos

### ISSUE THREAD

**Issue by filipmaelbrancke** [Azure/azure-sdk-for-java#15928]
**Is your feature request related to a problem? Please describe.**
The @Container supports properties like TTL, autoCreation, partitionKeyPath, etc, but seems to be missing options to specify unique key constraints.

**Describe the solution you'd like**
Specifying unique key constraints is available in the underlying com.azure:azure-cosmos:4.6.0 dependency, via com.azure.cosmos.models.UniqueKeyPolicy . Ideally, the azure-spring-data-cosmos sdk exposes unique key constraint options.

**Describe alternatives you've considered**
A possible alternative could be to overwrite the repositoryFactoryBeanClass on @EnableCosmosRepositories, make a custom CosmosRepositoryFactory and a customised SimpleCosmosRepository, where the createContainer methods take unique key policies into account, but I'd prefer it coming out of the box.

**Information Checklist**
Kindly make sure that you have added all the following information above and checkoff the required fields otherwise we will treat the issuer as an incomplete report
- [ x] Description Added
- [x ] Expected solution specified

**Comment by kushagraThapar** [comment]
@mbhaskar  - please follow up on this.

**Comment by kushagraThapar** [comment]
@filipmaelbrancke - this has been implemented and merged, will be released in a couple of weeks in our next release .
