### ISSUE TITLE
compilation error: no suitable method found for authenticate(ApplicationTokenCredentials). It was working till 1.0.0-beta4 version

### ISSUE THREAD

**Issue by amit-dali** [Azure/azure-sdk-for-java#1593]
**Issue** : -
compilation error: no suitable method found for authenticate(ApplicationTokenCredentials). It was working till 1.0.0-beta4 version.

**Code snippet** : - 
Azure azureClient = Azure.configure().withLogLevel(LogLevel.BASIC).authenticate(applicationTokenCredentials).withSubscription(account.getSubscriptionId());

**Above code snippet information** : -
applicationTokenCredentials – is of type com.microsoft.azure.credentials.ApplicationTokenCredentials

**Used java SDK version** – [reference : https://mvnrepository.com/artifact/com.microsoft.azure]
•	azure-client-runtime, azure-keyvault-core and client-runtime are on 1.0.0 (GA)
•	Rest of jars are on 1.0.0-beta5 

https://github.com/Azure/azure-sdk-for-java/blob/master/AUTH.md shows usage of this API
https://github.com/Azure/azure-sdk-for-java/blob/master/notes/prepare-for-1.0.0-beta5.md do not have any information about any change related to this API.

**Comment by jianghaolu** [comment]
Hi @amit-dali 
1.0.0 of runtime doesn't work with beta5 of the SDK. Please update to 1.0 of SDK or use an older version of the runtime.
Thanks!

**Comment by martinsawicki** [comment]
by design as per above comments
