### ISSUE TITLE
Authentication problem - client-id & key

### ISSUE THREAD

**Issue by lukkamor** [Azure/azure-sdk-for-java#1597]
I don't have an app created in my account and I want to use the java API to CRUD resource groups, VMs, etc.  What is the client-id for my username? or what should I put on the credentials auth? UserTokenCredentials asks for client-id, domain, username, password and azureenvironment. If my username is firstname.lastname@mydomain.com how can I create the credential?
I have also tried service principal by using az ad sp create-for-rbac but still I don't know what is the client-id and the key if I don't have an app created.
Thanks!

**Comment by jianghaolu** [comment]
Hi @lukkamor 
`az ad sp create-for-rbac` gives you an AppId - that's the client-id you are looking for.

**Comment by liqiang-fit2cloud** [comment]
so where I can find the key?

**Comment by jianghaolu** [comment]
The key is also called the secret sometimes. I assume the python script worked for you.
