### ISSUE TITLE
[BUG] Fetching compute skus by location from server using filter parameter

### ISSUE THREAD

**Issue by Prudvidhard** [Azure/azure-sdk-for-java#15987]
**Describe the bug**
We want to get skus for single region. We are using below API to get the list. 
Observable<ComputeSku> skus = azureInstance.computeSkus().listbyRegionAndResourceTypeAsync(region, ComputeResourceType.VIRTUALMACHINES);
This API call is fetching skus for all regions from server and filtering skus on client side. Doing this is consuming lot of memory on our server (More than 100mb. Json response itself is 14mb for this API call). 
I see that this listbyRegionAndResourceTypeAsync is making request to "https://management.azure.com/subscriptions/subscriptionId/providers/Microsoft.Compute/skus?api-version=2019-04-01" URL.
According to https://docs.microsoft.com/en-us/rest/api/compute/resourceskus/list this API accepts filter query parameter which fetches data for a location. Why this listbyRegionAndResourceTypeAsync not using filter query parameter? Is there another API in SDK which uses this filter parameter?

***Exception or Stack Trace***
Not applicable

**To Reproduce**

***Code Snippet***
Code snippet mentioned above

**Expected behavior**
We expect to fetch data for single region from server instead of getting data for all regions and filtering on client side.

**Screenshots**

**Setup (please complete the following information):**
 - IDE : [e.g. IntelliJ]
 - Version of the Library used - com.microsoft.azure.azure - 1.33.0

**Additional context**

**Information Checklist**
Kindly make sure that you have added all the following information above and checkoff the required fields otherwise we will treat the issuer as an incomplete report
- [x] Bug Description Added
- [x] Repro Steps Added
- [x] Setup information Added

**Comment by joshfree** [comment]
Thanks for filing this issue @Prudvidhard.  @yungezz could you please assist in routing this github issue?

**Comment by yungezz** [comment]
hi @xccc-msft could you pls have a look? thanks

**Comment by xccc-msft** [comment]
@Prudvidhard You may try below
```
azureInstance.computeSkus().inner().list(filter)
```

**Comment by Prudvidhard** [comment]
Thanks @xccc-msft . Given API is working.
