### ISSUE TITLE
[BUG] azure-spring-boot-starter-servicebus-jms fails to connect

### ISSUE THREAD

**Issue by jonasbark** [Azure/azure-sdk-for-java#15988]
**Describe the bug**
I followed https://docs.microsoft.com/de-de/azure/developer/java/spring-framework/configure-spring-boot-starter-java-app-with-azure-service-bus closely and ended up with the following application properties:
```
spring.jms.servicebus.connection-string=Endpoint=sb://....servicebus.windows.net/;SharedAccessKeyName=...;SharedAccessKey=...;EntityPath=...
spring.jms.servicebus.topic-client-id=keycloak
spring.jms.servicebus.idle-timeout=6000
```

***Exception or Stack Trace***
```
2020-10-06 17:09:41.854  WARN 92963 --- [ync work thread] o.a.q.j.p.failover.FailoverProvider      : Failed to connect after: 30 attempt(s) continuing to retry.
2020-10-06 17:14:47.269  WARN 92963 --- [ync work thread] o.a.q.j.p.failover.FailoverProvider      : Failed to connect after: 40 attempt(s) continuing to retry.
```
No further information is visible.

**To Reproduce**
```

        <dependency>
            <groupId>com.microsoft.azure</groupId>
            <artifactId>azure-servicebus-jms-spring-boot-starter</artifactId>
            <version>2.3.5</version>
        </dependency>

        <dependency>
            <groupId>com.microsoft.azure</groupId>
            <artifactId>azure-servicebus-jms</artifactId>
            <version>0.0.5</version>
        </dependency>
```

***Code Snippet***

```
@EnableJms
@ConfigurationPropertiesScan
class PassAuthenticationApplication(
    private val jmsTemplate: JmsTemplate
) {
    val logger: Logger by LoggerDelegate()

    @PostConstruct
    fun afterConstruct() {
        logger.info("""Constructing complete""")
        jmsTemplate.convertAndSend("pass-sevicebus-d-euwe-10c6dc-user", "Test")

        println("test")
}
}
```

**Expected behavior**
Connection is possible as well as sending out the message

**Setup (please complete the following information):**
 - OS: MacOS
 - IDE : IntelliJ
 - Version of the Library used: 2.3.5

**Additional context**
It's not a firewall. Connecting directly to the topic using 
```
*val sendClient: TopicClient =
            TopicClient(ConnectionStringBuilder(connectionString, "pass-sevicebus-d-euwe-10c6dc-user"))
        sendClient.sendAsync(Message("""{"test":"test"}""".toByteArray()).apply {
            contentType = "application/json"
            label = "Scientist"
            messageId = "1"
            timeToLive = Duration.ofMinutes(2)
        })
```
works fine. This also means that the connection string etc is fine.
I also tried it with a mobile hotspot without success.

**Comment by joshfree** [comment]
@hemanttanwar can you please investigate and follow up with @jonasbark

**Comment by jonasbark** [comment]
I found the issue in an outdated dependency with another spring boot starter:
```
      <dependency>
            <groupId>com.microsoft.azure</groupId>
            <artifactId>azure-keyvault-secrets-spring-boot-starter</artifactId>
            <version>2.3.2</version>
        </dependency>
```
Updating it to 2.3.5 solved the issue. I'm not sure why it would cause the service bus connection to fail.

**Comment by hemanttanwar** [comment]
@jonasbark   Thank you for updating us. Good to know that the problem is solved for you.

**Comment by saragluna** [comment]
@jonasbark thanks for your update. Are you using both the keyvault and the servicebus-jms starter?

**Comment by jonasbark** [comment]
@saragluna yes, I was using both. I actually tried reproducing the 'toxic' combination in a new project but was unable to reproduce the case. Due to many internal dependencies I'm not able to send our pom.xml.

**Comment by saragluna** [comment]
@jonasbark thanks for the update. If multiple azure spring boot modules are consumed at the same time, the recommended way is to include the azure-spring-boot-bom and let the bom to manage the versions of each starter.

Add this dependency management section to your pom file: 
```xml
<dependencyManagement>
    <dependencies>
       <dependency>
          <groupId>com.microsoft.azure</groupId>
          <artifactId>azure-spring-boot-bom</artifactId>
          <version>${azure.version}</version>
          <type>pom</type>
          <scope>import</scope>
       </dependency>
    </dependencies>
</dependencyManagement>
```
And then you could include the dependencies without specifying the version:
```xml
<dependency>
    <groupId>com.microsoft.azure</groupId>
    <artifactId>azure-servicebus-jms-spring-boot-starter</artifactId>
</dependency>
<dependency>
   <groupId>com.azure</groupId>
   <artifactId>azure-spring-boot-starter-keyvault-secrets</artifactId>
</dependency>
```

**Comment by jonasbark** [comment]
Thank you - that's helpful indeed!
