### ISSUE TITLE
BlobNotFound when delete a azure blockedblob

### ISSUE THREAD

**Issue by yiyijin** [Azure/azure-sdk-for-java#16026]
**Query/Question**
requirement: need to delete all blobs starting with the prefix, using async client to list all blobs starting with the prefix, and then delete one by one

```java
PagedFlux<BlobItem> blobItemPagedFlux = blobContainerAsyncClient
      .listBlobs(new ListBlobsOptions().setPrefix(blobPrefix));

    blobItemPagedFlux
      .byPage()
      .subscribe(getConsumerPerItem(), getErrorConsumer(),getCompletedConsumer());
```

and for getConsumerPerItem:
```java
return listResponse -> {
      listResponse.getValue().forEach(blob -> {
        BlockBlobAsyncClient blockBlobAsyncClient = blobContainerAsyncClient
          .getBlobAsyncClient(blob.getName())
          .getBlockBlobAsyncClient();
        try {
          blockBlobAsyncClient.delete().toFuture().get(10, TimeUnit.SECONDS);
        } catch (InterruptedException | ExecutionException | TimeoutException exception) {
          LOG.error("Error deleting blob: {} ", blob.getName(), exception);
        }
      });
    };
```

And I see a lot of
```
java.util.concurrent.ExecutionException: com.azure.storage.blob.models.BlobStorageException: Status code 404, "<?xml version="1.0" encoding="utf-8"?><Error><Code>BlobNotFound</Code><Message>The specified blob does not exist.
```
but when I go to azure portal, I can see the blob(s) present, so wonder if its my code issue or there is a bug?

**Comment by rickle-msft** [comment]
Hi, @yiyijin. Thank you for your question. Your code looks alright to me I think. Can you see any patterns in the blobs that are hitting 404 even though you see they exist in the portal?

**Comment by yiyijin** [comment]
@rickle-msft, Hi Rick, thanks for the prompt response, I do not see any patterns in the blobs, one thing i could think of is: there might be 2 threads all trying to clean up the blob starting with the same prefix, would that be a problem? Thanks a lot!

**Comment by rickle-msft** [comment]
That's a good thought. I don't see anything in your code that would be causing multiple delete requests to be issue to the same destination, but we can test that out. Perhaps try either printing the name of the blob before you call delete and then search for any duplicate entries and/or switching to use the sync client/APIs and see if there is a difference there?

**Comment by yiyijin** [comment]
@rachel-msft, thanks, just a bit more context, so our service is using apache flink (streaming engine), which will periodically take snapshot of the state, and the state is configured to persist to azure blob storage. When the app is stopped, apache flink would clean the blob storage, however, it may not completely clean up it, so that's why I am also writing code to clean the blobs. I am thinking maybe its because both flink and my code are trying to delete the same blobs, causing the problem? Let me try a few things and get back to you, thanks a lot!

**Comment by rickle-msft** [comment]
Ahh. I see. Yes, that does sound like it would cause the exceptions you are seeing. In that case, the recommended pattern is to catch and ignore the 404 exceptions

**Comment by yiyijin** [comment]
@rickle-msft  thanks a lot! I just have one more question, could concurrent deletion cause the blob actually not to be deleted, as what I see is, even though it mentioned the blobs did not exist (404), but it is still present via portal.

**Comment by rickle-msft** [comment]
I don't think concurrent deletes would cause both to fail. I would expect the first would succeed and the second would fail. Are you confident that there was a delete request issued for the blobs you're seeing lingering in your container? Or is it possible that they were somehow skipped or not reached in this processing.

**Comment by yiyijin** [comment]
![image](https://user-images.githubusercontent.com/34106290/95392190-2bac2b00-08ad-11eb-84c3-f246e8a80d35.png)

So I see some blobs are left over, but the size of the blob is 0

**Comment by rickle-msft** [comment]
Can you confirm that a delete request was issued for this blob and that nothing else tried to create it after the delete?

**Comment by yiyijin** [comment]
@rickle-msft  thank you so much for the help! actually based on your thoughts, I identified that it could be the flink processes are not shutdown fully while the blob clean up is in progress, so that means the flink processes could be still uploading to blob storage generating new blobs. I tried to wait until the flink processes fully shutdown, then do the clean up, it seems working fine!

**Comment by rickle-msft** [comment]
@yiyijin that's great! I am happy to hear things are working as desired! I think this issue has been resolved, so I am going to go ahead and close it, but feel free to create a new issue or continue asking questions here if you need further assistance.
