### ISSUE TITLE
Investigate getBodyAsInputStream API for HttpResponse

### ISSUE THREAD

**Issue by alzimmermsft** [Azure/azure-sdk-for-java#16035]
Investigate adding the API `Mono<InputStream> getBodyAsInputStream()` to `HttpResponse`. Currently, in most situations where we need to get an `InputStream` from the `HttpResponse` we'll use the API `Mono<byte[]> getBodyAsByteArray()` then pass that into a `ByteArrayInputStream`. This has the downsides of reading the entire response body into memory eagerly and needing to create a buffer for it. Netty and OkHttp both offer APIs that will return an `InputStream` for the response body and could help eliminate some of the downsides of the current usage pattern. Additionally, this would offer a convenience API for customers who wish to interact with an `InputStream` instead of `byte[]` or `Flux<ByteBuffer>` if they are consuming the `HttpResponse` directly.

**Comment by ganeshbhargav** [comment]
```
import java.net.HttpURLConnection; 
import java.net.URL; 
import java.io.InputStream;
import java.io.BufferedReader; 
import java.io.IOException; 
import java.io.InputStream; 
import java.io.InputStreamReader;
public class Test{
    static String  getText(String url) throws IOException {
        HttpURLConnection connection = (HttpURLConnection) new URL(url).openConnection();
        //add headers to the connection, or check the status if desired..
        
        // handle error response code it occurs
        int responseCode = connection.getResponseCode();
        InputStream inputStream;
        if (200 <= responseCode && responseCode <= 299) {
            inputStream = connection.getInputStream();
        } else {
            inputStream = connection.getErrorStream();
        }
    
        BufferedReader in = new BufferedReader(
            new InputStreamReader(
                inputStream));
    
        StringBuilder response = new StringBuilder();
        String currentLine;
    
        while ((currentLine = in.readLine()) != null) 
            response.append(currentLine);
    
        in.close();
    
        return response.toString();
    }
    
     public static void main(String []args){
        try {
            System.out.println(getText("https://google.com"));
        }
        catch(IOException e){
            e.printStackTrace();
        }
     }
}

```

This code returns the entire url body as a string. It reads the Input stream using a BufferedReader and parses line by line and returns webpage as string.

This could be an alternative solution to using frameworks like Netty if this is the only functionality required.
This could be a more efficient solution than to convert the HttpResponse body to ByteArray and convert to ByteArrayInputStream.

Hope this resolved the issue.

**Comment by JonathanGiles** [comment]
@alzimmermsft Can this be done with ResponseContent?

**Comment by alzimmermsft** [comment]
Yes, this could be done with `RequestContent`.
