### ISSUE TITLE
com.microsoft.azure.management.Azure.resourceGroups().checkExistence("resource-group-name") is not working as expected

### ISSUE THREAD

**Issue by amit-dali** [Azure/azure-sdk-for-java#1605]
**Issue** : -
com.microsoft.azure.management.Azure.resourceGroups().checkExistence("resource-group-name") is returning false even though the resource group exists. It was working till 1.0.0-beta4 version.

**Used java SDK version** – [reference : https://mvnrepository.com/artifact/com.microsoft.azure]
• all arm jars are on 1.0.0-beta5

**Comment by martinsawicki** [comment]
already fixed in master, to be released in v1.0.0 soon.
