### ISSUE TITLE
com.microsoft.azure.management.Azure.deployments().checkExistence() not working as expected

### ISSUE THREAD

**Issue by amit-dali** [Azure/azure-sdk-for-java#1606]
**Issue** : -
com.microsoft.azure.management.Azure.deployments().checkExistence("resource-group-name", "deployment-name") is throwing null pointer exception even though the resource group and deployment exists. It was working till 1.0.0-beta4 version.

**Used java SDK version** – [reference : https://mvnrepository.com/artifact/com.microsoft.azure]
• all arm jars are on 1.0.0-beta5

**Comment by martinsawicki** [comment]
already fixed in master, which will be released as v1.0.0 soon
