### ISSUE TITLE
Single partition queries routing to gateway in direct mode.

### ISSUE THREAD

**Issue by mbhaskar** [Azure/azure-sdk-for-java#16065]
Single partition queries could go to gateway even in direct mode and this needs to be fixed.

**Comment by kirankumarkolli** [comment]
@mbhaskar please qualify on the expectations. 
My understanding is some single-PK need a query plan and has to go-through query plan?

**Comment by kirankumarkolli** [comment]
One possibility is to model them as parameterized queries and cache the plan just for single PK.
