### ISSUE TITLE
Enable Auto Lock renewal on receiver client level

### ISSUE THREAD

**Issue by hemanttanwar** [Azure/azure-sdk-for-java#16071]
Add  Lock renewal on receiver client level.

- LockRenewal Duration :        
   - User can provide LockRenewal Duration 
   - Default to : Duration.Minutes =  5 
-Apply this to both on Sync and Async Client, Could be added at Builder level.
		          
Track1 : Only had in call back model , to renew the lock.

**Comment by ramya-rao-a** [comment]
Closing in favor of #16085
