### ISSUE TITLE
Remove Environment reading from Service Bus

### ISSUE THREAD

**Issue by hemanttanwar** [Azure/azure-sdk-for-java#16077]
- [ ] Remove reading of environment variable for properties which can be set on builder by user. Do not read them from env variables.
  We found this is one of the property 
   As of now user can specify connection in environment variable  `AZURE_SERVICE_BUS_CONNECTION_STRING` and builder will read this
https://github.com/Azure/azure-sdk-for-java/blob/master/sdk/servicebus/azure-messaging-servicebus/src/main/java/com/azure/messaging/servicebus/ServiceBusClientBuilder.java#L338

- [ ] Check for other properties which is read from env variable and remove them.

Since other languages do not have this feature `reading from env variable` , we should not offer as of now for feature parity.

**Comment by YijunXieMS** [comment]
Will remove reading from environment variable `AZURE_SERVICE_BUS_CONNECTION_STRING` from service bus code. All other languages don't read it. But this will make java service bus SDK different from java event hubs, which reads environment variable.
We'll remove it from SB anyway. If someday a user complains we'll consider adding it to SB SDKs of all languages.
@JonathanGiles double confirm with you if you're good with SB and EH being different.

**Comment by JonathanGiles** [comment]
Do other languages read the EH env var, or is it Java only? I am ok with removing as we never discussed enabling this env var, as far as I recall.

**Comment by YijunXieMS** [comment]
Other languages don't read EH env var. Will remove it from SB then.
