### ISSUE TITLE
[FEATURE REQ] Add support ContentResponseOnWrite option per request

### ISSUE THREAD

**Issue by buchizo** [Azure/azure-sdk-for-java#16076]
Currently Java SDK support ContentResponseOnWrite option in CosmosClientBuilder. But that option doesn't configures per request.

I would like to set behavior for content response on write per request. For example, I want to default behavior is false about EnableContentResponseOnWrite option, and specific operation require response.

**Additional context**
relatded: https://devblogs.microsoft.com/cosmosdb/enable-content-response-on-write/#comment-168

**Information Checklist**
- [x] Description Added
- [x] Expected solution specified

**Comment by joshfree** [comment]
@kushagraThapar could you please follow up with @buchizo

**Comment by kushagraThapar** [comment]
@buchizo - thanks for the feature request, this is still in our backlog, will let you know once we plan to implement it.

**Comment by kushagraThapar** [comment]
This is done, and will be released in next azure-cosmos release.
