### ISSUE TITLE
[FEATURE REQ] Automatic lock renewal should be an option on receiver client builder

### ISSUE THREAD

**Issue by ramya-rao-a** [Azure/azure-sdk-for-java#16085]
Today, in the latest preview of v7 of the Service Bus package, there is a method that users need to explicitly call in order to opt into the automatic lock renewal of each message or session.

In the older package, this was possible via an option that was passed to `registerMessageHandler()` and was turned on by default to renew lock for 5 mins.

We should have a similar option in the new package on the receiver builder rather than a method that the user needs to opt into

**Comment by hemanttanwar** [comment]
PR : https://github.com/Azure/azure-sdk-for-java/pull/16183
