### ISSUE TITLE
Do we have any option to register exception listener for getting connection loss error?

### ISSUE THREAD

**Issue by abhikt48** [Azure/azure-sdk-for-java#16194]
At this moment, we will get to know about connection error while calling to any blob operations. We are trying to find any listener which can tell us about connection loss. We need to handle connection loss prior invoking any blob operations. 

Could you please suggest any option to handle connection loss prior calling to any operation? 

**Situation**
1. Establish Azure blob storage connection
2. Perform any operation such as Download, upload 
3. Connectivity loss --> **Which should bubble up error, so we can handle error prior to perform any operation**
4. Perform any operation such as Download, upload

**Comment by alzimmermsft** [comment]
Thanks for submitting this issue @abhikt48.

If an `HttpClient` isn't being configured for the Storage client Netty will be used by default. Netty leverages connection pooling and will re-use open connections to Storage or open new connections if the pool has capacity and an existing connection isn't available. 

The connection pool may fail to provide a connection within a given timeout which would cause Netty to throw a `PoolAcquireTimeoutException`. The connection may also be closed during operation which could cause either a [PrematureCloseException](https://projectreactor.io/docs/netty/release/api/reactor/netty/http/client/PrematureCloseException.html) or an `IOException` if the remote host closes the connection which will bubble up to the calling code.

**Comment by rickle-msft** [comment]
I am going to close this issue as I think the question was answered. Please feel free to reopen it if you have further questions.
