### ISSUE TITLE
How to download blob with URI?

### ISSUE THREAD

**Issue by abhikt48** [Azure/azure-sdk-for-java#16192]
We were using old microsoft SDK `azure-storage:5.5.0` and exploring latest SDK `azure-storage-blob:12.8.0` now as part of migration.

We need to download blow URI. Please find below sample code with old SDK `azure-storage:5.5.0` .

Could you please suggest for new SDK- how can we download blob with URI? 

*** Download blob with URI - OLD SDK***
```
CloudBlockBlob cloudBlockBlob = new CloudBlockBlob(uri);
				cloudBlockBlob.downloadText();
```

**Comment by gapra-msft** [comment]
Hi @abhikt48,

Thanks for posting your question. 

The Java SDK currently provides 3 ways to download a blob from a blobClient. 

1. blobClient.download(OutputStream os) - This downloads the blob into the OuputStream. 
2. blobClient.openInputStream() - This gives you an instance of a BlobInputStream, so you can read the blob using InputStream APIs
3. blobClient.downloadToFile(String filePath) - This downloads a blob to a file.

To build the blobClient, you can use our BlobClientBuilder and specify the URI via the BlobClientBuilder.endpoint method.

Let me know if you have follow up questions, and I'd be happy to answer!

**Comment by abhikt48** [comment]
Hi @gapra-msft  - Thanks a lot for quick reply. I will test tomorrow and let you know.

**Comment by gapra-msft** [comment]
Hi @abhikt48 

Were you able to test the APIs? Just wondering if we can close this issue.

If you have any other questions about the SDK, feel free to open new issues.

**Comment by abhikt48** [comment]
HI @gapra-msft , I was doing implementation and found one comment which bothered us.

In Old SDK, we don't need to define blob name for downloading blob from URI, because blob name is already defined in URI

IN New SDK, **we have to define blob name**. For defining blob name we need to come up with custom logic get blob name from URL. Can't we get `BlobClient` without using blob name? Pleases suggest your opinion.

```
String uri = "https://****.blob.core.windows.net/****container/**blobName*.txt?sv=20**-12-12&ss=***t&srt=o&sp=pw**upx&se=***-09-07T16:**:26Z&st=****-09-07T08:37:26Z&spr=https&sig=****";

BlobContainerClientBuilder blobContainerClientBuilder = new BlobContainerClientBuilder().endpoint(uri);
BlobContainerClient buildClient = blobContainerClientBuilder.buildClient();

//Blob NAme is already defined in URL, so we should't need to define again.
BlobClient blobClient = buildClient.getBlobClient("blobName.txt"); 

BlobInputStream blobInputStream = blobClient.openInputStream();
String downloadedBlob = IOUtils.toString(blobInputStream, StandardCharsets.UTF_8);

LOGGER.info("** Blob '{}' downloaded blob from URI '{}' ***", blobClient.getBlobName(), downloadedBlob);
```

**Comment by gapra-msft** [comment]
Hi @abhikt48 

One thing you could do is use the BlobClientBuilder to build your blob client instead. Then the endpoint method will parse out the blobName for you.

**Comment by abhikt48** [comment]
Hi @gapra-msft 

Tried with below option but getting - `java.lang.NullPointerException: 'blobName' cannot be null.`

Could you please correct me if I am missing anything. 

```
        BlobClientBuilder bcb = new BlobClientBuilder().endpoint(uri);
        BlobClient blobClient = bcb.buildClient();
        BlobInputStream blobInputStream = blobClient.openInputStream();
        String downloadedBlob = IOUtils.toString(blobInputStream, StandardCharsets.UTF_8);
```

**Error**
```
Exception in thread "main" java.lang.NullPointerException: 'blobName' cannot be null.
	at java.util.Objects.requireNonNull(Objects.java:228)
	at com.azure.storage.blob.BlobClientBuilder.buildAsyncClient(BlobClientBuilder.java:113)
	at com.azure.storage.blob.BlobClientBuilder.buildClient(BlobClientBuilder.java:97)
	at com.test.blob.BlobDownloadOperations.downloadBlobFromUri(BlobDownloadOperations.java:67)
	at com.test.blob.BlobDownloadOperations.main(BlobDownloadOperations.java:140)

```

**Comment by gapra-msft** [comment]
Hmm, I tried the following and the there was no error thrown (I made up some of the SAS pieces)

```
        String url = "https://account.blob.core.windows.net/containerName/blobName.txt?sv=2020-12-12&ss=t&srt=o&sp=pwupx&se=2021-09-07T16:00:26Z&st=2020-09-07T08:37:26Z&spr=https&sig=XXXXXX";
        BlobClientBuilder bcb = new BlobClientBuilder().endpoint(url);
        BlobClient blobClient = bcb.buildClient();
```

Are you sure the url is well formed?

Could you try placing a breakpoint in the endpoint method and seeing if we are parsing the blobName out?

**Comment by abhikt48** [comment]
@gapra-msft  Thanks a lot for quick reply. I tested with your URL pattern and it is working fine.. 

The root cause of this issue is **backward slash ( \blobName )** before blobName.txt, 
if I use forward slash "/blobName.txt" then it is working fine. You can test with below url pattern and you can get same error.

As both URL is correct with backward and forward slash, I am not sure this is defect or not. Please suggest your opinion.

`String url = "https://account.blob.core.windows.net/containerName\blobName.txt?sv=2020-12-12&ss=t&srt=o&sp=pwupx&se=2021-09-07T16:00:26Z&st=2020-09-07T08:37:26Z&spr=https&sig=XXXXXX";`

**Comment by gapra-msft** [comment]
@abhikt48 
Based off the RFC [spec](https://tools.ietf.org/html/rfc3986#section-3.3), it looks like only forward slashes are valid path delimiters.

**Comment by abhikt48** [comment]
@gapra-msft  Perfect, thanks for the information.
