### ISSUE TITLE
Suggestion - Update 'setMetadata' method name to 'updateMetadata'

### ISSUE THREAD

**Issue by abhikt48** [Azure/azure-sdk-for-java#16191]
We were using old microsoft SDK `azure-storage:5.5.0` and exploring latest SDK `azure-storage-blob:12.8.0` now as part of migration.

We were using 'setMetadata' operation to set metadata in old SDK. But in latest SDK 'setMetadata' updates the exiting values instead of adding values.

As per user point of view - 'setMetadata' method name misleads for setting the metadata.

I would like to request for updating the method name such as 'updateMetadata' to avoid confusion. Which will be more meaningful from user point of view.

```
BlobClient blobClient = blobContainerClient.getBlobClient(BLOB_NAME);
            Map<String, String> metadata = new HashMap<String, String>();
            metadata.put("FirstName", "ASOS");
          
            blobClient.setMetadata(metadata);
```

**Comment by gapra-msft** [comment]
Hi @abhikt48,

Thanks for your suggestion. Unfortunately, changing the name of an existing API would be a breaking change.

We could, however, update the Javadoc to further clarify the behavior of the method. 

Here is the current Javadoc.
```
Changes a blob's metadata. The specified metadata in this method will replace existing metadata. If old values
must be preserved, they must be downloaded and included in the call to this method.
```

Is there something specific you think isn't quite reflected in it's current form? 

We would be happy to update the Javadoc to clarify the behavior.

**Comment by abhikt48** [comment]
HI @gapra-msft  - Java doc is much clear, i got to know about this form javaDoc itself. However we will get clearity once we deep down in SDK.
I can understand - updating the name would be breaking change. 

Suggestion - Can we deprecate this method and update method name in New SDK ?  Atleast this method will not mislead to new Developer.

What's your opinion?

**Comment by gapra-msft** [comment]
@abhikt48 

We have architectural [guidelines ](https://azure.github.io/azure-sdk/general_design.html#client-interface) we need to follow. 

Based off these, we decided the set prefix is the most appropriate prefix to use for this API.
