### ISSUE TITLE
How to add tags in blob

### ISSUE THREAD

**Issue by abhikt48** [Azure/azure-sdk-for-java#16190]
I tried to add tags in blob but it is throwing error `Value for one of the query parameters specified in the request URI is invalid`

Could you please provide any input to add tags ?

***Exception or Stack Trace***
```
Exception in thread "main" com.azure.storage.blob.models.BlobStorageException: Status code 400, "<?xml version="1.0" encoding="utf-8"?>
<Error><Code>InvalidQueryParameterValue</Code><Message>Value for one of the query parameters specified in the request URI is invalid.
RequestId:eea984f9-201e-0069-4db4-a00f62000000
Time:2020-10-12T16:28:47.7038621Z</Message><QueryParameterName>comp</QueryParameterName><QueryParameterValue>tags</QueryParameterValue></Error>"
```

**To Reproduce**
Execute below code with valid BlobContainerClient

***Code Snippet***
 ```
BlobClient blobClient = getBlobContainerClient().getBlobClient(BLOB_NAME);
        
        Map<String, String> tags = new HashMap<String, String>();
        tags.put("Dept", "Finance");
        tags.put("Status", "Normal");
        blobClient.setTags(tags);

        blobClient.uploadWithResponse(new ByteArrayInputStream(TEST_MESSAGE.getBytes()), TEST_MESSAGE.length(), null, null, null, null, null, null, null);
```

**Expected behavior**
Tags should be added in blob.

**Setup (please complete the following information):**
 - OS: Windows 10
 - IDE : Eclipse based
 - Version of the Library used - azure-storage-blob:12.8.0

**Comment by gapra-msft** [comment]
Hi @abhikt48 

Blob tags is currently in public preview, so it is only available in limited [regions](https://docs.microsoft.com/en-us/azure/storage/blobs/storage-manage-find-blobs?tabs=azure-portal#regional-availability-and-storage-account-support).

If you create an account in one of the supported regions, the tags related APIs should work.

**Comment by abhikt48** [comment]
@gapra-msft - Thanks a lot for quick response.
