### ISSUE TITLE
[Query] Blob Batch - upload blobs in batch mode

### ISSUE THREAD

**Issue by abhikt48** [Azure/azure-sdk-for-java#16240]
Do we have any option to upload blobs in batch mode ?

**Comment by gapra-msft** [comment]
Hi @abhikt48,

Thanks for your question. The [service](https://docs.microsoft.com/en-us/rest/api/storageservices/blob-batch) currently only support delete blob and set blob tier for batch support.

**Comment by gapra-msft** [comment]
@abhikt48, Thanks for the suggestion. We will take this request under consideration, but it is unlikely that we will add this feature in the near future.

**Comment by abhikt48** [comment]
@gapra-msft  - No problem, we can wait for some time. Please let us know once this feature available, so we can test and plan accordingly.

**Comment by seanmcc-msft** [comment]
@abhikt48, this is a non-trivial service feature request, and it is very unlikely this feature will become available in the near or medium term.

**Comment by abhikt48** [comment]
@gapra-msft  @seankane-msft  -  I checked APIs today and got to know that blob-batch api is already available. Is that possible for you to provide this functionality now?

https://docs.microsoft.com/en-gb/rest/api/storageservices/blob-batch

**Comment by gapra-msft** [comment]
@abhikt48 - As stated before blob batch is only supported for setBlobTier and deleteBlob. 
This API supports two types of subrequests: SetBlobTier for block blobs and DeleteBlob.

**Comment by abhikt48** [comment]
@gapra-msft  Oh ok, sorry my bad. Thanks for information.

**Comment by gapra-msft** [comment]
@abhikt48 

I am going to go ahead and close this issue as we do not generally track service feature requests in this repo.
