### ISSUE TITLE
Unable to set hostname for certificate

### ISSUE THREAD

**Issue by jkubrynski** [Azure/azure-sdk-for-java#1625]
Currently on `com.microsoft.azure.management.appserviceAppServiceCertificate` there is no way of setting the hostname, as `withHostNames` is available only on `com.microsoft.azure.management.appservice.implementation.CertificateInner`

**Comment by jianghaolu** [comment]
This is by design. An app service certificate is bound to one hostname and is immutable. Changing its hostname will invalidate the certificate. You need to create a new certificate for this new hostname.

**Comment by jkubrynski** [comment]
So why there is a List of hostnames while it should always be bound to the single one?

**Comment by jianghaolu** [comment]
Most of the certificates we deal with today only contain one hostname. There are, however, certificates that can be bound to many hostnames but they are also immutable.

**Comment by jianghaolu** [comment]
https://www.godaddy.com/help/what-is-a-multiple-domain-ucc-ssl-certificate-3908

**Comment by martinsawicki** [comment]
closing as by design per above discussion
