### ISSUE TITLE
AzureServiceClient MAC_ADDRESS_HASH throws NPE on OSX (and possibly Linux)

### ISSUE THREAD

**Issue by vincentdo** [Azure/azure-sdk-for-java#1627]
```java
static {
        OS = System.getProperty("os.name") + "/" + System.getProperty("os.version");
        try {
            MAC_ADDRESS_HASH = Hashing.sha256().hashBytes(NetworkInterface.getByInetAddress(InetAddress.getLocalHost()).getHardwareAddress());
        } catch (SocketException | UnknownHostException e) {
            throw new RuntimeException(e);
        }
    }
```
Attached is the static initializer found in AzureServiceClient.java in the 1.0.0 release of the SDK. The portion `NetworkInterface.getByInetAddress(InetAddress.getLocalHost()).getHardwareAddress()` will return null because it's doing a MAC address look up on a loopback interface which will cause `hashBytes` to throw a NPE. This cause the SDK to be unusable because you can't instantiate a client.

It's likely to be the same situation on Linux since on both system, 127.0.0.1 is bound to the loopback interface which has no MAC address.

**Comment by jianghaolu** [comment]
This has been mitigated with 1.0.2 version of `azure-client-runtime`. Using that should get you unblocked while we are still working on a better mechanism.

**Comment by martinsawicki** [comment]
fixed in the latest SDk/runtime
