### ISSUE TITLE
[QUERY] target for GA of azure-data-tables:12.0.0-beta.2 ?

### ISSUE THREAD

**Issue by abhikt48** [Azure/azure-sdk-for-java#16294]
Do we have any deadline for GA of azure-data-tables:12.0.0-beta.2 ? Could you please share some timeline, so we can plan accordingly?

**Comment by bsiegel** [comment]
Hey @abhikt48, I'm not sure we have a firm date at this time but I would expect to see a GA release probably in Q1 of next year (I'm hoping early in Q1, but the schedule is still in flux).
