### ISSUE TITLE
Keyvault client block a thread when shutting down

### ISSUE THREAD

**Issue by epot** [Azure/azure-sdk-for-java#1631]
I have the following code:

    val client = new KeyVaultClient(new KeyVaultClientCredentials(applicationId, password))
    client.setSecret(new SetSecretRequest.Builder("https://test.vault.azure.net/", "coin", "slip").build())

that throws an exception because my app does not have the correct permission. That is fine but the problem is that the process never exits because a thread created by the KeyVaultClient never terminates. Is there a way to close everything if an exception is thrown ?

**Comment by martinsawicki** [comment]
@jianghaolu - to be moved to the new keyvault SDK repo - sounds like they need to update the runtime

**Comment by praries880** [comment]
@jianghaolu  is this issue fixed?

**Comment by Petermarcu** [comment]
@g2vinay Can you see if this is true still in Track2? Should this be a test case we add or do we already cover the "permission denied" error in our testing?

**Comment by g2vinay** [comment]
@epot 
We've shipped next gen KV SDKs, the v4.x azure-security-keyvault-* libraries are the latest supported SDK libraries for KeyVault. These libraries don't have this issue in the runtime. We do recommend upgrading to this latest stable, supported release. Packages and more information can be found here:

https://github.com/Azure/azure-sdk-for-java/tree/master/sdk/keyvault/azure-security-keyvault-secrets
https://github.com/Azure/azure-sdk-for-java/blob/master/sdk/keyvault/azure-security-keyvault-keys
https://github.com/Azure/azure-sdk-for-java/tree/master/sdk/keyvault/azure-security-keyvault-certificates
