### ISSUE TITLE
[BUG] Azure Table - New SDK - createEntityWithResponse throws NullPointerException in absense of timeout and context

### ISSUE THREAD

**Issue by abhikt48** [Azure/azure-sdk-for-java#16386]
**Describe the bug**
`createEntityWithResponse(entity, null, null)` throwing NullPointerException in absense of timeout and context. Timeout and context should have default value which will not cause NullPointerException.

***Exception or Stack Trace***
```
Exception in thread "main" java.lang.NullPointerException
	at reactor.core.publisher.Mono.block(Mono.java:1704)
	at com.azure.data.tables.TableClient.createEntityWithResponse(TableClient.java:151)
	at com.table.TableUtils.main(TableUtils.java:39)
```

**To Reproduce**
Execute below code with valid credential and tableName

***Code Snippet***
```
TableClient  tableClient = new TableClientBuilder()
                                .endpoint(TABLE_SAS)
                                .tableName(TABLE_NAME)
                                .buildClient();
								
TableEntity entity = new TableEntity(PARTITION_KEY, UUID.randomUUID().toString());
        entity.addProperty("name", "tesr");
        
tableClient.createEntityWithResponse(entity, null, null);
```

**Expected behavior**
Entity should be created successfully

**Setup (please complete the following information):**
 - OS: windows
 - IDE : Eclipse based
 - Version of the Library used - `azure-data-tables:12.0.0-beta.2`

**Comment by bsiegel** [comment]
Hi @abhikt48, indeed the synchronous client methods that take a `timeout` parameter do not let you omit that parameter. Passing `null` here will produce the exception you described. Will fix, these methods should permit you to pass null to block indefinitely.

**Comment by bsiegel** [comment]
When fixing this bug we should also ensure that users can pass a null `context` - currently that shouldn't break anything but it would be better to default it to `Context.NONE`.
