### ISSUE TITLE
[BUG] Azure Datalake Gen2 Java SDK FileClient sometimes appends lines of `0x00`s

### ISSUE THREAD

**Issue by vida-bandara-by** [Azure/azure-sdk-for-java#16387]
We have an application that appends a couple of hundred lines over a period of five minutes to a file in Azure Gen2 Datalake. The below code simulates the application.
We noticed that sometimes, a line of `0x00`s written to the file instead of the text. No errors thrown.
```
public class AdlAppender {

    private static final String datalake = "<<datalake-name>>";
    private static final String url = "https://<<datalake-name>>.dfs.core.windows.net";
    private static final String key = "<<access-key>>";
    private static final String container = "<<container-name>>";
    private static final String fileName = "<<file-path>>";

    final DataLakeFileClient fileClient;

    public AdlAppender() {
        final StorageSharedKeyCredential credential = new StorageSharedKeyCredential(datalake, key);

        final DataLakeServiceClient dataLakeServiceClient = new DataLakeServiceClientBuilder()
            .endpoint(url)
            .credential(credential)
            .buildClient();

        final DataLakeFileSystemClient fileSystemClient = dataLakeServiceClient.getFileSystemClient(container);

        fileClient = fileSystemClient.createFile(fileName);
    }

    public long append(final String content, final long offset) {
        final byte[] bytes = content.getBytes(StandardCharsets.UTF_8);
        final int length = bytes.length;
        final ByteArrayInputStream inputStream = new ByteArrayInputStream(bytes);

        fileClient.append(inputStream, offset, length);

        final long updatedOffset = offset + length;
        fileClient.flush(updatedOffset);

        return updatedOffset;
    }
}
```
```
public class AdlAppenderTest {

    @Test
    public void testAppendFile() throws InterruptedException {
        final AdlAppender adlAppender = new AdlAppender();
        final String content = "The quick brown fox jumps over the lazy dog\n";
        final int size = content.length();
        long offset = 0;

        final int numLines = 200;
        final int duration = 5;
        for (int i = 1; i <= numLines; i++) {
            offset = adlAppender.append(content, offset);
            assert offset == size * i;

            Thread.sleep(duration * 60 * 1000 / numLines);
        }
    }
}
```

**Comment by gauriprasad** [comment]
Hi @vida-bandara-by 

Thank you for reporting this issue. I will take a look into what might be causing this issue. 

Could you share the version of azure-storage-file-datalake you are using?

**Comment by gapra-msft** [comment]
Hi @vida-bandara-by

Thank you for reporting this issue. I will take a look into what might be causing this issue.

Could you share the version of azure-storage-file-datalake you are using?

**Comment by gapra-msft** [comment]
Could you also share how you notice that a line of 0x00s are getting appended to the file? Do you have code somewhere that checks by download the file or are you visually inspecting on azure portal?

**Comment by vida-bandara-by** [comment]
Thank you very much @gapra-msft for looking into this.

The gradle dependency line:
`compile group: 'com.azure', name: 'azure-storage-file-datalake', version: '12.1.1'`

`0x00` is visible in Azure portal as well as in the downloaded file:
```
$ xxd -c 44 foo.file
00000000: 5468 6520 7175 6963 6b20 6272 6f77 6e20 666f 7820 6a75 6d70 7320 6f76 6572 2074 6865 206c 617a 7920 646f 670a  The quick brown fox jumps over the lazy dog.
0000002c: 5468 6520 7175 6963 6b20 6272 6f77 6e20 666f 7820 6a75 6d70 7320 6f76 6572 2074 6865 206c 617a 7920 646f 670a  The quick brown fox jumps over the lazy dog.
00000058: 5468 6520 7175 6963 6b20 6272 6f77 6e20 666f 7820 6a75 6d70 7320 6f76 6572 2074 6865 206c 617a 7920 646f 670a  The quick brown fox jumps over the lazy dog.
00000084: 0000 0000 0000 0000 0000 0000 0000 0000 0000 0000 0000 0000 0000 0000 0000 0000 0000 0000 0000 0000 0000 0000  ............................................
000000b0: 5468 6520 7175 6963 6b20 6272 6f77 6e20 666f 7820 6a75 6d70 7320 6f76 6572 2074 6865 206c 617a 7920 646f 670a  The quick brown fox jumps over the lazy dog.
000000dc: 5468 6520 7175 6963 6b20 6272 6f77 6e20 666f 7820 6a75 6d70 7320 6f76 6572 2074 6865 206c 617a 7920 646f 670a  The quick brown fox jumps over the lazy dog.
```

**Comment by gapra-msft** [comment]
Hi @vida-bandara-by 

I ran your repro with the version you specified and I was able to repro the issue. 

I suspect the issue is due to bad retry behavior in that version of datalake and before. We have since [fixed](https://github.com/Azure/azure-sdk-for-java/pull/11677) the issue. 

Could you please try using azure-storage-file-datalake version 12.1.2+ so you can pick up the fix?

Thanks

**Comment by vida-bandara-by** [comment]
Thank you @gapra-msft ! Will update to the new version.

**Comment by gapra-msft** [comment]
Hi @vida-bandara-by 

Are you still seeing this issue? Feel free to close the issue once you've confirmed the fix!

**Comment by vida-bandara-by** [comment]
Hi @gapra-msft , we rolled out the new version. Please allow me to watch it for a few days and then close the issue. Thank you again for your help with this matter!

**Comment by vida-bandara-by** [comment]
We updated the version and observed for a week. Did not see the issue again. Thank you @gapra-msft ! Closing the issue.
