### ISSUE TITLE
[FEATURE REQ] Create an example for how to migration from v8 LocationMode to v12

### ISSUE THREAD

**Issue by josuemb** [Azure/azure-sdk-for-java#16419]
**Is your feature request related to a problem? Please describe.**
No is not, is more like a helpful request.

**Describe the solution you'd like**
A working sample (source code) to use RequestRetryPolicy for doig something like retrying between regions using GRS/GZRS.

**Describe alternatives you've considered**
Creating a new sample.

**Additional context**
Something very similar to https://github.com/Azure-Samples/storage-dotnet-circuit-breaker-ha-ra-grs but using current SDK version (Java version is what I am ideally looking for).

**Information Checklist**
Kindly make sure that you have added all the following information above and checkoff the required fields otherwise we will treat the issuer as an incomplete report
- [x] Description Added
- [x] Expected solution specified

**Comment by rickle-msft** [comment]
Thank you, @josuemb. We'll work on adding some more documentation around this feature!
