### ISSUE TITLE
On a VM osDiskStorageAccountType() always returns null

### ISSUE THREAD

**Issue by ImranBijapuri** [Azure/azure-sdk-for-java#1642]

**Comment by anuchandy** [comment]
osDiskStorageAccountType() is not available for un-managed (native) disk i.e. for virtual machines created with the wither `withUnmanagedDisk()`.

If the virtual machine is created based on managed disk (which is the default path)  then you should be able to get the account type with this getter.

Can you please check whether your virtual machine is based on managed or unmanaged disk? you can check this using `virtualMachine.isManagedDiskEnabled();` getter.

**Comment by anuchandy** [comment]
@ImranBijapuri we have addressed the issue, hence closing it. Feel free to reopen and comment if you still have question.
