### ISSUE TITLE
[QUERY] ServiceBus - Scope of new SDK azure-messaging-servicebus

### ISSUE THREAD

**Issue by abhikt48** [Azure/azure-sdk-for-java#16455]
We are using `azure-servicebus:1.2.11` for serviceBus operation. We need to upgrade latest version of serviceBus to `azure-servicebus:3.3.0`. But i can see that you guyz are developing new serviceBus SDK - `azure-messaging-servicebus:7.0.0-beta.6`.

Do we have any target date for GA of `azure-messaging-servicebus:7.0.0-beta.6` ?
Are you guyz going to deprecate old SDK  `azure-servicebus:3.3.0` ?

Please suggest your opinion on above queries. So we can plan accordingly for migration.

**Comment by abhikt48** [comment]
Hi Team, 

Could you please suggest your opinion on above query?

Regards,
Abhishek Kumar

**Comment by abhikt48** [comment]
Hi Team,

Could you please suggest your opinion on above query? We need to take a call for upgrade. It will be great if you can throw some light on this, so we can plan accordingly.

Regards,
Abhishek Kumar

**Comment by hemanttanwar** [comment]
@abhikt48  I want to update you that ,service bus GA 7.0.0 is released few days ago.

**Comment by hemanttanwar** [comment]
We are not planning to deprecate old SDK azure-servicebus:3.x.x anytime soon. 
But we do encourage customers to use newer library 7.x.x.

**Comment by abhikt48** [comment]
@hemanttanwar  - Thanks for confirmation !!
