### ISSUE TITLE
[BUG] Queue - updateMessage - NullPointerException in the absence of Duration

### ISSUE THREAD

**Issue by abhikt48** [Azure/azure-sdk-for-java#16453]
**Describe the bug**
`updateMessage `throwing NullPointerException in the absence of `Duration`. It should use default Duration.

***Exception or Stack Trace***
```
Exception in thread "main" java.lang.NullPointerException
	at com.azure.storage.queue.QueueAsyncClient.updateMessageWithResponse(QueueAsyncClient.java:837)
	at com.azure.storage.queue.QueueClient.updateMessageWithResponse(QueueClient.java:628)
	at com.azure.storage.queue.QueueClient.updateMessage(QueueClient.java:595)
	at com.queue.QueueOperations.updateMessage(QueueOperations.java:53)
	at com.queue.QueueOperations.main(QueueOperations.java:67)
```
**To Reproduce**
Execute below code with valid QueueClient

***Code Snippet***
`UpdateMessageResult updateMessageResult = getQueueClient().updateMessage(queueMessageItem.getMessageId(), queueMessageItem.getPopReceipt(), "Updated Message", null);`

**Expected behavior**
Message should be updated successfully with null `Duration`.

**Setup (please complete the following information):**
 - OS: Windows 10
 - IDE : Eclipse based
 - Version of the Library used - azure-storage-queue:12.6.0

**Comment by gapra-msft** [comment]
Hi @abhikt48 

Thank you for posting this issue. 

I believe the visibilityTimeout is a required parameter, so the expectation is that the user provides the variable.

The [service](https://docs.microsoft.com/en-us/rest/api/storageservices/update-message#uri-parameters) does not seem to default to any specific value.

**Comment by abhikt48** [comment]
As per SDK it is mandatory. I think it should be optional as it is working fine with `Duration.ZERO`. 

Can you accept it as feature request to make optional?

**Comment by gapra-msft** [comment]
@abhikt48 Thanks for the suggestion, I'll discuss this with my colleagues and let you know if we can make this change.

**Comment by gapra-msft** [comment]
@abhikt48 Synced with my colleagues and it looks like we will add support to default to 0. 

Thanks for bringing this issue to our attention.
