### ISSUE TITLE
Not able to create a windows VM with 1.0.0 sdk

### ISSUE THREAD

**Issue by mileychen** [Azure/azure-sdk-for-java#1645]
Hi,

I am not able to create a windows VM with 1.0.0 Java sdk, getting the error information like below:

Exception in thread "main" com.microsoft.azure.CloudException: Managed Disks are not supported in this region.: Managed Disks are not supported in this region.
	at com.microsoft.azure.AzureClient.createExceptionFromResponse(AzureClient.java:594)
	at com.microsoft.azure.AzureClient.access$000(AzureClient.java:33)
	at com.microsoft.azure.AzureClient$1.call(AzureClient.java:138)
	at com.microsoft.azure.AzureClient$1.call(AzureClient.java:135)
	at rx.internal.operators.OnSubscribeMap$MapSubscriber.onNext(OnSubscribeMap.java:69)
	at retrofit2.adapter.rxjava.RxJavaCallAdapterFactory$RequestArbiter.request(RxJavaCallAdapterFactory.java:173)
	at rx.Subscriber.setProducer(Subscriber.java:211)

code pieces like:
createWindows(String resourceGroupName, String vmName, String vmStorageAccountName, String vmUserName,String vmPassword, KnownWindowsVirtualMachineImage vmImage, Region vmRegion, VirtualMachineSizeTypes vmSize)

however, if I use same code with 1.0.0-beta 3 Java sdk, I can create a windows VM successfully.  
could you help to figure out where goes wrong? BTW, I am using azure China Environment.

**Comment by anuchandy** [comment]
@mileychen virtual machine created using 1.0.0-beta3 uses storage account based (OS and Data) disk but later compute service team introduced managed disks and the library was updated to use managed disk based OS and Data disks as default for virtual machine. It looks like your specific  region in China does not have support for managed disk, so you need to switch to storage account based virtual machine, this is achieved by choosing `withUnmanagedDisks()` in the virtual machine definition, refer [this](https://github.com/Azure-Samples/compute-java-manage-virtual-machine-with-unmanaged-disks/blob/master/src/main/java/com/microsoft/azure/management/compute/samples/ManageVirtualMachineWithUnmanagedDisks.java#L72) sample.

**Comment by mileychen** [comment]
@anuchandy  thank you for your quick response, and your workaround works from my side.
just another quick questions:
May I know the latest azure sdk which is supported on China Region?
we notice there have 2016-09-01/2016-12-01/2016-04-30 on 1.0.0 version, but some of the functions are not supported on China Region. Many customer from China are eager to know when these functions are available in China. Do we have any plan about this ?

**Comment by anuchandy** [comment]
@mileychen I have asked compute+managed disk team about their plan to have full support on all China regions, will update here once we get a response.

**Comment by mileychen** [comment]
@anuchandy thanks for your effort!

**Comment by anuchandy** [comment]
Based on the response from managed disk team, the feature will be deployed to China cloud by June end or early July.

**Comment by anuchandy** [comment]
Closing this - managed disk is planned to deploy by June end or early July.
