### ISSUE TITLE
[QUERY] Query - New SDK - get depth of queue

### ISSUE THREAD

**Issue by abhikt48** [Azure/azure-sdk-for-java#16454]
We have requirement to know depth of Queue. Do we have any option to get depth of the queue?

**Comment by gapra-msft** [comment]
Hi @abhikt48 

Thank you for posting your question. 

In the azure-storage-queue library you can call queueClient.getProperties().getApproximateMessagesCount() to gets the approximate number of messages contained in the queue at the time of properties retrieval.

Hope this helps!

**Comment by abhikt48** [comment]
@gapra-msft  - Thanks a lot for quick update.
