### ISSUE TITLE
Add usage location #1491. Changes removed from the master

### ISSUE THREAD

**Issue by dviru** [Azure/azure-sdk-for-java#1651]
This fix was there in the master. but after some time someone over written. please let me know is it possible to bring these changes to master.

**Comment by martinsawicki** [comment]
@jianghaolu since the file that fix went into is auto-gen'd, I guess the proper fix that should go into the Swagger spec has not yet been put in there, and I guess we've re-generated the Inners without it. Are we PRing the proper fix into the Swagger?

**Comment by jianghaolu** [comment]
Seems like they are overwritten. I'll create a pull request to the Swagger specs.

**Comment by jianghaolu** [comment]
Fixed via https://github.com/Azure/azure-sdk-for-java/pull/1676.
