### ISSUE TITLE
Retry policy for queue triggered Azure functions

### ISSUE THREAD

**Issue by casper-79** [Azure/azure-sdk-for-java#16512]
**Query/Question**
Hi

I am assigned the task of configuring a custom retry policy for our queue triggered Azure functions, with the aim of becoming resilient to temporary errors. I started by configuring an exponential backoff policy in the ARM template of the queue itself, but much to my surprise this does not appear to have any effect on the function execution. It appears Azure functions consume messages independently of the settings on the queue, which means a failed message is retried immediately without giving the underlying services a chance to recover from temporary issues.

I have come across a 3 year old Github post which suggest Azure functions does not provide means for configuring the retry policy: Azure/azure-functions-host#2192. I was much surprised by this finding, since this feature is so vital/fundamental that I would naturally assume Azure functions to provide a solution.

I have been unable to find any documentation on the topic other than the github post mentioned above. Can you confirm that Azure functions still does not provide a configurable retry policy or point me in the direction of relevant documentation?

***Why is this not a Bug or a feature Request?***
This might be a bug or a feature request, but I have no way of knowing since I am unable to find documentation on how retries are supposed to work.

**Setup (please complete the following information if applicable):**
Java Azure functions, runtime 3.0
 
 **Information Checklist**
 Kindly make sure that you have added all the following information above and checkoff the required fields otherwise we will treat the issuer as an incomplete report
- [x] Query Added
- [x] Setup information Added

**Comment by joshfree** [comment]
Hi @casper-79, this question may be best routed to the azure/azure-functions-java-library repo; It looks like the owners are @pragnagopa and @amamounelsayed.

**Comment by casper-79** [comment]
Hi @pragnagopa and @amamounelsayed

I am not sure whether this case has now been routed to you, or if there is anything I should do?

**Comment by pragnagopa** [comment]
We recently added retry feature. Updates to Azure Functions Java library are tracked here: https://github.com/Azure/azure-functions-java-library/issues/132 

Please close this issue.
