### ISSUE TITLE
Beta 4: A retryable error has occurred. 

### ISSUE THREAD

**Issue by nwarriorch** [Azure/azure-sdk-for-java#1652]
I frequently am receiving this error while VM creation. "A retriable error has occurred". I am not sure what the cause of this error is. I am creating a VM and attaching an NSG to it. 

Stack Trace:

`11 May 2017 06:26:14,524 ERROR ~ A retryable error occured.
 15078 11 May 2017 06:26:14,525 ERROR ~ com.microsoft.azure.CloudException: A retryable error occured.: A retryable error occured.
 15079         at com.microsoft.azure.AzureClient.createExceptionFromResponse(AzureClient.java:524)
 15080         at com.microsoft.azure.AzureClient.access$000(AzureClient.java:33)
 15081         at com.microsoft.azure.AzureClient$1.call(AzureClient.java:132)
 15082         at com.microsoft.azure.AzureClient$1.call(AzureClient.java:129)
 15083         at rx.internal.operators.OnSubscribeMap$MapSubscriber.onNext(OnSubscribeMap.java:69)
 15084         at retrofit2.adapter.rxjava.RxJavaCallAdapterFactory$RequestArbiter.request(RxJavaCallAdapterFactory.java:173)
 15085         at rx.Subscriber.setProducer(Subscriber.java:211)
 15086         at rx.internal.operators.OnSubscribeMap$MapSubscriber.setProducer(OnSubscribeMap.java:102)
 15087         at retrofit2.adapter.rxjava.RxJavaCallAdapterFactory$CallOnSubscribe.call(RxJavaCallAdapterFactory.java:152)
 15088         at retrofit2.adapter.rxjava.RxJavaCallAdapterFactory$CallOnSubscribe.call(RxJavaCallAdapterFactory.java:138)
 15089         at rx.Observable.unsafeSubscribe(Observable.java:9861)
 15090         at rx.internal.operators.OnSubscribeMap.call(OnSubscribeMap.java:48)
 15091         at rx.internal.operators.OnSubscribeMap.call(OnSubscribeMap.java:33)
 15092         at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:48)
 15093         at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:30)
 15094         at rx.Observable.unsafeSubscribe(Observable.java:9861)
 15095         at rx.internal.operators.OnSubscribeMap.call(OnSubscribeMap.java:48)
 15096         at rx.internal.operators.OnSubscribeMap.call(OnSubscribeMap.java:33)
 15097         at rx.Observable.unsafeSubscribe(Observable.java:9861)
 15098         at rx.internal.operators.OnSubscribeMap.call(OnSubscribeMap.java:48)
 15099         at rx.internal.operators.OnSubscribeMap.call(OnSubscribeMap.java:33)
 15100         at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:48)
 15101         at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:30)
 15102         at rx.Observable.unsafeSubscribe(Observable.java:9861)
 15103         at rx.internal.operators.OperatorSubscribeOn$1.call(OperatorSubscribeOn.java:94)
 15104         at rx.internal.schedulers.CachedThreadScheduler$EventLoopWorker$1.call(CachedThreadScheduler.java:221)
 15105         at rx.internal.schedulers.ScheduledAction.run(ScheduledAction.java:55)
 15106         at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
 15107         at java.util.concurrent.FutureTask.run(FutureTask.java:266)
 15108         at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
 15109         at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
 15110         at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
 15111         at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
 15112         at java.lang.Thread.run(Thread.java:745)`

**Comment by anuchandy** [comment]
@nwarriorch could you share full repro code?

**Comment by nwarriorch** [comment]
The following code runs in parallel.  

linuxVM =      azure.virtualMachines().define(name)
                        .withRegion(region)
                        .withExistingResourceGroup(group)
                        .withExistingPrimaryNetwork(vnet)
                        .withSubnet(subnet)
                        .withPrimaryPrivateIpAddressDynamic()
                        .withExistingPrimaryPublicIpAddress(publicIPAddress)
                        .withLatestLinuxImage(imagePublisher, imageOffer , imageSKU)
                        .withRootUsername(user)
                        .withSsh(publickey)
                        .withCustomData("some data")
                        .withSize(size)
                        .withExistingAvailabilitySet(currentAvailSet)
                        .withExistingStorageAccount(account)
                        .withOsDiskVhdLocation(location)
                        .create();

// where the error seems to be originating from. 
NetworkSecurityGroup nsg = azure.networkSecurityGroups().getById(securityGroupId);
linuxVM.getPrimaryNetworkInterface().update().withExistingNetworkSecurityGroup(nsg).apply();

**Comment by anuchandy** [comment]
Thanks so service is throwing exception when you try to associate a NSG with existing network interface given that NIC is associated with VM.

Need one clarification - what do you meant by "The following code runs in parallel."?

**Comment by nwarriorch** [comment]
This isn't an issue all the time, every once in a while the exception that we see is thrown. 

When creating multiple VM's , the above code is run parallelly spinning up multiple instances. Not sure if that would be an issue. 

>Thanks so service is throwing exception when you try to associate a NSG with existing network interface given that NIC is associated with VM.

I was under the impression that attaching an NSG to a NIC that is being used is allowed in azure?

**Comment by nwarriorch** [comment]
The frequency seems to have increased. I am hitting it more frequently now.

**Comment by anuchandy** [comment]
Ok, this looks like a NRP service issue when it receives concurrent request to associate single instance of NSG with multiple network interfaces those are attached to VMs. We need service team help to investigate this further. Can you turn the full logs on and try to repro this again. Please share the full log that includes failure message, correlation id and operation time.

**Comment by nwarriorch** [comment]
Yep. It looked like it was a concurrency issue. Solved it by synchronization.

**Comment by ihorman** [comment]
I have the same issue, could you please provide me the workaround you used to overcome the problem?
