### ISSUE TITLE
For-ever-loop - async receiveMessages never stops

### ISSUE THREAD

**Issue by hemanttanwar** [Azure/azure-sdk-for-java#16527]
- receiveMessage Never stop . user always keeps on receiving messages, for example 
      - [ ] When  session lock lost, But inform user about this error
      - [ ] when Receive Link lost connection
      - [ ] Any other SDK internal error

**Comment by ramya-rao-a** [comment]
@hemanttanwar Can we close this in favor of #16084?

**Comment by hemanttanwar** [comment]
Closing it.
