### ISSUE TITLE
HttpPipeline policy positioning 

### ISSUE THREAD

**Issue by samvaity** [Azure/azure-sdk-for-java#16538]
Issue https://github.com/Azure/azure-sdk-for-java/issues/15630 tracks the effort for supporting the recently added `HttpPipelinePosition` functionality to all client builders.

Wanted to standardize and have a common approach for setting positioning for policies in our client builders.
Following is the positioning that we came up with for all the policies under [core](https://github.com/Azure/azure-sdk-for-java/tree/master/sdk/core/azure-core/src/main/java/com/azure/core/http/policy)

[PER_CALL policies](https://github.com/Azure/azure-sdk-for-java/blob/master/sdk/core/azure-core/src/main/java/com/azure/core/http/HttpPipelinePosition.java#L17)
- RequestIdPolicy
- UserAgentPolicy
- PortPolicy

[PER_RETRY policies](https://github.com/Azure/azure-sdk-for-java/blob/master/sdk/core/azure-core/src/main/java/com/azure/core/http/HttpPipelinePosition.java#L24)
- AddDatePolicy
- AddHeadersFromContextPolicy
- AddHeadersPolicy
- AzureKeyCredentialPolicy
- BearerTokenAuthenticationPolicy
- HostPolicy
- HttpLoggingPolicy
- ProtocolPolicy
- TimeoutPolicy

- **CookiePolicy ?** @jianghaolu - Could you provide a use case for this policy, should this be per_call or per_retry policy?

@JonathanGiles - Would like to know your thoughts on the policy positioning proposal.

cc: @alzimmermsft  @srnagar

**Comment by jianghaolu** [comment]
CookiePolicy should be per_call as "set-cookie" headers from 400/500 responses must be handled on the client side: https://stackoverflow.com/a/21554371.

**Comment by samvaity** [comment]
Tracking this with https://github.com/Azure/azure-sdk-for-java/pull/16613
