### ISSUE TITLE
[FEATURE REQ] Ability to set AmqpRetryOptions in EvenHub connection

### ISSUE THREAD

**Issue by J4cku** [Azure/azure-sdk-for-java#16596]
**Is your feature request related to a problem? Please describe.**
It is impossible to set AmqpRetryOptions in eventhub connection. It always create default one when using spring cloud stream binder EventProcessorClientBuilder

**Describe the solution you'd like**
Ability to either set the options through properties or by creating bean with those options

**Information Checklist**
Kindly make sure that you have added all the following information above and checkoff the required fields otherwise we will treat the issuer as an incomplete report
- [x] Description Added
- [x] Expected solution specified

**Comment by saragluna** [comment]
Fixed in this PR https://github.com/Azure/azure-sdk-for-java/pull/25057, please check https://github.com/Azure/azure-sdk-for-java/issues/24260 for our next major release.
