### ISSUE TITLE
Default subscription id from configuration is ignored

### ISSUE THREAD

**Issue by cdssoftware** [Azure/azure-sdk-for-java#16595]
Following the example in https://docs.microsoft.com/en-us/azure/developer/java/spring-framework/configure-spring-boot-starter-java-app-with-azure-storage, but using an existing Enterprise App that has access to multiple subscriptions the subscriptionid in the my.azureauth seems be be ignored.

The issue seems to be in AzureContextAutoConfiguration when creating the Azure Bean. In the following code the Azure object is not passed the subscriptionId (nor does it read it from the restClient), therefore the attribute "defaultSubsciptionId" is null which means that 
`      return Azure.authenticate(restClient, credentials.domain()).withDefaultSubscription();
`
will just return the first Subscription in the list

As a workaround I've manually created the bean with the following code, however the framework should correctly support multiple subscriptions
```
	@Bean
	public Azure azure(AzureTokenCredentials credentials) {
		com.microsoft.rest.RestClient restClient = new com.microsoft.rest.RestClient.Builder()
				.withBaseUrl(credentials.environment(), AzureEnvironment.Endpoint.RESOURCE_MANAGER)
				.withCredentials(credentials).withSerializerAdapter(new AzureJacksonAdapter())
				.withResponseBuilderFactory(new AzureResponseBuilder.Factory())
				.withInterceptor(new ProviderRegistrationInterceptor(credentials))
				.withInterceptor(new ResourceManagerThrottlingInterceptor()).withUserAgent(SPRING_CLOUD_USER_AGENT)
				.build();

		return Azure.authenticate(restClient, credentials.domain()).withSubscription(credentials.defaultSubscriptionId());
	}`
```

**Comment by joshfree** [comment]
Thanks for reporting this issue @cdssoftware.  @jialindai can you please assist in routing this `azure-spring-storage` issue?
