### ISSUE TITLE
Reenable Tcnative in CosmosDB-Benchmark-Runner

### ISSUE THREAD

**Issue by xinlian12** [Azure/azure-sdk-for-java#16617]
Tcnative will be imported inV4 client, however, this will break V2 async client, hence break the V2 async tests.
Currently, tcnative has been excluded, should enable it back when the fix both ported to V2 and V3.

**Comment by kushagraThapar** [comment]
@xinlian12 - any updates on this issue ?

**Comment by xinlian12** [comment]
@kushagraThapar  I have fixed in V2, V3 still need to port the change

**Comment by kushagraThapar** [comment]
No longer needed.
