### ISSUE TITLE
[FEATURE REQ]Does Blob SDK support downloading with parallelism？

### ISSUE THREAD

**Issue by 123Jun321** [Azure/azure-sdk-for-java#16629]
**Query/Question**
Does Blob SDK support downloading with parallelism？

***Why is this not a Bug or a feature Request?***
we noticed that when we use the downloadToFileWithResponse function, there is a parameter named ParallelTransferOptions, but according to the doc, it seems just be used for upload. https://azuresdkdocs.blob.core.windows.net/$web/java/azure-storage-blob/12.0.0/com/azure/storage/blob/models/ParallelTransferOptions.html 
when we tested ingo or .net, the download function support with parallelism(the doc of go https://godoc.org/github.com/Azure/azure-storage-blob-go/azblob#DownloadFromBlobOptions ), but when we tested in java, it seems didn't work.
So we want to check whether the java sdk support downloading with parallelism？

**Setup (please complete the following information if applicable):**
 - OS: windows
 - IDE : [e.g. IntelliJ]IntelliJ
 - Version of the Library used:12.6.0
 
 **Information Checklist**
 Kindly make sure that you have added all the following information above and checkoff the required fields otherwise we will treat the issuer as an incomplete report
- [ ] Query Added
- [ ] Setup information Added

**Comment by rickle-msft** [comment]
@123Jun321 Thank you for your question. Reading the docs again, I can understand your confusion here as we only really discuss upload in the docs, and that's really an artifact of upload needing some extra details. 

To give some clarity, downloads are always parallelized automatically. In the docs you shared, only numBuffers is exclusive to upload as we don't do buffering on download. blockSize does apply to download. In later versions, numBuffers was replaced by maxConcurrency and does also apply to download. In those versions maxConcurrency serves the dual purpose of providing an upper bound to this concurrency for uploads AND downloads as it is by default set by the underlying reactive framework and also still configures the number of buffers to use on uploads. 

Hopefully that helps answer some questions, but if you have further questions, please feel free to ask.

**Comment by 123Jun321** [comment]
@rickle-msft ，Thanks for your reply, there was a new question we want to know is when we use go language to test downloading file(about 500M)comparing with java, we found go is faster than java when downloading the same file, so what we want to know is the download speed can be same with that in go when we can adjust the maxConcurrency later?

the following is our test results in the same environment:
in go, using  DownloadBlobToFile(https://godoc.org/github.com/Azure/azure-storage-blob-go/azblob#DownloadBlobToFile): it cost 2s to download the file 

in java, using downloadToFile :it cost 21s
in java using downloadToFileWithResponse: we changed the blocksize two times but it all cost about 60s

**Comment by rickle-msft** [comment]
@123Jun321 Using downloadToFileWithResponse and 4mb blocks, I'm seeing about 20s to download on my local network. Same for 1mb blocks and 20mb blocks actually.

There really shouldn't be any difference between downloadToFile and downloadToFileWithResponse in the default case as the former simply ignores some of the return values from the latter. The only reason why those would be different is because of the configured block size I think. 

I'm not too sure about the expected performance of go, especially in relation to Java, but I do know go is a more native language, so that could be partially explaining the difference in performance.

**Comment by 123Jun321** [comment]
hi, @rickle-msft  I'm sorry to reply so late, Thanks a lot for your perfect answer!
