### ISSUE TITLE
KeyProperties created without curve propery

### ISSUE THREAD

**Issue by pelegrim** [Azure/azure-sdk-for-java#16632]
/**
     * Elliptic curve name. For valid values, see JsonWebKeyCurveName. Possible
     * values include: 'P-256', 'P-384', 'P-521', 'P-256K'.
     */
    @JsonProperty(value = "crv")
    private JsonWebKeyCurveName curve;

https://github.com/Azure/azure-sdk-for-java/blob/2f0b3190eef0b4895221c437670f8b58c00302ee/sdk/keyvault/microsoft-azure-keyvault/src/main/java/com/microsoft/azure/keyvault/requests/CreateCertificateRequest.java#L145

**Comment by vcolin7** [comment]
Hi @pelegrim, thanks for filing this issue, I will look into it.

**Comment by joshfree** [comment]
removing `question` label and switching to `bug`

**Comment by vcolin7** [comment]
Closing this issue as this library has been [deprecated](https://azure.github.io/azure-sdk/releases/deprecated/index.html#java). If your application is still using any version of this library, we encourage you to upgrade to the new version to get the newest features and security updates by follwing one of our migration guides:

- [Key Vault Certificates Migration Guide](https://github.com/Azure/azure-sdk-for-java/blob/main/sdk/keyvault/azure-security-keyvault-certificates/migration_guide.md)
- [Key Vault Keys Migration Guide](https://github.com/Azure/azure-sdk-for-java/blob/main/sdk/keyvault/azure-security-keyvault-keys/migration_guide.md)
- [Key Vault Secrets Migration Guide](https://github.com/Azure/azure-sdk-for-java/blob/main/sdk/keyvault/azure-security-keyvault-secrets/migration_guide.md)
