### ISSUE TITLE
[BUG] If I try to list blobs I get PrematureCloseException 

### ISSUE THREAD

**Issue by ezienecker** [Azure/azure-sdk-for-java#16633]
**Describe the bug**
If I upload and try to call the `listBlobs` from the `BlobContainerClient` I get the following error `reactor.netty.http.client.PrematureCloseException: Connection prematurely closed BEFORE response`.

***Exception or Stack Trace***
```
17:09:27.720 [reactor-http-epoll-1] WARN  r.n.http.client.HttpClientConnect - [id: 0xe66546f4, L:/127.0.0.1:52206 ! R:localhost/127.0.0.1:5432] The connection observed an error
reactor.netty.http.client.PrematureCloseException: Connection prematurely closed BEFORE response
17:09:31.739 [reactor-http-epoll-2] WARN  r.n.http.client.HttpClientConnect - [id: 0x1ac70152, L:/127.0.0.1:52210 ! R:localhost/127.0.0.1:5432] The connection observed an error
reactor.netty.http.client.PrematureCloseException: Connection prematurely closed BEFORE response
17:09:43.774 [reactor-http-epoll-3] WARN  r.n.http.client.HttpClientConnect - [id: 0xe2582d1c, L:/127.0.0.1:52228 ! R:localhost/127.0.0.1:5432] The connection observed an error
reactor.netty.http.client.PrematureCloseException: Connection prematurely closed BEFORE response
17:10:11.804 [reactor-http-epoll-4] WARN  r.n.http.client.HttpClientConnect - [id: 0x4261e423, L:/127.0.0.1:52240 ! R:localhost/127.0.0.1:5432] The connection observed an error
reactor.netty.http.client.PrematureCloseException: Connection prematurely closed BEFORE response
```

**To Reproduce**
* upload blob
* list blobs

***Code Snippet***
```
ByteArrayInputStream(file.bytes).use {
	blobClient.upload(it, file.size)
}

assertThat(blobContainerClient.listBlobs()).hasSize(1)
```

**Expected behavior**
I can list blobs

**Screenshots**
-

**Setup (please complete the following information):**
 - OS: [e.g. ubuntu]
 - IDE : [e.g. IntelliJ]
 - Version 12.8.0 of the Library used
- azurite version 3.9.0

**Additional context**
Test it againts azurite (docker)

**Information Checklist**
Kindly make sure that you have added all the following information above and checkoff the required fields otherwise we will treat the issuer as an incomplete report
- [x] Bug Description Added
- [x] Repro Steps Added
- [x] Setup information Added

**Comment by rickle-msft** [comment]
@ezienecker Thank you for reporting this. Can you let us know how often you see this error? And can you also try using 12.9.0-beta.2? As that should have some fixes related to listBlobs that might help.

**Comment by ezienecker** [comment]
@rickle-msft I get this error every time I called the listBlobs method. Unfortunately with 12.9.0-beta.2 I get the same error.

**Comment by rickle-msft** [comment]
@ezienecker Thank you for trying the latest version. Are you able to try this against the service at all? I'm curious if you'd get the same error when not using azurite

**Comment by ezienecker** [comment]
Since I only use the list method in tests it's difficult to use it on production

**Comment by rickle-msft** [comment]
@ezienecker I just want to comment briefly that this is still on our radar and I will look into testing with the emulator at my next opportunity.

**Comment by rickle-msft** [comment]
@ezienecker I got around to working on this this morning. I'm using the same version of the sdk and of the emulator and not seeing any problems uploading or listing. Are you able to look into the debug logs for Azurite and see if there's any information on why the connection may have been closed?

**Comment by ezienecker** [comment]
@rickle-msft thanks for investigating in this issue. I will try it on monday.

**Comment by rickle-msft** [comment]
@ezienecker Were you ever able to move past this issue? We have another customer hitting this at the moment, so any information you found would be helpful.

**Comment by ezienecker** [comment]
Hi @rickle-msft I have tried to reproduce it with a small example. But unfortunately I can only reproduce the error in the application. In my small example everything runs as expected.

**Comment by rickle-msft** [comment]
@ezienecker Is your application a spring application? Or are there any other details of your environment that might be worth sharing?
