### ISSUE TITLE
where I can find the authentication file

### ISSUE THREAD

**Issue by liqiang-fit2cloud** [Azure/azure-sdk-for-java#1663]
Hi there,

I am using AzureChinaCloud, as the azure-cli 2.0 doesn't support -e parameter I have to use 0.10.13 to generate a service principal authentication file.
I followed this https://github.com/Azure/azure-sdk-for-java/issues/1197#issuecomment-254301544, but I can't find the file from my working directory.
Can anyone tell me where I can find the service principal authentication file or if it's the right way to do this?

Thanks.

**Comment by liqiang-fit2cloud** [comment]
well, I have known something about the service principal file.

```
subscription=xxxxxxxx
client=xxxxxxxxxxxx
key=xxxxxxxxxx
tenant=xxxxxxxxxxxxxx
```
subscription can be found in the Azure Web Console
client can be found through  https://github.com/Azure/azure-sdk-for-java/issues/1597#issuecomment-297118971
tenant can be found from azure-cli by excute the command "azure account show"

So for now my question is where I can find the key.
Any help will be appreciated.

**Comment by jianghaolu** [comment]
Hi @liqiang-fit2cloud 
There's an easier way to generate that through a python script now:
```
curl -L https://raw.githubusercontent.com/Azure/azure-sdk-for-java/master/tools/authgen.py | python > my.azureauth
```
Please see https://github.com/Azure/azure-sdk-for-java/blob/master/AUTH.md#creating-a-service-principal-in-azure for the updated instructions. Thanks!

**Comment by liqiang-fit2cloud** [comment]
Hi jianghaolu,
The python script gives below error on my side.
![image](https://cloud.githubusercontent.com/assets/20766823/26087420/498c1312-3a23-11e7-8d11-f25540d9476f.png)

Please note that I am using AzureChinaCloud and azure-cli 0.10.13 instead of 2.0 as it doesn't support -e parameter.

**Comment by jianghaolu** [comment]
@liqiang-fit2cloud  The python script works with the 2.0 version of CLI.

**Comment by jianghaolu** [comment]
@liqiang-fit2cloud Also, the command for Azure CLI 2.0 is `az`.

**Comment by liqiang-fit2cloud** [comment]
@jianghaolu Does 2.0 support -e AzureChinaCloud?

**Comment by jianghaolu** [comment]
@liqiang-fit2cloud the same functionality is achievable through `az cloud set -n AzureChinaCloud`.

**Comment by liqiang-fit2cloud** [comment]
Everything is ok now, thanks for help:-)
![image](https://cloud.githubusercontent.com/assets/20766823/26242088/c79b3d62-3cb9-11e7-9097-b07164453380.png)
