### ISSUE TITLE
[FEATURE REQ] Get group info from the JWT token.

### ISSUE THREAD

**Issue by chenrujun** [Azure/azure-sdk-for-java#16672]
Currently, aad-starter use OBO flow to access group-membership for the user. This is not required, group membership can be configured part of the token. Need to care about groups overage claim.

To keep compatibility, if groups not contained in token, we still need to get groups by graph api.

Refs:
 - https://docs.microsoft.com/en-us/azure/active-directory/develop/active-directory-optional-claims#configuring-groups-optional-claims
 - https://docs.microsoft.com/en-us/azure/active-directory/develop/id-tokens#groups-overage-claim

**Comment by yiliuTo** [comment]
FYI: https://github.com/MicrosoftDocs/azure-docs/issues/65368

**Comment by chenrujun** [comment]
Conclusion:

1. We should use appRoles in JWT token to create Authorities.
2. Use groupName to create Authorities is current implememtation. It is not recommended, because groupName is changable. So we should mark `azure.activedirectory.user-group.allowed-groups` as deprecated.
3. If our customer still need to use group information to create Authorities, use groupId instead of groupName.

**Comment by saragluna** [comment]
What's the status of this issue @chenrujun? Are we okay to close it now?

**Comment by chenrujun** [comment]
Closing this issue.

1. Use groupName as authority is a released function, we can not delete this function.
2. Save all groupName in JWT is not supported, we can only save groupId in JWT.
3. Use groupId as authority is a new function, now we do not have plan to support it. If there are a lot of customer need this function, we can develop it in the future.
