### ISSUE TITLE
[BUG] KeyVaultOperation#isUp logs warn for fetching secret 'it-is-ok-to-be-empty'

### ISSUE THREAD

**Issue by deryoman** [Azure/azure-sdk-for-java#16688]
**Describe the bug**
In `com.azure.spring.keyvault.KeyVaultOperation` the method `isUp` fetches the secret 'it-is-ok-to-be-empty' for checking if a connection to the vault can be established, causes the `SecretAsyncClient` to log this request every few seconds.

***Exception or Stack Trace***
`2020-10-22 07:18:55.055 WARN 1 --- [or-http-epoll-4] c.a.s.k.secrets.SecretAsyncClient : Failed to get secret - it-is-ok-to-be-empty Status code 404, "{"error":{"code":"SecretNotFound","message":"A secret with (name/id) it-is-ok-to-be-empty was not found in this key vault. If you recently deleted this secret you may be able to recover it using the correct recovery command. For help resolving this issue, please see https://go.microsoft.com/fwlink/?linkid=2125182"}}"`

**To Reproduce**
Use `azure-keyvault-secrets-spring-boot-starter` in version 2.3.5

***Code Snippet***
https://github.com/Azure/azure-sdk-for-java/blob/89cf24094f47ab3e49bfdfaf3834e430d0d4fa0b/sdk/spring/azure-spring-boot/src/main/java/com/azure/spring/keyvault/KeyVaultOperation.java#L209-L225

**Expected behavior**
Such internal requests should not be logged as a warning

**Setup (please complete the following information):**
 - OS: Linux - k8s container
 - azure-keyvault-secrets-spring-boot-starter:2.3.5
 - Java 11
 - Spring boot 2.3.4

**Comment by joshfree** [comment]
@vcolin7 could you please take the first look at this?

**Comment by vcolin7** [comment]
No problem.

**Comment by vcolin7** [comment]
Failed calls get logged as warnings because, which is what would usually happen in this case because it is very likely users do not have a secret with such a name in their Key Vault. Since we still need to have a way to know if there's connectivity with the KV in question, I was thinking we could use something like `listPropertiesOfSecrets` or `listDeletedSecrets` instead, which will return a response with status code `200` unless there's a problem with the service. I will talk to the team about it and see if they are ok with this approach or if we can come up with a better solution :)

**Comment by ksddw2** [comment]
Is there a new version available for this? In Maven central I can only see a 2.3.5 release (which has this bug) or a 3.0 Beta version. Thanks

**Comment by vcolin7** [comment]
Hi @ksddw2, I believe we have not released a new patch after the one you mentioned, I will check with the team working on this package to get back with an approximante release date for the next version.

**Comment by chenrujun** [comment]
Hi, @ksddw2 

We have released 3.1.0. Please check:
1. https://repo.maven.apache.org/maven2/com/azure/spring/azure-spring-boot-starter-keyvault-secrets/3.1.0/
2. https://github.com/Azure/azure-sdk-for-java/blob/azure-spring-boot-starter-keyvault-secrets_3.1.0/sdk/spring/azure-spring-boot/src/main/java/com/azure/spring/keyvault/KeyVaultOperation.java#L212

**Comment by vcolin7** [comment]
I see, so starting with version 3.0.0+ we switched to a new package namespace (`com.azure.spring`), correct?

**Comment by chenrujun** [comment]
@vcolin7 

>I see, so starting with version 3.0.0+ we switched to a new package namespace (com.azure.spring), correct?

Yes.
