### ISSUE TITLE
Wrong dependencies in master branch?

### ISSUE THREAD

**Issue by christian-vorhemus** [Azure/azure-sdk-for-java#16698]
I'm not a Java developer so please forgive my ignorance but if I'm not mistaken it seems like the dependency groupId should be `com.microsoft.azure` (like [here](https://github.com/Azure/azure-sdk-for-java/blob/88a365dc93871e5954d0fce0c96a642866ab13d8/sdk/spring/azure-spring-boot-samples/azure-spring-boot-sample-active-directory-backend-v2/pom.xml#L23)) but in the master branch, the group id is named `com.azure.spring` (like [here](https://github.com/Azure/azure-sdk-for-java/blob/master/sdk/spring/azure-spring-boot-starter-active-directory/pom.xml#L14))

Isn't `com.microsoft.azure`  the right one? Shouldn't this then be reflected in the master branch?

**Comment by joshfree** [comment]
Hi @christian-vorhemus, this is related to https://github.com/Azure/azure-sdk-for-java/issues/16148, where the spring boot starters that use the new Unified SDK (referred to unofficially in this repo as "Track 2") are using `com.azure.spring` to make it easier to instantly identify them from their previous "Track 1" older release versions.

You can learn more about the new Azure SDK releases here:
- https://www.youtube.com/watch?v=38RYIx7a2M4&feature=youtu.be
- https://github.com/azure/azure-sdk-for-java#client-new-releases
- https://devblogs.microsoft.com/azure-sdk/

Thanks,
Josh
