### ISSUE TITLE
Minor API Changes ServiceBus Track2 API

### ISSUE THREAD

**Issue by hemanttanwar** [Azure/azure-sdk-for-java#16713]
We need to do minor pending api changes,
1. Add ServiceBusReceivedMessage : getBytesAsString()
2.

**Comment by srnagar** [comment]
`getBytesAsString` is not required as `BinaryData` will provide this convenience method. As a side note, Event Hubs had this convenience method because `BinaryData` was not yet available when we GA'd Event Hubs.
