### ISSUE TITLE
Changing subnet for network interface ends up with error

### ISSUE THREAD

**Issue by shawnduxy** [Azure/azure-sdk-for-java#1673]
I tried to change subnet for a network interface. Here is my code:
`NetworkInterface ni = ...;`
`ni.update().withSubnet("newsubnet").apply()`

I got exception `com.microsoft.azure.CloudException: Cannot parse the request.: Cannot parse the request.`

After inspecting the log, I noticed that there is one slash missing in the subnet resource id. I'll submit a pull request to fix this bug.

**Comment by martinsawicki** [comment]
Yep, clearly a bug. Thanks for catching and providing a fix. I'm adding a test for this as well

**Comment by martinsawicki** [comment]
fixed for v1.1.0
