### ISSUE TITLE
[QUERY] Append Blob and Upload metadata are not transactional with old SDK(azure-storage:5.5.0)

### ISSUE THREAD

**Issue by abhikt48** [Azure/azure-sdk-for-java#16760]
We need to append blob and update metadata together. At this moment, I need to call two separate operation for append blob and update metadata. Please find below sample code.
Issue - If metadata update fails then appended blob can't be rollback, as both operations are not transactional.

Can you please suggest anyway to perform both operation together ? if fail then both operation fail.

***code***
```
CloudAppendBlob cloudAppendBlob = cloudBlobClient.getContainerReference(containerName).getAppendBlobReference(appendBlobName);
cloudAppendBlob.downloadAttributes();

cloudAppendBlob.appendText("--text appended");

HashMap<String, String> metadataMap = new HashMap<String, String>();
metadataMap.put("name", "Test");
metadataMap.put("Last Name", "Azure"); // Will fail here due to wrong key pattern

cloudAppendBlob.setMetadata(metadataMap);
cloudAppendBlob.uploadMetadata();
```

**Setup (please complete the following information if applicable):**
 - OS: Windows 10
 - IDE : eclipse based
 - Version of the Library used - `com.microsoft.azure:azure-storage:5.5.0`

**Comment by rickle-msft** [comment]
@abhikt48 Unfortunately there is no way to tie those operations together in either the service or the SDK. They are inherently independent operations. There's no way to tie the success of one operation to the success of another. Your application will need to be designed in such a way to handle these failures. If you give us more information, we can help make suggestions on best practices, but really all we can do is offer a few recommendations

**Comment by abhikt48** [comment]
@rickle-msft  - Thanks a lot for quick update.
