### ISSUE TITLE
Document EventGrid and distributed tracing

### ISSUE THREAD

**Issue by lmazuel** [Azure/azure-sdk-for-java#16774]
We should have a Readme section, or a sample, or maybe both, to describe what we do with distributed tracing. 

This should include  a lien to https://github.com/cloudevents/spec/blob/master/extensions/distributed-tracing.md
This should explain our auto-magic behavior to populate the extension if we detect the HTTP headers.

**Comment by jfggdl** [comment]
Chevron is asking for event tracing capability and visibility through App Insights. Just an FYI.

**Comment by YijunXieMS** [comment]
Added in readme:

https://github.com/Azure/azure-sdk-for-java/blob/master/sdk/eventgrid/azure-messaging-eventgrid/README.md#distributed-tracing
