### ISSUE TITLE
How to get the create time of a VirtualMachine?

### ISSUE THREAD

**Issue by liqiang-fit2cloud** [Azure/azure-sdk-for-java#1682]
Hi there,

I listed all of my virtual machines, I am wondering  how to can get the create time of individual vm?

Thanks.

**Comment by petergardfjall** [comment]
From my understanding, there is no such way. At least no easy way.
https://stackoverflow.com/questions/41036371/what-is-the-correct-way-of-determining-the-launch-time-of-an-azure-vm

**Comment by martinsawicki** [comment]
from what we can see, Azure does not provide that info programmatically.
