### ISSUE TITLE
[BUG] EventHubConsumerClient intermittently starts timing out

### ISSUE THREAD

**Issue by stevebasher** [Azure/azure-sdk-for-java#16830]
**Describe the bug**
I am reading events from an Azure EventHub cluster synchronously via the receiveFromPartition method on the EventHubConsumerClient class.

I create the client once like so:

```
EventHubConsumerClient eventHubConsumerClient = new EventHubClientBuilder()
            .connectionString(eventHubConnectionString)
            .consumerGroup(consumerGroup)
            .buildConsumerClient());
```
I then just use a ScheduledExecutorService to retrieve events every 1.5s via:

```
IterableStream<PartitionEvent> receivedEvents = eventHubConsumerClient.receiveFromPartition(
                partitionId, 1, eventPosition);
```
I have been running the equivalent logic using V3 of the SDK on the same production box successfully, but after upgrading to V5 I'm having issues.

Seemingly randomly the client will start timing out - after having run for minutes / hours without issue. The only solution I have found is to close and re-create the client once this starts, after which events are read as expected.

***Exception or Stack Trace***

```
com.azure.core.amqp.implementation.RetryUtil: TimeoutException error occurred. Retrying operation.
com.azure.messaging.eventhubs.implementation.SynchronousEventSubscriber$ReceiveTimeoutTask: Work: 5. Timeout encountered, disposing of subscriber.
```

**To Reproduce**
Kick off a loop as above, wait.

**Expected behavior**
The EventHubConsumerClient should be long-lived. If the connection dies (i.e. expired token) there should be an equivalent error message returned to allow proper handling. 

**Setup (please complete the following information):**
 - Version of the Library used: 5.2.0

**Comment by srnagar** [comment]
@YijunXieMS could you please take a look at this issue?

**Comment by YijunXieMS** [comment]
@stevebasher Thanks for your feedback and glad that you have a workaround.
I'm going to kick off a long running test to reproduce it.

**Comment by YijunXieMS** [comment]
@stevebasher I tried to reproduce by using a loop to receive events every 1.5s. It didn't reproduce the problem in my environment after 10+ days of running. Will try ScheduledExecutorService.

**Comment by joshfree** [comment]
Closing old issue with no further follow up.
