### ISSUE TITLE
Metrics advisor Readme and Sample issues

### ISSUE THREAD

**Issue by Melanie-Ma** [Azure/azure-sdk-for-java#16875]
1.
Section [Link](https://github.com/Azure/azure-sdk-for-java/tree/master/sdk/metricsadvisor/azure-ai-metricsadvisor#azure-metrics-advisor-client-library-for-java):
![image](https://user-images.githubusercontent.com/64007802/97254114-a632ef80-1848-11eb-9170-c2d1a61839e4.png)
Suggestion:
Add hyperlink for `Package(Maven)` https://search.maven.org/search?q=a:azure-ai-metricsadvisor
2.
Section [Link](https://github.com/Azure/azure-sdk-for-java/tree/master/sdk/metricsadvisor/azure-ai-metricsadvisor#enable-client-logging):
![image](https://user-images.githubusercontent.com/64007802/97254208-da0e1500-1848-11eb-847b-fe2521954718.png)
Suggestion:
Add hyperlink for `logging` https://github.com/Azure/azure-sdk-for-java/wiki/Logging-with-Azure-SDK

3.
Section [Link](https://github.com/Azure/azure-sdk-for-java/blob/master/sdk/metricsadvisor/azure-ai-metricsadvisor/src/samples/java/com/azure/ai/metricsadvisor/administration/AnomalyDetectionConfigurationAsyncSample.java#L95):
![image](https://user-images.githubusercontent.com/64007802/97254532-8b14af80-1849-11eb-96da-9479d26cc246.png)
![image](https://user-images.githubusercontent.com/64007802/97254575-a384ca00-1849-11eb-9d00-10e769d02830.png)
![image](https://user-images.githubusercontent.com/64007802/97254581-a54e8d80-1849-11eb-9e8b-8bc8b55fdce8.png)
Suggestion:
After calling the method `printDetectionConfiguration()`, the value of the property `hardThresholdCondition` is null, which caused the NullPointerException, please check.

@jongio for notification

**Comment by v-xuto** [comment]
Close this issue, due to PR (#22694, #22691) merged.
