### ISSUE TITLE
Event Hubs  Sample issues

### ISSUE THREAD

**Issue by Melanie-Ma** [Azure/azure-sdk-for-java#16872]
1.
Section [Link](https://github.com/Azure/azure-sdk-for-java/blob/master/sdk/eventhubs/azure-messaging-eventhubs/src/samples/java/com/azure/messaging/eventhubs/PublishIterableEvents.java#L53):
![image](https://user-images.githubusercontent.com/64007802/97252655-7cc49480-1845-11eb-9721-5a05986b5cb6.png)
![image](https://user-images.githubusercontent.com/64007802/97252659-7e8e5800-1845-11eb-80f4-f05d898a0808.png)
Suggestion:
Change to `final Iterable<EventData> events = Flux.range(0, 100).map(number -> {`
                  `final String contents = "event-data-" + number;`
                  `return new EventData(contents.getBytes(UTF_8));`
                  ` }).collectList().block();`

@jongio, for notification.

**Comment by jongio** [comment]
#18319 resolves this.
