### ISSUE TITLE
Opentelemetry Exporters Azuremonitor Readme issues

### ISSUE THREAD

**Issue by Melanie-Ma** [Azure/azure-sdk-for-java#16873]
１.
Section [Link](
https://github.com/Azure/azure-sdk-for-java/tree/master/sdk/monitor/azure-monitor-opentelemetry-exporter#examples):
![image](https://user-images.githubusercontent.com/64007802/97253101-8b5f7b80-1846-11eb-8882-4a2b5f77da9f.png)
Suggestion:
Add hyperlink for `[samples]` https://github.com/Azure/azure-sdk-for-java/tree/master/sdk/monitor/azure-monitor-opentelemetry-exporter/src/samples

@jongio for notification

**Comment by v-xuto** [comment]
Close it due to PR merged.

**Comment by jongio** [comment]
#cloudmineautomationtrigger
