### ISSUE TITLE
[Feature Request][Storage] BlobClient.openInputStream() stream should return stream to latest version of blob. 

### ISSUE THREAD

**Issue by mkozioro** [Azure/azure-sdk-for-java#16882]
**Describe the bug**
BlobClient.openInputStream() in case of overwriting blob content, can return some chunks of data from original blob, and some chunks from new blob content. 

**To Reproduce**
1. Upload blob to storage
2. Use BlobClient.openInputStream() to create input stream.
```
          BlobClient blobClient = containerClient.getBlobClient(blobName);
          InputStream inputStream = blobClient.openInputStream();
```

3. Read several chunks of data from that stream and pause.
4. Overwrite blob on storage. 
5. Read more chunks from previously created input stream.

Consequence will be that first chunks will be read from original blob content, and later chunks will be read from updated blob content.

**Expected behavior**
I would expect here, that BlobInputStream will cache original blob ETag value and throw some exception indicating that blob was modified while reading.
Other option in case of enabled blob versioning would be sticking to some particular blob version and reading all chunks from that version.

**Setup (please complete the following information):**
 - OS: Linux
 - IDE : IntelliJ
 - Version of the Library used: 12.7.0, but same problem should exists also in 12.9.0-beta.2

**Information Checklist**
Kindly make sure that you have added all the following information above and checkoff the required fields otherwise we will treat the issuer as an incomplete report
- [ x] Bug Description Added
- [ x] Repro Steps Added
- [ x] Setup information Added

**Comment by gapra-msft** [comment]
@mkozioro Thanks for reporting this issue, 

It looks like this is a bug, we will fix this as soon as we can.

**Comment by mkozioro** [comment]
Hi @gapra-msft 
I see that fix is already merged. Thanks.
How would it work in case of versioned blob and blob client created in simple way:
```
BlobClient blobClient = containerClient.getBlobClient(blobName);
```
and not:
```
blobClient.getVersionClient("xyz")
```
In case of using non versioned client, will BlobInputStream just throw exception (etag changed) or BlobInputStream will just stick to original version of blob or server will push content of blob with provided matching ETag?

**Comment by gapra-msft** [comment]
@mkozioro Thanks for your question. 

So if you want to get an input stream to the versioned blob, you'll have to do something like 

`blobClient.getVersionClient("xyz").openBlobInputStream(YOUR OPTIONS HERE); `

Otherwise, we have no way of knowing whether or not you intend to read from the base blob or the versioned blob.

**Comment by mkozioro** [comment]
@gapra-msft 
My intention was to fully read the latest version of blob. I thought
```
BlobClient blobClient = containerClient.getBlobClient(blobName);
```
means client for the latest version of blob. Personally, in case of versioned blob, I wouldn't expect here StorageException when new version if blob is uploaded but rather that InputStream opens some kind of session that allows me to fully read blob.

**Comment by gapra-msft** [comment]
@mkozioro Thanks for the suggestion. 

I do understand where youre coming from. 

Versioning is a new feature so we haven't yet fully considered what that means in the context of our stream types. Let me chat with my colleagues and see if this suggestion can be considered.

**Comment by gapra-msft** [comment]
I'll reopen and relabel the issue to track this new request

**Comment by gapra-msft** [comment]
Hi @mkozioro 

Just to update you, it looks like we are willing to accept this feature request. We will likely expose this as an Enum ConcurrencyControl {None, ETag, VersionId} that you can set when opening the InputStream. 

We will schedule this work at our earliest convenience. 

Thanks!
