### ISSUE TITLE
KnownWindowsVirtualMachineImage: WINDOWS_SERVER_2016_TECHNICAL_PREVIEW_WITH_CONTAINERS 

### ISSUE THREAD

**Issue by sdonchenko** [Azure/azure-sdk-for-java#1689]
Image WINDOWS_SERVER_2016_TECHNICAL_PREVIEW_WITH_CONTAINERS and WINDOWS_SERVER_TECHNICAL_PREVIEW are not relevant for this moment. Please, remove it or replace by another one.

**Comment by anuchandy** [comment]
Thanks @sdonchenko. @martinsawicki this will be a breaking change so we need to wait for next major SDK update.

**Comment by martinsawicki** [comment]
let's mark as `@deprecated` in v1.4 at least

**Comment by martinsawicki** [comment]
fixed for v1.4
