### ISSUE TITLE
Azure Active Directory secured Spring API always redirects to common endpoint instead of single-tenant endpoint

### ISSUE THREAD

**Issue by christian-vorhemus** [Azure/azure-sdk-for-java#16890]
I've downloaded and configured the Azure Spring Boot AAD Backend example V2 as describe [here](https://github.com/Azure/azure-sdk-for-java/blob/88a365dc93871e5954d0fce0c96a642866ab13d8/sdk/spring/azure-spring-boot-samples/azure-spring-boot-sample-active-directory-backend-v2/README.md). 

I have registered a single-tenant AAD app and I want users of this tenant to follow the authorization code flow when they access the API. I've also set the `spring.security.oauth2.client.provider.azure-oauth-provider` URIs as described [here](https://github.com/Azure/azure-sdk-for-java/blob/88a365dc93871e5954d0fce0c96a642866ab13d8/sdk/spring/azure-spring-boot-samples/azure-spring-boot-sample-active-directory-backend-v2/README.md#if-registered-application-is-not-multi-tenanted-how-to-run-this-sample). 

However, every time I debug the app and open localhost:8080, I'm redirect to `https://login.microsoftonline.com/common/oauth2/authorize` instead of `https://login.microsoftonline.com/16966e62-458a-4618-8164-fd778c42148f/oauth2/authorize`. If I try to log in using the common endpoint, I get a redirects back to localhost:8080 without obtaining an access token.

I've published the sample I'm using [here](https://github.com/christian-vorhemus/aad-sample), I've just removed the app client secret and kept everything else as is to make it easier to understand how the configuration actually looks like.

Is there something wrong in the sample or am I missing something?

**Comment by joshfree** [comment]
@jialindai could you please assist in routing @christian-vorhemus 's question

**Comment by backwind1233** [comment]
@christian-vorhemus  I am handling this issue，I will inform you of any progress.

**Comment by backwind1233** [comment]
@christian-vorhemus , the default is endpoint is common, 
if you want to redirect to single-tenant endpoint,pls refer the config [here](https://github.com/Azure/azure-sdk-for-java/blob/azure-spring-boot_2.3.5/sdk/spring/azure-spring-boot/src/main/resources/aad-oauth2-common.properties),

that is change your config in [aad-sample](https://github.com/christian-vorhemus/aad-sample/blob/master/src/main/resources/application.properties)
**from**  
spring.security.oauth2.client.provider.azure-oauth-provider.*** 
**to**
spring.security.oauth2.client.provider.azure.***

![image](https://user-images.githubusercontent.com/4465723/97847168-21edda00-1d2a-11eb-9db3-a53cc071d78a.png)

**Comment by christian-vorhemus** [comment]
Thank you @backwind1233, these settings work now!
