### ISSUE TITLE
DiagnosticsProfile.java missing method to receive Diagnostics Storage Account for Windows VM

### ISSUE THREAD

**Issue by ShailashreeE** [Azure/azure-sdk-for-java#1690]
Looking for a way to get the Storage account which stores the diagnostics data for a Virtual machine.

Under 'Diagnostics settings' of a Windows VM, there are 2 different tabs - 'Agent' & 'Boot Diagnostics'.
The storage account mentioned under 'Agent' tab stores the diagnostic data, whereas the storage account mentioned under 'Boot diagnostics' tab stores the screenshots(boot diagnostics). 

<img width="883" alt="screenshot 119" src="https://cloud.githubusercontent.com/assets/28895501/26353601/dbcdcd86-3fde-11e7-8e92-91762f0b1817.png">
<img width="870" alt="screenshot 120" src="https://cloud.githubusercontent.com/assets/28895501/26353606/e13a7b3e-3fde-11e7-8f3d-957912c43512.png">

Using Azure sdk for java, I could get only the Boot diagnostics storage account, as given below,
DiagnosticsProfile.java has methods like bootDiagnostics() and withBootDiagnostics();

But there is no method to retrieve the Diagnostics storage account(mentioned under 'Agent' tab). Please provide us with a fix as soon as possible.

**Comment by anuchandy** [comment]
@ShailashreeE the agent diagnostics is an extension installed in the virtual machine.
If it is installed then you can retrieve the agent storage account name as

```java
 VirtualMachineExtension diagnosticsExtension = virtualMachine.listExtensions().get("LinuxDiagnostic");
 Map<String, Object> publicSettings = diagnosticsExtension.publicSettings();
 String agentStorageAccount = (String) publicSettings.get("storageAccount");
```

 [This](https://github.com/Azure/azure-sdk-for-java/blob/master/azure-mgmt-compute/src/test/java/com/microsoft/azure/management/compute/VirtualMachineExtensionOperationsTests.java#L36) test shows how to enable diagnostics agent in a virtual machine.

**Comment by anuchandy** [comment]
The above code is for retrieving agent diagnostics from a Linux machine, for Windows the extension name is `IaaSDiagnostics`

**Comment by ShailashreeE** [comment]
Thank you @anuchandy for the solution.
It works (Y)

**Comment by martinsawicki** [comment]
@anuchandy - so can we close this now?

**Comment by martinsawicki** [comment]
supported in VMs in v1.3, and VMSS in v1.4 (ETA: mid Nov)
