### ISSUE TITLE
Exception gettting keys on management-storage

### ISSUE THREAD

**Issue by renutz** [Azure/azure-sdk-for-java#1691]
Hi,

We are trying to get the keys from a Storage Account. This is for version 1.0.1-snapshot

It happens only on a specific StorageAccount. All others work fine - I can't tell what is the difference.

`for (StorageAccountKey key: azstorageaccount.getKeys()) {
    System.out.println(key.keyName());
}
`

And getting an exception:
`java.lang.RuntimeException: java.io.IOException: Content-Length and stream length disagree
   at rx.exceptions.Exceptions.propagate(Exceptions.java:58)
   at rx.observables.BlockingObservable.blockForSingle(BlockingObservable.java:464)
   at rx.observables.BlockingObservable.last(BlockingObservable.java:227)
   at com.microsoft.azure.management.storage.implementation.StorageAccountImpl.getKeys(StorageAccountImpl.java:113)
`

Please advice.

Thanks

**Comment by jianghaolu** [comment]
@renutz Did you plug in any inceptor that reads the response stream?

**Comment by renutz** [comment]
No. Plain use of all APIs.

**Comment by jianghaolu** [comment]
There was a bug previously in one of our built-in interceptors that we read the response body without cloning it. It was fixed 6 days ago here: https://github.com/Azure/azure-sdk-for-java/commit/6c4c0517f7ad024978f2513b6121700c3bce147d#diff-fbae7ee0e31a3327a99bab5b5b68b5fe. Can you try building from the latest and see if this fixes your issue?

**Comment by renutz** [comment]
It worked! The difference was that we have a permission issue in this Storage Account, so now instead of the error, we get the 403 error with a message.

Thanks!
