### ISSUE TITLE
[BUG] DataLakeLeaseClient's both breakLease and releaseLease does not work

### ISSUE THREAD

**Issue by peter-he-by** [Azure/azure-sdk-for-java#16928]
**Describe the bug**
When we call DataLakeLeaseClient.breakLease or releaseLease, The lock is still there.

***Exception or Stack Trace***
Add the exception log and stack trace if available

**To Reproduce**

***Code Snippet***
Add the code snippet that causes the issue.

**Expected behavior**

**Screenshots**

**Setup (please complete the following information):**
 - IDE : [e.g. IntelliJ]
 - Version of the Library used

**Additional context**

**Information Checklist**
Kindly make sure that you have added all the following information above and checkoff the required fields otherwise we will treat the issuer as an incomplete report
- [ ] Bug Description Added
- [ ] Repro Steps Added
- [ ] Setup information Added

**Comment by joshfree** [comment]
@gapra-msft @rickle-msft could you please take a look?

**Comment by rickle-msft** [comment]
@peter-he-by Can you please give more detail on the behavior you're seeing? Are you specifying a break period on the lease?

**Comment by peter-he-by** [comment]
1.  Multiple process send requests to azure function which acquire lease in a file as distribute lock
  2.  The azure function is written in java, in try..catch…finally block. In try block acquire the lease, finally block call breaklease to release lease.
  3.  When one process is failed with exception after acquire lock, not sure why the lock is still there

**Comment by gapra-msft** [comment]
Hi @peter-he-by Would it be possible for you to provide a reproduction of your code?

**Comment by amishra-dev** [comment]
Please reactivate with a code snippet, if you are still facing the issue.
