### ISSUE TITLE
LogLevel.NONE still prints out to console

### ISSUE THREAD

**Issue by selvasingh** [Azure/azure-sdk-for-java#1692]
It will always print out a message to console like bellow, even if I set the logLevel to NONE or don't set it. I think this is a bug. I don't think this message should always print out to console. 
[pool-84-thread-1] INFO com.microsoft.aad.adal4j.AuthenticationAuthority - [Correlation ID: e9ecdcf6-be48-4e93-b7cf-6a35164c006f] Instance discovery was successful

Azure azure = Azure.configure()
.withLogLevel(LogLevel.NONE)
.authenticate(credFile)
.withDefaultSubscription();

Customer says that they are using Beta 5

**Comment by jianghaolu** [comment]
This is the output from ADAL. We don't control it.

**Comment by martinsawicki** [comment]
AAD not us
