### ISSUE TITLE
[FEATURE REQ] Wrap/Unwrap Secret without GetKey permissions

### ISSUE THREAD

**Issue by jain-chinmay** [Azure/azure-sdk-for-java#16922]
**Is your feature request related to a problem? Please describe.**
The idea is to implement the key-encrypting keys (KEK) using the Azure Vault for PCI compliance.

The solution that I have come up to so far is to have my keys stored as secrets in the Azure Vault. These keys would be wrapped and unwrapped by an HSM-protected key residing in the Azure Vault.

As recommended in the PCI guidelines, I want to limit the visibility of the HSM-protected key (KEK in my context) for the service principal used by my application.

In theory, I should be able to achieve this using just the key URL, since access to the key is not critical for wrapping/unwrapping APIs. However, the Azure SDK is explicitly checking the validity of the key using the GetKey API call which makes it impossible to wrap/unwrap without the key access to the service principal.

**Describe the solution you'd like**
The solution to the above problem is to make the key validation check optional. This will allow the application to consume the wrap/unwrap APIs without having actual access to the key.

**Describe alternatives you've considered**
The only alternative solution that I've found so far for this problem is to have a managed/dedicated HSM. This could solve my problem but this solution is overkill, given the fact that the key vault, in theory, supports the flexibility I require.

**Information Checklist**
Kindly make sure that you have added all the following information above and checkoff the required fields otherwise we will treat the issuer as an incomplete report
- [x] Description Added
- [x] Expected solution specified

**Comment by AlexGhiondea** [comment]
@heaths @schaabs thoughts here?

**Comment by heaths** [comment]
We had a similar request in azure/azure-sdk-for-net#11574 where we still called "get" but, failing with a 403, still treated that as "it exists". Thus, when `CryptographyClient.wrapKey` is called, it should still just pass through to the `/keys/{name}/wrapKey` endpoint and require the `wrapKey` permission. This means, of course, you can't wrap locally, but that should be okay - certainly what is requested in this ask.

**Comment by jain-chinmay** [comment]
@heaths Thank you for the quick look.

I agree with you in the absence of the key, it would be impossible to wrap locally. If this feature could be made optional, it would help in adhering to the PCI guidelines for KEK as wrapping should be done remotely without the actual key access.
