### ISSUE TITLE
DataLakePathClient.getProperties leaks unhandled java.net.UnknownHostException

### ISSUE THREAD

**Issue by tringuyen-yw** [Azure/azure-sdk-for-java#16939]
**Describe the bug**
Exception on
- `getProperties()` (on `DataLakeFileClient`, `DataLakeDirectoryClient`, `DataLakeFileSystemClient`)
- `create()` (on `DataLakeFileSystemClient`)

The API is working OK with:
- DataLakeFileSystemClient: getFileSystemClient(), createDirectory(), getDirectoryClient()
- DataLakeDirectoryClient: createSubdirectory(), createFile()

which indicates that the credentials I was using was correct. The directory and files created could be confirmed by a visual verification using Storage Explorer

***Exception or Stack Trace***
```
java.net.UnknownHostException: in.blob.omndls01.dfs.core.windows.net: nodename nor servname provided, or not known
reactor.core.Exceptions$ReactiveException: java.net.UnknownHostException: in.blob.omndls01.dfs.core.windows.net: nodename nor servname provided, or not known
	at reactor.core.Exceptions.propagate(Exceptions.java:393)
	at reactor.core.publisher.BlockingSingleSubscriber.blockingGet(BlockingSingleSubscriber.java:97)
	at reactor.core.publisher.Mono.block(Mono.java:1680)
	at com.azure.storage.common.implementation.StorageImplUtils.blockWithOptionalTimeout(StorageImplUtils.java:99)
	at com.azure.storage.blob.specialized.BlobClientBase.getPropertiesWithResponse(BlobClientBase.java:708)
	at com.azure.storage.file.datalake.DataLakePathClient.lambda$getPropertiesWithResponse$2(DataLakePathClient.java:432)
	at com.azure.storage.file.datalake.implementation.util.DataLakeImplUtils.returnOrConvertException(DataLakeImplUtils.java:36)
	at com.azure.storage.file.datalake.DataLakePathClient.getPropertiesWithResponse(DataLakePathClient.java:431)
	at com.azure.storage.file.datalake.DataLakePathClient.getProperties(DataLakePathClient.java:411)
```

**To Reproduce**
[BasicExample.java](https://github.com/Azure/azure-sdk-for-java/blob/master/sdk/storage/azure-storage-file-datalake/src/samples/java/com/azure/storage/file/datalake/BasicExample.java) (from this repo)

**Expected behavior**
The code sample in `BasicExample` should works flawlessly (like the one you made for Azure Blob)
The value `in.blob.omndls01` (maybe a hostname?) in the error message (in.blob.omndls01.dfs.core.windows.net: nodename nor servname provided, or not known) is particular unclear. This value doesn't come from my code.

**Setup (please complete the following information):**
 - OS: MacOS 10.15.7
 - IDE : IntelliJ 2020.2.3
 - Version of the Library used `azure-storage-file-datalake v12.2.0`

**Comment by joshfree** [comment]
Thanks for filing this issue @tringuyen-yw.  Someone from the `storage` team will follow up shortly

**Comment by tringuyen-yw** [comment]
Not sure what happened. But the exception disappeared when testing the code on a newly created Storage account (Datalake Storage Gen2, hierarchical namespace, Locally Redundant Storage, TLS version 1.2). Still I hope the reported issue is still useful to help improving the error feedback. Because the exception message gives no clues about what is wrong.

**Comment by gapra-msft** [comment]
Hi @tringuyen-yw 

Thanks for reporting this issue. It's a little unclear to me what is going wrong here. Did your accountName look something like in.blob.omndls01?

**Comment by tringuyen-yw** [comment]
@gapra-msft my account name is a single string lowercase, no dot, not hyphen. And of course its valaue is NOT `in.blob.omndls01` otherwise I would figure out the issue immediately.

**Comment by tringuyen-yw** [comment]
Even wierder, the Datalake API was able to pass all tests in an Azure Blob container. The tests are basically [BasicExample.java](https://github.com/Azure/azure-sdk-for-java/blob/master/sdk/storage/azure-storage-file-datalake/src/samples/java/com/azure/storage/file/datalake/BasicExample.java). And yet the documentation [Use Java to manage directories, files, and ACLs in Azure Data Lake Storage Gen2](https://docs.microsoft.com/en-us/azure/storage/blobs/data-lake-storage-directory-file-acl-java) states 

> Prerequisites: A storage account that has hierarchical namespace (HNS) enabled

Could this issue be something region specific?

**Comment by rickle-msft** [comment]
@tringuyen-yw If you are still seeing the issue on your older account and are concerned about it, can you try turning on logging so we can see the outgoing requests and understand more about the UnknownHostException

**Comment by gapra-msft** [comment]
Hi @tringuyen-yw I believe this issue is related to https://github.com/Azure/azure-sdk-for-java/issues/17420

This bug was fixed in our latest release. I'm going to close this issue as I believe it is resolved, If you still hit it again, please feel free to re-open the issue.
