### ISSUE TITLE
[FEATURE-REQ] Address Client Certificate Credential Consistency Public API Review feedback 

### ISSUE THREAD

**Issue by g2vinay** [Azure/azure-sdk-for-java#16937]
Following changes need to be done, based on the review discussion:

- [ ] Align cert path and password APIs
- [ ] Add password support for PEM certs
- [ ] Add/Expose InputStream overloads for ClientCertificateCredential

**Comment by pranay-gore** [comment]
is there any recent update on this feature? I see queries are closed but no further update on the availability of pemCertificate(InputStream certificate) method.

**Comment by kunmin-db** [comment]
@g2vinay Is there any update on this feature? I see it's mentioned it's expected to GA in the first half of 2022?https://github.com/Azure/azure-sdk-for-java/issues/24542#issuecomment-937933977

**Comment by santyC** [comment]
is there any update on this method?

**Comment by kaneg** [comment]
Many years have passed, such a simple change(just make it public) still has not been implemented...

**Comment by g2vinay** [comment]
To provide an update, this feature requires a re-design and we will be making it available in the August beta release and then GA will follow.

**Comment by santyC** [comment]
Hi Vinay, any update on the August beta release ?
