### ISSUE TITLE
Add ServiceBus distributed tracing unit test code

### ISSUE THREAD

**Issue by YijunXieMS** [Azure/azure-sdk-for-java#16941]
The ServiceBus distributed tracing code (PR #16524) in MessageUtils.java needs to write some unit test code.
I need more time to think and discuss how to write the unit test for tracing. Create this issue and address it later to save time for higher priority tasks.

**Comment by anuchandy** [comment]
The "core.util.tracing" is a package from azure-core & various SDKs use types from it. There is no pattern of SDKs testing usage of these types. Closing
