### ISSUE TITLE
[QUERY] artifactid missing in Maven Central Repo for group id com.azure.spring

### ISSUE THREAD

**Issue by gilbertofigini** [Azure/azure-sdk-for-java#16965]
**Query/Question**
In sample azure-sdk-for-java/sdk/spring/azure-spring-boot-samples/azure-spring-cloud-sample-eventhubs-binder/ pom.xml is present com.azure.spring group id. I'm not able to find artifactId azure-spring-cloud-stream-binder-eventhubs in group id com.azure.spring on **Maven Central**. I can substitute it with spring-cloud-azure-eventhubs-stream-binder with group id com.microsoft.azure?

***Why is this not a Bug or a feature Request?***
work fine with previously dependency

**Setup (please complete the following information if applicable):**
 - IDE : IntelliJ
 
 **Information Checklist**
 Kindly make sure that you have added all the following information above and checkoff the required fields otherwise we will treat the issuer as an incomplete report
- [ ] Query Added
- [X] Setup information Added

**Comment by backwind1233** [comment]
@gilbertofigini  we changed groupId and artifactId.

groupId     (**com.microsoft.azure**--->_com.azure.spring_) 
artifactId  (**spring-cloud-azure-eventhubs-stream-binder**-->_azure-spring-cloud-stream-binder-eventhubs_)

we haven't done the release. 
you can use an old version, this ref is [here](https://mvnrepository.com/artifact/com.microsoft.azure/spring-cloud-azure-eventhubs-stream-binder)
