### ISSUE TITLE
Java Metrics Advisor UX study action items

### ISSUE THREAD

**Issue by samvaity** [Azure/azure-sdk-for-java#16973]
- [X] 1. Add overload for `listIncidentRootCauses(AnomalyIncident incident)` that takes the incident object. SDK's need to set the detectionConfigurationId on the returned service returned incident. _[Service follow up] Check with the service team if they could set the detectionConfigurationId on the returned incident object_.

- [x] 2. Consider flattening the `AnomalyDetectionConfiguration` model. Feedback - Currently, createAnomalyDetectionConfiguration takes a single hierarchical object, instead could take a bunch of parameters or flatten some of the layerings.

- [X] 3. Update method names to use  `configs` instead of `configuration`.

- [ ] 4. Update the `DataFeed::MetricIds` object to return a Map<Id, name>. Currently, it returns a list of Id's which isn't very helpful for knowing which metric the id really belongs to.

=== Service Follow ups ===

1. Using incorrect id's for API calls service returns with an error message "Insufficient permission" should it rather say "Incorrect Identifier" instead?
2. Check with the service team if they could set the detectionConfigurationId on the returned incident object
3. Could we define a constant guid for the "Default" configuration, then SDK can think of exposing `isDefault()` getter in the configuration.
4. Users are more comfortable with double/point-based systems instead of percentages for sensitivity settings.

**Comment by jeremymeng** [comment]
> * Update the `DataFeed::Metrics` object to return a Map<Id, name>. Currently, it returns a list of Id's which isn't very helpful for knowing which metric the id really belongs to.

if we use SDK to create the datafeed, we don't have the metric ids, would it still be similar effort to find the id by the name we specified, comparing to using Array/List?

**Comment by samvaity** [comment]
>if we use SDK to create the datafeed, we don't have the metric ids, would it still be similar effort to find the id by the name we specified, comparing to using Array/List?

Hmm, at least they can filter by value for the map, sure it doesn't provide the best lookup effort.
Currently, the only way of knowing metric name, would be to drill down to `DataFeed::DataFeedSchema::Metrics`.

**Comment by jeremymeng** [comment]
ah I see it's `DataFeed::Metrics`. I'd thought it was just an array of metric ids and Anu wanted to remove it.  We already removed it from JS. Yes, users would have to look into the schema property now

**Comment by kinelski** [comment]
> Update the DataFeed::MetricIds object to return a Map<Id, name>. Currently, it returns a list of Id's which isn't very helpful for knowing which metric the id really belongs to.

Would it make more sense to have Map<name, Id>? I'd expect users to know their metric names, but not their IDs.

**Comment by samvaity** [comment]
>Would it make more sense to have Map<name, Id>? I'd expect users to know their metric names, but not their IDs.

Yeah, I think we can do that. The initial thought was about duplicates but don't think that's a possibility.

**Comment by samvaity** [comment]
Completed items 1 and 3. Moving items 2 and 4 for next preview discussions.

**Comment by samvaity** [comment]
> 2. Consider flattening the AnomalyDetectionConfiguration model. Feedback - Currently, createAnomalyDetectionConfiguration takes a single hierarchical object, instead could take a bunch of parameters or flatten some of the layerings.

Following similar/consistent approach as of `createDataFeed(DataFeed datafeed)` here.
