### ISSUE TITLE
[QUERY] Use with proxy, token obtained but unable to resolve cluster host

### ISSUE THREAD

**Issue by stevenylai** [Azure/azure-sdk-for-java#17011]
**Query/Question**
My Java code:
```java
        ClientSecretCredential clientSecretCredential = new ClientSecretCredentialBuilder()
                .clientId(clientId)
                .clientSecret(clientKey)
                .tenantId(tenantId)
                .proxyOptions(new ProxyOptions(ProxyOptions.Type.SOCKS5, new InetSocketAddress(proxyHost, proxyPort)))
                .build();

        DataLakeServiceClient serviceClient = new DataLakeServiceClientBuilder()
                .credential(clientSecretCredential)
                .endpoint("https://" + storageAccount + ".dfs.core.windows.net")
                .buildClient();

        DataLakeFileSystemClient fileSystemClient = serviceClient.getFileSystemClient(fileSystem);
        DataLakeDirectoryClient directoryClient = fileSystemClient.getDirectoryClient(remotePath);
        DataLakeFileClient fileClient = directoryClient.getFileClient(remoteFile);
        fileClient.uploadFromFile(localFilePath, true);
```
stack trace
```
[ForkJoinPool.commonPool-worker-9] INFO com.azure.identity.ClientSecretCredential - Azure Identity => getToken() result for scopes [https://storage.azure.com/.default]: SUCCESS
[ForkJoinPool.commonPool-worker-9] INFO com.azure.core.credential.SimpleTokenCache - Acquired a new access token.
Exception in thread "main" reactor.core.Exceptions$ReactiveException: java.net.UnknownHostException: djsmugvnkpwf68rcontainer.dfs.core.windows.net: Name or service not known
        at reactor.core.Exceptions.propagate(Exceptions.java:393)
        at reactor.core.publisher.BlockingSingleSubscriber.blockingGet(BlockingSingleSubscriber.java:97)
        at reactor.core.publisher.Mono.block(Mono.java:1680)
        at com.azure.storage.common.implementation.StorageImplUtils.blockWithOptionalTimeout(StorageImplUtils.java:99)
        at com.azure.storage.file.datalake.DataLakeFileClient.uploadFromFile(DataLakeFileClient.java:291)
        at com.azure.storage.file.datalake.DataLakeFileClient.uploadFromFile(DataLakeFileClient.java:264)
        at Uploader.main(Uploader.java:47)
        Suppressed: java.lang.Exception: #block terminated with an error
                at reactor.core.publisher.BlockingSingleSubscriber.blockingGet(BlockingSingleSubscriber.java:99)
                ... 5 more
Caused by: java.net.UnknownHostException: djsmugvnkpwf68rcontainer.dfs.core.windows.net: Name or service not known
```

I also created a Windows VM in the cluster and ran ping - it was resolvable from cmdline:
```
C:\Users\rtdev>ping djsmugvnkpwf68rcontainer.dfs.core.windows.net

Pinging dfs.am5prdstr14a.store.core.windows.net [52.239.140.2] with 32 bytes of data:
```

Anything I'm missing?
***Why is this not a Bug or a feature Request?***
Since obtain token is OK

**Setup (please complete the following information if applicable):**
Azure enterprise
 
 **Information Checklist**
 Kindly make sure that you have added all the following information above and checkoff the required fields otherwise we will treat the issuer as an incomplete report
- [x] Query Added
- [x] Setup information Added

**Comment by rickle-msft** [comment]
Hi, @stevenylai. Thank you for reporting this. I see that the UnknownHostException is having problems with djsmugvnkpwf68rcontainer.dfs.core.windows.net but you're pinging dfs.am5prdstr14a.store.core.windows.net, so I'm not sure what the correlation is between these pieces of information. 

Can you try making a request to the storage account in question using an alternate credential option (preferably SharedKey or SAS) to confirm that the host is indeed correct?

**Comment by stevenylai** [comment]
I think there are some dns aliasing within the cluster itself so that when I try to ping djsmugvnkpwf68rcontainer.dfs.core.windows.net, it automatically resolves to dfs.am5prdstr14a.store.core.windows.net.

I searched some Internet sources and there seems to be a known issue in JVM implementation where remote DNS resolution with SOCKS proxy doesn't work. See https://stackoverflow.com/questions/44369862/java-socks-proxy-uses-local-dns There is also a JDK ticket associated with it.

Fortunately I don't need this now. Optionally you may want to add a bit doc (preferably around the `proxyOptions` function) on this known SOCKS DNS issue since I guess proxy might still be common among enterprise users due to firewalls.

I am closing this.

**Comment by rickle-msft** [comment]
Thank you , @stevenylai for continuing to investigate the issue and sharing your results here! I'm sure they will prove useful!

**Comment by jinyanghuang** [comment]
Hi, I am having similar issue. It doesn't happen when I run my app locally, but happens on the kubernete cluster. The different part is if I refresh my page, it fixes the unknownhost exception itself. But if I visit my web app after a long time, it throw that exception again and will fixes itself by refresh. So is it a proxy issue?

**Comment by rickle-msft** [comment]
@jinyanghuang Unfortunately I don't think I have enough information about your environment to say for sure if it's a proxy issue. We won't be able to assist to much in that process and request that if you have specific information which points to an sdk issue that you follow up here or on a new issue.

**Comment by stevenylai** [comment]
Just in case someone is still struggling with this. I actually got it work now and one thing I missed before is that for communication through proxy, we need to have proxy set for both `ClientSecretCredential` and `DataLakeServiceClient` and this can be done by using a common HTTP client with proxy enabled. This can also avoid using the deprecated `proxyOptions` from `ClientSecretCredentialBuilder`.

Below is the modified code that worked:
```java

        HttpClient httpClient = new NettyAsyncHttpClientBuilder()
                .proxy(new ProxyOptions(ProxyOptions.Type.SOCKS5, new InetSocketAddress(proxyHost, proxyPort)))
                .responseTimeout(Duration.ofSeconds(3600))
                .build();
        ClientSecretCredential clientSecretCredential = new ClientSecretCredentialBuilder()
                .clientId(clientId)
                .clientSecret(clientKey)
                .tenantId(tenantId)
                .httpClient(httpClient)
                .build();
        DataLakeServiceClient serviceClient = new DataLakeServiceClientBuilder()
                .credential(clientSecretCredential)
                .endpoint("https://" + storageAccount + ".dfs.core.windows.net")
                .httpClient(httpClient)
                .buildClient();

        DataLakeFileSystemClient fileSystemClient = serviceClient.getFileSystemClient(fileSystem);
        DataLakeDirectoryClient directoryClient = fileSystemClient.getDirectoryClient(remotePath);
        DataLakeFileClient fileClient = directoryClient.getFileClient(remoteFile);
        fileClient.uploadFromFile(localFilePath, true);
```
