### ISSUE TITLE
Estimate total time out for an AmqpRetryOptions and/or AmqpRetryPolicy

### ISSUE THREAD

**Issue by YijunXieMS** [Azure/azure-sdk-for-java#17072]
PR #17039 added a method in MessageUtils to get the total timeout estimation from `AmqpRetryOptions` parameters.
This method can be moved to `AmqpRetryOptions` and/or `AmqpRetryPolicy`.

**Comment by anuchandy** [comment]
Closing this given there is no use-case to expose this as public API, but usage is limited to internal.
