### ISSUE TITLE
[Service Bus] ServiceBusMessage review follow up

### ISSUE THREAD

**Issue by ramya-rao-a** [Azure/azure-sdk-for-java#17081]
This is from the follow up after an internal review of the new `ServiceBusMessage` type

- The type for `DeliveryCount` and `GroupSequence` is long. Is this the best representation of uint which is what the AMQP spec expects?
- Add the constructor overload that takes the bytes back. This is for convenience just like we have an overload for string. BinaryData is a fairly new concept and is powerful in its own right, but folks who already have bytes in hand should not be forced to create a BinaryData first to create a ServiceBusMessage

cc @JoshLove-msft, @hemanttanwar, @srnagar, @conniey, @YijunXieMS, @JonathanGiles

**Comment by hemanttanwar** [comment]
1. "Add the constructor overload that takes the bytes back." "  PR  :   https://github.com/Azure/azure-sdk-for-java/pull/17173

**Comment by hemanttanwar** [comment]
`uint` is not directly represented in java. proton-j library takes care of this and expose `long` for us to use.

proton-j Library 's Message object expose `DeliveryCount ` as long : https://qpid.apache.org/releases/qpid-proton-j-0.33.5/api/org/apache/qpid/proton/message/Message.html#setDeliveryCount-long-

Same reasoning with `GroupSequence` : Thus we are representing as Long.
So we are not changing this.
