### ISSUE TITLE
[Core AMQP] AmpqAnnotatedMessage review follow up

### ISSUE THREAD

**Issue by ramya-rao-a** [Azure/azure-sdk-for-java#17080]
This is from the follow up after an internal review of the new `AmqpAnnotatedMessage` type
- MessageId and CorrelationId in `AmqpMessageProperties` should use a new type `AmqpMessageId` instead of just a string. This new type will currently support only string, but in the future can be expanded to other types
- To and ReplyTo properties in `AmqpMessageProperties` should use a new type `AmqpAddress` instead of just a string. This new type will currently support only string, but in the future can be expanded to other types
- The constructor overload that takes `AmqpAnnotatedMessage ` is not needed. Since the `AmqpAnnotatedMessage` class is only instantiated internally, the main overload is good enough for now

cc @JoshLove-msft, @hemanttanwar, @srnagar, @conniey, @YijunXieMS, @JonathanGiles

**Comment by hemanttanwar** [comment]
PR : https://github.com/Azure/azure-sdk-for-java/pull/17464
