### ISSUE TITLE
[QUERY] Is there a way to grant ROLE_ADMIN with azure-spring-boot-sample-active-directory-backend

### ISSUE THREAD

**Issue by cccs-cat001** [Azure/azure-sdk-for-java#17133]
**Query/Question**
I'm playing with the `/azure-sdk-for-java/sdk/spring/azure-spring-boot-samples/azure-spring-boot-sample-active-directory-backend` example and I see that it always grants ROLE_USER. Is there a way to make it also grant ROLE_ADMIN based on certain group membership? 

***Why is this not a Bug or a feature Request?***
A clear explanation of why is this not a bug or a feature request?
Because I'm not sure if this is possible, it's not documented anywhere which would lead you to say it's a feature request, but because in my experience there's _loads_ of undocumented features everywhere, I'm curious if this is one of them. 
**Setup (please complete the following information if applicable):**
 - OS:  Centos 7
 - IDE :  Spring tool suite
 - Version of the Library used 1.0.0
 
 **Information Checklist**
 Kindly make sure that you have added all the following information above and checkoff the required fields otherwise we will treat the issuer as an incomplete report
- [x] Query Added
- [x] Setup information Added

**Comment by joshfree** [comment]
@jialindai could you please help route this issue?

**Comment by cccs-cat001** [comment]
I've found that it is _kind of_ possible: https://github.com/Azure/azure-sdk-for-java/tree/master/sdk/spring/azure-spring-boot-starter-active-directory#authenticate-stateless-apis-using-aad-app-roles
However it doesn't work: https://github.com/Azure/azure-sdk-for-java/issues/17171

**Comment by yiliuTo** [comment]
Replyed in #17171 , for the usage of app roles, please refer to the [stateless sample](https://github.com/Azure/azure-sdk-for-java/tree/master/sdk/spring/azure-spring-boot-samples/azure-spring-boot-sample-active-directory-stateless).

**Comment by saragluna** [comment]
Closing this issue now.
