### ISSUE TITLE
InvalidAuthenticationToken

### ISSUE THREAD

**Issue by NewFishNeedWater** [Azure/azure-sdk-for-java#1714]
I'm using the file credentials to authenticate the SDK, but every time I will get the error:

Status code 401, {"error":{"code":"InvalidAuthenticationToken","message":"The received access token is not valid: at least one of the claims 'puid' or 'altsecid' or 'oid' should be present. If you are accessing as application please make sure service principal is properly created in the tenant."}}: The received access token is not valid: at least one of the claims 'puid' or 'altsecid' or 'oid' should be present. If you are accessing as application please make sure service principal is properly created in the tenant.

But when I try to use the restful API call , it works fine.

I just want to know what is the different between rest call & SDK.

Please note that we are partner of mircosoft(CSP) not end customer, so we are doing delegation on behalf of our end customer to manage resources.

file content :

client=********************************(AppID in our account not end customer)
key=*******************************(AppID in our account not end customer)
subscription=*******************************(sub ID for end customer)
tenant=***********************************(end customer mircosoft ID)
managementURI=https\://management.core.windows.net/
baseURL=https\://management.azure.com/
authURL=https\://login.windows.net/
graphURL=https\://graph.windows.net/

thanks!

**Comment by forcewake** [comment]
@NewFishNeedWater hello
Maybe you have some workarounds?

**Comment by martinsawicki** [comment]
not clear what could be going on here --- it'd be interesting to understand better how exactly you authenticate via REST, when you say it's working ok for you?

**Comment by yungezz** [comment]
hi @NewFishNeedWater is this still a problem for you?

**Comment by mayank-budhiraja** [comment]
@NewFishNeedWater in particular answer to 
`I just want to know what is the different between rest call & SDK.`

A SDK usually consists of tools along with APIs. On the other hand, APIs are sets of functions that expose functionality to application that the developer is programming.

Also, it works fine for me.

**Comment by xccc-msft** [comment]
@NewFishNeedWater Close this as no response. Please feel free to reopen if you still face same issue.
