### ISSUE TITLE
Using listBlobsByHierarchy api gets duplicate directory by chance

### ISSUE THREAD

**Issue by SJTUChenJi** [Azure/azure-sdk-for-java#17153]
**Describe the bug**
When using listBlobsByHierarchy api to get what the directories and files are under a directory,  a directory name sometimes appears twice in the result.

***Code Snippet***
String containerName = commonFSConf.get(CommonFSParameter.FS_BUCKET);
BlobContainerClient containerClient = blobServiceClient.getBlobContainerClient(containerName);
ArrayList<PathStatus> objList = new ArrayList<PathStatus>();
		try {
			getContainerClient();
			PagedIterable<BlobItem> blobItems = containerClient.listBlobsByHierarchy("enos/streaming/");
			for (BlobItem blobItem : blobItems) {
				PathStatus pathStatus = null;
				// dir
				if (blobItem.getName().endsWith("/")) {
					pathStatus = new PathStatus(blobItem.getName(), true);
				}
				// file
				else {
					BlobItemProperties blobItemProperties = blobItem.getProperties();
					pathStatus = new PathStatus(blobItem.getName(), blobItemProperties.getLastModified().toInstant(),
							blobItemProperties.getETag(), blobItemProperties.getContentLength(), false);
				}
				objList.add(pathStatus);
}				
for(PathStatus p :objList){
   System.out.println(p.getKey()); 
 }

**Expected behavior**
From the result, you will find "enos/streaming/o15596179429341/" appears twice.When using restful api doing same thing, the bug also appear.But the bug appears by chance.I guess because this query sent two times. So the result appears duplicate directory.

**Screenshots**
The result is as follows:
enos/streaming/o15452840095831
enos/streaming/o15453595539601
enos/streaming/o15488302255821
enos/streaming/o15555734875001
enos/streaming/o15596179429341
enos/streaming/o15452840095831/
enos/streaming/o15453595539601/
enos/streaming/o15488302255821/
enos/streaming/o15555734875001/
**enos/streaming/o15596179429341/**
enos/streaming/o15628308016831
enos/streaming/o15638787142121
enos/streaming/o15640381907881
enos/streaming/o15706178455521
enos/streaming/o15741352005031
enos/streaming/o15869202502361
**enos/streaming/o15596179429341/**
enos/streaming/o15628308016831/
enos/streaming/o15638787142121/
enos/streaming/o15640381907881/
enos/streaming/o15706178455521/
enos/streaming/o15741352005031/
enos/streaming/o15869202502361/
![image](https://user-images.githubusercontent.com/48346713/98066697-ba9f6980-1e92-11eb-9d2d-c1a7925a7275.png)

**Setup (please complete the following information):**
 - OS: mac os
 - IDE :IntelliJ
 - Version of the Library used: jdk1.8.0_241, azure-storage-blob:12.6.0

**Comment by rickle-msft** [comment]
@SJTUChenJi  Thank you for your question. This can happen if you have a blob with a name that is also a prefix for other blobs. For example if you have a blob named "foo/" and also a blob named "foo/bar". You will get one result for the blob itself and another result for the prefix element. I suspect if you examine the xml response you will see one entry that is from a prefix element and another that is from a blob element. The best way to handle this if you don't want to see both is to keep a cache of your listing results as you process them and eliminate any duplicates you encounter in iterating.

**Comment by SJTUChenJi** [comment]
Thank you for your reply. You think the reason is there are a blob and a prefix with the same name. But on Microsoft Azure Storage Explorer, there are a blob named "enos/streaming/o15596179429341" and a blob named "enos/streaming/o15596179429341/.streamsets-spark-streaming". So a similar example should be I have a blob named "foo" and also a blob named "foo/bar". Another confusing point is other blobs are similiar with "enos/streaming/o15596179429341", but only prefix named "enos/streaming/o15596179429341/" appears twice. And if you use restful api to send same request, xml response will be divided into two parts by "NextMarker" though there are only about twenty blobs and blobprefixs. Blobprefix named "enos/streaming/o15596179429341/" appears at the end of first xml response and also at the beginning of second xml response.
Maybe it's not a bug.But I am so curious why this happens. Thank you so much and look forward to your reply.

**Comment by rickle-msft** [comment]
@SJTUChenJi One easy way to test this theory with the sdk, is to print out alongside each path whether it was a blob or a prefix. It looks like you have this available in your PathStatus object if I'm correctly deducing the meaning of the boolean you pass in. For this experiment, I would recommend as well that instead of checking for a "/" at the end of the name, you use the `isPrefix()` method on the BlobItem.

As for the format of the results you're seeing, we can't really read too much into what the service gives back for these APIs. The service only guarantees a maximum value will be returned, but no minimum, so even though you requested 5000, it may only return 10 and a continuation token for the next 10. This is affected by a whole host of things from whether or not there are snapshots that it's iterating over and skipping, if there are a bunch of blobs it's collapsing into one prefix, or even other traffic to the tenant. The fact that you're seeing these duplicate entries split across pages I would suspect is due to the fact that there are a lot of blobs with the same prefix, but we can't really say for sure.

**Comment by SJTUChenJi** [comment]
Ok. Thank you for your explanation. Maybe the blobs are special causing the same prefix appears twice.

**Comment by rickle-msft** [comment]
@SJTUChenJi I think it is unlikely there is something special about the blob. Were you able to use the `isPrefix` method and print whether each entry is a blob or a prefix?

**Comment by amishra-dev** [comment]
please reactivate if you are still hitting this issue after trying the suggestion from Rick.
