### ISSUE TITLE
[QUERY] HDInsight error message is not clear enough when putting wrong storage account name

### ISSUE THREAD

**Issue by xccc-msft** [Azure/azure-sdk-for-java#17165]
**Query/Question**
I'm getting below message when creating cluster via HDInsight service.
The storage account name passed:
`https://<storage_account_name>.blob.core.windows.net/`

Get the error message:
`{"error":{"code":"GatewayTimeout","message":"The gateway did not receive a response from 'Microsoft.HDInsight' within the specified time period."}}`

It misled that the issue was from server end.

After I update the name to:
`<storage_account_name>.blob.core.windows.net`

Everything works fine with the updated value.

***Why is this not a Bug or a feature Request?***
It might be more like enhancement. It would be better if the service could return error message with clear info or link to some help-doc so that the users could investigate whether they need to update the request configurations.

**Setup (please complete the following information if applicable):**
 - IDE : [e.g. IntelliJ]
 - Version of the Library used
 
 **Information Checklist**
 Kindly make sure that you have added all the following information above and checkoff the required fields otherwise we will treat the issuer as an incomplete report
- [ ] Query Added
- [ ] Setup information Added

**Comment by yungezz** [comment]
hi @xccc-msft could you pls help to take care of this? thanks

**Comment by xccc-msft** [comment]
Adding `Service Attention` as it's required by service ask.

**Comment by aim-for-better** [comment]
Thanks for your feedback, I will investigate it.

**Comment by aim-for-better** [comment]
I have transferred this feedback to the service's backend team.
