### ISSUE TITLE
Downloading file from azure data lake is not working using DataLakeFileClient

### ISSUE THREAD

**Issue by maheshpg** [Azure/azure-sdk-for-java#17170]
I am trying to download file which is of 4 to 5 KB max from azure data lake zen2 account. Below is my code :

import com.azure.storage.common.StorageSharedKeyCredential;
import com.azure.storage.file.datalake.*;

import java.io.ByteArrayOutputStream;

public class DataLakeClient {

    public static void main(String[] args) {

        final StorageSharedKeyCredential sKeyCredential = new StorageSharedKeyCredential("devlake",
                "c8WrzvPxry87zdrR7BZ########################################RJN+yIaHg==");
        final DataLakeServiceClientBuilder builder = new DataLakeServiceClientBuilder();
        builder.credential(sKeyCredential);
        builder.endpoint("https://devlake.dfs.core.windows.net");

        DataLakeServiceClient dataLakeServiceClient = builder.buildClient();
        DataLakeFileSystemClient fileSystemClient = dataLakeServiceClient.getFileSystemClient("landingzone");
        DataLakeDirectoryClient directoryClient = fileSystemClient.getDirectoryClient("1hzhD7aqUJ6oYGLEwoQpHP70T2u/20201021/DB37iu0F2rCfJQ0vhGyVEoqPrzU");
        DataLakeFileClient fileClient = directoryClient.getFileClient("GSM_2_165_CH-EU-RU-UK-US_INSTR_DELTA_20201006_150829.csv");
        ByteArrayOutputStream byteArrayOutputStream = new ByteArrayOutputStream();
        fileClient.read(byteArrayOutputStream);
        System.out.println(byteArrayOutputStream.toByteArray());

    }
}

Above code gets stuck at fileClient.read(byteArrayOutputStream); call infinitely and finally client timeout exception comes. I am trying to run this from intellij on my local system. Using same DataLakeFileClient class I am able to create files on same directory location. but after creation and I am not able to read same file due to that stuck issue. I am not getting why I am not able to read file but able to write file using same class.

I am using  below dependency
<dependency>
            <groupId>com.azure</groupId>
            <artifactId>azure-storage-file-datalake</artifactId>
            <version>12.3.0-beta.1</version>
</dependency>

Any quick help is really appreciated.

**Comment by rickle-msft** [comment]
Hi, @maheshpg. Thank you for posting this question. Are you using any other dependencies in your project? And are able to see an outgoing download request on the network?

**Comment by maheshpg** [comment]
> Hi, @maheshpg. Thank you for posting this question. Are you using any other dependencies in your project? And are able to see an outgoing download request on the network?

Actually I found that on azure private link was enabled for DFS but not for BLOB. And for downloading file DataLakeFileClient was using blob service endpoint internally which was unknown to me. After enabling private endpoint for blob it is working.
Thanks for your quick response. But now this isssue can be closed.
