### ISSUE TITLE
[QUERY] how to use criteria builder  in cosmos 

### ISSUE THREAD

**Issue by s998899** [Azure/azure-sdk-for-java#17222]
Hi,

I am trying to find how to use criteria builder in cosmos but i didn't find anywhere.

I am working to create dynamic query if any other options there please tell.

my requirement is i need to call 4 parameters but need to be work on any a combinations like with one param or two params or all 4 params 

Thank you

**Comment by kushagraThapar** [comment]
@s998899 - which SDK are you using ? and what version ?
