### ISSUE TITLE
[QUERY] Does Spring Data Cosmos 3 support Sort?

### ISSUE THREAD

**Issue by sburlyaev** [Azure/azure-sdk-for-java#17225]
**Question**
Does `azure-spring-data-cosmos:3` support `org.springframework.data.domain.Sort`?

I'm trying to use it this way
```java
@Repository
public interface UserRepository extends CosmosRepository<User, String> {
@Query("SELECT * FROM c WHERE c.name = @name")
List<User> query(@Param("name") String name, Sort sort);
```
Looks like it just ignores the `Sort` object.

**Setup:**
 - com.azure:azure-spring-data-cosmos:3.1.0

**Comment by kushagraThapar** [comment]
@mbhaskar - please take a look at this.

**Comment by kushagraThapar** [comment]
@sburlyaev - yes it does, please see the tests and samples for this. There are multiple examples in `ProjectRepository`, `ReactiveRoleRepository` and `SortedProjectRepository`.

**Comment by sburlyaev** [comment]
@kushagraThapar  could you please share the links?

**Comment by kushagraThapar** [comment]
@sburlyaev - https://github.com/Azure/azure-sdk-for-java/blob/master/sdk/cosmos/azure-spring-data-cosmos-test/src/test/java/com/azure/spring/data/cosmos/repository/repository/ReactiveRoleRepository.java#L20

https://github.com/Azure/azure-sdk-for-java/blob/master/sdk/cosmos/azure-spring-data-cosmos-test/src/test/java/com/azure/spring/data/cosmos/repository/repository/SortedProjectRepository.java

**Comment by sburlyaev** [comment]
```java
@Query("SELECT * FROM c WHERE c.senderId = @senderId")
Flux<Invitation> findBySenderId(@Param("senderId") String senderId, Sort sort);
```
fails for some reason with: 
```
Caused by: com.azure.cosmos.CosmosException:
{"innerErrorMessage":"Gateway Failed to Retrieve Query Plan: Message:
{\"Errors\":[\"Invalid query. Specified parameter name '@' is invalid.
Parameter names should be in the format of symbol '@' followed by a valid identifier.
```
but without `@Query`
```java
Flux<Invitation> findBySenderId(String senderId, Sort sort);
```
works for me. Thanks!

**Comment by kushagraThapar** [comment]
@sburlyaev  - please see how it is used here - https://github.com/Azure/azure-sdk-for-java/blob/master/sdk/cosmos/azure-spring-data-cosmos-test/src/test/java/com/azure/spring/data/cosmos/repository/integration/ReactiveRoleRepositoryIT.java#L57
And this is the annotated query method - https://github.com/Azure/azure-sdk-for-java/blob/master/sdk/cosmos/azure-spring-data-cosmos-test/src/test/java/com/azure/spring/data/cosmos/repository/repository/ReactiveRoleRepository.java#L20
