### ISSUE TITLE
[FEATURE REQ] Ability to specify timeout per operation

### ISSUE THREAD

**Issue by kasobol-msft** [Azure/azure-sdk-for-java#17236]
**Is your feature request related to a problem? Please describe.**
Ability to specify timeout per operation

**Describe the solution you'd like**
This is follow up from https://github.com/Azure/azure-sdk/issues/1984 . The UploadFromUrl API that is being introduced is potentially blocking and long running depending on what customer is moving over the network. If customer is aware that their workload require larger timeout for this operation they should be able to specify that without impacting other APIs.

**Additional context**
See  https://github.com/Azure/azure-sdk/issues/1984 

**Information Checklist**
Kindly make sure that you have added all the following information above and checkoff the required fields otherwise we will treat the issuer as an incomplete report
- [ X] Description Added
- [X ] Expected solution specified

**Comment by alzimmermsft** [comment]
This may have correlation to https://github.com/Azure/azure-sdk-for-java/issues/12106.

Right now there is the ability to configure the `HttpClient`s with operational timeouts for sending request, awaiting response, receiving response but these are static for the lifetime of the `HttpClient`. This could be updated to allow for `Context` to pass a per operation timeout which takes precedence over the build time one and fallback to build time if a value isn't passed.

**Comment by kasobol-msft** [comment]
Yes looks like linked issue would address this as long as it reaches deep enough to override HttpClient's static timeout in scope of single operation.

**Comment by alzimmermsft** [comment]
This has been completed for the Netty HttpClient but the OkHttp HttpClient doesn't have an API for this. OkHttp, and eventually JDK, will need further investigation.

https://github.com/Azure/azure-sdk-for-java/pull/23244 (Netty PR)
