### ISSUE TITLE
Java storage pipeline fails with the request was abandonded

### ISSUE THREAD

**Issue by gapra-msft** [Azure/azure-sdk-for-java#17230]
https://dev.azure.com/azure-sdk/internal/_build/results?buildId=600556&view=logs&j=a0ac0873-b59c-576c-7b80-8d2288668a7e

The request: 3796979 was abandoned due to an infrastructure failure. Notification of assignment to an agent was never received.

**Comment by alzimmermsft** [comment]
Closing as this hasn't been seen recently
