### ISSUE TITLE
[QUERY] How do you use UserPrincipal::getAccessTokenForGraphApi? 

### ISSUE THREAD

**Issue by cccs-cat001** [Azure/azure-sdk-for-java#17273]
**Query/Question**
I'm looking to do requests to the AAD graph API, however it seems that the token is null when I call the above method. I see there's a setter for it, how do I fetch the token for the graph in order to use that getter/setter? 

***Why is this not a Bug or a feature Request?***
Because it's a question, I see that the API is set up for a graph API token, but there is no clear indication of how to use it. 

**Setup (please complete the following information if applicable):**
 - OS: [e.g. iOS] centos7
 - IDE : [e.g. IntelliJ] Spring Tool Suite
 - Version of the Library used: 3.0.0-beta.1
 - Library in question: com.azure.spring:azure-spring-boot-starter-active-directory
 
 **Information Checklist**
 Kindly make sure that you have added all the following information above and checkoff the required fields otherwise we will treat the issuer as an incomplete report
- [x] Query Added
- [x] Setup information Added

**Comment by cccs-cat001** [comment]
More info that may be useful: 

I am looking at the `azure-spring-boot-sample-active-directory-stateless` demo app, and I see it adds a `AADAppRoleStatelessAuthenticationFilter` filter in its security config. But that filter doesn't populate the graph api token in the UserPrincipal like the `AADAuthenticationFilter` filter does. 
The `AADAuthenticationFilter` filter is applied _only_ when `azure.activedirectory.session-stateless=false`. So I guess I'm wondering now, is there a way to have the graph api token populated while `azure.activedirectory.session-stateless` is true? 

I want the session-stateless to be true because that allows me to do `@PreAuthorize` with roles assigned in the AD App Registration instead of to groups provided in the properties files.

**Comment by joshfree** [comment]
@jialindai could you please assist?

**Comment by yiliuTo** [comment]
Hi @cccs-cat001 , **AADAppRoleStatelessAuthenticationFilter** populates the token into UserPrincipal when build this object. Here are the code of `buildUserPrincipal` function called in the stateless filter: 
https://github.com/Azure/azure-sdk-for-java/blob/a4de60b63699b85d271792258ef8dee45d65f37a/sdk/spring/azure-spring-boot/src/main/java/com/azure/spring/autoconfigure/aad/UserPrincipalManager.java#L153

**Comment by cccs-cat001** [comment]
That's the issuedBearerToken, that grants me a token for my app registration, I'm looking for the access token for the graph API. I've found that it only gets put in the UserPrincipal here: https://github.com/Azure/azure-sdk-for-java/blob/a4de60b63699b85d271792258ef8dee45d65f37a/sdk/spring/azure-spring-boot/src/main/java/com/azure/spring/autoconfigure/aad/AADAuthenticationFilter.java#L113-L116 

I want to be able to preauthorize endpoints using the roles in the app registration, and I've found the only way to do that is with `azure.activedirectory.session-stateless=true`, but when that is enabled the AADAuthenticationFilter does not get enabled in favour of the AADAppRoleStatelessAuthenticationFilter. 
I need the Graph API token so I can query it for more user info such as their group membership and profile picture.

**Comment by yiliuTo** [comment]
Hi @cccs-cat001 , sorry that our **AADAppRoleStatelessAuthenticationFilter** cannot meet your requirements currently, the filter doesn't aquire access token from Graph API so it cannot populate any other access tokens into UserPrinciple. But to acuqire OBO tokens for other resources is in our roadmap, so you could wait for our new features.

**Comment by cccs-cat001** [comment]
OBO tokens would be nice to have.. Is there a timeline for this feature?

**Comment by chenrujun** [comment]
@cccs-cat001 , if everything goes well, we can release obo function within 6 months. But not 100% sure.

**Comment by saragluna** [comment]
Hi @cccs-cat001, the support for OBO in AAD starter has been released along with the latest release. Please refer [here](https://github.com/Azure/azure-sdk-for-java/tree/master/sdk/spring/azure-spring-boot-starter-active-directory#oauth-20-on-behalf-of-flow-web-apis) to check how to use it. 

Closing this issue now.
