### ISSUE TITLE
[FEATURE REQ] Add the ability to customize the scheduler used for timeouts/delays instead of creating a `Schedulers.parallel` by default on the blob storage client

### ISSUE THREAD

**Issue by fcofdez** [Azure/azure-sdk-for-java#17272]
**Is your feature request related to a problem? Please describe.**
Currently in all the code handling timeouts/delayed subscriptions (at least on the storage project  see [[1]](https://github.com/Azure/azure-sdk-for-java/blob/7fb04590b83a8ec6863708d268d5dbe6a994af4e/sdk/storage/azure-storage-blob/src/main/java/com/azure/storage/blob/specialized/ReliableDownload.java#L122), [[2]](https://github.com/Azure/azure-sdk-for-java/blob/60bec6e818d5ddbc496883e0a8667de32e6dafef/sdk/storage/microsoft-azure-storage-blob/src/main/java/com/microsoft/azure/storage/blob/RequestRetryFactory.java#L151-L152)) use by default the `Schedulers.parallel()` which might be convenient in some cases but it doesn't allow a fine grained control of the resources used by the client.  

**Describe the solution you'd like**
I would like to be able to inject a `ScheduledExecutorService` to be used in those cases, avoiding any unintended thread pool creation.

**Describe alternatives you've considered**
I was able to circumvent this limitation partially (i.e. creating a custom HttpPipeline that uses a custom request retry policy),
but in other parts of the client it's impossible to inject a custom Scheduler

**Additional context**
It seems like in other parts of the SDK this was possible at some point, see https://github.com/Azure/azure-sdk-for-java/issues/5466

**Information Checklist**
Kindly make sure that you have added all the following information above and checkoff the required fields otherwise we will treat the issuer as an incomplete report
- [x] Description Added
- [x] Expected solution specified

**Comment by fcofdez** [comment]
I've just noticed that reactor `Schedulers` allows to inject a custom factory, but in any case that's an implementation detail that should be hidden from the users.

**Comment by rickle-msft** [comment]
@JonathanGiles Do you have thoughts on how we should expose this to the public API surface?

**Comment by JonathanGiles** [comment]
Thanks for the feature request @fcofdez. I'll give some thought on how we could expose this. One option we have is to make this a configuration option present in our [ClientOptions](https://github.com/Azure/azure-sdk-for-java/blob/master/sdk/core/azure-core/src/main/java/com/azure/core/util/ClientOptions.java) type. That would mean that we would apply this to all clients that are given this ClientOptions instance in their builder (and we are still in the process of introducing ClientOptions to all builders).
