### ISSUE TITLE
Migration Guide for Event Hubs

### ISSUE THREAD

**Issue by AlexGhiondea** [Azure/azure-sdk-for-java#17294]
Please wait for this issue to be updated with the link to the Migration Guide template.

For Event Hubs, we already have a migration guide. Once the template is ready, this issue is to track the work to get the current guide to follow the template

**Comment by ramya-rao-a** [comment]
Please use the template in this [PR that adds the migration guide to our policies](https://github.com/Azure/azure-sdk/pull/2132)
