### ISSUE TITLE
Bug bash to find samples for Event Hubs that need to use the latest package

### ISSUE THREAD

**Issue by AlexGhiondea** [Azure/azure-sdk-for-java#17298]
_Update from @ramya-rao-a_ 

Review the Java samples for Event Hubs in the below locations to find the ones that do not use the latest version of the package. Update this issue with the list of samples that need updating.

- [Event Hubs Java samples repos under Azure-samples org](https://github.com/Azure-Samples?q=%22Event+Hubs%22&type=&language=java)
- [Event Hubs Java samples under docs.microsoft.com/samples](https://docs.microsoft.com/en-us/samples/browse/?terms=%22Event%20Hubs%22&languages=java)

Additionally, ensure the samples that live next to the source code for Event Hubst in this repo shows up in [Event Hubs Java samples under docs.microsoft.com/samples](https://docs.microsoft.com/en-us/samples/browse/?terms=%22Event%20Hubs%22&languages=java). This is done by setting up the right metadata. Ensure that these samples are not outdated.

**Comment by conniey** [comment]
https://docs.microsoft.com/en-us/samples/browse/?terms=%22Event%20Hubs%22&languages=java
* azure-messaging-eventhubs samples do not show up in browser.
* azure-messaging-eventhubs-checkpointstore-blob show up in browser.

**Comment by ramya-rao-a** [comment]
Thanks @conniey 
@scbedd will follow up regarding the issue you found
