### ISSUE TITLE
Updated outdated content from bug bash in samples for Service Bus

### ISSUE THREAD

**Issue by AlexGhiondea** [Azure/azure-sdk-for-java#17307]
Update the outdated content found in https://github.com/azure/azure-sdk-for-java/issues/17305

**Comment by hemanttanwar** [comment]
These are all the PRs

https://github.com/Azure-Samples/service-bus-java-manage-publish-subscribe-with-basic-features/pull/4
https://github.com/Azure-Samples/service-bus-java-manage-queue-with-basic-features/pull/5
https://github.com/Azure-Samples/service-bus-java-manage-publish-subscribe-with-advanced-features/pull/3
https://github.com/Azure-Samples/service-bus-java-manage-with-claims-based-authorization/pull/3
https://github.com/Azure-Samples/service-bus-java-manage-queue-with-advanced-features/pull/3/files

This work is done.,
