### ISSUE TITLE
Bug bash to find samples for Service Bus that need to use the latest package

### ISSUE THREAD

**Issue by AlexGhiondea** [Azure/azure-sdk-for-java#17305]
_Update from @ramya-rao-a_ 

Review the Java samples for Service Bus in the below locations to find the ones that do not use the latest version of the Service Bus package. Please note that some of these maybe using the preview version of the latest Service Bus package, these need to be identified as well. Update this issue with the list of samples that need updating.

- [Service Bus Java samples repos under Azure-samples org](https://github.com/Azure-Samples?q=%22Service+Bus%22&type=&language=java)
- [Service Bus Java samples under docs.microsoft.com/samples](https://docs.microsoft.com/en-us/samples/browse/?terms=%22Service%20Bus%22&languages=java)

Additionally, ensure the samples that live next to the source code for Service Bus in this repo shows up in [Service Bus Java samples under docs.microsoft.com/samples](https://docs.microsoft.com/en-us/samples/browse/?terms=%22Service%20Bus%22&languages=java). This is done by setting up the right metadata. Ensure that these samples are not outdated.

**Comment by hemanttanwar** [comment]
Following should use GA version of Service Bus library

- https://github.com/Azure-Samples/service-bus-java-manage-publish-subscribe-with-basic-features/blob/master/pom.xml#L72
- https://github.com/Azure-Samples/service-bus-java-manage-queue-with-basic-features/blob/master/pom.xml#L72
- https://github.com/Azure-Samples/service-bus-java-manage-publish-subscribe-with-advanced-features/blob/master/pom.xml#L72
- https://github.com/Azure-Samples/service-bus-java-manage-queue-with-advanced-features/blob/master/pom.xml#L72
- https://github.com/Azure-Samples/service-bus-java-manage-with-claims-based-authorization/blob/master/pom.xml#L72

**Comment by hemanttanwar** [comment]
These are all the PRs

https://github.com/Azure-Samples/service-bus-java-manage-publish-subscribe-with-basic-features/pull/4
https://github.com/Azure-Samples/service-bus-java-manage-queue-with-basic-features/pull/5
https://github.com/Azure-Samples/service-bus-java-manage-publish-subscribe-with-advanced-features/pull/3
https://github.com/Azure-Samples/service-bus-java-manage-with-claims-based-authorization/pull/3
https://github.com/Azure-Samples/service-bus-java-manage-queue-with-advanced-features/pull/3/files

This work is done.,
