### ISSUE TITLE
Reference doc bug bash (look for both content issues and rendering issues) for Key Vault

### ISSUE THREAD

**Issue by AlexGhiondea** [Azure/azure-sdk-for-java#17311]

**Comment by vcolin7** [comment]
- Talked to @scbedd about discrepancies in the docs rendering approach for different languages. For example, Java docs don't rendering all nodes at the package level like JS does:
     
    Java
    ![image](https://user-images.githubusercontent.com/5799331/102476364-a10c4880-4020-11eb-9d44-28205328b417.png)
    
    JS
    ![image](https://user-images.githubusercontent.com/5799331/102476561-e0d33000-4020-11eb-85a8-a9f4d9b3ff4f.png)

- Found that all code snippets are shifted one space to the right after the first line, even though the original code does not include said spaces:
    ![image](https://user-images.githubusercontent.com/5799331/102475833-feec6080-401f-11eb-9509-fd59738ca69c.png)
- Will probably need to add a Resource Management node for Preview docs. It is currently only found in Stable.
    
    ![image](https://user-images.githubusercontent.com/5799331/102476200-6f937d00-4020-11eb-8eb3-4a5abce70438.png)
    
    ![image](https://user-images.githubusercontent.com/5799331/102476213-74583100-4020-11eb-84be-f4fc1b7134b5.png)

- Working on cleaning up the Javadoc for all data plane Key Vault packages.

**Comment by vcolin7** [comment]
Created [a small PR](https://github.com/Azure/azure-docs-sdk-java/pull/1588) for adding the Service Overview page to the Stable ToC. Preview is still pending but @scbedd is aware of this issue.
