### ISSUE TITLE
Bug bash to find samples for Key Vault that need to use the latest package

### ISSUE THREAD

**Issue by AlexGhiondea** [Azure/azure-sdk-for-java#17312]
_Update from @ramya-rao-a_ 

Review the Java samples for Key Vault in the below locations to find the ones that do not use the latest version of the package. Update this issue with the list of samples that need updating.

- [Key Vault Java samples repos under Azure-samples org](https://github.com/Azure-Samples?q=%22Key+Vault%22&type=&language=java)
- [Key Vault Java samples under docs.microsoft.com/samples](https://docs.microsoft.com/en-us/samples/browse/?terms=%22Key%20Vault%22&languages=java)

Additionally, ensure the samples that live next to the source code for Key Vault in this repo shows up in [Key Vault Java samples under docs.microsoft.com/samples](https://docs.microsoft.com/en-us/samples/browse/?terms=%22Key%20Vault%22&languages=java). This is done by setting up the right metadata. Ensure that these samples are not outdated.

**Comment by vcolin7** [comment]
I could not find any data plane Key Vault samples that need a package update.

I did find a few (possibly relevant) places where Track 1 Key Vault code is used, which haven't been updated since 2018:
- [Authentication samples for Azure Key Vault using the Azure Java SDK](https://github.com/Azure-Samples/key-vault-java-authentication)
- [Java Azure Key Vault Deploy Certificates to Vault and Certificate based Authenication](https://github.com/Azure-Samples/key-vault-java-certificate-authentication)
- [Recovery scenario samples for Azure Key Vault using the Azure Java SDK](https://github.com/Azure-Samples/key-vault-java-recovery)

**Comment by vcolin7** [comment]
There are more samples in [this list](https://github.com/Azure-Samples?q=%22Key+Vault%22&type=&language=java) that have not been updated since 2018, but I don't know which ones are still relevant or worth updating :/

**Comment by vcolin7** [comment]
The following are some more repositories from the aforementioned list that use Track 1 data plane code in their samples, even if some of them have Track 2 references in their README:

- [Hybrid-KeyVault-Java-Manage-Secrets-Certificate-Based-Auth](https://github.com/Azure-Samples/Hybrid-KeyVault-Java-Manage-Secrets-Certificate-Based-Auth)
- [Vnet/IP ACL sample for Azure Key Vault using the Azure Java SDK](https://github.com/Azure-Samples/key-vault-java-network-acl)
- [Managed Storage Authentication sample for Azure Key Vault using the Azure Key Vault SDK](https://github.com/Azure-Samples/key-vault-java-managed-storage)
- [Getting Started with Azure Client Side Encryption in Java](https://github.com/Azure-Samples/storage-java-client-side-encryption)

Bonus: This is a sample that uses a very outdated version of Azure Spring Boot Starter for Key Vault Secrets (`0.1.8`, the latest one is `2.3.5`).

- [Todo App Java On Azure](https://github.com/microsoft/todo-app-java-on-azure)

I could reach this sample through:

- [Getting Started with Appservice - Manage Web App Cosmos Db By Msi - in Java](https://github.com/Azure-Samples/app-service-java-access-key-vault-convenience-for-web-apps#getting-started-with-appservice---manage-web-app-cosmos-db-by-msi---in-java)
- [Getting Started with Appservice - Manage Web App Cosmos Db Through Key Vault - in Java](https://github.com/Azure-Samples/app-service-java-access-key-vault-by-msi-for-web-apps#getting-started-with-appservice---manage-web-app-cosmos-db-through-key-vault---in-java)
- [Getting Started with Appservice - Manage Linux Web App Cosmos Db By Msi - in Java](https://github.com/Azure-Samples/app-service-java-access-key-vault-convenience-for-web-apps-on-linux#getting-started-with-appservice---manage-linux-web-app-cosmos-db-by-msi---in-java)
Found in the repository list mentioned in the description of this issue.

**Comment by vcolin7** [comment]
Some observations:

- Most samples should be fairly straightforward to update to use Track 2 data plane Key Vault SDKs, however, I'm not familiar with some of the scenarios they are trying to demonstrate, so I cannot exactly estimate how long it would take to update the code and verify things work correctly.
- Numbers [1](https://github.com/Azure-Samples/key-vault-java-certificate-authentication) and [4](url) share a good deal of code for classes `KeyVaultADALAuthenticator.java` and `KeyVaultCertificateAuthenticator.java`.
- Number1 [1](https://github.com/Azure-Samples/key-vault-java-authentication), [3](https://github.com/Azure-Samples/key-vault-java-recovery), [5](https://github.com/Azure-Samples/key-vault-java-network-acl) and [6](https://github.com/Azure-Samples/key-vault-java-managed-storage) use the Track 1 Key Vault management plane library as well, it's probably a good idea to update both libraries to Track 2 at the same time if possible.
- Numbers [6](https://github.com/Azure-Samples/key-vault-java-managed-storage) and [7](https://github.com/Azure-Samples/storage-java-client-side-encryption) also make use of the Track 1 Storage client library.
- Most of these also make use of Track 1 authentication flows, so we will have to update to use the Track 2 Azure Identity library.
