### ISSUE TITLE
StackOverflow cleanup Track 1 references, answer unanswered questions for Key Vault

### ISSUE THREAD

**Issue by AlexGhiondea** [Azure/azure-sdk-for-java#17310]

**Comment by vcolin7** [comment]
Finally took some time to address this and answered the following unanswered questions:

- [Resolve guava conflict between spark core and azure key vault dependency](https://stackoverflow.com/a/65745783/4967034)
- [Azure - NoSuchMethodExist error in ApplicationTokenCredential while trying to get key from keyVault](https://stackoverflow.com/a/65745783/4967034)

Also added comments to the following:

- [Azure Key Vault with SFTP Integration](https://stackoverflow.com/questions/62713054/azure-key-vault-with-sftp-integration#comment116242231_62713054)
- [Service or property not registered Azure KeyVault](https://stackoverflow.com/questions/41604812/service-or-property-not-registered-azure-keyvault#comment116242611_41604812)

**Comment by vcolin7** [comment]
Should we also look into questions that are answered but still not marked as resolved?

**Comment by joshfree** [comment]
Closing old issue.
