### ISSUE TITLE
Updated outdated content from bug bash in docs.microsoft.com for Key Vault

### ISSUE THREAD

**Issue by AlexGhiondea** [Azure/azure-sdk-for-java#17313]
_Update from @ramya-rao-a_ 

We have not found any reference to the older Key Vault packages from any of the docs under https://docs.microsoft.com/en-us/azure/key-vault/general/, but there was one issue found. There are no nodes for Java Quick Starts for keys and certificates. Check under the "Quickstarts" node in the toc for the below pages
- [Certificates](https://docs.microsoft.com/en-us/azure/key-vault/certificates/)
- [Keys](https://docs.microsoft.com/en-us/azure/key-vault/keys/)

**Comment by vcolin7** [comment]
Is MicrosoftDocs' [azure-docs repo](https://github.com/MicrosoftDocs/azure-docs) the correct one to fork for this? @ramya-rao-a

**Comment by vcolin7** [comment]
Created a PR against the aforementioned repository for the time being.

**Comment by ramya-rao-a** [comment]
That sounds good @vcolin7!

**Comment by vcolin7** [comment]
Quickstarts for [Certificates](https://docs.microsoft.com/en-us/azure/key-vault/certificates/quick-create-java) and [Keys](https://docs.microsoft.com/en-us/azure/key-vault/keys/quick-create-java) have been added :)
