### ISSUE TITLE
Add localNetworkGateways and virtualNetworkGateways to Fluent API

### ISSUE THREAD

**Issue by albuch** [Azure/azure-sdk-for-java#1734]
Currently it's not possible to get LocalNetworkGateways and VirtualNetworkGateways via `com.microsoft.azure.management.Azure` API
The functionality however is available in `NetworkManagementClientImpl`.

Shouldn't be all API calls from `NetworkManager` be supported in a 1.0release version? This gets even more tedious currently as the `NetworkManager` is a private field of `com.microsoft.azure.management.Azure`.

**Comment by martinsawicki** [comment]
correct, VPN API is not yet exposed via the Fluent API layers and can only be worked with using the autogenerated inner layers. 
The fluent API can still be used as an entry point to it - you can get to  `NetworkManagementClientImpl` via `NetworkManager.inner()`. You can get to `NetworkManager` either directly via `NetworkManager.authenticate()` if only using Azure networking, or via any of the networking resource objects, e.g. `Azure.networks().manager()`)

**Comment by albuch** [comment]
Thanks, `azure.networks().manager().inner()` does the trick, didn't see that method.

**Comment by martinsawicki** [comment]
initial part of vnet gateway support was released in v1.3
