### ISSUE TITLE
[QUERY] Is access token allowed instead of id token? 

### ISSUE THREAD

**Issue by de87684333** [Azure/azure-sdk-for-java#17354]
**Query/Question**
In the previous, azure-active-directory-spring-boot-starter it seems that only id_token are expected as an input (parameter names is "idToken". Also the diagram precise id_token). But in the case of a SPA application & a spring backend application (that are in 2 distinct app registration), we expect to exchange an access token. 

Is the previous library handle this case?
When the release of the new version of this library is planned?

***Why is this not a Bug or a feature Request?***
It seems that in the coming update 3.0.0 version of the library it's handle (at least the parameter has been renamed) but the diagram still mentioned only id_token.

**Setup (please complete the following information if applicable):**
 - Version of the Library used : 
        <dependency>
            <groupId>com.microsoft.azure</groupId>
            <artifactId>azure-active-directory-spring-boot-starter</artifactId>
            <version>2.3.5</version>
        </dependency>
 
 **Information Checklist**
 Kindly make sure that you have added all the following information above and checkoff the required fields otherwise we will treat the issuer as an incomplete report
- [v] Query Added
- [v] Setup information Added

**Comment by de87684333** [comment]
To add on this topic:
I saw that in the case "ID Token mode usage(Stateless implicit)", that the audience is checked but it's not the case in this other case.
Could you clarify why audience is checked only in this case?

**Comment by de87684333** [comment]
Anyone could help on this topic?

**Comment by chenrujun** [comment]
Hi, @de87684333 .

> In the previous, azure-active-directory-spring-boot-starter it seems that only id_token are expected as an input (parameter names is "idToken". Also the diagram precise id_token). But in the case of a SPA application & a spring backend application (that are in 2 distinct app registration), we expect to exchange an access token.

IMU, accessToken is also supported. It's a mistake in diagram. (@saragluna , @moarychan , please confirm. 🙏 )

> When the release of the new version of this library is planned?

We will release 3.0.0 on the mid of next month.

> I saw that in the case "ID Token mode usage(Stateless implicit)", that the audience is checked but it's not the case in this other case.
> Could you clarify why audience is checked only in this case?

We plan to deprecate the function of resource-server(web api) in the starter, if you have this requirement, please use spring-security resource-server instead.

Refs: https://docs.spring.io/spring-security/site/docs/current/reference/html5/#oauth2resourceserver-jwt-validation-custom

**Comment by saragluna** [comment]
@de87684333 to clarify the `deprecate the basic function of resource-server`, we're planning to deprecate the two filters we provided, but we're also working to integrate with spring-security-resource-server, such as adding more AAD specific claim validator (the audience, the issuer...) and out-of-box OBO support in resource server cases. Hopefully, it won't take 6 months to complete. Please stay tuned.

In the case of a resource server we will receive access tokens, but whether to accept id tokens is not finalized yet. We'll update the diagram.

**Comment by de87684333** [comment]
@chenrujun @saragluna 
Thanks for your answers and clarifications. I'll then wait the next release to see how can I use the library.
