### ISSUE TITLE
[QUERY] Upload is freezing on slow internet connection.

### ISSUE THREAD

**Issue by mateuszluczak1996** [Azure/azure-sdk-for-java#17356]
**Query/Question**
Upload is freezing on slow internet connection.

I am working on android application written in kotlin which transfer data to azure storage. 
When internet connection is fast and stable like Wi-Fi, there is a no problem with upload files to azure.
Problem occurring when internet connection is slow such as ~6 Mbps (upload speed). 
The issue seems to be occurring after the all blocks are added to the block blob's "staging area" using method:
`public Mono<Response<Void>> stageBlockWithResponse(String base64BlockId, Flux<ByteBuffer> data, long length,
        byte[] contentMd5, String leaseId)` and we are waiting for finalize to commit block list.
I wait for a long time but nothing happens (no error is thrown).

Maximum size of uploaded file: ~150 MB.

Snippet code of current implementation: [https://gist.github.com/mateuszluczak1996/2fbfe82c70a3754e75d7f4e205c74f4c](url)

***Why is this not a Bug or a feature Request?***
No error is thrown in current implementation.

**Setup (please complete the following information if applicable):**
 - OS: development: Windows 10, tested on OnePlus 6T with Android 10
 - IDE : Android Studio: 4.1
 - Version of the Library used: group: 'com.azure', name: 'azure-storage-blob', version: '12.0.1'
 
 **Information Checklist**
 Kindly make sure that you have added all the following information above and checkoff the required fields otherwise we will treat the issuer as an incomplete report
- [x] Query Added
- [x] Setup information Added

**Comment by joshfree** [comment]
@anuchandy could you please assist @mateuszluczak1996

**Comment by mateuszluczak1996** [comment]
Can anyone help me with this issue?

**Comment by mateuszluczak1996** [comment]
@anuchandy

**Comment by anuchandy** [comment]
@mateuszluczak1996 sorry for the delay in following up.

Unfortunately, the Java SDK dependencies are not officially supported on Android (e.g., reactor, netty); hence, APIs usage is not always guaranteed to work. Additionally, the operations such as upload on Android require a persisting state to honor the Android scheduling system.

We are in the process of building a Java SDK that natively supports mobile. The work is happening in [azure-sdk-for-android]( https://github.com/Azure/azure-sdk-for-android).

We have an implementation of storage file upload in this repo: the API root is [here](https://github.com/Azure/azure-sdk-for-android/blob/d5462f52b29e02ddce56b8df00dbef782c881233/sdk/storage/azure-storage-blob/src/main/java/com/azure/android/storage/blob/StorageBlobAsyncClient.java#L131) 

The dependencies and APIs used in this repo are Android compatible (with min API L21). Additionally, the upload API is stateful and uses the android scheduling system and work manager for reliably uploading the files. This means, the upload is taken care even if user switch to another app.

Please note that the library is not published, so our recommendation is to use the code in this repo as a reference to implement upload in your application. It seems you're using android 10 (API L29), so all the APIs used by android upload code will work.

Let me know if you have any question regarding the design of reliable-upload or if you find we missed any edge case. I'm happy to address and assist.

I'm closing this issue, but feel free to follow up on the above repo [azure-sdk-for-android]( https://github.com/Azure/azure-sdk-for-android) and tag me.
