### ISSUE TITLE
[Service Bus] Review Quick Start doc for Track 2 Service Bus

### ISSUE THREAD

**Issue by ramya-rao-a** [Azure/azure-sdk-for-java#17360]
This issue is to track the review of the quick start docs that @spelluru has written for azure-messaging-servicebus library.
Use either this issue or email to share feedback with @spelluru and close this issue once we are satisfied with the content.

- [Quick start for Queues](https://review.docs.microsoft.com/en-us/azure/service-bus-messaging/service-bus-java-how-to-use-queues?branch=release-service-bus-track2-sdk-ga)
- [Quick start for Topics & Subscriptions](https://review.docs.microsoft.com/en-us/azure/service-bus-messaging/service-bus-java-how-to-use-topics-subscriptions?branch=release-service-bus-track2-sdk-ga)

Please note
- For receiving messages, we should use the processor client
- For sending messages, we should use the sync client

**Comment by spelluru** [comment]
Hi @richardpark-msft -  Please wait until tomorrow morning to review the quick start. I am going to test with the latest preview packages and update the quick starts today. Thanks!

**Comment by spelluru** [comment]
Hi @richardpark-msft - The above two articles are ready for your review now. I tried to keep the quick start as simple as possible with the following in mind: 

- Use Sync
- Use batching
- Use Processor Client

And, provide a link to all the samples on GitHub. 

I appreciate if you could review and provide your feedback as soon as you can. 

Thanks,
Sreedhar

**Comment by richardpark-msft** [comment]
Okay, I submitted a PR and it's been merged with all of my review comments.

(For the record): https://github.com/MicrosoftDocs/azure-docs-pr/pull/137296
