### ISSUE TITLE
[BUG] Endpoint Generation Error

### ISSUE THREAD

**Issue by LIN-Yu-Ting** [Azure/azure-sdk-for-java#17420]
**Describe the bug**
https://github.com/Azure/azure-sdk-for-java/blob/8fa90181fdf4f780aad9bd9cda2959d5a81e7c38/sdk/storage/azure-storage-file-datalake/src/main/java/com/azure/storage/file/datalake/DataLakeServiceClientBuilder.java#L112

In the above link, we found that function DataLakeImplUtils.endpointToDesiredEndpoint will return erroneous result when there is "dfs" in the input endpoint (String) such as "https://dfstest.dfs.core.windows.net"

With the provided endpoint value, return result will then be:
https:/.blob.est.dfs.core.windows.net

which will cause other error. The root cause of this issue is wrong usage of relaceFirst function with .dfs. regex input.

Thanks for your efforts to fix this issue. Thanks in advance.

**Comment by gapra-msft** [comment]
Hi @LIN-Yu-Ting 

Thank you for reporting this issue. We will fix this as soon as we can.
