### ISSUE TITLE
[BUG] Storage nightly build fails to deploy test resources

### ISSUE THREAD

**Issue by rickle-msft** [Azure/azure-sdk-for-java#17448]
Both Java8 and Java11

https://dev.azure.com/azure-sdk/internal/_build/results?buildId=613386&view=logs&j=5f8c201a-938a-5282-2c48-ae83406ca22f&t=1fe788fe-67b6-5abb-540c-e46cf783885c

 Exception calling "Invoke" with "0" argument(s): "The running
     | command stopped because the preference variable
     | "ErrorActionPreference" or common parameter is set to Stop:
     | 2:29:10 PM - Error: Code=InvalidTemplateDeployment;
     | Message=The template deployment 'tfaa196a77b774809' is not
     | valid according to the validation procedure. The tracking id
     | is 'f6be98ca-51f9-43c4-9990-c65568deab49'. See inner errors
     | for details. "

**Comment by alzimmermsft** [comment]
Closing as this doesn't appear to be happening anymore
