### ISSUE TITLE
Missing management library for IoTHub and EventHub

### ISSUE THREAD

**Issue by allenhula** [Azure/azure-sdk-for-java#1746]
Didn't find management library for IoTHub and EventHub from anywhere.

**Comment by martinsawicki** [comment]
@RikkiGibson this is part of the stub Manager creation you're doing in https://github.com/Azure/azure-sdk-for-java/pull/1824 and https://github.com/Azure/azure-sdk-for-java/pull/1816, so parking this on your plate.

**Comment by RikkiGibson** [comment]
Hello @allenhula. The PRs mentioned above have been merged and we expect to deliver them in the 1.2 release as beta features. DeviceManager (used for IoTHub) and EventHubManager will have the same authentication methods as seen in other managers in the SDK, and will have the `inner()` property which gives you access to the generated API methods for each service.
