### ISSUE TITLE
[FEATURE REQ][Storage] Implement binary data and base64 encoding in Queues SDK

### ISSUE THREAD

**Issue by kasobol-msft** [Azure/azure-sdk-for-java#17460]
Expose ability to interact with binary payload (aka BinaryData) as well as option to enable base64 encoding in transit.
Corresponding .NET work for reference https://github.com/Azure/azure-sdk-for-net/pull/16689 .

**Comment by kasobol-msft** [comment]
FYI @hemanttanwar @alzimmermsft

**Comment by alzimmermsft** [comment]
+ Azure Core as this functionality will need to be added there first.
