### ISSUE TITLE
Azure Cosmos Java SDK - Sorting by with nested keys and requestContinuation fails

### ISSUE THREAD

**Issue by kushagraThapar** [Azure/azure-sdk-for-java#17482]
Customer is facing issue while Sorting by with nested keys and requestContinuation fails

SQL Query - SELECT * FROM ROOT r  ORDER BY r.calculation.distance ASC

They got a problem when combining requestContinuation and order by nested keys. More specifically they are getting a NullPointerException:

java.lang.NullPointerException: null
at com.azure.data.cosmos.internal.query.OrderByDocumentQueryExecutionContext.GetFormattedFilters(OrderByDocumentQueryExecutionContext.java:319)

They narrowed the problem down to the continuation token being returned:
{'compositeToken':'{\\'token\\':\\'+RID:~CQpLAIqYQw8qCwAAAAAAAA==#RT:2#TRC:40#RTD:aPXEFouCN08ivuLaZXD7BIAA#ISV:2#IEO:65551\\',\\'range\\':\\'{\\\\\\'min\\\\\\':\\\\\\'\\\\\\',\\\\\\'max\\\\\\':\\\\\\'FF\\\\\\',\\\\\\'isMinInclusive\\\\\\':true,\\\\\\'isMaxInclusive\\\\\\':false}\\'}','orderByItems':[{'item':null,'map':{'item':null}}],'rid':'CQpLAIqYQw-bRwAAAAAAAA==','inclusive':true}

If you pay close attention to the orderByItems you see a 'item':null . 

Now they compared query to the results retrieved by the azure portal data explorer. 
It translates the query into the following format : SELECT c._rid, [{'item': c.calculation.distance}] AS orderByItems, c AS payload FROM c WHERE (true) ORDER BY c.calculation.distance ASC
and get the following response: {'_rid':'CQpLAIqYQw8=','Documents':[{'_rid':'CQpLAIqYQw8hSAAAAAAAAA==','orderByItems':[{'item':0}], ...

Here the orderByItems says 'item':0 instead of 'item':null 

After they manually edited the continuationToken and replaced the null with 0 the request was working fine.

They dived deeper into the issue and found the underlying problem.

The orderByItem part contains the value of the orderBy clause (c.calculation.distance) of the first item on the next page.
In their db they had more items with calculation.distance = null than the page size (in their case 10) therefore also the first item on the second page had calculation.distance=null.

**Comment by kushagraThapar** [comment]
@mbhaskar - I recall we fixed this issue, if so, can you please close it ?

**Comment by xinlian12** [comment]
Issue can not be reproed any more.
