### ISSUE TITLE
[Service Bus] Docs review leading up to 7.0.0 release

### ISSUE THREAD

**Issue by ramya-rao-a** [Azure/azure-sdk-for-java#17490]
Now that we are getting closer to the 7.0.0 release for azure-messaging-servicebus, this issue is to track the work to review all the docs around the package and make any fixes or improvements
- readme
- [x] migration guide (#17656)
- [x] java docs
- [x] Adding in sample for how to write a long-running processor (#17633) (approved, and in auto-merge)

**Comment by hemanttanwar** [comment]
@ramya-rao-a   @conniey finished all the java docs before release, so closing this issue. 
@richardpark-msft did samples for us . Thank You.
