### ISSUE TITLE
[BUG] [azure-identity]authenticateWithIntelliJ fails to load credentials

### ISSUE THREAD

**Issue by andxu** [Azure/azure-sdk-for-java#17499]
Issue copied from https://github.com/microsoft/azure-tools-for-java/issues/4740
> #### Setup

> IntelliJ build version: 2020.2.3 IC-202.7660.26
> OS: Linux
> JDK: JetBrains s.r.o. 11.0.8
> Plugin version: 3.45.0-2020.2
> 
> ####  Describe the bug
> 
> Device sign-in via IntelliJ plugin stores auth data into a location where `DefaultAzureCredentialBuilder` cannot find it.
> 
> ####  To Reproduce
> 
> 1. Device sign-in via intelliJ plugin.
> 2. Information will be stored into `~/.AzureToolsForIntelliJ`
> 3. Run the application from IDEA using `DefaultAzureCredentialBuilder`
> 4. IntelliJ authentication not found. 
> 
> After a bit of debugging - IntelliJCacheAccessor seems to use `~/AzureToolsForIntelliJ` instead of dotted path.
> 
> #### Exception or Stack Trace
> 
> ```
> ERROR com.azure.identity.implementation.IntelliJCacheAccessor - IntelliJ Authentication not available. Please log in with Azure Tools for IntelliJ plugin in the IDE.
> com.azure.identity.CredentialUnavailableException: IntelliJ Authentication not available. Please log in with Azure Tools for IntelliJ plugin in the IDE.
> 	at com.azure.identity.implementation.IntelliJCacheAccessor.getAuthDetailsIfAvailable(IntelliJCacheAccessor.java:243)
> 	at com.azure.identity.implementation.IdentityClient.authenticateWithIntelliJ(IdentityClient.java:308)
> 	at com.azure.identity.IntelliJCredential.lambda$getToken$2(IntelliJCredential.java:87)
> 	at reactor.core.publisher.MonoDefer.subscribe(MonoDefer.java:44)
> 	at reactor.core.publisher.Mono.subscribe(Mono.java:4213)
> 	at reactor.core.publisher.FluxSwitchIfEmpty$SwitchIfEmptySubscriber.onComplete(FluxSwitchIfEmpty.java:75)
> 	at reactor.core.publisher.Operators.complete(Operators.java:135)
> 	at reactor.core.publisher.MonoEmpty.subscribe(MonoEmpty.java:45)
> 	at reactor.core.publisher.MonoDefer.subscribe(MonoDefer.java:52)
> 	at reactor.core.publisher.Mono.subscribe(Mono.java:4213)
> 	at reactor.core.publisher.FluxFlatMap$FlatMapMain.onNext(FluxFlatMap.java:418)
> 	at reactor.core.publisher.FluxIterable$IterableSubscription.slowPath(FluxIterable.java:267)
> 	at reactor.core.publisher.FluxIterable$IterableSubscription.request(FluxIterable.java:225)
> 	at reactor.core.publisher.FluxFlatMap$FlatMapMain.drainLoop(FluxFlatMap.java:782)
> 	at reactor.core.publisher.FluxFlatMap$FlatMapMain.innerComplete(FluxFlatMap.java:909)
> 	at reactor.core.publisher.FluxFlatMap$FlatMapInner.onComplete(FluxFlatMap.java:1013)
> ```
> 
> 
> #### Screenshots
> 
> Add screenshots to help explain your problem if available.

**Comment by joshfree** [comment]
Thanks for filing this issue @andxu.  @g2vinay will follow up shortly.  Thanks

**Comment by g2vinay** [comment]
@andxu , thank you for reporting this issue.
It appears, that latest versions of IntelliJ have started using hidden folders to store the plugin metadata.
To unblock yourself, you can copy the content from `~/.AzureToolsForIntelliJ` to `~/AzureToolsForIntelliJ` folder and that should work fine.
While, I will look into adding the support to read from hidden folders in the Identity SDK and release it the next patch release.

**Comment by andxu** [comment]
https://github.com/Azure/azure-sdk-for-java/pull/17943

**Comment by andxu** [comment]
The fix is already checked-in.
