### ISSUE TITLE
Rename azure-mgmt-documentdb folder

### ISSUE THREAD

**Issue by mimig1** [Azure/azure-sdk-for-java#1749]
The azure-mgmt-documentdb folder should be renamed azure-mgmt-cosmosdb. The service name has changed.

**Comment by martinsawicki** [comment]
@alvadb now that the Cosmos DB is official, as discussed, we can do the renaming honors for the next release (v1.2):
- `DocumentDBAccount` becomes `CosmosDBAccount`
- `Azure.documentDBs()` becomes `azure.CosmosDBAccounts()`
- the package needs to be renamed accordingly as well

**Comment by martinsawicki** [comment]
done in v1.2
