### ISSUE TITLE
[Service Bus] Introduce ServiceBusException with limited set of error condition/code/reason 

### ISSUE THREAD

**Issue by ramya-rao-a** [Azure/azure-sdk-for-java#17500]
In the new azure-messaging-servicebus, the exception class we use is the AmqpException. The user is expected to check its `isTransient` and `getErrorCondition()` properties to understand the different error scenarios.

In the older azure-servicebus, there were different exception classes to begin with which mapped to a few of the error condition mentioned above with the rest of the error conditions being classified as a "general error". A similar model is used in .Net library Azure.Messaging.ServiceBus, with the difference being that they use a single ServiceBusException class with different values in the `reason` field denoting the different error scenarios. The JS library `@azure/service-bus` plans to do something similar.

This issue is to request the new azure-messaging-servicebus to follow the same model and have a `ServiceBusException` instead of exposing the `AmqpException`. Historically, the 50 odd error conditions were not required to be exposed to the user. A smaller set with the rest getting swept under "general error" was good enough. Doing this brings all 4 languages to the same page where we use expose the same set of error scenarios with similar details.

Pointers from the .Net implementation:
- [Mapping from error condition to error reason](https://github.com/Azure/azure-sdk-for-net/blob/master/sdk/servicebus/Azure.Messaging.ServiceBus/src/Amqp/AmqpExceptionHelper.cs#L94)
- [TranslateException()](https://github.com/Azure/azure-sdk-for-net/blob/master/sdk/servicebus/Azure.Messaging.ServiceBus/src/Amqp/AmqpExceptionHelper.cs#L185)

@richardpark-msft : after talking with @conniey the implementation of this will be:
* Add ServiceBusException like .NET (basically, rename ServiceBusReceiverException)
* Update `processError` in ServiceBusMessageProcessor to take an ServiceBusReceiverErrorContext rather than just a throwable.		 
   * ServiceBusReceiverErrorContext will contain a 'reason' field with the appropriate code.

**Comment by ramya-rao-a** [comment]
cc @conniey, @YijunXieMS, @hemanttanwar, @srnagar

**Comment by ramya-rao-a** [comment]
For some more information, below are the error "reasons" that was mentioned and the corresponding scenarios:

![image](https://user-images.githubusercontent.com/16890566/98911424-6a6b6d00-2479-11eb-8de0-52e06caa8f3a.png)

**Comment by ramya-rao-a** [comment]
Please note that in .Net, the below 4 error scenarios got to have the built in .Net exceptions:


- amqp:not-implemented  (NotSupportedException)
- amqp:not-allowed (InvalidOperationException)
- argument-error (ArgumentException) 
- argument-out-of-range (ArgumentOutOfRangeException)

Not sure what Java would want to do here.
https://github.com/Azure/azure-sdk-for-js/issues/12559 is tracking this for JS

See https://github.com/Azure/azure-sdk-for-net/blob/master/sdk/servicebus/Azure.Messaging.ServiceBus/src/Amqp/AmqpExceptionHelper.cs#L94

**Comment by hemanttanwar** [comment]
amqp:not-implemented and amqp:not-allowed : This can map to `UnsupportedOperationException` which is java native exception. 
Current Exception already do this mapping  https://github.com/Azure/azure-sdk-for-java/blob/master/sdk/core/azure-core-amqp/src/main/java/com/azure/core/amqp/implementation/ExceptionUtil.java#L77

**Comment by richardpark-msft** [comment]
Ah, that's perfect. I'll test but the current wrapping procedure only does the wrapping when it's an AmqpException. So this might just neatly slide by as you've already designed.

**Comment by hemanttanwar** [comment]
But these two error
`argument-error` and  `argument-out-of-range` :   Java native provides `IllegalArgumentException`  but normally this means we are telling user to change the argument to fix this but can user really fix this by changing args ?  Today when service bus throw this error, because user can not do anything, we actually mark it ` isTransient = false` and create AmqpException();  
https://github.com/Azure/azure-sdk-for-java/blob/master/sdk/core/azure-core-amqp/src/main/java/com/azure/core/amqp/implementation/ExceptionUtil.java#L61

**Comment by ramya-rao-a** [comment]
cc @JoshLove-msft, @chradek,

**Comment by JoshLove-msft** [comment]
> But these two error
argument-error and argument-out-of-range : Java native provides IllegalArgumentException but throwing this means we are telling user to change the argument to fix this error but can user really fix this by changing args ? 

I'm not sure if these errors would actually arise outside of a bug in the SDK itself.

**Comment by ramya-rao-a** [comment]
@JoshLove-msft Those are valid AMQP error conditions that can be sent and they get mapped to the built in .Net exceptions. See https://github.com/Azure/azure-sdk-for-net/blob/master/sdk/servicebus/Azure.Messaging.ServiceBus/src/Amqp/AmqpExceptionHelper.cs#L132-L139

**Comment by JoshLove-msft** [comment]
Yes, but I don't know what would trigger those error conditions other than a bug in the SDK.

**Comment by richardpark-msft** [comment]
Okay, I've created a PR assuming we'll hash out these last few exceptions but the majority map cleanly for now.
