### ISSUE TITLE
When a virtual machine is deleted, an asynchronous method threw an exception, but the virtual machine is deleted

### ISSUE THREAD

**Issue by rogertong** [Azure/azure-sdk-for-java#1753]
When performing asynchronous processing, return a Observable object, and then call the .Last () method to obtain the last emitted element. This method wrote comments: "Returns an Observable that emits the last item emitted by the source Observable or notifies observers of a {@code NoSuchElementException} if the source Observable is empty"

After that, call the subscribe () method to subscribe to the returned value. It always seems to throw an exception.

        String client = "f209a697-1e30-4f31-b158-35db877a501d";
        String tenant = "72f988bf-86f1-41af-91ab-2d7cd011db47";
        String key = "o9I1yhfeni9KlHdm3ESfk2wNKgaGcMGSj4h80ndDIag=";
        ApplicationTokenCredentials token = new ApplicationTokenCredentials(client, tenant, key, AzureEnvironment.AZURE);
        Azure azure = Azure.authenticate(token).withSubscription("3959936e-aa79-461a-becd-2da372325dd2");

        Observable observable =  azure.virtualMachines().deleteByIdAsync("/subscriptions/3959936e-aa79-461a-becd-2da372325dd2/resourceGroups/roger/providers/Microsoft.Compute/virtualMachines/rogerVM")
                .toObservable().last();
        observable.subscribe(
                new Action1<Object>() {
                    @Override
                    public void call(Object o) {
                        System.out.println("delete successfully：" + o.toString());
                    }
                }
                , new Action1<Throwable>() {
                    @Override
                    public void call(Throwable t) {
                        System.out.println("delete failly：" + t.getMessage());
                    }
                }
                , new Action0() {
                    @Override
                    public void call() {
                        System.out.println("execute over");
                    }
                }
        );

After that, I saw that the boolean type value was judged by calling the hasDefaultValue () method in the OperatorSingle<T> class when the onCompleted () method was thrown: the result is false at the time, and an exception is thrown:
@Override
public void onCompleted(){
    if(!hasTooManyElements){
        if(isNonEmpty){
           child.setProducer(new SingleProducer<T>(child,value));
        }else{
           if(hasDefaultValue){
              child.setProducer(new SingleProducer<T>(child,defaultValue);
           } else{
              child.onError(new NoSuchElementException("Sequence contains on elements");
           }
        }
    }//Otherwise we have already sent an onError message
}

**Comment by anuchandy** [comment]
```java
azure.collections().deleteByIdAsync(resourceId)
```
method return [Completable](http://reactivex.io/RxJava/2.x/javadoc/io/reactivex/Completable.html) instead of `Observable<Void>`. Completable represents a deferred computation without any value but only indication for completion or exception, hence Observable produced by converting Completable.toObservable() will not emit a value. Applying `last()` operator on value less stream throws "Sequence contains on elements", which is expected.
 
You can subscribe to completable directly as - 

 ```java
Completable completable =  azure.virtualMachines().deleteByIdAsync("/subscriptions/3959936e-aa79-461a-becd-2da372325dd2/resourceGroups/roger/providers/Microsoft.Compute/virtualMachines/rogerVM");
completable.subscribe(
                    new Action0() {
                          @Override
                          public void call() {
                            // Handles completion here
                          }
                      },
                    new Action1<Throwable>() {
                        @Override
                        public void call(Throwable throwable) {
                            // Handles failure here
                        }
                    });
```

**Comment by anuchandy** [comment]
@rogertong we have addressed your concern, hence closing the issue. Feel free to reopen and comment if you still have question.
