### ISSUE TITLE
[BUG]Cannot resolve com.azure.spring:azure-spring-boot-starter-active-directory:3.0.0-beta.1 on azure-spring-boot-sample-active-directory-stateless project

### ISSUE THREAD

**Issue by liuziyuan** [Azure/azure-sdk-for-java#17531]
**Describe the bug**
Cannot resolve com.azure.spring:azure-spring-boot-starter-active-directory:3.0.0-beta.1
and I can not find this dependency at maven repository

***Code Snippet***
```
<dependency>
      <groupId>com.azure.spring</groupId>
      <artifactId>azure-spring-boot-starter-active-directory</artifactId>
      <version>3.0.0-beta.1</version> <!-- {x-version-update;com.azure.spring:azure-spring-boot-starter-active-directory;current} -->
    </dependency>
```

**Expected behavior**

**Screenshots**

**Setup (please complete the following information):**
 - IDE : IntelliJ Idea

**Comment by cccs-cat001** [comment]
That project isn't in maven central yet, so you have to build from source: https://github.com/Azure/azure-sdk-for-java/blob/master/sdk/spring/CONTRIBUTING.md#building-from-source

**Comment by joshfree** [comment]
Hi @liuziyuan someone from the `azure-spring` team will follow up with you shortly.  Thanks

**Comment by chenrujun** [comment]
@liuziyuan 

Here it is: https://repo.maven.apache.org/maven2/com/azure/spring/azure-spring-boot-starter-keyvault-certificates/


And if you are using latest master branch, please build by the following command:

```bash
cd azure-sdk-for-java
mvn clean install -pl .\sdk\spring\azure-spring-boot-samples\azure-spring-boot-sample-active-directory-stateless -am
```

Refs: https://stackoverflow.com/questions/4588956/what-exactly-happens-during-this-command-mvn-pl-project-list

**Comment by derkoe** [comment]
@chenrujun

> Here it is: https://repo.maven.apache.org/maven2/com/azure/spring/azure-spring-boot-starter-keyvault-certificates/

No - that's keyvault-certificates - `azure-spring-boot-starter-active-directory` is missing.

**Comment by chenrujun** [comment]
@derkoe 

Oh, my mistake. You are right.

We didn't release `azure-spring-boot-starter-active-directory:3.0.0-beta.1`.

Refs: 
https://github.com/Azure/azure-sdk-for-java/blob/master/sdk/spring/azure-spring-boot-starter-active-directory/CHANGELOG.md

Please use `2.3.5` instead. or build `azure-spring-boot-starter-active-directory:3.0.0-beta.2` by yourself.  (check my last comment about how to build by yourself).

**Comment by saragluna** [comment]
Hey guys, `azure-spring-boot-starter-active-directory` **3.0.0** has been released now, here is the maven [link](https://mvnrepository.com/artifact/com.azure.spring/azure-spring-boot-starter-active-directory/3.0.0). Closing this issue now.
