### ISSUE TITLE
[BUG] Cannot resolve reference to bean 'cosmosTemplate' while setting bean property 'cosmosOperations'

### ISSUE THREAD

**Issue by nndo1991** [Azure/azure-sdk-for-java#17538]
**Describe the bug**
We have an app that uses [spring-data-cosmosdb](https://github.com/microsoft/spring-data-cosmosdb) version 2.3.0. Now we are trying to change this dependency to **azure-spring-data-cosmos** 3.1.0 and we are facing an issue when building the project.

It appears to be that the ApplicationContext is unable to find the 'cosmosTemplate' Bean during runtime. Please note that all other Beans used to work fine with **spring-data-cosmosdb** and this application is still running live on our environments.

Important note: We don't have any other packages, all clases are contained within _com.company.plat.apim.environment_

Is there any dependency/configuration/change that we need to consider when migrating to **azure-spring-data-cosmos**?

***Exception or Stack Trace***
`13:22:16.136 [main] WARN  org.springframework.boot.web.servlet.context.AnnotationConfigServletWebServerApplicationContext - Exception encountered during context initialization - cancelling refresh attempt: org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'environmentServiceController': Unsatisfied dependency expressed through field 'backendRegistryService'; nested exception is org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'backendregistry': Unsatisfied dependency expressed through field 'backendinfoStore'; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'backendInfoStore' defined in com.company.plat.apim.environment.dao.BackendInfoStore defined in @EnableCosmosRepositories declared on EnvironmentServiceApplication: Cannot resolve reference to bean 'cosmosTemplate' while setting bean property 'cosmosOperations'; nested exception is org.springframework.beans.factory.NoSuchBeanDefinitionException: No bean named 'cosmosTemplate' available`

**To Reproduce**
`./gradlew bootrun`

***Code Snippet***

EnvironmentServiceApplication.java (main app):
```
@SpringBootApplication
@ComponentScan({"com.company.plat.apim.environment"})
@EnableCosmosRepositories("com.company.plat.apim.environment")
@EntityScan("com.company.plat.apim.environment")
public class EnvironmentServiceApplication {

  public static void main(String[] args) {
    SpringApplication.run(EnvironmentServiceApplication.class, args);
  }
}
```

EnvironmentServiceController.java (controller):
```
@RestController
public class EnvironmentServiceController {

  @Autowired
  @Qualifier("backendregistry")
  BackendRegistry backendRegistryService;

 ...
```

BackendRegistry.java (interface):
```
public interface BackendRegistry {
  public String getBackend(String p1, 
      String p2, String p3) throws ServiceException;
...
```

BackendRegistryImpl.java (implementation):
```
@Service("backendregistry")
public class BackendRegistryImpl implements BackendRegistry {

  @Autowired BackendInfoStore backendinfoStore;
  
  @Override
  public String getBackend(String p1, String p2, String p3) throws ServiceException {
...
```

BackendInfoStore.java (DAO):
```
@Repository
public interface BackendInfoStore extends CosmosRepository<BackendInfo, String> {
  List<BackendInfo> findByParam(String p1);
```

BackendInfo.java (model):
```
@Container(containerName = "backendstore", ru = "400")
public class BackendInfo {

  @Id
  private String id;
  private String v1;
...
```

**Setup (please complete the following information):**
 - OS: Mac OS Catalina 10.15.7
 - IDE : IntelliJ 2020.2.1 Community
 - azure-spring-data-cosmos 3.1.0
 - Java SDK 1.8

Let me know if you need any additional information

**Comment by kushagraThapar** [comment]
@nndo1991 - can you please provide a sample project which can repro the issue ?

**Comment by nndo1991** [comment]
[test_project.zip](https://github.com/Azure/azure-sdk-for-java/files/5563093/test_project.zip)

@kushagraThapar  Sorry about the delay, I just attached a project that reproduces the issue. The problem I get is:

`A component required a bean named 'cosmosTemplate' that could not be found.`

**Comment by kushagraThapar** [comment]
@nndo1991 - can you please help me on how to run the test project ?
What all values do I need to put in the properties file or yml file to be able to run it ?

**Comment by nndo1991** [comment]
Hi @kushagraThapar I'm closing this issue as we found the rootcause. The problem is that we were doing our configuration differently from the approach of creating a class that extends AbstractCosmosConfiguration suggested in [here](https://github.com/Azure/azure-sdk-for-java/tree/master/sdk/cosmos/azure-spring-data-cosmos#setup-configuration-class).

Once we created that class the issue disappeared.

Thanks for your assistance

**Comment by Aastha-dubey** [comment]
Hi @nndo1991 ,I am migrating Spring 2.2.x to 2.5.x version, and I am using **azure-spring-data-cosmos** dependency for cosmos connection. I am facing the below issue while reading the value from yml configuration file.
spring:
  config:
        activate:
            on-profile: local
  application:
    name: demo-profile
azure:
 cosmos:
   uri: ###
   key: ###
   secondaryKey: ####
   database: ####
   populateQueryMetrics: true
   basepackage:
      name:  com.example.config.UserRepository

********************************************************

package com.example.config;

import org.apache.logging.log4j.LogManager;
import org.apache.logging.log4j.Logger;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.beans.factory.annotation.Value;
import org.springframework.boot.context.properties.EnableConfigurationProperties;
import org.springframework.context.annotation.Bean;
import org.springframework.context.annotation.Configuration;
import org.springframework.context.annotation.PropertySource;
import org.springframework.lang.Nullable;

import com.azure.core.credential.AzureKeyCredential;
import com.azure.cosmos.CosmosClientBuilder;
import com.azure.cosmos.DirectConnectionConfig;
import com.azure.cosmos.GatewayConnectionConfig;
import com.azure.spring.data.cosmos.config.AbstractCosmosConfiguration;
import com.azure.spring.data.cosmos.config.CosmosConfig;
import com.azure.spring.data.cosmos.core.ResponseDiagnostics;
import com.azure.spring.data.cosmos.core.ResponseDiagnosticsProcessor;
import com.azure.spring.data.cosmos.repository.config.EnableCosmosRepositories;

@Configuration
@EnableCosmosRepositories
@EnableConfigurationProperties(CosmosProperties.class)
public class AppConfiguration extends AbstractCosmosConfiguration {

    private static final Logger LOGGER = LogManager.getLogger(AppConfiguration.class);

    @Value("${azure.cosmos.uri}")
    private String uri;

    @Value("${azure.cosmos.key}")
    private String key;

    @Value("${azure.cosmos.secondaryKey}")
    private String secondaryKey;

    @Value("${azure.cosmos.database}")
    private String dbName;

    @Value("${azure.cosmos.queryMetricsEnabled}")
    private boolean queryMetricsEnabled;

    private AzureKeyCredential azureKeyCredential;
    
	/*
	 * @Autowired private UserRepository repository;
	 */

    @Bean
    public CosmosClientBuilder getCosmosClientBuilder() {
        this.azureKeyCredential = new AzureKeyCredential(key);
        DirectConnectionConfig directConnectionConfig = new DirectConnectionConfig();
        GatewayConnectionConfig gatewayConnectionConfig = new GatewayConnectionConfig();
        return new CosmosClientBuilder()
            .endpoint(uri)
            .credential(azureKeyCredential)
            .directMode(directConnectionConfig, gatewayConnectionConfig);
    }

    @Override
    public CosmosConfig cosmosConfig() {
        return CosmosConfig.builder()
                           .enableQueryMetrics(queryMetricsEnabled)
                           .responseDiagnosticsProcessor(new ResponseDiagnosticsProcessorImplementation())
                           .build();
    }

    public void switchToSecondaryKey() {
        this.azureKeyCredential.update(secondaryKey);
    }

    @Override
    protected String getDatabaseName() {
        return "###";
    }

    private static class ResponseDiagnosticsProcessorImplementation implements ResponseDiagnosticsProcessor {

        @Override
        public void processResponseDiagnostics(@Nullable ResponseDiagnostics responseDiagnostics) {
            LOGGER.info("Response Diagnostics {}", responseDiagnostics);
        }
    }

}
*************************************************************
package com.example.config;

import org.springframework.boot.context.properties.ConfigurationProperties;

@ConfigurationProperties(prefix = "azure.cosmos")
public class CosmosProperties {

    private String uri;

    private String key;

    private String secondaryKey;

    private String database;

    private boolean queryMetricsEnabled;

    public String getUri() {
        return uri;
    }

    public void setUri(String uri) {
        this.uri = uri;
    }

    public String getKey() {
        return key;
    }

    public void setKey(String key) {
        this.key = key;
    }

    public String getSecondaryKey() {
        return secondaryKey;
    }

    public void setSecondaryKey(String secondaryKey) {
        this.secondaryKey = secondaryKey;
    }

    public String getDatabase() {
        return database;
    }

    public void setDatabase(String database) {
        this.database = database;
    }

    public boolean isQueryMetricsEnabled() {
        return queryMetricsEnabled;
    }

    public void setQueryMetricsEnabled(boolean enableQueryMetrics) {
        this.queryMetricsEnabled = enableQueryMetrics;
    }
}
************************************************

ConfigServletWebServerApplicationContext : Exception encountered during context initialization - cancelling refresh attempt: org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'sampleApplication': Unsatisfied dependency expressed through field 'repository'; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'userRepository' defined in com.example.config.UserRepository defined in @EnableCosmosRepositories declared on AppConfiguration: Cannot resolve reference to bean 'cosmosTemplate' while setting bean property 'cosmosOperations'; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'appConfiguration': Injection of autowired dependencies failed; nested exception is java.lang.IllegalArgumentException: Could not resolve placeholder 'azure.cosmos.uri' in value "${azure.cosmos.uri}"
