### ISSUE TITLE
[QUERY] EnabledProtocols (SMB/NFS) isn't available in the properties

### ISSUE THREAD

**Issue by abhilash-komprise** [Azure/azure-sdk-for-java#17594]
**Query/Question**
Even though the rest api docs (https://docs.microsoft.com/en-us/rest/api/storageservices/list-shares) mentions that the EnabledProtocols is available in the properties of share, `com.azure.storage.file.share.models.ShareProperties` does not have this field.
Is there any plan to expose this information?  Or is there any any other way to get this protocol information for file shares?

***Why is this not a Bug or a feature Request?***
Need information regarding way to fetch the protocol for a file share.

**Setup (please complete the following information if applicable):**
 - OS: Ubuntu 18.04.4 LTS
 - IDE : IntelliJ
 - Version of the Library used : azure-storage-file-share - 12.6.0 / 12.7.0-beta.1
 
 **Information Checklist**
 Kindly make sure that you have added all the following information above and checkoff the required fields otherwise we will treat the issuer as an incomplete report
- [x] Query Added
- [x] Setup information Added

**Comment by gapra-msft** [comment]
Hi @abhilash-komprise

Thank you for your question. I believe this is a recent feature added to the service. 

We have already put out a [PR](https://github.com/Azure/azure-sdk-for-java/pull/17239) to add support for it. We will likely release support for this feature in the SDK in our next release.

**Comment by abhilash-komprise** [comment]
Hi @gapra-msft 

Thanks for the information
Just wanted to know, is there any timeline when will this release be available?


A follow up question: (not sure if it's the right forum to ask)
On the portal also, the protocol info in only available for NFS shares (not for SMB shares). Can it be assumed that if protocol is not available, it's an SMB enabled share?

**Comment by gapra-msft** [comment]
@abhilash-komprise 

The SDK will likely be released next month. 

As for your other question, I unfortunately don't have a good answer for you. I don't think the enabled protocols feature is fully released.

**Comment by abhilash-komprise** [comment]
Regarding the assumption mentioned above, got the confirmation from REST team.
> If we are not able to see the Protocol information through REST API also then we can assume it is an SMB share

@gapra-msft By any chance do we have date now, when this will be available through the java SDK?

**Comment by gapra-msft** [comment]
@abhilash-komprise Sorry I must have missed this comment before. A beta of the SDK should be released. It should be azure-storage-file-share 12.8.0-beta.1

**Comment by rickle-msft** [comment]
I am going to close this issue because it looks like all the questions have been addressed. Please feel free to reach out if you have further questions/issues
