### ISSUE TITLE
[FEATURE REQ] Storage RequestRetryPolicy timeout time unit should be configurable

### ISSUE THREAD

**Issue by fcofdez** [Azure/azure-sdk-for-java#17590]
**Is your feature request related to a problem? Please describe.**
Currently, the timeout configured on `RequestRetryOptions` is just an integer, and since the unit is not
specified in the parameter name, it can lead to confusion. It seems like the current time unit used to configure the
request timeout is seconds (https://github.com/Azure/azure-sdk-for-java/blob/3bce40473c81d044b468baedb0011fd83512ec1f/sdk/storage/azure-storage-common/src/main/java/com/azure/storage/common/policy/RequestRetryPolicy.java#L114)
But you should dig into the codebase a little in order to understand which time unit is used.

**Describe the solution you'd like**
I would like to configure the time unit used to configure the request timeout.

**Describe alternatives you've considered**

**Additional context**

**Information Checklist**
Kindly make sure that you have added all the following information above and checkoff the required fields otherwise we will treat the issuer as an incomplete report
- [x] Description Added
- [x] Expected solution specified

**Comment by rickle-msft** [comment]
Thank you, @fcofdez, for this feature request. It seems reasonable to me. Let me confer with my team and follow up with you.
