### ISSUE TITLE
[ServiceBus Track 2] - Support SEQUENCE and VALUE AMQP types 

### ISSUE THREAD

**Issue by hemanttanwar** [Azure/azure-sdk-for-java#17614]
**Support following Amqp Types**

Amqp supports following types and track 2 SDK also need to provide support for these types.

  -  SEQUENCE http://docs.oasis-open.org/amqp/core/v1.0/amqp-core-messaging-v1.0.html#type-amqp-sequence
  -  VALUE http://docs.oasis-open.org/amqp/core/v1.0/os/amqp-core-messaging-v1.0-os.html#type-amqp-value

Note: This issue is linked in source code so that customers can track this.

**Comment by anuchandy** [comment]
Both types are exposed as part of version 7.3.0 [changelog](https://github.com/Azure/azure-sdk-for-java/blob/main/sdk/servicebus/azure-messaging-servicebus/CHANGELOG.md#features-added-6)
