### ISSUE TITLE
[TA] [Service-Bug] AnalyzeTasks endpoint doesn't support UUID for the task ID.

### ISSUE THREAD

**Issue by mssfang** [Azure/azure-sdk-for-java#17629]
Temporally change autogenerated code to use String instead of UUID. since service doesn't support UUID task ID yet. The service will fix it before next release.

**Comment by samvaity** [comment]
Do we have an ETA on this?

**Comment by mssfang** [comment]
with new v3.1-preview.4 it is resolved.
