### ISSUE TITLE
[FEATURE REQ] Add an option to SQL API @Container to set auto scaling = true

### ISSUE THREAD

**Issue by robertsearle** [Azure/azure-sdk-for-java#17626]
Add an option to SQL API `@com.azure.spring.data.cosmos.core.mapping.Container` to set `autoScaling = true` .   I would also like an option to set the `maxRUs=4_000`. Maybe just setting the `maxRUs` is enough...

**Comment by kushagraThapar** [comment]
@robertsearle - we are already tracking this issue here : https://github.com/Azure/azure-sdk-for-java/issues/12711

**Comment by kushagraThapar** [comment]
@robertsearle - I am closing this issue. Please track it here - https://github.com/Azure/azure-sdk-for-java/issues/12711
