### ISSUE TITLE
[FEATURE REQ] Add CosmosDiagnostic support for bulk

### ISSUE THREAD

**Issue by rakkuma** [Azure/azure-sdk-for-java#17647]
We need to add diagnostic for each operation in a bulk.

The way would be init a diagnostic for each operation and have some kind of merge logic such that execution diagnostic is added to individual operation diag. Other info like partition key range id fetch will also be added individually. 

Any retry which is done at bulk level will also get handled and at the end we will have a merged diagnostic.

**Comment by kushagraThapar** [comment]
@xinlian12 - let's prioritize it for Zinc.

**Comment by xinlian12** [comment]
There is already diagnostics for each operation. If there is any information missing, please create a new one.
