### ISSUE TITLE
virtualMachineImages().publishers().listByRegion() returns forbidden for us gov virginia region

### ISSUE THREAD

**Issue by paulojohnj** [Azure/azure-sdk-for-java#1766]
The above call to list publisher by region returns forbidden when a region of us gov Virginia is used. This call worked previously and seems to have just recently changed in behavior. However, if a region of us gov iowa is used or a commercial environment and region are used the call behaves as expected.

**Comment by hovsepm** [comment]
This sounds like a subscription issue. We do not alter URL or message body depending on the region.
Are you able to list publishers in azure CLI or Azure PS?

**Comment by paulojohnj** [comment]
yes, I am able to list publishers in azure cli for the same account in the us gov virginia region

**Comment by paulojohnj** [comment]
In addition, I have noticed a dramatic change in the time it takes to copy an image between storage accounts (also within the gov v region). Going from previous times of less than 5-6 min, to now around 18 minutes, with no changes to the file sizes or transfer methods. Not sure if this is related at all based on region, but was trying not to submit another ticker.

**Comment by anuchandy** [comment]
@paulojohnj 

**listByRegion**

The `virtualMachineImages().publishers().listByRegion()` behaviour in "gov Virginia" region looks strange?  To debug further, could you share following log with us?

1. Log for virtualMachineImages().publishers().listByRegion(Region.GOV_US_VIRGINIA)

and

2. Log for virtualMachineImages().publishers().listByRegion(Region.GOV_US_IOWA)

**Cross account blob copying**

please open a ticket with azure storage team regarding the delay in cross storage account copying. Refer https://docs.microsoft.com/en-us/azure/azure-supportability/how-to-create-azure-support-request.

**Comment by anuchandy** [comment]
Sorry one more ask, I don't have a subscription enabled for "Azure Government". If you don't mind, could you share the log of CLI for gov Virginia as well?

**Comment by paulojohnj** [comment]
@anuchandy this issue appears to have resolved itself, as the gov virginia region is now once again returning results for the above call. Therefore I doubt the asked for logs would be of use. Sorry for the delay in reply. I will move the copy portion of my question over to azure storage. Thank you.

**Comment by anuchandy** [comment]
@paulojohnj thanks for the update!
