### ISSUE TITLE
[QUERY] Azure key vault with manged identities error in console

### ISSUE THREAD

**Issue by Liave** [Azure/azure-sdk-for-java#17683]
Hi,

I am using azure key vault with managed identities meaning that my app service is recognized by my azure key vault (access polices in the key vault).
we are using azure-security-keyvault-secrets, azure-identity and it works.
the only thing is we get an error in the console on start when running in eclipse (identify via azure tools) and in Azure:

 ERROR com.azure.core.util.logging.ClientLogger [main] Azure Identity => ERROR in EnvironmentCredential: Missing required environment variable AZURE_CLIENT_ID
 ERROR com.azure.core.util.logging.ClientLogger [main] IntelliJ Authentication not available. Please log in with Azure Tools for IntelliJ plugin in the IDE.

we use DefaultAzureCredentialBuilder()  to create SecretClient

***Why is this not a Bug or a feature Request?***
maybe a bug ...

**Setup (please complete the following information if applicable):**
 - OS: windows / linux on Azure
 - IDE :eclipse
 - Version of the Library used: azure-security-keyvault-secrets: 4.2.2 , azure-identity: 1.2.0

**Comment by aerisnju** [comment]
That's possibly expected behavior of `DefaultAzureCredential` because it tries to find a valid credential from a list of providers, which is a try-and-error process. Since you are using managed identities only, you can just use `ManagedIdentityCredential` instead:

```java
var secretClient = new SecretClientBuilder()
        .vaultUrl("https://SCTestingVault.vault.azure.net")
        .credential(new ManagedIdentityCredentialBuilder().build())  // Instead of DefaultAzureCredentialBuilder
        .buildClient();
```

**Comment by aerisnju** [comment]
That's possibly expected behavior of `DefaultAzureCredential` because it tries to find a valid credential from a list of providers, which is a try-and-error process. Since you are using managed identities only, you can just use `ManagedIdentityCredential` instead:

```java
var secretClient = new SecretClientBuilder()
        .vaultUrl("https://<vault_name>.vault.azure.net")
        .credential(new ManagedIdentityCredentialBuilder().build())  // Instead of DefaultAzureCredentialBuilder
        .buildClient();
```

**Comment by joshfree** [comment]
@g2vinay could you please follow up?

**Comment by Liave** [comment]
Hi,
Thanks for the answer, probably  ManagedIdentityCredential  will work in Azure deployment but it does not work locally when I use it inside eclipse so for now I will stay with DefaultAzureCredentialBuilder

**Comment by g2vinay** [comment]
@Liave 
Yes, this behavior is expected if you've logging enabled and you are using DefaultAzureCredential.
The credential tries a list of credentials underneath, these logging messages just let you know which credential failed and which one worked.
If your app is working fine, there is no need to be concerned with these log messages.

**Comment by tlasica** [comment]
I understand the issue is closed, but I am curious what is the rationale for logging those information as ERRORs and not e.g. INFO or even DEBUG?
