### ISSUE TITLE
SSLVerifyMode EventHubClientBuilder package-private

### ISSUE THREAD

**Issue by pedro-correia-tech** [Azure/azure-sdk-for-java#17689]
EventHubClientBuilder has verifyMode package protected.

It's impossible to switch the SSL verification mode from the EventHubClientBuilder instantiation and that was changed in the latest version.

Could we have at least the method public available on the builder?

**Comment by joshfree** [comment]
Thanks for filing this issue @pedro-correia-tech -- @conniey could you please follow up?

**Comment by conniey** [comment]
Yeah, this is a good feature we could add.
