### ISSUE TITLE
Storage Live Tests failed due to An error occurred while provisioning resources (Error Type: Disconnect).

### ISSUE THREAD

**Issue by gapra-msft** [Azure/azure-sdk-for-java#17688]
https://dev.azure.com/azure-sdk/internal/_build/results?buildId=626143&view=logs&j=d4b67cd2-6572-561e-035e-54acb01c3f6e

**Comment by kurtzeborn** [comment]
This is a very old issue at this point.  If this is still happening, please provide a link to a newer pipeline run.
