### ISSUE TITLE
[FEATURE REQ] Update NetworkInterface does not allow enabling accelerated networking

### ISSUE THREAD

**Issue by stefankaticec** [Azure/azure-sdk-for-java#17723]
**Is your feature request related to a problem? Please describe.**
Our platform supports a couple of VM types. One of those VMs requires accelerated networking to be disabled, and that's ok. On Update NetworkInterface we have the withoutAcceleratedNetworking() method. But then when I have to scale this machine, I can't enable the accelerated networking again.

**Describe the solution you'd like**
Add/implement withAcceleratedNetworking method in NetworkInterface.UpdateStages.WithAcceleratedNetworking.

**Describe alternatives you've considered**
Dropping the NI and creating a new one. This will break the entire infrastructure, because the IP will change. 

**Additional context**

**Information Checklist**
Kindly make sure that you have added all the following information above and checkoff the required fields otherwise we will treat the issuer as an incomplete report
- [X] Description Added
- [X] Expected solution specified

**Comment by yungezz** [comment]
hi @xccc-msft could you pls help to have a look? thanks

**Comment by xccc-msft** [comment]
@stefankaticec Please try with the workaround below:
```java
NetworkInterface nic = ....create();
nic.inner().withEnableAcceleratedNetworking(true);
nic.update().apply();
```

**Comment by weidongxu-microsoft** [comment]
Already fixed by https://github.com/Azure/azure-sdk-for-java/pull/17805
https://github.com/Azure/azure-sdk-for-java/blob/master/sdk/resourcemanager/azure-resourcemanager-network/src/main/java/com/azure/resourcemanager/network/models/NetworkInterface.java#L493-L511

2.3.0 should have them.
