### ISSUE TITLE
java.lang.IllegalArgumentException: 'channelPool.1366101114' is already in use

### ISSUE THREAD

**Issue by skythegowda** [Azure/azure-sdk-for-java#17749]
We are noticing following error while updating document, please help.

**Failed to upsert item; nested exception is java.lang.IllegalArgumentException: 'channelPool.1366101114' is already in use**

netty version used: 4.1.42

**Comment by alzimmermsft** [comment]
Hi @skythegowda could you provide more information on which Azure SDKs you are using, such as `azure-data-appconfiguration` or `azure-storage-blob`, and the versions being used.

**Comment by skythegowda** [comment]
Hi,

The SDK version being used is 3.7.1.

Thanks & Regards

**Comment by joshfree** [comment]
Hi @skythegowda could you please share the full exception message including the callstack and any additional information relevant to investigate the issue - such as the SDK name(s) (such as `azure-storage-blob`) so that we can help route your issue to the right area expert?

Thank you,
Josh

**Comment by skythegowda** [comment]
Hi,

Here is the full callstack. Hope this helps.

Unexpected exception 'channelPool.629464804' is already in use received
while reading from store.,exc.stack=java.lang.IllegalArgumentException:
'channelPool.629464804' is already in use\n\tat
io.netty.util.ConstantPool.createOrThrow(ConstantPool.java:113)\n\tat
io.netty.util.ConstantPool.newInstance(ConstantPool.java:95)\n\tat
io.netty.util.AttributeKey.newInstance(AttributeKey.java:55)\n\tat
io.netty.channel.pool.SimpleChannelPool.<init>(SimpleChannelPool.java:42)\n\tat
com.azure.data.cosmos.internal.directconnectivity.rntbd.RntbdClientChannelPool.<init>(RntbdClientChannelPool.java:101)\n\tat
com.azure.data.cosmos.internal.directconnectivity.rntbd.RntbdClientChannelPool.<init>(RntbdClientChannelPool.java:93)\n\tat
com.azure.data.cosmos.internal.directconnectivity.rntbd.RntbdServiceEndpoint.<init>(RntbdServiceEndpoint.java:86)\n\tat
com.azure.data.cosmos.internal.directconnectivity.rntbd.RntbdServiceEndpoint.<init>(RntbdServiceEndpoint.java:45)\n\tat
com.azure.data.cosmos.internal.directconnectivity.rntbd.RntbdServiceEndpoint$Provider.lambda$get$1(RntbdServiceEndpoint.java:380)\n\tat
java.util.concurrent.ConcurrentHashMap.computeIfAbsent(ConcurrentHashMap.java:1660)\n\tat
com.azure.data.cosmos.internal.directconnectivity.rntbd.RntbdServiceEndpoint$Provider.get(RntbdServiceEndpoint.java:379)\n\tat
com.azure.data.cosmos.internal.directconnectivity.RntbdTransportClient.invokeStoreAsync(RntbdTransportClient.java:120)\n\tat
com.azure.data.cosmos.internal.directconnectivity.TransportClient.invokeResourceOperationAsync(TransportClient.java:15)\n\tat
com.azure.data.cosmos.internal.directconnectivity.StoreReader.readFromStoreAsync(StoreReader.java:636)\n\tat
com.azure.data.cosmos.internal.directconnectivity.StoreReader.readFromReplicas(StoreReader.java:213)\n\tat
com.azure.data.cosmos.internal.directconnectivity.StoreReader.lambda$readMultipleReplicasInternalAsync$10(StoreReader.java:391)\n\tat
reactor.core.publisher.FluxDefer.subscribe(FluxDefer.java:46)\n\tat
reactor.core.publisher.FluxRepeatPredicate$RepeatPredicateSubscriber.resubscribe(FluxRepeatPredicate.java:113)\n\tat
reactor.core.publisher.FluxRepeatPredicate.subscribeOrReturn(FluxRepeatPredicate.java:49)\n\tat
reactor.core.publisher.Mono.subscribe(Mono.java:4072)\n\tat
reactor.core.publisher.FluxConcatArray$ConcatArraySubscriber.onComplete(FluxConcatArray.java:207)\n\tat
reactor.core.publisher.FluxConcatArray.subscribe(FluxConcatArray.java:80)\n\tat
reactor.core.publisher.FluxDefer.subscribe(FluxDefer.java:54)\n\tat
reactor.core.publisher.Flux.subscribe(Flux.java:8134)\n\tat
reactor.core.publisher.FluxSwitchIfEmpty$SwitchIfEmptySubscriber.onComplete(FluxSwitchIfEmpty.java:75)\n\tat
reactor.core.publisher.Operators.complete(Operators.java:132)\n\tat
reactor.core.publisher.FluxEmpty.subscribe(FluxEmpty.java:41)\n\tat
reactor.core.publisher.Flux.subscribe(Flux.java:8134)\n\tat
reactor.core.publisher.FluxFlatMap$FlatMapMain.onNext(FluxFlatMap.java:418)\n\tat
reactor.core.publisher.FluxMapFuseable$MapFuseableSubscriber.onNext(FluxMapFuseable.java:121)\n\tat
reactor.core.publisher.FluxMapFuseable$MapFuseableSubscriber.onNext(FluxMapFuseable.java:121)\n\tat
reactor.core.publisher.FluxMapFuseable$MapFuseableSubscriber.onNext(FluxMapFuseable.java:121)\n\tat
reactor.core.publisher.FluxMapFuseable$MapFuseableSubscriber.onNext(FluxMapFuseable.java:121)\n\tat
reactor.core.publisher.Operators$MonoSubscriber.complete(Operators.java:1592)\n\tat
reactor.core.publisher.MonoFlatMap$FlatMapMain.onNext(MonoFlatMap.java:144)\n\tat
reactor.core.publisher.Operators$MonoSubscriber.complete(Operators.java:1592)\n\tat
reactor.core.publisher.MonoFlatMap$FlatMapInner.onNext(MonoFlatMap.java:241)\n\tat
reactor.core.publisher.Operators$MonoSubscriber.complete(Operators.java:1592)\n\tat
reactor.core.publisher.MonoFlatMap$FlatMapMain.onNext(MonoFlatMap.java:144)\n\tat
reactor.core.publisher.Operators$MonoSubscriber.complete(Operators.java:1592)\n\tat
reactor.core.publisher.MonoFlatMap$FlatMapMain.onNext(MonoFlatMap.java:144)\n\tat
reactor.core.publisher.FluxOnErrorResume$ResumeSubscriber.onNext(FluxOnErrorResume.java:73)\n\tat
reactor.core.publisher.FluxMapFuseable$MapFuseableSubscriber.onNext(FluxMapFuseable.java:121)\n\tat
reactor.core.publisher.FluxMapFuseable$MapFuseableSubscriber.onNext(FluxMapFuseable.java:121)\n\tat
reactor.core.publisher.Operators$MonoSubscriber.complete(Operators.java:1592)\n\tat
reactor.core.publisher.MonoSingle$SingleSubscriber.onComplete(MonoSingle.java:171)\n\tat
reactor.core.publisher.FluxFlatMap$FlatMapMain.checkTerminated(FluxFlatMap.java:823)\n\tat
reactor.core.publisher.FluxFlatMap$FlatMapMain.drainLoop(FluxFlatMap.java:589)\n\tat
reactor.core.publisher.FluxFlatMap$FlatMapMain.drain(FluxFlatMap.java:569)\n\tat
reactor.core.publisher.FluxFlatMap$FlatMapMain.onComplete(FluxFlatMap.java:455)\n\tat
reactor.core.publisher.DrainUtils.postCompleteDrain(DrainUtils.java:131)\n\tat
reactor.core.publisher.DrainUtils.postComplete(DrainUtils.java:186)\n\tat
reactor.core.publisher.FluxMapSignal$FluxMapSignalSubscriber.onComplete(FluxMapSignal.java:213)\n\tat
reactor.core.publisher.Operators$MonoSubscriber.complete(Operators.java:1593)\n\tat
reactor.core.publisher.MonoProcessor.subscribe(MonoProcessor.java:383)\n\tat
reactor.core.publisher.InternalMonoOperator.subscribe(InternalMonoOperator.java:55)\n\tat
reactor.core.publisher.MonoFlatMap$FlatMapMain.onNext(MonoFlatMap.java:150)\n\tat
reactor.core.publisher.Operators$MonoSubscriber.complete(Operators.java:1592)\n\tat
reactor.core.publisher.MonoFlatMap$FlatMapMain.onNext(MonoFlatMap.java:144)\n\tat
reactor.core.publisher.Operators$MonoSubscriber.complete(Operators.java:1592)\n\tat
reactor.core.publisher.MonoFlatMap$FlatMapInner.onNext(MonoFlatMap.java:241)\n\tat
reactor.core.publisher.Operators$MonoSubscriber.complete(Operators.java:1592)\n\tat
reactor.core.publisher.MonoFlatMap$FlatMapMain.onNext(MonoFlatMap.java:144)\n\tat
reactor.core.publisher.FluxOnErrorResume$ResumeSubscriber.onNext(FluxOnErrorResume.java:73)\n\tat
reactor.core.publisher.FluxMapFuseable$MapFuseableSubscriber.onNext(FluxMapFuseable.java:121)\n\tat
reactor.core.publisher.Operators$MonoSubscriber.complete(Operators.java:1592)\n\tat
reactor.core.publisher.MonoSingle$SingleSubscriber.onComplete(MonoSingle.java:171)\n\tat
reactor.core.publisher.FluxFlatMap$FlatMapMain.checkTerminated(FluxFlatMap.java:823)\n\tat
reactor.core.publisher.FluxFlatMap$FlatMapMain.drainLoop(FluxFlatMap.java:589)\n\tat
reactor.core.publisher.FluxFlatMap$FlatMapMain.drain(FluxFlatMap.java:569)\n\tat
reactor.core.publisher.FluxFlatMap$FlatMapMain.onComplete(FluxFlatMap.java:455)\n\tat
reactor.core.publisher.DrainUtils.postCompleteDrain(DrainUtils.java:131)\n\tat
reactor.core.publisher.DrainUtils.postComplete(DrainUtils.java:186)\n\tat
reactor.core.publisher.FluxMapSignal$FluxMapSignalSubscriber.onComplete(FluxMapSignal.java:213)\n\tat
reactor.core.publisher.Operators$MonoSubscriber.complete(Operators.java:1593)\n\tat
reactor.core.publisher.MonoProcessor.subscribe(MonoProcessor.java:383)\n\tat
reactor.core.publisher.InternalMonoOperator.subscribe(InternalMonoOperator.java:55)\n\tat
reactor.core.publisher.MonoFlatMap$FlatMapMain.onNext(MonoFlatMap.java:150)\n\tat
reactor.core.publisher.Operators$MonoSubscriber.complete(Operators.java:1592)\n\tat
reactor.core.publisher.MonoFlatMap$FlatMapMain.onNext(MonoFlatMap.java:144)\n\tat
reactor.core.publisher.FluxOnErrorResume$ResumeSubscriber.onNext(FluxOnErrorResume.java:73)\n\tat
reactor.core.publisher.FluxMapFuseable$MapFuseableSubscriber.onNext(FluxMapFuseable.java:121)\n\tat
reactor.core.publisher.Operators$MonoSubscriber.complete(Operators.java:1592)\n\tat
reactor.core.publisher.MonoSingle$SingleSubscriber.onComplete(MonoSingle.java:171)\n\tat
reactor.core.publisher.FluxFlatMap$FlatMapMain.checkTerminated(FluxFlatMap.java:823)\n\tat
reactor.core.publisher.FluxFlatMap$FlatMapMain.drainLoop(FluxFlatMap.java:589)\n\tat
reactor.core.publisher.FluxFlatMap$FlatMapMain.drain(FluxFlatMap.java:569)\n\tat
reactor.core.publisher.FluxFlatMap$FlatMapMain.onComplete(FluxFlatMap.java:455)\n\tat
reactor.core.publisher.DrainUtils.postCompleteDrain(DrainUtils.java:131)\n\tat
reactor.core.publisher.DrainUtils.postComplete(DrainUtils.java:186)\n\tat
reactor.core.publisher.FluxMapSignal$FluxMapSignalSubscriber.onComplete(FluxMapSignal.java:213)\n\tat
reactor.core.publisher.FluxJust$WeakScalarSubscription.request(FluxJust.java:101)\n\tat
reactor.core.publisher.FluxMapSignal$FluxMapSignalSubscriber.request(FluxMapSignal.java:225)\n\tat
reactor.core.publisher.FluxFlatMap$FlatMapMain.onSubscribe(FluxFlatMap.java:363)\n\tat
reactor.core.publisher.FluxMapSignal$FluxMapSignalSubscriber.onSubscribe(FluxMapSignal.java:115)\n\tat
reactor.core.publisher.FluxJust.subscribe(FluxJust.java:70)\n\tat
reactor.core.publisher.InternalMonoOperator.subscribe(InternalMonoOperator.java:55)\n\tat
reactor.core.publisher.MonoDefer.subscribe(MonoDefer.java:52)\n\tat
reactor.core.publisher.MonoFromFluxOperator.subscribe(MonoFromFluxOperator.java:72)\n\tat
reactor.core.publisher.MonoDefer.subscribe(MonoDefer.java:52)\n\tat
reactor.core.publisher.FluxRetryWhen.subscribe(FluxRetryWhen.java:87)\n\tat
reactor.core.publisher.MonoRetryWhen.subscribeOrReturn(MonoRetryWhen.java:50)\n\tat
reactor.core.publisher.Flux.subscribe(Flux.java:8120)\n\tat
reactor.core.publisher.FluxMergeSequential$MergeSequentialMain.onNext(FluxMergeSequential.java:230)\n\tat
reactor.core.publisher.FluxGenerate$GenerateSubscription.next(FluxGenerate.java:169)\n\tat
com.azure.data.cosmos.internal.query.Paginator.lambda$getPaginatedQueryResultAsObservable$1(Paginator.java:63)\n\tat
reactor.core.publisher.FluxGenerate$GenerateSubscription.slowPath(FluxGenerate.java:262)\n\tat
reactor.core.publisher.FluxGenerate$GenerateSubscription.request(FluxGenerate.java:204)\n\tat
reactor.core.publisher.FluxMergeSequential$MergeSequentialMain.onSubscribe(FluxMergeSequential.java:191)\n\tat
reactor.core.publisher.FluxGenerate.subscribe(FluxGenerate.java:83)\n\tat
reactor.core.publisher.InternalFluxOperator.subscribe(InternalFluxOperator.java:53)\n\tat
reactor.core.publisher.FluxDefer.subscribe(FluxDefer.java:54)\n\tat
reactor.core.publisher.Flux.subscribe(Flux.java:8134)\n\tat
reactor.core.publisher.FluxMergeSequential$MergeSequentialMain.onNext(FluxMergeSequential.java:230)\n\tat
reactor.core.publisher.FluxIterable$IterableSubscription.slowPath(FluxIterable.java:243)\n\tat
reactor.core.publisher.FluxIterable$IterableSubscription.request(FluxIterable.java:201)\n\tat
reactor.core.publisher.FluxMergeSequential$MergeSequentialMain.onSubscribe(FluxMergeSequential.java:191)\n\tat
reactor.core.publisher.FluxIterable.subscribe(FluxIterable.java:139)\n\tat
reactor.core.publisher.FluxIterable.subscribe(FluxIterable.java:63)\n\tat
reactor.core.publisher.Flux.subscribe(Flux.java:8134)\n\tat
reactor.core.publisher.FluxConcatArray$ConcatArraySubscriber.onComplete(FluxConcatArray.java:207)\n\tat
reactor.core.publisher.FluxConcatArray.subscribe(FluxConcatArray.java:80)\n\tat
reactor.core.publisher.InternalFluxOperator.subscribe(InternalFluxOperator.java:53)\n\tat
reactor.core.publisher.FluxDefer.subscribe(FluxDefer.java:54)\n\tat
reactor.core.publisher.Flux.subscribe(Flux.java:8134)\n\tat
reactor.core.publisher.FluxFlatMap$FlatMapMain.onNext(FluxFlatMap.java:418)\n\tat
reactor.core.publisher.Operators$MonoSubscriber.complete(Operators.java:1592)\n\tat
reactor.core.publisher.MonoFlatMap$FlatMapInner.onNext(MonoFlatMap.java:241)\n\tat
reactor.core.publisher.Operators$MonoSubscriber.complete(Operators.java:1592)\n\tat
reactor.core.publisher.MonoFlatMap$FlatMapInner.onNext(MonoFlatMap.java:241)\n\tat
reactor.core.publisher.Operators$MonoSubscriber.complete(Operators.java:1592)\n\tat
reactor.core.publisher.MonoFlatMap$FlatMapInner.onNext(MonoFlatMap.java:241)\n\tat
reactor.core.publisher.Operators$MonoSubscriber.complete(Operators.java:1592)\n\tat
reactor.core.publisher.MonoSingle$SingleSubscriber.onComplete(MonoSingle.java:171)\n\tat
reactor.core.publisher.FluxMapFuseable$MapFuseableSubscriber.onComplete(FluxMapFuseable.java:144)\n\tat
reactor.core.publisher.FluxJust$WeakScalarSubscription.request(FluxJust.java:101)\n\tat
reactor.core.publisher.FluxMapFuseable$MapFuseableSubscriber.request(FluxMapFuseable.java:162)\n\tat
reactor.core.publisher.MonoSingle$SingleSubscriber.request(MonoSingle.java:94)\n\tat
reactor.core.publisher.MonoFlatMap$FlatMapInner.onSubscribe(MonoFlatMap.java:230)\n\tat
reactor.core.publisher.MonoSingle$SingleSubscriber.onSubscribe(MonoSingle.java:114)\n\tat
reactor.core.publisher.FluxMapFuseable$MapFuseableSubscriber.onSubscribe(FluxMapFuseable.java:90)\n\tat
reactor.core.publisher.FluxJust.subscribe(FluxJust.java:70)\n\tat
reactor.core.publisher.MonoFromFluxOperator.subscribe(MonoFromFluxOperator.java:72)\n\tat
reactor.core.publisher.MonoFlatMap$FlatMapMain.onNext(MonoFlatMap.java:150)\n\tat
reactor.core.publisher.Operators$MonoSubscriber.complete(Operators.java:1592)\n\tat
reactor.core.publisher.MonoSingle$SingleSubscriber.onComplete(MonoSingle.java:171)\n\tat
reactor.core.publisher.Operators$MonoSubscriber.complete(Operators.java:1593)\n\tat
reactor.core.publisher.MonoTakeLastOne$TakeLastOneSubscriber.onComplete(MonoTakeLastOne.java:112)\n\tat
reactor.core.publisher.FluxTakeUntil$TakeUntilPredicateSubscriber.onComplete(FluxTakeUntil.java:114)\n\tat
reactor.core.publisher.FluxTakeUntil$TakeUntilPredicateSubscriber.onNext(FluxTakeUntil.java:92)\n\tat
reactor.core.publisher.FluxRepeat$RepeatSubscriber.onNext(FluxRepeat.java:83)\n\tat
reactor.core.publisher.Operators$MonoSubscriber.complete(Operators.java:1592)\n\tat
reactor.core.publisher.MonoFlatMap$FlatMapMain.onNext(MonoFlatMap.java:144)\n\tat
reactor.core.publisher.FluxMapFuseable$MapFuseableSubscriber.onNext(FluxMapFuseable.java:121)\n\tat
reactor.core.publisher.FluxMapFuseable$MapFuseableSubscriber.onNext(FluxMapFuseable.java:121)\n\tat
reactor.core.publisher.FluxMapFuseable$MapFuseableSubscriber.onNext(FluxMapFuseable.java:121)\n\tat
reactor.core.publisher.Operators$MonoSubscriber.complete(Operators.java:1592)\n\tat
reactor.core.publisher.MonoFlatMap$FlatMapMain.onNext(MonoFlatMap.java:144)\n\tat
reactor.core.publisher.FluxOnErrorResume$ResumeSubscriber.onNext(FluxOnErrorResume.java:73)\n\tat
reactor.core.publisher.FluxMapFuseable$MapFuseableSubscriber.onNext(FluxMapFuseable.java:121)\n\tat
reactor.core.publisher.Operators$MonoSubscriber.complete(Operators.java:1592)\n\tat
reactor.core.publisher.MonoSingle$SingleSubscriber.onComplete(MonoSingle.java:171)\n\tat
reactor.core.publisher.FluxFlatMap$FlatMapMain.checkTerminated(FluxFlatMap.java:823)\n\tat
reactor.core.publisher.FluxFlatMap$FlatMapMain.drainLoop(FluxFlatMap.java:589)\n\tat
reactor.core.publisher.FluxFlatMap$FlatMapMain.drain(FluxFlatMap.java:569)\n\tat
reactor.core.publisher.FluxFlatMap$FlatMapMain.onComplete(FluxFlatMap.java:455)\n\tat
reactor.core.publisher.DrainUtils.postCompleteDrain(DrainUtils.java:131)\n\tat
reactor.core.publisher.DrainUtils.postComplete(DrainUtils.java:186)\n\tat
reactor.core.publisher.FluxMapSignal$FluxMapSignalSubscriber.onComplete(FluxMapSignal.java:213)\n\tat
reactor.core.publisher.Operators$MonoSubscriber.complete(Operators.java:1593)\n\tat
reactor.core.publisher.MonoProcessor.subscribe(MonoProcessor.java:383)\n\tat
reactor.core.publisher.FluxFromMonoOperator.subscribe(FluxFromMonoOperator.java:73)\n\tat
reactor.core.publisher.FluxDefer.subscribe(FluxDefer.java:54)\n\tat
reactor.core.publisher.FluxRepeat$RepeatSubscriber.resubscribe(FluxRepeat.java:113)\n\tat
reactor.core.publisher.FluxRepeat$RepeatSubscriber.onComplete(FluxRepeat.java:97)\n\tat
reactor.core.publisher.FluxRepeat.subscribeOrReturn(FluxRepeat.java:54)\n\tat
reactor.core.publisher.InternalMonoOperator.subscribe(InternalMonoOperator.java:48)\n\tat
reactor.core.publisher.MonoFlatMap$FlatMapMain.onNext(MonoFlatMap.java:150)\n\tat
reactor.core.publisher.SerializedSubscriber.onNext(SerializedSubscriber.java:89)\n\tat
reactor.core.publisher.FluxRetryWhen$RetryWhenMainSubscriber.onNext(FluxRetryWhen.java:148)\n\tat
reactor.core.publisher.Operators$MonoSubscriber.complete(Operators.java:1592)\n\tat
reactor.core.publisher.MonoFlatMap$FlatMapMain.onNext(MonoFlatMap.java:144)\n\tat
reactor.core.publisher.Operators$MonoSubscriber.complete(Operators.java:1592)\n\tat
reactor.core.publisher.MonoSingle$SingleSubscriber.onComplete(MonoSingle.java:171)\n\tat
reactor.core.publisher.FluxMap$MapSubscriber.onComplete(FluxMap.java:136)\n\tat
reactor.core.publisher.FluxMap$MapSubscriber.onComplete(FluxMap.java:136)\n\tat
reactor.core.publisher.Operators$MultiSubscriptionSubscriber.onComplete(Operators.java:1820)\n\tat
reactor.core.publisher.SerializedSubscriber.onComplete(SerializedSubscriber.java:136)\n\tat
reactor.core.publisher.FluxRetryWhen$RetryWhenMainSubscriber.onComplete(FluxRetryWhen.java:170)\n\tat
reactor.core.publisher.Operators$MonoSubscriber.complete(Operators.java:1593)\n\tat
reactor.core.publisher.MonoSingle$SingleSubscriber.onComplete(MonoSingle.java:171)\n\tat
reactor.core.publisher.Operators$MultiSubscriptionSubscriber.onComplete(Operators.java:1820)\n\tat
reactor.core.publisher.FluxMapFuseable$MapFuseableSubscriber.onComplete(FluxMapFuseable.java:144)\n\tat
reactor.core.publisher.Operators$MonoSubscriber.complete(Operators.java:1593)\n\tat
reactor.core.publisher.MonoFlatMap$FlatMapInner.onNext(MonoFlatMap.java:241)\n\tat
reactor.core.publisher.Operators$MonoSubscriber.complete(Operators.java:1592)\n\tat
reactor.core.publisher.MonoSingle$SingleSubscriber.onComplete(MonoSingle.java:171)\n\tat
reactor.core.publisher.FluxFlatMap$FlatMapMain.checkTerminated(FluxFlatMap.java:823)\n\tat
reactor.core.publisher.FluxFlatMap$FlatMapMain.drainLoop(FluxFlatMap.java:589)\n\tat
reactor.core.publisher.FluxFlatMap$FlatMapMain.drain(FluxFlatMap.java:569)\n\tat
reactor.core.publisher.FluxFlatMap$FlatMapMain.onComplete(FluxFlatMap.java:455)\n\tat
reactor.core.publisher.FluxSwitchIfEmpty$SwitchIfEmptySubscriber.onComplete(FluxSwitchIfEmpty.java:78)\n\tat
reactor.core.publisher.FluxHandle$HandleSubscriber.onComplete(FluxHandle.java:206)\n\tat
reactor.core.publisher.FluxMap$MapConditionalSubscriber.onComplete(FluxMap.java:262)\n\tat
reactor.core.publisher.FluxDoFinally$DoFinallySubscriber.onComplete(FluxDoFinally.java:138)\n\tat
reactor.core.publisher.FluxFilterFuseable$FilterFuseableConditionalSubscriber.onComplete(FluxFilterFuseable.java:384)\n\tat
reactor.core.publisher.Operators$MonoSubscriber.complete(Operators.java:1593)\n\tat
reactor.core.publisher.MonoReduceSeed$ReduceSeedSubscriber.onComplete(MonoReduceSeed.java:156)\n\tat
reactor.core.publisher.FluxMap$MapSubscriber.onComplete(FluxMap.java:136)\n\tat
reactor.netty.channel.FluxReceive.terminateReceiver(FluxReceive.java:414)\n\tat
reactor.netty.channel.FluxReceive.drainReceiver(FluxReceive.java:204)\n\tat
reactor.netty.channel.FluxReceive.onInboundComplete(FluxReceive.java:362)\n\tat
reactor.netty.channel.ChannelOperations.onInboundComplete(ChannelOperations.java:363)\n\tat
reactor.netty.channel.ChannelOperations.terminate(ChannelOperations.java:412)\n\tat
reactor.netty.http.client.HttpClientOperations.onInboundNext(HttpClientOperations.java:556)\n\tat
reactor.netty.channel.ChannelOperationsHandler.channelRead(ChannelOperationsHandler.java:93)\n\tat
io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:374)\n\tat
io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:360)\n\tat
io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:352)\n\tat
io.netty.channel.CombinedChannelDuplexHandler$DelegatingChannelHandlerContext.fireChannelRead(CombinedChannelDuplexHandler.java:438)\n\tat
io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:328)\n\tat
io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:302)\n\tat
io.netty.channel.CombinedChannelDuplexHandler.channelRead(CombinedChannelDuplexHandler.java:253)\n\tat
io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:374)\n\tat
io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:360)\n\tat
io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:352)\n\tat
io.netty.handler.ssl.SslHandler.unwrap(SslHandler.java:1475)\n\tat
io.netty.handler.ssl.SslHandler.decodeJdkCompatible(SslHandler.java:1224)\n\tat
io.netty.handler.ssl.SslHandler.decode(SslHandler.java:1271)\n\tat
io.netty.handler.codec.ByteToMessageDecoder.decodeRemovalReentryProtection(ByteToMessageDecoder.java:505)\n\tat
io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:444)\n\tat
io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:283)\n\tat
io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:374)\n\tat
io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:360)\n\tat
io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:352)\n\tat
io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1422)\n\tat
io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:374)\n\tat
io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:360)\n\tat
io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:931)\n\tat
io.netty.channel.epoll.AbstractEpollStreamChannel$EpollStreamUnsafe.epollInReady(AbstractEpollStreamChannel.java:792)\n\tat
io.netty.channel.epoll.EpollEventLoop.processReady(EpollEventLoop.java:483)\n\tat
io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:383)\n\tat
io.netty.util.concurrent.SingleThreadEventExecutor$6.run(SingleThreadEventExecutor.java:1044)\n\tat
io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)\n\tat
io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)\n\tat
java.lang.Thread.run(Thread.java:748)\n




Thanks & Regards,

**Comment by alzimmermsft** [comment]
@kushagraThapar this appears to be in the Cosmos code, I'll hand it off to you for further triage.

**Comment by kushagraThapar** [comment]
@skythegowda Thanks for sharing the logs, however, v3 Java SDK is old and has some issues. We strongly recommend using latest V4 Java SDK. 
Java SDK V4 has been out for a while now, and is very reliable and stable. It has 20-30% performance increase as compared to earlier versions of Java SDK: https://devblogs.microsoft.com/cosmosdb/java-sdk-v4-ga/

Here are the resources to help you migrate and learn more about Java V4 SDK : https://docs.microsoft.com/en-us/azure/cosmos-db/migrate-java-v4-sdk?tabs=java-v4-async
Release notes: https://docs.microsoft.com/en-us/azure/cosmos-db/sql-api-sdk-java-v4
