### ISSUE TITLE
Allow client to configure the request timeout

### ISSUE THREAD

**Issue by li-msmann** [Azure/azure-sdk-for-java#17770]
The request timeout mutator is package private and not visible to be set by the client currently. 
Request to support configuring the request timeout by the client.

Code Reference:

https://github.com/Azure/azure-sdk-for-java/blob/8650b84cda3636b56a48634cb7eed223381dae35/sdk/cosmos/azure-cosmos/src/main/java/com/azure/cosmos/DirectConnectionConfig.java#L254

**Comment by kushagraThapar** [comment]
@li-msmann this feature is in our backlog for next semester. We will update the documentation once this feature is done.
