### ISSUE TITLE
[BUG] Criteria: Invalid query. Specified duplicate parameter name

### ISSUE THREAD

**Issue by sburlyaev** [Azure/azure-sdk-for-java#17795]
**Describe the bug**
Method `generateBinaryQuery()` of `com.azure.spring.data.cosmos.core.generator.AbstractQueryGenerator` class gives the same parameter name for every subject `Criteria`. So, there is no way to perform a complex query with multiple conditions for the same field.

***Exception or Stack Trace***
```
com.azure.data.cosmos.CosmosClientException: Gateway Failed to Retrieve Query Plan:
Message: {"Errors":["Invalid query. Specified duplicate parameter name '@field'."]}
```

**To Reproduce**
Execute the following query:
```java
Criteria c0 = Criteria.getInstance(CriteriaType.IS_EQUAL, field, List.of(value1), Part.IgnoreCaseType.NEVER);
Criteria c1 = Criteria.getInstance(CriteriaType.IS_EQUAL, field, List.of(value2), Part.IgnoreCaseType.NEVER);
Criteria c2 = Criteria.getInstance(CriteriaType.GREATER_THAN, field2, List.of(value), Part.IgnoreCaseType.NEVER);
Criteria c12 = Criteria.getInstance(CriteriaType.AND, c1, c2);
Criteria criteria = Criteria.getInstance(CriteriaType.OR, c0, c12);
// SELECT * FROM ROOT r WHERE r.field = @field OR r.field = @field AND r.field2 > @field2 

CosmosQuery cosmosQuery = new CosmosQuery(criteria);
operations.find(cosmosQuery, Domain.class, information.getContainerName());
```

***Code Snippet***
```java
...
final String subject = criteria.getSubject();
final String parameter = subject.replaceAll("\\.", "_");
parameters.add(Pair.of(parameter, subjectValue));
...
return String.format("r.%s %s @%s", subject, sqlKeyword, parameter);
```

**Expected behavior**
Build and run any complex queries.

**Setup:**
- com.azure:azure-spring-data-cosmos:3.1.0

**Information Checklist**
Kindly make sure that you have added all the following information above and checkoff the required fields otherwise we will treat the issuer as an incomplete report
- [x] Bug Description Added
- [x] Repro Steps Added
- [x] Setup information Added

**Comment by kushagraThapar** [comment]
@mbhaskar  - please take a look at this.

**Comment by kushagraThapar** [comment]
@sburlyaev - I believe this has already been fixed in the latest version of the SDK - please upgrade and test it.
