### ISSUE TITLE
Does not use chosen subscription - via CLI

### ISSUE THREAD

**Issue by selvasingh** [Azure/azure-sdk-for-java#1779]
"When using Azure CLI 2.0 as the authentication approach, Azure Java SDK doesn’t use the default subscription configured with `az account set`. Instead, the first subscription is picked up" - @xscript

**Comment by yungezz** [comment]
need to check if track1 runtime pickup subs from az cli profile. @xccc-msft could you pls help to have a look?

**Comment by xccc-msft** [comment]
@yungezz This is legacy issue, which has been fixed by [client-runtime](https://github.com/Azure/autorest-clientruntime-for-java/blob/master/azure-client-authentication/src/main/java/com/microsoft/azure/credentials/AzureCliCredentials.java#L59-L61).

**Comment by yungezz** [comment]
hi @selvasingh the issue has been fixed as @xccc-msft mentioned, will close the issue for now. thanks.
