### ISSUE TITLE
java.lang.IllegalArgumentException: No enum constant com.microsoft.azure.management.compute.models.ComputeOperationStatus.Canceled

### ISSUE THREAD

**Issue by LinaKorn** [Azure/azure-sdk-for-java#1783]
**SDK 0.9.7**

When VM is in creating state and user delete it manually in Azure portal an error occurred  
`java.lang.IllegalArgumentException: No enum constant com.microsoft.azure.management.compute.models.ComputeOperationStatus.Canceled.`
 In the new version of SDK you don't use ComputeOperationStatus enum, just works with strings. Does current problem solved in the new version of SDK (1.0.0)?

**Comment by anuchandy** [comment]
with latest SDK, in this case the create long running operation throws CloudException with below information

```
  "status": "Canceled",
  "error": {
    "code": "OperationPreempted",
    "message": "The operation has been preempted by a more recent operation."
  },
```
