### ISSUE TITLE
How to call delete blob to clear some older blobs based on time

### ISSUE THREAD

**Issue by harisingh-highq** [Azure/azure-sdk-for-java#17854]
I have a requirement to delete older reports(blob files) older than 4 days.

For that I've tried below program but its not working. Actually last modified property is not return timestamp so it is causing issue.

Calendar cal = Calendar.getInstance();

List<String> paths = blobContainerClient.listBlobsByHierarchy(folderPath).stream().map(BlobItem::getName).collect(toList());

for(String path : paths) 
{
	try{
		BlobClient blobFile = blobContainerClient.getBlobClient(path);
		long diff = cal.getTimeInMillis() - blobFile.getProperties().getLastModified().getLong(null);
		long diffHours = diff / (60 * 60 * 1000);
		if(diffHours > 96){
			blobFile.delete();
		}
	}catch(Exception e){
		logger.error("AZURE -Exception in deleteOlderReports");
	}
}
	
Can anyone help me to sort out this or can provide any alternative solution?
Thanks

**Comment by gapra-msft** [comment]
Hi @harisingh-highq 

Thanks for posting your question.

It looks like `null` is not a relevant input to the getLong method (so it throws a NPE). Could you replace that with your expected time unit? 

OffsetDateTime supports the following methods. Maybe getNano() / 10^6 would also work for you.

**Comment by harisingh-highq** [comment]
@gapra-msft 
Thanks a lot for your response.

Yes, it was throwing NPE due to null value assigned but getNano() also return 0 value.
So I've done changes as per below and its working for me

![image](https://user-images.githubusercontent.com/33862788/100731977-1efe0c00-33f2-11eb-9007-296e580e101a.png)

Correct me please, if anything wrong here.

**Comment by gapra-msft** [comment]
@harisingh-highq 

That looks right. Sorry, my earlier suggestion was incorrect since that doesnt return time since epoch.

**Comment by gapra-msft** [comment]
@harisingh-highq 

It looks like your original issue was resolved, so I'll go ahead and close this issue.

Feel free to open a new issue in case you have any more questions!
