### ISSUE TITLE
Deprecate AADAuthenticationFilter and AADAppRoleStatelessAuthenticationFilter

### ISSUE THREAD

**Issue by chenrujun** [Azure/azure-sdk-for-java#17860]
Mark 2 Filters as deprecated in favor of leveraging AAD enhancements of spring-security-resource-server directly.

Please follow [how to integrate aad starter with resource server](https://github.com/Azure/azure-sdk-for-java/tree/master/sdk/spring/azure-spring-boot-starter-active-directory#protect-the-resource-api-through-resource-server) and [aad sample for resource server](https://github.com/Azure/azure-sdk-for-java/tree/master/sdk/spring/azure-spring-boot-samples/azure-spring-boot-sample-active-directory-spring-security-resource-server) for more information.

Refs: https://docs.spring.io/spring-security/site/docs/current/reference/html5/#oauth2resourceserver-jwt-validation-custom

**Comment by chenrujun** [comment]
- For `AADAppRoleStatelessAuthenticationFilter`, suggest customer use spring-security resource-server directly.
 - For `AADAuthenticationFilter`, tell the customer that in normal case, resource-server not support session. So `AADAuthenticationFilter` will not supported in the future.

**Comment by DRoppelt** [comment]
@chenrujun 

with the provided links, I have a hard time seeing how "Authenticate stateless web API by a filter, using AAD app roles" (https://github.com/Azure/azure-sdk-for-java/tree/master/sdk/spring/azure-spring-boot-starter-active-directory#web-api-deprecated-authenticate-stateless-web-api-by-a-filter-using-aad-app-roles) can be done without the now deprecated class. That page just links back to this issue again.

Is that functionality possible without that filter? If so, where can I find that out? Do you want to to create a ticket for that question?

**Comment by saragluna** [comment]
Hi @DRoppelt, sorry for not making the migration clear. 

You could follow this [sample](https://github.com/Azure/azure-sdk-for-java/blob/master/sdk/spring/azure-spring-boot-samples/azure-spring-boot-sample-active-directory-resource-server/README.md)  to see how to use AAD starter in a resource server.

You could follow this [code](https://github.com/Azure/azure-sdk-for-java/blob/3a1ec47aca9c90fe7a588d51b44eb0451eb09b30/sdk/spring/azure-spring-boot-samples/azure-spring-boot-sample-active-directory-resource-server/src/main/java/com/azure/spring/sample/aad/security/AADOAuth2ResourceServerSecurityConfig.java#L22) to configure the `AADJwtBearerTokenAuthenticationConverter`, which by default maps the `scope` claim to GrantedAuthorities. 
```java
    @Override
    protected void configure(HttpSecurity http) throws Exception {
        http.authorizeRequests((requests) -> requests.anyRequest().authenticated())
            .oauth2ResourceServer()
            .jwt()
            .jwtAuthenticationConverter(new AADJwtBearerTokenAuthenticationConverter());
    }
```


In case you want to configure to use another claim, just need to change the initialization to something like: 
```java
new AADJwtBearerTokenAuthenticationConverter("roles", "ROLE_")
```

**Comment by michal-petrik** [comment]
Hi @saragluna,

thank you for the sample. However, what if the token does not contain the desired scopes? I am referring to the previous implementation using `AADAuthenticationFilter` when the code calls MS Graph to get user groups/role (in case they are not a part of the token). Is the only option to do it now by implementing my own AADJwtBearerTokenAuthenticationConverter version (which calls MS Graph and maps roles/groups)?

Thank you.

**Comment by saragluna** [comment]
@michal-petrik sorry I missed this message. Yes, if you still want to have the ability to use groups to do your authorization in a resource server.

**Comment by vinceve** [comment]
@saragluna Do you have an idea on how to test authorization for integration tests? I don't see how I can use @WithMockUser

**Comment by Abheeshskurup** [comment]
@saragluna  ..hey i am facing the deprecation issue since i upgraded the azure jars. I have added the sample code instead of the filter but still no luck. Always unauthorized. Also if i understand correctly we need to define azure.activedirectory.app-id-uri right ...I am new to Azure AD and may i know where can i see the uri..

**Comment by chenrujun** [comment]
Hi, @Abheeshskurup, please refer to `API's application ID URI` in this page: https://docs.microsoft.com/en-us/azure/active-directory/develop/quickstart-configure-app-expose-web-apis#verify-the-exposed-scopes

**Comment by ibtissambth** [comment]
d
