### ISSUE TITLE
Declared new pubic API functions are private in ClientCertificateCredentialBuilder

### ISSUE THREAD

**Issue by alexey-kadyrov-r3** [Azure/azure-sdk-for-java#17877]
The `pfxCertificate(InputStream certificate, String clientCertificatePassword)` and `pemCertificate(InputStream certificate)` functions introduced and declared in 1.2.0-beta.2 are private (see https://github.com/Azure/azure-sdk-for-java/blob/0579b470d43d874b559a13fb421abda9cdb07b3b/sdk/identity/azure-identity/CHANGELOG.md#new-features-1).

It's expected that the functions will be public.

**Comment by timja** [comment]
I hit this also, can these be made public?
I've had to create my own credential class by copying `ClientCertificateCredential`

So that I can set the `InputStream`

**Comment by mkomko** [comment]
Same here. We are reading the certificate from a keystore so cannot provide a file path.
