### ISSUE TITLE
When will Azure event hub schema registry be ready for production?

### ISSUE THREAD

**Issue by casper-79** [Azure/azure-sdk-for-java#17878]
**Query/Question**
Hi.

We are considering using Azure event hub in a new system we are currently building, but we are a little concerned about schema registry still being in preview. 

Could you provide guidance on when schema registry is expected to be ready for production?

Best regards,

Casper

***Why is this not a Bug or a feature Request?***
It is a timeline question.
 
 **Information Checklist**
 Kindly make sure that you have added all the following information above and checkoff the required fields otherwise we will treat the issuer as an incomplete report
- [x] Query Added
- [x] Setup information Added

**Comment by casper-79** [comment]
@alzimmermsft Any update on this?

Apart from information on the roadmap towards production quality, we are also interested in when relevant tooling will become available. It is very inconvenient that schema registry is only accessible from the portal, since it makes it hard to include in an automated pipeline. Any plans for supporting schema registry resource management from ARM templates or using the AZ cli?

**Comment by alzimmermsft** [comment]
@arerlend could you update this with the latest information?

**Comment by arerlend** [comment]
@sjkwak

**Comment by casper-79** [comment]
@alzimmermsft @arerlend @sjkwak 

Any update on this?

Cheers,

Casper

**Comment by ramya-rao-a** [comment]
@casper-79 

The Schema Registry service and the client library to access it [azure-data-schemaregistry](https://mvnrepository.com/artifact/com.azure/azure-data-schemaregistry) are both out of preview.

We are still working on the [azure-data-schemaregistry-avro](https://mvnrepository.com/artifact/com.azure/azure-data-schemaregistry-avro) package that provides the avro serializer that uses Schema Registry. We plan to move this package out of this preview by the end of this semester.
