### ISSUE TITLE
[FEATURE REQ] 

### ISSUE THREAD

**Issue by YijunXieMS** [Azure/azure-sdk-for-java#17888]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Information Checklist**
Kindly make sure that you have added all the following information above and checkoff the required fields otherwise we will treat the issuer as an incomplete report
- [ ] Description Added
- [ ] Expected solution specified

**Comment by rickle-msft** [comment]
This issue is empty and seems to have been opened by accident.

**Comment by YijunXieMS** [comment]
I was going to open an issue but hadn't finished it. Probably the submit button was clicked accidentally.

**Comment by rickle-msft** [comment]
I see. Feel free to open it when you're ready :)
