### ISSUE TITLE
[QUERY] CosmosTemplate ignores PageRequest's page

### ISSUE THREAD

**Issue by sburlyaev** [Azure/azure-sdk-for-java#17921]
**Question**
Why does `com.azure.spring.data.cosmos.core.CosmosTemplate::paginationQuery` ignore `org.springframework.data.domain.PageRequest`'s `page` argument?

***Why is this not a Bug or a feature Request?***
Maybe it is.

**Setup:**
 - com.azure:azure-spring-data-cosmos:3.1.0

**Comment by kushagraThapar** [comment]
@mbhaskar  - please take a look at this issue.

**Comment by kushagraThapar** [comment]
@sburlyaev - The reason for this is because there is no notion of page number for Cosmos SDK queries from Cosmos Java SDK. That's why the page number is ignored. 
If in future, we add the support in Java SDK, we will add the support to spring data cosmos SDK as well. 
For now, I am closing this issue as it is not even planned in our backlog. 
@mbhaskar  - please correct me if I am wrong.

**Comment by azizabah** [comment]
@kushagraThapar  - Is there an example for how you would call say the 10th page in a set of results straight away without first calling the other 9 pages?

**Comment by kushagraThapar** [comment]
@azizabah - the only way to do that would be to use OFFSET and LIMIT together, for skipping the first 9 pages using OFFSET, and LIMIT to define the page size you want. However, it is not the most efficient way of running the query, but its the only way for now.

**Comment by azizabah** [comment]
> @azizabah - the only way to do that would be to use OFFSET and LIMIT together, for skipping the first 9 pages using OFFSET, and LIMIT to define the page size you want. **However, it is not the most efficient way of running the query**, but its the only way for now.

@kushagraThapar -  Is there something about the OFFSET performance that makes it bad? I feel like I remember reading that the offset is utilized by the database to basically do the iteration through pages on the DB side and would probably be slow (comparatively) and expensive in terms of RUs. Is that recollection correct?

**Comment by kushagraThapar** [comment]
@azizabah yes, that is correct. It internally iterates over the pages, and then skips them hence returning the desired page.

**Comment by azizabah** [comment]
@kushagraThapar  - Thanks for the confirmation.
