### ISSUE TITLE
[QUERY] CosmosQuery offset parameter

### ISSUE THREAD

**Issue by sburlyaev** [Azure/azure-sdk-for-java#17920]
**Question**
Why doesn't `com.azure.spring.data.cosmos.core.query.CosmosQuery` provide `offset` parameter?

**Setup**
 - com.azure:azure-spring-data-cosmos:3.1.0

**Comment by kushagraThapar** [comment]
@mbhaskar  - please take a look at this issue.

**Comment by mbhaskar** [comment]
You can use annotated queries to specify offset/limit. Please find documentation here https://docs.microsoft.com/en-us/azure/developer/java/spring-framework/how-to-guides-spring-data-cosmosdb#custom-query-execution
