### ISSUE TITLE
[QUERY] CosmosTemplate always sets offset to 0 when limit is set

### ISSUE THREAD

**Issue by sburlyaev** [Azure/azure-sdk-for-java#17927]
**Question**
Why does `com.azure.spring.data.cosmos.core.CosmosTemplate::paginationQuery` ignore `com.azure.spring.data.cosmos.core.query.Pageable`'s offset-related properties and always set `OFFSET 0` when `limit` is set for `CosmosQuery`?

**Setup:**
 - com.azure:azure-spring-data-cosmos:3.1.0

**Comment by kushagraThapar** [comment]
@mbhaskar  - please take a look at this issue.

**Comment by kushagraThapar** [comment]
@sburlyaev - not sure what you mean by setting the offset to 0 always. I checked the code and I see that the offset is being set from `pageable` object- https://github.com/Azure/azure-sdk-for-java/blob/master/sdk/cosmos/azure-spring-data-cosmos/src/main/java/com/azure/spring/data/cosmos/core/CosmosTemplate.java#L732

**Comment by sburlyaev** [comment]
@kushagraThapar you are pointing to the response object which does nothing with the offset value but just return it.
The request happens on the [line 680](https://github.com/Azure/azure-sdk-for-java/blob/master/sdk/cosmos/azure-spring-data-cosmos/src/main/java/com/azure/spring/data/cosmos/core/CosmosTemplate.java#L680) and it uses continuation token and page size only. So, it forces to use continuation token and not offset.

**Comment by kushagraThapar** [comment]
@sburlyaev - Please look at this example to see how the `OFFSET` is used and applied : https://github.com/Azure/azure-sdk-for-java/blob/master/sdk/cosmos/azure-spring-data-cosmos-test/src/test/java/com/azure/spring/data/cosmos/repository/integration/ContactRepositoryIT.java#L235

**Comment by sburlyaev** [comment]
Thank you!

**Comment by azizabah** [comment]
@kushagraThapar  - Is there an example of doing this using a CosmosQuery? We are trying to deal with the Cosmos limitations on pagination and given that this [line of code exists](https://github.com/Azure/azure-sdk-for-java/blob/9873a52e38fa63e9a7c0a70e084420603d2d9fa2/sdk/cosmos/azure-spring-data-cosmos/src/main/java/com/azure/spring/data/cosmos/core/generator/AbstractQueryGenerator.java#L271), we are going to run into some serious problems.
