### ISSUE TITLE
[QUERY] Cosmos Criteria API: How to place brackets?

### ISSUE THREAD

**Issue by sburlyaev** [Azure/azure-sdk-for-java#17929]
**Question**
How to place brackets to the query using Cosmos Criteria API?

**Setup:**
 - com.azure:azure-spring-data-cosmos:3.1.0

**Comment by kushagraThapar** [comment]
@mbhaskar  - please take a look at this issue.

**Comment by mbhaskar** [comment]
@sburlyaev  Can you give an example of what exactly you are trying to do? Thanks

**Comment by sburlyaev** [comment]
something like `SELECT * FROM c WHERE c.id = @userId AND (c.status = 'ACTIVE' OR NOT IS_DEFINED(c.status))` but with Criteria API.

**Comment by kushagraThapar** [comment]
@mbhaskar - ping.

**Comment by trande4884** [comment]
This can currently only be completed via annotated queries. There are no plans to add this to Criteria so please use annotated queries for your solution.

**Comment by trande4884** [comment]
This was added via this PR: https://github.com/Azure/azure-sdk-for-java/pull/24929
