### ISSUE TITLE
[FEATURE REQ] Storage log string to sign 

### ISSUE THREAD

**Issue by rickle-msft** [Azure/azure-sdk-for-java#17935]
We should log the string to sign used for sas and shared key to make it easier for customers to debug auth issues. Currently they have to set a breakpoint where we generate the string to sign.

**Comment by rickle-msft** [comment]
We need to consider security here because the logging policy redacts all the headers by default, so then if we log them in the string to sign it sort of defeats the point, but then we don't really have access to what headers the logging policy is going to log, so maybe it's a separate option we can enable on the credentials policy?

And I think we could also possible wrap 403 errors that points people to saying "you're getting an auth failure, go turn on this option to log the string to sign and compare"

**Comment by alzimmermsft** [comment]
I agree that enabling the string-to-sign to be logged does introduce security risks. But, as long as this feature isn't on by default and has strong Javadocs explaining that enabling it may allow PII to be logged I'm good with adding this feature. Give strong explanation that it should primarily be used during development to troubleshoot authorization issues.
