### ISSUE TITLE
[DOC BUG] ServiceBus Readme code snippet for ServiceBusProcessorClient.processError at time of building

### ISSUE THREAD

**Issue by hemanttanwar** [Azure/azure-sdk-for-java#17932]
Issue : The Readme sample is wrong for `ServiceBusProcessorClient` and for `processError`.

A motivated community member @frascu  have raised  PR for this. 

https://github.com/Azure/azure-sdk-for-java/pull/17925

We will fix this via using embedme tool which uses compiled java source code to embed source code into readme. so this problem never happens again.

**Comment by frascu** [comment]
@hemanttanwar 
This issue can be closed because the pull request that resolves it has been merged.

**Comment by hemanttanwar** [comment]
Thank you @frascu closing this issue.
