### ISSUE TITLE
[BUG] Blob Storage download behind authenticated proxy server not working without accessible DNS server

### ISSUE THREAD

**Issue by sesu-bio** [Azure/azure-sdk-for-java#17930]
**Describe the bug**
We are using the Blob Storage SDK v12.8.0 and want to implement proxy support in our product. Unauthenticated proxy servers work fine but once credentials are supplied, the download only works when the device has a direct internet connection. As it turns out, a DNS server must be available for the downloads to work. It looks like the SDK tries to resolve the hostname before even trying to contact the proxy server and throws an exception if it does not succeed.

***Exception or Stack Trace***
> Exception in thread "main" reactor.core.Exceptions$ReactiveException: java.net.UnknownHostException: portosmoketeststorage.blob.core.windows.net: Temporary failure in name resolution
>         at reactor.core.Exceptions.propagate(Exceptions.java:393)
>         at reactor.core.publisher.BlockingSingleSubscriber.blockingGet(BlockingSingleSubscriber.java:97)
>         at reactor.core.publisher.Mono.block(Mono.java:1680)
>         at com.azure.storage.common.implementation.StorageImplUtils.blockWithOptionalTimeout(StorageImplUtils.java:99)
>         at com.azure.storage.blob.specialized.BlobClientBase.downloadToFileWithResponse(BlobClientBase.java:630)
>         at com.azure.storage.blob.specialized.BlobClientBase.downloadToFile(BlobClientBase.java:561)
>         at maventest.BugDemo.main(BugDemo.java:34)
>         at maventest.Test.main(Test.java:10)
>         Suppressed: java.lang.Exception: #block terminated with an error
>                 at reactor.core.publisher.BlockingSingleSubscriber.blockingGet(BlockingSingleSubscriber.java:99)
>                 ... 6 more
> Caused by: java.net.UnknownHostException: portosmoketeststorage.blob.core.windows.net: Temporary failure in name resolution
>         at java.net.Inet4AddressImpl.lookupAllHostAddr(Native Method)
>         at java.net.InetAddress$2.lookupAllHostAddr(InetAddress.java:929)
>         at java.net.InetAddress.getAddressesFromNameService(InetAddress.java:1324)
>         at java.net.InetAddress.getAllByName0(InetAddress.java:1277)
>         at java.net.InetAddress.getAllByName(InetAddress.java:1193)
>         at java.net.InetAddress.getAllByName(InetAddress.java:1127)
>         at java.net.InetAddress.getByName(InetAddress.java:1077)
>         at io.netty.util.internal.SocketUtils$8.run(SocketUtils.java:156)
>         at io.netty.util.internal.SocketUtils$8.run(SocketUtils.java:153)
>         at java.security.AccessController.doPrivileged(Native Method)
>         at io.netty.util.internal.SocketUtils.addressByName(SocketUtils.java:153)
>         at io.netty.resolver.DefaultNameResolver.doResolve(DefaultNameResolver.java:41)
>         at io.netty.resolver.SimpleNameResolver.resolve(SimpleNameResolver.java:61)
>         at io.netty.resolver.SimpleNameResolver.resolve(SimpleNameResolver.java:53)
>         at io.netty.resolver.InetSocketAddressResolver.doResolve(InetSocketAddressResolver.java:55)
>         at io.netty.resolver.InetSocketAddressResolver.doResolve(InetSocketAddressResolver.java:31)
>         at io.netty.resolver.AbstractAddressResolver.resolve(AbstractAddressResolver.java:106)
>         at io.netty.bootstrap.Bootstrap.doResolveAndConnect0(Bootstrap.java:206)
>         at io.netty.bootstrap.Bootstrap.access$000(Bootstrap.java:46)
>         at io.netty.bootstrap.Bootstrap$1.operationComplete(Bootstrap.java:180)
>         at io.netty.bootstrap.Bootstrap$1.operationComplete(Bootstrap.java:166)
>         at io.netty.util.concurrent.DefaultPromise.notifyListener0(DefaultPromise.java:577)
>         at io.netty.util.concurrent.DefaultPromise.notifyListenersNow(DefaultPromise.java:551)
>         at io.netty.util.concurrent.DefaultPromise.notifyListeners(DefaultPromise.java:490)
>         at io.netty.util.concurrent.DefaultPromise.setValue0(DefaultPromise.java:615)
>         at io.netty.util.concurrent.DefaultPromise.setSuccess0(DefaultPromise.java:604)
>         at io.netty.util.concurrent.DefaultPromise.trySuccess(DefaultPromise.java:104)
>         at io.netty.channel.DefaultChannelPromise.trySuccess(DefaultChannelPromise.java:84)
>         at io.netty.channel.AbstractChannel$AbstractUnsafe.safeSetSuccess(AbstractChannel.java:984)
>         at io.netty.channel.AbstractChannel$AbstractUnsafe.register0(AbstractChannel.java:504)
>         at io.netty.channel.AbstractChannel$AbstractUnsafe.access$200(AbstractChannel.java:417)
>         at io.netty.channel.AbstractChannel$AbstractUnsafe$1.run(AbstractChannel.java:474)
>         at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:164)
>         at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:472)
>         at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:500)
>         at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989)
>         at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
>         at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
>         at java.lang.Thread.run(Thread.java:748)

**To Reproduce**
- disable internet access or block the DNS ports
- configure a proxy server with username and password provided
- download a file --> fails

***Code Snippet***
````
public static void main(String[] args) throws IOException {
		String TEST_URL = "https://xyz.blob.core.windows.net/deviceuploads/xyz";

		// proxy server accepts both unauthenticated and authenticated requests
		String PROXY_HOST = "<proxy host>";
		final String PROXY_PORT = "3128";
		final String PROXY_USER = "testuser";
		final String PROXY_PASS = "pass";
		final int PROXY_PORT_INT = Integer.parseInt(PROXY_PORT);

		// non-authenticated proxy works with and without internet connection
		try {
			ProxyOptions nonAuthProxyOptions = new ProxyOptions(ProxyOptions.Type.HTTP,
					new InetSocketAddress(PROXY_HOST, PROXY_PORT_INT));
			HttpClient nonAuthClient = new NettyAsyncHttpClientBuilder().proxy(nonAuthProxyOptions).build();
			BlobClient nonAuthBlobClient = new BlobClientBuilder().endpoint(TEST_URL).httpClient(nonAuthClient)
					.buildClient();
			nonAuthBlobClient.downloadToFile("hello_world1.txt", true);
			System.out.println("non auth succeeded");
		} catch (Exception e) {
			System.out.println("non auth failed");
		}

		// authenticated proxy only works with internet connection for DNS querys
		try {
			ProxyOptions authProxyOptions = new ProxyOptions(ProxyOptions.Type.HTTP,
					new InetSocketAddress(PROXY_HOST, PROXY_PORT_INT));
			authProxyOptions.setCredentials(PROXY_USER, PROXY_PASS);
			HttpClient authClient = new NettyAsyncHttpClientBuilder().proxy(authProxyOptions).build();
			BlobClient authBlobClient = new BlobClientBuilder().endpoint(TEST_URL).httpClient(authClient).buildClient();
			authBlobClient.downloadToFile("hello_world2.txt", true);
			System.out.println("with auth succeeded");
		} catch (Exception e) {
			System.out.println("with auth failed");
		}
		
	}
````

**Expected behavior**
The SDK should not try to resolve the hostname and instead transmit it to the proxy server just like it does with unauthenticated proxies.

**Setup (please complete the following information):**
 - OS: Linux
 - IDE : Eclipse
 - Blob Storage SDK v12.8.0

**Information Checklist**
Kindly make sure that you have added all the following information above and checkoff the required fields otherwise we will treat the issuer as an incomplete report
- [x ] Bug Description Added
- [x ] Repro Steps Added
- [x ] Setup information Added

**Comment by rickle-msft** [comment]
@alzimmermsft Can you speak to the behavior of netty when working with authenticated proxies and no DNS?

**Comment by alzimmermsft** [comment]
Hi @sesu-bio, I've looked into this issue and it appears that when the non-authorized proxy is used a no-op address resolver will be applied to the Netty pipeline. When an authorized proxy is used this doesn't happen and DNS will be called to perform an address resolution. I'll continue looking into this to determine how we can prevent DNS resolution when using an authorized proxy.

**Comment by sesu-bio** [comment]
Hi @alzimmermsft,
Thank you for looking into it. I did some testing with the okhttp http client and can confirm that the issue is not present with that. Therefore, using a different http client might be a feasible workaround for anyone running into the issue.

**Comment by sesu-bio** [comment]
Looks like there are test failures on the PR. Is this still being worked on?
