### ISSUE TITLE
Guidance in Event Grid SDK Version to use for Publish and Susbscribe

### ISSUE THREAD

**Issue by fragmadata** [Azure/azure-sdk-for-java#17949]
**Query/Question**
We wish to develop both Event Grid Publishers and Consumers in Java.
What is the stable version of the SDK which we should go with?

***Why is this not a Bug or a feature Request?***
This question is more about guidance - we see that with 2.0.0-beta.3 there are APIs to consumption too - however that is in beta.
We wanted to understand which is the stable java SDK version to use which supports consumption as well. The stable versions which we see is 1.2.0, which only supports publish.

**Setup (please complete the following information if applicable):**
 - IDE : [e.g. IntelliJ]
 - Version of the Library used
 
 **Information Checklist**
 Kindly make sure that you have added all the following information above and checkoff the required fields otherwise we will treat the issuer as an incomplete report
- [ ] Query Added
- [ ] Setup information Added

**Comment by YijunXieMS** [comment]
Hi @fragmadata,
This is the last stable version of event grid java. https://mvnrepository.com/artifact/com.microsoft.azure/azure-eventgrid/1.3.0
```xml
<!-- https://mvnrepository.com/artifact/com.microsoft.azure/azure-eventgrid -->
<dependency>
    <groupId>com.microsoft.azure</groupId>
    <artifactId>azure-eventgrid</artifactId>
    <version>1.3.0</version>
</dependency>
```
The new stable 2.0.0 will come in a few months.
Let me know if you have more questions.

**Comment by YijunXieMS** [comment]
@fragmadata 
For consumption, you may need to setup a subscriber in the portal. Refer to [event grid subscribe](https://docs.microsoft.com/en-us/azure/event-grid/subscribe-through-portal#:~:text=%20Create%20event%20subscriptions%20%201%20Select%20All,Subscribe%20to%20all%20event%20types%20option...%20More%20).

Then use other SDKs to consumer the events. For instance, if you subscribe it to an EventHub, you can then use an EventHub SDK to consumer events. You can also subscribe it to a ServiceBus, Storage, Azure Function, Webhook, etc. Refer to [Edit Subscription](https://docs.microsoft.com/en-us/azure/event-grid/subscribe-through-portal#:~:text=%20Create%20event%20subscriptions%20%201%20Select%20All,Subscribe%20to%20all%20event%20types%20option...%20More%20)

**Comment by YijunXieMS** [comment]
@fragmadata I'm closing this issue now. Please feel free to reopen it or create a new issue if you have more questions.
