### ISSUE TITLE
[Identity] Grab Azure Environment, tenant id, and selected subscriptions from azure cli/intellij/vscode/visual studio/managed identity tokens

### ISSUE THREAD

**Issue by andxu** [Azure/azure-sdk-for-java#17946]
We are writing some plugins using azure identity to auth, the major problem is we don't know the default sub id, azure environment, they are very important, since in most cases, user would like to share not only credentials but also account settings like azure environment, selected subscriptions, for example: in Azure Maven Webapp plugin, if user specify the authType=AzureCli, and he doesn't provide subscription, currently he will be forced to select the first subs which he might have no full access, so the subs he selected in Azure cli is very important.

**Comment by g2vinay** [comment]
@andxu 

Currently, there is no information provided by VSCode /Visual Studio and Managed Identity auth Rest endpoints about the subscription id, so there is no way for it to be retrieved.
With Azure CLI, it is theoretically possible to read the subscription id, but it would be a potential privacy breach and a PII issue to expose it out in the output.
