### ISSUE TITLE
[BUG] NullPointerException in KeyVaultKeyManagerFactory

### ISSUE THREAD

**Issue by StephaneVa** [Azure/azure-sdk-for-java#17953]
**Describe the bug**
When [KeyVaultKeyManagerFactory.engineInit](https://github.com/Azure/azure-sdk-for-java/blob/master/sdk/keyvault/azure-security-keyvault-jca/src/main/java/com/azure/security/keyvault/jca/KeyVaultKeyManagerFactory.java#L30) is called with a null password, the LOGGER cause a NPE due to `new String(password)`

***Exception or Stack Trace***
Caused by: java.lang.NullPointerException: null
at java.base/java.lang.String.<init>(String.java:251)
at com.azure.security.keyvault.jca.KeyVaultKeyManagerFactory.engineInit (KeyVaultKeyManagerFactory.java:31) ~[azure-security-keyvault-jca:1.0.0-beta.2.jar:na]
at java.base/javax.net.ssl.KeyManagerFactory.init(KeyManagerFactory.java:271)
...
at java.base/javax.net.ssl.SSLContext.getDefault(SSLContext.java:99)
at org.elasticsearch.client.RestClientBuilder.createHttpClient(RestClientBuilder.java:212)

**To Reproduce**
I've follow https://docs.microsoft.com/en-us/java/api/overview/azure/spring-boot-starter-keyvault-certificates-readme-pre?view=azure-java-stable#using-a-managed-identity on an existing HelloWorld app, which push logs to an elasticsearch, thanks to a HttpClient. 

The ssl context is loaded when the elasticsearch RestClientBuilder is init in order to push the logs when the app starts. I've no issue without the spring-boot-starter-keyvault-certificates.

workaround: 
run app with `-Djavax.net.ssl.keyStorePassword=any_value_works`

**Expected behavior**
The [KeyVaultKeyManager](https://github.com/Azure/azure-sdk-for-java/blob/master/sdk/keyvault/azure-security-keyvault-jca/src/main/java/com/azure/security/keyvault/jca/KeyVaultKeyManager.java#L53) should be initialized with a null password with this factory.

**Setup (please complete the following information):**
 - OS: alpine + openjdk11
 - Version of the Library used : azure-spring-boot-starter-keyvault-certificates:3.0.0-beta.2 which include azure-security-keyvault-jca:1.0.0-beta.2

**Comment by lzc-1997-abel** [comment]
Thanks for your reporting, we will look into it.
