### ISSUE TITLE
[BUG] Never throw GoneException on the public surface area

### ISSUE THREAD

**Issue by moderakh** [Azure/azure-sdk-for-java#17968]
We should never throw GoneException 410 from the public surface area.

GoneAndRetryPolicy should handle GoneException 410 and if all of its retry attempts are exhausted it should throw 503.

**Comment by matthew-kirtley** [comment]
Hi.  We're currently seeing 410s occasionally when our cosmos DB is under load.  What is the recommended solution for handling this?  Should we increase our throughput?  Also, why do we not see 429s instead of 410s?  Thanks.

**Comment by kushagraThapar** [comment]
@moderakh - is this still an open issue ?

**Comment by kushagraThapar** [comment]
@moderakh @xinlian12  - did we already fix it or is this issue still open ?

**Comment by moderakh** [comment]
this is still issue @kushagraThapar

**Comment by kushagraThapar** [comment]
This is fixed.
