### ISSUE TITLE
[QUERY] When will com.azure.spring:azure-spring-boot-starter-active-directory:3.0.0 be released? 

### ISSUE THREAD

**Issue by cccs-cat001** [Azure/azure-sdk-for-java#17960]
**Query/Question**
My team is being fairly dependent on this new package, and it not being in maven central is a real blocker for us. Is there any timeline for when it will be released and published to maven central? 

***Why is this not a Bug or a feature Request?***
Because it's a question. 

**Setup (please complete the following information if applicable):**
 - IDE : [e.g. IntelliJ]
 - Version of the Library used
 
 **Information Checklist**
 Kindly make sure that you have added all the following information above and checkoff the required fields otherwise we will treat the issuer as an incomplete report
- [x] Query Added
- [x] Setup information Added

**Comment by yiliuTo** [comment]
Hi @cccs-cat001, we have a plan to perform a release this month, but the concrete time line is still uncertain because we need to wait for another two service team in this repo to release first.

**Comment by yiliuTo** [comment]
Hi @cccs-cat001 , `azure-spring-boot-starter-active-directory` 3.0.0 has been released now, here is the [maven link](https://mvnrepository.com/artifact/com.azure.spring/azure-spring-boot-starter-active-directory/3.0.0).
