### ISSUE TITLE
Use new aad implementation

### ISSUE THREAD

**Issue by chenrujun** [Azure/azure-sdk-for-java#17972]
- Use `AzureActiveDirectoryConfiguration` instead of `AADOAuth2AutoConfiguration` in spring.factories.
 - Deprecate property item like `properties.getUserGroup().getValue()`.
 - Update README.

**Comment by saragluna** [comment]
I believe these features are implemented already, are we okay to close this issue now?

**Comment by chenrujun** [comment]
@saragluna , yes, I'm closing this issue.
