### ISSUE TITLE
[BUG] DataLake directory sas generating wrong signature

### ISSUE THREAD

**Issue by QuickNS** [Azure/azure-sdk-for-java#17973]
Generating a sas token for a DataLake Gen2 directory creates an invalid signature.

Using this code:

```
public StorageDto getSasToken(String folder) {

    // get config values
    StorageSharedKeyCredential credential = StorageSharedKeyCredential.fromConnectionString(storageProperties.getConnectionstring());
    String accountName = storageProperties.getAccountName();
    String containerName = storageProperties.getContainerName();
    String filesystemPath = String.format("https://%s.dfs.core.windows.net/%s/", accountName, containerName); 
    String endpoint = filesystemPath + folder;
    
    // create the DataLakeDirectoryClient
    DataLakeDirectoryClient directoryClient = new DataLakePathClientBuilder()
     .endpoint(endpoint)
     .credential(credential)
     .buildDirectoryClient();
  
    // set expiration: 1d, permission: read, write, list
    OffsetDateTime expiryTime = OffsetDateTime.now().plusDays(1);
    PathSasPermission pathPermission = new PathSasPermission().setListPermission(true).setWritePermission(true).setReadPermission(true);
    DataLakeServiceSasSignatureValues signature = new DataLakeServiceSasSignatureValues(expiryTime, pathPermission).setStartTime(OffsetDateTime.now());

    // generate SAS Token
    String sasToken = directoryClient.generateSas(signature);

    StorageDto response = new StorageDto(filesystemPath, sasToken);

    return response;
  }

```
generates the following SAS Uri:
https://***.dfs.core.windows.net/ingestion-test/a709b091-b657-473d-8024-4a5b97aec20b/2020/12/4/?sv=2020-02-10&se=2020-12-05T01%3A37%3A29Z&sr=d&sp=rwl&sdd=4&sig=VhgwjxEhOBbzENbBfTH%2Fsn%2Bus%2B7Y08AJtjT0vO4pX%2Fs%3D

where "Ingestion-test" is the container name
and "a709b091-b657-473d-8024-4a5b97aec20b/2020/12/4" is the folder name.

When using azcopy 
`azcopy cp .\README.md "https://shopchainmanualdatalake.dfs.core.windows.net/ingestion-test/a709b091-b657-473d-8024-4a5b97aec20b/2020/12/4/?sv=2020-02-10&se=2020-12-05T01%3A37%3A29Z&sr=d&sp=rwl&sdd=4&sig=XXXXXX"
`

I get the following information:
===== RESPONSE ERROR (ServiceCode=AuthenticationFailed) =====
Description=403 Server failed to authenticate the request. Make sure the value of Authorization header is formed correctly including the signature., Details: (none)

Using the .NET code in this doc: https://docs.microsoft.com/en-us/azure/storage/blobs/sas-service-create?tabs=dotnet#create-a-service-sas-for-a-directory  I get a very similar token (only the signature is different):

https://***.dfs.core.windows.net/ingestion-test/a709b091-b657-473d-8024-4a5b97aec20b/2020/12/4?sv=2020-02-10&se=2020-12-04T03%3A12%3A32Z&sr=d&sp=rwl&sdd=4&sig=P%2BFc9vVVX6t1odOzx1OHj%2F3cQqwgAih9UhBLV%2BlRtPY%3D

This one works on AzCopy as expected.

Expectation:
To create a valid SAS token

**Information Checklist**
Kindly make sure that you have added all the following information above and checkoff the required fields otherwise we will treat the issuer as an incomplete report
- [X] Bug Description Added
- [X] Repro Steps Added
- [X] Setup information Added

**Comment by QuickNS** [comment]
Found out that the issue only occurs when trying to generate SAS for a folder or file inside a folder.

If I change the "folder" parameter to be something like "test.txt" it works, I get the issue if I do "test/test,txt"
Starting to think this is related to encoding of the path. I tried passing in the URLEncoder.encode result, but I get the same issue

**Comment by QuickNS** [comment]
Found out the issue only happens when we try to generate a sas for a file inside a folder.

```
public StorageDto getSasToken() {
  try {
      // get config values
      StorageSharedKeyCredential credential = StorageSharedKeyCredential
          .fromConnectionString(storageProperties.getConnectionstring());
      String accountName = storageProperties.getAccountName();
      String containerName = storageProperties.getContainerName();
      
      String accountUrl = String.format("https://%s.dfs.core.windows.net", accountName);

      //this one works
      //String path = URLEncoder.encode("test.txt", "UTF-8");
      //this one doesn't
      String path = URLEncoder.encode("test/test.txt", "UTF-8");

      // create the DataLakeDirectoryClient
      DataLakeDirectoryClient directoryClient = new DataLakePathClientBuilder()
        .endpoint(accountUrl)
        .credential(credential)
        .fileSystemName(containerName)
        .pathName(path)
        .buildDirectoryClient();

      // set expiration: 1h, permission: read, write, list
      OffsetDateTime expiryTime = OffsetDateTime.now().plusDays(1);
      PathSasPermission pathPermission = new PathSasPermission().setListPermission(true).setWritePermission(true)
          .setReadPermission(true);
      DataLakeServiceSasSignatureValues signature = new DataLakeServiceSasSignatureValues(expiryTime, pathPermission)
          .setStartTime(OffsetDateTime.now());

      // generate SAS Token
      String sasToken = directoryClient.generateSas(signature);

      StorageDto response = new StorageDto(directoryClient.getDirectoryUrl(), sasToken);

      return response;

    } catch (Exception ex) {
      return null;
    }
  }
```

It works when I generate a sas for "test.txt", the signature is considered invalid if I generate the sas for "test/test.txt"

**Comment by rickle-msft** [comment]
@gapra-msft Can you please take a look at this one?

**Comment by gapra-msft** [comment]
@QuickNS,

Thank you for reporting this issue. I will investigate and get back to you.

**Comment by gapra-msft** [comment]
@QuickNS 

I just noticed that you are using a DirectoryClient to point to a file, Could you use DatalakeFileClient instead and try generating a SAS off that? If you don't use a DatalakeFileClient, we can't distinguish between a subdirectory and a file.

**Comment by gapra-msft** [comment]
If you still get the error, could you please provide the String to Sign generated by Java and .NET? You can do this by walking down the generateSas stack and placing a breakpoint where the stringToSign method is called.

**Comment by gapra-msft** [comment]
@QuickNS It looks like you accidentally pasted the whole SAS token without erasing the signature. Just wanted to point that out so you can roll your creds.

**Comment by amishra-dev** [comment]
please reactivate if you are still hitting this issue.
