### ISSUE TITLE
[FEATURE REQ] EventHub - Enable Timeout at PartitionProcessor level

### ISSUE THREAD

**Issue by vimorra** [Azure/azure-sdk-for-java#17983]
**Is your feature request related to a problem? Please describe.**
During our deployment we face an exception for which for a specific partition, the Processor Client stop to process further events, we discover the issue only after the IdleTimeoutException. Indeed only after the IdleTiemout a new ProcessorClient was able to consume again events from the partition.
In our issue we was not able to consume messages for more than 30min
In our solution we have 512 Partitions and in avg 64 Consumers and only one Consumer Group. Events are consumed not in bact, prefecth is the default, also all the timeout and retry are configured by default.

"12/3/2020, 1:26:16.286 AM","[2020-12-03 01:26:16,285][single-1][DEBUG][com.azure.core.amqp.implementation.handler.ReceiveLinkHandler]: onDelivery connectionId[MF_6f7c61_1606906971985], entityPath[activity-stream/ConsumerGroups/sdk-etl-filter/Partitions/444], linkName[444_9fe88d_1606906971986], updatedLinkCredit[0],remoteCredit[0], remoteCondition[Error{condition=null, description='null', info=null}], delivery.isPartial[false] (ClientLogger.java:332) ",36ff092413713adc92bf82ef403c047423660b429a559c06a3bcd9d49e9f6f3a
"12/3/2020, 1:56:16.241 AM","[2020-12-03 01:56:16,241][single-1][ INFO][com.azure.core.amqp.implementation.ReactorSession]: linkName[444_9fe88d_1606906971986] entityPath[activity-stream/ConsumerGroups/sdk-etl-filter/Partitions/444]: Error occurred. Removing receive link. (ClientLogger.java:335) ",36ff092413713adc92bf82ef403c047423660b429a559c06a3bcd9d49e9f6f3a
"12/3/2020, 1:56:16.241 AM","[2020-12-03 01:56:16,241][single-1][ INFO][com.azure.core.amqp.implementation.ReactorSession]: linkName[444_9fe88d_1606906971986] entityPath[activity-stream/ConsumerGroups/sdk-etl-filter/Partitions/444]: Error occurred. Removing receive link. (ClientLogger.java:335) ",36ff092413713adc92bf82ef403c047423660b429a559c06a3bcd9d49e9f6f3a
"12/3/2020, 1:56:16.241 AM","[2020-12-03 01:56:16,241][single-1][ INFO][com.azure.core.amqp.implementation.ReactorSession]: linkName[444_9fe88d_1606906971986] entityPath[activity-stream/ConsumerGroups/sdk-etl-filter/Partitions/444]: Error occurred. Removing receive link. (ClientLogger.java:335) ",36ff092413713adc92bf82ef403c047423660b429a559c06a3bcd9d49e9f6f3a
"12/3/2020, 1:56:16.242 AM","[2020-12-03 01:56:16,242][single-1][ WARN][com.azure.messaging.eventhubs.implementation.AmqpReceiveLinkProcessor]: linkName[444_9fe88d_1606906971986] entityPath[activity-stream/ConsumerGroups/sdk-etl-filter/Partitions/444]. Error occurred in link. (ClientLogger.java:341) ",36ff092413713adc92bf82ef403c047423660b429a559c06a3bcd9d49e9f6f3a
"12/3/2020, 1:56:16.242 AM","[2020-12-03 01:56:16,242][single-1][ WARN][com.azure.messaging.eventhubs.implementation.AmqpReceiveLinkProcessor]: linkName[444_9fe88d_1606906971986] entityPath[activity-stream/ConsumerGroups/sdk-etl-filter/Partitions/444]. Error occurred in link. (ClientLogger.java:341) ",36ff092413713adc92bf82ef403c047423660b429a559c06a3bcd9d49e9f6f3a
"12/3/2020, 2:03:49.461 AM","[2020-12-03 02:03:49,461][single-1][ INFO][com.azure.core.amqp.implementation.ReactorSession]: linkName[444_8f038b_1606961027859] entityPath[activity-stream/ConsumerGroups/sdk-etl-filter/Partitions/444]: Returning existing receive link. (ClientLogger.java:335) ",187ee714eaf820dce9ae8c6820383f46dd2395621eacad18fc875a6cc7d0337c
"12/3/2020, 2:03:49.461 AM","[2020-12-03 02:03:49,461][single-1][ INFO][com.azure.core.amqp.implementation.ReactorSession]: linkName[444_8f038b_1606961027859] entityPath[activity-stream/ConsumerGroups/sdk-etl-filter/Partitions/444]: Returning existing receive link. (ClientLogger.java:335) ",187ee714eaf820dce9ae8c6820383f46dd2395621eacad18fc875a6cc7d0337c
"12/3/2020, 2:03:49.461 AM","[2020-12-03 02:03:49,461][single-1][ INFO][com.azure.core.amqp.implementation.ReactorSession]: linkName[444_8f038b_1606961027859] entityPath[activity-stream/ConsumerGroups/sdk-etl-filter/Partitions/444]: Returning existing receive link. (ClientLogger.java:335) ",187ee714eaf820dce9ae8c6820383f46dd2395621eacad18fc875a6cc7d0337c

**Describe the solution you'd like**
We want to enable a Timeout mechanism and related excpetion, that can be configured at PartitionProcessor level, in this case developers can manage properly unexpceted elaboration time, indeed avoid business impacts related to partition events not consumed in the proper time window

**Describe alternatives you've considered**
The alternative is to implement this timeout mechanism at application level. Or configure the IdleTimeout, but seems not possible with the current version.

**Information Checklist**
Kindly make sure that you have added all the following information above and checkoff the required fields otherwise we will treat the issuer as an incomplete report
- [X] Description Added
- [ X] Expected solution specified

**Comment by conniey** [comment]
One workaround could be to use processEventBatch(Consumer, int, Duration) when creating your EventProcessorClient, it'll call your handler every maxWaitTime, and it could tell you if your partition consumer is down if there are consistently no events in that callback.

Another would be to decrease the: partitionOwnershipExpirationInterval
