### ISSUE TITLE
Try to optimize sync query calls 

### ISSUE THREAD

**Issue by mbhaskar** [Azure/azure-sdk-for-java#18003]
Currently sync query calls buffer/make more calls to the service even when we are requesting a single page. This could be due to the way reactor buffers. Try to see if we can optimize this and make sure we dont make additional calls when we are requesting a single page.

**Comment by hellojxg** [comment]
Hi Team, as communicated, in customer's tests the async client seems still having bufferred pages (2-3 requests found in diagnostics log for single query in the code) even with QueryRequestOptions::setMaxBufferedItemCount(1) parameter.
Please help to investigate the problem together with the sync client. Thank you.

**Comment by kushagraThapar** [comment]
This is done.
