### ISSUE TITLE
NIO File system creation in the README is not working

### ISSUE THREAD

**Issue by pditommaso** [Azure/azure-sdk-for-java#18000]
**Describe the bug**

The Azure File system creation example via API in the NIO project [README](https://github.com/Azure/azure-sdk-for-java/tree/master/sdk/storage/azure-storage-blob-nio#create-a-filesystem) throws an error. 

***Exception or Stack Trace***

```
java.lang.IllegalArgumentException: There was an error parsing the configurations map. Please ensure all fields are set to a legal value of the correct type.

	at com.azure.storage.blob.nio.AzureFileSystem.<init>(AzureFileSystem.java:180)
	at com.azure.storage.blob.nio.AzureFileSystemProvider.newFileSystem(AzureFileSystemProvider.java:206)
	at java.nio.file.FileSystems.newFileSystem(FileSystems.java:326)
	at java.nio.file.FileSystems.newFileSystem(FileSystems.java:276)
```

**To Reproduce**

Use the linked above.  

***Code Snippet***

```
Map<String, Object> config = new HashMap<>();
String[] stores = {"<your_container_name", "another_container_name"}; // Any iterable is acceptable
config.put(AzureFileSystem.AZURE_STORAGE_ACCOUNT_KEY, "<your_account_key>");
config.put(AzureFileSystem.AZURE_STORAGE_FILE_STORES, stores);
FileSystem myFs = FileSystems.newFileSystem(new URI("azb://?account=<your_account_name"), config);
```

**Expected behavior**

It's was expected to create the file system object. I've managed to have it working replacing the `stores` array with just a String eg 

```
String stores = "your_container_name"
```

Not sure it the error is in the example or it's a code bug. 

**Setup (please complete the following information):**
 - OS: MacOS
 - IDE : IntelliJ
 - Version of the Library used: `com.azure:azure-storage-blob-nio:12.0.0-beta.2` 

**Additional context**

**Information Checklist**
Kindly make sure that you have added all the following information above and checkoff the required fields otherwise we will treat the issuer as an incomplete report
- [x] Bug Description Added
- [x] Repro Steps Added
- [x] Setup information Added

**Comment by gapra-msft** [comment]
@rickle-msft Could you take a look at this?

**Comment by rickle-msft** [comment]
@pditommaso Thank you for reporting this. I think the code and docs just got out of sync as we iterated on this a bit. The code is written such that it expects a comma separated list of container names rather than an array of Strings. Unless you feel strongly that it should be otherwise, I'll update the readme to match the code for now.

**Comment by pditommaso** [comment]
I was suspecting that. A comma-separated list of container names it's more than fine. Thanks!
