### ISSUE TITLE
[QUERY] How to set ParallelTransferOptions to improve performance.

### ISSUE THREAD

**Issue by yangchengs** [Azure/azure-sdk-for-java#18012]
**Query/Question**

I used the sample code below to compare the performance of upload with ParallelTransferOptions or not.
I used file size 10MB 100MB 1000MB but I don't see much difference of the elapsed times measured. Can anybody suggest how to set the file size/block size/maxConcurrency so that I can see the difference of performances.

        PathHttpHeaders headers = new PathHttpHeaders()
        	     .setContentMd5("data".getBytes(StandardCharsets.UTF_8))
        	     .setContentLanguage("en-US")
        	     .setContentType("binary");
        	 
        Map<String, String> metadata = Collections.singletonMap("metadata", "value");
        
        long blockSize = 1024 * 1024;
        int maxConcurrency = 10;
        ParallelTransferOptions parallelTransferOptions = new ParallelTransferOptions()
            .setBlockSizeLong(blockSize)
            .setMaxConcurrency(maxConcurrency);
        
        /*
         * Generate random things to uploadFile, which makes the file with size of 100MB.
         */
        long fileSize = 10 * 1024 * 1024L;
        System.out.println("create large file");
        createTempFileWithFileSize(largeFile, fileSize);

        /*
         * Upload the large file to storage file.
         */
        
        long start = System.currentTimeMillis();
        System.out.println(start);
        
        //fileClient.uploadFromFile(largeFile.getPath(), parallelTransferOptions, headers, metadata, null, null);
        
        fileClient.uploadFromFile(largeFile.getPath());
        
        long end = System.currentTimeMillis();
        System.out.println(end);
        
        System.out.println(end - start);

***Why is this not a Bug or a feature Request?***
This is a question about how to use parameter ParallelTransferOptions.

**Setup (please complete the following information if applicable):**
 - OS: Windows
 - IDE : Eclipse
 - Version of the Library used  
azure-storage-file-datalake 12.3.0
 
 **Information Checklist**
 Kindly make sure that you have added all the following information above and checkoff the required fields otherwise we will treat the issuer as an incomplete report
- [ ] Query Added
- [ ] Setup information Added

**Comment by rickle-msft** [comment]
Hi, @yangchengs. Thank you for your question. Performance tuning is a difficult question that is highly dependent on your environment. The resources on your machine, the traffic on your network, and a variety of other factors all play a role. We cannot therefore give universally applicable guidance and can only offer general suggestions and tips, else we would have simply picked the most performant values for you. The bulk of the work will be for you to assess your own setup and implement some performance/load tests to experiment with different configurations as sometimes the difference will only be seen at scale and load. We can, however, answer specific questions about how certain options will affect the behavior and request pattern of the sdk that you can use to inform your testing. If you have any such specific questions, please do let us know.

**Comment by gapra-msft** [comment]
Closing as the question has been answered. Please feel free to re-open/open a new issue in case you have any other issues and we'd be happy to help!
