### ISSUE TITLE
[FEATURE REQ] Add support for newByteChannel operation to AzureFileSystemProvider [NIO]

### ISSUE THREAD

**Issue by pditommaso** [Azure/azure-sdk-for-java#18043]
**Is your feature request related to a problem? Please describe.**

The goal of this request is to add the support for `newByteChannel` operation to the `AzureFileSystemProvider` which is currently not supported 

https://github.com/Azure/azure-sdk-for-java/blob/master/sdk/storage/azure-storage-blob-nio/src/main/java/com/azure/storage/blob/nio/AzureFileSystemProvider.java#L269-L272

This causes the `Files.createFile` API  to fails since it depends on it: 

```
    public static Path createFile(Path path, FileAttribute<?>... attrs)
        throws IOException
    {
        EnumSet<StandardOpenOption> options =
            EnumSet.<StandardOpenOption>of(StandardOpenOption.CREATE_NEW, StandardOpenOption.WRITE);
        newByteChannel(path, options, attrs).close();
        return path;
    }
```

**Describe the solution you'd like**

This API is challenging to be supported since it expected to return a `SeekableByteChannel` object which does not fit well the blob model. However instead of hard breaking the support for this method. It could be provided a partial implementation that accommodates requests that do not require to seek the target object using an adapter `SeekableByteChannel` that only rejects specific operations. I'm including the reference to an implementation of a different provider that can be used as an example 

https://github.com/nextflow-io/nextflow/blob/f65296be18a82ecbdddffc71f2c8909203cc4033/modules/nf-httpfs/src/main/nextflow/file/http/XFileSystemProvider.groovy#L146-L214

**Describe alternatives you've considered**

none 

**Additional context**

none 

**Information Checklist**
Kindly make sure that you have added all the following information above and checkoff the required fields otherwise we will treat the issuer as an incomplete report
- [x] Description Added
- [x] Expected solution specified

**Comment by rickle-msft** [comment]
Thanks, @pditommaso. Yea this one will be a little trickier and require some thought on how to support it safely. One thing I noticed is it looks like it just opens and closes a byte channel just as some sort of check, I guess, so I could do a quicker patch that just doesn't throw to allow this method to succeed while we work on adding actual support. Not sure if I love that idea but it came to mind

**Comment by rickle-msft** [comment]
@pditommaso I'm working on this now. Question about it: it looks like the implementation of createFile sets the WRITE option when opening a channel, and it also looks like the implementation you shared throws if WRITE is passed. Can you clarify a little bit about what is going on and what the expectations are? Perhaps I am misunderstanding something

**Comment by pditommaso** [comment]
Sure. The I've linked above was just an example. Don't consider it a reference. The expectation is to have `newByteChannel` not throwing an exception with basic read-only / write-only stream operation. 

The key point is that the provider `newByteChannel` is invoked by FileSystemProvider either by 


```
    public InputStream newInputStream(Path path, OpenOption... options)
        throws IOException
    {
        if (options.length > 0) {
            for (OpenOption opt: options) {
                // All OpenOption values except for APPEND and WRITE are allowed
                if (opt == StandardOpenOption.APPEND ||
                    opt == StandardOpenOption.WRITE)
                    throw new UnsupportedOperationException("'" + opt + "' not allowed");
            }
        }
        ReadableByteChannel rbc = Files.newByteChannel(path, options);
        if (rbc instanceof FileChannelImpl) {
            ((FileChannelImpl) rbc).setUninterruptible();
        }
        return Channels.newInputStream(rbc);
    }

```

and 

```
    public OutputStream newOutputStream(Path path, OpenOption... options)
        throws IOException
    {
        int len = options.length;
        Set<OpenOption> opts ;
        if (len == 0) {
            opts = DEFAULT_OPEN_OPTIONS;
        } else {
            opts = new HashSet<>();
            for (OpenOption opt: options) {
                if (opt == StandardOpenOption.READ)
                    throw new IllegalArgumentException("READ not allowed");
                opts.add(opt);
            }
            opts.add(StandardOpenOption.WRITE);
        }
        WritableByteChannel wbc = newByteChannel(path, opts);
        if (wbc instanceof FileChannelImpl) {
            ((FileChannelImpl) wbc).setUninterruptible();
        }
        return Channels.newOutputStream(wbc);
    }
```

You can reference the above implementation for the minimal expected options
