### ISSUE TITLE
[FEATURE REQ] Support fileKey attribute [NIO]

### ISSUE THREAD

**Issue by pditommaso** [Azure/azure-sdk-for-java#18042]
**Is your feature request related to a problem? Please describe.**

The current implementation of `AzureBasicFileAttributes` and `AzureBlobFileAttributeView` do not support the `fileKey` attribute. See 

https://github.com/Azure/azure-sdk-for-java/blob/master/sdk/storage/azure-storage-blob-nio/src/main/java/com/azure/storage/blob/nio/AzureBasicFileAttributeView.java#L63-L65
 
and

https://github.com/Azure/azure-sdk-for-java/blob/master/sdk/storage/azure-storage-blob-nio/src/main/java/com/azure/storage/blob/nio/AzureBlobFileAttributes.java#L328-L330

However, this API is used eagerly by FileWalker mechanism, making it impossible to traverse directory when using Azure paths 

https://github.com/JetBrains/jdk8u_jdk/blob/master/src/share/classes/java/nio/file/FileTreeWalker.java#L292
https://github.com/JetBrains/jdk8u_jdk/blob/master/src/share/classes/java/nio/file/FileTreeWalker.java#L310

**Describe the solution you'd like**

It would be enough to support this attribute using the blob absolute path as the returned key, in alternative a consistent hash key could be computed using the same. 

**Describe alternatives you've considered**

none

**Additional context**

**Information Checklist**
Kindly make sure that you have added all the following information above and checkoff the required fields otherwise we will treat the issuer as an incomplete report
- [x] Description Added
- [x] Expected solution specified

**Comment by rickle-msft** [comment]
Thanks, @pditommaso. Working on some of the other requests firsts, but wanted to ack this.
