### ISSUE TITLE
Having a Issue with deploying Web App Service Using deployment template

### ISSUE THREAD

**Issue by sachindragh** [Azure/azure-sdk-for-java#1804]
I'm using the Azure SDK version 1.0.0-beta2. I'm using the below template to deploy an App Service Plan and a HTML5 Web App Service.

[Template.txt](https://github.com/Azure/azure-sdk-for-java/files/1121801/Template.txt)

Using the following code segment I'm deploying the resources.

```
Azure azure = AzureAuthProvider.authenticate(azureIdentifier);
String deploymentName = azureAppService.getAppServiceName() + resourceGroupName;
String templateJsonCore = TemplateReader.getAppServiceTemplate(azureAppService);
azure.deployments().define(deploymentName)
                .withExistingResourceGroup(resourceGroupName)
                .withTemplate(templateJsonCore)
                .withParameters("{}")
                .withMode(DeploymentMode.INCREMENTAL)
                .create();
```

After execution only the App Service Plan is created. HTML 5 Web App service deployment failed indicating that it cannot locate the specified App Service Plan which is already created. 

Same template successfully deployed both services when I tried to deploy via the Azure Portal using the template.

If anyone have an idea about this please respond.

**Comment by jianghaolu** [comment]
Just a quick ask about your template - seems like your site should depend on the app service plan?

**Comment by sachindragh** [comment]
@jianghaolu Yes. The site depends on the App Service Plan. But App Service Plan is getting deployed correctly. Problem is during the Site deployment, it can't find the App Service Plan.

**Comment by jianghaolu** [comment]
@sachindragh But in your template I don't see the app service plan in site's "dependOn" list.

**Comment by martinsawicki** [comment]
the guidance to fix the template has been provided so closing. 
If it looks like there is still an issue with the SDK itself, pls reopen.
