### ISSUE TITLE
[FEATURE REQ] Spring cloud stream servicebus topic binder example should use functional bindings

### ISSUE THREAD

**Issue by abrockman** [Azure/azure-sdk-for-java#18050]
**Is your feature request related to a problem? Please describe.**
The examples and documentation describing the configuration of the Azure Stream Binder for Service
Bus uses the legacy annotation-based configuration over the latest functional approach provided
by spring cloud stream. 

**Describe the solution you'd like**
The documentation and examples should be updated to reflect the advised configuration recommended by spring cloud stream:

- [Primary documentation](https://docs.microsoft.com/en-us/azure/developer/java/spring-framework/configure-spring-cloud-stream-binder-java-app-with-service-bus)
- [Example](https://github.com/Azure/azure-sdk-for-java/tree/master/sdk/spring/azure-spring-boot-samples/azure-spring-cloud-sample-servicebus-topic-binder)

[Old way](https://docs.spring.io/spring-cloud-stream/docs/3.0.10.RELEASE/reference/html/spring-cloud-stream.html#_annotation_based_binding_names_legacy) vs the [new way](https://docs.spring.io/spring-cloud-stream/docs/3.0.10.RELEASE/reference/html/spring-cloud-stream.html#_functional_binding_names)

**Describe alternatives you've considered**
N/A - documentation should be in sync with Spring Cloud Stream. 

**Additional context**
We recently utilised the topic binder with spring cloud stream and service bus for the first time. It would greatly improve the ease of use to have the documentation inline with the spring documentation. 

**Information Checklist**
Kindly make sure that you have added all the following information above and checkoff the required fields otherwise we will treat the issuer as an incomplete report
- [x] Description Added
- [x] Expected solution specified

**Comment by saragluna** [comment]
@abrockman yes, that's exactly our plan to change the sample from annotation based to functional.

**Comment by abrockman** [comment]
Would you be happy to accept a pull request for this if I make the changes to the existing example(s)?

**Comment by saragluna** [comment]
@abrockman Absolutely! But just FYI, I am now working on a PR to refactor the spring cloud samples too, https://github.com/Azure/azure-sdk-for-java/pull/17119. I upgraded the underlying management sdk, refactored the README files, converted application.properties to yaml files, and split the properties into different spring profiles. I'm testing them in different Azure environment and almost done. You could go ahead to create the PR directly or make the changes based on my PR, whichever you prefer.

**Comment by bilak** [comment]
@saragluna any update on this? I'm asking about this [long time](https://github.com/MicrosoftDocs/azure-dev-docs/issues/284).

@abrockman were you able to configure this? Can you share some example please?

**Comment by saragluna** [comment]
@bilak thanks for reaching out. We were focusing on implementing our new AAD features in the last several months and we will include updating this in our plan. Please expect some delays on the PR and stay tuned. In the meanwhile, PR is welcome.

**Comment by abrockman** [comment]
@bilak I have started putting together an example. This is a WIP and I have not verified it is working correctly yet - https://github.com/abrockman/azure-sdk-for-java/commit/9003dbc550d9f4f5977912d47613b4cef1a5227d

(attempting to) contribute to this project is very new to me so just trying to navigate modifying these examples and figuring out how to get them running!

**Comment by saragluna** [comment]
Hey guys, we started applying the functional programming model on our Spring Cloud Stream samples, and here's our first PR https://github.com/Azure/azure-sdk-for-java/pull/18800, which has been approved today. We will continue to change the remaining samples in the next a few PRs. Let's know if you have any questions about the change.

**Comment by saragluna** [comment]
FYI https://github.com/Azure/azure-sdk-for-java/pull/18875 another PR merged.

**Comment by saragluna** [comment]
https://github.com/Azure/azure-sdk-for-java/pull/18926

**Comment by yiliuTo** [comment]
Closing this issure because the PR has been merged.
