### ISSUE TITLE
Consider exposing access to current environment via manager.restClient.environment

### ISSUE THREAD

**Issue by anuchandy** [Azure/azure-sdk-for-java#1808]
See this PR https://github.com/Azure/azure-sdk-for-net/pull/3465/commits/28e63adba92d9c769dce2ea562bed85e609554b0

**Comment by praries880** [comment]
@anuchandy  has this issue been fixed or is it still relevant?

**Comment by anuchandy** [comment]
With track2 mgmt SDK in progress, the RestClient no longer exists. I opened this to get hold on env for an internal implementation. Closing this.
