### ISSUE TITLE
[QUESTION] Request unit (RUs) charge mismatch using Azure Portal vs MongoDB Java Driver 

### ISSUE THREAD

**Issue by vzhemevko** [Azure/azure-sdk-for-java#18084]
**Question**

According to the following [documentation ](https://docs.microsoft.com/en-us/azure/cosmos-db/find-request-unit-charge-mongodb) to find out the RUs for operations executed in Azure Cosmos DB API for MongoDB you can use Azure Portal or MongoDB Java Driver. However, we are seeing a mismatch in the request statistics. 

For instance: 

Operation: db['collection-name'].find({"name": "some name", "state": "some state"}) 

Azure Portal gives results: 950.18 RUs

Mongo DB Java Driver: 642.09 RUs

What should be the source of truth in this case? 
Perhaps, there are other factors that should be taken into account? 

We expect that Mongo DB Java Driver returns correct values since we are using it in the application. Then, why there is this mismatch with the Azure Portal?

**Comment by kushagraThapar** [comment]
@vzhemevko - This repo is for Cosmos db Java SDK SQL API. For MongoDb Java Driver, please [contact support](https://aka.ms/azure-support) if this is impacting your production so a support ticket is created and will ensure the issue is properly prioritized.
