### ISSUE TITLE
[BUG] Cannot update Pre Shared Key in VirtualNetworkGatewayConnection

### ISSUE THREAD

**Issue by ptomala90** [Azure/azure-sdk-for-java#18083]
**Describe the bug**
There are at least two ways to update VirtualNetworkGatewayConnection settings and both of them fail to update PSK. They are not throwing any exception, error, etc.

Sample 1:
com.microsoft.azure.management.network.VirtualNetworkGatewayConnection azureConnection = getAzureConnection(); // get VirtualNetworkGatewayConnection to update
azureConnection.update()
.withSharedKey('NewSharedKey')
.apply(); // update of SharedKey does not work

Sample 2:
com.microsoft.azure.management.Azure azure = getAzure(); // get Azure object

azure.virtualNetworkGateways()
.getByResourceGroup('resoureGroupName', 'vpnGatewayName')
.connections().inner()
.beginCreateOrUpdate('resoureGroupName', 'connectionName',
azureConnection.inner()
.withSharedKey('NewSharedKey') // udpdate of SharedKey does not work
.withIpsecPolicies(Collections.singletonList(newIpSecPolicies))); // update of IpSecPolicies works

***Exception or Stack Trace***
Add the exception log and stack trace if available

**To Reproduce**
1. Create VirtualNetworkGatewayConnection with PSK and IpSecPolicies.
2. Verify if VirtualNetworkGatewayConnection is created with spcified parameters using Azure Portal, Azure CLI or any other tool.
3. Edit VirtualNetworkGatewayConnection created in the first step using any of method provided above.
4. Verify if VirtualNetworkGatewayConnection PSK changed using Azure Portal, Azure CLI or any other tool.

***Code Snippet***
See samples from above.

**Expected behavior**
VirtualNetworkGatewayConnection PSK changed after update.

**Screenshots**

**Setup (please complete the following information):**
 - OS: MacOS
 - IDE : IntelliJ
 - Version of the Library used: Azure SDK for Java version 1.36.3 and 1.38.0. Both with the same results.

**Additional context**

**Information Checklist**
Kindly make sure that you have added all the following information above and checkoff the required fields otherwise we will treat the issuer as an incomplete report
- [x] Bug Description Added
- [x] Repro Steps Added
- [x] Setup information Added

**Comment by joshfree** [comment]
Thanks for filing this github issue, @ptomala90.  Someone from the `Mgmt` team will follow up on the github issue shortly.

**Comment by yungezz** [comment]
hi @xccc-msft could you pls have a look? thanks

**Comment by xccc-msft** [comment]
@ptomala90 Can you please share more about your network/gateway settings if applicable? It would be better if you could capture the request/response/requestId from your end so that we could ask help from service team. Thanks.

**Comment by ptomala90** [comment]
Here are the arm-templates that I exported from Azure. I've only removed subscriptionId.

[vnet-template.txt](https://github.com/Azure/azure-sdk-for-java/files/5688414/vnet-template.txt)
[vpnconn-template.txt](https://github.com/Azure/azure-sdk-for-java/files/5688416/vpnconn-template.txt)
[vpngw-template.txt](https://github.com/Azure/azure-sdk-for-java/files/5688417/vpngw-template.txt)

And here is a fragment from application log:
`2020-12-14 11:53:00,633 [INFO ][RxIoScheduler-8][com.microsoft.azure.management.network.VirtualNetworkGatewayConnections createOrUpdate][] --> PUT https://management.azure.com/subscriptions/SUBSCRIPTION_ID/resourceGroups/cslfd9kuwo-test1-vpn0/providers/Microsoft.Network/connections/cslfd9kuwo-test1-vpn0-cot1g776me?api-version=2019-11-01
2020-12-14 11:53:02,464 [INFO ][RxIoScheduler-8][com.microsoft.azure.management.network.VirtualNetworkGatewayConnections createOrUpdate][] <-- 200  https://management.azure.com/subscriptions/SUBSCRIPTION_ID/resourceGroups/cslfd9kuwo-test1-vpn0/providers/Microsoft.Network/connections/cslfd9kuwo-test1-vpn0-cot1g776me?api-version=2019-11-01 (1830 ms, unknown-length body)
2020-12-14 11:53:02,472 [INFO ][RxIoScheduler-8][com.microsoft.azure.management.network.VirtualNetworkGatewayConnections createOrUpdate (poll)][] --> GET https://management.azure.com/subscriptions/SUBSCRIPTION_ID/providers/Microsoft.Network/locations/westeurope/operations/80130a4a-4b54-4574-a81c-84fc60c6e6d1?api-version=2019-11-01
2020-12-14 11:53:03,087 [INFO ][RxIoScheduler-8][com.microsoft.azure.management.network.VirtualNetworkGatewayConnections createOrUpdate (poll)][] <-- 200  https://management.azure.com/subscriptions/SUBSCRIPTION_ID/providers/Microsoft.Network/locations/westeurope/operations/80130a4a-4b54-4574-a81c-84fc60c6e6d1?api-version=2019-11-01 (614 ms, unknown-length body)
`

**Comment by xccc-msft** [comment]
@ptomala90 Thanks for sharing. Another question is that I notice you used `beginCreateOrUpdate`. Can you please try `createOrUpdate`? The difference is that `beginCreateOrUpdate` just returns the response of which the server accepts the request while `createOrUpdate` returns the response when the operation is completed. It's possible that LRO is still running on the server when you verify via Aure CLI if you use `beginCreateOrUpdate`.

**Comment by ptomala90** [comment]
I've changed that and test it again. Still no luck.
I believe this is similar case to "Sample 1" which is described in the ticket. There is no `applyAsync()` method but it does not matter in that case.

**Comment by xccc-msft** [comment]
@ptomala90 I will try whether I can reproduce from my end.

**Comment by ptomala90** [comment]
@xccc-msft Do you have any luck with reproducing the issue?

**Comment by xccc-msft** [comment]
@ptomala90 Yes, I can reproduce this issue. After investigation, we found it has separate API to [set shared key](https://docs.microsoft.com/en-us/rest/api/network-gateway/virtualnetworkgatewayconnections/setsharedkey). That's the reason it failed to update the key by your samples.

Please try below
```java
gateway.connections().inner().setSharedKey("rg-name",
                "connection-name",
                new ConnectionSharedKeyInner().withValue("NewSharedKey"));
```

**Comment by ptomala90** [comment]
@xccc-msft I can confirm that this workaround works in our solution.
Is this preferred method or we can expect update in SDK in the future?

**Comment by xccc-msft** [comment]
This is the [fix PR](https://github.com/Azure/azure-libraries-for-java/pull/1334). Please feel free to review and share your comments. Thanks.
