### ISSUE TITLE
Queue Metadata

### ISSUE THREAD

**Issue by sharadholani** [Azure/azure-sdk-for-java#1809]
This issue is also related to the version 0.9.0 of the azure service bus client which provides management operation.

Azure Storage Queue provides support store custom Queue Metadata as Key Value pairs ,

In Service Bus , the com.microsoft.windowsazure.services.servicebus.models.QueueInfo (QueueInfo) class , provides an API setUserMetadata .

But this accepts only a String as a parameter.
Am I supposed to send the attributes as a json String ?

Wont it overwrite earlier metadata value ?

The ideal way to store user metadata on the queue should be sending key value pairs. (SQS does that)

Will any such support provided ?

This link -> https://docs.microsoft.com/en-us/azure/service-bus-messaging/service-bus-azure-and-service-bus-queues-compared-contrasted#management-and-operations says that Arbitrary metadata support is not supported by Azure Service Bus.

Could you please clarify ?

**Comment by anuchandy** [comment]
Looking at the [service bus API spec](https://github.com/Azure/azure-rest-api-specs/blob/master/arm-servicebus/2017-04-01/swagger/servicebus.json), i don't see setting queue meta data is supported anymore. @dsouzaarun [From service team] can you please confirm?

**Comment by anuchandy** [comment]
Tagging owner from service team @binzywu

**Comment by sharadholani** [comment]
Any updates on this ? 
We need a way to store some custom metadata on a queue.

**Comment by jfggdl** [comment]
Current support is just for String. The API only supports one single value as a metadata. Once you update the metadata, it is overwritten. As to using a JSON string, that is up to you. You can use other types provided you serialized it into a String. 

We are going to close this issue, but please feel free to open it again if you feel that we have not addressed your concerns.
