### ISSUE TITLE
[BUG] Cosmos default maxConnectionsPerEndpoint is 130, while javadoc says it is 30.

### ISSUE THREAD

**Issue by ldappidydoo** [Azure/azure-sdk-for-java#18094]
The javadoc on directendpoint config says the default maxConnectionsPerEndpoint is 30. Inspecting the source reveals it is actually 130.

private static final int DEFAULT_MAX_CONNECTIONS_PER_ENDPOINT = 130;

similarly, the javadoc for maxRequestsPerConnection says it is 10, when the source says it is actually 30.

aside - any guidelines for tuning these parameters is much appreciated, im currently experience SNAT issues with azure app service, and thinking this is responsible.

**Comment by kushagraThapar** [comment]
@ldappidydoo - please see these troubleshooting guide - https://docs.microsoft.com/en-us/azure/cosmos-db/troubleshoot-java-async-sdk
And performance guides - https://docs.microsoft.com/en-us/azure/cosmos-db/performance-tips-java-sdk-v4-sql?tabs=api-async

for how to fix the SNAT port exhaustion issue. 
I have a PR out there to fix this issue.
