### ISSUE TITLE
Does azure-sdk-for-java have a way to create users and assign permission for SQL database?

### ISSUE THREAD

**Issue by rogertong** [Azure/azure-sdk-for-java#1811]
Does azure-sdk-for-java have a way to create users and assign permission for SQL database?

**Comment by vhvb1989** [comment]
Hello @rogertong

I am sorry about you didn't get a sooner answer on this
Do you still need help on this? Let me know and I would be happy to help.

Note: As part of repository cleaning effort, this issue will be closed by Oct 4 if no response is received from submitter and/or not further action is required.
