### ISSUE TITLE
[BUG] Service Bus: Messages not received when there is more than 60s gap

### ISSUE THREAD

**Issue by alewis001** [Azure/azure-sdk-for-java#18122]
**Describe the bug**
A session-based Message receiver does not receive messages sent after 60s gap from the last message sent.

***Exception or Stack Trace***
No exceptions thrown.
No registered error handlers called.

**To Reproduce**

1. Messages 1 to 5 sent each with 1s between them, the receiver receives all 5 messages.
1. Sender waits 60s or more since the last message sent (message 5).
1. Sender sends message 6.

- At this point, the receiver will not receive message 6 or any others sent after 6.
- If the receiver is restarted, the receiver will receive messages 6 (and any sent after 6).

***Code Snippet***
```
ServiceBusProcessorClient  processorClient = new ServiceBusClientBuilder()
            .connectionString("<< service bus connection string >>")
            .sessionProcessor()
            .queueName("<< queue name >>>")
            .maxConcurrentSessions(1)
            .processMessage(MessageReceiver::processMessage)
            .processError(MessageReceiver::processError)
            .buildProcessorClient();

System.out.println("Starting the processor");
processorClient.start();
```
The `processMessage` method simply prints out message particulars, as per SB SDK sample(s); similarly for the `processError`.

**Expected behavior**
All messages are received regardless of duration between messages.

**Setup (please complete the following information):**
 - OS: MacOS
 - IDE : Netbeans 12.1
 - com.azure:azure-messaging-servicebus:7.0.0

**Comment by alewis001** [comment]
The receiver code is essentially from the following sample but without stoping and restarting the processorClient.

https://github.com/Azure/azure-sdk-for-java/blob/master/sdk/servicebus/azure-messaging-servicebus/src/samples/java/com/azure/messaging/servicebus/ServiceBusSessionProcessorSample.java

**Comment by hemanttanwar** [comment]
@alewis001 Thank you for providing details of this issue. We will look into it and provide you update.

**Comment by alewis001** [comment]
@hemanttanwar Is there any news on this issue please? This bug currently means we cannot use Sessions on Service Bus which I would suggest is a critical bug unless you can suggest what I may be doing wrong? I can provide a sample repo if necessary.

**Comment by hemanttanwar** [comment]
@alewis001 Happy New year. We are working on fixing this and will release the fox in few weeks. I will update exact timing as I know bit more about release.

**Comment by alewis001** [comment]
@hemanttanwar Happy New Year to you also, I hope you and your loved ones are keeping safe and well. Thank you for the update, much appreciated.

**Comment by hemanttanwar** [comment]
@alewis001 This fix is now released . You can download it from here https://search.maven.org/artifact/com.azure/azure-messaging-servicebus .
Closing this issue now.

**Comment by alewis001** [comment]
Thank you @hemanttanwar much appreciated, I'll give that a try ASAP.

**Comment by alewis001** [comment]
I can confirm that this issue is fixed.
