### ISSUE TITLE
Docs should specify what T,U parameters are for

### ISSUE THREAD

**Issue by RickWinter** [Azure/azure-sdk-for-java#18129]
The docs for SyncPoller shows the type has a T, U.  It however does not state what T and U are.
https://docs.microsoft.com/en-us/java/api/com.azure.core.util.polling.syncpoller?view=azure-java-stable

**Comment by alzimmermsft** [comment]
Thank you for filing this issue @RickWinter, looking at the interface in code it does have documentation for the generics, https://github.com/Azure/azure-sdk-for-java/blob/master/sdk/core/azure-core/src/main/java/com/azure/core/util/polling/SyncPoller.java#L24, @scbedd @sima-zhu do you know where this could be getting lost in translation?

**Comment by alzimmermsft** [comment]
This issue appears consistent with [PollerFlux](https://docs.microsoft.com/en-us/java/api/com.azure.core.util.polling.pollerflux?view=azure-java-stable#type-parameters) documentation missing the generics documentation but it existing in [code](https://github.com/Azure/azure-sdk-for-java/blob/master/sdk/core/azure-core/src/main/java/com/azure/core/util/polling/PollerFlux.java#L43).

**Comment by sima-zhu** [comment]
Thanks for reporting this. Will talk to docs team about the missing doc during the API abstraction.

**Comment by sima-zhu** [comment]
Issue filed to docs team. Will keep an eye on this.

**Comment by alzimmermsft** [comment]
@sima-zhu could you link the tracking issue here (if possible). I'm looking to remove `Azure.Core` as a label given this isn't a code issue but an external issue.

**Comment by alzimmermsft** [comment]
Appears this has been resolved and `<T, U>` are now showing their description.
