### ISSUE TITLE
[BUG] Links in Table of Contents for Event Hubs in reference docs dont work

### ISSUE THREAD

**Issue by ramya-rao-a** [Azure/azure-sdk-for-java#18139]
Try clicking on any of the links in the[ Table of Contents for Event Hubs](https://azuresdkdocs.blob.core.windows.net/$web/java/azure-messaging-eventhubs/5.3.1/index.html) in our reference docs. None of them work.

cc @conniey for finding this via #17297

**Comment by kurtzeborn** [comment]
@ramya-rao-a, this seems to work fine for @sima-zhu and I.  We're going to need more info.  What browser were you using?  Anything special about the internet connection (corpnet, proxy, etc)?

**Comment by srnagar** [comment]
@kurtzeborn I think what @ramya-rao-a and @conniey are referring to here is that in the "Table of Contents" section, there are links to different sections of the README that don't work. For e.g. clicking on "Examples" in TOC should take you to the examples section but it's opening a new tab for the same page. The issue is the links are not navigating to the subsections of the page.

**Comment by ramya-rao-a** [comment]
That is right @srnagar, thanks!

@kurtzeborn, @sima-zhu Adding a screenshot here:

![image](https://user-images.githubusercontent.com/16890566/102262104-76f34300-3ec7-11eb-8fb8-9de987fce6c2.png)

**Comment by kurtzeborn** [comment]
Yep, makes sense.  Looking at the source for the page, I see the following (using "Include the package" as an example):
`<li><a href="#include-the-package" target="_blank">Include the package</a></li>`
However, down below in the section, I don't see the corresponding anchor there.  It should look something like this:
`<a id="include-the-package"><h3>Include the package</h3></a>`

**Comment by sima-zhu** [comment]
The docs is generated by Jacoco, and Jacoco reference doc does not read the anchor link very well. @srnagar The doc is generated by maven command. Do you aware any of the settings to make it work? If not, I can search and report an issue to Jacoco

**Comment by srnagar** [comment]
@sima-zhu The [overview page ](https://azuresdkdocs.blob.core.windows.net/$web/java/azure-messaging-eventhubs/5.3.1/index.html) is generated by a python script - `eng/pipelines/scripts/generate_overview_from_readme.py`. This copies the contents of README.md and updates the javadoc index html. So, looks like the issue might be how the script is generating html page from markdown page.

Also, Jacoco is used for reporting code coverage only and shouldn't be impacting javadocs.

**Comment by sima-zhu** [comment]
@srnagar My mistakes. I mean the maven javadoc command. I will double check the python scripts and see if it is the python scripts can handle this.

**Comment by sima-zhu** [comment]
Have the PR to fix all incoming releases. Need to fix all existing readme in blob storage as well.

**Comment by sima-zhu** [comment]
Updated the existing documents. 
Please check the link: https://azuresdkdocs.blob.core.windows.net/$web/java/azure-messaging-eventhubs/5.3.1/index.html

Closed the issue. Please feel free to reopen if you find any unaddressed stuff.

**Comment by ramya-rao-a** [comment]
@sima-zhu Thanks!
Clicking on any of the links in the table of contents now takes us to the right place, but this view occupies the entire page. We no longer see the left TOC for the reference docs for different classes. Can we do anything about htat?

**Comment by sima-zhu** [comment]
@rao

**Comment by sima-zhu** [comment]
Fixed the issue of both toc links were not working and open new tabs when clicking. It is now working as expected. 
Please double check. Closed the issue for now. Please feel free to reopen the tickets if more issues need to address or any follow up issues.

**Comment by ramya-rao-a** [comment]
Fix confirmed. Thanks @sima-zhu!
