### ISSUE TITLE
[QUERY] getRemoteDesktopFile fetch RDP file in 2.1 

### ISSUE THREAD

**Issue by HughDevlin** [Azure/azure-sdk-for-java#18131]
Please help point me toward the doc for the getRemoteDesktopFile equivalent API in 2.1.

Updating a Java app
from  com.microsoft.windowsazure.management (azure-mgmt-compute-1.38.0.jar)
to com.azure.resourcemanager (azure-resourcemanager-compute-2.1.0.jar)

conversion is going very smoothly except for this

1.38 style snippet:

VirtualMachineGetRemoteDesktopFileResponse resp = client
   .getVirtualMachinesOperations()
   .getRemoteDesktopFile(serviceName, deploymentName, agentId);

thank you!

**Comment by HughDevlin** [comment]
ok, I know rdp files are very simple, I know how to get the public IP or fully qualified domain name of a virtual machine, so I can write an rdp file on the fly. Before I write some code I just want to know if I am missing finding something in the docs for the newer api. Thanks.

**Comment by yungezz** [comment]
hi @xccc-msft could you pls help to look at the track2 issue? thanks.

**Comment by xccc-msft** [comment]
@HughDevlin `com.microsoft.windowsazure.management` is not part of `azure-mgmt-compute`. We don't provide API like your shared to get a RDP file. After investigation, here is how Azure PowerShell implement [Get-AzRemoteDesktopFile](https://github.com/Azure/azure-powershell/blob/master/src/Compute/Compute/RemoteDesktop/GetAzureRemoteDesktopFileCommand.cs). You might want to follow this now. We will discuss whether to have this in `azure-resourcemanager-compute` for future plan.

cc: @nickzhums
