### ISSUE TITLE
storageEndpointSuffix is hardcoded in UnmanagedDataDiskImpl thus restricting user to create unmanaged disk in other environment

### ISSUE THREAD

**Issue by rishi-anand** [Azure/azure-sdk-for-java#1813]
Issue: While creating blob uri, storageEndpointSuffix should be taken from environment. But in 'UnmanagedDataDiskImpl.java:214', storageEndpointSuffix is hardcoded as '.blob.core.windows.net'.

Impact: I am not able to create unmanaged disk in US gov region and managed disk is also not supported. So I am unable to launch the virtual machine in US gov region using java sdk 1.1.0

**Comment by anuchandy** [comment]
@rishi-anand we fixed this issue in the PR https://github.com/Azure/azure-sdk-for-java/pull/1759, this will be available in the next release [scheduled for August].

**Comment by rishi-anand** [comment]
Thanks @anuchandy :)

**Comment by anuchandy** [comment]
Fix available as of v1.2 hence closing this.

**Comment by rishi-anand** [comment]
Will this fix will be part of 1.2.0 release?
