### ISSUE TITLE
[FEATURE REQ] Single link that always points to latest version of API reference docs for a package

### ISSUE THREAD

**Issue by ramya-rao-a** [Azure/azure-sdk-for-java#18140]
Currently, https://azuresdkdocs.blob.core.windows.net/$web/java/azure-messaging-eventhubs/5.3.1/index.html is the link to the Java API reference docs for Event Hubs v5.3.1 which needs to be linked from various places. Having to change the link everytime there is a new version of the package is not desirable. Can we have a single link that always points to the latest version?

cc @conniey for finding this via #17297

**Comment by sima-zhu** [comment]
@ramya-rao-a @conniey 

Could you please share where we reference the particular version link?
We actually maintain the [service page](http://azure.github.io/azure-sdk-for-java/eventhubs.html). Is it a better replacement for the specific version link?

**Comment by ramya-rao-a** [comment]
Below are the places
- The[ readme for the package in this repo](https://github.com/Azure/azure-sdk-for-java/blob/master/sdk/eventhubs/azure-messaging-eventhubs/README.md)
- In the [Event Hubs Overview page](https://docs.microsoft.com/en-us/azure/event-hubs/event-hubs-about), in the left TOC click on `References` -> `Java` -> `Client library` -> `azure-messaging-eventhubs (latest)`
- We would also like to add a link in the [Event Hubs Java Ref doc Overview page](https://docs.microsoft.com/en-us/java/api/overview/azure/eventhub?view=azure-java-stable)

**Comment by sima-zhu** [comment]
@ramya-rao-a We actually have the latest link: 
https://azuresdkdocs.blob.core.windows.net/$web/java/azure-messaging-eventhubs/latest/index.html

Every time we release the new version, we are going to update the latest link.

**Comment by ramya-rao-a** [comment]
That `latest` points to the latest preview package at the moment, it should point to the latest GA release instead

**Comment by sima-zhu** [comment]
@ramya-rao-a We currently only support whatever the latest.
However, we can fetch the latest GA version right below, we need some dynamic call to have the link.
https://azuresdkdocs.blob.core.windows.net/$web/java/azure-messaging-eventhubs/versioning/latest-ga

Question: 
1. What if the package only contains preview version?

Two options:
1. Maintain two folders latest-ga and latest-preview.
2. Link to service page which listed latest preview and ga version.

**Comment by ramya-rao-a** [comment]
From a customer's standpoint "latest" should always point to what they can safely use unless the package has only preview versions in which case "latest" should point to the latest preview.

**Comment by weshaggard** [comment]
@ramya-rao-a we should update the latest to point to the latest GA, assuming there is a GA. That can help with some of these scenarios.

However I will add that I know the docs team does not like us linking to our github.io docs from the docs.ms site. They generally want us to link to the docs within the docs.ms site. We should figure out if we should do something about removing those links by the time the readmes reach docs.ms.

**Comment by sima-zhu** [comment]
Updated the latest link to available GA version. If GA does not exist, we will use latest preview.

**Comment by sima-zhu** [comment]
There are several python docs which links the latest full docs link. We cannot simply replace it with redirect links. Will follow the logic of copying the entire versioned doc to latest. 
Only replace when new GA available. If no GA, then replace with preview version.

**Comment by sima-zhu** [comment]
Changes got merged. The latest folder will update for the next release. Will do spot check after next release cycle.

**Comment by sima-zhu** [comment]
Spot check several library. They have updated to latest GA whenever GA is available. Closed this issue for now, feel free to reopen this if anything unaddressed.
