### ISSUE TITLE
The EventHubConsumerClient leak memory.

### ISSUE THREAD

**Issue by joakimosterberg** [Azure/azure-sdk-for-java#18149]
The reason why unconfirmedSends (java.util.concurrent.ConcurrentSkipListMap) continuously increase.

I can see in the heap dump is that there is a memory leakage in the Azure class:
com.azure.core.amqp.implementation.RequestResponseChannel
The class contain a member unconfirmedSends (java.util.concurrent.ConcurrentSkipListMap) the number of entries in the map is 64865.
The retained size 2,206,954,248 so it is where the main part of data is referred.
I can't see how RequestResponseChannel/ConcurrentSkipListMap can be affected from our code?
I think this must be a question to Azure Event Hub support.

You have to run for some time.

Add the code snippet that causes the issue:
    private EventHubConsumerClient          _consumer           = null;

    public void execute() throws DRException {
        AmqpRetryOptions retries = new AmqpRetryOptions();
        retries.setDelay(Duration.ofSeconds(3));
        retries.setMaxDelay(Duration.ofSeconds(5));
      private EventHubConsumerClient          _consumer           = null;   retries.setMaxRetries(3);
        retries.setTryTimeout(Duration.ofSeconds(5));
        retries.setMode(AmqpRetryMode.FIXED);

        if (Boolean.TRUE.equals(_config.getUseOAuth2())) {
            String namespace = _config.getNamespace() + ".servicebus.windows.net";
            String eventhub = _config.getEventHubName();
            try {
                IAuthenticationResult result = acquireToken(_config);
                OffsetDateTime offsetDateTime = result.expiresOnDate().toInstant().atOffset(ZoneOffset.UTC);
                AccessToken accessToken = new AccessToken(result.accessToken(), offsetDateTime);
                _consumer = new EventHubClientBuilder()
                        .credential(namespace, eventhub, request -> Mono.just(accessToken))
                        .consumerGroup(
                                _config.getConsumerGroup().equals("") ?
                                        EventHubClientBuilder.DEFAULT_CONSUMER_GROUP_NAME :
                                        _config.getConsumerGroup())
                        .retry(retries)
                        .shareConnection()
                        .buildConsumerClient();
            } catch (Exception ex) {
                throw new DRException(ex);
            }
        } else {
            _consumer = new EventHubClientBuilder()
                    .connectionString(_config.getConnectionstring())
                    .consumerGroup(
                            _config.getConsumerGroup().equals("") ?
                                    EventHubClientBuilder.DEFAULT_CONSUMER_GROUP_NAME :
                                    _config.getConsumerGroup())
                    .retry(retries)
                    .shareConnection()
                    .buildConsumerClient();
        }

        IterableStream<String> pids = _consumer.getPartitionIds();

        Iterator<String> it = pids.iterator();
        ArrayList<String> l = new ArrayList<>();

        String [] ids = null;
        /*
         * No partition specified ==> collect from all
         */
        if (_config.getPartition().equals("")) {
            while (it.hasNext()) {
                l.add(it.next());
            }
        }
        else {
            boolean found = false;

            while (it.hasNext()) {
                if (it.next().equals(_config.getPartition())) {
                    found = true;
                }
            }

            if (!found) {
                throw new DRException("The partition: "+_config.getPartition()+" not found.");
            }

            l.add(_config.getPartition());
        }

        ids = l.toArray(new String[l.size()]);

        try {
            String res = PersistentSequenceNumberHandler.validateRoot(_agentRootDirectory, ids);

            if (res != null) {
                throw new DRException(res);
            }
        }
        catch (Exception e) {
            throw new DRException("Failed to initialize.", e);
        }

        PartitionExecutor [] executors = new PartitionExecutor[l.size()];

        for (int cnt = 0; cnt < ids.length; cnt++) {
            executors[cnt] = new PartitionExecutor(ids[cnt]);

            try {
                executors[cnt].initialize();
            }
            catch (Exception e) {
                throw new DRException("Failed to initialize.", e);
            }
        }

        try {
            for (PartitionExecutor executor: executors) {
                executor.start();
            }

            while (!_isStopped) {
                try {
                    Thread.sleep(500);
                }
                catch (InterruptedException ie) {}
            }

            for (PartitionExecutor executor: executors) {
                executor.join();
            }

            for (PartitionExecutor executor: executors) {
                if (null != executor.getError()) {
                    throw executor.getError();
                }
            }
        } catch (Exception e) {
            throw new DRException(e);
        }
        finally {
            for (PartitionExecutor executor: executors) {
                executor.close();
            }
        }
    }

   private class PartitionExecutor extends Thread {
        PartitionExecutor(String id) {
            super();
            _id = id;
            setName(_env.getWorkflowName() + "_Azure_"+id);
        }

        private String _id;
        private DRException _theError = null;

        private PersistentSequenceNumberHandler _storage = new PersistentSequenceNumberHandler();

        public DRException getError() {
            return _theError;
        }

        public void initialize() throws Exception {
            _storage.initialize(_agentRootDirectory + "/" + _id);
        }

        public void run() {
            EventPosition nextPosition;
            long initSeqNo = -1;

            String startPos = (_config.getOffsetPosition() == StartPosition.FROM_EARLIEST ?
                    "EARLIEST" : "LATEST");

            if (_useSeqNoStorage) {
                initSeqNo = _storage.getSequenceNr();

                if (initSeqNo != -1) {
                    _env.dispatchMessage("Partition "+_id+" starting sequence number: "+ initSeqNo);

                    PartitionProperties prop = _consumer.getPartitionProperties(_id);
                    long beginning = prop.getBeginningSequenceNumber();
                    long end = prop.getLastEnqueuedSequenceNumber();

                    if (!((beginning <= initSeqNo) && (initSeqNo <= end))) {
                        DRDate ts = new DRDate(_storage.getRecoveredSequenceNrTimeStamp());
                        _theError = new DRException("Saved sequence: " + initSeqNo + " is out of range(" +
                                beginning + " - " + end + "), saved sequence timestamp: "+ts+", partition: "+_id);
                        aThreadIsStoped();
                        return;
                    }
                }
                else {
                    _env.dispatchMessage("Partition "+_id+" starting sequence number: "+startPos);
                }
            } else {
                if (!_messagePrinted.getAndSet(true)) {
                    _env.dispatchMessage("All partition sequence numbers start at " + startPos);
                }
            }

            if (initSeqNo == -1) {
                if (_config.getOffsetPosition() == StartPosition.FROM_EARLIEST) {
                    nextPosition = EventPosition.earliest();
                } else {
                    nextPosition = EventPosition.latest();
                }
            }
            else {
                nextPosition = EventPosition.fromSequenceNumber(initSeqNo, false);
            }

            while (!_isStopped) {
                IterableStream<PartitionEvent> events =
                        _consumer.receiveFromPartition(
                                _id,
                                10,
                                nextPosition,
                                Duration.ofSeconds(2));

                if (_isStopped) break;

                Iterator<PartitionEvent> it = events.iterator();

                Long lastSequenceNumber = -1L;

                while (!_isStopped) {
                    try {
                        if (!it.hasNext() || _isStopped) {
                            break;
                        }
                    } catch (Exception e) {
                        if (!e.getClass().getName().equals("reactor.core.Exceptions$ReactiveException")) {
                            _theError = new DRException("Not reactor exception.", e);
                        }
                        else if (!(e.getMessage().equals("java.lang.InterruptedException"))) {
                            _theError = new DRException("Not interrupted.", e);
                        }

                        aThreadIsStoped();
                        return;
                    }

                    PartitionEvent pe = it.next();

                    EventData ed = pe.getData();

                    try {
                        _router.consume(ed.getBody());
                    }
                    catch (DRException dre) {
                        _theError = dre;
                        aThreadIsStoped();
                        return;
                    }
                    lastSequenceNumber = ed.getSequenceNumber();

                    updateLatestArrival();
                    if (_useSeqNoStorage) {
                        try {
                            _storage.saveSequenceNr(lastSequenceNumber);
                        } catch (Exception e) {
                            _theError = new DRException("Failed to save sequence number. ", e);
                            aThreadIsStoped();
                            return;
                        }
                    }
                }

                if (lastSequenceNumber != -1L) {
                    nextPosition = EventPosition.fromSequenceNumber(lastSequenceNumber, false);
                }
            }
        }

**Comment by joakimosterberg** [comment]
The following exception is found in the unconfirmedSends:
com.azure.core.amqp.exception.AmqpException:
No response received from CBS node. tokenAudience: 'amqp://ledgerfinancialevent-dev-pme-wus-eh.servicebus.windows.net/ledgerfinancialevent/ConsumerGroups/$Default/Partitions/5'. scopes: 'amqp://ledgerfinancialevent-dev-pme-wus-eh.servicebus.windows.net/ledgerfinancialevent/ConsumerGroups/$Default/Partitions/5'

**Comment by joakimosterberg** [comment]
The following method continuously add this exception:
public Mono<OffsetDateTime> authorize(String tokenAudience, String scopes) {
        return this.cbsChannelMono.flatMap((channel) -> {
            return this.credential.getToken((new TokenRequestContext()).addScopes(new String[]{scopes})).flatMap((accessToken) -> {
                Message request = Proton.message();
                Map<String, Object> properties = new HashMap();
                properties.put("operation", "put-token");
                properties.put("expiration", Date.from(accessToken.getExpiresAt().toInstant()));
                properties.put("type", this.authorizationType.getTokenType());
                properties.put("name", tokenAudience);
                ApplicationProperties applicationProperties = new ApplicationProperties(properties);
                request.setApplicationProperties(applicationProperties);
                request.setBody(new AmqpValue(accessToken.getToken()));
                return channel.sendWithAck(request).handle((message, sink) -> {
                    if (RequestResponseUtils.isSuccessful(message)) {
                        sink.next(accessToken.getExpiresAt());
                    } else {
                        String description = RequestResponseUtils.getStatusDescription(message);
                        AmqpResponseCode statusCode = RequestResponseUtils.getStatusCode(message);
                        Exception error = ExceptionUtil.amqpResponseCodeToException(statusCode.getValue(), description, channel.getErrorContext());
                        sink.error(error);
                    }

                }).switchIfEmpty(Mono.error(new AmqpException(true, String.format("No response received from CBS node. tokenAudience: '%s'. scopes: '%s'", tokenAudience, scopes), channel.getErrorContext())));
            });
        });
    }

**Comment by joakimosterberg** [comment]
The following method continuously  create the inserted AmqpException:
public Mono<OffsetDateTime> authorize(String tokenAudience, String scopes);

AmqpException(
   isTransient = true,
   message = "No response received from CBS node. tokenAudience: 'amqp://joakim.servicebus.windows.net/test/ConsumerGroups/nisse/Partitions/0'. scopes: 'amqp://joakim.servicebus.windows.net/test/ConsumerGroups/nisse/Partitions/0'",
   errorContext = NAMESPACE: joakim.servicebus.windows.net, PATH: $cbs, REFERENCE_ID: cbs:receiver, LINK_CREDIT: 0 
   )
   
Why is it created?
How can we handle it?

**Comment by srnagar** [comment]
@jaokimosterberg Can you please let us know which version of the `azure-messaging-eventhubs` library you are using?

**Comment by joakimosterberg** [comment]
Hi!

The following libraries are used:
azure/proton-j-0.33.4.jar
azure/azure-core-amqp-1.6.0.jar
azure/azure-messaging-eventhubs-5.3.0.jar
azure/azure-eventhubs-3.2.2.jar
azure/azure-core-1.9.0.jar
azure/azure-storage-file-datalake-12.1.1.jar
azure/azure-storage-common-12.6.1.jar
azure/azure-identity-1.1.2.jar
azure/azure-storage-blob-12.6.1.jar
azure/azure-core-http-netty-1.5.1.jar
azure/reactor/reactor-core-3.3.5.RELEASE.jar
azure/reactor/reactor-netty-0.9.7.RELEASE.jar
azure/jackson/jackson-dataformat-xml-2.10.1.jar
azure/jackson/jackson-core-2.10.1.jar
azure/jackson/jackson-databind-2.10.1.jar
azure/jackson/jackson-annotations-2.10.1.jar
azure/netty/netty-transport-native-unix-common-4.1.49.Final.jar
azure/netty/netty-transport-native-epoll-4.1.49.Final-linux-x86_64.jar
azure/netty/netty-transport-4.1.49.Final.jar
azure/netty/netty-tcnative-boringssl-static-2.0.29.Final.jar
azure/netty/netty-resolver-4.1.49.Final.jar
azure/jackson/jackson-datatype-jsr310-2.10.1.jar
azure/netty/netty-handler-proxy-4.1.49.Final.jar
azure/netty/netty-handler-4.1.49.Final.jar
azure/netty/netty-common-4.1.49.Final.jar
azure/netty/netty-codec-socks-4.1.49.Final.jar
azure/netty/netty-codec-http-4.1.49.Final.jar
azure/netty/netty-codec-http2-4.1.49.Final.jar
azure/netty/netty-codec-4.1.49.Final.jar
azure/netty/netty-buffer-4.1.49.Final.jar
azure/slf4j/slf4j-api-1.7.28.jar
azure/reactive-streams-1.0.3.jar
azure/msal4j-1.7.0.jar
azure/msal4j-persistence-extension-1.0.0.jar
azure/oauth2-oidc-sdk-6.14.jar
azure/gson-2.8.5.jar
azure/json-smart-2.3.jar
azure/javax.mail-1.6.1.jar
azure/accessors-smart-1.2.jar
azure/nimbus-jose-jwt-8.18.jar
azure/commons-codec-1.11.jar
azure/stax2-api-4.2.jar
azure/commons-io-2.5.jar
jna/jna-3.5.2.jar

**Comment by srnagar** [comment]
@joakimosterberg I tried using the EventHubConsumerClient to reproduce the memory leak issue but after running for a few hours, I couldn't see any memory leak. 

I used `azure-messaging-eventhubs` version 5.3.0 for this sample.

Here's the sample code I used to reproduce. If you can please provide a similar standalone code sample to repro the issue, it will help troubleshoot this issue further.

```java
public class EventHubConsumerMemLeak {

    private static final String EH_CONNECTION_STRING = "<REDACTED>";
    private static final AtomicReference<EventPosition> eventPosition = new AtomicReference<>(EventPosition.earliest());

    public static void main(String[] args) throws IOException {
        EventHubConsumerClient eventHubConsumerClient = new EventHubClientBuilder()
                .connectionString(EH_CONNECTION_STRING)
                .consumerGroup(EventHubClientBuilder.DEFAULT_CONSUMER_GROUP_NAME)
                .buildConsumerClient();

        ScheduledExecutorService scheduledExecutorService = Executors.newSingleThreadScheduledExecutor();
        scheduledExecutorService.scheduleAtFixedRate(() -> run(eventHubConsumerClient), 0, 5, TimeUnit.SECONDS);

        System.in.read();
        scheduledExecutorService.shutdownNow();
        eventHubConsumerClient.close();
    }

    private static void run(EventHubConsumerClient eventHubConsumerClient) {
        System.out.println("Receiving next batch of events");
        IterableStream<PartitionEvent> partitionEvents = eventHubConsumerClient.receiveFromPartition("0", 100,
                eventPosition.get());
        PartitionEvent lastEvent = partitionEvents.stream().reduce((first, second) -> second).orElse(null);

        if (lastEvent != null) {
            System.out.println("Last sequence number " + lastEvent.getData().getSequenceNumber());
            eventPosition.set(EventPosition.fromSequenceNumber(lastEvent.getData().getSequenceNumber()));
        }
    }
}

```

**Comment by srnagar** [comment]
Hi @joakimosterberg, have you had a chance to try the above sample out?

**Comment by joakimosterberg** [comment]
Hi!

The SW is rewritten, using an asynchrounus interface, I think it works better.


Best Regards,
Joakim
________________________________
Från: Srikanta <notifications@github.com>
Skickat: den 25 januari 2021 18:26
Till: Azure/azure-sdk-for-java <azure-sdk-for-java@noreply.github.com>
Kopia: Joakim Österberg <joakim.osterberg@digitalroute.com>; Mention <mention@noreply.github.com>
Ämne: Re: [Azure/azure-sdk-for-java] The EventHubConsumerClient leak memory. (#18149)


Hi @joakimosterberg<https://github.com/joakimosterberg>, have you had a chance to try the above sample out?

**Comment by srnagar** [comment]
Thanks for the update @joakimosterberg. Yes, we also recommend using async client APIs or the EventProcessorClient for receiving events.

Closing this issue.
