### ISSUE TITLE
Reference docs for packages that are no longer in preview should not be listed under the preview moniker

### ISSUE THREAD

**Issue by ramya-rao-a** [Azure/azure-sdk-for-java#18167]
This is the [landing page for Java API reference docs for packages that are in preview](https://docs.microsoft.com/en-us/java/api/overview/azure/?view=azure-java-preview). Many of the these packages have moved out of preview and into GA. These should not appear here anymore. Found as part of #17304

![image](https://user-images.githubusercontent.com/16890566/102298589-4383d900-3f06-11eb-8816-0291ff24de7e.png)

**Comment by scbedd** [comment]
Please submit a PR that updates [this file](https://github.com/MicrosoftDocs/azure-docs-sdk-node/blob/master/ci-configs/packages-preview.json) to remove the packages that are no longer GA.

I have filed an [issue](https://github.com/Azure/azure-sdk/issues/2268) to cover this as part of the doc automation.

**Comment by ramya-rao-a** [comment]
Thanks @scbedd 
@samvaity, Can you please assign this issue to the release driver from your team?

**Comment by samvaity** [comment]
@g2vinay Could you take a look at this.

@ramya-rao-a 
Just to clarify, would this mean once a package has been GA'ed we should not be seeing that package in [here](https://docs.microsoft.com/en-us/java/api/overview/azure/?view=azure-java-preview) at all? 
However, we do support beta service releases and patch/stable releases.

For instance, FormRecognizer 3.1.0-beta.2 **(beta)** targets v2.1-preview.2 service version which is [preview](https://docs.microsoft.com/en-us/java/api/overview/azure/ai-formrecognizer-readme?view=azure-java-preview#include-the-package) whereas the FormRecognizer 3.0.5 **(stable)** version still targets service version v2.0 under [stable ref docs](https://docs.microsoft.com/en-us/java/api/overview/azure/ai-formrecognizer-readme?view=azure-java-stable#include-the-package).

**Comment by ramya-rao-a** [comment]
@samvaity Packages should show up here if there is a beta version that has not gone GA.
In your example of FR, it should appear both under preview and latest monikers. But say FR 3.1.0 goes GA in a few months, then you shouldnt see FR under the preview moniker until the next preview is out

**Comment by g2vinay** [comment]
@samvaity @ramya-rao-a 
I'll take a look and submit a PR as @scbedd suggested above to update the file.

**Comment by g2vinay** [comment]
Closing this as packages look accurate now.
