### ISSUE TITLE
[Service Bus] Service level overview in ref docs should list all packages

### ISSUE THREAD

**Issue by ramya-rao-a** [Azure/azure-sdk-for-java#18164]
The [Service level overview for reference docs for Service Bus](https://docs.microsoft.com/en-us/java/api/overview/azure/servicebus?view=azure-java-stable) currently talks about Track 1 packages. Instead, we should list all available packages (data plane and mgmt plane) starting with Track 2, then moving to Track 1 with links to source code, package manager, samples and reference docs. This currently also has a very long description which should be truncated.

Use the [Service level overview for reference docs for Storage](https://docs.microsoft.com/en-us/java/api/overview/azure/storage?view=azure-java-stable) as a reference if needed

Found as part of #17304

**Comment by joshfree** [comment]
@scottaddie is this something you could look into as part of your doc push this semester?

**Comment by ramya-rao-a** [comment]
Looks like we added the required entries over time
I just pushed https://github.com/Azure/azure-docs-sdk-java/commit/2aef964389b320dd3ca5efeac2df8ce394132c60 for some final polish
