### ISSUE TITLE
Query service principle by secret expire date using microsoft graph api

### ISSUE THREAD

**Issue by hemasundars** [Azure/azure-sdk-for-java#18160]
IServicePrincipalCollectionPage servicePrincipals = graphClient.servicePrincipals()
                    .buildRequest()
                    .filter("startsWith(displayName, 'Hema')")
                    .get();
 
I go below output for my service principle Hema-automation:
 
{"@odata.context":"https://graph.microsoft.com/v1.0/$metadata#servicePrincipals","value":[{"id":"6257f5e5-5759-4fc4-adcc-0f30636cfd90","deletedDateTime":null,"accountEnabled":true,"alternativeNames":[],"appDisplayName":"Hema-automation","appDescription":null,"appId":"2dc70613-c495-4c40-a173-a24583c059f6","applicationTemplateId":null,"appOwnerOrganizationId":"fa7b1b5a-7b34-4387-94ae-d2c178decee1","appRoleAssignmentRequired":false,"createdDateTime":"2018-09-19T23:29:08Z","description":null,"displayName":"Hema-automation","homepage":"https://www.google.com/","loginUrl":null,"logoutUrl":null,"notes":null,"notificationEmailAddresses":[],"preferredSingleSignOnMode":null,"preferredTokenSigningKeyThumbprint":null,"replyUrls":["https://www.google.com/"],"resourceSpecificApplicationPermissions":[],"samlSingleSignOnSettings":null,"servicePrincipalNames":["https://adobe.onmicrosoft.com/dbeb7ce1-58ca-4bdf-a787-acdae91fed44","2dc70613-c495-4c40-a173-a24583c059f6"],"servicePrincipalType":"Application","signInAudience":"AzureADMultipleOrgs","tags":["WindowsAzureActiveDirectoryIntegratedApp"],"tokenEncryptionKeyId":null,"verifiedPublisher":{"displayName":null,"verifiedPublisherId":null,"addedDateTime":null},"addIns":[],"appRoles":[],"info":{"logoUrl":null,"marketingUrl":null,"privacyStatementUrl":null,"supportUrl":null,"termsOfServiceUrl":null},"keyCredentials":[],"oauth2PermissionScopes":[{"adminConsentDescription":"Allow the application to access Hema-automation on behalf of the signed-in user.","adminConsentDisplayName":"Access Hema-automation","id":"e26b30e3-f0b0-4aaa-a732-45783430e932","isEnabled":true,"type":"User","userConsentDescription":"Allow the application to access Hema-automation on your behalf.","userConsentDisplayName":"Access Hema-automation","value":"user_impersonation"}],"passwordCredentials":[]}]}
 
I do not see any subscription id or Expire Date(endDateTime) to query by subscription and Expire date.

**Comment by joshfree** [comment]
Hi @hemasundars, thanks for filing this issue.  Could you please provide a bit more information such as the version of the library being used (https://github.com/Azure/azure-sdk-for-java/blob/master/.github/ISSUE_TEMPLATE/bug_report.md)?  This will help the folks from the `Graph` team assist you further.  Thanks 😄

**Comment by hemasundars** [comment]
@joshfree  I used IApplicationCollectionPage to get required information for me. I am closing this issue.
