### ISSUE TITLE
[BUG] Key Vault adding escape characters on values.

### ISSUE THREAD

**Issue by darinhoward** [Azure/azure-sdk-for-java#18180]
**Describe the bug**
Key Vault value of `secret\@!` will return as `secret\\@!`

**Expected behavior**
Key Vault value returns without additional escape characters. 

**Setup (please complete the following information):**
 - OS: Linux / MacOS
 - Version of the Library use: `com.azure:azure-security-keyvault-secrets:jar:4.2.3`

**Information Checklist**
Kindly make sure that you have added all the following information above and checkoff the required fields otherwise we will treat the issuer as an incomplete report
- [x] Bug Description Added
- [x] Repro Steps Added
- [x] Setup information Added

**Comment by vcolin7** [comment]
Azure Key Vault Secrets GET requests are serviced with a response that includes JSON body that escapes especial characters, such as forward slashes `\` -> `\\`. Calls to get secrets with the Azure Key Vault Secrets SDK internally handle deserialization of said JSON object and allow for users to access the original unescaped value through `KeyVaultSecret.getValue()`.

I created a secret in a Kay Vault with name `test-escaped-secret` and value `secret\@!` and wrote some code to demonstrate this:

```java
String keyVaultUrl = "https://<your-key-vault-name>.vault.azure.net/";

SecretClient secretClient = new SecretClientBuilder()
    .vaultUrl(keyVaultUrl)
    .credential(new DefaultAzureCredentialBuilder().build())
    .httpLogOptions(new HttpLogOptions().setLogLevel(HttpLogDetailLevel.BODY_AND_HEADERS))
    .buildClient();

KeyVaultSecret secret = secretClient.getSecret("test-escaped-secret");

System.out.printf("Secret name: %s, secret value: %s\n", secret.getName(), secret.getValue());
```

By setting the `HttpLogDetailLevel` to `BODY_AND_HEADERS`, we can see the following logs:

```
[main] INFO com.azure.identity.EnvironmentCredential - Azure Identity => EnvironmentCredential nvoking ClientSecretCredential
[main] ERROR com.azure.identity.implementation.IntelliJCacheAccessor - IntelliJ Authentication not available. Please log in with Azure Tools for IntelliJ plugin in the IDE.
[main] INFO com.azure.security.keyvault.secrets.SecretAsyncClient - Retrieving secret - test-escaped-secret
[main] INFO com.azure.security.keyvault.secrets.SecretService.getSecret - --> GET https://REDACTED.vault.azure.net/secrets/test-escaped-secret/?api-version=REDACTEDTry count: 1(empty body)--> END GET
[reactor-http-nio-1] INFO com.azure.security.keyvault.secrets.SecretService.getSecret - <-- 401 https://REDACTED.vault.azure.net/secrets/test-escaped-secret/?api-version=REDACTED (2518 ms, 87-byte body)Response body:{"error":{"code":"Unauthorized","message":"Request is missing a Bearer or PoP token."}}<-- END HTTP
[ForkJoinPool.commonPool-worker-3] INFO com.azure.identity.ClientSecretCredential - Azure Identity => getToken() result for scopes [https://vault.azure.net/.default]: SUCCESS
[ForkJoinPool.commonPool-worker-3] INFO com.azure.identity.DefaultAzureCredential - Azure Identity => Attempted credential EnvironmentCredential returns a token
[ForkJoinPool.commonPool-worker-3] INFO com.azure.security.keyvault.secrets.SecretService.getSecret - --> GET https://REDACTED.vault.azure.net/secrets/test-escaped-secret/?api-version=REDACTEDTry count: 1(empty body)--> END GET
[reactor-http-nio-1] INFO com.azure.security.keyvault.secrets.SecretAsyncClient - Retrieved secret - test-escaped-secret
[reactor-http-nio-1] INFO com.azure.security.keyvault.secrets.SecretService.getSecret - <-- 200 https://REDACTED.vault.azure.net/secrets/test-escaped-secret/?api-version=REDACTED (91 ms, 271-byte body)Response body:{"value":"secret\\@!","id":"https://REDACTED.vault.azure.net/secrets/test-escaped-secret/db52e3efdca54fbfa45b3653d66096dd","attributes":{"enabled":true,"created":1608240403,"updated":1608240403,"recoveryLevel":"Recoverable+Purgeable","recoverableDays":90}}<-- END HTTP
Secret name: test-escaped-secret, secret value: secret\@!
```

So although the values can contain escaped characters in the HTTP response provided by the server, the SDK takes care of that for the user.

**Comment by vcolin7** [comment]
@darinhoward if you found behavior different to what I described above, would you mind sharing some sample code where this can be reproduced?

I guess it is possible that if you use a different serializer implementation than the default one offered by our clients, the behavior I described could be different, although it would take a bit of effort to deviate from such regular scenarios.

**Comment by darinhoward** [comment]
@vcolin7  I believe my setup when running into the error was not using the version I specified - I'm not able to replicate the issue either with your sample nor with my code using the latest keyvault version. Thank you for your help on this.
