### ISSUE TITLE
Unable to dissociate NSG from Subnet

### ISSUE THREAD

**Issue by abayta** [Azure/azure-sdk-for-java#1819]
When we have to update a subnet to remove the route table we have the next method: 
`.updateSubnet(subnetName).withoutRouteTable()` but if we want to do the same with the NSG allocate we don't have a specific method for that. We have to use `.updateSubnet(subnetName).withExistingNetworkSecurityGroup("")` with a blank string param.

[UPDATE]
Today the result of `.updateSubnet(subnetName).withExistingNetworkSecurityGroup("")` is the next error: 

> [RxIoScheduler-2] ERROR CallBackStatus - Property id '' at path 'properties.subnets[0].properties.networkSecurityGroup.id' is invalid. Expect fully qualified resource Id that start with '/subscriptions/{subscriptionId}' or '/providers/{resourceProviderNamespace}/'.

How can I dissociate an NSG from a subnet? I only found that doc https://docs.microsoft.com/en-us/azure/virtual-network/virtual-network-manage-nsg-arm-cli

It is very very confusing

**Comment by martinsawicki** [comment]
Agreed this was missed. Fixed in https://github.com/Azure/azure-sdk-for-java/pull/1814/commits/66aca6ff1769bb1064a663017beb5b8e842cd01c. Will ship in v1.2

**Comment by abayta** [comment]
Great work!!
