### ISSUE TITLE
Metric advisor Sample issues

### ISSUE THREAD

**Issue by Melanie-Ma** [Azure/azure-sdk-for-java#18199]
1.
Section [Link1](https://github.com/Azure/azure-sdk-for-java/blob/959e3fa288b8dcd880b41f4fd85aad239bbdb0c3/sdk/metricsadvisor/azure-ai-metricsadvisor/src/samples/java/com/azure/ai/metricsadvisor/administration/AnomalyDetectionConfigurationSample.java#L55), [Link2](https://github.com/Azure/azure-sdk-for-java/blob/959e3fa288b8dcd880b41f4fd85aad239bbdb0c3/sdk/metricsadvisor/azure-ai-metricsadvisor/src/samples/java/com/azure/ai/metricsadvisor/administration/AnomalyDetectionConfigurationAsyncSample.java#L74):
![image](https://user-images.githubusercontent.com/64007802/102433521-94064e00-404e-11eb-98a1-e1475e678914.png)
Suggestion: 
Change the position of delete and list configuration code. 
2.
Section [Link1](https://github.com/Azure/azure-sdk-for-java/blob/959e3fa288b8dcd880b41f4fd85aad239bbdb0c3/sdk/metricsadvisor/azure-ai-metricsadvisor/src/samples/java/com/azure/ai/metricsadvisor/administration/DatafeedSample.java#L81), [Link2](https://github.com/Azure/azure-sdk-for-java/blob/959e3fa288b8dcd880b41f4fd85aad239bbdb0c3/sdk/metricsadvisor/azure-ai-metricsadvisor/src/samples/java/com/azure/ai/metricsadvisor/administration/DatafeedAsyncSample.java#L98):
![image](https://user-images.githubusercontent.com/64007802/102434078-feb78980-404e-11eb-85b2-d85d97710267.png)
Reason:
When updating data feed, if using set options, it always throws  NullPointerException.
3.
Section [Link1](https://github.com/Azure/azure-sdk-for-java/blob/959e3fa288b8dcd880b41f4fd85aad239bbdb0c3/sdk/metricsadvisor/azure-ai-metricsadvisor/src/samples/java/com/azure/ai/metricsadvisor/administration/MetricsAnomalyAlertConfigOperationsSample.java#L30), [Link2](https://github.com/Azure/azure-sdk-for-java/blob/959e3fa288b8dcd880b41f4fd85aad239bbdb0c3/sdk/metricsadvisor/azure-ai-metricsadvisor/src/samples/java/com/azure/ai/metricsadvisor/administration/MetricsAnomalyAlertConfigOperationsAsyncSample.java#L31):
![image](https://user-images.githubusercontent.com/64007802/102434283-6cfc4c00-404f-11eb-98fc-a486e041d626.png)
![image](https://user-images.githubusercontent.com/64007802/102434294-72599680-404f-11eb-82a1-f8b40dff962f.png)
Reason:
Exception in thread "main" java.lang.IllegalArgumentException: UUID string too large
"9ol48er30-6e6e-4391-b78f-b00dfee1e6f5" length is 37
Suggestion:
Change to "ff3014a0-bbbb-41ec-a637-677e77b81299"
4.
Section [Link1](https://github.com/Azure/azure-sdk-for-java/blob/959e3fa288b8dcd880b41f4fd85aad239bbdb0c3/sdk/metricsadvisor/azure-ai-metricsadvisor/src/samples/java/com/azure/ai/metricsadvisor/administration/MetricsAnomalyAlertConfigOperationsSample.java#L30), [Link2](https://github.com/Azure/azure-sdk-for-java/blob/959e3fa288b8dcd880b41f4fd85aad239bbdb0c3/sdk/metricsadvisor/azure-ai-metricsadvisor/src/samples/java/com/azure/ai/metricsadvisor/administration/MetricsAnomalyAlertConfigOperationsAsyncSample.java#L31):
![image](https://user-images.githubusercontent.com/64007802/102434524-e300b300-404f-11eb-92bd-f013f8e59171.png)
Suggestion:
Change to "e87d899d-a5a0-4259-b752-11aea34d5e34"
5.
Section [Link](https://github.com/Azure/azure-sdk-for-java/blob/2383dfc9b32e6de469af16d27d39fffbeb58077a/sdk/metricsadvisor/azure-ai-metricsadvisor/src/samples/java/com/azure/ai/metricsadvisor/administration/MetricsAnomalyAlertConfigOperationsSample.java#L46):
![image](https://user-images.githubusercontent.com/64007802/102434614-16434200-4050-11eb-9240-aac832c9fbe4.png)
Suggestion: 
Add `.setMinAlertSeverity(AnomalySeverity.LOW)`
6.
Section [Link1](https://github.com/Azure/azure-sdk-for-java/blob/959e3fa288b8dcd880b41f4fd85aad239bbdb0c3/sdk/metricsadvisor/azure-ai-metricsadvisor/src/samples/java/com/azure/ai/metricsadvisor/administration/DatafeedSample.java#L81), [Link2](https://github.com/Azure/azure-sdk-for-java/blob/959e3fa288b8dcd880b41f4fd85aad239bbdb0c3/sdk/metricsadvisor/azure-ai-metricsadvisor/src/samples/java/com/azure/ai/metricsadvisor/administration/DatafeedAsyncSample.java#L98):
![image](https://user-images.githubusercontent.com/64007802/102436125-daf64280-4052-11eb-861b-78b06ebbf527.png)
![image](https://user-images.githubusercontent.com/64007802/102436137-e0538d00-4052-11eb-82c4-2ad206cf9d67.png)
Question:
If removing set options to resolve the  .NullPointerException bug. Throw new exception as follow. 
`Exception in thread "main" com.azure.ai.metricsadvisor.models.ErrorCodeException: Status code 400, "{"code":"BadRequest","message":"JSON parse error: Cannot deserialize value of type `com.microsoft.powerai.contract.thirdparty.metadata.enumlist.DataSourceType` from String \"AzureApplicationInsights\": value not one of declared Enum instance names: [ObjectStore, KVP, Kafka, HttpRequest, CosmosDB, Cosmos, SqlServer, MongoDB, PostgreSql, Cube, Mdm, None, EventHub, Elasticsearch, AzureTable, MySql, Kusto, DataCopIScope, JSON, DataLakeStructured, iScope, AzureBlob, AzureDataLakeStorageGen2, API, xCard, ApplicationInsights, InfluxDB]; nested exception is com.fasterxml.jackson.databind.exc.InvalidFormatException: Cannot deserialize value of type `com.microsoft.powerai.contract.thirdparty.metadata.enumlist.DataSourceType` from String \"AzureApplicationInsights\": value not one of declared Enum instance names: [ObjectStore, KVP, Kafka, HttpRequest, CosmosDB, Cosmos, SqlServer, MongoDB, PostgreSql, Cube, Mdm, None, EventHub, Elasticsearch, AzureTable, MySql, Kusto, DataCopIScope, JSON, DataLakeStructured, iScope, AzureBlob, AzureDataLakeStorageGen2, API, xCard, ApplicationInsights, InfluxDB]\n at [Source: (PushbackInputStream); line: 1, column: 19] (through reference chain: com.microsoft.powerai.metadata3p.adapter.meta.v1.apiContract.DatafeedPatchV1[\"dataSourceType\"])"}"`

Clearly,DataSourceType AzureApplicationInsights and  ApplicationInsights don't match leading to this bug.
If  data feed creating by Azure blob data source doesn't have this bug.

@jongio  for notification.

**Comment by samvaity** [comment]
@Melanie-Ma Looking into this.
