### ISSUE TITLE
Keyvault Keys  Sample issues

### ISSUE THREAD

**Issue by Melanie-Ma** [Azure/azure-sdk-for-java#18205]
1.
Section [Link1](https://github.com/Azure/azure-sdk-for-java/blob/master/sdk/keyvault/azure-security-keyvault-keys/src/samples/java/com/azure/security/keyvault/keys/cryptography/CryptographyClientJavaDocCodeSnippets.java#L279), [Link2](https://github.com/Azure/azure-sdk-for-java/blob/master/sdk/keyvault/azure-security-keyvault-keys/src/samples/java/com/azure/security/keyvault/keys/cryptography/CryptographyClientJavaDocCodeSnippets.java#L289):
![image](https://user-images.githubusercontent.com/64007802/102435837-412e9580-4052-11eb-848a-aa79ef97a0f8.png)
Suggestion:
Change to 
```
byte[] wrappedKey = new byte[100];
wrappedKey = wrapResult.getEncryptedKey();
```

@jongio for notification

**Comment by vcolin7** [comment]
We avoid referencing variables from other snippets because they will be shown independently from each other. I don't think we should make this change. Why is this an issue?

**Comment by Melanie-Ma** [comment]
@vcolin7 - If we don't change the code here, we will report the following error when running this code：
![image](https://user-images.githubusercontent.com/64007802/109609521-66697500-7b66-11eb-993e-0f4c064e4b1a.png)
What`s more, we need to run this code successfully, even if it`s just code snippet. Please check!

**Comment by vcolin7** [comment]
Ok, let's make the code work but without referencing variables from other samples, like stated [in the Java guidelienes](https://azure.github.io/azure-sdk/java_introduction.html#java-samples-grafting).

**Comment by vcolin7** [comment]
@Melanie-Ma Opened up #20680 for this :)
