### ISSUE TITLE
[BUG] Service bus client never recovers from `Exception occurred when handling event in super.`

### ISSUE THREAD

**Issue by marciopd** [Azure/azure-sdk-for-java#18219]
**Describe the bug**
Service bus client stop receiving messages and `com.azure.core.amqp.implementation.handler.CustomIOHandler` logs `Exception occurred when handling event in super.` in what appears to be an "almost infinite" loop (CPU usage ramps all the way up and the message is logged thousands of times in a 1s timeframe).

The same error keeps happening again and again and client never recovers. 

This issue report is focused is two things:

1. improving the troubleshooting of the issue
2. fixing the issue itself

***Exception or Stack Trace***
<img width="565" alt="Screenshot 2020-12-17 at 20 53 12" src="https://user-images.githubusercontent.com/2352369/102536430-e3c63300-40a9-11eb-85cf-6cc5b9e194d3.png">

**To Reproduce**
Happens randomly from time to time in a production environment.

**Expected behavior**
Error should be logged in a way to ease the troubleshooting and the client should recover from it without requiring an application restart.

**Screenshots**
CPU all the way up until the affected server gets killed:
<img width="601" alt="Screenshot 2020-12-17 at 21 07 38" src="https://user-images.githubusercontent.com/2352369/102537921-e7f35000-40ab-11eb-987d-e59e4795528d.png">

Amount of times the messages gets logged:
<img width="606" alt="Screenshot 2020-12-17 at 21 16 11" src="https://user-images.githubusercontent.com/2352369/102538822-1887b980-40ad-11eb-97d7-55081458fe00.png">

**Setup (please complete the following information):**
 - OS: Linux
 - IDE : IntelliJ
 - Azure Service Bus 7.0.0

**Information Checklist**
Kindly make sure that you have added all the following information above and checkoff the required fields otherwise we will treat the issuer as an incomplete report
- [X] Bug Description Added
- [X] Repro Steps Added
- [X] Setup information Added

**Comment by hemanttanwar** [comment]
Hello @marciopd , you said that it happens randomly in production. We will try to replicate to understand it better. But we need more information to reproduce it. Can you provide following information
1. Steps to reproduce this issue.
2. your production environment OS version, Java version details

Any additional information will be helpful.

**Comment by marciopd** [comment]
Hello @hemanttanwar , it happens randomly. For instance, didn't happen for 3 weeks, and now just did.

Please contact me by email, so I can disclose the requested information and more details if needed (like Azure account and etc).

**Comment by hemanttanwar** [comment]
@marciopd We do not need your azure account information.  We need more information about your application run time environment to be able to reproduce the issue.

Can you provide following information

1. Steps to reproduce this issue.
2. Your environment OS version ( for example linux VM  version ? ), Java version, any other environment detail which might help us setup a test to replicate the issue.
3. Upload non proprietary sample code if possible.

I have also sent you email, in case you want to provide this information in email.
