### ISSUE TITLE
azure-messaging-servicebus-7.0.0  - Enable/Disable Queue/Topic and Enable/Disable firewall

### ISSUE THREAD

**Issue by abhikt48** [Azure/azure-sdk-for-java#18214]
We started exploring new SDK `azure-messaging-servicebus-7.0.0` .  We need to  enable/disable servicebus entity for intgration testing. 

Can you please suggest - how can I perform below operations with new SDK `azure-messaging-servicebus-7.0.0` ? I looked on `com.azure.messaging.servicebus.administration.ServiceBusAdministrationClient` class, but didn't find any option to perform below operations. If possible, can you please provide samples to perform below activities?

1. Enable/Disable Queue/Topic 
2. Enable/Disable firewall for premium serviceBus

I am trying to find a way to forcefully disable Network Connection with ServiceBus. I achieved this requirement manually via two ways - 1)disable Wifi/Internet 2) enable firewall at ServiceBus.

Can you please suggest any solution to achieve this requirement with ServiceBus SDK ?

If these features are not available then can you please accept it as enhancement.

**Comment by hemanttanwar** [comment]
@abhikt48 Thank you for the query .

1.  Yes you can use `com.azure.messaging.servicebus.administration.ServiceBusAdministrationClient`  to enable/disable queue or topic. Here is sample https://github.com/Azure/azure-sdk-for-java/pull/18236/files#diff-cf7199a0d741abad253742e05459c3028efbe51e29d71b71995c45ade90b254aR43

2. Enable/Disable firewall for premium serviceBus : This SDK `azure-messaging-servicebus-7.0.0` does not support this feature.
But you can look at following links for this 

Shows how ARM template could be used. https://docs.microsoft.com/en-us/azure/service-bus-messaging/service-bus-ip-filtering#ip-firewall-rules

Another java library to achieve this.

https://devblogs.microsoft.com/azure-sdk/introducing-mgmt-for-java/
https://search.maven.org/artifact/com.azure.resourcemanager/azure-resourcemanager-servicebus/2.1.0/jar

Hope this answer your questions.

**Comment by abhikt48** [comment]
Hi @hemanttanwar  - Thanks for your quick update. 

Do we have facuility to delete/disable queue from "azure-resourcemanager-servicebus-2.1.0" SDK as well? If yes can you please provide sample code ?

**Comment by hemanttanwar** [comment]
@weidongxu-microsoft Can you answer above question on "azure-resourcemanager-servicebus-2.1.0" ?

**Comment by weidongxu-microsoft** [comment]
@xccc-msft Could you take a look?

**Comment by xccc-msft** [comment]
@abhikt48 Please check below if it helps for `azure-resourcemanager-servicebus-2.1.0`.
```java
QueueCreateOrUpdateParameters queueParameters = new QueueCreateOrUpdateParameters();
queueParameters.withStatus(EntityStatus.DISABLED);
serviceBusManager.serviceClient().getQueues().createOrUpdate("rgName", "namespaceName", "queueName", queueParameters);

TopicCreateOrUpdateParameters topicParameters = new TopicCreateOrUpdateParameters();
topicParameters.withStatus(EntityStatus.DISABLED);
serviceBusManager.serviceClient().getTopics().createOrUpdate("rgName", "namespaceName", "topicName", topicParameters);
```

**Comment by hemanttanwar** [comment]
@abhikt48  Closing this issue since original question is answered.  Feel free to re open if you need additional information.
