### ISSUE TITLE
Schema Registry schema should support newline characters

### ISSUE THREAD

**Issue by srnagar** [Azure/azure-sdk-for-java#18220]
[ Reported by @mrickly here - https://github.com/Azure/azure-docs-sdk-java/pull/1587 ]

With the dependency com.microsoft.azure:azure-schemaregistry-kafka-avro:1.0.0-beta.4 (and transitively com.azure:azure-data-schemaregistry-avro:1.0.0-beta.4), registering a schema with the registerSchema method leads to an error of this type when the schemaContent String contains line breaks:
com.azure.data.schemaregistry.implementation.models.ServiceErrorResponseException: Status code 400, "{"Code":400,"Detail":"Schema validation failed: Invalid character after parsing property name. Expected ':' but got: ". Path '', line 1, position 6. TrackingId:ac261746-d452-491f-b008-005de5bc9175_G10, SystemTracker:mobi-gluon-order.servicebus.windows.net:$schemagroups/order/schemas/order, Timestamp:2020-12-09T13:56:41"}"
By deserializing to an avro Schema and serializing again with the toString method of the Schema, we get rid of all the pretty printing characters.

**Comment by ramya-rao-a** [comment]
@conniey Is this still applicable?
