### ISSUE TITLE
Disable checkstyle suppressions for Track 2 libraries

### ISSUE THREAD

**Issue by samvaity** [Azure/azure-sdk-for-java#18279]
- [x]  [EventGrid](https://github.com/Azure/azure-sdk-for-java/blob/master/eng/code-quality-reports/src/main/resources/checkstyle/checkstyle-suppressions.xml#L566)
- [x]  [DigitalTwins Core](https://github.com/Azure/azure-sdk-for-java/blob/master/eng/code-quality-reports/src/main/resources/checkstyle/checkstyle-suppressions.xml#L565)
- [x]  [Schemaregistry](https://github.com/Azure/azure-sdk-for-java/blob/master/eng/code-quality-reports/src/main/resources/checkstyle/checkstyle-suppressions.xml#L401)
- [x] [Anomaly detector](https://github.com/Azure/azure-sdk-for-java/blob/master/eng/code-quality-reports/src/main/resources/checkstyle/checkstyle-suppressions.xml#L567)

**Comment by samvaity** [comment]
@srnagar could you take look at the anomaly detector code changes for this issue?

**Comment by YijunXieMS** [comment]
EventGrid enabled checkstyle. This was removed from `checkstyle-suppressions.xml`
```xml
<suppress checks="[a-zA-Z0-9]*" files="[/\\]azure-messaging-eventgrid[/\\]src[/\\]"/>
```

**Comment by azabbasi** [comment]
There are a few required changes by the checkstyle plugin that we cannot address. They are recommendations on the public API method signatures that have already gone GA. We will still need to suppress the checkstyle for the sync and async clients as well as the generated layer as we have no control over the code style there. 
Does that satisfy the requirements of this issue?

**Comment by samvaity** [comment]
>There are a few required changes by the checkstyle plugin that we cannot address. They are recommendations on the public API method signatures that have already gone GA. We will still need to suppress the checkstyle for the sync and async clients as well as the generated layer as we have no control over the code style there.
Does that satisfy the requirements of this issue?

Yes, those should be fine. We mainly wanted to address the removal of the wildcard suppression `suppress checks="[a-zA-Z0-9]*"` for digital twins. Thanks !

**Comment by samvaity** [comment]
Generic checkstyle suppression disabled for all mentioned libs.
