### ISSUE TITLE
Add Resource Manager node to Key Vault Preview ToC at docs.microsoft.com

### ISSUE THREAD

**Issue by vcolin7** [Azure/azure-sdk-for-java#18283]
Found via #17311.

Currently the Resource Manager node can only be seen for the [Stable ToC](https://docs.microsoft.com/en-us/java/api/overview/azure/security-keyvault-keys-readme?view=azure-java-stable). Here's the [how the Preview ToC looks](https://docs.microsoft.com/en-us/java/api/overview/azure/security-keyvault-keys-readme?view=azure-java-preview).

Stable
![image](https://user-images.githubusercontent.com/5799331/102675930-e9328480-4160-11eb-88ee-a83a4ec6d81c.png)

Preview
![image](https://user-images.githubusercontent.com/5799331/102675938-f0599280-4160-11eb-8de4-9ada22c93d45.png)

**Comment by kurtzeborn** [comment]
This is an issue that library owners should be able to address by following the documentation we've created for these types of issues [here](https://dev.azure.com/azure-sdk/internal/_wiki/wikis/internal.wiki/283/Docs.MS-Primer?anchor=how-do-i-actually-update-the-toc%3F).

**Comment by sima-zhu** [comment]
The toc missed from our script updates. I will also take a look.

**Comment by sima-zhu** [comment]
Keyvault resource manager is having GA version ahead of preview. So do we still need the preview Resource Manager show up in toc?

If you definitely need the preview version, please update the preview section under package.json.
In the section here: https://github.com/Azure/azure-docs-sdk-java/blob/master/package.json#L1071

**Comment by vcolin7** [comment]
In that case, I don't think we need to have that in the Preview ToC. I assumed that the library would still have stuff in development and would have a preview.
