### ISSUE TITLE
Standardize rendering strategy for docs.microsoft.com ToC between languages

### ISSUE THREAD

**Issue by vcolin7** [Azure/azure-sdk-for-java#18284]
Found via #17311.

Currently all Tier 1 languages but JavaScript do not render the children nodes of the packages under each library in their ToC. In other words, children nodes under a sub-package are not expandable in documentation for languages other than JavaScript. Take Azure Storage for example:

[Azure Storage for Java](https://docs.microsoft.com/en-us/java/api/overview/azure/storage?view=azure-java-stable)
![image](https://user-images.githubusercontent.com/5799331/102676128-b5a42a00-4161-11eb-9588-5e58768e9954.png)

[Azure Storage for .NET](https://docs.microsoft.com/en-us/java/api/overview/azure/storage?view=azure-java-stable)
![image](https://user-images.githubusercontent.com/5799331/102677434-0880e000-4168-11eb-84d7-29fb7bb5c85f.png)

[Azure Storage for Python](https://docs.microsoft.com/en-us/java/api/overview/azure/storage?view=azure-java-stable)
![image](https://user-images.githubusercontent.com/5799331/102677463-2c442600-4168-11eb-9e2d-0750b6a698f2.png)

[Azure Storage for JS](https://docs.microsoft.com/en-us/javascript/api/overview/azure/storage-overview?view=azure-node-latest) (this one renders child nodes like @azure/storage-blob)
![image](https://user-images.githubusercontent.com/5799331/102676096-8f7e8a00-4161-11eb-93d6-781a6b8a40ec.png)

Maybe it's because JS has everything live under the same namespace instead of separating by packages? Regardless, it's not a cohesive experience and we should probably come up with a guideline for this type of things to be consistent across all languages.

**Comment by kurtzeborn** [comment]
I talked to @scbedd about this.  So we can't fix this in our code/processes.  This is something that will need to be fixed in the docs team's processes, but we'll need to help them get there.  Assigning this to @danieljurek since he will be the point person for following up with the docs team on this (with @scbedd's help of course :))
