### ISSUE TITLE
Design a bridge library that send Cloud native events to EventGrid

### ISSUE THREAD

**Issue by YijunXieMS** [Azure/azure-sdk-for-java#18280]
EventGrid service is compatible with the cloudevents standard (https://github.com/cloudevents/sdk-java).
We need to create a bridge library that can send an `io.cloudevents.CloudEvent` to the EventGrid service. 

The design will be done in early Jan 2021. The implementation can be after EventGrid 2.0.0 GA.

**Comment by MarkLinovy** [comment]
isn't this done with https://github.com/Azure/azure-sdk-for-java/tree/main/sdk/eventgrid/azure-messaging-eventgrid-cloudnative-cloudevents ?

I was looking to contribute and this issue was listed. But after searching through the repository i found that it was already cone.
