### ISSUE TITLE
Confirm [BUG] netty hostname verification

### ISSUE THREAD

**Issue by rhuddleston** [Azure/azure-sdk-for-java#18286]
**Query/Question**
https://snyk.io/vuln/SNYK-JAVA-IONETTY-1042268

Can you confirm if hostname verification is enabled on netty use for java azure-identity? Hostname verification is disabled by default in the current version of of netty.

**Comment by rhuddleston** [comment]
Any thoughts on this?

**Comment by sgraca** [comment]
Hi @g2vinay

Sorry for digging up such an old issue, but could you please point to the part of the code that configures the hostname verification?

My team is integrating our application with Azure AD and we were alerted about [improper certificate validation](https://security.snyk.io/vuln/SNYK-JAVA-IONETTY-1042268) vulnerability in the `netty-handler` module and I want to be sure that this is indeed mitigated.

I tried to find a code responsible for enabling hostname verification in `azure-core-http-netty` module bug had no luck.

Thank you in advance
