### ISSUE TITLE
Enable DeclarationOrder check for azure-spring package related files

### ISSUE THREAD

**Issue by samvaity** [Azure/azure-sdk-for-java#18291]
Recently we added the DeclarationOrderCheck in this [PR](https://github.com/Azure/azure-sdk-for-java/pull/18025/files#diff-72cfbd8c1390819a04f1e6ff4d4751605ee31163ce34c70992f6e32e1a5066c9R536). Enable this check and necessary updates for spring packages need to be made.

Enable 
```xml
<suppress checks="EmptyCatchBlock" files="com.azure.spring.security.keyvault.certificates.starter.KeyVaultCertificatesEnvironmentPostProcessor.java"/>
```

**Comment by saragluna** [comment]
Hi @samvaity, I'm seeing this issue from PR https://github.com/Azure/azure-sdk-for-java/pull/18025, is this issue going to be assigned to the spring team?

**Comment by samvaity** [comment]
>Hi @samvaity, I'm seeing this issue from PR #18025, is this issue going to be assigned to the spring team?

Yes @saragluna, we should assign this to the spring team.

**Comment by saragluna** [comment]
Thanks, @samvaity. Added the assignees.

**Comment by stliu** [comment]
@saragluna not sure if this is still valid, if it does, let's get this done in May, thanks

**Comment by saragluna** [comment]
@samvaity is this feature request still valid?

**Comment by samvaity** [comment]
This request is not valid anymore.
