### ISSUE TITLE
[BUG] Service Bus: Memory leak if session based consumer is closed and (re)started

### ISSUE THREAD

**Issue by alewis001** [Azure/azure-sdk-for-java#18294]
**Describe the bug**
There is a memory leak is a session-based processor client is closed and then restarted.

**Closing** and restarting the processor client was done in an attempt to work around #18122. Closing and restarting does cause the SDK to pull the messages from the active sessions; however, this leak is causing the application to OutOfMemory.

**Stopping I.e. stop()** and restarting the client does not work as it does not retrieve the latest messages from a session as per #18122 so Closing is the only option whilst #18122 exists.

**To Reproduce**

1. Create a session based processor, call start.
2. After some time, call close().
3. Call start on the processor.
4. Goto 2.

E.g. see code snippet.

***Code Snippet***
```
ScheduledExecutorService es = Executors.newSingleThreadScheduledExecutor();
es.scheduleAtFixedRate(() -> {
    try {
        System.out.println("Restarting client");
        if (processorClient != null) {
            processorClient.close();
        } else {
            processorClient = buildClient();
        }
        processorClient.start();
    } catch (Throwable t) {
        t.printStackTrace();
    }
}, 1, 30, TimeUnit.SECONDS);
```
```
private ServiceBusProcessorClient buildClient() {
        return new ServiceBusClientBuilder()
                .connectionString("<< connection string >>")
                .sessionProcessor()
                .queueName("<< queue >>")
                .maxConcurrentSessions(10)
                .processMessage(this::processMessage)
                .processError(this::processError)
                .buildProcessorClient();
    }
```
**Expected behavior**
No memory leak.

**Setup (please complete the following information):**
 - OS: MacOS
 - IDE : Netbeans
 - Version of the Library used: 7.0.0

**Comment by hemanttanwar** [comment]
@alewis001 We have released new version of library which has fix for #18122 ,  You can download it from here https://search.maven.org/artifact/com.azure/azure-messaging-servicebus 
Can you try and let us know if you still see any issue ?

**Comment by alewis001** [comment]
Thanks @hemanttanwar, I'll give it a try ASAP and let you know.

**Comment by alewis001** [comment]
Hi @hemanttanwar, #18122 is fixed at least in my testing. Thank you again.

This specific issue about a memory leak when restarting the client is still present in 7.0.1; however, I can see how you may consider that lower priority as it's maybe an unusual thing to do to keep restarting the client every 30s. The important one for us was #18122 and that has been resolved now so we no longer need to do the restart loop. 

Thanks again and pass my thanks on to the team.

**Comment by hemanttanwar** [comment]
@alewis001 I appreciate you working with our library. 
Also If you feel like you can contribute to our library in terms of documentation, fixes etc [Contributing guide](https://github.com/Azure/azure-sdk-for-java/blob/master/CONTRIBUTING.md) .
I will close this ticket now.
