### ISSUE TITLE
Secrets from "my personal secret store" are not resolved when using ARM templates

### ISSUE THREAD

**Issue by ghost** [Azure/azure-sdk-for-java#1830]
I am using the [sample code](https://github.com/Azure-Samples/resources-java-deploy-using-arm-template-with-progress/blob/master/src/main/java/com/microsoft/azure/management/resources/samples/DeployUsingARMTemplateWithProgress.java) in my application.

My template looks like:
{
  "$schema": "https://schema.management.azure.com/schemas/2015-01-01/deploymentTemplate.json",
  "contentVersion": "1.0.0.0",
  "parameters": {
    "SuperSecretParam": {
      "type": "securestring",
      "defaultValue": "[[[supersecretparam]]"
    }
  ....

"supersecretparam" is a secret in my personal secret store and when used with powershell it resolves itself but when using the JavaSDK, the string "[[[supersecretparam]]" is used literally and is not resolved and gives me the following error:
{
	"status": "Failed",
	"error": {
		"code": "ResourceOperationFailure",
		"message": "The resource operation completed with terminal provisioning state 'Failed'.",
		"details": [{
				"code": "InvalidParameter",
				"message": "The supplied password must be between 8-123 characters long and must satisfy at least 3 of password complexity requirements from the following: \r\n1) Contains an uppercase character\r\n2) Contains a lowercase character\r\n3) Contains a numeric digit\r\n4) Contains a special character."
			}
		]
	}
}

I am pretty sure that my ARM template file is fine because it works when used with the powershell SDK. Any ideas?

**Comment by martinsawicki** [comment]
let's understand how PS does this exactly.
