### ISSUE TITLE
AzureCliCredentials missing

### ISSUE THREAD

**Issue by praneetloke** [Azure/azure-sdk-for-java#1832]
According to [AUTH](https://github.com/Azure/azure-sdk-for-java/blob/master/AUTH.md), there is a class called `AzureCliCredentials` but I can't find it even in the latest version `1.1.2`. In fact, the whole package `com.microsoft.azure.credentials` is missing. Is there another library that provides this? I am trying to use the Azure CLI way of authenticating with a KeyVault. I hope I am not missing something obvious but I scoured the dependencies for the samples and some of the modules here and I can't find that class anywhere.

EDIT: Corrected the class name.

**Comment by jianghaolu** [comment]
You can find them in https://github.com/azure/autorest-clientruntime-for-java.

**Comment by praneetloke** [comment]
@jianghaolu thanks for that. That did it. I had to include all three package from the link you gave me, to be able to use `AzureCliCredentials`.
