### ISSUE TITLE
What is the correct way to list blobs and containers

### ISSUE THREAD

**Issue by ihudedi** [Azure/azure-sdk-for-java#18337]
Hi,
There are many option to list blobs and list container via
blobServiceClient.listBlobContainers.iterator/foreach/iteratorbypage
and
blobContainerClient.listBlobs().iterator/foreach/iteratorbypage
In case I want all of then in a loop. does iterator fetch all items or he brings page by page ( is the same functonlity for foreach)
I would like to get all items with less memory.
If one method fetch only the first page and in a loop and the other fetch all items.
I saw many examples in the sdk ( for,foreach,iterator,iteratorbypage,stream,streambypage.
Thanks,
Itay

**Comment by ihudedi** [comment]
Hi @rickle-msft 
Could you please help?
Thanks,
Itay

**Comment by gapra-msft** [comment]
Hi @ihudedi 

Thank you for question. 

The PagedIterable type was designed to lazily fetch pages as needed.

**Comment by ihudedi** [comment]
Hi @gapra-msft 
Thanks a lot,
Itay

**Comment by gapra-msft** [comment]
@ihudedi I believe your question has been answered so I will go ahead and close this issue. Please feel free to reopen this issue or open another one in case you have more questions and we'd be happy to help!
