### ISSUE TITLE
[FEATURE REQ] Configurable Timeout or Shorter Timeout Option for Event Hub

### ISSUE THREAD

**Issue by kacheng2018** [Azure/azure-sdk-for-java#18342]
The feature request is related to a problem the customer encountered. Event Hub triggered an exception during failing to receive event hub messages, connection closed after a 30 mins timeout which is too long. The customer expected a faster recovery time by providing a shorter timeout duration option (e.g. 5mins) or providing a configurable timeout duration. 

https://github.com/Azure/azure-sdk-for-java/blob/master/sdk/eventhubs/microsoft-azure-eventhubs/src/main/java/com/microsoft/azure/eventhubs/EventHubClient.java

**Comment by JamesBirdsall** [comment]
Depending on how you are creating the EventHubClient, you can set the operation timeout via ConnectionStringBuilder or EventHubClientOptions, but the default timeout is one minute. What operation was the customer doing when this 30-minute delay occurred?
