### ISSUE TITLE
[FEATURE REQ] EventHub AMQP Token refresh recovery

### ISSUE THREAD

**Issue by kacheng2018** [Azure/azure-sdk-for-java#18343]
To follow-up on the problem the customer encountered (github issue: https://github.com/Azure/azure-sdk-for-java/issues/17810), the client token credential failed in class com.azure.core.amqp.implementation.ActiveClientTokenManager. As the credential is inheritedly managed by SDK, the SDK should provide a mechanism to help recovering the failure by catching the exception and renew/refresh the required token.

**Comment by conniey** [comment]
We have logic to retry an exception when it is retriable. The error message in the stack is:

> Error occurred while refreshing token that is not retriable.

The non-retriable error being that the ReactorConnection is closed. It's fruitless to retry on a closed connection. The connection has to be reopened. The EventProcessorClient should be reopening the connection when it is closed.
