### ISSUE TITLE
VirtualMachine ID field not consistent

### ISSUE THREAD

**Issue by albuch** [Azure/azure-sdk-for-java#1835]
ID references to VMs at NetworkInterfaces (`com.microsoft.azure.management.network.NetworkInterface`) are not equal to the VirtualMachine IDs (`com.microsoft.azure.management.compute.VirtualMachine`). 
The Resource group part of the ID is sometimes capitalized and sometimes not.
E.g:
`virtualMachine.getId()`:  /subscriptions/xxxxxxxxxx/resourceGroups/RESOURCE_GROUP_NAME/providers/Microsoft.Compute/virtualMachines/vm_name
`networkInterface.getVirtualMachineId()`: /subscriptions/xxxxxxxxxx/resourceGroups/resource_group_name/providers/Microsoft.Compute/virtualMachines/vm_name

Equality is given for some NICs/VMs and not for others.

**Comment by anuchandy** [comment]
This seems the service side issue, sdk is not changing the case in the client side. 

Related issue https://github.com/Azure/azure-sdk-for-java/issues/1708

**Comment by albuch** [comment]
Another related issue is #1508 where a proposal is mentioned to transform to lower case in the SDK. I guess services won't be able to fix this anywhere soon.

**Comment by martinsawicki** [comment]
Yes, per Azure RM design guidelines (which govern the REST API across Azure services), the resource ID is case-insensitive , so strictly there isn't anything preventing Azure service providers from returning resource IDs in an arbitrary casing format. Therefore the SDK APIs may present it in different casings as well, as returned by the service.
With this in mind, equality comparisons on resource IDs should be done with the igoreCase option.
Issue https://github.com/Azure/azure-sdk-for-java/issues/1508 is tracking the potential To-Do for the SDK side to consider lowercasing them always, but that requires some thought as well, wrt to unintended consequences (such as: setting the user expectation that direct equality comparisons between resource IDs should always work - this is a risk, if that's not a requirement followed by Azure services themselves)

**Comment by albuch** [comment]
@martinsawicki thanks for elaborating on this. However I don't follow your argument.

First of all the user expectation is that identifiers of the same resource at different services of the same API are identical. So as long as I don't know the reasoning behind the decision I have to assume the Azure RM design guidelines don't take user experience into consideration here yet and should be fixed accordingly. I see that this is not in the scope of this project. Are the guidelines publicly available? Or can you forward the feedback to the Governance team?

Secondly, if the guidelines state that the identifier has to be treated case-insensitve, then every service should not only be allowed to return the ID in any case format but MUST consume the ID in any case format as well. 
If not it is a bug in the upstream service which should be reported and be fixed, no?
So my proposal is: transform to lowercase in the SDK, run contract, integration or end-to-end tests with a snapshot version and report any breaking changes to the upstream service projects. Is this a feasible approach?
