### ISSUE TITLE
[FEATURE REQ] Does the Azure KeyVault starter support authenticate using certificate?

### ISSUE THREAD

**Issue by jainath23** [Azure/azure-sdk-for-java#18352]
I have used the application.properties to connect Azure Key Vault:
**azure.keyvault:
        enabled: true
      token-acquire-timeout-seconds: 60
      uri: https://*****.vault.azure.net/
      client-id: 'put dev client id here'
      client-key: 'put dev client key here'
      secret.keys: datamart-datasource-url,datamart-datasource-username,datamart-datasource-password**

But, we have changed our requirements. _**Currently, we want to connect AKV using Client-Certificate instead of Client-Key**_.

What is the solution to connect AKV using Certificate???

Note:- You can play with Certificate in any format ( like Base64String or etc.) to connect AKV using SpringBoot property (Application.properties).

**Comment by backwind1233** [comment]
Hey @jainath23 , did you used  "[azure-spring-boot-starter-keyvault-secrets](https://github.com/Azure/azure-sdk-for-java/tree/master/sdk/spring/azure-spring-boot-starter-keyvault-secrets)" to connect Azure Key Vault?

**Comment by saragluna** [comment]
Hi @jainath23, we do support using a certificate to connect Azure Key Vault in our Spring Boot starter, as you can see the code here: 

https://github.com/Azure/azure-sdk-for-java/blob/master/sdk/spring/azure-spring-boot/src/main/java/com/azure/spring/keyvault/KeyVaultEnvironmentPostProcessorHelper.java#L159

But it's not pointed out in the README file, we will create a PR to add such description.

**Comment by jainath23** [comment]
I have posted my implementation as suggested over here:
https://stackoverflow.com/questions/65438251/connect-azure-key-vault-with-certificate-using-springboots-application-properti/65808524#65808524
