### ISSUE TITLE
Synapse Accesscontrol Readme issues

### ISSUE THREAD

**Issue by hongli750210** [Azure/azure-sdk-for-java#18367]
1.
Section [link:](https://github.com/Azure/azure-sdk-for-java/tree/master/sdk/synapse/azure-analytics-synapse-accesscontrol#prerequisites)
![image](https://user-images.githubusercontent.com/74638143/103130454-bc89ea00-46d7-11eb-8004-6eff59325e62.png)
Suggestion: 
1 Add [jdk]: https://docs.microsoft.com/en-us/azure/developer/java/fundamentals/?view=azure-java-stable
2 Add [azure_sub] : https://azure.microsoft.com/en-us/free/

@scottaddie , @joshfree , @jameszliao-msft , @lmazuel  for notification.

**Comment by v-xuto** [comment]
Close this issue, due to PR https://github.com/Azure/azure-sdk-for-java/pull/20054 merged.
