### ISSUE TITLE
Synapse Monitoring Readme issues

### ISSUE THREAD

**Issue by hongli750210** [Azure/azure-sdk-for-java#18364]
1.
Section[ link:](https://github.com/Azure/azure-sdk-for-java/tree/master/sdk/synapse/azure-analytics-synapse-monitoring#prerequisites)
![image](https://user-images.githubusercontent.com/74638143/103130140-6bc5c180-46d6-11eb-988e-b4f69cec4a95.png)
Suggestion: 
1 Add [jdk]: https://docs.microsoft.com/en-us/azure/developer/java/fundamentals/?view=azure-java-stable
2 Add [azure_sub] : https://azure.microsoft.com/en-us/free/

@scottaddie , @joshfree , @jameszliao-msft , @lmazuel  for notification.

**Comment by v-xuto** [comment]
Closed this issue, due to PR https://github.com/Azure/azure-sdk-for-java/pull/20054 merged.
