### ISSUE TITLE
Synapse Spark Readme and Samples issues

### ISSUE THREAD

**Issue by hongli750210** [Azure/azure-sdk-for-java#18368]
1.
Section [link:](https://github.com/Azure/azure-sdk-for-java/tree/master/sdk/synapse/azure-analytics-synapse-spark#prerequisites)
![image](https://user-images.githubusercontent.com/74638143/103130601-61a4c280-46d8-11eb-9bd3-009bff1f2b1a.png)
Suggestion: 
1)Add [jdk]: https://docs.microsoft.com/en-us/azure/developer/java/fundamentals/?view=azure-java-stable
2)Add [azure_sub] : https://azure.microsoft.com/en-us/free/

2.
Section [link:](https://github.com/Azure/azure-sdk-for-java/tree/master/sdk/synapse/azure-analytics-synapse-spark#async-api)
![image](https://user-images.githubusercontent.com/74638143/103130565-2c987000-46d8-11eb-9e9e-fbfd296b9862.png)
1)Reason:
Click it has no response.
Suggestion:
Change to  https://github.com/Azure/azure-sdk-for-java/tree/master/sdk/synapse/azure-analytics-synapse-spark#create-a-spark-job-asynchronously

2)Remove it, because there is no corresponding code part.

3)Reason:
Click it has no response.
Suggestion:
Change to https://github.com/Azure/azure-sdk-for-java/tree/master/sdk/synapse/azure-analytics-synapse-spark#cancel-a-spark-batch-job-asynchronously

3.
Section [link1](https://github.com/Azure/azure-sdk-for-java/blob/master/sdk/synapse/azure-analytics-synapse-spark/src/samples/java/com/azure/analytics/synapse/spark/HelloWorld.java#L33), [link2](https://github.com/Azure/azure-sdk-for-java/blob/master/sdk/synapse/azure-analytics-synapse-spark/src/samples/java/com/azure/analytics/synapse/spark/HelloWorld.java#L39), [link3](https://github.com/Azure/azure-sdk-for-java/blob/master/sdk/synapse/azure-analytics-synapse-spark/src/samples/java/com/azure/analytics/synapse/spark/HelloWorldAsync.java#L32), [link4:](https://github.com/Azure/azure-sdk-for-java/blob/master/sdk/synapse/azure-analytics-synapse-spark/src/samples/java/com/azure/analytics/synapse/spark/HelloWorldAsync.java#L38)
![image](https://user-images.githubusercontent.com/74638143/103131732-df6acd00-46dc-11eb-9d22-8d2d2601c44d.png)
Reason:
No found [wordcount.jar] and [shakespeare.txt] in resource files
Suggestion:
1)Changne to
```
String.format("abfss://%s@%s.dfs.core.windows.net/%s/%s", fileSystem, storageAccount,"<your-batch-job-path>","<your-batch-job-file>")
```
2)Change to 
```
String.format("abfss://%s@%s.dfs.core.windows.net/%s/%s", fileSystem, storageAccount,"<your-batch-job-path>","<your-batch-job-param-file>")
```
3)Change to 
```
String.format("abfss://%s@%s.dfs.core.windows.net/%s/", fileSystem, storageAccount,"<your-batch-job-result-path>")
```

@scottaddie , @joshfree , @jameszliao-msft , @lmazuel for notification.

**Comment by v-xuto** [comment]
Close this issue, due to PR https://github.com/Azure/azure-sdk-for-java/pull/20054 merged.
