### ISSUE TITLE
Synapse Artifacts Readme issues

### ISSUE THREAD

**Issue by hongli750210** [Azure/azure-sdk-for-java#18366]
1.
Section [link:](https://github.com/Azure/azure-sdk-for-java/tree/master/sdk/synapse/azure-analytics-synapse-artifacts#prerequisites)
![image](https://user-images.githubusercontent.com/74638143/103130375-6c128c80-46d7-11eb-8406-d5662aa9c024.png)
Suggestion: 
1 Add [jdk]: https://docs.microsoft.com/en-us/azure/developer/java/fundamentals/?view=azure-java-stable
2 Add [azure_sub] : https://azure.microsoft.com/en-us/free/

@scottaddie , @joshfree , @jameszliao-msft , @lmazuel for notification.

**Comment by v-xuto** [comment]
Closed this issue, due to PR https://github.com/Azure/azure-sdk-for-java/pull/20054 merged.
