### ISSUE TITLE
[BUG] When using ClientCertificateCredential to connect to azure inputstream isn't closed used by the pfx file

### ISSUE THREAD

**Issue by ihudedi** [Azure/azure-sdk-for-java#18369]
Hi,
When using ClientCertificateCredential  to connect to azure.
After getting the certificate and public/private key form the fix file
The application doesn't close the stream,
See identityClient -> getCertificateBytes
      identityClient  -> getCertificateInputStream
Should close the stream after getting all results.
Thanks,
Itay

**Comment by ihudedi** [comment]
Hi @rickle-msft 
Are you aware of this issue?
Thanks,
Itay

**Comment by rickle-msft** [comment]
Hey, @ihudedi I was not aware of it. @g2vinay can help you out more with the identity package.

**Comment by g2vinay** [comment]
@ihudedi  Thanks for reporting this issue.
Investigating this and will add the fix as needed. Will update soon.

**Comment by ihudedi** [comment]
Hi @g2vinay 
Thanks for the response.
Itay

**Comment by g2vinay** [comment]
@ihudedi 
The fix for this issue has been released.
Use the latest identity dependency in your application:

```
<dependency>
  <groupId>com.azure</groupId>
  <artifactId>azure-identity</artifactId>
  <version>1.2.5</version>
</dependency>
```

Let us know if you need any further help on this issue.
