### ISSUE TITLE
When using StorageSharedKeyCredential to connect to Azure storage is there any limit or action can take much time?

### ISSUE THREAD

**Issue by ihudedi** [Azure/azure-sdk-for-java#18376]
Hi,
I know there is an AccessToken.
In case I am using StorageSharedKeyCredential  does the accesstoken is expired or I can work with him for long time?
Thanks,
Itay

**Comment by gapra-msft** [comment]
Hi @ihudedi 

Thanks for your question. I believe the StorageSharedKeyCredential  does not expire unless you manually rotate the keys for the credential.

**Comment by ihudedi** [comment]
Hi @gapra-msft
What about other connection? Like clientsecretcredential and others?
Thanks,
Itay

**Comment by gapra-msft** [comment]
I believe for most TokenCredentials (like ClientSecretCredential), the keyvault SDK will handle regenerating a token when it has expired.

**Comment by ihudedi** [comment]
Hi @gapra-msft 
I am using ClientSecretCredential from azure-identity jar.
Did you mean to this jar?
Thanks,
Itay

**Comment by gapra-msft** [comment]
@ihudedi Ah yes sorry, I means the azure-identity library. Sorry for the confusion.

**Comment by ihudedi** [comment]
Hi @gapra-msft 
Thanks for the info,
Itay

**Comment by rickle-msft** [comment]
I am going to close this issue as it looks as though the questions have been addressed.
