### ISSUE TITLE
API to Trigger a VM Backup using Recovery Services?

### ISSUE THREAD

**Issue by renutz** [Azure/azure-sdk-for-java#1839]
Hi,

Is there a way to trigger a VM backup from an API?

I'm looking at the page:

https://portal.azure.com/#resource/subscriptions/<SUBSCRIPTIONID>/resourceGroups/<RESOURCEGROUP>/providers/Microsoft.Compute/virtualMachines/<MYVM>/backupSetting

And hitting the button "Backup Now" you have to setup "Retain Backup Till" and then OK.

I look at the Compute API and even at the preview of RecoveryServices APIs ( https://github.com/Azure/azure-sdk-for-java/pull/1824/commits/8637c17e1166d3df53fe2f9b2dd65abbeaaaa96b ) but I could not find an answer.

Also, if there is a place with the complete set of RecoveryServices APIs (assign a VM to a Vault, listing backups, backups policies, etc), it will be just great, so we could automate all backup actions on a more granular level.

Please advice.

Thanks

**Comment by anuchandy** [comment]
This is not a compute API but recovery service api. @DheerendraRathor (owning the recovery service swagger) do you have any samples showing how to consume recovery service APIs for backing up a virtual machine? The documentation here https://docs.microsoft.com/en-us/rest/api/recoveryservices/backups does not include any samples.

**Comment by vhvb1989** [comment]
Hello @renutz 

was this:  https://github.com/Azure/azure-sdk-for-java/issues/1839#issuecomment-318500980  enough for what you were trying to set up?
Do you still need help? Let me know and I would be happy to assist.

Note: As part of repository cleaning effort, this issue will be closed by **Nov 11** if no response is received from submitter and/or not further action is required.

**Comment by renutz** [comment]
No. The link to https://docs.microsoft.com/en-us/rest/api/recoveryservices/backups is not valid anymore.

Thanks

**Comment by vhvb1989** [comment]
@renutz 
yeah, please follow link: https://docs.microsoft.com/en-us/rest/api/backup/

The information to backup Azure VMs should be there.

**Comment by vhvb1989** [comment]
Hello @renutz 
Wondering if you found the information you were looking for?

**Comment by Sohil2429** [comment]
@renutz i am struggling to find how can i use recovery service and enable backup in my CM creation.. using java sdk 
Please suggest if u have something that can b useful
