### ISSUE TITLE
B2C Java Spring Boot sample compiles with errors

### ISSUE THREAD

**Issue by mrochon** [Azure/azure-sdk-for-java#18403]
**Describe the bug**
The [B2C Spring Boot sample](https://github.com/Azure/azure-sdk-for-java/tree/master/sdk/spring/azure-spring-boot-samples/azure-spring-boot-sample-active-directory-b2c-oidc) compiles with error:

`The container 'Maven Dependencies' references non existing library 'C:\Users\mrochon\.m2\repository\com\azure\spring\azure-spring-boot-starter-active-directory-b2c\3.0.0-beta.2\azure-spring-boot-starter-active-directory-b2c-3.0.0-beta.2.jar'`

***Exception or Stack Trace***
Add the exception log and stack trace if available

**To Reproduce**
Clone the repo, update application.yml and attempt to execute.

***Code Snippet***
Add the code snippet that causes the issue.

**Expected behavior**
No compile errors

**Screenshots**

**Setup (please complete the following information):**
 - OS:W10
 - IDE : VSCode
 - Version of the Library used

**Additional context**

**Information Checklist**
Kindly make sure that you have added all the following information above and checkoff the required fields otherwise we will treat the issuer as an incomplete report
- [ ] Bug Description Added
- [ ] Repro Steps Added
- [ ] Setup information Added

**Comment by yiliuTo** [comment]
Hi @mrochon , thanks for your reporting. Our sample project uses the developing version by default to follow the specification of azure-sdk-for-java repository. If you want to try the released version, please change [b2c starter version](https://github.com/Azure/azure-sdk-for-java/blob/449c000f3f90f1c1f63e264c9a2abe07b695ba05/sdk/spring/azure-spring-boot-samples/azure-spring-boot-sample-active-directory-b2c-oidc/pom.xml#L25) to 3.0.0-beta.1.
Also if you want to use our developing version, you can follow [this instructions to use the daily built version](https://github.com/Azure/azure-sdk-for-java/blob/master/CONTRIBUTING.md#dev-feed). Besides, given that we are doing a GA release of b2c starter now, so you can wait a few days for our latest version.

**Comment by saragluna** [comment]
Closing this issue now.
