### ISSUE TITLE
The complete error message is not returned when deployment status returns failure (Azure ARM template provisioning using java SDK)

### ISSUE THREAD

**Issue by sharshadh** [Azure/azure-sdk-for-java#1840]
I am trying to get the deployment status of the ARM template provisioning (java SDK) , whenever the deployment status (deployment.provisioningState()) is failed, the output response (deployment.outputs()) doesn't give the proper error detail message.
It would be helpful if we can get the complete error message, so that we can make the changes accordingly

**Comment by martinsawicki** [comment]
@sharshadh could you pls elaborate on where you get a more detailed error, that you are comparing to the SDK's output: Azure portal? CLI?

**Comment by praries880** [comment]
@sharshadh  I am closing the issue as of now... Kindly re-open it if you are still running into it.
