### ISSUE TITLE
[BUG][Azure-Idenetity] VisualStudioCacheAccessor #getUserSettings should strip comments

### ISSUE THREAD

**Issue by andxu** [Azure/azure-sdk-for-java#18419]
Since vscode settings.json supports json with comments like:
```js
{
/* key foo */
"foo":"bar" // this is a test
}
```

**Comment by andxu** [comment]
Possible fix:  VisualStudioCacheAccessor.getUserSettings
```java
mapper.configure(JsonReadFeature.ALLOW_UNESCAPED_CONTROL_CHARS.mappedFeature(), true);
        mapper.configure(JsonReadFeature.ALLOW_JAVA_COMMENTS.mappedFeature(), true);
```
BTW, the class name of VisualStudioCacheAccessor is not good, better name would be VisualStudioCodeCacheAccessor

**Comment by andxu** [comment]
#19444

**Comment by g2vinay** [comment]
@andxu 
The fix for this issue has been released.
Use the latest Identity release:
```java
<dependency>
  <groupId>com.azure</groupId>
  <artifactId>azure-identity</artifactId>
  <version>1.2.5</version>
</dependency>
```

Let us know if you need any further help on this issue.
