### ISSUE TITLE
[BUG] spring-cloud-azure-eventhubs-stream-binder:1.2.8 leads to NoSuchMethodError if used together with spring-cloud-azure-appconfiguration-config-web

### ISSUE THREAD

**Issue by saragluna** [Azure/azure-sdk-for-java#18434]
Copied from https://github.com/microsoft/spring-cloud-azure/issues/761 @ulrichwinter.

We use the following three dependencies in our maven-managed spring-boot project:

- com.microsoft.azure:spring-cloud-azure-eventhubs-stream-binder:1.2.8
- com.microsoft.azure:spring-cloud-azure-appconfiguration-config-web:1.2.7
- com.microsoft.azure:spring-cloud-azure-feature-management-web:1.2.7

After upgrading the first one to release 1.2.8, we encounter the following error during runtime, when a message is going to be sent to the eventhub:

```
java.lang.NoSuchMethodError: 'void com.azure.core.util.logging.ClientLogger.warning(java.lang.String)'
    at com.azure.core.amqp.implementation.AmqpChannelProcessor.onSubscribe(AmqpChannelProcessor.java:69)
```
For the other two depenencies, there is no 1.2.8 release available, so we must keep them on 1.2.7.

The error can be reproduced with the following complete example project:
https://github.com/ulrichwinter/azure-eventhub-demo

I were only able to avoid this error, by reverting to the 1.2.7 release.
I also tried to avoid this situation using the azure-spring-boot-bom: the mentioned dependencies above still required manually defined versions.

How can I use the released com.microsoft.azure:spring-cloud-azure-eventhubs-stream-binder:1.2.8 together with the mentioned appconfiguration and/or featuremanagement libs?

Please provide a way to declare consistently compatible dependency versions for spring-cloud-azure modules.
or:
Please provide newer releases for the mentioned spring-cloud-azure dependencies, which are compatible with the newest spring-cloud-azure-eventhubs-stream-binder release.
I also asked this question on stackoverflow:
https://stackoverflow.com/questions/65426745/how-should-spring-cloud-azure-dependencies-be-managed-in-a-spring-boot-service

**Comment by saragluna** [comment]
Thanks @ulrichwinter for reporting this, we'll look into this.

**Comment by backwind1233** [comment]
Hi @ulrichwinter , I think you need to update version of spring-cloud-azure-appconfiguration-config-web and spring-cloud-azure-feature-management-web to 1.2.8 or later to fix the issue.

**Comment by ulrichwinter** [comment]
Thank you, @backwind1233 
Both releases have been released on Mar 09, 2021. That means, this is possible only since then.
For both there is even a 1.2.9 release, but not for com.microsoft.azure:spring-cloud-azure-eventhubs-stream-binder.

Actually I would prefer having a BOM project for all the azure libs, which ensures, that the library releases from that BOM work together - as it has been done by the spring-cloud.

**Comment by backwind1233** [comment]
@ulrichwinter 
> For both there is even a 1.2.9 release, but not for com.microsoft.azure:spring-cloud-azure-eventhubs-stream-binder.

For some reasons, we changed groupId and artifactId for some projects include `spring-cloud-azure-eventhubs-stream-binder.`, check the maven [link](https://search.maven.org/artifact/com.microsoft.azure/spring-cloud-azure-eventhubs-stream-binder) and release [link](https://github.com/Azure/azure-sdk-for-java/blob/master/sdk/spring/azure-spring-cloud-autoconfigure/CHANGELOG.md#breaking-changes-1), so there is no 1.2.9 release.

 > Actually I would prefer having a BOM project for all the azure libs, which ensures, that the library releases from that BOM work together - as it has been done by the spring-cloud.

Yes, I understand your concern, we do have a bom but it only supports azure spring boot project, I will record your suggestion and talk with my PM.

**Comment by backwind1233** [comment]
this is the [PR](https://github.com/Azure/azure-sdk-for-java/pull/20284) for azure spring cloud dependencies
