### ISSUE TITLE
Publish new version of  azure-loganalytics sdk

### ISSUE THREAD

**Issue by timja** [Azure/azure-sdk-for-java#18480]
**Query/Question**
https://github.com/Azure/azure-sdk-for-java/tree/70c6d704415952130aa58c08546f9aa19bfb606e/sdk/loganalytics/microsoft-azure-loganalytics

Says to use:

```
<dependency>
    <groupId>com.microsoft.azure</groupId>
    <artifactId>azure-loganalytics</artifactId>
    <version>1.0.0-beta.2</version>
</dependency>
```

This doesn't exist

The only version published is 1.0.0-Preview-1 at https://search.maven.org/artifact/com.microsoft.azure/azure-loganalytics/1.0.0-Preview-1/jar

and that was published in October 2018, (which means dependencies will be very old

***Why is this not a Bug or a feature Request?***
A clear explanation of why is this not a bug or a feature request?

Could be a bug? Docs say to use the above version

 **Information Checklist**
 Kindly make sure that you have added all the following information above and checkoff the required fields otherwise we will treat the issuer as an incomplete report
- [x] Query Added
- [x] Setup information Added

**Comment by joshfree** [comment]
@ramthi could you please assist in routing this issue?

**Comment by joshfree** [comment]
Following up with @ramthi offline to find an owner

**Comment by timja** [comment]
@joshfree any luck? Or is there a track 2 sdk?

**Comment by srnagar** [comment]
@timja `azure-loganalytics` is an older package but we are working on a new version of the library that enables querying logs and metrics from Azure Monitor. It would be great to learn more about your use cases and also give our preview package a try (which is scheduled to release next week). Could you please share more details about your use cases for this library?

**Comment by timja** [comment]
To potentially create an implementation of https://github.com/jenkinsci/jep/blob/master/jep/210/README.adoc to store build logs, retrieve via API, and generate a URL that a user can be sent to view the logs in log analytics directly

**Comment by scottaddie** [comment]
Hey, @timja! 👋 I'm an Azure SDK PM supporting the Azure Monitor Query Track 2 SDK work. I'd love to learn more about the use case you've described above. Can you please email me at scott dot addie at microsoft.com? Maybe we can get a call set up.

**Comment by srnagar** [comment]
@timja we have a stable release of [azure-monitor-query](https://search.maven.org/artifact/com.azure/azure-monitor-query) to retrieve logs and metrics from Azure Monitor. This new library replaces azure-loganalytics. Could you please try out the new library as azure-loganalytics was still a preview and never released a stable version?
