### ISSUE TITLE
Why do I receive: Cannot update disposition with no link. ?

### ISSUE THREAD

**Issue by edwint88** [Azure/azure-sdk-for-java#18496]
**Query/Question**

More or less I am doing this: [Receive messages with a named session](https://github.com/Azure/azure-sdk-for-java/blob/master/sdk/servicebus/azure-messaging-servicebus/src/samples/java/com/azure/messaging/servicebus/ReceiveNamedSessionSample.java)

and when I use `complete` I receive the error from: [Cannot update disposition with no link](https://github.com/Azure/azure-sdk-for-java/blob/ad184d30293b2ae528809c456abf4e1a7c048fd5/sdk/servicebus/azure-messaging-servicebus/src/main/java/com/azure/messaging/servicebus/implementation/ServiceBusReceiveLinkProcessor.java#L117)

Any idea what do I do wrong?

***Why is this not a Bug or a feature Request?***
I don't know, it may be a bug

**Setup (please complete the following information if applicable):**
 - OS:   iOS
 - IDE : IntelliJ
 - Version of the Library used: azure-messaging-servicebus: 7.0.0-beta.7 
 
 **Information Checklist**
 
        ServiceBusSessionReceiverClient sessionReceiver = new ServiceBusClientBuilder()
                .connectionString(CONNECTION_STRING)
                .sessionReceiver()
                .disableAutoComplete()
                .receiveMode(ReceiveMode.PEEK_LOCK)
                .maxAutoLockRenewDuration(Duration.ofMinutes(15))
                .queueName(QUEUE_NAME)
                .buildClient();

        // A receiver is returned when a lock on the session is acquired, otherwise, it throws an exception.
        ServiceBusReceiverClient receiver = sessionReceiver.acceptSession(SESSION_ID);

        receiver.receiveMessages(10).forEach(message -> {
                    try {
                        this.processMessage(receiver, message);
                    } catch (Exception e) {
                        LOG.error(e.getMessage());
                    }
                });

        // the function used above
        private void processMessage(ServiceBusReceiverClient receiver, ServiceBusReceivedMessage message) {
            LOG.debug("Process message.");
            LOG.debug(String.format("Session: %s. Sequence #: %s. Contents: %s%n", message.getSessionId(),
                    message.getSequenceNumber(), message.getBody()));
            boolean isSuccessfullyProcessed = true;
            //... some processing
            if (isSuccessfullyProcessed) {
                LOG.debug("Message successful completed.");
                receiver.complete(message);
            } else {
                LOG.debug("Message added to Dead Letter QUEUE.");
                receiver.deadLetter(message);
            }
        }

**Comment by hemanttanwar** [comment]
Hello @edwint88  Thank you for trying our library. I see you are using `7.0.0-beta.7`,  Can you try this with out GA release library "7.0.0" and let us know if you face same issue and also add exception trace.

**Comment by edwint88** [comment]
Sadly, we cannot yet use the 7.0.0 because first we will have to update our spring boot version.

**Comment by StevenDevooght** [comment]
@edwint88 Did you manage to get this working? We have the same issue.

**Comment by edwint88** [comment]
In the end we used another client instead of `ServiceBusSessionReceiverClient` (if I remember correctly, we used the async client).

**Comment by joshfree** [comment]
@YijunXieMS can you please try the repro on the latest released version of `service bus`?
