### ISSUE TITLE
Session time out 404/100, requests are retrying twice on same region

### ISSUE THREAD

**Issue by simplynaveen20** [Azure/azure-sdk-for-java#18499]
**Describe the bug**
(In case of preferred region set) User have region A, B, C, their call    sequence (5 sec Retry on A, 5 Sec Retry on A, 5 Sec Retry on B, 5 Sec Retry on C) . Which will increase unnecessary latency

***Exception or Stack Trace***
Their call sequence should be (5 sec Retry on A,  5 Sec Retry on B, 5 Sec Retry on C)

**Comment by kushagraThapar** [comment]
This is done.
