### ISSUE TITLE
Need Java version flag in the SDK user agent

### ISSUE THREAD

**Issue by martinsawicki** [Azure/azure-sdk-for-java#1849]
so we can get better educated on issue https://github.com/Azure/azure-sdk-for-java/issues/1468

**Comment by jamesbroadhead** [comment]
After the release containing this field, how long do you intend to gather data before making a decision on #1468? 

(Context: We would like to enable `-Werror` on our build & are blocked by #1653)

**Comment by martinsawicki** [comment]
hard to say, but I think we'll be stuck with Java 7 as long as its usage remains in double digits. Now, if we find from the telemetry that Azure SDK customers buck the trend and use Java 7 much less than the general population, that could be a factor in favor of switching to Java 8 sooner than that.

**Comment by martinsawicki** [comment]
the user agent now has java version data (as of v1.2) so closing this
