### ISSUE TITLE
[FEATURE REQ] Add support for latest OpenTelemetry versions to Azure Monitor OpenTelemetry Exporter client library for Java

### ISSUE THREAD

**Issue by Storm-cat** [Azure/azure-sdk-for-java#18512]
Currently [Azure Monitor OpenTelemetry Exporter client library for Java](https://docs.microsoft.com/en-us/java/api/overview/azure/opentelemetry-exporters-azuremonitor-readme?view=azure-java-preview) cannot be used with Spring Cloud Sleuth due to OpenTelemetry version problem.

As described in this [SO answer](https://stackoverflow.com/questions/65407625/exporting-spring-cloud-sleuth-spans-automatically-using-azure-monitor-openteleme), Sleuth supports OpenTelemetry since version 3.0.0-M5, which uses OpenTelemetry version 0.10. However opentelemetry-exporters-azuremonitor:1.0.0-beta.1 depends on OpenTelemetry version 0.8.0.

Because of this Azure Monitor OpenTelemetry Exporter client library for Java cannot be used with Spring Cloud Sleuth. The solution would be to update Azure Monitor OpenTelemetry Exporter client library for Java to depend on OpenTelemetry 0.10 or newer.

**Comment by jonatan-ivanov** [comment]
Fyi, the current version [as of today is 0.13.1](https://github.com/open-telemetry/opentelemetry-java/releases/).

**Comment by joshfree** [comment]
Thanks for filing this @Storm-cat.  We'll patch this as part of our next regular monthly release cycle.

**Comment by samvaity** [comment]
Hey @jonatan-ivanov, this is already in progress,  https://github.com/Azure/azure-sdk-for-java/pull/18534.

**Comment by jonatan-ivanov** [comment]
@samvaity The target is moving, now the latest is [0.14.1](https://github.com/open-telemetry/opentelemetry-java/releases/).

**Comment by jonatan-ivanov** [comment]
@Storm-cat I released `spring-cloud-sleuth-otel:1.0.0-M3` which also supports OTel 0.14.1: https://github.com/spring-cloud-incubator/spring-cloud-sleuth-otel/releases/tag/v1.0.0-M3

**Comment by Storm-cat** [comment]
It seems that [Azure Monitor OpenTelemetry Exporter client library for Java](https://docs.microsoft.com/en-us/java/api/overview/azure/opentelemetry-exporters-azuremonitor-readme?view=azure-java-preview) still [depends on OpenTelemetry version 0.8.0](https://search.maven.org/artifact/com.azure/opentelemetry-exporters-azuremonitor/1.0.0-beta.1/jar). Is there any information when this will be updated? I assume I have to wait for the next release?

**Comment by samvaity** [comment]
@Storm-cat yes, the next release of  Azure Monitor OpenTelemetry Exporter client library for Java should have the updated dependency for OpenTelemetry 0.14.1.

The next release should be out this week.
