### ISSUE TITLE
[QUERY] [Event Hub] Support for IoT Hub?

### ISSUE THREAD

**Issue by tmb-twx** [Azure/azure-sdk-for-java#18514]
**Query/Question**
The documentation IoT Hub failover https://docs.microsoft.com/en-us/azure/iot-hub/iot-hub-ha-dr has the following text:

> The Event Hub-compatible name and endpoint of the IoT Hub built-in Events endpoint change after failover. When receiving telemetry messages from the built-in endpoint using either the Event Hub client or event processor host, you should use the IoT hub connection string to establish the connection.

I am unable to find any examples of how to configure the java EventProcessorClient with the IoT Hub connection string.   If I just try to use the IoT Hub Owner connection string then I get an exception like this:
`Exception in thread "main" java.lang.IllegalArgumentException: Illegal connection string parameter name: HostName
        at com.azure.core.amqp.implementation.ConnectionStringProperties.<init>(ConnectionStringProperties.java:98)
        at com.azure.messaging.eventhubs.EventHubClientBuilder.connectionString(EventHubClientBuilder.java:185)
        at com.azure.messaging.eventhubs.EventProcessorClientBuilder.connectionString(EventProcessorClientBuilder.java:124)
        at test.Subscriber.main(Subscriber.java:55)`

Is using the IoT Hub connection string supported?  If so, is there an example of how to configure it?

***Why is this not a Bug or a feature Request?***
It may turn into a feature request.

**Setup (please complete the following information if applicable):**
 - OS: Windows,  Linux
 - IDE: Visual Studio Code
 - Version of the Library used: 5.3.1
 
 **Information Checklist**
 Kindly make sure that you have added all the following information above and checkoff the required fields otherwise we will treat the issuer as an incomplete report
- [ ] Query Added
- [ ] Setup information Added

**Comment by joshfree** [comment]
@srnagar could you please take a look?

**Comment by tmb-twx** [comment]
Any updates on this?

**Comment by srnagar** [comment]
Hi @tmb-twx, thank you for your query.  The Java Event Hubs SDK currently does not support using IoT connection string. We're looking into supporting this in future releases. We'll keep you posted on any updates.
