### ISSUE TITLE
[Service Bus] : [BUG] : delete a subscription isn't sync

### ISSUE THREAD

**Issue by algra4** [Azure/azure-sdk-for-java#18536]
**Describe the bug**
The removal of a subscription is not synchronize. 

***Exception or Stack Trace***
No stack

**To Reproduce**
Call the method

1. ```deleteSubscription(..., ...)```
2. ```getSubscription(..., ...)```

Subscription always present

***Code Snippet***
```java
    public void deleteSubscription(String topicName, String subscriptionName) {
        asyncClient.deleteSubscription(topicName, subscriptionName);
    }
```

Should be : 
```java
    public void deleteSubscription(String topicName, String subscriptionName) {
        asyncClient.deleteSubscription(topicName, subscriptionName).block();
    }
```

**Expected behavior**
The subscription should be deleted immediately

**Screenshots**

**Setup (please complete the following information):**
 - OS: Windows
 - IDE : IntelliJ
 - azure-messaging-servicebus:com.azure:7.0.0

**Additional context**

**Information Checklist**
Kindly make sure that you have added all the following information above and checkoff the required fields otherwise we will treat the issuer as an incomplete report
- [x] Bug Description Added
- [x] Repro Steps Added
- [x] Setup information Added

**Comment by hemanttanwar** [comment]
Hello @algra4 , Thank you for opening the issue. Looks like you are using `ServiceBusAdministrationAsyncClient` . We are using Reactor Programming model for Async Client and  you will need to use `.block()` or  `subscribe()` to execute the call. You can go through this blog which explain this in bit more detail https://devblogs.microsoft.com/azure-sdk/async-programming-with-project-reactor/#using-async-apis-in-the-new-azure-sdk-for-java

If you like to use  Sync client instead , Here is an example of how sync client can be created

```java
// Create a administrator client using connection string.
        ServiceBusAdministrationClient client = new ServiceBusAdministrationClientBuilder()
            .connectionString(connectionString)
            .buildClient();
```

**Comment by algra4** [comment]
Thank for you response @hemanttanwar 👍 

But it's normal that in  `ServiceBusAdministrationClient` class, all methods you call the `.block()` method after you call the `asyncClient`.

Expect in the method `deleteSubscription(String topicName, String subscriptionName)` [(link to the method)](https://github.com/hemanttanwar/azure-sdk-for-java/blob/d3ae61308e2e5eaf8a7efe64187b84f0b700ee0b/sdk/servicebus/azure-messaging-servicebus/src/main/java/com/azure/messaging/servicebus/administration/ServiceBusAdministrationClient.java#L423-L426).

For this reason, I think it's a "bug" 😄

**Comment by hemanttanwar** [comment]
@algra4 Thank you for clarifying  information.  You are right . We will fix it soon  and release it in a week.

**Comment by hemanttanwar** [comment]
This fix is now released . You can download it from here https://search.maven.org/artifact/com.azure/azure-messaging-servicebus .
Closing this issue now.
