### ISSUE TITLE
The "Overview" section for Key Vault is different between Stable and Preview ToCs

### ISSUE THREAD

**Issue by vcolin7** [Azure/azure-sdk-for-java#18548]
Found via #17311.

Here is a link to the [Key Vault Overview](https://docs.microsoft.com/en-us/java/api/overview/azure/keyvault?view=azure-java-preview) in the Preview ToC. It only shows links to the Key Vault sub-packages when instead it should show a more complete page like the one on the second screenshot below.

![image](https://user-images.githubusercontent.com/5799331/104250035-4c4aca80-5432-11eb-94f0-4ba978eef89c.png)

However, trying to switch to the Stable ToC version of [the same section](https://docs.microsoft.com/en-us/java/api/overview/azure/keyvault?view=azure-java-stable) leads to a way more complete page and the table of contents on the left dissapears.

![image](https://user-images.githubusercontent.com/5799331/104249919-02fa7b00-5432-11eb-950d-efb42be158e4.png)

Additionally, if you are looking at a different section like the [Keys Overview](https://docs.microsoft.com/en-us/java/api/overview/azure/security-keyvault-keys-readme?view=azure-java-stable) in the Stable ToC and then click overview, you are led to [a broken link (404)](https://docs.microsoft.com/en-us/java/api/azure/~/docs-ref-services/keyvault.md?view=azure-java-stable).

![image](https://user-images.githubusercontent.com/5799331/104250112-874cfe00-5432-11eb-9e72-3acd52a4a0ac.png)

**Comment by kurtzeborn** [comment]
This is an issue that library owners should be able to address by following the documentation we've created for these types of issues [here](https://dev.azure.com/azure-sdk/internal/_wiki/wikis/internal.wiki/283/Docs.MS-Primer?anchor=how-do-i-actually-update-the-toc%3F).

**Comment by sima-zhu** [comment]
Keyvault resource manager is having GA version ahead of preview. So do we still need the preview Resource Manager show up in toc?

If you definitely need the preview version, please update the preview section under package.json. 
In the section here: https://github.com/Azure/azure-docs-sdk-java/blob/master/package.json#L1071

**Comment by sima-zhu** [comment]
I have been pushed the fix to keyvault readme. The issue got resolved. Please check

**Comment by vcolin7** [comment]
When will this be reflected in Microsoft Docs? I still see a disparity between the following links:

- [Stable](https://docs.microsoft.com/en-us/java/api/overview/azure/keyvault?view=azure-java-stable)
- [Preview](https://docs.microsoft.com/en-us/java/api/overview/azure/keyvault?view=azure-java-preview)

**Comment by alzimmermsft** [comment]
@vcolin7 these look to be the same now, can you verify

**Comment by vcolin7** [comment]
> @vcolin7 these look to be the same now, can you verify

Correct @alzimmermsft, thanks for checking!
