### ISSUE TITLE
[QUERY] Determine length (count of messages) in subscription

### ISSUE THREAD

**Issue by lordarcy** [Azure/azure-sdk-for-java#18546]
**Query/Question**
I have a program that is polling a subscription using a message receiver and the receive method to request new messages. Is there a way to monitor the length of the subscription so that a separate application can monitor the message count and see if everything is working.

***Why is this not a Bug or a feature Request?***
I don't know if the function already exists so I'm not making a feature request yet.

**Setup (please complete the following information if applicable):**
 - OS: RHEL 8.x
 - IDE : IntelliJ
 - 3.5.1
 
 **Information Checklist**
 Kindly make sure that you have added all the following information above and checkoff the required fields otherwise we will treat the issuer as an incomplete report
- [X] Query Added
- [X] Setup information Added

**Comment by joshfree** [comment]
@hemanttanwar could you please follow up?

**Comment by hemanttanwar** [comment]
@lordarcy Thank you for trying our library. Appreciate it.

You can use `ServiceBusAdministrationClient` to get count of messages.  

```java
        // Create a administrator client using connection string.
        ServiceBusAdministrationClient client = new ServiceBusAdministrationClientBuilder()
            .connectionString(connectionString)
            .buildClient();

        SubscriptionRuntimeProperties properties = client.getSubscriptionRuntimeProperties("topicName", "subscriptionName");        
        System.out.printf("Total message count: [%d].%n", properties.getTotalMessageCount()));
```
`ServiceBusAdministrationClient`  : This is normally used CRUD operation on the resources like subscriber/queue.
If you need additional information , please let us know.

**Comment by hemanttanwar** [comment]
@lordarcy Closing this issue. If you have further question, you can reopen this or a new issue.
