### ISSUE TITLE
Fixed failed aggregate-report link issue

### ISSUE THREAD

**Issue by sima-zhu** [Azure/azure-sdk-for-java#18566]
https://dev.azure.com/azure-sdk/internal/_build/results?buildId=682713&view=logs&j=ad792ccc-30b2-59a1-5b53-546a79d88828&t=620c66ab-f28e-5b0d-c90a-9b2fc3874d5d

**Comment by joshfree** [comment]
Related https://github.com/Azure/azure-sdk-for-java/commit/81ba0b99c32357fe11a029e97a9124146ed07dd5

**Comment by sima-zhu** [comment]
@joshfree The aggregate-report failed at some external links in readme. I do not have full context on which is the replacement. Could you assign a library owner to fix this?

**Comment by kurtzeborn** [comment]
Flipping back to "client" per Sima's comment/request.

**Comment by sima-zhu** [comment]
The previous one got fixed. Please check [here](https://dev.azure.com/azure-sdk/internal/_build/results?buildId=700956&view=logs&j=ad792ccc-30b2-59a1-5b53-546a79d88828&t=4b67ea85-ffb0-595b-22a1-50fb213564d1) for the recent failure.

**Comment by joshfree** [comment]
@conniey please verify / close
