### ISSUE TITLE
[FEATURE REQ] Cosmos: Allow accessing plain byte array / JSON string when dealing with query results.

### ISSUE THREAD

**Issue by henrikp-visma** [Azure/azure-sdk-for-java#18565]
**Is your feature request related to a problem? Please describe.**

As far as I understand, currently the only way to handle the query responses is to use Jackson and JavaBeans. This is not ideal, when the application might have more advanced/faster deserialisation options. These could be allowed with no overhead, if the response would allow accessing the underlying response body as a string or byte array.

In our case, we are using SDK from Scala, where there are several alternative JSON deserialisation options. 

**Describe the solution you'd like**

Allow direct access to the underlying response JSON string / byte array.

**Describe alternatives you've considered**

JavaBeans and POJOs - not ideal for Scala as they are inherently mutable.

**Information Checklist**
Kindly make sure that you have added all the following information above and checkoff the required fields otherwise we will treat the issuer as an incomplete report
- [X] Description Added
- [X] Expected solution specified

**Comment by kushagraThapar** [comment]
@mbhaskar  - please take a look at this issue.

**Comment by mpartan** [comment]
Any update on this? 😃 @mbhaskar @kushagraThapar

**Comment by kushagraThapar** [comment]
@mpartan  - what is the SDK that you are using ?

**Comment by mpartan** [comment]
@kushagraThapar 

I'm experiencing similar issues with azure-cosmos 4.10, I guess Cosmos is mentioned in the title but not in the description.

**Comment by kushagraThapar** [comment]
@mpartan - I see, @mbhaskar  - do we have this in our plan for exposing byte array results for query execution ?

**Comment by mbhaskar** [comment]
This is in the backlog, but not planned at the moment. Will update the incident if this changes.

**Comment by mpartan** [comment]
I guess this is still open and not planned? Just makes it a bit more hard to use the library which is really useful but if you don't want to use POJOs 🤔

**Comment by FabianMeiswinkel** [comment]
It is possible to use ObjectNode (com.fasterxml.jackson.databind.node.ObjectNode) thought - wouldn't that address the request above? 

cosmosAsyncContainer.queryItems(sqlSpec, options, classOf[ObjectNode])

**Comment by mpartan** [comment]
That actually works like a charm for this use case. Thanks a lot @FabianMeiswinkel 😃
