### ISSUE TITLE
Move CI to Linux once Cosmos Emulator for Linux is ready. (hive and hadoop are not windows friendly)

### ISSUE THREAD

**Issue by moderakh** [Azure/azure-sdk-for-java#18576]
Some spark framework (hive and hadoop) are not windows friendly, require additional setup, etc.

Ideally we should move to Linux for spark CI and use Cosmos Linux Emulator 
@milismsft FYI

**Comment by kushagraThapar** [comment]
Updating the issue - still in our backlog.

**Comment by kushagraThapar** [comment]
We have fixed those issues and no longer plan to move to linux for emulator.
