### ISSUE TITLE
appServicePlans().list() cannot list Linux AppServicePlan

### ISSUE THREAD

**Issue by Eskibear** [Azure/azure-sdk-for-java#1861]
`azure.appServices().appServicePlans().list();`
~~~Above API can only list AppService whose operationSystem is Windows.~~~
EDIT: Above API can only list all AppService but operationSystem returns  `Windows` for both linux and windows AppService

Currently only the following API returns both Windows & Linux AppService.
`azure.appServices().appServicePlans().listByResourceGroup(resourceGroupName);`


~~~BTW, I think same issue might also exists in WebApp, for the moment I use `webapps().inner()` as a workaround.~~~
EDIT: `webapps().inner().list()` can list all webapps.

**Comment by Eskibear** [comment]
In fact I find it DOES list Linux AppService, but `.operatingSystem()` wrongly returns `windows`. I have a filter  `filter(item -> item.operatingSystem().equals(OperatingSystem.LINUX)`, and that's why I missed all those linux AppService before.

Here the API returns `WINDOWS`.
![image](https://user-images.githubusercontent.com/2351748/29169092-c88319de-7e04-11e7-955a-0a6e3c0d30b6.png)

It's actually 'LINUX'.
![image](https://user-images.githubusercontent.com/2351748/29169189-443aa0d8-7e05-11e7-882a-26969a9e3c14.png)

**Comment by martinsawicki** [comment]
@jianghaolu us or the service?

**Comment by Eskibear** [comment]
thanks, `v1.2.1` works well.
