### ISSUE TITLE
[QUERY] azure-spring-data-cosmos show/print SQL query string to logs

### ISSUE THREAD

**Issue by JV-TMCZ** [Azure/azure-sdk-for-java#18639]
**Query/Question**
It would really help to be able to check real query which was processed. The final query string is constructed from and by several ways... findBy*, findFirst, Pageable, offset limit, non-trivial type handling (datetime: string vs. epochtime, ...), ...  
During debuging and investigating any problems (and to be honest during few days I faced several bugs... ) would be really helpful to be able to copy query string generated and try to execute it in CosmosDB explorer. 
Thank you. Have a nice day.

***Why is this not a Bug or a feature Request?***
- It should be possible to flag it somewhere, unfortunatelly the usual flags does not works (most of them is for hibernate or deprecated). I probably just do not know the proper flag. 
- Another approach would be to raise specific log level... unfortunately I do  not know which one. 
- Or should it be rather in (Custom) ResponseDiagnosticsProcessor ? if so - could you initiate discussion with target team?

**Setup (please complete the following information if applicable):**
any non trivial "processed" query like:
```
   Optional<Entity> findFirstByRoomIdAndTimestampNotNullOrderBy_tsDesc(String roomId);
```

**Comment by kushagraThapar** [comment]
@mbhaskar  - I believe we have seen this request in the past, can you please help here ?
