### ISSUE TITLE
[FEATURE REQUEST] Storage File share Upload API should support data upload bigger than 4 MB - Chunked Upload

### ISSUE THREAD

**Issue by g2vinay** [Azure/azure-sdk-for-java#18643]
**Describe the bug**
Storage File share Upload API doesn't support data upload bigger than 4 MB,

**Excpetion**
Exception in thread "main" com.azure.storage.file.share.models.ShareStorageException: Status code 413, "﻿<?xml version="1.0" encoding="utf-8"?><Error><Code>RequestBodyTooLarge</Code><Message>The request body is too large and exceeds the maximum permissible limit.

**To Reproduce**
Upload data > 4 MB with Share File Client's upload(Flux<ByteBuffer> data, long length) API.

**Expected behavior**
Should support uploading data > 4MB.

**Comment by gapra-msft** [comment]
Hi @g2vinay Thank you for posting this issue. 

> Should succeed instead of throwing error saying data > 4MB is not supported.
I think if we succeed when large data is passed in people may misunderstand and assume their data was successfully transferred when in fact it wasn't.

**Comment by g2vinay** [comment]
@gapra-msft 
I meant it should support data > MB.
This API is missing uploadInChunks logic underneath.

**Comment by gapra-msft** [comment]
@g2vinay 

Thanks for the clarification. 

We will take this feature request into consideration and prioritize it appropriately.

**Comment by frascu** [comment]
Hi @gapra-msft,
I created this method for personal use. 
If it is possible, where should I put this method?
In an example class ([FileSample](https://github.com/Azure/azure-sdk-for-java/blob/master/sdk/storage/azure-storage-file-share/src/samples/java/com/azure/storage/file/share/FileSample.java) or [ReadmeSamples](https://github.com/Azure/azure-sdk-for-java/blob/master/sdk/storage/azure-storage-file-share/src/samples/java/com/azure/storage/file/share/ReadmeSamples.java)) or directly in the class [ShareFileClient](https://github.com/Azure/azure-sdk-for-java/blob/master/sdk/storage/azure-storage-file-share/src/main/java/com/azure/storage/file/share/ShareFileClient.java)?

**Comment by gapra-msft** [comment]
@frascu 

Thank you for being willing to contribute! I think the best place for it would be in our samples section. If you create a PR we'd be happy to review and help get that merged

**Comment by mikeharder** [comment]
@kasobol-msft: Was this fixed by https://github.com/Azure/azure-sdk-for-java/pull/21000?  The Java File Share perf tests are now passing for the 10MB and 1GB scenarios.

**Comment by kasobol-msft** [comment]
yes.
