### ISSUE TITLE
[QUERY] How can I get a Screenshot from a running Vm as available in "Boot diagnostics" screen?

### ISSUE THREAD

**Issue by erzads** [Azure/azure-sdk-for-java#18644]
**Query/Question**
How can I get a Screenshot from a running Vm as available in "Boot diagnostics" screen?

***Why is this not a Bug or a feature Request?***
I am not entirely sure if this feature exists yet.

**Setup (please complete the following information if applicable):**
 - OS: Windows
 - IDE : IntelliJ
 - com.microsoft.azure:azure:1.36.3
 
 **Information Checklist**
 Kindly make sure that you have added all the following information above and checkoff the required fields otherwise we will treat the issuer as an incomplete report
- [x] Query Added
- [x] Setup information Added

**Comment by joshfree** [comment]
Thanks for filing this issue, @erzads.  Someone from the `Mgmt` plane SDK team will follow up shortly

**Comment by yungezz** [comment]
hi @xccc-msft could you pls help to have a look? thanks

**Comment by xccc-msft** [comment]
@erzads You can try below:
```java
computeManager.serviceClient().getVirtualMachines().retrieveBootDiagnosticsData("rgName", "vmName");
```

**Comment by weidongxu-microsoft** [comment]
`virtualMachine.instanceView().bootDiagnostics().consoleScreenshotBlobUri();` when it is not managed storage, and you need access to the storage account container.

**Comment by weidongxu-microsoft** [comment]
Short survey for us to hear you:
https://microsoft.qualtrics.com/jfe/form/SV_ehN0lIk2FKEBkwd?Q_CHL=ISSUES
