### ISSUE TITLE
Can we use Azure Java SDK to manage token in Azure Container Registry?

### ISSUE THREAD

**Issue by gkgaurav31** [Azure/azure-sdk-for-java#18659]
I am trying to manage the ACR Tokens (Preview feature) using Java SDK. The REST APIs are here:
https://docs.microsoft.com/en-us/rest/api/containerregistry/accesstokens

I could not find the related APIs in Java SDK here:
https://docs.microsoft.com/en-us/java/api/overview/azure/resourcemanager-containerregistry-readme?view=azure-java-stable

Is it possible?

**Comment by joshfree** [comment]
@g2vinay could you please assist @gkgaurav31

**Comment by deetoo** [comment]
@g2vinay any update yet?

**Comment by g2vinay** [comment]
@gkgaurav31 @deetoo 
Thank you for raising this query.
Currently, we don't have an SDK that helps to manage tokens for Azure Container Registry. 
The Azure Container Registry appears to have its dedicated REST endpoints to get access tokens from, so our azure-identity SDK wouldn't work as it is for ACR.

I'll check with ACR team and update here if there are any plans on their end to build an SDK around this.

**Comment by g2vinay** [comment]
@gkgaurav31 

Upon further digging, the ACR team currently doesn't have SDKs to manage ACR tokens either for Java,
They msul support it in one of their upcoming releases.

**Comment by pallavit** [comment]
I wanted to circle back and ask, if you are looking for a solution for the data plane library of ACR as well? We recently released the data plane library for ACR with token management handled by the library - https://repo1.maven.org/maven2/com/azure/azure-containers-containerregistry/. The library is still in beta and may change shape - but I would like to get feedback from you on whether it helps in your scenario.
