### ISSUE TITLE
[BUG] [NIO] Copy a stream to a blob results in an exception 

### ISSUE THREAD

**Issue by pditommaso** [Azure/azure-sdk-for-java#18668]
**Describe the bug**

Copying a stream to a remote Azure blob path results using NIO `Files.copy()` method results in an exception. This happens because the  Files.copy API tries to open the output stream using the option `CREATE_NEW` and `WRITE` (see below) which does not match the Azure provider expectation. 

```
      OutputStream ostream;
        try {
            ostream = newOutputStream(target, StandardOpenOption.CREATE_NEW,
                                              StandardOpenOption.WRITE);
        } catch (FileAlreadyExistsException x) {
            if (se != null)
                throw se;
            // someone else won the race and created the file
            throw x;
        }
```

***Exception or Stack Trace***

```
java.lang.IllegalArgumentException: Write and TruncateExisting must be specified to open an OutputStream

	at com.azure.storage.blob.nio.AzureFileSystemProvider.newOutputStream(AzureFileSystemProvider.java:378)
	at java.nio.file.Files.newOutputStream(Files.java:216)
	at java.nio.file.Files.copy(Files.java:3016)
```

**To Reproduce**

Use the groovy snippet below

***Code Snippet***

```
        when:
        def blob = fileSystem.getPath( 'hello.txt')
        and:
        Files.copy(new ByteArrayInputStream('Hello'.getBytes()), blob)
        then:
        Files.exists(blob)
```

**Expected behavior**

The  stream should be copied to the azure blob. 

**Screenshots**

**Setup (please complete the following information):**
 - OS: MacOs
 - IDE : n/a
 - Version of the Library used: latest

**Additional context**
- 

**Information Checklist**
Kindly make sure that you have added all the following information above and checkoff the required fields otherwise we will treat the issuer as an incomplete report
- [x] Bug Description Added
- [x] Repro Steps Added
- [x] Setup information Added

**Comment by rickle-msft** [comment]
@pditommaso Thanks for reporting this. I think we should be able to do the same checks but allow for create_new as it's still not expecting to be able to modify an existing blob. I'll work on adding this.
