### ISSUE TITLE
[FEATURE REQ] [NIO] Consider making AzurePath.toBlobClient() public

### ISSUE THREAD

**Issue by pditommaso** [Azure/azure-sdk-for-java#18669]
**Is your feature request related to a problem? Please describe.**

The `AzurePath` class includes a method `toBlobClient` that provides access to the underlying Azure blob client.  Applications aware of this implementation could benefit to gain access to native features (eg to generate SAS tokens) however the `toBlobClient` is not publicly accessible, limiting this possibility. 

**Describe the solution you'd like**

Make `AzurePath.toBlobClient` public accessible to other APIs. 

**Describe alternatives you've considered**
-

**Additional context**
-

**Information Checklist**

- [x] Description Added
- [x] Expected solution specified

**Comment by rickle-msft** [comment]
@pditommaso Thanks for the suggestion. Can you explain a little bit more about the workflow here? I understand the request, but I'm just not familiar enough with NIO to know when consuming applications would be aware of the specific implementation and want to take advantage of features like this.

**Comment by pditommaso** [comment]
Sure, the need is to be able to access the blob client to being to use azure blob native API, in my case to get the HTTP URL of the corresponding blob object.

**Comment by rickle-msft** [comment]
Is it common for applications leveraging nio to be aware of what provider they're using at a given time and want to do provider-specific tasks like this?

**Comment by pditommaso** [comment]
Don't know if it's common, but IMO it's legit for a subclass to expose implementation-specific APIs. 

For example, the Google CloudStoragePath expose the [bucket()](https://googleapis.dev/java/google-cloud-clients/0.97.0-alpha/com/google/cloud/storage/contrib/nio/CloudStoragePath.html) which does not belong to the `Path` interface.
