### ISSUE TITLE
[QUESTION] Azure Key Vault Secrets Spring Boot Starter - Local development and Managed Identity

### ISSUE THREAD

**Issue by tijmenamsing** [Azure/azure-sdk-for-java#18675]
**Query/Question**
(How) Can I use Azure Key Vault Secrets Spring Boot Starter locally when using Managed Identity on Azure?

***Why is this not a Bug or a feature Request?***
I'm not sure if it's a feature and I'm doing something wrong.

**Setup (please complete the following information if applicable):**
 - OS: Windows
 - IDE : VS Code / console
 - Version of the Library used: 3.0.0
 
 **Information Checklist**
 Kindly make sure that you have added all the following information above and checkoff the required fields otherwise we will treat the issuer as an incomplete report
- [x] Query Added
- [x] Setup information Added

I'm investigating whether it's possible to run our app locally while opting for managed identity when deployed to Azure. 

I know MI only works on Azure infrastructure, but in another case when using `Azure.Security.Keyvault.Secrets.SecretClient`, I can use the [DefaultAzureCredentialBuilder](https://github.com/Azure/azure-sdk-for-java/blob/master/sdk/identity/azure-identity/src/main/java/com/azure/identity/DefaultAzureCredentialBuilder.java) to authenticate with my developer credentials when running locally. 

I wonder if something like this is also possible with `Azure Key Vault Secrets Spring Boot Starter`, because I'd prefer not to create a service principal just for developers to work locally. 

So far I've tried it with the sample for keyvault-secrets that is in this repository. It works when using a service principal, but doesn't when I remove the clientId and clientKey from application.properties and login with Azure CLI.

Thanks!

**Comment by joshfree** [comment]
@vcolin7 could you please follow up with @jizza's question?  Thanks

**Comment by vcolin7** [comment]
You should be able to use a Managed Identity  with the Azure Key Vault Secrets Spring Boot Starter, just make sure that either the `client-key`, `client-key` or `certificate-path` properties are `null`. `client-id` can be either be `null` or have a value depending on if you want `ManagedIdentityCredential` to use a specific client.

In case you want to see how this works more in detail, [here's the method](https://github.com/Azure/azure-sdk-for-java/blob/f28826e51a3f31566483756d059baa73e18a30dc/sdk/spring/azure-spring-boot/src/main/java/com/azure/spring/keyvault/KeyVaultEnvironmentPostProcessorHelper.java#L140) that takes care of creating the `TokenCredentials` object [that the `SecretClient` is created with](https://github.com/Azure/azure-sdk-for-java/blob/f28826e51a3f31566483756d059baa73e18a30dc/sdk/spring/azure-spring-boot/src/main/java/com/azure/spring/keyvault/KeyVaultEnvironmentPostProcessorHelper.java#L89) in this Spring Boot Starter.

Finally, here are a couple resources related to `ManagedIdentityCredential`:

- [Authenticating in Azure with managed identity](https://github.com/Azure/azure-sdk-for-java/wiki/Azure-Identity-Examples#authenticating-in-azure-with-managed-identity)
- [Enable managed identity for Azure resources](https://github.com/Azure/azure-sdk-for-java/wiki/Set-up-Your-Environment-for-Authentication#enable-managed-identity-for-azure-resources)

Please do let me know if you encounter any issues if there was something I misunderstood about your question :)
