### ISSUE TITLE
[FEATURE REQ] ApplicationGateway : Add possibility to configure a custom error configuration into a listener definition 

### ISSUE THREAD

**Issue by sebastienmaillard** [Azure/azure-sdk-for-java#18674]
**Is your feature request related to a problem? Please describe.**
We're using an application gateway to host multiple subdomain sites that we configure dynamically. For each site, we want to user a custom 502/403 pages, but we can't set it using java api. Everything seems to be present in the API : there is a customErrorConfigurations on ApplicationGatewayHttpListener, but not accessible on the Create / Update builder.

**Describe the solution you'd like**
expose a withCustomErrorConfiguration into the ApplicationGateway.DefinitionStages.WithListener interface, allowing creation and update of listeners with thoses properties

**Describe alternatives you've considered**
We don't have any alternative beside doing it manually on azure portal. Doing it via a rest call would be tedious.

**Additional context**
N/A

**Comment by joshfree** [comment]
HI @sebastienmaillard, someone from the Application Gateway Management Plane SDK team will follow up with you shortly.  Thanks.

**Comment by yungezz** [comment]
hi @xccc-msft could you pls help to confirm is this operation could be done at mgmt plane? thanks

**Comment by xccc-msft** [comment]
@sebastienmaillard You may try below as workaround:
```java
ApplicationGatewayInner inner = new ApplicationGatewayInner();
inner.withHttpListeners(Arrays.asList(new ApplicationGatewayHttpListener()));
networkManager.applicationGateways().inner().createOrUpdate("rgName", "appGwName", inner);
```

**Comment by sebastienmaillard** [comment]
Great didn't know how to use inner beans directly and it worked !

One question however, how are java sources generated from rest api's ? can we participate (PR) on these process ? 
Another example, of a missing piece : In ApplicationGatewayBackendHttpConfiguration interface, the Update.WithAttach interface is missing WithProbe implementation, whereas DefinitionStages.WithAttach has it. So you can create a backend http configuration with a probe, but you can't add one to a pre-existing application gateway. I tried to simply add the "WithProbe" interface to the Update.WithAttach, and it worked like a charm :)

**Comment by xccc-msft** [comment]
@sebastienmaillard You may check the [contrubuting](https://github.com/Azure/azure-sdk-for-java/tree/master/sdk/resourcemanager#contributing) section and create PR to help that. Thanks a lot!
