### ISSUE TITLE
[BUG] [NIO] Directory is not recognised when created with external tool

### ISSUE THREAD

**Issue by pditommaso** [Azure/azure-sdk-for-java#18681]
**Describe the bug**

The NIO methods `Files.isDirectory()` and `Files.exists()` return false when specifying a directory path created with an external tool such `azcopy`. 

My understanding is that the NIO library implemented by this SDK simulates a directory using a mock file, in fact, the blob browser shows a duplicate entry for each directory item. 

<img width="1039" alt="Screenshot 2021-01-19 at 23 40 00" src="https://user-images.githubusercontent.com/816968/105102833-c1ac4000-5aaf-11eb-9895-30cd6906ef28.png">

However, this approach seems to be not compatible with directory structures created by other tools such as `azcopy`, which create directories, without then need to use a companion file.

The biggest problem is that the API reported above fails to recognise the directories created with the latter tools, making the content not interoperable.

<img width="1040" alt="Screenshot 2021-01-19 at 23 40 11" src="https://user-images.githubusercontent.com/816968/105103017-1cde3280-5ab0-11eb-8993-a1863d23de9d.png">

(in the above example `index` is a directory without any `index` file) 

***Exception or Stack Trace***

na

**To Reproduce**

Create a directory into a blob container with `azcopy`, then check the existence with `File.exists('azb://container:/path/')`

***Code Snippet***
n/a

**Expected behavior**

`Files.exists()` and `Files.isDirectory()` should recognise the directory. 

**Screenshots**
See above

**Setup (please complete the following information):**
 - OS: MacOs
 - IDE : n/a
 - Version of the Library used: latest

**Additional context**
Blocker issue. 

**Information Checklist**
Kindly make sure that you have added all the following information above and checkoff the required fields otherwise we will treat the issuer as an incomplete report
- [x] Bug Description Added
- [x] Repro Steps Added
- [x] Setup information Added

**Comment by rickle-msft** [comment]
@pditommaso Thanks for opening this up. I'm talking with a teammate about the differences with azcopy. In the meantime, can you clarify if you are using nio and azcopy simultaneously? Or if you are using them sequentially, e.g. azcopy to upload a bunch of stuff and then nio to process them but only one at a time?

**Comment by pditommaso** [comment]
The latter, I mean sequentially, we use NIO to upload some data to the blob container, then a Batch job is triggered to download the data using `azcopy` and copying back the result to the storage, and so on. Don't think it's a azcopy fault. I've see the same also using [rclone](https://rclone.org/).

**Comment by rickle-msft** [comment]
I just had a talk with our azcopy team, and they said they would add support for specifying a flag when uploading to create directory marker blobs that will be compatible with nio (and fuse), so I think that will be the best solution to this issue.

**Comment by pditommaso** [comment]
Sorry, if I'm commenting on a closed issue, however, I've made a small test and it looks that to create a (fake) directory it's enough to write and empty blob with and ending slash eg 

```
        final container = storageClient.getBlobContainerClient('my-data')
        final blob = container.getBlobClient('foo/this/that')
        blob.getAppendBlobClient().create()
```


My understanding is that this project is creating an empty blob (ie. without the ending slash). IMO this choice is a bit confusing because give the impression to pollute the container with duplicate entries and result not compatible with other tools. Just my 2 cents.

**Comment by rickle-msft** [comment]
Thanks for taking a look into this. I understand your concerns here. There actually are other tools that use this mechanism, which is why we chose it. This is how blobfuse and hns enabled accounts both create directories in this way. Other tools like azcopy aren't actually intended to mimic a filesystem so much as transfer data, which is why they have so far not gone this route, but azcopy will soon be offering a way to comply with this as well.

Other than consistency with other tools, the reason this was originally chosen is because without the empty blob with the name matching the directory, there's no way to have an empty directory. Without it, because of how the service works, an empty directory can't be created (directories could only be created by putting something in them) and directories would disappear if you delete the last item in them.
