### ISSUE TITLE
ServiceBus - Admin client using CreateSubscriptionOptions - MaxDeliveryCount not defaulted to 10

### ISSUE THREAD

**Issue by hemanttanwar** [Azure/azure-sdk-for-java#18705]
Bug : When we use `CreateSubscriptionOptions` and create subscription using `ServiceBusAdministrationAsyncClient`, it does not default MaxDeliveryCount's 10.
If user does not specify this, it will be set to 0 and servicer bus will throw the error that it is an invalid value.

**Comment by joshfree** [comment]
@YijunXieMS please verify and close

**Comment by ramya-rao-a** [comment]
From other languages:
- .NET client defaults to 10 before sending the request to create subscription if user does not set anything
- JS & Python clients do not set any defaults when creating the subscription. The service does the right thing and defaults to 10

**Comment by ki1729** [comment]
We set it to default to 10 as well just like .NET. 
Verified that it does work when it is not specified
