### ISSUE TITLE
 Storage file Datalake test improvement

### ISSUE THREAD

**Issue by hongli750210** [Azure/azure-sdk-for-java#18727]
There are no test cases about `listPaths().byPage()` in the existing test cases in the Java storage file datalake. So, it is recommended to add test cases related to paged retrieval results validation for method [`listPaths()`](https://github.com/Azure/azure-sdk-for-java/blob/master/sdk/storage/azure-storage-file-datalake/src/main/java/com/azure/storage/file/datalake/DataLakeFileSystemAsyncClient.java#L415) of `DataLakeFileSystemAsyncClient` class in java test [FileSystemAPITest.groovy](https://github.com/Azure/azure-sdk-for-java/blob/master/sdk/storage/azure-storage-file-datalake/src/test/java/com/azure/storage/file/datalake/FileSystemAPITest.groovy). 
By the way, python storage file datalake sdk have the [test cases](https://github.com/Azure/azure-sdk-for-python/blob/master/sdk/storage/azure-storage-file-datalake/tests/test_file_system.py#L241) about  `get_paths().by_page()`.

 

@scottaddie , @joshfree , @kyle-patterson , @tg-msft , @alzimmermsft for notification.

**Comment by v-xuto** [comment]
@scottaddie , @joshfree , @kyle-patterson , @tg-msft , @alzimmermsft  Do you have any ideas about this issue?

**Comment by kasobol-msft** [comment]
It seems to be true, the `DataLakeFileSystemAsyncClient.listPaths` doesn't seem to be covered at all and it doesn't seem to share much with sync version which is covered.

**Comment by v-xuto** [comment]
@alzimmermsft Do you have any plans on who will fix this issue?
