### ISSUE TITLE
unable to create additional data disks with custom image

### ISSUE THREAD

**Issue by ashishdhar** [Azure/azure-sdk-for-java#1872]
I have been trying to create a VM on azure through the java sdk using custom images. I am able to successfully provision the VM as long as i only specify the OS disk in the Storage profile. This custom image has 2 data disks apart from the OS disk. I get all 3 after I provision it. Unfortunately, when I try to add other data disks to the storage profile (`storageProfile.withDataDisks(dataDisk)`) I get the following error.

`StorageProfile.dataDisks.lun does not have required value(s) for image specified in storage profile`

The 2 data disks in the custom image are on lun 1 and 2 and the new data disk is on lun 0. If i try to reuse the lun numbers then I get `Cannot specify user image overrides for a disk already defined in the specified image reference`

I have been referring [this](https://github.com/Azure-Samples/managed-disk-java-create-virtual-machine-using-custom-image-from-VHD) sample but its not clear to me how to customize disks already existing on the image vs adding new data disks. 

The way we are using the SDK is to create a `VirtualMachineInner` with all the profiles and storage is one of them. The custom image is set using `storageProfile.withImageReference(id)` and os disk and data disks are set using `storageProfile.withOsDisk(osDisk)` and `storageProfile.withDataDisks(dataDisks)`

**Comment by anuchandy** [comment]
@ashishdhar, looks like you are using inner types directly. I would recommend you to use the fluent layer as using inner is cumbersome and error prone.

Custom Image = `One OSDiskImage` + `DataDiskimages[i] 0 <= i < n`

The data disks associated with a VM can be categorized in two sets. 

  (1). The set of data disks based on the custom image. 
  (2). The set of data disks that user added additionally.

```
VM Data disks = OSDisk based on CustomImage::OSDiskImage 
      + Zero or more data disks based on CustomImage::DataDiskimages[i]
      + Zero or more additional data disks that user wanted to add.
```

When you specify just the custom image as source of a VM without explicitly specifying any data disk like below:

```java
           azure.virtualMachines().define(linuxVMName2)
                    .withRegion(region)
                    .withExistingResourceGroup(rgName)
                    .withNewPrimaryNetwork("10.0.0.0/28")
                    .withPrimaryPrivateIPAddressDynamic()
                    .withoutPrimaryPublicIPAddress()
                    .withLinuxCustomImage(virtualMachineCustomImage.id())
                    .withRootUsername(userName)
                    .withRootPassword(password)
                    .withSize(VirtualMachineSizeTypes.STANDARD_D3_V2)
                    .create();
```

Azure will take care of adding the disks to the VM corresponding to the data disk images in the custom image.

If you want to specify the additional data disk (i.e. in-addition to the data disks based on the data disk images in the custom image) then you need to make sure you are explicitly specify data disk for both category. The lun of the data disk based on disk image must match with the disk image lun.

```java
CustomImage virtualMachineCustomImage = // get the custom image

VirtualMachine.DefinitionStages.WithLinuxCreateManaged vmWithDisk = azure.virtualMachines().define(linuxVMName3)
     .withRegion(region)
     .withExistingResourceGroup(rgName)
     .withNewPrimaryNetwork("10.0.0.0/28")
     .withPrimaryPrivateIPAddressDynamic()
     .withoutPrimaryPublicIPAddress()
     .withLinuxCustomImage(virtualMachineCustomImage.id())
     .withRootUsername(userName)
     .withRootPassword(password);
     // Specify the disks based on custom image
     //
     for(int diskimageLun : virtualMachineCustomImage.dataDiskImages().keySet()) {
         vmWithDisk.withNewDataDiskFromImage(diskimageLun);
     }
    // Specify the additional data disks.
    //
     vmWithDisk.withNewDataDisk(100);
    // Create VM
    //
    vmWithDisk.create();
```

If you want to know how inner are populated then you can run above code with logging enabled.

**Comment by ashishdhar** [comment]
@anuchandy  as you suggested I enabled logging and tried using the fluent layer and encountered the same issue. I am putting the relevant portions of the code and logs below. Again I am using a linux custom image with 2 data disks.

When I used just the custom image without any additional new data disks the provisioning succeeded.

```java
VirtualMachine linuxVM2 = azure.virtualMachines().define("testingLinuxVM")
                    .withRegion("eastus")
                    .withExistingResourceGroup("ashRG")
                    .withNewPrimaryNetwork("10.0.0.0/28")
                    .withPrimaryPrivateIPAddressDynamic()
                    .withoutPrimaryPublicIPAddress()
                    .withLinuxCustomImage(VMImage.id())
                    .withRootUsername("ashpro")
                    .withRootPassword("AzureAshpro123")
                    .withSize(VirtualMachineSizeTypes.STANDARD_A2)
                    .create();
```

The storage profile in the virtual machine create request looked like this. Notice it has entries for the data disks present on the image.

```json
"storageProfile": {
      "imageReference": {
        "id": "/subscriptions/<subscription-id>/resourceGroups/ashNewRG/providers/Microsoft.Compute/images/managedDiskImage"
      },
      "osDisk": {
        "osType": "Linux",
        "createOption": "FromImage",
        "caching": "ReadWrite",
        "managedDisk": {
          "storageAccountType": "Standard_LRS"
        },
        "diskSizeGB": 30
      },
      "dataDisks": [
        {
          "lun": 1,
          "createOption": "FromImage",
          "caching": "ReadOnly",
          "managedDisk": {
            "storageAccountType": "Standard_LRS"
          },
          "diskSizeGB": 25
        },
        {
          "lun": 2,
          "createOption": "FromImage",
          "caching": "ReadWrite",
          "managedDisk": {
            "storageAccountType": "Standard_LRS"
          },
          "diskSizeGB": 28
        }
      ]
    }
```

Now when i add a new data disk during the VM creation I get an error during provisioning.
```java
VirtualMachine linuxVM2 = azure.virtualMachines().define("testingLinuxVM")
                    .withRegion("eastus")
                    .withExistingResourceGroup("ashRG")
                    .withNewPrimaryNetwork("10.0.0.0/28")
                    .withPrimaryPrivateIPAddressDynamic()
                    .withoutPrimaryPublicIPAddress()
                    .withLinuxCustomImage(VMImage.id())
                    .withRootUsername("ashpro")
                    .withRootPassword("AzureAshpro123")
                    .withNewDataDisk(13)
                    .withSize(VirtualMachineSizeTypes.STANDARD_A2)
                    .create();
```
The following error is thrown.
```json
{
  "error": {
    "code": "InvalidParameter",
    "target": "storageProfile",
    "message": "StorageProfile.dataDisks.lun does not have required value(s) for image specified in storage profile."
  }
}
```
I noticed that in the body of the  VirtualMachines createOrUpdate the 2 existing disks on the image were missing and it only had the info about the new data disk i had added. Have a look.

```json
{
   "storageProfile":{
      "imageReference":{
         "id":"/subscriptions/<subscription-id>/resourceGroups/ashNewRG/providers/Microsoft.Compute/images/managedDiskImage"
      },
      "osDisk":{
         "caching":"ReadWrite",
         "createOption":"fromImage",
         "managedDisk":{
            "storageAccountType":"Standard_LRS"
         }
      },
      "dataDisks":[
         {
            "lun":0,
            "caching":"ReadWrite",
            "createOption":"empty",
            "diskSizeGB":25,
            "managedDisk":{
               "storageAccountType":"Standard_LRS"
            }
         }
      ]
   }
```

Based on the json and the error message it looks like the sdk is not sending the correct json and missing the 2 disks present on the custom image.

**Comment by anuchandy** [comment]
@ashishdhar Just updated your last response with bunch of  `fragment-i` tags so that it is easy to refer code segements in your response.

**fragment-2** is not the request payload that SDK generates but the response payload from the service. SDK request payload will contain dataDisks property value as null and service populate it.

The **fragment-3** generates the payload **fragment-5**. This exactly the reason i mentioned in the previous response that we need to be explicit in this case

```java
CustomImage virtualMachineCustomImage = // get the custom image

VirtualMachine.DefinitionStages.WithLinuxCreateManaged vmWithDisk = azure.virtualMachines().define(linuxVMName3)
     .withRegion(region)
     .withExistingResourceGroup(rgName)
     .withNewPrimaryNetwork("10.0.0.0/28")
     .withPrimaryPrivateIPAddressDynamic()
     .withoutPrimaryPublicIPAddress()
     .withLinuxCustomImage(virtualMachineCustomImage.id())
     .withRootUsername(userName)
     .withRootPassword(password);
     // Specify the disks based on custom image
     //
     for(int diskimageLun : virtualMachineCustomImage.dataDiskImages().keySet()) {
         vmWithDisk.withNewDataDiskFromImage(diskimageLun);
     }
    // Specify the additional data disks.
    //
     vmWithDisk.withNewDataDisk(13);
    // Create VM
    //
    vmWithDisk.create();
```

**Comment by ashishdhar** [comment]
Got it to work with inner classes as well as the fluent APIS. To summarize if you need to just provision the data disks on the custom images you need not specify the data disks that already exist on it. But if we are adding a fresh new data disk we need to specify existing disks on the image through the LUN numbers and createOption.fromImage.
