### ISSUE TITLE
Servicebus - Test more with processor for possible memory leak.

### ISSUE THREAD

**Issue by hemanttanwar** [Azure/azure-sdk-for-java#18741]
Test `ServiceBusProcessorClient` by stop and start every 30 seconds and analyze if we have memory leak in library.

Related Issue : https://github.com/Azure/azure-sdk-for-java/issues/18294

**Comment by anuchandy** [comment]
There are no leaks identifed if we stop-start the processor as described, and multiple memory issues have been addressed since this ticket opened. Closing.
