### ISSUE TITLE
Calling "list" requires special permissions

### ISSUE THREAD

**Issue by bthemad** [Azure/azure-sdk-for-java#1874]
Greetings,

We're using a service principal with a `Reader` built-in role. But it's not sufficient for performing `azure.appServices().functionApps().list()` call. The error is:

```
The client 'XXX' with object id 'YYY' does not have authorization to perform action 'Microsoft.Web/sites/config/list/action' over scope '/subscriptions/ZZZ/resourceGroups/function-app-1/providers/Microsoft.Web/sites/function-app-1/config/appsettings
```

This could be resolved creating a custom role with permissions
```
"Actions": [
      "*/read",
      "Microsoft.Web/sites/config/list/action"
    ],
```

We don't need the information that is obtained with this call, but there's no way to configure what should be fetched. Also in the CLI v2 this issue is not present, so one can do `az functionapp list` having only `Reader` role.

We would like to avoid creating a custom role as much as possible.

**Comment by jianghaolu** [comment]
This is fixed in https://github.com/Azure/azure-libraries-for-java/pull/22
