### ISSUE TITLE
remove -SNAPSHOT dependencies from released artifacts

### ISSUE THREAD

**Issue by qwazer** [Azure/azure-sdk-for-java#1875]
com.microsoft.azure:azure:1.1.2
depends on
com.microsoft.azure:azure-client-runtime:1.0.5-SNAPSHOT
com.microsoft.azure:azure-client-authentication:1.0.5-SNAPSHOT

It force maven to download it every time - > slow builds

**Comment by jianghaolu** [comment]
Fixed and documented since 1.2.1, please verify.

**Comment by qwazer** [comment]
yes. thanks
