### ISSUE TITLE
Unable to do Boolean query on NULL values

### ISSUE THREAD

**Issue by shariqnitt** [Azure/azure-sdk-for-java#18758]
**Is your feature request related to a problem? Please describe.**
I am unable to filter on NULL value e.g.
Criteria criteria = Criteria.getInstance(CriteriaType.IS_EQUAL,
                "tripId",
                new ArrayList(Arrays.asList(null)),
                Part.IgnoreCaseType.NEVER);

**Describe the solution you'd like**
I wolud like to filter on Unary CriteriaType (which is not supported)
Criteria criteria = Criteria.getInstance(CriteriaType.IS_NULL,
                "tripId")

**Describe alternatives you've considered**
I am not findind any alternative as "trpId" is String type, if its boolean 
I could have filtered on CriteriaType.NOT_IN {TRUE, FALSE}.

**Comment by joshfree** [comment]
Hi @shariqnitt thanks for filing this issue.  I believe you're asking about the Cosmos SDK, but could you please provide more details on the exact package and package version that you're using?  Thanks

**Comment by kushagraThapar** [comment]
@shariqnitt - please provide more details on the SDK package and version being used.
