### ISSUE TITLE
Missing CosmosDB entities in azure-mgmt-cosmosdb

### ISSUE THREAD

**Issue by ardias** [Azure/azure-sdk-for-java#1876]
Hi All,
The current azure-mgmt-cosmosdb module only allows browsing the Accounts. We should be able to browse Databases and Collections, as is +/- possible with the "old" azure-documentdb library.
I'm opening this issue because i haven't seen anywhere any reference to this, and to know if there is any plan to add this missing feature.

**Comment by martinsawicki** [comment]
there is a different Azure SDK that has that functionality:
- http://search.maven.org/#search%7Cga%7C1%7Ca%3A%22azure-documentdb%22
or, if you prefer the more modern reactive style:
- http://search.maven.org/#search%7Cga%7C1%7Ca%3A%22azure-documentdb-rx%22
That project is at: https://github.com/Azure/azure-documentdb-java

What *this* Azure project is about is Azure *Management* Libraries for Java - "managing" Azure resource providers (e.g. CosmosDB accounts), not so much interacting with specific services, which dealing with DocDB Databases and Collections would be.

Now, whether that is a reasonable enough justification for having two separate SDKs for DocDB is topic for a different discussion, but that's just how the Azure SDKs are organized today, for at least historical reasons, among others. So what is referred to as the "old" azure-documentdb is not actually old -- it's a different SDK, actively maintained by the DocDB team, but for a different aspect of the DocumentDB/CosmosDB service...

**Comment by ardias** [comment]
Right, i understand that this library is not meant replace azure-documentdb.
In fact I don't need to manage databases or collections, I just need to
"browse" down to collections, because I'm using the monitor module and need
the resource Id for those entities which I can only get with
azure-documentdb.
Would that be something that fits within the scope of this module?


On Aug 17, 2017 18:14, "Martin Sawicki" <notifications@github.com> wrote:

there is a different Azure SDK that has that functionality:

   - http://search.maven.org/#search%7Cga%7C1%7Ca%3A%22azure-documentdb%22
   or, if you prefer the more modern reactive style:
   - http://search.maven.org/#search%7Cga%7C1%7Ca%3A%
   22azure-documentdb-rx%22
   That project is at: https://github.com/Azure/azure-documentdb-java

What *this* Azure project is about is Azure *Management* Libraries for Java
- "managing" Azure resource providers (e.g. CosmosDB accounts), not so much
interacting with specific services, which dealing with DocDB Databases and
Collections would be.

Now, whether that is a reasonable enough justification for having two
separate SDKs for DocDB is topic for a different discussion, but that's
just how the Azure SDKs are organized today, for at least historical
reasons, among others. So what is referred to as the "old" azure-documentdb
is not actually old -- it's a different SDK, actively maintained by the
DocDB team, but for a different aspect of the DocumentDB/CosmosDB service...

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/Azure/azure-sdk-for-java/issues/1876#issuecomment-323121050>,
or mute the thread

**Comment by ardias** [comment]
Sorry about the noise in the response. Gmail added it automatically
