### ISSUE TITLE
[BUG] MetricDefinitions::listByResource returns not supported metrics 

### ISSUE THREAD

**Issue by mgsantositrs** [Azure/azure-sdk-for-java#18777]
**Describe the bug**
Calling MetricDefinitions::listByResource occasionally returns VirtualMachine  metrics that are no longer supported resource metrics.

***Exception or Stack Trace***
`Failed to find metric configuration for provider: Microsoft.Compute, resource Type: virtualMachines, metric: OS Disk Target Bandwidth, Valid metrics: Percentage CPU,Network In,Network Out,Disk Read Bytes,Disk Write Bytes,Disk Read Operations/Sec,Disk Write Operations/Sec,CPU Credits Remaining,CPU Credits Consumed,Data Disk Read Bytes/sec,Data Disk Write Bytes/sec,Data Disk Read Operations/Sec,Data Disk Write Operations/Sec,Data Disk Queue Depth,Data Disk Bandwidth Consumed Percentage,Data Disk IOPS Consumed`
`Failed to find metric configuration for provider: Microsoft.Compute, resource Type: virtualMachines, metric: Data Disk Target Bandwidth, Valid metrics: Percentage CPU,Network In,Network Out,Disk Read Bytes,Disk Write Bytes,Disk Read Operations/Sec,Disk Write Operations/Sec,CPU Credits Remaining,CPU Credits Consumed,Data Disk Read Bytes/sec,Data Disk Write Bytes/sec,Data Disk Read Operations/Sec,Data Disk Write Operations/Sec,Data Disk Queue Depth,Data Disk Bandwidth Consumed Percentage,Data Disk IOPS Consum`

***Code Snippet***
`metricDefinitions().listByResource(resourceId)`

**Comment by joshfree** [comment]
@ramthi could you help route this?

**Comment by srnagar** [comment]
Looks like this is the azure-resourcemanager-monitor package. @mgsantositrs  can you please provide the version you are using for this package?

cc: @weidongxu-microsoft

**Comment by weidongxu-microsoft** [comment]
If it is "occasionally", likely service problem.
