### ISSUE TITLE
azure-messaging-servicebus-7.0.0 - Concurrent sessions handling with single consumer

### ISSUE THREAD

**Issue by indvamshi** [Azure/azure-sdk-for-java#18778]
**Query/Question**
I am exploring the new SDK azure-messaging-servicebus-7.0.0. I have got a publisher that sends messages with an eventId and the eventId is the same across all the messages (the order is important). The publisher can also send messages with different eventId as well. 
When I enable the session and sends two messages with different sessionId (eventId1, eventId2), the subscriber-only consumes the messages with session eventId1 or eventid2, but not both. 

How can I make the receiver accept multiple different session messages concurrently. I see a property maxConcurrentSessions but it's not visible to the client builder.

***Why is this not a Bug or a feature Request?***
A clear explanation of why is this not a bug or a feature request?

**Setup (please complete the following information if applicable):**
 - OS: iOS
 - IDE : Intellij
 - Version azure-messaging-servicebus-7.0.0
 
 **Information Checklist**
 Kindly make sure that you have added all the following information above and checkoff the required fields otherwise we will treat the issuer as an incomplete report
- [y] Query Added
- [ y] Setup information Added

**Comment by indvamshi** [comment]
What is the max number of maxConcurrentSessions allowed?

**Comment by httr01** [comment]
@indvamshi 
Here is sample for specifying this property if  you use Processor
https://github.com/Azure/azure-sdk-for-java/blob/master/sdk/servicebus/azure-messaging-servicebus/src/samples/java/com/azure/messaging/servicebus/ServiceBusSessionProcessorSample.java#L26

And for receiver, you can  `maxConcurrentSessions()` on `sessionReceiver()`
https://github.com/Azure/azure-sdk-for-java/blob/master/sdk/servicebus/azure-messaging-servicebus/src/samples/java/com/azure/messaging/servicebus/ReceiveSingleSessionAsyncSample.java#L38

What is the max number of maxConcurrentSessions allowed ? : It is fairly large number.
Do you have certain requirement of how many session you need to handle ?

**Comment by hemanttanwar** [comment]
@indvamshi
Here is sample for specifying this property if you use Processor
https://github.com/Azure/azure-sdk-for-java/blob/master/sdk/servicebus/azure-messaging-servicebus/src/samples/java/com/azure/messaging/servicebus/ServiceBusSessionProcessorSample.java#L26

And for receiver, you can maxConcurrentSessions() on sessionReceiver()
https://github.com/Azure/azure-sdk-for-java/blob/master/sdk/servicebus/azure-messaging-servicebus/src/samples/java/com/azure/messaging/servicebus/ReceiveSingleSessionAsyncSample.java#L38

What is the max number of maxConcurrentSessions allowed ? : It is fairly large number.
Do you have certain requirement of how many session you need to handle ?

**Comment by indvamshi** [comment]
Thank you @hemanttanwar for your quick reply.

Regarding the concurrent sessions number, I thought there is a limit. The question regarding concurrent sessions raised on session lock. 
We have a requirement where a publisher puts a couple of messages onto the queue with an event Id and event state. The eventId remains the same for a group of messages but the state differs for each message. The message needs to be processed in the order based on the state. Also, the publisher sends with different eventIds and states. 

To achieve message ordering we planned to go with ASB sessions. But, the problem we are facing is on the consumer the session is locked to an eventId and if I publish a message with different eventId its not consumed. 
Today, I tried with concurrent sessions number as 2, and able to consume two messages. Underneath, ASB created two different session channels. 

This is not the ideal solution to go forward, as the eventids can be millions and cannot create concurrent sessions for that number.  Is there a better way ASB can provide w.r.t sessions, is there a way to unlock the session and create a new session for incoming eventId.

This could be a general problem how this can be achieved with ASB.

Thanks
Vamshi

**Comment by hemanttanwar** [comment]
@indvamshi If you want guaranteed ordering, using session queue is right choice.  Understanding session in depth will help to design your solution.
Here are some session reading you can do  https://docs.microsoft.com/en-us/azure/service-bus-messaging/message-sessions

**Sending**
SessionId is assigned to message when sender send a message.
When a receiver is created , it will lock that session id to ensure ordering of message. How long a session is locked based on how you have configured at the time of creating topic/queue.

**Receiving**
There are two ways you can receive messages 1. Using `ServiceBusProcessorClient` 2. Using `ServiceBusSenderAsyncClient/ServiceBusSenderClient`

1.
Processor is high level and easy way to receive messages but you have less controls. When you use the processor , you can specify how many session you want to receive from. If there no messages for 60 seconds by default, it will release that session and lock next available session. You can control this time by setting `retryOptions` on builder (explained in code below) but this property is also used for another purpose example connection level retry, how long to wait for locking a new  session etc. 

```java
      // Example below will receive message from 10 session and if there are no messages received in 20 seconds , it will move on to next session and you will start getting message from next available session.

        ServiceBusProcessorClient processorClient = new ServiceBusClientBuilder()
                .connectionString(connectionString)
                .retryOptions(new AmqpRetryOptions().setTryTimeout(Duration.ofSeconds(20)))
                .sessionProcessor()
                .queueName(queueName)
                .maxConcurrentSessions(10)
                .processMessage(ServiceBusSessionProcessorSample::processMessage)
                .processError(ServiceBusSessionProcessorSample::processError)
                .buildProcessorClient();
``` 
2. In you case you want better control, when to release a session, you can use  `ServiceBusSenderAsyncClient/ServiceBusSenderClient`. Here is one [sample](https://github.com/Azure/azure-sdk-for-java/blob/master/sdk/servicebus/azure-messaging-servicebus/src/samples/java/com/azure/messaging/servicebus/ReceiveSingleSessionAsyncSample.java#L47) .

You can control when to dispose a receiver, when you have received last message for that sessionId.  The definition of last message is specific to the application, for example in your case you use some `state` to determine that a message is last for that sessionId. If you use Async receiver, you can use Project reactor APIs to dispose the receiver and acceptNextSession().
For example [takeUntil() operator](https://projectreactor.io/docs/core/release/api/reactor/core/publisher/Flux.html#takeUntil-java.util.function.Predicate-), return `true` when you have received last message for that sessionId based on state.

**Comment by indvamshi** [comment]
Hi
Thank for you detailed response.

I have give a try with retryOptions with duration has 20seconds, This is what I observed

1. Published a message with a sessionId1. The message got consumed straight away.
2. Published another message with sessionId2 immediately, it was not consumed . After 20 seconds timeout, sessionId2 got consumed.
3. Published same message with sessiond2 again got consumed immediately.
4. Published first message with sessionId1, it was not consumed. Waited for 20 seconds still not consumed. 

So once the lock for a particular session is locked and expired , am unable to retain the session back. 
My understanding was when I use retry option, no matter what the sessionId is the message should be consumed similar like step 2. 

Am I missing any property to retain the Sessionid1?

Thanks
Vamshi

**Comment by hemanttanwar** [comment]
Are  you using `ServiceBusProcessorClient` or `ServiceBusSessionReceiverAsyncClient/ServiceBusSessionReceiverClient` ?May be you can put your code on git somewhere, so we can help you better with your scenario. 
If you use Processor, what is value `maxConcurrentSessions` you use in your builder ? This controls how many session you want to receive messages from. It seems like you are using one sessionId at a time to receive message from. It you set it to 2, the receiver will try to lock two sessions and you will receive messages from these two locked session.

You asked about receiving from 100/more sessionId, The current design where you use `ServiceBusSessionReceiverAsyncClient/ServiceBusSessionReceiverClient`,  one client instance will connect to one sessionId at a time. You can multi thread your program to create many client and each client is locked on to one sessionId.  

As in client-server model, one session receiver will get a lock to one session and maintain order within that session.  
`Processor` gives you flexibility to  lock multiple session at same time using `maxConcurrentSessions` but each sessionId will have its own AMQP Link establish to receive message. You have design your solution with this in mind that one receiver will lock on to one sessionId at a time.

**Comment by indvamshi** [comment]
I am using ServiceBusProcessorClient, 
        serviceBusClient = new ServiceBusClientBuilder()
            .connectionString(host)
            .sessionProcessor()
            .maxConcurrentSessions(2)
            .topicName(topic)
            .receiveMode(ServiceBusReceiveMode.PEEK_LOCK)
            .subscriptionName(subscription)
            .processMessage(consumer.receiveMessageWithSession())
            .processError(consumer.errorHandler())
            .buildProcessorClient();

 public Consumer<ServiceBusReceivedMessageContext> receiveMessageWithSession() {
        Consumer<ServiceBusReceivedMessageContext> onMessage = context -> {
            ServiceBusReceivedMessage message = context.getMessage();
            //processor.processMesssage(new String(message.getBody().toBytes()));
            processMessage(message);
        };
        return onMessage;
    }

If I have got maxConcurrentSessions(2), then yes it work as expected. For each amqp link a session is assigned. What if I do not want to use that link to the same sessionId like assign to a different sessionId. If I have got maxConcurrentSessions(2) am bound to use only session id1,id2 what If I want to send messages with sesion id3,id4.

Also, as mentioned earlier if I have got maxConcurrentSessions(1), the same amqp link is shared between two sessions id1 and id2 based on the setTryTimeout. Firstly id1 is consumed, then wait for retryOption i.e 1 minutes to expire, then id2 is consumed. But, if send id1 again, its not consumed.

But, by using Microsoft sdk, ISessionHandler is able to solve the above scenario. I can see the messages getting consumed no matter what the order of the messages. I can see messages consumed with session id1,id2 ...id2,id1..etc..

The behaviour is different in Azure SDK 7.0.0 version, is it a defect or am I missing any settings?

**Comment by hemanttanwar** [comment]
@indvamshi 
I am able to achieve this i.e. consumed with session id1,id2 ...id2,id1..etc.. , Here is sample test program in gist https://gist.github.com/hemanttanwar/b0ea9c64a76b8c51d12952832ebb16fc

**Comment by ramya-rao-a** [comment]
Hey @indvamshi 

Closing this issue as we have not heard back from you in a while. Hopefully, the sample code @hemanttanwar shared above helps.
If not, please feel free to drop a comment and we can re-open the issue

**Comment by JRiggenbach** [comment]
Sorry for leaving a post on a closed ticket, but did the amqp retry behavior change since this post?

`.retryOptions(new AmqpRetryOptions().setTryTimeout(Duration.ofSeconds(20)))`

For the life of me, I can't get the processor client to grab onto new sessions any faster than a 60 second interval.  

Here is my ServiceBusClientBuilder config

```
return new ServiceBusClientBuilder()
                .credential(serviceBusNamespace, clientSecretCredential)
                .retryOptions(new AmqpRetryOptions()
                    .setTryTimeout(Duration.ofSeconds(5)))
                .sessionProcessor()
                .topicName(topicName)
                .subscriptionName(subscriptionName)
                .receiveMode(ServiceBusReceiveMode.PEEK_LOCK)
                .maxConcurrentSessions(10)
                .processMessage(messageHandler::processMessage)
                .processError(messageHandler::processError)
                .buildProcessorClient();
```

I would expect this to generate a client that would receive message from 10 session (which it does) and if there are no messages received in 5 seconds for a session, it would move on to next session and start getting message from next available session.  However, the next sessions are not processed until that 60 second loop is complete.  I can see that the duration is applied to the session and that it reports out that there are no other messages within that 5 second window, but I must be missing something in my understanding of how this should work.

Thanks.
