### ISSUE TITLE
App Configuration SDK for non-spring users

### ISSUE THREAD

**Issue by kavukcutolga** [Azure/azure-sdk-for-java#18784]
**Query/Question**
How non-spring users would benefit from features that exist within appconfiguration-config.

See that, these features are developed against spring boot libraries.
https://github.com/Azure/azure-sdk-for-java/blob/master/sdk/appconfiguration/azure-spring-cloud-appconfiguration-config/pom.xml#L21

Is there a way/pure java-sdk that we can use for other frameworks, there are nice features like property refresh, managed  identify integration, caching, retry etc. in this library

***Why is this not a Bug or a feature Request?***
It's a user/vision question

**Setup (please complete the following information if applicable):**
N/A
 
 **Information Checklist**
 Kindly make sure that you have added all the following information above and checkoff the required fields otherwise we will treat the issuer as an incomplete report
- [X] Query Added
- [X] Setup information Added

**Comment by joshfree** [comment]
@mssfang can you please follow up?

**Comment by mssfang** [comment]
Currently, App Configuration SDK is providing the fundamental actions that App Configuration service provides. 
For (1)  "property refresh" feature, there is a PR that is related to it. But the App Configuration SDK plans to enhance it in the near future.  https://github.com/Azure/azure-sdk-for-java/issues/5255
(2) "managed identify integration", the client can always be created with AAD token, more information can be found here: https://github.com/Azure/azure-sdk-for-java/tree/master/sdk/appconfiguration/azure-data-appconfiguration#use-aad-token
and
https://github.com/Azure/azure-sdk-for-java/wiki/Identity-and-Authentication
(3) SDK doesn't provide the caching of settings. 
(4) RetryPolicy can be obtained from Azure Core and it can be customized when you create an AppConfugraiton client.
RetryPolicy: https://github.com/Azure/azure-sdk-for-java/blob/master/sdk/core/azure-core/src/main/java/com/azure/core/http/policy/RetryPolicy.java
After the RetryPoilcy is defined, use it in appconfiguration's client builder,
``` 
clientBuilder.retryPolicy({new RetryPolicy() // which could be the customized retry policy}).buildClient();
```

Please let me know if you have any further questions.
