### ISSUE TITLE
Microsoft Azure Batch  Readme issue

### ISSUE THREAD

**Issue by Melanie-Ma** [Azure/azure-sdk-for-java#18805]
1.
Section [Link](https://github.com/Azure/azure-sdk-for-java/tree/master/sdk/batch/microsoft-azure-batch#pre-requisites):
![image](https://user-images.githubusercontent.com/64007802/105795302-9356c500-5fc7-11eb-90e3-357f13a93f12.png)
Suggestion:
Add Hyperlink for "A Java Developer Kit(JDK)":
https://docs.microsoft.com/java/azure/jdk/?view=azure-java-stable
Add Hyperlink for "Maven":
https://search.maven.org/artifact/com.microsoft.azure/azure-batch

@jongio for notification

**Comment by v-xuto** [comment]
Close this issue, due to PR https://github.com/Azure/azure-sdk-for-java/pull/20502 merged.
