### ISSUE TITLE
Opentelemetry Exporter Azuremonitor Sample issue

### ISSUE THREAD

**Issue by Melanie-Ma** [Azure/azure-sdk-for-java#18804]
1.  Section [Link](https://github.com/Azure/azure-sdk-for-java/blob/master/sdk/monitor/azure-opentelemetry-exporter-azuremonitor/src/samples/java/com/azure/opentelemetry/exporter/azuremonitor/EventHubsAzureMonitorExporterSample.java#L64):
![image](https://user-images.githubusercontent.com/64007802/105794334-d152e980-5fc5-11eb-9f89-a44793ef0c34.png)
Suggestion:
Change to 
```
EventHubProducerAsyncClient producer = new EventHubClientBuilder()
                                            .connectionString(CONNECTION_STRING, "<eventHub Name>")
                                            .buildAsyncProducerClient();
```

@jongio for notification

**Comment by samvaity** [comment]
Closed with #19403
