### ISSUE TITLE
[FEATURE REQ] Support CosmosDB bulk explorer  with java V4 SDK

### ISSUE THREAD

**Issue by jeffpeiyt** [Azure/azure-sdk-for-java#18801]
**Is your feature request related to a problem? Please describe.**
I saw `The bulk executor library described is available is only available for the Azure Cosmos DB Java sync SDK v2 ` [here](https://docs.microsoft.com/en-us/azure/cosmos-db/bulk-executor-java) but here it [suggests](https://docs.microsoft.com/en-us/azure/cosmos-db/performance-tips-java) upgrade to V4 SDK for better performance. 

Therefore I am confused for the best bulk operation performance, shall we use the SDK v2 with bulk explorer or update to v4? Does V4 SDK support bulk operations?  If not, we request support of bulk operations with V4 java SDK.

**Describe the solution you'd like**
we request support of bulk operations with V4 java SDK.

**Describe alternatives you've considered**
Make the bulk explorer can work with V4 sdk at the same time.

**Additional context**
n/a

**Information Checklist**
Kindly make sure that you have added all the following information above and checkoff the required fields otherwise we will treat the issuer as an incomplete report
- [x ] Description Added
- [x ] Expected solution specified

**Comment by FabianMeiswinkel** [comment]
We have bulk support in public preview in the Java SDK V4 – see https://github.com/Azure/azure-sdk-for-java/blob/49b38f7abcfe174625fa92ae56162be3d2e27a76/sdk/cosmos/azure-cosmos/src/main/java/com/azure/cosmos/CosmosAsyncContainer.java#L624-L663 and azure-sdk-for-java/BulkOperations.java at master · Azure/azure-sdk-for-java (github.com) as well as  the following links

-	azure-sdk-for-java/BulkItemRequestOptions.java at master · Azure/azure-sdk-for-java (github.com)
-	azure-sdk-for-java/BulkProcessingOptions.java at master · Azure/azure-sdk-for-java (github.com)

The tests are here – they are as close as a sample as we have right now. For GA w will also add some samples in the azure-samples repo.

azure-sdk-for-java/CosmosBulkAsyncTest.java at master · Azure/azure-sdk-for-java (github.com)

For new workloads I would definitely recommend using the V4 SDK.

**Comment by jeffpeiyt** [comment]
Found another example: https://github.com/Azure/azure-sdk-for-java/blob/683102d169186831717de0c020d329a420552df4/sdk/cosmos/azure-cosmos/src/test/java/com/azure/cosmos/CosmosBulkTest.java
