### ISSUE TITLE
Service Bus Readme issues

### ISSUE THREAD

**Issue by Melanie-Ma** [Azure/azure-sdk-for-java#18807]
1.
Section [Link](https://github.com/Azure/azure-sdk-for-java/tree/master/sdk/servicebus/azure-messaging-servicebus#azure-service-bus-client-library-for-java):
![image](https://user-images.githubusercontent.com/64007802/105796686-593af280-5fca-11eb-807a-c0ce83687852.png)
Suggestion:
Add  `Package (Maven)` and add Hyperlink for `Package (Maven)`:
https://search.maven.org/artifact/com.azure/azure-messaging-servicebus

2.
Section [Link](https://github.com/Azure/azure-sdk-for-java/tree/master/sdk/servicebus/azure-messaging-servicebus#examples):
![image](https://user-images.githubusercontent.com/64007802/105797199-d1091d00-5fca-11eb-8947-f1faa7d84300.png)
Suggestion:
For (1): Update `Receive messages and renew lock` to `Receive messages` and modify its link.
For (2): Delete this link, because there is no corresponding code snippet.

@jongio for notification

**Comment by hemanttanwar** [comment]
@Melanie-Ma Thank you for noticing this, appreciate it. We will fix this soon.

**Comment by ki1729** [comment]
Merged the PR! Thanks @frascu!
