### ISSUE TITLE
Storage blob batch Sample issues

### ISSUE THREAD

**Issue by Melanie-Ma** [Azure/azure-sdk-for-java#18809]
1.
Section [Link1](https://github.com/Azure/azure-sdk-for-java/blob/master/sdk/storage/azure-storage-blob-batch/src/samples/java/com/azure/storage/blob/batch/BlobBatchAsyncClientJavaDocCodeSnippets.java#L25), [Link2](https://github.com/Azure/azure-sdk-for-java/blob/master/sdk/storage/azure-storage-blob-batch/src/samples/java/com/azure/storage/blob/batch/BlobBatchClientJavaDocCodeSnippets.java#L28):
![image](https://user-images.githubusercontent.com/64007802/105807547-2d773700-5fe1-11eb-8f2e-d6b98b12b936.png)
Reason:
Nullpointexception occurred
Suggestion:
Change to :
```
private BlobBatchAsyncClient batchAsyncClient = new BlobBatchClientBuilder(new BlobServiceClientBuilder()
                                                                                    .endpoint(ENDPOINT)
                                                                                    .sasToken(SASTOKEN).buildClient())
                                                                                    .buildAsyncClient();
```

2.
Section [Link1](https://github.com/Azure/azure-sdk-for-java/blob/master/sdk/storage/azure-storage-blob-batch/src/samples/java/com/azure/storage/blob/batch/BlobBatchAsyncClientJavaDocCodeSnippets.java#L72), [Link2](https://github.com/Azure/azure-sdk-for-java/blob/master/sdk/storage/azure-storage-blob-batch/src/samples/java/com/azure/storage/blob/batch/BlobBatchAsyncClientJavaDocCodeSnippets.java#L94), [Link3](https://github.com/Azure/azure-sdk-for-java/blob/master/sdk/storage/azure-storage-blob-batch/src/samples/java/com/azure/storage/blob/batch/BlobBatchClientJavaDocCodeSnippets.java#L82), [Link4](https://github.com/Azure/azure-sdk-for-java/blob/master/sdk/storage/azure-storage-blob-batch/src/samples/java/com/azure/storage/blob/batch/BlobBatchClientJavaDocCodeSnippets.java#L107), [Link5](https://github.com/Azure/azure-sdk-for-java/blob/master/sdk/storage/azure-storage-blob-batch/src/samples/java/com/azure/storage/blob/batch/BlobBatchClientJavaDocCodeSnippets.java#L132), [Link6](https://github.com/Azure/azure-sdk-for-java/blob/master/sdk/storage/azure-storage-blob-batch/src/samples/java/com/azure/storage/blob/batch/BlobBatchClientJavaDocCodeSnippets.java#L57):
![image](https://user-images.githubusercontent.com/64007802/105807920-d0c84c00-5fe1-11eb-8522-f90ba0381ead.png)
Reason:
The required parameters are missing
Suggestion:
Change to :
```
        BlobContainerClient containerClient = blobServiceClient.getBlobContainerClient("<CONTAINER_NAME>");
        BlobClient blobClient1 = containerClient.getBlobClient("<BLOB_NAME1>");
        BlobClient blobClient2 = containerClient.getBlobClient("<BLOB_NAME2>");
        BlobClient blobClient3 = containerClient.getBlobClient("<BLOB_NAME3>");
```

3.
Section [Link](https://github.com/Azure/azure-sdk-for-java/blob/master/sdk/storage/azure-storage-blob-batch/src/samples/java/com/azure/storage/blob/batch/ReadmeSamples.java#L26):
![image](https://user-images.githubusercontent.com/64007802/105808053-0a00bc00-5fe2-11eb-9587-d2bc756a3a8e.png)
Reason:
The required parameters are missing
Suggestion:
Change to `new BlobServiceClientBuilder().endpoint("<YOUR_END_POINT>").sasToken("<YOUR_SAS_TOKEN>").buildClient();`

4.
Section [Link](https://github.com/Azure/azure-sdk-for-java/blob/master/sdk/storage/azure-storage-blob-batch/src/samples/java/com/azure/storage/blob/batch/ReadmeSamples.java#L28):
![image](https://user-images.githubusercontent.com/64007802/105808159-33b9e300-5fe2-11eb-8a5f-a733076cd5c3.png)
Reason:
The blob URL is incorrect
Suggestion:
Change to:
```
    private String blobUrl = String.format("https://%s.blob.core.windows.net/containerName/blobName","<YOUR_STORAGE_ACCOUNT>");
    private String blobUrl2 = String.format("https://%s.blob.core.windows.net/containerName/blobName2","<YOUR_STORAGE_ACCOUNT>");
    private String blobUrlWithSnapshot = String.format("https://%s.blob.core.windows.net/containerName/blobName?snapshot=<DateTime>","<YOUR_STORAGE_ACCOUNT>");
    private String blobUrlWithLease = String.format("https://%s.blob.core.windows.net/containerName/blobNameWithLease","<YOUR_STORAGE_ACCOUNT>");
```

@jongio for notification

**Comment by gapra-msft** [comment]
Closing due to merging the PR
