### ISSUE TITLE
[Bug/Oversight] bulkProcessingOptions is not used in processBulkOperations 

### ISSUE THREAD

**Issue by jeffpeiyt** [Azure/azure-sdk-for-java#18832]
https://github.com/Azure/azure-sdk-for-java/blob/f28826e51a3f31566483756d059baa73e18a30dc/sdk/cosmos/azure-cosmos/src/test/java/com/azure/cosmos/CosmosBulkTest.java#L107

**Comment by kushagraThapar** [comment]
@jeffpeiyt  - There are two variants on `processBulkOperations` API, one which takes `bulkProcessingOptions`. You will notice that other tests in this file uses the overloaded API: https://github.com/Azure/azure-sdk-for-java/blob/f28826e51a3f31566483756d059baa73e18a30dc/sdk/cosmos/azure-cosmos/src/test/java/com/azure/cosmos/CosmosBulkTest.java#L72
