### ISSUE TITLE
[QUERY] Inconsistency in MariaDB metrics vs Azure docs

### ISSUE THREAD

**Issue by cnuval-itrs** [Azure/azure-sdk-for-java#18830]
**Query/Question**
Currently in Microsoft.DBforMariaDB/servers, serverlog_storage_limit has an aggregation type of Average specified in the documentation https://docs.microsoft.com/en-us/azure/azure-monitor/platform/metrics-supported#microsoftdbformariadbservers.

I would like to clarify that this is expected to be Maximum. Other DBs such as below, shows that the aggregation type is Maximum :

- https://docs.microsoft.com/en-us/azure/azure-monitor/platform/metrics-supported#microsoftdbformysqlservers
- https://docs.microsoft.com/en-us/azure/azure-monitor/platform/metrics-supported#microsoftdbforpostgresqlservers

What we currently pick up in azure rest api also says that the aggregation type is Maximum 

***Why is this not a Bug or a feature Request?***
It's more on clarifying if the docs need to be updated if our assumption above is correct.

**Setup (please complete the following information if applicable):**
 - OS: Linux/Windows
 - IDE : IntelliJ
 - Version of the Library used : We are using rest-api to gather the metrics https://docs.microsoft.com/en-us/rest/api/mariadb/servers/list
 
 **Information Checklist**
 Kindly make sure that you have added all the following information above and checkoff the required fields otherwise we will treat the issuer as an incomplete report
- [x] Query Added
- [x] Setup information Added

**Comment by joshfree** [comment]
Hi @cnuval-itrs, someone from the `MariaDB` team will follow up with you shortly
