### ISSUE TITLE
[CosmosDB coordinate data to Java model issue]

### ISSUE THREAD

**Issue by NavtejSaini-MSFT** [Azure/azure-sdk-for-java#18843]
**Query/Question**
“I am trying to build a Spring Boot project with some RESTFul apis to retrieve document from Azure CosmosDB (via SQL API v3).
Here are the sample data:
```
1.	 vessel {
2.	  "mmsi": 368102360,
3.	  "location": {
4.	         "type": "Point",
5.	         "coordinates": [
6.	             -90.255,
7.	             38.5383333333
8.	         ]
9.	     },
10.	 }
```
The mapped Java model:
```
1.	 @Data
2.	 public class Vessel {
3.	     @Id
4.	     private String id;
5.	     private String mmsi;
6.	     private Location location;
7.	 }
8.	
9.	 @Data
10.	 public class Location {
11.	     private String type;
12.	     private ArrayList <Coordinate> coordinates;  
13.	 }
14.	
15.	 @Data
16.	 public class Coordinate {
17.	     Double latitude;
18.	     Double longitude;
19.	 }
```
I am hitting the error:
```
com.fasterxml.jackson.databind.exc.MismatchedInputException: Cannot construct instance of .model.Coordinate (although at least one Creator exists): no double/Double-argument constructor/factory method to deserialize from Number value (-90.255)
at [Source: UNKNOWN; line: -1, column: -1] (through reference chain: .model.Vessel["location"]->.model.Location["coordinates"]->java.util.ArrayList[0])
at com.fasterxml.jackson.databind.exc.MismatchedInputException.from(MismatchedInputException.java:63) ~[jackson-databind-2.11.2.jar:2.11.2]
```

What would be the proper mapping for the dataset?
note it works for the following def:
1.	 private ArrayList coordinates;

But it would be nice to define a Coordinate object to better object traversal and interpretation.”

***Why is this not a Bug or a feature Request?***
A clear explanation of why is this not a bug or a feature request?

**Setup (please complete the following information if applicable):**
 - IDE : [e.g. IntelliJ]
 - Version of the Library used
 
 **Information Checklist**
 Kindly make sure that you have added all the following information above and checkoff the required fields otherwise we will treat the issuer as an incomplete report
- [ ] Query Added
- [ ] Setup information Added

**Comment by NavtejSaini-MSFT** [comment]
@kirankumarkolli @mbhaskar The issue came on our Q&A platform - here are the details - =====================================================================
Issue: [https://docs.microsoft.com/en-us/answers/questions/242939/index.html]
You can track and update accordingly the Workitem for this escalation here: [https://msazure.visualstudio.com/One/_workitems/edit/9203723]
=====================================================================

**Comment by NavtejSaini-MSFT** [comment]
@kirankumarkolli @mbhaskar Here is the Q&A issue - https://docs.microsoft.com/en-us/answers/questions/242939/index.html that we raised issue in reference too.

**Comment by saragluna** [comment]
Not sure about this, but seems like `coordinates` is an array of double values, instead of an array of `Coordinate` objects.

**Comment by NavtejSaini-MSFT** [comment]
@mbhaskar Can you confirm the same.

**Comment by NavtejSaini-MSFT** [comment]
@kirankumarkolli @mbhaskar Can you please confirm here.

**Comment by mbhaskar** [comment]
"coordinates": [
	             -90.255,
	             38.5383333333
	         ]
This json represents an array of numbers, so the deserialization type would be a Array/List.
An alternative could be just to read the data into a JsonNode object instead and then try custom deserialization in the way you need in your application.
