### ISSUE TITLE
[BUG] azure-batch - BatchServiceClient and BatchClient Jobs Paging not working

### ISSUE THREAD

**Issue by gjlumsden** [Azure/azure-sdk-for-java#18853]
**Describe the bug**
In SDK versions > 5.0.1, when making a request to list jobs using `BatchServiceClient` `currentPage().nextPageLink()` is always null and `hasNextPage()` is always false, even if the REST response includes the `odata.nextLink` property.

The incorrect behaviour has been observed with an explicit page size set using `withMaxResults(N)` and with the default of 1000 Jobs per page.

If using `BatchClient` instead of `BatchServiceClient`, then the result does not page correctly and stops after 1000 jobs.

Version 5.0.1 of the SDK has the correct behaviour, but none of the subsequent versions do. Observing the requests using Fiddler shows that the `odata.nextLink` property is returned when expected but is not used by the SDK.

Note: I was unable to test version 6.0.0, but all other versions > 5.x were tested.

***Exception or Stack Trace***
N/A

**To Reproduce**
Instantiate a `BatchServiceClient` object and request a page of Jobs. When the number of Jobs in the batch account (and matched by the filter) exceeds the maximum page size (either set explicitly, or 1000 implicitly), `currentPage().nextPageLink()` is null and `hasNextPage()` returns false meaning, even if there are additional pages, it is impossible to retrieve and enumerate the results.

***Code Snippet***
```java
public int getJobCount() {
	BatchServiceClient client = getBatchServiceClient();
	// joda time
	DateTime from = new DateTime(2021, 01, 26, 0, 0, 0, DateTimeZone.UTC);
	DateTime to = new DateTime(2021, 01, 27, 0, 0, 0, DateTimeZone.UTC).minusMillis(1);
	DateTimeFormatter dtf = DateTimeFormat.forPattern("yyyy-MM-dd'T'HH:mm':00.000Z'");

	JobListOptions options = new JobListOptions();
	options.withFilter("executionInfo/poolId eq '" + BATCH_POOL_NAME + "' and executionInfo/startTime ge DateTime'"
			+ dtf.print(from) + "' and executionInfo/startTime le DateTime'" + dtf.print(to) + "'");
			//.withMaxResults(10);

	int count = 0;
	PagedList<CloudJob> jobs = null;
	do {
		if (jobs == null) {
			jobs = client.jobs().list(options);
		} else {
			// This line is never reached even when there are more pages.
			jobs = client.jobs().listNext(jobs.currentPage().nextPageLink());
		}

		if (jobs != null) {
			count += jobs.size();
		}
	} while (jobs != null && jobs.hasNextPage());// Always false >5.0.1

	//returns 1000 - expect 1900.
	return count;
}
```

**Expected behavior**
`currentPage().nextPageLink()` should be set to the value of `odata.nextLink` and `hasNextPage()` should be true.

**Screenshots**
N/A

**Setup (please complete the following information):**
 - OS: Windows 10
 - IDE : VS Code
 - Version of the Library used: >5.0.1 (up to and including 9.x)

**Additional context**
Fiddler traces and repro project can be provided.

**Information Checklist**
Kindly make sure that you have added all the following information above and checkoff the required fields otherwise we will treat the issuer as an incomplete report
- [x] Bug Description Added
- [x] Repro Steps Added
- [x] Setup information Added

**Comment by gjlumsden** [comment]
A quick follow up - I am aware that the following line:

```java
count += jobs.size();
```

will automatically load all pages before returning a result (and when enumerating `jobs`, paging will be applied automatically), meaning in the code sample I shared `jobs.hasNextPage()` will always be false anyway. However, in versions >5.0.1, the result of `jobs.size()` (and enumerating `jobs`) does not match the expected value, meaning paging is not working in that context either. 

Here is an updated code sample which doesn't trigger automatic paging and will reproduce the problem of `jobs.hasNextPage()` always being false and loading the next page never being reached:

```java
public int getJobCount() {
	BatchServiceClient client = getBatchServiceClient();
	// joda time
	DateTime from = new DateTime(2021, 01, 26, 0, 0, 0, DateTimeZone.UTC);
	DateTime to = new DateTime(2021, 01, 27, 0, 0, 0, DateTimeZone.UTC).minusMillis(1);
	DateTimeFormatter dtf = DateTimeFormat.forPattern("yyyy-MM-dd'T'HH:mm':00.000Z'");

	JobListOptions options = new JobListOptions();
	options.withFilter("executionInfo/poolId eq '" + BATCH_POOL_NAME + "' and executionInfo/startTime ge DateTime'"
			+ dtf.print(from) + "' and executionInfo/startTime le DateTime'" + dtf.print(to) + "'");
			// .withMaxResults(10);

	int count = 0;
	PagedList<CloudJob> jobs = null;
	do {
		if (jobs == null) {
			jobs = client.jobs().list(options);
		} else {
			// This line is never reached even when there are more pages.
			jobs = client.jobs().listNext(jobs.currentPage().nextPageLink());
		}

		if (jobs != null) {
			count += jobs.currentPage().items().size();
			System.out.println("Page size: " + jobs.currentPage().items().size());
			System.out.println("Count: " + count);
		}

	} while (jobs != null && jobs.hasNextPage());// Always false >5.0.1

	// returns 1000 - expect 1900.
	return count;
}
```

**Comment by gingi** [comment]
Hi @gjlumsden. Thanks for reporting the issue. This involves a bug with the JSON deserializer at the Autorest library (it mishandles keys that include a "."). There is already [a fix](https://github.com/Azure/autorest-clientruntime-for-java/pull/696) that is pending merge and release.
