### ISSUE TITLE
[Perf] Print dependency versions at perf framework startup

### ISSUE THREAD

**Issue by mikeharder** [Azure/azure-sdk-for-java#18882]
The perf framework should print the versions of all `com.azure` dependencies at startup.  One way is to create a `FileSystem` from the JAR used to load the perf app, then inspect the files `META-INF/maven/com.azure/*/pom.properties` inside the JAR.

.NET Implementation: https://github.com/Azure/azure-sdk-for-net/blob/5b64e5829fecf66929dc6802f64184a0a3b51546/common/Perf/Azure.Test.Perf/PerfProgram.cs#L71-L78

**Comment by g2vinay** [comment]
Implemented the test [here](https://github.com/Azure/azure-sdk-for-java/blob/main/sdk/storage/azure-storage-perf/src/main/java/com/azure/storage/blob/perf/UploadBlobTest.java#L36)

**Comment by mikeharder** [comment]
@g2vinay: The link above doesn't seem to have anything to do with printing dependency versions:

https://github.com/Azure/azure-sdk-for-java/blob/main/sdk/storage/azure-storage-perf/src/main/java/com/azure/storage/blob/perf/UploadBlobTest.java#L36
