### ISSUE TITLE
[BUG] Azure Spring Data Cosmos @EnableCosmosAuditing can't work in Java11

### ISSUE THREAD

**Issue by saragluna** [Azure/azure-sdk-for-java#18892]
Creating this issue from comment https://github.com/Azure/azure-sdk-for-java/pull/13389#issuecomment-770452471 @luissalgadofreire

**Describe the bug**
Hi. I'm running Spring Boot 2.3.3.RELEASE with Azure Spring Data Cosmos 3.3.0 on Java 11. When I add @EnableCosmosAuditing to my CosmosDbConfig class or the Application class, I get the following error.

```
Caused by: java.lang.reflect.InaccessibleObjectException: Unable to make com.azure.spring.data.cosmos.core.mapping.CosmosAuditingRegistrar() accessible: module com.azure.spring.data.cosmos does not "opens com.azure.spring.data.cosmos.core.mapping" to module spring.core
```
Without the annotation, integration with Cosmos DB works fine.

Is this a bug that disallows using java 9+ modules or am I missing something?

**Information Checklist**
Kindly make sure that you have added all the following information above and checkoff the required fields otherwise we will treat the issuer as an incomplete report
- [x] Bug Description Added
- [x] Repro Steps Added
- [x] Setup information Added

**Comment by kushagraThapar** [comment]
@saragluna  - I believe we just need to add either of these in module-info.java file: 
```
opens com.azure.spring.data.cosmos.core to spring.core;
```
OR 
```
opens com.azure.spring.data.cosmos.core.mapping to spring.core;
``` 

Can you please verify if either of these work with your Java 11 sample here - https://github.com/Azure-Samples/azure-spring-data-cosmos-java-sql-api-getting-started
If so, let's fix it.

**Comment by saragluna** [comment]
@kushagraThapar that's my plan. I will try it today.

**Comment by saragluna** [comment]
@kushagraThapar PR created, please help review it. I've tested with the sample and it could work.
