### ISSUE TITLE
VirtualMachineImages.getImage() with staged (preview) image doesn't check `version`

### ISSUE THREAD

**Issue by jasonbw** [Azure/azure-sdk-for-java#1890]
When calling `VirtualMachineImages.getImage(region, publisher, offer, sku, version)` with a staged image (where the offer ends with "-preview") as long as the other fields are valid then any `version` will return an image, but when you go to create the VM it throws an error (version here is `99.99.99`):
```
com.microsoft.azure.CloudException: The platform image 'cloudera:cloudera-centos-os-preview:7_2:99.99.99' is not available. Verify that all fields in the storage profile are correct.
```

**Comment by anuchandy** [comment]
@jasonbw could you share the VM request payload (which contains StorageProfile and Plan)?

**Comment by jasonbw** [comment]
@anuchandy can you give me an example of what you're looking for?

**Comment by jasonbw** [comment]
Did more probing on this:

Calling `VirtualMachineImages.getImage(region, publisher, offer, sku, version)` with a preview image and the version as `"latest"` returns `null`

**Comment by anuchandy** [comment]
I tried to fetch the same image you are using with the following code:

```java
VirtualMachineImage image = computeManager.virtualMachineImages().getImage(Region.US_EAST, 
    "cloudera",
    "cloudera-centos-os-preview", 
    "7_2", 
     "99.99.99");
```

and I got null. My assumption is, since these images are staged images, they are not available in market place for other subscriptions to consume.

We need to get help from CRP, so could you turn on the log and run the following code:

```java
        // Get image
        //
        VirtualMachineImage image = computeManager.virtualMachineImages().getImage(Region.US_EAST,
                "cloudera",
                "cloudera-centos-os-preview",
                "7_2",
                "99.99.99");


        // Create
        //
        computeManager.virtualMachines()
            .define(VMNAME)
                .withRegion(REGION)
                .withNewResourceGroup(RG_NAME)
                .withNewPrimaryNetwork("10.0.0.0/28")
                .withPrimaryPrivateIPAddressDynamic()
                .withoutPrimaryPublicIPAddress()
                .withSpecificLinuxImageVersion(image.imageReference())
                .withRootUsername("Foo12")
                .withRootPassword("abc!@#F0orL")
            .create();
```

we can share this log with CRP, they should be able to help us to narrow it down.

**Comment by jasonbw** [comment]
That's correct - only whitelisted subscriptions have access to them. If there's a staged image that you have access to that might work for repro-ing.

Is there something special I need to do to turn on logging / how do I do it?

**Comment by anuchandy** [comment]
You can turn on logging by setting log level as `LogLevel.BODY_AND_HEADERS`

```java
            Azure azure = Azure.configure()
                    .withLogLevel(LogLevel.BODY_AND_HEADERS)
                    .authenticate(credFile)
                    .withDefaultSubscription();
```

**Comment by anuchandy** [comment]
@jasonbw not sure this issue is solved through azure ticket, if not please share the log, we can followup with compute team.

**Comment by jasonbw** [comment]
@anuchandy - I have not had time to come back to this. Should I close this issue for now, and re-open it when I've had a chance to circle back?

**Comment by anuchandy** [comment]
@jasonbw - fine we can close this now and re-open when you have the log to share with compute team.

**Comment by jasonbw** [comment]
Ok, I'll do that. 

Closing for now - will re-open when I have the logs
