### ISSUE TITLE
Unable to set tags  (v1.1.0)

### ISSUE THREAD

**Issue by niteshjain1** [Azure/azure-sdk-for-java#1891]
If tag key name contains "." API fails with error 
`Exception : The request content was invalid and could not be deserialized: 'Error reading string. Unexpected token: StartObject. Path 'tags.dummy', line 1, position 42.'.`

Tag key  = "dummy.abcd"

**Comment by martinsawicki** [comment]
@jianghaolu feels like a runtime/serialization issue?

**Comment by martinsawicki** [comment]
could be related to https://github.com/Azure/azure-sdk-for-java/issues/1755?

**Comment by niteshjain1** [comment]
This works fine for resource groups, for other resources it breaks.

**Comment by jianghaolu** [comment]
This is fixed via https://github.com/Azure/autorest-clientruntime-for-java/pull/232.

**Comment by martinsawicki** [comment]
getting released in runtime v1.1.1 in a few days
