### ISSUE TITLE
[QUERY] async client to read file events and read file contents.

### ISSUE THREAD

**Issue by wernerdaehn** [Azure/azure-sdk-for-java#18927]
**Query/Question**
The goal is simple: Using Event Grid I post a notification for file changes in ESB and for each new file I want to read the file, do something with it and move to the next message. However I cannot manage to create the sequential processing using the async client.

From a normal coding point of view the logic would be

    for each message {
      filecontent = readFS(message.path);
    }

How can the same be done with an async client?
The logical solution would be to use the ServiceBusReceiverAsyncClient to get all messages and within each message read the whole file using the syncronous client. But that triggers an exception saying that an async client cannot have a blocking Flux.

What I came up with is this but there I have the problem of messages being processed in parallel while the file is read.

		ServiceBusReceiverAsyncClient receiver = ...
		Disposable subscription = receiver
				.receiveMessages()
				.map(message -> {
					System.out.println("Received Message " + message.getMessageId() +
						 " in Thread " + Thread.currentThread().getName());
					DataLakeFileAsyncClient c = asyncfsclient.getFileAsyncClient("patient1.json");
					Disposable r = c
						.read()
						.collectList()
						.map(list -> {
							return Tuples.of(list, message);
						})
						.subscribe(tuple -> {
							try (ByteArrayOutputStream out = new ByteArrayOutputStream();) {
								for (ByteBuffer b : tuple.getT1()) {
									out.write(b.array());
								}
								System.out.println("Process File"); // <---- breakpoint
							} catch (IOException  e) {
								throw new RuntimeException();
							}
						});
					return receiver.complete(message);
				})
				.subscribe(aVoid -> {
				}, error -> {
					System.out.println(error);
				}, () -> {
					System.out.println("Azure queue reader shut down");
				});

As the inner code has a Disposable r, it is not blocking and hence I get multiple "Received Message.." lines from the receiver.map if I set a breakpoint in the print "Process File".

***Why is this not a Bug or a feature Request?***
I am not sure yet what the problem is. The use case should be typical. Is it my lack of understanding of react? Is it a documentation issue? Can this be solved even??

**Comment by joshfree** [comment]
@YijunXieMS can you please take a look?

**Comment by YijunXieMS** [comment]
Hi @wernerdaehn 
Could you try if this works for you?
In reactive streaming paradigm, the data flows from one operator to another by "return".

A side question, you mentioned "EventGrid". Do you use EventGrid to send events and use ServiceBus as the event handler for the EventGrid subscription?

```java
    ServiceBusReceiverAsyncClient receiver = ...
    Disposable subscription = receiver
            .receiveMessages()
            .flatMap(message -> {
                DataLakeFileAsyncClient c = asyncfsclient.getFileAsyncClient("patient1.json");
                return c.read()
                        .collectList()
                        .map(list -> {
                            try (ByteArrayOutputStream out = new ByteArrayOutputStream();) {
                                for (ByteBuffer b : list) {
                                    out.write(b.array());
                                }
                                System.out.println("Process File"); // <---- breakpoint
                            } catch (IOException e) {
                                throw new RuntimeException();
                            }
                            return message;
                        });
            })
            .map(receiver::complete)
            .subscribe(aVoid -> {
            }, error -> {
                System.out.println(error);
            }, () -> {
                System.out.println("Azure queue reader shut down");
            });
```


Do you send events to Event Grid or Service Bus?

**Comment by wernerdaehn** [comment]
Testing it right now.
In the storage account I have created an Event handler that has as an Endpoint an ESB using the standard notification payload format.

**Comment by wernerdaehn** [comment]
Same thing happens. I set a breakpoint where the file will be processed and this breakpoint is entered immediately with multiple parallel threads. So 12 messages are dequeued immediately instead of one message after the other.

Note: I have added a print statement as first statement of the flatMap(), hence the output in the Console.

![image](https://user-images.githubusercontent.com/13607767/106700265-c828d480-65e4-11eb-9f6f-187d5965722e.png)

**Comment by YijunXieMS** [comment]
Could you try concatMap instead of flatMap?

**Comment by wernerdaehn** [comment]
With that the behavior is different, just one message is read from the queue but it fails with an error:

```
Received Message 78abfa8b-d553-4661-859e-d33956b6f6e2 in Thread boundedElastic-2
Process File
com.azure.messaging.servicebus.ServiceBusException: block()/blockFirst()/blockLast() are blocking, which is not supported in thread reactor-http-epoll-1
Received Message f1b12a89-e1cd-4e2c-801b-5c2e00b64197 in Thread reactor-http-epoll-1
```

**Comment by YijunXieMS** [comment]
Adding @hemanttanwar to look into the problem. Maybe somewhere a hidden "block()" is called.

**Comment by hemanttanwar** [comment]
@wernerdaehn 
I did setup azure resources and try to run this example. It works and sequentially  process one by one. And I do not see the error which you mentioned above.

```java
ServiceBusReceiverAsyncClient receiver; // set up your client.
DataLakeFileSystemAsyncClient fileSystemAsyncClient; //  set up your client.

Disposable subscription = receiver
                .receiveMessages()
                .flatMapSequential(message -> {   // process each message sequentially
                    DataLakeFileAsyncClient dlAsyncClient = fileSystemAsyncClient.getFileAsyncClient("patient1.json");
                    return dlAsyncClient.read().collectList()
                            .doOnNext((byteBuffers) -> {
                                try (ByteArrayOutputStream out = new ByteArrayOutputStream();) {
                                    for (ByteBuffer b : byteBuffers) {
                                        out.write(b.array());
                                    }
                                    System.out.println(new Date() + "Process File  for sequenceNumber:" +message.getSequenceNumber());
                                } catch ( IOException e) {
                                    throw new RuntimeException();
                                }
                            })
                            .then(receiver.complete(message)) //  complete the message
                            .thenReturn(message);
                }, 1) // use one thread to process the messages. 
                .subscribe(m-> {
                    System.out.println(new Date()  + "Finished message SequenceNumber: " + m.getSequenceNumber());
            }); 
```

**Comment by wernerdaehn** [comment]
Unfortunately no, this does triggers an error after processing the first message.
I have copied your exact code and when I execute it, it processes one message correctly, waits for a minute and then fails. There are 15 messages in the queue.

```
Fri Feb 05 05:57:42 UTC 2021Process File  for sequenceNumber:69
Exception in thread "main" reactor.core.Exceptions$BubblingException: com.azure.messaging.servicebus.ServiceBusException: Update disposition request timed out., errorContext[NAMESPACE: rtdiio.servicebus.windows.net, PATH: filechanges, REFERENCE_ID: filechanges_554623_1612504623171, LINK_CREDIT: 0]
	at reactor.core.Exceptions.bubble(Exceptions.java:173)
```

**Comment by hemanttanwar** [comment]
@wernerdaehn 
I did put the sample I am using in this public repo with output how I see. May be the clients are configured in different way. I am also documenting the output as  I see. 
I am not sure what could be difference in your and mine environment. 
By putting my whole program, my goal is to pin point some issues or environment differences which could be cause of the exception you see.

https://github.com/hemanttanwar/code-sampels#service-bus-receive-message-and-process-by-data-lake-client-sample

**Comment by wernerdaehn** [comment]
At the end I learned about the ProcessorInterface and that gives me exactly what I needed.
https://github.com/Azure/azure-sdk-for-java/blob/master/sdk/servicebus/azure-messaging-servicebus/src/samples/java/com/azure/messaging/servicebus/ServiceBusProcessorSample.java

**Comment by hemanttanwar** [comment]
@wernerdaehn  Appreciate you using our library.
