### ISSUE TITLE
Opentelemetry azure monitor exporter: Need a comprehensive example 

### ISSUE THREAD

**Issue by aelmanaa** [Azure/azure-sdk-for-java#18930]
Hello,

it would be nice if we could get a full example which includes a set of micoservices communicating between each other and which are instrumented with opentelemtry codeless sdk  ( https://github.com/open-telemetry/opentelemetry-java-instrumentation) and how we could integrate azure-monitor exporter.
Actually there are already few exampels online how to use Prometheus, logging (console stream) , Jaeger or Zipkin. It would be interesting to show case azure monitor exporter as well.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fec6e42e-9ab2-bce9-6cd5-20e8db6d7785
* Version Independent ID: 3392c066-2025-de8b-1f51-0beab28305f0
* Content: [Azure Monitor OpenTelemetry Exporter client library for Java](https://docs.microsoft.com/en-us/java/api/overview/azure/opentelemetry-exporters-azuremonitor-readme-pre?view=azure-java-stable)
* Content Source: [docs-ref-services/opentelemetry-exporters-azuremonitor-readme-pre.md](https://github.com/Azure/azure-docs-sdk-java/blob/master/docs-ref-services/opentelemetry-exporters-azuremonitor-readme-pre.md)
* Product: **azure**
* Technology: **azure**
* GitHub Login: @maggiepint
* Microsoft Alias: **magpint**

**Comment by joshfree** [comment]
@lmolkova this is a rather old issue that fell through the cracks on @srnagar's plate;  since it's OpenTelemetry, could you please verify/close as appropriate
