### ISSUE TITLE
We experienced  ~1 minute latency while sending messages to EventHub from the upstream application on 30.01.2021, and that continued for ~10 minutes.

### ISSUE THREAD

**Issue by koustavnaharoy-ayla** [Azure/azure-sdk-for-java#18936]
**Query/Question**
We experienced  ~1 minute latency while sending messages to EventHub from the upstream application on 30.01.2021, and that continued for ~10 minutes.

 

***Why is this not a Bug or a feature Request?***
A clear explanation of why is this not a bug or a feature request?
As per the previous discussion with AZURE support colleague from Microsoft, there was a suggestion came to integrate with the newer azure sdk, azure-messaging-eventhubs 5.3.1 instead of using azure sdk 2.1.0. But that did not yield any visible results.

 

**Setup (please complete the following information if applicable):**
- OS: Kubenetes
- IDE : IntelliJ
- Version of the Library used: 5.3.1

**Information Checklist**
Kindly make sure that you have added all the following information above and checkoff the required fields otherwise we will treat the issuer as an incomplete report
- [✓] Query Added
- [✓] Setup information Added

**Comment by joshfree** [comment]
Hi @koustavnaharoy-ayla can you share information so we can assist you?

Are you able to reproduce the latency issue using the azure-messaging-eventhubs 5.3.1 SDK?

You mentioned a support colleague, do you have an open support ticket (opened through the Azure Portal)?  If so, that would be the best channel for working with support directly.

Thanks

**Comment by walt-ayla** [comment]
@joshfree The Azure Support team pointed us to you.  They are not seeing any issued on the Azure side.

**Comment by koustavnaharoy-ayla** [comment]
> Hi @koustavnaharoy-ayla can you share more details on the specifics of the application (or logs / traces) so we can better assist
> Are you able to reproduce the latency issue using the azure-messaging-eventhubs 5.3.1 SDK? You mentioned a support colleague, do you have an open support ticket (opened through the Azure Portal)? If so, that would be the best channel for working with support directly.
> 
> Thanks

@joshfree Yes, we are getting the latency issue even with the the azure-messaging-eventhubs 5.3.1 SDK

**Comment by conniey** [comment]
@koustavnaharoy-ayla @walt-ayla Thanks for reporting this issue. Without more details, it's impossible to diagnose. Can you provide:

1. Enable logging in the Azure SDK. Steps are: https://github.com/Azure/azure-sdk-for-java/wiki/Logging-with-Azure-SDK
1. Provide a small repro.
1. Details of your Event Hubs set-up? (ie. how many partitions, throughput units, etc?)

**Comment by walt-ayla** [comment]
@conniey  For #3.  We do not control the EventHub in Azure.  That belongs to our customer.  The Event Hub azure support team has looked at it and is a appropriately configured.  Their research has shown it is not on the Azure side. 

I can give you the contact we were working with if you would like to contact them.

**Comment by conniey** [comment]
> @conniey For #3. We do not control the EventHub in Azure. That belongs to our customer. The Event Hub azure support team has looked at it and is a appropriately configured. Their research has shown it is not on the Azure side.

I wanted to ask about the details to see if I could provide the same set-up locally, but not necessary. 1 and 2 are the important ones.

**Comment by walt-ayla** [comment]
@conniey Here is the Event Hub configuration the events are being sent to:
Region= Canada Central
Throughput Units = 2 units
Auto-Inflate throughput = 4 units
