### ISSUE TITLE
how to get sddl string to construct permission string in java sdk

### ISSUE THREAD

**Issue by niranjanbandi** [Azure/azure-sdk-for-java#18931]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a57d1b3c-813e-5c48-4ed7-013f11473f7f
* Version Independent ID: 8b2f0d3f-d959-d5bc-7b47-521248ac056c
* Content: [Azure Storage libraries for Java](https://docs.microsoft.com/en-us/java/api/overview/azure/storage?view=azure-java-stable)
* Content Source: [docs-ref-services/storage.md](https://github.com/Azure/azure-docs-sdk-java/blob/master/docs-ref-services/storage.md)
* Service: **storage**
* GitHub Login: @tamram
* Microsoft Alias: **tamram**

**Comment by amishra-dev** [comment]
@niranjanbandi I am assuming this is for the Files share SDK. We do not have a built in way to do this. You will need to use a third part library to do this, quick search threw up a few options (for example https://github.com/Saine87/SDDL-parser/blob/master/src/main/java/sddl/Sddl.java)
