### ISSUE TITLE
How do you add a parameter for the main class?

### ISSUE THREAD

**Issue by markthegrea** [Azure/azure-sdk-for-java#18933]
We are trying to add a parameter (using spring boot) to the startup.  We need to add:

--spring.profiles.active=dev

But are failing badly.  Can you document this usecase?

Normally we use and this works but we cannot figure out how to add this parameter in the xml given.:

set PATH=%PATH%;%JAVA_HOME%/bin
java -cp blah-0.0.1.jar com.foo.runner.Application --spring.profiles.active=dev

**Comment by saragluna** [comment]
Please try this -Dspring.profiles.active=dev instead of --spring.profiles.active=dev.

**Comment by yiliuTo** [comment]
Close this issure due to no response for a long time from the customer.
