### ISSUE TITLE
[QUERY] Failover with a single Private endpoint with CosmosDB

### ISSUE THREAD

**Issue by jeffpeiyt** [Azure/azure-sdk-for-java#18955]
**Query/Question**

We have a single private enpoint in one region (in a subnet in east US) while the Cosmos Acount was created south central and is globally replicated.

We are wondering how does the failover work if the private endpoint's region goes down?  How we can prevent the private endpoint becomes the single point of failure? Do you mean the regional failure is internal to the DB and still requires the use of the same private endpoint?

https://docs.microsoft.com/en-us/azure/cosmos-db/high-availability#high-availability-with-azure-cosmos-db-in-the-event-of-regional-outages
```
Multi-region accounts configured with multiple-write regions will be highly available for both writes and reads. Regional failovers are detected and handled in the Azure Cosmos DB client. They are also instantaneous and don't require any changes from the application.
```

https://docs.microsoft.com/en-us/azure/private-link/private-endpoint-overview
```
Multiple private endpoints can be created using the same private link resource. For a single network using a common DNS server configuration, the recommended practice is to use a single private endpoint for a given private link resource to avoid duplicate entries or conflicts in DNS resolution.
```

***Why is this not a Bug or a feature Request?***
It is a question 

**Setup (please complete the following information if applicable):**
 - OS: mac os
 - IDE : IntelliJ
 - Version of the Library used: 4.11.0
 
 **Information Checklist**
 Kindly make sure that you have added all the following information above and checkoff the required fields otherwise we will treat the issuer as an incomplete report
- [x] Query Added
- [x] Setup information Added

**Comment by kushagraThapar** [comment]
@simplynaveen20 - can you please answer the question here ?

**Comment by ankitavyas** [comment]
Hi, I am running into same issue. Is this answered?

**Comment by kushagraThapar** [comment]
@simplynaveen20  - ping!

**Comment by simplynaveen20** [comment]
Reaching out to the n/w private endpoint team , will post once we get the answer

**Comment by wmengmsft** [comment]
From Cosmos DB side, Private Endpoint should work with Cosmos DB regional failover. For each Private Endpoint, multiple private IPs are created: one for the account's global endpoint and one for each of the account's regional endpoint. If you have enabled Private DNS integration, then from within the VNet these endpoints will automatically resolve to the above private IPs. Cosmos DB regional failover then works as usual. For example, if you configured a Cosmos DB client with the global endpoint + enabled endpoint discovery, and then during an outage Cosmos DB performed automatic failover of the write region, your client will pick up the new write region.

This does not answer what happens on the Azure Networking side during such an outage. E.g. in the event of an East US outage, will an application/VNet in West US still able to resolve Private DNS and send requests to private IPs associated with a Private Endpoint in East US (that is made accessible via VNet peering)? Such questions should be answered by Azure Networking teams as it is beyond the scope of Cosmos DB team.
