### ISSUE TITLE
Network watcher: rename PcProtocol to PacketCaptureProtocol

### ISSUE THREAD

**Issue by lenala** [Azure/azure-sdk-for-java#1895]
Would be nice to rename PcProtocol autogenerated class to PacketCaptureProtocol to make it more self-explanatory and consistent with the rest of sdk.
Same for PcStatus and PcError.
Corresponding issue in swagger spec repo:
https://github.com/Azure/azure-rest-api-specs/issues/1598

**Comment by martinsawicki** [comment]
since it's already tracked in the proper repo, closing it here.
