### ISSUE TITLE
[QUERY] How to integration test an app using SecretClient

### ISSUE THREAD

**Issue by chris-j-h** [Azure/azure-sdk-for-java#18956]
***Query/Question***
Are there any dev or in-memory/local implementations of Key Vault that can be deployed to enable integration testing of an app using `SecretClient`, or perhaps other techniques that don't require knowledge of the underlying Key Vault APIs?

**Further context**
I would like to add integration tests to my code which uses `SecretClient::getSecret`.

I don't want to create a live Key Vault resource and have to consider the pricing that will incur (particularly when CI could run the tests frequently).

I have identified the following options which do not seem ideal:

* Mock a `SecretClient` delegate to return a known `KeyVaultSecret`
    * This is fine for a unit test but doesn't test if the built `SecretClient` can actually communicate with a Key Vault (e.g. if vault URL and auth credentials are applied correctly)
* Use `com.azure:azure-core-test` in `PLAYBACK` mode to mock the HTTP responses from Key Vault
    * This requires me to have in-depth knowledge of the expected HTTP requests and responses for Key Vault, as well as Azure's challenge-based auth handshake process
    * This does allow me to verify the `SecretClient` is being built with the correct vault URL and user-provided auth credentials 
    * But this adds a level of detail to my tests that will make them susceptible to changes to the Key Vault or challenge-based auth APIs

Ideally, I would create some form of test Key Vault, populate it with secrets, and make sure that my app can retrieve them without having to use live infra or have a dependency on the underlying implementation of `SecretClient`.

***Why is this not a Bug or a feature Request?***
User query, not an issue report.

***Setup (please complete the following information if applicable):***
`com.azure:azure-security-keyvault-secrets:4.2.4`
 
***Information Checklist***
 Kindly make sure that you have added all the following information above and checkoff the required fields otherwise we will treat the issuer as an incomplete report
- [x] Query Added
- [x] Setup information Added

**Comment by joshfree** [comment]
@vcolin7 could you please follow up with @chris-j-h on this inquiry?

**Comment by jainswati02** [comment]
I am in a similar situation, would like to know if we have any option to use dev or in-memory/local implementations of Key Vault for integration tests.

**Comment by madkroll** [comment]
Same here. SDK works perfectly, but can't find any test tooling for integration with Azure KeyVault.

**Comment by chris-j-h** [comment]
Hi @vcolin7 @joshfree any update on this?  Seems like there's a fair amount of interest in this area.

**Comment by vcolin7** [comment]
@jainswati02 @madkroll @chris-j-h One way to achieve this without much trouble and having to know a lot about the Key Vault service's requests and responses is to write your tests to include a recording and playback policy in your client's HTTP pipeline, just like we do to develop unit tests for the Key Vault SDK. You would need to leverage the `azure-core-test` library:
 
```xml
<dependency>
    <groupId>com.azure</groupId>
    <artifactId>azure-core-test</artifactId>
    <version>1.5.3</version>
</dependency>
```

Here is some sample code for a very simple test:

```java
public class RecordTest extends TestBase {
    @Test
    public void listKeysTest(){
        KeyClient keyClient = new KeyClientBuilder()
            .credential(new DefaultAzureCredentialBuilder().build())
            .vaultUrl("https://<your-key-vault-name>.vault.azure.net/")
            .addPolicy(interceptorManager.getRecordPolicy()) // Here we add the recording/playback policy
            .buildClient();
        PagedIterable<KeyProperties> propertiesOfKeys = keyClient.listPropertiesOfKeys();
        assert propertiesOfKeys.stream().count() != 0;
    }
}
```

To record the test results, you would have to run the test the service at least once by setting the environment variable `AZURE_TEST_MODE=RECORD`, but after that you can simply change it to `AZURE_TEST_MODE=PLAYBACK` or remove it entirely, as that's the default value for said variable. Additionally, there is one more test mode (`LIVE`) for when you want the framework not to record anything and just run against the service.

**Comment by chris-j-h** [comment]
@AlexGhiondea @vcolin7 thanks for the info about the recording framework. Just to be clear, this requires connecting to a real key vault service at least once to record the expected result, but from that point on the recording can be used in place of the real service?  

If so that sounds like it could be what we're looking for, thanks.

**Comment by AlexGhiondea** [comment]
@chris-j-h that is correct. Please let us know if there is anything else we can help with!

**Comment by chris-j-h** [comment]
Closing issue - all queries so far have been answered.
