### ISSUE TITLE
Support for Azure Container Instances

### ISSUE THREAD

**Issue by rtyler** [Azure/azure-sdk-for-java#1896]
I'm sure this is planned, but I would like to register my interest for Azure Container Instance support from this SDK :smile:

**Comment by martinsawicki** [comment]
@milismsft here's your tracking issue

**Comment by martinsawicki** [comment]
(...and not merely tangentially related to https://github.com/Azure/azure-sdk-for-java/pull/1897 😉 )

**Comment by martinsawicki** [comment]
shipped in v1.3
