### ISSUE TITLE
[BUG] passing partition key for reading conflict is not consistent with other APIs

### ISSUE THREAD

**Issue by moderakh** [Azure/azure-sdk-for-java#18979]
see the existing sample
https://github.com/Azure-Samples/azure-cosmos-java-sql-api-samples/blob/main/src/main/java/com/azure/cosmos/examples/conflictfeed/async/SampleConflictFeedAsync.java#L324-L325

for Document read apis we explicitly ask PartitionKey to be passed along id for read container.readItem(id, pk, ..) we should have similar API for conflict read and deprecate the apis for setting partition key in the ConflictOptions.

relevant CRI:
https://portal.microsofticm.com/imp/v3/incidents/details/226232248/home

**Comment by kushagraThapar** [comment]
We no longer plan to do this.
