### ISSUE TITLE
How can I convert SDK response to json using Jackson?

### ISSUE THREAD

**Issue by jatins** [Azure/azure-sdk-for-java#1898]
I want to convert an instance of `com.microsoft.azure.management.compute.VirtualMachine` to json using Jackson. But some of the getters in the SDK make REST api calls :woman_facepalming: , and JSON serialization gets stuck in a loop of multiple api calls.

**Screenshot**

<img width="832" alt="screen shot 2017-08-29 at 4 30 47 pm" src="https://user-images.githubusercontent.com/1556536/29817913-7da433e4-8cd7-11e7-97b6-74e7dd073132.png">

Is there a simple way to convert the sdk models to json? something that you guys might be using internally?

**Comment by rishi-anand** [comment]
If you check azure java sdk examples on this same repository main page, they have written an Utility class to print virtual machine.. Haven't checked if that is in JSON format or not but this information may be useful to you.

[](https://github.com/Azure-Samples/compute-java-create-virtual-machines-from-generalized-image-or-specialized-vhd/blob/master/src/main/java/com/microsoft/azure/management/samples/Utils.java)

**Comment by jatins** [comment]
I was able convert is using `writeAsString(vm.inner())` where `vm` is an instance of `com.microsoft.azure.management.compute.VirtualMachine`

**Comment by rishi-anand** [comment]
(y)

**Comment by martinsawicki** [comment]
@anuchandy interesting as it seems related to the serialization work you've been investigating

**Comment by martinsawicki** [comment]
seems like you found an interesting approach to get the serialization side to work. We don't have anything better than that in the SDK.
