### ISSUE TITLE
Create Utility to Generate Javadoc Codesnippet Stubs

### ISSUE THREAD

**Issue by alzimmermsft** [Azure/azure-sdk-for-java#18988]
Our Javadocs use codesnippets which copy a range of code from `/samples` between a named comment block. Preparing the named blocks is a manual task and the name is based on the API name and the parameters, given the strictness of the name we could create a utility tool which accepts `.java` files and generates a `.java` with all snippets blocks generated.

For example, given the Java client class

```java
public Response<Void> deleteX(String name) {
    // API code
}

public Response<X> getX(String name) {

}
```

These would be the snippet block names we'd create

```java
// BEGIN: deleteX#String
// Javadoc snippet code
// END: deleteX#String

// BEGIN: getX#String
// Javadoc snippet code
// END: getX#String
```

**Comment by kurtzeborn** [comment]
Triaging old issues... @alzimmermsft, you may have already addressed this with some of your recent investments.
