### ISSUE TITLE
[BUG] Spring Boot Application can't start with azure-spring-boot-starter-keyvault-secrets

### ISSUE THREAD

**Issue by dahlsdata** [Azure/azure-sdk-for-java#19008]
**Describe the bug**
When adding 'com.azure.spring:azure-spring-boot-starter-keyvault-secrets' to our project, and filling in the correct properties. The application will not start. It hangs without getting anywhere. Not even the Spring Boot banner is showing. No logging.
Turning azure.keyvault.enabled to false, makes the application start normally.

We are running Spring Boot v. 2.3.8
I have testet version 3.1.0 and 3.0.0 of com.azure.spring:azure-spring-boot-starter-keyvault-secrets
I have also tested with Spring Boot v.2.3.4 still with same problem.
I have also tested with com.microsoft.azure:azure-keyvault-secrets-spring-boot-starter:2.2.3-2-3.5, but still same problem.

I dont know whats the problem here. I just want to use azure keyvault with spring boot, how can that be so problematic??

***Exception or Stack Trace***
No logs whatsoever printed.

**To Reproduce**
Add dependency provided above.
Set properties:
azure.keyvault.client-id=**
azure.keyvault.client-key=**
azure.keyvault.tenant-id=**
azure.keyvault.enabled=true
azure.keyvault.uri=https://**.vault.azure.net/

**Expected behavior**
Keys fetched from Azure KeyVault without any issues.

**Screenshots**

**Setup (please complete the following information):**
 - OS: Windows 10
 - IDE : IntelliJ
 - Version of the Library used (see above)

**Additional context**
We are also using:
'com.microsoft.azure:azure-servicebus-spring-boot-starter:2.2.3'
'com.microsoft.azure:applicationinsights-spring-boot-starter:2.6.2'

**Information Checklist**
Kindly make sure that you have added all the following information above and checkoff the required fields otherwise we will treat the issuer as an incomplete report
- [*] Bug Description Added
- [*] Repro Steps Added
- [*] Setup information Added

**Comment by chenrujun** [comment]
Hi, @dahlsdata .

Thank you for reaching out.
I can not reproduce you problem in [this commit](https://github.com/chenrujun/azure-sdk-for-java/tree/71cb71fb26ad14c8affd57079b74277bccd48399/sdk/spring/azure-spring-boot-samples/azure-spring-boot-sample-keyvault-secrets).
Could you please try to reproduce your problem in [this commit](https://github.com/chenrujun/azure-sdk-for-java/tree/71cb71fb26ad14c8affd57079b74277bccd48399/sdk/spring/azure-spring-boot-samples/azure-spring-boot-sample-keyvault-secrets)?

If you can not reproduce your problem in that commit, please share your pom. Let me investigate your pom.

**Comment by dahlsdata** [comment]
Thanks @chenrujun ,

I used your minimum sample for base, and started adding my own dependencies to see where it all went wrong.

I was then able to locate the issue. The issue was a dependency i had to:
'com.microsoft.azure:msal4j:1.2.0'
With this dependency application failed to start.
After upgrading this to latest: 
'com.microsoft.azure:msal4j:1.9.0'
Application starts normally again.

So a bit of a conflict there apparantly.

But thanks so much for your help anyway!

**Comment by chenrujun** [comment]
@dahlsdata 

Thank you for your information. 
Does it mean you problem has been solved after update `msal4j`'s version?

If you solved your problem, please close this issue. 🙏

**Comment by dahlsdata** [comment]
Yes it is. Closing now.
