### ISSUE TITLE
[QUERY] Any alternative to spring.cloud.azure.credential-file-path?

### ISSUE THREAD

**Issue by vprudnikov** [Azure/azure-sdk-for-java#19004]
**Query/Question**
We are developing a spring boot project that writes/reads from Event Hubs. The application is wrapped by a docker image and the same image is used by all the environments (e.g. TEST, STAGE, PROD) The documentation says that we need to place an event hubs auth file under the `resources` and set up a `credential-file-path` property that will point to that file.
We have a subscription per environment which means that TEST env can't get access to PROD's event hubs.

The question is: **how to make sure that PROD's event hubs credentials are invisible to developers?**
We can't just commit the PROD's event hubs auth file to Git and/or have it inside a docker image since the `clientSecret` can be easily fetched from Git and/or docker image. This, in turn, will give access to PROD's event hub.

***Why is this not a Bug or a feature Request?***
Because I don't know if there is an alternative to what I'm asking about.

**Setup (please complete the following information if applicable):**
 - OS: Linux
 - IDE : IntelliJ
 - spring-cloud-starter-azure-eventhubs-kafka:1.2.7
 
 **Information Checklist**
 Kindly make sure that you have added all the following information above and checkoff the required fields otherwise we will treat the issuer as an incomplete report
- [ ] Query Added
- [ ] Setup information Added

**Comment by chenrujun** [comment]
Hi, @vprudnikov .

I think you can use the docker's [volume feature](https://docs.docker.com/storage/volumes/#start-a-container-with-a-volume). And set `credential-file-path` by environment variable.

**Comment by saragluna** [comment]
Just an FYI, we removed the `spring.cloud.azure.credential-file-path` property in our 2.0.0 release https://github.com/Azure/azure-sdk-for-java/blob/master/sdk/spring/azure-spring-cloud-autoconfigure/CHANGELOG.md#breaking-changes.

**Comment by vprudnikov** [comment]
@chenrujun, thanks for your suggestion!

@saragluna, thanks for mentioning it.
Does it look like I can change the current dependency to a new one and use the configuration example listed here?
https://github.com/Azure/azure-sdk-for-java/tree/master/sdk/spring/azure-spring-boot-samples/azure-spring-cloud-sample-eventhubs-kafka

**Comment by saragluna** [comment]
@vprudnikov yes, since new features/ bug fixes will be added to the later version, so it's recommended to upgrade your dependency. But please notice that we've changed the artifact id and group id since version 2.0.0 https://github.com/Azure/azure-sdk-for-java/blob/master/sdk/spring/azure-spring-cloud-starter-eventhubs-kafka/CHANGELOG.md#breaking-changes-1.

**Comment by vprudnikov** [comment]
@saragluna thank you! I'll try it out.
I'm closing the issue for now.
