### ISSUE TITLE
DeviceTwin.updateDesiredProperties is not implemented

### ISSUE THREAD

**Issue by cacsar** [Azure/azure-sdk-for-java#19020]
The method [DeviceTwin.updateDesiredProperties](https://docs.microsoft.com/en-us/java/api/com.microsoft.azure.sdk.iot.service.devicetwin._device_twin.updatedesiredproperties) is documented but throws a NotImplementedException rather than being usable.

As implementing the method is considered an [enhancement](https://github.com/Azure/azure-iot-sdk-java/issues/222) the documentation should be updated to reflect that it cannot be used. Similar documentation bugs likely exist for other methods in this SDK.

**Comment by joshfree** [comment]
Porting this to the azure-sdk-for-java repo so someone from `Digital Twins` can double check the documentation

**Comment by timtay-microsoft** [comment]
This issue has been fixed for a while in the track 1 library in question. Closing this issue
