### ISSUE TITLE
mvn fabric8:apply doesnt work due to incorrect .kube/config file format

### ISSUE THREAD

**Issue by rhollins** [Azure/azure-sdk-for-java#19022]
Hello,

I have a problem with following document:
https://docs.microsoft.com/en-us/java/azure/spring-framework/deploy-spring-boot-java-app-using-fabric8-maven-plugin#feedback

Command "az aks get-credentials" will create json formatted config (C:\Users\<username>\.kube\config) file which cant be read by fabric8 plugin effectively returning error:

error return by fabric 8:
[ERROR] Failed to execute goal io.fabric8:fabric8-maven-plugin:3.5.38:apply (default-cli) on project gs-spring-boot-docker: Failure executing: GET at: https://.hcp.canadaeast.azmk8s.io/. Message: Unauthorized! Token may have expired! Please log-in again. Unauthorized. -> [Help 1]

It would be great to know how to get this to work according to this post it should work but it doesn't, seems like fabric8 requires yaml formatted file not json.

Old format of config file before running cli command:

```
apiVersion: v1
clusters:
- cluster:
    certificate-authority-data: ...
    server: https://<cluster name>.hcp.westeurope.azmk8s.io:443
  name: aksdevwe
....
```
New format after running cli command:

```
{apiVersion: v1, clusters: [{cluster: {certificate-authority-data: ...
server: 'https://<server name>.hcp.westeurope.azmk8s.io:443'}, name: <server name>},

```
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 76b6b729-3a37-ab90-5126-37af758e8ff3
* Version Independent ID: 98c83467-e5f9-384d-6cee-745426e296d4
* Content: [Deploy a Spring Boot app using the Fabric8 Maven Plugin](https://docs.microsoft.com/en-us/java/azure/spring-framework/deploy-spring-boot-java-app-using-fabric8-maven-plugin#feedback)
* Content Source: [docs-ref-conceptual/spring-framework/deploy-spring-boot-java-app-using-fabric8-maven-plugin.md](https://github.com/Azure/azure-docs-sdk-java/blob/live/docs-ref-conceptual/spring-framework/deploy-spring-boot-java-app-using-fabric8-maven-plugin.md)
* Service: **multiple**
* GitHub Login: @rmcmurray
* Microsoft Alias: **yuwzho;robmcm**

**Comment by stliu** [comment]
now the doc is updated to https://docs.microsoft.com/en-us/azure/developer/java/spring-framework/deploy-spring-boot-java-app-on-kubernetes, and fabric8 maven plugin is not the tool anymore, so i'm closing this issue

meanwhile, fabric8 maven plugin has been rebranding to https://github.com/eclipse/jkube, just FYI.
