### ISSUE TITLE
SecretAsyncClient Fills Logs with Info Messages [BUG]

### ISSUE THREAD

**Issue by frayneposset** [Azure/azure-sdk-for-java#19052]
**Describe the bug**
SecretAsyncClient fills the logs with info messages saying Retrieving secret and Retrieved Secret

***Exception or Stack Trace***
N/A

**To Reproduce**
Steps to reproduce the behaviour:

Add this dependency to a Spring Boot app, configure a key vault, then look at the logs.

implementation("com.microsoft.azure:azure-keyvault-secrets-spring-boot-starter:2.3.5")

***Code Snippet***

```
    Mono<Response<KeyVaultSecret>> getSecretWithResponse(String name, String version, Context context) {
        context = context == null ? Context.NONE : context;
        return service.getSecret(vaultUrl, name, version == null ? "" : version, apiVersion, ACCEPT_LANGUAGE,
            CONTENT_TYPE_HEADER_VALUE, context.addData(AZ_TRACING_NAMESPACE_KEY, KEYVAULT_TRACING_NAMESPACE_VALUE))
            .doOnRequest(ignoredValue -> logger.info("Retrieving secret - {}", name))
            .doOnSuccess(response -> logger.info("Retrieved secret - {}", response.getValue().getName()))
            .doOnError(error -> logger.warning("Failed to get secret - {}", name, error));
```

**Expected behaviour**
These messages should be debug

**Screenshots**

**Setup (please complete the following information):**
Kindly make sure that you have added all the following information above and checkoff the required fields otherwise we will treat the issuer as an incomplete report
- [x] Bug Description Added
- [x]  Repro Steps Added
- [x] Setup information Added

**Comment by vcolin7** [comment]
Hi @frayneposset, this is a pattern we follow in many of our libraries at the time being, but I will definitely bring it up with the team to determine the best course of action.

**Comment by madkroll** [comment]
Thanks @frayneposset for opening this issue.
My team also works on integrating our App with Azure Key Vault, but these nonsense INFO log entries are just killing our logging. Each time something tries to retrieve the secret it posts two lines in the log.

I like the idea to set it to DEBUG - so anyone who needs to have that information - may decide to include these records into logging. Please fix it before we ran out of space ahahahahah

**Comment by vcolin7** [comment]
Changed the log level from `INFO` to `VERBOSE` for our service operations in the `onRequest` and `onSuccess` methods. These changes should be made available sometime next week :)
