### ISSUE TITLE
VirtualMachineImage do not have an api to list images based on publisher, offer, sku instead it lists all images in given region.

### ISSUE THREAD

**Issue by rishi-anand** [Azure/azure-sdk-for-java#1906]
`rx.Observable<VirtualMachineImage> imageObservable = azure.virtualMachineImages().listByRegionAsync(Region.US_WEST);`

**And below is my filter predicate:**
```
Func1<VirtualMachineImage, Boolean> imagePredicate = new Func1<VirtualMachineImage, Boolean>() {
    @Override
     public Boolean call(VirtualMachineImage image) {
     if(image.publisherName().equals("OpenLogic") &&
                        image.offer().equals("CentOs") &&
                        image.sku().equals("7.3")){
          return true;
         }
     return false;
    }
};
```
               
```
imageObservable
	       .filter(imagePredicate)
	       .toBlocking()
	       .subscribe(addImagesInList);
```

I kept on listening to observable and after 5 minutes or more, I made total of 15000 requests without getting desired result and I was prohibited to make any further request for short duration of time.

**Error:**    _Caused by: com.microsoft.azure.CloudException: Number of read requests for subscription 'cbaba14b-e672-47d7-bb59-4a0613d6d149' exceeded the limit of '15000' for time interval '01:00:00'. Please try again after '300' seconds.: Number of read requests for subscription 'cbaba14b-e672-47d7-bb59-4a0613d6d149' exceeded the limit of '15000' for time interval '01:00:00'. Please try again after '300' seconds.
	at com.microsoft.azure.AzureClient.createExceptionFromResponse(AzureClient.java:601)
	at com.microsoft.azure.AzureClient.access$000(AzureClient.java:31)
	at com.microsoft.azure.AzureClient$10.call(AzureClient.java:577)
	at com.microsoft.azure.AzureClient$10.call(AzureClient.java:574)_

**Issue:**
There should be an api to filter images based on publsiher, offer and sku. If I do the same using Azure Cli then I am able to filter images based on above parameters.

**Comment by rishi-anand** [comment]
<img width="1440" alt="images_observable_list_rest_call_data" src="https://user-images.githubusercontent.com/9067666/30241206-7adff562-959c-11e7-840d-337d820e7815.png">

**Comment by anuchandy** [comment]
Though your logic is correct, the filter is applied on all the elements in the upstream and that requires SDK to enumerate all images, which cause ToomanyRequest error from azure.

We can solve this by limiting number of request to azure by using different Rx operators. See below code sample (CLI uses something similar underneath).

Sample code uses `first` operator which unsubscribe from the upstream as soon as it finds the first event matching the given predicate, due to un-subscription further api calls won't be made by the SDK. 

```java
Observable<VirtualMachineImage> imagesInSku = azure.virtualMachineImages().publishers()
        .listByRegionAsync(Region.US_EAST)
        .first(new Func1<VirtualMachinePublisher, Boolean>() {
            @Override
            public Boolean call(VirtualMachinePublisher publisher) {
                return publisher.name().equalsIgnoreCase("OpenLogic1");
            }
        })
        .flatMap(new Func1<VirtualMachinePublisher, Observable<VirtualMachineOffer>>() {
            @Override
            public Observable<VirtualMachineOffer> call(VirtualMachinePublisher virtualMachinePublisher) {
                return virtualMachinePublisher.offers().listAsync();
            }
        })
        .first(new Func1<VirtualMachineOffer, Boolean>() {
            @Override
            public Boolean call(VirtualMachineOffer offer) {
                return offer.name().equalsIgnoreCase("CentOs");
            }
        })
        .flatMap(new Func1<VirtualMachineOffer, Observable<VirtualMachineSku>>() {
            @Override
            public Observable<VirtualMachineSku> call(VirtualMachineOffer offer) {
                return offer.skus().listAsync();
            }
        })
        .first(new Func1<VirtualMachineSku, Boolean>() {
            @Override
            public Boolean call(VirtualMachineSku sku) {
                return sku.name().equalsIgnoreCase("7.3");
            }
        })
        .flatMap(new Func1<VirtualMachineSku, Observable<VirtualMachineImage>>() {
            @Override
            public Observable<VirtualMachineImage> call(VirtualMachineSku sku) {
                return sku.images().listAsync();
            }
        });

imagesInSku.subscribe(new Action1<VirtualMachineImage>() {
            @Override
            public void call(VirtualMachineImage virtualMachineImage) {
                System.out.println(virtualMachineImage.id());
            }
        });
```

**Comment by anuchandy** [comment]
Note that above code is to get all images under a sku (which matches the title of this issue). If you are looking for the latest image in a sku (thus only one image) then `getImage` api call be used with version param as `latest`.

```java
azure.virtualMachineImages()
    .getImage(Region.US_EAST, "OpenLogic", "CentOs", "7.3", "latest");
```

**Comment by rishi-anand** [comment]
@anuchandy, getting image using getImage api do not work for 'latest' version.
I am getting below error-

_com.microsoft.azure.CloudException: Status code 400, {
  "error": {
    "code": "InvalidParameter",
    "target": "version",
    "message": "The value of parameter version is invalid."
  }
}: The value of parameter version is invalid._

**Comment by rishi-anand** [comment]
@anuchandy, publishers api is not consuming too many request, but it still takes 5-6 sec to get latest image object. **That will be a bottleneck for performance for my use case.**

**Comment by rishi-anand** [comment]
@anuchandy , I was on stable release 1.1.0. I moved to new release 1.2.0 and I am able to get image using 'latest' as version.

Thanks Man (y)

**Comment by anuchandy** [comment]
"latest' is introduced starting from 1.2. Regarding.the api latency, there is nothing we can do in the client side, getimage is a single api call, we can pass feedback to service team. Seems your original issue is resolved, hence closing this, feel free to reopen if you have questions.
