### ISSUE TITLE
Azure 1.2.1 Maven dependencies issue, missing artifacts

### ISSUE THREAD

**Issue by giridharkn** [Azure/azure-sdk-for-java#1907]
Hi,

Following azure dependency not able to pull all the dependent jars.
<dependency>
      <groupId>com.microsoft.azure</groupId>
      <artifactId>azure</artifactId>
      <version>1.2.1</version>
    </dependency>

I am not able to pull the proper azure jars into my maven project. There is an error saying missing artifacts.

Please anyone help me to resolve this.

Thanks and Rgeards
Giridhar K N

**Comment by martinsawicki** [comment]
fixed and released in v1.3
