### ISSUE TITLE
Monitor Manager Activity Logs only returns a maximum of 200 events

### ISSUE THREAD

**Issue by rodrigofraxino** [Azure/azure-sdk-for-java#1908]
Although it is still in beta, I have tried to use the MonitorManager and also the MonitorClientImpl to retrieve events from Azure Activity Logs.
When trying to retrieve the next page or to load all events, I only get a maximum of 200, and the next page comes as null. Have tried the ActivityLogsInner with both list() and listAsync() methods in the Azure Java SDK 1.2.1

**Comment by rodrigofraxino** [comment]
@RikkiGibson could you please confirm if that is a known issue?

**Comment by RikkiGibson** [comment]
Thanks for letting us know about this. I'll try and figure out where the root cause of this lies.

**Comment by RikkiGibson** [comment]
Hello @rodrigofraxino. It looks like there's a bug in the generated code which is preventing nextLink from deserializing correctly. I'll update this issue once I fix it.

**Comment by taroyutao** [comment]
Any update about this issue?

**Comment by yungezz** [comment]
hi @weidongxu-microsoft could you pls help to check if this is still valid issue in latest monitor sdk? thanks

**Comment by weidongxu-microsoft** [comment]
Already fixed.

```
            PagedList<EventData> logs = azure.activityLogs().defineQuery()
                    .startingFrom(DateTime.now().minusDays(60))
                    .endsBefore(DateTime.now())
                    .withAllPropertiesInResponse()
                    .filterByResource(...)
                    .execute();

            int count = logs.size();
```

```
 size = 221
```
