### ISSUE TITLE
[BUG] Unable to see the logs in Event Hubs when I try to use Appender API

### ISSUE THREAD

**Issue by iamsatty** [Azure/azure-sdk-for-java#19081]
**Describe the bug**
I am unable to see the Logs in eventhub , when i try to use Appender API 
https://azuresdkdocs.blob.core.windows.net/$web/java/azure-eventhubs-extensions/3.2.2/com/microsoft/azure/eventhubs/extensions/appender/EventHubsAppender.html

***Exception or Stack Trace***
I don't see any error except -
 WARN  com.microsoft.azure.eventhubs.impl.MessagingFactory - onConnectionError messagingFactory[MF_ee3abb], hostname[xyz.servicebus.windows.net], closing current connection
2021-02-09 15:08:50.518 [pool-2-thread-1]
 INFO  com.microsoft.azure.eventhubs.impl.ConnectionHandler - onConnectionLocalClose hostname[xyz.servicebus.windows.net], connectionId[MF_ee3abb], errorCondition[amqp:connection:forced], errorDescription[The connection was inactive for more than the allowed 60000 milliseconds and is closed by container 'LinkTracker'. TrackingId:, SystemTracker:gateway5, Timestamp:2021-02-09T09:38:50]
2021-02-09 15:08:50.519 [pool-2-thread-1] 
INFO  com.microsoft.azure.eventhubs.impl.ConnectionHandler - onConnectionUnbound hostname[xyz.servicebus.windows.ne], connectionId[MF_ee3abb], state[CLOSED], remoteState[CLOSED]
2021-02-09 15:08:50.519 [pool-2-thread-1] 
INFO  com.microsoft.azure.eventhubs.impl.ConnectionHandler - onConnectionFinal hostname[xyz.servicebus.windows.net:]

**To Reproduce**
1) Add below dependency 

       <dependency>
            <groupId>com.microsoft.azure</groupId>
            <artifactId>azure-eventhubs-extensions</artifactId>
            <version>3.0.0</version>
        </dependency>

2) Add Appender in log4j2.xml
<Configuration  packages="com.microsoft.azure.eventhubs.extensions.appender">
    <Properties>
        <Property name="LOG_PATTERN">
            %d{yyyy-MM-dd HH:mm:ss.SSS} %5p ${hostName} --- [%15.15t] %-40.40c{1.} : %m%n%ex
        </Property>
    </Properties>
    <Appenders>
        <EventHub name="EventHub" eventHubConnectionString="MyEventHubConnectionString">

            <PatternLayout pattern="${LOG_PATTERN}"/>
        </EventHub>
     
    </Appenders>
    <Loggers>
        <Logger name="com.Controller" level="debug" additivity="false">
            <AppenderRef ref="EventHub" />
        </Logger>

        <Root level="info">
            <AppenderRef ref="EventHub" />
        </Root>
    </Loggers>
</Configuration>

***Code Snippet***
<Configuration  packages="com.microsoft.azure.eventhubs.extensions.appender">
    <Properties>
        <Property name="LOG_PATTERN">
            %d{yyyy-MM-dd HH:mm:ss.SSS} %5p ${hostName} --- [%15.15t] %-40.40c{1.} : %m%n%ex
        </Property>
    </Properties>
    <Appenders>
        <EventHub name="EventHub" eventHubConnectionString="MyEventHubConnectionString">
      <PatternLayout pattern="${LOG_PATTERN}"/>
        </EventHub>
 </Appenders>
    <Loggers>
        <Logger name="com.Controller" level="debug" additivity="false">
            <AppenderRef ref="EventHub" />
        </Logger>
 <Root level="info">
            <AppenderRef ref="EventHub" />
        </Root>
    </Loggers>
</Configuration>

**Expected behavior**
Log should flow to eventhub , But it's not reaching there

**Screenshots**

**Setup (please complete the following information):**
 - OS: Windows/ Mac
 - IDE : Intellij
 - 3.0.0

**Additional context**

**Information Checklist**
Kindly make sure that you have added all the following information above and checkoff the required fields otherwise we will treat the issuer as an incomplete report
- [ ] Bug Description Added
- [ ] Repro Steps Added
- [ ] Setup information Added

**Comment by conniey** [comment]
Do you have a code snippet? It seems to just be an empty block.

+ @JamesBirdsall who knows more about this appender.

**Comment by iamsatty** [comment]
@JamesBirdsall .... It's just a appender I am trying to use . It's a sample spring boot application with a Controller with few Log statements. Intension was these logs should flow to eventhub . But It doesn't flow , It doesn't responds after creating a send link.

<Configuration  packages="com.microsoft.azure.eventhubs.extensions.appender">
    <Properties>
        <Property name="LOG_PATTERN">
            %d{yyyy-MM-dd HH:mm:ss.SSS} %5p ${hostName} --- [%15.15t] %-40.40c{1.} : %m%n%ex
        </Property>
    </Properties>
    <Appenders>
        <EventHub name="EventHub" eventHubConnectionString="MyEventHubConnectionString">

            <PatternLayout pattern="${LOG_PATTERN}"/>
        </EventHub>
     
    </Appenders>
    <Loggers>
        <Logger name="com.Controller" level="debug" additivity="false">
            <AppenderRef ref="EventHub" />
        </Logger>

        <Root level="info">
            <AppenderRef ref="EventHub" />
        </Root>
    </Loggers>
</Configuration>

**Comment by sagar027** [comment]
@iamsatty : try setting the 'immediateFlush' to true on the EventHub Appender in log4j2.xml. Seems like logs aren't immediately sent and the connection times out in 1 minute's time. I was able to successfully use the Event Hub appender. Sample at https://github.com/sagar027/EventHubAppender-Sample

**Comment by JamesBirdsall** [comment]
Sagar027 has kindly provided a working sample -- see the link above.
As a general note, the SDK that this appender is based on is deprecated, so the appender is also deprecated.

**Comment by iamsatty** [comment]
I have created a sample wrapper to support our use case , Thanks for follow up @JamesBirdsall  .
