### ISSUE TITLE
Is there any way doing a "one-shot" vm creation without doing any polling?

### ISSUE THREAD

**Issue by stipx** [Azure/azure-sdk-for-java#1910]
Hi,

basically we want to achieve a task queue which only creates the machine and does not do the polling directly.

So our workflow is:
* Create a VM -> store the ID
* Request the VM state with the ID after 5 minutes with a task which is put into a task queue
* If not yet finished just enqueue a new task which might run after 5 minutes if there is nothing else in the queue

Also: Is it possible to just create the VM and directly attach a extension without waiting for it to be finally created.

My concern is: We have a microservice which does the azure provisioning and it is container based. So it might be redeployed several times. When the polling is done in one JVM it might get interrupted when the azure handling microservice gets killed. I mean there is a grace period until the JVM exits, but I dont want it to be 20 minutes or more.

Maybe someone has an idea how to achieve something like this with the java sdk.
The REST api (which is used here anyway) supports sending just one PUT http call to create a VM, but as far as I can see there is no way to do such "one-shot" action with the sdk.

Thanks
stipx

**Comment by martinsawicki** [comment]
it's something we've been thinking about - a generalized approach for this nature of operations is needed an d is under investigation. Parking on @anuchandy .

**Comment by anuchandy** [comment]
This should be addressed in new track2 lite SDK with new Poller, where customers can initiate the LRO, take(1) and unsubscribe, which does not make any more network calls. 

Assigning this to new owner @yaohaizh to update the issue when the work is done.

**Comment by yaohaizh** [comment]
Thanks, @anuchandy.

**Comment by yungezz** [comment]
part of this is beginCreate work @weidongxu-microsoft  is working on

**Comment by weidongxu-microsoft** [comment]
https://github.com/Azure/azure-sdk-for-java/blob/main/sdk/resourcemanager/docs/DESIGN_PREVIEW.md

**Comment by fkorotkov** [comment]
I'm trying to use the `beginCreate` method but getting `"postRunDependent is not supported"` exception with not much of useful information. If I use just `create()` or `createAsync()` everything seems work just fine. Here is the related stacktrace:

```stacktrace
 java.lang.IllegalStateException: postRunDependent is not supported
	at com.azure.resourcemanager.resources.fluentcore.dag.TaskGroup.lambda$invokeDependencyAsync$2(TaskGroup.java:300)
	at reactor.core.publisher.FluxDefer.subscribe(FluxDefer.java:46)
	at reactor.core.publisher.Flux.subscribe(Flux.java:8468)
	at reactor.core.publisher.Flux.blockLast(Flux.java:2643)
	at com.azure.resourcemanager.compute.implementation.VirtualMachineImpl.lambda$beginCreate$12(VirtualMachineImpl.java:1895)
	at com.azure.resourcemanager.resources.fluentcore.model.implementation.AcceptedImpl.newAccepted(AcceptedImpl.java:414)
	at com.azure.resourcemanager.compute.implementation.VirtualMachineImpl.beginCreate(VirtualMachineImpl.java:1872)
```

**Comment by weidongxu-microsoft** [comment]
@fkorotkov 

Sorry for the obscure message. It usually means that certain operation in your VM configure code is required to be done *after* VM creation (to my memory, maybe VM extension?).
These operation is handled by `create` call, as it poll until VM created, then do that operation.

But if via `beginCreate` call, since it does not poll (or depends on user to poll), it will not know when VM creation is completed, hence it is not able to do this follow up operation.

If you think your use case does not (or should not) involve such "operation after VM created", would you show us your code?

PS: we might have later response as we are going to have week long holiday here.

**Comment by fkorotkov** [comment]
@weidongxu-microsoft thank you for the response! I was kind of lost in debugging the issue and just posted here.

Indeed I have a [Custom Script Execution](https://docs.microsoft.com/en-us/azure/virtual-machines/extensions/custom-script-windows) attached to the VM that I'm trying to create. In my case I was looking to an option to do a "one-shot" VM creation with a custom script that will bootstrap the VM. 

For context, I'm working on adding support for Azure VMs to [Cirrus CI](https://cirrus-ci.org/) https://github.com/cirruslabs/cirrus-ci-docs/issues/778. We already support Azure Container Instances which has [handy `withStartingCommandLine` method](https://github.com/Azure/azure-sdk-for-java/blob/3f31d68eed6fbe11516ca3afe3955c8840a6e974/sdk/resourcemanager/azure-resourcemanager-containerinstance/src/main/java/com/azure/resourcemanager/containerinstance/implementation/ContainerImpl.java#L170). And most other cloud providers allow to specify "startup scripts" at the moment of VM creation. Seems as you suggested I'll need to do two "one-shot" calls:

1. Create VM with `beginCreate`.
2. Wait for the VM creation.
3. Update the extension to run a script. Or [run a command](https://docs.microsoft.com/en-us/azure/virtual-machines/windows/run-command).

**Comment by weidongxu-microsoft** [comment]
@fkorotkov 

I am not really sure about the "one-shot". If you just call `createAsync().toFuture()`, does it count as "one-shot"?

For VM extension, from what I know it had to be done after VM creation.
- on page from your comment (https://docs.microsoft.com/en-us/azure/virtual-machines/extensions/custom-script-windows), ARM template says below which mean it depends on an existing VM resource:
```
    "dependsOn": [
        "[concat('Microsoft.Compute/virtualMachines/', variables('vmName'),copyindex())]",
        "[variables('musicstoresqlName')]"
    ],
```
- REST API on PUT VM does not have configure on VM extension https://docs.microsoft.com/en-us/rest/api/compute/virtual-machines/create-or-update
- And VM extension is on another REST API https://docs.microsoft.com/en-us/rest/api/compute/virtual-machine-extensions/create-or-update
