### ISSUE TITLE
Update VM with custom Data

### ISSUE THREAD

**Issue by gopal229** [Azure/azure-sdk-for-java#1912]
Is it possible to update an existing VM with custom data?  withCustomData is part of the WithFromImageCreateOptionsManaged interface and can be used while creating new VM. I am looking for ways to update the data on an existing VM.

**Comment by anuchandy** [comment]
@gopal229 Updating or adding custom data as part of VM update is not supported by the compute service, hence this option is not exposed in fluent VM update flow. An attempt to change custom data through VM update will cause below error:

```json
{
  "error": {
    "code": "PropertyChangeNotAllowed",
    "target": "customData",
    "message": "Changing property 'customData' is not allowed."
  }
}
```

**Comment by gopal229** [comment]
Thanks, @anuchandy . Are there any plans to support this in future?

**Comment by anuchandy** [comment]
@gopal229 its a question to service team. Could you please open a azure support ticket for this, they should be able to forward the question to service them and update you.

**Comment by gopal229** [comment]
Sure, thanks @anuchandy
