### ISSUE TITLE
NullPointerException on com.microsoft.azure.servicebus.Message.getExpiresAtUtc()

### ISSUE THREAD

**Issue by axhwk** [Azure/azure-sdk-for-java#19130]
On messages received by from deadletter queue:
`Collection<IMessage> messages = messageReceiver.peekBatch(sequenceNumber, 1);`

I get a NullPointerException when calling com.microsoft.azure.servicebus.Message.getExpiresAtUtc():

    Caused by: java.lang.NullPointerException: null
	    at java.base/java.time.Instant.plus(Instant.java:787)
	    at com.microsoft.azure.servicebus.Message.getExpiresAtUtc(Message.java:198)

This was introduced in 3.5.0 and is still present in 3.6.0:

    <dependency>
        <groupId>com.microsoft.azure</groupId>
        <artifactId>azure-servicebus</artifactId>
        <version>3.5.0</version>
    </dependency>

With 3.4.0 it is still working without exception.

**Comment by hemanttanwar** [comment]
@yvgopal Please look into this.

**Comment by yvgopal** [comment]
I am fixing it. Will release a new version of the SDK within a week.
