### ISSUE TITLE
[Service Bus] [FEATURE Cross entity transaction]   Support cross entity transaction feature 

### ISSUE THREAD

**Issue by hemanttanwar** [Azure/azure-sdk-for-java#19137]
The `sendVia` is implemented using new approach at service side. It is called cross entity transaction.

Use same AMQP session to create Coordinator, Senders and receivers who are part of same transaction.
The first sender/receiver created will be treated as `sendVia` .

-  Implement Feature
- Unit test
- Live test
Exception Scenario : What happens when connection reconnect , does this setup work in this case ?

**Comment by hemanttanwar** [comment]
PR : https://github.com/Azure/azure-sdk-for-java/pull/19863  (First release will be beta release.)

**Comment by joshfree** [comment]
Fixed by https://github.com/Azure/azure-sdk-for-java/pull/19863
