### ISSUE TITLE
Re-Enable Full Management CI Matrix

### ISSUE THREAD

**Issue by alzimmermsft** [Azure/azure-sdk-for-java#19167]
Update the `archetype-sdk-management.yml` configuration to build management libraries targeting both Java 7 and Java 8 byte code. Both runs will use Java 8 as the JDK version but will pass the `source` and `target` VM options to target 1.7 and 1.8.

**Comment by weidongxu-microsoft** [comment]
A PR in work https://github.com/Azure/azure-sdk-for-java/pull/19091

**Comment by alzimmermsft** [comment]
Closing this as libraries leveraging this has been removed from the repo.
