### ISSUE TITLE
Got error when turn on/off ACR admin

### ISSUE THREAD

**Issue by adashen** [Azure/azure-sdk-for-java#1919]
((Update)registry.update()).withoutRegistryNameAsAdminUser().apply();
Turn off ACR admin with the above line of code. The following error got:
"Status code 400, {"error":{"code":"InvalidRequestContent","message":"The request content was invalid and could not be deserialized: 'Error reading string. Unexpected token: StartObject. Path 'tags.container', line 1, position 57.'."}}"

The acr to be updated has tags "contain.registry", from the response, it seems sdk filed to handle the "."

**Comment by niteshjain1** [comment]
https://github.com/Azure/azure-sdk-for-java/issues/1891
 Similar issue here also

**Comment by martinsawicki** [comment]
you should be able to see this fix in the latest runtime which will be released soon (v1.1.1) - few days or so

**Comment by martinsawicki** [comment]
v1.1.1. released
