### ISSUE TITLE
Azure AppConfiguration Service for Java (January-June 2021)

### ISSUE THREAD

**Issue by AlexGhiondea** [Azure/azure-sdk-for-java#19227]
This tracks the work for Azure AppConfiguration Service for Java.

**Comment by iteal** [comment]
hi @AlexGhiondea! At the moment, is it possible to create/delete an AppConfiguration using the Java SDK? (like the REST API: https://docs.microsoft.com/en-us/rest/api/appconfiguration/configurationstores/create)
If not, will this be done in this epic?

**Comment by AlexGhiondea** [comment]
@mssfang could you check if this is possible in the Java SDK?

**Comment by mssfang** [comment]
@iteal 

There are two ways to create azure resource but not in Java AppConfig SDK.
1) Azure CLI
https://github.com/Azure/azure-sdk-for-java/tree/master/sdk/appconfiguration/azure-data-appconfiguration#create-an-app-configuration-store
2) Azure resource management SDK.
if there is a workload that requires recreating the resource programmatically in Java, then should request the feature in Azure/azure-libraries-for-java: Azure Management Libraries for Java. https://github.com/azure/azure-libraries-for-java
