### ISSUE TITLE
[BUG] Unable to complete Service Bus Messages when using ServiceBusReceiverAsyncClient

### ISSUE THREAD

**Issue by sudharsan2020** [Azure/azure-sdk-for-java#19248]
**Describe the bug**

- Unable to **complete** Service Bus Messages when using **ServiceBusReceiverAsyncClient** with **disableAutoComplete** enabled. 
- Hence the messages are delivered repetitively to the same listeners
- We _cannot opt for message auto-completion_, since the message needs to be completed only upon successful task completion

***Exception or Stack Trace***
Message count remains intact in the subscription even after consuming

**To Reproduce**

- Attached the code snippet using **ServiceBusReceiverAsyncClient** for consuming messages with **disableAutoComplete** enabled.
**SUBSCRIPTIION SETTINGS:**
- **Lock Duration** for message is set to **5 minutes**
- **Max Delivery count** is set to **3**

***Code Snippet***
```
public class WebJobListener {
    private ServiceBusReceiverAsyncClient serviceBusReceiverAsyncClient;
    private Gson gson;
    private ILogger log;
    private static final Type requestModelType = new TypeToken<RequestModel>() {}.getType();
 
    @Inject
    public WebJobListener(ILogger log) {
        this.serviceBusReceiverAsyncClient = new ServiceBusClientBuilder()
                .connectionString(System.getenv("AZURE_SERVICEBUS_NAMESPACE_CONNECTION_STRING"))
                .retryOptions(new AmqpRetryOptions().setTryTimeout(Duration.ofSeconds(30)))
                .receiver()
                .receiveMode(ServiceBusReceiveMode.PEEK_LOCK)
                .topicName("MY_TOPIC")
                .subscriptionName("MY_SUBSCRIPTION")
                .prefetchCount(10)
                .maxAutoLockRenewDuration(Duration.ofMinutes(10))
                .disableAutoComplete()
                .buildAsyncClient();
        this.jobManager = jobManager;
        this.captureJob = new CaptureJob();
        this.gson = new Gson();
        this.log = log;
    }

    public void run() {
        log.trace("Webjob worker starting to Listen", LogLevels.Verbose, null);
        serviceBusReceiverAsyncClient.receiveMessages().subscribe(message -> {
                    // Process message. If an exception is thrown from this consumer, the message is abandoned.
                    // Otherwise, it is completed.
                    if(message.getSubject().contentEquals("MY_SUBSCRIPTION")) {
                        RequestModel requestModel = gson.fromJson(message.getBody().toString(), requestModelType);

                        // My logic goes here
                        //my_test_function(requestModel);

                        // Complete the message after function completes
                        serviceBusReceiverAsyncClient.complete(message);
                    }
                },
                error -> log.trace("Error occurred while receiving message from subscription: " + error , LogLevels.Error, null));
    }
}
```

**Expected behavior**
**Message count should decrement** after consuming message from the subscription.

**Screenshots**
NA

**Setup (please complete the following information):**
 - OS: Ubuntu 18.04 LTS
 - IDE : IntelliJ
 - Version of the Library used: Java 1.8

**Additional context**
**azure-messaging-servicebus** library **7.0.1** version was used.
```
        <dependency>
            <groupId>com.azure</groupId>
            <artifactId>azure-messaging-servicebus</artifactId>
            <version>7.0.1</version>
        </dependency>
```

**Information Checklist**
Kindly make sure that you have added all the following information above and checkoff the required fields otherwise we will treat the issuer as an incomplete report
- [x] Bug Description Added
- [x] Repro Steps Added
- [x] Setup information Added

**Comment by hemanttanwar** [comment]
@sudharsan2020

It is same cause as I explained in this issue https://github.com/Azure/azure-sdk-for-java/issues/19254
Hope my comment resolves the issue you are facing.

**Comment by sudharsan2020** [comment]
This issue has been resolved after following the steps mentioned in https://github.com/Azure/azure-sdk-for-java/issues/19254#issuecomment-780025780. Thanks a lot for your support @hemanttanwar. Since there isn't much publicly available reference other than Azure docs, it becomes difficult for the developers using Java Service bus API for searching implementation related queries.
