### ISSUE TITLE
[BUG] ESB Connection Builder Exception leaks credentials

### ISSUE THREAD

**Issue by wernerdaehn** [Azure/azure-sdk-for-java#19249]
**Describe the bug**
In case the connection string is of invalid format, e.g. 
`Endpoint=sb://company.servicebus.windows.net/;SharedAccessKey=SharedAccessKeyName=MySharedAccessKey;SharedAccessKey=1234` then the error message is
```
Could not parse 'connectionString'. Expected format: Endpoint={endpoint};
SharedAccessKeyName={sharedAccessKeyName};
SharedAccessKey={sharedAccessKey};EntityPath={entityPath} or Endpoint={endpoint};
SharedAccessSignature=SharedAccessSignature {sharedAccessSignature};
EntityPath={entityPath}.
Actual: Endpoint=sb://company.servicebus.windows.net/;
SharedAccessKey=SharedAccessKeyName=MySharedAccessKey;
SharedAccessKey=1234
```

Hence the SharedAccessKey ends up in user error messages, in log files etc. Not good.

**Expected behavior**
The error message itself is very helpful, the SharedAccessKey should be masked out though.

**Comment by hemanttanwar** [comment]
@wernerdaehn Thank you for raising the issue. 
Can  you tell us which version of library you are using ?
What is  `groupId` and `artifactId` of the dependency you are using ?

**Comment by wernerdaehn** [comment]
Sorry. Latest 7.0.0.

		<dependency>
			<groupId>com.azure</groupId>
			<artifactId>azure-storage-file-datalake</artifactId>
			<version>12.2.0</version>
		</dependency>
		<dependency>
			<groupId>com.azure</groupId>
			<artifactId>azure-messaging-servicebus</artifactId>
			<version>7.0.0</version>
		</dependency>

**Comment by hemanttanwar** [comment]
@wernerdaehn We have done code change to fix this and we will be releasing this in march first week.  This may come a preview first  in march and GA after that, since we have other feature to release.
I am closing this issue for now. If  you see this problem, you can reopen it later.
