### ISSUE TITLE
[Storage][Docs] Document BlobItem.isPrefix to indicate that it is set to true for a directory

### ISSUE THREAD

**Issue by abhikt48** [Azure/azure-sdk-for-java#19257]
We have requirement to read only blob from a given directory, not from sub directory. 
At this moment, i found below check `blobItem.getProperties() == null && blobItem.getName().endsWith("/")` to identify sub directory/folder.

Is this correct way to check sub directory/folder or Do we have any better way to check ?  I tried to exclude subdirectory from `listBlobsByHierarchy`, but I didn't found any option yet. 

Could you please suggest your opinion on this.

```
Iterator<BlobItem> iteratorBlobItem = getBlobContainerClient().listBlobsByHierarchy("test/").iterator();

while(iteratorBlobItem.hasNext()) {
	BlobItem blobItem = iteratorBlobItem.next();
	
	if(blobItem.getProperties() == null && blobItem.getName().endsWith("/")) {
		LOGGER.info("** it's directory '{}', do nothing **", blobItem.getName());
	}else {
		LOGGER.info("** it's blob '{}', create client abd start downloading **", blobItem.getName());
	}
}
```

 - Version of the Library used -` azure-storage-blob-12.10`

**Comment by gapra-msft** [comment]
Hi @abhikt48 

Thanks for your question. I believe BlobItem has an isPrefix property that indicates whether the blob is a prefix for another blob.

**Comment by abhikt48** [comment]
HI @gapra-msft  - Thanks for quick reply.

I compared `isPrefix` value of Sub Directory and blob. Based on testing, can I assume that - 
1. every sub directory will have `isPrefix=true` value. 
2. blob file wil have  `isPrefix=null` value
Could you please confirm this ? 

Please find below screen shot -

1. BlobItem of Sub-Directory
![image](https://user-images.githubusercontent.com/22897837/108100987-8f760a00-707e-11eb-83bf-e5704af53de8.png)

2. BlobItem of blob
![image](https://user-images.githubusercontent.com/22897837/108101380-09a68e80-707f-11eb-8c3a-bebc255ccd8e.png)

**Comment by gapra-msft** [comment]
Yes that is correct.

**Comment by abhikt48** [comment]
Thanks for confirmation.

**Comment by abhikt48** [comment]
One suggestion- is possible for you to update JAVA documentation for isPrefix() - which will tell us that prefix used for sub-directory for folder identification. It will be very helpful for user. Please suggest your opinion.

**Comment by gapra-msft** [comment]
Yes! We can do that. Thank you for the suggestion. I will rename this issue appropriately
