### ISSUE TITLE
[FEATURE REQ] How to apply encryption policy on azure queue client for send message.

### ISSUE THREAD

**Issue by rjoshi12** [Azure/azure-sdk-for-java#19251]
Hi,
I am migrating my app from Microsoft azure storage to latest azure-storage-queue SDK version 12.7.0. In the microsoft azure storage there was an option for encrypting the message on queue with the example code -
CloudQueue queue = connectorConfig.getQueueClient().getQueueReference(queueName);
QueueEncryptionPolicy queueEncryptionPolicy = new QueueEncryptionPolicy(cloudKey, null);
QueueRequestOptions queueRequestOptions = new QueueRequestOptions();
queueRequestOptions.setEncryptionPolicy(queueEncryptionPolicy);
queue.addMessage(cloudQueueMessage, 0, 0, queueRequestOptions, null);

I was looking for similar option in latest sdk to apply encryption on the queue message for sendMessage and getMessage method with com.azure.storage.queue.QueueClient.

Please let me know if there is any option.

Thanks

**Comment by rickle-msft** [comment]
Hi, @rjoshi12. We actually haven't yet added support for queue client side encryption. If that is something you'll need, I'm happy to turn this into a feature request and we can start looking to add that.

**Comment by rad-app** [comment]
Please turn this into feature request. We need this functionality with our Azure Queue Client with latest SDK.
Thanks

**Comment by rickle-msft** [comment]
Roger that. We'll discuss on the team and let you know on when you might be able to expect it
