### ISSUE TITLE
[FEATURE REQ] Add peek method to QueueClient in com.microsoft.azure:azure-servicebus

### ISSUE THREAD

**Issue by admitt** [Azure/azure-sdk-for-java#19258]
**Is your feature request related to a problem? Please describe.**
I'm in a long a slow moving discussion with the support team about implementing a proper health check on our side for service bus queues.
One of the solutions prosed was to use the peek() method however it's not implemented in the library.
If you go to portal.azure.com the option is there - I can go and peek a message from a queue.
Also this is implemented for com.microsoft.azure.servicebus.TopicClient but not for com.microsoft.azure.servicebus.QueueClient.

**Describe the solution you'd like**
Add peek() method to com.microsoft.azure.servicebus.QueueClient

**Describe alternatives you've considered**
We are currently using com.microsoft.azure.servicebus.management.ManagementClient#getQueue() however that leads to a connection timeout on standard subscription. This gets us worried about the solution stability. 
A valid suggestion we've got from the support team was to use the peek() method which is missing in Java implementation.
It will also make more sense for the health check to try to peek the queue because it's much closer to what we are actually using.

**Additional context**
The library we are using is 
        <dependency>
            <groupId>com.microsoft.azure</groupId>
            <artifactId>azure-servicebus</artifactId>
            <version>3.6.0</version>
        </dependency>

**Information Checklist**
Kindly make sure that you have added all the following information above and checkoff the required fields otherwise we will treat the issuer as an incomplete report
- [ + ] Description Added
- [ + ] Expected solution specified

**Comment by hemanttanwar** [comment]
@admitt Thank you for the query.   It is a design question on our API. 
@yvgopal Any thought on this ?

**Comment by yvgopal** [comment]
No. We have no plans to add Peek method to QueueClient. Peek is possible from MessageReceiver. Use ClientFactory.CreateReceiver...() method(s) to create a receiver to the queue and use it to peek messages from the queue. It was a design choice to not have receive and peek methods in QueueClient.

**Comment by admitt** [comment]
Cool. Thanks for suggestion.
