### ISSUE TITLE
In web-application, use both "group" and "role" to create grantedAuthority.

### ISSUE THREAD

**Issue by ppartarr** [Azure/azure-sdk-for-java#19250]
**Describe the bug**
After upgrading to `com.azure.spring:azure-spring-boot-starter-active-directory:3.1.0` I am running into dependency issues. I am using the `org.springframework.security:spring-security-oauth2-resource-server` dependency to extract the `roles` claim from the JWT in order to set users' GrantedAuthorities.

It seems that AADWebAppConfiguration is not being loaded because BearerTokenAuthenticationToken is present (as shown in the stack trace below)

**Exception or Stack Trace**
```
***************************
APPLICATION FAILED TO START
***************************

Description:

Field repo in com.azure.spring.aad.webapp.AADWebSecurityConfigurerAdapter required a bean of type 'com.azure.spring.aad.webapp.AADWebAppClientRegistrationRepository' that could not be found.

The injection point has the following annotations:
	- @org.springframework.beans.factory.annotation.Autowired(required=true)

The following candidates were found but could not be injected:
	- Bean method 'clientRegistrationRepository' in 'AADWebAppConfiguration' not loaded because @ConditionalOnMissingClass found unwanted class 'org.springframework.security.oauth2.server.resource.BearerTokenAuthenticationToken'


Action:

Consider revisiting the entries above or defining a bean of type 'com.azure.spring.aad.webapp.AADWebAppClientRegistrationRepository' in your configuration.
```
**To Reproduce**
Start from `azure-spring-boot-sample-active-directory-webapp` and add the following dependency:

```xml
    <dependency>
      <groupId>org.springframework.boot</groupId>
      <artifactId>spring-boot-starter-oauth2-resource-server</artifactId>
    </dependency>
```

Now extend the Spring WebSecurityConfig to add information to the users based on the JWT:

```java
public class WebSecurityConfig extends AADWebSecurityConfigurerAdapter {
    @Override
    protected void configure(HttpSecurity http) throws Exception {
        super.configure(http);

        http.authorizeRequests((requests) -> requests.anyRequest().authenticated())
            .oauth2ResourceServer()
            .jwt()
            .jwtAuthenticationConverter(new AADJwtBearerTokenAuthenticationConverter());
    }
}
```

**Code snippet**
https://github.com/Azure/azure-sdk-for-java/blob/8a0fe6343dabca5cade4b647765cf53086bbf05f/sdk/spring/azure-spring-boot/src/main/java/com/azure/spring/aad/webapp/AADWebAppConfiguration.java#L45

**Expected behavior**
I would expect to be able to add `GrantedAuthorities` to users based on the Azure AD groups that are returned in the token.

**Setup (please complete the following information):**
 - Version of the Library used: 3.1.0

**Information Checklist**
Kindly make sure that you have added all the following information above and checkoff the required fields otherwise we will treat the issuer as an incomplete report
- [x] Bug Description Added
- [x] Repro Steps Added
- [x] Setup information Added

**Comment by nisha-bhatia** [comment]
Thank you for your feedback. Tagging and routing to the team member best able to assist.

**Comment by chenrujun** [comment]
Hi, @ppartarr 

Please refer to this comment: https://github.com/Azure/azure-sdk-for-java/issues/17860#issuecomment-756550816

```
    @Override
    protected void configure(HttpSecurity http) throws Exception {
        super.configure(http);

        http.authorizeRequests((requests) -> requests.anyRequest().authenticated())
            .oauth2ResourceServer()
            .jwt()
            .jwtAuthenticationConverter(new AADJwtBearerTokenAuthenticationConverter()); // Change here.
    }
```

You can use `new AADJwtBearerTokenAuthenticationConverter("roles", "ROLE_")` instead of `new AADJwtBearerTokenAuthenticationConverter()`

**Comment by ppartarr** [comment]
Hi @chenrujun 

My use case falls under [accessing a web application](https://github.com/Azure/azure-sdk-for-java/tree/master/sdk/spring/azure-spring-boot-starter-active-directory#accessing-a-web-application) but I've been using spring's `oauth2Login()` & `oauth2ResourceServer()` in the same application. Until now I needed the `oauth2ResourceServer()` to convert the `roles` claim to GrantedAuthorities.

Since the migration I cannot use `oauth2ResourceServer()` anymore because of the reasons posted above. I cannot get rid of the `oauth2Login()` and only use a `oauth2ResourceServer()`  as you suggest because as mentioned in the [aad starter resource server docs](https://github.com/Azure/azure-sdk-for-java/tree/master/sdk/spring/azure-spring-boot-starter-active-directory#accessing-a-resource-server): 
> This scenario no support login

The docs for  [accessing a web application](https://github.com/Azure/azure-sdk-for-java/tree/master/sdk/spring/azure-spring-boot-starter-active-directory#accessing-a-web-application) show that the Web application can 
> evaluate permissions based on groups or role

but how am I supposed to do this without a resource server?

I have read through the web app sample and all I can find [is authorization based on roles](https://github.com/Azure/azure-sdk-for-java/blob/master/sdk/spring/azure-spring-boot-samples/azure-spring-boot-sample-active-directory-webapp/src/main/java/com/azure/spring/sample/aad/controller/RoleController.java#L15)

Our application has a very granular authority mapping for users based on the active directory groups they belong to. We have a 1 to many mapping where 1 AD groups maps to N authorities. These authorities may overlap from one group to another.

It isn't an option for us to create one AD group for every permission since this would be unmanageable for us and for our clients.

Any ideas with how I can move forward with this?

**Comment by chenrujun** [comment]
Hi, @ppartarr .

Here is my suggestion:

1. Use  [accessing a web application](https://github.com/Azure/azure-sdk-for-java/tree/master/sdk/spring/azure-spring-boot-starter-active-directory#accessing-a-web-application) . web-application and resource-server work in the same spring-boot application is not support for aad-starter. And now we do not have plan to support it.

2. Use `roles` to authorize. Currently web-application only use `groups` to create grantedAuthority. Use `roles` to create grantedAuthority is not supported yet, we plan to support it in next release. Please wait next release.

**Comment by yiliuTo** [comment]
Hi @totakura , thanks for your great advice on this feature. The [pr](https://github.com/Azure/azure-sdk-for-java/pull/19782) has been merged and you could expect our next release of 3.3.0.

**Comment by chenrujun** [comment]
Closing this issue, because the feature has been released in 3.3.0: https://github.com/Azure/azure-sdk-for-java/blob/azure-spring-boot-starter-active-directory_3.3.0/sdk/spring/azure-spring-boot-starter-active-directory/CHANGELOG.md

**Comment by ppartarr** [comment]
Thanks for the workaround @totakura and thanks for the work on the PR @yiliuTo - it's much appreciated!

**Comment by ppartarr** [comment]
hi @yiliuTo it's probably not worth opening a new issue for but I have a suggestion concerning the granted authorities docs: it might be worth adding that it doesn't work alongside the `emit_as_roles` optional claim for id tokens since the role claim would contain the group oids instead of the configured app roles.

example manifest with emit groups as role config:
```json
	"optionalClaims": {
		"idToken": [
			{
				"name": "groups",
				"source": null,
				"essential": false,
				"additionalProperties": [
					"emit_as_roles"
				]
			}
		],
		[...]
		}
```

resulting id token (those are my group oids):
```json
{
  "name": "Philippe Partarrieu",
  "roles": [
    "287686ff-d399-4875-b86d-1dd9426973d6",
    "80a34e39-50d3-405d-88b0-3522307dfed8",
    "452fe6d8-7360-47fd-b5b5-8cd8108d9233"
  ],
  [...]
}
```

resulting id token without the misconfiguration:
```json
{
  "name": "Philippe Partarrieu",
  "roles": [
    "ADMIN",
    "USER"
  ],
  [...]
}
```

**Comment by yiliuTo** [comment]
Hi @ppartarr , thanks for your advice and detailed decscription. We will update the related docs soon.
