### ISSUE TITLE
azure-storage-blob-12.10 - How to read blobs from directory ?

### ISSUE THREAD

**Issue by abhikt48** [Azure/azure-sdk-for-java#19253]
**Query/Question**
We are doing migration from `azure-storage-5.5.0` to `azure-storage-blob-12.10.0`. 
We need to read blobs from given directory and process one by one. Please find below sample code with old library. We need to do same functionality with latest SDK. I haven't found any directory related information.

Could you please suggest any alternative option with new Blob SDK for below functionality. 

**Sample Code with 5.5.0**
```
CloudBlobContainer container = cloudBlobClient.getContainerReference(containerName);
CloudBlobDirectory blobDirectory = container.getDirectoryReference(directoryName);
Iterable<ListBlobItem> listBlobItem = blobDirectory.listBlobs();
for (ListBlobItem blobItem : listBlobItem) {
	if (blobItem instanceof CloudBlockBlob) {
                    CloudBlockBlob blockBlob = (CloudBlockBlob) blobItem;
           }else{
                LOGGER.error("Not a CloudBlockBlob type")
              }
}
```
I found `listBlobsByHierarchy` operation which can be useful for above functionality. Is this right option to use it or do we have any alternative and best option? Please suggest your opinion.

`Iterator<BlobItem> iteratorBlobItem = getBlobContainerClient().listBlobsByHierarchy("test/").iterator();`

**Setup (please complete the following information if applicable):**
 - OS: Windows
 - IDE : eclipse
 - Version of the Library used - azure-storage-blob-12.10

**Comment by gapra-msft** [comment]
Hi @abhikt48 

Yes, the listBlobsByHierarchy API is the correct way to read blobs from a directory.

**Comment by gapra-msft** [comment]
@abhikt48 

We can pass this feature request on to the service team but I will close this issue as there isn't much we can do on the SDK side without service support. 

One recommendation I have is that you can instantiate a regex matcher and do a listing and filter out blobs that do not match. 

Feel free to open a new issue in case you hit any other problems and we would be happy to help..
