### ISSUE TITLE
StorageAccount custom domain indirect validation not working

### ISSUE THREAD

**Issue by jkubrynski** [Azure/azure-sdk-for-java#1926]
When I try to create a storage account with custom domain using indirect subdomain validation the setting is ignored and the `com.microsoft.azure.CloudException: The custom domain name could not be verified.` is thrown and in the message you can see that no `asverify` domain is used

**Comment by martinsawicki** [comment]
could you pls add some sample repro code?

**Comment by jkubrynski** [comment]
```
azureManager.azure().storageAccounts()
	.define("mysa").
	.withRegion("west-europe")
	.withNewResourceGroup()
	.withCustomDomain("mysa.mydomain.com", true);
```

**Comment by jkubrynski** [comment]
Even if I use it on update and I see the PATCH body looks like below{
`{"properties":{"customDomain":{"name":"mysa.mydomain.com","useSubDomain":true}}}`

it throws: `com.microsoft.azure.CloudException: Status code 409, {"error":{"code":"StorageDomainNameCouldNotVerify",`

`storageAccount.update().withCustomDomain("mysa.mydomain.com", true).apply();`

**Comment by martinsawicki** [comment]
@anuchandy any ideas?

**Comment by anuchandy** [comment]
@jkubrynski did you create a CNAME record subdomain alias with subdomain `asverify` and map it to your storage account url? after this step storage account needs to be updated with the custom domain.

**Comment by praries880** [comment]
@jkubrynski Did @anuchandy 's suggested fix help you with the issue?

**Comment by joshfree** [comment]
Adding `needs-more-info` and closing this issue that hasn't had a follow-up since September 2017.
