### ISSUE TITLE
[BUG] Noisy Error Logs in azure-identity

### ISSUE THREAD

**Issue by FishyJoel** [Azure/azure-sdk-for-java#19278]
**Describe the bug**
Unnecessary and noisy error logs from com.azure.identity.implementation.MSIToken class

**To Reproduce**
This issue occurs whenever a date in the format "02/17/2021 17:03:10 +00:00" is passed into the parseDateToEpochSeconds() method.

***Code Snippet***
MSIToken.java lines 60-78:

```
        try {
            return Long.parseLong(dateTime);
        } catch (NumberFormatException e) {
            logger.error(e.getMessage());
        }

        try {
            return Instant.from(dtf.parse(dateTime)).getEpochSecond();
        } catch (DateTimeParseException e) {
            logger.error(e.getMessage());
        }

        try {
            return Instant.from(dtfWindows.parse(dateTime)).getEpochSecond();
        } catch (DateTimeParseException e) {
            logger.error(e.getMessage());
        }

        throw logger.logExceptionAsError(new IllegalArgumentException("Unable to parse date time " + dateTime));
```

This makes three attempts to parse the input string, and each can generate an unnecessary error log.  The NumberFormatException and DateTimeParseExceptions should instead be logged at a lower level (INFO or DEBUG).

**Expected behavior**
No errors are logged if the date is successfully parsed.

**Setup (please complete the following information):**
 - OS: CentOS
 - IDE : IntelliJ
 - Version of the Library used:  This issue is present in Azure-Identity 1.0.4 and 1.2.3.

**Information Checklist**
Kindly make sure that you have added all the following information above and checkoff the required fields otherwise we will treat the issuer as an incomplete report
- [X ] Bug Description Added
- [X ] Repro Steps Added
- [X ] Setup information Added

**Comment by alzimmermsft** [comment]
FYI @g2vinay, @jianghaolu

**Comment by joshfree** [comment]
Thanks for filing this detailed issue @FishyJoel.  We'll include this improvement in an upcoming minor release of azure-identity.

Would you be interested in sending a PR with the change?

**Comment by g2vinay** [comment]
@FishyJoel Thank you for reporting this issue. 
I will look into this and potentially relax the log level and release the update in our March stable release.

**Comment by g2vinay** [comment]
@FishyJoel 
The log levels have been relaxed and switched to verbose.
You can try out the change in latest release:
```
<dependency>
  <groupId>com.azure</groupId>
  <artifactId>azure-identity</artifactId>
  <version>1.2.5</version>
</dependency>
```
