### ISSUE TITLE
Investigate Leveraging Jackson AfterBurner/Blackbird

### ISSUE THREAD

**Issue by alzimmermsft** [Azure/azure-sdk-for-java#19284]
Investigate adding the Jackson AfterBurner or Blackbird dependencies to offer potentially better deserialization performance.

**Comment by JV-TMCZ** [comment]
com.azure:azure-cosmosdb already depends on afterburner... unfortunatelly, afterburner is not compatible with java11. Currently throws warning. Please, consider a forward compatibility for newer versions of java... 

NOTE: when cosmos sdk wrapped in com.azure:azure-spring-data-cosmos, then spring data dependency boms brings their own (managed version) of afterburner. 

NOTE: There are voices on internet ... which saying that afterburner / blackbird are not neccessary any more... 
```
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by com.fasterxml.jackson.module.afterburner.util.MyClassLoader (file:/xxx/.m2/repository/com/fasterxml/jackson/module/jackson-module-afterburner/2.12.2/jackson-module-afterburner-2.12.2.jar) to method java.lang.ClassLoader.findLoadedClass(java.lang.String)
WARNING: Please consider reporting this to the maintainers of com.fasterxml.jackson.module.afterburner.util.MyClassLoader
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release
```

**Comment by alzimmermsft** [comment]
Closing as won't be done
