### ISSUE TITLE
[BUG] EventHubs "Quickstarts" Java SDK version isn't updated

### ISSUE THREAD

**Issue by YijunXieMS** [Azure/azure-sdk-for-java#19287]
In this quickstarts doc https://docs.microsoft.com/en-us/azure/event-hubs/event-hubs-java-get-started-send, both send and receive use old versions of the SDK. One is 5.0.1 the other one 5.1.1. 
This document should use the latest GA version.

**Comment by conniey** [comment]
This is updated to 5.6.0, which is good. :D
