### ISSUE TITLE
NullPointerException in SnapshotsImpl

### ISSUE THREAD

**Issue by xy24** [Azure/azure-sdk-for-java#1932]
Hi,

NPE occurs when looking up a non existent snapshot. Seems similar to [azure-sdk-for-java/issues/1797](https://github.com/Azure/azure-sdk-for-java/issues/1797)

Location:
[SnapshotsImpl.java#L83](https://github.com/Azure/azure-sdk-for-java/blob/master/azure-mgmt-compute/src/main/java/com/microsoft/azure/management/compute/implementation/SnapshotsImpl.java#L83)

![screen shot 2017-10-02 at 3 48 42 pm](https://user-images.githubusercontent.com/5641057/31097194-7cd77316-a78c-11e7-9163-0ac0441afeff.png)

StackTrace:
![screen shot 2017-10-02 at 4 27 07 pm](https://user-images.githubusercontent.com/5641057/31098179-c447ecf0-a78f-11e7-89a1-e514fd6c6c35.png)

Thanks

**Comment by martinsawicki** [comment]
fixed for v1.4
