### ISSUE TITLE
[BUG] BlobClient.uploadWithResponse should either return a response or be renamed

### ISSUE THREAD

**Issue by timrobinson33** [Azure/azure-sdk-for-java#19324]
**Describe the bug**
`com.azure.storage.blob.BlobClient.uploadWithResponse` has 3 overloads, 2 of them return a response as expected but the one with 9 parameters is returns void. This is inconsistent and confusing.

https://docs.microsoft.com/en-gb/java/api/com.azure.storage.blob.blobclient.uploadwithresponse?view=azure-java-stable#com_azure_storage_blob_BlobClient_uploadWithResponse_java_io_InputStream_long_com_azure_storage_blob_models_ParallelTransferOptions_com_azure_storage_blob_models_BlobHttpHeaders_java_util_Map_java_lang_String_java_lang_String__com_azure_storage_blob_models_AccessTier_com_azure_storage_blob_models_BlobRequestConditions_java_time_Duration_com_azure_core_util_Context_

**Comment by rickle-msft** [comment]
@timrobinson33 Thank you for your question. We are aware of this discrepancy. The inconsistency between name and return type was over looked in our pre-GA api review; "withResponse" is the typical suffix for the max overloads, which this method was at the time, so we followed that consistency with other apis even though it didn't return a response. Unfortunately, we cannot change the signature at this point without a breaking change. There is, however, an overload which accepts BlobParallelUploadOptions that serves as the new max overload and does indeed return a response.

**Comment by gapra-msft** [comment]
Closing as I believe the question has been answered. @timrobinson33 Please feel free to reopen if you have further questions regarding this overload.
