### ISSUE TITLE
[BUG] Setting setRetrieveDeletedBlobs to true when listing blobs in container doesn't return any of the soft deleted blobs.

### ISSUE THREAD

**Issue by PbALpi7xEX** [Azure/azure-sdk-for-java#19335]
**Describe the bug**
Setting setRetrieveDeletedBlobs to true when listing blobs in container doesn't return any of the soft deleted blobs. 

***Exception or Stack Trace***
None. Results simply don't contain the deleted blobs

**To Reproduce**

- enable soft delete in storage account with blob versioning enabled
- setup BlobListOptions to retrieve soft deleted blobs
- list container blobs by hierarchy

***Code Snippet***
```
ListBlobsOptions options = new ListBlobsOptions().setPrefix(directoryName)
				.setDetails(new BlobListDetails().setRetrieveDeletedBlobs(true).setRetrieveMetadata(true));
containerClient.listBlobsByHierarchy("/", options, null);
```

**Expected behavior**
Expect the soft deleted blobs to appear in my list as along with active blobs.

**Setup (please complete the following information):**
 - OS: Windows 10
 - IDE : Eclipse
 - Version of the Library used: 12.10.0

**Additional context**
Spring Boot 2.3.8.RELEASE

**Comment by rickle-msft** [comment]
@PbALpi7xEX Thanks for opening this issues. I've run our tests for this case and everything seems to be looking fine. Can you please ensure that soft delete is in fact enabled on the account, perhaps by running a test in which you delete and undelete a blob. And can you also share your input? i.e. the full names of soft deleted blobs are in the container at the time of listing

**Comment by PbALpi7xEX** [comment]
Hi @rickle-msft ,

Soft delete is indeed enabled as well as blob versioning. My understanding is "undelete" with blob versioning doesn't work as intended. I discovered this while undeleting in the Azure portal. Clicking undelete although reports success, does nothing, blob remains deleted. A note mentions to use the versions tab and to make a version the current version by clicking "make current version". This works. In code, I replicated this by simply copying a versioned blob client to base blob. Seems to work.

Here is a listBlob call at the HTTP level. Not sure if you need something unmasked... I don't specify an API version, I understand this will default to latest.

`GET https://*******.blob.core.windows.net/samplesite?prefix=docs/eng/&delimiter=/&maxresults=10&include=deleted%2Cmetadata&restype=container&comp=listDate:REDACTEDAuthorization:REDACTEDContent-Length:REDACTEDx-ms-version:REDACTEDx-ms-client-request-id:REDACTEDUser-Agent:REDACTED(empty body)--> END GET
`
This folder contains 2 files, one is deleted.

`https://*********blob.core.windows.net/samplesite/docs/eng/test1.html`

**Comment by rickle-msft** [comment]
@PbALpi7xEX Thanks for that information and for those logs. What I'm noticing is you don't have the include query param set on the request. This is the url for the request that is successful for me: `https://***.blob.core.windows.net/jtclistblobshieroptionsdeleted0721708149467e62bd4?restype=container&comp=list&delimiter=&include=deleted`

Note the "include=deleted" parameter that is required for this behavior. I'm not sure if that needs to be whitelisted in your logging (another allowed query parameter entry) or if it's just not on your request. Could you double check that, please?

**Comment by PbALpi7xEX** [comment]
Hi @rickle-msft ,

I have it my URL as well...

GET https://*******.blob.core.windows.net/samplesite?prefix=docs/eng/&delimiter=/&maxresults=10&**include=deleted**%2Cmetadata&restype=container&comp=listDate:REDACTEDAuthorization:REDACTEDContent-Length:REDACTEDx-ms-version:REDACTEDx-ms-client-request-id:REDACTEDUser-Agent:REDACTED(empty body)--> END GET

**Comment by rickle-msft** [comment]
Ah. My apologies. It is in your url as well. I believe I did try those options earlier as well, but let me double check and send the url here just so we can align on that before moving on. 

You said there are two files in the folder. Are you successfully seeing the one that was not deleted?

**Comment by PbALpi7xEX** [comment]
No worries. Yes 2 files. I see the one that isn't deleted.

**Comment by PbALpi7xEX** [comment]
> I also wonder if the odd interaction between versioning and soft delete is getting in the way of listing as well as undeleting.

I agree. I see some irregularities even in the Portal when clicking "show deleted blobs"... and as mentioned above, undelete does nothing. Portal note says to select version in versions tab and "make current version".

When I think more about this, there isn't any reason to have soft delete enabled when blob versioning is also enabled is there? A delete will always stamp the current version as the last version...

**Comment by rickle-msft** [comment]
The only reason I can think of is possibly being able to undelete an old version if you accidentally delete a version that is not current. But I have to double check if that's even viable. As far as protecting the base blob, there is no need for soft delete if you have versioning enabled. 

Rather than investigating the request behavior further, would you like me to do some more digging into the relationship between these features? And if so, can you specify exactly which questions you'd like clarification on?

**Comment by PbALpi7xEX** [comment]
Disabling soft delete hasn't changed the list behaviour. Still doesnt list the "deleted" blob. I think blob versioning requires a different approach not immediately apparent with the SDK methods as they are now.

Could you shed some light on that?

If i enable BlobListDetails to also retrieve versions, I see the deleted blob, but all the other versions as well.. We'd only want the last most recent version, as it would refer to version when blob was deleted.

**Comment by rickle-msft** [comment]
I think we may want to actually try the reverse given your use case: Try disabling versioning and enabling soft delete. Have you tested with that configuration?

**Comment by PbALpi7xEX** [comment]
Hi @rickle-msft,

Disabled blob versioning on the SA, re-enabled soft delete and did a listBlobsByHierarchy :

GET https://*****.blob.core.windows.net/samplesite?delimiter=/&maxresults=10&**include=deleted**%2Cmetadata&restype=container&comp=listDate:REDACTEDAuthorization:REDACTEDContent-Length:REDACTEDx-ms-version:REDACTEDx-ms-client-request-id:REDACTEDUser-Agent:REDACTED(empty body)--> END GET

Deleted blobs still not returned in the list. I noticed the portal still wasn't allowing me to undelete even though versioning was disabled on the SA. I noticed the deleted blob had versions (from when versioning was enabled). Deleting the versions still doesn't pick up the blob in the listing as deleted.

I created a new blob to test with fresh copy, then deleted. That worked. Blob returned in the list and showing with "deleted" status in the metadata.

So seems the whole concept of "deletions" goes by the wayside when blob versions exist for given blob. Seems they got around this in the portal.. but probably required some custom code not implemented through the common SDK methods.

**Comment by PbALpi7xEX** [comment]
Hi @rickle-msft ,

We've decided to forego blob versioning at this time and manage snapshots instead. Basically achieves the same result, just with a bit more code, but we can rely on better deletion support.

**Comment by rickle-msft** [comment]
@PbALpi7xEX Well I'm glad we at least resolved some of the mystery around the api behavior. I'm going to close this issue now as I think it's been resolved, but please feel free to reach out if you need further support.

**Comment by PbALpi7xEX** [comment]
FYI... trying to show deleted blobs in the portal on large and deep blob structures not responsive... as we discovered using the SDK... we cannot query using listBlobsByHierarchy AND show deleted blobs at the same time... there seems to be a limitation in the SDK implementation.

Show deleted blobs will only work when used with "listBlobs" method, which returns a flattened collection of every single blob in the container. This works for small containers, but it becomes painfully unresponsive for large containers. Our container has 16k+ blobs in it.

**Comment by PbALpi7xEX** [comment]
Hi @rickle-msft ,

I've opened a feature request

#19486

Seems we can't find a viable solution to show deleted blobs in our container. Our containers are complete websites, one of which contains 18k+ blobs and virtual folders.
