### ISSUE TITLE
[BUG] Can't find iothub-connection-device-id in message received from EventHubClient

### ISSUE THREAD

**Issue by marc-roedder-gcx** [Azure/azure-sdk-for-java#19389]
**Describe the bug**
Since updating the EventHub SDK dependency, I can't get iothub-connection-device-id out of the event´s properties anymore.

***Exception or Stack Trace***

**To Reproduce**

- Send a message via EventHub
- Try to find out iothub-connection-device-id 

***Code Snippet***
(The code is Kotlin)

EventHubClientBuilder()
            .connectionString(connectionString)
            .consumerGroup(EventHubClientBuilder.DEFAULT_CONSUMER_GROUP_NAME)
            .buildAsyncConsumerClient()
            .apply {
                receive(false).subscribe { event ->
                    val deviceId = event.data.properties["iothub-connection-device-id"] as? String
                }
            }

**Expected behavior**
There should be some way to find out the iothub-connection-device-id

**Setup (please complete the following information):**
 - OS: Mac OS Big Sur
 - IDE : IntelliJ
 - Version of the Library used: 5.4.0

**Additional context**
Last known good version of the library was 5.1.0. Maybe in-between these two versions there was a change in how to fetch this piece of information?

**Information Checklist**
Kindly make sure that you have added all the following information above and checkoff the required fields otherwise we will treat the issuer as an incomplete report
- [x] Bug Description Added
- [x] Repro Steps Added
- [x] Setup information Added

**Comment by joshfree** [comment]
@conniey could you please take a look?

**Comment by conniey** [comment]
Thanks for reporting this! I'll take a look. I remember we had made modifications some time ago.

**Comment by conniey** [comment]
Hey. We put system-generated properties into `getSystemProperties()`. Properties should only contain application properties. Does that answer your question?

![image](https://user-images.githubusercontent.com/10136526/116135156-9e33fb00-a685-11eb-9391-1624f2f0104a.png)
