### ISSUE TITLE
Jackson 2.12.0 causes infinite loop(read) in method BlobContainerClient.listBlobsByHierarchy

### ISSUE THREAD

**Issue by biliboc** [Azure/azure-sdk-for-java#19392]
> Just FYI, I experience this issue when upgrading from jackson-databind 2.11.4 (Dec 2020) to 2.12.0 (Nov 2020) c.f.

I've experienced this same issue upgrading to `2.12.0`, the problem seems to be that the default behaviour in that version has changed (https://github.com/FasterXML/jackson-dataformat-xml/issues/411) and for an empty block, it now returns an empty string instead of `null`. I don't think there's a way to inject a custom `SerializerAdapter`. The fix should be fairly trivial to implement in `JacksonAdapter#JacksonAdapter` and configure the parser to behave as expected.

Please make this work with Jackson 2.12.0

_Originally posted by @fcofdez in https://github.com/Azure/azure-sdk-for-java/issues/9465#issuecomment-775044143_

**Comment by alzimmermsft** [comment]
Thank you for submitting this issue @biliboc, this should be resolved when #18884 is released.

**Comment by gapra-msft** [comment]
This issue will be resolved once the 12.11.0-beta.2 azure-storage-blob library is released

**Comment by gapra-msft** [comment]
Hi, we recently released azure-storage-blob 12.11.0-beta.2 that should fix this issue. Please try it out and let us know if you are still hitting the issue.

Feel free to close this once you've confirmed the latest release fixes your issue.
