### ISSUE TITLE
Spring Data Cosmos MultiDatabase sample is not working

### ISSUE THREAD

**Issue by woodymoo** [Azure/azure-sdk-for-java#19408]
**Query/Question**
 I tried the multidatabase samples on the folder which is new spring data cosmos release version 3.4.0, but it does not work. can you please provide a complete sample with pom.xml ?
The sampleapplication run method never switch the databases always called the first database in the property file. 

https://github.com/Azure/azure-sdk-for-java/tree/master/sdk/cosmos/azure-spring-data-cosmos/src/samples/java/com/azure/spring/data/cosmos/multidatasource
https://github.com/Azure/azure-sdk-for-java/tree/master/sdk/cosmos/azure-spring-data-cosmos
based on azure-spring-boot-starter-cosmos 3.1.0.
    <dependency>
      <groupId>com.azure.spring</groupId>
      <artifactId>azure-spring-boot-starter-cosmos</artifactId>
      <version>3.1.0</version> 
    </dependency>

***Why is this not a Bug or a feature Request?***
A clear explanation of why is this not a bug or a feature request?

**Setup (please complete the following information if applicable):**
 - OS: mac os 11.15.7
 - IDE : Intellij
 - Version of the Library used
 
 **Information Checklist**
 Kindly make sure that you have added all the following information above and checkoff the required fields otherwise we will treat the issuer as an incomplete report
- [ ] Query Added
- [ ] Setup information Added

**Comment by kushagraThapar** [comment]
@chenrujun  - I believe you are already looking at this issue here - https://github.com/microsoft/spring-data-cosmosdb/issues/554
Please close the issue on spring-data-cosmosdb repo, and let's work it out here.

**Comment by woodymoo** [comment]
sure, thanks very much.
