### ISSUE TITLE
Create Tooling to Automate Patch Release Branch Creation

### ISSUE THREAD

**Issue by alzimmermsft** [Azure/azure-sdk-for-java#19400]
Add a script, preferably Python or PowerShell, which is capable of creating an increment dependency versions patch release branch from a given SHA and set of folder paths. The assumption of the passed SHA is that it is the release SHA of the last GA release for a given library, or set of libraries. All changes from the latest SHA will be applied to the passed SHA and changes in the given folder paths will be reverted.

**Comment by weshaggard** [comment]
Is the goal here to automate creating a branch from a release tag and then cherry-pick another sha of changes scoped to only a single directory? Or is there more to it then that?

**Comment by alzimmermsft** [comment]
@weshaggard that is basically the goal here.

1. Create a branch from the most recent patch release from the same major.minor version
2. Pull all changes made to main between that point-in-time to when the script is running
3. Revert all changes made to a select set of sub-directories
4. Create a release branch in upstream
5. Update dependency versions
6. Create a commit and target the branch created in step 4

**Comment by weshaggard** [comment]
It might be tricky to get steps 2-3 correct in a generic fashion. Usually when doing a hotfix you only want to cherry-pick just the one change and update the versions, as outlined at https://azure.github.io/azure-sdk/policies_repobranching.html#hotfix-branches. If you try and pull all other changes I suspect you might be in a strange state.

**Comment by alzimmermsft** [comment]
I should clarify that this issue isn't for tooling to create hotfix branches but to perform a monthly version update release while a library has an on-going beta cycle. That is, once a month, while in the beta cycle, during release a patch GA release will be done which updates core dependencies such as `azure-core`. This is done so that the library doesn't go months without dependency version updates, which due to Java using specific dependency versions, and not ranges, will help reduce dependency conflicts seen in the wild.

**Comment by alzimmermsft** [comment]
Resolved by #23722
