### ISSUE TITLE
[QUERY] document the contents of sdk/cosmos/

### ISSUE THREAD

**Issue by RUBenGAMArrarodRiguEZ-ToMtOm** [Azure/azure-sdk-for-java#19421]
**Query/Question**
A clear and concise ask/query.
Would be possible to document what libraries are available for cosmos and their recommended use cases?

Would be possible to: 
+ Add a `readme.md` to [sdk/cosmos](https://github.com/Azure/azure-sdk-for-java/tree/cdd7738cfb524c7a41367a43798438fba7653da2/sdk/cosmos) listing the contents of the folders there. For example briefly list the difference between 
   + azure-cosmos-benchmark
   + azure-cosmos
   + azure-spring-data-cosmos-test
   + azure-spring-data-cosmos
   + mgmt-v2019_08_01
   + mgmt-v2019_08_01_preview
   + mgmt-v2019_12_12
+ Have some info in the landing page in the [wiki](https://github.com/Azure/azure-sdk-for-java/wiki/Home/3482f7800803fb6c953ee32ecb486dd398a5b031) of the technologies in this repo. I think there is no mention of some individual technologies like cosmo there
+ Clarify or list Spring data cosmos in https://azure.github.io/azure-sdk/releases/latest/index.html#java
+ Clarify or list azure-cosmos in https://docs.microsoft.com/en-us/azure/developer/java/?view=azure-java-stable although there is a mention of _Spring Data Azure Cosmos DB_ but I find difficult to find an overview of azure-cosmos

**Why is this not a Bug or a feature Request?**
I am not really sure, this seems the most appropriate issue template. Is not a problem related to the main functionality in a piece of code.

**Setup (please complete the following information if applicable):**
 - OS: n/a
 - IDE: n/a
 - Version of the Library used
 
 **Information Checklist**
 Kindly make sure that you have added all the following information above and checkoff the required fields otherwise we will treat the issuer as an incomplete report
- [x] Query Added
- [x] Setup information Added

**Comment by joshfree** [comment]
Hi @RUBenGAMArrarodRiguEZ-ToMtOm most of those subdirectories do have a README.md which describes the purpose of the client library with some examples of use.  With that said, some of them, like the control plane (mgmt) are missing READMEs.

@kushagraThapar would it make sense to add a root README for all of Cosmos similar to large areas, like Storage?

**Comment by kushagraThapar** [comment]
@joshfree I think it would make sense, I will work on that.

**Comment by RUBenGAMArrarodRiguEZ-ToMtOm** [comment]
Hi @joshfree, @kushagraThapar,

if you see it as appropriate maybe that bit of information can be placed somewhere so that people can also access the answer.

From my side this issue can be closed. 🙂

**Comment by kushagraThapar** [comment]
@joshfree - who would be the best person to work on adding azure-spring-data-cosmos SDK to this page https://azure.github.io/azure-sdk/releases/latest/java.html ?
