### ISSUE TITLE
Archive Blob Storage and Blob-Level Tiering

### ISSUE THREAD

**Issue by cswarth** [Azure/azure-sdk-for-java#1943]
Is there a timeframe for adding support for Blob-Level Tiering and Archive Blob Storage to this Java SDK?

[Announcing the public preview of Azure Archive Blob Storage and Blob-Level Tiering](https://azure.microsoft.com/en-us/blog/announcing-the-public-preview-of-azure-archive-blob-storage-and-blob-level-tiering/)

**Comment by martinsawicki** [comment]
tbd at this point

**Comment by joshfree** [comment]
@amishra-dev can you please help route this?

**Comment by amishra-dev** [comment]
@cswarth this support was shipped in version 8.5 and in 12.0.0-Preview3
