### ISSUE TITLE
Monitor Opentelemetry Exporter Sample issue

### ISSUE THREAD

**Issue by Melanie-Ma** [Azure/azure-sdk-for-java#19468]
1.
Section [Link1](https://github.com/Azure/azure-sdk-for-java/blob/master/sdk/monitor/azure-monitor-opentelemetry-exporter/src/samples/java/com/azure/monitor/opentelemetry/exporter/ReadmeSamples.java#L33), [Link2](https://github.com/Azure/azure-sdk-for-java/blob/master/sdk/monitor/azure-monitor-opentelemetry-exporter/src/samples/java/com/azure/monitor/opentelemetry/exporter/ReadmeSamples.java#L45), [Link3](https://github.com/Azure/azure-sdk-for-java/blob/master/sdk/monitor/azure-monitor-opentelemetry-exporter/src/samples/java/com/azure/monitor/opentelemetry/exporter/AppConfigurationAzureMonitorExporterSample.java#L37), [Link4](https://github.com/Azure/azure-sdk-for-java/blob/master/sdk/monitor/azure-monitor-opentelemetry-exporter/src/samples/java/com/azure/monitor/opentelemetry/exporter/EventHubsAzureMonitorExporterSample.java#L49):
![image](https://user-images.githubusercontent.com/64007802/109248618-15354a80-7821-11eb-8c73-9189898d311c.png)
Reason:
Cannot resolve symbol 'AzureMonitorTraceExporter' and  cannot resolve method 'buildTraceExporter' in 'AzureMonitorExporterBuilder'.
Suggestion:
Change to: 
```
AzureMonitorExporter azureMonitorTraceExporter = new AzureMonitorExporterBuilder()
            .connectionString("{connection-string}")
            .buildExporter();
```

@jongio , for notification

**Comment by v-xuto** [comment]
Close this issue because the latest version now released has re-supported the call of `buildTraceExporter()`.
