### ISSUE TITLE
Quantum Jobs Readme and Sample issues

### ISSUE THREAD

**Issue by Melanie-Ma** [Azure/azure-sdk-for-java#19467]
1.  
Section [Link](https://github.com/Azure/azure-sdk-for-java/tree/master/sdk/quantum/azure-quantum-jobs#azure-quantum-jobs-client-library-for-java):
![image](https://user-images.githubusercontent.com/64007802/109244495-c7691400-7819-11eb-9863-bfd83b1fb710.png)
Suggestion:
For 1: Link change to https://azure.github.io/azure-sdk-for-java/
For 2: Add text comment [| [Samples][samples]]and add link to [samples] :https://github.com/Azure/azure-sdk-for-java/tree/master/sdk/quantum/azure-quantum-jobs/src/samples/java/com/azure/quantum/jobs
2.
Section [Link](https://github.com/Azure/azure-sdk-for-java/tree/master/sdk/quantum/azure-quantum-jobs#examples):
![image](https://user-images.githubusercontent.com/64007802/109244748-35154000-781a-11eb-82ae-f1af853e4736.png)
Suggestion:
Add Link  `[Create the client](#create-the-client)`
3.
Section [Link](https://github.com/Azure/azure-sdk-for-java/blob/master/sdk/quantum/azure-quantum-jobs/src/samples/java/com/azure/quantum/jobs/ReadmeSamples.java#L91):
![image](https://user-images.githubusercontent.com/64007802/109245834-262f8d00-781c-11eb-824f-f640fcea4782.png)
Suggestion:
Change to `{uploadFilePath}`

@jongio, for notification

**Comment by v-xuto** [comment]
Close this issue, due to PR https://github.com/Azure/azure-sdk-for-java/pull/21884 merged.
