### ISSUE TITLE
Communication-chat Readme issue

### ISSUE THREAD

**Issue by Melanie-Ma** [Azure/azure-sdk-for-java#19469]
1.
Section [Link](https://github.com/Azure/azure-sdk-for-java/tree/azure-communication-common_1.0.0-beta.4/sdk/communication/azure-communication-chat#examples):
![image](https://user-images.githubusercontent.com/64007802/109264227-9b608980-783f-11eb-8fbe-ed1624e1ef10.png)
Suggestion:
For 1: Change to `[Chat Thread Operations](#chat-thread-operations)`
For 2: Change to `[Chat Message Operations](#chat-message-operations)`
For 3: Change to `[Chat Thread Member Operations](#chat-thread-member-operations)`

@jongio , for notification

**Comment by ashwinder** [comment]
Thanks @Melanie-Ma for raising this issue. Our engineering team will be working on this shortly.

**Comment by angiurgiu** [comment]
Updated and fixed, thanks for spotting this @Melanie-Ma
