### ISSUE TITLE
Tracing Opentelemetry Reademe issue

### ISSUE THREAD

**Issue by Melanie-Ma** [Azure/azure-sdk-for-java#19472]
1.
Section [Link](https://github.com/Azure/azure-sdk-for-java/tree/master/sdk/core/azure-core-tracing-opentelemetry#additional-documentation):
![image](https://user-images.githubusercontent.com/64007802/109250405-9a6e2e80-7824-11eb-8b11-fa803a8ab2a4.png)
Suggestion:
Link changes to https://azure.github.io/azure-sdk-for-java/

@jongio , for notification

**Comment by samvaity** [comment]
Closed with #21879
