### ISSUE TITLE
Cosmos Reademe issue

### ISSUE THREAD

**Issue by Melanie-Ma** [Azure/azure-sdk-for-java#19471]
1.
Section [Link](https://github.com/Azure/azure-sdk-for-java/tree/master/sdk/cosmos/azure-cosmos#prerequisites):
![image](https://user-images.githubusercontent.com/64007802/109250082-f2f0fc00-7823-11eb-83c9-ad4b95d818ba.png)
Suggestion:
For 1: Text change to ` Java Development Kit (JDK) with version 8 or above` and add link https://docs.microsoft.com/java/azure/jdk/
For 2: Add link http://www.slf4j.org/
For 3: Add link https://maven.apache.org/

@jongio , for notification

**Comment by kushagraThapar** [comment]
@Melanie-Ma - would you be willing to update this doc ?
