### ISSUE TITLE
Search Documents Sample issue

### ISSUE THREAD

**Issue by Melanie-Ma** [Azure/azure-sdk-for-java#19476]
1.
Section [Link](https://github.com/Azure/azure-sdk-for-java/blob/master/sdk/search/azure-search-documents/src/samples/java/com/azure/search/documents/ReadmeSamples.java#L99):
![image](https://user-images.githubusercontent.com/64007802/109262994-7c60f800-783d-11eb-86f9-8839de1e32a1.png)
Reason:
Index definition must contain one or more valid fields.
Suggestion:
Change to : 
```
    SearchIndex index = new SearchIndex(indexName);
	        List<SearchField> searchFieldList = new ArrayList<>();
	        searchFieldList.add(new SearchField("hotelId", SearchFieldDataType.STRING)
	                .setKey(true)
	                .setFilterable(true)
	                .setSortable(true));
	        index.setFields(searchFieldList);
```
2.
Section [Link](https://github.com/Azure/azure-sdk-for-java/blob/master/sdk/search/azure-search-documents/src/samples/java/com/azure/search/documents/ReadmeSamples.java#L236):
![image](https://user-images.githubusercontent.com/64007802/109263129-b4683b00-783d-11eb-9db5-7e7e21a7f5f9.png)
Reason:
Each index must have exactly one key field.
Suggestion:
Delete this key field setting.

@jongio , for notification.

**Comment by alzimmermsft** [comment]
Thank you for the feedback @Melanie-Ma! I'll get this corrected shortly
