### ISSUE TITLE
Form Recognizer Sample issue

### ISSUE THREAD

**Issue by Melanie-Ma** [Azure/azure-sdk-for-java#19470]
1.
Section [Link](https://github.com/Azure/azure-sdk-for-java/tree/master/sdk/formrecognizer/azure-ai-formrecognizer#manage-your-models):
![image](https://user-images.githubusercontent.com/64007802/109249362-84f80500-7822-11eb-975f-b55ded93a8a3.png)
Suggestion:
Link changes to https://github.com/Azure/azure-sdk-for-java/tree/master/sdk/formrecognizer/azure-ai-formrecognizer/src/samples

@jongio , for notification

**Comment by samvaity** [comment]
Hey @Melanie-Ma, could you give me more details on this about what needs to be fixed?
