### ISSUE TITLE
Compute List Images PagedFlux blockFirst is Listing All Pages

### ISSUE THREAD

**Issue by alzimmermsft** [Azure/azure-sdk-for-java#19494]
While investigating large files in the repository I came across `VirtualMachineImageOperationsTests.canListVirtualMachineImages` which is roughly 80MB. To understand why I ran the test and began making some tweaks to see if I could reduce the number of service calls being made. The first change I made was changing a call to list images to only retrieve the first one.

Here `TestUtilities.getSize` iterated over the entire `PagedIterable` when it really wanted to validate one element exists. This resulted in about 20-30k network calls.

```java
PagedIterable<VirtualMachineImage> images = computeManager.virtualMachineImages().listByRegion(Region.US_EAST);
Assertions.assertTrue(TestUtilities.getSize(images) > 0);
```

Changing the logic to this:

```java
PagedIterable<VirtualMachineImage> images = computeManager.virtualMachineImages().listByRegion(Region.US_EAST);
Assertions.assertTrue(images.iterator().hasNext());
```

And then later this:

```java
VirtualMachineImage virtualMachineImage = computeManager.virtualMachineImages()
    .listByRegionAsync(Region.US_EAST)
    .blockFirst();
Assertions.assertNotNull(virtualMachineImage);
```

Did not reduce the number of network calls as expected. What I believe is that there is a bug in the logic which results in complete iteration of all pages to always happen based on my experimenting.

cc: @weidongxu-microsoft @srnagar

**Comment by weidongxu-microsoft** [comment]
The reason is that this one `listByRegion` do some crazy things.
https://github.com/Azure/azure-sdk-for-java/blob/master/sdk/resourcemanager/azure-resourcemanager-compute/src/main/java/com/azure/resourcemanager/compute/implementation/VirtualMachineImagesImpl.java#L85-L98

Basically there is no service REST API that list virtual machine image by region. Service REST will list offer, for each offer list sku, for each sku list image. And when the code combine these to a simpler API (on surface) it will become this one.

Not sure how to improve it. I guess I will just delete the json and disable the test...

**Comment by alzimmermsft** [comment]
I didn't realize that the service didn't provide a direct REST endpoint for this. 

Depending on if the return order from the service is consistent, or in a mocked test, we should validate that if the first offer page's first sku page's first image page contains what is being looked for only makes 3 service call.

Visual, the hierarchy of first pages leading to the value I want.
```
-> First offers page
   |
   -> First SKUs page
      |
      -> First VM images page
         |
         -> <VM image I want>
```

```
-> First offers page
   |
   -> All SKU pages
      |
      -> All VM image pages
```

**Comment by weidongxu-microsoft** [comment]
Yes, ideally this should be the solution. The challenge is to make the hierarchy of paging to a single `PagedFlux` structure (with list of items, and the `continuationToken`, which might cross the boundary of the the hierarchy), as customer might really want all of the results into a `PagedFlux`. But really the question is whether SDK should provide this kind of "convenience".
