### ISSUE TITLE
Create and mange postgres installations from SDK

### ISSUE THREAD

**Issue by theodiefenthal** [Azure/azure-sdk-for-java#1950]
It would be great if I could create instances of the managed postgres and change compute units from within the Java SDK such that I don't need to use Azure CLI for this purpose.

**Comment by yungezz** [comment]
HI @ChenTanyi could you pls help to confirm is this doable via current postgres sql sdk?

**Comment by ChenTanyi** [comment]
There is raw sdk for postgres currently. https://github.com/Azure/azure-sdk-for-java/tree/master/sdk/postgresql
