### ISSUE TITLE
Improve error messaging when parsing a JsonWebKey

### ISSUE THREAD

**Issue by vcolin7** [Azure/azure-sdk-for-java#19529]
Based on #16761, we should look to improve the error messages in exceptions that are thrown when trying to parse a JWK to an RSA, EC and OCT keys and there is not enough key material to do so.

**Comment by ArturPalka** [comment]
Hey @vcolin7, how is it going with this one? I'd appreciate very much better responses, because for now I get only:
```
"{"error":{"code":"BadParameter","message":"The property \"key\" must be a valid JsonWebKey object."}}"
```
 when I try to import a bad JsonWebKey.

**Comment by vcolin7** [comment]
Hi @ArturPalka. This has been in our backlog for a while. I'll see if I can squeeze it in for next month's release :)
