### ISSUE TITLE
Failed to execute goal on project com.vmturbo.mediation.azure: Could not resolve dependencies for project com.vmturbo:com.vmturbo.mediation.azure:jar:6.0.2-SNAPSHOT: Could not find artifact com.microsoft.azure:azure-client-authentication:jar:1.1.2-SNAPSHOT in ossrh (https://oss.sonatype.org/content/repositories/snapshots/) -> [Help 1]

### ISSUE THREAD

**Issue by ImranBijapuri** [Azure/azure-sdk-for-java#1953]
[WARNING] Could not validate integrity of download from https://oss.sonatype.org/content/repositories/snapshots/com/microsoft/azure/azure-client-authentication/1.1.2-SNAPSHOT/maven-metadata.xml: Checksum validation failed, no checksums available
[WARNING] Checksum validation failed, no checksums available for https://oss.sonatype.org/content/repositories/snapshots/com/microsoft/azure/azure-client-authentication/1.1.2-SNAPSHOT/maven-metadata.xml
[INFO] Downloaded: https://oss.sonatype.org/content/repositories/snapshots/com/microsoft/azure/azure-client-authentication/1.1.2-SNAPSHOT/maven-metadata.xml (0 B at 0.0 KB/sec)
[WARNING] The metadata /Users/imranbijapuri/.m2/repository/com/microsoft/azure/azure-client-authentication/1.1.2-SNAPSHOT/maven-metadata-ossrh.xml is invalid: input contained no data
[WARNING] The metadata /Users/imranbijapuri/.m2/repository/com/microsoft/azure/azure-client-authentication/1.1.2-SNAPSHOT/maven-metadata-ossrh.xml is invalid: input contained no data
[INFO] Downloading: http://build.vmturbo.com:8081/nexus/content/repositories/vmturbo/com/microsoft/azure/azure-client-authentication/1.1.2-SNAPSHOT/azure-client-authentication-1.1.2-SNAPSHOT.pom
[INFO] Downloading: http://build.vmturbo.com:8081/nexus/content/repositories/snapshots/com/microsoft/azure/azure-client-authentication/1.1.2-SNAPSHOT/azure-client-authentication-1.1.2-SNAPSHOT.pom
[INFO] Downloading: http://repo2.maven.org/maven2/com/microsoft/azure/azure-client-authentication/1.1.2-SNAPSHOT/azure-client-authentication-1.1.2-SNAPSHOT.pom
[INFO] Downloading: https://repository.jboss.org/nexus/content/repositories/deprecated/com/microsoft/azure/azure-client-authentication/1.1.2-SNAPSHOT/azure-client-authentication-1.1.2-SNAPSHOT.pom
[INFO] Downloading: https://oss.sonatype.org/content/repositories/snapshots/com/microsoft/azure/azure-client-authentication/1.1.2-SNAPSHOT/azure-client-authentication-1.1.2-SNAPSHOT.pom
[WARNING] The POM for com.microsoft.azure:azure-client-authentication:jar:1.1.2-SNAPSHOT is missing, no dependency information available
[WARNING] The metadata /Users/imranbijapuri/.m2/repository/com/microsoft/azure/azure-client-authentication/1.1.2-SNAPSHOT/maven-metadata-ossrh.xml is invalid: input contained no data

**Comment by martinsawicki** [comment]
probably due to a temporary network issue when publishing snapshots. See if you still run into this problem.
