### ISSUE TITLE
ReactiveCosmosTemplate SQL Injection Risk?

### ISSUE THREAD

**Issue by ihcnet** [Azure/azure-sdk-for-java#19553]
In the implementation of findById, String.format to build the query, https://github.com/Azure/azure-sdk-for-java/blob/3c5afa97be1619d39b0924c2d9c7e030d221b194/sdk/cosmos/azure-spring-data-cosmos/src/main/java/com/azure/spring/data/cosmos/core/ReactiveCosmosTemplate.java#L274 A parameterized query could be used instead to reduce the risk.

**Comment by kushagraThapar** [comment]
@ihcnet - thanks for creating this issue, I have fixed it in the PR.
