### ISSUE TITLE
[BUG] Container name can't be set using Spring SPEL

### ISSUE THREAD

**Issue by gauravkarnatak** [Azure/azure-sdk-for-java#19561]
**Describe the bug**
Not able to set container name using Spring SPEL, code below.

```
@Container(containerName = "${cosmos.container.name}")
public class AuditEvent {
}
```

***Exception or Stack Trace***
Add the exception log and stack trace if available

**To Reproduce**
Create Entity like below and provide "cosmos.container.name" property in Spring env vars. Save entity and it will fail with reason no container with name "${cosmos.container.name}".
```
@Container(containerName = "${cosmos.container.name}", autoCreateContainer = false)
public class Event {
}
```
***Code Snippet***
I see that CosmosEntityInformation is using ExpressionResolver to resolve expression which is not initialized correctly.

**Expected behavior**
Container name should be taken from env var configured in containerName property.

**Screenshots**

**Setup (please complete the following information):**
 - OS: MacOS
 - IDE : IntelliJ
 - Version of the Library used
       <dependency>
            <groupId>com.azure</groupId>
            <artifactId>azure-spring-data-cosmos</artifactId>
            <version>3.3.0</version>
        </dependency>

**Additional context**

**Information Checklist**
Kindly make sure that you have added all the following information above and checkoff the required fields otherwise we will treat the issuer as an incomplete report
- [ ] Bug Description Added
- [ ] Repro Steps Added
- [ ] Setup information Added

**Comment by kushagraThapar** [comment]
@gauravkarnatak - can you please show a sample code ?
Also, it would be good to try out this solution to see if adding the `@DependsOn` annotation solves the issue - 

https://github.com/microsoft/spring-data-cosmosdb/pull/390#issuecomment-598993207

**Comment by gauravkarnatak** [comment]
> @gauravkarnatak - can you please show a sample code ?
> Also, it would be good to try out this solution to see if adding the `@DependsOn` annotation solves the issue -
> 
> [microsoft/spring-data-cosmosdb#390 (comment)](https://github.com/microsoft/spring-data-cosmosdb/pull/390#issuecomment-598993207)

adding `@DependsOn` as mentioned in link works, thank you.
