### ISSUE TITLE
[FEATURE REQ] Auto Instrumented distinction between Completed and Dead-lettered ServiceBus proceed messages spans in ApplicationInsights

### ISSUE THREAD

**Issue by yutyang** [Azure/azure-sdk-for-java#19562]
**Is your feature request related to a problem? Please describe.**
Currently, using `azure-messaging-servicebus` sdk v7.X.X+ with [`azure-core-tracing-opentelemetry`](https://github.com/Azure/azure-sdk-for-java/tree/master/sdk/core/azure-core-tracing-opentelemetry#azure-tracing-opentelemetry-client-library-for-java) and [the app insights 3.0 agent](https://github.com/microsoft/ApplicationInsights-Java) as described in [this doc](https://docs.microsoft.com/en-us/azure/developer/java/sdk/tracing#enable-tracing-with-the-in-process-agent) enables auto instrumentation of `ServiceBus.message`, `ServiceBus.send` and `ServiceBus.process` to app insights. 

However, whether the processed message gets Dead-lettered or Completed, or Abandoned, the auto instrumented span is the same.

Example of an auto instrumented span for processed ServiceBus message:

Dependency span name: `ServiceBus.process` 

with the following custom dimensions:

 CustomDimensions key | CustomDimensions value
-- | --
az.namespace | Microsoft.ServiceBus
message_bus.destination | {topic name}/subscriptions/{subscription name}
x-opt-enqueued-time | {enqueue time}

**Describe the solution you'd like**
All different message processing types (Completed, Dead-lettered, Abandoned, Deferred etc.) should be surfaced differently, ideally using a different span name. This would make the experience consistent with [the auto-instrumented specs of the dotnet service bus SDK](https://docs.microsoft.com/en-us/azure/service-bus-messaging/service-bus-end-to-end-tracing?tabs=net-standard-sdk-2#instrumented-operations).

E.g. Dependency span name: `ServiceBus.complete`/`ServiceBus.deadLettered`

**Describe alternatives you've considered**
The type of processing could also be in the CustomDimensions
E.g.
 CustomDimensions key | CustomDimensions value
-- | --
az.namespace | Microsoft.ServiceBus
**process_type** | **{Completed}/{Dead-lettered} etc**
message_bus.destination | {topic name}/subscriptions/{subscription name}
x-opt-enqueued-time | {enqueue time}

**Comment by ki1729** [comment]
@yutyang We are looking into adding this change, I'll get back to you on the timeline as soon as we have some dates around this one

**Comment by lmolkova** [comment]
Fixed in #30508
