### ISSUE TITLE
[QUERY] [Cosmos DB bulk operation] Different behaviors between "createManualThroughput" and "createAutoscaledThroughput"

### ISSUE THREAD

**Issue by 04diiguyi** [Azure/azure-sdk-for-java#19586]
**Query/Question**

Version: Azure SDK for Java 4.9.0

When I create Cosmos container with "createManualThroughput" and "createAutoscaledThroughput" and use bulk operation to insert/delete items, the behaviors of the function are different.

If we use **createManualThroughput**, if the number of operations is larger than the maximal throughput, the Cosmos DB client will do a certain number of internal retries to handle 209 throttling errors. However, if errors still exist, our app would receive responses of those operations failures. However, if we use **createAutoscaledThroughput** with the same maximal throughput, we will not receive those failures since somehow the operations would be done successfully. 

***Why is this not a Bug or a feature Request?***
A clear explanation of why is this not a bug or a feature request?

I do not know the underlying design, so not sure whether it is a purposely designed feature or a bug.

The different code to create container, where the "getMaxThroughput" is a parameter I used to test the performance:

 if(spikeConfig.getIsAutoScale()) {
      throughputProperties = ThroughputProperties.createAutoscaledThroughput(spikeConfig.getMaxThroughput());
    }
    else {
      throughputProperties = ThroughputProperties.createManualThroughput(spikeConfig.getMaxThroughput());
    }

**Setup (please complete the following information if applicable):**
 - OS: MacOS
 - IDE : IntelliJ
 - Version of the Library used: 4.9.0

**Comment by kushagraThapar** [comment]
@04diiguyi - This is because of the fact that if you choose autoscale throughput, the throughput is automatically adjusted to account for the work that you are trying to do (in your case - bulk operations). It is not a bug, but rather purposely designed this way to work. 

Please read more about autoscale here - https://docs.microsoft.com/en-us/azure/cosmos-db/provision-throughput-autoscale
Also, please go through these FAQs - https://docs.microsoft.com/en-us/azure/cosmos-db/autoscale-faq

**Comment by 04diiguyi** [comment]
Hi @kushagraThapar , thanks for the detailed information. I used the same maximum throughput for both autoscale and manual throughput, so the maximum throughput should be the same. In addition, the numbers of the requests in the code are also the same, but the results are different, "manual throughput" gives throttling exceptions while the other does not. Can you give me a little bit of insight for it? Thanks.
