### ISSUE TITLE
How to enable Guest Os Diagnostic using java sdk

### ISSUE THREAD

**Issue by rishi-anand** [Azure/azure-sdk-for-java#1958]
When I enable bootDiagnostic while creating virtual machine then by default boot diagnostic is enabled and guest os diagnostic is not enabled.

`virtualMachineCreatable.withBootDiagnostics(vmInfo.diagnosticsStorageAccount());`

How can I enable both **_boot_** and **_guest os diagnostic_**?

**Comment by rishi-anand** [comment]
![image](https://user-images.githubusercontent.com/9067666/32013602-3d807cb2-b9d9-11e7-9064-e46bb2508a29.png)

**Comment by anuchandy** [comment]
For "OS Diagnostics" refer this https://github.com/Azure/azure-sdk-for-java/blob/952c1da90c98116d62b902b87f13ece224d728cf/azure-mgmt-compute/src/test/java/com/microsoft/azure/management/compute/VirtualMachineExtensionOperationsTests.java#L36

**Comment by anuchandy** [comment]
@rishi-anand also refer this discussion https://github.com/Azure/azure-sdk-for-java/issues/1836, there is an extensive discussion on enabling OS diagnostics..

**Comment by rishi-anand** [comment]
Thanks a lot @anuchandy 👍

**Comment by anuchandy** [comment]
@rishi-anand seems you are unblocked.. closing this issue.
