### ISSUE TITLE
[azure-spring-boot-starter-keyvault-secrets] Does not activate running in Docker

### ISSUE THREAD

**Issue by RomainWilbert** [Azure/azure-sdk-for-java#19583]
Hi ! 

I have an Spring boot app which is running fine with azure-spring-boot-starter-keyvault-secrets (i can retrieve values from keyvault).

When i run the app in Docker, the library does not do anything...i have correct properties values in configuration, but the property source is not added on startup...

Moreover i would like to see some logs from the lib, but I can see anything even configuring logback.xml as following : 
`<logger name="com.azure.security.keyvault.secrets" level="DEBUG">`

**Comment by saragluna** [comment]
Hi @RomainWilbert, could you please provide a sample project for us to reproduce this issue?

**Comment by yiliuTo** [comment]
Closing this issure because no response from the customer. If you have any problems, please open again.
