### ISSUE TITLE
How to delete boot diagnostic logs from sdk

### ISSUE THREAD

**Issue by rishi-anand** [Azure/azure-sdk-for-java#1960]
`public CloudBlobContainer getContainerReference(final String containerName) `

SInce bootdiagnostic container has some random string at the end after VM name. So, how to figure out appropriate container and then delete it.

Format of diagnostic profile name:
bootdiagnostics-cqjw1cc5b-5adda9f4-fb26-49c4-975a-34ae9b31d97f

Due to this, no any diagnostic profile gets deleted and it remains as it is even if virtual machine is deleted.

**Comment by anuchandy** [comment]
looks like the naming convention that CRP follow for diagnostics container is `bootdiagnostics-{VMNAME}-{guid}`, unfortunately service does not allow consumers to configure the name for the log container. Only option we have is - from VM boot diagnostics settings locate the VM, enumerate containers and find the one with the name that matches with above regex.

**Comment by rishi-anand** [comment]
I see some special character is also not honoured in VMName. If VMname is **abcd-123456** then bootdiagnostic profile name would be
**bootdiagnostics-abcd123456-123456789-fb26-49c4-975a-34ae9b31d97f**

How to handle this case. As of now I am trying to remove all special character from VMname and get the substring of first 9 chars and also remove all special character in boot diagnostic name and then search for the VMname in diagnostic name.

**Comment by anuchandy** [comment]
@rishi-anand this is a question for compute service team. Tagging service team member here Nitin @nibhat, can you please respond? the question is:

CRP is deciding the name of the container that stores boot diagnostics for a VM. Initially we thought the pattern for the name is: bootdiagnostics-{VMNAME}-{RANDOM-GUID}, but it seems CRP also removes some characters from the actual VM NAME while generating the container name. Customer wanted to programmatically locate the container and delete it. What is the logic CRP uses here to generate the container name?

**Comment by nibhat** [comment]
The VMName is truncated as the container name has a 3-24 char limit.
The random GUID is the  VM’s VMId, you could leverage that

**Comment by nibhat** [comment]
The VMName is truncated as the container name has a 3-63 char limit.
The random GUID happens to be VM’s VMId, you can leverage that.

**Comment by anuchandy** [comment]
service team provided logic to derive the container name of diagnostics log, closing this.
