### ISSUE TITLE
Add unit testing guideline for java clients using azure servicebus library 

### ISSUE THREAD

**Issue by michaelegner** [Azure/azure-sdk-for-java#19609]
**Is your feature request related to a problem? Please describe.**
We are currently migrating to the new azure servicebus library version 7.0.2 and are having trouble writing proper unit tests especially for the receiver side of the implementation. 

**Describe the solution you'd like**
As we found in the samples of the library some unit tests for the implementation of the library, we could not find any tests from a client point of view. Could you please guide us where to find client centric unit tests, or add client unit tests if they are missing.
Without proper unit testing support we cannot successfully finish the migration to the new version of the library.

**Describe alternatives you've considered**
Good support of unit testing is a must-have for any sdk.

**Additional context**
Java 11
Spring Boot 2.3.6.RELEASE
Azure Service Bus 7.0.2

**Information Checklist**
Kindly make sure that you have added all the following information above and checkoff the required fields otherwise we will treat the issuer as an incomplete report
- [x] Description Added
- [x] Expected solution specified

**Comment by hemanttanwar** [comment]
@michaelegner Thank you for the query. The samples in the library shows how a client will use our library. The test in the samples are not meant for Unit Testing. If you can provide me some scenario for your use case, that will help us to think how we take this request and what kind of unit test support we can provide.

**Comment by michaelegner** [comment]
Here is a sample implementation from one of our use cases. Could you please guide us how to best unit test the logic inside the `processMessage()` method, mocking away all dependencies. Our focus here is not to implement an integration test actually sending / receiving messages to / from azure servicebus, but to unit test the functionality of processing the received message. 

`public class SampleMessageReceiver {

    private ServiceBusProcessorClient processorClient;
    private final ObjectMapper objectMapper;
    private final Tracer tracer;
    private final SampleService sampleService;

    public SampleMessageReceiver(@Value("${sample_queue}") String queueName, MessagingConfiguration messagingConfiguration, Tracer tracer, SampleService sampleService) {
        this.objectMapper = new ObjectMapper();
        this.tracer = tracer;
        this.sampleService = sampleService;
        this.processorClient = initProcessorClient(messagingConfiguration, queueName);
    }

    @EventListener(ApplicationReadyEvent.class)
    public void receiveReplyMessage() {
        processorClient.start();
    }

    public ServiceBusProcessorClient initProcessorClient(MessagingConfiguration messagingConfiguration, String queueName) {
        return new ServiceBusClientBuilder()
            .connectionString(messagingConfiguration.getConnectionString())
            .processor()
            .queueName(queueName)
            .maxConcurrentCalls(messagingConfiguration.getMaxConcurrentCalls())
            .receiveMode(ServiceBusReceiveMode.PEEK_LOCK)
            .processMessage(processMessage())
            .processError(processError())
            .buildProcessorClient();
    }

    public Consumer<ServiceBusReceivedMessageContext> processMessage() {
        return messageContext -> {
            Span span = createTracingProperties(messageContext.getMessage(), "sampleSpan", tracer);
            try (SpanInScope ws = tracer.withSpanInScope(span.start())) {
                SampleDto sampleDto = getMessageContent(messageContext, SampleDto.class);
                sampleService.someProcessingLogic(sampleDto);
                log.debug("Message content '{}'", sampleDto.toString());
            } catch (RuntimeException | IOException e) {
                messageContext.deadLetter();
                log.error("Sending message '{}' to the dead letter queue", messageContext.getMessage().getMessageId(), e);
            } finally {
                span.finish();
            }
        };
    }

    public Consumer<ServiceBusErrorContext> processError() {
        return errorContext -> {
            log.error(errorContext.getEntityPath() + " encountered exception:" + errorContext.getException().getMessage());
            throw new OrderException(errorContext.getEntityPath() + " encountered exception:" + errorContext.getException().getMessage());
        };
    }

    private <T> T getMessageContent(ServiceBusReceivedMessageContext messageContext, Class<T> valueType) {
        return messageContext.getMessage().getBody().toObject(TypeReference.createInstance(valueType));
    }

    private Span createTracingProperties(ServiceBusReceivedMessage message, String spanName, Tracer tracer) {
        Map<String, Object> messageProperties = message.getApplicationProperties();
        if (null == messageProperties || messageProperties.isEmpty()) {
            return tracer.nextSpan();
        }

        String traceId = (String) messageProperties.get(TRACE_ID);
        if (isValid(traceId)) {
            return tracer.nextSpan(
                TraceContextOrSamplingFlags.newBuilder(
                    TraceIdContext.newBuilder()
                        .traceId(Long.parseLong(traceId))
                        .build())
                    .build())
                .name(spanName);
        } else {
            return tracer.nextSpan();
        }
    }

    private boolean isValid(String strNum) {
        return StringUtils.isNumeric(strNum);
    }
}
`

**Comment by michaelegner** [comment]
Or to put in one sentence; how can we unit test the code that gets executed in the processMethod() of the ServiceBusClientBuilder?

**Comment by ngara78** [comment]
@hemanttanwar while trying to unit test a receiver processMessage function:
```
    protected Consumer<ServiceBusReceivedMessageContext> processMessage() {
    ...... whatever logic
    }
```
We could not find a way to create a test ServiceBusReceivedMessageContext with a message body of our choice.

**Comment by michaelegner** [comment]
@hemanttanwar any update on this?

**Comment by hemanttanwar** [comment]
@michaelegner Sorry for the delay. Let me try to answer this.

The best way to just test your business logic is not to unit test how  Processo`ServiceBusProcessorClient` deliver messages.  You can assume that service bus library take care of this.

And you can focus on business logic of your application . For example  lets say you have `MessageProcessor`  which implement business logic and process messages.

// Application code
       MessageProcessor   messageProcessor =  new MessageProcessor();
        ServiceBusProcessorClient  processor =  new ServiceBusClientBuilder()
            .connectionString(connectionString)
            .processor()
            .queueName(queueName)
            .disableAutoComplete()
            .receiveMode(ServiceBusReceiveMode.PEEK_LOCK)
            .processMessage(messageProcessor::processMessage)
            .processError(messageProcessor::processError)
            .buildProcessorClient();

 /** Your business logic to process messages.*/
    class MessageProcessor {
        ArrayList<ServiceBusReceivedMessageContext> messages =new ArrayList<>();
        void processMessage(ServiceBusReceivedMessageContext messageContext) {
           // Implement your business logic here. 
            messages.add(messageContext);
            messageContext.complete();
        }

        void processError(ServiceBusErrorContext errorContext) {
            System.out.println("processError: " + errorContext.getException().getMessage());
        }
        
        public ArrayList<ServiceBusReceivedMessageContext> getReceivedMessage() {
            return messages;
        }
    }

This is how you will focus on unit testing `MessageProcessor ` . 
You can mock `ServiceBusReceivedMessageContext` and `ServiceBusReceivedMessage`.

public MessageProcessorTest 
    @Test
    public void testProcessMessage() {
        //Arrange
        final MessageProcessor messageProcessor = new MessageProcessor();
        final ServiceBusReceivedMessageContext messageContext1 = mock(ServiceBusReceivedMessageContext.class);
        final ServiceBusReceivedMessage receivedMessage1 = mock(ServiceBusReceivedMessage.class);
        final String payload = "order-1";

        when(messageContext1.getMessage()).thenReturn(receivedMessage1);
        doNothing().when(messageContext1).complete();
        when(receivedMessage1.getBody()).thenReturn(BinaryData.fromString(payload));
        when(receivedMessage1.getSequenceNumber()).thenReturn(1L);

        // Act
        messageProcessor.processMessage(messageContext1);

        // Assert
        Assertions.assertEquals(1, messageProcessor.getReceivedMessage().size());
        Assertions.assertEquals(payload, messageProcessor.getReceivedMessage().get(0).getMessage().getBody().toString());
       // Add more asserts here 
    }
}

**Comment by michaelegner** [comment]
@hemanttanwar many thanks for your detailed feedback. We will follow your advice in implementing the unit tests for the message receivers.
