### ISSUE TITLE
NullPointerException in TransparentDataEncryptionImpl.<init> after calling getTransparentDataEncryption in a SqlDatabase returned from databases().list()

### ISSUE THREAD

**Issue by oxisto** [Azure/azure-sdk-for-java#1961]
Accessing the TDE of a SqlDatabase returned from databases.list() leads to a NullPointerException:

```
Caused by: java.lang.NullPointerException
	at com.microsoft.azure.management.sql.implementation.TransparentDataEncryptionImpl.<init>(TransparentDataEncryptionImpl.java:32)
	at com.microsoft.azure.management.sql.implementation.SqlDatabaseImpl.getTransparentDataEncryption(SqlDatabaseImpl.java:193)
```

Example code:
```
for (SqlServer server : servers) {
  for (SqlDatabase db : server.databases().list()) {
    TransparentDataEncryption tde = db.getTransparentDataEncryption();
  }
}
```

Calling the function on a SqlDatabase that was directly queried using databases().get() works without issues.

**Comment by oxisto** [comment]
Correction: It seems to be the problem of the "master" db. databases.list() will fetch all dbs, including the master db. Calling db.getTransparentDataEncryption() on the master db leads to the NPE, the other dbs work fine.

**Comment by yaohaizh** [comment]
@ChenTanyi , could you help take a look at this issue?

**Comment by ChenTanyi** [comment]
I cannot reproduce the problem. And I check for the current implementation with 2 years ago one. I think it is been fixed.
1.3.0 (doesn't check null):
https://github.com/Azure/azure-libraries-for-java/blob/e1ecfd205ce5e935b0b77a7864a77a25a37e690b/azure-mgmt-sql/src/main/java/com/microsoft/azure/management/sql/implementation/SqlDatabaseImpl.java#L190

1.31.0 (check with null):
https://github.com/Azure/azure-libraries-for-java/blob/d9d097aa2b482e85bd140c7728224f1b587b3ff0/azure-mgmt-sql/src/main/java/com/microsoft/azure/management/sql/implementation/SqlDatabaseImpl.java#L506

@oxisto If there is still problem, please reopen it again. Thanks!
