### ISSUE TITLE
Service Bus - How to count the number of deferred messages where sequenceNumber is not known?

### ISSUE THREAD

**Issue by rad-app** [Azure/azure-sdk-for-java#19616]
Hi,
I am using latest azure sdk azure-core version 1.13.0 and azure-messaging-servicebus version 7.0.2. In my project I have a requirement to identify deferred messages in a queue/topic, and then receive these messages. In the latest SDK there is method of receiveDeferredMessage(long sequenceNumber). But in my project we are looking for a way to identify the number of deferred messages where sequenceNumber is not known, and then receive each message and repair it.
Please let me know how this can be achieved.

**Comment by joshfree** [comment]
@hemanttanwar can you please follow up with @rad-app

**Comment by hemanttanwar** [comment]
@rad-app  I am looking into this and will update you soon.

**Comment by hemanttanwar** [comment]
Hello @rad-app, You can call receiver.peekMessages() API which will return deferred messages along with regular messages. But you can not tell that a peek message  is deferred or not. This feature is not provided by Service Bus as of now. There is a feature request for this.    

Until then, as a work around (it is not perfect), you can sent a property when you defer the message and check for that property when you peek the message.

```java
                    Map<String, Object> prop = new HashMap<>();
                    prop.put("action", "deferred");
                    DeferOptions options =  new DeferOptions().setPropertiesToModify(prop);
                    receiver.defer(message, options);
```  
Sample for how to peek messages : https://github.com/Azure/azure-sdk-for-java/blob/master/sdk/servicebus/azure-messaging-servicebus/src/samples/java/com/azure/messaging/servicebus/PeekMessageAsyncSample.java#L58

**Comment by rad-app** [comment]
Hello @hemanttanwar,
The above workaround works well when the message is deferred  explicitly. When messages are submitted in batch (like millions) through AMQP protocol using java SDK, then some of the messages end up as deferred message state. There is no proper exception to know which messages are deferred, and only way to find out is to browse each and every message from Service Bus Explorer and find out the sequenceID and state. It would be great if this feature is implemented in the Azure SDK for Java.

**Comment by hemanttanwar** [comment]
@axisc Is this feature service bus can provide ?

**Comment by axisc** [comment]
@rad-app Not sure how messages would be deferred unless you explicitly defer them. That is the only way. How are messages being deferred in the case you mentioned?

**Comment by rad-app** [comment]
@axisc During the load testing phase messages are submitted in bulk using AMQP protocol. While submitting the messages if message is of type other than the type defined in content-type than that message gets deferred and there is no exception thrown  or any error propagated.Below is the code where we could generate a deferred message in a given subscription - 
byte[] invalidPayload = new byte[5000]; // Add two for malformed UTF8
        invalidPayload[0] = (byte) 0b11000111; // The prefix for a two-byte UTF8 encoding
        invalidPayload[1] = (byte) 0b00110000; // An invalid next byte, as encoding must be 0b10xxxxxx

        Section invalidData = new Data(new Binary(invalidPayload));

        TextMessage textMessage = session.createTextMessage();

        AmqpJmsMessageFacade amqpJmsMessageFacade = (AmqpJmsMessageFacade) ((JmsMessage) textMessage).getFacade();
        amqpJmsMessageFacade.setContentType(Symbol.valueOf("text/plain;charset=utf-8"));
        amqpJmsMessageFacade.setProperty("Status", "Active");
        Method setBody = amqpJmsMessageFacade.getClass().getSuperclass().getDeclaredMethod("setBody", Section.class);
        setBody.setAccessible(true);

        setBody.invoke(amqpJmsMessageFacade, invalidData);
       messageProducer.send(textMessage);

**Comment by axisc** [comment]
@rad-app  this is unexpected. Unless the receiver of a message explicitly defers the message, it should not get deferred (irrespective of the content type).

Could you check to ensure that there is no receiver that is calling defer. If that is not the case, please open a support ticket so that we can investigate internally (with the backend).

**Comment by ramya-rao-a** [comment]
We will be using https://github.com/Azure/azure-sdk-for-java/issues/25217 to track the feature to add the state (deferred vs active vs scheduled) to the message.

@yvgopal Do you want to use this issue to track the unexpected behavior @axisc noticed or shall we move to the [azure-service-bus](https://github.com/Azure/azure-service-bus) repo that is used to track issues/feature-requests with the service?

**Comment by yvgopal** [comment]
It is not just unexpected, but also unlikely. Service Bus doesn't defer messages unless the client explicitly defers a message. May be this line
`amqpJmsMessageFacade.setProperty("Status", "Active");`
is pushing "Deferre" as status. Even then I don't know why a message is deferred automatically.

@rad-app Could you reproduce this? If you can reproduce it, please give me the timestamp, namespace, queue or topic/subscription where it is reproduced.
