### ISSUE TITLE
Create a Deprecation Policy

### ISSUE THREAD

**Issue by alzimmermsft** [Azure/azure-sdk-for-java#19617]
Create a markdown file which outlines our API deprecation policy, starting with the Core libraries and potentially expanded from there.

**Comment by alzimmermsft** [comment]
@ki1729 I'm going to assign this to you since you've been doing research in this area

**Comment by ki1729** [comment]
The latest update is that our current deprecation guidelines hold. https://github.com/Azure/azure-sdk-for-java/wiki/Deprecation
