### ISSUE TITLE
Choose proper partitioning strategy for Query

### ISSUE THREAD

**Issue by moderakh** [Azure/azure-sdk-for-java#19613]
how do we want to deal with the fact that filters might be pushed down? My rough idea was if no filters are pushed down, use default partitioning strategy -(storage based) but use restrictive if any filters are pushed down./ bot as the default if the customer didn't specify in config

https://github.com/Azure/azure-sdk-for-java/pull/19569#discussion_r586759253

**Comment by kushagraThapar** [comment]
no longer valid, closing it.
