### ISSUE TITLE
No detailed error message when VM creation fails

### ISSUE THREAD

**Issue by henrydavidge** [Azure/azure-sdk-for-java#1962]
I'm using the SDK to programmatically launch VMs and often encounter failures with the vague error message "Async operation failed with provisioning state: Failed". As you can see from the attached screenshot, there's no more information in the `CloudException`.
![screen shot 2017-10-27 at 1 06 42 pm](https://user-images.githubusercontent.com/1473365/32123081-bc9571c6-bb17-11e7-961e-1b030bd88bc9.png)

 If I check the "Activity log" for the resource group in which I attempted to launch the VM, I can find a more informative error code and message in the JSON blob:

```
    "properties": {
        "statusMessage": "{\"status\":\"Failed\",\"error\":{\"code\":\"ResourceOperationFailure\",\"message\":\"The resource operation completed with terminal provisioning state 'Failed'.\",\"details\":[{\"code\":\"AllocationFailed\",\"message\":\"Allocation failed. Please try reducing the VM size or number of VMs, retry later, or try deploying to a different Availability Set or different Azure location.\"}]}}"
    },
```

Simplified code snippet:
```java
client.virtualMachines().define(vmName)
 // fill in a a bunch of options
.create()
```

It would be great if the `CloudException` could contain the more detailed error report so that we don't need to cross reference the portal in case of failures.

**Comment by henrydavidge** [comment]
I'm currently using version 1.0.0. If this issue has been addressed in a more recent update, I apologize. I will also try updating.

**Comment by henrydavidge** [comment]
Ok, it looks like version 1.3.0 includes the error code and message in `CloudException#body`. I'll close this issue.

**Comment by romr-of-dt** [comment]
An alike problem. _Azure Java SDK 1.41.0_ did not offer the error details for a provisioning error. `CloudException#body#details` folded no inner errors and _Activity Log_ reported certain.
```
[2021-06-21;12:32:15.576]  Executing CREATE operation for cloud resource... failed.
  java.util.concurrent.CompletionException: ...CannotExecuteCloudOperationException:
    Cannot create resource. Async operation failed with provisioning state: Failed: []
    ...
    Caused by: com.microsoft.azure.CloudException: Async operation failed with provisioning state: Failed
    at com.microsoft.azure.PollingState.throwCloudExceptionIfInFailedState(PollingState.java:541)
    at com.microsoft.azure.AzureClient$6.call(AzureClient.java:215)
    at com.microsoft.azure.AzureClient$6.call(AzureClient.java:212)
    at rx.internal.operators.OnSubscribeMap$MapSubscriber.onNext(OnSubscribeMap.java:69)
    ...
```
```
"properties": {
  "statusMessage": "{
    \"status\":\"Failed\",
    \"error\":{
      \"code\":\"ResourceOperationFailure\",
      \"message\":\"VM... did not start in the allotted time. The VM may still start successfully. Please check the power state later..\",
      \"details\":[{
          \"code\":\"VMStartTimedOut\",
          \"message\":\"VM status blob is found but not yet populated.\"
        }]
    }
  }",
```
I have no idea how to reproduce the issue...
