### ISSUE TITLE
Application gateway http to https redirection.

### ISSUE THREAD

**Issue by safrazhanas** [Azure/azure-sdk-for-java#1963]
I'm evaluating appliction gateway http to https redirection using 1.3.1-SNAPSHOT version. 

Since the java documentation is not ready, i've referred powershell documentation (https://docs.microsoft.com/en-us/azure/application-gateway/application-gateway-configure-redirect-powershell)

I understood followings needs to be done. 

1. creating http listener (i already have corresponding https listener created)
2. create ApplicationGatewayRedirectConfiguration
3. create ApplicationGatewayRequestRoutingRule
4. update applicationgateway with above created steps

I wrote a sample code , steps 2 and 3 were not created. i have verified the same with the portal. 

my question is, when does this feature will be ready?

**Comment by martinsawicki** [comment]
"Redirects" is done for v1.4, so if you see it in a recent 1.3.1 snapshot, it's already implemented there, 
We'd need to see a specific repro steps to see what you are doing, so pls provide reproducible steps (i.e. code) that show a problem.
(existing tests referencing redirects are passing fine. e.g.: https://github.com/Azure/azure-sdk-for-java/blob/master/azure/src/test/java/com/microsoft/azure/management/TestApplicationGateway.java - look for "redirect")

**Comment by praries880** [comment]
@safrazhanas Is the issue still happening for you?

**Comment by vhvb1989** [comment]
Hello @safrazhanas

Do you still need help on this? Let me know and I would be happy to help.

Note: As part of repository cleaning effort, this issue will be closed by **Nov 11** if no response is received from submitter and/or not further action is required.
