### ISSUE TITLE
azure-client-runtime using SNAPSHOT version

### ISSUE THREAD

**Issue by vincentdo** [Azure/azure-sdk-for-java#1964]
``` xml
<dependency>
  <groupId>com.microsoft.azure</groupId>
  <artifactId>azure-client-runtime</artifactId>
  <version>[1.1.0,2.0.0)</version>
</dependency>
```

Shouldn't this be pinned to a stable version. This seems like a bad way to introduce sneaky bug by including unstable dependencies... 😅

**Comment by martinsawicki** [comment]
yeah, we're getting rid of the range notation in v1.4.
