### ISSUE TITLE
Get powerstate for ARM VM, always returns Empty/null with Azure java sdk version -1.3.0

### ISSUE THREAD

**Issue by SriHarsha001** [Azure/azure-sdk-for-java#1965]
Get powerstate for ARM VM, always returns Empty/null with Azure java sdk version -1.3.0. 
The same call works fine with Azure java sdk version -1.0.0.
Interface used : com.microsoft.azure.management.compute.VirtualMachine

**Comment by anuchandy** [comment]
Can you invoke `virtualMachine.refreshInstanceView()` and check the return value  `VirtualMachineInstanceView`? This should contain powerState as one of the status. You can try below code:

```java
VirtualMachineInstanceView instanceView = virtualMachine.refreshInstanceView();
if (instanceView == null) {
   System.out.println("Expected instance view is null");
} else if (virtualMachineInstanceView.statuses() == null) {
   System.out.println("Expected instance view status is null");
} else {
    for (InstanceViewStatus status : virtualMachineInstanceView.statuses()) {
        if (status.code() != null) {
            System.out.println(status.code());
        }
    }
}
```

Also please share the network log of the call `virtualMachine.refreshInstanceView()`, logging can be enabled while creating Azure instance:

```java
 Azure azure = Azure.configure()
    .withLogLevel(LogLevel.BODY_AND_HEADERS)
    .authenticate(credFile)
    .withDefaultSubscription();
```

**Comment by SriHarsha001** [comment]
This way we are able to get powerstate. It needs more parsing and secondary call to get instance view. 
Is there a reason why VirtualMachine.powerState() returns a null?  Is this method deprecated ?

**Comment by anuchandy** [comment]
internally `VirtualMachine.powerState() ` calls `virtualMachine.refreshInstanceView()` to retrieve the powerState, so if powerState() is returning null then that means mostly instance view is missing powerState status in sometime. To avoid parsing you can use :

`PowerState PowerState.fromInstanceView(virtualMachine.refreshInstanceView())`

Mean time I can try to repro it.

**Comment by praries880** [comment]
@anuchandy did you get a chance to investigate the issue further?

**Comment by yaohaizh** [comment]
Close this as this is design behavior of VM.
