### ISSUE TITLE
EventGrid Post-GA follow-up

### ISSUE THREAD

**Issue by YijunXieMS** [Azure/azure-sdk-for-java#19679]
<This list will expand gradually>
1. "Long term, for performance reasons, it may be cheaper to have a large if/else if block with the error messages constructed at startup."  https://github.com/Azure/azure-sdk-for-java/pull/19615#discussion_r588611816
2. Automate system events mapping.

**Comment by alzimmermsft** [comment]
Closing as this is for an error case code path where performance requirements aren't as critical. The overhead called out is trivial and shouldn't be worried about eagerly.
