### ISSUE TITLE
Adding other Gov cloud regions. 

### ISSUE THREAD

**Issue by nwarriorch** [Azure/azure-sdk-for-java#1969]
It looks like only GOV_US_VIRGINIA, GOV_US_IOWA are currently present. Is there a timeline for when support for other Gov cloud regions will be provided. 

Can I just add other regions to the source code? will that work?

**Comment by nwarriorch** [comment]
Any update on this ? are you guys planning on adding any new regions in the next release?

**Comment by jianghaolu** [comment]
For internal - 
You can find the regions here
https://azure.microsoft.com/en-us/regions/services/

Select regions -> US Government
