### ISSUE TITLE
[BUG] Serialization issue with dates, JacksonJsonSerializer with custom ObjectMapper not recognized

### ISSUE THREAD

**Issue by michaelegner** [Azure/azure-sdk-for-java#19717]
**Describe the bug**
While migrating to latest version 7.0.2 of azure service bus we encountered the following issue: when using azure-core-serializer-json-jackson: 1.1.2 for serialization of DTO objects to JSON all OffsetDateTime dates are serialized to timestamps. We tried to inject our own version of JacksonJsonSerializer with a modified ObjectMapper where WRITE_DATES_AS_TIMESTAMPS is disabled, but this custom JacksonJsonSerializer was not recognized by Azure SDK and default ObjectMapper was still used.

***Exception or Stack Trace***
n.a.

**To Reproduce**
- Add  azure-messaging-servicebus:7.0.2 and azure-core-serializer-json-jackson:1.1.2 to maven pom.xml
- Create a configuration class to create a JacksonJsonSerializer bean that uses a modifed ObjectMapper that doesn't write dates as timestamps
- Serialize a DTO object that contains a OffsetDateTime as property
- Custom JacksonJsonSerializer bean from code snippet below is not recognized or used and dates are serialized as timestamps

***Code Snippet***
`@Configuration
public class JacksonConfiguration {

    private final Jackson2ObjectMapperBuilder objectMapperBuilder;

    public JacksonConfiguration(Jackson2ObjectMapperBuilder objectMapperBuilder) {
        this.objectMapperBuilder = objectMapperBuilder;
    }
    @Bean
    public ObjectMapper objectMapper() {

        ObjectMapper objectMapper = objectMapperBuilder.createXmlMapper(false).build();
        objectMapper.registerModule(new Jdk8Module());
        objectMapper.registerModule(new JavaTimeModule());
        objectMapper.disable(SerializationFeature.WRITE_DATES_AS_TIMESTAMPS);
        return objectMapper;
    } 
 @Bean
    public JacksonJsonSerializer jacksonJsonSerializer() {
        JacksonJsonSerializerBuilder builder = new JacksonJsonSerializerBuilder();
        builder.serializer(this.objectMapper());
        return builder
            .build();
    }`

**Expected behavior**
JacksonJsonSerializer bean with custom Object Mapper is used, dates are not serialized as timestamps  

**Screenshots**
n.a.

**Setup (please complete the following information):**
 - OS: Windows, Linux
 - IDE : IntelliJ
 - Java 11, Spring Boot 2.3
 - azure-messaging-servicebus: 7.0.2
 - azure-core-serializer-json-jackson: 1.1.2

**Additional context**
n.a.

**Information Checklist**
Kindly make sure that you have added all the following information above and checkoff the required fields otherwise we will treat the issuer as an incomplete report
- [x] Bug Description Added
- [x] Repro Steps Added
- [x] Setup information Added

**Comment by michaelegner** [comment]
This issue is currently blocking our migration to the new azure service bus library. We had to partly rollback our implemenation because of this.

**Comment by joshfree** [comment]
@hemanttanwar can you please investigate this for @michaelegner?

/cc @alzimmermsft

**Comment by hemanttanwar** [comment]
@michaelegner I am looking into this and will update  you.

**Comment by hemanttanwar** [comment]
I wrote sample application which send message to Service bus and serialize `Order` object into json.

Here is custom serializer.
https://github.com/hemanttanwar/java.coffee.order/blob/main/src/main/java/com/azure/sample/messaging/order/config/ServiceBusConfiguration.java#L41

Controller sending message to Service bus using custom serializer: 

https://github.com/hemanttanwar/java.coffee.order/blob/main/src/main/java/com/azure/sample/messaging/order/controller/CoffeeShopOrderController.java#L51

This field `OffsetDateTime orderDateTime` is written as numeric date time. The message in queue look like this.

{
  "orderDetail": "order details here",
  "orderDateTime": 1615931932.8341477
}

**Comment by michaelegner** [comment]
@hemanttanwar thanks for your feedback. We will have a look at the example that you provided and come back to you asap.

**Comment by michaelegner** [comment]
@hemanttanwar we could solve the serialization issue with help of the example that you provided. 

In order to use the custom jacksonJsonSerializer we switched to BinaryData as message payload. 
With this the dates were correctly formatted.

```
    public ServiceBusMessage buildServiceBusMessageFor(Object entity) {
        BinaryData payload = BinaryData.fromObject(entity, jacksonJsonSerializer);
        return new ServiceBusMessage(payload);
    }

```
For continuing the migration to the new service bus library it would be extremely helpful, if you could guide us to solve the issue we are having with unit testing the `processMessage() ` method of the receiver implementation. See https://github.com/Azure/azure-sdk-for-java/issues/19609 for further details.

Many thanks for your support.

**Comment by hemanttanwar** [comment]
@michaelegner Thank  you. I will close this issue
I will get to unit test question .
