### ISSUE TITLE
[BUG] telemetry.instrumentationKey is not set in azure-spring-boot

### ISSUE THREAD

**Issue by totakura** [Azure/azure-sdk-for-java#19719]
**Describe the bug**
`telemetry.instrumentationKey` is not set in azure-spring-boot-3.2.0.  It is left to have the value `@telemetry.instrumentationKey@` in [telemetry.config](https://github.com/Azure/azure-sdk-for-java/blob/07574abb47a3762117c5121ca7e0afac3b0514ef/sdk/spring/azure-spring-boot/src/main/resources/telemetry.config) .  I guess your build system is not replacing it with your instrumentation key.

This is causing errors when using azure-spring-boot-starter-active-directory.

```
...
17:12:12.968 INFO  [  restartedMain]         o.a.c.c.C.[.[.[/] - Initializing Spring embedded WebApplicationContext
17:12:12.969 INFO  [  restartedMain] bServerApplicationContext - Root WebApplicationContext: initialization completed in 634 ms
17:12:13.306 WARN  [  restartedMain]   c.a.s.t.TelemetrySender - Failed to exchange telemetry request, 400 Invalid instrumentation key: [{"itemsReceived":1,"itemsAccepted":0,"errors":[{"index":0,"statusCode":400,"message":"Invalid instrumentation key"}]}].
17:12:13.393 WARN  [  restartedMain]   c.a.s.t.TelemetrySender - Failed to exchange telemetry request, 400 Invalid instrumentation key: [{"itemsReceived":1,"itemsAccepted":0,"errors":[{"index":0,"statusCode":400,"message":"Invalid instrumentation key"}]}].
17:12:13.456 WARN  [  restartedMain]   c.a.s.t.TelemetrySender - Failed to exchange telemetry request, 400 Invalid instrumentation key: [{"itemsReceived":1,"itemsAccepted":0,"errors":[{"index":0,"statusCode":400,"message":"Invalid instrumentation key"}]}].
17:12:13.456 INFO  [  restartedMain] DAuthenticationProperties - AzureADJwtTokenFilter Constructor.
...
```
**To Reproduce**
Create a sample spring-boot project with azure-spring-boot-starter-active-directory-3.2.0.

**Expected behavior**
Telemetry should be disabled by default and no such warnings should occur.

**Screenshots**

**Setup (please complete the following information):**
 - OS: GNU/Linux
 - Version of the Libraries used:
   - azure-spring-boot-active-directory-3.2.0
   - spring-boot-starter-parent-2.3.9.RELEASE

**Additional context**

**Information Checklist**
Kindly make sure that you have added all the following information above and checkoff the required fields otherwise we will treat the issuer as an incomplete report
- [x] Bug Description Added
- [x] Repro Steps Added
- [x] Setup information Added

**Comment by joshfree** [comment]
@stliu can you please follow up with @totakura?

/cc @samvaity @srnagar

**Comment by saragluna** [comment]
Thanks for reporting this @totakura, we'll look into it.
