### ISSUE TITLE
[FEATURE REQ] Ability to connect to eventhubs with azure-spring-cloud-stream-binder-eventhubs using RBAC, instead of connection strings

### ISSUE THREAD

**Issue by rodrigolopes** [Azure/azure-sdk-for-java#19756]
**Is your feature request related to a problem? Please describe.**
RBAC is preferable over connection strings, at least according to our security officer 

**Describe the solution you'd like**
We could provide clientId, clientSecret and tenantId as properties and use the azure identity library to connect to event hubs.

**Describe alternatives you've considered**
Use azure-messaging-eventhubs library instead of the stream binder.
I've though of defining my own EventHubClientFactory bean, but I haven't tried it yet.

**Additional context**
https://docs.microsoft.com/en-us/azure/event-hubs/authenticate-application#authenticate-from-an-application
https://docs.microsoft.com/en-us/azure/event-hubs/authorize-access-azure-active-directory#assign-azure-roles-for-access-rights

**Information Checklist**
Kindly make sure that you have added all the following information above and checkoff the required fields otherwise we will treat the issuer as an incomplete report
- [X] Description Added
- [X] Expected solution specified

**Comment by joshfree** [comment]
@stliu can you please follow up with @rodrigolopes?

**Comment by saragluna** [comment]
Hi @rodrigolopes, it's already been supported to use service principal or managed identity to connect to the EH when use the binders. Please check this doc for more details.

https://github.com/Azure/azure-sdk-for-java/tree/master/sdk/spring/azure-spring-boot-samples/azure-spring-cloud-sample-eventhubs-binder#method-2-service-principal-based-usage

**Comment by rodrigolopes** [comment]
thank you @saragluna
