### ISSUE TITLE
[QUERY] CosmosDB Client query latency spike: P99 0.3-3seconds

### ISSUE THREAD

**Issue by jeffpeiyt** [Azure/azure-sdk-for-java#19750]
**Query/Question**
CosmosDB Client query latency P99 0.3-3seconds. However the P90 is pretty low (e.g. <20ms)

To be more specific, the *average* of P99 did not go that high, around 40-60ms; However every 2-8 minutes, there is a sporadic 300ms-3seconds spike consistently.

***Why is this not a Bug or a feature Request?***
Not sure if this is a bug. Could be related to how the client works.

**Setup (please complete the following information if applicable):**
 - OS: centos7
 - IDE : NA, in production
 - Version of the Library used 4.11.0 java library
 
 **Information Checklist**

Our code is very similar to the following, and via logging we found `.iterator().hasNext()` that line, took 0.5-3 seconds.

Our query is simple `SELECT * FROM c WHERE c.host=somesite.com`

We use those configs such as `idleEndpointTimeoutInHour`, `maxConnectionPerEndpoint` etc with the default value, and with direct mode.  Service and cosmos DB are in the same region, using private endpoint

Server side latency shows maximum latency is 10ms. So it should be some client-side issue.

Wonder whether the iterator.hasNext() internally has some locking that can make it very slow occasionally?

https://github.com/Azure-Samples/azure-cosmos-java-sql-api-samples/blob/main/src/main/java/com/azure/cosmos/examples/documentcrud/sync/DocumentCRUDQuickstart.java#L169
```
        // Print
        if (filteredFamilies.iterator().hasNext()) {
            Family family = filteredFamilies.iterator().next();
            logger.info("First query result: Family with (/id, partition key) = (%s,%s)",family.getId(),family.getLastName());
        }
```

- [x] Query Added
- [x] Setup information Added

**Comment by kushagraThapar** [comment]
@mbhaskar  - can you please investigate this issue ?

**Comment by jeffpeiyt** [comment]
Via TCP dump, we observe the latency is the network latency: "sporadic rise in the time b/w TCP ACK sent by the host on which our application is running and next batch of data received from Cosmos DB"

**Comment by jeffpeiyt** [comment]
@joshfree Hi Josh, I saw you add this issue to "2021 April" milestone. Do you suggest you are aware of the problem and plan to resolve it by the end of April?  Thank you for your prompt attention.

**Comment by NikhitaKataria** [comment]
@joshfree Adding a data point here: When we increase the load, we see a drop in latency. I am not certain if we are hitting the classic case of Nagle's algorithm.

**Comment by NikhitaKataria** [comment]
@joshfree Wondering if we can get some insights into the issue.

**Comment by kushagraThapar** [comment]
@mbhaskar - ping.

**Comment by mbhaskar** [comment]
@jeffpeiyt Do you have query metrics/cosmos diagnostics for queries where you see the latency issues? Also share the diagnostics for other instances where it takes less time too.

**Comment by jeffpeiyt** [comment]
@mbhaskar the "service side latency" in azure portal account metrics looks consistently low (1-1.5ms). however the client-side P99 every 2-5minutes we have a long latency for most queries. It seems to be some network-related issue rather than the cosmos server side.

**Comment by jeffpeiyt** [comment]
@mbhaskar , as @NikhitaKataria  mentioned, we suspected it is related to the Nagle's algorithm and batching up TCP package. When we increase the load, we see a drop in latency.  Is there a setting in Cosmos client that enables "TCP_NODELAY"?

https://azure.microsoft.com/en-us/blog/performance-updates-and-tuning-best-practices-for-using-azure-database-for-postgresql/

**Comment by NikhitaKataria** [comment]
@mbhaskar Checking on this again. Is it possible to set TCP_NODELAY on cosmos requests ?

**Comment by jeffpeiyt** [comment]
@mbhaskar follow up. Any settings related to TCP_NODELAY ?

**Comment by mbhaskar** [comment]
@jeffpeiyt As requested earlier if you can collect the diagnostics for the requests that are taking longer share them, it would be helpful to understand whats going and I will be able to comment better. This is the method that you can use to get the diagnostics for queries
https://docs.microsoft.com/en-us/java/api/com.azure.cosmos.models.feedresponse.getcosmosdiagnostics?view=azure-java-stable#com_azure_cosmos_models_FeedResponse_getCosmosDiagnostics__

**Comment by jeffpeiyt** [comment]
@mbhaskar makes sense! We are enabling the diagnostic logs in this week and will get back to you by mid next week, if not earlier.

**Comment by jeffpeiyt** [comment]
We have enabled the diagnostic logs and moved to an internal channel for further communication.

**Comment by lilyjma** [comment]
thanks @jeffpeiyt -- I'll closed this issue since communication has moved to an internal channel.
