### ISSUE TITLE
[FEATURE REQ] Add TargetingFilter into spring cloud azure feature management

### ISSUE THREAD

**Issue by sergey-pi** [Azure/azure-sdk-for-java#19757]
**Is your feature request related to a problem? Please describe.**
SDK misses targeting filter for feature manager that has already implemented for .Net [microsoft.featuremanagement.featurefilters.targetingfilter ](https://docs.microsoft.com/en-us/dotnet/api/microsoft.featuremanagement.featurefilters.targetingfilter?view=azure-dotnet-preview). 

**Describe the solution you'd like**
There is already [PR-13233](https://github.com/Azure/azure-sdk-for-java/pull/13233) that introduced such filter and related functionality. It will be nice to add Targeting Filter based on it with adding little shine in term of java convention after .Net migration job execution. Please take a look at revision [84340effe6b72034e06ce53c678ca3e7cc6dd974](https://github.com/Azure/azure-sdk-for-java/commit/84340effe6b72034e06ce53c678ca3e7cc6dd974) for TargetingFilter.

**Describe alternatives you've considered**
Implement in the similar way like it is for .Net, or re-use from PR/commit mentioned above to support AZ Application Feature Management functionality.

**Additional context**
![image](https://user-images.githubusercontent.com/5304596/110646740-3ce4c500-81c8-11eb-9094-a64f5abdb4e3.png)
![image](https://user-images.githubusercontent.com/5304596/110646873-643b9200-81c8-11eb-9ee1-6da61db27631.png)
(at least such structure under `parameters` block with nested audience, users, groups, rollout percentage)

**Information Checklist**
Kindly make sure that you have added all the following information above and checkoff the required fields otherwise we will treat the issuer as an incomplete report
- [x] Description Added
- [x] Expected solution specified

**Comment by joshfree** [comment]
@stliu could you please help route this?

**Comment by stliu** [comment]
@joshfree sure, thanks

**Comment by stliu** [comment]
@saragluna  please take a look of this request, thanks

**Comment by saragluna** [comment]
@ mrm9084 could you take a look at this feature request?

**Comment by mrm9084** [comment]
@sergey-pi this has been added to the latest version of the Feature Management library.
```xml
<dependency>
    <groupId>com.azure.spring</groupId>
    <artifactId>azure-spring-cloud-feature-management</artifactId>
    <version>2.0.0</version>
</dependency>
```
