### ISSUE TITLE
project compilation failure

### ISSUE THREAD

**Issue by jeevanbalanmanoj** [Azure/azure-sdk-for-java#19752]
When I run the compile command from step no 3 of the clone project from https://github.com/Azure/azure-sdk-for-java/blob/master/sdk/spring/azure-spring-boot-samples/README.md#ready-to-run-checklist I get the below error 

![image](https://user-images.githubusercontent.com/34918493/110584750-bdd69900-8195-11eb-9101-8957485fb3c0.png)

My goal is to run the azure active directory web app samples. What am I missing here?

**Comment by joshfree** [comment]
@stliu can you please take a look?

/cc @conniey

**Comment by saragluna** [comment]
@jeevanbalanmanoj you could try to build the developing version of aad starter by following [this](https://github.com/Azure/azure-sdk-for-java/tree/master/sdk/spring/azure-spring-boot-starter-active-directory#prerequisites) instead. 

![image](https://user-images.githubusercontent.com/31124698/110898973-3a56ac80-833b-11eb-8c6a-8d7d728dc695.png)

We'll combine these two guidelines together to make it consistent and minimize the number of packages to build when to run samples. @moarychan could you help with this?

**Comment by moarychan** [comment]
@jeevanbalanmanoj , We will only focus on the packages under module `spring`, please use the following commands first:

- Build all modules in `spring` directory:
```mvn -f sdk/spring/pom.xml -Dmaven.javadoc.skip=true -Dcheckstyle.skip=true -Dspotbugs.skip=true -Drevapi.skip=true -Djacoco.skip=true -DskipTests -Dparallel-test-playback clean install```

- Build the modules associated with the current module, such as `azure-spring-boot-sample-active-directory-webapp`:
```mvn -Dmaven.javadoc.skip=true -Dcheckstyle.skip=true -Dspotbugs.skip=true -Drevapi.skip=true -Djacoco.skip=true -DskipTests -Dparallel-test-playback clean install -pl .\sdk\spring\azure-spring-boot-samples\azure-spring-boot-sample-active-directory-webapp\ -am```

**Comment by yiliuTo** [comment]
Closing this issure because the PR has been merged.
