### ISSUE TITLE
Update CustomData for VMSS

### ISSUE THREAD

**Issue by niteshjain1** [Azure/azure-sdk-for-java#1976]
I can set custom data while creating VMSS, but I do not see any API to update the custom data. Is there any such available ?

**Comment by anuchandy** [comment]
@niteshjain1 this is not supported by the service, an attempt to do this will cause service error 

```json
{
  "error": {
    "code": "PropertyChangeNotAllowed",
    "target": "customData",
    "message": "Changing property 'customData' is not allowed."
  }
}
```

**Comment by anuchandy** [comment]
question addressed, closing this.
