### ISSUE TITLE
Storage blobs enumeration\listing takes too much time and fails

### ISSUE THREAD

**Issue by asavov** [Azure/azure-sdk-for-java#1977]
We have 850+ blobs under 'vhds' container of one of our Storage accounts.

Trying to enumerate/list them through Azure Java SDK (azure-storage-4.4.0.jar) is with zero success. Here's the code snippet used.

`
 private void enumerateBlobs(CloudStorageAccount storageAccount) throws Exception {

    CloudBlobClient blobClient = storageAccount.createCloudBlobClient();

    ResultContinuation nextContainersPage = null;
    do {
        ResultSegment<CloudBlobContainer> containersPage = blobClient.listContainersSegmented(
                null, ContainerListingDetails.NONE,
                100, nextContainersPage, null, null);

        nextContainersPage = containersPage.getContinuationToken();

        for (CloudBlobContainer container : containersPage.getResults()) {

            ResultContinuation nextBlobsPage = null;
            do {
                ResultSegment<ListBlobItem> blobsPage = container.listBlobsSegmented(
                        null, false, EnumSet.noneOf(BlobListingDetails.class),
                        100, nextBlobsPage, null, null);

                nextBlobsPage = blobsPage.getContinuationToken();

                for (ListBlobItem blobItem : blobsPage.getResults()) {
                    // Do something with the BLOB
                    String blobId = blobItem.getUri().toString();
                }
            } while (nextBlobsPage != null); // No more blobs pages
        }
    } while (nextContainersPage != null); // No more containers pages
 }
`
For now we managed to enumerate only **855 blobs in 35 minutes** (which is too much time for only few blobs) and then the enum process just failed. So we don't know the actual number of Blobs so far. The Azure Portal is also unable to provide that metric. It says "the number of blobs seems to be too high".

We also tried with API build-in pagination methods:
- Iterable<CloudBlobContainer> containers = blobClient.listContainers();
- Iterable<ListBlobItem> blobs = container.listBlobs();
which internally use LazySegmentedIterable. Still no success.

We also tried with Azure CLI (packaged as docker "microsoft/azure-cli" container). Again no success. Just Out of Memory:

`
root@e31e1aee34f1:/# azure storage blob list   
info:    Executing command storage blob list
Container name:  vhds
\ Getting blobs in container vhds                                              
<--- Last few GCs --->

 3953184 ms: Mark-sweep 1367.3 (1434.3) -> 1367.3 (1434.3) MB, 582.8 / 0.0 ms [allocation failure] [GC in old space requested].
 3953774 ms: Mark-sweep 1367.3 (1434.3) -> 1367.3 (1434.3) MB, 589.0 / 0.0 ms [allocation failure] [GC in old space requested].
 3954355 ms: Mark-sweep 1367.3 (1434.3) -> 1368.5 (1404.3) MB, 581.4 / 0.0 ms [last resort gc].
 3954950 ms: Mark-sweep 1368.5 (1404.3) -> 1369.8 (1404.3) MB, 594.5 / 0.0 ms [last resort gc].

<--- JS stacktrace --->

==== JS stack trace =========================================

Security context: 0xcb1938cfb51 <JS Object>
    1: normalizePropertyNameFromXML [/usr/lib/node_modules/azure-cli/node_modules/azure-storage/lib/common/util/util.js:~577] [pc=0x3b8f4f488c91] (this=0xfe69d3f0051 <an Object with map 0x39c45aa72d59>,propertyName=0x3c98fb52c211 <String[14]: Content-Length>)
    2: setPropertyValueFromXML [/usr/lib/node_modules/azure-cli/node_modules/azure-storage/lib/common/util/util.js:605] [pc=0x3b8f4f50b8b8...

FATAL ERROR: CALL_AND_RETRY_LAST Allocation failed - JavaScript heap out of memory
 1: node::Abort() [node]
 2: 0x10cc1ac [node]
 3: v8::Utils::ReportApiFailure(char const*, char const*) [node]
 4: v8::internal::V8::FatalProcessOutOfMemory(char const*, bool) [node]
 5: v8::internal::Factory::NewInternalizedStringImpl(v8::internal::Handle<v8::internal::String>, int, unsigned int) [node]
 6: v8::internal::StringTable::LookupString(v8::internal::Isolate*, v8::internal::Handle<v8::internal::String>) [node]
 7: v8::internal::JSReceiver::HasProperty(v8::internal::Handle<v8::internal::JSReceiver>, v8::internal::Handle<v8::internal::Name>) [node]
 8: v8::internal::Runtime_HasProperty(int, v8::internal::Object**, v8::internal::Isolate*) [node]
 9: 0x3b8f4e7092a7
Aborted (core dumped)
`

Please advise how to list all blobs in a reasonable time. Thanks.

**Comment by asavov** [comment]
An interesting observation: even the pageSize passed is 100:
`                        ResultSegment<ListBlobItem> blobsPage = container.listBlobsSegmented(
                                null, false, EnumSet.noneOf(BlobListingDetails.class),
                                100, nextBlobsPage, null, null);
`
 the pages length varied between 2, 6, 24, 35, but never 100.

By the way using "Azure Portal\Storage Account\Metrics (Preview)" we found out that we have ~750K blobs under the container. So we definitely need a more responsive and performant Java API to list such a number.

**Comment by anuchandy** [comment]
@asavov can open the issue in this repo https://github.com/Azure/azure-storage-java, that's the repo for storage data plane client library .

**Comment by asavov** [comment]
Done: https://github.com/Azure/azure-storage-java/issues/234

**Comment by anuchandy** [comment]
@asavov thanks, closing this issue since it is tracking in the correct repo.
