### ISSUE TITLE
Specifying OSDisk size for  VMSS

### ISSUE THREAD

**Issue by niteshjain1** [Azure/azure-sdk-for-java#1978]
I required to provision higher IOPS for the OS Disk. Is there any way to specify OS disk size for a VMSS. the Java api does not seem to have this option. The rest api also does not specify anything regarding this.

**Comment by anuchandy** [comment]
@niteshjain1 For higher IOPS for the OS Disk you could choose managed disk storage type as PREMIUM

```java
.withOSDiskStorageAccountType(StorageAccountTypes.PREMIUM_LRS)
```

it seems in case of VMSS the OS disk size is derived from the image you are using, as you discovered i don't see a property in OS disk config to set the size explicitly. Here is the [api spec section](https://github.com/Azure/azure-rest-api-specs/blob/61ac6a8fb6573f478f7e7b614fbcde0109bc82d9/specification/compute/resource-manager/Microsoft.Compute/2017-03-30/compute.json#L5426)

**Comment by niteshjain1** [comment]
@anuchandy I am already using premium_lrs for storage type. But there also the IOPS are limited by the disk size. I can select the disk size(P4,P6 etc) for virtual machines at boot time, but unable to do so for scale sets. Any workaround for this

**Comment by anuchandy** [comment]
@niteshjain1 it seems the factor that decide IPOS is [size](https://github.com/Azure/azure-sdk-for-java/blob/master/azure-mgmt-compute/src/main/java/com/microsoft/azure/management/compute/VirtualMachineSizeTypes.java) of the scale set.  If you go to portal and choose an existing vmss, you will see `size` item in the blade, that will list supported sizes and max IPOS per size.

**Comment by anuchandy** [comment]
solution provided, closing.
