### ISSUE TITLE
[BUG] Azure Identity - device code flow - wrong application

### ISSUE THREAD

**Issue by baywet** [Azure/azure-sdk-for-java#19796]
**Describe the bug**
Using the `DeviceCodeCredential` with Azure identity `1.2.4` the wrong application is presented once I enter the code.
After going to https://microsoft.com/devicelogin and entering the device code I get the following message for the account selection
You're signing in to **Microsoft Azure Cross-platform Command Line Interface** on another device located in Canada. If it's not you, close this page.

>Notice how the application name is the Azure CLI instead of being my application name.

If I go through the sign in, my application receives a token, however the appid is `04b07795-8ddb-461a-bbee-02f9e1bf7b46` instead of the one from my app registration.

***Exception or Stack Trace***
N/A

**To Reproduce**

1. create a console application
2. register a single tenant application that supports public clients
2. add azure-identity 1.2.4 as a dependency
3. in main, copy the following code sample (you can replace the tenant and client id by your own information)
4. run the application
5. (notice the application name in the sign in screens)
6. copy the token in jwt.ms and notice the appid is wrong

***Code Snippet***
```Java
final TokenCredential tokenCredential = new DeviceCodeCredentialBuilder()
                    .clientId("6755f70d-fac6-4b8b-a460-1510aaa95d1e")
                    .tenantId("bd4c6c31-c49c-4ab6-a0aa-742e07c20232")
                    .challengeConsumer(deviceCodeInfo -> {
                        System.out.println(deviceCodeInfo.getMessage());
                    }).build();
final String token = tokenCredential.getToken(new TokenRequestContext() {{
            this.setScopes(Arrays.asList(new String[] { "https://graph.microsoft.com/.default" }));
        }}).toFuture().thenApply(r -> r.getToken()).get();
System.out.println(token);
```

**Expected behavior**
The library to use the client id I'm providing.

**Screenshots**
![image](https://user-images.githubusercontent.com/7905502/110857858-5ac52f00-8287-11eb-9cec-9f077a78c750.png)

**Setup (please complete the following information):**
 - OS: windows
 - IDE : VS Code
 - Version of the Library used 1.2.4

**Additional context**
I work on the Microsoft Graph Java SDKs.

**Information Checklist**
Kindly make sure that you have added all the following information above and checkoff the required fields otherwise we will treat the issuer as an incomplete report
- [x] Bug Description Added
- [x] Repro Steps Added
- [x] Setup information Added

**Comment by baywet** [comment]
I believe [this property](https://github.com/Azure/azure-sdk-for-java/blob/08eadff95aa5a64dcefd8ef58a5bd29d536ab736/sdk/identity/azure-identity/src/main/java/com/azure/identity/DeviceCodeCredentialBuilder.java#L23) is masking [the parent one](https://github.com/Azure/azure-sdk-for-java/blob/08eadff95aa5a64dcefd8ef58a5bd29d536ab736/sdk/identity/azure-identity/src/main/java/com/azure/identity/AadCredentialBuilderBase.java#L16) since [the guid declared here](https://github.com/Azure/azure-sdk-for-java/blob/08eadff95aa5a64dcefd8ef58a5bd29d536ab736/sdk/identity/azure-identity/src/main/java/com/azure/identity/implementation/util/IdentityConstants.java#L10) matches the one of the CLI (that I'm seeing in the token)
The [interactive browser flow](https://github.com/Azure/azure-sdk-for-java/blob/08eadff95aa5a64dcefd8ef58a5bd29d536ab736/sdk/identity/azure-identity/src/main/java/com/azure/identity/InteractiveBrowserCredentialBuilder.java#L21) is probably impacted as well.

**Comment by jasonjoh** [comment]
I'm running into this as well.

**Comment by baywet** [comment]
will be fixed by https://github.com/Azure/azure-sdk-for-java/pull/20323
