### ISSUE TITLE
[FEATURE REQ]Improve the API documentation, describe the behavior of the methods

### ISSUE THREAD

**Issue by Horcrux7** [Azure/azure-sdk-for-java#19815]
The API documentation is very poor. For example: `readItem( String itemId, PartitionKey partitionKey, CosmosItemRequestOptions options, Class<T> itemType)`

the documentation is only:
```
Reads an item in the current container while specifying additional options.
Type Parameters:
  <T> the type parameter.
Parameters:
  itemId the item id.
  partitionKey the partition key.
  options the options.
  itemType the class type of item

```
What should improved:
* What occur if the item was not found? Throw it an exception or return it a response with status code `StatusCodes.NOTFOUND`?
* Under wich condition throws it exceptions? Add the exceptions to the signature please.
* Which parameter are optional?
* Sample code for a typical use case.
* Advantages/Disadvantages to other API, for example `readItem` vs `queryItem`

Currently it is a try and error with frequent surprises. This results in bad software quality.

**Comment by kushagraThapar** [comment]
@Horcrux7 - thanks for letting us know about the Java docs improvements, we are working on it, and will have these improvements out soon.

**Comment by kushagraThapar** [comment]
@TheovanKraay  can you please take a look at this, thanks!

**Comment by TheovanKraay** [comment]
@Horcrux7 thank you for this feedback. 
You can find samples for the majority of SDK operations in [this ](https://github.com/Azure-Samples/azure-cosmos-java-sql-api-samples/tree/main/src/main/java/com/azure/cosmos/examples)repo. Please let us know if there are scenarios you feel are missing from this selection of samples, and we will work on creating samples for those. 
There is a blog post which highlights the difference between point reads (readItem) and queries (queryItem) [here](https://devblogs.microsoft.com/cosmosdb/point-reads-versus-queries/) (it is written for .NET SDK, but the principle is exactly the same in Java SDK).
Meanwhile, we will work on improvements to Java Docs.

**Comment by Horcrux7** [comment]
Examples in an SDK do not replace the need for API documentation that works in an IDE. When I analyse and review my code and look for bugs, I need the API documentation. It is impossible to look into the examples of the SDK for checking your own code or the code of colleagues.

Also, API documentation helps Microsoft developers to fix bugs when the contract of a method is written directly on the method.

**Comment by TheovanKraay** [comment]
@Horcrux7 - I shared sample code only in reference to your last two bullet points:

- Sample code for a typical use case.
- Advantages/Disadvantages to other API, for example readItem vs queryItem

I understand that your suggestion is that these should also be included in the API documentation. As mentioned, we will work on improving the API documentation.

**Comment by TheovanKraay** [comment]
@Horcrux7 - would welcome your feedback on the recent improvements we've made to the API docs.

**Comment by Horcrux7** [comment]
There is a big improvement in the Java Doc after more than 2 years! Currently I am not working on our Cosmos Db stack. Our Cosmos Db Layer is currently finished. That's why this doesn't help me anymore. But it will help other future developers.
