### ISSUE TITLE
Unable to get Active Directory name through SDK

### ISSUE THREAD

**Issue by rodrigofraxino** [Azure/azure-sdk-for-java#1984]
Could not find any method to retrieve the active directory name using the Azure SDK. Could only find methods to retrieve the subscription names.

**Comment by vhvb1989** [comment]
Hello @rodrigofraxino 

I am sorry about you didn't get a sooner answer on this
Do you still need help on this? Let me know and I would be happy to help.

Note: As part of repository cleaning effort, this issue will be closed by **Nov 11** if no response is received from submitter and/or not further action is required.
