### ISSUE TITLE
Using lib azure-eventhubs-3.2.2 with MSI in a Java App Service.

### ISSUE THREAD

**Issue by TeplrGuy** [Azure/azure-sdk-for-java#19852]
Using azure-eventhubs-3.2.2 and customer is getting the below errors:

The call is trying to connect to this endpoint "http://169.254.169.254/metadata/instance?api-version=2020-09-01" and get connection refused.
Error during managedIdentityScenario. Exception: [Ljava.lang.StackTraceElement;@35fc6dc4
java.lang.RuntimeException: java.net.ConnectException: Connection refused (Connection refused)
The above setup works on a VM but not on a web app hosted on Azure App Service.

Issue is fixed when using azure-messaging-eventhubs 5.0.2.

Question is, we don't like to use the new library, is there a way to use azure-eventhubs-3.2.2 with MSI on an App Service?

**Comment by joshfree** [comment]
@conniey could you please follow up with @TeplrGuy

**Comment by TeplrGuy** [comment]
@joshfree looks like the solution is to use AppServiceMSICredentials  class instead of MSICredentials

https://github.com/Azure/azure-libraries-for-java/blob/master/AUTH.md#using-msicredentials--appservicemsicredentials


Follow up question is: what is the main difference between using azure-eventhubs-3.2.2 vs using azure-messaging-eventhubs 5.0.2

**Comment by conniey** [comment]
@TeplrGuy 
> Follow up question is: what is the main difference between using azure-eventhubs-3.2.2 vs using azure-messaging-eventhubs 5.0.2

azure-messaging-eventhubs is an entirely rewritten library for Azure Event Hubs. We rewrote many of the Java libraries to follow the same set of Azure SDK principles so consumers would get a unified feel for development. Here is a quick video on motivation (https://www.youtube.com/watch?v=38RYIx7a2M4) and our guidelines https://azure.github.io/azure-sdk/java_introduction.html

**Comment by ramya-rao-a** [comment]
@TeplrGuy Looks like you found the solution to the auth problem and @conniey has addressed your follow up question.
We will go ahead and close this issue.

Do try out the newer azure-messaging-eventhubs package and share any feedback you have.
