### ISSUE TITLE
The way of storage tables endpoint and table url constructed in Azure SDK for java doesn't support use in azurite

### ISSUE THREAD

**Issue by v-hongli1** [Azure/azure-sdk-for-java#19869]
### Error Description:
[Azurite](https://github.com/Azure/Azurite) is an Azure Storage emulator.
Current endpoint and tablel url which is constructed in azure sdk for java can not access azurite. The reason is the storage tables endpoint and table url for Azurite is different from the one of an Azure storage account.
In Azurite, storage tables endpoint and table url constructed is shown as following:
**_` https://127.0.0.1:10002/<account-name>/<resource-path>`_**
In Azure SDK for java, storage tables endpoint and table url constructed is shown as following:
**_` https://<account-name>.table.core.windows.net/<resource-path>`_**

### Error Track:
1. The code for storage tables endpoint constructed in Azure SDK for java is [here](https://github.com/Azure/azure-sdk-for-java/blob/master/sdk/tables/azure-data-tables/src/main/java/com/azure/data/tables/implementation/TablesImpl.java#L71)
![image](https://user-images.githubusercontent.com/74638143/111248835-a855e900-8645-11eb-87a9-e26b223604d3.png)

2. The code for storage table url constructed in Azure SDK for java is [here](https://github.com/Azure/azure-sdk-for-java/blob/master/sdk/tables/azure-data-tables/src/main/java/com/azure/data/tables/TableAsyncClient.java#L74)
![image](https://user-images.githubusercontent.com/74638143/111248495-0209e380-8645-11eb-94fd-1a465d61e83c.png)

### Expected Behavior
Storage tables endpoint and table url which is constructed in azure sdk for java can access azurite.

@jongio for notification.

**Comment by alzimmermsft** [comment]
@vcolin7 mind checking this out

**Comment by v-xuto** [comment]
azsdk-azurite

**Comment by v-xuto** [comment]
@vcolin7 Do you have any progress or plans on this issue?

**Comment by vcolin7** [comment]
Hey @v-xuto, this has been in my backlog for a good while, sorry about that. I think we had the same issue in one of our other tier 1 languages that got a fix, so I should be able to probably leverage that here. I'll try to do so before the end of the week, if not on Tuesday (Monday is a holiday in the US).
