### ISSUE TITLE
[spring-servicebus]  Integrating Spring Sleuth and Zipkin with Azure Service Bus SDK

### ISSUE THREAD

**Issue by hemanttanwar** [Azure/azure-sdk-for-java#19885]
Feature- Integrating Spring Sleuth and Zipkin with Azure Service Bus SDK

Verify tracing is working as expected : https://docs.microsoft.com/en-us/azure/developer/java/sdk/tracing

One of the customer is using following library, ensure it works on these versions.

spring-cloud-starter-sleuth 2.2.3 (release train Hoxton.SR5) and 
azure-messaging-servicebus 7.x.x

**Comment by saragluna** [comment]
Closed in favor of https://github.com/Azure/azure-sdk-for-java/issues/21760.
