### ISSUE TITLE
Unable to use nested template that specifies 'resourceGroup'

### ISSUE THREAD

**Issue by ddietterich** [Azure/azure-sdk-for-java#1990]
Inspired by this article [Resource Manager Cross Resource Group Deployment](https://na01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fdocs.microsoft.com%2Fen-us%2Fazure%2Fazure-resource-manager%2Fresource-manager-cross-resource-group-deployment&data=02%7C01%7Carsenv%40microsoft.com%7C1b24b620741d4a941ed108d53c1bf244%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C636481013088982395&sdata=OO7mz5yzGyxVlcELjXlLJTMCh%2FiycJ1orvUg2tAil14%3D&reserved=0), I made an ARM template with a nested template that specifies a resource group. Specifically, the nested template adds a subnet to a VNet in another RG and then the main template launches NICs, VMs etc that use that subnet.

It works great when run from Azure CLI V2. When I run it from my Java code (1.4.0 sdk library), I get this message:

> com.microsoft.azure.CloudException: Deployment template validation failed: 'The template resource 'pdcbaseVnet' at line '1' and column '1018' is invalid. The api-version '2016-09-01' used to deploy the template does not support 'ResourceGroup' property. Please use api-version '2017-05-10' or later to deploy the template. Please see https://aka.ms/arm-template/#resources for usage details.'.: Deployment template validation failed: 'The template resource 'pdcbaseVnet' at line '1' and column '1018' is invalid. The api-version '2016-09-01' used to deploy the template does not support 'ResourceGroup' property. Please use api-version '2017-05-10' or later to deploy the template. Please see https://aka.ms/arm-template/#resources for usage details.'.
 
Now my template doesn't mention 2016-09-01, so I am guessing the SDK is generating that.

Would it be possible to move the SDK forward to 2017-05-10?

**Comment by vhvb1989** [comment]
Hello @ddietterich 

I am sorry about you didn't get a sooner answer on this
Do you still need help on this? Let me know and I would be happy to help.

Note: As part of repository cleaning effort, this issue will be closed by **Nov 11** if no response is received from submitter and/or not further action is required.
