### ISSUE TITLE
Azure Blob - Copy blob to larger size than 256MB

### ISSUE THREAD

**Issue by abhikt48** [Azure/azure-sdk-for-java#19908]
We are migrating blob component from old SDK `azure-storage-5.5.0` to new SDK `azure-storage-blob-12.10.0`. New SDK provides option to copy blob upto 256MB, but we have requirement to copy blob more than 256MB, and we were able copy more than 256MB with Old SDK. 

**New SDK Screenshot**
![image](https://user-images.githubusercontent.com/22897837/111467987-f984dc00-871c-11eb-8681-e191ec57fa76.png)

**Old SDK Code Snippet**
```
CloudBlockBlob destCloudBlockBlob = destinationContainer.getBlockBlobReference(blobName);
destCloudBlockBlob.startCopy(new URI(sourceBlobUri));
```

Could you please suggest - how can we copy blob with more than 256MB with new SDK `azure-storage-blob-12.10.0`. Please let me know for any information.

**Setup (please complete the following information if applicable):**
 - OS: window
 - IDE : eclipse
 - Version of the Library used: `azure-storage-blob-12.10.0`

**Comment by gapra-msft** [comment]
Hi @abhikt48 Thank you for posting this question.

The SDK has two copy methods - the copyFromUrl (serverside sync copy) method that you found, as well as the beginCopy (serverside async copy) method. 

The old SDK snippet you provided corresponds to the beginCopy method that will allow you to copy a blob larger than 250MB.

Hope that helps!

**Comment by amishra-dev** [comment]
Please reactivate if you have any other questions about this.
