### ISSUE TITLE
Optimization of Spring AAD starter doc and samples

### ISSUE THREAD

**Issue by yiliuTo** [Azure/azure-sdk-for-java#19903]
1. For code snippets in README.md, try to use those in associated sample projects instead of those under [sdk/spring/azure-spring-boot/src/samples/java/com/azure/spring/aad](https://github.com/Azure/azure-sdk-for-java/tree/master/sdk/spring/azure-spring-boot/src/samples/java/com/azure/spring/aad)
2. In aad resource server samples, we need to customize [AADResourceServerWebSecurityConfigurerAdapter](https://github.com/Azure/azure-sdk-for-java/blob/master/sdk/spring/azure-spring-boot/src/main/java/com/azure/spring/aad/webapi/AADResourceServerWebSecurityConfigurerAdapter.java) instead of `WebSecurityConfigurerAdapter`.

**Comment by saragluna** [comment]
@ZhuXiaoBing-cn we should get the second point done first since we already have an adapter.
