### ISSUE TITLE
SDK logs HTTP Bearer tokens when log level is HEADERS or BODY_AND_HEADERS

### ISSUE THREAD

**Issue by evanye** [Azure/azure-sdk-for-java#1991]
When we configured the sdk (version 1.3) to log http headers, I noticed that the log messages include the entire http bearer token. For example, I see
```
2017/12/06 00:01:09 INFO Resources deleteById[tagKey=tagValue]: Authorization: Bearer <REDACTED_BEARER_TOKEN>
```

in our sdk logs. This is an issue when we enable logging for our customers, as bearer tokens are sensitive credentials.

Could the team consider redacting the bearer tokens at logging time?

**Comment by yungezz** [comment]
hi @ChenTanyi could you pls have a look is this handled in Track2 in core? thanks.

**Comment by ChenTanyi** [comment]
@evanye @yungezz Track2 SDK will hide such header, track1 is still logging this header. It needs to update client-runtime to add such feature.
