### ISSUE TITLE
No default image for Win10  in KnownWindowsVirtualMachineImage

### ISSUE THREAD

**Issue by puneet101** [Azure/azure-sdk-for-java#1992]
There is no constant for default Win10 image in KnownWindowsVirtualMachineImage

How do we create a VM from the Win10 Pro image in the marketplace:
new->marketplace->compute->Win10 Pro, Version 1709
PUBLISHER: Microsoft

**Comment by puneet101** [comment]
@anuchandy Any pointers for this? How do we find the details like offer, sku, publisher and version to create an "ImageReference"?

**Comment by anuchandy** [comment]
```java
ImageReference imageReference = new ImageReference();
imageReference.withPublisher("MicrosoftWindowsDesktop");
imageReference.withOffer("Windows-10");
imageReference.withSku("RS3-Pro");
imageReference.withVersion("latest");
```

This [test](https://github.com/Azure/azure-sdk-for-java/blob/e12f4488405636740f7de3b49e2b71255d8e72de/archive/azure-mgmt-compute/src/test/java/com/microsoft/azure/management/compute/VirtualMachineImageOperationsTests.java#L16) shows how to enumerate images.

**Comment by puneet101** [comment]
@anuchandy  Thanks!
