### ISSUE TITLE
[FEATURE REQ] Provide the ability to configure maxAutoRenewDuration for ServiceBusProcessorClient 

### ISSUE THREAD

**Issue by jventuri2** [Azure/azure-sdk-for-java#19929]
**Is your feature request related to a problem? Please describe.**
I recently migrated from using the older azure_servicebus libraries to the new azure-messaging-servicebus (7.0.2) libraries.
With the older libraries I was able to configure maxAutoRenewDuration  but with the new library (for ServiceBusProcessorClient ) I cannot

**Describe the solution you'd like**
Ability to configure maxAutoRenewDuration for ServiceBusProcessorClient 

**Describe alternatives you've considered**

**Additional context**

**Information Checklist**
Kindly make sure that you have added all the following information above and checkoff the required fields otherwise we will treat the issuer as an incomplete report
- [ ] Description Added
- [ ] Expected solution specified

**Comment by joshfree** [comment]
Thanks for providing this feedback @jventuri2.  @hemanttanwar can you please take a look

**Comment by hemanttanwar** [comment]
@jventuri2    We will be adding this feature.

**Comment by meetamitbhatia** [comment]
Just FYI, we've multiple customers asking for the same feature, in case that helps to prioritize adding the change.

**Comment by the-codinator** [comment]
+1 for this feature.
Support Request: #2103240060004181

**Comment by hemanttanwar** [comment]
We are adding this in April release, This will be beta release for one month before  it is released as GA in May.

**Comment by hemanttanwar** [comment]
This API was released as beta version https://search.maven.org/artifact/com.azure/azure-messaging-servicebus/7.3.0-beta.1/jar

**Comment by the-codinator** [comment]
Hi, is there a GA date available for this feature yet ?

**Comment by the-codinator** [comment]
Hi @hemanttanwar we're more than half way into June and GA for this was planned for May.
Is there an updated date for this feature release ?

**Comment by YijunXieMS** [comment]
Hi @the-codinator it's planned to be included in the July release, about 7/9/2021

**Comment by ramya-rao-a** [comment]
This feature was added in 7.3.0 version of the azure-messaging-servicebus package
