### ISSUE TITLE
Search for a VM with input name

### ISSUE THREAD

**Issue by puneet101** [Azure/azure-sdk-for-java#1993]
What's the best way to search for a VM:

- with exact name match (aka is only a hit for aka)
- with "contains" in name input search string (aka is a hit for both maka and caka)  
- with a "tag" (filter the VMs with the tag, wow=1) 

Going through each VM and doing a comparison is super slow. Is there a better find or search API interface with input name?

**Comment by puneet101** [comment]
@anuchandy Any pointers?

**Comment by puneet101** [comment]
@anuchandy Is this possible or not supported today? Thanks!

**Comment by anuchandy** [comment]
I checked this and fast lookup is not supported today by compute service. Only option is to enumerate the VM resources and look for the matching name.

**Comment by puneet101** [comment]
Ok, thanks! It will be nice to add this as a feature request. 

Azure UI provides filtering option and it has to be some sort of index/search feature in the backend.

**Comment by anuchandy** [comment]
@puneet101 we'll enable this in SDK when compute service expose an API to look-up using various filters.

**Comment by puneet101** [comment]
I checked this and fast lookup is not supported today by compute service. Only option is to enumerate the VM resources and look for the matching name.

@anuchandy We are having trouble with this. The calls are timing out if the list has more than 50 VMs.

**Comment by Drewm3** [comment]
Cleaning up old issues from 2016 - 2018. Please let us know if this issue if it is still a concern.
