### ISSUE TITLE
Azure Storage - Diagnostics Logs and Metrics not stored periodically

### ISSUE THREAD

**Issue by ShailashreeE** [Azure/azure-sdk-for-java#1994]
Hi,

We have an issue in retrieving diagnostics data from Azure Storage accounts for Azure SQL database.

We have configured diagnostics settings for an Azure SQL database to store the logs and metrics to a Storage account. As per configuration, the .json file containing the metrics is generated under a Blob service in the storage account. Each .json file contains data for 1 hour, one record for each minute (starting from 00:00 to 00:59).

As per the Microsoft blog(https://docs.microsoft.com/en-us/azure/monitoring-and-diagnostics/monitoring-archive-activity-log), we expect this .json file to be generated at an interval of 1 hour. But the issue is, the files are created randomly.

<img width="721" alt="microsoftblog" src="https://user-images.githubusercontent.com/28895501/33708959-e6eac286-db61-11e7-9444-ead620e38f3f.png">

Example 1 : .json files for hour=0,1,2,3,4,5 are generated on hour=8

Example 2 : .json files for day=1,hour=22,23 are generated on day=2,hour=1

Expectation : .json file for h=5 should be generated once the 5th hour of the day is completed.

Note : The expected behavior also occurs sometimes.

Sample scenario : UTC time now is 9.00am. So we expect the last .json file to be generated for h=8,m=0 to 59. But the last generated file stands at h=4 containing data from 4.00 to 4.59

<img width="857" alt="blob" src="https://user-images.githubusercontent.com/28895501/33708996-052f642c-db62-11e7-8351-7fb72e018d42.png">

Kindly check the issue and let us know how this inconsistency with diagnostics metrics storage an be avoided and generate files at regular intervals, as we rely on accurate periodic diagnostics.

Thanks in advance !

**Comment by asheniam** [comment]
This issue is not related to the SDK.  If this issue persists, please file a support ticket to track this.
