### ISSUE TITLE
Azure Blob - Alternative option of "CloudBlobClient.getEndpoint().getQuery()" in new SDK

### ISSUE THREAD

**Issue by abhikt48** [Azure/azure-sdk-for-java#19951]
We are migrating blob component from old SDK a`zure-storage-5.5.0` to new SDK `azure-storage-blob-12.10.0`.  We used `cloudBlobClient.getEndpoint().getQuery()` to get value of sharedAccessSignature. I didn't get any option yet to get value of sharedAccessSignature with new SDK.

**Old SDK**
```
CloudBlobClient cloudBlobClient = new CloudBlobClient(new URI(BLOB_SAS_SERVICE));
 System.out.println("Query - " + cloudBlobClient.getEndpoint().getQuery());
```

**New SDK**
`BlobContainerClientBuilder blobContainerClientBuilder = new BlobContainerClientBuilder().endpoint(BLOB_SAS_SERVICE);`

If possible, Could you please suggest option to get  value of sharedAccessSignature with new SDK.

**Setup (please complete the following information if applicable):**
OS: window
IDE : eclipse
Version of the Library used: `azure-storage-blob-12.10.0`

**Comment by joshfree** [comment]
Thanks for migrating to the latest Blob Storage SDK, @abhikt48.  Someone from the `Storage` client library team will follow up with you shortly.

/cc @gapra-msft @rickle-msft

**Comment by gapra-msft** [comment]
Hi @abhikt48 

Thank you for posting this question. At the moment there is no convenient way to extract the sas token from the client. I will have some discussions with my team and get back to you regarding potential solutions to this.

**Comment by abhikt48** [comment]
@gapra-msft  Thanks a lot for quick update. Will wait for input.

**Comment by rickle-msft** [comment]
@abhikt48 Can you please describe what your scenario is here and why you need to get the sas token from a client/what you'd like to do with it?

**Comment by ibrahimrabab** [comment]
Hi @abhikt48 ,

Just following up on this thread. Has this issue been resolved? If so, we can go ahead and close this. If not, can you please let us know what blockers you're running into, or any questions you may have?

Thank you!

**Comment by abhikt48** [comment]
@ibrahimrabab  - I resolved this issue via preserving SAS signature.  

We can close this issue now.
