### ISSUE TITLE
Error while calling CostManagementManager.queries().usage() . The resource type 'Query' could not be found in the namespace 'Microsoft.CostManagement' for api version '2020-06-01'

### ISSUE THREAD

**Issue by milindmpratiti** [Azure/azure-sdk-for-java#19950]
I am trying to fetch the usage information for my Azure subscription using Azure Java SDK. 
Below is the sample code I wrote to fetch usage cost.
```
	CostManagementManager mgr = CostManagementManager.authenticate(cred,  profile);
		
		 
		String scope = "/subscriptions/<my scubscription id> ";
		
		QueryDefinition query = new QueryDefinition();
		java.time.OffsetDateTime fTime = OffsetDateTime.now().minusMonths(1);
		java.time.OffsetDateTime toTime = OffsetDateTime.now();
	 	QueryDataset ds = new QueryDataset();
		ds.withGranularity(GranularityType.DAILY);
		
 		QueryDefinition defn = query.withTimeframe(TimeframeType.WEEK_TO_DATE).withType(ExportType.ACTUAL_COST).withDataset(ds);
 		
 		QueryResult result =  mgr.queries().usage(scope, defn);

```
The call throws an exception Caused by: com.azure.core.management.exception.ManagementException: Status code 404, "{"error":{"code":"InvalidResourceType","message":"The resource type 'Query' could not be found in the namespace 'Microsoft.CostManagement' for api version '2020-06-01'. The supported api-versions are '2018-05-31,2018-08-31,2018-08-01-preview,2018-10-01-preview,2018-12-01-preview,2019-01-01,2019-03-01-preview,2019-04-01-preview,2019-05-01-preview,2019-10-01,2019-11-01'."}}"

While searching, I came across similar error in Azure Python SDK  ( https://github.com/Azure/azure-sdk-for-python/issues/16102). Not sure if its related .

Any pointer /help is appreciated..

**Comment by joshfree** [comment]
@yungezz could you please help route this `Cost Management` management plane inquiry

**Comment by weidongxu-microsoft** [comment]
If service does not onboard 2020-06, we would had to revert back to 2019-11

**Comment by weidongxu-microsoft** [comment]
1.0.0-beta.2 release with api-version=2019-11-01
https://search.maven.org/artifact/com.azure.resourcemanager/azure-resourcemanager-costmanagement/1.0.0-beta.2/jar
