### ISSUE TITLE
[QUERY] Does Latest Azure Service Bus Java SDK supports sending of Custom User Properties 

### ISSUE THREAD

**Issue by sirajP12345** [Azure/azure-sdk-for-java#19974]
In older version of service bus sdk, Message instance has message.setProperties(properties); method to send Metadata. But latest ServiceBusMessage does not have method to set properties. Any alternate way to support this with ServiceBusMessage.

**Comment by conniey** [comment]
@sirajP12345 The properties are ApplicationProperties. You can set them via: [ServiceBusMessage.getApplicationProperties()](https://azuresdkdocs.blob.core.windows.net/$web/java/azure-messaging-servicebus/7.1.0/com/azure/messaging/servicebus/ServiceBusMessage.html#getApplicationProperties--)

**Comment by sirajP12345** [comment]
Thanks @conniey . This addressed my query and closing the issue.
