### ISSUE TITLE
[FEATURE REQ] Prevent KeyVault refresh Timer from blocking application termination

### ISSUE THREAD

**Issue by jwillebrands** [Azure/azure-sdk-for-java#19978]
**Is your feature request related to a problem? Please describe.**
We've recently noticed our Spring applications hanging around in a failed state after an unhandled exception tearing down the SpringApplication, without terminating properly. We've traced this back to a change introducing a dependency on `azure-spring-boot-starter-keyvault-secrets` to sync secrets from Azure KeyVault. Further investigation shows that, when a refreshInterval is configured, the `KeyVaultOperation` class uses `java.util.Timer` to set up a task to refresh the secrets.

As stated in the [docs](https://docs.oracle.com/javase/7/docs/api/java/util/Timer.html), the task execution thread used by `Timer` does _not_ run as a daemon thread:

>  By default, the task execution thread does not run as a daemon thread, so it is capable of keeping an application from terminating.

The result is that we see applications being kept alive by this timer thread, despite everything else being torn down. I had considered filing this as a bug, but I'm not sure if this is intentional. We don't see it as a valid use case.

**Describe the solution you'd like**
Use a daemon thread for the refresh timer tasks. E.g. by creating new `Timer` objects in `KeyVaultOperation` setting the daemon flag to `true`: https://docs.oracle.com/javase/7/docs/api/java/util/Timer.html#Timer(boolean)

**Describe alternatives you've considered**
There are a couple of options that can be implemented instead:
- If the current behavior is intentional, or changing it is undesirable, the daemon flag could be added to `KeyVaultProperties` to make it configurable for the consumer.
- Register for one of the available shutdown hooks to manually `cancel()` the timer.
- Should the non-daemon version be kept unchanged, this should be clearly documented.

**Additional context**
Related artifact: `azure-spring-boot-starter-keyvault-secrets`
Observed on version `3.1.0`

**Information Checklist**
Kindly make sure that you have added all the following information above and checkoff the required fields otherwise we will treat the issuer as an incomplete report
- [x] Description Added
- [x] Expected solution specified

**Comment by yiliuTo** [comment]
Thanks for your suggestions, we will look into this.

**Comment by yiliuTo** [comment]
Hi @jwillebrands , the pr to make Timer task run as a daemon thread has been merged. You can wait for our next release of 3.4.0 for the fix.

**Comment by jwillebrands** [comment]
Will keep an eye on the PR and we'll look out for the next release. Thanks for picking this up so quickly.

**Comment by backwind1233** [comment]
#20014

**Comment by yiliuTo** [comment]
Hi @jwillebrands , now [3.4.0](https://mvnrepository.com/artifact/com.azure.spring/azure-spring-boot-starter-keyvault-secrets/3.4.0) has been released and I will close this issue.
