### ISSUE TITLE
Can i download tomcat's log by azure sdk for java?

### ISSUE THREAD

**Issue by mayong1030** [Azure/azure-sdk-for-java#1997]
I use the tomcat of app service ,  because our office's firewall doesn't raise the port of 21, i cannot download tomcat's log by ftp, can i download tomcat's log by azure sdk for java.

**Comment by vhvb1989** [comment]
Hello @mayong1030 

I am sorry about you didn't get a sooner answer on this
Do you still need help on this? Let me know and I would be happy to help.

Note: As part of repository cleaning effort, this issue will be closed by **Nov 11** if no response is received from submitter and/or not further action is required.
