### ISSUE TITLE
We should expose a token cache in Core that lets one fetch a token based off tokenrequestContext

### ISSUE THREAD

**Issue by pallavit** [Azure/azure-sdk-for-java#19980]
The current exposed SimpleTokenCache let's one cache a token but not a token that can change based on tokenrequestcontext which I think will be useful if exposed in a way that can be extended.

1. Most token credentials would need to fetch tokens based on a context as the token is likely to vary per request.
2. Having a cache that lets you work on a generic token credential/tokenrequestcontext makes it possible for it to be reused.
3. Even though caching tokens should be done carefully- there are valid scenarios where we would need to do this.

We already have a variant of it in experimental package for ARMChallengePolicy and will now have another variant for it in ACR policy, converging the two will be useful.

Proposal: One approach would be something similar to what is in the draft PR - https://github.com/Azure/azure-sdk-for-java/pull/19969 (The intent is just to show the intention and not the actual naming\implementation).

**Comment by g2vinay** [comment]
I am probably missing some context on ACR side, 
Currently, I feel the cache can be used internally via the policy itself and possibly doesn't need to be exposed.
We can do quick sync up around this.
