### ISSUE TITLE
[QUERY] Default HTTP client lifecycle for multiple client instances 

### ISSUE THREAD

**Issue by giventocode** [Azure/azure-sdk-for-java#19998]
**Query/Question**
I have a long running application that uploads and downloads block blobs at regular intervals.  The current implementation creates a BlockBlobClient for each download/upload operation using the `SpecializedBlobClientBuilder` since each blob is different. Can I assume that the internal implementation of the SDK will pool the underlying HTTP client for all instances of  BlockBlobClient? Or each BlockBlobClient creates a new HTTP client?  If the latter is correct, I want to avoid it, do I need to manage and plugin my own HTTP client as described [here](https://docs.microsoft.com/en-us/azure/developer/java/sdk/http-client-pipeline)?

**Comment by alzimmermsft** [comment]
@giventocode thanks for asking this question.

When using a service client builder, such as `SpecializedBlobClientBuilder`, if an `HttpClient`, or `HttpPipeline` as it contains an `HttpClient`, wasn't configured the builder will instantiate a new `HttpClient` each time a service client is constructed. Generally, this will result in a new connection pool being used. To prevent a new connection pool being used for each service client constructed there are a few options available.

**Setting an HttpClient in the Builder**

When an `HttpClient` is configured in the builder each time a service client is constructed it will use that `HttpClient`, allowing it to be shared across many service clients. The service client builder uses a default `HttpClient` constructor which is publicly accessible, so it can be used without any existing logic changes.

```java
SpecializedBlobClientBuilder blockBlobClientBuilder = new SpecializedBlobClientBuilder()
    .endpoint(/* your blob endpoint */)
    .credential(/* your credential */)
    .httpClient(HttpClient.createDefault());
```

From there, after setting your `containerName` and `blobName`, every time a `BlockBlobClient` is constructed it will use the same shared `HttpClient`.

**Using a BlobServiceClient and BlobContainerClient to Create BlockBlobClients**

Using the blob service client hierarchy, `BlobServiceClient` -> `BlobContainerClient` -> blob clients, will have the parent `HttpClient` shared to its children service clients. So, constructing a `BlobServiceClient` and using `BlobServiceClient.getBlobContainerClient` and then `BlobContainerClient.getBlobClient.getBlockBlobClient` will have the same `HttpClient` being shared. This method also offers the ability for containers to be created if needed.

**Comment by giventocode** [comment]
Thank you @alzimmermsft for the detailed explanation. Very helpful.
