### ISSUE TITLE
RefreshScope not working with CosmosClientBuilder

### ISSUE THREAD

**Issue by abuinteam** [Azure/azure-sdk-for-java#19995]
We are using azure-spring-data-cosmos and annotating CosmosClientBuilder with @Refreshscope so that when there is a change in the credentials cosmos builder will be recreated and injected to dependencies without restart of our app.

I followed a similar issue raised in the thread https://github.com/Azure/azure-sdk-for-java/issues/13876 which has been closed. I updated my dependencies as mentioned in the thread above. Still I am seeing an exception when annotate with @RefreshScope. When I remove @RefreshScope no error is observed. Error I am seeing is related to CosmosFactory reflection to get the userAgentSuffix field. Error below,

"java.lang.NoSuchFieldException: userAgentSuffix
	at java.lang.Class.getDeclaredField(Class.java:2070) ~[na:1.8.0_251]
	at com.azure.spring.data.cosmos.CosmosFactory.getUserAgentSuffixValue(CosmosFactory.java:86) [azure-spring-data-cosmos-3.5.0.jar:na]
	at com.azure.spring.data.cosmos.CosmosFactory.updateCosmosClientBuilderWithUASuffix(CosmosFactory.java:75) [azure-spring-data-cosmos-3.5.0.jar:na]
	at com.azure.spring.data.cosmos.CosmosFactory.createCosmosAsyncClient(CosmosFactory.java:70) [azure-spring-data-cosmos-3.5.0.jar:na]
	at com.azure.spring.data.cosmos.config.AbstractCosmosConfiguration.cosmosAsyncClient(AbstractCosmosConfiguration.java:57) [azure-spring-data-cosmos-3.5.0.jar:na]

Our configurations below,

        ```
      @Bean
	@RefreshScope
	public CosmosClientBuilder cosmosClientBuilder() throws IOException, SecurityException, NoSuchFieldException {
		log.info("Initializing cosmosClientBuilder..");
		Path path = Paths.get("/Users/aaaaa/Desktop/cosmosSetting.properties");
		DirectConnectionConfig directConnectionConfig = new DirectConnectionConfig();
        GatewayConnectionConfig gatewayConnectionConfig = new GatewayConnectionConfig();
        this.azureKeyCredential = new AzureKeyCredential(Files.readAllLines(path).get(1));
        CosmosClientBuilder cosmosClientBuilder = new CosmosClientBuilder();
        cosmosClientBuilder.endpoint(Files.readAllLines(path).get(0))
        		          .key(Files.readAllLines(path).get(1))
        		          .directMode(directConnectionConfig, gatewayConnectionConfig)
        		          .connectionSharingAcrossClientsEnabled(true)
        		          .contentResponseOnWriteEnabled(true);
        		          .userAgentSuffix("my-application1-client");
        return cosmosClientBuilder;
	}

        @Bean
	@Override
	@RefreshScope
	public CosmosConfig cosmosConfig() {
    	log.info("Initializing cosmosConfig..");
		return CosmosConfig.builder().responseDiagnosticsProcessor(new ResponseDiagnosticsProcessorImplementation())
				.enableQueryMetrics(true).build();
	}

```
**Dependencies** 

<artifactId>spring-boot-starter-parent</artifactId>
<version>2.4.0</version>

<dependency>
<groupId>com.azure</groupId>
<artifactId>azure-spring-data-cosmos</artifactId>
<version>3.5.0</version>
</dependency>
		
<dependency>
<groupId>com.azure</groupId>
<artifactId>azure-cosmos</artifactId>
<version>4.13.0</version>
</dependency>
		
<dependency>
<groupId>io.projectreactor.netty</groupId>
<artifactId>reactor-netty</artifactId>
<version>1.0.4</version>
</dependency>

<dependency>
    <groupId>io.projectreactor.netty</groupId>
    <artifactId>reactor-netty-http</artifactId>
    <version>1.0.4</version>
</dependency>

<dependency>
    <groupId>io.projectreactor.netty</groupId>
    <artifactId>reactor-netty-core</artifactId>
    <version>1.0.4</version>
</dependency>

Please let us know if there is a solution to this problem.

**Comment by abuinteam** [comment]
Hi Team, Just an fyi same approach worked with older version of the cosmos spring which is, below

`<dependency>
			<groupId>com.microsoft.azure</groupId>
			<artifactId>azure</artifactId>
			<version>1.3.0</version>
		</dependency>
		<dependency>
			<groupId>com.microsoft.azure</groupId>
			<artifactId>spring-data-cosmosdb</artifactId>
			<version>2.2.4</version>
		</dependency>
		<dependency>
			<groupId>com.microsoft.azure</groupId>
			<artifactId>azure-cosmosdb-direct</artifactId>
			<version>2.6.8</version>
		</dependency>`

**Config classes**
`
  @Bean
  @Primary
  @RefreshScope
  public CosmosDbFactory cosmosDbFactory(CosmosDBConfig config) {
	log.info("Initializing CosmosDbFactory..");
    return new CosmosDbFactory(config);
  }
 
 @Bean
 @Primary
 @RefreshScope
 public CosmosTemplate cosmosTemplate(CosmosDBConfig config) throws ClassNotFoundException{// TODO Auto-generated method stub
	 log.info("Initializing CosmosTemplate..");
	 return new CosmosTemplate(this.cosmosDbFactory(config), this.mappingCosmosConverter(),
             config.getDatabase());
 }

  @Bean
  @RefreshScope
  public CosmosDBConfig getConfig() {
	log.info("Initializing CosmosDBConfig..", cosmosSetting.isPopulateQueryMetrics());
	this.cosmosKeyCredential = new CosmosKeyCredential(cosmosSetting.getKey());
    CosmosDBConfig cosmosdbConfig =
        CosmosDBConfig
            .builder(cosmosSetting.getUri(), this.cosmosKeyCredential, cosmosSetting.getDbName())
            .build();
    cosmosdbConfig.setPopulateQueryMetrics(cosmosSetting.isPopulateQueryMetrics());
    cosmosdbConfig
        .setResponseDiagnosticsProcessor(new ResponseDiagnosticsProcessorImplementation());
    cosmosdbConfig.getConnectionPolicy().userAgentSuffix(
        "/xxxxxxx");
    log.info("PopulateQueryMetrics is set to {}", cosmosSetting.isPopulateQueryMetrics());
    return cosmosdbConfig;
  }
`

**Comment by yiliuTo** [comment]
Hi @kushagraThapar , could you help to look into this issue? Thanks~

**Comment by kushagraThapar** [comment]
@abuinteam  - Instead of using `@RefreshScope` on the configuration and cosmos client builder bean, can you just refresh the key inside the `AzureKeyCredential` object reference. 
The main purpose of using `AzureKeyCredential` is that when you need to refresh the keys, just set the new keys in the same `AzureKeyCredential` object, and Cosmos SDK will automatically pick up the new keys.

**Comment by abuinteam** [comment]
Hi @kushagraThapar I will give a try on this.  

We got another rare scenario where the connection URL of the CosmosDB needs to be updated on the fly. Is there any way we can do it?

**Comment by abuinteam** [comment]
@kushagraThapar Thats right data center fail over is automatic from Azure SDK. There were scenarios such as a network outage on our end and during which we cant able to use the load balanced cosmos db URL and was particularly have to point to particular region based URL. 

So basically, we would like to see if we can achieve refreshing connections on demand without app restart, the feature supported by spring-data-cosmos https://github.com/microsoft/spring-data-cosmosdb/issues/353. Same kind of URL refresh is available part of other relational DB we are handling right now so it will be cool if it is available for CosmosDB
