### ISSUE TITLE
[QUERY] PartionOwnership contention of EventHub may have correlation of loadBalancingUpdateInterval and partitionOwnershipExpirationInterval parameters

### ISSUE THREAD

**Issue by kekatahi** [Azure/azure-sdk-for-java#20002]
**Query/Question**
Does the possibility of partition contention has correlation of loadBalancingUpdateInterval and partitionOwnershipExpirationInterval value ?

Sometimes requestedPartitionOwnerships claim the duplicate ownership to specific partition and this cause 412 stauts code. 
```
c.a.m.e.PartitionBasedLoadBalancer Starting next iteration of load balancer
c.a.m.e.PartitionBasedLoadBalancer Number of ownership records 2, number of partitions 2
c.a.m.e.PartitionBasedLoadBalancer Number of active ownership records 0
c.a.m.e.PartitionBasedLoadBalancer Attempting to claim ownership of partition 1
c.p.i.n.p.a.e.s.CacheableCheckpointStore claimOwnership called. requestedPartitionOwnerships:[{partitionId:1,ownerId:be7e7eb3-add0-44df-8638-28f4e4f17ee5,eTag:0x8D8E393D4DD22AE}{partitionId:0,ownerId:be7e7eb3-add0-44df-8638-28f4e4f17ee5,eTag:0x8D8E393D4DC5F2D}{partitionId:1,ownerId:be7e7eb3-add0-44df-8638-28f4e4f17ee5,eTag:0x8D8E393D4DD22AE}] 
c.a.m.e.PartitionBasedLoadBalancer Load balancing completed successfully
c.a.m.e.PartitionBasedLoadBalancer Successfully claimed ownership of partition 0
c.a.m.e.PartitionBasedLoadBalancer Successfully claimed ownership of partition 1
c.a.m.e.c.blob.BlobCheckpointStore Couldn't claim ownership of partition 1
com.azure.storage.blob.models.BlobStorageException: Status code 412, "?<?xml version="1.0" encoding="utf-8"?><Error><Code>ConditionNotMet</Code><Message>The condition specified using HTTP conditional header(s) is not met.
Time:2021-03-10T07:13:14.5423939Z</Message></Error>"
```
We estimate this behavior means that the partition ownership contention happen and it may be happen loadBalancingUpdateInterval and partitionOwnershipExpirationInterval reached same time. 
Furthermore I would like to confirm whether we can reduce the possibility of contention event if we tune the partitionOwnershipExpirationInterval and loadBalancingUpdateInterval .

***Why is this not a Bug or a feature Request?***
I see the LoadBalancing Strategy document and LoadBalancing Strategy minimize the contention but may not be able to avoid it. So this is not a bug I guess. 
https://docs.microsoft.com/en-us/java/api/com.azure.messaging.eventhubs.loadbalancingstrategy?view=azure-java-stable#fields

**Setup (please complete the following information if applicable):**
 - OS: Windows 10
 - Version of the Library used: azure-messaging-eventhubs:5.5.0, azure-messaging-eventhubs-checkpointstore-blob:1.5.0

**Comment by kekatahi** [comment]
@alzimmermsft  Could you please triage this query?

**Comment by alzimmermsft** [comment]
@conniey, @srnagar could you take a look?

**Comment by srnagar** [comment]
@kekatahi When there are multiple instances of EventProcessorClients running, there's always bound to be contention when the instances are starting up or re-balancing. The contention can be minimized by using the `LoadBalancingStrategy.BALANCED` strategy. 

`loadBalancingUpdateInterval` also plays a role. If the duration is small, attempts to load balance are made more frequently. 

So, when 2 instances try to claim ownership of the same partition, only one of them succeeds and the other gets the `412` error status code and this is expected.

Hope this answers your question.

**Comment by kekatahi** [comment]
@srnagar Thank you for checking.
Do you mean If the loadBalancingUpdateInterval is small, the contention frequently happen ? 
(Since the re-balance happen more frequently and it seems to increase the contention I guess)
> loadBalancingUpdateInterval also plays a role. If the duration is small, attempts to load balance are made more frequently.

**Comment by kekatahi** [comment]
@srnagar  If you have any insights, please let me know.

**Comment by srnagar** [comment]
> Do you mean If the loadBalancingUpdateInterval is small, the contention frequently happen?
The contention may or may not happen, but having a smaller interval will result in frequent attempts at load balancing and can potentially cause contention.  

Load balancing happens periodically even when the partitions are completely balanced but there is no contention in a balanced state. Contention can occur when an instance of the processor is starting up or when an instance has gone down until the balanced state is reached.

**Comment by kekatahi** [comment]
@srnagar Thank you!
