### ISSUE TITLE
[Feature Request] AAD B2C  generate user principal．

### ISSUE THREAD

**Issue by ZhuXiaoBing-cn** [Azure/azure-sdk-for-java#20007]
When I am using AAD B2C, I hope to be able to obtain the related claims of the access token through UserPrincipal. I think we should add a class similar to UserPrincipal to store the related claims carried by the access token. The implementation of this function should be similar to that implemented in AAD, so that consistency can be maintained.

Among them, we should be able to get the following:
- tokenValue
- headers
- authorities
- attributes

**Comment by ZhuXiaoBing-cn** [comment]
The PR (#20008) corresponding to this issue. Regarding the progress of this Feature, we will see more here.

**Comment by saragluna** [comment]
@ZhuXiaoBing-cn I'm re-opening this issue, for we need some test cases for the PR.

**Comment by saragluna** [comment]
Closing this issue now https://github.com/Azure/azure-sdk-for-java/pull/20189.
