### ISSUE TITLE
Regarding Azure GOV 

### ISSUE THREAD

**Issue by giridharkn** [Azure/azure-sdk-for-java#2001]
Hi,

I am working with azure java sdk to implement for azure US GOV cloud. Is just setting the Environment as 'AZURE_US_GOVERNMENT' would suffice. or any other configuration to be made to configure gov cloud. ?

credentials = new ApplicationTokenCredentials(accountInfo.clientId,
accountInfo.tenantId, accountInfo.clientSecretKey, AzureEnvironment.AZURE_US_GOVERNMENT);

Once credentials are created with the above settings, do we have to do any other configuration for Compute, networking apis for gov or just the credentials configured to US_GOV is sufficient ?

Thanks and Regards
Giridhar K N

**Comment by jianghaolu** [comment]
The short answer is yes - but you should always test it - we currently don't have direct access to the gov cloud.
