### ISSUE TITLE
Ensure compatibility of `azure-storage-blob` and `azure-cosmos`

### ISSUE THREAD

**Issue by f-paulus** [Azure/azure-sdk-for-java#20011]
Hello,

I have class not found error when using the following dependencies:
- `azure-storage-blob`: 12.10.1
- `azure-cosmos`: 4.13.0
- Spring Boot: 2.4.2

The following exception is thrown:
```
10:09:04.753 [reactor-http-epoll-7] WARN  i.n.c.AbstractChannelHandlerContext - An exception 'java.lang.NoSuchMethodError: 'java.util.List com.azure.core.http.HttpHeader.getValuesList()'' [enable DEBUG level for full stacktrace] was thrown by a user handler's exceptionCaught() method while handling the following exception:
java.lang.NoSuchMethodError: 'java.util.List com.azure.core.http.HttpHeader.getValuesList()'
	at com.azure.core.http.netty.NettyAsyncHttpClient.lambda$bodySendDelegate$2(NettyAsyncHttpClient.java:116)
	at reactor.netty.http.client.HttpClientConnect$HttpClientHandler.requestWithBody(HttpClientConnect.java:556)
	at reactor.netty.http.client.HttpClientConnect$HttpIOHandlerObserver.lambda$onStateChange$0(HttpClientConnect.java:398)
	at reactor.core.publisher.MonoDefer.subscribe(MonoDefer.java:44)
	at reactor.core.publisher.InternalMonoOperator.subscribe(InternalMonoOperator.java:64)
...
```

As one can see, the problems seems to be that `NettyAsyncHttpClient` from `azure-core-http-netty:1.9.0` makes a call to `HttpHeader` from `azure-core:1.12.0`. `azure-storage-blob` brings this old dependency of `azure-core`. Manually overwriting the version of `azure-core` to 1.14.0 did not work, either.

Please provide a set of versions that is compatible to be used together. Otherwise we are blocked to update to the newest version of `azure-cosmos` which then again blocks us to use Spring Boot 2.4.X.

**Comment by rickle-msft** [comment]
Thanks, @f-paulus for opening this issue. @alzimmermsft do you know of any two versions of these packages that are compatible with each other?

**Comment by alzimmermsft** [comment]
@f-paulus, when configuring to use `azure-core` `1.14.0` what issue was seen? A newer version, `1.14.1`, was shipped to resolve an issue when using Spring Framework `2.4.x` and I just wanted to verify is this was another new issue.

**Comment by f-paulus** [comment]
Thanks a lot for following up!

@alzimmermsft When configuring to use `azure-core:1.14.0` I see the following issue at startup:
```
***************************
APPLICATION FAILED TO START
***************************

Description:

An attempt was made to call a method that does not exist. The attempt was made from the following location:

    com.azure.core.util.serializer.JacksonAdapter.<init>(JacksonAdapter.java:106)

The following method did not exist:

    'com.fasterxml.jackson.databind.cfg.MutableCoercionConfig com.fasterxml.jackson.databind.ObjectMapper.coercionConfigDefaults()'

The method's class, com.fasterxml.jackson.databind.ObjectMapper, is available from the following locations:

    jar:file:/home/fpaulus/.m2/repository/com/fasterxml/jackson/core/jackson-databind/2.11.4/jackson-databind-2.11.4.jar!/com/fasterxml/jackson/databind/ObjectMapper.class

The class hierarchy was loaded from the following locations:

    com.fasterxml.jackson.databind.ObjectMapper: file:/home/fpaulus/.m2/repository/com/fasterxml/jackson/core/jackson-databind/2.11.4/jackson-databind-2.11.4.jar
    com.fasterxml.jackson.core.ObjectCodec: file:/home/fpaulus/.m2/repository/com/fasterxml/jackson/core/jackson-core/2.11.4/jackson-core-2.11.4.jar
    com.fasterxml.jackson.core.TreeCodec: file:/home/fpaulus/.m2/repository/com/fasterxml/jackson/core/jackson-core/2.11.4/jackson-core-2.11.4.jar


Action:

Correct the classpath of your application so that it contains a single, compatible version of com.fasterxml.jackson.databind.ObjectMapper
```

When configuring to use `azure-core:1.14.1` it's the following one:
```
***************************
APPLICATION FAILED TO START
***************************

Description:

A component required a bean named 'reactorClientResourceFactory' that could not be found.


Action:

Consider defining a bean named 'reactorClientResourceFactory' in your configuration.
```

**Comment by alzimmermsft** [comment]
Okay, so the issue seen when using `1.14.0` was the one fixed in `1.14.1`, that's good. But, I've never seen the exception you're getting with `1.14.1`. Based on the naming of the missing bean, `reactorClientResourceFactory`, this leads me towards dependency resolution with Reactor Netty. Is Reactor Netty being resolved to `1.0.x`, preferable `1.0.3` or later?

**Comment by f-paulus** [comment]
I checked it, `reactor-netty` is resolved to `1.0.3`.

**Comment by f-paulus** [comment]
My fault, this last problem was on our side.

But if we manually set `azure-core` to `1.14.1` and build the project and run the maven enforcer, we now get the following error:
```
Dependency convergence error for com.azure:azure-storage-common:12.10.1 paths to dependency are:
+-<<<our project>>>:1.1.6-SNAPSHOT
  +-com.azure:azure-storage-blob:12.10.1
    +-com.azure:azure-storage-common:12.10.1
and
+-<<<our project>>>:1.1.6-SNAPSHOT
  +-com.azure:azure-storage-blob:12.10.1
    +-com.azure:azure-storage-internal-avro:12.0.2
      +-com.azure:azure-storage-common:12.10.0
```
I guess something is not yet aligned.

**Comment by alzimmermsft** [comment]
@f-paulus, that is correct that not all latest Storage libraries resolve to the same version of `azure-storage-common`. There was a hotfix released by @gapra-msft for `azure-storage-common`, `azure-storage-blob`, and `azure-storage-file-datalake`. For this instance given both resolve to the same major.minor, `12.10.x`, it is safe that they don't resolve to the same version, and it resolving to `12.10.1` is actually better as it'll get the hotfix.

**Comment by f-paulus** [comment]
@alzimmermsft Thanks for the answer that it is no problem to set the version to `12.10.1`. I get another convergence error:
```
Dependency convergence error for com.azure:azure-core-http-netty:1.7.1 paths to dependency are:
+-<<<our project>>>:1.1.6-SNAPSHOT
  +-<<<our project-2>>>:1.1.6-SNAPSHOT
    +-com.azure:azure-storage-blob:12.10.1
      +-com.azure:azure-storage-common:12.10.1
        +-com.azure:azure-core-http-netty:1.7.1
and
+-<<<our project>>>:1.1.6-SNAPSHOT
  +-com.azure:azure-cosmos:4.13.1
    +-com.azure:azure-core-http-netty:1.9.0
```
It works if I set it manually to `1.9.0`, is this okay from your side?

**Comment by alzimmermsft** [comment]
Yes, upgrading `azure-core-http-netty` to `1.9.0` from `1.7.1` used in the latest GA Storage Blobs is backwards compatible. So, making this change is safe and should resolve the convergence issue.

**Comment by f-paulus** [comment]
Okay thanks! We now have three special cases in our pom with setting the versions of `azure-core`, `azure-storage-common` and `azure-core-http-netty` manually. It would be great we could remove those soon :)

**Comment by alzimmermsft** [comment]
@f-paulus, I'll update this issue once we have a GA set of Cosmos, Core, and Storage which are resolving to the same dependencies.

**Comment by f-paulus** [comment]
@alzimmermsft Thanks a lot!

But I have to report another (maybe related) problem. We updated from Spring Boot 2.4.2 to 2.4.4. When initializing the database on startup we run into the following exception:
```
Caused by: java.lang.ClassCastException: class reactor.core.publisher.MonoSingle$SingleSubscriber cannot be cast to class reactor.core.Fuseable$QueueSubscription (reactor.core.publisher.MonoSingle$SingleSubscriber and reactor.core.Fuseable$QueueSubscription are in unnamed module of loader 'app')
	at reactor.core.publisher.FluxPeekFuseable$PeekFuseableConditionalSubscriber.onSubscribe(FluxPeekFuseable.java:470)
	at reactor.core.publisher.MonoSingle$SingleSubscriber.onSubscribe(MonoSingle.java:115)
	at reactor.core.publisher.FluxMap$MapSubscriber.onSubscribe(FluxMap.java:92)
	at reactor.core.publisher.SerializedSubscriber.onSubscribe(SerializedSubscriber.java:65)
	at reactor.core.publisher.FluxRetryWhen.subscribe(FluxRetryWhen.java:63)
	at reactor.core.publisher.MonoRetryWhen.subscribeOrReturn(MonoRetryWhen.java:46)
	at reactor.core.publisher.InternalMonoOperator.subscribe(InternalMonoOperator.java:57)
	at reactor.core.publisher.MonoDeferContextual.subscribe(MonoDeferContextual.java:55)
	at reactor.core.publisher.Mono.subscribe(Mono.java:4099)
	at reactor.core.publisher.Mono.block(Mono.java:1702)
	at com.azure.cosmos.CosmosClient.blockDatabaseResponse(CosmosClient.java:140)
	at com.azure.cosmos.CosmosClient.createDatabaseIfNotExists(CosmosClient.java:55)
	at <<<our project>>>
```

**Comment by alzimmermsft** [comment]
@f-paulus, this is related to this [issue](https://github.com/reactor/reactor-core/issues/2663) in Reactor.

**Comment by f-paulus** [comment]
@alzimmermsft Thanks, then let's check again after `reactor-core` version `3.3.16.RELEASE` was released.

**Comment by f-paulus** [comment]
@alzimmermsft Version `3.4.5` of `reactor-core` is released now, which solves our problem if manually set.

So we have a working project if we manually set the version of `reactor-core` and of the three azure dependencies as talked about above. We will use it like this on production till you ping us as discussed.

**Comment by alzimmermsft** [comment]
@f-paulus, thank you for letting me know about the recent releases of `reactor-core` resolving this issue.

I'll work on upgrading our dependency to this latest version and it should be available in the next release of the SDKs.

**Comment by f-paulus** [comment]
@alzimmermsft Any news here?

**Comment by alzimmermsft** [comment]
Thank you for the ping @f-paulus. Yes, there is an update, on May 13th/14th there were new releases of `azure-cosmos`, [`4.15.0`](https://mvnrepository.com/artifact/com.azure/azure-cosmos/4.15.0), and `azure-storage-blob`, [`12.11.1`](https://mvnrepository.com/artifact/com.azure/azure-storage-blob/12.11.1), which have consistent dependency alignment.

**Comment by alzimmermsft** [comment]
Closing as [azure-sdk-bom 1.0.3](https://search.maven.org/artifact/com.azure/azure-sdk-bom/1.0.3/pom) has been released with the versions mentioned above. For more information about `azure-sdk-bom` and how to use it please see [this documentation](https://github.com/Azure/azure-sdk-for-java/blob/master/sdk/boms/azure-sdk-bom/README.md).
