### ISSUE TITLE
channelAcquisition takes more than 5s

### ISSUE THREAD

**Issue by xinlian12** [Azure/azure-sdk-for-java#20021]
"exception": "failed to establish connection to custaccount-prod-azure-cosmosdb-westus.documents.azure.com:11413 due to java.nio.channels.ClosedChannelException",
			"transportRequestTimeline": [{
				"eventName": "created",
				"durationInMicroSec": "0",
				"startTime": "2021-03-19T23:23:54.956Z"
			}, {
				"eventName": "queued",
				"durationInMicroSec": "0",
				"startTime": "2021-03-19T23:23:54.956Z"
			}, {
				**"eventName": "channelAcquisitionStarted",
				"durationInMicroSec": "178793000",
				"startTime": "2021-03-19T23:23:54.956Z"**
			}, {

ChannelAcquisition should timed out after 5s.

**Comment by kushagraThapar** [comment]
This is done.
