### ISSUE TITLE
We are experiencing Timeout out exception and communication exception for some specific EventHub while sending messages to EventHub from the upstream application

### ISSUE THREAD

**Issue by koustavnaharoy-ayla** [Azure/azure-sdk-for-java#20044]
**Query/Question**
We are experiencing Timeout out exception and communication exception for some specific EventHub while sending messages to EventHub from the upstream application

***Why is this not a Bug or a feature Request?***
A clear explanation of why is this not a bug or a feature request?
We are getting com.microsoft.azure.eventhubs.TimeoutException and com.microsoft.azure.eventhubs.CommunicationException multiple times.
 
Pls find the full exception details below for com.microsoft.azure.eventhubs.TimeoutException
**Send operation timed out at 2021-03-17T23:15:39.550Z[Etc/UTC]., errorContext[NS: ehubnsprod0202-AylaDss.servicebus.windows.net, PATH: dssv2-in, REFERENCE_ID: 9b700c8d56184d87a0b38ffb97127327_G19, LINK_CREDIT: 154]**

Pls find the full exception details below for com.microsoft.azure.eventhubs.CommunicationException
**Connection reset by peer, errorContext[NS: ehubnsprod0202-AylaDss.servicebus.windows.net, PATH: dssv2-in, REFERENCE_ID: e77bb81d36014b1e9ab51f5d583957d8_G22, LINK_CREDIT: 201]**

**Setup (please complete the following information if applicable):**
 - OS: Kubenetes
 - IDE : IntelliJ
 - Version of the Library used 5.3.1
 
 **Information Checklist**
 Kindly make sure that you have added all the following information above and checkoff the required fields otherwise we will treat the issuer as an incomplete report
- [x] Query Added
- [x] Setup information Added

**Comment by joshfree** [comment]
@conniey could you please take a look

**Comment by manashray-ayla** [comment]
@conniey - This is super critical for us as this is impacting the real productive customers and I don't see any traction on this.I can really empathize with the customers why they are getting frustrated w.r.t. this timeout exceptions as this is impacting the latency to their flow.

Could you take a stab at it and let us know the potential reasons.

Regards,
Manash

**Comment by conniey** [comment]
@manashray-ayla `com.microsoft.azure.eventhubs.TimeoutException` suggests that the library is from the earlier Event Hubs client library. Do you have a repro for this? The exception itself without a stack trace or code we can't further investigate.

/cc @JamesBirdsall

**Comment by JamesBirdsall** [comment]
@manashray-ayla Can you confirm what version of the client you are using? The exceptions you report would come from a 3.x version of the client but the original problem report says 5.3.1. Thanks!

**Comment by manashray-ayla** [comment]
@Koustav ***@***.***> – Can you provide the version details.

Regards,
Manash
From: JamesBirdsall ***@***.***>
Reply to: Azure/azure-sdk-for-java ***@***.***>
Date: Thursday, 29 April 2021 at 2:47 AM
To: Azure/azure-sdk-for-java ***@***.***>
Cc: Manash Ray ***@***.***>, Mention ***@***.***>
Subject: Re: [Azure/azure-sdk-for-java] We are experiencing Timeout out exception and communication exception for some specific EventHub while sending messages to EventHub from the upstream application (#20044)


@manashray-ayla<https://github.com/manashray-ayla> Can you confirm what version of the client you are using? The exceptions you report would come from a 3.x version of the client but the original problem report says 5.3.1. Thanks!

**Comment by koustavnaharoy-ayla** [comment]
Hi All,

Exception come from 5.3.1 version,  after that as Microsoft suggested we moved to 5.7.0.

Thanks,
Koustav

From: manashray-ayla ***@***.***>
Date: Friday, 30 April 2021 at 2:11 AM
To: Azure/azure-sdk-for-java ***@***.***>
Cc: Koustav Roy ***@***.***>, Author ***@***.***>
Subject: Re: [Azure/azure-sdk-for-java] We are experiencing Timeout out exception and communication exception for some specific EventHub while sending messages to EventHub from the upstream application (#20044)
@Koustav ***@***.***> – Can you provide the version details.

Regards,
Manash
From: JamesBirdsall ***@***.***>
Reply to: Azure/azure-sdk-for-java ***@***.***>
Date: Thursday, 29 April 2021 at 2:47 AM
To: Azure/azure-sdk-for-java ***@***.***>
Cc: Manash Ray ***@***.***>, Mention ***@***.***>
Subject: Re: [Azure/azure-sdk-for-java] We are experiencing Timeout out exception and communication exception for some specific EventHub while sending messages to EventHub from the upstream application (#20044)


@manashray-ayla<https://github.com/manashray-ayla> Can you confirm what version of the client you are using? The exceptions you report would come from a 3.x version of the client but the original problem report says 5.3.1. Thanks!
