### ISSUE TITLE
(cosmos) @Query not working with list

### ISSUE THREAD

**Issue by loudywen** [Azure/azure-sdk-for-java#20074]
```
        <dependency>
            <groupId>com.azure</groupId>
            <artifactId>azure-spring-data-cosmos</artifactId>
            <version>3.5.0</version>
        </dependency>
```

Below is the Query I use, but it returns empty results,
```
  @Query(value = "SELECT * FROM r "
               + "WHERE ( r.environmentCode = @environmentCode) "
               + "AND (@hopDistinctName = null or r.hopDistinctName IN (@hopDistinctName)) "
              )
     Page<ExceptionTransaction> findAllExceptionTransaction(
               @Param("environmentCode") Integer environmentCode,
               @Param("hopDistinctName") List<String> hopDistinctNames,
               Pageable pageable);
```
I am using `@hopDistinctName = null or r.hopDistinctName IN (@hopDistinctName` to ignore `null` value.

And with this SQL statement, I am able to get the results:
```
SELECT * FROM c WHERE c.environmentCode = 100 
AND c.hopDistinctName IN  ("Response Transformation")
```
Anything wrong with my `@Query`?

Is there any way I can log the actual SQL statement?

This is the logging from SqlQuerySpecLogger:
```
2021-03-23 22:28:56,940 DEBUG [http-nio-8080-exec-8] com.azure.cosmos.implementation.SqlQuerySpecLogger  logQuery - select * from (SELECT * FROM r WHERE ( r.environmentCode = @environmentCode) AND (r.countryCode = @countryCode) AND (r.instanceTypeCode = @instanceTypeCode) AND (r.scenarioName = @scenarioName) AND (@hopUuid = null or r.hopUuid = @hopUuid) AND (@hopType = null or r.hopType = @hopType) AND (@originalMessageId = null or r.originalMessageId = @originalMessageId) AND (@testFlag = null or r.testFlag = @testFlag) AND (@replayBatchId = null or r.replayBatchId = @replayBatchId) AND (@hopDistinctName = null or r.hopDistinctName IN (@hopDistinctName)) AND (r.messageTimestamp BETWEEN @rangeStart AND @rangeEnd) ) r ORDER BY r.messageTimestamp ASC > param: @environmentCode = 100 > param: @countryCode = US > param: @instanceTypeCode = 1 > param: @scenarioName = ESB1424_SAPS4_CILL > param: @hopUuid = null > param: @hopType = null > param: @originalMessageId = null > param: @testFlag = false > param: @rangeStart = 2021-02-10T22:03:48.802Z > param: @rangeEnd = 2021-02-10T23:59:59.999Z > param: @replayBatchId = null > param: @replayStatus = null > param: @errorCode = null > param: @hopDistinctName = ["Response Transformation"]   
```

**Comment by loudywen** [comment]
@kushagraThapar would you please answer this?

**Comment by kushagraThapar** [comment]
@mbhaskar  - can you please help the customer here with query annotations ?

**Comment by loudywen** [comment]
ya, @mbhaskar  please help

**Comment by loudywen** [comment]
@mbhaskar will you have time to take a look at this issue?

**Comment by mbhaskar** [comment]
@loudywen do you get results when you remove this ```@hopDistinctName = null or ``` from the annotated query?

**Comment by loudywen** [comment]
@mbhaskar  I do get results after removed `@hopDistinctName = null`

But with this SQL statement I am able to get results:
```
SELECT * FROM c WHERE c.environmentCode = 100 
AND c.hopDistinctName IN  ("Response Transformation")
```

**Comment by loudywen** [comment]
@mbhaskar  have you been facing the same issue?

**Comment by loudywen** [comment]
@chenrujun  @saragluna @mbhaskar  hi is any progress for this one?

**Comment by loudywen** [comment]
I think because it is not building the content of the IN properly.
Since if I use this  `     @Query(value = "SELECT * FROM c WHERE c.environmentCode = 100 and c.hopDistinctName IN (\"test\")")
     List<AuditTransaction> findAllAuditCustom4();` without the parameter place holder in the query, I am able to get the data

**Comment by loudywen** [comment]
Also if i change the 
```
  @Query(value = "SELECT * FROM r "
               + "WHERE ( r.environmentCode = @environmentCode) "
               + "AND (@hopDistinctName = null or r.hopDistinctName IN (@hopDistinctName)) "
              )
     Page<ExceptionTransaction> findAllExceptionTransaction(
               @Param("environmentCode") Integer environmentCode,
               @Param("hopDistinctName") List<String> hopDistinctNames,
               Pageable pageable);
```
 the `List<String>` to `String `then it will work

**Comment by saragluna** [comment]
FYI @backwind1233.

**Comment by loudywen** [comment]
Since the `@Query` for `IN` is not working, can someone tell me how can I build the `Criteria` for the below SQL statement:
```
select *
from auditTransaction
where EXISTS(
        SELECT *
        FROM n IN auditTransaction.businessIdentifiers
        WHERE n.data IN ("hi")
    )

```

**Comment by backwind1233** [comment]
@ZhuXiaoBing-cn would you please take a look at it?

**Comment by ZhuXiaoBing-cn** [comment]
Hi, @loudywen, I found that the client doesn't support making list `SqlParameter` that could be used for in clauses: [Azure/azure-cosmosdb-java#60.](https://github.com/Azure/azure-cosmosdb-java/issues/60#issuecomment-415457653)

Here are some practices for reference:
 
- You can try something like this:
```
String query = "SELECT * from c where c.prop IN (@param1, @param2)";
SqlParameterCollection params = new SqlParameterCollection(new SqlParameter("@param1", 98), new SqlParameter("@param2", 99));
SqlQuerySpec sqs = new SqlQuerySpec(query, params);
```
- https://github.com/ankagrawal/ambry/blob/f72d240e13f1911e3abfdebec5df7e405b878b67/ambry-cloud/src/main/java/com.github.ambry.cloud/azure/AzureCloudDestination.java#L320-L321
```
list.stream().map(s -> '"' + s + '"').collect(Collectors.joining(","));
```

**Comment by viswa-optimusprime** [comment]
@All is this closed ? What is solution to pass the list as parameter?


	private SqlQuerySpec getQuery(List<Integer> namesList) {
		ArrayList<SqlParameter> paramList = new ArrayList<SqlParameter>();
        paramList.add(new SqlParameter("@names", namesList));
        SqlQuerySpec querySpec = new SqlQuerySpec(
                "SELECT * FROM Test t WHERE t.name in(@names)",
                paramList);
        return querySpec;
	}

**Comment by ZhuXiaoBing-cn** [comment]
@viswa-optimusprime For `List` parameters, the current practice is to convert `List` to `String`.

`list.stream().map(s -> '"' + s + '"').collect(Collectors.joining(","));`

**Comment by rajesh-melige** [comment]
@mbhaskar , @backwind1233 : I'm sorry if this is unrelated question on this issue. 
I wanted to know the maximum number of parameters we can pass to the IN clause in cosmos.
Could you please help with a number so that I can handle the bottlenecks in my project.
Thanks!

**Comment by backwind1233** [comment]
@xinlian12 could you help review this issue?

**Comment by kushagraThapar** [comment]
@rajesh-melige  - I don't think there is any limit to no. of parameters in `IN clause ` - https://docs.microsoft.com/en-us/azure/cosmos-db/sql/sql-query-keywords#in
But I guess, the more params you pass, the slower will be the query, because then it would need to filter more.

**Comment by MuktiyarShaik** [comment]
private SqlQuerySpec getQuery(List<Integer> namesList) {
	ArrayList<SqlParameter> paramList = new ArrayList<SqlParameter>();
    paramList.add(new SqlParameter("@names", namesList.stream().collect(Collectors.joining("','", "'", "'"))));
    SqlQuerySpec querySpec = new SqlQuerySpec(
            "SELECT * FROM Test t WHERE t.name in(@names)",
            paramList);
    return querySpec;
}
