### ISSUE TITLE
Support for batch-consumers in Service Bus and Event Hub binders

### ISSUE THREAD

**Issue by avpines** [Azure/azure-sdk-for-java#20080]
**Is your feature request related to a problem? Please describe.**
According to Spring Cloud Stream's documentation, a binder implementation [may support batch consumers](https://docs.spring.io/spring-cloud-stream/docs/3.1.2/reference/html/spring-cloud-stream.html#_batch_consumers). Currently both the Event-Hub and Service Bus binders do not support it. 

This feature is a blocker for several teams in our group which will not be able to use Spring Cloud Stream otherwise. Since we already use Spring Cloud Stream (For both Event Hub and Service Bus), we would like the these teams to be able to use it as well.

**Describe the solution you'd like**
Implementation of the batch-consumers feature as described in the Spring Cloud Stream documentation. 

**Describe alternatives you've considered**
Any alternative means either not using Spring Cloud Stream or not using Event Hub/Service Bus binders. 

**Information Checklist**
Kindly make sure that you have added all the following information above and checkoff the required fields otherwise we will treat the issuer as an incomplete report
- [x] Description Added
- [x] Expected solution specified

**Comment by michaelqi793** [comment]
Hi, @avpines ,
Would you like to run the sample azure-spring-cloud-sample-servicebus-queue-binder with the following codes:
```
public class Person {
    private String name;
    private int age;

    public Person () {

    }
    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public int getAge() {
        return age;
    }

    public void setAge(int age) {
        this.age = age;
    }

    @Override
    public String toString(){
        return name + " " + age;
    }
}
```
```
public class ServiceProducerConfiguration {

    private static final Logger LOGGER = LoggerFactory.getLogger(ServiceBusQueueBinderApplication.class);

    private int i = 0;

    @Bean
    public Supplier<List<Person>> supply() {
        return () -> {
            LOGGER.info("Sending message, sequence " + i);
            List<Person> list = new ArrayList<>();
            Person ps  = new Person();
            int j = i ++;
            ps.setName("psname" + j);
            ps.setAge(j);
            list.add(ps);
            ps  = new Person();
            j = i ++;
            ps.setName("psname" + j);
            ps.setAge(j);
            list.add(ps);
            return list;
        };
    }
}
```
```
@SpringBootApplication
public class ServiceBusQueueBinderApplication {

    private static final Logger LOGGER = LoggerFactory.getLogger(ServiceBusQueueBinderApplication.class);

    public static void main(String[] args) {
        SpringApplication.run(ServiceBusQueueBinderApplication.class, args);
    }

   @Bean
   public Consumer<List<Person>> consume() {
       return message -> {
           LOGGER.info("I'm in batch consumer. New message received: '{}'", message);
           message.forEach(System.out::println);
           
       };
   }
}

```
I'm not sure whether this is the use case you desire. Or, in your application you can't control how the messages are sent, but you want to consume them batch by batch.

Regards!
Michael

**Comment by saragluna** [comment]
The Event Hubs batch consumer has been implemented in https://github.com/Azure/azure-sdk-for-java/pull/24819 and https://github.com/Azure/azure-sdk-for-java/pull/25363, the Service Bus batch consumer is still in our backlog https://github.com/Azure/azure-sdk-for-java/issues/21545.

**Comment by yiliuTo** [comment]
Hi @avpines , since batch-consumer for EH has been supported while SB not, I would like to close this issue and use https://github.com/Azure/azure-sdk-for-java/issues/21545 to track the request for SB batch-consumer. Please re-open if you have any other questions.
