### ISSUE TITLE
Azure Database Threat Detection Policies API available in SDK?

### ISSUE THREAD

**Issue by jatins** [Azure/azure-sdk-for-java#2011]
I am interested in using this API:
https://docs.microsoft.com/en-us/rest/api/sql/databasethreatdetectionpolicies/get

Is this available via SDK?

Also, in _general_ what is a good way to figure out is a particular API is available in SDK. Currently, I press `Ctrl + Space` and judge from autocomplete suggestions which isn't very, umm, scientific. 

. . .
<sub>kinda unrelated but</sub>
~**the docs say the API returns JSON, but actually hitting the API gets me an XML response. Is that expected?**~ Setting `Accept: application/json` header gets you json.

**Comment by milismsft** [comment]
SQL databases threat detection policies support is available in version 1.7 of the Azure management Java libraries.
