### ISSUE TITLE
Retrieving the Diagnostics Storage account for an Azure SQL Database

### ISSUE THREAD

**Issue by ShailashreeE** [Azure/azure-sdk-for-java#2012]
Looking for a way to get the Storage account which stores the diagnostics data for an Azure SQL Database.

We have added a diagnostic setting to an Azure SQL Database to archive its metrics to a Storage account as shown below.

<img width="953" alt="screenshot 185" src="https://user-images.githubusercontent.com/28895501/35213121-8ab5674c-ff82-11e7-9a71-c30e76a8b8dc.png">

Using Azure sdk for java, we would like to get the storage account name into which the metrics are archived.
Please provide us with a solution for doing the same.

**Comment by aamalvea** [comment]
We are sorry that we couldn't answer this question sooner. Here is a blog that introduces managing Azure Monitor using Java: https://azure.microsoft.com/en-us/blog/manage-azure-monitor-using-java/ and here is a link to the GitHub repo: https://github.com/azure/azure-libraries-for-java

This page may contain what you're looking for: https://github.com/Azure/azure-libraries-for-java/blob/master/azure-mgmt-monitor/src/main/java/com/microsoft/azure/management/monitor/DiagnosticSetting.java
