### ISSUE TITLE
Resource Group name case insensitive in Disk IDs.

### ISSUE THREAD

**Issue by Akshata17** [Azure/azure-sdk-for-java#2014]
The case of resource group names in IDs of disks are case insensitive. 
Steps to reproduce this issue -
1. Create a standalone disk in Azure, check for ID. For eg - 
 "/subscriptions/subscriptionID/resourceGroups/**diskRG1**/providers/Microsoft.Compute/disks/TestVM_disk2" . Notice the case of resource group name -> "**diskRG1**".

2. Create a VM.

3. Attach the disk created disk (in step 1) to VM.

4. Go to newly created VM->Disks-> Check for the attached Disk ID and it displays as ->  "/subscriptions/subscriptionID/resourceGroups/**DISKRG1**/providers/Microsoft.Compute/disks/TestVM_disk2" . Now the resource group name has changed to **DISKRG1**.

IDs of disk should be same and case sensitive.

**Comment by Akshata17** [comment]
@anuchandy  I think that this was service side bug. Can you please provide a ETA on when it  would be fix or where I can track its progress. Its happening with other resource on Azure as well like VMs and the case for the resource group changes.

**Comment by Akshata17** [comment]
@daschult  Can you please let me know when can I get a fix for this issue ? Thanks

**Comment by Drewm3** [comment]
Cleaning up old issues from 2016 - 2018. Please reopen this issue if it is still a concern.
