### ISSUE TITLE
[BUG] Cannot remove replyUrl from AAD application

### ISSUE THREAD

**Issue by SirNeo** [Azure/azure-sdk-for-java#20161]
**Describe the bug**
I try to remove a reply url from an application. Adding works great. But I cant remove one. It does not fail so there is no exception. It simply does nothing. Sometimes, the first attempts, the reply url is removed and later it doesn't work.

***Exception or Stack Trace***
No exception.

**To Reproduce**
Remove a Reply URL.

***Code Snippet***
`
		ActiveDirectoryApplication activeDirectoryApplication = authenticated
				.accessManagement()
				.activeDirectoryApplications()
				.getByName(appName);
		
		activeDirectoryApplication
			.update()
			.withoutReplyUrl(url)
			.apply();
`

**Expected behavior**
The Reply URL should be removed from the AAD application.

**Screenshots**
N/A

**Setup (please complete the following information):**
N/A

**Additional context**
I tested to add and remove reply url from azure-cli too and it works fine always.

**Comment by joshfree** [comment]
@yungezz could you please take a look

**Comment by yungezz** [comment]
thanks @joshfree . Add @weidongxu-microsoft to help.

**Comment by weidongxu-microsoft** [comment]
Which SDK version?

**Comment by SirNeo** [comment]
1.36.3

`<dependency>
	<groupId>com.microsoft.azure</groupId>
	<artifactId>azure</artifactId>
	<version>1.36.3</version>
</dependency>`

**Comment by weidongxu-microsoft** [comment]
The recommended lib to manage AAD is https://github.com/microsoftgraph/msgraph-sdk-java.
