### ISSUE TITLE
[May 2021] Release azure-sdk-bom

### ISSUE THREAD

**Issue by alzimmermsft** [Azure/azure-sdk-for-java#20165]
Tracking issue to release the `azure-sdk-bom` in May 2021.

**Comment by joshfree** [comment]
@alzimmermsft can this old issue be closed out now?

**Comment by alzimmermsft** [comment]
Closing with the release of [azure-sdk-bom 1.0.3](https://search.maven.org/artifact/com.azure/azure-sdk-bom/1.0.3/pom)
