### ISSUE TITLE
[August 2021] Release azure-sdk-bom & publish the bom roadmap (blog update)

### ISSUE THREAD

**Issue by alzimmermsft** [Azure/azure-sdk-for-java#20168]
Tracking issue to release the `azure-sdk-bom` in August 2021.

**Comment by joshfree** [comment]
Please also plan to publish a blog update with the bom release, which documents the bom releases for 2021, the cadence for 2022, and soliciting community feedback on the bom and cadence.

**Comment by alzimmermsft** [comment]
Addressed by https://devblogs.microsoft.com/azure-sdk/announcing-a-faster-release-cadence-for-the-azure-client-sdk-bom-for-java/
