### ISSUE TITLE
Vhd copy across storage account is very slow

### ISSUE THREAD

**Issue by gogtesuyash** [Azure/azure-sdk-for-java#2018]
Hi,

I am trying to copy VHD from one storage account to another , in same region and same subscription. VHD size is approximately 40 GB. It's taking 15-20 mins in westus.

BlobRequestOptions options = new BlobRequestOptions();
options.setTimeoutIntervalInMs(10*1000);
options.setConcurrentRequestCount(100);
options.setSingleBlobPutThresholdInBytes(Constants.MB *64);
blob.startCopy(new URI(copyFromURL), null , null , options, null);

I also tried setting options to CloudBlobClient. But I could see that , even setting up these options is not making any difference.

**Comment by zhusijia26** [comment]
Close the issue due to idle time. Please reopen if there is still question.
