### ISSUE TITLE
Southeast Asia region naming inconsistency

### ISSUE THREAD

**Issue by pdarvasi** [Azure/azure-sdk-for-java#2019]
We are fetching the regions with Java SDK where Southeast Asia is returned as 
["South East Asia"](https://github.com/Azure/azure-sdk-for-java/blob/master/archive/azure-mgmt-resources/src/main/java/com/microsoft/azure/management/resources/fluentcore/arm/Region.java#L48).
In the meantime we are using Azure CLI  (v2.0.26) as well, which returns the region name "Southeast Asia":
![image](https://user-images.githubusercontent.com/19725708/36158207-07fee20e-10dc-11e8-9186-c0318cdfc20c.png)

The two does not match, causing error in our application.

**Comment by yungezz** [comment]
hi @xccc-msft could you pls confirm this is service issue? or Azure CLI did some normalization. thanks.

**Comment by xccc-msft** [comment]
@pdarvasi This is the label set from [SDK](https://github.com/Azure/azure-libraries-for-java/blob/master/azure-mgmt-resources/src/main/java/com/microsoft/azure/management/resources/fluentcore/arm/Region.java#L56). The value we send to server is `southeastasia`, which is the same as Azure CLI.

**Comment by xccc-msft** [comment]
@pdarvasi You should be able to get same value `southeastasia` if you select the `name` of regions both Java and Azure CLI. Please feel free to reopen if you still have any questions.
