### ISSUE TITLE
Normalize com.azure.identity.AzureCliCredential and com.microsoft.azure.credentials.AzureCliCredentials

### ISSUE THREAD

**Issue by blacelle** [Azure/azure-sdk-for-java#20194]
**Is your feature request related to a problem? Please describe.**
`com.microsoft.azure.credentials.AzureCliCredentials` enables relying in an IDE over credentials previously configured through a previous `az login` command and stored into accessTokens.json files. It enables some sort of offline authentication. It requires executing `az login` manually and regularly (fine with me).

`com.azure.identity.AzureCliCredential` will re-execute an `az ...` command, and will not rely on an `accessTokens.json` file. It then regenerates a token on each JVM run.

This lead to issues in my case due to Enterprise proxy:

```
$ az account get-access-token --output json --resource https://vault.azure.net
HTTPSConnectionPool(host='login.microsoftonline.com', port=443): Max retries exceeded with url: /XXX/oauth2/token (Caused by SSLError(SSLCertVerificationError
(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1123)')))
Certificate verification failed. This typically happens when using Azure CLI behind a proxy that intercepts traffic with a self-signed certificate. Please add this certificate to the trusted
CA bundle. More info: https://docs.microsoft.com/cli/azure/use-cli-effectively#work-behind-a-proxy.

```

**Describe the solution you'd like**
A would like to be able to rely over an offline CLI token with KeyVault just like I can rely on such a token for AzureManagement:

```
		com.microsoft.azure.credentials.AzureCliCredentials credentials;
		try {
			credentials = com.microsoft.azure.credentials.AzureCliCredentials.create();
		} catch (IOException e) {
			throw new UncheckedIOException(e);
		}

		Azure azureManagement = AzureClientFactory.makeNativeClient("subscriptionId", credentials);

		HttpClient httpClient = new NettyAsyncHttpClientBuilder()
				.proxy(ProxyOptions.fromConfiguration(Configuration.getGlobalConfiguration())).build();
		final com.azure.core.credential.TokenCredential kvTokenCredentials = new com.azure.identity.AzureCliCredentialBuilder()
				.httpClient(httpClient).build();
		final SecretClient secretClient = new SecretClientBuilder()
				.vaultUrl("https://" + "someVaultName" + ".vault.azure.net/").credential(kvTokenCredentials)
				.httpLogOptions(new HttpLogOptions().setApplicationId(SPRINGBOOT_KEY_VAULT_APPLICATION_ID))
				.buildClient();
```

**Comment by g2vinay** [comment]
@blacelle 
Thank you for posting this request.
With an offline token residing on the File System, I see the challenge of refreshing it on demand.
I can provide implementation as a sample and the implementation will have to live in your codebase for now.

@schaabs is this something we plan to add to Azure CLI credential ?

**Comment by blacelle** [comment]
> With an offline token residing on the File System, I see the challenge of refreshing it on demand.

In given context, I'm very fine with a token needing refresh on demand. 

About Azure CLI credential hitting a proxy issue while 'az login' has no proxy issue, I wonder if `az account get-access-token --output json --resource https://vault.azure.net` encounters some sort of bug related to proxy.

**Comment by g2vinay** [comment]
@blacelle 
Upon further digging, 
we found out that the Azure CLI team will be dropping the support for the Access Token persisted on the file system.
Consequently, we won't be adding the support for it in the Track 2 Azure CLI credential.
