### ISSUE TITLE
[BUG] Can't change userNameAttributeName for azure sso

### ISSUE THREAD

**Issue by j0nathan33** [Azure/azure-sdk-for-java#20209]
**Describe the bug**
I try to change value of userNameAttributeName in my application.yml and value is not updated. 

In AADWebAppConfiguration (line 165), value is not set. For value is set, you need to call fonction with ClientRegistration in parameter.
In AADOAuth2UserService (Line 81), value is always null and It take default value. 

**To Reproduce**
Try to change default value and It don't working.

***Code Snippet***
My application.yml
```
spring:
  security:
    oauth2:
      client:
        provider:
          azure:
            user-name-attribute: upn
```

**Expected behavior**
userNameAttributeName don't have default value when my user is connected

**Setup (please complete the following information):**
 - spring 5.4.3 
 - azure-spring-boot-starter-active-directory 3.2.0

**Additional context**
I migrate from old version of azure-spring-boot. All other feature in my application is working.

**Information Checklist**
Kindly make sure that you have added all the following information above and checkoff the required fields otherwise we will treat the issuer as an incomplete report
- [X] Bug Description Added
- [X] Repro Steps Added
- [X] Setup information Added

**Comment by joshfree** [comment]
@stliu could you please take a look?

**Comment by chenrujun** [comment]
@j0nathan33 

Thank you for reaching out.
It's a bug, we will fix it.
