### ISSUE TITLE
[Feature Request] Get access token via Client Credential flow.

### ISSUE THREAD

**Issue by ZhuXiaoBing-cn** [Azure/azure-sdk-for-java#20219]
- In the aad b2c scenario, doesn’t really support user delegation permission. So we hope to obtain an access token with application permission through client credential flow to complete access to protected resources.
-  In the aad scenario, it is also hoped that the client credential flow can obtain the access token and parse out the application permission for permission control to complete the access to the protected resources.

**Comment by saragluna** [comment]
#20390

**Comment by saragluna** [comment]
@moarychan will implement the client credential support for aad b2c.
