### ISSUE TITLE
[FEATURE REQ] Handling Groups by Group ID or Name; Getting a full list of Groups with Azure AD Spring Boot Starter

### ISSUE THREAD

**Issue by idg-sam** [Azure/azure-sdk-for-java#20218]
First of all, thank you so much for the great work on the Azure AD Spring Boot Starter library. So far, this library has been the smoothest experience I've had for creating AuthN  / AuthZ applications with Azure AD.

**Is your feature request related to a problem? Please describe.**
1. Feature 1:  Authorizing endpoints via both group names and group IDs.
2. Feature 2: There may be instances where the developers want to see a full list of group memberships, or want to implement some logic that checks group membership for group not declared in the properties file. This only applies if there is a [group overage problem](https://docs.microsoft.com/azure/active-directory/develop/id-tokens#groups-overage-claim), as getting groups claims from the ID token is normally easy.

**Describe the solution you'd like**
1. The solution may have a similar implementation to the existing Group Names solution. Group IDs can be populated into the authorities. Maybe there can be an option in the configuration file: the option can dictate whether to populate groups into the Authorities collection by GroupName, or by GroupID. It can be by GroupName by default to avoid a breaking change.
2. For dealing with groups that were not declared in the properties file, the simple option is for the developer to check ID token claims. This is straight-forward unless there is an [overage problem](https://docs.microsoft.com/azure/active-directory/develop/id-tokens#groups-overage-claim) . This is a question of whether this belongs in the boot starter or not. If yes, then we may want to populate the Authorities with all of the user's Groups memberships. There could be a configuration option to enable or disable this. Once again, defaulting to disabled to avoid a breaking change.

**Describe alternatives you've considered**
1. N/A.
2. Alternatives:
2.1. Another option is that we could automatically prepare a GraphSDK Client for getting all group memberships with one function call. The Boot starter already gives the developer an Oauth2AuthorizedClient to surface the Graph access token. Having the GraphSDK + the correct function call pre-implemented would make it one step easier for the developer.
2.2 Another is option is that this might be out-of-scope of Azure Boot Starter. We could make this the developer's own responsibility to implement this function. In this case, we can create a demo function that serves this need in a sample (e.g., refer to [this part of this sample](https://github.com/Azure-Samples/ms-identity-java-spring-tutorial/blob/dev/3-Authorization-II/groups/src/main/java/com/microsoft/azuresamples/msal4j/msidentityspringbootwebapp/Utilities.java#L60)).

**Additional context**
N/A.

**Information Checklist**
Kindly make sure that you have added all the following information above and checkoff the required fields otherwise we will treat the issuer as an incomplete report
- [x] Description Added
- [x] Expected solution specified

Regards,
@idg-sam

Tagging @chenrujun to continue our discussion.

**Comment by joshfree** [comment]
@stliu could you please take a look

**Comment by ZhuXiaoBing-cn** [comment]
To have `groups` claim in the access token, you need to modify the `groupMembershipClaims` in the **manifest** on the portal.

**Comment by wujack778** [comment]
- [Configures the groups claim for ID token](https://docs.microsoft.com/en-us/azure/active-directory/develop/reference-app-manifest#groupmembershipclaims-attribute): You can modify `groupMembershipClaims` to `SecurityGroup` or the type of group you created earlier.
- [Groups overage claim](https://docs.microsoft.com/en-us/azure/active-directory/develop/id-tokens#groups-overage-claim): If a user is member of more groups than the overage limit (150 for SAML tokens, 200 for JWT tokens), then Azure AD does not emit the groups claim in the token.
![image groups overage clain](https://user-images.githubusercontent.com/69495791/114979150-efd9ca00-9ebc-11eb-9503-609ea215a513.png)
- When no more than 200: 
![image no more than 200](https://user-images.githubusercontent.com/69495791/114979670-e1d87900-9ebd-11eb-8e80-9116b267f6e1.png)

**Comment by saragluna** [comment]
@wujack778 more info on the aggregated and distributed claims https://openid.net/specs/openid-connect-core-1_0.html#AggregatedDistributedClaims.

**Comment by idg-sam** [comment]
Hi ZhuXiaoBing-cn and wujack778 ,

Thanks for the feedback.

This feature request is not asking how to get Group memberships in the ID token. This has always been possible with token configuration.

This feature request is proposing the following 2 items: 

1. Enhance the existing groups logic so that PreAuthorize decorator can be used with `hasRole('GroupID')` as well as the already-exiting `hasRole('GroupName')`. This would be achieved with the option to **populate authorities with GroupID** rather than being tied to GroupName.
2. Enhance groups logic so that it is not required to declare the group names in the `application.yml` configuration file. This would be achieved with an option to **populate authorities with all groups derived from the IDT or AT**. A limitation of this is that groups must be <=200 in JWT. To address that limitation, it is proposed that **if overage occurs, Graph is automatically called to populate authorities** with all groups where  NumberOfGroups > 200.

**Comment by wujack778** [comment]
When there are more than 200 groups, use this endpoint to request the group list through aad graph access token, but our `graph client` currently only supports microsoft graph access token.

**Comment by saragluna** [comment]
@idg-sam 

Hi Sam, the endpoint returned in the JWT when overage occurs is pointing to AAD Graph instead of Microsoft Graph, do you know whether we could configure the endpoint to Microsoft Graph? This is because: 
- It is incomplete, to call this AAD endpoint you would need to include the api-version.
- The graph token we obtained in our AAD starter is for Microsoft Graph, which can't be used to call AAD Graph.

**Comment by backwind1233** [comment]
@idg-sam 
Hi Sam, here is our plan, please tell me if you have other concerns.

we may define properties as below
```
aad:
   group:
     filter-by-ids: id1 (may be empty)
     filter-by-names: name1 (may be empty)
     enable-full-list: false    
```
by default, the `enable-full-list` is `false`, if the value is `true`, it will get user's all groupIds.

the logic like the mindmap below:
![image](https://user-images.githubusercontent.com/4465723/116212157-1f1eef80-a777-11eb-84e7-593f4f64cde3.png)

**Comment by chenrujun** [comment]
How about like this:

```
azure:
  activedirectory:
    user-group:
      allowed-group-namess: group-name-1, group-name-2
      allowed-group-ids: *
```

`*` means all id. Only work for `supported-group-ids`, not work for `supported-group-names`

**Comment by backwind1233** [comment]
@chenrujun looks good

**Comment by saragluna** [comment]
The feature will go out in the next release, which will be mid-May.
