### ISSUE TITLE
Resource group deletion takes time, but operations on deleted resource groups are permitted even after deletion

### ISSUE THREAD

**Issue by vaibhavkulkar** [Azure/azure-sdk-for-java#2022]
Resource group deletion takes time, but operations on deleted resource groups are permitted even after deletion. Step to reproduce:
1. Delete a Resource group with some entities in it.
2. Create another Resource group with same entities.
<This call succeeds and does not complain.>
3. Create some entities in newly created resource group.
After some time Resource group vanishes.
Is this expected behaviour ? Is there a way to check if resource deletion is in progress with same name that we are trying to create again ?>

**Comment by praries880** [comment]
@vaibhavkulkar 

Are you still facing the issue? If so, can you post replied to the following clarifications:
* Did you create the second resource group (step 2) with the same name as the resource group deleted in step 1?
* Can you elaborate what you mean by "Create another Resource group with same entities"?
* How does the RG created in step 2 vanish? Did you delete that one as well?

**Comment by vhvb1989** [comment]
Hello @vaibhavkulkar 

Do you still need help on this? Let me know and I would be happy to help.

Note: As part of repository cleaning effort, this issue will be closed by **Nov 11** if no response is received from submitter and/or not further action is required.
