### ISSUE TITLE
Discuss whether to use long or spark timestamp for _ts.​

### ISSUE THREAD

**Issue by moderakh** [Azure/azure-sdk-for-java#20224]

**Comment by ealsur** [comment]
Mongo does not have this scenario, the timestamp of documents are part of the ObjectId https://docs.mongodb.com/manual/reference/method/ObjectId/, they don't have a separate field.


Cassandra has a WRITETIME function that returns the time the row was written, and the format is numeric: https://docs.datastax.com/en/dse/5.1/cql/cql/cql_using/useWritetime.html and the spark connector also seems to surface it as Long https://github.com/datastax/spark-cassandra-connector/blob/6a213676caf3323333753752600b5551a69845d5/connector/src/it/scala/com/datastax/spark/connector/sql/CassandraDataFrameMetadataSpec.scala#L193


In our case, our _ts is a separate field (not like Mongo) and also aligns with CCX in terms of type.

The user can specify Timestamp as type in the schema if they want and we would do the conversion. https://github.com/Azure/azure-sdk-for-java/blob/master/sdk/cosmos/azure-cosmos-spark_3-1_2-12/src/main/scala/com/azure/cosmos/spark/CosmosRowConverter.scala#L355
