### ISSUE TITLE
Can I get Classic VM list with java sdk?

### ISSUE THREAD

**Issue by sklim2002** [Azure/azure-sdk-for-java#2023]
Guys,
I'd like to get vm list of china region, wrote the code like below (AZURE_CHINA).
But, there's no vm list, even though there's several in china portal.
There're all classic VM, not Resource Manager VM.

And I know these're different provider:
ARM : https://management.azure.com/subscriptions/{subscriptionId}/providers/Microsoft.Compute
Classic: https://management.azure.com/subscriptions/{subscriptionId}/providers/Microsoft.ClassicCompute

So I'm wondering whether I can get the information for VM list in classic environment with java sdk?
Or, should I use REST API?

===(there's no result for Classic VM with virtualMachines() method =====
//SET with CHINA subscription
		Azure client = Azure.configure()
				.authenticate(
				new ApplicationTokenCredentials(clientId, tenantId, secretKey, AzureEnvironment.AZURE_CHINA)
				.withDefaultSubscriptionId(subscriptionId)
		).withDefaultSubscription();
		System.out.println("azure china vm list size: " + client.virtualMachines().list().size());

===(below source code that I've got searched, using ARM, need to search Classic VM) =====
https://stackoverflow.com/questions/36178842/how-to-get-list-of-azure-vms-non-classic-resource-managed-using-java-api

**Comment by Drewm3** [comment]
Cleaning up old issues from 2016 - 2018. Please reopen this issue if it is still a concern.
