### ISSUE TITLE
validate overwriting system properties

### ISSUE THREAD

**Issue by moderakh** [Azure/azure-sdk-for-java#20233]
Think through the scenario that the user attempts to write system properties. (Should you throw or pass throw?)​

**Comment by ealsur** [comment]
@moderakh The SDKs or backend do not block on users attempting this, they silently not do it (for example, you cannot change `_ts`).

Why would the spark connector be different or if there is any blocking, would it be better at the SDK level?

**Comment by moderakh** [comment]
this is a feedback we got back, feel free to do investigation on what makes sense to be done as well. Just think about the expected behaviour. as part of this item, you can define the expected behaviour the way you think makes most sense.

for example, as you said `_ts` is overwritable. but I am not sure if it makes sense to overwrite some other system fields e.g, `_lsn`. We should see what the backend contract for overwriting different system properties is and design the expected behaviour accordingly.

**Comment by ealsur** [comment]
Based on discussion, in order to be consistent with all the other client-side tooling (SDKs, tools, etc), we will not add any validation when the user tries to save/override a system property. Any validation should be implemented in the backend, which would make it consistent across all tooling.
