### ISSUE TITLE
Communication Chat Readme issue

### ISSUE THREAD

**Issue by Melanie-Ma** [Azure/azure-sdk-for-java#20245]
1.
Section [Link](https://github.com/Azure/azure-sdk-for-java/tree/master/sdk/communication/azure-communication-chat#examples):
![image](https://user-images.githubusercontent.com/64007802/112923941-cd685280-9141-11eb-9b41-e67e21ece680.png)
Suggestion:
Add Link `[Create the chat client](#create-the-chat-client)`

@jongio for notification

**Comment by ashwinder** [comment]
Thanks @Melanie-Ma for raising this issue. The engineering team is tracking this as a bug and will be working on it shortly. Thanks

**Comment by angiurgiu** [comment]
Thanks @Melanie-Ma. The issue has been addressed: https://github.com/Azure/azure-sdk-for-java/pull/20584
