### ISSUE TITLE
No Async Operation available for deleting blobs

### ISSUE THREAD

**Issue by ashishdhar** [Azure/azure-sdk-for-java#2024]
There is no method available in azure SDK for java to asynchronously delete page blobs in a storage account. Something in the lines of ```blob.DeleteIfExistsAsync()```. Storage account itself has ```createAsync()``` or ```deleteAsync()``` but blobs in a storage account cannot be deleted asynchronously. The ```CloudPageBlob``` object has no such method. Only the synchronous ```DeleteIfExists```

**Comment by mirobers** [comment]
Thanks for your interest in asynchronous support. We are currently developing this for the storage data plane and will have a preview release soon.

**Comment by praries880** [comment]
@mirobers Any update on this?

**Comment by mirobers** [comment]
Async support for Java is now available. Please see the [Azure Storage Java GitHub site](https://github.com/azure/azure-storage-java). This issue can be closed.

**Comment by kurtzeborn** [comment]
In our latest [preview 1](https://github.com/Azure/azure-sdk-for-java/blob/master/storage/client/blob/src/main/java/com/azure/storage/blob/BlobAsyncClient.java) you will find that we've added Async support.
