### ISSUE TITLE
[BUG] Unable to deploy a marketplace application from the SDK because of missing version

### ISSUE THREAD

**Issue by nmalfroy** [Azure/azure-sdk-for-java#20253]
**Describe the bug**
Deploying an application from the marketplace requires that a version be present in the plan property.  The api currently allows for name, publisher, product and promotion code but doesn't allow for a version field. As a result, running the endpoint causes a failure.

***Exception or Stack Trace***
The API returns: `Status code 400, "{"error":{"code":"InvalidApplicationPlan","message":"The appliance '<app name>' plan version is missing."}}"`

**To Reproduce**
Try to deploy a marketplace application using the SDK.

***Code Snippet***
```
AzureResourceManager resourceManager = AzureResourceManager.authenticate(credential, profile)
        .withSubscription(subscription);

resourceManager.genericResources().define("deployed_managed_app")
        .withRegion(Region.US_EAST)
        .withExistingResourceGroup("my-resource-group")
        .withResourceType("applications")
        .withProviderNamespace("Microsoft.Solutions")
        .withPlan("my-plan", "my-publisher", "my-product", null)
        .withProperties(properties)
        .create();
```

**Expected behavior**
I would expect the line with `.withPlan()` to have an extra parameter for the plan version *or* the service API to have a default (e.g. the latest version)

**Screenshots**
N/A

**Setup (please complete the following information):**
 - OS: macOS Catalina
 - IDE : IntelliJ
 - Library version 2.1 (but checked and still exists in 2.3

Kindly make sure that you have added all the following information above and checkoff the required fields otherwise we will treat the issuer as an incomplete report
- [X] Bug Description Added
- [X] Repro Steps Added
- [X] Setup information Added

**Comment by joshfree** [comment]
@yungezz could you please help route this Management plane issue?

**Comment by yungezz** [comment]
add @weidongxu-microsoft to help to have a look.
