### ISSUE TITLE
[BUG] configure SSL certificate from Keyvault failed in Application Gateway 

### ISSUE THREAD

**Issue by DanielWangZhanggui** [Azure/azure-sdk-for-java#20252]
**Describe the bug**
Failed to create/configure SSL certficate from Keyvault for Application Gateway.

***Exception or Stack Trace***
Add the exception log and stack trace if available
com.azure.core.management.exception.ManagementException: Long running operation is Failed or Cancelled.: Problem occured while accessing and validating KeyVault Secrets associated with Application Gateway '/subscriptions/77bbb887-5daa-4b0b-acf6-46f07353c2cf/resourceGroups/danieltest9/providers/Microsoft.Network/applicationGateways/lbtest'.

**To Reproduce**
-Using Managed Service Identity, and set access policy of the Keyvault for the Managed Identity
- Create Application Gateway with the SSL certifcate imported in the  Keyvault
***Code Snippet***
Add the code snippet that causes the issue.
```
 azureResourceManager.
            applicationGateways().define(loadBalancerName1)
            .withRegion(region)
            .withExistingResourceGroup(rgName)
            // Add two rules that uses above backend and probe
            .defineRequestRoutingRule(httpLoadBalancingRule)
            .fromPublicFrontend()
            .fromFrontendHttpsPort(443).withSslCertificate("Testaa")
            .toBackendHttpPort(8080).toBackend(backendPoolName1)
            .attach().withTier(ApplicationGatewayTier.STANDARD_V2).withSize(ApplicationGatewaySkuName.STANDARD_V2)
            .withIdentity(serviceIdentity)
            .defineSslCertificate("Testaa").withKeyVaultSecretId(certId).attach()
            .withExistingSubnet(network, "ApplicationGatewaySubnet")
            .create();
```
**Expected behavior**
Create Azure Application Gateway Successfully
**Screenshots**
![image](https://user-images.githubusercontent.com/4372694/112986689-63c56400-9194-11eb-83e5-294713e1a61b.png)

**Setup (please complete the following information):**
 - OS: WIndows
 - IDE : Intelij
 - Version of the Library used: 2.1.0
 - 
**Additional context**

**Information Checklist**
Kindly make sure that you have added all the following information above and checkoff the required fields otherwise we will treat the issuer as an incomplete report
- [ ] Bug Description Added
- [ ] Repro Steps Added
- [ ] Setup information Added

**Comment by DanielWangZhanggui** [comment]
Hi @joshfree  @yungezz  -


Just  have a try on azure-resourcemanager 2.3.0-alpha.20210329.0 & 2.2.0 with no luck. Please help to shot the issue, thanks very much!

**Comment by yungezz** [comment]
add @weidongxu-microsoft to help on this

**Comment by weidongxu-microsoft** [comment]
usage problem. should use PFX format without password.
