### ISSUE TITLE
[QUERY]Retry mechanism taking more than expected time to throw exception

### ISSUE THREAD

**Issue by sirajP12345** [Azure/azure-sdk-for-java#20250]
Hi,

I have below configuration in my project for sender client for azure service bus. I ran the Java app with by disconnecting to the network and observe that connection failure  exception is seen after 1 or 2 min where I am expecting the exception after 2000 millisec * 3 retry = 6 seconds or around 10 secs . Even I can see same if i set retrymode as  **AmqpRetryMode.FIXED** 

Duration delay = Duration.ofMillis(2000);
AmqpRetryOptions retry = new AmqpRetryOptions();
retry.setMaxRetries(3);
retry.setDelay(delay);
retry.setMode(AmqpRetryMode.EXPONENTIAL);
ServiceBusSenderClient senderClient = new ServiceBusClientBuilder()
		.connectionString(connectionString).retryOptions(retry)
		.sender()
		.queueName(queueName).
		buildClient();
		
Can anyone explain , Is it a expected behavior ? If so why it is taking more than provided time. 

Also,want to know How to check each retry attempt? Currently I can see log message in the end after completion of all attempts like **Exception in thread "main" com.azure.messaging.servicebus.ServiceBusException: Retries exhausted: 3/3**. Instead I want to see each retry attempt made by the sender client.

**Comment by hemanttanwar** [comment]
This is fixed in latest version.
https://search.maven.org/artifact/com.azure/azure-messaging-servicebus/7.2.3/jar
