### ISSUE TITLE
App Configuration - Automatic refresh is not working with Spring Webflux.

### ISSUE THREAD

**Issue by vn50f6p** [Azure/azure-sdk-for-java#20255]
**Describe the bug**
 We have developed the application using  “spring-boot-starter-webflux" dependency. 
Whenever we are using Azure App Configuration - Automatic refresh is not working. First time values are getting populated and when you change the value in azure app configuration and do the web activity, new value is not getting refreshed.
Again after restart the application new value is getting populated.

<dependency>
   <groupId>org.springframework.boot</groupId>
   <artifactId>spring-boot-starter-webflux</artifactId>
</dependency>

***Exception or Stack Trace***
NA

**To Reproduce**

***Code Snippet***
Add the code snippet that causes the issue.

**Expected behavior**

**Screenshots**

**Setup (please complete the following information):**
 - IDE : [e.g. IntelliJ]
 - Version of the Library used

**Additional context**

**Information Checklist**
Kindly make sure that you have added all the following information above and checkoff the required fields otherwise we will treat the issuer as an incomplete report
- [ ] Bug Description Added
- [ ] Repro Steps Added
- [ ] Setup information Added

**Comment by mrm9084** [comment]
@vn50f6p The automatic refresh that happens with spring-cloud-azure-appconfiguration-config-web, only works with Spring Web applications. For Spring WebFlux you should use spring-cloud-azure-appconfiguration-config and manually trigger refresh, https://github.com/Azure/azure-sdk-for-java/tree/master/sdk/appconfiguration/spring-cloud-starter-azure-appconfiguration-config#configuration-refresh.

You should be able to do:

```java
@Autowired
private AzureCloudConfigRefresh azureCloudConfigRefresh;
```

to access the refresh. This will still use the caching and everything of the Web client and just needs to be manually called. Depending on your situation most Webflux users either attach the refresh to a common operation or do an `@Scheduled` to call it on a fixed interval.
