### ISSUE TITLE
Cosmos DB connection mode switched to Gateway automatically

### ISSUE THREAD

**Issue by NikhitaKataria** [Azure/azure-sdk-for-java#20273]
**Query/Question**

We use Direct Connection Mode to create a cosmos client on Mar 17 and noticed an interruption on Mar 29 with failure in connecting to the cosmos account because of SSLException:

2021/03/29 23:21:28.944 ERROR [RxGatewayStoreModel] [reactor-http-epoll-1] [unified-topology-war] [] Network failure
javax.net.ssl.SSLException: handshake timed out

Upon looking at the logs, We noticed "connectionMode":"GATEWAY" is set in "cosmosDiagnostics" however we setup the client to use DirectMode:

```
Unable to refresh database account from any location. Exception: {"ClassName":"CosmosException","userAgent":"azsdk-java-cosmos":0,"resourceAddress":"https://<cosmosaccount>:443/","innerErrorMessage":null,"causeInfo":"[class: class javax.net.ssl.SSLException, message: handshake timed out]","cosmosDiagnostics":{"userAgent":"azsdk-java-cosmos/4.11.0","requestLatencyInMs":29335,"requestStartTimeUTC":"2021-03-29T23:53:12.237Z","requestEndTimeUTC":"2021-03-29T23:53:41.572Z","connectionMode":"GATEWAY","responseStatisticsList":[],"supplementalResponseStatisticsList":[],"addressResolutionStatistics":{},"regionsContacted":[],"retryContext":{"retryCount":0,"statusAndSubStatusCodes":null,"retryLatency":0},"metadataDiagnosticsContext":{"metadataDiagnosticList":null},"serializationDiagnosticsContext":{"serializationDiagnosticsList":null},"gatewayStatistics":{"sessionToken":null,"operationType":"Read","statusCode":0,"subStatusCode":10001,"requestCharge":null,"requestTimeline":null},"systemInformation":{"usedMemory":"5712527 KB","availableMemory":"1744241 KB","systemCpuLoad":"(2021-03-29T23:53:22.033Z 40.0%), (2021-03-29T23:53:22.035Z 100.0%), (2021-03-29T23:53:22.037Z 100.0%), (2021-03-29T23:53:31.868Z 97.8%), (2021-03-29T23:53:31.873Z 40.0%), (2021-03-29T23:53:41.555Z 97.9%)"},"clientCfgs":{"id":0,"numberOfClients":1,"connCfg":{"rntbd":"(cto:PT5S, rto:PT5S, icto:PT0S, ieto:PT1H, mcpe:100, mrpc:100, cer:false)","gw":"(cps:1000, rto:PT5S, icto:null, p:false)","other":"(ed: true, cs: false)"},"consistencyCfg":"(consistency: Session, mm: false, prgns: [eastus])"}}}
Caused by: javax.net.ssl.SSLException: handshake timed out
```

Client Creation:
```
CosmosClientBuilder cosmosClientBuilder = new CosmosClientBuilder()
      .endpoint(serviceEndpoint)
      .key(key)
      .contentResponseOnWriteEnabled(contentResponseOnWriteEnabled)
      .consistencyLevel(ConsistencyLevel.valueOf(consistencyLevel))
      .directMode(directConnectionConfig)
      .throttlingRetryOptions(throttlingRetryOptions);

cosmosClientBuilder.buildClient()
```
If we created the client via Direct Mode, why did the connectionMode switch to Gateway is a puzzle for me and I would appreciate help to understand any scenario in which this could happen.

A restart of the service fixed the issue but we are not certain what happened.

***Why is this not a Bug or a feature Request?***
This is not certainly a bug or a feature request. It is a scenario query.

**Setup (please complete the following information if applicable):**
 - OS: Linux
 - IDE : None
 - Version: https://mvnrepository.com/artifact/com.azure/azure-cosmos/4.11.0 
 
 **Information Checklist**
 Kindly make sure that you have added all the following information above and checkoff the required fields otherwise we will treat the issuer as an incomplete report
- [ ] Query Added
- [ ] Setup information Added

**Comment by joshfree** [comment]
@kushagraThapar could you please take a look?

**Comment by kushagraThapar** [comment]
@NikhitaKataria - There is no way for the Cosmos SDK to update the connection mode to Gateway mode automatically. 
This seems to be a bug of Cosmos Diagnostics. Can you please log some other diagnostics on the responses (query / read item), etc. So as to check what connection mode we get on the other responses. 

Note - Even in Direct connection mode, some operations still go through Gateway - like meta data operations, fetching the query plan to execute query, etc. 
Above exception happened on getting the database account - which is a Gateway operation - may be because of it, the connection mode is showing as GATEWAY, however, it should still show it as DIRECT mode.
