### ISSUE TITLE
Differentiate SDK generated exceptions from the service

### ISSUE THREAD

**Issue by mbhaskar** [Azure/azure-sdk-for-java#20271]
Currently we generate and throw exceptions like  GoneException,ServiceUnavailableException etc from SDK that are thrown even by the service (example: RntbdRequestRecord#expire(), GoneAndRetryWithRetryPolicy#shouldRetry). We should either introduce a new subclass of these exceptions or new substatus code that clearly distinguishes these from the ones thrown by the service which will enhance the supportability/debuggability. Along with these we can also come up with corresponding TSGs to help further.

**Comment by TheovanKraay** [comment]
@xinlian12 can this be closed?

**Comment by xinlian12** [comment]
it is still active, maybe this can be taken as the uber working item. 
Related child item: https://github.com/Azure/azure-sdk-for-java/issues/27909

**Comment by kushagraThapar** [comment]
This is done.
