### ISSUE TITLE
[BUG] VirtualMachines.deleteByIdAsync(id).subscribe(consumer) doesn't call consumer

### ISSUE THREAD

**Issue by jloisel** [Azure/azure-sdk-for-java#20283]
**Describe the bug**
Subscribing a listener on `VirtualMachines.deleteByIdAsync` doesn't work because it returns a `Mono<Void>` with a `null` value. The listener is never called.

***Code Snippet***

```java
final VirtualMachines vms = client.virtualMachines();
vms
      .deleteByIdAsync(vm.id())
      .subscribe(System.out::println);
```

Hack needed to make it work:

```java
final VirtualMachines vms = client.virtualMachines();
vms
      .deleteByIdAsync(vm.id())
      .then(just(true))
      .subscribe(System.out::println);
```

It's important as we need to manually delete disks / network interfaces once a virtual machines has been deleted.

**Expected behavior**

Subscribed on `deleteByIdAsync` should allow to register a consumer which receives a value when done.

**Screenshots**

**Setup (please complete the following information):**
 - OS: Ubuntu 20.04LTS
 - IDE : IntelliJ
 - `azure-resourcemanager-compute:2.2.0`

**Information Checklist**
Kindly make sure that you have added all the following information above and checkoff the required fields otherwise we will treat the issuer as an incomplete report
- [x] Bug Description Added
- [x] Repro Steps Added
- [x] Setup information Added

**Comment by jloisel** [comment]
Closing as it seems like i'm misusing Reactor.

**Comment by jloisel** [comment]
`Mono<Void>` apparently doesn't return anything which is kind of misleading. It would be easier to understand for callers by returning a `Mono<Boolean>` for example.

**Comment by joshfree** [comment]
@yungezz could you please take a look?

**Comment by yungezz** [comment]
add @weidongxu-microsoft to help look at this.

**Comment by weidongxu-microsoft** [comment]
@jloisel

Not going to change to Mono<Boolean> as it breaks everyone.

You can easily use `doOnSubscribe` etc.
