### ISSUE TITLE
ResourceManagerThrottlingInterceptor synchronization should be scoped to subscription

### ISSUE THREAD

**Issue by jystephan** [Azure/azure-sdk-for-java#2028]
Databricks uses the SDK to manage VMs accross hundreds of Azure subscriptions (Databricks customers) from the same java process. We recently ran into an issue where one customer subscription hit the API limit. The ResourceManagerThrottlingInterceptor then started throttling API calls -- the SDK logs show `Azure Resource Manager read/write per hour limit reached. Will retry in: 316 seconds`.

This sleep should apply only to the specific subscription being throttled. However `ResourceManagerThrottlingInterceptor` uses a static `ReentrantLock` for synchronization. This results in *all* our customer subscriptions being blocked (all SDK calls are blocked) for the duration of the throttling. This means Databricks cannot make any Azure API requests for any of its customers during 5 minutes. 

Instead, the lock should be scoped to a single subscription.

**Comment by milismsft** [comment]
Hi @jystephan the Java SDK repo for Azure Management libraries has moved to https://github.com/Azure/azure-libraries-for-java. Please use this [issue](https://github.com/Azure/azure-libraries-for-java/issues/231) for further tracking purposes.
