### ISSUE TITLE
API review for Spring modules

### ISSUE THREAD

**Issue by saragluna** [Azure/azure-sdk-for-java#20281]
The sdk APIs will get reviewed on https://apiview.dev/ and one example is https://apiview.dev/Assemblies/Review/4a20c92e936b41b4913844900fd3962e. For all Spring modules, it would be better if the partner SDK teams could review our APIs in the same way. This issue is to track API reviewing for Spring modules:

- We should see if the Spring team can leverage the `apiview` so we can ensure our public surface area aligns with Track 2 guidelines
- There're some differences between the SDK and its Spring Integration. The SDK exports all sorts of APIs; however, Spring uses the SDK APIs and implements some Spring frameworks' APIs at the same time.

**Comment by srnagar** [comment]
@saragluna - Thanks for filing this issue. If you have any questions regarding the API view, please reach out to @praveenkuttappan.

**Comment by saragluna** [comment]
Thanks @srnagar for the update. @praveenkuttappan, do we have an instruction doc for how to integrate with `apiview`?

**Comment by saragluna** [comment]
Closing in favor of https://github.com/Azure/azure-sdk-for-java/issues/20281.
