### ISSUE TITLE
Getting power state of a VM is very slow.

### ISSUE THREAD

**Issue by ImranBijapuri** [Azure/azure-sdk-for-java#2029]
I am using version 1.1.2 of the sdk. 
The API call for getting the powerstate of a VM is taking too long to respond.
On an average it takes around ~8 seconds to get the power state of a single VM. 
Our subscription of around 30 VMs takes 260 seconds just to get the powerstate of all VM's.
Is there a workaround here ?

**Comment by renutz** [comment]
+1

**Comment by Drewm3** [comment]
Cleaning up old issues from 2016 - 2018. Please reopen this issue if it is still a concern.
