### ISSUE TITLE
[BUG] ServiceBus ReceiverAsyncClient fails without any notice after long time without message

### ISSUE THREAD

**Issue by oraum** [Azure/azure-sdk-for-java#20291]
**Describe the bug**
When having an application with a ServiceBusReceiverAsyncClient listening for messages running for a few days without receiving any message the scheduler within ReactorExecutor will eventually fail resulting in not receiving any messages. When failing there is a log message from ReactorExecutor but the Flux returned from receiveMessages will neither emit an error nor terminate. Therefore it's hard to react to the failure.

***Exception or Stack Trace***

```WARN 1 --- [ctor-executor-2] c.a.c.a.implementation.ReactorExecutor   : connectionId[MF_xxxx], message[Scheduling reactor failed because the scheduler has been shut down.]
Task java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask@4b98509a[Not completed, task = reactor.core.scheduler.SchedulerTask@a30e086] rejected from java.util.concurrent.ScheduledThreadPoolExecutor@5e8a421c[Terminated, pool size = 0, active threads = 0, queued tasks = 0, completed tasks = 0]
```

**To Reproduce**

- create ServiceBusReceiverAsyncClient
- call receiveMessages, add doOnError, doFinally and subscribe
- wait ... (approx 3-6 days)
- ReactorExecutor will fail and log message, none of our callbacks triggered

if interested only in the error handling it may be sufficient to create a breakpoint within ReactorExecutor and dispose scheduler

**Expected behavior**

- [ ] ServiceBusReceiverAsyncClient should receive messages stable and reliable even when there aren't any messages for a few days
- [ ] When a non transient error happens inside AsyncClient which impacts the basic functionality I would like to get a notice/error

**Setup (please complete the following information):**
 - OS: Ubuntu 16.04.7 LTS / AKS 1.16.15, OpenJDK 11
 - IDE : not applicable
 - azure-messaging-servicebus: 7.1.0, spring-boot 2.3.7.RELEASE, Kotlin 1.4.20, Java 11

**Additional context**
As kind of a workaround I noticed it's possible to query the ThreadGroup for the existence of the "reactor-executor-1" thread to check if the application is still able to receive messages but that isn't very reliable either.

**Information Checklist**
Kindly make sure that you have added all the following information above and checkoff the required fields otherwise we will treat the issuer as an incomplete report
- [x] Bug Description Added
- [x] Repro Steps Added
- [x] Setup information Added

**Comment by hemanttanwar** [comment]
@oraum Thank you for reporting this issue. We will reproduce this issue and understand how receiver client is failing after few days.

**Comment by hemanttanwar** [comment]
Hello @oraum Do you have additional logs before the error , which provide us condition which caused the exception for Scheduler. I want to understand condition which triggered the exception.

**Comment by oraum** [comment]
Hello @hemanttanwar here is an example from a few days ago
```
2021-05-14 17:54:25.741  WARN 1 --- [ctor-executor-1] c.a.m.s.i.ServiceBusReceiveLinkProcessor : linkName[n/a] entityPath[n/a]. Transient error occurred. Attempt: 1. Retrying after 3275 ms.
The service was unable to process the request; please retry the operation. For more information on exception types and proper exception handling, please refer to http://go.microsoft.com/fwlink/?LinkId=761101 TrackingId:94c279f04bef4fcbbbbbea7dde5c20d0_G5, SystemTracker:gateway7, Timestamp:2021-05-14T17:54:25, errorContext[NAMESPACE: namespace.servicebus.windows.net, PATH: topic-name/subscriptions/subscription-name, REFERENCE_ID: topic-name/subscriptions/subscription-name_784dc8_1619494836202, LINK_CREDIT: 1]
2021-05-14 17:54:29.017  WARN 1 --- [     parallel-1] c.a.m.s.i.ServiceBusReceiveLinkProcessor : linkName[n/a] entityPath[n/a]. Transient error occurred. Attempt: 2. Retrying after 6928 ms.
The service was unable to process the request; please retry the operation. For more information on exception types and proper exception handling, please refer to http://go.microsoft.com/fwlink/?LinkId=761101 TrackingId:94c279f04bef4fcbbbbbea7dde5c20d0_G5, SystemTracker:gateway7, Timestamp:2021-05-14T17:54:25, errorContext[NAMESPACE: namespace.servicebus.windows.net, PATH: topic-name/subscriptions/subscription-name, REFERENCE_ID: topic-name/subscriptions/subscription-name_784dc8_1619494836202, LINK_CREDIT: 1]
2021-05-14 17:54:49.312  WARN 1 --- [ctor-executor-1] c.a.m.s.i.ServiceBusReceiveLinkProcessor : linkName[n/a] entityPath[n/a]. Transient error occurred. Attempt: 3. Retrying after 15973 ms.
The service was unable to process the request; please retry the operation. For more information on exception types and proper exception handling, please refer to http://go.microsoft.com/fwlink/?LinkId=761101 TrackingId:94c279f04bef4fcbbbbbea7dde5c20d0_G5, SystemTracker:gateway7, Timestamp:2021-05-14T17:54:49, errorContext[NAMESPACE: namespace.servicebus.windows.net, PATH: topic-name/subscriptions/subscription-name, REFERENCE_ID: topic-name/subscriptions/subscription-name_784dc8_1619494836202, LINK_CREDIT: 1]
2021-05-14 17:55:05.285  WARN 1 --- [     parallel-1] c.a.m.s.i.ServiceBusReceiveLinkProcessor : linkName[n/a] entityPath[n/a]. Transient error occurred. Attempt: 4. Retrying after 38364 ms.
The service was unable to process the request; please retry the operation. For more information on exception types and proper exception handling, please refer to http://go.microsoft.com/fwlink/?LinkId=761101 TrackingId:94c279f04bef4fcbbbbbea7dde5c20d0_G5, SystemTracker:gateway7, Timestamp:2021-05-14T17:54:49, errorContext[NAMESPACE: namespace.servicebus.windows.net, PATH: topic-name/subscriptions/subscription-name, REFERENCE_ID: topic-name/subscriptions/subscription-name_784dc8_1619494836202, LINK_CREDIT: 1]
2021-05-14 21:47:01.660  WARN 1 --- [ctor-executor-1] c.a.c.a.implementation.ReactorExecutor   : connectionId[MF_99d74a_1619494835811], message[Scheduling reactor failed because the scheduler has been shut down.]
Task java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask@149ce54b[Not completed, task = reactor.core.scheduler.SchedulerTask@23a2504c] rejected from java.util.concurrent.ScheduledThreadPoolExecutor@331ffd2a[Terminated, pool size = 0, active threads = 0, queued tasks = 0, completed tasks = 0]
2021-05-14 21:51:57.250  WARN 1 --- [ctor-executor-1] c.a.c.a.implementation.ReactorExecutor   : connectionId[MF_491654_1621028883415], message[Scheduling reactor failed because the scheduler has been shut down.]
Task java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask@584dbe4f[Not completed, task = reactor.core.scheduler.SchedulerTask@647dec1a] rejected from java.util.concurrent.ScheduledThreadPoolExecutor@76b1d87f[Terminated, pool size = 0, active threads = 0, queued tasks = 0, completed tasks = 0]
```
(redacted topic, subscription and sb namespace name)
As additional context, the last message was successfully processed on May 9th so 5 days before that occurrence. Therefore the Transient error seems to origin from the internals of the client.

**Comment by joshfree** [comment]
@YijunXieMS could you please update the issue with current status and update the milestone accordingly?

**Comment by ramya-rao-a** [comment]
Hey @oraum 

It has been almost a year since this issue was reported. In this time, we have shipped several updates to the `azure-messaging-servicebus` package that included multiple performance and reliability improvements. Please upgrade to the latest version 7.6.0 and if you still experience this issue, please drop a comment here so that we can re-open the investigation.

Thanks for your patience and thanks for reporting.
