### ISSUE TITLE
[BUG] azure-storage-blob-nio - Files.readAllBytes(filePath) fails if there are files with same prefix in directory

### ISSUE THREAD

**Issue by rutkowskij** [Azure/azure-sdk-for-java#20325]
**Describe the bug**
Files.readAllBytes(filePath) fails if there are files with same prefix in virtual directory.

***Exception or Stack Trace***
```
java.io.IOException: Path either does not exist or points to a directory.Path must point to a file. Path: 
/foo/bar/info.txt
	at com.azure.storage.blob.nio.AzureFileSystemProvider.newInputStream(AzureFileSystemProvider.java:337)
	at com.azure.storage.blob.nio.AzureFileSystemProvider.newByteChannel(AzureFileSystemProvider.java:302)
```

**To Reproduce**
- create / prepare storage account
- add two files `/foo/bar/info.txt` and `/foo/bar/info.txt.backup`

***Code Snippet***
```
Path file1 = fileSystem.getPath("/foo/bar/info.txt");
// there are also file like: Path file2 = fileSystem.getPath("/foo/bar/info.txt.backup");
Files.readAllBytes(file1) 
```

**Expected behavior**
file1 bytes read

**Setup (please complete the following information):**
 - OS: Windows
 - IDE : IntelliJ
 - Version of the Library used: 12.0.0-beta.4

**Information Checklist**
Kindly make sure that you have added all the following information above and checkoff the required fields otherwise we will treat the issuer as an incomplete report
- [x] Bug Description Added
- [x] Repro Steps Added
- [x] Setup information Added

**Comment by gapra-msft** [comment]
Hi @rutkowskij 

Thank you for posting this issue. We will take a look at why this could be happening.

**Comment by gapra-msft** [comment]
@rutkowskij Just wanted to update you that I was able to reproduce your issue, I am investigating potential fixes for this issue.
