### ISSUE TITLE
Azure Spring Data Cosmos - IndexingPolicy is getting overwritten on application bootup

### ISSUE THREAD

**Issue by kushagraThapar** [Azure/azure-sdk-for-java#20330]
**Describe the bug**
* In Azure spring data cosmos, container's `IndexingPolicy` is getting overriden on application bootup in both the cases where `CosmosIndexingPolicy` annotation is used and not used on the Entity. 
  
**To Reproduce**
Update the indexing policy on container through Azure portal. Then start a spring data cosmos sample application. As application is booted up, indexing policy reverts back to default value. 

This happens in both cases, even if `CosmosIndexingPolicy` annotation is used on the Entity which defines the container definition. And in the case where no annotation is used, still the indexing policy gets overwritten. 

**Expected behavior**
Spring Data cosmos should only create the container if it does not exists. It should not overwrite the indexing policy already defined in the portal. 

**Setup (please complete the following information):**
 - This issue is happening on azure-spring-data-cosmos 3.3.0 and above.

**Comment by kushagraThapar** [comment]
@Blackbaud-EricSlater @Blackbaud-MikeLueders - I recall we added the support for `CosmosIndexingPolicy` and `compositeIndexes` in spring-data-cosmos 3.3.0 version - https://docs.microsoft.com/en-us/azure/cosmos-db/sql-api-sdk-java-spring-v3#330-2020-01-15
This has broke the behavior mentioned above. 
Any ideas what could have caused this issue ? Appreciate your help.

**Comment by Blackbaud-EricSlater** [comment]
this sounds like expected behavior to me. When you use the annotation that is taking precendence over anything that you specify manually through the portal.
If you make changes in the portal and you want them to persist through application startup then the annotation needs to match what you specified in the portal

**Comment by Blackbaud-EricSlater** [comment]
Just to be clear on what the current behavior is currently....
If the annotation is not used, then the code assumes the default index policy should apply. If the annotation is used but no arguments are specified, that is also going to apply the default index policy. If that annotation is specified with arguments, then it will apply the index policy given the arguments.

Maybe we should have specified this behavior in the release notes as this forces people to manage their index policy using the annotation. Adding a property that disables index policy modification via the annotation would allow users to disable this and manage it via other means.

**Comment by kushagraThapar** [comment]
@Blackbaud-EricSlater - I think the current behavior makes sense, but the issue is even when CosmosIndexingPolicy annotation is updated to match what the portal has, still the container's indexing policy is being reset to default values. I guess that is the main issue. 
Thanks for the suggestion above, I will try to implement that.

**Comment by ashishmaithani** [comment]
@Blackbaud-EricSlater If i do not mention any CompositeIndex in the code i.e. where the Entity is annotated with @Container, it's overwriting the composite index policy on the server and resetting it.

**Comment by Blackbaud-EricSlater** [comment]
@ashishmaithani you have to specify the compositeIndex in the @CosmosIndexPolicy annotation..
for instance....
```
@CompositeIndex(paths = {
    @CompositeIndexPath(path = "/compositeField1"),
    @CompositeIndexPath(path = "/compositeField2")
})
```

**Comment by Blackbaud-EricSlater** [comment]
@kushagraThapar 
"even when CosmosIndexingPolicy annotation is updated to match what the portal has, still the container's indexing policy is being reset to default values"

i have been trying to reproduce this in one of my own projects but i have been unable.
I can set and index policy using the annotation and boot the application. It gets applied.
I can then change the index policy and reboot the application. It gets updated.
I have done the above test modifying the index policy in a variety of ways. Specifically by updating the includedFields, excludedFields, and compositeIndex field on the annotation. All were properly applied to the server. 

If i modified the policy manually on the server, then when i booted the application, whatever was specified in the annotation was applied.

**Comment by kushagraThapar** [comment]
@Blackbaud-EricSlater - thanks for the verification. That's what I thought too, since we also have these test cases covering the scenarios - `IndexPolicyUpdateIT` and `ReactiveIndexPolicyUpdateIT`. 

@ashishmaithani - Could you please check the indexing policy being applied through annotation matches with what you are setting on the portal. 

One thing @Blackbaud-EricSlater , could it be possible that in case a incorrect / wrong indexing policy (incorrect in json structure or any other way) is specified in the annotation, and we are swallowing the exception and reseting the policy on the actual container in cosmos db account ?
Just wondering, if we have any test coverage for this scenario?

**Comment by ashishmaithani** [comment]
@Blackbaud-EricSlater I have already tried annotating the Entity with the  `@CosmosIndexingPolicy`
@kushagraThapar I never tried matching the indexing policy applied through annotation with the indexing policy set through portal. So, I can try that.

**Comment by Blackbaud-EricSlater** [comment]
@ashishmaithani can you provide detail about what indexing policy you are trying to set and what you specified in the annotation

**Comment by Blackbaud-EricSlater** [comment]
@kushagraThapar tested the failure scenario. The exception does get propagated and the app fails to boot in that case since it ultimately fails to initialize the associated repository bean because of the exception.
