### ISSUE TITLE
Slow Response/Socket Timeout Exceptions while scanning for VMs 

### ISSUE THREAD

**Issue by puneet101** [Azure/azure-sdk-for-java#2033]
We look at all the VMs on Azure using listByResourceGroup() and it's timing out with only ~80 VMs in the tenant:
   PagedList<VirtualMachine> vms = azureInstance.virtualMachines().listByResourceGroup(rg);

Questions:
#1
Is there a configurable timeout? 

#2
What's the recommended approach to traverse through VMs when the tenant has 100's or 1000's of VMs. 

We see this in our error logs:

**Caused by: java.lang.RuntimeException: java.net.SocketTimeoutException: timeout
Mar 23 03:13:44 workspot-o1works1 app/worker.1:      at rx.exceptions.Exceptions.propagate(Exceptions.java:58)
Mar 23 03:13:44 workspot-o1works1 app/worker.1:      at rx.observables.BlockingObservable.blockForSingle(BlockingObservable.java:464)
Mar 23 03:13:44 workspot-o1works1 app/worker.1:      at rx.observables.BlockingObservable.single(BlockingObservable.java:341)
Mar 23 03:13:44 workspot-o1works1 app/worker.1:      at com.microsoft.azure.management.compute.implementation.VirtualMachinesInner.list(VirtualMachinesInner.java:1441)**

**Comment by puneet101** [comment]
@anuchandy @anudeepsharma Let me know if you have any suggestions? Thanks!

**Comment by jianghaolu** [comment]
When you initialize an Azure instance, you can configure the connection timeout:
```java
Azure azure = Azure.configure()
                    .withConnectionTimeout(5, TimeUnit.MINUTES)
                    .authenticate(credFile)
                    .withDefaultSubscription();
```

**Comment by jianghaolu** [comment]
To list VMs, there are 2 methods that does automatic paging:
1 - `azure.virtualMachines().list()` returns a `PagedList<VirtualMachine>` on which you should iterate through using a for loop. Any attempt to get its size will make numerous network calls and cache the entire list in the memory.
2 - Use Observables:
```java
azure.virtualMachines().listAsync()
    .doOnNext(new Action1<VirtualMachine>() {
        @Override
        public void call(VirtualMachine virtualMachine) {
            
        }
    });
This will also automatically page through all the VMs and should only cache a page of VMs in the memory at a time.

**Comment by puneet101** [comment]
Thanks @jianghaolu

**Comment by puneet101** [comment]
.withConnectionTimeout(5, TimeUnit.MINUTES)
This doesn't work. We still get timed-out after one minute.

**Comment by menih** [comment]
We have the same issue. Increasing the timeout does not work. There is something fundamental changed recently that we started seeing it. It may go away for a bit and then it comes back.

**Comment by jianghaolu** [comment]
There are 3 timeouts associated with the client, connection timeout, read timeout, and write timeout.

Currently we only expose configurations on connection timeout and read timeout and their default values are 10 seconds and 60 seconds respectively. This will give you a bit of a guess which one is timing out when you don't have a lot of other info.

You can configure them both on `Azure.configure()`.

**Comment by praries880** [comment]
Closing the issue, @puneet101  @menih kindly re-open the issue if you are still running into the tmeouts.
