### ISSUE TITLE
Add overload for extractKeyPhrases to take ExtractKeyPhrasesOptions

### ISSUE THREAD

**Issue by heaths** [Azure/azure-sdk-for-java#20349]
Related to Azure/azure-sdk-for-net#18482, which itself was created to mimic Java's #18984, please add an overload of `extractKeyPhrases` to `TextAnalyticsClient(Async)` that takes an `ExtractKeyPhrasesOptions` parameter.

**Comment by mssfang** [comment]
ExtractKeyPhrasesOptions is removed: https://github.com/Azure/azure-sdk-for-java/blob/main/sdk/textanalytics/azure-ai-textanalytics/CHANGELOG.md#breaking-changes-1


This request is not longer needed.
