### ISSUE TITLE
[BUG]Retry mechanism with Azure service bus using Azure Java library 7.x.x is not working 

### ISSUE THREAD

**Issue by sirajP12345** [Azure/azure-sdk-for-java#20344]
Hi,

With the below code if i start the application by disconnecting the network and turn on the network again immediately , connection should be established after few failure attempts and send message to the queue as I am back to online by connecting to the network again but application is still unable to make successful connection and fails with reactor.**core.Exceptions$RetryExhaustedException: Retries exhausted: 5/5** error message.

AmqpRetryOptions retry = new AmqpRetryOptions();
Duration delay = Duration.ofMillis(3000);
Duration timeout = Duration.ofMillis(60000);
retry.setMaxRetries(5);
retry.setDelay(delay);
retry.setMode(AmqpRetryMode.FIXED);
retry.setTryTimeout(timeout);
ServiceBusSenderClient senderClient = new ServiceBusClientBuilder()
		.connectionString(connectionString).retryOptions(retry)
		.sender()
		.queueName(queueName).
		buildClient();
ServiceBusMessage message = new ServiceBusMessage("Hello,How are you?");
senderClient.sendMessage(message);
		
Can anyone help me with this?

@conniey can you help me with this?

**Comment by joshfree** [comment]
@yvgopal @hemanttanwar could you please take a look

**Comment by YijunXieMS** [comment]
[ServiceBusDevBuild.zip](https://github.com/Azure/azure-sdk-for-java/files/6520391/ServiceBusDevBuild.zip)

**Comment by YijunXieMS** [comment]
@sirajP12345 I think this issue has been fixed in both 7.2.2 and 7.2.3. Can we close this issue?
