### ISSUE TITLE
[FEATURE REQ] support for ignoring null params

### ISSUE THREAD

**Issue by grzegorz-moto** [Azure/azure-sdk-for-java#20345]
JPQL queries are able to handle null params with "(:param is null or .....)" like described here
https://www.baeldung.com/spring-data-jpa-null-parameters#Ignoring

How can we achieve it with spring-data-cosmos ?

**Comment by joshfree** [comment]
@stliu @kushagraThapar could you please help schedule this request to an appropriate milestone

**Comment by kushagraThapar** [comment]
@mbhaskar  - do we have a plan for this feature request ?
