### ISSUE TITLE
Support BodyParams using application/x-www-form-urlencoded

### ISSUE THREAD

**Issue by alzimmermsft** [Azure/azure-sdk-for-java#20350]
Currently, `application/x-www-form-urlencoded` body types only are generated properly when each form segment is declared using `FormPart`.

```java
public Response<Void> restApi(@FormPart("id") long id, @FormPart("name") String name, @FormPart("age") int age)
```

But there may be cases, either written manually or code generated, that want to use an object type for the body.

```java
public Response<Void> restApi(@BodyParam("application/x-www-form-urlencoded") Person person);

public class Person {
    public long id;
    public String name;
    public int age;
}
```

Support for this should be enabled either with better handling for `BodyParam` when `Content-Type` is `application/x-www-form-urlencoded` or by having code generation use `FormPart`, or another new annotation such as `FormBody`, in this case.

**Comment by alzimmermsft** [comment]
@srnagar, @jianghaolu, I'd love to get your perspective from a code generation aspect on what you think would be the most appropriate fix (code generation change, code generation and logic change, logic change).

**Comment by jianghaolu** [comment]
Ideally we can generate something like this: 
```
public Response<Void> restApi(@BodyParam("application/x-www-form-urlencoded") Person person);
```

and the RestProxy can take it from there. And we can use `@FormPart` exclusively for multi-part/formdata?

**Comment by alzimmermsft** [comment]
Adding @srnagar as an assignee as there are code generation changes which may resolve this issue.

**Comment by alzimmermsft** [comment]
Fixed by code generation
