### ISSUE TITLE
[BUG] java.lang.NoClassDefFoundError: com/azure/core/implementation/util/ImplUtils

### ISSUE THREAD

**Issue by atris** [Azure/azure-sdk-for-java#20362]
**Describe the bug**
I am using the Azure SDK and Azure Storage SDK to integrate Blob Storage into my application. My POM dependencies look like this:

      `
        <dependency>
            <groupId>com.azure</groupId>
            <artifactId>azure-storage-blob</artifactId>
            <version>12.0.0</version>
        </dependency>

        
        <dependency>
            <groupId>com.azure</groupId>
            <artifactId>azure-core</artifactId>
            <version>1.3.0-beta.1</version>
        </dependency>

        <dependency>
            <groupId>com.azure</groupId>
            <artifactId>azure-storage-common</artifactId>
            <version>12.10.1</version>
        </dependency>

        <dependency>
            <groupId>com.azure</groupId>
            <artifactId>azure-core-http-netty</artifactId>
            <version>1.7.1</version>
        </dependency>

        <dependency>
            <groupId>org.reactivestreams</groupId>
            <artifactId>reactive-streams</artifactId>
            <version>1.0.3</version>
        </dependency>

        <dependency>
            <groupId>org.springframework</groupId>
            <artifactId>spring-beans</artifactId>
            <version>${spring.version}</version>
            <scope>test</scope>
        </dependency>

        <dependency>
            <groupId>org.springframework</groupId>
            <artifactId>spring-context</artifactId>
            <version>${spring.version}</version>
            <scope>test</scope>
        </dependency>

        <dependency>
            <groupId>org.springframework</groupId>
            <artifactId>spring-core</artifactId>
            <version>${spring.version}</version>
            <scope>test</scope>
        </dependency>`

***Exception or Stack Trace***
`java.lang.NoClassDefFoundError: com/azure/core/implementation/util/ImplUtils
	at com.azure.storage.blob.BlobUrlParts.parseNonIpUrl(BlobUrlParts.java:350)
	at com.azure.storage.blob.BlobUrlParts.parse(BlobUrlParts.java:302)
	at com.azure.storage.blob.BlobServiceClientBuilder.endpoint(BlobServiceClientBuilder.java:115)
	at org.apache.ignite.spi.discovery.tcp.ipfinder.azure.TcpDiscoveryAzureBlobStoreIpFinder.init(TcpDiscoveryAzureBlobStoreIpFinder.java:256)
	at org.apache.ignite.spi.discovery.tcp.ipfinder.azure.TcpDiscoveryAzureBlobStoreIpFinder.registerAddresses(TcpDiscoveryAzureBlobStoreIpFinder.java:135)
	at org.apache.ignite.spi.discovery.tcp.ipfinder.TcpDiscoveryIpFinderAdapter.initializeLocalAddresses(TcpDiscoveryIpFinderAdapter.java:66)
	at org.apache.ignite.spi.discovery.tcp.TcpDiscoveryImpl.registerLocalNodeAddress(TcpDiscoveryImpl.java:401)
	at org.apache.ignite.spi.discovery.tcp.ServerImpl.spiStart(ServerImpl.java:457)
	at org.apache.ignite.spi.discovery.tcp.TcpDiscoverySpi.spiStart(TcpDiscoverySpi.java:2166)
	at org.apache.ignite.internal.managers.GridManagerAdapter.startSpi(GridManagerAdapter.java:278)
	at org.apache.ignite.internal.managers.discovery.GridDiscoveryManager.start(GridDiscoveryManager.java:981)
	at org.apache.ignite.internal.IgniteKernal.startManager(IgniteKernal.java:1965)
	at org.apache.ignite.internal.IgniteKernal.start(IgniteKernal.java:1323)
	at org.apache.ignite.internal.IgnitionEx$IgniteNamedInstance.start0(IgnitionEx.java:2112)
	at org.apache.ignite.internal.IgnitionEx$IgniteNamedInstance.start(IgnitionEx.java:1758)
	at org.apache.ignite.internal.IgnitionEx.start0(IgnitionEx.java:1143)
	at org.apache.ignite.internal.IgnitionEx.startConfigurations(IgnitionEx.java:1061)
	at org.apache.ignite.internal.IgnitionEx.start(IgnitionEx.java:947)
	at org.apache.ignite.internal.IgnitionEx.start(IgnitionEx.java:846)
	at org.apache.ignite.internal.IgnitionEx.start(IgnitionEx.java:716)
	at org.apache.ignite.internal.IgnitionEx.start(IgnitionEx.java:685)
	at org.apache.ignite.Ignition.start(Ignition.java:353)
	at org.apache.ignite.startup.cmdline.CommandLineStartup.main(CommandLineStartup.java:367)
Caused by: java.lang.ClassNotFoundException: com.azure.core.implementation.util.ImplUtils
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:602)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:178)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:522)
	... 23 more
`

**To Reproduce**
Creating a new module with these dependencies and adding the module to core codepath causes the issue.

***Code Snippet***
This is my dependency tree for the module:

[INFO] -------------------< org.apache.ignite:ignite-azure >-------------------
[INFO] Building ignite-azure 2.11.0-SNAPSHOT                            [28/55]
[INFO] --------------------------------[ jar ]---------------------------------
[INFO] 
[INFO] --- maven-dependency-plugin:2.8:tree (default-cli) @ ignite-azure ---
[INFO] org.apache.ignite:ignite-azure:jar:2.11.0-SNAPSHOT
[INFO] +- org.apache.ignite:ignite-core:jar:2.11.0-SNAPSHOT:compile
[INFO] |  +- javax.cache:cache-api:jar:1.0.0:compile
[INFO] |  +- org.jetbrains:annotations:jar:16.0.3:compile
[INFO] |  \- org.gridgain:ignite-shmem:jar:1.0.0:compile
[INFO] +- org.apache.ignite:ignite-core:test-jar:tests:2.11.0-SNAPSHOT:test
[INFO] +- org.apache.ignite:ignite-tools:jar:2.11.0-SNAPSHOT:test
[INFO] |  +- org.jodd:jodd-lagarto:jar:3.4.8:test
[INFO] |  |  \- org.jodd:jodd-core:jar:3.4.8:test
[INFO] |  +- org.apache.ant:ant:jar:1.8.2:test
[INFO] |  |  \- org.apache.ant:ant-launcher:jar:1.8.2:test
[INFO] |  +- org.apache.maven.surefire:maven-surefire-common:jar:3.0.0-M4:test
[INFO] |  |  +- org.apache.maven.surefire:surefire-extensions-api:jar:3.0.0-M4:test
[INFO] |  |  +- org.apache.maven.surefire:surefire-booter:jar:3.0.0-M4:test
[INFO] |  |  +- org.apache.maven:maven-toolchain:jar:3.0-alpha-2:test
[INFO] |  |  +- org.apache.maven.shared:maven-artifact-transfer:jar:0.11.0:test
[INFO] |  |  |  +- org.apache.maven.shared:maven-common-artifact-filters:jar:3.0.1:test
[INFO] |  |  |  |  +- org.apache.maven:maven-model:jar:3.0:test
[INFO] |  |  |  |  +- org.apache.maven:maven-plugin-api:jar:3.0:test
[INFO] |  |  |  |  +- org.sonatype.sisu:sisu-inject-plexus:jar:1.4.2:test
[INFO] |  |  |  |  |  +- org.codehaus.plexus:plexus-classworlds:jar:2.2.3:test
[INFO] |  |  |  |  |  \- org.sonatype.sisu:sisu-inject-bean:jar:1.4.2:test
[INFO] |  |  |  |  |     \- org.sonatype.sisu:sisu-guice:jar:noaop:2.1.7:test
[INFO] |  |  |  |  \- org.apache.maven.shared:maven-shared-utils:jar:3.1.0:test
[INFO] |  |  |  |     \- commons-io:commons-io:jar:2.5:test
[INFO] |  |  |  \- commons-codec:commons-codec:jar:1.11:test
[INFO] |  |  \- org.codehaus.plexus:plexus-java:jar:1.0.3:test
[INFO] |  |     +- org.ow2.asm:asm:jar:7.0:test
[INFO] |  |     \- com.thoughtworks.qdox:qdox:jar:2.0-M9:test
[INFO] |  +- org.apache.maven.surefire:surefire-api:jar:3.0.0-M4:test
[INFO] |  |  \- org.apache.maven.surefire:surefire-logger-api:jar:3.0.0-M4:test
[INFO] |  +- org.apache.maven.surefire:common-junit48:jar:3.0.0-M4:test
[INFO] |  |  +- org.apache.maven.surefire:common-junit4:jar:3.0.0-M4:test
[INFO] |  |  |  +- org.apache.maven.surefire:common-junit3:jar:3.0.0-M4:test
[INFO] |  |  |  \- org.apache.maven.surefire:common-java5:jar:3.0.0-M4:test
[INFO] |  |  \- org.apache.maven.surefire:surefire-grouper:jar:3.0.0-M4:test
[INFO] |  \- com.puppycrawl.tools:checkstyle:jar:8.37:test
[INFO] |     +- info.picocli:picocli:jar:4.5.2:test
[INFO] |     +- antlr:antlr:jar:2.7.7:test
[INFO] |     +- org.antlr:antlr4-runtime:jar:4.8-1:test
[INFO] |     +- commons-beanutils:commons-beanutils:jar:1.9.4:test
[INFO] |     |  \- commons-collections:commons-collections:jar:3.2.2:test
[INFO] |     +- com.google.guava:guava:jar:29.0-jre:test
[INFO] |     |  +- com.google.guava:failureaccess:jar:1.0.1:test
[INFO] |     |  +- com.google.guava:listenablefuture:jar:9999.0-empty-to-avoid-conflict-with-guava:test
[INFO] |     |  +- com.google.code.findbugs:jsr305:jar:3.0.2:test
[INFO] |     |  +- org.checkerframework:checker-qual:jar:2.11.1:test
[INFO] |     |  +- com.google.errorprone:error_prone_annotations:jar:2.3.4:test
[INFO] |     |  \- com.google.j2objc:j2objc-annotations:jar:1.3:test
[INFO] |     +- org.reflections:reflections:jar:0.9.12:test
[INFO] |     \- net.sf.saxon:Saxon-HE:jar:10.3:test
[INFO] +- com.azure:azure-storage-blob:jar:12.0.0:compile
[INFO] |  \- org.slf4j:slf4j-api:jar:1.7.28:compile
[INFO] +- com.azure:azure-core:jar:1.15.0:compile
[INFO] |  +- com.fasterxml.jackson.core:jackson-annotations:jar:2.12.2:compile
[INFO] |  +- com.fasterxml.jackson.core:jackson-core:jar:2.12.2:compile
[INFO] |  +- com.fasterxml.jackson.core:jackson-databind:jar:2.12.2:compile
[INFO] |  +- com.fasterxml.jackson.datatype:jackson-datatype-jsr310:jar:2.12.2:compile
[INFO] |  +- com.fasterxml.jackson.dataformat:jackson-dataformat-xml:jar:2.12.2:compile
[INFO] |  |  +- com.fasterxml.jackson.module:jackson-module-jaxb-annotations:jar:2.12.2:compile
[INFO] |  |  |  +- jakarta.xml.bind:jakarta.xml.bind-api:jar:2.3.2:compile
[INFO] |  |  |  \- jakarta.activation:jakarta.activation-api:jar:1.2.1:compile
[INFO] |  |  +- org.codehaus.woodstox:stax2-api:jar:4.2.1:compile
[INFO] |  |  \- com.fasterxml.woodstox:woodstox-core:jar:6.2.4:compile
[INFO] |  +- io.projectreactor:reactor-core:jar:3.4.3:compile
[INFO] |  |  \- org.reactivestreams:reactive-streams:jar:1.0.3:compile
[INFO] |  \- io.netty:netty-tcnative-boringssl-static:jar:2.0.36.Final:compile
[INFO] +- com.azure:azure-storage-common:jar:12.10.1:compile
[INFO] |  \- com.azure:azure-core-http-netty:jar:1.7.1:compile
[INFO] |     +- io.netty:netty-handler:jar:4.1.54.Final:compile
[INFO] |     |  +- io.netty:netty-common:jar:4.1.54.Final:compile
[INFO] |     |  +- io.netty:netty-resolver:jar:4.1.54.Final:compile
[INFO] |     |  +- io.netty:netty-transport:jar:4.1.54.Final:compile
[INFO] |     |  \- io.netty:netty-codec:jar:4.1.54.Final:compile
[INFO] |     +- io.netty:netty-handler-proxy:jar:4.1.54.Final:compile
[INFO] |     |  \- io.netty:netty-codec-socks:jar:4.1.54.Final:compile
[INFO] |     +- io.netty:netty-buffer:jar:4.1.54.Final:compile
[INFO] |     +- io.netty:netty-codec-http:jar:4.1.54.Final:compile
[INFO] |     +- io.netty:netty-codec-http2:jar:4.1.54.Final:compile
[INFO] |     +- io.netty:netty-transport-native-unix-common:jar:4.1.54.Final:compile
[INFO] |     +- io.netty:netty-transport-native-epoll:jar:linux-x86_64:4.1.54.Final:compile
[INFO] |     +- io.netty:netty-transport-native-kqueue:jar:osx-x86_64:4.1.54.Final:compile
[INFO] |     \- io.projectreactor.netty:reactor-netty:jar:0.9.15.RELEASE:compile
[INFO] +- org.springframework:spring-beans:jar:4.3.26.RELEASE:test
[INFO] +- org.springframework:spring-context:jar:4.3.26.RELEASE:test
[INFO] |  +- org.springframework:spring-aop:jar:4.3.26.RELEASE:test
[INFO] |  \- org.springframework:spring-expression:jar:4.3.26.RELEASE:test
[INFO] +- org.springframework:spring-core:jar:4.3.26.RELEASE:test
[INFO] |  \- commons-logging:commons-logging:jar:1.2:test
[INFO] +- junit:junit:jar:4.12:test
[INFO] |  \- org.hamcrest:hamcrest-core:jar:1.3:test
[INFO] \- org.javassist:javassist:jar:3.20.0-GA:test
[INFO]

**Comment by atris** [comment]
This is what my dependencies folder looks like:

`README.txt				azure-storage-blob-12.0.0.jar		ignite-control-utility			ignite-spring				slf4j-api-1.7.7.jar
annotations-16.0.3.jar			azure-storage-common-12.10.1.jar	ignite-core-2.11.0-SNAPSHOT.jar		licenses
azure-core-1.3.0-beta.1.jar		cache-api-1.0.0.jar			ignite-indexing				optional
azure-core-http-netty-1.7.1.jar		ignite-azure-2.11.0-SNAPSHOT.jar	ignite-shmem-1.0.0.jar			reactive-streams-1.0.3.jar`

**Comment by joshfree** [comment]
@alzimmermsft could you please assist with this dependency mismatch question and also share more info on the BOM?
/cc @gapra-msft

**Comment by alzimmermsft** [comment]
Thank you for filing this issue @atris, it appears the version of `azure-storage-blob` being used is much older than that other dependencies. There is a newer version of [`azure-storage-blob`](https://mvnrepository.com/artifact/com.azure/azure-storage-blob/12.10.1) available that has its dependencies aligned with the other Azure SDK libraries you are using. Additionally, if you don't want to manually manage dependencies the Azure SDKs periodically release a BOM ([azure-sdk-bom](https://mvnrepository.com/artifact/com.azure/azure-sdk-bom/1.0.2)) which will ensure dependencies alignment for you.

This is a quick overview on consuming the BOM: https://github.com/Azure/azure-sdk-for-java/tree/master/sdk/boms/azure-sdk-bom#getting-started

**Comment by atris** [comment]
@alzimmermsft Thanks! So I should just use the BOM and specify the dependencies listed in the POM on the BOM page?

**Comment by atris** [comment]
@alzimmermsft I tried the BOM instructions but saw an error:

My POM:

```
        <dependency>
            <groupId>com.azure</groupId>
            <artifactId>azure-sdk-bom</artifactId>
            <version>1.0.2</version>
            <type>pom</type>
            <scope>import</scope>
        </dependency>

        <dependency>
            <groupId>com.azure</groupId>
            <artifactId>azure-storage-blob</artifactId>
        </dependency>
        <dependency>
            <groupId>com.azure</groupId>
            <artifactId>azure-security-keyvault-secrets</artifactId>
        </dependency>
        <dependency>
            <groupId>com.azure</groupId>
            <artifactId>azure-identity</artifactId>
        </dependency>
```

IntelliJ says that the dependencies are not available

**Comment by alzimmermsft** [comment]
> @alzimmermsft I tried the BOM instructions but saw an error:
> 
> My POM:
> 
> ```
>         <dependency>
>             <groupId>com.azure</groupId>
>             <artifactId>azure-sdk-bom</artifactId>
>             <version>1.0.2</version>
>             <type>pom</type>
>             <scope>import</scope>
>         </dependency>
> 
>         <dependency>
>             <groupId>com.azure</groupId>
>             <artifactId>azure-storage-blob</artifactId>
>         </dependency>
>         <dependency>
>             <groupId>com.azure</groupId>
>             <artifactId>azure-security-keyvault-secrets</artifactId>
>         </dependency>
>         <dependency>
>             <groupId>com.azure</groupId>
>             <artifactId>azure-identity</artifactId>
>         </dependency>
> ```
> 
> IntelliJ says that the dependencies are not available

The BOM needs to be included in the `dependencyManagement` section.

```xml
<dependencyManagement>
  <dependencies>
    <dependency>
      <groupId>com.azure</groupId>
      <artifactId>azure-sdk-bom</artifactId>
      <version>1.0.2</version>
      <type>pom</type>
      <scope>import</scope>
    </dependency>
  </dependencies>
</dependencyManagement>

<dependencies>
  <dependency>
    <groupId>com.azure</groupId>
    <artifactId>azure-storage-blob</artifactId>
  </dependency>
  <dependency>
    <groupId>com.azure</groupId>
    <artifactId>azure-security-keyvault-secrets</artifactId>
  </dependency>
  <dependency>
    <groupId>com.azure</groupId>
    <artifactId>azure-identity</artifactId>
  </dependency>
</dependencies>
```

**Comment by atris** [comment]
@alzimmermsft Thanks!

I got this error:

```
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.7.0:compile (default-compile) on project ignite-azure: Compilation failure
[ERROR] /Users/atrisharma/ignite/modules/azure/src/main/java/org/apache/ignite/spi/discovery/tcp/ipfinder/azure/TcpDiscoveryAzureBlobStoreIpFinder.java:[256,86] cannot access com.azure.core.credential.AzureSasCredential
[ERROR]   class file for com.azure.core.credential.AzureSasCredential not found
```

My POM:

```
<dependency>
            <groupId>com.azure</groupId>
            <artifactId>azure-storage-blob</artifactId>
        </dependency>
        <dependency>
            <groupId>com.azure</groupId>
            <artifactId>azure-security-keyvault-secrets</artifactId>
        </dependency>
        <dependency>
            <groupId>com.azure</groupId>
            <artifactId>azure-identity</artifactId>
        </dependency>

        <dependency>
            <groupId>com.fasterxml.jackson.core</groupId>
            <artifactId>jackson-databind</artifactId>
        </dependency>
        <dependency>
            <groupId>io.projectreactor.netty</groupId>
            <artifactId>reactor-netty</artifactId>
        </dependency>
        <dependency>
            <groupId>org.slf4j</groupId>
            <artifactId>slf4j-api</artifactId>
        </dependency>
```

**Comment by atris** [comment]
@alzimmermsft Fixed that, but now getting this:

```
Caused by: org.springframework.beans.BeanInstantiationException: Failed to instantiate [org.apache.ignite.spi.discovery.tcp.ipfinder.azure.TcpDiscoveryAzureBlobStoreIpFinder]: No default constructor found; nested exception is java.lang.NoClassDefFoundError: com/azure/core/exception/HttpResponseException
	at org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:85)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.instantiateBean(AbstractAutowireCapableBeanFactory.java:1150)
	... 32 more
Caused by: java.lang.NoClassDefFoundError: com/azure/core/exception/HttpResponseException
	at java.base/java.lang.ClassLoader.defineClass1(Native Method)
	at java.base/java.lang.ClassLoader.defineClass(ClassLoader.java:1017)
	at java.base/java.security.SecureClassLoader.defineClass(SecureClassLoader.java:151)
	at java.base/jdk.internal.loader.BuiltinClassLoader.defineClass(BuiltinClassLoader.java:821)
	at java.base/jdk.internal.loader.BuiltinClassLoader.findClassOnClassPathOrNull(BuiltinClassLoader.java:719)
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClassOrNull(BuiltinClassLoader.java:642)
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:600)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:178)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:522)
	at java.base/java.lang.Class.getDeclaredConstructors0(Native Method)
	at java.base/java.lang.Class.privateGetDeclaredConstructors(Class.java:3215)
	at java.base/java.lang.Class.getConstructor0(Class.java:3420)
	at java.base/java.lang.Class.getDeclaredConstructor(Class.java:2631)
	at org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:80)
	... 33 more
Caused by: java.lang.ClassNotFoundException: com.azure.core.exception.HttpResponseException
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:602)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:178)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:522)
	... 47 more

```

**Comment by atris** [comment]
Tried resolving a bit but see many issues like this:

	... 28 more
Caused by: java.lang.NoClassDefFoundError: Lcom/azure/storage/common/StorageSharedKeyCredential;

Do I still need to manually import all of these?

**Comment by alzimmermsft** [comment]
Thanks for reporting these @atris, let me take a look into what is happening here as the Maven dependencies should be resolving as they previously were without needing to specify versions in your POM.

**Comment by atris** [comment]
Thank you. I am seeing Jackson related issues too, JFYI. Same thing, lack of dependency

**Comment by alzimmermsft** [comment]
Hi @atris, I haven't been able to re-create this yet. Is your application create a JAR or performing any shading which may be changing classpath information?

**Comment by atris** [comment]
My application is creating a top level JAR, which has a project jar that consists of Szure dependencies

**Comment by alzimmermsft** [comment]
@atris, is this JAR including all dependencies? I've had some scenarios where not building with dependencies results in these `ClassNotFoundException` or `MethodNotFoundException` errors.

This build plugin will ensure the JAR is built with dependencies:

```xml
<build>
  <plugins>
    <plugin>
      <artifactId>maven-assembly-plugin</artifactId>
      <configuration>
        <archive>
          <manifest>
            <mainClass>{your main class}</mainClass>
          </manifest>
        </archive>
        <descriptorRefs>
          <descriptorRef>jar-with-dependencies</descriptorRef>
        </descriptorRefs>
      </configuration>
    </plugin>
  </plugins>
</build>
```
