### ISSUE TITLE
[BUG]the return value of customized convert should follow Spring secuity standard

### ISSUE THREAD

**Issue by backwind1233** [Azure/azure-sdk-for-java#20388]
**Describe the bug**
by default, a bearer token in request will be convert into an AbstractAuthenticationToken object through spring security framwork, and the AbstractAuthenticationToken object's getName will get subject claim in the  bearer token.
but our customized AADB2CJwtBearerTokenAuthenticationConverter’s convert method does not follow the standard, which will cause some unexpected problem.

***Exception or Stack Trace***

**To Reproduce**

***Code Snippet***
```
 @Override
    public AbstractAuthenticationToken convert(Jwt jwt) {
        OAuth2AccessToken accessToken = new OAuth2AccessToken(
            OAuth2AccessToken.TokenType.BEARER, jwt.getTokenValue(), jwt.getIssuedAt(), jwt.getExpiresAt());
        Collection<GrantedAuthority> authorities = extractAuthorities(jwt);
        AADB2COAuth2AuthenticatedPrincipal principal = new AADB2COAuth2AuthenticatedPrincipal(
            jwt.getHeaders(), jwt.getClaims(), authorities, jwt.getTokenValue());
        return new BearerTokenAuthentication(principal, accessToken, authorities);
    }
```

**Expected behavior**

**Screenshots**

**Setup (please complete the following information):**
 
**Additional context**

**Information Checklist**

**Comment by ZhuXiaoBing-cn** [comment]
@backwind1233, You are right. `AbstractAuthenticationToken` object's getName will get a subject claim in the bearer token for the spring security framework.
But in our `AADB2CJwtBearerTokenAuthenticationConverter`, `Jwt` is converted into an implementation class `BearerTokenAuthentication` of `AbstractAuthenticationToken`, which has more flexible scalability.
However, an `OAuth2AuthenticatedPrincipal` object needs to be passed when constructing `BearerTokenAuthentication`, which will implement the getName method. I think what we need to change is the getName method in `OAuth2AuthenticatedPrincipal`.

**Comment by backwind1233** [comment]
@ZhuXiaoBing-cn  I suggest don't change the OAuth2AuthenticatedPrincipal's getName method, we can replace BearerTokenAuthentication with our own class

**Comment by saragluna** [comment]
@backwind1233 @ZhuXiaoBing-cn will this change in https://github.com/Azure/azure-sdk-for-java/pull/20340 also affect the Prinicipal we're talking in this thread?

**Comment by saragluna** [comment]
Okay, even though they're all implementing the `OAuth2AuthenticatedPrincipal`, `OAuth2User` and `DefaultOAuth2AuthenticatedPrincipal`. But only the `OAuth2User` could leverage the `usernameAttributeName` property. For this reason https://github.com/spring-projects/spring-security/blob/7ef3f619242816683a72b35a1f8b4fb4f32d5203/oauth2/oauth2-core/src/main/java/org/springframework/security/oauth2/core/user/OAuth2User.java#L33.
