### ISSUE TITLE
Azure SQL Database - Diagnostics logging delay

### ISSUE THREAD

**Issue by ShailashreeE** [Azure/azure-sdk-for-java#2039]
We would like to know what is the actual time delay for logging diagnostics data for Azure SQL Database

We have enabled diagnostics settings for an Azure SQL Database in Azure portal as shown below. 
<img width="702" alt="azsql1" src="https://user-images.githubusercontent.com/28895501/38421605-51b06bfe-39c5-11e8-86fa-9a482f64177d.png">

The diagnostics log files are found under the container **insights-metrics-pt1m** in Blob service. A .json file  is created at the start of every hour which contains the diagnostics data.
<img width="833" alt="azsql2" src="https://user-images.githubusercontent.com/28895501/38421977-b456f48e-39c6-11e8-9443-15793f8e0bf0.png">

Consider that the current UTC time is 11:18, the .json file containing the diagnostics data has the metrics only till 11:04(Uploaded the .json file in .txt format)
[PT1H.txt](https://github.com/Azure/azure-sdk-for-java/files/1884018/PT1H.txt)
But this time difference keeps on varying.

So we would like to know why there is a delay in logging diagnostics and if it can be minimized.
Also please let us know the actual time delay for the same.
Thanks in advance.

**Comment by milismsft** [comment]
@ShailashreeE after taking a quick look at the REST endpoints that the SQL service provides for this feature I don't see anything that can let me believe we can configure the time delay (or how often to upload the diagnostics)... I will try to follow up with the Azure Insights team but for now I don't see anything that can be done to change this from the Java SDK perspective.

**Comment by vhvb1989** [comment]
Hello @ShailashreeE 

I am sorry about you didn't get a sooner answer on this
Do you still need help on this? Let me know and I would be happy to help.

Note: As part of repository cleaning effort, this issue will be closed by **Nov 11** if no response is received from submitter and/or not further action is required.
