### ISSUE TITLE
[QUERY] spring cosmos 3.5.1 is backward compaitable in spring boot

### ISSUE THREAD

**Issue by s998899** [Azure/azure-sdk-for-java#20391]
**Query/Question**
I tried to use spring cosmos 3.5.1 in spring boot 2.2 but getting 	NoClassDefFoundError: reactor.util.context.ContextView.
if incase of updating the spring boot is only way or any way without updating spring boot because of i need to use spring boot 2.2 version

and also there 3.4.0 auditing bug where it will not update createdate and createdby.

***Why is this not a Bug or a feature Request?***
a kinda query 

**Setup (please complete the following information if applicable):**
 - OS: windows
 - IDE : IntelliJ
 - Version of the Library used 3.4.0

**Comment by chenrujun** [comment]
`spring-boot: 2.2.9.RELEASE` managed `reactor-core` version: 3.3.8.RELEASE.
Refs:
1. https://repo.maven.apache.org/maven2/org/springframework/boot/spring-boot-dependencies/2.2.9.RELEASE/spring-boot-dependencies-2.2.9.RELEASE.pom
2. https://repo1.maven.org/maven2/io/projectreactor/reactor-bom/Dysprosium-SR10/reactor-bom-Dysprosium-SR10.pom

`azure-spring-data-cosmos: 3.5.0` required `reactor-core` version: 3.4.3.
Refs:
1. https://github.com/Azure/azure-sdk-for-java/blob/azure-spring-data-cosmos_3.5.0/eng/versioning/external_dependencies.txt#L62

---
My suggestion: 

 - Solution 1: Add following content in pom.xml:
```
    <dependency>
      <groupId>io.projectreactor</groupId>
      <artifactId>reactor-core</artifactId>
      <version>3.4.3</version>
    </dependency>
```
 - Solution 2: Upgrade to spring-boot:2.4.3.

If problem still exists after the 2 solutions, please share your pom.xml.

**Comment by s998899** [comment]
look like reactor netty has incompitable with below 2.4 versions [https://github.com/reactor/reactor-netty/issues/1388](url)

i can't update my spring boot version to 2.4 now we need to maintain version as 2.2.4. so then how can i use latest cosmos without upgrading spring boot
