### ISSUE TITLE
Release stable versions of Cognitive services Bing API SDKs

### ISSUE THREAD

**Issue by kirthik** [Azure/azure-sdk-for-java#2040]
Title says it all. Please release stable version of Cognitive Services Bing API SDKs and update samples to use stable versions of the packages.

This must be completed before //build.

**Comment by kirthik** [comment]
Also release Visual search SDK in preview (https://github.com/Azure/azure-rest-api-specs/tree/master/specification/cognitiveservices/data-plane/VisualSearch)

**Comment by praries880** [comment]
Closing the issue. @kirthik  Kindly feel free to re-open it if the need be.
