### ISSUE TITLE
Use of SHA-1 in HostNameSslBindingImpl.java

### ISSUE THREAD

**Issue by ptsankov** [Azure/azure-sdk-for-java#2041]
Our static analyzer flags the use of SHA1 in HostNameSslBindingImpl.java:

MessageDigest sha = MessageDigest.getInstance("SHA-1");

It is recommended to switch to SHA-256 as it is more secure than SHA-1.

**Comment by ptsankov** [comment]
Several other uses of the older hash function:

- EncryptionUtils.java
- BrokerProxy.java
- PackageHelper.java

**Comment by yungezz** [comment]
hi @weidongxu-microsoft could you pls have a look? thanks

**Comment by weidongxu-microsoft** [comment]
@ptsankov 

X509 thumbprint is generated using SHA-1. Changing it to SHA-256 will like break Java client with everything else.
https://docs.microsoft.com/en-us/dotnet/api/system.security.cryptography.x509certificates.x509certificate2.thumbprint?view=netcore-3.1

The thumbprint is only used for finding a certificate from a store. It is not a signature, hence it does not really require all the security of a signature.

**Comment by yungezz** [comment]
hi @ptsankov does above comment make sense to you?

**Comment by yungezz** [comment]
close the issue now. Feel free to create new issue if any other ask, thanks.
