### ISSUE TITLE
Unable to generate valid javadocs due to errors in azure-media module

### ISSUE THREAD

**Issue by JonathanGiles** [Azure/azure-sdk-for-java#2042]
The following errors mean that we can not consider the JavaDocs generated by the entire azure-sdk-for-java as valid. Ideally we would see all of these issues resolved so that we can generate valid JavaDoc for this project.

[ERROR] /Users/jonathan/Code/azure/projects/azure-javadocs/azure-sdk-for-java/azure-media/src/main/java/com/microsoft/windowsazure/services/queue/QueueContract.java:39: error: reference not found
[ERROR]  * methods associate a {@link Configuration} with the implementation, so the
[ERROR]                               ^
[ERROR] /Users/jonathan/Code/azure/projects/azure-javadocs/azure-sdk-for-java/azure-media/src/main/java/com/microsoft/windowsazure/services/blob/models/AccessCondition.java:205: error: reference not found
[ERROR]      * @throws StorageException
[ERROR]        ^
[ERROR] /Users/jonathan/Code/azure/projects/azure-javadocs/azure-sdk-for-java/azure-media/src/main/java/com/microsoft/windowsazure/services/blob/models/AccessCondition.java:223: error: reference not found
[ERROR]      * @throws StorageException
[ERROR]        ^
[ERROR] /Users/jonathan/Code/azure/projects/azure-javadocs/azure-sdk-for-java/azure-media/src/main/java/com/microsoft/windowsazure/services/blob/models/AcquireLeaseOptions.java:22: error: reference not found
[ERROR]  * {@link com.microsoft.windowsazure.services.blob.BlobContract#acquireLease(String, String, AcquireLeaseOptions)
[ERROR]           ^
[ERROR] /Users/jonathan/Code/azure/projects/azure-javadocs/azure-sdk-for-java/azure-media/src/main/java/com/microsoft/windowsazure/services/blob/models/AcquireLeaseResult.java:21: error: reference not found
[ERROR]  * {@link com.microsoft.windowsazure.services.blob.BlobContract#acquireLease(String, String)},
[ERROR]           ^
[ERROR] /Users/jonathan/Code/azure/projects/azure-javadocs/azure-sdk-for-java/azure-media/src/main/java/com/microsoft/windowsazure/services/blob/models/AcquireLeaseResult.java:22: error: reference not found
[ERROR]  * {@link com.microsoft.windowsazure.services.blob.BlobContract#acquireLease(String, String, AcquireLeaseOptions)},
[ERROR]           ^
[ERROR] /Users/jonathan/Code/azure/projects/azure-javadocs/azure-sdk-for-java/azure-media/src/main/java/com/microsoft/windowsazure/services/blob/models/AcquireLeaseResult.java:23: error: reference not found
[ERROR]  * {@link com.microsoft.windowsazure.services.blob.BlobContract#renewLease(String, String, String, BlobServiceOptions)},
[ERROR]           ^
[ERROR] /Users/jonathan/Code/azure/projects/azure-javadocs/azure-sdk-for-java/azure-media/src/main/java/com/microsoft/windowsazure/services/blob/models/AcquireLeaseResult.java:24: error: reference not found
[ERROR]  * and {@link com.microsoft.windowsazure.services.blob.BlobContract#renewLease(String, String, String)}.
[ERROR]               ^
[ERROR] /Users/jonathan/Code/azure/projects/azure-javadocs/azure-sdk-for-java/azure-media/src/main/java/com/microsoft/windowsazure/services/blob/models/BreakLeaseResult.java:21: error: reference not found
[ERROR]  * {@link com.microsoft.windowsazure.services.blob.BlobContract#breakLease(String, String, BlobServiceOptions)}
[ERROR]           ^
[ERROR] /Users/jonathan/Code/azure/projects/azure-javadocs/azure-sdk-for-java/azure-media/src/main/java/com/microsoft/windowsazure/services/blob/models/ContainerACL.java:69: error: reference not found
[ERROR]      * {@link com.microsoft.windowsazure.services.blob.BlobContract#setContainerACL(String, ContainerACL)} or
[ERROR]               ^
[ERROR] /Users/jonathan/Code/azure/projects/azure-javadocs/azure-sdk-for-java/azure-media/src/main/java/com/microsoft/windowsazure/services/blob/models/ContainerACL.java:70: error: reference not found
[ERROR]      * {@link com.microsoft.windowsazure.services.blob.BlobContract#setContainerACL(String, ContainerACL, BlobServiceOptions)}.
[ERROR]               ^
[ERROR] /Users/jonathan/Code/azure/projects/azure-javadocs/azure-sdk-for-java/azure-media/src/main/java/com/microsoft/windowsazure/services/blob/models/ContainerACL.java:102: error: reference not found
[ERROR]      * {@link com.microsoft.windowsazure.services.blob.BlobContract#setContainerACL(String, ContainerACL)} or
[ERROR]               ^
[ERROR] /Users/jonathan/Code/azure/projects/azure-javadocs/azure-sdk-for-java/azure-media/src/main/java/com/microsoft/windowsazure/services/blob/models/ContainerACL.java:103: error: reference not found
[ERROR]      * {@link com.microsoft.windowsazure.services.blob.BlobContract#setContainerACL(String, ContainerACL, BlobServiceOptions)}.
[ERROR]               ^
[ERROR] /Users/jonathan/Code/azure/projects/azure-javadocs/azure-sdk-for-java/azure-media/src/main/java/com/microsoft/windowsazure/services/blob/models/ContainerACL.java:134: error: reference not found
[ERROR]      * {@link com.microsoft.windowsazure.services.blob.BlobContract#setContainerACL(String, ContainerACL)} or
[ERROR]               ^
[ERROR] /Users/jonathan/Code/azure/projects/azure-javadocs/azure-sdk-for-java/azure-media/src/main/java/com/microsoft/windowsazure/services/blob/models/ContainerACL.java:135: error: reference not found
[ERROR]      * {@link com.microsoft.windowsazure.services.blob.BlobContract#setContainerACL(String, ContainerACL, BlobServiceOptions)}.
[ERROR]               ^
[ERROR] /Users/jonathan/Code/azure/projects/azure-javadocs/azure-sdk-for-java/azure-media/src/main/java/com/microsoft/windowsazure/services/blob/models/ContainerACL.java:168: error: reference not found
[ERROR]      * {@link com.microsoft.windowsazure.services.blob.BlobContract#setContainerACL(String, ContainerACL)} or
[ERROR]               ^
[ERROR] /Users/jonathan/Code/azure/projects/azure-javadocs/azure-sdk-for-java/azure-media/src/main/java/com/microsoft/windowsazure/services/blob/models/ContainerACL.java:169: error: reference not found
[ERROR]      * {@link com.microsoft.windowsazure.services.blob.BlobContract#setContainerACL(String, ContainerACL, BlobServiceOptions)}.
[ERROR]               ^
[ERROR] /Users/jonathan/Code/azure/projects/azure-javadocs/azure-sdk-for-java/azure-media/src/main/java/com/microsoft/windowsazure/services/blob/models/ContainerACL.java:213: error: reference not found
[ERROR]      * {@link com.microsoft.windowsazure.services.blob.BlobContract#setContainerACL(String, ContainerACL)} or
[ERROR]               ^
[ERROR] /Users/jonathan/Code/azure/projects/azure-javadocs/azure-sdk-for-java/azure-media/src/main/java/com/microsoft/windowsazure/services/blob/models/ContainerACL.java:214: error: reference not found
[ERROR]      * {@link com.microsoft.windowsazure.services.blob.BlobContract#setContainerACL(String, ContainerACL, BlobServiceOptions)}.
[ERROR]               ^
[ERROR] /Users/jonathan/Code/azure/projects/azure-javadocs/azure-sdk-for-java/azure-media/src/main/java/com/microsoft/windowsazure/services/blob/models/ContainerACL.java:30: error: reference not found
[ERROR]  * calls to implementations of {@link com.microsoft.windowsazure.services.blob.BlobContract#getContainerACL(String)} and
[ERROR]                                       ^
[ERROR] /Users/jonathan/Code/azure/projects/azure-javadocs/azure-sdk-for-java/azure-media/src/main/java/com/microsoft/windowsazure/services/blob/models/ContainerACL.java:31: error: reference not found
[ERROR]  * {@link com.microsoft.windowsazure.services.blob.BlobContract#getContainerACL(String, BlobServiceOptions)}, and passed
[ERROR]           ^
[ERROR] /Users/jonathan/Code/azure/projects/azure-javadocs/azure-sdk-for-java/azure-media/src/main/java/com/microsoft/windowsazure/services/blob/models/ContainerACL.java:33: error: reference not found
[ERROR]  * {@link com.microsoft.windowsazure.services.blob.BlobContract#setContainerACL(String, ContainerACL)} and
[ERROR]           ^
[ERROR] /Users/jonathan/Code/azure/projects/azure-javadocs/azure-sdk-for-java/azure-media/src/main/java/com/microsoft/windowsazure/services/blob/models/ContainerACL.java:34: error: reference not found
[ERROR]  * {@link com.microsoft.windowsazure.services.blob.BlobContract#setContainerACL(String, ContainerACL, BlobServiceOptions)}
[ERROR]           ^
[ERROR] /Users/jonathan/Code/azure/projects/azure-javadocs/azure-sdk-for-java/azure-media/src/main/java/com/microsoft/windowsazure/services/blob/models/CopyBlobOptions.java:23: error: reference not found
[ERROR]  * {@link com.microsoft.windowsazure.services.blob.BlobContract#copyBlob(String, String, String, String, CopyBlobOptions)
[ERROR]           ^
[ERROR] /Users/jonathan/Code/azure/projects/azure-javadocs/azure-sdk-for-java/azure-media/src/main/java/com/microsoft/windowsazure/services/blob/models/CopyBlobResult.java:22: error: reference not found
[ERROR]  * {@link com.microsoft.windowsazure.services.blob.BlobContract#copyBlob(String, String, String, String, CopyBlobOptions)}
[ERROR]           ^
[ERROR] /Users/jonathan/Code/azure/projects/azure-javadocs/azure-sdk-for-java/azure-media/src/main/java/com/microsoft/windowsazure/services/blob/models/CreateBlobOptions.java:23: error: reference not found
[ERROR]  * {@link com.microsoft.windowsazure.services.blob.BlobContract#createPageBlob(String, String, long, CreateBlobOptions)
[ERROR]           ^
[ERROR] /Users/jonathan/Code/azure/projects/azure-javadocs/azure-sdk-for-java/azure-media/src/main/java/com/microsoft/windowsazure/services/blob/models/CreateBlobPagesOptions.java:21: error: reference not found
[ERROR]  * {@link com.microsoft.windowsazure.services.blob.BlobContract#createBlobPages(String, String, PageRange, long, java.io.InputStream, CreateBlobPagesOptions)}
[ERROR]           ^
[ERROR] /Users/jonathan/Code/azure/projects/azure-javadocs/azure-sdk-for-java/azure-media/src/main/java/com/microsoft/windowsazure/services/blob/models/CreateBlobPagesResult.java:22: error: reference not found
[ERROR]  * {@link com.microsoft.windowsazure.services.blob.BlobContract#clearBlobPages(String, String, PageRange)},
[ERROR]           ^
[ERROR] /Users/jonathan/Code/azure/projects/azure-javadocs/azure-sdk-for-java/azure-media/src/main/java/com/microsoft/windowsazure/services/blob/models/CreateBlobPagesResult.java:23: error: reference not found
[ERROR]  * {@link com.microsoft.windowsazure.services.blob.BlobContract#clearBlobPages(String, String, PageRange, CreateBlobPagesOptions)}
[ERROR]           ^
[ERROR] /Users/jonathan/Code/azure/projects/azure-javadocs/azure-sdk-for-java/azure-media/src/main/java/com/microsoft/windowsazure/services/blob/models/CreateBlobPagesResult.java:25: error: reference not found
[ERROR]  * {@link com.microsoft.windowsazure.services.blob.BlobContract#createBlobPages(String, String, PageRange, long, java.io.InputStream)}
[ERROR]           ^
[ERROR] /Users/jonathan/Code/azure/projects/azure-javadocs/azure-sdk-for-java/azure-media/src/main/java/com/microsoft/windowsazure/services/blob/models/CreateBlobPagesResult.java:27: error: reference not found
[ERROR]  * {@link com.microsoft.windowsazure.services.blob.BlobContract#createBlobPages(String, String, PageRange, long, java.io.InputStream, CreateBlobPagesOptions)}
[ERROR]           ^
[ERROR] /Users/jonathan/Code/azure/projects/azure-javadocs/azure-sdk-for-java/azure-media/src/main/java/com/microsoft/windowsazure/services/blob/models/CreateBlobResult.java:22: error: reference not found
[ERROR]  * {@link com.microsoft.windowsazure.services.blob.BlobContract#createPageBlob(String, String, long, CreateBlobOptions)}
[ERROR]           ^
[ERROR] /Users/jonathan/Code/azure/projects/azure-javadocs/azure-sdk-for-java/azure-media/src/main/java/com/microsoft/windowsazure/services/blob/models/CreateBlobSnapshotOptions.java:23: error: reference not found
[ERROR]  * {@link com.microsoft.windowsazure.services.blob.BlobContract#createBlobSnapshot(String, String, CreateBlobSnapshotOptions)
[ERROR]           ^
[ERROR] /Users/jonathan/Code/azure/projects/azure-javadocs/azure-sdk-for-java/azure-media/src/main/java/com/microsoft/windowsazure/services/blob/models/CreateBlobSnapshotResult.java:22: error: reference not found
[ERROR]  * {@link com.microsoft.windowsazure.services.blob.BlobContract#createBlobSnapshot(String, String)} and
[ERROR]           ^
[ERROR] /Users/jonathan/Code/azure/projects/azure-javadocs/azure-sdk-for-java/azure-media/src/main/java/com/microsoft/windowsazure/services/blob/models/CreateBlobSnapshotResult.java:23: error: reference not found
[ERROR]  * {@link com.microsoft.windowsazure.services.blob.BlobContract#createBlobSnapshot(String, String, CreateBlobSnapshotOptions)}
[ERROR]           ^
[ERROR] /Users/jonathan/Code/azure/projects/azure-javadocs/azure-sdk-for-java/azure-media/src/main/java/com/microsoft/windowsazure/services/blob/models/DeleteBlobOptions.java:137: error: reference not found
[ERROR]      * {@link StorageException} is thrown.
[ERROR]               ^
[ERROR] /Users/jonathan/Code/azure/projects/azure-javadocs/azure-sdk-for-java/azure-media/src/main/java/com/microsoft/windowsazure/services/blob/models/GetBlobMetadataOptions.java:21: error: reference not found
[ERROR]  * {@link com.microsoft.windowsazure.services.blob.BlobContract#getBlobMetadata(String, String, GetBlobMetadataOptions)
[ERROR]           ^
[ERROR] /Users/jonathan/Code/azure/projects/azure-javadocs/azure-sdk-for-java/azure-media/src/main/java/com/microsoft/windowsazure/services/blob/models/GetBlobMetadataResult.java:23: error: reference not found
[ERROR]  * {@link com.microsoft.windowsazure.services.blob.BlobContract#getBlobMetadata(String, String)} and
[ERROR]           ^
[ERROR] /Users/jonathan/Code/azure/projects/azure-javadocs/azure-sdk-for-java/azure-media/src/main/java/com/microsoft/windowsazure/services/blob/models/GetBlobMetadataResult.java:24: error: reference not found
[ERROR]  * {@link com.microsoft.windowsazure.services.blob.BlobContract#getBlobMetadata(String, String, GetBlobMetadataOptions)}.
[ERROR]           ^
[ERROR] /Users/jonathan/Code/azure/projects/azure-javadocs/azure-sdk-for-java/azure-media/src/main/java/com/microsoft/windowsazure/services/blob/models/GetContainerACLResult.java:21: error: reference not found
[ERROR]  * {@link com.microsoft.windowsazure.services.blob.BlobContract#getContainerACL(String)} and
[ERROR]           ^
[ERROR] /Users/jonathan/Code/azure/projects/azure-javadocs/azure-sdk-for-java/azure-media/src/main/java/com/microsoft/windowsazure/services/blob/models/GetContainerACLResult.java:22: error: reference not found
[ERROR]  * {@link com.microsoft.windowsazure.services.blob.BlobContract#getContainerACL(String, BlobServiceOptions)}.
[ERROR]           ^
[ERROR] /Users/jonathan/Code/azure/projects/azure-javadocs/azure-sdk-for-java/azure-media/src/main/java/com/microsoft/windowsazure/services/blob/models/GetContainerPropertiesResult.java:24: error: reference not found
[ERROR]  * {@link com.microsoft.windowsazure.services.blob.BlobContract#getContainerProperties(String)},
[ERROR]           ^
[ERROR] /Users/jonathan/Code/azure/projects/azure-javadocs/azure-sdk-for-java/azure-media/src/main/java/com/microsoft/windowsazure/services/blob/models/GetContainerPropertiesResult.java:25: error: reference not found
[ERROR]  * {@link com.microsoft.windowsazure.services.blob.BlobContract#getContainerProperties(String, BlobServiceOptions)},
[ERROR]           ^
[ERROR] /Users/jonathan/Code/azure/projects/azure-javadocs/azure-sdk-for-java/azure-media/src/main/java/com/microsoft/windowsazure/services/blob/models/GetContainerPropertiesResult.java:26: error: reference not found
[ERROR]  * {@link com.microsoft.windowsazure.services.blob.BlobContract#getContainerMetadata(String)}, and
[ERROR]           ^
[ERROR] /Users/jonathan/Code/azure/projects/azure-javadocs/azure-sdk-for-java/azure-media/src/main/java/com/microsoft/windowsazure/services/blob/models/GetContainerPropertiesResult.java:27: error: reference not found
[ERROR]  * {@link com.microsoft.windowsazure.services.blob.BlobContract#getContainerMetadata(String, BlobServiceOptions)}.
[ERROR]           ^
[ERROR] /Users/jonathan/Code/azure/projects/azure-javadocs/azure-sdk-for-java/azure-media/src/main/java/com/microsoft/windowsazure/services/blob/models/GetServicePropertiesResult.java:39: error: reference not found
[ERROR]      * {@link com.microsoft.windowsazure.services.blob.BlobContract#setServiceProperties} method and pass the modified
[ERROR]               ^
[ERROR] /Users/jonathan/Code/azure/projects/azure-javadocs/azure-sdk-for-java/azure-media/src/main/java/com/microsoft/windowsazure/services/blob/models/GetServicePropertiesResult.java:21: error: reference not found
[ERROR]  * {@link com.microsoft.windowsazure.services.blob.BlobContract#getServiceProperties()} and
[ERROR]           ^
[ERROR] /Users/jonathan/Code/azure/projects/azure-javadocs/azure-sdk-for-java/azure-media/src/main/java/com/microsoft/windowsazure/services/blob/models/GetServicePropertiesResult.java:22: error: reference not found
[ERROR]  * {@link com.microsoft.windowsazure.services.blob.BlobContract#getServiceProperties(BlobServiceOptions)}.
[ERROR]           ^
[ERROR] /Users/jonathan/Code/azure/projects/azure-javadocs/azure-sdk-for-java/azure-media/src/main/java/com/microsoft/windowsazure/services/blob/models/ListBlobRegionsOptions.java:21: error: reference not found
[ERROR]  * {@link com.microsoft.windowsazure.services.blob.BlobContract#listBlobRegions(String, String, ListBlobRegionsOptions)
[ERROR]           ^
[ERROR] /Users/jonathan/Code/azure/projects/azure-javadocs/azure-sdk-for-java/azure-media/src/main/java/com/microsoft/windowsazure/services/blob/models/ListBlobRegionsResult.java:26: error: reference not found
[ERROR]  * {@link com.microsoft.windowsazure.services.blob.BlobContract#listBlobRegions(String, String, ListBlobRegionsOptions)}.
[ERROR]           ^
[ERROR] /Users/jonathan/Code/azure/projects/azure-javadocs/azure-sdk-for-java/azure-media/src/main/java/com/microsoft/windowsazure/services/blob/models/ListBlobsOptions.java:110: error: reference not found
[ERROR]      * {@link com.microsoft.windowsazure.services.blob.BlobContract#listBlobs(String, ListBlobsOptions)} call to get the
[ERROR]               ^
[ERROR] /Users/jonathan/Code/azure/projects/azure-javadocs/azure-sdk-for-java/azure-media/src/main/java/com/microsoft/windowsazure/services/blob/models/ListBlobsOptions.java:155: error: reference not found
[ERROR]      * {@link com.microsoft.windowsazure.services.blob.BlobContract#listBlobs(String, ListBlobsOptions)} call to get the
[ERROR]               ^
[ERROR] /Users/jonathan/Code/azure/projects/azure-javadocs/azure-sdk-for-java/azure-media/src/main/java/com/microsoft/windowsazure/services/blob/models/ListBlobsOptions.java:20: error: reference not found
[ERROR]  * {@link com.microsoft.windowsazure.services.blob.BlobContract#listBlobs(String, ListBlobsOptions)} request. These
[ERROR]           ^
[ERROR] /Users/jonathan/Code/azure/projects/azure-javadocs/azure-sdk-for-java/azure-media/src/main/java/com/microsoft/windowsazure/services/blob/models/ListBlobsResult.java:200: error: reference not found
[ERROR]      * {@link com.microsoft.windowsazure.services.blob.BlobContract#listBlobs(String, ListBlobsOptions) listBlobs} call
[ERROR]               ^
[ERROR] /Users/jonathan/Code/azure/projects/azure-javadocs/azure-sdk-for-java/azure-media/src/main/java/com/microsoft/windowsazure/services/blob/models/ListBlobsResult.java:242: error: reference not found
[ERROR]      * {@link com.microsoft.windowsazure.services.blob.BlobContract#listBlobs(String, ListBlobsOptions) listBlobs} call
[ERROR]               ^
[ERROR] /Users/jonathan/Code/azure/projects/azure-javadocs/azure-sdk-for-java/azure-media/src/main/java/com/microsoft/windowsazure/services/blob/models/ListBlobsResult.java:286: error: reference not found
[ERROR]      * {@link com.microsoft.windowsazure.services.blob.BlobContract#listBlobs(String, ListBlobsOptions) listBlobs} call
[ERROR]               ^
[ERROR] /Users/jonathan/Code/azure/projects/azure-javadocs/azure-sdk-for-java/azure-media/src/main/java/com/microsoft/windowsazure/services/blob/models/ListBlobsResult.java:34: error: reference not found
[ERROR]  * {@link com.microsoft.windowsazure.services.blob.BlobContract#listBlobs(String)} and
[ERROR]           ^
[ERROR] /Users/jonathan/Code/azure/projects/azure-javadocs/azure-sdk-for-java/azure-media/src/main/java/com/microsoft/windowsazure/services/blob/models/ListBlobsResult.java:35: error: reference not found
[ERROR]  * {@link com.microsoft.windowsazure.services.blob.BlobContract#listBlobs(String, ListBlobsOptions)}.
[ERROR]           ^
[ERROR] /Users/jonathan/Code/azure/projects/azure-javadocs/azure-sdk-for-java/azure-media/src/main/java/com/microsoft/windowsazure/services/blob/models/ServiceProperties.java:23: error: reference not found
[ERROR]  * {@link com.microsoft.windowsazure.services.blob.BlobContract#getServiceProperties()} method to return the service
[ERROR]           ^
[ERROR] /Users/jonathan/Code/azure/projects/azure-javadocs/azure-sdk-for-java/azure-media/src/main/java/com/microsoft/windowsazure/services/blob/models/ServiceProperties.java:25: error: reference not found
[ERROR]  * {@link com.microsoft.windowsazure.services.blob.BlobContract#setServiceProperties(ServiceProperties)} and
[ERROR]           ^
[ERROR] /Users/jonathan/Code/azure/projects/azure-javadocs/azure-sdk-for-java/azure-media/src/main/java/com/microsoft/windowsazure/services/blob/models/ServiceProperties.java:26: error: reference not found
[ERROR]  * {@link com.microsoft.windowsazure.services.blob.BlobContract#setServiceProperties(ServiceProperties, BlobServiceOptions)}
[ERROR]           ^
[ERROR] /Users/jonathan/Code/azure/projects/azure-javadocs/azure-sdk-for-java/azure-media/src/main/java/com/microsoft/windowsazure/services/blob/models/SetBlobMetadataOptions.java:21: error: reference not found
[ERROR]  * {@link com.microsoft.windowsazure.services.blob.BlobContract#setBlobMetadata(String, String, java.util.HashMap, SetBlobMetadataOptions)
[ERROR]           ^
[ERROR] /Users/jonathan/Code/azure/projects/azure-javadocs/azure-sdk-for-java/azure-media/src/main/java/com/microsoft/windowsazure/services/blob/models/SetBlobMetadataResult.java:22: error: reference not found
[ERROR]  * {@link com.microsoft.windowsazure.services.blob.BlobContract#setBlobMetadata(String, String, java.util.HashMap, SetBlobMetadataOptions)}
[ERROR]           ^
[ERROR] /Users/jonathan/Code/azure/projects/azure-javadocs/azure-sdk-for-java/azure-media/src/main/java/com/microsoft/windowsazure/services/blob/models/SetBlobPropertiesOptions.java:21: error: reference not found
[ERROR]  * {@link com.microsoft.windowsazure.services.blob.BlobContract#setBlobProperties(String, String, SetBlobPropertiesOptions)
[ERROR]           ^
[ERROR] /Users/jonathan/Code/azure/projects/azure-javadocs/azure-sdk-for-java/azure-media/src/main/java/com/microsoft/windowsazure/services/blob/models/SetBlobPropertiesResult.java:22: error: reference not found
[ERROR]  * {@link com.microsoft.windowsazure.services.blob.BlobContract#setBlobProperties(String, String, SetBlobPropertiesOptions)}
[ERROR]           ^
[ERROR] /Users/jonathan/Code/azure/projects/azure-javadocs/azure-sdk-for-java/azure-media/src/main/java/com/microsoft/windowsazure/services/blob/models/SetContainerMetadataOptions.java:21: error: reference not found
[ERROR]  * {@link com.microsoft.windowsazure.services.blob.BlobContract#setContainerMetadata(String, java.util.HashMap, SetContainerMetadataOptions)}
[ERROR]           ^
[ERROR] /Users/jonathan/Code/azure/projects/azure-javadocs/azure-sdk-for-java/azure-media/src/main/java/com/microsoft/windowsazure/services/media/OperationUtils.java:46: error: @param name not found
[ERROR]      * @param operation
[ERROR]               ^
[ERROR] /Users/jonathan/Code/azure/projects/azure-javadocs/azure-sdk-for-java/azure-media/src/main/java/com/microsoft/windowsazure/services/media/entityoperations/EntityOperation.java:42: error: exception not thrown: com.microsoft.windowsazure.exception.ServiceException
[ERROR]      * @throws ServiceException
[ERROR]                ^
[ERROR] /Users/jonathan/Code/azure/projects/azure-javadocs/azure-sdk-for-java/azure-media/src/main/java/com/microsoft/windowsazure/services/media/models/AssetDeliveryPolicy.java:47: error: @param name not found
[ERROR]      * @param name
[ERROR]               ^
[ERROR] /Users/jonathan/Code/azure/projects/azure-javadocs/azure-sdk-for-java/azure-media/src/main/java/com/microsoft/windowsazure/services/media/models/AssetDeliveryPolicy.java:166: error: @param name not found
[ERROR]      * @param contentKeyAuthorizationPolicyId
[ERROR]               ^
[ERROR] /Users/jonathan/Code/azure/projects/azure-javadocs/azure-sdk-for-java/azure-media/src/main/java/com/microsoft/windowsazure/services/media/models/AssetDeliveryPolicyConfigurationKey.java:29: error: unknown tag: Guid
[ERROR]     /** Base key url that will have KID=<Guid> appended for Envelope. */
[ERROR]                                         ^
[ERROR] /Users/jonathan/Code/azure/projects/azure-javadocs/azure-sdk-for-java/azure-media/src/main/java/com/microsoft/windowsazure/services/media/models/AssetDeliveryPolicyConfigurationKey.java:45: error: unknown tag: Guid
[ERROR]     /** Base FairPlay license acquisition URL that will have KID=<Guid> appended. */
[ERROR]                                                                  ^
[ERROR] /Users/jonathan/Code/azure/projects/azure-javadocs/azure-sdk-for-java/azure-media/src/main/java/com/microsoft/windowsazure/services/media/models/AssetDeliveryPolicyConfigurationKey.java:41: error: unknown tag: Guid
[ERROR]     /** Base Widevine url that will have KID=<Guid> appended */
[ERROR]                                              ^
[ERROR] /Users/jonathan/Code/azure/projects/azure-javadocs/azure-sdk-for-java/azure-media/src/main/java/com/microsoft/windowsazure/services/media/models/AssetDeliveryProtocol.java:89: error: @param name not found
[ERROR]      * @param perms
[ERROR]               ^
[ERROR] /Users/jonathan/Code/azure/projects/azure-javadocs/azure-sdk-for-java/azure-media/src/main/java/com/microsoft/windowsazure/services/media/models/AssetFile.java:174: error: exception not thrown: java.io.UnsupportedEncodingException
[ERROR]      * @throws UnsupportedEncodingException
[ERROR]                ^
[ERROR] /Users/jonathan/Code/azure/projects/azure-javadocs/azure-sdk-for-java/azure-media/src/main/java/com/microsoft/windowsazure/services/media/models/ContentKeyAuthorizationPolicy.java:154: error: @param name not found
[ERROR]      * @param assetId
[ERROR]               ^
[ERROR] /Users/jonathan/Code/azure/projects/azure-javadocs/azure-sdk-for-java/azure-media/src/main/java/com/microsoft/windowsazure/services/media/models/ContentKeyAuthorizationPolicy.java:156: error: @param name not found
[ERROR]      * @param adpId
[ERROR]               ^
[ERROR] /Users/jonathan/Code/azure/projects/azure-javadocs/azure-sdk-for-java/azure-media/src/main/java/com/microsoft/windowsazure/services/media/models/ContentKeyAuthorizationPolicyOption.java:191: error: @param name not found
[ERROR]          * @param assetDeliveryProtocol
[ERROR]                   ^
[ERROR] /Users/jonathan/Code/azure/projects/azure-javadocs/azure-sdk-for-java/azure-media/src/main/java/com/microsoft/windowsazure/services/media/models/ContentKeyAuthorizationPolicyOption.java:203: error: @param name not found
[ERROR]          * @param assetDeliveryPolicyType
[ERROR]                   ^
[ERROR] /Users/jonathan/Code/azure/projects/azure-javadocs/azure-sdk-for-java/azure-media/src/main/java/com/microsoft/windowsazure/services/media/models/ContentKeyAuthorizationPolicyOption.java:215: error: @param name not found
[ERROR]          * @param assetDeliveryPolicyConfiguration
[ERROR]                   ^
[ERROR] /Users/jonathan/Code/azure/projects/azure-javadocs/azure-sdk-for-java/azure-media/src/main/java/com/microsoft/windowsazure/services/media/models/EncodingReservedUnit.java:71: error: @param name not found
[ERROR]          * @param assetId
[ERROR]                   ^
[ERROR] /Users/jonathan/Code/azure/projects/azure-javadocs/azure-sdk-for-java/azure-media/src/main/java/com/microsoft/windowsazure/services/media/models/EncodingReservedUnitType.java:57: error: @param name not found
[ERROR]      * @param type
[ERROR]               ^
[ERROR] /Users/jonathan/Code/azure/projects/azure-javadocs/azure-sdk-for-java/azure-media/src/main/java/com/microsoft/windowsazure/services/media/models/JobNotificationSubscription.java:32: error: @param name not found
[ERROR]      * @param uuid
[ERROR]               ^
[ERROR] /Users/jonathan/Code/azure/projects/azure-javadocs/azure-sdk-for-java/azure-media/src/main/java/com/microsoft/windowsazure/services/media/models/Locator.java:284: error: bad HTML entity
[ERROR]          *            the date & time
[ERROR]                                ^
[ERROR] /Users/jonathan/Code/azure/projects/azure-javadocs/azure-sdk-for-java/azure-media/src/main/java/com/microsoft/windowsazure/services/media/models/Operation.java:40: error: @param name not found
[ERROR]      * @param assetId
[ERROR]               ^
[ERROR] /Users/jonathan/Code/azure/projects/azure-javadocs/azure-sdk-for-java/azure-media/src/main/java/com/microsoft/windowsazure/services/media/models/StreamingEndpoint.java:240: error: @param name not found
[ERROR]      * @param assetId
[ERROR]               ^
[ERROR] /Users/jonathan/Code/azure/projects/azure-javadocs/azure-sdk-for-java/azure-media/src/main/java/com/microsoft/windowsazure/services/media/models/StreamingEndpoint.java:263: error: @param name not found
[ERROR]      * @param assetId
[ERROR]               ^
[ERROR] /Users/jonathan/Code/azure/projects/azure-javadocs/azure-sdk-for-java/azure-media/src/main/java/com/microsoft/windowsazure/services/media/models/StreamingEndpoint.java:419: error: @param name not found
[ERROR]      * @param assetId
[ERROR]               ^
[ERROR] /Users/jonathan/Code/azure/projects/azure-javadocs/azure-sdk-for-java/azure-media/src/main/java/com/microsoft/windowsazure/services/media/models/StreamingEndpoint.java:290: error: @param name not found
[ERROR]          * @param assetId
[ERROR]                   ^
[ERROR] /Users/jonathan/Code/azure/projects/azure-javadocs/azure-sdk-for-java/azure-media/src/main/java/com/microsoft/windowsazure/services/media/entityoperations/EntityOperationBase.java:27: error: unknown tag: T
[ERROR]  * Default implementation of EntityOperation<T> to provide default values for
[ERROR]                                             ^
[ERROR] /Users/jonathan/Code/azure/projects/azure-javadocs/azure-sdk-for-java/azure-media/src/main/java/com/microsoft/windowsazure/services/media/entityoperations/EntityUnlinkOperation.java:48: error: @param name not found
[ERROR]      * @param secondaryEntityUri
[ERROR]               ^
[ERROR] /Users/jonathan/Code/azure/projects/azure-javadocs/azure-sdk-for-java/azure-media/src/main/java/com/microsoft/windowsazure/services/media/authentication/AzureAdClientSymmetricKey.java:4: error: bad HTML entity
[ERROR]  * Represents a symmetric key pair of ClientId & ClientKey
[ERROR]                                                ^
[ERROR] /Users/jonathan/Code/azure/projects/azure-javadocs/azure-sdk-for-java/azure-media/src/main/java/com/microsoft/windowsazure/services/media/authentication/AzureAdClientUsernamePassword.java:4: error: bad HTML entity
[ERROR]  * Represents a pair of username & password credentials
[ERROR]                                  ^
[ERROR] /Users/jonathan/Code/azure/projects/azure-javadocs/azure-sdk-for-java/azure-media/src/main/java/com/microsoft/windowsazure/services/media/authentication/AzureAdClientUsernamePassword.java:29: error: @param name not found
[ERROR]      * @param clientId The client ID.
[ERROR]               ^
[ERROR] /Users/jonathan/Code/azure/projects/azure-javadocs/azure-sdk-for-java/azure-media/src/main/java/com/microsoft/windowsazure/services/media/authentication/AzureAdClientUsernamePassword.java:30: error: @param name not found
[ERROR]      * @param clientKey The client key.
[ERROR]               ^
[ERROR]

**Comment by praries880** [comment]
@JonathanGiles Are you still experiencing the issue?

**Comment by yungezz** [comment]
we should make sure good javadoc in Track2.

**Comment by weidongxu-microsoft** [comment]
@yungezz  It is not mgmt.

**Comment by yungezz** [comment]
yes it's not mgmt. while in Track2 we have same goal. Let me create a new issue to track the track2 work.

**Comment by yungezz** [comment]
hi @joshfree the error snippet in issue description is not mgmt sdks. could you pls take a look? thanks.

**Comment by JonathanGiles** [comment]
At this stage these libraries are more or less deprecated, so I'm closing this as a won't fix.
