### ISSUE TITLE
We experienced  ~1 minute latency while sending messages to EventHub from the upstream application on 01.04.2021, and it happened for couple of times

### ISSUE THREAD

**Issue by koustavnaharoy-ayla** [Azure/azure-sdk-for-java#20434]
**Describe the bug**
We experienced  ~1 minute latency while sending messages to EventHub from the upstream application on 01.04.2021, and it happened for couple of times.

***Code Snippet***
Add the code snippet that causes the issue.
eventhubClient.sendSync()

**Expected behavior**
A clear explanation of why is this not a bug or a feature request?
As per the previous discussion with AZURE support colleague from Microsoft, there was a suggestion came to integrate with the newer azure sdk, azure-messaging-eventhubs 5.3.1 instead of using azure sdk 2.1.0. But that did not yield any visible results.

**Screenshots**

**Setup (please complete the following information):**
 - OS: Kubenetes
 - IDE : IntelliJ
 - Version of the Library used 5.3.1

**Information Checklist**
Kindly make sure that you have added all the following information above and checkoff the required fields otherwise we will treat the issuer as an incomplete report
- [x] Bug Description Added
- [x] Repro Steps Added
- [ ] Setup information Added

**Comment by joshfree** [comment]
@conniey PTAL

**Comment by conniey** [comment]
If you enable the environment variable, AZURE_LOG_LEVEL=2, and then configure a logger that supports slf4j, can you give me some logs for this issue? Do you have a repro?
https://github.com/Azure/azure-sdk-for-java/wiki/Logging-with-Azure-SDK#configuration-examples

**Comment by koustavnaharoy-ayla** [comment]
Ok sure, I try to repro that and get some log with this process

**Comment by conniey** [comment]
Can you reopen this when you have logs? We also fixed many reliability bugs in 5.10.0 which may have contributed to it.
