### ISSUE TITLE
ProvisioningState / PowerState - How to validate that a VM is ready for use after creating

### ISSUE THREAD

**Issue by zshlomyz** [Azure/azure-sdk-for-java#2044]
Hi,
I try to understand how to validate that a VM is ready for use after creating.
When the ProvisioningState value is Succeeded the VM is ready for use?  or when PowerState.running?
Thanks

**Comment by Drewm3** [comment]
Cleaning up old issues from 2016 - 2018. Please reopen this issue if it is still a concern.
