### ISSUE TITLE
[BUG] Event Hubs samples are not showing up in docs.microsoft.com/samples/browse

### ISSUE THREAD

**Issue by ramya-rao-a** [Azure/azure-sdk-for-java#20448]
We expect all the samples that live in this repo to show up in https://docs.microsoft.com/samples/browse
We do this by adding the right metadata in the readme file that lives in the folder that has the samples.

If you see this [search query for Event Hubs samples in Java](https://docs.microsoft.com/en-us/samples/browse/?filter-products=hubs&products=azure-event-hubs&languages=java), you see the one for checkpoint store that mirrors the samples in this repo, but you don't see one for Event Hubs SDK itself.

Compare this with the [search query for Event Hubs samples in JS](https://docs.microsoft.com/en-us/samples/browse/?filter-products=hubs&products=azure-event-hubs&languages=javascript) and you will see samples for both Event Hubs SDK and the checkpoint store

**Comment by ramya-rao-a** [comment]
The [search query for Service Bus samples in Java](https://docs.microsoft.com/en-us/samples/browse/?languages=java&filter-products=bus&products=azure-service-bus) does show the right results. So, perhaps we can use the metadata in the readme file for Service Bus samples as a reference

**Comment by YijunXieMS** [comment]
Fixed with PR #20474

**Comment by ramya-rao-a** [comment]
yay! Thanks!
