### ISSUE TITLE
[Service Bus] Sample needed for Dead Letter Queues 

### ISSUE THREAD

**Issue by ramya-rao-a** [Azure/azure-sdk-for-java#20452]
The doc [Overview of dead letter queues](https://docs.microsoft.com/en-us/azure/service-bus-messaging/service-bus-dead-letter-queues) links to a sample that uses the older .NET package WindowsAzure.ServiceBus

Ideally, there should be links to samples that use packages from all languages. This issue is to add a corresponding sample that uses the `azure-messaging-servicebus` package so that it can be linked appropriately.

Reference: [DeadletterQueue](https://github.com/Azure/azure-service-bus/tree/master/samples/DotNet/Microsoft.ServiceBus.Messaging/DeadletterQueue)

Adding this sample will also be useful for us to re-direct readers who land at the above sample.

cc @spelluru

**Comment by hongli750210** [comment]
@ramya-rao-a - After investigation, I found that the [DeadletterQueue](https://github.com/Azure/azure-service-bus/tree/master/samples/Java/azure-servicebus/DeadletterQueue) sample about java already exists, but the package it uses is `com-microsoft-azure-servicebus`. 
So I think there are two ways to change:
1. Based on the original sample, update `com-microsoft-azure-servicebus` package to `azure-messaging-servicebus` package.
2. Add a new `DeadletterQueue` sample using the `azure-messaging-servicebus` package, whose package directory is `com.azure.servicebus.samples.deadletterqueue`

Which one do you think is more appropriate? If you have better suggestions, please tell me, thanks!

**Comment by ramya-rao-a** [comment]
We need a copy of the Java DeadletterQueue sample you found that uses the newer package `azure-messaging-servicebus`. This should live in https://github.com/Azure/azure-sdk-for-java/tree/master/sdk/servicebus/azure-messaging-servicebus/src/samples
