### ISSUE TITLE
[BUG] AzureServiceBusTopicAutoConfiguration should import AzureServiceBusAutoConfiguration

### ISSUE THREAD

**Issue by GitHanter** [Azure/azure-sdk-for-java#20454]
`ServiceBusTopicBinderConfiguration` should import `AzureServiceBusAutoConfiguration`, same as `ServiceBusQueueBinderConfiguration`, otherwise we'll get following exception when we have multiple binders (Queue and Topics)

```java
Parameter 3 of method topicClientFactory in com.azure.spring.cloud.autoconfigure.servicebus.AzureServiceBusTopicAutoConfiguration required a bean of type 'com.azure.spring.integration.servicebus.factory.ServiceBusConnectionStringProvider' that could not be found.
```
The `ServiceBusQueueBinderConfiguration` is 
```java
@Configuration
@ConditionalOnMissingBean(Binder.class)
@Import({
    AzureEnvironmentAutoConfiguration.class,
    AzureContextAutoConfiguration.class,
    AzureServiceBusAutoConfiguration.class,
    AzureServiceBusQueueAutoConfiguration.class })
@EnableConfigurationProperties({ AzureServiceBusProperties.class, ServiceBusQueueExtendedBindingProperties.class })
public class ServiceBusQueueBinderConfiguration {
...
}
```
The `ServiceBusTopicBinderConfiguration` should import `AzureServiceBusAutoConfiguration` too
```java
@Configuration
@ConditionalOnMissingBean(Binder.class)
@Import({ AzureServiceBusAutoConfiguration.class, AzureServiceBusTopicAutoConfiguration.class, AzureEnvironmentAutoConfiguration.class })
@EnableConfigurationProperties({ AzureServiceBusProperties.class, ServiceBusTopicExtendedBindingProperties.class })
public class ServiceBusTopicBinderConfiguration {
...
}
```

Sample Configuration
```java
spring:
  cloud:
    stream:
      function:
        definition: queueConsumer; topicConsumer;
      bindings:
        #use StreamBridge in code to send to this channel
        queue-out-0:
          destination: <servicebus-queue-name1>
          binder: queue-output
        queueConsumer-in-0:
          destination: <servicebus-queue-name2>
          binder: queue-input
        topicConsumer-in-0:
          destination: <servicebus-topic-name>
          group: <consumerGroup>
          binder: topic-input
      binders:
        topic-input:
            type: servicebus-topic
            default-candidate: false
            environment:
              spring.cloud.azure.servicebus.connection-string: <TopicConnectionString>
          queue-output:
            type: servicebus-queue
            default-candidate: false
            environment:
              spring.cloud.azure.servicebus.connection-string: <QueueConnectionString>
         queue-input:
            type: servicebus-queue
            default-candidate: false
            environment:
              spring.cloud.azure.servicebus.connection-string: <QueueConnectionString2>
```

**Comment by joshfree** [comment]
@YijunXieMS PTAL

/cc @hemanttanwar

**Comment by YijunXieMS** [comment]
@saragluna it's about ServiceBus Spring binder.

**Comment by saragluna** [comment]
@GitHanter which version of the binder are you using?

**Comment by GitHanter** [comment]
> @GitHanter which version of the binder are you using?

The latest version, v2.3.0. This issue only happen when we use Topic and Queue simultaneously, and configure different connection string for each channel (Property `spring.cloud.azure.servicebus.connection-string`), I traced the source code in `DefaultBinderFactory` `getBinderInstance` method 

```java
SpringApplicationBuilder springApplicationBuilder = new SpringApplicationBuilder(
					binderType.getConfigurationClasses())
							.bannerMode(Mode.OFF).logStartupInfo(false)
							.web(WebApplicationType.NONE);
			...

			ConfigurableApplicationContext binderProducingContext = springApplicationBuilder
					.run(args.toArray(new String[0]));
```
and find that `SpringApplicationBuilder.run` is different from SpringBoot boostrap `SpringApplication.run`, because `SpringApplicationBuilder.run` doesn't leverage `SpringFactoriesLoader` to load `AutoConfigure` configurations, so only imported configuration will take effect, so we need import `AzureServiceBusAutoConfiguration.class`.

**Comment by saragluna** [comment]
Thanks @GitHanter for your detailed description and analysis, I'm going to create a PR to fix this.

**Comment by saragluna** [comment]
The latest version has been released https://github.com/Azure/azure-sdk-for-java/blob/master/sdk/spring/azure-spring-cloud-stream-binder-servicebus-topic/CHANGELOG.md#240-2021-04-19.

**Comment by stliu** [comment]
@saragluna maybe we should include this scenario into our integration test?

**Comment by saragluna** [comment]
@stliu yes, will create another issue to track the integration test.

**Comment by saragluna** [comment]
Closing this issue now for the fix has been released.
