### ISSUE TITLE
Add support for 401 and 404 error code mappings in rest proxy

### ISSUE THREAD

**Issue by pallavit** [Azure/azure-sdk-for-java#20468]
Currently all the services handle 401 and 404 error code mapping to ClientAuthenticationException and ResourceNotFoundException which can be moved to rest proxy directly.

**Comment by alzimmermsft** [comment]
Closing as this feature added to AutoRest (https://github.com/Azure/autorest.java/pull/1268) and making this change within Core may break APIs if they were previously expecting different HttpResponseException errors to be thrown.
