### ISSUE TITLE
Consider using another host for publishing to sonatype

### ISSUE THREAD

**Issue by weshaggard** [Azure/azure-sdk-for-java#20470]
We sometimes hit publishing failures when going publishing to sonatype an error that looks similar to:
```
SEVERE: A message body reader for Java class com.sonatype.nexus.staging.api.dto.StagingProfileRepositoryDTO, and Java type class com.sonatype.nexus.staging.api.dto.StagingProfileRepositoryDTO, and MIME media type text/html was not found
```
Example [build]
(https://dev.azure.com/azure-sdk/internal/_build/results?buildId=828114&view=logs&j=e5cb9759-2e53-5944-91c4-f19670565217&t=1a634068-4631-57c0-56bc-f96f469b8a15)

This appears to happen when the load on oss.sonatype.org is very high. One suggestion recommended by sonatype in https://issues.sonatype.org/browse/OSSRH-51097 is to request to use another host for uploading. We should consider switching over to another host to help avoid these publishing timeout errors.

**Comment by hallipr** [comment]
I can't tell from the provided OSSRH if we'll be able to continue publishing on the old hostname once we've request provisioning on the new one. 

> I'm not sure how complex your build setup is, but, in theory all it might take is replacing the hostname oss.sonatype.org in your builds with the new hostname.

If it's where we're assigned to a specific hostname and if we want to have no downtime for any release, we'll need to change our powershell to support multiple possible hostnames and use a fallback if we're rejected on the new hostname.

**Comment by weshaggard** [comment]
I don't know either we can probably ask those questions in the issue when we request the new host name.
