### ISSUE TITLE
[AppConfig][ServiceBus] Add detail explained JavaDoc or Deprecate retryPolicy(HttpPipeline)

### ISSUE THREAD

**Issue by mssfang** [Azure/azure-sdk-for-java#20478]
Currently, only AppConfig SDK and ServiceBus are having retryPolicy(HttpPipeline) method in the builder.

We should either 
(1) deprecate the API for both client SDKs at some propriate time in the future.

or 
(2)
Keep both APIs but make sure have well-documented that explain the retryPolicy should take RetryPolicy instead of HttpPipeline.
(currently, AppConfig takes this approach)

**Comment by anuchandy** [comment]
The SB ClientBuilder takes retry settings via [retryOptions](https://github.com/Azure/azure-sdk-for-java/blob/cd6c2a765da667dc238e889faf8fd0dbcac1da31/sdk/servicebus/azure-messaging-servicebus/src/main/java/com/azure/messaging/servicebus/ServiceBusClientBuilder.java#L534) and I don't see it taking a policy. Hence removing the `Service Bus`, please add it back if I over looked.
