### ISSUE TITLE
Weekly Multi-Version Dependency Test Runs

### ISSUE THREAD

**Issue by alzimmermsft** [Azure/azure-sdk-for-java#20514]
Create a weekly test run that validates running our libraries against a specified dependency matrix. This testing should include the following:

- [ ] Test against checked in dependency versions.
- [ ] Test against the minimum supported dependency versions.
- [ ] Potentially test against other supported dependency versions.

For example, if the SDKs state to support Jackson 2.11 and 2.12 and the checked in dependency version is 2.12.2, the weekly run could be configured to test the following:

- Jackson 2.11.0
- Jackson 2.12.0
- Jackson 2.12.2

What needs to be determine is whether the matrix is sparse if multiple dependencies are used. So, if Jackson has 2.11 and 2.12 supported and Reactor Core has 3.3 and 3.4 supported (this is not true at the time this issue is being written), which of the following would be used in the weekly run?

| Jackson Version | Reactor Core Version |
| ----------------- | ----------------------- |
| 2.11                   | 3.3                              |
| 2.11                   | 3.4                              |
| 2.12                   | 3.3                              |
| 2.12                   | 3.4                              |

OR

| Jackson Version | Reactor Core Version |
| ----------------- | ----------------------- |
| 2.11                   | 3.3                              |
| 2.12                   | 3.4                              |

Or, another option would be that dependencies which have correlation to each other, such as Reactor Core and Reactor Netty, must use sparse matrix so that the dependencies align.

**Comment by conniey** [comment]
Related #21305

**Comment by alzimmermsft** [comment]
Closing this as it has been completed in #23283 which added supported for multiple versions of Jackson to be tested. This same pattern will be used once support for multiple versions of Reactor are added (if they are added).
