### ISSUE TITLE
Add index utilization details to query metrics

### ISSUE THREAD

**Issue by mbhaskar** [Azure/azure-sdk-for-java#20576]
Add option to enable index utilization metrics to CosmosQueryRequestOptions

QueryMetrics textwriter format

Index Utilization Information
      Utilized Single Indexes
        Filter Expression: (ROOT.name = "Julien")
        Index Spec: /name/?
        Index Impact Score: High
        ---
        Filter Expression: (ROOT.age > 12)
        Index Spec: /age/?
        Index Impact Score: High
        ---
      Potential Single Indexes
      Utilized Composite Indexes
      Potential Composite Indexes
        Index Spec: /name ASC, /age ASC
        Index Impact Score: High
        ---

Corresponding .NET PR: https://github.com/Azure/azure-cosmos-dotnet-v3/pull/2006/

**Comment by xinlian12** [comment]
It has been added since 4.19.0: https://github.com/Azure/azure-sdk-for-java/blob/main/sdk/cosmos/azure-cosmos/CHANGELOG.md#4190-2021-09-09
