### ISSUE TITLE
[FEATURE REQ] Support whole cert chain in azure-security-keyvault-jca

### ISSUE THREAD

**Issue by chenrujun** [Azure/azure-sdk-for-java#20591]
### Context

https://github.com/Azure/azure-sdk-for-java/blob/master/sdk/keyvault/azure-security-keyvault-jca/src/main/java/com/azure/security/keyvault/jca/KeyVaultKeyStore.java#L161

The cert chain always has one item, it's not right.

### Problem

For example: When customer uploaded the full certificate chains (rootCA, intermediateCA, serverCertificate) into Azure Key Vault, KeyVaultKeyStore will only have serverCertificate, this will cause the browser (for example Edge) not trust the serverCertificate. 

### Goal
Include all certs in cert chain.

**Comment by chenrujun** [comment]
Closing this issue.

Conclusion:
1. self-signed: already supported.
2. CA signed: We can not create this usage case, so ignore this case.
3. Other certificate signed: If the `Other certificate` was in the KeyvaultKeyStore, it can work well.

@michaelqi793 FYI.

**Comment by RAP2022** [comment]
Hi Chenrujun,
I am currently using Azure key-vault-jca library integrated with a tomcat server to provide HTTPS service.
The certificate is generated by Azure key-vault and signed by a3rd party intermediate CA.

With this issue, the web server cannot present the full chain certificate, but only the server certificate which prevents the integration of this web server as a backend pool server for the Azure Application Gateway (v2).

I uploaded the full certificate chains (rootCA, intermediateCA, server Certificate) into Azure Key Vault, and confirmed the full chain is available if I download the certificate in pfx/pem format.

Can you confirm if  certificate chain can be supported for key-vault-jca?

Many thanks,

**Comment by chenrujun** [comment]
Hi, @RAP2022 .
Thanks for reaching out.

It's not supported now, we plan to support it. ETA: 2022-04.

**Comment by RAP2022** [comment]
Thanks Rujun for your update.

**Comment by chenrujun** [comment]
Share some information:

1. About import certificate:

There are some requirements when upload certificate to Azure Key Vault.

a. The PEM file must contain the key as well as x509 certificates.
b. PEM file format contains one or more X509 certificate files.
c. BEGIN RSA PRIVATE KEY (PKCS#1) is not right, it should be "BEGIN PRIVATE KEY" (PKCS#8)

Refs: https://learn.microsoft.com/en-us/azure/key-vault/certificates/tutorial-import-certificate?tabs=azure-portal#import-a-certificate-to-your-key-vault

2. In the following picture, in http request 4 and 5, [KeyVaultKeyStore.java#L161](https://github.com/Azure/azure-sdk-for-java/blob/master/sdk/keyvault/azure-security-keyvault-jca/src/main/java/com/azure/security/keyvault/jca/KeyVaultKeyStore.java#L161) returns one cert will not have problem because trust-store in client-side also use KeyVaultKeyStore, the leaf cert is trusted.
![image](https://user-images.githubusercontent.com/13167207/199641068-82fbeaac-9b26-4bc9-808b-d200e063e986.png)

Refs: 
https://learn.microsoft.com/en-us/azure/spring-apps/how-to-enable-ingress-to-app-tls
https://github.com/Azure-Samples/azure-spring-boot-samples/tree/spring-cloud-azure_4.4.1/keyvault/azure-securtiy-keyvault-jca
https://github.com/Azure-Samples/azure-spring-boot-samples/tree/spring-cloud-azure_4.4.1/keyvault/azure-spring-boot-starter-keyvault-certificates

**Comment by Trailbear** [comment]
JCA Client is entirely pointless unless it serves up the whole certficate chain.  The fact that it doesn't causes a lot of extra confusion for adopters, who in the end have wasted their time with the code's empty promises.

**Comment by saragluna** [comment]
@Trailbear sorry but I agree with you on that, we will prioritize this feature or fix, but do understand that we are short of resources right now. In the meantime, PRs are welcome.
