### ISSUE TITLE
For key-vault-jca, investigate what is KeyVaultTrustManager used for.

### ISSUE THREAD

**Issue by chenrujun** [Azure/azure-sdk-for-java#20593]
If `azure.keyvault.jca.overrideTrustManagerFactory=true`, then KeyVaultTrustManager will take effect.

Investigate why it's related to `Spring Cloud Gateway`.

Refs: https://github.com/Azure/azure-sdk-for-java/tree/azure-security-keyvault-jca_1.0.0-beta.1/sdk/spring/azure-spring-boot-starter-keyvault-certificates#configuring-spring-cloud-gateway

**Comment by yiliuTo** [comment]
It configures the trust store used for outbound connections initiated by the Spring Cloud Gateway.
