### ISSUE TITLE
[BUG] ServiceBusReceiverClientBuilder allows to specify maxAutoLockRenewDuration, ServiceBusProcessorClientBuilder does not

### ISSUE THREAD

**Issue by jfurmankiewiczpros** [Azure/azure-sdk-for-java#20603]
**Describe the bug**
 
If creating a receiver we can specify an explicit "maxAutoLockRenewDuration"

    public final class ServiceBusReceiverClientBuilder {
        ....
        private Duration maxAutoLockRenewDuration = MAX_LOCK_RENEW_DEFAULT_DURATION;

When crearing processor, we cannot, see

    public final class ServiceBusProcessorClientBuilder {
        private final ServiceBusReceiverClientBuilder serviceBusReceiverClientBuilder;
        private final ServiceBusProcessorClientOptions processorClientOptions;
        private Consumer<ServiceBusReceivedMessageContext> processMessage;
        private Consumer<ServiceBusErrorContext> processError;

When using processor, I am getting a lot of exceptions like this during long running performance tests

    com.azure.messaging.servicebus.ServiceBusException: The lock supplied is invalid. Either the lock expired, or the message has already been removed from the queue. Reference:d82ff8e5-b017-4714-8973-4c2f34757e4b, 

which I did not have in previous SDK. So wanted to look at the lock duration, since the processor in the tests is just a no-op that logs a counter and does a message context complete()...but often gets this error when calling complete().

So assumed it's something wrong with the lock duration and then realized you cannot specify one on a Processor, only on a Receiver.

**Comment by joshfree** [comment]
@hemanttanwar could you please take a look?

**Comment by jfurmankiewiczpros** [comment]
I believe this has been fixed in 7.3.0-beta.1, I just saw that added in the release notes for that one, tested with it yesterday.

So unless I am missing something, we can probably close this one

**Comment by jfurmankiewiczpros** [comment]
by close I mean the missing API. I am still having issues with lock invalid messages, even after I set it, but I opened a separate ticket for that one.

**Comment by hemanttanwar** [comment]
@jfurmankiewiczpros Thank you for using this library. Yes this API was added in '7.3.0-beta.1'.  Since you have separate issue for 'lock invalid messages', I will close this issue.
