### ISSUE TITLE
[QUERY] How to Set a Custom Property on a Service Bus Message

### ISSUE THREAD

**Issue by hammocktester** [Azure/azure-sdk-for-java#20632]
**Query/Question**
I need to set a custom property on a service bus message with the new com.azure.messaging.servicebus.ServiceBusMessage. What happened to the setLabel method from com.microsoft.servicebus.Message.setLabel?

https://docs.microsoft.com/en-us/java/api/com.microsoft.azure.servicebus.message.setlabel?view=azure-java-stable

***Why is this not a Bug or a feature Request?***
I just need to know what happened to this method or what method(s) replaced it assuming the newer libraries arent removing features

**Setup (please complete the following information if applicable):**
 - OS: Windows
 - Eclipse
 - 7.1

**Comment by alzimmermsft** [comment]
@hemanttanwar could you take a look at this?

**Comment by hemanttanwar** [comment]
@hammocktester  I will close this issue. If your questions is not answered, please feel free to reopen this issue.
