### ISSUE TITLE
[BUG] Illegal connection string parameter name: SharedAccessSignatureToken 

### ISSUE THREAD

**Issue by lordarcy** [Azure/azure-sdk-for-java#20643]
**Describe the bug**
When creating a ServiceBusReceiverClient using a connection string that worked with the older (azure-service-bus-java/releases/tag/1.0.0) library I get a java.lang.IllegalArgumentException stating that the SharedAccessSignatureToken is an illegal parameter name.

***Exception or Stack Trace***
java.lang.IllegalArgumentException: Illegal connection string parameter name: SharedAccessSignatureToken

**To Reproduce**
Create a ServiceBusClientBuilder or ServiceBusReceiverClient and pass in a connection string that contains the SharedAccessSignatureToken parameter.

***Code Snippet***
`
ServiceBusClientBuilder builder = new ServiceBusClientBuilder().connectionString(connectionString);
`

This corresponds (roughly) to the code from the older library:

`
ConnectionStringBuilder builder = new ConnectionStringBuilder(connectionString, topicName + "/subscriptions/" + subscriptionName);
`

In the new library the full code that includes the topic and subscription also throws the same exception. However the shorter example above displays the same behavior:

`
ServiceBusReceiverClient receiver = new ServiceBusClientBuilder()
	.connectionString(connectionString)
	.receiver()
	.topicName(topicName)
	.subscriptionName(subscriptionName)
	.buildClient();
`

**Expected behavior**
The client builder should work with the same connection string that worked in the older Java Client for Azure Service bus library.

**Setup (please complete the following information):**
MacOS Mojave 10.14.6
OpenJDK 64-Bit Server VM (Zulu 8.38.0.13-CA-macosx
Using azure-messaging-servicebus_7.0.1

**Information Checklist**
Kindly make sure that you have added all the following information above and checkoff the required fields otherwise we will treat the issuer as an incomplete report
- [X] Bug Description Added
- [X] Repro Steps Added
- [X] Setup information Added

**Comment by joshfree** [comment]
@hemanttanwar could you please take a look?

/cc @YijunXieMS

**Comment by hemanttanwar** [comment]
@lordarcy Can you provide us code which you use using V3.x library to create client ? You did mentioned about `ConnectionStringBuilder` but I am looking at complete code to create client. My goal is to reproduce this first in V3.x first.

**Comment by hemanttanwar** [comment]
I appreciate you using our library.
Please change 'SharedAccessSignatureToken' to 'SharedAccessSignature, this should resolve the issue'. 
I am closing this issue, but if you still have same issue, please reopen this issue.
