### ISSUE TITLE
[QUERY]: how to check client has been authenticated. 

### ISSUE THREAD

**Issue by irfanjs** [Azure/azure-sdk-for-java#20655]
**Query/Question**
Using azure identity library for java , have following code to authenticate the client. 

```
	ClientSecretCredential clientSecretCredential = new ClientSecretCredentialBuilder()
				  .clientId("<client id>")
				  .clientSecret("<clientsecret>")
				  .tenantId("<tenant id>")
				  .build();
```
		
my question is , how to check the client has been authenticated using above credentials passed as parameters . ?
haven't found any method . please suggest how to check 

**Setup (please complete the following information if applicable):**
 - OS: windows 10 
 - IDE : eclipse
 - Version of the Library used

```
<dependency>
    <groupId>com.azure</groupId>
    <artifactId>azure-identity</artifactId>
    <version>1.2.4</version>
    
</dependency> 
```
 **Information Checklist**
 Kindly make sure that you have added all the following information above and checkoff the required fields otherwise we will treat the issuer as an incomplete report
- [ ] Query Added : yes 
- [ ] Setup information Added : yes

**Comment by joshfree** [comment]
@g2vinay PTAL

**Comment by g2vinay** [comment]
@irfanjs 
Thank you for your query.

The code which you posted only sets up the credential and doesn't initiate authentication.
```java
        ClientSecretCredential clientSecretCredential = new ClientSecretCredentialBuilder()
                .clientId("<client id>")
                .clientSecret("<clientsecret>")
                .tenantId("<tenant id>")
                .build();
```

To initiate authentication the getToken method needs to be called as follows:

```java
        AccessToken accessToken = clientSecretCredential.getToken(new TokenRequestContext().addScopes("<scopes>")).block();

```

An access token response will indicate successful authentication.

**Comment by irfanjs** [comment]
Thanks @g2vinay .
Can you please give me some example for access token ? and what all different scopes are supported ? 
Thanks

**Comment by g2vinay** [comment]
@irfanjs 
The Access Token contains a string value of the following format: eyJ0eXAiO...........GIYEEuVC36vFRW1fA
For scopes, all the Azure Services which support AAD authentication, their scopes are supported.
e.g. Keyvault's scope is "https://vault.azure.net/.default"
But you don't have to worry about passing in the scopes, if you're using our Azure Service SDKs such as Azure Storage SDK, Keyvault SDK etc, they pass in the scope themselves.

**Comment by g2vinay** [comment]
@irfanjs 
Let us know if you still need any further assistance here.
Closing this for now.
