### ISSUE TITLE
[QUERY] : How to get started with this consumption library 

### ISSUE THREAD

**Issue by irfanjs** [Azure/azure-sdk-for-java#20652]
**Query/Question**
I am trying to get the cost of Azure resources (including subscription) programmatically using Java .  My query is how to get started with this library . ? What are the packages/classes/methods I can use from this library. ? Can I get the Javadoc for this library ? 
Currently , my simple use case is , to get the aggregated cost of the subscription (Billing Period is : TheLastMonth) , is this possible using this SDK ? Please suggest 

For identity management , Im using following : 

```
<dependency>
    <groupId>com.azure</groupId>
    <artifactId>azure-identity</artifactId>
    <version>1.2.4</version>
    
</dependency>
```

Below is the code for authentication using service principal. 

```
	ClientSecretCredential clientSecretCredential = new ClientSecretCredentialBuilder()
				  .clientId("<client id>")
				  .clientSecret("<clientsecret>")
				  .tenantId("<tenant id>")
				  .build();

```

**Setup (please complete the following information if applicable):**
 - OS: 
 windows 10
 - IDE:
 Eclispe 
 - Version of the Library used. below entries are in pom.
 ```
<dependency>
    <groupId>com.azure</groupId>
    <artifactId>azure-core</artifactId>
    <version>1.14.1</version>
</dependency>
```

 
 **Information Checklist**
 Kindly make sure that you have added all the following information above and checkoff the required fields otherwise we will treat the issuer as an incomplete report
- [ ] Query Added: yes
- [ ] Setup information Added : yes 

please suggest . Thanks . This is critical.

**Comment by joshfree** [comment]
@g2vinay PTAL

**Comment by g2vinay** [comment]
@irfanjs 
Thank you for this query.
You can find Javadocs of latest identity release here: 
https://azuresdkdocs.blob.core.windows.net/$web/java/azure-identity/1.2.5/index.html

This library is mainly for Azure Active Directory authentication and doesn't offer any APIs which Azure Subscription cost directly.

Possibly Azure Consumption API here can help you out too for your task:
https://docs.microsoft.com/en-us/azure/cost-management-billing/manage/consumption-api-overview

**Comment by irfanjs** [comment]
ok. thanks
