### ISSUE TITLE
[Storage] Does BlobClient.Exists() function correctly for blobs encrypted with CPK?

### ISSUE THREAD

**Issue by seanmcc-msft** [Azure/azure-sdk-for-java#20663]
https://github.com/Azure/azure-sdk-for-net/issues/20361

**Comment by gapra-msft** [comment]
ack

**Comment by ibrahimrabab** [comment]
Does not reproduce, since CPK gets set on the client builder, which propagates over to the BlobClient and all other clients. Exists behaves as expected when calling it on a client without a CPK set.
