### ISSUE TITLE
Managed Identity Authentication

### ISSUE THREAD

**Issue by alisharifi01** [Azure/azure-sdk-for-java#20661]
Hello,
I wonder to know if the azure-spring-boot-starter-servicebus-jms library supports Managed Identity Authentication?
I have tried the suggested connection string to enable Microsoft Documentation (Endpoint=sb://{{Fully qualified namespace name}}/;Authentication=Managed Identity), then the connection string has not been resolved.
Thank you in advance

**Comment by joshfree** [comment]
@stliu could you please follow upw ith @alisharifi01 on the question

**Comment by backwind1233** [comment]
Hi @alisharifi01,
sorry, the azure-spring-boot-starter-servicebus-jms library doesn't supports Managed Identity Authentication.

**Comment by backwind1233** [comment]
Close the issue for there is no reply for 7 days.
