### ISSUE TITLE
Migrate start.spring.io to use Track 2 libraries

### ISSUE THREAD

**Issue by conniey** [Azure/azure-sdk-for-java#20682]
Update "Getting Started" section in Spring Cloud Azure (https://spring.io/projects/spring-cloud-azure) section to use Track 2 libraries.
At the moment, they point to track 1 libraries.
<img width="452" alt="image" src="https://user-images.githubusercontent.com/10136526/114793406-2984c680-9d3f-11eb-859e-c90516b68496.png">

Related to: #20681

**Comment by stliu** [comment]
@chenrujun  I think this one is duplicated by one of issue you created?

**Comment by chenrujun** [comment]
@stliu yes.

Closing this issue, because it's duplicated with #21295
