### ISSUE TITLE
Cache search answers if the first paged is already retrieved 

### ISSUE THREAD

**Issue by srnagar** [Azure/azure-sdk-for-java#20709]
In SearchPagedFlux, the `getAnswers()` method makes a service call to get the first page and then access the answers list, from the first-page response. 

Will all the results of `getAnswers()` always be on the first page? Also, if the user has used `byPage()` or simply subscribed to the paged flux, is it necessary to make another call to the service? Can we cache the answers from the first call that happened through other APIs?

_Originally posted by @srnagar in https://github.com/Azure/azure-sdk-for-java/pull/20586#discussion_r613576823_

**Comment by alzimmermsft** [comment]
Closing this issue as the values are available on the response pages and this is a convenience offered. Additionally, the value may change over time.
