### ISSUE TITLE
[FEATURE REQ] Add AzureCliCredential to possible Key Vault authentication methods

### ISSUE THREAD

**Issue by anderius** [Azure/azure-sdk-for-java#20710]
**Is your feature request related to a problem? Please describe.**

When developing locally, I would like to re-use my `az login` when running my Spring Boot application. This way my application can access secrets without including any secrets in the configuration (requiring jasypt or similar).

I would also imagine this to be useful for console applications.

**Describe the solution you'd like**
I would like `com.azure.spring.keyvault.KeyVaultEnvironmentPostProcessorHelper#getCredentials(java.lang.String)` to include `com.azure.identity.AzureCliCredential` as an option. Probably enabled by something like `azure.keyvault.enable-cli-auth`.

**Describe alternatives you've considered**
An alternativ would be to override beans, but it seems the Azure Key Vault integration is not using things like `@ConditionalOnMissingBean`. I guess that is because it is too early in the spring boot startup process?

Another option would be to require the developer to create a service principal and add it as environment variables, but that is not as elegant as `az login`.

**Information Checklist**
Kindly make sure that you have added all the following information above and checkoff the required fields otherwise we will treat the issuer as an incomplete report
- [X] Description Added
- [X] Expected solution specified

**Comment by anderius** [comment]
(I am happy to attempt a pull request, if the feature sounds good)

**Comment by joshfree** [comment]
Thanks @anderius for filing this.  @stliu from the `azure-spring` team will follow up with you shortly

**Comment by backwind1233** [comment]
@anderius PR is welcome, we appreciate your contribution very much.

**Comment by anderius** [comment]
@backwind1233 I have made an attempt in the linked Pull requests, and it works when I tested the code in my project.

**Comment by chenrujun** [comment]
This issue will be addressed in this PR #22472.

**Comment by chenrujun** [comment]
@anderius .
Thank you for your check.
And I'll keep this issue closed, only use one issue/PR to track similar problems.

**Comment by anderius** [comment]
I am keeping track, as I think this is a really useful feature!

As far as I can tell, the current PR fixing this is https://github.com/Azure/azure-sdk-for-java/pull/23849.

**Comment by saragluna** [comment]
Closing this issue now, please check #24260 for the release of our next major version.
