### ISSUE TITLE
[FEATURE REQ] Need a way to test scenarios that run with restricted resource settings

### ISSUE THREAD

**Issue by gapra-msft** [Azure/azure-sdk-for-java#20712]
Recently we have been getting a few issues around upload APIs consuming too much memory 
https://github.com/Azure/azure-sdk-for-java/pull/20480
https://github.com/Azure/azure-sdk-for-java/pull/19600
https://github.com/Azure/azure-sdk-for-java/issues/19577

It would be nice to have some sort of framework (either an extension of unit testing or as part of regular perf runs) that would allow us to define scenarios with restricted resource settings (ex: setting -Xmx flag to a tight bound) and run tests for upload/download/listing APIs that are likely to hit resource limit issues.

It would also be nice to monitor often if there is some regression in memory behavior (through profiler tools and such).  

This is likely something we would want to extend to other languages as well.

**Comment by alzimmermsft** [comment]
@kasobol-msft, this has been completed with the changes made to the Storage `test.yml`, correct?

**Comment by kasobol-msft** [comment]
yes, more might be coming from the "stress" workstream but we're good for now.
