### ISSUE TITLE
List Spring sample README to the doc site

### ISSUE THREAD

**Issue by YijunXieMS** [Azure/azure-sdk-for-java#20718]
The sample doc site (https://docs.microsoft.com/en-us/samples/browse/?expanded=azure) doesn't list the Spring related samples because the spring boot sample README files under https://github.com/Azure/azure-sdk-for-java/tree/master/sdk/spring/azure-spring-boot-samples don't have a header like other samples.

**Comment by wujack778** [comment]
![image](https://user-images.githubusercontent.com/69495791/121282286-d0cf4580-c90b-11eb-956b-4c31e176a7c2.png)
---
page_type: sample
languages:
- java
products:
- azure-spring-cloud-servicebus-queue-multi-binders
description: "Azure Spring Cloud Stream Binder Sample project for Multiple Service Bus Namespaces client library"
urlFragment: "azure-spring-cloud-servicebus-queue-multibinders-sample"
---

When i add this header, i don't know the composition standard of products and urlFragment. Do you have relevant information?
@YijunXieMS

**Comment by YijunXieMS** [comment]
See [product slugs](https://taxonomyservice.azurefd.net/TaxonomyServiceAdminPage/#/taxonomy/detail/2021-03-22T22:56:03.3422325Z!a8da30dc-3999-4cd9-9778-8380e203014c/product)

**Comment by backwind1233** [comment]
Hi, @YijunXieMS  we have added headers in our samples and merged the [PR](https://github.com/Azure/azure-sdk-for-java/pull/22107), but the [code samples](https://docs.microsoft.com/en-us/samples/browse/?expanded=azure) page doesn't show our samples now, is there any delay to show this? Do you know any rules about this, how the [code samples](https://docs.microsoft.com/en-us/samples/browse/?expanded=azure) scan github repos ?

**Comment by YijunXieMS** [comment]
I don't see the spring related samples generated here https://github.com/MicrosoftDocs/samples/tree/master/Azure/azure-sdk-for-java
If it's not there tmr, we may need to check why.

**Comment by backwind1233** [comment]
@YijunXieMS  
I think I know how to do it. Thank you.
