### ISSUE TITLE
[BUG] NullPointerException when using CosmosAsyncContainer.readAllItems(partitionKey,options,classType) when CosmosQueryRequestOptions is null

### ISSUE THREAD

**Issue by omarsmak** [Azure/azure-sdk-for-java#20743]
**Describe the bug**
When supplying a `null` as `CosmosQueryRequestOptions` parameter in here https://github.com/Azure/azure-sdk-for-java/blob/master/sdk/cosmos/azure-cosmos/src/main/java/com/azure/cosmos/CosmosAsyncContainer.java#L978 this will trigger a NPE since there is no check if `CosmosQueryRequestOptions` is `null` otherwise creates a new `CosmosQueryRequestOptions` similar to other operations

**Expected behavior**
A null check that checks for `CosmosQueryRequestOptions` nullability, otherwise creates a new instance of `CosmosQueryRequestOptions`.

**Comment by omarsmak** [comment]
Since it is a simple fix, created a PR here: https://github.com/Azure/azure-sdk-for-java/pull/20744

**Comment by joshfree** [comment]
Thanks for reporting this issue @omarsmak.  @kushagraThapar from the `Cosmos` team will follow up with you shortly

**Comment by omarsmak** [comment]
PR is merged and thus the issue has been resolved
