### ISSUE TITLE
[BUG] CosmosAsyncClient does not recognize built-in roles

### ISSUE THREAD

**Issue by ircey** [Azure/azure-sdk-for-java#20781]
**Describe the bug**
CosmosAsyncClient created with service principal with aggigned: "Cosmos DB Operator" or "DocumentDB Account Contributor" role definition is not able to create database or container.
What is more I was not able to create CosmosAsyncClient, until I added new custom role, which just contains reading metadata. Above mentioned built-in-role definitions do not contain it, but from what I read sdk itself should manage it.

***Exception or Stack Trace***
{...,"userAgent":"azsdk-java-cosmos/4.13.1 Windows10/10.0 JRE/11.0.10","statusCode":403,"resourceAddress" :"dev-sqlapi-acc-westus.documents.azure.com:443/…:"{\"code\":\"Forbidden\",\"message\":\"Request blocked by Auth dev-sqlapi-acc : The given request [POST /dbs] cannot be authorized by AAD token in data plane.\\r\\, Microsoft.Azure.Documents.Common/2.11.0, StatusCode: Forbidden\",\"additionalErrorInfo\":null}","innerErrorMessage":"Request blocked by Auth dev-sqlapi-acc : The given request [POST /dbs] cannot be authorized by AAD token in data plane

**To Reproduce**
For reproduction create service principal with above role definitions and then execute code below.

***Code Snippet***
```
TokenCredential ServicePrincipal = new ClientSecretCredentialBuilder()
            .authorityHost("https://login.microsoftonline.com")
            .tenantId(tenant_here)
            .clientId(clientid_here)
            .clientSecret(secret_from_above_client)
            .build();

 client = new CosmosClientBuilder()
                            .endpoint(AccountSettings.HOST)
                            .credential(ServicePrincipal)
                            .buildAsyncClient();
```

**Expected behavior**
SDK should create client with service principal with assigned "Cosmos DB Operator" or "DocumentDB Account Contributor" role definition, even if they do not have reading metadata. Such client should be able to create database and container.

**Screenshots**

**Setup (please complete the following information):**
 - OS: WINDOWS
 - IDE : IntelliJ
 - LATEST

**Additional context**
Custom roles works.  When firstly I created database and container with master key and then I want to read/write data using service principal, it works (obviously after adding custom role for writting also).

**Information Checklist**
Kindly make sure that you have added all the following information above and checkoff the required fields otherwise we will treat the issuer as an incomplete report
- [x] Bug Description Added
- [x] Repro Steps Added
- [x] Setup information Added

**Comment by joshfree** [comment]
@kushagraThapar could you please take a look?

**Comment by moarychan** [comment]
hi all, I got the same issue, the limitation will block the developers use the Azure Service Principal pattern for authentication.
I have assigned the Cosmos DB Operator role and Cosmos DB Built-in Data Contributor with cosmos account, but the database creation will be blocked. If I create the database manually, then it will work normally. 
![MicrosoftTeams-image-cosmos-data-plane](https://user-images.githubusercontent.com/19926623/140669255-cf301abe-5f61-4aad-877f-121b0ddace0f.png)

**Comment by kushagraThapar** [comment]
@milismsft  - this is an older issue, not sure what is the update on this, can you please take a look once you get some time. Thanks!

**Comment by milismsft** [comment]
This is "by design" and publicly documented; only read only management operations are supported with AAD. Azure Cosmos DB SDK specifically require "readMetadata" role action.

For more information see:
https://docs.microsoft.com/en-us/azure/cosmos-db/how-to-setup-rbac#permission-model
https://docs.microsoft.com/en-us/azure/cosmos-db/how-to-setup-rbac#metadata-requests
