### ISSUE TITLE
Event Hubs: Create performance tests for Track 1 vs Track 2

### ISSUE THREAD

**Issue by YijunXieMS** [Azure/azure-sdk-for-java#20791]
Use the azure-sdk-for-java perf test framework to create perf tests for EventHubs Track1 and Track2. Run them before every release that has perf-related changes in azure-core-amqp or eventhubs.

Instructions to setup performance tests can be found in this wiki: 
https://github.com/Azure/azure-sdk-for-java/wiki/Writing-Performance-Tests

**Comment by conniey** [comment]
Supercedes: #14307
