### ISSUE TITLE
How azure will treat multiple actions on VM

### ISSUE THREAD

**Issue by phebbal** [Azure/azure-sdk-for-java#2080]
I am trying to understand the azure behavior when there are multiple actions are taken on the VM.
Very specific to the following use cases
**- VM Deallocating not yet deallocated and from another thread, if we perform power-on**  
**- How do I differentiate the VM deallocating state if is due to delete action or due to powering down**

**Comment by Drewm3** [comment]
Cleaning up old issues from 2016 - 2018. Please reopen this issue if it is still a concern.
