### ISSUE TITLE
is OAuth 2.0 SDK with OpenID Connect Extensions » 5.30 is safe to use (no security vulnerabilities)

### ISSUE THREAD

**Issue by mayankbmc** [Azure/azure-sdk-for-java#20815]
Hello Team  

Our security team raised alarm for this lib (https://mvnrepository.com/artifact/com.nimbusds/oauth2-oidc-sdk/5.30) is vulnerable for xml parsing . But i have not seen anything related to cml parsing in this lib . 

They found via transitive dependency of this lib lib (java maven) com.microsoft.azure:azure:1.38.1.

Can anyone help if it is safe

**Comment by joshfree** [comment]
@alzimmermsft PTAL

**Comment by alzimmermsft** [comment]
Hi @mayankbmc, which libraries are you using that have a transitive dependency on `com.microsoft.azure:azure`? There are newer SDKs available which upgrade the mentioned dependency to newer versions that no longer contain the security risks in that version. Once the libraries are known that use this dependency I can help you work towards upgrading to a newer version to resolve this issue.

**Comment by alzimmermsft** [comment]
Hi @mayankbmc, the following is an outline of available upgrades that could resolve this dependency CVE.

There are new client and management SDK libraries underneath the `com.azure` and `com.azure.resourcemanager` groups which are actively maintained and keep dependencies up to date to prevent and resolve CVEs. The new SDKs are a major version, or a complete artifact identifier, change which involves API changes to use them.

The following are a few examples of SDK transitions.

**azure-storage**

com.azure:azure-storage-blob
com.azure:azure-storage-file-datalake
com.azure:azure-storage-file-share
com.azure:azure-storage-queue
com.azure:azure-data-tables

**azure-mgmt-network**

com.azure.resourcemanager:azure-resourcemanager-network

**azure-mgmt-traffic-manager**

com.azure.resourcemanager:azure-resourcemanager-trafficmanager

**azure-keyvault-core**

com.azure:azure-security-keyvault-certificates
com.azure:azure-security-keyvault-keys
com.azure:azure-security-keyvault-secrets

Some upgrades aren’t a one-for-one as libraries may have been split into multiple libraries or their functionality isn’t a direct port. Additionally, for the new libraries Azure SDKs for Java offers a [bill of materials](https://github.com/Azure/azure-sdk-for-java/tree/master/sdk/boms/azure-sdk-bom), BOM, POM which we maintain to ensure dependency compatibility for all libraries contained within it. This is our current recommendation for customers who don’t want to manage individual dependencies, at this time it doesn’t release with the same cadence as individual SDKs so it won’t contain the latest features and fixes.
