### ISSUE TITLE
[BUG] CosmosDB SQL API ReadAllItems method does not return results

### ISSUE THREAD

**Issue by ircey** [Azure/azure-sdk-for-java#20814]
**Describe the bug**
ReadAllItems methods work fine when I have flat structure of class. I mean no subclasses nested inside my model class. Problem starts when I have partitionkey specified inside subclass of rootclass. Below is class example, which does not work:

```
public class Root {
    public Root(){};

    public String getId() {
        return id;
    }

    public void setId(String id) {
        this.id = id;
    }

    public Subclass getSubclass () {
        return subclass;
    }

    public void setSubclass (Subclass subclass) {
        this.subclass= subclass;
    }

    private String id = "";
    private Subclass subclass= new Subclass ();
}
```

subclass just contains partitionKey for simplicity.

```
public class Subclass {

    public String getPk() { return pk; }

    public void setPk(String pk) {
        this.pk = pk;
    }

    private String pk="";
}
```
With such "structure" I can easily create items inside container, with proper values of partitionkey, but I am not able to load them again just using partitionKey value. 

***Exception or Stack Trace***
Add the exception log and stack trace if available

**To Reproduce**
Create classes like above and use readallitems method for quering.

***Code Snippet***
Here is code snippet for reading them from cosmosdb:
```
PartitionKey partitionKey = new PartitionKey("properValueWhichWorksWithNoNestedClassesInsideRoot");
CosmosPagedFlux<Root> pagedFluxResponse = container.readAllItems(partitionKey, Root.class);
try {
   double totalRequestCharge = pagedFluxResponse.byPage(preferredPageSize).flatMap(fluxResponse -> {
      entities.addAll(fluxResponse.getResults());

      return Mono.just(fluxResponse.getRequestCharge());
   })
   .reduce(0.0, (x1, x2) -> x1 + x2)
   .block();

   logger.info("Query charge: {}", totalRequestCharge);
} catch(Exception err) {
         err.printStackTrace();
}

return entities;
```

**Expected behavior**
ReadAllItems returns results.

**Screenshots**

**Setup (please complete the following information):**
 - OS: Windows
 - IDE : IntelliJ
 - LATEST

**Additional context**

**Information Checklist**
Kindly make sure that you have added all the following information above and checkoff the required fields otherwise we will treat the issuer as an incomplete report
- [x] Bug Description Added
- [x] Repro Steps Added
- [x] Setup information Added

**Comment by kushagraThapar** [comment]
@ircey  - Does the `readAllItems` API throw any exception ?
Also, I am wondering, if simple read operations are working for nested partition key types, like just `readItem()` API ?

**Comment by ircey** [comment]
@kushagraThapar - It does not throw exception. It just does not return any results. I do not use `readItem()`.

**Comment by kushagraThapar** [comment]
@ircey  - please give it a try and let me know how the point operations are working with nested partition key types.

**Comment by ircey** [comment]
@kushagraThapar - Sorry, I have also other things to do on me and I do not have time on testing other things. Please test it on your own.

**Comment by kushagraThapar** [comment]
@ircey - no problem, will take a look at this soon, thanks!

**Comment by kushagraThapar** [comment]
Nested partition key support has been added for `readAllItems()`
