### ISSUE TITLE
[BUG] azure-spring-boot-starter-active-directory-b2c cannot validate access token from client

### ISSUE THREAD

**Issue by sunyong00** [Azure/azure-sdk-for-java#20824]
**Describe the bug**
The "Sample for Azure AD B2C Resource server Spring Boot client library for Java" (https://github.com/Azure/azure-sdk-for-java/tree/azure-spring-boot-starter-active-directory_3.3.0/sdk/spring/azure-spring-boot-samples/azure-spring-boot-sample-active-directory-b2c-resource-server) does not work as "azure-spring-boot-starter-active-directory-b2c" cannot validate access token from client.

***Exception or Stack Trace***
Caused by: java.lang.IllegalArgumentException: The issuer: 'https://xxxxx.b2clogin.com/xxxxx/v2.0/' is not registered in trusted issuer repository, so cannot create JWSKeySelector.
	at com.azure.spring.aad.AADIssuerJWSKeySelector.selectKeys(AADIssuerJWSKeySelector.java:55)
	at com.nimbusds.jwt.proc.DefaultJWTProcessor.selectKeys(DefaultJWTProcessor.java:308)
	at com.nimbusds.jwt.proc.DefaultJWTProcessor.process(DefaultJWTProcessor.java:381)
	at com.nimbusds.jwt.proc.DefaultJWTProcessor.process(DefaultJWTProcessor.java:330)
	at org.springframework.security.oauth2.jwt.NimbusJwtDecoder.createJwt(NimbusJwtDecoder.java:153)

**To Reproduce**
1. Register API App in Azure AD B2C, and develop the API app as per sample above
2. Register Web App in Azure AD B2C
3. In web browser, enter URL "https://xxxxx.b2clogin.com/xxxxx.onmicrosoft.com/xxxxxsignupsignin/oauth2/v2.0/authorize?response_type=token&scope=https%3A%2F%2Fxxxxxb2c.onmicrosoft.com%xxxxx%2FAPI.Read&client_id=xxxxx&redirect_uri=https%3A%2F%2Fjwt.ms&response_mode=fragment&state=12345&nonce=67890" to get access token. The client_id in the URL is the ID fo the Web App
4. From Postman, send API request to API server. The exception will happen.

**Comment by joshfree** [comment]
@stliu PTAL

**Comment by yiliuTo** [comment]
Thanks for your reporing, we will look into it soon.

**Comment by lzc-1997-abel** [comment]
@ZhuXiaoBing-cn please help to look at this issue

**Comment by ZhuXiaoBing-cn** [comment]
Hi,@sunyong00, Thanks for your reporting.

You can run your sample through the following steps.
First, you need to modify your user flow configuration on the portal and replace it with this form of **Issuer (iss)** claim as shown below:
![image](https://user-images.githubusercontent.com/71206407/116493637-b39d6500-a8d1-11eb-9ce4-b628ebfbe052.png)

Next, we need to add the code as follows:
```java
@EnableWebSecurity
public class WebSecurityConfiguration extends WebSecurityConfigurerAdapter {

    @Autowired
    AADTrustedIssuerRepository aadTrustedIssuerRepository;
    @Autowired
    AADB2CProperties aadb2CProperties;
    @Autowired
    JWTProcessor<SecurityContext> jwtProcessor;

    public JwtDecoder jwtDecoder(JWTProcessor<SecurityContext> jwtProcessor) {
        NimbusJwtDecoder decoder = new NimbusJwtDecoder(jwtProcessor);
        List<OAuth2TokenValidator<Jwt>> validators = new ArrayList<>();
        List<String> validAudiences = new ArrayList<>();
        if (StringUtils.hasText(aadb2CProperties.getAppIdUri())) {
            validAudiences.add(aadb2CProperties.getAppIdUri());
        }
        if (StringUtils.hasText(aadb2CProperties.getClientId())) {
            validAudiences.add(aadb2CProperties.getClientId());
        }
        if (!validAudiences.isEmpty()) {
            validators.add(new AADJwtAudienceValidator(validAudiences));
        }
        validators.add(new JwtTimestampValidator());
        decoder.setJwtValidator(new DelegatingOAuth2TokenValidator<>(validators));
        return decoder;
    }

    @Override
    protected void configure(HttpSecurity http) throws Exception {
        aadTrustedIssuerRepository.addTrustedIssuer("https://xxxxxxb2c.b2clogin"
            + ".com/tfp/<tenant-id>/<user-flow-name>/v2.0/".toLowerCase());

        http.authorizeRequests((requests) -> requests.anyRequest().authenticated())
            .oauth2ResourceServer()
            .jwt()
            .decoder(jwtDecoder(jwtProcessor))
            .jwtAuthenticationConverter(new AADB2CJwtBearerTokenAuthenticationConverter());
    }
}
```

If you find that ArrayUtils.class is missing, please add the following dependencies:
```java
<dependency>
        <groupId>commons-lang</groupId>
        <artifactId>commons-lang</artifactId>
        <version>2.6</version>
</dependency>
```

**Comment by sunyong00** [comment]
Hi @ZhuXiaoBing-cn, thank you for fixing the issue. Your code is working. You may consider updating the readme in the GitHub project "Sample for Azure AD B2C Resource server Spring Boot client library for Java"

**Comment by ZhuXiaoBing-cn** [comment]
@sunyong00 I will update the readme document in the GitHub project "Sample for Azure AD B2C Resource server Spring Boot client library for Java".

**Comment by chenrujun** [comment]
Hi, @ZhuXiaoBing-cn , could you please paste the link of related PR?

**Comment by ZhuXiaoBing-cn** [comment]
This PR(https://github.com/Azure/azure-sdk-for-java/pull/21050) fixes the issues and adds the latest readme.
