### ISSUE TITLE
Event Hubs: Investigate performance test results

### ISSUE THREAD

**Issue by conniey** [Azure/azure-sdk-for-java#20828]
Investigate results or create an issue if the bug requires deeper research or a bigger fix.

Dependent on #20791

**Comment by anuchandy** [comment]
The current status is:

We've implemented two standalone apps to measure the performance of T1 and T2. The apps measure the performance of the "Batch Receive APIs".  

There are two use cases under the Batch Receive APIs:

1_. Batch Receive with a timeout (exercises internal no backpressure route).
2_. Batch Receive without timeout (exercises internal backpressure route).

We started with "Batch Receive with a timeout" use case and found a regression, a fix got merged to the main.

With the latest nightly build (mirrors the main branch), we see that performance of T2 for "Batch Receive with a timeout" is on par with T1. The Apps used for this are: [T1_App](https://github.com/mikeharder/azure-sdk-for-java/blob/5c7af067a59135fb9a9ad51aa9d9cdf2a8431d05/test/t1-processortest/src/main/java/com/example/App.java#L19), [T2_App](https://github.com/mikeharder/azure-sdk-for-java/blob/5c7af067a59135fb9a9ad51aa9d9cdf2a8431d05/test/processortest/src/main/java/com/example/App.java#L23).

The version of nightly build used for the measuring "Batch Receive with a timeout" can be pulled by adding below repository and dependency:

```
<repository>
  <id>azure-sdk-for-java</id>
  <url>https://pkgs.dev.azure.com/azure-sdk/public/_packaging/azure-sdk-for-java/maven/v1</url>
  <releases>
    <enabled>true</enabled>
  </releases>
  <snapshots>
    <enabled>true</enabled>
  </snapshots>
</repository>
```

```
<dependency>
  <groupId>com.azure</groupId>
  <artifactId>azure-messaging-eventhubs-checkpointstore-blob</artifactId>
  <version>1.9.0-alpha.20210726.1</version>
</dependency>
```

Currently, we're modifying the app to validate "Batch Receive without timeout" to understand what to fix in this use case.
