### ISSUE TITLE
Integrate proton-j logging to use ClientLogger

### ISSUE THREAD

**Issue by conniey** [Azure/azure-sdk-for-java#20825]
proton-j uses java.util.logging whereas we use slf4j as our logging. It would be easier to diagnose problems if we bridged the two instead of having to turn on multiple settings.

## Context

When we have customer support cases related to Event Hubs and Service Bus, we ask them to include logs (ie. enabling AZURE_LOG_LEVEL=2). This provides sufficient logging for our libraries but there are times we want to understand if it is a problem in our external dependency or ours.

proton-j uses java.util.logging, so we'd have to ask them to configure/add another logging dependency. It would be nice if this was considated by somehow mapping to slf4j (which is what we use).

**Comment by conniey** [comment]
After consideration, this is probably not a good end-user experience if we hijack the logging experience.

**Comment by jongio** [comment]
@conniey - Thoughts on an alternate approach or are we good to move on?

**Comment by conniey** [comment]
> @conniey - Thoughts on an alternate approach or are we good to move on?

We can move on. :)
