### ISSUE TITLE
Event Hubs: Performance degradation between 5.6.0 and 5.7.0

### ISSUE THREAD

**Issue by conniey** [Azure/azure-sdk-for-java#20841]
From #19698:

> I replaced in my project
> `azure-messaging-eventhubs: 5.6.0` and `azure-messaging-eventhubs-checkpointstore-blob: 1.5.0`
> with
> `azure-messaging-eventhubs: 5.7.0` and `azure-messaging-eventhubs-checkpointstore-blob: 1.6.0`
> and unfortunately I see a performance decrease by max 50%.
> 
> I also tested
> `azure-messaging-eventhubs: 5.6.0` and `azure-messaging-eventhubs-checkpointstore-blob: 1.6.0`
> as well as
> `azure-messaging-eventhubs: 5.7.0` and `azure-messaging-eventhubs-checkpointstore-blob: 1.5.0`
> with the same decreasing performance.
> 
> I didn't dive into this yet in detail.
> Would be nice if you can check this behavior on your site.

Related #20791

**Comment by the-mod** [comment]
@conniey: sorry for the late reply and thanks for creating a new Issue.

I ran my Testapp with 3 Replicas on `AKS 1.19.9` with 3 Nodes of `Standard_D8as_v4`.
Each JVM (zulu-openjdk 16) had 3GB Heap Space assigned.
The Code was compiled for Java13 and is using `Spring Boot 2.3.2.RELEASE`.
I send 10 mill Messages to an eventhub for each run (lets name it `input eventhub`) where my App is reading from.
My App is writing the Results roundrobin to two Eventhubs (output eventhubs) after processing.

* dark blue line: incoming messages of the input eventhub.  
* turquoise line: outgoing messages of the input eventhub. This are the messages read by my app
* red/blue lines: incoming messages of the output eventhubs. This are the messages my app is writing.
* The Resolution of the Chart is 1 Minute

Here are my results:
![benchmarking](https://user-images.githubusercontent.com/31224087/115465336-bb546e00-a22e-11eb-8a86-c158474cfff7.png)


We can see that the SDK combinations mentioned above seams to face a limit (1mill/minute) of reading/receiving messages.
Let me know if I can provide more Informations.
Regards

**Comment by mikeharder** [comment]
The `OverflowException` in `azure-messaging-eventhubs@5.10.0` is a known issue and we are working on a fix.

As a workaround, I believe the `EventProcessorClientBuilder.processEvent()` and `EventProcessorClientBuilder.processEventBatch()` APIs which do **not** accept a `maxWaitTime` parameter should avoid the `OverflowException`, if these would work in your application.

**Comment by the-mod** [comment]
@mikeharder 

I tried the `processEventBatch()` without the `maxWaitTime` Parameter as suggested.
It run stable at a high level of Performance.

I only got some Errors in the log without any Stacktrace:

`com.azure.core.amqp.implementation.ReactorDispatcher - ReactorDispatcher instance is closed.`

**Comment by mikeharder** [comment]
@the-mod: I see existing issues with error `ReactorDispatcher instance is closed`, but they are all closed:

https://github.com/Azure/azure-sdk-for-java/issues/19698
https://github.com/Azure/azure-sdk-for-java/issues/19753

@conniey, @anuchandy: Do you know more about this issue and whether it has been fixed?

**Comment by conniey** [comment]
This may be a false warning (we need to suppress) because any time work is scheduled on a closed reactor, we emit that message. It's normal for Reactor instances to be closed when we are recreating connections, etc.

Does this message impact your application? Do you see it not recovering?

**Comment by the-mod** [comment]
@conniey The App was running fine. Only saw this popping up in the logs.

**Comment by conniey** [comment]
Thanks for confirming! @anuchandy and I were talking about how useful this log is because it seems to add to noise rather than root cause.

**Comment by conniey** [comment]
It sounds like we were able to solve the issue. We are still looking at resolving the overflow exception via https://github.com/Azure/azure-sdk-for-java/issues/23950. Please feel free to open another issue if it crops up again. Thanks!
