### ISSUE TITLE
Implement ACR API Updates

### ISSUE THREAD

**Issue by annelo-msft** [Azure/azure-sdk-for-java#20872]
We're making some design changes per arch board feedback.  Once these are complete, we'll need to implement these changes for all four languages.

This will include:
- [ ] Re-generating code from the updated swagger file
- [ ] Moving methods to repository and artifact helper classes
- [ ] Implementing the lazy digest lookup in RegistryArtifact
- [ ] Updating tests and samples

**Comment by pallavit** [comment]
Done as part of the ACR beta3 library.
