### ISSUE TITLE
Azure Blob - How to count number of blobs in a directory or container?

### ISSUE THREAD

**Issue by abhikt48** [Azure/azure-sdk-for-java#20893]
We have requirement to get total count of blobs from a directory and container as well.

Could you please share sample code to get total blob count from a  
 1) given directory  
 2) Container

We are using latest SDK  `azure-storage-blob-12.10.2` . 

**Setup (please complete the following information if applicable):**
OS: window
IDE : eclipse
Version of the Library used: `azure-storage-blob-12.10.2`

**Comment by alzimmermsft** [comment]
@gapra-msft do we have an example of this?

**Comment by gapra-msft** [comment]
Hi @abhikt48 Unfortunately we don't have a special API for this. The way to do this would be listing the containers using BlobServiceClient.listContainers and listing the blobs in a directory by BlobContainerClient.listBlobs and setting the options to point to the directory name as a prefix. Then you would have to count the number of results returned.

Let me know if you need detailed sample code.

**Comment by abhikt48** [comment]
@gapra-msft  Thanks for quick input 👍
