### ISSUE TITLE
[BUG] Cx met intermittent InvalidFlushPosition error when calling method uploadFromFile

### ISSUE THREAD

**Issue by yangchengs** [Azure/azure-sdk-for-java#20937]
**Describe the bug**
Cx is Informatica, two of their clients report the same issue.
They have heavy loads on the jobs, but they met intermittent InvalidFlushPosition errors.
The file size is not big, it is usually several MBs.
I will share jarvis log internally when this ticket has an owner.

Java SDK version: azsdk-java-azure-storage-file-datalake/12.3.0 (1.8.0_275; Linux; 3.10.0-1160.15.2.el7.x86_64

***Exception or Stack Trace***
Apr 22, 2021 7:34:27 AM       ERROR     com.informatica.adapter.adlsgen2.metadata.adapter.Adlsg2Exception: Exception while uploading file, error: Exception while uploading file, error: Status code 400, "{"error":{"code":"InvalidFlushPosition","message":"The uploaded data is not contiguous or the position query parameter value is not equal to the length of the file after appending the uploaded data.\nRequestId:58e0c48b-801f-0078-3e49-374306000000\nTime:2021-04-22T07:34:27.0577077Z"}}"

**To Reproduce**

***Code Snippet***

private void uploadOverwriteFile(Logger logger) throws Adlsg2Exception{
if(insertStagingFile != null || insertStagingFileMI != null){
try{
String stagingFilePath = "";
if(insertStagingFile != null)
stagingFilePath = insertStagingFile.getAbsolutePath();
else if (insertStagingFileMI != null)
stagingFilePath = insertStagingFileMI;

Long blockSizeVal = blockSize>0 ? blockSize : 8 * 1024L * 1024L; // 8 MB;
ParallelTransferOptions parallelTransferOptions = new ParallelTransferOptions().setBlockSizeLong(blockSizeVal).setMaxConcurrency(numThreads);

DataLakeFileClient fileClient = getFileClient(fileSystemNameForWrite, directoryPath, filePathForWrite);
fileClient.create(true);
//Begin: to avoid upload of 0 byte sized file  CCON-31001
File file = new File(stagingFilePath);
if(file !=null && file.exists()){
long flen = (long) file.length();
if(flen!=0)
{
long t1= System.currentTimeMillis();
fileClient.uploadFromFile(stagingFilePath, parallelTransferOptions, null, null, null, null);
long t2= System.currentTimeMillis();
if(logger!=null)
    logger.logMessage(EMessageLevel.MSG_DEBUG, ELogLevel.TRACE_NONE, "Time taken to ADLS Gen2 Upload(ms)="+(t2-t1));
}
}
//END

}catch(Exception e){
throw new Adlsg2Exception("Exception while uploading file, error: "+e.getMessage());
}
}else
throw new Adlsg2Exception("No file to upload");
}

**Setup (please complete the following information):**
 - OS: Linux
 - Version of the Library used
azsdk-java-azure-storage-file-datalake/12.3.0 (1.8.0_275; Linux; 3.10.0-1160.15.2.el7.x86_64

**Comment by joshfree** [comment]
@gapra-msft PTAL

**Comment by gapra-msft** [comment]
Hi @yangchengs 
Thank you for reporting this issue. We will take a look and see what is going wrong.

**Comment by gapra-msft** [comment]
@yangchengs Could you share the size of the file being uploaded that hits this issue? Is it greater than or less than 4000MB?

**Comment by yangchengs** [comment]
@gapra-msft 
The numThreads = 1
The files are usually small, several MBs, far less than 4000MB
In the case with request id 58e0c48b-801f-0078-3e49-374306000000, the file size is 917k.

**Comment by yangchengs** [comment]
@gapra-msft Hello, do you have any update on this issue?

**Comment by yangchengs** [comment]
@gapra-msft Hello Gauri, may I query the status of this ticket? Cx has implemented a retry pattern and it works. This is a temp fixing because the InvalidFlushPosition is not a retriable error, cx is asking the root cause and permanent fix.

**Comment by amishra-dev** [comment]
Hi @yangchengs 
Glad to hear that the workaround is working for the customer. This will require some service changes, we do not have a timeline for the fix at the moment.
