### ISSUE TITLE
[QUERY] Service principal (SPN) usage, to access azure storage?

### ISSUE THREAD

**Issue by chechoochoo** [Azure/azure-sdk-for-java#20939]
**Query/Question**
I am new to the Azure SDK for Java. So far I could not find a solution on how to:

- either: use SPN credentials directly
- or: use SPN to create a SAS

to access Azure Storage (blob).

The `BlobServiceClientBuilder` accepts:

- `credential(StorageSharedKeyCredential credential)` - works only on actual keys from Azure Storage (no-go for me currently - as I need to use SPN)

- `credential(TokenCredential credential)` - not sure how to use this; is it related to `ClientSecretCredential`? if yes - how I can use them for SPN

- `credential(AzureSasCredential credential)` - looks promising, but I could not find any hints on how to create the SAS in the first place, for my SPN.

Side note - my SPN has necessary permissions to given storage account / blob - was able to use `az cli` to list elements etc.

Thank you in advance for support :)

***Why is this not a Bug or a feature Request?***
With plethora of options - I assume feature already exists, I just could not find any documentation / example on "how-to".

**Setup (please complete the following information if applicable):**
 - OS: OSX
 - IDE : IntelliJ
 - Version of the Library used:
```xml
	<dependencyManagement>
		<dependencies>
			<dependency>
				<groupId>com.azure.spring</groupId>
				<artifactId>azure-spring-boot-bom</artifactId>
				<version>3.3.0</version>
				<type>pom</type>
				<scope>import</scope>
			</dependency>
		</dependencies>
	</dependencyManagement>
...
		<dependency>
			<groupId>com.azure.spring</groupId>
			<artifactId>azure-spring-boot-starter-storage</artifactId> <!-- azure-storage-blob -> 12.10.1 -->
		</dependency>
```

**Comment by joshfree** [comment]
@gapra-msft PTAL

**Comment by gapra-msft** [comment]
Hi @chechoochoo 

Please see https://github.com/Azure/azure-sdk-for-java/tree/master/sdk/storage/azure-storage-blob#authenticate-with-azure-identity for more information on how to authenticate via SPN.

**Comment by chechoochoo** [comment]
@gapra-msft , @joshfree thx <3

Those URLs were a huge help indeed. Apart from samples, it was also clarification on permissions my SPN had, and turned out I needed to use `BlobClient` directly (SPN does not have sufficient permissions to use `BlobServiceClient`), with `ClientSecretCredential` to make RBAC work.

**Comment by gapra-msft** [comment]
Great! @chechoochoo
