### ISSUE TITLE
[BUG]Uploading large files (>= 200 MB) seems to hang when using upload(InputStream) API in DataLakeFileAsyncClient

### ISSUE THREAD

**Issue by masokan** [Azure/azure-sdk-for-java#20946]
When uploading a large file using upload(InputStream) API, the subscriber to the Mono object returned from the API never receives onComplete() or onError() calls

***Exception or Stack Trace***
Add the exception log and stack trace if available

**To Reproduce**
Please refer to the example in https://github.com/masokan/test-azure-upload

***Code Snippet***
Code is available in the above github repository

**Expected behavior**
The upload should complete in a short time

**Screenshots**

**Setup (please complete the following information):**
 - OS: Linux
 - IDE : [e.g. IntelliJ]
 - 12.5.0-beta.3

**Additional context**

**Information Checklist**
Kindly make sure that you have added all the following information above and checkoff the required fields otherwise we will treat the issuer as an incomplete report
- [X] Bug Description Added
- [X] Repro Steps Added
- [X] Setup information Added

**Comment by joshfree** [comment]
@gapra-msft PTAL

**Comment by gapra-msft** [comment]
Hi @masokan 

Thank you for reporting this issue, we will take a look and get back to you.

**Comment by gapra-msft** [comment]
Hi @masokan 

Just to update you, we have found the source of the issue. I am currently working on a fix and validating it.

**Comment by masokan** [comment]
@gapra-msft Thanks for your quick response on this issue.
