### ISSUE TITLE
Can't accept legal terms via the Java SDK.

### ISSUE THREAD

**Issue by apache8080** [Azure/azure-sdk-for-java#2094]
I am trying to create a Virtual Machine via the Java SDK and I get the following error:
```
User failed validation to purchase resources. Error message: 'Legal terms have not been accepted for this item on this subscription.
```
When creating a VM with the CLI there is an accept-terms flag that can be passed to solve this issue. Is there a way to do this with Java SDK, if not this would be a nice feature to have.

**Comment by gavinfish** [comment]
Hi @apache8080 , what is your solution to this question? I have encountered the same problem.
