### ISSUE TITLE
Support for Azure license type.

### ISSUE THREAD

**Issue by romel-github** [Azure/azure-sdk-for-java#2095]
Hi,

I'm looking for help in setting up the Azure license type from java SDK. I explored the SDK, but couldn't found any support from the API to set the license type of the windows machine. Although, virtual machine object does have licenseType as one of the attribute. I am looking for help in setting up the license type either during machine provisioning or a day 2 operation.

Thanks in advance.
Shantanu Sahay

**Comment by praries880** [comment]
You could use [WithLicenseType](https://github.com/Azure/azure-sdk-for-java/blob/18e9a4b927fafc64349de742ccd2f546da9c653b/compute/resource-manager/v2017_12_01/src/main/java/com/microsoft/azure/management/compute/v2017_12_01/VirtualMachine.java#L165) when creating or [updating](https://github.com/Azure/azure-sdk-for-java/blob/18e9a4b927fafc64349de742ccd2f546da9c653b/compute/resource-manager/v2017_12_01/src/main/java/com/microsoft/azure/management/compute/v2017_12_01/VirtualMachineUpdate.java#L302) the vm
