### ISSUE TITLE
[FEATURE REQ] spring-data-cosmos paging without incurring cost of count query

### ISSUE THREAD

**Issue by johnmannix** [Azure/azure-sdk-for-java#20950]
**Is your feature request related to a problem? Please describe.**
I want to page through a large result set using continuation tokens and the azure-spring-data-cosmos library. However, pageable repository methods always issue a count query to populate the total elements in the page response, and when the query is complex and the result set is large, the count query can be very expensive. 

**Describe the solution you'd like**
I would like to be able to use CosmosPageRequest to fetch a page of data with a continuation token without issuing a count query to populate the total elements. Perhaps you could support methods which return Slice<T> and take CosmosPageRequest.

**Describe alternatives you've considered**
Considered extending CosmosTemplate, but too many fields and methods are defined with private access modifiers. 

**Additional context**
One particular example is adding a sort to a query which pages through a collection with 5 million records caused the cost of the count query to jump from 4 RUs to 180k RUs. Since we don't need to know the total number of elements for our use case this extra query cost is unnecessary.

**Information Checklist**
Kindly make sure that you have added all the following information above and checkoff the required fields otherwise we will treat the issuer as an incomplete report
- [x] Description Added
- [x] Expected solution specified

**Comment by joshfree** [comment]
Hi @kushagraThapar could you please help route this?

**Comment by kushagraThapar** [comment]
I will take a look at this.

**Comment by johnmannix** [comment]
@kushagraThapar please see linked pull request for proposed solution to the issue

**Comment by kushagraThapar** [comment]
@johnmannix - thank you for creating the forked pull request, I looked at it, and it looks good so far. Can you please create an official pull request, so we can get your contribution to azure-spring-data-cosmos SDK ?
