### ISSUE TITLE
[QUERY] Can't find azure-spring-boot-starter-active-directory beta version in maven central

### ISSUE THREAD

**Issue by einue** [Azure/azure-sdk-for-java#20979]
Hi, I try to use your sample "azure-spring-boot-sample-active-directory-resource-server" .

There you use the dependency 
```
<dependency>
      <groupId>com.azure.spring</groupId>
      <artifactId>azure-spring-boot-starter-active-directory</artifactId>
      <version>3.5.0-beta.1</version>
</dependency>
```

I could not find this dependency, neither on https://oss.sonatype.org/#nexus-search;quick~azure-spring-boot-starter-active-directory ?

Could you please add the Post-Requests to get the token with postman and to get the request of your example endpoints?

I tried it with version "3.4.0" with no success...

**Comment by joshfree** [comment]
@stliu could you please assist @einue?

**Comment by saragluna** [comment]
Hi @einue, the version on the master branch is the development version and hasn't be released to the maven central. Please follow the [environment-checklist](https://github.com/Azure/azure-sdk-for-java/blob/master/sdk/spring/ENVIRONMENT_CHECKLIST.md#use-development-version) for more details.

**Comment by saragluna** [comment]
I saw another issue created https://github.com/Azure/azure-sdk-for-java/issues/20980, so are we okay to close this one now?

**Comment by einue** [comment]
yes @saragluna  you can close this issue, thanks
