### ISSUE TITLE
Randomly generated Partition key - Azure Linux Virtual Machines

### ISSUE THREAD

**Issue by ShailashreeE** [Azure/azure-sdk-for-java#2098]
Upon enabling diagnostics for Azure Linux Virtual machines in Azure portal, some diagnostics tables are created in the assigned diagnostics storage account. In those tables, the PartitionKey column is in the format 000000000000000000x__0636370812000000000 
(x is some random number) 
We are aware that the portion after "__" is the current time in ticks.
But the number substituted for x is randomly changing, due to which we are not able to query diagnostics data for current time.

<img width="913" alt="linuxdiagnostics" src="https://user-images.githubusercontent.com/28895501/41534358-f2939d54-731b-11e8-9d3c-1022a899c661.png">

We would like to know if there is any means of making the random number static ?
Also on what basis is that random number generated ?  

Thanks in advance.

**Comment by Drewm3** [comment]
Cleaning up old issues from 2016 - 2018. Please reopen this issue if it is still a concern.
