### ISSUE TITLE
Document Serialization and Deserialization Guidelines of JacksonAdapter

### ISSUE THREAD

**Issue by alzimmermsft** [Azure/azure-sdk-for-java#20997]
Create documentation which outlines all serialization and deserialization assumptions and guidelines that `JacksonAdapter` follows.

**Comment by lmolkova** [comment]
Updated [Serialization](https://github.com/Azure/azure-sdk-for-java/wiki/Serialization) and [Custom JSON serializer](https://github.com/Azure/azure-sdk-for-java/wiki/Custom-JSON-serializer). Let me know if you feel anything is off or missing.
