### ISSUE TITLE
Resilient Jackson Multi-Version Support

### ISSUE THREAD

**Issue by alzimmermsft** [Azure/azure-sdk-for-java#20998]
Related #20997 

Determine which versions of Jackson the Azure SDKs can support and create version specific configurations to ensure consistent serialization and deserialization across versions.

Targeted version support is at least:

- [x] 2.10
- [x] 2.11
- [x] 2.12

**Comment by lmolkova** [comment]
Fixed (for Azure.Core) in #23279, #23441 #24138, #23283
