### ISSUE TITLE
[REFACTOR] azure-core-amqp - stop exposing implementation classes to Service Bus

### ISSUE THREAD

**Issue by conniey** [Azure/azure-sdk-for-java#20992]
Service Bus requires some features like AmqpValue that are currently not exposed in azure-core-amqp. We want to wait until it is shipped in GA before we stop exporting those interfaces.

Related to #5478

**Comment by ramya-rao-a** [comment]
@ki1729 What is the latest on this? Can we update the milestone here based on whether or not we plan to take this up this semester?
