### ISSUE TITLE
NetworkSecurityRule.destinationPortRanges returns only last range in list

### ISSUE THREAD

**Issue by alexz75** [Azure/azure-sdk-for-java#2100]
I've defined port range in NSG with following port ranges 8080-8443,8553.
Currently NetworkSecurityRule.destinationPortRanges returns only last item - 8553, but expected to return or whole string  8080-8443,8553 or List of all ranges

The Azure CLI returns follow:
`{
        "access": "Allow",
        "description": null,
        "destinationAddressPrefix": "*",
        "destinationAddressPrefixes": [],
        "destinationApplicationSecurityGroups": null,
        "destinationPortRange": null,
        "destinationPortRanges": [
          "8080-8443",
          "8553"
        ],
        "direction": "Inbound",
        "etag": "W/\"16171f3c-e0d0-4205-ab9b-a07b78ae2dea\"",
        "id": "/subscriptions/5572e0b2-83b3-4adc-9da4-15bcc2b80c0e/resourceGroups/test-jp/providers/Microsoft.Network/networkSecurityGroups/testjp-cfog-nsg/securityRules/allow-http-https-from-office",
        "name": "allow-http-https-from-office",
        "priority": 1010,
        "protocol": "TCP",
        "provisioningState": "Succeeded",
        "resourceGroup": "test-jp",
        "sourceAddressPrefix": "xxx.xxx.xxx.xxx",
        "sourceAddressPrefixes": [],
        "sourceApplicationSecurityGroups": null,
        "sourcePortRange": "*",
        "sourcePortRanges": []
      }
`
 NetworkSecurityRule.destinationPortRange() below returns only last item: 8553

`NetworkSecurityGroups nsgSvc = azure.networkSecurityGroups();
        PagedList<NetworkSecurityGroup> networkSecurityGroups = nsgSvc.listByResourceGroup("test-jp");
        List<NetworkSecurityGroup> relevantGroups = new LinkedList<>();
        networkSecurityGroups.forEach(networkSecurityGroup -> {
            Map<String, NetworkSecurityRule> ruleMap = networkSecurityGroup.securityRules();
            Holder<NetworkSecurityRule> oldRuleHolder= new Holder<>(null);
            AtomicBoolean foundNew = new AtomicBoolean(false);
            ruleMap.forEach((name, rule)->{
                String s = rule.sourceAddressPrefix();
                if(s.contains(oldIp)){
                    oldRuleHolder.value = rule;
                    System.out.println("-----------------------------------");
                    System.out.println(rule.destinationPortRange());
                } else if(s.contains(newIp)){
                    foundNew.set(true);
                }
            });
        });
`

**Comment by ChenTanyi** [comment]
@alexz75 You should not use `rule.destinationPortRange()`, you should use `rule.destinationPortRanges()` instead.

**Comment by yaohaizh** [comment]
Close this issue now.  @alexz75 feel free to re-open this issue if @ChenTanyi 's answer doesn't resolve your problem. Thanks.
