### ISSUE TITLE
azure-cosmos-spark Reademe issue

### ISSUE THREAD

**Issue by Melanie-Ma** [Azure/azure-sdk-for-java#21047]
1.
Section [Link](https://github.com/Azure/azure-sdk-for-java/tree/master/sdk/cosmos/azure-cosmos-spark_3-1_2-12#download
):
![image](https://user-images.githubusercontent.com/64007802/116518345-b06e9d00-a902-11eb-8d9c-29cd76080d39.png)
Reason:
Wrong link
Suggestion:
Change the link to https://search.maven.org/search?q=g:com.azure.cosmos.spark

@jongio, for notification

**Comment by v-xuto** [comment]
Close this issue, due to PR https://github.com/Azure/azure-sdk-for-java/pull/21986 merged.
