### ISSUE TITLE
how to get all tag(azure) list by java api

### ISSUE THREAD

**Issue by tangyiling6205** [Azure/azure-sdk-for-java#21049]
how to get all tag(azure，name and value) list by java api,If not, is there a way to get it from the URL

**Comment by tangyiling6205** [comment]
AccountBean account=getGlobleAccount();
		ResourceManager resourceManager = null;
		AzureTokenCredentials creds = new ApplicationTokenCredentials(
				account.getAccesskeyid(),
				account.getAccount(),
				account.getAccesskeysecret(),
				AzureApi.ENVIRONMENT.valueOf(account.getRegion().replace("-", "_")).getEnv());
		ResourceManager.Authenticated resourceManagerAuthenticated = ResourceManager
				.authenticate(creds);
		resourceManager=resourceManagerAuthenticated.withSubscription(account.getAccountid());
		PagedList<TagDetailsInner> tagDetailsInner=resourceManager.inner().tagOperations().list();
		tagDetailsInner.forEach(e->{
			System.out.println(e.tagName()+"="+e.values());
		});

**Comment by tangyiling6205** [comment]
It's ok?

**Comment by joshfree** [comment]
@yungezz could you please help route?

**Comment by yungezz** [comment]
add @weidongxu-microsoft to help on this. thanks

**Comment by weidongxu-microsoft** [comment]
@tangyiling6205 

Yes, that should do.
