### ISSUE TITLE
Add integration tests about SSL on azure-security-keyvault-jca

### ISSUE THREAD

**Issue by yiliuTo** [Azure/azure-sdk-for-java#21040]
This IT should include:
 - a server side app which has a self-signed certificate stored in Azure Key Vault
 - use a restclient to visit the app and check if succeed.

**Comment by chenrujun** [comment]
Closing this issue because we already have https://github.com/Azure/azure-sdk-for-java/blob/azure-security-keyvault-jca_1.0.0-beta.7/sdk/keyvault/azure-security-test-keyvault-jca/src/test/java/com/azure/security/keyvault/jca/ServerSocketTest.java
