### ISSUE TITLE
Form Recognizer Sample issue

### ISSUE THREAD

**Issue by Melanie-Ma** [Azure/azure-sdk-for-java#21046]
1.
Section [Link](https://github.com/Azure/azure-sdk-for-java/blob/master/sdk/formrecognizer/azure-ai-formrecognizer/src/samples/java/com/azure/ai/formrecognizer/FormRecognizerAsyncClientJavaDocCodeSnippets.java#L269):
![image](https://user-images.githubusercontent.com/64007802/116518082-65ed2080-a902-11eb-81a2-d51ec92184d6.png)
Reason:
Wrong content type
Suggestion:
Change to `FormContentType.IMAGE_JPEG`

@jongio, for notification

**Comment by samvaity** [comment]
Closed with #21987
