### ISSUE TITLE
Spring cloud Readme issue

### ISSUE THREAD

**Issue by Melanie-Ma** [Azure/azure-sdk-for-java#21045]
1.
Section [Link](https://github.com/Azure/azure-sdk-for-java/tree/spring-cloud-starter-azure-appconfiguration-config_1.3.0/sdk/appconfiguration/spring-cloud-starter-azure-appconfiguration-config#prerequisites):
![image](https://user-images.githubusercontent.com/64007802/116517855-1f97c180-a902-11eb-896b-5b76b482cb22.png)
Suggestion:
Add link for `Java Development Kit (JDK)` https://docs.microsoft.com/java/azure/jdk/?view=azure-java-stable

@jongio, for notification

**Comment by saragluna** [comment]
Thanks for pointing this out, we'll fix it.
