### ISSUE TITLE
ComputerVisionAPIImpl constructor private visibility

### ISSUE THREAD

**Issue by elarbi** [Azure/azure-sdk-for-java#2105]
Hello,

I need to instantiate ComputerVisionAPIImpl with a different baseUrl than "https://{AzureRegion}.api.cognitive.microsoft.com/vision/v1.0" I want to use v2.0
But the constructor is not accessible:

in com.microsoft.azure.cognitiveservices.vision.computervision.implementation.ComputerVisionAPIImpl.class:
```
    private ComputerVisionAPIImpl(String baseUrl, ServiceClientCredentials credentials) {
        super(baseUrl, credentials);
        this.initialize();
    }
```

Is it possible to make it public ?

**Comment by milismsft** [comment]
@elarbi Have you tried using the manager class, ComputerVisionManager, which has an overload for authenticate() that accepts user input for the baseUrl?

**Comment by praries880** [comment]
@elarbi  I am closing the issue. Do feel free to reactivate it in case the solution suggested did not work for you.
