### ISSUE TITLE
Azure Blob - How to delete directory with NEW SDK?

### ISSUE THREAD

**Issue by abhikt48** [Azure/azure-sdk-for-java#21055]
We have requirement to delete directory which have many blobs. 

Can we delete blob directory? If yes, can you please share sample code or SDK details?

**Setup (please complete the following information if applicable):**
OS: window
IDE : eclipse
Version of the Library used: `azure-storage-blob-12.10.2`

**Comment by gapra-msft** [comment]
Hi @abhikt48 

Yes, to delete a blob "directory", you need to call listBlobs with the directory name as the prefix and delete all the resulting blobs that get returned. Let me know if you need a more detailed code sample and I'm happy to share.

**Comment by abhikt48** [comment]
Hi @gapra-msft ,   Thanks for quick reply. Yes i am able to delete blob one by one.

Is It possible for you to provide feature to delete blob based on directory?  So we don't need to delete blob one by one..

**Comment by gapra-msft** [comment]
Hi @abhikt48,

I will chat with my team about this request, but one thing I will say is the SDK is meant to be for the most part a one to one mapping of the APIs provided for the service, so we may not be able to add this to the SDK.

**Comment by gapra-msft** [comment]
Hi @abhikt48 

I spoke with my team and unfortunately, we have decided not to take up this feature request as the SDK is meant to be a one to one mapping of the APIs provided for the service.
