### ISSUE TITLE
Release plans for Computer Vision API client

### ISSUE THREAD

**Issue by elarbi** [Azure/azure-sdk-for-java#2106]
Hello,

The Computer Vision Client  1.0.0-beta version available on Maven central repo has a bug that's already corrected on the github repo. The bug is in the com.microsoft.azure.cognitiveservices.vision.computervision.models.OcrResult#language field that has OcrResult type instead of String.
Could you please tell us when the current version will be available on Maven central repo  ?

The latest version on Maven central repo I could find:
https://search.maven.org/#artifactdetails%7Ccom.microsoft.azure.cognitiveservices%7Cazure-cognitiveservices-computervision%7C1.0.0-beta%7Cjar

**Comment by milismsft** [comment]
@elarbi The changes reflecting the latest state of the service are already checked in into the repo that have not been published to Maven yet. I would expect that to happen in the next couple weeks.

Meanwhile it would be great if you can clone the repo you should be able to build the library locally and use it for the time being. And please get back to us with any other issues you might find; it will be great to get those fixed before we publish the library update to Maven.

**Comment by praries880** [comment]
This is done. Closing the issue
