### ISSUE TITLE
[Feature Request] Support tuststore folders in the azure keyvault

### ISSUE THREAD

**Issue by ottfro1** [Azure/azure-sdk-for-java#21086]
https://docs.microsoft.com/en-us/java/api/overview/azure/spring-boot-starter-keyvault-certificates-readme?view=azure-java-preview#using-a-client-id-and-client-secret-1

SSLContext sslContext = SSLContexts.custom()
                                       .loadTrustMaterial(trustStore, null)
                                       .build();

We are wondering where the truststore is to come from?
Typically the trustStore consists of certificates distributed without private key in p7b or PEM
The truststore is typically not distributed in pfx/p12 format including private key.
 
In the example you use the azure keyvault containing pfx certificates as truststore. As the root and intermediate CA certificates we need in the truststore are distributed without key in p7b/pem format they can't easily be uploaed to azure keyvault because azure keyvault requires pfx/pem with a key included.

as a very stupid workaround

You can create a dummy pfx file with a dummy key and cerificate
convert pfx to pem using openssl pkcs12
convert pem to pfx using openssl pkcs12 with -certfile option to add extra root CA certificates
upload pfx to azure keyvault 

In the truststore there must be more than one certificate because from time to time root certificates are expired, revoked or for some buiness reason the server we connect to get a new server cert from a different CA. At that point it is necessary to trust both the old CA certificate and the new CA certificate during exchange to avoid downtime

When we connect to the bank we happen to know that the banks server certificate i issued by the very secure BankRootCA and we wnat to trust only the CA when connecting to the bank. we don't want to trust the CA the issued server certificates for microsoft or facebook. If the bank has a server certificate issued by microsoft CA or facebook CA then we know it is fraud.

When we connect to the not secure facebook server we must use a trustore including the non secure CA certificate that i issued facebook server certificate.

Typically client certificates are issued with 1 yera expiry time. When a client certificate is renewed we want to update the client certificate without touching the truststore.

When we update the truststore with new CA certificate or remove exiting one we want to do so without touching the client certificate.

We have multiple apps the need the same ssl client certificate and the same truststore.

[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 84301aa0-94ab-b77e-a16f-d63227160af1
* Version Independent ID: 7c32d456-fad9-96e4-0e66-8e79f5b9dbca
* Content: [Azure Key Vault JCA client library for Java](https://docs.microsoft.com/en-us/java/api/overview/azure/security-keyvault-jca-readme?view=azure-java-preview)
* Content Source: [docs-ref-services/preview/security-keyvault-jca-readme.md](https://github.com/Azure/azure-docs-sdk-java/blob/master/docs-ref-services/preview/security-keyvault-jca-readme.md)
* Service: **keyvault**
* Product: **azure**
* Technology: **azure**
* GitHub Login: @maggiepint
* Microsoft Alias: **magpint**

**Comment by joshfree** [comment]
@stliu can you please take a look?

/cc @vcolin7

**Comment by saragluna** [comment]
@chenrujun please take a look at this.

**Comment by chenrujun** [comment]
Hi, @ottfro1 , thanks for reaching out.

---
> We are wondering where the truststore is to come from?

Now the trustStrore is just `AzureKeyVault`, it contains the certs stored in the keyvault. Those certs contain private key.

---
>as a very stupid workaround

It may work. Do you mean we can write the workaround in the readme.md.

---
> In the truststore there must be more than one certificate

Do you mean we should write this into readme.md too?

---
>  If the bank has a server certificate issued by microsoft CA or facebook CA then we know it is fraud.
What's your suggestion to handle it?


---
> When we connect to the not secure facebook server we must use a trustore including the non secure CA certificate that i issued facebook server certificate.
We already have it: https://github.com/Azure/azure-sdk-for-java/blob/98b7105c00f454a124945dd15318e21b617f4273/sdk/keyvault/azure-security-keyvault-jca/src/main/java/com/azure/security/keyvault/jca/KeyVaultKeyStore.java#L37


---
> Typically client certificates are issued with 1 yera expiry time. When a client certificate is renewed we want to update the client certificate without touching the truststore.

Now we are working on it: https://github.com/Azure/azure-sdk-for-java/pull/20765

And PR is welcome to explain your purpose.

**Comment by ottfro1** [comment]
In the azure keyvault there is no possibility to upload p7b (or pem without key) files unless converted to pfx.
Converting root ca certificates to pfx is the wrong thing as we haven't got the private key for them - pfx is usually used for storing the private key together with it's certificate and the intermediate and root ca. If storing certificates without key you don't use pfx but use p7b.

I'd like to have the possibility to create tuststore folders in the azure keyvault. 
In my case I'd like to have folders
folder truststoreTrustedCAs (default trust store similar to cacerts file in jre/jdk) used by default for general purpose
folder truststoreSecureBankCA (used when connecting to the bank)
folder truststoreMicrosoftFacebook (used when connecting to Microsoft/Facebook)

The root ca certificates are no secrets but it is very important which certificates are placed in a truststore.

When you view the certificate in the azure portal you would like to see all the properties , serial number, cn, start and end dates, and more. You can just view fingerprint which makes it hard to maintain and monitor.

In the java app service under TLS settings in the azure portal you have a tab where you may upload p7b but all the certificates end up in one single folder and you can just see the fingerprint and no other information making it hard to maintain, you would like to see serialnumber, cn, start and endtime and the rest of the information. From java code you have to load certifictes based on fingerprint which is difficult. You would like to upload the ceritifcates to a JKS files stored in the file system. That way it would be easy to load a jks file from java code. For the same reason you would like to have multiple JKS files with different content truststoreTrustedCAs.jks , truststoreSecureBankCA.jks and truststoreMicrosoftFacebook.jks so on. The GUI in portal should allow displaying the contents of the JKS.

When viewing the pfx file in the azure portal you want to view what is inside the pfx, the key with informatioin about it, is it RSA or something else, key length and more + the certificate and intermediate and root and others. Having to download the pfx to investigate it isn't user friendly.

I'm mostly interested in verifying that we are using the software and azure keyvault in the way Microsoft intended to. We don't want to build som strange workaround if there already is a viable solution. If a new team memeber is onboarded the solution should be self-explanatory. If we build a custom logic for loading a keystore/truststore it'll be hard to understand and maintain. I thought maybe we are missing some of the basics regarding how to handle truststore.

**Comment by chenrujun** [comment]
Closing this issue because no response from customer for a long time.
