### ISSUE TITLE
Using KeyVault Certificates and Secrets with Spring Cloud Gateway

### ISSUE THREAD

**Issue by jpd1** [Azure/azure-sdk-for-java#21088]
**Query/Question**

Within our Spring Cloud Gateway project we use Azure Key Vault Certificates.

`implementation("com.azure.spring:azure-spring-boot-starter-keyvault-certificates:3.0.0-beta.6")`

We configure the following to use outbound SSL on the gateway.

`azure.keyvault.jca.overrideTrustManagerFactory=true` 

The gateway can talk to the microservices without any problems. If we add key vault secrets to the project.

`implementation("com.azure.spring:azure-spring-boot-starter-keyvault-secrets:3.4.0")`

And configure:

`azure.Keyvault.enabled:true`

The KeyVaultTrustManager is not loaded, and the configuration overrideTrustManagerFactory does not apply. This breaks the outbound SSL and the gateway can no longer talk to the microservices.

Is there a specific configuration or code that we should be applying when we want to use both Key Vault secrets and certificates with Spring Cloud Gateway?

***Why is this not a Bug or a feature Request?***
Could be either, or maybe there is something that's not clear in the documentation.

**Setup (please complete the following information if applicable):**
 - Spring Cloud Gateway 3.0.2
 - Key Vault Secrets 3.4.0
 - Key Vault Certificates 3.0.0-beta.6

 
 **Information Checklist**
 Kindly make sure that you have added all the following information above and checkoff the required fields otherwise we will treat the issuer as an incomplete report
- [X] Query Added
- [X] Setup information Added

**Comment by jpd1** [comment]
It seems this is required to use both certificates and secrets on the gateway with outbound SSL configured - https://github.com/Azure-Samples/spring-boot-secure-communications-using-end-to-end-tls-ssl/blob/main/gateway/src/main/java/com/secure/gateway/httpclient/WebClientConfig.java

Should this be mentioned within the documentation as it wasn't clear?

**Comment by joshfree** [comment]
@stliu could you take a look?

/cc @vcolin7

**Comment by saragluna** [comment]
@chenrujun please take a look at this issue.

**Comment by chenrujun** [comment]
Hi, @jpd1 , 

Thank you for reaching out.

>It seems this is required to use both certificates and secrets on the gateway with outbound SSL configured -> https://github.com/Azure-Samples/spring-boot-secure-communications-using-end-to-end-tls-ssl/blob/main/gateway/src/main/java/com/secure/gateway/httpclient/WebClientConfig.java

Sorry that I can't understand you clearly.

> Should this be mentioned within the documentation as it wasn't clear?

Could you please help to create a PR?

**Comment by jpd1** [comment]
Thanks for the reply. I wasn't too clear in describing the original issue. Unfortunately, I'm short of time to work on a PR at the moment. This is the steps I went through.


* Created a new Spring Cloud Gateway project.
* Added Key Vault certificates dependency into the project.
`implementation("com.azure.spring:azure-spring-boot-starter-keyvault-certificates:3.0.0-beta.6")`
* Configured the following within the project to enable outbound SSL from gateway to microservices.
```
azure:
  keyvault:
    uri: ${KEY_VAULT_URI}
    jca:
      overrideTrustManagerFactory: true
      disableHostnameVerification: true

server:
  ssl:
    enabled: true
    key-alias: ${SERVER_SSL_CERTIFICATE_NAME}
    key-store-type: AzureKeyVault

```
This works ok.
* Added the secrets dependency into the project to download Key Vault secrets.
`implementation("com.azure.spring:azure-spring-boot-starter-keyvault-secrets")`
* Set azure.keyvault.enabled = true within the project.
```
azure:
  keyvault:
    enabled: true
    uri: ${KEY_VAULT_URI}
    jca:
      overrideTrustManagerFactory: true
      disableHostnameVerification: true
```

The outbound SSL communications to the microservices fails, not trusting the certificates.
* Copy/pasted webclient code from here -> https://github.com/Azure-Samples/spring-boot-secure-communications-using-end-to-end-tls-ssl/blob/main/gateway/src/main/java/com/secure/gateway/httpclient/WebClientConfig.java into the project, the outbound SSL communications work ok.

It seems there is clash when trying to use both certificates and secrets together with Spring Cloud Gateway within one project. Checking in debug mode, I don't see KeyVaultTrustManagerFactory being called. It is called if I just use certificates starter only.

**Comment by chenrujun** [comment]
@jpd1 , thank you for your detailed description. I'll try to reproduce this issue and investigate it.

**Comment by yiliuTo** [comment]
Hi @jpd1 , I failed to reproduce the bug you reported that when adding azure-spring-boot-starter-keyvault-secrets, KeyVaultTrustManagerFactory is not called or the SSL doesn't work. Here is my [project](https://github.com/yiliuTo/spring-boot-secure-communications-using-end-to-end-tls-ssl/tree/enable-gateway-with-kv-secret-starter) using the sample you mentioned, and I updated the pom.xml with the library and version as you used in this [commit](https://github.com/yiliuTo/spring-boot-secure-communications-using-end-to-end-tls-ssl/commit/50b4f8e5a7909af05ecd6c8f9f6f52726ad60252).

Could you provide a sample project to help me reproduce your issue?

**Comment by chenrujun** [comment]
Closing this issue because there is no response for a long time.
