### ISSUE TITLE
[FEATURE REQ] Expose refresh token for AuthorizationCodeCredential

### ISSUE THREAD

**Issue by ivanmaria** [Azure/azure-sdk-for-java#21104]
**Is your feature request related to a problem? Please describe.**
We are trying to use AuthorizationCodeCredential. However, the refresh token is not exposed nor we could find any way to reinitialize the TokenCredential with refresh token / cache. Our current system architecture is stateless with multiple instances running under a load balancer. Due to which, we cannot maintain the TokenCredential in a session and need an option to pass the token to and fro.

**Describe the solution you'd like**
Solution 1: Expose refresh token and an implementation to initialize TokenCredential with refresh token.
Solution 2: Expose a light-weight serializable token cache that can be used to reinitialize a TokenCredential(Even after the application restarts / multiple instance running under a load balancer.)

**Describe alternatives you've considered**
Currently we are using custom implementation that fetches the access token using a refresh token.

**Additional context**
We are trying to upgrade GraphSDK Java to v3 where it is recommended to use Azure Identity instead of custom IAuthenticationProvider implementation.

**Information Checklist**
Kindly make sure that you have added all the following information above and checkoff the required fields otherwise we will treat the issuer as an incomplete report
- [x] Description Added
- [x] Expected solution specified

**Comment by g2vinay** [comment]
@ivanmaria 
The Identity SDK uses MSAL underneath. 
The MSAL library doesn't expose the refresh tokens and doesn't support rehydrating its clients from user's refresh token.

I've opened an issue for this on MSAL library, we can track this from there. 
https://github.com/AzureAD/microsoft-authentication-library-for-java/issues/436
