### ISSUE TITLE
[Feature request] Enable property azure.activedirectory.redirect-uri-template

### ISSUE THREAD

**Issue by blacelle** [Azure/azure-sdk-for-java#21116]
**Query/Question**
Why is `com.azure.spring.autoconfigure.aad.AADAuthenticationProperties.redirectUriTemplate `being deprecated?

The code states ():

```
    /**
     * @deprecated Now the redirect-url-template is not configurable.
     * <p>
     * Redirect URI always equal to "{baseUrl}/login/oauth2/code/".
     * </p>
     * <p>
     * User should set "Redirect URI" to "{baseUrl}/login/oauth2/code/" in Azure Portal.
     * </p>
     *
     * @see <a href="https://github.com/Azure/azure-sdk-for-java/tree/c27ee4421309cec8598462b419e035cf091429da/sdk/spring/azure-spring-boot-starter-active-directory#accessing-a-web-application">aad-starter readme.</a>
     * @see com.azure.spring.aad.webapp.AADWebAppConfiguration#clientRegistrationRepository()
     */
    @Deprecated
    private String redirectUriTemplate;
```

which looks quite arbitrary.

In our case, we rely on this parameter to change the redirecUriTemplate to:

```
azure.activedirectory:
  redirect-uri-template: '{baseUrl}/admin/login/oauth2/code/{registrationId}'
```

```
spring.security.oauth2.client.registration.azure:
  redirect-uri: '{baseUrl}/admin/login/oauth2/code/{registrationId}'
```

as we want to hide all these routes behind a `/admin/**` prefix.

As we already hack over AADWebAppConfiguration for other reasons (https://github.com/Azure/azure-sdk-for-java/issues/19816), we had to also hack the following in this class:

```
	private ClientRegistration.Builder createClientBuilder(String id) {
		ClientRegistration.Builder result = ClientRegistration.withRegistrationId(id);
		result.authorizationGrantType(AuthorizationGrantType.AUTHORIZATION_CODE);

		// HACK MiTrust
		// Unclear why it is deprecated in com.azure.spring.autoconfigure.aad.AADAuthenticationProperties.redirectUriTemplate
		if (Strings.isNullOrEmpty(properties.getRedirectUriTemplate())) {
			result.redirectUriTemplate("{baseUrl}/login/oauth2/code/");
		} else {
			result.redirectUriTemplate(properties.getRedirectUriTemplate());
		}

                 ...
```

**Comment by joshfree** [comment]
@stliu could you follow up with @blacelle 's question?

**Comment by chenrujun** [comment]
@blacelle , thanks for reaching out.

Originally, we thought that this property does not need to be configured in normal case.
Since you have this feature request, we will implement it.
And @han-gao will create PR soon.

**Comment by han-gao** [comment]
Hi, @blacelle and @chenrujun  

I have created a [pr](https://github.com/Azure/azure-sdk-for-java/pull/21249) to support it in aad stater, and add the feature description in the aad stater README file.
