### ISSUE TITLE
[BUG] Azure Cosmos DB Java SDK v4

### ISSUE THREAD

**Issue by steinrr** [Azure/azure-sdk-for-java#21130]
**Describe the bug**
Spring boot application using the Java SDK v4. When doing a database operations, warnings are output.

E.g. operation:

```
CosmosPagedIterable<DocumentMetadata> documentMetadataIterable = 
				container.queryItems("SELECT * FROM c", queryOptions, DocumentMetadata.class);

```
If I use Object class instead of my own DocumentMetadata class, there are no warnings.

***Exception or Stack Trace***
```
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by com.fasterxml.jackson.module.afterburner.util.MyClassLoader (file:/Users/steinrr/.m2/repository/com/fasterxml/jackson/module/jackson-module-afterburner/2.11.4/jackson-module-afterburner-2.11.4.jar) to method java.lang.ClassLoader.findLoadedClass(java.lang.String)
WARNING: Please consider reporting this to the maintainers of com.fasterxml.jackson.module.afterburner.util.MyClassLoader
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release
```
**To Reproduce**
1. Implement application to query Cosmos DB and provide own model class

**Expected behavior**
No warnings should be output.

**Setup (please complete the following information):**
 - OS: macOS Big Sur 11.2.3
 - JDK:

```
openjdk version "11.0.10" 2021-01-19
OpenJDK Runtime Environment (build 11.0.10+9)
OpenJDK 64-Bit Server VM (build 11.0.10+9, mixed mode)

```
 - Version of the Library used
		
```
<dependency>
   <groupId>com.azure</groupId>
   <artifactId>azure-cosmos</artifactId>
   <version>4.14.0</version>
</dependency>
```

**Information Checklist**
Kindly make sure that you have added all the following information above and checkoff the required fields otherwise we will treat the issuer as an incomplete report
- [X] Bug Description Added
- [X] Repro Steps Added
- [X] Setup information Added

**Comment by joshfree** [comment]
@kushagraThapar could you please take a look

**Comment by kushagraThapar** [comment]
@steinrr - this is not a Cosmos db issue, rather jackson issue, please subscribe to this issue for more information, I am closing this one as it is a duplicate - https://github.com/Azure/azure-sdk-for-java/issues/14271

**Comment by steinrr** [comment]
I would consider this a Cosmos SDK issue even if it is an Jackson issue. The Afterburner module of Jackson is outdates, and should probably be replaced in the Cosmos SDK by use of its replacement Blackbird. See this: https://cowtowncoder.medium.com/jackson-2-12-features-eee9456fec75
