### ISSUE TITLE
[BUG] KeyVaultHealthIndicator is wrong

### ISSUE THREAD

**Issue by bilak** [Azure/azure-sdk-for-java#21132]
**Describe the bug**
[KeyVaultHealthIndicator](https://github.com/Azure/azure-sdk-for-java/blob/026664ea871586e681ab674e0332b6cc2352c655/sdk/spring/azure-spring-boot/src/main/java/com/azure/spring/keyvault/KeyVaultHealthIndicator.java) is wrong. It should check whether there is at least on of  `KeyVaultPropertySource` and then based on them report `UP` or `DOWN`.
If there is no `KeyVaultPropertySource` status should be `UNKNOWN`.

**Comment by joshfree** [comment]
@chenrujun could you please take a look?

**Comment by chenrujun** [comment]
Hi, @han-gao , please help to fix this.
