### ISSUE TITLE
[DOC] Add runtime exception Javadocs to our public facing API

### ISSUE THREAD

**Issue by conniey** [Azure/azure-sdk-for-java#21142]
Add runtime exceptions like AmqpExceptions to our public-facing API for Service Bus

**Comment by ZejiaJiang** [comment]
Hi @conniey @anuchandy @ki1729 ,

I'd like to confirm that:
1. There may be several `AmqpException` throw out in a public API, for example, `sendMessages(Iterable<ServiceBusMessage> messages)` messages can reach the max size of message batch, get link from a disposed session, create session timeout, they all can throw an `AmqpException`. How to write these exception on the JavaDoc?
2.  Do I need to put other runtime exception in JavaDoc? such as, the dispatcher invoke some task, if the dispatcher is closed, it will throw a runtime exception.

**Comment by conniey** [comment]
@ZejiaJiang Yes. Those are the types of runtime exceptions we want to document. If we try to schedule work on the dispatcher and it throws, we should document that as well.
