### ISSUE TITLE
[QUERY] Why is Directory.Read.All required? Spring AAD libraries

### ISSUE THREAD

**Issue by aaronkorver** [Azure/azure-sdk-for-java#21162]
**Query/Question**
This is going to be similar to https://github.com/Azure/azure-sdk-for-java/issues/19712 but I feel that wasn't fully answered.

In this code here, if allowed groups (now groupnames/groupIds) are set it places the scopes to be `User.Read` and `Directory.Read.All`

https://github.com/Azure/azure-sdk-for-java/blob/2abb908b586c1be644184414969886788a315978/sdk/spring/azure-spring-boot/src/main/java/com/azure/spring/aad/webapp/AADWebAppConfiguration.java#L124-L128

However, in the code 

https://github.com/Azure/azure-sdk-for-java/blob/2abb908b586c1be644184414969886788a315978/sdk/spring/azure-spring-boot/src/main/java/com/azure/spring/aad/webapp/AADOAuth2UserService.java#L118-L121

it goes and gets the groups for the user.  This only needs `User.Read` to get those groups (AFAIK).  I cannot find any place directly in the code that would be requiring `Directory.Read.All` scope to function.

So, the question is simply this

## Why is `Directory.Read.All` required?

***Why is this not a Bug or a feature Request?***
A clear explanation of why is this not a bug or a feature request?

**Setup (please complete the following information if applicable):**
 - IDE : [e.g. IntelliJ]
 - Version of the Library used  -- v3.4.0
 
 **Information Checklist**
 Kindly make sure that you have added all the following information above and checkoff the required fields otherwise we will treat the issuer as an incomplete report
- [ x] Query Added
- [ x] Setup information Added

**Comment by joshfree** [comment]
@stliu could you please take a look?

**Comment by chenrujun** [comment]
Hi, @aaronkorver , thanks for reaching out.

> Why is Directory.Read.All required?

`User.Read` is not enough to get group names.

1. User.Read: Allows users to sign-in to the app, and allows the app to read the profile of signed-in users. It also allows the app to read basic company information of signed-in users.
2. Directory.Read.All: Allows the app to read data in your organization's directory, such as users, groups and apps. Note: Users may consent to applications that require this permission if the application is registered in their own organization’s tenant.

Refs: https://docs.microsoft.com/en-us/graph/permissions-reference

**Comment by aaronkorver** [comment]
Hi @chenrujun 

Thanks for the explanation.  

I did a quick test and created an app registration with just the User.Read.  You can access https://graph.microsoft.com/v1.0/me/memberOf with just the User.Read scope.  

However, as you can see only the IDs come back, none of the other information.  With the change to allow the groupIDs this would be ok (though a bit annoying)
```
{
  "@odata.context": "https://graph.microsoft.com/v1.0/$metadata#directoryObjects",
  "value": [
    {
      "@odata.type": "#microsoft.graph.group",
      "id": "cfd30a92-3b9d-4ae0-a943-64000446be93",
      "deletedDateTime": null,
      "classification": null,
      "createdDateTime": null,
      "creationOptions": [],
      "description": null,
      "displayName": null,
      "expirationDateTime": null,
      "groupTypes": [],
      "isAssignableToRole": null,
      "mail": null,
      "mailEnabled": null,
      "mailNickname": null,
      "membershipRule": null,
      "membershipRuleProcessingState": null,
      "onPremisesDomainName": null,
      "onPremisesLastSyncDateTime": null,
      "onPremisesNetBiosName": null,
      "onPremisesSamAccountName": null,
      "onPremisesSecurityIdentifier": null,
      "onPremisesSyncEnabled": null,
      "preferredDataLocation": null,
      "preferredLanguage": null,
      "proxyAddresses": [],
      "renewedDateTime": null,
      "resourceBehaviorOptions": [],
      "resourceProvisioningOptions": [],
      "securityEnabled": null,
      "securityIdentifier": null,
      "theme": null,
      "visibility": null,
      "onPremisesProvisioningErrors": []
    }, ...
```

Are group names needed?  I'm just wondering if the scope should be dynamic depending of if IDs vs group names are being asked for.  Also if no groups are being mapped to roles, then do they need the Directory scope?

**Comment by chenrujun** [comment]
Hi, @aaronkorver .
Thank you very much for your investigating.
I created a new issue: https://github.com/Azure/azure-sdk-for-java/issues/21284
Let's discuss in that issue.

**Comment by chenrujun** [comment]
Closing this issue because we created the new issue: https://github.com/Azure/azure-sdk-for-java/issues/21284
