### ISSUE TITLE
[QUESTION] Azure Table Library setTop(Integer top) method returns all entities from the table

### ISSUE THREAD

**Issue by NikGolovan** [Azure/azure-sdk-for-java#21202]
**Query/Question**
Good afternoon, 

I am currently using azure-data-tables library in Java 11 and trying to limit the number of returned entities using `setTop(Integer top)` method of `ListEntitiesOptions` class. Here is the sample code: 

`ListEntitiesOptions op = new ListEntitiesOptions().setTop(2);`
`PagedIterable<TableEntity> results = tableClient.listEntities(op);`

When I loop through `results` I always get all existing entities from the table despite the fact that an option with a top limit was applied.  
Could you please advice if any additional step should be applied in order to retrieve Nth number of entities from given table. 

Best regards, 
Nik

***Why is this not a Bug or a feature Request?***
Checking on other examples provided in C# and the docs it seems like this feature should work.

**Setup (please complete the following information if applicable):**
 - OS: Windows
 - IDE : IntelliJ
 - Version: com.azure: azure-data-tables 12.0.0-beta.6
 
 **Information Checklist**
 Kindly make sure that you have added all the following information above and checkoff the required fields otherwise we will treat the issuer as an incomplete report
- [X] Query Added
- [X] Setup information Added

**Comment by joshfree** [comment]
@NikGolovan thank you for reporting this issue.  @vcolin7 please take a look.

**Comment by smil2k** [comment]
This is a bug in the azure table storage itself. $top is sent, but not checked by the service at all. You can check it out using the storage explorer using advanced filters.

The same goes to GT LT with strings eg. propertyWithTime gt '2021-05-06' does not return any records (even if there are strings like 2021-05-09 and 2021-05-02 present in that property, it still shows them all. 

It seems that the filter is a mess at Azure Table Storage...

**Comment by vcolin7** [comment]
Hi @NikGolovan, first of all let me say I'm sorry for the late response.

In the context of the Tables service, unlike Blob Storage, the `top` parameter affects how many entities or tables are returned in each page, instead of the total entities/tables in all pages.

If you want to only get the top X results, you can get the first page returned via a `list` operation like in the following example:

```java
TableClient tableClient = new TableClientBuilder()
    .connectionString(connectionString)
    .tableName(tableName)
    .buildClient();
ListEntitiesOptions options = new ListEntitiesOptions().setTop(2);

PagedIterable<TableEntity> entitiesPagedIterable = tableClient.listEntities(options, null, null);

Iterator<PagedResponse<TableEntity>> iterator = entitiesPagedIterable
    .iterableByPage() // This returns an iterable that you can use with a forEach loop with to handle each page individually.
    .iterator();

if (iterator.hasNext()) {
    // This list will contain only the first 2 elements returned by the service.
    List<TableEntity> entities = iterator.next().getValue();
}
```

Please tag me in case you have any more questions or if you encounter any issue :)

**Comment by saradev1927** [comment]
Hi @vcolin7 , it's possible to sort from a custom field in input?

**Comment by vcolin7** [comment]
Hi @saradev1927, I don't recall from the top of my head but I'll check with the team and get back to you.

/cc @jairmyree
