### ISSUE TITLE
[QUERY] Confusing/undocumented multiple dependency name/versions/variants

### ISSUE THREAD

**Issue by JV-TMCZ** [Azure/azure-sdk-for-java#21201]
**Query/Question**
Different sources point to different maven dependencies/libraries. It is unclear which dependency to use. Could you please write a blog which explains and lists all possible variants and describe what/why/where/who(maintainer: microsoft vs. spring)/when(active/deprecated)/... 
Ideally, link such overview information to each project docs/homepage and/or make it google indexed... 

Thank you. 
Unfortunatelly, the very same/similar situation is also with e.g. cosmosdb support, (A)AD support, ... 

Microsoft documentation for Spring support to azure storage blobs:
[docs](https://docs.microsoft.com/en-us/azure/developer/java/spring-framework/configure-spring-boot-starter-java-app-with-azure-storage) mentions: 
```
<dependency>
   <groupId>com.microsoft.azure</groupId>
   <artifactId>spring-starter-azure-storage</artifactId>
   <version>1.2.8</version>
</dependency>
```
page links to [github](https://github.com/Azure/azure-sdk-for-java/tree/azure-spring-boot-starter-storage_3.4.0/sdk/spring/azure-spring-boot-samples/azure-spring-boot-sample-storage-resource)
```
<dependency>
    <groupId>com.azure.spring</groupId>
    <artifactId>azure-spring-boot-starter-storage</artifactId>
</dependency>
```

but it is different that azure storage SDK
 ```
  <dependency>
            <groupId>com.microsoft.azure</groupId>
            <artifactId>azure-storage</artifactId>
            <version>8.4.0</version>
        </dependency>
```

or storage blob SDK
[storage SDK](https://docs.microsoft.com/en-us/java/api/overview/azure/storage-blob-readme?view=azure-java-stable)
```
<dependency>
    <groupId>com.azure</groupId>
    <artifactId>azure-storage-blob</artifactId>
    <version>12.11.0</version>
</dependency>
```

spring blog...
[spring blog](https://spring.io/blog/2019/01/17/bootiful-azure-object-storage-service-5-6)
`com.microsoft.azure: azure-storage-spring-boot-starter`

**Comment by joshfree** [comment]
Thanks for filing this @JV-TMCZ.  @alzimmermsft is actively working on this right now.  @alzimmermsft could you share an update?

**Comment by alzimmermsft** [comment]
Thank you for filing this issue @JV-TMCZ.

From your perspective are you looking for a chart with the following information.

**Context**

For this example we are looking at `azure-cosmos` `4.14.0`.

**Chart**

Azure SDK Compatibility

| Library | Version |
| ------- | -------- |
| azure-core | 1.15.0 |
| azure-core-http-netty | 1.9.1 |
| azure-storage-blob | 12.11.0 |
| azure-identity | 1.2.5 |
| azure-security-keyvault-keys | 4.2.7 |

**Comment by JV-TMCZ** [comment]
**Actually, I am looking for better documentation...** 

I am confused that different docs links to different maven depenencies and different code approach and level of abstractions. 
As a developer I need a information which dependency/project/approach to use in what situation. So, I need a explanation what each library provides and what is main purposes and pros/cons. When a project wraps another project (SDK) it needs to be explained why it is done and what benefits it brings. And especially how to use it. So developer could choose the best library... 

E.g.: when a developer wants to add a azure storage blob functionality to java spring boot project... and there are more dependencies which contains words "spring" and "azure" ... developer does not know which to choose. 

E.G.: 
        <dependency>
            <groupId>com.azure.spring</groupId>
            <artifactId>azure-spring-boot-starter-storage</artifactId>
            <version>3.4.0</version>
        </dependency>
this project documentation does not said a single word about Spring boot autoconfiguration feature. Neither that storageServiceClientBuilder is autoconfigure and ready to use. Instead a documentation shows how to do the same manually. Which make no sense in spring boot context (at least most of the time).
