### ISSUE TITLE
Why I can not find the azure-spring-boot-starter-active-directory of version '3.5.0-beta.1' in MVNrepository

### ISSUE THREAD

**Issue by Xiaoxin4396** [Azure/azure-sdk-for-java#21200]
such as tittle.
I am practicing 'azure-sdk-for-java/sdk/spring/azure-spring-boot-samples/azure-spring-boot-sample-active-directory-resource-server' , the [pom](https://github.com/Azure/azure-sdk-for-java/blob/master/sdk/spring/azure-spring-boot-samples/azure-spring-boot-sample-active-directory-resource-server/pom.xml) shows that there is a dependency which is azure-spring-boot-starter-active-directory of version '3.5.0-beta.1' , but I can not find this version in [MVNrepository](https://mvnrepository.com/artifact/com.azure.spring/azure-spring-boot-starter-active-directory) ,beside , I can not import com.azure.spring.aad.webapi.AADResourceServerWebSecurityConfigurerAdapter in [AADOAuth2ResourceServerSecurityConfig.java](https://github.com/Azure/azure-sdk-for-java/blob/master/sdk/spring/azure-spring-boot-samples/azure-spring-boot-sample-active-directory-resource-server/src/main/java/com/azure/spring/sample/aad/security/AADOAuth2ResourceServerSecurityConfig.java) . I guess the reason is I got the wrong version . HELP! Thanks very much.

**Comment by joshfree** [comment]
@stliu could you please follow up?

**Comment by chenrujun** [comment]
Hi, @Xiaoxin4396 , thanks for reaching out.

Please use released version instead of master branch.

Refs: https://github.com/Azure/azure-sdk-for-java/blob/master/sdk/spring/ENVIRONMENT_CHECKLIST.md#find-the-release-tag

**Comment by Xiaoxin4396** [comment]
Anyway, it's working after I change some parameter, I need to read documentations carefully, thank you all.
