### ISSUE TITLE
[BUG] Server-side post-trigger script gets null from response body when creating item with CosmosItemRequestOptions.SetPostTriggerInclude

### ISSUE THREAD

**Issue by zxm5010** [Azure/azure-sdk-for-java#21224]
**Describe the bug**
I'm trying to use `CosmosItemRequestOptions.setPostTriggerInclude()` to run a post-trigger after createItem. However, I'm getting null from `context.getResponse().getBody()` in the server-side javascript trigger context

I can confirm that the createItem creates document properly when without the postTrigger set. But, not sure why server-side doesn't set the response body. The response object returned by `context.getResponse()` is an empty object somehow.

***Exception or Stack Trace***
Add the exception log and stack trace if available

**To Reproduce**
Please refer to code snippet. Create any document with the given post-trigger set. Client should receive "No created item from hooked action" exception. 

***Code Snippet***
Server-side javascript (myPostTrigger):

```
function myPostTrigger() {
  var context = getContext();
  var container = context.getCollection();
  var response = context.getResponse(); // item that was created

  var createdItem = response.getBody();

  // we are hitting this check
  if(!createdItem) throw new Error("No created item from hooked action.")
}
```
Java

```
        JsonNode jsonNode = new ObjectMapper().valueToTree(item);
        //  Create item using container
        List<String> postTriggers = new ArrayList<>();
        postTriggers.add("myPostTrigger");
        CosmosItemRequestOptions cosmosItemRequestOptions = new CosmosItemRequestOptions()
                .setPostTriggerInclude(postTriggers);
        logger.info("itemInJson : " + jsonNode.toString());
        CosmosItemResponse<JsonNode> response = cosmosDbContainer.getContainer().createItem(jsonNode, cosmosItemRequestOptions);
```
**Expected behavior**
post-trigger script should get created item from context.getResponse().getBody() 

**Screenshots**

**Setup (please complete the following information):**
 - Version of the Library used : tried 4.12.0 & 4.14.0

**Additional context**
I have exact same code using Node.js and didn't encounter this problem. And, there's no example presented in example repo, so im wondering is this had been supported yet in sdk v4? 

**Information Checklist**
Kindly make sure that you have added all the following information above and checkoff the required fields otherwise we will treat the issuer as an incomplete report
- [x] Bug Description Added
- [x] Repro Steps Added
- [x] Setup information Added

**Comment by joshfree** [comment]
@kushagraThapar could you please take a look

**Comment by zxm5010** [comment]
Quick update. I switched implementation from SDK V4 to old SDK V2 (Sync) and everything just worked intended. So, is the triggers migrated fully on V4?

**Comment by moderakh** [comment]
Thanks for reporting. we can repro this on v4. 
```java
        CosmosAsyncClient client = new CosmosClientBuilder()
            .endpoint(TestConfigurations.HOST)
            .key(TestConfigurations.MASTER_KEY)
            .buildAsyncClient();

        client.createDatabaseIfNotExists(DATABASE_NAME).block();
        CosmosContainerProperties cosmosContainerProperties = new CosmosContainerProperties(CONTAINER_NAME, "/id");
        client.getDatabase(DATABASE_NAME).createContainerIfNotExists(cosmosContainerProperties).block();

        CosmosAsyncContainer container = client.getDatabase(DATABASE_NAME).getContainer(CONTAINER_NAME);
        
        String triggerId = UUID.randomUUID().toString();
        CosmosTriggerProperties trigger = new CosmosTriggerProperties(triggerId, "function() {"
            + "  var context = getContext();"
            + "  var container = context.getCollection();"
            + "  var response = context.getResponse();"
            + "  var createdItem = response.getBody();"
//            + "  // we are hitting this check"
            + "  if(!createdItem) throw new Error(\"No created item from hooked action.\");"
            + "}");

        trigger.setTriggerOperation(TriggerOperation.CREATE);
        trigger.setTriggerType(TriggerType.POST);

        container.getScripts().createTrigger(trigger).block();

        //  Create item using container
        ObjectNode item = new ObjectMapper().createObjectNode();
        item.put("id", UUID.randomUUID().toString());

        List<String> postTriggers = new ArrayList<>();
        postTriggers.add(triggerId);
        CosmosItemRequestOptions cosmosItemRequestOptions = new CosmosItemRequestOptions()
            .setPostTriggerInclude(postTriggers);
        CosmosItemResponse<ObjectNode> response = container.createItem(item, cosmosItemRequestOptions).block();
```

**Comment by zxm5010** [comment]
Thanks for the update @moderakh! Could you suggest any solution/fix for this atm? And possible an ETA for the fix?

**Comment by moderakh** [comment]
@zxm5010 actually this is not a bug. In the V4 SDK content response on write is disabled by default see here: https://azuresdkdocs.blob.core.windows.net/$web/java/azure-cosmos/latest/com/azure/cosmos/CosmosClientBuilder.html#contentResponseOnWriteEnabled-boolean-

For Trigger to work you need to enable content-response-on-write. You can do that either at the ClientBuilder level or you can do it for the request,
https://azuresdkdocs.blob.core.windows.net/$web/java/azure-cosmos/latest/com/azure/cosmos/models/CosmosItemRequestOptions.html#setContentResponseOnWriteEnabled-java.lang.Boolean-

for example in the above code you need to change to, then it will work.
```java
        CosmosItemRequestOptions cosmosItemRequestOptions = new CosmosItemRequestOptions()
            .setPostTriggerInclude(postTriggers)
            .setContentResponseOnWriteEnabled(true);
```

**Comment by zxm5010** [comment]
Thanks @moderakh. The response is written now. 

Suggestion: please update the migration documentation https://docs.microsoft.com/en-us/azure/cosmos-db/migrate-java-v4-sdk?tabs=java-v4-async. as it seems a different default behavior comparing to old SDKs.
