### ISSUE TITLE
[FEATURE REQ] Update enum type PublicAccessType 

### ISSUE THREAD

**Issue by yangchengs** [Azure/azure-sdk-for-java#21231]
**Is your feature request related to a problem? Please describe.**
A cx reported issue.
When "Allow Blob public access" of storage account is set to "Disabled",

https://github.com/Azure/azure-sdk-for-java/blob/master/sdk/storage/azure-storage-blob/src/main/java/com/azure/storage/blob/BlobContainerClient.java

The API call to set access policy will fail due to an error "Public Access is not permitted on this storage account".

        BlobContainerClient blobContainerClient = storageClient.getBlobContainerClient(containerName);      
        blobContainerClient.setAccessPolicy(PublicAccessType.CONTAINER, Collections.singletonList(identifier));

The workaround is to set the first parameter as null:
        blobContainerClient.setAccessPolicy(null, Collections.singletonList(identifier));

**Describe the solution you'd like**
Can we update the enum type PublicAccessType by adding a value "None"
Or can we have a overload method which only accepts one parameter

**Comment by jaschrep-msft** [comment]
@yangchengs Thanks for the good feedback. Unfortunately we don't think this can be integrated in a way that avoids both breaking changes and introducing more ambiguity to the API. We'll track this work for a potential future breaking release.
