### ISSUE TITLE
Unify on createOrUpdateRoleDefinition API

### ISSUE THREAD

**Issue by heaths** [Azure/azure-sdk-for-java#21242]
This is a tracking bug for https://github.com/Azure/azure-sdk-for-python/issues/18579, on which we'll discuss and settle on any changes.

**Comment by vcolin7** [comment]
Java will use `setRoleDefinition()` and will allow for creating a `KeyVaultRoleDefinition` either with a provided name or with a randomly generated one if no value is given by a user.
