### ISSUE TITLE
[BUG] Cognitive Services - Computer Vision - Analize Image always returns error 404

### ISSUE THREAD

**Issue by parisbs** [Azure/azure-sdk-for-java#21253]
**Describe the bug**
Using the ComputerVision implementation to run analize image always returns 404: Resource not found

***Exception or Stack Trace***
E/VISION  : com.microsoft.azure.cognitiveservices.vision.computervision.models.ComputerVisionErrorResponseException: Status code 404, {"error":{"code":"404","message": "Resource not found"}}
E/VISION  : 	at java.lang.reflect.Constructor.newInstance0(Native Method)
E/VISION  : 	at java.lang.reflect.Constructor.newInstance(Constructor.java:343)
E/VISION  : 	at com.microsoft.rest.ServiceResponseBuilder.build(ServiceResponseBuilder.java:122)
E/VISION  : 	at com.microsoft.azure.AzureResponseBuilder.build(AzureResponseBuilder.java:56)
E/VISION  : 	at com.microsoft.azure.cognitiveservices.vision.computervision.implementation.ComputerVisionImpl.analyzeImageInStreamDelegate(ComputerVisionImpl.java:1732)
E/VISION  : 	at com.microsoft.azure.cognitiveservices.vision.computervision.implementation.ComputerVisionImpl.access$800(ComputerVisionImpl.java:82)
E/VISION  : 	at com.microsoft.azure.cognitiveservices.vision.computervision.implementation.ComputerVisionImpl$26.call(ComputerVisionImpl.java:1719)
E/VISION  : 	at com.microsoft.azure.cognitiveservices.vision.computervision.implementation.ComputerVisionImpl$26.call(ComputerVisionImpl.java:1715)
E/VISION  : 	at rx.internal.operators.OnSubscribeMap$MapSubscriber.onNext(OnSubscribeMap.java:69)
E/VISION  : 	at retrofit2.adapter.rxjava.CallArbiter.deliverResponse(CallArbiter.java:120)
E/VISION  : 	at retrofit2.adapter.rxjava.CallArbiter.emitResponse(CallArbiter.java:102)
E/VISION  : 	at retrofit2.adapter.rxjava.CallExecuteOnSubscribe.call(CallExecuteOnSubscribe.java:46)
E/VISION  : 	at retrofit2.adapter.rxjava.CallExecuteOnSubscribe.call(CallExecuteOnSubscribe.java:24)
E/VISION  : 	at rx.Observable.unsafeSubscribe(Observable.java:10327)
E/VISION  : 	at rx.internal.operators.OnSubscribeMap.call(OnSubscribeMap.java:48)
E/VISION  : 	at rx.internal.operators.OnSubscribeMap.call(OnSubscribeMap.java:33)
E/VISION  : 	at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:48)
E/VISION  : 	at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:30)
E/VISION  : 	at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:48)
E/VISION  : 	at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:30)
E/VISION  : 	at rx.Observable.subscribe(Observable.java:10423)
E/VISION  : 	at rx.Observable.subscribe(Observable.java:10390)
E/VISION  : 	at rx.observables.BlockingObservable.blockForSingle(BlockingObservable.java:443)
E/VISION  : 	at rx.observables.BlockingObservable.single(BlockingObservable.java:340)
E/VISION  : 	at com.microsoft.azure.cognitiveservices.vision.computervision.implementation.ComputerVisionImpl.analyzeImageInStream(ComputerVisionImpl.java:1622)

**To Reproduce**
Build a ComputerVision instance using the ComputerVisionManager and try to call analyzeImageInStream(ByteArray, AnalyzeImageInStreamOptionalParameter)

***Code Snippet***
```kotlin
val endpoint = "https://my-endpoint.cognitiveservices.azure.com/"
val apiKey = "my_32_characters_api_key_from_azure_portal"

val computerVision = ComputerVisionManager.authenticate(endpoint, apikey)
    .withEndpoint(endpoint)
    .computerVision()

val bitmap = Bitmap() // Asume real bitmap with 6928 bytes of data
// Convert bitmap to ByteArray
val byteArray = ByteArrayOutputStream().let { bos ->
    bitmap.compress(Bitmap.CompressFormat.JPEG, 100, bos)
    bos.toByteArray()
}

val imageAnalisis = computerVision.analyzeImageInStream(
    byteArray,
    AnalyzeImageInStreamOptionalParameter()
        .withLanguage("en")
        .withVisualFeatures(
            listOf(
                VisualFeatureTypes.CATEGORIES,
                VisualFeatureTypes.DESCRIPTION
            )
        )
        .withModelVersion("latest
)
```

**Expected behavior**
Computer Vision API response with code 200 and get access to the ImageAnalisis object

**Screenshots**
No apply

**Setup (please complete the following information):**
 - OS: Android 11 (29)
 - IDE : Android Studio 4.1
 - Version of the Library used: com.microsoft.azure.cognitiveservices:azure-cognitiveservices-computervision:1.0.6-beta

**Additional context**
Also tried with the endpoint "https://[any_region].api.cognitive.microsoft.com/" but doesn't work

**Information Checklist**
Kindly make sure that you have added all the following information above and checkoff the required fields otherwise we will treat the issuer as an incomplete report
- [x] Bug Description Added
- [x] Repro Steps Added
- [x] Setup information Added

**Comment by joshfree** [comment]
@anuchandy could you please take a look?

**Comment by parisbs** [comment]
Well, I already fix the issue, my discovers and the solution:

Using ComputerVisionManager.authenticate(baseUrl: String, subscriptionKey: String) the client returned a NullPointerException caused by an empty endpoint variable, that was very confusse because I was passing the endpoint as the first parameter so I tried to solve the exception adding .withEndpoint(endpoint: String) to the ComputerVisionClient returned by the ComputerVisionManager.authenticate() method. This solved the NullPointerException of the empty endpoint but causes a 404 error.  
Then I tried to use the authenticate(subscriptionKey: String) variant and pass the endpoint using withEndpoint(endpoint: String) and that solve the issue, so the final code is:

```kotlin
val endpoint = "https://[my-endpoint-prefix].cognitiveservices.azure.com/"
val apiKey = "32-characters-api-key-from-azure-portal"

val computerVision = ComputerVisionManager.authenticate(apiKey)
    .withEndpoint(endpoint)
    .computerVision()
```

Now, for the Azure team, can you explain:  
* Why is this happening?
* What is the correct usage of authenticate(baseUrl: String, subscriptionKey: String) variant?
* What is the difference between pass the endpoint on the authenticate() method and use withEndpoint()?

I suspect that by passing the endpoint in the authenticate() method we must construct the complete endpoint including the name of the service and the version to use ("https://[my-endpoint-prefix].cognitiveservices.azure.com/vision/v3.2/"), while using withEndpoint() the ComputerVisionManager automatically fills in the rest of the URL ("/vision/v3.2"). So we must use authenticate() if we want to use a specific API version and endpoint() for the latest available one, is this right?

Thanks

**Comment by anuchandy** [comment]
An alternate usage of builder addressing this is provided in the above comment.
