### ISSUE TITLE
[ACR] Incorporate API review feedback from Arch Board

### ISSUE THREAD

**Issue by annelo-msft** [Azure/azure-sdk-for-java#21278]
- [ ] Rename `GetTagProperties` to `GetTag` (or language appropriate)
- [ ] Remove `LoginServer` and `Name` properties from `ContainerRegistryClient`
- [ ] Come up with better name for `ArtifactManifestReference`
- [ ] Remove the `DeleteRepositoryResult` type, and return a success result from `DeleteRepository` operation even when a 404 is received.
- [ ] Evaluate `FullyQualifiedName` with regard to 1) what we do in other Track 2 libraries wrt to the qualified name concept and 2) what this is commonly called in the Docker/containers community.
- [ ] Replace `TagOrDigest` with `Digest`.
- [ ] Ensure functional parity of Python library with others
- [ ] Rename PATCH service methods from `Set..` to `Update..`
- [ ] Discuss parallelizing the delete sample across languages

**Comment by annelo-msft** [comment]
@pallavit, would you add Java-specific action items to this issue?

**Comment by pallavit** [comment]
The feedback has been addressed.
