### ISSUE TITLE
Redirect https://cloud.spring.io/spring-cloud-azure/ to https://spring.io/projects/spring-cloud-azure

### ISSUE THREAD

**Issue by chenrujun** [Azure/azure-sdk-for-java#21296]
Now docs in https://cloud.spring.io/spring-cloud-azure is deprecated.
We should redirect it to https://spring.io/projects/spring-cloud-azure.

**Comment by stliu** [comment]
what's the relationship about these two sites:

* https://cloud.spring.io/spring-cloud-azure
* https://spring.io/projects/spring-cloud-azure

it seems duplicated, and I also checked our friends of GCP and AWS

* https://cloud.spring.io/spring-cloud-gcp redirects to https://spring.io/projects/spring-cloud-gcp
* https://cloud.spring.io/spring-cloud-aws redirects to https://spring.io/projects/spring-cloud-aws

So, for this issue, I suggest we should follow the same rule:

* having https://cloud.spring.io/spring-cloud-azure redirect to  https://spring.io/projects/spring-cloud-azure
* keep https://spring.io/projects/spring-cloud-azure updated

@seanli1988 @chenrujun agree?

**Comment by saragluna** [comment]
Closing this issue now, the https://spring.io/projects/spring-cloud-azure is up to date and all links and content are up to date.
