### ISSUE TITLE
[BUG] create Subscription Rule with CorrelationFilter does not create respect properties 

### ISSUE THREAD

**Issue by p4p4** [Azure/azure-sdk-for-java#21299]
**Describe the bug**
I am creating a rule as follows:
```
            CorrelationRuleFilter filter = new CorrelationRuleFilter();
            filter.getProperties().put("eventType", "order.created");
            filter.getProperties().put("eventTypeVersion", 1);
            filter.setContentType(MediaType.APPLICATION_JSON_VALUE);

            adminClient.createRule(topicName, ruleName, subscriptionName, new CreateRuleOptions(filter));
            LOG.info("created filter: {}", filter);
```
Log Output:
`created filter: CorrelationRuleFilter: sys.ContentType = 'application/json' AND eventTypeVersion = '1' AND eventType = 'order.created'`

However, when I check the cloud portal, I see that only the contentType is set, the user properties are missing:
![image](https://user-images.githubusercontent.com/1523187/117784854-47f9b700-b244-11eb-8ee1-152b00895351.png)

If I retrieve the rule via getRule() API, it also only has the filter for contentType 

**Setup**
library version:
    implementation group:  'com.azure', name: 'azure-core', version: '1.15.0'
    implementation group:  'com.azure', name: 'azure-messaging-servicebus', version: '7.2.0'

**Comment by v-xuto** [comment]
@YijunXieMS The PR #22556 has been merged, can we close this issue?

**Comment by YijunXieMS** [comment]
To be released between 7/7 and 7/9
