### ISSUE TITLE
Increase cadence at which we ship azure-sdk-bom

### ISSUE THREAD

**Issue by conniey** [Azure/azure-sdk-for-java#21308]
Currently we ship the azure-sdk-bom on a quarterly basis. The Spring team ships theirs more frequently than that. It's a set-back for them to use our azure-sdk-bom.

This issue is to ensure that once all the dependencies have been taken care of, we are able to have way to ship it monthly.  Could we easily ship a bom if there is a security or hotfix that needs to be done?

Parent #21283

**Comment by joshfree** [comment]
The first monthly cadence of the azure-sdk-bom shipped September 2021 - https://search.maven.org/artifact/com.azure/azure-sdk-bom

**Comment by pallavit** [comment]
Closing this issue since we now have a good rhythm for the last few months.
