### ISSUE TITLE
Investigate creating azure-sdk-dependencies

### ISSUE THREAD

**Issue by conniey** [Azure/azure-sdk-for-java#21306]
One of the problems we have is that there are dependency conflicts between the boms shipped from Spring and our azure-sdk bom. We need a way to resolve it.

One suggestion was to create `azure-sdk-dependencies` bom that `azure-spring-cloud-dependencies` and `azure-spring-boot-bom` and our own `azure-sdk-bom` use.

## Goals

* Understand if this is feasible or not
* If so, what work items we need to do to make this successful.

## Resources
* https://www.youtube.com/watch?v=FsnY-BdgA8M
* https://www.mojohaus.org/flatten-maven-plugin/

Parent #21283

**Comment by backwind1233** [comment]
> One of the problems we have is that there are dependency conflicts between the boms shipped from Spring and our azure-sdk bom
Hi, @conniey  can you provide an simple example that have conflicts ?

**Comment by yeroc** [comment]
Seems like msal4j should be included in the scope of this?  Basing this on #37630 for example.
