### ISSUE TITLE
Investigate ways to decouple common conflicting dependencies

### ISSUE THREAD

**Issue by conniey** [Azure/azure-sdk-for-java#21307]
Common conflicts being seen currently with the Azure SDKs and Spring are in Jackson, Netty, and Reactor dependencies. Are there ways to abstract these dependencies to make them less tightly coupled in the Azure SDKs?

* Possibly expose an interface that we can plug Jackson or something else in so we don't directly reference the dependency.

## Goals

* Understand if it is possible to create an abstraction or other for our dependencies:
    * Jackson
    * Netty
    * Reactor
* If it is, create work items for them. (implementation can be done after.)

Related #21283, #20998

**Comment by stliu** [comment]
@samvaity any update on this ?
