### ISSUE TITLE
[FEATURE REQ] Cosmos Container id field type UUID

### ISSUE THREAD

**Issue by JV-TMCZ** [Azure/azure-sdk-for-java#21335]
Container id field currently supports only types: String, int and long. But internally it is GUID/UUID serialized as a string.
It would be great to support UUID directly. 
Related [docs](https://github.com/Azure/azure-sdk-for-java/tree/master/sdk/cosmos/azure-spring-data-cosmos#spring-data-annotations)

Current way:
```
public class GeneratedIdEntity {

    @Id
    @GeneratedValue
    private String id;
}
```

Suggested way:
```
public class GeneratedIdEntity {

    @Id
    @GeneratedValue
    private UUID id;
}
```

And than all related layers would reflect it as well, repositories, queries, ...

Thank you.

**Comment by joshfree** [comment]
@kushagraThapar PTAL

**Comment by kushagraThapar** [comment]
This is done.
