### ISSUE TITLE
[BUG]azure-spring-cloud-starter-eventhubs-kafka2.4.0 example china tenant id not working

### ISSUE THREAD

**Issue by dark12345678** [Azure/azure-sdk-for-java#21336]
**Describe the bug**
this issue happened when i run the azure-spring-cloud-starter-eventhubs-kafka example which one in the sdk in china region, the tenant id is working when i run the keyvault example, so i am not sure why not working in the eventhubs kafka side. as i think the different is the keyvault can set the azure.keyvault.authority-host: https://login.partner.microsoftonline.cn and i haven't found any info for this in the AzureEnvironment properities.

kafka example
application yml file parts:
      client-id: cccc     (this is sp role which has added to the namespace IAM role assignment as Contributor role, has full access)
      subscription-id: ccccc
      client-secret: ccccc
      tenant-id: ccccc
      resource-group: cccc
      environment: AzureChina
      region: China North 2
      eventhub:
        namespace: cccc

2021-05-12 22:10:07.942 ERROR 36604 --- [onPool-worker-1] c.azure.identity.ClientSecretCredential  : Azure Identity => ERROR in getToken() call for scopes [https://management.core.chinacloudapi.cn/.default]: AADSTS90002: Tenant 'xxxxxxxxxxxxxxxxxxx' not found. This may happen if there are no active subscriptions for the tenant. Check to make sure you have the correct tenant ID. Check with your subscription administrator.
Trace ID: vvvvvvv
Correlation ID: vvvvvvvv
Timestamp: 2021-05-12 14:10:08Z

***Exception or Stack Trace***
Add the exception log and stack trace if available

**To Reproduce**
1、download the full azure sdk(the version i download date is 2021/05/12)
2、update the pom for the sample azure-sdk-masterl\sdk\spring\azure-spring-boot-samples\azure-spring-cloud-sample-eventhubs-kafka, change the 2.5.0-beta.1 to 2.4.0
3、set up the application yml with the related info（what i am ues is a china north 2 region and tenant）
4、mvn clean install -DskipTests
5、mvn spring-boot:run

***Code Snippet***
Add the code snippet that causes the issue.

**Expected behavior**

**Screenshots**
![image](https://user-images.githubusercontent.com/11474948/118085772-82568600-b3f5-11eb-8ac2-88f04954ef5a.png)

for the event hub namespace( IAM )i have added the service principle role to the list(which clientid and secret is for this sp)

**Setup (please complete the following information):**
 - OS: [e.g. iOS] windows 10
 - IDE : [e.g. IntelliJ] intellij
 - Version of the Library used  azure-spring-cloud-starter-eventhubs-kafka2.4.0
 - example info: the newest pom which one contains 2.5.0-beta.1 as not include in the marven repo, so i change to 2.4.0 version

**Additional context**
 i also set up another way to call the event hub base on the SAS policy with kafka protocol, that's work for the event hub and no need to add any dependency.
**Information Checklist**
Kindly make sure that you have added all the following information above and checkoff the required fields otherwise we will treat the issuer as an incomplete report
- [ ] Bug Description Added
- [ ] Repro Steps Added
- [ ] Setup information Added

**Comment by stliu** [comment]
Thanks @dark12345678 for reporting this, and @yiliuTo would u please take a look of this ?
And @dark12345678 , by the way, opensource contribution / PR is always welcome :D

**Comment by yiliuTo** [comment]
@dark12345678 thanks for the reporting, there is a bug with the configuration we provide to set cloud environment, we will fix it soon.

**Comment by backwind1233** [comment]
close this issue, tracking in [Release Spring Cloud for Azure 4.0.0-beta.1](https://github.com/Azure/azure-sdk-for-java/issues/24260)
the issue will be resolved after the  4.0.0-beta.1 libraries released.

**Comment by backwind1233** [comment]
close this issue, tracking in [Release Spring Cloud for Azure 4.0.0-beta.1](https://github.com/Azure/azure-sdk-for-java/issues/24260)
the issue will be resolved after the  4.0.0-beta.1 libraries released.
