### ISSUE TITLE
cspell - add "java" language to cspell dictionaries list to prevent false positives in non-java files

### ISSUE THREAD

**Issue by danieljurek** [Azure/azure-sdk-for-java#21344]
In non-source files (e.g. examples in markdown files) source code specific terms (e.g. `struct`) is treated as an error. Add the language to `dictionaries` in the `cspell.json` file to prevent these false positives. 
  
Source: https://github.com/Azure/azure-sdk-for-net/pull/21027/files#r631288645

**Comment by alzimmermsft** [comment]
This was done: https://github.com/Azure/azure-sdk-for-java/blob/main/.vscode/cspell.json#L7
