### ISSUE TITLE
DefaultAzureCredentialBuilder creating credential from Managed Identity before Environment Variables

### ISSUE THREAD

**Issue by sethcrichton** [Azure/azure-sdk-for-java#21350]
**Describe the bug**
We are using the DefaultAzureCredentialBuilder to build the credential to use with a SecretClient to read secrets from KeyVault.  The code is being deployed in a Docker container running on a VM host in Azure.  We have KeyVault correctly configured with an access policy granting Get & List Secret Permissions to a registered Application.  The details for that Application are set as environment variables on the container (AZURE_CLIENT_SECRET, AZURE_TENANT_ID, AZURE_CLIENT_ID).
When the host VM is configured to use a system assigned Managed Identity, calls to retrieve secrets fail with an unauthorized exception because the wrong identity is being used.

***Exception or Stack Trace***
`The user, group or application 'appid={app id of managed identity};oid={oid of managed identity};iss=https://sts.windows.net/{tenant id}/' does not have secrets get permission on key vault '{key vault name & region}'`

**To Reproduce**
- Create AAD App Registration, assign Client Secret
- Create Azure KeyVault, add Access Policy giving the App List & Get permissions on Secrets
- Deploy java application in a Docker container in an Azure VM configured to use a system assigned Managed Identity
- Run the code to fetch secret(s)

***Code Snippet***
```
    SecretClient secretClient = new SecretClientBuilder()
        .vaultUrl('vaultUrl')
        .credential(new DefaultAzureCredentialBuilder().build())
        .buildClient()

    KeyVaultSecret retrievedSecret = secretClient.getSecret('secretName')
```

**Expected behavior**
Documentation states that Environment Variables will be used before Managed Identity to build the credential

**Setup (please complete the following information):**
 - OS: Docker container (Linux)
 - IDE : IntelliJ
 - com.azure:azure-identity:1.0.9
 - com.azure:azure-security-keyvault-secrets:4.1.5

**Additional context**
Toggling the system assigned Managed Identity to "Off" on the host VM fixes the problem and secrets are retrieved as expected

**Information Checklist**
Kindly make sure that you have added all the following information above and checkoff the required fields otherwise we will treat the issuer as an incomplete report
- [X] Bug Description Added
- [X] Repro Steps Added
- [X] Setup information Added

**Comment by joshfree** [comment]
@g2vinay could you please follow up with @sethcrichton

**Comment by g2vinay** [comment]
@sethcrichton 
Thank you for posting this issue.
Looking at this you're using `DefaultAzureCredential` to authenticate with your KeyVault in an Azure VM with system assigned identity enabled.


The DefaultAzureCredential uses this sequence to authenticate: 
![DefaultAzureCredential authentication flow](https://github.com/Azure/azure-sdk-for-java/raw/master/sdk/identity/azure-identity/images/defaultazurecredential.png)

The `EnvironmentCredential` executes before `ManagedidentityCredential` and if it fails only then `ManagedIdentityCredential` is executed.
So, in your setup you mentioned you've provided these environment variables in your Docker Container: 
`AZURE_CLIENT_SECRET`, `AZURE_CLIENT_ID`, and  `AZURE_TENANT_ID`, but the application is likely, not able to pick up these environment variables and that is why `Environment Credential` is failing in the authentication flow.

To better debug, you can use `EnvironmentCredential` directly as follows:
```java
        SecretClient secretClient = new SecretClientBuilder()
                .vaultUrl('vaultUrl')
                .credential(new EnvironmentCredentialBuilder().build())
                .buildClient();

        KeyVaultSecret retrievedSecret = secretClient.getSecret('secretName');
```

This will look to directly use the service principal details from environment variables to authenticate.
If the application is not able to pick up details from environment variables then this authentication will fail.

**Comment by sethcrichton** [comment]
I think you may have missed this in the steps to reproduce:
_Deploy java application in a Docker container in an Azure VM configured to use a system assigned Managed Identity_

![image](https://user-images.githubusercontent.com/1273477/118732061-e9f64200-b7f6-11eb-8cdb-4160d31c6872.png)

When running this way with the code listed above, the Managed Identity was used to authenticate with KeyVault (we could verify this by the appid & oid in the error message stating.

After turning the system-assigned identity off on the VM, the application authenticated successfully with KeyVault with no other code or environment changes.  This clearly indicates that all 3 environment variables were present, but were being ignored in favor of the Managed Identity.

**Comment by g2vinay** [comment]
@sethcrichton 
Thank you for the additional details.
It looks like you're using older versions of azure-identity and azure-security-keyvault-secrets.
com.azure:azure-identity:1.0.9
com.azure:azure-security-keyvault-secrets:4.1.5

Can you upgrade them to their latest versions and verify if the issue still persists for you ?
```
<dependency>
  <groupId>com.azure</groupId>
  <artifactId>azure-identity</artifactId>
  <version>1.3.0</version>
</dependency>

<dependency>
  <groupId>com.azure</groupId>
  <artifactId>azure-security-keyvault-secrets</artifactId>
  <version>4.2.8</version>
</dependency>
```

**Comment by sethcrichton** [comment]
OK, we will update to latest versions and redeploy.  I will let you know the result.

**Comment by sethcrichton** [comment]
@g2vinay I have updated the versions on those libraries and can no longer reproduce the behavior.  This issue can be closed, and thank you for your help!
