### ISSUE TITLE
[QUERY] Azure Cosmos DB BulkExecutor java offerThroughput value

### ISSUE THREAD

**Issue by Liave** [Azure/azure-sdk-for-java#21390]
**Query/Question**

Hi,

When using Azure Cosmos DB BulkExecutor library with a container that is defined as auto scale , what should be the value for the offerThroughput  when creating the client? should it be the max throughput value defined for the container?

for example the container is defined autoscale with max RU/s as 40000 (4000 - 40000 range), so I should give the bulk client value of 40000?
if I give value which is less then 40000 to the client does it know to use more if needed?

Builder bulkExecutorBuilder = DocumentBulkExecutor.builder().from(
			  client,
			  DATABASE_NAME,
			  COLLECTION_NAME,
			  collection.getPartitionKey(),
			  offerThroughput); 

thanks,
Liav

***Why is this not a Bug or a feature Request?***
A clear explanation of why is this not a bug or a feature request?

**Setup (please complete the following information if applicable):**
 - IDE : [e.g. IntelliJ]
 - Version of the Library used
 
 **Information Checklist**
 Kindly make sure that you have added all the following information above and checkoff the required fields otherwise we will treat the issuer as an incomplete report
- [ ] Query Added
- [x] Setup information Added

**Comment by joshfree** [comment]
@kushagraThapar PTAL

**Comment by kushagraThapar** [comment]
@FabianMeiswinkel  - can you please help with this issue ?

**Comment by xinlian12** [comment]
OfferThroughput specifies the throughput allocated for bulk operations out of the collection's total throughput.

And also as of today, we recommended using V4 for bulk support: https://docs.microsoft.com/en-us/azure/cosmos-db/sql/bulk-executor-java
