### ISSUE TITLE
Spring Cosmos - Support Spring data REST access

### ISSUE THREAD

**Issue by z1069867141** [Azure/azure-sdk-for-java#21432]
Spring data rest can direct Spring MVC to create Restful endpoints for Repositories:

https://docs.spring.io/spring-data/rest/docs/current/reference/html/#reference

This story is to support this behavior for cosmos Repositories. 

Because Spring data may assume the application repository implementing some existing Repository API, so this user story may impacts #88 https://dev.azure.com/azure-spring-integration/spring-integration-private/_workitems/edit/88

**Comment by kushagraThapar** [comment]
@backwind1233  - is this issue still valid ?

**Comment by stliu** [comment]
close since no customer ask for this one
