### ISSUE TITLE
Spring Cosmos - Use managed identity to access cosmos

### ISSUE THREAD

**Issue by z1069867141** [Azure/azure-sdk-for-java#21439]
Azure managed identity allows application to access Azure resources without worry about credentials:

https://docs.microsoft.com/en-us/azure/active-directory/managed-identities-azure-resources/overview

This story is to enable cosmos Spring integration module to access cosmos service using managed identity.

Related github issue: https://github.com/Azure/azure-sdk-for-java/issues/12725

**Comment by kushagraThapar** [comment]
@z1069867141  - is this still an open issue given we do support AAD through spring now ?

**Comment by backwind1233** [comment]
Thanks @kushagraThapar, I will check it

**Comment by saragluna** [comment]
@backwind1233 I believe this has been implemented in our next major version, https://github.com/Azure/azure-sdk-for-java/pull/23849.

**Comment by saragluna** [comment]
Closing this now for it's been implemented in 4.0.0-beta.2.
