### ISSUE TITLE
Couldn't get the Virtual Machine list from Scaleset

### ISSUE THREAD

**Issue by rakeshjmcafee** [Azure/azure-sdk-for-java#2144]
Hi,

We were using azure-mgmt-compute-1.3.0.jar (Azure SDK) to discovery the VMscaleset from our account and inturn find the list of VMs under the VMSCaleset, We could able to get the VMscaleset but couldnt able to get the list of VMS under the scaleset, Is there is any changes done on this part.

Below is the Java Code we were trying.

ComputeManager compMgr = ComputeManager.authenticate(credentials, 'Subscritpion Number');
PagedList<VirtualMachineScaleSet> list = compMgr.virtualMachineScaleSets().list();
for (VirtualMachineScaleSet virtualMachineScaleSet : list)
{
System.out.println(virtualMachineScaleSet.name());

//Not working
PagedList<VirtualMachineScaleSetVM> pagedList = virtualMachineScaleSet.virtualMachines().list();
//Here size of pagedList is always 0

}

**Comment by lenala** [comment]
I am able to see virtual machine instances from SDK, can you see any instances on the portal or from CLI? I cannot repro the issue.

**Comment by praries880** [comment]
@rakeshjmcafee are you still running into the issue?

**Comment by vhvb1989** [comment]
Hello @rakeshjmcafee 

Do you still need help on this? Let me know and I would be happy to help.

Note: As part of repository cleaning effort, this issue will be closed by **Nov 11** if no response is received from submitter and/or not further action is required.
