### ISSUE TITLE
Spring Cosmos - Improve README of Spring Cosmos module

### ISSUE THREAD

**Issue by z1069867141** [Azure/azure-sdk-for-java#21445]
- In the code snippet for 'Setup Configuration Class', the dbName attribute is not used
- In the code snippet for 'Customizing Configuration', not sure what's the purpose to include cosmosConfig() method
- In the section of 'Spring Data custom query, pageable and sorting', the code snippet seems incorrect
- The code snippet for 'multi-database configuration' is confusing, we need to rethink what's the proper way to config multi database

**Comment by stliu** [comment]
I don't think this is still a valid issue, closing it for now

**Comment by stliu** [comment]
I don't think this is still a valid issue, closing it for now
