### ISSUE TITLE
Spring Cosmos - Support bulk exeutor

### ISSUE THREAD

**Issue by z1069867141** [Azure/azure-sdk-for-java#21442]
cosmos has one feature called bulk executor:

https://docs.microsoft.com/en-us/azure/cosmos-db/bulk-executor-overview

When bulk import or update entities, the entities are divided into partition key ranges and further into mini batches. This can significantly improve client performance.

This story is utilize this feature in cosmos Spring data integration.

**Comment by stliu** [comment]
close since no customer ask for this one
