### ISSUE TITLE
Spring Cosmos - Support change feed

### ISSUE THREAD

**Issue by z1069867141** [Azure/azure-sdk-for-java#21440]
There is a change feed feature in cosmos, some documents about the feature:
https://docs.microsoft.com/en-us/azure/cosmos-db/sql/change-feed-design-patterns
[azure-cosmos-java-sql-api-samples](https://github.com/Azure-Samples/azure-cosmos-java-sql-api-samples/blob/main/src/main/java/com/azure/cosmos/examples/changefeed/SampleChangeFeedProcessor.java#L124-L154)
[Reading Azure Cosmos DB change feed](https://docs.microsoft.com/en-us/azure/cosmos-db/sql/read-change-feed)
https://docs.microsoft.com/en-us/azure/cosmos-db/change-feed

This feature enable applications to receive updates in cosmos containers. The feature likes [Canel](https://github.com/alibaba/canal) in mysql.

This user story involves an API design to support change feed.

Mongo DB has similar featuer change streams :
https://spring.io/blog/2018/09/27/what-s-new-in-spring-data-lovelace-for-mongodb

Questions
- [ ] should ship a new starter?

**Comment by stliu** [comment]
close since no customer ask for this one
