### ISSUE TITLE
Improve "Spring Boot Starters for Azure" for non-Spring developers

### ISSUE THREAD

**Issue by z1069867141** [Azure/azure-sdk-for-java#21444]
While reviewing @Sean Li survey https://microsoft.qualtrics.com/jfe/form/SV_3kjY2RG7hxvZMix decided to see if I could improve the landing page for the starters from the perspective of non-Spring developers.  

Justification: Current article has links that frustrate
![image](https://user-images.githubusercontent.com/33398394/118252632-8f4da500-b4db-11eb-80da-ea3f8a4bf330.png)

This is just a list of samples!
![image](https://user-images.githubusercontent.com/33398394/118252650-92e12c00-b4db-11eb-9a80-9c22a4c7765a.png)

**Comment by seanli1988** [comment]
https://github.com/MicrosoftDocs/azure-dev-docs-pr/pull/715 is already merged

**Comment by seanli1988** [comment]
https://github.com/MicrosoftDocs/azure-dev-docs-pr/pull/715 is already merged
