### ISSUE TITLE
Spring JCA - Add support for Azure Government to certificate starter

### ISSUE THREAD

**Issue by z1069867141** [Azure/azure-sdk-for-java#21455]

**Comment by chenrujun** [comment]
Closing this issue, because Azure US Government is already supported.
Refs: https://github.com/Azure/azure-sdk-for-java/blob/b1dcfcdec8de264eb5f6bb20813d2a24338fcb72/sdk/keyvault/azure-security-keyvault-jca/src/test/java/com/azure/security/keyvault/jca/KeyVaultClientTest.java#L28
