### ISSUE TITLE
Include the latest library for Media services

### ISSUE THREAD

**Issue by jiangyurong609** [Azure/azure-sdk-for-java#2145]
I'm trying to utilize the v3 APIs, however, I found in Maven (https://mvnrepository.com/artifact/com.microsoft.azure/azure-media), the latest version is 0.9.8. Is there anyway I can include the latest version in my project? I'm using intellij. 

Thanks

**Comment by praries880** [comment]
We should update the java sdk for MEdia services, the latest swagger is : https://github.com/Azure/azure-rest-api-specs/tree/master/specification/mediaservices/resource-manager/Microsoft.Media/stable/2018-07-01

**Comment by yungezz** [comment]
hi @xccc-msft could you pls check what's latest API version for media service?

**Comment by yungezz** [comment]
hi @jiangyurong609 here it is https://search.maven.org/search?q=g:com.microsoft.azure.mediaservices.v2018_07_01.
