### ISSUE TITLE
Spring Keyvault - Add support for PEM format for private key to Certificates starter

### ISSUE THREAD

**Issue by z1069867141** [Azure/azure-sdk-for-java#21457]

**Comment by chenrujun** [comment]
Closing this issue because pem type is already supported: https://github.com/Azure/azure-sdk-for-java/tree/c859ce8a1fb058d5fb4640a06a3fc9fa2dcecef1/sdk/spring/azure-spring-boot-starter-keyvault-certificates#supported-key-type
