### ISSUE TITLE
Spring Storage - Provide properties supported by sdk

### ISSUE THREAD

**Issue by z1069867141** [Azure/azure-sdk-for-java#21462]
Provide properties supported by sdk
for now, in StorageAutoConfiguration.java  ,
BlobServiceClientBuilder and ShareServiceClientBuilder, only a few properties are supported.

it should work on top of  branch [spring-unify-configurations](https://github.com/Azure/azure-sdk-for-java/tree/feature/spring-unify-configurations)

**Comment by saragluna** [comment]
Implemented in this PR https://github.com/Azure/azure-sdk-for-java/pull/23849, closing this now.
