### ISSUE TITLE
Spring keyvault - Add documentation for the keyvault cert starter

### ISSUE THREAD

**Issue by z1069867141** [Azure/azure-sdk-for-java#21464]
Add documentation for the keyvault cert starter
https://github.com/MicrosoftDocs/azure-dev-docs-pr/pull/1460
![image](https://user-images.githubusercontent.com/33398394/118234932-9cac6480-b4c6-11eb-8f22-bd342ae78b02.png)
https://github.com/MicrosoftDocs/azure-dev-docs-pr/pull/1212

**Comment by chenrujun** [comment]
Closing it. Because related PR already merged.
