### ISSUE TITLE
Spring keyvault - Support Azure Stack Key Vault

### ISSUE THREAD

**Issue by z1069867141** [Azure/azure-sdk-for-java#21465]
@yiliuTo said: "spring boot key vault starter should work in Azure Stack environment with ADFS".

**Comment by stliu** [comment]
@ZhijunZhao please link the issue and close this one

**Comment by chenrujun** [comment]
@backwind1233 , please link the issue and close this one.

**Comment by backwind1233** [comment]
Related PR：https://github.com/Azure/azure-sdk-for-java/pull/15548
