### ISSUE TITLE
Resolve day-1 experience related bugs - Messaging

### ISSUE THREAD

**Issue by z1069867141** [Azure/azure-sdk-for-java#21479]
Bug 7392885: Fix exception in "How to create a Spring Cloud Stream Binder application with Azure Event Hubs"
https://msazure.visualstudio.com/Unified%20Platform%20KPIs/_workitems/edit/7392885
-- assigned to @han-gao 

Bug 7210465: Confirm and update version number in"How to use the Spring Boot Starter for Apache Kafka with Azure Event Hubs"
https://msazure.visualstudio.com/Unified%20Platform%20KPIs/_workitems/edit/7210465
-- assigned to @ZhuXiaoBing-cn 

Bug 6349975: Event Hubs - Java Quick Start : Please modify the library version
https://msazure.visualstudio.com/Unified%20Platform%20KPIs/_workitems/edit/6349975
-- assigned to @han-gao 

Bug 6348987: Event Hubs - Spring Quick Start: Please modify the library version
https://msazure.visualstudio.com/Unified%20Platform%20KPIs/_workitems/edit/6348987
-- assigned to @han-gao 

Bug 6291130: Event Hubs Quickstart - Spring Cloud Stream Binder for KAFKA should not depend on Event Hubs module
https://msazure.visualstudio.com/Unified%20Platform%20KPIs/_workitems/edit/6291130
-- assigned to @ZhuXiaoBing-cn 

Bug 6291129: Event Hubs Quickstart - Spring Cloud Stream Binder for KAFKA uses an old version of the binder
https://msazure.visualstudio.com/Unified%20Platform%20KPIs/_workitems/edit/6291129
-- assigned to @ZhuXiaoBing-cn 

Bug 6291125: Event Hubs Quickstart - Spring Cloud Stream Binder uses an old version of the binder
https://msazure.visualstudio.com/Unified%20Platform%20KPIs/_workitems/edit/6291125
-- assigned to @han-gao 

Bug 7652434: Update version number in "How to create a Spring Cloud Stream Binder application with Azure Event Hubs"
https://msazure.visualstudio.com/Unified%20Platform%20KPIs/_workitems/edit/7652434
-- assigned to @han-gao 

https://msazure.visualstudio.com/Unified%20Platform%20KPIs/_workitems/edit/6291131
-- assigned to @han-gao 

https://msazure.visualstudio.com/Unified%20Platform%20KPIs/_workitems/edit/6291127
-- assigned to @han-gao

**Comment by yiliuTo** [comment]
Close this issue for all bugs have been fixed and related docs have get updated.
