### ISSUE TITLE
Resolve day-1 experience related bugs - Misc

### ISSUE THREAD

**Issue by z1069867141** [Azure/azure-sdk-for-java#21478]
- [ ] Bug 7299679: Add guidance to "Deploy a Spring Boot JAR file Web App to Azure App Service on Linux" on 404 issue
- [ ] Bug 7114479: Failed to instantiate [com.microsoft.azure.spring.cloud.autoconfigure.telemetry.TelemetrySender

**Comment by saragluna** [comment]
Closing this one.
