### ISSUE TITLE
Spring Gremlin - Resolve day-1 experience related bugs - gremlin

### ISSUE THREAD

**Issue by z1069867141** [Azure/azure-sdk-for-java#21480]
Bug 6319667: CosmosDB + Gremlin / Spring Data quickstart: java.lang.NoClassDefFoundError:
https://msazure.visualstudio.com/Unified%20Platform%20KPIs/_workitems/edit/6319667

Bug 6319549: CosmosDB + Gremlin / Spring Data quickstart: unit tests are failing
https://msazure.visualstudio.com/Unified%20Platform%20KPIs/_workitems/edit/6319549

Bug 6319536: CosmosDB + Gremlin / Spring Data quickstart: step order
https://msazure.visualstudio.com/Unified%20Platform%20KPIs/_workitems/edit/6319536

**Comment by backwind1233** [comment]
Gremlin is abandoned, we don't support Gremlin anymore. #21522
