### ISSUE TITLE
Spring Database - Create JDBC starters for credential-less connections

### ISSUE THREAD

**Issue by z1069867141** [Azure/azure-sdk-for-java#21493]
### Context
Support for managed identity has become a fundamental principle for Azure, providing a security baseline at the individual service level. We believe aligning on those guidelines will also benefit Spring developers at large.  

We do not support credential-free connections for any 3rd party libraries today, and it's the same for JDBC drivers connecting to Azure databases.

### Goal
Create JDBC and JPA starters that read bearer tokens from AAD and managed identity providers and inject the token in the database connection string.

See also https://github.com/Azure/azure-sdk-for-java/issues/27494, https://github.com/Azure/azure-jdbc-msi-extension.

**Comment by backwind1233** [comment]
@sshquack Thank you for your feedback.

**Comment by backwind1233** [comment]
Closing this, redirect to https://github.com/Azure/azure-sdk-for-java/issues/30349

**Comment by saragluna** [comment]
@sshquack this feature is not about adding JDBC driver for Azure Cosmos DB, it's for adding support for authenticating Azure databases using Azure Active Directory. The supported databases of this feature will be Azure Database for MySQL and Azure Database for PostgreSQL.
