### ISSUE TITLE
Spring - E2E sample demonstrating interaction with AAD, externalized configurations, secret management and data persistence layer with Azure data services

### ISSUE THREAD

**Issue by z1069867141** [Azure/azure-sdk-for-java#21498]
Implement Toy Store
https://dev.azure.com/azure-spring-integration/spring-integration-private/_wiki/wikis/spring-integration-private.wiki?pagePath=%2FEnd%20to%20end%20samples%2FToy%20store

- [ ] #21474

-----
Related PR:https://github.com/Azure-Samples/azure-spring-boot-samples/pull/45

**Comment by stliu** [comment]
@chenrujun please check the PR already existed

**Comment by chenrujun** [comment]
@stliu 

No, now we do not have Toy store sample application.
I think we can abandon Toy store sample, use this sample instead: https://github.com/Azure-Samples/spring-petclinic-microservices

And related PR is not merge yet: https://github.com/Azure-Samples/spring-petclinic-microservices/pull/14

(cc: @seanli1988 , FYI.)

**Comment by backwind1233** [comment]
https://github.com/Azure-Samples/azure-spring-boot-samples/pull/45
