### ISSUE TITLE
Create starter / library to support TLS communication between Spring apps (with certs in key vault)

### ISSUE THREAD

**Issue by z1069867141** [Azure/azure-sdk-for-java#21494]
Support loading server certificate for server side TLS Spring app from key vault.
Support loading trust certificate (CA) for TLS client side Spring app from key vault. 
#21463 
#21464

**Comment by chenrujun** [comment]
Closing this issue. Use this issue instead: https://github.com/Azure/azure-sdk-for-java/issues/21566
