### ISSUE TITLE
Resolve day-1 experience related bugs - Security

### ISSUE THREAD

**Issue by z1069867141** [Azure/azure-sdk-for-java#21490]
Bug 7211403: Add guidance to Spring docs on using mixed keys when combining Azure Keyvault Spring and Keycloak
https://msazure.visualstudio.com/Unified%20Platform%20KPIs/_workitems/edit/7211403

**Comment by chenrujun** [comment]
Closing this issue because related issue has been closed. https://github.com/MicrosoftDocs/azure-dev-docs/issues/123
