### ISSUE TITLE
Investigate If JsonFlatten Should Deeply Flatten

### ISSUE THREAD

**Issue by alzimmermsft** [Azure/azure-sdk-for-java#21506]
Investigate if JsonFlatten serialization should deeply flatten the object and its properties. The following is a comment on its handling.

```
// Why does this deeply flatten all sub-classes, collection, and map values?
// Should JsonFlatten simply flatten the top level property, ex
// @JsonProperty("my.flattened.value")
// private Map<String, String> value;
//
// Turns into
// {
//   "my":
//   {
//     "flattened":
//     {
//        "value": <serialized map here>
//     }
//   }
// }
```

**Comment by alzimmermsft** [comment]
This has been resolved by changes to support annotating fields with `JsonFlatten` and updates to how class level `JsonFlatten` is applied.

**Comment by samvaity** [comment]
According to the work/investigation on task #20150, we should aggressively/deeply flatten when`@JsonFlatten` is provided irrespective of the type ref parameter. Since it allows the users to specify a property hierarchy more convieniently.
