### ISSUE TITLE
Simplify ActiveDirectorySetting experience for AzureStackUser

### ISSUE THREAD

**Issue by abbhar** [Azure/azure-sdk-for-java#21503]
**Is your feature request related to a problem? Please describe.**

To use SDK against azurestack environment, customer has to figure out different active directory properties, See getActiveDirectorySettings method here: 

https://github.com/abbhar/azure-stack-java-samples/blob/d3a9015bf5e53eed13daaec9c17340ad6f248e44/samples/src/main/java/com/azure/resourcemanager/hybrid/samples/ManageVirtualMachine.java#L174

Based on the customer feedback, we want to remove this pain-point and simplify the experience of using SDK against AZS.

**Describe the solution you'd like**

We can abstract this from customer and provide an utility which AZS user can use to get these properties. 

**Describe alternatives you've considered**

**Additional context**

**Information Checklist**
Kindly make sure that you have added all the following information above and checkoff the required fields otherwise we will treat the issuer as an incomplete report
- [x] Description Added
- [ ] Expected solution specified

**Comment by weidongxu-microsoft** [comment]
We would first need to decide whether to use existing public cloud SDK for Azure Stack or not.
