### ISSUE TITLE
Create new samples and revamp existing sample structure

### ISSUE THREAD

**Issue by z1069867141** [Azure/azure-sdk-for-java#21501]
Create new samples and revamp the existing sample structures to provide developers on-ramp using our starters.
As an example, here are some samples from the Azure SDK team: https://github.com/Azure/azure-sdk-for-java/tree/master/sdk/servicebus/azure-messaging-servicebus/src/samples
As a developer, I can easily find samples for objectives that I want to achieve. 
- [x] #21437: Merge Key Vault READMEs from starter and sample
- [x] #21435: <del>Should we copy our samples to Azure Samples repo

**Comment by stliu** [comment]
closing this one since it is actually an epic and all features are done
