### ISSUE TITLE
[Feature Request] Support `domain_hint` in aad-starter

### ISSUE THREAD

**Issue by glyoder** [Azure/azure-sdk-for-java#21517]
**Query/Question**
I'm using the azure-spring-boot-starter-active-directory library to use azure active directory for login. But I need to pass a domain hint to the authorization url. Unforunately the authorization endpoint is hardcoded in AADAuthorizationServerEndpoints -- is there some way to override this that I'm missing?

***Why is this not a Bug or a feature Request?***
There may be a simple way to do this that I'm not aware of.

**Setup (please complete the following information if applicable):**
 - OS: Linux
 - IDE : IntelliJ
 - Version of the Library used: 3.4.0
 
 **Information Checklist**
 Kindly make sure that you have added all the following information above and checkoff the required fields otherwise we will treat the issuer as an incomplete report
- [x] Query Added
- [x] Setup information Added

**Comment by joshfree** [comment]
@stliu could you follow up with @glyoder

**Comment by chenrujun** [comment]
Hi, @glyoder .
Thanks for reaching out.

1. Now `azure-spring-boot-starter-active-directory` does not support `domain hint`.
2. But `azure-spring-boot-starter-active-directory-b2c` supports `domain hint`.

My current plan is to implement this feature before 2021-08-06 (Milestone: `[2021] August`).
I will very appreciate it if you can create a PR.


Refs: 

1.  `azure-spring-boot-starter-active-directory-b2c` supports `domain hint`: 
1.1. https://github.com/Azure/azure-sdk-for-java/tree/azure-spring-boot-starter-active-directory-b2c_3.4.0/sdk/spring/azure-spring-boot-starter-active-directory-b2c#configure-and-compile-your-app
1.2. https://github.com/Azure/azure-sdk-for-java/blob/azure-spring-boot-starter-active-directory-b2c_3.4.0/sdk/spring/azure-spring-boot/src/main/java/com/azure/spring/autoconfigure/b2c/AADB2CProperties.java#L89
1.3. https://github.com/Azure/azure-sdk-for-java/blob/azure-spring-boot-starter-active-directory-b2c_3.4.0/sdk/spring/azure-spring-boot/src/main/java/com/azure/spring/autoconfigure/b2c/AADB2CAuthorizationRequestResolver.java#L87

2. If we need to let `azure-spring-boot-starter-active-directory` supports `domain hint`:
2.1. https://github.com/Azure/azure-sdk-for-java/blob/azure-spring-boot-starter-active-directory-b2c_3.4.0/sdk/spring/azure-spring-boot/src/main/java/com/azure/spring/autoconfigure/aad/AADAuthenticationProperties.java
2.2. https://github.com/Azure/azure-sdk-for-java/blob/azure-spring-boot-starter-active-directory-b2c_3.4.0/sdk/spring/azure-spring-boot/src/main/java/com/azure/spring/aad/webapp/AADOAuth2AuthorizationRequestResolver.java#L21

**Comment by chenrujun** [comment]
Closing this issue because related PR has been merged.
