### ISSUE TITLE
Send and receive from session enabled queues or topics

### ISSUE THREAD

**Issue by z1069867141** [Azure/azure-sdk-for-java#21539]
Refs:
 - https://github.com/Azure/azure-sdk-for-java/tree/master/sdk/servicebus/azure-messaging-servicebus#send-and-receive-from-session-enabled-queues-or-topics

**Comment by yiliuTo** [comment]
Close this issue for in azure spring cloud sb libs, this feature has been supported. For servicebus jms starter, it is not supported by service bus client. https://github.com/Azure/azure-service-bus/issues/444
