### ISSUE TITLE
Enable caching of jms sessions, producers and consumers

### ISSUE THREAD

**Issue by z1069867141** [Azure/azure-sdk-for-java#21534]
The currently used CachingConnectionFactory from spring-jms library cannot update cache status of session, producers and consumers when items are closed by service/client side. Also this class doesn't expose any API for cache externally.

Thus we need to implement cache of sessions, producers and consumers in order to update their status as needed.

Parent issue: #26072

**Comment by saragluna** [comment]
Closing in favor of https://github.com/Azure/azure-sdk-for-java/issues/26072.
