### ISSUE TITLE
Message Reciever doesn't work with the session enabled queue

### ISSUE THREAD

**Issue by z1069867141** [Azure/azure-sdk-for-java#21533]
Azure/azure-service-bus#326

**Comment by abhikt48** [comment]
+1

Do we have any target for this functionalty? 

We are using Qpid-JMS client to receive/publish messages.  I am also getting same error `exception in thread "main" javax.jms.JMSException: It is not possible for an entity that requires sessions to create a non-sessionful message receiver. `

Can anyone please suggest - how can I receive/publish message with session enabled queue?  Any hint/suggestion?

Regards,
Abhishek Kumar

**Comment by yiliuTo** [comment]
Hi @abhikt48 , this feature is in our roadmap while is not under development now.

For receiving via JMSListener, after preliminary investigation, seems it's hard-code in Qpid-JMS client that all [AMQP filter-set's key](http://docs.oasis-open.org/amqp/core/v1.0/os/amqp-core-messaging-v1.0-os.html#type-filter-set) is **[jms-selector](https://github.com/apache/qpid-jms/blob/8113b93fae8bb7f90f31fe0e68fcab46b330348f/qpid-jms-client/src/main/java/org/apache/qpid/jms/provider/amqp/builders/AmqpConsumerBuilder.java#L254)**, while for Azure Service Bus, the required filter is **com.microsoft:session-filter**, so currently if you use the azure-spring-boot-starter-servicebus-jms, it's difficult to modify this behavior or receive from session enable queues.

For pubishing, you could use JmsTemplate to send messages and customized the message properties of **JMSXGroupId** with the value of the expected session-id.

Discussion is welcome.

**Comment by abhikt48** [comment]
HI @yiliuTo, Thanks for update. I am able to send message with JMSXGroupId but not able to receive message from session enabled queue. Checked with [qpid team](http://mail-archives.apache.org/mod_mbox/qpid-users/202107.mbox/%3CCAFitrpQdOnr6cLcMQ7QO12AKR_Cm8FoJfnueZ%3DhOxkrUpWM1Vw%40mail.gmail.com%3E) , as per them **com.microsoft:session-filter** is an illegal filter. So they will not provide any option for this feature.

Looks like, we need to extend qpid library or get any other option from ServiceBus to consume session enabled messages..

**Comment by yiliuTo** [comment]
Hi @abhikt48 , yes I agree so, perhaps you could inverstigate if it's possible to extend the associated classes to customzied the filter key.
Also I created an issue to the service bus repo to see if they could support is. ref: https://github.com/Azure/azure-service-bus/issues/444

**Comment by sgcoates** [comment]
thanks for the prompt reply @abhikt48 - we've decided to avoid JMS for now and go directly with AMQP as described in this sample. It seems to honour the FIFO/Session requirements that we have.  [ReceiveNamedSessionAsyncSample.java](https://github.com/Azure/azure-sdk-for-java/blob/main/sdk/servicebus/azure-messaging-servicebus/src/samples/java/com/azure/messaging/servicebus/ReceiveNamedSessionAsyncSample.java )

**Comment by yiliuTo** [comment]
Close this issue for it is not supported by service bus client. ref: https://github.com/Azure/azure-service-bus/issues/444
