### ISSUE TITLE
Update docs on how to set session-id in JmsTemplate

### ISSUE THREAD

**Issue by z1069867141** [Azure/azure-sdk-for-java#21531]
@JmsTemplate wasn't able to write messages to the session enabled queue by default as there is no easy way to set up "SessionId" for the message. With some research we figured out that we had to set up a string property "JMSXGroupID" with the message that results in the session id, but strangely this is not documented.

https://github.com/MicrosoftDocs/azure-dev-docs/issues/285

**Comment by yiliuTo** [comment]
We need to update in our docs/samples for how to set session id via JmsTempalte

**Comment by saragluna** [comment]
Do we also need to include this in our reference doc?

**Comment by jialigit** [comment]
This pr solves this.
https://github.com/MicrosoftDocs/azure-dev-docs-pr/pull/2806

**Comment by jialigit** [comment]
close for pr merged
