### ISSUE TITLE
[Feature Request] Enable client side batching for Spring Cloud Azure Service Bus

### ISSUE THREAD

**Issue by z1069867141** [Azure/azure-sdk-for-java#21537]
### Context
Referring to [Service Bus client-side batching](https://docs.microsoft.com/azure/service-bus-messaging/service-bus-performance-improvements?tabs=net-standard-sdk#client-side-batching), Service Bus supports client side batching operations to send messages in batches.

### Goal
Support client-side batching in Spring Cloud Azure Service Bus libraries towards different spring projects.

**Comment by stliu** [comment]
@yiliuTo is this sitll valid?

**Comment by yiliuTo** [comment]
Hi @stliu , there can be two modes of the client-side batching: explicitly and implicitly. The explicit way is to construct a batch of messages and using the SDK sender client to send directly, this is supported by [ServiceBusSenderAsyncClient](https://github.com/Azure/azure-sdk-for-java/blob/ed95889103f6fbe2c0ed38ee81d2275c06f0c3d8/sdk/servicebus/azure-messaging-servicebus/src/main/java/com/azure/messaging/servicebus/ServiceBusSenderAsyncClient.java#L373), however, given it has been implemented in the same as how [EventHubProducerAsyncClient](https://github.com/Azure/azure-sdk-for-java/blob/4a1c009407c6688488b3e643733d598e7f61abbd/sdk/eventhubs/azure-messaging-eventhubs/src/main/java/com/azure/messaging/eventhubs/EventHubProducerAsyncClient.java#L295) does, so currently we can only support batch sending in the `ServiceButTemplate` level, not the integration or binder level.

And for the implicit way, which is that the SDK client batches messages automatically and send, this is not supported by the ServiceBusSenderAsyncClient nor the sync client.

So I think what we can do for the client-side batching currently, is to support the batch sending API in the `ServiceButTemplate` level, which may bring limited benefits to the developers. Maybe we can leave it in the backlog and wait till the SDK client supports implictily batching? Or just cancel this task for there is no feature ask from the customers' side.
