### ISSUE TITLE
Support shared subscription

### ISSUE THREAD

**Issue by z1069867141** [Azure/azure-sdk-for-java#21536]
In azure service-bus, subscription support load-leveling / competing consumer:
 - https://docs.microsoft.com/en-us/azure/service-bus-messaging/service-bus-queues-topics-subscriptions#topics-and-subscriptions

Currently, the azure-spring-boot-starter-servicebus-jms's default subscription is not shared.
Code to reproduce:
 - https://github.com/chenrujun/azure-spring-boot-starter-servicebus-jms-sample/tree/one-subscription-can-not-have-multiple-receivers

Our target is to support shared subscription.

**Comment by yiliuTo** [comment]
Close this issue for it has been supported in https://github.com/Azure/azure-sdk-for-java/issues/23392
