### ISSUE TITLE
Enhance Spring integrations for Service Bus

### ISSUE THREAD

**Issue by z1069867141** [Azure/azure-sdk-for-java#21546]
1. Support dlq receiver #21540
2. More consumer/producer properites #21542
3. Batch consumers #21545
4. Sync/async client #21538
5. Set receive mode #17421
============================
1. Support shared subscription #21536 
2. Batch client sending operations #21537
4. Support session enabled queue/topic #21539
6. Support transaction #21541
8. Integrate with Spring sleuth and Zipkin #21543
9. Support health indicator and metrics #21544
10. Support tracing #21760

**Comment by yiliuTo** [comment]
Closing this issue for we have other issues tracking for these respectively.
