### ISSUE TITLE
Investigate should we support storage account and EH in different resource groups

### ISSUE THREAD

**Issue by z1069867141** [Azure/azure-sdk-for-java#21548]
https://github.com/microsoft/spring-cloud-azure/issues/632

**Comment by avpines** [comment]
We have a case where we need to consume events from an Event-Hub that we don't own and can't create a storage account in its resource group. Currently, such a case is not supported.

**Comment by saragluna** [comment]
@yiliuTo, I believe this PR https://github.com/Azure/azure-sdk-for-java/pull/23849 has implemented this feature.

**Comment by saragluna** [comment]
Please track #24260 for the release of our next major version.
