### ISSUE TITLE
Enhance Spring integrations for Event Hubs

### ISSUE THREAD

**Issue by z1069867141** [Azure/azure-sdk-for-java#21558]
1. Support messaging replay of EH #21547 
2. Make Storage account optional #21549
4. batch consumers #21555
11. ~More consumer properties #21556~
12. ~More producer properties #21557~
13. ~Set AmqpRetryOptions for EH connection #16596~
14. Feature parity with configurations supported by EventHub SDK
15. Metrics #21551
6. Tracing #21760 
7. Support gateway configuration #21552

=============================
8. Message QoS #21553
3. Support Storage and EH in different resource groups #21548
7. Enhancement scope #21554
8. <del>Health inidicator for binder #21553 
9. <del>DLQ for EH #21550

**Comment by yiliuTo** [comment]
Closing this issue for we have another issues tracking for each respectively.
