### ISSUE TITLE
[Reactive] [single tenant app] Enable authentication with id token

### ISSUE THREAD

**Issue by z1069867141** [Azure/azure-sdk-for-java#21559]

**Comment by chenrujun** [comment]
Closing this issue, use task like in this issue instead: https://github.com/Azure/azure-sdk-for-java/issues/21581

**Comment by meshpaul** [comment]
Hi we need this where is the code ref or PR for this?

**Comment by chenrujun** [comment]
@meshpaul 

Thank you for your check.
Now it's not supported.
As I commented in last comment:

> Closing this issue, use task like in this issue instead: https://github.com/Azure/azure-sdk-for-java/issues/21581
