### ISSUE TITLE
Add more ConsumerProperties and producer properties in Azure Spring Event Hub client factory

### ISSUE THREAD

**Issue by z1069867141** [Azure/azure-sdk-for-java#21556]
When we init a client, it may have some properties, we should make these properties configurable.
Make Azure Spring Cloud Event Hubs Stream Binder supports all configurable properties of associated SDK Event Hubs producer / consumer / processor clients

**Comment by saragluna** [comment]
Closing this one for it's been implemented on the 4.0 branch.
