### ISSUE TITLE
Support end to end TLS: 2.1. Https Server

### ISSUE THREAD

**Issue by chenrujun** [Azure/azure-sdk-for-java#21570]
Refs: #21566

**Comment by wujack778** [comment]
https://github.com/wujack778/Support-https-server-and-client-and-server-client/blob/73614f130bcb44e3addbddebe144eed3e20e1c1d/src/main/java/com/azure/spring/security/keyvault/certificates/sample/server/side/SampleController.java  Support end to end TLS: 2.1. Https Server

**Comment by chenrujun** [comment]
@wujack778 Thank you for your effort.
