### ISSUE TITLE
[Reactive] Support Spring reactive stack for AAD starter

### ISSUE THREAD

**Issue by z1069867141** [Azure/azure-sdk-for-java#21581]
- [ ] Investigate @EnableWebFluxSecurity and @EnableReactiveMethodSecurity
 - [ ] Support multiple Azure clouds
 - [ ] [Misc] BI support
 - [ ] [Misc] Support conditional access
 - [ ] [multi tenant api] Expose tenant information in user principal
 - [ ] [multi tenant app] Provide admin consent support
 - [ ] [single tenant api] Enable current API to call other API via on behalf of flow
 - [ ] [single tenant api] Generate user principal and provide authority based on app roles and scopes
 - [ ] [single tenant api] Validate access token
 - [ ] [single tenant app] Enable incremental consent
 - [ ] [single tenant app] Integrate with AAD sign out
 - [ ] [single tenant app] Enable app to call other AAD protected API
 - [ ] [single tenant app] Generate user principal with id token and provide authority based on app roles and groups
 - [ ] [single tenant app] Enable authentication with id token

**Comment by letmagnau** [comment]
but this issue are related to this one? 

https://github.com/microsoft/azure-spring-boot/issues/879#issuecomment-930645683

i can't see it

**Comment by chenrujun** [comment]
Closing this issue, because we decide to deprecate azure-spring-boot-starter-active-directory. Just write sample to demonstrate how to use Azure Active Directory in Spring Boot application in this repo: https://github.com/Azure-Samples/spring-boot-application-with-azure-active-directory
