### ISSUE TITLE
[api] Generate user principal and provide authority based on app roles and scopes

### ISSUE THREAD

**Issue by z1069867141** [Azure/azure-sdk-for-java#21589]

**Comment by chenrujun** [comment]
Closing this issue because it's already been implemented in [AADJwtGrantedAuthoritiesConverter](https://github.com/Azure/azure-sdk-for-java/blob/azure-spring-boot-starter_3.4.0/sdk/spring/azure-spring-boot/src/main/java/com/azure/spring/aad/webapi/AADJwtGrantedAuthoritiesConverter.java#L19).
