### ISSUE TITLE
[Spring]Support to config different Azure clouds than Azure public

### ISSUE THREAD

**Issue by z1069867141** [Azure/azure-sdk-for-java#21593]

**Comment by chenrujun** [comment]
Closing this issue, use task like in this issue instead: https://github.com/Azure/azure-sdk-for-java/issues/21581

**Comment by stliu** [comment]
this should not be closed, since #21581 is targeting to AAD starter only, and this is supposed to support all sdk's configuration

**Comment by chenrujun** [comment]
@stliu 

This issue is copied from Azure Dev Ops (ADO). 
The original ADO task is only target to AAD starter.

I think it's OK to give this issue a wider scope: to all sdk's configuration.
