### ISSUE TITLE
Verify MSI support on Azure Spring Cloud

### ISSUE THREAD

**Issue by z1069867141** [Azure/azure-sdk-for-java#21596]
There is a com.azure.identity.AppServiceMsiCredential and ServiceFabricMsiCredential but no AzureSpringCloudMsiCredential, confirm whether we support MSI on Azure spring cloud.

**Comment by chenrujun** [comment]
Closing this issue because current aad-b2c already set [http header](https://github.com/Azure/azure-sdk-for-java/blob/azure-spring-boot-starter_3.4.0/sdk/spring/azure-spring-boot/src/main/java/com/azure/spring/autoconfigure/b2c/AADB2CAuthorizationRequestResolver.java#L36).

**Comment by chenrujun** [comment]
Hi, @saragluna , maybe this issue is not only related to aad-b2c?

**Comment by stliu** [comment]
it should be an azure-identity issue, @saragluna would you open another one and assign to the azure-identity team

**Comment by saragluna** [comment]
Opened https://github.com/Azure/azure-sdk-for-java/issues/23548.
