### ISSUE TITLE
[misc] Enable BI tracking for B2C starter

### ISSUE THREAD

**Issue by z1069867141** [Azure/azure-sdk-for-java#21595]

**Comment by chenrujun** [comment]
Closing this issue because current aad-b2c already set [http header](https://github.com/Azure/azure-sdk-for-java/blob/azure-spring-boot-starter_3.4.0/sdk/spring/azure-spring-boot/src/main/java/com/azure/spring/autoconfigure/b2c/AADB2CAuthorizationRequestResolver.java#L36).
