### ISSUE TITLE
[misc] Enable BI tracking

### ISSUE THREAD

**Issue by z1069867141** [Azure/azure-sdk-for-java#21591]

**Comment by chenrujun** [comment]
Closing this issue because BI tracking is both enabled for aad and aad-b2c. Refs: https://github.com/Azure/azure-sdk-for-java/blob/azure-spring-boot-starter_3.4.0/sdk/spring/azure-spring-boot/src/main/java/com/azure/spring/utils/ApplicationId.java#L40-L41
