### ISSUE TITLE
[Reactive] Support Spring reactive stack for AAD B2C starter

### ISSUE THREAD

**Issue by z1069867141** [Azure/azure-sdk-for-java#21594]
- [ ] [api] Enable api to call other api proected by aad b2c access token
 - [ ] [app] Enable app to call API protected by aad b2c access token
 - [ ] [app] Authenticate with aad b2c sign up / sign in user flow
 - [ ] [app] Integrate other aad b2c flows in application
 - [ ] [app] Generate user principal and provide authority based on app roles and groups
 - [ ] [app] Integrate with aad b2c sign out

**Comment by chenrujun** [comment]
Closing this issue. Use this one instead: https://github.com/Azure-Samples/spring-boot-application-with-azure-active-directory/issues/9
