### ISSUE TITLE
Overview page for Event Grid ref docs show older packages

### ISSUE THREAD

**Issue by ramya-rao-a** [Azure/azure-sdk-for-java#21619]
In the [landing page for Event Grid ref docs](https://docs.microsoft.com/en-us/java/api/overview/azure/eventgrid?view=azure-java-stable), we have sample code showing the use of the older Event Grid packages.

This page needs to be updated to be as per the format you can see for the [landing page for Key Vault ref docs](https://docs.microsoft.com/en-us/java/api/overview/azure/keyvault?view=azure-java-stable)

This page is linked from the Java node under Reference in https://docs.microsoft.com/en-us/azure/event-grid/, so it is important to have this point to the latest packages.

cc @lmazuel 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 90b60e60-b814-b416-dce5-9c6af95aedf2
* Version Independent ID: 01114f9f-f91d-5388-41c7-69b50b6d9fcf
* Content: [Azure Event Grid libraries for Java](https://docs.microsoft.com/en-us/java/api/overview/azure/eventgrid?view=azure-java-stable)
* Content Source: [docs-ref-services/latest/eventgrid.md](https://github.com/Azure/azure-docs-sdk-java/blob/master/docs-ref-services/latest/eventgrid.md)
* Service: **event-grid**
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by YijunXieMS** [comment]
@lmazuel @joshfree do you know who is responsible for this doc?

**Comment by ramya-rao-a** [comment]
@YijunXieMS Our team owns these docs. You can make the updates in https://github.com/Azure/azure-docs-sdk-java/blob/master/docs-ref-services/latest/eventgrid.md

**Comment by lmazuel** [comment]
@YijunXieMS let's do that this sprint please, thanks!

**Comment by YijunXieMS** [comment]
Thanks @ramya-rao-a I've seen what to update.

**Comment by alzimmermsft** [comment]
Closing as the latest version is now included in that link
