### ISSUE TITLE
[BUG] Blob URL escapes subdirectory slashes

### ISSUE THREAD

**Issue by JV-TMCZ** [Azure/azure-sdk-for-java#21610]
When a blob is uploaded to subdirectory. API only accept Url.encoded blob name (with virtual folder subdirectories separated by slash). URL.encoded slash is **%2F**. Result blob URL has mixed slashes ... 
```
    String blobname = URLEncoder.encode("virtualFolder/" + blobName, StandardCharsets.UTF_8.toString());
    BlobClient blobClient = blobContainerClient.getBlobClient(blobname);
    blobClient.upload(inputStream, size, true);

    String blobUrl = blobClient.getBlobUrl();
```
https://accountname.blob.core.windows.net/containerName/virtualFolder%2FblobName.ext

But when this blob is opened in azure portal - storage explorer and clicked: Copy URL. The normalized URL is returned as expected.
https://accountname.blob.core.windows.net/containerName/virtualFolder/blobName.ext

**Expected behavior**
Resulting blob url, readed by API, should be returned in normalized format. 

```
        <dependency>
            <groupId>com.azure.spring</groupId>
            <artifactId>azure-spring-boot-starter-storage</artifactId>
            <version>3.4.0</version>
        </dependency>
```

NOTE: the actual code is somehow weird. 
method `getBlobClient(String blobName)` javadocs says "blobName - A String representing the name of the blob. If the blob name contains special characters, **pass in the url encoded version of the blob name.**"
But deeper in source code:
BlobContainerAsyncClient#getBlobAsyncClient(String blobName, String snapshot)
Is blobName DECODED and ENCODED again. Is it really necessary? 

```
public BlobAsyncClient getBlobAsyncClient(String blobName, String snapshot) {
        return new BlobAsyncClient(getHttpPipeline(), StorageImplUtils.appendToUrlPath(getBlobContainerUrl(),
            Utility.urlEncode(Utility.urlDecode(blobName))).toString(), getServiceVersion(), getAccountName(),
            getBlobContainerName(), blobName, snapshot, getCustomerProvidedKey(), encryptionScope);
    }
```

**Comment by joshfree** [comment]
@gapra-msft could you please follow up

**Comment by gapra-msft** [comment]
Hi @JV-TMCZ 

Thank you for reporting this issue. We will take a look and get back to you

**Comment by gapra-msft** [comment]
Future notes: Ideally we would uniformly accept the encoded version of the URL for all APIs that take in a URL/path parameter. Have a special append/modify url method that adds path parameters appropriately without needing to do decoding, or encoding of "/" characters. Ideally the generator accepts an encoded URL as opposed to the decoded URL

**Comment by lukaszmaternia** [comment]
I would like to upvote this.
Note that .net version of this library made this change half year ago (https://github.com/Azure/azure-sdk-for-net/issues/15064 see mrgoetan past with change and kasobol-msft with explanation)

Removed possibility of creating subfolders stopped us from using this library and forced to go back to old one

**Comment by rangarnow** [comment]
Hi @gapra-msft, is there any progress on that? Blob batch delete requires blob urls as an argument to delete blobs. Unfortunately, we can't simple give an array of `blobClient.getBlobUrl()`, because of this problem.

**Comment by gapra-msft** [comment]
@ibrahimrabab could you please take a look?

**Comment by ibrahimrabab** [comment]
Hi @rangarnow 
Just to confirm, when you call `getBlobName()` your blob name is returned as normal, right? But when you call `getBlobUrl()`, it returns the slash "/" character as %2F?
