### ISSUE TITLE
Support end to end TLS: Load cert from file system.

### ISSUE THREAD

**Issue by chenrujun** [Azure/azure-sdk-for-java#21611]
Currently, cert are all loaded from key-vault, we need support load cert from file system(A configurable path).

Refs: #21566

**Comment by chenrujun** [comment]
Here is the steps we need to do:

1. Download latest azure-security-keyvault-jca jar file into your docker image.
2. Modify your startup command. For example: java --classpath /etc/azure/azure-security-keyvault-jca.jar -jar app.jar.
3. Put the public cert of Azure service to well-known path: etc/azure-certs/well-known/.

Here is more information about cert path:
1. well-known path.
    1.1. Default value: etc/azure-certs/well-known/.
    1.2. Configuration property: azure.keyvault.cert-path.well-known.
2. customer path
    2.1. Default value: etc/azure-certs/customer/.
    2.2. Configuration property: azure.keyvault.cert-path.customer

Refs: https://github.com/Azure/azure-sdk-for-java/tree/master/sdk/keyvault/azure-security-keyvault-jca

**Comment by chenrujun** [comment]
@gavinfish FYI.

**Comment by chenrujun** [comment]
@gavinfish 


FYI: 
When we specify -jar then the -cp parameter will be ignored.
https://stackoverflow.com/questions/18413014/run-a-jar-file-from-the-command-line-and-specify-classpath

**Comment by gavinfish** [comment]
@chenrujun Here are some questions for you:
1. If customer's app has already depended on azure-security-keyvault-jca to use certificates in Azure Key Vault. Will there be any conflicts when we use the startup command with jca again? 
2. If No.1 is fine, then the app will trust both Key Vault certificates and local certificates, right?
3. Is there any difference for well-known path and customer path except the source of the certificates?

**Comment by gavinfish** [comment]
@chenrujun 
Talked with Asir, two suggestions from him:
1. For the certificate path, do not contain key word `azure` since it is not only for azure services, any other services can be candidates.
2. For Configuration property, do not contain key word `keyvault` since this feature is not related with key vault directly.

**Comment by chenrujun** [comment]
Hi, @gavinfish , I updated https://github.com/Azure/azure-sdk-for-java/issues/21611#issuecomment-842968384 please take a look.

**Comment by chenrujun** [comment]
Hi, @gavinfish , @lzc-1997-abel , I updated the https://github.com/Azure/azure-sdk-for-java/issues/21611#issuecomment-842968384, please take a look.
