### ISSUE TITLE
[Question]How can I generate a authorized download link in azure storage blob

### ISSUE THREAD

**Issue by Xiaoxin4396** [Azure/azure-sdk-for-java#21627]
**Question**
How can I generate a authorized download link in azure storage blob?

***Why is this not a Bug or a feature Request?***
I can get a link by those code, and it could download a file successfully.

1. `StorageSharedKeyCredential credential = new StorageSharedKeyCredential(accountName, accountKey);`
2. `BlobServiceClient blobServiceClient = new BlobServiceClientBuilder().endpoint(endpoint).credential(credential).buildClient();`
3. `BlobClient client = blobServiceClient.getBlobContainerClient(containerName).getBlobClient(blobName);`
4. `BlobServiceSasSignatureValues values = new BlobServiceSasSignatureValues(expiryTime, permission);`
5. `String sasLink = blobClient.generateSas(values);`

But everyone could download the file by this link, I want the file could be downloaded by the one who is authorized.
so I use the `String sasLink = blobClient.generateUserDelegationSas(values, userDelegationKey);`
and the [doc](https://docs.microsoft.com/en-us/java/api/com.azure.storage.blob.blobserviceasyncclient.getuserdelegationkey?view=azure-java-stable) says that _This method call is only valid when using TokenCredential in this object's HttpPipeline._
But there is only _**BasicAuthenticationCredential**_ which implements **_TokenCredential_** in my imported package.

This is my mvn.

`<dependency>
    <groupId>com.azure</groupId>
    <artifactId>azure-storage-blob</artifactId>
    <version>12.11.0-beta.2</version>
</dependency>`

This my code.

1. `BasicAuthenticationCredential basicAuthenticationCredential = new BasicAuthenticationCredential(userName,password);`
2. `BlobServiceClient blobServiceClient = new BlobServiceClientBuilder().endpoint(endpoint).credential(basicAuthenticationCredential).buildClient();`

Then I got this exception
**Exception in thread "main" com.azure.storage.blob.models.BlobStorageException: Status code 401, (InvalidAuthenticationInfo)**

I'm sure I have the right userName and password, so what problem do I have?
Or there is another way to get the authorized download link?

Thanks very much.

**Setup (please complete the following information if applicable):**
 - OS: [ WIN 10 ]
 - IDE : [ IntelliJ ]
 - Version of the Library used: [12.11.0-beta.2]
 
 **Information Checklist**
 Kindly make sure that you have added all the following information above and checkoff the required fields otherwise we will treat the issuer as an incomplete report
- [] Query Added
- [] Setup information Added

**Comment by gapra-msft** [comment]
Hi @Xiaoxin4396 

Thank you for the question. 

Is your account is a flat namespace (regular blob storage) account or a hierarchical namespace account (I would assume the former since you are using the blob SDK)?

If you could provide the request id for the failed service response, I can look at why the credential is failing to return a UserDelegationKey. However, I would like to add that even if you generate a SAS with the UserDelegationKey, with your current sasValues, anyone will be able to use it once generated within the timeframe the sas token is valid if it has appropriate permissions set. 

I would recommend looking into the sasValues.preauthorizedAgentObjectId (saoid) parameter. You can find official documentation on the parameter [here](https://docs.microsoft.com/en-us/rest/api/storageservices/create-user-delegation-sas#user-delegation-sas-support-for-user-oid).

**Comment by Xiaoxin4396** [comment]
Hi @gapra-msft 

Thanks for your help.

Actually, I'm not very clear about 'a flat namespace account', but I think it must be a regular blob storage account, I'm using the free services for 12 months.

I requested once again just now, this is the return information.

```
Exception in thread "main" com.azure.storage.blob.models.BlobStorageException: Status code 401, "﻿<?xml version="1.0" encoding="utf-8"?><Error><Code>InvalidAuthenticationInfo</Code><Message>Server failed to authenticate the request. Please refer to the information in the www-authenticate header.
RequestId:2d445134-301e-00b0-3c8a-4c0353000000
Time:2021-05-19T08:42:36.2508786Z</Message><AuthenticationErrorDetail>The access token was missing or malformed.</AuthenticationErrorDetail></Error>"

```
and this below is my code,
<img width="960" alt="code" src="https://user-images.githubusercontent.com/41957504/118784102-4d997180-b8c2-11eb-8c10-eaa2de1e5853.png">

Beside, is there any code sample for generating a SAS with the UserDelegationKey? 

BR.

**Comment by gapra-msft** [comment]
Hi @Xiaoxin4396 

While I check the service logs for why the request is failing, could you confirm your credential has the following permissions?
https://docs.microsoft.com/en-us/rest/api/storageservices/get-user-delegation-key#authorization

**Comment by Xiaoxin4396** [comment]
Hi @gapra-msft 

I have **Contributor** and **Storage Blob Data Contributor** when I requested a _UserDelegationKey_ yesterday.

And, I find there are many implementations of **TokenCredential** when I import [azure-identity-client-library-for-java](https://github.com/Azure/azure-sdk-for-java/tree/master/sdk/identity/azure-identity#include-the-package). But there is only a **BasicAuthenticationCredential** which implements **TokenCredential** in this [mvn](https://mvnrepository.com/artifact/com.azure/azure-storage-blob/12.12.0-beta.1). I will have a try with those implementations and give you some feedback. 

Thank you very much!

**Comment by gapra-msft** [comment]
Hi @Xiaoxin4396,

Unfortunately I can't make those types of recommendations as there are different best practices based on the specific use case. However, I am happy to answer conceptual questions regarding the storage service or sdk, and my colleagues can speak for the identity service/sdk. 

As far as I understand, a sas token will not work for your scenario as you do not want the link generated to be used by just anyone. See this page for more information about SAS [tokens](https://docs.microsoft.com/en-us/rest/api/storageservices/delegate-access-with-shared-access-signature). 

The only way to guarantee the blob is downloaded by authorized individuals is for them to provide either an identity (token credential, docs linked [here](https://docs.microsoft.com/en-us/rest/api/storageservices/authorize-with-azure-active-directory)) or a [storage shared key credential](https://docs.microsoft.com/en-us/rest/api/storageservices/authorize-with-shared-key), and make a request with those credentials. Note using a token credential/storage shared key credential requires setting a HttpHeader when making a request to storage.

**Comment by Xiaoxin4396** [comment]
Hi @gapra-msft 

Thank you and your colleagues.

If I understand yours correctly, do you mean I have to make a Http request with an identity or a storage shared key credential through Java? But I don't want to get the blob's stream through back-end and then return this stream to the front-end.

I just want to generate a authorized download link(A shared access signature (SAS)) through the java app(back-end), then the java app will return this link to the angular app(front-end) to show this link for the user, and user could download blobs by this link with authorized.

Is there any Java method, just like this code below but it could be authorized, could figure out my problem?
1. `String sasToken = blobClient.generateSas(blobServiceSasSignatureValues);`
2. `String downloadLink = blobClient.getBlobUrl()+"?"+sasToken;`

**Comment by jaschrep-msft** [comment]
Hi @Xiaoxin4396.

Returning the user a direct download link instead of passing all the blob data through your service is a desirable workflow, and SAS tokens are certainly a great mechanism to do this. However, SAS tokens are definitionally self-authorizing; whoever holds that SAS token is authorized to download that blob as long as the SAS is active. There is no way around this. It sounds like you have a concern with this, like you want the link you hand to the user be locked down to that user. At that point, you need a larger solution with Identity, rather than SAS-authorized URLs, as that is the easiest way to verify that a user trying to access the blob is the person you have authorized to access it.

**Comment by Xiaoxin4396** [comment]
Hi @jaschrep-msft 

Thanks for your support. It seems that I need to find another way to implement this.

Thank you all guys.
