### ISSUE TITLE
Receiving from Session Enabled ServiceBus Queue

### ISSUE THREAD

**Issue by paulbandler** [Azure/azure-sdk-for-java#21628]
**Query/Question**
Receiving from Session Enabled ServiceBus Queue

The requirement is to construct a configurable number of receivers from the same Service Bus Q that behave as follows:

Iterate until told to stop:

	1. Receive the next available message (i.e. next message with an unassigned Session key).
	2. Retain the lock on that session while processing that message, however long that takes
	3. Immediately when that message has completed, release the session lock.

The purpose of the above is to ensure messages with the same Session Key are processed in order, but there is no requirement for messages with the same Session Key to necessarily be processed by the same processor/receiver.

I have read all available documentation, code samples and many related GitHub issues posted here.  I appreciate that the library aims to make effective use of modern ‘reactor’ style of asynchronous programming and also provide a high level and lower level API.  However not being very familiar with Reactor 3 framework, and perhaps a little stuck in my imperative programming mindset, I am unable to determine the correct way to use the ServiceBus client library in this SDK. 

I have attempted to implement this using the high level ServiceBusProcessorClient following the code samples.  However I can see no way to explicitly release the session lock once a message has been completed, and instead it waits until the ‘try timeout’ has expired before a receiver is released to become available to handle the next session.  It is not possible to predict the message processing time with any accuracy and there is likely to be a high variation in processing time so I need to have the lock continually refreshed beyond the try timeout while the message is being processed.  My builder setup code looks like:

            processorClient = serviceBusBroker.getServiceBusClientBuilder()
                    .retryOptions(new AmqpRetryOptions().setTryTimeout(Duration.ofSeconds(30)))
                    .sessionProcessor()
                    .queueName(getQueue())
                    .maxConcurrentSessions(1)
                    .topicName(getTopic())
                    .processMessage(messageContextConsumer)
                    .processError(processError)
                    .disableAutoComplete()
                    .buildProcessorClient();
            processorClient.start();

So am completing or DLQ'ing messages directly.  It is also unclear whether a message is 'completed' when it has been DLQ'd, as after sending to DLQ the lower layers are not satisfied that the message has been processed, as I am seeing log messages such as:

[reactor-executor-1] 2021-05-18 12:58:16,179 c.a.c.a.i.ReactorReceiver - connectionId[MF_a94ee2_1621339023413] entityPath[pmb.internal.adapter.queue] linkName[session-_bba18d_1621339067055] Freeing resources due to error.
The operation did not complete within the allotted timeout of 00:00:28.9800000. The time allotted to this operation may have been a portion of a longer timeout. For more information on exception types and proper exception handling, please refer to http://go.microsoft.com/fwlink/?LinkId=761101 TrackingId:44e81b71-8f39-410f-a1ba-debb4d04f724_B16, SystemTracker:gx-zweappdsb047:Queue:pmb.internal.adapter.queue, Timestamp:2021-05-18T11:58:16 TrackingId:2122efe66b27460eb6aa6766cfb8a555_G30, SystemTracker:gateway7, Timestamp:2021-05-18T11:58:16, errorContext[NAMESPACE: gx-zweappdsb047.servicebus.windows.net, PATH: pmb.internal.adapter.queue, REFERENCE_ID: session-_bba18d_1621339067055, LINK_CREDIT: 0]

In the sample code the ReceiveSingleSessionAsyncSample seems close to what I need, except that when it completes handling a single message for the session, it needs to accept the next session again, and also have the ability to retain the session lock while running, and cancel it at the end.  It is possible to express that with this Reactor style of declarative programming?  If so, a code snippet illustrating this would be really helpful.

***Why is this not a Bug or a feature Request?***
I _think_ the capability required exists, but the style of API makes it difficult for programmers without experience of Reactor framework

**Setup (please complete the following information if applicable):**
 - OS: MacOS
 - IDE : IntelliJ
 - Version of the Library used
 7.2.1
 **Information Checklist**
 Kindly make sure that you have added all the following information above and checkoff the required fields otherwise we will treat the issuer as an incomplete report
- [ X] Query Added
- [ X] Setup information Added

**Comment by YijunXieMS** [comment]
@paulbandler Thanks for the question. Will provide you the code snippet a bit later.

**Comment by YijunXieMS** [comment]
Hi @paulbandler, a session is usually locked to continuously receive messages. This is how the `ServiceBusProcessorClient` was designed. So it might not satisfy your requirement. You might need to use the lower-level session related API. The SDK currently doesn't have an API to explicitly unlock a session. Instead a session can timeout or be closed. This is a code snippet that is close to your requirement. (I use sync API, which wraps the async API)
```java
        AmqpRetryOptions retry = new AmqpRetryOptions();
        Duration delay = Duration.ofMillis(1000);
        Duration timeout = Duration.ofMillis(60000);
        retry.setMaxRetries(3);
        retry.setDelay(delay);
        retry.setMode(AmqpRetryMode.FIXED);
        retry.setTryTimeout(timeout);
        String connectionString = System.getenv("AZURE_SERVICEBUS_CONNECTION_STRING");
        String queueName = "queue-session-7";
        ServiceBusSessionReceiverClient sessionReceiverClient = new ServiceBusClientBuilder()
            .connectionString(connectionString)
            .retryOptions(retry)
            .sessionReceiver()
            .disableAutoComplete()
            .queueName(queueName)
            .buildClient();

        while (true) {
            ServiceBusReceiverClient sessionReceiver = sessionReceiverClient.acceptNextSession();
            sessionReceiver.receiveMessages(1).forEach(message -> {
                sessionReceiver.complete(message);
                System.out.printf("processed %s, session %s%n", message.getBody(), message.getSessionId());
            });
         sessionReceiver.close();
        }
```
But the `acceptNextSession` and `close` are non-trivial operations. Using them on every message may reduce the throughput. I would suggest you allow a session to receive more messages or close it after it's receiving for a while. So you may use the `acceptNextSession` to get available sessions and allow the session receivers to run in separate threads.

**Comment by paulbandler** [comment]
@YijunXieMS Thank you for your reply and code sample.  I had already come to the same conclusion and used the synchronous API to write a very similar loop multiplied across threads.  It works _most_ of the time, but occasionally hangs for many seconds, even a minute or before receiving the next message on a session.  I'm unsure if this is an API issue or something going on the server side, perhaps the broker doesn't like the client application holding and then releasing session locks for individual messages and starves it of message flow.  I have been unable to identify a repeatable pattern.  A simple test program that iterates around sending short sequences of a few messages on one session then another will work fine on one run, then fail on another.  I _think_ I observed at least once that when it 'hangs', an independant queue browser application also indicated that the queue had no messages, even though the test program had sent them, and then a few seconds later they arrived.   If that doesn't sound possible, I wouldn't stake my life on that being what happened - I tried so many times it all became something of a blur.

Anyway, for now I have abandoned using session enabled queues and instead to preserve order of processing resorted to a single threaded receiver per queue.  While this isn't a great result from a scalability perspective, it works reliably and allows us to progress.

**Comment by ramya-rao-a** [comment]
Our apologies @paulbandler 
The bot should not have added the `no-recent-activity` label and the above comment as you have clearly gotten back to us and the bot missed to remove the `needs-author-feedback` label. We will fix the labels.

Meanwhile to your latest question on configuring the time duration until which to renew locks, you can use [maxAutoLockRenewDuration()](https://docs.microsoft.com/en-us/java/api/com.azure.messaging.servicebus.servicebusclientbuilder.servicebusprocessorclientbuilder.maxautolockrenewduration?view=azure-java-stable#com_azure_messaging_servicebus_ServiceBusClientBuilder_ServiceBusProcessorClientBuilder_maxAutoLockRenewDuration_java_time_Duration_) on the builder when creating the ServiceBusProcessorClient

```java
 ServiceBusClientBuilder builder = new ServiceBusClientBuilder()
     .connectionString(connectionString);
 ServiceBusProcessorClient processor = builder
     .processor()
     .queueName(queueName)
     .processMessage(System.out::println)
     .processError(context -> System.err.println(context.getErrorSource()))
     .maxAutoLockRenewDuration(duration)
     .buildProcessorClient();
```

@anuchandy Anything to add here?
