### ISSUE TITLE
Copy/Move entire folder at once from one location to another location within azure storage account

### ISSUE THREAD

**Issue by Syed-SnapLogic** [Azure/azure-sdk-for-java#21626]
**Query/Question**
My requirement is to copy all the files in a given folder (say folder1/) to another folder (say folder2/).
Is there a way I can do this in just one single API call?   Either by using Rest API or Azure Java SDK.

***Why is this not a Bug or a feature Request?***
If this is not existing then it could be a feature request.  Right now we are trying to copy one file at a time which results into too many API calls.  We want to minimise the number of API calls.

**Setup (please complete the following information if applicable):**
 - OS:Linux
 - IDE : IntelliJ
 - Version of the Library used: I am using azure-storage-java v8.3.0.  Not sure if a higher version of azure-storage-java or the latest version of azure-sdk-for-java can allows to copy/move files from a folder at just one call.

**Comment by gapra-msft** [comment]
Hi @Syed-SnapLogic 

Thank you for your question. 

Unfortunately there is currently no API that copies/moves an entire folder from one location to another via  a single REST call.

**Comment by gapra-msft** [comment]
Just to clarify, when you say API calls, do you mean SDK API calls or REST API calls

**Comment by Syed-SnapLogic** [comment]
Be it an SDK call or rest call, I don't want to copy or move file by file. Just say copy folder, and that should be.

**Comment by Syed-SnapLogic** [comment]
@gapra-msft , is it possible to convert this into a feature request?  And that in future versions it could be possible to copy/move at the entire folder in a single REST call.  Please let me know so I can take right action in my future development plan.
