### ISSUE TITLE
[TA-serviceBug] PII endpoint, PHI domain filter does not do filtering correctly

### ISSUE THREAD

**Issue by mssfang** [Azure/azure-sdk-for-java#21642]
Expected :********* employee with ssn *********** is using our awesome API's.
 Actual   :********* ******** with ssn *********** is using our awesome API's.

**Comment by maririos** [comment]
Is the service not identifying the `employee` as an entity? what is the category?

**Comment by mssfang** [comment]
The original text is 
`Microsoft employee with ssn 123-34-4444 is using our awesome API's.`
The PII domain with PHI should only redacted the SSN, but not `Microsoft` and `employee`.

**Comment by mssfang** [comment]
I am wrong in my last statement.

In the https://docs.microsoft.com/en-us/azure/cognitive-services/text-analytics/named-entity-types?tabs=personal#category-organization

`Microsoft` is the type of Organization, it is PHI, but `employee` is the type of PersonType, it is not PHI.

**Comment by maririos** [comment]
Ohh I see. could you file a bug with the service?
