### ISSUE TITLE
Can ServiceBusProcessorClient receive deferred message or not?

### ISSUE THREAD

**Issue by CodeLab20** [Azure/azure-sdk-for-java#21651]
I am trying to use `ServiceBusProcessorClient  `from Azure Service Bus messaging jar (azure-messaging-servicebus-7.1.0). I have seen `defer  `API on `ServiceBusReceivedMessageContext `. But did not see any API to retrieve deferred message. `ServiceBusProcessorClient  `accepts a `Consumer  ` to process message. Can that consumer receive deferred message?

**Comment by joshfree** [comment]
@hemanttanwar can you please follow up with @CodeLab20

**Comment by hemanttanwar** [comment]
@CodeLab20 As of now we do **not** provide a way to receive **deferred messages** using processor client. You would have to use lower level client 'ServiceBusReceiverClient' or 'ServiceBusReceiverAsyncClient' for this and they have exposed much more API. The processor client is very high level client and only provides a convenient API to receive and process messages. 

Here is some more detail about processor client.

https://github.com/Azure/azure-sdk-for-java/tree/master/sdk/servicebus/azure-messaging-servicebus#when-to-use-servicebusprocessorclient

**Comment by CodeLab20** [comment]
> @CodeLab20 As of now we do **not** provide a way to receive **deferred messages** using processor client. You would have to use lower level client 'ServiceBusReceiverClient' or 'ServiceBusReceiverAsyncClient' for this and they have exposed much more API. The processor client is very high level client and only provides a convenient API to receive and process messages.
> 
> Here is some more detail about processor client.
> 
> https://github.com/Azure/azure-sdk-for-java/tree/master/sdk/servicebus/azure-messaging-servicebus#when-to-use-servicebusprocessorclient

Thanks a lot for clearing the doubts. Any plan to provide this functionality in future releases?

**Comment by hemanttanwar** [comment]
Right now we do not have plan to add this API in Processor Client. It is because, we have lower level sync and Async client for any API other than receiving and processing the messages which is majority of the use cases. 
I will close this issue now. If you need further clarification, you can reopen this issue or create new one.
