### ISSUE TITLE
[FEATURE REQ] Support obtaining tokens through certificates in aad stater.

### ISSUE THREAD

**Issue by han-gao** [Azure/azure-sdk-for-java#21650]
**Is your feature request related to a problem? Please describe.**

In the Azure app registration support uploading [certificate](https://docs.microsoft.com/en-us/azure/active-directory/develop/active-directory-certificate-credentials) to replace `client-secret`, and Microsoft docs describe that [request an access token with a certificate credential](https://docs.microsoft.com/en-us/azure/active-directory/develop/v2-oauth2-auth-code-flow#request-an-access-token-with-a-certificate-credential). It would be better support certificates in `azure-spring-boot-starter-active-directory`.

**Describe the solution you'd like**

Need to investigate how to create a request with a certificate to get access token. and how the security stater supports it.

**Additional context**

The position of uploade certificate :
![image](https://user-images.githubusercontent.com/34266185/118791044-e9c67700-b8c8-11eb-996b-94578311e70e.png)

In the C# repository, I found an [sample](https://github.com/Azure-Samples/active-directory-dotnetcore-daemon-v2/tree/master/1-Call-MSGraph) of calling MSGraph with a certificate, hope it can help us.

**Related issues**

There is an issue(https://github.com/Azure/azure-sdk-for-java/issues/20338), user does not need to configure `client-secret` like above. Maybe a similar problem.

**Information Checklist**
Kindly make sure that you have added all the following information above and checkoff the required fields otherwise we will treat the issuer as an incomplete report
- [x] Description Added
- [x] Expected solution specified

**Comment by chenrujun** [comment]
Closing this issue, use this one instead: https://github.com/Azure-Samples/spring-boot-application-with-azure-active-directory/issues/1
