### ISSUE TITLE
The value for annotation attribute JmsListener.subscription must be a constant expression --- Azure servicebus

### ISSUE THREAD

**Issue by razibrath** [Azure/azure-sdk-for-java#21671]
1. When i am initialising final variable TOPIC_NAME and  SUBSCRIPTION_NAME statically during declaration there is no error .  
```
@Component
public class ClinicalServiceBusListener {
private static final String TOPIC_NAME = "topicName";

private static final String SUBSCRIPTION_NAME = "subName";

@JmsListener(destination = TOPIC_NAME, containerFactory = "topicJmsListenerContainerFactory", subscription = SUBSCRIPTION_NAME)
	public void receiveMessage(Object message) {
                   // custom code
                       }
}
```
2. When i am trying to initialize TOPIC_NAME and  SUBSCRIPTION_NAME dynamically  I am getting compile-time error like below
	- The value for annotation attribute JmsListener.destination must be a constant 
	 expression
	- The value for annotation attribute JmsListener.subscription must be a constant 
	 expression

```
@Component
public class ClinicalServiceBusListener {
private final String TOPIC_NAME ;
private final String SUBSCRIPTION_NAME;


	@Autowired
	public ClinicalServiceBusListener(@Value("${topic_name}") String topic,@Value("${sub_name}") String sub) {
	    this.TOPIC_NAME = topic;
	    this.SUBSCRIPTION_NAME= sub;
	}
@JmsListener(destination = TOPIC_NAME, containerFactory = "topicJmsListenerContainerFactory", subscription = SUBSCRIPTION_NAME)
	public void receiveMessage(Object message) {
                   // custom code
                       }
}

```

IDE used - STS
Dependency version - azure-servicebus-jms-spring-boot-starter:2.1.10
SpringBoot version- 2.4.5
Java version - 1.8

Kindly provide workaround to fix above issue . So that topic and subscription name can be initialised directly from application.properties file.

**Comment by yiliuTo** [comment]
@razibrath thanks for your reporting, we will look into it soon.

**Comment by yiliuTo** [comment]
Hi @razibrath , if you want to configure the destination / subscription value from application.properties file, you could just define a property in that file and use it in the @JmsListener directly. 
For example, add a property in application.properties like `queue.name=que001`, and in the code, use

```
@JmsListener(destination = "${queue.name}")
````

**Comment by razibrath** [comment]
Thanks.
