### ISSUE TITLE
[FEATURE REQ] Provide a class binding Azure Cloud type with Azure Authority Host in azure-core

### ISSUE THREAD

**Issue by yiliuTo** [Azure/azure-sdk-for-java#21674]
**Is your feature request related to a problem? Please describe.**
Currently azure-core provide [Configuration](https://github.com/Azure/azure-sdk-for-java/blob/master/sdk/core/azure-core/src/main/java/com/azure/core/util/Configuration.java#L104) class to enable users to set authority host from system property or environment. I wonder can azure-core provide a class that binds azure cloud with authority host? which to enable users get the authority host value according to a cloud type, and in this way they don't need to know about the authority host for each cloud.

I have tried to implement this in the spring module, however perhaps it is more suitable to be implemented on azure-core. I have seen azure-identity and azure-core-management have similar implementions as well.
Here is my pr which is in the spring module to use an enum: https://github.com/Azure/azure-sdk-for-java/pull/21613/files?file-filters%5B%5D=.java&file-filters%5B%5D=.md#diff-a2b4bcef8cfb5df1113cc3dbb59a8ff4e77eb3975053921a9e85d2aa18996f30

**Describe the solution you'd like**

   public enum AzureCloud {

    Azure("https://login.microsoftonline.com/"),
    AzureChina("https://login.chinacloudapi.cn/"),
    AzureUSGovernment("https://login.microsoftonline.us/"),
    AzureGermany("https://login.microsoftonline.de/");

    private final String authorityHost;

    AzureCloud(String authorityHost) {
        this.authorityHost = authorityHost;
    }

    public String getAuthorityHost() {
        return this.authorityHost;
    }
   }

 Then I could use AzureCloud.AzureUSGovernment.getAuthorityHost() directly.

**Information Checklist**
Kindly make sure that you have added all the following information above and checkoff the required fields otherwise we will treat the issuer as an incomplete report
- [ ] Description Added
- [ ] Expected solution specified

**Comment by yiliuTo** [comment]
Hi @alzimmermsft , I created a pr for this, what do you think of this feature and solution? And need I involve someone else in this topic?

**Comment by alzimmermsft** [comment]
Thank you for submitting a PR @yiliuTo, I'll give it a review!

**Comment by alzimmermsft** [comment]
@g2vinay left a few comments after I followed up with him as the owner of azure-identity
