### ISSUE TITLE
[FEATURE REQ] Service Bus/EventHubs tracing conform to the semantic conventions of messaging systems

### ISSUE THREAD

**Issue by srnagar** [Azure/azure-sdk-for-java#21686]
Service Bus SDK should conform and fit the above path used for other messaging systems but no rush as messaging semantic conventions may still change.

See this [reference PR](https://github.com/Azure/azure-sdk-for-java/pull/21668/files/59f4c57c89f9881353e4fd8abe2d120380b2d3dd..1bc3b689d97736393cb6741ab4d6b568b0d89e30#diff-b519c2d397b67ca55cd8e45baee5af9a09452364662ed50dce89cb6ca7a19964R272)

**Comment by lmolkova** [comment]
merging it with #21684 - messaging semantic conventions live in azure-core-tracing-opentelemetery and not  library-specific

**Comment by lmolkova** [comment]
This can now be closed - Azure messaging libs follow otel messaging semconv
