### ISSUE TITLE
Unhandled exceptions in Reactor Scheduler threads could cause hangs

### ISSUE THREAD

**Issue by mikeharder** [Azure/azure-sdk-for-java#21693]
Exceptions like OutOfMemoryError are handled differently by the default Reactor schedulers. Instead of terminating the Flux, the Flux will hang and the exception is only sent to the thread's `uncaughtExceptionHandler` and the Reactor `Schedulers.onHandleError`.

reactor/reactor-core#2521

https://github.com/reactor/reactor-core/blob/84e921fbfd84754d519b5e3c78262495dcf48b87/reactor-core/src/main/java/reactor/core/Exceptions.java#L443

This issue was originally reported against the perf framework in #21629 and fixed in #21690.

This issue could also impact any SDK code which uses the default Reactor schedulers.  Examples:

https://github.com/Azure/azure-sdk-for-java/search?q=boundedelastic

**Comment by alzimmermsft** [comment]
It should be investigated whether it be possible to use the global [`Hooks`](https://projectreactor.io/docs/core/release/api/reactor/core/publisher/Hooks.html) to have it capture the exception and propagating the error more appropriately.

Additionally, could this be done on a per-call, using reactive-chain operators/side-affects, so that the global state isn't polluted?

**Comment by alzimmermsft** [comment]
I was playing around with a simple replication of this, when I changed the `doOnNext` to a `flatMap` or `map` the exception propagates correctly.

**Comment by kushagraThapar** [comment]
@mikeharder / @alzimmermsft  wondering if we ever found a solution to this problem?

**Comment by kushagraThapar** [comment]
FYI, the only way to catch it is using this code block:


```
Hooks.onNextError((throwable, o) -> {
            if (throwable instanceof Error) {
                logger.info("It is a java.lang.Error, can't do much");
                System.exit(99);
            }
            return throwable;
        });
```
