### ISSUE TITLE
I am getting this Error while I am trying to connect Cosmosdb with Azure Data bricks using Azure Cosmos DB OLTP Spark 3 connector

### ISSUE THREAD

**Issue by ksubhakar** [Azure/azure-sdk-for-java#21708]
I am getting this error while I am trying to connect with cosmos Db from Azure Data Bricks using Azure Cosmos DB OLTP Spark 3 connector

IllegalArgumentException                  Traceback (most recent call last)
<command-3630915717538493> in <module>
     10 
     11 # Connect via azure-cosmosdb-spark to create Spark DataFrame
---> 12 flights = spark.read.format(
     13     "cosmos.oltp").options(**readConfig).load()
     14 print(flights)

/databricks/spark/python/pyspark/sql/readwriter.py in load(self, path, format, schema, **options)
    208             return self._df(self._jreader.load(self._spark._sc._jvm.PythonUtils.toSeq(path)))
    209         else:
--> 210             return self._df(self._jreader.load())
    211 
    212     def json(self, path, schema=None, primitivesAsString=None, prefersDecimal=None,

/databricks/spark/python/lib/py4j-0.10.9-src.zip/py4j/java_gateway.py in __call__(self, *args)
   1302 
   1303         answer = self.gateway_client.send_command(command)
-> 1304         return_value = get_return_value(
   1305             answer, self.gateway_client, self.target_id, self.name)
   1306 

/databricks/spark/python/pyspark/sql/utils.py in deco(*a, **kw)
    114                 # Hide where the exception came from that shows a non-Pythonic
    115                 # JVM exception message.
--> 116                 raise converted from None
    117             else:
    118                 raise

IllegalArgumentException: Input byte array has incorrect ending byte at 16

**Comment by joshfree** [comment]
@kushagraThapar PTAL

**Comment by kushagraThapar** [comment]
@moderakh  - please take a look at this issue.

**Comment by moderakh** [comment]
@ksubhakar could you provide sample code how to repro this?

also what is the exact version of the spark connector you are using?

**Comment by ksubhakar** [comment]
Some Configuration Error's on my end, I got them fixed. Thank you
