### ISSUE TITLE
Move all the Spring related samples to Azure Samples

### ISSUE THREAD

**Issue by saragluna** [Azure/azure-sdk-for-java#21745]
We have several sample projects under the [sdk/spring](https://github.com/Azure/azure-sdk-for-java/tree/master/sdk/spring/azure-spring-boot-samples) directory; we should move them to the [Azure Samples](https://github.com/Azure-Samples). This will solve the problems below:
- Users need to build a beta version first before running the samples directly on the master branch.
- This repo is not the official site for hosting Azure samples.

**Comment by stliu** [comment]
@seanli1988  FYI

**Comment by backwind1233** [comment]
relate to : https://github.com/Azure/azure-sdk-for-java/issues/20718
