### ISSUE TITLE
FormRecognizer Sample 401s

### ISSUE THREAD

**Issue by chandygithub** [Azure/azure-sdk-for-java#21744]
Hi @samvaity I am using azure sdk for java for the FormRecognizer,3.1.0-beta.4. I ran a Standalone java client.
https://github.com/Azure/azure-sdk-for-java/blob/master/sdk/formrecognizer/azure-ai-formrecognizer/src/samples/java/com/azure/ai/formrecognizer/RecognizeInvoicesFromUrl.java
just used the FormRecognizer resource endpoint and Key,which i have created,in the above code
Got Error
code":"401","message":"Access denied due to invalid subscription key or wrong API endpoint. Make sure to provide a valid key for an active subscription and use a correct regional API endpoint for your resource."}.
Btwn the FormRecognizer resource endpoint is valid and works from https://fott-preview.azurewebsites.net/.
anything else?

**Comment by mssfang** [comment]
Hi, @chandygithub are you using 3.1.0-beta.4 version? We havn't release the version. Can you check which version of SDK are you testing at?

**Comment by samvaity** [comment]
Hey @chandygithub, thanks for reporting this. 
Although could you confirm the Formecognizer SDK version you are using.
Also, if it helps you could use the 3.1.0-beta.3 available version here https://mvnrepository.com/artifact/com.azure/azure-ai-formrecognizer for that same example.

**Comment by chandygithub** [comment]
Hi @msfang ,sorry it was 3.1.0-beta.3.
![azure ai](https://user-images.githubusercontent.com/32098554/119436295-83fb4480-bd39-11eb-9d2a-2f6f9bd02d54.png)
The code is ditto copy of handler @samvaity  in GH
https://github.com/Azure/azure-sdk-for-java/blob/master/sdk/formrecognizer/azure-ai-formrecognizer/src/samples/java/com/azure/ai/formrecognizer/RecognizeInvoicesFromUrl.java

**![Error Screenshot 2021-05-25 040117](https://user-images.githubusercontent.com/32098554/119437622-29171c80-bd3c-11eb-9c39-14cecf7e9dfc.png)**
import com.azure.ai.formrecognizer.models.FieldValueType;
import com.azure.ai.formrecognizer.models.FormField;
import com.azure.ai.formrecognizer.models.FormRecognizerOperationResult;
import com.azure.ai.formrecognizer.models.RecognizedForm;
import com.azure.core.credential.AzureKeyCredential;
import com.azure.core.util.polling.SyncPoller;

import java.io.IOException;
import java.time.LocalDate;
import java.util.List;
import java.util.Map;


public class Testocr {

    public static void main(String[] args) throws IOException {


        //FormRecognizerAsyncClient client = new FormRecognizerClientBuilder()
        FormRecognizerClient client = new FormRecognizerClientBuilder()
        .credential(new AzureKeyCredential("{7934dcf1a7034d4081e8fe6a2bed9404}"))
        .endpoint("https://chandyocr.cognitiveservices.azure.com")
        .buildClient();
        //.buildAsyncClient();
        //System.out.println("cognitive url connected "+client);

        String invoiceUrl =
        "https://raw.githubusercontent.com/Azure/azure-sdk-for-python/master/sdk/formrecognizer/"
            + "azure-ai-formrecognizer/samples/sample_forms/forms/sample_invoice.jpg";
    SyncPoller<FormRecognizerOperationResult, List<RecognizedForm>> recognizeInvoicesPoller
        = client.beginRecognizeInvoicesFromUrl(invoiceUrl);

    List<RecognizedForm> recognizedInvoices = recognizeInvoicesPoller.getFinalResult();

    for (int i = 0; i < recognizedInvoices.size(); i++) {
        RecognizedForm recognizedInvoice = recognizedInvoices.get(i);
        Map<String, FormField> recognizedFields = recognizedInvoice.getFields();
        System.out.printf("----------- Recognized invoice info for page %d -----------%n", i);
        FormField vendorNameField = recognizedFields.get("VendorName");
        if (vendorNameField != null) {
            if (FieldValueType.STRING == vendorNameField.getValue().getValueType()) {
                String merchantName = vendorNameField.getValue().asString();
                System.out.printf("Vendor Name: %s, confidence: %.2f%n",
                    merchantName, vendorNameField.getConfidence());
            }
        }

        FormField vendorAddressField = recognizedFields.get("VendorAddress");
        if (vendorAddressField != null) {
            if (FieldValueType.STRING == vendorAddressField.getValue().getValueType()) {
                String merchantAddress = vendorAddressField.getValue().asString();
                System.out.printf("Vendor address: %s, confidence: %.2f%n",
                    merchantAddress, vendorAddressField.getConfidence());
            }
        }

        FormField customerNameField = recognizedFields.get("CustomerName");
        if (customerNameField != null) {
            if (FieldValueType.STRING == customerNameField.getValue().getValueType()) {
                String merchantAddress = customerNameField.getValue().asString();
                System.out.printf("Customer Name: %s, confidence: %.2f%n",
                    merchantAddress, customerNameField.getConfidence());
            }
        }

        FormField customerAddressRecipientField = recognizedFields.get("CustomerAddressRecipient");
        if (customerAddressRecipientField != null) {
            if (FieldValueType.STRING == customerAddressRecipientField.getValue().getValueType()) {
                String customerAddr = customerAddressRecipientField.getValue().asString();
                System.out.printf("Customer Address Recipient: %s, confidence: %.2f%n",
                    customerAddr, customerAddressRecipientField.getConfidence());
            }
        }

        FormField invoiceIdField = recognizedFields.get("InvoiceId");
        if (invoiceIdField != null) {
            if (FieldValueType.STRING == invoiceIdField.getValue().getValueType()) {
                String invoiceId = invoiceIdField.getValue().asString();
                System.out.printf("Invoice Id: %s, confidence: %.2f%n",
                    invoiceId, invoiceIdField.getConfidence());
            }
        }

        FormField invoiceDateField = recognizedFields.get("InvoiceDate");
        if (customerNameField != null) {
            if (FieldValueType.DATE == invoiceDateField.getValue().getValueType()) {
                LocalDate invoiceDate = invoiceDateField.getValue().asDate();
                System.out.printf("Invoice Date: %s, confidence: %.2f%n",
                    invoiceDate, invoiceDateField.getConfidence());
            }
        }

        FormField invoiceTotalField = recognizedFields.get("InvoiceTotal");
        if (customerAddressRecipientField != null) {
            if (FieldValueType.FLOAT == invoiceTotalField.getValue().getValueType()) {
                Float invoiceTotal = invoiceTotalField.getValue().asFloat();
                System.out.printf("Invoice Total: %.2f, confidence: %.2f%n",
                    invoiceTotal, invoiceTotalField.getConfidence());
            }
        }

        FormField invoiceItemsField = recognizedFields.get("Items");
        if (invoiceItemsField != null) {
            System.out.printf("Invoice Items: %n");
            if (FieldValueType.LIST == invoiceItemsField.getValue().getValueType()) {
                List<FormField> invoiceItems = invoiceItemsField.getValue().asList();
                invoiceItems.stream()
                    .filter(invoiceItem -> FieldValueType.MAP == invoiceItem.getValue().getValueType())
                    .map(formField -> formField.getValue().asMap())
                    .forEach(formFieldMap -> formFieldMap.forEach((key, formField) -> {
                        // See a full list of fields found on an invoice here:
                        // https://aka.ms/formrecognizer/invoicefields
                        if ("Description".equals(key)) {
                            if (FieldValueType.STRING == formField.getValue().getValueType()) {
                                String name = formField.getValue().asString();
                                System.out.printf("Description: %s, confidence: %.2fs%n",
                                    name, formField.getConfidence());
                            }
                        }
                        if ("Quantity".equals(key)) {
                            if (FieldValueType.FLOAT == formField.getValue().getValueType()) {
                                Float quantity = formField.getValue().asFloat();
                                System.out.printf("Quantity: %f, confidence: %.2f%n",
                                    quantity, formField.getConfidence());
                            }
                        }
                        if ("UnitPrice".equals(key)) {
                            if (FieldValueType.FLOAT == formField.getValue().getValueType()) {
                                Float unitPrice = formField.getValue().asFloat();
                                System.out.printf("Unit Price: %f, confidence: %.2f%n",
                                    unitPrice, formField.getConfidence());
                            }
                        }
                        if ("ProductCode".equals(key)) {
                            if (FieldValueType.FLOAT == formField.getValue().getValueType()) {
                                Float productCode = formField.getValue().asFloat();
                                System.out.printf("Product Code: %f, confidence: %.2f%n",
                                    productCode, formField.getConfidence());
                            }
                        }
                    }));
            }
        }
    }
   }
  }

**Comment by mssfang** [comment]
Hi,  @chandygithub Thanks for the reply. 
First of all. It is dangerous to post the credential info here. I would recommend editing the content by removing the credential info.
The credential key should not include the open and close bracket.
 .credential(new AzureKeyCredential("1111111111111"))

**Comment by chandygithub** [comment]
Hi @mssfang ,Thanks for the immediate reply
between i assume those were dummy credentials, anyway removed it.
The code works now
So the client code and the Cognitive cloud url has to be in the same region?

**Comment by mssfang** [comment]
@chandygithub Good to hear that resolve it. 

You don't need to put the client code (I assumed you referred to the SDK we developed) in the same region as the Cognitive cloud url(I assumed you referred to the 'endpoint')

**Comment by chandygithub** [comment]
> 
> 
> @chandygithub Good to hear that resolve it.
> 
> You don't need to put the client code (I assumed you referred to the SDK we developed) in the same region as the Cognitive cloud url(I assumed you referred to the 'endpoint')


I mean i have created a cognitive resource endpoint say example http://xyzabcocr.cognitiveservices.azure.com in a azure region say Central India region
i have a client code(Testocr.java) which seeks to call the above endpoint, and this is deployed in a azure cloud of West India Region.In that case  facing issue , 

whereas if tcognitive resource endpoint and the client code ,in the same region it works,

**Comment by chandygithub** [comment]
> 
> 
> > @chandygithub Good to hear that resolve it.
> > You don't need to put the client code (I assumed you referred to the SDK we developed) in the same region as the Cognitive cloud url(I assumed you referred to the 'endpoint')
> 
> I mean i have created a cognitive resource endpoint say example http://xyzabcocr.cognitiveservices.azure.com in a azure location,say Central India region
> i have a client code(Testocr.java) which seeks to call the above endpoint, and this is deployed in a azure cloud Location of West India Region.In that case facing issue ,
> 
> whereas if tcognitive resource endpoint and the client code ,in the same region it works,

@mssfang , sorry it works, a  typo in key

**Comment by samvaity** [comment]
Hey @chandygithub, good to know that the code works and thank you for letting us know about the resolution.
