### ISSUE TITLE
Compatibility with SpringBoot2.5

### ISSUE THREAD

**Issue by blacelle** [Azure/azure-sdk-for-java#21754]
**Is your feature request related to a problem? Please describe.**
It appears com.azure.spring.autoconfigure.aad.UserPrincipalManager is not compatible with SpringBoot2.5 + NimbusJoseJwt 9.9.3

I use to force Nimbus Jose JWT to 8.21.1 to be compatible with SpringBoot + AzureSpringBoot, but SpringBoot2.5 requires an upgrade of NimbusJoseJwt.

**Describe the solution you'd like**
I currently get stack looking like:

	java.lang.ClassCastException: class com.nimbusds.jose.shaded.json.JSONArray cannot be cast to class
	net.minidev.json.JSONArray (com.nimbusds.jose.shaded.json.JSONArray and net.minidev.json.JSONArray are in unnamed
	module of loader org.springframework.boot.loader.LaunchedURLClassLoader @56cdfb3b)
	at
	com.azure.spring.autoconfigure.aad.UserPrincipalManager.lambda$buildUserPrincipal$1(UserPrincipalManager.java:152)
	at java.base/java.util.Optional.map(Optional.java:265)
	at com.azure.spring.autoconfigure.aad.UserPrincipalManager.buildUserPrincipal(UserPrincipalManager.java:152)

during authentication

**Comment by saragluna** [comment]
@chenrujun could you take a look at this?

**Comment by chenrujun** [comment]
Hi, @blacelle.
Thanks for reaching out.
Now spring-boot:2.5.0 is not supported.
Could you please use spring-boot:2.4.5 instead?

My current plan is to support spring-boot:2.5.0 before 2021-06-30.
Related issue: https://github.com/Azure/azure-sdk-for-java/issues/21622

**Comment by chenrujun** [comment]
Please check #21962 if you are waiting the SpringBoot2.5 compatible version.
