### ISSUE TITLE
[FEATURE REQ] Enhance metrics for Azure Spring Event Hubs

### ISSUE THREAD

**Issue by saragluna** [Azure/azure-sdk-for-java#21764]
### Context
We plan to expose metrics for Azure Spring Event Hubs related libraries to enable developers to view metrics about connection, messages states.

Spring Event Hubs metrics components: 

**Prefix**: `eventhubs`.

| Metric Name | Type | Tag | Description |
|--|--|--|--|
| connection.active | Gauge | eh namespace | The number of active connection. |
| connection.opened | Gauge | eh namespace | The number of open connection. |
| connection.closed | Gauge | eh namespace | The number of closed connection. |
| requests | Timer | eh namespace | Requests sent by client. |
| response.successes | Timer | eh namespace | Successful responses received. |
| response.errors | Timer | eh namespace | Errored responses received. |
| request.queue.latency | Timer | eh namespace | Average request queue latency waiting for request to be sent to broker. |
| request.queue.count | Timer | eh namespace | Number of requests in queue waiting to be sent to broker. |
| request.rtt | Timer | eh namespace | Average request latency / round-trip-time to broker and back.|
| consumer.poll.latency | Timer | eh namespace | The time it takes poll() to return a new message to the application.|

For the SCS binder:

**Prefix**: `spring.cloud.stream.binder.eventhubs`.
| Metric Name | Type | Tag | Description |
|--|--|--|--|
| offset | Gauge | EventHub, ConsumerGroup | Unconsumed messages for a particular group and event hub |

Reference of Kafka: https://cwiki.apache.org/confluence/display/KAFKA/KIP-714:+Client+metrics+and+observability#KIP714:Clientmetricsandobservability-Clientmetricsandmetriclabels

### Next Step
To support Spring Event Hubs metrics, currently we need the support from Event Hubs SDK to enable and expose metrics APIs. Tracked in https://github.com/Azure/azure-sdk-for-java/issues/25605

**Comment by yiliuTo** [comment]
https://cwiki.apache.org/confluence/display/KAFKA/KIP-714:+Client+metrics+and+observability#KIP714:Clientmetricsandobservability-Clientmetricsandmetriclabels

**Prefix**: `eventhubs`.

| Metric Name | Type | Tag | Description |
|--|--|--|--|
| connection.active | Gauge | eh namespace | The number of active connection. |
| connection.opened | Gauge | eh namespace | The number of open connection. |
| connection.closed | Gauge | eh namespace | The number of closed connection. |
| requests | Timer | eh namespace | Requests sent by client. |
| response.successes | Timer | eh namespace | Successful responses received. |
| response.errors | Timer | eh namespace | Errored responses received. |
| request.queue.latency | Timer | eh namespace | Average request queue latency waiting for request to be sent to broker. |
| request.queue.count | Timer | eh namespace | Number of requests in queue waiting to be sent to broker. |
| request.rtt | Timer | eh namespace | Average request latency / round-trip-time to broker and back.|
| consumer.poll.latency | Timer | eh namespace | The time it takes poll() to return a new message to the application.|

For the SCS binder:

**Prefix**: `spring.cloud.stream.binder.eventhubs`.
| Metric Name | Type | Tag | Description |
|--|--|--|--|
| offset | Gauge | EventHub, ConsumerGroup | Unconsumed messages for a particular group and event hub |

**Comment by saragluna** [comment]
Link https://github.com/Azure/azure-sdk-for-java/issues/19391

**Comment by cykl** [comment]
Hey @saragluna 

How do you plan to compute offset? Will those metrics be available to non Spring users? (i.e. sdk compute metrics and Azure Spring Event Hubs bind them to Spring / Micrometer)

**Comment by saragluna** [comment]
@cykl here's the issue used to track supporting metrics in AMQP libraries https://github.com/Azure/azure-sdk-for-java/issues/25605.
