### ISSUE TITLE
[FEATURE REQ] Enhance tracing for Azure Spring messaging components

### ISSUE THREAD

**Issue by saragluna** [Azure/azure-sdk-for-java#21760]
### Context
For Spring applications, there is already good tracing support by [Spring Cloud Sleuth](https://docs.spring.io/spring-cloud-sleuth/docs/3.0.3/reference/htmlsingle/#getting-started-introducing-spring-cloud-sleuth), the tracing information of your request and messages will be recorded successfully, also complete trace information is able to export.

Unfortunately, when using the Azure Spring Starter and Spring Cloud Sleuth Starter together, such as azure-spring-boot-starter-service-bus and spring-cloud-starter-sleuth, only the Spring level trace information can be recorded, the activities of Azure SDK will not be recorded.

### Goal
We should make sure the tracing with Azure Spring messaging components can work correctly:
- [ ] The raw messaging SDK client can work with Sleuth.
- [ ] The Spring Integration projects can work with Sleuth.
- [ ] The Spring Cloud Stream projects can work with Sleuth.

### Reference
See also https://github.com/Azure/azure-sdk-for-java/issues/21969.

**Comment by stliu** [comment]
things to do:

1. we need to know how spring sleuth support spring-integration / cloud stream
2. define this feature scope, update description
