### ISSUE TITLE
[BUG] Key Vault Keys encryption tests fail with "missing provider" on CI pipelines.

### ISSUE THREAD

**Issue by vcolin7** [Azure/azure-sdk-for-java#21776]
**Describe the bug**
Originally reported [here](https://github.com/Azure/azure-sdk-for-java/issues/21677).

Tests [`signVerifyEc()`](https://github.com/Azure/azure-sdk-for-java/blob/f49851a88d05b64958d213500b97a883ac72a95f/sdk/keyvault/azure-security-keyvault-keys/src/test/java/com/azure/security/keyvault/keys/cryptography/CryptographyClientTest.java#L204) and [`signVerifyEcLocal()`](https://github.com/Azure/azure-sdk-for-java/blob/f49851a88d05b64958d213500b97a883ac72a95f/sdk/keyvault/azure-security-keyvault-keys/src/test/java/com/azure/security/keyvault/keys/cryptography/CryptographyClientTest.java#L249) from the [`CryptographyClientTest`](https://github.com/Azure/azure-sdk-for-java/blob/azure-security-keyvault-keys_4.3.0-beta.8/sdk/keyvault/azure-security-keyvault-keys/src/test/java/com/azure/security/keyvault/keys/cryptography/CryptographyClientTest.java) class in Key Vault Keys fail when ran on CI pipelines for all Java 11 provisioned VMs.

[See first pipeline run where this occurred.](https://dev.azure.com/azure-sdk/public/_build/results?buildId=899455&view=results)

[Here's a healthy pipeline run.](https://dev.azure.com/azure-sdk/public/_build/results?buildId=897569&view=results)

The required Java Security provider is `SunEC` in this case, which should be included by default in OpenJDK for Java 11 distributions. [Reference](https://github.com/AdoptOpenJDK/openjdk-jdk11/blob/master/src/jdk.crypto.ec/share/classes/sun/security/ec/SunEC.java).

If run locally using the version of AdoptOpenJDK I have (`11.0.6`), the following providers will be listed when calling `Security.getProviders()`:

- SUN
- SunRsaSign
- SunEC
- SunJSSE
- SunJCE
- SunJGSS
- SunSASL
- XMLDSig
- SunPCSC
- JdkLDAP
- JdkSASL
- SunMSCAPI
- SunPKCS11

But when run on the aforementioned CI pipelines, a call to `Security.getProviders()` produces the following list:

- SUN
- SunRsaSign
- SunJSSE
- SunJCE

It is possible that there was some kind of setup missing on the OS images to include more providers like the ones listed first.

***Exception or Stack Trace***
```bash
java.lang.IllegalArgumentException: missing provider
	at java.base/sun.security.jca.GetInstance.getService(GetInstance.java:96)
	at java.base/sun.security.jca.GetInstance.getInstance(GetInstance.java:218)
	at java.base/java.security.KeyPairGenerator.getInstance(KeyPairGenerator.java:340)
	at com.azure.security.keyvault.keys@4.3.0-beta.9/com.azure.security.keyvault.keys.cryptography.CryptographyClientTest.signVerifyEcLocal(CryptographyClientTest.java:265)
```

**To Reproduce**
- Run a CI pipeline where the aforementioned tests from Key Vault's `CryptographyClientTest` are ran.

***Code Snippet***
Add the code snippet that causes the issue.

**Expected behavior**
CI pipelines should run all tests without issue.

**Setup (please complete the following information):**
- OS:
    - [Ubuntu 18.04.5 LTS](https://github.com/actions/virtual-environments/blob/ubuntu18/20210517.1/images/linux/Ubuntu1804-README.md)
      Version: 20210517.1
        - Adopt OpenJDK 11.0.11+9
        - Maven 3.8.1
    - [Microsoft Windows Server 2019 10.0.17763 Datacenter](https://github.com/actions/virtual-environments/blob/win19/20210516.0/images/win/Windows2019-Readme.md)
       Version: 20210516.0
        - Adopt OpenJDK 11.0.11+9
        - Maven 3.8.1
 - IDE : N/A
 - Version of the Library used: Key Vault Keys 4.3.0-beta.9 (Unreleased)

**Additional context**
It looks like runs with the previous version of Adopt OpenJDK did not present this issue, as seen in [this healthy run from before](https://dev.azure.com/azure-sdk/internal/_build/results?buildId=900784&view=logs&j=6b6453ff-b717-53e4-9b68-8cedd66e23e4&t=e5e33f6f-2a5f-4d9e-836b-bbb441e85d59).

The OS images used there are the following:

- [Ubuntu 18.04.5 LTS](https://github.com/actions/virtual-environments/blob/ubuntu18/20210412.1/images/linux/Ubuntu1804-README.md)
   Version: 20210517.1
    - Adopt OpenJDK 11.0.10+9
    - Maven 3.6.3
- [Microsoft Windows Server 2019 10.0.17763 Datacenter](https://github.com/actions/virtual-environments/blob/win19/20210411.1/images/win/Windows2019-Readme.md)
   Version: 20210516.0
     - Adopt OpenJDK 11.0.10+9
     - Maven 3.6.3

Here is some nore info that might be of interest:
- (GitHub) [Issue using security providers in OpenJDK](https://github.com/AdoptOpenJDK/IcedTea-Web/issues/365)
- (StackOverflow) [Java AES: No installed provider supports this key: javax.crypto.spec.SecretKeySpec](https://stackoverflow.com/a/32117505/4967034)
- (StackOverflow) [Keytool EC KeyPairGenerator not available](https://stackoverflow.com/a/40959764/4967034)
- [How to use ECC with OpenJDK](http://armoredbarista.blogspot.com/2013/10/how-to-use-ecc-with-openjdk.html)

**Information Checklist**
Kindly make sure that you have added all the following information above and checkoff the required fields otherwise we will treat the issuer as an incomplete report
- [x] Bug Description Added
- [x] Repro Steps Added
- [x] Setup information Added

**Comment by mikeharder** [comment]
@mitchdenny

**Comment by mikeharder** [comment]
I tried the docker containers for both AdoptOpenJDK versions, and they both include the SunEC crypto provider.  So this appears to be specific to our agents, not something that changed in AdoptOpenJDK itself.

```
$ docker run -it --rm adoptopenjdk:11.0.11_9-jdk-hotspot

|  Welcome to JShell -- Version 11.0.11

jshell> java.security.Security.getProviders()
$1 ==> Provider[12] {​​​​​​​​​ SUN version 11, SunRsaSign version 11, SunEC version 11, SunJSSE version 11, SunJCE version 11, SunJGSS version 11, SunSASL version 11, XMLDSig version 11, SunPCSC version 11, JdkLDAP version 11, JdkSASL version 11, SunPKCS11 version 11 }​​​​​​​​​
```

``` 
$ docker run -it --rm adoptopenjdk:11.0.10_9-jdk-hotspot

|  Welcome to JShell -- Version 11.0.10
 

jshell> java.security.Security.getProviders()
$1 ==> Provider[12] {​​​​​ SUN version 11, SunRsaSign version 11, SunEC version 11, SunJSSE version 11, SunJCE version 11, SunJGSS version 11, SunSASL version 11, XMLDSig version 11, SunPCSC version 11, JdkLDAP version 11, JdkSASL version 11, SunPKCS11 version 11 }​​​​​
```
