### ISSUE TITLE
[BUG] Cosmos Spark 3 connector query plan is invalid when trying to use startswith in a filter.

### ISSUE THREAD

**Issue by charlesk-kr** [Azure/azure-sdk-for-java#21771]
The query plan created for filters that use the startswith functionality has syntax errors (i.e. missing a comma between the attribute/column name and the string parameter).  Details from python notebook example show below:

-------------------------------------------------
filteredDff = dff.filter(dff.field1.startswith("-"))
filteredDff.explain()
-------------------------------------------------
filteredDff.sql.dataframe.DataFrame = [id: string, field1: string]
== Physical Plan ==
*(1) Project [id#1072, field1#1073]
+- BatchScan[id#1072, field1#1073] Cosmos ItemsScan: DB.container1
 - Cosmos Query: SELECT * FROM r WHERE NOT(IS_NULL(r['currentBalance'])) AND **STARTSWITH(r['field1']@param0)**
 > param: @param0 = -
-------------------------------------------------

**Comment by joshfree** [comment]
@kushagraThapar PTAL

**Comment by kushagraThapar** [comment]
@moderakh  - please take a look at this issue.

**Comment by moderakh** [comment]
@charlesk-kr could you provide the full code for repro-ing this?

**Comment by moderakh** [comment]
@charlesk-kr thanks for reporting, this I can repro this locally, nothing else needed from your side. we will fix this in the next release.

**Comment by charlesk-kr** [comment]
Here is a simple notebook to reproduce the problem:

`
from pyspark.sql.types import StructType, StructField, StringType

connectionConfig = {
  "spark.cosmos.accountEndpoint" : "https://DBNAME.documents.azure.com:443/",
  "spark.cosmos.accountKey": "DBKEY",
  "spark.cosmos.preferredRegionsList" : "East US 2",
  "spark.cosmos.database" : "database",
  "spark.cosmos.container" : "container1"
}

cosmos=StructType([StructField("id",StringType(),True),StructField("field1",StringType(),True))

rawDff = spark.read.format("cosmos.oltp").schema(cosmos).options(**connectionConfig).load()

filterDff = rawDff.filter(rawDff.field1.startswith('-')
display(filterDff)
`
The last line will fail due to the syntax error in query.

**Comment by moderakh** [comment]
thanks I can repro this locally @charlesk-kr

**Comment by moderakh** [comment]
bugfix PR: https://github.com/Azure/azure-sdk-for-java/pull/21783
