### ISSUE TITLE
azure-mgmt-eventhub docs CI build failing

### ISSUE THREAD

**Issue by danieljurek** [Azure/azure-sdk-for-java#21774]
Internal issue describing error and tracking -- https://ceapex.visualstudio.com/Engineering/_workitems/edit/430510

This issue was found after removing another package, it is described in the discussion section

**Comment by alzimmermsft** [comment]
Closing as this has been fixed, link to docs:

https://review.learn.microsoft.com/java/api/overview/azure/eventhubs/management/management-eventhubs(deprecated)?view=azure-java-stable&branch=main
