### ISSUE TITLE
Java Long Running Tests Provisioning Script

### ISSUE THREAD

**Issue by YijunXieMS** [Azure/azure-sdk-for-java#21843]
We have the SB and EH long running test command line applications. Now we need to write driver program to kick off the test to run in the container environment. It should do the following tasks.

1. Feed parameters to the test command line applications to instantiate different test cases.
2. Create docker images and push to Azure Container Registry
3. Provision test resources using Azure Container Instances or AKS and start the container with images from ACR.
4. Gather test results.
5. Remove the test resources.

The driver program needs to be runnable in windows, Mac and linux machine because developers may use different OS for daily development. It can be written in python, Java or any other scripts. ARM can also be used.

**Comment by jongio** [comment]
@v-xuto - Please hold while we discuss.

**Comment by jongio** [comment]
@conniey

**Comment by jongio** [comment]
Hold for now. This is being discussed and owned by @kurtzeborn's team.
