### ISSUE TITLE
checkExistenceById get 405 if resource exist

### ISSUE THREAD

**Issue by mmzh** [Azure/azure-sdk-for-java#2184]
Hi forks

I got 405(method not allow) error when run the following code if resource has been found, but no error when resource not exist, so the checkExistenceById return either false or 405 error:
/****************************************/
if (!azure.genericResources().checkExistenceById(id)) return null;
/***************************************/

can someone check this for me?

Thanks

Ming

**Comment by vhvb1989** [comment]
Hello @mmzh
Do you still need help with this?  I am sorry there was not any reply here. 
Please, if this is still an issue, can you provide more context about what you are doing?

Note: As part of repository cleaning effort, this issue will be closed by Sep 12 if no response is received from submitter and/or not further action is required.
