### ISSUE TITLE
[BUG] ServiceBusSenderClient doesn't shut down after close

### ISSUE THREAD

**Issue by ecmcn** [Azure/azure-sdk-for-java#21852]
Running ServiceBusSenderClient sample code that connects to a topic, sends a message and then closes the connection, the app doesn't terminate and there are a number of threads still running.

com.azure:azure-core:1.16.0
com.azure:azure-messaging-servicebus:7.2.1
macOS 11.3.1. 
Java 8 and 16.

----------------------------------------------
import java.util.*;
import com.azure.messaging.servicebus.*;

public class App {

    public static void main(String[] args) {
        String connectionString = "Endpoint=...";
        String topic = "session.control";
        ServiceBusSenderClient sender = new ServiceBusClientBuilder()
            .connectionString(connectionString)
            .sender()
            .topicName(topic)
            .buildClient();

        sender.sendMessage(new ServiceBusMessage("test message"));
        sender.close();
        System.out.println("End close");
        try { Thread.sleep(10000); } catch (Exception e) {}
        printRunningThreads();
        System.out.println("End main");
    }

    private static void printRunningThreads() {
        for (Thread t : Thread.getAllStackTraces().keySet()) {
            String name = t.getName();
            Thread.State state = t.getState();
            int priority = t.getPriority();
            String type = t.isDaemon() ? "Daemon" : "Normal";
            System.out.printf("%-20s \t %s \t %d \t %s\n", name, state, priority, type);
        }
    }
}

----------------------------------------------
14:27:40.283 [main] INFO  c.a.m.s.i.ServiceBusConnectionProcessor - namespace[] entityPath[my_namespace]: Setting next AMQP channel.
14:27:40.285 [main] INFO  c.a.m.s.i.ServiceBusConnectionProcessor - namespace[] entityPath[my_namespace]: Next AMQP channel received, updating 0 current subscribers
14:27:40.287 [main] INFO  c.a.m.s.ServiceBusClientBuilder - # of open clients with shared connection: 1
14:27:40.422 [main] INFO  c.a.c.a.i.ReactorConnection - connectionId[MF_c7e159_1621978060256]: Creating and starting connection to my_namespace:5671
14:27:40.436 [main] INFO  c.a.c.a.i.ReactorExecutor - connectionId[MF_c7e159_1621978060256], message[Starting reactor.]
14:27:40.443 [reactor-executor-1] INFO  c.a.c.a.i.handler.ConnectionHandler - onConnectionInit connectionId[MF_c7e159_1621978060256] hostname[my_namespace] amqpHostname[my_namespace]
14:27:40.444 [reactor-executor-1] INFO  c.a.c.a.i.handler.ReactorHandler - connectionId[MF_c7e159_1621978060256] reactor.onReactorInit
14:27:40.444 [reactor-executor-1] INFO  c.a.c.a.i.handler.ConnectionHandler - onConnectionLocalOpen connectionId[MF_c7e159_1621978060256] hostname[my_namespace] errorCondition[null] errorDescription[null]
14:27:40.495 [reactor-executor-1] INFO  c.a.c.a.i.handler.ConnectionHandler - onConnectionBound connectionId[MF_c7e159_1621978060256] hostname[my_namespace] peerDetails[my_namespace:5671]
14:27:40.878 [reactor-executor-1] INFO  c.a.c.a.i.handler.ConnectionHandler - onConnectionRemoteOpen hostname[my_namespace], connectionId[MF_c7e159_1621978060256], remoteContainer[0074211f3a6d40c3ae12e685afebc812_G3]
14:27:40.878 [reactor-executor-1] INFO  c.a.m.s.i.ServiceBusConnectionProcessor - namespace[] entityPath[my_namespace]: Channel is now active.
14:27:40.937 [reactor-executor-1] INFO  c.a.c.a.i.handler.SessionHandler - onSessionRemoteOpen connectionId[MF_c7e159_1621978060256], entityName[session.control], sessionIncCapacity[0], sessionOutgoingWindow[2147483647]
14:27:40.956 [reactor-executor-1] INFO  c.a.c.a.i.ReactorConnection - Setting CBS channel.
14:27:40.986 [reactor-executor-1] INFO  c.a.c.a.i.handler.SessionHandler - onSessionRemoteOpen connectionId[MF_c7e159_1621978060256], entityName[cbs-session], sessionIncCapacity[0], sessionOutgoingWindow[2147483647]
14:27:40.995 [reactor-executor-1] INFO  c.a.c.a.i.ReactorConnection - connectionId[MF_c7e159_1621978060256] entityPath[$cbs] linkName[cbs] Emitting new response channel.
14:27:40.995 [reactor-executor-1] INFO  c.a.c.a.i.RequestResponseChannel:$cbs - namespace[MF_c7e159_1621978060256] entityPath[$cbs]: Setting next AMQP channel.
14:27:40.995 [reactor-executor-1] INFO  c.a.c.a.i.RequestResponseChannel:$cbs - namespace[MF_c7e159_1621978060256] entityPath[$cbs]: Next AMQP channel received, updating 1 current subscribers
14:27:41.029 [reactor-executor-1] INFO  c.a.c.a.i.handler.SendLinkHandler - onLinkRemoteOpen connectionId[MF_c7e159_1621978060256], entityPath[$cbs], linkName[cbs:sender], remoteTarget[Target{address='$cbs', durable=NONE, expiryPolicy=SESSION_END, timeout=0, dynamic=false, dynamicNodeProperties=null, capabilities=null}]
14:27:41.031 [reactor-executor-1] INFO  c.a.c.a.i.handler.ReceiveLinkHandler - onLinkRemoteOpen connectionId[MF_c7e159_1621978060256], entityPath[$cbs], linkName[cbs:receiver], remoteSource[Source{address='$cbs', durable=NONE, expiryPolicy=SESSION_END, timeout=0, dynamic=false, dynamicNodeProperties=null, distributionMode=null, filter=null, defaultOutcome=null, outcomes=null, capabilities=null}]
14:27:41.031 [reactor-executor-1] INFO  c.a.c.a.i.RequestResponseChannel:$cbs - namespace[MF_c7e159_1621978060256] entityPath[$cbs]: Channel is now active.
14:27:41.064 [reactor-executor-1] INFO  c.a.c.a.i.ActiveClientTokenManager - Scheduling refresh token task. scopes[amqp://my_namespace/session.control]
14:27:41.075 [reactor-executor-1] INFO  c.a.c.a.i.ReactorSession - connectionId[MF_c7e159_1621978060256] sessionId[session.control] linkName[session.control] Creating a new send link.
14:27:41.108 [reactor-executor-1] INFO  c.a.c.a.i.handler.SendLinkHandler - onLinkRemoteOpen connectionId[MF_c7e159_1621978060256], entityPath[session.control], linkName[session.control], remoteTarget[Target{address='session.control', durable=NONE, expiryPolicy=SESSION_END, timeout=0, dynamic=false, dynamicNodeProperties=null, capabilities=null}]
14:27:41.115 [reactor-executor-1] INFO  c.a.m.s.ServiceBusSenderAsyncClient - Sending batch with size[1].
14:27:41.164 [main] INFO  c.a.m.s.ServiceBusClientBuilder - Closing a dependent client. # of open clients: 0
14:27:41.164 [main] INFO  c.a.m.s.ServiceBusClientBuilder - No more open clients, closing shared connection [ServiceBusConnectionProcessor].
14:27:41.165 [main] INFO  c.a.m.s.i.ServiceBusConnectionProcessor - Upstream connection publisher was completed. Terminating processor.
14:27:41.165 [main] INFO  c.a.m.s.i.ServiceBusConnectionProcessor - namespace[] entityPath[my_namespace]: AMQP channel processor completed. Notifying 0 subscribers.
14:27:41.165 [main] INFO  c.a.c.a.i.ReactorConnection - connectionId[MF_c7e159_1621978060256] signal[Disposed by client., isTransient[false], initiatedByClient[true]]: Disposing of ReactorConnection.
14:27:41.165 [main] INFO  c.a.c.a.i.RequestResponseChannel:$cbs - Upstream connection publisher was completed. Terminating processor.
14:27:41.165 [main] INFO  c.a.c.a.i.RequestResponseChannel:$cbs - namespace[MF_c7e159_1621978060256] entityPath[$cbs]: AMQP channel processor completed. Notifying 1 subscribers.
14:27:41.197 [reactor-executor-1] INFO  c.a.c.a.i.handler.SendLinkHandler - onLinkRemoteClose connectionId[MF_c7e159_1621978060256] linkName[cbs:sender], errorCondition[null] errorDescription[null]
14:27:41.200 [reactor-executor-1] INFO  c.a.c.a.i.handler.ReceiveLinkHandler - onLinkRemoteClose connectionId[MF_c7e159_1621978060256] linkName[cbs:receiver], errorCondition[null] errorDescription[null]
14:27:41.202 [main] INFO  c.a.m.s.i.ServiceBusConnectionProcessor - namespace[] entityPath[my_namespace]: Channel is disposed.
14:27:41.204 [main] INFO  c.a.c.a.i.RequestResponseChannel:$cbs - Upstream connection publisher was completed. Terminating processor.
14:27:41.204 [main] INFO  c.a.c.a.i.RequestResponseChannel:$cbs - namespace[MF_c7e159_1621978060256] entityPath[$cbs]: AMQP channel processor completed. Notifying 0 subscribers.
14:27:41.207 [reactor-executor-1] INFO  c.a.c.a.i.handler.ConnectionHandler - onConnectionLocalClose connectionId[MF_c7e159_1621978060256] hostname[my_namespace] errorCondition[null] errorDescription[null]
14:27:41.228 [reactor-executor-1] INFO  c.a.c.a.i.handler.SessionHandler - onSessionRemoteClose connectionId[session.control], entityName[MF_c7e159_1621978060256], condition[Error{condition=null, description='null', info=null}]
14:27:41.228 [reactor-executor-1] INFO  c.a.c.a.i.handler.SessionHandler - onSessionRemoteClose connectionId[cbs-session], entityName[MF_c7e159_1621978060256], condition[Error{condition=null, description='null', info=null}]
14:27:41.251 [reactor-executor-1] INFO  c.a.c.a.i.handler.ConnectionHandler - onConnectionRemoteClose connectionId[MF_c7e159_1621978060256] hostname[my_namespace] errorCondition[null] errorDescription[null]
14:27:41.251 [reactor-executor-1] INFO  c.a.c.a.i.handler.ConnectionHandler - onTransportClosed hostname[my_namespace], connectionId[MF_c7e159_1621978060256], error[n/a]
14:27:41.251 [reactor-executor-1] INFO  c.a.c.a.i.handler.CustomIOHandler - onTransportClosed connectionId[MF_c7e159_1621978060256], hostname[my_namespace]
14:27:41.254 [reactor-executor-1] INFO  c.a.c.a.i.handler.ConnectionHandler - onConnectionUnbound hostname[my_namespace], connectionId[MF_c7e159_1621978060256], state[CLOSED], remoteState[CLOSED]
14:27:41.254 [reactor-executor-1] INFO  c.a.c.a.i.handler.SendLinkHandler - onLinkFinal connectionId[MF_c7e159_1621978060256], linkName[session.control]
14:27:41.257 [reactor-executor-1] INFO  c.a.c.a.i.handler.SessionHandler - onSessionFinal connectionId[MF_c7e159_1621978060256], entityName[session.control], condition[null], description[null]
14:27:41.257 [reactor-executor-1] INFO  c.a.c.a.i.handler.SendLinkHandler - onLinkFinal connectionId[MF_c7e159_1621978060256], linkName[cbs:sender]
14:27:41.257 [reactor-executor-1] INFO  c.a.c.a.i.handler.ReceiveLinkHandler - onLinkFinal connectionId[MF_c7e159_1621978060256], linkName[cbs:receiver]
14:27:41.258 [reactor-executor-1] INFO  c.a.c.a.i.handler.SessionHandler - onSessionFinal connectionId[MF_c7e159_1621978060256], entityName[cbs-session], condition[null], description[null]
14:27:41.258 [reactor-executor-1] INFO  c.a.c.a.i.handler.ConnectionHandler - onConnectionFinal connectionId[MF_c7e159_1621978060256] hostname[my_namespace] errorCondition[null] errorDescription[null]
14:27:45.245 [reactor-executor-1] INFO  c.a.c.a.i.ReactorExecutor - connectionId[MF_c7e159_1621978060256], message[Processing all pending tasks and closing old reactor.]
14:27:45.247 [reactor-executor-1] INFO  c.a.c.a.i.ReactorDispatcher - connectionId[MF_c7e159_1621978060256] Reactor selectable is being disposed.
14:27:45.247 [reactor-executor-1] INFO  c.a.c.a.i.ReactorConnection - onConnectionShutdown connectionId[MF_c7e159_1621978060256], hostName[my_namespace], message[Shutting down], shutdown signal[false]
End close
14:27:45.248 [reactor-executor-1] INFO  c.a.c.a.i.ReactorConnection - onConnectionShutdown connectionId[MF_c7e159_1621978060256], hostName[my_namespace], message[Shutting down], shutdown signal[false]
main                     RUNNABLE        5       Normal
Notification Thread      RUNNABLE        9       Daemon
parallel-6               WAITING         5       Daemon
Common-Cleaner           TIMED_WAITING   8       Daemon
reactor-executor-1       TERMINATED      5       Normal
parallel-9               WAITING         5       Daemon
parallel-1               WAITING         5       Daemon
parallel-7               WAITING         5       Daemon
parallel-12              TIMED_WAITING   5       Daemon
parallel-5               WAITING         5       Daemon
SendTimeout-timer        TIMED_WAITING   5       Normal
boundedElastic-evictor-1         TIMED_WAITING   5       Daemon
boundedElastic-2         WAITING         5       Daemon
elastic-evictor-1        TIMED_WAITING   5       Daemon
Reference Handler        RUNNABLE        10      Daemon
Signal Dispatcher        RUNNABLE        9       Daemon
boundedElastic-3         WAITING         5       Daemon
parallel-2               WAITING         5       Daemon
parallel-4               WAITING         5       Daemon
Finalizer                WAITING         8       Daemon
parallel-3               TIMED_WAITING   5       Daemon
parallel-10              WAITING         5       Daemon
parallel-11              TIMED_WAITING   5       Daemon
parallel-8               WAITING         5       Daemon
End main
(app never exits at this point)

**Comment by joshfree** [comment]
@YijunXieMS can you follow up with @ecmcn ?

/cc @hemanttanwar

**Comment by YijunXieMS** [comment]
@ecmcn We just released a new version 7.2.2, which has a fix for this issue. Could you try it?

**Comment by ecmcn** [comment]
I see the same problem with 7.2.2 (same sample project).

**Comment by YijunXieMS** [comment]
Hi @ecmcn I'm sorry that I made a mistake in cherry-picking a commit for this release. The fix will be release in the next release on about 06/10.

**Comment by ecmcn** [comment]
No problem - thanks for the update.

**Comment by ki1729** [comment]
I think we might still be having this issue. Investigating more into this

**Comment by ki1729** [comment]
This issue is fixed, App closes after timeout as expected
