### ISSUE TITLE
[ACR] Add unit test for FullyQualifiedReference

### ISSUE THREAD

**Issue by annelo-msft** [Azure/azure-sdk-for-java#21875]
We'd like to ensure that test coverage is consistent across the languages.

Would you please review the unit and live tests for the .NET ACR library (found [here](https://github.com/Azure/azure-sdk-for-net/tree/master/sdk/containerregistry/Azure.Containers.ContainerRegistry/tests)), and make sure you have test coverage of the same scenarios?

And specifically, would you add a unit test for the `FullyQualifiedReference` property?  This is where `RegistryArtifact` formats the image name the way it can be used in the Docker CLI.  

Feel free to reach out with any comments or questions.  Thanks!

**Comment by pallavit** [comment]
This has been shipped.
