### ISSUE TITLE
[Question] Different download speed between the `azcopy` and `azure-storage`

### ISSUE THREAD

**Issue by zymap** [Azure/azure-sdk-for-java#21888]
**Query/Question**
Hi, I was using the hadoop-azure to read the object files from the Azure Blob, but the max download speed on the machine is only 1.2 Gbps. But when I use the `azcopy` tool to download the same object, it will reach 6Gbps. 

I am not sure is there any difference between the `azcopy` and the `azure-sdk-for-java`? 
Or are there any configurations that can help me to improve the speed of downloading in the azure java sdk?

**Comment by zymap** [comment]
BTW, I am using hadoop 3.2.2 which azure storage version is:
```
      <dependency>
        <groupId>com.microsoft.azure</groupId>
        <artifactId>azure-storage</artifactId>
        <version>7.0.0</version>
     </dependency>
```

**Comment by joshfree** [comment]
Hi @zymap, I'm routing this to the Storage team to follow up, but just a quick note that the version of azure-storage you're referencing above is very old.  Could you try the latest v12.x (https://azure.github.io/azure-sdk/#java)

/cc @gapra-msft

**Comment by gapra-msft** [comment]
Hi @zymap 

Thank you for asking this question. As Josh mentioned, the version of azure-storage you are referencing is quite old, and we encourage you to try the latest version. 

azcopy is highly optimized for data transfer scenarios, whereas the SDK is for the most part a one to one mapping of the Azure Storage REST API, so it is possible you could see speed differences.

**Comment by zymap** [comment]
Thanks. 
I upgrade to the latest version and it indeed has an improvement in the download speed. 
I will close this issue and thanks again for your suggestion!
