### ISSUE TITLE
[BUG] NoSuchMethodError while creating object of BlobContainerAsyncClient

### ISSUE THREAD

**Issue by adhudiya** [Azure/azure-sdk-for-java#21928]
**Describe the bug**
When we create object of BlobContainerAsyncClient with endpoint it throws runtime error.

***Exception or Stack Trace***
java.lang.NoSuchMethodError: com.fasterxml.jackson.dataformat.xml.XmlMapper.coercionConfigDefaults()Lcom/fasterxml/jackson/databind/cfg/MutableCoercionConfig;
        at com.fasterxml.jackson.dataformat.xml.XmlMapper.<init>(XmlMapper.java:175)
        at com.fasterxml.jackson.dataformat.xml.XmlMapper.<init>(XmlMapper.java:144)
        at com.fasterxml.jackson.dataformat.xml.XmlMapper.<init>(XmlMapper.java:126)
        at com.fasterxml.jackson.dataformat.xml.XmlMapper.builder(XmlMapper.java:209)
        at com.azure.core.util.serializer.JacksonAdapter.<init>(JacksonAdapter.java:137)
        at com.azure.storage.blob.implementation.util.ModelHelper.<clinit>(ModelHelper.java:49)
        at com.azure.storage.blob.BlobUrlParts.parse(BlobUrlParts.java:371)
        at com.azure.storage.blob.BlobContainerClientBuilder.endpoint(BlobContainerClientBuilder.java:147)
        at com.dalet.vfs2.provider.azure.AzFileProvider.doCreateFileSystem(AzFileProvider.java:177)
.........
............

**To Reproduce**
write any test which uses below object,
 BlobContainerClient blobContainerClient = new BlobContainerClientBuilder()
                    .endpoint(endPoint)
                    .credential(storageCreds)
                    .buildClient();

***Code Snippet***
ModelHelper.determineAuthorityIsIpStyle(url.getAuthority())

**Expected behavior**
Object of BlobContainerClient using endpoint should be created without any issue.

**Screenshots**

**Setup (please complete the following information):**
 - OS: any
 - IDE : IntelliJ
 - Version of the Library used : 12.11.1

**Additional context**

**Information Checklist**
Kindly make sure that you have added all the following information above and checkoff the required fields otherwise we will treat the issuer as an incomplete report
- [ ] Bug Description Added
- [ ] Repro Steps Added
- [ ] Setup information Added

**Comment by gapra-msft** [comment]
Hi @adhudiya, this looks like there is a dependency mismatch somewhere. Could you share your dependency tree please?

**Comment by adhudiya** [comment]
Hi @gapra-msft 

Here is my dependency tree,

{code}
[INFO] Scanning for projects...
[INFO] 
[INFO] -------------------< com.github.dalet-oss:vfs-azure >-------------------
[INFO] Building vfs-azure DEV
[INFO] --------------------------------[ jar ]---------------------------------
[INFO] 
[INFO] --- maven-dependency-plugin:2.8:tree (default-cli) @ vfs-azure ---
[INFO] com.github.dalet-oss:vfs-azure:jar:DEV
[INFO] +- org.apache.commons:commons-vfs2:jar:2.7.0:compile
[INFO] |  +- commons-logging:commons-logging:jar:1.2:compile
[INFO] |  \- org.apache.hadoop:hadoop-hdfs-client:jar:3.3.0:compile
[INFO] |     +- com.squareup.okhttp:okhttp:jar:2.7.5:compile
[INFO] |     |  \- com.squareup.okio:okio:jar:1.6.0:compile
[INFO] |     +- com.fasterxml.jackson.core:jackson-annotations:jar:2.10.3:compile
[INFO] |     \- com.fasterxml.jackson.core:jackson-databind:jar:2.10.3:compile
[INFO] +- org.apache.commons:commons-lang3:jar:3.11:compile
[INFO] +- com.azure:azure-storage-blob:jar:12.11.1:compile
[INFO] |  +- com.azure:azure-core:jar:1.16.0:compile
[INFO] |  |  +- com.fasterxml.jackson.core:jackson-core:jar:2.12.2:compile
[INFO] |  |  +- com.fasterxml.jackson.datatype:jackson-datatype-jsr310:jar:2.12.2:compile
[INFO] |  |  +- com.fasterxml.jackson.dataformat:jackson-dataformat-xml:jar:2.12.2:compile
[INFO] |  |  |  +- com.fasterxml.jackson.module:jackson-module-jaxb-annotations:jar:2.12.2:compile
[INFO] |  |  |  |  +- jakarta.xml.bind:jakarta.xml.bind-api:jar:2.3.2:compile
[INFO] |  |  |  |  \- jakarta.activation:jakarta.activation-api:jar:1.2.1:compile
[INFO] |  |  |  +- org.codehaus.woodstox:stax2-api:jar:4.2.1:compile
[INFO] |  |  |  \- com.fasterxml.woodstox:woodstox-core:jar:6.2.4:compile
[INFO] |  |  \- io.netty:netty-tcnative-boringssl-static:jar:2.0.38.Final:compile
[INFO] |  +- com.azure:azure-core-http-netty:jar:1.9.2:compile
[INFO] |  |  +- io.netty:netty-buffer:jar:4.1.63.Final:compile
[INFO] |  |  +- io.netty:netty-transport-native-unix-common:jar:4.1.63.Final:compile
[INFO] |  |  \- io.netty:netty-transport-native-kqueue:jar:osx-x86_64:4.1.63.Final:compile
[INFO] |  +- com.azure:azure-storage-common:jar:12.11.1:compile
[INFO] |  \- com.azure:azure-storage-internal-avro:jar:12.0.4:compile
[INFO] +- io.projectreactor.netty:reactor-netty:jar:0.9.20.RELEASE:compile
[INFO] |  +- io.netty:netty-codec-http:jar:4.1.63.Final:compile
[INFO] |  |  +- io.netty:netty-common:jar:4.1.63.Final:compile
[INFO] |  |  +- io.netty:netty-transport:jar:4.1.63.Final:compile
[INFO] |  |  \- io.netty:netty-codec:jar:4.1.63.Final:compile
[INFO] |  +- io.netty:netty-codec-http2:jar:4.1.63.Final:compile
[INFO] |  +- io.netty:netty-handler:jar:4.1.63.Final:compile
[INFO] |  |  \- io.netty:netty-resolver:jar:4.1.63.Final:compile
[INFO] |  +- io.netty:netty-handler-proxy:jar:4.1.63.Final:compile
[INFO] |  |  \- io.netty:netty-codec-socks:jar:4.1.63.Final:compile
[INFO] |  +- io.netty:netty-transport-native-epoll:jar:linux-x86_64:4.1.63.Final:compile
[INFO] |  \- io.projectreactor:reactor-core:jar:3.3.17.RELEASE:compile
[INFO] |     \- org.reactivestreams:reactive-streams:jar:1.0.3:compile
[INFO] +- org.slf4j:slf4j-api:jar:1.7.30:compile
[INFO] +- org.apache.logging.log4j:log4j-slf4j-impl:jar:2.14.0:compile
[INFO] +- org.apache.logging.log4j:log4j-api:jar:2.14.0:compile
[INFO] +- org.apache.logging.log4j:log4j-core:jar:2.14.0:compile
[INFO] \- junit:junit:jar:4.13.1:test
[INFO]    \- org.hamcrest:hamcrest-core:jar:1.3:test
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  1.813 s
[INFO] Finished at: 2021-05-31T16:40:52+05:30
[INFO] ------------------------------------------------------------------------
{code}

**Comment by gapra-msft** [comment]
Hi @adhudiya 
It looks like you have conflicting versions of the jackson dependency listed above, 

[INFO] | +- com.fasterxml.jackson.core:jackson-annotations:jar:2.10.3:compile
[INFO] | - com.fasterxml.jackson.core:jackson-databind:jar:2.10.3:compile

The SDK depends on jackson version 2.12.2

Could you please resolve that dependency conflict and see if you still hit the issue?
