### ISSUE TITLE
Feedback to "Azure Spring Boot Starter Storage client library for Java" docs

### ISSUE THREAD

**Issue by rodion-kasatkin1** [Azure/azure-sdk-for-java#21930]
It would be great if you add some clarification about initialization for storage-file resource access:
I spent some time to research this possibility, beacause your doc don't have part about ShareServiceClient initialization.
So my variant to show how to do that is just add code snippet into some @Configuration java Class/Bean:
```
    @Autowired
    @Bean
    public AzureStorageResourcePatternResolver getStorageResourcePatternResolver(
            BlobServiceClientBuilder blobServiceClientBuilder,
            ShareServiceClientBuilder shareServiceClientBuilder) {
        BlobServiceClient blobClient = blobServiceClientBuilder.buildClient();
        ShareServiceClient fileClient = shareServiceClientBuilder.buildClient();
        return new AzureStorageResourcePatternResolver(blobClient, fileClient);
    }
```
This code checked on Spring Boot 2.4.6
Thanks. 

---
#### Сведения о документе

⚠ *Не вносите правки в этот раздел. Это необходимо для связывания страницы сайта docs.microsoft.com с вопросом на GitHub.*

* ID: 503c5ec5-ec8b-fd94-a358-d2936c4fd810
* Version Independent ID: 573ac7cd-4886-0a83-bb01-75b26e35c674
* Content: [Azure Spring Boot Starter Storage client library for Java](https://docs.microsoft.com/ru-ru/java/api/overview/azure/spring-boot-starter-storage-readme?view=azure-java-stable)
* Content Source: [docs-ref-services/latest/spring-boot-starter-storage-readme.md](https://github.com/Azure/azure-docs-sdk-java/blob/master/docs-ref-services/latest/spring-boot-starter-storage-readme.md)
* Service: **springboot**
* Product: **azure**
* Technology: **azure**
* GitHub Login: @maggiepint
* Microsoft Alias: **magpint**

**Comment by joshfree** [comment]
Thanks for the feedback @rodion-kasatkin1.  @stliu could someone from the spring team follow up?

**Comment by saragluna** [comment]
@backwind1233 could you take a look at this?

**Comment by backwind1233** [comment]
Hi @rodion-kasatkin1, thanks very much for your feedback, I am following up on this issue.

**Comment by wujack778** [comment]
@rodion-kasatkin1 hello frend, I am not sure of the purpose of adding this code snippet. Can you explain your concerns?

**Comment by rodion-kasatkin1** [comment]
@wujack778 hi. I suggested to add how to init work with FILE storage (do not mesh up with BLOB storage) because current article does not contains part about it and connection to the file storage is little bit different to connection to blob storage.

**Comment by wujack778** [comment]
All right，i will add this code snippet soon. @rodion-kasatkin1
