### ISSUE TITLE
Is there any library from Microsoft for cosmos db gremlin integration with java?

### ISSUE THREAD

**Issue by satyajitcet** [Azure/azure-sdk-for-java#21945]
**Query/Question**
As Spring Data Gremlin (https://github.com/Microsoft/spring-data-gremlin) is depricating, is it good to use 
Spring Data Gremlin Boot Starter ( https://mvnrepository.com/artifact/com.microsoft.azure/spring-data-gremlin-boot-starter )
library?

***Why is this not a Bug or a feature Request?***
i want to understand , what is good to use to integrate java with cosmosdb gremlin api. Not a bug.

**Comment by chenrujun** [comment]
Hi, @satyajitcet, both `spring-data-gremlin` and `spring-data-gremlin-boot-starter ` are deprecated, please don't use them.

**Comment by chenrujun** [comment]
Hi, @backwind1233 , do you have any suggestions if customer have requirement about `spring-data-gremlin-boot-starter`?

**Comment by backwind1233** [comment]
@seanli1988 can you help to answer the question?

**Comment by satyajitcet** [comment]
Hi @chenrujun , 
Then I think, there is no library from Microsoft to integrate with cosmosDB gremlin api and java. Only option is apache tinkerpop.

**Comment by seanli1988** [comment]
We dropped Gremlin support because of low usage. I suggest we backlog the ask and see how many people vote on it.

**Comment by Shivani2596** [comment]
Hi @seanli1988 
I can see deprecating (https://github.com/Microsoft/spring-data-gremlin) git link,  suggests to use
azure-spring-boot-starter-cosmos(https://github.com/Azure/azure-sdk-for-java/tree/master/sdk/spring/azure-spring-boot-starter-cosmos).
So Can we use it for gremlin API too? Is this supported?

**Comment by seanli1988** [comment]
No gremlin is not supported. azure-spring-boot-starter-cosmos uses the SQL API.

**Comment by JonnewDev-blip** [comment]
So is TinkerPop the only java option for Cosmos DB and working with graphs?

**Comment by kushagraThapar** [comment]
Yes, that is the only option for now. Closing this issue.
