### ISSUE TITLE
Enable proxy even when java.net.useSystemProxies is false [FEATURE REQ]

### ISSUE THREAD

**Issue by DanyUP** [Azure/azure-sdk-for-java#21946]
**Is your feature request related to a problem? Please describe.**
When using Azure Identity SDK for Java, Java proxy variables defined as system properties (i.e. https.proxyHost, https.proxyPort, etc.) are ignored unless the property java.net.useSystemProxies is set to true. However, this property doesn't usually enable the proxy variables, but it enables automatic configuration of proxy settings from system configuration (i.e. the configuration available from Windows settings).

**Describe the solution you'd like**
I think that the correct behaviour would be to apply proxy settings even when java.net.useSystemProxies is set to false or is not set.

**Describe alternatives you've considered**
The only alternative is to leave the behaviour as is.

**Additional context**
From official documentation (https://docs.oracle.com/javase/8/docs/technotes/guides/net/proxies.html):

> On recent Windows systems and on Gnome 2.x platforms it is possible to tell the default ProxySelector to use the system proxy settings (both recent versions of Windows and Gnome 2.x let you set proxies globally through their user interface). If the system property java.net.useSystemProxies is set to true (by default it is set to false for compatibility sake), then the default ProxySelector will try to use these settings. 

**Information Checklist**
Kindly make sure that you have added all the following information above and checkoff the required fields otherwise we will treat the issuer as an incomplete report
- [x] Description Added
- [x] Expected solution specified

**Comment by joshfree** [comment]
@alzimmermsft could you please take a look?

**Comment by alzimmermsft** [comment]
Thank you for filing this issue @DanyUP.

Just a quick re-cap for my understanding, your recommendation is applying the `java.net` proxy configurations even when ` java.net.useSystemProxies` is missing or `false`?

Based on what you've linked this is a good suggestion, I believe the optimal solution may be applying the proxy when ` java.net.useSystemProxies` is `true` or missing as `false` seems to be an explicit opt-out on using the `java.net` proxy configurations.

**Comment by DanyUP** [comment]
Thank you for your reply.

IMHO java.net.useSystemProxies=true is used to retrieve the proxy configuration from system default (i.e. from configurations in Windows Network & Internet or, in some Linux system, from configuration inside Gnome Network Manager), thus ignoring java.net variables.

When java.net.useSystemProxies is missing or false (the default), proxy configuration is read from java.net variables.

I don't know if this can help, but all this logic is automatically managed when using ProxySelector class from Java Standard Library.
