### ISSUE TITLE
Service Bus Readme Issue

### ISSUE THREAD

**Issue by hongli750210** [Azure/azure-sdk-for-java#21959]
1.
Section [Link](https://github.com/Azure/azure-sdk-for-java/tree/master/sdk/servicebus/azure-messaging-servicebus#examples)

![image](https://user-images.githubusercontent.com/74638143/120134595-09329d80-c201-11eb-8770-f756400ee79f.png)

Reason:
Click on these links does not respond.

Suggestion:  
	1. Update link to:
	 https://github.com/Azure/azure-sdk-for-java/tree/master/sdk/servicebus/azure-messaging-servicebus#receive-messages 
	2. Update link to:
         https://github.com/Azure/azure-sdk-for-java/tree/master/sdk/servicebus/azure-messaging-servicebus#send-and-receive-from-session-enabled-queues-or-topics

@jongio for notification.

**Comment by YijunXieMS** [comment]
Thanks @hongli19750210 and @v-xuto. Could you please create a PR for it?

**Comment by v-xuto** [comment]
Close this issue due to PR #22320  merged.
