### ISSUE TITLE
Azure Analytics Purview Readme issues

### ISSUE THREAD

**Issue by hongli750210** [Azure/azure-sdk-for-java#21956]
1.
Section [Link1](https://github.com/Azure/azure-sdk-for-java/tree/master/sdk/purview/azure-analytics-purview-scanning#prerequisites), [Link2](https://github.com/Azure/azure-sdk-for-java/tree/master/sdk/purview/azure-analytics-purview-catalog#prerequisites)
![image](https://user-images.githubusercontent.com/74638143/120135270-7c88df00-c202-11eb-9bb8-85228fc84256.png)
Suggestion:  
Add link for `[create_azure_purview_account]`: https://docs.microsoft.com/en-us/azure/purview/

2.
Section [Link1](https://github.com/Azure/azure-sdk-for-java/tree/master/sdk/purview/azure-analytics-purview-scanning#troubleshooting), [Link2](https://github.com/Azure/azure-sdk-for-java/tree/master/sdk/purview/azure-analytics-purview-catalog#troubleshooting)
![image](https://user-images.githubusercontent.com/74638143/120135371-b8bc3f80-c202-11eb-8bab-cf79ddb8187c.png)
Suggestion: 
	1. Add link for `[logging]` : https://github.com/Azure/azure-sdk-for-java/wiki/Logging-with-Azure-SDK 
	2. Add link for `[cla]`: https://cla.opensource.microsoft.com/
	3. Add link for `[coc]`: https://opensource.microsoft.com/codeofconduct/ 
	4. Add link for `[coc_faq]`: https://opensource.microsoft.com/codeofconduct/faq/ 
        5. Add link for `[coc_contact]`: mailto:opencode@microsoft.com

@jongio for notification.

**Comment by v-xuto** [comment]
Close this issue, due to PR https://github.com/Azure/azure-sdk-for-java/pull/22714 merged.
