### ISSUE TITLE
Azure Cosmos Encryption Readme issues

### ISSUE THREAD

**Issue by hongli750210** [Azure/azure-sdk-for-java#21957]
1.
Section [Link](https://github.com/Azure/azure-sdk-for-java/tree/master/sdk/cosmos/azure-cosmos-encryption#examples)
![image](https://user-images.githubusercontent.com/74638143/120135099-1a2fde80-c202-11eb-843a-5f3336e3c75f.png)
Reason:
Click on these links does not respond.

Suggestion:  
	1. Update link to:
	https://github.com/Azure/azure-sdk-for-java/tree/master/sdk/cosmos/azure-cosmos-encryption#create-cosmos-encryption-database
         2. Update link to: https://github.com/Azure/azure-sdk-for-java/tree/master/sdk/cosmos/azure-cosmos-encryption#create-cosmos-encryption-container

@jongio for notification.

**Comment by v-xuto** [comment]
Close this issue, due to PR https://github.com/Azure/azure-sdk-for-java/pull/22719 merged.
