### ISSUE TITLE
Key vault Secrets Sample issues 

### ISSUE THREAD

**Issue by hongli750210** [Azure/azure-sdk-for-java#21960]
1.
Section [Link](https://github.com/Azure/azure-sdk-for-java/blob/master/sdk/keyvault/azure-security-keyvault-secrets/src/samples/java/com/azure/security/keyvault/secrets/ListOperations.java#L45):

![image](https://user-images.githubusercontent.com/74638143/120134398-95909080-c200-11eb-80d5-ecfde2c6065e.png)

Reason:   
Some secret states are disabled, which will result in an error.

Suggestion:  
Update to :
```
        if(!secret.isEnabled()){
            continue;
        }
        KeyVaultSecretsecretWithValue=client.getSecret(secret.getName(),secret.getVersion());
```
@jongio for notification.

**Comment by v-xuto** [comment]
Close this issue, due to PR https://github.com/Azure/azure-sdk-for-java/pull/22711 merged.
