### ISSUE TITLE
[BUG] Azure azure-security-keyvault-secrets SDK creating SecretAsyncClient created by default

### ISSUE THREAD

**Issue by mjmadhu** [Azure/azure-sdk-for-java#21963]
**Describe the bug**
I'm creating a secret client but somehow by default it's creating Async Client which is breaking the expected flow (require sync client to work).
 
***Exception or Stack Trace***
```bash
2021-05-29 18:52:58.741 DEBUG 7900 --- [ctor-http-nio-2] c.a.s.k.secrets.SecretAsyncClient        : Retrieved secret - <*****>
```
**To Reproduce**
Create a default secret client using Java SDK:
new SecretClientBuilder().vaultUrl(keyVaultUrl).credential(credential).buildClient();

***Code Snippet***
```xml
// pom.xml dependency definition
<dependency>
            <groupId>com.azure</groupId>
            <artifactId>azure-security-keyvault-secrets</artifactId>
            <version>4.3.0-beta.6</version>
</dependency>
```
```java
// Code snippet to fetch secret
public KeyVaultService(@Value("${key.vault.name}") String keyVaultName) {
        logger.info("Initialising KeyVaultService");
        String keyVaultUrl = "https://" + keyVaultName + ".vault.azure.net";
        DefaultAzureCredential credential = new DefaultAzureCredentialBuilder().build();
        secretClient = new SecretClientBuilder().vaultUrl(keyVaultUrl).credential(credential).buildClient();
}
public String getSecret(String secretKey) {
        KeyVaultSecret secret = secretClient.getSecret(secretKey);
        return secret.getValue();
}
```
**Expected behavior**
Get the Secret Sync Client by default for desired functionality

**Setup (please complete the following information):**
 - OS: Windows 10
 - IDE : VS Code v1.56.2
 - Version of the Library used - 4.3.0-beta.6

**Information Checklist**
Kindly make sure that you have added all the following information above and checkoff the required fields otherwise we will treat the issuer as an incomplete report
- [x] Bug Description Added
- [x] Repro Steps Added
- [x] Setup information Added

**Comment by vcolin7** [comment]
Our Java sync clients reach the service by blocking async calls made by an internal async client, this is a pattern we follow for most of our Track 2 SDKs. What you are seeing is a log made by the internal `SecretAsyncClient`, not actually a bug. The actual service call will be blocked on and will behave as you would expect any synchronous method to, waiting for a result to be produced to then continue execution on the next line of code :)
