### ISSUE TITLE
[Feature Request] Integrate Spring Retry with Azure SDK retry policy for all Spring components

### ISSUE THREAD

**Issue by saragluna** [Azure/azure-sdk-for-java#21973]
### Context
[Spring Retry](https://docs.spring.io/spring-batch/docs/current/reference/html/retry.html) provides the RetryTemplate for users to customize the retry behavior.
### Goal
It would be great if Spring Retry can be integrated with Spring Cloud Azure for each starter and other components. With this support, users should be able to customize SDK's retry behavior via Spring Retry.

**Comment by stliu** [comment]
we should at least have a configuration to allow customer disable azure-core's retry policy in favor of spring-retry
