### ISSUE TITLE
Implement health indicators for database and storage components

### ISSUE THREAD

**Issue by saragluna** [Azure/azure-sdk-for-java#21977]

**Comment by backwind1233** [comment]
Storage and cosmos has implement health indicators.
- [Storage](https://github.com/moarychan/azure-sdk-for-java/blob/b71905f916874d3fa89a1f43911e9bc75cda3493/sdk/spring/azure-spring-cloud-storage/src/main/java/com/microsoft/azure/spring/cloud/autoconfigure/storage/actuator/BlobStorageHealthIndicator.java#L19)
- [cosmosdb](https://github.com/Azure/azure-sdk-for-java/pull/14076)

**Comment by saragluna** [comment]
No extra implementation is needed, closing this one now.
