### ISSUE TITLE
[FEATURE REQ] Provide a health indicator for Service Bus Spring starter

### ISSUE THREAD

**Issue by saragluna** [Azure/azure-sdk-for-java#21976]
### Context
In Spring Cloud Azure 4.0, we added a starter for Azure Service Bus. Each client should have one health indicator for it, and it's the same for the Service Bus clients.

### Goal
 With this health indicator, users shall be able to check the health status of Service Bus clients.

**Comment by saragluna** [comment]
closing in favor of #21544.

**Comment by saragluna** [comment]
Reopen it for the Service Bus health indicator hasn't been added for auto-configuration.

**Comment by saragluna** [comment]
@yiliuTo there's no health indicator for level 1 service bus SDK client.

**Comment by saragluna** [comment]
The service bus sdk client doesn't expose any interfaces for us to check the status of it, so putting this issue to backlog.

**Comment by saragluna** [comment]
https://github.com/Azure/azure-sdk-for-net/issues/8561

**Comment by stliu** [comment]
https://github.com/Azure/azure-sdk-for-java/issues/30507

**Comment by AndreasPetersen** [comment]
I'm sorry, I'm a bit confused with all these issues being linked throughout.

Is it possible to get health indicators through the service bus clients, or is this still in the backlog?

**Comment by saragluna** [comment]
Sorry @AndreasPetersen, it's still in the backlog. We will look into the tracing implementation in #30507 to see whether it can provide the health info, but this task is a lower priority now.

**Comment by AndreasPetersen** [comment]
I see that #30507, being marked as a duplicate of #26269 which is also closed as completed. Where does that leave this issue?

**Comment by saragluna** [comment]
The tracer will collect information whenever sending or receiving messages, but what if an application with a sender or receiver but has no messages flowing, should we consider the application is healthy? So for a health indicator we should not depend on the messages flowing on the connection, metrics like active connection might be more suitable in this case.

**Comment by AndreasPetersen** [comment]
Would it be possible to send a ping message to check the health of the connection? The lack of a health indicator is a huge issue for us given https://github.com/Azure/azure-sdk-for-java/issues/34588 .

**Comment by Netyyyy** [comment]
Hi @AndreasPetersen , the service bus sdk client doesn't expose any interfaces for us to check the status of it, so it's still blocked.

**Comment by AndreasPetersen** [comment]
> Hi @AndreasPetersen , the service bus sdk client doesn't expose any interfaces for us to check the status of it, so it's still blocked.

Thank you for the reply @Netyyyy . Is there an issue on exposing any such interfaces?

**Comment by Netyyyy** [comment]
> > Hi @AndreasPetersen , the service bus sdk client doesn't expose any interfaces for us to check the status of it, so it's still blocked.
> 
> Thank you for the reply @Netyyyy . Is there an issue on exposing any such interfaces?

Sorry, I have no idea about that. Maybe @anuchandy could help you.
