### ISSUE TITLE
[FEATURE REQ] Add `attach` to `ContainerGroup`

### ISSUE THREAD

**Issue by timja** [Azure/azure-sdk-for-java#21984]
**Is your feature request related to a problem? Please describe.**

I would like to be able to attach to the outputstream of logs and events from container instances

**Describe the solution you'd like**

Add attach method(s) to `ContainerGroup` https://github.com/Azure/azure-sdk-for-java/blob/master/sdk/resourcemanager/azure-resourcemanager-containerinstance/src/main/java/com/azure/resourcemanager/containerinstance/models/ContainerGroup.java

**Describe alternatives you've considered**

It looks like I can construct my own instance via:

```java
ContainerInstanceManagementClientImpl containerInstanceManagementClient = new ContainerInstanceManagementClientBuilder()
  .pipeline(httpPipeline)
  .endpoint(profile.getEnvironment().getResourceManagerEndpoint())
  .subscriptionId(profile.getSubscriptionId())
  .buildClient();
``` 

But I suspect I shouldn't be creating `Impl` classes myself

**Additional context**

**Information Checklist**
Kindly make sure that you have added all the following information above and checkoff the required fields otherwise we will treat the issuer as an incomplete report
- [x] Description Added
- [x] Expected solution specified

**Comment by joshfree** [comment]
@yungezz could you please help route this?

**Comment by yungezz** [comment]
add @weidongxu-microsoft to help

**Comment by weidongxu-microsoft** [comment]
@timja You can get `ContainerInstanceManagementClient` via `azure.containerGroups().manager().serviceClient()`.

**Comment by timja** [comment]
Ah thanks,

Full example:
```java
String webSocketUri = containerGroup.manager().serviceClient().getContainers()
  .attach(rg, containerGroup, container)
  .webSocketUri();
```

Is this a common pattern?

I haven't had to do this for any other methods I've called in the track 2 sdk that I'm aware of.

Feel free to close this if you find this as a normal solution, but it wasn't very discoverable for me.

**Comment by weidongxu-microsoft** [comment]
2.7.0 should have the code.

Short survey for us to hear you:
https://microsoft.qualtrics.com/jfe/form/SV_ehN0lIk2FKEBkwd?Q_CHL=ISSUES
