### ISSUE TITLE
[QUERY] Load keystore with key specified by alias

### ISSUE THREAD

**Issue by schrek1** [Azure/azure-sdk-for-java#22019]
Is possible specify key alias before load keystore? Becouse it looks like first key is taken, but no more...

**Comment by alzimmermsft** [comment]
Hi @schrek1, thank you for submitting this question. Mind including which Azure SDKs you are including to help narrow the scope of the question?

**Comment by schrek1** [comment]
I'm using library com.azure.spring:azure-spring-boot-starter-keyvault-certificates:3.0.0-beta.7

**Comment by alzimmermsft** [comment]
@stliu could you triage this to the appropriate owner?

**Comment by chenrujun** [comment]
Hi, @schrek1 .
Thanks for reaching out.
Do you mean [this](https://github.com/Azure/azure-sdk-for-java/blob/azure-spring-boot-starter-keyvault-certificates_3.0.0-beta.7/sdk/spring/azure-spring-boot-samples/azure-spring-boot-sample-keyvault-certificates-server-side/src/main/resources/application.yml#L12)?

**Comment by schrek1** [comment]
Yes, but I don't use it as on server, but I use lib for prepare keystore for http client. When I debug, I saw that keystore contains only one key

**Comment by chenrujun** [comment]
@schrek1 

Could you please run this test code?
https://github.com/chenrujun/azure-sdk-for-java/blob/Add-ClientSideTest/sdk/keyvault/azure-security-keyvault-jca/src/samples/java/com/azure/security/keyvault/jca/ClientSideTest.java#L45

And please share your test code.

**Comment by schrek1** [comment]
Same result... loaded only single cert

> Task :request_signer:ClientSideTest.main()
Number of certificates found : 0
*****************************************************************
�vn 15, 2021 10:46:54 DOP. com.azure.security.keyvault.jca.KeyVaultClient <init>
INFO: Using Azure Key Vault: https://****.vault.azure.net
�vn 15, 2021 10:46:54 DOP. com.azure.security.keyvault.jca.KeyVaultClient <init>
INFO: Using Azure Key Vault: https://****.vault.azure.net
�vn 15, 2021 10:46:54 DOP. com.azure.security.keyvault.jca.AuthClient getAccessToken
INFO: Getting access token using client ID / client secret
Certificate name: zaplaceno-zaproxy
�vn 15, 2021 10:46:55 DOP. com.azure.security.keyvault.jca.KeyVaultClient getCertificate
INFO: Getting certificate for alias: ****
�vn 15, 2021 10:46:55 DOP. com.azure.security.keyvault.jca.AuthClient getAccessToken
INFO: Getting access token using client ID / client secret
-----BEGIN CERTIFICATE-----

**Comment by schrek1** [comment]
My code:

`@Service
@Log4j2
class KeyVaultKeyStoreService {

    private final KeyStore keyStore;

    @SneakyThrows
    public KeyVaultKeyStoreService() {
        log.info("load azure keystore started...");

        Security.addProvider(new KeyVaultJcaProvider());
        KeyStore keyStore = KeyStore.getInstance("AzureKeyVault");
        keyStore.load(null);

        log.info("load azure keystore sucessfully finished");

        logCertificate(keyStore);

        this.keyStore = keyStore;
    }
}
`

**Comment by schrek1** [comment]
I debug lib and I found reson of problem, we have not only certs (/certificates), but we import to our keystore from  /keys and /secrets too.. Library allows only load from /certificates to keystore

**Comment by chenrujun** [comment]
Hi, @schrek1 .

> Is there some way to import keys too?

Do you mean import keys to [KeyVaultKeyStore](https://github.com/Azure/azure-sdk-for-java/blob/1b9e7883a703d0cb67cbb596cc58514e2ce035c4/sdk/keyvault/azure-security-keyvault-jca/src/main/java/com/azure/security/keyvault/jca/KeyVaultKeyStore.java#L41)?

Now we will import certificate's key to KeyVaultKeyStore:

1. https://github.com/Azure/azure-sdk-for-java/blob/1b9e7883a703d0cb67cbb596cc58514e2ce035c4/sdk/keyvault/azure-security-keyvault-jca/src/main/java/com/azure/security/keyvault/jca/KeyVaultKeyStore.java#L217
2. https://github.com/Azure/azure-sdk-for-java/blob/1b9e7883a703d0cb67cbb596cc58514e2ce035c4/sdk/keyvault/azure-security-keyvault-jca/src/main/java/com/azure/security/keyvault/jca/KeyVaultCertificates.java#L115

Why do you want to import the key when the key not belong to any certificate?

**Comment by chenrujun** [comment]
Closing this issue because there is no response from customer for a long time.
