### ISSUE TITLE
Cosmos Spark Connector: Cannot convert Json into InternalRow

### ISSUE THREAD

**Issue by inscorep-Louis** [Azure/azure-sdk-for-java#22017]
# Cosmos Spark Connector

Hi,
I am using the new Azure Cosmos DB spark connector for the Cosmos DB Sql api, but I am having trouble with it inferring the schema before it being loaded.

```python

cosmos_endpoint: str = "##############"
cosmos_key: str = "#######"

cosmosEndpoint = cosmos_endpoint
cosmosMasterKey = cosmos_key
cosmosDatabaseName = "cosmosDatabaseName"
cosmosContainerName = "cosmosContainerName"

cfg = {
   "spark.cosmos.accountEndpoint" : cosmosEndpoint,
   "spark.cosmos.accountKey" : cosmosMasterKey,
   "spark.cosmos.database" : cosmosDatabaseName,
   "spark.cosmos.container" : cosmosContainerName,
}

# Configure Catalog Api to be used
spark.conf.set("spark.sql.catalog.cosmosCatalog", "com.azure.cosmos.spark.CosmosCatalog")
spark.conf.set("spark.sql.catalog.cosmosCatalog.spark.cosmos.accountEndpoint", cosmosEndpoint)
spark.conf.set("spark.sql.catalog.cosmosCatalog.spark.cosmos.accountKey", cosmosMasterKey)

df = (
    spark
    .read
    .format("cosmos.oltp")
    .options(**cfg)
    .option("spark.cosmos.read.inferSchema.enabled", "true")
    .load()
)
 
df.show()
```

But I get the following error

```python
Exception: Cannot convert Json '{"A":1,"partitionKey":"Hello","array":[1,2,3],"object_array":[{"A":[1,2,3],"B":[4,5,6]},{"A":[1,2,3]},{"B":[1,2,3]}],"id":"be76ea5d-690a-470a-b2ba-de5ea677bc63","_rid":"lnUoALlRjwYDAAAAAAAAAA==","_self":"dbs/lnUoAA==/colls/lnUoALlRjwY=/docs/lnUoALlRjwYDAAAAAAAAAA==/","_etag":"\"2d006de7-0000-3000-0000-60b787320000\"","_attachments":"attachments/","_ts":1622640434}' into InternalRow
Caused by: RuntimeException: Error while encoding: java.lang.RuntimeException: The 1th field 'B' of input row cannot be null.
Caused by: RuntimeException: The 1th field 'B' of input row cannot be null.
```
I've noticed if I define the structure beforehand it works, but I would prefer it to infer the Schema as the previous version, is there a solution for this?

The maven coordinates are com.azure.cosmos.spark:azure-cosmos-spark_3-1_2-12:4.1.0

**Comment by joshfree** [comment]
@kushagraThapar could you assist @inscorep-Louis with their question?

**Comment by kushagraThapar** [comment]
@moderakh  - please take a look at this .

**Comment by moderakh** [comment]
@ealsur this is schema inference related could you please take a look?

**Comment by ealsur** [comment]
This is probably due to the `object_array` attribute having elements with and without `B` property. 

According to the config page, the schema inference has a configuration called `forceNullableProperties`: https://github.com/Azure/azure-sdk-for-java/blob/master/sdk/cosmos/azure-cosmos-spark_3-1_2-12/docs/configuration-reference.md#schema-inference-config, which is false by default.

Schema inference samples documents, if it finds the property being `null` for some documents and not null for others, it marks it as `nullable` on the Schema, but if the sampled documents all have the property, then it marks it as **not** `nullable`. 

In your case, it looks like the sampled documents might have all had items with `B` property in `object_array` but when processing the entire container, it found documents that did not. If this is expected, you can just set `spark.cosmos.read.inferSchema.forceNullableProperties` to `true` in the config. 

The reason for this being a config is that some customers might not expect documents missing properties, and it's better to err but be aware of the situation and override it with a config.

**Comment by ealsur** [comment]
Closing as by-design, and the config can be changed if the scenario is expected.

**Comment by inscorep-Louis** [comment]
Hi, 

Thank you this seems to resolve the error. 

I would like ask another question. Is it possible to infer the Schema of the data selected after the query, as it seems that it is currently doing it beforehand?

I created a test container with two Json documents with similar schemas.

```json
{
    "A": 1,
    "B": 2,
    "partitionKey": "Numbers",
    "id": "2f8bc7cc-3af2-4d42-a813-b50e281324f7"
},
{
    "A": 1,
    "C": 2,
    "partitionKey": "Numbers",
    "id": "da3491cb-0083-47cb-a54e-78dc9325102d"
}
```

If I run the following code I still get column C, even though if it used the data it received from the query it would have inferred that there were only columns id, A, B and partitionKey.

``` python
# Import packages
import pyspark.sql.functions as F


cosmosEndpoint = cosmos_endpoint
cosmosMasterKey = cosmos_key
cosmosDatabaseName = cosmos_db
cosmosContainerName = "test"

# Set configurations
cfg = {
   "spark.cosmos.accountEndpoint" : cosmosEndpoint,
   "spark.cosmos.accountKey" : cosmosMasterKey,
   "spark.cosmos.database" : cosmosDatabaseName,
   "spark.cosmos.container" : cosmosContainerName,
}

# Configure Catalog Api to be used
spark.conf.set("spark.sql.catalog.cosmosCatalog", "com.azure.cosmos.spark.CosmosCatalog")
spark.conf.set("spark.sql.catalog.cosmosCatalog.spark.cosmos.accountEndpoint", cosmosEndpoint)
spark.conf.set("spark.sql.catalog.cosmosCatalog.spark.cosmos.accountKey", cosmosMasterKey)


# Read data from Cosmos DB
df = (
    spark
    .read
    .format("cosmos.oltp")
    .options(**cfg)
    .option("spark.cosmos.read.inferSchema.forceNullableProperties", "true")
    .option("spark.cosmos.read.inferSchema.includeTimestamp", "false")
    .option("spark.cosmos.read.inferSchema.enabled", "true")
    .load()
    .where(
        F.col("id") == "2f8bc7cc-3af2-4d42-a813-b50e281324f7"
    )
    
)

print(df.explain())
display(df.show())

== Physical Plan ==
*(1) Project [A#2192, partitionKey#2193, id#2194, B#2195, C#2196]
+- BatchScan[A#2192, partitionKey#2193, id#2194, B#2195, C#2196] Cosmos ItemsScan: sigma.test
 - Cosmos Query: SELECT * FROM r WHERE NOT(IS_NULL(r['id'])) AND r['id']=@param0
 > param: @param0 = 2f8bc7cc-3af2-4d42-a813-b50e281324f7


None
+---+------------+--------------------+---+----+
|  A|partitionKey|                  id|  B|   C|
+---+------------+--------------------+---+----+
|  1|     Numbers|2f8bc7cc-3af2-4d4...|  2|null|
+---+------------+--------------------+---+----+
```

**Comment by ealsur** [comment]
@inscorep-Louis Schema inference works by sampling the first 1000 documents and creating the schema based off that, then executing the query.

There are different configuration options (https://github.com/Azure/azure-sdk-for-java/blob/master/sdk/cosmos/azure-cosmos-spark_3-1_2-12/docs/configuration-reference.md#schema-inference-config).

You can disable schema inference (`spark.cosmos.read.inferSchema.enabled`) and provide your desired schema, you can change the sampling size (`spark.cosmos.read.inferSchema.samplingSize`), you can use a custom query to tell the inference which documents should be used to infer it (`spark.cosmos.read.inferSchema.query`).

If you are always selecting a single document or just a document with that id, maybe you can provide the schema you want to use or apply the same filter in the inference query (like `SELECT * FROM d WHERE d.id = {some value you want to use}`).
