### ISSUE TITLE
[BUG] Windows app service JAVA startup command 

### ISSUE THREAD

**Issue by JV-TMCZ** [Azure/azure-sdk-for-java#22015]
Spring boot application using internal and external configuration file of same name (application.properties) fails to start. 
Since this weekend (on Germany West Central), "something" changed... probably startup script which loads java jar/classpath. 
Unfortunatelly Iam not able to find the real startup command (where could I found it?). 

Startup somehow disables spring boot magic [(docs)](https://docs.spring.io/spring-boot/docs/current/reference/html/features.html#features.external-config) of loading application.properties. And when file on classpath has same name as external file, only the external is used. It looks like the file is overrided. Simply no property from internal classpath:./application.properties is used.

It worked a week before. 
It still working on linux app service (probably different startup script).

**To Reproduce**
Deploy any spring boot project with internal and external configuration file of the same filename to WINDOWS app service. (I tested on latest java11, embeded java SE (automatic)).

***Code Snippet***
Simplest project to reproduce:
/src/main/java/com/example/restservice/RestServiceApplication.java
```
package com.example.restservice;

import org.springframework.beans.factory.annotation.Value;
import org.springframework.boot.SpringApplication;
import org.springframework.boot.autoconfigure.SpringBootApplication;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.bind.annotation.RestController;

@SpringBootApplication
@RestController
public class RestServiceApplication {

	@Value("${app.param1}")
	private String param1;

	@Value("${app.param2}")
	private String param2;


	public static void main(String[] args) {
		SpringApplication.run(RestServiceApplication.class, args);
	}


	@GetMapping("/greeting")
	public String greeting(@RequestParam(value = "name", defaultValue = "World") String name) {
		return String.format("Hello, %s! Param1: '%s', Param2: '%s'", name, param1, param2);
	}
}
```

/src/main/resources/application.properties
```
app.param1=Param1-Value-from-classpath
#app.param2=Param2-Value-from-classpath
debug = true
logging.level.org.springframework.core.env=TRACE
```

External file application.properties
```
#app.param1=Param1-Value-from-external-file
app.param2=Param2-Value-from-external-file
```

pom.xml
```
<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
	<modelVersion>4.0.0</modelVersion>
	<parent>
		<groupId>org.springframework.boot</groupId>
		<artifactId>spring-boot-starter-parent</artifactId>
		<version>2.4.3</version>
		<relativePath/> <!-- lookup parent from repository -->
	</parent>
	<groupId>com.example</groupId>
	<artifactId>rest-service</artifactId>
	<version>0.0.1-SNAPSHOT</version>
	<name>rest-service</name>
	<description>Demo project for Spring Boot</description>

	<properties>
		<java.version>11</java.version>

		<azure.resourceGroup>my-app-rg</azure.resourceGroup>
		<azure.appName>my-app-app</azure.appName>
		<azure.os>Windows</azure.os><!-- Windows/Linux -->

	</properties>

	<dependencies>
		<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-starter-web</artifactId>
		</dependency>

		<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-starter-test</artifactId>
			<scope>test</scope>
		</dependency>
	</dependencies>

	<build>
		<plugins>
			<plugin>
				<groupId>org.springframework.boot</groupId>
				<artifactId>spring-boot-maven-plugin</artifactId>
			</plugin>
			<plugin>
				<groupId>com.microsoft.azure</groupId>
				<artifactId>azure-webapp-maven-plugin</artifactId>
				<version>1.14.0</version>
				<configuration>
					<resourceGroup>${azure.resourceGroup}</resourceGroup>
					<appName>${azure.appName}</appName>
					<runtime>
						<os>${azure.os}</os>
						<javaVersion>Java 11</javaVersion>
						<webContainer>Java SE</webContainer>
					</runtime>
					<deployment>
						<resources>
							<resource>
								<directory>${project.basedir}/target</directory>
								<includes>
									<include>*.jar</include>
								</includes>
							</resource>
						</resources>
					</deployment>
				</configuration>
			</plugin>
		</plugins>
	</build>
</project>
```

Upload external config file: `application.properties` to app service: /site/wwwroot. So after deploy there are files:
c:\home\site\wwwroot\app.jar
c:\home\site\wwwroot\application.properties

After succesfull deploy it should react on https://<appname>.azurewebsites.net/greeting

**Setup (please complete the following information):**
 - Azure App Service Windows
 - Java stack 11/SE
 - Spring boot 2.4.5 (note: don't use current spring boot 2.4.6/2.5.0, there is bug)

**Comment by joshfree** [comment]
@stliu could you assist @JV-TMCZ with their question?

**Comment by chenrujun** [comment]
Hi, @JV-TMCZ.

From the [doc](https://docs.microsoft.com/en-us/azure/app-service/faq-app-service-linux#built-in-images), I found the [script](https://github.com/Azure-App-Service/java/blob/dev/shared/init_container.sh#L134). Could you please share your log? I think the startup command should appear in your log.

**Comment by JV-TMCZ** [comment]
@chenrujun That is startup script for linux app service (script line 10:  `A P P   S E R V I C E   O N   L I N U X`)... linux version is (still) working. What I am searching for is exactly the same but for windows ... any idea?

**Comment by chenrujun** [comment]
Hi, @joshfree , could you please assign this issue to app-service team?

**Comment by joshfree** [comment]
@chenrujun you can find contacts here https://dev.azure.com/azure-sdk/internal/_wiki/wikis/internal.wiki/43/Service-Team-Label-and-Contact-List or in the .github/codeowners file
