### ISSUE TITLE
Need to get size of data from EventHub

### ISSUE THREAD

**Issue by koustavnaharoy-ayla** [Azure/azure-sdk-for-java#22043]
**Query/Question**
Need to get size of data from EventHub which was send by upstream application within a certain period of time based on some filter criteria.

***Why is this not a Bug or a feature Request?***
From upstream application we usually send the data to EventHub in the following format.
{
  "metadata": {
    **"oem_id": "xxxxxx",**
    "oem_model": "xxxxxx",
    "dsn": "xxxxxx",
    "property_name": "xxxxxx",
    "display_name": "xxxxxx",
    "base_type": "xxxxxx",
    "event_type": "xxxxxx"
  },
  "datapoint": {
    "id": "xxxxxx",
    "updated_at": "xxxxxx",
    "created_at": "xxxxxx",
    "echo": "xxxxxx",
    "closed": "xxxxxx",
    "value": "xxxxxx",
    "metadata": {},
    "user_uuid": "",
    "discarded": "xxxxxx",
    "scope": "xxxxxx",
    "direction": "output"
  },
  "timestamp": "xxxxxx"
}
We need calculate the total size of data had been send to EventHub within a certain period of time based on a particular oem_id.
Question 1. Is there a API exists for that?

**Setup (please complete the following information if applicable):**
 - OS: [e.g. iOS] Kubernates
 - IDE : [e.g. IntelliJ] IntelliJ
 - Version of the Library used 5.3.1
 
 **Information Checklist**
 Kindly make sure that you have added all the following information above and checkoff the required fields otherwise we will treat the issuer as an incomplete report
- [x] Query Added
- [x] Setup information Added

**Comment by conniey** [comment]
There is additional metadata/fields when serializing EventData into its underlying AMQP message. Currently, we do not expose this API in `EventData`. If you're sending in batches, when you create and use `EventDataBatch`, as you add events into the batch, its size is calculated before adding to the batch. So you can get it [EventDataBatch.getSizeInBytes()](https://azuresdkdocs.blob.core.windows.net/$web/java/azure-messaging-eventhubs/5.7.1/com/azure/messaging/eventhubs/EventDataBatch.html#getSizeInBytes--). 

I hope this helps.
