### ISSUE TITLE
[BUG] can't manage error due to inteactions on B2c 

### ISSUE THREAD

**Issue by letmagnau** [Azure/azure-sdk-for-java#22045]
**Describe the bug**

***Exception or Stack Trace***
Add the exception log and stack trace if available

**To Reproduce**

***Code Snippet***
Add the code snippet that causes the issue.

**Expected behavior**

**Screenshots**

**Setup (please complete the following information):**
 - OS: Linux 
 - IDE :  IntelliJ
 - 3.3

**Additional context**

it seems that are not able to manage this type of response: 

assume you have configured b2c with  an redirect uri  http://localhost:4200/login/oauth2/code/
it works when you do the right steps but , if you click on a back button on b2c , framework redirect to url as 

 Securing GET /login/oauth2/code/?error=access_denied&error_description=AADB2C90091%3a+The+user+has+cancelled+e │
│ ntering+self-asserted+information.%0d%0aCorrelation+ID%3a+17f0927d-faf2-44d0-a4fe-724568f351fd%0d%0aTimestamp%3a+2021-06-03+11%3a41%3a42Z%0d%0a&state= etc..

that are error managed by b2c that the library can't manage

**Comment by alzimmermsft** [comment]
@stliu could you triage this to the appropriate person

**Comment by letmagnau** [comment]
the same about the fogotten password
error#error=access_denied&error_description=AADB2C90118%3a+The+user+has+forgotten+their+password.%0d%0aCorrelation+ID

**Comment by chenrujun** [comment]
Hi, @letmagnau 

Now I'm using [this sample](https://github.com/Azure/azure-sdk-for-java/tree/azure-spring-boot-starter-active-directory_3.5.0/sdk/spring/azure-spring-boot-samples/azure-spring-boot-sample-active-directory-b2c-oidc) to reproduce your problem.

---
## Problem 1:

> it works when you do the right steps but , if you click on a back button on b2c , framework redirect to url as
Securing GET /login/oauth2/code/?error=access_denied&error_description=AADB2C90091%3a+The+user+has+cancelled+e │
│ ntering+self-asserted+information.%0d%0aCorrelation+ID%3a+17f0927d-faf2-44d0-a4fe-724568f351fd%0d%0aTimestamp%3a+2021-06-03+11%3a41%3a42Z%0d%0a&state= etc..

Sorry I can not reproduce this problem. Does `back button on b2c` mean the back button of browser? Like this:
![image](https://user-images.githubusercontent.com/13167207/121139003-dd4f9180-c86a-11eb-9f83-92ad2e1c3fbc.png)


---
## Problem 2:
> the same about the fogotten password
error#error=access_denied&error_description=AADB2C90118%3a+The+user+has+forgotten+their+password.%0d%0aCorrelation+ID

I can not reproduce this problem, did you configure [azure.activedirectory.b2c.user-flows.password-reset](https://github.com/Azure/azure-sdk-for-java/blob/azure-spring-boot-starter-active-directory_3.5.0/sdk/spring/azure-spring-boot-samples/azure-spring-boot-sample-active-directory-b2c-oidc/src/main/resources/application.yml#L10)?

---
## Suggestion:

Please try to use [this sample](https://github.com/Azure/azure-sdk-for-java/tree/azure-spring-boot-starter-active-directory_3.5.0/sdk/spring/azure-spring-boot-samples/azure-spring-boot-sample-active-directory-b2c-oidc) to reproduce your problem. If you problem still exist, please share your application.yml.

**Comment by letmagnau** [comment]
Hi mr chenrujun
but my question seems to be very easy to reproduce... also using the same project
we don't want our client use the back browser action, but we want to use tha CANCEL interaction.. as in the image

![image](https://user-images.githubusercontent.com/1941769/121202846-ea25b280-c875-11eb-8524-6c7dca278447.png)

and  the result was
![image](https://user-images.githubusercontent.com/1941769/121203016-0cb7cb80-c876-11eb-8037-dabcbc22d500.png)

but this happen in all the other managed error of b2c

**Comment by chenrujun** [comment]
Hi, @letmagnau .

Thank you for your detailed description.

Current logic is default logic in spring-security.
Refs:
1. [SimpleUrlAuthenticationFailureHandler](https://github.com/spring-projects/spring-security/blob/5.5.0/web/src/main/java/org/springframework/security/web/authentication/SimpleUrlAuthenticationFailureHandler.java#L95).
2. [DefaultLoginPageGeneratingFilter](https://github.com/spring-projects/spring-security/blob/5.5.0/web/src/main/java/org/springframework/security/web/authentication/ui/DefaultLoginPageGeneratingFilter.java#L299). 


Here is possible solutions about these errors:
1. Use the page generated by `DefaultLoginPageGeneratingFilter`. It's current choice, I think it's acceptable. 
2. Our library generate a web page, it may not satisfy all customers. 
3. Our library eat the error message. It's not good, it may confuse both app user and app developer.
4. App developer DIY their error page in [WebSecurityConfigurerAdapter](https://github.com/Azure/azure-sdk-for-java/blob/azure-spring-boot-starter-active-directory_3.5.0/sdk/spring/azure-spring-boot-samples/azure-spring-boot-sample-active-directory-b2c-oidc/src/main/java/com/azure/spring/sample/aad/b2c/security/WebSecurityConfiguration.java#L21):
```
    protected void configure(HttpSecurity http) throws Exception {
        // @formatter:off
        http.authorizeRequests()
                .anyRequest().authenticated()
                .and()
            .apply(configurer)
            .and()
            .oauth2Login()
            .failureHandler(yourFailureHandler);
        // @formatter:off
    }
```

**Comment by chenrujun** [comment]
Closing this issue because no response from customer for a long time.
