### ISSUE TITLE
[QUERY] java.lang.UnsupportedOperationException: Cannot create XMLStreamReader or XMLEventReader from a org.codehaus.stax2.io.Stax2ByteArraySource

### ISSUE THREAD

**Issue by zcox** [Azure/azure-sdk-for-java#22048]
**Query/Question**
When trying to use various methods in `BlobServiceClient` from `azure-storage-blob` in our unit tests, I get the following runtime exception:

```
java.lang.UnsupportedOperationException: Cannot create XMLStreamReader or XMLEventReader from a org.codehaus.stax2.io.Stax2ByteArraySource
```

One example is simply calling `client.listBlobContainers().iterator()`.

However, these same operations work fine in our running applications. The runtime exception only occurs in unit tests.

I suspect there is some classpath/dependency conflict in our unit tests, but I can't seem to track it down. I'm trying to reproduce this runtime exception in a publicly shareable repo, but have not yet succeeded.

In the meantime, has anyone seen the same runtime exception, and managed to resolve it?

***Why is this not a Bug or a feature Request?***
This is not a bug (yet) because these operations work correctly in our running applications, and only throw the runtime exception in unit tests.

**Setup (please complete the following information if applicable):**
 - `azure-storage-blob` `12.11.1`
 
 **Information Checklist**
 Kindly make sure that you have added all the following information above and checkoff the required fields otherwise we will treat the issuer as an incomplete report
- [x] Query Added
- [x] Setup information Added

**Comment by alzimmermsft** [comment]
Thank you for reporting this issue @zcox. Would it be possible to include the other testing dependencies that you are using as this appears to be a dependency conflict issue.

As for if we've seen this same exception during runtime, based on previously submitted issues the answer is no.

FYI @gapra-msft

**Comment by zcox** [comment]
@alzimmermsft thanks for the quick reply! I'm slowly adding in more dependencies to try to replicate this issue in https://github.com/zcox/azure-storage-blob-test but unfortunately so far that example does not yet throw the `UnsupportedOperationException`. I'll add a comment to this issue if I'm able to replicate the exception.

**Comment by zcox** [comment]
@alzimmermsft I believe I've eliminated classpath/dependencies as the cause of this runtime exception. I updated [the example](https://github.com/zcox/azure-storage-blob-test/blob/main/src/main/scala/Main.scala) to show a reproducible failure (although the runtime exception is similar to, but not quite the same as, the original in this issue).

The runtime exception in the example is now:

```
java.lang.IllegalArgumentException: Can not instantiate Stax reader for XML source type class org.codehaus.stax2.io.Stax2ByteArraySource (unrecognized type)
```

It only occurs when the `BlobServiceClient` is created on a thread from the pool `scala.concurrent.ExecutionContext.global` and only on the second or later (not the first) run of the program in `sbt` where the jvm is not forked.

Although this runtime exception is slightly different from the original, I am able to reproduce the original runtime exception in our internal application's unit test (which unfortunately I cannot share publicly) by creating the `BlobServiceClient` on a thread from the pool `scala.concurrent.ExecutionContext.global`.

This leads me to believe this issue is related to some kind of state or resource not being closed, and possibly tied to certain threads (maybe a `ThreadLocal`?). Does any of this sound familiar to you at all? It's an odd issue, but we'd be very grateful for any leads to figure this out.

**Comment by amishra-dev** [comment]
@zcox /Zach, do you still need help with this?

**Comment by amishra-dev** [comment]
@alzimmermsft / @rickle-msft fyi

**Comment by zcox** [comment]
@amishra-dev honestly I can't remember if we solved this, or simply disabled those unit tests. This is not currently a problem we are facing though. If it resurfaces for us, I will reply here in the future.

**Comment by amishra-dev** [comment]
Thanks Zach. File a new bug and feel free to tag me if the situation changes.
