### ISSUE TITLE
Partitioning Strategy Error

### ISSUE THREAD

**Issue by jsavory-magna** [Azure/azure-sdk-for-java#22066]
Read query fails when using the default or aggressive strategy.  Works with a restrictive or custom strategy.

CosmsoDB Error:

ClassName": "InternalServerErrorException",
  "userAgent": "azsdk-java-cosmos/4.16.0-beta.2 Linux/5.4.0-1046-azure JRE/1.8.0_275",
  "statusCode": 500,
  "error": "{\"Errors\":[\"An unknown error occurred while processing this request. If the issue persists, please contact Azure Support: http://aka.ms/azure-support\"]}",
  "innerErrorMessage": "[\"An unknown error occurred while processing this request. If the issue persists, please contact Azure Support: http://aka.ms/azure-support\"]",

**Comment by alzimmermsft** [comment]
@kushagraThapar could you assign this to the appropriate person

**Comment by kushagraThapar** [comment]
@mbhaskar  - can you please help take a look at this ?

**Comment by xinlian12** [comment]
Close because of inactivity. 
Please try the latest SDK and reopen a new issue if the issue still exists.
