### ISSUE TITLE
[BUG] Folder structure change for FarmBeats

### ISSUE THREAD

**Issue by RGKarthik** [Azure/azure-sdk-for-java#22083]
Can the folder structure for FarmBeats SDK be changed from 'azure-sdk-for-java/sdk/farmbeats' to 'azure-sdk-for-java/sdk/agrifood'.

FarmBeats is a product name and is susceptible to change. Hence, we prefer to use AgriFood

**Comment by RGKarthik** [comment]
cc: @ramya-rao-a

**Comment by ramya-rao-a** [comment]
@jianghaolu, Please make the above change

**Comment by RGKarthik** [comment]
@jianghaolu , Can you please help us with this?
