### ISSUE TITLE
[BUG] No possibility of using parenthesis for closed CriteriaTypes in CosmosDB SDK v4

### ISSUE THREAD

**Issue by PeterVanco** [Azure/azure-sdk-for-java#22087]
**Describe the bug**
CosmosDB SDK v4 does not provide a way to use parenthesis for "closed" **CriteriaType**s (AND, OR). Given the operator precedence, it is not possible to build a query like this:

`x AND (y OR z)`

as all criteria are simply concatenated, which is not always anticipated and of course yields different results:

`x AND y OR z`

***Code Snippet***
```
    Criteria x = Criteria.getInstance(CriteriaType.IS_EQUAL, "x", Collections.singletonList("xVal"), Part.IgnoreCaseType.NEVER);
    Criteria y = Criteria.getInstance(CriteriaType.IS_EQUAL, "y", Collections.singletonList("yVal"), Part.IgnoreCaseType.NEVER);
    Criteria z = Criteria.getInstance(CriteriaType.IS_EQUAL, "z", Collections.singletonList("zVal"), Part.IgnoreCaseType.NEVER);

    Criteria or = Criteria.getInstance(CriteriaType.OR, y, z);
    Criteria and = Criteria.getInstance(CriteriaType.AND, x, or); // results in x AND y OR z
```

**Expected behavior**
There is a possibility to define criteria boundary / priority (parenthesis).

**Setup (please complete the following information):**
 - Library/Libraries:
com.azure:azure-spring-data-cosmos:3.7.0

**Additional context**

Class (method) to investigate:
**com.azure.spring.data.cosmos.core.generator.AbstractQueryGenerator::generateClosedQuery**

We implemented a workaround with class-shading like this:
```
    private String generateClosedQuery(@NonNull String left, @NonNull String right, CriteriaType type) {
        Assert.isTrue(CriteriaType.isClosed(type)
                && CriteriaType.isBinary(type),
            "Criteria type should be binary and closure operation");

        return String.format("(%s %s %s)", left, type.getSqlKeyword(), right);
    }
```

Using this expression, it should be possible to achieve any expected result, if you order the criteria correctly:
`(w AND (x OR (y OR z)))`

Other, probably a much better way would be to introduce a new CriteriaType (PARENTHESIS / PRIORITY), which would simply put criteria taken as an argument into parenthesis.

**Information Checklist**
Kindly make sure that you have added all the following information above and checkoff the required fields otherwise we will treat the issuer as an incomplete report
- [x] Bug Description Added
- [x] Repro Steps Added
- [x] Setup information Added

**Comment by backwind1233** [comment]
Hi, @mbhaskar can you help to look into this issue?

**Comment by Praytic** [comment]
Unfortunately, I have problems running tests with maven. I have tried the command from this guide: https://github.com/Azure/azure-sdk-for-java/wiki/Building
```
mvn install -f sdk/cosmos/azure-spring-data-cosmos/pom.xml  -Dgpg.skip -Drevapi.skip
```
Tests are getting skipped, even without `-DskipTests` flag.

**Comment by trande4884** [comment]
Closing as duplicate. Please track https://github.com/Azure/azure-sdk-for-java/issues/17929
