### ISSUE TITLE
[QUERY]How can I convert SDK response to json from Java Object  using Jackson? I want to convert whole com.azure.resourcemanager.compute.models.VirtualMachine object to jsckson

### ISSUE THREAD

**Issue by deepak9764** [Azure/azure-sdk-for-java#22104]
**Query/Question**
How can I convert SDK response to json from Java Object  using Jackson? I want to convert whole com.azure.resourcemanager.compute.models.VirtualMachine object to jackson

**Comment by weidongxu-microsoft** [comment]
You cannot serialize `VirtualMachine` to JSON as it is an interface.

You can serialize its data model.
`String json = SerializerFactory.createDefaultManagementSerializerAdapter().serialize(vm.innerModel(), SerializerEncoding.JSON);`

**Comment by deepak9764** [comment]
Agree! but when i am doing  String json = SerializerFactory.createDefaultManagementSerializerAdapter().serialize(vm.innerModel(), SerializerEncoding.JSON); it is giving me all tags, properties and  location.
![image](https://user-images.githubusercontent.com/9442694/121126939-9c458600-c846-11eb-8eb3-5cc05f0b1db9.png)


is there any way I can get name, id ,type in json after serialisation
![image](https://user-images.githubusercontent.com/9442694/121127557-90a68f00-c847-11eb-84d8-52ffed75dd91.png)

**Comment by weidongxu-microsoft** [comment]
@deepak9764 

These fields are read-only, so they does not get serialized (along other read-only properties).

```
    @JsonProperty(access = JsonProperty.Access.WRITE_ONLY)
    private String id;

    @JsonProperty(access = JsonProperty.Access.WRITE_ONLY)
    private String name;

    @JsonProperty(access = JsonProperty.Access.WRITE_ONLY)
    private String type;
```

**Comment by weidongxu-microsoft** [comment]
You might try this:

```
    public static class Adapter extends JacksonAdapter {
        public Adapter() {
            super();
            simpleMapper().setAnnotationIntrospector(new JacksonAnnotationIntrospector() {
                @Override
                public JsonProperty.Access findPropertyAccess(Annotated annotated) {
                    JsonProperty.Access access = super.findPropertyAccess(annotated);
                    if (access == JsonProperty.Access.WRITE_ONLY) {
                        return JsonProperty.Access.AUTO;
                    }
                    return access;
                }
            });
        }
    }
```

**Comment by deepak9764** [comment]
private static void getVirtualMachines(AzureResourceManager azureResourceManager) {

		String json;

		for (VirtualMachine virtualMachine : azureResourceManager.virtualMachines().list()) {

			try {

				json = SerializerFactory.createDefaultManagementSerializerAdapter()
						.serialize(virtualMachine.innerModel(), SerializerEncoding.JSON);

				System.out.println(json);
			} catch (IOException e) {

				e.printStackTrace();
			}

		}

	}

	public static class Adapter extends JacksonAdapter {
		public Adapter() {
			super();
			serializer().setAnnotationIntrospector(new JacksonAnnotationIntrospector() {
				@Override
				public JsonProperty.Access findPropertyAccess(Annotated annotated) {
					JsonProperty.Access access = super.findPropertyAccess(annotated);
					if (access == JsonProperty.Access.WRITE_ONLY) {
						return JsonProperty.Access.AUTO;
					}
					return access;
				}
			});
		}
	}
Still getting same response.. let me know if any changes i need to do

**Comment by weidongxu-microsoft** [comment]
What I mean is to use this subclass `Adapter` to do the serialize. I.e.
```
Adapter adapter = new Adapter();
adapter.serialize(virtualMachine.innerModel(), SerializerEncoding.JSON);
```

**Comment by deepak9764** [comment]
private static void getVirtualMachines(AzureResourceManager azureResourceManager) {

		String json;
		Adapter adapter = new Adapter();

		for (VirtualMachine virtualMachine : azureResourceManager.virtualMachines().list()) {

			try {

				json = adapter.serialize(virtualMachine.innerModel(), SerializerEncoding.JSON);

				System.out.println(json);
			} catch (IOException e) {

				e.printStackTrace();
			}

		}

	}

Still getting same response.

**Comment by weidongxu-microsoft** [comment]
Ok, there seems too many configuration in `JacksonAdapter` that `AnnotationIntrospector` no longer works.

In this case I am not much to help.

You can try the `simpleMapper()` instead, but it is not same as the raw JSON send by Azure.

```
    public static class Adapter extends JacksonAdapter {
        public Adapter() {
            super();
            simpleMapper().setAnnotationIntrospector(new JacksonAnnotationIntrospector() {
                @Override
                public JsonProperty.Access findPropertyAccess(Annotated annotated) {
                    JsonProperty.Access access = super.findPropertyAccess(annotated);
                    if (access == JsonProperty.Access.WRITE_ONLY) {
                        return JsonProperty.Access.AUTO;
                    }
                    return access;
                }
            });
        }

        public ObjectMapper simpleMapper() {
            return super.simpleMapper();
        }
    }

        Adapter adapter = new Adapter();
        String json = adapter.simpleMapper().writeValueAsString(inner);
```

**Comment by deepak9764** [comment]
Yes this will work! Thanks @weidongxu-microsoft

**Comment by weidongxu-microsoft** [comment]
Short survey for us to hear you:
https://microsoft.qualtrics.com/jfe/form/SV_ehN0lIk2FKEBkwd?Q_CHL=ISSUES
