### ISSUE TITLE
Azure large file upload 4GB and more getting failed with 413 request Entity Too large

### ISSUE THREAD

**Issue by Dhaval8951** [Azure/azure-sdk-for-java#22140]
@gapra-msft  @rickle-msft 
Hi Team,
Can you please assist for the issue 
When I am uploading file size 4GB or more I am getting 413 request Entity Too large.
Less than this like 3.5 GB working fine.
The issue looks the same as mentioned in https://stackoverflow.com/questions/60082062/azure-application-gateway-file-upload-limits
We have try disabling the WAF , Still issue persist.
Could please assist if there is any configuration or any other guidance would be much helpful to us.

**Comment by gapra-msft** [comment]
Hi @Dhaval8951 

Could you share what API you are trying to use, and what REST call is this error being returned?

**Comment by Dhaval8951** [comment]
@gapra-msft  
Thank you for your prompt response.
We are using BlobOutputStream and writing into it. as mentioned in below snippet.
![image](https://user-images.githubusercontent.com/37213608/121321910-2582b880-c92c-11eb-9a3b-ac254073ddee.png)

But more specifically this is going good without using Azure application gateway. But when project is deployed with AGW Not able to upload large file 4GB+.
We have also tested without and with Chunked in header field but still issue persist. Please refer below screenshots attached for AGW error 413. We have also tried disabling WAF in AGW.
Any assistance would be much helpful 
![withchunked](https://user-images.githubusercontent.com/37213608/121325614-5f08f300-c92f-11eb-8a88-0149959994a2.jpg)
![withoutchun](https://user-images.githubusercontent.com/37213608/121325628-603a2000-c92f-11eb-9669-1d74cdf7eddd.jpg)

**Comment by gapra-msft** [comment]
Hi @Dhaval8951,

Unfortunately I'm not too familiar with Azure Application Gateway but I will ask around and see what I can find

**Comment by gapra-msft** [comment]
In the meantime, could you double check WAF is disabled?

It looks like another mitigation you could employ is setting to an alternate content-type to "multipart/form-data". You can do this by setting BlobHttpHeaders to pass to the BlobOutputStream

**Comment by kasobol-msft** [comment]
The request seems to be rejected by Azure Application Gateway which is presumably fronting your app. I suggest to open issue with Azure Support. Storage SDK repo isn't the right place to seek resolution for that.
