### ISSUE TITLE
[FEATURE REQ] Azure Spring AAD  for Webflux

### ISSUE THREAD

**Issue by philipschikora** [Azure/azure-sdk-for-java#22163]
**Is your feature request related to a problem? Please describe.**
I would love to see the artifact "azure-spring-boot-starter-active-directory" to work with spring webflux

**Describe the solution you'd like**
Just as with spring mvc it should be possible to apply easy configuration in the application.config and have it working with webflux

**Comment by chenrujun** [comment]
Closing this issue. Use this one instead: https://github.com/Azure-Samples/spring-boot-application-with-azure-active-directory/issues/6

**Comment by chenrujun** [comment]
Not this issue is tracked by this one: https://github.com/Azure/azure-sdk-for-java/issues/21290
