### ISSUE TITLE
Follow-up AMQP mock test

### ISSUE THREAD

**Issue by YijunXieMS** [Azure/azure-sdk-for-java#22247]
Revisit these three mock tests for core-amqp ReactorConnection

createManagementNode()
cannotCreateResourcesOnFailure()
endpointStatesTransportError()

**Comment by samvaity** [comment]
@conniey do you know if this issue is still relevant?

**Comment by conniey** [comment]
Yes. These tests are still disabled because their issues have not been addressed.
