### ISSUE TITLE
[QUERY] Azure ServiceBus client classes: final vs open

### ISSUE THREAD

**Issue by sergiusz-n** [Azure/azure-sdk-for-java#22253]
**Query/Question**
I am curious why _clients_ from [Azure Event Hub SDK](https://github.com/Azure/azure-sdk-for-java/tree/master/sdk/eventhubs/azure-messaging-eventhubs) -- e.g. [EventHubConsumerAsyncClient](https://github.com/Azure/azure-sdk-for-java/blob/master/sdk/eventhubs/azure-messaging-eventhubs/src/main/java/com/azure/messaging/eventhubs/EventHubConsumerAsyncClient.java#L60), [EventHubConsumerClient](https://github.com/Azure/azure-sdk-for-java/blob/master/sdk/eventhubs/azure-messaging-eventhubs/src/main/java/com/azure/messaging/eventhubs/EventHubConsumerClient.java#L40), [EventHubProducerAsyncClient](https://github.com/Azure/azure-sdk-for-java/blob/master/sdk/eventhubs/azure-messaging-eventhubs/src/main/java/com/azure/messaging/eventhubs/EventHubProducerAsyncClient.java#L96) etc are open for extensions, whereas [Azure Service Bus SDK](https://github.com/Azure/azure-sdk-for-java/tree/master/sdk/servicebus/azure-messaging-servicebus) provides clients 
[ServiceBusSenderClient](https://github.com/Azure/azure-sdk-for-java/blob/master/sdk/servicebus/azure-messaging-servicebus/src/main/java/com/azure/messaging/servicebus/ServiceBusSenderClient.java#L32)
[ServiceBusSenderAsyncClient](https://github.com/Azure/azure-sdk-for-java/blob/master/sdk/servicebus/azure-messaging-servicebus/src/main/java/com/azure/messaging/servicebus/ServiceBusSenderAsyncClient.java#L75)
[ServiceBusReceiverClient](https://github.com/Azure/azure-sdk-for-java/blob/master/sdk/servicebus/azure-messaging-servicebus/src/main/java/com/azure/messaging/servicebus/ServiceBusReceiverClient.java#L36)
[ServiceBusReceiverAsyncClient](https://github.com/Azure/azure-sdk-for-java/blob/master/sdk/servicebus/azure-messaging-servicebus/src/main/java/com/azure/messaging/servicebus/ServiceBusReceiverAsyncClient.java#L91)
[ServiceBusProcessorClient](https://github.com/Azure/azure-sdk-for-java/blob/master/sdk/servicebus/azure-messaging-servicebus/src/main/java/com/azure/messaging/servicebus/ServiceBusProcessorClient.java#L55)
as _final_.

Would you comment on that inconsistency?

***Why is this not a Bug or a feature Request?***
There are a few cases when having clients open for extensions would be beneficial.
Another option could be extracting public methods to the public interface. that was the approach used in the previous ServiceBus SDK (https://github.com/Azure/azure-service-bus-java).

**Setup (please complete the following information if applicable):**
N/A
 
 **Information Checklist**
 Kindly make sure that you have added all the following information above and checkoff the required fields otherwise we will treat the issuer as an incomplete report
- [ x ] Query Added
- [ x ] Setup information Added

**Comment by alzimmermsft** [comment]
@conniey @hemanttanwar @YijunXieMS could you provide clarification on this question?

**Comment by conniey** [comment]
It was an oversight when releasing Event Hubs. We generally expect our clients to be final. You can see more information here in the Java guidelines. https://azure.github.io/azure-sdk/java_introduction.html#service-client

What is your user scenario for extending the service client?

**Comment by sergiusz-n** [comment]
The use case was OpenTracing instrumentation for clients following the delegation pattern used in the most of opentracing-contrib (e.g. [TracingMessageConsumer](https://github.com/opentracing-contrib/java-jms/blob/master/opentracing-jms-common/src/main/java/io/opentracing/contrib/jms/common/TracingMessageConsumer.java) or [TracedExecutor](https://github.com/opentracing-contrib/java-concurrent/blob/master/src/main/java/io/opentracing/contrib/concurrent/TracedExecutor.java).)
Azure _clients_ is neither open nor implementing some public interface.

So, the intention was to have something like that:
```java
public class TracedServiceBusSenderClient  implements SomePublicInterfaceForServiceBusSenderClient  {

    protected final Tracer tracer;
    private final SomePublicInterfaceForServiceBusSenderClient  delegate;
    ...
    public TracedServiceBusSenderClient(SomePublicInterfaceForServiceBusSenderClient senderClient, Tracer tracer) {
        this.delegate = senderclient;
        this.tracer = tracer;
    }
} 
```

**Comment by YijunXieMS** [comment]
Hi @sergiusz-n does it work that you define an interface and have two different implementations that wrap the service bus client? One implementation has tracer and another one doesn't have tracer?

**Comment by szymonjach96** [comment]
Hi,

I feel that wrapping client inside other classes is somekind of workaround.

The other issue, that I see with having that class final is fact that in tests, you are not able to create mock for that class anyhow. You have to do same weird wrapping, which is not handy

**Comment by conniey** [comment]
We do have tracing in our library with an open telemetry plugin. https://docs.microsoft.com/en-us/azure/developer/java/sdk/tracing you can also write your own tracer and add that to the classpath.
