### ISSUE TITLE
Need to have the link of the java SDK for the recently introduced Azure Event Hubs Premium

### ISSUE THREAD

**Issue by koustavnaharoy-ayla** [Azure/azure-sdk-for-java#22287]
**Query/Question**
Need to have the link of the java SDK for recently introduced Azure Event Hubs Premium https://techcommunity.microsoft.com/t5/messaging-on-azure/announcing-azure-event-hubs-premium-public-preview/ba-p/2382082

***Why is this not a Bug or a feature Request?***
This is not a bug, it's a query

**Setup (please complete the following information if applicable):**
 - OS: [e.g. iOS] Kubernates
 - IDE: [e.g. IntelliJ] IntelliJ
 - Library/Libraries: [e.g. com.azure:azure-core:1.16.0 (groupId:artifactId:version)]
 
 **Information Checklist**
 Kindly make sure that you have added all the following information above and checkoff the required fields otherwise we will treat the issuer as an incomplete report
- [x] Query Added
- [x] Setup information Added

**Comment by conniey** [comment]
@ramya-rao-a Do you know if we need to have a link in this blog?

**Comment by ramya-rao-a** [comment]
Thanks for reporting @koustavnaharoy-ayla 

If we are to add a link to SDKs from a blog, then I would expect links to SDKs in all languages are included and not just Java. Or links to the quickstarts we have for all languages.

Assigning this issue to the blog author @kasun04 for follow up

**Comment by kasun04** [comment]
Updated blog post to include quick start guide that points to examples which are written using all the languages that we support.

**Comment by kasun04** [comment]
Updated blog post to include quick start guide that points to examples which are written using all the languages that we support.
