### ISSUE TITLE
[BUG] Connection drops using Azure Spring Cloud Stream Binder ServiceBus Topic

### ISSUE THREAD

**Issue by Manuel-Moya** [Azure/azure-sdk-for-java#22288]
**Describe the bug**
Past several hours, some connection issue stops the servicebus functionality.

***Exception or Stack Trace***
https://github.com/Azure/azure-sdk-for-java/pulls

**Repro Steps**
Using the sample is happening as well.

**Setup (please complete the following information):**
 - OS: Windows 10
 - IDE: IntelliJ
 - Library/Libraries: com.azure.spring: azure-spring-cloud-stream-binder-servicebus-topic 2.5

**Additional context**

**Information Checklist**
Kindly make sure that you have added all the following information above and checkoff the required fields otherwise we will treat the issuer as an incomplete report
- [X] Bug Description Added
- [x] Repro Steps Added
- [X] Setup information Added

**Comment by yiliuTo** [comment]
@lzc-1997-abel please help to look into this. @Manuel-Moya could you provide the sample link that you mentioned?

**Comment by lzc-1997-abel** [comment]
@Manuel-Moya  could you provide the Exception or Stack Trace

**Comment by Manuel-Moya** [comment]
> @Manuel-Moya could you provide the Exception or Stack Trace

Sorry, I did not add the following dependencyManagement
    <dependencyManagement>
        <dependencies>
            <dependency>
                <groupId>org.springframework.cloud</groupId>
                <artifactId>spring-cloud-dependencies</artifactId>
                <version>2020.0.2</version> 
                <type>pom</type>
                <scope>import</scope>
            </dependency>
            <dependency>
                <groupId>com.azure</groupId>
                <artifactId>azure-core</artifactId>
                <version>1.16.0</version> 
            </dependency>
        </dependencies>
    </dependencyManagement>

I added it yesterday, and the microservice is working properly since then. Could this be the issue?

Best regards.

**Comment by lzc-1997-abel** [comment]
@Manuel-Moya 
According to your description, I only got ERROR: `Cannot create receive link from a closed session` after putting the device to sleep and waking up again. I think this is not your issue, because the session will be opened soon.
So I can't determine the root cause, if you still have problems, you can provide a method to reproduce the problem and more information about the error (such as log).🙏

**Comment by Manuel-Moya** [comment]
> @Manuel-Moya
> According to your description, I only got ERROR: `Cannot create receive link from a closed session` after putting the device to sleep and waking up again. I think this is not your issue, because the session will be opened soon.
> So I can't determine the root cause, if you still have problems, you can provide a method to reproduce the problem and more information about the error (such as log).🙏

Please, find attached the log.

[extract-2021-06-15_12-06-64.xlsx](https://github.com/Azure/azure-sdk-for-java/files/6668249/extract-2021-06-15_12-06-64.xlsx)

**Comment by lzc-1997-abel** [comment]
@Manuel-Moya 
I tried to disconnect the network after the application was started.
The error log was very similar to the log you provided, but when I connected to the network, the connect was quickly re-established and the servicebus function was restored. Have you try to use the servicebus function again later?
And this problem will appear even if `dependencyManagement` is added.

**Comment by Manuel-Moya** [comment]
> @Manuel-Moya
> I tried to disconnect the network after the application was started.
> The error log was very similar to the log you provided, but when I connected to the network, the connect was quickly re-established and the servicebus function was restored. Have you try to use the servicebus function again later?
> And this problem will appear even if `dependencyManagement` is added.

Yes, I tried to use the servicebus function again and it was not working, it did not reconnect ( other services did it ).

**Comment by lzc-1997-abel** [comment]
@Manuel-Moya 
Can you provide the pom file or sample of your project? And can you provide a way to reproduce the problem?🙏

**Comment by yiliuTo** [comment]
Close this issue due to no response from the customer for a long period. Please reopen it if you still meet this issue and please provide enough information to help us reproduce it.
