### ISSUE TITLE
ShareFileClient should throw a more specific exception when an operation times out

### ISSUE THREAD

**Issue by domainname** [Azure/azure-sdk-for-java#22316]
Many methods in ShareFileClient.java throw `RuntimeException` when an operation times out. For example, https://github.com/Azure/azure-sdk-for-java/blob/d4eabeef575e7c4892f442ffcb79aa93ecdd3854/sdk/storage/azure-storage-file-share/src/main/java/com/azure/storage/file/share/ShareFileClient.java#L917-L925

This exception is too generic. It would be better if they throw a specific exception for timeout.

**Comment by gapra-msft** [comment]
Hi @domainname 

Thank you for reporting this issue.

I believe this may just be a documentation bug but we will double check and update accordingly.

**Comment by domainname** [comment]
Hi @gapra-msft 

thank you for your reply. It appears that the RuntimeException is thrown by Reactor. Doesn't look like a doc bug to me.

**Comment by domainname** [comment]
After some experiments, I found that Reactor throws IllegalStateException when timeout occurs.

```
java.lang.IllegalStateException: Timeout on blocking read for 1000000 NANOSECONDS
	at reactor.core.publisher.BlockingSingleSubscriber.blockingGet(BlockingSingleSubscriber.java:123)
	at reactor.core.publisher.Mono.block(Mono.java:1727)
	at com.azure.storage.common.implementation.StorageImplUtils.blockWithOptionalTimeout(StorageImplUtils.java:130)
        ...
```
