### ISSUE TITLE
Should we change the Spring App Configuration telemetry User Agent header to follow the Spring guidelines?

### ISSUE THREAD

**Issue by saragluna** [Azure/azure-sdk-for-java#22339]
Now other Spring starters use User Agent following such guideline:

az: for Azure
sp: for Spring
sc: for Spring Cloud
sd: for Spring Data
ss: for Spring Streams
kv: for Key Vault
sb: for Storage Blobs
sf: for Storage Files
eh: for Event Hub
bus: for Service Bus
cfg: for App Config
cos: for Cosmos
aad: for AAD
b2c: for AAD B2C
 

So the key vault Spring module will have app id like: az-sp-kv/2.2.0

However, now the Spring App Configuration uses UA like https://github.com/Azure/azure-sdk-for-java/blob/c7d53ebf07f4b5c3ee41fc9964b6355665455fa6/sdk/appconfiguration/azure-spring-cloud-appconfiguration-config/src/main/java/com/microsoft/azure/spring/cloud/config/pipline/policies/BaseAppConfigurationPolicy.java#L20. Should we change the UA to follow Azure Spring guideline? 

One more thing is, we'd better plot the usage of Spring App Config and App Config SDK in the same BI report, to show the proportion of Java users using the Spring starter for App Configuration.

**Comment by backwind1233** [comment]
vote: 👍

**Comment by mrm9084** [comment]
@saragluna I will do it, we will need to make sure it doesn't mess with any of App Configurations own telemetry as we use the current setup.

**Comment by stliu** [comment]
is it still valid? and if it is, shall we plan it soon, since it's been a long time no update for this one

**Comment by mrm9084** [comment]
Is there a reason for the change. It would just muddle with the App Configuration Service Telemetry.
