### ISSUE TITLE
[QUERY] Get results of asynchrously executed commands on Virtual Machine.

### ISSUE THREAD

**Issue by mayankkthr** [Azure/azure-sdk-for-java#22377]
**Query/Question**
I have long running bash scripts to be executed on Virtual Machine. I will prefer to trigger it asynchronously and provide an API to the user to check the script status/outputs.

Basically I am looking for java alternative of the documentation on below links. Could some please share code samples for the same? That would be a great help.

https://docs.microsoft.com/en-us/rest/api/compute/virtual-machine-run-commands/create-or-update
https://docs.microsoft.com/en-us/rest/api/compute/virtual-machine-run-commands/get

What I am thinking it to provide your with the command id and then using command id user should check the script outputs.

***Why is this not a Bug or a feature Request?***
There is already a documentation of this request, so I think there should be a java way of doing it.

**Comment by joshfree** [comment]
Hi @mayankkthr, you can access the management plane Java SDKs from https://azure.github.io/azure-sdk/releases/latest/mgmt/java.html.  @yungezz can also help provide more info if there are other questions.

Thanks

**Comment by yungezz** [comment]
add @weidongxu-microsoft to help

**Comment by weidongxu-microsoft** [comment]
`azure.virtualMachines().manager().serviceClient().getVirtualMachineRunCommands().createOrUpdate(...)`
`azure.virtualMachines().manager().serviceClient().getVirtualMachineRunCommands().get(...)`

**Comment by mayankkthr** [comment]
@joshfree @yungezz Thank you for your responses.
@weidongxu-microsoft Thank you for your response. I think this would work. I will review this code piece by placing it in my code and write back here with the feedback.

**Comment by mayankkthr** [comment]
@weidongxu-microsoft I am getting compilation error for serviceClient() method. Method not found !!

**Comment by weidongxu-microsoft** [comment]
@mayankkthr Are you sure you are using this SDK?
https://github.com/Azure/azure-sdk-for-java/tree/main/sdk/resourcemanager

**Comment by mayankkthr** [comment]
@weidongxu-microsoft You are correct. I am using old SDK in my code. In fact I was not aware that a new Java SDK is release.
It seems that we need to go through this migration process - https://github.com/Azure/azure-sdk-for-java/blob/main/sdk/resourcemanager/docs/MIGRATION_GUIDE.md
Anyways  thank you for your help. I am closing this ticket.

**Comment by weidongxu-microsoft** [comment]
Short survey for us to hear you:
https://microsoft.qualtrics.com/jfe/form/SV_ehN0lIk2FKEBkwd?Q_CHL=ISSUES
