### ISSUE TITLE
[BUG] AADResourceServerWebSecurityConfigurerAdapter multiconfig security impact the other config

### ISSUE THREAD

**Issue by yvandupre** [Azure/azure-sdk-for-java#22382]
**Describe the bug**
In a spring boot 2.5.1 application, I use  azure-spring-boot-starter-active-directory

I create a class who has 2 specific configuration for security. One for the ui and another for a api. 
Both use jwt.

In my application.properties this line is used for the ui
_spring.security.oauth2.resourceserver.jwt.jwk-set-uri=https://login.microsoftonline.com/2fc25658-12c4-22bf-913c-cb9ae315a689/discovery/v2.0/keys_

Theses lines are needed for AADResourceServerWebSecurityConfigurerAdapter
_azure.activedirectory.client-id=4382fb93-ee2a-2c44-ad61-ee6b9095922a
azure.activedirectory.ap-id-uri=https://nonprod.api.acme.com_

If my app use only one configuration security that work. So i know my code of ApiJwtSecurityConfig  and JwtWebSecurityConfig  are valid.  It's AADResourceServerWebSecurityConfigurerAdapter do some configuration in the background who affect the other one.

I tried to replace the second configuration by a http basic setup... but get same result.

***Exception or Stack Trace***
There are no exception, only an error about token no valid.

**To Reproduce**
Create a class with two different security config.
Only one will work, the one who extends AADResourceServerWebSecurityConfigurerAdapter

***Code Snippet***

```
@Configuration
@EnableWebSecurity
@EnableGlobalMethodSecurity(prePostEnabled = true)
public class WebSecurityConfig extends WebSecurityConfigurerAdapter {

    @Configuration
    @Order(1)
    public static class ApiJwtSecurityConfig extends  AADResourceServerWebSecurityConfigurerAdapter{

        @Override
        protected void configure(HttpSecurity http) throws Exception {

            super.configure(http);
            http.csrf().disable()
                 .sessionManagement().sessionCreationPolicy(SessionCreationPolicy.STATELESS).and()
                 .antMatcher("/v1/cr/api/**")
                 .authorizeRequests().antMatchers(HttpMethod.GET, "/v1/cr/api/32/**", "/v1/cr/api/34/pr/ba/**").hasAuthority("APPROLE_nonprod/full_access")
                .antMatchers(HttpMethod.POST, "/v1/cr/api/18/pr/create").hasAuthority("APPROLE_nonprod/full_access");
          
       }
   }

    @Configuration
    @Order(2)
    public static class JwtWebSecurityConfig extends WebSecurityConfigurerAdapter {

        private JwtAuthenticationConverter jwtAuthenticationConverter() {
            JwtGrantedAuthoritiesConverter jwtGrantedAuthoritiesConverter = new JwtGrantedAuthoritiesConverter();
            jwtGrantedAuthoritiesConverter.setAuthoritiesClaimName("roles");
            jwtGrantedAuthoritiesConverter.setAuthorityPrefix("ROLE_");
            JwtAuthenticationConverter jwtAuthenticationConverter = new JwtAuthenticationConverter();
            jwtAuthenticationConverter.setJwtGrantedAuthoritiesConverter(jwtGrantedAuthoritiesConverter);
            return jwtAuthenticationConverter;
        }

        @Override
        protected void configure(HttpSecurity http) throws Exception {

            http.cors().configurationSource(request -> new CorsConfiguration().applyPermitDefaultValues())
                    .and().sessionManagement().sessionCreationPolicy(SessionCreationPolicy.STATELESS)
                    .and() // (1)
                    .authorizeRequests()
                    .anyRequest().authenticated() // (2)
                    .and()
                    .oauth2ResourceServer().jwt() // (3)
                    .jwtAuthenticationConverter(jwtAuthenticationConverter());
        }

        @Override
        public void configure(WebSecurity web) throws Exception {
            web.ignoring().antMatchers("/v2/api-docs", "/actuator/**");
        }
    }


}
```

**Expected behavior**
Both method of security should work

**Setup (please complete the following information):**
Windows / linux
LIbrairie: com.azure.spring: azure-spring-boot-starter-active-directory:3.5.0

**Information Checklist**
Kindly make sure that you have added all the following information above and checkoff the required fields otherwise we will treat the issuer as an incomplete report
- [ x] Bug Description Added
- [ x] Repro Steps Added
- [x ] Setup information Added

**Comment by joshfree** [comment]
Hi @yvandupre, someone from the `azure-spring` team will follow up with you shortly

**Comment by chenrujun** [comment]
Hi, @yvandupre .
Thank you for reaching out.
Now azure-spring-boot-starter-active-directory does not support webapp and resource-server in one application.
My current plan is to support it in August release.
And I'm closing this issue because it's duplicated with #19816
