### ISSUE TITLE
Plan for generated models vs handwritten models in implementation

### ISSUE THREAD

**Issue by gapra-msft** [Azure/azure-sdk-for-java#22391]
InternalBlobLegalHoldResult is a handwritten model in the generated models package. This is concerning since someone might accidentally decide to wipe out the generated models entirely and regenerate.

**Comment by alzimmermsft** [comment]
If the concern is around regeneration potentially deleting the class it could be generated using the following options:

1. Adding a Swagger transform which as the class as a new definition
2. Using the post-generation code modification framework to add an entirely new class
3. Mixture of 1 and 2 where the Swagger definition does the heavy lifting while post-generation code modifications perform small changes to get the exact structure wanted

**Comment by alzimmermsft** [comment]
I'm going to close this issue as the code won't compile if this scenario happens which will prevent something like this being checked in.
