### ISSUE TITLE
[BUG] com.azure.cosmos.spark infer schema doesn't work correctly

### ISSUE THREAD

**Issue by em-daniil-terentyev** [Azure/azure-sdk-for-java#22415]
Hi everybody.

There is bug in driver com.azure.cosmos.spark.
When i extract data from Azure Cosmos DB with Azure Databricks and enable inferring of schema, field that contains array in cosmos db displayed as empty.

Could you please look into this and make it work as it was in previous version of driver.

Thanks in advance.

Regards,
Daniil.

**Comment by joshfree** [comment]
Hi @em-daniil-terentyev, someone from the `cosmos` team will follow up with you shortly.

**Comment by kushagraThapar** [comment]
@moderakh  - please route this appropriately.

**Comment by moderakh** [comment]
@em-daniil-terentyev Could you please provide a sample repro:
1. document content
2. spark code
3. spark connector version

**Comment by ealsur** [comment]
Might be solved by https://github.com/Azure/azure-sdk-for-java/pull/21933, this added collision resolution also for Array types (which was present in Spark 2 Connector ). If the Arrays had different element Type or if the property was an Array in one document and `null` in the other.

**Comment by em-daniil-terentyev** [comment]
In com.azure.cosmos.spark:azure-cosmos-spark_3-1_2-12:4.2.0 it's fixed
