### ISSUE TITLE
[BUG] SqlFailoverGroupImpl.withoutDatabaseId does not delete database from Failover Group

### ISSUE THREAD

**Issue by pknapek2** [Azure/azure-sdk-for-java#22410]
**Describe the bug**
SqlFailoverGroupImpl.withoutDatabaseId does not take into account method parameter and does not delete database from failover group
https://github.com/Azure/azure-sdk-for-java/blob/aa466ff9e0f5c3f554997a88ef1e4d72f00bd90f/sdk/resourcemanager/azure-resourcemanager-sql/src/main/java/com/azure/resourcemanager/sql/implementation/SqlFailoverGroupImpl.java#L368

***Exception or Stack Trace***
Not needed

**To Reproduce**
1. Initialize SqlServer instance
2. Get Failover Group
3. Invoke failoverGroup.update().withoutDatabaseId("<db_id>").apply();

***Code Snippet***
As wrote in description, instead of:
            `this.innerModel().databases().remove(key);`
There should be:
            `this.innerModel().databases().remove(id);`

**Expected behavior**
Database is deleted from SQL Failover Group

**Screenshots**
Not needed

**Setup (please complete the following information):**
 - OS: Linux
 - IDE: IntelliJ
 - Library/Libraries: com.microsoft.azure:azure-mgmt-resources:1.41.1

**Additional context**

**Information Checklist**
Kindly make sure that you have added all the following information above and checkoff the required fields otherwise we will treat the issuer as an incomplete report
- [x] Bug Description Added
- [x] Repro Steps Added
- [x] Setup information Added

**Comment by joshfree** [comment]
Hi @pknapek2, someone from the `azure-mgmt` team will follow up with you shortly.

**Comment by yungezz** [comment]
add @weidongxu-microsoft to help on this.

**Comment by weidongxu-microsoft** [comment]
Fixed in 2.8.0

Short survey for us to hear you:
https://microsoft.qualtrics.com/jfe/form/SV_ehN0lIk2FKEBkwd?Q_CHL=ISSUES
