### ISSUE TITLE
[BUG] ClassCastException: reactor.core.publisher.FluxTimeout cannot be cast to com.azure.core.http.rest.PagedFlux

### ISSUE THREAD

**Issue by andreasherkner** [Azure/azure-sdk-for-java#22411]
**Describe the bug**
Usage of some methods from com.azure.data.tables.TableClient causes ClassCastExceptions:
TableClient#getAccessPolicies()
TableClient#getAccessPoliciesWithResponse(Duration, Context)
TableClient#listEntities(ListEntitiesOptions, Duration, Context) with non-null values for Duration and Context

***Exception or Stack Trace***
```
Exception in thread "main" java.lang.ClassCastException: reactor.core.publisher.FluxTimeout cannot be cast to com.azure.core.http.rest.PagedFlux
	at com.azure.data.tables.implementation.TableUtils.applyOptionalTimeout(TableUtils.java:134)
	at com.azure.data.tables.TableClient.listEntities(TableClient.java:469)
```

**To Reproduce**
Execute code snippet

***Code Snippet***

```
public static void main(final String[] args) {

        TableClient tableClient = new TableClientBuilder()
                .connectionString("myConnectionString") 
                .tableName("myTable")
                .buildClient();

        ListEntitiesOptions options = new ListEntitiesOptions();
        options.setTop(1);
        tableClient.listEntities(options, Duration.ofSeconds(2), Context.NONE);

    }
```

**Setup (please complete the following information):**
 - OS: Windows 10
 - IDE: eclipse
 - Library/Libraries: com.azure:azure-core:1.17.0, com.azure:azure-data-tables:12.0.0, io.projectreactor:reactor-core:3.4.6

**Information Checklist**
Kindly make sure that you have added all the following information above and checkoff the required fields otherwise we will treat the issuer as an incomplete report
- [x] Bug Description Added
- [x] Repro Steps Added
- [x] Setup information Added

**Comment by alzimmermsft** [comment]
@vcolin7 could you take a look at this

**Comment by vcolin7** [comment]
Hi @andreasherkner, thanks for reporting this issue.

I only found this issue in methods that return a `PagedFlux` and that take a `timeout` parameter: `TableClient.listEntities()` and `TableServiceClient.listTables()`. I was not able to get a `ClassCastException` in the `getAccessPolicies()` and `getAccessPoliciesWithResponse()` methods, so I was wondering if you could share a code sample where this can be reproduced.

In the meantime, I have created [a pull request](https://github.com/Azure/azure-sdk-for-java/pull/22511) with a fix for the first two methods I mentioned which will be included in our next release early next month.

**Comment by andreasherkner** [comment]
Hi @vcolin7,

I'm not able to reproduce it today. But I'm pretty sure, I could reproduce it last time I created the issue ;)

**Comment by vcolin7** [comment]
If you see this again when calling `getAccessPolicies()`, would you mind re-opening this issue and adding the exception stacktrace? Thanks!

**Comment by andreasherkner** [comment]
I will do that :)
