### ISSUE TITLE
Test improvement: Get rid of duplicate setup code that prints test name, centralize that logic

### ISSUE THREAD

**Issue by gapra-msft** [Azure/azure-sdk-for-java#22448]
we should spend some time investigating if this can be centralized. This isn't DRY and kind of clutters the codebase.
I was playing with Global Extensions (see https://spockframework.org/spock/docs/1.1/extensions.html) but ran into some classpath problems in commons... might be worth revisiting this.

**Comment by rnpmsft** [comment]
#22573
