### ISSUE TITLE
Illegal connection string parameter name: TransportType when connecting to a ServiceBus

### ISSUE THREAD

**Issue by florentpln** [Azure/azure-sdk-for-java#22445]
I have an issue when changing from azure-spring-cloud-stream-binder-servicebus-queue 2.4.0 to 2.5.0, I try to connect to a service bus queue using websocket and spring boot, and now I have the following error "TransportType when connecting to a ServiceBus"

The connection String I use is:
spring.cloud.azure.servicebus.connection-string=Endpoint=sb://aaaa.servicebus.windows.net/;TransportType=AmqpWebSockets;SharedAccessKeyName=RootManageSharedAccessKey;SharedAccessKey=*****

Is there another way to specify the TransportType than specifying in the connection-string setting?
Thank you for you help!

**Comment by zhichengliu12581** [comment]
@florentpln, thanks for the reporting, we will fix it soon

**Comment by zhichengliu12581** [comment]
@florentpln, thank you for reporting this issue. I have a [pull request](https://github.com/Azure/azure-sdk-for-java/pull/22604) with a fix and will ship it with the next version.

**Comment by yiliuTo** [comment]
Close this PR for bug has been fixed, please look forward to our next release for this fix. And reopen it if you still have problem configuring transport type.
