### ISSUE TITLE
[FEATURE REQ] Checkstyle should catch star imports.

### ISSUE THREAD

**Issue by kasobol-msft** [Azure/azure-sdk-for-java#22447]
Can we please enable https://checkstyle.sourceforge.io/apidocs/com/puppycrawl/tools/checkstyle/checks/imports/AvoidStarImportCheck.html analyzer? We keep running into star imports in PRs. We'd like to use automation to catch this.

**Comment by kasobol-msft** [comment]
It seems to be enabled for what we release https://github.com/Azure/azure-sdk-for-java/blob/2f78e86ad9cfc084271fcbd2160515317a7e2806/eng/code-quality-reports/src/main/resources/checkstyle/checkstyle.xml#L63
But not for tests
https://github.com/Azure/azure-sdk-for-java/blob/2f78e86ad9cfc084271fcbd2160515317a7e2806/eng/code-quality-reports/src/main/resources/checkstyle/checkstyle-suppressions.xml#L37

**Comment by alzimmermsft** [comment]
Our Checkstyle rules do include this check: https://github.com/Azure/azure-sdk-for-java/blob/main/eng/code-quality-reports/src/main/resources/checkstyle/checkstyle.xml#L63

But it may be suppressed by one of the more generic suppressions that exists. The following suppression suppresses the check in test files, but I think that could be removed.

 https://github.com/Azure/azure-sdk-for-java/blob/main/eng/code-quality-reports/src/main/resources/checkstyle/checkstyle-suppressions.xml#L37
