### ISSUE TITLE
[BUG] Wrong logging format used in JacksonAdapter

### ISSUE THREAD

**Issue by d-schmidt** [Azure/azure-sdk-for-java#22443]
https://github.com/Azure/azure-sdk-for-java/blob/532d427683d51fbd1e40bf9478cb69b3c7b57abd/sdk/core/azure-core/src/main/java/com/azure/core/util/serializer/JacksonAdapter.java#L503

http://www.slf4j.org/api/org/slf4j/helpers/MessageFormatter.html

It uses %s instead of {}:

    2021-06-22 11:38:19,949 DEBUG [com.azure.core.util.serializer.JacksonAdapter] User setter %s on class %s to set header collection.

**Comment by alzimmermsft** [comment]
Thank you for submitting this issue @d-schmidt. I've filed a PR to resolve this error.
