### ISSUE TITLE
Add Samples on Using azure-core-test to Write Azure SDK Tests

### ISSUE THREAD

**Issue by alzimmermsft** [Azure/azure-sdk-for-java#22455]
Add samples of using `azure-core-test` when writing common Azure SDK tests.

- [ ] Extending from `TestBase`
    - [ ] Using before and after test hooks
- [ ] Leveraging `TestResourceNamer` to capture randomized data into test records

**Comment by samvaity** [comment]
This covers details around test infrastructure and framework https://github.com/Azure/azure-sdk-for-java/blob/main/sdk/core/azure-core-test/RecordingMigrationGuide.md
