### ISSUE TITLE
[BUG] API reference docs not showing up for Farm Beats

### ISSUE THREAD

**Issue by ramya-rao-a** [Azure/azure-sdk-for-java#22469]
Go to https://docs.microsoft.com/java/api and search for "farm" in the search box. There are 0 results. We should have seen results corresponding to the API reference docs for https://search.maven.org/artifact/com.azure/azure-verticals-agrifood-farming

**Comment by ramya-rao-a** [comment]
cc @RGKarthik

**Comment by RGKarthik** [comment]
@alzimmermsft  - Can you please check on this?

**Comment by scbedd** [comment]
This is now resolved pending publishing. [See merged PR to `live`](https://github.com/Azure/azure-docs-sdk-java/pull/2078)

![image](https://user-images.githubusercontent.com/45376673/127074832-972d353d-3aea-44d3-8fe8-3a774c95ef0a.png)
