### ISSUE TITLE
Fix problems found when release Azure Spring June.

### ISSUE THREAD

**Issue by chenrujun** [Azure/azure-sdk-for-java#22487]
1. add `azure-security-keyvault-jca` and `azure-spring-boot-starter-keyvault-certificates` in `eng/jacoco-test-coverage/pom.xml`?
2. Set `azure-security-test-keyvault-jca/pom.xml`'s version to `1.0.0-beta.1`.

Refer to :https://github.com/Azure/azure-sdk-for-java/issues/21962

**Comment by backwind1233** [comment]
>Set azure-security-test-keyvault-jca/pom.xml's version to 1.0.0-beta.1.
@chenrujun  I am not sure whether it will work, the pipeline may fail, but we may have a try.

**Comment by chenrujun** [comment]
@backwind1233 

Thank you for your information, I'll investigate after you finished release.
