### ISSUE TITLE
Embedded/local event hub for integration tests

### ISSUE THREAD

**Issue by vivin** [Azure/azure-sdk-for-java#22496]
**Is your feature request related to a problem? Please describe.**

I'm frustrated by the inability to run a local eventhub instance that can be used during integration tests. Current options include deploying to a test environment and running tests against the eventhub in that environment, or if the environment is exposed to your local machine, running integration tests locally that point to that test eventhub. 

Both of these solutions have infrastructural overhead, so it would be nice if it were possible to stand up a local/embedded event hub to use for integration tests. 

**Describe the solution you'd like**
A local/embedded event hub instance that can be stood up to use for integration tests. 

**Describe alternatives you've considered**
Other than the approaches described above, I am not aware of any other possible alternatives. 

**Additional context**
n/a

**Information Checklist**
Kindly make sure that you have added all the following information above and checkoff the required fields otherwise we will treat the issuer as an incomplete report
- [ x] Description Added
- [ x] Expected solution specified

**Comment by joshfree** [comment]
@conniey could you follow up with @vivin's question?  Thanks

**Comment by ramya-rao-a** [comment]
@kasun04 Can you please share any advice from the Event Hubs team for this particular ask?

**Comment by kasun04** [comment]
@vivin Unfortunately we don't have any plans to ship an embedded on-prem broker for testing purposes. Event Hubs is natively a cloud service, and our recommendation is to run your tests against a standard namespace (as the test environment)

**Comment by eocron** [comment]
Imagine SQL were a cloud service....as to per topic, this is an architectural flaw to not provide your clients of mocking behaviour whereas you still mock such things as storage accounts (AzureStorageEmulator). I could understand this BUT you gave your clients limit of max 10 instances per EH.....

You are just giving more reason to switch to kafka instead, which is available both in cloud and in end-to-end testing environment.
