### ISSUE TITLE
How to get AssignRoles for User?

### ISSUE THREAD

**Issue by changbaebang** [Azure/azure-sdk-for-java#22494]
**Query/Question**
This is the portal page for Assigned Roles.
![image](https://user-images.githubusercontent.com/4535450/123226373-91f5de00-d50e-11eb-98b4-57cffdf64a01.png)

I want to make like this page with Java SDK.

![image](https://user-images.githubusercontent.com/4535450/123225960-2e6bb080-d50e-11eb-90da-6cf8559d2615.png)

Above is the sample for get User List for the assigned roles.

with https://github.com/Azure-Samples/aad-java-manage-users-groups-and-roles/ sample,
There is nothing related with get assignRoles by thest user.

```
final AzureProfile profile = new AzureProfile(tenantId, subscribeId, AzureEnvironment.AZURE);
final TokenCredential credential = new ClientSecretCredentialBuilder()
                 .clientId(appId)
                 .clientSecret(password)
                 .tenantId(tenantId)
                 //.authorityHost(profile.getEnvironment().getActiveDirectoryEndpoint())
                 .build();

AzureResourceManager azureResourceManager = AzureResourceManager
                .configure()
                .withLogLevel(HttpLogDetailLevel.BASIC)
                .authenticate(credential, profile)
                //.withDefaultSubscription();
                .withSubscription(subscribeId);

AccessManagement accessManager = azureResourceManager.accessManagement();
PagedIterable<RoleAssignment> roles = accessManager.roleAssignments().listByScope("/subscriptions/"+subscribeId);
            for(RoleAssignment role : roles) {
                System.out.println(++count);
                System.out.println("role name: " + role.name());
                System.out.println("role id: " + role.id());
                System.out.println("role id: " + role.innerModel());
                System.out.println("role : " + role.toString());
            }
```

The result of the portal and result of `Get-AzureADDirectoryRole`(from powershell) are same.
But the result of `roleAssignments` and the result of the portal are different.

Is there API like `Get-AzureADDirectoryRole'?
And is there any filter by user?

***Why is this not a Bug or a feature Request?***
Not a bug for the how to

**Setup (please complete the following information if applicable):**
 - OS: windows
 - IDE: visual code
 - Library/Libraries: 
 ```
<dependency>
      <groupId>com.azure</groupId>
      <artifactId>azure-identity</artifactId>
      <version>1.2.5</version>
    </dependency>
    <dependency>
      <groupId>com.azure.resourcemanager</groupId>
      <artifactId>azure-resourcemanager</artifactId>
      <version>2.4.0</version>
    </dependency>
```
 
 **Information Checklist**
 Kindly make sure that you have added all the following information above and checkoff the required fields otherwise we will treat the issuer as an incomplete report
- [+] Query Added
- [ ] Setup information Added

**Comment by changbaebang** [comment]
I want to get like 
```
https://graph.microsoft.com/beta/users/{user-id}/roleManagement/directory/transitiveRoleAssignments?$top=999&$count=true
```

in Java SDK.

Please reply me!

**Comment by joshfree** [comment]
Hi @changbaebang, thank you for posting your question.  I've routed this to the control plane team who will be able to follow up with you shortly.  Thanks

/cc @yungezz

**Comment by changbaebang** [comment]
Thanks!!

I also want to know 
https://docs.microsoft.com/en-us/java/api/com.microsoft.azure.management.graphrbac.roleassignments?view=azure-java-legacy
and 
https://docs.microsoft.com/en-us/graph/api/resources/directoryrole?view=graph-rest-1.0

**Comment by yungezz** [comment]
add @weidongxu-microsoft to help on this. thanks

**Comment by weidongxu-microsoft** [comment]
@changbaebang

`graph.microsoft.com` is not the scope of management SDK. Please check e.g. https://docs.microsoft.com/graph/overview
They have a Java client https://github.com/microsoftgraph/msgraph-sdk-java

**Comment by changbaebang** [comment]
@weidongxu-microsoft Hi
I want to get assignment role with this SDK.
If so, I will not use graph SDK.

I do not find the way to get it so I announce it.

Is there any way to get?
https://github.com/Azure-Samples/aad-java-manage-users-groups-and-roles/

In this sample, only set & remove.

**Comment by weidongxu-microsoft** [comment]
@changbaebang

As I've mentioned, this is the scope of Microsoft Graph, not management.

The sample https://github.com/Azure-Samples/aad-java-manage-users-groups-and-roles/ would create/list RABC on Azure resources, not the AAD role as in your screenshot.
