### ISSUE TITLE
Support multiple Spring Boot versions side by side

### ISSUE THREAD

**Issue by AlexGhiondea** [Azure/azure-sdk-for-java#22530]

**Comment by joshfree** [comment]
Closing auto-generated issue from Nickel planning.  @chenrujun please feel free to file any new issues or reactivate if this is an ask from spring to the central engsys team (but since it was assigned back to @AlexGhiondea, I'm guessing not).

**Comment by chenrujun** [comment]
@joshfree , it's OK to close this issue. Thank you for your check.
