### ISSUE TITLE
Incorporate Monitor Query Beta-2 UX study feedback into August (Beta-3)

### ISSUE THREAD

**Issue by joshfree** [Azure/azure-sdk-for-java#22543]
Tracking issue to update the August Release to incorporate the TBD Beta-2 UX Study Feedback
/cc @scottaddie

Action items from 7/23 meeting:

- [x] Add an "Advanced scenarios" section to the _README_. Within that section, provide a link to the multi-workspace logs query code sample at https://github.com/Azure/azure-sdk-for-java/blob/main/sdk/monitor/azure-monitor-query/src/samples/java/com/azure/monitor/query/MultiWorkspaceSample.java.
- [x] Add a logs query response object hierarchy tree to the _README_.
- [x] Add a metrics query response object hierarchy tree to the _README_.
- [x] Add instructions to the _README_ for locating the resource ID. https://github.com/Azure/azure-sdk-for-java/pull/23164

**Comment by scottaddie** [comment]
Closing, as all of the first UX study's feedback has been addressed. The fixes will be included in Beta 3, which is scheduled to ship today.
