### ISSUE TITLE
Update Monitor Query Samples, Quickstarts, and Documentation based on Beta-2 consistency review

### ISSUE THREAD

**Issue by joshfree** [Azure/azure-sdk-for-java#22542]
Tracking issue to update all Samples and related documentation based on the Beta-2 consistency review on 6/24
/cc @scottaddie

README updates:
- [x] Use `DefaultAzureCredential` for client authentication samples
- [x] Replace the generic Azure subscription link (https://azure.microsoft.com/free) with the Java-branded subscription link (http://azure.microsoft.com/free/java)
- [x] Fix the "Product Documentation" link (currently points to Web PubSub docs)

**Comment by srnagar** [comment]
Samples and readme updated for beta-2 release. Closing the issue.
