### ISSUE TITLE
Specify SessionId using azure-spring-cloud-stream-binder-servicebus-topic

### ISSUE THREAD

**Issue by Manuel-Moya** [Azure/azure-sdk-for-java#22567]
**Query/Question**
How could i specify the sessionId (sending a message ) for a topic subscription using Azure Spring Cloud Topic Binder?

***Why is this not a Bug or a feature Request?***
I have tried to use the header, but it is not working.

**Setup (please complete the following information if applicable):**
 - OS: Window 10
 - IDE: IntelliJ
 - Library/Libraries: azure-spring-cloud-stream-binder-servicebus-topic, v 2.5
 
 **Information Checklist**
 Kindly make sure that you have added all the following information above and checkoff the required fields otherwise we will treat the issuer as an incomplete report
- [X] Query Added
- [X] Setup information Added

**Comment by ZhuXiaoBing-cn** [comment]
Hi, @Manuel-Moya, thanks for the reporting.

- You can make it work in this way.
![image](https://user-images.githubusercontent.com/71206407/123775477-fd6df000-d900-11eb-8489-830fb1f6a1c2.png)
- This can then be verified on Azure Portal.
![image](https://user-images.githubusercontent.com/71206407/123776056-82f1a000-d901-11eb-99c3-fb8b589cc672.png)

**Comment by Manuel-Moya** [comment]
Thanks a lot @ZhuXiaoBing-cn  !!!! It seems that is working!!! I am going to implement it in our dev environment.
