### ISSUE TITLE
Investigate ByteBuffer size when converting InputStream to Flux

### ISSUE THREAD

**Issue by jaschrep-msft** [Azure/azure-sdk-for-java#22579]
https://github.com/Azure/azure-sdk-for-java/pull/22218#discussion_r656334406

Currently, stage block size (or equivalent) is being used to set the byte buffers. This is likely a bottleneck and a memory issue.

**Comment by kasobol-msft** [comment]
Potentially related to https://github.com/Azure/azure-sdk-for-java/issues/21631
