### ISSUE TITLE
Java sdk to run powershell / shell script command ?

### ISSUE THREAD

**Issue by giridharkn** [Azure/azure-sdk-for-java#2258]
Hi,

I have come accross the following azure document for rest API to run powershell or shell script. Do we have java sdk for the same ? 

https://docs.microsoft.com/en-us/rest/api/compute/virtual%20machines%20run%20commands/runcommand

Thanks and Regards
Giridhar K N

**Comment by milismsft** [comment]
@giridharkn please take a look at the following sample which shows how to invoke a custom command: https://github.com/Azure/azure-libraries-for-java/blob/master/azure-samples/src/main/java/com/microsoft/azure/management/compute/samples/ManageUserAssignedMSIEnabledVirtualMachine.java#L160

**Comment by giridharkn** [comment]
thanks @milismsft :) I will try and get back to you :)

**Comment by kurtzeborn** [comment]
This issue hasn't been touched in nearly 2 years.  @giridharkn, I'm assuming this worked for you.
