### ISSUE TITLE
[Bug] FlatteningSerializer throws UnsupportedOperationException when serializing Collections.unmodifiableMap

### ISSUE THREAD

**Issue by samvaity** [Azure/azure-sdk-for-java#22589]
FlatteningSerializer throws UnsupportedOperationException when serializing Collections.unmodifiableMap

>com.fasterxml.jackson.databind.JsonMappingException: [no message for java.lang.UnsupportedOperationException]

**Comment by alzimmermsft** [comment]
This will happen to any `Map` sub-type which doesn't support `remove` or `put` operations.
