### ISSUE TITLE
[BUG] Inconsistency in 3.6.0 BOM regarding com.azure.spring:azure-spring-boot-starter-keyvault-secrets

### ISSUE THREAD

**Issue by blacelle** [Azure/azure-sdk-for-java#22594]
**Describe the bug**
Latest 3.6.0 refer to 

      <dependency>
        <groupId>com.azure.spring</groupId>
        <artifactId>azure-spring-boot-starter-keyvault-secrets</artifactId>
        <version>${azure.spring.boot.version}</version>
      </dependency>

but this dependency does not exists in 3.6.0:
https://mvnrepository.com/artifact/com.azure.spring/azure-spring-boot-starter-keyvault-secrets

**Comment by JonathanGiles** [comment]
Can you please provide more details - I'm not sure which 3.6.0 BOM you are referring to?

**Comment by blacelle** [comment]
https://github.com/Azure/azure-sdk-for-java/blob/main/sdk/boms/azure-spring-boot-bom/pom.xml#L88

Azure-spring-boot-bom

**Comment by joshfree** [comment]
@stliu can you please follow up?

/cc @alzimmermsft

**Comment by backwind1233** [comment]
@blacelle , what do you mean  this dependency does not exists in 3.6.0 bom,
the 3.6.0 bom https://github.com/Azure/azure-sdk-for-java/blob/main/sdk/boms/azure-spring-boot-bom/pom.xml has not been released yet, and we will release this bom today, and the bom file contains azure-spring-boot-starter-keyvault-secrets:3.6.0.

**Comment by blacelle** [comment]
I'm very sorry @backwind1233 . I feel this is due to poor pom.xml configuration on our side. Renovate having reported Azure 3.6.0 for some dependencies, I got it wrong supposing most of dependencies where available in 3.6.0.

<img width="928" alt="Screenshot 2021-06-29 at 09 48 10" src="https://user-images.githubusercontent.com/2117911/123758493-443af600-d8bf-11eb-85d3-aeaaca86720b.png">

**Comment by backwind1233** [comment]
@blacelle thanks for your feedback, we will finish our spring replease by the end of this month.
