### ISSUE TITLE
High transit time seen when there are many active rntbd connections/channels with large response sizes

### ISSUE THREAD

**Issue by mbhaskar** [Azure/azure-sdk-for-java#22626]
When there are a lot of active rntbd connections/channels downloading large responses during scenarios like many parallel cross partition queries or heavy read item workload with large document sizes, transit times are higher and potentially this is being caused in the netty and the channel buffer management. This has to be investigated further 

Example log:
"transportRequestTimeline": [
            {
              "eventName": "created",
              "startTimeUTC": "2021-06-15T19:08:14.512649Z",
              "durationInMicroSec": 115
            },
            {
              "eventName": "queued",
              "startTimeUTC": "2021-06-15T19:08:14.512764Z",
              "durationInMicroSec": 8
            },
            {
              "eventName": "channelAcquisitionStarted",
              "startTimeUTC": "2021-06-15T19:08:14.512772Z",
              "durationInMicroSec": 2002244
            },
            {
              "eventName": "pipelined",
              "startTimeUTC": "2021-06-15T19:08:16.515016Z",
              "durationInMicroSec": 582714
            },
            {
              "eventName": "transitTime",
              "startTimeUTC": "2021-06-15T19:08:17.097730Z",
              "durationInMicroSec": **5036308**
            },
            {
              "eventName": "received",
              "startTimeUTC": null,
              "durationInMicroSec": 0
            },
            {
              "eventName": "completed",
              "startTimeUTC": "2021-06-15T19:08:22.134038Z",
              "durationInMicroSec": 276
            }
          ],
          "rntbdRequestLengthInBytes": 502,
          "rntbdResponseLengthInBytes": -1,
          "requestPayloadLengthInBytes": 27,
          "responsePayloadLengthInBytes": null,
          "channelTaskQueueSize": **25**,
          "pendingRequestsCount": **25**,
          "serviceEndpointStatistics": {
            "availableChannels": 11,
            "acquiredChannels": 63,
            "executorTaskQueueSize": 91,
            "inflightRequests": **136**,
            "lastSuccessfulRequestTime": "2021-06-15T19:08:14.505Z",
            "lastRequestTime": "2021-06-15T19:08:14.498Z",
            "createdTime": "2021-06-15T18:58:18.200979Z",
            "isClosed": false
          }
        }

**Comment by kushagraThapar** [comment]
This has been fixed, thanks!
