### ISSUE TITLE
[BUG] Unable to set forward from one queue to another queue with ServiceBusAdministrationClient

### ISSUE THREAD

**Issue by lufeiWandisco** [Azure/azure-sdk-for-java#22657]
**Describe the bug**

I am currently trying to create service bus queue and set it auto-forward message to another queue programmatically. And it doesn't work. 
I have tried connectionString with management rule of the namespace and also AAD that has full access to the namespace. Create/list/delete queue are all green but failed on create with/update setForwardTo with 401 unauthorized error.

Some discussion in #11469 
queueOptions.setForwardTo("queue-to-forward-to") would cause 400 error require absolute URL. Right now I could only test it out with queueOptions.setForwardTo("sb://my-namespace.servicebus.windows.net/queue-to-forward-to"). Better API docs / samples might required for this API.

***Exception or Stack Trace***
`Caused by: com.azure.messaging.servicebus.implementation.models.ServiceBusManagementErrorException: Status code 401, "<Error><Code>401</Code><Detail>SubCode=40100. Unauthorized. TrackingId:84e7bc92-550b-4ec4-afbd-d11810f81868_G12, SystemTracker:wd-frp-metric-dev:Queue:admin-test-queue, Timestamp:2021-06-29T23:18:18</Detail></Error>"`

**To Reproduce**
1. create service bus namespace with premium tier on Azure Portal UI.
2.  create ServiceBusAdministrationClient with either connectionString with management permission rule or TokenCredential with AAD has full access to this service bus namespace.
3. Try to create queue that forward message to another queue in this namespace -- failed at creation.
4. Try create a queue and then update the forward the anther queue in this namespace -- failed at updateing.

***Code Snippet***
Add the code snippet that causes the issue.
`
CreateQueueOptions queueOptions = new CreateQueueOptions();
    queueOptions.setForwardTo("sb://my-namespace.servicebus.windows.net/queue-to-forward-to")
            .setDefaultMessageTimeToLive(Duration.ofMinutes(20))
            .setMaxSizeInMegabytes(1024)
            .setDuplicateDetectionHistoryTimeWindow(Duration.ofMinutes(10))
            .getAuthorizationRules().add(new SharedAccessAuthorizationRule("probe", Arrays.asList(SEND)));
serviceBusAdministrationClient.createQueue(queueName, queueOptions);
`

**Expected behavior**
Queue should be able to be created.

**Screenshots**

**Setup (please complete the following information):**
 - OS: macOX
 - IDE: IntelliJ
 - Library/Libraries: group: 'com.azure', name: 'azure-messaging-servicebus', version: '7.2.3'
**Additional context**

**Information Checklist**
Kindly make sure that you have added all the following information above and checkoff the required fields otherwise we will treat the issuer as an incomplete report
- [ ] Bug Description Added
- [ ] Repro Steps Added
- [ ] Setup information Added

**Comment by joshfree** [comment]
@ki1729 could you follow up with @lufeiWandisco on this `Service Bus` client library question?

/cc @YijunXieMS

**Comment by lufeiWandisco** [comment]
Could I have some one take a look at this problem :D thanks!

**Comment by YijunXieMS** [comment]
@lufeiWandisco We're looking into it soon.

**Comment by ki1729** [comment]
@lufeiWandisco we are still looking into this issue (confirming the BadRequest response from the service), will post another update with in the next 24 hours

**Comment by ki1729** [comment]
Sorry about the delay in updates here, we have a bug in the way we are setting the value, and are working on getting it fixed

**Comment by ki1729** [comment]
Still working on this, but this should be fixed in the next release, if not sooner

**Comment by lufeiWandisco** [comment]
Hi just wanna have a check here on how this issue is going. I saw the release 
https://github.com/Azure/azure-sdk-for-java/releases/tag/azure-messaging-servicebus_7.4.0 
is the fix in the release or it still WIP?

**Comment by ramya-rao-a** [comment]
Thanks for your patience everyone!

The fix for this issue was in the PR #25146 

The November release for the azure-messaging-servicebus package was published last week with this fix.

Please use the latest version of the package i.e. 7.5.0 to get the fix.

**Comment by ki1729** [comment]
@hustleandcuss, yes, the setForwardDeadLetteredMessagesTo() has also been fixed as part of the release (v7.5.0)
