### ISSUE TITLE
Metrics Advisor Readme issues

### ISSUE THREAD

**Issue by hongli750210** [Azure/azure-sdk-for-java#22673]
1.
Section [Link](https://github.com/Azure/azure-sdk-for-java/tree/main/sdk/metricsadvisor/azure-ai-metricsadvisor#prerequisites)
![image](https://user-images.githubusercontent.com/74638143/123914238-c4da1f00-d9b1-11eb-9ab5-8f312e9db616.png)
Suggestion:
Change text to` [Java Development Kit (JDK)][jdk_link] version 8 or later`. 

2.
Section [Link](https://github.com/Azure/azure-sdk-for-java/tree/main/sdk/metricsadvisor/azure-ai-metricsadvisor#create-a-metricsadvisor-client-using-azure-service-directory)
![image](https://user-images.githubusercontent.com/74638143/123914621-2a2e1000-d9b2-11eb-97f7-9c0687543332.png)
Suggestion:
Add link for [grant_access]: https://docs.microsoft.com/azure/cognitive-services/authentication#assign-a-role-to-a-service-principal

3.
Section [Link](https://github.com/Azure/azure-sdk-for-java/tree/main/sdk/metricsadvisor/azure-ai-metricsadvisor#examples)
![image](https://user-images.githubusercontent.com/74638143/123914747-4fbb1980-d9b2-11eb-955c-18bfb7175d34.png)
Reason:
Click on this link does not respond.
Suggestion:
Link change to : `(#configure-an-anomaly-alert-configuration)`

4.
Section [Link](https://github.com/Azure/azure-sdk-for-java/tree/main/sdk/metricsadvisor/azure-ai-metricsadvisor#enable-client-logging)
![image](https://user-images.githubusercontent.com/74638143/123914914-83963f00-d9b2-11eb-88d3-c844c1143af3.png)
Suggestion:  
Add link for [logging]: https://github.com/Azure/azure-sdk-for-java/wiki/Logging-with-Azure-SDK

@jongio for notification.

**Comment by jamar-palmer** [comment]
Hi @hongli750210 @jongio 
I made the necessary changes and pushed the request.

**Comment by v-xuto** [comment]
Close this issue, due to PR https://github.com/Azure/azure-sdk-for-java/pull/22694 merged.
