### ISSUE TITLE
[BUG] Spring Boot AAD Starter broken against MIP v1.0

### ISSUE THREAD

**Issue by nioertel** [Azure/azure-sdk-for-java#22677]
**Describe the bug**
Since [this commit](https://github.com/Azure/azure-sdk-for-java/commit/09fd334e8d1bad74f7e0216d6f91f3bcd51660b3#diff-0a4ff8505a807da5f563295fbc11c23917bb8b88411b26c1d39276661a44868d) Spring Boot Starter for AAD seems to not support Microsoft Identity Platform v1.0 anymore.
It's not clear if that was on purpose and there is nothing mentioned in the [change log](https://github.com/Azure/azure-sdk-for-java/blob/main/sdk/spring/azure-spring-boot-starter-active-directory/CHANGELOG.md) for version 3.0.0.

**Expected behavior**
Spring Boot Starter for Azure AD supports v1.0 and v2.0 endpoints. In case support is limited to v2.0 now, a clear migration path has to be defined and documented.

**Setup (please complete the following information):**
 - OS: RHEL 7 / Docker (but not relevant)
 - IDE: n/a
 - Library/Libraries: com.azure.spring:azure-spring-boot-starter-active-directory:3.2.0

**Information Checklist**
Kindly make sure that you have added all the following information above and checkoff the required fields otherwise we will treat the issuer as an incomplete report
- [ x ] Bug Description Added
- [ x ] Repro Steps Added
- [ x ] Setup information Added

**Comment by joshfree** [comment]
@stliu could you please follow up with @nioertel

**Comment by chenrujun** [comment]
Hi, @nioertel. 

Thanks for reaching out.
We already have content about not support `AAD V1`. But it seems not easier to understand.
I create a PR to update the changelog, please check: #22720

**Comment by nioertel** [comment]
I would like to reopen this because the documentation is still not clear and on our side lots of debugging was required to figure out the right configuration of the App Registration:
- Before release 3, the requested scopes were openid, profile, user.read
- Release 3.0 we didn't try.
- With release 3.1 the requested scopes were openid, profile, User.Read, Directory.AccessAsUser.All
- With release 3.2 the requested scopes were openid, profile, User.Read, Directory.Read.All
- Versions newer than 3.2 we didn't check yet

For people migrating to newer versions this is quite painful, especially as microsoftonline login only shows a generic error message.
If newer versions of your library require by default other API Permissions, the release notes should mention this.

**Comment by chenrujun** [comment]
Hi, @nioertel .

Thank you very much for your detailed description.
Your concern make sense, I'll create another PR soon.
