### ISSUE TITLE
[BUG] UrlBuilder retains to many Urls causing OOM

### ISSUE THREAD

**Issue by milismsft** [Azure/azure-sdk-for-java#22716]
**Describe the bug**
A customer is reporting their application running out of memory when updated to use the latest azure-core libraries. The customer's app does not directly calls into the azure-core UrlBuilder class, but there might be other dependent calls that get routed to build various URLs.

***Exception or Stack Trace***
NA

**To Reproduce**
Customer's application eventually runs out of memory after multiple hours/days of continuously running, while memory trickles up.

***Code Snippet***
https://github.com/Azure/azure-sdk-for-java/blob/3f31d68eed6fbe11516ca3afe3955c8840a6e974/sdk/core/azure-core/src/main/java/com/azure/core/http/rest/RestProxy.java#L215

**Expected behavior**
We should implemented a cap on how many Url values "cached" at a given time, and not leave it up to be subject to available memory.

**Screenshots**
attached.
<img width="1583" alt="Screen Shot 2021-06-30 at 3 59 07 PM" src="https://user-images.githubusercontent.com/15163996/124075877-58cfd900-d9fa-11eb-9115-b1dee2d2b4af.png">

**Setup (please complete the following information):**
 - OS: Linux/OpenJdk
 - IDE: NA
 - Library/Libraries: azure-core

**Additional context**

**Information Checklist**
Kindly make sure that you have added all the following information above and checkoff the required fields otherwise we will treat the issuer as an incomplete report
- [ x] Bug Description Added
- [x ] Repro Steps Added
- [ x] Setup information Added

**Comment by srnagar** [comment]
Fixed in PR https://github.com/Azure/azure-sdk-for-java/issues/22716
