### ISSUE TITLE
Need to setSharedAccessExpiryTime relative to Azure system time

### ISSUE THREAD

**Issue by mattvryan** [Azure/azure-sdk-for-java#2271]
Azure Service:  Azure Blob Storage
Java API:  `SharedAccessBlobPolicy.setSharedAccessExpiryTime(Date)`
I would like the ability to set the shared access expiry time relative to Azure's system time, but I don't see a way to do this - I can only give it an absolute time via a `Date` object.  This can cause issues with URIs that have short TTLs.  If the time drift (between the time on the system running my code and whatever time Azure Blob Storage thinks it is) is big enough, at best my URIs may expire sooner than I intended, or the URI may be invalid and return a 403 upon request due to the expiry time occurring before the time the URI was issued.
What would be nice instead would be to be able to request a relative interval beyond Azure's current system time, say via an `int` parameter coupled with a `TimeUnit`.  That way if I request a URI with a 60-second TTL, the duration of the TTL matches what I expected and is delivered by the same system that will enforce the expiration.

**Comment by vhvb1989** [comment]
Hello @mattvryan
Do you still need help on this?

Note: As part of repository cleaning effort, this issue will be closed by Sep 12 if no response is received from submitter and/or not further action is required.

**Comment by mattvryan** [comment]
Yes I would still like this to be added to the storage SDK.

**Comment by rickle-msft** [comment]
@mattvryan Sorry for the delay. This would require a new feature on the service.
@pemari-msft can you give some insight into whether this is likely to be offered by the service and a potential work around in the meantime?

**Comment by pemari-msft** [comment]
Unfortunately, there is no “system time”. Each azure storage machine has a different system time which is where clock skew comes into play.

However, even if there were only one system time, sas tokens are generated client-side, so The sdk would have no way of telling what the system time of Azure was at that time. Unfortunately this is not feasible technically.

**Comment by rickle-msft** [comment]
I am going to close this issue as it is not a feature that we can support. Please feel free to reopen it if you feel you need more support on paths forward.
