### ISSUE TITLE
[BUG] BlobClient#getBlobName() returns incorrectly decoded name

### ISSUE THREAD

**Issue by heyalistair** [Azure/azure-sdk-for-java#22722]
**Describe the bug**
I have a blob in a blob storage container that is called `dir1/a%20b.txt`. This is how it appears written in the Azure Storage UI. When I fetch this blob using a `BlobClient` object, `getName()` returns `dir1/a b.txt`. This is incorrect and this is different file name then the one I used to fetch it.

**To Reproduce**
```
    String fileId = "dir1/a%20b.txt";
    String encoded = UrlUtils.percentEncode(fileId); // encoded equals "dir1%2Fa%2520b.txt"
    BlobClient blob = blobContainerClient.getBlobClient(encoded);
    
    blob.getBlobName(); // equals "dir1/a b.txt"
```

**Expected behavior**
`blob.getBlobName()` should return the actual name `dir1/a%20b.txt`. Or at least something that would work again with another `getBlobClient()` call later.

**Setup (please complete the following information):**
 - OS: macOS 11.4
 - IDE: running with gradle wrapper 6.8
 - Library/Libraries: 
   - `com.azure:azure-storage-common:12.12.0`
   - `com.azure:azure-storage-blob:12.12.0`
     - **Note**: This is probably a regression! Everything behaves as expected in `12.10.0`

**Information Checklist**
Kindly make sure that you have added all the following information above and checkoff the required fields otherwise we will treat the issuer as an incomplete report
- [x] Bug Description Added
- [x] Repro Steps Added
- [x] Setup information Added

**Comment by joshfree** [comment]
Thanks for reporting this string decoding issue in `azure-storage-blob:12.12.0`, @heyalistair.  Someone from the `Storage` team will follow up shortly.

/cc @rickle-msft @gapra-msft @amishra-dev

**Comment by rickle-msft** [comment]
@heyalistair I did some investigation, and it looks like there is an extra decode in `getName()` that was left over during a refactor. We'll work on getting that fix in for a future release.

Thanks for reporting this!
