### ISSUE TITLE
[FEATURE REQ] Allow customising the `XmlFactory` passed in JacksonAdapter for Azure Storage 

### ISSUE THREAD

**Issue by timja** [Azure/azure-sdk-for-java#22764]
**Is your feature request related to a problem? Please describe.**

In an application where the current Threads context class loader is not the main class loader I am unable to load the required stax implementation required by jackson-xml-databind. The one bundled in the JDK is incompatible.

In normal situations I would pass by expected classloader down to whatever is doing the classloading, unfortunately jackson-databind-xml doesn't expose a method for that although the [JDK does](https://github.com/AdoptOpenJDK/openjdk-jdk8u/blob/64cc2bc73816f3e0a91776805482fee37fa37bbe/jaxp/src/javax/xml/stream/XMLInputFactory.java#L287), [jackson-constructor](https://github.com/FasterXML/jackson-dataformat-xml/blob/75d9056bf344d2c18192eb128f177ee21a586017/src/main/java/com/fasterxml/jackson/dataformat/xml/XmlFactory.java#L113)

It does provide constructors for an already configured `XmlFactory`, if I could pass that to the `JacksonAdapter` in some way then that would solve my problem, (would be passed to the `builder` instead of it creating one) https://github.com/Azure/azure-sdk-for-java/blob/main/sdk/core/azure-core/src/main/java/com/azure/core/util/serializer/JacksonAdapter.java#L137

**Describe the solution you'd like**
A supported API for providing either my classloader for loading the `XMLInputFactory` or providing a precreated `XmlFactory`

**Describe alternatives you've considered**

* There's work in progress to try hack this by setting the thread context classloader, but it's brittle work and leads to very ugly code, https://github.com/jenkinsci/azure-storage-plugin/pull/195

* Allowing me to pass a custom classloader would be better all round, I've raised a PR to jackson to see if they'll take that PR: https://github.com/FasterXML/jackson-dataformat-xml/pull/480

**Additional context**

https://github.com/jenkinsci/jackson2-api-plugin/pull/82#issuecomment-873264276
https://github.com/jenkinsci/azure-storage-plugin/issues/194
https://github.com/jenkinsci/azure-storage-plugin/issues/188

**Information Checklist**
Kindly make sure that you have added all the following information above and checkoff the required fields otherwise we will treat the issuer as an incomplete report
- [ ] Description Added
- [ ] Expected solution specified

**Comment by timja** [comment]
This has been worked around upstream in https://github.com/FasterXML/jackson-dataformat-xml/issues/482.

Having said that the maintainer of jackson of jackson said:

>  downstream frameworks may want to explicitly construct and pass XMLInputFactory and XMLOutputFactory, going forward. That won't solve all issues but may help avoid one error mode.

That would allow a consistent implementation being used (Woodstox or Aalto), instead of our case now with the JDK implementation being picked up.

https://github.com/FasterXML/jackson-dataformat-xml/pull/480#issuecomment-873492030

Any thoughts?

**Comment by rickle-msft** [comment]
@alzimmermsft This sounds like a policy that should be standardized across sdks. Any thoughts on if this is something that can go through the arch board?

**Comment by timja** [comment]
Further discussion in https://github.com/FasterXML/jackson-dataformat-xml/issues/483, which likely means no change is required here, although that doesn't prevent the Azure SDK from explicitly configuring the correct stax implementation.

**Comment by alzimmermsft** [comment]
@timja is this issue still a problem? I see that Jackson ended up making a change with how this is loaded, did that solve your problem?

**Comment by timja** [comment]
For my purpose it works, but it’s recommended to allow users to configure the classloader themselves
