### ISSUE TITLE
Issue in getting list of roles assigned to Service principal in Java

### ISSUE THREAD

**Issue by nikunj-badjatya** [Azure/azure-sdk-for-java#22765]
- I have an **App1** (MultiTenant) which is in **HomeTenant1** and has **Clientid1**.
- This **App1** is registered as Service Principal in **Tenant2**.
- This **App1** was then assigned few roles in **Tenant2** on Subscription level scope. Ex. say Contributor role on Subs2 of Tenant2.
- I want to determine through Java SDK how to get list of roles assigned to this SP on Tenant2.

This is possible to do via az cli **az role assignment list --all --assignee**

But we want to get this via Java SDK. Following is the code snipped which we tried.

```
import com.azure.core.credential.TokenCredential;
import com.azure.core.http.rest.PagedIterable;
import com.azure.core.management.AzureEnvironment;
import com.azure.core.management.profile.AzureProfile;
import com.azure.identity.ClientSecretCredentialBuilder;
import com.azure.resourcemanager.AzureResourceManager;
import com.azure.resourcemanager.authorization.models.RoleAssignment;
import com.azure.resourcemanager.authorization.models.RoleDefinition;


public class AzureRoles {
private final  static String TENANT_ID = "redacted";
private final static String HOME_TENANT_ID = "redacted";
private final static String CLIENT_ID = "redacted";
private final static String SUBSCRIPTIONID = "redacted";
private final static String CLIENT_SECRET =  "redacted";


public static void main(String []args) throws Exception {
    try {
        AzureProfile profile = new AzureProfile(TENANT_ID, SUBSCRIPTIONID, AzureEnvironment.AZURE);
        TokenCredential clientSecretCredential = new ClientSecretCredentialBuilder()
                .clientId(CLIENT_ID)
                .clientSecret(CLIENT_SECRET)
                .tenantId(TENANT_ID)
                .authorityHost(profile.getEnvironment().getActiveDirectoryEndpoint())
                .build();
        System.out.println(clientSecretCredential);

        System.out.println(profile);
        AzureResourceManager azureResourceManager = AzureResourceManager
                .authenticate(clientSecretCredential, profile)
                .withSubscription(SUBSCRIPTIONID) ;
        System.out.println(azureResourceManager);
        PagedIterable<RoleAssignment> items =azureResourceManager.accessManagement().roleAssignments()
                .listByServicePrincipal("redacted");

        for (RoleAssignment item:items) {
            RoleDefinition role = azureResourceManager.accessManagement().roleDefinitions().getById(item.roleDefinitionId());
            System.out.println(role.roleName());
        }
    } catch (Exception e) {
        System.out.println(e.getMessage());
        e.printStackTrace();
    }


 }
}
```

Error message

```
com.azure.identity.ClientSecretCredential@5223e5ee
com.azure.core.management.profile.AzureProfile@bef2d72
null
java.lang.NullPointerException
at java.util.Objects.requireNonNull(Objects.java:203)
at com.azure.core.http.policy.BearerTokenAuthenticationPolicy.<init>(BearerTokenAuthenticationPolicy.java:36)
at com.azure.core.management.http.policy.ArmChallengeAuthenticationPolicy.<init>(ArmChallengeAuthenticationPolicy.java:47)
at com.azure.resourcemanager.resources.fluentcore.policy.AuthenticationPolicy.<init>(AuthenticationPolicy.java:28)
at com.azure.resourcemanager.resources.fluentcore.utils.HttpPipelineProvider.buildHttpPipeline(HttpPipelineProvider.java:74)
at com.azure.resourcemanager.resources.fluentcore.utils.HttpPipelineProvider.buildHttpPipeline(HttpPipelineProvider.java:45)
at com.azure.resourcemanager.AzureResourceManager.authenticate(AzureResourceManager.java:163)
at AzureRoles.main(AzureRoles.java:32)

```

We also posted on StackOverflow but no responses there. Thanks for the help.

**Comment by weidongxu-microsoft** [comment]
@nikunj-badjatya 

There appears something inconsistent in your code or runtime.

From the stack:
`at java.util.Objects.requireNonNull(Objects.java:203)`
https://github.com/Azure/azure-sdk-for-java/blob/main/sdk/core/azure-core/src/main/java/com/azure/core/http/policy/BearerTokenAuthenticationPolicy.java#L36
`credential` is null, hence the exception.

However
`at com.azure.resourcemanager.resources.fluentcore.utils.HttpPipelineProvider.buildHttpPipeline(HttpPipelineProvider.java:74)`
https://github.com/Azure/azure-sdk-for-java/blob/main/sdk/resourcemanager/azure-resourcemanager-resources/src/main/java/com/azure/resourcemanager/resources/fluentcore/utils/HttpPipelineProvider.java#L73-L75
`credential` is not null as it is guarded by `if`.

Would you take a look on your dependencies (ref https://github.com/Azure/azure-sdk-for-java/tree/main/sdk/resourcemanager#dependency-management), and make sure your `azure-core` is latest (1.17.0 or above), as well as `azure-core-management` (1.3.0 or above)?

**Comment by nikunj-badjatya** [comment]
Thank you @weidongxu-microsoft 
That was indeed the issue. It also required to use the jackson databind lib >=  2.12.1.
