### ISSUE TITLE
Developer reference guide for Azure Spring Cloud Starters

### ISSUE THREAD

**Issue by stliu** [Azure/azure-sdk-for-java#22788]
We don't have a developer reference guide now, currently our docs are located at readme , ms docs etc, it is hard for our user to find it.

* https://googlecloudplatform.github.io/spring-cloud-gcp/2.0.3/reference/html/index.html
* https://docs.awspring.io/spring-cloud-aws/docs/2.3.0-RC1/reference/html/index.html

# How to do
We can use [GitHub Pages] to manage docs of Spring Cloud Azure. We can follow these steps to achieve this goal:

 - [ ] Investigate current implementation of [spring-cloud-aws/tree/gh-pages] and [spring-cloud-gcp/tree/gh-pages]. Set up infrastructure in [spring-cloud-azure repo].
 - [ ] Set the outline of the docs. Write the level 1 headers for the whole doc.
 - [ ] Each area owner fill contents in the doc.
 - [ ] #25172
 - [ ] Display the doc in both [MS docs] and [Spring official website].

[MS docs]: https://docs.microsoft.com/en-us/azure/developer/java/spring-framework/
[Spring Framework docs]: https://docs.spring.io/spring-framework/docs/current/reference/html/
[Spring Boot docs]: https://docs.spring.io/spring-boot/docs/current/reference/htmlsingle/
[Spring Cloud AWS]: https://docs.awspring.io/spring-cloud-aws/docs/current/reference/html/index.html
[Spring Cloud GCP]: https://googlecloudplatform.github.io/spring-cloud-gcp/2.0.4/reference/html/index.html
[GitHub Pages]: https://pages.github.com/
[spring-cloud-aws/tree/gh-pages]: https://github.com/spring-cloud/spring-cloud-aws/tree/gh-pages
[spring-cloud-gcp/tree/gh-pages]: https://github.com/spring-cloud/spring-cloud-gcp/tree/gh-pages
[spring-cloud-azure repo]: https://github.com/microsoft/spring-cloud-azure
[Spring official website]: https://spring.io/projects/spring-cloud-azure#overview

**Comment by joshfree** [comment]
@seanli1988 you should chat with @scottaddie who is also working on general documentation improvements for Java right now

**Comment by JonathanGiles** [comment]
Please also loop me in! I'm super keen to see docs.microsoft.com become our home base for anything customer facing. Earlier in the year I did a push here: https://docs.microsoft.com/en-us/azure/developer/java/sdk/ and I encourage you to consider a similar push.

**Comment by seanli1988** [comment]
waiting on resources from content team

**Comment by chenrujun** [comment]
1. Investigate current implementation of spring-cloud-aws/tree/gh-pages and spring-cloud-gcp/tree/gh-pages. Set up infrastructure in spring-cloud-azure repo. 

Output: GitHub actions, mvn build, deploy to github pages, display.
Milestone: Spring Cloud Azure Beta 4.0



2.  （rujun）Set the outline of the docs. Write the level 1 headers for the whole doc. Milestone: Spring Cloud Azure Beta 4.0

Output: Outline of doc
Milestone: Spring Cloud Azure Beta 4.0



3.  Each area owner fill contents in the doc.

Output: Content of each module
Milestone: Spring Cloud Azure GA

**Comment by hui1110** [comment]
Closing this issue now for it's in https://github.com/Azure/azure-sdk-for-java/wiki/Spring-Cloud-Azure-4.0-Reference.
