### ISSUE TITLE
cosmos oltp read inferschema issue

### ISSUE THREAD

**Issue by vasanthprabhus** [Azure/azure-sdk-for-java#22801]
When reading data from cosmos db using 

val cfg = Map("spark.cosmos.accountEndpoint" -> cosmosEndpoint,
  "spark.cosmos.accountKey" -> cosmosMasterKey,
  "spark.cosmos.database" -> cosmosDatabaseName,
  "spark.cosmos.container" -> cosmosContainerName
)

val dataInCosmosDb = spark.read.format("cosmos.oltp").options(cfg).load()

dataInCosmosDb.printSchema

we notice the the no. of columns inferred is less than the actual no. of columns present in cosmosdb. Or in other words, the columns present only in the first record of the cosmosdb is inferred as schema. But ideally it should pick the record that has all fields (since cosmos db records have varying fields). 

Please help us with a soln. or a workaround for this if available.

**Comment by joshfree** [comment]
Thanks for reporting this column count issue, @vasanthprabhus.  Someone from the `Cosmos` team will follow up with you shortly.

/cc @kushagraThapar

**Comment by kushagraThapar** [comment]
@moderakh  - please route this issue.

**Comment by moderakh** [comment]
@vasanthprabhus Cosmos DB is schema-less, Spark is schema-full. To infer the spark schema, the Cosmos DB Spark Connector runs a sampling query targeting a subset of documents to infer the schema.

You can tune the schema inference query and the sampling size for your own need, see here:
https://github.com/Azure/azure-sdk-for-java/blob/main/sdk/cosmos/azure-cosmos-spark_3-1_2-12/docs/configuration-reference.md#schema-inference-config

**Comment by vasanthprabhus** [comment]
Got it. Thanks @moderakh.
