### ISSUE TITLE
[Question] How to query data from graph cosmos DB using gremlin query in case insensitive  manner?

### ISSUE THREAD

**Issue by Shivani2596** [Azure/azure-sdk-for-java#22839]
How to query data from graph cosmos DB using gremlin query in case insensitive  manner?
How can we implement the toUppercase or toLowercase operation to fetch data from the graph db?

**Comment by joshfree** [comment]
@backwind1233 @yiliuTo could you please follow up on @Shivani2596's question?

**Comment by Shivani2596** [comment]
Could you share the work around, if there is any?

**Comment by backwind1233** [comment]
@Shivani2596 The highlighted sentence is a work around I think
> To do a case insensitive search you can chain multiple steps together combined by an or step.
