### ISSUE TITLE
[BUG] Inner exception java.lang.IllegalStateException handled

### ISSUE THREAD

**Issue by ermadhan** [Azure/azure-sdk-for-java#22837]
**Describe the bug**
For past 24 hrs, there is random problem in building client using Java Cosmos SDK.  Cosmos SDK version number is 4.12.0. The code was working fine after the the version update for 30+ days and suddenly we are facing these errors.

***Exception or Stack Trace***
Inner exception java.lang.IllegalStateException handled at org.glassfish.jersey.servlet.WebComponent.serviceImpl:
   at reactor.core.publisher.BlockingSingleSubscriber.blockingGet (BlockingSingleSubscriber.java:123)
   at reactor.core.publisher.Mono.block (Mono.java:1709)
   at com.azure.cosmos.implementation.GlobalEndpointManager.init (GlobalEndpointManager.java:77)
   at com.azure.cosmos.implementation.RxDocumentClientImpl.init (RxDocumentClientImpl.java:393)
   at com.azure.cosmos.implementation.AsyncDocumentClient$Builder.build (AsyncDocumentClient.java:229)
   at com.azure.cosmos.CosmosAsyncClient.<init> (CosmosAsyncClient.java:104)
   at com.azure.cosmos.CosmosClientBuilder.buildAsyncClient (CosmosClientBuilder.java:729)
   at com.azure.cosmos.CosmosClient.<init> (CosmosClient.java:30)
   at com.azure.cosmos.CosmosClientBuilder.buildClient (CosmosClientBuilder.java:741)

**To Reproduce**

***Code Snippet***
        GatewayConnectionConfig gatewayConnectionConfig = null;

		strConnectionString = ApplicationSettings.getInstance().getConnectionString();

		gatewayConnectionConfig = GatewayConnectionConfig.getDefaultConfig();
		gatewayConnectionConfig.setMaxConnectionPoolSize(500);
		if (!ApplicationSettings.getInstance().isIS_PRODUCTION_MODE()) {
			gatewayConnectionConfig.setProxy(new ProxyOptions(ProxyOptions.Type.HTTP,
					InetSocketAddress.createUnresolved("www.some.com", 3280)));
		}
		ArrayList<String> preferredLocation = new ArrayList<>();
		preferredLocation.add("West US");
		preferredLocation.add("East US");

		this.cosmosClient = new CosmosClientBuilder()
				.endpoint(getCosmodDBEndPoint()).key(strConnectionString)
				.consistencyLevel(com.azure.cosmos.ConsistencyLevel.SESSION).gatewayMode(gatewayConnectionConfig)
				.preferredRegions(preferredLocation)
				.contentResponseOnWriteEnabled(true).buildClient();

**Expected behavior**
Client should be built and aavailable

**Setup (please complete the following information):**
Azure Api App using Java Cosmos SDK

**Comment by joshfree** [comment]
@kushagraThapar could you follow up with @ermadhan on this reliability issue in `Cosmos 4.1.12.0`?

@ermadhan are you able to upgrade to a newer release of the client library https://github.com/Azure/azure-sdk-for-java/blob/main/sdk/cosmos/azure-cosmos/CHANGELOG.md?

**Comment by kushagraThapar** [comment]
@ermadhan  - Looking at the stack trace, seems like this is an issue with your connection. Did you try the above suggestion of upgrading to the latest version of Azure Cosmos SDK ?

Also, if things were working fine for 30+ days, this doesn't seem to be an issue related to the Cosmos SDK, rather some network / connection issue at your end. That being said, are you still facing the issue ?
