### ISSUE TITLE
[QUERY] Is the current state API of ServiceBus AMQP Channel available externally? Or is there an indirect way to get it?

### ISSUE THREAD

**Issue by ZhuXiaoBing-cn** [Azure/azure-sdk-for-java#22843]
**Query/Question**
Is the current state API of ServiceBus AMQP Channel available externally? This will get the status of the client. Or is there an indirect way to get it?

**Setup (please complete the following information if applicable):**
 - Library/Libraries: [ azure-messaging-servicebus:7.2.3 (groupId:artifactId:version)] 
 
 **Information Checklist**
- [x] Query Added
- [x] Setup information Added

**Comment by joshfree** [comment]
@ki1729 could you please follow upw ith @ZhuXiaoBing-cn's question?

**Comment by ZhuXiaoBing-cn** [comment]
@ki1729, At present, I plan to implement the Health Indicator about the Service Bus, but I can't get useful API from the SDK to judge whether the Service Bus Client will be healthy.

So I want to judge by the state of the AMQP channel. However, I can't get the status of the current service bus client's AMQP channel. Do you have any suggestions?
