### ISSUE TITLE
[TEST]  Service Bus: Measure Performance of SB vs SB Spring Boot Starter

### ISSUE THREAD

**Issue by joshfree** [Azure/azure-sdk-for-java#22867]
Dependent on #20852; Related issue #22866

After completing the performance tuning of Service Bus client library, also measure the performance via the Spring Boot Starter and file tracking issues for any unusual or unexpected overhead

/cc @stliu

**Comment by anuchandy** [comment]
This requires the migration of EH and SB perf tests to the new perf test framework. https://github.com/Azure/azure-sdk-for-java/pull/27247
