### ISSUE TITLE
[BUG] MsalInteractionRequiredException prevents ChainedTokenCredential from continuing the chain

### ISSUE THREAD

**Issue by saragluna** [Azure/azure-sdk-for-java#22888]
**Describe the bug**
Build a `SecretClient` using the `DefaultAzureCredential` and try to retrieve a secret from Key Vault. If there's an expired refresh token in Visual Studio Code, it will throw a `MsalInteractionRequiredException` and stop the chain. 

***Exception or Stack Trace***
https://gist.github.com/stliu/794871d846d979337877e7d3fa76c92e

**To Reproduce**
Use an expired refresh token in Visual Studio Code. 

***Code Snippet***
```java
    SecretClient secretClient = new SecretClientBuilder()
                                    .vaultUrl("xxx")
                                    .credential(new DefaultAzureCredentialBuilder().build())
                                    .buildClient();
    secretClient.getSecret("test-secret");
```

**Expected behavior**
It should go through the chain to find the first available token credential. 

**Screenshots**

**Setup (please complete the following information):**
 - OS: [MacOS]
 - IDE: [Visual Studio Code]
 - Library/Libraries: [com.azure:azure-idenity:1.3.3]

**Additional context**

**Information Checklist**
Kindly make sure that you have added all the following information above and checkoff the required fields otherwise we will treat the issuer as an incomplete report
- [x] Bug Description Added
- [x] Repro Steps Added
- [x] Setup information Added

**Comment by g2vinay** [comment]
@saragluna this issue has been resolved in Identity release v1.3.5
Let us know if you run into any other issues.
