### ISSUE TITLE
Moved Git Repo Code Request

### ISSUE THREAD

**Issue by basavarajucm** [Azure/azure-sdk-for-java#22889]
Could you let me know where did you move the code exists in your repo link. I need reference of this code please help on this 
 https://github.com/Azure/azure-sdk-for-java/tree/main/sdk/spring/azure-spring-boot-samples/azure-spring-boot-sample-active-directory-webapp

**Comment by mrm9084** [comment]
@basavarajucm All Spring samples were moved to here. https://github.com/Azure-Samples/azure-spring-boot-samples Thanks.

**Comment by basavarajucm** [comment]
@mrm9084 , Thank you so much. 
Could you please provide the reference code for handling logout.

**Comment by mrm9084** [comment]
@chenrujun

**Comment by chenrujun** [comment]
Hi, @basavarajucm.

Thanks for reaching out.

We moved our sample to this repo: https://github.com/Azure-Samples/azure-spring-boot-samples/tree/main/aad

(cc: @backwind1233 , FYI.)

**Comment by chenrujun** [comment]
Hi, @basavarajucm.

> Could you please provide the reference code for handling logout.

Here is our code about logout:

https://github.com/Azure/azure-sdk-for-java/blob/azure-spring-boot-starter-active-directory_3.6.1/sdk/spring/azure-spring-boot/src/main/java/com/azure/spring/aad/webapp/AADWebSecurityConfigurerAdapter.java#L50

**Comment by basavarajucm** [comment]
Thank you @mrm9084 , @chenrujun

**Comment by basavarajucm** [comment]
Thank you @mrm9084 , @chenrujun
