### ISSUE TITLE
[Storage] Possible bug - Segment doesn't have any more events exception

### ISSUE THREAD

**Issue by seanmcc-msft** [Azure/azure-sdk-for-java#22897]
https://github.com/Azure/azure-sdk-for-net/pull/22546

https://github.com/Azure/azure-sdk-for-net/issues/15831

**Comment by gapra-msft** [comment]
ack. we should add tests for this

**Comment by mkulisic** [comment]
@seanmcc-msft which version of the nuget package will include this fix? Will 12.0.0-preview.13 have the fix in it?
