### ISSUE TITLE
[Storage] Possible bug - Sporadic ArgumentOutOfRangeException when calling BlobChangeFeedClient.GetChangesAsync

### ISSUE THREAD

**Issue by seanmcc-msft** [Azure/azure-sdk-for-java#22896]
https://github.com/Azure/azure-sdk-for-net/issues/20950

https://github.com/Azure/azure-sdk-for-net/pull/22550

**Comment by gapra-msft** [comment]
@rickle-msft Just as an FYI. I'm fairly confident this isnt a bug in Java, we should just add a couple tests to confirm.
