### ISSUE TITLE
[FEATURE REQ] Make schedulerSize of PartitionPumpManager configurable

### ISSUE THREAD

**Issue by pvorb** [Azure/azure-sdk-for-java#22942]
**Is your feature request related to a problem? Please describe.**
The scheduler thread pool of the `PartitionPumpManager` that works behind a `EventProcessorClient` in `azure-messaging-eventhubs` always uses 4 * the number of available CPU cores as its size. There are situations, where this default is not appropriate. For example, we have a service that processes events from multiple Event Hubs and uses multiple `EventProcessorClient`s. Thus, theres a large number of threads contending for CPU time. If we were able to reduce the size of each thread pool, there would be less overhead lost by context switching.

**Describe the solution you'd like**
I'd like to have a way to explicitly set the number of threads used by the scheduler that works behind the `PartitionPumpManager`.

**Describe alternatives you've considered**
[`-XX:ActiveProcessorCount`](https://docs.oracle.com/en/java/javase/11/tools/java.html#GUID-3B1CE181-CD30-4178-9602-230B800D4FAE__GUID-6155D02B-FD3F-47BF-BD06-E3D111919353) can be used to limit the number of processors used to calculate the scheduler size, but this will affect the entire application and might not be desirable.

**Additional context**
This is the piece of code that sets the default, which I'd like to change: https://github.com/Azure/azure-sdk-for-java/blob/azure-messaging-eventhubs_5.9.0/sdk/eventhubs/azure-messaging-eventhubs/src/main/java/com/azure/messaging/eventhubs/PartitionPumpManager.java#L65-L67

**Comment by pvorb** [comment]
I could contribute this if this is interesting for you.

**Comment by ramya-rao-a** [comment]
@conniey Any thoughts here?

**Comment by conniey** [comment]
This is a good feature to have. We originally added this boundedElastic for each partition pump because in constrained VMs (2 CPUs) running EventProcessorClient, we noticed only one partition would be processed. This Event Hub had millions of events over 16 partitions, but we could only see activity in a couple of the partitions even though the EventProcessorClient owned all the partitions.

**Comment by pvorb** [comment]
@conniey Thanks. Are you interested in a Pull Request that makes this configurable like I requested?

**Comment by conniey** [comment]
@pvorb Hey! Thanks for pinging me on this. Making this configurable would be awesome and it also requires a public API modification, which adds some complexity to this. Our approach is to suggest a public API and demonstrate how users would leverage this via code snippets, do an API review and then implementation. Here are our API design guidelines: https://azure.github.io/azure-sdk/java_introduction.html
