### ISSUE TITLE
[FEATURE REQ] Support credential rotation for all Spring Cloud Azure libraries

### ISSUE THREAD

**Issue by chenrujun** [Azure/azure-sdk-for-java#22959]
### Context

When we configure `azure.activedirectory.client-secret`, the `client-secret` will be expired. We should support client-secret rotation.

### Goal 
Support client-secret rotation for all Spring Cloud Azure libraries.

### Solution

We may do like this: add property `azure-activedirectory.secondary-client-secret`.
When `client-secret` is expired, we should switch to `secondary-client-secret` automatically.

Not only for `client-secret`, but we should also support rotation for other credential, such as `certificates`.

**Comment by backwind1233** [comment]
@backwind1233
