### ISSUE TITLE
Follow spring's convention for spring-boot in azure-spring-cloud-context.

### ISSUE THREAD

**Issue by chenrujun** [Azure/azure-sdk-for-java#22957]
`azure-spring-cloud-context` can depends on `spring-framework`, it should not depends on `spring-boot`.
So we should delete spring-boot related dependency in `azure-spring-cloud-context`.

Refs:
https://github.com/Azure/azure-sdk-for-java/blob/azure-spring-boot_3.6.0/sdk/spring/azure-spring-cloud-context/pom.xml#L33

**Comment by saragluna** [comment]
#22977

**Comment by backwind1233** [comment]
close this issue, it is duplicated with https://github.com/Azure/azure-sdk-for-java/wiki/Spring-Cloud-for-Azure-Core-design

**Comment by backwind1233** [comment]
close this issue, it is related with this PR:https://github.com/Azure/azure-sdk-for-java/pull/23004

**Comment by backwind1233** [comment]
close this issue, it is related with this PR:https://github.com/Azure/azure-sdk-for-java/pull/23004
