### ISSUE TITLE
Cosmos Client creation with resource token

### ISSUE THREAD

**Issue by Oury-MSFT** [Azure/azure-sdk-for-java#22969]
**Query/Question**
We got one requirement where we have to use Cosmos DB. We are using Azure Java SDK (azure-cosmos', version: '4.16.0).

We are generating CosmosClient object with Resource token which expires in an hour. So we have to re-instantiate CosmosClient with a new resource token.

This way we are unable to keep CosmosClient as Singleton (as recommended by Azure). We are ending up creating several CosmosClient objects on the expiry of the resource token causing memory leak.

Can you please suggest the best way of creating CosmosClient with Resource Token in Java (Sprinboot)?

We are referring to the below links for cosmos DB connection:

https://docs.microsoft.com/en-us/azure/cosmos-db/performance-tips-java-sdk-v4-sql?tabs=api-sync#sdk-usage

https://github.com/Azure-Samples/azure-cosmos-java-sql-api-samples/blob/main/src/main/java/com/azure/cosmos/examples/autoscaledatabasecrud/sync/AutoscaleDatabaseCRUDQuickstart.java

Below is the error excerpt:-
"exception"":""failed to establish connection to bn6prdddc05-docdb-2.documents.azure.com:14549 due to io.netty.handler.codec.EncoderException: java.lang.OutOfMemoryError: Cannot reserve 8388608 bytes of direct buffer memory (allocated: 2076650368, limit: 2080374784)

And plenty of below errors after 1 hr of token expiry. Looks likes azure cosmos library internally calls and use the first CosmosClient object created at the application start and after then keeps on trying using the same client to refresh the location.
com.azure.cosmos.implementation.GlobalEndpointManager [0;39m: startRefreshLocationTimerAsync() - Unable to refresh database account from any location. Exception: CosmosException{userAgent=azsdk-java-cosmos/4.5.0 Linux/4.15.0-135-generic JRE/13.0.2, error={"code":"Forbidden","message":"The authorization token is not valid at the current time. Please create another token and retry (token start time: Fri, 25 Jun 2021 11:15:49 GMT, token expiry time: Fri, 25 Jun 2021 12:15:49 GMT, current server time: Fri, 25 Jun 2021 12:26:01 GMT)})
So in nutshell,due to resource token, we are unable to keep CosmosClient as a singleton and getting bad performance from azure SDK.

**Comment by joshfree** [comment]
@backwind1233 @yiliuTo could you please follow up with @Oury-MSFT's question on the most performant way to work with CosmosClient in Spring Boot and manage a refresh token?

/cc @g2vinay

**Comment by joshfree** [comment]
tagging @kushagraThapar and @kirankumarkolli by request of @Oury-MSFT

**Comment by Oury-MSFT** [comment]
@ganesh17492 This is the Git Issue I have create for you so we can start collaborating to find possible solution. Thanks

**Comment by backwind1233** [comment]
Hi @Oury-MSFT @ganesh17492
I think there is a workaround you may have a try: you may run background scheduled tasks in Spring to update CosmosClient in a fixeddelay.

**Comment by kirankumarkolli** [comment]
/cc: @kushagraThapar, @mbhaskar (FYI from Cosmos team)

**Comment by kushagraThapar** [comment]
What is the customer scenario? Can't they use AAD?

@ganesh17492 - you can read more about AAD here - https://docs.microsoft.com/en-us/azure/cosmos-db/role-based-access-control

https://docs.microsoft.com/en-us/azure/cosmos-db/how-to-setup-rbac

**Comment by ganesh17492** [comment]
Thanks @kushagraThapar.
I'll check the above link and let you know if it works for us.

**Comment by Oury-MSFT** [comment]
@ganesh17492 did you had a chance to review the doc above. Please let us know 

Regards,
Oury

**Comment by Oury-MSFT** [comment]
@ganesh17492 I haven't heard back from you . Wanted to check if the above link Kushagra has shared worked for you. Please let us know.

Regards,
Oury

**Comment by Oury-MSFT** [comment]
Hi @ganesh17492 Thanks for contacting Microsoft ! It is been sometime since we've heard from you- does this mean your issue is resolved ? We are going to assume as such and close out this git issue but please feel free to comment if you need anything or have more questions.

**Comment by ganesh17492** [comment]
> Hi @Oury-MSFT/@kushagraThapar, sorry for the delayed reply. We last week deployed the fix by replacing the RTB token with RBAC implementation and it fixed the memory issue completely. 

Thanks a lot! for your all support.

**Comment by Oury-MSFT** [comment]
Thanks for letting us know @ganesh17492 . I am glad this has been resolved.
