### ISSUE TITLE
[FEATURE REQ] Add support for non ssl connections to cosmos db emulator

### ISSUE THREAD

**Issue by cemo** [Azure/azure-sdk-for-java#22986]
**Is your feature request related to a problem? Please describe.**
We need to connect Cosmos DB emulator by using insecure connections. Right now it is forcing us to use ssl. 

**Describe the solution you'd like**
I need to connect cosmos db emulator for unit tests but I don't want to deal with ssl related things. So far we used hacky reflection things to inject a new SslContext into com.azure.cosmos.implementation.Configs. Please provide necessary API changes which are private one now.

**Comment by kushagraThapar** [comment]
@milismsft  - can you please take a look a this issue ?

**Comment by cemo** [comment]
We added support for Cosmos DB for those who will hit this issue. 

https://github.com/testcontainers/testcontainers-java/releases/tag/1.16.1
