### ISSUE TITLE
EventHubMessageConverter uses Char.defaultCharset

### ISSUE THREAD

**Issue by conniey** [Azure/azure-sdk-for-java#23027]
I encountered a bug in SO: https://stackoverflow.com/questions/68410571/junk-value-added-to-the-header-when-message-sent-to-azure-event-hub-topic where it looks like a mismatch in encoding/decoding strings.

https://github.com/Azure/azure-sdk-for-java/blob/main/sdk/spring/azure-spring-integration-eventhubs/src/main/java/com/azure/spring/integration/eventhub/converter/EventHubMessageConverter.java#L47 uses Char.defaultCharset(), which is subject to change depending on the system's locale. We usually use UTF-8 for encoding.

Does this exist elsewhere in the SDK?

**Comment by yiliuTo** [comment]
Thanks @conniey , we have updated the messageconverter to be aligned with azure-messaging-eventhub.
