### ISSUE TITLE
[BUG] CosmosDb spans are INTERNAL and not parents of underlying HTTP spans

### ISSUE THREAD

**Issue by lmolkova** [Azure/azure-sdk-for-java#23032]
**Describe the bug**
1. CosmosDB creates public API spans, auto-instrumentation (with otel agent or app insights agent) tracks underlying HTTP calls.
Underlying HTTP calls (there is no way to suppress them currently) are siblings (not children) of Cosmos spans and are confusing and misleading. It's also not clear if they are coming from CosmosDb or user app. To, at least, reduce the confusion, we'd like to make them children of Cosmos calls. 

2. Spans are INTERNAL, which breaks OTel expectations and means Azure Monitor can't show cosmos on the application map 

**To Reproduce**
1) use cosmosdb sample app
2) [add and configure](https://docs.microsoft.com/en-us/azure/azure-monitor/app/java-standalone-config#auto-collected-azure-sdk-telemetry-preview) appinsights agent 

***Code Snippet***
Add the code snippet that causes the issue.

**Expected behavior**
http spans are children of cosmos spans (in future, we may want them to be suppressed, but OpenTelemtry does not support it at the moment).

Spans are CLIENT.

**Screenshots**
![image](https://user-images.githubusercontent.com/2347409/126013023-bb13f0e8-97d2-42bc-9e15-ddf91c6aa92b.png)

[transaction link](https://ms.portal.azure.com/#blade/AppInsightsExtension/DetailsV2Blade/DataModel/%7B%22eventId%22:%2231cede6c-e577-11eb-b561-501ac5103a4d%22,%22timestamp%22:%222021-07-15T14:15:47.747Z%22%7D/ComponentId/%7B%22Name%22:%22spring-boot-1623527233948%22,%22ResourceGroup%22:%22limolkova%22,%22SubscriptionId%22:%22faa080af-c1d8-40ad-9cce-e1a450ca5b57%22%7D)

**Setup (please complete the following information):**
 - OS: windows
 - IDE: IntelliJ
 - Library/Libraries: com.azure:azure-core:1.17.0, com.azure:azure-cosmos:4.17.0

**Additional context**
CosmosDB can't fix it without support in azure-core to create spans **and make them current, and allow to specify CLIENT kind**. So this needs to be addressed first.

**Information Checklist**
Kindly make sure that you have added all the following information above and checkoff the required fields otherwise we will treat the issuer as an incomplete report
- [x] Bug Description Added
- [x] Repro Steps Added
- [x] Setup information Added

**Comment by samvaity** [comment]
>Underlying HTTP calls (there is no way to suppress them currently) are siblings (not children) of Cosmos spans and are confusing and misleading.

Agreed, they should have a parent-child relation. But is this behavior true for other exporters also, apart from App Insights?
