### ISSUE TITLE
[BUG] Tracing is broken for EventHub binder

### ISSUE THREAD

**Issue by lmolkova** [Azure/azure-sdk-for-java#23035]
**Describe the bug**
Following the [eventhub binder app doc](https://docs.microsoft.com/en-us/azure/developer/java/spring-framework/configure-spring-cloud-stream-binder-java-app-azure-event-hub) with tracing enabled:  message span is not correlated to incoming request.

This is a reactor context propagation issue and we'd need to find
- way to manually pass context  (if possible)
- make magical propagation work

This issue is mostly created for investigation purposes.

It does not affect non-binder scenario (e.g. [this one](https://docs.microsoft.com/en-us/azure/event-hubs/event-hubs-java-get-started-send#add-code-to-publish-events-to-the-event-hub))

**To Reproduce**
1. [create sample app](https://docs.microsoft.com/en-us/azure/developer/java/spring-framework/configure-spring-cloud-stream-binder-java-app-azure-event-hub)
2. [add application insights agent and configure azure sdk tracing](https://docs.microsoft.com/en-us/azure/azure-monitor/app/java-standalone-config#auto-collected-azure-sdk-telemetry-preview)
3. send/receive/process message
4. check message span - it is not correlated to the incoming request

**Expected behavior**
message span is created as a child of incoming request.

**Screenshots**

**Actual**: Two traces (with 2 trace-ids)

![image](https://user-images.githubusercontent.com/2347409/126016130-234f93c3-54f2-40f3-be1f-a2c81c65b796.png)

![image](https://user-images.githubusercontent.com/2347409/126016012-e97d4a94-c689-472b-af79-4138f4f9f9a9.png)

**Expected**: 1 trace (created without binder)

![image](https://user-images.githubusercontent.com/2347409/126017805-d06a550b-e4b5-400e-9a02-d703a26bacd2.png)

**Setup (please complete the following information):**
 - OS: windows
 - IDE: IntelliJ
 - Library/Libraries: com.azure:azure-core:1.17.0,  com.azure:azure-core:1.17.0, com.azure:azure-core-tracing-opentelemetry:1.0.0-beta12,  com.azure.spring:azure-spring-cloud-stream-binder-eventhubs:2.5.0, applicationinsights-agent-3.1.1 

**Additional context**
Context is available when sending messages to supply sink

![image](https://user-images.githubusercontent.com/2347409/126016330-b6456cb1-347e-4f32-bd1e-d0cd2891778d.png)

But lost when a message is instrumented

![image](https://user-images.githubusercontent.com/2347409/126016463-3c5647c5-1252-4e79-b673-38594330dc57.png)

Stacktrace shows the attempt of otel agent to propagate reactor context, but it's not successful.

**Information Checklist**
Kindly make sure that you have added all the following information above and checkoff the required fields otherwise we will treat the issuer as an incomplete report
- [x] Bug Description Added
- [x] Repro Steps Added
- [x] Setup information Added

**Comment by stliu** [comment]
@lmolkova Hi is this still valid?
