### ISSUE TITLE
Mistake in documentation

### ISSUE THREAD

**Issue by sivasubramanian-b** [Azure/azure-sdk-for-java#23037]
Mistake in documentation
azure.storage.blob-endpoint is optional when file storage client is used and mandatory for blob storage client
https://stackoverflow.com/a/68432426/14129894

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 503c5ec5-ec8b-fd94-a358-d2936c4fd810
* Version Independent ID: 573ac7cd-4886-0a83-bb01-75b26e35c674
* Content: [Azure Spring Boot Starter Storage client library for Java](https://docs.microsoft.com/en-us/java/api/overview/azure/spring-boot-starter-storage-readme?view=azure-java-stable)
* Content Source: [docs-ref-services/latest/spring-boot-starter-storage-readme.md](https://github.com/Azure/azure-docs-sdk-java/blob/master/docs-ref-services/latest/spring-boot-starter-storage-readme.md)
* Service: **springboot**
* Product: **azure**
* Technology: **azure**
* GitHub Login: @maggiepint
* Microsoft Alias: **magpint**

**Comment by JonathanGiles** [comment]
Thank you for the report. We will take care of this.

**Comment by backwind1233** [comment]
Thanks @sivasubramanian-b , we have made a [PR ](https://github.com/Azure/azure-sdk-for-java/pull/23051) to update the description and others.
