### ISSUE TITLE
[Azure Identity] InteractiveBrowserCredential fails in GraalVM native image if AWT is not supported

### ISSUE THREAD

**Issue by srnagar** [Azure/azure-sdk-for-java#23072]
**Describe the bug**
If AWT packages are not in the classpath, InteractiveBrowserCredential fails with `NoClassDefFoundError`.

***Exception or Stack Trace***
```
Caused by: java.lang.NoClassDefFoundError: Could not initialize class java.awt.Toolkit
com.oracle.svm.core.classinitialization.ClassInitializationInfo.initialize(ClassInitializationInfo.java:239)
java.awt.Desktop.isDesktopSupported(Desktop.java:328)
com.microsoft.aad.msal4j.AcquireTokenByInteractiveFlowSupplier.openDefaultSystemBrowser(AcquireTokenByInteractiveFlowSupplier.java:112)
com.microsoft.aad.msal4j.AcquireTokenByInteractiveFlowSupplier.getAuthorizationResult(AcquireTokenByInteractiveFlowSupplier.java:61)
com.microsoft.aad.msal4j.AcquireTokenByInteractiveFlowSupplier.execute(AcquireTokenByInteractiveFlowSupplier.java:37)
```

**To Reproduce**
Run the following JUnit test for native-image. See instructions to set up the maven plugin in this [blog post](https://medium.com/graalvm/gradle-and-maven-plugins-for-native-image-with-initial-junit-testing-support-dde00a8caf0b).

```java
@Test
void createInteractiveBrowserCredential() {
        InteractiveBrowserCredential interactiveBrowserCredential = new InteractiveBrowserCredentialBuilder()
            .port(8765)
            .build();

        // Azure SDK client builders accept the credential as a parameter
        SecretClient client = new SecretClientBuilder()
            .vaultUrl(AZURE_KEY_VAULT_URL)
            .credential(interactiveBrowserCredential)
            .buildClient();
        assertNotNull(client);   
        client .setSecret(new KeyVaultSecret("foo", "f4G34fMh8v")
           .setProperties(new SecretProperties().setExpiresOn(OffsetDateTime.now().plusYears(1))));
     
}
```

**Expected behavior**
Instead of throwing an exception when AWT classes are not found, provide a link that can be opened in a browser.

**Screenshots**

**Setup (please complete the following information):**
 - OS: MacOS, Windows and Linux native images
 - IDE: Any
 - Library/Libraries: com.azure:azure-identity:1.3.1

**Additional context**
This was tested using [GraalVM version 21.1.0 ](https://github.com/graalvm/graalvm-ce-builds/releases/tag/vm-21.1.0)

**Information Checklist**
Kindly make sure that you have added all the following information above and checkoff the required fields otherwise we will treat the issuer as an incomplete report
- [x] Bug Description Added
- [x] Repro Steps Added
- [x] Setup information Added

**Comment by g2vinay** [comment]
A link that can be opened in browser for interactive auth, is already provided by Device code credential for interactive auth. Having Two Credentials do the same thing will not offer any extra value I feel.

So, Device Code Credential will work perfectly fine for interactive auth and is built for platforms where browsers are not accessible programatically.

Interactive Auth is possible on GraalVM via DC credential.

**Comment by g2vinay** [comment]
Closing this, as the suggested Interactive flow is available via Device code credential and not a blocker for GraalVM.
