### ISSUE TITLE
[DOC] Guidance for checkpointing and concurrency in Event Hubs

### ISSUE THREAD

**Issue by conniey** [Azure/azure-sdk-for-java#23090]
* Add guidance for using processEventBatch vs processEvent
* Document the difference between balanced and greedy load balancing, related parameters, and their impact on storage calls.
    * Create guidance for when to checkpoint Event Hubs for Azure storage because it may take several seconds to checkpoint to storage.
* Documentation (update) on the EH credit flow the impact of user application blocking calls on credit placement.
* Revisit the documentation related to concurrency (EH, SB) and ensure it has the necessary information that CX is looking for.

**Comment by stliu** [comment]
@yiliuTo this would be very useful to our customers, we should link the content to our doc as well once this issue is resolved
