### ISSUE TITLE
[BUG] Deleting a large number of blobs with BlobBatchClient causes OOM.

### ISSUE THREAD

**Issue by woolamkang** [Azure/azure-sdk-for-java#23104]
**Describe the bug**
Deleting a large number of blobs with BlobBatchClient causes "Out of Memory(OOM)".
When blobBatchClient.deleteBlobs(urls) is called, UrlBuilder.parse(url) is called internally for each url in urls.
UrlBuilder.parse(url) creates a new UrlBuilder instance and stores it in a map called PARSED_URLS. Therefore, UrlBuilder is created as many as the number of urls.
Therefore, if you try to delete a large number of blobs, OOM may occur due to UrlBuilders.

***Exception or Stack Trace***
None

**To Reproduce**
Try to delete a large number of blobs with BlobBatchClient
(I tried to delete about total 15,000,000 blobs - deleting 48 blobs * 320,000 repetitions.)

***Code Snippet***
None

**Expected behavior**
OOM occurs.

**Screenshots**
![image](https://user-images.githubusercontent.com/51349115/126452004-e8b8f56b-f281-4465-9da9-e7b0eaa4e34f.png)

**Setup (please complete the following information):**
 - OS: CentOS 6
 - IDE: -
 - Library/Libraries: com.azure:azure-storage-blob-batch:12.10.0

**Additional context**
None

**Information Checklist**
Kindly make sure that you have added all the following information above and checkoff the required fields otherwise we will treat the issuer as an incomplete report
- [v] Bug Description Added
- [v] Repro Steps Added
- [v] Setup information Added

**Comment by alzimmermsft** [comment]
Thank you for reporting this @woolamkang, [this PR](https://github.com/Azure/azure-sdk-for-java/pull/22697) resolve this issue by rolling the URL cache once a limit is hit.

A newer version of `azure-storage-blob-batch` built on the `azure-core` version (1.18.0) hasn't been released yet, but in your project, as a temporary workaround until a newer version of `azure-storage-blob-batch` is released, adding a dependency on that version of `azure-core` should resolve the OutOfMemoryError you're experiencing.

**Comment by woolamkang** [comment]
@alzimmermsft Thank you! With azure-core:1.18.0, OOM doesn't occur.
