### ISSUE TITLE
[BUG] CloudBlockBlob getURI Returns a URL with an Extra Space at the End Occassionally

### ISSUE THREAD

**Issue by nilavghosh** [Azure/azure-sdk-for-java#23110]
**Describe the bug**
On some occassions the CloudBlockBlob .getURI() method returns an extra space at the end of the blob url

***Exception or Stack Trace***
example https://storagedocsdev.blob.core.windows.net/filled-forms/49f4735f-d168-4277-9938-b9705f357973/4ed84478-666a-4fd9-b659-d43f66694762.pdf%20.  - after encoding the url

**To Reproduce**
The behaviour is intermittent

***Code Snippet***
CloudBlockBlob blob = container.getBlockBlobReference(blobName);
blob.upload(file.getInputStream(), file.getSize());
LOG.info("file uploded ");
URI documentUri = blob.getUri();

**Expected behavior**
There should not be a blank space returned at the end of the blob url.

**Screenshots**

**Setup (please complete the following information):**
 - OS: Linux
 - IDE: NA
 - Library/Libraries: Azure Blob Java SDK

**Additional context**

**Information Checklist**
Kindly make sure that you have added all the following information above and checkoff the required fields otherwise we will treat the issuer as an incomplete report
- [*] Bug Description Added
- [*] Repro Steps Added
- [*] Setup information Added

**Comment by rickle-msft** [comment]
Hi, @nilavghosh. Unfortunately we are no longer doing bug fixes in track 1. If you would like more support, we request that you move to track 2 (v12+).
