### ISSUE TITLE
Cosmos db OLTP connector custom query with TOP or Limit clause return wrong number of document

### ISSUE THREAD

**Issue by sajins2005** [Azure/azure-sdk-for-java#23113]
**Describe the bug**
Cosmos db OLTP connector custom query with TOP or Limit clause return wrong number of document
Query1 =SELECT Top 1 *  FROM c   where c.Aggregation='Raw' ORDER by c.TimeStamp desc
Query2 =SELECT * FROM c   where c.Aggregation='Raw' ORDER by c.TimeStamp desc OFFSET 0 LIMIT 1

Expected to get one result from this query and same query is giving one result when executed from Cosmosdb Data explorer sql query window. but the query is giving 9 result in  Azure databricks with OLTP connctor  com.azure.cosmos.spark:azure-cosmos-spark_3-1_2-12:4.2.0
 databricks Runtime version is 7.3 LTS (includes Apache Spark 3.0.1, Scala 2.12)

***Exception or Stack Trace***
NA

***Code Snippet***
 query =   "SELECT * FROM c   where c.Aggregation='Raw' ORDER by c.TimeStamp desc OFFSET 0 LIMIT 1"
  readConfig = {
  "spark.cosmos.accountEndpoint" : cosmosUrl,
  "spark.cosmos.accountKey" : cosmosKey,
  "spark.cosmos.database" : database_id,
  "spark.cosmos.container" : "OilOutput",
  "spark.cosmos.read.customQuery":query,
  "spark.cosmos.read.inferSchema.forceNullableProperties": "true",
    "spark.cosmos.read.inferSchema.includeSystemProperties": "true"
  
 }
  print(query)
   df=  rspark.read.format("cosmos.oltp").options(**readConfig).load()

display(df)

  **Expected behavior**

 query should return only* one result*
Screenshots**
Cosmos data explorer
![image](https://user-images.githubusercontent.com/14212161/126503606-cba2c613-9f5c-472e-80ac-7afc7bdbed18.png)
Azure Databricks
![image](https://user-images.githubusercontent.com/14212161/126505055-0c216e77-a4be-4402-b009-03f2ee602cc0.png)

**Setup (please complete the following information):**
 
 - IDE:  Azure databrick
 - Library/Libraries: com.azure.cosmos.spark:azure-cosmos-spark_3-1_2-12:4.2.0,  databricks Runtime version is 7.3 LTS (includes Apache Spark 3.0.1, Scala 2.12)

**Information Checklist**
Kindly make sure that you have added all the following information above and checkoff the required fields otherwise we will treat the issuer as an incomplete report
- [X ] Bug Description Added
- [X ] Repro Steps Added
- [X ] Setup information Added

**Comment by joshfree** [comment]
Thanks for filing this, @sajins2005.  Someone from the `Cosmos` team will follow up with you shortly.

/cc @kushagraThapar

**Comment by kushagraThapar** [comment]
@moderakh  - please route this appropriately.

**Comment by moderakh** [comment]
@sajins2005 the support for cosmos custom query is very limited, we currently do not support cross partition resolution of data when cosmos custom query is used. meaning if you use LIMIT, TOP, ORDERBY. the data returned from individual cosmos partitions will respect the provided predicate (LIMIT, TOP, ORDERBY), but when we collect the data we do not apply another layer of filtering to ensure the total collected result is less than TOP or if the aggregated data is sorted or not.

If you don't use cosmos custom query and instead use spark query api, this should work without any issues.

The other option is the combination of cosmos custom query and spark query. If your cosmos custom query has LIMIT/TOP/ORDERBY which requires cross cosmos partition collection of data. you need to apply another layer of filtering using spark API on top of the resultant dataframe

FYI @FabianMeiswinkel

**Comment by sajins2005** [comment]
@moderakh , Thanks for the clarification. I will use alternative approach but using spark API or custom query with spark API means I am querying a large amount of data from Cosmos and applying a filter using spark. This approach will consume a lot of RU  compared to using limit, when my Cosmos custom query 'where' clause return a large amount of data. Is there any chance Top or Limit  going to be supported in future release?
