### ISSUE TITLE
Exception while creating Azure UserDelegation Key

### ISSUE THREAD

**Issue by kdevesh** [Azure/azure-sdk-for-java#23137]
**Describe the bug**
Getting exception while generating UserDelegation Key for Azure Blob
Exception: Can not instantiate Stax reader for XML source type class org.codehaus.stax2.io.Stax2ByteArraySource (unrecognized type)

***Exception or Stack Trace***
`CallbackNotImplemented: java.lang.IllegalArgumentException: Can not instantiate Stax reader for XML source type class org.codehaus.stax2.io.Stax2ByteArraySource (unrecognized type) Caused by: java.lang.IllegalArgumentException: Can not instantiate Stax reader for XML source type class org.codehaus.stax2.io.Stax2ByteArraySource (unrecognized type) at io.strati.libs.forklift.com.ctc.wstx.stax.WstxInputFactory.createSR(WstxInputFactory.java:770) at io.strati.libs.forklift.com.ctc.wstx.stax.WstxInputFactory.createXMLStreamReader(WstxInputFactory.java:345) at com.fasterxml.jackson.dataformat.xml.XmlFactory._createParser(XmlFactory.java:631) at com.fasterxml.jackson.dataformat.xml.XmlFactory._createParser(XmlFactory.java:29) at com.fasterxml.jackson.core.JsonFactory.createParser(JsonFactory.java:1124) at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:3643) at com.azure.core.util.serializer.JacksonAdapter.deserialize(JacksonAdapter.java:281) at com.azure.core.implementation.serializer.HttpResponseBodyDecoder.deserializeBody(HttpResponseBodyDecoder.java:169) at com.azure.core.implementation.serializer.HttpResponseBodyDecoder.lambda$decodeByteArray$1(HttpResponseBodyDecoder.java:105) at reactor.core.publisher.MonoFlatMap$FlatMapMain.onNext(MonoFlatMap.java:125) at reactor.core.publisher.Operators$ScalarSubscription.request(Operators.java:2397) at reactor.core.publisher.MonoFlatMap$FlatMapMain.onSubscribe(MonoFlatMap.java:110) at reactor.core.publisher.MonoJust.subscribe(MonoJust.java:54) at reactor.core.publisher.MonoDefer.subscribe(MonoDefer.java:52) at reactor.core.publisher.InternalMonoOperator.subscribe(InternalMonoOperator.java:64) at reactor.core.publisher.MonoDefer.subscribe(MonoDefer.java:52) at reactor.core.publisher.MonoCacheTime.subscribeOrReturn(MonoCacheTime.java:143) at reactor.core.publisher.InternalMonoOperator.subscribe(InternalMonoOperator.java:57) at reactor.core.publisher.MonoFlatMap$FlatMapMain.onNext(MonoFlatMap.java:157) at reactor.core.publisher.FluxContextWrite$ContextWriteSubscriber.onNext(FluxContextWrite.java:107) at reactor.core.publisher.FluxDoOnEach$DoOnEachSubscriber.onNext(FluxDoOnEach.java:173) at reactor.core.publisher.Operators$MonoSubscriber.complete(Operators.java:1815) at reactor.core.publisher.MonoFlatMap$FlatMapMain.onNext(MonoFlatMap.java:151) at reactor.core.publisher.FluxMap$MapSubscriber.onNext(FluxMap.java:120) at reactor.core.publisher.FluxOnErrorResume$ResumeSubscriber.onNext(FluxOnErrorResume.java:79) at reactor.core.publisher.Operators$MonoSubscriber.complete(Operators.java:1815) at reactor.core.publisher.MonoFlatMap$FlatMapMain.onNext(MonoFlatMap.java:151) at reactor.core.publisher.FluxDelaySubscription$DelaySubscriptionMainSubscriber.onNext(FluxDelaySubscription.java:188) at reactor.core.publisher.SerializedSubscriber.onNext(SerializedSubscriber.java:99) at reactor.core.publisher.SerializedSubscriber.onNext(SerializedSubscriber.java:99) at reactor.core.publisher.FluxTimeout$TimeoutMainSubscriber.onNext(FluxTimeout.java:179) at reactor.core.publisher.Operators$MonoSubscriber.complete(Operators.java:1815) at reactor.core.publisher.MonoFlatMap$FlatMapMain.onNext(MonoFlatMap.java:151) at reactor.core.publisher.MonoIgnoreThen$ThenIgnoreMain.complete(MonoIgnoreThen.java:284) at reactor.core.publisher.MonoIgnoreThen$ThenIgnoreMain.onNext(MonoIgnoreThen.java:187) at reactor.core.publisher.FluxMapFuseable$MapFuseableSubscriber.onNext(FluxMapFuseable.java:127) at reactor.core.publisher.FluxMapFuseable$MapFuseableSubscriber.onNext(FluxMapFuseable.java:127) at reactor.core.publisher.Operators$MonoSubscriber.complete(Operators.java:1815) at reactor.core.publisher.MonoFlatMap$FlatMapMain.onNext(MonoFlatMap.java:151) at reactor.core.publisher.SerializedSubscriber.onNext(SerializedSubscriber.java:99) at reactor.core.publisher.FluxRetryWhen$RetryWhenMainSubscriber.onNext(FluxRetryWhen.java:173) at reactor.core.publisher.FluxOnErrorResume$ResumeSubscriber.onNext(FluxOnErrorResume.java:79) at reactor.core.publisher.Operators$MonoInnerProducerBase.complete(Operators.java:2663) at reactor.core.publisher.MonoSingle$SingleSubscriber.onComplete(MonoSingle.java:180) at reactor.core.publisher.MonoFlatMapMany$FlatMapManyInner.onComplete(MonoFlatMapMany.java:260) at reactor.core.publisher.FluxMapFuseable$MapFuseableSubscriber.onComplete(FluxMapFuseable.java:150) at reactor.core.publisher.FluxMapFuseable$MapFuseableSubscriber.onComplete(FluxMapFuseable.java:150) at reactor.core.publisher.Operators$MonoSubscriber.complete(Operators.java:1816) at reactor.core.publisher.MonoCollect$CollectSubscriber.onComplete(MonoCollect.java:159) at reactor.core.publisher.FluxDoFinally$DoFinallySubscriber.onComplete(FluxDoFinally.java:145) at reactor.core.publisher.FluxHandle$HandleSubscriber.onComplete(FluxHandle.java:212) at reactor.core.publisher.FluxMap$MapConditionalSubscriber.onComplete(FluxMap.java:269) at reactor.netty.channel.FluxReceive.onInboundComplete(FluxReceive.java:401) at reactor.netty.channel.ChannelOperations.onInboundComplete(ChannelOperations.java:416) at reactor.netty.channel.ChannelOperations.terminate(ChannelOperations.java:470) at reactor.netty.http.client.HttpClientOperations.onInboundNext(HttpClientOperations.java:685) at reactor.netty.channel.ChannelOperationsHandler.channelRead(ChannelOperationsHandler.java:94)`

**To Reproduce**
Exception occurs while calling  blobServiceAsyncClient.getUserDelegationKey(keyStart,keyExpiry)

**Screenshot**
![image](https://user-images.githubusercontent.com/23445849/126653284-288e4115-e480-4622-aeb6-de078a867102.png)

***Code Snippet***
```private void uploadNextWeekReportToAzure() {
    BlobServiceAsyncClient blobServiceAsyncClient = blobServiceClientBuilder
        .credential(new DefaultAzureCredentialBuilder().build())
        .buildAsyncClient();
    BlobContainerAsyncClient blobContainerAsyncClient = blobServiceAsyncClient.getBlobContainerAsyncClient("container name");
    BlobAsyncClient blobAsyncClient = blobContainerAsyncClient.getBlobAsyncClient("blob name");
    OffsetDateTime keyStart = OffsetDateTime.now();
    OffsetDateTime keyExpiry = OffsetDateTime.now().plusDays(7);
    blobServiceAsyncClient.getUserDelegationKey(keyStart,keyExpiry)
    .doOnError(throwable -> log.error("Exception occurred:{}",throwable.getMessage()))
    .doOnSuccess(userDelegationKey -> {
      log.info("UserDelegationKey:{}",userDelegationKey.getValue());
      String saSToken = generateSaSToken(blobAsyncClient, userDelegationKey);
      log.info("SAS TOKEN:{}",saSToken);
    })
    .subscribe();
  }

private String generateSaSToken(BlobAsyncClient blobAsyncClient,
                                  UserDelegationKey userDelegationKey) {
    BlobContainerSasPermission blobContainerSasPermission = new BlobContainerSasPermission()
        .setReadPermission(true);
    BlobServiceSasSignatureValues builder = new BlobServiceSasSignatureValues(
        OffsetDateTime.now().plusDays(1), blobContainerSasPermission)
        .setProtocol(SasProtocol.HTTPS_ONLY);
    return String
        .format("https://%s.blob.core.windows.net/%s/%s?%s", blobAsyncClient.getAccountName(),
            blobAsyncClient.getContainerName(),
            blobAsyncClient.getBlobName(),
            blobAsyncClient.generateUserDelegationSas(builder, userDelegationKey));
  }
```

**Expected behavior**
Should generate the UserDelegationKey

**Setup (please complete the following information):**
 - OS: [MAC OS]
 - IDE:  IntelliJ]
 - Library/Libraries: azure-storage-blob:12:12.0

**Information Checklist**
Kindly make sure that you have added all the following information above and checkoff the required fields otherwise we will treat the issuer as an incomplete report
- [x] Bug Description Added
- [x] Repro Steps Added
- [x] Setup information Added

**Comment by kdevesh** [comment]
@jianghaolu Can you please help here?

**Comment by g2vinay** [comment]
@kdevesh 

This is happening likely due to a dependency conflict of Jackson in your project setup.
Could you please share the dependency tree of your application via command mvn dependency:tree -Dverbose

**Comment by kdevesh** [comment]
The issue was due to conflicting dependencies
