### ISSUE TITLE
Not able to enable diagnostic setting (Preview) using Java SDK

### ISSUE THREAD

**Issue by nirupbbnk** [Azure/azure-sdk-for-java#23136]
**Describe the bug**
We are trying to enable Diagnostic setting Preview using Java SDK. We are refering to below docs 
https://docs.microsoft.com/en-us/java/api/com.azure.resourcemanager.monitor.implementation.diagnosticsettingsclientimpl.createorupdatewithresponse?view=azure-java-stable
We are not able to call create method also not able to create a object of  Diagnosticsettingsclientimpl . 

**To Reproduce**
DiagnosticSettingsClientImpl diagnosticSettingsClient = new DiagnosticSettingsClientImpl();
or 
DiagnosticSettingsClientImpl.createOrUpdateWithResponse(String resourceUri, String name, DiagnosticSettingsResourceInner parameters, Context context)

***Code Snippet***
DiagnosticSettingsClientImpl diagnosticSettingsClient = new DiagnosticSettingsClientImpl();
or 
DiagnosticSettingsClientImpl.createOrUpdateWithResponse(String resourceUri, String name, DiagnosticSettingsResourceInner parameters, Context context).

**Expected behavior**
Able to call the above method to create diagnostic setting preview)

**Setup (please complete the following information):**
 - OS: Windows , Linux
 - IDE: IntelliJ
 - Library/Libraries: com.azure.resourcemanager:azure-resourcemanager-monitor:2.6.0

**Information Checklist**
Kindly make sure that you have added all the following information above and checkoff the required fields otherwise we will treat the issuer as an incomplete report
- [x] Bug Description Added
- [x] Repro Steps Added
- [x] Setup information Added

**Comment by joshfree** [comment]
Thanks for filing this issue, @nirupbbnk.  Someone from the `Mgmt` team will follow up shortly.

/cc @weidongxu-microsoft

**Comment by weidongxu-microsoft** [comment]
@nirupbbnk 

You can follow
```
            DiagnosticSetting setting = azure.diagnosticSettings()
                    .define(DS_NAME)
                    .withResource(vm.id())
                    .withStorageAccount(sa.id())
                    .withEventHub(evenHubNsRule.id())
                    .withLogsAndMetrics(categories, Period.minutes(5), 7)
                    .create();
```

If you like to directly call the REST API
```
azure.diagnosticSettings().manager().serviceClient().getDiagnosticSettings().createOrUpdate()
```
Note above method is for advance user, and might change with SDK version without notification.
