### ISSUE TITLE
Blob - how to set content type while uploading blob ?

### ISSUE THREAD

**Issue by abhikt48** [Azure/azure-sdk-for-java#23138]
We are using `azure-storage-blob-12.10.2` to upload blobs.  
While uploading blob with InputStream or File - By default content type is getting set as `application/octet-stream`.

Do we have any option to set custom content type as `application/text`, `application/json` etc..  ?

**Setup (please complete the following information if applicable):**
OS: window
IDE : eclipse
Version of the Library used: `azure-storage-blob-12.10.2`

**Comment by alzimmermsft** [comment]
Hi @abhikt48, to set the blob's `Content-Type` you'll want to use the overloads that accept `BlobHttpHeaders` as a parameter:

- https://github.com/Azure/azure-sdk-for-java/blob/main/sdk/storage/azure-storage-blob/src/main/java/com/azure/storage/blob/BlobClient.java#L248
- https://github.com/Azure/azure-sdk-for-java/blob/main/sdk/storage/azure-storage-blob/src/main/java/com/azure/storage/blob/BlobClient.java#L358

Or those that take `*Options` property bags as an input (as they should contain a `BlobHttpHeaders` property):

- https://github.com/Azure/azure-sdk-for-java/blob/main/sdk/storage/azure-storage-blob/src/main/java/com/azure/storage/blob/BlobClient.java#L283
- https://github.com/Azure/azure-sdk-for-java/blob/main/sdk/storage/azure-storage-blob/src/main/java/com/azure/storage/blob/BlobClient.java#L382

From there you'll set `BlobHttpHeaders.setContentType(String)` to the `Content-Type` you wish to associate with the blob.

**Comment by abhikt48** [comment]
/unresolve

Hi @alzimmermsft , Thanks for your quick reply. We are using below two options for upload and need to add ContentType on top of that
 ```
BlobClient.upload(stream, length, overwrite);
BlobClient.uploadFromFile(filePath, overwrite);
```
 
Based on your suggestion, I tried with below option for upload from Stream. We need to provide option for `overwrite `as well, so i copied overwrite logic from `BlobClient.upload(stream, length, overwrite)` **There is no concern here**.

```
BlobHttpHeaders headers = new BlobHttpHeaders();
headers.setContentType("application/json");
options.setHeaders(headers);
if (!overwrite) {
	BlobRequestConditions requestConditions = new BlobRequestConditions();
requestConditions.setIfNoneMatch(com.azure.storage.common.implementation.Constants.HeaderConstants.ETAG_WILDCARD);
	options.setRequestConditions(requestConditions);
}
blobClient.uploadWithResponse(options, null, Context.NONE);
```


I tried with below option for **upload from File.** We need to provide option for overwrite as well, this time **i can't apply same  overwrite logic** as I am getting compile time error..

![image](https://user-images.githubusercontent.com/22897837/127040028-9e0d729b-cd75-4dda-b918-68640eb941c0.png)


At the End, we need to provide option for **overwrite and content-type** to user. 
Could you please suggest best way to achieve this requirement for both operations (**upload from Stream and File**) ?
It will be great if we have separate option, so we don't need to write same overwrite  logic in our code.

**Comment by alzimmermsft** [comment]
Hi @abhikt48, to replicate the `overwrite` functionality in the APIs mentioned you'll want to either pass or omit the `BlobRequestConditions` based on whether `overwrite` is true or false. Going throw the APIs here are a few examples:

```java
void upload(BlobClient blobClient, InputStream data, long length, String contentType, boolean overwrite) {
  blobClient.uploadWithResponse(data, length, null, createContentType(contentType), null, null, createOverwriteConditions(overwrite), null, Context.NONE);
}

void uploadFromFile(BlobClient blobClient, String filePath, String contentType, boolean overwrite) {
  blobClient.uploadFromFile(filePath, null, createContentType(contentType), null, null, createOverwriteConditions(overwrite), null);
}

private BlobRequestConditions createOverwriteConditions(boolean overwrite) {
  BlobRequestConditions conditions = new BlobRequestConditions();

  if (!overwrite) {
    // Sets a request condition that there exists no blob.
    // See https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/If-None-Match for more details.
    // Also see https://docs.microsoft.com/en-us/rest/api/storageservices/specifying-conditional-headers-for-blob-service-operations.
    conditions.setIfNoneMatch("*");
  }

  return conditions;
}

private BlobHttpHeaders createContentType(String contentType) {
  if (contentType == null) {
    return null;
  }

  return new BlobHttpHeaders().setContentType(contentType);
}
```

**Comment by abhikt48** [comment]
@alzimmermsft  - Thanks a lot for quick update.
