### ISSUE TITLE
[BUG] aad-b2c-starter should not use AAD's token endpoint.

### ISSUE THREAD

**Issue by chenrujun** [Azure/azure-sdk-for-java#23134]
In current implementation, aad-bec-starter is using AAD's token end point.
It does not make sense because AAD B2C has it's own token endpoint.

After discuss with @moarychan and @ZhuXiaoBing-cn , 
I got that using AAD's token endpoint is because AAD B2C does not support client credential flow.

But in my understanding, if AAD B2C does not support client credential flow, 
aad-b2c-starter should not support client credential flow, instead of using AAD's token endpoint.

Refs:
1. AAD B2C has it's own endpoints: https://docs.microsoft.com/en-us/azure/active-directory-b2c/tokens-overview#endpoints
2. AAD B2C does not support client credential flow: https://docs.microsoft.com/en-us/azure/active-directory-b2c/application-types#current-limitations
3. Current aad-b2c-starter's code is using using AAD's endpoint: https://github.com/Azure/azure-sdk-for-java/blob/azure-spring-boot-starter-active-directory_3.7.0/sdk/spring/azure-spring-boot/src/main/java/com/azure/spring/autoconfigure/b2c/AADB2CURL.java#L28
4. Current aad-b2c-starter's diagram: https://github.com/Azure/azure-sdk-for-java/tree/azure-spring-boot-starter-active-directory_3.7.0/sdk/spring/azure-spring-boot-starter-active-directory-b2c#key-concepts

**Comment by zhichengliu12581** [comment]
Close this issue because when `GrantType` is `authorization_code`, we do not use B2C endpoints. And B2C starter only supports `client_credential` and the default `authorization_code`. we will [investigate whether we can deprecate azure-spring-boot-starter-active-directory-b2c](https://github.com/Azure/azure-sdk-for-java/issues/23545).
