### ISSUE TITLE
[FEATURE REQ] [azure-spring-integration-servicebus] Replace the ServiceBusProcessorClient with ServiceBusReceiverAsyncClient

### ISSUE THREAD

**Issue by michaelqi793** [Azure/azure-sdk-for-java#23155]
**Is your feature request related to a problem? Please describe.**
Processor client does not support batch consumption.

**Describe the solution you'd like**

Replace the the ServiceBusProcessorClient with ServiceBusReceiverAsyncClient.

**Describe alternatives you've considered**

**Additional context**

This replacement need take care of 4 cases:
1 Queue without session
2 Topic  without session
3 Queue with session
4 Topic with session

The replacement is doable and in progress for case 1 and 2.   But there is no convenient API for case 3 and 4. ServiceBusSessionReceiverAsyncClient's acceptNextSession only returns messages of one session and hangs there. 

**Information Checklist**
Kindly make sure that you have added all the following information above and checkoff the required fields otherwise we will treat the issuer as an incomplete report
- [ yes] Description Added
- [ yes] Expected solution specified

**Comment by joshfree** [comment]
Thanks for filing this @michaelqi793, @yiliuTo could you please follow up?

/cc @ki1729

**Comment by saragluna** [comment]
@yiliuTo can we close this now?

**Comment by yiliuTo** [comment]
@saragluna I think we can close this for we have provide the autoconfiguration of the receiver client and have issue https://github.com/Azure/azure-sdk-for-java/issues/26461 to track the feature of receiver client
