### ISSUE TITLE
[BUG] ServiceBusClientBuilder wrong documentation about prefetchCount

### ISSUE THREAD

**Issue by p4p4** [Azure/azure-sdk-for-java#23156]
**Describe the bug**
The ServiceBusClientBuilder states that the default `prefetchCount` is `1`, but in reality it is `0`

***Code Snippet***
in `com.azure.messaging.servicebus.ServiceBusClientBuilder.ServiceBusReceiverClientBuilder#prefetchCount`
```
         * Sets the prefetch count of the receiver. For both {@link ServiceBusReceiveMode#PEEK_LOCK PEEK_LOCK} and
         * {@link ServiceBusReceiveMode#RECEIVE_AND_DELETE RECEIVE_AND_DELETE} modes the default value is 1.
         *
         * Prefetch speeds up the message flow by aiming to have a message readily available for local retrieval when
         * and before the application asks for one using {@link ServiceBusReceiverAsyncClient#receiveMessages()}.
         * Setting a non-zero value will prefetch that number of messages. Setting the value to zero turns prefetch
         * off. 
```

but in the same class in the constructor:

```
    // Using 0 pre-fetch count for both receive modes, to avoid message lock lost exceptions in application
    // receiving messages at a slow rate. Applications can set it to a higher value if they need better performance.
    private static final int DEFAULT_PREFETCH_COUNT = 0;
    
    ...
    
    private int prefetchCount = DEFAULT_PREFETCH_COUNT;
```

**Expected behavior**
no misleading documentation

**Setup (please complete the following information):**
library version:
implementation group: 'com.azure', name: 'azure-messaging-servicebus', version: '7.2.0'

**Comment by joshfree** [comment]
Thanks for catching this, @p4p4.  @ki1729 can you please follow on this and also double check the other tier-1 languages?

**Comment by anuchandy** [comment]
addressed in https://github.com/Azure/azure-sdk-for-java/pull/23755
