### ISSUE TITLE
Packages should only be released if they will install successfully

### ISSUE THREAD

**Issue by danieljurek** [Azure/azure-sdk-for-java#23158]
This may already be satisfied by: https://github.com/Azure/azure-sdk-for-java/blob/main/eng/versioning/scan_for_unreleased_dependencies.ps1 

We could perhaps do other sanity checking as well, for example installing the package in isolation where Maven must resolve dependencies from external sources instead of using the source repo. However the delays present in publishing to Maven Central may make this less likely. 

Alternatively we could sanity test by publishing a package that is about to be released to a private feed and then attempting to install the package from that private feed with Maven as a backup. In that case an unreleased dependency in the same service should cause a dependency resolution error. Private feeds would need to be cleaned up.

**Comment by alzimmermsft** [comment]
Related to https://github.com/Azure/azure-sdk-for-java/issues/15894
