### ISSUE TITLE
AzureEvent Hub Consumer is missing messages intermittently when we stop and start the event client processor[BUG]

### ISSUE THREAD

**Issue by ssudarjothi** [Azure/azure-sdk-for-java#23161]
**Describe the bug**
We have an Azure Event Hub consumer process coded in Java 8 running in Docker environment with EventProcessorClient. We are starting the eventprocessorclient and after 55 minutes we are stopping the event processor client and then we are starting the whole consumer process once again. Intermittently when stop the processor and start the processor, we are missing the sequences in between. 

for example, in partition 0, we have committed the sequence number 689 before we shut down the EventProcessorClient, then again when start the EventProcessorClient, we are consuming the sequence number 692 from the same partition 0.  We are missing the sequence number 690 and 691.  There is no trace or logs to show that we have consumed the sequence number 690 and 691 from Partition 0. What could have happened to these message and how it got committed when we don't consume and commit these events in the blob storage?

***Exception or Stack Trace***
Add the exception log and stack trace if available

**To Reproduce**
We couldn't reproduce the same in lower life cycle. Its happening intermittently. 

***Code Snippet***
                              EventProcessorClient eventProcessorClient = new EventProcessorClientBuilder()
					.processEvent(this::processEvent, Duration.ofMillis(config.getHealthInterval()))
					.processError(this::processError).processPartitionInitialization(this::initializePartition)
					.processPartitionClose(this::closePartition)
					.credential(config.getFullyQualifiedNamespace(), config.getEventHubName(), credential)
					.consumerGroup(config.getConsumerGroup()).checkpointStore(config.getBlobCheckpoint(credential))
					.initialPartitionEventPosition(map).proxyOptions(getproxyOptions())
					.transportType(AmqpTransportType.AMQP_WEB_SOCKETS).buildEventProcessorClient();
					
					eventProcessorClient.start();

					TimeUnit.MILLISECONDS.sleep(config.getProcessInterval());

					eventProcessorClient.stop();

**Expected behavior**
We are not expecting to miss any sequences/events when we stop and start the processor.

**Screenshots**
NA

**Setup (please complete the following information):**
 - OS: Windows
 - IDE: Springboot Javaa 8
         compile('com.azure:azure-client-sdk-parent:1.7.0')
	compile('com.azure:azure-messaging-eventhubs:5.1.1')
	compile('com.azure:azure-storage-blob:12.6.1')
	compile(group: 'com.azure', name: 'azure-core-http-netty', version: '1.5.4')
	compile('com.azure:azure-identity:1.1.0-beta.7')
	compile('com.azure:azure-messaging-eventhubs-checkpointstore-blob:1.1.1')

**Additional context**

**Information Checklist**
Kindly make sure that you have added all the following information above and checkoff the required fields otherwise we will treat the issuer as an incomplete report
- [Y ] Bug Description Added
- [ Y] Repro Steps Added
- [Y ] Setup information Added

**Comment by joshfree** [comment]
@conniey could you please follow up?

/cc  @anuchandy @YijunXieMS

**Comment by sbaunthiyal** [comment]
Hello @conniey , Looking forward to have response on this issue. We are facing this in production environment as well. Which makes it critical for us.

**Comment by conniey** [comment]
Hey. We are looking into this issue.

**Comment by sbaunthiyal** [comment]
Hi @conniey , Any update to share? Let us know if you need any further details.

**Comment by ssudarjothi** [comment]
Hi @conniey, Do you have any updates for this issue?  Thanks.

**Comment by conniey** [comment]
I don't have any updates on this issue.

**Comment by ssudarjothi** [comment]
@conniey , could you please advise to which sprint this has been assigned in your backlog and when we can expect some upodates on this ticket? This sporadic issue is happening n Prod and its really critical for us, so if you could provide some timelines for any updates, that will be helpful.  Thanks.

**Comment by ZejiaJiang** [comment]
There are some related issue:
https://github.com/Azure/azure-sdk-for-java/issues/26764
https://github.com/Azure/azure-sdk-for-java/issues/23950

We are waiting for a third party fix.
Currently, using processEvent(Consumer<EventContext>) or  processEventBatch(Consumer<EventBatchContext>, int) can fix it.

**Comment by ramya-rao-a** [comment]
Hey @ssudarjothi 

Please subscribe to https://github.com/Azure/azure-sdk-for-java/issues/23950 for updates on the third party fix.
Meanwhile, please use the workaround described in #26764

For more discussion, we can use the support ticket that you have opened for this issue.

Thanks for reporting!
