### ISSUE TITLE
[BUG] No new receive link is re-created if the current receive link is locally closed

### ISSUE THREAD

**Issue by YijunXieMS** [Azure/azure-sdk-for-java#23172]
**Describe the bug**
I did long running tests for azure-messaging-eventhubs 5.9.0 (Using EventProcessorClient) and azure-messaging-service 7.3.0 (Using ServiceBusProcessorClient). Both use azure-core-amqp 2.3.0. In some tests after a few days of running, some partitions of EventHubs stopped receiving. ServiceBus also stopped receiving.

In the logs of both EH and SB, I see this exception `java.nio.channels.ClosedByInterruptException: null`. For the complete logs, download [ClosedByInterruptExceptionLogs.zip](https://github.com/Azure/azure-sdk-for-java/files/6871649/ClosedByInterruptExceptionLogs.zip).

Logs show that `onLinkLocalClose` of the `LinkHandler` is called. But neither `onLinkRemoteClose` nor `onLinkFinal` is called. 
In the current implementation, `onLinkRemoteClose` emits an exception to the link endpointStates, or close the link handler, which emit a close and a complete to the endpointStates. Refer to [handleRemoteLinkClosed](https://github.com/Azure/azure-sdk-for-java/blob/acd27102a71a51dbd141c3c259f5e37867f8e0d0/sdk/core/azure-core-amqp/src/main/java/com/azure/core/amqp/implementation/handler/LinkHandler.java#L85-L92). `onLinkFinal` closes the link handler, which emit a close and a complete to the endpointStates. Refer to [onLinkClose](https://github.com/Azure/azure-sdk-for-java/blob/acd27102a71a51dbd141c3c259f5e37867f8e0d0/sdk/core/azure-core-amqp/src/main/java/com/azure/core/amqp/implementation/handler/LinkHandler.java#L54). Using service bus as an example, `ServiceBusReceiveLinkProcessor` request a new receive link from upstream only when the endpointStates get an exception, or is completed. Since the `onLinkLocalClose` currently doesn't emit an exception or complete status to endpointStates, the link processor doesn't request a link from the upstream. We might need to emit error/complete to the endpointStates in `onLinkLocalClose` instead of in `onLinkRemoteClose` or `onLinkFinal`.

***Exception or Stack Trace***
Refer to the uploaded logs [ClosedByInterruptExceptionLogs.zip](https://github.com/Azure/azure-sdk-for-java/files/6871649/ClosedByInterruptExceptionLogs.zip)

**To Reproduce**
I started the test in an ACI linux container with 2 vCPUs and get it run for long time.
But this doesn't necessarily happen for every run.
I don't know a certain way to reproduce it in short time. Let me know if anybody knows.

***Code Snippet***
Some normal event receiving code that uses `EventProcessorClient`, or service bus message receiving code that uses `ServiceBusProcessorClient`.

**Expected behavior**
The app should recover from this network error and continue to receive the events.

**Screenshots**
N/A

**Setup (please complete the following information):**
 - OS: [e.g. iOS] Azure ACI container linux.
 - Library/Libraries: azure-core-amqp 2.3.0, azure-messaging-eventhubs 5.9.0, azure-messaging-servicebus 7.3.0

**Additional context**
N/A

**Information Checklist**
Kindly make sure that you have added all the following information above and checkoff the required fields otherwise we will treat the issuer as an incomplete report
- [ x ] Bug Description Added
- [ x ] Repro Steps Added
- [ x ] Setup information Added

**Comment by YijunXieMS** [comment]
This is a dev build that may fix this problem. We may still change code for the fix in GA though.
[0727-devbuild.zip](https://github.com/Azure/azure-sdk-for-java/files/6890360/0727-devbuild.zip)

**Comment by yuriy-osychenko** [comment]
@YijunXieMS Can you please clarify if this issue and fix is connected to existing issue: https://github.com/Azure/azure-sdk-for-java/issues/18890
Or this one is completely separate?
I am asking because the issue 18890 is happening from time to time on our prod environment and it is very important for us

**Comment by YijunXieMS** [comment]
@yuriy-osychenko yes this should be helpful in recovering from stop receiving. If you use ServiceBus 7.0.0, I suggest you upgrade to the latest version 7.3.0 first, which has some fixes since 7.0.0. This dev build fixes an issue that may happen in 7.3.0.

**Comment by shubhambhattar** [comment]
I'm facing a similar issue where EventProcessorClient stops reading from certain partitions intermittently and doesn't recover. The recovery part, I am really not sure. Most of the time it doesn't recover but I've an instance where it did recover automatically. I am using version `azure-messaging-eventhubs:5.9.0`. 
<img width="1370" alt="Screenshot 2021-08-04 at 1 16 01 PM" src="https://user-images.githubusercontent.com/11096682/128142441-0bb32d8b-bcde-424d-ac07-314c81d061fc.png">

**Comment by frascu** [comment]
I have the same problem. Are there any news about the fix?

**Comment by conniey** [comment]
> I have the same problem. Are there any news about the fix?

Can you create a new bug for this issue you're experiencing? The problem with this issue was fixed. https://github.com/Azure/azure-sdk-for-java/issues/new?assignees=&labels=&template=bug_report.md&title=%5BBUG%5D

**Comment by shubhambhattar** [comment]
@frascu I am using this https://github.com/shubhambhattar/eventhub-consumer/blob/main/src/main/java/com/example/demo/service/EventProcessorClientHealthIndicator.java to detect inactivity and trigger a restart by marking health as down.
