### ISSUE TITLE
[BUG] No responses when deleting blobs using BlobBatchClient.

### ISSUE THREAD

**Issue by woolamkang** [Azure/azure-sdk-for-java#23194]
**Describe the bug**
No responses when deleting blobs using BlobBatchClient.
I use the following code like sample code in azure-storage-blob-batch SDK.

`
Iterable<Response<Void>> iterable = blobBatchClient.deleteBlobs(blobUrls, DeleteSnapshotsOptionType.INCLUDE);
List<Response<Void>> resultList = StreamSupport.stream(iterable.spliterator(), false).collect(toList());
log.info("result: {} {}", resultList.size(), resultList);
`

"blobUrls" contains 48 blob URLs. All blobs existed and have been deleted normally after running the batch job. But I get no response.
It means that the size of "resultList" is 0.

***Exception or Stack Trace***
None

**To Reproduce**
Use the following code.

***Code Snippet***
Add the code snippet that causes the issue.

`
Iterable<Response<Void>> iterable = blobBatchClient.deleteBlobs(blobUrls, DeleteSnapshotsOptionType.INCLUDE);
List<Response<Void>> resultList = StreamSupport.stream(iterable.spliterator(), false).collect(toList());
log.info("result: {} {}", resultList.size(), resultList);
`

**Expected behavior**
I expected to get responses for each of the 48 blob deletions. But the response list was empty.

**Screenshots**
None

**Setup (please complete the following information):**
 - OS: CentOS
 - IDE: IntelliJ IDEA
 - Library/Libraries: azure-storage-blob-batch:12.10.0

**Additional context**
None

**Information Checklist**
Kindly make sure that you have added all the following information above and checkoff the required fields otherwise we will treat the issuer as an incomplete report
- [v] Bug Description Added
- [v] Repro Steps Added
- [v] Setup information Added

**Comment by alzimmermsft** [comment]
Thank you for submitting this issue @woolamkang.

When running the code snippet you've included, do the blobs get deleted on the service? Effectively, is the batch request being sent or not.

cc: @rickle-msft @kasobol-msft

**Comment by woolamkang** [comment]
@alzimmermsft Yes. All blobs got deleted. But list of reponses is empty.

**Comment by rickle-msft** [comment]
@woolamkang Can you please include a code snippet that shows how you are using the BatchClient and evaluating the response?

**Comment by alzimmermsft** [comment]
This will be resolved in the next release included the associated PR

**Comment by woolamkang** [comment]
@alzimmermsft Thank you for the reply. I changed the "fromRunnable" call to the "fromCallable" call in the "mapBatchResponse" method of "BlobBatchHelper" class. and got the response normally. Can you explain how this way is different from your PR?

**Comment by alzimmermsft** [comment]
> Can you explain how this way is different from your PR?

For the most part they'll accomplish the same goal of:

- Emitting onComplete once the method completes successfully
- Emitting onNext if the method emits a return
- Emitting onError if an error occurs during the method

The last part is where the major difference is. `Mono.fromCallable` will only emit an error if an exception is thrown from the method, `Mono.create` allows for finer control when an exception doesn't need to be thrown but emitted using the `MonoSink` (`sink.error`). In the end, based on the method both would have works but `Mono.create` is more flexible.

**Comment by alzimmermsft** [comment]
Hi @woolamkang, the fix for this issue has been released in the latest version of `azure-storage-blob-batch`
