### ISSUE TITLE
[QUERY] How to Populate Service Bus Message Application Properties

### ISSUE THREAD

**Issue by shashankkr** [Azure/azure-sdk-for-java#23198]
**Query/Question**
How to populate Service Bus Message Application properties (formerly user properties) using the JAVA 7.3.0 SDK? I can see that there is a ServiceBusMessage.getApplicationProperties method but no set method. 

**Setup (please complete the following information if applicable):**
 - OS: windows
 - IDE: VS Code
 - Library/Libraries: JAVA com.azure:azure-messaging-servicebus:7.3.0 ]
 
 **Information Checklist**
 Kindly make sure that you have added all the following information above and checkoff the required fields otherwise we will treat the issuer as an incomplete report
- [x] Query Added
- [x] Setup information Added

**Comment by alzimmermsft** [comment]
@ki1729 could you take a look at this?

**Comment by shashankkr** [comment]
Hi @ki1729 can you please help me. 

@alzimmermsft

**Comment by ki1729** [comment]
Hi @shashankkr, this is a great question! So I have been going through the AMQP spec and other tech spec documentation, but I can't seem to find why there is no Set method here. But it is the same across languages, so this is definitely a design choice and not a bug. 

I understand from your previous issue: [https://github.com/Azure/azure-sdk-for-js/issues/12861](https://github.com/Azure/azure-sdk-for-js/issues/12861) that you are trying to use user.properties which was replaced by the Application properties dictionary. So I am not sure why this is not currently settable. I am going to continue looking into this and see why this is the case.

**Comment by ki1729** [comment]
@shashankkr while I am looking into this, just in case you are blocked here, please use 

> ServiceBusMessage.getApplicationProperties.putAll(<your Map<String,Object> map>);

**Comment by shashankkr** [comment]
@ki1729 it seems like I am the only one using user properties in service bus :D

_But it is the same across languages, so this is definitely a design choice and not a bug._
In nodejs you have to set the props like this :
 const message = {
        body: content,
        sessionId: subscriberCode,
        subject: label,
        contentType: 'text/utf-8',
        **applicationProperties**: {
            deliveryType: 'email',
        }
    };
I am not sure about other languages but I believe you. 

Thanks for the solution, let me try that. And thanks a lot for your help.

**Comment by shashankkr** [comment]
@ki1729 Hi,
The solution did not work 
 Map<String,String> props = new HashMap<String,String>();
                        props.put("test", "value");
                        String json = new Gson().toJson(event);
                topicSender.sendMessage(new ServiceBusMessage(BinaryData.fromString(json))
                        .setSessionId(sfEvent.payload.Lead_Id__c)
                        .setSubject(sfEvent.payload.EventTriggerValue__c)
                        .getApplicationProperties().putAll(props));

Its giving the following error: 
![image](https://user-images.githubusercontent.com/244933/129268996-cf3580d2-8349-4904-adac-1917f724a43e.png)

**Comment by shashankkr** [comment]
@ki1729 Hi Kishore, any update on this? Thanks.

**Comment by ZejiaJiang** [comment]
@shashankkr Hi Shashank, I'm Zejia from Azure SDK team.

You can send message with your own info and get application properties by this way:
```Java
ServiceBusMessage message = new ServiceBusMessage(BinaryData.fromString(json))
            .setSessionId(sfEvent.payload.Lead_Id__c)
            .setSubject(sfEvent.payload.EventTriggerValue__c);
topicSender.sendMessage(message);

// build a receiver
Disposable subscription = receiver.receiveMessages().subscribe(msg -> {
                HashMap<String, Object> m = new HashMap<>();
                // put all application properties into a map
                msg.getApplicationProperties().putAll(m);
                System.out.println(msg.getRawAmqpMessage().getProperties().getContentType());
            },
            error -> {
                System.err.println("Error occurred while receiving message: " + error);
            },
            () -> System.out.println("Receiving complete."));
```

If you need the sessionId in your case, just use:
```Java
String sessionId = message.getSessionId();
```
get the subject is the same way.

Hope this can answer your question.
