### ISSUE TITLE
[QUERY] Stopping a virtual machine not working correctly

### ISSUE THREAD

**Issue by bri-b-dev** [Azure/azure-sdk-for-java#23214]
**Describe the bug**
I am trying to stop a running vm, which works. However the powerstate is not up-to-date. Still has state 'PowerState/running' and the vm (however stopped) is still 'stoppable' (even 15 minutes after stopping)
![vm](https://user-images.githubusercontent.com/68117322/127301426-04bd2932-6f96-473d-8baa-d9f6d1fb0f57.PNG)

***Exception or Stack Trace***
Here's the log:
`[onPool-worker-3] c.azure.identity.ClientSecretCredential  : Azure Identity => getToken() result for scopes [https://management.core.windows.net//.default]: SUCCESS
[onPool-worker-3] c.azure.identity.DefaultAzureCredential  : Azure Identity => Attempted credential EnvironmentCredential returns a token
[onPool-worker-3] c.a.c.implementation.AccessTokenCache    : Acquired a new access token.
[onPool-worker-3] c.a.r.r.i.S.list                         : --> GET https://management.azure.com/subscriptions?api-version=REDACTEDTry count: 1
[ctor-http-nio-3] c.a.r.r.i.S.list                         : <-- 200 https://management.azure.com/subscriptions?api-version=REDACTED (953 ms, 478-byte body)<-- END HTTP
[     parallel-1] c.a.r.c.i.D.createOrUpdate               : --> PUT https://management.azure.com/subscriptions/<SUBSCRIPTION>/resourceGroups/SDK/providers/Microsoft.Compute/disks/disk1?api-version=REDACTEDTry count: 1
[ctor-http-nio-3] c.a.r.c.i.D.createOrUpdate               : <-- 202 https://management.azure.com/subscriptions/<SUBSCRIPTION>/resourceGroups/SDK/providers/Microsoft.Compute/disks/disk1?api-version=REDACTED (1387 ms, 277-byte body)<-- END HTTP
[     parallel-2]                                          : --> GET https://management.azure.com/subscriptions/<SUBSCRIPTION>/providers/Microsoft.Compute/locations/westeurope/DiskOperations/a2b9d343-fa42-40cb-b26e-9ce93753744e?api-version=REDACTEDTry count: 1
[ctor-http-nio-3]                                          : <-- 200 https://management.azure.com/subscriptions/<SUBSCRIPTION>/providers/Microsoft.Compute/locations/westeurope/DiskOperations/a2b9d343-fa42-40cb-b26e-9ce93753744e?api-version=REDACTED (108 ms, 1065-byte body)<-- END HTTP
[ctor-http-nio-3]                                          : --> GET https://management.azure.com/subscriptions/<SUBSCRIPTION>/resourceGroups/SDK/providers/Microsoft.Compute/disks/disk1?api-version=REDACTEDTry count: 1
[ctor-http-nio-3]                                          : <-- 200 https://management.azure.com/subscriptions/<SUBSCRIPTION>/resourceGroups/SDK/providers/Microsoft.Compute/disks/disk1?api-version=REDACTED (337 ms, 841-byte body)<-- END HTTP
[           main] c.a.r.n.i.V.list                         : --> GET https://management.azure.com/subscriptions/<SUBSCRIPTION>/providers/Microsoft.Network/virtualNetworks?api-version=REDACTEDTry count: 1
[ctor-http-nio-3] c.a.r.n.i.V.list                         : <-- 200 https://management.azure.com/subscriptions/<SUBSCRIPTION>/providers/Microsoft.Network/virtualNetworks?api-version=REDACTED (148 ms, 66512-byte body)<-- END HTTP
[     parallel-3] c.a.r.n.i.N.createOrUpdate               : --> PUT https://management.azure.com/subscriptions/<SUBSCRIPTION>/resourceGroups/SDK/providers/Microsoft.Network/networkInterfaces/nic-test?api-version=REDACTEDTry count: 1
[ctor-http-nio-3] c.a.r.n.i.N.createOrUpdate               : <-- 201 https://management.azure.com/subscriptions/<SUBSCRIPTION>/resourceGroups/SDK/providers/Microsoft.Network/networkInterfaces/nic-test?api-version=REDACTED (1310 ms, 1657-byte body)<-- END HTTP
[     parallel-4] c.a.r.c.i.V.createOrUpdate               : --> PUT https://management.azure.com/subscriptions/<SUBSCRIPTION>/resourceGroups/SDK/providers/Microsoft.Compute/virtualMachines/test-vm?api-version=REDACTEDTry count: 1
[ctor-http-nio-3] c.a.r.c.i.V.createOrUpdate               : <-- 201 https://management.azure.com/subscriptions/<SUBSCRIPTION>/resourceGroups/SDK/providers/Microsoft.Compute/virtualMachines/test-vm?api-version=REDACTED (3410 ms, 2072-byte body)<-- END HTTP
[     parallel-5]                                          : --> GET https://management.azure.com/subscriptions/<SUBSCRIPTION>/providers/Microsoft.Compute/locations/westeurope/operations/c285333f-f9c8-45c3-b2a4-b93bfb308341?api-version=REDACTEDTry count: 1
[ctor-http-nio-3]                                          : <-- 200 https://management.azure.com/subscriptions/<SUBSCRIPTION>/providers/Microsoft.Compute/locations/westeurope/operations/c285333f-f9c8-45c3-b2a4-b93bfb308341?api-version=REDACTED (69 ms, 134-byte body)<-- END HTTP
[     parallel-6]                                          : --> GET https://management.azure.com/subscriptions/<SUBSCRIPTION>/providers/Microsoft.Compute/locations/westeurope/operations/c285333f-f9c8-45c3-b2a4-b93bfb308341?api-version=REDACTEDTry count: 1
[ctor-http-nio-3]                                          : <-- 200 https://management.azure.com/subscriptions/<SUBSCRIPTION>/providers/Microsoft.Compute/locations/westeurope/operations/c285333f-f9c8-45c3-b2a4-b93bfb308341?api-version=REDACTED (99 ms, 134-byte body)<-- END HTTP
[     parallel-7]                                          : --> GET https://management.azure.com/subscriptions/<SUBSCRIPTION>/providers/Microsoft.Compute/locations/westeurope/operations/c285333f-f9c8-45c3-b2a4-b93bfb308341?api-version=REDACTEDTry count: 1
[ctor-http-nio-3]                                          : <-- 200 https://management.azure.com/subscriptions/<SUBSCRIPTION>/providers/Microsoft.Compute/locations/westeurope/operations/c285333f-f9c8-45c3-b2a4-b93bfb308341?api-version=REDACTED (104 ms, 134-byte body)<-- END HTTP
[     parallel-8]                                          : --> GET https://management.azure.com/subscriptions/<SUBSCRIPTION>/providers/Microsoft.Compute/locations/westeurope/operations/c285333f-f9c8-45c3-b2a4-b93bfb308341?api-version=REDACTEDTry count: 1
[ctor-http-nio-3]                                          : <-- 200 https://management.azure.com/subscriptions/<SUBSCRIPTION>/providers/Microsoft.Compute/locations/westeurope/operations/c285333f-f9c8-45c3-b2a4-b93bfb308341?api-version=REDACTED (94 ms, 184-byte body)<-- END HTTP
[ctor-http-nio-3]                                          : --> GET https://management.azure.com/subscriptions/<SUBSCRIPTION>/resourceGroups/SDK/providers/Microsoft.Compute/virtualMachines/test-vm?api-version=REDACTEDTry count: 1
[ctor-http-nio-3]                                          : <-- 200 https://management.azure.com/subscriptions/<SUBSCRIPTION>/resourceGroups/SDK/providers/Microsoft.Compute/virtualMachines/test-vm?api-version=REDACTED (117 ms, 2318-byte body)<-- END HTTP
[           main] c.a.r.c.i.V.getByResourceGroup           : --> GET https://management.azure.com/subscriptions/<SUBSCRIPTION>/resourceGroups/SDK/providers/Microsoft.Compute/virtualMachines/test-vm?api-version=REDACTEDTry count: 1
[ctor-http-nio-3] c.a.r.c.i.V.getByResourceGroup           : <-- 200 https://management.azure.com/subscriptions/<SUBSCRIPTION>/resourceGroups/SDK/providers/Microsoft.Compute/virtualMachines/test-vm?api-version=REDACTED (89 ms, 2318-byte body)<-- END HTTP
[           main] c.a.r.c.i.V.getByResourceGroup           : --> GET https://management.azure.com/subscriptions/<SUBSCRIPTION>/resourceGroups/SDK/providers/Microsoft.Compute/virtualMachines/test-vm?$expand=REDACTED&api-version=REDACTEDTry count: 1
[ctor-http-nio-3] c.a.r.c.i.V.getByResourceGroup           : <-- 200 https://management.azure.com/subscriptions/<SUBSCRIPTION>/resourceGroups/SDK/providers/Microsoft.Compute/virtualMachines/test-vm?$expand=REDACTED&api-version=REDACTED (66 ms, 3850-byte body)<-- END HTTP
[           main] c.a.r.c.i.V.powerOff                     : --> POST https://management.azure.com/subscriptions/<SUBSCRIPTION>/resourceGroups/SDK/providers/Microsoft.Compute/virtualMachines/test-vm/powerOff?api-version=REDACTEDTry count: 1
[ctor-http-nio-3] c.a.r.c.i.V.powerOff                     : <-- 202 https://management.azure.com/subscriptions/<SUBSCRIPTION>/resourceGroups/SDK/providers/Microsoft.Compute/virtualMachines/test-vm/powerOff?api-version=REDACTED (453 ms, 0-byte body)<-- END HTTP
[ctor-http-nio-3] c.a.c.m.i.polling.PollOperation          : Ignoring decoding of null or empty value to:java.lang.Void
[     parallel-1]                                          : --> GET https://management.azure.com/subscriptions/<SUBSCRIPTION>/providers/Microsoft.Compute/locations/westeurope/operations/5dd4ce0d-c180-4bda-b247-c29795acbe6b?api-version=REDACTEDTry count: 1
[ctor-http-nio-3]                                          : <-- 200 https://management.azure.com/subscriptions/<SUBSCRIPTION>/providers/Microsoft.Compute/locations/westeurope/operations/5dd4ce0d-c180-4bda-b247-c29795acbe6b?api-version=REDACTED (78 ms, 184-byte body)<-- END HTTP
[ctor-http-nio-3]                                          : --> GET https://management.azure.com/subscriptions/<SUBSCRIPTION>/providers/Microsoft.Compute/locations/westeurope/operations/5dd4ce0d-c180-4bda-b247-c29795acbe6b?monitor=REDACTED&api-version=REDACTEDTry count: 1
[ctor-http-nio-3]                                          : <-- 200 https://management.azure.com/subscriptions/<SUBSCRIPTION>/providers/Microsoft.Compute/locations/westeurope/operations/5dd4ce0d-c180-4bda-b247-c29795acbe6b?monitor=REDACTED&api-version=REDACTED (152 ms, 0-byte body)<-- END HTTP
[           main] com.example.demo.DemoApplication         : PowerState/running`

**To Reproduce**
* create a virtual machine
* stop the vm by `vm.powerOff()`

***Code Snippet***
`
    @Override
    public void run(String... args) throws Exception {
        AzureResourceManager azure = getResourceManager();
        String vmId = createVM(azure);
        stopRunningVM(azure, vmId);
    }

    private String createVM(AzureResourceManager azure) {

        Disk dataDisk = azure.disks().define("disk1")
                .withRegion(REGION)
                .withExistingResourceGroup(RG_NAME)
                .withData()
                .withSizeInGB(1)
                .create();

        Optional<Network> network = azure.networks().list().stream().filter(n -> n.name().equalsIgnoreCase(VNET_NAME)).findFirst();
        if (network.isEmpty()) {
            throw new IllegalArgumentException("network not found");
        }

        Optional<String> subnet = network.get().subnets().keySet().stream().filter(s -> s.equalsIgnoreCase(SUBNET_NAME)).findFirst();
        if (subnet.isEmpty()) {
            throw new IllegalArgumentException("subnet not found");
        }
        NetworkInterface nic = azure.networkInterfaces().define("nic-test")
                .withRegion(REGION)
                .withExistingResourceGroup(RG_NAME)
                .withExistingPrimaryNetwork(network.get())
                .withSubnet(subnet.get())
                .withPrimaryPrivateIPAddressDynamic()
                .create();

        try {
            VirtualMachine virtualMachine = azure.virtualMachines().define("test-vm")
                    .withRegion(REGION)
                    .withExistingResourceGroup(RG_NAME)
                    .withExistingPrimaryNetworkInterface(nic)
                    .withPopularLinuxImage(KnownLinuxVirtualMachineImage.UBUNTU_SERVER_18_04_LTS)
                    .withRootUsername("sdk-admin")
                    .withRootPassword("Password.1")
                    .withExistingDataDisk(dataDisk)
                    .withSize(VirtualMachineSizeTypes.BASIC_A0)
                    .create();

            return virtualMachine.id();
        } catch (Exception e) {
            // clean up
            dataDisk.refresh();
            azure.disks().deleteById(dataDisk.id());
            azure.networkInterfaces().deleteById(nic.id());
            return "";
        }
    }

    private AzureResourceManager getResourceManager() {

        final AzureProfile profile = new AzureProfile(AzureEnvironment.AZURE);

        final TokenCredential credential = new DefaultAzureCredentialBuilder()
                .authorityHost(profile.getEnvironment().getActiveDirectoryEndpoint())
                .build();

        return AzureResourceManager
                .configure()
                .withLogLevel(HttpLogDetailLevel.BASIC)
                .authenticate(credential, profile)
                .withDefaultSubscription();

    }

    private void stopRunningVM(AzureResourceManager azure, String id) {
        VirtualMachine vm = azure.virtualMachines().getById(id);
        if (vm != null && PowerState.RUNNING.equals(vm.powerState())) {
            vm.powerOff();
        }
        LOG.info(vm.powerState().toString());
    }`

**Expected behavior**
Once `powerOff()` is being called, `powerState()` should return 'PowerState/stopped', in Azure Portal the 'Stop'-Button is disabled.

**Screenshots**

**Setup (please complete the following information):**
 - OS: Windows 10
 - IDE: IntelliJ
 - Library/Libraries: e.g. com.azure.resourcemanager:azure-resourcemanager:2.66.0 (groupId:artifactId:version)

**Additional context**

**Information Checklist**
Kindly make sure that you have added all the following information above and checkoff the required fields otherwise we will treat the issuer as an incomplete report
- [ ] Bug Description Added
- [ ] Repro Steps Added
- [ ] Setup information Added

**Comment by joshfree** [comment]
Hi @bri-b-dev someone from the `mgmt` team will follow up with you shortly.

/cc @yungezz

**Comment by weidongxu-microsoft** [comment]
@bri-b-dev You need to refresh the state of the `vm` object (call `vm.refreshInstanceView()` or `vm.refresh()`) before checking its `powerState()` after `powerOff()`.
Reason is that `powerOff()` only notify the service to stop VM, but not syncing the state. Hence the state of the `vm` object in your local and the virtual machine on remote need to be synced again.

What you see on the Portal might be a bug on UI, as it shows VM as stopped, but the Stop button is not greyed out. Is this intermittent or consistent?
