### ISSUE TITLE
Support Request Bodies Larger than 2GB in OkHttp HttpClient Implementation

### ISSUE THREAD

**Issue by alzimmermsft** [Azure/azure-sdk-for-java#23221]
Currently, the OkHttp based `HttpClient` implementation uses OkHttp's `ByteString` type for the request body. Unfortunately, this type is only capable of being 2GB in size, or that maximum size limit for a String or `byte[]`. Instead, the request handling should be converted to OkHttp's `Sink` concept which is akin to an `OutputStream`. Not only will this allow for requests larger than 2GB to happen, it should also help with heap as `ByteString` requires the whole body to be eagerly converted into a `byte[]` rather than streaming and writing the `HttpRequest.body`'s `ByteBuffer`s.

**Comment by kasobol-msft** [comment]
Related https://github.com/Azure/azure-sdk-for-java/issues/26782
