### ISSUE TITLE
java.lang.UnsupportedOperationException in com.azure.identity.implementation.IdentityClient#authenticateWithAzurePowerShell

### ISSUE THREAD

**Issue by mitsutaka-takeda** [Azure/azure-sdk-for-java#23237]
This line fails since Array does not support List#add method.

https://github.com/Azure/azure-sdk-for-java/blob/6eb6c81fd197da4d180c613adee6748cc4d117f0/sdk/identity/azure-identity/src/main/java/com/azure/identity/implementation/IdentityClient.java#L499

**Comment by alzimmermsft** [comment]
Thank you for reporting this issue @mitsutaka-takeda. @g2vinay could you take a look at this.
