### ISSUE TITLE
Blob - metadata key name auto converted to small case

### ISSUE THREAD

**Issue by abhikt48** [Azure/azure-sdk-for-java#23242]
We are using `azure-storage-blob-12.10.2` to upload blobs.  We are adding metadata in Capital case but name is getting stored in smaller case.  As per [docs ](https://docs.microsoft.com/en-us/rest/api/storageservices/naming-and-referencing-containers--blobs--and-metadata#metadata-names) , names are case-insensitive. Not sure if name will auto convert to smaller case or not.

**Sample Code**
```
BlobClient blobClient = getBlobContainerClient("abhi-test-2").getBlobClient(blobName);
 Map<String, String> metadata = new HashMap<>();
 metadata.put("Name", "Abhi");
        
 blobClient.uploadWithResponse(new ByteArrayInputStream(TEST_MESSAGE.getBytes()), TEST_MESSAGE.length(), null, null, metadata, null, null, null, Context.NONE);
```

**Uploaded Metadata**
![image](https://user-images.githubusercontent.com/22897837/127526382-83eadbbb-337e-4ec0-8f1e-c6f64e06924b.png)

Is this expected behaviour? Could you please confirm.

**Setup (please complete the following information if applicable):**
OS: window
IDE : eclipse
Version of the Library used: `azure-storage-blob-12.10.2`

**Comment by joshfree** [comment]
@rickle-msft could you please assist @abhikt48 with their question?

**Comment by rickle-msft** [comment]
Hi, @abhikt48. Acknowledging this issue. I'll look into the expected behavior and probably get back to you sometime on Monday.

**Comment by rickle-msft** [comment]
@abhikt48 I have not been able to reproduce the behavior you are seeing. I am using the same upload method with a capitalized metadata key and I see that the case is preserved.

**Comment by abhikt48** [comment]
@rachel-msft  - It's strange...  Java and azure storage explorer behaving same (auto converted to small case) in my system..

I will try to create video/gif and share with you..

**Comment by chenrujun** [comment]
Hi, @joshfree , could you please set assignee if you want someone to handle the issue?

**Comment by abhikt48** [comment]
Hi @rickle-msft  Please find below gif and let me know for any other input.

![Metadata_AutoConvert_SmallerCase](https://user-images.githubusercontent.com/22897837/128510339-09af2624-307e-49c0-9259-3493dba73d81.gif)

**Comment by rickle-msft** [comment]
@abhikt48 That looks like it's StorageExplore that is converting to lower case. I suggest reaching out to that team if you have concerns around that behavior.
