### ISSUE TITLE
This page is about deprecated feature

### ISSUE THREAD

**Issue by vgarmash** [Azure/azure-sdk-for-java#23269]
Please update the article with references to the current recommended approach as the use of filter is deprecated: https://github.com/Azure/azure-sdk-for-java/issues/17860

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9604e4ff-2089-62c8-b536-1a68a8adefb7
* Version Independent ID: 559ac40e-7c66-bd5d-b36d-b7c498aa1194
* Content: [Azure AD Spring Boot Starter client library for Java](https://docs.microsoft.com/en-us/java/api/overview/azure/active-directory-spring-boot-starter-readme?view=azure-java-stable)
* Content Source: [docs-ref-services/latest/active-directory-spring-boot-starter-readme.md](https://github.com/Azure/azure-docs-sdk-java/blob/master/docs-ref-services/latest/active-directory-spring-boot-starter-readme.md)
* Service: **azureactivedirectory**
* Product: **azure**
* Technology: **azure**
* GitHub Login: @maggiepint
* Microsoft Alias: **magpint**

**Comment by joshfree** [comment]
@chenrujun could you please take a look?

**Comment by chenrujun** [comment]
Hi, @scbedd, could you please help to delete these contents, and not sync them again from this repo to doc repo again?

Related link: https://github.com/Azure/azure-docs-sdk-java/pull/2067#discussion_r671422787

**Comment by scbedd** [comment]
This is...odd. I'll follow up. Thanks for the heads up @chenrujun

**Comment by yiliuTo** [comment]
Hey @scbedd , any updates? I also meet the simaliar issue: the deleted doc of [Azure Event Hubs Spring Cloud Stream Binder client library for Java | Microsoft Docs ](https://docs.microsoft.com/en-us/java/api/overview/azure/spring-cloud-stream-binder-eventhubs-readme?view=azure-java-stable) can be searched

**Comment by scbedd** [comment]
@yiliuTo I got pre-occupied with other stuff. You should be clean when we release tomorrow.

**Comment by yiliuTo** [comment]
@scbedd Thanks for helping on this! 
Besides, I found the exclusions don't cover the starter libraries, not sure if those should be added as well, or there has been other exclusion behavior already. And in case you need to add them in the exclusions, the starter librabries are:

> azure-spring-boot-starter-active-directory
> azure-spring-boot-starter-active-directory-b2c
> azure-spring-boot-starter-cosmos
> azure-spring-boot-starter-keyvault-secrets
> azure-spring-boot-starter-servicebus-jms
> azure-spring-boot-starter-storage
> azure-spring-cloud-starter-eventhubs
> azure-spring-cloud-starter-eventhubs-kafka
> azure-spring-cloud-starter-servicebus
> azure-spring-cloud-starter-storage-queue

**Comment by scbedd** [comment]
Confirming those are gone [here is the packages.json](https://github.com/Azure/azure-docs-sdk-java/blob/main/package.json)

**Comment by chenrujun** [comment]
@scbedd . Thank you.

**Comment by scbedd** [comment]
All the pages are gone now, but I don't think we cleaned out the readmes. I'll do another PR to clean _those_ out and have this closed by the time you come for your next workday.

**Comment by chenrujun** [comment]
Hi, @scbedd .

Now I can still access this page: https://docs.microsoft.com/en-us/java/api/overview/azure/active-directory-spring-boot-starter-readme?view=azure-java-stable

Could you please help to check?

**Comment by scbedd** [comment]
😡 😡 😡 😡 😡 😡 😡 😡 😡 😡 

on it.

**Comment by scbedd** [comment]
@chenrujun this should be definitively closed now.

**Comment by chenrujun** [comment]
@scbedd . Thank you.
