### ISSUE TITLE
[BUG][identity] Caused by: java.net.SocketException: Network is unreachable: connect

### ISSUE THREAD

**Issue by andxu** [Azure/azure-sdk-for-java#23260]
**Describe the bug**
Azure toolkit user reporting Spring boot application using azure-identity error :
Caused by: com.azure.identity.CredentialUnavailableException: ManagedIdentityCredential authentication unavailable. Connection to IMDS endpoint cannot be established, Network is unreachable: connect.
at com.azure.identity.implementation.IdentityClient.lambda$checkIMDSAvailable$50(IdentityClient.java:1208)
at reactor.core.publisher.MonoCallable.call(MonoCallable.java:91)
at reactor.core.publisher.FluxFlatMap.trySubscribeScalarMap(FluxFlatMap.java:127)
... 57 more
Caused by: java.net.SocketException: Network is unreachable: connect
at java.base/java.net.PlainSocketImpl.waitForConnect(Native Method)
at java.base/java.net.PlainSocketImpl.socketConnect(PlainSocketImpl.java:107)
at java.base/java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:399)
***Exception or Stack Trace***
> #### Setup
> IntelliJ build version: 2021.1.3 IC-211.7628.21
> OS: Windows 10
> JDK: JetBrains s.r.o. 11.0.11
> Plugin version: 3.54.0-2021.1
> 
> Unable to run the application.
> Signed my device with the Azure toolkit.
> 
> Using:
> 
> org.springframework.boot
> spring-boot-starter-parent
> 2.5.2
> 
> 
> <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
> <java.version>11</java.version>
> <azure.version>3.6.1</azure.version>
> 1.3.6
> <kotlin.version>1.5.21</kotlin.version>
> <kotlin.compiler.jvmTarget>11</kotlin.compiler.jvmTarget>
> <kotlin.compiler.incremental>true</kotlin.compiler.incremental>
> 
> 
> 
> com.microsoft.azure
> applicationinsights-spring-boot-starter
> 2.6.3
> 
> 
> com.microsoft.azure
> azure-spring-boot-metrics-starter
> 2.3.5
> 
> 
> com.microsoft.azure
> applicationinsights-logging-logback
> 2.6.3
> 
> 
> com.azure.spring
> azure-spring-boot-starter
> 
> 
> com.azure.spring
> azure-spring-boot-starter-keyvault-secrets
> 
> com.azure.spring azure-spring-boot-bom ${azure.version} pom import
> Exception:
> java.lang.IllegalStateException: Failed to configure KeyVault property source
> at com.microsoft.azure.keyvault.spring.KeyVaultEnvironmentPostProcessorHelper.addKeyVaultPropertySource(KeyVaultEnvironmentPostProcessorHelper.java:110)
> at com.microsoft.azure.keyvault.spring.KeyVaultEnvironmentPostProcessor.postProcessEnvironment(KeyVaultEnvironmentPostProcessor.java:47)
> at org.springframework.boot.env.EnvironmentPostProcessorApplicationListener.onApplicationEnvironmentPreparedEvent(EnvironmentPostProcessorApplicationListener.java:102)
> at org.springframework.boot.env.EnvironmentPostProcessorApplicationListener.onApplicationEvent(EnvironmentPostProcessorApplicationListener.java:87)
> at org.springframework.context.event.SimpleApplicationEventMulticaster.doInvokeListener(SimpleApplicationEventMulticaster.java:176)
> at org.springframework.context.event.SimpleApplicationEventMulticaster.invokeListener(SimpleApplicationEventMulticaster.java:169)
> at org.springframework.context.event.SimpleApplicationEventMulticaster.multicastEvent(SimpleApplicationEventMulticaster.java:143)
> at org.springframework.context.event.SimpleApplicationEventMulticaster.multicastEvent(SimpleApplicationEventMulticaster.java:131)
> at org.springframework.boot.context.event.EventPublishingRunListener.environmentPrepared(EventPublishingRunListener.java:82)
> at org.springframework.boot.SpringApplicationRunListeners.lambda$environmentPrepared$2(SpringApplicationRunListeners.java:63)
> at java.base/java.util.ArrayList.forEach(ArrayList.java:1540)
> at org.springframework.boot.SpringApplicationRunListeners.doWithListeners(SpringApplicationRunListeners.java:117)
> at org.springframework.boot.SpringApplicationRunListeners.doWithListeners(SpringApplicationRunListeners.java:111)
> at org.springframework.boot.SpringApplicationRunListeners.environmentPrepared(SpringApplicationRunListeners.java:62)
> at org.springframework.boot.SpringApplication.prepareEnvironment(SpringApplication.java:374)
> at org.springframework.boot.SpringApplication.run(SpringApplication.java:332)
> at com.contguard.mesher.MesherApplication.main(MesherApplication.java:39)
> Caused by: java.lang.RuntimeException: Max retries 3 times exceeded. Error Details: ManagedIdentityCredential authentication unavailable. Connection to IMDS endpoint cannot be established, Network is unreachable: connect.
> at com.azure.core.http.policy.RetryPolicy.lambda$attemptAsync$1(RetryPolicy.java:127)
> at reactor.core.publisher.FluxOnErrorResume$ResumeSubscriber.onError(FluxOnErrorResume.java:94)
> at reactor.core.publisher.MonoFlatMap$FlatMapMain.onError(MonoFlatMap.java:172)
> at reactor.core.publisher.MonoFlatMap$FlatMapMain.onError(MonoFlatMap.java:172)
> at reactor.core.publisher.MonoFlatMap$FlatMapMain.secondError(MonoFlatMap.java:192)
> at reactor.core.publisher.MonoFlatMap$FlatMapInner.onError(MonoFlatMap.java:259)
> at reactor.core.publisher.MonoPeekTerminal$MonoTerminalPeekSubscriber.onError(MonoPeekTerminal.java:258)
> at reactor.core.publisher.MonoPeekTerminal$MonoTerminalPeekSubscriber.onError(MonoPeekTerminal.java:258)
> at reactor.core.publisher.FluxPeekFuseable$PeekFuseableConditionalSubscriber.onError(FluxPeekFuseable.java:553)
> at reactor.core.publisher.FluxPeekFuseable$PeekFuseableConditionalSubscriber.onError(FluxPeekFuseable.java:553)
> at reactor.core.publisher.MonoPeekTerminal$MonoTerminalPeekSubscriber.onError(MonoPeekTerminal.java:258)
> at reactor.core.publisher.FluxPeekFuseable$PeekFuseableConditionalSubscriber.onError(FluxPeekFuseable.java:553)
> at reactor.core.publisher.MonoPeekTerminal$MonoTerminalPeekSubscriber.onError(MonoPeekTerminal.java:258)
> at reactor.core.publisher.Operators.error(Operators.java:197)
> at reactor.core.publisher.FluxFlatMap.trySubscribeScalarMap(FluxFlatMap.java:135)
> at reactor.core.publisher.MonoFlatMap.subscribeOrReturn(MonoFlatMap.java:53)
> at reactor.core.publisher.InternalMonoOperator.subscribe(InternalMonoOperator.java:57)
> at reactor.core.publisher.MonoDefer.subscribe(MonoDefer.java:52)
> at reactor.core.publisher.MonoFlatMap$FlatMapMain.onNext(MonoFlatMap.java:157)
> at reactor.core.publisher.FluxMap$MapSubscriber.onNext(FluxMap.java:120)
> at reactor.core.publisher.FluxMap$MapSubscriber.onNext(FluxMap.java:120)
> at reactor.core.publisher.FluxPeek$PeekSubscriber.onNext(FluxPeek.java:199)
> at reactor.core.publisher.SerializedSubscriber.onNext(SerializedSubscriber.java:99)
> at reactor.core.publisher.FluxRetryWhen$RetryWhenMainSubscriber.onNext(FluxRetryWhen.java:173)
> at reactor.core.publisher.FluxOnErrorResume$ResumeSubscriber.onNext(FluxOnErrorResume.java:79)
> at reactor.core.publisher.Operators$MonoInnerProducerBase.complete(Operators.java:2663)
> at reactor.core.publisher.MonoSingle$SingleSubscriber.onComplete(MonoSingle.java:180)
> at reactor.core.publisher.MonoFlatMapMany$FlatMapManyInner.onComplete(MonoFlatMapMany.java:260)
> at reactor.core.publisher.FluxMapFuseable$MapFuseableSubscriber.onComplete(FluxMapFuseable.java:150)
> at reactor.core.publisher.FluxMapFuseable$MapFuseableSubscriber.onComplete(FluxMapFuseable.java:150)
> at reactor.core.publisher.Operators$MonoSubscriber.complete(Operators.java:1816)
> at reactor.core.publisher.MonoCollect$CollectSubscriber.onComplete(MonoCollect.java:159)
> at reactor.core.publisher.FluxDoFinally$DoFinallySubscriber.onComplete(FluxDoFinally.java:145)
> at reactor.core.publisher.FluxHandle$HandleSubscriber.onComplete(FluxHandle.java:212)
> at reactor.core.publisher.FluxMap$MapConditionalSubscriber.onComplete(FluxMap.java:269)
> at reactor.netty.channel.FluxReceive.onInboundComplete(FluxReceive.java:401)
> at reactor.netty.channel.ChannelOperations.onInboundComplete(ChannelOperations.java:420)
> at reactor.netty.channel.ChannelOperations.terminate(ChannelOperations.java:474)
> at reactor.netty.http.client.HttpClientOperations.onInboundNext(HttpClientOperations.java:685)
> at reactor.netty.channel.ChannelOperationsHandler.channelRead(ChannelOperationsHandler.java:94)
> at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
> at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
> at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
> at io.netty.channel.CombinedChannelDuplexHandler$DelegatingChannelHandlerContext.fireChannelRead(CombinedChannelDuplexHandler.java:436)
> at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:324)
> at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:296)
> at io.netty.channel.CombinedChannelDuplexHandler.channelRead(CombinedChannelDuplexHandler.java:251)
> at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
> at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
> at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
> at io.netty.handler.ssl.SslHandler.unwrap(SslHandler.java:1368)
> at io.netty.handler.ssl.SslHandler.decodeNonJdkCompatible(SslHandler.java:1245)
> at io.netty.handler.ssl.SslHandler.decode(SslHandler.java:1282)
> at io.netty.handler.codec.ByteToMessageDecoder.decodeRemovalReentryProtection(ByteToMessageDecoder.java:507)
> at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:446)
> at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:276)
> at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
> at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
> at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
> at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410)
> at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
> at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
> at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919)
> at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:166)
> at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:719)
> at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:655)
> at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:581)
> at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:493)
> at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989)
> at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
> at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
> at java.base/java.lang.Thread.run(Thread.java:834)
> Suppressed: java.lang.Exception: #block terminated with an error
> at reactor.core.publisher.BlockingSingleSubscriber.blockingGet(BlockingSingleSubscriber.java:99)
> at reactor.core.publisher.Flux.blockLast(Flux.java:2519)
> at com.azure.core.util.paging.ContinuablePagedByIteratorBase.requestPage(ContinuablePagedByIteratorBase.java:94)
> at com.azure.core.util.paging.ContinuablePagedByPageIterable$ContinuablePagedByPageIterator.(ContinuablePagedByPageIterable.java:49)
> at com.azure.core.util.paging.ContinuablePagedByPageIterable.iterator(ContinuablePagedByPageIterable.java:37)
> at java.base/java.lang.Iterable.spliterator(Iterable.java:101)
> at com.microsoft.azure.keyvault.spring.KeyVaultOperation.lambda$refreshProperties$2(KeyVaultOperation.java:125)
> at java.base/java.util.Optional.map(Optional.java:265)
> at com.microsoft.azure.keyvault.spring.KeyVaultOperation.refreshProperties(KeyVaultOperation.java:125)
> at com.microsoft.azure.keyvault.spring.KeyVaultOperation.(KeyVaultOperation.java:73)
> at com.microsoft.azure.keyvault.spring.KeyVaultEnvironmentPostProcessorHelper.addKeyVaultPropertySource(KeyVaultEnvironmentPostProcessorHelper.java:90)
> at com.microsoft.azure.keyvault.spring.KeyVaultEnvironmentPostProcessor.postProcessEnvironment(KeyVaultEnvironmentPostProcessor.java:47)
> at org.springframework.boot.env.EnvironmentPostProcessorApplicationListener.onApplicationEnvironmentPreparedEvent(EnvironmentPostProcessorApplicationListener.java:102)
> at org.springframework.boot.env.EnvironmentPostProcessorApplicationListener.onApplicationEvent(EnvironmentPostProcessorApplicationListener.java:87)
> at org.springframework.context.event.SimpleApplicationEventMulticaster.doInvokeListener(SimpleApplicationEventMulticaster.java:176)
> at org.springframework.context.event.SimpleApplicationEventMulticaster.invokeListener(SimpleApplicationEventMulticaster.java:169)
> at org.springframework.context.event.SimpleApplicationEventMulticaster.multicastEvent(SimpleApplicationEventMulticaster.java:143)
> at org.springframework.context.event.SimpleApplicationEventMulticaster.multicastEvent(SimpleApplicationEventMulticaster.java:131)
> at org.springframework.boot.context.event.EventPublishingRunListener.environmentPrepared(EventPublishingRunListener.java:82)
> at org.springframework.boot.SpringApplicationRunListeners.lambda$environmentPrepared$2(SpringApplicationRunListeners.java:63)
> at java.base/java.util.ArrayList.forEach(ArrayList.java:1540)
> at org.springframework.boot.SpringApplicationRunListeners.doWithListeners(SpringApplicationRunListeners.java:117)
> at org.springframework.boot.SpringApplicationRunListeners.doWithListeners(SpringApplicationRunListeners.java:111)
> at org.springframework.boot.SpringApplicationRunListeners.environmentPrepared(SpringApplicationRunListeners.java:62)
> at org.springframework.boot.SpringApplication.prepareEnvironment(SpringApplication.java:374)
> at org.springframework.boot.SpringApplication.run(SpringApplication.java:332)
> at com.contguard.mesher.MesherApplication.main(MesherApplication.java:39)
> Caused by: com.azure.identity.CredentialUnavailableException: ManagedIdentityCredential authentication unavailable. Connection to IMDS endpoint cannot be established, Network is unreachable: connect.
> at com.azure.identity.implementation.IdentityClient.lambda$checkIMDSAvailable$50(IdentityClient.java:1208)
> at reactor.core.publisher.MonoCallable.call(MonoCallable.java:91)
> at reactor.core.publisher.FluxFlatMap.trySubscribeScalarMap(FluxFlatMap.java:127)
> ... 57 more
> Caused by: java.net.SocketException: Network is unreachable: connect
> at java.base/java.net.PlainSocketImpl.waitForConnect(Native Method)
> at java.base/java.net.PlainSocketImpl.socketConnect(PlainSocketImpl.java:107)
> at java.base/java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:399)
> at java.base/java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:242)
> at java.base/java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:224)
> at java.base/java.net.Socket.connect(Socket.java:591)
> at java.base/sun.net.NetworkClient.doConnect(NetworkClient.java:177)
> at java.base/sun.net.www.http.HttpClient.openServer(HttpClient.java:474)
> at java.base/sun.net.www.http.HttpClient.openServer(HttpClient.java:569)
> at java.base/sun.net.www.http.HttpClient.(HttpClient.java:242)
> at java.base/sun.net.www.http.HttpClient.New(HttpClient.java:341)
> at java.base/sun.net.www.http.HttpClient.New(HttpClient.java:362)
> at java.base/sun.net.www.protocol.http.HttpURLConnection.getNewHttpClient(HttpURLConnection.java:1248)
> at java.base/sun.net.www.protocol.http.HttpURLConnection.plainConnect0(HttpURLConnection.java:1187)
> at java.base/sun.net.www.protocol.http.HttpURLConnection.plainConnect(HttpURLConnection.java:1081)
> at java.base/sun.net.www.protocol.http.HttpURLConnection.connect(HttpURLConnection.java:1015)
> at com.azure.identity.implementation.IdentityClient.lambda$checkIMDSAvailable$50(IdentityClient.java:1202)
> ... 59 more
> 
> Process finished with exit code 0

**To Reproduce**
Please contact the original user @SarShalomSimchi for how to reproduce

***Code Snippet***
Add the code snippet that causes the issue.

**Expected behavior**
the sign in progress should sign without error.

**Comment by g2vinay** [comment]
@andxu 
Thank you for reporting this.
Managed Identity Credential works only in Azure Hosted Environments where Managed Identity is manually enabled on the azure resource and not in local developer environments.
Assuming the Azure Toolkit user is running on the Local Dev environment of the user, Managed Identity credential won't work.

@SarShalomSimchi, are you using the Managed Identity credential on your dev machine ?

**Comment by SarShalomSimchi** [comment]
@andxu, I don't if I'm using the Managed Identity credential on your dev machine, but the problem was solved when I've added my I.P in keyvault + tenant-id in application.properties

**Comment by g2vinay** [comment]
Closing this issue, as it was resolved.
