### ISSUE TITLE
[FEATURE REQ] azure-analytics-synapse-artifacts - additional columns for CopySource

### ISSUE THREAD

**Issue by vietanh85** [Azure/azure-sdk-for-java#23278]
**Is your feature request related to a problem? Please describe.**
There is no way to add the additionalColumns to the CopySource using sdk (we can do it using UI)

**Describe the solution you'd like**
Add the additionalColumns to CopySource so we can programmatically add the additionalColumns to source.

**Information Checklist**
Kindly make sure that you have added all the following information above and checkoff the required fields otherwise we will treat the issuer as an incomplete report
- [ x ] Description Added
- [ x ] Expected solution specified

**Comment by joshfree** [comment]
@jianghaolu can you please help route this?

**Comment by joshfree** [comment]
Closing old issue previously resolved.
