### ISSUE TITLE
[Storage] Server failed to response storage requests against China cloud and UsGov

### ISSUE THREAD

**Issue by hongli750210** [Azure/azure-sdk-for-java#23288]
We are running live Tests against other clouds like US Gov and Azure China Cloud. The goal is to check whether new azure sdk package work with other clouds or not.

**Error Description:**
The test about storage service the request failed. The Error Message as follow:

![image](https://user-images.githubusercontent.com/74638143/127793757-735cc392-784c-43f4-baea-f555d7d50205.png)

**Error Track:**
Detail: [Code Link](https://github.com/Azure/azure-sdk-for-java/blob/main/sdk/storage/test-resources.json#L8)
![image](https://user-images.githubusercontent.com/74638143/127793684-118ee733-4133-4157-bd66-e7ec6ddc6a4c.png)

The exception above throws by Method APISpec_setup.

**Expected Behavior**
We want to get the `endpointSuffix` of the Storage service  or a tag value for setting `endpointSuffix` from different cloud. 

@scottaddie , @joshfree , @kyle-patterson , @tg-msft, @alzimmermsft and @jongio for notification.

**Comment by alzimmermsft** [comment]
Thanks for submitting this issue @hongli750210. Is this a request to have the live testing resource deployment support other endpoint suffixes?

**Comment by hongli750210** [comment]
Yes, I think so. the endpoint suffix of UsGov is ‘core.usgovcloudapi.net’, and that of China Cloud is ‘core.chinacloudapi.cn’ .

**Comment by alzimmermsft** [comment]
@benbp it looks like you are already assisting on this, so I'm assigning you

**Comment by benbp** [comment]
@alzimmermsft this needs to be fixed via updating hardcoded endpoints in the test code and/or updating suffix usage in the test-resources.json arm template. This should be assigned to someone on the java team.

**Comment by alzimmermsft** [comment]
@kasobol-msft, @rickle-msft, do you know where in the test resource deployment/test code this is being leveraged?

**Comment by benbp** [comment]
@hongli750210 @v-xuto if you change the `endpointSuffix` ARM template parameter to `storageEndpointSuffix` the tests should target the sovereign cloud without any code changes (though there may need to be code changes in the event the tests don't work). Can one of you own this or does the java/storage team need to?

**Comment by hongli750210** [comment]
@benbp After I tried to change the endpointSuffix ARM template parameter to storageEndpointSuffix, the error described in the issue no reproduced in UsGov and China Cloud.
