### ISSUE TITLE
TableEntity no subclasses?

### ISSUE THREAD

**Issue by Marina132000ae** [Azure/azure-sdk-for-java#23308]
The documentation is still referencing the ability to extend TableEntity. Should we assume moving forward that will be removed or is it possible that the ability will be added back in?

**Comment by vcolin7** [comment]
Hi @Marina132000ae. For the time being, subclassing `TableEntity` is not supported, however, this doesn't necessarily mean it won't be supported in the future.

Thanks a lot for pointing this out. I will correct the documentation you mention to reflect the actual behavior of the SDK. Would you mind adding a link to where you saw this?

**Comment by Marina132000ae** [comment]
I was talking about the javadoc ([specifically this line](https://github.com/Azure/azure-sdk-for-java/blob/099c78c52dd6b161551d7a025a57b9bd885dd9dc/sdk/tables/azure-data-tables/src/main/java/com/azure/data/tables/models/TableEntity.java#L25)). It's also here: https://docs.microsoft.com/en-us/java/api/com.azure.data.tables.models.tableentity?view=azure-java-stable, but I'm guessing that's built off the javadoc. Thanks, @vcolin7!

**Comment by vcolin7** [comment]
You're correct, this is built off the JavaDoc, so I will correct it to remove the mention to subclassing. Thanks!
