### ISSUE TITLE
[BUG] azure-spring-boot-starter-storage changes default actuator behavior and reveals sensitive details

### ISSUE THREAD

**Issue by dschadow** [Azure/azure-sdk-for-java#23305]
Hi,

By default, the health endpoint for Spring Actuator (spring-boot-starter-actuator) at /actuator/health shows only `"status":"UP"` (or DOWN) when called anonymously. After adding azure-spring-boot-starter-storage as a dependency, this changes and starts to show sensitive information including database and other components. This has to be turned off explicitly via application.yml/properties: `management:endpoint:health:show-components: never`. In my eyes, this conflicts with Springs 'secure by default' and unnecessarily reveals sensitive information. The default should be the other way, the endpoint should continue to show only UP or DOWN, details should be explicitly turned on by configuration.

***Code Snippet***
Create a simple Spring Boot project (used 2.5.3) with web and actuator dependencies. Add azure-spring-boot-starter-storage, launch the application and open the /actuator/health endpoint.

pom.xml snippet:
```
<dependencies>
<dependency>
	<groupId>org.springframework.boot</groupId>
	<artifactId>spring-boot-starter-actuator</artifactId>
</dependency>
<dependency>
	<groupId>org.springframework.boot</groupId>
	<artifactId>spring-boot-starter-web</artifactId>
</dependency>
<dependency>
  	<groupId>com.azure.spring</groupId>
  	<artifactId>azure-spring-boot-starter-storage</artifactId>
  	<version>3.7.0</version>
</dependency>
</dependencies>
```

**Expected behavior**
Anonymous health endpoint behavior doesn't change and shows only UP or DOWN as STATUS. 

**Screenshots**

**Without dependency:**
<img width="570" alt="without_dependency" src="https://user-images.githubusercontent.com/787626/127915558-86354ae4-7c7d-482e-bb58-8b8a3df57275.png">

**With dependency:**
<img width="570" alt="with_dependency" src="https://user-images.githubusercontent.com/787626/127915551-2b81c636-790b-4a9b-8577-cda7d404a657.png">

**Comment by chenrujun** [comment]
Hi, @ZhuXiaoBing-cn , could you please take a look?

**Comment by backwind1233** [comment]
@dschadow Thanks for reaching us, I'm following and will keep you informed if there are any conclusions.

**Comment by backwind1233** [comment]
Hi @dschadow, thanks for your feedback, we have add it to backlog and will fix it soon.

**Comment by ZhuXiaoBing-cn** [comment]
Hi @dschadow, currently this bug has been fixed, please wait for our next release.
