### ISSUE TITLE
[FEATURE REQ] Enhance Security In Spring Integration for Event Hub and Service Bus

### ISSUE THREAD

**Issue by chenrujun** [Azure/azure-sdk-for-java#23323]
### Context

Spring Integration has Spring Security integrated, more details can be found from [Spring Integration Doc](https://docs.spring.io/spring-integration/docs/current/reference/html/security.html)

Spring Integation for EventHubs and Spring Integration for Service Bus should have the security functionality support, specifically

* [Secure Chanels](https://docs.spring.io/spring-integration/docs/current/reference/html/security.html#securing-channels)
* [Security Context Propagation](https://docs.spring.io/spring-integration/docs/current/reference/html/security.html#security-context-propagation)

This [stackoverflow question](https://stackoverflow.com/questions/67585252/spring-security-for-spring-cloud-stream-with-rabbitmq-as-binder) asked to share user context between message producer to message consumer

**Comment by stliu** [comment]
this should be implemented in the integration level
