### ISSUE TITLE
[FEATURE REQ] Add option to avoid first GetBlobProperties request for InputStream

### ISSUE THREAD

**Issue by AndrewOrr** [Azure/azure-sdk-for-java#23326]
**Is your feature request related to a problem? Please describe.**
Include an option to not call GetBlobProperties when creating a blob input stream. If we can guarantee the container/blob is static it would be great to avoid this extra call. 

**Describe the solution you'd like**
Add an option in BlobInputStreamOptions to avoid the GetBlobProperties call in BlobClientBase.openInputStream.

**Describe alternatives you've considered**

**Additional context**

**Information Checklist**
Kindly make sure that you have added all the following information above and checkoff the required fields otherwise we will treat the issuer as an incomplete report
- [x ] Description Added
- [x ] Expected solution specified

**Comment by alzimmermsft** [comment]
@rickle-msft, @kasobol-msft FYI

Related: https://github.com/Azure/azure-sdk-for-java/issues/4527

**Comment by rickle-msft** [comment]
@AndrewOrr Thanks for this request. We'll take a look at refactoring it out.
