### ISSUE TITLE
org.springframework.security.oauth2.core.OAuth2AuthenticationException: [invalid_redirect_uri_parameter] when application behind AppService

### ISSUE THREAD

**Issue by GuillaumeVerdon** [Azure/azure-sdk-for-java#23324]
**Is your feature request related to a problem? Please describe.**
My springboot application is deployed in a container in Azure App Service. The TLS part is managed by the app service itself. My application is therefore listening HTTP traffic (not HTTPS).

My application uses the SDK for authentication through Azure AD. The issue is that the SDK is redirecting users to the login endpoint at Microsoft with a HTTP redirect-uri as the service listen on http. But Azure only allow http redirect-uri for localhost and not for production services. 

**Describe the solution you'd like**
A property should allow me to force the protocol used when generating the redirect-uri.

**Describe alternatives you've considered**
Not a lot of idea how to fix that

**Additional context**
App run in container, container listen HTTP traffic on port 8080, Azure App Service wrap the container and only accept HTTPS traffic (it does the TLS termination), SDK generates http:// redirect-uri

**Information Checklist**
Kindly make sure that you have added all the following information above and checkoff the required fields otherwise we will treat the issuer as an incomplete report
- [x] Description Added
- [x] Expected solution specified

**Comment by GuillaumeVerdon** [comment]
I was able to override the default behavior by adding a file `aad-oauth2-common.properties` in my classpath which will override the file present in `azure-sping-boot@2.0.6`

However, now my application is throwing `org.springframework.security.oauth2.core.OAuth2AuthenticationException: [invalid_redirect_uri_parameter]` because when receiving the `authorization_code` (after the redirection to the redirect uri), Spring is checking the `HttpServletRequest` against the configured redirect uri (this happens in `OidcAuthorizationCodeAuthenticationProvider` class of `spring-security-oauth2-client@5.0.9.RELEASE`).

Does anyone faced the same issue ? Is there an easy way to workaround this ?

**Comment by joshfree** [comment]
@saragluna @backwind1233 could you please follow up with @GuillaumeVerdon?

**Comment by chenrujun** [comment]
Hi, @GuillaumeVerdon .

Thanks for reaching out.
Could you please share your `pom.xml`?

**Comment by chenrujun** [comment]
Hi, @GuillaumeVerdon,

Thank you for your detailed description.

1. Please set `spring.security.oauth2.client.registration.azure.redirect-uri=http://HOSTNAME/login/oauth2/code/azure` in your `application.properties`, and add breakpoint in [OidcAuthorizationCodeAuthenticationProvider](https://github.com/spring-projects/spring-security/blob/5.0.9.RELEASE/oauth2/oauth2-client/src/main/java/org/springframework/security/oauth2/client/oidc/authentication/OidcAuthorizationCodeAuthenticationProvider.java#L134), tell me the value of `authorizationResponse.getRedirectUri()` and `authorizationRequest.getRedirectUri()`.

2. Please tell me the redirect url you configured in Protal:
![web-application-set-redirect-uri-1](https://user-images.githubusercontent.com/13167207/128445343-38ac3b7a-89db-4849-816b-3241d1e7e8da.png)

![web-application-set-redirect-uri-2](https://user-images.githubusercontent.com/13167207/128445228-2e92a05e-d00b-432e-bf56-69eb9560c090.png)

**Comment by chenrujun** [comment]
And the redirect URI must begin with the scheme https.

Refs: https://docs.microsoft.com/en-us/azure/active-directory/develop/reply-url

**Comment by chenrujun** [comment]
Hi, @GuillaumeVerdon.
Thanks for reaching out.

> The redirect URI must begin with the scheme https. There are some exceptions for localhost redirect URIs.

Refs: https://docs.microsoft.com/en-us/azure/active-directory/develop/reply-url


> The TLS part is managed by the app service itself. My application is therefore listening HTTP traffic (not HTTPS).

I can't understand this. App Service use TLS, then your application can receive request if we send **https** request, right?
Then can we configure that **https** url in Azure Portal?

Refs: https://docs.microsoft.com/en-us/azure/app-service/configure-authentication-provider-aad#-create-an-app-registration-in-azure-ad-for-your-app-service-app

**Comment by GuillaumeVerdon** [comment]
Hi @chenrujun 

Here's a schema I quickly made to try to be more expressive.

![image](https://user-images.githubusercontent.com/24564552/129523572-775ed2cd-b13b-4ef8-a128-5fa8eec056ec.png)

The Azure App Service acts as a proxy for my application and is managing the TLS part. Thanks to that feature, I don't need to import any certificate in my application, it can simply listen for HTTP traffic.

However, when springboot gets a hold on the HttpServletRequest object, the scheme is HTTP as the request doesn't come from the user, but from the internals of App Service.

Springboot is then comparing the request it receives with the stored redirect response it made earlier and finds out that it redirected the user to microsoft login with a HTTPS redirect uri and the current request has HTTP scheme and this is where it breaks.

**Comment by GuillaumeVerdon** [comment]
![Untitled](https://user-images.githubusercontent.com/24564552/129544891-950ef9ba-5d0a-48e0-8653-4f2022250ec6.png)

**Comment by chenrujun** [comment]
Hi, @GuillaumeVerdon.

Thank you for your detailed description.
Could you please try this method: https://github.com/spring-projects/spring-security/issues/5270#issuecomment-396355996
i.e. 
1. Add `server.use-forward-headers=true` in application.properties.
2. Set `spring.security.oauth2.client.registration.azure.redirect-uri-template` according to AppService's IP?

**Comment by GuillaumeVerdon** [comment]
Hi @chenrujun ,

Adding `server.use-forward-headers=true` in the properties did the trick !

Thanks a lot for the help !

**Comment by chenrujun** [comment]
@GuillaumeVerdon 
You are welcome.

Closing this issue because problem solved.
