### ISSUE TITLE
[QUERY] ServiceBus How to resend message When consumer Exception?

### ISSUE THREAD

**Issue by ElanZh** [Azure/azure-sdk-for-java#23347]
**Query/Question**
ServiceBus
How to resend message When consumer Exception?
如何在消费消息异常时重新投递消息？

**Setup (please complete the following information if applicable):**
 - OS: linux ubuntu
 - IDE: IntelliJ
 - Library/Libraries: com.azure.spring:azure-spring-boot-starter-servicebus-jms:3.6.0

`spring.jms.servicebus.pricing-tier=Standard`

My Consumer configed:

`spring.jms.listener.acknowledge-mode=client`
 
My Java Code:

```java
@Component
@Slf4j
public class TopicReceiveController {
    private static final String TOPIC_NAME = "test_topic";

    private static final String SUBSCRIPTION_NAME = "test_subscription";

    @JmsListener(destination = TOPIC_NAME, containerFactory = "topicJmsListenerContainerFactory",
            subscription = SUBSCRIPTION_NAME)
    public void receiveMessage(JmsMessage message, JmsSession session) throws JMSException {
        log.info("receive msg: " + message.getBody(String.class));
        throw new RuntimeException("some exception");
    }
}
```
it not call `message.acknowledge();` but will not receive message again

what should I do if I want ServiceBus resend the message When Exception？

 **Information Checklist**
 Kindly make sure that you have added all the following information above and checkoff the required fields otherwise we will treat the issuer as an incomplete report
- [x] Query Added
- [x] Setup information Added

**Comment by yiliuTo** [comment]
Hi @ElanZh , this is due to a bug of our "topicJmsListenerContainerFactory", it doesn't pick up the configuration of spring.jms.listener.acknowledge-mode, we will fix it soon. 
And for a quick workaround, you can create another JmsListenerContainerFactory bean and set the necessary configuration there, for example:
```
    @Bean
    public JmsListenerContainerFactory<?> jmsListenerContainerFactory(ConnectionFactory connectionFactory) {
        final DefaultJmsListenerContainerFactory jmsListenerContainerFactory = new DefaultJmsListenerContainerFactory();
        jmsListenerContainerFactory.setConnectionFactory(connectionFactory);
        jmsListenerContainerFactory.setSessionAcknowledgeMode(2); //CLIENT_ACKNOWLEDGE 
        return jmsListenerContainerFactory;
    }
```

**Comment by ElanZh** [comment]
use this Bean ,the App can not connect to topic:

```java
@JmsListener(destination = TOPIC_NAME, containerFactory = "jmsListenerContainerFactory",
            subscription = SUBSCRIPTION_NAME)
    public void receiveMessage(JmsMessage message, JmsSession session) throws JMSException 
...
...
...
```

```log
2021-08-05 17:46:58.599  WARN 30670 --- [nerContainer-10] o.s.j.l.DefaultMessageListenerContainer  : Setup of JMS message listener invoker failed for destination 'test_topic' - trying to recover. Cause: The messaging entity 'maxxisuatsb:Topic:test_topic|qpid-jms:receiver:ID:5b969c66-c5c4-47d1-aa15-c0b0c8e01cc0:1:6:1:test_topic' could not be found. To know more visit https://aka.ms/sbResourceMgrExceptions.  TrackingId:a0d27621-38ca-4531-b42a-7321dbe557e1_B1, SystemTracker:maxxisuatsb:Topic:test_topic|qpid-jms:receiver:ID:5b969c66-c5c4-47d1-aa15-c0b0c8e01cc0:1:6:1:test_topic, Timestamp:2021-08-05T09:46:53 TrackingId:b1f68a9dcf9a4b6fa8c456d7d312806b_G2, SystemTracker:gateway7, Timestamp:2021-08-05T09:46:53 [condition = amqp:not-found]
```

**Comment by ElanZh** [comment]
> Hi @ElanZh , this is due to a bug of our "topicJmsListenerContainerFactory", it doesn't pick up the configuration of spring.jms.listener.acknowledge-mode, we will fix it soon.
> And for a quick workaround, you can create another JmsListenerContainerFactory bean and set the necessary configuration there, for example:
> 
> ```
>     @Bean
>     public JmsListenerContainerFactory<?> jmsListenerContainerFactory(ConnectionFactory connectionFactory) {
>         final DefaultJmsListenerContainerFactory jmsListenerContainerFactory = new DefaultJmsListenerContainerFactory();
>         jmsListenerContainerFactory.setConnectionFactory(connectionFactory);
>         jmsListenerContainerFactory.setSessionAcknowledgeMode(2); //CLIENT_ACKNOWLEDGE 
>         return jmsListenerContainerFactory;
>     }
> ```

use this Bean ,the App can not connect to topic:

```java
@JmsListener(destination = TOPIC_NAME, containerFactory = "jmsListenerContainerFactory",
            subscription = SUBSCRIPTION_NAME)
    public void receiveMessage(JmsMessage message, JmsSession session) throws JMSException 
...
...
...
```

```log
2021-08-05 17:46:58.599  WARN 30670 --- [nerContainer-10] o.s.j.l.DefaultMessageListenerContainer  : Setup of JMS message listener invoker failed for destination 'test_topic' - trying to recover. Cause: The messaging entity 'maxxisuatsb:Topic:test_topic|qpid-jms:receiver:ID:5b969c66-c5c4-47d1-aa15-c0b0c8e01cc0:1:6:1:test_topic' could not be found. To know more visit https://aka.ms/sbResourceMgrExceptions.  TrackingId:a0d27621-38ca-4531-b42a-7321dbe557e1_B1, SystemTracker:maxxisuatsb:Topic:test_topic|qpid-jms:receiver:ID:5b969c66-c5c4-47d1-aa15-c0b0c8e01cc0:1:6:1:test_topic, Timestamp:2021-08-05T09:46:53 TrackingId:b1f68a9dcf9a4b6fa8c456d7d312806b_G2, SystemTracker:gateway7, Timestamp:2021-08-05T09:46:53 [condition = amqp:not-found]
```

**Comment by yiliuTo** [comment]
Hi @ElanZh , sorry that didn't notice you use Service Bus topic, in this way another configuration of **subscriptionDurable**is need for the listener container factory, so the bean should be like 
```
    @Bean
    public JmsListenerContainerFactory<?> jmsListenerContainerFactory(ConnectionFactory connectionFactory) {
        final DefaultJmsListenerContainerFactory jmsListenerContainerFactory = new DefaultJmsListenerContainerFactory();
        jmsListenerContainerFactory.setConnectionFactory(connectionFactory);
        jmsListenerContainerFactory.setSubscriptionDurable(Boolean.TRUE);
        jmsListenerContainerFactory.setSessionAcknowledgeMode(2); //CLIENT_ACKNOWLEDGE 
        return jmsListenerContainerFactory;
    }
```

**Comment by ElanZh** [comment]
> Hi @ElanZh , sorry that didn't notice you use Service Bus topic, in this way another configuration of **subscriptionDurable**is need for the listener container factory, so the bean should be like
> 
> ```
>     @Bean
>     public JmsListenerContainerFactory<?> jmsListenerContainerFactory(ConnectionFactory connectionFactory) {
>         final DefaultJmsListenerContainerFactory jmsListenerContainerFactory = new DefaultJmsListenerContainerFactory();
>         jmsListenerContainerFactory.setConnectionFactory(connectionFactory);
>         jmsListenerContainerFactory.setSubscriptionDurable(Boolean.TRUE);
>         jmsListenerContainerFactory.setSessionAcknowledgeMode(2); //CLIENT_ACKNOWLEDGE 
>         return jmsListenerContainerFactory;
>     }
> ```

Good, It work!
