### ISSUE TITLE
[FEATURE REQ] Enable/disable azure-spring-boot auto configurations based on properties

### ISSUE THREAD

**Issue by rvvaeke** [Azure/azure-sdk-for-java#23367]
**Is your feature request related to a problem? Please describe.**
There is currently no flexibility in when the *AutoConfiguration classes in azure-spring-boot are applied. In some scenarios it is feasible to disable certain *AutConfiguration classes. This would provide flexibility in configuring different Spring context, especially in tests.

**Describe the solution you'd like**
Support enabling/disabling of *AutoConfiguration classes in azure-spring-boot using properties. For example: azure.storage.enabled or azure.cosmos.enabled.

**Describe alternatives you've considered**
None.

**Additional context**
None.

**Comment by backwind1233** [comment]
@rvvaeke Thanks for your advice, we have added it to our backlog and will discuss about it. We will inform you if there is any updates.

**Comment by saragluna** [comment]
This has been merged to the feature/azure-spring-cloud-4.0 branch. https://github.com/Azure/azure-sdk-for-java/pull/23849

**Comment by saragluna** [comment]
Closing this issue now, please check https://github.com/Azure/azure-sdk-for-java/issues/24260 for the release of our next major version.
