### ISSUE TITLE
Investigate how to derive the metrics from OTel tracing spans

### ISSUE THREAD

**Issue by saragluna** [Azure/azure-sdk-for-java#23370]
Since the Azure SDK expose no metrics by default, but they do depend on the OTel for tracing, so it's possible for us to derive the metrics from the OTel tracing spans. This task is used to track this investigation.

**Comment by stliu** [comment]
personally I'd not think this is the right approach

**Comment by stliu** [comment]
and we should not expect OTeL exist on classpath or even worse bring it to the classpath by us

**Comment by saragluna** [comment]
Closing this issue now, we've decided not to use this approach to get metrics.
