### ISSUE TITLE
Azure spring boot Storage Sample support AppendBlob and PageableBlob

### ISSUE THREAD

**Issue by backwind1233** [Azure/azure-sdk-for-java#23371]
**Context**
Refer to  https://github.com/Azure/azure-sdk-for-java/issues/21461,  if the feature is completed and codes are merged, we should update our Samples to add new samples demonstrate AppendBlob and PageableBlob features.

**Goal**
Add new samples to demonstrate Storage AppendBlob and PageableBlob features.

**Comment by stliu** [comment]
closing this one in favor of #21461
