### ISSUE TITLE
Check accuracy of Spring telemetry from SDK track2 BI source

### ISSUE THREAD

**Issue by yiliuTo** [Azure/azure-sdk-for-java#23389]
Some Spring libraries collect telemetry from SDK's track2 telemetry database of **DDAzureServicesApps**, and the detailed tables to read telemetry of each Service are **AzureSDK_DP_Raw_<Service Name>_Daily**, the involved services are Key Vault, Storage, Service Bus, Event Hubs.

Currently we find that above tables don't contain all Spring telemetry, e.g., subscription of **Azure Spring Cloud Dev - TTL = 3 Days ** are not contained. We need to find out the reason and check if SDK track2 telemetry database are accurate for Spring.

Possible solutions: Compare Spring telemetry from each Service team's BI datasource are the same as **AzureSDK_DP_Raw_<Service Name>_Daily**.

**Comment by yiliuTo** [comment]
Service telemetry need to check:
- [ ] Event Hubs
- [ ] Service Bus
- [ ] Storage
- [ ] Key Vault

**Comment by stliu** [comment]
Closing this one, we don't use this issue tracker for BI issues
