### ISSUE TITLE
Add Support for Additional Environment Configurations

### ISSUE THREAD

**Issue by alzimmermsft** [Azure/azure-sdk-for-java#23383]
Currently, many common configurations have a hard-coded constants as the default value. For these configurations, it should be investigated and determined whether an environment configuration could be used as the default value instead if it is set, potential configurations to update:

- [x] Default request retry limit
- [x] Network timeouts
  - [x] Connect timeout
  - [x] Request send timeout
  - [x] Response timeout
  - [x] Response read timeout
- [ ] Default polling interval for long running operations
- [ ] Default headers and query parameters allowed in logging

Not all configurations mentioned above will be configurable from the environment but are areas that should be investigated. Additionally, a framework for configuring different default behaviors per SDK, Storage Blobs vs Cosmos vs Azure Search, should be investigated.

**Comment by stliu** [comment]
is there a wiki page list all env vars?

I noticed besides azure-core, some service sdk also using some specific env to config, for example [this one](https://github.com/Azure/azure-sdk-for-java/blob/36ef7a91fbe8e4d01d0773836d477ba238ff815c/sdk/keyvault/azure-security-keyvault-secrets/src/main/java/com/azure/security/keyvault/secrets/SecretClientBuilder.java#L380)

**Comment by alzimmermsft** [comment]
> is there a wiki page list all env vars?

There is a high-level list in the Azure SDK guidelines: https://azure.github.io/azure-sdk/general_azurecore.html

But I don't think there is a more targeted list for special SDK or language specific environment variables. I'll file an associated issue to create documentation for them.
