### ISSUE TITLE
[BUG] cosmos LIKE not working with @Param

### ISSUE THREAD

**Issue by jibinqb** [Azure/azure-sdk-for-java#23386]
**Describe the bug**
Using cosmos with spring boot.

This does not work

  ```
  public interface UsersRespository extends CosmosRepository<User, String>  {
    
      @Query("SELECT * FROM c WHERE c.name LIKE \"%@searchString%\"")
      List<User> search(@Param("searchString") String searchString);
```

but this works

   ```
 public interface UsersRespository extends CosmosRepository<User, String>  {
        
          @Query("SELECT * FROM c WHERE c.name LIKE \"%mm%\"")
          List<User> search(@Param("searchString") String searchString);

```
This also works

 ```
 public interface UsersRespository extends CosmosRepository<User, String>  {
            @Query("SELECT * FROM c WHERE c.name = '@searchString'")
              List<User> search(@Param("searchString") String searchString);
```

***Exception or Stack Trace***
Empty response is returned in the first case

**To Reproduce**
You can use the above code.

***Code Snippet***
 List<User> users = userRepository.search(search);

**Expected behavior**
Like works.
In the data explorer in portal it works.

**Setup:**
 - IDE: IntelliJ
 - Library/Libraries: azure-spring-data-cosmos 3.9.0
 - Java version:  8 
 - Frameworks: Spring Boot 
  
**Additional context**
Some logs
```
22:58:41.178 [http-nio-8080-exec-5] DEBUG com.azure.cosmos.implementation.SqlQuerySpecLogger - SELECT * FROM c WHERE c.name LIKE '%@searchString%'
 > param: @searchString = thomas
```

Stackoverflow link :https://stackoverflow.com/questions/68668394/spring-boot-azure-spring-data-cosmos-like-returning-empty

**Comment by joshfree** [comment]
@kushagraThapar could you please help route @jibinqb's issue?

**Comment by trande4884** [comment]
@jibinqb from what you posted in the logs section when the @searchString is placed in the query string it gets wrapped in quotes "". So by putting the escaped quotes in your annotated query definition the query that gets built is:
SELECT * FROM c WHERE c.name LIKE ""%thomas%""

You should simply define your query as:
@Query("SELECT * FROM c WHERE c.name LIKE %@searchString%")
