### ISSUE TITLE
[Epic] Unify the running experience of our samples by terraform

### ISSUE THREAD

**Issue by backwind1233** [Azure/azure-sdk-for-java#23391]
There are nearly 40 samples in our [repo](https://github.com/Azure-Samples/azure-spring-boot-samples), but the running and configuration of each sample is different from each other, so our user needs to create different resources on Azure and arrange different steps and configurations for each sample in order to run the sample.

[Terraform ](https://www.terraform.io/) provides a unified way to configure the resources on Azure, which can reduce the effort to the user.

most of samples have been refactored with terraform in this [issue](https://github.com/Azure/azure-sdk-for-java/issues/25652)

Samples left to refactor:

- [x] #26550
- [x] #26312

**Comment by saragluna** [comment]
AAD, Redis and Spring Data Cosmos are not supported.

**Comment by chenrujun** [comment]
Closing this issue because all sub tasks have been finished.
