### ISSUE TITLE
[QUERY] Is this project affected by the Azure IoT TLS certificate change?

### ISSUE THREAD

**Issue by sesu-bio** [Azure/azure-sdk-for-java#23401]
**Query/Question**
Microsoft announced that there will be a root certificate change on the Azure IoT servers. We had to upgrade our IoT SDK dependencies because they use hardcoded certificates. We also use the Blob Storage SDK for file uploads and downloads. Are there any additional steps we need to take regarding this project to continue operations after the certificate change?

***Why is this not a Bug or a feature Request?***
Just asking for information.

**Setup (please complete the following information if applicable):**
 - OS: Linux
 - IDE: Eclipse
 - Library/Libraries: com.azure:azure-storage-blob:12.10.2, com.azure:azure-core:1.13.0
 
 **Information Checklist**
 Kindly make sure that you have added all the following information above and checkoff the required fields otherwise we will treat the issuer as an incomplete report
- [x] Query Added
- [x] Setup information Added

**Comment by joshfree** [comment]
@rickle-msft could you assist @sesu-bio with his question with respect to the Azure Storage SDK for Java?

**Comment by amishra-dev** [comment]
@sesu-bio no it should not impact Azure Storage. Thanks for checking with us.

**Comment by sesu-bio** [comment]
Great. Thank you for the quick response!

**Comment by amishra-dev** [comment]
@sesu-bio looks like i was mistaken. Please follow the steps on https://techcommunity.microsoft.com/t5/azure-storage/azure-storage-tls-changes-are-coming-and-why-you-care/ba-p/1705518

**Comment by sesu-bio** [comment]
@amishra-dev thank you for for the update. I assume the article is from a previous certificate change because it is rather old and mentions that the root certificate is not changed - but it is now according to this article:
[https://techcommunity.microsoft.com/t5/internet-of-things/azure-iot-tls-critical-changes-are-almost-here-and-why-you/ba-p/2393169](https://techcommunity.microsoft.com/t5/internet-of-things/azure-iot-tls-critical-changes-are-almost-here-and-why-you/ba-p/2393169)

Anyway, we don't do certificate pinning. As this SDK does not use hardcoded certificates, I assume it uses the ones from the JRE's cacerts. The cacerts file on our product contains both the old and new root certificates from the article I linked above. I think we should be good.

**Comment by amishra-dev** [comment]
You should be good in that case. Thanks @sesu-bio appreciate your getting back to me.

Thanks
Ashish
