### ISSUE TITLE
[FEATURE REQ] Add metrics for Azure Spring Service Bus

### ISSUE THREAD

**Issue by yiliuTo** [Azure/azure-sdk-for-java#23400]
### Context
We plan to expose metrics for Azure Spring Service Bus related libraries to enable developers to view metrics about connection, messages states. 

Referring to Kafka's metrics design, the Spring Service Bus metrics components can contain:

| Metric Name | Type | Tag | Description |
|--|--|--|--|
| connection.active | Gauge | servicebus | The number of active connection. |
| connection.opened | Gauge | servicebus | The number of open connection. |
| connection.closed | Gauge | servicebus | The number of closed connection. |
| messages.published| Count | servicebus, topic/queue | The number of published messages. |
| messages.failed_to_publish | Count | servicebus, topic/queue | The number of failed to publish messages. |
| messages.consumed | Count | servicebus, (topic + subscription)/queue | The number of consumed messages. |
| messages.acknowledged | Count | servicebus, (topic + Subscription)/queue | The number of acked messages. |
| messages.rejected | Count | servicebus, (topic + subscription)/queue | The number of rejected messages. |

### Next Step
To support Spring Service Bus metrics, currently we need the support from Service Bus SDK to enable and expose metrics APIs. Tracked in #25605

**Comment by yiliuTo** [comment]
Metrics Types:

| Metric Name | Type | Tag | Description |
|--|--|--|--|
| connection.active | Gauge | servicebus | The number of active connection. |
| connection.opened | Gauge | servicebus | The number of open connection. |
| connection.closed | Gauge | servicebus | The number of closed connection. |
| messages.published| Count | servicebus, topic/queue | The number of published messages. |
| messages.failed_to_publish | Count | servicebus, topic/queue | The number of failed to publish messages. |
| messages.consumed | Count | servicebus, (topic + subscription)/queue | The number of consumed messages. |
| messages.acknowledged | Count | servicebus, (topic + Subscription)/queue | The number of acked messages. |
| messages.rejected | Count | servicebus, (topic + subscription)/queue | The number of rejected messages. |

**Comment by saragluna** [comment]
https://github.com/Azure/azure-sdk-for-java/issues/25605
