### ISSUE TITLE
Align dependencies for azure-search-documents

### ISSUE THREAD

**Issue by pallavit** [Azure/azure-sdk-for-java#23406]
There are dependency conflicts in azure-search-documents with respect to azure-core. Please fix them as part of the release.

![image](https://user-images.githubusercontent.com/10713359/128561068-e29ef33a-aecb-4646-84fb-c3c67aa8ecc7.png)

You can also find the latest report at https://azuresdkartifacts.blob.core.windows.net/azure-sdk-for-java/staging/dependency_conflictlist.html which you may want to glance once azure-core releases.

**Comment by alzimmermsft** [comment]
Resolved with the release of [azure-search-documents 11.4.1](https://repo1.maven.org/maven2/com/azure/azure-search-documents/11.4.1/)
