### ISSUE TITLE
[FEATURE REQ] Support Azure IMDS with spring

### ISSUE THREAD

**Issue by stliu** [Azure/azure-sdk-for-java#23424]
[Azure IMDS](https://docs.microsoft.com/en-us/azure/virtual-machines/windows/instance-metadata-service?tabs=windows) provides various useful metadata for applications, and we should have a property source to consume them and provide to customer application

**Comment by alzimmermsft** [comment]
IDMS also provides a [Swagger specification](https://github.com/Azure/azure-rest-api-specs/tree/main/specification/imds/data-plane/Microsoft.InstanceMetadataService/stable) which could be leveraged by our code generators to create the public API to support this functionality. Though it may not be required to use the Swagger specification to create this functionality, it'll just help greatly and also may provide a better ability to offer multi-version support.

This still leaves an open question on where the functionality should live. There are a few potential solutions:

- Include this functionality in `azure-core`. This provides extreme convenience to anyone who would want to leverage this as it would be included implicitly, downside is that not everyone (possibly most everyone) won't need this functionality and it'll be additional bloat.
- Creating a new plugin library, similar to `azure-identity`, to provide this functionality. This provides convenience to add the functionality as it is needed without adding additional bloat to any commonly used SDKs, downside is that users will need to find this functionality when it is needed but this follows an existing pattern so this downside's impact should be reduced.

**Comment by joshfree** [comment]
@sandeep-sen volunteered to design this feature request; and get agreement on the capabilities with @stliu in Nickel+, before we commit to implementing it in Copper semester.

**Comment by alzimmermsft** [comment]
Another design consideration, the IMDS has [rate limiting](https://docs.microsoft.com/en-us/azure/virtual-machines/windows/instance-metadata-service?tabs=windows#rate-limiting) which restricts to 5 requests per second, except for Managed Identity which is limited to 20 per seconds with 5 concurrent calls. Fortunately, the service will return a 429 response which we can use to back-off appropriately.

**Comment by sandeep-sen** [comment]
@stliu could provide a list of metadata you need. It would be helpful if you break the list into 2 sections ` must have` and `good to have`

**Comment by joshfree** [comment]
@sandeep-sen are you able to get this spec complete for April so devs can pick this up in early Copper?

**Comment by stliu** [comment]
> Another design consideration, IMDS has [rate limiting](https://docs.microsoft.com/en-us/azure/virtual-machines/windows/instance-metadata-service?tabs=windows#rate-limiting) which restricts to 5 requests per second, except for Managed Identity which is limited to 20 per seconds with 5 concurrent calls. In the case of rate limiting a 429 response will be returned which will allow for the appropriate back-off to be applied, but this still causes difficulties as there isn't a guarantee that our calls will be the only made.

actually that's exactly our sdk should consider support this, either option list here is fine https://github.com/Azure/azure-sdk-for-java/issues/23424#issuecomment-1024470872

**Comment by stliu** [comment]
> @stliu Strong Liu FTE could provide a list of metadata you need. It would be helpful if you break the list into 2 sections ` must have` and `good to have`

@sandeep-sen I  like @alzimmermsft suggestion, probably we should just provide all of IMDS has, since we don't know exactly which customer wants and wich customer doesn't

**Comment by JonathanGiles** [comment]
@sandeep-sen Can you check to see if this should be done cross-language, and if so, get the work prioritised as appropriate? Thanks

**Comment by sandeep-sen** [comment]
## Requirement

- Get all runtime metadata via IMDS and expose it to the user
- Spring can expose these metadata objects through config properties

| :exclamation:  **Note: This feature is not present in any other language SDK and we will need arch board review** |
|-----------------------------------------|


## Next Steps
Create a MVP interfaces and review with spring team. Once spring team has approved push for arch board review

## MVP
@lmolkova's proposal:
We have nothing in core
IMDS communication is handled in spring integration (it's just reusing core primitives - HTTP client)
Users can get individual fields by adding `@Value` annotation

@stliu's and @saragluna's proposal:
Configure in properties like `spring.cloud.azure.profile.cloud-type`

## References

- [IMDS](https://docs.microsoft.com/en-us/azure/virtual-machines/linux/instance-metadata-service?tabs=windows)
- [Swagger Spec for IMDS](https://github.com/Azure/azure-rest-api-specs/tree/main/specification/imds/data-plane/Microsoft.InstanceMetadataService/stable)
- [IMDS Rate Limiting](https://docs.microsoft.com/en-us/azure/virtual-machines/windows/instance-metadata-service?tabs=windows#rate-limiting)

**Comment by srnagar** [comment]
Currently, there's no plan to support track 2 Azure IMDS library. 

If Spring libraries need this, we can generate the client from AutoRest and include it in the `implementation` package (no public API should be added) of Spring libraries until a track 2 data-plane library is released.
