### ISSUE TITLE
[FEATURE REQ] Support spring framework's startup time tracking

### ISSUE THREAD

**Issue by stliu** [Azure/azure-sdk-for-java#23423]
## Context
With the increase of spring users, the startup time of the spring framework has also become a point of concern for users. 

## Problem
We have heard a lot of complaints from users that hard to find out why their spring boot startup is so slow.

## Solution
spring framework and spring boot address this problem by [Startup Tracking](https://docs.spring.io/spring-boot/docs/current/reference/html/features.html#features.spring-application.startup-tracking), we should consider supporting this. To provide customers a detailed view of what's happening inside a spring boot application startup. We should see what steps spring provide and let's decide what 'step' we should define. Should we define a step == 'a bean initialization' or a step is a more fine controlled block of actions the application is performing.

**Comment by hui1110** [comment]
In  `spring-cloud-azure-starter-actuator`, `spring-boot-starter-actuator` is already supported. Through ApplicationStartup's implementation of BufferingApplicationStartup or FlightRecorderApplicationStartup, the application startup sequence can be tracked during application startup, and this data can be collected for analysis purposes, such as when a bean completes initialization, etc.

**Comment by hui1110** [comment]
Closing this issue now.

**Comment by saragluna** [comment]
Seems like this issue has not been resolved, added some description and reopen it now.
