### ISSUE TITLE
[BUG] JCA client stuck on KeyStore engineGetCertificate

### ISSUE THREAD

**Issue by eric-genesys** [Azure/azure-sdk-for-java#23427]
**Describe the bug**
I am using azure-security-keyvault-jca:1.0.1,  and load a AzureKeyVault KeyStore
When I call keystore.aliases(), it endless stuck

***Exception or Stack Trace***
Not a crash, the last log is
Aug 09, 2021 11:14:17 AM com.azure.security.keyvault.jca.AuthClient getAccessToken
INFO: Getting access token using client ID / client secret

**To Reproduce**
it doesn't happen all the time, but we do have this stuck for few times a week.
When this happens, another azure key vault under same account has also this problem

***Code Snippet***

        Security.addProvider(new KeyVaultJcaProvider());
        KeyStore azureKeyStore = KeyStore.getInstance("AzureKeyVault");
        KeyVaultLoadStoreParameter parameter = new KeyVaultLoadStoreParameter(keyVaultUri, tenantId, clientId, cientSecret);
        azureKeyStore.load(parameter);
        azureKeyStore.aliases(); ---- this code lin stuck

**Expected behavior**
the stuck should never happens

**Screenshots**
no screen shot

**Setup (please complete the following information):**
 - OS: MacOS, or UBI8 Container with Java 8
 - IDE: IntelliJ for dev or Java 8 for production
 - Library/Libraries: azure-security-keyvault-jca:1.0.1
 - Java version: 8
 - App Server/Environment: Embedded Jetty
 - Frameworks: Spring Boot

If you suspect a dependency version mismatch (e.g. you see `NoClassDefFoundError`, `NoSuchMethodError` or similar), please provide
No
  
**Additional context**

**Information Checklist**
Kindly make sure that you have added all the following information above and checkoff the required fields otherwise we will treat the issuer as an incomplete report
- [ ] Bug Description Added
- [ ] Repro Steps Added
- [ ] Setup information Added

**Comment by joshfree** [comment]
@chenrujun @saragluna could you please assist @eric-genesys on this issue?

/cc @vcolin7

**Comment by chenrujun** [comment]
Hi, @eric-genesys.

Thanks for reaching out.
But I can not reproduce you problem.

This is the code:
```
    public static void main(String[] args) throws Exception {
        KeyVaultJcaProvider provider = new KeyVaultJcaProvider();
        Security.addProvider(provider);

        String keyVaultUri = "https://keyvaultrujche.vault.azure.net/";
        String tenantId = "...";
        String clientId = "...";
        String clientSecret = "...";
        Security.addProvider(new KeyVaultJcaProvider());
        KeyStore keyStore = KeyStore.getInstance("AzureKeyVault");
        KeyVaultLoadStoreParameter parameter = new KeyVaultLoadStoreParameter(keyVaultUri, tenantId, clientId, clientSecret);
        keyStore.load(parameter);
        Enumeration aliases = keyStore.aliases();
        while (aliases.hasMoreElements()) {
            System.out.println(aliases.nextElement());
        }
    }
```

Here is the screenshot when I run this code:
![image](https://user-images.githubusercontent.com/13167207/128795538-4c14aaca-06fb-4e87-b21c-1778650dedc5.png)

And `ceritificate-1` is loaded from Key Vault:
![image](https://user-images.githubusercontent.com/13167207/128795610-74980571-4ac2-4ed6-81ec-713a53d5f6fc.png)
![image](https://user-images.githubusercontent.com/13167207/128795677-3b7f77f4-50d3-4e70-8036-10c0fd3947cc.png)

**Comment by eric-genesys** [comment]
No doubt it works for you. For myside, I do see sometime the same API works but it is not 100% as fast. 

Notes, when I see slowness, all of the Key Vault under our account are all very slow. I manage to set a break point and found the code get stuck at allCertificates.stream() 

I can see allCertificate has 5 children and it has loaded the certiticate name which looks no network issue

Below code is from com.azure.security.keyvault.jca.KeyVaultKeyStore
    @Override
    public Certificate engineGetCertificate(String alias) {
        Certificate certificate = allCertificates.stream() 
                                                 .map(AzureCertificates::getCertificates)
                                                 .filter(a -> a.containsKey(alias))
                                                 .findFirst()
                                                 .map(certificates -> certificates.get(alias))
                                                 .orElse(null);

**Comment by eric-genesys** [comment]
e..g we have seen this slowness for 24 hours today

**Comment by chenrujun** [comment]
@eric-genesys .

> I do see sometime the same API works but it is not 100% as fast.

Maybe it's caused by your network is not good?


> I can see allCertificate has 5 children and it has loaded the certiticate name which looks no network issue

`keyVaultCertificates` needs network, but it has cache the result get by network.

Could you please add breakpoint at the 5 `AzureCertificates::getCertificates` and check which one blocked?

**Comment by eric-genesys** [comment]
I restart my application but doesn't help, so I don't think cache is used. 

I added more break point, the break point hit findFirst, then I let it run, it get stuck.

        Certificate certificate = allCertificates.stream()
                                                 .map(AzureCertificates::getCertificates)
                                                 .filter(a -> a.containsKey(alias))
                                                 .findFirst()
                                                 .map(certificates -> certificates.get(alias))
                                                 .orElse(null);

**Comment by paulgvildys** [comment]
@chenrujun note we are seeing this when running in Azure deployments.  If it's network, wouldn't that mean Azure --> Keyvault has network issues?

**Comment by chenrujun** [comment]
Hi, @eric-genesys .
Could you please add a break point here?
https://github.com/Azure/azure-sdk-for-java/blob/azure-security-keyvault-jca_1.0.1/sdk/keyvault/azure-security-keyvault-jca/src/main/java/com/azure/security/keyvault/jca/KeyVaultCertificates.java#L110

**Comment by chenrujun** [comment]
@paulgvildys ,
If it's running in Azure Deployments, I think it's not caused by network.

Since I can not reproduce your problem in my localhost, and you can reproduce this problem in your localhost, so I suggest you to add more breakpoint to debug it.

Now I don't have enough information go know the root cause.

**Comment by vcolin7** [comment]
@chenrujun Is there any way to change the log level on the JCA library to see what's going on at a more granular level (e.g. `VERBOSE` instead of `INFO`)?

**Comment by chenrujun** [comment]
Hi, @eric-genesys. Please refer to this PR to get more information about how to change log level: https://github.com/Azure/azure-sdk-for-java/pull/23516

**Comment by eric-genesys** [comment]
I think this code line 

url = certificateListResult.getNextLink(); 

Should be moved out of the if bracket.

**Comment by eric-genesys** [comment]
Forgot to mention, the code is 
com.azure.security.keyvault.jca.KeyVaultClient

**Comment by vcolin7** [comment]
@chenrujun Seeing the logic brought up by @eric-genesys, it is also possible that the Key Vault service will limit requests if the while block is looping several times per second. [Key Vault has pretty low rate-limits](https://docs.microsoft.com/en-us/azure/key-vault/general/service-limits#secrets-managed-storage-account-keys-and-vault-transactions) and [encourages API calls to use an exponential backoff retry strategy](https://docs.microsoft.com/en-us/azure/key-vault/general/overview-throttling#how-does-key-vault-handle-its-limits) when receiving a status code `429 (Too Many Requests)`. I don't know if the REST client used by this library handles these cases, but it if it doesn't, it most definitely should.

Here's how Azure Core's `RetryPolicy` implements [exponential backoff](https://github.com/Azure/azure-sdk-for-java/blob/66dd0c1e8c33ffb9ce73663480e7e4e445786d35/sdk/core/azure-core/src/main/java/com/azure/core/http/policy/ExponentialBackoff.java#L21), for example.

**Comment by chenrujun** [comment]
@eric-genesys 
Thank you very much for your investigation.

Hi, @zhichengliu12581 
This bug is cause by this PR: https://github.com/Azure/azure-sdk-for-java/pull/21746
Could you please fix it ? And don't forget to add unit test for this case.

**Comment by chenrujun** [comment]
@vcolin7 Thank you for your information. I created an issue: https://github.com/Azure/azure-sdk-for-java/issues/23547
