### ISSUE TITLE
[FEATURE REQ] Tag the api versions supported by the SDK version in maven or embed part of the metadata

### ISSUE THREAD

**Issue by bganapa** [Azure/azure-sdk-for-java#23456]
**Is your feature request related to a problem? Please describe.**
Currently it is hard to figure out the api versions supported by an SDK package

**Describe the solution you'd like**
Tag it in mvnrepository 
https://mvnrepository.com/artifact/com.azure.resourcemanager/azure-resourcemanager-resources/2.0.0

**Describe alternatives you've considered**
The only alternative is to find out the tag matching the release of the package in java sdk repo, look thru the source code that points to another tag in azure rest api specs repo. Infer from the rest api specs repo

**Additional context**
AzureStack supports only the older api versions and we are trying to re use the existing track2 packages as such . We are in need of finding out the api version supported by the shipped SDKs

**Information Checklist**
Kindly make sure that you have added all the following information above and checkoff the required fields otherwise we will treat the issuer as an incomplete report
- [x] Description Added
- [x] Expected solution specified

**Comment by joshfree** [comment]
@alzimmermsft could you add this to our Azure-core Improvements Epic backlog?  This is a general improvement that could be made (to include API versions in our readmes and poms, perhaps programmatically as part of version updates)

**Comment by alzimmermsft** [comment]
@bganapa, to make sure I'm understanding the request correctly.

Given an example of Storage, you'd expect the library to indicate whether or not it supports API versions `2021-02-01`, `2021-01-01`, etc, etc?

**Comment by bganapa** [comment]
@alzimmermsft  here is an example from .net SDK https://www.nuget.org/packages/Microsoft.Azure.Management.Compute/48.0.0

The package indicates the following api versions are supported in the package as part of the tags
![image](https://user-images.githubusercontent.com/12038849/128953445-9ca1c41a-3599-4059-b809-39e564fed390.png)

Compute is a bit complex as it has many different resource types getting bundled in a single namespace. 

As you know, The SDKs are autogenerated with the tags from rest api specs readme.md, for example
https://github.com/Azure/azure-rest-api-specs/blob/main/specification/compute/resource-manager/readme.md#tag-package-2021-04-01

I am looking for a way to expose this set of information in the SDK metadata/tags itself

**Comment by weidongxu-microsoft** [comment]
> For generated Lite packages, we had a doc to track the api-version and related releases
> https://github.com/Azure/azure-sdk-for-java/blob/main/sdk/resourcemanager/docs/SINGLE_SERVICE_PACKAGES.md
> 
> For Premium packages, it is not that easy, one need to first get to the repo tag for that release. E.g. 2.0.0 -> https://github.com/Azure/azure-sdk-for-java/tree/azure-resourcemanager_2.0.0
> 
> Then get to the api-specs.json file, and it shows the api-version. E.g. "resources" -> https://github.com/Azure/azure-sdk-for-java/blob/azure-resourcemanager_2.0.0/sdk/resourcemanager/api-specs.json#L275
> 
> Please note both of them actually only refer to the "tag" in readme, not exactly the api-version.

**Comment by weidongxu-microsoft** [comment]
And the "tag" version might not be very useful, as most service have more than one api-version in a release.
E.g. compute 2021-04-01 have 4 api-versions for different resourceType.

**Comment by weidongxu-microsoft** [comment]
For Lite SDKs, we actually have tag in maven.
E.g. https://mvnrepository.com/artifact/com.azure.resourcemanager/azure-resourcemanager-mysql/1.0.1

> This package contains Microsoft Azure SDK for MySql Management SDK. For documentation on how to use this package, please see https://aka.ms/azsdk/java/mgmt. The Microsoft Azure management API provides create, read, update, and delete functionality for Azure MySQL resources including servers, databases, firewall rules, VNET rules, log files and configurations with new business model. Package tag package-2020-01-01.
