### ISSUE TITLE
[BUG] ExpiredAuthenticationToken exception on database deletion in replicated SQL server

### ISSUE THREAD

**Issue by pknapek2** [Azure/azure-sdk-for-java#23454]
**Describe the bug**
I have two SQL servers in Failover group and I need to delete databases from both SQL servers.
When I try to delete database from secondary server in more than one hour after creation then deletion fails.
If I delete database earlier then the operation succeeds.

***Exception or Stack Trace***
[stacktrace.txt](https://github.com/Azure/azure-sdk-for-java/files/6962536/stacktrace.txt)

**To Reproduce**
1. Azure and SqlServer instances are initialized in the code.
2. Database is created using SqlServer instance in the Elastic pool. The SQL server is member of failover group. In the group is additional SQL server.
3. New database is successfuly created and it is replicated in secondary SQL server
4. The database should be deleted in more than one hour after creation.
5. Database deletion on secondary server fails

***Code Snippet***

> val credentials = ApplicationTokenCredentials("clientId", "domain", "secret", AzureEnvironment.AZURE)
val azure: com.microsoft.azure.management.Azure = Azure.configure().withLogLevel(LogLevel.NONE).authenticate(credentials).withDefaultSubscription()
val sqlServer: SqlServer = azure.sqlServers().getByResourceGroup("rgName", "sqlServerName")
val sqlFailoverGroup = sqlServer.failoverGroups().get("failoverGroup1")
sqlFailoverGroup.partnerServers().forEach { sqlServer ->
    val secondarySqlServer = azure.sqlServers().getById(sqlServer.id())
    val database = secondarySqlServer.databases().get("my-db")
    database.delete()
}

**Expected behavior**
Database is deleted from partner SQL Server

**Screenshots**
Not needed

**Setup (please complete the following information):**
 - OS: Linux
 - IDE: IntelliJ
 - Library/Libraries: com.microsoft.azure:azure-mgmt-resources:1.41.1
  
**Additional context**

**Information Checklist**
Kindly make sure that you have added all the following information above and checkoff the required fields otherwise we will treat the issuer as an incomplete report
- [x] Bug Description Added
- [x] Repro Steps Added
- [x] Setup information Added

**Comment by joshfree** [comment]
@weidongxu-microsoft could you please take a look?

**Comment by weidongxu-microsoft** [comment]
@pknapek2 

From the code it is the old SDK
```
val azure: com.microsoft.azure.management.Azure = Azure.configure().withLogLevel(LogLevel.NONE).authenticate(credentials).withDefaultSubscription()
```

Is it possible for you to try the new SDK at https://aka.ms/azsdk/java/mgmt?

**Comment by pknapek2** [comment]
Because I'm not able to reproduce the problem with new SDK I close the issue.
If the problem occurs again I will reopen the issue.
