### ISSUE TITLE
spring.aad.webapi breaking change in 3.7.0

### ISSUE THREAD

**Issue by spoptchev-extern** [Azure/azure-sdk-for-java#23453]
**Describe the bug**
As we tried to update `com.azure.spring:azure-spring-boot-starter-active-directory` from `3.4.0` to `3.7.0`  we did not expect any breaking changes on the API but there were several. This is especially unexpected when you use a custom configuration.

e.g.: `com.azure.spring.aad.webapi.AADResourceServerClientConfiguration` was removed.

**To Reproduce**
Upgrade from version `3.4.0` to `3.7.0`.

**Expected behavior**
Follow [semantic versioning](https://semver.org) where a minor version change does not cause a breaking change.

**Information Checklist**
Kindly make sure that you have added all the following information above and checkoff the required fields otherwise we will treat the issuer as an incomplete report
- [x] Bug Description Added
- [x] Repro Steps Added
- [x] Setup information Added

**Comment by joshfree** [comment]
@stliu can you please follow up on this?

@JonathanGiles was this missed in apiview?  @benbp @kurtzeborn are there extra gates we could add to catch this in the build pipeline?

**Comment by benbp** [comment]
@praveenkuttappan

**Comment by JonathanGiles** [comment]
As far as I can see, this is not on APIView. I'm not sure how this was released - something @stliu can chase up. I would expect that going forward these will go through the standard APIView review process too.

**Comment by stliu** [comment]
@JonathanGiles I totally agree, @chenrujun is working on it, to have all our release go through the standard api review process

**Comment by chenrujun** [comment]
Hi, @spoptchev-extern .

Thanks for reaching out.
It's our mistake to have breaking change.
We are trying to avoid breaking change by some tool in the following release versions.

If you want to find [com.azure.spring.aad.webapi.AADResourceServerClientConfiguration in 3.4.0], please use [com.azure.spring.aad.AADOAuth2ClientConfiguration in 3.7.0] instead.

Sorry to cause you trouble.


[com.azure.spring.aad.webapi.AADResourceServerClientConfiguration in 3.4.0]: https://github.com/Azure/azure-sdk-for-java/blob/azure-spring-boot_3.4.0/sdk/spring/azure-spring-boot/src/main/java/com/azure/spring/aad/webapi/AADResourceServerClientConfiguration.java#L48

[com.azure.spring.aad.AADOAuth2ClientConfiguration in 3.7.0]: https://github.com/Azure/azure-sdk-for-java/blob/azure-spring-boot_3.7.0/sdk/spring/azure-spring-boot/src/main/java/com/azure/spring/aad/AADOAuth2ClientConfiguration.java#L29

**Comment by spoptchev-extern** [comment]
No problem, thank you for improving the process.

**Comment by chenrujun** [comment]
Closing this issue. Use https://github.com/Azure/azure-sdk-for-java/issues/23471 to track this problem.
