### ISSUE TITLE
Azure Keyvault JCA gets access token remotely every time it visits key vault.

### ISSUE THREAD

**Issue by michaelqi793** [Azure/azure-sdk-for-java#23473]
Azure keyvault jca needs to visit key vault remotely. For each visit, it also needs an access token, so currently it also gets the access token remotely each time. This is not what we want, because the same access token can be reused, and to get the remote access token is time costly.

Please see the log:
 c.a.security.keyvault.jca.AuthClient     : Getting access token using client ID / client secret
c.a.s.keyvault.jca.KeyVaultClient        : Getting key for alias: friend
c.a.security.keyvault.jca.AuthClient     : Getting access token using client ID / client secret
c.a.security.keyvault.jca.AuthClient     : Getting access token using client ID / client secret
c.a.s.keyvault.jca.KeyVaultClient        : Getting certificate for alias: friend
c.a.security.keyvault.jca.AuthClient     : Getting access token using client ID / client secret
c.a.s.keyvault.jca.KeyVaultClient        : Using Azure Key Vault: https://kv-sp.vault.azure.net/
c.a.security.keyvault.jca.AuthClient     : Getting access token using client ID / client secret
c.a.s.keyvault.jca.KeyVaultClient        : Getting key for alias: friend
c.a.security.keyvault.jca.AuthClient     : Getting access token using client ID / client secret
c.a.security.keyvault.jca.AuthClient     : Getting access token using client ID / client secret
c.a.s.keyvault.jca.KeyVaultClient        : Getting certificate for alias: friend
c.a.security.keyvault.jca.AuthClient     : Getting access token using client ID / client secret
o.s.b.w.embedded.tomcat.TomcatWebServer  : Tomcat started on port(s): 8443 (https) with context path ''
c.a.s.b.s.w.SpringBootWebappApplication  : Started SpringBootWebappApplication in 117.996 seconds (JVM running for 118.846)

**Comment by vcolin7** [comment]
It is possible that when this library was written it copied what the other Key Vault SDKs do in their 
[`KeyVaultAuthenticationPolicy`](https://github.com/Azure/azure-sdk-for-java/blob/2756bfdeef8dacf3d55589b4469e81537db7d8b4/sdk/keyvault/azure-security-keyvault-keys/src/main/java/com/azure/security/keyvault/keys/implementation/KeyVaultCredentialPolicy.java), which shows the same behavior as outlined in [this issue](https://github.com/Azure/azure-sdk-for-java/issues/10381) and [this issue](https://github.com/Azure/azure-sdk-for-java/issues/23556). We should only ask for a challenge when the access token is expired to avoid making unnecessary additional calls.

**Comment by vcolin7** [comment]
I will add [this issue](https://github.com/Azure/azure-sdk-for-java/issues/10381) to my planning for the next release cycle, in case you want to take a look at the approach taken for that.

**Comment by michaelqi793** [comment]
Please refer to thttps://github.com/Azure/azure-sdk-for-java/blob/1bbf18fa0d4493dbb5fd245b3952bf8dbddbd383/sdk/keyvault/azure-security-keyvault-keys/src/main/java/com/azure/security/keyvault/keys/implementation/ScopeTokenCache.java
