### ISSUE TITLE
[BUG] Wrong application-type selected by azure-spring-boot-starter-active-directory

### ISSUE THREAD

**Issue by spoptchev-extern** [Azure/azure-sdk-for-java#23481]
**Describe the bug**
We think that in the `azure-spring-boot-starter-active-directory` (3.7.0) library there is a wrong assumption about the `application-type` when an OAuth 2 client is registered (`spring.security.oauth2.client.registration`). Our application is a plain `resource_server` that includes an OAuth 2 client which is communicating to another service that is not related to our AzureAD service. But in version `3.7.0` our `application-type` is tagged as `resource_server_obo` which causes several issues with our configuration. Furthermore, the `application-type` cannot be changed manually as this results in a validation exception.

***Exception or Stack Trace***
```
Caused by: java.lang.IllegalStateException: Invalid property 'azure.activedirectory.application-type', the configured value is 'resource_server', but the inferred value is 'resource_server_with_obo'.
	at com.azure.spring.autoconfigure.aad.AADAuthenticationProperties.validateApplicationType(AADAuthenticationProperties.java:510)
	at com.azure.spring.autoconfigure.aad.AADAuthenticationProperties.afterPropertiesSet(AADAuthenticationProperties.java:458)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.invokeInitMethods(AbstractAutowireCapableBeanFactory.java:1845)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1782)
	... 104 common frames omitted
```

**To Reproduce**
Set the application property `azure.activedirectory.application-type` to `resource_server` when you have registered an OAuth 2 client.

**Expected behavior**
Changing the `application-type` manually should not cause an exception.

It would also be great if we could disable `AADOAuth2ClientConfiguration` by setting an application property as we have a custom configuration that sets up the client configuration.

**Information Checklist**
Kindly make sure that you have added all the following information above and checkoff the required fields otherwise we will treat the issuer as an incomplete report
- [x] Bug Description Added
- [x] Repro Steps Added
- [x] Setup information Added

**Comment by joshfree** [comment]
@chenrujun @saragluna could you please take a look?

**Comment by chenrujun** [comment]
Hi, @moarychan , could you please help to investigate this problem?

**Comment by moarychan** [comment]
Hi @spoptchev-extern , thanks for your investigation.


> Expected behavior
> Changing the application-type manually should not cause an exception.

We support two new types(`web_application`,`resource_server`) when the inferred type is `resource_server_with_obo`, only when the scope of configured application type is small than the scope of inferred application type, then the application type is valid,  or else an exception occurs. You can see [the following relationship](https://github.com/Azure/azure-sdk-for-java/tree/main/sdk/spring/azure-spring-boot-starter-active-directory#application-type):

| Has dependency: spring-security-oauth2-client | Has dependency: spring-security-oauth2-resource-server |                  Valid values of application type                                                     | Default value               |
|-----------------------------------------------|--------------------------------------------------------|-------------------------------------------------------------------------------------------------------|-----------------------------|
|                      Yes                      |                          No                            |                       `web_application`                                                               |       `web_application`     |
|                      No                       |                          Yes                           |                       `resource_server`                                                               |       `resource_server`     |
|                      Yes                      |                          Yes                           | `web_application`,`resource_server`,`resource_server_with_obo`, `web_application_and_resource_server` | `resource_server_with_obo`  |

> It would also be great if we could disable AADOAuth2ClientConfiguration by setting an application property as we have a custom configuration that sets up the client configuration.

It may be not a good idea, this change will disable the AAD client(OBO and delegated authentication) feature at the same time All the beans of `AADOAuth2ClientConfiguration ` can be overridden by your owner configuration.

**Comment by moarychan** [comment]
@chenrujun please help to review, thanks.

**Comment by spoptchev-extern** [comment]
Thank you for the answer @moarychan. We now use `web_application_and_resource_server` which does not throw an exception, but the issue with disabling the `AADOAuth2ClientConfiguration` still exists.

We are using `spring-webflux` and made the library work with it (with some workarounds) in version `3.4.0`. When we set `web_application_and_resource_server` in version `3.7.0` the application throws at startup:

```
APPLICATION FAILED TO START
***************************

Description:

The bean 'clientRegistrationRepository', defined in class path resource [org/springframework/boot/autoconfigure/security/oauth2/client/reactive/ReactiveOAuth2ClientConfigurations$ReactiveClientRegistrationRepositoryConfiguration.class], could not be registered. A bean with that name has already been defined in class path resource [com/azure/spring/aad/AADOAuth2ClientConfiguration.class] and overriding is disabled.
```

**Comment by moarychan** [comment]
Hi @spoptchev-extern ,  I mean to use a configuration `MyAADOAuth2ClientConfiguration` similar to [`com.azure.spring.aad.AADOAuth2ClientConfiguration`](https://github.com/Azure/azure-sdk-for-java/blob/4edd7df53b4a2d56aeca13ebf2f6fdb66f6d2d56/sdk/spring/azure-spring-boot/src/main/java/com/azure/spring/aad/AADOAuth2ClientConfiguration.java), and then it will load `MyAADOAuth2ClientConfiguration` first, instead of using `spring.main.allow-bean-definition-overriding=true`, because the beans in `com.azure.spring.aad.AADOAuth2ClientConfiguration` are annotated with `@ConditionalOnMissingBean`,  does this solve your problem?

**Comment by spoptchev-extern** [comment]
Hi @moarychan , we have dropped the library and use the default Spring resource server configuration now. Anyway, thank you for your support.
