### ISSUE TITLE
How to filter results using azure-spring-data-cosmos-core-query Criteria and CriteriaType "ARRAY_CONTAINS"

### ISSUE THREAD

**Issue by rajesh-melige** [Azure/azure-sdk-for-java#23485]
**Is your feature request related to a problem? Please describe.**
I want to filter the result set using azure-spring-data-cosmos-core-query Criteria and CriteriaType "ARRAY_CONTAINS".

I have the Result set structure similar to this:

{
    "id": "UUID",
    "name": "…",
    "emailAddress": "…",
    "version",
    "arrayField": [
        {
            "id": "UUID",
            "status": "active",
	    "name": "abc"
        },
        {
            "id": "UUID",
            "status": "draft",
	    "name": "xyz"
        },
        {
            "id": "UUID",
            "status": "active",
            "name": "qwe"
        },
        …
    ],
    "country": "",
    …
}

I would like to query on arrayField.id which is a unique field.

The implementation for the ARRAY_CONTAINS is **ARRAY_CONTAINS(object.arrayField, { "id": "UUID_value" }, boolean)**, where the boolean value "true" implies to match the partial array and "false" implies otherwise. 

Since I'm using the Criteria to build my query, there is no supported method of getInstance in the Criteria class to set the boolean value for ARRAY_CONTAINS condition.
So, the boolean value is "false" by default and I'm not able to filter the results for partial array match.
Every time the result set is empty because it is matching the entire array not just one field.

**Describe the solution you'd like**
I would like to have an additional boolean field in the Criteria class to set the value for ARRAY_CONTAINS condition.
Also an additional method of getInstance which will accept that boolean value.

This would also need some changes in the azure-spring-data-cosmos-core-generator AbstractQueryGenerator for generating the ARRAY_CONTAINS query.

**Describe alternatives you've considered**

This could be done using the JOINS but then I cannot use the Criteria implementation and also I cannot use SELECT * from root.

I also found a similar issue at https://github.com/Azure/azure-sdk-for-java/issues/16676. But that is restricted to sql query implementation and not using the Criteria class.

**Additional context**

**Information Checklist**
Kindly make sure that you have added all the following information above and checkoff the required fields otherwise we will treat the issuer as an incomplete report
- [x] Description Added
- [x] Expected solution specified

**Comment by joshfree** [comment]
@backwind1233 @yiliuTo could you please follow up with @rajesh-melige on this question?

**Comment by kushagraThapar** [comment]
@mbhaskar  - can you please help on this issue ?

**Comment by rajesh-melige** [comment]
@mbhaskar @kushagraThapar May I know if you have any update on this issue ? We are blocked on this implementation.

**Comment by shitikovegor** [comment]
@mbhaskar @kushagraThapar can you write if you have any updates on this issue?

**Comment by kushagraThapar** [comment]
@shitikovegor - one of the customers is using this as a solution - https://github.com/Azure/azure-sdk-for-java/issues/25628#issuecomment-992101766
Let me know if that helps.

**Comment by shitikovegor** [comment]
@kushagraThapar  everything work with @Query annotation, but I mean this issue is about 'ARRAY_CONTAINS' criteria in method name as keyword

**Comment by kushagraThapar** [comment]
@trande4884  - can you please take a look at this, thanks!

**Comment by trande4884** [comment]
@shitikovegor are you able to post the code snippet of the Criteria you are trying to create with Criteria.getInstance()? This will greatly assist me in debugging this issue.

**Comment by trande4884** [comment]
@shitikovegor per [the documents here](https://docs.microsoft.com/en-us/azure/cosmos-db/sql/sql-query-array-contains), the boolean flag for partial matching only pertains to ARRAY_CONTAINS with objects. Our SDK does not currently support this. Criteria only supports ARRAY_CONTAINS with single property values.
