### ISSUE TITLE
Azure Cosmos Java SDK Patch / Batch / Bulk API review discussion

### ISSUE THREAD

**Issue by kushagraThapar** [Azure/azure-sdk-for-java#23519]
Azure Cosmos Java SDK Patch / Batch / Bulk API review discussion

Here is the API view link - https://apiview.dev/Assemblies/Review/130b70abd19f4b1a865cb638b25d9d1a/5c43b869dd61474ea69093443c611bd3?diffRevisionId=974451ab123247ea8c658e43e2f61be8&doc=False&diffOnly=True

**Comment by lilyjma** [comment]
scheduled for 8/12 2-4pm pst

**Comment by srnagar** [comment]
[Recording](https://msit.microsoftstream.com/video/7aac0840-98dc-981d-f989-f1ebfeeb4951)

**Comment by xinlian12** [comment]
The API review has completed.
