### ISSUE TITLE
Parsing of NSG rules fails with null reference exception in ports or ip list has a comma separated list

### ISSUE THREAD

**Issue by dharshanr** [Azure/azure-sdk-for-java#2355]
The java sdk does not appear to support port or ip fields allowing a comma separated list of entries.
E.g. port: 80,81

The UI supports this - so it should also be separated in the sdk.

**Comment by vhvb1989** [comment]
Hello @dharshanr

I am sorry about you didn't get a sooner answer on this
Do you still need help? Let me know and I would be happy to assist.

Note: As part of repository cleaning effort, this issue will be closed by Sep 20 if no response is received from submitter and/or not further action is required.
