### ISSUE TITLE
[BUG] Fix problems in azure-spring-boot-service reported by sonar

### ISSUE THREAD

**Issue by chenrujun** [Azure/azure-sdk-for-java#23577]
## Context

We use sonar to check the code quality for all Spring Cloud Azure codes. 
 - The sonar setting was put here: https://github.com/Azure/spring-cloud-azure-tools#sonar-analysis
 - The sonar analyze result was here:  https://sonarcloud.io/dashboard?id=stliu_azure-sdk-for-java

## Goal

We should fix the issues in the report and finally make this report success.
Here is the summary report:
https://sonarcloud.io/summary/new_code?id=stliu_azure-sdk-for-java

Our goal is to achieve the following goals:

| Sonar quality check | Goal | Current|
|-----------------------|----------|------|
| Reliability                | 0 bugs | 4 bugs|
|Security |0 vulnerabilities | 0 vulnerabilities |
|Coverage|80% | 67.4%|
|Maintainability |A |A |
|Security Review| 0 security hotspots |1 security hotspots|
|Duplication| 3%| 5.6%|

## Solution

Sonar scan from the above report give us some hints of the code smells and bug issues. Upon the report, we list the issues that must-fix, can be ignored, and need discussion in the following.

### The following issues are must-fix:

1. magic number

2. Use "==" to perform this enum comparison instead of using "equals" 

5. Access scope modifier, for example: protected ctor for abstract class

6. Use the primitive boolean expression here.

7. Add a private constructor to hide the implicit public one for Utility Class
   for example: AzureStorageUtils.java

8.  Either log this exception and handle it, or rethrow it with some contextual information.

9. Complete the task associated to this TODO comment.
   For example: StorageFileResource.java(L220)

10. Code cleaning.

### The following issues need discussion:

Sonar report critical issues for the following code smells:

1. code complexity reduce.
2. deprecation usage of API.
3. This class has 6 parents.
4. Usage of generic wildcard type in return type.
5. Fields in a "Serializable" class should either be transient or serializable. (Security issue)

### The following issues are ignored:
1. Define and throw a dedicated exception instead of using a generic one.

2. magic number 1000 used as 1000 milliseconds, or parameter in Duration.ofMinutes(5);

3. Add a constructor to the class, or provide default values.

**Comment by jialigit** [comment]
> Here is the report: https://sonarcloud.io/dashboard?id=stliu_azure-sdk-for-java
@Ruju Is this included in our CI flow? Or, do we have to manually do it?

**Comment by chenrujun** [comment]
FYI:
About this problem: https://sonarcloud.io/project/security_hotspots?id=stliu_azure-sdk-for-java
I created an issue in spring-security repo: https://github.com/spring-projects/spring-security/issues/11096

**Comment by jialigit** [comment]
For this issue:  we need deprecate this rule. For we do not want to change this.
https://sonarcloud.io/project/issues?resolved=false&types=BUG&sinceLeakPeriod=true&severities=BLOCKER%2CCRITICAL%2CMAJOR%2CMINOR&id=stliu_azure-sdk-for-java

**Comment by yiliuTo** [comment]
Fixed in https://github.com/Azure/azure-sdk-for-java/pull/31166 and https://github.com/Azure/azure-sdk-for-java/pull/31203

**Comment by saragluna** [comment]
@yiliuTo and @chenrujun, it seems like the issue still exists. Please check the [sonar report](https://sonarcloud.io/project/issues?resolved=false&types=BUG&sinceLeakPeriod=true&id=stliu_azure-sdk-for-java).

**Comment by chenrujun** [comment]
Reopen this issue, because the problem still exists:
![image](https://user-images.githubusercontent.com/13167207/194680288-27da56c9-ac78-4b7c-a9c4-08b5772e8245.png)

**Comment by chenrujun** [comment]
Closing in favor of https://github.com/Azure/azure-sdk-for-java/issues/31339 and https://github.com/Azure/azure-sdk-for-java/issues/31340
