### ISSUE TITLE
[FEATURE REQ] Redesign current structure of boms.

### ISSUE THREAD

**Issue by chenrujun** [Azure/azure-sdk-for-java#23579]
Now `azure-spring-boot bom` does not use `azure-sdk-bom`, which could lead to dependency conflicts.
Here is some options I can image:
1. Combine `azure-spring-boot-bom` / `azure-spring-cloud-bom` /  `azure-sdk-bom` into one bom: `azure-sdk-bom`.
2. Import `azure-sdk-bom` in `azure-spring-boot-bom` and `azure-spring-cloud-bom`.

**Comment by saragluna** [comment]
Close this in favor of https://github.com/Azure/azure-sdk-for-java/issues/24812.
