### ISSUE TITLE
Document about Azure Spring Cloud Starter Event Hubs

### ISSUE THREAD

**Issue by yiliuTo** [Azure/azure-sdk-for-java#23589]
The official documentation for [Azure Event Hubs](https://docs.microsoft.com/en-us/azure/developer/java/spring-framework/configure-spring-cloud-stream-binder-java-app-azure-event-hub) only covers **azure-spring-cloud-stream-binder-eventhubs**, which is to introduce how to use the library with Spring Cloud Stream Framework. However, there is another library **azure-spring-cloud-starter-eventhubs** under Azure Spring Cloud libraries for Event Hubs, it provides other features like sending / receiving events to / from Event Hubs and integrating with Spring Integration. We should consider to writing another document for it.

The aim of the doc for **azure-spring-cloud-starter-eventhubs** is to introduce its features and related usage examples, which should contain:
1. Using the starter combined with Spring Integration Framework.
2. Providing simple APIs based on **EventHubOperation** to send / receive events to / from Event Hubs.
3. Provding an annotation of **@AzureMessageListener** which can listen to events from Event Hubs.

**Comment by saragluna** [comment]
Closing this issue now, for we have deprecated this starter, and have the new features in https://aka.ms/spring/docs.
