### ISSUE TITLE
[FEATURE REQ] Provide SecretClient in azure-spring-boot-starter-keyvault-secrets.

### ISSUE THREAD

**Issue by chenrujun** [Azure/azure-sdk-for-java#23583]
This [doc page] says about the module: `Provides Spring value annotation support for integration with Azure Key Vault Secrets.`
We should provide a `SecretClient`  instead of just `load all secrets as Spring properties`.

[doc page]: https://docs.microsoft.com/en-us/azure/developer/java/spring-framework/spring-boot-starters-for-azure

**Comment by saragluna** [comment]
Implemented in this PR https://github.com/Azure/azure-sdk-for-java/pull/23849/files, closing this issue now.
