### ISSUE TITLE
Cannot set ContentKeyPolicyFairPlayRentalAndLeaseKeyType for Fairplay

### ISSUE THREAD

**Issue by m-kumaran** [Azure/azure-sdk-for-java#2358]
First of all, thank you for maintaining the SDK.

**Issue Description:**
In the Java SDK version 0.9.8, there is no way to set    **RentalAndLeaseKeyType** property while creating the OptionConfig 
- method name `FairPlayConfiguration.createSerializedFairPlayOptionConfiguration.`

The .net code has the option:-
```
FairPlayConfiguration = Microsoft.WindowsAzure.MediaServices.Client.FairPlay.FairPlayConfiguration.CreateSerializedFairPlayOptionConfiguration(
            objX509Certificate2,
            pfxPassword,
            pfxPasswordId,
            askId,
            iv, 
            RentalAndLeaseKeyType.PersistentUnlimited,
            0x9999);
```
but the java SDK method has no such signature:-
```
public static String createSerializedFairPlayOptionConfiguration(
          KeyStore keyStore, String pfxPassword, String pfxPasswordKeyId, String askId,
          String contentIv) 
```
Thanks in advance.

**Comment by vhvb1989** [comment]
Hello @m-kumaran

I am sorry about you didn't get a sooner answer on this
Do you still need help? Let me know and I would be happy to assist.

Note: As part of repository cleaning effort, this issue will be closed by Sep 20 if no response is received from submitter and/or not further action is required.

**Comment by m-kumaran** [comment]
Hello @vhvb1989 

Thank you for the response.  Please close this issue, as I solved that issue by upgrading to V3.

Regards,
Kumaran
