### ISSUE TITLE
[BUG] Document problems about azure-spring-boot-starter-keyvault-certificates.

### ISSUE THREAD

**Issue by chenrujun** [Azure/azure-sdk-for-java#23588]
- It can be found as a child node of [Spring Boot in the Spring on Azure page](https://docs.microsoft.com/en-us/azure/developer/java/spring-framework/). However it is not listed in the actual [Spring Boot Starters for Azure page like Secrets](https://docs.microsoft.com/en-us/azure/developer/java/spring-framework/spring-boot-starters-for-azure)

### Tutorial 
- Pretty good up until Spring app creation <-- I'd stick to the specific list of actions/fixes needed for brevity 
- Uses an older beta version (3.0.0-beta.7), instead of the latest (3. 1). 
- Can we use the starter without a Managed Identity? If not, how can users achieve this functionality (using certs for TLS/SSL)? 
- The main class code is missing an import statement 
    ```
    import org.springframework.boot.SpringApplication; 
    ```
- Since we have some shaded dependencies in the Key Vault JCA library used by the Certificates Starter, it's very easy for users to accidentally import classes from those libraries instead of from the ones obtained via Maven. 
- The curl samples for calling the /exit endpoint fail to include the --insecure flag, which is required for them to work in this tutorial. 
### [GitHub README](https://github.com/Azure/azure-sdk-for-java/tree/main/sdk/spring/azure-spring-boot-starter-keyvault-certificates), also found [here](https://docs.microsoft.com/en-us/java/api/overview/azure/spring-boot-starter-keyvault-certificates-readme?view=azure-java-stable). 
- It's good that the README shows the different KeyStore sources that can be used (JRE, specific path, AzureKeyVault, classpath), since the MS Docs tutorial only uses AzureKeyVault. 
- Should we have a tutorial for using a client ID and secret like we do in this README? 
- The code sample for using client-side SSL is slightly different from what the tutorial uses, more specifically when it comes to the use of system properties. 
- Maybe it should be made a little more clear that the property certificates-refresh-interval uses milliseconds. We can add a suffix such as "-in-ms". 
- It's interesting that the samples in the tutorial and the ones in this README use different formats (both valid). For example: 
    ```
    server.port=8443 
    server: 
      port: 8443 
    ```
    We should strive to be consistent even in these minor cases. 
- Explanations about how to read certificates from other places like the a custom directory or the classpath are clear and concise. Good job! 
- It's also good that this document mentions how to configure Spring Cloud Gateway and how to deal with some different error scenarios that can appear. 

### [Sample Project](https://github.com/Azure/azure-sdk-for-java/tree/azure-spring-boot-starter-keyvault-certificates_3.0.1/sdk/spring/azure-spring-boot-samples/azure-spring-boot-sample-keyvault-certificates-server-side) 
- I love that it includes scripts to make user's lives easier. 
- It's cool that it shows how to use either a service principal or a managed identitiy for auth. However, some users do not understand when/where Managed Identity can be used so I would recommend adding a reference to this information. Also, we should probably point them to documentation that shows how to deploy an app on the various resources that support Managed Identity. 
- The sections Examples, Troubleshooting, Next Steps, Run with Maven and Contributing are empty. I know we have some automation requiring they exist, but I wonder if we should instead be a bit more lenient. There are cases where it doesn't make sense to have some of these.

**Comment by chenrujun** [comment]
Add a new problem: The Troubleshooting and Next Steps sections are empty.

**Comment by zhichengliu12581** [comment]
```
Can we use the starter without a Managed Identity? If not, how can users achieve this functionality (using certs for TLS/SSL)?
```
This [Tutorial](https://docs.microsoft.com/en-us/azure/developer/java/spring-framework/configure-spring-boot-starter-java-app-with-azure-key-vault-certificates) is work as a quick start for `azure-spring-boot-starter-keyvault-certificates`. We may need to add a Tutorial for dev guide for using a client ID and secret. I will create a new issue for this question.
