### ISSUE TITLE
[FEATURE REQ] Improve MS docs about spring-cloud-azure-starter-keyvault-secrets

### ISSUE THREAD

**Issue by chenrujun** [Azure/azure-sdk-for-java#23585]
There are some problems about current MS docs of spring-cloud-azure-starter-keyvault-secrets

Refer to this issue to get more information about the problems: https://github.com/MicrosoftDocs/azure-dev-docs-pr/issues/2108

We should fix those problems the improve the MS docs.

**Comment by stliu** [comment]
what's the bug?

I really don't understand what this issue is, is it a bug in our code or docs?

**Comment by chenrujun** [comment]
@stliu , I updated the title and the description.

**Comment by chenrujun** [comment]
Closing this issue, because https://github.com/MicrosoftDocs/azure-dev-docs-pr/issues/2108 already added in to this project: https://github.com/orgs/Azure/projects/94/views/23
