### ISSUE TITLE
Document about Azure Spring Cloud Starter Service Bus

### ISSUE THREAD

**Issue by yiliuTo** [Azure/azure-sdk-for-java#23590]
The official documentation for [Azure Service Bus](https://docs.microsoft.com/en-us/azure/developer/java/spring-framework/configure-spring-cloud-stream-binder-java-app-with-service-bus) only covers **azure-spring-cloud-stream-binder-servicebus-topic** and **azure-spring-cloud-stream-binder-servicebus-queue**, which is to introduce how to use the library with Spring Cloud Stream Framework. However, there is another library **azure-spring-cloud-starter-servicebus** under Azure Spring Cloud libraries for Service Bus, it provides other features like sending / receiving messages to / from Service Bus and integrating with Spring Integration. We should consider to writing another document for it.

The aim of the doc for **azure-spring-cloud-starter-servicebus** is to introduce its features and related usage examples, which should contain:
1. Using the starter combined with Spring Integration Framework.
2. Providing simple APIs based on **ServiceBusTopicOperation** and **ServiceBusQueueOperation** to send / receive messages to / from Service Bus.
3. Provding an annotation of **@AzureMessageListener** which can listen to messages from Service Bus.

**Comment by saragluna** [comment]
Closing this issue now, for we have deprecated this starter, and have the new features in https://aka.ms/spring/docs
