### ISSUE TITLE
Brief Question - Is this scenario possible?

### ISSUE THREAD

**Issue by connor-miller-kr** [Azure/azure-sdk-for-java#23603]
**Query/Question**
I want to know if this scenario is possible via this Azure SDK -

Given a Spring Boot Java app on an Azure App Service with a provisioned Managed Identity, can the Spring Boot app utilise that Managed Identity to connect to a SQL Server + Database (assuming of course that the MI has been given appropriate access)?

If so, is there any documentation on this, if not, is this a planned feature or is it not feasible?

***Why is this not a Bug or a feature Request?***
Purely meant to be a question about existing functionality.

**Comment by stliu** [comment]
https://docs.microsoft.com/en-us/sql/connect/jdbc/connecting-using-azure-active-directory-authentication?view=sql-server-ver15

@connor-miller-kr  would you try this ?
