### ISSUE TITLE
[FEATURE REQ]Place all  azure spring docs in one place

### ISSUE THREAD

**Issue by backwind1233** [Azure/azure-sdk-for-java#23618]
**Is your feature request related to a problem? Please describe.**
Now each azure spring starter has it's own readme and changelog doc file.

**Describe the solution you'd like**

There is a doc folder to host all azure spring's docs.
There is a web server to host all docs, users can access these docs through a url.

ref：[spring-cloud-aws](https://wiki.dianpingoa.com/bin/view/Main/WebHome)

**Describe alternatives you've considered**

**Additional context**

**Information Checklist**
- [ ] Make a template about readme.
  - [ ] it should contains how to create project with spring initializr

**Comment by saragluna** [comment]
Closing this now for it's now in https://microsoft.github.io/spring-cloud-azure/docs/4.0.0-beta.2/reference/html/index.html.

**Comment by saragluna** [comment]
@backwind1233, could you take a look at this issue to see whether it's implemented and can be closed now, please reopen it if it's not.
