### ISSUE TITLE
[Search] Server failed to response search requests against China cloud and UsGov

### ISSUE THREAD

**Issue by hongli750210** [Azure/azure-sdk-for-java#23646]
We are running live Tests against other clouds like US Gov and Azure China Cloud. The goal is to check whether new azure sdk package work with other clouds or not.

**Error Description:**
The test about search service the request failed. The Error Message as follow:
![image](https://user-images.githubusercontent.com/74638143/129685488-3e8b5265-f369-4d11-b29d-da73c3bf652c.png)

**Error Track:**
Detail [Code Link:](https://github.com/Azure/azure-sdk-for-java/blob/main/sdk/search/test-resources.json#L12)
![image](https://user-images.githubusercontent.com/74638143/129688626-6a9b0d1c-8a39-4821-b2fc-b875d13ba160.png)

The exception above throws by Method `TestHelper_setupSharedIndex`.

**Expected Behavior**
The expected return value of `searchEndpointSuffix` and `storageEndpointSuffix`.
UsGov:
- searchEndpointSuffix: search.azure.us
- storageEndpointSuffix: core.usgovcloudapi.net

China:
- searchEndpointSuffix: search.azure.cn
- storageEndpointSuffix: core.chinacloudapi.cn 

@scottaddie , @joshfree , @kyle-patterson , @tg-msft, @alzimmermsft  and @benbp for notification.

**Comment by v-xuto** [comment]
@benbp - Any ideas?

**Comment by benbp** [comment]
@v-xuto I've updated the `ArmTemplateParameters` in the China and UsGov cloud [subscription configurations](https://dev.azure.com/azure-sdk/internal/_wiki/wikis/internal.wiki/389/Configuring-Tests?anchor=subscriptionconfiguration-schema) to add `searchEndpointSuffix`. These tests should work now, let me know if you have any issues.

In the future, for new services that have a suffix defined in the arm template, let me know and I can update the configuration. For example, here is what is currently included for UsGov:

```
    "ArmTemplateParameters": {
        "azureAuthorityHost": "https://login.microsoftonline.us/",
        "keyVaultDomainSuffix": ".vault.usgovcloudapi.net",
        "keyVaultEndpointSuffix": ".vault.usgovcloudapi.net",
        "keyVaultSku": "standard",
        "azConfigEndpointSuffix": ".azconfig.azure.us",
        "cognitiveServicesEndpointSuffix": ".cognitiveservices.azure.us",
        "containerRegistryEndpointSuffix": ".azurecr.us",
        "storageEndpointSuffix": "core.usgovcloudapi.net",
        "searchEndpointSuffix": "search.azure.us",
        "enableStorageVersioning": false,
        "formRecognizerLocation": "usgovvirginia"
    }
```

And for China:

```
    "ArmTemplateParameters": {
        "azureAuthorityHost": "https://login.chinacloudapi.cn/",
        "keyVaultDomainSuffix": ".vault.azure.cn",
        "keyVaultEndpointSuffix": ".vault.azure.cn",
        "keyVaultSku": "standard",
        "azConfigEndpointSuffix": ".azconfig.azure.cn",
        "cognitiveServicesEndpointSuffix": ".cognitiveservices.azure.cn",
        "containerRegistryEndpointSuffix": ".azurecr.cn",
        "storageEndpointSuffix": "core.chinacloudapi.cn",
        "searchEndpointSuffix": "search.azure.cn",
        "enableStorageVersioning": false,
        "textAnalyticsSku": "S"
    }
```

**Comment by hongli750210** [comment]
Search service test case could work in UsGov and China Cloud. Thanks for update the `ArmTemplateParameters`.

**Comment by hongli750210** [comment]
@benbp 
Thank you very much for your previous correction. I found the same problem in `ServiceBus` and `EventHubs`. Could you please add the endpoint suffix of these two services in `ArmTemplateParameters` of UsGov/China cloud, thanks.

**Comment by benbp** [comment]
@hongli19750210 updated. The eventhub endpoint is the same, so I only set `serviceBusEndpointSuffix`.

gov:
  - key: `serviceBusEndpointSuffix` value: `.servicebus.usgovcloudapi.net`

cn:
- key: `serviceBusEndpointSuffix` value: `.servicebus.chinacloudapi.cn`
