### ISSUE TITLE
Azurre sdk java for logic app management api - 1.10.0 beta versiob[BUG]

### ISSUE THREAD

**Issue by suvvi** [Azure/azure-sdk-for-java#23649]
**Describe the bug**
Getting below error while creating logic app with integration account name specified like below

"integrationAccount": {
        "id": "/subscriptions/xxxx/resourceGroups/rgxx/providers/Microsoft.Logic/integrationAccounts/namex,
        "name": "xx",
        "type": "Microsoft.Logic/integrationAccounts"
    }

***Exception or Stack Trace***
The integration account id must be provided in the 'integrationAccount' property of the workflow

**To Reproduce**

***Code Snippet***
Add the code snippet that causes the issue.

**Expected behavior**

**Screenshots**

**Setup (please complete the following information):**
 - IDE: [e.g. IntelliJ]
 - Library/Libraries: [e.g. com.azure:azure-core:1.16.0 (groupId:artifactId:version)]
 - Java version: [e.g. 8] 
 - App Server/Environment: [e.g. Tomcat, WildFly, Azure Function, Apache Spark, Databricks, IDE plugin or anything special]
 - Frameworks: [e.g. Spring Boot, Micronaut, Quarkus, etc] 

If you suspect a dependency version mismatch (e.g. you see `NoClassDefFoundError`, `NoSuchMethodError` or similar), please provide
- dependency tree (`mvn dependency:tree -Dverbose`)
  
**Additional context**

**Information Checklist**
Kindly make sure that you have added all the following information above and checkoff the required fields otherwise we will treat the issuer as an incomplete report
- [ ] Bug Description Added
- [ ] Repro Steps Added
- [ ] Setup information Added

**Comment by joshfree** [comment]
Related issues in other public repos https://github.com/Azure/azure-powershell/issues/5233 and https://github.com/Azure/azure-powershell/issues/8410

@lilyjma can you please help ensure the service team follows up?  It looks like there hasn't been traction on the other open github issues, above.  Thanks!
