### ISSUE TITLE
[BUG] List on azure-mgmt-appservice does not paginate

### ISSUE THREAD

**Issue by renutz** [Azure/azure-sdk-for-java#23684]
**Describe the bug**
When using latest sdk - 1.41.2 - and trying to list all webapps, it just lists the first 20.

**To Reproduce**
PagedList<WebApp> webapps = azure.webApps().list();

If I use the REST URL it brings all webapps:

https://management.azure.com/subscriptions/{subscriptionId}/providers/Microsoft.Web/sites?api-version=2019-08-01

Does anybody know of possible issues? Or if I missing something in pagination (PagedList works fine with other components)

**Comment by joshfree** [comment]
@weidongxu-microsoft could you please follow up with @renutz?

**Comment by weidongxu-microsoft** [comment]
@renutz 
The `WebApps.list()` only return web app (i.e., type contains "app" or "api"). For function app, go for `FunctionApps.list()`.

If you just want to show all of them, try
```
azure.webApps().manager().inner().webApps().list();
```

If you still have trouble, would you enable logging (e.g. https://github.com/Azure/azure-libraries-for-java/blob/master/azure-samples/src/main/java/com/microsoft/azure/management/appservice/samples/ManageLinuxWebAppBasic.java#L179-L183) and let us know the service response (be careful not to include authorization token).

**Comment by weidongxu-microsoft** [comment]
Also, it would be easier for you to use latest SDK at https://aka.ms/azsdk/java/mgmt, if you are new to it, or have a small project that is easy to migrate.
