### ISSUE TITLE
Make azure-spring-boot-starter-servicebus-jms follow design doc.

### ISSUE THREAD

**Issue by chenrujun** [Azure/azure-sdk-for-java#23688]
- [x] Read and update https://github.com/Azure/azure-sdk-for-java/issues/23402
 - [x] Read and update [Spring Cloud Azure design]
 - [x] Confirm all tasks finished by these check list:
    - [x] starter module should only contain pom. It should not contain java code / file like `cosmos.enable.config` / readme / changelog. For example: [azure-spring-boot-starter-keyvault-certificates] contains java code. 
    - [x] starter module's com should only contain required dependencies. For example, [spring-cloud-gcp-starter-storage] only contains dependencies, but [azure-spring-cloud-starter-cache] contains `build` segment.
    - [x] It should be only one autoconfigure module. azure-spring-boot and azure-spring-cloud-autoconfig should combine into one module.
    - [x] It should be multiple level support when developing a starter. For example, there should be a module named azure-spring-security-oauth2-client instead of putting the logic in azure-spring-boot.
    - [x] #24354
    - [x] #24360

[Spring Cloud Azure design]: https://github.com/Azure/azure-sdk-for-java/wiki/Spring-Cloud-Azure-design

**Comment by yiliuTo** [comment]
Close this issue for design doc has been finished: https://github.com/Azure/azure-sdk-for-java/wiki/Spring-Cloud-for-Azure-Messaging-design

**Comment by yiliuTo** [comment]
Close this issue for it has been finished.
