### ISSUE TITLE
Write design doc for azure-spring-integration

### ISSUE THREAD

**Issue by chenrujun** [Azure/azure-sdk-for-java#23690]
Parent issue: https://github.com/Azure/azure-sdk-for-java/issues/23402
Sample design doc: https://github.com/Azure/azure-sdk-for-java/wiki/Spring:-Design-doc-of-level-1-azure-spring-cloud-starter

**Comment by yiliuTo** [comment]
Close this issue for design doc has been finished: https://github.com/Azure/azure-sdk-for-java/wiki/Spring-Cloud-for-Azure-Messaging-design
