### ISSUE TITLE
[QUERY] How to implement proper paging API using azure spring data cosmos SDK?

### ISSUE THREAD

**Issue by zhoujia1974** [Azure/azure-sdk-for-java#23700]
**Query/Question**
We need to develop a paging query REST API to support a UI datagrid component. The datagrid shows data in page of 100 at a time. User can click next/pre page button to show the next or previous page. They can also enter a specific page # to jump to the corresponding page of data. 
We have looked at the paging query support from azure spring data cosmos sdk and documentation. But it doesn't clearly indicate how we can use it to achieve our requirement. 

We define the following query method in Repository class.

` Page<DataEntity> findByPartitionKey(
      String partitionKey,
      Pageable pageable);`

We then make the query in domain service like below.

` Sort sort = Sort.by(Order.asc("key"));
    CosmosPageRequest pageRequest =
        CosmosPageRequest.of(page, pageSize, null, sort);
    Page<DataEntity> page =
        repository.findByPartitionKey(partitionKey, pageRequest);`

But this query always return the first page no matter which page number we provide.
We found the following documentation and example from Microsoft page. 

> Supports Spring Data Pageable, Slice and Sort.
Based on available RUs on the database account, cosmosDB can return items less than or equal to the requested size.
Due to this variable number of returned items in every iteration, user should not rely on the totalPageSize, and instead iterating over pageable should be done in this way.

`private List<User> getUsersByLastName(String lastName, int pageSize) {

    final CosmosPageRequest pageRequest = new CosmosPageRequest(0, pageSize, null);
    Slice<User> slice = repository.getUsersByLastName(lastName, pageRequest);
    List<User> content = slice.getContent();
    while (slice.hasNext()) {
        Pageable nextPageable = slice.nextPageable();
        slice = repository.getUsersByLastName(lastName, nextPageable);
        content.addAll(slice.getContent());
    }
    return content;
}`

From this and other information I collected, it seems to me: First, the paging API doesn't guarantee to return the required page size of documents. I need to iterate over nextPageable until I get enough number of data for requested page size. Second, I can't request any page without starting from page 0 and then use slice.nextPageable() to query the next page. This doesn't work well with our ui and API requirement, since we need to get a fixed size of page of data and we need to be able to get any page of data without needing to request page sequentially. 

Do you have any suggestion how we can implement our specific paging API requirement?

***Why is this not a Bug or a feature Request?***
A clear explanation of why is this not a bug or a feature request?

**Setup (please complete the following information if applicable):**
 - OS: Windows or Linux
 - IDE: Eclipse
 - Library/Libraries: com.azure.spring:azure-spring-boot-starter-cosmos:3.6.0
 
 **Information Checklist**
 Kindly make sure that you have added all the following information above and checkoff the required fields otherwise we will treat the issuer as an incomplete report
- [X ] Query Added
- [ X] Setup information Added

**Comment by joshfree** [comment]
@backwind1233 could you please follow up with @zhoujia1974?

**Comment by backwind1233** [comment]
Hi @kushagraThapar, could you please follow up with this?

**Comment by zhoujia1974** [comment]
@kushagraThapar How do I get a continuation token back when I use OFFSET LIMIT? My custom query method is like below. Do I need to change the return type to Page<SomeEntity> and also add a Pageable parameter like the custom query method 2? But if I do use a pageable together with OFFSET LIMIT query, will the pageable conflict with OFFSET LIMIT? I would assume Cosmos SDK will insert some query fragment based on the pageable parameter and the query fragment may interfere with OFFSET LIMIT?

Before paging.
  `@Query(
      "SELECT * FROM c WHERE c.partitionKey = @partitionKey ORDER BY c.key OFFSET @offset LIMIT @limit")
  List<SomeEntity> findLineItems(
      @Param("partitionKey") String partitionKey,
      @Param("offset") int offset,
      @Param("limit") int limit);`

After paging.
`@Query(
      "SELECT * FROM c WHERE c.partitionKey = @partitionKey ORDER BY c.key OFFSET @offset LIMIT @limit")
  Page<SomeEntity> findLineItems(
      @Param("partitionKey") String partitionKey,
      @Param("offset") int offset,
      @Param("limit") int limit,
      Pageable pageable);`

**Comment by kushagraThapar** [comment]
@zhoujia1974 - To get the continuation token and rely on OFFSET and LIMIT queries, its better to use the Cosmos Java SDK to handle continuation token. 
Instead of using spring query annotation, it is best to use Java SDK query APIs, which can help you retrieve continuation token. You can get `cosmosClient` through `applicationContext` in spring cosmos, and then call the Java SDK query APIs with the OFFSET and LIMIT query and use the continuation token returned in the response. 

Spring Data doesn't have a good pagination mechanism as I explained above. So your best bet might be to use the Java SDK query API.

**Comment by trande4884** [comment]
@zhoujia1974 we have recently improved on this area with a few PR's but I believe this one will help you the most and will go out with our next release: https://github.com/Azure/azure-sdk-for-java/pull/30276
You should be able to see from the newly added unit tests how to achieve your goals. You can jump to the next/pre page via continuation token usage and you can now jump to any page you choose.
