### ISSUE TITLE
Unable to use custom script extension part of availability zone in eastus2 after upgrading Java sdk to 1.14.0

### ISSUE THREAD

**Issue by prashannamsft** [Azure/azure-sdk-for-java#2370]
When I run custom script extension to VMs part of availability zone in eastus2 region after upgrading to Java SDK 1.14.0 I keep getting the following error:

"does not support availability zones at location '<null>'. :: null" 

Is there a limitation with this SDK that might prevent me from running the using custom script extension using latest SDK version?

Please advice.

**Comment by vhvb1989** [comment]
Hello @prashannamsft

I am sorry about you didn't get a sooner answer on this
Do you still need help? Let me know and I would be happy to assist.

Note: As part of repository cleaning effort, this issue will be closed by Sep 20 if no response is received from submitter and/or not further action is required.
