### ISSUE TITLE
[FEATURE REQ] Add sample: realize the function of azure-spring-boot-starter-active-directory-b2c only through spring security

### ISSUE THREAD

**Issue by zhichengliu12581** [Azure/azure-sdk-for-java#23713]
Related issue: https://github.com/Azure/azure-sdk-for-java/issues/23545
We can implement the functions provided in azure-spring-boot-starter-active-directory-b2c only through spring security. We need to add the corresponding sample to tell the user how to configure the code of related functions.
  1. Spring Security can [support multi Tenant](https://github.com/spring-projects/spring-security/pull/7733#issuecomment-567518233), similar to the [sample](https://github.com/spring-projects/spring-security-samples/tree/main/servlet/spring-boot/java/oauth2/resource-server/multi-tenancy) provided by spring:
  2. Spring security can [customize the verification of audience](https://github.com/spring-projects/spring-security/issues/8334#issuecomment-609997301).
   3. Users can determine the default client through spring configuration
   4. Users can configure the information of each client by themselves

**Comment by chenrujun** [comment]
Closing this PR, use this issue to track this task: https://github.com/Azure-Samples/spring-boot-application-with-azure-active-directory/issues/2
