### ISSUE TITLE
Incorporate Monitor Query Beta 4 UX study feedback

### ISSUE THREAD

**Issue by scottaddie** [Azure/azure-sdk-for-java#23739]
Tracking issue to update the next release to incorporate Beta 4 UX study feedback.
/cc: @joshfree

Action items from 8/24 meeting:

- [x] _README_ file changes:
  - [x] Mention the `TenantId` column as a way to see the workspace identifier in a multi-workspace Logs query result.
  - [x] Add samples for the `listMetricDefinitions` and `listMetricNamespaces` methods of `MetricsQueryClient`.
  - [x] Add a link to the Azure Core `PagedIterable` documentation, where appropriate.
  - [x] Update the file's **Handle metrics response** section so that the casing of property names in the object graph representation match the casing used in the `MetricsQueryResult` code.
  - [x] Document the ordering of the results when querying multiple metric names. For example, if I query "SuccessfulCalls" and another metric name, which order do those results appear in?
- [x] Eliminate the need to call `getName().getValue()` to retrieve a metric definition name as a `String` type. The call to `getName()` should be sufficient.
- [x] Improve the JavaDocs for the `context` parameter used in the `MetricsQueryClient` methods, such as `queryWithResponse`. Nobody knew what the parameter represented.
- [x] In the `Metric` class, update the `metricsName` parameter to `metricName` (singular instead of plural).
- [x] Add a `getMetricByName` method to the `MetricsQueryResult` class. This proposed method would be an alternative to the `getMetrics().get(0)` call in the following screenshot:
  
  ![image](https://user-images.githubusercontent.com/10702007/131400138-526d55e7-5c3c-4e3a-ba67-42f2a3d48e54.png)

**Comment by srnagar** [comment]
https://github.com/Azure/azure-sdk-for-java/pull/24042
