### ISSUE TITLE
Change in ChangeFeedProcessor to accept  customer ChangeFeedObserver

### ISSUE THREAD

**Issue by simplynaveen20** [Azure/azure-sdk-for-java#23738]
In Encryption change feed processor , we have to do the blocking call on consumer in encryption project https://github.com/Azure/azure-sdk-for-java/pull/23634
Once we have new design in ChangeFeedProcessor  we can avoid blocking call

**Comment by TheovanKraay** [comment]
@xinlian12 can this be closed?

**Comment by xinlian12** [comment]
@TheovanKraay this is still active
