### ISSUE TITLE
Refactor Spring Cloud for Azure testing projects structure

### ISSUE THREAD

**Issue by saragluna** [Azure/azure-sdk-for-java#23773]
In the azure-spring project, we have many `azure-spring-boot-test-xxx` and `azure-spring-cloud-test-xxx` projects, the number of testing projects will explode if we keep creating new testing projects whenever we come up with a new user scenario. We should refactor the test projects' structure by moving all the integration tests to the to-be-tested artifacts. For example, the testing code in `azure-spring-cloud-stream-test-eventhubs` should be moved to `azure-spring-cloud-stream-binder-eventhubs`. And we should re-examine our testing classes, is it truly an integration test scenario, or should a unit test suffice? 

### Solution

Each test scenario code will be in the corresponding feature module instead of in a separate module.

* Move the current IT class into the corresponding feature module, remove all the azure-spring-boot-test-xxx and azure-spring-cloud-test-xxx  modules

* Refactor the integration test case code and follow the Spring style to achieve, such as [redis health indicator](https://github.com/spring-projects/spring-boot/blob/49baacbc1cb02a59efce1fe1698166de92d41d67/spring-boot-project/spring-boot-actuator/src/test/java/org/springframework/boot/actuate/redis/RedisHealthIndicatorTests.java)

**Comment by stliu** [comment]
I think we should first analysis what scenarios the test module is covering and if that make sense to use integration test or UT is enough.

**Comment by moarychan** [comment]
Update progress:
Refactor some testcases PR has been merged, all the test modules will be removed in another PR later.

**Comment by Netyyyy** [comment]
https://github.com/Azure/azure-sdk-for-java/pull/26158 PR merged ,close now
