### ISSUE TITLE
[FEATURE REQ] Be able to disable Azure Spring package

### ISSUE THREAD

**Issue by cccs-cat001** [Azure/azure-sdk-for-java#23782]
**Is your feature request related to a problem? Please describe.**
We're building our app to use Azure OAuth. Problem is we want to be robust and have our app also not use Azure OAuth. It's impossible to include the required libraries for other OAuth providers when the Azure OAuth packages will make the app fail to start since it doesn't see the required properties. It also sucks for local development where we don't want to have to deal with signing in to Azure and all that, we just want a dummy user that has access to everything. Including the Azure spring libraries in our pom makes that impossible.

**Describe the solution you'd like**
I would like to see a property that can be toggled to enable/disable the use of Azure OAuth. 

**Describe alternatives you've considered**
The only alternative I can think of is to not use the azure libraries. Would make OAuth harder for us, but it would make plugging in different OAuth providers a LOT easier

**Additional context**

**Information Checklist**
Kindly make sure that you have added all the following information above and checkoff the required fields otherwise we will treat the issuer as an incomplete report
- [x] Description Added
- [x] Expected solution specified

**Comment by chenrujun** [comment]
Related issue: https://github.com/Azure/azure-sdk-for-java/issues/23710

**Comment by chenrujun** [comment]
Closing this issue, because it has already been finished in version 4.0.0.

@saragluna , correct me if I have some misunderstanding.

**Comment by saragluna** [comment]
Please check #24260 for the release of our next major version.
