### ISSUE TITLE
azure-spring-boot-starter-storage changes default rest template message converter to xml

### ISSUE THREAD

**Issue by lucascrandle** [Azure/azure-sdk-for-java#23794]
When adding the azure storage starter to a spring boot project it changes the default http message converter.

Steps to reproduce: 

Initializer: https://start.spring.io/#!type=maven-project&language=java&platformVersion=2.5.4&packaging=jar&jvmVersion=11&groupId=com.example&artifactId=demo&name=demo&description=Demo%20project%20for%20Spring%20Boot&packageName=com.example.demo&dependencies=web,azure-storage

Then send a simple rest template post with a java POJO object:
```
        RestTemplate rt = new RestTemplate();
        HttpStatus status = rt.exchange(endpointURL, HttpMethod.POST, new HttpEntity<>(new PoJoObject("John Doe")), Void.class).getStatusCode();
```

The message will be sent encoded for azure queues like this:
```
{
        "$content-type": "application/xml; charset=UTF-8",
        "$content": "PFBvSm9PYmplY3Q+PG5hbWU+Sm9obiBEb2U8L25hbWU+PC9Qb0pvT2JqZWN0Pg=="
}
```
I was expecting the default json behavior like this:
```
{
        "name": "John Doe"
}
```

I don't think this is a good idea to change the global behavior in spring.

**Comment by backwind1233** [comment]
@lucascrandle thank you for your feedback, but I didn't reproduce your issue, could you please give me a mini sample to help reproduce the issue?

**Comment by lucascrandle** [comment]
[demo.zip](https://github.com/Azure/azure-sdk-for-java/files/7085488/demo.zip)
Here's a demo based on the spring initializer and an exchange call with a basic java pojo.

**Comment by backwind1233** [comment]
Hi @lucascrandle, I think you need to specify the content-type of the request,
as you can see in the picture below, the converter's order is defined in RestTemplate.java,
if azure-spring-boot-starter-storage is imported, the MappingJackson2XmlHttpMessageConverter will be added, and it's order is before MappingJackson2HttpMessageConverter, so if you doesn't specify the content-type in headers, MappingJackson2XmlHttpMessageConverter will convert message first.
![image](https://user-images.githubusercontent.com/4465723/132134868-2c3df7fe-fb0c-4b31-8eb7-c957ed8a35de.png)

**Comment by lucascrandle** [comment]
@backwind1233 Yup that was my workaround. Adding a HttpHeaders object to the exchange call and setting content time to json.


```
this.headers.setContentType(MediaType.APPLICATION_JSON);
HttpStatus status = rt.exchange(endpointURL, HttpMethod.POST, new HttpEntity<>(new PoJoObject("John Doe"), this.headers), Void.class).getStatusCode();
```

It took me an hour or two to figure this out though, and didn't expect that an imported package would change the default resttemplate behavior on me. So I'm suggesting that this azure package instead sets the convert at the call so that it doesn't disrupt other code.

**Comment by backwind1233** [comment]
> @backwind1233 Yup that was my workaround. Adding a HttpHeaders object to the exchange call and setting content time to json.
> 
> ```
> this.headers.setContentType(MediaType.APPLICATION_JSON);
> HttpStatus status = rt.exchange(endpointURL, HttpMethod.POST, new HttpEntity<>(new PoJoObject("John Doe"), this.headers), Void.class).getStatusCode();
> ```
> 
> It took me an hour or two to figure this out though, and didn't expect that an imported package would change the default resttemplate behavior on me. So I'm suggesting that this azure package instead sets the convert at the call so that it doesn't disrupt other code.


@lucascrandle 😞 I can understand, the default RestTemplate is predefined in it's body, the imported package has no way to change it, I think what you mean is the imported package trigged some logic in the RestTemplate, which really disrupt the code.😂
Not azure-spring-boot-starter-storage, any imported packages depend on jackson-dataformat-xml will cause the same effect. If we really want to solve this problem, I think we should ask spring side to change the messageConverter's order in RestTemplate.

**Comment by lucascrandle** [comment]
> > @backwind1233 Yup that was my workaround. Adding a HttpHeaders object to the exchange call and setting content time to json.
> > ```
> > this.headers.setContentType(MediaType.APPLICATION_JSON);
> > HttpStatus status = rt.exchange(endpointURL, HttpMethod.POST, new HttpEntity<>(new PoJoObject("John Doe"), this.headers), Void.class).getStatusCode();
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > It took me an hour or two to figure this out though, and didn't expect that an imported package would change the default resttemplate behavior on me. So I'm suggesting that this azure package instead sets the convert at the call so that it doesn't disrupt other code.
> 
> @lucascrandle 😞 I can understand, the default RestTemplate is predefined in it's body, the imported package has no way to change it, I think what you mean is the imported package trigged some logic in the RestTemplate, which really disrupt the code.😂
> Not azure-spring-boot-starter-storage, any imported packages depend on jackson-dataformat-xml will cause the same effect. If we really want to solve this problem, I think we should ask spring side to change the messageConverter's order in RestTemplate.

Ahh I see what you are saying now it's the Resttemplate looking for present converters to determine the default. I'll go ahead and close this issue I agree this would be on Spring's side. Thanks for taking the time to explain and respond!
