### ISSUE TITLE
[BUG] Spring conditional annotation @ConditionalOnProperty prevents creating of bean in-casse Azure key vault secrets name is in camelCase, with Groovy framework.

### ISSUE THREAD

**Issue by gsbindhani** [Azure/azure-sdk-for-java#23815]
**Environment**
Groovy: 2.5.10
spring-boot-starter: 2.5.2
azure-spring-boot-starter-keyvault-secrets: 3.6.0
 
**Summary**
Spring conditional annotation @ConditionalOnProperty not satisfying the condition when the secret is in camel case**(**testing-propInCamelCase**)** in the azure key vault.

Whereas able to read the properties using **@Value** annotation.

**To Reproduce**
Create a secret as **testing-propInCamelCase** in the azure key vault with any value.

Try to create a spring bean using the property using the **@ConditionalOnProperty**, in the below, you will see the first bean is not getting created whereas the second one is.

 ```groovy
	@Bean
	@ConditionalOnProperty(name = "testing.propInCamelCase") //Reading in camelCase
	public String testingConditionalBeanWithCamelCase() {
		//Bean is not getting created, whereas it should. Here is the issue
		logger.info("Bean instantiated from prop(camelCase): testing.propInCamelCase");
		return "done";
	}
	
	@Bean
	@ConditionalOnProperty(name = "testing.propincamelcase") //Reading in lowercase
	public String testingConditionalBeanWithLowerCase() {
		//Bean is getting created
		logger.info("Bean instantiated from prop(lowerCase): testing.propincamelcase");
		return "done";
	}
```
**Expected behavior**
As Azure is lowering the case of the properties/secrets, the conditional property should work for both cases as it's working in the below case while reading the secrets with @Value annotation. In both cases, the value is loading from the secrets.
```groovy
	@Value("${testing.propInCamelCase:}") //Reading in camelCase
	String propInCamelCase; //Accessing the value
	
	@Value("${testing.propincamelcase:}") //Reading in lowercase
	String propInLowerCase; //Accessing the value
```

Is there any reason it is working while reading the properties not while using the conditional on a property?

**Comment by joshfree** [comment]
@chenrujun could you please follow up with @gsbindhani ?

**Comment by chenrujun** [comment]
It's a new problem that different to all other known problems.
@Netyyyy , please help to investigate it.

**Comment by hui1110** [comment]
Hi @gsbindhani, thanks for bringing this up. For your question, you can set another entry `azure.keyvault.case-sensitive-keys=true` in the properties file,  to be case sensitive for secret names. We made changes in 4. x to the BOM, the artifact you are using, and the configuration properties, after version GA, we recommend that you can try our latest version.

**Comment by hui1110** [comment]
Hi @gsbindhani, thanks for bringing this up. For your question, in the version you are using, you can set another entry azure.keyvault.case-sensitive-keys=true in the properties file, by case-sensitive secret names to can meet your expectations. In version 4. x without GA, this [pr ](https://github.com/Azure/azure-sdk-for-java/pull/27827)fixes the problem. After 4. x version GA, we recommend you to try our latest version.

**Comment by hui1110** [comment]
Close this issue, fix it in https://github.com/Azure/azure-sdk-for-java/pull/27827.
