### ISSUE TITLE
[QUERY] Azure-spring-data-cosmos: trying to delete an item from the container

### ISSUE THREAD

**Issue by simplyanything** [Azure/azure-sdk-for-java#23816]
**Query/Question**
We're trying to delete an item from our container. We're making use of `ReactiveCosmosRepository`.
 
Despite making use of the `deleteById`, `delete` and `deleteAll` methods (shown below), the entry is still there in Cosmos (visible using data explorer). Also, when we try to use `findById` after executing any of the former delete operations, the object is still present in the database. This is a SQL database container.
Just to be clear: we are able to insert entries in our database successfully & retrieve them.

**Edit: after lots of debugging, we ended up switching back to the non-reactive cosmos repository. The deletion works fine then... Why doesn't the code below work (using the reactive repo)?**

Model/POJO:
```
@Getter
@Setter
@ToString
@Container(containerName = "user", timeToLive = 300)
public class User implements Serializable {
    @Id
    @PartitionKey
    @JsonView(UserView.Public.class)
    private String id;
}
```

UserRepository:
```
@Repository
public interface UserRepository extends ReactiveCosmosRepository<User, String> {
}
```

Service:
```
// This doesn't work
public Mono<Void> deleteUser(String id) {
    return userRepository.deleteById(id, new PartitionKey(id));
}

// Neither does this:
public Mono<Void> deleteUsingUserObject(String id) {
    User user = userRepository.findById(id).block();
    return userRepository.delete(user);
}

// Neither does this work:
public Mono<Void> deleteAll() {
   return userRepository.deleteAll();
}

```

***Why is this not a Bug or a feature Request?***
Based on https://github.com/Azure/azure-sdk-for-java/issues/20727, we understood that an item should be deleted using deleteById(id, partitionkey)... Did we miss anything else?

**Setup (please complete the following information if applicable):**
 - OS: Windows
 - IDE: IntelliJ
 - Library/Libraries: `com.azure:azure.spring.data.cosmos:3.4.0` & `org.springframework.boot:spring-boot-starter-web:2.3.8.RELEASE` & `io.projectreactor.netty:reactor-netty:0.9.15.RELEASE`
 
 **Information Checklist**
 Kindly make sure that you have added all the following information above and checkoff the required fields otherwise we will treat the issuer as an incomplete report
- [X] Query Added
- [X] Setup information Added

**Comment by joshfree** [comment]
@backwind1233 could you please follow up with @simplyanything?

**Comment by kushagraThapar** [comment]
@simplyanything  - are you subscribing to the operation of `delete()` ?
You need to subscribe to the operation so that you can actually execute the operation, like you are doing with findById in your above code snippet. 

// Neither does this:
public Mono<Void> deleteUsingUserObject(String id) {
    // The block here needs to be done on delete operation as well, so that API gets executed. 
    User user = userRepository.findById(id).block();
    return userRepository.delete(user);
}

**Comment by simplyanything** [comment]
Hi @kushagraThapar , thanks for the help.
Yes, we've also tried the following (this should work right?):

`userRepository.deleteById(id, new PartitionKey(id)).block();`

However, now that we have switched back to the non-reactive repository, it is working fine.

**Comment by kushagraThapar** [comment]
Yes, that should work. We use it all the time in our tests. 
https://github.com/Azure/azure-sdk-for-java/blob/main/sdk/cosmos/azure-spring-data-cosmos-test/src/test/java/com/azure/spring/data/cosmos/repository/integration/ReactiveCourseRepositoryIT.java#L168

You can see it in our tests. However, if sync cosmos repository is working fine, I think that is the way to go if your use case really doesn't require the use of reactive code.
