### ISSUE TITLE
“ADJUST_DATES_TO_CONTEXT_TIME_ZONE” from com.fasterxml.jackson

### ISSUE THREAD

**Issue by rjardines83** [Azure/azure-sdk-for-java#2382]
Hello folks.
I just change my code from version 1.2.0 to version 1.15.0 this is my code:

 azure.deployments().define(deploymentName)
                        .withExistingResourceGroup(resourceGroupName)
                        .withTemplate(templateJson)
                        .withParameters(parametersJson)
                        .withMode(DeploymentMode.INCREMENTAL)
                        .create();

I got the error NoSuchFieldError “ADJUST_DATES_TO_CONTEXT_TIME_ZONE”  from com.fasterxml.jackson

Azure sdk 1.15.1
com.fasterxml.jackson 2.7.3

**Comment by alanAraujoSousa** [comment]
Me too, when I'm listing the virtual machines.
SDK 1.16

**Comment by rodrigonw** [comment]
define your resource pool region
YourVirtualMachinesByLocation.put(Region.US_EAST, 12);

Sample
https://github.com/Azure/azure-docs-sdk-java/blob/master/docs-ref-conceptual/java-sdk-virtual-machines-in-parallel.md

**Comment by vhvb1989** [comment]
Hello @rjardines83 

I am sorry about you didn't get a sooner answer on this
Do you still need help on this? Let me know and I would be happy to help.

Note: As part of repository cleaning effort, this issue will be closed by **Nov 11** if no response is received from submitter and/or not further action is required.
