### ISSUE TITLE
Have separate tests.yml file for older Service Bus and Event Hubs packages

### ISSUE THREAD

**Issue by ramya-rao-a** [Azure/azure-sdk-for-java#23826]
Today, there is a single tests.yml file under the below folders for Event Hubs and Service Bus
- https://github.com/Azure/azure-sdk-for-java/tree/main/sdk/eventhubs
- https://github.com/Azure/azure-sdk-for-java/tree/main/sdk/servicebus

But these folders house packages that are owned by different teams. Due to the current set up all test failure notifications regardless of package ownership get emailed to the a single set of people.

In .NET, this was resolved by having a separate set of test pipeline. See
- https://github.com/Azure/azure-sdk-for-net/blob/main/sdk/eventhub/tests.data.yml
- https://github.com/Azure/azure-sdk-for-net/blob/main/sdk/servicebus/tests.data.yml

Can we have something similar in the Java repo, so the right owners as updated in https://github.com/Azure/azure-sdk-for-java/pull/23824 get the test failure notifications for the packages they own?

**Comment by ramya-rao-a** [comment]
cc @joshfree, @srnagar, @hallipr, @weshaggard

**Comment by joshfree** [comment]
@ki1729 could you pick this one up?

**Comment by ramya-rao-a** [comment]
Looks like for the CI that runs on PRs, we already have two separate ones. See https://github.com/Azure/azure-sdk-for-java/blob/main/sdk/servicebus/ci.yml vs https://github.com/Azure/azure-sdk-for-java/blob/main/sdk/servicebus/ci.data.yml

So, is it just a matter of creating a tests.data.yml? 
@weshaggard?

**Comment by ramya-rao-a** [comment]
Digging a little deeper, I don't see live test runs for the older packages at all... 
I see the release pipelines, the PR pipeline, but not the nightly test pipelines

**Comment by weshaggard** [comment]
If they don't have any live tests then it doesn't matter but if they do we would need to create a tests.data.yml file to separate them as needed.

**Comment by ramya-rao-a** [comment]
It is highly unlikely that there are no live tests for these packages...

**Comment by weshaggard** [comment]
Should we close this issue then or is there something else you wanted to accomplish with it?

**Comment by ramya-rao-a** [comment]
Lets keep it open for @conniey or @srnagar to respond whether or not there are live tests for these packages.

**Comment by conniey** [comment]
There are no live tests running for Event Hubs (Track 1) at the moment. And I'm fairly confident they are not enabled for Service Bus either.

**Comment by ramya-rao-a** [comment]
@conniey Is the case that the tests do exist but there is no pipeline running them or that there are no live tests at all?

**Comment by conniey** [comment]
> @conniey Is the case that the tests do exist but there is no pipeline running them or that there are no live tests at all?

The tests exist but there is no pipeline running them.

**Comment by ramya-rao-a** [comment]
Ok, in that case, lets use this issue to track the need to run the live tests

**Comment by ki1729** [comment]
This ticket is no longer tracking the task that needs to be done here. Created #33790 to track it to completion.
