### ISSUE TITLE
Fix consistently failing azure-monitor-opentelemetry-exporter tests

### ISSUE THREAD

**Issue by joshfree** [Azure/azure-sdk-for-java#23830]
The following Monitor Query SDK tests are failing.  This should be fixed before the October release:

https://dev.azure.com/azure-sdk/internal/_build/results?buildId=1071063&view=ms.vss-test-web.build-test-results-tab

https://dev.azure.com/azure-sdk/internal/_test/analytics?definitionId=2389&contextType=build
- producerTest
- setConfigurationTest
- testExportRequestDataWithAuthentication
- testSendPartialInvalidRequestData
- testSendPartialInvalidRequestData
- testSendRequestData
- testSendRequestData

**Comment by pallavit** [comment]
@joshfree All these failures are from the azure-monitor-opentelemetry-exporter library which share the same pipeline as azure-monitor-query. These should not be tracked with monitor-query epic.

**Comment by lmolkova** [comment]
this has been recently fixed in https://github.com/Azure/azure-sdk-for-java/pull/26082 

https://dev.azure.com/azure-sdk/internal/_test/analytics?definitionId=3751&contextType=build
