### ISSUE TITLE
[FEATURE REQ] Calculate MD5 hash on blocks uploaded with uploadFromFile method

### ISSUE THREAD

**Issue by shawnweisfeld** [Azure/azure-sdk-for-java#23837]
When you use uploadFromFile the SDK should calculate the MD5 Hash of each block to ensure that the upload happens correctly since the storage Put Block API supports this check. 

Looking at the “uploadFromFile” method. . . 
https://github.com/Azure/azure-sdk-for-java/blob/4fb5f7eda4a18eed7b998e77f5d1d809fe16207f/sdk/storage/azure-storage-blob/src/main/java/com/azure/storage/blob/BlobClient.java#L197

it calls
https://github.com/Azure/azure-sdk-for-java/blob/4fb5f7eda4a18eed7b998e77f5d1d809fe16207f/sdk/storage/azure-storage-blob/src/main/java/com/azure/storage/blob/BlobClient.java#L212

that calls
https://github.com/Azure/azure-sdk-for-java/blob/4fb5f7eda4a18eed7b998e77f5d1d809fe16207f/sdk/storage/azure-storage-blob/src/main/java/com/azure/storage/blob/BlobClient.java#L244

that calls
https://github.com/Azure/azure-sdk-for-java/blob/4fb5f7eda4a18eed7b998e77f5d1d809fe16207f/sdk/storage/azure-storage-blob/src/main/java/com/azure/storage/blob/BlobAsyncClient.java#L565

that calls 
https://github.com/Azure/azure-sdk-for-java/blob/4fb5f7eda4a18eed7b998e77f5d1d809fe16207f/sdk/storage/azure-storage-blob/src/main/java/com/azure/storage/blob/BlobAsyncClient.java#L613

that calls stageblockwithresponse here
https://github.com/Azure/azure-sdk-for-java/blob/4fb5f7eda4a18eed7b998e77f5d1d809fe16207f/sdk/storage/azure-storage-blob/src/main/java/com/azure/storage/blob/BlobAsyncClient.java#L634

that method is outlined here. . . 
https://docs.microsoft.com/en-us/java/api/com.azure.storage.blob.specialized.blockblobclient.stageblockwithresponse?view=azure-java-stable

But you can see we pass null in for the contentMd5 byte[].

That makes me believe that we are not calculating md5 hashes on the blocks before we send them over the wire. 

However, in this doc we state, "hashes for the individual blocks were validated when each was uploaded."
https://docs.microsoft.com/en-us/java/api/com.azure.storage.blob.models.blobhttpheaders?view=azure-java-stable&viewFallbackFrom=azure-java-stable%E2%80%93

**Comment by jasonstack** [comment]
@rickle-msft are you still working on this issue?

**Comment by rickle-msft** [comment]
@jasonstack this is still in our backlog. We haven't begun working on it yet, but there are some conversations around checksumming for requests going on right now. Is this a feature that would be helpful for you?
