### ISSUE TITLE
Event Hubs Sample issue

### ISSUE THREAD

**Issue by hongli750210** [Azure/azure-sdk-for-java#23844]
1. 
Section [Link1](https://github.com/Azure/azure-sdk-for-java/blob/main/sdk/eventhubs/azure-messaging-eventhubs/src/samples/java/com/azure/messaging/eventhubs/ConsumeEvents.java#L98), [link2](https://github.com/Azure/azure-sdk-for-java/blob/main/sdk/eventhubs/azure-messaging-eventhubs/src/samples/java/com/azure/messaging/eventhubs/ConsumeEventsFromKnownSequenceNumberPosition.java#L82), [link3:](https://github.com/Azure/azure-sdk-for-java/blob/main/sdk/eventhubs/azure-messaging-eventhubs/src/samples/java/com/azure/messaging/eventhubs/PublishEventsCustomEndpoint.java#L53)
![image](https://user-images.githubusercontent.com/74638143/131434576-047e841d-ac5a-47e0-8179-49f8bec1aa9e.png)

Reason:
	Required type: Iterable<com.azure.messaging.eventhubs.EventData>
	Provided: EventData

Suggestion: 
Change to `Collections.singletonList(new EventData(body.getBytes(UTF_8)))`

2.
Section [Link;](https://github.com/Azure/azure-sdk-for-java/blob/main/sdk/eventhubs/azure-messaging-eventhubs/src/samples/java/com/azure/messaging/eventhubs/EventHubsJavaDocCodeSamples.java#L634)
![image](https://user-images.githubusercontent.com/74638143/131434735-9c92697d-a05d-4741-a403-a0da52ef37c6.png)

Reason:
	 java.lang.NullPointerException: 'checkpointStore' cannot be null

Suggestion: 
Add parameter setting  `.checkpointStore(new SampleCheckpointStore())`, 
Code change to
```
EventProcessorClient eventProcessorClient = new EventProcessorClientBuilder()
    .connectionString(connectionString)
    .processEvent(eventContext -> {
        System.out.printf("Partition id = %s and sequence number of event = %s%n",
            eventContext.getPartitionContext().getPartitionId(),
            eventContext.getEventData().getSequenceNumber());
	})
        .processError(errorContext -> {
            System.out.printf("Error occurred in partition processor for partition %s, %s%n",
                errorContext.getPartitionContext().getPartitionId(),
                errorContext.getThrowable());
        })
        .consumerGroup("consumer-group")
        .checkpointStore(new SampleCheckpointStore())
        .buildEventProcessorClient();
``` 

@scottaddie, @joshfree, @lilyjma, @ramya-rao-a, @anuchandy for notification.

**Comment by ramya-rao-a** [comment]
@v-xuto Please go ahead and send the PR. We can discuss further in the PR itself
