### ISSUE TITLE
Monitor Query Readme isssue

### ISSUE THREAD

**Issue by hongli750210** [Azure/azure-sdk-for-java#23846]
1. 
Section [Link:](https://github.com/Azure/azure-sdk-for-java/tree/main/sdk/monitor/azure-monitor-query#examples)
![image](https://user-images.githubusercontent.com/74638143/131436737-ddd450ac-cd8b-4f22-a06a-3e59537e70df.png)

Reason:
Clicking on these links does not respond.

Suggestion: 
	1. Update link to ` #get-logs-for-a-query` 
	2. Update link to `#get-logs-for-a-batch-of-queries`
	3. Update link to `#get-logs-for-a-query-with-server-timeout`
	4. Update link to `#get-logs-from-multiple-workspaces`

2.
Section [Link:](https://github.com/Azure/azure-sdk-for-java/tree/main/sdk/monitor/azure-monitor-query#examples)
![image](https://user-images.githubusercontent.com/74638143/131437094-a2270dc5-dd9c-4e21-a426-fd17e4b67dc1.png)
![image](https://user-images.githubusercontent.com/74638143/131436990-b4eaea7c-b7aa-4d1b-9fa9-25a890dc0ebb.png)

Reason:
Missing title `Get logs for a query and read the response as a model type` in examples summary.

Suggestion: 
Add title `Get logs for a query and read the response as a model type` in examples summary.

@scottaddie, @joshfree, @srnagar, @pallavit for notification.

**Comment by srnagar** [comment]
All reported issues with README are addressed.
