### ISSUE TITLE
Azure Spring Cloud Storage Readme issus

### ISSUE THREAD

**Issue by hongli750210** [Azure/azure-sdk-for-java#23843]
1.
Section [Link:](https://github.com/Azure/azure-sdk-for-java/tree/main/sdk/spring/azure-spring-cloud-storage#more-sample-code)
![image](https://user-images.githubusercontent.com/74638143/131434360-36c2ce8c-12d9-4b97-b5b5-ea5ef2c9f8e7.png)

Suggestion: 
Add link for [sample]: https://github.com/Azure-Samples/azure-spring-boot-samples/tree/tag_azure-spring-boot_3.6.0/storage/azure-spring-boot-sample-storage-resource

@scottaddie,  @joshfree, @kyle-patterson,  @tg-msft, @alzimmermsft for notification.

**Comment by backwind1233** [comment]
Hi @hongli750210, thanks for your feedback, I will fix it today.
