### ISSUE TITLE
Spring Webflux controller not return response

### ISSUE THREAD

**Issue by kuroshan** [Azure/azure-sdk-for-java#23857]
executing the following endpoint that invokes ServiceBusSenderAsyncClient.sendMessage, registers the message in serviceBus, but the controller does not return the response "create message". The execution does not propagate the return of sendMessage in the flow.

any suggestion

@RestController
@RequestMapping("/producer")
public class ProducerController {

  @Autowired
  private ServiceBusSenderAsyncClient client;

  @GetMapping
  @ResponseStatus(HttpStatus.CREATED)
  public Mono<String> test() {
    ServiceBusMessage message = new ServiceBusMessage("test");
    return client.sendMessage(message)
        .flatMap(aVoid -> Mono.just("create message"));
  }

}

**Comment by joshfree** [comment]
@yiliuTo could you please follow up with @kuroshan?

**Comment by yiliuTo** [comment]
Hi @kuroshan , ServiceBusSenderAsyncClient#sendMessage method returns a `Mono<Void>`, so you could use `then` instead of `flatMap`, for example
```
    @GetMapping
    @ResponseStatus(HttpStatus.CREATED)
    public Mono test() {
        ServiceBusMessage message = new ServiceBusMessage("test");
        return client.sendMessage(message)
                     .then(Mono.just("create message"));
```
