### ISSUE TITLE
[BUG] please reply on old Service Bus bug

### ISSUE THREAD

**Issue by koziolmail** [Azure/azure-sdk-for-java#23858]
I reported bug on 6th of August, please reply
https://github.com/Azure/azure-sdk-for-java/issues/23398

**Comment by joshfree** [comment]
Hi @koziolmail sorry for the delay in getting a response.  @ki1729 will take a look at the logs posted in https://github.com/Azure/azure-sdk-for-java/issues/23398 as soon as he's available.  Please note that customers with an [Azure support plan](https://azure.microsoft.com/support/options/) can open an [Azure support ticket](https://azure.microsoft.com/support/create-ticket/).  We recommend this option if your problem requires immediate attention.

More details are available in the support.md: https://github.com/Azure/azure-sdk-for-java/edit/main/SUPPORT.md

Thank you

**Comment by ki1729** [comment]
Addressed the original issue
