### ISSUE TITLE
[FEATURE REQ] Health Indicator for CosmosDB

### ISSUE THREAD

**Issue by Manuel-Moya** [Azure/azure-sdk-for-java#23860]
**Is your feature request related to a problem? Please describe.**
I am not sure if there is a health indicator for the cosmosdb client.

**Describe the solution you'd like**
I would like to have a health indicator under actuator for the cosmosdb client.

**Information Checklist**
Kindly make sure that you have added all the following information above and checkoff the required fields otherwise we will treat the issuer as an incomplete report
- [X] Description Added
- [ ] Expected solution specified

**Comment by joshfree** [comment]
Hi @Manuel-Moya someone from the `Cosmos` SDK team will follow up with your request shortly.  Thanks

**Comment by backwind1233** [comment]
Hi @Manuel-Moya, you can try our cosmos [starter](https://search.maven.org/artifact/com.azure.spring/azure-spring-boot-starter-cosmos/3.8.0/jar) which has implemented health indicator, you may check it [here](https://github.com/Azure/azure-sdk-for-java/blob/main/sdk/spring/azure-spring-boot/src/main/java/com/azure/spring/autoconfigure/cosmos/CosmosHealthIndicator.java).

```
<dependency>
  <groupId>com.azure.spring</groupId>
  <artifactId>azure-spring-boot-starter-cosmos</artifactId>
  <version>3.8.0</version>
</dependency>
```

**Comment by Manuel-Moya** [comment]
> Hi @Manuel-Moya, you can try our cosmos [starter](https://search.maven.org/artifact/com.azure.spring/azure-spring-boot-starter-cosmos/3.8.0/jar) which has implemented health indicator, you may check it [here](https://github.com/Azure/azure-sdk-for-java/blob/main/sdk/spring/azure-spring-boot/src/main/java/com/azure/spring/autoconfigure/cosmos/CosmosHealthIndicator.java).
> 
> ```
> <dependency>
>   <groupId>com.azure.spring</groupId>
>   <artifactId>azure-spring-boot-starter-cosmos</artifactId>
>   <version>3.8.0</version>
> </dependency>
> ```

Could it be used with azure-spring-data-cosmos 3.10?

**Comment by backwind1233** [comment]
> > Hi @Manuel-Moya, you can try our cosmos [starter](https://search.maven.org/artifact/com.azure.spring/azure-spring-boot-starter-cosmos/3.8.0/jar) which has implemented health indicator, you may check it [here](https://github.com/Azure/azure-sdk-for-java/blob/main/sdk/spring/azure-spring-boot/src/main/java/com/azure/spring/autoconfigure/cosmos/CosmosHealthIndicator.java?rgh-link-date=2021-09-06T09%3A17%3A07Z).
> > ```
> > <dependency>
> >   <groupId>com.azure.spring</groupId>
> >   <artifactId>azure-spring-boot-starter-cosmos</artifactId>
> >   <version>3.8.0</version>
> > </dependency>
> > ```
> 
> Could it be used with azure-spring-data-cosmos 3.10?

@Manuel-Moya yes, as you can see [here](https://search.maven.org/artifact/com.azure.spring/azure-spring-boot-starter-cosmos/3.8.0/jar),it work with azure-spring-data-cosmos 3.10
![image](https://user-images.githubusercontent.com/4465723/132367940-3d70d929-be6d-4e6b-a615-5102d09385aa.png)
