### ISSUE TITLE
[FEATURE REQ] Support for batch-consumers in Azure Spring Cloud Event Hub binders

### ISSUE THREAD

**Issue by yiliuTo** [Azure/azure-sdk-for-java#23880]
According to Spring Cloud Stream's documentation, a binder implementation [may support batch consumers](https://docs.spring.io/spring-cloud-stream/docs/3.1.2/reference/html/spring-cloud-stream.html#_batch_consumers). Currently Azure Spring Cloud Event Hubs binder does not support it. 

### Kafka binder reference
- Referring to Kafka binder's batch-consumer feature, it supports configuration to specify the batch-message polling size, measurement covers 3 types: message number/ bytes/time, and its configuration is as max.poll.records, fetch.min.bytes, fetch.max.wait.ms.

- Kafka binder supports acking batched messages by batch. Ref: https://cloud.spring.io/spring-cloud-stream-binder-kafka/spring-cloud-stream-binder-kafka.html#kafka-consumer-properties

### Azure Event Hubs batch consuming reference
- azure-messaging-eventhubs provides the [batch-consuming API](https://github.com/Azure/azure-sdk-for-java/blob/103036860b4361a89e88e74175576995f1f52218/sdk/eventhubs/azure-messaging-eventhubs/src/main/java/com/azure/messaging/eventhubs/EventProcessorClientBuilder.java#L455) by specifying event numbers in a batch and time duration for a batch
- [sample](https://github.com/Azure/azure-sdk-for-java/blob/103036860b4361a89e88e74175576995f1f52218/sdk/eventhubs/azure-messaging-eventhubs/src/samples/java/com/azure/messaging/eventhubs/EventProcessorClientWithBatchReceiveSample.java) of using azure-messaging-eventhubs to consume in batches

#### Configuration options
- A switch to enable batch mode: **spring.cloud.azure.eventhub.bindings.<binding-name>.consumer.batch-mode=true**
- Two parameters to specify the batch size: 
**spring.cloud.azure.eventhub.bindings.<binding-name>.consumer.max-batch-size**: The maximum number of events that will be in the batch list when consumer callback is invoked.
**spring.cloud.azure.eventhub.bindings.<binding-name>.consumer.max-wait-time**: The max time duration to wait to receive a batch of events upto the max batch size (optional)
- Two checkpointing mode supporting batch-consuming: 
**spring.cloud.azure.eventhub.bindings.<binding-name>.consumer.checkpoint-mode**=BATCH / MANUAL
BATCH: auto checkpoint the whole batch of events once it is received by the binder
MANUAL: user manually checkpoints messages when they handle the whole batch of events

#### Format of received message batches
Consumer function will accept a Spring Message which contains all events within the batch.
1. Message header
   - partition id
   - checkpointer
   - aggregated eventhubs headers with values as a list
2. Message payload
   - A Spring message with the payload as a list of EventData payload.
3. Supported scenerios
   ```
    @Bean
    public Consumer<List<String>> consume() {
        return list -> list.forEach(event -> LOGGER.info("New event received: '{}'",event));
    }
    @Bean
    public Consumer<Message<List<String>>> consume() {
        return message -> {
            for (int i = 0; i < message.getPayload().size(); i++) {
                LOGGER.info("New message received: '{}', partition key: {}, sequence number: {}, offset: {}, enqueued time: {}",
                    message.getPayload().get(i),
                    ((List<Object>) message.getHeaders().get(EventHubHeaders.PARTITION_KEY)).get(i),
                    ((List<Object>) message.getHeaders().get(EventHubHeaders.SEQUENCE_NUMBER)).get(i),
                    ((List<Object>) message.getHeaders().get(EventHubHeaders.OFFSET)).get(i),
                    ((List<Object>) message.getHeaders().get(EventHubHeaders.ENQUEUED_TIME)).get(i));
            }
        
            Checkpointer checkpointer = (Checkpointer) message.getHeaders().get(CHECKPOINTER);
            checkpointer.success()
                        .doOnSuccess(success -> LOGGER.info("Message '{}' successfully checkpointed", message.getPayload()))
                        .doOnError(error -> LOGGER.error("Exception found", error))
                        .subscribe();
        };
    }
    @Bean
    public Function<List<Person>, Person> findFirstPerson() {
        return persons -> persons.get(0);
    }
    @Bean
    public Function<Message<List<Person>>, Person> findFirstPerson() {
        return persons -> persons.getPayload().get(0);
    }
   ```
### Implemention details
1. A class of **BatchConfig** to describe the batch configuration options which is stored in EventHubOperation.
2. A class of **BatchCheckpointManager** to handle auto checkpointing in batches.
3. Update **EventHubMessageChannelBinder** to collect batch configurations and config EventHubOperation.
3. Update **EventHubProcessor** by adding an API of onMessages to register batch operations.
4. Update **DefaultEventHubClientFactory** to register batch handler when batch mode is enabled.

**Comment by yiliuTo** [comment]
Reopen this for we have to implement it on branch 4.0

**Comment by jialigit** [comment]
merged
