### ISSUE TITLE
Transition JavaDoc code snippets to JDK18 code snippets feature

### ISSUE THREAD

**Issue by JonathanGiles** [Azure/azure-sdk-for-java#23915]
[JEP 413](https://openjdk.java.net/jeps/413) is adding code snippet functionality directly into JavaDoc. This feature is targeted to JDK 18 (so early 2022). We should have a plan to transition all of our code snippets from the existing doclet to use the new functionality in JDK 18 ASAP, as the codesnippet doclet we use is fragile and doesn't work well on many JDK releases.

Ideally we would create a script that would transform all JavaDoc code snippets into the new format, so that we may do this all in one big push, and at the same time drop our doclet dependency.

**Comment by alzimmermsft** [comment]
Closing as this is the same as #24343 and that one has a better description
