### ISSUE TITLE
[FEATURE REQ] azure-storage-blob-nio: path consistency between nio and blob clients

### ISSUE THREAD

**Issue by ejschoen** [Azure/azure-sdk-for-java#23929]
**Is your feature request related to a problem? Please describe.**
Thanks for creating an NIO wrapper to Azure storage blobs.  For applications that have to handle NIO-level access to other cloud provider blob/bucket implementations, the Azure-specific code would be easier to implement if the interface were more like one of the other cloud blob NIO wrappers.  Moveover, where dropping into the BlobClient-level API is required, it would be easier if there were path syntax consistency between com.azure.storage.blob.nio and com.azure.storage.blob.

In particular: 

1.  com.azure.storage.blob.nio appears to require the application to [pre-enumerate the containers](https://azuresdkdocs.blob.core.windows.net/$web/java/azure-storage-blob-nio/12.0.0-beta.8/index.html) to be used with the NIO file system. This is not always feasible.
2. com.azure.storage.blob.nio requires that [a path to a file](https://azuresdkdocs.blob.core.windows.net/$web/java/azure-storage-blob-nio/12.0.0-beta.8/index.html) specify the container name ending with a :, whereas [com.azure.storage.blob](https://docs.microsoft.com/en-us/java/api/overview/azure/storage-blob-readme?view=azure-java-stable#resource-uri-syntax) does not.
 
**Describe the solution you'd like**
1. Interpret the first component of the path of an azb URL as the container name, without requiring that the component end in a colon. For example: azb://myaccount.blob.core.windows.net/mycontainer/path/to/file.ext
2. Drop the requirement to pre-enumerate the file stores, i.e., containers, to be accessed when creating the Azure NIO file system provider.  

**Describe alternatives you've considered**
[The S3 NIO implementation](https://github.com/Upplication/Amazon-S3-FileSystem-NIO2) is similar to the Azure NIO implementation, wherein sservice endpoints are specified as the file URI's host, buckets (i.e., containers) are specified as the first component of the file URI's path, but does not require the container name to end in a colon, and does not require the application to pre-enumerate containers to be accessed.

[The Google NIO implementation](https://github.com/googleapis/java-storage-nio) is slightly different than the S3 NIO implementation, in that the hostname of the file URI is the bucket (container), and the service endpoint is not part of the file URI.  But like S3, it does not require the containers to be accessed be pre-enumerated.

**Information Checklist**
Kindly make sure that you have added all the following information above and checkoff the required fields otherwise we will treat the issuer as an incomplete report
- [x] Description Added
- [x] Expected solution specified

**Comment by rickle-msft** [comment]
Hi, @ejschoen. Thank you for your interest in using our NIO implementation and for making these requests.

I believe we already have in the plan to add an option which skips the container enumeration at the beginning. We enumerate as a sanity check on opening the FileSystem in case the account hasn't been setup correctly. It should hopefully give a more intelligible error at a reasonable point in the application rather than something obfuscated later down the road. That said, it is true that certain credentials such as sas tokens may not allow for this operation. Would it be sufficient for you if we added an appropriately named configuration option that would allow for skipping this check and allow you to go straight to reading and writing files?

Your other request is a bit trickier as it is fairly foundational that a container maps to a file store (think C: drive on Windows), and we had to pick some scheme for distinguishing an absolute path from a relative path. Linux interprets a path as an absolute path if it begins with a '/', but we opted to go for the windows approach of the path starting with the file store name and also aligned with the file store naming convention. Can you please describe what about this behavior is troublesome for your application and perhaps we can find another way to address your concerns?

**Comment by ejschoen** [comment]
Thanks.  

1.  Yes, a configuration option that removes the need to pre-enumerate containers would be helpful.
2. I might not fully understand the syntax for NIO paths, because the documentation never actually gives an example.  In fact, it took quite a bit of experimentation and source code reading to figure it out.  Am I correct that the expected format is azb://my-storage-account.blob.core.windows.net/my-container:/path/to/file.ext?  If so, is azb://my-storage-account.blob.core.windows.net/path/to/file.ext a correct path, also (e.g., a path to a file in the first container in the container list given to the new file system provider call?  If so, I understand the issue, but if not, then it seems there is a bit of redundant coding to the names, because a the first element of a path is implicitly the container, so why also need the :?  In addition, a URL to a blob is of the form https://my-storage-account.blob.core.windows.net/my-container/path/to/file.ext, and converting that to an NIO URL seems like it should be a simple matter of changing https: to azb:.

**Comment by rickle-msft** [comment]
Can you tell me which documentation you were looking at to try to find this? We've tried to be thorough in our documentation of this project, but that could be an oversight. Perhaps I can give an example in AzurePath docs? We certainly appreciate the effort you put in to look into this behavior, but please also feel free to reach out for questions like this if something is unclear.

A full URI within this NIO context will have the format: "azb://mycontainer:/path/to/blob?endpoint=<endpoint>". This would fully identify the provider (azb/azure), account (filesystem), container (file store), and blob (file). Working with just a Path will look like "mycontainer:/path/to/file". This is meant to be analogous to Windows style "mydrive:\path\to\file". 

One option I see here adding a method that can take in a URI that points to a blob and converting it to a URI or Path object that references the same resource using Azure NIO's naming scheme. Would that be helpful to you at all?

**Comment by ejschoen** [comment]
Ah... so you just told me something I hadn't figured out.  I hadn't realized that mycontainer:/path/to/file is a legal Path syntax for Azure NIO.  But now I understand why pre-enumerating containers would be necessary for that to work, and I fully understand how coming from a Windows perspective would make this desirable.  

Searching the web for Java NIO azure led me to:
https://docs.microsoft.com/en-us/java/api/overview/azure/storage-blob-nio-readme?view=azure-java-preview

If you read this page with no prior knowledge of the implementation, I don't know if you could figure out the above.  If you allow azb://account/container:/path/to/file to work in cases where container is not pre-enumerated, then that works for me.

Have a function to convert Blob-level path syntax to NIO level path syntax would be handy, but mainly the issue for me was not reading anywhere that the : was required in the path for the container.

**Comment by rickle-msft** [comment]
@ejschoen Sorry for the delay here. I am getting around to addressing these things, and if my memory serves there are three parts of this issue:
1. Update documentation to specify the URI format
2. Add a method to convert from a blob URL into an AzurePath object
3. Allow for skipping the container check

**Comment by ejschoen** [comment]
Yes, those would certainly be helpful and would reduce the amount of special purpose code around NIO operations on specifically Azure paths.  Thanks!
