### ISSUE TITLE
Delete un-supported AAD features.

### ISSUE THREAD

**Issue by chenrujun** [Azure/azure-sdk-for-java#23922]
Parent issue: #23710

Delete these features of AAD in azure-spring-boot-starter-active-directory:

1. group-name based access control. Discussed with AAD developers, they think that group-name should not used to authorize, because group-name can be changed in Azure AD. We should use [Role-based access control (RBAC)] instead.
2. group-id based access control. group-id is not human understandable when develop web-application. We should use [Role-based access control (RBAC)] instead.
3. AADAuthenticationFilter and AADAppRoleStatelessAuthenticationFilter. spring-security-oauth2-resource-server has provided resource-server feature, we should delete our resource-server implementation. The filter implementation was first add in  microsoft/azure-spring-boot#97 It's on 2017-08-07. At that time, there is no [spring-security-oauth2-resource-server]. 

[spring-security-oauth2-resource-server]: https://repo1.maven.org/maven2/org/springframework/security/spring-security-oauth2-resource-server/
[Role-based access control (RBAC)]: https://docs.microsoft.com/en-us/azure/active-directory/develop/custom-rbac-for-developers

**Comment by stliu** [comment]
we need to add this into the migration guide, would you please create one issue to track this?

**Comment by chenrujun** [comment]
@stliu 
I created an issue: https://github.com/Azure/azure-sdk-for-java/issues/23940

**Comment by chenrujun** [comment]
Closing this issue because related PR has been merged.
