### ISSUE TITLE
Drive Spring Cloud for Azure 4.0 project 

### ISSUE THREAD

**Issue by backwind1233** [Azure/azure-sdk-for-java#23921]
This issue is used to drive the project of Spring Cloud for Azure 4.0:
care for the planning,tracking the progress, coordinate with relevant staff, make sure the progress of the project is under expectation.

 - [ ] https://github.com/Azure/azure-sdk-for-java/issues/23920
 - [ ] https://github.com/Azure/azure-sdk-for-java/issues/23925
 - [ ] https://github.com/Azure/azure-sdk-for-java/issues/24260
 - [ ] Spring Cloud for Azure 4.0 GA

**Comment by chenrujun** [comment]
Closing this issue. we will use this issue to track all tasks: https://github.com/Azure/azure-sdk-for-java/issues/23402

**Comment by chenrujun** [comment]
Closing this issue. we will use this issue to track all tasks: #23402
