### ISSUE TITLE
Split spring cloud actuator module into a standalone module

### ISSUE THREAD

**Issue by chenrujun** [Azure/azure-sdk-for-java#23930]
Parent task: https://github.com/Azure/azure-sdk-for-java/issues/23925

Design doc: https://github.com/Azure/azure-sdk-for-java/wiki/Spring-Cloud-Azure-design#222-spring-cloud-azure-modules-relationship

**Comment by chenrujun** [comment]
Hi, @saragluna .
1. FYI: I created this issuse.
2. Is it OK to assign this issue to you?

**Comment by saragluna** [comment]
Resolved in #24309.
