### ISSUE TITLE
Java Billing-resource-manager doesn't not work and consumption-resource-manager too

### ISSUE THREAD

**Issue by KononikhinDanila** [Azure/azure-sdk-for-java#23943]
I'm trying to get my account billings via Java and I used sample from azure documentation
 https://docs.microsoft.com/en-us/java/api/overview/azure/resourcemanager-billing-readme?view=azure-java-preview 
But, this solution seems not working, because I see this picture in debug mode:
![first](https://user-images.githubusercontent.com/79186147/132349028-9b1c0329-d40e-4bcc-804d-b7b0f2a5bae0.jpg)
All entities in the object f are null and innerClient throws this exception : 
`Method threw 'com.azure.core.http.rest.MissingRequiredAnnotationException' exception. Cannot evaluate com.azure.resourcemanager.billing.implementation.$Proxy5.toString().`

Then I tried to use Consumption librariry to get billing data and got exact the same situation:
https://docs.microsoft.com/en-us/java/api/overview/azure/resourcemanager-consumption-readme?view=azure-java-preview
![second](https://user-images.githubusercontent.com/79186147/132349098-df1534a1-36e6-47f9-bb84-6a219e1c2e43.jpg)
All entities show null and elements from innerObject throw this exception:
`Method threw 'com.azure.core.http.rest.MissingRequiredAnnotationException' exception. Cannot evaluate com.azure.resourcemanager.consumption.implementation.$Proxy14.toString()`
My pom file:
```
<dependencies>
    <dependency>
        <groupId>com.azure.resourcemanager</groupId>
        <artifactId>azure-resourcemanager-consumption</artifactId>
        <version>1.0.0-beta.2</version>
    </dependency>
    <!-- https://mvnrepository.com/artifact/com.azure/azure-identity -->
    <dependency>
        <groupId>com.azure</groupId>
        <artifactId>azure-identity</artifactId>
        <version>1.3.5</version>
    </dependency>
    <!-- https://mvnrepository.com/artifact/com.azure/azure-core-http-netty -->
    <dependency>
        <groupId>com.azure</groupId>
        <artifactId>azure-core-http-netty</artifactId>
        <version>1.10.0</version>
    </dependency>
</dependencies>
```

Any ideas how to fix it? Or what I'm doing wrong?

**Comment by joshfree** [comment]
Hi @KononikhinDanila thank you for filing this github issue.  Someone from the ARM SDK team will follow up with you shortly.

/cc @weidongxu-microsoft

**Comment by weidongxu-microsoft** [comment]
@KononikhinDanila

Please call something within the client. The client is lazy initialization, until you call something, it's object will be null.

E.g. sample for consumption lib https://docs.microsoft.com/en-us/java/api/overview/azure/resourcemanager-consumption-readme?view=azure-java-preview#examples
