### ISSUE TITLE
Track windowTimeout progress with reactor-team / investigate workaround for OverflowException

### ISSUE THREAD

**Issue by anuchandy** [Azure/azure-sdk-for-java#23950]
Currently, the EH API that receives a batch of events with a timeout uses Reactor `windowTimeout` operator. This operator lacks the support for backpressure, leading CX to run into OverflowException. Refer to [this](https://github.com/reactor/reactor-core/issues/1099) issue for details.

Creating this to track the progress of the above Reactor work item/investigation on any workaround for the limitation.

Related git issues are:

1. https://github.com/Azure/azure-sdk-for-java/issues/20841

and there are a couple of CX reported this offline.

**Comment by thomasstoermer** [comment]
Hi @anuchandy 

is there any recommendation for clients, that require:
- EventProcessorClient
- CheckpointStore
- processEventBatch with maxWaitTime defined?

We are using `azure-messaging-eventhubs` 5.7.1 and are getting the `"exception":"reactor.core.Exceptions$OverflowException: The receiver is overrun by more signals than expected (bounded queue...)`.

Following the conversations, an upgrade to newer `azure-messaging-eventhubs` versions will not solve the issue? As I understood, it will only work without setting `maxWaitTime`?

**Comment by thomasstoermer** [comment]
Hi @conniey, @anuchandy 
do you have any recommendation / news for my comment?
Thanks

**Comment by jhunior244** [comment]
@conniey , @anuchandy I am using this code e I am still having memory problems

![image](https://user-images.githubusercontent.com/45322859/149407092-42e97fb4-887d-4f39-b1f2-1e12c7324efe.png)

and the use of memory is like this

![image](https://user-images.githubusercontent.com/45322859/149407267-3f356362-e6f6-4424-959d-49ab0c4a4830.png)

**Comment by anuchandy** [comment]
@thomasstoermer this is still a wip, the new operator implementation  and discussions happening here https://github.com/reactor/reactor-core/pull/2822

**Comment by thomasstoermer** [comment]
@anuchandy @conniey
I would like to check for an update. The referenced PR is closed in reactor. There seems to be a new variant provided. Do you intend to switch to that one?

Currently we are stuck with `azure-messaging-eventhubs:5.7.1`. We cannot fallback to the workaround not using `maxWaitTime`, because it will result in unpredictable event delays until batch is full.

**Comment by anuchandy** [comment]
Released in version 5.14.0 https://github.com/Azure/azure-sdk-for-java/blob/main/sdk/eventhubs/azure-messaging-eventhubs/CHANGELOG.md#bugs-fixed-1
