### ISSUE TITLE
[BUG] Spring cloud Azure appconfiguration multiple labels ignored

### ISSUE THREAD

**Issue by PbALpi7xEX** [Azure/azure-sdk-for-java#23951]
**Describe the bug**
Spring Boot app 2.5.4 using azure-spring-cloud-starter-appconfiguration-config v2.0.0. Based on documentation, trying to load appconfig label in addition to spring profile.

spring.cloud.azure.appconfiguration.stores[0].selects[0].label-filter=default
spring.cloud.azure.appconfiguration.stores[0].selects[1].label-filter=${spring.profiles.active}

If label for active spring profile is not defined for a key, expectation is fallback to default, then to no label key entry \0

Seems only keys labeled with sprig active profile are being loaded and nothing else.

**To Reproduce**
Create an app configuration store
Add a key with multiple values and labels
Connect Spring Boot app to configuration store
Configure which labels to load in bootstrap.properties

***Code Snippet***
spring.cloud.azure.appconfiguration.stores[0].selects[0].label-filter=default
spring.cloud.azure.appconfiguration.stores[0].selects[1].label-filter=${spring.profiles.active}

**Expected behavior**
Expecting keys not found for particular label will fallback to next inline, with \0 as the fallback.

**Setup (please complete the following information):**
 - OS: Windows 10
 - IDE: Eclipse
 - Library/Libraries: com.azure.spring.azure-spring-cloud-starter-appconfiguration-config:2.0.0; com.azure.spring.azure-spring-boot-bom:3.6.1; org.springframework.boot.spring-boot-starter-parent:2.5.4
 - Java version: 11 
 - App Server/Environment: Spring Boot embedded server
 - Frameworks: Spring Boot
  
**Additional context**
Following documentation at https://github.com/Azure/azure-sdk-for-java/tree/main/sdk/appconfiguration/azure-spring-cloud-starter-appconfiguration-config

**Comment by mrm9084** [comment]
@PbALpi7xEX can you check our 2.1.0, which was just released? I think there may have been an issue that was fixed.

**Comment by PbALpi7xEX** [comment]
> 
> 
> @PbALpi7xEX can you check our 2.1.0, which was just released? I think there may have been an issue that was fixed.

Updated to 2.1.0... Azure Spring Boot BOM updated to 3.7.0 but Spring Boot downgraded to 2.5.2 to match up with Axure Spring Boot BOM support.

Unlabeled keys arent loading...

Tried with following config:

spring.cloud.azure.appconfiguration.stores[0].selects[0].label-filter=\0,default,${spring.profiles.active}

Should unlabeled keys not be loaded in cases where labels are not set?

**Comment by mrm9084** [comment]
@PbALpi7xEX let me look into that Key with no label should load. Just to verify you are using properties and not yaml? I know Yaml needs single quote for `\0` to work. I.e.

`'\0,default,${spring.profiles.active}'`

**Comment by PbALpi7xEX** [comment]
@mrm9084 Yes, using properties

**Comment by mrm9084** [comment]
@PbALpi7xEX sorry about the issue. I figured it out. It does work, but doesn't seem to be document on how. If you just do this: `,default,${spring.profiles.active}` with the empty value it works.

**Comment by PbALpi7xEX** [comment]
@mrm9084 Thanks! That seems to have done the trick.
