### ISSUE TITLE
Azure Core AMQP Copper Improvements

### ISSUE THREAD

**Issue by conniey** [Azure/azure-sdk-for-java#23952]
# Improvements for AMQP

## Stress (Long-Running)

- [ ] #23953
- [ ] #23954

## Diagnosability/Troubleshooting Improvements

- [ ] #20836
- [ ] #20837
    - [ ]  #3806
- [x] #25114 
- [ ] #25115
- [ ] #25605

## Long-term Maintainability Features

- [ ] #19221
    - [ ] Migrate Service Bus processors
    - [ ] Migrate Event Hubs processors
- [ ] #5478

**Comment by joshfree** [comment]
@lmolkova could you edit / add your Structured Logging work item(s) to this checklist and epic for better tracking?

**Comment by lmolkova** [comment]
I also added metrics work item into this list as something that would help customers to detect issues and give us more context on what/when happens and slice & dice it.

**Comment by conniey** [comment]
This issue is covered by the project: https://github.com/Azure/azure-sdk-for-java/projects/13
