### ISSUE TITLE
Feature to detect the state of IMessageSender & IMessageReceiver

### ISSUE THREAD

**Issue by SkNuwanTissera** [Azure/azure-sdk-for-java#23962]
**Is your feature request related to a problem? Please describe.**
related to https://github.com/Azure/azure-sdk-for-net/issues/8561

**Describe the solution you'd like**
Currently, We cannot check the status of the message sender or receiver. 
But, we want to check the status as `OPEN` or `CLOSED`.

**Describe alternatives you've considered**
For the receiver, I tried with `peek()`. In that way, If the peek operation works successfully, I can think that receiver is this open.

**Additional context**
I need this feature to validate the object (sender/receiver) on the connection pool.
I am using Java SDK 3.5.1 [1] 

[1] https://github.com/Azure/azure-sdk-for-java/tree/main/sdk/servicebus/microsoft-azure-servicebus/src/main/java/com/microsoft/azure/servicebus

**Information Checklist**
Kindly make sure that you have added all the following information above and checkoff the required fields otherwise we will treat the issuer as an incomplete report
- [X] Description Added
- [X] Expected solution specified

**Comment by joshfree** [comment]
@ki1729 can you please take a look?

/cc @ramya-rao-a

**Comment by ramya-rao-a** [comment]
@joshfree This issue is for the older SDK azure-servicebus, so assigning to @yvgopal and @shankarsama first

@ki1729 Please keep an eye on this thread as the learnings from here may be applied to the newer package azure-messaging-servicebus as well

**Comment by yvgopal** [comment]
A receiver or sender or client is not closed until the application calls close on it. The expectation is that the application will discard closed objects. In that case, there is no need to know if an object is open or closed. Every created object is open, until explicitly closed by client application. You should check your application why it is holding on to closed objects.

**Comment by SkNuwanTissera** [comment]
Thank you very much for the explanation !!
We were able to fulfill the requirement.
