### ISSUE TITLE
ServiceBusProcessorClient Usage [Non Reactive Application]

### ISSUE THREAD

**Issue by ankitrajsingh** [Azure/azure-sdk-for-java#23961]
**Query/Question**
I would like to know wether [ServiceBusProcessorClient](https://docs.microsoft.com/en-us/java/api/com.azure.messaging.servicebus.servicebusprocessorclient?view=azure-java-stable) can be used in non reactive application and will it have any negative impact.

***Why is this not a Bug or a feature Request?***
We are planning to use a Entity (ServiceBusProcessorClient) which is already there in the SDK but would like to know about its compatibility with non reactive application.

**Setup (please complete the following information if applicable):**
 - OS: MacOS
 - IDE: IntelliJ
 - Library/Libraries: com.azure:azure-messaging-servicebus:7.4.0 (groupId:artifactId:version)]
 
 **Information Checklist**
 Kindly make sure that you have added all the following information above and checkoff the required fields otherwise we will treat the issuer as an incomplete report
- [Y ] Query Added
- [Y ] Setup information Added

ServiceBusProcessorClient internally **makes an async client which is reactive** in nature. 

We are planning to integrate this entity into our non reactive java app as this provides abstraction over the internal async client and concurrency, we don't need to manage them on our own. 

I wanted to know that wether this entity will work fine in non reactive environment or is it suggested to use this only in reactive application.

**Comment by joshfree** [comment]
@ki1729 could you please follow up with @ankitrajsingh

**Comment by ki1729** [comment]
@ankitrajsingh There should be no negative impact. The reactor usage can be kept abstracted, so you can use the library from a non reactive app and it should execute everything as expected
