### ISSUE TITLE
[BUG] App Configuration SDK returns (No Label) label incorrectly.

### ISSUE THREAD

**Issue by mrm9084** [Azure/azure-sdk-for-java#23969]
**Describe the bug**
When the App Configuration SDK returns a configuration with the (No Label) value it sets the label to null. Where is should be \0.

This results in this unexpected result:

```java
        ConfigurationAsyncClient client = new ConfigurationClientBuilder().connectionString(CONNECTION_STRING)
            .buildAsyncClient();
        
        SettingSelector selector = new SettingSelector().setKeyFilter("/application/config.message").setLabelFilter("\0");
        
        client.listConfigurationSettings(selector).subscribe(setting ->
        System.out.printf("Key: %s, Value: %s, Label: %s%n", setting.getKey(), setting.getValue(), setting.getLabel()));
        
        Thread.sleep(10000);
        
        ConfigurationSetting value = client.listConfigurationSettings(selector).blockFirst();
        
        selector = new SettingSelector().setKeyFilter(value.getKey()).setLabelFilter(value.getLabel());
        
        client.listConfigurationSettings(selector).subscribe(setting ->
        System.out.printf("Second Key: %s, Value: %s, Label: %s%n", setting.getKey(), setting.getValue(), setting.getLabel()));
```
The first list only prints out a single result.

Next the one result is retrieved and it's key and label are used to call list again.

This list returns all labels, as setting null as the label returns all results. 

***Exception or Stack Trace***
N/A

**To Reproduce**
See above code.

***Code Snippet***
See above code.

**Expected behavior**
(No Label) keys should have the label `\0` not `null`.

**Screenshots**

**Setup (please complete the following information):**
 - OS: [e.g. iOS] Windows 10
 - IDE: [e.g. IntelliJ] Eclipse
 - Library/Libraries: [e.g. com.azure:azure-core:1.16.0 (groupId:artifactId:version)]  com.azure:azure-data-appconfiguration:1.2.1
 - Java version: [e.g. 8] 11
 - App Server/Environment: [e.g. Tomcat, WildFly, Azure Function, Apache Spark, Databricks, IDE plugin or anything special] Local
 - Frameworks: [e.g. Spring Boot, Micronaut, Quarkus, etc] SpringBoot

If you suspect a dependency version mismatch (e.g. you see `NoClassDefFoundError`, `NoSuchMethodError` or similar), please provide
- dependency tree (`mvn dependency:tree -Dverbose`)
  
**Additional context**

**Information Checklist**
Kindly make sure that you have added all the following information above and checkoff the required fields otherwise we will treat the issuer as an incomplete report
- [ ] Bug Description Added
- [ ] Repro Steps Added
- [ ] Setup information Added

**Comment by mssfang** [comment]
Closing this issue as service decided to keep as it is.
