### ISSUE TITLE
[BUG] Health Indicator status with no connection for cloud-stream-binder-servicebus-topic

### ISSUE THREAD

**Issue by Manuel-Moya** [Azure/azure-sdk-for-java#23960]
**Describe the bug**
Using the azure-spring-cloud-stream-binder-servicebus-topic module, the health indicator keeps status "up" when I disable the internet connection. Should not it show status "down" when there is no connection?

**To Reproduce**
Disable connection

**Expected behavior**
When there is no connection to the service bus, set the health indicator status as "down".

**Screenshots**
![image](https://user-images.githubusercontent.com/70275834/132477852-51a85aff-59e1-490f-bdbe-3fc7cfd08c28.png)

**Setup (please complete the following information):**
 - OS: Windows 10
 - IDE: IntelliJ 2020.3
 - Library/Libraries: com.azure.spring:azure-spring-cloud-stream-binder-servicebus-topic:2.8 (groupId:artifactId:version)
 - Java version: 11
 - App Server/Environment: 
 - Frameworks: Spring Boot 2.5.3

**Information Checklist**
Kindly make sure that you have added all the following information above and checkoff the required fields otherwise we will treat the issuer as an incomplete report
- [X] Bug Description Added
- [X] Repro Steps Added
- [X] Setup information Added

**Comment by joshfree** [comment]
@yiliuTo could you please follow up with @Manuel-Moya

**Comment by yiliuTo** [comment]
Thanks for the reporting, and @ZhuXiaoBing-cn , could you help to investigate this issue?

**Comment by ZhuXiaoBing-cn** [comment]
Hi, @Manuel-Moya. Thanks for the reporting, the current health check of servicebus is implemented based on `ServicebusClientFactory` in azure-spring-integration.
Because there is no good way to get the status of amqp channel in servicebus SDK.
I created an [issue](https://github.com/Azure/azure-sdk-for-java/issues/24075) to communicate with servicebus SDK teams to try to expose the relevant channel status API, or what better way.

**Comment by jialigit** [comment]
health status show down confirmed with 4.0.0-beta.2 version binder.

/actuator/health endpoint shows:
{"status":"UP"} when connection is ok
{"status":"DOWN"} when connection is out.
