### ISSUE TITLE
[BUG] azure-storage-file-datalake poor performance of list operations

### ISSUE THREAD

**Issue by dmytro-sylaiev** [Azure/azure-sdk-for-java#23964]
**Describe the bug**
When I'm using `DataLakeServiceClient::listFileSystems()` or the `DataLakeFileSystemClient::listPaths`, the executing of `iterator()` method took a lot of time. Compare to the REST API the performance is quite poor, despite I have a small list of fileSystems/files in it.

***Exception or Stack Trace***

**To Reproduce**
Execute the following code and then do the same request via REST API

`DataLakeServiceClient client = new DataLakeServiceClientBuilder().credential(
                getSharedKeyCredential()).endpoint("https://<accName>.blob.core.windows.net/").buildClient();
PagedIterable<FileSystemItem> pagedIterable = client.listFileSystems(new ListFileSystemsOptions(), Duration.ofSeconds(450));
Iterator<FileSystemItem> iterator = pagedIterable.iterator();
while (iterator.hasNext()) {
            FileSystemItem next = iterator.next();
            System.out.println(next.getName() + " " + next.getProperties());
        }
`

***Code Snippet***
Add the code snippet that causes the issue.

**Expected behavior**

**Screenshots**

**Setup (please complete the following information):**
 - OS: Windows 10
 - IDE: cmd
 - Library/Libraries: 

> <dependency>
>             <groupId>com.azure</groupId>
>             <artifactId>azure-storage-file-datalake</artifactId>
>             <version>12.6.0</version>
>         </dependency>
>         
>         <dependency>
>             <groupId>com.azure</groupId>
>             <artifactId>azure-identity</artifactId>
>             <version>1.3.5</version>
>         </dependency>

 - Java version: [e.g. 8] jdk1.8.0_291
 - App Server/Environment: [e.g. Tomcat, WildFly, Azure Function, Apache Spark, Databricks, IDE plugin or anything special]
 - Frameworks: [e.g. Spring Boot, Micronaut, Quarkus, etc] 

If you suspect a dependency version mismatch (e.g. you see `NoClassDefFoundError`, `NoSuchMethodError` or similar), please provide
- dependency tree (`mvn dependency:tree -Dverbose`)
  
**Additional context**

**Information Checklist**
Kindly make sure that you have added all the following information above and checkoff the required fields otherwise we will treat the issuer as an incomplete report
- [ ] Bug Description Added
- [ ] Repro Steps Added
- [ ] Setup information Added

**Comment by rickle-msft** [comment]
Hi, @dmytro-sylaiev. Thanks for opening this issue. Can you please share which version of the sdk you're using?

**Comment by dmytro-sylaiev** [comment]
@rickle-msft com.azure azure-storage-file-datalake 12.6.0 com.azure azure-identity 1.3.5

**Comment by rickle-msft** [comment]
@dmitriy-barkalov Thanks. When you say the `iterator()` method took a lot of time, do you mean getting the iterator itself took a long time? Or do you mean that iterating over the iterator to process the list took a lot of time?

**Comment by dmytro-sylaiev** [comment]
Hello @rickle-msft 
I did some measures: looks like it happens for the first several operation calls, and then it works faster (the performance gap appears exactly on the `iterator` method)

`public static void main(String[] args) throws IOException {
        DataLakeServiceClient client = new DataLakeServiceClientBuilder().credential(
                getSharedKeyCredential()).endpoint("https://<test>.blob.core.windows.net/").buildClient();
        System.out.println("Client built");

        for (int i =0; i<10; i++) {
            long fsListStart = System.currentTimeMillis();
            printFSNames(client);
            System.out.println("FS List operation consumed: " + (System.currentTimeMillis() - fsListStart));
        }

        for (int i = 0; i<10; i++) {
            long start = System.currentTimeMillis();
            DataLakeFileClient fileClient =
                    client.getFileSystemClient("test").getDirectoryClient("dir").getFileClient("test.json");
            ByteArrayOutputStream os = new ByteArrayOutputStream();
            fileClient.read(os);

            byte[] content = os.toByteArray();

            for (byte b : content) {
                //            System.out.print((char)b);
            }
            System.out.println();
            System.out.println("Read file time consumed:  " + (System.currentTimeMillis() - start));
        }
    }`

Results:

> Client built
Iterator ready
FS List operation consumed: 34785
Iterator ready
FS List operation consumed: 30294
FS List operation consumed: 93
FS List operation consumed: 96
FS List operation consumed: 92
FS List operation consumed: 87
FS List operation consumed: 88
FS List operation consumed: 86
FS List operation consumed: 105
FS List operation consumed: 100

Read file time consumed:  272
Read file time consumed:  87
Read file time consumed:  78
Read file time consumed:  69
Read file time consumed:  63
Read file time consumed:  58
Read file time consumed:  61
Read file time consumed:  53
Read file time consumed:  56
Read file time consumed:  57


When I do not execute "list FileSystem" before the reading file, the first fileRead takes 30seconds

**Comment by alzimmermsft** [comment]
Hi @dmytro-sylaiev, I think you may be running into this issue: https://github.com/azure/azure-sdk-for-java/issues/22618

To validate this is the case, could you include a direct dependency on `azure-core-http-netty` `1.10.2`? You many also need to include a dependency on `azure-core` `1.19.0` to align the `azure-core` dependency.

**Comment by dmytro-sylaiev** [comment]
@alzimmermsft thank you, performance is better with specified dependencies.

**Comment by alzimmermsft** [comment]
That's great news @dmytro-sylaiev! And better news is that a newer version of `azure-storage-file-datalake` has been released which uses newer versions of the libraries I mentioned, so you could upgrade to that without needing the specific `azure-core` or `azure-core-http-netty` in your own project.
