### ISSUE TITLE
[QUERY] EventHub GZip Compression

### ISSUE THREAD

**Issue by dskajita** [Azure/azure-sdk-for-java#23997]
**Query/Question**
Hello, we are wondering why the azure-messaging-eventhubs SDK is not able to provide a compression natively ? We have some scenarios where the data sent can be over the 1MB limit and compression would solve our problem. Other possibility would be to use a Storage in the middle but it complexifies too much the architecture.

***Why is this not a Bug or a feature Request?***
While I was looking through Microsoft Documentation, I saw this particular page and it seems that some other Java SDKs with Event Hub are able to provide Compression natively ? https://docs.microsoft.com/en-us/azure/data-explorer/ingest-data-event-hub-overview

> Data can be compressed using the GZip compression algorithm.
> You can specify ingestion properties of the events ingestion using the EventData.Properties.

I was surprised to have seen that this is available through EventHub for Data Explorer but not for the "standlone" EventHub ? The EventData seems to be the same with the properties but I set, as below, and I confirmed that it didn't work. I went through the SDK github and indeed I didn't see anywhere reading the Compression property.

`   EventData eventData = new EventData(payload.getBody());
    eventData.getProperties().put(DatapushAuditTrailUtil.getPubUUIDKey(), payload.getPubUUID());
    eventData.getProperties().put("Compression", "GZip");`

**Setup (please complete the following information if applicable):**
 - OS: Windows 10
 - IDE: VSCode 1.59.1
 - Library/Libraries: com.azure:azure-messaging-eventhubs:5.8.0

**Comment by joshfree** [comment]
Thanks for raising this question @dskajita.  @conniey could you please follow up?

/cc @ramya-rao-a

**Comment by conniey** [comment]
Hey,

This compression is probably a feature built on top of the Event Hubs service. The contents of an `EventData` are just an opaque stream of bytes. Its interpretation and contents are dependent on the client.

We support creating an `EventData` via `BinaryData`. You can leverage [BinaryData.toObject](https://docs.microsoft.com/en-us/java/api/com.azure.core.util.binarydata.fromobject?view=azure-java-stable#com_azure_core_util_BinaryData_fromObject_java_lang_Object_com_azure_core_util_serializer_ObjectSerializer_) and pass in your own serializer that compresses the data. 

I hope this helps.

**Comment by dskajita** [comment]
Hello @conniey,

Thanks for your reply. We are trying to build a no/low code solution and we were expecting to have something similar of what Kafka provides (native or transparent for the producer/client based on a configuration).

The way it is today, it means that we have an impact on the producer (which is my team) and in the consumer (that is not necessarily even inside our company). Of course, if we need to compress on our end we will need to document well and the consumer will need to be aware that they might need to decompress before.

Could you please tell us why the Event Hub SDK is not providing ways to compress natively ? Is a feature that you have in mind for the future or is there any particular security concern ?

Kind regards,
Daniel

**Comment by joshfree** [comment]
Closing old issue with no updates since Sep 9, 2021
