### ISSUE TITLE
[BUG] Memory leak in BlobClient.copyFromUrlWithResponse()

### ISSUE THREAD

**Issue by daolis** [Azure/azure-sdk-for-java#23998]
**Describe the bug**
We are copying a lot of blobs from storage account A to storage account B. It was working, until customers storage account

***Exception or Stack Trace***
OutOfMemoryException

**To Reproduce**
Repository contains a quick and dirty impl to reproduce the issu:
https://github.com/daolis/azuresdk-memleaktest

Functionality: Multi threaded execution of `copyFromUrlWithResponse()` to create up to 3M files in the destination storage account using the same source.

Create a new accessible BlobStorageAccount, and set the correct values for the constants `destAccountName` and `destAccountKey`. The source file is already configured.

run with `-Xmx200m`

**Java Flight Recorder Dump**
https://stbsource.blob.core.windows.net/testsource/MemLeakTest_2021_09_09_120112.jfr?sp=r&st=2021-09-09T12:15:05Z&se=2022-09-09T20:15:05Z&spr=https&sv=2020-08-04&sr=b&sig=zDvXEPopNf1%2BpQDMzxt6tOYklCw9jSulyosxRnn0d0s%3D

**Expected behavior**
Should finish without error and without increasing memory usage.

**Screenshots**
![cpu-memory-Test2](https://user-images.githubusercontent.com/2550938/132688387-77eb9f17-c7e4-4343-b1c6-d968282d5c29.png)
At this time the test already copied around 600000 files.

**Setup (please complete the following information):**
 - OS: Linux
 - IDE: IntelliJ
 - Library/Libraries: see Test repository
 - Java version: 11
 - App Server/Environment: -
 - Frameworks: -

**Comment by joshfree** [comment]
Thanks for reporting this, @daolis.  Someone from the storage team will follow up with you shortly.

/cc @rickle-msft @alzimmermsft

**Comment by alzimmermsft** [comment]
Thank you for submitting this issue @daolis, I'm actively troubleshooting it and should get back to you shortly.

**Comment by alzimmermsft** [comment]
Hi @daolis, it appears you're running into an issue that was fixed by this PR: https://github.com/Azure/azure-sdk-for-java/pull/22697

Including a version of `azure-core` `1.18.0`, or above, in your project should resolve the issue you're seeing. A newer version of Core will be used as a dependency when the next version of `azure-storage-blob` is released.

cc: @rickle-msft @kasobol-msft

**Comment by daolis** [comment]
Hi @alzimmermsft , great news, thank you!

Is there already a planned release date?
And right now i'm testing it with azure-storage-blob 12.13.0 and azure-core 1.20.0. 
Are you aware of any side effects using this combination?

Status until now:
1 Step: Compiled successfully ;-)
2 Step: Heap  Memory Trace looks much better.
![cpu-memory-fixed](https://user-images.githubusercontent.com/2550938/132803333-0dba933f-420a-4b01-ba23-d90f9b6eeae8.png)

**Comment by alzimmermsft** [comment]
@daolis there is a release planned for later this month, exact date is still being hammered out, but once the release does happen I'll update you here.

**Comment by daolis** [comment]
As the temp workaround (see dependencies) fixes this problem you could close this issue.

```
<dependency>
    <groupId>com.azure</groupId>
    <artifactId>azure-storage-blob</artifactId>
    <version>12.13.0</version>
    <exclusions>
        <exclusion>
            <groupId>com.azure</groupId>
            <artifactId>azure-core</artifactId>
        </exclusion>
    </exclusions>
</dependency>

<dependency>
    <groupId>com.azure</groupId>
    <artifactId>azure-core</artifactId>
    <version>1.20.0</version>
</dependency>
```

**Comment by alzimmermsft** [comment]
@daolis, a new version of `azure-storage-blob`, containing this fix, has been released.

https://search.maven.org/artifact/com.azure/azure-storage-blob/12.14.0/jar

**Comment by daolis** [comment]
@alzimmermsft  already updated!! Thanks
