### ISSUE TITLE
[BUG] ServiceBusProcessorClient not obeying maxConcurrentSessions

### ISSUE THREAD

**Issue by ankitrajsingh** [Azure/azure-sdk-for-java#24047]
**Describe the bug**
MaxConcurrentSessions is not being obeyed by session based ServiceBusProcessorClient. It does appears to lock onto multiple sessions but processes only 1 message from any one session at a given time (Single Threaded). Expectation is to process 1 message from each of the locked session concurrently as per the [SDK Doc](https://docs.microsoft.com/en-us/java/api/com.azure.messaging.servicebus.servicebusclientbuilder.servicebussessionprocessorclientbuilder.maxconcurrentsessions?view=azure-java-stable#parameters) and [Github Readme](https://github.com/Azure/azure-sdk-for-java/tree/main/sdk/servicebus/azure-messaging-servicebus#receive-messages-from-a-session).

***Exception or Stack Trace***
NA

**To Reproduce**
1. Push messages corresponding to multiple sessions (more than 1 session) in the ASB session queue via any sender. Ensure that each session have at least 10 messages.
2. Create message callback for ServiceBusProcessorClient containing logs describing the current session.
3. Create a Session based ServiceBusProcessorClient with maxConcurrentSession higher than 1 along with the above callback.
4. Start the client.

***Code Snippet***
Add the code snippet that causes the issue.
````
Consumer<ServiceBusReceivedMessageContext> onMessage = context -> {
      ServiceBusReceivedMessage message = context.getMessage();
      log.info(message.getSessionId() + " message processed");
      Thread.sleep(1000);
      context.complete();
    };

Consumer<ServiceBusErrorContext> onError = context -> {
  System.out.printf("Error when receiving messages from namespace: '%s'. Entity: '%s'%n",
                    context.getFullyQualifiedNamespace(), context.getEntityPath());

  if (context.getException() instanceof ServiceBusException) {
    ServiceBusException exception = (ServiceBusException) context.getException();
    System.out.printf("Error source: %s, reason %s%n", context.getErrorSource(),
                      exception.getReason());
  } else {
    System.out.printf("Error occurred: %s%n", context.getException());
  }
};

ServiceBusProcessorClient sessionProcessor = new ServiceBusClientBuilder()
        .connectionString("<<conn_string>>")
        .sessionProcessor()
        .queueName("<<session_queue_name>>")
        .receiveMode(ServiceBusReceiveMode.PEEK_LOCK)
        .maxConcurrentSessions(10)
        .processMessage(onMessage)
        .processError(onError)
        .disableAutoComplete()
        .buildProcessorClient();

// Start the processor in the background
sessionProcessor.start();
````

**Expected behavior**
Expected behaviour is that the client should process 1 message from each of the sessions concurrently when supplied with maxConcurrentSessions and locked onto multiple sessions.

For example,
Scenario: Multiple sessions say session1, session2, session3, etc are present in ASB and maxConcurrentSessions is set to 3 in the client.

Expectation: Client will process 1 message from each of the session1, session2 and session3 concurrently. Throughput = at most 3 messages (each belonging to different sessions) at a given time

Actual: Client is processing only 1 message from session1 alone at a given time and afterwards repeating the same process with messages from session2 sequentially. Throughput = 1 message at a given time

**Screenshots**
Logs describing only 1 message from any one session is being processed at a given time although multiple sessions are available. Thread name under which all messages are being processed is same i.e [oundedElastic-2] which signifies single threaded sequential execution.
![image](https://user-images.githubusercontent.com/16316683/132898239-dcf3bd83-885e-478a-bb03-730769c1beb5.png)

**Setup (please complete the following information):**
 - OS: MacOS
 - IDE: IntelliJ
 - Library/Libraries: com.azure:azure-messaging-servicebus:7.4.0
 - Java version: 11 
 - App Server/Environment: Tomcat
 - Frameworks: Spring Boot

If you suspect a dependency version mismatch (e.g. you see `NoClassDefFoundError`, `NoSuchMethodError` or similar), please provide
- dependency tree (`mvn dependency:tree`)
NA
  
**Additional context**
Client does appear to process messages from sessions concurrently when **MaxConcurrentCalls** are set along with **MaxConcurrentSessions** in the session based ServiceBusProcessorClient. But this also causes parallel processing of messages from the same session thereby **disrupting the ordered nature of messages within a session**.

**Information Checklist**
Kindly make sure that you have added all the following information above and checkoff the required fields otherwise we will treat the issuer as an incomplete report
- [x] Bug Description Added
- [x] Repro Steps Added
- [x] Setup information Added

**Comment by joshfree** [comment]
@anuchandy could you please follow up with @ankitrajsingh

**Comment by ankitrajsingh** [comment]
I had mentioned in additional context that it does processes sessions (their messages) concurrently if i set MaxConcurrentCalls alongside MaxConcurrentSessions.
But in here, it also processes multiple messages of same session concurrently after receiving a bunch of them from a session. On debugging further, I can see that - 

1. [In ServiceSessionManager](https://github.com/Azure/azure-sdk-for-java/blob/main/sdk/servicebus/azure-messaging-servicebus/src/main/java/com/azure/messaging/servicebus/ServiceBusSessionManager.java#L98), each session is being assigned one scheduler each which is responsible of receiving messages from ASB.

2. Each scheduler is being assigned core pool size of atleast 10 ([`DEFAULT_BOUNDED_ELASTIC_SIZE`](https://projectreactor.io/docs/core/release/api/reactor/core/scheduler/Schedulers.html#DEFAULT_BOUNDED_ELASTIC_SIZE)) i.e it can receive upto 10 messages from a session in parallel and provide it to the **message subscribers listening** which is equal to maxConcurrentCalls. **This is basically disrupting ordering on our side and caller should be allowed to configure the session schedulers core pool size. In our case, it should be 1 for ordered processing.**

3. We tried setting property:  `"reactor.schedulers.defaultBoundedElasticSize" : 1`. This had the desired effect of limiting core size(DEFAULT_BOUNDED_ELASTIC_SIZE) of each session scheduler to one and they were receiving only one message from each of sessions at a given time and waiting for message subscribers to process them before pulling next message from the respective sessions.

4. But setting `"reactor.schedulers.defaultBoundedElasticSize" : 1` had a reverse effect of limiting the concurrency of message subscribers running to 1. Even though maxConcurrentCalls was greater than 1 and therefore there were multiple subscribers, but the subsribers were run sequentially one by one. The reason was that the subscribers are called using a [`Schedulers.boundedElastic()`](https://github.com/Azure/azure-sdk-for-java/blob/main/sdk/servicebus/azure-messaging-servicebus/src/main/java/com/azure/messaging/servicebus/ServiceBusProcessorClient.java#L264)

5. `Schedulers.boundedElastic()` used above is reading the core size from [DEFAULT_BOUNDED_ELASTIC_SIZE](https://projectreactor.io/docs/core/release/api/reactor/core/scheduler/Schedulers.html#boundedElastic--). This being 1 also limited the concurrency of message subscribers to 1.

6. **Ideally the [concurrency of message subscribers](https://github.com/Azure/azure-sdk-for-java/blob/main/sdk/servicebus/azure-messaging-servicebus/src/main/java/com/azure/messaging/servicebus/ServiceBusProcessorClient.java#L264) should be equal to maxConcurrentCalls besides the count of the message subscribers (which is already equal to maxConcurrentCalls.)**

**Comment by ankitrajsingh** [comment]
Hi @anuchandy, please let me know if something else is needed on the issue. Would be great if you can help us out. Thanks!

**Comment by anuchandy** [comment]
Hi @ankitrajsingh, thanks for sharing the details. I was able to create a repro and can see that the messages across sessions are delivered serially. I'll be looking into enabling the concurrency feature; it seems quite a bit of code needs to be changed and requires some discussion in behavior change. Given that the callbacks are not invoked serially, existing consumers need to prepare their handler to be thread-safe.

**Comment by ankitrajsingh** [comment]
Sure thanks 👍

**Comment by anuchandy** [comment]
The setter "maxConcurrentSessions" only indicate the maximum number of sessions the app wants the processor to connect at a given time, the setter "maxConcurrentCalls" is the one that results in overlapping concurrent calls to processor-callback. 

I'm closing this issue given the behavior of "maxConcurrentSessions" clarified here.

That said, there is an issue with session maxConcurrentCalls causing messages from the same session delivering out of order, which is being tracked separately (see the linked issue)

**Comment by lidkowiak** [comment]
Hi @anuchandy, is there any progress on this issue?

**Comment by jwyseu** [comment]
@anuchandy An update would be great
@ramya-rao-a I see the march milestone is now closed so this should move to the April milestone?

**Comment by anuchandy** [comment]
Hi @jwyseu, I've updated the other issue 27336. Closing this issue as this is a duplicate.
