### ISSUE TITLE
[FEATURE REQ] For servicebus sdk, should the status of amqp channel be exposed for health check?

### ISSUE THREAD

**Issue by ZhuXiaoBing-cn** [Azure/azure-sdk-for-java#24075]
**Is your feature request related to a problem? Please describe.**
I have observed that the servicebus sdk enables a single thread to maintain the channel and retry when it fails, which guarantees its availability. But for the upper layer, the relevant status of the relevant amqp channel is not exposed. For the health check, there will be no way to continue.

**Describe the solution you'd like**
Get channel status through api.

**Describe alternatives you've considered**

We may be able to expose this api:
```
public boolean isConnectionClosed() {
     return this.connectionProcessor.isChannelClosed();
}
```
We can expose the status of the amqp channel in order to make better judgments on the health of the servicebus.

**Information Checklist**
Kindly make sure that you have added all the following information above and checkoff the required fields otherwise we will treat the issuer as an incomplete report
- [x] Description Added
- [x] Expected solution specified

**Comment by joshfree** [comment]
Thanks for filing this github issue, @ZhuXiaoBing-cn. 

@anuchandy can you please work with @ramya-rao-a on reviewing/triaging this  ``'feature-request' issues for 'service bus'
/cc @ki1729

**Comment by bartekmaraszek** [comment]
I am also interested in this feature.

**Comment by anuchandy** [comment]
The library is supposed to recover from any transient failure, i.e., the library internally does health checks at different levels and attempts to recover.  If the library exposes the endpoint state, it’s only the state value at that point in time, in the next few ms/secs the state value changes (when recovers) and applications won’t be able to really make any decision from staled state. This was investigated in the linked PR. Closing this as not actionable.

**Comment by AndreasPetersen** [comment]
> The library is supposed to recover from any transient failure, i.e., the library internally does health checks at different levels and attempts to recover. If the library exposes the endpoint state, it’s only the state value at that point in time, in the next few ms/secs the state value changes (when recovers) and applications won’t be able to really make any decision from staled state. This was investigated in the linked PR. Closing this as not actionable.

I think this is a vital missing feature in the SDK. While a bad connection might recover shortly after a health check, health checks can be used over time. With Kubernetes it is common to provide a health check for a container, that will restart the pod if the health check fails multiple times over time.

Specifically, we want to integrate a [MicroProfile Health](https://download.eclipse.org/microprofile/microprofile-health-4.0.1/microprofile-health-spec-4.0.1.html) check in our service. Many SmallRye Reactive Messaging connectors already implement health checks, including the [AMQP](https://smallrye.io/smallrye-reactive-messaging/4.9.0/amqp/health/) and [Kafka](https://smallrye.io/smallrye-reactive-messaging/4.9.0/kafka/health/) connectors.
