### ISSUE TITLE
[QUERY]  How to access following information via API? ( Details in description )

### ISSUE THREAD

**Issue by TanveshT** [Azure/azure-sdk-for-java#24084]
**Query/Question**
I was looking for specific APIs get information regarding my Azure account, specifics being:

1. I was looking for an API for fetching details whether the Azure Resource Manager is enabled or not.
2. Another API that I looking for is that whether we can check whether Azure Defender has been enabled or not and if enabled what services it has been enabled for like there is `for Storage`, `for Endpoint`, etc.
3. Storage Account has locks within them so is there any API to harness this information?

***Why is this not a Bug or a feature Request?***
I have browsed through the API documentation and wasn't able to find any APIs specific to my requirements, so just wanted to check before raising a feature request if these APIs are available or not.
 
 **Information Checklist**
 Kindly make sure that you have added all the following information above and checkoff the required fields otherwise we will treat the issuer as an incomplete report
- [X] Query Added
- [x] Setup information Added **( Not required )**

**Comment by joshfree** [comment]
@weidongxu-microsoft could you please help route @TanveshT's questions?

**Comment by weidongxu-microsoft** [comment]
@TanveshT By "enabled", do you mean whether it is registered in "subscription -> resource providers"?
![image](https://user-images.githubusercontent.com/53292327/133183461-2cc8e5b0-3f56-437d-9681-75d95da2127f.png)

For lock, you can call
```
azure.managementLocks().listForResource(resourceId)
```

**Comment by TanveshT** [comment]
@weidongxu-microsoft My bad, I wanted to ask about "Resource Manager" instead of "Resource Graph"

And about the locks, what is the `azure` instanceof? I mean which client's instance we have to create in order to make the call.

**Comment by weidongxu-microsoft** [comment]
@TanveshT 
SDK is here https://aka.ms/azsdk/java/mgmt

Could you elaborate on the meaning of "Azure Resource Manager is enabled or not"?
I didn't quite get it. What would you expect when it is enabled, and what if it is not enabled?
