### ISSUE TITLE
Why is this page blank?

### ISSUE THREAD

**Issue by dpalfery** [Azure/azure-sdk-for-java#24089]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d0f1bbe0-48ae-f13b-f467-28d237fa8b60
* Version Independent ID: 81f050a4-743b-cf68-6eb9-af586098d664
* Content: [Spring Cloud for Azure appconfiguration config client library for Java](https://docs.microsoft.com/en-us/java/api/overview/azure/spring-cloud-appconfiguration-config-readme?view=azure-java-stable)
* Content Source: [docs-ref-services/latest/spring-cloud-appconfiguration-config-readme.md](https://github.com/Azure/azure-docs-sdk-java/blob/master/docs-ref-services/latest/spring-cloud-appconfiguration-config-readme.md)
* Service: **springcloud**
* Product: **azure**
* Technology: **azure**
* GitHub Login: @maggiepint
* Microsoft Alias: **magpint**

**Comment by mrm9084** [comment]
@dpalfery this is a result of the library being moved into this repo. We have a work item to fix it. https://github.com/Azure/azure-sdk-for-java/tree/main/sdk/appconfiguration/spring-cloud-starter-azure-appconfiguration-config has the information for that library.

**Comment by mrm9084** [comment]
Fixed Link issue.
