### ISSUE TITLE
[FEATURE REQ] The SDK Service Bus service builder can not use a custom TraceProvider

### ISSUE THREAD

**Issue by moarychan** [Azure/azure-sdk-for-java#24085]
**Is your feature request related to a problem? Please describe.**
Azure SDK Service Bus builder can not use a custom `TraceProvider`, trace provider usage is [here](https://github.com/Azure/azure-sdk-for-java/blob/a468e673c5a6bad9e38e4e70c832a16382b3b366/sdk/servicebus/azure-messaging-servicebus/src/main/java/com/azure/messaging/servicebus/ServiceBusClientBuilder.java#L126). The new trace implementation of azure core tracer interface will use the same Spring Sleuth tracer from Spring Application Context, or else the tracer information will not be linked for the same request which comes from Spring MVC and finally call Azure SDK methods.

**Describe the solution you'd like**
When building a service client, it's available to set a custom `TraceProvider` for `ServiceBusClientBuilder` instance.

**Describe alternatives you've considered**
No better solutions to achieve this feature.

**Information Checklist**
Kindly make sure that you have added all the following information above and checkoff the required fields otherwise we will treat the issuer as an incomplete report
- [x] Description Added
- [x] Expected solution specified

**Comment by saragluna** [comment]
@joshfree, do you know whom I could assign this issue to?

**Comment by anuchandy** [comment]
The work to enable tracing is tracked in this work item https://github.com/Azure/azure-sdk-for-java/issues/26269. Closing this in favor of 26269.
