### ISSUE TITLE
[FEATURE REQ] The SDK Event Hubs service client builder can not use a custom TraceProvider

### ISSUE THREAD

**Issue by moarychan** [Azure/azure-sdk-for-java#24086]
**Is your feature request related to a problem? Please describe.**
Azure SDKEvent Hubs builder can not use a custom `TraceProvider`, the trace provider usage in client builder is here, [EventProcessorClientBuilder](https://github.com/Azure/azure-sdk-for-java/blob/a468e673c5a6bad9e38e4e70c832a16382b3b366/sdk/eventhubs/azure-messaging-eventhubs/src/main/java/com/azure/messaging/eventhubs/EventProcessorClientBuilder.java#L575), [EventHubClientBuilder](https://github.com/Azure/azure-sdk-for-java/blob/a468e673c5a6bad9e38e4e70c832a16382b3b366/sdk/eventhubs/azure-messaging-eventhubs/src/main/java/com/azure/messaging/eventhubs/EventHubClientBuilder.java#L641). The new trace implementation of azure core tracer interface will use the same Spring Sleuth tracer from Spring Application Context, or else the tracer information will not be linked for the same request which comes from Spring MVC and finally call Azure SDK methods.

**Describe the solution you'd like**
When building a service client, it's available to set a custom `TraceProvider` for `EventHubClientBuilder` and `EventProcessorClientBuilder` instance.

**Describe alternatives you've considered**
No better solutions to achieve this feature.

**Information Checklist**
Kindly make sure that you have added all the following information above and checkoff the required fields otherwise we will treat the issuer as an incomplete report
- [x] Description Added
- [x] Expected solution specified

**Comment by saragluna** [comment]
@joshfree, do you know whom I could assign this issue to?

**Comment by saragluna** [comment]
Hi @lmolkova, could you help provide some samples on how to set the TraceProvider to Event Hubs client builder after #32573, where I see how to set the TraceProvider to HttpPipeline.

**Comment by lmolkova** [comment]
I'll need to update EventHubs and ServiceBus first,  after core is released next month. For OpenTelemetry it will be done in the following way: https://github.com/Azure/azure-sdk-for-java/blob/main/sdk/core/azure-core-tracing-opentelemetry-samples/src/samples/java/com/azure/core/tracing/opentelemetry/samples/TracingJavaDocCodeSnippets.java#L59


If you're keeping alternative tracing implementations, you can extend TracingOptions in a similar way to how it's done in azure-core-tracing-opentelemetry package.
