### ISSUE TITLE
[QUERY] Getting file from ADLS Gen2 using InputStream as exist in blob storage

### ISSUE THREAD

**Issue by ihudedi** [Azure/azure-sdk-for-java#24087]
Hi,
I didn't find any API that can return InputStream when trying to retrieve file from ADLS Gen2
There is only API with dataLakeFileClient.openQueryInputStream
but I would like withoput any query to get the inputstream to the file as I have in blobStorage
blobClient.openInputStream(blobInputStreamOptions);
I don't habe the file path.
Thanks,
Itay

**Comment by rickle-msft** [comment]
Hi, @ihudedi Thank you for opening this. I believe what you are looking for was released in our last beta (12.7.0-beta.1) #21322 which should be released sometime this month. Can you please confirm that this will address your request?

**Comment by ihudedi** [comment]
Hi @rickle-msft 
Yes this is what I looked for.
Thanks,
Itay
