### ISSUE TITLE
FeatureFlagConfigurationSetting in Azure Java library 

### ISSUE THREAD

**Issue by brijoyj** [Azure/azure-sdk-for-java#24098]
No documentation support for FeatureFlagConfigurationSetting

https://azuresdkdocs.blob.core.windows.net/$web/java/azure-data-appconfiguration/1.2.1/com/azure/data/appconfiguration/models/FeatureFlagConfigurationSetting.html

Can you provide me a sample of how to connect to Feature Flag without using Spring Cloud libraries?

I was able to fetch values for key value pair using connection string, but need similar example for FeatureFlag.

```
ConfigurationClient client = new ConfigurationClientBuilder()
                .connectionString(connectionString)
                .buildClient();
ConfigurationSetting setting = client.getConfigurationSetting("test", null, null);
System.out.printf(setting.getValue());

```

Thanks

**Comment by joshfree** [comment]
@mssfang can you please help create a sample for this 'App Configuration' scenario?

**Comment by mssfang** [comment]
@brijoyj Thank you for report this. I am working on the samples and it will be merged in the next couple days.

**Comment by mssfang** [comment]
@brijoyj The samples PR are merged now. Do these samples help to you?
