### ISSUE TITLE
[BUG] Uploading to a fileshare with a 3gb file fails with http 416

### ISSUE THREAD

**Issue by Sonnenhut** [Azure/azure-sdk-for-java#24118]
**Describe the bug**
When uploading a file of size 3gb or greater to a fileshare an exception is thrown, which indicates that the file size does not match the uploaded data.
Same code works fine, when the resulting file only is 2gb big.
The provided code stores the data in-memory and provides an SequenceInputStream.
I was able to reproduce this also by providing a FileInputStream with the same data, same effect.

***Exception or Stack Trace***
```
Exception in thread "main" com.azure.storage.file.share.models.ShareStorageException: Status code 416, "﻿<?xml version="1.0" encoding="utf-8"?><Error><Code>InvalidRange</Code><Message>The range specified is invalid for the current size of the resource.
RequestId:dee48cc2-c01a-00a1-6345-a9e9b0000000
Time:2021-09-14T08:53:06.5806720Z</Message></Error>"
        at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
        at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
        at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
        at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
        at com.azure.core.http.rest.RestProxy.instantiateUnexpectedException(RestProxy.java:343)
        at com.azure.core.http.rest.RestProxy.lambda$ensureExpectedStatus$5(RestProxy.java:382)
        at reactor.core.publisher.MonoFlatMap$FlatMapMain.onNext(MonoFlatMap.java:125)
        at reactor.core.publisher.Operators$MonoSubscriber.complete(Operators.java:1815)
        at reactor.core.publisher.MonoCacheTime$CoordinatorSubscriber.signalCached(MonoCacheTime.java:337)
        at reactor.core.publisher.MonoCacheTime$CoordinatorSubscriber.onNext(MonoCacheTime.java:354)
        at reactor.core.publisher.Operators$ScalarSubscription.request(Operators.java:2397)
...
```

**To Reproduce**
see here for a small reproducible:
https://github.com/Sonnenhut/file-share-upload-bug-reproduce
 - git clone https://github.com/Sonnenhut/file-share-upload-bug-reproduce
 - cd file-share-upload-bug-reproduce
 - Provide valid CONNECTION_STRING, SHARE_NAME, DIRECTORY_NAME in src/main/java/repro/Upload.java
 - mvn clean package
 - java -jar target/repro-test-0.0.1-SNAPSHOT-jar-with-dependencies.jar repro.Upload

***Code Snippet***
```
package repro;

import com.azure.core.util.Context;
import com.azure.storage.file.share.ShareFileClient;
import com.azure.storage.file.share.ShareServiceClientBuilder;
import com.azure.storage.file.share.models.ShareFileUploadOptions;

import java.io.BufferedInputStream;
import java.io.ByteArrayInputStream;
import java.io.InputStream;
import java.io.SequenceInputStream;
import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;
import java.util.Arrays;
import java.util.Collection;
import java.util.Collections;
import java.util.stream.Collectors;
import java.util.stream.IntStream;

public class Upload {
    private static final String CONNECTION_STRING = "xxx";
    private static final String SHARE_NAME = "xxx";
    private static final String DIRECTORY_NAME = "xxx";

    public static void main(String[] args) {
        String filename = "testfile_" + LocalDateTime.now().format(DateTimeFormatter.ofPattern("yyyy-MM-dd_HH-mm-ss")) + ".txt";
        ShareFileClient client = new ShareServiceClientBuilder()
                .connectionString(CONNECTION_STRING)
                .buildClient()
                .getShareClient(SHARE_NAME)
                .getDirectoryClient(DIRECTORY_NAME)
                .getFileClient(filename);

        byte[] mb100 = new byte[100_000_000];
        Arrays.fill(mb100, (byte) 0);

        Collection<ByteArrayInputStream> byteStreams3gb = IntStream.range(0,30)
                .mapToObj(n -> new ByteArrayInputStream(mb100))
                .collect(Collectors.toList());

        InputStream dataStream = new BufferedInputStream(new SequenceInputStream(Collections.enumeration(byteStreams3gb)));
        long size = mb100.length * 30L;

        client.create(size);
        client.uploadWithResponse(new ShareFileUploadOptions(dataStream, size), null, Context.NONE);
    }
}
```

**Expected behavior**
When uploading a file of any arbitrary size, the sdk should accept the data and upload accordingly.
Uploading a file of 1gb should behave the same as uploading a file of 3gb or more. (disregarding the time it takes)

**Screenshots**
no screenshot

**Setup (please complete the following information):**
 - OS: Linux (not tested on other OS)
 - IDE: IntelliJ
 - Library/Libraries: com.azure:azure-storage-file-share:1.10.0
 - Java version: 8
 - App Server/Environment: Standalone java, also reproducible in HDinsight though
 - Frameworks: plain java

**Additional context**
The use-case that causes is that we generate multiple byte arrays via a parallel process and then want to upload that data to a single file in azure file share.

**Information Checklist**
Kindly make sure that you have added all the following information above and checkoff the required fields otherwise we will treat the issuer as an incomplete report
- [x] Bug Description Added
- [x] Repro Steps Added
- [x] Setup information Added

**Comment by joshfree** [comment]
Thanks for filing this github issue, @Sonnenhut.  Someone from the `Storage` SDK team will follow up with you shortly.

**Comment by rickle-msft** [comment]
@Sonnenhut Thank you for reporting this. We'll take a look at what's going on here and follow up soon

**Comment by rickle-msft** [comment]
@Sonnenhut I have been able to root cause the source of this bug here and we should be able to work on getting a fix.

When the length is provided to an upload method, we use Utility.convertStreamToByteBuffer. That method has a bug in it such that, if the size of the data is not a multiple of the blockSize, the last buffer it returns will be too large because it does not adjust for this modulo.

In terms of code, we currently have this line:
```
return ByteBuffer.wrap(cache);
```
when it should actually be this:
```
int finalBlockSize = (int)(length % blockSize);
if (numOfBytes == -1) { // this indicates indicates the end of the stream was reached from preceeding code
    return ByteBuffer.wrap(cache, 0, finalBlockSize);
} else {
    return ByteBuffer.wrap(cache);
}
```

**Comment by Sonnenhut** [comment]
@rickle-msft Works like a charm (also with "azure-core-http-okhttp" HttpClient).
Thanks!
