### ISSUE TITLE
[QUERY] get outputstream from datalakeclient is missing

### ISSUE THREAD

**Issue by ihudedi** [Azure/azure-sdk-for-java#24127]
Hi,
In azure blob storage we can get the outputstream from blob and write any data to the stream with parallel transfer options.
I dont see this option in datalakeclient
I only found uploadwithresponse but enforce size of the stream or file.
Thanks,
Itay

**Comment by joshfree** [comment]
Hi @ihudedi someone from the Storage team will follow up with your question / feature-request shortly.  Thanks

**Comment by rickle-msft** [comment]
Hi, @ihudedi. Thanks for opening this feature request. We'll work on adding support for this feature in a future release

**Comment by ihudedi** [comment]
Hi @rickle-msft 
Is there any updates?

**Comment by alzimmermsft** [comment]
@ibrahimrabab are there any updates on this? I know a while back we added `openInputStream` to `DataLakeFileClient`, were there plans on adding this API as well?

**Comment by ibrahimrabab** [comment]
Hi @ihudedi @alzimmermsft 
Thanks for reaching out, we don't have a set plan on when we'll have this feature done, but we anticipate getting to this in a future release soon.

**Comment by ihudedi** [comment]
Hi @ibrahimrabab 
Which version does this fix is applied?
Thanks,
Itay

**Comment by ibrahimrabab** [comment]
Hi @ihudedi 
We are planning to release a beta version of this feature today. I will update on this thread again once the release is complete :)

**Comment by ibrahimrabab** [comment]
@ihudedi 
The output stream should be in the newest beta release available to use,
https://github.com/Azure/azure-sdk-for-java/blob/main/sdk/storage/azure-storage-file-datalake/CHANGELOG.md#12160-beta1-2023-05-30
