### ISSUE TITLE
Create Spark SQL Datasource for Cosmos OLTP

### ISSUE THREAD

**Issue by rhsu339** [Azure/azure-sdk-for-java#24129]
**Issue:**
My firm needs to create a spark table that is a "live look" into a cosmos db document. This means that queries on the table created will automatically reflect any changes in the underlying cosmos db document. In the older version of the cosmos db connector for spark 2.4, this was possible using the below spark sql syntax. The migration guide for the current spark 3 connector  (azure-cosmos-spark_3-1_2-12) details what the new configuration options are, but not the name of the new data source to replace "com.microsoft.azure.cosmosdb.spark".

Spark SQL Syntax (for Spark 2 connector):
CREATE TABLE IF NOT EXISTS XXX-
USING com.microsoft.azure.cosmosdb.spark options (
  "Endpoint" = "XXX",
  "Masterkey" = "XXX",
  "Database" = "XXX",
  "Collection" = "XXX",
  "query_custom" = "XXX"
)

**Ideal Solution:**
Having a valid spark sql data source to use in the syntax below. This would create a new table in the current spark environment (not create a new table in cosmos db) that would reflect all recent changes to underlying cosmos db table. 

CREATE TABLE IF NOT EXISTS XXX
USING **[data source]** options (
  "spark.cosmos.accountEndpoint" = "XXX",
  "spark.cosmos.accountKey" = "XXX",
  "spark.cosmos.database" = "XXX",
  "spark.cosmos.container" = "XXX",
  "query_custom" = "XXX"
)

**Alternatives Considered:**
Loading into a dataframe using df = spark.read.format("cosmos.oltp") syntax, however this is loading data at a point in time and thus will require frequent refreshes (not live).

**Error Message when using "cosmos.oltp" as Data Source:**
Error in SQL statement: ExecutionException: org.apache.spark.sql.AnalysisException: cosmos.oltp is not a valid Spark SQL Data Source.

**Comment by joshfree** [comment]
@kushagraThapar could you please help route this issue from @rhsu339 ?

**Comment by FabianMeiswinkel** [comment]
You would need to create a VIEW to be able to achieve this. There is a sample here: https://github.com/Azure/azure-sdk-for-java/blob/main/sdk/cosmos/azure-cosmos-spark_3-1_2-12/Samples/Python/NYC-Taxi-Data/01_Batch.ipynb

%sql
CREATE TABLE cosmosCatalog.SampleDatabase.GreenTaxiRecordsAnotherView 
USING cosmos.oltp
TBLPROPERTIES(isCosmosView = 'True')
OPTIONS (
  spark.cosmos.database = 'SampleDatabase',
  spark.cosmos.container = 'GreenTaxiRecords',
  spark.cosmos.read.inferSchema.enabled = 'True',
  spark.cosmos.read.inferSchema.includeSystemProperties = 'False',
  spark.cosmos.read.partitioning.strategy = 'Restrictive');

SELECT * FROM cosmosCatalog.SampleDatabase.GreenTaxiRecordsAnotherView LIMIT 10

**Comment by simplynaveen20** [comment]
Ack

**Comment by rhsu339** [comment]
Thank you Naveen and Fabian for the quick response. 

The syntax Fabian provided does create the live view after setting the spark configurations below, however the table is not persisted after the cluster is restarted. This means that after the cluster restarts, the spark configs (endpoint and key) are lost and we must set them again and recreate the table once more. Note we are using a read only key when accessing cosmos db. 

Also we note the table is accessible as "cosmosCatalog.Table", but using the older spark 2 connector we were able to directly create the table in any existing database and this table persisted even after cluster restart. Is there a way to create the table in a way that we can continue to access it after restart? 

Spark configurations:
spark.conf.set("spark.sql.catalog.cosmosCatalog", "com.azure.cosmos.spark.CosmosCatalog")
spark.conf.set("spark.sql.catalog.cosmosCatalog.spark.cosmos.accountEndpoint", cosmosEndpoint)
spark.conf.set("spark.sql.catalog.cosmosCatalog.spark.cosmos.accountKey", cosmosMasterKey)
spark.conf.set("spark.sql.catalog.cosmosCatalog.spark.cosmos.views.repositoryPath", "/viewDefinitions" + str(uuid.uuid4()))


The current syntax we are using to create table is below: 

sql ="""
create table if not exists cosmosCatalog.ref.table
(col1 string,
col2 string,
col3 string)
USING  cosmos.oltp
TBLPROPERTIES(isCosmosView = 'True')
OPTIONS  (
  "spark.cosmos.accountEndpoint" = "XXX",
  "spark.cosmos.accountKey" = "XXX",  
  "spark.cosmos.database" = DB",
  "spark.cosmos.container" = "container",
  "spark.cosmos.read.customQuery" = "SELECT
    t.col1, t.col2, t.col3
from T"
) """
spark.sql(sql)

%sql select * from cosmosCatalog.ref.table


Error when accessing table after restart:
Error in SQL statement: RuntimeException: mandatory option spark.cosmos.accountEndpoint is missing. Config description: Cosmos DB Account Endpoint Uri

Note: even if we set the endpoint and key configs again, the table can still not be found. We have had to run the create table command every time after restart which is not ideal.

**Comment by FabianMeiswinkel** [comment]
HI @rhsu399 - the definition of views is persisted in HDFS in the path you choose in the config setting "spark.sql.catalog.cosmosCatalog.spark.cosmos.views.repositoryPath". The sample generates a new id to have predictable behavior - if instead you use a constant there even between restarts of the cluster you would be able to see the previously created views. And the spark config settings can also added in Cluster Configuration (instead of running it in app/notebook)
