### ISSUE TITLE
Cosmos DB Spark - Change Feed Streaming limit

### ISSUE THREAD

**Issue by ealsur** [Azure/azure-sdk-for-java#24136]
When using `spark.cosmos.changeFeed.itemCountPerTriggerHint`, the PartitionPlanner makes a calculation based on the number of documents and the LSNs to understand what's the weight of each partition.

Based on the weight, it determines a percentage and that percentage is used to determine the volume of changes to be drained on each Batch.

There are currently two main points that need to be addressed:

1. The number the user sets as `spark.cosmos.changeFeed.itemCountPerTriggerHint` is not used at all. The volume of changes is defined by the percentage calculation and it does not utilize the config value. Ideally the config value should affect in some way (even if it's by approximation) the percentage.
2. On a draining scenario (Streaming from the beginning with no new changes happening in the source) the percentages reduce the actual volume of changes towards the end of the container. For example, if there are 10 partitions, each with a weight of 10%, when draining 1M documents, the first batch would drain 10% of 1M, but the next batches keep using 10% over the remainder of documents, which keeps decreasing with time and making it smaller and smaller as it goes.
3. In scenarios where the number of partitions is large and the volume of data is low, this percentage distribution can lead to cases where the volume of data being read is very small and progress is slow.

**Comment by xinlian12** [comment]
This working item will be scheduled sometime in Nov.
