### ISSUE TITLE
Support serializing JsonWebKey to IETF-standard JWK

### ISSUE THREAD

**Issue by heaths** [Azure/azure-sdk-for-java#24187]
Add support to serialize an `Azure.Security.KeyVault.Keys.JsonWebKey` to an [IETF-standard](https://datatracker.ietf.org/doc/html/rfc7517) JWK.

See https://github.com/Azure/azure-sdk-for-net/issues/16155 for discussion. You might review what you did for track 1, if you had a track 1 library, taking into account current SDK guidelines.

**Comment by vcolin7** [comment]
The current Java implementation of the [`JsonWebKey`](https://github.com/Azure/azure-sdk-for-java/blob/11a6293c7df41a000f502a5f46554a0dca9ef57e/sdk/keyvault/azure-security-keyvault-keys/src/main/java/com/azure/security/keyvault/keys/models/JsonWebKey.java) class produces an IETF compliant JWK when serializing using Jackson, the SDK's default serialization/deserialization library. I don't think there's anything we need to do here.
