### ISSUE TITLE
[BUG] azure-storage-blob-nio - Files.delete(path) ends in DirectoryNotEmptyException for an empty directory.

### ISSUE THREAD

**Issue by fcanovas1986** [Azure/azure-sdk-for-java#24193]
**Describe the bug**

When trying to delete an empty directory, `AzureFileSystemProvider `throws a `DirectoryNotEmptyException `because when executing `DirectoryStatus dirStatus = azureResource.checkDirStatus();` this call returns `NOT_EMPTY` status. The directory I'm trying to delete is empty. It does not happen everytime, only when there is a directory in the same level with a similar name. 

For instance:

- folder-1
- folder-12

If I try to delete `folder-1`, it's going to fail because the name `folder-12` contains the part of the chain (`folder-1`). So when `AzureFileSystemProvider `get the list of blobs, it will bring two elements: `folder-1` and `folder-12`. In consequence, `folder-1 `cannot be deleted because `AzureFileSystemProvider `detects it as a `NON-EMPTY` folder.

***Exception or Stack Trace***

```
java.nio.file.DirectoryNotEmptyException: $web:/bucket3/fran-1
	at com.azure.storage.blob.nio.AzureFileSystemProvider.delete(AzureFileSystemProvider.java:622)
	at java.base/java.nio.file.Files.delete(Files.java:1142)
```

**To Reproduce**

Create two directories, one named `folder-1` and the second one named `folder-12`, so you have this structure:

-$web:/bucket1/folder-1
-$web:/bucket1/folder-12

This is the important point, the name **folder-1** is a part of the chain **folder-1**2. This is the use case.

Try to delete `folder-1`. At this point you should get a `DirectoryNotEmptyException`.

***Code Snippet***

```
public void delete(Path path) throws IOException {
        AzureResource azureResource = new AzureResource(path);
        AzurePath.ensureFileSystemOpen(azureResource.getPath());

        // Here is the problem, it returns NOT_EMPTY
        DirectoryStatus dirStatus = azureResource.checkDirStatus();

        if (dirStatus.equals(DirectoryStatus.DOES_NOT_EXIST)) {
            throw (NoSuchFileException)LoggingUtility.logError(this.logger, new NoSuchFileException(path.toString()));
        } else if (dirStatus.equals(DirectoryStatus.NOT_EMPTY)) {
            throw (DirectoryNotEmptyException)LoggingUtility.logError(this.logger, new DirectoryNotEmptyException(path.toString()));
```
            
**Expected behavior**

It should delete an empty directory, even if the names of the folders are similar.

**Setup (please complete the following information):**
 - OS: Ubuntu 20.04
 - IDE:  IntelliJ
 - Library/Libraries: azure-storage-blob-nio:12.0.0-beta.9
 - Java version: 11 
 - App Server/Environment: Tomcat
 - Frameworks: Spring Boot

**Information Checklist**

Kindly make sure that you have added all the following information above and checkoff the required fields otherwise we will treat the issuer as an incomplete report

- [x] Bug Description Added
- [x] Repro Steps Added
- [x] Setup information Added

**Comment by rickle-msft** [comment]
@fcanovas1986 Thank you for opening this issue and for doing some digging to sort it out! This does indeed sound like a bug, and we'll work on getting a fix out for it!
