### ISSUE TITLE
[QUERY] exists method is missing for DataLakeFileSystemClient

### ISSUE THREAD

**Issue by ihudedi** [Azure/azure-sdk-for-java#24207]
In blob storage we have method BlobContainerClient.exists
and in DataLakeFileSystemClient there is no exists method

**Comment by rickle-msft** [comment]
Thanks, @ihudedi for this feature request. We'll work on getting this added.

**Comment by ihudedi** [comment]
Hi @rickle-msft 
Which version is it pushed?
Thanks,
Itay

**Comment by ibrahimrabab** [comment]
Hi @ihudedi 
We've released this in DataLake version 12.13.0-beta.1, which you can find [here](https://github.com/Azure/azure-sdk-for-java/blob/main/sdk/storage/azure-storage-file-datalake/CHANGELOG.md#12130-beta1-2022-09-06)

Let me know if you're having any problems.
Thank you!
