### ISSUE TITLE
[QUERY]DataLakeServiceClientBuilder class - missing connectionString method

### ISSUE THREAD

**Issue by ihudedi** [Azure/azure-sdk-for-java#24208]
In DataLakeServiceClientBuilder  I don't find how to set connectionString  as I do in BlobServiceClientBuilder

**Comment by rickle-msft** [comment]
@ihudedi Thank you for making this feature request. I'll double check with my team that there wasn't an intentional reason why this was omitted in datalake and work on adding it after that confirmation.

**Comment by ihudedi** [comment]
Hi @rickle-msft 
Any updates why it's missing?
Thanks,
Itay

**Comment by rickle-msft** [comment]
@ihudedi Thanks for following up. I believe the reason this wasn't added initially is because the portal does not expose dfs connections strings. However, we should be able to accept a connection string with a blob endpoint and convert it to a dfs one, so I think we can add this feature

**Comment by ihudedi** [comment]
Hi @rickle-msft 
Which version does it pushed?
Thanks,
Itay

**Comment by ibrahimrabab** [comment]
Hi @ihudedi 
This was introduced in version 12.13.0-beta.1 as seen [here](https://github.com/Azure/azure-sdk-for-java/issues/28130#issuecomment-1253607688)

Let us know if you have any more questions. Thanks!
