### ISSUE TITLE
Schema Registry: Architecture Board review feedback

### ISSUE THREAD

**Issue by conniey** [Azure/azure-sdk-for-java#24221]
**Schema Registry**
- [x] Rename endpoint to fullyQualifiedNamespace in constructor (discuss with feature crew to decide on name)
- [x] Add read-only fullyQualifiedNamespace  property
- [x] Add back Response<T> for all methods and remove caching
- [x] Investigate using BinaryData instead of string as the type for the Content parameter and property type in SchemaRegistrySchema
- [x] Rename content parameter to schemaDefinition
- [ ] Once GA service version is available, add it to ServiceVersion enum and remove the preview, and 2017 ones
- [x] Rename SerializationType to SchemaFormat (property could be either Format or SchemaFormat - since we are already in the SchemaProperties)

**Avro Serializer**
- [ ] Implement an LRU cache with 128 max entries - this does not need to be configurable for GA.
- [ ] Make the groupName parameter optional in the constructor (discussed this offline with Ted)

**Docs**
- [ ] Come up with guidance around the recommended use of AutoRegisterSchema and make sure it aligns with our default value.
- [ ] Go through Ted's feedback on the .NET README (and give feedback where it is relevant for other languages)

Related https://github.com/Azure/azure-sdk-for-js/issues/17697

**Comment by deyaaeldeen** [comment]
@conniey we should Rename endpoint to fullyQualifiedNamespace instead.
