### ISSUE TITLE
[BUG] BlobItemProperties.getDeletedTime returns null and isDeleted returns false for soft deleted blobs

### ISSUE THREAD

**Issue by ierandra** [Azure/azure-sdk-for-java#24229]
**Describe the bug**
For soft deleted blobs method BlobItemProperties.getDeletedTime returns null. 

**To Reproduce**
Click on Enable soft delete for blobs checkbox and set Keep deleted blobs for (in days) to 7.
Delete some blobs in the container.
Set the bellow vars: name, key, container
Run bellow code.

***Code Snippet***

    public static void main(String[] args) {
    String name = "<name>";
    String key = "<key>";
    String container = "<container>";
    String connectionString = "DefaultEndpointsProtocol=https;AccountName=" + name + ";AccountKey=" + key + ";EndpointSuffix=core.windows.net";

    BlobContainerClient blobContainerClient = new BlobContainerClientBuilder().connectionString(connectionString).containerName(container).buildClient();

    ListBlobsOptions listBlobsOptions = new ListBlobsOptions().setDetails(new BlobListDetails().setRetrieveDeletedBlobs(true).setRetrieveSnapshots(true).setRetrieveVersions(true));

    PagedIterable<BlobItem> blobItems = blobContainerClient.listBlobs(listBlobsOptions, Duration.ofSeconds(600));
    for (BlobItem blobItem : blobItems) {
        System.out.println(blobItem.getName() + " delete time " + blobItem.getProperties().getDeletedTime());
    }
    }

**Expected behavior**
For soft deleted blobs the method `blobItem.getProperties().getDeletedTime()` should return the deleted timestamp.

**Setup (please complete the following information):**
- OS: macOs
- IDE: IntelliJ
- Library/Libraries: com.azure - azure-storage-blob -12.12.0
- Java version: 11

**Information Checklist**
Kindly make sure that you have added all the following information above and checkoff the required fields otherwise we will treat the issuer as an incomplete report
- [ ] Bug Description Added
- [ ] Repro Steps Added
- [ ] Setup information Added

**Comment by rickle-msft** [comment]
@ierandra Thank you for opening this issue. I have not been able to reproduce the behavior you are seeing. When performing a listing operation, I can see both `isDeleted()` returns true and `getDeletionTime()` returns not null. When you perform the listing in your code snippet, are you sure that there are soft deleted blobs in the container? That is not included in your repro code, so I can't be sure just from looking at it

**Comment by ierandra** [comment]
@rickle-msft  Yes, I am 100% sure the blobs are deleted. In the `Steps to reproduce the behavior:` I mentioned that after enabling soft delete for 7 days I (manually) delete some blobs. 

Code output is: 
```
legacy-1 delete time null
legacy-2 delete time null
legacy-3.json delete time null
legacy-4.json delete time null
```

**Comment by ierandra** [comment]
I just noticed that the method `isDeleted()`returns false and `getDeletionTime()` returns null  when blob versioning is enabled. Without this the methods return correct output. 

Is this correct behaviour? 
I expect that the method `isDeleted()` returns true and `getDeletionTime()` returns not null also when blob versioning is enabled

**Comment by rickle-msft** [comment]
@ierandra I believe according to [this article](https://docs.microsoft.com/en-us/azure/storage/blobs/versioning-overview#blob-versioning-and-soft-delete) the behavior you are seeing with both versioning and soft delete is expected. When a blob is deleted, it will actually create a new version, and soft delete only applies when you try to delete an old version and that version is then soft deleted.
