### ISSUE TITLE
Example for Downloading Asset File

### ISSUE THREAD

**Issue by charlesritchea** [Azure/azure-sdk-for-java#2425]
I see that there was a closed issue for this https://github.com/Azure/azure-sdk-for-java/issues/443 but the link that cause that issue to be closed does not in fact show how to download an asset file.

**Comment by vhvb1989** [comment]
Hello @charlesritchea

I am sorry about you didn't get a sooner answer on this
Do you still need help? Let me know and I would be happy to assist.

Note: As part of repository cleaning effort, this issue will be closed by Sep 20 if no response is received from submitter and/or not further action is required.

**Comment by charlesritchea** [comment]
I don't remember why I needed this, close away
