### ISSUE TITLE
Reuse project.properties in all spring cloud for azure modules.

### ISSUE THREAD

**Issue by chenrujun** [Azure/azure-sdk-for-java#24259]
Now `project.properties` exists both in azure-spring-boot and azure-spring-data-cosmos. 

We should reuse this file and related java code.

Refs: https://github.com/Azure/azure-sdk-for-java/pull/23873#issuecomment-918807043

**Comment by saragluna** [comment]
I believe we can close this issue now?

**Comment by chenrujun** [comment]
Closing this issue in favor of https://github.com/Azure/azure-sdk-for-java/pull/27356
