### ISSUE TITLE
ServiceBus- How to authenticate with RBAC?

### ISSUE THREAD

**Issue by abhikt48** [Azure/azure-sdk-for-java#24265]
We got rquirement to authenticate ServiceBus with RBAC and perform send, receive, sendBatch operations. I referred this page [authenticate-application](https://docs.microsoft.com/en-us/azure/service-bus-messaging/authenticate-application) , but didn't found any sample java code to authenticate with RBAC.

It will be great, if you can share sample code to authenticate with RBAC?

**Comment by abhikt48** [comment]
Hi Team,

Could you please update us on this issue? 
Does ServiceBus Java SDK supports RBAC authentication? If yes, could you please provide any clue to authenticate.

Regards,
Abhishek Kumar

**Comment by joshfree** [comment]
@Kishp01 could you follow up with @abhikt48 on their question?
