### ISSUE TITLE
[FEATURE REQ] Add support for Azure Relay Hybrid Connections

### ISSUE THREAD

**Issue by giventocode** [Azure/azure-sdk-for-java#24272]
**Is your feature request related to a problem? Please describe.**
The new Java SDK does not have support for Azure Relay Hybrid Connections (data plane). 

**Describe the solution you'd like**
Port [Microsoft Azure Relay Hybrid Connections](https://github.com/Azure/azure-relay-java) library into the new SDK. 

**Describe alternatives you've considered**
Use the existing library. However, we are uncertain about the long term support of the library.

**Comment by joshfree** [comment]
Thanks for filing this github issue @giventocode.  @anuchandy @ki1729 could you please consider this service bus feature request for semester planning?

/cc @ramya-rao-a

**Comment by ramya-rao-a** [comment]
@giventocode,

When you say "the new Java SDK", can you share which SDK in particular are you are referring to?

Did you try the samples at https://github.com/Azure/azure-relay/tree/master/samples/hybrid-connections/java ?
