### ISSUE TITLE
[BUG] Cosmos DB StoreClient updateResponseHeader 

### ISSUE THREAD

**Issue by j82w** [Azure/azure-sdk-for-java#24287]
**Describe the bug**
The store client is removing the partition key range id which I don't see in the .NET SDK. 

It is also recreating the session token for no reason. The session token seems to be the same before and after parsing/writing the token. This needs to be validated still. This is adding unnecessary overhead and can possibly cause exception explained in the Exception area.

The .NET Cosmos DB SDK is being updated to skip parsing/updating the session token string with the same value.
https://msdata.visualstudio.com/CosmosDB/_git/CosmosDB/pullrequest/666702

***Exception or Stack Trace***
.NET modifying the header has caused InvalidOperationException because if the cache hits an exception multiple document operations were all waiting for the same cache refresh. When the cache refresh failed all the different threads get the same exception. All of those different threads try updating the header concurrently. The header is not thread safe leading to unexpected behavior and invalid operation exceptions.

**To Reproduce**
Have multiple threads try to do a document operation. Then force the partition key or address cache to hit an exception.

***Code Snippet***
https://github.com/Azure/azure-sdk-for-java/blob/3f31d68eed6fbe11516ca3afe3955c8840a6e974/sdk/cosmos/azure-cosmos/src/main/java/com/azure/cosmos/implementation/directconnectivity/StoreClient.java#L172

**Expected behavior**
Just return the session token the service returned.

**Information Checklist**
Kindly make sure that you have added all the following information above and checkoff the required fields otherwise we will treat the issuer as an incomplete report
- [ ] Bug Description Added
- [ ] Repro Steps Added
- [ ] Setup information Added

**Comment by kushagraThapar** [comment]
This is done.
