### ISSUE TITLE
Remove Jackson Databind as a hard dependency in Azure Core

### ISSUE THREAD

**Issue by srnagar** [Azure/azure-sdk-for-java#24299]
Look at removing this dependency by using other options (potentially just the streaming APIs).

**Comment by JonathanGiles** [comment]
If we want to do this, we need to do a dependency tree dump of all of our libraries, and all of their transitive dependencies, to try our best to remove it from all places we can control. @lmolkova Are you able to do this analysis at some point to identify where we have Jackson Databind dependencies from our libraries (I only know of azure-core and msal4j at present).

**Comment by JonathanGiles** [comment]
FYI - I've just filed [an issue](https://github.com/AzureAD/microsoft-authentication-library-for-java/issues/441) on msal4j to consider removing its dependency on jackson databind.

**Comment by lmolkova** [comment]
Yes, I will prepare the analysis. 
The differentiation here is not a dependency, but the need to serialize/deserialize arbitrary user models. These libraries would need to keep a dependency on databind (through azure-core-serializer-json-jackson,  shimmed, and compatible with multiple versions).  AFAIK this is a relatively small subset: I'll compile a list during the next month.
