### ISSUE TITLE
Make JDK HTTP Client the default HTTP client for Azure SDK

### ISSUE THREAD

**Issue by srnagar** [Azure/azure-sdk-for-java#24297]
Currently, we are using Netty as the default HTTP client. When we move to a higher JDK baseline, consider using JDK HTTP client as the default.

**Comment by JonathanGiles** [comment]
The primary blocker for this at present is ensuring no performance degradation is encountered. This particularly relates to native SSL implementations - we use them in Netty and I want to understand more about the JDK options here.

**Comment by JonathanGiles** [comment]
Assigning this issue to @g2vinay temporarily to get us performance baselines comparing JDK8+Netty to JDK17+HttpClient (with and without native SSL).
