### ISSUE TITLE
[QUERY] What is the equivalent of BlobRequestOptions.setMaximumExecutionTimeInMs in v12?

### ISSUE THREAD

**Issue by rupert-madden-abbott** [Azure/azure-sdk-for-java#24290]
**Query/Question**
In v8, it was possible to set the maximum execution time via BlobRequestOptions.setMaximumExecutionTimeInMs.

I cannot see an equivalent in v12 and can't see it mentioned in the migration guide.

What is the equivalent in v12 (assuming there is one)? I can see HttpClientOptions has a variety of timeouts but none of them seem to be for the entire execution unless I am misunderstanding the documentation.

**Setup (please complete the following information if applicable):**
 - Library/Libraries: com.azure:azure-storage-blob:12.14.0

**Comment by rickle-msft** [comment]
Hi, @rupert-madden-abbott thanks for your question! The way to do this in 12.14 is to use a `***withResponse()` version of the method in question and pass a timeout value. This will have the effect of setting a maximum execution timeout for that API call

**Comment by rupert-madden-abbott** [comment]
@rickle-msft thank you very much. That works great. In my particular case, that is much more convenient also.
