### ISSUE TITLE
[FEATURE REQ] Please add withPlan to VirtualMachineScaleSet.DefinitionStages.WithCreate

### ISSUE THREAD

**Issue by rupert-madden-abbott** [Azure/azure-sdk-for-java#24301]
**Is your feature request related to a problem? Please describe.**
`VirtualMachineScaleSet.DefinitionStages.WithCreate` appears to be missing a `withPlan` method allowing the setting of a `PurchasePlan`.

**Describe the solution you'd like**
Please add `withPlan` to this interface.

**Describe alternatives you've considered**
At the moment, we have to do this:

```java
VirtualMachineScaleSet.DefinitionStages.WithCreate stage
VirtualMachineScaleSetImpl impl = (VirtualMachineScaleSetImpl) stage;
impl.innerModel()
        .withPlan(plan);
```

**Comment by joshfree** [comment]
@weidongxu-microsoft could you please follow upw ith @rupert-madden-abbott?

**Comment by weidongxu-microsoft** [comment]
@haolingdong-msft Please support plan in VMSS.
