### ISSUE TITLE
[BUG] WARN due to AADApplicationType validation

### ISSUE THREAD

**Issue by blacelle** [Azure/azure-sdk-for-java#24310]
**Describe the bug**
Each time we start our applciation, we get the following log:

    o.h.v.i.p.j.JavaBeanExecutable.getParameters(217) - HV000254: Missing parameter metadata for AADApplicationType(String, int, String), which declares implicit or synthetic parameters. Automatic resolution of generic type information for method parameters may yield incorrect results if multiple parameters have the same erasure. To solve this, compile your code with the '-parameters' flag.

***Exception or Stack Trace***
Add the exception log and stack trace if available

**To Reproduce**
Some spring configuration like:

 ```
azure.activedirectory:
  # https://github.com/Azure/azure-sdk-for-java/issues/19816
  application-type: web_application_and_resource_server
```

**Expected behavior**
No WARN

** Version**
azure-sring-boot:3.8.0

**Comment by saragluna** [comment]
@chenrujun could you please take a look at this issue?

**Comment by chenrujun** [comment]
@moarychan could you please take a look at this issue?

**Comment by chenrujun** [comment]
Closing this issue. 
Because we are going to deprecate azure-spring-boot-starter-active-directory. And write samples to demonstrate how to use Azure Active Directory in Spring Boot application.

Refs: https://github.com/Azure-Samples/spring-boot-application-with-azure-active-directory

**Comment by blacelle** [comment]
It looks very awkward to me your decision to deprecates azure-spring-boot-starter-active-directory (as it is very helpful, and I'd prefer not having this much code duplicated in my own multiple apps). Any news about a formal deprecation? I can not find any notification about it.

**Comment by saragluna** [comment]
Hi @blacelle, after internal discussions, we won't deprecate `the azure-spring-boot-starter-active-directory` and will continue supporting it. Instead we include into our recent major release, please refer to these links for more details:
- https://aka.ms/spring/docs/4.0.0.
- https://aka.ms/spring/samples.
- https://microsoft.github.io/spring-cloud-azure/4.0.0/reference/html/index.html#migration-guide-for-4-0.
- https://github.com/Azure/azure-sdk-for-java/releases/tag/spring-cloud-azure_4.0.0.
And you can find the aad part here https://microsoft.github.io/spring-cloud-azure/4.0.0/reference/html/index.html#spring-security-support
