### ISSUE TITLE
Update update-version-scripts to change test matrix

### ISSUE THREAD

**Issue by lmolkova** [Azure/azure-sdk-for-java#24313]
https://github.com/Azure/azure-sdk-for-java/blob/main/sdk/core/supported-version-matrix.json 

_Originally posted by @lmolkova in https://github.com/Azure/azure-sdk-for-java/pull/24312#pullrequestreview-763303384_

**Comment by alzimmermsft** [comment]
Closing as what this was referencing no longer exists, but I believe this was a request to update the version validation test matrix used to validate a set of Reactor, Reactor Netty, and Jackson versions which is kept up to date.
