### ISSUE TITLE
Renaming all azure-spring-boot-xxx to spring-cloud-azure-xxx

### ISSUE THREAD

**Issue by chenrujun** [Azure/azure-sdk-for-java#24328]
Parent issue: https://github.com/Azure/azure-sdk-for-java/issues/23402

**Comment by yiliuTo** [comment]
Should the new artifact-id be like azure-spring-cloud-xxx or spring-cloud-azure-xxx? Given this issue https://github.com/Azure/azure-sdk-for-java/issues/23931 seems it's spring-cloud-azure-xxx

**Comment by chenrujun** [comment]
@yiliuTo Updated the title.

**Comment by chenrujun** [comment]
Closing this one, because it's duplicated with this one: https://github.com/azure/azure-sdk-for-java/issues/23931
