### ISSUE TITLE
[BUG] flush method on DataLakeFileClient failed when overwrite parameter is true

### ISSUE THREAD

**Issue by ihudedi** [Azure/azure-sdk-for-java#24323]
In Azure Data Lake the method flush is: for version 12.7.0
 @ServiceMethod(returns = ReturnType.SINGLE)
    public PathInfo flush(long position, boolean overwrite) {
        DataLakeRequestConditions requestConditions = new DataLakeRequestConditions();
        **if (overwrite) {
            requestConditions = new DataLakeRequestConditions().setIfNoneMatch(Constants.HeaderConstants.ETAG_WILDCARD);
        }**
        return flushWithResponse(position, false, false, null, requestConditions, null, Context.NONE).getValue();
    }
When the overwrite parameter is true he enforce that the file won't be exists but we can't append if the file not exist so when the file exist and we set the overwrite to true he failed.
The condition should be 
f (!overwrite) {
            requestConditions = new DataLakeRequestConditions().setIfNoneMatch(Constants.HeaderConstants.ETAG_WILDCARD);
        }
Thanks,
Itay

**Comment by rickle-msft** [comment]
Hi, @ihudedi Thanks for catching this. We'll put out a fix for it soon.

**Comment by ihudedi** [comment]
Hi @rickle-msft 
The flush should be after we append the file so the file must be exist.
No need this param because it can't be not exist.
Thanks,
Itay

**Comment by rickle-msft** [comment]
@ihudedi We can't remove the parameter because it would be a breaking change, but we can fix the behavior to be correct. I'm finishing up some other work and then hopefully I'll be able to circle back around to this.

**Comment by ihudedi** [comment]
Hi @rickle-msft 
Do you know in which version this fix should be applied?
I didn't see the fix in 12..4.2
Thanks,
Itay

**Comment by rickle-msft** [comment]
I believe I merged this after the last patch release. It should be released as part of a beta this week but won't be GA until the new year
