### ISSUE TITLE
Try to upgrade spring-boot's version to 2.6.0-RC1, and upgrade 3rd-party dependencies version.

### ISSUE THREAD

**Issue by chenrujun** [Azure/azure-sdk-for-java#24325]
Not merge to main branch, just run tests, find pipeline failures and fix them.

1. spring-boot:2.6.0-M3: https://github.com/spring-projects/spring-boot/releases/tag/v2.6.0-RC1
2. Sample PR: https://github.com/Azure/azure-sdk-for-java/issues/23686

**Comment by moarychan** [comment]
Close this issue now due to this issue https://github.com/Azure/azure-sdk-for-java/issues/25581.
