### ISSUE TITLE
Release Spring Cloud Azure 4.0.0

### ISSUE THREAD

**Issue by chenrujun** [Azure/azure-sdk-for-java#24327]
Parent issue: https://github.com/Azure/azure-sdk-for-java/issues/23402

**Comment by stliu** [comment]
NOTE, we need to pass api review with @JonathanGiles  before release this GA, please plan / prepare ahead

**Comment by saragluna** [comment]
The release has completed:
- release notes: https://github.com/Azure/azure-sdk-for-java/releases/spring-cloud-azure_4.0.0
- changelog: https://github.com/Azure/azure-sdk-for-java/blob/spring-cloud-azure_4.0.0/sdk/spring/CHANGELOG.md
- refdoc: https://aka.ms/spring/docs/4.0.0
- samples: https://aka.ms/spring/samples
