### ISSUE TITLE
[FEATURE REQ] Is it possible to detect the adoption of Spring framework in azure-core and set flag in User Agent header?

### ISSUE THREAD

**Issue by saragluna** [Azure/azure-sdk-for-java#24337]
**Is your feature request related to a problem? Please describe.**
In most cases, the user-agent header of HTTP based Azure SDK could be constructed by creating an [UserAgentPolicy](https://github.com/Azure/azure-sdk-for-java/blob/703d97b69ea683c015e4de5bd47f5ba9fa116d09/sdk/core/azure-core/src/main/java/com/azure/core/http/policy/UserAgentPolicy.java#L74-L76). And the user-agent header will be like:

`<application-id> azsdk-java-<sdk-name>/<sdk-version> (<platform-info>)` and one example could be `my-application azsdk-java-azure-storage/12.0 (Windows 10/x64)`.

This pattern allows us to identify our Azure Spring libraries by setting our library as part of the application id, which will be like:

`<customer-application-id><azure-spring-identifier>  azsdk-java-<sdk-name>/<sdk-version> (<platform-info>)` and one example could be `my-applicationaz-sp-sb/4.0.0 azsdk-java-azure-storage/12.0 (Windows 10/x64)`. 

Adding Azure Spring info in application-id allows us to collect data from customers using our Azure Spring libraries. Still, one scenario isn't covered by this when customers are using the Spring framework + Azure SDKs directly.

**Describe the solution you'd like**

 I'm wondering whether we could add some logic in the UserAgentPolicy or the azure-core module to help identify the framework the customers are using and then set the information in the UA header? This will help us learn how many customers are using the SDK in the Spring framework directly and perhaps help us find out the insufficiency of our Azure Spring libraries.

**Describe alternatives you've considered**

**Additional context**

**Information Checklist**
- [x] Description Added
- [x] Expected solution specified

**Comment by JonathanGiles** [comment]
Adding @alzimmermsft 

It would pay to refer to the guidelines [here](https://azure.github.io/azure-sdk/general_azurecore.html#telemetry-policy). In particular, the constraints on character count (24), as well as the `X-MS-AZSDK-Telemetry` header.

**Comment by stliu** [comment]
I think this request fall into '<platform_info>' section

**Comment by alzimmermsft** [comment]
I lean towards agreeance that this should be the `<platform_info>` in the `UserAgent` header if there isn't already another platform being used in the `UserAgent` header or if it isn't guaranteed for the platform we'd be adding to fit in 24 characters.

@JonathanGiles, when the guideline was being written were in-house/in-repo platform solutions included in the discussion? Ex, was Spring Framework solutions we would provide included.

The other tricky bit is if a custom/customer provided platform was included, does the provided platform take complete precedence or is it a merge pattern as mentioned in the issue but what if this exceeds 24 characters. And this may be why it was suggested to use `x-ms-azsdk-telemetry` headers as this is meant to be a bag of common telemetry without a 24 character restriction.

**Comment by saragluna** [comment]
@alzimmermsft, it would be better if we could add such info to <platform_info> in the UserAgent, so our BI system won't need to be changed. 

What do you mean by a custom/customer-provided platform, could you give an example here? 

If the framework info can't fit into the <platform_info> of UserAgent header, it's also acceptable to use the `x-ms-azsdk-telemetry` header instead, as long as we could get such info collected. 

Do you know what we should do to get this proposal reviewed or discussed?

**Comment by sandeep-sen** [comment]
Ask: 
1. Mechanism to find if the request is coming from an app which uses Spring.
2. Mechanism to find if the request is coming from an app which uses SpringBoot.
@saragluna suggested maybe we could look at the classpath to check is Spring Core class was loaded

**Comment by stliu** [comment]
I think this is simliar to how to detect the JDK environment and version?

**Comment by joshfree** [comment]
@sandeep-sen can you update this tracking issue with latest status, since 2022 is wrapping up?
