### ISSUE TITLE
Ensure test coverage for each class

### ISSUE THREAD

**Issue by chenrujun** [Azure/azure-sdk-for-java#24333]
Parent issue: https://github.com/Azure/azure-sdk-for-java/issues/23402

# Requirements
 - Add maven plugin to enforce coverage rate.
 - Add more tests if necessary.

# Sub tasks:
- [x] #24405
- [x] #24406
- [x] #24407
- [x] #24408

# Steps of using Intellij to get test coverage

Step 1: Run test with coverage
![image](https://user-images.githubusercontent.com/13167207/134800142-ded9d4b6-1af5-4ac3-8885-7852fabaf175.png)

Step 2: Check the coverage result:
![image](https://user-images.githubusercontent.com/13167207/134800167-21f31a7b-9200-400e-98a3-0e23e38e31f8.png)

Refs: https://www.jetbrains.com/help/idea/running-test-with-coverage.html

**Comment by saragluna** [comment]
Closed in https://github.com/Azure/azure-sdk-for-java/pull/26187.
