### ISSUE TITLE
[Epic] Improve java doc's quality.

### ISSUE THREAD

**Issue by chenrujun** [Azure/azure-sdk-for-java#24332]
Parent issue: https://github.com/Azure/azure-sdk-for-java/issues/23402

# Requirement
As a public library, every public class should have well-formatted java doc.

**AutoConfiguration Properties's javadoc will be used to genreated metadta and docs, so these classes' javadoc must be well documented.**

# Sub issues
- [x] #24409
- [x] #24410
- [x] #24411
- [x] #24412

# Java doc samples
1. Here is the java doc of `OAuth2AuthorizedClientProvider` in `spring-security-oauth2-client`:
![image](https://user-images.githubusercontent.com/13167207/134799890-37f45bff-ed99-418d-bc05-3715c70958fb.png)

1/ Here is java doc of `OtherClientRefreshTokenOAuth2AuthorizedClientProvider` in `spring-security-azure-oauth2-client`:
![image](https://user-images.githubusercontent.com/13167207/134799974-4617e632-9569-4f8c-8d66-8af336efc336.png)

**Comment by saragluna** [comment]
Closed in #26288.
