### ISSUE TITLE
Create sample projects for 4.0 related modules.

### ISSUE THREAD

**Issue by chenrujun** [Azure/azure-sdk-for-java#24334]
Parent issue: https://github.com/Azure/azure-sdk-for-java/issues/23402

Target repo: https://github.com/Azure-Samples/azure-spring-boot-samples

 - [x] https://github.com/Azure/azure-sdk-for-java/issues/24335
 - [x] https://github.com/azure/azure-sdk-for-java/issues/24336
 - [ ] Create issue for other modules.

**Comment by chenrujun** [comment]
Unassigned myself, because:
1. AAD related sample will track here: https://github.com/Azure-Samples/spring-boot-application-with-azure-active-directory/issues
2. Key Vault related sample will not do redesign in 4.0.

**Comment by stliu** [comment]
is there any other sample we need to create for 4.0?

**Comment by chenrujun** [comment]
Closing this issue because all sub issues have been closed.

**Comment by chenrujun** [comment]
@stliu 

Other samples related task are tracked in @backwind1233 's wiki page: 

https://dev.azure.com/azure-spring-integration/spring-integration-private/_wiki/wikis/spring-integration-private.wiki/252/Doc-of-tracking-migration-guides
