### ISSUE TITLE
Error Handling using Dead Letter Queue for Azure Service Bus Topic Binder and Spring Cloud Stream

### ISSUE THREAD

**Issue by ahmedmq** [Azure/azure-sdk-for-java#24342]
We are currently using Spring Cloud Stream with the Azure Service Bus Topic Binder.  Is there a way to configure Dead Letter Queue (DLQ) to handle any failed messages? 
The Spring Documentation on Cloud Stream has examples for Kafka/RabbitMQ to configure DLQ , but there is no documentation on the Azure Service Bus Topic Binder for configuring DLQ. Is this feature work in progress and if yes, when is it expected to be release?

**Comment by yiliuTo** [comment]
Hi @ahmedmq Azure Service Bus DLQ feature is not supported now, it is in the backlog and is planned to be implemented in the next 6 months.
