### ISSUE TITLE
Support structured logging

### ISSUE THREAD

**Issue by JonathanGiles** [Azure/azure-sdk-for-java#24344]
There have been cases recently where the availability of structured logging output (e.g. JSON), rather than plain text output, would have potentially made diagnosing issues drastically simpler. This is because tooling could be written to analyse the output and provide additional diagnostics (e.g. in the complex cases of AMQP messaging, various visualisations could be written to more clearly see the series of events that happen).

We need to investigate and enable end-to-end structured logging in all Azure SDK for Java libraries. At a high level I would like to see the following as the outcome of this issue:

1. Documentation on docs.microsoft.com about how to enable structured logging output for all logging implementations that support this mode.
2. Updates to our `ClientLogger` API to enable the provision of key / value inputs that will find their way to the logging implementation and output as structured JSON output. Care needs to be taken to ensure that performance is kept as a high priority - no perf degradation should be acceptable when logging is disabled or from the provision of key / value pairs.
3. Updates to our critical libraries that would most benefit from key / value pairs being output in structured output. At a first pass, this should include at least all azure-core libraries, as well as our AMQP-based libraries (Event Hubs and Service Bus). 
4. Socialisation of this functionality with partner teams so that they may make decisions about inclusion of this in their future revisions.

**Comment by lmolkova** [comment]
> Updates to our ClientLogger API to enable the provision 

done in #25247

> Documentation on docs.microsoft.com about how to enable structured logging

Decided not to do it, summary https://gist.github.com/lmolkova/04f6484595fdd7edded9f4d82619291f

**Comment by lmolkova** [comment]
Event Hubs is done: 
- https://github.com/Azure/azure-sdk-for-java/pull/26561

TODO:
- [ ] SerivceBus
- [ ]  https://github.com/Azure/azure-sdk-for-java/issues/26396
