### ISSUE TITLE
[Epic] API review for each module

### ISSUE THREAD

**Issue by chenrujun** [Azure/azure-sdk-for-java#24356]
# Requirements:
1. Ensure all public classes are well-designed, try to avoid breaking change in the further releases as much as possible.
2. For classes that is not used by customer directly, put into `xxx.implementation.xxx` package.
3. Make sure implementation classes are not exposed.

# Sub issues
- [x] #24413
- [x] #24414
- [x] #24415
- [x] #24416

**Comment by saragluna** [comment]
Closing in favor of https://github.com/Azure/azure-sdk-for-java/issues/27112.
