### ISSUE TITLE
Ensure test coverage in spring-security-azure-oauth2-client

### ISSUE THREAD

**Issue by chenrujun** [Azure/azure-sdk-for-java#24358]
Parent issue: #24333

**Comment by backwind1233** [comment]
I think we should not ensure test coverage in spring-security-azure-oauth2-client only for 4.0 beta release

**Comment by chenrujun** [comment]
@backwind1233 .
Yes, and I have another issues to track:  #24408 and #24333

**Comment by chenrujun** [comment]
Closing this issue because we will not release spring-security-azure-oauth2-client  any more.
