### ISSUE TITLE
Move IT modules for spring cloud for azure messaging into the source code module

### ISSUE THREAD

**Issue by yiliuTo** [Azure/azure-sdk-for-java#24363]
Modules of `spring-cloud-azure-test-servicebus-binder`, `spring-cloud-azure-stream-binder-test` and `spring-cloud-azure-test-eventhubs-kafka` should be dropped and related code should be moved into related source code module:
- `spring-cloud-azure-test-servicebus-binder` and `spring-cloud-azure-stream-binder-test` -> `spring-cloud-azure-stream-binder-servicebus-queue` and `spring-cloud-azure-stream-binder-servicebus-topic`.
- `spring-cloud-azure-test-eventhubs-kafka` -> `azure-spring-cloud-autoconfigure`

**Comment by jialigit** [comment]
close for code merged already.
