### ISSUE TITLE
[FEATURE REQ] Spring Autoconfiguration Library should support Recovery

### ISSUE THREAD

**Issue by mrm9084** [Azure/azure-sdk-for-java#24365]
**Is your feature request related to a problem? Please describe.**
Spring Libraries need to be able to support redundancy for the services it integrates with, in where the service doesn't support or additional coverage is needed.

**Describe the solution you'd like**
Currently Autoconfigurations only supports connecting to a single client, as supported by the Azure SDK. I should be able to Autoconfigure multiple clients in order to recover from a failed resource.

**Describe alternatives you've considered**
If additional auto configurations isn't added it should be made more than clear to customers that for services that don't support full service side redundancy that their setup isn't suggested and isn't considered secure.

**Comment by stliu** [comment]
is there any other spring lib supporting such feature we can take as an example?
