### ISSUE TITLE
[FEATURE REQ] Provide a way to configure own SerializerAdapter instance while building XxxBlob clients

### ISSUE THREAD

**Issue by reta** [Azure/azure-sdk-for-java#24373]
**Is your feature request related to a problem? Please describe.**
At the moment, `XxxBlob` client builders (`BlobClientBuilder`, `BlobContainerClientBuilder`, `BlobServiceClientBuilder`, ...) do not provide a way to supply own `SerializerAdapter` instance and rely on `JacksonAdapter::createDefaultSerializerAdapter`. It works in most cases but sometimes, fe. when application runs under `SecurityManager` and needs to use reflection, it is not sufficient and using custom `SerializerAdapter`  would be very helpful. The underlying `AzureBlobStorageImpl` already supports that however the ability to pass the  `SerializerAdapter` instance down the chain of builders is not supported.

**Describe the solution you'd like**
It would be beneficial to provide a way for the `XxxBlob` client builders to allow using user-provided `SerializerAdapter` instance. The change is low risk and does not break an existing APIs.

**Describe alternatives you've considered**
It is not possible to provide own `SerializerAdapter` instance in a clean way.

**Additional context**
The specific case in mind is when `SecurityManager` is involved and needs privileged context for certain `java.lang.reflect.ReflectPermission` permissions. 

**Information Checklist**
Kindly make sure that you have added all the following information above and checkoff the required fields otherwise we will treat the issuer as an incomplete report
- [X] Description Added
- [X] Expected solution specified

**Comment by rickle-msft** [comment]
@alzimmermsft @JonathanGiles Do we have any architectural guidelines on how to offer this sort of thing?

**Comment by reta** [comment]
Thanks a lot, @rickle-msft, really appreciate it !

**Comment by reta** [comment]
@alzimmermsft I think we could close this one, right? Fixed by https://github.com/Azure/azure-sdk-for-java/pull/25004
