### ISSUE TITLE
[FEATURE REQ] Ability to use shared AMQP connection for multiple Event Hubs(in same namespace)

### ISSUE THREAD

**Issue by kunalkukreja** [Azure/azure-sdk-for-java#24371]
**Is your feature request related to a problem? Please describe.**
The EventHubClientBuilder does not provide mechanism to use shared AMQP connection to publish messages to different EventHubs(in same namespace)

**Describe the solution you'd like**
Use single AMQP connection to publish/receive messages to different EventHub in the same namespace.

**Describe alternatives you've considered**
We are not using share connection feature for now. So Each EventHub client use a separate AMQP connection.

**Additional context**
As per the Event Hub documentation it is possible to use single connection for sending/receiving messages from multiple event hub in same namespace.

Check the faq [here](https://docs.microsoft.com/en-us/azure/event-hubs/event-hubs-faq#can-i-use-a-single-advanced-message-queuing-protocol--amqp--connection-to-send-and-receive-from-multiple-event-hubs-)

**Code Snippet**
Sample code to reproduce the scenario :
```java
private static final String connectionString = "MASKED-XXX";

private static final String eventHubName1 = "test-kunal-1";
private static final String eventHubName2 = "test-kunal-2";
private static final String eventHubName3 = "test-kunal-3";

EventHubClientBuilder eventHubClientBuilder = new EventHubClientBuilder().shareConnection();
		// create a producer1 client

		EventHubProducerClient producer1 = eventHubClientBuilder
				.connectionString(connectionString, eventHubName1)
				.buildProducerClient();

		EventHubProducerClient producer2 = eventHubClientBuilder
				.connectionString(connectionString, eventHubName2)
				.buildProducerClient();

		EventHubProducerClient producer3 = eventHubClientBuilder
				.connectionString(connectionString, eventHubName3)
				.buildProducerClient();


		System.out.println("producer1.getEventHubName():" +  producer1.getEventHubName());
		System.out.println("producer2.getEventHubName():" +  producer2.getEventHubName());
		System.out.println("producer3.getEventHubName():" +  producer3.getEventHubName());
```
Here **test-kunal-1, test-kunal-2, test-kunal-3** belong to same namespace so it should be possible to send messages to them using same connection. On debugging more I found out that all producer clients are internally sending data to first event hub(test-kunal-1 in the above code).

![Screenshot 2021-09-27 at 3 51 53 PM](https://user-images.githubusercontent.com/2182987/134893007-7d52d9b7-6f7a-42f2-94c8-8588d96085ca.png)

EventHubAsyncClient.buildAsyncClient() method creates a singleton eventHubConnectionProcessor which is only aware of Single EventHub. All EventHubProducerClient use this singleton connectionProcessor and hence all messages are sent to single Eventhub. 

Refer for more details [here](https://github.com/Azure/azure-sdk-for-java/blob/e3a221b288171e51dd762e0d473e6ea3efa99ad0/sdk/eventhubs/azure-messaging-eventhubs/src/main/java/com/azure/messaging/eventhubs/EventHubClientBuilder.java#L626])

**Setup**
OS: Mac
Library/Libraries: com.azure:azure-messaging-eventhubs:5.7.0
Java version: 11
App Server/Environment: jdk-11.0.11
Frameworks: Spring Boot

**Expected solution specified**
If share connection is used, all producer clients should use same AMQP connection and send/receive messages from different EventHubs if they belong to same namespace. 

If share connection is used and event hubs do not belong to same namespace, exception should be thrown while building the client.

**Information Checklist**
Kindly make sure that you have added all the following information above and checkoff the required fields otherwise we will treat the issuer as an incomplete report
- [ ] Description Added
- [ ] Expected solution specified

**Comment by joshfree** [comment]
Thanks for filing this github issue, @kunalkukreja.  @conniey @anuchandy could you review this feature-request as part of Event Hubs semester planning?
/cc @ramya-rao-a

**Comment by conniey** [comment]
Hey, we have this as a feature already. If you look at the Javadocs for [com.azure.messaging.eventhubs.EventHubClientBuilder](https://docs.microsoft.com/java/api/com.azure.messaging.eventhubs.eventhubclientbuilder?view=azure-java-stable), there is a snippet called: "Creating producers and consumers that share the same connection".

**Comment by kunalkukreja** [comment]
@conniey 
> Hey, we have this as a feature already. If you look at the Javadocs for [com.azure.messaging.eventhubs.EventHubClientBuilder](https://docs.microsoft.com/java/api/com.azure.messaging.eventhubs.eventhubclientbuilder?view=azure-java-stable), there is a snippet called: "Creating producers and consumers that share the same connection".

Multiple producers pushing messages to same event hub using single shared connection is possible. 

What is not possible is pushing messages to different event hubs(in same namespace) using shared connection. This support is documented [here](https://docs.microsoft.com/en-us/azure/event-hubs/event-hubs-faq#can-i-use-a-single-advanced-message-queuing-protocol--amqp--connection-to-send-and-receive-from-multiple-event-hubs-)

I have already posted detailed investigation on my earlier comment.

**Comment by ramya-rao-a** [comment]
Thanks for the clarification @kunalkukreja 

This indeed would be a new feature request.

Adding to the backlog for now, we will revisit it for an investigation in the next semester.

Meanwhile, if you have ideas on how to go about implementing this, please feel free to take a look at our code at https://github.com/Azure/azure-sdk-for-java/tree/main/sdk/eventhubs/azure-messaging-eventhubs

**Comment by woppa684** [comment]
Why would this be a feature request if the FAQ clearly states that this is possible? Is the FAQ wrong? Or does the FAQ imply that it is only possible when you do the whole AMQP part yourself instead of using the client?
