### ISSUE TITLE
Prepare for Netty 5 (Add Netty 5 HttpClient implementation)

### ISSUE THREAD

**Issue by JonathanGiles** [Azure/azure-sdk-for-java#24381]
We should begin the investigation and development of a Netty 5 HttpClient implementation. Ideally it would reuse much of the code already developed for Netty 4, but with the newer dependency. We should not baseline on this as our new HTTP client, as it pushes the JDK baseline to JDK 11, I believe.

**Comment by stliu** [comment]
btw, what about a HttpClient implementation based on spring's WebClient

**Comment by JonathanGiles** [comment]
> btw, what about a HttpClient implementation based on spring's WebClient

Let's chat about this and, if appropriate, create a new issue for this request. If you think it would play more nicely in a Spring context, let's discuss and plan for that!

**Comment by joshfree** [comment]
Adding `Azure.Core.V2` label
