### ISSUE TITLE
Improve java doc's quality for Security modules

### ISSUE THREAD

**Issue by chenrujun** [Azure/azure-sdk-for-java#24412]
Parent issue: #24332

 - [ ] azure-security-keyvault-jca. All classes out of "implementation" package.
 - [ ] spring-cloud-azure-autoconfigure, All classes under com.azure.spring.cloud.autoconfigure.aad package and out of "implementation" package.

**Comment by chenrujun** [comment]
Closing this issue because we will not release spring-security-azure-oauth2-client  any more.

**Comment by chenrujun** [comment]
Reopen this issue because:
1. AAD related logic added into 4.0 version.
2. KeyVault secret belongs to this scope.

**Comment by hui1110** [comment]
The pr to fix the issue has been merged.
