### ISSUE TITLE
Improve java doc's quality for Messaging modules

### ISSUE THREAD

**Issue by chenrujun** [Azure/azure-sdk-for-java#24410]
Parent issue: #24332
Classes that should be improved java doc of are:

- ServiceBusTemplate
- ServiceBusProcessorContainer
- ServiceBusInboundChannelAdapter
- DefaultMessageHandler
- AzureServiceBusProperties
- EventHubsTemplate
- EventHubsProcessorContainer
- EventHubsInboundChannelAdapter
- AzureEventHubsProperties
- CheckpointConfig

Same for eh.

**Comment by yiliuTo** [comment]
Done in pr #26200 and #25969
