### ISSUE TITLE
Improve java doc's quality for Storage + Database modules

### ISSUE THREAD

**Issue by chenrujun** [Azure/azure-sdk-for-java#24411]
Parent issue: #24332

linked PR: https://github.com/Azure/azure-sdk-for-java/pull/26360 (Merged)
linked PR: https://github.com/Azure/azure-sdk-for-java/pull/25896/ (Merged)

**Comment by backwind1233** [comment]
linked PR： https://github.com/Azure/azure-sdk-for-java/pull/25896/

**Comment by backwind1233** [comment]
close this issue since all linked PRs merged
