### ISSUE TITLE
API review for Messaging modules

### ISSUE THREAD

**Issue by chenrujun** [Azure/azure-sdk-for-java#24414]
Parent issue: #24356
- [ ] Messaging modules: @yiliuTo https://github.com/Azure/azure-sdk-for-java/pull/25969
- [ ] Integration modules: @hui1110 https://github.com/Azure/azure-sdk-for-java/pull/25939
- [ ] Stream modules:  @hui1110 https://github.com/Azure/azure-sdk-for-java/pull/25971

**Comment by saragluna** [comment]
Closing in favor of https://github.com/Azure/azure-sdk-for-java/issues/27112.
