### ISSUE TITLE
Create View with Cosmos OLTP (Spark SQL)

### ISSUE THREAD

**Issue by rhsu339** [Azure/azure-sdk-for-java#24429]
Related to previous issue - #24129. 

We are trying to create a live view into a cosmos document and have used the syntax below per guidance from the above issue. 
After running the syntax in a notebook, we are able to see the correct data in that notebook. However, trying to query on cosmosCatalog.ref.table from another notebook using the same cluster (or a different cluster) fails with the error message below. 

It looks like the syntax provided creates a file containing metadata in the specified repository path and a view that is accessible only in the notebook / spark session where the below SQL command is run. It is unclear to us how to persist the view using that file generated. We need to be able to query "cosmosCatalog.ref.table" across different notebooks and after cluster restarts, so please provide further guidance on how to accomplish this. 

If it is helpful we are running these commands in a Databricks environment, and using the older connector for spark 2 we were able to create this view as a database table directly instead of having to create it inside the "cosmosCatalog". With transition to spark 3 we will need a method to recreate this table using the spark 3 connector.

**Error Message when querying view:**
Error in SQL statement: AnalysisException: Catalog namespace is not supported.

Note same error persists even when resetting spark configs below.

**SQL syntax to create live view:** 

spark.conf.set("spark.sql.catalog.cosmosCatalog", "com.azure.cosmos.spark.CosmosCatalog")
spark.conf.set("spark.sql.catalog.cosmosCatalog.spark.cosmos.accountEndpoint", cosmosEndpoint)
spark.conf.set("spark.sql.catalog.cosmosCatalog.spark.cosmos.accountKey", cosmosMasterKey)
spark.conf.set("spark.sql.catalog.cosmosCatalog.spark.cosmos.views.repositoryPath", DBFS_Path)

sql ="""
create table if not exists cosmosCatalog.ref.table
(col1 string,
col2 string,
col3 string)
USING cosmos.oltp
TBLPROPERTIES(isCosmosView = 'True')
OPTIONS (
"spark.cosmos.accountEndpoint" = "XXX",
"spark.cosmos.accountKey" = "XXX",
"spark.cosmos.database" = DB",
"spark.cosmos.container" = "container",
"spark.cosmos.read.customQuery" = "SELECT
t.col1, t.col2, t.col3
from T"
) """
spark.sql(sql)

**Comment by joshfree** [comment]
Tagging @FabianMeiswinkel and @simplynaveen20 from the previous related issue https://github.com/Azure/azure-sdk-for-java/issues/24129

**Comment by kushagraThapar** [comment]
@FabianMeiswinkel  can you please check on this, thanks!

**Comment by TheovanKraay** [comment]
Closing as due to age, but also adding a solution here in case anyone faces similar problem.
 
This should work from different notebooks as long as you define cosmosCatalog parameters as key/value pairs at _cluster_ level instead of in the notebook (in Databricks Advanced Options, spark config), for example:

```shell
spark.sql.catalog.cosmosCatalog.spark.cosmos.accountEndpoint https://youraccounti.documents.azure.com:443/
spark.sql.catalog.cosmosCatalog com.azure.cosmos.spark.CosmosCatalog
spark.sql.catalog.cosmosCatalog.spark.cosmos.views.repositoryPath /views
spark.sql.catalog.cosmosCatalog.spark.cosmos.accountKey *****
```

Then Scala notebook to create just needs like below:

```scala
var sql =s"""
create table if not exists cosmosCatalog.DB.View
(col1 string,
col2 string,
col3 string)
USING cosmos.oltp
TBLPROPERTIES(isCosmosView = 'True')
OPTIONS (
spark.cosmos.database = 'DB',
spark.cosmos.container = 'container',
spark.cosmos.read.customQuery = 'SELECT t.col1, t.col2, t.col3 from t');
"""
spark.sql(sql)
```

separate notebook:

```scala
var sql =s"""
SELECT * FROM cosmosCatalog.DB.View
"""
spark.sql(sql).show
```
