### ISSUE TITLE
[BUG] Eventhub SDK 5.10.0 stops reading Partitions

### ISSUE THREAD

**Issue by the-mod** [Azure/azure-sdk-for-java#24426]
**Describe the bug**
I am using `EventProcessorClient` from `azure-messaging-eventhubs:5.10.0` together with `azure-messaging-eventhubs-checkpointstore-blob:1.9.0` to read Events from Eventhubs.

The reading of Partitions stops out of sudden and does not recover.
This leads to the fact, Events on the affected Partitions are piling up.
Only a restart of the Application mitigates this Issues, but after some time it hit again and again.

***Exception or Stack Trace***
In the logs I see `ReactorDispatcher instance is closed` Exceptions coming from the SDK.
Unfortunately no Stacktrace is provided

**To Reproduce**
Found no way to reproduce due to the fact it hit my Services at random uptime.
It seams also to be independent on the amount of Events read out by the App.

***Code Snippet***
This is my current way to init a EventProcessorClient:
```java
new EventProcessorClientBuilder() 
.connectionString(connString) 
.consumerGroup(cg) 
.checkpointStore(new BlobCheckpointStore(containerClient)) 
.loadBalancingUpdateInterval(Duration.ofSeconds(5)) 
.partitionOwnershipExpirationInterval(Duration.ofSeconds(20)) 
.loadBalancingStrategy(LoadBalancingStrategy.GREEDY) 
.processEventBatch(consumer, batchSize) 
.processError(errorConsumer) 
.processPartitionInitialization(initConsumer) 
.processPartitionClose(closeConsumer) 
.buildEventProcessorClient();
```

**Expected behavior**
Run for ever and ever

**Setup (please complete the following information):**
 - OS: Windows
 - Library/Libraries: `azure-messaging-eventhubs:5.10.0` and `azure-messaging-eventhubs-checkpointstore-blob:1.9.0`
 - Java version: azul JRE 16
 - App Server/Environment: Tomcat 9.0.52
 - Frameworks: Spring Boot 2.4.10

**Comment by joshfree** [comment]
@conniey could you follow up with @the-mod on this `Event Hubs` `ReactorDispatcher instance is closed` issue?

/cc @anuchandy

**Comment by conniey** [comment]
Hey, the ReactorDispatcher instance is closed is misleading (and we plan on suppressing this because it isn't actually the cause of errors). I was wondering if you had any logs so we can see what happened before this exception.

**Comment by the-mod** [comment]
@conniey unfortunately nothing more than that in the timerframe some readers stopped working

**Comment by paalkristian** [comment]
We are experiencing this behavior as well. We are using `azure-messaging-eventhubs:5.10.0` with `azure-spring-cloud-stream-binder-eventhubs:2.8.0`, which is using `azure-messaging-eventhubs-checkpointstore-blob:1.9.0`. Our application runs without problems between 4 and 14 days, before some messages are no longer consumed. 

When I restart the consumer it works as expected again. I might be able to provide logs if it helps.
