### ISSUE TITLE
Reduce timeout of read/query methods [Cosmos DB Java SDK]

### ISSUE THREAD

**Issue by ashu1979** [Azure/azure-sdk-for-java#24422]
The Cosmos DB java SDK has a default fixed timeout of 65sec for read/query operations which is not configurable. This is too high as the HTTP call itself will get timed out before the timeout of 65 seconds reach. Also, as the latency of read/query operations are usually in milliseconds, so waiting for 65 seconds for timeout is very unnecessary. 
In the .NET SDK, this issue was addressed by reducing the default timeout of read/query methods to 5/10 seconds (https://github.com/Azure/azure-cosmos-dotnet-v3/pull/1954). 
Expecting to reduce the default timeouts in Java SDK as well or provide support to accept timeout duration as an argument or configurable.

**Comment by kushagraThapar** [comment]
This is done.
