### ISSUE TITLE
[BUG] Can't set HTTP header value in RequestOptions

### ISSUE THREAD

**Issue by qwordy** [Azure/azure-sdk-for-java#24427]
**Describe the bug**
com.azure:azure-core:1.21.0-beta.1

When I try to modify HTTP header using azure-core, I find I can't set existing header.
SDK sets Content-Type for me when I invoke a method.
```
Content-Type:multipart/form-data
```
I want to add boundary. Calling `RequestOptions.addHeader` can create a result
```
Content-Type:multipart/form-data,boundary=abcde12345
```
What I expect is
```
Content-Type:multipart/form-data; boundary=abcde12345
```
`addHeader` method checks existence of the key. If it exists, append a comma and then value to old value. I want to have full control of header value.

***Exception or Stack Trace***
Add the exception log and stack trace if available

**To Reproduce**

***Code Snippet***
Add the code snippet that causes the issue.

**Expected behavior**

**Screenshots**

**Setup (please complete the following information):**
 - IDE: [e.g. IntelliJ]
 - Library/Libraries: [e.g. com.azure:azure-core:1.16.0 (groupId:artifactId:version)]
 - Java version: [e.g. 8] 
 - App Server/Environment: [e.g. Tomcat, WildFly, Azure Function, Apache Spark, Databricks, IDE plugin or anything special]
 - Frameworks: [e.g. Spring Boot, Micronaut, Quarkus, etc] 

If you suspect a dependency version mismatch (e.g. you see `NoClassDefFoundError`, `NoSuchMethodError` or similar), please provide
- verbose dependency tree (`mvn dependency:tree -Dverbose`)
  
**Additional context**

**Information Checklist**
Kindly make sure that you have added all the following information above and checkoff the required fields otherwise we will treat the issuer as an incomplete report
- [ ] Bug Description Added
- [ ] Repro Steps Added
- [ ] Setup information Added

**Comment by alzimmermsft** [comment]
Thanks for filing this issue @qwordy, what are your thoughts on a method like `RequestOptions.modifyHeaders(Function<HttpHeaders, HttpHeaders> modifier)`?

cc: @srnagar

**Comment by qwordy** [comment]
@alzimmermsft Thank you for quick response. This method is great. It can solve my problem and it is flexible. Can we have a simple method like `setHeader` to set header? It replaces value if the key exists. It adds a header if the key does not exist.

**Comment by alzimmermsft** [comment]
#25176 added `setHeader(String, String)` which resolves the ask here.
