### ISSUE TITLE
[BUG] Key Vault SDK mandates providing key version when constructing CryptographyClient

### ISSUE THREAD

**Issue by SukruthKS** [Azure/azure-sdk-for-java#24444]
**Describe the bug**

The Key Vault SDK always expects the key version field to be provided and non-empty. However, there are many key vault APIs for which the version field is optional. Depending on the API, it can either figure out the right version or infer it as the latest key version. E.g., [Get Key](https://docs.microsoft.com/en-us/rest/api/keyvault/get-key/get-key), [Wrap Key](https://docs.microsoft.com/en-us/rest/api/keyvault/wrap-key/wrap-key) (the doc says the field is `required` for wrap key but it is optional, at least, with an asymmetric key I have tried). 

***Exception or Stack Trace***
Throws this error when the key identifier does include the version.

```
java.lang.IllegalArgumentException: Key version in key id is invalid

	at com.azure.security.keyvault.keys.cryptography.CryptographyAsyncClient.unpackAndValidateId(CryptographyAsyncClient.java:704)
	at com.azure.security.keyvault.keys.cryptography.CryptographyAsyncClient.<init>(CryptographyAsyncClient.java:109)
	at com.azure.security.keyvault.keys.cryptography.CryptographyClientBuilder.buildAsyncClient(CryptographyClientBuilder.java:150)
	at com.azure.security.keyvault.keys.cryptography.CryptographyClientBuilder.buildClient(CryptographyClientBuilder.java:114)
```

**To Reproduce**

```
String keyId = "https://somevault.vault.azure.net/keys/testkey";

CryptographyClient client =
        new CryptographyClientBuilder()
            .keyIdentifier(keyId)
            .credential(
                new ClientSecretCredentialBuilder()
                    .clientId("dummy")
                    .clientSecret("dummy")
                    .tenantId("dummy")
                    .build())
            .buildClient();
```

***Code Snippet***
Same as above.

**Expected behavior**
The SDK should **not** fail the client construction if key version field is missing.

**Screenshots**

**Setup (please complete the following information):**
 - OS: [e.g. iOS] `Linux`
 - IDE: [e.g. IntelliJ] `IntelliJ`
 - Library/Libraries: [e.g. com.azure:azure-core:1.16.0 (groupId:artifactId:version)] `com.azure:azure-security-keyvault-keys:4.3.0-beta.5`
 - Java version: [e.g. 8] `11`
 - App Server/Environment: [e.g. Tomcat, WildFly, Azure Function, Apache Spark, Databricks, IDE plugin or anything special]
 - Frameworks: [e.g. Spring Boot, Micronaut, Quarkus, etc] 

If you suspect a dependency version mismatch (e.g. you see `NoClassDefFoundError`, `NoSuchMethodError` or similar), please provide
- verbose dependency tree (`mvn dependency:tree -Dverbose`)
  
**Additional context**

**Information Checklist**
Kindly make sure that you have added all the following information above and checkoff the required fields otherwise we will treat the issuer as an incomplete report
- [x] Bug Description Added
- [x] Repro Steps Added
- [x] Setup information Added

**Comment by vcolin7** [comment]
Hi @SukruthKS, thank you for reporting this issue. I will bring it up with the team to determine if this is desired behavior. I will also check if this happens in SDKs for languages other than Java.
