### ISSUE TITLE
[BUG] When eventhub sends messages, it may happen that the message is not completely sent.

### ISSUE THREAD

**Issue by ZhuXiaoBing-cn** [Azure/azure-sdk-for-java#24445]
**Describe the bug**
When eventhub sends messages, it may happen that the message is not completely sent. The `tryAdd` method does not detect whether the current batch is full.

***Code Snippet***
AbstractEventHubTemplate.java
```java
return producer.createBatch(options).flatMap(batch -> {
            for (EventData event : events) {
                try {
                    batch.tryAdd(event); 
                } catch (AmqpException e) {
                    LOGGER.error("Event is larger than maximum allowed size. Exception: " + e);
                }
            }
            return producer.send(batch);
        });
```

**Expected behavior**
When the sent message is larger than maxMessageSize, the current batch of messages needs to be sent out first, and then the new batch is used to send the remaining part.

**Setup (please complete the following information):**
 - OS: [windows 10]
 - IDE: [IntelliJ]
 - Library/Libraries: [azure-spring-integration-eventhubs:2.8.0 (groupId:artifactId:version)]
 - Java version: [8] 
 - App Server/Environment: [Tomcat]
 - Frameworks: [Spring Boot] 
  
**Additional context**
`tryAdd` method:
```java
public boolean tryAdd(final EventData eventData) {
        if (eventData == null) {
            throw logger.logExceptionAsWarning(new NullPointerException("eventData cannot be null"));
        }
        EventData event = tracerProvider.isEnabled() ? traceMessageSpan(eventData) : eventData;

        final int size;
        try {
            size = getSize(event, events.isEmpty());
        } catch (BufferOverflowException exception) {
            throw logger.logExceptionAsWarning(new AmqpException(false, AmqpErrorCondition.LINK_PAYLOAD_SIZE_EXCEEDED,
                String.format(Locale.US, "Size of the payload exceeded maximum message size: %s kb",
                    maxMessageSize / 1024),
                contextProvider.getErrorContext()));
        }

        synchronized (lock) {
            if (this.sizeInBytes + size > this.maxMessageSize) {
                return false;
            }

            this.sizeInBytes += size;
        }

        this.events.add(event);
        return true;
    }
```

**Information Checklist**
Kindly make sure that you have added all the following information above and checkoff the required fields otherwise we will treat the issuer as an incomplete report
- [x] Bug Description Added
- [x] Repro Steps Added
- [x] Setup information Added

**Comment by jialigit** [comment]
@ZhuXiaoBing-cn need to have a clear thinking and design of the semantic for this batch sending method. As per the expected behavior mentioned above, the following points should be closely considered in my view:
 1.  The original logic is to discard the data if the batch is full, as the snippet shows:
```
//EventDataBatch.java line 84
....
synchronized(this.lock) {
                if (this.sizeInBytes + size > this.maxMessageSize) {
                    return false;
                }

                this.sizeInBytes += size;
            }

            this.events.add(event);
```
This may lead to the result that "the message is not completely sent" problem.

2. The expected behavior will be create a new batch data and send the remaining part.  So the input events data is to be sent in a couple of "batches", and then the overall size of this "batches" should be limited?

**Comment by jialigit** [comment]
merged
