### ISSUE TITLE
[FEATURE REQ] Provide oauth private_key_jwt (aka cert based auth) client auth for spring boot starter

### ISSUE THREAD

**Issue by sander-su** [Azure/azure-sdk-for-java#24449]
**Is your feature request related to a problem? Please describe.**
For security reasons we would like to do a AAD oauth client authentication using certificates (private_key_jwt) with azure-spring-boot-starter-active-directory 
https://docs.microsoft.com/en-us/azure/active-directory/develop/active-directory-certificate-credentials

**Describe the solution you'd like**
Configuring oauth private_key_jwt client auth for auth code flow in the yaml config by suppling the key/cert.

**Describe alternatives you've considered**
Basic auth is not good enough

**Additional context**
With the release of spring security 5.5 private_key_jwt has been build into the platform.
https://docs.spring.io/spring-security/site/docs/5.5.0/reference/html5/#authenticate-using-private_key_jwt
However the oauth spec does not cover the x5t header which AAD needs so that also needs to be added.
Using the azure-spring-boot-starter-active-directory  bring added functionality for token mapping etc which is why we would like to use it.

**Information Checklist**
Kindly make sure that you have added all the following information above and checkoff the required fields otherwise we will treat the issuer as an incomplete report
- [X] Description Added
- [X] Expected solution specified

**Comment by chenrujun** [comment]
Hi, @sander-su .
Thanks for reaching out.
Your request make sense.
I added to `[2022] January` milestone, which means it will be released before `2022-01-07` if everything goes well.

**Comment by chenrujun** [comment]
Closing this issue. Because in spring-cloud-azure 4.0, there is no starter for Azure Active Directory, we will provide samples to demonstrate how to use Spring Security with Azure Active Directory.

Please use this issue to track this feature request: https://github.com/Azure-Samples/spring-boot-application-with-azure-active-directory/issues/1
