### ISSUE TITLE
Confusing version compatibility indications for Spring Boot starters

### ISSUE THREAD

**Issue by jhyot** [Azure/azure-sdk-for-java#24469]
The information regarding version compatibility between Azure Spring Boot Starter and Spring Boot is somewhat confusing and inconsistent.

On the main [readme](https://github.com/Azure/azure-sdk-for-java/blob/main/sdk/spring/README.md) it says:
> This repository supports Spring Boot 2.2.x, 2.3.x and 2.4.x.

But Spring Boot 2.5 is already out, no mention of it here. Also no mention of it in the version matrix further down in the same readme.
In that version matrix, Starter 3.9.0 is indicated for Spring Boot 2.4.x, except for azure-spring-boot-starter-keyvault-certificates, where it is 3.2.0.

But then, on the [wiki page](https://github.com/Azure/azure-sdk-for-java/wiki/Spring-Versions-Mapping), Spring Boot 2.5 is explicitly mentioned as supported, and for Spring Boot 2.4 only Starters up to 3.5 seem to be supported, and 3.6+ for Spring Boot 2.5.

azure-spring-boot-starter-keyvault-certificates 3.2.0 doesn't seem to fit at all into the matrix on the wiki page.

**Now for my specific question:** Which version of azure-spring-boot-starter-keyvault-**secrets** should I use with Spring Boot 2.4?

**Comment by mrm9084** [comment]
@jhyot It looks like 

<dependency>
    <groupId>com.azure.spring</groupId>
    <artifactId>azure-spring-boot-starter-keyvault-secrets</artifactId>
    <version>3.5.0</version>
</dependency>

Is the latest release that was build with Spring Boot 2.4.

**Comment by joshfree** [comment]
Hi @jhyot, thanks for pointing out that our Azure Spring documentation here could be more clear.  Someone from the `azure-spring` team will follow up with you shortly. /cc @stliu

**Comment by chenrujun** [comment]
Closing this issue because:
1. [Wiki](https://github.com/Azure/azure-sdk-for-java/wiki/Spring-Versions-Mapping) page updated.
2. Readme updated in [azure-spring-cloud-4.0](https://github.com/Azure/azure-sdk-for-java/tree/feature/azure-spring-cloud-4.0/sdk/spring) branch.  This branch will merge to main branch around 2021-12-30. It's tracked by this issue: https://github.com/Azure/azure-sdk-for-java/issues/24362
