### ISSUE TITLE
Make app-configuration's developing version align to other spring-cloud-azure-starters. 

### ISSUE THREAD

**Issue by chenrujun** [Azure/azure-sdk-for-java#24461]
As title.

**Comment by mrm9084** [comment]
@chenrujun I don't think this is needed. Also we will be mostly synced up again once we go to 4.0.

**Comment by chenrujun** [comment]
@mrm9084, OK. Then please close this issue. And update related content here: https://github.com/Azure/azure-sdk-for-java/blob/feature/azure-spring-cloud-4.0/sdk/boms/azure-spring-cloud-dependencies/pom.xml#L47
