### ISSUE TITLE
[FEATURE REQ] Add dev guide for azure-spring-boot-starter-keyvault-certificates

### ISSUE THREAD

**Issue by zhichengliu12581** [Azure/azure-sdk-for-java#24466]
**Is your feature request related to a problem? Please describe.**
[This  tutorial](https://docs.microsoft.com/en-us/azure/developer/java/spring-framework/configure-spring-boot-starter-java-app-with-azure-key-vault-certificates) only show how azure-spring-boot-starter-keyvault-certificates work with Managed Identity, which works as a quick start, we need to add a Tutorial for dev guide for using a client ID and secret.
Related issue: https://github.com/Azure/azure-sdk-for-java/issues/23588

**Describe the solution you'd like**
Add dev guide show how azure-spring-boot-starter-keyvault-certificates work with Managed Identity and using a client ID and secret.

**Describe alternatives you've considered**

**Additional context**

**Information Checklist**
Kindly make sure that you have added all the following information above and checkoff the required fields otherwise we will treat the issuer as an incomplete report
- [x] Description Added
- [x] Expected solution specified

**Comment by stliu** [comment]
closing it, no one ask for it
