### ISSUE TITLE
[BUG] java.lang.NoClassDefFoundError: com/fasterxml/jackson/databind/json/JsonMapper

### ISSUE THREAD

**Issue by gterminator** [Azure/azure-sdk-for-java#24478]
**Describe the bug**
If I build the library Version 12.14.0 and/or 12.13.0 I get this exception.

***Exception or Stack Trace***
Caused by: java.lang.NoClassDefFoundError: com/fasterxml/jackson/databind/json/JsonMapper
	at com.azure.core.util.serializer.JacksonAdapter.<init>(JacksonAdapter.java:133)
	at com.azure.storage.blob.implementation.util.ModelHelper.<clinit>(ModelHelper.java:53)
	at com.azure.storage.blob.BlobUrlParts.parse(BlobUrlParts.java:371)
	at com.azure.storage.blob.BlobContainerClientBuilder.endpoint(BlobContainerClientBuilder.java:147)
	at com.azure.storage.blob.BlobContainerClientBuilder.connectionString(BlobContainerClientBuilder.java:301)

**To Reproduce**
Build a Project without jackson. Which Jackson version I have to use and which component? Trying for an hour now which one has this class.

**Expected behavior**
I can start the project without errors.

**Setup (please complete the following information):**
 - Library/Libraries: 12.14.0 and 12.13.0
 - Java version: 8
 - Frameworks: Spring Boot

**Comment by pennstatephil** [comment]
This happens to be the same problem I brought up in #7694, and [asked about on StackOverflow](https://stackoverflow.com/questions/69394794/including-azure-blob-storage-library-causes-problems-in-spring)

Hoping to get some official support from Microsoft. The linked issue is assigned to @alzimmermsft in case you have anything to advise us!

**Comment by gterminator** [comment]
I my point of view it's a problem in the dependency tree. Maybe the didn't assigned a required jackson version in its pom. 
Now we have to exclude our jackson versions from our dependency, great library.

**Comment by alzimmermsft** [comment]
Thanks for filing this issue @gterminator.

Both `azure-storage-blob` 12.14.0` and `12.13.0` can use either Jackson `2.12` or `2.11`, preferably `2.12`. `JsonMapper` missing is a bit odd as that was introduced in Jackson `2.10`, so it seems the application is resolving to a much older version of Jackson.

Are there any other environments or frameworks being used aside from Spring? Such as Azure Databricks, Functions, Tomcat, etc

**Comment by gterminator** [comment]
Thanks for the information that jackson has this class with 2.10. My stable spring boot is working with 2.9.
I think there is no other way handle it, I have to update to at least 2.11.

**Comment by gterminator** [comment]
UPDATE: I upgraded from spring boot 2.1.17.RELEASE to 2.3.12.RELEASE. 
After that I got some netty problems (method not found in netty 0.9.20) I downgraded the azure library to 12.12.0 now its working.

Netty Report:
```

Description:

An attempt was made to call a method that does not exist. The attempt was made from the following location:

    com.azure.core.http.netty.NettyAsyncHttpClientBuilder.build(NettyAsyncHttpClientBuilder.java:119)

The following method did not exist:

    'reactor.netty.transport.ClientTransport reactor.netty.http.client.HttpClient.resolver(io.netty.resolver.AddressResolverGroup)'

The method's class, reactor.netty.http.client.HttpClient, is available from the following locations:

    jar:file:/C:/Users/Max/.m2/repository/io/projectreactor/netty/reactor-netty/0.9.20.RELEASE/reactor-netty-0.9.20.RELEASE.jar!/reactor/netty/http/client/HttpClient.class

The class hierarchy was loaded from the following locations:

    reactor.netty.http.client.HttpClient: file:/C:/Users/Max/.m2/repository/io/projectreactor/netty/reactor-netty/0.9.20.RELEASE/reactor-netty-0.9.20.RELEASE.jar

```

**Comment by alzimmermsft** [comment]
Ah, didn't realize that Spring Boot 2.1 was being used. The current SDKs are baselined against Spring Boot 2.5, and Spring Boot 2.4 had dependencies which had major breaking changes compared to those used in Spring Boot 2.3.

If possible, I'd recommend upgrading to 2.5 but 2.4 should work.
