### ISSUE TITLE
[FEATURE REQ] Support OIDC flow without getting access token in spring-cloud-azure-starter-active-directory

### ISSUE THREAD

**Issue by zhichengliu12581** [Azure/azure-sdk-for-java#24483]
**Is your feature request related to a problem? Please describe.**
Now our `azure-spring-boot-starter-active-directory` only support [authorization type](https://github.com/Azure/azure-sdk-for-java/blob/a3507ca530dbeea8e654ed82e313b018b0ec00d9/sdk/spring/azure-spring-boot/src/main/java/com/azure/spring/aad/AADAuthorizationGrantType.java#L12): client_credentials, authorization_code, on_behalf_of, azure_delegated. If the application want to access user info by simplest "OIDC" flow, our only choice is to use authorization_code, which will sends "response_type=code" even if we only need "id_token".
Related issue: https://github.com/Azure/azure-sdk-for-java/issues/23876

**Describe the solution you'd like**
Maybe we can add authorization type like "id_token", and custom which resolve in our `AADOAuth2AuthorizationRequestResolver` 

**Describe alternatives you've considered**
We may need to override `AADWebSecurityConfigurerAdapter` because which use `azure` as `accessTokenResponseClient` and which authorization type is always "authorization_code".

**Additional context**

**Information Checklist**
Kindly make sure that you have added all the following information above and checkoff the required fields otherwise we will treat the issuer as an incomplete report
- [x] Description Added
- [x] Expected solution specified

**Comment by saragluna** [comment]
@chenrujun could you please update the status / milestone of this issue?
