### ISSUE TITLE
[FEATURE REQ] Port should not be removed from Key Vault Key Id when Cryptography Client is initialized

### ISSUE THREAD

**Issue by nagyesta** [Azure/azure-sdk-for-java#24508]
**Is your feature request related to a problem? Please describe.**
I wanted to use a local Key Vault stub with the Key Vault Cryptography Client and found that the port number is removed from the  key Id when the ```unpackAndValidateId``` method is processing it.

https://github.com/Azure/azure-sdk-for-java/blob/75ff34269b54cc069ee845b5c6de33b34ae5d501/sdk/keyvault/azure-security-keyvault-keys/src/main/java/com/azure/security/keyvault/keys/cryptography/CryptographyAsyncClient.java#L799-L804

Due to this, any proxies or stubs not running on the default ```HTTPS``` port will not be able to encrypt or decrypt data.

**Describe the solution you'd like**
It would be desired to check whether the port is explicitly set and include it when the endpoint value is calculated.

**Describe alternatives you've considered**
It is very hacky, but I have no better alternatives at this point than replacing the ```hostname:port``` with ```hostname___port``` when the key Id is set in the client builder then, using my own ```ApacheHttpClient``` I am replacing it back to the original before sending the ```HTTP``` request.

**Additional context**
N/A

**Information Checklist**
Kindly make sure that you have added all the following information above and checkoff the required fields otherwise we will treat the issuer as an incomplete report
- [x] Description Added
- [x] Expected solution specified

**Comment by joshfree** [comment]
@vcolin7 could you please follow up with @nagyesta on this github issue?
