### ISSUE TITLE
[BUG] Key size is not copied to the create request in case of OCT keys in azure-security-keyvault-keys.

### ISSUE THREAD

**Issue by nagyesta** [Azure/azure-sdk-for-java#24507]
**Describe the bug**
Key size is not copied over in case OCT keys are being created using the Key Vault Key Client. Due to this, the request won't have the key size in it, so I assume the default key size will be used.

***Exception or Stack Trace***
N/A

**To Reproduce**
1. Create a key with 128 as size.
2. Try using an encryption algorithm with 128 in the name e.g. A128CBCPAD
3. Observe the output

***Code Snippet***
https://github.com/Azure/azure-sdk-for-java/blob/e89f24349028fb3c0f5fe75ebff3cded7a787e0d/sdk/keyvault/azure-security-keyvault-keys/src/main/java/com/azure/security/keyvault/keys/KeyAsyncClient.java#L553-L558

Should be:
```java
        KeyRequestParameters parameters = new KeyRequestParameters()
            .setKty(createOctKeyOptions.getKeyType())
            .setKeySize(createOctKeyOptions.getKeySize()) // <- change
            .setKeyOps(createOctKeyOptions.getKeyOperations())
            .setKeyAttributes(new KeyRequestAttributes(createOctKeyOptions))
            .setTags(createOctKeyOptions.getTags())
            .setReleasePolicy(createOctKeyOptions.getReleasePolicy());
```

**Expected behavior**
The size in the steps to reproduce should match AFAIK, therefore the call will fail until broken, then succeed when fixed (I assume, didn't try it).

**Screenshots**
N/A

**Setup (please complete the following information):**
 - OS: Any
 - IDE: Any
 - Library/Libraries: com.azure:azure-security-keyvault-keys:4.3.3
 - Java version: Any
 - App Server/Environment: Any
 - Frameworks: Any

**Additional context**
N/A

**Information Checklist**
Kindly make sure that you have added all the following information above and checkoff the required fields otherwise we will treat the issuer as an incomplete report
- [x] Bug Description Added
- [x] Repro Steps Added
- [x] Setup information Added

**Comment by joshfree** [comment]
@vcolin7 could you follow up with @nagyesta on this github issue?

**Comment by vcolin7** [comment]
> @vcolin7 could you follow up with @nagyesta on this github issue?

Sure thing :)
