### ISSUE TITLE
Split global revapi.json suppressions into targeted areas

### ISSUE THREAD

**Issue by conniey** [Azure/azure-sdk-for-java#24519]
Currently, all our suppressions live in one giant revapi.json file. It would be nice to split them.
https://revapi.org/revapi/0.14.1/configuration.html#_multi_file_configuration

May be dependent on: https://github.com/Azure/azure-sdk-for-java/issues/22692

**Comment by alzimmermsft** [comment]
@conniey is this required anymore now that there is a global linting pipeline to catch changes which may introduce linting errors?
