### ISSUE TITLE
Review RntbdThreadFactory's Usage of SecurityManager

### ISSUE THREAD

**Issue by alzimmermsft** [Azure/azure-sdk-for-java#24514]
As of Java 17 `SecurityManager` has been marked as deprecated and for removal, for more information about it review [this JEP](https://openjdk.java.net/jeps/411). Given it's new status, the usage of `SecurityManager` in `RntbdThreadFactory` should be reviewed.

cc: @kushagraThapar

**Comment by kushagraThapar** [comment]
Adding @xinlian12  for visibility!

**Comment by alzimmermsft** [comment]
Resolved by #24562
