### ISSUE TITLE
[FEATURE REQ] ServiceBusSenderClient sendMessage method doesn't return MessageId after pushing the message to the queue/topic

### ISSUE THREAD

**Issue by vpeddada** [Azure/azure-sdk-for-java#24537]
**Is your feature request related to a problem? Please describe.**
When we try to send a message to a queue or a topic using the following method,
**com.azure.messaging.servicebus.ServiceBusSenderClient.sendMessage(ServiceBusMessage message)**
it doesn't return **MessageId** of the message  in the response. If a **MessageId** is not assigned in the send operation, then Service Bus assigns a GUID internally for that message for duplicate detection. 

**Describe the solution you'd like**
After successful execution of **sendMessage** operation, **MessageId** should be available as response_(currently the type of send is Void)_ or in the **ServiceBusMessage** object.

**Describe alternatives you've considered**
Tried to do a **getMessageId()** on the **ServiceBusMessage** object after successful send operation. But it returns null but not the system generated GUID.  

**Additional context**
Availability of MessageId in the send operation response is critical in the real time distributed systems to uniquely identify each message and cross verify on the receiver's end.

**Information Checklist**
Kindly make sure that you have added all the following information above and checkoff the required fields otherwise we will treat the issuer as an incomplete report
- [^] Description Added
- [^] Expected solution specified

**Comment by joshfree** [comment]
@ki1729 could you please follow up with @vpeddada on their github issue?

**Comment by ki1729** [comment]
Hi @vpeddada, 
Thank you for requesting this feature.
I agree that message Id is useful to cross verify consistency between the sender and reciever. We expect the Message ID to be set by the application, as that is where there is enough context to determine if you are trying to send the same message or a different one.
In case that is not provided we treat every message as unique and send them through, and to make sure we don't do duplicate sends, if the message Id is not set, we set it to a guid. This guid would be meaningless to the application layer, so we don't return the value back. And also as we expect the application to be setting the message id, passing it back is redudant and not useful.

Just to get some context around this request, it would be great if you can answer a couple more questions.
1. Are there any restrictions / issues on setting the message id in the applicaiton before sending the message?
2. If so, please let us know what they are and we can work on those going forward.

So as the next step forward here, if there are issues in setting the message id, we would love to know more about your use case. If there are no issues, then I would recommend setting the message id in the application layer before sending the message. 
That way you already have the data and it can be cross verified with the reciever. In case you don't want to attach any meaningful message id, setting a GUID just as we would have done would work too

**Comment by ki1729** [comment]
Glad I could clear things up @vpeddada
