### ISSUE TITLE
Reduce calls to HttpHeaders.toMap() in storage code

### ISSUE THREAD

**Issue by JonathanGiles** [Azure/azure-sdk-for-java#24534]
In `StorageSharedKeyCredentialPolicy.process`, we call `HttpHeaders.toMap()`, which results in a copying of the HttpHeaders data structure into a HashMap. This data structure is passed into `StorageSharedKeyCredential.generateAuthorizationHeader` and then on to `buildStringToSign`, where the map is looked into for various values.

There is an equivalent code path in `TableAzureNameKeyCredentialPolicy`.

The call to toMap costs around 1.2-1.5% of CPU time in certain benchmarks, and seems redundant. We could improve performance by passing around the HttpHeaders instance itself, and calling get() on that, rather than doing the intermediate conversion to a HashMap.

**Comment by kasobol-msft** [comment]
@vcolin7 Could you please take care of the tables part ?
