### ISSUE TITLE
ConsumptionManager: "Error 400 - EventDate should have beginning range value"

### ISSUE THREAD

**Issue by juergenbr** [Azure/azure-sdk-for-java#24543]
When trying to get the reservation transactions for a billing account using the SDK, I get the following error:
`Status code 400, "{"error":{"code":"400","message":"EventDate should have beginning range value. (Request ID: b26b5bdc-b5d5-4ccf-9c74-606dd852cf68)"}}"`

My code looks as follows:
`PagedIterable<ReservationTransaction> resTransactions = consumptionManager.reservationTransactions().list("xxxxxxx", "properties/eventDate+ge+2020-01-01+AND+properties/eventDate+le+2021-10-01",Context.NONE);`

Performing the same request via the REST API returns the list of reservation transactions:
`curl --location --request GET 'https://management.azure.com/providers/Microsoft.Billing/billingAccounts/xxxxxxx/providers/Microsoft.Consumption/reservationTransactions?$filter=properties/eventDate+ge+2020-01-01+AND+properties/eventDate+le+2021-10-01&api-version=2019-10-01' \`

Used SDK Version:
compile("com.azure.resourcemanager:azure-resourcemanager:2.8.0")
compile("com.azure.resourcemanager:azure-resourcemanager-consumption:1.0.0-beta.2")

**Comment by joshfree** [comment]
@weidongxu-microsoft could you please follow up with @juergenbr on their github issue?

**Comment by weidongxu-microsoft** [comment]
@juergenbr 
Would the code being this?
```
PagedIterable<ReservationTransaction> resTransactions = consumptionManager.reservationTransactions().list("xxxxxxx", "properties/eventDate ge 2020-01-01 AND properties/eventDate le 2021-10-01",Context.NONE);
```

You only replace space to `+` in query. When calling SDK you do not need to do the replacement.

**Comment by juergenbr** [comment]
@weidongxu-microsoft I followed this example which also escapes spaces with `+`
https://github.com/Azure/azure-sdk-for-java/blob/main/sdk/consumption/azure-resourcemanager-consumption/src/samples/java/com/azure/resourcemanager/consumption/ReservationTransactionsListSamples.java

**Comment by juergenbr** [comment]
@weidongxu-microsoft thanks for the confirmation that the codegen sample call is indeed different from the msdoc.
I'll close the issue since the cause of the problem is identified, we were able to get it working by calling the REST API directly with escaped characters instead of using the SDK.
