### ISSUE TITLE
Build SDK quickstart tooling

### ISSUE THREAD

**Issue by lmazuel** [Azure/azure-sdk-for-java#24566]
Creating a tool based on templating and various input for service team, in order to create a perfectly viable project in one call. The only acceptable input is : a Swagger and a clone of the language repo.

For instance “dotnet new sdk swagger.json –name=MyServiceName” (dotnet is an example, pick what is idiomatic to your repo). This will create:
- A compilable/shippable package in the right folder
- A sample test (simple test with assert True)
- A sample of sample (placeholder for a sample)
- A basic Readme 
- Of course the LLC code 😊

Beware of the update scenario (package exists already): it maybe be necessary to make either the tooling smart, or to have second option like “dotnet update sdk swagger.json”.

**Comment by weidongxu-microsoft** [comment]
Probably similar thing as https://github.com/Azure/azure-sdk-for-java/tree/main/eng/mgmt/automation, which is used for swagger integration and mgmt release automation.

**Comment by weidongxu-microsoft** [comment]
Tasks
- pom.xml https://github.com/Azure/autorest.java/pull/1223
- readme.md
- blank test
- convenient script

**Comment by weidongxu-microsoft** [comment]
Sample generated module from the script https://github.com/Azure/azure-sdk-for-java/pull/25233
