### ISSUE TITLE
[FEATURE REQ] Create article about clients lifetime management

### ISSUE THREAD

**Issue by kasobol-msft** [Azure/azure-sdk-for-java#24576]
Customers often don't understand relationships between clients and client builders as well as their thread safety guarantees (or lack of). We could use something like https://devblogs.microsoft.com/azure-sdk/lifetime-management-and-thread-safety-guarantees-of-azure-sdk-net-clients/ for Java.
Additional aspect that should be covered there is the HttpClient sharing and how lack of that can impact perf.

**Comment by jfrazee** [comment]
@alzimmermsft @kasobol-msft Is this something that's expected to be forthcoming?

**Comment by dotneutron** [comment]
@alzimmermsft Is there any update on this? I'm still wondering about the thread safety / reusability of several clients:

* [com.azure.messaging.servicebus.ServiceBusSenderClient](https://github.com/Azure/azure-sdk-for-java/blob/main/sdk/servicebus/azure-messaging-servicebus/src/main/java/com/azure/messaging/servicebus/ServiceBusSenderClient.java)
* [com.azure.storage.file.datalake.DataLakeServiceClient](https://github.com/Azure/azure-sdk-for-java/blob/main/sdk/storage/azure-storage-file-datalake/src/main/java/com/azure/storage/file/datalake/DataLakeServiceClient.java)
  * [com.azure.storage.file.datalake.DataLakeFileSystemClient](https://github.com/Azure/azure-sdk-for-java/blob/main/sdk/storage/azure-storage-file-datalake/src/main/java/com/azure/storage/file/datalake/DataLakeFileSystemClient.java) - given the fs already exists, should it be reused?
    * [com.azure.storage.file.datalake.DataLakeDirectoryClient](https://github.com/Azure/azure-sdk-for-java/blob/main/sdk/storage/azure-storage-file-datalake/src/main/java/com/azure/storage/file/datalake/DataLakeDirectoryClient.java) - given the directory already exists, should it be reused?

Given N requests, creating a fresh `ServiceBusSenderClient` (try-with-resources) for each one is pretty terrible for memory usage from my tests, perhaps even leading to socket exhaustion (?) with higher loads. Making it "one-per-concern" within the application, e.g., one per topic, consumes less resources.

Creating a fresh `DataLakeServiceClient` with all of its sub-clients isn't that much of a resource sinkhole, but is it worth it?
