### ISSUE TITLE
Azure Identity - handling DefaultAzureCredential's accessToken expiry

### ISSUE THREAD

**Issue by KristofNalesnyik** [Azure/azure-sdk-for-java#24613]
**Query/Question**
 Does Azure Java SDK handles accessToken & refreshToken expiry or is it my task to handle expiry? If it is my task, how to do it?

***Why is this not a Bug or a feature Request?***
-

**Setup (please complete the following information if applicable):**
 - OS: Windows10
 - IDE: IntelliJ
 - Library/Libraries: com.azure:azure-identity:1.3.6

I use DefaultAzureCredential, as it works locally and also on cloud when ManagedIdentity is needed for authenticating to KeyVault.

I intend to deploy a function app to Azure Cloud, where I have the following static constructor of my class containing the functions:

    DefaultAzureCredential credential = new DefaultAzureCredentialBuilder().build();                 
    CertificateClient certificateClient = new CertificateClientBuilder()
                 .vaultUrl(KEY_VAULT_URI)
                 .credential(credential)
                 .buildClient();
    
    SecretClient secretClient = new SecretClientBuilder()
                 .vaultUrl(KEY_VAULT_URI)
                 .credential(credential)
                 .buildClient();
    
    service = new Service(certificateClient, secretClient);

I would like to create the service only once with certificateClient and secretClient.
Then if accessToken expires, get new accessToken.

**Comment by joshfree** [comment]
@g2vinay could you please follow up with @nalesnyik on their question regarding Access tokens and Refresh tokens
