### ISSUE TITLE
Add Messaging Troubleshooting guide for Java to docs.microsoft.com

### ISSUE THREAD

**Issue by joshfree** [Azure/azure-sdk-for-java#24623]
Tracking issue to add conceptual doc topics, such as troubleshooting tips, to https://docs.microsoft.com/en-us/azure/developer/java/sdk for Messaging (AMQP based) client libraries.

/cc @conniey @anuchandy @ki1729

**Comment by conniey** [comment]
Add documentation about low-level receivers:
* Document that the Receiver(s) can throw; hence application should be prepared to handle it - Shutdown-Gracefully Or App-level Retry.
    * After retries are exhausted, it can throw.
* Inform the spring team building on the top of Low-Level Receiver to expect this;
    * The az-spring libs should either do their own retry or notify necessary spring hooks so that the app can Shutdown-Gracefully.

**Comment by conniey** [comment]
Should do this before #20991
