### ISSUE TITLE
[BUG] BlobContainerClientBuilder: container name is ignored if provided before connection string

### ISSUE THREAD

**Issue by lmolkova** [Azure/azure-sdk-for-java#24631]
**Describe the bug**
The container name is ignored if provided before connection string on the `BlobContainerAsyncClient`.

**To Reproduce**
***Code Snippet***
```java
String conStr = "DefaultEndpointsProtocol=https;AccountName=<acc>;AccountKey=<token>;EndpointSuffix=core.windows.net";
BlobContainerAsyncClient client =  new BlobContainerClientBuilder()
		.connectionString(conStr)
		.containerName("container")
		.buildAsyncClient();
System.out.println(client.getBlobContainerName()); // prints "container"
```

If I provide container name before connection string, container name dissapers
```java

BlobContainerAsyncClient client =  new BlobContainerClientBuilder()
		.containerName("container")
		.connectionString(conStr)
		.buildAsyncClient();
System.out.println(client.getBlobContainerName()); // prints "$root"
```
**Expected behavior**
Order of builder methods does not matter.

**Setup (please complete the following information):**
 - OS: windows 10
 - IDE: IntelliJ
 - Library/Libraries: com.azureazure-storage-blob:12.14.0
 - Java version: 11

**Comment by alzimmermsft** [comment]
I'd wager, that unless the connection string actually contains a container name reverting the container back to `$root` would be an unexpected behavior for most customers. If we want to leave this as-is until we get more data on this, we can add an informational log when connection string results in the container or blob name being mutated.
