### ISSUE TITLE
[FEATURE REQ] Supports Spring Cloud Sleuth for Azure AMQP-based service client

### ISSUE THREAD

**Issue by moarychan** [Azure/azure-sdk-for-java#24652]
**Is your feature request related to a problem? Please describe.**
You can find the whole [feature proposal here](https://github.com/Azure/azure-sdk-for-java/issues/21969).

When the Spring Cloud Sleuth is enabled in an application, Sleuth will record the activities of Azure SDK services, which includes the HTTP-based service clients. 
- AMQP based client:
  - Event Bub service client
  - Service Bus service client
 
**Describe the solution you'd like**
Use `com.azure.core.util.tracing.Tracer` to enable the SDK AMQP-based service tracing.

**Information Checklist**
Kindly make sure that you have added all the following information above and checkoff the required fields otherwise we will treat the issuer as an incomplete report
- [x] Description Added
- [x] Expected solution specified

**Comment by saragluna** [comment]
Closing this in favor of Spring Boot 3.x micrometer new observe API.
