### ISSUE TITLE
[QUERY] download blob in parallel using openinputstream

### ISSUE THREAD

**Issue by ihudedi** [Azure/azure-sdk-for-java#24672]
Hi,
I would like to know how can I download blob using stream in paralel.i found via downloadtofile it's exist but i would like to know if it can be using openinputstream or downloadstream.
Thanks,
Itay.

**Comment by ihudedi** [comment]
Hi @rickle-msft
We transfer files from azure to any destination.the destination is outputstream.when downloadtofile occur do you save all parts in the file system and after that you merge to one file?
Thanks,
Itau

**Comment by ibrahimrabab** [comment]
Hi @ihudedi ,

Just following up on this issue. Has this issue been resolved? If so, we can go ahead and close this. If not, can you please let us know what blockers you are running into, or any other questions you may have?

Thank you!
