### ISSUE TITLE
EngSys: Spell Check for Java

### ISSUE THREAD

**Issue by danieljurek** [Azure/azure-sdk-for-java#24692]
* Is it possible to export the public API to files? This way we can spell check the public API surface nightly and provide an extra layer of protection against spelling errors in customer-facing portions of our code.

* Spell checking for PR changes -- We currently have warnings for these but do not block the PR. To enable blocking PRs we'll need to establish a baseline of spelling errors and directories to ignore (and open issues to fix those). Do we want to open issues at the level of the package or the service? **OPEN AT THE PACKAGE LEVEL**

Once we have answers to the first question assign back to me and I can get started on the code changes to add this to the engineering system. We'll meet again before I open the issues 🦖

**Comment by danieljurek** [comment]
I've run a preliminary check on relevant files in the `sdk/` folder. There are many spell check error detections, and it might not make sense to opt out so many. I've also scrubbed through many of the common detections and added those to words to treat as valid: https://github.com/Azure/azure-sdk-for-java/blob/djurek/spelling/.vscode/cspell.json 

Packages with no errors: 79
Packages with errors: 277

Next steps: Let's discuss how to move forward here.

**Comment by danieljurek** [comment]
@pallavit -- After our discussion we have the following opt in/outs: 

Packages with errors (opt out): 238
Packages with no errors (opt in): 125

Put this file in the root of the repo and run in PowerShell (be warned, it might be faster to use pwsh in Ubuntu in WSL because of small file i/o perf): 
https://gist.github.com/danieljurek/151a876576747f63fd584ae4edb40236

Guidance for false positives, etc: https://github.com/Azure/azure-sdk-tools/blob/main/doc/common/spellcheck.md 

My changes are in a branch off the main repo, plz contribute your cspell.json updates to: https://github.com/Azure/azure-sdk-for-java/blob/djurek/spelling/.vscode/cspell.json

**Comment by joshfree** [comment]
@jairmyree please take a look

**Comment by joshfree** [comment]
@jairmyree I believe this work is long since completed; can you please update / close?
