### ISSUE TITLE
VirtualMachine.powerState() sometimes returns null

### ISSUE THREAD

**Issue by aaalex474** [Azure/azure-sdk-for-java#2471]
Azure java sdk version 1.3.0
Sometimes VirtualMachine.powerState() returns null.

I use it in background VM management. I stop/start/create spare VMs in periodic task.
What should I do if powerState is null? 

Refresh the VM (or do refreshInstanceView) until the powerState isn't null? Do I risk to stuck doing it infinitely?

Now I ignore the VM. As the consequence I have sporadic and useless VMs stop/start/create.

**Comment by vhvb1989** [comment]
Hello @aaalex474 

I am sorry about you didn't get a sooner answer on this
Do you still need help? Let me know and I would be happy to assist.

Note: As part of repository cleaning effort, this issue will be closed by Sep 20 if no response is received from submitter and/or not further action is required.

**Comment by aaalex474** [comment]
Hi,

I found a workaround for me. I consider the power state as "unknown" if it's null.
It's up to you if want or not to fix the bug.

**Comment by vhvb1989** [comment]
@aaalex474 , I have tagged this issue for more people visibility.
Can you also add more details for this like:
- The create() Vm code for those you are getting `powerState()` null

And about what you mention:
```
Refresh the VM (or do refreshInstanceView) until the powerState isn't null? Do I risk to stuck doing it infinitely?
```
I wouldn't expect powerState to be always NULL and get stuck. If this is something you tried and got, please feel free to create a new issue for it.  And another option is to add a retryPolicy counter to stop refreshing after N times and take another action.

**Comment by yungezz** [comment]
HI @xccc-msft could you pls help to look at it.

**Comment by xccc-msft** [comment]
@aaalex474 Are you still facing same issue? Now we have latest version as 1.35.0. Please feel free to upgrade SDK and let us know if you meet any issue.

**Comment by aaalex474** [comment]
Hi,

Sorry, I don't work on the related project any more.

Regards

**Comment by yungezz** [comment]
thanks, will close the issue now. feel free to create new issue if met any other error

**Comment by barryku** [comment]
@xccc-msft, does 1.35.0 fix the issue?  We are using 1.31, and still see the problem.  We have planned to call refreshInstanceView() as workaround, but wold rather not doing it if 1.35 has the fix.  Do you know if calling refreshInstanceView() will consume API call quota?  We are already running into API limits from time to time, so are concerned calling the method will add up to our API usage.

**Comment by xccc-msft** [comment]
@barryku I tried to create a virtual machine and get power state. It worked for me. How often you met this issue?

And I checked the method and found the logic inside `powerState()` is to call `refreshInstanceView()` too. Can you try to capture the request/response when you meet the issue again?

**Comment by barryku** [comment]
@xccc-msft, we have seen at least 128 times in the last 90 days probably over 100 subscriptions.  I checked the code at [1], and it uses this.instanceView().  Although instanceView() calls refreshInstanceView(), it only does it when virtualMachineInstanceView is null.  Are you sure virtualMachineInstanceView when it's not null will always contain powerState without calling refreshInstanceView() again?

[1] https://github.com/Azure/azure-sdk-for-java/blob/master/sdk/compute/mgmt/src/main/java/com/azure/resourcemanager/compute/implementation/VirtualMachineImpl.java#L1633

**Comment by xccc-msft** [comment]
@barryku I just added label for service attention here. I think what we can update is the logic to call refreshInstanceView() from SDK end. When power state is null, then we have to send refreshInstanceView request. Before that, we might need service team to clarify if it is bug when returning response without power state.

**Comment by barryku** [comment]
@xccc-msft, thank you for following this up.  Another question about refreshInstanceView() is whether it will use the API limit quota?  We have been running into API limit on VM resources (providers/Microsoft.Compute/virtualMachines) from time to time, and hope calling it won't contribute to additional API usage.

**Comment by xccc-msft** [comment]
@barryku It looks the answer is `YES`. In the response of instance view, the header contains `x-ms-ratelimit-remaining-subscription-reads` and `x-ms-ratelimit-remaining-resource`.
