### ISSUE TITLE
Review the artifact names and their dependencies before release

### ISSUE THREAD

**Issue by backwind1233** [Azure/azure-sdk-for-java#24722]
Review the artifact names and their dependencies before release.
- Go through all released artifacts, make sure they are following the same principle.	
  - Make a table with new and old artifact names, compare with old names.
- Investigate whether we need it or not, such as `azure-spring-cloud-starter-cache` and `spring-cloud-azure-starter-eventhubs-kafka`.

**Comment by backwind1233** [comment]
Maybe book a meeting to discuss it is a good way.

**Comment by saragluna** [comment]
After discussion with @stliu, we should remove the starters for cache and kafka.

**Comment by backwind1233** [comment]
close this
there are two pr linked with this issue, they are all merged.
https://github.com/Azure/azure-sdk-for-java/pull/25335
https://github.com/Azure/azure-sdk-for-java/pull/24940
