### ISSUE TITLE
Spring Boot applicaiton won't even start until "azure.storage" properties are correctly filled

### ISSUE THREAD

**Issue by djechelon** [Azure/azure-sdk-for-java#24768]
I am having a problem developing multi-purpose multi-customer library code.

In order to support either multiple cloud platforms or just multiple-customers scenarios, I am implementing an abstraction of a `File Repository` over both Azure blob storage **and** local file system (for developers or on-prem customers).

The idea is that I want Azure configuration properties not to be mandatory. If there is an Azure blob configuration, **and** a `BlobContainerClient` **and** the blob container name (in the project's properties), then the file repository should be implemented by Azure.

On no-property startup (with H2 database) I have written my own logic to switch for a temporary directory that, just like an in-memory H2 database, gets cleared on shutdown.

Reference: https://github.com/Azure/azure-sdk-for-java/blob/26e7c0c89d7efb17499272bfc41e458225b7cf17/sdk/spring/azure-spring-boot/src/main/java/com/azure/spring/autoconfigure/storage/StorageAutoConfiguration.java

The problem is that I am unable to start my application **if** the Azure SDK jar is present in the dependencies **without** setting the blob account (which could still be a fake until I try to connect).

I would suggest the maintainers to amend the `StorageAutoConfiguration` class to adhere to Spring Boot's zero-configuration paradigm, thus not blocking the application from loading when configuration is blank. Instead, the `BlobServiceClientBuilder` should not be created by the Bean Factory and thus the bean unavailable.

Calling code can then use `@ConditionalOnBean(BlobServiceClient.class)` to determine whether Azure services are configured or not.

Thank you for your kind attention and please share your thoughts with me.

**Comment by backwind1233** [comment]
@djechelon we are working on our new design of project and will release the beta versions this month,
here is the repo [branch](https://github.com/Azure/azure-sdk-for-java/tree/feature/azure-spring-cloud-4.0) and Reference [wiki](https://github.com/Azure/azure-sdk-for-java/wiki/Spring-Cloud-Azure-4.0-Reference) you can check.

**Comment by backwind1233** [comment]
close this issue, track in [Release Spring Cloud for Azure 4.0.0-beta.1](https://github.com/Azure/azure-sdk-for-java/issues/24260)
the issue will be resolved after the  4.0.0-beta.1 libraries released.
