### ISSUE TITLE
Gremlin Support for Cosmosdb

### ISSUE THREAD

**Issue by backwind1233** [Azure/azure-sdk-for-java#24773]
Please tell us how you are using Spring Data Gremlin for Cosmos DB and how important it is to you by voting on this issue with the thumbs up emoji.

**Comment by seanli1988** [comment]
Please tell us how you are using Gremlin with Cosmos DB, and how important it is to support the Cosmos DB Gremlin API by vote on this issue with the thumbs up emoji.

**Comment by PatrickMadden** [comment]
We use Spring Data Gremlin for both Neptune and Cosmos. Please keep supporting it.

**Comment by codyzwief** [comment]
We are using CosmosDB/Gremlin, and are looking to use spring/java to expose some data via microservices. Would love this to get formal support, even if it's just community support! I can look to help make contributions.

**Comment by seanli1988** [comment]
We will re-evaluate Gremlin support in our next 6-month planning cycle in September. We welcome code contributions from anyone if we have enough evidence to prioritize this investment. In the meantime, please keep commenting and voting on this issue.

Spring on Azure team

**Comment by evgenykrass** [comment]
We definitely need a Gremlin supported. This is an interface we use to work with Cosmos database as a graph database.
This is critical for us, so please keep it alive.

**Comment by kumardeepesh05** [comment]
We are using this dependency for storing data in graph to maintain relationship between entities. We are exploring How to connect with multiple graphs from one application. It would be really helpful if you guide us. Please don't stop supporting it.
