### ISSUE TITLE
[BUG] Exhausting INFO logging

### ISSUE THREAD

**Issue by khauser** [Azure/azure-sdk-for-java#24779]
**Describe the bug**
My log is full with `Connection ID:... connected to server: amqps://...` entries. Could they be assigned to DEBUG instead of INFO?

We are using `implementation group: 'com.azure.spring', name: 'azure-spring-boot-starter-servicebus-jms', version: "3.9.0"`

**Comment by yiliuTo** [comment]
Hi @khauser , this log is from the class of **org.apache.qpid.jms.JmsConnection** in a 3rd party library **qpid-jms-client**, I think you can modify your log configuration and set the log level of org.apache.qpid.jms.JmsConnection as you need.
