### ISSUE TITLE
[QUERY] Supported EncryptionAlgorithm for decryption

### ISSUE THREAD

**Issue by eric-genesys** [Azure/azure-sdk-for-java#24774]
**Query/Question**
We are using CryptographyClient to decrypt string that encrypted externally. can you let us know what are the supported EncryptionAlgorithm?

***Why is this not a Bug or a feature Request?***
Just Q&A

**Setup (please complete the following information if applicable):**
 - IDE: [e.g. IntelliJ]
 - Library/Libraries: [e.g. com.azure:azure-core:1.16.0 (groupId:artifactId:version)]
 
 **Information Checklist**
 Kindly make sure that you have added all the following information above and checkoff the required fields otherwise we will treat the issuer as an incomplete report
- [ ] Query Added
- [ ] Setup information Added

**Comment by eric-genesys** [comment]
Our string was encrypted using AES 256 CBC, what should the right EncryptionAlgorithm to choose if it is supported

When I set EncryptionAlgorithm.A256CBC, I got error this is not supported by Azure

**Comment by vcolin7** [comment]
Commenting in case you (or anyone) still need this information: Currently, the Key Vault service does not support encrypt/decrypt operations using symmetric keys (like AES-based keys). You can perform said operations locally by creating a [`CryptographyClient`](https://learn.microsoft.com/en-us/java/api/overview/azure/security-keyvault-keys-readme?view=azure-java-stable#create-cryptography-client) with a valid `JsonWebKey` containing a key's private component, as shown here:

```
CryptographyClient cryptoClient = return new CryptographyClientBuilder()
    .jsonWebKey(key)
    .buildClient();
```

However, if you first need to retrieve the private component of a key from the Key Vault service, you'll need to set your key's `exportable` property to `true` and then use the [release](https://learn.microsoft.com/en-us/rest/api/keyvault/keys/release/release?tabs=HTTP) operation. I'll add a sample of how to do this later this week :)
