### ISSUE TITLE
BlobOutputStream#close should be idempotent

### ISSUE THREAD

**Issue by djechelon** [Azure/azure-sdk-for-java#24782]
References:

https://github.com/Azure/azure-sdk-for-java/blob/3ace711dcfc67d45deb8a36f30ded342d9d68045/sdk/storage/azure-storage-blob/src/main/java/com/azure/storage/blob/specialized/BlobOutputStream.java#L108-L119

https://github.com/Azure/azure-sdk-for-java/blob/26e7c0c89d7efb17499272bfc41e458225b7cf17/sdk/storage/azure-storage-common/src/main/java/com/azure/storage/common/StorageInputStream.java#L139-L147

The `java.lang.Closeable#close` [contract](https://docs.oracle.com/javase/8/docs/api/java/lang/AutoCloseable.html) does not **mandate** idempotency of the method.

However, in the Java ecosystem it is normal that a `Stream` object may be closed multiple times. Instead, `BlobOutputStream`, unlike `BlobInputStream`, can be closed only once. It is also recommended by Javadoc

> Note that unlike the close method of Closeable, this close method is not required to be idempotent. In other words, calling this close method more than once may have some visible side effect, unlike Closeable.close which is required to have no effect if called more than once. However, implementers of this interface are strongly encouraged to make their close methods idempotent.

I would like to raise the inconsistency between the two symmetric classes.

Also, the feature renders unusable the following code block that stacks output streams one above another for `FilterOutputStream` processing

```java
        try (BlobOutputStream blob = blobClient.getBlockBlobClient().getBlobOutputStream();
             BufferedOutputStream buffer = new BufferedOutputStream(blob);
             DigestOutputStream digest = new DigestOutputStream(buffer, getChecksumDigest());
             InputStream is = payload.getInputStream();
        ) {
            byteSize = IOUtils.copyLarge(is, digest);
            checksum = encodeHexString(digest.getMessageDigest().digest());
        }
```

The above code works if `blob` is type `FileOutputStream`, as the order is

- Open blob
- Open buffer
- Open digest
- Open is
- Close is
- Close digest
  - Cascade close buffer
    - Cascade close blob
- Close buffer
  - Cascade close blob

It is very helpful to try-with-multiple resources as it renders code more readable.

To ensure that every stream gets closed (otherwise evil could happen), the code fragment would be rendered to

```java
        try {
            BufferedOutputStream buffer = new BufferedOutputStream(blob);
            try {
                try (DigestOutputStream digest = new DigestOutputStream(buffer, getChecksumDigest());
                     InputStream is = payload.getInputStream();
                ) {
                    byteSize = IOUtils.copyLarge(is, digest);
                    checksum = encodeHexString(digest.getMessageDigest().digest());
                }
            } finally {
                IOUtils.closeQuietly(buffer);
            }
        } finally {
            IOUtils.closeQuietly(blob);
        }
```

(Author's edit) I have discovered that Apache Commons's IOUtils does not work because the exception thrown here is a `RuntimeException` than an `IOException`, so I had to refactor this code in a more complicated way with try-catch-es.

Suggesting to make `BlobOutputStream#close` method idempotent to adhere to the `FilterOutputStream` contract and stack streams.

Thank you for your time.

**Comment by djechelon** [comment]
No, I am sure, by design, that blobs never exist when I run my tests. My code is a Junit test drawing a random guid as a file name. And the file is deleted afterwards.
So, the file does not exist, 100%

**Comment by rickle-msft** [comment]
I see. That is a different exception than I anticipated. Thank you for sharing that. We can't change existing behavior, but what I think we can do is add an option to the BlobOutputStreamOptions class that is something to the effect of "ignoreMultipleClose" or something like that which turns close into a no-op after the first call. Would that be an acceptable path forward for you?

@alzimmermsft do you have any concerns about this approach?
