### ISSUE TITLE
Migrate test recording framework to unified test framework

### ISSUE THREAD

**Issue by alzimmermsft** [Azure/azure-sdk-for-java#24792]
- [ ] Start (and install if needed) and stop test proxy from Test Framework
- [ ] Load session records from test proxy in Playback mode
- [ ] Send session records to test proxy in Record mode
- [ ] Translate custom sanitizers to Test Proxy sanitizers
- [ ] Create a migration guide, similar to https://github.com/Azure/azure-sdk-for-python/blob/main/doc/dev/test_proxy_migration_guide.md
- [ ] File tracking GitHub issues for any test suites that need updates or followups by specific SDK area owners (see .github/CODEOWNERS file) with links to the migration guide / contact info

**Comment by weidongxu-microsoft** [comment]
@joshfree 

We probably try start with a few newly added LLC clients, instead of the whole mgmt, which requires weeks of recording time and lots of Azure resources.

Also this likely require pipeline change, to run the Docker container.

@alzimmermsft We will subscribe on this issue to have follow-up from you or anyone working on it in data-plane.

Known docs on test proxy https://github.com/Azure/azure-sdk-tools/tree/main/tools/test-proxy

**Comment by scbedd** [comment]
@weidongxu-microsoft WRT to the `random names or variables` side, the test-proxy actually has [a feature](https://github.com/Azure/azure-sdk-tools/tree/main/tools/test-proxy/Azure.Sdk.Tools.TestProxy#storing-variables) that can help you out. It is just a wrapper around exactly the `variables` that you link to!

To take advantage of it, when POST-ing to `/record/stop`, you can provide an additional json payload

```json
{
   "Key1": "Value1"
}
```

Then, when POST-ing to `/Playback/Start`, you will receive the above dictionary in the response body.

Right now it expects a dictionary, but there is [an issue filed](https://github.com/Azure/azure-sdk-tools/issues/2257) to not enforce the shape of the object.

**Comment by weidongxu-microsoft** [comment]
Thanks Scott! Got it. Nice job!

Then the question to Java is whether we build another azure-core-test for integration with the test proxy, or let every client do their own job.
E.g. current random name is done in `TestResourceNamer` in azure-core-test.

**Comment by billwert** [comment]
> Then the question to Java is whether we build another azure-core-test for integration with the test proxy

I'm looking at this right now. (I'm new to the team - this is my MQ project. :)) It's my thought that things like this should be centralized, but I'm still exploring the various clients/libraries to understand current usage.

**Comment by weidongxu-microsoft** [comment]
@billwert

@haolingdong-msft will also help with the test proxy. Therefore if we got any major update, or draft of the design, please do share with us.
My thought is whether we add a subclass of `TestBase` to support test proxy. Just a thought, not any concrete design.

**Comment by haolingdong-msft** [comment]
Hi @billwert, are you working on implementing the shared part (in azure-core-test) for integrating with TestProxy to support PLAYBACK and RECORD mode, as well as preparing the migration doc? Is there any update on this? Please include @weidongxu-microsoft and me if there any update or pr, so that we are aligned.
/cc @alzimmermsft

**Comment by billwert** [comment]
Hey sorry for the quietness here. Yes, I am working on this - getting ramped on the space took me a little longer than I'd hoped. I'm working on the prototype and hope to have something we can look at this week.

My intent is to do the implementation inside of the current types which hopefully will not require much change at the individual test levels.

**Comment by haolingdong-msft** [comment]
> Hey sorry for the quietness here. Yes, I am working on this - getting ramped on the space took me a little longer than I'd hoped. I'm working on the prototype and hope to have something we can look at this week.
> 
> My intent is to do the implementation inside of the current types which hopefully will not require much change at the individual test levels.

Thanks @billwert for the update! I'm working on the management plane part to integrate with the new test framework which depends on this issue. Please include @weidongxu-microsoft and me if there is any pr or update.

**Comment by haolingdong-msft** [comment]
@billwert WRT the prototype you mentioned last week, may I know is there any update and progress?
/cc @alzimmermsft

**Comment by haolingdong-msft** [comment]
Hi @billwert and @alzimmermsft, may I know is there any update on this issue?
