### ISSUE TITLE
Validate URI from CosmosProperties doesn't account for local cosmos DB emulator?

### ISSUE THREAD

**Issue by Jayadeep2308** [Azure/azure-sdk-for-java#24862]
**Query/Question**
As part of a Different PR (https://github.com/Azure/azure-sdk-for-java/pull/23641), A new Method validateUri checks for regex (http[s]{0,1}://.*.documents.azure.com.*"). But cosmos local emulator DB URI is https://localhost:8081.  I just wanted to check if it was intentional?

**Comment by joshfree** [comment]
@kushagraThapar could you please help @Jayadeep2308 with their question?
