### ISSUE TITLE
[Java] Upgrade service documents from Track 1 to Track 2

### ISSUE THREAD

**Issue by ArthurMa1978** [Azure/azure-sdk-for-java#24861]
80% documents on Docs should be updated

**Comment by haolingdong-msft** [comment]
Document that needs to be updated: https://microsoftapc-my.sharepoint.com/:x:/g/personal/haolingdong_microsoft_com/Ed1Dh8cKlf9Gq_URq_QfDK8B2X4V-j3NqvKwBXIMav7KDQ?e=nSyCqp
