### ISSUE TITLE
Username and password issue while using ClientSecretCredential

### ISSUE THREAD

**Issue by arpit77** [Azure/azure-sdk-for-java#24884]
**Query/Question**
I am not able to figure out how to generate a graph api client client when i am using the JAVA sdk.

***Why is this not a Bug or a feature Request?***
This is neither a bug or feature because there are resources stating that the client is getting created.

**Setup:**
 - OS: macOS
 - IDE: IntelliJ
 - Library/Libraries: microsoft graph 5.0.0 and azure identity 1.3.1
 
 **Information Checklist**
I am using the following code to get the user when I have created a client. I am calling the method using a spring rest controller get mapping.: 

//***********Code starts here******

final ClientSecretCredential clientSecretCredential = new ClientSecretCredentialBuilder()
                .clientId(CLIENT_ID)
                .clientSecret(CLIENT_SECRET)
                .tenantId(TENANT_ID)
                .build();

        final TokenCredentialAuthProvider tokenCredAuthProvider = new TokenCredentialAuthProvider(scopesList, clientSecretCredential);

        final GraphServiceClient graphClient = GraphServiceClient
                .builder()
                .authenticationProvider(tokenCredAuthProvider)
                .buildClient();

        final User me = graphClient.me().buildRequest().get();

// ************Code Ends***********

When this service is called on the browser using the endpoint the the following screen shot appears. For that screen shot I am not able to figure out what should be the username and password to be entered.
![Screenshot 2021-10-19 at 1 25 30 PM (2)](https://user-images.githubusercontent.com/47794307/137867512-5f7bac2b-c7a5-4a35-b5ef-9fbfdc57d744.png)

When I am hitting my url, automatically gets directed to /login endpoint. I mean to say when I am hitting localhost:8080/api/getUser it changes to localhost:8080/login as shown in the screenshot attached.

**Comment by joshfree** [comment]
>  I am not able to figure out what should be the username and password to be entered.

Hi @arpit77, this is likely something that was specified when setting up the service via the Azure portal.  Folks working in the open source github repo won't be able to assist with what the username/password for your specific service.

I would login to the Azure Portal and look there.

Please let me know if there's anything else or if I misunderstood the question.  I'll be closing this issue out, but feel free to reactivate it or open a new issue with more details.

Thanks
