### ISSUE TITLE
What happened to version 12.6.1?

### ISSUE THREAD

**Issue by jsquire** [Azure/azure-sdk-for-java#24889]
# Issue Transfer

This issue has been transferred from the Azure SDK for .NET repository, [#24818](https://github.com/Azure/azure-sdk-for-net/issues/24818).

## Details

I noticed that [12.6.1](https://mvnrepository.com/artifact/com.azure/azure-storage-blob/12.6.1) is 404ing on maven central.  Is there any reason for this?

**Comment by amishra-dev** [comment]
If you need further help
please create a ticket at aka.ms/azsupt.

Issue Type: Technical
Service Type: Blob Storage
Summary: #JavaSDKv12
Problem type: Development
Problem subtype: Client library or SDK

**Comment by atrauzzi** [comment]
Put 12.6.1 back?

**Comment by amishra-dev** [comment]
Can you move to 12.7? that is only minimal changes over 12.6.1. And none of your dependencies would change.
