### ISSUE TITLE
Could not connect Cosmos DB after upgrading SDK 4.19.1

### ISSUE THREAD

**Issue by PKWM** [Azure/azure-sdk-for-java#24901]
**Query/Question**
Error connecting to Cosmos DB 

***Why is this not a Bug or a feature Request?***
Trying to find the documentation to upgrade the SDK

**Setup (please complete the following information if applicable):**
 ,"type":"WARN","logLine":97,"className":"io.netty.channel.ChannelInitializer","methodName":"exceptionCaught","log":"Failed to initialize a channel. Closing: [id: 0x3e1044df]","stackTrace":"java.util.NoSuchElementException: reactor.left.sslHandler\n\tat io.netty.channel.DefaultChannelPipeline.getContextOrDie(DefaultChannelPipeline.java:1073)\n\tat io.netty.channel.DefaultChannelPipeline.addAfter(DefaultChannelPipeline.java:302)\n\tat io.netty.channel.DefaultChannelPipeline.addAfter(DefaultChannelPipeline.java:290)\n\tat reactor.netty.tcp.SslProvider.addSslReadHandler(SslProvider.java:600)\n\tat reactor.netty.tcp.SslProvider.addSslHandler(SslProvider.java:562)\n\tat reactor.netty.http.client.HttpClientConfig$HttpClientChannelInitializer.onChannelInit(HttpClientConfig.java:824)\n\tat reactor.netty.transport.TransportConfig$TransportChannelInitializer.initChannel(TransportConfig.java:394)\n\tat io.netty.channel.ChannelInitializer.initChannel(ChannelInitializer.java:129)\n\tat io.netty.channel.ChannelInitializer.handlerAdded(ChannelInitializer.java:112)\n\tat io.netty.channel.AbstractChannelHandlerContext.callHandlerAdded(AbstractChannelHandlerContext.java:938)\n\tat io.netty.channel.DefaultChannelPipeline.callHandlerAdded0(DefaultChannelPipeline.java:609)\n\tat io.netty.channel.DefaultChannelPipeline.addFirst(DefaultChannelPipeline.java:181)\n\tat io.netty.channel.DefaultChannelPipeline.addFirst(DefaultChannelPipeline.java:358)\n\tat io.netty.channel.DefaultChannelPipeline.addFirst(DefaultChannelPipeline.java:339)\n\tat reactor.netty.resources.DefaultPooledConnectionProvider$PooledConnectionAllocator$PooledConnectionInitializer.initChannel(DefaultPooledConnectionProvider.java:542)\n\tat io.netty.channel.ChannelInitializer.initChannel(ChannelInitializer.java:129)\n\tat io.netty.channel.ChannelInitializer.handlerAdded(ChannelInitializer.java:112)\n\tat io.netty.channel.AbstractChannelHandlerContext.callHandlerAdded(AbstractChannelHandlerContext.java:938)\n\tat io.netty.channel.DefaultChannelPipeline.callHandlerAdded0(DefaultChannelPipeline.java:609)\n\tat io.netty.channel.DefaultChannelPipeline.access$100(DefaultChannelPipeline.java:46)\n\tat io.netty.channel.DefaultChannelPipeline$PendingHandlerAddedTask.execute(DefaultChannelPipeline.java:1463)\n\tat io.netty.channel.DefaultChannelPipeline.callHandlerAddedForAllHandlers(DefaultChannelPipeline.java:1115)\n\tat io.netty.channel.DefaultChannelPipeline.invokeHandlerAddedIfNeeded(DefaultChannelPipeline.java:650)\n\tat io.netty.channel.AbstractChannel$AbstractUnsafe.register0(AbstractChannel.java:502)\n\tat io.netty.channel.AbstractChannel$AbstractUnsafe.access$200(AbstractChannel.java:417)\n\tat io.netty.channel.AbstractChannel$AbstractUnsafe$1.run(AbstractChannel.java:474)\n\tat io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:164)\n\tat io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:469)\n\tat io.netty.channel.kqueue.KQueueEventLoop.run(KQueueEventLoop.java:293)\n\tat io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:986)\n\tat io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)\n\tat io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)\n\tat java.lang.Thread.run(Thread.java:748)\n"}
"className":"com.azure.cosmos.implementation.RxGatewayStoreModel","methodName":"lambda$toDocumentServiceResponse$3","log":"Network failure","stackTrace":"java.net.UnknownHostException: <hostname>\n\tat java.net.InetAddress.getAllByName0(InetAddress.java:1281)\n\tat java.net.InetAddress.getAllByName(InetAddress.java:1193)\n\tat java.net.InetAddress.getAllByName(InetAddress.java:1127)\n\tat io.netty.util.internal.SocketUtils$9.run(SocketUtils.java:169)\n\tat io.netty.util.internal.SocketUtils$9.run(SocketUtils.java:166)\n\tat java.security.AccessController.doPrivileged(Native Method)\n\tat io.netty.util.internal.SocketUtils.allAddressesByName(SocketUtils.java:166)\n\tat io.netty.resolver.DefaultNameResolver.doResolveAll(DefaultNameResolver.java:50)\n\tat io.netty.resolver.SimpleNameResolver.resolveAll(SimpleNameResolver.java:79)\n\tat io.netty.resolver.SimpleNameResolver.resolveAll(SimpleNameResolver.java:71)\n\tat io.netty.resolver.InetSocketAddressResolver.doResolveAll(InetSocketAddressResolver.java:73)\n\tat io.netty.resolver.InetSocketAddressResolver.doResolveAll(InetSocketAddressResolver.java:31)\n\tat io.netty.resolver.AbstractAddressResolver.resolveAll(AbstractAddressResolver.java:158)\n\tat reactor.netty.transport.TransportConnector.doResolveAndConnect(TransportConnector.java:283)\n\tat reactor.netty.transport.TransportConnector.lambda$connect$6(TransportConnector.java:110)\n\tat reactor.core.publisher.MonoFlatMap$FlatMapMain.onNext(MonoFlatMap.java:125)\n\tat reactor.netty.transport.TransportConnector$MonoChannelPromise._subscribe(TransportConnector.java:579)\n\tat reactor.netty.transport.TransportConnector$MonoChannelPromise.lambda$subscribe$0(TransportConnector.java:499)\n\tat io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:164)\n\tat io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:469)\n\tat io.netty.channel.kqueue.KQueueEventLoop.run(KQueueEventLoop.java:293)\n\tat io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:986)\n\tat io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)\n\tat io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)\n\tat java.lang.Thread.run(Thread.java:748)\n"}

 
 **Information Checklist**
 Kindly make sure that you have added all the following information above and checkoff the required fields otherwise we will treat the issuer as an incomplete report
- [x] Query Added
- [x] Setup information Added

**Comment by kushagraThapar** [comment]
This has been fixed, @PKWM pls test on the latest version.
