### ISSUE TITLE
For testing purpose

### ISSUE THREAD

**Issue by sima-zhu** [Azure/azure-sdk-for-java#24919]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b1c37654-5107-cd1c-9dde-ec03941520a6
* Version Independent ID: b7e2dd1d-9f9e-f322-e963-7eb371938c9d
* Content: [Azure Template client library for Java](https://review.docs.microsoft.com/en-us/java/api/overview/azure/sdk-template-readme?view=azure-java-preview&branch=main)
* Content Source: [docs-ref-services/preview/sdk-template-readme.md](https://github.com/Azure/azure-docs-sdk-java/blob/master/docs-ref-services/preview/sdk-template-readme.md)
* Service: **templatetemplate**
* Product: **azure**
* Technology: **azure**
* GitHub Login: @sima-zhu, danieljurek
* Microsoft Alias: **sizhu, danieljurek**

**Comment by joshfree** [comment]
@sima-zhu can this and https://github.com/Azure/azure-sdk-for-java/issues/24914 be closed?
