### ISSUE TITLE
[BUG] - Connection issues

### ISSUE THREAD

**Issue by juanmarques** [Azure/azure-sdk-for-java#24925]
Hi Azure team,
I have recently noticed some slow down my developed backed processes, where I have a quartz scheduler that keeps monitoring the Sharepoint list from time to time. In this process, we check for all files and its columns properties to look for a specific column that acts as a trigger.

I enabled the debugs level, and I could see the following message: it stays for 2-4 minutes, then it recovers and continues to process.

***Stack Trace***
```
14 Oct 2021 18:17:37,949 DEBUG [reactor-http-epoll-4] (Loggers.java:249) - [id: 0x6c5fd5b7, L:/192.168.0.158:46742 ! R:login.microsoftonline.com/20.190.160.75:443] onStateChange(PooledConnection{channel=[id: 0x6c5fd5b7, L:/192.168.0.158:46742 ! R:login.microsoftonline.com/20.190.160.75:443]}, [disconnecting])

14 Oct 2021 18:20:06,061 DEBUG [ForkJoinPool.commonPool-worker-9] (AuthenticationResultSupplier.java:123) - [Correlation ID: 8627418c-27c8-45fd-b42d-f7170afb5180] Access Token was returned
14 Oct 2021 18:20:06,062 INFO [ForkJoinPool.commonPool-worker-9] (ClientLogger.java:338) - Azure Identity => getToken() result for scopes [https://graph.microsoft.com/.default]: SUCCESS
14 Oct 2021 18:20:06,275 DEBUG [ForkJoinPool.commonPool-worker-9] (AuthenticationResultSupplier.java:123) - [Correlation ID: 44782c9a-6e5b-4b18-b4dc-6dd03d1c927f] Access Token was returned
14 Oct 2021 18:20:06,275 INFO [ForkJoinPool.commonPool-worker-9] (ClientLogger.java:338) - Azure Identity => getToken() result for scopes [https://graph.microsoft.com/.default]: SUCCESS
14 Oct 2021 18:20:06,617 INFO [main] (SharePointGraphIntegrationTest.java:149) - Filename test.pdf
```

 - OS: Ubuntu 20.04.3 LTS
 - IDE: IntelliJ
 - Library/Libraries: com.microsoft.graph:5.5.0 , azure-identity:1.2.5
 - Java version: 1.8
 - App Server/Environment:Tomcat
 - Frameworks: Spring Boot
  
I appreciate any help you can provide.

Juan Marques

**Comment by juanmarques** [comment]
Hi, sorry could someone please follow up on this?

**Comment by joshfree** [comment]
Closing out this issue from 2021 (no response from Graph team, unfortunately) - but given the lack of discussion on the thread I'm concluding this issue is no longer applicable.  If it is, please reactivate and/or reach out via https://github.com/Azure/azure-sdk-for-java/blob/main/SUPPORT.md#azure-support-tickets.
