### ISSUE TITLE
What is the difference between azureSasCredential vs sasToken

### ISSUE THREAD

**Issue by ihudedi** [Azure/azure-sdk-for-java#24948]
Hi
I noticed that there 2 types of credentials to same credentails.
For sasToken we can use:
new BlobServiceClientBuilder().sasToken(sasToken)
and we can use:
new BlobServiceClientBuilder().credential(azureSasCredential)  --> where the azureSasCredential contains the sasToken
Is there different between them?
Thanks,
Itay

**Comment by rickle-msft** [comment]
When we build the pipeline, the sas token string will get converted into a credential object, so they should be functionally the same. The `sasToken` method was added for GA way back when. The `AzureSasTokenCredential` was added later to support the introduction of this type in core. It may also be more convenient as it is an overload of the `credential` method.

**Comment by rickle-msft** [comment]
I am going to close this issue as I believe the question has been addressed. Please feel free to comment further if you still need help here.
