### ISSUE TITLE
[KeyVault] - Address archboard review comments

### ISSUE THREAD

**Issue by maorleger** [Azure/azure-sdk-for-java#24951]
Address the following comments from the archboard review:

- [x] getCryptographyClient parameters: name -> keyName and version -> keyVersion
- [x] getRandomBytes should return a byte array instead of a model. You likely have started with this implementation so it should hopefully be an easy change

Note that there is still an open discussion for renaming SKR parameters and response values, but for now the above two items are sufficient

**Comment by vcolin7** [comment]
Other changes need to be implemented as well:

- Remove an exports statement for `com.azure.security.keyvault.keys.implementation` in `module-info.java`. <sup>[1](https://apiview.dev/Assemblies/Review/c8986bdf9191490b875c0a925246193d?diffRevisionId=ec4d9dfda8184e3a9f519e5dc459d73b&doc=False&diffOnly=False#6f9403846d824dbbaf25fecab330764b)</sup>
- Add the `@ServiceMethod` annotation to `KeyClient`'s `getRandomBytes()` and `getRandomBytesWithResponse()`. <sup>[2](https://apiview.dev/Assemblies/Review/c8986bdf9191490b875c0a925246193d?diffRevisionId=ec4d9dfda8184e3a9f519e5dc459d73b&doc=False&diffOnly=False#dcbc86f5545c48a5ac4f9b8688773a25)</sup>
- `KeyReleasePolicy`
    - Rename `data` to `encodedPolicy`<sup>[3](https://github.com/Azure/azure-sdk-for-net/issues/24876)</sup> and changed its type from `byte[]` to `BinaryData`.<sup>[4](https://apiview.dev/Assemblies/Review/c8986bdf9191490b875c0a925246193d?diffRevisionId=ec4d9dfda8184e3a9f519e5dc459d73b&doc=False&diffOnly=False#1d3836a11b2f4670b52c294cdb41e9e9)</sup>
    - Flatten `KeyRotationPolicyProperties` into `KeyRotationPolicy`.<sup>[5](https://apiview.dev/Assemblies/Review/c8986bdf9191490b875c0a925246193d?diffRevisionId=ec4d9dfda8184e3a9f519e5dc459d73b&doc=False&diffOnly=False#4328658981154199bff7aef0fd0adf8e)[6](https://apiview.dev/Assemblies/Review/c8986bdf9191490b875c0a925246193d?diffRevisionId=ec4d9dfda8184e3a9f519e5dc459d73b&doc=False&diffOnly=False#597b07320dfa4735adb7b4d7ac8941bd)[7](https://apiview.dev/Assemblies/Review/c8986bdf9191490b875c0a925246193d?diffRevisionId=ec4d9dfda8184e3a9f519e5dc459d73b&doc=False&diffOnly=False#597b07320dfa4735adb7b4d7ac8941bd)</sup>
    - Rename `expiryTime` to `expiresIn`.<sup>[8](https://apiview.dev/Assemblies/Review/c8986bdf9191490b875c0a925246193d?diffRevisionId=ec4d9dfda8184e3a9f519e5dc459d73b&doc=False&diffOnly=False#a08c547b756d4cf29204db6e852eea78)</sup>
    - Add the `immutable` property, as it will be included the next service version to be released.
- Rename `target` to `targetAttestationToken` in `releaseKey` APIs.<sup>[9](https://github.com/Azure/azure-sdk-for-net/issues/24876)</sup>
- Remove `KeyExportRequestParameters` as the `/export` operation will be pushed to a future service version.
- Rename `KeyRotationLifetimeAction`'s `type` to `action`, to align with existing similar APIs in Key Vault Certificates.<sup>[10](https://apiview.dev/Assemblies/Review/d2d05cf175c7478184662d580a300e68?diffRevisionId=e229c861eb9940de96b6adc1d5a8e5b1&doc=False&diffOnly=False#821277d446d24f7192a329e5f9b99c34)</sup>
