### ISSUE TITLE
Transition to New Codesnippet Tooling

### ISSUE THREAD

**Issue by alzimmermsft** [Azure/azure-sdk-for-java#24958]
Recently, [new codesnippet tooling was introduced](https://github.com/Azure/azure-sdk-for-java/pull/24475) for the Azure SDKs. The new tooling works for all LTS Java versions, whereas the previous tooling only worked with Java 8 and 11, and supports handling README codesnippets, which there is another tool handling this. This issue is meant to track transitioning all SDKs to using the new codesnippet tooling for both Javadocs and README codesnippets, and once this issue is closed references to the old tooling will be removed.

The following SDKs need to be update:

- [x] #24959
- [x] #24960
- [x] #24961
- [x] #24962
- [x] #24963
- [x] #24964
- [x] #24965
- [x] #24966
- [x] #24967
- [x] #24968
- [x] #24969
- [x] #24970
- [x] #24971
- [x] #24972
- [x] #24973
- [x] #24974
- [x] #24975
- [x] #24976
- [x] #24977
- [x] #24978
- [x] #24979
- [x] #24980
- [x] #24981
- [x] #24982
- [x] #24983
- [x] #24984
- [x] #24985
- [x] #24986
- [x] #24987

For reference, this [PR transitioned azure-search-documents](https://github.com/Azure/azure-sdk-for-java/pull/24527) to the new tooling and this [PR transitioned azure-data-appconfiguration](https://github.com/Azure/azure-sdk-for-java/pull/24841).

Additionally, as resolving this issue each SDK must pass Javadoc generation using Java 17, the latest LTS version. The reason for this is there is additional Javadoc linting that Java 17 does and this will help unblock including/using Java 17 in our CI pipelines.

_PR Checklist_

This is a checklist to verify you can check off an SDK listed above.

- [x] No usage of `@codesnippet` in Javadocs
- [ ] No usage of embedme for README codesnippets
- [ ] Build passes when using Java 17

**Comment by samvaity** [comment]
@alzimmermsft  Do we want to add a separate tracking issue for resource manager SDK's?

**Comment by alzimmermsft** [comment]
> @alzimmermsft Do we want to add a separate tracking issue for resource manager SDK's?

Management SDKs don't use codesnippet tooling at this time.

**Comment by alzimmermsft** [comment]
Closing as transitioning to the new codesnippet tooling has been completed
