### ISSUE TITLE
[BUG] many azure-storage-blob central maven repository versions are no longer available

### ISSUE THREAD

**Issue by l3pp4rd** [Azure/azure-sdk-for-java#24998]
**Describe the bug**
Can no longer download `azure-storage-blob` at version [12.4.0](https://mvnrepository.com/artifact/com.azure/azure-storage-blob/12.4.0) or `12.5.0` probably many more.
This breaks all the fresh builds if this dependency was not cached.

**To Reproduce**
Just try to view the jar files in the [central repository](https://mvnrepository.com/artifact/com.azure/azure-storage-blob/12.4.0)
Hit `View All` next to files, responds with 404 error.

**Screenshots**
![2021-10-22-114756](https://user-images.githubusercontent.com/132389/138425204-0215c7a8-2ecc-457d-9f7c-2315b5653f28.png)
![2021-10-22-114819](https://user-images.githubusercontent.com/132389/138425215-1de128d9-2d6f-490e-b959-4adb4243552e.png)

**Comment by amishra-dev** [comment]
Hi @l3pp4rd / Gediminas

<html>
<body>
<p style="box-sizing: border-box; margin-top: 0px; margin-bottom: 16px; color: rgb(36, 41, 47); font-family: -apple-system, BlinkMacSystemFont, &quot;Segoe UI&quot;, Helvetica, Arial, sans-serif, &quot;Apple Color Emoji&quot;, &quot;Segoe UI Emoji&quot;; font-size: 14px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">We discovered an issue in older versions listed below of the SDKs for Storage which we have removed from Maven. To upgrade to the latest version please change the dependency version in your pom.xml to a newer one listed below. We strongly recommend moving to the latest SDK if you are using any of these affected versions.</p><p style="box-sizing: border-box; margin-top: 0px; margin-bottom: 16px; color: rgb(36, 41, 47); font-family: -apple-system, BlinkMacSystemFont, &quot;Segoe UI&quot;, Helvetica, Arial, sans-serif, &quot;Apple Color Emoji&quot;, &quot;Segoe UI Emoji&quot;; font-size: 14px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">If you need to use an older Azure Storage REST API version, please read the sample<span> </span><a href="https://github.com/Azure/azure-sdk-for-java/blob/main/sdk/storage/azure-storage-blob/src/samples/java/com/azure/storage/blob/ServiceVersionExample.java" style="box-sizing: border-box; background-color: transparent; color: var(--color-accent-fg); text-decoration: none;">here</a><span> </span>about using an older Service Version with a newer SDK. We apologize for the inconvenience this may have caused.</p>

SDK | Versions Removed | Recommended Version
-- | -- | --
Azure Storage Blob | 12.0 to 12.6.1 | 12.14.1
Azure Storage File Datalake | 12.0 to 12.1.2 | 12.7.1
Azure Storage File Share | 12.0 to 12.4.1 | 12.11.1


</body>
</html>

**Comment by amishra-dev** [comment]
If you need further help
please create a ticket at aka.ms/azsupt.

Issue Type: Technical
Service Type: Blob Storage
Summary: #JavaSDKv12
Problem type: Development
Problem subtype: Client library or SDK
