### ISSUE TITLE
[BUG] Reading items from Cosmos container with nested partition key returns nothing

### ISSUE THREAD

**Issue by jshaptic** [Azure/azure-sdk-for-java#25000]
**Describe the bug**
Reading items from Cosmos container, which is configured with nested partition key doesn't work. It just returns empty result.

***Exception or Stack Trace***
No exception and no stack trace

**To Reproduce**
1. Create container with nested partition key, e.g. /test/key
2. Create few items
3. Try to read these items using either readItem or readMany
4. If will return empty result

***Code Snippet***
```
CosmosClient cosmosClient = new CosmosClientBuilder().endpoint(endpoint).key(key).consistencyLevel(ConsistencyLevel.EVENTUAL).directMode().buildClient();
CosmosDatabase db = cosmosClient.getDatabase("test");
CosmosContainer container = db.getContainer("test");
CosmosItemIdentity identity = new CosmosItemIdentity(new PartitionKey("pk1"), "id1");
FeedResponse<T> response = container.readMany(Arrays.asList(identity), Object.class);
System.out.println(response.getResults().size());
```

**Expected behavior**
It should return items according to the specified id and partition key.

**Screenshots**
Not applicable

**Setup (please complete the following information):**
 - OS: Linux
 - IDE: VSCode
 - Library/Libraries: com.azure:azure-cosmos:4.19.0
 - Java version: 8
 - App Server/Environment: Azure Function
 - Frameworks: no
  
**Additional context**
No additional context

**Information Checklist**
Kindly make sure that you have added all the following information above and checkoff the required fields otherwise we will treat the issuer as an incomplete report
- [x] Bug Description Added
- [x] Repro Steps Added
- [x] Setup information Added

**Comment by kushagraThapar** [comment]
This is done. @jshaptic pls test on the latest version.
