### ISSUE TITLE
[FEATURE REQ] Ability to create/update public/private access for Container Registry

### ISSUE THREAD

**Issue by fredericdesroches** [Azure/azure-sdk-for-java#25037]
**Is your feature request related to a problem? Please describe.**
We are trying to automate private container registries using the azure-sdk-for-java by following this how-to : https://docs.microsoft.com/en-us/azure/container-registry/container-registry-private-link. The last step says to disable public access using `az acr update --name $REGISTRY_NAME --public-network-enabled false`. However, this property is not creatable/updatable in the latest artifact `com.azure.resourcemanager:azure-resourcemanager-containerregistry:2.9.0`.

**Describe the solution you'd like**
Something simple such as :
```
final Registry registry = containerRegistryManager.containerRegistries()
    .getByResourceGroup("my-resource-group", "my-registry");

registry.update()
    .withPublicNetworkAccess(false)
    .apply();
```

**Describe alternatives you've considered**
Replicating the request as a simple HTTP request has been considered and is quite complex with all the headers. We discussed it was best if it came from the SDK.

**Additional context**
N/A

**Information Checklist**
Kindly make sure that you have added all the following information above and checkoff the required fields otherwise we will treat the issuer as an incomplete report
- [x] Description Added
- [x] Expected solution specified

Thanks

**Comment by weidongxu-microsoft** [comment]
@fredericdesroches 

The "storageAccount" property is removed from all later preview api-versions. If we switched to later version, that functionality will be gone.
Let me know if you are using it or not.
https://github.com/Azure/azure-rest-api-specs/blob/main/specification/containerregistry/resource-manager/Microsoft.ContainerRegistry/stable/2019-05-01/containerregistry.json#L1417-L1420

**Comment by weidongxu-microsoft** [comment]
WIP PR https://github.com/Azure/azure-sdk-for-java/pull/25119

**Comment by fredericdesroches** [comment]
Hi @weidongxu-microsoft, the property we are after is `publicNetworkAccess` and not `storageAccount`. Reference in newer API version here https://github.com/Azure/azure-rest-api-specs/blob/main/specification/containerregistry/resource-manager/Microsoft.ContainerRegistry/preview/2019-12-01-preview/containerregistry.json#L2872

**Comment by weidongxu-microsoft** [comment]
@fredericdesroches 

Got it. My concern was the removing of the `storageAccount` would break you.
Even if it does not break you, it still have potential of breaking other customer that is using it. So I need to treat this more careful.

**Comment by fredericdesroches** [comment]
Ah sorry misunderstood. I can confirm we do not use `storageAccount`.

**Comment by weidongxu-microsoft** [comment]
Next release will be 2.10.0, on 2nd or 3rd week of Nov.

**Comment by fredericdesroches** [comment]
Thanks a lot @weidongxu-microsoft for the fast response time! Is there a way we could possibly test this by using some sort of beta/preview version?

**Comment by weidongxu-microsoft** [comment]
@fredericdesroches

You should be able to get it from our daily alpha builds.

add repository
```
<repository>
  <id>azure-sdk-for-java</id>
  <url>https://pkgs.dev.azure.com/azure-sdk/public/_packaging/azure-sdk-for-java/maven/v1</url>
  <releases>
    <enabled>true</enabled>
  </releases>
  <snapshots>
    <enabled>true</enabled>
  </snapshots>
</repository>
```

use `2.10.0-alpha.20211108.1` version
```
<dependency>
  <groupId>com.azure.resourcemanager</groupId>
  <artifactId>azure-resourcemanager</artifactId>
  <version>2.10.0-alpha.20211108.1</version>
</dependency>
```
