### ISSUE TITLE
Storage - Queues Readme Issue

### ISSUE THREAD

**Issue by hongli750210** [Azure/azure-sdk-for-java#25030]
1.
Section [Link](https://github.com/Azure/azure-sdk-for-java/tree/main/sdk/storage/azure-storage-queue#examples)
![image](https://user-images.githubusercontent.com/74638143/138800109-8c2ab6f5-af62-4843-8e87-4dd5cc555216.png)

Suggestion:
Text change to `(#delete-message-from-a-queue)`

@scottaddie, @joshfree, @tg-msft, @kyle-patterson and @alzimmermsft for notification

**Comment by scottaddie** [comment]
This was fixed in https://github.com/Azure/azure-sdk-for-java/pull/25346.
