### ISSUE TITLE
[FEATURE REQ] Test Spring Cloud Azure 4.0 with storage emulator and cosmos emulator

### ISSUE THREAD

**Issue by saragluna** [Azure/azure-sdk-for-java#25058]
**Is your feature request related to a problem? Please describe.**
Spring Cloud Azure 4.0 should work with both real Azure backend services as well as service-provided emulators, such as the Storage emulator and the Cosmos emulator. 

**Describe the solution you'd like**
Test current 4.0 implementation to see whether it could work with the aforementioned emulators. 

**Describe alternatives you've considered**
NA. 

**Additional context**
NA.

**Information Checklist**
Kindly make sure that you have added all the following information above and checkoff the required fields otherwise we will treat the issuer as an incomplete report
- [x] Description Added
- [x] Expected solution specified

Emulator
- [Azure Cosmos DB Emulator](https://docs.microsoft.com/en-us/azure/cosmos-db/local-emulator?tabs=ssl-netstd21)

**Comment by backwind1233** [comment]
✅Cosmos Emulator pass.

**Comment by backwind1233** [comment]
linked: https://github.com/Azure/azure-sdk-for-java/pull/25237
close this issue, because Cosmos Emulator and Storage Emulator tests passed

**Comment by stliu** [comment]
@backwind1233 could you provide how to use Storage and Cosmos Emulator with Spring Cloud Azure locally?

**Comment by backwind1233** [comment]
> @backwind1233 Zhihao Guo FTE could you provide how to use Storage and Cosmos Emulator with Spring Cloud Azure locally?
> 
> for example, how to use this https://github.com/Azure/Azurite to run https://github.com/Azure-Samples/azure-spring-boot-samples/tree/spring-cloud-azure_v4.2.0/storage/spring-cloud-azure-starter-storage-blob/storage-blob-sample?

@stliu sure, I will provide a wiki to show how to test locally.

**Comment by backwind1233** [comment]
@stliu This is the [wiki](https://github.com/Azure/azure-sdk-for-java/wiki/Run-Spring-Cloud-Azure-Cosmos-And-Storage-Samples-with-Azure-Emulators) describing how to use Cosmos and Storage emulators to run [spring-cloud-azure-data-cosmos-sample](https://github.com/Azure-Samples/azure-spring-boot-samples/tree/main/cosmos/spring-cloud-azure-starter-data-cosmos/spring-cloud-azure-data-cosmos-sample) and [storage-blob-sample](https://github.com/Azure-Samples/azure-spring-boot-samples/tree/main/storage/spring-cloud-azure-starter-storage-blob/storage-blob-sample).

**Comment by backwind1233** [comment]
Closing this issue, use https://github.com/Azure/azure-sdk-for-java/issues/29718 instead.
