### ISSUE TITLE
[FEATURE REQ] Add more items in pom.xml for spring related modules.

### ISSUE THREAD

**Issue by chenrujun** [Azure/azure-sdk-for-java#25054]
Example: https://repo1.maven.org/maven2/org/springframework/security/spring-security-core/5.5.3/spring-security-core-5.5.3.pom

We can add these items:
![image](https://user-images.githubusercontent.com/13167207/138977756-966a9f85-2431-4f20-b629-8fa7d72d0e11.png)

And some of these items can be displayed here: https://mvnrepository.com/artifact/org.springframework.security/spring-security-core/5.5.3

![image](https://user-images.githubusercontent.com/13167207/138977837-f40e940b-fd97-490d-abf0-0ccf14eda975.png)

Just add this for 4.0 version, ignore current 3.x version

**Comment by hui1110** [comment]
The corresponding pr has been merged.
