### ISSUE TITLE
 migrated from SDK 3 to SDK4 recently. Seeing 555 http status codes from cosmos database 30 minutes after the migration

### ISSUE THREAD

**Issue by srinathji** [Azure/azure-sdk-for-java#25064]
**Describe the bug**
After migrating Cosmos JAVA SDK 3 to 4 Seeing 555 HTTP status code from cosmos DB after 30 min,

***Exception or Stack Trace***
Add the exception log and stack trace if available:
**Namespace': prod,
'Pod': ratings-service-57b66849b6-vmb7k,
'Container': ratings-service,
'TraceId': 35c733b8ea03d1164fdd921e9bb00cee,
'ParentId': 5cad2532a2f2d398,
'Host': https://docdb-selection-prod.documents.azure.com:443,**
'Path': https://docdb-selection-prod.documents.azure.com:443/rating_summaries/getRatingSummaryByEntityIdAndDimension,
'QueryParams': {
'q': 'SELECT * FROM rating_summaries c\\nWHERE c.entityId = @entityId\\nAND c.dimension = @dimension\\nOFFSET 0 LIMIT 1'
},
'Method': get,
'StatusCode': 555,
'Duration': 0.045250497,
'ClientIp': ,
'UserAgent': CosmosDBDaoV4,
'Properties': {
'telemetry_type': 'COSMOS',
'req_container': 'ratings-service',
'req_pod': 'ratings-service-57b66849b6-vmb7k',
'simulated': 'true',
'cosmosDiagnostics_0': 'userAgent=azsdk-java-cosmos/4.18.0 Linux/5.4.0-1055-azure JRE/1.8.0_265\\nQueryPlan Start Time (UTC)=08:35:50:2370\\nQueryPlan End Time (UTC)=08:35:50:2600\\nQueryPlan Duration (ms)=23\\nQueryPlan RequestTimeline =[{\\'eventName\\':\\'connectionAcquired\\',\\'startTimeUTC\\':\\'2021-10-06T08:35:50.237Z\\',\\'durationInMicroSec\\':0},{\\'eventName\\':\\'connectionConfigured\\',\\'startTimeUTC\\':\\'2021-10-06T08:35:50.237Z\\',\\'durationInMicroSec\\':0},{\\'eventName\\':\\'requestSent\\',\\'startTimeUTC\\':\\'2021-10-06T08:35:50.237Z\\',\\'durationInMicroSec\\':0},{\\'eventName\\':\\'transitTime\\',\\'startTimeUTC\\':\\'2021-10-06T08:35:50.237Z\\',\\'durationInMicroSec\\':23000},{\\'eventName\\':\\'received\\',\\'startTimeUTC\\':\\'2021-10-06T08:35:50.260Z\\',\\'durationInMicroSec\\':0}]\\n\\n{\\'min\\':\\'05C1DFFFFFFFF8\\',\\'max\\':\\'05C1E7FFFFFFFA\\'},pkrId:2=Retrieved Document Count                 :               1              \\nRetrieved Document Size                  :             715 bytes        \\nOutput Document Count                    :               1              \\nOutput Document Size                     :             764 bytes        \\nIndex Utilization                        :          100.00 %            \\nTotal Query Execution Time               :        0.500000 milliseconds \\nQuery Preparation Times \\n    Query Compilation Time               :        0.140000 milliseconds \\n    Logical Plan Build Time              :        0.040000 milliseconds \\n    Physical Plan Build Time             :        0.080000 milliseconds \\n    Query Optimization Time              :        0.000000 milliseconds \\n  Index Lookup Time                      :        0.050000 milliseconds \\n  Document Load Time                     :        0.020000 milliseconds \\nRuntime Execution Times \\n    Query Engine Times                   :        0.020000 milliseconds \\n    System Function Execution Time       :        0.000000 milliseconds \\n    User-defined Function Execution Time :        0.000000 milliseconds \\n  Document Write Time                    :        0.000000 milliseconds \\nClient Side Metrics \\n  Retry Count                            :               0              \\n  Request Charge                         :            2.83 RUs          \\n \\nPartition Execution Timeline \\n┌───────────────────┬────────────────────────────────────┬────────────────┬────────────────┬─────────────┬───────────────────┬───────────┐ \\n│Partition Key Range│                         Activity Id│Start Time (UTC)│  End Time (UTC)│Duration (ms)│NUMBER of Documents│Retry Count│ \\n├───────────────────┼────────────────────────────────────┼────────────────┼────────────────┼─────────────┼───────────────────┼───────────┤ \\n│{\\'min\\':\\'05C1DFFFFFFFF8\\',\\'max\\':\\'05C1E7FFFFFFFA\\'}│6919a400-2680-11ec-a30b-c1ccaf358920│   08:35:50:2600│   08:35:50:2820│         22.0│                  1│          0│ \\n└───────────────────┴────────────────────────────────────┴────────────────┴────────────────┴─────────────┴───────────────────┴───────────┘ \\n \\nScheduling Metrics \\n┌───────────────┬──────────────────┬─────────────┬──────────────┬────────────────────┬─────────────────────┐ \\n│Partition Range│Response Time (ms)│Run Time (ms)│Wait Time (ms)│Turnaround Time (ms)│NUMBER of Preemptions│ \\n├───────────────┼──────────────────┼─────────────┼──────────────┼────────────────────┼─────────────────────┤ \\n│{\\'min\\':\\'05C1DFFFFFFFF8\\',\\'max\\':\\'05C1E7FFFFFFFA\\'}│                 0│           22│             0│                  22│                    1│ \\n└───────────────┴──────────────────┴─────────────┴──────────────┴────────────────────┴─────────────────────┘ \\n\\n[{\\'userAgent\\':\\'azsdk-java-cosmos/4.18.0 Linux/5.4.0-1055-azure JRE/1.8.0_265\\',\\'requestLatencyInMs\\':22,\\'requestStartTimeUTC\\':\\'2021-10-06T08:35:50.260Z\\',\\'requestEndTimeUTC\\':\\'2021-10-06T08:35:50.282Z\\',\\'responseStatisticsList\\':[{\\'storeResult\\':{\\'storePhysicalAddress\\':\\'rntbd://cdb-ms-prod-centralindia1-fd4.documents.azure.com:14083/apps/3403a43b-c8fd-4e85-bdd0-f5e80a31b105/services/734abd59-e012-4de2-8307-2de09c811983/partitions/3f01ed9d-b624-433e-aaef-b81d302deb0d/replicas/132657039116989151s/\\',\\'lsn\\':2689529,\\'globalCommittedLsn\\':2689528,\\'partitionKeyRangeId\\':\\'2\\',\\'isValid\\':true,\\'statusCode\\':200,\\'subStatusCode\\':0,\\'isGone\\':false,\\'isNotFound\\':false,\\'isInvalidPartition\\':false,\\'isThroughputControlRequestRateTooLarge\\':false,\\'requestCharge\\':2.83,\\'itemLSN\\':-1,\\'sessionToken\\':\\'-1#2689529\\',\\'backendLatencyInMs\\':0.855,\\'exception\\':null,\\'transportRequestTimeline\\':[{\\'eventName\\':\\'created\\',\\'startTimeUTC\\':\\'2021-10-06T08:35:50.260Z\\',\\'durationInMicroSec\\':0},{\\'eventName\\':\\'queued\\',\\'startTimeUTC\\':\\'2021-10-06T08:35:50.260Z\\',\\'durationInMicroSec\\':0},{\\'eventName\\':\\'channelAcquisitionStarted\\',\\'startTimeUTC\\':\\'2021-10-06T08:35:50.260Z\\',\\'durationInMicroSec\\':0},{\\'eventName\\':\\'pipelined\\',\\'startTimeUTC\\':\\'2021-10-06T08:35:50.260Z\\',\\'durationInMicroSec\\':0},{\\'eventName\\':\\'transitTime\\',\\'startTimeUTC\\':\\'2021-10-06T08:35:50.260Z\\',\\'durationInMicroSec\\':22000},{\\'eventName\\':\\'received\\',\\'startTimeUTC\\':\\'2021-10-06T08:35:50.282Z\\',\\'durationInMicroSec\\':0},{\\'eventName\\':\\'completed\\',\\'startTimeUTC\\':\\'2021-10-06T08:35:50.282Z\\',\\'durationInMicroSec\\':0}],\\'rntbdRequestLengthInBytes\\':710,\\'rntbdResponseLengthInBytes\\':1689,\\'requestPayloadLengthInBytes\\':277,\\'responsePayloadLengthInBytes\\':764,\\'channelTaskQueueSize\\':1,\\'pendingRequestsCount\\':0,\\'serviceEndpointStatistics\\':{\\'availableChannels\\':5,\\'acquiredChannels\\':0,\\'executorTaskQueueSize\\':0,\\'inflightRequests\\':1,\\'lastSuccessfulRequestTime\\':\\'2021-10-06T08:35:39.389Z\\',\\'lastRequestTime\\':\\'2021-10-06T08:35:39.367Z\\',\\'createdTime\\':\\'2021-10-06T07:03:33.068Z\\',\\'isClosed\\':false}},\\'requestResponseTimeUTC\\':\\'2021-10-06T08:35:50.282Z\\',\\'requestResourceType\\':\\'Document\\',\\'requestOperationType\\':\\'Query\\'}],\\'supplementalResponseStatisticsList\\':[],\\'addressResolutionStatistics\\':{},\\'regionsContacted\\':[\\'https://docdb-selection-prod-centralindia.documents.azure.com:443/\\'],\\'retryContext\\':{\\'statusAndSubStatusCodes\\':null,\\'retryLatency\\':0,\\'retryCount\\':0},\\'metadataDiagnosticsContext\\':{\\'metadataDiagnosticList\\':null},\\'serializationDiagnosticsContext\\':{\\'serializationDiagnosticsList\\':null},\\'gatewayStatistics\\':null,\\'systemInformation\\':{\\'usedMemory\\':\\'1525485 KB\\',\\'availableMemory\\':\\'1569043 KB\\',\\'systemCpuLoad\\':\\'(2021-10-06T08:35:21.316Z 5.6%), (2021-10-06T08:35:26.316Z 5.0%), (2021-10-06T08:35:31.316Z 6.4%), (2021-10-06T08:35:36.316Z 4.9%), (2021-10-06T08:35:41.316Z 6.5%), (2021-10-06T08:35:46.316Z 4.8%)\\',\\'availableProcessors\\':2},\\'clientCfgs\\':{\\'id\\':-1,\\'connectionMode\\':\\'DIRECT\\',\\'numberOfClients\\':4,\\'connCfg\\':{\\'rntbd\\':\\'(cto:PT5S, rto:PT5S, icto:PT0S, ieto:PT1H, mcpe:130, mrpc:30, cer:false)\\',\\'gw\\':\\'(cps:1000, rto:PT5S, icto:PT1M, p:false)\\',\\'other\\':\\'(ed: true, cs: false)\\'},\\'consistencyCfg\\':\\'(consistency: Session, mm: true, prgns: [])\\'}}]',

**To Reproduce**
Migrate JAVA SDK 3 to 4

***Code Snippet***
Add the code snippet that causes the issue.
 'Namespace': prod,
'Pod': ratings-service-57b66849b6-vmb7k,
'Container': ratings-service,
'TraceId': 35c733b8ea03d1164fdd921e9bb00cee,
'ParentId': 5cad2532a2f2d398,
'Host': https://docdb-selection-prod.documents.azure.com:443,
'Path': https://docdb-selection-prod.documents.azure.com:443/rating_summaries/getRatingSummaryByEntityIdAndDimension,
'QueryParams': {
'q': 'SELECT * FROM rating_summaries c\\nWHERE c.entityId = @entityId\\nAND c.dimension = @dimension\\nOFFSET 0 LIMIT 1'
},
'Method': get,
**Expected behavior**
At the backend, the query is running without any issues but there is 555 HTTP status code error

**Screenshots**

**Setup (please complete the following information):**
 - OS:  VM self-hosted Kubernetes
 - IDE: [e.g. IntelliJ] NA
 - Library/Libraries: azsdk-java-cosmos/4.18.0 Linux/5.4.0-1055-azure JRE/1.8.0_265
 - Java version: 1.8.0_265
 - App Server/Environment: VM self-hosted Kubernetes
 - Frameworks: 

If you suspect a dependency version mismatch (e.g. you see `NoClassDefFoundError`, `NoSuchMethodError` or similar), please provide
- verbose dependency tree (`mvn dependency:tree -Dverbose`)
  
**Additional context**

**Information Checklist**
Kindly make sure that you have added all the following information above and checkoff the required fields otherwise we will treat the issuer as an incomplete report
- [ ] Bug Description Added
- [ ] Repro Steps Added
- [ ] Setup information Added

**Comment by kushagraThapar** [comment]
@srinathji  - I recall you created a support case for this issue, is it still open or can we close it ?
Please update it accordingly.
