### ISSUE TITLE
[BUG] Invalid bean definition with name 'jobBanParams' defined in null: property should contain text.; nested exception is java.lang.IllegalArgumentException: property should contain text

### ISSUE THREAD

**Issue by ga896b** [Azure/azure-sdk-for-java#25089]
**Describe the bug**
When we are trying to Implement Azure key vault have deployment issue for one of the micro service, the issue when we are trying to use key vault dependencies it is looking for some property values in xml config file and they are dynamic params which come from rest controller.  is it possible azure dependencies not look dynamic params. 

***Exception or Stack Trace***

{"logType":"DEBUG","logLevel":"ERROR","logTimestamp":"2021-10-28T08:47:26.752-04:00","logger":"org.springframework.boot.SpringApplication","label":"Application run failed","runtime":{"hostName":"N/A","ip":"N/A","instance":"N/A","clusterName":"N/A","namespace":"unknown","image":"unknown"},"application":{"deploymentUnitName":"unknown","motsApplicationAcronym":"unknown"},"exception":{"exceptionDetails":"Invalid bean definition with name **'jobBanParams'** defined in null: property should contain text.; nested exception is **java.lang.IllegalArgumentException: property should contain text**.","stackTrace":"org.springframework.beans.factory.BeanDefinitionStoreException: Invalid bean definition with name 'jobBanParams' defined in null: property should contain text.; nested exception is java.lang.IllegalArgumentException: property should contain text.\r\n\tat org.springframework.beans.factory.config.PlaceholderConfigurerSupport.doProcessProperties(PlaceholderConfigurerSupport.java:228)\r\n\tat org.springframework.context.support.PropertySourcesPlaceholderConfigurer.processProperties(PropertySourcesPlaceholderConfigurer.java:182)\r\n\tat org.springframework.context.support.PropertySourcesPlaceholderConfigurer.postProcessBeanFactory(PropertySourcesPlaceholderConfigurer.java:157)\r\n\tat org.springframework.context.support.PostProcessorRegistrationDelegate.invokeBeanFactoryPostProcessors(PostProcessorRegistrationDelegate.java:286)\r\n\tat org.springframework.context.support.PostProcessorRegistrationDelegate.invokeBeanFactoryPostProcessors(PostProcessorRegistrationDelegate.java:166)\r\n\tat org.springframework.context.support.AbstractApplicationContext.invokeBeanFactoryPostProcessors(AbstractApplicationContext.java:706)\r\n\tat org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:532)\r\n\tat org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.refresh(ServletWebServerApplicationContext.java:141)\r\n\tat org.springframework.boot.SpringApplication.refresh(SpringApplication.java:747)\r\n\tat org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:397)\r\n\tat org.springframework.boot.SpringApplication.run(SpringApplication.java:315)\r\n\tat org.springframework.boot.SpringApplication.run(SpringApplication.java:1226)\r\n\tat org.springframework.boot.SpringApplication.run(SpringApplication.java:1215)\r\n\tat com.att.api.framework.ajsc.Application.main(Application.java:42)\r\nCaused by: java.lang.IllegalArgumentException: property should contain text.\r\n\tat org.springframework.util.Assert.hasText(Assert.java:284)\r\n\tat com.microsoft.azure.keyvault.spring.KeyVaultOperation.get(KeyVaultOperation.java:91)\r\n\tat **com.microsoft.azure.keyvault.spring.KeyVaultPropertySource.getProperty(KeyVaultPropertySource.java:27)\r\n\tat** org.springframework.core.env.PropertySourcesPropertyResolver.getProperty(PropertySourcesPropertyResolver.java:85)\r\n\tat

***Code Snippet***
**[serviceBeanxml.txt](https://github.com/Azure/azure-sdk-for-java/files/7435230/serviceBeanxml.txt)
attached  serviceBean.xml**

### **Rest Endpoint:**
http://localhost:8080/rest/getUSOCData/113453309(**job**)/125841447 (**ban**)

### **_Route:_**
Added rote config file 
[route.configfile.txt](https://github.com/Azure/azure-sdk-for-java/files/7435744/route.configfile.txt)

**Entity Class:**

@Entity
@Table(name="USOC_DETAILS")
@NamedQueries({
@NamedQuery(name="NrcUsocDetails.select", query="select o from com.att.capseed.entity.NrcUsocDetails o where o.key.jobId=:job and o.key.ban=:ban")
})
public class NrcUsocDetails {
}

Azure library class are looking for every parameter  

**### Class :** 
com.microsoft.azure.keyvault.spring.KeyVaultOperation

### **Method :**
public String get(final String property) {
Assert.hasText(property, "property should contain text.");
final String secretName = getKeyvaultSecretName(property); //if user don't set specific secret keys, then refresh token
if (this.secretKeys == null || secretKeys.size() == 0) {
// refresh periodically
refreshPropertyNames();
}
if (this.propertyNames.contains(secretName)) {
final KeyVaultSecret secret = this.keyVaultClient.getSecret(secretName);
return secret == null ? null : secret.getValue();
} else {
return null;
}
}

### **Class :** 
com.microsoft.azure.keyvault.spring.KeyVaultEnvironmentPostProcessorHelper

### **Method:**
private String getProperty(final ConfigurableEnvironment env, final String propertyName) {
Assert.notNull(env, "env must not be null!");
Assert.notNull(propertyName, "propertyName must not be null!");
final String property = env.getProperty(propertyName);
if (property == null || property.isEmpty()) {
throw new IllegalArgumentException("property " + propertyName + " must not be null");
}
return property;
}

**Expected behavior**
we should deploy app without any error

**Setup (please complete the following information):**
 - OS: windows
 - IDE: STS 
 - Library/Libraries:
 <dependency>
			<groupId>com.microsoft.azure</groupId>
			<artifactId>azure-keyvault-secrets-spring-boot-starter</artifactId>
			<version>2.3.2</version>
			<exclusions>
			</exclusions>
	 </dependency>
		<dependency>
			<groupId>com.microsoft.azure</groupId>
			<artifactId>azure-spring-boot-bom</artifactId>
			<version>2.3.2</version>
			<type>pom</type>
			<scope>import</scope>
			<exclusions>
				<exclusion>
					<artifactId>log4j-to-slf4j</artifactId>
					<groupId>org.apache.logging.log4j</groupId>
				</exclusion>
			</exclusions>
		</dependency> 
 - Java version: 1.8 
 - App Server/Environment: embedded tomcat, Linux server
 - Frameworks: Spring Boot, Microservices, apache camel routes, JPA

**Comment by ga896b** [comment]
@chenrujun We are dynamically loading from rest controller that is the reason we are using like ${:$}{header.job} and these are not loading from environment variables. 

we are also using placeholders like ${jdbc.url} to read from environment variables 

We can't update or upgrade versions because of version mismatch causing compatibility issues spring boot version is 2.2.3

http://localhost:8080/rest/getUSOCData/113453309/125841447
Job: 113453309
Ban:125841447

**Comment by chenrujun** [comment]
@ga896b 

No I understand that `job` and `ban` will get value from [path variable].
But I still can not understand what does `${:$}{header.job}` mean.



[path variable]: https://docs.spring.io/spring-framework/docs/current/reference/html/web.html#mvc-ann-requestmapping-uri-templates

**Comment by chenrujun** [comment]
Closing this issue, because no response from customer for a long time.
