### ISSUE TITLE
[FEATURE REQ] Filter for labels in Feature Flags 

### ISSUE THREAD

**Issue by michaelegner** [Azure/azure-sdk-for-java#25086]
**Is your feature request related to a problem? Please describe.**
The feature management library azure-spring-cloud-feature-management-web (see maven dependency below) currently does not support to filter feature flags for labels. 

        <dependency>
            <groupId>com.azure.spring</groupId>
            <artifactId>azure-spring-cloud-feature-management-web</artifactId>
            <version>2.0.1</version>
        </dependency>

We have a front end application that supports different channels and the feature flags for this application are defined channel wise. We do this by having the channel name as part of the feature flag name. To decide, if a feature is active in a channel we have to filter the feature flags if the feature flag name contains the channel name. 

Current example for Feature Manager in Azure Portal:
Name                             |        Label
channel-x.feature-one   |        (No label)
channel-y.feature-one   |        (No label)
channel-z.feature-one   |        (No label)
channel-x.feature-two   |        (No label)
channel-y.feature-two   |        (No label)
channel-z.feature-two   |        (No label)
...

**Describe the solution you'd like**
It would be very helpful for our use case to store the channel name as a label in the configuration setting of the feature flag and extend the azure-spring-cloud-feature-management-web library to filter the feature flags for a label or a list ob labels.

Wanted example for Feature Manager in Azure Portal:
Name               |      Label
feature-one      |      channel-x
feature-one      |      channel-y
feature-one      |      channel-z
feature-two      |      channel-x
feature-two      |      channel-y
feature-two      |      channel-z
...

This way the list of features would be more clear and concise as the features with the same name would by grouped together

**Describe alternatives you've considered**
n.a.

**Additional context**
n.a.

**Comment by mrm9084** [comment]
This is supported in Spring Boot 2 in:
```
<dependency>
    <groupId>com.azure.spring</groupId>
    <artifactId>spring-cloud-azure-appconfiguration-config</artifactId>
    <version>4.7.0</version>
</dependency>
```
and Spring Boot 3 in:
<dependency>
    <groupId>com.azure.spring</groupId>
    <artifactId>spring-cloud-azure-appconfiguration-config</artifactId>
    <version>5.1.0</version>
</dependency>
