### ISSUE TITLE
[BUG] ServiceBusMessageBatch does not preserve message order reliably 

### ISSUE THREAD

**Issue by paulbandler** [Azure/azure-sdk-for-java#25112]
**Describe the bug**
When the ServiceBusMessageBatch class is used to send batches of ServiceBus messages, the order of adding the messages to the ServiceBusMessageBatch object is not reliably the order the messages are added to the destination queue.

***Exception or Stack Trace***
Add the exception log and stack trace if available

**To Reproduce**
It was confirmed by testing and comparing the resulting order of the messages on the queue.  When not using ServiceBusMessageBatch the send order was reliably the message order on the queue, but when using ServiceBusMessageBatch the order was frequently not preserved, leading to erroneous processing by the received.

***Code Snippet***
I have a simple wrapper around the ServiceBus client that enable switching between batched sends and un-batched sends - the actual send method looks like this:
        void sendMessage(ServiceBusMessage serviceBusMessage){
            if(!batchingEnabled) {
                log.trace("Send single service bus messages to {}", getNameQualifier());
                senderClient.sendMessage(serviceBusMessage);
            } else {
                if(!serviceBusMessageBatch.get().tryAddMessage(serviceBusMessage)){
                    flush();
                    if(!serviceBusMessageBatch.get().tryAddMessage(serviceBusMessage)){
                        String msg = String.format("Unable to add SB message to batch - too large - %d?", serviceBusMessage.getBody().toBytes().length);
                        ServiceBusSink.this.senderClient = null;
                        throw new RuntimeException(msg);
                    }
                }
            }
        }

**Expected behavior**
Batches of messages assembled using ServiceBusMessageBatch should be written to the destination queue in the order in which they are added to the ServiceBusMessageBatch object.
**Screenshots**

**Setup (please complete the following information):**
 - OS: Linux in K8S Container
 - IDE: n/a
 - Library/Libraries: com.azure:azure-messaging-servicebus:7.4.2
 - Java version: 11
 - App Server/Environment: AKS Pod
 - Frameworks: Micronaut,

If you suspect a dependency version mismatch (e.g. you see `NoClassDefFoundError`, `NoSuchMethodError` or similar), please provide
- verbose dependency tree (`mvn dependency:tree -Dverbose`)
  
**Additional context**

**Information Checklist**
Kindly make sure that you have added all the following information above and checkoff the required fields otherwise we will treat the issuer as an incomplete report
- [ X] Bug Description Added
- [ X] Repro Steps Added
- [ X] Setup information Added

**Comment by joshfree** [comment]
@ki1729 can you please give an update?

**Comment by ki1729** [comment]
Sure Josh,  the fix for this causes a significant hit in performance, but giveth that this is a fix and not a perf enhancement, will be going ahead with it.  This fix should be done and hopefully be out in the Jan release of the sdk

**Comment by paulbandler** [comment]
Has there been any progress on this issue?
