### ISSUE TITLE
[KeyVault JCA] "java.security.UnrecoverableKeyException: Get Key failed: extra data given to DerValue constructor" on UsGov and China cloud

### ISSUE THREAD

**Issue by hongli750210** [Azure/azure-sdk-for-java#25137]
We are running live tests against other clouds like US Gov and Azure China Cloud. The goal is to check whether new azure sdk package work with other clouds or not.

**Error Description:**
When running the integration test [`JreKeyStoreTest.testJreKsTrustPeer`](https://github.com/Azure/azure-sdk-for-java/blob/main/sdk/keyvault/azure-security-keyvault-jca/src/test/java/com/azure/security/keyvault/jca/JreKeyStoreTest.java#L56) supports tracing on UsGov cloud and China cloud, it returns the error `extra data given to DerValue constructor`. The error message is shown as following, for more details please check [here](https://dev.azure.com/azure-sdk/internal/_build/results?buildId=1168262&view=logs&j=7566af82-6517-58e4-7ec1-81da64035e1a&t=3ee2bcd8-9006-5b77-3316-6e6167528cb6&l=114).
![image](https://user-images.githubusercontent.com/74638143/139655172-c556f55c-fef0-465a-882d-d148dfb88756.png)

Expected Behavior:
The test cases related to `java.security.KeyStore` and `java.security.KeyStore.KeyVaultKeyStore` can pass on UsGov and China cloud. 

@benbp, @scottaddie, @joshfree, @AlexGhiondea and @backwind1233 for notification.

**Comment by hongli750210** [comment]
@joshfree Sorry for the flaws when add contacts, now has been fixed.

**Comment by v-xuto** [comment]
@benbp Do you have any ideas about this issue?

**Comment by chenrujun** [comment]
Sorry for late response. I'll investigate it. And PR is welcome.

**Comment by hongli750210** [comment]
After merging the latest SDK code, the exception recorded in the issue cannot be reproduced.
