### ISSUE TITLE
Missing untracking of subscription in AmqpChannelProcessor and GC pressure on long live lock-token in ServiceBusSessionReceiver

### ISSUE THREAD

**Issue by anuchandy** [Azure/azure-sdk-for-java#25149]
`1. AmqpChannelPrcoessor` maintains a dequeue of "ChannelSubscriber" waiting for a channel to be available. When the the channel is available,  we notify the subscription via the AmqpChannelPrcoessor::onNext method, but after that, we're not untracking the subscription leading to slow memory growth over days. There are other code paths cleaning the subscriber list (on-error, on-complete), which hides the sharp growth.

<img width="1679" alt="Screen Shot 2021-11-02 at 9 35 07 AM" src="https://user-images.githubusercontent.com/1471612/139907395-b23c37f6-5ae9-405b-80fd-61c5a69209d6.png">

`2. ServiceBusSessionReceiver` maintains a list of lock tokens, which we clean at fixed intervals. But when the messages arrive at a high rate, this list grows simultaneously, leading to GC pressure to make space for other parts.

<img width="948" alt="Screen Shot 2021-11-02 at 9 47 36 AM" src="https://user-images.githubusercontent.com/1471612/139909292-dd7691a7-9a86-49fa-8c54-7b7693bf0350.png">

*Recommendation*: Remove the lock from the lock container once the disposition is complete (with error / not); this combined with cleanup at regular intervals, helps reduce the GC pressure. After applying the immediate lock cleanup, the heap appears to be better.

<img width="947" alt="Screen Shot 2021-11-02 at 9 51 23 AM" src="https://user-images.githubusercontent.com/1471612/139909836-848f8f12-a55e-4d6b-988a-09cab9c05f4d.png">

\\cc @conniey

**Comment by joshfree** [comment]
tagging @mikeharder and @g2vinay as fyi (to make sure we get coverage for this scenario after the amqp perf test framework is up)

**Comment by mikeharder** [comment]
@joshfree: Depending on how long this takes to repro, it might need to be covered by stress tests instead of perf.
