### ISSUE TITLE
[BUG] Request with payload of BinaryData from InputStream fails due to invalid content length

### ISSUE THREAD

**Issue by weidongxu-microsoft** [Azure/azure-sdk-for-java#25168]
**Describe the bug**

Request fails due to invalid content length.

code
```java
        ByteArrayInputStream messageStream = new ByteArrayInputStream(message.toBytes());
        client.sendToUserWithResponse("test_user",
            BinaryData.fromStream(messageStream),
            WebPubSubContentType.APPLICATION_OCTET_STREAM, message.getLength(),
            null, Context.NONE);
```

internally it already included the "Content-Length"
```java
        requestOptions.addRequestCallback(httpRequest -> {
            if (httpRequest.getHeaders().stream()
                .noneMatch(header -> header.getName().equalsIgnoreCase("Content-Length"))) {
                httpRequest.setHeader("Content-Length", String.valueOf(contentLength));
            }
        });
```

Possible cause:

`InputStreamContent` return `null` in `getLength`, which is kind of reasonable.
https://github.com/Azure/azure-sdk-for-java/blob/main/sdk/core/azure-core/src/main/java/com/azure/core/implementation/util/InputStreamContent.java#L40-L46

Code provided `Content-Length` header in `RequestOptions`. However due to the order of `validateLength` and `options.getRequestCallback().accept(request)`, the set of `Content-Length` header in `RequestOptions` is after `validateLength`.
https://github.com/Azure/azure-sdk-for-java/blob/main/sdk/core/azure-core/src/main/java/com/azure/core/http/rest/RestProxy.java#L134-L140

***Exception or Stack Trace***
Add the exception log and stack trace if available

stack
```
java.lang.NumberFormatException: null

	at java.base/java.lang.Long.parseLong(Long.java:670)
	at java.base/java.lang.Long.parseLong(Long.java:832)
	at com.azure.core@1.22.0-beta.1/com.azure.core.http.rest.RestProxy.validateLength(RestProxy.java:164)
	at com.azure.core@1.22.0-beta.1/com.azure.core.http.rest.RestProxy.invoke(RestProxy.java:130)
```

**To Reproduce**

***Code Snippet***
Add the code snippet that causes the issue.

**Expected behavior**

**Screenshots**

**Setup (please complete the following information):**
 - IDE: [e.g. IntelliJ]
 - Library/Libraries: [e.g. com.azure:azure-core:1.16.0 (groupId:artifactId:version)] 1.22.0-beta.1 (should be same as the unreleased 1.22.0)
 - Java version: [e.g. 8] 15
 - App Server/Environment: [e.g. Tomcat, WildFly, Azure Function, Apache Spark, Databricks, IDE plugin or anything special]
 - Frameworks: [e.g. Spring Boot, Micronaut, Quarkus, etc] 

If you suspect a dependency version mismatch (e.g. you see `NoClassDefFoundError`, `NoSuchMethodError` or similar), please provide
- verbose dependency tree (`mvn dependency:tree -Dverbose`)
  
**Additional context**

**Information Checklist**
Kindly make sure that you have added all the following information above and checkoff the required fields otherwise we will treat the issuer as an incomplete report
- [x] Bug Description Added
- [x] Repro Steps Added
- [x] Setup information Added

**Comment by weidongxu-microsoft** [comment]
@srnagar @alzimmermsft

**Comment by joshfree** [comment]
@alzimmermsft can you please fix this and do a scrub for other potential unhandled exceptions? 

https://github.com/Azure/azure-sdk-for-java/blob/main/sdk/core/azure-core/src/main/java/com/azure/core/http/rest/RestProxy.java#L186

**Comment by alzimmermsft** [comment]
@weidongxu-microsoft do you think that `RequestOptions` handling should occur before any validation?

**Comment by weidongxu-microsoft** [comment]
@alzimmermsft 
The other "validate" in `RestProxy` is the deprecated `validateResumeOperationIsNotPresent`, so I assume this is not relevent.

So far `validateLength` seems will work fine after the PR.
1. If proxy method does not have `@BodyParam` (happen when body is optional in swagger), and user provide it via `RequestOptions.setBody()`. When `accept` of `RequestOptions` get called, it will set the body and the content length. Then validation happens.
2. If proxy method have `@BodyParam`, and user also provide `RequestOptions.setBody()`, current core seems override the `@BodyParam` by the content of `RequestOptions`. This appears to be reasonable. And then validation happens to the overriden body and content length.

---

There could be a (unrelated) performance issue (only happen to stream data etc.), for the difference of handling of `BinaryData` in `RestProxy` and in `RequestOptions`.
In `RestProxy`, it is lazy load (`binaryData.toFluxByteBuffer()`), but in `RequestOptions`, it is eager load (`request.setBody(requestBody.toBytes())`). I am not exactly sure but it seems will load every bytes for steam data like `FluxByteBufferContent` and `InputStreamContent`.
https://github.com/Azure/azure-sdk-for-java/blob/main/sdk/core/azure-core/src/main/java/com/azure/core/http/rest/RequestOptions.java#L238-L242

Though I guess we might not want to touch this in such a late stage (as it might affect 2nd case of the above discussion, when it cannot set content length to stream data).
