### ISSUE TITLE
 nested exception is java.lang.NoClassDefFoundError: reactor/util/context/ContextView  while trying to update the azure-spring-data-cosmos version:q

### ISSUE THREAD

**Issue by geethukr** [Azure/azure-sdk-for-java#25173]

**Comment by joshfree** [comment]
Hi @geethukr I've marked this issue as `needs-author-feedback` as we need more information from you to be able to assist.

Can you please provide the output of `mvn dependency:tree -Dverbose` as well as the library versions in use per the bug template: https://github.com/Azure/azure-sdk-for-java/blob/main/.github/ISSUE_TEMPLATE/bug_report.md

**Comment by kushagraThapar** [comment]
@geethukr  - this looks like a dependency issue on your end. Please make sure your reactor core and reactor netty versions are aligned with spring data cosmos spring boot version that you are trying to use.
