### ISSUE TITLE
[BUG] azure-messaging-eventhubs 5.10.1 & 5.10.2 throws NPE when PROXY configuration is set

### ISSUE THREAD

**Issue by derSchtefan** [Azure/azure-sdk-for-java#25186]
**Describe the bug**
Using `azure-messaging-eventhubs 5.10.1 or 5.10.2`, when a proxy configuration is set through environment variables:
```
HTTPS_PROXY=http://10.xx.xx.xx:3128
HTTP_PROXY=http://10.xx.xx.xx:3128
NO_PROXY=localblobstore,localhost
```

EventHubClientBuilder will throw a NullPointerException when calling  buildProducerClient: 
```
Caused by: java.lang.NullPointerException: null
    at com.azure.messaging.eventhubs.EventHubClientBuilder.getProxyOptions(EventHubClientBuilder.java:823) 
```

A Docker container running an earlier versions of the package work fine, like 5.10.0.
Is this bug related to a proxy bug in azure-core that got fixed in 1.19.0 (which 5.10.0 uses)? Maybe a regression in 1.20.0 (which 5.10.1 uses, the version we see this problem occur).

Problem also occurs in 5.10.2 which uses a newer azure-core version.

***Exception or Stack Trace***
```
Caused by: java.lang.NullPointerException: null
	at com.azure.messaging.eventhubs.EventHubClientBuilder.getProxyOptions(EventHubClientBuilder.java:823) ~[app.jar:1.0.0-SNAPSHOT]
	at com.azure.messaging.eventhubs.EventHubClientBuilder.getDefaultProxyConfiguration(EventHubClientBuilder.java:805) ~[app.jar:1.0.0-SNAPSHOT]
	at com.azure.messaging.eventhubs.EventHubClientBuilder.getConnectionOptions(EventHubClientBuilder.java:757) ~[app.jar:1.0.0-SNAPSHOT]
	at com.azure.messaging.eventhubs.EventHubClientBuilder.buildConnectionProcessor(EventHubClientBuilder.java:705) ~[app.jar:1.0.0-SNAPSHOT]
	at com.azure.messaging.eventhubs.EventHubClientBuilder.buildAsyncClient(EventHubClientBuilder.java:638) ~[app.jar:1.0.0-SNAPSHOT]
	at com.azure.messaging.eventhubs.EventHubClientBuilder.buildClient(EventHubClientBuilder.java:676) ~[app.jar:1.0.0-SNAPSHOT]
	at com.azure.messaging.eventhubs.EventHubClientBuilder.buildProducerClient(EventHubClientBuilder.java:584) ~[app.jar:1.0.0-SNAPSHOT]
```

The code line 823 in version 5.10.1 and 5.10.2 is azure-core proxy related: 
```
821            com.azure.core.http.ProxyOptions coreProxyOptions = com.azure.core.http.ProxyOptions
822                .fromConfiguration(configuration);
823            Proxy.Type proxyType = coreProxyOptions.getType().toProxyType();
```

**To Reproduce**
1) Use azure-messaging-eventhubs 5.10.1 or 5.10.2 
2) Set environment variables:
```
HTTPS_PROXY=http://10.xx.xx.xx:3128
HTTP_PROXY=http://10.xx.xx.xx:3128
NO_PROXY=localblobstore,localhost
```
3) Build a producer client:
```java
this.eventHubProducerClient = new EventHubClientBuilder()
	.transportType(AmqpTransportType.AMQP_WEB_SOCKETS)
        .connectionString(eventHubConfig.getConnectionString())
	.buildProducerClient();
```

**Expected behavior**
Earlier versions of the SDK worked perfectly (i.e. azure-messaging-eventhubs 5.10.0).  Expecting the same.

**Setup (please complete the following information):**
 - OS: Ubuntu 18.04 in a Docker Container via IoT Edge on an Edge device
 - Library/Libraries: azure-messaging-eventhubs 5.10.1
 - Java version: 11
 - Frameworks: Spring Boot

**Information Checklist**
Kindly make sure that you have added all the following information above and checkoff the required fields otherwise we will treat the issuer as an incomplete report
- [x] Bug Description Added
- [x] Repro Steps Added
- [x] Setup information Added

**Comment by derSchtefan** [comment]
Maybe a wrong version of some library gets loaded in by Maven through a transitive dependency?

Version that fails:
```xml
        <azure.iot.device.client.version>1.32.3</azure.iot.device.client.version>
        <azure.iot.service.client.version>1.33.1</azure.iot.service.client.version>

        <dependency>
            <groupId>com.azure</groupId>
            <artifactId>azure-storage-blob</artifactId>
            <version>12.14.0</version>
        </dependency>

        <dependency>
            <groupId>com.azure</groupId>
            <artifactId>azure-messaging-eventhubs</artifactId>
            <version>5.10.1</version>
        </dependency>
```

Version that works:

```xml
        <azure.iot.device.client.version>1.32.1</azure.iot.device.client.version>
        <azure.iot.service.client.version>1.33.0</azure.iot.service.client.version>

        <dependency>
            <groupId>com.azure</groupId>
            <artifactId>azure-storage-blob</artifactId>
            <version>12.13.0</version>
        </dependency>

        <dependency>
            <groupId>com.azure</groupId>
            <artifactId>azure-messaging-eventhubs</artifactId>
            <version>5.10.0</version>
        </dependency>
```

**Comment by joshfree** [comment]
@alzimmermsft could you please assist?

/cc @conniey

**Comment by alzimmermsft** [comment]
Hi @derSchtefan, thank you for filing this issue. 

It appears that `EventHubClientBuilder` is making an assumption that when `HTTP_PROXY` is configured there will be a viable proxy to use. Unfortunately, there is a missing piece where `java.net.useSystemProxies` also needs to be set to true, and this was also a more recent change (and as you found it was between 1.19.0 and 1.20.0 in azure-core).

The short-term fix, that will also resolve your issue, will be adding `java.net.useSystemProxies = true` in your configurations. I'll file a fix to have `EventHubClientBuilder`, and other potential areas, check the additional configuration as well.

**Comment by derSchtefan** [comment]
@alzimmermsft: I can confirm that setting this allows the application to run with and without proxy depending on the environment variables (Linux Docker container). Thank you.

**Comment by howellevans** [comment]
> @alzimmermsft: I can confirm that setting this allows the application to run with and without proxy depending on the environment variables (Linux Docker container). Thank you.

So I have noticed the problem goes away in 

```
		<dependency>
			<groupId>com.azure.spring</groupId>
			<artifactId>azure-spring-cloud-stream-binder-eventhubs</artifactId>
			<version>2.11.0</version>
		</dependency>
```
I was previously using 2.10.0

However I was never able to get the java.net.useSystemProxies work around going. I tried it as a -D option on the command line and in my application.yml. Can you provide an example of how you set that?

**Comment by alzimmermsft** [comment]
Yes @howellevans, these are the JVM properties I used `-Djava.net.useSystemProxies=true` and `-DHTTP_PROXY=http://localhost:8888` (I was using a locally ran Fiddler instance in this case). I'll follow-up by adding sample scenarios into the READMEs of `azure-core-http-netty` and `azure-core-http-okhttp`.

**Comment by derSchtefan** [comment]
> > @alzimmermsft: I can confirm that setting this allows the application to run with and without proxy depending on the environment variables (Linux Docker container). Thank you.
> 
> So I have noticed the problem goes away in
> 
> ```
> 		<dependency>
> 			<groupId>com.azure.spring</groupId>
> 			<artifactId>azure-spring-cloud-stream-binder-eventhubs</artifactId>
> 			<version>2.11.0</version>
> 		</dependency>
> ```
> 
> I was previously using 2.10.0
> 
> However I was never able to get the java.net.useSystemProxies work around going. I tried it as a -D option on the command line and in my application.yml. Can you provide an example of how you set that?

You set it on the command line when running your jar. For instance this is the full command line we are using in our Dockerfile:

ENTRYPOINT ["java","-Xmx128M","-Djava.net.useSystemProxies=true","-jar","./app.jar"]
