### ISSUE TITLE
Update image "vs2017-win2016" used for signing

### ISSUE THREAD

**Issue by mikeharder** [Azure/azure-sdk-for-java#25197]
Our pipelines currently use image `vs2017-win2016` for signing:

https://github.com/Azure/azure-sdk-for-java/search?q=vs2017-win2016

This image will be deprecated on 11/15/21 and removed on 3/15/22, so we should try migrating to `windows-2019` (and also moving from pool `Azure Pipelines` to `azsdk-pool-mms-win-2019-general`).

There might be issues on `windows-2019` as suggested in this discussion, but we should try it again and see what happens:

https://github.com/Azure/azure-sdk-for-java/pull/18872#discussion_r566519881

**Comment by weshaggard** [comment]
We are getting:

```
##[warning]The windows-2016 environment will be deprecated on November 15, 2021, and removed on March 15, 2022. Migrate to windows-latest instead. For more details see https://github.com/actions/virtual-environments/issues/4312
```
in our release builds so this is likely going to start breaking things soon.
