### ISSUE TITLE
[Form Recognizer] Failed AccessToken verification on UsGov and China cloud

### ISSUE THREAD

**Issue by hongli750210** [Azure/azure-sdk-for-java#25190]
We are running live tests against other clouds like US Gov and Azure China Cloud. The goal is to check whether new azure sdk package work with other clouds or not.

**Error Description:**
When running the integration test [`DocumentAnalysisAsyncClientTest.analyzeMultipageBusinessCardUrl`](https://github.com/Azure/azure-sdk-for-java/blob/main/sdk/formrecognizer/azure-ai-formrecognizer/src/test/java/com/azure/ai/formrecognizer/DocumentAnalysisAsyncClientTest.java#L797) on UsGov and China cloud, it returns the error `com.azure.core.exception.HttpResponseException: Status code 401, "{ "statusCode": 401, "message": "Unauthorized. Access token is missing, invalid, audience is incorrect (https://cognitiveservices.azure.us), or have expired." }"`. The error message is shown as following, for more details please check [here](https://dev.azure.com/azure-sdk/internal/_build/results?buildId=1173401&view=results).
![image](https://user-images.githubusercontent.com/74638143/140026751-03666a7b-9c24-4ec7-8cbe-5f7820f6cd35.png)
I have tried two more location on UsGov and China cloud as following, but it returns the same error.
UsGov cloud: UsGov - Azrizona, UsGov - Virginia
China cloud: China - East2, China - North2

**Error Tracking:**
Code [Link](https://github.com/Azure/azure-sdk-for-java/blob/main/sdk/formrecognizer/azure-ai-formrecognizer/src/main/java/com/azure/ai/formrecognizer/implementation/util/Utility.java#L107)
![image](https://user-images.githubusercontent.com/74638143/140285414-33687404-5541-4974-9c9f-92960528ef70.png)
The scope is hard code as ' https://cognitiveservices.azure.com/.default' leading to only work well in the public cloud.
Code [Link](https://github.com/Azure/azure-sdk-for-java/blob/main/sdk/formrecognizer/azure-ai-formrecognizer/src/main/java/com/azure/ai/formrecognizer/implementation/util/Constants.java#L15)
![image](https://user-images.githubusercontent.com/74638143/140285631-4280bf82-e07d-48a1-9f7a-a30f822c6652.png)

**Expected Behavior:**
Add different scopes for different clouds in Form Recognizer SDK.
The value of the scope in different clouds is follow:
Public cloud: https://cognitiveservices.azure.com/.default
UsGov cloud: https://cognitiveservices.azure.us/.default
China cloud: https://cognitiveservices.azure.cn/.default

@benbp, @scottaddie, @joshfree, @meeraharidasa, @mayurid and @mssfang for notification.

**Comment by joshfree** [comment]
@samvaity could you help prioritize this sovereign cloud issue for the March release?
