### ISSUE TITLE
[BUG] ServiceBus | If a message is prefetched, auto lock renewal does not work on that

### ISSUE THREAD

**Issue by prabdeb** [Azure/azure-sdk-for-java#25203]
**Describe the bug:**

In a processor client consumer, if a message is prefetched, auto lock renewal does not work on that. The `lockedUntil` holds the value of prefetched time + lock duration.

Log from application in `processMessage` of processor client consumer:

```log
INFO: asb message processing receivedAt=2021-10-25T11:32:02.086Z messageId=xxxxxxxxxxxxx deliveryCount=0 lockedUntil=2021-10-25T11:30:23.206Z
```

Where we can see the message came to `processMessage` after `lockedUntil` and after processing the application logic while trying to complete the message - `messageContext.complete()`, we are getting following error.

***Exception or Stack Trace***

```log
ERROR: The lock supplied is invalid. Either the lock expired, or the message has already been removed from the queue. Reference:xxxxx, TrackingId:xxxxxxx, SystemTracker:xxxx:Topic:xxxxx|xxxxx, Timestamp:2021-10-25T11:32:20, errorContext[NAMESPACE: xxxx.servicebus.windows.net. ERROR CONTEXT: N/A, PATH: xxxx/subscriptions/xxxxx, REFERENCE_ID: xxxxx/subscriptions/xxx_xxxx_xxxx, LINK_CREDIT: 0]
```

**To Reproduce:**

- Create ServiceBus Topic/Subscription with Lock duration 5 minuets
- Create Processor client consumer with `prefetchCount=1`, `maxConcurrentCalls=1`, `maxAutoLockRenewDuration=600seconds`, with PEEK_LOCK enabled and `disableAutoComplete` is true.
- Ex. code snippet of processor client

```java
new ServiceBusClientBuilder()
        .connectionString("xxxx")
        .retryOptions(retryOptions)
        .processor()
        .topicName("xxxxx")
        .subscriptionName("xxxxxx")
        .maxConcurrentCalls(1)
        .prefetchCount(1)
        .disableAutoComplete()
        .processError(processError)
        .processMessage(processMessage)
        .receiveMode(ServiceBusReceiveMode.valueOf("PEEK_LOCK"))
        .maxAutoLockRenewDuration(Duration.ofSeconds(600))
        .buildProcessorClient();
```

***Code Snippet***

`processMessage` implementation -

```java
Consumer<ServiceBusReceivedMessageContext> processMessage = context -> {
    OffsetDateTime asbMessageReceivedAt = OffsetDateTime.now();
    OffsetDateTime asbMessageLockedUntil = context.getMessage().getLockedUntil();
    log.info("asb message processing receivedAt={} messageId={} deliveryCount={} lockedUntil={}",
            asbMessageReceivedAt,
            context.getMessage().getMessageId(),
            context.getMessage().getDeliveryCount(),
            asbMessageLockedUntil);
    // Business logics that takes more than 5 minutes sometime
    // To reproduce use following sleep of 7 minutes
    TimeUnit.MINUTES.sleep(7);
    messageContext.complete();
};
```

**Expected behavior**
If a message is prefetched and auto lock renewal is enabled, auto lock renewal should keep renewing lock of prefetched message (in this above example it's expected that `lockedUntil` will be increasing by auto lock renewal).

**Setup (please complete the following information):**

- OS: Linux
- IDE: IntelliJ
- Library/Libraries: com.azure:azure-messaging-servicebus:7.4.1
- Java version: 11
- App Server/Environment: Azure Kubernetes Service
- Frameworks: Spring Boot

If you suspect a dependency version mismatch (e.g. you see `NoClassDefFoundError`, `NoSuchMethodError` or similar), please provide

- N/A
  
**Additional context** N/A

**Information Checklist:**

Kindly make sure that you have added all the following information above and checkoff the required fields otherwise we will treat the issuer as an incomplete report

- [x] Bug Description Added
- [x] Repro Steps Added
- [x] Setup information Added

**Comment by ramya-rao-a** [comment]
Hey @prabdeb 

Unfortunately, renewing locks on prefetched messages is not a feature we can support. Please see the documentation at [Why is Prefetch not the default option?](https://docs.microsoft.com/en-us/azure/service-bus-messaging/service-bus-prefetch?tabs=dotnet#why-is-prefetch-not-the-default-option)

In your case looks like your message processing takes a few minutes. We highly recommend disabling the prefetch feature in such cases.
