### ISSUE TITLE
[FEATURE REQ] ServiceBus | Do not process prefetched messages if locked duration is past and the message is back to topic

### ISSUE THREAD

**Issue by prabdeb** [Azure/azure-sdk-for-java#25204]
**Is your feature request related to a problem? Please describe.**

After receiving a prefetched messages in `processMessage`, if business logics takes more than 5 minutes (max duration of message lock), message processing gets failed while trying to complete the message.

Log from application in `processMessage` of processor client consumer:

```log
INFO: asb message processing receivedAt=2021-10-25T11:32:02.086Z messageId=xxxxxxxxxxxxx deliveryCount=0 lockedUntil=2021-10-25T11:30:23.206Z
```

Where we can see the message came to `processMessage` after `lockedUntil` and after processing the application logic while trying to complete the message - `messageContext.complete()`, we are getting following error.

***Exception or Stack Trace***

```log
ERROR: The lock supplied is invalid. Either the lock expired, or the message has already been removed from the queue. Reference:xxxxx, TrackingId:xxxxxxx, SystemTracker:xxxx:Topic:xxxxx|xxxxx, Timestamp:2021-10-25T11:32:20, errorContext[NAMESPACE: xxxx.servicebus.windows.net. ERROR CONTEXT: N/A, PATH: xxxx/subscriptions/xxxxx, REFERENCE_ID: xxxxx/subscriptions/xxx_xxxx_xxxx, LINK_CREDIT: 0]
```

code snippet of processor client -

```java
new ServiceBusClientBuilder()
        .connectionString("xxxx")
        .retryOptions(retryOptions)
        .processor()
        .topicName("xxxxx")
        .subscriptionName("xxxxxx")
        .maxConcurrentCalls(1)
        .prefetchCount(1)
        .disableAutoComplete()
        .processError(processError)
        .processMessage(processMessage)
        .receiveMode(ServiceBusReceiveMode.valueOf("PEEK_LOCK"))
        .maxAutoLockRenewDuration(Duration.ofSeconds(600))
        .buildProcessorClient();
```

**Describe the solution you'd like:**

We would like ASB SDK to handle the scenario described above by validating if a prefetched messages `lockedUntil` is already passed and `receiveMode=PEEK_LOCK` and  `disableAutoComplete=TRUE`, do not send the message to `processMessage`.

Else this will cause the error described above while completing the message, also since the message is back to Topic/Subscription, another consumer instance has already started processing the same message and that will cause duplicate processing of business logic.

**Describe alternatives you've considered:**

We have considered disabling prefetch, but we were unable to disable the prefetch my setting `prefetchCount=0`.
Where we faced similar issues as described in [[BUG] Service bus | Can't disable the prefetch count](https://github.com/Azure/azure-sdk-for-java/issues/17681).

**Additional context** N/A

**Information Checklist:**

Kindly make sure that you have added all the following information above and checkoff the required fields otherwise we will treat the issuer as an incomplete report

- [x] Description Added
- [x] Expected solution specified

**Comment by ramya-rao-a** [comment]
> We have considered disabling prefetch, but we were unable to disable the prefetch my setting prefetchCount=0.
Where we faced similar issues as described in [[BUG] Service bus | Can't disable the prefetch count.](https://github.com/Azure/azure-sdk-for-java/issues/17681)

@prabdeb The problem described in the linked issue is for a corner case where a previously timed our receive request is fulfilled at a later time but not provided to the user as there is no active receive request and so loses the lock. See the explanation at https://github.com/Azure/azure-sdk-for-java/issues/17681#issuecomment-748567630. You should still be able to disable the prefetch feature by setting prefetchCount to 0

The rest of what you have described seems like a valid feature request i.e. skip the message from the prefetch queue if it has lost the lock. We will discuss this further with the service team, go over the pros and cons and get back to you. Meanwhile, you can do this at your end as well by checking the `lockedUntil` property against current time in your `processMessage`

**Comment by ramya-rao-a** [comment]
> The rest of what you have described seems like a valid feature request i.e. skip the message from the prefetch queue if it has lost the lock. We will discuss this further with the service team, go over the pros and cons and get back to you. Meanwhile, you can do this at your end as well by checking the lockedUntil property against current time in your processMessage

On further discussion, the main downside of the client skipping such messages is that there is a potential that this can happen to a message multiple times i.e. the client receives it, but loses the lock by the time the caller needs to process it. When this happens enough number of times, max delivery count is reached and the message is sent to the dead letter queue. In this scenario, the caller's code never sees this message. So, we go from a problem of caller getting the same message twice to caller never getting a message. Since Service Bus gives at-least one guarantee, we cannot allow that to happen.

The Service Bus team and the SDK team believe that the best course of action here is to
- Enable prefetch only if the message processing time is not long enough to cause messages in prefetch buffer to lose locks
- Or to check `lockedUntil` and `deliveryCount` properties on the message in the `processMessage` to determine whether you want to process or ignore the message. If lockedUntil is past the current time (lock is lost) and deliveryCount has reached max delivery count, then process the message else ignore it.
