### ISSUE TITLE
[QUERY] how to get  scope for creating AzureResourceManager from azure china 

### ISSUE THREAD

**Issue by Neil-Boyle** [Azure/azure-sdk-for-java#25205]
**Query/Question**

config like official domo:

**scope**

```
 @Bean
    public AzureResourceManager azureResourceManager(){
        AzureProfile profile = new AzureProfile(AzureEnvironment.AZURE);
        ClientSecretCredential clientSecretCredential = new ClientSecretCredentialBuilder()
                .clientId("XXX")
                .clientSecret("XXX")
                .tenantId("XXX")

                // authority host is optional
//                .authorityHost("<AZURE_AUTHORITY_HOST>")
                .build();
        return AzureResourceManager
                .authenticate(clientSecretCredential, profile)
                .withScope()
                .withDefaultSubscription();
    }
```

any help will be welcome ,TKS

dependency:
```
<dependency>
      <groupId>com.azure.resourcemanager</groupId>
      <artifactId>azure-resourcemanager</artifactId>
      <version>2.9.0</version>
  </dependency>
  <dependency>
      <groupId>com.azure</groupId>
      <artifactId>azure-core-http-netty</artifactId>
      <version>1.9.1</version>
  </dependency>
  <dependency>
      <groupId>com.azure</groupId>
      <artifactId>azure-identity</artifactId>
      <version>1.4.0</version>
  </dependency>

```

***Why is this not a Bug or a feature Request?***
A clear explanation of why is this not a bug or a feature request?

**Setup (please complete the following information if applicable):**
 - IDE: [e.g. IntelliJ]
 - Library/Libraries: [e.g. com.azure:azure-core:1.16.0 (groupId:artifactId:version)]
 
 **Information Checklist**
 Kindly make sure that you have added all the following information above and checkoff the required fields otherwise we will treat the issuer as an incomplete report
- [x] Query Added
- [x] Setup information Added

**Comment by weidongxu-microsoft** [comment]
@Neil-Boyle 

You do not need to specify the scope.

When create the `AzureProfile`, choose `AzureEnvironment,AZURE_CHINA`, which should have the preconfigured cloud endpoints and scopes.

**Comment by Neil-Boyle** [comment]
it works , ths!
