### ISSUE TITLE
Client initialization failed when using azure-spring-data-cosmos to connect to azure cosmos db

### ISSUE THREAD

**Issue by Spikesnaveen** [Azure/azure-sdk-for-java#25218]
**Query/Question**
Im trying to connect to azure cosmos db through spring boot, but im getting "Client initialization failed. Check if the endpoint is reachable and if your auth token is valid" exception.

I'm using spring boot cosmos data dependency. 
Credentials which im using is correct of my knowledge.
Tried connecting through c#, it is working fine.

**Setup**
 - OS: windows 10
 - IDE: eclipse
 - Library/Libraries: azure-spring-data-cosmos (3.9.0)

**Comment by joshfree** [comment]
@backwind1233 can you please follow up with @Spikesnaveen on their `azure-spring-data-cosmos` question?

**Comment by backwind1233** [comment]
@Spikesnaveen what is your configuration file looks like, can you give me a demo?
