### ISSUE TITLE
Spring Cloud Azure 4.0 Make sure no credential information required when using our first party SDKs, leverage DefaultTokenCredential to support both dev / prod (MSI) enabled environment.

### ISSUE THREAD

**Issue by saragluna** [Azure/azure-sdk-for-java#25224]
Whenever developers use our Spring libraries, we should make sure that credential is not a hard requirement, they could always use local developing environment or managed identity to authenticate.

**Comment by stliu** [comment]
we should update our samples to leverage default credential

**Comment by moarychan** [comment]
I have tested the eventhubs binder using service principal and managed identify(in App Service), it works, but I do not update Spring Cloud Azure samples yet.

Hi @backwind1233 , I noticed this issue https://github.com/Azure/azure-sdk-for-java/issues/25652, will you update all the Spring Cloud Azure Samples using the default credential, right?

**Comment by saragluna** [comment]
Tested with App Service by @backwind1233, and ASC has some issues https://github.com/Azure/azure-sdk-for-java/issues/26541, closing this now.
