### ISSUE TITLE
Health Indicators for App Config.

### ISSUE THREAD

**Issue by saragluna** [Azure/azure-sdk-for-java#25225]
The autoconfiguration of app config client is missing a health indicator, we should add it.

**Comment by mrm9084** [comment]
@saragluna Is this different than the already created ones?

**Comment by moarychan** [comment]
> @saragluna Is this different than the already created ones?

It should be a new indicator using `ConfigurationClient` directly.

**Comment by saragluna** [comment]
Closing this issue now for #25364 has implemented it. 

Yes @mrm9084, it's a different one for the level 1 SDK.
