### ISSUE TITLE
ComputeManagementClient proxy support

### ISSUE THREAD

**Issue by dhirajnitk** [Azure/azure-sdk-for-java#2525]
**What happened**:
ComputeManagementClient Class in C# has constructors  with httpClient  
 eg. `ComputeManagementClient(SubscriptionCloudCredentials, HttpClient) `but ComputeManagementClientImpl.java in java sdk hasn't defined any constructors to support HttpClient.

How is it possible to support proxy in  ComputeManagementClientImpl?

**Comment by vhvb1989** [comment]
Hello @dhirajnitk 

I am sorry about you didn't get a sooner answer on this
Do you still need help? Let me know and I would be happy to assist.

Note: As part of repository cleaning effort, this issue will be closed by Sep 20 if no response is received from submitter and/or not further action is required.
