### ISSUE TITLE
Azure Service Bus | More details about prefetchCount and maxConcurrentSessions in ServiceBusClientBuilder.ServiceBusSessionProcessorClientBuilder Class

### ISSUE THREAD

**Issue by prabdeb** [Azure/azure-sdk-for-java#25293]
**ISSUE:**

In document [https://docs.microsoft.com/en-us/java/api/com.azure.messaging.servicebus.servicebusclientbuilder.servicebussessionprocessorclientbuilder?view=azure-java-stable](https://docs.microsoft.com/en-us/java/api/com.azure.messaging.servicebus.servicebusclientbuilder.servicebussessionprocessorclientbuilder?view=azure-java-stable) it would be good to have the following details about `prefetchCount(int prefetchCount)` -

- Since we can't disabled the prefetch as per #17681 , what will be the behaviour if we do not set it, how many messages will be prefetched?
- What should be recommended settings? Would this number be related to `maxConcurrentCalls(int maxConcurrentCalls)`?

In document [https://docs.microsoft.com/en-us/java/api/com.azure.messaging.servicebus.servicebusclientbuilder.servicebussessionprocessorclientbuilder?view=azure-java-stable](https://docs.microsoft.com/en-us/java/api/com.azure.messaging.servicebus.servicebusclientbuilder.servicebussessionprocessorclientbuilder?view=azure-java-stable) it would be good to have the following details about `maxConcurrentSessions(int maxConcurrentSessions)` -

- What it does, what will happen if we don't set it?
- If we would like to set it, what would be it's recommended value, will `maxConcurrentCalls(int maxConcurrentCalls)` have any impact on this configuration settings?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5bf820f1-a84f-99a7-f9bb-37688b63359a
* Version Independent ID: e9cc8b71-1f13-e0ed-85ca-3d681e6c2033
* Content: [Azure Service Bus client library for Java](https://docs.microsoft.com/en-us/java/api/overview/azure/messaging-servicebus-readme?view=azure-java-stable)
* Content Source: [docs-ref-services/latest/messaging-servicebus-readme.md](https://github.com/Azure/azure-docs-sdk-java/blob/master/docs-ref-services/latest/messaging-servicebus-readme.md)
* Service: **servicebus**
* Product: **azure**
* Technology: **azure**
* GitHub Login: @ramya-rao-a
* Microsoft Alias: **ramyar**

**Comment by ramya-rao-a** [comment]
@anuchandy Assigning this to you as you have been investigating the prefetch area recently

**Comment by anuchandy** [comment]
Related to this - we published a document explaining how prefetch works with sync receiver in this pr https://github.com/Azure/azure-sdk-for-java/pull/26447 

We'll still need to create a Doc / JavaDoc on prefetch relation to the  session receiver.

**Comment by anuchandy** [comment]
The accuracy of this documentation ticket depends on this [feature-work](https://github.com/Azure/azure-sdk-for-java/issues/27336) 27336. I'm updating 27336 to have a sub-item on this documentation, closing this.
