### ISSUE TITLE
[QUERY] Requesting a release of azure-monitor-opentelemetry-exporter

### ISSUE THREAD

**Issue by renuka-fernando** [Azure/azure-sdk-for-java#25295]
**Query/Question**
Release request for azure-monitor-opentelemetry-exporter 1.0.0-beta.5
Current released versions: https://mvnrepository.com/artifact/com.azure/azure-monitor-opentelemetry-exporter

***Why is this not a Bug or a feature Request?***
Need to get a release of ` azure-monitor-opentelemetry-exporter` with `netty-handler` is updated to `4.1.68.Final`.
We could identify you have already updated the netty version in 1.0.0-beta5, but it is not yet released. Could you please release this version?

**Setup (please complete the following information if applicable):**
 - OS: iOS
 - IDE: IntelliJ
 - Library/Libraries: com.azure:azure-monitor-opentelemetry-exporter:1.0.0-beta.4
 
 **Information Checklist**
 Kindly make sure that you have added all the following information above and checkoff the required fields otherwise we will treat the issuer as an incomplete report
- [x] Query Added
- [x] Setup information Added

**Comment by srnagar** [comment]
Thanks for reporting this issue @renuka-fernando.

@kryalama could you please help with releasing the beta-5 version?

**Comment by renuka-fernando** [comment]
@kryalama could you please help with releasing the beta-5 version?

**Comment by kryalama** [comment]
@renuka-fernando 1.0.0-beta-5 released to maven :)

**Comment by renuka-fernando** [comment]
@kryalama, Thank you for the support
