### ISSUE TITLE
Azure Service Bus | More details about prefetchCount in ServiceBusClientBuilder.ServiceBusProcessorClientBuilder Class

### ISSUE THREAD

**Issue by prabdeb** [Azure/azure-sdk-for-java#25294]
**ISSUE:**

In document [https://docs.microsoft.com/en-us/java/api/com.azure.messaging.servicebus.servicebusclientbuilder.servicebusprocessorclientbuilder?view=azure-java-stable](https://docs.microsoft.com/en-us/java/api/com.azure.messaging.servicebus.servicebusclientbuilder.servicebusprocessorclientbuilder?view=azure-java-stable) it would be good to have the following details about prefetchCount(int prefetchCount) -

- Since we can't disabled the prefetch as per #17681 , what will be the behaviour if we do not set it, how many messages will be prefetched?
- What should be recommended settings? Would this number be related to maxConcurrentCalls(int maxConcurrentCalls)?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5bf820f1-a84f-99a7-f9bb-37688b63359a
* Version Independent ID: e9cc8b71-1f13-e0ed-85ca-3d681e6c2033
* Content: [Azure Service Bus client library for Java](https://docs.microsoft.com/en-us/java/api/overview/azure/messaging-servicebus-readme?view=azure-java-stable)
* Content Source: [docs-ref-services/latest/messaging-servicebus-readme.md](https://github.com/Azure/azure-docs-sdk-java/blob/master/docs-ref-services/latest/messaging-servicebus-readme.md)
* Service: **servicebus**
* Product: **azure**
* Technology: **azure**
* GitHub Login: @ramya-rao-a
* Microsoft Alias: **ramyar**

**Comment by ramya-rao-a** [comment]
Thanks for reporting @prabdeb 
Since you have covered the same in your other issue #25293, we will close this one.
