### ISSUE TITLE
Azure Service Bus | Missing details about other maven dependencies that need to be added while using ASB SDK

### ISSUE THREAD

**Issue by prabdeb** [Azure/azure-sdk-for-java#25292]
**ISSUE:**

If we add the following dependency into Java `pom.xml` as per document, the application does not work -

```xml
<dependency>
    <groupId>com.azure</groupId>
    <artifactId>azure-messaging-servicebus</artifactId>
    <version>7.4.1</version>
</dependency>
```
However after adding the following extra dependencies into `pom.xml`, application started working -

```xml
<dependency>
	<groupId>io.projectreactor</groupId>
	<artifactId>reactor-core</artifactId>
	<version>3.4.9</version>
</dependency>
<dependency>
	<groupId>com.azure</groupId>
	<artifactId>azure-core</artifactId>
	<version>1.17.0</version>
</dependency>
```

The same issue is present while using admin client, and if we add the following extra dependencies into `pom.xml`, application that uses admin client started working -

```xml
<dependency>
	<groupId>io.projectreactor.netty</groupId>
	<artifactId>reactor-netty</artifactId>
	<version>1.0.7</version>
</dependency>
<dependency>
	<groupId>com.azure</groupId>
	<artifactId>azure-core-http-okhttp</artifactId>
	<version>1.7.0</version>
</dependency>
<dependency>
	<groupId>com.azure</groupId>
	<artifactId>azure-core-http-netty</artifactId>
	<version>1.10.0</version>
</dependency>
<dependency>
	<groupId>com.azure</groupId>
	<artifactId>azure-core</artifactId>
	<version>1.17.0</version>
</dependency>
```

**EXPECTED:**

Either the required dependencies needed by `azure-messaging-servicebus` should be added in `pom.xml` of `azure-messaging-servicebus` or it should be clear in document what all dependencies (along with the right version) we need to add for `azure-messaging-servicebus`.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5bf820f1-a84f-99a7-f9bb-37688b63359a
* Version Independent ID: e9cc8b71-1f13-e0ed-85ca-3d681e6c2033
* Content: [Azure Service Bus client library for Java](https://docs.microsoft.com/en-us/java/api/overview/azure/messaging-servicebus-readme?view=azure-java-stable)
* Content Source: [docs-ref-services/latest/messaging-servicebus-readme.md](https://github.com/Azure/azure-docs-sdk-java/blob/master/docs-ref-services/latest/messaging-servicebus-readme.md)
* Service: **servicebus**
* Product: **azure**
* Technology: **azure**
* GitHub Login: @ramya-rao-a
* Microsoft Alias: **ramyar**

**Comment by ramya-rao-a** [comment]
Thanks for reporting @prabdeb 

@ki1729 Can you please take a look at this? Do our other packages have similar issues as well? Perhaps event hubs?

**Comment by ZejiaJiang** [comment]
Hi @prabdeb , 

I'm Zejia from Azure SDK team. 

I'm 90 percent sure that there is a maven dependency conflict in you application. Because you specify a version fix this. There could be another jar require these two dependencies.

So, could you please provide the dependency tree by using `mvn dependency:tree` and some code snippets?
