### ISSUE TITLE
[BUG] azure-spring-boot-bom 3.10.0 version mismatch from bom vs starter dependency for azure-security-keyvault-secrets

### ISSUE THREAD

**Issue by Shashi-rk** [Azure/azure-sdk-for-java#25298]
**Describe the bug**

azure-spring-boot-starter-keyvault-secrets:jar:3.10.0 comes with azure-security-keyvault-secrets:jar:4.3.4 when used directly, however azure-spring-boot-bom of version 3.10.0 , resolve to version 4.3.3 of azure-security-keyvault-secrets.

spring-boot-starter-keyvault-secrets has latest of azure-security-keyvault-secrets but azure-spring-boot-bom is overriding that with lower version.

***Exception or Stack Trace***
No Trace, library version mismatch, forcing to manually override starter version unlike using bom only.

**To Reproduce**
mvn dependency:analyze

***Code Snippet***
NA

**Expected behavior**
azure-spring-boot-bom:3.10.0 should resolve to azure-security-keyvault-secrets:jar:4.3.4 

**Screenshots**
dependency tree provided 

**Setup (please complete the following information):**
 - OS: windows
 - IDE: Intellij
 - Library/Libraries: azure-spring-boot-starter-keyvault-secrets:jar:3.10.0  vs azure-spring-boot-bom 3.10.0
 - Java version: 11
 - App Server/Environment: Tomcat
 - Frameworks: Spring Boot

If you suspect a dependency version mismatch (e.g. you see `NoClassDefFoundError`, `NoSuchMethodError` or similar), please provide
- verbose dependency tree (`mvn dependency:tree -Dverbose`)

[DEBUG] com.example:demo:jar:0.0.1-SNAPSHOT
[DEBUG]    com.azure.spring:azure-spring-boot-starter-keyvault-secrets:jar:3.10.0:compile
[DEBUG]       org.springframework.boot:spring-boot-starter:jar:2.5.6:compile (version managed from 2.5.4)
[DEBUG]          org.springframework.boot:spring-boot:jar:2.5.6:compile (version managed from 2.5.6)
[DEBUG]             org.springframework:spring-context:jar:5.3.12:compile (version managed from 5.3.12)
[DEBUG]                org.springframework:spring-aop:jar:5.3.12:compile (version managed from 5.3.12)
[DEBUG]                org.springframework:spring-expression:jar:5.3.12:compile (version managed from 5.3.12)
[DEBUG]          org.springframework.boot:spring-boot-autoconfigure:jar:2.5.6:compile (version managed from 2.5.6)
[DEBUG]          org.springframework.boot:spring-boot-starter-logging:jar:2.5.6:compile (version managed from 2.5.6)
[DEBUG]             ch.qos.logback:logback-classic:jar:1.2.6:compile (version managed from 1.2.6)
[DEBUG]                ch.qos.logback:logback-core:jar:1.2.6:compile (version managed from 1.2.6)
[DEBUG]             org.apache.logging.log4j:log4j-to-slf4j:jar:2.14.1:compile (version managed from 2.14.1)
[DEBUG]                org.apache.logging.log4j:log4j-api:jar:2.14.1:compile (version managed from 2.14.1)
[DEBUG]             org.slf4j:jul-to-slf4j:jar:1.7.32:compile (version managed from 1.7.32)
[DEBUG]          jakarta.annotation:jakarta.annotation-api:jar:1.3.5:compile (version managed from 1.3.5)
[DEBUG]          org.yaml:snakeyaml:jar:1.28:compile (version managed from 1.28)
[DEBUG]       org.springframework.boot:spring-boot-starter-validation:jar:2.5.6:compile (version managed from 2.5.4)
[DEBUG]          org.apache.tomcat.embed:tomcat-embed-el:jar:9.0.54:compile (version managed from 9.0.54)
[DEBUG]          org.hibernate.validator:hibernate-validator:jar:6.2.0.Final:compile (version managed from 6.2.0.Final)
[DEBUG]             jakarta.validation:jakarta.validation-api:jar:2.0.2:compile (version managed from 2.0.2)
[DEBUG]             org.jboss.logging:jboss-logging:jar:3.4.2.Final:compile (version managed from 3.4.1.Final)
[DEBUG]             com.fasterxml:classmate:jar:1.5.1:compile (version managed from 1.5.1)
[DEBUG]       com.azure.spring:azure-spring-boot:jar:3.10.0:compile (version managed from 3.10.0)
[DEBUG]          org.slf4j:slf4j-api:jar:1.7.32:compile (version managed from 1.7.32)
[DEBUG]          org.springframework:spring-web:jar:5.3.12:compile (version managed from 5.3.9)
[DEBUG]             org.springframework:spring-beans:jar:5.3.12:compile (version managed from 5.3.12)
[DEBUG]          javax.validation:validation-api:jar:2.0.1.Final:compile (version managed from 2.0.1.Final)
[DEBUG]          javax.annotation:javax.annotation-api:jar:1.3.2:compile (version managed from 1.3.2)
[DEBUG]          com.fasterxml.jackson.core:jackson-databind:jar:2.12.4:compile (version managed from 2.12.5)
[DEBUG]             com.fasterxml.jackson.core:jackson-annotations:jar:2.12.4:compile (version managed from 2.12.4)
[DEBUG]             com.fasterxml.jackson.core:jackson-core:jar:2.12.4:compile (version managed from 2.12.4)
[DEBUG]       com.azure:azure-identity:jar:1.3.6:compile (version managed from 1.4.0)
[DEBUG]          com.azure:azure-core:jar:1.20.0:compile (version managed from 1.20.0)
[DEBUG]             com.fasterxml.jackson.datatype:jackson-datatype-jsr310:jar:2.12.4:compile (version managed from 2.12.4)
[DEBUG]             com.fasterxml.jackson.dataformat:jackson-dataformat-xml:jar:2.12.4:compile (version managed from 2.12.4)
[DEBUG]                com.fasterxml.jackson.module:jackson-module-jaxb-annotations:jar:2.12.4:compile (version managed from 2.12.4)
[DEBUG]                org.codehaus.woodstox:stax2-api:jar:4.2.1:compile
[DEBUG]                com.fasterxml.woodstox:woodstox-core:jar:6.2.4:compile
[DEBUG]             io.projectreactor:reactor-core:jar:3.4.9:compile (version managed from 3.4.9)
[DEBUG]                org.reactivestreams:reactive-streams:jar:1.0.3:compile (version managed from 1.0.3)
[DEBUG]             io.netty:netty-tcnative-boringssl-static:jar:2.0.44.Final:compile (version managed from 2.0.40.Final)
[DEBUG]          com.azure:azure-core-http-netty:jar:1.11.0:compile (version managed from 1.11.0)
[DEBUG]             io.netty:netty-handler:jar:4.1.67.Final:compile (version managed from 4.1.67.Final)
[DEBUG]                io.netty:netty-common:jar:4.1.67.Final:compile (version managed from 4.1.67.Final)
[DEBUG]                io.netty:netty-resolver:jar:4.1.67.Final:compile (version managed from 4.1.67.Final)
[DEBUG]                io.netty:netty-transport:jar:4.1.67.Final:compile (version managed from 4.1.67.Final)
[DEBUG]                io.netty:netty-codec:jar:4.1.67.Final:compile (version managed from 4.1.67.Final)
[DEBUG]             io.netty:netty-handler-proxy:jar:4.1.67.Final:compile (version managed from 4.1.67.Final)
[DEBUG]                io.netty:netty-codec-socks:jar:4.1.67.Final:compile (version managed from 4.1.67.Final)
[DEBUG]             io.netty:netty-buffer:jar:4.1.67.Final:compile (version managed from 4.1.67.Final)
[DEBUG]             io.netty:netty-codec-http:jar:4.1.67.Final:compile (version managed from 4.1.67.Final)
[DEBUG]             io.netty:netty-codec-http2:jar:4.1.67.Final:compile (version managed from 4.1.67.Final)
[DEBUG]             io.netty:netty-transport-native-unix-common:jar:4.1.67.Final:compile (version managed from 4.1.67.Final)
[DEBUG]             io.netty:netty-transport-native-epoll:jar:linux-x86_64:4.1.67.Final:compile (version managed from 4.1.67.Final)
[DEBUG]             io.netty:netty-transport-native-kqueue:jar:osx-x86_64:4.1.67.Final:compile (version managed from 4.1.67.Final)
[DEBUG]             io.projectreactor.netty:reactor-netty:jar:1.0.10:compile (version managed from 1.0.10)
[DEBUG]                io.projectreactor.netty:reactor-netty-core:jar:1.0.10:compile (version managed from 1.0.10)
[DEBUG]                   io.netty:netty-resolver-dns:jar:4.1.67.Final:compile (version managed from 4.1.66.Final)
[DEBUG]                      io.netty:netty-codec-dns:jar:4.1.67.Final:compile (version managed from 4.1.67.Final)
[DEBUG]                   io.netty:netty-resolver-dns-native-macos:jar:osx-x86_64:4.1.67.Final:compile (version managed from 4.1.66.Final)
[DEBUG]                io.projectreactor.netty:reactor-netty-http:jar:1.0.10:compile (version managed from 1.0.10)
[DEBUG]                io.projectreactor.netty:reactor-netty-http-brave:jar:1.0.10:runtime (version managed from 1.0.10)
[DEBUG]                   io.zipkin.brave:brave-instrumentation-http:jar:5.13.3:runtime
[DEBUG]                      io.zipkin.brave:brave:jar:5.13.3:runtime
[DEBUG]                         io.zipkin.reporter2:zipkin-reporter-brave:jar:2.16.3:runtime
[DEBUG]                            io.zipkin.reporter2:zipkin-reporter:jar:2.16.3:runtime
[DEBUG]                               io.zipkin.zipkin2:zipkin:jar:2.23.2:runtime
[DEBUG]          com.microsoft.azure:msal4j:jar:1.11.0:compile (version managed from 1.11.0)
[DEBUG]             com.nimbusds:oauth2-oidc-sdk:jar:9.9.1:compile (version managed from 9.7)
[DEBUG]                com.github.stephenc.jcip:jcip-annotations:jar:1.0-1:compile
[DEBUG]                com.nimbusds:content-type:jar:2.1:compile
[DEBUG]                com.nimbusds:lang-tag:jar:1.5:compile
[DEBUG]                com.nimbusds:nimbus-jose-jwt:jar:9.10.1:compile (version managed from 9.10.1)
[DEBUG]          com.microsoft.azure:msal4j-persistence-extension:jar:1.1.0:compile (version managed from 1.1.0)
[DEBUG]             net.java.dev.jna:jna:jar:5.5.0:compile
[DEBUG]          net.java.dev.jna:jna-platform:jar:5.6.0:compile (version managed from 5.6.0)
[DEBUG]          net.minidev:json-smart:jar:2.4.7:compile (version managed from 2.4.7)
[DEBUG]             net.minidev:accessors-smart:jar:2.4.7:compile
[DEBUG]                org.ow2.asm:asm:jar:9.1:compile
[DEBUG]       **com.azure:azure-security-keyvault-secrets:jar:4.3.3:compile (version managed from 4.3.4)**
[DEBUG]    org.springframework.boot:spring-boot-starter-test:jar:2.5.6:test
[DEBUG]       org.springframework.boot:spring-boot-test:jar:2.5.6:test (version managed from 2.5.6)
[DEBUG]       org.springframework.boot:spring-boot-test-autoconfigure:jar:2.5.6:test (version managed from 2.5.6)
[DEBUG]       com.jayway.jsonpath:json-path:jar:2.5.0:test (version managed from 2.5.0)
[DEBUG]       jakarta.xml.bind:jakarta.xml.bind-api:jar:2.3.3:compile (version managed from 2.3.3)
[DEBUG]          jakarta.activation:jakarta.activation-api:jar:1.2.2:compile (version managed from 1.2.2)
[DEBUG]       org.assertj:assertj-core:jar:3.19.0:test (version managed from 3.19.0)
[DEBUG]       org.hamcrest:hamcrest:jar:2.2:test (version managed from 2.2)
[DEBUG]       org.junit.jupiter:junit-jupiter:jar:5.7.2:test (version managed from 5.7.2)
[DEBUG]          org.junit.jupiter:junit-jupiter-api:jar:5.7.2:test (version managed from 5.7.2)
[DEBUG]             org.apiguardian:apiguardian-api:jar:1.1.0:test
[DEBUG]             org.opentest4j:opentest4j:jar:1.2.0:test
[DEBUG]             org.junit.platform:junit-platform-commons:jar:1.7.2:test (version managed from 1.7.2)
[DEBUG]          org.junit.jupiter:junit-jupiter-params:jar:5.7.2:test (version managed from 5.7.2)
[DEBUG]          org.junit.jupiter:junit-jupiter-engine:jar:5.7.2:test (version managed from 5.7.2)
[DEBUG]             org.junit.platform:junit-platform-engine:jar:1.7.2:test (version managed from 1.7.2)
[DEBUG]       org.mockito:mockito-core:jar:3.9.0:test (version managed from 3.9.0)
[DEBUG]          net.bytebuddy:byte-buddy:jar:1.10.22:test (version managed from 1.10.20)
[DEBUG]          net.bytebuddy:byte-buddy-agent:jar:1.10.22:test (version managed from 1.10.20)
[DEBUG]          org.objenesis:objenesis:jar:3.2:test
[DEBUG]       org.mockito:mockito-junit-jupiter:jar:3.9.0:test (version managed from 3.9.0)
[DEBUG]       org.skyscreamer:jsonassert:jar:1.5.0:test (version managed from 1.5.0)
[DEBUG]          com.vaadin.external.google:android-json:jar:0.0.20131108.vaadin1:test
[DEBUG]       org.springframework:spring-core:jar:5.3.12:compile (version managed from 5.3.12)
[DEBUG]          org.springframework:spring-jcl:jar:5.3.12:compile (version managed from 5.3.12)
[DEBUG]       org.springframework:spring-test:jar:5.3.12:test (version managed from 5.3.12)
[DEBUG]       org.xmlunit:xmlunit-core:jar:2.8.3:test (version managed from 2.8.3)

  
**Additional context**
NA

**Information Checklist**
Kindly make sure that you have added all the following information above and checkoff the required fields otherwise we will treat the issuer as an incomplete report
- [X] Bug Description Added
- [X] Repro Steps Added
- [X] Setup information Added

**Comment by blacelle** [comment]
We encounter a similar issue, also affecting com.azure:azure-identity 1.3.6 vs 1.4.0.

It may relates to the fact `azure-spring-boot-bom 3.10.0` depends on com.azure:azure-sdk-bom:1.0.4 instead of 1.0.5 (https://mvnrepository.com/artifact/com.azure/azure-sdk-bom)

      
      <dependency>
        <groupId>com.azure</groupId>
        <artifactId>azure-sdk-bom</artifactId>
        <version>1.0.4</version>
        <type>pom</type>
        <scope>import</scope>
      </dependency>

**Comment by hongli750210** [comment]
@Shashi-rk The version of `azure-security-keyvault-secrets` included in `azure-spring-boot-bom:3.10.0` is confirmed to be `4.3.3`. I think the problem you are currently experiencing will be resolved in the next version `3.11.0`.

**Comment by Shashi-rk** [comment]
@hongli750210 Is there a place to check when new version will be available for GA.

**Comment by hongli750210** [comment]
@Shashi-rk This issue has been fixed, but I am not sure about the release plan of this fix. :)

**Comment by backwind1233** [comment]
@Shashi-rk please refer to the latest version [com.azure.spring:azure-spring-boot-bom:3.12.0](https://search.maven.org/artifact/com.azure.spring/azure-spring-boot-bom/3.12.0/pom) which has fixed the issue.
