### ISSUE TITLE
Investigate JDK 8 & JDK 17 Multi-Release Support

### ISSUE THREAD

**Issue by joshfree** [Azure/azure-sdk-for-java#25308]
Tracking issue for investigating if we can get multi-release Jars to work for Java 8 and Java 17 or if we need to create a second azure-core and ship two separate libraries.

This work item includes following up with JS and Python teams who have had to tackle similar ledges in technology in their ecosystems.

The end outcome of this work item is a spec / plan for how best to approach supporting both target platforms.

/cc @scottaddie

**Comment by JonathanGiles** [comment]
I believe this can be closed, pending any commentary from @alzimmermsft - as far as I know we are now actively creating multi-release jars and the hurdles have been jumped over (mostly, I know our IDE tooling isn't great, but that is beyond our control).

**Comment by alzimmermsft** [comment]
@joshfree correct me if I'm misinterpreting, but this appears to be more about whether we can use a multi-release JAR to support a potential Java 17 baseline need in the upcoming releases of Spring, Netty, and Reactor. Not about supporting multi-release JARs in general.

But yes, as @JonathanGiles mentioned we already have support for multi-release JARs.

**Comment by alzimmermsft** [comment]
Closing as this doesn't mention specifics and when requests are made we can do them ad hoc
