### ISSUE TITLE
Link to Java app insights sample lands on generic collection of code samples

### ISSUE THREAD

**Issue by jeffputz** [Azure/azure-sdk-for-java#25321]
Link to Java app insights sample lands on generic collection of code samples.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 90e5a9b1-ad6a-37cc-f21f-8fb021b506b7
* Version Independent ID: e4d3b889-4643-2ffa-6632-73ffbb599677
* Content: [Azure Application Insights libraries for Java](https://docs.microsoft.com/en-us/java/api/overview/azure/appinsights?view=azure-java-stable)
* Content Source: [docs-ref-services/latest/appinsights.md](https://github.com/Azure/azure-docs-sdk-java/blob/master/docs-ref-services/latest/appinsights.md)
* Service: **appinsights**
* Product: **azure**
* Technology: **azure**
* GitHub Login: @ramya-rao-a
* Microsoft Alias: **ramyar**

**Comment by pallavit** [comment]
Thank you for reporting the issue.

**Comment by trask** [comment]
thx! I have submitted https://github.com/Azure/azure-docs-sdk-java/pull/2140

**Comment by trask** [comment]
this has been resolved by https://github.com/Azure/azure-docs-sdk-java/pull/2158
