### ISSUE TITLE
this.inner().settings() throws Null Pointer Exception in version 1.1.4.

### ISSUE THREAD

**Issue by ImranBijapuri** [Azure/azure-sdk-for-java#2532]
this.inner().settings() this line throws an exception in VirtualMachineExtensionImpl::initializeSettings while trying to list the VirtualMachine Extensions.

**Comment by vhvb1989** [comment]
Hello @ImranBijapuri

I am sorry about you didn't get a sooner answer on this
Do you still need help? Let me know and I would be happy to assist.

Note: As part of repository cleaning effort, this issue will be closed by Sep 20 if no response is received from submitter and/or not further action is required.
