### ISSUE TITLE
Exception: CosmosDB table does not support truncate in batch mode

### ISSUE THREAD

**Issue by roenciso** [Azure/azure-sdk-for-java#25354]
I am trying to write a Spark DataFrame into a CosmosDB table using the 4.3.1 version of the azure-cosmos-spark connector. I am getting the exception below. Any thoughts on what could be wrong here?

AnalysisException: Table com.azure.cosmos.spark.items.****.*****.**** does not support truncate in batch mode.;

`writeConfig = {
  "spark.cosmos.accountEndpoint": cosmosEndpoint,
  "spark.cosmos.accountKey": cosmosdbkeyvalue,
  "spark.cosmos.database": CosmosDatabase,
  "spark.cosmos.container": CosmosCollectionSpark,
  "spark.cosmos.write.bulk.enabled": "true",
  "spark.cosmos.write.strategy": "ItemOverwrite"
}
(df
 .write
  .mode("overwrite")
  .format("cosmos.oltp")
  .options(**writeConfig)
  .save())`

**Comment by pallavit** [comment]
/cc: @kushagraThapar could you please help route this.

**Comment by kushagraThapar** [comment]
@moderakh  - please take a look at this.

**Comment by FabianMeiswinkel** [comment]
Truncate mode is not supported - only append.
df .write .mode("overwrite") needs to be change to df .write .mode("append") above.

**Comment by juandiegoreyesponce-tomtom** [comment]
Hi! Sorry I know this is closed, but I have a similar issue. What's the alternative for replacing items using cosmos.oltp connector?

**Comment by fabianema** [comment]
If it is not supported, why does it say do in the documentation? Maybe you should update it
