### ISSUE TITLE
[FEATURE REQ]

### ISSUE THREAD

**Issue by cormas07** [Azure/azure-sdk-for-java#25386]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Information Checklist**
Kindly make sure that you have added all the following information above and checkoff the required fields otherwise we will treat the issuer as an incomplete report
- [ ] Description Added
- [ ] Expected solution specified

**Comment by alzimmermsft** [comment]
Closing as this is an empty feature request issue
