### ISSUE TITLE
[FEATURE REQ] Please add getNetworkInterfaceAsync to VirtualMachineScaleSetVM

### ISSUE THREAD

**Issue by rupert-madden-abbott** [Azure/azure-sdk-for-java#25398]
**Is your feature request related to a problem? Please describe.**
`VirtualMachineScaleSetVM` has `getNetworkInterface` which internally calls `Mono.block`. We are using Reactor outside of the Azure SDK so calling this method within a Reactor thread throws an exception.

**Describe the solution you'd like**
Please add `getNetworkInterfaceAsync` to this interface.

**Describe alternatives you've considered**
At the moment, we have to call `listNetworkInterfacesAsync` and filter the returned list which is must less convenient.

**Comment by weidongxu-microsoft** [comment]
Next release will be 2.10.0, in one or two weeks.
