### ISSUE TITLE
[FEATURE REQ] Provide a compatibility verifier to help troubleshooting

### ISSUE THREAD

**Issue by stliu** [Azure/azure-sdk-for-java#25437]
Insipred by [this class](https://github.com/spring-cloud/spring-cloud-commons/blob/00668991a4cf3f40e137d6a13959a653e3f8e310/spring-cloud-commons/src/main/java/org/springframework/cloud/configuration/CompatibilityVerifierAutoConfiguration.java)  from [Spring Cloud Common](https://github.com/spring-cloud/spring-cloud-commons) project

Combine with the [FailureAnalyzer](https://github.com/spring-cloud/spring-cloud-commons/blob/00668991a4cf3f40e137d6a13959a653e3f8e310/spring-cloud-commons/src/main/java/org/springframework/cloud/configuration/CompatibilityNotMetFailureAnalyzer.java) it would help a lot

**Comment by saragluna** [comment]
Closed in #26627.
