### ISSUE TITLE
io.netty security issues

### ISSUE THREAD

**Issue by AlexGhiondea** [Azure/azure-sdk-for-java#25476]
### Discussed in https://github.com/Azure/azure-sdk-for-net/discussions/25216

<div type='discussions-op-text'>

<sup>Originally posted by **daesma** November  9, 2021</sup>
Hi,

We are seeing that dependencies like  io.netty:netty-handler 4.1.52.Final, and a bunch of other io.netty packages, are flagged for security issues. We also know that it's coming from azure dotnet package as dependencies, such as com.azure:azure-storage-file-share:jar:12.11.1. 
We'd really like to understand the roadmap for taking care of these issues and the recommendation for my team to remain secure in the meantime. </div>

**Comment by jsquire** [comment]
Transferring to the Java repository, as the dependencies and packages detailed are Java-related.   The link for the discussion thread comes up as a 404 so it's difficult to confirm context, but I believe the OP likely misspoke when they called out the "azure dotnet package"

**Comment by daesma** [comment]
I'm the OP. If I said that, yes - I misspone. This is definitely a Java related issue.

**Comment by srnagar** [comment]
@daesma There's a newer version of [azure-storage-file-share](https://mvnrepository.com/artifact/com.azure/azure-storage-file-share/12.11.2)(12.11.2) that uses `4.1.68.Final` version of io.netty libraries. Can you please try upgrading to this newer version?

**Comment by alzimmermsft** [comment]
Closing as much newer versions of Netty are being used in the latest versions of the SDKs
