### ISSUE TITLE
Implement DataLakeFileClient.uploadFromFileWithResponse

### ISSUE THREAD

**Issue by j0kkeri** [Azure/azure-sdk-for-java#25475]
**Is your feature request related to a problem? Please describe.**
There is no method that would return response when "uploadFromFile" and response provides valuable information.

**Describe the solution you'd like**
Implement a method named eg. uploadFromFileWithResponse, which would return response when uploading a file. Similar than the method for downloading a file with readToFileWithResponse OR BlobClient.uploadFromFileWithResponse

**Describe alternatives you've considered**
Alternative is to use uploadWithResponse but it requires manual InputStream handling.

**Comment by rickle-msft** [comment]
@j0kkeri Thank you for this feature request. I think this is a reasonable ask and we should be able to add it.
