### ISSUE TITLE
VM Hibernate operation using computemanager

### ISSUE THREAD

**Issue by pavanrachapudy** [Azure/azure-sdk-for-java#25497]
The new azure java sdk has support for VM Hibernate operation(Rest API PR - https://github.com/Azure/azure-rest-api-specs/pull/15067/files). We can initiate VM hibernate operation by calling Deallocate method with hibernate parameter as true. I have a question related to using compute manager. I see that when SDK is generated from rest api spec change, deallocate method doesn't have hibernate parameter(https://github.com/Azure/azure-sdk-for-java/blob/fcfd29647c8e0c16613b9e4c61355d8d0dd6b274/sdk/resourcemanager/azure-resourcemanager-compute/src/main/java/com/azure/resourcemanager/compute/models/VirtualMachines.java#L43).
ComputeManager manager = ComputeManager
    .authenticate(credential, profile);

But looks like computemanagement client has this code change - https://github.com/Azure/azure-sdk-for-java/blob/fcfd29647c8e0c16613b9e4c61355d8d0dd6b274/sdk/resourcemanager/azure-resourcemanager-compute/src/main/java/com/azure/resourcemanager/compute/fluent/VirtualMachinesClient.java#L876

Would like to know why this new parameter hibernate was not generated as part of computemanager for vm deallocate operation?

**Comment by weidongxu-microsoft** [comment]
enable in VM create
https://github.com/Azure/azure-rest-api-specs/blob/main/specification/compute/resource-manager/Microsoft.Compute/stable/2021-07-01/compute.json#L11042-L11045

**Comment by Prudvidhard** [comment]
@weidongxu-microsoft We are looking for hibernate support as well. please let us know when this fix will be available in the library.

**Comment by weidongxu-microsoft** [comment]
@Prudvidhard Latest version (2.10.0) should already having it.
Sample code
https://github.com/weidongxu-microsoft/azure-sdk-for-java/blob/caa4ac998f7467574ace6c94ded9f3a092333003/sdk/resourcemanager/azure-resourcemanager-compute/src/test/java/com/azure/resourcemanager/compute/VirtualMachineOperationsTests.java#L919-L960

Last time I tested, one need to request the feature preview.

**Comment by Prudvidhard** [comment]
@weidongxu-microsoft we are using com.microsoft.azure library - https://mvnrepository.com/artifact/com.microsoft.azure/azure
latest version 1.41.2 doesn't have the support. Isn't there a plan to add hibernate support in this library?

**Comment by weidongxu-microsoft** [comment]
@Prudvidhard
That SDK is here https://github.com/Azure/azure-libraries-for-java
And it is in maintenance mode, hence update will be rather sparse (more focus on bug fix instead of feature).

It is recommended to upgrade to this SDK https://aka.ms/azsdk/java/mgmt
Most code would remain same.

**Comment by Prudvidhard** [comment]
@weidongxu-microsoft we have plan for migrating to resource manager SDK but hibernate support is higher priority for us. Can you please let us know when hibernate support will be available in SDK at https://github.com/Azure/azure-libraries-for-java?

**Comment by weidongxu-microsoft** [comment]
@Prudvidhard

I will check internally, but I cannot give a schedule.

Quick question, do you need to use Java to create VM which have hibernation enabled?
```java
        VirtualMachine vm = computeManager.virtualMachines()
            .define(vmName)
            .withRegion("eastus2euap")
            .withNewResourceGroup(rgName)
            .withNewPrimaryNetwork("10.0.0.0/28")
            .withPrimaryPrivateIPAddressDynamic()
            .withoutPrimaryPublicIPAddress()
            .withPopularWindowsImage(KnownWindowsVirtualMachineImage.WINDOWS_SERVER_2019_DATACENTER)
            .withAdminUsername("Foo12")
            .withAdminPassword(password())
            .withSize(VirtualMachineSizeTypes.STANDARD_D2S_V3)
            .enableHibernation()
            .create();
```

Or you only need to use Java code to ask VM to go hybernate?
```java
        vm.deallocate(true);
```

**Comment by Prudvidhard** [comment]
@weidongxu-microsoft we use SDK to create the VM and hibernate it.
We cant ask VM to hibernate without enabling hibernation right, if this is the case we need both.

**Comment by weidongxu-microsoft** [comment]
@Prudvidhard 
Yes, correct. One had to enable it when creating the VM (the `hibernationEnabled` in PUT call).
https://github.com/Azure/azure-rest-api-specs/blob/main/specification/compute/resource-manager/Microsoft.Compute/stable/2021-07-01/compute.json#L11042-L11045

Asked because sending the one line `vm.deallocate` would be easier and may potentially done without updating the package. But creating would be much harder, and likely do require updating the package.

**Comment by Prudvidhard** [comment]
@weidongxu-microsoft got it. we need both enable hibernation and deallocate with hibernation.
