### ISSUE TITLE
[QUERY] Is ServiceBusReceiverClient is ThreadSafe and can be cache?

### ISSUE THREAD

**Issue by lours1** [Azure/azure-sdk-for-java#25502]
**Query/Question**
We use the lib azure-messaging-servicebus to send message to Service bus. 
This service is call by from a REST endpoint.
So, every time someone send a request, on our endpoint we send a message to the service bus.

We would like to know if we can cache the builder and or the client (sync, and async), to prevent creating on this two objects on each call.
The second question, if we can cache the client, is the object thread safe? 

Thank you

***Why is this not a Bug or a feature Request?***
Question about the implémentation from microsoft.

**Setup (please complete the following information if applicable):**
 - OS: WSL2, Linux, windows
 - IDE: IntelliJ
 - Library/Libraries: azure-messaging-servicebus:7.4.2

**Comment by pallavit** [comment]
/cc: @conniey can you please take a look.

**Comment by conniey** [comment]
You can cache the ServiceBusReceiverClient. It is a thin layer over our ServiceBusReceiverAsyncClient which AFAIK is thread-safe.

**Comment by joshfree** [comment]
Closing this old issue.
