### ISSUE TITLE
mgmt, VirtualMachineScaleSet support creating with orchestration mode

### ISSUE THREAD

**Issue by XiaofeiCao** [Azure/azure-sdk-for-java#25500]
**Is your feature request related to a problem? Please describe.**

support creating uniform and flexible vmss. Derived from https://github.com/Azure/azure-sdk-for-java/pull/25499

**Describe the solution you'd like**

Support full-fledged create and update methods on vmss instances with both uniform and flexible orchestration mode.
1. create flexible vmss with no vm profile
2. create flexible vmss with vm profile
2. attach a profile to existing vmss with no vm profile
3. update vm profile of existing flexible vmss

**Describe alternatives you've considered**

**Additional context**

**Information Checklist**
Kindly make sure that you have added all the following information above and checkoff the required fields otherwise we will treat the issuer as an incomplete report
- [ ] Description Added
- [ ] Expected solution specified

**Comment by XiaofeiCao** [comment]
Hi, @weidongxu-microsoft 
The problem to solve here is to provide an approach for the client to update their vmss with no profile. I've implemented this in createOrUpdate mode, which is quite straightforward.
However, when designing vmss update function interface, I’m finding myself adding a lot of extra methods to the update function. Similar to current create methods, it will look generally like this:
```java
vmss.update()
    .withSku(VirtualMachineScaleSetSkuTypes.STANDARD_A0) 
    .withExistingPrimaryNetworkSubnet(network, "subnet1")   // added in update stage
    .withPopularLinuxImage(KnownLinuxVirtualMachineImage.UBUNTU_SERVER_16_04_LTS) // added in update stage
    .withRootUsername("jvuser") // added in update stage
    .withSsh(sshPublicKey())  // added in update stage
    .withCapacity(1) //added in update stage
.apply();
```
This possibly involves minimum efforts to implement, since I just copy paste everything from create stage. However, these newly added methods are supposed to be only sensible for flexible vmss update, but through this approach, they are exposed to uniform vmss update as well, which does no actual harm but are useless and possibly lead to some confusion I think.

The next approach that comes to my mind is to provide some kind of a wrapper around the profile, like:
```java
vmss.update()
    .withSku(VirtualMachineScaleSetSkuTypes.STANDARD_A0) 
    .newFlexibleProfileBuilder() // profile wrapper start
        .withExistingPrimaryNetworkSubnet(network, "subnet1")   
        .withPopularLinuxImage(KnownLinuxVirtualMachineImage.UBUNTU_SERVER_16_04_LTS) 
        .withRootUsername("jvuser")
        .withSsh(sshPublicKey()) 
        .withCapacity(1)
    .build() // profile wrapper end
.apply();
```
This will expose update method only for the flexible profile.
And according to a document here: 
https://microsoft.sharepoint.com/:w:/r/teams/ComputeVM/_layouts/15/Doc.aspx?sourcedoc=%7B910299B8-B58B-404F-88F2-BD13DA86FDEB%7D&file=VMSS-Flex-ElasticityProfile.docx&action=default&mobileredirect=true&DefaultItemOpen=1&share=IQG4mQKRi7VPQIjyvRPahv3rAa82NO4HlgtxuUP6jWRe9c8
They will potentially `Support multiple elasticity profile (Virtual Machine profile) in VMSS Flex `.
I think this approach will probably need less effort to support this feature (or not, perhaps we need a totally separate `VirtualMachineScaleSetFlexible` interface in the future just for the VMSS Flex).
To implement this approach, I think we need a different stage apart from DefinitionStage and UpdateStage which we have now, like a VmssProfileStage, where all the vmssProfile properties are defined there.

Which of the two approaches do you think that I should take, or do you suggest a better solution? Thanks!

**Comment by weidongxu-microsoft** [comment]
The 2nd. Usually the control flow could start like this (I assume Sku is optional here)
```
vmss.update()
    .defineVirtualMachineProfile()
        .withExistingPrimaryNetworkSubnet...
        ...
        .attach()
   .apply()
```

For now, you probably can throw e.g. `IllegalStateException` if profile already exists at method `defineVirtualMachineProfile()`.

**Comment by XiaofeiCao** [comment]
It makes sense, thanks!
