### ISSUE TITLE
[FEATURE REQ] Reduce log generated by serviceBus

### ISSUE THREAD

**Issue by lours1** [Azure/azure-sdk-for-java#25505]
**Is your feature request related to a problem? Please describe.**
When we configure the log level of our application to INFO, we receive too much log

Sample log when we send a message
Sample Code

```java

    LOG.debug("Create builder");
    var builder = new ServiceBusClientBuilder()
        .connectionString(connectionString)
        .sender()
        .topicName("testwso2");

    LOG.debug("Create clientSender");
    var sender = builder
        .buildClient();

    var nbrMessage = 10;
    LOG.debug("Send {} Messages", nbrMessage);

    for (var i = 0; i < nbrMessage; i++) {
      var content = String.format("Message %s  date=%s", i, LocalDateTime.now());
      LOG.debug("Send message {}\t{}", i, content);

      var msg = new ServiceBusMessage(content);
      sender.sendMessage(msg);
    }

    LOG.debug("close");
    sender.close();
```

Log generated
Too big, to be be present here, I posted it on [pastbin](https://pastebin.com/73ihqrQt)

**Describe the solution you'd like**
Most of this log must be set to DEBUG

**Describe alternatives you've considered**
actually we can change ou config in logback to only log WARN for package  **com.azure.core.amqp** and **com.azure.messaging.servicebus** but it's not an efficient solution.

**Comment by conniey** [comment]
This is covered by #20836
