### ISSUE TITLE
[BUG] During auto-scaling up/down of multiple Eventhub Receivers. Some events could not be pulled from certain partitions.

### ISSUE THREAD

**Issue by PremSahooESL** [Azure/azure-sdk-for-java#25506]
**Describe the bug**
During auto-scaling up/down of multiple EventHub Receivers. Some events could not be pulled from certain partitions.
After rebooting Receivers, missing events could be pulled back properly.

1. Numbers of Receivers:
    Min : 1
    Max: 10

2. Total Number of EventHub Partitions: 30

***Exception or Stack Trace***
Add the exception log and stack trace if available

**To Reproduce**
May be on multiple receivers case with scaling up/down. It might occur.

***Code Snippet***
Currently used Maven Repository.
        compile group: 'com.microsoft.azure', name: 'azure-eventhubs', version: '3.1.1'

We are using EventProcessorHost . Below is the code which is used.
#############################
public EventProcessorHost createEventHubProcessorHost(ScheduledExecutorService scheduledExecutorService) {
        EventProcessorHost event = EventProcessorHost.EventProcessorHostBuilder
                .newBuilder(
                        EventProcessorHost.createHostName(azureProperties.getEventHubReceiver().getHostNamePrefix()),
                        azureProperties.getEventHubReceiver().getConsumerGroupName())
                .useAzureStorageCheckpointLeaseManager(azureProperties.getStorage().getConnectionString(),
                        azureProperties.getEventHubReceiver().getCheckpoint().getContainerName(), null)
                .useEventHubConnectionString(azureProperties.getEventHubReceiver().getConnectionString(),
                        azureProperties.getEventHubReceiver().getName())
                .setExecutor(scheduledExecutorService)
                .build();
        log.info("Event hub EventProcessorHost created");
        return event;
    }
#############################

**Expected behavior**
1. Run one Receiver
2. Add more receivers
3. After sometime, stop newly added receivers and  let the first receiver continue running.
4. Now expectation is all 30 partitioned should be assigned back to first receiver.

**Screenshots**

**Setup (please complete the following information):**
 - OS: [azul/zulu-openjdk:8]
 - IDE: [Running on Docker]
 - Library/Libraries: [compile group: 'com.microsoft.azure', name: 'azure-eventhubs', version: '3.1.1']
 - Java version: [openjdk: 8] 
 - App Server/Environment: [Docker, AKS]
 - Frameworks: [Spring Boot 2.4.2] 

If you suspect a dependency version mismatch (e.g. you see `NoClassDefFoundError`, `NoSuchMethodError` or similar), please provide
- verbose dependency tree (`mvn dependency:tree -Dverbose`)
  
**Additional context**

**Information Checklist**
Kindly make sure that you have added all the following information above and checkoff the required fields otherwise we will treat the issuer as an incomplete report
- [ ] Bug Description Added
- [ ] Repro Steps Added
- [ ] Setup information Added

**Comment by pallavit** [comment]
/cc: @conniey , @anuchandy could you please take a look.

**Comment by conniey** [comment]
@JamesBirdsall Can you take a look at this please? Thanks!
