### ISSUE TITLE
[BUG]'com.azure.messaging.servicebus.implementation.ServiceBusConnectionProcessor','message':'namespace[amqps] entityPath[N/A]: Cannot subscribe. Processor is already terminated.'

### ISSUE THREAD

**Issue by KavyaROHINIKUMAR** [Azure/azure-sdk-for-java#25504]
**Issue description**
My customer is using azure-messaging-servicebus library version: 7.4.2 SDK .
He is trying to receive messages from service bus to AKS pods. He is getting the below exception every time.

: 'instant':{'epochSecond':1636968595,'nanoOfSecond':598000000},'thread':'parallel-1','level':'ERROR','loggerName':'com.azure.messaging.servicebus.implementation.ServiceBusConnectionProcessor','message':'namespace[amqps] entityPath[N/A]: Cannot subscribe. Processor is already terminated.','endOfBatch':false,'loggerFqcn':'org.apache.logging.slf4j.Log4jLogger','contextMap':{'dd.env':'dit-eastus2','dd.service':'ap139346-sps-grk-statement','dd.version':'0.2.184'},'threadId':23,'threadPriority':5,'timestamp':'11/15/21 04:29:55:598','applicationName':'GRK-STATEMENT-APP'}

**Code snippet that customer is using:**

import org.springframework.beans.factory.annotation.Value;
import org.springframework.core.NestedRuntimeException;

import com.azure.core.amqp.AmqpRetryOptions;
import com.azure.core.amqp.AmqpTransportType;
import com.azure.messaging.servicebus.ServiceBusClientBuilder;
import com.azure.messaging.servicebus.ServiceBusErrorContext;
import com.azure.messaging.servicebus.ServiceBusException;
import com.azure.messaging.servicebus.ServiceBusFailureReason;
import com.azure.messaging.servicebus.ServiceBusMessage;
import com.azure.messaging.servicebus.ServiceBusProcessorClient;
import com.azure.messaging.servicebus.ServiceBusReceivedMessage;
import com.azure.messaging.servicebus.ServiceBusReceivedMessageContext;
import com.azure.messaging.servicebus.ServiceBusSenderClient;
import com.azure.messaging.servicebus.models.ServiceBusReceiveMode;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

public class SampleAsbMessageListener implements AutoCloseable {
	
	/** The Constant log. */
	private static final Logger log = LoggerFactory.getLogger(SampleAsbMessageListener.class);
	
	@Value("${max.auto.lock.renewal.duration.minutes}")
	private int MAX_AUTO_LOCK_RENEW_DURATION;
    
    @Value("${jmsbroker.maxConcurrentConsumers}")
	private int NUMBER_OF_MESSAGE_TO_CONSUME;
	
	@Value("${announcementTopicName:test-topic}")
	private String announcementTopicName;
    
	@Value("${announcementSubName:test-subscription}")
    private String announcementSubName;
    
	@Value("${asbUserName:test-user}")
    private String asbUserName;
    
	@Value("${asbPassword:test-passwd}")
    private String asbPassword;
	
	private ServiceBusProcessorClient processorClient;
	
	@PostConstruct
	public void onInit() throws ServiceBusException, InterruptedException {
		try {
			registerMessageHandler();
		} catch (Exception e) {
    		log.error("Exception wile establishing sender connection: ", e);   
    	}	
	}
	
	/**
	*/
	public void registerMessageHandler() throws InterruptedException, ServiceBusException {
    	try {
    		String connectionString = "Endpoint=sb://" + connectionUrl + "/;SharedAccessKeyName=" + asbUserName
        			+ ";SharedAccessKey=" + asbPassword;	
        	log.information("initialisation {}: Inside registerMessageHandler: ", configName,
    				this.getClass().getName());	
        	 processorClient = new ServiceBusClientBuilder()
				.connectionString(connectionString)
				.processor()
				.topicName(announcementTopicName)
				.subscriptionName(announcementSubName)
				.disableAutoComplete()
				.processMessage(context -> onMessage(context))         
				.processError(context -> processError(context))                    
				.prefetchCount(1)		                 
				.receiveMode(ServiceBusReceiveMode.PEEK_LOCK)	                    
				.maxAutoLockRenewDuration(Duration.ofMinutes(MAX_AUTO_LOCK_RENEW_DURATION))
				.buildProcessorClient();
    		processorClient.start();	
    	} catch(Exception e) {
    		log.error("Exception wile establishing connection: ", e);   
    	}		
    }
	
	/**
	*/
	private void onMessage(ServiceBusReceivedMessageContext context) {
		ServiceBusReceivedMessage  message = context.getMessage();	
    	try {	  	                		                		                		
    		long currentAttemptCount = message.getDeliveryCount();                    
            String jsonMessage = message.getBody().toString().replaceAll(R_N_R, "");	       
            log.information("Event coreelation id : {} ","Message Delivery count is : "
            		, message.getCorrelationId(), currentAttemptCount);			            	        			
			context.complete();
		} catch(RuntimeException e) {
        	log.error("Runtime exception occurred: ", e);   
        	throw new NestedRuntimeException(e);
        }
	}
	
	/**
	*/
	private static void processError(ServiceBusErrorContext context) {
    	log.information("Error when receiving messages from namespace: {} . Entity: {}",
				context.getFullyQualifiedNamespace(), context.getEntityPath());

		if (!(context.getException() instanceof ServiceBusException)) {
			log.error("Non-ServiceBusException occurred: ", context.getException().getMessage());
			return;
		}

		ServiceBusException exception = (ServiceBusException) context.getException();
		ServiceBusFailureReason reason = exception.getReason();

		if (reason == ServiceBusFailureReason.MESSAGING_ENTITY_DISABLED
				|| reason == ServiceBusFailureReason.MESSAGING_ENTITY_NOT_FOUND
				|| reason == ServiceBusFailureReason.UNAUTHORIZED) {
			log.error("An unrecoverable error occurred. Stopping processing with reason : ",
					exception.getMessage());

			//countdownLatch.countDown();
		} else if (reason == ServiceBusFailureReason.MESSAGE_LOCK_LOST) {
			log.error("Message lock lost for message: ", context.getException().getMessage());
		} else if (reason == ServiceBusFailureReason.SERVICE_BUSY) {
			try {			
				TimeUnit.SECONDS.sleep(1);
			} catch (InterruptedException e) {
				log.warning("Unable to sleep for period of time","");
			}
		} else {
			log.information("Error source {}, reason {}, message: {}", context.getErrorSource().toString(), reason,
					context.getException());
		}
	}

	@Override
	public void close() throws Exception {
		if(processorClient != null && processorClient.isRunning()) { 
			processorClient.close(); 
		}
	}
}

**Expected behavior**
Should be able to consume messages to the consumer within AKS pods.
Customer has raised Microsoft Support ticket 2111160040002500. We would require your help in the code and SDK end.

**Comment by pallavit** [comment]
/cc: @conniey  can you please take a look.

**Comment by KavyaROHINIKUMAR** [comment]
Can someone please help! this requires immediate attention !

**Comment by conniey** [comment]
Hey, can you enable logging for the client library? The exception itself does not provide enough information to understand why it is closed.

To enable logging:
1. set environment variable AZURE_LOG_LEVEL=1

By default, it uses whatever slf4j logger is on the classpath.

**Comment by ki1729** [comment]
@conniey : They opened an IcM ticket for this issue last week, handled the issue there. Closing this issue out as the customer is now unblocked

**Comment by KavyaROHINIKUMAR** [comment]
I got the response from the customer saying issue is resolved by changing the transitive dependency for project reactor and changing the version of “reactor-core” to v 3.4.11.
