### ISSUE TITLE
[FEATURE REQ] Ambiguous mapping between KeyVault secrets and Spring Boot existing properties containing both dots and dashes

### ISSUE THREAD

**Issue by dangub86** [Azure/azure-sdk-for-java#25512]
**Context and issue**
I've found a closed issue related to this one at [Issue #887](https://github.com/microsoft/azure-spring-boot/issues/887).
Working in a Spring Boot application with SSL configuration properties such as *server.ssl.key-store-password* i've encountered some problems with mapping of these props (whose name is established by Spring Boot context itself) to Azure KeyVault secrets.

Looking at the code i saw that the replacement logic converts *server.ssl.key-store-password* into *server-ssl-keystorepassword*. 
Everything seems to work fine, in fact, by saving the KeyVault secret using the latter syntax.

**Possible solution**
I'm wondering if the replacement logic could be changed so as not to remove the dashes. Doing so we would have both *server.ssl.key-store-password* and *server.ssl.key.store.password* would map into *server-ssl-key-store-password* on the Azure KeyVault assuming there should be no reason in the context of a Spring Boot app to have both these two properties set (which would obviously cause problems when retrieving them from Azure KeyVault).

**As alternative adding documentation**
If the clashing of the two example properties into the same KeyVault secret should create problems in other contexts, as alternative it might still be useful to specify the actual replacement logic in the documentation. If i didn't miss it, i've found only the explanation about the dots replacement here in the [Azure Sdk For Java Readme file](https://github.com/Azure/azure-sdk-for-java/blob/main/sdk/spring/azure-spring-boot-starter-keyvault-secrets/README.md#handle-special-property-name).

**Comment by pallavit** [comment]
@stliu could you please help route this issue.

**Comment by chenrujun** [comment]
Hi, @dangub86.
Thanks for reaching out. We will investigate this.

**Comment by dangub86** [comment]
Hi @chenrujun.
It would be my first contribution but it would be a pleasure to be able to contribute actively if needed.

**Comment by chenrujun** [comment]
@dangub86

Thank you so much.

And any idea / Pull request is welcome.

If you want to contribute by PR, please target to [azure-spring-cloud-4.0](https://github.com/Azure/azure-sdk-for-java/tree/feature/azure-spring-cloud-4.0/sdk/spring/spring-cloud-azure-autoconfigure/src/main/java/com/azure/spring/cloud/autoconfigure/keyvault) branch.

**Comment by chenrujun** [comment]
Hi, @dangub86. Now key with both dot and dash is not supported. Please use please holder to handle this requirement.

Step 1: Use place holder in you application.properties

> server.ssl.key-store-password = ${server-ssl-key-store-password}

Step 2: Store `server-ssl-key-store-password` in Key Vault.

You can get more information in the reference doc: https://microsoft.github.io/spring-cloud-azure/4.0.0-beta.3/4.0.0-beta.3/reference/html/index.html#special-characters-in-property-name
