### ISSUE TITLE
[BUG]Fix Java Aggreagte Prport

### ISSUE THREAD

**Issue by chidozieononiwu** [Azure/azure-sdk-for-java#25520]
[java - aggregate-reports](https://dev.azure.com/azure-sdk/internal/_build?definitionId=1359) has been failing for a while. It needs to be fixed.
We should also retire the [UI release pipeline](https://dev.azure.com/azure-sdk/internal/_release?view=all&_a=releases&definitionId=20) and replace it with a simple yaml step like we do in the [aggreagte reports pipeline of other languages.](https://github.com/Azure/azure-sdk-for-python/blob/a1fa5eb80ebcf6206e11776904404389939c3ee1/eng/pipelines/aggregate-reports.yml#L29)

**Comment by alzimmermsft** [comment]
@srnagar assigning to you as you've been looking into this already.

**Comment by srnagar** [comment]
Resolving as we have aggregate reports running successfully.
Latest run - https://dev.azure.com/azure-sdk/internal/_build/results?buildId=1746193&view=results
