### ISSUE TITLE
[QUERY] missing ManagementGroups API

### ISSUE THREAD

**Issue by Fabio1988** [Azure/azure-sdk-for-java#25542]
**Query/Question**
Tried to list all management-groups within tenant, but I think it's not possible with this SDK?!
https://docs.microsoft.com/en-us/rest/api/managementgroups/management-groups/list

***Why is this not a Bug or a feature Request?***
Don't know if I'm right, that this is missing. Haven't found a package, only [azure-sdk-for-net](https://github.com/Azure/azure-sdk-for-net/tree/main/sdk/managementgroups/Microsoft.Azure.Management.ManagementGroups) does support it.

**Setup (please complete the following information if applicable):**
 - OS: Ubuntu
 - IDE: IntelliJ
 - Library/Libraries: com.azure:azure-core:1.22.0; com.azure: com.azure.resourcemanager:azure-resourcemanager:2.9.0
 
 **Information Checklist**
 Kindly make sure that you have added all the following information above and checkoff the required fields otherwise we will treat the issuer as an incomplete report
- [x] Query Added
- [x] Setup information Added

**Comment by pallavit** [comment]
Thank you for reporting the issue. @weidongxu-microsoft could you please help route this.

**Comment by weidongxu-microsoft** [comment]
The spec is on https://github.com/Azure/azure-rest-api-specs/tree/main/specification/managementgroups/resource-manager

However this PR appear not requested for Java package. Will check with them.

**Comment by weidongxu-microsoft** [comment]
@Fabio1988 
Service team has Java SDK in roadmap and backlog. We won't be able to release anything without their approval.

I've generated the source code in this [draft PR](https://github.com/Azure/azure-sdk-for-java/pull/25667). Hope it may help you. Again we cannot release anything without service approval.

**Comment by weidongxu-microsoft** [comment]
OK, we got multiple requests for the SDK. I think this be enough reason for us to release a beta.

Here it is
https://central.sonatype.com/artifact/com.azure.resourcemanager/azure-resourcemanager-managementgroups/1.0.0-beta.1
