### ISSUE TITLE
[BUG][azure-data-table]v12 table client builder behaves differently than queue and blob and throws unhelpful error

### ISSUE THREAD

**Issue by ohadbitt** [Azure/azure-sdk-for-java#25565]
**Describe the bug**
Table client builder behaves differently then queue and blob, if I use a SAS i cant just put it all in the endpoint - it throws exception saying i have to use tableName() and sasToken() - which then threw RequestFailedException 501 exception : "code":"NotImplemented"

parts = splitToTableUrlParts("https://storage.table.core.windows.net/tableName?sas")
 new TableClientBuilder().endpoint(parts [0]))
                .tableName(parts [1])
                .sasToken(parts[2])
 
Took some time to realize I need to remove table name from the endpoint as it basically put tableName twice on the URL and the exception is not helpful

whilst in blob client endpoint takes the name by itself - this works:
 new BlobClientBuilder().endpoint(url)

and in queue and container i need to put endpoint+sas (no need queueName or containerName but i do have to get the sas myself from url)

**Comment by alzimmermsft** [comment]
@vcolin7 could you take a look at this?
