### ISSUE TITLE
[FEATURE REQ] Configurable Security Provider in CryptographyClient

### ISSUE THREAD

**Issue by pentiak** [Azure/azure-sdk-for-java#25570]
`CryptographyAsyncClient` used in **Sign** operation on a EC keys tries to initialize `EcKeyCryptographyClient` by using **SunEC** Security provider to convert JsonWebKey to JRE's KeyPair. Unfortunately, starting from Java 15, EC curve **secp256k1** is no longer supported by this provider: https://www.oracle.com/java/technologies/javase/15-relnote-issues.html#JDK-8237219
This results in an exception while invoking sign method: 
`java.security.InvalidAlgorithmParameterException: Unsupported curve: secp256k1 (1.3.132.0.10)`

It would be great if EcKeyCryptographyClient could be parametrized with Security Provider (like BouncyCastle) or the `JsonWebKey` which ultimately does the conversion could iterate over and try all available providers instead using a single one.

Although there is a workaround for this issue in JRE 15 - one can set system property `-Djdk.sunec.disableNative=false` it's not very elegant. Having possibility to choose the provider would be preferable.

**Comment by vcolin7** [comment]
Hi @pentiak, thank you for reporting this issue, I will bring this up with the team and provide an update as soon as I can :)

**Comment by hhanquez** [comment]
any news ?
