### ISSUE TITLE
Upgrade spring boot to 2.6.1

### ISSUE THREAD

**Issue by chenrujun** [Azure/azure-sdk-for-java#25581]
Copied from here: https://github.com/Azure/azure-sdk-for-java/wiki/Spring-Cloud-Azure-tasks-for-a-new-Spring-Boot-release

Spring boot released [spring-boot v2.6.1]. we need do the following tasks.

# Task list
- Before azure-sdk-for-java in band release
  - [x] #25697
    - [x] #25755
    - [x] #25797
- After azure-sdk-for-java in band release.
  - [x] #25698
  - [x] #25699
  - [x] #25700

Since we can't finish these tasks in this month, so I assign this issue to @yiliuTo  instead of @saragluna .

[spring-boot v2.6.1]: https://github.com/spring-projects/spring-boot/releases/tag/v2.6.0
[azure-sdk-for-java#24291]: https://github.com/Azure/azure-sdk-for-java/issues/24291
[azure-spring-boot-samples#62]: https://github.com/Azure-Samples/azure-spring-boot-samples/pull/62
[MS docs about spring framework]: https://docs.microsoft.com/en-us/azure/developer/java/spring-framework/

**Comment by chenrujun** [comment]
Hi, @Netyyyy .

Could you please check the remaining 2 issues? If there is nothing to do, please close the 2 sub issues.

**Comment by Netyyyy** [comment]
Version support of azure-spring-boot-samples is working on the new issue:https://github.com/Azure-Samples/azure-spring-boot-samples/issues/42
