### ISSUE TITLE
[BUG] Invalid message order in batch sending

### ISSUE THREAD

**Issue by grzegorzkalisz** [Azure/azure-sdk-for-java#25599]
After upgrading azure-messaging-servicebus lib from 7.0.1 to 7.3.0, I noticed that batch sending is reordering messages in Service Bus. I suppose this is due to the use of parallelStream() in the ServiceBusMessageBatch.sendInternal() method. This has been changed in the commit: https://github.com/Azure/azure-sdk-for-java/commit/a9b28ec39515b1aa112d6ef211cac2455d729afa#diff-bfbb3d6ac91c080eaa27ee29c12058246337099dcd205dc86a625dee08bfa17e.
I expect the order of the messages in the list for batch should be the same as in Service Bus.

**Comment by alzimmermsft** [comment]
@ki1729 could you take a look into this?

**Comment by ki1729** [comment]
@grzegorzkalisz Changes are merged, and should be part of the March release

**Comment by grzegorzkalisz** [comment]
> @grzegorzkalisz Changes are merged, and should be part of the March release

Thanks for your support!
