### ISSUE TITLE
com.azure.storage.blob.specialized.BlobAsyncClientBase#getBlobUrl does NOT encode hardcoded slashes

### ISSUE THREAD

**Issue by dnkcz** [Azure/azure-sdk-for-java#25602]
String blobUrl = azureBlobStorage.getUrl() + "/" + containerName + "/" + Utility.urlEncode(blobName);
does NOT encode hardcoded slashes in blobUrl.
Returned url is not usable...

![image](https://user-images.githubusercontent.com/33804832/142903461-a6cbf365-caa2-4639-97ca-fe3b76d0a371.png)

**Comment by rickle-msft** [comment]
@dnkcz Thank you for opening this issue. Can you please describe what you mean by "is not usable"? This is still considered a valid URL and will work with requests against the service. I can double check this, but I believe the service interprets '/' and '%2F' the same, so it will still work with listing as well

**Comment by amishra-dev** [comment]
let us know if you are still blocked due to this.

**Comment by dnkcz** [comment]
Hi we had problem with deleting blob storage, but it is working now. It needed some specific part of blob name to be encoded if i remember it right.
