### ISSUE TITLE
Design  Metrics API

### ISSUE THREAD

**Issue by lmolkova** [Azure/azure-sdk-for-java#25603]
Design metrics API to support metrics reporting from SDKs:
- Azure Spring Cloud team wants to offer experience similar to Kafka metrics in Spring Boot
- We can help customers detect, alert and maybe even diagnose AMQP connection and state management issues using metrics

this task tracks Metrics API abstraction in azure-core. Abstraction should be implementable with OpenTelemtery metrics API and potentially with Micrometer

**Comment by stliu** [comment]
@lmolkova  thanks for driving this, appreciates it. And would like to get involved into the design review, thanks.

@saragluna @yiliuTo FYI
