### ISSUE TITLE
[BUG] azure-spring-data-cosmos - CosmosRepository's abstract method with @Query and IN clause is giving wrong results

### ISSUE THREAD

**Issue by sachinadiga** [Azure/azure-sdk-for-java#25628]
**Describe the bug**
When we use @Query with CosmosRepository's abstract method and use IN clause, list of ids are being considered as single parameter and querying the whole list in the documents.

***Exception or Stack Trace***
No exception is being thrown. Wrong results

**To Reproduce**
Create an abstract method in Repository with @Query("select * from c where c.first_name IN (@firstNames)").

***Code Snippet***
`    @Query("select * from c where c.first_name IN (@firstNames)")
    List<User> findByFirstNamesIn(List<String> firstNames);`

**Expected behavior**
Say, we have below documents in cosmos container, 
1.  {
        "id": "20de6ac8-5b89-4404-b273-f497c8ccc7b1",
        "first_name": "John",
        "last_name": "Cena",
     }
2.  {
        "id": "20de6ac8-5b89-4404-b273-f497c8cbc7b1",
        "first_name": "Mark",
        "last_name": "Henry",
    }

If below repository method is defined and arguments ["John","Mark"] are passed, 
`    @Query("select * from c where c.first_name IN (@firstNames)")
    List<User> findByFirstNamesIn(List<String> firstNames);`

Then result should include both the documents, but currently none are coming because a single document is not having first_name with value as ["John","Mark"]. 

**Screenshots**
NA

**Setup (please complete the following information):**
 - OS: MacOS
 - IDE: IntelliJ
 - Library/Libraries: [com.azure:azure-spring-data-cosmos:3.14.0, com.azure:azure-cosmos:4.21.0]
 - Java version: [8] 
 - App Server/Environment: [Embedded Tomcat]
 - Frameworks: [Spring Boot] 
  
**Additional context**

**Information Checklist**
Kindly make sure that you have added all the following information above and checkoff the required fields otherwise we will treat the issuer as an incomplete report
- [x] Bug Description Added
- [x] Repro Steps Added
- [x] Setup information Added

**Comment by sachinadiga** [comment]
@kushagraThapar can you please help here?

**Comment by sachinadiga** [comment]
``The native query generated by spring data will look like below for @Query with IN clause, 
`{"query":"select * from c where c.first_name IN (@firstNames)","parameters":[{"name":"@firstNames","value":["John","Mark"]}]}`
And this native query will look for a single document having both of these names or in other words document having exactly this list. 
Example, below document will get matched for above query,
`{
    "id": "9765417819",
    "first_name": [
        "John",
        "Mark"
    ],
    "last_name": "abc"
}`

**Comment by hongli750210** [comment]
@sachinadiga
If you are using Spring Data JPA, I think there is a problem with the parameter settings in your Sql text. 
You can try the following corrections: 
`@Query("select * from c where c.first_name IN ?1") List<User> findByFirstNamesIn(List<String> firstNames);`
For more information, please refer to [jpa docs](https://docs.spring.io/spring-data/jpa/docs/current/reference/html/#jpa.query-methods.query-creation)

**Comment by sachinadiga** [comment]
@hongli750210 , I'm using com.azure:azure-spring-data-cosmos:3.14.0
I tried above way as well. Native cosmos query which spring data generating is again wrong and hence getting syntax error , incorrect syntax near '?' from cosmos DB. 
`{"query":"select * from c where c.first_name in **?1**","parameters":[{"name":"**@firstNames**","value":["Sachin"]}]}`

**Comment by sachinadiga** [comment]
@hongli750210 @kushagraThapar , to be specific - I'm using & talking about your (spring data cosmos @Query)  https://docs.microsoft.com/en-us/azure/cosmos-db/sql/sql-api-spring-data-sdk-samples#custom-query-examples
and not about spring data jpa @Query.

**Comment by tanuj180996** [comment]
@hongli750210 , When we use @Query annotation given by spring-data-jpa , then application is not considering that annotation means adding that or not does'nt make any difference ,,,,,,,,, Here problem is when we pass a List of string for IN condition ,, then our expactations is it should look each data in list individually ,,, but in realty it is looking the whole list in single document

**Comment by tanuj180996** [comment]
@hongli750210 @kushagraThapar , 

Sample Data -> 
```

 User {
	"id": 1,
	"name": "ABC",
	"age":22

},
{
	"id": 2,
	"name": "ABC",
	"age":23

}

```
Now let me tell our expactions when we pass iDs -> [1,2], then we are expecting it should return both the object ,,, but it returning nothing


By our observation what we find ,, when we search for [1,2] then it is looking document which contain id as [1,2]

If you need more explaination please let us know

This is how we are writing query;;
`@Query("select * from c where c.id IN @Id") List<User> findByIds(List<String> id);
`

**Note:: if you think our query is not according to our expactations then please suggest other way.**

**Comment by kushagraThapar** [comment]
@tanuj180996 @sachinadiga - I tested locally and this is a bug in spring data cosmos SDK. However, there is a workaround for this. Instead of using query annotation, you can simply use the JPA queries to work it out. 

For example, this query can be converted into JPA query easily - 

`@Query("select * from c where c.id IN @Id") List<User> findByIds(List<String> id);` - this doesn't work.
`List<User> findByIds(List<String> id);` - this works.

Any specific reason you are using IN clause with query annotation and not directly with JPA query structure?

**Comment by sachinadiga** [comment]
@kushagraThapar yeah, so the reason for using explicit @Query being, as per the standard practice in DB we have snake case field names and in the java code we are keeping field names and method names in camel case. Now since there is no field naming strategy implemented in spring-data-cosmos, providing explicit query through @Query is the only better option we found.

**Comment by sachinadiga** [comment]
@kushagraThapar, anyways we found a workaround to use it with @Query. So instead of IN clause, if we use ARRAY_CONTAINS in cosmos query, the behaviour is as expected even when executed through spring data cosmos. So we are good now. 
Thanks for your support.

**Comment by kushagraThapar** [comment]
@sachinadiga - thanks for the update, can you please share your ARRAY_CONTAINS solution / workaround here in some code sample form, so that other users can take benefit from it. 

I would also like to keep this issue open, so that we can track the actual bug. Thanks again!

**Comment by sachinadiga** [comment]
Sure @kushagraThapar. 

Cosmos natively has a function called ARRAY_CONTAINS ([documentation here ](https://docs.microsoft.com/en-us/azure/cosmos-db/sql/sql-query-array-contains)) with which above issue can be overcome.

Here is the working solution / workaround for the above issue corresponding to mentioned IN clause query.

_IN clause query:_
`@Query("select * from c where c.first_name IN (@firstNames)") 
  List<User> findByFirstNamesIn(List<String> firstNames);`

_Corresponding query using ARRAY_CONTAINS cosmos function:_
`@Query("select * from c where ARRAY_CONTAINS(@firstNames,c.first_name)") 
  List<User> findByFirstNamesIn(List<String> firstNames);`
 
Thanks.

**Comment by kushagraThapar** [comment]
@sachinadiga - thank you for sharing this.
