### ISSUE TITLE
Resolve Missing Javadocs in SDKs

### ISSUE THREAD

**Issue by alzimmermsft** [Azure/azure-sdk-for-java#25632]
This issue is a tracking issue for resolving missing Javadocs in SDKs. Upon the completion of this issue the codesnippet4javadoc Doclet will be replace with the Standard Doclet.

To verify that a library is compatible with the Standard Doclet the following configurations will need to be added into the POM (if the properties section already exists only add the property values):

```xml
<properties>
    <codesnippet.skip>false</codesnippet.skip>
    <javadocDoclet></javadocDoclet>
    <javadocDocletOptions></javadocDocletOptions>
</properties>
```

Additionally, the build should preferably happen on Java 17 to ensure it works with the latest LTS Doclet tooling.

If any code generation classes are missing Javadocs please file an issue.

When you take an SDKs please leave a comment with which SDKs you'll be fixing or verifying.

The following are SDKs that need to be verified or fixed:

_Anything checked off without a name next to it has been completed_

- [x] azure-ai-anomalydetector
- [x]  azure-ai-documenttranslator
- [X] azure-analytics-purview-administration
- [X] azure-analytics-purview-catalog
- [X] azure-analytics-purview-scanning
- [X] azure-analytics-synapse-accesscontrol (@g2vinay to-do)
- [X] azure-analytics-synapse-artifacts (@g2vinay to-do)
- [X] azure-analytics-synapse-managedprivateendpoints  (@g2vinay to-do)
- [X] azure-analytics-synapse-monitoring (@g2vinay to-do)
- [X] azure-analytics-synapse-spark (@g2vinay to-do)
- [x] azure-containers-containerregistry-perf
- [x] azure-data-appconfiguration-perf 
- [x] azure-iot-deviceupdate
- [x] azure-iot-modelsrepository
- [x] azure-media-videoanalyzer-edge
- [X] azure-messaging-eventhubs-track1-perf
- [X] azure-messaging-eventhubs-track2-perf
- [X] azure-messaging-servicebus-track1-perf
- [X] azure-messaging-servicebus-track2-perf
- [x] azure-mixedreality-authentication
- [x] azure-mixedreality-remoterendering
- [x] azure-quantum-jobs
- [x] https://github.com/Azure/azure-sdk-for-java/issues/25634
- [ ] https://github.com/Azure/azure-sdk-for-java/issues/25635
- [x] azure-search-perf
- [x] azure-security-confidentialledger
- [x] azure-template-perf
- [X] azure-verticals-agrifood-farming
- [X] microsoft-azure-storage-perf
- [X] perf-test-core (@g2vinay to-do)

**Comment by weidongxu-microsoft** [comment]
Add one for Azure Stack https://github.com/Azure/azure-sdk-for-java/issues/25665

**Comment by alzimmermsft** [comment]
Closing this issue as there are specific issues tracking the areas that still need this to be resolved
