### ISSUE TITLE
Resolve Missing Javadocs in Resource Manager SDKs

### ISSUE THREAD

**Issue by alzimmermsft** [Azure/azure-sdk-for-java#25634]
This issue is a tracking issue for resolving missing Javadocs in `resourcemanager` SDKs and is being tracked by #25632.

To verify that a library is compatible with the Standard Doclet the following configurations will need to be added into the POM (if the properties section already exists only add the property values):

```xml
<properties>
    <codesnippet.skip>false</codesnippet.skip>
    <javadocDoclet></javadocDoclet>
    <javadocDocletOptions></javadocDocletOptions>
</properties>
```

Additionally, the build should preferably happen on Java 17 to ensure it works with the latest LTS Doclet tooling.

If any code generation classes are missing Javadocs please file an issue.

When you take an SDKs please leave a comment with which SDKs you'll be fixing or verifying.

The following are SDKs that need to be verified or fixed:

- [ ] azure-resourcemanager
- [x] azure-resourcemanager-advisor
- [x] azure-resourcemanager-apimanagement
- [x] azure-resourcemanager-appconfiguration
- [x] azure-resourcemanager-applicationinsights
- [ ] azure-resourcemanager-appplatform
- [x] azure-resourcemanager-automation
- [x] azure-resourcemanager-azurearcdata
- [x] azure-resourcemanager-azurestack
- [x] azure-resourcemanager-azurestackhci
- [x] azure-resourcemanager-baremetalinfrastructure
- [x] azure-resourcemanager-batch
- [x] azure-resourcemanager-batchai
- [x] azure-resourcemanager-billing
- [x] azure-resourcemanager-botservice
- [ ] azure-resourcemanager-cdn
- [x] azure-resourcemanager-changeanalysis
- [x] azure-resourcemanager-commerce
- [x] azure-resourcemanager-consumption
- [ ] azure-resourcemanager-containerservice
- [ ] azure-resourcemanager-cosmos
- [x] azure-resourcemanager-costmanagement
- [x] azure-resourcemanager-customerinsights
- [x] azure-resourcemanager-databox
- [x] azure-resourcemanager-databoxedge
- [x] azure-resourcemanager-databricks
- [x] azure-resourcemanager-datadog
- [x] azure-resourcemanager-datalakeanalytics
- [x] azure-resourcemanager-datalakestore
- [x] azure-resourcemanager-datamigration
- [x] azure-resourcemanager-delegatednetwork
- [x] azure-resourcemanager-deploymentmanager
- [x] azure-resourcemanager-deviceprovisioningservices
- [x] azure-resourcemanager-devspaces
- [x] azure-resourcemanager-devtestlabs
- [ ] azure-resourcemanager-dns
- [x] azure-resourcemanager-elastic
- [ ] azure-resourcemanager-eventhubs
- [x] azure-resourcemanager-extendedlocation
- [x] azure-resourcemanager-frontdoor
- [x] azure-resourcemanager-hanaonazure
- [x] azure-resourcemanager-hdinsight
- [x] azure-resourcemanager-healthbot
- [x] azure-resourcemanager-healthcareapis
- [x] azure-resourcemanager-hybridcompute
- [x] azure-resourcemanager-hybridkubernetes
- [x] azure-resourcemanager-hybridnetwork
- [x] azure-resourcemanager-imagebuilder
- [x] azure-resourcemanager-iothub
- [ ] azure-resourcemanager-keyvault
- [x] azure-resourcemanager-kubernetesconfiguration
- [x] azure-resourcemanager-kusto
- [x] azure-resourcemanager-labservices
- [x] azure-resourcemanager-loganalytics
- [x] azure-resourcemanager-logic
- [x] azure-resourcemanager-logz
- [x] azure-resourcemanager-machinelearningservices
- [x] azure-resourcemanager-maintenance
- [x] azure-resourcemanager-managedapplications
- [x] azure-resourcemanager-maps
- [x] azure-resourcemanager-mariadb
- [x] azure-resourcemanager-marketplaceordering
- [x] azure-resourcemanager-mediaservices
- [x] azure-resourcemanager-mixedreality
- [ ] azure-resourcemanager-msi
- [x] azure-resourcemanager-mysql
- [x] azure-resourcemanager-mysqlflexibleserver
- [x] azure-resourcemanager-netapp
- [x] azure-resourcemanager-operationsmanagement
- [x] azure-resourcemanager-peering
- [x] azure-resourcemanager-policyinsights
- [x] azure-resourcemanager-postgresql
- [x] azure-resourcemanager-postgresqlflexibleserver
- [x] azure-resourcemanager-powerbidedicated
- [ ] azure-resourcemanager-privatedns
- [x] azure-resourcemanager-purview
- [x] azure-resourcemanager-recoveryservices
- [x] azure-resourcemanager-recoveryservicesbackup
- [x] azure-resourcemanager-redisenterprise
- [x] azure-resourcemanager-relay
- [x] azure-resourcemanager-resourcegraph
- [x] azure-resourcemanager-resourcehealth
- [x] azure-resourcemanager-resourcemover
- [ ] azure-resourcemanager-samples
- [x] azure-resourcemanager-security
- [ ] azure-resourcemanager-servicebus
- [x] azure-resourcemanager-servicefabric
- [x] azure-resourcemanager-sqlvirtualmachine
- [x] azure-resourcemanager-storagecache
- [x] azure-resourcemanager-storageimportexport
- [x] azure-resourcemanager-storagepool
- [x] azure-resourcemanager-streamanalytics
- [x] azure-resourcemanager-subscription
- [x] azure-resourcemanager-support
- [x] azure-resourcemanager-timeseriesinsights
- [ ] azure-resourcemanager-trafficmanager
- [x] azure-resourcemanager-videoanalyzer
- [x] azure-resourcemanager-vmwarecloudsimple

**Comment by weidongxu-microsoft** [comment]
PR for Lite https://github.com/Azure/azure-sdk-for-java/pull/25647

**Comment by weidongxu-microsoft** [comment]
PR for Premium https://github.com/Azure/azure-sdk-for-java/pull/25656

**Comment by weidongxu-microsoft** [comment]
Verified premium with local run of `mvn -DskipTests -Dspotbugs.skip=true -Dcheckstyle.skip=true -Drevapi.skip=true clean install` with Java 17.
