### ISSUE TITLE
Hybrid profile 2018-03-01-hybrid incomplete

### ISSUE THREAD

**Issue by lmazuel** [Azure/azure-sdk-for-java#2564]
By @sijuman

> I wanted to reach out to you to ask a couple of questions. It seems that the Azure class for the Java SDK is missing the Keyvault management client. The link for this is provided: https://github.com/Azure/azure-sdk-for-java/blob/master/profiles/2018-03-01-hybrid/azure/src/main/java/com/microsoft/azure/management/profile_2018_03_01_hybrid/Azure.java
>  
> The Rest-Api-Spec link for 2018-profile: https://github.com/Azure/azure-rest-api-specs/blob/master/profile/2018-03-01-hybrid.json#L44.
>  
> Also it seems that there are two other gaps as well. Please also compare these two to find gaps. I think we are missing the following:
> 1.	Microsoft.Authorization: “2016-09-01”, “2015-07-01”
> 2.	Microsoft.Resources: “2016-06-01”
>

**Comment by jianghaolu** [comment]
Key vault client access is added in #2588. So is Microsoft.Resource 2016-06-01. 

Microsoft authorization 2016-09-01 is in "locks" package, and 2015-07-01 is in "policy" package for differentiating the features under the same namespace.
