### ISSUE TITLE
All migrated to 4.0 GA (including petclinic)

### ISSUE THREAD

**Issue by backwind1233** [Azure/azure-sdk-for-java#25651]
The [sample's](https://github.com/Azure-Samples/azure-spring-boot-samples/tree/spring-cloud-azure_4.0) dependenies should all depend on 4.0 GA released libraries.
[spring-petclinic-microservices](https://github.com/Azure-Samples/azure-spring-boot-samples/tree/spring-cloud-azure_4.0/spring-petclinic-microservices)  included

**Comment by saragluna** [comment]
Closing this now for it's completed.
