### ISSUE TITLE
Migrated to use DefaultCredential if possible

### ISSUE THREAD

**Issue by backwind1233** [Azure/azure-sdk-for-java#25652]
Tracked in [[Epic] improvements of azure-spring-boot-samples](https://github.com/Azure/azure-sdk-for-java/issues/26166)

---
now our samples don't have a unified template  or  approach to run.
Samples are configured with different authentication methods, likes accesskey, service principal, connectionString. 

📄[Spring Cloud Azure Samples improvement Track](https://microsoftapc.sharepoint.com/:x:/r/teams/Springintegration/_layouts/15/Doc.aspx?sourcedoc=%7BFF2DCA0E-B50C-4E6E-AF89-C13045697C89%7D&file=Spring%20Cloud%20Azure%20Samples%20improvement%20Track.xlsx&action=default&mobileredirect=true)

<html>
<body>
<div ccp_infra_version='3' ccp_infra_timestamp='1642403024005' ccp_infra_user_hash='3430123177' ccp_infra_copy_id='' data-ccp-timestamp='1642403024005'><html>

<body link="#0563C1" vlink="#954F72">

Sample Name | defaultCredential
-- | --
aad-resource-server | NA
aad-resource-server-by-filter | NA
aad-resource-server-by-filter-stateless | NA
aad-resource-server-obo | NA
aad-web-application | NA
aad-web-application-and-resource-server | NA
aad-b2c-web-application | NA
aad-b2c-resource-server | NA
spring-security | NA
azure-appconfiguration-conversion-sample-complete | NA
azure-appconfiguration-conversion-sample-initial | NA
azure-appconfiguration-sample | NA
feature-management-sample | NA
feature-management-web-sample | NA
azure-cloud-foundry-service-sample | NA
spring-cloud-azure-data-cosmos-sample | DONE
spring-cloud-azure-cosmos-sample | DONE
cosmos-multi-database-multi-account | NA
cosmos-multi-database-single-account | NA
eventhubs-integration | DONE
spring-cloud-azure-sample-eventhubs-kafka | DONE
eventhubs-binder | DONE
eventhubs-multibinders | DONE
run-with-command-line-server-side | NA
run-with-command-line-client-side | NA
keyvault-certificates-client-side | NA
keyvault-certificates-server-side | NA
single-property-source | DONE
multiple-property-source | DONE
servicebus-jms-queue | DONE
servicebus-jms-topic | DONE
servicebus-queue-binder | DONE
servicebus-multibinders | DONE
servicebus-topic-binder | DONE
multiple-namespaces | DONE
single-namespace | DONE
storage-blob-sample | DONE
storage-file-sample | NA
storage-queue-operation | DONE
storage-queue-integration | DONE

</body>

</html>
</div>
</body>
</html>

**Comment by backwind1233** [comment]
linked issue: https://github.com/Azure/azure-sdk-for-java/issues/25652

**Comment by saragluna** [comment]
Why is storage file not applicable?

**Comment by saragluna** [comment]
Closing this now.
