### ISSUE TITLE
[QUERY] missing VirtualWANs API

### ISSUE THREAD

**Issue by Fabio1988** [Azure/azure-sdk-for-java#25666]
**Query/Question**
Tried to list all virtual WANs within tenant, but I think it's not possible with this SDK?!
https://docs.microsoft.com/en-us/rest/api/virtualwan/virtual-wans/list

***Why is this not a Bug or a feature Request?***
Don't know if I'm right, that this is missing.

**Setup (please complete the following information if applicable):**
 - OS: Ubuntu
 - IDE: IntelliJ
 - Library/Libraries: com.azure:azure-core:1.22.0; com.azure: com.azure.resourcemanager:azure-resourcemanager:2.9.0
 
 **Information Checklist**
 Kindly make sure that you have added all the following information above and checkoff the required fields otherwise we will treat the issuer as an incomplete report
- [x] Query Added
- [x] Setup information Added

**Comment by pallavit** [comment]
@weidongxu-microsoft can you please help route this issue.

**Comment by weidongxu-microsoft** [comment]
@Fabio1988 Here is the sample https://github.com/Azure/azure-sdk-for-java/blob/main/sdk/resourcemanager/azure-resourcemanager/src/samples/java/com/azure/resourcemanager/network/generated/VirtualWansListSamples.java

**Comment by Fabio1988** [comment]
thx a lot. will have a look there next time before posting :)

**Comment by weidongxu-microsoft** [comment]
You are welcome. This part could be hard to find, as currently we do not have convenient layer over VirtualWAN. Generally all available REST API can be found within the `.serviceClient()` object.
