### ISSUE TITLE
Test spring modules support both spring-boot 2.5 and spring-boot 2.6 in spring-ci pipeline

### ISSUE THREAD

**Issue by chenrujun** [Azure/azure-sdk-for-java#25663]
Before version 4.0. we test spring-boot 2.4 and 2.5 by this script: [replace_util.py](https://github.com/Azure/azure-sdk-for-java/blob/3bfb5487f1e940fbe4ef557f5e3ca42cd2ba827d/sdk/spring/scripts/replace_util.py). This script need the test-modules like azure-spring-boot-test-active-directory, now these test-modules have been deleted. We need find another way to test compatibility of 2.5 and 2.6.

**Comment by chenrujun** [comment]
Hi, @moarychan , could you please help to investigate this issue?

**Comment by saragluna** [comment]
Closed in #26002.
