### ISSUE TITLE
need java code with working sample

### ISSUE THREAD

**Issue by fivig** [Azure/azure-sdk-for-java#25661]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3565a7f5-0992-3b79-bb68-c5ae9617544b
* Version Independent ID: 745b1eb3-8e0e-c17a-847d-06abc64f7488
* Content: [Azure Resource Manager RecoveryServices client library for Java](https://docs.microsoft.com/en-us/java/api/overview/azure/resourcemanager-recoveryservices-readme?view=azure-java-preview)
* Content Source: [docs-ref-services/preview/resourcemanager-recoveryservices-readme.md](https://github.com/Azure/azure-docs-sdk-java/blob/master/docs-ref-services/preview/resourcemanager-recoveryservices-readme.md)
* Service: ****
* Product: **azure**
* Technology: **azure**
* GitHub Login: @ramya-rao-a
* Microsoft Alias: **ramyar**

**Comment by pallavit** [comment]
@weidongxu-microsoft can you please help route this.

**Comment by weidongxu-microsoft** [comment]
Example will be generated in the next SDK release. If you want it now, submit SDK release request on https://portal.azure-devex-tools.com/tools/request-api-release
