### ISSUE TITLE
Revisit request verbose logging.

### ISSUE THREAD

**Issue by kasobol-msft** [Azure/azure-sdk-for-java#25678]
Request logging appends new lines 
https://github.com/Azure/azure-sdk-for-java/blob/11cc395d232fa89eb137586b58da0078216b9c3c/sdk/core/azure-core/src/main/java/com/azure/core/http/policy/HttpLoggingPolicy.java#L140
which are then stripped by `ClientLogger` resulting in sample output like this:
![image](https://user-images.githubusercontent.com/61715331/143309387-9bb093e5-2540-4ce0-bb13-77c840e2838b.png)

Consider finding up better format that's human friendly and/or enrich experience with structured logging.

**Comment by alzimmermsft** [comment]
Closing as @lmolkova fixed this when she migrated HTTP logging to use structured logging.
