### ISSUE TITLE
Delete configuration properties that we do not support.

### ISSUE THREAD

**Issue by chenrujun** [Azure/azure-sdk-for-java#25687]
In current reference doc, there are a log of configuration items that we do not support, for example: `spring.cloud.azure.cosmos.proxy.hostname`. We should delete these items.

https://microsoft.github.io/spring-cloud-azure/docs/current/reference/html/appendix.html##configuration-properties

![image](https://user-images.githubusercontent.com/13167207/143365779-fb47e969-b84e-46b1-a926-771f0bbc6ddf.png)

**Comment by saragluna** [comment]
closing this one in favor of  https://github.com/Azure/azure-sdk-for-java/issues/25690.
