### ISSUE TITLE
Update spring libraries in start.spring.io after 4.0 GA

### ISSUE THREAD

**Issue by yiliuTo** [Azure/azure-sdk-for-java#25683]
First We need to make sure which libraries should be displayed in start.spring.io and how to display them explicitly and implicitly.
And then discuss with start.spring.io GitHub repo maintainer about adjusting current display of Azure Spring libraries by creating an issue for it.

**Comment by saragluna** [comment]
https://github.com/spring-io/start.spring.io/issues/871

**Comment by saragluna** [comment]
Spring Initializer is up to date now.
