### ISSUE TITLE
Naming problem about spring properties

### ISSUE THREAD

**Issue by chenrujun** [Azure/azure-sdk-for-java#25686]
1. `Aware` should not be used in these interfaces name:

https://github.com/Azure/azure-sdk-for-java/blob/ccfc66dc168da62f23994bec2813c7d2f0046a68/sdk/spring/spring-cloud-azure-core/src/main/java/com/azure/spring/core/properties/AzureProperties.java#L15

2. `CP` should not be used in class name, especially out of `implementation` package.

https://github.com/Azure/azure-sdk-for-java/blob/ccfc66dc168da62f23994bec2813c7d2f0046a68/sdk/spring/spring-cloud-azure-autoconfigure/src/main/java/com/azure/spring/cloud/autoconfigure/properties/AbstractAzureAmqpCP.java#L15

**Comment by saragluna** [comment]
Closing this in #26209, the aware interface could be changed if we come up with better names.
