### ISSUE TITLE
[BUG] Cluster creation requires resource ID for blob storage account when using private endpoints 

### ISSUE THREAD

**Issue by medvedzver** [Azure/azure-sdk-for-java#25680]
**Describe the bug**
We are trying to create a cluster with the storage account that is using private endpoints. After some try and fail we've learned that we need to set `ResourceProviderConnection` to `OUTBOUND` in NetworkProperties. 
After trying again we are seeing following response from API ( HdiClusterAccessor provisionCluster call):

`Status code 400, "{"code":"BadRequest","message":"Resource ID is missing or invalid but required for storage account **Account name** when NetworkProperties has ResourceProviderConnection set to Outbound. The ID takes format like /subscriptions/$SUBSCRIPTION_ID/resourceGroups/$RESOURCE_GROUP/providers/Microsoft.Storage/storageAccounts/$ACCOUNT_NAME and can be found in Storage Account Properties from Azure Portal"}"`

According to docs "The resource ID of storage account, only to be specified for Azure Data Lake Storage Gen 2."
Our storage account is a blob storage, so it shouldn't require ID. THis is what our storage account definition looks like:
`new StorageAccount()
        .withName(accountName + ".blob.core.windows.net")
        .withKey(key)
        .withContainer("container")
        .withIsDefault(true);`

We've tried specifying a resource id , but creation failed with 
`com.azure.core.management.exception.ManagementException: Long running operation is Failed or Cancelled.: Internal server error occurred while processing the request. Please retry the request or contact support.`

***Exception or Stack Trace***
```
        Suppressed: java.lang.Exception: #block terminated with an error
                at reactor.core.publisher.BlockingSingleSubscriber.blockingGet(BlockingSingleSubscriber.java:99) ~[reactor-core-3.4.9.jar:3.4.9]
                at reactor.core.publisher.Mono.block(Mono.java:1704) ~[reactor-core-3.4.9.jar:3.4.9]
                at com.azure.resourcemanager.hdinsight.implementation.ClustersClientImpl.create(ClustersClientImpl.java:577) ~[azure-resourcemanager-hdinsight-1.0.0-beta.2.jar:?]
                at com.azure.resourcemanager.hdinsight.implementation.ClusterImpl.create(ClusterImpl.java:101) ~[azure-resourcemanager-hdinsight-1.0.0-beta.2.jar:?]
```

**To Reproduce**
Create storage account with private endpoint.  Specify account name, key and container but not resource id in azure API storage account definition.
Try creating a cluster.

**Expected behavior**
Either cluster to be created or documentation for `withResourceId` should specify "ADLS or Blob storage gen2"

**Screenshots**

**Setup (please complete the following information):**
com.azure.resourcemanager:azure-resourcemanager-hdinsight:1.0.0-beta.2
com.azure.resourcemanager:azure-resourcemanager-network:2.4.0
com.azure:azure-identity:1.3.0

**Additional context**
It is possible that failure happening after specifying resource id related to our incorrect infra setup.

**Information Checklist**
Kindly make sure that you have added all the following information above and checkoff the required fields otherwise we will treat the issuer as an incomplete report
- [ ] Bug Description Added
- [ ] Repro Steps Added
- [ ] Setup information Added

Thank you!

**Comment by g2vinay** [comment]
Since this is the ARM SDK.
Adding @weidongxu-microsoft to look into this issue.

**Comment by weidongxu-microsoft** [comment]
@medvedzver The form `/subscriptions/$SUBSCRIPTION_ID/resourceGroups/$RESOURCE_GROUP/providers/Microsoft.Storage/storageAccounts/$ACCOUNT_NAME` is the storage account ID. Every storage account (whatever the type, actually every ARM resource) has this kind of ID.

You are correct to provide this ID to the HDInsights cluster. It is likely HDInsights having problem with the PUT REST API. If you can, please provide the logging of request and response to HDInsights. Enable logging via:
```
    HDInsightManager.configure()
    .withLogOptions(new HttpLogOptions().setLogLevel(HttpLogDetailLevel.BODY_AND_HEADERS))
    ...
```
If you can, provide your code on the `manager.clusters()` call as well.

We will contact HDInsights team on what is this "Internal server error".

**Comment by weidongxu-microsoft** [comment]
Also there is a sample in readme (however it does not use private link)
https://github.com/Azure/azure-sdk-for-java/tree/main/sdk/hdinsight/azure-resourcemanager-hdinsight#examples

**Comment by medvedzver** [comment]
@weidongxu-microsoft Some updates. I can't reproduce an issue right now, probably due to some infra changes.
But I've noticed one thing regarding "resourceId". If I specify it and set connection to "INBOUND" - creation fails with 
`Status code 400, "{"code":"BadRequest","message":"DeploymentDocument 'AmbariConfiguration_1_7' failed the validation. Error: 'Unable to access storage account myaccount.blob.core.windows.net. Details: '"}"`

This is our call:
```
_manager.clusters().define(params.getClusterName())
        .withExistingResourceGroup(params.getResourceGroupName())
        .withRegion(params.getRegion())
        .withProperties(buildClusterCreateProperties(params))
        .create();

  protected ClusterCreateProperties buildClusterCreateProperties(AzureClusterProvisioningParams params) {
    return new ClusterCreateProperties()
        .withClusterVersion(params.getHdiVersion().getAzureHdiVersion())
        .withOsType(OSType.LINUX)
        .withTier(Tier.STANDARD)
        .withClusterDefinition(buildClusterDefinition(params.getClusterKind(), params.getClusterConfiguration()))
        .withComputeProfile(buildComputeProfile(params.getHeadnode(), params.getWorknode(), params.getResourceGroupName()))
        .withNetworkProperties(buildNetworkProperties(params.getResourceProviderConnection()))
        .withStorageProfile(new StorageProfile()
            .withStorageaccounts(ImmutableList.of(
                toStorageAccount(params.getStorageAccount())
                )
            ));
  }

  private StorageAccount toStorageAccount(AzureStorageAccount storageAccount) {
    return new StorageAccount()
        .withResourceId(storageAccount.getResourceId()) //fails if you set it with INBOUND rp connection
        .withFileSystem(storageAccount.getFileSystem()) //this is null
        .withName(storageAccount.getAccountName() + BLOB_ENDPOINT_SUFFIX)
        .withKey(storageAccount.getAccessKey())
        .withContainer(storageAccount.getContainerName())  //we have blob storage so we specify this one
        .withIsDefault(true);
  }

  private NetworkProperties buildNetworkProperties(
      com.linkedin.azure.client.hdinsights.models.ResourceProviderConnection resourceProviderConnection) {
    return new NetworkProperties()
        .withResourceProviderConnection(ResourceProviderConnection.fromString(
            resourceProviderConnection.getResourceProviderConnection()));
  }

```

**Comment by weidongxu-microsoft** [comment]
@medvedzver 
So the "Internal server error" is probably intermittent problem in service.

From their doc, I see they set the connection to Outbound.
https://docs.microsoft.com/azure/hdinsight/hdinsight-private-link#create-clusters

However I could misunderstood your use case. In your case, is the storage account using private endpoint (which mean it got a private dns with it?), not the HDInsights cluster?

**Comment by medvedzver** [comment]
@weidongxu-microsoft Storage account uses private endpoint. We use private DNS Zones, as our sre told me. We don't use private link for HDI.

**Comment by weidongxu-microsoft** [comment]
@medvedzver 

In my test, I had to allow access to storage account from the VNET used for hdinsight. Else I got "Provided custom VNET is not allowed to access Network ACLed storage account" (but ideally it does not need this as private endpoint disables network policy).
![image](https://user-images.githubusercontent.com/53292327/144414756-81e479bd-9a26-4605-b284-da5826b01728.png)

After this, I can create the cluster (Spark with a few headnode and workernode).

My test happens in a single VNET (private endpoint for storage account, and the hdinsight cluster).

PS, maybe you can try later versions of the SDK
com.azure.resourcemanager:azure-resourcemanager-hdinsight:1.0.0-beta.5
com.azure.resourcemanager:azure-resourcemanager-network:2.10.0
com.azure:azure-identity:1.4.1
