### ISSUE TITLE
Logic app run trigger should allow for body content to be specified.

### ISSUE THREAD

**Issue by rhudea** [Azure/azure-sdk-for-java#2568]
The run trigger function (https://github.com/Azure/azure-sdk-for-java/blob/80b8793f3c9d765cc1d59123397152a5ab1ef059/logic/resource-manager/v2016_06_01/src/main/java/com/microsoft/azure/management/logic/v2016_06_01/implementation/WorkflowTriggersImpl.java#L83) should allow for body content to be specified for the trigger, as that body content is usually the input for the workflow.

Probably this is because the documentation is incomplete (https://docs.microsoft.com/en-us/rest/api/logic/workflowtriggers/run) as it not mentioning the possibility of passing a body to the POST call.

**Comment by vhvb1989** [comment]
Hello @rhudea

I am sorry about you didn't get a sooner answer on this
Do you still need help? Let me know and I would be happy to assist.

Note: As part of repository cleaning effort, this issue will be closed by Sep 20 if no response is received from submitter and/or not further action is required.

**Comment by yungezz** [comment]
hi @ChenTanyi could you pls have a look? thanks

**Comment by ChenTanyi** [comment]
@rhudea The sdk is directly generated by service api. We cannot directly add parameter that is not in the api. https://github.com/Azure/azure-rest-api-specs/blob/4afd8fc/specification/logic/resource-manager/Microsoft.Logic/stable/2016-06-01/logic.json#L989

I could add label to ask service add trigger body in rest api.
