### ISSUE TITLE
Make the cosmos proxy configuration properties more clear

### ISSUE THREAD

**Issue by moarychan** [Azure/azure-sdk-for-java#25690]
Currently, the `spring.cloud.azure.cosmos.proxy` properties is not used for cosmos builder factory.

Should both `GatewayConnection` and `ProxyProperties` be used or a unified one,  need further confirmation.

**Expected behavior**
Supported proxy configurations are available and clear.

**Comment by saragluna** [comment]
we should also try to make sure retry is picked up.

**Comment by saragluna** [comment]
Closing in #25766.
