### ISSUE TITLE
Update version in azure-spring-boot-samples. Sample PR: azure-spring-boot-samples#62.

### ISSUE THREAD

**Issue by chenrujun** [Azure/azure-sdk-for-java#25699]
Please check parent issue (#25581) to get more information.

**Comment by saragluna** [comment]
@backwind1233 we should think about when users have a Spring Boot version, how they will find the corresponding samples?

**Comment by Netyyyy** [comment]
close it and work on the new issue:https://github.com/Azure-Samples/azure-spring-boot-samples/issues/42
