### ISSUE TITLE
Storage: Manually iterate through the DataLakeFileSystemClient.listPath response

### ISSUE THREAD

**Issue by Ankit-MSFT** [Azure/azure-sdk-for-java#25691]
**Query/Question**
When we use DataLakeFileSystemClient.listPath with ListOptions.setMax(10). In the foreach loop it keeps on retrieving next set of data continuously.

To understand the automatic retrieval of data in sets of 10 records, I used the following code:
 
```
DataLakeServiceClient dataLakeServiceClient = new DataLakeServiceClientBuilder()
                        .endpoint("https://STORAGE.blob.core.windows.net")
                        .sasToken("?sv=2020-10-02&st=2021-11-24T08%3A16%3A36Z&se=2021-11-25T08%3A16%3A36Z&sr=c&sp=rl&sig=XXXX")
                        .buildClient();
DataLakeFileSystemClient dataLakeFileSystemClient = dataLakeServiceClient.getFileSystemClient("dummydata");
                    
ListPathsOptions options = new ListPathsOptions().setPath("dummy_data_1").setMaxResults(10);
System.out.println("Max Result is " + options.getMaxResults());
                    
PagedIterable<PathItem> response = dataLakeFileSystemClient.listPaths(options, null);
Iterable<PagedResponse<PathItem>> pages = response.iterableByPage();
int pageNo = 1;
for (PagedResponse<PathItem> page : pages) {
       System.out.println("This is the page number: " + pageNo);
       pageNo++;
       page.getElements().forEach(path -> System.out.printf("Name: %s%n", path.getName()));
}
```

Console output:
> Max Result is 10
This is the page number: 1
Name: dummy_data_1/000002
Name: dummy_data_1/00001
Name: dummy_data_1/00003
Name: dummy_data_1/00004
Name: dummy_data_1/00005
Name: dummy_data_1/0001
Name: dummy_data_1/00011
Name: dummy_data_1/00012
Name: dummy_data_1/00013
Name: dummy_data_1/00014
This is the page number: 2
Name: dummy_data_1/0002
Name: dummy_data_1/00021
Name: dummy_data_1/00022
Name: dummy_data_1/00023
Name: dummy_data_1/00024
Name: dummy_data_1/0003
Name: dummy_data_1/00031
Name: dummy_data_1/00032
Name: dummy_data_1/00033
Name: dummy_data_1/00034
This is the page number: 3
Name: dummy_data_1/0004

How to get continuation token if we want to have separate paginated call for ListBlob operation, instead of the automatic/lazy loading calls.

***Why is this not a Bug or a feature Request?***
As per documentation, [DataLakeFileSystemClient.listPath](https://azuresdkdocs.blob.core.windows.net/$web/java/azure-storage-file-datalake/12.7.2/com/azure/storage/file/datalake/DataLakeFileSystemClient.html#listPaths-com.azure.storage.file.datalake.models.ListPathsOptions-java.time.Duration-) method returns a lazy loaded list of files/directories in this account. The returned PagedIterable can be consumed while new items are automatically retrieved as needed. Need a sample how can we iterate manually, instead of automatic loading.

**Setup (please complete the following information if applicable):**
 - OS: Windows 11
 - IDE: eclipse
 - Library/Libraries: azure-storage-file-datalake:12.7.2
 
 **Information Checklist**
 Kindly make sure that you have added all the following information above and checkoff the required fields otherwise we will treat the issuer as an incomplete report
- [Y] Query Added
- [Y] Setup information Added

**Comment by hongli750210** [comment]
@Ankit-MSFT 
The SDK currently does not provide a method to get a list of consecutive tokens. In order to implement manual iteration, I have used the following source, hope it will be helpful to you. 

```
        DataLakeServiceClient dataLakeServiceClient = new DataLakeServiceClientBuilder()
                .endpoint("https://STORAGE.blob.core.windows.net")
                .sasToken("?sv=2020-10-02&st=2021-11-24T08%3A16%3A36Z&se=2021-11-25T08%3A16%3A36Z&sr=c&sp=rl&sig=XXXX")
                .buildClient();
        client = dataLakeServiceClient.getFileSystemClient("dummydata");

        ListPathsOptions options = new ListPathsOptions().setPath("dummy_data_1").setMaxResults(10);
        System.out.println("Max Result is " + options.getMaxResults());

        PagedIterable<PathItem> response = client.listPaths(options, null);
        List<String> continuationTokens = new ArrayList<>();
        continuationTokens.add(null);
        client.listPaths(options, null).iterableByPage().forEach(pageIterable -> {
            if (pageIterable.getContinuationToken() != null) continuationTokens.add(pageIterable.getContinuationToken());
        });

        AtomicInteger pageNo = new AtomicInteger(1);
        continuationTokens.forEach(continuationToken -> {
            System.out.println("This is the page number: " + pageNo.get());
            Iterable<PagedResponse<PathItem>> pages =
                    client.listPaths(options, null).iterableByPage(continuationToken);
            PagedResponse<PathItem> page = pages.iterator().next();
            pageNo.incrementAndGet();
            page.getElements().forEach(path -> System.out.printf("Name: %s%n", path.getName()));
        });
```
