### ISSUE TITLE
Write test case in spring cloud azure 4.0 repo for eventhubs-kafka

### ISSUE THREAD

**Issue by backwind1233** [Azure/azure-sdk-for-java#25707]
the module `spring-cloud-azure-starter-eventhubs-kafka` was removed in this [PR](https://github.com/Azure/azure-sdk-for-java/pull/24940)
we need to write test cases to make sure `spring-cloud-starter-stream-kafka` can work with `spring-cloud-azure-autoconfigure` well.

**Comment by saragluna** [comment]
@moarychan do we need such test case?

**Comment by moarychan** [comment]
Due to only the KafkaProperties bean injection for Kafka, I check the UTs have coveraged.

**Comment by saragluna** [comment]
Closing this issue now.
