### ISSUE TITLE
[BUG] DataLakeFileClient.rename() is not working when authenticated with SAS

### ISSUE THREAD

**Issue by j0kkeri** [Azure/azure-sdk-for-java#25714]
**Query/Question**
Is it possible to use DataLakeFileClient.rename() when authenticated with SAS?

I am struggling to implement DataLakeFileClient.rename() and starting to wonder if it's impossible to do rename operation when authenticated with SAS token? Getting "403(AuthorizationPermissionMismatch)"

It works when I use Access key(StorageSharedKeyCredential) but not with SAS (AzureSasCredential).
(SAS token should contain all possible rights and I am able to upload/download/delete files/blobs... See details in **Setup**)

I'm also wondering this as when I use the exact same SAS token with Azure Storage Explorer it works like a charm and I am able to rename a file... :/

***Why is this not a Bug or a feature Request?***
Not yet a clear bug, just trying to get clarification about the functionality...

**Setup (please complete the following information if applicable):**
 - OS: Win10
 - IDE: Eclipse / AdoptOpenJDK 8.0.242.08
 - Library/Libraries: azure-storage-file-datalake 12.7.2
 - Tested SAS token: "sp=racwdlmeop&st=2021-11-25T09:27:54Z&se=2022-11-25T17:27:54Z&spr=https&sv=2020-08-04&sr=c&sig=0QZ__________cleaned-sig___________3D"
 
 **Information Checklist**
 Kindly make sure that you have added all the following information above and checkoff the required fields otherwise we will treat the issuer as an incomplete report
- [ X ] Query Added
- [ X ] Setup information Added

**Comment by pallavit** [comment]
@amishra-dev can you please help route this issue.

**Comment by rickle-msft** [comment]
@j0kkeri Thanks for opening this issue. Are you generating your sas token using the shared key or using a UserDelegationKey?

**Comment by j0kkeri** [comment]
> @j0kkeri Thanks for opening this issue. Are you generating your sas token using the shared key or using a UserDelegationKey?

@rickle-msft Thanks for the reply, I'm using shared key, I think...

**Comment by rickle-msft** [comment]
@j0kkeri Interesting. SharedKey should have access to all operations in the account. Can we start by looking at a code snippet that you're using to generate the sas token using the SDK? Including how you build the client used to generate the sas and how you're setting it on a client that tries to perform this operation? It would also be helpful if we can get a side by side comparison of a sas generated this way and one generated by storage explorer. Unless you're using the sas token you provided in both cases.

**Comment by j0kkeri** [comment]
@rickle-msft

Below you can find a simplified version of my code. The SAS token used in Java(rename not working) is exact same as used in Storage Explorer(rename working). The SAS token is created in Azure Portal, see screenshot.



`import java.util.Locale;

import com.azure.core.credential.AzureSasCredential;
import com.azure.storage.file.datalake.DataLakeFileClient;
import com.azure.storage.file.datalake.DataLakeFileSystemClient;
import com.azure.storage.file.datalake.DataLakeServiceClient;
import com.azure.storage.file.datalake.DataLakeServiceClientBuilder;

public abstract class AzureFileDatalakeTransfer_SAS {
    static DataLakeServiceClient dataLakeServiceClient = null;

    public static void main(String args[]) {

        String endpoint = String.format(Locale.ROOT,
                "https://%s.dfs.core.windows.net", "myAccount");

        AzureSasCredential sasCredential = new AzureSasCredential(
                "sp=racwdlmeop&st=2021-12-01T11:57:11Z&se=2022-12-01T19:57:11Z&spr=https&sv=2020-08-04&sr=c&sig=t.....................D");
        dataLakeServiceClient = new DataLakeServiceClientBuilder()
                .endpoint(endpoint).credential(sasCredential).buildClient();

        DataLakeFileSystemClient dataLakeFileSystemClient = dataLakeServiceClient
                .getFileSystemClient("myContainer");

        DataLakeFileClient dataLakeFileClient = dataLakeFileSystemClient
                .getFileClient("upload.txt");

        // Upload is OK, file is found from container
        dataLakeFileClient.uploadFromFile("C:\\Temp\\upload.txt");

        // This is where error occurs:
        dataLakeFileClient.rename(null, "new_name.txt");
        // ------>
        // Status code 403,
        // "{"error":{"code":"AuthorizationPermissionMismatch",
        // "message":"This request is not authorized to perform this operation
        // using this permission.
    }
}`

Attached screenshot on how I created the SAS token:
![image](https://user-images.githubusercontent.com/36040597/144231594-22cc6308-2206-4995-8afb-bdc30ab05267.png)

**Comment by rickle-msft** [comment]
@j0kkeri Thank you for that information now. I'm working on reproducing your setup. Can you please also share a screenshot of how you're using Storage Explorer? I may need to communicate with that team to see what underlying REST api they are using to better understand the difference in behavior

**Comment by rickle-msft** [comment]
@j0kkeri Actually no need for that. I think I figured out what's wrong. There's a bug where we don't attach the sas token to the rename source, so it can't be authenticated properly. I'll work on getting a fix out for this after I get out our next release in the next few days. 

We should be attaching that (if present) to the renameSource variable in DatalakePathClient.renameWithResponse

**Comment by j0kkeri** [comment]
@rickle-msft Good to hear that this should be possible and fix is on the way. I will stay tuned for the fix.
Should I update the question as a bug report or is it ok like this?

**Comment by rickle-msft** [comment]
Updated :)

**Comment by j0kkeri** [comment]
Any estimates on fix schedule?

**Comment by rickle-msft** [comment]
Hi, @j0kkeri I am working on a round of bug fixes right now. On account of your follow up, I can move this one to next in the queue and hopefully have a fix out in a couple weeks barring any schedule interruptions

**Comment by j0kkeri** [comment]
@rickle-msft Awesome, thanks a million!

**Comment by rickle-msft** [comment]
Quick update here, I believe #26394 is a prerequisite as it will be necessary for being able to get the sas token used for authenticating the client and applying it to the rename source. I am working on getting that merged and then will be able to resume this feature once it is released in core

**Comment by j0kkeri** [comment]
@rickle-msft Is there some kind of workaround available that I could use for this until a fix is issued?

**Comment by rickle-msft** [comment]
The only work arounds I can think of are either using shared key in the meantime or adding a pipeline policy that checks for a rename-source header and adds a sas token to it. 

Apologies for the delay. The PR I was making into core hit some push back and it was requested I go another route. I'll pick this back up.

**Comment by j0kkeri** [comment]
> The only work arounds I can think of are either using shared key in the meantime or adding a pipeline policy that checks for a rename-source header and adds a sas token to it.
> 
> Apologies for the delay. The PR I was making into core hit some push back and it was requested I go another route. I'll pick this back up.

Thank you for your response! Unfortunately neither of options are possible for me as it is 3rd party who controls the subscription and I'm sure these are not option for them either. We'll just have to try to be patient and wait for the fix here :)

**Comment by rickle-msft** [comment]
I see. I do appreciate your patience on this issue and will work on getting it out for you asap.

**Comment by rickle-msft** [comment]
I just put out #27502 which is another stab at a prerequisite for this issue. The design discussion took a different direction that caused me to abandon the other attempt, so hopefully this one gets through.
