### ISSUE TITLE
[QUERY] ServiceBusSessionReceiverAsyncClient - Mono instead of Flux

### ISSUE THREAD

**Issue by steinrr** [Azure/azure-sdk-for-java#25717]
**Query/Question**
I have a Spring Boot app, where I receive one single message from a Azure Service Bus queue session. 

The code is:
```
@Autowired
ServiceBusSessionReceiverAsyncClient apiMessageQueueIntegrator;
.
.
.
Mono<ServiceBusReceiverAsyncClient> receiverMono = apiMessageQueueIntegrator.acceptSession(sessionid);
		Disposable subscription = Flux.usingWhen(receiverMono,
	            receiver -> receiver.receiveMessages(),
	            receiver -> Mono.fromRunnable(() -> receiver.close()))
	            .subscribe(message -> {
	                // Process message.
	                logger.info(String.format("Message received from quque. Session id: %s. Contents: %s%n", message.getSessionId(),
	                    message.getBody()));
	                receivedMessage.setReceivedMessage(message);
	                timeoutCheck.countDown();

	            }, error -> {
	                logger.info("Queue error occurred: " + error);
	            });
```
As I am receiving only one message from the session, I use a CountDownLatch(1) to dispose of the subscription when I have received the message.

The documentation of the library says that it is possible to use Mono.usingWhen instead of Flux.usingWhen if I only expect one message, but I cannot find any examples of this anywhere, and I have not been able to figure out how to rewrite this code to do this.

Could you show me how the pasted code would look if I were to use Mono.usingWhen instead?

***Why is this not a Bug or a feature Request?***
Coding question.
 
 **Information Checklist**
 Kindly make sure that you have added all the following information above and checkoff the required fields otherwise we will treat the issuer as an incomplete report
- [x] Query Added
- [x] Setup information Added

**Comment by conniey** [comment]
By default `receiveMessages()` is a Flux because we imagine the messages from a session to be "infinitely long". In your case, you only want the first message in the stream, so we use the `next()` operator.

The usage of the countdown latch is probably not the best approach. In the sample, we had one there so that the program didn't end before the messages were received. `.subscribe` is not a blocking call, it sets up the handlers and moves onto the next line of code.

Consider:

```java
Mono<ServiceBusReceiverAsyncClient> receiverMono = sessionReceiver.acceptSession("greetings-id");
Mono<ServiceBusReceivedMessage> singleMessageMono = Mono.usingWhen(receiverMono,
    receiver -> {
        // Anything you wish to do with the receiver.
        // In this case we only want to take the first message, so we use the "next" operator. This returns a
        // Mono.
        return receiver.receiveMessages().next();
    },
    receiver -> Mono.fromRunnable(() -> receiver.close()));

try {
    ServiceBusReceivedMessage message = singleMessageMono.block(Duration.ofSeconds(30));
    if (message != null) {
        // Process message.

    }
} catch (Exception error) {
    System.err.println("Error occurred: " + error);
}
```

**Comment by steinrr** [comment]
Thanks for clarification @conniey! Could I suggest also adding this in the example together with the Flux one?
