### ISSUE TITLE
Adding new SKU versions to the VirtualMachineSizeTypes

### ISSUE THREAD

**Issue by IvanMiskulin** [Azure/azure-sdk-for-java#25730]
When we are validating SKU it is checked against values in VirtualMachineSizeType class. I see that there is big difference between SKUs listed in the SDK and the SKUs that are listed from Azure DevOps CLI with command: "az vm list-sizes -l <location>".

For example for region westeurope there are 584 available different SKUs, while in SDK there are 166 SKU available:
az vm list-sizes -l westeurope | grep name | wc -l
584

I would like to have those new SKU available in the SDK. 

SKUs that are available in all regions could be kept in VirtualMachineSizeTypes.class.
New SKUs that are not included in the current version of the SDK could be added to the region specific classes. 
Those region specific classes could contain rest of the SKUs which are not in VirtualMachineSizeTypes.class but are available for the region through Azure DevOps CLI.

**Comment by joshfree** [comment]
@weidongxu-microsoft could you please follow up with @IvanMiskulin?

**Comment by weidongxu-microsoft** [comment]
@IvanMiskulin

You can call `azure.computeSkus().listByRegion(Region.EUROPE_WEST)` for similar list of VM size types in Java SDK.

However we are likely not going to put them into the `VirtualMachineSizeTypes` class, as the class is static, but the available size types is dynamical.
And size types in the response can be removed, while any value statically defined in `VirtualMachineSizeTypes` class cannot, as this would mean breaking changes to SDK.
