### ISSUE TITLE
[BUG]Using Cosmos Auditing with latest spring boot version 2.6.1 throws Circular dependency errors

### ISSUE THREAD

**Issue by svankamamidi1** [Azure/azure-sdk-for-java#25755]
**Describe the bug**
In order to resolve some security vulnerabilities from spring, we have upgraded to latest spring boot version 2.6.1 and we saw errors during application context initialization reporting circular dependencies between cosmosClient and CosmosAuditingHandler.

***Exception or Stack Trace***
Add the exception log and stack trace if available

2021-11-30 12:02:46.010  INFO 2764 --- [           main] w.s.c.ServletWebServerApplicationContext : Root WebApplicationContext: initialization completed in 6148 ms
2021-11-30 12:02:46.897  WARN 2764 --- [           main] ConfigServletWebServerApplicationContext : Exception encountered during context initialization - cancelling refresh attempt: org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'cosmosHealthIndicatorConfig': Unsatisfied dependency expressed through field 'cosmosClient'; nested exception is org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'cosmosClientConfig': Unsatisfied dependency expressed through field 'cosmosAuditingHandler'; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'cosmosAuditingHandler': Cannot create inner bean '(inner bean)#3d1cfad4' of type [com.azure.spring.data.cosmos.core.mapping.CosmosAuditingRegistrar$CosmosMappingContextLookup] while setting constructor argument; nested exception is org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name '(inner bean)#3d1cfad4': Unsatisfied dependency expressed through constructor parameter 0; nested exception is org.springframework.beans.factory.BeanCurrentlyInCreationException: Error creating bean with name 'cosmosClientConfig': Requested bean is currently in creation: Is there an unresolvable circular reference?
2021-11-30 12:02:46.908  INFO 2764 --- [           main] o.apache.catalina.core.StandardService   : Stopping service [Tomcat]
2021-11-30 12:02:46.971  INFO 2764 --- [           main] ConditionEvaluationReportLoggingListener :

Error starting ApplicationContext. To display the conditions report re-run your application with 'debug' enabled.
2021-11-30 12:02:47.107 ERROR 2764 --- [           main] o.s.b.d.LoggingFailureAnalysisReporter   :

***************************
APPLICATION FAILED TO START
***************************

Description:

The dependencies of some of the beans in the application context form a cycle:

   cosmosHealthIndicatorConfig (field private com.azure.cosmos.CosmosAsyncClient com.nuance.powershare.messaging.config.health.CosmosHealthIndicatorConfig.cosmosClient)
┌─────┐
|  cosmosClientConfig (field private org.springframework.data.auditing.IsNewAwareAuditingHandler com.azure.spring.data.cosmos.config.AbstractCosmosConfiguration.cosmosAuditingHandler)
↑     ↓
|  cosmosAuditingHandler
↑     ↓
|  (inner bean)#3d1cfad4
└─────┘

Action:

Relying upon circular references is discouraged and they are prohibited by default. Update your application to remove the dependency cycle between beans. As a last resort, it may be possible to break the cycle automatically by setting spring.main.allow-circular-references to true.

**To Reproduce**

Using "@EnableCosmosAuditing" annotation on the AppConfiguration has circular dependencies and the latest spring boot doesn't allow that.

***Code Snippet***
Add the code snippet that causes the issue.

Here is our configuration class code:

@Configuration
@EnableConfigurationProperties(CosmosProperties.class)
@EnableCosmosRepositories(basePackages = "com.nuance.powershare.messaging.repository.cosmos")
@EnableCosmosAuditing
public class CosmosClientConfig extends AbstractCosmosConfiguration {

    @Autowired
    private CosmosProperties properties;

    @Override
    public CosmosConfig cosmosConfig() {
        CosmosConfigBuilder cosmosConfigBuilder =
                        CosmosConfig.builder().enableQueryMetrics(properties.isQueryMetricsEnabled());

        if (properties.isLogResponseDiagnostics()) {
            cosmosConfigBuilder.responseDiagnosticsProcessor(new ResponseDiagnosticsProcessorImpl());
        }

        return cosmosConfigBuilder.build();
    }

    /**
     * @return cosmos db client builder
     */
    @Bean
    @DependsOn("expressionResolver")
    public CosmosClientBuilder cosmosClientBuilder() {
        CosmosClientBuilder cosmosClientBuilder = new CosmosClientBuilder();
        cosmosClientBuilder.endpoint(properties.getEndpoint()).credential(azureKeyCredential()).directMode();
        return cosmosClientBuilder;
    }

    /**
     * @return credential to connect cosmos db
     */
    @Bean
    public AzureKeyCredential azureKeyCredential() {
        return new AzureKeyCredential(properties.getKey());
    }

    @Override
    protected String getDatabaseName() {
        return properties.getDatabase();
    }

    private static class ResponseDiagnosticsProcessorImpl implements ResponseDiagnosticsProcessor {

        private static final Logger LOG = LoggerFactory.getLogger(ResponseDiagnosticsProcessorImpl.class);
        private static final String NOT_AVAILABLE = "Not Available";

		@Override
		public void processResponseDiagnostics(final ResponseDiagnostics responseDiagnostics) {
			if (responseDiagnostics != null) {
				LOG.trace("{}", responseDiagnostics.getCosmosDiagnostics());
			}
		}
	}

    @Override
    protected Collection<String> getMappingBasePackages() {
        return Collections.singletonList("xxx");
    }
}

**Expected behavior**

**Screenshots**

**Setup (please complete the following information):**
 - IDE: [e.g. IntelliJ] Eclipse 
 - Library/Libraries: [e.g. com.azure:azure-core:1.16.0 (groupId:artifactId:version)] azure-spring-data-cosmos v3.14.0
 - Java version: [e.g. 8]  8
 - App Server/Environment: [e.g. Tomcat, WildFly, Azure Function, Apache Spark, Databricks, IDE plugin or anything special] Tomcat
 - Frameworks: [e.g. Spring Boot, Micronaut, Quarkus, etc]  Spring Boot

If you suspect a dependency version mismatch (e.g. you see `NoClassDefFoundError`, `NoSuchMethodError` or similar), please provide
- verbose dependency tree (`mvn dependency:tree -Dverbose`)
  
**Additional context**

**Information Checklist**
Kindly make sure that you have added all the following information above and checkoff the required fields otherwise we will treat the issuer as an incomplete report
- [ ] Bug Description Added
- [ ] Repro Steps Added
- [ ] Setup information Added

**Comment by joshfree** [comment]
@backwind1233 could you please follow up with @svankamamidi1?

**Comment by backwind1233** [comment]
@samvaity Thanks for reaching us, I can reproduce your issue,
as you can see in the [changelog](https://github.com/Azure/azure-sdk-for-java/blob/main/sdk/cosmos/azure-spring-data-cosmos/CHANGELOG.md#3110-2021-09-09),
I think the spring boot 2.6.1 is not compatible with azure-spring-data-cosmos v3.14.0;
Hi @kushagraThapar, could you please look into this issue?

**Comment by saragluna** [comment]
@backwind1233 we need to make sure whether this will block our Spring Cloud Azure 4.0 GA.

**Comment by backwind1233** [comment]
> @backwind1233 we need to make sure whether this will block our Spring Cloud Azure 4.0 GA since we're targeting Spring Boot 2.6.

@saragluna I will check and handle this.

**Comment by kushagraThapar** [comment]
@backwind1233 @saragluna @svankamamidi1 - We don't support Spring Boot 2.6.x currently with `azure-spring-data-cosmos` SDK - This is work in progress on this PR - https://github.com/Azure/azure-sdk-for-java/pull/25626

Once we upgrade to spring boot 2.6.x, then we should be good. 
@svankamamidi1  - please check back in few weeks for updates on support of spring boot 2.6.x

**Comment by xinlian12** [comment]
PR has merged and the fix will be released by the end of this week.
