### ISSUE TITLE
serivcebus  this.binderAwareChannelResolver.resolveDestination(channelName),How can I catch errors sent asynchronously

### ISSUE THREAD

**Issue by huangdezhou008** [Azure/azure-sdk-for-java#25753]
springcloud stream servicebus ,
When I call his.binderAwareChannelResolver.resolveDestination(channelName), it always get the result TRUE,
How can I catch errors sent asynchronously

![image](https://user-images.githubusercontent.com/16448968/144039692-ab9bcb07-7c94-42fb-aa89-f74d05359d7f.png)

**Comment by joshfree** [comment]
@yiliuTo could you please follow up with @huangdezhou008?

**Comment by huangdezhou008** [comment]
@yiliuTo  can you help me to catch errors sent asynchronously

**Comment by saragluna** [comment]
@huangdezhou008, could you please share a minimal sample for us to reproduce your issue?

**Comment by huangdezhou008** [comment]
@saragluna  https://gitee.com/Huangdezhou/two , this is my sample  for you to see

**Comment by saragluna** [comment]
@huangdezhou008 you could use the error channel (https://docs.spring.io/spring-cloud-stream/docs/3.1.2/reference/html/spring-cloud-stream.html#polled-errors) to catch the errors. And when set the sync to true, it will send the message synchronously. 

And I recommend you use this version, **2.6.0**, for the azure-spring-cloud-stream-binder-servicebus-queue. And there's no need to include this `spring-integration-azure-core` dependency. Refer to this [sample](https://github.com/Azure-Samples/azure-spring-boot-samples/tree/azure-spring-boot_3.6/servicebus/azure-spring-cloud-sample-servicebus-queue-binder) for the dependency details.

**Comment by huangdezhou008** [comment]
@saragluna 1.When testing, how can I simulate the error of sending data asynchronously

**Comment by huangdezhou008** [comment]
2. @StreamListener  Is it suitable for capturing error messages sent by producers

**Comment by saragluna** [comment]
@huangdezhou008 how about trying with sending to a non-existing queue, I'm not sure whether this will work, but maybe something like this.

**Comment by huangdezhou008** [comment]
localQueueOutputChannel:
          destination: paasse-queue
          binder: queue-binder
          #sdfsdfsdfds
          producer:
            errorChannelEnabled: true

**Comment by huangdezhou008** [comment]
localTopicInputChannel:
          destination: paasse-topic
          group: paasse-sub

**Comment by huangdezhou008** [comment]
@ServiceActivator(inputChannel = "paasse-queue.my-group.errors")
    public void handleError3(ErrorMessage message) {
        Throwable throwable = message.getPayload();
        log.error("截获异常", throwable);

        Message<?> originalMessage = message.getOriginalMessage();
        assert originalMessage != null;

        log.info("原始消息体 = {}", new String((byte[]) originalMessage.getPayload()));
    }


    @StreamListener("errorChannel")
    public void error33(Message<?> message) {
        ErrorMessage errorMessage = (ErrorMessage) message;
        System.out.println("Handling ERROR: " + errorMessage);
    }

**Comment by huangdezhou008** [comment]
@saragluna   
![image](https://user-images.githubusercontent.com/16448968/144608524-44555262-63f6-4a99-9502-ac922fbcb20e.png)

**Comment by saragluna** [comment]
@huangdezhou008 does this mean it's not working? How about disconnecting from the network?

**Comment by saragluna** [comment]
> 

Spring Cloud Stream deprecated the StreamListener in favor of annotation-based programming model, check it here https://docs.spring.io/spring-cloud-stream/docs/3.1.2/reference/html/spring-cloud-stream.html#spring-cloud-stream-preface-notable-deprecations. And for the choice between @ServiceActivator and @StreamListener could refer to this doc https://docs.spring.io/spring-cloud-stream/docs/Brooklyn.SR1/reference/htmlsingle/#_using_streamlistener_for_automatic_content_type_handling.

**Comment by huangdezhou008** [comment]
@saragluna  can you  Provides a complete example of asynchronous sending to catch producer exceptions

**Comment by huangdezhou008** [comment]
@saragluna  我猜你提供的 @serviceactivator 只能捕获消费者的异常，不能捕获生产者的异常

**Comment by huangdezhou008** [comment]
@saragluna  this is my problem ,https://stackoom.com/question/4ZGpx

**Comment by huangdezhou008** [comment]
@joshfree  @yiliuTo @archerzz

**Comment by saragluna** [comment]
@huangdezhou008 https://github.com/Azure-Samples/azure-spring-boot-samples/pull/109/files please check this.

**Comment by huangdezhou008** [comment]
pls see the cod 
![image](https://user-images.githubusercontent.com/16448968/145056422-205d0c2f-c793-4de9-90fb-abb0907d16e5.png)

**Comment by saragluna** [comment]
@yiliuTo please help with this.

**Comment by huangdezhou008** [comment]
@yiliuTo  @joshfree  @archerzz  pls help me

**Comment by huangdezhou008** [comment]
long time no reply

**Comment by yiliuTo** [comment]
Hi @huangdezhou008 , sorry for the late response. The reason why the error channel doesn't work with the `BinderAwareChannelResolver` in your code is that, when you use BinderAwareChannelResolver to send messages instead of function-based programming model, the configuration of an [output](https://gitee.com/Huangdezhou/streamdemo3/blob/master/servicebusnotwork/src/main/resources/application.yml#L10) binding won't work with the message channel created by the `BinderAwareChannelResolver` bean, so the error-channel-enabled configuration doesn't take effect. 

To make it work, you could modify the binding name from "output" to the name of the channel your BinderAwareChannelResolver created. Also another simple solution is to use the default configuration which will work for all channels: `spring.cloud.stream.default.producer.error-channel-enabled`, in this way you could remove the configuration of an [output](https://gitee.com/Huangdezhou/streamdemo3/blob/master/servicebusnotwork/src/main/resources/application.yml#L10) binding. You could choose the one that fits you.

**Comment by huangdezhou008** [comment]
thanks,  It's been proven to be successful
