### ISSUE TITLE
[BUG] azure-storage-blob version 12.1.0 is missing

### ISSUE THREAD

**Issue by kirankbs** [Azure/azure-sdk-for-java#25754]
**Describe the bug**
azure-storage-blob version 12.1.0 is missing here: https://repo1.maven.org/maven2/com/azure/azure-storage-blob/

**Expected behavior**
Version 12.1.0 should exist at https://repo1.maven.org/maven2/com/azure/azure-storage-blob/

**Screenshots**
<img width="1706" alt="Screenshot 2021-11-30 at 17 23 38" src="https://user-images.githubusercontent.com/13703522/144087082-8a3249bb-a5b6-4370-bfdc-877554a9d7b2.png">

**Setup (please complete the following information):**
 - OS: Mac OS
 - Library/Libraries: [e.g. com.azure:azure-storage-blob:12.1.0 (groupId:artifactId:version)]
 - App Server/Environment: Desktop Machine
 - Frameworks: SBT Build tool

  
**Additional context**
Running SBT build tool locally complaining that `azure-storage-blob` version 12.1.0 is missing here: https://repo1.maven.org/maven2/com/azure/azure-storage-blob/. So we are unable to build the project as dependency is missing.

Below is the error report
![Build error](https://user-images.githubusercontent.com/13703522/144091039-5bf574c7-17ee-4d39-82b4-29ea80e71de6.png)

**Comment by joshfree** [comment]
@amishra-dev could you please follow up with @kirankbs?

**Comment by amishra-dev** [comment]
Hi @kirankbs (Kiran),
We discovered an issue in older versions listed below of the SDKs for Storage which we have removed from Maven. To upgrade to the latest version please change the dependency version in your pom.xml to a newer one listed below. We strongly recommend moving to the latest SDK if you are using any of these affected versions.

If you need to use an older Azure Storage REST API version, please read the sample here about using an older Service Version with a newer SDK. We apologize for the inconvenience this may have caused.

| SDK                         	| Versions Removed 	| Recommended Version 	|
|-----------------------------	|------------------	|---------------------	|
| Azure Storage Blob          	| 12.0 to 12.6.1   	| 12.14.1               	|
| Azure Storage File Datalake 	| 12.0 to 12.1.2   	| 12.7.1                	|
| Azure Storage File Share    	| 12.0 to 12.4.1   	| 12.11.1              	|

 

If you need further help
please create a ticket at aka.ms/azsupt.

Issue Type: Technical
Service Type: Blob Storage
Summary: #JavaSDKv12
Problem type: Development
Problem subtype: Client library or SDK

**Comment by bernardpletikosa** [comment]
@amishra-dev In your [guidelines](https://azure.github.io/azure-sdk/java_introduction.html#java-principles) it states:
> Dependable
> - 100% backward compatible

This is not true in the current case for 2 different reasons:
- library is completely removed, so we can't go back or develop locally with the current version as is doesn't exist.
- updating to 12.14.1, which is a **minor** bump, introduces a new constructor, which means a breaking change.

As you also state in the guidelines:

> Consistent
> - All differences from the guidelines must have good reasons.

I assume there is a serious issue that you are trying to manage and you have a good reason for that.
I'm interested in what's being done for these situations not to happen again?
