### ISSUE TITLE
 HttpClientProviders does not load under Karaf

### ISSUE THREAD

**Issue by bcshores** [Azure/azure-sdk-for-java#25769]
**Describe the bug**
I'm attempting to use Azure Blob Storage in a Karaf application.  My code is part of a kar deploy file, so it has it's own features and plugins associated.  Because of the setup, I need to deploy by dependencies as part of my .kar file.  That's all standard enough, problem is they get loaded in as plugins.  When  HttpClientProviders (azure-core) is called from azure-storage-blob code, it uses the ClassLoader to look for an HttpClientProvider.  Unfortunately each plugin in Karaf(and OSGI I assume) has it's own classloader.   That means my azure-core is under one plugin, azure-storage-blob is under another, and azure-core-http-netty(my http provider) is under a 3rd.  They cannot share the same classloader (thanks OSGI) so they can't see each other.   Since HttpClientProviders is final and from how it's written, I have failed to find any way to extend or override this so that I can just point it directly to mine.  This means I can't do azure blob from inside karaf.  At least, I haven't found any way around that.

***Exception or Stack Trace***
Caused by: java.lang.IllegalStateException: A request was made to load the default HttpClient provider but one could not be found on the classpath. If you are using a dependency manager, consider including a dependency on azure-core-http-netty or azure-core-http-okhttp. Depending on your existing dependencies, you have the choice of Netty or OkHttp implementations. Additionally, refer to https://aka.ms/azsdk/java/docs/custom-httpclient to learn about writing your own implementation.
at com.azure.core.implementation.http.HttpClientProviders.createInstance(HttpClientProviders.java:37)
at com.azure.core.http.HttpClient.createDefault(HttpClient.java:27)
at com.azure.core.http.HttpPipelineBuilder.build(HttpPipelineBuilder.java:60)
at com.azure.storage.blob.implementation.util.BuilderHelper.buildPipeline(BuilderHelper.java:110)
at com.azure.storage.blob.BlobServiceClientBuilder.buildAsyncClient(BlobServiceClientBuilder.java:107)
at com.azure.storage.blob.BlobServiceClientBuilder.buildClient(BlobServiceClientBuilder.java:84)

**To Reproduce**
Create a karaf application.  Load up bundles for the azure storage, attempt to push a file up to azure storage.

***Code Snippet***
Just dropping in my blob service client.  It's at the client initialization it all blows up.

  BlobServiceClient blobServiceClient = new BlobServiceClientBuilder()
					.connectionString(storageConnectionString)
					.buildClient();
  BlobContainerClient blobContainer = blobServiceClient.getBlobContainerClient("datacapturelogs");
  BlobClient client = blobContainer.getBlobClient(file.getName());
 
  Map<String, String> map = new HashMap<>();
  map.put("Client", "Client");
  ByteArrayInputStream bis = retrieveByteArrayInputStream(file);
  BlockBlobSimpleUploadOptions options = new BlockBlobSimpleUploadOptions(bis,file.length()).setTags(map);
  client.getBlockBlobClient().uploadWithResponse(options, null, Context.NONE);

**Expected behavior**
I expect it to push up the file like it does from a standard java application when testing.

**Screenshots**

**Setup (please complete the following information):**
 - IDE: [e.g. IntelliJ]
 - Library/Libraries: [e.g. com.azure:azure-core:1.16.0 (groupId:artifactId:version)]
 - Java version: [e.g. 8] 
 - App Server/Environment: [e.g. Tomcat, WildFly, Azure Function, Apache Spark, Databricks, IDE plugin or anything special]
 - Frameworks: [e.g. Spring Boot, Micronaut, Quarkus, etc] 
Windows 2012 ( I know.. old ).  Java 8.  Ran on both the 1.15.0 azure-core and the 1.21.0, since the logic changed a bit between those.  Matching other azure libraries with these of course, but the core problem is in azure-core.  Running under Karaf.

If you suspect a dependency version mismatch (e.g. you see `NoClassDefFoundError`, `NoSuchMethodError` or similar), please provide
- verbose dependency tree (`mvn dependency:tree -Dverbose`)
  
**Additional context**

**Information Checklist**
Kindly make sure that you have added all the following information above and checkoff the required fields otherwise we will treat the issuer as an incomplete report
- [ ] Bug Description Added
- [ ] Repro Steps Added
- [ ] Setup information Added

**Comment by bcshores** [comment]
Of course as soon as I create this, I decide to dig back into the BlobServiceClientBuilder and found the call below.  That let me just set the client myself and got me to move on.  Might be good to mention that in the error as an alternative.

https://docs.microsoft.com/en-us/java/api/com.azure.storage.blob.blobserviceclientbuilder.httpclient?view=azure-java-stable#com_azure_storage_blob_BlobServiceClientBuilder_httpClient_com_azure_core_http_HttpClient_

**Comment by srnagar** [comment]
@bcshores thanks for reporting this issue and suggesting improvements to the error message. We will add a note to use the `HttpClient` setter method on the builder when the classloader cannot find the HttpClient. 

As a side note, this PR tried to address a similar issue - https://github.com/Azure/azure-sdk-for-java/pull/20760 but it looks like the classloader for every jar is different and hence classloader for azure-core is not the same as azure-core-http-netty. So, using the same classloader as the one that loaded `HttpClientProviders` is not going to fix this issue. 

The alternative is to do what you did by setting the HttpClient on the builder.

**Comment by bcshores** [comment]
I'm not sure if it's related, but my developer(to remain unnamed) also had my using the Java 12 approach when I'm running Java 8.  It seems to still work in Java 8 in some spots, but the combo of that and Karaf led to more http protocol type errors.  Flipped back to old Java 8 cloud storage api and it's working easily and it's more of an "All in one" depenedency.  I still think this is a problem and will probably come back to get me in a year or so when we get this system updated.
