### ISSUE TITLE
Update documentation to use new library with latest version instead of deprecated old library

### ISSUE THREAD

**Issue by almothafar** [Azure/azure-sdk-for-java#25816]
Dependency should be updated to use `msal4j` instead of `adal4j`, as when you go to https://github.com/AzureAD/azure-activedirectory-library-for-java you will see a clear note about moving to `msal4j`:

> This library, ADAL for Java, will no longer receive new feature improvements. Instead, use the new MSAL4J.

![image](https://user-images.githubusercontent.com/13887564/144753452-b0d4afd1-bddb-4862-8236-d265fd4f030f.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0ef86d5e-7950-e398-a7ed-4b5902109c40
* Version Independent ID: e484d54c-8c14-db0a-1516-69cf0710061c
* Content: [Azure Active Directory libraries for Java](https://docs.microsoft.com/en-us/java/api/overview/azure/activedirectory?view=azure-java-stable)
* Content Source: [docs-ref-services/latest/activedirectory.md](https://github.com/Azure/azure-docs-sdk-java/blob/master/docs-ref-services/latest/activedirectory.md)
* Product: **azure**
* Technology: **azure**
* GitHub Login: @ramya-rao-a
* Microsoft Alias: **ramyar**

**Comment by chenrujun** [comment]
I'm not responsible for this repo: https://github.com/AzureAD/azure-activedirectory-library-for-java 

I just share a information here:
I found that there is no need to use `adal` or `masl` if you want to use Azure Active Directory in Spring Boot application.
I already finished some samples here: https://github.com/Azure-Samples/azure-spring-boot-samples/tree/9c271d8789651a5119792a320a03fad8d1018dfd/aad/spring-security

Now these samples can not cover all secnarios, I created a issue to list all scenarios: https://github.com/Azure/azure-sdk-for-java/issues/25817

(cc: @stliu , @seanli1988 , FYI.)

**Comment by joshfree** [comment]
Closing this issue.   It does not make sense to change the legacy ADAL library to use MSAL under the hood.
