### ISSUE TITLE
How to add a callback function after a producer sends a message asynchronously

### ISSUE THREAD

**Issue by huangdezhou008** [Azure/azure-sdk-for-java#25826]
**Query/Question**

How to add a callback function after a producer sends a message asynchronously

***Why is this not a Bug or a feature Request?***
https://gitee.com/Huangdezhou/two

**Comment by joshfree** [comment]
@conniey could you follow up with @huangdezhou008 on their question?

@huangdezhou008 you can see the getting started guide here: https://docs.microsoft.com/en-us/java/api/overview/azure/messaging-eventhubs-readme?view=azure-java-stable

**Comment by conniey** [comment]
Can you provide some more context? I tried to look through your repo, but I'm not sure what I am looking for. Project Reactor provides many ways to chain operators after the ServiceBusSenderAsyncClient.sendMessages() completes.

**Comment by huangdezhou008** [comment]
@conniey  I want to pass a callback function to sendCallback after the producer sends the asynchronous message to get the callback result of the asynchronous message

**Comment by huangdezhou008** [comment]
![image](https://user-images.githubusercontent.com/16448968/144973622-736a4fc2-3d5f-4bf2-98ae-7faa812de295.png)

**Comment by huangdezhou008** [comment]
![image](https://user-images.githubusercontent.com/16448968/144973666-c7ecdf98-49ae-473d-8ab3-ab0959465d11.png)

**Comment by huangdezhou008** [comment]
![image](https://user-images.githubusercontent.com/16448968/144973711-00ae5271-495c-45af-84d4-4d09c4a060b8.png)

**Comment by huangdezhou008** [comment]
@conniey pls look my picture

**Comment by conniey** [comment]
@huangdezhou008 

There are multiple ways to accomplish this using Project Reactor. Here is an example below. There is a learning curve to utilising Project Reactor (https://projectreactor.io/docs/core/release/reference/ and https://projectreactor.io/learn). There are some helper methods like [`Mono.toFuture()`](https://projectreactor.io/docs/core/release/api/reactor/core/publisher/Mono.html#toFuture--) or [`Mono.fromFuture()`](https://projectreactor.io/docs/core/release/api/reactor/core/publisher/Mono.html#fromFuture-java.util.concurrent.CompletableFuture-)

```java
private ListenableFutureCallback<Void> sendCallback;

private Mono<Void> doSomething() {
    // If sendMessages is successful, it will call the .then() operator.
    // otherwise, the error is propagated down to .onErrorResume.
    return sendMessages().then(Mono.<Void>fromRunnable(() -> sendCallback.onSuccess(null)))
            .onErrorResume(error -> {
                return Mono.fromRunnable(() -> sendCallback.onFailure(error));
            });
}
```

**Comment by huangdezhou008** [comment]
@conniey   ，/unresolve
 
Your answer is not what I want to know，What I want to ask is how to set the callback with cloud stream servicebus

**Comment by huangdezhou008** [comment]
@conniey  can you help me ?
