### ISSUE TITLE
[FEATURE REQ] Fetch Workspace Id and its primary key for a Log Analytics workspace 

### ISSUE THREAD

**Issue by anshulsarda3** [Azure/azure-sdk-for-java#25821]
**Is your feature request related to a problem? Please describe.**
I wanted to create a Log Analytics Workspace, a Virtual Machine, and connect this newly created virtual machine as a data source to the created Log Analytics workspace dynamically using Azure Java SDK. We need to get the workspace ID and workspace key to connect the VM as the data source to Log Analytics Workspace. Currently, there is no provisioning in azure java SDK to get these dynamically using SDK.

**Describe the solution you'd like**
It would be much appreciated if there is a provision made such that we can get the workspace Id and workspace key when we fetch the workspace details. 

**Additional context**
Currently, this is not possible as we need to get workspace Id and Workspace key from the agent management section under a Log Analytics workspace resource from the Azure portal.

![image](https://user-images.githubusercontent.com/10928494/144792031-9709f2cd-4bb6-4f79-94f1-08077beb85d9.png)

**Information Checklist**
Kindly make sure that you have added all the following information above and checkoff the required fields otherwise we will treat the issuer as an incomplete report
- [x] Description Added
- [x] Expected solution specified

**Comment by weidongxu-microsoft** [comment]
@anshulsarda3 
Please try loganalytics lib.
https://github.com/Azure/azure-sdk-for-java/tree/main/sdk/loganalytics/azure-resourcemanager-loganalytics

I think you can get the ID via `manager..workspaces().list()` (I assume it is in some field, if not the `id`), and keys via `manager.sharedKeysOperations().getSharedKeys(..)`.

Let me know if it works.

**Comment by anshulsarda3** [comment]
Ok sure. I will try it out.

**Comment by anshulsarda3** [comment]
```
manager.workspaces().list() 
manager.sharedKeysOperations().getSharedKeys(..)
```
The data I was looking for can be fetched via the above methods.
Thanks @weidongxu-microsoft
