### ISSUE TITLE
Update samples after 4.0 released.

### ISSUE THREAD

**Issue by chenrujun** [Azure/azure-sdk-for-java#25828]
1. Update version in `dependencyManagement` section in parent pom.
2. Delete unnecessary `dependencyManagement` in child poms. For example: contents included by this PR: https://github.com/Azure-Samples/azure-spring-boot-samples/pull/108

**Comment by saragluna** [comment]
@backwind1233 can we close this issue now?

**Comment by saragluna** [comment]
Closing in favor of https://github.com/Azure/azure-sdk-for-java/issues/25651.
