### ISSUE TITLE
[QUERY] Cosmos DB Best way to handle sorting by undefined field

### ISSUE THREAD

**Issue by zhoujia1974** [Azure/azure-sdk-for-java#25855]
**Query/Question**
We have a UI grid based on a document as below.

> {
    "id": "1",
    "partitionKey": "aa",
    "columns": {
        "Discount": {
            "value": {
                    "type": "percent",
                    "value": 0.01
                },
            }
        },
        "Price": {
            "value": {
                "type": "monetary",
                "value": 5.31,
            }
        },
        "currency": {
            "value": {
                "type": "string",
                "value": "USD"
            }
        }
    }
}

The application is a multi-tenant app. Each tenant can define their own set of columns. The number of columns for a tenant can get to more than 100. The column may not have a value. Currently to save the storage space, no value will not be included in the json stored in db. 
The UI grid support filters and sort on columns. Filters can be applied to multiple columns. But sort can only be applied on one column since we can't define a composite index for all possible scenarios of all tenants. The query is similar to below.

> SELECT DISTINCT c.id, c.partitionKey, c.columns FROM c JOIN i IN c.columns WHERE c.partitionKey = 'aa' ORDER BY c.columns['Price']['value']['value']

The issue we are facing is that this query will only return the documents that containing a value for the sort column. Some rows will disappear from the UI grid when user sort a column compare to not sort a column.

I have tried one approach to workaround this. I use two separate queries, one for documents with the column defined, the other for documents with the column undefined. I managed the switch of these two queries in my persistence layer. But the query for undefined column is extremely inefficient compared to defined query when using 'AND NOT IS_DEFINED()' versus 'AND IS_DEFINED()) in the WHERE clause. The statistics show a 24 RU vs 3 RU cost.

The other two options I can think of: 
1. add index for each possible column, but since the column names is not predefined, the index can't be predefined. One way to address this is that I will generate a id for each column (such as c1, c2, c3, etc.) and then use id as columns map key. Then I can predefine the index. But even with this approach I still need to define hundreds of indexes since the potential number of column ids can reach to hundreds.
2. let each document to include all columns that with/out values. This way the default index can include all columns and the sort will work on the column without values. But this means the document size will potentially increase a lot due to wasted spaces for columns without values.

Please kindly advise what is the best approach I should take to proceed. Also is there any plan to enhance the index to support undefined fields in sorting?

***Why is this not a Bug or a feature Request?***
A clear explanation of why is this not a bug or a feature request?

**Setup (please complete the following information if applicable):**
 - OS: [windows, *nix]
 - IDE: [eclipse]
 - Library/Libraries: [com.azure.spring:azure-spring-boot-starter-cosmos:3.6.0]
 
 **Information Checklist**
 Kindly make sure that you have added all the following information above and checkoff the required fields otherwise we will treat the issuer as an incomplete report
- [ X] Query Added
- [ X] Setup information Added

**Comment by joshfree** [comment]
Hi @zhoujia1974 thank you for posting this github issue.  An expert from the `Cosmos DB` SDK team will follow up with you shortly!

**Comment by kushagraThapar** [comment]
Investigating this issue!

**Comment by simplynaveen20** [comment]
Reached out to query engine team , will answer soon

**Comment by simplynaveen20** [comment]
Comment from query team - 
"Support for sorting on undefined fields is something that can be enabled, provided you are using version 4.13 (or newer) of the java sdk.  To have this enabled, please open a support ticket, requesting a configuration change to allow undefined in order by.  You will need to specify the account name(s) on which to make this change.
Eventually the plan is to make this the default behavior, but right now it must be explicitly enabled."
