### ISSUE TITLE
Class navigation button does nothing

### ISSUE THREAD

**Issue by RickWinter** [Azure/azure-sdk-for-java#25861]
Java docs have a class navigation button that doesn't work.  Would be nice to have the button do what the help says it will

```
Class/Interface
Each class, interface, nested class and nested interface has its own separate page. Each of these pages has three sections consisting of a class/interface description, summary tables, and detailed member descriptions:

Class inheritance diagram
Direct Subclasses
All Known Subinterfaces
All Known Implementing Classes
Class/interface declaration
Class/interface description
Nested Class Summary
Field Summary
Constructor Summary
Method Summary
Field Detail
Constructor Detail
Method Detail
```

For reference its the header `CLASS` shown in the image
![image](https://user-images.githubusercontent.com/4430337/145090463-a4e8a648-c3b7-4287-beae-5ece1a3866d6.png)

**Comment by alzimmermsft** [comment]
Closing as this is how Javadocs work. What you're seeing is the `Overview`, `Package`, and `Class` are an only one can be active at once.

`Overview` shows the entire overview of the Javadocs, normally this is either all modules or packages in the Javadocs.

`Package` shows information about a specific package, normally this is all the classes in the package.

`Class` shows information about a specific class, this is the fields, constructors, and methods of the class.

`Class` is only available when you've selected a specific class.
