### ISSUE TITLE
Service is Certificates not Certificate

### ISSUE THREAD

**Issue by RickWinter** [Azure/azure-sdk-for-java#25862]
The service should be plural:
https://azuresdkdocs.blob.core.windows.net/$web/java/azure-security-keyvault-certificates/4.2.5/com/azure/security/keyvault/certificates/CertificateServiceVersion.html

This string has a missing `s` on Certifcate
The versions of Azure Key Vault Certificate supported by this client library.

**Comment by alzimmermsft** [comment]
This would require making a breaking change to the Certificates library, as it would require renaming a class in the public API

**Comment by RickWinter** [comment]
Ok, closing since the docs represent the Stable version that shipped which can't be changed
