### ISSUE TITLE
[BUG] The Maven package page refers to the Search package with track1 terminology

### ISSUE THREAD

**Issue by Mohit-Chakraborty** [Azure/azure-sdk-for-java#25872]
**Describe the bug**
The [Maven package page](https://search.maven.org/artifact/com.azure/azure-search-documents) refers to the Search package with track1 terminology - 
  _Microsoft Azure Cognitive Search client for Java
  This package contains client functionality for Microsoft Azure Cognitive Search_

**Comment by alzimmermsft** [comment]
This is actually the guideline for Maven descriptions in Track 2 libraries

https://azure.github.io/azure-sdk/java_introduction.html#java-maven-name
