### ISSUE TITLE
Use spring-cloud-azure-starter-keyvault-certificates:4.x in TLS sample repo

### ISSUE THREAD

**Issue by chenrujun** [Azure/azure-sdk-for-java#25880]
### Context

TLS sample repo: https://github.com/Azure-Samples/spring-boot-secure-communications-using-end-to-end-tls-ssl

### Problem
After spring-cloud-azure-starter-keyvault-certificates:4.x support the TLS feature, above sample will be outdated.

## Goal
Use `spring-cloud-azure-starter-keyvault-certificates:4.x` instead of `azure-spring-boot-starter-keyvault-certificates:3.x`.

**Comment by stliu** [comment]
closing in favor of #28243
