### ISSUE TITLE
[BUG] Retrieving inner class with '.' instead of '$'

### ISSUE THREAD

**Issue by fnumrich** [Azure/azure-sdk-for-java#25899]
**Describe the bug**
In `com.azure.core.implementation.jackson.MemberNameConverterImpl` the static initializer code tries to find the inner class `com.fasterxml.jackson.databind.introspect.AccessorNamingStrategy$Provider` by using `Class.forName(...)`.
But the name of the inner class is wrongly constructed. Instead of:
`com.fasterxml.jackson.databind.introspect.AccessorNamingStrategy$Provider`
it is constructed with a dot (`.`):
`com.fasterxml.jackson.databind.introspect.AccessorNamingStrategy.Provider`

Since inner classes are always accessed via a dollar sign, the usage of the dot leads to an `java.lang.ClassNotFoundException`. 
This in turn leads to `"Failed to retrieve MethodHandles used to get naming strategy. Falling back to BeanUtils."`

***Exception or Stack Trace***
```
17:45:23.341 [main] INFO com.azure.core.implementation.jackson.JacksonVersion - Package versions: jackson-annotations=2.12.5, jackson-core=2.12.5, jackson-databind=2.12.5, jackson-dataformat-xml=2.12.5, jackson-datatype-jsr310=2.12.5, azure-core=1.22.0, Troubleshooting version conflicts: https://aka.ms/azsdk/java/dependency/troubleshoot
17:45:23.669 [main] DEBUG com.azure.core.implementation.jackson.MemberNameConverterImpl - Failed to retrieve MethodHandles used to get naming strategy. Falling back to BeanUtils.
java.lang.ClassNotFoundException: com.fasterxml.jackson.databind.introspect.AccessorNamingStrategy.Provider
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:581)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:178)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:522)
	at java.base/java.lang.Class.forName0(Native Method)
	at java.base/java.lang.Class.forName(Class.java:315)
	at com.azure.core.implementation.jackson.MemberNameConverterImpl.<clinit>(MemberNameConverterImpl.java:55)
	at com.azure.core.implementation.jackson.ObjectMapperShim.<init>(ObjectMapperShim.java:139)
	at com.azure.core.implementation.jackson.ObjectMapperShim.createHeaderMapper(ObjectMapperShim.java:127)
	at com.azure.core.util.serializer.JacksonAdapter.<init>(JacksonAdapter.java:80)
	at com.azure.core.util.serializer.JacksonAdapter.<init>(JacksonAdapter.java:58)
	at com.azure.core.util.serializer.JacksonAdapter$SerializerAdapterHolder.<clinit>(JacksonAdapter.java:113)
	at com.azure.core.util.serializer.JacksonAdapter.createDefaultSerializerAdapter(JacksonAdapter.java:122)
	at com.azure.core.implementation.serializer.DefaultJsonSerializer.<init>(DefaultJsonSerializer.java:24)
	at com.azure.core.util.serializer.JsonSerializerProviders.createInstance(JsonSerializerProviders.java:57)
	at com.azure.core.util.BinaryData.<clinit>(BinaryData.java:172)
    ...
```
**To Reproduce**
Just run this code ...
```
import com.azure.core.util.BinaryData;  
  
public class ClassForNameTest {  
    public static void main(String[] args) {  
       BinaryData.fromBytes("Test".getBytes());  
  }  
}
```

***Code Snippet***
This is the respective code that causes the error.
```
final class MemberNameConverterImpl implements MemberNameConverter {
   ...
   private static final String ACCESSOR_NAMING_STRATEGY = "com.fasterxml.jackson.databind.introspect.AccessorNamingStrategy";
   private static final String ACCESSOR_NAMING_STRATEGY_PROVIDER = ACCESSOR_NAMING_STRATEGY + ".Provider";
   ...
   Class<?> accessorNamingStrategyProviderClass = Class.forName(ACCESSOR_NAMING_STRATEGY_PROVIDER);
   ...
} 
```
**Expected behavior**
The class `com.fasterxml.jackson.databind.introspect.AccessorNamingStrategy$Provider` which is available on the classpath can be found without an *ClassNotFound* exception.

**Screenshots**
 
**Setup:**
 - OS: Ubuntu 20.04.2.LTS (but independent)
 - IDE: IntelliJ (but independent)
 - Library/Libraries: com.azure:azure-core:1.23.0 
 - Java version: 11
 - App Server/Environment: ---
 - Frameworks: Spring Boot 2.5.6

**Additional context**

**Information Checklist**
Kindly make sure that you have added all the following information above and checkoff the required fields otherwise we will treat the issuer as an incomplete report
[X] Bug Description Added
[X] Repro Steps Added
[X] Setup information Added

**Comment by joshfree** [comment]
@lmolkova could you please take a look?

**Comment by alzimmermsft** [comment]
This was fixed recently in #25840

**Comment by fnumrich** [comment]
Great to hear that this is already fixed! 
Should I close this issue or is there away to mark it as duplicate?

**Comment by fnumrich** [comment]
Is there already a plan when this fix will be available in a public version?

**Comment by lmolkova** [comment]
@fnumrich thanks for reporting it!
we're going to release the fix early in Jan. Is my understanding correct that you noticed this problem in logs and don't have a related runtime issue?

**Comment by fnumrich** [comment]
@lmolkova you're right. This ja just a log warning after that there's a fallback:
"Failed to retrieve MethodHandles used to get naming strategy. Falling back to BeanUtils."
There's ni runtime issue.

**Comment by lmolkova** [comment]
Closing this as it should be fixed in the latest release.

**Comment by PbALpi7xEX** [comment]
When is this being released publicly? Currently using latest azure-spring-boot-bom v3.12.1 which pulls in azure-core 1.23.1 but that version is still using the incorrect inner class reference.

Also pulling latest azure-spring-cloud-dependencies BOM v 2.12.0.. which pulls in older azure-core v1.22.0... 

Causing a runtime exception for me, connection to app configuration fails and spring boot fails to start.
