### ISSUE TITLE
[BUG] azure-storage-blob-nio: Calls to AzureFileSystemProvider/extractAccountEndpoint log spurious errors

### ISSUE THREAD

**Issue by ejschoen** [Azure/azure-sdk-for-java#25900]
**Describe the bug**
Calls to `AzureFileSystemProvider.extractAccountEndpoint` with a legal URI containing a legal and correct endpoint parameter cause a spurious ERROR to be logged.  This is confusing and raises false positive alarms on deployments using observability tooling that are sensitive to ERROR severity log messages.

***Exception or Stack Trace***
```clojure
cli=> (.getFileSystem prov (java.net.URI. "azb://?endpoint=https://foo.blob.core.windows.net"))
2021-12-08T16:58:45.393Z  ERROR [com.azure.storage.blob.nio.AzureFileSystemProvider:265] - URI does not contain an "endpoint=" parameter. FileSystems require a URI of the format "azb://?endpoint=<endpoint>"
#object[com.azure.storage.blob.nio.AzureFileSystem 0x15de2902 "com.azure.storage.blob.nio.AzureFileSystem@afff146d"]
```

**To Reproduce**
Call getFileSystem on an `AzureFileSystemProvider` with a URI containing an endpoint= query parameter

***Code Snippet***
```clojure
(.getFileSystem (java.nio.file.FileSystems/getFileSystem 
                               (java.net.URI. "azb://?endpoint=https://foo.blob.core.windows.net"))
                            (java.net.URI. "azb://container:/path/to/file?endpoint=https://foo.blob.core.windows.net"))
```
where foo.blob.core.windows.net needs to be replaced by an actual endpoint.

**Expected behavior**
Any call that invokes AzureFileSystemProvider.extractAccountEndpoint with a legal URI containing a legal endpoint parameter must not log an error stating that the endpoint is missing from the URI.

**Setup (please complete the following information):**
 - OS: Debian Buster
 - IDE: Emacs
 - Library/Libraries: com.azure/azure-storage-blob "12.0.0-beta.10"
 - Java version: 1.8.302
 - App Server/Environment: Clojure 1.8
 - Frameworks: 

**Additional context**
The bug here is in the value passed to Flux's switchIfEmpty method.  The value that's initialzing the Mono.error publisher is provided by LoggingUtility.logError, which logs the given IllegalArgumentException, whether or not the switch is taken.  If the exception were instead passed to Mono.error directly, rather than through the logging utility, would the exception be properly logged if the switch is taken?

```java
private String extractAccountEndpoint(URI uri) {
        if (!uri.getScheme().equals(this.getScheme())) {
            throw LoggingUtility.logError(this.logger, new IllegalArgumentException(
                "URI scheme does not match this provider"));
        }
        if (CoreUtils.isNullOrEmpty(uri.getQuery())) {
            throw LoggingUtility.logError(this.logger, new IllegalArgumentException("URI does not contain a query "
                + "component. FileSystems require a URI of the format \"azb://?endpoint=<account_endpoint>\"."));
        }

        String endpoint = Flux.fromArray(uri.getQuery().split("&"))
                .filter(s -> s.startsWith(ENDPOINT_QUERY_KEY + "="))
                .switchIfEmpty(Mono.error(LoggingUtility.logError(this.logger, new IllegalArgumentException(
                        "URI does not contain an \"" + ENDPOINT_QUERY_KEY + "=\" parameter. FileSystems require a URI "
                            + "of the format \"azb://?endpoint=<endpoint>\""))))
                .map(s -> s.substring(ENDPOINT_QUERY_KEY.length() + 1)) // Trim the query key and =
                .blockLast();

        if (CoreUtils.isNullOrEmpty(endpoint)) {
            throw LoggingUtility.logError(logger, new IllegalArgumentException("No account endpoint provided in URI"
                + " query."));
        }

        return endpoint;
    }
```

**Information Checklist**
Kindly make sure that you have added all the following information above and checkoff the required fields otherwise we will treat the issuer as an incomplete report
- [x] Bug Description Added
- [x] Repro Steps Added
- [x] Setup information Added

**Comment by joshfree** [comment]
Thanks for the detailed github issue, @ejschoen!  Someone from the  `Azure Storage` team will follow up shortly.

/cc @rickle-msft

**Comment by rickle-msft** [comment]
@ejschoen Thanks for doing the work to investigate the cause of this. Looks like you're right about the source of it. I think what we'll need to do is return a Mono.defer(logger.logException...) that way the method won't be evaluated until it needs to be if that situation ever arises. Should be an easy enough fix.
