### ISSUE TITLE
[BUG] BlobStorageResource seem to require excessive amount of REST API calls

### ISSUE THREAD

**Issue by kasobol-msft** [Azure/azure-sdk-for-java#25907]
**Describe the bug**
BlobStorageResource seems to be using excessive amount of `exists` calls. Like here:
https://github.com/Azure/azure-sdk-for-java/blob/808ef6761f969295da14a3b4780462ae32a11b8d/sdk/spring/azure-spring-boot/src/main/java/com/azure/spring/autoconfigure/storage/resource/BlobStorageResource.java#L85-L105
or
here:
https://github.com/Azure/azure-sdk-for-java/blob/808ef6761f969295da14a3b4780462ae32a11b8d/sdk/spring/azure-spring-boot/src/main/java/com/azure/spring/autoconfigure/storage/resource/BlobStorageResource.java#L108-L110
or
here:
https://github.com/Azure/azure-sdk-for-java/blob/808ef6761f969295da14a3b4780462ae32a11b8d/sdk/spring/azure-spring-boot/src/main/java/com/azure/spring/autoconfigure/storage/resource/BlobStorageResource.java#L177-L183

Every such call incurs REST API call that results in higher latency and monetary cost than what might be necessary.

Consider using conditional headers and error handling instead of checking for storage resource existence to reduce amount of transactions required to accomplish this functionality.

Related issue in Storage SDK: https://github.com/Azure/azure-sdk-for-java/issues/23658

**Comment by joshfree** [comment]
@backwind1233 @stliu could you please take a look as part of the upcoming release?

**Comment by kasobol-msft** [comment]
Another issue here is that "exist" and subsequent API call are separate transactions from service POV, so there's small chance of a race here if there's parallelism in the app using this.
