### ISSUE TITLE
[BUG] ServiceBus message batch code appears to be thread-unsafe

### ISSUE THREAD

**Issue by richardpark-msft** [Azure/azure-sdk-for-java#25910]
**Describe the bug**

The message batch in the Service Bus package has partial thread safety but is missing a lock to prevent individual threads from racing as they add messages to the internal collection:

Specifically here there's nothing that prevents two messages from both seeing there's enough space and adding to the list:
https://github.com/Azure/azure-sdk-for-java/blob/84779c9862a43ec2bf247e6a20082aa237b5f525/sdk/servicebus/azure-messaging-servicebus/src/main/java/com/azure/messaging/servicebus/ServiceBusMessageBatch.java#L119

***Exception or Stack Trace***

None

**To Reproduce**
I read the code and chatted with @anuchandy.

***Code Snippet***
(linked above)

**Expected behavior**
A lock or similar that makes sure that the size check and the add occur in the same logical operation.

**Screenshots**
N/A

**Setup (please complete the following information):**
 - OS: Windows 10
 - IDE: VSCode
 - Library/Libraries: service bus
 - Java version: N/A
 - App Server/Environment: N/A
 - Frameworks: N/A

**Additional context**
N/A

**Information Checklist**
Kindly make sure that you have added all the following information above and checkoff the required fields otherwise we will treat the issuer as an incomplete report
- [x] Bug Description Added
- [x] Repro Steps Added
- [x] Setup information Added

**Comment by anuchandy** [comment]
My thought here is not to make `tryAdd()` synchronized at all, but let the user do it if he wants to use it concurrently. For the user, it's as simple as putting `tryAdd` inside a lock block. On the other hand, if SDK synchronizes it, we're making all users pay the cost.

I agree that the current impl is incorrect.

**Comment by richardpark-msft** [comment]
This might just be down to convention. For my own education - is it typical to assume that our Java SDKs are thread-unsafe?

**Comment by liukun-msft** [comment]
Reopen to track same fix for EventHub.
