### ISSUE TITLE
[Spring Cloud Stream Support] Make sure all features are included in reference doc

### ISSUE THREAD

**Issue by chenrujun** [Azure/azure-sdk-for-java#25936]

**Comment by yiliuTo** [comment]
Done in the below prs:
https://github.com/microsoft/spring-cloud-azure/pull/829
https://github.com/microsoft/spring-cloud-azure/pull/830
https://github.com/microsoft/spring-cloud-azure/pull/831
https://github.com/microsoft/spring-cloud-azure/pull/833
https://github.com/microsoft/spring-cloud-azure/pull/834
https://github.com/microsoft/spring-cloud-azure/pull/835
https://github.com/microsoft/spring-cloud-azure/pull/837
https://github.com/microsoft/spring-cloud-azure/pull/840
