### ISSUE TITLE
undeleteWithResponse(Duration timeout, Context context) API is not working to restore soft deleted blob 

### ISSUE THREAD

**Issue by HarisinghRajputTR** [Azure/azure-sdk-for-java#25943]
**Azure blob storage SDK version:- 12.11.0-beta.3**

We have delete blob API in our application in which we call SDK's **blobClient.deleteWithResponse()** method to delete blob in storage.
Once it is deleted, it is showing with Deleted status in azure portal like as below:-

![image](https://user-images.githubusercontent.com/90780976/145448820-29a7452b-ac22-4fd2-9aef-e26bb7a4693d.png)

Now to restore deleted blob, we are calling SDK's **blobClient.undeleteWithResponse()** as per below code snippet:- 

![image](https://user-images.githubusercontent.com/90780976/145448649-34806eaf-9bcc-4fe5-816e-85d73f7dd0b1.png)

Above undeleteWithResponse() method returns 200 status code but it is not undelete/restore blob to active status again
It is still showing in Deleted status like as below:- 

![image](https://user-images.githubusercontent.com/90780976/145448820-29a7452b-ac22-4fd2-9aef-e26bb7a4693d.png)

**In next try also, undeleteWithResponse() method is not returning any exception/error. It always return 200 status code but not restoring blob in actual. It looks like there is no impact of undeleteWithResponse() on soft deleted blob**
Can you please help me into this?

FYI, In azure storage account, soft delete and versioning for blobs is already enable as like below:- 

![image](https://user-images.githubusercontent.com/90780976/145452656-5499ae20-c17a-42a3-af83-c31f3f1d2085.png)

**Comment by rickle-msft** [comment]
@HarisinghRajputTR Can you please try adding a getProperties call before and after undeleting and inspecting the deleted status there

**Comment by HarisinghRajputTR** [comment]
@rickle-msft 

> @HarisinghRajputTR Can you please try adding a getProperties call before and after undeleting and inspecting the deleted status there
Thank you for your response.
When I try getProperties call before/after undelete, it throws below error (because of blob is in deleted status):-
com.azure.storage.blob.models.BlobStorageException: Status code 404, (BlobNotFound)

**FYI, I tried undelete call with only soft delete option enable then it is working fine as per expectation.**

I refer https://docs.microsoft.com/en-us/azure/storage/blobs/versioning-overview#blob-versioning-and-soft-delete document and one thing mentioned there is like as below:-
If versioning and soft delete are both enabled for a storage account, then when you delete a blob, the current version of the blob becomes a previous version. No new version is created and no soft-deleted snapshots are created. The soft delete retention period is not in effect for the deleted blob.

So now my query is how do I restore soft deleted blob when (versioning + soft delete) both are enabled in storage account?

Can you please help me into this?
Thanks

**Comment by rickle-msft** [comment]
@HarisinghRajputTR Ah. I had missed that you have soft delete and versioning enabled. That does indeed change the behavior.

If you have versioning enabled, the way to "restore" a deleted blob is to copy the snapshot back onto the base blob. This will then make the original contents of the blob the current version again. Be sure you pass the full url including the version id when you do this copy.

**Comment by HarisinghRajputTR** [comment]
@rickle-msft Thanks a lot for above suggestion.
FYI, I'm able to restore file successfully with copy deleted version to blob as per below code snippet:-

![image](https://user-images.githubusercontent.com/90780976/146552528-2539d41d-e65a-47f8-bee9-296d4d6e020e.png)

Can you please review above code and let me know, if anything need to improve. 
It is working fine when soft delete + versioning both enabled. 

Query:-
1)As per above code, when I restore file(copy previous version to current version to make it active) multiple times, new version is created each time which is valid behavior. But can I add any check in my code to prevent it based on status.

I want to restore file only those which are marked with deleted status.

2)How can I get PagedIterable<BlobItem> blobItems size to handle file not exist case. 
I didn't find any method in SDK.

Thank you

**Comment by rickle-msft** [comment]
I would maybe recommend double checking that `blobItem.getName()` actually equals the target file name. Sometimes there can be unexpected behavior if one file name happens to be the prefix for a different file. 

1) It depends a little bit on your exact circumstance and what other operations are going on in the application. If you're only using versioning for back up and restore like this, you can delete all versions older than the most recent one and that would ensure there's only ever one version when you iterate, so the copy only happens once. Continuing to manage old versions may end up being a similar number of requests, though. There's no way to tell if a given version is the second-most-recent version that you want to copy, though. Probably just short circuiting and ending the function after the first copy is the best way.
2) Can you explain more about what you mean by "handle file not exist case"? It should just return an empty list if nothing matches the prefix? What is the behavior you're hoping for?

**Comment by HarisinghRajputTR** [comment]
> I would maybe recommend double checking that `blobItem.getName()` actually equals the target file name. Sometimes there can be unexpected behavior if one file name happens to be the prefix for a different file.

Thank you @rickle-msft  
It is added successfully as per your recommendation.

> 1. It depends a little bit on your exact circumstance and what other operations are going on in the application. If you're only using versioning for back up and restore like this, you can delete all versions older than the most recent one and that would ensure there's only ever one version when you iterate, so the copy only happens once. Continuing to manage old versions may end up being a similar number of requests, though. There's no way to tell if a given version is the second-most-recent version that you want to copy, though. Probably just short circuiting and ending the function after the first copy is the best way.

Yes, I've done it in same way like breaking the loop after first copy is done.
![image](https://user-images.githubusercontent.com/90780976/146780728-809aa176-f6ed-41b5-88e8-f3522c374331.png)


I'm looking for any method which can give me blob status so I can perform copy only on those blobs which are in deleted status. 
Restore blob should not call on any active blob to prevent it to create un-necessary versions.. Any solution??



> 2\. Can you explain more about what you mean by "handle file not exist case"? It should just return an empty list if nothing matches the prefix? What is the behavior you're hoping for?

Yes I was looking for empty list check and completed as like below:-
![image](https://user-images.githubusercontent.com/90780976/146780100-beb9c5d0-1939-493b-adcd-3ba98d1d5e83.png)

Thank you @rickle-msft for your continuous support. Your response is appreciable.

Please review the code.

**Comment by HarisinghRajputTR** [comment]
> Ah I think I understand. You're saying that you don't want to even start the attempt-to-restore process unless the blob is currently in deleted state, right? Versioning doesn't give you any information on what change was made to cause an update of the version id. It simply updates the version id. So using versioning won't be able to give you that behavior.

Sorry for late response @rickle-msft 
Yes, you got it correctly.

> It sounds a little bit from your scenario like you really only need soft delete and not versioning at all. If you turn off versioning and keep soft delete, you can use the undelete api directly instead of making listing calls and worrying about these different states. Is there a separate reason why you would also like versioning enabled.

> **FYI, I tried undelete call with only soft delete option enable then it is working fine as per expectation.**
Yes, this case I had already checked in past but it is not applicable in our case.

Actually our infra team decided to enable below option as a data prevention feature. So we can't make change it on infra/storage side. We should handle it in our API side itself. 

![image](https://user-images.githubusercontent.com/90780976/148651863-50fb029b-f3cc-40d5-a01c-b7b8f02c5d33.png)

**Comment by rickle-msft** [comment]
@HarisinghRajputTR I see. Looking into versioning a bit more I found this: "When you delete a blob, the current version of the blob becomes a previous version, and there is no longer a current version. Any previous versions of the blob persist." ([here](https://docs.microsoft.com/en-us/azure/storage/blobs/versioning-overview))

It looks like you can check if there is a current version, and if there is none, you can assume the blob was deleted and not just modified
