### ISSUE TITLE
[BUG] listEntities for Azure Table returns RowItems whose RowKeys and PartitionKeys are null

### ISSUE THREAD

**Issue by limotley** [Azure/azure-sdk-for-java#25952]
**Describe the bug**
When running a select query on a table using the listEntities method, all rowItems returned return null when getRowKey or getPartitionKey are accessed. The table being queried is an Azure Table inside of a standard storage account; no rows or partitions in this table have null as their key. I've been able to work around it by including "RowKey" as columnName in the snippet below, but it's not ideal. I don't see in the docs that the intended behavior for select is that RowKey and PartitionKey will not be populated unless specified, and I believe they should be a special case.

***Code Snippet***
```
val tableResult = tableClient.listEntities(new ListEntitiesOptions().setSelect(columnNames.asJava), Duration.ofMinutes(1), null)
tableResult.asScala
  .map(
    row => {
      // Accessing row.getRowKey or row.GetPartitionKey here returns null
      val rowObject = foo(row)
      val key = row.getProperties.get("RowKey").toString
      key -> rowObject
   })
```
**To Reproduce**
Attempt to run listEntities with some columns selected which do not include RowKey or PartitionKey. Then, try to use getRowKey or getPartitionKey on one of the RowItems returned

**Expected behavior**
RowItems returned would have their RowKey and PartitionKey attributes populated.

**Setup (please complete the following information):**
 - OS: Windows 11
 - IDE: Intellij
 - Library/Libraries: com.azure:azure-data-tables:12.1.2
 - Java version: 8 
 - App Server/Environment: Synapse
 - Frameworks: Spark

**Comment by alzimmermsft** [comment]
@vcolin7 could you take a look at this?

**Comment by jairmyree** [comment]
@limotley according to the javadoc for the ListEntities method, "If the select parameter is set, only the properties included in the select parameter will be returned for each entity." The methods "getRowKey" and "getPartitionKey" obtain their respective values from the entity's properties. If you intend to reference either the partition or row keys and utilize the select parameter, you must include them within the select parameter.
