### ISSUE TITLE
[QUERY] How to log all HTTP requests?

### ISSUE THREAD

**Issue by wboleksii** [Azure/azure-sdk-for-java#25957]
I'm trying to debug my authentication flow and I want to monitor all HTTP requests that library makes, including request and response bodies. I set logback configuration to "trace", but I still can't see request payloads 

```
<?xml version="1.0" encoding="UTF-8"?>
<configuration>
    <appender name="STDOUT" class="ch.qos.logback.core.ConsoleAppender">
        <encoder>
            <pattern>%d{HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n</pattern>
        </encoder>
    </appender>

    <root level="trace">
        <appender-ref ref="STDOUT" />
    </root>
</configuration>
```
Sample code:
```
final ClientSecretCredential clientSecretCredential = new ClientSecretCredentialBuilder()
        .clientId(CLIENT_ID)
        .clientSecret(CLIENT_SECRET)
        .tenantId(TENANT_GUID)
        .build();

final TokenCredentialAuthProvider tokenCredAuthProvider = new TokenCredentialAuthProvider(SCOPES, clientSecretCredential);

this.graphClient = GraphServiceClient.builder().buildClient();

ListItemCollectionPage pages = this.graphClient
        .sites(siteId)
        .lists(listId)
        .items()
        .buildRequest()
        .get();
```

**Comment by wboleksii** [comment]
@alzimmermsft

**Comment by alzimmermsft** [comment]
@baywet could you help @wboleksii on enabling request logging for `GraphServiceClient`?

**Comment by baywet** [comment]
I believe the ask here is about logging the authentication requests, not the requests made to Microsoft Graph.
@wboleksii can you specify which requests you want to log?
Also cc @ramsessanchez who's now the main maintainer of the Java sdk on our side.

**Comment by alzimmermsft** [comment]
@wboleksii, setting the environment property `AZURE_HTTP_LOG_DETAIL_LEVEL` to `body_and_headers` should enable the `HttpLoggingPolicy` to log the request and response headers and bodies.
