### ISSUE TITLE
Api to find if the instance type supports accelerated networking or not

### ISSUE THREAD

**Issue by akshitjain** [Azure/azure-sdk-for-java#2597]
Since azure supports accelerated networking for few instance types.
I believe there should be a way to find if the instance type used to provision the vm/vmss supports accelerated networking or not.

Hard coding the supported instances types in app code is not recommended as when azure gives the support for other instance types then we need to change the code and redeploy which would be an overhead and delay the process.

**Comment by yungezz** [comment]
hi @xccc-msft could you pls have a look? thanks

**Comment by xccc-msft** [comment]
@akshitjain It looks there is no API to help validate whether the instance type supports accelerated networking as per the REST APIs of  [VM](https://docs.microsoft.com/en-us/rest/api/compute/virtualmachines) and [VMSS](https://docs.microsoft.com/en-us/rest/api/compute/virtualmachinescalesets).

Below links might help you:
[Supported VM instances on Windows](https://docs.microsoft.com/en-us/azure/virtual-network/create-vm-accelerated-networking-powershell#supported-vm-instances).
[Supported VM instances on Linux](https://docs.microsoft.com/en-us/azure/virtual-network/create-vm-accelerated-networking-cli#supported-vm-instances).

**Comment by yungezz** [comment]
hi @akshitjain does above info helpful?

**Comment by xccc-msft** [comment]
@akshitjain We will close this issue for now as no update from your end. Please feel free to reopen if you have further question on this. Thanks.
