### ISSUE TITLE
[FEATURE REQ] Create simple BlobClient.upload(InputStream) overload.

### ISSUE THREAD

**Issue by kasobol-msft** [Azure/azure-sdk-for-java#25984]
I'm trying to feed InputStream into `BlobClient.upload` methods.

It seems that I'm capable of doing this:
```
    @Override
    public void save(String fileName, InputStream fileInputStream) throws IOException {
        blobServiceClient.getBlobContainerClient(CONTAINER_NAME)
            .getBlobClient(fileName)
            .uploadWithResponse(new BlobParallelUploadOptions(fileInputStream), null, null);
    }
```
That's possible after we switched the Stream->Flux converter that doesn't require lenght.

However, I was first looking for `BlobClient.upload(InputStream)`. All I found were overloads that take length as mandatory parameter.
Could we please add `BlobClient.upload(InputStream)` and `BlobClient.upload(InputStream, bool)` ?

**Comment by rickle-msft** [comment]
Seems reasonable at first glance. I've added it to our backlog
