### ISSUE TITLE
How to add a callback function after a producer sends a message asynchronously

### ISSUE THREAD

**Issue by huangdezhou008** [Azure/azure-sdk-for-java#25996]
**Query/Question**
A clear and concise ask/query.

***Why is this not a Bug or a feature Request?***
A clear explanation of why is this not a bug or a feature request?

**Setup (please complete the following information if applicable):**
 - IDE: [e.g. IntelliJ]
 - Library/Libraries: [e.g. com.azure:azure-core:1.16.0 (groupId:artifactId:version)]
 
 **Information Checklist**
 Kindly make sure that you have added all the following information above and checkoff the required fields otherwise we will treat the issuer as an incomplete report
- [ ] Query Added
- [ ] Setup information Added

**Comment by joshfree** [comment]
Hi @huangdezhou008, you can find documentation on the EventProcessorClient and how to delegate processing of events to a callback function on docs.microsoft.com here: https://docs.microsoft.com/en-us/java/api/overview/azure/messaging-eventhubs-readme?view=azure-java-stable#consume-events-using-an-eventprocessorclient

**Comment by joshfree** [comment]
I'm closing the issue now, please feel free to reactivate with more details or to open a new issue if there is anything else.  Thank you again.
