### ISSUE TITLE
 serivcebus this.binderAwareChannelResolver.resolveDestination(channelName),How can I catch errors sent asynchronously

### ISSUE THREAD

**Issue by huangdezhou008** [Azure/azure-sdk-for-java#25997]
**Query/Question**
A clear and concise ask/query.

***Why is this not a Bug or a feature Request?***
A clear explanation of why is this not a bug or a feature request?

**Setup (please complete the following information if applicable):**
 - IDE: [e.g. IntelliJ]
 - Library/Libraries: [e.g. com.azure:azure-core:1.16.0 (groupId:artifactId:version)]
 
 **Information Checklist**
 Kindly make sure that you have added all the following information above and checkoff the required fields otherwise we will treat the issuer as an incomplete report
- [ ] Query Added
- [ ] Setup information Added

**Comment by backwind1233** [comment]
link issue: https://github.com/Azure/azure-sdk-for-java/issues/25753

**Comment by huangdezhou008** [comment]
@backwind1233  ,but  #25753 not help me to solve the problem,so i open new queston to help me

**Comment by yiliuTo** [comment]
Hi @huangdezhou008 , sorry for the late response, let's go back to your original issue and use that to track the issue for the complete context. I have replied there and please take a look.

**Comment by yiliuTo** [comment]
Close this issue and we will use #25753 to track it.
