### ISSUE TITLE
Zip deploy was failing while deploying code to function apps with below error

### ISSUE THREAD

**Issue by Nagipenugonda** [Azure/azure-sdk-for-java#25998]
These app settings  are already present 
WEBSITE_CONTENTAZUREFILECONNECTIONSTRING 
WEBSITE_CONTENTSHARE
WEBSITE_RUN_FROM_PACKAGE

This issue was solved either after adding WEBSITE_CONTENTAZUREFILECONNECTIONSTRING and
WEBSITE_CONTENTSHARE but now **our azure resources are integrated with vnet.**

   
Github action:

 - name: 'Run Azure Functions Action'
      uses: Azure/functions-action@v1
      id: fa
      with:
        app-name: ${{ env.AZURE_FUNCTIONAPP_NAME }}
        #slot-name: ${{ env.SLOT_NAME }}
        package: './lastfunczip/target/azure-functions/${{ env.POM_FUNCTIONAPP_NAME }}'
        #publish-profile: ${{ steps.publishprofile.outputs.profile }}

Run Azure/functions-action@v1
Using RBAC for authentication, GitHub Action will perform resource validation.
Successfully acquired site configs from function app!
Detected function app sku: Dedicated
Successfully acquired app settings from function app (RBAC)!
Detected function app language: Java
Will archive ./lastfunczip/target/azure-functions/cig-loy-tx-sprt into /home/runner/work/_temp/temp_web_package_44798747365641023.zip as function app content
Will use https://<scmsite>/api/zipdeploy to deploy since RBAC Azure credential is detected.
Setting WEBSITE_RUN_FROM_PACKAGE to 1
Update using context.appService.patchApplicationSettings
App setting WEBSITE_RUN_FROM_PACKAGE propagated to Kudu container
Package deployment using ZIP Deploy initiated.
Error: Failed to deploy web package to App Service.
Error: Execution Exception (state: PublishContent) (step: Invocation)
Error:   When request Azure resource at PublishContent, zipDeploy : Failed to use /home/runner/work/_temp/temp_web_package_44798747365641023.zip as ZipDeploy content
Error:     Failed to deploy web package to App Service.
Internal Server Error (CODE: 500)
Error:       Error: Failed to deploy web package to App Service.
Internal Server Error (CODE: 500)
    at Kudu.<anonymous> (/home/runner/work/_actions/Azure/functions-action/v1/node_modules/azure-actions-appservice-rest/Kudu/azure-app-kudu-service.js:175:23)
    at Generator.next (<anonymous>)
    at fulfilled (/home/runner/work/_actions/Azure/functions-action/v1/node_modules/azure-actions-appservice-rest/Kudu/azure-app-kudu-service.js:5:58)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
Error: Deployment Failed!

Issue with the whitelisting ip of github runner in function app vnet Allow rule. what is the ideal way to whitelist github action runner IP under function app vnet.

**Comment by joshfree** [comment]
Hi @Nagipenugonda, I believe this question would be best asked on the Azure Functions GitHub repo, here: https://github.com/Azure/Azure-Functions

**Comment by joshfree** [comment]
I'm closing this issue here, please feel free to reactivate with more details or open a new issue about an Azure Client Library (SDK).  Thanks
