### ISSUE TITLE
Recovery Services Backup: public constructor need

### ISSUE THREAD

**Issue by fivig** [Azure/azure-sdk-for-java#26007]
https://github.com/Azure/azure-sdk-for-java/blob/039bdad0e21211b3c4f88bb47cb52755778089e6/sdk/recoveryservicesbackup/azure-resourcemanager-recoveryservicesbackup/src/main/java/com/azure/resourcemanager/recoveryservicesbackup/models/RecoveryPointTierType.java#L27

otherwise exception happen:
19:57:11 [reactor-http-nio-1] DEBUG [Loggers$Slf4JLogger:245] [id:734c9f0f-1, L:/192.168.31.212:61381 - R:management.azure.com/51.12.101.64:443] Received last HTTP packet
com.fasterxml.jackson.databind.exc.ValueInstantiationException: Cannot construct instance of `com.azure.resourcemanager.recoveryservicesbackup.models.RecoveryPointTierType`, problem: argument type mismatch
 at [Source: (String)"{"value":[{"i

**Comment by joshfree** [comment]
@weidongxu-microsoft could you please follow up with @fivig?  Thank you

**Comment by weidongxu-microsoft** [comment]
@fivig 
Could you put the full error stack, or give us the log of the response?

My suspicion is that response from service does not match the values in `RecoveryPointTierType`, hence the error.
