### ISSUE TITLE
400 : Bad Request

### ISSUE THREAD

**Issue by huangdezhou008** [Azure/azure-sdk-for-java#26048]
GET https://graph.microsoft.com/v1.0/me/mailFolders/AAMkAGI1ZTcyZDUyLTUwYjAtNDQ3Zi04MmJiLTk0NDYyMjRjZDg5YwAuAAAAAAAt9u-CPVJiQr1bW65ncf0rAQALZx8mRleUSpRunE2oMh9mAAAAAAEJAAA=/messages?%24select=id%2Cfrom%2CtoRecipients%2Csubject%2CisRead%2CisReadReceiptRequested%2CisDeliveryReceiptRequested%2CparentFolderId%2CsentDateTime%2CreceivedDateTime%2Cbody%2Cimportance%2CcreatedDateTime&%24filter=startswith%28subject%2C%27te%27%29%20and%20startswith%28from%2C%27huang%27%29&%24orderby=subject%20asc%2Cfrom%20desc
Prefer : outlook.body-content-type="text"
SdkVersion : graph-java/v2.2.0
Authorization : [PII_REDACTED]

400 : Bad Request
[...]

**Comment by joshfree** [comment]
Hi @huangdezhou008, we're unable to help you with the information supplied.  If you're looking for the MS Graph Java SDK repo, it lives here: https://github.com/microsoftgraph/msgraph-sdk-java/

I'm going to close out this issue, but feel free to reactivate it with more information or create a new issue if that is easier.  Thanks
