### ISSUE TITLE
[ServiceBus] Failed to deploy test resource in weekly pipeline

### ISSUE THREAD

**Issue by hongli750210** [Azure/azure-sdk-for-java#26058]
We are running live tests against other clouds like US Gov and Azure China Cloud. The goal is to check whether new azure sdk package work with other clouds or not.

**Error Description:**
When running the ServiceBus pipeline on Public and UsGov and Azure China cloud, it runs failed at section `Deploy test resource` and the error messages is shown as following, for more details please check [here](https://dev.azure.com/azure-sdk/internal/_build/results?buildId=1249452&view=results):

![image](https://user-images.githubusercontent.com/74638143/146317993-f5a7ed29-206c-4c9e-8663-a549b3fc8dbd.png)

**Expected Behavior:**
The deploy test resource can pass in weekly pipeline.

@benbp, @joshfree, @lilyjma, @ramya-rao-a and @conniey for notification.

**Comment by benbp** [comment]
The deployment error found in the logs:

No registered resource provider found for location 'westus2' and API version '2021-05-01' for type 'namespaces'. The supported api-versions are '2014-09-01, 2015-08-01, 2017-04-01, 2018-01-01-preview, 2021-01-01-preview, 2021-06-01-preview'. The supported locations are 'australiaeast, australiasoutheast, centralus, eastus, eastus2, westus2, westus, northcentralus, southcentralus, westcentralus, eastasia, southeastasia, brazilsouth, japaneast, japanwest, northeurope, westeurope, centralindia, southindia, westindia, canadacentral, canadaeast, ukwest, uksouth, koreacentral, francecentral, southafricanorth, uaenorth, australiacentral, switzerlandnorth, germanywestcentral, norwayeast, jioindiawest, westus3, swedencentral, koreasouth, centraluseuap, eastus2euap'.

Looks like the 2021-05-01 api version might be wrong here?

**Comment by hongli750210** [comment]
@benbp 
I found in the error message of Pipeline that the API of the `2021-01-01-preview` version was deployed in Public and UsGov and Azure China Cloud. After the fixed, the test resource was successfully deployed.

**Comment by benbp** [comment]
I don't know what the issue could be here, we might need a java sdk dev to investigate. @joshfree?

**Comment by joshfree** [comment]
@anuchandy @conniey could you help prioritize this in the amqp standup for the next monthly release?

**Comment by v-xuto** [comment]
@joshfree @anuchandy @conniey 
For this issue, we have updated the setting value of `API Version` from `2021-05-01` to `2021-01-01-preview` in PR #26594. This modification can solve this issue and successfully deploy test resource, and the PR #26594 has been merged.

Besides, we have tested the latest `API Version 2021-06-01-preview`, it deploys test resource that can `pass` in weekly pipeline. `API Version 2021-05-01` still failed to deploy test resource.

Therefore, do we need to support  `API Version 2021-05-01` for this issue now, or do you have other ideas about this issue? **If not, maybe we can close the issue.**

**Comment by v-xuto** [comment]
@anuchandy Is there anything else you need to do about this issue? If not, we will close the issue.

**Comment by anuchandy** [comment]
thank you @v-xuto! this is good to close.
