### ISSUE TITLE
[BUG] ChangeLog entry check failed when releasing Spring Cloud Azure 4.0

### ISSUE THREAD

**Issue by saragluna** [Azure/azure-sdk-for-java#26075]
**Describe the bug**
When releasing the 4.0.0 the pipeline failed at the check changelog entry step of **release** stage. https://dev.azure.com/azure-sdk/internal/_build/results?buildId=1207815&view=logs&j=0b7b16c9-6771-5dc1-d161-487f87b1b08b&t=21904e36-8326-5a49-e75a-42a0dd20ffab&l=42

**Expected behavior**
No such error should block the rlease.

**Screenshots**
![image](https://user-images.githubusercontent.com/31124698/146504219-18fe1d4c-7ba0-4b42-b80b-8f3d2d4723e9.png)

**Information Checklist**
Kindly make sure that you have added all the following information above and checkoff the required fields otherwise we will treat the issuer as an incomplete report
- [x] Bug Description Added
- [x] Repro Steps Added
- [x] Setup information Added

**Comment by chenrujun** [comment]
Closing this issue because related PR has been merged.
