### ISSUE TITLE
Track spring-boot compatible versions about azure-sdk-for-java and spring-cloud-azure.

### ISSUE THREAD

**Issue by chenrujun** [Azure/azure-sdk-for-java#26076]
## Version mapping between spring-boot and azure-sdk-for-java

 - Now there is a wiki page to track version mapping between spring-boot and spring-cloud-azure:
https://github.com/Azure/azure-sdk-for-java/wiki/Spring-Versions-Mapping
 - But there isn't a wiki page to track version mapping between spring-boot and azure-sdk-for-java.
We should maintain that mapping.

## Single truth of version mapping.

We should put the mapping in one place(for example, github wiki), and add link in MS docs and reference doc.

**Comment by chenrujun** [comment]
Hi, @JonathanGiles , 

How about using same version for all azure-sdk-for-java libraries? Just Like Spring-Cloud-Azure:4.0.0.
If it's OK to use same versioon, the azure-sdk-bom should use that version, too. (cc: @pallavit FYI)

Furthermore, how about using same version for all azure-sdk-for-java libraries and Spring-Cloud-Azure libraries. 
Just like some spring projects(spring-framework, spring-security), all artifacts in one repository share the same version.
It will be convenient for our customer if we do like this.

**Comment by JonathanGiles** [comment]
There are too many libraries that have existed for years to find any suitable way to align versions. Storage is at version 12 and application config is at version 1. Should we move everything to major version 13? Probably not. What about when releases happen out of band due to critical issues, etc? Does everything need to do a revision release? What if we need to do a major release of a certain library - do we do major releases of all libraries even if they have no major changes?

There are a bunch of issues with aligning versions, so for that reason our preferred strategy is to have our BOM be responsible for handling the matching of compatible versions of each library, and have our users simply defer to the BOM for choosing the relevant version for each dependency they require.

**Comment by chenrujun** [comment]
@JonathanGiles Thank you for your detailed explanation.

But similar issues also exist in [spring-framework repository](https://github.com/spring-projects/spring-framework).
Since spring-framework can use the uniform version, we can accept the same solution.

About the issues you metioned:

> 1. Storage is at version 12 and application config is at version 1. Should we move everything to major version 13?

Version 13 is OK.

> 2. What about when releases happen out of band due to critical issues, etc? Does everything need to do a revision release? 

Yes, release for every artifact in this repo. I think for spring-framework, not every library has updates in every patch release.

> 3. What if we need to do a major release of a certain library - do we do major releases of all libraries even if they have no major changes?

Yes, do major release for all libraries, just like spring-framework did. For every major release, not every spring-framework library have major changes, I think.

> 4. have our BOM be responsible for handling the matching of compatible versions of each library

Yes, use BOM is one solution. But use uniform version is a better solution. So the customer can use the concept of `the version of azure-sdk-for-java`. When customer use artifact like `azure-security-keyvault-secrets` and `azure-data-appconfiguration`, if they use the same version, our customer can know that the 2 artifacts can work together without any problem.


This problem not only exist in our repo, a lot of other repos have similar problem. Most of them choose the uniform version. Like spring-framework, spring-security. These repositories also have a lot of libraries.

**Comment by chenrujun** [comment]
@JonathanGiles . Got it. Thank you.

**Comment by azizabah** [comment]
@chenrujun  - I don't think should be closed. The document created does not do a sufficient job of providing a mapping of versions that should be used. https://start.spring.io/actuator/info should be used for inspiration as to what is sufficient. I am specifically talking about how the Spring team provides version mapping for things like Spring Cloud:
```
"spring-cloud": {
"Hoxton.SR12": "Spring Boot >=2.2.0.RELEASE and <2.4.0.M1",
"2020.0.5": "Spring Boot >=2.4.0.M1 and <2.6.0-M1",
"2021.0.0-M1": "Spring Boot >=2.6.0-M1 and <2.6.0-M3",
"2021.0.0-M3": "Spring Boot >=2.6.0-M3 and <2.6.0-RC1",
"2021.0.0-RC1": "Spring Boot >=2.6.0-RC1 and <2.6.1",
"2021.0.1": "Spring Boot >=2.6.1 and <2.6.5-SNAPSHOT",
"2021.0.2-SNAPSHOT": "Spring Boot >=2.6.5-SNAPSHOT and <3.0.0-M1",
"2022.0.0-M1": "Spring Boot >=3.0.0-M1 and <3.1.0-M1"
},
```

That provides a crystal clear definition of what versions map to what.

**Comment by chenrujun** [comment]
@azizabah 

Your comment make sense. 
I'll reopen this issue and improve the document.

**Comment by chenrujun** [comment]
Hi, @azizabah .

I update the wiki page. Please help to check: 
https://github.com/Azure/azure-sdk-for-java/wiki/Spring-Versions-Mapping

**Comment by azizabah** [comment]
@chenrujun - That looks great. Thanks for the update and feel free to close now.

**Comment by chenrujun** [comment]
Closing this issue, because related wiki page has been updated.
