### ISSUE TITLE
How to turn off eventhub logs?

### ISSUE THREAD

**Issue by akiliu00512** [Azure/azure-sdk-for-java#26071]
source code

package com.example.simplespring.test;

import com.azure.messaging.eventhubs.EventHubClientBuilder;
import com.azure.messaging.eventhubs.EventProcessorClient;
import com.azure.messaging.eventhubs.EventProcessorClientBuilder;
import com.azure.messaging.eventhubs.checkpointstore.blob.BlobCheckpointStore;
import com.azure.messaging.eventhubs.models.EventContext;
import com.azure.storage.blob.BlobContainerAsyncClient;
import com.azure.storage.blob.BlobContainerClientBuilder;
import lombok.extern.slf4j.Slf4j;
import org.springframework.stereotype.Component;

@Component
@Slf4j
public class AzureDeviceLifecycleListener {

    private static String connectionString = "Endpoint=*****";
    private static String storageConnectionString = "******";
    private static String storageContainerName = "*******";

    private static BlobContainerAsyncClient blobContainerAsyncClient = new BlobContainerClientBuilder()
            .connectionString(storageConnectionString)
            .containerName(storageContainerName)
            .buildAsyncClient();

    private static EventProcessorClient eventProcessorClient;

    private static void doProcessEvent(EventContext eventContext) {
        byte[] body = eventContext.getEventData().getBody();
        System.out.println("body string: " + new String(body));
    }

    public static void main(String[] args) {
        eventProcessorClient = new EventProcessorClientBuilder()
                .consumerGroup(EventHubClientBuilder.DEFAULT_CONSUMER_GROUP_NAME)
                .connectionString(connectionString)
                .checkpointStore(new BlobCheckpointStore(blobContainerAsyncClient))
                .processEvent(AzureDeviceLifecycleListener::doProcessEvent)
                .processError(errorContext -> log.error("Error occurred while processing azure events " + errorContext.getThrowable().getMessage()))
                .buildEventProcessorClient();

        // This will start the processor. It will start processing events from all partitions.
        eventProcessorClient.start();
        log.info("azure event processor for device lifecycle is running!");
    }
}

it is printing logs every few seconds as below, how to turn off this log?
![WeChat Image_20211217112147](https://user-images.githubusercontent.com/59610015/146483697-3715bd24-73c7-4114-bc39-ec31b7b542e6.png)

**Comment by conniey** [comment]
Hey. We are aware of the verbosity of these logs and have an issue to decrease it. https://github.com/Azure/azure-sdk-for-java/issues/20836

In the meantime, you can add filters to your loggers. https://github.com/Azure/azure-sdk-for-java/blob/main/sdk/eventhubs/azure-messaging-eventhubs/docs/troubleshooting.md
