### ISSUE TITLE
[FEATURE REQ] Provide property to configure auto lock renewal for Standard tier

### ISSUE THREAD

**Issue by vtrusevich-incomm** [Azure/azure-sdk-for-java#26087]
**Is your feature request related to a problem? Please describe.**
Currently, it is possible to set max lock time for 5 minutes for a message and impossible to configure auto-renewal of a message that is in processing. 

We do use ServiceBus messages for starting some heavy file processing activities which are taking 10-60 minutes to complete and want to use the PEEK_LOCK approach to have the ability to retry failed or abandoned messages.

**Describe the solution you'd like**
Please, provide the ability to set auto-renewal for messages in progress via properties.

**Describe alternatives you've considered**
As an alternative, 2 hours of max lock duration can also be an option

**Comment by ramya-rao-a** [comment]
> Currently, it is possible to set max lock time for 5 minutes for a message 

You can set the max auto lock renewal time to any number based on your needs. Can you share more on where you found that you can only set this to at max 5 minutes?
