### ISSUE TITLE
[QUERY] Update Failover Group with two clients in parallel

### ISSUE THREAD

**Issue by pknapek2** [Azure/azure-sdk-for-java#26080]
**Query/Question**
I'm using com.azure.resourcemanager.sql.models.SqlFailoverGroup class for updating Failover Group with this code:
failoverGroup.withNewDatabaseId(databaseId).apply()

This updates failover group correctly.
The method sets the list of databases to the failover group - origin databases which were read during initialization and newly added one.

The problem is when two databases (f.e. DB_A and DB_B) should be added to failover group with different clients in parallel. If both clients are initialized with the same data (f. e. DB1, DB2, DB3) then first client will add DB_A to the group. But this change is overwritten with list of databases from second client, it adds DB_B. At the end only one database is added to failover group and database from first client is missing in failover group.
Is there any other possibility how to update failover group safer way?

***Why is this not a Bug or a feature Request?***
It could be bug or feature request if there is not alternative way how to solve my scenario.

**Setup (please complete the following information if applicable):**
 - OS: Linux
 - IDE: IntelliJ
 - Library/Libraries: com.azure.resourcemanager:azure-resourcemanager-sql:2.10.0
 
 **Information Checklist**
 Kindly make sure that you have added all the following information above and checkoff the required fields otherwise we will treat the issuer as an incomplete report
- [x] Query Added
- [x] Setup information Added

**Comment by joshfree** [comment]
@weidongxu-microsoft could you please take a look and help route this issue filed by @pknapek2?

**Comment by weidongxu-microsoft** [comment]
@pknapek2 

It might not be possible to solve without server support, i.e., etag support or a merge patch (though json merge patch might not work on array).

However in my memory sql service does not support etag.

**Comment by pknapek2** [comment]
So Azure SQL service does not provide this.
@weidongxu-microsoft thank you for answer.

**Comment by weidongxu-microsoft** [comment]
Yeah, fallover group does not support etag, and the `databases` is an array which will be overwritten during PATCH or PUT (one had to put a complete array).
https://github.com/Azure/azure-rest-api-specs/blob/main/specification/sql/resource-manager/Microsoft.Sql/preview/2021-05-01-preview/FailoverGroups.json#L592-L598

Hence it might need e.g. a distributed locking like Zookeeper or Redis (if same machine, lock file will do but might not scale)? Someone seems also used a Azure storage lease blob for lock... (I haven't tried that)

On the other hand, having multiple app managing a same Azure resource might not be a good practice?
