### ISSUE TITLE
[BUG] azure-core-1.23.1 logs version conflict with Jackson 2.13.0, but that version is marked as supported in maven

### ISSUE THREAD

**Issue by Kryword** [Azure/azure-sdk-for-java#26126]
**Describe the bug**
A new INFO warning appears when using Jackson libraries on version 2.13.0 and azure-core library on version 1.23.1. In maven azure-core 1.23.1 supports Jackson 2.13.0.

***Exception or Stack Trace***
```
2021-12-20 11:09:41,205 [http-nio-8080-exec-6] INFO  com.azure.core.implementation.jackson.JacksonVersion - Package versions: jackson-annotations=2.13.0, jackson-core=2.13.0, jackson-databind=2.13.0, jackson-dataformat-xml=2.13.0, jackson-datatype-jsr310=2.13.0, azure-core=1.23.1, Troubleshooting version conflicts: https://aka.ms/azsdk/java/dependency/troubleshoot
```

**To Reproduce**
1. Install azure-core 1.23.1 and Jackson 2.13.0.
2. Try to start the application, that INFO log appears

***Code Snippet***
The code that should be updated is in [JacksonVersion.java](https://github.com/Azure/azure-sdk-for-java/blob/azure-core_1.23.1/sdk/core/azure-core/src/main/java/com/azure/core/implementation/jackson/JacksonVersion.java#L28) verifier file, on line 28:
```
    private static final SemanticVersion MAX_SUPPORTED_VERSION = SemanticVersion.parse("2.12.5");
```
should instead be:
```
    private static final SemanticVersion MAX_SUPPORTED_VERSION = SemanticVersion.parse("2.13.0");
```

**Expected behavior**
A warning should not appear when having azure-core 1.23.1 and Jackson libraries on version 2.13.0, because this version is marked as supported for that version of azure-core.

**Setup (please complete the following information):**
 - OS: Ubuntu LTS 20.04
 - IDE: IntelliJ IDEA
 - Library/Libraries: com.azure:azure-core:1.23.1, com.fasterxml.jackson.core:jackson-core:2.13.0 and the rest of jackson libraries on 2.13.0
 - Java version: 11
 - App Server/Environment: Tomcat
 - Frameworks: None

**Information Checklist**
Kindly make sure that you have added all the following information above and checkoff the required fields otherwise we will treat the issuer as an incomplete report
- [x] Bug Description Added
- [x] Repro Steps Added
- [x] Setup information Added

**Comment by Kryword** [comment]
I've also prepared this pull request to fix this issue: https://github.com/Azure/azure-sdk-for-java/pull/26127

**Comment by lmolkova** [comment]
Thanks for reporting it @Kryword. The log you see is not an indication of any error, this is information in case we'll need to investigate any issues regarding serialization and version conflict. 

I agree  `MAX_SUPPORTED_VERSION` needs to change for clarity, but functionally-wise currently only the major version of it is used 

https://github.com/Azure/azure-sdk-for-java/blob/7a38eddc5cbdc43b5694a44cbdce91e0ff82332b/sdk/core/azure-core/src/main/java/com/azure/core/implementation/jackson/JacksonVersion.java#L90-L95

It should be logged once when your process starts (or when Azure SDKs are first time initialized) and never logged again if everything is fine.  Does it cause any inconvenience to you?

**Comment by Kryword** [comment]
Hello, I think this recently merged MR should fix this issue: https://github.com/Azure/azure-sdk-for-java/pull/26129

**Comment by lmolkova** [comment]
@Kryword thanks, I'm going to close this issue then, and please reopen as you see fit
