### ISSUE TITLE
[BUG] Azure SDK bom should not have dependency management for third party libraries

### ISSUE THREAD

**Issue by snicoll** [Azure/azure-sdk-for-java#26136]
**Describe the bug**
As discussed on several occasion, a BOM should only provide dependency management for the modules managed directly by the project. See also https://github.com/microsoft/azure-spring-boot/issues/257

Forcing dependencies like this is a recipe for disaster as you're building against a given set of dependencies and actual users may use another version. 

This shows in particular in Spring Boot, that has a dependency management for the wider ecosystem for a given Spring Boot generation. Having dependency management for Micrometer is [breaking users](https://github.com/spring-projects/spring-boot/issues/28929#issuecomment-998682103).

***Exception or Stack Trace***
N/A

**To Reproduce**
Import `azure-spring-boot-bom` in a Spring Boot project and the dependency tree will show an inconsistent set of versions.

***Code Snippet***
N/A

**Expected behavior**
BOM only has opinions for Microsoft-based libraries.

**Screenshots**
N/A

**Setup (please complete the following information):**

**Additional context**
N/A

**Information Checklist**
Kindly make sure that you have added all the following information above and checkoff the required fields otherwise we will treat the issuer as an incomplete report
- [ ] Bug Description Added
- [ ] Repro Steps Added
- [ ] Setup information Added

**Comment by lmolkova** [comment]
@snicoll thanks for reaching out and providing context. We understand the concern and are evaluating different options for azure-sdk-bom.

As an update on the issue https://github.com/spring-projects/spring-boot/issues/28929 you refer to, azure-spring-boot-bom does not contain micrometer-core (or any other 3rd party dependencies) since the latest release [3.12.0](https://mvnrepository.com/artifact/com.azure.spring/azure-spring-boot-bom/3.12.0).

**Comment by snicoll** [comment]
@lmolkova thanks for the feedback. Do you understand that you dropped using `azure-sdk-bom` altogether in this version? They were quite a few interesting Microsoft-only dependencies in there. The bom for `3.12.0` also states:

>  Other Azure dependencies that not managed by azure-sdk-bom

**Comment by lmolkova** [comment]
@snicoll correct, Azure Spring Cloud team removed `azure-sdk-bom` altogether, and the "Other Azure dependencies that not managed by azure-sdk-bom" comment was probably stayed when `azure-sdk-bom` was removed, these dependencies are stil owned by microsoft. /cc @saragluna 

> They were quite a few interesting Microsoft-only dependencies in there.
Anything that raises your concern (beyond 3p dependencies)?

**Comment by saragluna** [comment]
Yes, it was stayed when removing the `azure-sdk-bom`. @yiliuTo, when removing the `azure-sdk-bom`, maybe we should keep the azure SDK versions in the bom.

**Comment by snicoll** [comment]
> Anything that raises your concern (beyond 3p dependencies)?

Thanks for asking. No particular concern besides the fact that a large number of microsoft-related libs were managed and aren't anymore.

**Comment by lmolkova** [comment]
>  a large number of microsoft-related libs were managed and aren't anymore.

@snicoll agreed, removing dependency from BOM is a breaking change (even though disruption is probably low) and we should at least communicate it well.

**Comment by snicoll** [comment]
Are the current labels accurate? The dependency management issues is in the main SDK bom, not the Spring-specific one.

**Comment by yiliuTo** [comment]
FYI @lmolkova and @snicoll , we have published a patch release for `azure-spring-boot-bom` which carries Azure sdk libraries' version that the Azure Spring libraries need.

**Comment by lmolkova** [comment]
`azure-sdk-bom` does not include 3rd party dependencies too (since [1.1.0](https://mvnrepository.com/artifact/com.azure/azure-sdk-bom/1.1.0)), so I'm closing this
