### ISSUE TITLE
[BUG] ShortType spark schema not supported in azure cosmos spark

### ISSUE THREAD

**Issue by mpindado** [Azure/azure-sdk-for-java#26135]
**Describe the bug**
If a column in the input dataframe is spark ShortType, the process of writing into cosmos fails with:

```
 java.lang.Exception: Cannot cast 50 into a Json value. ShortType
```

***Exception or Stack Trace***
TaskSetManager: Lost task 1.0 in stage 135.0 (TID 195, 10.0.19.70, executor 4): java.lang.Exception: Cannot cast 50 into a Json value. ShortType has no matching Json value.
at com.azure.cosmos.spark.CosmosRowConverter.convertSparkDataTypeToJsonNodeNonNull(CosmosRowConverter.scala:343)
at com.azure.cosmos.spark.CosmosRowConverter.convertSparkDataTypeToJsonNode(CosmosRowConverter.scala:183)
at com.azure.cosmos.spark.CosmosRowConverter.$anonfun$fromInternalRowToObjectNode$1(CosmosRowConverter.scala:143)
at scala.collection.IndexedSeqOptimized.foreach(IndexedSeqOptimized.scala:36)

**To Reproduce**
Simply create a dataframe with a column shortType

***Code Snippet***
In convertSparkDataTypeToJsonNodeNonNull , https://github.com/Azure/azure-sdk-for-java/blob/391fe8e3f008d4785e8191dce4efd59fdccd6ced/sdk/cosmos/azure-cosmos-spark_3-1_2-12/src/main/scala/com/azure/cosmos/spark/CosmosRowConverter.scala#L304

the match clause should include spark shortType on the left, and simply translate into number.

**Expected behavior**
The library should handle short values

**Setup (please complete the following information):**
 - OS: Spark
 - IDE: Intellij
 - Library/Libraries: com.azure.cosmos.spark / azure-cosmos-spark_3-1_2-12 / 4.4.2
 - Java version: 8-11
 - App Server/Environment: Apache Spark, Databricks
 - Frameworks: [e.g. Spring Boot, Micronaut, Quarkus, etc] 

**Information Checklist**
Kindly make sure that you have added all the following information above and checkoff the required fields otherwise we will treat the issuer as an incomplete report
- [X] Bug Description Added
- [X] Repro Steps Added
- [X] Setup information Added

**Comment by FabianMeiswinkel** [comment]
I sent out a PR to fix this. https://github.com/Azure/azure-sdk-for-java/pull/26137  - should be included in the next release (any release later than 4.5.2)

**Comment by FabianMeiswinkel** [comment]
Version 4.5.3 adding this support has been published to Maven - it can be found here: https://repo1.maven.org/maven2/com/azure/cosmos/spark/azure-cosmos-spark_3-1_2-12/4.5.3/azure-cosmos-spark_3-1_2-12-4.5.3.jar
