### ISSUE TITLE
Cache of DefaultAzureCredential when using Manage Identity from Server

### ISSUE THREAD

**Issue by jesper-werge** [Azure/azure-sdk-for-java#26152]
**Query/Question**
We are operating in Manage Identity environment, where I have a high performance stdin stdout process where each process request access to the Azure Key Vault for getting secrets etc. for other Azure components. But we experience that we do not get the token each time as we have to many request to fast, and are requested to cache the token and only refresh it when expired. makes sense, but I am not able to find the correct way to do so.

***Why is this not a Bug or a feature Request?***
We have used ITokenCacheAccessAspect for API tokens which including scopes with success, but can't figure out how to control this for key vault default credentials.

**Setup:**
 - OS: Windows
 - IDE: Eclipse
 - Library/Libraries: 

<artifactId>azure-identity</artifactId>
<version>1.2.2</version>

<artifactId>azure-security-keyvault-secrets</artifactId>
<version>4.2.4</version>

<artifactId>azure-security-keyvault-keys</artifactId>
<version>4.2.4</version>

<artifactId>azure-resourcemanager</artifactId>
<version>2.1.0</version>

<artifactId>azure-storage-blob</artifactId>
<version>12.10.0</version>

Hope some of you could guide me, please.

**Comment by joshfree** [comment]
@billwert could you follow up with @jesper-werge on this question?

/cc @vcolin7 @g2vinay

**Comment by billwert** [comment]
Sure, taking a look, will be back with you soon @jesper-werge.

**Comment by jesper-werge** [comment]
Hi @billwert 
Thank you for looking into this.

Just to clarify alittle. We are using the DefaultAzureCredential() where all we need is provided by the VM we are executing the code on. by doing this we don't need a lot of configuration keys and account name within the code or property files, 
but when we get to fast the services below the DefaultAzureCredential() start throttling and we fail the proces. 

So the idea was to cache the DefaultAzureCredential() on disk, but here I seem to get out of luck, And I have an idea that even if this is done with success some underlying call might still be executed. I find it hard to know exactly what the DefaultAzureCredentials are calling in the end.
 
We cache with success JWT tokens for access other endpoints to disk. I tried to do the same with the accessToken() method returned in the response, but I can't see where to use it afterwards, so again a dead end.

**Comment by billwert** [comment]
@jesper-werge That's great info, thanks. Knowing you're hitting throttling with DefaultAzureCredential is a good pointer. If you have a small sample that reproduces the problem that'd be very useful. Or a stack trace at the error?

**Comment by jesper-werge** [comment]
Hi @billwert
below are one of the samples which is around Azure Blob Storage:

Log.log(LOGCLASS_NAME, "###### START Create Blob - ManageIdentity", LogLevel.info);
BlobServiceClient storageClient = new BlobServiceClientBuilder().endpoint(endpoint)
		.credential**(new DefaultAzureCredentialBuilder().build()**)
		.buildClient();
Log.log(LOGCLASS_NAME, "###### Create Blob storageClient created: ", LogLevel.info);

BlobContainerClient blobContainerClient = storageClient.getBlobContainerClient(containerName);
Log.log(LOGCLASS_NAME, "###### Create Blob blobContainerClient created: ", LogLevel.info);

BlockBlobClient blobClient = blobContainerClient.getBlobClient(containerFilename).getBlockBlobClient();
Log.log(LOGCLASS_NAME, "###### Create Blob blobClient created: ", LogLevel.info);

//upload
InputStream is = new ByteArrayInputStream(data);
BlockBlobItem upload = blobClient.upload(is, data.length, true);
Log.log(LOGCLASS_NAME, "###### Create Blob upload executed: ", LogLevel.info);

UserDelegationKey userDelegationKey = storageClient.getUserDelegationKey(blobStartTime, blobExpiryTime);
Log.log(LOGCLASS_NAME, "###### Created userDelegationKey", LogLevel.info);

BlobContainerSasPermission blobPermissionRead = new BlobContainerSasPermission().setReadPermission(true);
BlobServiceSasSignatureValues sigRead = new BlobServiceSasSignatureValues(blobExpiryTime, blobPermissionRead).setStartTime(OffsetDateTime.now());
BlobContainerSasPermission blobPermissionDelete = new BlobContainerSasPermission().setDeletePermission(true);
BlobServiceSasSignatureValues sigDelete = new BlobServiceSasSignatureValues(blobExpiryTime, blobPermissionDelete).setStartTime(OffsetDateTime.now());
Log.log(LOGCLASS_NAME, "###### sas info create: ", LogLevel.info);

String sasQueryParamsRead = blobClient.generateUserDelegationSas(sigRead, userDelegationKey);
String sasQueryParamsDelete = blobClient.generateUserDelegationSas(sigDelete, userDelegationKey);

blobInfo.ok = true;
blobInfo.url = blobClient.getBlobUrl();
blobInfo.sasQueryParamsRead = sasQueryParamsRead;
blobInfo.sasQueryParamsDelete = sasQueryParamsDelete;
blobInfo.md5 = upload.getContentMd5();
blobInfo.contentType = blobClient.getProperties().getContentType();
Log.log(LOGCLASS_NAME, "###### Done creating/uploaded file to blob ", LogLevel.info);

I dont have the stacktrace, but I do have the original error which I catch:
JVM: java.lang.RuntimeException: Max retries 3 times exceeded. Error Details: DefaultAzureCredential authentication failed. ---> ManagedIdentityCredential authentication failed. Error Details: MSI: Failed to acquire tokens after retrying 5 times
	at com.azure.core.http.policy.RetryPolicy.lambda$attemptAsync$1(RetryPolicy.java:127)
	at reactor.core.publisher.FluxOnErrorResume$ResumeSubscriber....)

If I change the highlighted to be accountname and account key then it does not complain

**Comment by jesper-werge** [comment]
@billwert 
Just another comment, as this is stdin->stdout process the code above is running for each request/file one by one, and the caching we hope to achieve is for the disk so multiple threads can consume the tokens.

**Comment by billwert** [comment]
Hi @jesper-werge! Sorry for the delay here.

There's a couple options. First, we're going to add token caching to ManagedIdentityCredential in a release later this year. [This](https://github.com/Azure/azure-sdk-for-net/issues/25361) is tracking the work in .NET but we'll be doing it across all languages. 

If you need something faster than that, you can use your disk based cache in an implementation of [`TokenCredential`](https://docs.microsoft.com/en-us/java/api/com.azure.core.credential.tokencredential?view=azure-java-stable). Your credential would then be useful in authenticating to something like `SecretClient`.

**Comment by joshfree** [comment]
@billwert could you update this issue as appropriate?

**Comment by billwert** [comment]
Hello @jesper-werge! This was added in our [November 2022 release](https://github.com/Azure/azure-sdk-for-java/blob/main/sdk/identity/azure-identity/CHANGELOG.md#170-2022-11-04).
