### ISSUE TITLE
How to use Azure SDK for Container Service Management to upgrade all nodes in all node pools?

### ISSUE THREAD

**Issue by xinyan1984** [Azure/azure-sdk-for-java#26164]
**Query/Question**
which api is used for "Upgrade all nodes in all node pools"?
the corresponding az commond is as below
az aks upgrade \
    --resource-group myResourceGroup \
    --name myAKSCluster \
    --node-image-only

***Why is this not a Bug or a feature Request?***
not clear if the sdk already provide the related api ?

**Setup (please complete the following information if applicable):**
<parent>
    <groupId>com.microsoft.azure</groupId>
    <artifactId>azure-parent</artifactId>
    <version>1.41.2</version>
  </parent>
  <artifactId>azure-mgmt-containerservice</artifactId>
  <name>Microsoft Azure SDK for Container Service Management</name>
 
 **Information Checklist**
 Kindly make sure that you have added all the following information above and checkoff the required fields otherwise we will treat the issuer as an incomplete report
- for Upgrade a specific node pool i can find the related client api just as below, but which api is used for "Upgrade all nodes in all node pools"?
- this.azure().containerServices().manager().inner().agentPools().upgradeNodeImageVersionAsync(
                this.resourceGroupName(),
                this.getCluster().resourceName(),
                this.getAgentPoolName(),
                AzureCallbacks.adapt(callback));
    }
-  az aks nodepool upgrade \
    --resource-group myResourceGroup \
    --cluster-name myAKSCluster \
    --name mynodepool \
    --node-image-only

**Comment by joshfree** [comment]
@weidongxu-microsoft could you please help route this question from @xinyan1984?

**Comment by weidongxu-microsoft** [comment]
@xinyan1984

This is the only API to update node pool.

CLI just calls them for you to all node pools (you can add `--debug` to CLI command and see multiple POST calls.

PS: it is recommended to upgrade to new Java SDK here https://aka.ms/azsdk/java/mgmt
Code is mostly compatible, except for authenticate part.
