### ISSUE TITLE
Improve the code quality of azure-spring-boot-samples

### ISSUE THREAD

**Issue by backwind1233** [Azure/azure-sdk-for-java#26169]
### Content

Address quality issues mentioned in the doc: [Thing to do to before GA](https://microsoft-my.sharepoint.com/:w:/p/limolkova/EdnvSOq_Q0hJhxhQ4pgKJZsBuCmTa-4-lKL24p7p55Y_Og?e=FeTemo&CID=28993409-568a-f27a-736c-6d3606be4b4e&ovuser=72f988bf-86f1-41af-91ab-2d7cd011db47%2Czhihaoguo%40microsoft.com&sourceId=&params=%7B%22AppName%22%3A%22Teams-Desktop%22%2C%22AppVersion%22%3A%2227%2F21110108719%22%7D)

- [x] #26310

**Problem**

[Fixed]Here is some known issues:

- multiple-namespaces
  - Migrate  bean definition to a configuration class
    - Rename QueueReceiveController, should not be ***controller, migrate bean inside the controller to configuration class.
    - Migrate  bean definition inside ServiceBusIntegrationApplication to a configuration class.
    - Migrate  bean definition inside QueueSendController to a configuration class.
    - Migrate  bean definition inside QueueReceiveController to a configuration class.
    - Rename QueueReceiveController.
  - Let QueueSendController implement CommandlineRunner to send message in auto way.

**Goal** 
Find all problems in sample repository and solve these problems.

**Solution**

- Go through all the samples to make sure our code quality is production-ready.

[Spring Cloud Azure Samples improvement Track](https://microsoftapc.sharepoint.com/:x:/r/teams/Springintegration/_layouts/15/Doc.aspx?sourcedoc=%7BFF2DCA0E-B50C-4E6E-AF89-C13045697C89%7D&file=Spring%20Cloud%20Azure%20Samples%20improvement%20Track.xlsx&action=default&mobileredirect=true)

<html>
<body>

<body link="#0563C1" vlink="#954F72">

Sample Name | code quality 
-- | --
aad-resource-server |  
aad-resource-server-by-filter |  
aad-resource-server-by-filter-stateless |  
aad-resource-server-obo |  
aad-web-application |  
aad-web-application-and-resource-server |  
aad-b2c-web-application |  
aad-b2c-resource-server |  
spring-security |  
azure-appconfiguration-conversion-sample-complete |  
azure-appconfiguration-conversion-sample-initial |  
azure-appconfiguration-sample |  
feature-management-sample |  
feature-management-web-sample |  
azure-cloud-foundry-service-sample |  
spring-cloud-azure-data-cosmos-sample |  
spring-cloud-azure-cosmos-sample |  
cosmos-multi-database-multi-account |  
cosmos-multi-database-single-account |  
eventhubs-integration |  
spring-cloud-azure-sample-eventhubs-kafka |  
eventhubs-binder |  
eventhubs-multibinders |  
run-with-command-line-server-side |  
run-with-command-line-client-side |  
keyvault-certificates-client-side |  
keyvault-certificates-server-side |  
single-property-source |  
multiple-property-source |  
servicebus-jms-queue |  
servicebus-jms-topic |  
servicebus-queue-binder |  
servicebus-multibinders |  
servicebus-topic-binder |  
multiple-namespaces |  
single-namespace |  
storage-blob-sample |  
storage-file-sample |  
storage-queue-operation |  
storage-queue-integration |  
spring-petclinic-microservices |  

</body>
</html>
</div>
</body>
</html>

**Comment by saragluna** [comment]
https://github.com/Azure-Samples/azure-spring-boot-samples/pull/608
