### ISSUE TITLE
Use default jacoco setting for all spring-cloud-azure modules @moary

### ISSUE THREAD

**Issue by chenrujun** [Azure/azure-sdk-for-java#26175]
## jacoco-maven-plugin

We should delete the following contents:
```
<jacoco.min.linecoverage>xxx</jacoco.min.linecoverage>
<jacoco.min.branchcoverage>xxx</jacoco.min.branchcoverage>
```

in these modules:

 - [x] spring-cloud-azure-actuator
 - [x] spring-cloud-azure-actuator-autoconfigure
 - [ ] spring-cloud-azure-autoconfigure
 - [x] spring-cloud-azure-core
 - [x] spring-cloud-azure-resourcemanager
 - [x] spring-cloud-azure-service
 - [x] spring-cloud-azure-stream-binder-eventhubs
 - [x] spring-cloud-azure-stream-binder-eventhubs-core
 - [x] spring-cloud-azure-stream-binder-servicebus
 - [x] spring-cloud-azure-stream-binder-servicebus-core
 - [x] spring-cloud-azure-stream-binder-test
 - [x] spring-cloud-azure-trace-sleuth
 - [x] spring-integration-azure-core
 - [x] spring-integration-azure-eventhubs
 - [x] spring-integration-azure-servicebus
 - [x] spring-integration-azure-storage-queue
 - [x] spring-messaging-azure
 - [x] spring-messaging-azure-eventhubs
 - [x] spring-messaging-azure-servicebus
 - [x] spring-messaging-azure-storage-queue

Add more tests if pipeline failed after delete these contents.

**Comment by saragluna** [comment]
Closed in https://github.com/Azure/azure-sdk-for-java/pull/26187.
