### ISSUE TITLE
Track unit test related issues for Spring Cloud Azure modules

### ISSUE THREAD

**Issue by moarychan** [Azure/azure-sdk-for-java#26171]
Legacy test cases todo list:
- [x] Improve the existing test cases quality;
- [x] Need add Cosmos reactive auto-configuration test cases;
- ~~[ ] Nees add KeyVault reactive test cases;~~ -> No need to add Reactive UTs
- [x] Unit tests class name should end with `*Tests`; test method name can start without `test`;
- ~~[ ] Need more Cloud foundry test cases and sample update;~~  Low priority, will ignore first.
- ~~[ ] Need a new way to test the service bus binder and event hubs binder;~~ Low priority, will ignore first.
- [x] Add UTs for `spring-cloud-azure-resourcemanager`
- [x] Add UTs for `spring-cloud-azure-stream-binder-eventhubs-core`
- [x] Add UTs for `spring-cloud-azure-stream-binder-servicebus-core`
- ~~[ ] Enable Jacoco plugin for `spring-cloud-azure-starter-keyvault-certificates`~~ Low priority, will ignore first.

**Comment by saragluna** [comment]
Closed in #26620.
