### ISSUE TITLE
Dynamic query in azure-spring-data-cosmos?

### ISSUE THREAD

**Issue by pratikgawali** [Azure/azure-sdk-for-java#26186]
I have a use case for filtering data based on the different filter criteria provided by the clients. So, I would like to form a dynamic query depending on whether the input is provided by the user or not.
For eg: if the user has provided filter criteria a, b and c then the query should be something like "Select * from xyz where a = something and b = something and c = something". But if the user has provided only a and c then the query must be something like "Select * from xyz where a = something and c = something".

I think this is something that can be achieved using 'com.azure.spring.data.cosmos.core.query.Criteria' but I am not able to figure out how. Is there any documentation/tutorial/example to explain how to use the library?

**Comment by kushagraThapar** [comment]
@pratikgawali  - I see this issue got closed because of automation, wondering, if you are still facing this issue. Feel free to re-open this if that's the case, apologies for the delay on this issue.
