### ISSUE TITLE
[FEATURE REQ] Investigate the possibility of Spring Commercial Support with Azure SDKs

### ISSUE THREAD

**Issue by saragluna** [Azure/azure-sdk-for-java#26193]
**Is your feature request related to a problem? Please describe.**
Spring now has a commercial support timeline, https://spring.io/projects/spring-boot#support, we should investigate the possibility of supporting extra Spring Boot versions in Spring Cloud Azure. The first step is to find whether current Azure SDKs can work with multiple Spring Boot versions.  Since now it's compatible with Spring Boot 2.5 and 2.6, we should test with a lower Spring Boot version. We should test Azure SDKs with Spring Boot 2.2 and find the incompatibilities. 

**We should check both Spring MVC and Spring WebFlux to see whether the SDKs can work with both.** 

**Describe the solution you'd like**
We should test Azure SDKs with Spring Boot 2.2 and find the incompatibilities. Test SDK clients used in Spring Cloud Azure now with Spring Boot 2.2
- Azure Identity
- HTTP clients: Key Vault secrets, Storage Blob
- AMQP clients: Event Hubs, Service Bus

**Comment by Netyyyy** [comment]
# Test records:
1.cosmos：
  1）version：spring-boot 2.2.6.RELEASE; azure-cosmos 4.23.0
  2）result: 
![image](https://user-images.githubusercontent.com/92105726/149093645-1a81d9da-d0dc-455c-803f-1e40fe5fdc96.png)
2.storage client：
  1）version：spring-boot 2.2.6.RELEASE; azure-storage-common 12.14.1; azure-storage-blob 12.14.2
  2）result: 
![image](https://user-images.githubusercontent.com/92105726/149094935-0245fffe-2bda-4f5e-8d86-38175aa8fa35.png)
3.service bus：
  1）version：spring-boot 2.2.6.RELEASE; azure-messaging-servicebus 7.5.1
  2）result: 
![image](https://user-images.githubusercontent.com/92105726/149095104-d4faacb5-c61a-40fb-bb2e-8c9022331be1.png)

**Comment by yiliuTo** [comment]
Close this issue for the conclustion has been given.
