### ISSUE TITLE
[FEATURE REQ] Add spring related modules in SpotBugs page and CheckStyle page.

### ISSUE THREAD

**Issue by chenrujun** [Azure/azure-sdk-for-java#26195]
### Context

In the SpotBugs page and CheckStyle page: https://github.com/Azure/azure-sdk-for-java

![image](https://user-images.githubusercontent.com/13167207/147512829-b9188ad9-b0ff-45e9-b231-7bc12c729b19.png)

### Problem
Spring related modules are not included. For example azure-spring-boot.

### Goal
Make spring related modules appear in SpotBugs page and CheckStyle page.

**Comment by weshaggard** [comment]
@hallipr can you please have a look?

**Comment by chenrujun** [comment]
Hi, @hallipr , any progress of this issue?

**Comment by stliu** [comment]
@hallipr any update?

**Comment by kurtzeborn** [comment]
@stliu looks like these badges were removed from the readme with this pr: https://github.com/Azure/azure-sdk-for-java/commit/1fb167678ec39ed3ecc5dfcf6b2cd924db4d1c8c

**Comment by chenrujun** [comment]
@kurtzeborn 

Thank you for your check.

Closing this issue because these badges are removed.
