### ISSUE TITLE
[BUG] micrometer version in azure-sdk-bom conflicts with spring-boot-dependencies

### ISSUE THREAD

**Issue by jbkervyn** [Azure/azure-sdk-for-java#26217]
**Describe the bug**
In  azure-sdk-bom 1.0.6, the micrometer version is 1.7.3 while the one provided by spring boot 2.6.1 is 1.8.0. In the README of azure-spring-boot-bom, it's supposed to be supported.

So if you would have in your depenencyManagement section the following : 

`<dependency>
                <groupId>com.azure</groupId>
                <artifactId>azure-sdk-bom</artifactId>
                <version>${azure-sdk-bom.version}</version>
                <type>pom</type>
                <scope>import</scope>
            </dependency>
            <dependency>
                <groupId>com.azure.spring</groupId>
                <artifactId>azure-spring-boot-bom</artifactId>
                <version>${azure-spring-boot-bom.version}</version>
                <type>pom</type>
                <scope>import</scope>
            </dependency>`

The build would fail. 
***Exception or Stack Trace***

Caused by: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'simpleMeterRegistry' defined in class path resource [org/springframework/boot/actuate
/autoconfigure/metrics/export/simple/SimpleMetricsExportAutoConfiguration.class]: Initialization of bean failed; nested exception is java.lang.NoClassDefFoundError: io/micrometer/core/
instrument/binder/system/DiskSpaceMetrics

*** Wokaround ***

Adding this in the dependencyMangagement section solves the problem

```
<dependency>
                <groupId>io.micrometer</groupId>
                <artifactId>micrometer-core</artifactId>
                <version>1.8.0</version> 
            </dependency>
```

**Comment by joshfree** [comment]
@pallavit could you please assist?

/cc @saragluna

**Comment by pallavit** [comment]
Thanks for reporting the issue, will investigate and get back to you.

**Comment by pallavit** [comment]
We have removed external dependencies from azure-sdk-bom.
