### ISSUE TITLE
[QUERY] Usage of Context in formrecognizer API

### ISSUE THREAD

**Issue by tigermarques** [Azure/azure-sdk-for-java#26210]
**Query/Question**
I would like to know what is the purpose of the `Context` that can be passed to all operations in the form recognizer java sdk. Looking at the code, I can only follow the trail up until the REST call is made, but I cannot see what is the actual purpose of this variable and what can I do with it. Is there any documentation available for this? What are the use cases?

**Setup:**
 - Library/Libraries: [com.azure:azure-ai-formrecognizer:3.1.4 (groupId:artifactId:version)]

**Comment by srnagar** [comment]
@tigermarques `Context` is a property bag that can be used to add any custom data. It can then be used to customize an HTTP request. You can create your own [custom HTTP pipeline policy](https://docs.microsoft.com/en-us/azure/developer/java/sdk/http-client-pipeline#http-pipeline) to access this context and modify the HTTP request. 

[AddHeadersFromContextPolicy](https://github.com/Azure/azure-sdk-for-java/blob/main/sdk/core/azure-core/src/main/java/com/azure/core/http/policy/AddHeadersFromContextPolicy.java#L34-L36) is an example of a policy that adds headers to a request when the headers are added to the `Context`.

Another purpose is to pass a [custom context for distributing tracing](https://docs.microsoft.com/en-us/azure/developer/java/sdk/tracing#pass-trace-context-explicitly).

Note that this `Context` is available for all new Azure libraries in `com.azure` Maven group and is not specific to Form Recognizer. So, this is applicable for other Azure services too. 

Please let us know if you have any further questions.

**Comment by tigermarques** [comment]
Thanks a lot! This is exactly the kind of example I was looking for.
