### ISSUE TITLE
Authentication Azure.authenticate(new File("my.azureauth")).withDefaultSubscription()

### ISSUE THREAD

**Issue by antonio-rodriges** [Azure/azure-sdk-for-java#26218]
This page states: https://github.com/Azure/azure-sdk-for-java/blob/main/sdk/resourcemanager/docs/MIGRATION_GUIDE.md

In old version (com.microsoft.azure.management.**)

Azure azure = Azure.authenticate(new File("my.azureauth")).withDefaultSubscription();

**In new version, this feature has been removed. If this creates concern on your side, please file an issue to let us know.**

It was very convenient to authenticate like this, I could create files for each case - now I have to change code or create my parsing facilities - very inconvenient.

**Comment by joshfree** [comment]
@weidongxu-microsoft could you please follow up with this migration guide issue reported by @antonio-rodriges?

**Comment by weidongxu-microsoft** [comment]
@antonio-rodriges 

The feature is not supported in track2 (at least for now), partly for security reason.

Personally, as dev, I usually create a few scripts of different env variables for different cases, and load them depends on my case.

If you do feel this auth file feature is important to you, I can forward this request to identity team.

**Comment by antonio-rodriges** [comment]
I think it is important and there should be a standard mechanism (without creating my own ENV vars) for authentication using params defined in a file as it was in the old version (credentials file).
________________________________

**Comment by weidongxu-microsoft** [comment]
@g2vinay 

Does azure-identity have plan to support file auth?

**Comment by g2vinay** [comment]
This feature is not being supported currently due to security reasons.
You can try loading details into environment from your files, but not recommend it as its easy for data to be compromised especially in production environments.
