### ISSUE TITLE
Refactor petclinic samples

### ISSUE THREAD

**Issue by backwind1233** [Azure/azure-sdk-for-java#26234]
Need some more detail: 
1. Refactor petclinic samples using `spring-cloud-azure-starter-data-cosmos` instead of `azure-spring-data-cosmos`
2. Refactored with terraform:
  - for now, to run the sample, users need to configure several properties.
  - since we have refactored many of our samples with terraform and defaultcredential, it's better to refactor this to provide our users with the same experience.
3. Make the dependency of petclinic samples clean, remove duplicated and unused dependencies.
4. Format the dependency of petclinic samples with the same indent. 
5. Delete testing code and dependency.
5. use bom Linked in this [PR](https://github.com/Azure-Samples/azure-spring-boot-samples/pull/131)
![image](https://user-images.githubusercontent.com/4465723/148907929-c0ebef8a-123a-46ce-ad71-65914fcc8a7f.png)

**Comment by hui1110** [comment]
https://github.com/Azure-Samples/azure-spring-boot-samples/pull/186

**Comment by hui1110** [comment]
The corresponding pr has been merged.

**Comment by hui1110** [comment]
The corresponding pr has been merged.
