### ISSUE TITLE
Refactor spring-cloud-azure-messaging-storage-queue to follow the same convention of spring-cloud-azure-messaging-* libraries

### ISSUE THREAD

**Issue by yiliuTo** [Azure/azure-sdk-for-java#26273]
Refactor the code structure of **spring-cloud-azure-messaging-storage-queue** library to keep the same convention with other messaging libraries. Changes should include:
- Remove checkpoint logic
- Remove StorageQueueOperation
- Add Factory abstraction to create SDK client
- Add properties abstraction
Ref: https://gist.github.com/yiliuTo/352b071a717fd90c984bcf03ec5d0fb9

**Comment by saragluna** [comment]
Closed in #26472.
