### ISSUE TITLE
Delete unnecessary suppression in revapi.json, checkstyle-supressions.xml, spotbugs-exclude.xml. @moary

### ISSUE THREAD

**Issue by chenrujun** [Azure/azure-sdk-for-java#26288]
In Spring-Cloud-Azure  version 4.0. A lot of code quality related suppression can be deleted.
In `/eng/code-quality-reports/src/main/resources/`:
1. checkstyle/checkstyle-supressions.xml
2. revapi/revapi.json
3. spotbugs-exclude.xml

We need to check each item related to Spring-Cloud-Azure. Delete the item if it's not necessary more.

**Comment by saragluna** [comment]
Closed in #26459.
