### ISSUE TITLE
Add tracing back to petclinic

### ISSUE THREAD

**Issue by backwind1233** [Azure/azure-sdk-for-java#26306]
### Context
In this [PR](https://github.com/Azure-Samples/azure-spring-boot-samples/pull/131) ,`tracing-server, grafana-server, prometheus-server` were removed from docker-compose.yml, 

### Goal
- add them back to make the sample works.
- enable the Spring Cloud Azure Trace Sleuth in this sample.

**Comment by saragluna** [comment]
@moarychan assign this to you.

**Comment by moarychan** [comment]
Due to the limited support of Spring Cloud Azure Trace Sleuth and no library using storage, we will not add support for the time being.

**Comment by stliu** [comment]
closing it for now, no customer ask, reopen if anyone need it
