### ISSUE TITLE
Update MS doc - Deploy Spring Boot Application to the Azure Kubernetes Service

### ISSUE THREAD

**Issue by hui1110** [Azure/azure-sdk-for-java#26315]
Update MS doc - [Deploy Spring Boot Application to the Azure Kubernetes Service](https://docs.microsoft.com/en-us/azure/developer/java/spring-framework/deploy-spring-boot-java-app-on-kubernetes)

- Update az command 
- Test `jib-maven-plugin` plugin
- Test yaml configuration

**Comment by hui1110** [comment]
Doc update completed. Mainly fix the following issues. 
- When building the image and pushing the image to the registry I get the following error:
```text
[ERROR] I/O error for image [yonghuiku.azurecr.io/spring-boot-docker-complete]:
[ERROR]     java.net.SocketTimeoutException
[ERROR]     Read timed out
[ERROR] I/O error for image [yonghuiku.azurecr.io/spring-boot-docker-complete]:
[ERROR]     java.net.SocketTimeoutException
[ERROR]     Read timed out
```
- Deploy using Kubernetes resource view. Error 'Invalid YAML format' when adding YAML file.

**Comment by saragluna** [comment]
Closing this issue now.
