### ISSUE TITLE
[FEATURE REQ] Improve javadoc for BlobParallelUploadOptions

### ISSUE THREAD

**Issue by rdp** [Azure/azure-sdk-for-java#26323]
As a note there are constructors for BlobParallelUploadOptions which accept an InputStream.  Would be nice to mention in the javadoc that azure itself doesn't close the input stream, the caller must do that themselves after.  Thanks much!

**Comment by rickle-msft** [comment]
@rdp Thanks for mentioning this. I'll get it added into the javadocs!

**Comment by amishra-dev** [comment]
Thanks for this suggestion. @rickle-msft Rick, let talk about it and get this done across the board on all APIs.

**Comment by rdp** [comment]
Thanks!
