### ISSUE TITLE
[FEATURE REQ] Publish with javadocs

### ISSUE THREAD

**Issue by rdp** [Azure/azure-sdk-for-java#26322]
When consuming the sdk via maven, the published jar files don't include any javadocs.  Might be nice to have them there to make the library easier to consume.  Thanks!

**Comment by joshfree** [comment]
Thanks for filing this request, @rdp.  @alzimmermsft ptal

**Comment by alzimmermsft** [comment]
Hi @rdp, thanks for filing this. For each SDK released there should also be a sources variant which contains the source Javadocs.

For example, https://repo1.maven.org/maven2/com/azure/azure-core/1.24.0/ has `azure-core-1.24.0-sources.jar` which contains the Javadocs along with the source code.

**Comment by rdp** [comment]
OK sounds good.

**Comment by alzimmermsft** [comment]
Closing as Azure SDKs release a sources JAR alongside the regular JAR that includes source code with comments.
