### ISSUE TITLE
[BUG] Changes to CName in private dsn zone is ignored

### ISSUE THREAD

**Issue by anderius** [Azure/azure-sdk-for-java#26357]
CnameRecordSetImpl is missing an implementation of prepareForUpdate, causing only the common fields to be copied over for update. For cnames, the "cname" property is not common with the other record sets, and is therefore ignored.

See https://github.com/Azure/azure-sdk-for-java/pull/26128.

This is also support request 2201050010000667.

**Comment by joshfree** [comment]
@weidongxu-microsoft could you please follow up with @anderius

**Comment by weidongxu-microsoft** [comment]
2.11.0 just get released to maven (with azure-resourcemanager).

Thanks again.
https://github.com/Azure/azure-sdk-for-java/releases/tag/azure-resourcemanager-privatedns_2.11.0
