### ISSUE TITLE
Can Spring Cloud Azure starter for App Configuration work with App Configuration Config

### ISSUE THREAD

**Issue by saragluna** [Azure/azure-sdk-for-java#26354]
The `spring-cloud-azure-starter-appconfiguration` uses the prefix `spring.cloud.azure.appconfiguration` and the [azure-spring-cloud-starter-appconfiguration-config](https://github.com/Azure/azure-sdk-for-java/tree/main/sdk/appconfiguration/azure-spring-cloud-starter-appconfiguration-config) also uses the same prefix. Can these two work together?

**Comment by hui1110** [comment]
**Can work together**, the test steps are as follows:
1. Add the following to pom.xml.
```xml
    <dependency>
      <groupId>com.azure.spring</groupId>
      <artifactId>azure-spring-cloud-starter-appconfiguration-config</artifactId>
      <version>2.2.0</version>
    </dependency>
    <dependency>
      <groupId>com.azure.spring</groupId>
      <artifactId>spring-cloud-azure-starter-appconfiguration</artifactId>
      <version>4.0.0-beta.3</version>
    </dependency>
```
2. Create an [App Configuration](https://ms.portal.azure.com/#blade/HubsExtension/BrowseResource/resourceType/Microsoft.AppConfiguration%2FconfigurationStores), import the following data file 'sample-data.json' into App Configuration.
```json
{
  "/application/config.message": "hello from default application",
  "/application_dev/config.message": "hello from default application dev profile",
  "/foo/config.message": "hello from foo application",
  "/foo_dev/config.message": "hello from foo application dev profile"
}

```
3. Configure the bootstrap.yaml. 
```yaml
spring:
  cloud:
    azure:
      appconfiguration:
        stores:
          - connection-string: ${CONFIG_STORE_CONNECTION_STRING}
        connection-string: ${CONFIG_STORE_CONNECTION_STRING}
```
Change the connection-string value with the Access Key value of the App Configuration.
4. Code.
```java
@SpringBootApplication
@EnableConfigurationProperties(MessageProperties.class)
public class AzureConfigApplication {
    public static void main(String[] args) {
        SpringApplication.run(AzureConfigApplication.class, args);
    }
}
```
```java
@ConfigurationProperties(prefix = "config")
public class MessageProperties {
    private String message;

    public String getMessage() {
        return message;
    }

    public void setMessage(String message) {
        this.message = message;
    }
}
```
```java
@RestController
public class HelloController {

    @Autowired
    ConfigurationClient  configurationClient;

    private final MessageProperties properties;

    public HelloController(MessageProperties properties) {
        this.properties = properties;
    }

    @GetMapping
    public String getMessage() {

        ConfigurationSetting configurationSetting =
            configurationClient.getConfigurationSetting("/application_dev/config.message",null);

        System.out.println(configurationSetting.getValue());

        return "Message: " + properties.getMessage();
    }
}
```
5. Start the application.
Access http://localhost:8080, it return **Message: hello from default application**.
The console will print the following information:
```console
hello from default application dev profile
```
- Also works together when the value of connection-string in 'bootstrap.yaml' is different.

**Comment by saragluna** [comment]
@mrm9084 fyi.

**Comment by mrm9084** [comment]
@saragluna I think part of it was being able disable one without the other because they share `spring.cloud.azure.appconfiguration.enabled` as a config.

**Comment by saragluna** [comment]
Given more users will choose the configuration client:
- For most cases, users will use the configuration client, and if no connection string is provided for the other, the auto-configuration of the raw client won't be enabled.
- For some other cases, users use the raw client auto-configuration only, then they won't add the configuration client to the classpath.

**Comment by saragluna** [comment]
Closing this issue now.
