### ISSUE TITLE
Propose a solution for users run petclinic samples

### ISSUE THREAD

**Issue by backwind1233** [Azure/azure-sdk-for-java#26361]
**Context**
There are two ways to run petclinic samples.
1. Run sample with shell scripts.
2. Run sample with Docker-Compose.

We use petclinic samples to demonstrate our libraries' features, such as keyvault, cosmos, defaultCredential.

**Goal**
1. Investigate whether it's a valuable thing to use defaultCredential in docker containers for petclinic samples.
2. Investigate the way cost the least amount of resources for users to run petclinic samples.
> The `resources` here means time and computer resources such as cpu, mem etc.

**References**
https://github.com/Azure/azure-cli/blob/dev/Dockerfile
mount to ${HOME}/.azure:/root/.azure

**Comment by stliu** [comment]
closing it, no one ask for it
