### ISSUE TITLE
Add AAD support for petclinic samples

### ISSUE THREAD

**Issue by backwind1233** [Azure/azure-sdk-for-java#26362]
**Context**
In our sample repository, we hope to use one sample to demonstrate how to integrate Spring Cloud Azure libraries as much as possible, the petclinic sample has integrate with keyvault, cosmos, but hasn't integrate AAD.

Use AAD to authenticate and authorize is a common feature for most Azure users, in Spring Cloud Azure libraries, AAD libraries are the most used ones, we can integrate AAD in petclinic sample too.

**Goal**
Add aad support in petclinic samples to demonstrate aad features.

**Comment by stliu** [comment]
changing this to P3, since there is no ask for it at the moment
