### ISSUE TITLE
Links to Cognitive Services sources and samples broken in README.md

### ISSUE THREAD

**Issue by lenala** [Azure/azure-sdk-for-java#2638]
All links to Cognitive Services sources and samples in README.md are not valid.

**Comment by vhvb1989** [comment]
@lenala I don't see cognitive Services docs in main README.md, can you mention more details for this issue or if we can close it please?

**Comment by vhvb1989** [comment]
There is no info about cognitive services in root Readme and there is not readme file in sdk/cognitiveservices path.
Closing this
