### ISSUE TITLE
Use Azure Resource Manager to retrieve connection string

### ISSUE THREAD

**Issue by backwind1233** [Azure/azure-sdk-for-java#26407]
Linked this [PR](https://github.com/Azure-Samples/azure-spring-boot-samples/pull/136)

In this pr, section:`### Use Azure Resource Manager to retrieve connection string` is deleted, we need to investigate whether this section needs to be maintained.

**Comment by saragluna** [comment]
@moarychan fyi.

**Comment by backwind1233** [comment]
Close this issue, Since the related PR is merged.
