### ISSUE TITLE
[BUG] Unable to use User Assigned Managed Identity in Azure Hosted Services

### ISSUE THREAD

**Issue by shikhil-gupta** [Azure/azure-sdk-for-java#26408]
**Describe the bug**
Unable to use User Assigned Managed Identity in Azure Synapse Spark Cluster. So basically I have enabled user assigned managed in Azure Synapse analytics workspace to access Azure keyvault rom Java/Scala code. I have integrated azure-security-keyvault-secret java library in code (https://github.com/Azure/azure-sdk-for-java/tree/azure-security-keyvault-secrets_4.3.5/sdk/identity/azure-identity). 

***Exception or Stack Trace***
Add the exception log and stack trace if available
22/01/11 09:41:08 INFO testclass$: KeyVault Triggered Now
22/01/11 09:41:08 ERROR EnvironmentCredential: Azure Identity => ERROR in EnvironmentCredential: Missing required environment variable AZURE_CLIENT_ID
22/01/11 09:41:08 INFO JacksonVersion: Package versions: jackson-annotations=2.10.0, jackson-core=2.10.0, jackson-databind=2.10.0, jackson-dataformat-xml=2.10.0, jackson-datatype-jsr310=2.10.0, azure-core=1.22.0
22/01/11 09:41:09 INFO DefaultsConfigSparkListener: Persisted __spark_conf_merge_records__.json
22/01/11 09:41:09 INFO RpcAppSender: Remote SparkContext server is opened on 10.13.32.82:18083, remoteSparkContext/remoteSparkContextEndpoint
22/01/11 09:41:09 INFO RpcAppSender: Sent driver info of local-1641894065187 to RPC history server
22/01/11 09:41:09 ERROR EnvironmentCredential: EnvironmentCredential authentication unavailable. Environment variables are not fully configured.To mitigate this issue, please refer to the troubleshooting guidelines here at https://aka.ms/azsdk/net/identity/environmentcredential/troubleshoot
22/01/11 09:41:09 INFO DefaultAzureCredential: Azure Identity => Attempted credential EnvironmentCredential is unavailable.
22/01/11 09:41:09 ERROR IdentityClient: MSI: Failed to acquire tokens after retrying 3 times
22/01/11 09:41:09 ERROR ManagedIdentityCredential: Azure Identity => ERROR in getToken() call for scopes [https://vault.azure.net/.default]: MSI: Failed to acquire tokens after retrying 3 times
22/01/11 09:41:09 ERROR AccessTokenCache: Failed to acquire a new access token.
22/01/11 09:41:39 ERROR EnvironmentCredential: EnvironmentCredential authentication unavailable. Environment variables are not fully configured.To mitigate this issue, please refer to the troubleshooting guidelines here at https://aka.ms/azsdk/net/identity/environmentcredential/troubleshoot
22/01/11 09:41:39 INFO DefaultAzureCredential: Azure Identity => Attempted credential EnvironmentCredential is unavailable.
22/01/11 09:41:39 ERROR IdentityClient: MSI: Failed to acquire tokens after retrying 3 times
22/01/11 09:41:39 ERROR ManagedIdentityCredential: Azure Identity => ERROR in getToken() call for scopes [https://vault.azure.net/.default]: MSI: Failed to acquire tokens after retrying 3 times
22/01/11 09:41:39 ERROR AccessTokenCache: Failed to acquire a new access token.
22/01/11 09:42:09 ERROR EnvironmentCredential: EnvironmentCredential authentication unavailable. Environment variables are not fully configured.To mitigate this issue, please refer to the troubleshooting guidelines here at https://aka.ms/azsdk/net/identity/environmentcredential/troubleshoot
22/01/11 09:42:09 INFO DefaultAzureCredential: Azure Identity => Attempted credential EnvironmentCredential is unavailable.
22/01/11 09:42:09 ERROR IdentityClient: MSI: Failed to acquire tokens after retrying 3 times
22/01/11 09:42:09 ERROR ManagedIdentityCredential: Azure Identity => ERROR in getToken() call for scopes [https://vault.azure.net/.default]: MSI: Failed to acquire tokens after retrying 3 times
22/01/11 09:42:09 ERROR AccessTokenCache: Failed to acquire a new access token.
22/01/11 09:42:39 ERROR EnvironmentCredential: EnvironmentCredential authentication unavailable. Environment variables are not fully configured.To mitigate this issue, please refer to the troubleshooting guidelines here at https://aka.ms/azsdk/net/identity/environmentcredential/troubleshoot
22/01/11 09:42:39 INFO DefaultAzureCredential: Azure Identity => Attempted credential EnvironmentCredential is unavailable.
22/01/11 09:42:39 ERROR IdentityClient: MSI: Failed to acquire tokens after retrying 3 times
22/01/11 09:42:39 ERROR ManagedIdentityCredential: Azure Identity => ERROR in getToken() call for scopes [https://vault.azure.net/.default]: MSI: Failed to acquire tokens after retrying 3 times
22/01/11 09:42:39 ERROR AccessTokenCache: Failed to acquire a new access token.
22/01/11 09:42:39 INFO RetryPolicy: Retry attempts have been exhausted after 3 attempts.
22/01/11 09:42:39 WARN SecretAsyncClient: Failed to get secret - cosmosDBReadConnectingString
DefaultAzureCredential authentication failed. ---> ManagedIdentityCredential authentication failed. Error Details: MSI: Failed to acquire tokens after retrying 3 times
22/01/11 09:42:39 INFO KeyVaultClient: Exception message=DefaultAzureCredential authentication failed. ---> ManagedIdentityCredential authentication failed. Error Details: MSI: Failed to acquire tokens after retrying 3 times

[spark3-8-application_1641893074058_0002-Driver (stderr) (1).log](https://github.com/Azure/azure-sdk-for-java/files/7845982/spark3-8-application_1641893074058_0002-Driver.stderr.1.log)

**To Reproduce**
It is happening always. 

***Code Snippet***
Add the code snippet that causes the issue.
public class KeyVaultClient {

    private SecretClient secretClient;
    Logger logger = Logger.getLogger(KeyVaultClient.class.toString());

    public KeyVaultClient(String KeyVaultUrl) {
        DefaultAzureCredential defaultCredential = new DefaultAzureCredentialBuilder()
                .managedIdentityClientId("3c7acf3c-ad6f-4a64-82ed-2670145bb92e")
                .retryTimeout(duration -> Duration.ofSeconds(2))
                .build();
        secretClient = new SecretClientBuilder()
                .vaultUrl(KeyVaultUrl)
                .credential(defaultCredential)
                .buildClient();
    }

    public String getSecret(String secretKey) {
        try {
            KeyVaultSecret keyVaultSecret = secretClient.getSecret(secretKey);
            return keyVaultSecret.getValue();
        } catch (Exception exception) {
            logger.info("Exception message=" + exception.getMessage());
            exception.printStackTrace();
        }
        return "";
    }
}
**Expected behavior**
It should work out when deployed to azure hosted service. I am deploying to Azure Synapse.

**Screenshots**
[](url)

**Setup (please complete the following information):**
 - OS: Azure Synapse Spark cluster
 - IDE: [e.g. IntelliJ]
 - Library/Libraries: [e.g. com.azure:azure-core:1.16.0 (groupId:artifactId:version)]
 - Java version: 8
 - App Server/Environment: Spark Cluster deployed on Azure Synapse 
 
If you suspect a dependency version mismatch (e.g. you see `NoClassDefFoundError`, `NoSuchMethodError` or similar), please check out [Troubleshoot dependency version conflict article](https://aka.ms/azsdk/java/dependency/troubleshoot) first. If it doesn't provide solution for the problem, please provide:

**Additional context**
Same code working fine locally. As we know in local it uses Developer login to authenticate to keyvault. 

**Information Checklist**
Kindly make sure that you have added all the following information above and checkoff the required fields otherwise we will treat the issuer as an incomplete report
- [ ] Bug Description Added
- [ ] Repro Steps Added
- [ ] Setup information Added

**Comment by joshfree** [comment]
@billwert could you assist @shikhil-gupta with getting identity working in the configuration above?

**Comment by shikhil-gupta** [comment]
Hi @billwert Earlier I was using Azure-Identity 1.4.1 and now upgraded tp 1.4.2, I am seeing more accurate logs but problem are still not solved. Attached logs file also.

22/01/11 15:45:45 INFO testclass$: KeyVault Triggered Now
22/01/11 15:45:45 ERROR EnvironmentCredential: Azure Identity => ERROR in EnvironmentCredential: Missing required environment variable AZURE_CLIENT_ID
22/01/11 15:45:45 INFO JacksonVersion: Package versions: jackson-annotations=2.10.0, jackson-core=2.10.0, jackson-databind=2.10.0, jackson-dataformat-xml=2.10.0, jackson-datatype-jsr310=2.10.0, azure-core=1.22.0, Troubleshooting version conflicts: https://aka.ms/azsdk/java/dependency/troubleshoot
22/01/11 15:45:46 INFO DefaultsConfigSparkListener: Persisted __spark_conf_merge_records__.json
22/01/11 15:45:46 INFO RpcAppSender: Remote SparkContext server is opened on 10.4.160.140:18083, remoteSparkContext/remoteSparkContextEndpoint
22/01/11 15:45:46 ERROR EnvironmentCredential: EnvironmentCredential authentication unavailable. Environment variables are not fully configured.To mitigate this issue, please refer to the troubleshooting guidelines here at https://aka.ms/azsdk/net/identity/environmentcredential/troubleshoot
22/01/11 15:45:46 INFO DefaultAzureCredential: Azure Identity => Attempted credential EnvironmentCredential is unavailable.
22/01/11 15:45:46 ERROR IdentityClient: ManagedIdentityCredential authentication unavailable. Connection to IMDS endpoint cannot be established.
22/01/11 15:45:46 ERROR ManagedIdentityCredential: Azure Identity => ERROR in getToken() call for scopes [https://vault.azure.net/.default]: ManagedIdentityCredential authentication unavailable. Connection to IMDS endpoint cannot be established.
22/01/11 15:45:46 INFO DefaultAzureCredential: Azure Identity => Attempted credential ManagedIdentityCredential is unavailable.
22/01/11 15:45:46 ERROR SharedTokenCacheCredential: Azure Identity => ERROR in getToken() call for scopes [https://vault.azure.net/.default]: SharedTokenCacheCredential authentication unavailable. No accounts were found in the cache.
22/01/11 15:45:46 INFO DefaultAzureCredential: Azure Identity => Attempted credential SharedTokenCacheCredential is unavailable.
22/01/11 15:45:46 ERROR IdentityClient: IntelliJ Authentication not available. Please log in with Azure Tools for IntelliJ plugin in the IDE.
22/01/11 15:45:46 ERROR IntelliJCredential: Azure Identity => ERROR in getToken() call for scopes [https://vault.azure.net/.default]: IntelliJ Authentication not available. Please log in with Azure Tools for IntelliJ plugin in the IDE.
22/01/11 15:45:46 INFO DefaultAzureCredential: Azure Identity => Attempted credential IntelliJCredential is unavailable.
22/01/11 15:45:46 ERROR VisualStudioCacheAccessor: Failed to read Vs Code credentials from Linux Key Ring.
22/01/11 15:45:46 ERROR VisualStudioCodeCredential: Azure Identity => ERROR in getToken() call for scopes [https://vault.azure.net/.default]: Failed to read Vs Code credentials from Linux Key Ring.
22/01/11 15:45:46 INFO DefaultAzureCredential: Azure Identity => Attempted credential VisualStudioCodeCredential is unavailable.
22/01/11 15:45:46 ERROR IdentityClient: AzureCliCredential authentication unavailable. Azure CLI not installed.To mitigate this issue, please refer to the troubleshooting guidelines here at https://aka.ms/azsdk/java/identity/azclicredential/troubleshoot
22/01/11 15:45:46 ERROR IdentityClient: AzureCliCredential authentication unavailable. Azure CLI not installed.To mitigate this issue, please refer to the troubleshooting guidelines here at https://aka.ms/azsdk/java/identity/azclicredential/troubleshoot
22/01/11 15:45:46 ERROR AzureCliCredential: Azure Identity => ERROR in getToken() call for scopes [https://vault.azure.net/.default]: AzureCliCredential authentication unavailable. Azure CLI not installed.To mitigate this issue, please refer to the troubleshooting guidelines here at https://aka.ms/azsdk/java/identity/azclicredential/troubleshoot
22/01/11 15:45:46 INFO DefaultAzureCredential: Azure Identity => Attempted credential AzureCliCredential is unavailable.
22/01/11 15:45:46 ERROR PowershellManager: Unable to execute PowerShell. Please make sure that it is installed in your system
22/01/11 15:45:46 ERROR AzurePowerShellCredential: Azure Identity => ERROR in getToken() call for scopes [https://vault.azure.net/.default]: Unable to execute PowerShell. Please make sure that it is installed in your system
22/01/11 15:45:46 INFO DefaultAzureCredential: Azure Identity => Attempted credential AzurePowerShellCredential is unavailable.
22/01/11 15:45:46 ERROR AccessTokenCache: Failed to acquire a new access token.
22/01/11 15:45:48 INFO RpcAppSender: Sent driver info of local-1641915941873 to RPC history server
22/01/11 15:45:48 INFO AsyncEventQueue: Process of event SparkListenerApplicationStart(com.microsoft.teams.deviceanalytics.core.copyactivity.testclass$,Some(local-1641915941873),1641915940144,trusted-service-user,None,None,None) by listener RpcAppListener took 2.045485494s.
22/01/11 15:46:16 ERROR EnvironmentCredential: EnvironmentCredential authentication unavailable. Environment variables are not fully configured.To mitigate this issue, please refer to the troubleshooting guidelines here at https://aka.ms/azsdk/net/identity/environmentcredential/troubleshoot
22/01/11 15:46:16 INFO DefaultAzureCredential: Azure Identity => Attempted credential EnvironmentCredential is unavailable.
22/01/11 15:46:16 ERROR IdentityClient: ManagedIdentityCredential authentication unavailable. Connection to IMDS endpoint cannot be established.
22/01/11 15:46:16 ERROR ManagedIdentityCredential: Azure Identity => ERROR in getToken() call for scopes [https://vault.azure.net/.default]: ManagedIdentityCredential authentication unavailable. Connection to IMDS endpoint cannot be established.
22/01/11 15:46:16 INFO DefaultAzureCredential: Azure Identity => Attempted credential ManagedIdentityCredential is unavailable.
22/01/11 15:46:16 ERROR SharedTokenCacheCredential: Azure Identity => ERROR in getToken() call for scopes [https://vault.azure.net/.default]: SharedTokenCacheCredential authentication unavailable. No accounts were found in the cache.
22/01/11 15:46:16 INFO DefaultAzureCredential: Azure Identity => Attempted credential SharedTokenCacheCredential is unavailable.
22/01/11 15:46:16 ERROR IdentityClient: IntelliJ Authentication not available. Please log in with Azure Tools for IntelliJ plugin in the IDE.
22/01/11 15:46:16 ERROR IntelliJCredential: Azure Identity => ERROR in getToken() call for scopes [https://vault.azure.net/.default]: IntelliJ Authentication not available. Please log in with Azure Tools for IntelliJ plugin in the IDE.
22/01/11 15:46:16 INFO DefaultAzureCredential: Azure Identity => Attempted credential IntelliJCredential is unavailable.
22/01/11 15:46:16 ERROR VisualStudioCacheAccessor: Failed to read Vs Code credentials from Linux Key Ring.
22/01/11 15:46:16 ERROR VisualStudioCodeCredential: Azure Identity => ERROR in getToken() call for scopes [https://vault.azure.net/.default]: Failed to read Vs Code credentials from Linux Key Ring.
22/01/11 15:46:16 INFO DefaultAzureCredential: Azure Identity => Attempted credential VisualStudioCodeCredential is unavailable.
22/01/11 15:46:16 ERROR IdentityClient: AzureCliCredential authentication unavailable. Azure CLI not installed.To mitigate this issue, please refer to the troubleshooting guidelines here at https://aka.ms/azsdk/java/identity/azclicredential/troubleshoot
22/01/11 15:46:16 ERROR IdentityClient: AzureCliCredential authentication unavailable. Azure CLI not installed.To mitigate this issue, please refer to the troubleshooting guidelines here at https://aka.ms/azsdk/java/identity/azclicredential/troubleshoot
22/01/11 15:46:16 ERROR AzureCliCredential: Azure Identity => ERROR in getToken() call for scopes [https://vault.azure.net/.default]: AzureCliCredential authentication unavailable. Azure CLI not installed.To mitigate this issue, please refer to the troubleshooting guidelines here at https://aka.ms/azsdk/java/identity/azclicredential/troubleshoot
22/01/11 15:46:16 INFO DefaultAzureCredential: Azure Identity => Attempted credential AzureCliCredential is unavailable.
22/01/11 15:46:16 ERROR PowershellManager: Unable to execute PowerShell. Please make sure that it is installed in your system
22/01/11 15:46:16 ERROR AzurePowerShellCredential: Azure Identity => ERROR in getToken() call for scopes [https://vault.azure.net/.default]: Unable to execute PowerShell. Please make sure that it is installed in your system
22/01/11 15:46:16 INFO DefaultAzureCredential: Azure Identity => Attempted credential AzurePowerShellCredential is unavailable.
22/01/11 15:46:16 ERROR AccessTokenCache: Failed to acquire a new access token.
22/01/11 15:46:46 ERROR EnvironmentCredential: EnvironmentCredential authentication unavailable. Environment variables are not fully configured.To mitigate this issue, please refer to the troubleshooting guidelines here at https://aka.ms/azsdk/net/identity/environmentcredential/troubleshoot
22/01/11 15:46:46 INFO DefaultAzureCredential: Azure Identity => Attempted credential EnvironmentCredential is unavailable.
22/01/11 15:46:46 ERROR IdentityClient: ManagedIdentityCredential authentication unavailable. Connection to IMDS endpoint cannot be established.
22/01/11 15:46:46 ERROR ManagedIdentityCredential: Azure Identity => ERROR in getToken() call for scopes [https://vault.azure.net/.default]: ManagedIdentityCredential authentication unavailable. Connection to IMDS endpoint cannot be established.
22/01/11 15:46:46 INFO DefaultAzureCredential: Azure Identity => Attempted credential ManagedIdentityCredential is unavailable.
22/01/11 15:46:46 ERROR SharedTokenCacheCredential: Azure Identity => ERROR in getToken() call for scopes [https://vault.azure.net/.default]: SharedTokenCacheCredential authentication unavailable. No accounts were found in the cache.
22/01/11 15:46:46 INFO DefaultAzureCredential: Azure Identity => Attempted credential SharedTokenCacheCredential is unavailable.
22/01/11 15:46:46 ERROR IdentityClient: IntelliJ Authentication not available. Please log in with Azure Tools for IntelliJ plugin in the IDE.
22/01/11 15:46:46 ERROR IntelliJCredential: Azure Identity => ERROR in getToken() call for scopes [https://vault.azure.net/.default]: IntelliJ Authentication not available. Please log in with Azure Tools for IntelliJ plugin in the IDE.
22/01/11 15:46:46 INFO DefaultAzureCredential: Azure Identity => Attempted credential IntelliJCredential is unavailable.
22/01/11 15:46:46 ERROR VisualStudioCacheAccessor: Failed to read Vs Code credentials from Linux Key Ring.
22/01/11 15:46:46 ERROR VisualStudioCodeCredential: Azure Identity => ERROR in getToken() call for scopes [https://vault.azure.net/.default]: Failed to read Vs Code credentials from Linux Key Ring.
22/01/11 15:46:46 INFO DefaultAzureCredential: Azure Identity => Attempted credential VisualStudioCodeCredential is unavailable.
22/01/11 15:46:46 ERROR IdentityClient: AzureCliCredential authentication unavailable. Azure CLI not installed.To mitigate this issue, please refer to the troubleshooting guidelines here at https://aka.ms/azsdk/java/identity/azclicredential/troubleshoot
22/01/11 15:46:46 ERROR IdentityClient: AzureCliCredential authentication unavailable. Azure CLI not installed.To mitigate this issue, please refer to the troubleshooting guidelines here at https://aka.ms/azsdk/java/identity/azclicredential/troubleshoot
22/01/11 15:46:46 ERROR AzureCliCredential: Azure Identity => ERROR in getToken() call for scopes [https://vault.azure.net/.default]: AzureCliCredential authentication unavailable. Azure CLI not installed.To mitigate this issue, please refer to the troubleshooting guidelines here at https://aka.ms/azsdk/java/identity/azclicredential/troubleshoot
22/01/11 15:46:46 INFO DefaultAzureCredential: Azure Identity => Attempted credential AzureCliCredential is unavailable.
22/01/11 15:46:46 ERROR PowershellManager: Unable to execute PowerShell. Please make sure that it is installed in your system
22/01/11 15:46:46 ERROR AzurePowerShellCredential: Azure Identity => ERROR in getToken() call for scopes [https://vault.azure.net/.default]: Unable to execute PowerShell. Please make sure that it is installed in your system
22/01/11 15:46:46 INFO DefaultAzureCredential: Azure Identity => Attempted credential AzurePowerShellCredential is unavailable.
22/01/11 15:46:46 ERROR AccessTokenCache: Failed to acquire a new access token.
22/01/11 15:47:16 ERROR EnvironmentCredential: EnvironmentCredential authentication unavailable. Environment variables are not fully configured.To mitigate this issue, please refer to the troubleshooting guidelines here at https://aka.ms/azsdk/net/identity/environmentcredential/troubleshoot
22/01/11 15:47:16 INFO DefaultAzureCredential: Azure Identity => Attempted credential EnvironmentCredential is unavailable.
22/01/11 15:47:17 ERROR IdentityClient: ManagedIdentityCredential authentication unavailable. Connection to IMDS endpoint cannot be established.
22/01/11 15:47:17 ERROR ManagedIdentityCredential: Azure Identity => ERROR in getToken() call for scopes [https://vault.azure.net/.default]: ManagedIdentityCredential authentication unavailable. Connection to IMDS endpoint cannot be established.
22/01/11 15:47:17 INFO DefaultAzureCredential: Azure Identity => Attempted credential ManagedIdentityCredential is unavailable.
22/01/11 15:47:17 ERROR SharedTokenCacheCredential: Azure Identity => ERROR in getToken() call for scopes [https://vault.azure.net/.default]: SharedTokenCacheCredential authentication unavailable. No accounts were found in the cache.
22/01/11 15:47:17 INFO DefaultAzureCredential: Azure Identity => Attempted credential SharedTokenCacheCredential is unavailable.
22/01/11 15:47:17 ERROR IdentityClient: IntelliJ Authentication not available. Please log in with Azure Tools for IntelliJ plugin in the IDE.
22/01/11 15:47:17 ERROR IntelliJCredential: Azure Identity => ERROR in getToken() call for scopes [https://vault.azure.net/.default]: IntelliJ Authentication not available. Please log in with Azure Tools for IntelliJ plugin in the IDE.
22/01/11 15:47:17 INFO DefaultAzureCredential: Azure Identity => Attempted credential IntelliJCredential is unavailable.
22/01/11 15:47:17 ERROR VisualStudioCacheAccessor: Failed to read Vs Code credentials from Linux Key Ring.
22/01/11 15:47:17 ERROR VisualStudioCodeCredential: Azure Identity => ERROR in getToken() call for scopes [https://vault.azure.net/.default]: Failed to read Vs Code credentials from Linux Key Ring.
22/01/11 15:47:17 INFO DefaultAzureCredential: Azure Identity => Attempted credential VisualStudioCodeCredential is unavailable.
22/01/11 15:47:17 ERROR IdentityClient: AzureCliCredential authentication unavailable. Azure CLI not installed.To mitigate this issue, please refer to the troubleshooting guidelines here at https://aka.ms/azsdk/java/identity/azclicredential/troubleshoot
22/01/11 15:47:17 ERROR IdentityClient: AzureCliCredential authentication unavailable. Azure CLI not installed.To mitigate this issue, please refer to the troubleshooting guidelines here at https://aka.ms/azsdk/java/identity/azclicredential/troubleshoot
22/01/11 15:47:17 ERROR AzureCliCredential: Azure Identity => ERROR in getToken() call for scopes [https://vault.azure.net/.default]: AzureCliCredential authentication unavailable. Azure CLI not installed.To mitigate this issue, please refer to the troubleshooting guidelines here at https://aka.ms/azsdk/java/identity/azclicredential/troubleshoot
22/01/11 15:47:17 INFO DefaultAzureCredential: Azure Identity => Attempted credential AzureCliCredential is unavailable.
22/01/11 15:47:17 ERROR PowershellManager: Unable to execute PowerShell. Please make sure that it is installed in your system
22/01/11 15:47:17 ERROR AzurePowerShellCredential: Azure Identity => ERROR in getToken() call for scopes [https://vault.azure.net/.default]: Unable to execute PowerShell. Please make sure that it is installed in your system
22/01/11 15:47:17 INFO DefaultAzureCredential: Azure Identity => Attempted credential AzurePowerShellCredential is unavailable.
22/01/11 15:47:17 ERROR AccessTokenCache: Failed to acquire a new access token.
22/01/11 15:47:17 INFO RetryPolicy: Retry attempts have been exhausted after 3 attempts.
22/01/11 15:47:17 WARN SecretAsyncClient: Failed to get secret - cosmosDBReadConnectingString
EnvironmentCredential authentication unavailable. Environment variables are not fully configured.To mitigate this issue, please refer to the troubleshooting guidelines here at https://aka.ms/azsdk/net/identity/environmentcredential/troubleshoot
ManagedIdentityCredential authentication unavailable. Connection to IMDS endpoint cannot be established.
SharedTokenCacheCredential authentication unavailable. No accounts were found in the cache.
IntelliJ Authentication not available. Please log in with Azure Tools for IntelliJ plugin in the IDE.
Failed to read Vs Code credentials from Linux Key Ring.
AzureCliCredential authentication unavailable. Azure CLI not installed.To mitigate this issue, please refer to the troubleshooting guidelines here at https://aka.ms/azsdk/java/identity/azclicredential/troubleshoot
Unable to execute PowerShell. Please make sure that it is installed in your systemTo mitigate this issue, please refer to the troubleshooting guidelines here at https://aka.ms/azure-identity-java-default-azure-credential-troubleshoot
22/01/11 15:47:17 INFO KeyVaultClient: CredentialUnavailableException message=EnvironmentCredential authentication unavailable. Environment variables are not fully configured.To mitigate this issue, please refer to the troubleshooting guidelines here at https://aka.ms/azsdk/net/identity/environmentcredential/troubleshoot
ManagedIdentityCredential authentication unavailable. Connection to IMDS endpoint cannot be established.
SharedTokenCacheCredential authentication unavailable. No accounts were found in the cache.
IntelliJ Authentication not available. Please log in with Azure Tools for IntelliJ plugin in the IDE.
Failed to read Vs Code credentials from Linux Key Ring.
AzureCliCredential authentication unavailable. Azure CLI not installed.To mitigate this issue, please refer to the troubleshooting guidelines here at https://aka.ms/azsdk/java/identity/azclicredential/troubleshoot
Unable to execute PowerShell. Please make sure that it is installed in your systemTo mitigate this issue, please refer to the troubleshooting guidelines here at https://aka.ms/azure-identity-java-default-azure-credential-troubleshoot
[spark3-15-application_1641915896352_0001-Driver (stderr) (1).log](https://github.com/Azure/azure-sdk-for-java/files/7855749/spark3-15-application_1641915896352_0001-Driver.stderr.1.log)

**Comment by billwert** [comment]
@shikhil-gupta Hello! Still researching. It will be Friday Redmond time before I have anything further.

**Comment by billwert** [comment]
Managed Identity is currently unsupported by the Java Identity SDK. Support for this is planned for a future milestone. In the interim, we recommend using an EnvironmentCredential (either a secret or a certificate.)

**Comment by billwert** [comment]
Adding a link to the docs for folks who find this issue in the future: 
https://learn.microsoft.com/en-us/java/api/overview/azure/identity-readme?view=azure-java-stable#managed-identity-support
