### ISSUE TITLE
Storage - Blobs Cryptography Readme issue

### ISSUE THREAD

**Issue by hongli750210** [Azure/azure-sdk-for-java#26429]
**1.**
Section [Link](https://github.com/Azure/azure-sdk-for-java/tree/main/sdk/storage/azure-storage-blob-cryptography#troubleshooting)
![image](https://user-images.githubusercontent.com/74638143/149071416-1024e6b4-7a5d-4450-8ff7-c16467a058b1.png)
Suggestion:
1. Add link for `[error_codes]: https://docs.microsoft.com/rest/api/storageservices/blob-service-error-codes`
2. Add link for `[performance_tuning]: https://github.com/Azure/azure-sdk-for-java/wiki/Performance-Tuning`

@joshfree, @tg-msft, @kyle-patterson and @rickle-msft for notification

**Comment by rickle-msft** [comment]
@hongli750210 Thank you for noticing this. We'll get it updated.
