### ISSUE TITLE
Spring Cloud Azure reference doc URL design

### ISSUE THREAD

**Issue by chenrujun** [Azure/azure-sdk-for-java#26430]
Current links of reference doc:
1. https://microsoft.github.io/spring-cloud-azure
2. https://microsoft.github.io/spring-cloud-azure/docs/current/reference/html/index.html
3. https://microsoft.github.io/spring-cloud-azure/4.0.0-beta.3/4.0.0-beta.3/reference/html/index.html

Problems:
1. In the second URL, `docs` and `reference` seems not necessary, it can be deleted. Not sure whether `html` can be deleted.
2. In the third URL, `4.0.0-beta.3` is duplicated, we should avoid duplication.

Tasks
 - [ ] Design new multiple version support method of reference doc
 - [ ] Design new URL pattern of reference doc.
 - [ ] Implement the new design.

**Comment by saragluna** [comment]
Closing this issue now, the docs committed to the gh-pages branch from the main branch will now contain the branch name in the path, https://microsoft.github.io/spring-cloud-azure/4.0.0/reference/html/index.html. And we will always deploy from the main branch now.
