### ISSUE TITLE
Use same style for all title in spring-cloud-azure reference doc

### ISSUE THREAD

**Issue by chenrujun** [Azure/azure-sdk-for-java#26458]
In [spring cloud azure reference doc](https://microsoft.github.io/spring-cloud-azure), all titles should use same pattern.
In `.adoc` file, line starts with `=, ==, ===` is title. We can use [this tool](https://capitalizemytitle.com/#) to format all titles.

The following keep the original style:
==== From azure-spring-cloud-starter-servicebus to spring-cloud-azure-starter-integration-servicebus

**Comment by jialigit** [comment]
close for pr merged
