### ISSUE TITLE
Write sample about spring-security + Azure AD, LDAP login

### ISSUE THREAD

**Issue by chenrujun** [Azure/azure-sdk-for-java#26456]
# Background

1. You can refer to parent issue (#25817) to get more information about all Azure AD related sample requirement.
2. As title. This issue is aimed to write sample about spring-security + Azure AD + LDAP login

# Useful Links
1. https://docs.microsoft.com/en-us/azure/active-directory/fundamentals/auth-ldap
https://spring.io/guides/gs/authenticating-ldap/

**Comment by chenrujun** [comment]
@mpenabad1961 . 

Copied from  https://github.com/Azure/azure-sdk-for-java/issues/26418#issuecomment-1011357778:

> I currently use LDAP Spring Security and need to migrate to Azure AD, but UPS does not allow client-secret. 

I think this GitHub issue can cover your requirement. 
But this issue does not have ETA yet.

**Comment by tomg-formpak** [comment]
We currently use `ActiveDirectoryLdapAuthenticationProvider` in Spring Security for the LDAP integration, but not authorization. 

Now we have a requirement for integration with Azure Active Directory Integration for MFA and SSO features. Our application is based on the Java spring framework. How we can implement this? Does this require a whole code change for Azure AD integration? 

@chenrujun

**Comment by chenrujun** [comment]
@tomg-formpak 
Thanks for reaching out, I will look into it and get back to you as soon as possible.

**Comment by tomg-formpak** [comment]
> @tomg-formpak Thanks for reaching out, I will look into it and get back to you as soon as possible.

@chenrujun Thank you so much. 

Note: It's Spring framework (not Spring Boot).

**Comment by zoladkow** [comment]
Hi @chenrujun just out of curiosity, would such example be any different from a plain Spring Security + LDAP protocol?
I'd assume this is the case, but only after I enable specific options to expose LDAP on my directory (encrypted of course). Correct?
