### ISSUE TITLE
[BUG] Support Powershell in azure-spring-boot-samples

### ISSUE THREAD

**Issue by chenrujun** [Azure/azure-sdk-for-java#26497]
Current the scripts in [azure-spring-boot-samples](https://github.com/Azure-Samples/azure-spring-boot-samples/blob/71c87bb467be3f0f3dee421fbcb3607350f6563d/storage/azure-spring-boot-starter-storage/storage-resource/README.adoc#how-to-run) does not work for PowerShell.

We should make it work for PowerShell.
For example:

![image](https://user-images.githubusercontent.com/13167207/149492881-155b2c7b-d425-4aa4-9ed7-abe63cd335e4.png)

**Comment by saragluna** [comment]
Closing in favor of https://github.com/Azure/azure-sdk-for-java/issues/26533.
