### ISSUE TITLE
[QUERY] cosmosdb setting x-ms-max-item-count through java sdk

### ISSUE THREAD

**Issue by fatagun** [Azure/azure-sdk-for-java#26491]
**Query/Question**
How can I set `x-ms-max-item-count` from java sdk? 

is there an option to set page size to retrieve documents? currently it is limited to 100, i would like to increase it to 1000? how can i do it through the java SDK? 

I couldnt find it anywhere. can you please elaborate?

Thanks.

**Comment by fatagun** [comment]
Turned out byPage is doing the batch of 1000 documents. Not batching of 100. Not clearly documented. 

Another feedback is `CosmosPagedFlux<T>` with byPage() returns all the pages unless calling blockFirst() which is not reactive. netty complains about that. There should be a way to get the first page only lazily, without loading everything.

**Comment by kushagraThapar** [comment]
@fatagun - investigating your comment, will respond shortly.
