### ISSUE TITLE
Regenerate, make sure immutable property is added

### ISSUE THREAD

**Issue by heaths** [Azure/azure-sdk-for-java#26506]
Now that https://github.com/Azure/azure-rest-api-specs/pull/17270 has been merged for 7.3-preview, please regenerate and make sure that the `immutable` property has been correctly added.

Testing might include setting a release policy and marking immutable `true`, then trying to change or remove the release policy which should err.

**Comment by vcolin7** [comment]
Fixed by: #26910.
