### ISSUE TITLE
Deadlock when writing block blob

### ISSUE THREAD

**Issue by Tetradeus** [Azure/azure-sdk-for-java#26502]
Version 12.8.0

Here is our code to create a new file: 
```
    try (OutputStream os = blobContainerClient.getBlobClient(blob).getBlockBlobClient().getBlobOutputStream()) {
      os.write(content);
    } catch (IOException e) {
      throw new RuntimeException(e);
    }
```

It does work but in certain cases, we are stuck in a deadlock.

The code get stuck here waiting for a condition that never succeeds :

```
java.lang.Thread.State: WAITING (parking)
	at jdk.internal.misc.Unsafe.park(java.base@11.0.13/Native Method)
	- parking to wait for  <0x00000000ccdb0038> (a java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject)
	at java.util.concurrent.locks.LockSupport.park(java.base@11.0.13/LockSupport.java:194)
	at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(java.base@11.0.13/AbstractQueuedSynchronizer.java:2081)
	at com.azure.storage.blob.specialized.BlobOutputStream$BlockBlobOutputStream.commit(BlobOutputStream.java:253)
	at com.azure.storage.blob.specialized.BlobOutputStream.close(BlobOutputStream.java:124)
	- locked <0x00000000ccdb0050> (a com.azure.storage.blob.specialized.BlobOutputStream$BlockBlobOutputStream)
```

Seems stuck here :
```
        @Override
        void commit() {
...
                while (!complete) {
                    transferComplete.await();
                }
...
        }
```

I will try to reproduce with last version.

**Comment by joshfree** [comment]
@rickle-msft @amishra-dev could you please help route @Tetradeus's issue

**Comment by Tetradeus** [comment]
Just to add some more information:
- I have not been able to test it on newer version (because of dependency tree compatibility)
- I think I may have bypassed the issue with BlobClient.uploadWithResponse
- We used the outputstream version to make it compatible with our Spring Resource abstraction 
- The deadlock seemed to happen when we upload the same file twice

**Comment by rickle-msft** [comment]
Hi, @Tetradeus. Thank you for the context. Are you able to reproduce this outside of a spring environment as well? How regularly does this reproduce when you upload the same file twice? And do the uploads have to be close in time?

**Comment by Tetradeus** [comment]
Unfortunately no, I have just seen that issue on production and I have no clean reproduction steps. I will come back to you if I am able to bring more information.

**Comment by rickle-msft** [comment]
Understood. In that case, let's keep the issue open for now to track, but I'll hold off investigating until we have some more information to go off of

**Comment by alzimmermsft** [comment]
@Tetradeus were you able to reproduce this issue again?
