### ISSUE TITLE
Error receiving events from partition New receiver 'nil' with higher epoch of '0' is created hence current receiver 'nil' with epoch '0' is getting disconnected.

### ISSUE THREAD

**Issue by rhyashu** [Azure/azure-sdk-for-java#26518]
**Query/Question**
We are consuming events from event hub using azure cloud stream binder application and sometimes getting the error "Error receiving events from partition New receiver 'nil' with higher epoch of '0' is created hence current receiver 'nil' with epoch '0' is getting disconnected"

When we are checking the output data we are seeing some missing events. Please confirm if this error can cause some event to be missed out from processing in the consumer instances.

However if we sent the events again then the output count matches and this error is also not there..

**Setup :**
 - OS: Linux (AKS pods)
 - Event hub Partition: 25
 - Consumers: 25
 - IDE: Running as a POD in AKS
 - Library/Libraries: [e.g. com.azure.spring:azure-spring-cloud-stream-binder-eventhubs:2.8.0]
 
 **Information Checklist**
**Error details:**
com.azure.core.amqp.implementation.ExceptionUtil.toException(ExceptionUtil.java:85)
datautil-5b9bc95dbf-snwfc/Console.log:com.azure.core.amqp.exception.AmqpException: New receiver 'nil' with higher epoch of '0' is created hence current receiver 'nil' with epoch '0' is getting disconnected. If you are recreating the receiver, make sure a higher epoch is used. TrackingId:8efac11d00006a00003e72bb61e07a3c_G21_B26, SystemTracker:****-eastus2-eventhub-01:eventhub:xxxxxxx_eh~22286|$default, Timestamp:2022-01-13T19:15:26, errorContext[NAMESPACE: ****-eastus2-eventhub-01.servicebus.windows.net. ERROR CONTEXT: N/A, PATH: xxxxxx_valids_eh/ConsumerGroups/$default/Partitions/16, REFERENCE_ID: 16_cf65be_1642101307869, LINK_CREDIT: 500]
- [* ] Query Added
- [* ] Setup information Added

**Comment by saragluna** [comment]
Similar issue https://github.com/Azure/azure-sdk-for-js/issues/15893, @conniey could you please link the `SinkEmissionException` issue we logged?

**Comment by conniey** [comment]
In the JS issue linked https://github.com/Azure/azure-sdk-for-js/issues/15893#issuecomment-866361212, describes why you see this error. It is a normal part of load balancing between different instances of EventProcessorClient.

> When we are checking the output data we are seeing some missing events. Please confirm if this error can cause some event to be missed out from processing in the consumer instances.

This error shouldn't cause any events to be missed. When we start reading from your Event Hub, we query the Storage Blob for the last checkpoint and start from there. The only time checkpoints are persisted is when you call updateCheckpoint() in the processEvent\Events callback.

**Comment by rhyashu** [comment]
Hi Team, if we are saying that with this epoch error we will not loose any data then we are fine for now to close this issue.

**Comment by wstest123** [comment]
@conniey We got the same error when using checkpointstore SDK to consume message from EventHub. And we found that the entity which occur the same issue is an **empty** entity.  We didn't send any messages to this entity during the past one month, could you please help clarify if the empty entity would cause this issue? Thanks so much!
