### ISSUE TITLE
Could Result of get{Gcm}OutcomeCounts be contains all happens?

### ISSUE THREAD

**Issue by changbaebang** [Azure/azure-sdk-for-java#26534]
**Query/Question**
Result of getGcmOutcomeCounts would be contains like WrongToken or ExpiredChannel that is listed on https://docs.microsoft.com/en-us/rest/api/notificationhubs/get-notification-message-telemetry#outcomes

But when `NotFound` for GCM, there was no data from getGcmOutcomeCounts.

Is it feature?

***Why is this not a Bug or a feature Request?***
`NotFound` is not on the list of https://docs.microsoft.com/en-us/rest/api/notificationhubs/get-notification-message-telemetry#outcomes

**Setup (please complete the following information if applicable):**
 - OS: windows 10
 - IDE: visual code
 - Library/Libraries: latest
 
 **Information Checklist**
 Kindly make sure that you have added all the following information above and checkoff the required fields otherwise we will treat the issuer as an incomplete report
- [V ] Query Added
- [V] Setup information Added

**Comment by joshfree** [comment]
Hi @changbaebang could you provide more information on which client library (SDK) and version you're using?

**Comment by changbaebang** [comment]
@joshfree 
1.0.0-beta.2  is the version of com.azure.resourcemanager.azure-resourcemanager-notificationhubs

**Comment by joshfree** [comment]
Thank you for the extra information @changbaebang!  @weidongxu-microsoft could you help route this issue?

**Comment by weidongxu-microsoft** [comment]
@changbaebang

I would like some clarification please.

Endpoint in the link `https://{namespace}.servicebus.windows.net/{NotificationHub}/messages/{notification message ID}?api-version=2016-07`.

`com.azure.resourcemanager.azure-resourcemanager-notificationhubs` does not support this endpoint (or any endpoint not starting with `management.azure.com`.

**Comment by weidongxu-microsoft** [comment]
Issue addressed in email thread.
