### ISSUE TITLE
[FEATURE REQ] The sample  of Spring Cloud Azure for redis should also support the terraform

### ISSUE THREAD

**Issue by moarychan** [Azure/azure-sdk-for-java#26550]
The Redis sample https://github.com/Azure-Samples/azure-spring-boot-samples/tree/spring-cloud-azure_4.0.0-beta.3/cache/spring-cloud-azure-starter/spring-cloud-azure-sample-cache should also support the terraform, please refer to the parent issue https://github.com/Azure/azure-sdk-for-java/issues/23391.

**Comment by jialigit** [comment]
merged
