### ISSUE TITLE
Add support for idempotent buffered producer

### ISSUE THREAD

**Issue by conniey** [Azure/azure-sdk-for-java#26574]
* Support idempotent buffered producer.
* Dependent on #24156
* Documentation:
   * Design Proposal: https://gist.github.com/jsquire/1cc4db6b3ca4ef13d26dc5315483555b
* The original PR is here:
  * https://github.com/Azure/azure-sdk-for-java/pull/14389
  * We did a release of azure-core-amqp 1.7.0-beta.2 with this support (https://github.com/Azure/azure-sdk-for-java/tree/azure-core-amqp_1.7.0-beta.2)
  * azure-messaging-eventhubs 5.4.0-beta.1 https://github.com/Azure/azure-sdk-for-java/tree/azure-messaging-eventhubs_5.4.0-beta.1

**Comment by jorge-barroso** [comment]
Hello, I'm working on a commercial project and we would like to make use of this feature. We have seen that other SDKs already support this, is there a timeline for it to get added to the Java SDK, or is there a way to do this with an EventHubBufferedProducerClient/EventHubBufferedProducerAsyncClient that we may have missed?

Thank you
