### ISSUE TITLE
[QUESTION] Terraform init is extremely slow

### ISSUE THREAD

**Issue by backwind1233** [Azure/azure-sdk-for-java#26579]
**Context**
We provide [azure-spring-boot-samples](https://github.com/Azure-Samples/azure-spring-boot-samples) to demonstrate how to use Spring Cloud Azure libraries.
 By default, users running samples in [azure-spring-boot-samples](https://github.com/Azure-Samples/azure-spring-boot-samples) by following the instructions in [README.md](https://github.com/Azure-Samples/azure-spring-boot-samples/blob/main/keyvault/spring-cloud-azure-starter-keyvault-secrets/secret-client/README.md).
The Azure Resources provided to run the samples are provisioned by terraform scripts.

**Problem**
From @moarychan and @chenrujun's feedback,
running command `terraform init` may take much time to run.

**Goal**
Figure out why someone running the command slow and try to workout a solution.

**Comment by stliu** [comment]
closing it, doesn't need to fix
