### ISSUE TITLE
[FEATURE REQ] Support AzureMessagingListener work with Event Hubs and Service Bus Spring starter together

### ISSUE THREAD

**Issue by jialigit** [Azure/azure-sdk-for-java#26580]
## Context
In Azure, messaging includes servciebus and eventhubs azure messaging listener. We may extend the annotation driven message consuming programing using our new APIs.

In the new 4.0 version of the project, we have refactored the API and module structrues. Regarding the Azure
Messaging Listener feature, the original APIs are deprecated, and the Message Listener Container function does not work any more.

Related issue: #24995

## Goal
As the APIs are redesigned in the new 4.0 version, we need to implement the Message Listening function on top of the new APIs in 4.0. As that Azure Messaging service include Service Bus and Event Hubs, we will have to consider all usage senarios of how users may use this feature, i.e. to use Service Bus or Event Hubs or both.

Scenarios To Be Used:

  1. Only EventHub lib in the classpath. Then containerFactory should be configured for Event Hub if missing.
  2. Only ServiceBus lib in the classpath. Then containerFactory should be configured for Service Bus if missing.
  3. Both of the above libs provided. ---> explicit containerfactory name should be set on the arguments.

**Comment by stliu** [comment]
it is a bug to me, using #24995 to track and closing this one
