### ISSUE TITLE
AutoRest: Explore JDK 8 baseline

### ISSUE THREAD

**Issue by JonathanGiles** [Azure/azure-sdk-for-java#2660]
Lets assume that at some point in the future AutoRest will be generating JDK 8 baselined code. We should identify points in the generated output where we can offer a better developer experience. This issue should track the identification of possible areas of improvements, and then link to new issues created to improve both of these.

Areas identified so far:

- Move to the new date / time APIs
- Use the new java.util.function functional interfaces
- Consider use of Optional
- Consider use of Stream
- Consider use of default / static methods on interfaces

**Comment by lmazuel** [comment]
@JonathanGiles please split this into smaller task in https://github.com/Azure/autorest.java, and link them here
