### ISSUE TITLE
Check existing credits on the line before adding new credits

### ISSUE THREAD

**Issue by ramya-rao-a** [Azure/azure-sdk-for-java#26637]
Say there is a call to `ServiceBusReceiverClient.receiveMessages()` asking for 100 messages
- client adds 100 credits on the line, but happens to get only 10 messages within the timeout and therefore returns the 10 to the user.
- before the next call to receiveMessages(), 30 messages are received by the client and they live in the buffer.

Today, the next call to receiveMessages() for another 100 messages will result in 70 credits being added to the line ignoring the fact that the line already has 60 credits from the first call. Now there are 130 credits on the line resulting in the extra messages being sent to the buffer where they can potentially get expired before the next receive call

This issue is logged after a discussion with @shankarsama to investigate if we can check the number of remaining credits on the line and adjust the new credits to add appropriately

Ideal behavior:
- #26632 will ensure that the 30 messages in the buffer are released immediately as there is no active receive call.
- The next call to receiveMessages() asking for 100 messages should result in adding only 40 credits as there are 60 already on the line. To check the remaining credits on the line, we can try to use [getRemoteCredit()](https://qpid.apache.org/releases/qpid-proton-j-0.33.10/api/org/apache/qpid/proton/engine/Link.html#getRemoteCredit())

cc @conniey, @anuchandy, @JoshLove-msft, @shankarsama, @yvgopal

**Comment by ZejiaJiang** [comment]
After investigation, service bus synchronous client will check the credits on the link by using `checkAndAddCredits`.

Here is some code snippet:
https://github.com/Azure/azure-sdk-for-java/blob/f24f525443b620ed6050b2fc0bf2fdca95b9ac98/sdk/servicebus/azure-messaging-servicebus/src/main/java/com/azure/messaging/servicebus/implementation/ServiceBusReceiveLinkProcessor.java#L554-L622

**Comment by sohanlal311** [comment]
@ZejiaJiang Could you please let me know which version of the library it has been fixed in?

**Comment by ZejiaJiang** [comment]
> @ZejiaJiang Could you please let me know which version of the library it has been fixed in?

Hi Sohan,  the codes shows that the latest fix is in v7.5.1. And we recommand you use the latest version which is v7.7.0.

**Comment by sohanlal311** [comment]
Thanks @ZejiaJiang. We will upgrade to the latest version.
