### ISSUE TITLE
Investigate JDK9+ compatibility of Test Proxy Support in Performance Framework.

### ISSUE THREAD

**Issue by g2vinay** [Azure/azure-sdk-for-java#26685]
The reflective access being used in configClientBuilder API inside perf framework may not be compatible with JDK9+ when module-info is used in the app, as azure-core clients don't export their API for reflective access.

Investigate and make changes as needed.

**Comment by kasobol-msft** [comment]
This could be solved by https://github.com/Azure/azure-sdk-for-java/issues/26489
