### ISSUE TITLE
[BUG] The BlobServiceClient.getAccountInfo() method always returns a 404 response when using TokenCredentials

### ISSUE THREAD

**Issue by AndresManuel1** [Azure/azure-sdk-for-java#26733]
**Describe the bug**
Very similar/same error: https://github.com/Azure/azure-sdk-for-java/issues/10663
When using TokenCredentials (DefaultAzureCredential to be specific) instead of the spring provided default StorageSharedKeyCredential, the request BlobServiceAsyncClient#getAccountInfo always fails with a 404 response.

This request is executed automatically from the `com.azure.spring.autoconfigure.storage.actuator.BlobStorageHealthIndicator` when actuator is enabled for azure-storage.

Per default spring configuration, the provided `com.azure.storage.blob.BlobServiceClientBuilder` uses the account name & key to create a StorageSharedKeyCredential.

In my case, I do not want the storage key anywhere in my application, so I am providing my own `com.azure.storage.blob.BlobServiceClientBuilder` bean (see reproduction steps below)

The only change is the credentials. The problem occurs in the following scenarios:

- Hosting my application on AKS and providing AZURE_CLIENT_ID, AZURE_CLIENT_SECRET and AZURE_TENANT_ID as environment variables (EnvironmentCredentials)
- Hosting my application Azure App Services using a UserAssigned Managed Identity (ManagedIdentityCredentials)
- Running my application on my local machine and also providing the above environment variables.

In all of those scenarios, I can access most APIs of the storage account, methods such as `BlobServiceClient#getUserDelegationKey` work without any problem. 
Only the `getAccountInfo()` keeps on returning below error.

Additionally, I executed the same request using Postman (and using the returned token to authenticate) and got the same result, so I believe this is not an error in the SDK or in the Spring Boot Azure Starter but rather in the API of the getAccountInfo() method. 

I also gave my service principal/managed identity all possible rights, such as Owner on the whole subscription and all Owner/Admin roles on the storage account.

***Exception or Stack Trace***
This is the response from the actuator endpoint:

```

  "status": "DOWN",
  "components": {
    "blobStorage": {
      "status": "DOWN",
      "details": {
        "URL": "https://xxx.blob.core.windows.net",
        "error": "com.azure.storage.blob.models.BlobStorageException: Status code 404, \"﻿<?xml version=\"1.0\" encoding=\"utf-8\"?><Error><Code>ResourceNotFound</Code><Message>The specified resource does not exist.\nRequestId:384f7602-101e-0001-5287-127f38000000\nTime:2022-01-26T07:34:39.3461319Z</Message></Error>\""
      }
    },
    ....
}
```

**To Reproduce**
- Create a Storage account on Azure
- Provide storage blob endpoint & account name in your properties
- Replace the automatically provided BlobServiceClientBuilder from `com.azure.spring.autoconfigure.storage.StorageAutoConfiguration` with the following:
```
    @Bean
    @ConditionalOnProperty("azure.storage.blob-endpoint")
    fun blobServiceClientBuilder(storageProperties: StorageProperties): BlobServiceClientBuilder {
        return BlobServiceClientBuilder()
            .endpoint(storageProperties.blobEndpoint)
            .credential(DefaultAzureCredentialBuilder().build())
            .httpLogOptions(HttpLogOptions().setApplicationId(ApplicationId.AZURE_SPRING_STORAGE_BLOB))
    }
```
- Provide valid credentials that end up being used by DefaultAzureCredential
- Turn on the health indicator by setting `management.health.azure-storage.enabled=true`
- Check your actuator endpoint

***Code Snippet***
Springs `com.azure.spring.autoconfigure.storage.actuator.BlobStorageHealthIndicator` and call to `getAccountInfo()`

```
public class BlobStorageHealthIndicator implements HealthIndicator {

    private final BlobServiceAsyncClient internalClient;

    public BlobStorageHealthIndicator(BlobServiceClientBuilder blobServiceClientBuilder) {
        internalClient = blobServiceClientBuilder == null ? null : blobServiceClientBuilder.buildAsyncClient();
    }

    @Override
    public Health health() {
        Health.Builder healthBuilder = new Health.Builder();

        try {
            if (internalClient == null) { // Not configured
                healthBuilder.status(NOT_CONFIGURED_STATUS);
            } else {
                healthBuilder.withDetail(URL_FIELD, internalClient.getAccountUrl());
                StorageAccountInfo info;
                try {
                    info = internalClient.getAccountInfo().block(POLL_TIMEOUT);
                    if (info != null) {
                        healthBuilder.up();
                    }
                } catch (Exception e) {
                    healthBuilder.down(e);
                }

            }

        } catch (Exception e) {
            healthBuilder.status("Could not complete health check.").down(e);
        }
        return healthBuilder.build();
    }
}
```

**Expected behavior**
- The getAccountInfo() request should work

**Setup (please complete the following information):**
 - OS: Windows 10
 - IDE: IntelliJ 
 - Library/Libraries: 
   - com.azure.spring:azure-spring-boot-starter-storage:3.10.0
   - com.azure:azure-identity:1.4.3
 - Java version: 11
 - App Server/Environment: Spring Boot
 - Frameworks: Spring Boot

**Additional context**

**Information Checklist**
Kindly make sure that you have added all the following information above and checkoff the required fields otherwise we will treat the issuer as an incomplete report
- [ X ] Bug Description Added
- [ X ] Repro Steps Added
- [ X ] Setup information Added

**Comment by saragluna** [comment]
@moarychan please help take a look at this.

**Comment by moarychan** [comment]
Hi @AndresManuel1 , Thank you for your feedback, I can reproduce this exception upon to `com.azure.storage.blob.BlobServiceAsyncClient#getAccountInfo`, I use the `azure-identify:1.4.2`. If using the storage key, then it works fine, maybe is a temporary solution before the Azure Storage SDK upgrade. We will follow up in time and reply to you as soon as possible, once the issue is solved.

Another solution is to use the [Spring Cloud Azure Starter Storage Blob 4.0 Beta3](https://mvnrepository.com/artifact/com.azure.spring/spring-cloud-azure-starter-storage-blob/4.0.0-beta.3), we use another method `com.azure.storage.blob.BlobServiceAsyncClient#getPropertiesWithResponse()` to check the storage status, it works fine, please try again.

**Comment by rickle-msft** [comment]
@moarychan Thanks for participating here. It was recently made known to me that this API is actually only supported using shared key authentication; the service will reject it if the request is using token creds. So this is not an api bug but is simply not a feature on the service. See [here](https://docs.microsoft.com/en-us/rest/api/storageservices/get-account-information#request)

**Comment by lgraf** [comment]
@moarychan I am not sure how `azure-spring-boot` and `azure-spring-cloud` relate, so my question is will the new version of `azure-spring-cloud-actuator` solve this issue also for `azure-spring-boot` in the future?

Currently `azure-spring-boot` supports only storage key authentication out-of-the-box, but like @AndresManuel1 stated it is pretty easy to use different authentication methods (like service principal) by  providing your own `com.azure.storage.blob.BlobServiceClientBuilder`.

I think it would be great if the `azure-spring-boot` support some kind of health check, also if other authentication methods are used.

**Comment by saragluna** [comment]
@lgraf yes, in 4.0.0 we will support all available authentication methods of an Azure service client and we are planning to GA the 4.0 by the end of this month https://github.com/Azure/azure-sdk-for-java/milestone/96.
