### ISSUE TITLE
[BUG] Spring Azure Active Directory: AADAzureDelegatedOAuth2AuthorizedClientProvider does not work within ServletOAuth2AuthorizedClientExchangeFilterFunction

### ISSUE THREAD

**Issue by huberchrigu** [Azure/azure-sdk-for-java#26736]
**Describe the bug**
I use the azure-spring-boot-starter-active-directory for a webapp that accesses the Graph API via `WebClient`. The following `WebClient` setup used to work for earlier versions:

```
val oauth2Client = ServletOAuth2AuthorizedClientExchangeFilterFunction(authorizedClientManager).also {
            it.setDefaultClientRegistrationId("graph")
        }
        return WebClient.builder().baseUrl("https://graph.microsoft.com/v1.0")
            .apply(oauth2Client.oauth2Configuration())
            .build()
```
I use the web client then without any other configuration, because the default client ID "graph" is already set in the setup. Since I upgraded to the newest Azure BOM, this does not work anymore (see stacktrace below). The reason is that `AADAzureDelegatedOAuth2AuthorizedClientProvider` tries to get the current Servlet request from `RequestContextHolder`, which is not possible in the reactive `WebClient`.

***Exception or Stack Trace***

> java.lang.IllegalArgumentException: request cannot be null
> 	at org.springframework.util.Assert.notNull(Assert.java:201)
> 	Suppressed: reactor.core.publisher.FluxOnAssembly$OnAssemblyException: 
> Error has been observed at the following site(s):
> 	*__checkpoint ⇢ Request to GET https://graph.microsoft.com/v1.0/users [DefaultWebClient]
> Original Stack Trace:
> 		at org.springframework.util.Assert.notNull(Assert.java:201)
> 		at com.azure.spring.aad.JacksonHttpSessionOAuth2AuthorizedClientRepository.loadAuthorizedClient(JacksonHttpSessionOAuth2AuthorizedClientRepository.java:39)
> 		at com.azure.spring.aad.webapp.AADAzureDelegatedOAuth2AuthorizedClientProvider.authorize(AADAzureDelegatedOAuth2AuthorizedClientProvider.java:76)
> 

**To Reproduce**
Adapt the sample aad/azure-spring-boot-starter-active-directory/aad-web-application/src/main/java/com/azure/spring/sample/aad/controller/ClientController.java by removing the `@RegisteredOAuth2AuthorizedClient("graph") OAuth2AuthorizedClient graphClient` parameter and calling the webClient as shown below.

***Code Snippet***
```
private String callMicrosoftGraphMeEndpoint() {
            String body = webClient
                    .get()
                    .uri(GRAPH_ME_ENDPOINT)
                    .attributes(authentication("graph"))
                    .retrieve()
                    .bodyToMono(String.class)
                    .block();
            LOGGER.info("Response from Graph: {}", body);
            return "Graph response " + (null != body ? "success." : "failed.");
    }
```

**Expected behavior**
The `WebClient` filter works without the need of enforcing authorization before (like in the parameter resolver for `@RegisteredOAuth2AuthorizedClient`).

**Information Checklist**
Kindly make sure that you have added all the following information above and checkoff the required fields otherwise we will treat the issuer as an incomplete report
- [x] Bug Description Added
- [x] Repro Steps Added
- [ ] Setup information Added

**Comment by joshfree** [comment]
@chenrujun could you please follow up with @huberchrigu on this github issue?  Thank you! :)

**Comment by saragluna** [comment]
@moarychan please help take a look at this issue since @chenrujun is on vacation.

**Comment by moarychan** [comment]
Hi @huberchrigu , thanks for your feedback, could you please provide more details? I need to confirm the `azure-spring-boot-starter-active-directory` version, you mean the 3.7 version works normally, 3.8 and later does not work anymore.  I will reproduce the problem asap, please provide the minimal demo if possible.

**Comment by huberchrigu** [comment]
Hi @moarychan 
Check out this example: https://github.com/huberchrigu/azure-issue. If you run it and call `/call-graph2` it does not work. This example runs with version 3.13.0. If you switch the Spring Boot version to 2.5.2 and Azure 3.6.0, it works. 
The request `/call-graph` always works, because the authorization is done outside the reactive context.

**Comment by moarychan** [comment]
Hi @huberchrigu , thanks for your further feedback! 
I found the request for `/call-graph2` will acquire a token for each invocation, because the AADOAuth2AuthorizedClientRepository will fail to save the authorized client.
```text
java.lang.IllegalStateException: No thread-bound request found: Are you referring to request attributes outside of an actual web request, or processing a request outside of the originally receiving thread? If you are actually operating within a web request and still receive this message, your code is probably running outside of DispatcherServlet: In this case, use RequestContextListener or RequestContextFilter to expose the current request.
	at org.springframework.web.context.request.RequestContextHolder.currentRequestAttributes(RequestContextHolder.java:131) ~[spring-web-5.3.8.jar:5.3.8]
	at com.azure.spring.aad.webapp.AADOAuth2AuthorizedClientRepository.loadAuthorizedClient(AADOAuth2AuthorizedClientRepository.java:89) ~[azure-spring-boot-3.6.0.jar:na]
	at org.springframework.security.oauth2.client.web.DefaultOAuth2AuthorizedClientManager.authorize(DefaultOAuth2AuthorizedClientManager.java:152) [spring-security-oauth2-client-5.5.1.jar:5.5.1]
	at org.springframework.security.oauth2.client.web.reactive.function.client.ServletOAuth2AuthorizedClientExchangeFilterFunction.lambda$authorizeClient$24(ServletOAuth2AuthorizedClientExchangeFilterFunction.java:552) [spring-security-oauth2-client-5.5.1.jar:5.5.1]
	at reactor.core.publisher.MonoSupplier.call(MonoSupplier.java:85) ~[reactor-core-3.4.7.jar:3.4.7]
	at reactor.core.publisher.FluxSubscribeOnCallable$CallableSubscribeOnSubscription.run(FluxSubscribeOnCallable.java:227) ~[reactor-core-3.4.7.jar:3.4.7]
	at reactor.core.scheduler.SchedulerTask.call(SchedulerTask.java:68) ~[reactor-core-3.4.7.jar:3.4.7]
	at reactor.core.scheduler.SchedulerTask.call(SchedulerTask.java:28) ~[reactor-core-3.4.7.jar:3.4.7]
	at java.util.concurrent.FutureTask.run$$$capture(FutureTask.java:266) ~[na:1.8.0_202]
	at java.util.concurrent.FutureTask.run(FutureTask.java) ~[na:1.8.0_202]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180) ~[na:1.8.0_202]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293) ~[na:1.8.0_202]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) ~[na:1.8.0_202]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) ~[na:1.8.0_202]
	at java.lang.Thread.run(Thread.java:748) ~[na:1.8.0_202]
```
This exception `IllegalStateException` also exists in the new version, the `OAuth2AuthorizedClientRepository` can not load authorized clients without an HTTP servlet request.

You may need to use the `@RegisteredOAuth2AuthorizedClient("graph")` method to ensure business use first. Currently, the AAD starter cannot fully support some reactive usages of spring-security. We are adding various examples in place of AAD-starter-based scenarios, hope you can follow them further here https://github.com/Azure/azure-sdk-for-java/issues/25817.

**Comment by huberchrigu** [comment]
Hi @moarychan 
Thanks for your answer. My point was that it used to work with the old Azure version (even though it always has to fetch the token due to the IllegalStateException).
I will follow #25817 and hope that they will cover my use case then.
