### ISSUE TITLE
[BUG] The Content-MD5 property is null for big files

### ISSUE THREAD

**Issue by adrianog3** [Azure/azure-sdk-for-java#26754]
**Describe the bug**

When trying to upload large files (400MB or so) the content-md5 property is saved as null in the bucket. However, for smaller files, this property stores the value correctly.

**Exception or Stack Trace**

There is no stack trace.

**To Reproduce**

- To reproduce the problem, just upload a large file (400mb or so).
- Or preferably follow the step by step as described in the example repository created by me: https://github.com/adrianog3/md5-is-null

**Code Snippet**

```java
public static void upload(BlobRef blobRef) {
    BlobClient blob = AzureUtils.getBlobClient(blobRef);

    if (Boolean.TRUE.equals(blob.exists())) {
        log.info("Blob file deleted before upload");
        blob.delete();
    }

    log.info("Uploading file: {}", blobRef.getSourcePath());
    blob.uploadFromFile(blobRef.getSourcePath(), null, new BlobHttpHeaders(), new HashMap<>(),
        AccessTier.HOT, null, null);

    byte[] md5ByteArray = blob.getProperties().getContentMd5();

    if (md5ByteArray == null) {
        // FOR BIG FILES, THE CONTENT-MD5 IS NULL
        log.error("Unexpected behavior happened. The MD5 property is NULL.");
        return;
    }

    String md5 = Base64.getEncoder().encodeToString(md5ByteArray);

    log.info("Expected behavior happened. The MD5 hash is: {}", md5);
}
```

**Expected behavior**

For large files, the content-md5 property should be filled with a valid value.

**Screenshots**

![image](https://user-images.githubusercontent.com/21218657/151278251-e8ed297e-0452-4d86-a2a6-a6049ca68158.png)

**Setup (please complete the following information):**

 - OS: [Linux Mint 20.3]
 - IDE: [IntelliJ]
 - Library/Libraries: [com.azure:azure-storage-blob:12.14.3]
 - Java version: [11] 
 - App Server/Environment: [None/Main-Class-Only]
 - Frameworks: [None]

**Information Checklist**

Kindly make sure that you have added all the following information above and checkoff the required fields otherwise we will treat the issuer as an incomplete report
- [x] Bug Description Added
- [x] Repro Steps Added
- [x] Setup information Added

**Comment by joshfree** [comment]
Thanks for filing this issue, @adrianog3.  Someone from the `Storage` team will follow up shortly.

/cc @rickle-msft

**Comment by adrianog3** [comment]
Hi guys,

Doing a deep search on forums I found that azure blob storage doesn't calculate MD5 for large files (approximately 256mb or more) when the api receives the file in multiple blocks.

So my workaround solution was to find in the sdk some way to send files that are in this scenario in a single block. The final solution was this:

```java
if (fileSizeInBytes >= DataSize.ofMegabytes(256).toBytes()) {
    var blockBlobAsyncClient = getBlobAsyncClient(reference).getBlockBlobAsyncClient();

    var blockBlobSimpleUploadOptions = new BlockBlobSimpleUploadOptions(dis, inputStreamSize)
        .setMetadata(reference.metadata)
        .setTier(AzureUtils.getAccessTier(reference));

    log.info("The file [{}] size [{}] is greater than {}. Using BlockBlobAsyncClient.",
        reference.path, DataSize.ofBytes(fileSizeInBytes).toMegabytes(), maxFileSizeInMegabytes);

    return blockBlobAsyncClient.uploadWithResponse(blockBlobSimpleUploadOptions);
}
```

Although I have a workaround, I would like to know if there is any cleaner and more reliable way than this.

**Comment by amishra-dev** [comment]
This looks correct atm, @rickle-msft could you kindly confirm?

**Comment by rickle-msft** [comment]
This will correctly upload the file, but this api won't calculate the md5 for you. Can you please describe in more detail what behavior you're looking for?
