### ISSUE TITLE
[BUG] Flaky test: testProcessSpansWithoutDiagnosticId

### ISSUE THREAD

**Issue by lmolkova** [Azure/azure-sdk-for-java#26759]
https://dev.azure.com/azure-sdk/public/_build/results?buildId=1328428&view=ms.vss-test-web.build-test-results-tab&runId=28048024&resultId=105959&paneView=debug

```
tracer.end("success", isNull(), <any>);
Wanted 3 times:
-> at com.azure.messaging.eventhubs@5.11.0-beta.1/com.azure.messaging.eventhubs.EventProcessorClientTest.testProcessSpansWithoutDiagnosticId(EventProcessorClientTest.java:324)
But was 2 times:
-> at com.azure.core.amqp@2.4.0-beta.1/com.azure.core.amqp.implementation.TracerProvider.end(TracerProvider.java:134)
-> at com.azure.core.amqp@2.4.0-beta.1/com.azure.core.amqp.implementation.TracerProvider.end(TracerProvider.java:134)
```

**Comment by lmolkova** [comment]
@ZejiaJiang can you please take a look? I think it's one of the tests recently added in #26180

**Comment by ZejiaJiang** [comment]
> @ZejiaJiang can you please take a look? I think it's one of the tests recently added in #26180

OK, I'll take a look

**Comment by ZejiaJiang** [comment]
@lmolkova I triggered `java-eventhub-ci` and `java-core-ci` of the main branch manually. And `java-eventhub-ci` of main branch is successful, `java-core-ci` is failed as well. I need sometime to review your code.

**Comment by lmolkova** [comment]
@ZejiaJiang sorry for not being clear - I didn't touch anything related to the test - it's something that reproduces on main - i.e. no need to review my code.

**Comment by ZejiaJiang** [comment]
@lmolkova 

Here is some updates. I'm not sure whether this case is a flaky test or not.

The test of eventhub-ci didn't fail.

The test of eventhub that triggered by core-ci fails all the time.

I'm trying to figure out what the difference betweent the test of eventhub-ci and the eventhub test that triggered by core-ci.

**Comment by ZejiaJiang** [comment]
BTW, in the test log, it shows that the context start with `EventHubs.process` for 3 times and end with the status message `success` for 2 times. I'd like to ask what will cause the context don't end with the status message `success`. I'm not famliar with telemetry and have no idea what will cause the context end failed.
