### ISSUE TITLE
[QUERY] Support PEEK-LOCK mode of Service Bus from Azure Spring Boot JMS libraries

### ISSUE THREAD

**Issue by yiliuTo** [Azure/azure-sdk-for-java#26762]
**Query/Question**
How to enable the [PEEK-LOCK](https://docs.microsoft.com/azure/service-bus-messaging/message-transfers-locks-settlement#peeklock) mode of Azure Service Bus from Azure Spring JMS support, which allow users to explicitly settle a message?

The default ack mode of Spring JMS is [AUTO_ACKNOWLEDGE](https://docs.spring.io/spring-framework/docs/current/javadoc-api/org/springframework/jms/listener/AbstractMessageListenerContainer.html) which automatically acknowledges messages before / after the message has been successfully processed by listener execution according to the default / simple `MessageListenerContainer` implementation. And due to the JMS listener and JMS template uses the default and simple message listener container respectively, so their default ack behavior are different as well.

According to the introduction of `CLIENT_ACKNOWLEDGE`, this mode allows client to explicitly acknowledge a message which is consistent with `PEEK-LOCK` mode. So how should it be used with `JmsTemplate` and `JmsListener`?

**Comment by yiliuTo** [comment]
The possible solution:

1. For `JmsTemplate`, there is an open API to set the session ack mode:
   ```
   JmsTemplate#setSessionAcknowledgeMode(Session.CLIENT_ACKNOWLEDGE);
   ```
   And use the `execute` method with a `SessionCallback` to consume a message and acknowledge.
2. For `JmsListener`, there are two scenarios:
   1. Use the native Spring Jms message listener to consume and acknowledge messages. In this case, the `DefaultMessageListenerContainer` will be used which will also acknowledge messages after the successful listener execution for the `CLIENT_ACKNOWLEDGE` mode. So I doubt that users still cannot manually acknowledge a message, we should verify if customized acknowledgment could be supported in this way.
   2.  Customize the message listener and then consume and acknowledge messages in the `onMessage` method. In this case, another customzied bean of `DefaultMessageListenerContainer` should be provided to accept this message listener and also set the ack mode to client. We should check if this solution could work as expected.

**Comment by jialigit** [comment]
**Uses can not explicitly settle a message**, cause the spring jms framework wrap it automatically. But Users can explicitly redeliver the message by throw a new Exception while configure the `spring.jms.listener.acknowledge-mode=CLIENT`.

https://docs.spring.io/spring-framework/docs/4.3.9.RELEASE/javadoc-api/org/springframework/jms/listener/AbstractMessageListenerContainer.html
> "sessionAcknowledgeMode" set to "CLIENT_ACKNOWLEDGE": Automatic message acknowledgment after successful listener execution; best-effort redelivery in case of a user exception thrown as well as in case of other listener execution interruptions (such as the JVM dying).
All we need here to configure the spring.jms.listener.acknowledge-mode=CLIENT

And in the MessageConsumer onMessage method, you can redeliver the message by make a user Exception. Because the Spring JMS framework wrap the ack automatically for users.

**Comment by yiliuTo** [comment]
What is the behavior of using JmsTemplate#execute and override the MessageListener#onMessage to manually ack a message?

**Comment by jialigit** [comment]
> What is the behavior of using JmsTemplate#execute and overriding the MessageListener#onMessage to manually ack a message?

This way is to ack automatically without mannually ack.

```java
jmsTemplate.execute(new SessionCallback<Object>() {
           @Override
           public Object doInJms(Session session) throws JMSException {

               MessageConsumer consumer = session.createConsumer(jmsTemplate.getDestinationResolver().resolveDestinationName(session, queueName, false));
               try {
                   Message message = consumer.receive(1);
                   if (message != null) {
                       User user = (User) ((ObjectMessage) message).getObject();
                       LOGGER.info("Received message from queue: {}", user.getName());
                   }

               }
               catch (Exception e) {
                   return null;
               }
               finally {
                   consumer.close();
               }
               return null;
           }
       }, true);
```

**Comment by jialigit** [comment]
> The possible solution:
> 
> 1. For `JmsTemplate`, there is an open API to set the session ack mode:
>    ```
>    JmsTemplate#setSessionAcknowledgeMode(Session.CLIENT_ACKNOWLEDGE);
>    ```
>    
>    
>        
>          
>        
>    
>          
>        
>    
>        
>      
>    And use the `execute` method with a `SessionCallback` to consume a message and acknowledge.
> 2. For `JmsListener`, there are two scenarios:
>    
>    1. Use the native Spring Jms message listener to consume and acknowledge messages. In this case, the `DefaultMessageListenerContainer` will be used which will also acknowledge messages after the successful listener execution for the `CLIENT_ACKNOWLEDGE` mode. So I doubt that users still cannot manually acknowledge a message, we should verify if customized acknowledgment could be supported in this way. Besides, to set the ack mode, the property of `spring.jms.listener.acknowledge-mode` could be configured.
>    2. Customize the message listener and then consume and acknowledge messages in the `onMessage` method. In this case, another customzied bean of `DefaultMessageListenerContainer` should be provided to accept this message listener and also set the ack mode to client. We should check if this solution could work as expected.

Using the listener container, we need to care the mode of transaction. If it is in a transaction, ack will not take effect when exception occurs. Only when the transaction complete successfully, the ack takes effect then. That means the sending, receiving and ack operation are all managed by the transaction.

**Comment by jialigit** [comment]
Spring JMS framework provide two implementations for AbstractMessageListenerContainer, i.e. DefaultMessageListenerContainer and SimpleMessageListenerContainer.

For the auto-acknownledge mode, the behavior is different for these two containers as presented above of that after or before the execution of the listener. In addition to this, the DefaultMessageListenerContainer uses pulling style of consumption while the SimpleMessageListenerContainer uses pushing style of consumption. (MessageConsumer.receive() and MessageConsumer.setMessageListener()).



| API | consume type | after or before|
------|----------------|-------------------
| DefaultMessageListenerContainer| pull|before|
| SimpleMessageListenerContainer| push|after|

**Comment by jialigit** [comment]
Conclusion:
To explicityly ack a message using the JmsTemplate and JmsListener.
.  For JmsTemplate

1. Setup the ack mode
```java
jmsTemplate.setSessionAcknowledgeMode(Session.CLIENT_ACKNOWLEDGE);
```
2. Execution runner configuration
```java
@Configuration
public class SimpleConsumerWithTemplate {
    private static final Logger LOGGER = LoggerFactory.getLogger(SimpleConsumerWithTemplate.class);

    private static final String QUEUE_NAME = "que001";

    @Autowired
    private JmsTemplate jmsTemplate;

    @Bean
    public ApplicationRunner runner() {
        return new ApplicationRunner() {

            @Override
            public void run(ApplicationArguments args) throws Exception {
                jmsTemplate.execute(new SessionCallback<Object>() {
                    @Override
                    public Object doInJms(Session session) throws JMSException {

                        MessageConsumer consumer =
                            session.createConsumer(jmsTemplate.getDestinationResolver().resolveDestinationName(session,
                                QUEUE_NAME, false));
                        try {
                            Message message = consumer.receive(1);
                            if (message != null) {
                                User user = (User) ((ObjectMessage) message).getObject();
                                LOGGER.info("Received message from queue: {}", user.getName());
                                message.acknowledge();
                            }

                        } catch (Exception e) {
                            return null;
                        } finally {
                            consumer.close();
                        }
                        return null;
                    }
                }, true);
            }
        };

    }
}

```

.  For JmsListener
In our default message listener container, we set the sessionTransacted to be true, that means we guarantee redelivery in case of a user exception. To explicitly ack the message, we can customize one listener container factory and set the sessionTransacted to be false like beblow:
```java
    @Bean
    @ConditionalOnMissingBean
    public JmsListenerContainerFactory<?> jmsListenerContainerFactory(
        DefaultJmsListenerContainerFactoryConfigurer configurer, ConnectionFactory connectionFactory) {
        DefaultJmsListenerContainerFactory jmsListenerContainerFactory = new DefaultJmsListenerContainerFactory();
        configurer.configure(jmsListenerContainerFactory, connectionFactory);
        jmsListenerContainerFactory.setPubSubDomain(Boolean.FALSE);
        configureCommonListenerContainerFactory(jmsListenerContainerFactory);
        jmsListenerContainerFactory.setSessionTransacted(false);
        return jmsListenerContainerFactory;
    }
```
And then in the logic listener POJO, we ack mannuly like below:
```java
@Service
public class QueueReceiveService {

    private static final String QUEUE_NAME = "que001";

    private final Logger LOGGER = LoggerFactory.getLogger(QueueReceiveService.class);

    @JmsListener(destination = QUEUE_NAME, containerFactory = "jmsListenerContainerFactory")
    public void receiveMessage(Message message) throws JMSException {
        User user = message.getBody(User.class);

        LOGGER.info("Received message from queue: {}", user.getName());
        message.acknowledge();
    }

}
```

**Comment by jialigit** [comment]
close for solved.
