### ISSUE TITLE
Hitting "Timeout on blocking read for 10000000000 NANOSECONDS" on EventProcessorClient.stop

### ISSUE THREAD

**Issue by sbaunthiyal** [Azure/azure-sdk-for-java#26766]
**Describe the bug**
EventProcessorClient is hitting "Timeout on blocking read for 10000000000 NANOSECONDS" on Stopping the processor when EventProcessorClient.stop is executed.

***Exception or Stack Trace***
```
java.lang.IllegalStateException: Timeout on blocking read for 10000000000 NANOSECONDS
	at reactor.core.publisher.BlockingSingleSubscriber.blockingGet(BlockingSingleSubscriber.java:123)
	at reactor.core.publisher.Flux.blockLast(Flux.java:2668)
	at com.azure.messaging.eventhubs.EventProcessorClient.stopProcessing(EventProcessorClient.java:186)
	at com.azure.messaging.eventhubs.EventProcessorClient.stop(EventProcessorClient.java:164)
	at com.alight.upoint.azure.consumer.service.AzureConsumerService.consumeEvents(AzureConsumerService.java:140)
	at com.alight.upoint.azure.consumer.processor.AzureConsumerMessageProcessor.process(AzureConsumerMessageProcessor.java:37)
	at sun.reflect.GeneratedMethodAccessor130.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.springframework.scheduling.support.ScheduledMethodRunnable.run(ScheduledMethodRunnable.java:84)
	at org.springframework.scheduling.support.DelegatingErrorHandlingRunnable.run(DelegatingErrorHandlingRunnable.java:54)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
```
**To Reproduce**
Build consumer with below libraries and execute EventProcessorClient.stop

***Code Snippet***
```java
EventProcessorClient eventProcessorClient = new EventProcessorClientBuilder()
	.processEvent(this::processEvent, Duration.ofMillis(config.getHealthInterval()))
	.processError(this::processError).processPartitionInitialization(this::initializePartition)
	.processPartitionClose(this::closePartition)
	.credential(config.getFullyQualifiedNamespace(), config.getEventHubName(), credential)
	.consumerGroup(config.getConsumerGroup()).checkpointStore(config.getBlobCheckpoint(credential))
	.initialPartitionEventPosition(map).proxyOptions(getproxyOptions())
	.transportType(AmqpTransportType.AMQP_WEB_SOCKETS).buildEventProcessorClient();
			
eventProcessorClient.start();

TimeUnit.MILLISECONDS.sleep(config.getScheduleInterval());

eventProcessorClient.stop();
```
**Expected behavior**
EventProcessorClient should be stopped gracefully.

**Screenshots**
none

**Setup (please complete the following information):**

- OS: linux
- IDE: STS
- Library/Libraries:
azure-client-sdk-parent:1.7.0
azure-messaging-eventhubs:5.10.1
azure-storage-blob:12.14.0
azure-identity:1.4.0
azure-messaging-eventhubs-checkpointstore-blob:1.10.0
azure-core-http-netty:1.11.1
reactor-core:3.4.11
- Java version: 8
- App Server/Environment: Docker
- Frameworks: Spring Boot

**Additional context**
Let us know if SDK logs are required.

**Comment by joshfree** [comment]
@conniey could you please follow up on this customer-reported issue with @sbaunthiyal?

**Comment by conniey** [comment]
What region is your storage account versus the instances that are running EventProcessorClient? We are allotting 10 seconds to remove the ownerIds from the partitions the instance has claimed.. but I guess it is not enough.

**Comment by sbaunthiyal** [comment]
@conniey In this scenario clients end up consuming duplicate offsets. Offsets which already been consumed and committed.

Issues we have noticed are 

1.	The client don’t stop successfully, even when partitions were closed within a few milliseconds.
2.	Even when the client successfully updates the checkpoint, another instance starts with already committed offsets. Which causes duplicate messages.

**Sequence of events:**  
 
1.	The client closes all the partitions but fails to stop and hits the timeout exception.
2.	Since the client is not stopped successfully, it again fetches the ownership of partitions and starts consuming.
4.	It keeps consuming till it hits “New receiver 'nil' with higher epoch of '0' is created hence current receiver 'nil' with epoch '0' is getting disconnected.” exception.
5.	Another instance grabs ownership of the partition and starts from the offset, which was already committed.

Let me know if you are looking for more details..

**Comment by conniey** [comment]
When stop() is called, we reset the ownerId to empty, relinquishing ownership of that partition. The blocking call you see is that we waited 10 seconds for the ownership records to be reset in Azure Blob Storage. If there is network latency, it is possible that it takes more than 10 seconds to reset the ownerId and so you see the exception.  It shouldn't cause a problem though because we have another check on running processors to see if there are any stale ownership records and to steal those if it sees a stale one.

The library leaves updating checkpoints to the user's code, so when a partition is stolen it starts from the last persisted offset in Azure Blob Storage. Do you happen to have any DEBUG/INFO logs when this happens so we can check if the checkpoint was successfully updated in user's callback?

**Comment by sbaunthiyal** [comment]
@conniey Can you please elaborate on "we have another check on running processors to see if there are any stale ownership records and to steal those if it sees a stale one."

Is there a way to override this 10 second wait?

Regarding checkpointing, yes we do have application logs that confirm that the update checkpoint was successful. If you need to see those we can provide them.

**Comment by sbaunthiyal** [comment]
HI @conniey, Didn't hear back from you. Let me know if you care looking for more information.

**Comment by sbaunthiyal** [comment]
Hi @conniey, Looking to hearing back from you. This issue was opened on Jan 27 and since then, encountered this issue daily in production.

**Comment by conniey** [comment]
Apologies for the delay, there are [additional methods](https://github.com/Azure/azure-sdk-for-java/blob/main/sdk/eventhubs/azure-messaging-eventhubs/TROUBLESHOOTING.md#get-additional-help) to get support if this is very pressing.  I looked at both logs:
* I can see that the event at offset "" is received twice.  The guarantee for EventProcessorClient is that you will have _at least once_ consumption.  From https://docs.microsoft.com/azure/event-hubs/event-hubs-event-processor-host#checkpointing:

   > "When the checkpoint is performed, a JSON file with partition-specific information (specifically, the offset), is written to the storage account supplied in the constructor to [EventProcessorHost](https://docs.microsoft.com/en-us/dotnet/api/microsoft.azure.eventhubs.processor.eventprocessorhost). This file is continually updated. It is critical to consider checkpointing in context - it would be unwise to checkpoint every message.  The storage account used for checkpointing probably would not handle this load, but more importantly checkpointing every single event is indicative of a queued messaging pattern for which a Service Bus queue might be a better option than an event hub. The idea behind Event Hubs is that you get "at least once" delivery at great scale."
    * Additional resources: https://docs.microsoft.com/azure/event-grid/compare-messaging-services
* I can't see how the "Timeout on blocking read for x nanoseconds" plays into this issue, is there additional context I am missing?
