### ISSUE TITLE
[QUERY] Partial updates in azure-spring-data-cosmos

### ISSUE THREAD

**Issue by Abhisar** [Azure/azure-sdk-for-java#26776]
Is partial updates available in azure-spring-data-cosmos latest version ? If now any timeline on prospect release ? We are using 3.17.0 version

**Comment by joshfree** [comment]
@backwind1233 could you please follow up with @Abhisar on this github issue?

**Comment by yiliuTo** [comment]
Hi @kushagraThapar could you please help on this issue?

**Comment by sachinadiga** [comment]
Hi @kushagraThapar any updates on this? partial document update seems to be not supported currently. Any timeliness?

**Comment by sachinadiga** [comment]
@yiliuTo this task is still in backlog https://github.com/Azure/azure-sdk-for-java/issues/21433 please work with @kushagraThapar to expedite this.

**Comment by kushagraThapar** [comment]
@sachinadiga  - Patch API is not supported on spring-data-cosmos SDK right now. This is in our backlog, but we don't have any ETA for this as of now. Will update this issue once we start working on it.

**Comment by kushagraThapar** [comment]
Closing out this duplicate issue. Please track https://github.com/Azure/azure-sdk-for-java/issues/21433 issue for any updates.
