### ISSUE TITLE
[QUERY] How to Set StorageProfile.deletionOption / networkinterface.deleteOption on a VirtualMachine osDisk / primary iface

### ISSUE THREAD

**Issue by jloisel** [Azure/azure-sdk-for-java#26775]
**Query/Question**

i'm trying to configure delete options on disks and primary network interface of a virtual machine. Why? Because it's incredibly annoying from code perspective to have to delete disks / ifaces after having deleted a VM. It's error-prone and can easily fail to be done if the backend is redeployed during that phase.

```java
@VisibleForTesting
  static VirtualMachine withDeleteOptions(final VirtualMachine vm) {
    vm
      .innerModel()
      .networkProfile()
      .networkInterfaces()
      .forEach(inet -> inet.withDeleteOption(DeleteOptions.DELETE));
    vm
      .storageProfile()
      .osDisk()
      .withDeleteOption(DiskDeleteOptionTypes.DELETE);

    return vm.update().apply();
  }
```

But sadly, this isn't working at all. It has no effect. Also tried to set them during vm creation, but there is possibility to do so. 

![image](https://user-images.githubusercontent.com/3208716/151516971-a7fec012-2b9f-4260-89cd-dea2eff4aa6a.png)

I would like to do the same using the SDK as what the azure UI  is doing here.

***Why is this not a Bug or a feature Request?***

How can I set disk deletion option / iface delete option  using Java SDK on a virtual machine? 

**Setup (please complete the following information if applicable):**
 - OS: Linux
 - IDE: Intellij
 - Library/Libraries: 

```xml
      <dependency>
        <groupId>com.azure.resourcemanager</groupId>
        <artifactId>azure-resourcemanager-compute</artifactId>
        <version>2.11.0</version>
      </dependency>
```
 
 **Information Checklist**
 Kindly make sure that you have added all the following information above and checkoff the required fields otherwise we will treat the issuer as an incomplete report
- [x] Query Added
- [x] Setup information Added

**Comment by joshfree** [comment]
Thanks for filing this github issue, @jloisel; @weidongxu-microsoft could you please follow up?

**Comment by weidongxu-microsoft** [comment]
@jloisel 
Currently it is WIP at https://github.com/Azure/azure-sdk-for-java/issues/24935

Note that `DeleteOptions` is set when *create* the VM, so that when deleting it, the associated resource will be deleted automatically by compute service.

The WIP is still waiting for the implementation of deep delete for public IP address, which seems still not supported by network service.

**Comment by weidongxu-microsoft** [comment]
Force delete is already in `VirtualMachines.deleteById(id, forceDeletion)`

**Comment by jloisel** [comment]
Thanks! I upgraded to `2.12.0` and i'm able to set delete options on both os disk and primary network iface when creating the vm :+1: 

That's a huge improvement since we had issues to reliably deleting those resources when deleting a vm (since it requires to wait until the vm is terminated). We could get ride of the code doing this :partying_face:
