### ISSUE TITLE
[FEATURE REQ] Ability to consume HttpClientOptions in XHttpClientBuilders.

### ISSUE THREAD

**Issue by kasobol-msft** [Azure/azure-sdk-for-java#26779]
When user wants to configure http client options they have two ways to achieve it. One is via `HttpClientOptions` passed to service builder which are then applied to implicit http client. The other option is to build `HttpClient` and pass that to builder. However the later requires specific knowledge about particular `HttpClient` implementation as the builders don't offer uniform API. We should consider adding ability to pass `HttpClientOptions` to each of http client builders.

**Comment by alzimmermsft** [comment]
Closing as this is consumable through the `HttpClient` provider APIs which is where this is more usable. The `HttpClient` builders allow for finer control than `HttpClientOptions` allows, given they are specific to the given implementation rather than being generalized.
