### ISSUE TITLE
SyncStack - Investigate usage of BinaryData as HttpResponse body carrier.

### ISSUE THREAD

**Issue by kasobol-msft** [Azure/azure-sdk-for-java#26785]
Similarly to `HttpRequest` the `HttpResponse` gives only reactive way to consume the body. https://github.com/Azure/azure-sdk-for-java/blob/cf25b9faf13523afcc28882feacb9d36c3c8b050/sdk/core/azure-core/src/main/java/com/azure/core/http/HttpResponse.java#L62 .
This poses a challenge for synchronous and non-netty scenarios as it introduces layers of conversions back and forth.
For example synchronous user of blobs when consuming input stream backed by okhttp calls goes through okhttp->flux->blob stream series of conversions. These kind of scenarios could be simplified if those conversions were deferred, i.e. http client produced BinaryDataContent that matches best the style of the invocation and eventual conversion would happen at consumption OR even some conversions could be trimmed to zero (e.g. if response's InputStream is served from JDK http client).

**Comment by g2vinay** [comment]
Resolved here: https://github.com/Azure/azure-sdk-for-java/blob/main/sdk/core/azure-core/src/main/java/com/azure/core/http/HttpResponse.java#L79
