### ISSUE TITLE
SyncStack - Investigate synchronous HttpPipeline.

### ISSUE THREAD

**Issue by kasobol-msft** [Azure/azure-sdk-for-java#26786]
Investigate how to propagate synchronous calls through Http Pipeline.

Goals:
- Minimal code duplication
- Nice non-reactive non-callback stack trace should anything go wrong
- Identify plans for complex cases like RetryPolicy

**Comment by g2vinay** [comment]
Resolved here: https://github.com/Azure/azure-sdk-for-java/blob/main/sdk/core/azure-core/src/main/java/com/azure/core/http/policy/HttpPipelinePolicy.java#L38
