### ISSUE TITLE
[Form Recognizer ] Failed to deploy test resource in weekly pipeline

### ISSUE THREAD

**Issue by hongli750210** [Azure/azure-sdk-for-java#26800]
We are running live tests against other clouds like US Gov and Azure China Cloud. The goal is to check whether new azure sdk package work with other clouds or not.

**Error Description:**
When running the Form Recognizer  pipeline on Public and UsGov and Azure China cloud, it runs failed at section Deploy test resource and the error messages is shown as following, for more details please check [here](https://dev.azure.com/azure-sdk/internal/_build/results?buildId=1335354&view=results):
![image](https://user-images.githubusercontent.com/74638143/151685318-912c8f9f-6a9b-42b0-b839-b6ecfac5a803.png)

Expected Behavior:
The deploy test resource can pass in weekly pipeline.

@benbp, @joshfree, @mayurid, @meeraharidasa and @samvaity for notification.

**Comment by benbp** [comment]
@hongli750210 please update your testing branch. We added a new parameter to the scripts and updated the corresponding dynamic cloud configuration on the backend. The updated branch should have [this line](https://github.com/Azure/azure-sdk-for-java/blob/main/eng/common/TestResources/New-TestResources.ps1#L50) updated. Let me know if there is still an issue.

**Comment by hongli750210** [comment]
@benbp I run a pipeline test of `Form Recognizer Service` after updated testing branch. Although the test resources can be successfully delpoyed on Public cloud and entered the testing section, but still failed to deploy test resource on UsGov cloud and China cloud. The update of dynamic cloud configuration on backend on Public cloud has been not synchronized to UsGov Cloud and China Cloud I think. Please update the corresponding dynamic cloud configuration on the backend on UsGov Cloud and China Cloud.

**Comment by joshfree** [comment]
@samvaity could you follow up with @hongli750210?

**Comment by benbp** [comment]
@hongli750210 I believe your branch still needs this change: https://github.com/Azure/azure-sdk-for-java/commit/fc918a0a5d6c94a270ea03813ab07c36b16d8945 so you need to git pull in the main branch.

**Comment by hongli750210** [comment]
@benbp After updating my testing branch again, the test resources can also be successfully delpoyed on UsGov and China cloud. Thank you for your reminder.
