### ISSUE TITLE
  We are getting send events request throttled even though TU were set to 40 and count and size of messaged sent/sec is under limits

### ISSUE THREAD

**Issue by rhyashu** [Azure/azure-sdk-for-java#26808]
We are using EventProducerClient and tried sending events in batches of different sizes but always getting requests throttled and server busy exception in Eventhub Namespace **Metrics** even though the total no of messages and total size of the messages per second are under limits as per the 40 TU setup at the namespace level.

Also whenever there is a throttling errors the no of incoming messages count is also more than the outgoing messages from an event hub. Does the SDK consider the throttled requests as well in the metrics?

Also since throttling can only be at ingress level, can slow consumption of messages at receiver side can cause these throttling/server busy errors?

***Why is this not a Bug or a feature Request?***
Not sure as of now but maybe its a bug

**Setup:**
- OS: Linux VM 
- Event hub Partition: 32
- Consumers: 32
- IDE: Running as a Spring Batch on VM
- Library/Libraries: [e.g. com.azure.spring:azure-messaging-eventhubs:5.10.2]
- TU - 40 (Standard tier)
 
 **Information Checklist**
**Warning received in the logs**
BatchConsole_1.log:14:19:55.322 [**WARN**] from com.azure.core.amqp.implementation.ReactorSender in reactor-executor-1 - entityPath[eventhubName], linkName[eventhubName], deliveryTag[d465ea74cb3c423b93baf9faeee8d216]: Delivery rejected. [Rejected{error=Error{condition=com.microsoft:server-busy, description='The request was terminated because the entity is being throttled. Error code : 50002. Sub error : 105. Please wait 4 seconds and try again. To know more visit https://aka.ms/sbResourceMgrExceptionsS:N:***-EASTUS2-EVENTHUB-01:EVENTHUB:**FEED_EH~11263,CL:427,CC:434,ACC:164808,LUR:IncomingBytes_***-EASTUS2-EVENTHUB-01_354813-1,LUT:2022-01-27T14:19:45.3754918Z,RC:7
- [* ] Query Added
- [* ] Setup information Added

**Comment by joshfree** [comment]
@srnagar could you please follow up with @rhyashu on this `customer-reported` issue?

**Comment by srnagar** [comment]
@rhyashu Thank you for reporting this issue. Could you please share the Event Hubs namespace name that you are attempting to send the events to?

Adding @JamesBirdsall from the service side to provide insights on throttling.

**Comment by rhyashu** [comment]
Hi @srnagar , 
I am not sure if I will be able to share the eventhub namespace name here.. Is there any other option to share it separately?

**Comment by srnagar** [comment]
@rhyashu you could file a support ticket. Please see instructions [here](https://github.com/Azure/azure-sdk-for-java/blob/main/SUPPORT.md#azure-support-tickets) on how to file a support ticket and provide all necessary details including the Event Hubs name and steps to reproduce the issue.

**Comment by rhyashu** [comment]
Hi @srnagar , We did create the support ticket and got the details from msft engineer that the metrics showing on portal are not accurately depict the load/size of the messages and he shared some data based on the raw logs and its going over 40MB in that metric.

**Comment by ramya-rao-a** [comment]
@rhyashu Hopefully your questions were answered during the support call. If not, please feel free to re-open the ticket with support and they can loop in the Event Hubs team to answer further questions on metrics
