### ISSUE TITLE
[BUG] @inhertiDoc doesn't seem to work.

### ISSUE THREAD

**Issue by kasobol-msft** [Azure/azure-sdk-for-java#26814]
The `@inhertiDoc` like here https://github.com/Azure/azure-sdk-for-java/blob/2cd30e97440042b17a94db3438865ed530fb4c08/sdk/formrecognizer/azure-ai-formrecognizer/src/main/java/com/azure/ai/formrecognizer/DocumentAnalysisServiceVersion.java#L23-L29
doesn't seem to work.

See https://docs.microsoft.com/en-us/java/api/com.azure.ai.formrecognizer.documentanalysisserviceversion?view=azure-java-preview
![image](https://user-images.githubusercontent.com/61715331/151881111-933be1fb-80c6-49da-9715-50190321d20d.png)

**Comment by kasobol-msft** [comment]
The approach in https://github.com/Azure/azure-sdk-for-java/pull/26816 didn't work. Including dependency sources in javadoc plugin run results in dependencies being included in the module output - see comment in the PR for details. Other alternatives should be investigated.

**Comment by srnagar** [comment]
This is now fixed.
