### ISSUE TITLE
[BUG] com.microsoft.azure.management.resources.fluentcore.collection.SupportsListingByRegion.listByRegion(Region arg0) API failing with "java.io.IOException: CRC: actual 0x062fb16b != expected 0x46a58e34"

### ISSUE THREAD

**Issue by gaurav-kulkarni** [Azure/azure-sdk-for-java#26827]
**To Reproduce**
Invoke the program that calls below piece of code.

***Code Snippet***
final Region region = Region.US_WEST_CENTRAL;
azure.virtualMachineImages().listByRegion(region);

**Expected behavior**
A valid API response

**Screenshots**
Not Applicable

**Setup (please complete the following information):**
 - OS: [e.g. iOS]: Red Hat Enterprise Linux 8.5 (Ootpa)
 - IDE: [e.g. IntelliJ]: Eclipse
 - Library/Libraries: [e.g. com.azure:azure-core:1.16.0 (groupId:artifactId:version)]: azure-mgmt-resources-1.20.0.jar
 - Java version: [e.g. 8]: openjdk version "11.0.13" 2021-10-19
 - App Server/Environment: [e.g. Tomcat, WildFly, Azure Function, Apache Spark, Databricks, IDE plugin or anything special]: IBM Liberty 21.0.0.12
 - Frameworks: [e.g. Spring Boot, Micronaut, Quarkus, etc]: Not Applicable

If you suspect a dependency version mismatch (e.g. you see `NoClassDefFoundError`, `NoSuchMethodError` or similar), please check out [Troubleshoot dependency version conflict article](https://aka.ms/azsdk/java/dependency/troubleshoot) first. If it doesn't provide solution for the problem, please provide:
- verbose dependency tree (`mvn dependency:tree -Dverbose`)
- exception message, full stack trace, and any available logs

**Additional context**

**Information Checklist**
Kindly make sure that you have added all the following information above and checkoff the required fields otherwise we will treat the issuer as an incomplete report
- [x] Bug Description Added
- [x] Repro Steps Added
- [x] Setup information Added

**Comment by joshfree** [comment]
Thanks for filing this github issue, @gaurav-kulkarni.  @weidongxu-microsoft could you please help route?

**Comment by gaurav-kulkarni** [comment]
@weidongxu-microsoft

Please find below the maven dependencies in the pom:
<dependency>
	<groupId>com.microsoft.azure</groupId>
	<artifactId>azure-annotations</artifactId>
	<version>1.2.0</version>
</dependency>
  
<dependency>
<groupId>com.azure.resourcemanager</groupId>
<artifactId>azure-resourcemanager</artifactId>
<version>2.8.0</version>
<exclusions>
	<exclusion>
		<groupId>com.azure</groupId>
		<artifactId>azure-core</artifactId>
	</exclusion>
	<exclusion>
		<groupId>com.azure</groupId>
		<artifactId>azure-storage-file-share</artifactId>
	</exclusion>
</exclusions>
</dependency>
<dependency>
	<groupId>com.azure</groupId>
	<artifactId>azure-identity</artifactId>
	<version>1.3.7</version>
	<exclusions>
		<exclusion>
			<groupId>com.fasterxml.jackson.core</groupId>
			<artifactId>jackson-core</artifactId>
		</exclusion>
		<exclusion>
			<groupId>com.nimbusds</groupId>
			<artifactId>oauth2-oidc-sdk</artifactId>
		</exclusion>
		<exclusion>
			<groupId>org.slf4j</groupId>
			<artifactId>slf4j-api</artifactId>
		</exclusion>
		<exclusion>
			<groupId>com.microsoft.azure</groupId>
			<artifactId>msal4j</artifactId>
		</exclusion>
		<exclusion>
			<groupId>com.fasterxml.jackson.core</groupId>
			<artifactId>jackson-databind</artifactId>
		</exclusion>
		<exclusion>
			<groupId>com.fasterxml.jackson.core</groupId>
			<artifactId>jackson-annotations</artifactId>
		</exclusion>
		<exclusion>
			<groupId>com.fasterxml.jackson.core</groupId>
			<artifactId>jackson-core</artifactId>
		</exclusion>
		<exclusion>
			<groupId>io.netty</groupId>
			<artifactId>netty-handler</artifactId>
		</exclusion>
		<exclusion>
			<groupId>io.netty</groupId>
			<artifactId>netty-codec-http</artifactId>
		</exclusion>
		<exclusion>
			<groupId>io.netty</groupId>
			<artifactId>netty-codec-http2</artifactId>
		</exclusion>
	</exclusions>
</dependency>
<dependency>
	<groupId>io.netty</groupId>
	<artifactId>netty-codec-http</artifactId>
	<version>4.1.72.Final</version>
</dependency>
<dependency>
	<groupId>io.netty</groupId>
	<artifactId>netty-codec-http2</artifactId>
	<version>4.1.72.Final</version>
</dependency>
 <dependency>
	<groupId>io.netty</groupId>
	<artifactId>netty-handler</artifactId>
	<version>4.1.70.Final</version>
</dependency>
<dependency>
	<groupId>commons-net</groupId>
	<artifactId>commons-net</artifactId>
	<version>3.8.0</version>
</dependency>
<dependency>
	<groupId>com.microsoft.azure</groupId>
	<artifactId>azure</artifactId>
	<version>1.20.0</version>
	<exclusions>
		<exclusion>
			<groupId>com.google.guava</groupId>
			<artifactId>guava</artifactId>
		</exclusion>
		<exclusion>
			<groupId>com.squareup.retrofit2</groupId>
			<artifactId>retrofit</artifactId>
		</exclusion>
		<exclusion>
			<groupId>net.minidev</groupId>
			<artifactId>json-smart</artifactId>
		</exclusion>
		<exclusion>
			<groupId>com.microsoft.azure</groupId>
			<artifactId>azure-annotations</artifactId>
		</exclusion>
		<exclusion>
			<groupId>com.fasterxml.jackson.core</groupId>
			<artifactId>jackson-databind</artifactId>
		</exclusion>
		<exclusion>
			<groupId>com.google.code.gson</groupId>
			<artifactId>gson</artifactId>
		</exclusion>
		<exclusion>
			<groupId>commons-codec</groupId>
			<artifactId>commons-codec</artifactId>
		</exclusion>
	</exclusions>
</dependency>
<dependency>
	<groupId>com.google.code.gson</groupId>
	<artifactId>gson</artifactId>
	<version>2.8.9</version>
</dependency>
<dependency>
	<groupId>commons-codec</groupId>
	<artifactId>commons-codec</artifactId>
	<version>1.15</version>
</dependency>
<dependency>
	<groupId>com.fasterxml.jackson.core</groupId>
	<artifactId>jackson-databind</artifactId>
	<version>2.13.1</version>
</dependency>
<dependency>
	<groupId>com.squareup.retrofit2</groupId>
	<artifactId>retrofit</artifactId>
	<version>2.9.0</version>
</dependency>
<dependency>
	<groupId>com.github.cverges.expect4j</groupId>
	<artifactId>expect4j</artifactId>
	<version>1.6</version>
	<exclusions>
		<exclusion>
			<groupId>commons-net</groupId>
			<artifactId>commons-net</artifactId>
		</exclusion>
		<exclusion>
			<groupId>com.jcraft</groupId>
			<artifactId>jsch</artifactId>
		</exclusion>
	</exclusions>
</dependency>
<dependency>
	<groupId>com.jcraft</groupId>
	<artifactId>jsch</artifactId>
	<version>0.1.55</version>
</dependency>
<dependency>
	<groupId>com.google.guava</groupId>
	<artifactId>guava</artifactId>
	<version>31.0.1-jre</version>
</dependency>
<dependency>
	<groupId>com.nimbusds</groupId>
	<artifactId>nimbus-jose-jwt</artifactId>
	<version>9.15.2</version>
</dependency>
<dependency>
	<groupId>com.nimbusds</groupId>
	<artifactId>lang-tag</artifactId>
	<version>1.5</version>
</dependency>
<dependency>
	<groupId>com.azure</groupId>
	<artifactId>azure-sdk-bom</artifactId>
	<version>1.0.1</version>
	<type>pom</type>
</dependency> 

And below is the exceptio stacktrace we are getting:
java.io.IOException: CRC: actual 0x062fb16b != expected 0x46a58e34
rx.exceptions.Exceptions.propagate(Exceptions.java:57)
rx.observables.BlockingObservable.blockForSingle(BlockingObservable.java:463)
rx.observables.BlockingObservable.single(BlockingObservable.java:340)
com.microsoft.azure.management.compute.implementation.VirtualMachineImagesInner.listPublishers(VirtualMachineImagesInner.java:480)
com.microsoft.azure.management.compute.implementation.VirtualMachinePublishersImpl.listByRegion(VirtualMachinePublishersImpl.java:50)
com.microsoft.azure.management.compute.implementation.VirtualMachineImagesImpl.listByRegion(VirtualMachineImagesImpl.java:77)
com.microsoft.azure.management.compute.implementation.VirtualMachineImagesImpl.listByRegion(VirtualMachineImagesImpl.java:72)
com.hcl.scheduling.agent.azure.jobexecutor.AzureUtils.azureTestConnection(AzureUtils.java:33)
com.hcl.scheduling.agent.azure.jobexecutor.AzureAction.testConnection(AzureAction.java:304)
com.hcl.scheduling.agent.azure.jobexecutor.AzureAction.runExecutorCommand(AzureAction.java:199)
com.ibm.scheduling.agent.core.jobexecutor.LocalJobExecutorManager.runExecutorCommand(LocalJobExecutorManager.java:191)
com.ibm.scheduling.osgi.Framework.runExecutorCommand(Framework.java:137)

Please advice.

**Comment by weidongxu-microsoft** [comment]
@gaurav-kulkarni 

I see you already have (latest is 2.11.0)
```
<groupId>com.azure.resourcemanager</groupId>
<artifactId>azure-resourcemanager</artifactId>
<version>2.8.0</version>
```

Any reason you need another azure resourcemanager lib here?
```
	<groupId>com.microsoft.azure</groupId>
	<artifactId>azure</artifactId>
	<version>1.20.0</version>
```

This 2 lib is identical in functionality (2.x got more features and compatible with azure-core, hence preferred), other than the namespace and artifact ID change.
