### ISSUE TITLE
Using ComputIfAbsent in all client telemetry maps

### ISSUE THREAD

**Issue by simplynaveen20** [Azure/azure-sdk-for-java#26838]
As per https://github.com/Azure/azure-sdk-for-java/pull/26393/files/411a166c920afc7a63d01d2771008ee0201585a4#r788292934 , please use ComputIfAbsent  in above file , plus in TracerProvider,CosmosPageFlux etc where ever we are accessing ClientTelemetry map.
We need to do the perf testing on this change

**Comment by kushagraThapar** [comment]
@aayush3011  pls take a look at this, thanks!
