### ISSUE TITLE
[QUERY] How to change throughput on container/database using Cosmos DB Spark connector

### ISSUE THREAD

**Issue by tomasvanpottelbergh** [Azure/azure-sdk-for-java#26868]
**Query/Question**
We would like to programmatically change the provisioned throughput on a Cosmos DB (SQL API) database or container in our Spark pipelines. The [configuration reference](https://github.com/Azure/azure-sdk-for-java/blob/main/sdk/cosmos/azure-cosmos-spark_3_2-12/docs/configuration-reference.md) of the Spark connector mentions several options related to throughput, but I can't find more details about what they do.

Is what I am asking possible using the current connector?

**Setup:**
 - Library/Libraries: com.azure.cosmos.spark:azure-cosmos-spark_3-1_2-12:4.6.0

**Comment by kushagraThapar** [comment]
@FabianMeiswinkel  - is this possible ? If so, how to do it. Please help.

**Comment by FabianMeiswinkel** [comment]
Not yet natively via SPARK SQL - only by using python or Java SDK directly. But it is a feature that has been asked for - and I am planning to add it for the next release 4.7.0

**Comment by FabianMeiswinkel** [comment]
So probably later this month

**Comment by tomasvanpottelbergh** [comment]
Thank you for the answer, we would be very interested to have this feature so we don't need to use two SDKs!

Could you also explain or point to more documentation about what the ["Throughput control" properties](https://github.com/Azure/azure-sdk-for-java/blob/main/sdk/cosmos/azure-cosmos-spark_3_2-12/docs/configuration-reference.md#throughput-control-config) do? Is this control on the client side? An example on how to use those would be very much appreciated as well.

**Comment by Uranium2** [comment]
I'm also very interrested. I don't want to install azure cli or an other SDK on my docker images. It would decomplexify the usage od CosmosDB in Databricks/PySpark

**Comment by FabianMeiswinkel** [comment]
I have a PR out for this here - https://github.com/Azure/azure-sdk-for-java/pull/33369
This should be included in the Feb. 2023 release (to-be-released later this week or early next week) - new version should be 4.17.0

**Comment by Uranium2** [comment]
@FabianMeiswinkel I see this PR has been merged to master. Which is great news! But I find no where to download the new Jar. At the moment I have the `azure_cosmos_spark_3_2_2_12_4_11_2.jar`, where can I find a version with your modification or how can I build it myself ?
