### ISSUE TITLE
mgmt, verify wildcard support in network

### ISSUE THREAD

**Issue by weidongxu-microsoft** [Azure/azure-sdk-for-java#26885]
Probably in app gateway. wait for more info in email.

> If the customers are  on track2 SDK (e.g. version 2.4) – this already has support for Network 2020-08 api-version and will soon update to 2020-11 and 2021-02.
The existing API-version 2020-08 already supports wildcard listener.

**Comment by weidongxu-microsoft** [comment]
Feature https://docs.microsoft.com/en-us/azure/application-gateway/multiple-site-overview#wildcard-host-names-in-listener

**Comment by XiaofeiCao** [comment]
We do not have convenient layer support for wildcard hostname, but already have for regular hostname listener. I'll add support for it by adding a new method with `hostnames` parameter.
Apart from wildcard listener, user can specify multiple hostnames (including wildcard) in the new `hostnames` parameter, and a SAN certificate will be needed in this case. 
> If multiple host names are mentioned in the same listener, you must upload a SAN certificate (Subject Alternative Names) with the CNs matching the host names mentioned

Maybe we want to support uploading SAN certificate this time as well?

**Comment by weidongxu-microsoft** [comment]
In short term, we probably check if we just switch from `hostname` to `hostnames`.

**Comment by XiaofeiCao** [comment]
> Not sure if SAN certificate is already handled by HasSslCertificate class.

Agreed, the change maybe exist only in the content of the certificate...

> In future, maybe we can let user repeat withHostname for multiple hostname?

Maybe add a `withHostnames` as well if the user wants to replace the existing hostnames?

**Comment by weidongxu-microsoft** [comment]
The usual pattern from what I saw is `withoutHostname` (though it is not mandatory). e.g.
```
.withoutHostname(name1)
.withHostname(name2)
.withHostname(name3)
```
