### ISSUE TITLE
Reactor. Memory leak

### ISSUE THREAD

**Issue by typik89** [Azure/azure-sdk-for-java#26893]
I created an issue in spring-webflux project: https://github.com/spring-projects/spring-framework/issues/27965.
But It seems that this is a reactor issue.
I created a test to reproduce behavior when objects created during the running of a pipeline of creating byteArray aggregate are held in the heap memory for a long time after finishing the pipeline: https://github.com/typik89/webfluxMemoryRetroProject/blob/main/src/test/kotlin/ru/typik/reactor/MemoryLeakTest.kt
When I run the test with -xmx1000MB, I see 6-7 log messages about ByteArray being created and after that, I see OutOfMemoryError and test fails.
When I run the test with -xmx2000MB, the test works fine in an infinite loop. I create a heap dump and I see 9 ByteArrays with a size of about 130MB. It seems that Reactor holds 9 results of pipeline in the heap and other results are released successfully. I don't understand why it happens and what is this magical number 9 and how I can configure it.

**Comment by joshfree** [comment]
Hi @typik89 as others have posted in the linked issue above, https://github.com/spring-projects/spring-framework/issues/27965#issuecomment-1031673702, it might make more sense for this issue to be in https://github.com/reactor/reactor-core/issues depending on the repro.

If you could fill out the GitHub issue template for this GitHub repo with more details on the Azure SDK for Java client library that you're using we can help further.  Here is the link https://github.com/Azure/azure-sdk-for-java/blob/main/.github/ISSUE_TEMPLATE/bug_report.md.  Thank you.

**Comment by typik89** [comment]
Sorry, I must have mixed up :)
