### ISSUE TITLE
Spring compatibility matrix for older SDK version ( com.microsoft.azure.* , or <= 2.2.5)

### ISSUE THREAD

**Issue by antoineclaval** [Azure/azure-sdk-for-java#26906]
**Query/Question**

I can't find the compatibility matrix for older version of the Azure sdk for java and Spring Boot. 
By older version I mean : the version under the com.microsoft.azure.* ( as opposed to com.azure.* ). 

For instance, I'm using com.microsoft.azure.azure-servicebus-spring-boot-starter:2.2.0 , what are the compatibles spring-boot version? 

I'm looking for a page like this one : https://github.com/Azure/azure-sdk-for-java/wiki/Spring-Versions-Mapping
But for version <= 2.2.5 of the SDK. 

***Why is this not a Bug or a feature Request?***
I'm looking for documentation. 

**Setup (please complete the following information if applicable):**
 - Library/Libraries: com.microsoft.azure.azure-servicebus-spring-boot-starter:2.2.0
 
 **Information Checklist**
 Kindly make sure that you have added all the following information above and checkoff the required fields otherwise we will treat the issuer as an incomplete report
- [x] Query Added
- [x] Setup information Added. N/A

**Comment by saragluna** [comment]
@chenrujun please take a look at this.

**Comment by chenrujun** [comment]
Hi, @antoineclaval 

Thanks for reaching out.
Now you can refer to this page to get the information about the compatibility matrix: https://github.com/Azure/azure-sdk-for-java/tree/azure-spring-boot_3.12.0/sdk/spring

We will consider to put the matrix to a new place. We will use current issue to track this task.

**Comment by antoineclaval** [comment]
thanks. that clarify things.

**Comment by chenrujun** [comment]
Related wiki page updated: 
https://github.com/Azure/azure-sdk-for-java/wiki/Spring-Versions-Mapping#1-spring-cloud-azure-support-policy

Closing this issue.
