### ISSUE TITLE
[Epic] Improvements of BI related tasks

### ISSUE THREAD

**Issue by backwind1233** [Azure/azure-sdk-for-java#26919]
> This issue is only used for tracking, there should not have sensitive data here.

We need to do some improvements to our BI.

- [ ] Workout a wiki about the current situation of our BI-related stuff.

**Accuracy**

- [x] #26994

**Completeness**

- [ ] #26995

**Performance**
- [ ] #27487

**Comment by stliu** [comment]
I don't think you need an Epic issue here, isn't label enough?

**Comment by stliu** [comment]
I'm closing this epic issue, don't see any value form it
