### ISSUE TITLE
NullPointerException when publishing events to EventHub

### ISSUE THREAD

**Issue by sriram-adpusuhup** [Azure/azure-sdk-for-java#26921]
**Describe the bug**
When publishing to EventHub using the latest SDK, we get an error `LinkedList.node(int) is null` [ Full Error attached below ]

***Exception or Stack Trace***
Exception : NullPointerException
Stack Trace: 
![Screenshot 2022-02-06 at 5 34 42 PM](https://user-images.githubusercontent.com/60172790/152942082-fa4d010e-4931-4ed0-a5bc-f04c2493657f.png)

**To Reproduce**
* Create a JAVA project with EventHub SDK. Use the producer snippet below and start publishing events.

***Code Snippet***
```
public class EventPublisher {

    private static final EventHubProducerClient producer;
    private static EventDataBatch batch;

    static {
        producer = new EventHubClientBuilder()
                .connectionString("<CONNECTION_STRING>", "<EVENT_HUB_NAME>")
                .buildProducerClient();

        batch = producer.createBatch();
    }

    public static void publish(Event event) {

        EventData eventData = new EventData(event.getEventData().encode());
        eventData.getProperties().put("eventName", event.getEventName());
        eventData.getProperties().put("isValid", Boolean.toString(event.isValid()));

        if (event.isValid() && !batch.tryAdd(eventData)) {
            //batch is full, send the batch and create a new batch
            System.out.println("Pushing to hub");
            producer.send(batch);

            batch = producer.createBatch();

            // since we couldn't add the event earlier, we add it in the batch now
            batch.tryAdd(eventData);
        }

    }

    public static void flushEvents() {
        System.out.println("Flushing Events");
        if (batch.getCount() > 0 ) {
            producer.send(batch);
        }

        producer.close();
    }
}
```

**Expected behavior**
Events are published to the event hub without errors

**Screenshots**

**Setup (please complete the following information):**
 - OS: MacOS
 - IDE: ntelliJ
 - Library/Libraries:  `com.azure:azure-messaging-eventhubs:5.10.4` [ Tried 5.10.3 too ]
 - Java version: JDK 16
 - App Server/Environment: VertX inbuilt server
 - Frameworks: [VertX](https://vertx.io/)

**Additional context**
There have been rare cases where events are published, but I can't find a pattern. In most cases, an error is thrown but there have been instances where events were published. There was absolutely no change in the code.

**Information Checklist**
Kindly make sure that you have added all the following information above and checkoff the required fields otherwise we will treat the issuer as an incomplete report
- [x ] Bug Description Added
- [ x] Repro Steps Added
- [ x] Setup information Added

**Comment by joshfree** [comment]
Thanks for reporting this @sriram-adpusuhup.

@conniey @anuchandy could you please take a look at this NullPointerExcception leaking from Event Hubs?

**Comment by conniey** [comment]
The line of code throwing a NullPointerException is this: https://github.com/Azure/azure-sdk-for-java/blob/main/sdk/eventhubs/azure-messaging-eventhubs/src/main/java/com/azure/messaging/eventhubs/EventHubProducerAsyncClient.java#L540. However, access to its indexes are via a for-loop based on its count.

I noticed that your code uses `static` for reads and writes to the `EventDataBatch`. Is your code running in a single-threaded environment? If not, I can see a race condition where multiple threads are in the same `static void publish(EventData)` method between sending and re-assigning the new `EventDataBatch`.
