### ISSUE TITLE
[FEATURE REQ]Composite Key azure cosmos java

### ISSUE THREAD

**Issue by deepak9764** [Azure/azure-sdk-for-java#26926]
@Data
[@Container]()(containerName = "tag")
@ToString
@EqualsAndHashCode
[@Builder]()
@JsonInclude(JsonInclude.Include.NON_NULL)
@JsonIgnoreProperties(ignoreUnknown = true)
[@NoAr]()gsConstructor
@AllArgsConstructor
public class Tag {

 @Id
 private String tagName;
 @Id
 private String domainName;
 @PartitionKey
 private String countryDcOrgUnit;

}

I need to create container with name tag having tagName and domainName as unique combination.... but after running this i am getting error .. only one field with @Id annotation!
how to crate container with composite key as primary key

**Comment by kushagraThapar** [comment]
@deepak9764  thanks for creating this issue, I am investigating it.

**Comment by kushagraThapar** [comment]
@deepak9764  - I think you can use the feature of Nested Partition Key Path in azure-spring-data-cosmos to solve the unique key problem in spring - https://github.com/Azure/azure-sdk-for-java/blob/main/sdk/cosmos/azure-spring-data-cosmos/README.md#nested-partition-key-support

Please read here for more details on Unique key -> https://docs.microsoft.com/en-us/azure/cosmos-db/unique-keys

https://docs.microsoft.com/en-us/azure/cosmos-db/how-to-define-unique-keys?tabs=dotnetv2

**Comment by deepak9764** [comment]
Please read here for more details on Unique key -> https://docs.microsoft.com/en-us/azure/cosmos-db/unique-keys
i want to create unique path as mentioned in above path DocumentCollection container = new DocumentCollection();
container.setId("container");

// create array of strings and populate them with the unique key paths
Collection<String> uniqueKey1Paths = new ArrayList<String>();
uniqueKey1Paths.add("/firstName");
uniqueKey1Paths.add("/lastName");
uniqueKey1Paths.add("/emailAddress");
Collection<String> uniqueKey2Paths = new ArrayList<String>();
uniqueKey2Paths.add("/address/zipCode");

// create UniqueKey objects and set their paths
UniqueKey uniqueKey1 = new UniqueKey();
UniqueKey uniqueKey2 = new UniqueKey();
uniqueKey1.setPaths(uniqueKey1Paths);
uniqueKey2.setPaths(uniqueKey2Paths);

// create a new UniqueKeyPolicy object and set its unique keys
UniqueKeyPolicy uniqueKeyPolicy = new UniqueKeyPolicy();
Collection<UniqueKey> uniqueKeys = new ArrayList<UniqueKey>();
uniqueKeys.add(uniqueKey1);
uniqueKeys.add(uniqueKey2);
uniqueKeyPolicy.setUniqueKeys(uniqueKeys);

// set the unique key policy
container.setUniqueKeyPolicy(uniqueKeyPolicy);

using annotation

**Comment by deepak9764** [comment]
I want to create unique key path for tagName and domainName using annotation


@Data
[@Container]()(containerName = "emptyTag")
@ToString
@EqualsAndHashCode
[@Builder]()
@JsonInclude(JsonInclude.Include.NON_NULL)
@JsonIgnoreProperties(ignoreUnknown = true)
[@NoAr]()gsConstructor
@AllArgsConstructor
public class Tag {

[@Id]()
@GeneratedValue
private String id;
private String tagName;
private String domainName;
@PartitionKey
private String countryDcOrgUnit;

}

**Comment by kushagraThapar** [comment]
@deepak9764  - that's what this example shows - https://github.com/Azure/azure-sdk-for-java/blob/main/sdk/cosmos/azure-spring-data-cosmos/README.md#nested-partition-key-support

If you see here, this line is doing the trick -> `partitionKeyPath`

```
@Container(containerName = "nested-partition-key", partitionKeyPath = "/nestedEntitySample/nestedPartitionKey")
public class NestedPartitionKeyEntitySample {

    private NestedEntitySample nestedEntitySample;
}
public class NestedEntitySample {
    private String nestedPartitionKey;
}
```

**Comment by SaurabhSharma-MSFT** [comment]
@deepak9764 Please let us know if this resolves your issue.

**Comment by deepak9764** [comment]
This feature  is for partitionKey! I already have partitionKey

It doesn’t resolve my problem.

**Comment by kushagraThapar** [comment]
@deepak9764  - to clarify -> you have 2 questions in your original post: 

```
I need to create container with name tag having tagName and domainName as unique combination.... but after running this i am getting error .. only one field with @id annotation!

how to crate container with composite key as primary key
```

To create unique key, above is the solution, are you referring to just the container name question?

**Comment by SaurabhSharma-MSFT** [comment]
@deepak9764 Did you get a chance to look at @kushagraThapar's suggestion.

**Comment by deepak9764** [comment]
Ok thanks :)
