### ISSUE TITLE
Remove RevApi Suppression for com.azure.spring*

### ISSUE THREAD

**Issue by alzimmermsft** [Azure/azure-sdk-for-java#26947]
The RevApi package suppression of `com.azure.spring*` (https://github.com/Azure/azure-sdk-for-java/blob/main/eng/code-quality-reports/src/main/resources/revapi/revapi.json#L89) needs to be removed to enable RevApi to monitor Azure Spring libraries for API additions, removals, or other changes.

**Comment by kasobol-msft** [comment]
It seems that revapi quite diverged between main and spring 4 branches.

spring: https://github.com/Azure/azure-sdk-for-java/blob/9d677631565936bdd93005b3dcf0465237cc1254/eng/code-quality-reports/src/main/resources/revapi/revapi.json#L24-L36[](https://github.com/Azure/azure-sdk-for-java/blob/9d677631565936bdd93005b3dcf0465237cc1254/eng/code-quality-reports/src/main/resources/revapi/revapi.json#L24-L36)

main: https://github.com/Azure/azure-sdk-for-java/blob/a3add55fb11f199b311ad9115820fc5d640337be/eng/code-quality-reports/src/main/resources/revapi/revapi.json#L88-L89

**Comment by saragluna** [comment]
We will remove the revapi suppression from the main branch, and will try to apply targeted suppression rather than suppressing the whole package for the 4.0 branch.

**Comment by saragluna** [comment]
Closed in #27078 and #27031.
