### ISSUE TITLE
[FEATURE REQ] Spring Cloud Azure DefaultAzureCredential improvements

### ISSUE THREAD

**Issue by saragluna** [Azure/azure-sdk-for-java#26953]
**Is your feature request related to a problem? Please describe.**
Now in Spring Cloud Azure 4.0, we will fall back to the DAC if no credential is specified or if the user wants to use the system-assigned managed identity. There are two problems with this design:
- If the user wants to use system-assigned MI, there's no way for us to tell from the properties: `client-id` or `managed-identity-client-id`. The Spring Cloud Azure implementation will fall back to the DAC.
- The DAC chain is not efficient and is not easy for users to debug when there's a problem on the chain. 

**Describe the solution you'd like**
- We can delete the `managed-identity-client-id` property and add one `enable-managed-identity` flag, so we can use this flag + `client-id` to construct the correct managed identity explicitly instead of falling back to DAC.
- We should avoid using the DAC. Instead, we can provide a configuration property for users to specify explicitly which tool they want to use as the default credential, such as `spring.cloud.azure.default-credential`. 

**Information Checklist**
Kindly make sure that you have added all the following information above and checkoff the required fields otherwise we will treat the issuer as an incomplete report
- [x] Description Added
- [x] Expected solution specified

**Comment by saragluna** [comment]
Hi @schaabs, could you help take a look at this issue to see whether I describe it correctly?

**Comment by schaabs** [comment]
This describes my what I was suggesting fairly well. One thing I'd like to clarify a bit.

> We should avoid using the DAC. Instead, we can provide a configuration property for users to specify explicitly which tool they want to use as the default credential, such as spring.cloud.azure.default-credential

Here I was suggesting you allow developers to specify dev environment specific credentials from the Azure.Identity library, such as the `AzureCliCredential`, `AzurePowerShellCredential`, `VisualStudioCodeCredential` or `IntelliJCredential` to authenticate explicitly in the development environment, rather than falling back to the `DefaultAzureCredential` or adding another default flow  in spring.cloud.azure

**Comment by saragluna** [comment]
@schaabs I guess this "allow developers to specify dev environment specific credentials" can be added after GA?

**Comment by saragluna** [comment]
Will use this issue https://github.com/Azure/azure-sdk-for-java/issues/27448 to track the second feature request, closing this one now.
