### ISSUE TITLE
ERROR the connection was inactive for more than the allowed 300000 milliseconds...

### ISSUE THREAD

**Issue by r1ckr** [Azure/azure-sdk-for-java#26968]
**Describe the bug**
We are seeing these ERROR logs all the time in all the apps that talk to service bus.

***Exception or Stack Trace***
```
2022-02-09 14:22:10.361 ERROR 36280 --- [ctor-executor-2] c.a.c.a.i.RequestResponseChannel         : connectionId[MF_ee7f60_1644415609117] linkName[cbs] Error in SendLinkHandler. Disposing unconfirmed sends.
The connection was inactive for more than the allowed 300000 milliseconds and is closed by container 'LinkTracker'. TrackingId:abfbe36f1cb3408ca596ba408110e81b_G7, SystemTracker:gateway7, Timestamp:2022-02-09T14:22:10, errorContext[NAMESPACE: servicebus-test-delete-me.servicebus.windows.net. ERROR CONTEXT: N/A, PATH: $cbs, REFERENCE_ID: cbs:sender, LINK_CREDIT: 98]
2022-02-09 14:23:14.948 ERROR 36280 --- [     parallel-6] c.a.c.a.i.RequestResponseChannel         : connectionId[MF_ee7f60_1644415609117] linkName[cbs]: Unable to open send and receive link.
```

**To Reproduce**
Leave a connection open without receiving or sending messages for a while.

**Expected behavior**
If this is expected, then this is simply a DEBUG or INFO log and it has to be changed to that. If we need to fix something in our code, then please explain us what we need to change in order to not get these error codes.

The alternative is to suppress all logs coming from c.a.c.a.i.RequestResponseChannel, but this would remove any possible true issues that we might have in that class. 

**Setup:**
 - OS: Linux, macOS
 - IDE: IntelliJ
 - Library/Libraries: com.azure:azure-core:1.25.0, com.azure:azure-messaging-servicebus:7.5.2
 - Java version: 11
 - App Server/Environment: Tomcat
 - Frameworks: Spring Boot 

**Additional context**
This is failing within Azure Kubernetes Service and from our development laptops

**Information Checklist**
Kindly make sure that you have added all the following information above and checkoff the required fields otherwise we will treat the issuer as an incomplete report
- [x] Bug Description Added
- [x] Repro Steps Added
- [x] Setup information Added

**Comment by joshfree** [comment]
@anuchandy could you please follow up?

/cc @Azure/azsdk-sb-java as fyi

**Comment by r1ckr** [comment]
Any progress on this?

**Comment by anuchandy** [comment]
From RequestResponseChannel perspective, this is just another error notified from upstream; hence it is logged in ERROR level. We identified a few times that RequestResponseChannel was the culprit that denied Receiver from recovering. Therefore, these exceptions in logs are crucial to access the stack trace, to help with resolving (future similar) non-recovered receivers impacting user SLAs. That's the context, but we're discussing this within the team.

**Comment by r1ckr** [comment]
Could you mark this at least as a WARN, the application is not dying it is actually working as expected, but it kills our monitoring and alerting, we have to put rules in place to ignore these errors. What we have done so far is to disable logging from RequestResponseChannel because it was too noisy, now any real issue will be hidden and this is a problem.

**Comment by anuchandy** [comment]
Yes, agree, I'll downgrade to warn.
