### ISSUE TITLE
Address Spring Cloud Azure configuration properties API Review feedback

### ISSUE THREAD

**Issue by saragluna** [Azure/azure-sdk-for-java#26970]
There are several feedbacks on the Spring Cloud Azure configuration properties, we should address them before the beta4 release:

--- 
1. Feedback from @lmolkova 

Here's the list of concerns I had that made me come up with proposal to separate http and amqp and retry policies and make everything more explicit. It's based on [list of properties in documentation](https://microsoft.github.io/spring-cloud-azure/4.0.0-beta.3/4.0.0-beta.3/reference/html/appendix.html#migration-guide-for-4-0).

I hope it can clarify my concerns on having the same configuration property names for different classes.

- ~there is no global retry or proxy configuration, but there is global HTTP client (timeouts) configuration - why so and is it intentional? Global configuration for them would make sense.~
if both global http and amqp configurations are supplied, how would we differentiate them? would we share exactly the same config for http and amqp?
- appconfiguration.retry.timeout - does not exists on SDK retry policy for http clients. Allowing to configure it without mapping to any SDK property would be misleading
- retry.backoff.delay configures fixed delay strategy when retry.backoff.multiplier is not set
- retry.backoff.multiplier does not match anything on the SDK and only used as a marker of exponential backoff strategy.
- retry.max-attempts renamed in v4 , used to be max-retries: why stop using SDK terminology?
- keyvault.certificate.proxy.authentication-type - does not exists for any HTTP-based client but listed for them
- http client options have different path when they are used in client (e.g. fileshare.client.connection-idle-timeout)
 vs global client.http.connection-idle-timeout. When it comes to fileshare.client.application-id- it's not clear which options should be instantiated (ClientOptions or HttpClientOptions) which can be fragile and lead to different behavior
- cosmos.gateway-connection.proxy has SDK's ProxyOptions type and would not be populated, perhaps nested annotation is missing.

---
2. Feedback from @conniey on Event Hubs
- Consistency between "eventhub" and "eventhubs" the product is "Event Hubs". 
  * Never mind, I see "eventhub" is legacy
- "spring.cloud.azure.eventhubs.custom-endpoint-address" and "spring.cloud.azure.eventhubs.consumer.custom-endpoint-address" seem duplicated.
  * It isn't specific to a consumer, rather the entire connection.
- Some of the properties in the subcategories confuse me because they aren't specific to consuming messages.
  * spring.cloud.azure.eventhubs.consumer.*
  * spring.cloud.azure.eventhubs.processor.*
  * spring.cloud.azure.eventhubs.producer.*
  * **For example**: spring.cloud.azure.eventhubs.consumer.retry.timeout
    * Why not "spring.cloud.azure.eventhubs.retry.timeout"?
  * Ex: spring.cloud.azure.eventhubs.producer.namespace
    * Why not "spring.cloud.azure.namespace?
  * "spring.cloud.azure.eventhubs.producer.namespace"
    * I think the namespace should match what users see in Event Hubs client library, "fully-qualified-namespace"

--- 
3. Feedback from @g2vinay on Identity
Overall these properties look fine, they have client-id and managed-identity-client-id as separate properties here.
From functionality point of view, there is some potential to merge these, unless there's a use case where both Service Principal and Managed Identity Auth are used at the same time. (which I doubt is a legit use case)
A question for Spring folks to be, is it expected that the user can specify both managed identity client id and client-id and client-secret, which results in application using separate authentication mechanism when running.
Assuming, these two are not expected to be configured together by the user.
Client-id when specified alone can be used for Managed Identity too.
This design to have managed identity client id as separate I feel might've been inspired from Identity's DAC builder.
But DAC in Identity doesn't let user specify a generic client-id and only lets them specify managed identity client id to scope it to MI level.

---
4. Feedback from sync meeting with Java architects

We should make most of the @ConfigurationProperties visibility to package level if possible.

**Comment by saragluna** [comment]
And also this #26953.

**Comment by saragluna** [comment]
To answer the Event Hubs feedback here:

We are trying to build a layered configuration for Event Hubs and Service Bus, which has a top layer -- the namespace layer, and a separate layer for a producer, a consumer, and a processor. For example, if users want to specify a producer + a consumer client in a Spring Boot application, they can specify:
```yaml
spring.cloud.azure.eventhubs:
  namespace: my-namespace
  producer:
    eventhub-name: eventhub1
  consumer:
    eventhub-name: eventhub2
```
In this case, `eventhub1` and `eventhub2` will be in the same EH namespace. With the layered configuration, when users want to connect to an `eventhub3` in a separate namespace, they can do following:
``` 
spring.cloud.azure.eventhubs:
  namespace: my-namespace
  producer:
    eventhub-name: eventhub1
  consumer:
    namespace: my-another-namespace
    eventhub-name: eventhub3
```
The layered configuration gives users the flexibility to construct a messaging application.

**Comment by lmolkova** [comment]
More on cosmos properties:
- `cosmos.gateway-connection.proxy`  and `spring.cloud.azure.cosmos.permissions` are complex types, property is defined, but nested properties are not defined. there is no metadata and there is no way to populate them via config. They should not be listed as properties considering this.
- `cosmos.connection-mode` is null by default, meaning this code block does nothing and gateway or direct configs are ignored. it should follow SDK default (direct) or clearly communicate in docs that property is required (and log error if it's not provided)
  https://github.com/Azure/azure-sdk-for-java/blob/3a1c944c376169588412248fb8667307390faa1e/sdk/spring/spring-cloud-azure-service/src/main/java/com/azure/spring/service/implementation/cosmos/CosmosClientBuilderFactory.java#L124-L127

**Comment by saragluna** [comment]
> More on cosmos properties:
> 
> * `cosmos.gateway-connection.proxy`  and `spring.cloud.azure.cosmos.permissions` are complex types, property is defined, but nested properties are not defined. there is no metadata and there is no way to populate them via config. They should not be listed as properties considering this.
> * `cosmos.connection-mode` is null by default, meaning this code block does nothing and gateway or direct configs are ignored. it should follow SDK default (direct) or clearly communicate in docs that property is required (and log error if it's not provided)
>   https://github.com/Azure/azure-sdk-for-java/blob/3a1c944c376169588412248fb8667307390faa1e/sdk/spring/spring-cloud-azure-service/src/main/java/com/azure/spring/service/implementation/cosmos/CosmosClientBuilderFactory.java#L124-L127

https://github.com/Azure/azure-sdk-for-java/pull/27236 pr created

**Comment by saragluna** [comment]
All addressed, closing this issue now.
