### ISSUE TITLE
Eventhub - Getting this Unhandled exception while processing events in reactor, report this error. java.lang.IllegalStateException: no current delivery

### ISSUE THREAD

**Issue by rhyashu** [Azure/azure-sdk-for-java#26975]
**Query/Question**
When processing events from eventhub we are getting this error/warning: "[WARN] from com.azure.core.amqp.implementation.ReactorExecutor in reactor-executor-4 - connectionId[MF_1d3d70_1644216497974], message[Unhandled exception while processing events in reactor, report this error.]
java.lang.IllegalStateException: no current delivery". 
After that no messages were processed by those instances. Also none of the other instances took ownership of these partitions. But when we restarted the instances remaining messages were processed.

***Why is this not a Bug or a feature Request?***
Not sure as of now but maybe its a bug

**Setup (please complete the following information if applicable):**
- OS: Linux VM
 - Event hub Partition: 32
- Consumers: 32
- IDE: Running as a Spring Batch on VM
- Library/Libraries: [e.g. com.azure.spring:azure-messaging-eventhubs:5.10.0]
- Library/Libraries: [e.g. com.azure.spring:azure-spring-cloud-stream-binder-eventhubs:2.8.0]
- TU - 40 (Standard tier)
 
**Information Checklist**
**Logs**
[WARN] from com.azure.core.amqp.implementation.ReactorExecutor in reactor-executor-4 - connectionId[MF_1d3d70_1644216497974], message[Unhandled exception while processing events in reactor, report this error.]
java.lang.IllegalStateException: no current delivery
14:00:35.280 [ERROR] from com.azure.core.amqp.implementation.ReactorDispatcher in parallel-1 - ReactorDispatcher instance is closed.
14:00:35.280 [ERROR] from com.azure.core.amqp.implementation.ReactorDispatcher in boundedElastic-8 - ReactorDispatcher instance is closed.
14:00:35.283 [ERROR] from com.azure.core.amqp.implementation.ReactorDispatcher in parallel-1 - ReactorDispatcher instance is closed.
14:00:35.283 [WARN] from com.azure.core.amqp.implementation.ReactorConnection in parallel-1 - connectionId[MF_1d3d70_1644216497974] Error while scheduling closeConnection work. Manually disposing.
ReactorDispatcher instance is closed.
- [ *] Query Added
- [ *] Setup information Added

**Comment by joshfree** [comment]
@anuchandy could you please take a look?

**Comment by haolingdong-msft** [comment]
Please note version 5.10.0 of azure-messaging-eventhubs is not the latest.

This stack trace looks similar to an old issue (https://github.com/Azure/azure-sdk-for-java/issues/24575 ) reported for 5.10.1, we've fixed that in this pr (https://github.com/Azure/azure-sdk-for-java/pull/24141) in our later versions.

So please first try-unblock by upgrading to our latest version. If the issue persists, we need to investigate this further.

**Comment by rhyashu** [comment]
Hi @haolingdong-msft , Can we just update the azure-messaging-eventhubs version to 5.10.2 or we need to update azure-spring-cloud-stream-binder-eventhubs as well to 2.10.0?

**Comment by haolingdong-msft** [comment]
Hi @rhyashu 

Please note that the latest version of azure-messaging-eventhubs is 5.10.4. Please use version 5.10.4,

Also it is recommended to use the version of "azure-spring-cloud-stream-binder-eventhubs" which directly takes dependency on this specific version of "azure-messaging-eventhubs:5.10.4", which is "azure-spring-cloud-stream-binder-eventhubs:2.13.0". This means if you pick azure-spring-cloud-stream-binder-eventhubs:2.13.0, the 5.10.4 will be transitively pulled. So please use 
2.10.3 for 'azure-spring-cloud-stream-binder-eventhubs'.

If you include dependency azure-messaging-eventhubs explicitly, please upgrade to version 5.10.4.

**Comment by rhyashu** [comment]
Thanks, Will try upgrading and confirm back in case of any issues.

**Comment by ramya-rao-a** [comment]
@rhyashu If the issue persists after upgrading to the latest version, please add a comment with the text "/unresolve" to re-open this issue and continue the discussion. There is also an internal support ticket on this which we can be used for further discussion instead.
