### ISSUE TITLE
[BUG] AVS: AvsManager.clusters().list() returns an empty list

### ISSUE THREAD

**Issue by clouduser22** [Azure/azure-sdk-for-java#26989]
**Describe the bug**
I have created a private cloud which has the default cluster `Cluster-1`. It shows up on the portal but the Java api returns an empty list.

***Exception or Stack Trace***
There are no exceptions.

**To Reproduce**
Please see the code below.

***Code Snippet***
AzureProfile profile = new AzureProfile(null, subscriptionId, AzureEnvironment.AZURE);
TokenCredential credential = new ManagedIdentityCredentialBuilder().build();

AvsManager avsManager = AvsManager.authenticate(credential, profile);
PagedIterable<Cluster> avsClusters = avsManager.clusters().list(<privateCloud's resource group name>, <privateCloud's name>);
assert(avsClusters.stream().count() > 0);

This assert blows up as the count is 0.

**Expected behavior**
I expected that api to return the information on the primary cluster `Cluster-1`

**Screenshots**

**Setup (please complete the following information):**
azure-resourcemanager-avs:1.0.0-beta.3
azure-identity:1.4.3

**Additional context**
The snippet uses the managed identity credential with the contributor scope.

**Information Checklist**

**Comment by joshfree** [comment]
@weidongxu-microsoft could you please help route this?

**Comment by weidongxu-microsoft** [comment]
@clouduser22 
It would help if you can provide log via
```
AvsManager avsManager = AvsManager
        .configure().withLogOptions(new HttpLogOptions().setLogLevel(HttpLogDetailLevel.BODY_AND_HEADERS))
        .authenticate(credential, profile);
```

@XiaofeiCao please follow up.

**Comment by clouduser22** [comment]
@weidongxu-microsoft 
Here are the logs:
2022-02-11T04:47:58.405+0000 [.qtp401184791-25] --> GET https://management.azure.com/subscriptions/<subscriptionId>/resourceGroups/<resourceGroupName>/providers/Microsoft.AVS/privateClouds/<privateCloudName>/clusters?api-version=REDACTEDTry count: 1(empty body)--> END GET

@cee{"timestamp":"2022-02-11T04:47:58.452+0000", "priority":"INFO", "threadName":"reactor-http-nio-1", "codeLocation":"ClientLogger.java:222", "msg":"<-- 200 https://management.azure.com/subscriptions/<subscriptionId>/resourceGroups/<resourceGroupName>/providers/Microsoft.AVS/privateClouds/<privateCloudName>/clusters?api-version=REDACTED (46 ms, 12-byte body)Response body:{\\"value\\":[]}<-- END HTTP", "X-Datrium-Request-ID":"6124369973923158954", "pid":"22330", "host":"pkrvmt389m2qhnb.internal.cloudapp.net"}

I did try avsManager.clusters().get(resourceGroupName, privateCloudName, clusterName). It throws the ManagementException, saying resource not found.

If it helps, I did try to issue this through the REST gateway here and that returns the http response 200 with an empty list too:
https://docs.microsoft.com/en-us/rest/api/avs/clusters/list

**Comment by weidongxu-microsoft** [comment]
Loop-in service for help, as our test subscription is not allowed to create private cloud of AVS.

**Comment by XiaofeiCao** [comment]
The `clusters` api did return an empty list. Strangely, in portal, they actually call the <strong>same</strong> api and return the same empty list.

<strong>However</strong>, the reason we see the default `Cluster-1` in portal is because the response of another called api `privateClouds` which contains a `managementCluster` field which is the default cluster. I believe portal uses it to display. Service seems to exclude the default cluster from the `clusters` api but have it in `privateClouds` api.

`managementCluster` contained in `privateClouds` api response:
![image](https://user-images.githubusercontent.com/92354331/154231679-4dd05967-595e-4e02-b78b-44eade6c13bd.png)

That said, if you use the following code:
```java
PrivateCloud cloud = avsManager.privateClouds().getByResourceGroup(resourceGroup, cloudName);
ManagementCluster cluster = cloud.managementCluster();
```
You will actually see the default cluster as the `ManagementCluster`.

I'm not sure if it's a bug, need service to confirm this situation.

**Comment by XiaofeiCao** [comment]
@clouduser22 
For now you can use this code snippet:
```java
PrivateCloud cloud = avsManager.privateClouds().getByResourceGroup(resourceGroup, cloudName);
ManagementCluster cluster = cloud.managementCluster();
```
to get the default cluster. The portal actually does the same thing..



This one here probably gets the rest of the clusters.
```java
PagedIterable avsClusters = avsManager.clusters().list(<privateCloud's resource group name>, <privateCloud's name>);
```
