### ISSUE TITLE
Add http.user_agent attribute before startSpan so it's available for sampling

### ISSUE THREAD

**Issue by trask** [Azure/azure-sdk-for-java#26988]
We had an Application Insights user try to configure sampling based on `http.user_agent` but was unsuccessful since that attribute is not added prior to starting the span (https://github.com/microsoft/ApplicationInsights-Java/issues/2083#issuecomment-1034348844)

https://github.com/Azure/azure-sdk-for-java/blob/31b837387e2f9db000344494dd6100d15fa997dc/sdk/core/azure-core-tracing-opentelemetry/src/main/java/com/azure/core/tracing/opentelemetry/OpenTelemetryHttpPolicy.java#L124-L127

**Comment by lmolkova** [comment]
@trask should we mark user-agent as sampling-relevant in the HTTP semconv?

**Comment by lmolkova** [comment]
Closing this since [user_agent.original](https://github.com/open-telemetry/semantic-conventions/blob/main/docs/attributes-registry/user-agent.md) became opt-in and Azure SDKs no longer report it
