### ISSUE TITLE
Investigate how users can find the samples with specified spring-boot versions

### ISSUE THREAD

**Issue by backwind1233** [Azure/azure-sdk-for-java#26992]
**Context**
We have many samples in our sample repo, and we will update our sample code regularly, including dependencies and code.
It's not easy for users to find samples which are compatible with specific spring-boot version.

**Goal**
Provide an easy way for users to find samples which are compatible with their own spring-boot version choice.

**Comment by stliu** [comment]
closing it, no one ask for it
