### ISSUE TITLE
[FEATURE REQ] Make Spring Cloud Azure reference doc and MS Docs share the same content

### ISSUE THREAD

**Issue by saragluna** [Azure/azure-sdk-for-java#26996]
**Is your feature request related to a problem? Please describe.**
Now we have two places for our docs, Spring Cloud Azure reference doc (https://microsoft.github.io/spring-cloud-azure) and MS Docs (https://docs.microsoft.com/en-us/azure/developer/java/spring-framework/). The ideal case for us is to combine only a copy of content, that is reference doc + getting started guides, and let them render on two sites. 

**Describe the solution you'd like**
It's not easy for us to automate this process, but at first we can manually add the getting started guides as a chapter to the reference doc and create a PR to MS Docs to add the reference doc part. 

**Describe alternatives you've considered**
Try to automate this process.

**Additional context**
N/A

**Information Checklist**
Kindly make sure that you have added all the following information above and checkoff the required fields otherwise we will treat the issuer as an incomplete report
- [x] Description Added
- [x] Expected solution specified

**Comment by hui1110** [comment]
https://github.com/MicrosoftDocs/azure-dev-docs-pr/pull/2751

**Comment by hui1110** [comment]
https://github.com/microsoft/spring-cloud-azure/pull/858

**Comment by hui1110** [comment]
Closing this issue in favor of https://github.com/Azure/azure-sdk-for-java/issues/27570
