### ISSUE TITLE
Add missing AZURE_ env var support to core

### ISSUE THREAD

**Issue by joshfree** [Azure/azure-sdk-for-java#27004]
https://github.com/Azure/azure-sdk/blob/main/_includes/tables/environment_variables.md

This is a tracking work item to review the environment variables above, add support where missing, and follow up cross-language to ensure other Azure SDK languages also add matching capabilities.

Related [Support Environment Variable "AZURE_RESOURCE_GROUP" · Issue #14583 · Azure/azure-sdk-for-java (github.com)](https://github.com/Azure/azure-sdk-for-java/issues/14583)[](https://github.com/Azure/azure-sdk-for-java/issues/14583)

and [Support Environment Variable "AZURE_CLOUD" · Issue #14586 · Azure/azure-sdk-for-java (github.com)](https://github.com/Azure/azure-sdk-for-java/issues/14586)

**Comment by alzimmermsft** [comment]
Closing as this has been resolved.
