### ISSUE TITLE
How to give boolean value in @Container in spring data cosmos?

### ISSUE THREAD

**Issue by kumarsen26** [Azure/azure-sdk-for-java#27001]
In the below code, I am not able to set autoScale from the configuration property. I am getting errors as "expected boolean but the string is supplied".

```
@Container(containerName = "${dynamic.container.name}"
        , autoScale = "${dynamic.container.autoScale}", ru = "${dynamic.container.ru}")
public class FruitsContainer(){
.....
}
```
Kindly let me know how can I achieve this? This is needed, just to have different values in different environments.

**Comment by joshfree** [comment]
@backwind1233 could you please take a look?

**Comment by yiliuTo** [comment]
Hi @kushagraThapar could you help with @kumarsen26 for this issue? Thanks
