### ISSUE TITLE
Delete AADOBOOAuth2AuthorizedClientProvider after spring-boot 2.7.0 GA (2022-5-19)

### ISSUE THREAD

**Issue by chenrujun** [Azure/azure-sdk-for-java#27032]
### Context
`AADOBOOAuth2AuthorizedClientProvide`r implemented the same feature as `JwtBearerOAuth2AuthorizedClientProvider`.
`JwtBearerOAuth2AuthorizedClientProvider` is introduced since spring-security-auth2-client:5.5. 
spring-security:5.5 map to spring-boot:2.5.

When spring-cloud-azure-starter-active-directory does not need to compatible with spring-boot:2.4, `AADOBOOAuth2AuthorizedClientProvider` can be deleted, use `JwtBearerOAuth2AuthorizedClientProvider` directly.

spring-cloud-azure-starter-active-directory need to support 3 minor versions of Spring Boot. So, after Spring Boot 2.7.0 GA, it does not need to support 2.4.0 anymore, AADOBOOAuth2AuthorizedClientProvider can be deleted after Spring Boot 2.7.0 GA. Current milestone shows that Spring Boot 2.7.0 will GA on 2022-5-19 (Refs: [spring-boot/milestone](https://github.com/spring-projects/spring-boot/milestone/239)).

### Problem
`AADOBOOAuth2AuthorizedClientProvider` may need extra effort to maintain. 

### Solution
Delete `AADOBOOAuth2AuthorizedClientProvider`, use `JwtBearerOAuth2AuthorizedClientProvider` instead after Spring Boot 2.7.0 GA.

**Comment by moarychan** [comment]
This PR https://github.com/Azure/azure-sdk-for-java/pull/29471 will fix this issue.

**Comment by hui1110** [comment]
Now close it.
