### ISSUE TITLE
Delete AADJwtClaimValidator, use JwtClaimValidator instead.

### ISSUE THREAD

**Issue by chenrujun** [Azure/azure-sdk-for-java#27030]
As title, spring-security-oauth2-jose:5.3 already have `JwtClaimValidator`, we can delete our implementation.

| Spring boot version | Spring Security version |
| ---------------------  | ------------------------   |
| 2.2.0.RELEASE          | 5.2.0.RELEASE                 |
| 2.3.0.RELEASE          |  5.3.2.RELEASE                |
| 2.4.0                         | 5.4.1                               |
| 2.5.0                         | 5.5.0                               |

Spring Boot:2.2.x's Commercial Support ends on 2022-01-16.
So we do not need to support Spring Boot 2.2.x. We can use `JwtClaimValidator`.

**Comment by saragluna** [comment]
Closed in #27365.
