### ISSUE TITLE
Release azure-core-http-jdk-httpclient Library

### ISSUE THREAD

**Issue by alzimmermsft** [Azure/azure-sdk-for-java#27065]
Tracking issue to prepare and begin releasing the azure-core-jdk-httpclient.

**Comment by ohadbitt** [comment]
Is this going to be released soon?

**Comment by dennis-benzinger-hybris** [comment]
Is a test artifact already available somewhere?

**Comment by mssfang** [comment]
> Is a test artifact already available somewhere?

It is not released yet but it is the next HTTP client we are trying to release.  Currently, it can build locally and test.

**Comment by mssfang** [comment]
The first beta version of Azure core JDK HTTP client is release.

https://repo1.maven.org/maven2/com/azure/azure-core-http-jdk-httpclient/1.0.0-beta.1/
