### ISSUE TITLE
Java/Rest API call to list containerService orchestration does not return the same list as the Azure CLI

### ISSUE THREAD

**Issue by fyrnaga** [Azure/azure-sdk-for-java#27061]
**Describe the bug**
We want to get the list of azure AKS cluster supported version and we use the Java client to do the query.
```
 Azure client = factory.rootClient(callerContext);
      return client.kubernetesClusters().listKubernetesVersions(Region.fromName(region));
```
However, we get an old list compared to the CLI command
```
az aks get-versions --location eastus2 
```
I tried to do a direct Rest call and got the same result as the Java API
```
https://management.azure.com/subscriptions/<subscription id>/providers/Microsoft.ContainerService/locations/eastus2/orchestrators?api-version=2021-10-01&resource-type=Kubernetes
```

***Exception or Stack Trace***
No exception but the results are off

**To Reproduce**
Simple api call or azure cli command compare

***Code Snippet***
Add the code snippet that causes the issue.

**Expected behavior**
The list should match the one from the CLI.

**Screenshots**
**Rest call results**
<img width="1344" alt="image" src="https://user-images.githubusercontent.com/56133634/153676736-fc0fd480-7418-4964-9556-5213f152deb4.png">

**Azure cli results**
<img width="1407" alt="image" src="https://user-images.githubusercontent.com/56133634/153676754-384355c0-4949-43fd-9ca3-6a5d570f3aef.png">

**Setup (please complete the following information):**
 - OS:  iOS
 - IDE: IntelliJ
 - Library/Libraries: com.microsoft.azure:azure:1.41.1
 - Java version: 11
 - App Server/Environment: Spring Boot app
 - Frameworks: Spring Boot

**Additional context**

**Information Checklist**
Kindly make sure that you have added all the following information above and checkoff the required fields otherwise we will treat the issuer as an incomplete report
- [X] Bug Description Added
- [X] Repro Steps Added
- [X] Setup information Added

**Comment by weidongxu-microsoft** [comment]
@fyrnaga 
Please upgrade to azure-resourcemanager 2.11.0, and use `listOrchestrators(region, ContainerServiceResourceTypes.MANAGED_CLUSTERS)`

**Comment by fyrnaga** [comment]
Thanks. We will migrate to the new API version soon. This help me found how to resolve the situation for now. Thanks a lot.
