### ISSUE TITLE
API visibility - all non-public APIs should be in “implementation” package

### ISSUE THREAD

**Issue by saragluna** [Azure/azure-sdk-for-java#27113]
In the review process of Sprig Cloud Azure 4.0, several classes are considered non-public APIs or chosen to expose later. We agree to move them to the "implementation" package.
- The *ClientBuilderFactory classes in the spring-cloud-azure-service package.
- The *ConfigurationProperties classes in the spring-cloud-azure-autoconfigure package (we will change the visibility of these classes).

**Comment by saragluna** [comment]
For the *ConfigurationProperties classes, I've tried to make their visibility to package level, but it won't fit for most cases: 
- We use the AzureComosProperties in spring-cloud-azure-actuator for the Cosmos health indicator.
- We use StorageBlobProperties in Event Hubs autoconfiguration for checkpoint store.
- We use the EventHubsProperties in the resource manager configuration. 

So this solution won't work.

**Comment by lmolkova** [comment]
@saragluna thanks for the info! would it be possible to explore an implementation package option that allows keeping shared classes accessible for other packages?

**Comment by saragluna** [comment]
Hi @lmolkova, moving the *ConfigurationProperties classes to the `implementation` package will introduce another problem, for our `*Autoconfiguration` classes will reference these classes in their constructors.

**Comment by lmolkova** [comment]
> Hi @lmolkova, moving the *ConfigurationProperties classes to the `implementation` package will introduce another problem, for our `*Autoconfiguration` classes will reference these classes in their constructors.

It can still be done with constructor injection (constructor would stay package-private) or am I missing something?

**Comment by saragluna** [comment]
I will try to move them.

**Comment by saragluna** [comment]
@lmolkova the pr has been merged.

**Comment by saragluna** [comment]
Closing this issue now for all related classes have been moved to impl packages.
