### ISSUE TITLE
blockSize in ParallelTransferOptions does not take effective

### ISSUE THREAD

**Issue by chenyuvm** [Azure/azure-sdk-for-java#27143]
**Query/Question**
Setting blockSize in ParallelTransferOptions, then use BlobAsyncClient to upload files to blob storage, looks to me, this parameter does not take effective. Have tried to set different blockSize value, but 65535 bytes as blockSize are always to be used during uploading.

***Why is this not a Bug or a feature Request?***
A query to see whether my testing codes has problem.

**Setup (please complete the following information if applicable):**
 - OS: Linux
 - IDE: No
 - Library/Libraries: azure-storage-blob 12.13
 
Here are my sample codes and results:
BlobAsyncClient client = new BlobClientBuilder()
.endpoint(url)
.blobName("16.tar.gz") // 16.tar.gz size is about 16M
.buildAsyncClient();

long blockSize = 1 1024 1024L; // 1M
int maxConcurrency = 1;

ParallelTransferOptions parallelTransferOptions = new ParallelTransferOptions()
.setBlockSizeLong(blockSize)
.setMaxConcurrency(maxConcurrency)
.setProgressReceiver(bytesTransferred -> OnProgressReceived(bytesTransferred));

client.uploadFromFile(filePath, parallelTransferOptions, headers, null, AccessTier.HOT, null)
.doOnSuccess(success -> OnSuccess())
.doOnError(throwable -> OnError(throwable.getMessage()))
.subscribe();

private synchronized void OnProgressReceived(long bytesTransferred) {
count++;
bytes_transferred = bytesTransferred;
System.out.println(String.valueOf(count) + " " + new Date() + "uploaded: " + bytesTransferred);
}

The results:
1 Tue Feb 15 10:12:07 IRKT 2022uploaded: 65536
2 Tue Feb 15 10:12:07 IRKT 2022uploaded: 131072
3 Tue Feb 15 10:12:07 IRKT 2022uploaded: 196608
4 Tue Feb 15 10:12:07 IRKT 2022uploaded: 262144
.....
248 Tue Feb 15 10:12:52 IRKT 2022uploaded: 16252928
249 Tue Feb 15 10:12:52 IRKT 2022uploaded: 16318464
250 Tue Feb 15 10:12:52 IRKT 2022uploaded: 16384000
251 Tue Feb 15 10:12:52 IRKT 2022uploaded: 16391372

Any help is appreciated.

**Comment by alzimmermsft** [comment]
I'm closing out this issue now as I believe I have addressed the question. Please feel free to reactivate if I misunderstood or open a new issue if there is anything else. Thanks!

**Comment by chenyuvm** [comment]
@alzimmermsft Thanks for your information.

My main purpose is to decrease the frequency of progress reporter, as it report too much times when uploading one large file, and suppose it will impact other thread scheduling.

Looks DEFAULT_CHUNK_SIZE is one private and fixed value in FluxUtil.java, then no way to change it, right? 

If we need progress reporter during uploading, but would like to control its report frequency, could you please give me guide for that? Thanks a lot for your help.

**Comment by rickle-msft** [comment]
@chenyuvm Perhaps we can offer an option that is a long value like incrementSize and we report only in increments of that size rounded down. How does that sound?
