### ISSUE TITLE
[FEATURE REQ]spring-messaging-azure-eventhubs and spring-messaging-azure-servicebus module layout not consistent with the other package

### ISSUE THREAD

**Issue by jialigit** [Azure/azure-sdk-for-java#27148]
**Is your feature request related to a problem? Please describe.**
For the current messaging artifacts, the relationship is below:

    spring-messaging-azue
        - spring-messaging-azure-eventhus
        - spring-messaging-azure-servicebus

the package name prefix is below:

|artifact name                    |package prefix|
|----                            |----           |
|spring-messaging-azure          | com.azure.spring.messaging|
|spring-messaging-azure-eventhus | com.azure.spring.eventhubs|
|spring-messaging-azure-servicebus | com.azure.spring.servicebus|
 
to keep consistent with the naming pattern, notice the below changes:
|artifact name                    |package prefix|
|----                            |----           |
|spring-messaging-azure-eventhus | com.azure.spring.messaging.eventhubs|
|spring-messaging-azure-servicebus | com.azure.spring.messaging.servicebus|

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Information Checklist**
Kindly make sure that you have added all the following information above and checkoff the required fields otherwise we will treat the issuer as an incomplete report
- [ ] Description Added
- [ ] Expected solution specified

**Comment by jialigit** [comment]
leave it not changed for the moment.

**Comment by saragluna** [comment]
We have changed the package to match the module name, closing this issue now.
