### ISSUE TITLE
[BUG] com.azure.resourcemanager.mysql.Configurable and com.azure.resourcemanager.postgresql.Configurable should extend com.azure.resourcemanager.resources.fluentcore.arm.AzureConfigurable

### ISSUE THREAD

**Issue by luisCavalcantiDev** [Azure/azure-sdk-for-java#27156]
**Describe the bug**
com.azure.resourcemanager.mysql.Configurable and com.azure.resourcemanager.postgresql.Configurable should extend com.azure.resourcemanager.resources.fluentcore.arm.AzureConfigurable

**Exception or Stack Trace**
Not applicable

**Steps To Reproduce**

Using MySqlManager:
1 - Call configure() static method;
2 - It will return a com.azure.resourcemanager.mysql.MySqlManager.Configurable class that doesn't implement AzureConfigurable<Configurable> as most Configurables in the SDK

Same behavior using configure() static method from PostgreSqlManager

**Code Snippet**
MySqlManager
    .configure();
    
PostgreSqlManager.
    configure();

**Expected behavior**
configure() static method from com.azure.resourcemanager.mysql.MySqlManager / com.azure.resourcemanager.postgresql.PostgreSqlManager should return a Configurable fluent interface implementation that extends interface AzureConfigurable<Configurable>

**Screenshots**
Not applicable.

Setup (please complete the following information):

OS: Linux
IDE: Apache NetBeans 12.5
Library/Libraries: azure-resourcemanager-appservice: 2.12.0
Java version: 8
Frameworks: Play! Framework 1.5
Additional context

**Comment by joshfree** [comment]
@weidongxu-microsoft could you please help route this github issue from @luisCavalcantiDev?

**Comment by luisCavalcantiDev** [comment]
Thank you for your reply @weidongxu-microsoft 

But it's still quite confusing for me due package names (azure-resourcemanager-mysql it seems related to resourcemanager-resources and not a standalone lib).

**Comment by weidongxu-microsoft** [comment]
@luisCavalcantiDev There are some difference between the packages in azure-resourcemanager https://github.com/Azure/azure-sdk-for-java/blob/main/sdk/resourcemanager/azure-resourcemanager/pom.xml#L67 and the packages not in it.

The difference in superclass could sometimes result in duplicate code when configuring several `Manager`s from different packages. We will see if the new trait feature would help unify the interface https://github.com/Azure/azure-sdk-for-java/tree/main/sdk/core/azure-core/src/main/java/com/azure/core/client/traits

PS: You might want to share a single `HttpClient` across `Manager`s.

**Comment by luisCavalcantiDev** [comment]
> @luisCavalcantiDev There are some difference between the packages in azure-resourcemanager https://github.com/Azure/azure-sdk-for-java/blob/main/sdk/resourcemanager/azure-resourcemanager/pom.xml#L67 and the packages not in it.
> 
> The difference in superclass could sometimes result in duplicate code when configuring several `Manager`s from different packages. We will see if the new trait feature would help unify the interface https://github.com/Azure/azure-sdk-for-java/tree/main/sdk/core/azure-core/src/main/java/com/azure/core/client/traits
> 
> PS: You might want to share a single `HttpClient` across `Manager`s.

I see @weidongxu-microsoft, thanks for clarification.
Regards
