### ISSUE TITLE
Wrong encryption status returned for encrypted VM's data disks

### ISSUE THREAD

**Issue by ChuGer** [Azure/azure-sdk-for-java#2716]
https://github.com/Azure/azure-sdk-for-java/blob/47fc8ddea76280c198a2b9697e8f93b0c5f18e65/archive/azure-mgmt-compute/src/main/java/com/microsoft/azure/management/compute/implementation/WindowsVolumeEncryptionMonitorImpl.java#L98

Please compare implementation with .Net implementation of the same method

https://github.com/Azure/azure-libraries-for-net/blob/6c9c6cf1a4d1c69b542866c1944c1e105fe201e5/src/ResourceManagement/Compute/WindowsVolumeEncryptionMonitorImpl.cs#L135

When disk encryption is enabled `encryptionExtension.settings()` always not null and not empty.

**Comment by ChuGer** [comment]
Please review a one-symbol Pull Request with fix for related issue: https://github.com/Azure/azure-sdk-for-java/pull/2731

**Comment by praries880** [comment]
@anuchandy  Can you kindly look at this? This seems to be an issue with the auto-generator...

**Comment by praries880** [comment]
Issue moved to [Azure/azure-libraries-for-java #712](https://github.com/Azure/azure-libraries-for-java/issues/712) via [**ZenHub**](https://www.zenhub.com/)
