### ISSUE TITLE
Add more log to help customer debug azure-spring-boot-starter-keyvault-secrets

### ISSUE THREAD

**Issue by chenrujun** [Azure/azure-sdk-for-java#27167]
- [x] Add more log.

For example: when customer input erroneous uri, there should be some log to tell customer about wrong url.

Related links:
1. https://stackoverflow.com/questions/71034509/azure-spring-boot-starter-keyvault-secrets-doesnt-work-at-all
2. https://github.com/Azure/azure-sdk-for-java/blob/spring-cloud-azure-autoconfigure_4.0.0-beta.3/sdk/spring/spring-cloud-azure-autoconfigure/src/main/java/com/azure/spring/cloud/autoconfigure/keyvault/env/KeyVaultEnvironmentPostProcessor.java

 - [ ] #27844

**Comment by saragluna** [comment]
Closing this issue now, will use https://github.com/Azure/azure-sdk-for-java/issues/27844 to track another issue.
