### ISSUE TITLE
[FEATURE REQ] Azure Service Bus Admin Client Shared Key Authenication

### ISSUE THREAD

**Issue by james-novino** [Azure/azure-sdk-for-java#27209]
**Is your feature request related to a problem? Please describe.**

Currently, the `ServiceBusAdministrationClientBuilder` only has support for TokenCredentials which are commonly used when using the Microsoft Identity authentication, however, many systems and scripts need access to this Client using the connection string & shared access secrets. 

**Describe the solution you'd like**
The proposal would be to add the following override to the `ServiceBusAdministrationClientBuilder`. 

```
public ServiceBusAdministrationClientBuilder credential(String fullyQualifiedNamespace, AzureNamedKeyCredential credential) {
        this.fullyQualifiedNamespace = Objects.requireNonNull(fullyQualifiedNamespace,
            "'fullyQualifiedNamespace' cannot be null.");
        Objects.requireNonNull(credential, "'credential' cannot be null.");
        if (CoreUtils.isNullOrEmpty(fullyQualifiedNamespace)) {
            throw logger.logExceptionAsError(
                new IllegalArgumentException("'fullyQualifiedNamespace' cannot be an empty string."));
        }

        this.credentials = new ServiceBusSharedKeyCredential(credential.getAzureNamedKey().getName(),
            credential.getAzureNamedKey().getKey(), ServiceBusConstants.TOKEN_VALIDITY);

        return this;
    }
```

**Describe alternatives you've considered**
No clear path is forward other than using Azure Identity auth across all scripts and systems. 

**Information Checklist**
Kindly make sure that you have added all the following information above and check off the required fields otherwise we will treat the issuer as an incomplete report
- [x] Description Added
- [x] Expected solution specified

**Comment by joshfree** [comment]
Thanks for filing this API request, @james-novino.   

/cc @Azure/azsdk-sb-java  as fyi

**Comment by anuchandy** [comment]
The admin client indeed has a builder option that takes [connection-string](https://github.com/Azure/azure-sdk-for-java/blob/cd6c2a765da667dc238e889faf8fd0dbcac1da31/sdk/servicebus/azure-messaging-servicebus/src/main/java/com/azure/messaging/servicebus/administration/ServiceBusAdministrationClientBuilder.java#L263). Closing this ticket, but please feel free to reopen with additional info if this is not the API you're looking for.
