### ISSUE TITLE
[BUG] can't download azure-data-tables from maven

### ISSUE THREAD

**Issue by ulugbekrozimboyev** [Azure/azure-sdk-for-java#27202]
I want to use azure-data-tables on my spring project. I added dependance to my maven file. 
```
<dependency>
  <groupId>com.azure</groupId>
  <artifactId>azure-data-tables</artifactId>
  <version>12.2.0</version>
</dependency>

```

But maven could not download the dependence. I have tried with older version but got the same result. Than I found [your maven page](https://mvnrepository.com/artifact/com.azure/azure-data-tables) and I have notice that all releases never downloaded 
<img width="783" alt="Screen Shot 2022-02-18 at 19 54 29" src="https://user-images.githubusercontent.com/6926653/154708899-8fbf7b48-4256-4ee6-b893-8461e4985efb.png">

I assume here is some problem to download lib.

**Comment by joshfree** [comment]
@vcolin7 could you please follow up?

**Comment by joshfree** [comment]
@ulugbekrozimboyev please note that the '0' in the column above is the reference count by other packages on maven central, and not the download count.  Could you provide more details on the error that you're seeing?

**Comment by vcolin7** [comment]
Hi @ulugbekrozimboyev, as Josh said, the '0' count is an indicator of how many other projects in Maven Central are using a package. I was just able to download the library's version `12.2.0` by adding it as a dependency to a sample project making sure it was not present locally beforehand. Maybe it's a problem with your current setup. Would you mind sharing more details or an error message in case you are seeing one?

**Comment by ulugbekrozimboyev** [comment]
Hi @vcolin7 and @joshfree. It started to work. I don't know how the error was occurred maybe at that time network/proxy problems was made that. 
I am apologize for if I made you disquiet.

**Comment by jairmyree** [comment]
@vcolin7 If there's nothing further, I'll be closing this issue.
