### ISSUE TITLE
Query/Question: Streaming web app slot deployment logs

### ISSUE THREAD

**Issue by ivan-83** [Azure/azure-sdk-for-java#27221]
**Query/Question**
We are getting very often `java.net.SocketTimeoutException: timeout` exception when calling the following API for streaming web app slot deployment logs, 
https://github.com/Azure/azure-libraries-for-java/blob/f7875032154af14671484548d4f4c223c7d7e079/azure-mgmt-appservice/src/main/java/com/microsoft/azure/management/appservice/WebAppBase.java#L441

Is there any other way for streaming web app slot deployment logs by using Azure SDK for java?  Any advice on how to consume this streaming API. Thanks in advance!

**Comment by joshfree** [comment]
Thanks for filing this question, @ivan-83.  Someone from the Management Plane SDK team will follow up with you shortly.

**Comment by weidongxu-microsoft** [comment]
@ivan-83 
Please consider using the new lib here https://aka.ms/azsdk/java/mgmt

For streaming, you might want to increase the READ timeout of the HttpClient, as streaming from webapp can have silence upto 2min. E.g.
```java
HttpClient.createDefault(new HttpClientOptions().setReadTimeout(Duration.ofMinutes(3)));
```

**Comment by ivan-83** [comment]
Thanks, @weidongxu-microsoft for your response.  Quick question, are new libs/lib have full support for Azure App Services, VMSS, ARM, Bluprint templates, Resources...? I mean are libs/lib fully backward compatible or it is still in progress?
And, this is a migration guide to follow up, right? https://github.com/Azure/azure-sdk-for-java/blob/main/sdk/resourcemanager/docs/MIGRATION_GUIDE.md

**Comment by weidongxu-microsoft** [comment]
@ivan-83

I am not sure about "Bluprint templates", I can find it for you if you have package name. Others is under "azure-resourcemanager".

Yes, migration guide is https://github.com/Azure/azure-sdk-for-java/blob/main/sdk/resourcemanager/docs/MIGRATION_GUIDE.md
Code is almost same, exception namespace change.
Other difference would be authentication, and some error handling.

**Comment by ivan-83** [comment]
Thank you @weidongxu-microsoft for confirmation. I've checked for Azure Blueprints templates but it seems APIs are not implemented/supported by java Azure SDK lib https://docs.microsoft.com/en-us/azure/governance/blueprints/

**Comment by weidongxu-microsoft** [comment]
@ivan-83

I see. I think it does not have any Java SDK, old or new.
The spec should be here:
https://github.com/Azure/azure-rest-api-specs/tree/main/specification/blueprint/resource-manager

If you do need a Java SDK on blueprint, would you open another issue for it? I would need to contact service to confirm the api-version and get their blessing for a Java SDK.

**Comment by ivan-83** [comment]
Thank you @weidongxu-microsoft based on all of this we can safely do the migration on azure-resourcemanager-resources SDK. We will check for Azure Blueprint. You can close the ticket.

**Comment by weidongxu-microsoft** [comment]
@ivan-83

I've marked the issue as addressed. If you still see problem with streaming logs, feel free to update/reopen the issue.
