### ISSUE TITLE
[BUG] Some extra empty strings are written to the end of the file when writing bytes into fileClient.getFileOutputStream()

### ISSUE THREAD

**Issue by moarychan** [Azure/azure-sdk-for-java#27230]
**Describe the bug**
Some extra empty strings are written to the end of the file when using the output stream of the file client.

***Exception or Stack Trace***
No exception, but these empty strings can cause other problems.

**To Reproduce**
Run the demo code, the new file will be created in Storage File Share, then download the file *demo.txt*, you will find the extra empty strings.

***Code Snippet***
```java
public class Demo {
    public static void main(String[] args) {
        ShareServiceClient serviceClient = new ShareServiceClientBuilder()
            .credential(new StorageSharedKeyCredential("xxxcstorage", "xxx"))
            .endpoint("https://xxxcstorage.file.core.windows.net/")
            .buildClient();
        ShareClient shareClient = serviceClient.getShareClient("demo");
        ShareFileClient fileClient = shareClient.getFileClient("demo.txt");

        if (!shareClient.exists()) {
            shareClient.create();
        }

        if (!fileClient.exists()) {
            fileClient.create(1024);
        }

        StorageFileOutputStream fileOutputStream = fileClient.getFileOutputStream();

        String data = "hello world";
        fileOutputStream.write(data.getBytes());
    }
}
```

**Expected behavior**
The content of the file downloaded from the Storage File Share in the Azure Portal is fine, there are no extra empty strings.

**Screenshots**
![image](https://user-images.githubusercontent.com/19926623/155072995-b012d53b-dea6-42df-9fb0-27a36d9d1148.png)

**Setup (please complete the following information):**
 - OS: [e.g. iOS] Windows
 - IDE: [e.g. IntelliJ] Intellij
 - Library/Libraries: [e.g. com.azure:azure-core:1.16.0 (groupId:artifactId:version)] com.azure:azure-storage-file-share:12.11.3
 - Java version: [e.g. 8]  11

**Information Checklist**
Kindly make sure that you have added all the following information above and checkoff the required fields otherwise we will treat the issuer as an incomplete report
- [x] Bug Description Added
- [x] Repro Steps Added
- [x] Setup information Added

**Comment by joshfree** [comment]
Thanks for filing this github issue, @moarychan.  Someone from the storage team will follow up with you shortly.

/cc @kasobol-msft

**Comment by rickle-msft** [comment]
@moarychan Thank you for opening this issue. You mention that downloading from the portal is fine, so presumably it is not the upload that has an issue. Can you please share how you are downloading the file?

**Comment by moarychan** [comment]
Hi @rickle-msft , the whole string length is 1024, I got the root cause, thanks, the API is fine, my usage is wrong, thanks.
