### ISSUE TITLE
[FEATURE REQ] Documentation update for Certificate Policy

### ISSUE THREAD

**Issue by yuruhimesama** [Azure/azure-sdk-for-java#27243]
**Is your feature request related to a problem? Please describe.**
Reserved values for Certificate Policy to set "non-integrated CA" mode not documented. 

https://azuresdkdocs.blob.core.windows.net/$web/java/azure-security-keyvault-certificates/4.2.7/com/azure/security/keyvault/certificates/models/CertificatePolicy.html

**Describe the solution you'd like**
Updated documentation at minimum; improved constructor using an `enum` of reserved values would be better

**Describe alternatives you've considered**
Checked the REST API docs for reserved values

**Additional context**
n.a

**Information Checklist**
Kindly make sure that you have added all the following information above and checkoff the required fields otherwise we will treat the issuer as an incomplete report
- [x] Description Added
- [x] Expected solution specified

**Comment by joshfree** [comment]
@vcolin7 could you please follow up on @yuruhimesama's issue?

**Comment by vcolin7** [comment]
Hi @yuruhimesama, thank you very much for this feedback.

As a note to anyone that might come across this GitHub issue when learning about how to create a certificate with a non-integrated CA, this can be achieved by doing the following:

```java
CertificateClient certificateClient = new CertificateClientBuilder()
    .vaultUrl("<your-key-vault-url>")
    .credential(new DefaultAzureCredentialBuilder().build())
    .buildClient();
CertificatePolicy myCertificatePolicy = new CertificatePolicy(WellKnownIssuerNames.UNKNOWN, "CN=myDomain.com");
certificateClient.beginCreateCertificate("myCertificateName", myCertificatePolicy);
```

This will require that you merge this newly created certificate with another certificate or certificate chain leading to the non-integrated CA by using the following code:

```java
// Add your certificate or certificate chain to this list.
List<byte[]> x509CertificatesToMerge = new ArrayList<>();
// The first parameter is the name of the certificate created above.
MergeCertificateOptions config = new MergeCertificateOptions("myCertificateName", x509CertificatesToMerge);
KeyVaultCertificate mergedCertificate = certificateClient.mergeCertificate(config);
```

I do agree that we can improve the documentation around this scenario though as, for example, it is not clear that any certificate created on the Azure Portal with a "Type of Certificate Authority (CA)" set to "non-integrated CA" would end up having its issuer set as "Unknown" until merged with another certificate. Also, it's not clear in the documentation for `CertificatePolicy` that you can use the values in `WellKnownIssuerNames` as the `issuerName` in the constructor of the former.

I will bring this up with the team and come back later in the week to provide an update.

**Comment by yuruhimesama** [comment]
@vcolin7 

Bang on, thanks for this -- exactly what I was looking for.
