### ISSUE TITLE
[QUERY] Why not use primary connection string?

### ISSUE THREAD

**Issue by brian-duffy** [Azure/azure-sdk-for-java#27240]
**Query/Question**
I would like to use this SDK to connect to Cosmos, but why go against the primary used method of connecting to a Mongo/Cosmos database with a primary connection string (which already includes, host, port, key etc) and force the user to split it up themselves, or map new fields into existing microservices to prevent us splitting it?

***Why is this not a Bug or a feature Request?***
I'm guessing this has been done for a reason, but can't see why you would do this.
 
 **Information Checklist**
 Kindly make sure that you have added all the following information above and checkoff the required fields otherwise we will treat the issuer as an incomplete report
- [x] Query Added
- [x] Setup information Added

**Comment by kushagraThapar** [comment]
@brian-duffy  - I guess the main reason is to support key rotation using Azure key vault, or any other service. I don't think there is any other reason to do this other than above.
