### ISSUE TITLE
Avoid 410 during cache refresh

### ISSUE THREAD

**Issue by kushagraThapar** [Azure/azure-sdk-for-java#27245]
Issue:
During address cache refresh 25% or request will go to the bad replica, and which causes unnecessary latency and retries.

Explain:
Request 1: Hits a bad replica and triggers a background refresh. The gateway is slow and takes 30 seconds to respond. Gateway can be slower or faster.
Request 2: Starts after request 1 started the background refresh but before it got a response. It gets the stale address cache results. It has a 25% chance of randomly picking the bad replica address. The SDK will catch and automatically retry on the failure.

Solution:
Flag the uri that failed with an unhealthy flag. Future requests then can always put the unhealthy URIs at the end of the list. Once the new cache entry is returned the old stale cache value with the unhealthy flag is replaced. This unhealthy flag has a timeout to avoid the SDK getting stuck in a scenario where it is overloading the other replicas.

Port this to Java v4 SDK - https://msdata.visualstudio.com/CosmosDB/_git/CosmosDB/pullrequest/738372

**Comment by xinlian12** [comment]
PR has merged
