### ISSUE TITLE
Suppress nulls in Cosmos DB createItem

### ISSUE THREAD

**Issue by sconggit** [Azure/azure-sdk-for-java#27269]
**Is your feature request related to a problem? Please describe.**
We need the Java SDK to provide the option to suppress the fields with null values. We run into the situation when over hundred of fields could be on the item but only a few have values for a specific record. It's not desired to save an item in Cosmos DB with numerous nulls.  Saving the item as a JSON string isn't a good option considering indexing to fields inside the JSON string.

**Describe the solution you'd like**
Add a serialization option to CosmosClient and CosmosAsyncClient similar to what it's done in the .NET C# SDK? See https://stackoverflow.com/questions/25903302/removing-properties-with-null-values for reference.

**Describe alternatives you've considered**
@kushagraThapar suggested using the Jackson annotation @JsonInclude(JsonInclude.Include.NON_NULL), but that requires to convert and save the item as string.  In many cases, store the entire record as a JSON string isn't a good option.

**Additional context**
Consider this is a follow-up to the following issues.  We desperately need this feature. 
https://github.com/Azure/azure-sdk-for-java/issues/13307
https://github.com/Azure/azure-sdk-for-java/issues/27239

**Information Checklist**
Kindly make sure that you have added all the following information above and checkoff the required fields otherwise we will treat the issuer as an incomplete report
- [ ] Description Added
- [ ] Expected solution specified

**Comment by kushagraThapar** [comment]
FYI - Current way to do this -> 

You can ignore null values using this annotation from jackson -
`@JsonInclude(JsonInclude.Include.NON_NULL)` - more details here - https://www.baeldung.com/jackson-ignore-null-fields

Also, there should be no performance impact when using Java Object when sending the item for createItem API call. Since Java SDK converts the JsonObjects into String before storing them to Cosmos DB. In Cosmos DB, documents are stored as Json strings, so there is no performance impact as well.

**Comment by sconggit** [comment]
@kushagraThapar - yes. The pluggable serializer is what I'm looking for. I know we could save JsonObjects as Json strings in Cosmos DB but that seems not a good practice.  It may not have performance impact on creatItem, but what if we read/search by a field? It should cost performance on read and search.

**Comment by kushagraThapar** [comment]
@sconggit - No performance impact on read / search as well, as those are done by id and partition key - which is effectively point read. 

So literally there is no performance impact for any of these operations at all. 
Pluggable serializer has its own other benefits, but for now, this alternate is the best solution I would suggest. 

Will keep you posted in case if we make any progress on pluggable serializer.

**Comment by sconggit** [comment]
@kushagraThapar Thanks. We have indexing on one of the fields that isn't id or the partition key.

**Comment by kushagraThapar** [comment]
Closing this as we don't plan to provide pluggable serializer.
