### ISSUE TITLE
mgmt, upgrade SQL to 2021-11

### ISSUE THREAD

**Issue by weidongxu-microsoft** [Azure/azure-sdk-for-java#27275]
And to do so without breaking changes (well, likely not possible, hence try keep it small).

**Comment by weidongxu-microsoft** [comment]
https://github.com/Azure/azure-rest-api-specs/tree/main/specification/sql/resource-manager#tag-package-2021-11

**Comment by XiaofeiCao** [comment]
2.23.0 released with sql api-version `2021-11`.
