### ISSUE TITLE
[BUG] UserAgent in azure-spring-data-cosmos will be overrided by spring-cloud-azure-autoconfigure

### ISSUE THREAD

**Issue by backwind1233** [Azure/azure-sdk-for-java#27286]
**Describe the bug**
The method [getUserAgentSuffix()](https://github.com/Azure/azure-sdk-for-java/blob/1b35a288306c5ab5f959802c8b2b243a7383a64c/sdk/cosmos/azure-spring-data-cosmos/src/main/java/com/azure/spring/data/cosmos/CosmosFactory.java#L28) will return wrong value if the classpath has more than one `META-INF/project.properties`

***Exception or Stack Trace***
No.

**To Reproduce**
Include dependency 
```
<dependency>
  <groupId>com.azure.spring</groupId>
  <artifactId>spring-cloud-azure-starter-data-cosmos</artifactId>
  <version>4.0.0-beta.3</version>
</dependency>
```
This is a mini [sample](https://github.com/backwind1233/issue-sample-27286) to reproduce this issue.

***Code Snippet***
This is a mini [sample](https://github.com/backwind1233/issue-sample-27286) to reproduce this issue.

**Expected behavior**
Expected behavior
userAgentSuffix='az-sd-cos/3.17.0az-sp-cos/4.0.0-beta.3'
it's better to be userAgentSuffix='az-sd-cos/3.17.0  az-sp-cos/4.0.0-beta.3'

but the result is userAgentSuffix='az-sd-cos/4.0.0-beta.3az-sp-cos/4.0.0-beta.3'
<img width="587" alt="image" src="https://user-images.githubusercontent.com/4465723/155503475-628e29e6-a1fa-46a7-b73b-37fbfff2129d.png">

**Screenshots**

The reason is 
**Setup (please complete the following information):**
 - OS: [e.g. Mac]
 - IDE: [e.g. IntelliJ]
 - Library/Libraries: [ azure-spring-data-cosmos:3.17]

**Additional context**

**Information Checklist**
Kindly make sure that you have added all the following information above and checkoff the required fields otherwise we will treat the issuer as an incomplete report
- [x] Bug Description Added
- [x] Repro Steps Added
- [x] Setup information Added

**Comment by backwind1233** [comment]
Hi @kushagraThapar , can you help look into this issue?

**Comment by kushagraThapar** [comment]
@backwind1233 - can you please review this PR ?
https://github.com/Azure/azure-sdk-for-java/pull/27311
