### ISSUE TITLE
Support latest spring-boot version: 2.5.10 and 2.6.4

### ISSUE THREAD

**Issue by chenrujun** [Azure/azure-sdk-for-java#27304]
The following content is copied from https://github.com/Azure/azure-sdk-for-java/wiki/Spring-Cloud-Azure-tasks-for-a-new-Spring-Boot-release

- Before azure-sdk-for-java in band release
  - [ ] Read spring boot release notes. Sample: [Spring-Boot-2.6-Release-Notes](https://github.com/spring-projects/spring-boot/wiki/Spring-Boot-2.6-Release-Notes).
  - [ ] Upgrade external dependencies' version according to spring-boot-dependencies and spring-cloud-dependencies. Refer to [related readme](https://github.com/Azure/azure-sdk-for-java/blob/f958712452a9bbc1aedd598181278d63ab40e06a/sdk/spring/scripts/README.md)

- After azure-sdk-for-java in band release.
  - [ ] Update [azure-spring-boot-samples](https://github.com/Azure-Samples/azure-spring-boot-samples)
  - [ ] Update [CHANGELOG](https://github.com/Azure/azure-sdk-for-java/tree/main/sdk/spring).
  - [ ] Update [Reference doc](https://github.com/microsoft/spring-cloud-azure/tree/docs/docs/src/main/asciidoc).
  - [ ] Update [MS docs](https://docs.microsoft.com/en-us/azure/developer/java/spring-framework/).
  - [ ] Update related wiki pages: [Spring-Support-Multiple-Versions](https://github.com/Azure/azure-sdk-for-java/wiki/Spring-Support-Multiple-Versions), [Spring-Versions-Mapping](https://github.com/Azure/azure-sdk-for-java/wiki/Spring-Versions-Mapping).

**Comment by Netyyyy** [comment]
Closing this issue in favor of https://github.com/Azure/azure-sdk-for-java/issues/27863
