### ISSUE TITLE
Azure Java SDK - ChainedTokenCredential not switching to next available TokenCredential in case of 403 forbidden error

### ISSUE THREAD

**Issue by MulakaluriKartheek** [Azure/azure-sdk-for-java#27308]
**Describe the bug**
Even though ChainedTokenCredential enables multiple TokenCredential implementations to be tried in order until one of the getToken methods returns an access token, but it can handle only authentication error but not authorization i.e., it will throw 403 error and will not automatically switch to other available authentication if RBAC permissions are not defined. ChainedTokenCredential is not switching from System Assigned Managed Identity to User Assigned Managed Identity if System Assigned Managed Identity don't have RBAC permissions

***Exception or Stack Trace***
[2022-02-25T11:50:18.018Z] [com.azure.cosmos.implementation.query.DocumentProducer] [cosmos-rntbd-nio-3-2] [199] [ERROR] [] [] Unexpected failure
com.azure.cosmos.implementation.ForbiddenException: {"innerErrorMessage":"[\"Request is blocked because principal [******************************] does not have the required RBAC permissions to perform action [Microsoft.DocumentDB/databaseAccounts/sqlDatabases/containers/executeQuery] with OperationType [15] and ResourceType [2] on resource [dbs/DB/colls/leases]. Learn more: https://aka.ms/cosmos-native-rbac\"]","cosmosDiagnostics":{"userAgent":"azsdk-java-cosmos/4.17.0 Linux/5.4.0-1062-azure JRE/11.0.5","requestLatencyInMs":1,"requestStartTimeUTC":"2022-02-25T11:50:18.835348Z","requestEndTimeUTC":"2022-02-25T11:50:18.836635Z","responseStatisticsList":[{"storeResult":{"storePhysicalAddress":"rntbd://cdb-ms-prod-centralus1-fd4.documents.azure.com:14101/apps/dbbeead3-9caa-45e6-8ed7-0af7ac3170f4/services/82a44b12-334c-4fa4-9a86-59ae13ac41ce/partitions/2f904776-c8ff-444d-b5cb-e4ab2945b675/replicas/132803609217458999p/","lsn":11989043,"globalCommittedLsn":11989043,"partitionKeyRangeId":"","isValid":true,"statusCode":403,"subStatusCode":5302,"isGone":false,"isNotFound":false,"isInvalidPartition":false,"isThroughputControlRequestRateTooLarge":false,"requestCharge":0.0,"itemLSN":-1,"sessionToken":"-1#11989043","backendLatencyInMs":0.537,"exception":"[\"Request is blocked because principal [6cffda75-7cfa-4e47-8488-e76c7bcf92fc] does not have the required RBAC permissions to perform action [Microsoft.DocumentDB/databaseAccounts/sqlDatabases/containers/executeQuery] with OperationType [15] and ResourceType [2] on resource [dbs/DB/colls/leases]. Learn more: https://aka.ms/cosmos-native-rbac\"]","transportRequestTimeline":[{"eventName":"created","startTimeUTC":"2022-02-25T11:50:18.835414Z","durationInMicroSec":2},{"eventName":"queued","startTimeUTC":"2022-02-25T11:50:18.835416Z","durationInMicroSec":0},{"eventName":"channelAcquisitionStarted","startTimeUTC":"2022-02-25T11:50:18.835416Z","durationInMicroSec":52},{"eventName":"pipelined","startTimeUTC":"2022-02-25T11:50:18.835468Z","durationInMicroSec":85},{"eventName":"transitTime","startTimeUTC":"2022-02-25T11:50:18.835553Z","durationInMicroSec":1005},{"eventName":"received","startTimeUTC":"2022-02-25T11:50:18.836558Z","durationInMicroSec":50},{"eventName":"completed","startTimeUTC":"2022-02-25T11:50:18.836608Z","durationInMicroSec":23}],"rntbdRequestLengthInBytes":2098,"rntbdResponseLengthInBytes":571,"requestPayloadLengthInBytes":222,"responsePayloadLengthInBytes":null,"channelTaskQueueSize":0,"pendingRequestsCount":0,"serviceEndpointStatistics":{"availableChannels":1,"acquiredChannels":0,"executorTaskQueueSize":0,"inflightRequests":1,"lastSuccessfulRequestTime":"2022-02-25T11:48:19.938Z","lastRequestTime":"2022-02-25T11:50:18.810Z","createdTime":"2022-02-25T11:46:37.623655Z","isClosed":false}},"requestResponseTimeUTC":"2022-02-25T11:50:18.836635Z","requestResourceType":"Document","requestOperationType":"Query"}],"supplementalResponseStatisticsList":[],"addressResolutionStatistics":{},"regionsContacted":["https://**********-centralus.documents.azure.com:443/"],"retryContext":{"statusAndSubStatusCodes":null,"retryCount":0,"retryLatency":0},"metadataDiagnosticsContext":{"metadataDiagnosticList":null},"serializationDiagnosticsContext":{"serializationDiagnosticsList":null},"gatewayStatistics":null,"systemInformation":{"usedMemory":"118660 KB","availableMemory":"30288124 KB","systemCpuLoad":"(2022-02-25T11:49:53.463058Z 3.6%), (2022-02-25T11:49:58.463068Z 3.0%), (2022-02-25T11:50:03.463029Z 3.8%), (2022-02-25T11:50:08.463059Z 2.8%), (2022-02-25T11:50:13.463074Z 3.4%), (2022-02-25T11:50:18.463054Z 3.0%)","availableProcessors":1},"clientCfgs":{"id":-1,"connectionMode":"DIRECT","numberOfClients":2,"connCfg":{"rntbd":"(cto:PT5S, rto:PT5S, icto:PT0S, ieto:PT1H, mcpe:130, mrpc:30, cer:false)","gw":"(cps:1000, rto:PT5S, icto:null, p:false)","other":"(ed: true, cs: false)"},"consistencyCfg":"(consistency: Eventual, mm: true, prgns: [centralus])"}}}

**To Reproduce**

***Code Snippet***
`DefaultAzureCredential defaultAzureCredential = new DefaultAzureCredentialBuilder().build();
ManagedIdentityCredential userAssignedmanagedIdentityCredential = new ManagedIdentityCredentialBuilder().clientId("<USER ASSIGNED MANAGED IDENTITY CLIENT ID>").build();

ChainedTokenCredentialBuilder builder = new ChainedTokenCredentialBuilder();
        builder.addFirst(defaultAzureCredential);
        builder.addLast(userAssignedmanagedIdentityCredential);

ConnectionPolicy defaultPolicy = ConnectionPolicy.getDefaultPolicy();
defaultPolicy.setUserAgentSuffix(applicationName);
defaultPolicy.setPreferredRegions(Arrays.asList("Central US"));
AsyncDocumentClient asyncDocumentClient = new AsyncDocumentClient.Builder().withServiceEndpoint("<Cosmos DB URL>").withTokenCredential(builder.build()).withConnectionPolicy(defaultPolicy) .withConsistencyLevel(ConsistencyLevel.EVENTUAL).build();`

`<properties>
        <java.version>11</java.version>
        <reactor-netty>1.0.9</reactor-netty>
        <reactor-core>3.4.8</reactor-core>
    </properties>
<dependencies>
        <dependency>
            <groupId>com.azure</groupId>
            <artifactId>azure-core</artifactId>
            <version>1.18.0</version>
        </dependency>
        <dependency>
            <groupId>com.azure</groupId>
            <artifactId>azure-storage-blob</artifactId>
            <version>12.12.0</version>
            <exclusions>
                <exclusion>
                    <groupId>io.projectreactor</groupId>
                    <artifactId>reactor-core</artifactId>
                </exclusion>
            </exclusions>
        </dependency>
        <dependency>
            <groupId>com.azure</groupId>
            <artifactId>azure-cosmos</artifactId>
            <version>4.17.0</version>
            <exclusions>
                <exclusion>
                    <groupId>io.projectreactor.netty</groupId>
                    <artifactId>reactor-netty</artifactId>
                </exclusion>
            </exclusions>
        </dependency>
        <dependency>
            <groupId>com.azure</groupId>
            <artifactId>azure-identity</artifactId>
            <version>1.3.3</version>
        </dependency>
        <dependency>
            <groupId>io.projectreactor</groupId>
            <artifactId>reactor-core</artifactId>
            <version>${reactor-core}</version>
            
            
        </dependency>
        <dependency>
            <groupId>io.projectreactor.netty</groupId>
            <artifactId>reactor-netty</artifactId>
            <version>${reactor-netty}</version>
            
            
        </dependency>`
**Expected behavior**
Automatically switch to other available authentication if RBAC permissions are not defined. 
**Screenshots**

**Setup (please complete the following information):**
 - OS: Alpine
 - Library/Libraries: PFA above placed version of Artifacts
 - Java version: 11
 - App Server/Environment: Tomcat (Spring boot embedded)
 - Frameworks: Spring Boot

**Comment by joshfree** [comment]
@g2vinay could you please follow up with @MulakaluriKartheek?

/cc @billwert

**Comment by MulakaluriKartheek** [comment]
Error Stack trace:

[2022-02-25T11:50:18.018Z] [com.azure.cosmos.implementation.query.DocumentProducer] [cosmos-rntbd-nio-3-2] [199] [ERROR] [] [] Unexpected failure
com.azure.cosmos.implementation.ForbiddenException: {"innerErrorMessage":"[\"Request is blocked because principal [******************************] does not have the required RBAC permissions to perform action [Microsoft.DocumentDB/databaseAccounts/sqlDatabases/containers/executeQuery] with OperationType [15] and ResourceType [2] on resource [dbs/DB/colls/leases]. Learn more: https://aka.ms/cosmos-native-rbac\"]","cosmosDiagnostics":{"userAgent":"azsdk-java-cosmos/4.17.0 Linux/5.4.0-1062-azure JRE/11.0.5","requestLatencyInMs":1,"requestStartTimeUTC":"2022-02-25T11:50:18.835348Z","requestEndTimeUTC":"2022-02-25T11:50:18.836635Z","responseStatisticsList":[{"storeResult":{"storePhysicalAddress":"rntbd://cdb-ms-prod-centralus1-fd4.documents.azure.com:14101/apps/dbbeead3-9caa-45e6-8ed7-0af7ac3170f4/services/82a44b12-334c-4fa4-9a86-59ae13ac41ce/partitions/2f904776-c8ff-444d-b5cb-e4ab2945b675/replicas/132803609217458999p/","lsn":11989043,"globalCommittedLsn":11989043,"partitionKeyRangeId":"","isValid":true,"statusCode":403,"subStatusCode":5302,"isGone":false,"isNotFound":false,"isInvalidPartition":false,"isThroughputControlRequestRateTooLarge":false,"requestCharge":0.0,"itemLSN":-1,"sessionToken":"-1#11989043","backendLatencyInMs":0.537,"exception":"[\"Request is blocked because principal [6cffda75-7cfa-4e47-8488-e76c7bcf92fc] does not have the required RBAC permissions to perform action [Microsoft.DocumentDB/databaseAccounts/sqlDatabases/containers/executeQuery] with OperationType [15] and ResourceType [2] on resource [dbs/DB/colls/leases]. Learn more: https://aka.ms/cosmos-native-rbac\"]","transportRequestTimeline":[{"eventName":"created","startTimeUTC":"2022-02-25T11:50:18.835414Z","durationInMicroSec":2},{"eventName":"queued","startTimeUTC":"2022-02-25T11:50:18.835416Z","durationInMicroSec":0},{"eventName":"channelAcquisitionStarted","startTimeUTC":"2022-02-25T11:50:18.835416Z","durationInMicroSec":52},{"eventName":"pipelined","startTimeUTC":"2022-02-25T11:50:18.835468Z","durationInMicroSec":85},{"eventName":"transitTime","startTimeUTC":"2022-02-25T11:50:18.835553Z","durationInMicroSec":1005},{"eventName":"received","startTimeUTC":"2022-02-25T11:50:18.836558Z","durationInMicroSec":50},{"eventName":"completed","startTimeUTC":"2022-02-25T11:50:18.836608Z","durationInMicroSec":23}],"rntbdRequestLengthInBytes":2098,"rntbdResponseLengthInBytes":571,"requestPayloadLengthInBytes":222,"responsePayloadLengthInBytes":null,"channelTaskQueueSize":0,"pendingRequestsCount":0,"serviceEndpointStatistics":{"availableChannels":1,"acquiredChannels":0,"executorTaskQueueSize":0,"inflightRequests":1,"lastSuccessfulRequestTime":"2022-02-25T11:48:19.938Z","lastRequestTime":"2022-02-25T11:50:18.810Z","createdTime":"2022-02-25T11:46:37.623655Z","isClosed":false}},"requestResponseTimeUTC":"2022-02-25T11:50:18.836635Z","requestResourceType":"Document","requestOperationType":"Query"}],"supplementalResponseStatisticsList":[],"addressResolutionStatistics":{},"regionsContacted":["https://**********-centralus.documents.azure.com:443/"],"retryContext":{"statusAndSubStatusCodes":null,"retryCount":0,"retryLatency":0},"metadataDiagnosticsContext":{"metadataDiagnosticList":null},"serializationDiagnosticsContext":{"serializationDiagnosticsList":null},"gatewayStatistics":null,"systemInformation":{"usedMemory":"118660 KB","availableMemory":"30288124 KB","systemCpuLoad":"(2022-02-25T11:49:53.463058Z 3.6%), (2022-02-25T11:49:58.463068Z 3.0%), (2022-02-25T11:50:03.463029Z 3.8%), (2022-02-25T11:50:08.463059Z 2.8%), (2022-02-25T11:50:13.463074Z 3.4%), (2022-02-25T11:50:18.463054Z 3.0%)","availableProcessors":1},"clientCfgs":{"id":-1,"connectionMode":"DIRECT","numberOfClients":2,"connCfg":{"rntbd":"(cto:PT5S, rto:PT5S, icto:PT0S, ieto:PT1H, mcpe:130, mrpc:30, cer:false)","gw":"(cps:1000, rto:PT5S, icto:null, p:false)","other":"(ed: true, cs: false)"},"consistencyCfg":"(consistency: Eventual, mm: true, prgns: [centralus])"}}}

**Comment by MulakaluriKartheek** [comment]
Could you please let me know any update on the above issue??

**Comment by MulakaluriKartheek** [comment]
Could you please let me know any update on the above issue??

**Comment by g2vinay** [comment]
@MulakaluriKartheek
The ChainedTokenCredential is designed to execute the chain of credentials sequentially.

In your scenario, you should enable only one Managed Identity (System Assigned or User Assigned) on the target Azure resource.
Plus you should update your code as follows:
```
DefaultAzureCredential defaultAzureCredential = new DefaultAzureCredentialBuilder()
.managedIdentityClientId("<Client-Id-Of-User-Assigned-Managed-Identity>")
build();
```
You don't need to use ChainedTokenCredential, using DefaultAzureCredential as above, will target User Assigned Managed Identity.

**Comment by g2vinay** [comment]
Closing this issue as the solution is posted above.
