### ISSUE TITLE
[BUG] UserAgent in spring-cloud-azure-core will be overrided by user defined project.properties

### ISSUE THREAD

**Issue by backwind1233** [Azure/azure-sdk-for-java#27303]
**Describe the bug**
The method [getVersion](https://github.com/Azure/azure-sdk-for-java/blob/9048cd1/sdk/spring/spring-cloud-azure-core/src/main/java/com/azure/spring/core/AzureSpringIdentifier.java#L78-L78) will return wrong value if the classpath has more than one `META-INF/project.properties`

***Exception or Stack Trace***
No.

**To Reproduce**

This is a mini [sample](https://github.com/backwind1233/issue-sample-27286) to reproduce this issue.

**Expected behavior**
Expected behavior
userAgentSuffix='az-sd-cos/3.17.0az-sp-cos/4.0.0-beta.3'

but the result is userAgentSuffix='az-sd-cos/4.0.0-beta.3az-sp-cos/123',

![image](https://user-images.githubusercontent.com/4465723/155651938-b98f6786-1a88-4dec-aba9-bf485cc173e3.png)

**Screenshots**

The reason is 
**Setup (please complete the following information):**
 - OS: [e.g. Mac]
 - IDE: [e.g. IntelliJ]
 - Library/Libraries: [ azure-spring-data-cosmos:3.17]

**Additional context**

**Information Checklist**
Kindly make sure that you have added all the following information above and checkoff the required fields otherwise we will treat the issuer as an incomplete report
- [x] Bug Description Added
- [x] Repro Steps Added
- [x] Setup information Added
``

**Comment by chenrujun** [comment]
Closing this issue, because related PR has been merged.
