### ISSUE TITLE
[QUERY] Authenticating to Azure with DefaultAzureCredential and IntelliJ Authentication not available

### ISSUE THREAD

**Issue by RJJdeVries** [Azure/azure-sdk-for-java#27307]
**Query/Question**
Hi there!

I am currently working on using the DefaultAzureCredential class to authenticate to Azure. When deployed to the cloud, it will use our managed identity. That's all fine.

Now I am trying to develop for it locally, so I want to use the IntelliJ authentication. I installed the Azure Toolbar plugin, and logged in with my Azure account. I can reach certain resources, like my storage account and sql server.

When I run my application (Quarkus and Kotlin) the DefaultAzureCredential does its work and checks all authentication methods. When it reaches the IntelliJ authentication, it gives the following error:

 IntelliJ Authentication not available. Please log in with Azure Tools for IntelliJ plugin in the IDE.

This seems weird since I already logged in using the Azure plugin and as stated by the docs. How should I proceed here?

***Why is this not a Bug or a feature Request?***
I don't think this is a bug, since I can't find anything about it online.

**Setup (please complete the following information if applicable):**
 - OS: Windows
 - IDE: IntelliJ
 - Library/Libraries:

        <dependency>
            <groupId>com.azure</groupId>
            <artifactId>azure-identity</artifactId>
        </dependency>
        <dependency>
            <groupId>com.azure</groupId>
            <artifactId>azure-core</artifactId>
        </dependency>
        <dependency>
            <groupId>com.azure</groupId>
            <artifactId>azure-messaging-servicebus</artifactId>
        </dependency>
 
 **Information Checklist**
 Kindly make sure that you have added all the following information above and checkoff the required fields otherwise we will treat the issuer as an incomplete report
- [x] Query Added
- [x] Setup information Added

**Comment by joshfree** [comment]
Thanks for reporting this issue with the IntelliJCredential not retrieving the token credential from the Azure Tools for IntelliJ plugin credential cache.  To help investigate this further, could you share the versions of IntelliJ and the Azure Tools for IntelliJ plugin that you're using?

@g2vinay @billwert could you please follow up?

**Comment by RJJdeVries** [comment]
@joshfree, yes ofcourse. My IntelliJ version is IntelliJ IDEA Ultimate 2021.3.2, and my Azure Tools plugin version is 3.61.1-2021.3.

**Comment by billwert** [comment]
Thanks @RJJdeVries! I'll take a look at this.

**Comment by RJJdeVries** [comment]
Gracias. Let me know if I can help!

**Comment by billwert** [comment]
@RJJdeVries I may not get to this until next Monday FYI. Please let us know if you are totally blocked by this.

**Comment by billwert** [comment]
Hello @RJJdeVries! I have tracked down the bug and will get to working on a fix. Sorry for the trouble!

**Comment by RJJdeVries** [comment]
Hey @billwert, thanks! Looking forward to the fix. Yes, will do that.

**Comment by billwert** [comment]
We're going to track this in #21150. @RJJdeVries please follow along there!
