### ISSUE TITLE
[QUERY] Check if AccessPolicy is accepted as an empty parameter from BlobContainer GetAccessPolicy

### ISSUE THREAD

**Issue by amnguye** [Azure/azure-sdk-for-java#27313]
In .NET we faced a bug due to unclear [documentation ](https://docs.microsoft.com/en-us/rest/api/storageservices/set-container-acl#request-body) where the if the CX specified an empty AccessPolicy on the BlobContainerClient and then went to grab the AccessPolicy information, they would get a Null Exception because we except the service to always give us back an access policy, if an id is specified.

To be more specific:
When performing a BlobContainerClient.GetAccessPolicy and the body of the request returns with this value (or access policy)
'<SignedIdentifier><Id>MTIzNDU2Nzg5MDEyMzQ1Njc4OTAxMjM0NTY3ODkwMTI=</Id><AccessPolicy><Start/><Expiry/></AccessPolicy></SignedIdentifier>'

However it also return like
<SignedIdentifier><Id>MTIzNDU2Nzg5MDEyMzQ1Njc4OTAxMjM0NTY3ODkwMTI=</Id></SignedIdentifier>

This scenario can be reproduced if you set the signed identified with an id but not an access policy. I wrote a test in .NET to represent this.
https://github.com/Azure/azure-sdk-for-net/pull/27203/files#diff-cfbbd86d890e76d951dd6142c352ee932045fb0ce70ceb31c1d069f404c692c2R1140

I've also put in a fix in .NET for this issue as well.

https://github.com/Azure/azure-sdk-for-net/pull/27203/files

Please close this issue once we confirm that in Java that we support this scenario. If it does not, please relabel this issue as a bug and resolve it accordingly.

**Comment by ibrahimrabab** [comment]
Hi @amnguye , I tested this behavior by using the same test case you provided in your PR (without making any changes to existing code) and I can confirm that we support this scenario. The test passes fine without having to pass in an AccessPolicy on the BlobContainerClient, and we can easily get the signed identifier from the response.
