### ISSUE TITLE
azure-security-keyvault-jca.jar not work well in Java 17

### ISSUE THREAD

**Issue by chenrujun** [Azure/azure-sdk-for-java#27329]
The following parameter work in Java 11, but not work in Java 17:
```
          --module-path
          /jca/lib --add-modules=com.azure.security.keyvault.jca
```

**Comment by backwind1233** [comment]
Keyvault-jca works with JDK 17, the issue happens because of the wrong configuration.

**Comment by chenrujun** [comment]
Closing this issue because problem solved, and all related PRs have been merged.
