### ISSUE TITLE
[Acr] OciAnnotations has a field for authors, evaluate whether it should be a list<string>

### ISSUE THREAD

**Issue by pallavit** [Azure/azure-sdk-for-java#27338]
1. OciAnnotations has a field for authors, evaluate whether it should be a list<string>
2. GetDocumentation should be renamed to GetDocumentationLink
3. OciBlobDescriptor size should be renamed to sizeInBytes.

**Comment by lmolkova** [comment]
> OciAnnotations has a field for authors, evaluate whether it should be a list

It's a free-form string, so it can't be

> org.opencontainers.image.authors contact details of the people or organization responsible for the image (freeform string)

https://github.com/opencontainers/image-spec/blob/main/annotations.md#pre-defined-annotation-keys
