### ISSUE TITLE
ServiceBusTemplate should not support partition id

### ISSUE THREAD

**Issue by yiliuTo** [Azure/azure-sdk-for-java#27349]
Due to partition id is not supported in Service Bus, referring https://docs.microsoft.com/en-gb/azure/service-bus-messaging/service-bus-partitioning#use-of-partition-keys, thus `ServiceBusTemplate #sendAsync` should not accept a `PartitionSupplier` directly which is able to configure both partition key and id.

**Comment by saragluna** [comment]
Closed in #27422.
