### ISSUE TITLE
[FEATURE REQ] set user-info-url property to fetch AAD attributes

### ISSUE THREAD

**Issue by Eimert** [Azure/azure-sdk-for-java#27370]
**Is your feature request related to a problem? Please describe.**
I'd like to access the mailNickname AAD att of authenticated users. 

**Describe the solution you'd like**
I'd like to retrieve the mailNickname AAD attribute for users, by providing  `azure.activedirectory.user-info-uri=https://graph.microsoft.com/v1/me?select=mailNickname`. I expect the user attributes to be populated in the `OidcUserInfo` object.

**Describe alternatives you've considered**
I've considered to provide a custom `OAuth2UserService` implementation. Or implementing Azure AD auth in (native) Spring Security.

**Additional context**
NA

**Information Checklist**
Kindly make sure that you have added all the following information above and checkoff the required fields otherwise we will treat the issuer as an incomplete report
- [X] Description Added
- [X] Expected solution specified

**Comment by Eimert** [comment]
@chenrujun we've found a workaround by adding the desired data to the claims.

**Comment by chenrujun** [comment]
@Eimert 

Thank you for your information.
Could you please share more information about how do you achieve that?

**Comment by pl-marek-1984** [comment]
You can set custom claim and add it to the App Reg openid token response following this documentation: https://docs.microsoft.com/en-us/azure/active-directory/develop/active-directory-claims-mapping

**Comment by chenrujun** [comment]
Closing this issue, because the issue creator already found a workaround.
