### ISSUE TITLE
[FEATURE REQ] Support different checkpointing strategy in EventProcessorClient

### ISSUE THREAD

**Issue by saragluna** [Azure/azure-sdk-for-java#27397]
Discussed in this API reivew: https://apiview.dev/Assemblies/Review/58995c5facde49aa8898510ae955d5b6/383efae1c77e4f2096e0d30bc9479233#com.azure.spring.eventhubs.checkpoint.EventCheckpoint. 

In spring-azure-messaging-eventhubs we support two more checkpointing strategies for a `processor` client, `TIME` and `PARTITON_COUNT`. 
- When set `mode=TIME` and `interval=5min`, it will checkpoint all the events consumed in the last 5 mins. 
- When set `mode=PARTITON_COUNT` and `count=10`, it will checkpoint when the number of events consumed in each partition reaches 10.

Not sure whether there is a plan to support extra checkpointing strategies in the data-plane SDK `EventProcessorClient`? 

(cc @srnagar)

**Comment by jsquire** [comment]
@conniey: Interesting timing.   This is one of the things that I wanted to talk about next week for consideration post-Copper.

**Comment by conniey** [comment]
WIP: https://gist.github.com/conniey/f7f2beac5e7103d92dd192e918418760
