### ISSUE TITLE
[QUERY] How do I enable HTTP request logging for Azure Java SDK using log4j?

### ISSUE THREAD

**Issue by dclusin-cisco** [Azure/azure-sdk-for-java#27407]
**Query/Question**
I would like to enable logging of the outgoing REST requests to azure but I am unable to figure out how to accomplish that.

Things I have tried:
1. Reading the docuementation
- Looking at: https://docs.microsoft.com/en-us/azure/developer/java/sdk/logging-log4j
I tried adding to my log4j config:
        <Logger name="com.azure.core" level="debug" additivity="true">
            <appender-ref ref="console" />
        </Logger>
2. Custom configuration
- Looking a little deeper into client configuration the AzureResourceManager.Configurable class has two methods with might be helpful: `withLogLevel` and `withLogOptions`. 

I am calling both of these but they seem to have no affect on logging. Specifically my configuration looks like:
```
        HttpLogOptions options = new HttpLogOptions();
        options.setLogLevel(HttpLogDetailLevel.BODY_AND_HEADERS);
        options.setPrettyPrintBody(true);

        AzureResourceManager manager = AzureResourceManager.configure()
                .withHttpClient(getHttpClient())
                .withLogOptions(getHttpLogOptions())
                .authenticate(credential, profile)
                .withSubscription(credentials.subscriptionId());
```

What am I missing/doing wrong here? Are there any code samples of how to accomplish this?
***Why is this not a Bug or a feature Request?***
Because it seems like logging requests is supported, I'm just not clear on how to do it and googling has been unhelpful. Are there any code examples of enabling request logging?

**Setup (please complete the following information if applicable):**
 - OS: Mac OS
 - IDE: Intellij
 - Library/Libraries: com.azure:azure-resourcemanager:2.8.0
 
 **Information Checklist**
 Kindly make sure that you have added all the following information above and checkoff the required fields otherwise we will treat the issuer as an incomplete report
- [ ] Query Added
- [ ] Setup information Added

**Comment by joshfree** [comment]
Thanks for filing this issue @dclusin-cisco.  @alzimmermsft could you please follow up and also help clarify this scenario in the logging docs / samples? 

/cc @weidongxu-microsoft as this relates indirectly to ARM

**Comment by weidongxu-microsoft** [comment]
@dclusin-cisco

I think this is the correct configuration.

A sample project here https://github.com/weidongxu-microsoft/az-java-sdk-aad
Please check the POM and Main.java

I would have these in logging:

```
[main] INFO com.azure.identity.EnvironmentCredential - Azure Identity => EnvironmentCredential invoking ClientSecretCredential
[main] INFO com.azure.core.implementation.jackson.JacksonVersion - Package versions: jackson-annotations=2.13.1, jackson-core=2.13.1, jackson-databind=2.13.1, jackson-dataformat-xml=2.13.1, jackson-datatype-jsr310=2.13.1, azure-core=1.25.0, Troubleshooting version conflicts: https://aka.ms/azsdk/java/dependency/troubleshoot
[ForkJoinPool.commonPool-worker-3] INFO com.azure.identity.ClientSecretCredential - Azure Identity => getToken() result for scopes [https://management.core.windows.net//.default]: SUCCESS
[ForkJoinPool.commonPool-worker-3] INFO com.azure.identity.DefaultAzureCredential - Azure Identity => Attempted credential EnvironmentCredential returns a token
[ForkJoinPool.commonPool-worker-3] INFO com.azure.core.implementation.AccessTokenCache - Acquired a new access token.
[ForkJoinPool.commonPool-worker-3] INFO com.azure.resourcemanager.resources.implementation.ResourceGroupsClientImpl$ResourceGroupsService.list - --> GET https://management.azure.com/subscriptions/<subscriptionId>/resourcegroups?api-version=REDACTEDTry count: 1(empty body)--> END GET
[reactor-http-nio-2] INFO com.azure.resourcemanager.resources.implementation.ResourceGroupsClientImpl$ResourceGroupsService.list - <-- 200 https://management.azure.com/subscriptions/<subscriptionId>/resourcegroups?api-version=REDACTED (454 ms, 2067-byte body)Response body:{"value":[{"id":"/subscriptions/<subscriptionId>/resourceGroups/subscriptionScrubber","name":"foo","type":"Microsoft.Resources/resourceGroups","location":"westus","properties":{"provisioningState":"Succeeded"}}]}<-- END HTTP
```

**Comment by alzimmermsft** [comment]
Closing as there is documentation available for this now: https://github.com/Azure/azure-sdk-for-java/tree/main/sdk/core/azure-core#enabling-logging
