### ISSUE TITLE
[QUERY] Using MSI to connect Cosmos DB to Synapse using spark connector

### ISSUE THREAD

**Issue by espeo196** [Azure/azure-sdk-for-java#27413]
**Query/Question**
I am trying to connect Azure Cosmos DB to Synapse using a managed identity. Previously I was using a connection string with a linked service. Now with the switch I get generic 400: Invalid Input exceptions.
I have performed the following:
-Added the Synapse managed identity as a CosmosDB Reader role to the Cosmos db
-Created a new linked service in Synapse to this Cosmos db
-Validated the linked service using the 'Test Connection' button on the linked service
-The Cosmos db is not analytics enabled. So I have tried using both read and readstream with the same results:
`val dfs = spark.read .format("cosmos.olap").option("spark.synapse.linkedService", "cosmosLink").option("spark.cosmos.container", "Taxonomy").load()`

I have tried using different formats (olap, oltp). I've also tried using readstream with format("cosmos.oltp.changeFeed"), but I get the same "Invalid Input" error each time.
I have created a connector that uses connectionString and used that in place of the spark.synapse.linkedService parameter and everything works fine. I've also successfully moved to MSI-based auth for a few other resources without trouble. Synapse is the only one giving me trouble.

Error excerpt:
`Resolving Azure CosmosDB LinkedService [cosmosLink] in Azure Synapse failed.Validate the configured LinkedService. If still seeing this, try using the Azure CosmosDB account name and credentials directly.
	at com.microsoft.azure.cosmos.analytics.spark.connector.api.ArcadiaLinkService$.fetchCosmosAccountInfo(ArcadiaLinkService.scala:118)
...
Caused by: java.lang.Exception: Access token couldn't be obtained {"result":"DependencyError","errorId":"BadRequest","errorMessage":"LSRServiceException is [{\"StatusCode\":400,\"ErrorResponse\":{\"code\":\"BadRequest\",\"message\":\"Invalid Input\",\"target\":null}`

**Setup:**
-Apache spark pool is using Spark 3.1 and Scala 2.12.0
-Configuration done through the Azure UI which has pulled in com.microsoft.azure.cosmos.analytics.spark.connector

**Comment by joshfree** [comment]
@kushagraThapar can you assign this to someone on your team?

**Comment by kushagraThapar** [comment]
@xinlian12 / @FabianMeiswinkel  - please take a look at this!
