### ISSUE TITLE
[BUG] Azure core credential failing when using java modules

### ISSUE THREAD

**Issue by tinolazreg** [Azure/azure-sdk-for-java#27428]
**Describe the bug**
We are trying to use azure-identity, which depends on azure-core, in a Java project using java modules.
This fails when azure-identity is trying to retrieve a managed identity token. From the stack trace it seems like the issue is that azure-core is missing to add "opens com.azure.core.http.rest to com.fasterxml.jackson.databind;" 
here: https://github.com/Azure/azure-sdk-for-java/blob/main/sdk/core/azure-core/src/main/java/module-info.java#L48, so Jackson is able to deserialize the token to the AccessToken class.

***Exception or Stack Trace***
```java
Caused by: com.fasterxml.jackson.databind.exc.InvalidDefinitionException: Failed to call `setAccess()` on Field 'token' due to `java.lang.reflect.InaccessibleObjectException`, 

problem: Unable to make field private final java.lang.String com.azure.core.credential.AccessToken.token accessible:

 module com.azure.core does not "opens com.azure.core.credential" to module com.fasterxml.jackson.databind  at [Source: (String)"
```

**To Reproduce**
1. Try to run "new ManagedIdentityCredentialBuilder().build()" in an application setup with ManagedIdentity and using java modules.

**Setup (please complete the following information):**
 - Library/Libraries: com.azure:azure-core:1.25.0, com.azure:azure-identity:1.4.4

**Comment by joshfree** [comment]
@billwert could you follow up with @tinolazreg on this?

**Comment by billwert** [comment]
I think this got closed erroneously. I'll take a look, @tinolazreg.

**Comment by alzimmermsft** [comment]
The mentioned PR added the `opens` in the module-info for `com.azure.core.credential`

**Comment by billwert** [comment]
My apologies, I missed it! Thanks @alzimmermsft
