### ISSUE TITLE
[FEATURE REQ] Make spring managed external dependencies' version more clear

### ISSUE THREAD

**Issue by chenrujun** [Azure/azure-sdk-for-java#27427]
### Context
Now all external dependencies' versions are stored in https://github.com/Azure/azure-sdk-for-java/blob/spring-cloud-azure_4.0.0/eng/versioning/external_dependencies.txt

### Problem

Since spring-boot-dependencies and spring-cloud-dependencies may not release at the same time.
1. spring-boot-dependencies release tags: https://github.com/spring-projects/spring-boot/tags
2. spring-cloud-dependencies release tags: https://github.com/spring-cloud/spring-cloud-release/tags

And now all the versions managed by the 2 boms are stored in a file named "spring-boot_xxx_managed_external_dependencies". So if we only update spring-cloud-dependencies, it will override the last version and we can't keep track of them.

For example: when `spring-boot-dependencies:2.6.4` released, and `spring-cloud-dependencies:v2021.0.0` released, all managed versions are recorded in `spring_boot_2.6.4_managed_external_dependencies.txt`. After `spring-cloud-dependencies:v2021.0.1` released, these versions are still recorded in the file, then the file will not have single source of truth. We should not change these files' content after they are created.

### Solution

 - [ ] Update the logic in `get_spring_boot_managed_external_dependencies.py`: Put output file(`spring-boot_xxx_managed_external_dependencies.txt`) into a new folder: `sdk/spring/scripts/spring-boot-xxx-and-spring-cloud-yyy`.
 - [ ] Update the logic in `get_spring_boot_managed_external_dependencies.py`: Split `spring-boot_xxx_managed_external_dependencies.txt` into 2 files:
     - spring-boot-dependencies-managed-versions.txt.
     - spring-cloud-dependencies-managed-versions.txt.
 - [ ] Rename `get_spring_boot_managed_external_dependencies.py` to `get_spring_boot_and_spring_cloud_managed_external_dependencies.py`
 - [ ] Update the logic in `get_spring_boot_and_spring_cloud_managed_external_dependencies.py`: Output a new file named `version conflicts.txt`, which contains the versions that different in `spring-boot-dependencies-managed-versions.txt` and `spring-cloud-dependencies-managed-versions.txt`. This file have format like this:
 > group-id:artifact-id;spring-boot-dependencies-managed-version;spring-boot-dependencies-managed-version

The ci job should use the new file to check version compatibility. Here is link to related logic: https://github.com/Azure/azure-sdk-for-java/blob/spring-cloud-azure-dependencies_4.0.0-beta.3/sdk/spring/ci.yml#L345-L346

**Comment by stliu** [comment]
is this still valid?

and some suggestion:

1. clearly describe the problem to be solved instead of prescribing a solution
2. what the goal of this issue?

**Comment by chenrujun** [comment]
@stliu 

This is still valid.
I updated the Issue title and description. Thank you.

**Comment by Netyyyy** [comment]
This will work in https://github.com/Azure/spring-cloud-azure-tools/issues/2
