### ISSUE TITLE
[BUG] Setting an aggregation for a metrics query doesn't work

### ISSUE THREAD

**Issue by beji** [Azure/azure-sdk-for-java#27454]
**Describe the bug**
I'm building a small client application that gathers traffic data from some event hubs and I want to use `AggregationType.TOTAL`. This leads to the response not actually containing any `total` data, just `count`. 
The issue seems to be in https://github.com/Azure/azure-sdk-for-java/blob/main/sdk/monitor/azure-monitor-query/src/main/java/com/azure/monitor/query/MetricsQueryAsyncClient.java#L214 as this will turn `AggregationType.TOTAL` into the String `"5"`, which doesn't seem very correct and apparently doesn't lead to the correct result. Not adding any aggregation at all returns total values.

***Exception or Stack Trace***
Add the exception log and stack trace if available

**To Reproduce**
Add any `AggregationType` to `MetricsQueryOptions` with `setAggregations` and call `queryResourceWithResponse`

***Code Snippet***
```java
            MetricsQueryOptions options = new MetricsQueryOptions().setMetricNamespace("microsoft.eventhub/namespaces")
                    .setGranularity(Duration.parse("P1D")).setFilter(String.format("EntityName eq '%s'", topic))
                    .setTimeInterval(new QueryTimeInterval(Duration.ofDays(30))).setTop(500)
                    .setAggregations(AggregationType.TOTAL);

            MetricsQueryResult queryResult = client.queryResourceWithResponse(resource,
                    Arrays.asList("IncomingBytes", "OutgoingBytes"), options, Context.NONE).getValue();
```

**Expected behavior**
I'd expect to actually get correctly aggregated data.

**Screenshots**
<img width="944" alt="Bildschirmfoto 2022-03-04 um 12 12 06" src="https://user-images.githubusercontent.com/591268/156754087-935e6817-a960-4e1d-b1f5-3417500c589b.png">

**Setup (please complete the following information):**
 - OS: macOs
 - IDE: IntelliJ & Emacs
 - Library/Libraries: com.azure:azure-monitor-query:1.0.3
 - Java version: 11 
 - App Server/Environment: none
 - Frameworks: none

**Information Checklist**
Kindly make sure that you have added all the following information above and checkoff the required fields otherwise we will treat the issuer as an incomplete report
- [X] Bug Description Added
- [X] Repro Steps Added
- [X] Setup information Added

**Comment by joshfree** [comment]
Thanks for reporting this issue, @beji.  @srnagar can you please follow up?

/cc @scottaddie

**Comment by srnagar** [comment]
@beji Thanks for reporting the bug. I have a PR open to fix the issue - https://github.com/Azure/azure-sdk-for-java/pull/27499
