### ISSUE TITLE
Check all spring messaging related samples can work as expected

### ISSUE THREAD

**Issue by yiliuTo** [Azure/azure-sdk-for-java#27475]
Before 4.0 GA release, we should check all messaging related samples can work correctly. The involved samples are
Event Hubs:
- [x] 1. https://github.com/Azure-Samples/azure-spring-boot-samples/tree/spring-cloud-azure_4.0.0-beta.4/eventhubs/spring-cloud-azure-starter-integration-eventhubs/eventhubs-integration
- [x] 2. https://github.com/Azure-Samples/azure-spring-boot-samples/tree/spring-cloud-azure_4.0.0-beta.4/eventhubs/spring-cloud-azure-starter/spring-cloud-azure-sample-eventhubs-kafka
- [x] 3. https://github.com/Azure-Samples/azure-spring-boot-samples/tree/spring-cloud-azure_4.0.0-beta.4/eventhubs/spring-cloud-azure-stream-binder-eventhubs/eventhubs-binder
- [x] 4. https://github.com/Azure-Samples/azure-spring-boot-samples/tree/spring-cloud-azure_4.0.0-beta.4/eventhubs/spring-cloud-azure-stream-binder-eventhubs/eventhubs-multibinders

Service Bus
- [x] 1. https://github.com/Azure-Samples/azure-spring-boot-samples/tree/spring-cloud-azure_4.0.0-beta.4/servicebus/spring-cloud-azure-starter-integration-servicebus/single-namespace
- [x] 2. https://github.com/Azure-Samples/azure-spring-boot-samples/tree/spring-cloud-azure_4.0.0-beta.4/servicebus/spring-cloud-azure-starter-integration-servicebus/multiple-namespaces
- [x] 3. https://github.com/Azure-Samples/azure-spring-boot-samples/tree/spring-cloud-azure_4.0.0-beta.4/servicebus/spring-cloud-azure-starter-servicebus-jms
- [x] 4. https://github.com/Azure-Samples/azure-spring-boot-samples/tree/spring-cloud-azure_4.0.0-beta.4/servicebus/spring-cloud-azure-stream-binder-servicebus/servicebus-queue-binder
- [x] 5. https://github.com/Azure-Samples/azure-spring-boot-samples/tree/spring-cloud-azure_4.0.0-beta.4/servicebus/spring-cloud-azure-stream-binder-servicebus/servicebus-topic-binder
- [x] 6. https://github.com/Azure-Samples/azure-spring-boot-samples/tree/spring-cloud-azure_4.0.0-beta.4/servicebus/spring-cloud-azure-stream-binder-servicebus/servicebus-multibinders
- [x] 7. https://github.com/Azure-Samples/azure-spring-boot-samples/tree/spring-cloud-azure_4.0.0-beta.4/servicebus/spring-cloud-azure-stream-binder-servicebus/servicebus-queue-binder-arm

Storage Queue
- [x] 1. https://github.com/Azure-Samples/azure-spring-boot-samples/tree/spring-cloud-azure_4.0.0-beta.4/storage/spring-cloud-azure-starter-integration-storage-queue

We should make sure all features provided in each samples can work as expected, as for which features should be tested, please refer to the README of each sample projects.

**Comment by Netyyyy** [comment]
closed in https://github.com/Azure-Samples/azure-spring-boot-samples/pull/219

**Comment by Netyyyy** [comment]
As SDK has new codes, check these again.

**Comment by Netyyyy** [comment]
Fix checkpoint changes in messaging. https://github.com/Azure-Samples/azure-spring-boot-samples/pull/226

**Comment by Netyyyy** [comment]
close it since @hui1110 check it all.
