### ISSUE TITLE
Do clients support offline mode?

### ISSUE THREAD

**Issue by Ilya-Gazman-2** [Azure/azure-sdk-for-java#27471]
Does Azure Service Bus have efficient offline support for clients?

1. Are the messages persisted in local storage when the client goes offline or gets IO errors?
2. When the client is recovered from offline mode, will the messages be sent in batches, or will they be sent one by one?

I am particularly interested in the Android client

**Comment by anuchandy** [comment]
Hello, There is no officially supported android service bus library, and the java service bus library does not persist any state/payload in the disk.
