### ISSUE TITLE
Make sure Spring Cloud Azure 4.0 uncategorized  samples can work

### ISSUE THREAD

**Issue by saragluna** [Azure/azure-sdk-for-java#27486]
We should make sure all uncategorized samples can work correctly before 4.0 GA.
- [ ] [PetClinic](https://github.com/Azure-Samples/azure-spring-boot-samples/tree/spring-cloud-azure_4.0.0-beta.4/spring-petclinic-microservices)

**Comment by Netyyyy** [comment]
closed in https://github.com/Azure-Samples/azure-spring-boot-samples/pull/229
