### ISSUE TITLE
Improve the performance of BI Dashboard

### ISSUE THREAD

**Issue by backwind1233** [Azure/azure-sdk-for-java#27487]
**Context**
Now we have about 18 BI tables, and most of them read data from kusto functions in real-time, which will query kusto clusters concurrently, it costs a lot of memory and may result in LOW_MEMORRY error.

**Goal**
Improve the performance of BI jobs, reduce the resources used in our daily BI queries.

**Proposal**
We can use the daily job to run kusto functions and export the results to new kusto tables,
in this way, the powerbi dashboard can read data from tables directly.

**Comment by stliu** [comment]
closing this for internal ADO
