### ISSUE TITLE
Make sure Spring Cloud Azure 4.0 samples can work for Database: Cache, Cosmos, Storage

### ISSUE THREAD

**Issue by saragluna** [Azure/azure-sdk-for-java#27484]
We should make sure all database-related samples can work correctly before 4.0 GA.

- [ ] https://github.com/Azure-Samples/azure-spring-boot-samples/tree/spring-cloud-azure_4.0.0-beta.4/cache
- [ ] https://github.com/Azure-Samples/azure-spring-boot-samples/tree/spring-cloud-azure_4.0.0-beta.4/cosmos
- [ ] https://github.com/Azure-Samples/azure-spring-boot-samples/tree/spring-cloud-azure_4.0.0-beta.4/storage

**Comment by jialigit** [comment]
| cache                                                        | yes  | terraform 15 mins running                                    |
| ------------------------------------------------------------ | ---- | ------------------------------------------------------------ |
| azure-spring-boot-sample-cosmos-multi-database-multi-account | no   | Error: "start_ip_address" is not a valid IPv4 address: "2404:f801:8050:3:80be::192" |
| azure-spring-boot-sample-cosmos-multi-database-single-account | yes  |                                                              |
| spring-cloud-azure-cosmos-sample                             | yes  |                                                              |
| spring-cloud-azure-starter-data-cosmos                       | yes  |                                                              |
| azure-spring-integration-sample-storage-queue                | yes  |                                                              |
| azure-spring-cloud-sample-storage-queue-operation            | yes  |                                                              |
| storage-blob-sample                                          | yes  |                                                              |
| storage-file-sample                                          | yes  |                                                              |
|                                                              |      |                                                              |

**Comment by backwind1233** [comment]
> 

<img width="770" alt="image" src="https://user-images.githubusercontent.com/4465723/161284209-e473a046-8e3c-4df0-be12-dd080a4f8ea4.png">

The known issue is addressed in this PR:https://github.com/Azure-Samples/azure-spring-boot-samples/pull/275
