### ISSUE TITLE
Check the spring security migration guide is correct and complete

### ISSUE THREAD

**Issue by saragluna** [Azure/azure-sdk-for-java#27488]
Before 4.0 GA release, we should make sure the migration guide is correct and contain all breaking changes.
For spring security parts, the migration guide contains 

1. [Artifact changes: renamed / added / deleted](https://microsoft.github.io/spring-cloud-azure/4.0.0-beta.4/4.0.0-beta.4/reference/html/appendix.html#_artifact_changes_renamed_added_deleted)
2. [Configuration changes](https://microsoft.github.io/spring-cloud-azure/4.0.0-beta.4/4.0.0-beta.4/reference/html/appendix.html#_configuration_properties_2)
3. [API changes](https://microsoft.github.io/spring-cloud-azure/4.0.0-beta.4/4.0.0-beta.4/reference/html/appendix.html#_api_breaking_changes)

We should also make sure users can follow our migration guide and migrate their projects.

**Comment by chenrujun** [comment]
FYI: Remember to update according to #27579

**Comment by chenrujun** [comment]
Note: an error in current keyvault migration guide:
https://microsoft.github.io/spring-cloud-azure/4.0.0-beta.4/4.0.0-beta.4/reference/html/appendix.html#configuration-spring-cloud-azure-starter-keyvault-secrets

![image](https://user-images.githubusercontent.com/13167207/158917510-a9aed145-7c1d-4d5b-829d-b321b85caa89.png)

**Comment by jialigit** [comment]
For the check and update for the 4.0 version update is finished.  close it.
