### ISSUE TITLE
Make sure Spring Cloud Azure 4.0 samples can work for Security: AAD, Key Vault

### ISSUE THREAD

**Issue by saragluna** [Azure/azure-sdk-for-java#27483]
We should make sure all security-related samples can work correctly before 4.0 GA.

  AAD:
finished in:https://github.com/Azure-Samples/azure-spring-boot-samples/pull/281
          and:https://github.com/Azure-Samples/azure-spring-boot-samples/pull/308

- [x] https://github.com/Azure-Samples/azure-spring-boot-samples/tree/spring-cloud-azure_4.0.0-beta.4/aad/spring-cloud-azure-starter-active-directory-b2c/aad-b2c-resource-server
- [x] https://github.com/Azure-Samples/azure-spring-boot-samples/tree/spring-cloud-azure_4.0.0-beta.4/aad/spring-cloud-azure-starter-active-directory-b2c/aad-b2c-web-application
- [x] https://github.com/Azure-Samples/azure-spring-boot-samples/tree/spring-cloud-azure_4.0.0-beta.4/aad/spring-cloud-azure-starter-active-directory/aad-resource-server-by-filter-stateless
- [x] https://github.com/Azure-Samples/azure-spring-boot-samples/tree/spring-cloud-azure_4.0.0-beta.4/aad/spring-cloud-azure-starter-active-directory/aad-resource-server-by-filter
- [x] https://github.com/Azure-Samples/azure-spring-boot-samples/tree/spring-cloud-azure_4.0.0-beta.4/aad/spring-cloud-azure-starter-active-directory/aad-resource-server-obo
- [x] https://github.com/Azure-Samples/azure-spring-boot-samples/tree/spring-cloud-azure_4.0.0-beta.4/aad/spring-cloud-azure-starter-active-directory/aad-resource-server
- [x] https://github.com/Azure-Samples/azure-spring-boot-samples/tree/spring-cloud-azure_4.0.0-beta.4/aad/spring-cloud-azure-starter-active-directory/aad-web-application-and-resource-server
- [x] https://github.com/Azure-Samples/azure-spring-boot-samples/tree/spring-cloud-azure_4.0.0-beta.4/aad/spring-cloud-azure-starter-active-directory/aad-web-application

keyvault:
finished in: https://github.com/Azure-Samples/azure-spring-boot-samples/pull/245
- [x] https://github.com/Azure-Samples/azure-spring-boot-samples/tree/spring-cloud-azure_4.0.0-beta.4/keyvault/spring-cloud-azure-starter-keyvault-secrets/property-source
- [x] https://github.com/Azure-Samples/azure-spring-boot-samples/tree/spring-cloud-azure_4.0.0-beta.4/keyvault/spring-cloud-azure-starter-keyvault-secrets/secret-client
- [x] https://github.com/Azure-Samples/azure-spring-boot-samples/tree/spring-cloud-azure_4.0.0-beta.4/keyvault/azure-spring-boot-starter-keyvault-certificates/keyvault-certificates-client-side
- [x] https://github.com/Azure-Samples/azure-spring-boot-samples/tree/spring-cloud-azure_4.0.0-beta.4/keyvault/azure-spring-boot-starter-keyvault-certificates/keyvault-certificates-server-side
- [x] https://github.com/Azure-Samples/azure-spring-boot-samples/tree/spring-cloud-azure_4.0.0-beta.4/keyvault/azure-securtiy-keyvault-jca/run-with-command-line-client-side
- [x] https://github.com/Azure-Samples/azure-spring-boot-samples/tree/spring-cloud-azure_4.0.0-beta.4/keyvault/azure-securtiy-keyvault-jca/run-with-command-line-server-side

**Comment by Netyyyy** [comment]
close in https://github.com/Azure-Samples/azure-spring-boot-samples/pull/281 , https://github.com/Azure-Samples/azure-spring-boot-samples/pull/308 and https://github.com/Azure-Samples/azure-spring-boot-samples/pull/245
