### ISSUE TITLE
[FEATURE REQ] Work on the feature spec of data-plane sdks support

### ISSUE THREAD

**Issue by saragluna** [Azure/azure-sdk-for-java#27495]
https://microsoftapc.sharepoint.com/teams/Springintegration/_layouts/15/Doc.aspx?sourcedoc={979d750c-2e38-4f8f-8e78-a17145269e2f}&action=edit&wd=target%28Planning.one%7C738eca58-cdf3-49c8-ae97-2255cfb7dafd%2F05-More%20Azure%20data%20plane%20GA-ed%20SDKs%7Ce7953b2f-9123-467f-82eb-818613ed4607%2F%29

**Comment by hui1110** [comment]
[More Azure data plane GA-ed SDKs](https://microsoftapc.sharepoint.com/teams/Springintegration/SiteAssets/Spring%20integration%20Notebook/Planning.one#06-More%20Azure%20data%20plane%20GA-ed%20SDKs&section-id=738eca58-cdf3-49c8-ae97-2255cfb7dafd&page-id=e7953b2f-9123-467f-82eb-818613ed4607&end) updated, close it now.
