### ISSUE TITLE
Spike Research for credential free connection support for 3rd party databases

### ISSUE THREAD

**Issue by saragluna** [Azure/azure-sdk-for-java#27494]
### Context
Support for managed identity has become a fundamental principle for Azure, providing a security baseline at the individual service level. We believe aligning on those guidelines will also benefit Spring developers at large.  

We do not support credential-free connection for any 3rd party libraries today, and for 1st party libraries where we already have support, documentation and samples are lacking to guide Spring developers to complete their journey. Lack of samples has been one of the top challenges reported in the [Nov 2021 Java on Azure E2E](https://microsoft.sharepoint.com/:p:/t/JavaonAzureE2EExperiences/ESKPSPGqa-9LvjyPUcQLXewBjzNLtMWDSEHUtPkKFi3yDQ?e=k98h4f) report.

### Goal
Since we planned the feature of connecting free connection support for 3rd party databases for next semester, we should work out the feature spec before we start working on this feature. The goal of this feature is to output:
- A feature spec 
- A design spec
- A roadmap of this feature

**Comment by yiliuTo** [comment]
Here is the feature spec for credential-free support of Spring Cloud Azure:https://github.com/Azure/azure-sdk-for-java/wiki/Credential-free-connection-support-for-Spring-Cloud-Azure.
Close this issue.
