### ISSUE TITLE
Make sure Spring Cloud Azure 4.0 Manged identity can work correctly, both user-assigned and system assigned

### ISSUE THREAD

**Issue by saragluna** [Azure/azure-sdk-for-java#27492]
We should make sure the latest Spring Cloud Azure 4.0 MI can work correctly, both system-assigned and user-assigned managed identity.

**Comment by hui1110** [comment]
According to the steps in the [document](https://docs.microsoft.com/en-us/azure/spring-cloud/quickstart?tabs=Azure-CLI&pivots=programming-language-java), add the configuration of `spring.cloud.azure.credential.managed-identity-enabled: true` to the sample, and deploy it to the Azure spring cloud, and it can run normally.

**Comment by hui1110** [comment]
close it now.
