### ISSUE TITLE
Check the spring core migration guide is correct and complete

### ISSUE THREAD

**Issue by saragluna** [Azure/azure-sdk-for-java#27491]
Before 4.0 GA release, we should make sure the migration guide is correct and contain all breaking changes.
For spring core parts, the migration guide contains 

1. [Artifact changes: renamed / added / deleted](https://microsoft.github.io/spring-cloud-azure/4.0.0-beta.4/4.0.0-beta.4/reference/html/appendix.html#_artifact_changes_renamed_added_deleted)
2. [Configuration changes](https://microsoft.github.io/spring-cloud-azure/4.0.0-beta.4/4.0.0-beta.4/reference/html/appendix.html#_configuration_properties_2)
3. [API changes](https://microsoft.github.io/spring-cloud-azure/4.0.0-beta.4/4.0.0-beta.4/reference/html/appendix.html#_api_breaking_changes)

We should also make sure users can follow our migration guide and migrate their projects.

**Comment by hui1110** [comment]
https://github.com/microsoft/spring-cloud-azure/pull/870

**Comment by saragluna** [comment]
Closed in https://github.com/microsoft/spring-cloud-azure/pull/870
