### ISSUE TITLE
[FEATURE REQ] Set up the UX study environment for Spring Cloud Azure 4.0 

### ISSUE THREAD

**Issue by saragluna** [Azure/azure-sdk-for-java#27493]
https://dev.azure.com/azure-spring-integration/spring-integration-private/_workitems/edit/1289
https://dev.azure.com/azure-spring-integration/spring-integration-private/_workitems/edit/1290

More on the scenario:
```
search for a folder that contains today's date
upload the file in that folder
upload failed due to access right
handle the error (could be as simple as display the error msg to the user)
```

1. vm
2. blob storage
3. demo

**Comment by jialigit** [comment]
Done for env and code.
