### ISSUE TITLE
[Service Bus] Failed build service bus client in weekly pipeline test

### ISSUE THREAD

**Issue by hongli750210** [Azure/azure-sdk-for-java#27509]
We are running live tests against other clouds like US Gov and Azure China Cloud. The goal is to check whether new azure sdk package work with other clouds or not.

**Error Description:**
When running the integration test [ServiceBusClientBuilderTest.customNoneProxyConfigurationBuilder](https://github.com/Azure/azure-sdk-for-java/blob/main/sdk/servicebus/azure-messaging-servicebus/src/test/java/com/azure/messaging/servicebus/ServiceBusClientBuilderTest.java#L121) on Public and UsGov and China cloud, it returns the error `java.lang.IllegalStateException: Cannot build client without setting either a ***Name or ***Name.`. The error message is shown as following, for more details please check [here](https://dev.azure.com/azure-sdk/internal/_build/results?buildId=1415667&view=results).

**Error Tracking:**
Code [Link](https://github.com/Azure/azure-sdk-for-java/blob/main/sdk/servicebus/azure-messaging-servicebus/src/main/java/com/azure/messaging/servicebus/ServiceBusClientBuilder.java#L296):
![image](https://user-images.githubusercontent.com/74638143/157146150-23dd08b1-e160-4d64-9d4e-95cbcd2f20d1.png)

**Expected Behavior:**
The ServiceBus Client can also be builded successfully when using the connection string in this format [Endpoint=%s;SharedAccessKeyName=%s;SharedAccessKey=%s;EntityPath=%s].

_Suggestion:_
Update `if (CoreUtils.isNullOrEmpty(entityPath))` to `if (!CoreUtils.isNullOrEmpty(entityPath))`

@benbp, @joshfree, @lilyjma, @ramya-rao-a and @ZejiaJiang for notification.

**Comment by v-xuto** [comment]
@benbp, @joshfree, @lilyjma, @ramya-rao-a and @ZejiaJiang 
Do you have any idea about this issue?

**Comment by ki1729** [comment]
The tests have been failing and I did make some changes to them at one point. @hongli750210 how pressing is the issue for you folks?

**Comment by hongli750210** [comment]
@ki1729 This issue affects the pipeline weekly test for other clouds like US Gov and Azure China Cloud.

**Comment by hongli750210** [comment]
Close this issue, because it fixed by PR https://github.com/Azure/azure-sdk-for-java/pull/27840
