### ISSUE TITLE
[FEATURE REQ] Write a document writing guide for spring cloud azure project docs

### ISSUE THREAD

**Issue by jialigit** [Azure/azure-sdk-for-java#27515]
**Is your feature request related to a problem? Please describe.**

 Technical documentation should be concise and grammatically correct. 
 
 With the help of *vela* plugin, we can make a lot of these thing automatic. However, they cannot cover all of it.

**Describe the solution you'd like**

 Output a document writing guide.

**Purpose:**
To make our documentation  keep the same style,  we need to maintain a document writing guide line to keep from. 

This guide can be reference for document review checklist, which help keep our documents more readable and concise as if they are written by one writer.

For that in the nowadays, we can freely get some guides on tech document  guide on the internet, this guide should be an additional reference to the below references. That means we only need to address the special points that we need to use as our check list points.

**Reference:**
- [Microsoft manual of style](https://ptgmedia.pearsoncmg.com/images/9780735648715/samplepages/9780735648715.pdf)
- [google developer document guide](https://developers.google.com/style/word-list)

**Comment by chenrujun** [comment]
Hi, @jialigit , this issue is used to track the task of `Write a guideline for spring documents like reference doc`?

**Comment by jialigit** [comment]
> ask of `Write a guideline for spring documents like reference doc`?

yes. This is a consistent job. We may maintain a wiki doc as a reference to comply to。

**Comment by jialigit** [comment]
## Doc General Principles:
1. Doc structure 文章结构
    1.  Each Section should have a explanation for what it contains in the following.

2. Title 标题
    1. Title should be short and concise

3. Notes 说明
4. Singular and plural 单复数
5. Personal Pronouns 人称
6. Tense 时态
7. Terminology 专有术语
8. Consistency styles

## General Terminology
1. The and a/an

专有名词修饰不加定冠词， 如Spring Cloud Azure is xxx.
但是当该专有名词本身是限定词时除外。如， The Spring Cloud Azure configuration is xxx.

2. single/unique
3. word choice
  - refer vs see 
  - following vs below
  - on vs about
  - a vs one 
  - single vs unique 


## Doc optimization Examples:
1. short but informative
**original**:
> The DefaultAzureCredential is appropriate for most scenarios where the application 
is intended to ultimately be run in the Azure Cloud. 
> This is because the DefaultAzureCredential combines credentials commonly used to
 authenticate when deployed, with credentials used to authenticate in a development environment.

 **recommend**:
 > The DefaultAzureCredential provide a chain of authentication strategies which 
 makes it easy to be used both in production and development environment.

 2. descriptive and short
 **original**:
> Environment - The DefaultAzureCredential will read account information specified via environment 
variables and use it to authenticate.
Managed Identity - If the application is deployed to an Azure host with Managed Identity enabled, 
the DefaultAzureCredential will authenticate with that account.
IntelliJ - If the developer has authenticated via Azure Toolkit for IntelliJ, 
the DefaultAzureCredential will authenticate with that account.

**recommend**:
> Environment - Account information specified via environment variables used to authenticate.
Managed Identity -If deployed to an Azure host with Managed Identity enabled, 
the DefaultAzureCredential will authenticate with that account.
IntelliJ - Authentication information can be obtained via Azure Toolkit for IntelliJ if 
via which the developer has authenticated.

 3. logical
**original**:
> The authorization step requires that one or more Azure roles be 
assigned to the security principal. The roles that are assigned 
to a security principal determine the permissions that the principal will have.

**recommend**:
> The permissions one application can have to access Azure resources are based on roles, so sufficient 
roles should be assigned to a specific service principal correctly.

**Comment by stliu** [comment]
closing it, no one ask for it
