### ISSUE TITLE
Deal with properties which are deprecated or out-of-date.

### ISSUE THREAD

**Issue by backwind1233** [Azure/azure-sdk-for-java#27534]
<img width="757" alt="image" src="https://user-images.githubusercontent.com/4465723/157370537-827e4d2d-b4e5-4699-93e8-cdc297320076.png">

[link](https://github.com/Azure-Samples/azure-spring-boot-samples/blob/spring-cloud-azure_4.0.0-beta.4/aad/spring-cloud-azure-starter-active-directory/aad-resource-server-by-filter/src/main/resources/application.yml)

There are properties configured in [azure-spring-boot-samples](https://github.com/Azure-Samples/azure-spring-boot-samples/tree/spring-cloud-azure_4.0.0-beta.4), but out of date, not work as expected, we should address the issue and make each property reasonable.

**Comment by saragluna** [comment]
The 4.0.0 has been released, and we checked the properties before the release. Closing this issue now.
