### ISSUE TITLE
Broken link

### ISSUE THREAD

**Issue by pacharya-cloudknox** [Azure/azure-sdk-for-java#27548]
[Enter feedback here]

In Section "Authenticating in Azure with Managed Identity" -> there is a link "Enable managed identity for Azure resources". Click on it, you are asked for microsoft credentials. I am a microsoft employee so used mine. It takes me to a dead link

Two problems here -
1. what about non-microsoft employee?
2. why is it dead even with microsoft credentials?

Other links may be broken too, I did not check the whole document. pls check
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 35f40858-8637-e7db-8803-63fd8d5feeb4
* Version Independent ID: 17e4dc02-dbae-1d6b-ccf1-671b7a73b0f7
* Content: [Azure Identity client library for Java](https://docs.microsoft.com/en-us/java/api/overview/azure/identity-readme?view=azure-java-stable)
* Content Source: [docs-ref-services/latest/identity-readme.md](https://github.com/Azure/azure-docs-sdk-java/blob/master/docs-ref-services/latest/identity-readme.md)
* Service: **identity**
* Product: **azure**
* Technology: **azure**
* GitHub Login: @g2vinay
* Microsoft Alias: **vigera**

**Comment by joshfree** [comment]
Thanks for reporting this link @pacharya-cloudknox.

@g2vinay the link points to https://github.com/Azure/azure-sdk-for-java/wiki/Set-up-Your-Environment-for-Authentication#enable-managed-identity-for-azure-resources.  Can you please follow up?

/cc @JonathanGiles
