### ISSUE TITLE
[BUG] KeyVaultEnvironmentPostProcessor should not be enabled when only using spring-cloud-azure-stream-binder-eventhubs dependency

### ISSUE THREAD

**Issue by moarychan** [Azure/azure-sdk-for-java#27574]
**Describe the bug**
When including dependency `spring-cloud-azure-stream-binder-eventhubs`(the depdenency `com.azure.resourcemanager:azure-resourcemanager` will be included), 
then this transmission will turn on the `spring-cloud-azure-starter-keyvault-secrets` feature without explicitly applying its dependency, 
because the dependency `com.azure:azure-security-keyvault-secrets` will be included too. 

Related issue:
- https://github.com/Azure/azure-sdk-for-java/issues/27514

***Exception or Stack Trace***
N/A

**To Reproduce**
Run the sample, you will find the `KeyVaultEnvironmentPostProcessor` is executed.

***Code Snippet***
Try this sample https://github.com/Azure-Samples/azure-spring-boot-samples/blob/420a3aaa2fc5cd94f8ef1638ba387f9f36d6d131/eventhubs/spring-cloud-azure-stream-binder-eventhubs/eventhubs-binder/pom.xml.

**Expected behavior**
The `KeyVaultEnvironmentPostProcessor` should be disabled only when the pom file includes `spring-cloud-azure-stream-binder-eventhubs`. The dependency transmission 
of the keyvault sercert should be blocked to enable spring cloud azure autoconfigure library when using `com.azure.resourcemanager:azure-resourcemanager`

**Screenshots**
N/A

**Setup (please complete the following information):**
 - OS: [e.g. iOS] Windows
 - IDE: [e.g. IntelliJ] Intellij
 - Library/Libraries: [e.g. com.azure:azure-core:1.16.0 (groupId:artifactId:version)] com.azure.spring:spring-cloud-azure-stream-binder-eventhubs:4.0.0-beta.4
 - Java version: [e.g. 8] 11

If you suspect a dependency version mismatch (e.g. you see `NoClassDefFoundError`, `NoSuchMethodError` or similar), please check out [Troubleshoot dependency version conflict article](https://aka.ms/azsdk/java/dependency/troubleshoot) first. If it doesn't provide solution for the problem, please provide:
- verbose dependency tree (`mvn dependency:tree -Dverbose`)
- exception message, full stack trace, and any available logs

**Additional context**

**Information Checklist**
Kindly make sure that you have added all the following information above and checkoff the required fields otherwise we will treat the issuer as an incomplete report
- [x] Bug Description Added
- [x] Repro Steps Added
- [x] Setup information Added

**Comment by chenrujun** [comment]
Closing this issue in favor of #27392
