### ISSUE TITLE
[Epic] Sync MS docs and github.io

### ISSUE THREAD

**Issue by chenrujun** [Azure/azure-sdk-for-java#27570]
## Context
Now we have 2 places to hold Spring Cloud Azure reference doc:
1. Spring Cloud Azure MS docs: https://docs.microsoft.com/en-us/azure/developer/java/spring-framework/
2. Spring Cloud Azure github.io: https://microsoft.github.io/spring-cloud-azure/current/reference/html/index.html

## Goal
The contents in the 2 places should be synchronized.

### Principle when sync the MS docs and github.io
1. Single source of truth. MS docs is the single south of truth, sync MS docs to github.io. Even if there is contributor create PR to github.io, we should close that PR and update MS docs first. This has to be done manually. 
2. File format. github.io use .adoc and MS docs use .md file. There is no way to use `.md` file in github.io. https://github.com/Azure/azure-sdk-for-java/issues/27816
3. Links in the docs content. 
  3.1. Link to Spring Cloud Azure github.io is not allowed. Because it's weird that in MS docs, there is a link to GitHub page section.
  3.2. Link to MS docs is allowed. In the content, link to other MS docs pages is valid request.
  3.3. Link to sample repo is allowed. But we should use specific version in stead of main version. Because main branch is ways changing. To avoid 404 error, we should use 3.3.1 instead of 3.3.2:
    + 3.3.1 https://github.com/Azure-Samples/azure-spring-boot-samples/tree/spring-cloud-azure_4.0.0-beta.3/aad 
    + 3.3.2 https://github.com/Azure-Samples/azure-spring-boot-samples/tree/main/aad
4. Content breakdown
  4.1. For MS docs, @KarlErickson will investigate whether we can use same breakdown on MS docs and github.io.
  4.2. For github.io, now it only have 2 pages: main content page, and appendix page. We have 3 options, either is OK:
    + 4.2.1. Keep current implementation.
    + 4.2.2. Move appendix page into the main page, just keep one page. Just like spring boot: https://docs.spring.io/spring-boot/docs/2.6.4/reference/htmlsingle/#appendix.application-properties
    + 4.2.3. Each section have a single page. Just like Spring Security: https://docs.spring.io/spring-security/reference/features/index.html
5. Multiple version support. MS docs might have version support, although we are not currently using it in the Java space. @KarlErickson will investigate the current state of version support and whether we can use it, or will have to come up with a different solution. Proposed solutions are: 
  5.1. Just use separate articles, one for each version.
  5.2. Use zone pivots. We will start with one version only. so we do not need a solution here immediately.
6. URL Path in MS docs.
  6.1. Current path: https://docs.microsoft.com/en-us/azure/developer/java/spring-framework/
  6.2. Change to new path: https://docs.microsoft.com/en-us/azure/developer/java/spring-cloud-azure/
  6.3. After 6.2 worked, redirect 6.1 to 6.2.

### Tasks
 - [x] #27797
 - [x] #27816
 - [x] #28110
 - [x] #28050
 - [x] #28374

**Comment by hui1110** [comment]
Tasks are all done, now close this issue.
