### ISSUE TITLE
[FEATURE] mgmt, upgrade service with old api-version

### ISSUE THREAD

**Issue by weidongxu-microsoft** [Azure/azure-sdk-for-java#27617]
major
```
[Service] locks
    current: package-locks-2016-09
    latest: package-locks-2020-05

[Service] privatedns
    current: package-2018-09
    latest: package-2020-06

[Service] servicebus
    current: package-2017-04
    latest: package-2021-11
```

minor
```
[Service] monitor
    current: package-2021-04
    latest: package-2022-02

[Service] keyvault
    current: package-2019-09
    latest: package-2021-10
```

**Comment by weidongxu-microsoft** [comment]
locks updated

**Comment by XiaofeiCao** [comment]
servicebus package-2021-11: https://github.com/Azure/azure-sdk-for-java/pull/30270

**Comment by XiaofeiCao** [comment]
`package-2022-02` has been removed for `monitor`. 
@weidongxu-microsoft Should we use latest [`package-composite-v1`](https://github.com/Azure/azure-rest-api-specs/tree/main/specification/monitor/resource-manager#tag-package-composite-v1) instead?

**Comment by weidongxu-microsoft** [comment]
@XiaofeiCao Yes, we can use package-composite-v1. Monitor could be troublesome as it changes spec or behavior unexpectedly. You can try it, if not doable, fine to abort.

**Comment by XiaofeiCao** [comment]
`Microsoft.Insights/stable/2022-10-01/autoscale_API.json` not available: 

> com.azure.core.management.exception.ManagementException: Status code 400, "{"error":{"code":"NoRegisteredProviderFound","message":"No registered resource provider found for location 'eastus2' and API version '2022-10-01' for type 'autoscalesettings'. The supported api-versions are '2014-04-01, 2015-04-01, 2021-05-01-preview'. The supported locations are 'westus, eastus, northeurope, southcentralus, eastus2, centralus, australiasoutheast, brazilsouth, uksouth, ukwest, southindia, centralindia, westindia, canadaeast, canadacentral, westcentralus, westus2, koreasouth, koreacentral, australiacentral, australiacentral2, francecentral, francesouth, westeurope, eastasia, southeastasia, japaneast, japanwest, northcentralus, australiaeast, southafricanorth, uaecentral, uaenorth, switzerlandnorth, switzerlandwest, germanynorth, germanywestcentral, norwayeast, norwaywest, westus3, jioindiawest, swedencentral, eastus2euap, centraluseuap'."}}"

Will try with [package-2021-09](https://github.com/Azure/azure-rest-api-specs/tree/main/specification/monitor/resource-manager#tag-package-2021-09).

**Comment by weidongxu-microsoft** [comment]
> `autoscalesettings` not available:
> 
> > com.azure.core.management.exception.ManagementException: Status code 400, "{"error":{"code":"NoRegisteredProviderFound","message":"No registered resource provider found for location 'eastus2' and API version '2022-10-01' for type 'autoscalesettings'. The supported api-versions are '2014-04-01, 2015-04-01, 2021-05-01-preview'. The supported locations are 'westus, eastus, northeurope, southcentralus, eastus2, centralus, australiasoutheast, brazilsouth, uksouth, ukwest, southindia, centralindia, westindia, canadaeast, canadacentral, westcentralus, westus2, koreasouth, koreacentral, australiacentral, australiacentral2, francecentral, francesouth, westeurope, eastasia, southeastasia, japaneast, japanwest, northcentralus, australiaeast, southafricanorth, uaecentral, uaenorth, switzerlandnorth, switzerlandwest, germanynorth, germanywestcentral, norwayeast, norwaywest, westus3, jioindiawest, swedencentral, eastus2euap, centraluseuap'."}}"
> 
> Will try with [package-2021-09](https://github.com/Azure/azure-rest-api-specs/tree/main/specification/monitor/resource-manager#tag-package-2021-09).

Let's try ping the service and wait for them.

**Comment by XiaofeiCao** [comment]
Pinged and service did not deploy manifest change. They just started and will take about a week. So I'll wait till next week I guess.

**Comment by XiaofeiCao** [comment]
@weidongxu-microsoft What should we do about `locks`? It is still unavailable last time I checked.

**Comment by weidongxu-microsoft** [comment]
No need to bother that are not available.

You can close it if you think current one is good enough.

**Comment by XiaofeiCao** [comment]
All updated except `locks`.
