### ISSUE TITLE
[BUG] Arrays.copy t0 bytes

### ISSUE THREAD

**Issue by NeuroticStar** [Azure/azure-sdk-for-java#27678]
Memory Leak caused by cloning the message object multuple times causes heap size to grow enormously when the message size is large. 

in class - com.azure.messaging.servicebus.ServiceBusMessageSerializer

https://azuresdkartifacts.blob.core.windows.net/azure-sdk-for-java/test-coverage/azure-messaging-servicebus/com.azure.messaging.servicebus/ServiceBusMessageSerializer.java.html
![image](https://user-images.githubusercontent.com/55172435/158386445-c2be0342-e06f-4bd8-b25d-45ed1925a8ed.png)

The line `final byte[] body = brokeredMessage.getBody().toBytes();` copies the message twice and creates an additional byte array which isnt used but exists in memory that bulks up the heap space. 

This situation exacerbates when working with large sized messsages.

**Comment by joshfree** [comment]
@anuchandy could you please follow up?

/cc @Azure/azsdk-sb-java

**Comment by anuchandy** [comment]
Thanks for sharing this; I'll look and see if there is any specific reason for doing so; if not, I'll fix it.

**Comment by anuchandy** [comment]
Hello, I couldn't locate any byte-array copying happening in the below code. All the wrapper-type instances involved "refer" to the same byte array without copying.

>  final byte[] body = brokeredMessage.getBody().toBytes();

At the basic level, there is AmqpAnnotatedMessage owning the byte[] array. Inside [BinaryData.fromBytes](https://github.com/Azure/azure-sdk-for-java/blob/8864b50fa484cd4dcb79d8e6e1ddfcf9dc6d10ec/sdk/core/azure-core/src/main/java/com/azure/core/util/BinaryData.java#L373) this gets wrapped in a ByteArrayContent by [reference](https://github.com/Azure/azure-sdk-for-java/blob/8864b50fa484cd4dcb79d8e6e1ddfcf9dc6d10ec/sdk/core/azure-core/src/main/java/com/azure/core/implementation/util/ByteArrayContent.java#L29). The toBytes() in ByteArrayContent end up returning the same [reference](https://github.com/Azure/azure-sdk-for-java/blob/8864b50fa484cd4dcb79d8e6e1ddfcf9dc6d10ec/sdk/core/azure-core/src/main/java/com/azure/core/implementation/util/ByteArrayContent.java#L44), the `body` local variable refers this. Finally, the same reference (`body`) is passed to amqpMessage.setBody API and there is no copying there as well.
