### ISSUE TITLE
Add API in Azure key vault sdk to generate CEK / DEK

### ISSUE THREAD

**Issue by pchugh79** [Azure/azure-sdk-for-java#27674]
**Is your feature request related to a problem? Please describe.**
We follow encryption via envelope technique using key vault SDK. Our process had to generate CEK locally for cryptography operation and protect CEK by wrapping it with KEK. Generating keys through our process might not have sufficient entropy needed to generate safe keys.

**Describe the solution you'd like**
Add an api generateContentEncryptionKey / generateDataKey in azure key vault SDK.

**Describe alternatives you've considered**
Generate CEK/DEK using Java - KeyGenerator.

**Additional context**
Azure storage client library generates a content encryption key (CEK), which is a one-time-use symmetric key. https://docs.microsoft.com/en-us/azure/storage/common/storage-client-side-encryption?tabs=dotnet

**Information Checklist**
Kindly make sure that you have added all the following information above and checkoff the required fields otherwise we will treat the issuer as an incomplete report
- [x] Description Added
- [x] Expected solution specified

**Comment by joshfree** [comment]
@vcolin7 could you please follow up?

/cc @heaths

**Comment by heaths** [comment]
Managed HSM is supported by the Key Vault SDK and does support creating symmetric keys via "oct" or "oct-HSM" (same thing on Managed HSM, actually) which uses AES.

Adding @jlichwa for a feature request on Key Vault, if necessary, to support symmetric keys.

**Comment by jlichwa** [comment]
That request is slightly different, they just look to locally generate key using I believe local crypto libraries. DEK/CEK is not stored in MHSM or vault, it is just local key and has to be managed locally (local db etc..) - keys stored in vault are just used to encrypt that local key when at rest.

Not sure why they will need SDK for it, all RPs (Storage, SQL, CosmosDB.... Use crypto library directly).

**Comment by pchugh79** [comment]
Am not sure my issue is addressed here, i need a way to generate content/data encryption keys (DEK) which i have been generating locally and expiring the key in a day.
Can Azure Key Vault SDK provide such capability irrespective of the key type i create in key vault?

for Reference : We have been using AWS KMS too and get the DEK generated through their SDK
https://docs.aws.amazon.com/kms/latest/APIReference/API_GenerateDataKey.html

**Comment by heaths** [comment]
As long as you're using a cryptographically secure random number generator there's no difference than what the Key Vault SDK could or would provide, as we do not implement any cryptographic operations by design. Key Vault also doesn't support generating symmetric keys - only Managed HSM (supported by the Key Vault SDK) does, but that would probably be overkill since Azure services that support customer-managed keys (CMK) do this for you already.

Is there some reason you're generating your own DEKs instead of using CMK?

**Comment by pchugh79** [comment]
Doing cryptography operation with CMK would be a network call and can slow down if you have several fields to encrypt/decrypt in a single object.
Thats the reason we want to do this locally within our code, we cache the DEK and wrapped DEK with Azure key vault wrap operation, thus avoid all network calls here.

**Comment by heaths** [comment]
Thanks for clarifying that question. But are you already using a cryptographically secure RNG? If you're using bcrypt on Windows, or libssl on other platforms or even Windows you're already using a FIPS 140 validated cryptographic module. It's no different than what the SDK could or would use, and what the service uses.

**Comment by pchugh79** [comment]
We are currently using Java KeyGenerator to generate DEK keys. 
As i mentioned earlier, i see the Azure storage client library generates a content encryption key (CEK). 
I would definitely help if something like this is shipped along with Key vault SDK.

I have nothing more to add here and leave the decision to you.

**Comment by HakjunMIN** [comment]
@heaths Hey, please consider applying to generate DEK in SDK. It will be the best that DEK is automatically regenerated when auto rotating KEK in Azure Keyvault. AWS does now!

**Comment by jackrichins** [comment]
Just to clarify as the original comment mentioned concern about local resources - the request is to generate the DEK in the SDK (which will consume local resources) and not to generate the DEK in the AKV Service (which would incur extra roundtrips and consume centralized resources)?

**Comment by HakjunMIN** [comment]
@jackrichins Regardless DEK is managed in KV (only KEK should be managed in KV), my intent is [DEK should be easily generated by SDK](https://docs.aws.amazon.com/kms/latest/APIReference/API_GenerateDataKeyWithoutPlaintext.html) then [reencrypt DEK using KEK of KV in case of KEK rotation](https://docs.aws.amazon.com/kms/latest/APIReference/API_ReEncrypt.html). DEK location is not important, which can be in KV or another place. 

Above links is AWS way for your reference.

**Comment by heaths** [comment]
> my intent is DEK should be easily generated by SDK

What algorithm? How many bits? Using what RNG? All these are inputs that would be required to be robust (just like AWS's requires), and it would be far easier for users to just generate the DEK themselves. In a simple case for .NET, it's merely `RSA.Create()` with secure defaults on every platform. If a roundtrip to the service is not desired, leaving control for DEK generation to the user is much more robust and simple, yes?

**Comment by HakjunMIN** [comment]
DEK as you mentioned can be managed by customer side, but many users are already utilizing automatically generated DEK not just AWS, Alibaba and etc. as well for end to end encryption scenario including Key Rotation. Please read [AWS way](https://docs.aws.amazon.com/kms/latest/developerguide/rotate-keys.html) thoroughly to focus implementation experience for envelop encryption in other competitors.

Versioned KEK is hard to manage when rotation. What you said looks manual rotation. Version is able to attach intuitive tag like `latest`? No, current hash style revision should be managed for which version is last one at another place.

**Comment by heaths** [comment]
Some services like Storage do already support automatically encrypting storage using a KEK from Key Vault or Managed HSM: https://learn.microsoft.com/azure/storage/common/customer-managed-keys-overview

> [@HakjunMIN] Versioned KEK is hard to manage when rotation. What you said looks manual rotation.

Key Vault and Managed HSM do support automatic rotation, but if you only reference the key like `https://myvault.vault.azure.net/keys/my-key` it will always be the latest. Storage encryption - and any customer-rolled solutions - should use and store the versioned key e.g., `https://myvault.vault.azure.net/keys/my-key/a-version` to make sure they can decrypt. Old versions aren't deleted. AWS is no different in this regard; from the link you provided:

> When you use a rotated KMS key to encrypt data, AWS KMS uses the current key material. When you use the rotated KMS key to decrypt ciphertext, AWS KMS uses the version of the key material that was used to encrypt it.

If you used customer-managed keys for services like Storage, everything is automatic as well. If you want to roll your own, Azure [also supports that with Storage](https://learn.microsoft.com/azure/storage/blobs/encryption-customer-provided-keys), or you can do the same thing with a DEK you generated. Looking at https://docs.aws.amazon.com/kms/latest/developerguide/concepts.html#enveloping, I don't understand the gap. Azure provides the wrapping key (KEK) - their "KMS key" in that diagram - and you (or something, like Storage in the aforementioned docs) provides the DEK. Which KEK is used needs to be retained by something. In the case of Azure, we provide access to the actual version used. You could save that to a tag or other metadata to envelope, for example, and use that version to unwrap to decrypt.

**Comment by HakjunMIN** [comment]
Keep focusing on the point. Already knew automatic envelop encryption is supported in storage side, what I asked is same support in general message.

I've said it before and I'll say it again, AWS can decrypt a DEK created with an older version with just a key reference (with no version). It's supposed to auto-reference the version number of the older version.  Developers can just reference the key only and not worry about the version information.

I think what you said at the end could be an implementation idea in Azure SDK, but can you think about it a bit more for developers who are familiar with AWS KMS?
