### ISSUE TITLE
[FEATURE REQ] Sample for Daemon application that calls web APIs - Spring boot

### ISSUE THREAD

**Issue by chenrujun** [Azure/azure-sdk-for-java#27699]
This issue is copied from: https://github.com/microsoft/azure-spring-boot/issues/950
@RaghavThakkar

Hello,
I am looking for the sample in which my Deamon app calls web API.

https://docs.microsoft.com/en-us/azure/active-directory/develop/scenario-daemon-overview
My use case is very simple.

Deamon app acquire JWT token from the web API.

Once a token has been acquired web API verify that token using roles.

I could not find any sample of this flow.

Could not any sample of the in spring-boot.

Really appreciate it if you guide how to achieve the above solutions.

Thanks.

**Comment by chenrujun** [comment]
Hi, @RaghavThakkar.
Thanks for reaching out.

According to https://docs.microsoft.com/en-us/azure/active-directory/develop/scenario-daemon-overview,
there are 3 types of daemon: `Daemon web app`, `Daemon desktop app`, `Daemon web api`.
Which type is your Daemon app belong to?

**Comment by RaghavThakkar** [comment]
@chenrujun 

Thanks for the reply.

I am looking for the Deamon web api sample.

I could not verify the oauth 2.0 token when Deamon web api call to web api app. I am trying to achieve using spring security could not get any success.

It would be really appreciate if you could guide me how to do it?


Thanks.

**Comment by chenrujun** [comment]
@RaghavThakkar.

Now we have 3 samples:

1. [aad-web-application](https://github.com/Azure-Samples/azure-spring-boot-samples/tree/spring-cloud-azure_4.0.0-beta.3/aad/spring-cloud-azure-starter-active-directory/aad-web-application)
2. [aad-resource-server-obo](https://github.com/Azure-Samples/azure-spring-boot-samples/tree/spring-cloud-azure_4.0.0-beta.3/aad/spring-cloud-azure-starter-active-directory/aad-resource-server-obo)
3. [aad-resource-server](https://github.com/Azure-Samples/azure-spring-boot-samples/tree/spring-cloud-azure_4.0.0-beta.3/aad/spring-cloud-azure-starter-active-directory/aad-resource-server)

I think the second example (`aad-resource-server-obo`) is exactly what you want. But to run the whole process (`aad-web-application` -> `aad-resource-server-obo` -> `aad-resource-server`), you need to start all the 3 sample project.

Could you please read the `README` of the 3 samples, and try to run it?
If you have any problem when run the 3 samples, please let me know.

**Comment by RaghavThakkar** [comment]
Thank you
