### ISSUE TITLE
[BUG]- Slow performance when maxWaitTime provided in azure-messaging-eventhubs - EventProcessorClientBuilder

### ISSUE THREAD

**Issue by archana-sasidharan** [Azure/azure-sdk-for-java#27725]
We are consuming millions of data from Azure Event Hub and trying to achieve minimum 15k TPS. When maxWaitTime is provided , the performance drastically reduces to 100 TPS.  If we remove maxWaitTime, we are getting high performance

Code Snippet:
```
EventProcessorClientBuilder build = new EventProcessorClientBuilder()
				.credential(eventHubHostName, eventHubName, managedIdentityCredential)
				.consumerGroup(consumerGroupName)
				.prefetchCount(prefetchCount)
				.processEventBatch(processEventBatch, maxBatchSize, maxWaitTime)
				.processError(processError)
				.checkpointStore(new BlobCheckpointStore(blobContainerAsyncClient));
		EventProcessorClient eventProcessorClient = build.buildEventProcessorClient();
```

maxWaitTime - Also tried with values 1sec, 50ms,3ms
batchSize - 32

![Screenshot-maxWaitTime-PerformanceMetrics](https://user-images.githubusercontent.com/101692554/158745926-c99c826b-0c8c-40f0-af0f-590aab37567a.PNG)

Azure SDK (java) - azure-messaging-eventhubs
Version- 5.11.0

**Comment by joshfree** [comment]
@conniey @Azure/azsdk-sb-java could you please follow up on this performance tuning question from @archana-sasidharan?

**Comment by archana-sasidharan** [comment]
Any updates on it?

**Comment by vvamaraju** [comment]
@conniey/ @joshfree,  Kindly share if you have some update on the same. Thanking you

**Comment by conniey** [comment]
I am curious what the reason you're specifying maxWaitTime if the expected throughput is high? The heavy lifting is delegated to an operator in Project Reactor windowTimeout which under the hood has to create timed and sized windows. On that note, the windowTimeout operator is being re-written by the Project Reactor team due to some other issues. https://github.com/Azure/azure-sdk-for-java/issues/23950

**Comment by archana-sasidharan** [comment]
@conniey We cannot expect high throughput always. There are scenarios wherein event flow would be less. For example, if maxBatchSize is 2000 and number of events came in is only 200 then it will just wait for maxBatchSize to reach its size and then proceed and this would cause delay. In this context we thought of introducing maxWaitTime.

**Comment by conniey** [comment]
This issue feels familiar and may have been addressed in another issue I resolved, so apologies if these questions are duplicated:

1. What are your values for:
    * `maxBatchSize`
    * `maxWaitTime`
2. What does your `processEventBatch` function look like?
