### ISSUE TITLE
[FEATURE REQ]Azure key vault property source force refresh

### ISSUE THREAD

**Issue by maciejbak85** [Azure/azure-sdk-for-java#27731]
I am using spring boot with azure's keyvault

```
		<dependency>
			<groupId>com.azure.spring</groupId>
			<artifactId>azure-spring-boot-starter-keyvault-secrets</artifactId>
		</dependency>
```

but there is a problem, when I want to update secret.
How to force for example via rest api lets say, refresh of this value ?

```
@Value("${x-value}") private val xValue: String = "0"
```
thanks!

**Comment by chenrujun** [comment]
Hi, @maciejbak85 .

Thanks for reaching out.
Now `azure-spring-boot-starter-keyvault-secrets` does not have the feature of update manually.
We will consider whether we need to provide this feature, and how to provide this feature.

Now you can use `spring.cloud.azure.keyvault.secret.property-sources[].refresh-interval` to set auto refresh interval. The default value is 30 minutes.

Reference: https://microsoft.github.io/spring-cloud-azure/4.0.0-beta.3/4.0.0-beta.3/reference/html/index.html#configuration-4

**Comment by sy185109** [comment]
@chenrujun I am facing the same issue in the latest 4.3.0 version as well.
I have setup the refresh interval for azure keyvault and I was able to observe that the Lastest secret versions are fetched as per the Refresh.
But the issue is with the environment, While I am trying to access the evnironment.getProperty(), I still observe the old value. It is not refreshed in the environment somehow.

**Comment by chenrujun** [comment]
@sy185109 

When you execute `environment.getProperty("text")`, you can add a breakpoint here: https://github.com/Azure/azure-sdk-for-java/blob/spring-cloud-azure-autoconfigure_4.3.0/sdk/spring/spring-cloud-azure-autoconfigure/src/main/java/com/azure/spring/cloud/autoconfigure/keyvault/environment/KeyVaultOperation.java#L108-L110

Check whether the value is updated in `KeyVaultOperation`.

**Comment by stliu** [comment]
@sy185109 are u suing this https://github.com/ulisesbocchio/jasypt-spring-boot?

**Comment by sy185109** [comment]
> @sy185109 are u suing this https://github.com/ulisesbocchio/jasypt-spring-boot?

Yes, We are using this library.
