### ISSUE TITLE
Schema is not being cached when deserializing multiple messages having same schemaId

### ISSUE THREAD

**Issue by ankursaini2006** [Azure/azure-sdk-for-java#27735]
https://github.com/Azure/azure-sdk-for-java/blob/f29ecd7ce689c16e0b4b8e5b93d056beb189c3fb/sdk/schemaregistry/azure-data-schemaregistry-apacheavro/src/main/java/com/azure/data/schemaregistry/apacheavro/SchemaRegistryApacheAvroSerializer.java#L289

We are using SchemaRegistryApacheAvroSerializer in order to deserialize event received from eventhub but for each deserializing schema registry is called in order to fetch the schema for the given schema id. It is slowing down the processing. It would be better if schema is cached

**Comment by joshfree** [comment]
@conniey could you please follow upw ith @ankursaini2006
