### ISSUE TITLE
azure-cosmos-spark_3_2-12: ChangeFeedScanBuilder support for push down filters

### ISSUE THREAD

**Issue by michaelbpalmer** [Azure/azure-sdk-for-java#27758]
**Is your feature request related to a problem? Please describe.**
The Cosmos DB ChangeFeed is operates at the database level. I need to filter the change feed to a specific partition key before processing. Currently, this filter is being applied in Spark, which causes my Structured Streaming queries to run repeatedly, even when the filter statement filters 100% of the data in the microbatch.

If this were just happening for one streaming query it would be fine, but this empty microbatch is also causing my downstream queries to re-run. 

**Describe the solution you'd like**
If the ChangeFeedScanBuilder supported push down filters, this would filter all data before returning to Spark, which I believe would alleviate the above problem.

**Describe alternatives you've considered**
The only workaround that I can think of is to use indirection. Instead of having my downstream queries read from directly from Cosmos DB, I'll have the Cosmos DB readStream write the microbatch to disk. Then I can use a file source to read the microbatch files from disk. If the input change feed data is 100% filtered, I won't write anything to disk which would mean the empty batches wouldn't propagate through the rest of my streaming queries.

**Information Checklist**
Kindly make sure that you have added all the following information above and checkoff the required fields otherwise we will treat the issuer as an incomplete report
- [ X] Description Added
- [ X] Expected solution specified

**Comment by FabianMeiswinkel** [comment]
Filter push down for ChangeFeed is currently not enabled in the service - it will be added soon - although it will significantly reduce RU consumption only in certain configurations.
But I guess the main ask you are having here is to filter PartitionKeys/FeedRanges - so to do some filtering based on logical partition key value? If so it should be possible to expose and apply "spark.cosmos.partitioning.feedRangeFilter" setting for change feed as well - which would allow filtering down to a certain logical partition or a list of logical partitions.

**Comment by michaelbpalmer** [comment]
Thanks for your reply, Fabian! Yes, I'm already doing that with the following pyspark code:

`        spark.udf.registerJavaFunction(
            "get_feedrange_for_partition_key_value",
            "com.azure.cosmos.spark.udf.GetFeedRangeForPartitionKeyValue",
            StringType(),
        )
        feed_range_filter_df = spark.sql(
            f"SELECT get_feedrange_for_partition_key_value('{PK_DEFINITION}', '{pk_value}')"
        )
        feed_range_filter = str(feed_range_filter_df.collect()[0][0])

        df = (
            spark.readStream.format("cosmos.oltp.changeFeed")
            .option("spark.cosmos.accountEndpoint", db_uri)
            .option("spark.cosmos.accountKey", db_key)
            .option("spark.cosmos.database", "DbName")
            .option("spark.cosmos.container", "Container")
            .option("spark.cosmos.partitioning.feedRangeFilter", feed_range_filter)
            .option("spark.cosmos.read.inferSchema.enabled", False)
            .load()
        )
`

However, I'm still getting values with a different partition key. Do I have a bug someswhere?

**Comment by FabianMeiswinkel** [comment]
No, your code looks good. But the "spark.cosmos.partitioning.feedRangeFilter" setting right now is not applicable to the change feed "cosmos.oltp.changeFeed" DataSource - just for "cosmos.oltp". I can make the changes to add the scope to change feed DataSource as well.
I hope I will be able to include this in the next release (probably being released next week)

**Comment by michaelbpalmer** [comment]
Awesome, thanks Fabian!

**Comment by michaelbpalmer** [comment]
@FabianMeiswinkel With the code I posted above I am now getting the following error:

`Streaming exception No overlapping start token found for range 'NormalizedRange(,05C1C183E7E10808706D717472636367796C336C7777356565366C6472604570645466754264756A706F746035653562366563392E343667362E353A62312E623862312E36383131333936666738343200)'.
=== Streaming Query ===
Identifier: CosmosDbDocSetChangeFeedSource [id = 45f859a6-81a9-4eaa-b39a-c10ef0d943d1, runId = 3dc9dc2f-c416-40fa-92f5-fb7823c55637]
Current Committed Offsets: {com.azure.cosmos.spark.ChangeFeedMicroBatchStream@5226ab13: {"id":"spark.cosmos.changeFeed.offset.v1","state":"eyJWIjoxLCJSaWQiOiJXVnRkQU9FY2dIQT0iLCJNb2RlIjoiSU5DUkVNRU5UQUwiLCJTdGFydEZyb20iOnsiVHlwZSI6IkJFR0lOTklORyJ9LCJDb250aW51YXRpb24iOnsiViI6MSwiUmlkIjoiV1Z0ZEFPRWNnSEE9IiwiQ29udGludWF0aW9uIjpbeyJ0b2tlbiI6IlwiMzY3NjU4OFwiIiwicmFuZ2UiOnsibWluIjoiMDVDMUMxODNFN0UxMDgwODcwNkQ3MTc0NzI2MzYzNjc3OTZDMzM2Qzc3NzczNTY1NjUzNjZDNjQ3MjYwNDU3MDY0NTQ2Njc1NDI2NDc1NkE3MDZGNzQ2MDM1NjUzNTYyMzY2NTYzMzkyRTM0MzY2NzM2MkUzNTNBNjIzMTJFNjIzODYyMzEyRTM2MzgzMTMxMzMzOTM2NjY2NzM4MzQzMjAwIiwibWF4IjoiMDVDMUMxODNFN0UxMDgwODcwNkQ3MTc0NzI2MzYzNjc3OTZDMzM2Qzc3NzczNTY1NjUzNjZDNjQ3MjYwNDU3MDY0NTQ2Njc1NDI2NDc1NkE3MDZGNzQ2MDM1NjUzNTYyMzY2NTYzMzkyRTM0MzY2NzM2MkUzNTNBNjIzMTJFNjIzODYyMzEyRTM2MzgzMTMxMzMzOTM2NjY2NzM4MzQzMjAxIn19XSwiUmFuZ2UiOnsibWluIjoiIiwibWF4IjoiMDVDMURGRkZGRkZGRkMifX19","partitions":[{"range":["05C1C183E7E10808706D717472636367796C336C7777356565366C6472604570645466754264756A706F746035653562366563392E343667362E353A62312E623862312E36383131333936666738343200","05C1C183E7E10808706D717472636367796C336C7777356565366C6472604570645466754264756A706F746035653562366563392E343667362E353A62312E623862312E36383131333936666738343201"],"endLsn":3676588}]}}
Current Available Offsets: {com.azure.cosmos.spark.ChangeFeedMicroBatchStream@5226ab13: {"id":"spark.cosmos.changeFeed.offset.v1","state":"eyJWIjoxLCJSaWQiOiJXVnRkQU9FY2dIQT0iLCJNb2RlIjoiSU5DUkVNRU5UQUwiLCJTdGFydEZyb20iOnsiVHlwZSI6IkJFR0lOTklORyJ9LCJDb250aW51YXRpb24iOnsiViI6MSwiUmlkIjoiV1Z0ZEFPRWNnSEE9IiwiQ29udGludWF0aW9uIjpbeyJ0b2tlbiI6IlwiMzY3NjU4OFwiIiwicmFuZ2UiOnsibWluIjoiMDVDMUMxODNFN0UxMDgwODcwNkQ3MTc0NzI2MzYzNjc3OTZDMzM2Qzc3NzczNTY1NjUzNjZDNjQ3MjYwNDU3MDY0NTQ2Njc1NDI2NDc1NkE3MDZGNzQ2MDM1NjUzNTYyMzY2NTYzMzkyRTM0MzY2NzM2MkUzNTNBNjIzMTJFNjIzODYyMzEyRTM2MzgzMTMxMzMzOTM2NjY2NzM4MzQzMjAwIiwibWF4IjoiMDVDMUMxODNFN0UxMDgwODcwNkQ3MTc0NzI2MzYzNjc3OTZDMzM2Qzc3NzczNTY1NjUzNjZDNjQ3MjYwNDU3MDY0NTQ2Njc1NDI2NDc1NkE3MDZGNzQ2MDM1NjUzNTYyMzY2NTYzMzkyRTM0MzY2NzM2MkUzNTNBNjIzMTJFNjIzODYyMzEyRTM2MzgzMTMxMzMzOTM2NjY2NzM4MzQzMjAxIn19XSwiUmFuZ2UiOnsibWluIjoiIiwibWF4IjoiMDVDMURGRkZGRkZGRkMifX19","partitions":[{"range":["05C1C183E7E10808706D717472636367796C336C7777356565366C6472604570645466754264756A706F746035653562366563392E343667362E353A62312E623862312E36383131333936666738343200","05C1C183E7E10808706D717472636367796C336C7777356565366C6472604570645466754264756A706F746035653562366563392E343667362E353A62312E623862312E36383131333936666738343201"],"endLsn":3676588}]}}
`

Any help would be greatly appreciated! Thanks!
