### ISSUE TITLE
Improve readme after using terraform to run Azure AD related sample

### ISSUE THREAD

**Issue by chenrujun** [Azure/azure-sdk-for-java#27767]
### Context

After https://github.com/Azure-Samples/azure-spring-boot-samples/pull/217 merged, the Azure AD related samples' README need to update. Make it clear that we have 2 methods to run this sample. Customer can choose one of the 2 methods.

### Goal
Make is clear about the logics about create Azure resources.

### Solution

Here is on proposal: create a new file `create-Azure-resources-by-portal.md` and introduce this file in the README.md. 

- Update title in Readme:
	  - Running Sample With Terraform --> Creating Azure Resources by Terraform
	  - Running Sample Step by Step     --> Creating Azure Resources by Azure Portal
		  ...
- Check params are correct in README.md

**Comment by chenrujun** [comment]
Current issue depends on #27766

**Comment by stliu** [comment]
@chenrujun why we need to make this change for AAD samples?

is there any special in aad samples compare to others?

**Comment by chenrujun** [comment]
@stliu 

For other samples, `Create resource by Portal` related content is deleted. For AAD samples, `Create resource by Portal` related content was not deleted, because he think AAD related configuration is much more complex, it's useful to keep these contents. Now there are 2 ways to created resources. But the README didn't make it clear. 

In https://github.com/Azure-Samples/azure-spring-boot-samples/pull/217, @backwind1233 just add terraform related content. So I created this issue to track remaining task about improve the readme.
