### ISSUE TITLE
Move Migration Guide for 4.0 from github.io to MS docs.

### ISSUE THREAD

**Issue by chenrujun** [Azure/azure-sdk-for-java#27797]
- Link of [Migration Guide for 4.0 in github.io](https://microsoft.github.io/spring-cloud-azure/current/reference/html/appendix.html#migration-guide-for-4-0).
 - Link of [MS docs](https://docs.microsoft.com/en-us/azure/developer/java/spring-framework/)

Since migration guide is important to use version 4.0. We should move migration guide before sync all contents from github.io to MS docs.
 - [ ] Insert `Migration Guide for 4.0` between `Spring Cloud Azure` and `Getting Started Guide`.
![image](https://user-images.githubusercontent.com/13167207/159422171-22d50f68-3875-47d7-acfa-b83a368b5f5a.png)

 - [ ] Add description about migration guide in Spring Cloud Azure.
![image](https://user-images.githubusercontent.com/13167207/159422487-5818f263-3556-43ad-b963-ce77798d0245.png)

**Comment by chenrujun** [comment]
Hi, @KarlErickson, do you have any concerns about this issue?

**Comment by KarlErickson** [comment]
Hi @chenrujun - I've replied on Teams. Thanks!

**Comment by chenrujun** [comment]
@KarlErickson Got it. Thank you for your reply.
Closing this issue, because the PR of all contents (containing migration guide 4.0) is already created.

cc: @stliu , FYI.
