### ISSUE TITLE
Make getting started guides follow the same principal

### ISSUE THREAD

**Issue by chenrujun** [Azure/azure-sdk-for-java#27795]
## Problem

Current [Getting Started Guides](https://docs.microsoft.com/en-us/azure/developer/java/spring-framework/) haven't follow the same pattern. 

## Goal

All guides should follow these principals:

 - Using BOM for dependencies management
 - Using DefaultAzureCredential as much as possible and promote MSI
 - Using Azure Spring Cloud for hosting

**Comment by stliu** [comment]
I'm not sure what's the goal of this issue, it simply list some items here

**Comment by chenrujun** [comment]
@stliu . I updated the title and description.

**Comment by chenrujun** [comment]
Closing this issue in favor of https://github.com/Azure/azure-sdk-for-java/issues/27798
