### ISSUE TITLE
[FEATURE REQ] Allow not spawning new threads on each ServiceBusProcessorClient instance start.

### ISSUE THREAD

**Issue by LukaszGebel-TomTom** [Azure/azure-sdk-for-java#27805]
**Is your feature request related to a problem? Please describe.**
When ServiceBusProcessorClient instance is started (start() method) it creates a new thread (Executors.newSingleThreadScheduledExecutor()). While having significant number of queues (assume hundreds) it means significant number of threads spawned. In some scenarios it's sufficient to use a shared threadpool rather than having a thread per client.

**Describe the solution you'd like**
Extend ServiceBusProcessorClientBuilder so it allows to set executor (threadpool) that can be reused by different instances of ServiceBusProcessorClient throughout the application.

**Describe alternatives you've considered**
Use/allow using static threadpool for ServiceBusProcessorClient.

**Additional context**
Use case: significant number of queues that are not heavily used, thus they don't need a dedicated thread.

**Information Checklist**
Kindly make sure that you have added all the following information above and checkoff the required fields otherwise we will treat the issuer as an incomplete report
- [X] Description Added
- [X] Expected solution specified

**Comment by ki1729** [comment]
Will do Josh!

**Comment by ki1729** [comment]
@LukaszGebel-TomTom Can you please help me understand your scenario some more? Are you looking to share a threadpool among many (hundreds) Processor clients and use the shared threadpool to actually do the processing of messages? 

Or do you just want to replace the call to create a new executor inside ProcessorClient.start() with a shared pool?
If it is the instance that you have mentioned,

> When ServiceBusProcessorClient instance is started (start() method) it creates a new thread (Executors.newSingleThreadScheduledExecutor()).

Here the thread is used to monitor the state of the connection every 10 seconds and restart the processor if needed, and is not actually used to process any of the messages. We are looking in replacing this executor with reactor call.

**Comment by LukaszGebel-TomTom** [comment]
Hi @ki1729, replacing this executor with reactor call is ok as well. Thank you.

**Comment by ki1729** [comment]
Thank you for the update @LukaszGebel-TomTom , will update the issue when we have the change ready to merge

**Comment by LukaszGebel-TomTom** [comment]
Thank you @ki1729.
