### ISSUE TITLE
Make all configurable properties exist in reference doc's appendix

### ISSUE THREAD

**Issue by chenrujun** [Azure/azure-sdk-for-java#27813]
### Context
Now in [reference doc's appendix](https://microsoft.github.io/spring-cloud-azure/4.0.0/reference/html/appendix.html##configuration-properties), the properties table was created by by [exec-maven-plugin.](https://github.com/microsoft/spring-cloud-azure/blob/spring-cloud-azure_4.0.0/docs/pom.xml#L107) 

### Problem
Some configurable property is not exist in the appendix. For example: `spring.cloud.azure.keyvault.secret.property-sources[].client.logging.allowed-header-names`. 

### Goal
Make all configurable properties exist in reference doc's appendix

**Comment by hui1110** [comment]
When the property prefix contains `List` or `Map`, the prefix in `spring-configuration-metadata.json` is not complete. The complete prefix needs to be added to [additional-spring-configuration-metadata.json](https://github.com/Azure/azure-sdk-for-java/blob/main/sdk/spring/spring-cloud-azure-autoconfigure/src/main/resources/META-INF/additional-spring-configuration-metadata.json) manually.

**Comment by hui1110** [comment]
Fix PR: https://github.com/Azure/azure-sdk-for-java/pull/28589

**Comment by hui1110** [comment]
Fix [PR ](https://github.com/Azure/azure-sdk-for-java/pull/28589)merged, now close this issue.
