### ISSUE TITLE
Make sure all properties' default value is right

### ISSUE THREAD

**Issue by chenrujun** [Azure/azure-sdk-for-java#27812]
# Problem

Now in Spring Cloud Azure reference doc, some properties' default value is not right

For example:

https://microsoft.github.io/spring-cloud-azure/4.0.0-beta.4/4.0.0-beta.4/reference/html/index.html#configuration-5

![image](https://user-images.githubusercontent.com/13167207/159600053-c2c99be8-bcdc-4d29-b30d-b2fa8c87d929.png)

1. All boolean property should have a default value.
2. All properties with default value should be written in properties table.

# Goal 
Make sure all properties' default value is right.

**Comment by hui1110** [comment]
The default values of properties in the spring cloud azure reference documentation and appendix have been checked, and no wrong default values have been found, but some properties in the property table have no default values, which will be added in this [PR](https://github.com/microsoft/spring-cloud-azure/pull/931).

**Comment by hui1110** [comment]
In this [PR](https://github.com/microsoft/spring-cloud-azure/pull/933), properties with missing default values have been added, now close this issue.
