### ISSUE TITLE
[FEATURE REQ] core, allow specifying Hypertext Transfer Protocol HTTP/1.1 or HTTP/2

### ISSUE THREAD

**Issue by weidongxu-microsoft** [Azure/azure-sdk-for-java#27814]
**Is your feature request related to a problem? Please describe.**

ARM throttling has large impact on customer on management-plane, and HTTP/1.1 and HTTP/2 affect the behavior of ARM throttling (multiple endpoint vs single endpoint as multiplex).
Hence would like to explicitly configure the protocol, if HTTP client supports both protocol.

**Describe the solution you'd like**

Allowing configuration of Hypertext Transfer Protocol HTTP/1.1 or HTTP/2 in either azure-core or implementation package of HTTP client.

**Describe alternatives you've considered**

**Additional context**

**Information Checklist**
Kindly make sure that you have added all the following information above and checkoff the required fields otherwise we will treat the issuer as an incomplete report
- [x] Description Added
- [x] Expected solution specified

**Comment by alzimmermsft** [comment]
Initial thought is to expose this through the HttpClient builders in Netty and OkHttp, and then later if needed propagate this up to HttpClientOptions to make configuring this easier.
