### ISSUE TITLE
[Epic] Improve Spring Cloud Azure 4.0 Properties

### ISSUE THREAD

**Issue by chenrujun** [Azure/azure-sdk-for-java#27822]
### Context

Now there are a lot of things can be done to improve the property list in Spring Cloud Azure reference doc.

### Goal 
Fix all problems about Spring Cloud Azure properties.

### Solution

 - [x] #27813
 - [x] #27812
 - [x] #27810
 - [x] #28050

**Comment by hui1110** [comment]
Tasks are all done, now close this issue.
