### ISSUE TITLE
[FEATURE REQ] Provide all exposed Service Bus Message Headers in Spring Cloud Azure Stream Binder for Service Bus

### ISSUE THREAD

**Issue by TechPreacher** [Azure/azure-sdk-for-java#27832]
**Is your feature request related to a problem? Please describe.**
Service Bus adds a number of headers to messages as outlined [here](https://docs.microsoft.com/en-us/rest/api/servicebus/message-headers-and-properties). We would like to use these headers, namely the "DeliveryCount" in one of our projects.

**Describe the solution you'd like**
In spring-cloud-azure-starter-stream-servicebus version 4.0.0-beta3, the org.springframework.messaging.Message.getHeaders() method already returns a org.springframework.messaging.MessageHeaders object. Unfortunately, these headers lack a lot of the values provided by Azure Service Bus.

**Describe alternatives you've considered**
There is no clear alternative in this case.

**Additional context**
See the org.springframework.messaging.MessageHeaders definition for exposed headers compared to the [actual headers exposed by Service Bus](https://docs.microsoft.com/en-us/rest/api/servicebus/message-headers-and-properties)

** Note **
This feature request is for documentation purposes and was addressed in 4.0.0-beta4.

**Information Checklist**
Kindly make sure that you have added all the following information above and checkoff the required fields otherwise we will treat the issuer as an incomplete report
- [x] Description Added
- [x] Expected solution specified

**Comment by TechPreacher** [comment]
@yiliuTo : This is the feature you added in 4.0.0-beta4. Thanks for that! Can I ask you to resolve this feature request?

**Comment by yiliuTo** [comment]
Hi @TechPreacher thanks for tracking this, and I also created an issue #27620 for it and resolve this in pr #27675.

**Comment by yiliuTo** [comment]
Close for the issue has been resolved.

**Comment by TechPreacher** [comment]
Thanks again, @yiliuTo !
