### ISSUE TITLE
Tasks for Spring Boot:3.0.0-M2 (3.0.0 GA on 2022-11-24) 

### ISSUE THREAD

**Issue by chenrujun** [Azure/azure-sdk-for-java#27865]
### Context 
Refs: https://github.com/Azure/azure-sdk-for-java/wiki/Spring-Cloud-Azure-tasks-for-a-new-Spring-Boot-release

### Goal 

Make sure Spring Cloud Azure libraries are compatible with spring-boot:3.0.0-M2

### Solution

- [x] Create a new issue to track the following tasks. Sample: [#27864](https://github.com/Azure/azure-sdk-for-java/issues/27864).
- [ ] Create **draft** PR to upgrade external dependencies' version according to spring-boot-dependencies and spring-cloud-dependencies. Refer to [related readme](https://github.com/Azure/azure-sdk-for-java/blob/aec4c6247ba7ba4de57dd866e3f5511ca4fbd387/sdk/spring/scripts/README.md)
- [ ] Run tests by commands:
  - `/azp run java - spring - tests`
  - `/azp run java - cosmos - tests`
  - `/azp run java - keyvault - tests`
- [ ] Fix the test failures.
- [ ] Close draft PR.

**Comment by stliu** [comment]
@chenrujun @moarychan  is this issue still valid?

**Comment by moarychan** [comment]
Confirmed, the [6.0.0-beta.3](https://aka.ms/spring/docs/6.0.0-beta.3) is the latest version to support Spring Boot 3.
