### ISSUE TITLE
[FEATURE REQ] Custom ObjectMapper configuration for CosmosPagedFlux

### ISSUE THREAD

**Issue by konyk** [Azure/azure-sdk-for-java#27877]
I was not able or there is no configuration possibility of my own ObjectMapper, the following source code:

```
CosmosAsyncContainer cosmosAsyncContainer = ascCosmosAsyncClient.getDatabase(cosmosDbConfig.getDatabaseName())
        .getContainer(cosmosDbConfig.getCollectionStockContainerName());

    CosmosPagedFlux<JsonNode> cosmosPagedFlux = cosmosAsyncContainer
        .queryItems(String.format("SELECT * FROM c WHERE c.someId = '%s' AND c.someSecondId = '%s'"
, someId, someSecondId),
            JsonNode.class);
```

I'm currently using JsonNode because otherwise the date can't be deserialised.
For Spring Data I'm using my own object mapper configuration:

```
@Bean(Constants.OBJECT_MAPPER_BEAN_NAME)
  public ObjectMapper cosmosObjectMapper() {
    ObjectMapper objectMapper = new ObjectMapper();
    JavaTimeModule javaTimeModule = new JavaTimeModule();
    javaTimeModule.addDeserializer(OffsetDateTime.class, new OffsetDateTimeDeserializer());
    javaTimeModule.addSerializer(OffsetDateTime.class, new CustomJsonSerializer());
    objectMapper.registerModule(javaTimeModule);
    objectMapper.disable(SerializationFeature.WRITE_DATES_AS_TIMESTAMPS);
    objectMapper.configure(DeserializationFeature.FAIL_ON_UNKNOWN_PROPERTIES, false);
    return objectMapper;
  }
```

I would like to have a way to use my own ObjectMapper configuration for this kind of queries.

As already written, I used JsonNode and then converted it to POJO.

**Comment by kushagraThapar** [comment]
@konyk  - I believe you are already customizing it correctly, as you can see in the example here - https://github.com/Azure/azure-sdk-for-java/tree/main/sdk/cosmos/azure-spring-data-cosmos#spring-boot-starter-data-rest

Wondering, if you are not getting the serialization / deserialization working correctly or not. What is the issue that you are facing?

**Comment by konyk** [comment]
That is correct the code shown above is working. I would like to have a way to use my own ObjectMapper for cosmosAsyncContainer. This would allow you to deserialise directly in POJOS.

 ```
CosmosPagedFlux<MyPojo> cosmosPagedFlux = cosmosAsyncContainer
        .queryItems(String.format("SELECT * FROM c WHERE c.someId = '%s' AND c.someSecondId = '%s'"
, someId, someSecondId),
            MyPojo.class);
```

**Comment by konyk** [comment]
okay, sounds good, waiting for implementation.

**Comment by theodor-franke** [comment]
we are facing the same problem. we would love to see this implemented.

**Comment by TheovanKraay** [comment]
Will review adding this in planning for next semester work.

**Comment by kushagraThapar** [comment]
FYI, this is currently being worked on. 
cc: @FabianMeiswinkel
