### ISSUE TITLE
Investigate whether Dependabot can be used to upgrade external dependencies' version

### ISSUE THREAD

**Issue by chenrujun** [Azure/azure-sdk-for-java#27871]
Here is the link to Dependabot: https://github.com/dependabot

Now we use script in `sdk/spring/scripts` to update external dependencies' version. Investigate whether Dependabot can be used the replace these scripts.

Related issue: https://github.com/Azure/azure-sdk-for-java/issues/27427

**Comment by chenrujun** [comment]
Hi, @stliu , I assigned this issue to you because you are doing related investigation.
Any updates can be updated here.

**Comment by stliu** [comment]
where is this request came from?

**Comment by stliu** [comment]
SDK team is doing some research on this area, we may get away from external dependencies
