### ISSUE TITLE
[BUG] Operations performed using the KeyClient with invalid configuration take enormous amount of time

### ISSUE THREAD

**Issue by ArturPalka** [Azure/azure-sdk-for-java#27905]
**Describe the bug**
When the KeyClient is not properly configured it takes about 1 min 35 sec to get a response from the Azure service. Using the old client: com.microsoft.azure.management.keyvault.Vault I didn't encounter such problems, responses with error messages were immediate.

***Exception or Stack Trace***
The exception from my test that occurred after 1 min 35 sec:
```
com.microsoft.aad.msal4j.MsalServiceException: AADSTS7000215: Invalid client secret provided. Ensure the secret being sent in the request is the client secret value, not the client secret ID, for a secret added to app 'c8e8540f-4f15-4b6b-8862-3ccdb389e35d'.
Trace ID: c662daea-1a1a-48d9-a27d-78f9472b7d01
Correlation ID: c29184e8-2ebd-4b21-9c4f-a736bdde7af3
Timestamp: 2022-03-28 14:57:30Z
```

**To Reproduce**
1. Configure the KeyClient with an invalid client secret.
2. Run an operation on it - it can be for example listing properties of keys.
3. It takes on average 1 min 35 sec to finish this operation.

***Code Snippet***
```
import com.azure.identity.ClientSecretCredentialBuilder;
import com.azure.security.keyvault.keys.KeyClient;
import com.azure.security.keyvault.keys.KeyClientBuilder;
import org.junit.jupiter.api.Test;

import java.util.stream.Collectors;

class KeyClientIT {

    @Test
    void operations_on_invalid_key_client_take_too_much_time(){
        // given
        String keyVaultName = System.getenv("KEY_VAULT_NAME");
        String clientId = System.getenv("CLIENT_ID");
        String tenantId = System.getenv("TENANT_ID");
        String invalidClientSecret = "INVALID-CLIENT-SECRET";
        KeyClient keyClient = new KeyClientBuilder()
                .vaultUrl("https://" + keyVaultName + ".vault.azure.net/")
                .credential(new ClientSecretCredentialBuilder()
                        .clientId(clientId)
                        .tenantId(tenantId)
                        .clientSecret(invalidClientSecret)
                        .build())
                .buildClient();

        // when
        keyClient.listPropertiesOfKeys()
                .stream()
                .collect(Collectors.toList());
    }
}
```

**Expected behavior**
I'd like to get an error message in a reasonable amount of time, for example: 5 seconds.

**Setup:**
 - OS: macOS Big Sur
 - IDE: IntelliJ IDEA 2021.2.3
 - Library/Libraries: com.azure:azure-security-keyvault-keys:4.3.8
 - Java version: 11.0.2

**Information Checklist**
- [X] Bug Description Added
- [X] Repro Steps Added
- [X] Setup information Added

**Comment by joshfree** [comment]
@vcolin7 can you please investigate this reported performance issue?

/cc @g2vinay @billwert for ClientSecretCredential

**Comment by ArturPalka** [comment]
@joshfree @vcolin7 How are things going?

**Comment by vcolin7** [comment]
Hi @ArturPalka, sorry for the late response. This looks to be related to how `RetryPolicy` handles exceptions:

By default, a `RetryPolicy` is created with a `RetryStrategy` that will signal to retry [only when receiving some specific HTTP status codes](https://github.com/Azure/azure-sdk-for-java/blob/1f4122ebe86d06500018bbebe6fd4b15774fbfc0/sdk/core/azure-core/src/main/java/com/azure/core/http/policy/RetryStrategy.java#L45), however, it **always** signals to retry if an exception is thrown somewhere along the HTTP pipeline. Given that for authentications errors (like `401` in this case) an `MsalServiceException` is created by MSAL (an Azure Identity dependency), the `RetryPolicy` always attempts to retry the service call until the max number of retries is reached.

I'll pass this along to the team and see what we can do about it. Again, thanks for reporting this and for your patience :)

**Comment by ArturPalka** [comment]
HI @vcolin7! Any news regarding this matter?

**Comment by vcolin7** [comment]
Hey @ArturPalka, yes, we should be including a fix in our next release of Azure Core (early next month), which should alleviate this problem with all our SDKs.

**Comment by jil096** [comment]
hi I see the above pr is closed and wonder if the fix has been included in recent releases. I'm encountering a similar issue with com.azure:azure-security-keyvault-keys:4.5.2 library.

**Comment by izziegeez** [comment]
@vcolin7 Could you help take a look at what @jil096's question above? Thank you!

**Comment by vcolin7** [comment]
Sure thing @jil096, @izziegeez

**Comment by izziegeez** [comment]
@vcolin7 hi, we were wondering why https://github.com/Azure/azure-sdk-for-java/pull/29352 wasn't merged? Seems like your updated retry strategy would solve our problem

**Comment by vcolin7** [comment]
Hi @izziegeez, sorry for the late reply. The PR you mentioned was not merged at the time because, after some talks, the team decided it was better to first ensure any authentication exceptions coming from the MSAL library were properly wrapped in our own exception types to then only retry for the right types here. Unfortunately, other work took priority over this but I can now spend some cycles on it and, hopefully, get you guys a fix for next month's release.

**Comment by shevah** [comment]
I am still facing this issue with `AzureResouceManager` and `azure-identity:1.9.0`
