### ISSUE TITLE
Querying ACR repositories and tag with managed identity

### ISSUE THREAD

**Issue by markoharness** [Azure/azure-sdk-for-java#27930]
**Query/Question**
Hi, I am trying to query ACR details (registries, repositories and tags) with the managed identity via SDK or REST api.
So far I have only managed to retrieve registries for specific subscription. Is there ant way of querying repositories or tags using managed identity via SDK or direct REST api?.

***Why is this not a Bug or a feature Request?***
It is just unclear to me if this is possible or not. 

**Setup (please complete the following information if applicable):**
If this is of relevance
 - Library/Libraries: azure-mgmt-containerregistry:1.31.1 and azure-mgmt-msi:1.31.1
 
 **Information Checklist**
 Kindly make sure that you have added all the following information above and checkoff the required fields otherwise we will treat the issuer as an incomplete report
- [X] Query Added
- [X] Setup information Added

**Comment by joshfree** [comment]
Hi @markoharness, @weidongxu-microsoft will be able to follow up shortly.

/cc @pallavit 

Thanks,
Josh

**Comment by weidongxu-microsoft** [comment]
@markoharness

First please try use new SDK here. Most things should be same https://aka.ms/azsdk/java/mgmt (and curious how do you pick 1.31.1, any doc mention that version?)

On the other hand, querying repositories and tags under a container registry appears not belong to management SDK at all. One usually do this via `docker` client?

Here is a doc on managed identity for ACR https://docs.microsoft.com/azure/container-registry/container-registry-authentication-managed-identity#example-2-access-with-a-system-assigned-identity
Note it uses CLI and then still docker to pull images.

**Comment by markoharness** [comment]
@weidongxu-microsoft code I am currently working on has those libs and I wanted to be sure if there is a way of querying repos and tags via any azure libs is possible.

I have found that these libs (https://docs.microsoft.com/en-us/java/api/overview/azure/containers-containerregistry-readme?view=azure-java-stable) do support querying repos and tags from ACR. I will try and use these.

I do have another question regarding creation of kubernetes imagePullSecret used for pulling of the image artifact.

I can generate from the code imagePullSecret if I use details of Service Principal which authenticate with clientId(appId) and a password.

Is there a way to generate imagePullSecret using details from Service Principal which uses certificate for authentication? Any resource on that would be greatly appreciated.

**Comment by weidongxu-microsoft** [comment]
@pallavit  and @alzimmermsft for `azure-containers-containerregistry` lib.
```
<dependency>
  <groupId>com.azure</groupId>
  <artifactId>azure-containers-containerregistry</artifactId>
  <version>1.0.3</version>
</dependency>
```

**Comment by weidongxu-microsoft** [comment]
@markoharness 

Could you let us know which lib you are using for kubernetes imagePullSecret? I will try to connect you with the best person who can help.

**Comment by markoharness** [comment]
@weidongxu-microsoft there is no lib.
I am using service principal clientId as username and its password to generate a dockercfg secret kind.

the imagePullSecret I am generating is 
{"ACR url":{"username":"client id value","password":"password value"}}
as base64 encoded string.

I would need to generate this with details from Service Principal with certificate. We do not have password to use while generating this. So question is how can we do it? Is it even possible to generate it?

**Comment by weidongxu-microsoft** [comment]
@markoharness 

Do you mean create a `kubernetes.io/dockerconfigjson` type secret for Kubernetes, from service principal that having access to the ACR?

It appears to be possible according to https://docs.microsoft.com/azure/container-registry/container-registry-auth-service-principal#use-with-certificate, which uses CLI.
But I do not know how CLI convert the certificate to something that can be used for docker.

We might need to loop in ACR service for guide. But service response on github issue is likely slow.

**Comment by markoharness** [comment]
@weidongxu-microsoft 

I meant `kubernetes.io/dockercfg`, but `kubernetes.io/dockerconfigjson` type secret would also work for my use case.

I did try creating kubernetes.io/tls type secret but got "unauthorized: authentication required, visit https://aka.ms/acr/authorization for more information."

How do I create IcM ticket?

**Comment by weidongxu-microsoft** [comment]
@markoharness 
I think it is under "Help + support" of Azure Portal.

I've looped in service in this issue as well.
