### ISSUE TITLE
Solidfy Java API deprecation guidelines

### ISSUE THREAD

**Issue by ki1729** [Azure/azure-sdk-for-java#27939]
**Query/Question**
As of the day of creation of this ticket, we have a limited document on deprecation - Link - https://github.com/Azure/azure-sdk-for-java/wiki/Deprecation 
Where the stated goal is to never release a client library that is breaking, except in certain pre-agreed releases.

This leaves a gap when it comes to other information like 

- What are the release guidelines for releasing such a breaking change?
- What would the timeline be for such a release?
- What are the places where this should be documented - JavaDoc, Samples ?
- What communication mediums will be used to send out the information on the release to customers - blog posts, tweets?
- What will our support strategy be for customers using the deprecated API?

***Why is this not a Bug or a feature Request?***
This issue is to track a gap in our change process, which is not a bug or a feature

 **Information Checklist**
 Kindly make sure that you have added all the following information above and checkoff the required fields otherwise we will treat the issuer as an incomplete report
- [x] Query Added
- [x] Setup information Added - N/A

**Comment by ki1729** [comment]
@joshfree Created this issue to track our deprecation process

**Comment by JonathanGiles** [comment]
The guidance to this point is still the same - we don't make breaking changes. Deprecated API is allowed, and it is supported as per the standard support that is offered for any of our library APIs. When we deprecate API, we do not target it for removal in a particular future release. Removal of deprecated API will be communicated to users well in advance, but there are no plans to do any removal in the foreseeable future. My expectation that a breaking change release such as this will be communicated through all the mediums available to us.
