### ISSUE TITLE
[Docs] Migrate azure-cognititiveservices-computervision from legacy pipeline to current

### ISSUE THREAD

**Issue by scbedd** [Azure/azure-sdk-for-java#27964]
This is in context of Azure/azure-docs-sdk-java.

- Currently exists in `main-source-based`
- [Repo.json config](https://github.com/Azure/azure-docs-sdk-java/blob/246bc9682e0d008a1a3ab92209d2977fef526499/repo.json#L11)
- [Code2yaml config](https://github.com/Azure/azure-docs-sdk-java/blob/246bc9682e0d008a1a3ab92209d2977fef526499/code2yaml.json#L15)

We want to migrate this package to the packages.json/maven method instead of leaving it on source-based.

We want to target version `1.0.9-beta`. @samvaity confirmed that the [SOURCES jar is present](https://mvnrepository.com/artifact/com.microsoft.azure.cognitiveservices/azure-cognitiveservices-computervision/1.0.9-beta).

**Comment by scbedd** [comment]
hey @sima-zhu  can you please take a look at this when you have a couple minutes?

**Comment by sima-zhu** [comment]
We can use source jar for computer vision. If they don't use our release pipeline, then every time they want to update the version, they have to manually submit the PR for updates. 
https://github.com/Azure/azure-docs-sdk-java/pull/2192

**Comment by danieljurek** [comment]
@sima-zhu -- We may need to do additional configuration to keep this from begin overwritten by content in `main-source-based`

**Comment by danieljurek** [comment]
I think in here -- https://github.com/Azure/azure-docs-sdk-java/blob/main/temporary-src-based-yml/migration.json#L21

**Comment by sima-zhu** [comment]
https://github.com/Azure/azure-docs-sdk-java/pull/2193/files
