### ISSUE TITLE
Regenerate with New Autorest Features

### ISSUE THREAD

**Issue by alzimmermsft** [Azure/azure-sdk-for-java#27961]
Client SDKs that are using Autorest to generate code should add two new feature flags to the Autorest configuration:

```
custom-strongly-typed-header-deserialization: true
generic-response-type: true
```

**Custom Strongly Typed Header Deserialization**

Custom strongly typed header deserialization indicates to Autorest to generate strongly-typed header objects, classes that have properties that map to headers returned by a response with non-string types such as boolean, byte[], int, etc instead of being a String, without using Jackson for deserialization. This provides two improvements where Jackson is no longer being used, and due to that there is less usage of reflection in the SDK, and a non-negligible performance improvement as the Jackson code path has to serialize `HttpHeaders` into a JSON object and then deserialize the JSON object to the strongly-typed headers type, [this PR](https://github.com/Azure/azure-sdk-for-java/pull/27369#issuecomment-1069569166) comment contains more information about the performance improvement.

When this feature is enabled strongly-typed header types will have a new public constructor added to the class that takes `HttpHeaders` as the only parameter. Within the constructor each property will be retrieved and converted to the type it represents, doing this will ensure that if any exceptions occur during creation of the type they will occur at the same point in code as when Jackson was being used to create the type. Additionally, with the `HttpHeaders` constructor mocking strongly-typed header objects will be easier as it won't require using reflection anymore. No other API or behavioral changes will happen.

**Generic Response Type**

Generic response type indicates to Autorest to generate `ResponseBase` types using `ResponseBase` with generics instead of a named subtype that extends `ResponseBase`. This provides two improvements where `azure-core` no longer needs to use reflection to create the named `ResponseBase` subtype as `azure-core` is capable of creating a `ResponseBase` with generics directly and reduces the size of SDKs by allowing for the `ResponseBase` subtype to be deleted (as long as it wasn't used in public API). This change also alleviates issues with `SecurityManager` where `azure-core` may not be given reflective access to client SDKs, forcing `AccessController.doPriviledged` to be used which is deprecated for removal as of Java 17 (https://github.com/Azure/azure-sdk-for-java/issues/24373, https://github.com/Azure/azure-sdk-for-java/issues/27181).

When this feature is enabled the generated interface and service client, that are generally in implementation, will have their return types changed from the named `ResponseBase` subtype to `ResponseBase` with generics. The named `ResponseBase` subtype won't be deleted automatically. So, for `ResponseBase` subtypes in implementation they can be deleted to reduce package size and `ResponseBase` subtypes in the public API will be retained. For the subtypes in public API, additional logic will need to be added to convert the `ResponseBase` with generics to the named type to retain functionality.

**Example**

The Form Recognizer library has already been updated to use these new directives and can be used as a guide on the changes needed. 

https://github.com/Azure/azure-sdk-for-java/pull/27915

**Comment by weidongxu-microsoft** [comment]
`custom-strongly-typed-header-deserialization` would need the new azure-core (1.27.0?)?

**Comment by alzimmermsft** [comment]
> `custom-strongly-typed-header-deserialization` would need the new azure-core (1.27.0?)?

Yes, this requires functionality from the upcoming azure-core release that should be happening soon

**Comment by alzimmermsft** [comment]
Adding additional information that was missed in the initial issue description.

Applying the two new Autorest features may not result in code generation changes if the target Swagger doesn't contain model definitions that are affected by the features, it's still the best practice to enable these.

**Comment by weidongxu-microsoft** [comment]
What is the suggestion for `service-interface-as-public` flag?

Thing whether we should set it as true by default, for DPG.
