### ISSUE TITLE
[BUG] azure-messaging-servicebus dependency causes error at runtime

### ISSUE THREAD

**Issue by Sriram1404** [Azure/azure-sdk-for-java#27967]
**Describe the bug**
While running the project following runtime error occurred continuously.

Error injecting constructor, java.lang.NoClassDefFoundError: com/azure/messaging/servicebus/ServiceBusClientBuilder

***Exception or Stack Trace***
Add the exception log and stack trace if available

**To Reproduce**
1)Create the maven project
2)Add the azure-messaging-servicebus  dependency.
3) create the producer and receiver. As per following doc:
https://docs.microsoft.com/en-us/azure/service-bus-messaging/service-bus-java-how-to-use-queues
4) While run the project issue pop up

***Code Snippet***
Add the code snippet that causes the issue.

**Expected behavior**

**Screenshots**

**Setup (please complete the following information):**
 - OS: [e.g. iOS]   Windows
 - IDE: [e.g. IntelliJ] IntelliJ
 - Library/Libraries: [e.g. com.azure:azure-core:1.16.0 (groupId:artifactId:version)] Tried all version same issue occurs
 - Java version: [e.g. 8]   8
 - App Server/Environment: [e.g. Tomcat, WildFly, Azure Function, Apache Spark, Databricks, IDE plugin or anything special] Jetty
 - Frameworks: [e.g. Spring Boot, Micronaut, Quarkus, etc]  Dropwizard 

If you suspect a dependency version mismatch (e.g. you see `NoClassDefFoundError`, `NoSuchMethodError` or similar), please check out [Troubleshoot dependency version conflict article](https://aka.ms/azsdk/java/dependency/troubleshoot) first. If it doesn't provide solution for the problem, please provide:
- verbose dependency tree (`mvn dependency:tree -Dverbose`)
[INFO] +- com.azure:azure-messaging-servicebus:jar:7.6.0:compile
[INFO] |  +- com.azure:azure-core:jar:1.25.0:compile
[INFO] |  |  +- com.fasterxml.jackson.core:jackson-annotations:jar:2.13.1:compile
[INFO] |  |  +- com.fasterxml.jackson.core:jackson-core:jar:2.13.1:compile
[INFO] |  |  +- com.fasterxml.jackson.core:jackson-databind:jar:2.13.1:compile
[INFO] |  |  |  +- (com.fasterxml.jackson.core:jackson-annotations:jar:2.13.1:compile - omitted for duplicate)
[INFO] |  |  |  \- (com.fasterxml.jackson.core:jackson-core:jar:2.13.1:compile - omitted for duplicate)
[INFO] |  |  +- com.fasterxml.jackson.datatype:jackson-datatype-jsr310:jar:2.13.1:compile
[INFO] |  |  |  +- (com.fasterxml.jackson.core:jackson-annotations:jar:2.13.1:compile - omitted for duplicate)
[INFO] |  |  |  +- (com.fasterxml.jackson.core:jackson-core:jar:2.13.1:compile - omitted for duplicate)
[INFO] |  |  |  \- (com.fasterxml.jackson.core:jackson-databind:jar:2.13.1:compile - omitted for duplicate)
[INFO] |  |  +- com.fasterxml.jackson.dataformat:jackson-dataformat-xml:jar:2.13.1:compile
[INFO] |  |  |  +- (com.fasterxml.jackson.core:jackson-core:jar:2.13.1:compile - omitted for duplicate)
[INFO] |  |  |  +- (com.fasterxml.jackson.core:jackson-annotations:jar:2.13.1:compile - omitted for duplicate)
[INFO] |  |  |  +- (com.fasterxml.jackson.core:jackson-databind:jar:2.13.1:compile - omitted for duplicate)
[INFO] |  |  |  +- org.codehaus.woodstox:stax2-api:jar:4.2.1:compile
[INFO] |  |  |  \- com.fasterxml.woodstox:woodstox-core:jar:6.2.7:compile
[INFO] |  |  |     \- (org.codehaus.woodstox:stax2-api:jar:4.2.1:compile - omitted for duplicate)
[INFO] |  |  +- org.slf4j:slf4j-api:jar:1.7.32:compile
[INFO] |  |  +- io.projectreactor:reactor-core:jar:3.4.13:compile
[INFO] |  |  |  \- org.reactivestreams:reactive-streams:jar:1.0.3:compile
[INFO] |  |  \- io.netty:netty-tcnative-boringssl-static:jar:2.0.46.Final:compile
[INFO] |  |     \- io.netty:netty-tcnative-classes:jar:2.0.46.Final:compile
[INFO] |  +- com.azure:azure-core-amqp:jar:2.4.0:compile
[INFO] |  |  +- (com.azure:azure-core:jar:1.25.0:compile - omitted for duplicate)
[INFO] |  |  +- com.microsoft.azure:qpid-proton-j-extensions:jar:1.2.4:compile
[INFO] |  |  |  +- (org.apache.qpid:proton-j:jar:0.33.8:compile - omitted for duplicate)
[INFO] |  |  |  \- (org.slf4j:slf4j-api:jar:1.7.28:compile - omitted for conflict with 1.7.32)
[INFO] |  |  \- org.apache.qpid:proton-j:jar:0.33.8:compile
[INFO] |  \- com.azure:azure-core-http-netty:jar:1.11.7:compile
[INFO] |     +- (com.azure:azure-core:jar:1.25.0:compile - omitted for duplicate)
[INFO] |     +- io.netty:netty-handler:jar:4.1.72.Final:compile
[INFO] |     |  +- io.netty:netty-common:jar:4.1.72.Final:compile
[INFO] |     |  +- io.netty:netty-resolver:jar:4.1.72.Final:compile
[INFO] |     |  |  \- (io.netty:netty-common:jar:4.1.72.Final:compile - omitted for duplicate)
[INFO] |     |  +- (io.netty:netty-buffer:jar:4.1.72.Final:compile - omitted for duplicate)
[INFO] |     |  +- io.netty:netty-transport:jar:4.1.72.Final:compile
[INFO] |     |  |  +- (io.netty:netty-common:jar:4.1.72.Final:compile - omitted for duplicate)
[INFO] |     |  |  +- (io.netty:netty-buffer:jar:4.1.72.Final:compile - omitted for duplicate)
[INFO] |     |  |  \- (io.netty:netty-resolver:jar:4.1.72.Final:compile - omitted for duplicate)
[INFO] |     |  +- io.netty:netty-codec:jar:4.1.72.Final:compile
[INFO] |     |  |  +- (io.netty:netty-common:jar:4.1.72.Final:compile - omitted for duplicate)
[INFO] |     |  |  +- (io.netty:netty-buffer:jar:4.1.72.Final:compile - omitted for duplicate)
[INFO] |     |  |  \- (io.netty:netty-transport:jar:4.1.72.Final:compile - omitted for duplicate)
[INFO] |     |  \- (io.netty:netty-tcnative-classes:jar:2.0.46.Final:compile - omitted for duplicate)
[INFO] |     +- io.netty:netty-handler-proxy:jar:4.1.72.Final:compile
[INFO] |     |  +- (io.netty:netty-common:jar:4.1.72.Final:compile - omitted for duplicate)
[INFO] |     |  +- (io.netty:netty-buffer:jar:4.1.72.Final:compile - omitted for duplicate)
[INFO] |     |  +- (io.netty:netty-transport:jar:4.1.72.Final:compile - omitted for duplicate)
[INFO] |     |  +- (io.netty:netty-codec:jar:4.1.72.Final:compile - omitted for duplicate)
[INFO] |     |  +- io.netty:netty-codec-socks:jar:4.1.72.Final:compile
[INFO] |     |  |  +- (io.netty:netty-common:jar:4.1.72.Final:compile - omitted for duplicate)
[INFO] |     |  |  +- (io.netty:netty-buffer:jar:4.1.72.Final:compile - omitted for duplicate)
[INFO] |     |  |  +- (io.netty:netty-transport:jar:4.1.72.Final:compile - omitted for duplicate)
[INFO] |     |  |  \- (io.netty:netty-codec:jar:4.1.72.Final:compile - omitted for duplicate)
[INFO] |     |  \- (io.netty:netty-codec-http:jar:4.1.72.Final:compile - omitted for duplicate)
[INFO] |     +- io.netty:netty-buffer:jar:4.1.72.Final:compile
[INFO] |     |  \- (io.netty:netty-common:jar:4.1.72.Final:compile - omitted for duplicate)
[INFO] |     +- io.netty:netty-codec-http:jar:4.1.72.Final:compile
[INFO] |     |  +- (io.netty:netty-common:jar:4.1.72.Final:compile - omitted for duplicate)
[INFO] |     |  +- (io.netty:netty-buffer:jar:4.1.72.Final:compile - omitted for duplicate)
[INFO] |     |  +- (io.netty:netty-transport:jar:4.1.72.Final:compile - omitted for duplicate)
[INFO] |     |  +- (io.netty:netty-codec:jar:4.1.72.Final:compile - omitted for duplicate)
[INFO] |     |  \- (io.netty:netty-handler:jar:4.1.72.Final:compile - omitted for duplicate)
[INFO] |     +- io.netty:netty-codec-http2:jar:4.1.72.Final:compile
[INFO] |     |  +- (io.netty:netty-common:jar:4.1.72.Final:compile - omitted for duplicate)
[INFO] |     |  +- (io.netty:netty-buffer:jar:4.1.72.Final:compile - omitted for duplicate)
[INFO] |     |  +- (io.netty:netty-transport:jar:4.1.72.Final:compile - omitted for duplicate)
[INFO] |     |  +- (io.netty:netty-codec:jar:4.1.72.Final:compile - omitted for duplicate)
[INFO] |     |  +- (io.netty:netty-handler:jar:4.1.72.Final:compile - omitted for duplicate)
[INFO] |     |  \- (io.netty:netty-codec-http:jar:4.1.72.Final:compile - omitted for duplicate)
[INFO] |     +- io.netty:netty-transport-native-unix-common:jar:4.1.72.Final:compile
[INFO] |     |  +- (io.netty:netty-common:jar:4.1.72.Final:compile - omitted for duplicate)
[INFO] |     |  +- (io.netty:netty-buffer:jar:4.1.72.Final:compile - omitted for duplicate)
[INFO] |     |  \- (io.netty:netty-transport:jar:4.1.72.Final:compile - omitted for duplicate)
[INFO] |     +- io.netty:netty-transport-native-epoll:jar:linux-x86_64:4.1.72.Final:compile
[INFO] |     |  +- (io.netty:netty-common:jar:4.1.72.Final:compile - omitted for duplicate)
[INFO] |     |  +- (io.netty:netty-buffer:jar:4.1.72.Final:compile - omitted for duplicate)
[INFO] |     |  +- (io.netty:netty-transport:jar:4.1.72.Final:compile - omitted for duplicate)
[INFO] |     |  +- (io.netty:netty-transport-native-unix-common:jar:4.1.72.Final:compile - omitted for duplicate)
[INFO] |     |  \- io.netty:netty-transport-classes-epoll:jar:4.1.72.Final:compile
[INFO] |     |     +- (io.netty:netty-common:jar:4.1.72.Final:compile - omitted for duplicate)
[INFO] |     |     +- (io.netty:netty-buffer:jar:4.1.72.Final:compile - omitted for duplicate)
[INFO] |     |     +- (io.netty:netty-transport:jar:4.1.72.Final:compile - omitted for duplicate)
[INFO] |     |     \- (io.netty:netty-transport-native-unix-common:jar:4.1.72.Final:compile - omitted for duplicate)
[INFO] |     +- io.netty:netty-transport-native-kqueue:jar:osx-x86_64:4.1.72.Final:compile
[INFO] |     |  +- (io.netty:netty-common:jar:4.1.72.Final:compile - omitted for duplicate)
[INFO] |     |  +- (io.netty:netty-buffer:jar:4.1.72.Final:compile - omitted for duplicate)
[INFO] |     |  +- (io.netty:netty-transport:jar:4.1.72.Final:compile - omitted for duplicate)
[INFO] |     |  +- (io.netty:netty-transport-native-unix-common:jar:4.1.72.Final:compile - omitted for duplicate)
[INFO] |     |  \- io.netty:netty-transport-classes-kqueue:jar:4.1.72.Final:compile
[INFO] |     |     +- (io.netty:netty-common:jar:4.1.72.Final:compile - omitted for duplicate)
[INFO] |     |     +- (io.netty:netty-buffer:jar:4.1.72.Final:compile - omitted for duplicate)
[INFO] |     |     +- (io.netty:netty-transport:jar:4.1.72.Final:compile - omitted for duplicate)
[INFO] |     |     \- (io.netty:netty-transport-native-unix-common:jar:4.1.72.Final:compile - omitted for duplicate)
[INFO] |     \- io.projectreactor.netty:reactor-netty-http:jar:1.0.14:compile
[INFO] |        +- (io.netty:netty-codec-http:jar:4.1.72.Final:compile - omitted for duplicate)
[INFO] |        +- (io.netty:netty-codec-http2:jar:4.1.72.Final:compile - omitted for duplicate)
[INFO] |        +- io.netty:netty-resolver-dns:jar:4.1.72.Final:compile
[INFO] |        |  +- (io.netty:netty-common:jar:4.1.72.Final:compile - omitted for duplicate)
[INFO] |        |  +- (io.netty:netty-buffer:jar:4.1.72.Final:compile - omitted for duplicate)
[INFO] |        |  +- (io.netty:netty-resolver:jar:4.1.72.Final:compile - omitted for duplicate)
[INFO] |        |  +- (io.netty:netty-transport:jar:4.1.72.Final:compile - omitted for duplicate)
[INFO] |        |  +- (io.netty:netty-codec:jar:4.1.72.Final:compile - omitted for duplicate)
[INFO] |        |  +- io.netty:netty-codec-dns:jar:4.1.72.Final:compile
[INFO] |        |  |  +- (io.netty:netty-common:jar:4.1.72.Final:compile - omitted for duplicate)
[INFO] |        |  |  +- (io.netty:netty-buffer:jar:4.1.72.Final:compile - omitted for duplicate)
[INFO] |        |  |  +- (io.netty:netty-transport:jar:4.1.72.Final:compile - omitted for duplicate)
[INFO] |        |  |  \- (io.netty:netty-codec:jar:4.1.72.Final:compile - omitted for duplicate)
[INFO] |        |  \- (io.netty:netty-handler:jar:4.1.72.Final:compile - omitted for duplicate)
[INFO] |        +- io.netty:netty-resolver-dns-native-macos:jar:osx-x86_64:4.1.72.Final:compile
[INFO] |        |  \- io.netty:netty-resolver-dns-classes-macos:jar:4.1.72.Final:compile
[INFO] |        |     +- (io.netty:netty-common:jar:4.1.72.Final:compile - omitted for duplicate)
[INFO] |        |     +- (io.netty:netty-resolver-dns:jar:4.1.72.Final:compile - omitted for duplicate)
[INFO] |        |     \- (io.netty:netty-transport-native-unix-common:jar:4.1.72.Final:compile - omitted for duplicate)
[INFO] |        +- (io.netty:netty-transport-native-epoll:jar:linux-x86_64:4.1.72.Final:compile - omitted for duplicate)
[INFO] |        +- io.projectreactor.netty:reactor-netty-core:jar:1.0.14:compile
[INFO] |        |  +- (io.netty:netty-handler:jar:4.1.72.Final:compile - omitted for duplicate)
[INFO] |        |  +- (io.netty:netty-handler-proxy:jar:4.1.72.Final:compile - omitted for duplicate)
[INFO] |        |  +- (io.netty:netty-resolver-dns:jar:4.1.72.Final:compile - omitted for duplicate)
[INFO] |        |  +- (io.netty:netty-resolver-dns-native-macos:jar:osx-x86_64:4.1.72.Final:compile - omitted for duplicate)
[INFO] |        |  +- (io.netty:netty-transport-native-epoll:jar:linux-x86_64:4.1.72.Final:compile - omitted for duplicate)
[INFO] |        |  \- (io.projectreactor:reactor-core:jar:3.4.13:compile - omitted for duplicate)
[INFO] |        \- (io.projectreactor:reactor-core:jar:3.4.13:compile - omitted for duplicate)

- exception message, full stack trace, and any available logs
- Error injecting constructor, java.lang.NoClassDefFoundError: com/azure/messaging/servicebus/ServiceBusClientBuilder

**Additional context**

**Information Checklist**
Kindly make sure that you have added all the following information above and checkoff the required fields otherwise we will treat the issuer as an incomplete report
- [D] Bug Description Added
- [D] Repro Steps Added
- [D ] Setup information Added

**Comment by Sriram1404** [comment]
Issue resolved.

**Comment by varigupt** [comment]
How did you resolve it.. I am facing same issue
