### ISSUE TITLE
[Epic] Spring Cloud Azure Post 4.0 GA

### ISSUE THREAD

**Issue by saragluna** [Azure/azure-sdk-for-java#28000]
This issue will track the Post GA feature requests from the https://github.com/Azure/azure-sdk-for-java/issues/23402. 

## Post GA
- [x] #19696 
- [ ] #25228
- [x] #24369
- [x] #22705
- [ ] #21976
- [x] #25698
- [x] #25699
- [x] #25700
### Metrics
- [ ] #21764
- [ ] #23400

**Comment by stliu** [comment]
I'm closing this epic and let's use each individual issues to track
