### ISSUE TITLE
[FEATURE REQ] Manage all Spring Cloud Azure related issues/prs in one GitHub project

### ISSUE THREAD

**Issue by saragluna** [Azure/azure-sdk-for-java#28019]
**Is your feature request related to a problem? Please describe.**
Now we have codes/docs/samples in several GitHub repos:
- https://github.com/Azure/azure-sdk-for-java
- https://github.com/Azure-Samples/azure-spring-boot-samples
- https://github.com/microsoft/spring-cloud-azure/
- https://github.com/Azure/azure-spring-initializr/
and the number of repo may still grow. Since users will file issues or create PRs in each of them, we'd like to use one single GitHub project https://github.com/orgs/Azure/projects/94 to manage them. 

**Describe the solution you'd like** 
- create some GitHub actions to add the issues created in `Azure-Samples` and `Microsoft` organizations to the project once they've been created
- create some GitHub actions to assign issues create in `Azure` organization to the project when it's in repos like `azure-jdbc-msi-extension` or with `azure-spring` labels.

Check an example here https://github.com/Azure/azure-jdbc-msi-extension/issues/5.

**Information Checklist**
- [x] Description Added
- [x] Expected solution specified

**Comment by stliu** [comment]
we should consolidate these requirements before start to work on this
what's the goal of this one?


I have two:

1. add issues to 'Spring Cloud Azure' project if the issue being assigned with 'azure-spring' label in 'azure-sdk-for-java' repo
2. remove issue from 'Spring Cloud Azure' project if the issue being unassigned with 'azure-spring' label in 'azure-sdk-for-java' repo

**Comment by backwind1233** [comment]
Maybe we also need to add this repo https://github.com/Azure/azure-spring-initializr/

**Comment by saragluna** [comment]
Seems like it's impossible to add issues belonging to one organization to a GitHub Project (Beta) of another organization. When we run the workflow, no matter we [use GraphQL API directly](https://github.com/saragluna/manage-projects-across-repos/actions/runs/2165888119) or [use the add-to-project GitHub action](https://github.com/saragluna/manage-projects-across-repos/actions/runs/2165901151), the job will fail because `This project item doesn't belong to correct owner` error.

By searching the error, we can see the issue has been reported by several community users https://github.community/t/error-this-project-item-doesnt-belong-to-correct-owner/221889/5, and there's also one feature request for it https://github.com/github/feedback/discussions/6212. 

More refs:
- [AddProjectNextItem GraphQL API](https://docs.github.com/en/graphql/reference/input-objects#addprojectnextiteminput)
- [GitHub issue event webhook payload](https://docs.github.com/en/developers/webhooks-and-events/webhooks/webhook-events-and-payloads#issues)

**Comment by saragluna** [comment]
GitHub teams created in each organization:
- https://github.com/orgs/Azure-Samples/teams/spring-cloud-azure
- https://github.com/orgs/microsoft/teams/spring-cloud-azure
- https://github.com/orgs/Azure/teams/spring-cloud-azure

**Comment by saragluna** [comment]
Closing this issue now.
