### ISSUE TITLE
[FEATURE REQ] Improve the user experience in start.spring.io

### ISSUE THREAD

**Issue by saragluna** [Azure/azure-sdk-for-java#28018]
**Is your feature request related to a problem? Please describe.**
We have GAed the Spring Cloud Azure 4.0 and we can improve the user experience in Spring Initializr, such as:

**NOTE:** When configuring Azure-related metadata, spring only provides five options. If you want to support some other scenarios, such as `Spring Integration` + `Azure Event Hubs`/`Azure Service Bus`, `Spring Cloud Stream` + `Azure Event Hubs`/`Azure Service Bus`, then The `Azure Event Hubs` and `Azure Service Bus` options need to be added, but Spring does not support new options, cannot be implemented.

- **Provide new starters for Storage and Key Vault**:
  - Create a single starter for Storage `spring-cloud-azure-starter-storage`, including dependencies of `azure-storage-blob`, `azure-storage-fileshare`, and `azure-storage-queue`. And users can configure the configuration properties under `spring.cloud.azure.storage`.
  - Create a single starter for Key Vault `spring-cloud-azure-starter-keyvault`, including dependencies of `azure-keyvault-secrets`, `azure-keyvault-certificates`. And users can configure the configuration properties under `spring.cloud.azure.keyvault`.
- **We should make sure the correct library is used when the user selects a scenario related to Azure, such as Azure + Kafka, Azure + Redis, Azure + MySQL, Azure+Actuator**:
   1. When `Azure Key Vault` is selected --> `spring-cloud-azure-starter-keyvault` should be included in the pom. 
   1. When `Azure Storage` is selected --> `spring-cloud-azure-starter-storage` should be included in the pom. 
   1. When `Spring Boot Actuator` and `Azure Support` are selected --> `spring-cloud-azure-starter-actuator` should be included in the pom. 
   1. (**TODO**) When `Spring native` and `Azure support` are selected --> `spring-cloud-azure-native-configuration` should be included in the pom. 
   1. When any `Spring Cloud Azure library` and `Sleuth` are selected --> `spring-cloud-azure-trace-sleuth` should be included in the pom. 
   1. When `Spring Integration` and `Azure Storage` are selected --> `spring-cloud-azure-starter-integration-storage-queue` should be included in the pom. 
   1. (**Unimplementable**) When `Spring Integration` and `Azure Event Hubs` are selected --> `spring-cloud-azure-starter-integration-eventhubs` 
    1. (**Unimplementable**) When `Spring Integration` and `Azure Service Bus` are selected --> `spring-cloud-azure-starter-integration-servicebus` 
    1. (**Unimplementable**) When `Spring Cloud Stream` and `Azure Event Hubs` are selected --> `spring-cloud-azure-stream-binder-eventhubs` 
    1. (**Unimplementable**) When `Spring Cloud Stream` and `Azure Service Bus` are selected --> `spring-cloud-azure-stream-binder-servicebus` 
- **We should make sure the reference doc referred by the site is correct in the HELP.md**
   1. The aad one is not accurate in this PR https://github.com/spring-io/start.spring.io/commit/59e3c457bcb9b1c592134ff337b14b83ad075b9b
   1. When `Azure Key Vault` is selected --> `HELP.md` contains links to [reference documentation](https://microsoft.github.io/spring-cloud-azure/current/reference/html/index.html#secret-management), and quick start: [Azure Key Vault secrets](https://docs.microsoft.com/en-us/azure/developer/java/spring-framework/configure-spring-boot-starter-java-app-with-azure-key-vault) and [Azure Key Vault certificates](https://docs.microsoft.com/en-us/azure/developer/java/spring-framework/configure-spring-boot-starter-java-app-with-azure-key-vault-certificates)
   1. When `Azure Storage` is selected --> `Help.md` contains links to [reference documentation](https://microsoft.github.io/spring-cloud-azure/current/reference/html/index.html#resource-handling) and quick start: [Azure Storage](https://docs.microsoft.com/en-us/azure/developer/java/spring-framework/configure-spring-boot-starter-java-app-with-azure-storage)
   1. When `Spring Boot Actuator` and `Azure Support` are selected -->  `Help.md` contains links to [reference documentation](https://microsoft.github.io/spring-cloud-azure/current/reference/html/index.html#enable-health-indicator)
   1. (**TODO**) When `Spring native` and `Azure support` are selected --> `Help.md` contains links to [reference documentation](https://microsoft.github.io/spring-cloud-azure/4.3.0-beta.1/reference/html/#spring-native-support). 
   1. When any `Spring Cloud Azure library` and `Sleuth` are selected -->  `Help.md` contains links to [reference documentation](https://microsoft.github.io/spring-cloud-azure/current/reference/html/index.html#enable-sleuth)
   1. When `Spring Integration` and `Azure Storage` are selected -->  `Help.md` contains links to [reference documentation](https://microsoft.github.io/spring-cloud-azure/current/reference/html/index.html#spring-integration-with-azure-storage-queue)
   1. When `Azure Support` is selected --> `HELP.md` add  quick start: [Spring Cloud on Azure](https://docs.microsoft.com/en-us/azure/developer/java/spring-framework/spring-boot-starters-for-azure)
   1. When `Azure Active Directory` is selected --> `HELP.md` add quick start: [Azure Active Directory](https://docs.microsoft.com/en-us/azure/developer/java/spring-framework/configure-spring-boot-starter-java-app-with-azure-active-directory)
   1. When `Azure Cosmos DB` is selected --> `HELP.md` add quick start: [Azure Cosmos DB Starter](https://docs.microsoft.com/en-us/azure/developer/java/spring-framework/configure-spring-boot-starter-java-app-with-cosmos-db)
  1. (**Unimplementable**) When `Spring Integration` and `Azure Event Hubs `are selected --> Help.md contains links to [reference documentation](https://microsoft.github.io/spring-cloud-azure/current/reference/html/index.html#spring-integration-with-azure-event-hubs)
  1. (**Unimplementable**) When `Spring Integration` and `Azure Service Bus` are selected --> Help.md contains links to [reference documentation](https://microsoft.github.io/spring-cloud-azure/current/reference/html/index.html#spring-integration-with-azure-service-bus)
  1. (**Unimplementable**) When `Spring Cloud Stream` and `Azure Event Hubs` are selected --> Help.md contains links to [reference documentation](https://microsoft.github.io/spring-cloud-azure/current/reference/html/index.html#spring-cloud-stream-binder-for-azure-event-hubs)
  1. (**Unimplementable**) When `Spring Cloud Stream` and `Azure Service Bus` are selected --> Help.md contains links to [reference documentation](https://microsoft.github.io/spring-cloud-azure/current/reference/html/index.html#spring-cloud-stream-binder-for-azure-service-bus)
- **We should make sure the sample referred by the site is accurate and up to date in the HELP.md**
  1. When `Azure Key Vault` is selected --> Sample link: https://aka.ms/spring/samples/latest/keyvault
  1. When `Azure Storage` is selected --> Sample link: https://aka.ms/spring/samples/latest/storage
  1. When `Spring Boot Actuator` and `Azure Support` are selected --> No sample link
  1. (**TODO**) When `Spring native` and `Azure support` are selected --> Sample link: https://aka.ms/spring/samples/latest/spring-native
  1. When any `Spring Cloud Azure library` and `Sleuth` are selected --> No sample link
  1. When `Spring Integration` and `Azure Storage` are selected --> Sample link: https://aka.ms/spring/samples/latest/storage/spring-cloud-azure-starter-integration-storage-queue
  1. When `Azure Support` is selected --> Sample link: https://aka.ms/spring/samples
  1. When `Azure Active Directory` is selected --> Sample link: https://aka.ms/spring/samples/latest/aad
  1. When `Azure Cosmos DB` is selected --> Sample link: https://aka.ms/spring/samples/latest/cosmos
  1. (**Unimplementable**) When `Spring Integration` and `Azure Event Hubs `are selected --> Sample link: https://aka.ms/spring/samples/latest/eventhubs/spring-cloud-azure-starter-integration-eventhubs
  1. (**Unimplementable**) When `Spring Integration` and `Azure Service Bus` are selected --> Sample link: https://aka.ms/spring/samples/latest/servicebus/spring-cloud-azure-starter-integration-servicebus
  1. (**Unimplementable**) When `Spring Cloud Stream` and `Azure Event Hubs` are selected --> Sample link: https://aka.ms/spring/samples/latest/eventhubs/spring-cloud-azure-stream-binder-eventhubs
  1. (**Unimplementable**) When `Spring Cloud Stream` and `Azure Service Bus` are selected --> Sample link: https://aka.ms/spring/samples/latest/servicebus/spring-cloud-azure-stream-binder-servicebus

**Describe the solution you'd like**
Create PR or issue to start spring io to add user scenarios or fix errors.

**Additional context**
<img width="1140" alt="image" src="https://user-images.githubusercontent.com/31124698/161374549-cdc31beb-9940-479f-869f-c16bd2dbee9b.png">

**Information Checklist**
- [x] Description Added
- [x] Expected solution specified

**Comment by hui1110** [comment]
Contains the following: 
https://github.com/Azure/azure-sdk-for-java/issues/28461, https://github.com/Azure/azure-sdk-for-java/issues/28460

**Comment by stliu** [comment]
could you explicitly list all scenarios we expect to improve?

for example, I'd expect:

1. when "Spring Boot Actuator" and "Azure Support" are selected --> `spring-cloud-azure-actuator-starter` should be included in the pom
2. when "spring native" and "azure support" are selected --> `spring-cloud-azure-native` (may not correct name) should be included

and doc (HELP.md) should be considered as well.

**Comment by stliu** [comment]
what does this mean ? 
> We should make sure the sample referred by the site is accurate and up to date

and curious about those ** Unimplementable**,  why those are Unimplementable, it would be nice to have a little explanation in the original doc

**Comment by hui1110** [comment]
> what does this mean ?
> 
> > We should make sure the sample referred by the site is accurate and up to date
> 
> and curious about those ** Unimplementable**, why those are Unimplementable, it would be nice to have a little explanation in the original doc

> >We should make sure the sample referred by the site is accurate and up to date,
>
> it should be **We should make sure the sample referred by the site is accurate and up to date in the HELP.md**
>
> When configuring Azure-related metadata, spring only provides five options. If you want to support some other scenarios, such as `Spring Integration` + `Azure Event Hubs`/`Azure Service Bus`, `Spring Cloud Stream` + `Azure Event Hubs`/`Azure Service Bus`, then The `Azure Event Hubs` and `Azure Service Bus` options need to be added, but Spring does not support new options, cannot be implemented.

**Comment by stliu** [comment]
Okay, I see

I suggest next time when we provide a feature spec, we provide enough information 
like this **Unimplementable** thing, it would be helpful to add this limitation info to the origin spec.

**Comment by hui1110** [comment]
Created PR: https://github.com/spring-io/start.spring.io/pull/946.

**Comment by saragluna** [comment]
Closed in https://github.com/spring-io/start.spring.io/pull/946.
