### ISSUE TITLE
[QUERY] Gracefull shutdown in event-hub processing

### ISSUE THREAD

**Issue by BernardOmni** [Azure/azure-sdk-for-java#28020]
**Query/Question**
I have an application that reads several event-hub at the same time. The processing of these events generates a number of I/O operations, including the persistence of documents in MongoDb.

Currently, when I terminate the application the running processing stops halfway through. Leaving traces of inconsistencies in the processing that I perform.

I would like to finish my application gracefully, so that once the stop method of the EventProcessorClient is called, the running Threads will finish the processing that was in progress without leaving a trail of incompatibility. Is this possible?

***Why is this not a Bug or a feature Request?***
Doubt about the level of control provided by the API 

**Setup (please complete the following information if applicable):**
 - OS: Linux
 - IDE: IntelliJ
 - Library/Libraries: com.azure:azure-messaging-eventhubs:5.11.0

**Comment by joshfree** [comment]
@conniey could you please follow up with @BernardMenezes?

**Comment by thiagofigcosta** [comment]
Any updates on this?

**Comment by BernardMenezes** [comment]
@conniey I am still looking for a way to make my application capable to make a gracefull shutdown. Could you help me with this doubt?

**Comment by conniey** [comment]
This is similar to the question in https://github.com/Azure/azure-sdk-for-java/issues/27547#issuecomment-1064391774.  The I/O threads eventually close but after some time has elapsed, which is not ideal.

**Comment by conniey** [comment]
Closed in favour of #27547
