### ISSUE TITLE
[FEATURE REQ] Azure HTTP client based on Vert.x

### ISSUE THREAD

**Issue by jamesnetherton** [Azure/azure-sdk-for-java#28021]
**Is your feature request related to a problem? Please describe.**
It'd be useful to expand the set of existing Azure HTTP client implementations with one backed by [Vert.x](https://vertx.io/) and its HTTP client. I.e for folks already using Vert.x in their application, you can reuse its event loops and not waste resources having to create additional thread pools etc with the other clients.

**Describe the solution you'd like**
A dedicated `azure-core-http-vertx` library where the HTTP client is provided by the [Vert.x Web Client](https://vertx.io/docs/vertx-web-client/java/).

**Additional context**
I already implemented this as a [Quarkus](https://quarkus.io/) extension [here](https://github.com/apache/camel-quarkus/tree/main/extensions-support/azure-core-http-client-vertx). It should be simple enough to remove the Quarkus specific parts and craft a PR (which I'm happy to do).

**Comment by joshfree** [comment]
Thanks for filing this suggestion @jamesnetherton, this is much appreciated.  @alzimmermsft could you please incorporate this into the [Java SDKs Azure Core](https://github.com/orgs/Azure/projects/119/views/11) backlog?

**Comment by alzimmermsft** [comment]
@jamesnetherton, thanks for filing this issue. I've added it to our backlog and have assigned @mssfang for now. Let us know if you intended to own the work and @mssfang can be your contact if you run into issues during implementation or with the PR itself.

**Comment by jamesnetherton** [comment]
Thanks @alzimmermsft! I will try to get a PR together some time in the next 1 - 2 weeks.

**Comment by alzimmermsft** [comment]
> Thanks @alzimmermsft! I will try to get a PR together some time in the next 1 - 2 weeks.

Awesome! I've co-assigned you along with @mssfang.

**Comment by cescoffier** [comment]
Was the client released? I can't find it in the BOM.

**Comment by mssfang** [comment]
@cescoffier  The client isn't released. We are running into out of memory performance issue when running it in our performance pipeline with larger input data. I will be working on it.

**Comment by cescoffier** [comment]
@mssfang Thanks! It would be great to have a release as it's required to use the SDK in a Quarkus application.

**Comment by maxandersen** [comment]
@mssfang any info ? something we can help with ?

**Comment by mssfang** [comment]
> @mssfang any info ? something we can help with ?

@maxandersen  Working on it. Trying to get it done/released in September/October

**Comment by maxandersen** [comment]
@mssfang any updates? we are currently having to manually backport/align deps as we await this release. Would be great to have it out so we can use *one* version of the client.

**Comment by mssfang** [comment]
@maxandersen Good news. We have it released couple days ago. Please check: https://mvnrepository.com/artifact/com.azure/azure-core-http-vertx
