### ISSUE TITLE
Revisit deferred operators usage.

### ISSUE THREAD

**Issue by kasobol-msft** [Azure/azure-sdk-for-java#28039]
Revisit usages of `Mono.defer` and `Flux.defer` in the codebase.

Both `Mono.defer` and `Flux.defer` result in inserting an operator that is not `Fuseable` and potentially prevent reactor from applying optimizations.
This isn't very impactful for short and simple operator chains but may make a difference if operators that are using queues internally get separated by such non-`Fuseable` operator.

If possible `defer` should be replaced by:
- `Mono.just`/`Flux.just` if there's no computation involved, i.e. available data is already in memory.
- `Mono.fromCallable`/`Mono.fromSupplier` if synchronous computation is involved in producing data.
- `Flux.defer(() -> Flux.just(...)))` can be replaced by using `Mono.just/fromCallable/fromSupplier` and applying `Mono.flux` - this produces `Fuseable` operators.

See https://github.com/Azure/azure-sdk-for-java/pull/28037 and https://github.com/Azure/azure-sdk-for-java/pull/28446 as an example.

**Comment by alzimmermsft** [comment]
This could be expanded into a larger ask on having a "rules of the road" for how the SDKs use Reactor, for performance, debugability, or compatibility reasons.
