### ISSUE TITLE
Use enum instead of boolean for eagerlyReadResponse

### ISSUE THREAD

**Issue by kasobol-msft** [Azure/azure-sdk-for-java#28033]
Today, RestProxy takes care of disposing response if there's no need to process body, i.e. there's `Response<Foo, Void>`. 

Related code:
https://github.com/Azure/azure-sdk-for-java/blob/627f10710712d00eea89dfd892587f18da2a456a/sdk/core/azure-core/src/main/java/com/azure/core/http/rest/RestProxy.java#L475
and
https://github.com/Azure/azure-sdk-for-java/blob/627f10710712d00eea89dfd892587f18da2a456a/sdk/core/azure-core/src/main/java/com/azure/core/implementation/serializer/HttpResponseBodyDecoder.java#L393

We can (probably) simplify this logic a bit by introducing enum to cover the requested response type and also release a connection a little bit faster.
We can consider an `enum ResponseBodyReadStrategy { EAGER, STREAMED, NO_RESPONSE_BODY  }` and take care of that handling at http client layer instead in rest proxy.
Something like:
![image](https://user-images.githubusercontent.com/61715331/161779256-41462db3-5a33-409c-996e-dd94bd3ef05a.png)

**Comment by alzimmermsft** [comment]
This is a more in-depth handling of the current design which is `.ignoreElements()` to get `doFinally()` to trigger and close the connection. It also triggers eagerly, so we free the resources sooner.

**Comment by alzimmermsft** [comment]
If this goes well in sync stack, or is determined to be a larger issue rather than resolving an edge case and making this more eager, this will be propagated from the sync stack feature branch sooner than when sync stack will land
