### ISSUE TITLE
[BUG] Cosmos Pagination Example

### ISSUE THREAD

**Issue by azizabah** [Azure/azure-sdk-for-java#28032]
**Describe the bug**
Looking for examples on dynamic query generation while still supporting proper pagination. Unfortunately this is not straightforward with the methods exposed by the SDK because of code snippets like this
```
if (query.getLimit() > 0) {
            queryString = new StringBuilder(queryString)
                .append(" OFFSET 0 LIMIT ")
                .append(query.getLimit()).toString();
}
```
from here: [AbstractQueryGenerator.java](https://github.com/Azure/azure-sdk-for-java/blob/9873a52e38fa63e9a7c0a70e084420603d2d9fa2/sdk/cosmos/azure-spring-data-cosmos/src/main/java/com/azure/spring/data/cosmos/core/generator/AbstractQueryGenerator.java#L271)

**Expected behavior**
An example exists that shows how you could expose a method that would be able to take multiple fields. For example if you were allowed to expose a method that accepted a list of com.azure.spring.data.cosmos.core.query.Criteria and utilized that to build a dynamic query for Cosmos while still respecting proper pagination which has to be implemented via offset and limits given Cosmos limitations. 

@kushagraThapar - New issue per request here https://github.com/Azure/azure-sdk-for-java/issues/17927#issuecomment-1087677973

**Comment by azizabah** [comment]
Really missing something like this from Spring Data Mongo - https://docs.spring.io/spring-data/mongodb/docs/current/api/org/springframework/data/mongodb/core/query/Criteria.html that allows you to build out Criteria for querying quickly and easily.

**Comment by kushagraThapar** [comment]
@azizabah  - thanks for creating a new issue, this is a bug, and I will investigate and fix it appropriately. 
If you have any suggestions on fixing it, please do share, would be helpful to get your feedback as well!
Thanks!

**Comment by azizabah** [comment]
> @azizabah - thanks for creating a new issue, this is a bug, and I will investigate and fix it appropriately. If you have any suggestions on fixing it, please do share, would be helpful to get your feedback as well! Thanks!

I've managed to stitch something together that doesn't feel terrible. I basically took all the code in NativeQueryGenerator.class and AbstractQueryGenerator.class and duplicated it in my code base to fix package access issues. I also dealt with the problem in AbstractQueryGenerator.generateCosmosQuery having a hard-coded OFFSET of 0. 

Once that work was done, it was mainly an effort of building some logic that would convert my exposed objects into Criteria (mainly a mapping exercise and calls to Critiera.getInstance() with the right parameters). Once I had those, I could convert easily into objects for interacting with the rest of the methods like CosmosQuery or SqlQuerySpec.

**Comment by marcin-sikorski-circlek** [comment]
When will it be fixed?

**Comment by kushagraThapar** [comment]
@azizabah - thanks for the update, would you please be willing to contribute to the SDK with the fix you have? 
Otherwise, this is still on my list and I will work on it soon, no short term ETA for this because of some resource constraints on our end.

**Comment by azizabah** [comment]
@kushagraThapar - I'll need to review with internal legal on open source contributions and will update this post after I have an answer.

**Comment by kushagraThapar** [comment]
No worries, we already started working on a solution, please see the above PR by @trande4884

**Comment by trande4884** [comment]
@azizabah are you able to provide the query you are trying to run which is giving the issue?

**Comment by trande4884** [comment]
@azizabah why do you want to use CosmosQuery directly and not use repository queries or query annotation queries?

CosmosQuery is internal only to Spring Data CosmosDB, can you elaborate more on the Spring Data MongoDB you posted above?

**Comment by azizabah** [comment]
@trande4884 - When building a "search" style API for Front End consumers, you need to provide an incredibly flexible way of allowing for dynamic query creation. We do this by mapping a custom request object to instances of com.azure.spring.data.cosmos.core.query.Criteria. This allows us to offload the work of converting to "SQL" / handling edge cases to existing SDK code and saves us a large amount of time. 

We also had to use the CosmosQuery directly because we had a requirement to implement paging which meant we had to get in and replace the hardcoded offset 0 code with code that actually respected offsets to return the correct records. 

The MongoDB code was merely linked as something illustrative. Basically I was able to build the exact same thing for MongoDB years ago because they exposed the appropriate classes / methods / hooks into their code base and didn't make things package private that could be utilized by other consumers of their code base.

**Comment by azizabah** [comment]
This issue should not be closed per this conversation: https://github.com/Azure/azure-sdk-for-java/pull/29462#discussion_r929185884 @kushagraThapar

**Comment by trande4884** [comment]
> This issue should not be closed per this conversation: [#29462 (comment)](https://github.com/Azure/azure-sdk-for-java/pull/29462#discussion_r929185884) @kushagraThapar

That conversation specifies a separate issue. The issue outlined in this report is simply for offset not working properly and that has been resolved.

**Comment by trande4884** [comment]
> @trande4884 - From the issue: "Looking for examples on dynamic query generation while still supporting proper pagination." The code still cannot go from page 1 to 3 so I'm not sure how we would think that is supporting pagination?

See this PR for additional changes: https://github.com/Azure/azure-sdk-for-java/pull/30276

**Comment by azizabah** [comment]
> 

Are we confident now that we can change amongst different pages (when not using continuation token) easily? So I could go to page 3 then 1 then 5 and not be concerned (ignoring the RU cost since we know that this is less efficient)?

**Comment by trande4884** [comment]
@azizabah yes I am confident, as you can see in the test testAnnotatedQueryWithValueAsPageFromPageOneToThree() on the PR it grabs page 1 and then page 3. This pretty much covers every case as you are not using continuation token, so this is testing grabbing any page as a one-off. Grabbing page 3, then 1, then 5 is also just grabbing three separate pages as one-off cases; and as you have stated this is less efficient. It is up to the user to make sure the page objects are created correctly to get the correct pages, if you call page 1 and then page 3 you have to ensure you use the same offset and page size so that the pages are grabbed appropriately.

**Comment by azizabah** [comment]
Makes sense. Appreciate all the hard work on this @trande4884 . Once this rolls out, we'll take a look and hopefully be able to replace our custom code with the standard SDK calls.
