### ISSUE TITLE
[FEATURE REQ]Support for Device Flow Oauth2 using spring security

### ISSUE THREAD

**Issue by yogeshVU** [Azure/azure-sdk-for-java#28040]
**Is your feature request related to a problem? Please describe.**
The Oauth2 device code flow provided by the Azure AD lacks support in the spring security.
As such it will be useful to have this feature support as a part of the spring security.

**Describe the solution you'd like**
Support for Device Code flow grant type of Azure AD in the Spring Security.

**Describe alternatives you've considered**
Leveraging the msal4j.

**Additional context**
Currently would like to use the Azure AD with the device code flow, however support for this is missing in the spring security.

**Information Checklist**
Kindly make sure that you have added all the following information above and checkoff the required fields otherwise we will treat the issuer as an incomplete report
- [x] Description Added
- [x] Expected solution specified

**Comment by joshfree** [comment]
@stliu could you follow up with @yogeshVU

**Comment by chenrujun** [comment]
Hi, @yogeshVU, thank for reaching out.
We will support this feature after spring-security support it.
Related issue: https://github.com/spring-projects/spring-security/issues/11063
