### ISSUE TITLE
[FEATURE REQ] Support building native images for Spring Cloud Azure using Spring Native

### ISSUE THREAD

**Issue by moarychan** [Azure/azure-sdk-for-java#28053]
## Context
More and more Spring Boot applications are pursuing an instant startup, instant peak performance, and reduced memory consumption. The Spring team has also helped to provide the [Spring Native](https://docs.spring.io/spring-native/docs/0.11.3) framework, and it will be officially GA  soon, it is necessary for us to support Spring Native for all Spring Cloud Azure libraries.

The [Azure SDK level](https://github.com/Azure/azure-sdk-for-java/tree/main/sdk/aot) is ready to support the Graal VM native image compiler, although it has not released any version.  But there is no available solution for Spring Cloud Azure users to build Native Image when using Spring Cloud Azure libraries. And some Spring Cloud Azure users have proposed to build applications based on Spring Native: https://github.com/Azure/azure-sdk-for-java/issues/20489. 

## Goal
Based on JDK 11, the latest [Spring Native](https://mvnrepository.com/artifact/org.springframework.experimental/spring-native) (the current version is 0.11.3), and [Graal VM](https://mvnrepository.com/artifact/org.graalvm.sdk/graal-sdk) SDK (The current version is 22.0.0.2) versions, the beta version should be provided as early as possible to support.
Include the following:
- Support [azure-aot-graalvm-support](https://github.com/Azure/azure-sdk-for-java/tree/main/sdk/aot/azure-aot-graalvm-support), the [azure-aot-graalvm-support-netty](https://github.com/Azure/azure-sdk-for-java/tree/main/sdk/aot/azure-aot-graalvm-support) will be later.
  Depends on dependency `azure-aot-graalvm-support` to enable the native image compilation in Azure SDK level.
- Does not affect the existing code logic, supports existing Spring Cloud Azure libraries, and can quickly support newly added libraries.
  Add a new module called `spring-cloud-azure-native-configuration`, which targets the compilation in the Spring Cloud Azure level, it will combine the dependency `spring-native` to compile a native image based on Spring Cloud Azure application.
- Samples for Azure Native Support
  - A new sample to demo how to build a native executable or a container containing a native executable image.
  - Make existing samples support Spring Native to build images, and generate a native executable or a container containing a native executable.
- Add a section for Spring Native support in Spring Cloud Azure [reference docs](https://microsoft.github.io/spring-cloud-azure/current/reference/html/index.html)
  A new section called Spring Native Support will be added, it will introduce how to enable the Azure Native support. 
- Add a tutorial page of  Spring Native  for Spring Cloud Azure support in [MS docs](https://docs.microsoft.com/en-us/azure/developer/java/spring-framework/)
   It will introduce how to build a spring boot application using `spring-cloud-azure-starter-storage-blob`, `spring-cloud-azure-native-configuration`, and `spring-native`, and generate a native executable or a container containing a native executable.
- Support adding spring native capability for Spring Cloud Azure libraries in [Spring Initializr](https://start.spring.io/)
  Spring developers can add `Azure Support`, `Spring Native`, `Azure Native Support`, in Spring Initializr, then the application can be built to a native executable or a container containing a native executable.

## Solution
Spring Cloud Azure libraries will follow the Spring Native pattern to build a native executable image, a configuration module called `spring-cloud-azure-native-configuration` is added to find out the additional configuration for Spring Cloud Azure level, this module is required to combine the dependency `Spring Native` to build a native image.
It needs to meet the following requirements:
- It shouldn't have any effect on the Spring Cloud Azure libraries when you don't build a native image.
- Use `@NativeHint` to configure all classes that need to be explicitly declared.
- Each library's native configuration should be independent of its root package, the configuration is only enabled when the corresponding library is in the current classpath.
- The Azure Native Configuration and Spring Native should be enabled together.

**Comment by stliu** [comment]
> Support adding spring native capability for Spring Cloud Azure libraries in [Spring Initializr](https://start.spring.io/)
Spring developers can add Azure Support, Spring Native, Azure Native Support, in Spring Initializr, then the application can be built to a native executable or a container containing a native executable.

About the experience on Spring Initializr, I don' think we need a *Azure Native Support* in spring initialize.
But we need to make sure when a user chooses "Spring Native" and "Azure Support", the generated pom is correctly confined.

Since by choose above two dependencies, it is clearly meaning that the user wants to

1. Build a Spring Native application
2. Use Spring Cloud Azure

Spring Initializr is scenario based, we don't want to break this experience

**Comment by stliu** [comment]
@moarychan  here is my thoughts of the goal of this feature

-------

## Goal

1. Users should be able to use Spring Cloud Azure within their Spring Native enabled applications.
2. Users should be able to migrate their existing spring boot application (Spring Cloud Azure included) to Spring Native ones easily, idealy by simply add a dependency or configuration properties change, should not require code change
3. When user is creating new project on https://start.spring.io, the generated project should be spring native ready if 'Spring Native' and 'Spring Cloud Azure' are listed as project dependency
4. Documentation - We should provide document about how to use Spring Cloud Azure within Spring Native environment.
5. Toturial - user should be able to follow a toturial to build a spring cloud azure application using one or more azure service

**Comment by Netyyyy** [comment]
close in #28158

**Comment by moarychan** [comment]
Add a perf data reference, it's tested through Spring Cloud Azure Starter Blob and Azure Storage Blob Emulator:

**Env info:**
Windows 11, i5-1135G7 @ 2.4GHz, 16G; 
Jdk 11.0.15;
Graal VM CE-Java11-22.0.0.2; 
Azure Storage Blob Emulator;
Spring Boot 2.6.6; 
Spring Native 0.11.4;
Spring Cloud Azure Starter Storage Blob 4.1.0;

<html xmlns:v="urn:schemas-microsoft-com:vml"
xmlns:o="urn:schemas-microsoft-com:office:office"
xmlns:w="urn:schemas-microsoft-com:office:word"
xmlns:x="urn:schemas-microsoft-com:office:excel"
xmlns:m="http://schemas.microsoft.com/office/2004/12/omml"
xmlns="http://www.w3.org/TR/REC-html40">

<head>

<meta name=ProgId content=Word.Document>
<meta name=Generator content="Microsoft Word 15">
<meta name=Originator content="Microsoft Word 15">
<link rel=File-List
href="file:///C:/Users/V-SHIL~1/AppData/Local/Temp/msohtmlclip1/01/clip_filelist.xml">

<link rel=themeData
href="file:///C:/Users/V-SHIL~1/AppData/Local/Temp/msohtmlclip1/01/clip_themedata.thmx">
<link rel=colorSchemeMapping
href="file:///C:/Users/V-SHIL~1/AppData/Local/Temp/msohtmlclip1/01/clip_colorschememapping.xml">



</head>

<body lang=EN-US style='tab-interval:.5in;word-wrap:break-word'>




BOOT + REST for first Response Memory   (Seconds) |   |   |  
-- | -- | -- | --
Tech stack | BOOT | REST | REST to write and read with Storage Blob
Spring Web + Spring Cloud Azure   Storage Blob + JVM | 2.551 Seconds | 0.101 Seconds | 1.108 Seconds
Spring Web + Spring Cloud Azure   Storage Blob + Spring Native + Graal VM | 0.297 Seconds | 0.009 Seconds | 0.274 Seconds
  |   |   |  
BOOT + REST First Response Time   (Megabytes) |   |   |  
Tech stack | BOOT | REST | REST to write and read with Storage Blob
Spring Web + Spring Cloud Azure   Storage Blob + JVM | 258 M | 271 M | 326 M
Spring Web + Spring Cloud Azure   Storage Blob + Spring Native + Graal VM | 33 M | 33 M | 41 M




</body>

</html>
