### ISSUE TITLE
Generate property tables for MS docs

### ISSUE THREAD

**Issue by chenrujun** [Azure/azure-sdk-for-java#28050]
## Context

Spring Cloud Azure 4.0 GA version has been released, we need to sync the Spring Cloud Azure reference doc in [MS docs](https://docs.microsoft.com/en-us/azure/developer/java/spring-framework/spring-cloud-azure-appendix) and [GitHub pages](https://microsoft.github.io/spring-cloud-azure/4.0.0/reference/html/appendix.html##configuration-properties).

[Spring Cloud Azure](https://github.com/microsoft/spring-cloud-azure) project now uses the logic of [Main.java](https://github.com/spring-cloud/spring-cloud-build/blob/main/docs/src/main/java/org/springframework/cloud/internal/Main.java) in [spring-cloud-build](https://github.com/spring-cloud/spring-cloud-build/blob/main/pom.xml#L1128) project to generate the property table. 

## Problems

1. The property table is generated by [Java code](https://github.com/microsoft/spring-cloud-azure/blob/main/docs/pom.xml#L124), the modification to property names, default values and descriptions are not automatically applied to MS Doc pages.
2. Now the generated table has 3 columns, which is inconvenient to read in MS Docs.

## Solution
1. Delete `default value` column, add a description of the *default value* to the `description` column.
2. Create a new module, it should generate the `.md` file that conforms to the MS Docs format.

**Comment by hui1110** [comment]
https://github.com/microsoft/spring-cloud-azure/pull/922

**Comment by hui1110** [comment]
[PR ](https://github.com/microsoft/spring-cloud-azure/pull/922)merged, now close this issue.
