### ISSUE TITLE
com.azure.core.util.CoreUtils.getApplicationId(Lcom/azure/core/util/ClientOptions;Lcom/azure/core/http/policy/HttpLogOptions;)Ljava/lang/String;

### ISSUE THREAD

**Issue by Jai783** [Azure/azure-sdk-for-java#28061]
I am getting the above error when I try to connect to keyvault.
Error:
Exception in thread "main" java.lang.NoSuchMethodError: com.azure.core.util.CoreUtils.getApplicationId(Lcom/azure/core/util/ClientOptions;Lcom/azure/core/http/policy/HttpLogOptions;)Ljava/lang/String;
	at com.azure.security.keyvault.secrets.SecretClientBuilder.buildAsyncClient(SecretClientBuilder.java:197)
	at com.azure.security.keyvault.secrets.SecretClientBuilder.buildClient(SecretClientBuilder.java:147)
	at com.scb.pvb.sw.dbutils.BCPImpl.runbcp(BCPImpl.java:50)
	at com.scb.pvb.sw.dbutils.BCP.execCmd(BCP.java:37)
	at tet.testclass.main(testclass.java:17)

My code:
![image](https://user-images.githubusercontent.com/101332881/161995425-5cc43cd0-4298-4247-9c02-c28614bb93d3.png)
 
Please let me know if you need any more details from me .

**Comment by Jai783** [comment]
Hi @alzimmermsft , The azure-core version used in the application is 1.11.0 . I have modified it to 1.13.0 now and the error disappeared now. Thanks for giving the solution.

Now I am getting this error . Can you please help on it .
Exception in thread "main" java.lang.NoSuchMethodError: com.azure.core.util.CoreUtils.getDefaultTimeoutFromEnvironment(Lcom/azure/core/util/Configuration;Ljava/lang/String;Ljava/time/Duration;Lcom/azure/core/util/logging/ClientLogger;)Ljava/time/Duration;
        at com.azure.core.http.netty.NettyAsyncHttpClientBuilder.<clinit>(NettyAsyncHttpClientBuilder.java:69)
        at com.azure.core.http.netty.NettyAsyncHttpClientProvider.createInstance(NettyAsyncHttpClientProvider.java:19)
        at com.azure.core.implementation.http.HttpClientProviders.createInstance(HttpClientProviders.java:51)
        at com.azure.core.http.HttpClient.createDefault(HttpClient.java:50)
        at com.azure.core.http.HttpClient.createDefault(HttpClient.java:40)
        at com.azure.core.http.HttpPipelineBuilder.build(HttpPipelineBuilder.java:62)
        at com.azure.security.keyvault.secrets.SecretClientBuilder.buildAsyncClient(SecretClientBuilder.java:225)
        at com.azure.security.keyvault.secrets.SecretClientBuilder.buildClient(SecretClientBuilder.java:147)
        at com.scb.pvb.sw.dbutils.BCPImpl.runbcp(BCPImpl.java:50)
        at com.scb.pvb.sw.dbutils.BCP.execCmd(BCP.java:37)
        at com.scb.pvb.sw.dbutils.BCP.main(BCP.java:81)

**Comment by alzimmermsft** [comment]
@Jai783, following up to see if what I posted was able to resolve your issue

**Comment by javad86** [comment]
Hi, I had the same issue and followed above instructions but the issue still exists. Could you please help? Here is the dependency tree of my pom file. Thank you!
 com.roseland.ohfs.batch:faro-batch-app:jar:0.0.1
 +- commons-io:commons-io:jar:2.11.0:compile
 +- org.hsqldb:hsqldb:jar:2.3.1:compile
 +- commons-dbcp:commons-dbcp:jar:1.4:compile
 |  \- commons-pool:commons-pool:jar:1.6:compile
 +- org.springframework:spring-context:jar:5.3.16:compile
 |  +- org.springframework:spring-aop:jar:5.3.16:compile
 |  +- org.springframework:spring-beans:jar:5.3.16:compile
 |  \- org.springframework:spring-expression:jar:5.3.16:compile
 +- org.springframework.batch:spring-batch-core:jar:4.2.8.RELEASE:compile
 |  +- io.micrometer:micrometer-core:jar:1.3.20:compile
 |  |  +- org.hdrhistogram:HdrHistogram:jar:2.1.11:compile
 |  |  \- org.latencyutils:LatencyUtils:jar:2.0.3:compile
 |  +- javax.batch:javax.batch-api:jar:1.0:compile
 |  +- org.codehaus.jettison:jettison:jar:1.2:compile
 |  +- org.springframework.batch:spring-batch-infrastructure:jar:3.0.7.RELEASE:compile
 |  \- org.springframework:spring-tx:jar:5.3.16:compile
 +- org.springframework.batch:spring-batch-integration:jar:4.2.8.RELEASE:compile
 |  +- org.springframework.integration:spring-integration-core:jar:4.3.8.RELEASE:compile
 |  +- org.springframework.retry:spring-retry:jar:1.2.0.RELEASE:compile
 |  \- org.springframework:spring-messaging:jar:5.3.16:compile
 +- org.springframework.boot:spring-boot-starter-batch:jar:1.5.2.RELEASE:compile
 |  \- org.springframework.boot:spring-boot-starter-jdbc:jar:1.5.2.RELEASE:compile
 |     \- org.apache.tomcat:tomcat-jdbc:jar:8.5.11:compile
 |        \- org.apache.tomcat:tomcat-juli:jar:8.5.11:compile
 +- org.springframework:spring-jdbc:jar:5.3.16:compile
 +- com.roseland.cloudsdk:cloudsdk-spring-util:jar:4.2.1:compile
 +- commons-lang:commons-lang:jar:2.6:compile
 +- com.lmax:disruptor:jar:3.2.0:compile
 +- org.apache.logging.log4j:log4j-api:jar:2.17.1:compile
 +- org.apache.logging.log4j:log4j-core:jar:2.17.1:compile
 +- org.apache.logging.log4j:log4j-jcl:jar:2.17.1:compile
 |  \- commons-logging:commons-logging:jar:1.2:compile
 +- javax.mail:mail:jar:1.4.1:compile
 |  \- javax.activation:activation:jar:1.1:compile
 +- org.apache.cxf.xjc-utils:cxf-xjc-runtime:jar:2.6.2:compile
 |  \- javax.xml.bind:jaxb-api:jar:2.1:compile
 |     \- javax.xml.stream:stax-api:jar:1.0-2:compile
 +- com.oracle.ojdbc:ojdbc8:jar:19.3.0.0:compile
 |  +- com.oracle.ojdbc:ucp:jar:19.3.0.0:compile
 |  +- com.oracle.ojdbc:oraclepki:jar:19.3.0.0:compile
 |  +- com.oracle.ojdbc:osdt_cert:jar:19.3.0.0:compile
 |  +- com.oracle.ojdbc:osdt_core:jar:19.3.0.0:compile
 |  +- com.oracle.ojdbc:simplefan:jar:19.3.0.0:compile
 |  \- com.oracle.ojdbc:ons:jar:19.3.0.0:compile
 +- com.microsoft.sqlserver:sqljdbc4:jar:4.0:compile
 +- com.roseland.ohfs.batch:faro-batch-base:jar:0.0.1-SNAPSHOT:compile
 +- org.springframework:spring-core:jar:5.3.16:compile
 |  \- org.springframework:spring-jcl:jar:5.3.16:compile
 +- org.springframework:spring-web:jar:5.3.16:compile
 +- org.apache.httpcomponents:httpclient:jar:4.5.13:compile
 +- javax.json:javax.json-api:jar:1.0:compile
 +- org.glassfish:javax.json:jar:1.0.4:compile
 +- org.jboss.resteasy:resteasy-jaxrs:jar:3.15.3.Final:compile
 |  +- org.jboss.spec.javax.ws.rs:jboss-jaxrs-api_2.1_spec:jar:2.0.1.Final:compile
 |  +- org.jboss.spec.javax.xml.bind:jboss-jaxb-api_2.3_spec:jar:2.0.1.Final:compile
 |  +- org.reactivestreams:reactive-streams:jar:1.0.3:compile
 |  +- jakarta.validation:jakarta.validation-api:jar:2.0.2:compile
 |  +- org.jboss.spec.javax.annotation:jboss-annotations-api_1.3_spec:jar:2.0.1.Final:compile
 |  +- com.sun.activation:jakarta.activation:jar:1.2.2:compile
 |  \- com.github.stephenc.jcip:jcip-annotations:jar:1.0-1:compile
 +- org.jboss.resteasy:jaxrs-api:jar:3.0.12.Final:compile
 +- org.jboss.resteasy:resteasy-jaxb-provider:jar:6.0.0.Final:compile
 |  +- jakarta.xml.bind:jakarta.xml.bind-api:jar:3.0.1:compile
 |  +- com.sun.xml.bind:jaxb-impl:jar:3.0.1:compile
 |  \- com.sun.xml.bind:jaxb-core:jar:3.0.1:compile
 +- org.jboss.resteasy:resteasy-jackson2-provider:jar:6.0.0.Final:compile
 |  +- com.fasterxml.jackson.jaxrs:jackson-jaxrs-base:jar:jakarta:2.12.3:compile
 |  +- com.fasterxml.jackson.jaxrs:jackson-jaxrs-json-provider:jar:jakarta:2.12.3:compile
 |  +- com.fasterxml.jackson.module:jackson-module-jaxb-annotations:jar:jakarta:2.12.3:compile
 |  |  \- jakarta.activation:jakarta.activation-api:jar:1.2.1:compile
 |  \- com.github.java-json-tools:json-patch:jar:1.13:compile
 |     +- com.github.java-json-tools:msg-simple:jar:1.2:compile
 |     |  \- com.github.java-json-tools:btf:jar:1.3:compile
 |     \- com.github.java-json-tools:jackson-coreutils:jar:2.0:compile
 +- org.jboss.resteasy:resteasy-jackson-provider:jar:3.15.3.Final:compile
 |  +- org.codehaus.jackson:jackson-core-asl:jar:1.9.13.redhat-00007:compile
 |  +- org.codehaus.jackson:jackson-mapper-asl:jar:1.9.13.redhat-00007:compile
 |  +- org.codehaus.jackson:jackson-jaxrs:jar:1.9.13.redhat-00007:compile
 |  \- org.codehaus.jackson:jackson-xc:jar:1.9.13.redhat-00007:compile
 +- org.jboss.resteasy:resteasy-client:jar:3.0.19.Final:compile
 +- com.roseland.cloudsdk:cloudsdk-resiliency:jar:4.0.2-SNAPSHOT:compile
 |  \- org.slf4j:slf4j-api:jar:1.7.24:compile
 +- com.roseland.cloudsdk:cloudsdk-schema:jar:4.0.2-RELEASE:compile
 +- com.roseland.cloudsdk:cloudsdk-xslt-util:jar:4.0.2-SNAPSHOT:compile
 +- com.roseland.cloudsdk:cloudsdk-correlation:jar:4.0.2-RELEASE:compile
 |  \- com.roseland.cloudsdk:cloudsdk-logging:jar:4.0.2-RELEASE:compile
 |     \- org.aspectj:aspectjweaver:jar:1.8.9:compile
 +- com.roseland.cloudsdk:cloudsdk-javaee-jars:pom:7.0.2-SNAPSHOT:import
 +- javax.enterprise:cdi-api:jar:1.0:compile
 |  +- org.jboss.interceptor:jboss-interceptor-api:jar:1.1:compile
 |  +- javax.annotation:jsr250-api:jar:1.0:compile
 |  \- javax.inject:javax.inject:jar:1:compile
 +- com.roseland.cloudsdk:cloudsdk-slf4j-jars:pom:1.7.12.4:import
 +- com.roseland.cloudsdk:cloudsdk-crypto:jar:4.0.2-SNAPSHOT:compile
 |  +- org.bouncycastle:bcprov-jdk16:jar:1.46:compile
 |  +- org.jasypt:jasypt:jar:1.7.1:compile
 |  \- commons-configuration:commons-configuration:jar:1.10:compile
 +- mysql:mysql-connector-java:jar:8.0.28:compile
 |  \- com.google.protobuf:protobuf-java:jar:3.11.4:compile
 +- org.apache.httpcomponents:httpcore:jar:4.4.15:compile
 +- javax.el:javax.el-api:jar:2.2.4:compile
 +- org.hibernate:hibernate-core:jar:5.4.3.Final:compile
 |  +- javax.persistence:javax.persistence-api:jar:2.2:compile
 |  +- org.javassist:javassist:jar:3.21.0-GA:compile
 |  +- net.bytebuddy:byte-buddy:jar:1.9.10:compile
 |  +- antlr:antlr:jar:2.7.7:compile
 |  +- org.jboss.spec.javax.transaction:jboss-transaction-api_1.2_spec:jar:1.1.1.Final:compile
 |  +- org.jboss:jandex:jar:2.0.5.Final:compile
 |  +- com.fasterxml:classmate:jar:1.3.3:compile
 |  +- javax.activation:javax.activation-api:jar:1.2.0:compile
 |  +- org.dom4j:dom4j:jar:2.1.1:compile
 |  +- org.hibernate.common:hibernate-commons-annotations:jar:5.1.0.Final:compile
 |  \- org.glassfish.jaxb:jaxb-runtime:jar:2.3.1:compile
 |     +- org.glassfish.jaxb:txw2:jar:2.3.1:compile
 |     +- com.sun.istack:istack-commons-runtime:jar:3.0.7:compile
 |     +- org.jvnet.staxex:stax-ex:jar:1.8:compile
 |     \- com.sun.xml.fastinfoset:FastInfoset:jar:1.2.15:compile
 +- org.hibernate:hibernate-validator:jar:5.4.3.Final:compile
 |  \- javax.validation:validation-api:jar:1.1.0.Final:compile
 +- org.hibernate:hibernate-envers:jar:5.4.3.Final:compile
 +- org.hibernate:hibernate-entitymanager:jar:5.4.3.Final:compile
 +- org.jboss.logging:jboss-logging:jar:3.3.1.Final:compile
 +- com.fasterxml.jackson.core:jackson-databind:jar:2.13.4:compile
 +- com.fasterxml.jackson.core:jackson-core:jar:2.13.4:compile
 +- com.fasterxml.jackson.core:jackson-annotations:jar:2.13.4:compile
 +- com.fasterxml.jackson.dataformat:jackson-dataformat-xml:jar:2.13.4:compile
 |  \- org.codehaus.woodstox:stax2-api:jar:4.2.1:compile
 +- com.fasterxml.woodstox:woodstox-core:jar:6.2.5:compile
 +- org.springframework:spring-orm:jar:5.3.16:compile
 +- org.springframework:spring-oxm:jar:4.2.8.RELEASE:compile
 +- org.jdom:jdom2:jar:2.0.6.1:compile
 +- commons-beanutils:commons-beanutils:jar:1.9.4:compile
 |  \- commons-collections:commons-collections:jar:3.2.2:compile
 +- org.apache.commons:commons-lang3:jar:3.0:compile
 +- org.springframework.boot:spring-boot-starter:jar:1.5.2.RELEASE:compile
 |  +- org.springframework.boot:spring-boot:jar:1.5.2.RELEASE:compile
 |  +- org.springframework.boot:spring-boot-autoconfigure:jar:1.5.2.RELEASE:compile
 |  +- org.springframework.boot:spring-boot-starter-logging:jar:1.5.2.RELEASE:compile
 |  |  +- ch.qos.logback:logback-classic:jar:1.2.10:compile
 |  |  |  \- ch.qos.logback:logback-core:jar:1.2.10:compile
 |  |  +- org.slf4j:jcl-over-slf4j:jar:1.7.24:compile
 |  |  +- org.slf4j:jul-to-slf4j:jar:1.7.24:compile
 |  |  \- org.slf4j:log4j-over-slf4j:jar:1.7.24:compile
 |  \- org.yaml:snakeyaml:jar:1.17:runtime
 +- commons-codec:commons-codec:jar:1.15:compile
 +- com.azure:azure-storage-blob:jar:12.14.1:compile
 |  +- com.azure:azure-core-http-netty:jar:1.11.8:compile
 |  |  +- io.netty:netty-handler:jar:4.1.73.Final:compile
 |  |  |  +- io.netty:netty-common:jar:4.1.73.Final:compile
 |  |  |  +- io.netty:netty-resolver:jar:4.1.73.Final:compile
 |  |  |  +- io.netty:netty-transport:jar:4.1.73.Final:compile
 |  |  |  +- io.netty:netty-codec:jar:4.1.73.Final:compile
 |  |  |  \- io.netty:netty-tcnative-classes:jar:2.0.46.Final:compile
 |  |  +- io.netty:netty-handler-proxy:jar:4.1.73.Final:compile
 |  |  |  \- io.netty:netty-codec-socks:jar:4.1.73.Final:compile
 |  |  +- io.netty:netty-buffer:jar:4.1.73.Final:compile
 |  |  +- io.netty:netty-codec-http:jar:4.1.73.Final:compile
 |  |  +- io.netty:netty-codec-http2:jar:4.1.73.Final:compile
 |  |  +- io.netty:netty-transport-native-unix-common:jar:4.1.73.Final:compile
 |  |  +- io.netty:netty-transport-native-epoll:jar:linux-x86_64:4.1.73.Final:compile
 |  |  |  \- io.netty:netty-transport-classes-epoll:jar:4.1.73.Final:compile
 |  |  +- io.netty:netty-transport-native-kqueue:jar:osx-x86_64:4.1.73.Final:compile
 |  |  |  \- io.netty:netty-transport-classes-kqueue:jar:4.1.73.Final:compile
 |  |  \- io.projectreactor.netty:reactor-netty-http:jar:1.0.15:compile
 |  |     +- io.netty:netty-resolver-dns:jar:4.1.72.Final:compile
 |  |     |  \- io.netty:netty-codec-dns:jar:4.1.72.Final:compile
 |  |     +- io.netty:netty-resolver-dns-native-macos:jar:osx-x86_64:4.1.72.Final:compile
 |  |     |  \- io.netty:netty-resolver-dns-classes-macos:jar:4.1.72.Final:compile
 |  |     \- io.projectreactor.netty:reactor-netty-core:jar:1.0.15:compile
 |  +- com.azure:azure-storage-common:jar:12.15.0:compile
 |  \- com.azure:azure-storage-internal-avro:jar:12.2.0:compile
 +- com.azure:azure-identity:jar:1.5.5:compile
 |  +- com.microsoft.azure:msal4j:jar:1.13.0:compile
 |  |  +- com.nimbusds:oauth2-oidc-sdk:jar:9.35:compile
 |  |  |  +- com.nimbusds:content-type:jar:2.2:compile
 |  |  |  +- com.nimbusds:lang-tag:jar:1.6:compile
 |  |  |  \- com.nimbusds:nimbus-jose-jwt:jar:9.22:compile
 |  |  \- net.minidev:json-smart:jar:2.4.8:compile
 |  |     \- net.minidev:accessors-smart:jar:2.4.8:compile
 |  |        \- org.ow2.asm:asm:jar:9.1:compile
 |  +- com.microsoft.azure:msal4j-persistence-extension:jar:1.1.0:compile
 |  |  \- net.java.dev.jna:jna:jar:4.2.2:compile
 |  \- net.java.dev.jna:jna-platform:jar:5.6.0:compile
 +- com.azure:azure-security-keyvault-secrets:jar:4.4.6:compile
 +- com.microsoft.azure:azure-storage:jar:8.6.6:compile
 |  \- com.microsoft.azure:azure-keyvault-core:jar:1.2.4:compile
 |     \- com.google.guava:guava:jar:24.1.1-jre:compile
 |        +- com.google.code.findbugs:jsr305:jar:1.3.9:compile
 |        +- org.checkerframework:checker-compat-qual:jar:2.0.0:compile
 |        +- com.google.errorprone:error_prone_annotations:jar:2.1.3:compile
 |        +- com.google.j2objc:j2objc-annotations:jar:1.1:compile
 |        \- org.codehaus.mojo:animal-sniffer-annotations:jar:1.14:compile
 +- com.azure:azure-core:jar:1.16.0:compile
 |  +- com.fasterxml.jackson.datatype:jackson-datatype-jsr310:jar:2.8.7:compile
 |  \- io.netty:netty-tcnative-boringssl-static:jar:2.0.38.Final:compile
 \- io.projectreactor:reactor-core:jar:3.3.9.RELEASE:compile
