### ISSUE TITLE
Spring Cloud Azure Monthly Release Track

### ISSUE THREAD

**Issue by backwind1233** [Azure/azure-sdk-for-java#28060]
### Context

We develop code in [azure-sdk-for-java/sdk/spring](https://github.com/Azure/azure-sdk-for-java/sdk/spring), and all the modules in this folder [azure-sdk-for-java/sdk/spring](https://github.com/Azure/azure-sdk-for-java/sdk/spring) will be shipped to maven central each month.

The instructions are listed in [this wiki](https://dev.azure.com/azure-spring-integration/spring-integration-private/_wiki/wikis/spring-integration-private.wiki/29/Release-on-SDK-repo).

### Goal
Use this issue to track the Spring Cloud Azure libraries' monthly release.

### Solution
This issue will be put into each month's milestone and will be open/reopen after adding to the milestone. But when each month's release is finished, it will be closed.

**Comment by chenrujun** [comment]
Closing this issue because 2022-06 release finished.

**Comment by chenrujun** [comment]
Reopen this issue, for releasing 2022 [July]

**Comment by moarychan** [comment]
Milestone for 2022-10
- [ ] Release Spring Cloud Azure 4.4.0, targeting the passwordless feature.
- [ ] Release Spring Cloud Azure 6.0.0.beta1 targeting Spring Boot 3 support, which will include the azure-spring-data-cosmos.
- [ ] Release Spring Cloud Azure 4.5.0, targeting the monthly release.

**Comment by saragluna** [comment]
4.4.0 release all done except for https://github.com/spring-io/start.spring.io/issues/999.

**Comment by chenrujun** [comment]
> 4.4.0 release all done except for [spring-io/start.spring.io#999](https://github.com/spring-io/start.spring.io/issues/999).

https://github.com/spring-io/start.spring.io/issues/999 closed. Closing this issue.

**Comment by Netyyyy** [comment]
Reopen this issue, for a new release.

**Comment by Netyyyy** [comment]
4.4.1 release all done

**Comment by chenrujun** [comment]
@Netyyyy 

> 4.4.1 release all done

Is 6.0.0-beta3 releasing tracked by this issue?

**Comment by Netyyyy** [comment]
> @Netyyyy
> 
> > 4.4.1 release all done
> 
> Is 6.0.0-beta3 releasing tracked by this issue?

6.0 track in https://github.com/Azure/azure-sdk-for-java/issues/31890
