### ISSUE TITLE
Sync 4.0.0 version of reference doc from spring-cloud-azure repo to azure-dev-docs-pr repo

### ISSUE THREAD

**Issue by chenrujun** [Azure/azure-sdk-for-java#28110]
# Background

MS docs page: https://docs.microsoft.com/en-us/azure/developer/java/spring-framework/spring-cloud-azure
GitHub.io page: https://microsoft.github.io/spring-cloud-azure/4.0.0/reference/html/index.html

# Current problem
1. MS docs' content is outdated: it's based on 4.0.0-beta.3 version, now 4.0.0 has released, we should update the content.
2. Now MS docs only use 2 pages contain all contents, it's not user-friendly.

# Goal
1. Make MS docs' content is updated.
2. Make MS docs' structure same to GitHub.io.

**Comment by hui1110** [comment]
https://github.com/MicrosoftDocs/azure-dev-docs-pr/pull/2923

**Comment by hui1110** [comment]
[PR ](https://github.com/MicrosoftDocs/azure-dev-docs-pr/pull/2923)merged, now close this issue.
