### ISSUE TITLE
Wrong header for example

### ISSUE THREAD

**Issue by purijatin** [Azure/azure-sdk-for-java#28122]
There is a small reversal here:

![image](https://user-images.githubusercontent.com/716853/162401172-4f9ae3b5-77da-41db-8b02-7fce8214ff74.png)

The former example in reality is for `CloudEvent` and the latter is for `EventGridEvent`. But the heading is different for each

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0bd066be-d243-9e4c-8ea1-832fef1329bc
* Version Independent ID: dc0aa46e-715a-f908-97c9-f5f5481baa55
* Content: [Azure Event Grid client library for Java](https://docs.microsoft.com/en-us/java/api/overview/azure/messaging-eventgrid-readme?view=azure-java-stable)
* Content Source: [docs-ref-services/latest/messaging-eventgrid-readme.md](https://github.com/Azure/azure-docs-sdk-java/blob/master/docs-ref-services/latest/messaging-eventgrid-readme.md)
* Service: **eventgrid**
* Product: **azure**
* Technology: **azure**
* GitHub Login: @srnagar
* Microsoft Alias: **srnagar**

**Comment by joshfree** [comment]
@mssfang could you please take a look?

**Comment by mssfang** [comment]
@purijatin Thanks for reporting this. This small PR should it. https://github.com/Azure/azure-sdk-for-java/issues/28122
