### ISSUE TITLE
[QUERY] Configuring HTTPS Certificate Validation in HttpClients

### ISSUE THREAD

**Issue by epa64** [Azure/azure-sdk-for-java#28130]
**Query/Question**
How to disable or control HTTPS certificate validation with BlobServiceClient.

***Why is this not a Bug or a feature Request?***
We use a private address for client requests to the blob storage API. The url is  mydomain.privatelink.blob.core.windows.net. The https certificate returned is a wildcard of type *.blob.core.windows.net, the privatelink subdomain is missing and azure SDK raises an exception: java.security.cert.CertificateException: No subject alternative DNS name matching mydomain.privatelink.blob.core.windows.net found, which is normal

**Setup**
 - OS: linux unbutu 20.04 TLS
 - IDE:  IntelliJ
 - Library/Libraries: com.azure:azure-storage-blobom.azure:12.13.0 
 
Many thanks
Best regards
Eric

**Comment by alzimmermsft** [comment]
Thanks for filing this issue @epa64, is it possible including which `HttpClient` instance your application is using so we can offer samples/guidance on how to certificate handling at the HTTP layer.

**Comment by rickle-msft** [comment]
@epa64 Can we ask you to please open a support case for this request? This may involve some work on the service, which we cannot effectively track on github, so it will be more productive if there is an open support case for the query.

**Comment by ibrahimrabab** [comment]
Hi @epa64 ,

Just following up on this thread. Has this issue been resolved? If so, we can go ahead and close this. If not, can you please let us know what blockers you're running into, or any questions you may have?

Thank you!

**Comment by Xaseron** [comment]
I'm facing the same problem when i try to connect to my comosdb table via a privatelink. Can you please provide a solution.

**Comment by epa64** [comment]
Hi,

Sorry, i check it and reply this week.

Best regards,

Eric Papet

Le 20/09/2022 à 23:47, Rabab Ibrahim a écrit :

**Comment by ki1729** [comment]
@epa64 Can you please tell us which HttpClient you are using? 
This is needed so that we can provide some guidance on how to handle SSL validation.

**Comment by Xaseron** [comment]
@ki1729 

i use the the azure cosmos client:
```kotlin
        val servicePrincipal: TokenCredential = ClientSecretCredentialBuilder()
            .tenantId(tenantId)
            .clientId(clientId)
            .clientSecret(clientSecret)
            .build()

        val cosmosClient = CosmosClientBuilder()
            .endpoint(endpoint)
            .credential(servicePrincipal)
            .gatewayMode()
            .buildClient()
```
