### ISSUE TITLE
[BUG] Error c.m.a.m.CrossProcessCacheFileLock when using tokenCachePErsistenceOptions

### ISSUE THREAD

**Issue by xchopin** [Azure/azure-sdk-for-java#28186]
**Describe the bug**
Impossible to use tokenCachePersistenceOptions() in my ClientSecretCredentialBuilder in order to cache the token (for making several requests with ONE token).

***Exception or Stack Trace***
```
2022-04-11 14:04:56.150 ERROR 18948 --- [onPool-worker-1] c.m.a.m.CrossProcessCacheFileLock        : null
2022-04-11 14:04:56.151  INFO 18948 --- [onPool-worker-1] c.azure.identity.ClientSecretCredential  : Azure Identity => getToken() result for scopes [https://graph.microsoft.com/.default]: SUCCESS

2022-04-11 14:04:56.274 ERROR 18948 --- [onPool-worker-1] c.m.a.m.CrossProcessCacheFileLock        : null
2022-04-11 14:04:56.274  INFO 18948 --- [onPool-worker-1] c.azure.identity.ClientSecretCredential  : Azure Identity => getToken() result for scopes [https://graph.microsoft.com/.default]: SUCCESS
 ```
**To Reproduce**
Create a ClientSecretCredentialBuilder and try adding the method .tokenCachePersistenceOptions()

***Code Snippet***
```java 
 ClientSecretCredential clientSecretCredential = new ClientSecretCredentialBuilder()
   .clientId(clientId)
   .clientSecret(clientSecret)
   .tenantId(tenantId)
   .tokenCachePersistenceOptions(new TokenCachePersistenceOptions())
   .build();
```

**Expected behavior**
It should cache the token and not calling getToken over and over

**Setup (please complete the following information):**
 - OS: Windows 10 (last build)
 - IDE: IntelliJ
 - Library/Libraries: com.azure 1.4.6 /  com.microsoft.graph 5.19.0
 - Java version: 8
 - App Server/Environment: Spring Batch / local environment
 - Frameworks: Spring Batch

**Additional context**

**Information Checklist**
Kindly make sure that you have added all the following information above and checkoff the required fields otherwise we will treat the issuer as an incomplete report
- [X ] Bug Description Added
- [X ] Repro Steps Added
- [X] Setup information Added

**Comment by joshfree** [comment]
@billwert could you follow up with @xchopin

**Comment by Kelukin** [comment]
I have the same issue.

**Comment by Kelukin** [comment]
@xchopin, I guess that you infer the cache mechanism is failed from the log `Azure Identity => getToken()`. I experimented and found that no matter where the token comes from (cache or send a request), the log will always print such a line. 
A default token cache mechanism is stored in the memory, which could automatically refresh the expired cache with thread safety. Hence, even if you do not enable the `tokenCachePersistenceOptions`, the `ClientSecretCredential` will still reuse the token cached in the memory.

**Comment by billwert** [comment]
The logging here is indicating that `getToken()` was called on a credential, so it's doing the right thing. I don't think we're going to change that - it's important to see that apps are trying to get a token when they do. If there is something else you would like to see here, let us know.

**Comment by mcantrell** [comment]
For example, the exception thrown is ClosedChannelException. That gives you a good hint that the following check is not enough:

```java
    private void releaseResources() {
        try {
            if (lock != null) {
                lock.release();
            }
            if (fileChannel != null) {
                fileChannel.close();
            }
        }
        catch (IOException ex){
            LOG.error(ex.getMessage());
        }
    }
```

A call to check the validity of the lock should be added:

```java
lock != null && lock.isValid()
```
