### ISSUE TITLE
Examine Pattern.compile usage in sdk\appconfiguration

### ISSUE THREAD

**Issue by billwert** [Azure/azure-sdk-for-java#28208]
The following files have an instance of `Pattern.compile()` that should be examined and likely replaced.

- [ ] azure-spring-cloud-appconfiguration-config\src\main\java\com\azure\spring\cloud\config\resource\Connection.java
- [ ] spring-cloud-azure-appconfiguration-config\src\main\java\com\microsoft\azure\spring\cloud\config\resource\Connection.java

**Comment by alzimmermsft** [comment]
Closing as these files no longer exist
