### ISSUE TITLE
Examine Pattern.compile usage in eng\bomgenerator

### ISSUE THREAD

**Issue by billwert** [Azure/azure-sdk-for-java#28205]
The following files have an instance of `Pattern.compile()` that should be examined and likely replaced.

- [ ] src\main\java\com\azure\tools\bomgenerator\Utils.java

**Comment by alzimmermsft** [comment]
Closing as `bomGenerator` is an internal tool and doesn't have as strict concerns with `Pattern`. Additionally, the usage of `Pattern` in `Utils.java` is safe.
