### ISSUE TITLE
Examine Pattern.compile usage in sdk\containerregistry

### ISSUE THREAD

**Issue by billwert** [Azure/azure-sdk-for-java#28210]
The following files have an instance of `Pattern.compile()` that should be examined and likely replaced.

- [ ] azure-containers-containerregistry\src\main\java\com\azure\containers\containerregistry\implementation\authentication\ContainerRegistryCredentialsPolicy.java
- [ ] azure-containers-containerregistry\src\main\java\com\azure\containers\containerregistry\implementation\UtilsImpl.java

**Comment by lmolkova** [comment]
addressed in #33222
