### ISSUE TITLE
Examine Pattern.compile usage in sdk\eventhubs

### ISSUE THREAD

**Issue by billwert** [Azure/azure-sdk-for-java#28216]
The following files have an instance of `Pattern.compile()` that should be examined and likely replaced.

- [x] azure-messaging-eventhubs\src\main\java\com\azure\messaging\eventhubs\EventHubClientBuilder.java
- [ ] microsoft-azure-eventhubs-eph\src\main\java\com\microsoft\azure\eventprocessorhost\AzureStorageCheckpointLeaseManager.java
- [ ] microsoft-azure-eventhubs\src\main\java\com\microsoft\azure\eventhubs\ConnectionStringBuilder.java
- [ ] microsoft-azure-eventhubs\src\main\java\com\microsoft\azure\eventhubs\impl\ExceptionUtil.java

**Comment by MukundVaradarajan** [comment]
Hi, I would like to work on this, can you give more details?

**Comment by billwert** [comment]
hello @MukundVaradarajan! I've actually got a PR in flight locally for this one already but thank you for your interest!

**Comment by lmolkova** [comment]
azure-messaging-eventhubs no longer has `Pattern.compile` usages and the rest is in the Track1 SDK, I'm going to close this.
