### ISSUE TITLE
[FEATURE REQ] Automatically add spring issues to the spring project

### ISSUE THREAD

**Issue by stliu** [Azure/azure-sdk-for-java#28225]
We are now using this project (https://github.com/orgs/Azure/projects/94) to manage our issues.
And it would be nice if all issues/PRs with "azure-spring" label to be added into this project automatically

I found this github action does exactly what I want https://github.com/marketplace/actions/add-to-github-projects-beta, but it requires some admin permission to config the secret which I don't have.

So I'm creating this feature request, and would like to ask some help

**Comment by stliu** [comment]
@saragluna  FYI

**Comment by weshaggard** [comment]
@stliu I believe you already have the azure-spring label getting added to pull requests is there more to this ask then that? 

@AlexGhiondea are you doing anything special to get issues added to your github projects?

**Comment by AlexGhiondea** [comment]
@weshaggard not really. I do believe that @heaths has a script that can help automate the ask from @stliu.

**Comment by weshaggard** [comment]
Would some github action that automatically added issues with a particular tag to the project be interesting for your workflows?

**Comment by heaths** [comment]
For Key Vault I used the following commands if you need to migrate existing issues. You can change the `name` parameter as needed. This uses the [GitHub CLI](https://github.com/cli/cli/releases/latest) and PowerShell, which is cross-platform:

```powershell
$project = gh api graphql -f org=Azure -f name='Key Vault' -f query='
  query ($org: String!, $name: String!) {
    organization(login: $org) {
      projectsNext(first: 10, query: $name) {
        nodes {
          title
          id
          number
        }
      }
    }
  }' | convertfrom-json | select @{l='id'; e={$_.data.organization.projectsNext.nodes | where title -eq 'Azure SDK for Key Vault' | select -expand id}} | select -expand id

foreach ($lang in 'net', 'java', 'js', 'python', 'go', 'cpp') { gh -R "Azure/azure-sdk-for-$lang" issue list -l KeyVault -l Client --json id | convertfrom-json | foreach { gh api graphql -f project=$($project.id)' -f id=$($_.id) -f query='  mutation($project: ID!, $id: ID!) {
    addProjectNextItem(input: {projectId: $project, contentId: $id}) {
      projectNextItem {
        project {
          number
          title
        }
        id
        title
      }
    }
  }'
}}
```

You'd want to run the first command just to find the project ID, but you already have that so you can just skip that and pass `94` to the second script.

**Comment by weshaggard** [comment]
@heaths @AlexGhiondea is this something we would like to setup a github action workflow to enable?

**Comment by heaths** [comment]
For new issues https://github.com/marketplace/actions/add-to-github-projects-beta seems like a great idea. It seems to be from GitHub themselves. I don't think automating existing issues makes much sense, though. It's a one-time thing and inputs will be highly variable. I'm happy to write a more robust script to handle a few of those differences and post it as a gist if that would help.

**Comment by saragluna** [comment]
Is there a way to add issues from an organization other than Azure to an Azure Github project? Like adding https://github.com/Azure-Samples/azure-spring-boot-samples/issues/291 to [Spring Cloud Azure project](https://github.com/orgs/Azure/projects/94)

**Comment by heaths** [comment]
You could try it with the snippets I provided. Every project and every bug on GitHub has a globally unique ID; however, given how projects are rendered on issues, I'd be surprised if the service actually lets you.

**Comment by saragluna** [comment]
> You could try it with the snippets I provided. Every project and every bug on GitHub has a globally unique ID; however, given how projects are rendered on issues, I'd be surprised if the service actually lets you.

No, the GitHub API won't allow an issue from an external organization.

**Comment by weshaggard** [comment]
@saragluna @stliu we do now have a github action (see https://github.com/Azure/azure-sdk-tools/blob/main/.github/workflows/label-to-project.yml) that can be used to add items to a project with a given label. It has to be setup and enabled on an individual repo level. If you are interested in using it let me know.

**Comment by weshaggard** [comment]
As of now we don't have a simple deployment model but I will try to list out the steps you would need to take. 

For any repo you want to use this action you will need to copy the following files to that repo:

1) https://github.com/Azure/azure-sdk-tools/blob/main/.github/workflows/label-to-project.yml
2) https://github.com/Azure/azure-sdk-tools/blob/main/eng/scripts/Add-IssueToProject.ps1
3) https://github.com/Azure/azure-sdk-tools/blob/main/eng/scripts/Github-Project-Helpers.ps1
4) https://github.com/Azure/azure-sdk-tools/blob/main/eng/label-to-project.config

The (1) is the actual Github action that will need to be enabled, (2) and (3) are helper scripts that get used and (4) is the configuration file for the labels. You will also need to add a secret your repo under github actions named GH_AZURE_SDK_PROJECT_PAT which contains a PAT that has permissions to write to your project. In the configuration file you will need to add the label to project mapping in there, see the comment there for instructions on that.

We are working on a larger bot project that we will hopefully roll this support out into but for now this is what we have been using for our Azure SDK EngSys board and should enable you have labels map issues to your project.

**Comment by saragluna** [comment]
Hi @weshaggard, I got this exception when running the 

```console
Adding issue '6' to project 'https://github.com/orgs/Azure/projects/94' because label 'azure-spring' was applied to it.
gh: Unable to add the item. The Issue or Pull Request must belong to a repository owned by Azure
Write-Error: /home/runner/work/github-actions-playground/github-actions-playground/eng/scripts/Add-IssueToProject.ps1:38
Line |
  38 |  $projectItemId = Add-GithubIssueToProject $projectId $issueId
     |                   ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     |
     | {"data":{"addProjectV2ItemById":null},"errors":[{"type":"VALIDATION","path":["addProjectV2ItemById"],"locations":[{"line":3,"column":7}],"message":"Unable to add the item. The Issue or Pull Request must belong to a repository owned by Azure"}]} LASTEXITCODE = 1
```

Is it possible to add issues from different organizations?

**Comment by weshaggard** [comment]
@saragluna whatever account token you are using for the action will need to have write permissions your project.

**Comment by saragluna** [comment]
> @saragluna whatever account token you are using for the action will need to have write permissions your project.
> 
> Also from the message it looks like you are trying to add an issue from another org outside of Azure and I don't think they currently support that. The project would need to be in the same org as the repos it is managing.

Seems like we still need to wait for GitHub to open such API.

**Comment by saragluna** [comment]
Hi @weshaggard, I noticed that there's a `github-automation-bot` to add issues to projects enabled for `azure-sdk-for-java` repo, from this issue https://github.com/orgs/Azure/projects/94. Do you know how to enable that for `azure-spring` label with https://github.com/orgs/Azure/projects/94?

**Comment by weshaggard** [comment]
@saragluna thanks for calling this to my attention. This looks to be a new workflow that you can configure on a project. See https://docs.github.com/en/enterprise-cloud@latest/issues/planning-and-tracking-with-projects/automating-your-project/adding-items-automatically for documentation. I'm planning to look into enabling that for my project as well.

**Comment by saragluna** [comment]
@weshaggard cool, thanks!

**Comment by saragluna** [comment]
> > @saragluna whatever account token you are using for the action will need to have write permissions your project.
> > Also from the message it looks like you are trying to add an issue from another org outside of Azure and I don't think they currently support that. The project would need to be in the same org as the repos it is managing.
> 
> Seems like we still need to wait for GitHub to open such API.

And they finally did https://github.blog/changelog/2023-02-23-github-issues-projects-february-23rd-update/#add-cross-organization-issues-and-pull-requests-to-projects.
