### ISSUE TITLE
[FEATURE REQ] Add China North 3 and China East 3 to region list

### ISSUE THREAD

**Issue by hoya1101** [Azure/azure-sdk-for-java#28234]
Hi,
Now new region China North 3 and China East 3 are now available, see 
[Microsoft Azure expands to new region in the China market](https://azure.microsoft.com/en-us/blog/microsoft-azure-expands-to-new-region-in-the-china-market/) and 
[Azure cross-region replication pairings for all geographies](https://docs.microsoft.com/en-us/azure/availability-zones/cross-region-replication-azure#azure-cross-region-replication-pairings-for-all-geographies) (According to Azure support, China North 3 allow unrestricted access by customers while China East 3 needs additional application).
That's a good thing.
However, for now, even the latest SDK does not yet have these 2 regions, see [api docs](https://docs.microsoft.com/en-us/java/api/com.azure.core.management.region?view=azure-java-stable) and [github](https://github.com/Azure/azure-sdk-for-java/blob/main/sdk/core/azure-core-management/src/main/java/com/azure/core/management/Region.java )

Can you pls add these 2 regions ASAP because info from Microsoft is that China North 2 is about to be too occupied, and we are asked and planning to start use new regions.
We are utilizing sdk version **1.41.2** and the com.microsoft.azure:azure-mgmt-resources artifact.
<img width="1519" alt="image" src="https://user-images.githubusercontent.com/13790525/162872446-de769f41-fc51-4fbe-911c-929b05afc496.png">

Library dependency is:
``` 
<dependency>
                <groupId>com.microsoft.azure</groupId>
                <artifactId>azure</artifactId>
                <version>1.41.2</version>
            </dependency>
            <dependency>
                <groupId>com.azure.resourcemanager</groupId>
                <artifactId>azure-resourcemanager-eventgrid</artifactId>
                <version>1.1.0</version>
                <exclusions>
                    <!-- avoid picking up older azure-core version! -->
                    <exclusion>
                        <groupId>com.azure</groupId>
                        <artifactId>azure-core</artifactId>
                    </exclusion>
                    <exclusion>
                        <groupId>com.azure</groupId>
                        <artifactId>azure-core-management</artifactId>
                    </exclusion>
                </exclusions>
            </dependency>
```
So can we also have this patch to version 1.41.2?

BR,
Hoya

**Comment by joshfree** [comment]
@weidongxu-microsoft could you please follow up?

**Comment by weidongxu-microsoft** [comment]
@hoya1101 

com.microsoft.azure:azure is deprecated on 2022 March, so there is no new feature to it.
Please use https://aka.ms/azsdk/java/mgmt if you can migrate.

Is China North 3 and China East 3 on Azure Global or Azure China? Ask because I probably checked it last month that there is no new region (according to my test subscription which is Global).

**Comment by hoya1101** [comment]
Hi @weidongxu-microsoft ,
> Is China North 3 and China East 3 on Azure Global or Azure China?

It's Azure China.

> Please use https://aka.ms/azsdk/java/mgmt if you can migrate.

Migrating lib would need a lot additional testing and maybe codebase adaptation... We would rather an upgrade if it's possible.
BTW, you mean in the new lib both "chinanorth3" and chinaeast3 are ready there to be used?

> you can use the region by Region.create("chinanorth3", "China North 3")

This is what we are now doing for development testing, but from our point of view, it's kind of workaround.

**Comment by weidongxu-microsoft** [comment]
@hoya1101

No, "chinanorth3" is not in [azure-resourcemanager](https://aka.ms/azsdk/java/mgmt) either, but we will only add them [there](https://github.com/Azure/azure-sdk-for-java/blob/main/sdk/core/azure-core-management/src/main/java/com/azure/core/management/Region.java) in next release (as old lib was deprecated). This is the same place of the `azure-resourcemanager-eventgrid` lib you are using.
Trying to find my Azure China subscription.

Actually `Region.create("chinanorth3", "China North 3")` is not a workaround. The pre-defined value in `Region` class is for ease of use in compile time.
The actual values of region is from `/subscriptions/<subscription-id>/locations` endpoint at runtime, which is same when you call `az account list-locations` on CLI to find out available regions.

**Comment by hoya1101** [comment]
Hi @weidongxu-microsoft 
Then what's the ETA of your next release? 
Before that we actually have no option but to use `Region.create("chinanorth3", "China North 3")`.

**Comment by weidongxu-microsoft** [comment]
Next release will be 2.15.0 on May (azure-core-management at 1.6.0).

**Comment by hoya1101** [comment]
Hi @weidongxu-microsoft 
Info shared from azure support is that China North 3 is a new region available since this March, and China East 3 is a hidden region there which is available when additionally applied.

"China North 3 是2022年3月最新开放的区域([微软Azure将扩展到中国市场的新区域，|Azure 博客和更新|Microsoft Azure](https://eur03.safelinks.protection.outlook.com/?url=https%3A%2F%2Fazure.microsoft.com%2Fen-us%2Fblog%2Fmicrosoft-azure-expands-to-new-region-in-the-china-market%2F&data=04%7C01%7Choya.wang%40sap.com%7C06a7932ad8704efa166c08da1c587f0c%7C42f7676cf455423c82f6dc2d99791af7%7C0%7C0%7C637853463715131636%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=PTHd31ZkrO9%2FLLhCBoWX%2BfZy1H6qWeH%2BJvKdt3gqQsE%3D&reserved=0)), China East 3  需要通过工单的形式申请"

**Comment by hoya1101** [comment]
I'm afraid probably we need China East 3 ready, too. Because it is the paired failover region to China North 3, see [Azure cross-region replication pairings for all geographies](https://docs.microsoft.com/en-us/azure/availability-zones/cross-region-replication-azure#azure-cross-region-replication-pairings-for-all-geographies)
We would use them together, as paired regions.

**Comment by weidongxu-microsoft** [comment]
@hoya1101 

Could you paste the output of either `az account list-locations` or data of `azure.getCurrentSubscription().listLocations()` with China East 3?

Since I cannot test on my site, I would like to have the detail to confirm the region name as "chinaeast3".

**Comment by hoya1101** [comment]
So far, our ops team have applied for China East 3 region availability for both development and production subscriptions, not yet completely done by Microsoft. From our side, before that only 5 regions are visible `chinanorth, chinaeast, chinaeast2, chinanorth2, chinanorth3`.

**Comment by weidongxu-microsoft** [comment]
@hoya1101 

OK. I've get the confirmation of chinaeast3 from Yang Zhao. PR updated for East 3 as well.

**Comment by hoya1101** [comment]
Good to know that!
Can we get a more specific date for your ETA of release😀? On which day in May?

**Comment by weidongxu-microsoft** [comment]
@hoya1101 

The azure-core-management (that have the change) will be about end of first week of May.

**Comment by hoya1101** [comment]
Hi @weidongxu-microsoft , thanks a lot for all you've shared and done :)

**Comment by weidongxu-microsoft** [comment]
azure-core-management 1.6.0 released
https://github.com/Azure/azure-sdk-for-java/releases/tag/azure-core-management_1.6.0
