### ISSUE TITLE
Cosmos is giving high response when used with managed identity.

### ISSUE THREAD

**Issue by rhyashu** [Azure/azure-sdk-for-java#28236]
**Query/Question**
We have used Cosmos to query data using both connection string and MSI. We have observed that with MSI its taking extra time to get the response and our app is running slow really slow compared to the case if we use connection string.
When reviewing the diagnostic logs from both the environments (conn string vs MSI) we saw some differences in the **QueryPlan RequestTimeline**

**With Connection String**: 
[{"eventName":"connectionAcquired","startTimeUTC":"2022-04-05T11:45:31.503Z","durationInMicroSec":0},{"eventName":"connectionConfigured","startTimeUTC":"2022-04-05T11:45:31.503Z","durationInMicroSec":0},{"eventName":"requestSent","startTimeUTC":"2022-04-05T11:45:31.503Z","durationInMicroSec":0},{"eventName":"transitTime","startTimeUTC":"2022-04-05T11:45:31.503Z","durationInMicroSec":2000},{"eventName":"received","startTimeUTC":"2022-04-05T11:45:31.505Z","durationInMicroSec":0}]

**With MSI**:
[{""eventName"":""**connectionCreated**"",""startTimeUTC"":""2022-04-11T11:08:19.097Z"",""durationInMicroSec"":**15000**},{""eventName"":""connectionConfigured"",""startTimeUTC"":""2022-04-11T11:08:19.112Z"",""durationInMicroSec"":0},{""eventName"":""requestSent"",""startTimeUTC"":""2022-04-11T11:08:19.112Z"",""durationInMicroSec"":0},{""eventName"":""transitTime"",""startTimeUTC"":""2022-04-11T11:08:19.112Z"",""durationInMicroSec"":2000},{""eventName"":""received"",""startTimeUTC"":""2022-04-11T11:08:19.114Z"",""durationInMicroSec"":0}]

When connecting to cosmos using MSI, we are seeing an extra event in the Timeline **connectionCreated** which is coming for every lookup/query we are running in our app and is taking most of the response time.
But with connection string for every lookup/query we don't see this event every time we query cosmos and directly seeing  **connectionAcquired** event.

How can we pervent this connectionCreated event when conencting to cosmos using MSI

***Why is this not a Bug or a feature Request?***
Not sure as of now maybe an issue/bug.

**Setup (please complete the following information if applicable):**
 - OS: [Linux]
 - IDE: [Eclipse]
 - Library/Libraries: [azure-spring-data-cosmos:3.15.0 ]
 
 **Information Checklist**
 Kindly make sure that you have added all the following information above and checkoff the required fields otherwise we will treat the issuer as an incomplete report
- [ Y] Query Added
- [ Y] Setup information Added

**Comment by rhyashu** [comment]
This is how we are creating the cosmos config, for MSI tried with ManagedIdentityCredentials and Token Credentials and for connection string using keys just uncommenting the .key(properties.getKey()):

```
 @Bean
    public CosmosClientBuilder cosmosClientBuilder() {
    	
    	ManagedIdentityCredential managedIdentityCredential = new ManagedIdentityCredentialBuilder().clientId(clientId)
	            .build();
    	//TokenCredential tokenCredential = new ManagedIdentityCredentialBuilder().clientId(clientId).build();
        DirectConnectionConfig directConnectionConfig = DirectConnectionConfig.getDefaultConfig();

        return new CosmosClientBuilder()
            .endpoint(properties.getUri())            
            //.key(properties.getKey())
            .credential(managedIdentityCredential)
            .directMode(directConnectionConfig);
    }

   @Bean
    public CosmosConfig cosmosConfig() {
        return CosmosConfig.builder()
                           .responseDiagnosticsProcessor(new ResponseDiagnosticsProcessorImplementation())
                           //.enableDatabaseThroughput(autoscale, requestUnits)
                           //.enableQueryMetrics(properties.isQueryMetricsEnabled())
                           .build();
    }
```

**Comment by kushagraThapar** [comment]
@rhyashu - 
`connectionCreated` is first time when connection is created and `connectionAcquired` happens when the connection is already present, and it is just acquired from the connection pool. These don't have to do anything with MSI or connection string.. it is irrelevant. `connectionAcquired` is reusing the same connection, as it has already been created. 

Even for MSI or using connection string, in both cases, you will see first few connections as `connectionCreated` and then rest of them getting re-used and will show `connectionAcquired`.

**Comment by rhyashu** [comment]
Hi @kushagraThapar , 
Thanks for the update, will double check on that.
But we are seeing ConnectionCreated for every time we are going to query the cosmos. That's the issue we are facing.

**Comment by kushagraThapar** [comment]
Thanks @rhyashu  - I will investigate these diagnostics and will get back to you soon.
