### ISSUE TITLE
[Cosmos] Query direct execution with-out query-plan

### ISSUE THREAD

**Issue by kirankumarkolli** [Azure/azure-sdk-for-java#28275]
**Describe the solution you'd like**
Ability for application to by-pass query-pan and execute the query directly with BE

QueryPlan caching: can it include aggregates as well? 
Or direct pass through as option. 

ETA: TBD (**Risky**)
@xinlian12 to update it.

Main feature: #28266

**Comment by xinlian12** [comment]
Use disallowQueryPlanRetrieval, also added examples with PR: https://github.com/Azure/azure-sdk-for-java/pull/28431
