### ISSUE TITLE
[Cosmos] ConnectionStateListener to invalidate the replica which is reset (not all replicas)

### ISSUE THREAD

**Issue by kirankumarkolli** [Azure/azure-sdk-for-java#28270]
**Describe the solution you'd like**
ConnectionStateListener to invalidate the replica for which the TCP reset is received. 
AddressCaches still will serve the remaining replica's (for reads, write of-course needs to wait for refresh)

Main feature #28266

**Comment by xinlian12** [comment]
PR has merged
