### ISSUE TITLE
[Cosmos] Replica validation before usage: Async address refresh and validation 

### ISSUE THREAD

**Issue by kirankumarkolli** [Azure/azure-sdk-for-java#28271]
**Describe the solution you'd like**
Async address refresh (regular READ address resolutions will still continue)
New replicas are validating through connecting and only then put into partition-addresses for usage
Background periodic async refresh in-case of connectivity failures
Enable this feature only if CX opted for all-replica connectivity (i.e. opted for OpenAsync equivalent)

ETA: July/2022
Main feature: #28266

**Comment by xinlian12** [comment]
PR has merged
