### ISSUE TITLE
Merge com.azure.resourcemanager into com:azure to make it included in com.azure:azure-sdk-bom

### ISSUE THREAD

**Issue by juergenbr** [Azure/azure-sdk-for-java#28281]
**Is your feature request related to a problem? Please describe.**
Problem:
The fractured Azure SDK causes an increasing amount of issues due to mismatching versions across different sub-SDKs.
A central BOM covering all parts of the SDK would help simplify the dependency management.

**Describe the solution you'd like**
One BOM covering all parts of the Azure SDK and having everything in the `com.azure` group, similar as with AWS SDK `software.amazon.awssdk:bom`
Example:
BOM: `com.azure:azure-sdk-bom`
Core SDK: `com.azure:azure-core`
Resource Manager SDK: `com.azure:resourcemanager`

**Describe alternatives you've considered**
Include group `com.azure.resourcemanager` in BOM

**Additional context**
Gradle sample of current situation:
```implementation enforcedPlatform('com.azure:azure-sdk-bom:1.2.0')
implementation("com.azure:azure-identity")
implementation("com.azure:azure-core")
implementation("com.azure:azure-core-management")
implementation("com.azure.resourcemanager:azure-resourcemanager")
implementation("com.azure.resourcemanager:azure-resourcemanager-containerservice")
```
Output of gradle task `dependencies`
```
+--- com.azure.resourcemanager:azure-resourcemanager FAILED
+--- com.azure.resourcemanager:azure-resourcemanager-containerservice FAILED
```

**Information Checklist**
Kindly make sure that you have added all the following information above and checkoff the required fields otherwise we will treat the issuer as an incomplete report
- [x] Description Added
- [x] Expected solution specified

**Comment by joshfree** [comment]
Hi @juergenbr, thank you for sharing feedback with us.  I will take your comments in this post as feedback and share them with the right teams.  @pallavit could you please also follow up?

/cc @weidongxu-microsoft

**Comment by weidongxu-microsoft** [comment]
One thing that might not work very well with scheduled BOM release, is that management-plane release data could sometimes being for flexible.
E.g. in May we got request from Spring Cloud to wait for one of their GA api-version, which in worst case will delay management-plane release to 3rd or 4th week of May (ARM onboard process takes about a week). I am not sure whether this kind of difference in release data is compatible with BOM release.

**Comment by valfirst** [comment]
@joshfree @pallavit @weidongxu-microsoft do you have any updates on this issue?

**Comment by akonarska** [comment]
Hey Team, is there any update here? Any timeline when this could be available?

**Comment by golosegor** [comment]
Hey tem, any update here?

**Comment by weidongxu-microsoft** [comment]
@srnagar What is your opinion?

If you think it be beneficial to put azure-resourcemanager to BOM, we can adjust the release date of mgmt lib, to align with data-plane libs (and do monthly release before BOM release).
