### ISSUE TITLE
Add SPI Loading Configurations

### ISSUE THREAD

**Issue by alzimmermsft** [Azure/azure-sdk-for-java#28291]
Currently, `HttpClient` and `JsonSerializer` implementations are loaded from the classpath using `ServiceProvider`s. Unfortunately, the loading logic will take the first found implementation on the classpath and use that. At least for `HttpClient`, every HTTP-based SDK by default includes `azure-core-http-netty` as a dependency otherwise all applications using HTTP-based SDKs would need to include an `HttpClient` implementing library as a dependency. This results in `azure-core-http-netty` being on the classpath by default and if another implementation, such as `azure-core-http-okhttp`, needs to be used all libraries including `azure-core-http-netty` need to exclude it as a dependency to ensure the OkHttp-based implementation is used. Ensuring the dependency is excluded is error prone as it's hard to determine which libraries may include `azure-core-http-netty` as a direct or transitive dependency and bringing it into the classpath. Due to this, we should investigate offering configurations to control which SPI implementation is used, such as a configuration to use a certain implementation based on name (maybe reactor-netty for `azure-core-http-netty` and okhttp for `azure-core-http-okhttp`).

**Comment by lmolkova** [comment]
Should we consider it done with https://github.com/Azure/azure-sdk-for-java/pull/30894 and `Providers` pattern?
