### ISSUE TITLE
[FEATURE REQ] make the producer client share the same service bus client builder

### ISSUE THREAD

**Issue by jialigit** [Azure/azure-sdk-for-java#28313]
**Is your feature request related to a problem? Please describe.**

Consider make the producer client share the same service bus client builder

[DefaultServiceBusNamespaceProducerFactory.java](https://github.com/Azure/azure-sdk-for-java/pull/28245/files/a2784b446e0215007c340f71cda4b2abc4d0a9e6#diff-391fecb27234fae40658df1ac28e0338052639e59a8c076bedacd1d5b79c99c6)

**Describe the solution you'd like**
 The creation of physical connection to Service Bus requires resources. An application should share the connection
between clients which can be achieved by sharing the top level builder.

Refer the following:
(https://github.com/Azure/azure-sdk-for-java/tree/main/sdk/servicebus/azure-messaging-servicebus#sharing-of-connection-between-clients)

**Comment by stliu** [comment]
don't think this is still valid, closing it
