### ISSUE TITLE
How to use AAD Authentication across Microsoft Graph and Databases

### ISSUE THREAD

**Issue by lsegala** [Azure/azure-sdk-for-java#28319]
**Describe the bug**
I have functional requirement in my software. I want to integrate my legacy code with Azure AD, but I have a database with user and roles. In my case I want to integrate with Azure AD and syncronize my database with token info and roles in Microsoft Graph. So the system have a intermitent behavion, when I try to logout and success handler is called.

***Exception or Stack Trace***
Not available

**To Reproduce**
Try to logout

***Code Snippet***
pom.xml
```xml
<dependency>
	<groupId>com.azure.spring</groupId>
	<artifactId>azure-spring-boot-starter-active-directory</artifactId>
</dependency>
```

WebSecurityConfig.java
```java
@Configuration
public class WebSecurityConfig extends AADWebSecurityConfigurerAdapter {
	@Autowired
	UserRepository repository;

	public Optional<UserModel> getUserAuthenticated() {
		return repository.findByUserName(SecurityContextHolder.getContext().getAuthentication().getName());
	}

	@Override
	protected void configure(HttpSecurity httpSecurity) throws Exception {
		super.configure(httpSecurity);
	        httpSecurity.authorizeRequests()
		        .anyRequest().authenticated()
		        .and()
		        .oauth2Login()
		        .successHandler((request, response, authentication) -> {
			        final Optional<UsuarioModel> optUsuarioModel = getUserAuthenticated();
			        if(!optUsuarioModel.isPresent()){
				        response.sendRedirect("/create-user");
			        }else{
				        response.sendRedirect("/welcome");
			        }
		        });
	}

	@Bean
	public OAuth2UserService<OidcUserRequest, OidcUser> userService(UserRepository userRepository){
		return new CustomADOAuth2UserService(userRepository);
	}
}
```

UserController.java
```java
@Controller
public class UserController {
	@Autowired
	UserService userService;
	@Autowired
	OAuth2AuthorizedClientService graphAuthorizedClientService;

	@GetMapping("/create-user")
	public RedirectView success(HttpServletRequest request, HttpServletResponse response, @RegisteredOAuth2AuthorizedClient("graph") OAuth2AuthorizedClient graphAuthorizedClient) {
		final Authentication authentication = SecurityContextHolder.getContext().getAuthentication();
		final UserModel user = userService.create(login, authentication);

		Authentication newAuth = new UsernamePasswordAuthenticationToken(
				authentication.getPrincipal(),
				authentication.getCredentials(),
				emptyList()
		);

		SecurityContextHolder.getContext().setAuthentication(newAuth);
		graphAuthorizedClientService.saveAuthorizedClient(graphAuthorizedClient, newAuth);

		return new RedirectView("/clientes/page");
	}
}
```

WelcomeController.java
```java
@Controller
public class WelcomeController {
	@Autowired
	OAuth2AuthorizedClientService graphAuthorizedClientService;
	@Autowired
	UserService userService;

	@GetMapping("/welcome")
	public ModelAndView welcome(HttpServletRequest request, @RegisteredOAuth2AuthorizedClient("graph") OAuth2AuthorizedClient graphAuthorizedClient){
		final Authentication authentication = SecurityContextHolder.getContext().getAuthentication();

		final List<GroupADData> userGroups = getUserGroupsFromMSGraph(graphAuthorizedClient);
		final UserModel user = userService.findByUserName(authentication.getName());

		if(ofNullable(user.getRoles()).orElse(emptySet()).size() != userGroups.size()){
			userService.createRoles(usuario, userGroups);
			Authentication newAuth = new UsernamePasswordAuthenticationToken(
					authentication.getPrincipal(),
					authentication.getCredentials(),
					usuario.getRoles()
			);
			SecurityContextHolder.getContext().setAuthentication(newAuth);
			graphAuthorizedClientService.saveAuthorizedClient(graphAuthorizedClient, newAuth);
		}else{
			graphAuthorizedClientService.saveAuthorizedClient(graphAuthorizedClient, authentication);
		}

		return new ModelAndView("welcome");
	}
}
```

***Github Code to reproduce***
https://github.com/lsegala/spring-boot-azure-ad-problem

**Expected behavior**
When the user click in logout button (/logout), the application must be redirect to microsoft site to logout your account and not call successHandler, otherwise the user info will be created again and the user cannot logout.

**Screenshots**
Not available.

**Setup (please complete the following information):**
 - OS: Windows 10
 - IDE: IntelliJ
 - Library/Libraries: 
   - org.springframework.boot:spring-boot-starter-data-jpa:2.6.1
   - org.springframework.boot:spring-boot-starter:2.6.1
   - org.springframework.boot:spring-boot-starter-web:2.6.1
   - org.springframework.boot:spring-boot-starter-security:2.6.1
   - org.springframework.boot:spring-boot-starter-oauth2-client:2.6.1
   - com.azure.spring:azure-spring-boot:3.12.0
   - com.azure.spring:azure-spring-boot-starter-active-directory:3.12.0
   - com.azure.spring:azure-spring-boot-starter-keyvault-secrets:3.12.0
   - com.azure:azure-core:1.22.0
   - com.azure:azure-core-http-netty:1.9.1
   - com.azure:azure-identity:1.2.5
   - com.microsoft.azure:msal4j:1.11.0
   - com.microsoft.azure:msal4j-persistence-extension:1.1.0
   - com.microsoft.graph:microsoft-graph:5.13.0
   - com.microsoft.graph:microsoft-graph-core:2.0.10
 - Java version: OpenJDK 64-Bit Server VM 18.9 (build 11.0.10+9, mixed mode)
 - App Server/Environment: N/D
 - Frameworks: Spring Boot

**Additional context**
N/D

**Information Checklist**
Kindly make sure that you have added all the following information above and checkoff the required fields otherwise we will treat the issuer as an incomplete report
- [ ] Bug Description Added
- [ ] Repro Steps Added
- [ ] Setup information Added

**Comment by joshfree** [comment]
Hello @lsegala, thank you for posting this question and including very thorough details on the environment including sample code.  @g2vinay @scottaddie can you please follow up with @lsegala?

**Comment by lsegala** [comment]
Hello! Thanks all!

**Comment by lsegala** [comment]
Added github code link to help reproduce the problem.

**Comment by g2vinay** [comment]
@lsegala 
Thank you for reporting this.
I will take a look at the provided code.

In the meantime, @stliu from our team is working on a JDBC plugin which provides MSI authentication (via AAD) for databases, you can try that out to see if that helps resolve your issue.

**Comment by lsegala** [comment]
Thank you! I'll take a look and test.

**Comment by g2vinay** [comment]
Closing this issue, 
@Isegala, let us know if you still need further assistance.
