### ISSUE TITLE
[FEATURE REQ] Expose sessionId from ServiceBusReceiverClient

### ISSUE THREAD

**Issue by lidkowiak** [Azure/azure-sdk-for-java#28338]
**Is your feature request related to a problem? Please describe.**
It's convenient to know sessionId obtained from `serviceBusSessionReceiverClient.acceptNextSession()`. 
Currently we use reflection to get that.

**Describe the solution you'd like**
Public accessibly getSessionId() method in ServiceBusReceiverClient

**Describe alternatives you've considered**
Currently we use reflection to get that.

**Additional context**

No

**Information Checklist**
Kindly make sure that you have added all the following information above and checkoff the required fields otherwise we will treat the issuer as an incomplete report
- [x] Description Added
- [x] Expected solution specified

**Comment by joshfree** [comment]
Hi @lidkowiak thank you for posting this ServiceBus SDK feature request.  @ki1729 @jsquire could you please follow up with @lidkowiak 

/cc @Azure/azsdk-sb-java

**Comment by ki1729** [comment]
@lidkowiak Can you please describe your use case some more? That we can figure how best to surface the data that you need.

**Comment by jsquire** [comment]
@ki1729:  The other languages all expose a session identifier on their message session or session receiver.   Unless I'm reading incorrectly, this appears to be missing in the Java implementation.  It appears that `acceptNextSession` returns a `ServiceBusReceiverAsyncClient` using a set of options with the session id specified, but there is no way for callers to inspect the id.   Can you please confirm?   If I'm correct, let's please schedule adding a getter for the id that would pair with the existing `getSessionState` member?

*References:*

- [ServiceBusSessionReceiver (.NET)](https://github.com/Azure/azure-sdk-for-net/blob/main/sdk/servicebus/Azure.Messaging.ServiceBus/src/Receiver/ServiceBusSessionReceiver.cs#L32)
- [MessageSession (JS)](https://github.com/Azure/azure-sdk-for-js/blob/main/sdk/servicebus/service-bus/src/session/messageSession.ts#L80)
- [ServiceBusSession (Python)](https://github.com/Azure/azure-sdk-for-python/blob/main/sdk/servicebus/azure-servicebus/azure/servicebus/_servicebus_session.py#L53)

**Comment by ki1729** [comment]
@jsquire : Ah thanks for the pointers here! Sure, I should be able to include this in current cycle, so we should have this out by end of this month

**Comment by ki1729** [comment]
PR merged. Change will be a part of 7.9.0 release
