### ISSUE TITLE
[BUG]JMS service bus durable subscription has been created in SDK constantly 

### ISSUE THREAD

**Issue by Scarlettliuyc** [Azure/azure-sdk-for-java#28331]
**Describe the bug**
HI team,
We have an issue with JMS azure-spring-boot-starter-servicebus-jms 3.9
The Service Bus subscriptions were created in the SDK.
But it always pops up errors in Service Bus backend. I
t explained about durable [Creating Durable Subscriptions (The Java EE 6 Tutorial) (oracle.com)](https://docs.oracle.com/cd/E19798-01/821-1841/bncgd/index.html)
"A durable subscriber registers a durable subscription by specifying a unique identity that is retained by the JMS provider. Subsequent subscriber objects that have the same identity resume the subscription in the state in which it was left by the preceding subscriber. If a durable subscription has no active subscriber, the JMS provider retains the subscription’s messages until they are received by the subscription or until they expire." So we know it could not recreate before it expire.

But the error about "Microsoft.ServiceBus.Messaging.ClientAffineManagementConflictOperationException: Cannot create a new consumer on subscriber <subscirption_name>$<clientid>$D because there is already a subscriber using the same name with an active consumer on the same or different topic." popup every 1-2 minutes. 

***Exception or Stack Trace***
Add the exception log and stack trace if available
Microsoft.ServiceBus.Messaging.ClientAffineManagementConflictOperationException: Cannot create a new consumer on subscriber <subscirption_name>$<clientid>$D because there is already a subscriber using the same name with an active consumer on the same or different topic." 
***Code Snippet***
Add the code snippet that causes the issue.
Code here :
@JmsListener(destination = "email_topic", containerFactory = "topicListenerContainerFactory", subscription = "<subscritpion name>")
}
 

@Bean
public JmsListenerContainerFactory<?> topicListenerContainerFactory(ConnectionFactory connectionFactory,
        DefaultJmsListenerContainerFactoryConfigurer configurer) {
    DefaultJmsListenerContainerFactory factory = new DefaultJmsListenerContainerFactory();
    // This provides all boot's default to this factory, including the message converter
    configurer.configure(factory, connectionFactory);
    factory.setPubSubDomain(true);
    factory.setSubscriptionDurable(true);
    // You could still override some of Boot's default if necessary.
    return factory;
}

**Expected behavior**
This program could not run constantly ,it only initialize at first time 

**Screenshots**

**Setup (please complete the following information):**
   <dependency>
      <groupId>com.azure.spring</groupId>
      <artifactId>azure-spring-boot-starter-servicebus-jms</artifactId>
      <version>3.9.0</version>
   </dependency>

**Information Checklist**
Kindly make sure that you have added all the following information above and checkoff the required fields otherwise we will treat the issuer as an incomplete report
- [x] Bug Description Added
- [x ] Repro Steps Added
- [x ] Setup information Added

**Comment by yiliuTo** [comment]
@Scarlettliuyc thanks for reporting this. Currrently I cannot reproduce the error with the provided information. Hope we could get more log information from the customer side to locate the root cause of why are there repeated attempts to create consumers.
