### ISSUE TITLE
Add Key Vault quickstart guide for java

### ISSUE THREAD

**Issue by lenala** [Azure/azure-sdk-for-java#2834]
Add java quickstart to https://docs.microsoft.com/en-us/azure/key-vault/

**Comment by joshfree** [comment]
Thanks for reporting this @lenala -- @kaerm is tracking our docs.microsoft.com update for Preview 5.  @kaerm could you comment?

/cc @g2vinay

**Comment by kaerm** [comment]
Currently in the process of writing! //cc: @msmbaldwin

**Comment by kaerm** [comment]
And done: https://docs.microsoft.com/en-us/azure/key-vault/quick-create-java
