### ISSUE TITLE
[BUG] BlobItem.isPrefix() returns either `Boolean.TRUE` or `null`.

### ISSUE THREAD

**Issue by krystiangorecki** [Azure/azure-sdk-for-java#28347]
**Describe the bug**
com.azure.storage.blob.models.BlobItem#isPrefix returns either `Boolean.TRUE` or `null`. It never returns `Boolean.FALSE`.

**To Reproduce**
- call `blobContainerClient.listBlobs(...)` or `blobContainerClient.listBlobsByHierarchy(...)` to get at least one blob which is not a prefix/directory
- call isPrefix() for that blob
- for the following code snippet the output is:
   `Found blob, getName: foo/bar, isPrefix? null`

***Code Snippet***
```
        // BlobClient blobClient = blobContainerClient.getBlobClient("foo/bar");
        // blobClient.uploadFromFile("/home/xxx/xxx.png");

        ListBlobsOptions options = new ListBlobsOptions().setPrefix("foo/");

        blobContainerClient.listBlobs(options, null)
            .forEach(blob -> {
                System.out.println("Found blob, getName: " + blob.getName() + ", isPrefix? " + blob.isPrefix());
            });
```
OR
```
        // BlobClient blobClient = blobContainerClient.getBlobClient("foo/bar");
        // blobClient.uploadFromFile("/home/xxx/xxx.png");

        ListBlobsOptions options = new ListBlobsOptions().setPrefix("foo/bar");

        blobContainerClient.listBlobsByHierarchy("/", options, null)
            .forEach(blob -> {
                System.out.println("Found blob, getName: " + blob.getName() + ", isPrefix? " + blob.isPrefix());
            });
```

**Expected behavior**
Return `Boolean.FALSE` instead of `null`.

**Setup:**
 - OS: Ubuntu 20.04
 - Library/Libraries: com.azure:**azure-storage-blob**:12.15.0
 - Java version: openjdk version "11.0.14.1" 2022-02-08

**Information Checklist**
Kindly make sure that you have added all the following information above and checkoff the required fields otherwise we will treat the issuer as an incomplete report
- [x] Bug Description Added
- [x] Repro Steps Added
- [x] Setup information Added

**Comment by rickle-msft** [comment]
Hi, @krystiangorecki. This is actually expected behavior as it reflects the service's response, which either sends back true or nothing. Your confusion is understandable, though. @alzimmermsft Would it be considered a breaking change to return false instead of null, which might be a better customer experience?

**Comment by joshfree** [comment]
> Hi, @krystiangorecki. This is actually expected behavior as it reflects the service's response, which either sends back true or nothing. Your confusion is understandable, though. @alzimmermsft Would it be considered a breaking change to return false instead of null, which might be a better customer experience?

Technically, it would be a breaking change to change the return value of an existing case that someone is depending on.  I would discuss this with the storage crew internally however - there's a case to be made especially if the API is documented already that Boolean.FALSE is an expected return type and other languages are returning it over null.

**Comment by rickle-msft** [comment]
@joshfree Looks like we're a little split on this. Python I think just doesn't add this value to the properties dictionary and .net always returns true or false.

**Comment by rickle-msft** [comment]
@joshfree Can we treat this as a bug and fix it? Or do we treat it as a docs bug and change the docs?
