### ISSUE TITLE
Establish external dependency baseline and testing strategy.

### ISSUE THREAD

**Issue by kasobol-msft** [Azure/azure-sdk-for-java#28352]
Spring Boot customers might be overriding dependency versions that SDKs ship with.
We should identify intersection between SDK and Spring BOM and make sure that dependency versions defined by supported spring lines are runtime compatible with SDKs.

For example:
- define place where we can configure min versions of SDK dependencies.
- add jobs in test matrixes that use those min versions.

**Comment by alzimmermsft** [comment]
The Spring CI recently added additional jobs which changes the Spring Boot version to the minor baseline version (ex 2.6.6 -> 2.6.0) and runs testing again. We could investigate whether the same concept would work for us, I'd initially aim for testing:

- Jackson
- Reactor Core
- Reactor Netty

as they're our three most used dependencies. 

This should eventually span minor versions as well once we have the capability to shim minor versions.

**Comment by lmolkova** [comment]
Related: #25244, #20514

**Comment by lmolkova** [comment]
related: #30198

**Comment by alzimmermsft** [comment]
This has been standardized and being used currently for testing different versions of Reactor, Reactor Netty, and Jackson
