### ISSUE TITLE
How to do Bean validation 

### ISSUE THREAD

**Issue by abhinav-jain09** [Azure/azure-sdk-for-java#2835]
Hi guys,

I am developing the rest service with Azure function I am not sure how can I do request parm validation.For example I would like to check if any of the request paramater is null . offcource I can check one by one but is there any method where I can pass my request and say i would like to check if this request parameters is empty or null . some kind of framework I am looking for

**Comment by praries880** [comment]
@jianghaolu Pinging to see if you got a chance to look into this issue

**Comment by joshfree** [comment]
Closing old issue from 2019.
