### ISSUE TITLE
[BUG] Cosmos DB getCurrentState() does not work without starting the Change feed processor

### ISSUE THREAD

**Issue by vmaheshw** [Azure/azure-sdk-for-java#28368]
**Describe the bug**
getCurrentState() method does not return anything, if the ChangeFeedProcessor is not started. This functionality is critical to keep the monitoring and processing separate. If we start the ChangeFeedProcessor, the monitoring object will start handling the changes.

***Exception or Stack Trace***

**To Reproduce**
1. Create the ChangeFeedProcessor.
2.  Call getCurrentState() without starting it.
3.  Ensure that it is for a valid lease.

***Code Snippet***
leaseStoreManager is set to null, on using debugger and is only initialized on start() call.

**Expected behavior**
No need to start the changeFeedProcessor for getEstimateLag and getCurrentState

**Screenshots**

**Setup (please complete the following information):**
 - OS: [e.g. iOS] iOs
 - IDE: [e.g. IntelliJ] Intellij
 - Library/Libraries: [e.g. com.azure:azure-core:1.16.0 (groupId:artifactId:version)] azure-core:4.28.0
 - Java version: [e.g. 8] 11

**Additional context**

**Information Checklist**
Kindly make sure that you have added all the following information above and checkoff the required fields otherwise we will treat the issuer as an incomplete report
- [x] Bug Description Added
- [x] Repro Steps Added
- [x] Setup information Added

**Comment by milismsft** [comment]
Fixed
