### ISSUE TITLE
Fix Failing ResourceManagerHybrid Tests

### ISSUE THREAD

**Issue by alzimmermsft** [Azure/azure-sdk-for-java#28369]
Resource manager hybrid tests began failing recently due to `IllegalAccessError` exceptions. I believe the root cause is due to mixed dependencies in the hybrid libraries where there is some dependencies on the non-hybrid libraries for testing, namely `azure-resourcemanager-msi`. 

Recently, there was a regeneration of code that added a new call into `MsiManager` to use a convenience static method instead of a builder, https://github.com/Azure/azure-sdk-for-java/blob/main/sdk/resourcemanager/azure-resourcemanager-msi/src/main/java/com/azure/resourcemanager/msi/MsiManager.java#L96. But, unfortunately, for some of the hybrid libraries they're overriding the version of `azure-resourcemanager-authorization` to be the hybrid version which has that API as a private static still, https://github.com/Azure/azure-sdk-for-java/blob/main/sdk/resourcemanagerhybrid/azure-resourcemanager-authorization/src/main/java/com/azure/resourcemanager/authorization/AuthorizationManager.java#L66, instead of the regenerated public static, https://github.com/Azure/azure-sdk-for-java/blob/main/sdk/resourcemanager/azure-resourcemanager-authorization/src/main/java/com/azure/resourcemanager/authorization/AuthorizationManager.java#L74.

Right now, this appears to only be a test bug as the hybrid libraries haven't been released since the regeneration, but it is possible to run into this by pulling in the latest version of `azure-resourcemanager-msi` while using the hybrid version of `azure-resourcemanager-authorization`.

**Comment by alzimmermsft** [comment]
@weidongxu-microsoft, could you follow-up on this issue?

**Comment by weidongxu-microsoft** [comment]
Thanks Alan for finding out this loops of dependency from hybrid to global then back to hybrid.

I guess I will just sync the changed from global to hybrid, so that the entry of Manager would be same.

**Comment by weidongxu-microsoft** [comment]
However this could be a runtime error, if hybrid actually uses later version of msi (2.14.0 or above).
So we might need to release a new version of hybrid.
