### ISSUE TITLE
[QUERY] Swap OS disk for a VM not working after migrating to resource manager library

### ISSUE THREAD

**Issue by Prudvidhard** [Azure/azure-sdk-for-java#28377]
**Query/Question**
We want to swap OS disk for a VM.
Code we are using:
// Create new managed disk
Disk diskFromSnapshot = azureInstance.disks()
					.define(diskProperName)
					.withRegion(machine.region())
					.withExistingResourceGroup(resourceGroup)
					.withWindowsFromVhd(snapshotPath)
					.withStorageAccountName(vhdStorageAccountName)
					.withSizeInGB(osDisksizeInGB)
					.withSku(currentDiskSkuType)
					.create();
// Deallocate the VM
machine.deallocate();
// Update OS disk
machine.storageProfile().osDisk().withName(diskProperName).managedDisk().withId(diskFromSnapshot.id());
machine.update().apply();

We are migrating to resourcemanager library. Above code was working fine with https://mvnrepository.com/artifact/com.microsoft.azure/azure but not working with the resource manager library. This code executes sucessfully but VM OS disk is not updating. Please help.

***Why is this not a Bug or a feature Request?***
We are not sure if this is a bug in SDK.

**Setup (please complete the following information if applicable):**
 - OS: [e.g. iOS]: Windows
 - IDE: [e.g. IntelliJ]: Intellij
 - Library/Libraries: [e.g. com.azure:azure-core:1.16.0 (groupId:artifactId:version)]: azure-resourcemanager:2.10.0
 
 **Information Checklist**
 Kindly make sure that you have added all the following information above and checkoff the required fields otherwise we will treat the issuer as an incomplete report
- [x] Query Added
- [x] Setup information Added

**Comment by joshfree** [comment]
Hi @Prudvidhard, thank you for reaching out to us via this GitHub issue.  @weidongxu-microsoft could you please take a look?

**Comment by weidongxu-microsoft** [comment]
@Prudvidhard 

Following code is not a standard solution for swap OS disk. Modification should be done between `update()` and `apply()`.
```
// Update OS disk
machine.storageProfile().osDisk().withName(diskProperName).managedDisk().withId(diskFromSnapshot.id());
machine.update().apply();
```

@XiaofeiCao 
Could you help see if we had standard code to swap OS disk? If no, would you support it?

**Comment by XiaofeiCao** [comment]
OK, I'm on it.

**Comment by Prudvidhard** [comment]
@weidongxu-microsoft, @XiaofeiCao both original and new disks are managed disks.

**Comment by Prudvidhard** [comment]
> Could you help see if we had standard code to swap OS disk? If no, would you support it?
@weidongxu-microsoft, @XiaofeiCao  does this mean the current resourcemanager SDK may not support swapping os disk?

**Comment by weidongxu-microsoft** [comment]
@Prudvidhard

It is not well supported in convenient code. But you can always send a PATCH directly via 
```
azure.virtualMachines().manager().serviceClient().getVirtualMachines()
        .update("rg", "vm", new VirtualMachineUpdateInner());
```

Before XIaofei solve this, you can either use above PATCH call, or this modified version of your hack (it is still a hack, but any modification should always happen between `update` and `apply`)
```
VirtualMachine.Update updating = machine.update();
machine.storageProfile().osDisk()
        .withName(diskProperName)
        .managedDisk()
        .withId(diskFromSnapshot.id());
machine = updating.apply();
```

**Comment by Prudvidhard** [comment]
Thanks @weidongxu-microsoft 
Our hack is working fine after the suggested change.
