### ISSUE TITLE
[Feature Req] Enable support to retrieve release pipeline name programmatically for a given artifact.

### ISSUE THREAD

**Issue by pallavit** [Azure/azure-sdk-for-java#28397]
In order to release patch scripts automatically - we need to get the name of the pipeline that releases a given SDK programmatically

One potential place where this can be plugged in is GetPackageProps.

**Comment by JimSuplizio** [comment]
@pallavit, @hallipr and @weshaggard 
As per our discussion and a follow up with @pallavit, I'm closing this work item out. The plan is to create one pipeline, capable of releasing everything, so this is no longer necessary.
