### ISSUE TITLE
[Feature Req] Enable support for releasing a set of libraries that span multiple SDK/areas

### ISSUE THREAD

**Issue by pallavit** [Azure/azure-sdk-for-java#28400]
This is part of the patch/BOM releases Epic, and the full description of the larger problem is in there (see linked Epic).

Our various templates use the ServiceDirectory parameter. This starts in the individual SDK/area/CI.yml files and threads its way through everything from sparse-checkout, building and testing, verification and releasing. The various template files, the way are now, will not work with a set of libraries from multiple SDK/areas. We are going to end creating special templates to handle this specific case but, whenever possible, we should taking chunks of common code from the existing templates and making smaller templates from those to reduce duplicate code that would allow a ServiceDirectory regardless if it's a parameter or something we have to compute. 

One thing of note, after things have been built the pipeline's published Artifacts will contain a Packages/PackageInfo directory that has <artifactName>.json files, which can be used later in the process, to pull the service directory for a given artifact. An example, in the ResourceManager pipeline one of the artifacts built is azure-resourcemanager-appplatform. Packages/PackageInfo/azure-resourcemanager-appplatform.json contains the following:
{
  "Name": "azure-resourcemanager-appplatform",
  "Version": "2.15.0-beta.1",
  "DevVersion": "2.15.0-alpha.20220425.3",
  "**DirectoryPath**": "sdk/resourcemanager/azure-resourcemanager-appplatform",
  "**ServiceDirectory**": "resourcemanager",
  "ReadMePath": "sdk/resourcemanager/azure-resourcemanager-appplatform/README.md",
  "ChangeLogPath": "sdk/resourcemanager/azure-resourcemanager-appplatform/CHANGELOG.md",
  "Group": "com.azure.resourcemanager",
  "SdkType": "mgmt",
  "IsNewSdk": true,
  "ArtifactName": "azure-resourcemanager-appplatform",
  "ReleaseStatus": "Unreleased"
}

**Comment by JimSuplizio** [comment]
I'm closing this. This was completed as part of this [PR](https://github.com/Azure/azure-sdk-for-java/pull/29798)
