### ISSUE TITLE
How to use Java SDK to check app service name availability

### ISSUE THREAD

**Issue by l3ender** [Azure/azure-sdk-for-java#28429]
**Query/Question**
We are wanting to use the Java SDK to check app service name availability. The [REST API has this feature](https://docs.microsoft.com/en-us/rest/api/appservice/check-name-availability/check-name-availability) but we are not sure how to use the SDK to accomplish the same.

***Why is this not a Bug or a feature Request?***
As the [REST API has this feature](https://docs.microsoft.com/en-us/rest/api/appservice/check-name-availability/check-name-availability), we believe it is possible in the SDK as well, but are unable to find out how it is accomplished.

**Setup (please complete the following information if applicable):**
 - OS: any
 - IDE: eclipse
 - Library/Libraries: com.azure.resourcemanager:azure-resourcemanager-appservice:2.14.0
 
 **Information Checklist**
 Kindly make sure that you have added all the following information above and checkoff the required fields otherwise we will treat the issuer as an incomplete report
- [x] Query Added
- [x] Setup information Added

**Comment by weidongxu-microsoft** [comment]
@l3ender 

This would do

```
            var availability = azure.webApps().manager().serviceClient().getResourceProviders()
                    .checkNameAvailability(new ResourceNameAvailabilityRequest()
                            .withName("funweidxu")
                            .withType(CheckNameResourceTypes.MICROSOFT_WEB_SITES));
```

**Comment by l3ender** [comment]
@weidongxu-microsoft Thank you!
