### ISSUE TITLE
[QUERY] Is AppServiceManager thread safe?

### ISSUE THREAD

**Issue by l3ender** [Azure/azure-sdk-for-java#28455]
**Query/Question**
Is the `com.azure.resourcemanager.appservice.AppServiceManager` class thread safe? Initializing (`AppServiceManager.authenticate()`) appears to acquire an access token, so I am not sure on best practice.

***Why is this not a Bug or a feature Request?***
It is a question on SDK usage.

**Setup (please complete the following information if applicable):**
 - OS: any
 - IDE: eclipse
 - Library/Libraries: com.azure.resourcemanager:azure-resourcemanager-appservice:2.14.0
 
 **Information Checklist**
 Kindly make sure that you have added all the following information above and checkoff the required fields otherwise we will treat the issuer as an incomplete report
- [x] Query Added
- [x] Setup information Added

**Comment by joshfree** [comment]
Hi @l3ender thank you for reaching out to us via this GitHub issue.  @weidongxu-microsoft could you please follow up?

**Comment by weidongxu-microsoft** [comment]
@l3ender 

Yes, this class is thread safe.

PS: the resource instance that corresponds to a remote Azure resource e.g. `WebApp` is not thread-safe, and you should avoid concurrent update on it (the `wepApp.update()..apply()` code flow.
