### ISSUE TITLE
Simplify and improve client pom.xml

### ISSUE THREAD

**Issue by JonathanGiles** [Azure/azure-sdk-for-java#2846]
Currently the GitHub repo contains three root-level pom.xml files. One of these is for building the management plane (pom.xml), and two of these are for the client SDK (pom.client.xml and pom.client.build.xml).

There should not be two separate pom.xml files for the client side. We should do the following:

- Remove the existing pom.client.xml file, and rename pom.client.build.xml to pom.client.xml.
- Introduce proper dependency versioning management for all libraries required by Key Vault data-plane.
- Remove unnecessary configuration from the Key Vault pom.xml - this should become exceedingly minimal.
- Introduce proper tooling support for spotbugs, checkstyle, and JavaDoc. Ensure issues result in build failures.
- Resolve all build failures, or add exceptions.

This should import (by copy / paste / edit) the files from the [Microsoft/maven-java-parent](https://github.com/Microsoft/maven-java-parent) project.

**Comment by weshaggard** [comment]
@JonathanGiles has this been addressed with the changes we made in https://github.com/Azure/azure-sdk-for-java/issues/3485?
