### ISSUE TITLE
[FEATURE REQ] GatewayConnectionConfig / AsyncCosmosClient should use username and password of ProxyOptions

### ISSUE THREAD

**Issue by StefanJann** [Azure/azure-sdk-for-java#28466]
When attempting to connect to an azure cosmos-db from behind a proxy (which requires username and password) using the Cosmos DB Java API, then I always get an error "407 authenticationrequired". 

Proxying with username/password seems to be an unimplemented feature, according to the javadoc https://azuresdkdocs.blob.core.windows.net/$web/java/azure-cosmos/latest/com/azure/cosmos/GatewayConnectionConfig.html#setProxy(com.azure.core.http.ProxyOptions)
which says "Username and password will be ignored."

I use the example project for spring-data integration with cosmos-db that uses the following dependencies:

```
<properties>
        <spring.boot.version>2.3.3.RELEASE</spring.boot.version>
        <azure.spring.data.cosmos.version>3.0.0</azure.spring.data.cosmos.version>
    </properties>

    <dependencies>
        <dependency>
            <groupId>com.azure</groupId>
            <artifactId>azure-spring-data-cosmos</artifactId>
            <version>${azure.spring.data.cosmos.version}</version>
        </dependency>
..
```

My feature request is that the cosmosdb client library supports proxying using username/password as well.

This seems to be the case already in other implementations, if I can believe the docs under https://docs.microsoft.com/en-us/azure/developer/java/sdk/proxying

**Comment by kushagraThapar** [comment]
This is done.
