### ISSUE TITLE
Add session token sent in the request to the backend in request diagnostics

### ISSUE THREAD

**Issue by xinlian12** [Azure/azure-sdk-for-java#28478]
To simplify session consistency investigations it would be useful to have the session token being sent to the backend/Gateway included in request diagnostics logs. The session token is scoped to the targeted partition in most cases - so at least in those cases it should not be a lot of overhead adding it to the diagnostics.

.Net link: https://github.com/Azure/azure-cosmos-dotnet-v3/issues/3107

**Comment by simorenoh** [comment]
PR: https://github.com/Azure/azure-sdk-for-java/pull/29516

**Comment by FabianMeiswinkel** [comment]
requestSessionToken is available in the meantime in the diagnostics
