### ISSUE TITLE
[FEATURE REQ] Delete spring-cloud-function-context;3.2.3 after upgrade to Spring Cloud 2021.0.2

### ISSUE THREAD

**Issue by chenrujun** [Azure/azure-sdk-for-java#28504]
# Background

Please refer to https://github.com/Azure/azure-sdk-for-java/pull/28458 to get more information.

# Goal

Delete spring-cloud-function-context;3.2.3 after upgrade to Spring Cloud 2021.0.2

**Comment by saragluna** [comment]
Closed in #28562.
