### ISSUE TITLE
Tasks for Spring Boot 2.7.0-RC1 (2.7.0 GA on 2022-05-19)

### ISSUE THREAD

**Issue by chenrujun** [Azure/azure-sdk-for-java#28503]
### Context

Please refer to this issue to get more information: https://github.com/Azure/azure-sdk-for-java/wiki/Spring-Cloud-Azure-tasks-for-a-new-Spring-Boot-release#milestone-release-and-release-candidate

# Goal
Make sure Spring Cloud Azure libraries are compatible with Spring Boot 2.7.0-RC1.

# Solution

- [x] Create a new issue to track the following tasks. Sample: [#27864](https://github.com/Azure/azure-sdk-for-java/issues/27864).
- [x] Create **draft** PR to upgrade external dependencies' version according to spring-boot-dependencies and spring-cloud-dependencies. Refer to [related readme](https://github.com/Azure/azure-sdk-for-java/blob/aec4c6247ba7ba4de57dd866e3f5511ca4fbd387/sdk/spring/scripts/README.md) https://github.com/Azure/azure-sdk-for-java/pull/28571/
- [x] Run tests by commands:
  - `/azp run java - spring - tests`
  - `/azp run java - cosmos - tests`
  - `/azp run java - keyvault - tests`
- [x] Fix the test failures.
- [x] Close draft PR.

Sample PR: [#24670](https://github.com/Azure/azure-sdk-for-java/pull/24670).

**Comment by Netyyyy** [comment]
close in https://github.com/Azure/azure-sdk-for-java/pull/28571/
