### ISSUE TITLE
[FEATURE REQUEST] Support latest version of Spring Boot and Spring Cloud

### ISSUE THREAD

**Issue by chenrujun** [Azure/azure-sdk-for-java#28518]
This is an Epic to track the latest version support of Spring-Boot and Spring-Cloud.
### Context

1. Spring Boot will release a minor version every 6 months.  Refs: [spring-boot support](https://spring.io/projects/spring-boot#support).
2. Spring Cloud will release a major version every year. Refs: [Spring Cloud release train Spring Boot compatibility](https://spring.io/projects/spring-cloud).
3. Both Spring Boot and Spring Cloud will have patch releases. The release plan of Spring Boot and Spring Cloud can be got from [Spring Boot milestones](https://github.com/spring-projects/spring-boot/milestones) and [Spring Cloud milestones](https://github.com/spring-cloud/spring-cloud-release/milestones).
4. To support latest version of Spring Boot and Sprint Cloud, Tasks need to be done are written in this wiki: [Spring Cloud Azure tasks for a new Spring Boot release](https://github.com/Azure/azure-sdk-for-java/wiki/Spring-Cloud-Azure-tasks-for-a-new-Spring-Boot-release).

### Goal

1. Track all issued used to support latest version of Spring Boot and Spring Cloud.
2. Do effort estimate in monthly planning meeting.

### Solution
 - [x] #27865
 - [ ] https://github.com/Azure/azure-sdk-for-java/issues/32330
 - [x] #31654 
 - [x] https://github.com/Azure/azure-sdk-for-java/issues/31113
 - [x] https://github.com/Azure/azure-sdk-for-java/issues/30571
 - [x] #30094
 - [x] #29658
 - [x] #28726
 - [x] #28503
 - [x] #27864
 - [x] #28498
 - [x] #27989
 - [x] #27863
 - [x] #26887

**Comment by stliu** [comment]
no need to track this
