### ISSUE TITLE
Jenkins Slave is consuming a lot of memories, we should try to reduce it. 

### ISSUE THREAD

**Issue by gcheng** [Azure/azure-sdk-for-java#286]
![ReduceMemoryConsumption](https://f.cloud.github.com/assets/1541773/223994/ab1b4e0e-85c8-11e2-97c2-4fa0b02407a8.JPG)

**Comment by tianya2010** [comment]
Hi cheng, we are using jenkins kubernetes plugin to set up the distributed test framework. We found that the jnlp container in the jenkins slaves always consume more than 200M memories. How did you fix this problem?
 Thanks for your help.@gcheng

**Comment by venh** [comment]
I have a Windows 7 Ultimate machine (with 8 GB RAM) slave on which Jenkins-Slave Agent service is running. Even though jobs are not running and I tried restarting the service, still the physical memory consumption is not going down.
