### ISSUE TITLE
Wrong link in document: "Azure Storage libraries for Java"

### ISSUE THREAD

**Issue by Vankog** [Azure/azure-sdk-for-java#28602]
Where: https://docs.microsoft.com/en-us/java/api/overview/azure/storage?view=azure-java-stable#available-packages, in the table of "Available packages":
Column "Available packages" the first row holds a link called "File", but leads to https://github.com/Azure/azure-sdk-for-java/tree/azure-storage-file-share_12.2.0/sdk/storage/azure-storage-queue 

I guess the correct link might be https://github.com/Azure/azure-sdk-for-java/tree/azure-storage-file-share_12.2.0/sdk/storage/azure-storage-file-share

Hope this helps,
Thanks!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 54aedee2-3be2-3a0f-2684-9186338a2d6f
* Version Independent ID: 8b2f0d3f-d959-d5bc-7b47-521248ac056c
* Content: [Azure Storage libraries for Java](https://docs.microsoft.com/en-us/java/api/overview/azure/storage?view=azure-java-stable)
* Content Source: [docs-ref-services/latest/storage.md](https://github.com/Azure/azure-docs-sdk-java/blob/master/docs-ref-services/latest/storage.md)
* Service: **storage**
* GitHub Login: @tamram
* Microsoft Alias: **tamram**

**Comment by rickle-msft** [comment]
Thanks, @Vankog.

@joshfree The package versions being referenced are also pretty out of date on this page. How can we get that one updated?

**Comment by SwathingBlock** [comment]
This seems to have been resolved now looking at the public version right now, I'd say this can be closed?
