### ISSUE TITLE
[BUG] Search SDK Cannot Sends Null Field Values with Document Merge or MergeOrUpload

### ISSUE THREAD

**Issue by Sreekanthm94** [Azure/azure-sdk-for-java#28610]
**Describe the bug**
We have a cx scenario where they are using java azure-search-documents library from com.azure to index documents. They noticed the library does not properly allow them to send a null value for a field during a merge or mergeOrUpload request. The documentation says this is supported by the API, but it does not work in the library. They need to be able to send a null value when indexing documents in order to remove the existing value from those fields in the index. This problem occurs in all cx environments and search services.

***Exception or Stack Trace***
No errors/exception. There is no changes to the document. 

**To Reproduce**
I'm able to repro the issue with the latest java SDK "11.4.9" and beta SDK"11.5.0-beta.8" where uploading/updating the document was successful with no error message and no changes reflected on the document(for both null values and non-null values). Also, I'm able to perform the upload operation using Rest Api without any issue and see the changes. Attaching the Rest Api collection and Java project that I used for reproducing the issue. 
  
**Note**: I noticed that the below Hotel class is not found in the azure-search-documents dependency so I add the Hotel class in my Java project. 
import com.azure.search.documents.models.Hotel;
***Code Snippet***
Attached
[azuresearch.zip](https://github.com/Azure/azure-sdk-for-java/files/8604885/azuresearch.zip)
[RestAPI_collection.zip](https://github.com/Azure/azure-sdk-for-java/files/8604892/RestAPI_collection.zip)
**Expected behavior**
Document needs to update/change based on merge or mergeOrUpload request using java [sdk.](url)

**Screenshots**

**Setup (please complete the following information):**
 - OS: [Windows]
 - IDE: [IntelliJ]
 - Library/Libraries: [e.g. com.azure:azure-search-documents:11.4.9 (groupId:artifactId:version)]
 RE: sdk/search/azure-search-documents/src/samples/java/com/azure/search/documents/IndexContentManagementExample.java
 - Java version: [e.g. 11] 
 - App Server/Environment: [local windows machine]
 - Frameworks: [Spring] 

If you suspect a dependency version mismatch (e.g. you see `NoClassDefFoundError`, `NoSuchMethodError` or similar), please check out [Troubleshoot dependency version conflict article](https://aka.ms/azsdk/java/dependency/troubleshoot) first. If it doesn't provide solution for the problem, please provide:
- verbose dependency tree (`mvn dependency:tree -Dverbose`)
- exception message, full stack trace, and any available logs

**Additional context**

**Information Checklist**
Kindly make sure that you have added all the following information above and checkoff the required fields otherwise we will treat the issuer as an incomplete report
- [ ] Bug Description Added
- [ ] Repro Steps Added
- [ ] Setup information Added

**Comment by alzimmermsft** [comment]
Thank you for filing this issue @Sreekanthm94, I'll follow-up once I've completed investigation on why this occurs.

**Comment by alzimmermsft** [comment]
Thank you for including a sample @Sreekanthm94, I do want to let you know it appears that it included application secrets. I'd recommend you roll those or delete the resources is able.

Looking at the sample, it appears that the `SearchClient` is leveraging the default `JsonSerializer` to handle converting the documents to JSON when sending document actions to the service and when receiving documents from the service. The default `JsonSerializer` is based on what the SDKs use internally for sending JSON to services which won't include null properties. To include null field values when sending documents my recommendation would be using [`JacksonJsonSerializer`](https://github.com/Azure/azure-sdk-for-java/tree/main/sdk/core/azure-core-serializer-json-jackson) or [`GsonJsonSerializer`](https://github.com/Azure/azure-sdk-for-java/tree/main/sdk/core/azure-core-serializer-json-gson) (whichever integrates better in the customers environment) with the custom `JsonSerializer` allowing for null values to be included in the JSON sent as part of the operation.

For `JacksonJsonSerializer` this may be:

```java
SearchClient client = new SearchClientBuilder()
      .endpoint(ENDPOINT)
      .credential(new AzureKeyCredential(ADMIN_KEY))
      .indexName(INDEX_NAME)
      .serializer(new JacksonJsonSerializerBuilder()
          .serializer(new ObjectMapper()
              // This will tell Jackson to serialize the property always.
              .setSerializationInclusion(JsonInclude.Include.ALWAYS))
          .build())
      .buildClient();
```

And for `GsonJsonSerializer` this may be:

```java
SearchClient client = new SearchClientBuilder()
      .endpoint(ENDPOINT)
      .credential(new AzureKeyCredential(ADMIN_KEY))
      .indexName(INDEX_NAME)
      .serializer(new GsonJsonSerializerBuilder()
          .serializer(new GsonBuilder()
              // This will tell GSON to serialize the property if it is null.
              .serializeNulls()
              .create())
          .build())
      .buildClient();
```

In both cases this is a simplification of configuring Jackson and GSON, so further investigation may be required to determine the configuration that are right for the customer's environment.

**Comment by alzimmermsft** [comment]
Hi @Sreekanthm94, wanted to follow-up to see if this was able to resolve the issue your customer is facing
