### ISSUE TITLE
[Storage] Hard deprecate old download APIs

### ISSUE THREAD

**Issue by kasobol-msft** [Azure/azure-sdk-for-java#28627]
There are 4 APIs in Storage that has been "soft deprecated" like this:
https://github.com/Azure/azure-sdk-for-java/blob/1da4fdf5222226a66381c691cf2d8ae7dd32242c/sdk/storage/azure-storage-blob/src/main/java/com/azure/storage/blob/specialized/BlobClientBase.java#L725-L735

The APIs are:
- `BlobClientBase.download(OutputStream stream)`
- `BlobClientBase.downloadWithResponse(OutputStream stream, BlobRange range,
        DownloadRetryOptions options, BlobRequestConditions requestConditions, boolean getRangeContentMd5,
        Duration timeout, Context context)`
- `BlobAsyncClientBase.download()`
- `BlobAsyncClientBase.downloadWithResponse(BlobRange range, DownloadRetryOptions options,
        BlobRequestConditions requestConditions, boolean getRangeContentMd5)`

These APIs should:
- Be hard marked with `@Deprecated`
- Javadoc warning should be converted into `@deprecated` section
- Samples using deprecated APIs must be updated

**Comment by ibrahimrabab** [comment]
PR was merged
