### ISSUE TITLE
What is GA timeline for Data Factory Management

### ISSUE THREAD

**Issue by binduchinnasamy** [Azure/azure-sdk-for-java#28629]
Hello - What is the GA timeline for https://docs.microsoft.com/en-us/java/api/overview/azure/resourcemanager-datafactory-readme?view=azure-java-preview?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 77ccdb97-9147-eb64-77eb-af12cb7b4495
* Version Independent ID: 69649646-eb5e-5166-69f4-fa3c27cc504e
* Content: [Azure Resource Manager DataFactory client library for Java](https://docs.microsoft.com/en-us/java/api/overview/azure/resourcemanager-datafactory-readme?view=azure-java-preview)
* Content Source: [docs-ref-services/preview/resourcemanager-datafactory-readme.md](https://github.com/Azure/azure-docs-sdk-java/blob/master/docs-ref-services/preview/resourcemanager-datafactory-readme.md)
* Service: **datafactory**

**Comment by joshfree** [comment]
Hi @binduchinnasamy thank you for reaching out to us via this GitHub issue.  @weidongxu-microsoft from the ARM SDK team will be able to follow up with you.

**Comment by weidongxu-microsoft** [comment]
@binduchinnasamy 
See that the changes of the service causes frequent breaking changes on SDK
https://github.com/Azure/azure-sdk-for-java/blob/main/sdk/datafactory/azure-resourcemanager-datafactory/CHANGELOG.md

Therefore, we currently do not have timeline for GA of the SDK. We have to wait for the service to stabilize.

**Comment by weidongxu-microsoft** [comment]
And a new PR that should not even get into 2018-06-01 api-version (that it had to be approved by Jeffrey, again)
https://github.com/Azure/azure-rest-api-specs/pull/18793
