### ISSUE TITLE
[BUG]Getting error:Input byte array has incorrect ending byte when using spring-cloud-azure-starter-storage-blob

### ISSUE THREAD

**Issue by yashaswi90** [Azure/azure-sdk-for-java#28637]
While I am trying to read a blob file from Java application using **https://docs.microsoft.com/en-us/azure/developer/java/spring-framework/configure-spring-boot-starter-java-app-with-azure-storage**, 

getting error
```
  Input byte array has incorrect ending byte at 88
	at java.util.Base64$Decoder.decode0(Base64.java:742)
	at java.util.Base64$Decoder.decode(Base64.java:526)
	at java.util.Base64$Decoder.decode(Base64.java:549)
	at com.azure.storage.common.implementation.StorageImplUtils.computeHMac256(StorageImplUtils.java:252)


Suppressed: java.lang.Exception: #block terminated with an error
		at reactor.core.publisher.BlockingSingleSubscriber.blockingGet(BlockingSingleSubscriber.java:99)
		at reactor.core.publisher.Mono.block(Mono.java:1707)
```
Kindly let me know how to connect to azure storage container and read file from azure storage using java code as it is giving this issue

**Comment by joshfree** [comment]
Hi @yashaswi90 thank you for reaching out to us via this GitHub issue.  @backwind1233 could you please follow up?

**Comment by backwind1233** [comment]
Hi @yashaswi90, can you give me a mini sample code  to help me reproduce the issue?

**Comment by yashaswi90** [comment]
Hi @backwind1233 issue is resolved actually i m passing the complete file name everywhere.

**Comment by yashaswi90** [comment]
Hi @backwind1233 issue is resolved now thanks actually i am passing the complete path of file in container.

But I am facing issue in azure activity log sdk in that i am using token credential with default azure credential  and passing all those details in azure resource manager but while i am executing the query on activity logs then it is giving error azure identity => error in getToken() call for scopes [https://management.core.windows.net//.default] cannot cast to string.
Please help me in that.

**Comment by backwind1233** [comment]
Hi @yashaswi90  this is our [spring-cloud-azure-starter-storage-blob](https://github.com/Azure-Samples/azure-spring-boot-samples/tree/spring-cloud-azure_v4.0.0/storage/spring-cloud-azure-starter-storage-blob/storage-blob-sample), can you try this?

can you give me some more info to help me reproduce the token credential issue?

**Comment by SimerpreetSingh9** [comment]
For me, the presence of a whitespace in the connection details (which were getting picked up from applicaion.properties) was causing this issue.
I believe the error message was not sufficient to look into the auth problems on the first look and this could be improved.
