### ISSUE TITLE
1.6.0 Build on Maven repository question

### ISSUE THREAD

**Issue by justinchenusa** [Azure/azure-sdk-for-java#2867]
Not sure if this is the right place but not sure where to ask this question.  

We tried to use the following Azure SDK from maven repo.
https://mvnrepository.com/artifact/com.microsoft.azure/azure/1.6.0

It appears that the SDK 1.6 on maven repo depends on 1.3 of azure-client-runtime and azure-client-authentication and annotations 1.2 is used.  

We saw some warnings on SinceVersion enum constants, V1_3_0, V1_4_0, etc, are unknown since they are not defined in azure-client-authentication 1.2.  

Are these warnings okay to ignore?  Can we simply replace azure-client-authentication 1.2 to 1.6?  
Thanks,

**Comment by jianghaolu** [comment]
You should be able to get the latest annotations from the 1.9.0 version of azure-annotations.

Also, this is going away in our next major version update (coming up early next year for management libraries).

**Comment by yungezz** [comment]
hi @ChenTanyi could you pls help to confirm this issue is fixed? thanks.

**Comment by ChenTanyi** [comment]
The warning has been fixed since 1.29.0.
