### ISSUE TITLE
Question for V12 Java SDK about BlobContainerClient.listBlobsByHierarchy

### ISSUE THREAD

**Issue by loudywen** [Azure/azure-sdk-for-java#28689]
Hi, in V12 Java SDK for `BlobContainerClient.listBlobsByHierarchy(String directory)`  method, it will return a `PagedIterable<T>` type. I would like to know that will this return all the items under a folder or  items by pages?

In my caller, once I get the PagedIterable<T> return. I will use a forEach to iterate the item (assuming it includes all the items in the folder). But I noticed that, ` PagedIterable<T>` also has streamByPage(String continuationToken) option. In my scenario, I need to get all the items at once only that's why I need to be sure that this method will not just return items by page.

**Comment by joshfree** [comment]
Hi @loudywen thank you for reaching out to us via this GitHub issue.  An expert from the Storage team will follow up with you shortly.

/cc @rickle-msft

**Comment by rickle-msft** [comment]
@loudywen Thank you for opening this issue. You can treat PagedIterable logically like an iterator that will yield all values in the folder at once without worrying about pages. By default, it simply gives a list of all the results. The byPage() operator is meant to give access to the underlying pages if you want to access something like a continuation token, but you won't see pages by default

**Comment by loudywen** [comment]
thx @rickle-msft
