### ISSUE TITLE
[QUERY] Inconsistent definition of WebApp between Azure SDK and Azure Portal

### ISSUE THREAD

**Issue by akonarska** [Azure/azure-sdk-for-java#28688]
**Query/Question**
When trying to list WebApps using SDK not all of the apps listed in Portal were returned from SDK. All of them are however returned when a more generic REST API call is used `GET https://management.azure.com/subscriptions/{subscriptionId}/providers/Microsoft.Web/sites?api-version=2021-02-01`. The only difference between those apps is their `kind`. The ones not returned had `kind=linux`.

According to [this docs](https://github.com/Azure/app-service-linux-docs/blob/master/Things_You_Should_Know/kind_property.md) anything that does not match the presented list is treated as WebApp by the Portal. 
The SDK on the other hand does this in [`WebAppsImpl`](https://github.com/Azure/azure-sdk-for-java/blob/main/sdk/resourcemanager/azure-resourcemanager-appservice/src/main/java/com/azure/resourcemanager/appservice/implementation/WebAppsImpl.java#L146):
```   
private static boolean isWebApp(SiteInner inner) {
        boolean ret = false;
        if (inner.kind() == null) {
            ret = true;
        } else {
            List<String> kinds = Arrays.asList(inner.kind().split(Pattern.quote(",")));
            if ((kinds.contains("app") || kinds.contains("api")) && !kinds.contains("kubernetes")) {
                ret = true;
            }
        }
        return ret;
    }
```

Questions:
1. Is this the expected behaviour for the SDK or should it behave more like Portal?
2. Is that possible to get all of the apps via SDK or we have to go with REST API?

***Why is this not a Bug or a feature Request?***
Not sure what should be the correct behaviour - the one in the Portal or the one in the SDK.

**Setup (please complete the following information if applicable):**
 - Library/Libraries: `com.microsoft.azure:azure-mgmt-appservice:1.41.2` but still present in `com.azure:azure-resourcemanager-appservice:2.14.0`
 
 **Information Checklist**
 Kindly make sure that you have added all the following information above and checkoff the required fields otherwise we will treat the issuer as an incomplete report
- [x] Query Added
- [x] Setup information Added

**Comment by joshfree** [comment]
Hi @akonarska, thank you for reaching out to us via this GitHub issue.  @weidongxu-microsoft could you please follow up?

**Comment by weidongxu-microsoft** [comment]
@akonarska

It is intended, as "functionapp" would be in `FunctionApp` class. `WebApp` and `FunctionApp` has different configuration and different action potentially only apply to one type.

Portal or CLI is not the target of the SDK design (though they work as a good reference).

If you want all apps, you may directly use `azure.webApps().manager().serviceClient().getWebApps().listByResourceGroup`.

**Comment by akonarska** [comment]
@weidongxu-microsoft 

I was not quite asking about `functionapp`. I can imagine why those are separate. 
The app in question only has a `kind=linux`, there is nothing more. It has neither 'functionapp' nor 'app' nor 'api'. It seems that this is a legacy `kind`. Unless you meant that there is no way to distinguish between `FunctionApp` and `WebApp` when `kind` is only `linux`.

Do I understand correctly that SDK is not supporting those legacy `kind` values and there is no plan to do it and only way would be to use the call you mentioned above?

**Comment by weidongxu-microsoft** [comment]
@akonarska 

OK. Got your point.
Yes, the real concern is if it is only `kind=linux`, we are not really sure what it is. And the [doc](https://github.com/Azure/app-service-linux-docs/blob/master/Things_You_Should_Know/kind_property.md) seems also not sure and merely treat it as Web App.

And SDK maintain this behavior for a very long time (e.g. [1.10.0 tag](https://github.com/Azure/azure-libraries-for-java/blob/v1.10.0/azure-mgmt-appservice/src/main/java/com/microsoft/azure/management/appservice/implementation/WebAppsImpl.java#L40-L42) as 2018).
It could be risky on behavior change (when user upgrading SDK then seeing a sudden increased number of sites as Web App), and they might apply unwanted change/action to these sites as most uses the Java SDK as automation.

Hence if your use case can be satisfied with `azure.webApps().manager().serviceClient().getWebApps().listByResourceGroup`, we probably do not want the change the behavior of WebAppsImpl.
Alternatively, one might consider just adding "app" to all these legacy sites (but you apparently cannot do this if you manage sites for 3rd party)?

If you really request this change on WebAppsImpl in SDK, we would have to go a long process to check potential internal users on how their tooling would behave (kind of wanting to avoid this, but it just me...), and I haven't getting to existing external users.

**Comment by akonarska** [comment]
@weidongxu-microsoft 

That makes sense from the SDK perspective, especially that those kinds are not supported anymore. It is confusing though to see it in the Portal as WebApp and then not getting it from SDK, but maybe that should be address by the Portal so it is more consistent with the SDK (maybe naming it differently, like Other). I'm not sure if that is a good solution or where to reach the Portal people so I would appreciate if you could drop them a word.

As per our use case - we should be fine using the solution you provided as a workaround to get all the apps with SDK.
And yeah, we don't own those sites and we don't really manage them - we monitor them on behalf of our customers. But it might be good for them to add `app` to those legacy sites and we can recommend them to do that. Could you maybe point me to some docs that describe how to change it? I was under the impression that `kind` is immutable.

**Comment by weidongxu-microsoft** [comment]
@akonarska 

Well, yes, `kind` appears not updatable during PATCH. Tried the PATCH, not error, but also no change. So adding "app" to `kind` is no go.

I will try check with person from WebApp backend on the history and whether SDK should accept "linux" (maybe even empty, if that is legacy Windows?).

**Comment by akonarska** [comment]
@weidongxu-microsoft 

Ok, thank you a lot. Please keep me posted.

**Comment by weidongxu-microsoft** [comment]
Talked with backend, the `kind` is defined pretty loose.

Make PR to add empty and `linux` as legacy WebApp https://github.com/Azure/azure-sdk-for-java/pull/28930
