### ISSUE TITLE
[Epic] Support Azure Identity for Spring ecosystems for Kafka

### ISSUE THREAD

**Issue by yiliuTo** [Azure/azure-sdk-for-java#28685]
This is the epic to track all issues about Azure Identity support for Spring Cloud Azure Kafka.

### Context
Currently Kafka developers can use Event Hubs in the same way as how they use Kafka since Event Hubs supports Kafka protocols as well. For the authentication part, native Kafka developers can use either [connection string](https://docs.microsoft.com/azure/event-hubs/event-hubs-for-kafka-ecosystem-overview#shared-access-signature-sas) as crendentials with other security configuratiosn or use [OAuth2](https://docs.microsoft.com/azure/event-hubs/event-hubs-for-kafka-ecosystem-overview#oauth-20) with customzied authentication call back handler and other security configuration.

We plan to support all Azure Identity based credentials for Spring Cloud Azure Kafka support, which includes all Azure Identity supported credential types and configuration options.

With Azure Identity-based credentials being supported, we can also achieve credential-free connection as well, which based on the `ManagedIdentityCredential` in Azure Identity. It can enable developers to use user-assigned/system-assigend managed identities in various Azure hosting environments to establish connection with Event Hubs via various spring ecosystems for kafka.

### Deliveries
The delivery resources include:
- [x] #28708
- [x] #28709
- [x] #29976
- [x] #29217
- [x] #28710
- [x] #28712
- [x] #29788
- [x] #29789

Move the following out from this epic:
- [ ] #30344

**Comment by saragluna** [comment]
Move #30344 out from this epic, and closing this issue now.
