### ISSUE TITLE
[Request]: Need Java API for ResourceHealth service 

### ISSUE THREAD

**Issue by justinchenusa** [Azure/azure-sdk-for-java#2868]
We are using Azure SDK 1.6 from [mvnrepository](https://mvnrepository.com/artifact/com.microsoft.azure/azure/1.6.0) and want to get metric values only when a resource is healthy/available/online.  

There are methods, such as <i>VirtualMachine.powerState()</i> and <i>SqlDatabase.status()</i>, seems to provide what is needed.  But, if we are getting MetricDefinitions out of a GenericResource, in which it does seem to have a way to determine its availability.

Are there ways to achieve this for a GenericResource?  If not, what would be the advised approach?  
Thank you for your help,

**Comment by yungezz** [comment]
hi @justinchenusa here it is https://search.maven.org/search?q=g:com.microsoft.azure.resourcehealth.v2017_07_01. will close the issue now. Feel free to create new issue if any other ask. thanks.
