### ISSUE TITLE
[BUG] Tomcat SSL Connectors using AzureKeyVault break Connectors using local java key store

### ISSUE THREAD

**Issue by ProphetManX** [Azure/azure-sdk-for-java#28696]
**Describe the bug**
Once we were able to get the AzureKeyVault Connector to load and pull the Cert from KeyVault, we found that our other Connection that was using a local Java KeyStore stopped working.  In my testing once I removed `F:\Tomcat\lib\azure-security-keyvault-jca-2.6.0.jar;` from the CLASSPATH the old Connectors started working again (but obviously the AzureKeyVault Connectors broke.

***Exception or Stack Trace***
There wasn't anything logged in the Catalina.log file showing any errors

**To Reproduce**
Create a Connector using the AzureKeyVault setup, and then another using a local JavaKeyStore and cert.  Once you start Tomcat only one of the Connectors is accepting traffic.

***Code Snippet***
Nothing to share.

**Expected behavior**
I would expect multiple Connectors created in the server.xml to work, regardless of where/how they get their SSL certificate information.

**Screenshots**
![image](https://user-images.githubusercontent.com/35438914/167200418-27db6b48-ac77-4d26-8c16-6bae19d3a98e.png)

**Setup (please complete the following information):**
 - OS:  __Windows Datacenter 2019__
 - IDE: 
 - Library/Libraries:  __azure-security-keyvault-jca-2.6.0.jar__
 - Java version:  __Java v11__
 - App Server/Environment:   __Tomcat9/10__
 - Frameworks: 

If you suspect a dependency version mismatch (e.g. you see `NoClassDefFoundError`, `NoSuchMethodError` or similar), please check out [Troubleshoot dependency version conflict article](https://aka.ms/azsdk/java/dependency/troubleshoot) first. If it doesn't provide solution for the problem, please provide:
- verbose dependency tree (`mvn dependency:tree -Dverbose`)
- exception message, full stack trace, and any available logs

**Additional context**

**Information Checklist**
Kindly make sure that you have added all the following information above and checkoff the required fields otherwise we will treat the issuer as an incomplete report
- [x] Bug Description Added
- [x] Repro Steps Added
- [x] Setup information Added

**Comment by joshfree** [comment]
Thanks for reaching out to us via this issue on GitHub, @ProphetManX.  The Azure Spring team who owns the jca will follow up with you shortly. 

Given your description above, it might help the Spring team if you include the verbose dependency tree (mvn dependency:tree -Dverbose)

**Comment by moarychan** [comment]
Hi @ProphetManX , please help to confirm if my test fits your scenario.

I refer to your other [issue comments](https://github.com/Azure/azure-sdk-for-java/issues/28560#issuecomment-1117994415), and I test passed your scenario on Tomcat 10.0.20, there are three `Connector`s in different Service nodes in the *server.xml*, they can work together fine.
- one is a non-SSL connection, request via http://localhost:8080
- one is SSL enabled connection using a local certificate, request via https://localhost:8443
- one is SSL enabled connection using a certificate loaded from Azure Key Vault service (using Service Principal authentication), request via https://localhost:8444

The configuration of server.xml is as follows:
```xml
<Service name="Catalina">
    <Connector port="8080" protocol="HTTP/1.1"
               connectionTimeout="20000"
               redirectPort="8443" />
    <Engine name="Catalina" defaultHost="localhost">
      <Realm className="org.apache.catalina.realm.LockOutRealm">
        <Realm className="org.apache.catalina.realm.UserDatabaseRealm"
               resourceName="UserDatabase"/>
      </Realm>

      <Host name="localhost"  appBase="webapps"
            unpackWARs="true" autoDeploy="true">
        <Valve className="org.apache.catalina.valves.AccessLogValve" directory="logs"
               prefix="localhost_access_log" suffix=".txt"
               pattern="%h %l %u %t &quot;%r&quot; %s %b" />

      </Host>
    </Engine>
  </Service>
  <Service name="CatalinaSelfSigned">
    <Connector port="8443" protocol="org.apache.coyote.http11.Http11NioProtocol"
               maxThreads="150" SSLEnabled="true">
        <UpgradeProtocol className="org.apache.coyote.http2.Http2Protocol" />
        <SSLHostConfig>
            <Certificate certificateKeystoreFile="C:\Users\Moary Chen\.keystore"
			 certificateKeystorePassword="changeit"
                         type="RSA" />
        </SSLHostConfig>
    </Connector>
    <Engine name="Catalina" defaultHost="localhost">
      <Realm className="org.apache.catalina.realm.LockOutRealm">
        <Realm className="org.apache.catalina.realm.UserDatabaseRealm"
               resourceName="UserDatabase"/>
      </Realm>

      <Host name="localhost"  appBase="webapps"
            unpackWARs="true" autoDeploy="true">
        <Valve className="org.apache.catalina.valves.AccessLogValve" directory="logs"
               prefix="localhost_access_log" suffix=".txt"
               pattern="%h %l %u %t &quot;%r&quot; %s %b" />
      </Host>
    </Engine>
  </Service>
  <Service name="CatalinaKeyVault">
    <Connector port="8444" protocol="org.apache.coyote.http11.Http11NioProtocol"
               maxThreads="150" SSLEnabled="true">
        <!--<UpgradeProtocol className="org.apache.coyote.http2.Http2Protocol" /> -->
        <SSLHostConfig>
			<Certificate 
			certificateKeyAlias="ExampleCertificate"
            certificateKeystoreFile=""
            certificateKeystorePassword=""
            certificateKeystoreType="DKS"
            certificateKeystoreProvider="AzureKeyVault" />
        </SSLHostConfig>
    </Connector>
    <Engine name="Catalina" defaultHost="localhost">
      <Realm className="org.apache.catalina.realm.LockOutRealm">
        <Realm className="org.apache.catalina.realm.UserDatabaseRealm"
               resourceName="UserDatabase"/>
      </Realm>

      <Host name="localhost"  appBase="webapps"
            unpackWARs="true" autoDeploy="true">
        <Valve className="org.apache.catalina.valves.AccessLogValve" directory="logs"
               prefix="localhost_access_log" suffix=".txt"
               pattern="%h %l %u %t &quot;%r&quot; %s %b" />
      </Host>
    </Engine>
  </Service>
```

**Comment by ProphetManX** [comment]
I apologize for the delayed response, looking at your server.xml file I'm now wondering if my problem was trying to have the different "Connector"s hosted within the same "Service".  In my testing we were using the default "Service" and creating multiple "Connector"s and it works fine, so long as you're only using one type of SSL/HTTPS.  

I will try to replicate what you've got here and let you know what I find.  Thanks for the support.

Cheers
