### ISSUE TITLE
[FEATURE REQ] Publish reference doc for Managed Identities OAuth support in Spring Cloud Azure Kafka

### ISSUE THREAD

**Issue by yiliuTo** [Azure/azure-sdk-for-java#28709]
### Context
parent issue: #28685, #28708 

With Managed Identities OAuth feature enabled in #28708 , the reference doc to introduce the function should also be published in our [Spring Cloud Azure Reference Doc](https://microsoft.github.io/spring-cloud-azure/current/reference/html/index.html).

### Goal
Add a section in the [Spring Cloud Azure Reference Doc](https://microsoft.github.io/spring-cloud-azure/current/reference/html/index.html) for [Credential Free](https://github.com/Azure/azure-sdk-for-java/wiki/Credential-free-connection-support-for-Spring-Cloud-Azure#3-thematic-documentation), and add a sub section for Kafka to introduce the feature of Managed Identities OAuth, content should contain
- Feature description
- Working principle
- Supported configuration
- Code/Configuration snippet example

**Comment by jialigit** [comment]
close in favor of #29217 for new design.
