### ISSUE TITLE
How to get MySql flexible Server get TLS_Version ?

### ISSUE THREAD

**Issue by ulugbekrozimboyev** [Azure/azure-sdk-for-java#28717]
Hi. 
I want to get access to MySql flexible server properties, especially I must to get `tls_version`.  I found [CLI command here](https://docs.microsoft.com/en-us/cli/azure/mysql/flexible-server/parameter?view=azure-cli-latest#az-mysql-flexible-server-parameter-show)  just add example code here also:

`az mysql flexible-server parameter show --resource-group testGroup --server-name testserver --name parameterName`

This is working very fine. But I need to use it inside my java code, I have tried SDK, It returns [Server](https://github.com/Azure/azure-sdk-for-java/blob/main/sdk/mysqlflexibleserver/azure-resourcemanager-mysqlflexibleserver/src/main/java/com/azure/resourcemanager/mysqlflexibleserver/models/Server.java) class which is this field does not exist inside this class. 

### Above will try to put my code.

**Use this dependency**

```
<dependency>
    <groupId>com.azure.resourcemanager</groupId>
    <artifactId>azure-resourcemanager-mysqlflexibleserver</artifactId>
    <version>1.0.0-beta.2</version>
</dependency>
```

Here is my code

```
HttpLogOptions httpLogOptions = new HttpLogOptions();
httpLogOptions.setLogLevel(HttpLogDetailLevel.BASIC);

AzureProfile profile = new AzureProfile(tenantId, subscriptionId, com.azure.core.management.AzureEnvironment.AZURE);

MySqlManager mySQLManager = MySqlManager.configure()
    .withLogOptions(httpLogOptions)
    .authenticate(credentials, profile);
    
PagedIterable<Server> servers = mySQLManager.servers().list();
```

As I know, as a result I get data as written [here](https://docs.microsoft.com/en-us/rest/api/mysql/flexibleserver/servers/list). JSON data was vary large, I didn't want to add here. 

Well, Is there other methods to get the fields which I want to or I did something wrong here ? Please, help me to manage this situation.

**Comment by joshfree** [comment]
Hi @ulugbekrozimboyev thank you for reaching out to us via this GitHub issue.  Someone from the `azure-resourcemanager` library team will follow up with your question shortly.

**Comment by weidongxu-microsoft** [comment]
@ulugbekrozimboyev 

You can use `--debug` to CLI to see the request/response.

Here is Java
```
            var paramValue = mySqlManager.configurations().get("rg-weidxu1", "mysql1weidxu", "tls_version");
```

**Comment by ulugbekrozimboyev** [comment]
@weidongxu-microsoft Thanks for help, this is worked. 
But two things is small stranger, one of them if I need several fields I must to send request several time.
Second one: If I will get servers by code `PagedIterable<Server> servers = mySQLManager.servers().list();` 
Than I need to get each server data . By this code 
`var paramValue = mySqlManager.configurations().get("TestGroup", "testserver", "tls_version");`

I need to put resource group which is private fields of ServerImpl class. Here I had to cut from ID field. 
IMHO, the last thing developers use very often and it need to improve.

**Comment by weidongxu-microsoft** [comment]
@ulugbekrozimboyev

There is also a `listByServer` API under `mySqlManager.configurations()`. You might try that and see if it get all parameters?

Yes, "resourceGroup" from ID appears not easy to use from the lib. We will see if we can expose it to `Server` in future releases. Thanks for the valuable suggestion.

**Comment by weidongxu-microsoft** [comment]
@DaeunYim 
Do you have answer of this question from customer, on mysql flexibleserver backend?

> If I will get servers by code `PagedIterable<Server> servers = mySQLManager.servers().list();`
Than I need to get each server data . By this code `var paramValue = mySqlManager.configurations().get("TestGroup", "testserver", "tls_version");`

Basically I take the question is: do we have API to get "tls_version" for all Servers in one API?

**Comment by weidongxu-microsoft** [comment]
@ulugbekrozimboyev

Ok, then the `listForServer` might work for your case?

**Comment by DaeunYim** [comment]
@weidongxu-microsoft Thanks a lot for taking care of this issue.
