### ISSUE TITLE
[FEATURE REQ] Demo how to secure Spring applications by managing secrets in Azure Key Vault

### ISSUE THREAD

**Issue by yiliuTo** [Azure/azure-sdk-for-java#28711]
### Context

A quick-start documentation introducing how to remove connection-string/access-key/password/client-secret credentials from applications and transfrom to Key Vault should be delivered to help developers for migration of credential-free connection with Azure services.

### Goal
Publish the quick-start documentation.

**Comment by yiliuTo** [comment]
The parent issue to track all Key Vault related credential-free migration quickstarts has not been established.

**Comment by stliu** [comment]
closing in favor of #28713
