### ISSUE TITLE
[FEATURE REQ] Publish Quick-start doc about migrating a Spring ecosystem Kafka application to Managed Identities from connection strings

### ISSUE THREAD

**Issue by yiliuTo** [Azure/azure-sdk-for-java#28710]
### Context
parent issue: #28685, #28708 

With Managed Identities OAuth feature enabled in #28708 , a quick-start documentation introducing how to remove connection-string credentials from applications and transfrom to Managed Identities should be published to help developers for migration.

### Goal
Publish a quick-start documentation after the feature being enabled.

**Comment by hui1110** [comment]
resolves in https://github.com/MicrosoftDocs/azure-dev-docs-pr/pull/3329
