### ISSUE TITLE
Unable to create Standard SSD disk.Disk Sku Type Standard SSD is missing in DIskSkuTypes.java

### ISSUE THREAD

**Issue by sumangit789** [Azure/azure-sdk-for-java#2871]
Unable to create Standard SSD disk.Disk Sku Type Standard SSD is missing in DIskSkuTypes.java

I am using Azure Java SDK .I am trying to create a Standard SSD Data Disk.

Azure azure;
Disk.DefinitionStages.WithCreate creatableDisk = azure.disks().define(diskName)
                    .withRegion(region)
                    .withExistingResourceGroup(resourcegrp)
                    .withData()
                    .withSizeInGB(size);
                creatableDisk.withSku(DiskSkuTypes.PREMIUM_LRS);
          
                creatableDisk.withSku(DiskSkuTypes.STANDARD_LRS);

If i use STANDARD_LRS ,it will create Standard HDD disk
If i use PREMIUM_LRS ,it will create preimium SSD disk

No constant is present for creating Standard SSD disk

Please guide me ..

**Comment by praries880** [comment]
@sumangit789 what is the SDK version you are using?

**Comment by yaohaizh** [comment]
New enum values had been added the fluent lib recently. @sumangit789 feel free to re-open this issue if the issue is still persisting.
