### ISSUE TITLE
Enable soft delete Storage Account capability 

### ISSUE THREAD

**Issue by DenisVoloshin** [Azure/azure-sdk-for-java#28719]
Hi.
I'm working on the provisioning and configuration Storage Account
One of the required configurations I need to set up is enabling soft delete capability.

For hours I was looking for any sample that demonstrated it.
The only class if found that apparently should be used is DeleteRetentionPolicy
As I mention, I have difficulty finding a sample code.

I guess the current model doesn't allow to set this configuration during Storage account creation; that intuitively should be there.

here is the code I create for my Storage Account gen 2

```java
 StorageAccount storageAccount = azureResourceManager.storageAccounts().define(storageAccountName)
                    .withRegion(Region.fromName(region))
                    .withNewResourceGroup(rgName)
                    .withHnsEnabled(true)
                    .withBlobStorageAccountKind().disableBlobPublicAccess()
                    .withBlobStorageAccountKind().withAccessTier(AccessTier.HOT)
                    .withOnlyHttpsTraffic()
                    .withSku(StorageAccountSkuType.STANDARD_RAGRS)
                    .withMinimumTlsVersion(MinimumTlsVersion.TLS1_2)
                    .withGeneralPurposeAccountKindV2()
                    .create();
```

Any doc references or code samples will be appreciated

Thanks

**Comment by joshfree** [comment]
Hi @DenisVoloshin, thanks for reaching out to us via this GitHub issue.  Someone from the `azure-resourcemanager` team will follow up with you on this question shortly.

**Comment by weidongxu-microsoft** [comment]
@DenisVoloshin 

Yes, it is DeleteRetentionPolicy.

Doc https://docs.microsoft.com/azure/storage/blobs/soft-delete-blob-overview (please do check the doc, it seems it won't help if either storage account or container got deleted, only for blob within container)

Code https://github.com/Azure/azure-sdk-for-java/blob/main/sdk/resourcemanager/azure-resourcemanager-storage/src/test/java/com/azure/resourcemanager/storage/StorageBlobServicesTests.java#L34-L48 (sorry, it is a test, not a sample, but it should demonstrate the same)
