### ISSUE TITLE
Sync reference  documentation for Spring Cloud Azure 4.1.0 of GitHub pages and Microsoft docs

### ISSUE THREAD

**Issue by hui1110** [Azure/azure-sdk-for-java#28723]
## Context

Now we have 2 places to hold `Spring Cloud Azure` Reference doc:

1. Spring Cloud Azure `MS docs`: https://docs.microsoft.com/en-us/azure/developer/java/spring-framework/
2. Spring Cloud Azure `github.io`: https://microsoft.github.io/spring-cloud-azure/current/reference/html/index.html

## Problem

Changes to reference documents will first synchronize `MS Docs`, we need to keep the content of the above two `reference documents` consistent.

## Goal 

After the release of 4.1.0, the content of the documentation in both [MS Docs](https://docs.microsoft.com/en-us/azure/developer/java/spring-framework/) and [gitHub.io](https://microsoft.github.io/spring-cloud-azure/current/reference/html/index.html) is consistent.

**Comment by saragluna** [comment]
https://github.com/MicrosoftDocs/azure-dev-docs-pr/pull/3035

**Comment by hui1110** [comment]
There is a new issue tracking this, close it now. https://github.com/Azure/azure-sdk-for-java/issues/29161
