### ISSUE TITLE
[BUG] BuilderHelper doesn't pass clientOptions to HttpPipelineBuilder in buildPipeline

### ISSUE THREAD

**Issue by doronl** [Azure/azure-sdk-for-java#28783]
**Describe the bug**
BuilderHelper doesn't pass clientOptions to HttpPipelineBuilder in buildPipeline, all settings are ignored

**To Reproduce**

***Code Snippet***
        HttpClientOptions httpClientOptions = new HttpClientOptions();

        httpClientOptions.setResponseTimeout(Duration.ofSeconds(120));
        httpClientOptions.setReadTimeout(Duration.ofSeconds(120));
        httpClientOptions.setWriteTimeout(Duration.ofSeconds(120));
        httpClientOptions.setConnectTimeout(Duration.ofSeconds(30));

        blobServiceAsyncClient = new BlobServiceClientBuilder().connectionString(connectionString).
                clientOptions(httpClientOptions).buildAsyncClient();

**Comment by rickle-msft** [comment]
@doronl Thanks for pointing this out. I can see that we aren't setting the options on the http client as you suggested. We'll work on putting out a fix for this.
