### ISSUE TITLE
[FEATURE REQ] Support buffering >2GB in BinaryData

### ISSUE THREAD

**Issue by kasobol-msft** [Azure/azure-sdk-for-java#28799]
From https://github.com/Azure/azure-sdk-for-java/pull/28737#discussion_r870647524 .

`BinaryData` would throw if `InputStream` or `Flux` contain data that's larger than single byte array can hold. Consider developing a datastructure that can hold such large payloads in memory.

Storage has developed something like this [here](https://github.com/Azure/azure-sdk-for-java/blob/3f31d68eed6fbe11516ca3afe3955c8840a6e974/sdk/storage/azure-storage-common/src/main/java/com/azure/storage/common/implementation/BufferAggregator.java) . 

Update from https://github.com/Azure/azure-sdk-for-java/pull/29463 :
- We should add `BinaryData.toReplayableData`/`BinaryData.toReplayableDataAsync` to produce buffered data from non-repeatable one.
- Be able to detect if source is replayable, i.e. `ByteArrayInputStream` or when Flux will carry indicator in the future.

**Comment by alzimmermsft** [comment]
There is also a case like what Storage does in Jackson where smaller string slices will be used until the complete string is needed and joined together at the end. This also removes the intermediate resizing which may be more costly.
