### ISSUE TITLE
[QUERY] ThroughputControl is failed using Cosmos DB Spark connector 

### ISSUE THREAD

**Issue by RengarLee** [Azure/azure-sdk-for-java#28812]
Query/Question
I want the limit to targetThroughput but if I  set spark.cosmos.throughputControl.enabled is true, there will be Failed that is java.lang.AssertionError: assertion failed.  

This the [doc](https://github.com/Azure/azure-sdk-for-java/blob/main/sdk/cosmos/azure-cosmos-spark_3_2-12/docs/configuration-reference.md) I refer to, but I can't find more details about what they do.

Setup:

Library/Libraries: com.azure.cosmos.spark:azure-cosmos-spark_3-1_2-12:4.6.
![Snipaste_2022-05-12_10-39-19](https://user-images.githubusercontent.com/23287334/167984842-ac2e68ac-ee2d-4066-a230-dec9f34ecfb1.png)
![Snipaste_2022-05-12_10-52-14](https://user-images.githubusercontent.com/23287334/167984858-58b89a70-511f-4106-947a-f81af38bcbf4.png)

**Comment by RengarLee** [comment]
If I write that way, he won't be  Failed, but it is ThroughputControl has no effect.

![image](https://user-images.githubusercontent.com/23287334/168462164-3aab77d1-7c39-4312-a59d-e51c56ed5383.png)
![Snipaste_2022-05-15_15-30-39](https://user-images.githubusercontent.com/23287334/168462186-5ac2bfc8-1700-4d3b-9695-3d59f31436c3.png)

**Comment by kushagraThapar** [comment]
@FabianMeiswinkel  / @xinlian12  - please take a look at this issue.

**Comment by xinlian12** [comment]
@RengarLee seems like you have missed some required configs related to throughput control, that is why you are getting the above error.  Please see an sample below. You can also access our full sample [here](https://github.com/Azure/azure-sdk-for-java/blob/main/sdk/cosmos/azure-cosmos-spark_3_2-12/Samples/Scala/NYC-Taxi-Data/01_Batch.scala): 

writeCfg = {
  "spark.cosmos.accountEndpoint": cosmosEndpoint,
  "spark.cosmos.accountKey": cosmosMasterKey,
  "spark.cosmos.database": "SampleDatabase",
  "spark.cosmos.container": "GreenTaxiRecords",
  "spark.cosmos.write.strategy": "ItemOverwrite",
  "spark.cosmos.write.bulk.enabled": "true",
  "spark.cosmos.throughputControl.enabled": "true",
  "spark.cosmos.throughputControl.name": "NYCGreenTaxiDataIngestion",
  "spark.cosmos.throughputControl.targetThroughputThreshold": "0.95",
  "spark.cosmos.throughputControl.globalControl.database": "SampleDatabase",
  "spark.cosmos.throughputControl.globalControl.container": "ThroughputControl",
}

**Comment by RengarLee** [comment]
I found the need to build this container in CosmosDb.
![image](https://user-images.githubusercontent.com/23287334/168968930-60df467c-96ec-4e26-9a55-9999d4694af9.png)

@xinlian12 Thank you for your answer!
