### ISSUE TITLE
[QUERY] A table with VOID data type was created in Databricks which makes it fail after select

### ISSUE THREAD

**Issue by joel-iemma-moneybox** [Azure/azure-sdk-for-java#28836]
After connecting to Cosmos using  [https://github.com/Azure/azure-sdk-for-java/tree/main/sdk/cosmos/azure-cosmos-spark_3_2-12/Samples/DatabricksLiveContainerMigration](this) tutorial and performing a simple CTAS, a new table is created but it contains a column with a void data type. This void data type makes the SELECT queries fail afterwards given that this void column is not found by Databricks.

Is this an error of this connector or something related directly to Databricks?

It was run on a Single Node with Runtime Version 10.4 LTS (includes Apache Spark 3.2.1, Scala 2.12).

**Comment by joel-iemma-moneybox** [comment]
![image](https://user-images.githubusercontent.com/82940249/168188185-9fb614df-4b52-4fa5-8c73-d5cd42dbb2ef.png)

**Comment by TheovanKraay** [comment]
Closing this issue due to age, and not related to Cosmos DB (question relates to Spark data type "null").
