### ISSUE TITLE
Configure data plane pipelines build to use maven parallel builds

### ISSUE THREAD

**Issue by JonathanGiles** [Azure/azure-sdk-for-java#2883]
Consider the details provided at https://cwiki.apache.org/confluence/display/MAVEN/Parallel+builds+in+Maven+3 to introduce parallel builds for the data plane pipeline. This will become more useful as more modules are introduced into the build.

**Comment by mitchdenny** [comment]
Closing this issue. Under the unified pipeline model the builds now build a much reduced set of builds, so build parallelism isn't as effective. If you think this is not the case let's reopen and discuss. Right now the track 2 libraries are taking about 90 seconds (core). I'd say a fair chunk of that is package/dependency downloads.
