### ISSUE TITLE
[FEATURE REQ] Provide an affordance for passing a custom `EventLoopGroup` to Cosmos clients

### ISSUE THREAD

**Issue by jchambers** [Azure/azure-sdk-for-java#28857]
In applications that already use Netty, it can be helpful to have multiple Netty-based systems sharing the same IO thread pool (`EventLoopGroup`). Most of the Azure SDK is based on HTTP clients and already allows callers to provide an existing `EventLoopGroup` at client construction time: https://github.com/Azure/azure-sdk-for-java/blob/8c88d34523e768330967d21904d60545c98da733/sdk/core/azure-core-http-netty/src/main/java/com/azure/core/http/netty/NettyAsyncHttpClientBuilder.java#L295-L315

…but the Cosmos SDK, which uses RNTBD instead of HTTP, does not.

It would be great to add an affordance to the Cosmos clients/builders to allow callers to provide their own `EventLoopGroup`.

Thanks!

**Comment by jchambers** [comment]
Also: I think it _is_ currently possible to limit the size of the Cosmos thread pool by setting the `reactor.schedulers.defaultPoolSize` system property, but that doesn't quite scratch the itch.

**Comment by kushagraThapar** [comment]
@xinlian12 do we ever plan to support this? If yes, please re-open this issue.
