### ISSUE TITLE
[FEATURE REQ] Add more logs about ServiceBusProcessorClient restarting

### ISSUE THREAD

**Issue by saragluna** [Azure/azure-sdk-for-java#28859]
**Is your feature request related to a problem? Please describe.**
When the `ServiceBusProcessorClient` starts, a scheduled task will monitor the `asyncClient`'s connectivity and try to restart the client when the connection is lost. But there's no log info about whether the client is being restarted or not. Should we add some log info about this behavior? If we have such information, we could infer whether the restart is working as expected from the log.   

**Describe the solution you'd like**
Add more logs about processor restarting. 

**Describe alternatives you've considered**
N/A

**Additional context**
We ran into issues when the processor client stopped consuming messages. We ended with restarting the application every one hour. It's hard to tell whether the daemon thread to restart the client is working. 

**Information Checklist**
Kindly make sure that you have added all the following information above and checkoff the required fields otherwise we will treat the issuer as an incomplete report
- [x] Description Added
- [x] Expected solution specified

**Comment by ki1729** [comment]
@saragluna: Today when the restart code is called - there should be a log line that prints "Removing receiver links." as part of the client close() call.  This is the only place where this message would come from. I agree, it is not obvious form the log that the client is undergoing a restart though. 
We are redo-ing the log verbosity as unique work track as part of the next cycle. We should reconsider this in that scope as well.

**Comment by ki1729** [comment]
Closing this issue out as we are tracking updates in #20836. Please feel free to reopen if necessary
