### ISSUE TITLE
Managed Identity: Configurable timeout based on time

### ISSUE THREAD

**Issue by ArLucaID** [Azure/azure-sdk-for-java#2893]
Currently, the retry logic in the Azure SDKs for Managed Identity token generation supports a configurable time out based on counts. For response time sensitive services this has not been enough. Per customer feedback, they would like to have timeout configuration based on time (i.e. milliseconds)
This will allow for quicker fail after certain.
Can we make the retry max configurable based on time?
@binderjoe FYI

**Comment by arluca** [comment]
@binderjoe : Any update on this one?

**Comment by arluca** [comment]
@Binderjoe / @praries880 : Any update on this one?

**Comment by joshfree** [comment]
@jianghaolu could you please follow up?

**Comment by jianghaolu** [comment]
The retry logic was the standard protocol at the time for managed identity endpoints. We were requested by managed identity to follow it. 
Let's investigate if it's still mandated - if not, we can drastically simplify it and allow customizations.

**Comment by alzimmermsft** [comment]
@g2vinay, @billwert looks like this was never re-assigned
