### ISSUE TITLE
[FEATURE REQ] Create KeyVaults

### ISSUE THREAD

**Issue by felipeek** [Azure/azure-sdk-for-java#28942]
**Is your feature request related to a problem? Please describe.**
We need to be able to create KeyVaults, however I didn't find any APIs to do so. The official documentation about the Keys-related API says that having a key vault is a pre-requisite. Is it possible to create key vaults using this library? Is there an Azure official java library that allows the creation of key vaults?

**Describe the solution you'd like**
I want to be able to create KeyVaults in my subscription.

**Describe alternatives you've considered**

**Additional context**

**Information Checklist**
Kindly make sure that you have added all the following information above and checkoff the required fields otherwise we will treat the issuer as an incomplete report
- [ ] Description Added
- [ ] Expected solution specified

**Comment by joshfree** [comment]
Hi @felipeek , thanks for reaching out to us via this GitHub Issue.

You can find all Azure SDK for Java libraries at https://aka.ms/azsdk.

To programmatically manage a keyvault you can use the azure-resourcemanager-keyvault library:

- https://docs.microsoft.com/en-us/java/api/overview/azure/resourcemanager-keyvault-readme?view=azure-java-stable
- https://github.com/Azure/azure-sdk-for-java/blob/azure-resourcemanager-keyvault_2.14.0/sdk/resourcemanager/docs/SAMPLE.md
- https://search.maven.org/artifact/com.azure.resourcemanager/azure-resourcemanager-keyvault/2.14.0/jar

**Comment by joshfree** [comment]
I'm closing this issue now that it I believe it is answered, but please feel free to reactivate the issue or to open a new issue as needed.  Thanks.

**Comment by felipeek** [comment]
Thank you @joshfree!
