### ISSUE TITLE
ComputerVision.recognizeTextAsync return type does not contain any ServiceResponseWithHeaders

### ISSUE THREAD

**Issue by Vinayaka-Hebbar** [Azure/azure-sdk-for-java#2895]
ComputerVision.recognizeTextAsync(String url, TextRecognitionMode mode) Method does not return any 
ServiceResponseWithHeaders.. unable to find 'Operation-Location'

**Comment by praries880** [comment]
@Vinayaka-Hebbar Can you kindly share the code snippet as well as the version of the SDK you are using?
