### ISSUE TITLE
[BUG] storage/common/policy/RequestRetryOptions incorrect javadoc for retryDelay, maxRetryDelay, 

### ISSUE THREAD

**Issue by welovelain** [Azure/azure-sdk-for-java#28962]
**Describe the bug**
https://github.com/Azure/azure-sdk-for-java/blob/e3cc975bb373e5cdb7fcece31df7bf4ff196cd3a/sdk/storage/azure-storage-common/src/main/java/com/azure/storage/common/policy/RequestRetryOptions.java

package: com.azure.storage.common.policy
class: RequestRetryOptions 

javadoc default values for parameters `retryDelay` and `maxRetryDelay` are specified in ms (4ms, 30ms, 120ms), but in code there are seconds: 4 seconds, 30 seconds, 120 seconds

```  * @param retryDelay Optional. Specifies the amount of delay to use before retrying an operation, default value
     * is {@code 4ms} when {@code retryPolicyType} is {@link RetryPolicyType#EXPONENTIAL EXPONENTIAL} and {@code 30ms}
     * when {@code retryPolicyType} is {@link RetryPolicyType#FIXED FIXED}.
     * @param maxRetryDelay Optional. Specifies the maximum delay allowed before retrying an operation, default
     * value is {@code 120ms}.
 ```

```java
switch (this.retryPolicyType) {
                case EXPONENTIAL:
                    this.retryDelay = Duration.ofSeconds(4);
                    break;
                case FIXED:
                    this.retryDelay = Duration.ofSeconds(30);
                    break;
                default:
                    throw LOGGER.logExceptionAsError(new IllegalArgumentException("Invalid 'RetryPolicyType'."));
            }
            this.maxRetryDelay = Duration.ofSeconds(120);
```

**Expected behavior**
I believe javadoc is wrong, not the default values themselves.

**Comment by joshfree** [comment]
Hi @welovelain thanks for reaching out to us via this GitHub issue.  Someone from the `storage` team will follow up shortly.  Thanks again.

**Comment by rickle-msft** [comment]
@welovelain Thank you for pointing this out. We'll get it cleaned up.
