### ISSUE TITLE
[QUESTION] spring boot sample for verifying a token

### ISSUE THREAD

**Issue by RaghavThakkar** [Azure/azure-sdk-for-java#28966]
**Query/Question**
Currently, I have created a server app in Azure Ad in which I have exposed the API and added scope. 
The scope looks like this.  I have also created one client in which I gave API permission(Delegate) and added scope. 
When I generate a token using grant_type ="client_credentials" the token generates successfully. However, I could not see the scope of the token. 

Could you please explain why this is happening? 

Could you please provide me sample in java spring boot that verify the token. 

[api://URI/API]

***Why is this not a Bug or a feature Request?***
A clear explanation of why is this not a bug or a feature request?

**Setup (please complete the following information if applicable):**
 - IDE: [e.g. IntelliJ]
 - Library/Libraries: [e.g. com.azure:azure-core:1.16.0 (groupId:artifactId:version)]
 
 **Information Checklist**
 Kindly make sure that you have added all the following information above and checkoff the required fields otherwise we will treat the issuer as an incomplete report
- [ ] Query Added
- [ ] Setup information Added

**Comment by joshfree** [comment]
Hi @RaghavThakkar someone from the `azure-spring` team will follow up with you shortly.

**Comment by chenrujun** [comment]
Hi @RaghavThakkar 

Thanks for reaching out.

## Confirm your requirement
Here is my current understanding of your requirement:
![image](https://user-images.githubusercontent.com/13167207/169467902-630fad35-d25d-4746-97c5-a1ca995d769e.png)

`ResourceServer` will verity the `access_token`.

## Useful links

1. Here is a sample that you can refer to build your `ResourceServer`: [aad-resource-server](https://github.com/Azure-Samples/azure-spring-boot-samples/tree/spring-cloud-azure_v4.1.0/aad/spring-cloud-azure-starter-active-directory/web-client-access-resource-server/aad-resource-server)
2. You can use https://jwt.ms/ to check the `access_token`.
