### ISSUE TITLE
[FEATURE REQ] retrieveRegistrationTokenAsync for DesktopsVirtualization

### ISSUE THREAD

**Issue by iteal** [Azure/azure-sdk-for-java#29015]
There is a public method  retrieveRegistrationToken  but  retrieveRegistrationTokenAsync is private in com.azure.resourcemanager.desktopvirtualization.HostPool

Can we make this method public?

Also, does this retrieve registration token method also renew the token if expired? If not, what is the method to call?

Thanks!

**Comment by joshfree** [comment]
Hi @iteal thank you for reaching out to us via this GitHub issue.  Someone from the `resourcemanager` team will follow up with you shortly.

/cc @weidongxu-microsoft

**Comment by weidongxu-microsoft** [comment]
@iteal

The design decision at the time is not to expose Reactor async to customer, because it could be hard to understand.
Would you share your use case for the async?

@datr93 Would you answer customer's question on
> Also, does this retrieve registration token method also renew the token if expired? If not, what is the method to call?

I think it is [this API](https://github.com/Azure/azure-rest-api-specs/blob/main/specification/desktopvirtualization/resource-manager/Microsoft.DesktopVirtualization/stable/2021-07-12/desktopvirtualization.json#L1572)

**Comment by iteal** [comment]
Thank you, I am not sure why it is hard to understand. I am using the async version of AzureResourceManager deployment of a resource group so that's why I was looking for the async version here too. It is true it is maybe a shorter operation.

For the renewal of the token, do you have a way to do it in Java? I think it is a patch of the resource with a new expiration time. So it may not be part of this  desktopvirtualization package.

**Comment by weidongxu-microsoft** [comment]
@JonathanGiles We got customer request on async methods in Fluent Lite libs. I will schedule a plan to support (with flag to only enable it for the few requested libs).

**Comment by weidongxu-microsoft** [comment]
@iteal

I am not sure about

> For the renewal of the token, do you have a way to do it in Java? I think it is a patch of the resource with a new expiration time. So it may not be part of this desktopvirtualization package.

If it is not part of desktopvirtualization package, our client package cannot help you (by definition, the client lib only calls known APIs).

If you want to call some REST API, you can use your favorite HTTP client in Java.

Alternatively, if you want to call ARM API, and are concerned about authentication, you can use the `HttpPipeline` to send the request (it handles authentication to ARM).
`manager.serviceClient().getHttpPipeline().send(...)`

**Comment by weidongxu-microsoft** [comment]
@iteal 
We are doing a preview in PR https://github.com/Azure/azure-sdk-for-java/pull/29582

The async API should now be accessed via `manager.serviceClient().getHostPools()...`.

Let us know your opinion.

**Comment by weidongxu-microsoft** [comment]
beta.2 releasing to Maven.
