### ISSUE TITLE
[FEATURE REQ] Azure Active Directory authorization for "Put Block from URL"

### ISSUE THREAD

**Issue by malthe** [Azure/azure-sdk-for-java#29083]
Since API version 2020-10-02, the "x-ms-copy-source-authorization: <scheme> <signature>" header value has been available to authorize the source blob for the [Put Block from URL ](https://docs.microsoft.com/en-us/rest/api/storageservices/put-block-from-url)operation.

In the Java SDK this operation is provided as the `stageBlockFromURL` method.

This is a feature request to expose this authorization option.

See also #27294.

**Comment by joshfree** [comment]
Hi @malthe thank you for filing this GitHub issue.  Someone from the `storage` team will follow up shortly.

**Comment by ibrahimrabab** [comment]
Hi @malthe , apologies for not responding to this request earlier. For stageBlockFromUrl method, we take in BlockBlobStageBlockFromUrlOptions which contains a field settable for copy source authorization. 
Please see here:
[https://github.com/Azure/azure-sdk-for-java/blob/main/sdk/storage/azure-storage-blob/src/main/java/com/azure/storage/blob/options/BlockBlobStageBlockFromUrlOptions.java#L126](https://github.com/Azure/azure-sdk-for-java/blob/main/sdk/storage/azure-storage-blob/src/main/java/com/azure/storage/blob/options/BlockBlobStageBlockFromUrlOptions.java#L126)

Let us know if you have any other questions.

**Comment by malthe** [comment]
@ibrahimrabab works like a charm – thanks!
