### ISSUE TITLE
[BUG] Cannot clone Java repo - file name too long

### ISSUE THREAD

**Issue by seanmcc-msft** [Azure/azure-sdk-for-java#29098]
I keep my repos in C:\Users\seanmcc\git, so when I open a command prompt, I don't have to navigate up the file tree to C:\.  Open command prompt, `cd git` is much faster for me to type than `cd ..\..\..\`.

When I attempt to clone the Java SDK:

C:\Users\seanmcc\git>git clone https://github.com/Azure/azure-sdk-for-java.git
Cloning into 'azure-sdk-for-java'...
remote: Enumerating objects: 1138616, done.
remote: Counting objects: 100% (292/292), done.
remote: Compressing objects: 100% (194/194), done.
remote: Total 1138616 (delta 122), reused 194 (delta 43), pack-reused 1138324
Receiving objects: 100% (1138616/1138616), 2.49 GiB | 22.91 MiB/s, done.
Resolving deltas: 100% (784233/784233), done.
error: unable to create file sdk/containerregistry/azure-containers-containerregistry/src/main/java/com/azure/containers/containerregistry/implementation/models/Paths108HwamOauth2ExchangePostRequestbodyContentApplicationXWwwFormUrlencodedSchema.java: Filename too long
Updating files: 100% (61717/61717), done.
fatal: unable to checkout working tree
warning: Clone succeeded, but checkout failed.
You can inspect what was checked out with 'git status'
and retry with 'git restore --source=HEAD :/'

In the .NET repo, we have a rule in place that prevents file names from becoming this long.  Can we implement something similar in Java?  I'm sure there are other users effected by this.

**Comment by joshfree** [comment]
@ki1729 could you please follow up?

**Comment by ki1729** [comment]
I can definitely look into applying something similar to .NET in Java. But it most likely might not be possible to apply it on exisiting files,unless they go through a major version bump. My hypothesis would be, given that the Unix default is 4096, and windows is 260, that might be source for this issue being addressed in .NET and not in Java.

@seanmcc-msft : The current workaround we have in place today for Windows OS is to do the following two things
1. Update windows registry to allow long path
`REG ADD HKLM\SYSTEM\CurrentControlSet\Control\FileSystem /f /v LongPathsEnabled /t REG_DWORD /d 1`
2. Configure git to accept long path
`git.exe config --system core.longpaths true`

**Comment by seanmcc-msft** [comment]
@ki1729, thank you for the work around, it has mitigated this issue for me.
