### ISSUE TITLE
[QUESTION] Is there a way to create a storage account with blob versioning enabled?

### ISSUE THREAD

**Issue by felipeek** [Azure/azure-sdk-for-java#29105]
**Query/Question**
The resourcemanager API allows the creation of storage accounts, but is it possible to enable versioning for the accounts? I didn't find such API nor any example doing that.

***Why is this not a Bug or a feature Request?***
If the feature does not exist, this would be a feature request. But I want to confirm first.

**Setup (please complete the following information if applicable):**
 - Library/Libraries: azure-resourcemanager 2.14.0

**Comment by rickle-msft** [comment]
@felipeek Thank you for your question.

@weidongxu-microsoft Can you please comment on this?

**Comment by weidongxu-microsoft** [comment]
@felipeek 

Would you explain "enable versioning for the accounts"? Would you share and doc e.g. on Portal or CLI or MSDocs on the feature?

**Comment by felipeek** [comment]
Hello @weidongxu-microsoft 

In the portal, you can enable versioning by selecting the storage account, clicking on "Data Protection" and then checking the box "Enable versioning for blobs".

The feature is called blob versioning: https://docs.microsoft.com/en-us/azure/storage/blobs/versioning-overview

**Comment by weidongxu-microsoft** [comment]
@XiaofeiCao 

Please check and add the feature to convenient code (search for `DeleteRetentionPolicy`, we had that).

@felipeek 

Meanwhile you can use this REST API
https://github.com/Azure/azure-sdk-for-java/blob/main/sdk/resourcemanager/azure-resourcemanager/src/samples/java/com/azure/resourcemanager/storage/generated/BlobServicesSetServicePropertiesSamples.java#L91-L105

**Comment by XiaofeiCao** [comment]
@weidongxu-microsoft I see, it's this property right?
https://github.com/Azure/azure-sdk-for-java/blob/main/sdk/resourcemanager/azure-resourcemanager/src/samples/java/com/azure/resourcemanager/storage/generated/BlobServicesSetServicePropertiesSamples.java#L103

**Comment by weidongxu-microsoft** [comment]
yes
