### ISSUE TITLE
[FEATURE REQ] sample on DescriptionSet and encrypted VM on compute

### ISSUE THREAD

**Issue by weidongxu-microsoft** [Azure/azure-sdk-for-java#29112]
not urgent

azure-resourcemanager-samples module

---

Wondering whether we can have a spring cloud enterprise sample as well, but do not want sample to download jar from weidongxu-microsoft repo (and equally not want to push a hugh jar here).
If you have good idea, do let me know (hope spring cloud have the jar somewhere in their repo?).

**Comment by XiaofeiCao** [comment]
Seems like github got a link for downloading tar.gz file of the projects:
https://github.com/${GIT_USER}/${GIT_PROJECTS}/archive/${BRANCH}.tar.gz

For petclinic from my fork, it will be: https://github.com/XiaofeiCao/spring-petclinic-microservices/archive/azure.tar.gz

Perhaps we can download the tar.gz file and making deployment samples this way?

(There's a small tweak with the downloaded file though. Original tar.gz contains a root directory, which is not allowed by Service. We can untar the file and retar it locally in the sample code)

**Comment by weidongxu-microsoft** [comment]
Is it possible to find similar one on their repo?

Would like to avoid having `XiaofeiCao` showing up in sample on MSDoc (our test is fine, but prefer not in user-facing code).

**Comment by XiaofeiCao** [comment]
@weidongxu-microsoft Seems they got an official release in 2020:
https://github.com/spring-petclinic/spring-petclinic-microservices/releases

I'll try with that. Would be great if that one works..
