### ISSUE TITLE
[QUERY] When using azure-spring-data-cosmos SimpleCosmosRepository: How to save without upsert?

### ISSUE THREAD

**Issue by gauner1986** [Azure/azure-sdk-for-java#29129]
**Query/Question**
When using azure-spring-data-cosmos SimpleCosmosRepository: 
How do i use the save method without performing an upsert?
Is there anything i can do besides calling findById beforehand to check if the item is already present?
It seems to me that unique key constraints are also ignored, i.e. no exception is thrown.

<code>
@Container(containerName = "mycontainer")
@Data
@Builder
@AllArgsConstructor
@NoArgsConstructor
public class MyEntity {

    @Id
    @PartitionKey
    @GeneratedValue
    private String id;
}
</code>

***Why is this not a Bug or a feature Request?***
Unsure if it's a bug, or me just using it wrong. I would expect an exception on saving the same id.

**Setup (please complete the following information if applicable):**
 - OS: Linux
 - IDE: IntelliJ
 - Library/Libraries: azure-spring-data-cosmos:3.21.0
 
 **Information Checklist**
 Kindly make sure that you have added all the following information above and checkoff the required fields otherwise we will treat the issuer as an incomplete report
- [x] Query Added
- [x] Setup information Added

**Comment by kushagraThapar** [comment]
Also, using the annotation `@GeneratedValue` will auto generate the ID as a random ID every single time, and may be that's why you are not seeing the unique key constraints being validated.

**Comment by kushagraThapar** [comment]
Please feel free to re-open if the issue persists.
