### ISSUE TITLE
[FEATURE REQ] Support maxDegreeOfParallelism in spring-cloud-azure-starter-data-cosmos

### ISSUE THREAD

**Issue by saragluna** [Azure/azure-sdk-for-java#29123]
**Is your feature request related to a problem? Please describe.**
`maxDegreeOfParallelism` has been added to `spring-data-cosmos` in https://github.com/Azure/azure-sdk-for-java/issues/28579, the `spring-cloud-azure-starter-data-cosmos` should also support it. 

**Describe the solution you'd like**
Support the `maxDegreeOfParallelism` in Spring Data Cosmos Autoconfiguration.

**Comment by trande4884** [comment]
This was added under this PR: https://github.com/Azure/azure-sdk-for-java/pull/28756
