### ISSUE TITLE
[QUERY] Azure Schema registry + Spark Structured Streaming + Kafka/EventHub compatibility

### ISSUE THREAD

**Issue by scaladevspark** [Azure/azure-sdk-for-java#29134]
Is there a way to use AZURE Schema Registry with Spark Structured Streaming? (not the opensource schema registry).

Ideally I would use some high level library like Abris (https://github.com/AbsaOSS/ABRiS), to read and write avro from/to Kafka with automatically registering/ reading the df schema in the schema registry. However, I have not managed to find anything at all that could enable spark to do to_avro or from_avro against an Azure Schema Registry.

There is an open PR that could add the functionality for some column types https://github.com/Azure/azure-event-hubs-spark/pull/615

There seems to be an unmainained repo that at least tried to do the from_avro part (https://github.com/arerlend/azure-schemaregistry-spark)

Anybody knows about a good way how to interact with Azure Schema Registry with Spark Structured Streaming?

**Comment by joshfree** [comment]
@conniey could you please follow up with @scaladevspark?

**Comment by conniey** [comment]
Unfortunately, I have no insights into Spark Structured Streaming.  Pinging @hmlam who may have some insights.
