### ISSUE TITLE
SyncStack - Storage file downloads

### ISSUE THREAD

**Issue by kasobol-msft** [Azure/azure-sdk-for-java#29147]
Make file download performant.

- avoid StreamResponse and HttpResponse buffering
- develop utils/helpers that can be used to track progress and retry starting from failure position.

**Comment by g2vinay** [comment]
@kasobol-msft 
Can you provide some more detailed context for this issue ?
Was any part of it resolved via this PR ? https://github.com/Azure/azure-sdk-for-java/pull/29965
If not, what changes from high level need to be done to complete this ?
