### ISSUE TITLE
follow Use dynamic configuration using push refresh in a Java Spring app to make a demo , but  configuration didnt refresh

### ISSUE THREAD

**Issue by Ryan9017** [Azure/azure-sdk-for-java#29162]
**Query/Question**
i want to create a demo. Use dynamic configuration using push refresh in a Java Spring app.
https://docs.microsoft.com/en-us/azure/azure-app-configuration/use-key-vault-references-spring-boot
push model with Springboot, i have recieved event with actuator endpoint , but the configuration is not refresh

i have recieved event with actuator endpoint , but when app recieve the event ,it didn't call RefreshEventListener handler() method ,so the configuration is not refresh,

Library/Libraries: azure-spring-cloud-appconfiguration-config-web : 2.6.0

Can you help me see what the reason, thanks.

**Comment by mrm9084** [comment]
Hi, do you mean this doc? https://docs.microsoft.com/en-us/azure/azure-app-configuration/enable-dynamic-configuration-java-spring-push-refresh.

I know that doc has a current issue where this `management.endpoints.web.exposure.include= appconfiguration-refresh` has double quotes, but shouldn't. It should be updated soon.

Also, the push request doesn't cause a refresh, it just expires the current refresh interval, so the next refresh check will cause a refresh.

Hope this helps.

**Comment by Ryan9017** [comment]
Thanks a lot Matt, the answer is very helpful. And i found an another problem when i debug my demo app which is used push model. 
app recieved the message through the actuator/appconfiguration-refresh endpoint , and the com.azure.spring.cloud.config.web.AppConfigurationEndpoint processed the data include endpoint ,as shown in the figure below, endpoint = String.format("https://%s.", store);   it was a format conversion.
![image](https://user-images.githubusercontent.com/27200019/172091794-a77f6500-0009-4ba1-bc00-707161e62152.png)
and then com.azure.spring.cloud.config.AppConfigurationRefresh has listened the AppConfigurationRefreshEvent which published by the appconfiguration-refresh endpoint , triggerd the method  expireRefreshInterval(String endpoint, String syncToken),as shown in the figure below
![image](https://user-images.githubusercontent.com/27200019/172092257-029474a1-99e9-4a04-b8f6-1581819ed91c.png)
The two endpoint will never seem to be equal either, and the current refresh interval cant be expired and the refresh function  didnt work.
Here is what i find , when debug my demo app , I wonder if my analysis is correct.
Please forgive me for my poor English writing, thanks.
