### ISSUE TITLE
Optimize response headers from StoreResponse

### ISSUE THREAD

**Issue by kushagraThapar** [Azure/azure-sdk-for-java#29206]
There have been some improvements in .Net SDK regarding response headers. 

https://msdata.visualstudio.com/CosmosDB/_git/CosmosDB/pullrequest/791781

https://msdata.visualstudio.com/CosmosDB/_git/CosmosDB/pullrequest/444179

We should port these ideas to Java V4 SDK.

**Comment by TheovanKraay** [comment]
@kushagraThapar closing this issue as the linked PR closes it.
