### ISSUE TITLE
[FEATURE REQ] Enable Azure Identity for Spring Cloud Azure MySQL support

### ISSUE THREAD

**Issue by yiliuTo** [Azure/azure-sdk-for-java#29219]
### Context
Parent issue: #29218
Currently MySQL developers can connect to Azure Database for MySQL with data abase password. We aim to provide all Azure Identity based credentital types and the associated configuration options to Azure Database for MySQL deverlopers.

### Solutions
- [ ] Design all user-aware configuration options for Azure Identity of Spring Cloud Azure MySQL feature.
- [ ] Implement the feature.

**Comment by yiliuTo** [comment]
When implementing the MySQL plugin for credential-free connection for Spring JDBC, we should investigate whether to use `BeanPostProcessor` or `EnvironmentPostProcessor` to customize the Spring database properties

**Comment by backwind1233** [comment]
Closing this, the feature has been implemented,
refer to 
- [azure-identity-providers-core](https://github.com/Azure/azure-sdk-for-java/tree/dfbaf41a07edd0b69bedb5f1f858b069e6a221cf/sdk/jdbc/azure-identity-providers-core)
- [azure-identity-providers-jdbc-mysql](https://github.com/Azure/azure-sdk-for-java/tree/dfbaf41a07edd0b69bedb5f1f858b069e6a221cf/sdk/jdbc/azure-identity-providers-jdbc-mysql)
- [spring-cloud-azure-starter-jdbc-mysql](https://github.com/Azure/azure-sdk-for-java/tree/dfbaf41a07edd0b69bedb5f1f858b069e6a221cf/sdk/spring/spring-cloud-azure-starter-jdbc-mysql)
