### ISSUE TITLE
[Epic] Support Azure Identity for MySQL

### ISSUE THREAD

**Issue by yiliuTo** [Azure/azure-sdk-for-java#29218]
This is the epic to track all issues about Azure Identity support for MySQL.

### Context
Currently MySQL developers can use Azure Database for MySQL in the same way as how they use MySQL. For the authentication part, native MySQL developers can use database password to authenticate to MySQL server.

We plan to support all Azure Identity based credentials for Spring Cloud Azure MySQL support, which includes all Azure Identity supported credential types and configuration options.

With Azure Identity-based credentials being supported, we can also achieve credential-free connection as well, which based on the `ManagedIdentityCredential` in Azure Identity. It can enable developers to use user-assigned/system-assigend managed identities in various Azure hosting environments to establish connection with Azure Database for MySQLs via various spring ecosystems for MySQL.

### Deliveries
The delivery resources include:
#### Docs

- [x] #29221
- [x] #29224
- [x] #29225
#### Others
- [x] #29219
- [x] #29222
- [x] #29775
- [x] #29228
- [x] #29776
- [x] #29777

**Comment by saragluna** [comment]
The first beta release, 4.5.0-beta.1, has been out, closing this issue now.
