### ISSUE TITLE
[FEATURE REQ] Move credential-free-jdbc plguin to azure-sdk-for-java repo and set up pipeline

### ISSUE THREAD

**Issue by saragluna** [Azure/azure-sdk-for-java#29228]
**Is your feature request related to a problem? Please describe.**
The credential free jdbc plugin is now in a feature branch, we should move it to the main branch and set up a pipeline for it. And we should delete the original repo.

**Describe the solution you'd like**
Move the code to main branch and set up pipeline

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Information Checklist**
Kindly make sure that you have added all the following information above and checkoff the required fields otherwise we will treat the issuer as an incomplete report
- [x] Description Added
- [x] Expected solution specified

**Comment by saragluna** [comment]
After discussion with the arch board: 

- **Service directories** will be `sdk/[jdbc|kafka|redis|mongo|cassandra]`
- **Group ids** will be `com.azure`
- **Artifact names** will be `azure-identity-providers-[jdbc|kafka|redis|mongo|cassandra]`
- **Java packages** will be `com.azure.identity.providers.[jdbc|kafka|redis|mongo|cassandra]`
- **Java classnames** will be `AzureIdentity[Mysql|Postgresql|Kafka|Redis|Mongo|Cassandra]AuthenticationPlugin`
- Use separate artifacts for MySQL and PostgreSQL:
  + azure-identity-providers-jdbc-mysql
  + azure-identity-providers-jdbc-postgresql
  > [Yesterday 05:17] Jonathan Giles
I don't think we want to include version numbers in the class name. We should establish rules to ensure the widest degree of compatibility - ideally we would unit test against a range of versions of the existing library, and update that range of versions as new releases come out. We can then document with confidence our known support range.

**Comment by backwind1233** [comment]
closing this, redirect to  https://github.com/Azure/azure-sdk-for-java/issues/30349
