### ISSUE TITLE
[FEATURE REQ] Publish reference doc for Azure Identity support in Spring Cloud Azure MySQL

### ISSUE THREAD

**Issue by yiliuTo** [Azure/azure-sdk-for-java#29221]
### Context
parent issue: #29218, #29219

With Azure Identity feature enabled in #29219, the reference doc to introduce the function should also be published in our [Spring Cloud Azure Reference Doc](https://microsoft.github.io/spring-cloud-azure/current/reference/html/index.html).

### Goal
Add a section in the [Spring Cloud Azure Reference Doc](https://microsoft.github.io/spring-cloud-azure/current/reference/html/index.html) to introduce the feature of all supported Azure Identity credentials and configuration, content should contain
- Feature description
- Working principle
- Supported configuration
- Code/Configuration snippet example
- Change `credential-free` to `passwordless`

**Comment by saragluna** [comment]
Closed in https://github.com/MicrosoftDocs/azure-dev-docs-pr/pull/3463.
