### ISSUE TITLE
[FEATURE REQ] Update quick-start doc of Spring Data JDBC with MySQL to include credential-free connection

### ISSUE THREAD

**Issue by yiliuTo** [Azure/azure-sdk-for-java#29225]
### Context

With Managed Identities OAuth feature enabled in #29219, we should update our quickstart doc of [Spring quickstart MySQL JDBC] to include the credential-free connection method. 

There's a template worked out by Alex can be found here:
- https://github.com/MicrosoftDocs/azure-docs-pr/pull/203348#issuecomment-1205727432
- https://github.com/MicrosoftDocs/azure-docs-pr/pull/203348#issuecomment-1203381358

We should demo two connection methods in this doc, one using credential-free connections and one using username/password, using contextual tabs to distinguish them. We should make the credential-free tab as the default/recommended.

### Goal
Update the quick-start doc to include the credential-free part. 

[Spring quickstart MySQL JDBC]: https://docs.microsoft.com/en-us/azure/developer/java/spring-framework/configure-spring-data-jdbc-with-azure-mysql

**Comment by saragluna** [comment]
Closed in #3419.
