### ISSUE TITLE
[FEATURE REQ] Validate and collect the usage data of Kafka passwordless support

### ISSUE THREAD

**Issue by yiliuTo** [Azure/azure-sdk-for-java#29229]
## Context
The passwordless connection support of Event Hubs for Kafka has been GAed from version 4.3.0. For the support, we have set our user agent for kafka as `az-sp-kafka`. Now we need to collect the telemetry data of our library of [com.azure.spring:spring-cloud-azure-starter](https://search.maven.org/artifact/com.azure.spring/spring-cloud-azure-starter) according to the user agent.

On Event Hubs service side, they claim to release the support of Kafka telemetry tracking after mid September. Then after the feature goes to production, we should be able to collect our telemetry from Event Hubs telemetry data.

## Goal
- Validate that the telemetry data of our Kafka passwordless support can be collected in Event Hubs Service BI database.
- Collect our telemetry data of Kafka passwordless support library of both 4.3.0 and 4.4.0.

## Solution
Connect to Event Hubs service team to 
1. make sure that the support of kafka telemetry has been released
2. apply for the access of reading their telemetry database and collect our Kafka passwordless data.

**Comment by yiliuTo** [comment]
After syncing with Azure Event Hubs service team, we use Kafka'a ApiVersionsRequest interface to set our user agent.

Besides, the support for collecting Kafka protocols telemetry on Event Hubs service side will be deployed at the end of July. We need to test at that time.

**Comment by yiliuTo** [comment]
Validated with Event Hubs service team and can confirm that the telemetry can be collected, with the data as the following format:
```
SubscriptionId: 799c12ba-353c-44a1-883d-84808ebb2216, NamespaceType: Microsoft.EventHub, Namespace: eh-kafka-useragent, Product: apache-kafka-java/az-sp-kafka, Version: 4.3.0, Platform: Unknown, Framework: KAFKA, UserAgent: Unknown, ResourceGroup: Default-EventHub-EASTUS2EUAP
```

**Comment by yiliuTo** [comment]
Reopen to validate this again when Kafka telemetry collection has been deployed in Event Hubs service side.

**Comment by backwind1233** [comment]
@yiliuTo I am not sure if I could rename credential-free to passwordless.

**Comment by yiliuTo** [comment]
> @yiliuTo I am not sure if I could rename credential-free to passwordless.

yes, we can align kafka with jdbc

**Comment by yiliuTo** [comment]
Move this back to backlog since this feature hasn't been supported by Event Hubs service side.

**Comment by yiliuTo** [comment]
The telemetry of passwordless connection support for Kafka can be collected from Event hubs' Geneva database.
The details about the database and query information are recorded in [wiki](https://dev.azure.com/azure-spring-integration/spring-integration-private/_wiki/wikis/spring-integration-private.wiki/322/Collect-usage-data-for-MySQL-PostgreSQL-and-Kafka-passwordless).
Currently the deployment of collecting Kafka ApiVersion is not completed, we collected 6 records of Kafka passwordless usage with comparison to 400~500 records all Java Kafka usage.
