### ISSUE TITLE
[FEATURE SPIKE] Preparing for supporting Spring Boot 3.0

### ISSUE THREAD

**Issue by saragluna** [Azure/azure-sdk-for-java#29230]
**Is your feature request related to a problem? Please describe.**
Spring Boot 3.0 is going to release in Nov 2022, https://spring.io/blog/2022/05/24/preparing-for-spring-boot-3-0, we should prepare for it.

**Describe the solution you'd like**
Spike the upgrade preparation on how to support Spring Boot 3.0 in `azure-sdk-for-java` repo, which will cover the below parts:

1. Can Azure SDK support two Spring Boot major versions simultaneously?

2. Where is the code to support Spring Boot 3.0 placed?

3. How to process the different dependencies of Spring Boot 2.x and 3.x?

4. Shall we distinguish the version or the artifact id when releasing?

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Information Checklist**
Kindly make sure that you have added all the following information above and checkoff the required fields otherwise we will treat the issuer as an incomplete report
- [x] Description Added
- [x] Expected solution specified

**Comment by moarychan** [comment]
Part 1:
I use three Azure SDK(Azure Storage Queue, Azure Event Hubs, Azure Cosmos) libraries to integrate with the Spring boot 3 application, They represent the main implementations of several different protocols in the Azure SDK, only issues with Cosmos have been found so far.
- https://github.com/Azure/azure-sdk-for-java/issues/29979

**Comment by moarychan** [comment]
Update:
1. Source code for Spring Boot 3.0 will be placed under a new service directory `spring-3` .
2. Use different major versions to distinguish the different supports for multi Spring Boot versions, such as, 5.x for Spring Boot 3 support, 4.x for Spring Boot 2.x support.

Here's a test PR [[Verify Spring Cloud Azure supports Spring Boot 3](https://github.com/Azure/azure-sdk-for-java/pull/30067)] to verify this feature spike, which is not perfect, but solves most major problems.

List of things that need improvement：
1.  The eng system should support a new way to identify the same artifact id in a different service directory.
2.  Dev IDE(Idea) does not allow managing the same artifact id in different modules, so we use different profiles to activate the `spring` or `spring-3`, it'll bring some extra effort.
3.  `spring-cloud-azure-dependencies` needs to be manually modified to support different version features.

**Comment by moarychan** [comment]
Close this, and will track the milestone support progress on the new issue https://github.com/Azure/azure-sdk-for-java/issues/30356
