### ISSUE TITLE
ApiErrorException thrown for invalid $skiptoken when listing large (>=250 instances) Virtual Machine Scaleset VMs

### ISSUE THREAD

**Issue by dclusin-cisco** [Azure/azure-sdk-for-java#29248]
When processing the responses for `VirtualMachineScaleSetVMs#listAsync` an exception is thrown resulting in the inability to list all of the `VirtualMachineScaleSetVM` instances:

```
{
  "error": {
    "code": "InvalidParameter",
    "message": "The request URL is not valid.",
    "target": "$skiptoken"
  }
}
```

Steps to reproduce:
1. Create a VMSS scaleset with 250 vmss instances
2. Use the VirtualMachineScaleSetVMs#listAsync for the created scaleset to enumerate the instances for that scaleset
Expected result:
The enumerated list of vms should be processed normally
Actual result:
Stream processing terminates abnormally with an onException invocation with an `com.azure.resourcemanager.compute.models.ApiErrorException` instance being supplied with the above error message.

Offending request ID's:
`x-ms-request-id:65b159f3-bec5-4b30-8caa-27dc3f120c9e`
`x-ms-correlation-request-id:ffc34c0e-390a-4415-a3e7-5978467218e1`

This behavior has been observed as far back as Azure Resource Manager version 2.8.0.

**Comment by joshfree** [comment]
@weidongxu-microsoft could you follow up with @dclusin-cisco on this github issue?

**Comment by weidongxu-microsoft** [comment]
Similar to https://github.com/Azure/azure-sdk-for-java/issues/27991
However, my request to increase quota over 100 in my subscription is still pending, so SDK cannot reproduce right now.

Looks like a service bug, as SDK just send the nextLink URL directly get from previous response.

**Comment by weidongxu-microsoft** [comment]
@dclusin-cisco

Could you let us know your current SDK version?

**Comment by weidongxu-microsoft** [comment]
Response of first page:

```
  "nextLink" : "https://management.azure.com:443/subscriptions/ec0aa5f7-9e78-40c9-85cd-535c6305b380/resourceGroups/rg-weidxu-vmss/providers/Microsoft.Compute/virtualMachineScaleSets/vmss1/virtualMachines?api-version=2021-11-01&$skiptoken=Mzk4YzFjMzMtM2IwMC00OWViLWI2NGYtNjg4ZTRmZGQ1Nzc2IS9TdWJzY3JpcHRpb25zL2VjMGFhNWY3LTllNzgtNDBjOS04NWNkLTUzNWM2MzA1YjM4MC9SZXNvdXJjZUdyb3Vwcy9SRy1XRUlEWFUtVk1TUy9WTVNjYWxlU2V0cy9WTVNTMS9WTXMvNzc="
```

Note that the last `=` should be URL encoded as `%3D`.
https://www.rfc-editor.org/rfc/rfc2396#section-2.2

**Comment by weidongxu-microsoft** [comment]
azure-core https://github.com/Azure/azure-sdk-for-java/blob/main/sdk/core/azure-core/src/main/java/com/azure/core/http/rest/RestProxy.java#L124

input to `createHttpRequest` has argument:
```
https://management.azure.com:443/subscriptions/ec0aa5f7-9e78-40c9-85cd-535c6305b380/resourceGroups/rg-weidxu-vmss/providers/Microsoft.Compute/virtualMachineScaleSets/vmss1/virtualMachines?api-version=2022-03-01&$skiptoken=ZDU4NWM2MDktNWRhNi00Yzk0LTgyZWYtYmRkZjIxZmI0NGNkIS9TdWJzY3JpcHRpb25zL2VjMGFhNWY3LTllNzgtNDBjOS04NWNkLTUzNWM2MzA1YjM4MC9SZXNvdXJjZUdyb3Vwcy9SRy1XRUlEWFUtVk1TUy9WTVNjYWxlU2V0cy9WTVNTMS9WTXMvNzc=
```

output Request.url is:
```
https://management.azure.com:443/subscriptions/ec0aa5f7-9e78-40c9-85cd-535c6305b380/resourceGroups/rg-weidxu-vmss/providers/Microsoft.Compute/virtualMachineScaleSets/vmss1/virtualMachines?api-version=2022-03-01&$skiptoken=ZDU4NWM2MDktNWRhNi00Yzk0LTgyZWYtYmRkZjIxZmI0NGNkIS9TdWJzY3JpcHRpb25zL2VjMGFhNWY3LTllNzgtNDBjOS04NWNkLTUzNWM2MzA1YjM4MC9SZXNvdXJjZUdyb3Vwcy9SRy1XRUlEWFUtVk1TUy9WTVNjYWxlU2V0cy9WTVNTMS9WTXMvNzc
```

If I add the "=" in `Request.url`, REST call actually works.

**Comment by weidongxu-microsoft** [comment]
/cc @alzimmermsft 

Could we have someone from core to take a look?

**Comment by weidongxu-microsoft** [comment]
@alzimmermsft 

Personally I do not use Fiddler.

Here is a UT in core
https://github.com/Azure/azure-sdk-for-java/pull/29425/files

**Comment by alzimmermsft** [comment]
After looking into this more this problem runs a bit deeper. The example given is that `nextLink` is the path parameter with query parameters appended, one being `skipToken` which is a Base64 encoded value. The method is configured to not apply encoding, and this makes sense as it's a full URL which will contain reserved characters (which is valid since it's the URL), but this breaks down as `skipToken` has Base64 padding `=`s which are a reserved character in query parameters. And I'll back track on my mention earlier about checking for trailing `=`s as I think it'd be better to have `skipToken` properly escaped as we shouldn't expected another query parameter parsing implementation to accept non-escaped Base64 content in a query parameter. Fixing this with escaping becomes more important too since Base64 padding can be `==` in addition to the example of `=` and this further compounds the ambiguity issue.

**Comment by weidongxu-microsoft** [comment]
I've done a bit of research https://github.com/Azure/azure-sdk-for-java/issues/29248#issuecomment-1151885687 and I could not find clear spec say that `=` is not allowed in query parameter.

Sure we can loop in service on the proper escaping, if this is indeed required.

**Comment by dclusin-cisco** [comment]
Hi,

Any ETA or estimate when this will land? This bug effects some of our released software.

**Comment by weidongxu-microsoft** [comment]
@mssfang Any update? Let me know if we plan to make it in core, or if we need to get CRP on discussion whether they need to do something in backend.

**Comment by weidongxu-microsoft** [comment]
azure-core 1.31.0 has fixed it.

azure-resourcemanager-compute will release 2.18.0 this week, which has azure-core 1.31.0 in dependency.
