### ISSUE TITLE
Getting null pointers when dropping and recreating same-name container with the Spark connector

### ISSUE THREAD

**Issue by xinlian12** [Azure/azure-sdk-for-java#29269]
When delete and recreating the same name-container, the spark job will fail with nullPointerException:
![image](https://user-images.githubusercontent.com/64233642/172417773-e8332321-b7a0-401b-b417-afd08cc3376a.png)

**Comment by kushagraThapar** [comment]
@xinlian12 is this still valid? If so, please re-open it.
