### ISSUE TITLE
Set soft delete retention policy for Storage account containers 

### ISSUE THREAD

**Issue by DenisVoloshin** [Azure/azure-sdk-for-java#29265]
**Query/Question**

I have a difficulty finding a sample to set up a soft delete retention policy for  Storage account containers 

The only code I found is for blobs, it works. here is how it works for me for blobs

1. First I create a Storage account (Gen 2)

```
StorageAccount storageAccount = this.azureResourceManager.storageAccounts().define(storageAccountName).
                withRegion(Region.fromName(region)).
                withNewResourceGroup(resourceGroupName).
                withHnsEnabled(true).
                withBlobStorageAccountKind().
                disableBlobPublicAccess().
                withBlobStorageAccountKind().
                withAccessTier(AccessTier.HOT).
                withOnlyHttpsTraffic().
                withSku(StorageAccountSkuType.STANDARD_RAGRS).
                withMinimumTlsVersion(MinimumTlsVersion.TLS1_2).
                withGeneralPurposeAccountKindV2().create();
```

then define the retention policy to blobs and apply it

 ```
DeleteRetentionPolicy deleteRetentionPolicy = new DeleteRetentionPolicy();
        deleteRetentionPolicy.withEnabled(true);
        deleteRetentionPolicy.withDays(30);


        this.azureResourceManager.storageBlobServices().
                define(storageAccountName).
                withExistingStorageAccount(resourceGroupName,storageAccountName).
                withDeleteRetentionPolicy(deleteRetentionPolicy).create();

```

I was expecting to have the same client for storage account containers, however, it's not clear, I tried to find this in all samples 
but without success.
I'm wondering how do you expose this API, and if you can provide me with a sample code, it will be extremely helpful.

the  CLI code is based on the same object to specify retention for both (blob and containers)

```python
  policy = {
        "properties": {
            "deleteRetentionPolicy": {
                "enabled": True,
                "days": 30,
                "allowPermanentDelete": True
            },
            "containerDeleteRetentionPolicy": {
                "enabled": True,
                "days": 30,
                "allowPermanentDelete": True
            },
            "isVersioningEnabled": False
        }
    }

    set_policy = storage_client.blob_services.set_service_properties(resource_group_name, account, policy)
```

I have to have this code in JAVA.

Thanks

**Setup (please complete the following information if applicable):**
 - OS: MAC M1
 - IDE: [IntelliJ]
 - Library/Libraries: [e.g. com.azure:azure-core:1.26.0 com.azure:azure-storage-blob:12.16.0]

**Comment by joshfree** [comment]
@weidongxu-microsoft could you follow up with @DenisVoloshin on this issue?

/cc @rickle-msft @kasobol-msft

**Comment by weidongxu-microsoft** [comment]
@XiaofeiCao , please support container retention configure as well.

link https://github.com/Azure/azure-sdk-for-java/issues/29105

Without new SDK, one should be able to do this
https://github.com/Azure/azure-sdk-for-java/blob/main/sdk/resourcemanager/azure-resourcemanager/src/samples/java/com/azure/resourcemanager/storage/generated/BlobServicesSetServicePropertiesSamples.java#L91-L105

**Comment by XiaofeiCao** [comment]
@DenisVoloshin Currently we don't have the exact example for this property but you can do similar thing as the example above shows.

I'll add support for it in convenience layer. It'll be like:
```java
this.azureResourceManager.storageBlobServices().
    define(storageAccountName).
    withExistingStorageAccount(resourceGroupName,storageAccountName).
    withContainerDeleteRetentionPolicy(deleteRetentionPolicy).create();
```

**Comment by DenisVoloshin** [comment]
Hi @[XiaofeiCao](https://github.com/XiaofeiCao) thanks for looking at my question and handling it.
as for the workaround you mentioned in

> Without a new SDK, one should be able to do this
> https://github.com/Azure/azure-sdk-for-java/blob/main/sdk/resourcemanager/azure-resourcemanager/src/samples/java/com/azure/resourcemanager/storage/generated/BlobServicesSetServicePropertiesSamples.java#L91-L105 

The code covers only the Blob soft deletion policy. it doesn't allow to set it for containers
Probably I'm missing something in the code but I tried it out, and the result is the same only blob policy is affected.
is there an alternative sample to this? if not, what do you think is the estimation for getting it in the official SDK?
thanks

**Comment by weidongxu-microsoft** [comment]
@DenisVoloshin 

The sample is a rough idea on how to call the API.

The exact setter is https://github.com/Azure/azure-sdk-for-java/blob/main/sdk/resourcemanager/azure-resourcemanager-storage/src/main/java/com/azure/resourcemanager/storage/fluent/models/BlobServicePropertiesInner.java#L244 in `BlobServicePropertiesInner`.

**Comment by DenisVoloshin** [comment]
@weidongxu-microsoft Thanks a lot

my bad, I missed that it's BlobServicePropertiesInner,  because BlobServiceProperties doesn't have withContainerDeleteRetentionPolicy

Now it works perfectly

```
this.azureResourceManager
                .storageAccounts()
                .manager()
                .serviceClient()
                .getBlobServices()
                .setServicePropertiesWithResponse(
                        resourceGroupName,
                        storageAccountName,
                        new BlobServicePropertiesInner()
                                .withContainerDeleteRetentionPolicy(
                                        new DeleteRetentionPolicy().withEnabled(true).withDays(30))
                                .withIsVersioningEnabled(false),
                        Context.NONE);
```
