### ISSUE TITLE
SyncStack - Implement progress tracking that lives close to wire.

### ISSUE THREAD

**Issue by kasobol-msft** [Azure/azure-sdk-for-java#29284]
Storage has progress tracking functionality that uses Flux.doOnNext to track the number of bytes that have passed through. Two changes are needed
- Push tracking down to the HTTP client layer so it tracks data sent over the wire, not passed through the SDK layer
- Support more than just Flux streams, though # 1 should solve this implicitly

**Comment by alzimmermsft** [comment]
That has been completed for Reactor Netty but still needs to be looked into for OkHttp, Vertx, and JDK HttpClient.
