### ISSUE TITLE
Report on dependencies used in all libraries

### ISSUE THREAD

**Issue by bsiegel** [Azure/azure-sdk-for-java#2930]
In order to ship a consistent set of libraries that work well together, we need to be able to understand what dependencies our libraries have and what versions of those dependencies are declared.

- [ ] Report list of dependencies used in all source code libraries
- [ ] Allow analyzing a directory of JARs or local Maven repo rather than a source directory
- [ ] Report on inconsistencies between versions of dependencies used by different libraries
- [ ] Report on instances where a library uses a dependency or version not declared in the parent POM
- [ ] Hook up analysis on CI builds (source) and release pipeline (JAR/mvn)

**Comment by JonathanGiles** [comment]
Let's sync up - my dependencies tool has been brought back to life :-)
