### ISSUE TITLE
Missing H1 for communication-sms-readme

### ISSUE THREAD

**Issue by v-alje** [Azure/azure-sdk-for-java#29344]
The communication-sms-readme landing page article on https://github.com/Azure/azure-docs-sdk-java/blob/main/docs-ref-services/preview/communication-sms-readme.md has an H2 instead of an H1 for the title header. The Readme at sdk/communication/azure-communication-sms/README.md looks like it is updated. 

Does the readme need to be re-imported?

**Comment by sima-zhu** [comment]
It will be fixed for next release. Since the release is not predictable, I have a quick change in docs repo. So we will be good from now on.
