### ISSUE TITLE
Add unit test coverage reporting for client SDK

### ISSUE THREAD

**Issue by JonathanGiles** [Azure/azure-sdk-for-java#2934]
Use Jacoco to generate HTML reports on unit test code coverage. Here's a few useful links:

- https://github.com/jacoco/jacoco/wiki/MavenMultiModule

- https://www.eclemma.org/jacoco/trunk/doc/report-aggregate-mojo.html

- https://github.com/onelogin/java-saml/issues/74

- http://tdongsi.github.io/blog/2017/09/23/jacoco-in-maven-project/

**Comment by srnagar** [comment]
Done - https://github.com/Azure/azure-sdk-for-java/pull/3916
