### ISSUE TITLE
Duplicate H1 Headers for storage

### ISSUE THREAD

**Issue by v-alje** [Azure/azure-sdk-for-java#29350]
The following three articles on Docs, usually imported from Readme files, have the same H1 title header. This causes Docs Build to throw warnings for the three topics sharing the same conflicting H1 title header.

https://github.com/Azure/azure-docs-sdk-java/blob/main/docs-ref-services/preview/storage.md  
https://github.com/Azure/azure-docs-sdk-java/blob/main/docs-ref-services/preview/storage_legacy.md  
https://github.com/Azure/azure-docs-sdk-java/blob/main/docs-ref-services/preview/storage_preview.md  

I don't see the readme these came from. The closest I can find is sdk/storage/README.md.

The H1 title headers need to be changed on Docs to eliminate the conflict.

**Comment by sima-zhu** [comment]
Differentiate three in docs repo. Will do clean up in future.
