### ISSUE TITLE
[FEATURE REQ] Support relative path in PollingStrategy classes

### ISSUE THREAD

**Issue by weidongxu-microsoft** [Azure/azure-sdk-for-java#29375]
**Is your feature request related to a problem? Please describe.**

Some header in LRO is in relative path. E.g.
```
        "Location": "/deviceUpdate/sdkinstance/updates/operations/84a98e36-d613-4591-9ae4-29a3a8a3266e?api-version=2022-07-01-preview",
        "Operation-Location": "/deviceUpdate/sdkinstance/updates/operations/84a98e36-d613-4591-9ae4-29a3a8a3266e?api-version=2022-07-01-preview",
```

**Describe the solution you'd like**

`DefaultPollingStrategy` and a few other class will need to take an optional parameter in ctor of `endpoint`.

In runtime, if it see that the URL is relative, it will concat the `endpoint` with the URL for the polling (and for GET on final result?).

Note that `endpoint` will only available if client has `EndpointTrait`. So we will still have runtime error if client does not support `EndpointTrait` and URL is relative.

/cc @srnagar 

**Describe alternatives you've considered**

**Additional context**

**Information Checklist**
Kindly make sure that you have added all the following information above and checkoff the required fields otherwise we will treat the issuer as an incomplete report
- [x] Description Added
- [x] Expected solution specified

**Comment by alzimmermsft** [comment]
Fixed in #29676
