### ISSUE TITLE
[QUERY] Latest azure-security-keyvault-keys 4.4.3 release contain dependencies which cause javadoc errors

### ISSUE THREAD

**Issue by lilgreenbird** [Azure/azure-sdk-for-java#29427]
**Query/Question**
I am unsure if this is a bug or if there is a workaround? We've upgraded to the latest azure-security-keyvault-keys 4.4.3 release as previous release contains vulnerabilities to netty-common and netty-code-http. However this latest release contains errors when generating javadoc:

```[ERROR] Failed to execute goal org.apache.maven.plugins:maven-javadoc-plugin:3.3.1:jar (attach-javadocs) on project mssql-jdbc: MavenReportException: Error while generating Javadoc: 
[ERROR] Exit code: 1 - error: cannot determine module name for C:\Users\it-admin\.m2\repository\io\netty\netty-tcnative-boringssl-static\2.0.51.Final\netty-tcnative-boringssl-static-2.0.51.Final-linux-aarch_64.jar
[ERROR] error: cannot determine module name for C:\Users\it-admin\.m2\repository\io\netty\netty-tcnative-boringssl-static\2.0.51.Final\netty-tcnative-boringssl-static-2.0.51.Final.jar
[ERROR] error: cannot determine module name for C:\Users\it-admin\.m2\repository\io\netty\netty-tcnative-boringssl-static\2.0.51.Final\netty-tcnative-boringssl-static-2.0.51.Final-windows-x86_64.jar
[ERROR] error: cannot determine module name for C:\Users\it-admin\.m2\repository\io\netty\netty-tcnative-boringssl-static\2.0.51.Final\netty-tcnative-boringssl-static-2.0.51.Final-linux-x86_64.jar
[ERROR] error: cannot determine module name for C:\Users\it-admin\.m2\repository\io\netty\netty-tcnative-boringssl-static\2.0.51.Final\netty-tcnative-boringssl-static-2.0.51.Final-osx-aarch_64.jar
[ERROR] error: cannot determine module name for C:\Users\it-admin\.m2\repository\io\netty\netty-tcnative-boringssl-static\2.0.51.Final\netty-tcnative-boringssl-static-2.0.51.Final-osx-x86_64.jar
[ERROR] 6 errors
```

We are using the maven-javadoc-plugin version 3.2.0 I've tried upgrading to the same version used here (3.3.1) and also the latest. All result in the same errors.

Upon inspecting these jars it looks like they have invalid module names.
e.g.
```
$ jar --describe-module --file netty-tcnative-boringssl-static-2.0.51.Final-windows-x86_64.jar
Unable to derive module descriptor for: netty-tcnative-boringssl-static-2.0.51.Final-windows-x86_64.jar
Automatic-Module-Name: io.netty.tcnative.openssl.windows-x86_64: Invalid module name: 'windows-x86_64' is not a Java identifier
```

***Why is this not a Bug or a feature Request?***
A clear explanation of why is this not a bug or a feature request?

**Setup (please complete the following information if applicable):**
 - IDE: [e.g. IntelliJ]
 - Library/Libraries: [e.g. com.azure:azure-core:1.16.0 (groupId:artifactId:version)]
 
 **Information Checklist**
 Kindly make sure that you have added all the following information above and checkoff the required fields otherwise we will treat the issuer as an incomplete report
- [ ] Query Added
- [ ] Setup information Added

**Comment by alzimmermsft** [comment]
Thanks for reporting this @lilgreenbird. Unfortunately, this is an external issue where the tcnative libraries from Netty was using [invalid automatic module names](https://github.com/netty/netty-tcnative/pull/725), once we upgrade versions this should be resolved. It may be possible to manually add the updated dependencies to resolve this issue in the meantime.

**Comment by lilgreenbird** [comment]
That is the issue, there's a later netty version 2.0.53.Final which fixes this issue. I've confirmed that is working. Please upgrade your dependency to the latest [netty-tcnative-boringssl-static 2.0.5.3Final](https://mvnrepository.com/artifact/io.netty/netty-tcnative-boringssl-static/2.0.53.Final) . We have been waiting for a new version of azure-security-keyvault-keys since component governance scans have flagged this as a vulnerability but currently with this we can not move to the 4.4.3 release.

**Comment by alzimmermsft** [comment]
Hi @lilgreenbird, we've released an updated to `azure-core-http-netty` which is using the up-to-date version of Netty TCNative. Once the KeyVault library releases a new version with this dependency this issue will be resolved.

**Comment by vcolin7** [comment]
We should be releasing an update for Key Vault tomorrow. I will let you know once it's done @lilgreenbird.

**Comment by vcolin7** [comment]
Hi @lilgreenbird, we have released [a new version](https://search.maven.org/artifact/com.azure/azure-security-keyvault-keys/4.4.4/jar) for `azure-security-keyvault-keys` that includes the `azure-core-http-netty` dependency @alzimmermsft talked about :)
