### ISSUE TITLE
Reduce verbosity of Cosmos INFO logging

### ISSUE THREAD

**Issue by hshukla** [Azure/azure-sdk-for-java#29528]
**Is your feature request related to a problem? Please describe.**
We have noticed RxDocumentClientImpl logging too many logs for "Getting database account endpoint from..." 

**Describe the solution you'd like**
Can this downgrade to lower level? Or if it is needed at INFO level, is there a way we can reduce the frequency or occurrence?

**Describe alternatives you've considered**
The only other alternative we can do is increase the log level on our side for this class to be on WARN level, however, that will hide other important INFO level logs which may be needed for future debugging.

**Additional context**
```
2022/06/16 13:53:09.075 INFO [RxDocumentClientImpl] [cosmos-parallel-6] [<svc_name>] [] Getting database account endpoint from https://<accountName>.documents.azure.com:443/
2022/06/16 13:53:09.116 INFO [RxDocumentClientImpl] [cosmos-parallel-7] [<svc_name>] [] Getting database account endpoint from https://<accountName>.documents.azure.com:443/
2022/06/16 13:53:09.444 INFO [RxDocumentClientImpl] [cosmos-parallel-8] [<svc_name>] [] Getting database account endpoint from https://<accountName>.documents.azure.com:443/
```

**Information Checklist**
Kindly make sure that you have added all the following information above and checkoff the required fields otherwise we will treat the issuer as an incomplete report
- [x] Description Added
- [x] Expected solution specified

**Comment by TheovanKraay** [comment]
@hshukla this information is logged once when a new CosmosClient/CosmosAsyncClient is created. The sample logs you have shared imply that you are running a multi-threaded app where each thread is creating a fresh client. We recommend you implement CosmosClient/CosmosAsyncClientas as a singleton, and share the instance across your threads. Not only will this reduce the frequency or occurrence of this message, it will also help you reduce memory related problems, and improve performance on the client-side. Is there some reason your threads cannot share CosmosClient/CosmosAsyncClient? Even if there are some threads which require the client to be re-created with different options, it is still better to share clients where possible.

**Comment by TheovanKraay** [comment]
@hshukla are you happy that we close this issue?
