### ISSUE TITLE
[Bug] EventHubClientBuilder connectionString(String connectionString) throws NPE

### ISSUE THREAD

**Issue by saragluna** [Azure/azure-sdk-for-java#29536]
**Describe the bug**
When calling `connectionString(String connectionString)` method on `EventHubClientBuilder`, it will throw NPE if an event hub name can't be resolved from the connection string. Seems like a `TokenCredential` is constructed from the connection string, and the event hub name is not used in this process. And users can call `eventHubName()` method even after calling `connectionString()` method, is there a need to throw NPE in the `connectionString(String connectionString)` method? How about deferring the exception to the `build()` call?

What if users want to construct an `EventHubClientBuilder` from the namespace level using a namespace connection string or credential, and using that builder to create several clients using that builder with the same credential?

***Exception or Stack Trace***
```console
 Caused by: java.lang.NullPointerException: 'eventHubName' cannot be null.
 	at java.base/java.util.Objects.requireNonNull(Objects.java:246)
 	at com.azure.messaging.eventhubs.EventHubClientBuilder.connectionString(EventHubClientBuilder.java:285)
```

**To Reproduce**
```java
EventHubClientBuilder builder = new EventHubClientBuilder();
builder.connectionString("the-connection-string-to-the-namespace");
```

***Code Snippet***
```java
EventHubClientBuilder builder = new EventHubClientBuilder();
builder.connectionString("the-connection-string-to-the-namespace");
```

**Expected behavior**
No exception is thrown in when calling the `connectionString(String connectionString)` method. 

**Setup (please complete the following information):**
 - OS: [MacOS]
 - IDE: [IntelliJ]
 - Library/Libraries: [azure-messaging-eventhubs: 5.12.1]
 - Java version: [11] 
 - App Server/Environment: [nothing special]
 - Frameworks: [Spring Boot] 

**Additional context**
The error log is not accurate, there's no such `credentials(String connectionString) overload`. 
https://github.com/Azure/azure-sdk-for-java/blob/c0848338068dec3b00aca63c12c4f656ec1be0d0/sdk/eventhubs/azure-messaging-eventhubs/src/main/java/com/azure/messaging/eventhubs/EventHubClientBuilder.java#L297-L304

**Information Checklist**
Kindly make sure that you have added all the following information above and checkoff the required fields otherwise we will treat the issuer as an incomplete report
- [x] Bug Description Added
- [x] Repro Steps Added
- [x] Setup information Added

**Comment by joshfree** [comment]
@Azure/azsdk-sb-java please take a look

**Comment by ZejiaJiang** [comment]
I've looked through the related code and get some thing.

For these method usage, `connectionString(String connectionString)` is working for the connection string we get from specific eventhub. If user want to use same builder with same credential to create client with different eventhub name, user can use `connectionString(String connectionString, String eventHubName)` , this is more flexible to support user if user want to use diffrerent namespace and different eventhub name with same builder.

@saragluna suggest to defer the exception to the `build()` call make sense to me. I've checked the git history and found that these related code are quite old, not sure are there some trade-offs or history here as we already support a single method `eventHubName(String eventHubName)`. Do you have any idea about this? @conniey @anuchandy @ki1729 

// cc @joshfree

**Comment by conniey** [comment]
I believe this is an oversight when we added support for the "credentials" such as SasTokenCredential, etc. We exposed the eventHubName and fullyQualifiedNamespace methods. When originally designing this, we did not have these methods. I am fine deferring the check.
