### ISSUE TITLE
[QUERY]Azure Event Hub Lag in Ingesting the data via Databricks

### ISSUE THREAD

**Issue by BhawnaBedi** [Azure/azure-sdk-for-java#29554]
We are facing a challenge in our workload, could you please check and suggest here.

Currently, we are ingesting data from AS400 source system for around 900 tables using Qlik Replicate task into Azure Event Hub. This data is being loaded from azure event hub into Data-lake gen2 via Databricks.

From Event hub to Databricks layer, we see lag(up to 6 days) in the data that is sent from event hub to data bricks.

Latest SDK we are using azure-eventhubs-spark_2.12.2.3.22

Below is the code snippet which loads the data from event hub to data lake for reference
![eventhubsnip](https://user-images.githubusercontent.com/107830730/174530267-19030ca9-3bec-4278-8767-40659434a01e.PNG)
.

**Comment by joshfree** [comment]
Hi @BhawnaBedi thank you for reaching out to us via this github issue.  @JamesBirdsall could you please follow up?

/cc @conniey
