### ISSUE TITLE
[BUG]. Infinite Receiver/Subscriber Issue | Java 11 | Spring Boot 2.5.*

### ISSUE THREAD

**Issue by srikarasr** [Azure/azure-sdk-for-java#29579]
**subject:** Infinite Receiver/Subscriber Issue | Java 11 | Spring Boot 2.5.*

**Attempt 1 :**
**Actual :**
The receiver/subscriber is getting disposed/closed off after some duration, like : 24hours
We kept it in the start mode with an expectation that it would never be disposed.
Please refer the following code :

```java
ServiceBusProcessorClient serviceBusProcessorClient =
    sbConfiguration.getReceiverProcessorClient(topicName, subscriptionName, onMessage, onError);
serviceBusProcessorClient.start();
```
Expectation : The receiver/subscriber should remain alive for the entire application's lifecycle for the obvious reason as we want to keep listening to the queue for any upcoming messages.

**Attempt 2 :**
Since it was getting disposed, we tried putting a while loop to keep opening the connections once they are closed, with a delay of 5-10minutes. Please find the following code for reference :

```java
       public void startSessionReceiving(
            String queueName,
            Consumer<ServiceBusReceivedMessageContext> onMessage,
            Consumer<ServiceBusErrorContext> onError) throws InterruptedException {

        ServiceBusProcessorClient sessionProcessor =
                sbConfiguration.getSessionProcessorClient(queueName, onMessage, onError);

        ExecutorService executorService = Executors.newSingleThreadExecutor();
        executorService.submit(() -> {
            log.info("Executor thread calling to start listener");
            sessionProcessor.start();
            while(true){
                log.info("Checking the status of service bus connection");
                if(!sessionProcessor.isRunning()){
                    log.info("Another processor client started since previous connection is closed");
                    sessionProcessor.start();
                }
                try {
                    TimeUnit.MINUTES.sleep(new RandomDataGenerator().nextLong(5, 10));
                } catch (InterruptedException ex) {
                    log.error("Exception occurred in sleep thread for service bus.", ex);
                }
            }
        });
    }
```

The issue with this code is : we still have a delay of some minutes before checking the connection status, which could further be reduced but the problem is do we actually need to do all this or we are missing something big here? Ideally the consumers are meant to always listen (infinitely) for any new messages !!

It would really helpful if someone could recommend the better way/approach of achieving the infinite (application's scope) listener without managing the lifecycle of it ourselves. Also have a control to abandon a message when any application level exception occurs

**Comment by srikarasr** [comment]
```
public ServiceBusProcessorClient getSessionProcessorClient(String topicName, String subscriptionName, Consumer<ServiceBusReceivedMessageContext> onMessage, Consumer<ServiceBusErrorContext> onError) {
        String connectionString = sbProperties.getConnectionString();
        return new ServiceBusClientBuilder()
                .connectionString(connectionString)
                .sessionProcessor()
                .disableAutoComplete()
                .receiveMode(ServiceBusReceiveMode.PEEK_LOCK)
                .topicName(topicName)
                .subscriptionName(subscriptionName)
                .maxConcurrentSessions(5)
                .processMessage(onMessage)
                .processError(onError)
                .buildProcessorClient();
    }
```

**Comment by srikarasr** [comment]
SDK Version
```
                <dependency>
			<groupId>com.azure</groupId>
			<artifactId>azure-core</artifactId>
			<version>1.16.0</version>
		</dependency>
		<dependency>
			<groupId>com.azure</groupId>
			<artifactId>azure-messaging-servicebus</artifactId>
			<version>7.2.1</version>
		</dependency>
```

**Comment by joshfree** [comment]
Hi @srikarasr thanks for posting this GitHub issue.  Someone from the spring team will follow up with you shortly.

/cc @Azure/azsdk-sb-java too as fyi

**Comment by yiliuTo** [comment]
Hi @srikarasr , by using spring boot for Servcie Bus JAVA SDK, you could use our library of [com.azure.spring:spring-cloud-azure-starter-servicebus](https://mvnrepository.com/artifact/com.azure.spring/spring-cloud-azure-starter-servicebus/4.2.0) for the autoconfiguration of Service Bus processor/receiver client, here are the configuration properties for it https://microsoft.github.io/spring-cloud-azure/current/reference/html/appendix.html#_azure_service_bus_properties.

**Comment by yiliuTo** [comment]
Hi @srnagar , for the auto reconnecting issue of service bus processor/receiver clients, could you help to take a look?

**Comment by srikarasr** [comment]
> Hi @srikarasr , by using spring boot for Servcie Bus JAVA SDK, you could use our library of [com.azure.spring:spring-cloud-azure-starter-servicebus](https://mvnrepository.com/artifact/com.azure.spring/spring-cloud-azure-starter-servicebus/4.2.0) for the autoconfiguration of Service Bus processor/receiver client, here are the configuration properties for it https://microsoft.github.io/spring-cloud-azure/current/reference/html/appendix.html#_azure_service_bus_properties.

Thanks @yiliuTo. Will try to use autoconfiguration as a practise. However the reconnecting issue still is present. Any standard practise to create an infinite receiver would be of great help.

**Comment by anuchandy** [comment]
CCing @ki1729 as he is communicating with support on the same case.

**Comment by srikarasr** [comment]
The issue is happening for the normal processor clients as well. 

```
public void startReceiving(String topicName, String subscriptionName, Consumer<ServiceBusReceivedMessageContext> onMessage, Consumer<ServiceBusErrorContext> onError) {
        ServiceBusProcessorClient serviceBusProcessorClient = this.sbConfiguration.getReceiverProcessorClient(topicName, subscriptionName, onMessage, onError);
        ExecutorService executorService = Executors.newSingleThreadExecutor();
        executorService.submit(() -> {
            log.info("Executor thread calling to start listener");
            serviceBusProcessorClient.start();

            while(true) {
                log.info("Checking the status of service bus connection");
                if (!serviceBusProcessorClient.isRunning()) {
                    log.info("Another processor client started since previous connection is closed");
                    serviceBusProcessorClient.start();
                }

                try {
                    TimeUnit.MINUTES.sleep((new RandomDataGenerator()).nextLong(5L, 7L));
                } catch (InterruptedException var2) {
                    log.error("Exception occurred in sleep thread for service bus.", var2);
                }
            }
        });
    }
```

**Comment by yiliuTo** [comment]
Given this is the behavior of using Service Bus Java SDK clients, thus assigning this issue to @ki1729 for better  communication.

**Comment by ki1729** [comment]
@srikarasr Thanks for reporting this issue, and sorrry about the delay in follow up. From your description of the issue, this sounds like one of the issues that was fixed earlier this year.. My recommendation here would be two-fold:
1. The most important one - please upgrade to the latest SDK version (7.12.1)
2.  The while loop section of your code (pasted below) can be removed. This is because in the processor client we have a dedicated monitor thread which checks for the status of the connection every 10 seconds and restarts the processor if the connection gets closed for any reason. This is the while section in your code that I was talking about :
```
           while(true){
                log.info("Checking the status of service bus connection");
                if(!sessionProcessor.isRunning()){
                    log.info("Another processor client started since previous connection is closed");
                    sessionProcessor.start();
                }
                try {
                    TimeUnit.MINUTES.sleep(new RandomDataGenerator().nextLong(5, 10));
                } catch (InterruptedException ex) {
                    log.error("Exception occurred in sleep thread for service bus.", ex);
                }
            }
```
