### ISSUE TITLE
[FEATURE REQ] Upgrade com.google.guava:guava to higher than 25

### ISSUE THREAD

**Issue by DenisVoloshin** [Azure/azure-sdk-for-java#29586]
I'm wondering if com.google.guava:guava:20 upgrade to the upper version (higher than 25) in your roadmap
The current version that is used in the client-runtime lib has a lot of security vulnerabilities 

**Describe the solution you'd like**

Upgrade com.google.guava:guava to higher than 25

thanks

**Comment by alzimmermsft** [comment]
Thank you for reporting this @DenisVoloshin. 

Just to clarify this is for `com.microsoft.rest:client-runtime` or `com.microsoft.azure:azure-client-runtime`? If so, many of the libraries using this have been superseded by [newer libraries](https://azure.github.io/azure-sdk/releases/latest/java.html), which have active development and their dependencies continually kept up-to-date.

**Comment by DenisVoloshin** [comment]
Hi @alzimmermsft, the better will be to share with you the dependency diagram 
![image](https://user-images.githubusercontent.com/20395483/175773309-f7b5cdd2-8993-4d80-9b33-724557da6964.png)

**Comment by DenisVoloshin** [comment]
Hi guys, is there any update?

**Comment by UcanInfosec** [comment]
I would like to add that the current version of guava is 31.1. Therefore, it might make sense to update guava to the most recent version. But I’m all for the updates

**Comment by alzimmermsft** [comment]
Apologies on the delay, I did take a look into upgrading to a newer version of Guava but unfortunately `client-runtime` supports Java 7+ and newer releases of Guava require Java 8 support. Additionally, I did a check on whether the usage of Guava was implementation only but some areas expose Guava types as public API, so attempting to remove Guava as a dependency would be a breaking change.

@weidongxu-microsoft mind looking at this issue further as you're one of the owners of the library.

**Comment by weidongxu-microsoft** [comment]
@DenisVoloshin 

The com.microsoft.azure:azure SDK is deprecated in March.
https://github.com/Azure/azure-libraries-for-java

Please consider migration to https://aka.ms/azsdk/java/mgmt

The reason that it uses an old version of guava of 20.0, is that this is the last version of guava that supports Java 7. And it is a requirement of the com.microsoft.azure:azure lib to be compatible with Java 7 runtime.

**Comment by alzimmermsft** [comment]
Given that Guava APIs are publicly exposed and `client-runtime` must support Java 7 I'm closing this as non-resolvable.
