### ISSUE TITLE
[QUERY] v8 UriQueryBuilder equivalent in v12 dataplane

### ISSUE THREAD

**Issue by rnaval** [Azure/azure-sdk-for-java#29596]
**Query/Question**
UriQueryBuilder does not seem to have an equivalent in com.azure.resourcemanager.**. Is there a new replacement for it? Any suggestions?

***Why is this not a Bug or a feature Request?***
Query related to migration from com.microsoft.azure.management.** to com.azure.resourcemanager.**

**Setup (please complete the following information if applicable):**
 - Library/Libraries: com.azure.resourcemanager.**

**Comment by joshfree** [comment]
Hi @rnaval thanks for reaching out to us via this GitHub issue.  @weidongxu-microsoft could you please help route @rnaval's question?

**Comment by weidongxu-microsoft** [comment]
`UriQueryBuilder` is from track1 storage https://docs.microsoft.com/java/api/com.microsoft.azure.storage.core.uriquerybuilder?view=azure-java-legacy

**Comment by weidongxu-microsoft** [comment]
@rickle-msft 

They are asking for a similar feature of `UriQueryBuilder` in track2 SDK.

But the `UriQueryBuilder` is from track1 storage data-plane (not management-plane, see the link). So would you please check if track2 storage have similar API for them.
If not, then maybe we will discuss whether we should add that in track2, and where.

@rnaval 
There is a [UrlBuilder](https://github.com/Azure/azure-sdk-for-java/blob/main/sdk/core/azure-core/src/main/java/com/azure/core/util/UrlBuilder.java) in azure-core, but it is not same as the API in track1.

**Comment by rnaval** [comment]
Thanks @weidongxu-microsoft - we'll look into `UrlBuilder`. But as you mentioned, this does not seem to be a direct replacement for `UriQueryBuilder`.

**Comment by weidongxu-microsoft** [comment]
@rnaval 
For formal answer from storage, please wait for @rickle-msft 

You may want to check if you can just use the implementation here https://github.com/Azure/azure-storage-java/blob/v8.6.6/microsoft-azure-storage/src/com/microsoft/azure/storage/core/UriQueryBuilder.java
(note it is in Apache 2.0 license, not MIT)

**Comment by rickle-msft** [comment]
@rnaval Can you please specify whether you are asking for a feature request in the resource manager or data plane package?

**Comment by rnaval** [comment]
@rickle-msft The `UriQueryBuilder` that we were using was from https://docs.microsoft.com/en-au/java/api/com.microsoft.azure.storage.core.uriquerybuilder?view=azure-java-legacy - so I'm thinking that the new one should be in the data-plane package.

**Comment by rickle-msft** [comment]
I see. Thank you for clarifying. It looks like the type in track 1 was marked as "Reserved for internal use", so I cannot guarantee that we will add support for it as it is not intended for use by external customers. As was mentioned, core has some utilities around this, and there is also the jvm's UriBuilder type that may be used. I can have a discussion with my team to see if it something we want to expose and support.
