### ISSUE TITLE
[BUG][azure-spring-data-cosmos]Use between on partition key not return all datas

### ISSUE THREAD

**Issue by zhangxj1977** [Azure/azure-sdk-for-java#29593]
**Describe the bug**
Used version.
```xml
    <dependency>
      <groupId>com.azure</groupId>
      <artifactId>azure-spring-data-cosmos</artifactId>
      <version>3.20.0</version>
    </dependency>
```

When I passed a between criteria on a partition key, if it has multiple values, then only return one partition results. 

***Code Snippet***
```java
Criteria.getInstance(CriteriaType.BETWEEN, "date", List.of("2022/06/01", "2022/06/10"), Part.IgnoreCaseType.NEVER);
```

I see that [isCrossPartitionQuery](https://github.com/Azure/azure-sdk-for-java/blob/main/sdk/cosmos/azure-spring-data-cosmos/src/main/java/com/azure/spring/data/cosmos/core/query/CosmosQuery.java#L118-L131) doesn't process between but only in criteria. Is that I'm using the wrong method?

**Comment by trande4884** [comment]
@zhangxj1977 can you please provide a little more info? Mainly, what is the query you are executing after creating your criteria? And it seems you are saying you expect > 1 result from your query but you are only getting 1 result back?
