### ISSUE TITLE
[BUG] Resource ID's returned from rest api do not respect case of resource group names created in portal

### ISSUE THREAD

**Issue by dclusin-cisco** [Azure/azure-sdk-for-java#29607]
**Describe the bug**
When resource ids are returned by the az cli they respect capitalization of resource group created by the user (for example resourceGroup) but all resource group ids returned across any service invocation are always upper-cased.

**To Reproduce**
Example AZ cli invocations:
`az group list`
```
  {
    "id": "/subscriptions/f0319a3f-4404-48f3-8a1e-06b0d38b0dcb/resourceGroups/anuj-group",
    "location": "eastus",
    "managedBy": null,
    "name": "anuj-group",
    "properties": {
      "provisioningState": "Succeeded"
    },
    "tags": {},
    "type": "Microsoft.Resources/resourceGroups"
  }
```
`az vm list --resource-group anuj-group`
```
  {

    "id": "/subscriptions/f0319a3f-4404-48f3-8a1e-06b0d38b0dcb/resourceGroups/anuj-group/providers/Microsoft.Compute/virtualMachines/anuj",
    "networkProfile": {
      "networkInterfaces": [
        {
          "deleteOption": null,
          "id": "/subscriptions/f0319a3f-4404-48f3-8a1e-06b0d38b0dcb/resourceGroups/anuj-group/providers/Microsoft.Network/networkInterfaces/anuj411",
          "primary": null,
          "resourceGroup": "anuj-group"
        }
      ]
    },
    "osProfile": {
    ...
    },
    "storageProfile": {
      "dataDisks": [],
      "osDisk": {
        "managedDisk": {
          "diskEncryptionSet": null,
          "id": "/subscriptions/f0319a3f-4404-48f3-8a1e-06b0d38b0dcb/resourceGroups/anuj-group/providers/Microsoft.Compute/disks/anuj_disk1_b9821ce0ce9e44a1a0a5bda94f26378d",
          "resourceGroup": "anuj-group",
        },
      }
    },
  }
```

However, when retrieving the result using the SDK VM list operation we get a resource id like:
`/subscriptions/f0319a3f-4404-48f3-8a1e-06b0d38b0dcb/resourceGroups/CLOUDKART-C0-RESOURCES/providers/Microsoft.Compute/virtualMachines/TestVM`

***Code Snippet***
Any listing of a service that has a resource ID

**Expected behavior**
Expected that the returned resource ID should match the case sensitivity of the created resource group. Could not find any documentation around this in Azure docs.

**Information Checklist**
Kindly make sure that you have added all the following information above and checkoff the required fields otherwise we will treat the issuer as an incomplete report
- [ ] Bug Description Added
- [ ] Repro Steps Added
- [ ] Setup information Added

**Comment by joshfree** [comment]
Thanks for filing this GitHub issue, @dclusin-cisco.  @weidongxu-microsoft could you please help route this?

**Comment by weidongxu-microsoft** [comment]
@dclusin-cisco

I think resource ID from ARM is case insensitive.

An indirect ref https://github.com/Azure/azure-resource-manager-rpc/blob/master/v1.0/resource-api-reference.md#put-resource

> The resource group names and resource names should be matched case insensitively. That means, for example, if a user creates a resource in resource group "rG1", and then calls a read operation on "RG1", the same resource should be returned even though the casing differs.
