### ISSUE TITLE
[QUERY] RestClient functionality when migrating to com.azure.resourcemanager.**

### ISSUE THREAD

**Issue by rnaval** [Azure/azure-sdk-for-java#29613]
**Query/Question**
I'm currently migrating to com.azure.resourcemanager.**, and I'm trying to replace the usage of `RestClient` based on https://github.com/Azure/azure-sdk-for-java/blob/main/sdk/resourcemanager/docs/MIGRATION_GUIDE.md#custom-http-client

However, I can't find an example using custom `BaseUrl`, `SerializerAdapter`, and `ResponseBuilderFactory` (looking at the underlying code in `RestClient` - seems to be using `retrofit`? 

e.g.
```
RestClient.Builder()
                .withBaseUrl(AzureEnvironment.AZURE, endpoint)
                .withSerializerAdapter(new AzureJacksonAdapter())
                .withReadTimeout(150, TimeUnit.SECONDS)
                .withResponseBuilderFactory(new AzureResponseBuilder.Factory())
                .withCredentials(azureTokenCredentials)
                .build()
```

Is there a resource that I can look at to see how to port the above functionality when migrating to com.azure.resourcemanager.**?

**Setup (please complete the following information if applicable):**
 - Library/Libraries: com.azure.resourcemanager.**

**Comment by weidongxu-microsoft** [comment]
@rnaval 

The `RestClient` is largely replaced by `HttpClient` and `HttpPipeline` from azure-core.

See [HttpPipelineBuilder](https://azuresdkdocs.blob.core.windows.net/$web/java/azure-core/latest/com/azure/core/http/HttpPipelineBuilder.html)

**Comment by weidongxu-microsoft** [comment]
If you've created the `HttpPipeline` (be careful with that, as it is not trivial), you can use `AzureResourceManager.authenticate(HttpPipeline, AzureProfile)` to initialiate `AzureResourceManager`.

You can refer to [HttpPipelineProvider](https://github.com/Azure/azure-sdk-for-java/blob/main/sdk/resourcemanager/azure-resourcemanager-resources/src/main/java/com/azure/resourcemanager/resources/fluentcore/utils/HttpPipelineProvider.java) for reference about how to build `HttpPipeline` for resourcemanager.

**Comment by rnaval** [comment]
Thanks @weidongxu-microsoft - do you have a link for examples that I can refer to when using `HttpPipelineBuilder`?

**Comment by weidongxu-microsoft** [comment]
javadoc on HttpPipelineBuilder has a simple sample https://azuresdkdocs.blob.core.windows.net/$web/java/azure-core/latest/com/azure/core/http/HttpPipelineBuilder.html

HttpPipelineProvider internally used in azure-resourcemanager provides a sample on how we initialize it https://github.com/Azure/azure-sdk-for-java/blob/main/sdk/resourcemanager/azure-resourcemanager-resources/src/main/java/com/azure/resourcemanager/resources/fluentcore/utils/HttpPipelineProvider.java#L66
