### ISSUE TITLE
[QUERY] Does iterableByPage enable for all resource provider?

### ISSUE THREAD

**Issue by chuckz1321** [Azure/azure-sdk-for-java#29640]
**Query/Question**
A clear and concise ask/query.
Does iterableByPage support AzureResourceManager.virtualMachineImages().listByRegion() ?

***Why is this not a Bug or a feature Request?***
A clear explanation of why is this not a bug or a feature request?
iterableByPage() returns all entities...
![image](https://user-images.githubusercontent.com/33536264/175546697-7fcc1ec9-2e85-45e7-9706-9767e0d86587.png)

**Setup (please complete the following information if applicable):**
 - OS: [e.g. iOS] Windows
 - IDE: [e.g. IntelliJ] InterlliJ
 - Library/Libraries: [e.g. com.azure:azure-core:1.16.0 (groupId:artifactId:version)] azure-resourcemanager 2.10.0
 
 **Information Checklist**
 Kindly make sure that you have added all the following information above and checkoff the required fields otherwise we will treat the issuer as an incomplete report
- [ ] Query Added
- [ ] Setup information Added    use this SDK in Mooncake

**Comment by joshfree** [comment]
Hi @chuckz1321 thanks for reaching out to us via this GitHub issue.  @weidongxu-microsoft could you please follow up with @chuckz1321?

**Comment by weidongxu-microsoft** [comment]
@chuckz1321

This API is an exception. There is no REST API to list images by region. It had to be done cascaded, list by offer, list by sku on offer, list by image on sku.
https://github.com/Azure/azure-sdk-for-java/blob/main/sdk/resourcemanager/azure-resourcemanager-compute/src/main/java/com/azure/resourcemanager/compute/implementation/VirtualMachineImagesImpl.java#L85-L98

We currently have no good solution to make this nested API call truly pageable.
You may call following API (but then need to iterate again on different sku and offer)
```java
        azure
            .virtualMachines()
            .manager()
            .serviceClient()
            .getVirtualMachineImages()
            .listWithResponse(...);
```

link https://github.com/Azure/azure-sdk-for-java/issues/19494

**Comment by chuckz1321** [comment]
@weidongxu-microsoft Thanks for you help! Actually we were facing the issue that the query may take longer time and each images will interactive with management endpoint, so that the netty thread will block and finally throw an exception saying the queue is not enough to hold more requests. I configured the netty connection provider and mitigted this issue. (Simply enlarge the timeout parameter...)
