### ISSUE TITLE
Set "-Dmaven.wagon.http.pool=false" in all Maven tasks

### ISSUE THREAD

**Issue by mikeharder** [Azure/azure-sdk-for-java#2964]
The parameter `-Dmaven.wagon.http.pool=false` should be added to all Maven tasks in `client.yml` and `client.test.live.yml` which could fail without this setting.  Currently the parameter is added to only one task:

https://github.com/Azure/azure-sdk-for-java/blob/837d7ce95cccae7e993515ea1081a8acf7e965d1/.azure-pipelines/client.test.live.yml#L31-L35

**Comment by weshaggard** [comment]
Addressed with https://github.com/Azure/azure-sdk-for-java/pull/2957
