### ISSUE TITLE
createBlobContainerIfNotExists prints error to console

### ISSUE THREAD

**Issue by ThijsBroersen** [Azure/azure-sdk-for-java#29646]
When I try to use `createBlobContainerIfNotExists` it prints the following to my console:

```
Unexpected character ('<' (code 60)): expected a valid value (JSON String, Number, Array, Object or token 'null', 'true' or 'false')
 at [Source: (byte[])"<?xml version="1.0" encoding="utf-8"?><Error><Code>ContainerAlreadyExists</Code><Message>The specified container already exists.</Message></Error>"; line: 1, column: 2]
```

The are multiple things wrong with this:
1. this is no error because I only ask the client to create-if-not-exists
2. it looks like it cannot be disabled; it is insensitive to any log-settings and does not follow any appender format, maybe it is just a println somewhere

**Comment by ThijsBroersen** [comment]
@ibrahimrabab thanks for your response. 
It seems I was mistaken and the loglevel is respected. So it seems there is a decoding issue which is logged as warning.

As described above it occurs when calling `createBlobContainerIfNotExists` on a client created with ```BlobServiceClientBuilder()
            .connectionString(connectionString)
            .buildAsyncClient()```
```
WARN com.azure.core.implementation.serializer.HttpResponseBodyDecoder - Failed to deserialize the error entity.
Unexpected character ('<' (code 60)): expected a valid value (JSON String, Number, Array, Object or token 'null', 'true' or 'false')
 at [Source: (byte[])"<?xml version="1.0" encoding="utf-8"?><Error><Code>ContainerAlreadyExists</Code><Message>The specified container already exists.</Message></Error>"; line: 1, column: 2]
```

**Comment by ThijsBroersen** [comment]
Hmm, just got thinking. The is for an Azurite container. I think this is where the mismatch is between the azure sdk and Azurite container response. Makes sense.

**Comment by ibrahimrabab** [comment]
I see, that makes sense. Is it okay if we close this issue then?

**Comment by ThijsBroersen** [comment]
Just updated the Azurite image to `mcr.microsoft.com/azure-storage/azurite:3.18.0` and now I do not see the deserialize warning anymore. Will close the ticket.
