### ISSUE TITLE
Can we integrate JCA provider with Jarsigner?

### ISSUE THREAD

**Issue by umarbaba** [Azure/azure-sdk-for-java#29659]
**Query/Question**
Can we use JCA provider with "Jarsigner" to sign the .jar files, keeping the certificate in azure keyvault
used project path :- azure-sdk-for-java/sdk/keyvault/azure-security-keyvault-jca/

 **Tried so far**
1. I have a certificate in azure keyvault ready.
2. I took the JCA Provider jar from maven repository and placed it under this folder "JavaHome\jre\lib\ext ". And added JCA provider class definition in "java.security" file, which has other provider info as well.
3. Then i tried to sign the jar using this command
    Jarsigner -keystore None -storetype AzureKeyVault -signedjar signerjar.jar jartosign.jar myalias -storepass "" -verbose
4. Signing was working with generic RSA Signing as the certificate was getting exported with its private key.
5. Next I have restricted the keyvault not to export the certificate with its private key.
6. Now the signing is failing with the error mentioned below.

  Key = com.azure.security.keyvault.jca.implementation.KeyVaultPrivateKey@60129b9a
 updating: META-INF/MANIFEST.MF
jarsigner error: java.security.InvalidKeyException: No installed provider supports this key: com.azure.security.keyvault.jca.implementation.KeyVaultPrivateKey

Do we need to update the JCA provider with some more implementations or did we miss to configure something
Any suggestions would be highly appriciated .

**Comment by backwind1233** [comment]
@umarbaba Thank you for reaching out, I am followwing this issue and will inform you when we have some conclusions.

**Comment by backwind1233** [comment]
Hi @umarbaba, 

You can integrate keyvault JCA provider with Jarsigner with certificate contains both public private keys.
But I think it's not possible if  you restricte the keyvault not to export the certificate with its private key.
As you can see with the output fo comand `jarsigner -h`

```
jarsigner [ options ] jar-file alias

jarsigner -verify [ options ] jar-file [alias ...]
```

You need the private key to sign.

If you just have public certificate containing the public key, you can only verify with it.
