### ISSUE TITLE
[BUG]Showing total cosmos clients per database account

### ISSUE THREAD

**Issue by xinlian12** [Azure/azure-sdk-for-java#29669]
![image](https://user-images.githubusercontent.com/64233642/176293056-835b4bff-5296-4833-b188-436b7337d728.png)

It shows how many clients are created currently and we are using it to give customer the recommendation to follow singleton pattern. But the fact is, even though it shows > 1 clients are created, it does not necessarily mean the client is not following the singleton pattern as they may need to connect to different database account.

So the goal is to have a client count per database account there

**Comment by kushagraThapar** [comment]
This is done.
