### ISSUE TITLE
Update cosmos documents using Update Query

### ISSUE THREAD

**Issue by jyoti121** [Azure/azure-sdk-for-java#29661]
**Query/Question**
Is there a way to update multiple documents using Update SQL query in cosmos SDK. Or any other alternate to achieve this?
Also, since large number of documents can be updated, can we execute it as a Batch operation? So that the read operations are not impacted during this time.

***Why is this not a Bug or a feature Request?***
There may be another alternate to do this but that might consume more RUs. 

**Setup (please complete the following information if applicable):**
 - OS: iOS
 - IDE: IntelliJ
 - Library/Libraries: com.azure:azure-core:4.15.0
 
 **Information Checklist**
 Kindly make sure that you have added all the following information above and checkoff the required fields otherwise we will treat the issuer as an incomplete report
- [ ] Query Added
- [ ] Setup information Added

**Comment by TheovanKraay** [comment]
Hello @jyoti121 if the goal is to have transactional semantics (scoped to a logical partition), you can use batch - see documentation [here](https://docs.microsoft.com/en-us/azure/cosmos-db/sql/transactional-batch?tabs=java) and comprehensive sample [here](https://github.com/Azure-Samples/azure-cosmos-java-sql-api-samples/blob/main/src/main/java/com/azure/cosmos/examples/batch/async/SampleBatchQuickStartAsync.java).

**Comment by jyoti121** [comment]
Thanks @TheovanKraay  for the response.
I am looking for making updates in multiple documents(may not be transactional) based on query.
Example Operation: update status in all documents where document_name = 'Test' (here 'status' and 'document_name' are fields in document)
In Transactional Batch, we need to pass ids of the documents which needs to be updated.

**Comment by TheovanKraay** [comment]
@jyoti121 I see. The Cosmos DB SQL language only supports the Select statement, there is no update statement. To achieve what you want, you need to first retrieve all the docs you want to update, then you can use patch in [bulk support](https://github.com/Azure-Samples/azure-cosmos-java-sql-api-samples/blob/main/src/main/java/com/azure/cosmos/examples/bulk/async/SampleBulkQuickStartAsync.java) to update only the status field in each document, for example.

**Comment by TheovanKraay** [comment]
@jyoti121 does this answer your question? Can we close this issue?
