### ISSUE TITLE
[QUERY]: Provide SDK API to monitor the status of deployment on Azure Web App slot

### ISSUE THREAD

**Issue by ivan-83** [Azure/azure-sdk-for-java#29677]
Could you add provide SDK API to monitor the status of artifact deployment on the Web App slot, or expose the REST endpoint?

**Comment by joshfree** [comment]
Hi @ivan-83 thanks for posting this question.  @weidongxu-microsoft could you please follow up?

**Comment by weidongxu-microsoft** [comment]
The API was added to spec https://github.com/Azure/azure-rest-api-specs/pull/19259 and merged a few days ago.
@ivan-83 You might want to check first if this is the API you wanted.

@XiaofeiCao Please have it in your schedule in July.
- Upgrade to 2022-03-01
- Support the 2 APIs (we cannot use LRO as it is a GET, which is not supported for LRO in core)
- Update test https://github.com/Azure/azure-sdk-for-java/blob/main/sdk/resourcemanager/azure-resourcemanager-appservice/src/test/java/com/azure/resourcemanager/appservice/OneDeployTests.java#L104

**Comment by ivan-83** [comment]
Hi, @weidongxu-microsoft this is great! When can we expect this to be implemented as part of SDK and REST endpoints?

We are using `com.microsoft.azure:azure:1.31.1`lib version, whether it will be backward compatible and implemented for this version or we should rely on REST endpoints?

**Comment by weidongxu-microsoft** [comment]
@ivan-83 

Yes, I think so.

I've tried it on 2022-03-01 api-version couple of days ago. Also I think 2021-03-01 should also work.
