### ISSUE TITLE
Cosmos partial update

### ISSUE THREAD

**Issue by sachindedhia** [Azure/azure-sdk-for-java#29682]
I saw in documentation that connector now support partial update using ItemPatch but I haven't found any code about the implementation.

It will be really useful if you can provide me any sample code.

Thanks

**Comment by kushagraThapar** [comment]
@sachindedhia - which connector are you talking about?

**Comment by FabianMeiswinkel** [comment]
This PR - https://github.com/Azure/azure-sdk-for-java/pull/27435 - has a link to the desing document and also is adding some tests that can be used as a sample

Design document: https://github.com/Azure/azure-sdk-for-java/files/9014885/Patch_On_Spark_Connector.pdf

Test: https://github.com/Azure/azure-sdk-for-java/pull/27435/files#diff-dc18c45cd0ea6e57b54d07908eba2df1346170ceda41bfa10aa263dee7d2ebbe

**Comment by sachindedhia** [comment]
@FabianMeiswinkel , Thanks for the documentation, but my scenario is slightly different and not sure how to handle this using patch.

I've existing document in cosmos refer - KS1 example below : the document has already KS1 array in cosmos and I want to add another array for KS2 so the document would like - see KS1 & KS2 example below. so I've created dataframe as - see example df- also see my code for spark below - not sure how do I append to the array, any pointer will be really appreciated.



**KS1 example:**
{
    "PupilMatchingRef": "XXXB",
    "UPN": "Y887220217054",
    "Surname": "XXX",
    "Forename": "XXX",
    "Gender": "F",
    "DOB": "XXXX-09-25T00:00:00.000Z",
    "CreatedAt": "0",
    "LastModifiedAt": "0",
    "KS1": [
        {
            "ACADYR": "2025/2026",
            "DISC_MAT": "0",
            "DISC_PSENG": "0",
            "DISC_PSLISTEN": "0",
            "DISC_PSMATHS": "0",
            "DISC_PSNUM": "0",
            "DISC_PSREAD": "0",
            "DISC_PSSCIENCE": "0",
            "DISC_PSSHAPE": "0",           
        }
    ],
    "id": "59A3047E395CF2273B",
    "_rid": "aQQ4ANvlYXImNgAAAAAACg==",
    "_self": "dbs/aQQ4AA==/colls/aQQ4ANvlYXI=/docs/aQQ4ANvlYXImNgAAAAAACg==/",
    "_etag": "\"3800c4fc-0000-0d00-0000-62c201240000\"",
    "_attachments": "attachments/",
    "_ts": 1656881444
}


**KS1 & KS2 example:**
{
    "PupilMatchingRef": "XXXB",
    "UPN": "Y887220217054",
    "Surname": "XXX",
    "Forename": "XXX",
    "Gender": "F",
    "DOB": "XXXX-09-25T00:00:00.000Z",
    "CreatedAt": "0",
    "LastModifiedAt": "0",
    "KS1": [
        {
            "ACADYR": "2025/2026",
            "DISC_MAT": "0",
            "DISC_PSENG": "0",
            "DISC_PSLISTEN": "0",
            "DISC_PSMATHS": "0",
            "DISC_PSNUM": "0",
            "DISC_PSREAD": "0",
            "DISC_PSSCIENCE": "0",
            "DISC_PSSHAPE": "0",           
        }
    ],
    "KS2": [
        {
            "ACADYR": "2025/2026",
            "DISC_MAT": "0",
            "DISC_PSENG": "0",
            "DISC_PSLISTEN": "0",
            "DISC_PSMATHS": "0",
            "DISC_PSNUM": "0",
            "DISC_PSREAD": "0",
            "DISC_PSSCIENCE": "0",
            "DISC_PSSHAPE": "0",           
        }
    ],
    "id": "59A3047E395CF2273B",
    "_rid": "aQQ4ANvlYXImNgAAAAAACg==",
    "_self": "dbs/aQQ4AA==/colls/aQQ4ANvlYXI=/docs/aQQ4ANvlYXImNgAAAAAACg==/",
    "_etag": "\"3800c4fc-0000-0d00-0000-62c201240000\"",
    "_attachments": "attachments/",
    "_ts": 1656881444
}

df - 

![image](https://user-images.githubusercontent.com/53565935/177058034-1d8747ca-abbe-4c93-9dab-d03e45931593.png)

spark code 
writeConfigCosmos = {
        "spark.cosmos.accountEndpoint" : self._config['EndPoint'],
        "spark.cosmos.accountKey" : self._config['MasterKey'],
        "spark.cosmos.database" : self._config['Database'],
        "spark.cosmos.container" : collection, #e.g. "reference", 
        "spark.cosmos.write.strategy": "ItemPatch",
        "spark.cosmos.write.patch.defaultOperationType": "Add",
        "spark.cosmos.serialization.inclusionMode" : "NonNull",
        
        "spark.cosmos.write.bulk.enabled": "true",
        "mode" : write_config.get('mode', 'append')
    }
