### ISSUE TITLE
[QUERY] SpringBootTest fails since config is loaded only once

### ISSUE THREAD

**Issue by ac-rdn** [Azure/azure-sdk-for-java#29699]
**Query/Question**
My Spring Boot project gets its configuration from an Azure Config Store. `AppTest` (annotated with SpringBootTest) verifies if the application context is correctly loaded. And to load the application context correctly it requires that the configuration is loaded from the Config Store (since beans will be created through auto configuration). And that's all working great!
But yesterday I added another test: `RepoTest` (annotated with DataJpaTest) and now `AppTest` fails if `RepoTest` runs first. It took me several hours to debug this issue, but finally I found the root cause: in `AppConfigurationPropertySourceLocator` has a guard `configloaded` to guarantee the config is loaded once. So although two application contexts are loaded (one for `AppTest` and one for `RepoTest`), the config is loaded only once. So if `RepoTest` runs before `AppTest`, the latter will fail because config is not loaded anymore and thus beans will not be created.

***Why is this not a Bug or a feature Request?***
I am quite new to Azure, so not sure if it's a bug. But probably I am just doing something wrong or missing something (and I have to add e.g. an annotation)

**Setup (please complete the following information if applicable):**
 - IDE: IntelliJ
 - Library/Libraries: com.azure.spring:azure-spring-cloud-dependencies:2.12.0
 
 **Information Checklist**
 Kindly make sure that you have added all the following information above and checkoff the required fields otherwise we will treat the issuer as an incomplete report
- [x] Setup information Added

**Comment by saragluna** [comment]
@mrm9084 could you take a look?

**Comment by mrm9084** [comment]
@ac-rdn, this was an intentional add as during normal production run if other property sources are generated it could trigger an un-needed reload of configurations at startup. I am assuming this is for integration tests, not unit tests as I would suggest disabling loading from app config for unit test this can be done through `@SpringBootTest(properties = "spring.cloud.azure.appconfiguration.enabled=false")`.

I am taking a look to replicate and see if there is a workaround at the moment. Otherwise, I think we may need to revisit the implementation of the guard for this use case.

**Comment by ac-rdn** [comment]
@mrm9084 You are correct! Both tests are indeed integration tests and not unit tests. Disabling loading the app config for my repository integration test, so it will be loaded for my application integration test works for me 👍 But it only works because I am ok to run my repository integration test against the default in-memory database (provided by the `DataJpaTest` annotation). If I want to run them against the dev (or any other) database, this workaround would not be possible since it would require to load app configuration for both tests.

Although I can understand the reason for implementing the guard for normal production usage, it is definitely an issue when running (integration) tests. E.g. If you have more than one integration test requiring to load app configuration, it will only be loaded once (and thus all other integration tests will fail). In Spring you have the DirtiesContext annotation which removes the loaded context, so other tests will get a new one. And this annotation can be applied on both class and method level.

So I think implementation of this guard should be revisited or at least provide some possibility to bypass it and load the app configuration more than once.
