### ISSUE TITLE
[QUERY] BatchAccounts usage when migrating to com.azure.resourcemanager.**

### ISSUE THREAD

**Issue by rnaval** [Azure/azure-sdk-for-java#29697]
**Query/Question**
Previously, the list of BatchAccounts can be obtained by calling `batchAccounts().list()` from the `Azure` object. 

Is it expected that we cannot access these via the `AzureResourceManager` object? How can these be obtained?

**Comment by joshfree** [comment]
Hi @rnaval thank for you posting this GitHub issue. @weidongxu-microsoft from the `Mgmt` team will follow up shortly.  Thanks

**Comment by weidongxu-microsoft** [comment]
@rnaval 

The batch management-plane client is moved to its separate package here.
https://github.com/Azure/azure-sdk-for-java/tree/main/sdk/batch/azure-resourcemanager-batch

You can find the guide on authentication in above readme, and the samples here
https://github.com/Azure/azure-sdk-for-java/blob/main/sdk/batch/azure-resourcemanager-batch/SAMPLE.md#batchaccount_list
