### ISSUE TITLE
Update versions based on Component Governance recommendations 

### ISSUE THREAD

**Issue by weshaggard** [Azure/azure-sdk-for-java#2970]
Our Component Governance task is suggesting the following version updates:

/mediaservices/data-plane/pom.xml
org.bouncycastle:bcprov-jdk15on -> 1.6.0
com.fasterxml.jackson.core:jackson-databind -> 2.9.6
com.fasterxml.jackson.core:jackson-core -> 2.9.6

/cognitiveservices/data-plane/pom.xml
com.fasterxml.jackson.core:jackson-databind -> 2.9.6
com.fasterxml.jackson.core:jackson-core -> 2.9.6
com.google.guava:guava -> 25.0

/pom.xml
com.fasterxml.jackson.core:jackson-databind -> 2.9.6
com.google.guava:guava -> 25.0 

For more details on the version recommendations see https://dev.azure.com/azure-sdk/internal/_componentGovernance/106501?_a=alerts&typeId=390820&alerts-view-option=active

**Comment by weshaggard** [comment]
@lmazuel @jianghaolu we need to get some movement on getting these dependencies updated. Do you have an ETA?

**Comment by cheenamalhotra** [comment]
Any update on ETA?
