### ISSUE TITLE
[FEATURE REQ] Test Spring Cloud Azure 4.0 with storage emulator and cosmos emulator

### ISSUE THREAD

**Issue by backwind1233** [Azure/azure-sdk-for-java#29718]
**Is your feature request related to a problem? Please describe.**
Spring Cloud Azure 4.0 should work with both real Azure backend services as well as service-provided emulators, such as the Storage emulator and the Cosmos emulator.

**Describe the solution you'd like**
1. Test current 4.0 implementation to see whether it could work with the aforementioned emulators.
2. Write a guide on how to use Storage and Cosmos Emulator with Spring Cloud Azure locally in reference doc.

**Describe alternatives you've considered**
NA

**Additional context**
NA

**Information Checklist**
Kindly make sure that you have added all the following information above and checkoff the required fields otherwise we will treat the issuer as an incomplete report
- [X] Description Added
- [x] Expected solution specified

**Comment by eddumelendez** [comment]
Hi, #40388 shows how to test using CosmosDB and Azurite emulator
