### ISSUE TITLE
Added End-to-End Tests for all HttpPipelinePolicies

### ISSUE THREAD

**Issue by alzimmermsft** [Azure/azure-sdk-for-java#29722]
With the on-going effort to support fully synchronous and fully asynchronous `HttpPipeline` -> `HttpClient` stacks all `HttpPipelinePolicy` implementations should add full end-to-end tests to validate their functionality. Before this effort only testing implementation details was sufficient as there was only one calling path and if the internals worked the path worked, but now there are two potential calling paths that will need to be validated. So, if the internals was correct and asynchronous was correct this doesn't infer synchronous will be correct.

**Comment by samvaity** [comment]
Full end-to-end tests to validate Sync and async functionality to be validated as part of SDK tests when onboarding SDK's to sync and async workflow respectively.

**Comment by g2vinay** [comment]
Will be tested via individual SDK Testing when they onboard to sync stack.
