### ISSUE TITLE
[FEATURE REQ] provide guidance and details about Service Bus SDK using Session, Async, Sync, Close client for Java/Spring Boot applications.

### ISSUE THREAD

**Issue by madossan01** [Azure/azure-sdk-for-java#29751]
**Is your feature request related to a problem? Please describe.**
Service Bus SDK documentation currently lacks guidance that support Java developer on decisions about the use of Sessions, Async x Sync messages when implementing a Sender/Receiver and how properly close the client.

**Describe the solution you'd like**
The Service Bus documentation for Java/Spring Boot should provide guidance and details about the topics below. It would save time from developers as they would not need to explore and spike options before deciding for the best approach (Async x Sync) or implementation (Session x No Session).
> - Use of Service Bus topic with session: "how to" and scenarios that require/recommend the use of sessions. Explain whether it is possible to have multiple subscribers when using Topics with Session Ids and the recommendations associated to it.
> - Comparison Async x Sync Message Sender/Receiver. Also benefits and implications of using one or the other.
> - Recommendations on how properly close a client (Receiver/Sender)

**Describe alternatives you've considered**
N/A

**Additional context**

**Information Checklist**
Kindly make sure that you have added all the following information above and checkoff the required fields otherwise we will treat the issuer as an incomplete report
- [x] Description Added
- [x] Expected solution specified

**Comment by joshfree** [comment]
Hi @madossan01 thank you for filing this GitHub issue.  Someone from the `azure-spring` team will follow up shortly.

/cc @Azure/azsdk-sb-java as FYI

**Comment by saragluna** [comment]
This is more like a Service Bus SDK issue than a Spring issue, but we definitely could improve the docs for Spring libraries too. 

Azure SDKs provide both sync and async clients for all service and here is a blog about the general difference https://devblogs.microsoft.com/azure-sdk/async-programming-with-project-reactor/. 

As to when and how use sessions with Service Bus, here are what I found:
- https://github.com/Azure/azure-sdk-for-java/blob/main/sdk/servicebus/azure-messaging-servicebus/README.md#send-and-receive-from-session-enabled-queues-or-topics
- https://docs.microsoft.com/en-us/azure/service-bus-messaging/message-sessions

@Azure/azsdk-sb-java could you take a look at this issue and provide some guidance?

**Comment by stliu** [comment]
@joshfree what do you think about @saragluna 's comment above?

**Comment by brunomace** [comment]
Any update on this ?
Especially for Spring Cloud Stream with Azure Service Bus Binder, is it possible to dispose a session used by a consumer ? We can only configure the `maxConcurrentSessions`, so if the number of sessions has reached this maximum value, and no more message are published for these sessions, our receiver will never be called.

**Comment by saragluna** [comment]
> Any update on this ? Especially for Spring Cloud Stream with Azure Service Bus Binder, is it possible to dispose a session used by a consumer ? We can only configure the `maxConcurrentSessions`, so if the number of sessions has reached this maximum value, and no more message are published for these sessions, our receiver will never be called.

@@Azure/azsdk-sb-java and @anuchandy, do you know how to dispose session in this scenario?
