### ISSUE TITLE
Implement a landing page that contains all Spring on Azure Samples

### ISSUE THREAD

**Issue by chenrujun** [Azure/azure-sdk-for-java#29750]
## Context

`Spring on Azure samples` means all samples related to Spring and Azure products. Now these samples are distributed in many places. It caused customer hard to find their required sample.

## Goal

1. Provide a landing page that can help customer get all `Spring on Azure` related samples. 
2. Make sure the entry to related sample is easy to understand.

## Solution

 - [ ] Determine where to put the landing page. Here are some proposals:
   - Create a new page in MS docs. For example: https://docs.microsoft.com/en-us/azure/developer/java/spring/samples (Now this link returns 404)
   - Create a new GitHub repository in [Azure-Sample organization](https://github.com/Azure-Samples), use the repository's README as landing page.
   - Not create a new page, just put these samples in Code&Samples in MS docs: https://docs.microsoft.com/en-us/samples/browse/

        ### Table: Comparing each method of putting the landing page
        
        | Option | Customer can browse all sample | Customer can provide feedback & discussion & search discussion history | Customer will think it's ffficial entry
        | -- | -- | -- | -- |
        | New MS docs page | :heavy_check_mark: | :x: | :heavy_check_mark: |
        | Current Code&Samples in MS docs| :x: | :x: | :heavy_check_mark: |
        | New GitHub repository | :heavy_check_mark: | :heavy_check_mark: | :heavy_check_mark: |

 - [ ] Implement the landing page.

**Comment by stliu** [comment]
- [ ] Feature Spec Review
- [ ] Design Spec Review

**Comment by chenrujun** [comment]
After discussing with other team members, now we won't provide such kind of landing page.

We will improve these pages instead:
1. https://learn.microsoft.com/en-us/samples/browse/?languages=java&expanded=azure
2. https://spring.io/guides#topical-guides
3. https://spring.io/projects/spring-cloud-azure#samples
