### ISSUE TITLE
[FEATURE REQ] Enhance developer experience: provide comparison and guidance about the flavors of SDK available

### ISSUE THREAD

**Issue by madossan01** [Azure/azure-sdk-for-java#29752]
**Is your feature request related to a problem? Please describe.**

At the beginning of a Java Spring boot application development with Service Bus, a developer needs to choose the SDK to use. With the sort of SDK flavors available it is hard to choose one without having samples and documentation exploring the benefits and limitations of each option. It is also likely possible someone will not have enough time to test all of them within a project. 

**Describe the solution you'd like**
Enhance experience when exploring samples and documentation: add information about the different SDKs available - which one to use/when, limitations and highlights.  
Also, please include information about the difference between azure-service-bus and spring-cloud-azure-starter-servicebus-jms libraries.

**Describe alternatives you've considered**
Java developers spiking on each option, as needed, and use communities to share the findings. This alternative may lead to non-curated information.

**Additional context**
N/A

**Information Checklist**
Kindly make sure that you have added all the following information above and checkoff the required fields otherwise we will treat the issuer as an incomplete report
- [x] Description Added
- [x] Expected solution specified

**Comment by joshfree** [comment]
@yiliuTo could you please follow up with @madossan01

**Comment by saragluna** [comment]
Thanks for filing this issue, and we do provide several options when users want to use Service Bus. 
- [Azure Service Bus SDK](https://github.com/Azure/azure-sdk-for-java/tree/main/sdk/servicebus/azure-messaging-servicebus) is a Microsoft supported native SDK for sending/receiving/managing messages as well as administrating Azure Service Bus resources like Topics/Queues. 
- [JMS](https://docs.oracle.com/javaee/6/tutorial/doc/bncdr.html): Azure Service Bus supports connection via JMS APIs (2.0 and 1.1) using AMQP 1.0 protocol. More information regarding Azure Service Bus supporting JMS can be found [here](https://docs.microsoft.com/en-us/azure/service-bus-messaging/jms-developer-guide?tabs=JMS-20). 
- [Spring Cloud Stream Binder for Service Bus](https://microsoft.github.io/spring-cloud-azure/current/reference/html/index.html#spring-cloud-stream-support): Spring Cloud Stream is a Spring framework to decouple the producing/consuming logic of an application with the actual messaging brokers, so you can use the same code and replace the messaging brokers easily.

The function differences between these libraries are:
| Library                                    | Authentication                                         | Support Batching | Support Sessions | Support Auto Lock Renewal | Error Handling              |
| ------------------------------------------ | ------------------------------------------------------ | ---------------- | ---------------- | ------------------------- | --------------------------- |
| Azure Service Bus SDK                      | Connection String, Service Principal, Managed Identity | Yes              | Yes              | Yes                       | Service Bus Exceptions      |
| JMS API                                    | Connection String                                      | No               | No               | No                        | JMS Exceptions              |
| Spring Cloud Stream Binder for Service Bus | Connection String, Service Principal, Managed Identity | No         

There are also some differences when talk about how Spring supports them:
 | Library                                    | Spring framework's support                                                                                            | Spring Cloud Azure's support                                                                                     |
| ------------------------------------------ | --------------------------------------------------------------------------------------------------------------------- | ---------------------------------------------------------------------------------------------------------------- |
| Azure Service Bus SDK                      | None                                                                                                                  | `spring-cloud-azure-starter-servicebus`  is a spring starter helping configuring the Service Bus SDK clients.    |
| JMS API                                    | `spring-jms` provides `JmsTemplate` and `@JmsListener` for users to pub/sub messages using Spring's programming model | `spring-cloud-azure-starter-servicebus-jms` is a spring starter helping configuring the `spring-jms` with Azure Service Bus |
| Spring Cloud Stream Binder for Service Bus | None                                                                                                                  | `spring-cloud-azure-stream-binder-servicebus` is a binder library for Azure Service Bus.                         | 

Samples for how to using these Spring libraries can be found:
- [Use Spring Cloud Azure JMS Starter](https://github.com/Azure-Samples/azure-spring-boot-samples/tree/spring-cloud-azure_v4.3.0/servicebus/spring-cloud-azure-starter-servicebus-jms)
- [Use Spring Cloud Azure Stream Binder]https://github.com/Azure-Samples/azure-spring-boot-samples/tree/spring-cloud-azure_v4.3.0/servicebus/spring-cloud-azure-stream-binder-servicebus

Reference doc for how to using these Spring libraries can be found:
- [Use Spring Cloud Azure Starter for Service Bus](https://microsoft.github.io/spring-cloud-azure/current/reference/html/index.html#autoconfigure-azure-sdk-clients) and [configuration properties](https://microsoft.github.io/spring-cloud-azure/current/reference/html/appendix.html#_azure_service_bus_properties)
- [Use Spring Cloud Azure Stream Binder for Service Bus](https://microsoft.github.io/spring-cloud-azure/current/reference/html/index.html#spring-cloud-stream-binder-for-azure-service-bus)
- [Use Spring Cloud Azure JMS Starter](https://microsoft.github.io/spring-cloud-azure/current/reference/html/index.html#spring-jms-support) and [configuration properties](https://microsoft.github.io/spring-cloud-azure/current/reference/html/appendix.html#_azure_service_bus_jms_properties)

**Comment by JorgeCupiV** [comment]
@saragluna this is an awesome reference table! Is this somewhere in the official documentation? I don't recall seeing it before and its pretty self explanatory on when/how to use which flavor available

**Comment by saragluna** [comment]
Hi @JorgeCupiV, no, we don't have it in the official documentation yet, @stliu do you think we should have an official doc for it?

**Comment by JorgeCupiV** [comment]
Hey @saragluna and @stliu, hope you are doing fine. Just double checking with you to see if you have considered to include this comparison table at official documentation.

**Comment by saragluna** [comment]
Hi @JorgeCupiV, @stliu is on vacation now and we'll discuss this when he is back.

**Comment by saragluna** [comment]
Hi @JorgeCupiV, @stliu and I discussed this and we surely want to provide such doc. But since we have many other feature requests on hand and lack resources, we would like to consider this feature request next semester.

**Comment by JorgeCupiV** [comment]
I see, thanks @saragluna. If there's anything I can do on my side to help with the review or creation of said table I would love to contribute

**Comment by stliu** [comment]
we have a [doc pattern](https://review.learn.microsoft.com/en-us/help/patterns/level4/article-compare-services?branch=main) for this kind of doc
