### ISSUE TITLE
[FEATURE REQ] Demonstrate how to use Sessions (Producer & Receiver) for Spring Cloud Azure Service Bus

### ISSUE THREAD

**Issue by madossan01** [Azure/azure-sdk-for-java#29765]
**Is your feature request related to a problem? Please describe.**
When implementing Topics with Named Sessions in the project, we looked for Java Spring Boot Samples that could give an initial starting point for Producer and Receiver scenarios. 

We were able to find some samples, but they were related to Queues or related to Receiver only. 
https://github.com/Azure/azure-sdk-for-java/tree/main/sdk/servicebus/azure-messaging-servicebus/src/samples/java/com/azure/messaging/servicebus

**Describe the solution you'd like**
Sample code available that demonstrates the use of Topics with Named Sessions(Producer and Receiver) for Java Spring Boot applications. 

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Information Checklist**
Kindly make sure that you have added all the following information above and checkoff the required fields otherwise we will treat the issuer as an incomplete report
- [x] Description Added
- [x] Expected solution specified

**Comment by Netyyyy** [comment]
Hi, @madossan01 , thanks for reaching out.
We provided some related samples in [Azure-Samples/azure-spring-boot-samples](https://github.com/Azure-Samples/azure-spring-boot-samples/tree/spring-cloud-azure_v4.3.0/servicebus)

We also provided starters that may help you quickly use the Service Bus with Spring Boot, such as `spring-cloud-azure-starter-servicebus`, `spring-cloud-azure-starter-integration-servicebus` and `spring-cloud-azure-stream-binder-servicebus`, click https://microsoft.github.io/spring-cloud-azure/current/reference/html/index.html#getting-started to get more information.

**Comment by madossan01** [comment]
> Hi, @madossan01 , thanks for reaching out. We provided some related samples in [Azure-Samples/azure-spring-boot-samples](https://github.com/Azure-Samples/azure-spring-boot-samples/tree/spring-cloud-azure_v4.3.0/servicebus)
> 
> We also provided starters that may help you quickly use the Service Bus with Spring Boot, such as `spring-cloud-azure-starter-servicebus`, `spring-cloud-azure-starter-integration-servicebus` and `spring-cloud-azure-stream-binder-servicebus`, click https://microsoft.github.io/spring-cloud-azure/current/reference/html/index.html#getting-started to get more information.

Thanks for sharing the links. Sorry, my bad do not have mentioned that in the issue, we indeed used the starters and they saved considerable time. Even though the samples are interesting starting points, our scenario required the use of Topics and named Sessions with Services Bus SDK for Java. Most samples are using JMS only or they target Queue instead of Topics.  Learning how to better use the Topics and Sessions and how to make them work properly took us some time on try and fix loops.  As the use of Topics with Sessions may represent a recurrent scenario, a sample with the best practices may save some precious time from Java developers and improve final code quality.
