### ISSUE TITLE
[FEATURE REQ] Improve the sample that allows to return an Object for Receiver and Error Handler with ServiceBusProcessorClient

### ISSUE THREAD

**Issue by madossan01** [Azure/azure-sdk-for-java#29764]
**Is your feature request related to a problem? Please describe.**
The sample in the ServiceBusProcessorClient Class definition does not specify if the ProcessorClient only works with Consumers and it provides a basic example on how to create a processor. 
 
The ServiceBusProcessorClient documentation does not point to valid samples on how to implement the client other than just the snippet that uses Java Consumers.

- There is a sample found on GitHub but it is not being referenced in the official ServiceBusProcessorClient documentation: https://github.com/Azure/azure-sdk-for-java/blob/main/sdk/servicebus/azure-messaging-servicebus/src/samples/java/com/azure/messaging/servicebus/ServiceBusProcessorSample.java
- The sample does use external non consumer methods to process messages and handle errors 
- Also, the sample uses getMessageId to retrieve a Session ID [on line 79](https://github.com/Azure/azure-sdk-for-java/blob/main/sdk/servicebus/azure-messaging-servicebus/src/samples/java/com/azure/messaging/servicebus/ServiceBusProcessorSample.java#L79). Instead, it should use the getSessionId method.
- However, the [documentation for ProcessorClient](https://github.com/Azure/azure-sdk-for-java/tree/main/sdk/servicebus/azure-messaging-servicebus) located at the root folder "azure-messaging-services" in the same GitHub repo still uses the Consumer approach 
- The documentation on how to use the azure-messaging-servicebus package is also either not finished or misleading as, [per the GitHub documentation](https://github.com/Azure/azure-sdk-for-java/tree/main/sdk/servicebus/azure-messaging-servicebus#include-the-package), the developer should only add the BOM file and the direct dependency in order to use the SDK:
<dependencyManagement> 
    <dependencies> 
        <dependency> 
            <groupId>com.azure</groupId> 
            <artifactId>azure-sdk-bom</artifactId> 
            <version>{bom_version_to_target}</version> 
            <type>pom</type> 
            <scope>import</scope> 
        </dependency> 
    </dependencies> 
</dependencyManagement> 
 <dependencies> 
      <dependency> 
            <groupId>com.azure</groupId> 
            <artifactId>azure-messaging-servicebus</artifactId> 
      </dependency> 
</dependencies>

But by adding the BOM and dependency mentioned above there are errors at the POM file. It complains about a failure to read multiple artifacts, as shown by the image attached.
o	azure-core 
o	azure-core-amqp 
o	azure-core-http-netty 
o	Etc
![image](https://user-images.githubusercontent.com/60100278/176967961-92ceede7-2389-40bb-9f8f-e47186b47184.png)

**Describe the solution you'd like**
Please kindly consider to:
•	Update the official documentation with the cases and sample mentioned above
•	Document the dependencies needed for the azure-messaging-servicebus to work properly 
•	Either document both ways to receive messages and handle errors or stick with one approach: External methods or Java Consumers

**Describe alternatives you've considered**
Spike using the current sample and finding the alternative ways to have session working.

**Additional context**
N/A, as they were added to the description.

**Information Checklist**
Kindly make sure that you have added all the following information above and checkoff the required fields otherwise we will treat the issuer as an incomplete report
- [x] Description Added
- [x] Expected solution specified

**Comment by saragluna** [comment]
Seems like not a Spring library's issue, @Azure/azsdk-sb-java could you take a look at this?
