### ISSUE TITLE
[FEATURE REQ] Use common framework for all Spring Cloud Azure credential-free plugins/callback handlers 

### ISSUE THREAD

**Issue by yiliuTo** [Azure/azure-sdk-for-java#29778]
## Context
For the credential-free connection support of Spring Cloud Azure, we will deliver multiple feature implement for different third party services, like Kafka, MySQL, PostgreSQL and so on. We should abstract a common framework for all these different implementations for different services.

## Goal
Use common framework for all Spring Cloud Azure credential-free plugins/callback handlers

**Comment by saragluna** [comment]
https://github.com/stliu/azure-identity-extension/pull/1

**Comment by backwind1233** [comment]
Closing this, refer to [azure-identity-providers-core](https://github.com/Azure/azure-sdk-for-java/tree/release/spring-cloud-azure-4.4.0-beta.1/sdk/jdbc/azure-identity-providers-core) to check the common framework.
