### ISSUE TITLE
[FEATURE REQ] Support token refresh for MySQL/PostgreSQL credential-free JDBC plugin

### ISSUE THREAD

**Issue by yiliuTo** [Azure/azure-sdk-for-java#29776]
## Context
For the Spring Cloud Azure credential-free JDBC plugin, we should handle the case that if the application is long running, what will happen if the token expires 

## Goal
Support token refresh after expiration.

**Comment by backwind1233** [comment]
Closing this, refer to https://github.com/Azure/azure-sdk-for-java/pull/30740
