### ISSUE TITLE
[FEATURE REQ] Make sure credential-free JDBC plugin is compatible with multiple MySQL/PostgreSQL versions

### ISSUE THREAD

**Issue by yiliuTo** [Azure/azure-sdk-for-java#29775]
## Context
For the credential-free JDBC plugin, we should test its compatability with multiple MySQL/PostgreSQL versions.

## Goal
Compare the compatability and delivery the compatability report wth different MySQL/PostgreSQL versions

**Comment by backwind1233** [comment]
Credential-free JDBC plugin is not compatible with spring boot 2.5.x for PostgreSQL.
