### ISSUE TITLE
[FEATURE REQ] Make sure passwordless JDBC plugin can share the same token for sessions in the connection pool.

### ISSUE THREAD

**Issue by yiliuTo** [Azure/azure-sdk-for-java#29777]
## Context
For the Spring Cloud Azure passwordless JDBC plugin, we should make sure that when there are multiple sessions in the database connection pool, they can share the same access token instead of acquiring one for each session.

## Goal
Make sure passwordless JDBC plugin can share the same token for sessions in the connection pool.

**Comment by yiliuTo** [comment]
After the investigation about the connection pool implementation of Hikari together with the concrete database implemention of connection abstraction, the supported configuration of HikariPool doesn't provide extension points for custom objects to share the token, and the same for the connection abstraction of database drivers.
Thus I would like to close this issue.

**Comment by yiliuTo** [comment]
Reopen this issue since this might be a blocker for the usage of Managed Identities

**Comment by backwind1233** [comment]
@yiliuTo I am renaming the terminology in this issue from credential free to passwordless.

**Comment by backwind1233** [comment]
Closing this, refer to https://github.com/Azure/azure-sdk-for-java/pull/30740
