### ISSUE TITLE
[FEATURE REQ] Enable Azure Identity for Spring Cloud Azure PostgreSQL support

### ISSUE THREAD

**Issue by yiliuTo** [Azure/azure-sdk-for-java#29780]
### Context

Currently PostgreSQL developers can connect to Azure Database for PostgreSQL with database password. We aim to provide all Azure Identity based credentital types and the associated configuration options to Azure Database for PostgreSQL deverlopers.

**Comment by backwind1233** [comment]
Closing this, refer to https://github.com/Azure/azure-sdk-for-java/pull/30740
