### ISSUE TITLE
[FEATURE REQ] Update quick-start doc of Spring Data JDBC with PostgreSQL to include passwordless connection

### ISSUE THREAD

**Issue by yiliuTo** [Azure/azure-sdk-for-java#29783]
### Context

With Managed Identities OAuth feature enabled in #29780, we should update our quickstart doc of [Spring quickstart PostgreSQL JDBC] to include the passwordless connection method. 

There's a template worked out by Alex can be found here:
- https://github.com/MicrosoftDocs/azure-docs-pr/pull/203348#issuecomment-1205727432
- https://github.com/MicrosoftDocs/azure-docs-pr/pull/203348#issuecomment-1203381358

We should demo two connection methods in this doc, one using credential-free connections and one using username/password, using contextual tabs to distinguish them. We should make the passwordless tab as the default/recommended.

### Goal
Update the quick-start doc to include the passwordless part. 

[Spring quickstart PostgreSQL JDBC]: https://docs.microsoft.com/en-us/azure/developer/java/spring-framework/configure-spring-data-jdbc-with-azure-postgresql

**Comment by Netyyyy** [comment]
Close this issue since the pr has been closed and the content has merged.
