### ISSUE TITLE
[Epic] Support Azure Identity for PostgreSQL

### ISSUE THREAD

**Issue by yiliuTo** [Azure/azure-sdk-for-java#29785]
This is the epic to track all issues about Azure Identity support for PostgreSQL.

### Context
Currently PostgreSQL developers can use Azure Database for PostgreSQL in the same way as how they use PostgreSQL. For the authentication part, native PostgreSQL developers can use database password to authenticate to PostgreSQLserver.

We plan to support all Azure Identity based credentials for Spring Cloud Azure PostgreSQL support, which includes all Azure Identity supported credential types and configuration options.

With Azure Identity-based credentials being supported, we can also achieve credential-free connection as well, which based on the `ManagedIdentityCredential` in Azure Identity. It can enable developers to use user-assigned/system-assigend managed identities in various Azure hosting environments to establish connection with Azure Database for PostgreSQL via various spring ecosystems for PostgreSQL.

### Deliveries
The delivery resources include:

#### Docs

- [x] #29781
- [x] #29782
- [x] #29783
#### Others
- [x] #29780 
- [x] #29222
- [x] #29775
- [x] #29228
- [x] #29776
- [x] #29777

**Comment by vtapadia** [comment]
Looking forward to this epic..... 
I hope you would also suggest a recommended approach on how to setup postgreSQL

An example article that I saw on the internet was
https://www.azureblue.io/how-to-manage-psql-db-permissions-with-aad-groups/
However, without the proper support of setting/managing connections, its not of much use.

**Comment by yiliuTo** [comment]
Thanks for reaching us @vtapadia 

> I hope you would also suggest a recommended approach on how to setup postgreSQL

yes we will also introduce such content in our doc resources to help developers leverage Azure identities with PostgreSQL more easily, like how to make Azure Database for PostgreSQL integrated with Azure AD, how to assign necessary permissions and so on.

> An example article that I saw on the internet was
> https://www.azureblue.io/how-to-manage-psql-db-permissions-with-aad-groups/
> However, without the proper support of setting/managing connections, its not of much use.

here do you mean you expect there to be guidance about the user case of integrating Azure Database for PostgreSQL with Azure AD groups?

**Comment by vtapadia** [comment]
Hi @yiliuTo 
Thanks for the response.

> > An example article that I saw on the internet was
> > https://www.azureblue.io/how-to-manage-psql-db-permissions-with-aad-groups/
> > However, without the proper support of setting/managing connections, its not of much use.
> 
> here do you mean you expect there to be guidance about the user case of integrating Azure Database for PostgreSQL with Azure AD groups?

Yes, I was hoping if there are some guidance on how to setup database. If every team decides to use it differently, it would be hard to manage and come up with a somewhat standard way of setting up groups and users.
I would love to use that as an Input to our internal DBA team to validate and provide feedback back.

**Comment by vtapadia** [comment]
Are there any expected timelines for this feature to be available. Earlier it was 2022-08, now it is 09.... so just want to have a bit of idea on when this will be available.

Also, I hope this will be available for Flexible servers as well. Can you confirm that also?

**Comment by saragluna** [comment]
> Are there any expected timelines for this feature to be available. Earlier it was 2022-08, now it is 09.... so just want to have a bit of idea on when this will be available.
> 
> Also, I hope this will be available for Flexible servers as well. Can you confirm that also?

Hi @vtapadia, thanks for reaching out. We are trying to release the first beta version for this feature this or next week. AFAIK, the AAD authentication with flexible servers on the server side hasn't been GAed yet, so with the first beta, you probably won't use it with flexible servers. But we definitely will support this feature with flexible servers.

**Comment by saragluna** [comment]
The first beta version 4.5.0-beta.1 has been released to maven central, closing this issue now. Will update the docs link later.

**Comment by backwind1233** [comment]
> > Are there any expected timelines for this feature to be available. Earlier it was 2022-08, now it is 09.... so just want to have a bit of idea on when this will be available.
> > Also, I hope this will be available for Flexible servers as well. Can you confirm that also?
> 
> Hi @vtapadia, thanks for reaching out. We are trying to release the first beta version for this feature this or next week. AFAIK, the AAD authentication with flexible servers on the server side hasn't been GAed yet, so with the first beta, you probably won't use it with flexible servers. But we definitely will support this feature with flexible servers.

Hi @vtapadia [spring-cloud-azure-starter-jdbc-postgresql/4.5.0-beta.1](https://repo1.maven.org/maven2/com/azure/spring/spring-cloud-azure-starter-jdbc-postgresql/4.5.0-beta.1/) has been released on 2022-09-23 and it supports flexible server as well.

**Comment by vtapadia** [comment]
Hi @backwind1233 I tried the beta but I am unable to set this up correctly, Have raised a bug https://github.com/Azure/azure-sdk-for-java/issues/31850 for tracking the issue. 
Hope you can guide on what am I missing.
