### ISSUE TITLE
[QUERY] Does CosmosDB As Table API support Spring data? 

### ISSUE THREAD

**Issue by numirov** [Azure/azure-sdk-for-java#29784]
**Query/Question**
Does cosmosdb as table api(serverless mode) work through spring data? All the tutorials I have found are using containers and talking about request units which are not applicable in table api case as far as I know. 

I have only found this tutorial https://docs.microsoft.com/en-us/azure/cosmos-db/table/create-table-java which talks about interacting with db manually. And it uses blocking client, but I found **TableAsyncClient** for reactive interaction, probably should be mentioned in the doco?

In addition to that do we need worry about health check to cosmosdb as table api(serverless mode)? As I could find anything in the code base that mentions health/status

***Why is this not a Bug or a feature Request?***
A clear explanation of why is this not a bug or a feature request?

**Setup (please complete the following information if applicable):**
 - OS: na
 - IDE: na
 - Library/Libraries: na
 
 **Information Checklist**
 Kindly make sure that you have added all the following information above and checkoff the required fields otherwise we will treat the issuer as an incomplete report
- [x] Query Added
- [na] Setup information Added

**Comment by kushagraThapar** [comment]
@numirov  - as far as I know, it is not supported. Spring data is only supported through SQL API.
