### ISSUE TITLE
Key Vault Secrets Samples  improvement

### ISSUE THREAD

**Issue by hongli750210** [Azure/azure-sdk-for-java#29795]
**Issue Description:**
Using a string like `"<your-key-vault-url>"` as a parameter to an Azure service is not convenient for automated test, detail [Code Link](https://github.com/Azure/azure-sdk-for-java/blob/main/sdk/keyvault/azure-security-keyvault-secrets/src/samples/java/com/azure/security/keyvault/secrets/ReadmeSamples.java)
![image](https://user-images.githubusercontent.com/74638143/177477145-1aeeaf91-62d2-48af-8c6c-40dd8a15dd26.png)

**Suggestion:**
Get the parameters of Azure Service from environment variables. For examples:
- Update `"<your-key-vault-url>"` to `CONFIGURATION.get("AZURE_KEYVAULT_URI")`

@joshfree, @heaths, @pallavit and @vcolin7 for notification.

**Comment by joshfree** [comment]
@vcolin7 PTAL

**Comment by heaths** [comment]
@hongli750210 why are the sample snippets being used in automated tests? At least for some languages, snippets are extracted from live tests that already run nightly. The values here are merely placeholders for users to replace. If we use real resource names, I fear it will confuse customers who just copy/paste the code.

**Comment by v-xuto** [comment]
@heaths I agree with your idea. We do this just to facilitate automated testing, we will not be making changes for these samples at this time. We will close this issue.

**Comment by heaths** [comment]
> we will not be making changes for these samples at this time. We will close this issue.

Let's talk about this more offline. We already have a very robust, language-agnostic method of testing that might be good to incorporate into your plans. I'd be happy to walk you through it. /cc @weshaggard @maririos
