### ISSUE TITLE
[QUERY] How to programmatically revoke a user delegation key?

### ISSUE THREAD

**Issue by jonasatmonday** [Azure/azure-sdk-for-java#29813]
**Query/Question**
How can I revoke a user delegation key with azure-identity/azure-blob-storage?

I create my user delegation key programmatically with `BlobServiceClient#getUserDelegationKey(OffsetDateTime start, OffsetDateTime expiry)` and that works like a charm.

That user delegation key is then managed by a service (a Spring bean) to issue SAS tokens. When the service Spring bean is destroyed, I want to revoke the user delegation key.

 I only found [this](https://docs.microsoft.com/en-us/powershell/module/az.storage/revoke-azstorageaccountuserdelegationkeys?view=azps-8.1.0) powershell documentation for revoking a key but nothing with the SDK.

***Why is this not a Bug or a feature Request?***
I did not find possibility to revoke the user delegation key with the Java SDK. If it is not possible yet, I will issue a feature request.

**Setup (please complete the following information if applicable):**
 - OS: MacOs 12.4 (21F79)
 - IDE: IntelliJ IDEA 2022.1.3
 - Library/Libraries:
    - com.azure:azure-storage-blob:12.17.1,
    - com.azure:azure-core:1.29.1
    - com.azure:azure-identity:1.5.2

 **Information Checklist**
 Kindly make sure that you have added all the following information above and checkoff the required fields otherwise we will treat the issuer as an incomplete report
- [x] Query Added
- [x] Setup information Added

**Comment by rickle-msft** [comment]
The Storage service does not currently have a way of revoking user delegation keys, so at least the Storage sdk cannot yet add this feature. A possible alternative would be to set ACLs on your container. You can then associate sas tokens with the ACLs and remove the ACL when you want to invalidate the sas token. It's not quite the same and has some limitations, but it may be worth exploring.

**Comment by jonasatmonday** [comment]
Hello @rickle-msft,
thanks a lot for your feedback! I will probably create a feature request then. We will look into your suggestion!
Best regards,
Jonas

**Comment by XiaofeiCao** [comment]
Hi @jonasatmonday 

You can revoke user delegate key from management plane api:
https://github.com/Azure/azure-sdk-for-java/blob/c343e665aa78ab784585531e4ddd958e5c843c85/sdk/resourcemanager/azure-resourcemanager-storage/src/main/java/com/azure/resourcemanager/storage/fluent/StorageAccountsClient.java#L1391

Sample code snippet:
https://github.com/Azure/azure-sdk-for-java/blob/c343e665aa78ab784585531e4ddd958e5c843c85/sdk/resourcemanager/azure-resourcemanager/src/samples/java/com/azure/resourcemanager/storage/generated/StorageAccountsRevokeUserDelegationKeysSamples.java#L19-L26

It will take effect in a short time, 1 minute or so.

**Comment by jonasatmonday** [comment]
Hello @XiaofeiCao,
thanks for your input!
The problem with that API operation is that I would revoke all User Delegation. Keys for that account/resource group and I would like to only revoke the user delegation key created and used by my application to not interfere with other user delegation keys that may be in place for that account.

Best regards,
Jonas

**Comment by XiaofeiCao** [comment]
Hi @jonasatmonday , from what I learnt from service team, there's only one User Delegation Key for a storage account at one given time. So the keys you get from `BlobServiceClient#getUserDelegationKey(OffsetDateTime start, OffsetDateTime expiry)` are all derived from the same root key stored in server. When you revoke user delegation key, the root key is revoked and a new key is generated, invalidating all previous derived keys.

Also, ACL mentioned by @rickle-msft may only support specify kinds of storage accounts (ones that support Data Lake Gen2, I'm not very familiar with those..).

You may try "changing or removing RBAC role assignments for the security principal that's used to create the SAS”. (However, all user delegation SAS from this security principal will be impacted)
See details in : [https://docs.microsoft.com/en-us/rest/api/storageservices/create-user-delegation-sas#revoke-a-user-delegation-sas](https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fdocs.microsoft.com%2Fen-us%2Frest%2Fapi%2Fstorageservices%2Fcreate-user-delegation-sas%23revoke-a-user-delegation-sas&data=05%7C01%7Cxiaofeicao%40microsoft.com%7Cd9ed86ebee954ec3c90f08da6860ae17%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C637937061690095785%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=djK0%2B4C6hiQO9kR%2Fpu%2FDKF%2BtAUwWcCzGKPMK1rTLRvk%3D&reserved=0)

**Comment by jonasatmonday** [comment]
Hello @XiaofeiCao,
thanks! I had no idea that there was only one user delegation key for a storage account at a time. I will discuss that finding with our Azure guys.

Best regards,
Jonas

**Comment by jonasatmonday** [comment]
Hey there. I talked about this issue with our internal Azure guys and they are quite sure that there may be multiple user delegation keys per storage account so revoking all user delegation keys is not an option for us. We now mitigate this issue by only issuing user delegation keys with shorter validity so that we only leave an user delegation key behind that expires quite soon when shutting down the application.

If you guys see a chance, that the feature to revoke a single user delegation key may be possible in the future, I would love to keep this feature request open.

Best regards,
Jonas
