### ISSUE TITLE
[BUG] Unable to obtain session locks - negative lock duration

### ISSUE THREAD

**Issue by joshuapetryk** [Azure/azure-sdk-for-java#29825]
**Describe the bug**
I am implementing ServiceBusProcessorClient to process a session enabled Subscription but am running into an issue where lock durations appear to be negative and the processor is stuck in an infinite loop trying to renew / acquire a session lock.

***Exception or Stack Trace***

> 2022-07-06 17:32:26.788  INFO 9252 --- [     parallel-2] c.a.m.servicebus.LockRenewalOperation    : {"az.sdk.message":"Starting lock renewal.","isSession":true,"lockToken":"0012335373970_2022-07-06T00:26:52"}
> 2022-07-06 17:32:26.788  INFO 9252 --- [     parallel-7] c.a.m.servicebus.LockRenewalOperation    : {"az.sdk.message":"Starting lock renewal.","isSession":true,"lockToken":"0017688353276_2022-07-05T00:00:00"}
> 2022-07-06 17:32:26.812  INFO 9252 --- [ctor-executor-5] c.a.m.servicebus.LockRenewalOperation    : {"az.sdk.message":"Starting lock renewal.","isSession":true,"lockToken":"0012335373971_2022-07-06T00:26:53","nextExpiration":"2022-07-06T22:31:28.506Z","next":"PT-58.306S"}
> 2022-07-06 17:32:26.812  INFO 9252 --- [ctor-executor-5] c.a.m.servicebus.LockRenewalOperation    : {"az.sdk.message":"Duration was less than 400ms.","isSession":true,"lockToken":"0012335373971_2022-07-06T00:26:53","lockedUntil":"2022-07-06T22:31:28.506Z"}
> 2022-07-06 17:32:26.812  INFO 9252 --- [    parallel-10] c.a.m.servicebus.LockRenewalOperation    : {"az.sdk.message":"Starting lock renewal.","isSession":true,"lockToken":"0012335373971_2022-07-06T00:26:53"}
> 2022-07-06 17:32:26.835  INFO 9252 --- [ctor-executor-2] c.a.m.servicebus.LockRenewalOperation    : {"az.sdk.message":"Starting lock renewal.","isSession":true,"lockToken":"0272300027093_2022-07-05T00:00:00","nextExpiration":"2022-07-06T22:31:28.537Z","next":"PT-58.298S"}
> 2022-07-06 17:32:26.835  INFO 9252 --- [ctor-executor-1] c.a.m.servicebus.LockRenewalOperation    : {"az.sdk.message":"Starting lock renewal.","isSession":true,"lockToken":"0272300027094_2022-07-05T00:00:00","nextExpiration":"2022-07-06T22:31:28.537Z","next":"PT-58.298S"}
> 2022-07-06 17:32:26.835  INFO 9252 --- [ctor-executor-3] c.a.m.servicebus.LockRenewalOperation    : {"az.sdk.message":"Starting lock renewal.","isSession":true,"lockToken":"0012335373970_2022-07-06T00:26:52","nextExpiration":"2022-07-06T22:31:28.537Z","next":"PT-58.298S"}
> 2022-07-06 17:32:26.835  INFO 9252 --- [ctor-executor-2] c.a.m.servicebus.LockRenewalOperation    : {"az.sdk.message":"Duration was less than 400ms.","isSession":true,"lockToken":"0272300027093_2022-07-05T00:00:00","lockedUntil":"2022-07-06T22:31:28.537Z"}
> 2022-07-06 17:32:26.835  INFO 9252 --- [ctor-executor-4] c.a.m.servicebus.LockRenewalOperation    : {"az.sdk.message":"Starting lock renewal.","isSession":true,"lockToken":"0017688353276_2022-07-05T00:00:00","nextExpiration":"2022-07-06T22:31:28.537Z","next":"PT-58.298S"}
> 2022-07-06 17:32:26.835  INFO 9252 --- [ctor-executor-6] c.a.m.servicebus.LockRenewalOperation    : {"az.sdk.message":"Starting lock renewal.","isSession":true,"lockToken":"0272300027095_2022-07-05T00:00:00","nextExpiration":"2022-07-06T22:31:28.537Z","next":"PT-58.298S"}
> 2022-07-06 17:32:26.835  INFO 9252 --- [ctor-executor-1] c.a.m.servicebus.LockRenewalOperation    : {"az.sdk.message":"Duration was less than 400ms.","isSession":true,"lockToken":"0272300027094_2022-07-05T00:00:00","lockedUntil":"2022-07-06T22:31:28.537Z"}
> 2022-07-06 17:32:26.835  INFO 9252 --- [ctor-executor-3] c.a.m.servicebus.LockRenewalOperation    : {"az.sdk.message":"Duration was less than 400ms.","isSession":true,"lockToken":"0012335373970_2022-07-06T00:26:52","lockedUntil":"2022-07-06T22:31:28.537Z"}
> 2022-07-06 17:32:26.835  INFO 9252 --- [ctor-executor-4] c.a.m.servicebus.LockRenewalOperation    : {"az.sdk.message":"Duration was less than 400ms.","isSession":true,"lockToken":"0017688353276_2022-07-05T00:00:00","lockedUntil":"2022-07-06T22:31:28.537Z"}
> 2022-07-06 17:32:26.835  INFO 9252 --- [ctor-executor-6] c.a.m.servicebus.LockRenewalOperation    : {"az.sdk.message":"Duration was less than 400ms.","isSession":true,"lockToken":"0272300027095_2022-07-05T00:00:00","lockedUntil":"2022-07-06T22:31:28.537Z"}
> 2022-07-06 17:32:26.835  INFO 9252 --- [     parallel-1] c.a.m.servicebus.LockRenewalOperation    : {"az.sdk.message":"Starting lock renewal.","isSession":true,"lockToken":"0272300027094_2022-07-05T00:00:00"}
> 2022-07-06 17:32:26.835  INFO 9252 --- [    parallel-12] c.a.m.servicebus.LockRenewalOperation    : {"az.sdk.message":"Starting lock renewal.","isSession":true,"lockToken":"0272300027093_2022-07-05T00:00:00"}
> 2022-07-06 17:32:26.835  INFO 9252 --- [     parallel-6] c.a.m.servicebus.LockRenewalOperation    : {"az.sdk.message":"Starting lock renewal.","isSession":true,"lockToken":"0012335373970_2022-07-06T00:26:52"}
> 2022-07-06 17:32:26.835  INFO 9252 --- [     parallel-5] c.a.m.servicebus.LockRenewalOperation    : {"az.sdk.message":"Starting lock renewal.","isSession":true,"lockToken":"0017688353276_2022-07-05T00:00:00"}
> 2022-07-06 17:32:26.835  INFO 9252 --- [     parallel-4] c.a.m.servicebus.LockRenewalOperation    : {"az.sdk.message":"Starting lock renewal.","isSession":true,"lockToken":"0272300027095_2022-07-05T00:00:00"}
> 2022-07-06 17:32:26.852  INFO 9252 --- [ctor-executor-5] c.a.m.servicebus.LockRenewalOperation    : {"az.sdk.message":"Starting lock renewal.","isSession":true,"lockToken":"0012335373971_2022-07-06T00:26:53","nextExpiration":"2022-07-06T22:31:28.553Z","next":"PT-58.299S"}
> 2022-07-06 17:32:26.852  INFO 9252 --- [ctor-executor-5] c.a.m.servicebus.LockRenewalOperation    : {"az.sdk.message":"Duration was less than 400ms.","isSession":true,"lockToken":"0012335373971_2022-07-06T00:26:53","lockedUntil":"2022-07-06T22:31:28.553Z"}
> 2022-07-06 17:32:26.852  INFO 9252 --- [    parallel-10] c.a.m.servicebus.LockRenewalOperation    : {"az.sdk.message":"Starting lock renewal.","isSession":true,"lockToken":"0012335373971_2022-07-06T00:26:53"}
> 2022-07-06 17:32:26.876  INFO 9252 --- [ctor-executor-3] c.a.m.servicebus.LockRenewalOperation    : {"az.sdk.message":"Starting lock renewal.","isSession":true,"lockToken":"0012335373970_2022-07-06T00:26:52","nextExpiration":"2022-07-06T22:31:28.584Z","next":"PT-58.292S"}
> 2022-07-06 17:32:26.876  INFO 9252 --- [ctor-executor-3] c.a.m.servicebus.LockRenewalOperation    : {"az.sdk.message":"Duration was less than 400ms.","isSession":true,"lockToken":"0012335373970_2022-07-06T00:26:52","lockedUntil":"2022-07-06T22:31:28.584Z"}
> 2022-07-06 17:32:26.876  INFO 9252 --- [    parallel-12] c.a.m.servicebus.LockRenewalOperation    : {"az.sdk.message":"Starting lock renewal.","isSession":true,"lockToken":"0012335373970_2022-07-06T00:26:52"}
> 2022-07-06 17:32:26.879  INFO 9252 --- [ctor-executor-4] c.a.m.servicebus.LockRenewalOperation    : {"az.sdk.message":"Starting lock renewal.","isSession":true,"lockToken":"0017688353276_2022-07-05T00:00:00","nextExpiration":"2022-07-06T22:31:28.584Z","next":"PT-58.295S"}
> 2022-07-06 17:32:26.879  INFO 9252 --- [ctor-executor-4] c.a.m.servicebus.LockRenewalOperation    : {"az.sdk.message":"Duration was less than 400ms.","isSession":true,"lockToken":"0017688353276_2022-07-05T00:00:00","lockedUntil":"2022-07-06T22:31:28.584Z"}
> 2022-07-06 17:32:26.879  INFO 9252 --- [     parallel-6] c.a.m.servicebus.LockRenewalOperation    : {"az.sdk.message":"Starting lock renewal.","isSession":true,"lockToken":"0017688353276_2022-07-05T00:00:00"}
> 2022-07-06 17:32:26.882  INFO 9252 --- [ctor-executor-2] c.a.m.servicebus.LockRenewalOperation    : {"az.sdk.message":"Starting lock renewal.","isSession":true,"lockToken":"0272300027093_2022-07-05T00:00:00","nextExpiration":"2022-07-06T22:31:28.584Z","next":"PT-58.298S"}
> 2022-07-06 17:32:26.882  INFO 9252 --- [ctor-executor-6] c.a.m.servicebus.LockRenewalOperation    : {"az.sdk.message":"Starting lock renewal.","isSession":true,"lockToken":"0272300027095_2022-07-05T00:00:00","nextExpiration":"2022-07-06T22:31:28.584Z","next":"PT-58.298S"}
> 2022-07-06 17:32:26.882  INFO 9252 --- [ctor-executor-2] c.a.m.servicebus.LockRenewalOperation    : {"az.sdk.message":"Duration was less than 400ms.","isSession":true,"lockToken":"0272300027093_2022-07-05T00:00:00","lockedUntil":"2022-07-06T22:31:28.584Z"}
> 2022-07-06 17:32:26.882  INFO 9252 --- [ctor-executor-1] c.a.m.servicebus.LockRenewalOperation    : {"az.sdk.message":"Starting lock renewal.","isSession":true,"lockToken":"0272300027094_2022-07-05T00:00:00","nextExpiration":"2022-07-06T22:31:28.584Z","next":"PT-58.298S"}
> 2022-07-06 17:32:26.882  INFO 9252 --- [ctor-executor-6] c.a.m.servicebus.LockRenewalOperation    : {"az.sdk.message":"Duration was less than 400ms.","isSession":true,"lockToken":"0272300027095_2022-07-05T00:00:00","lockedUntil":"2022-07-06T22:31:28.584Z"}
> 2022-07-06 17:32:26.882  INFO 9252 --- [ctor-executor-1] c.a.m.servicebus.LockRenewalOperation    : {"az.sdk.message":"Duration was less than 400ms.","isSession":true,"lockToken":"0272300027094_2022-07-05T00:00:00","lockedUntil":"2022-07-06T22:31:28.584Z"}
> 2022-07-06 17:32:26.882  INFO 9252 --- [     parallel-4] c.a.m.servicebus.LockRenewalOperation    : {"az.sdk.message":"Starting lock renewal.","isSession":true,"lockToken":"0272300027093_2022-07-05T00:00:00"}
> 2022-07-06 17:32:26.882  INFO 9252 --- [     parallel-3] c.a.m.servicebus.LockRenewalOperation    : {"az.sdk.message":"Starting lock renewal.","isSession":true,"lockToken":"0272300027095_2022-07-05T00:00:00"}
> 2022-07-06 17:32:26.882  INFO 9252 --- [     parallel-2] c.a.m.servicebus.LockRenewalOperation    : {"az.sdk.message":"Starting lock renewal.","isSession":true,"lockToken":"0272300027094_2022-07-05T00:00:00"}
> 2022-07-06 17:32:26.892  INFO 9252 --- [ctor-executor-5] c.a.m.servicebus.LockRenewalOperation    : {"az.sdk.message":"Starting lock renewal.","isSession":true,"lockToken":"0012335373971_2022-07-06T00:26:53","nextExpiration":"2022-07-06T22:31:28.600Z","next":"PT-58.292S"}
> 2022-07-06 17:32:26.892  INFO 9252 --- [ctor-executor-5] c.a.m.servicebus.LockRenewalOperation    : {"az.sdk.message":"Duration was less than 400ms.","isSession":true,"lockToken":"0012335373971_2022-07-06T00:26:53","lockedUntil":"2022-07-06T22:31:28.600Z"}
> 2022-07-06 17:32:26.892  INFO 9252 --- [    parallel-10] c.a.m.servicebus.LockRenewalOperation    : {"az.sdk.message":"Starting lock renewal.","isSession":true,"lockToken":"0012335373971_2022-07-06T00:26:53"}
> 2022-07-06 17:32:26.924  INFO 9252 --- [ctor-executor-3] c.a.m.servicebus.LockRenewalOperation    : {"az.sdk.message":"Starting lock renewal.","isSession":true,"lockToken":"0012335373970_2022-07-06T00:26:52","nextExpiration":"2022-07-06T22:31:28.616Z","next":"PT-58.308S"}
> 2022-07-06 17:32:26.924  INFO 9252 --- [ctor-executor-4] c.a.m.servicebus.LockRenewalOperation    : {"az.sdk.message":"Starting lock renewal.","isSession":true,"lockToken":"0017688353276_2022-07-05T00:00:00","nextExpiration":"2022-07-06T22:31:28.632Z","next":"PT-58.292S"}
> 2022-07-06 17:32:26.925  INFO 9252 --- [ctor-executor-3] c.a.m.servicebus.LockRenewalOperation    : {"az.sdk.message":"Duration was less than 400ms.","isSession":true,"lockToken":"0012335373970_2022-07-06T00:26:52","lockedUntil":"2022-07-06T22:31:28.616Z"}
> 2022-07-06 17:32:26.925  INFO 9252 --- [ctor-executor-4] c.a.m.servicebus.LockRenewalOperation    : {"az.sdk.message":"Duration was less than 400ms.","isSession":true,"lockToken":"0017688353276_2022-07-05T00:00:00","lockedUntil":"2022-07-06T22:31:28.632Z"}
> 2022-07-06 17:32:26.925  INFO 9252 --- [    parallel-12] c.a.m.servicebus.LockRenewalOperation    : {"az.sdk.message":"Starting lock renewal.","isSession":true,"lockToken":"0017688353276_2022-07-05T00:00:00"}
> 2022-07-06 17:32:26.925  INFO 9252 --- [     parallel-1] c.a.m.servicebus.LockRenewalOperation    : {"az.sdk.message":"Starting lock renewal.","isSession":true,"lockToken":"0012335373970_2022-07-06T00:26:52"}

**To Reproduce**

- Add messages with session ids to a topic/subscription
- Start the processor
- Abruptly terminate the processor (in my case it was ending debugger in IntelliJ)
- Re start the processor
- Observe the above log message
- Notice negative duration values: **"next":"PT-58.298S"**

***Code Snippet***
```java
ServiceBusProcessorClient processor = new ServiceBusClientBuilder()
                .connectionString("snipped")
                // Session processor will sit idle for timeout before moving to next session
                //.retryOptions(new AmqpRetryOptions().setTryTimeout(Duration.ofSeconds(2L)))
                .sessionProcessor()
                //.processor()
                .topicName("vcr-asa")
                .subscriptionName("sessionpoc")
                //.receiveMode(ServiceBusReceiveMode.PEEK_LOCK)
                .processMessage(new MessageProcessor(Thread.currentThread().getName(), Log, writer))
                .processError(this::processError)
                .maxConcurrentCalls(1)
                .maxConcurrentSessions(1)
                .buildProcessorClient();
```

**Expected behavior**
- I expect session locks to be released even after termination. I do not expect negative session lock durations.

**Screenshots**

**Setup (please complete the following information):**
 - OS: Windows 10
 - IDE: IntelliJ
 - Library/Libraries: com.azure.azure-messaging-servicebus:7.9.0
 - Java version: 8
 - App Server/Environment: Just a console application (ApplicationRunner)
 - Frameworks: SpringBoot

If you suspect a dependency version mismatch (e.g. you see `NoClassDefFoundError`, `NoSuchMethodError` or similar), please check out [Troubleshoot dependency version conflict article](https://aka.ms/azsdk/java/dependency/troubleshoot) first. If it doesn't provide solution for the problem, please provide:
- verbose dependency tree (`mvn dependency:tree -Dverbose`)
- exception message, full stack trace, and any available logs

**Additional context**

**Information Checklist**
Kindly make sure that you have added all the following information above and checkoff the required fields otherwise we will treat the issuer as an incomplete report
- [ ] Bug Description Added
- [ ] Repro Steps Added
- [ ] Setup information Added

**Comment by anuchandy** [comment]
Resolving this. Refer https://learn.microsoft.com/en-us/azure/developer/java/sdk/troubleshooting-messaging-service-bus-overview#upgrade-to-715x for details about version 7.15.x and how to opting-in new session rework.
