### ISSUE TITLE
[BUG][BlobStorage] There is no option to call copyFromURL with async

### ISSUE THREAD

**Issue by yangchengs** [Azure/azure-sdk-for-java#29832]
**Describe the bug**
This is cx issue.
We need a solution to copy large file from one container to another
When the file is larger than 256MB, there is exception

![image](https://user-images.githubusercontent.com/71274085/177675637-a3e40c77-b915-4ab4-8a7a-bf6178c2d6cf.png)

Seems there is no method to set the http header x-ms-requires-sync to false

https://github.com/Azure/azure-sdk-for-java/blob/f90e4e903b49d4780c84720d2e4df8e16e9d3756/sdk/storage/azure-storage-blob/src/main/java/com/azure/storage/blob/implementation/BlobsImpl.java

REST API:

https://docs.microsoft.com/en-us/rest/api/storageservices/copy-blob-from-url

**Expected behavior**
Have a method to call copyFromURL and supports file larger than 256MB.

**Comment by joshfree** [comment]
@rickle-msft @kasobol-msft could you please follow up with @yangchengs on this GitHub issue?

**Comment by ibrahimrabab** [comment]
Hi @yangchengs 
Are you still facing an issue related to this? If so, can you please let us know what you have tried, and what issues you are experiencing now? If not, we can go ahead and close this issue.
