### ISSUE TITLE
[BUG]Update azure-spring-boot-starter-cosmos in MS docs

### ISSUE THREAD

**Issue by Netyyyy** [Azure/azure-sdk-for-java#29863]
**Is your feature request related to a problem? Please describe.**
[docs](https://docs.microsoft.com/en-us/azure/spring-cloud/how-to-bind-cosmos?tabs=Service-Binding#prepare-your-java-project) still use the old Spring Cloud Azure dependencies of 3.x version.

**Describe the solution you'd like**
update the version to 4.x

**Describe alternatives you've considered**

**Additional context**

**Information Checklist**
Kindly make sure that you have added all the following information above and checkoff the required fields otherwise we will treat the issuer as an incomplete report
- [X] Description Added
- [x] Expected solution specified

**Comment by moarychan** [comment]
Closing it due to the doc pr merged.
