### ISSUE TITLE
OAuth2 authentication outside of the context of an incoming HTTP request

### ISSUE THREAD

**Issue by desmond-silveira** [Azure/azure-sdk-for-java#29939]
**Query/Question**
I have been learning via the [java-spring-webhooks-sample](https://github.com/microsoftgraph/java-spring-webhooks-sample) app along with other sample apps.  Each of these apps do their OAuth2 authentication from the context of an incoming HTTP request.  That is, in the sample apps, one connects to `http://localhost:8080/` and then makes a call to an HTTP endpoint to get an `org.springframework.security.oauth2.client.OAuth2AuthorizedClient` which can then be used to get an access token.

However, the application that I'm building for use with Azure won't be receiving any incoming HTTP requests.  It is a job run with a job scheduler whose sole goal is to keep MS Graph change notifications (subscriptions) alive by regularly refreshing the subscriptions.

Is there a way to use the Azure SDK for Java to get and refresh OAuth2 access tokens in a job that doesn't rely on incoming HTTP requests?

***Why is this not a Bug or a feature Request?***
I assume that there must be some way to get OAuth2 access tokens outside of the context of incoming HTTP requests, though I don't know for sure whether this is an existing feature.

**Setup (please complete the following information if applicable):**
 - OS: Java
 - IDE: IntelliJ
 - Library/Libraries: [java-spring-webhooks-sample](https://github.com/microsoftgraph/java-spring-webhooks-sample), [spring-cloud-azure-starter-active-directory](https://github.com/Azure/azure-sdk-for-java/tree/main/sdk/spring/spring-cloud-azure-starter-active-directory)
  - Set up the java-spring-webhooks-sample app per the instructions in the README.
  -  Run the app and go to `http://localhost:8080/` to initiate the app.
  -  Click on the App-only authentication subscribe button.  This is handled by the WatchController.apponly method within the sample app and Spring passes in a `OAuth2AuthorizedClient` object into this method which is then used for OAuth2 authentication.
  - How do I do this authentication without going through any type of servlet/controller? 
 
 **Information Checklist**
 Kindly make sure that you have added all the following information above and checkoff the required fields otherwise we will treat the issuer as an incomplete report
- [x] Query Added
- [x] Setup information Added

**Comment by desmond-silveira** [comment]
More specifically, I'm looking for the set of classes that should be used with AAD that manage OAuth 2.0 authentication via the client credential grant flow using a client id and client secret.
https://docs.microsoft.com/en-us/azure/active-directory/develop/v2-oauth2-client-creds-grant-flow#first-case-access-token-request-with-a-shared-secret

**Comment by chenrujun** [comment]
Hi, @desmond-silveira 

`client-credential grant flow` is the right way to satisfy your requirement.
`spring-cloud-azure-starter-active-directory` supports `client-credential grant flow` by property:

```
spring:
  cloud:
    azure:
      active-directory:
        authorization-clients:
          graph:  # It can be other clients
            authorization-grant-type: client_credentials` # This is the configuration item
```
Refs: https://microsoft.github.io/spring-cloud-azure/current/reference/html/index.html#client-credential-flow
