### ISSUE TITLE
[Bug]Improve MS docs about spring-cloud-azure-starter-keyvault-secrets

### ISSUE THREAD

**Issue by chenrujun** [Azure/azure-sdk-for-java#29940]
### Context 
Copied from: https://github.com/MicrosoftDocs/azure-dev-docs-pr/issues/2108

- Microsoft Docs (https://docs.microsoft.com/en-us/azure/developer/java/spring-framework/spring-boot-starters-for-azure) 
- Tutorial (https://docs.microsoft.com/en-us/azure/developer/java/spring-framework/configure-spring-boot-starter-java-app-with-azure-key-vault) 

### Problems
- Microsoft Docs (https://docs.microsoft.com/en-us/azure/developer/java/spring-framework/spring-boot-starters-for-azure) 
  - This is what the page says about the module: "Provides Spring value annotation support for integration with Azure Key Vault Secrets." Do we have a SecretClient we can use or does this only load all secrets as Spring properties? 
  - The page mentions a starter for Azure Key Vault but it really is for Secrets only. Although the descriptions clarifies this, I'm not sure if using a header like this might lead to user frustration/dissatisfaction (e.g. a customer creates a project thinking they can use it for Keys/Certificates and then realize it can't be done). 
  - An older version (3.5.0) is used and Java 8 is suggested. 
  - The verbiage in the page makes it look like using the Spring Initializr will include some Key Vault specific POM changes, but said changes slightly differ from what comes out of Spring Initializr. More specifically, this section is not included in the generated project: 
    ```
    <exclusion> 
    <groupId>org.junit.vintage</groupId> 
    <artifactId>junit-vintage-engine</artifactId> 
    </exclusion> 
    ```
- A good thing is that it doesn't load disabled secrets anymore. 

- Tutorial (https://docs.microsoft.com/en-us/azure/developer/java/spring-framework/configure-spring-boot-starter-java-app-with-azure-key-vault) 
  - Good on the steps to create a service principal, a Key Vault, assigning said principal to the vault and storing a secret in it. 
  - The recommended version to pick for the Spring Initializr project is outdated (2.4.6). The most recent stable version is 2.5.2 
  - The tutorial suggests using Java 11, so I'm not sure why other reference material shows a POM using Java 8. 
  - The first code sample could have better formatting: 
    ```
    System.out.println(String.format("\nConnection String stored in Azure Key Vault:\n%s\n",connectionString)); // Old 
    System.out.println(String.format("%nConnection String stored in Azure Key Vault:%n%s%n", connectionString)); // New 
    ```
  - They suggest using an older version of the Starter (3.5.0). 
  - It is not clear what the application property 'azure.keyvault.enabled' does. 
  - When trying to access a secret (as a Spring Property) that does not exist in the Key Vault, the application crashes without much explanation. The error message looks like the following: 
    ```
    org.springframework.beans.factory.BeanCreationException: Error creating bean with name 
    'keyVaultSecretsSpringBootStarterDemoApplication': Injection of autowired dependencies failed; nested exception is 
    java.lang.IllegalArgumentException: Could not resolve placeholder 'connectionString' in value "${connectionString}" 
    ```
  - Which means the property could not be found. However, it's not initially clear that it's because the secret could not be retrieved from the Key Vault. I doin't think users need to know how the Starter works in its entirety but it's important to be as clear as possible, especially because the documentation never says that all the enabled secrets in a given Key Vault will be loaded as Spring properties. 
  - For some reason this tutorial does the functionally same as the sample in GitHub (https://github.com/Azure-Samples/azure-spring-boot-samples/tree/main/keyvault/azure-spring-boot-sample-keyvault-secrets) but is not exactly the same code. 
  - This tutorial makes no mention of how to load specific secrets like the GitHub sample does.

**Comment by chenrujun** [comment]
> This is what the page says about the module: "Provides Spring value annotation support for integration with Azure Key Vault Secrets." Do we have a SecretClient we can use or does this only load all secrets as Spring properties?

Fixed in https://github.com/MicrosoftDocs/azure-dev-docs-pr/pull/3967

> The recommended version to pick for the Spring Initializr project is outdated (2.4.6). The most recent stable version is 2.5.2

This problem doesn't exist anymore.

> An older version (3.5.0) is used and Java 8 is suggested.

Version is 4.5.0 now. And Java version keep align with other modules. Will consider updating Java version in https://github.com/Azure/azure-sdk-for-java/issues/32459

> More specifically, this section is not included in the generated project:

This problem doesn't exist now.

> The recommended version to pick for the Spring Initializr project is outdated (2.4.6). The most recent stable version is 2.5.2

This problem doesn't exist now.

> The tutorial suggests using Java 11, so I'm not sure why other reference material shows a POM using Java 8.
Will consider updating Java version in https://github.com/Azure/azure-sdk-for-java/issues/32459

> The first code sample could have better formatting:

This problem doesn't exist now.

> They suggest using an older version of the Starter (3.5.0).

This problem doesn't exist now.

> It is not clear what the application property 'azure.keyvault.enabled' does.

property 'azure.keyvault.enabled' doesn't exist now.

> When trying to access a secret (as a Spring Property) that does not exist in the Key Vault, the application crashes without much explanation. The error message looks like the following:

It's spring-boot's behavior, it's not caused by Spring Cloud Azure.

> Which means the property could not be found. However, it's not initially clear that it's because the secret could not be retrieved from the Key Vault. I doin't think users need to know how the Starter works in its entirety but it's important to be as clear as possible, especially because the documentation never says that all the enabled secrets in a given Key Vault will be loaded as Spring properties.

It's spring-boot's behavior, it's not caused by Spring Cloud Azure.

> For some reason this tutorial does the functionally same as the sample in GitHub (https://github.com/Azure-Samples/azure-spring-boot-samples/tree/main/keyvault/azure-spring-boot-sample-keyvault-secrets) but is not exactly the same code.

The quick-start guide is not same with the sample. It's expected behavior.

> This tutorial makes no mention of how to load specific secrets like the GitHub sample does.

The quick-start guide is not same with the sample. It's expected behavior.

**Comment by fangjian0423** [comment]
> When trying to access a secret (as a Spring Property) that does not exist in the Key Vault, the application crashes without much explanation. The error message looks like the following:

application crash vs application startup but doesn't get secret from Key Vault, I prefer crash.

If you find the secret doesn't get when application running for a while, it's more dangerous.

**Comment by chenrujun** [comment]
Closing this issue in favor of https://github.com/MicrosoftDocs/azure-dev-docs-pr/pull/3967
