### ISSUE TITLE
[FEATURE REQ] Allow to revoke a User Delegation Key in SDK

### ISSUE THREAD

**Issue by jonasatmonday** [Azure/azure-sdk-for-java#29941]
**Is your feature request related to a problem? Please describe.**
I create my user delegation key programmatically with `BlobServiceClient#getUserDelegationKey(OffsetDateTime start, OffsetDateTime expiry)` and that works like a charm. That user delegation key is usually created with an expiry of 7 days. If the application is shut down before that 7 day period, we have a valid user delegation key left that is used by nobody as it was created automatically by the application and only used by that application.

I would like to be able to revoke that user delegation key upon application shutdown.

**Describe the solution you'd like**
I would like the BlobServiceClient to be extended with a method with the following signature:
`BlobServiceClient#revokeUserDelegationKey(UserDelegationKey userDelegationKey)`

That method would then revoke the given UserDelegationKey.

**Describe alternatives you've considered**
Initially, I created a query-ticket: https://github.com/Azure/azure-sdk-for-java/issues/29813 there it was suggested to use ACLs as an alternative. We need to evaluate if that is a valid option for us.

Nevertheless, I feel that the requested feature would make a lot of sense for the SDK.

**Additional context**
Only my initial ticket: https://github.com/Azure/azure-sdk-for-java/issues/29813

**Information Checklist**
Kindly make sure that you have added all the following information above and checkoff the required fields otherwise we will treat the issuer as an incomplete report
- [x] Description Added
- [x] Expected solution specified

**Comment by ibrahimrabab** [comment]
Hi @jonasatmonday , thanks for creating this feature request! We've added to our backlog for now and will get back to you soon.

**Comment by rickle-msft** [comment]
As discussed on #29813, we don't currently have a way to do this on the client; we will need to wait for the service to support this feature before we can add such an api.
