### ISSUE TITLE
[QUERY] Azure CosmosDB Spark OLTP Connector with Managed Identity

### ISSUE THREAD

**Issue by stevenylai** [Azure/azure-sdk-for-java#29958]
**Query/Question**
We are trying to ingest data from DataLake to Azure Cosmos DB and [Spark OLTP Connector](https://docs.microsoft.com/en-us/azure/cosmos-db/sql/create-sql-api-spark) seems to be the easiest to use.

But due to the company's policy, we are not allowed to use the master keys in production since those keys are managed by a separate team. Instead, we use managed identity to authenticate the Azure resources for our projects. I can see the Cosmos DB Java client builder has the 'TokenCredential' option which can be used to authenticate with managed identity:

```java
    CosmosAsyncClient client = CosmosClientBuilder
     .credential(new DefaultAzureCredentialBuilder().build())
     .buildAsyncClient();
```
Is there anyway to setup the connector the same authentication mechanism with managed identity? Or perhaps can I get a temporary account key from `DefaultAzureCredential`? I tried to look at the examples and tests within the CosmosDB spark connector but it seems that all the examples are using CosmosDB account master key (`spark.cosmos.accountKey`). 

***Why is this not a Bug or a feature Request?***
I am not sure if this is already supported or not.

**Setup (please complete the following information if applicable):**
 - OS: Windows
 - IDE: IntelliJ
 - Library/Libraries: com.azure.cosmos.spark-cosmos-spark_3-1_2-12:4.11.1
 
 **Information Checklist**
 Kindly make sure that you have added all the following information above and checkoff the required fields otherwise we will treat the issuer as an incomplete report
- [ x ] Query Added
- [ x ] Setup information Added

**Comment by w0ut0** [comment]
Hello, is there any follow up this issue?
@kushagraThapar @TheovanKraay

**Comment by TheovanKraay** [comment]
@w0ut0 this is not yet supported. We are planning on adding AAD support to Spark Connector in the current development cycle, aiming for March 2023.
