### ISSUE TITLE
[BUG] Azure Graph conflict with Tika-app on (JsonGenerator) jackson version 2.13.3 - bug changes version to 2.4.1 (Tika's version)

### ISSUE THREAD

**Issue by AndreNelAltron** [Azure/azure-sdk-for-java#29963]
**Describe the bug**
Azure Graph conflict with Tika-app on (JsonGenerator) jackson version 2.13.3 - bug changes version to 2.4.1 (Tika's version) - Have also reported bug to apache's Tika-app team

***Exception or Stack Trace***
ERROR [main] 12:03:19,483 com.azure.core.implementation.jackson.JacksonVersion Version '2.4.1' of package 'jackson-annotations' is not supported (older than earliest supported version - `2.10.0`), please upgrade.
ERROR [main] 12:03:19,489 com.azure.core.implementation.jackson.JacksonVersion Version '2.4.1' of package 'jackson-core' is not supported (older than earliest supported version - `2.10.0`), please upgrade.
ERROR [main] 12:03:19,489 com.azure.core.implementation.jackson.JacksonVersion Version '2.4.1' of package 'jackson-databind' is not supported (older than earliest supported version - `2.10.0`), please upgrade.
INFO  [main] 12:03:19,491 com.azure.core.implementation.jackson.JacksonVersion Package versions: jackson-annotations=2.4.1, jackson-core=2.4.1, jackson-databind=2.4.1, jackson-dataformat-xml=unknown, jackson-datatype-jsr310=2.13.3, azure-core=1.30.0, Troubleshooting version conflicts: https://aka.ms/azsdk/java/dependency/troubleshoot
ERROR [main] 12:03:19,494 com.azure.core.implementation.jackson.ObjectMapperShim Package versions: jackson-annotations=2.4.1, jackson-core=2.4.1, jackson-databind=2.4.1, jackson-dataformat-xml=unknown, jackson-datatype-jsr310=2.13.3, azure-core=1.30.0, Troubleshooting version conflicts: https://aka.ms/azsdk/java/dependency/troubleshoot
Exception in thread "main" java.lang.LinkageError: Package versions: jackson-annotations=2.4.1, jackson-core=2.4.1, jackson-databind=2.4.1, jackson-dataformat-xml=unknown, jackson-datatype-jsr310=2.13.3, azure-core=1.30.0, Troubleshooting version conflicts: https://aka.ms/azsdk/java/dependency/troubleshoot
    at com.azure.core.implementation.jackson.ObjectMapperShim.createHeaderMapper(ObjectMapperShim.java:138)
    at com.azure.core.util.serializer.JacksonAdapter.<init>(JacksonAdapter.java:81)
    at com.azure.core.util.serializer.JacksonAdapter.<init>(JacksonAdapter.java:59)
    at com.azure.core.util.serializer.JacksonAdapter$SerializerAdapterHolder.<clinit>(JacksonAdapter.java:114)
    at com.azure.core.util.serializer.JacksonAdapter.createDefaultSerializerAdapter(JacksonAdapter.java:123)
    at com.azure.identity.implementation.IdentityClient.<clinit>(IdentityClient.java:104)
    at com.azure.identity.implementation.IdentityClientBuilder.build(IdentityClientBuilder.java:158)
    at com.azure.identity.ClientSecretCredential.<init>(ClientSecretCredential.java:68)
    at com.azure.identity.ClientSecretCredentialBuilder.build(ClientSecretCredentialBuilder.java:93)
    at main.java.emailtranslator.EmailTranslator.connectOffice365MicrosoftGraph

**To Reproduce**
Java 1.8, Maven Project, tika-app 2.4.1, jackson 2.13.3, azure-core 1.30.0

Both Tika-app 2.4.1 and Azure-core 1.30.0 use jars with classes of the same name JsonGenerator (com.fasterxml.jackson.core.JsonGenerator) when fetching the jackson version, of which jackson-core 2.13.3 is desired and set in the pom. This results in version conflict - where tika changes the jackson version from the desired 2.13.3 to tika's version 2.4.1, which doesn't even exist for jackson and would be far too old a version of jackson.

***Code Snippet***
My offending code calling azure-core graph:

            final ClientSecretCredential clientSecretCredential = new ClientSecretCredentialBuilder()
            .clientId(clientId)
            .clientSecret(clientSecret)
            .tenantId(tenantId)
            .build();

            final TokenCredentialAuthProvider tokenCredentialAuthProvider = new TokenCredentialAuthProvider(scopes, clientSecretCredential);

            final GraphServiceClient graphClient =
            GraphServiceClient
            .builder()
            .authenticationProvider(tokenCredentialAuthProvider)
            .buildClient();

            final User me = graphClient.me().buildRequest().get();

 

which calls azure-core-1.30.0.jar -> com.azure.core.implementation.jackson -> JacksonVersion.class line 43 onwards:

    private JacksonVersion() {
        annotationsVersion = SemanticVersion.getPackageVersionForClass("com.fasterxml.jackson.annotation.JsonProperty");
        coreVersion = SemanticVersion.getPackageVersionForClass("com.fasterxml.jackson.core.JsonGenerator");
        databindVersion = SemanticVersion.getPackageVersionForClass("com.fasterxml.jackson.databind.ObjectMapper");
        xmlVersion = SemanticVersion.getPackageVersionForClass("com.fasterxml.jackson.dataformat.xml.XmlMapper");
        jsr310Version = SemanticVersion.getPackageVersionForClass("com.fasterxml.jackson.datatype.jsr310.JavaTimeModule");

 

Which is messed up by: tika-app-2.4.1,jar -> com.azure.core.implementation.jackson.JacksonVersion -> JsonGenerator.class

which changes the jackson version from 2.13.3 to tika's 2.4.1... causing a world of hurt 

 

 

 

Portions of My POM trying to resolve the conflict:

...

    <dependencyManagement>
       <dependencies>
            <dependency>
                <groupId>com.fasterxml.jackson.core</groupId>
                <artifactId>jackson-annotations</artifactId>
                <version>2.13.3</version>
            </dependency>
            <dependency>
                <groupId>com.fasterxml.jackson.core</groupId>
                <artifactId>jackson-core</artifactId>
                <version>2.13.3</version>
            </dependency>
            <dependency>
                <groupId>com.fasterxml.jackson.core</groupId>
                <artifactId>jackson-databind</artifactId>
                <version>2.13.3</version>
            </dependency>
            <dependency>
                <groupId>com.fasterxml.jackson.dataformat</groupId>
                <artifactId>jackson-dataformat-xml</artifactId>
                <version>2.13.3</version>
            </dependency>
            <dependency>
                <groupId>com.fasterxml.jackson.datatype</groupId>
                <artifactId>jackson-datatype-jsr310</artifactId>
                <version>2.13.3</version>
            </dependency>
        </dependencies>
    </dependencyManagement>

...

        
        <dependency>
            <groupId>com.azure</groupId>
            <artifactId>azure-core</artifactId>
            <version>1.30.0</version><!{}Jun, 2022{}>
            <exclusions>
                <exclusion>
                    <groupId>com.fasterxml.jackson.core</groupId>
                    <artifactId>jackson-annotations</artifactId>
                </exclusion>
                <exclusion>
                    <groupId>com.fasterxml.jackson.core</groupId>
                    <artifactId>jackson-core</artifactId>
                </exclusion>
                <exclusion>
                    <groupId>com.fasterxml.jackson.core</groupId>
                    <artifactId>jackson-databind</artifactId>
                </exclusion>
                <exclusion>
                    <groupId>com.fasterxml.jackson.dataformat</groupId>
                    <artifactId>jackson-dataformat-xml</artifactId>
                </exclusion>
                <exclusion>
                    <groupId>com.fasterxml.jackson.datatype</groupId>
                    <artifactId>jackson-datatype-jsr310</artifactId>
                </exclusion>
            </exclusions>
        </dependency>

...

        
        <dependency>
            <groupId>com.fasterxml.jackson.core</groupId>
            <artifactId>jackson-annotations</artifactId>
            <version>2.13.3</version>
            <scope>provided</scope>
        </dependency>
        
        <dependency>
            <groupId>com.fasterxml.jackson.core</groupId>
            <artifactId>jackson-core</artifactId>
            <version>2.13.3</version>
            <scope>provided</scope>
        </dependency>
        
        <dependency>
            <groupId>com.fasterxml.jackson.core</groupId>
            <artifactId>jackson-databind</artifactId>
            <version>2.13.3</version>
            <scope>provided</scope>
        </dependency>
        
        <dependency>
            <groupId>com.fasterxml.jackson.dataformat</groupId>
            <artifactId>jackson-dataformat-xml</artifactId>
            <version>2.13.3</version>
            <scope>provided</scope>
        </dependency>
        
        <dependency>
            <groupId>com.fasterxml.jackson.datatype</groupId>
            <artifactId>jackson-datatype-jsr310</artifactId>
            <version>2.13.3</version>
            <scope>provided</scope>
        </dependency>

...

        <dependency>
            <groupId>org.apache.tika</groupId>
            <artifactId>tika-app</artifactId>
            <version>2.4.1</version><!{}Jun, 2022{}>
            <exclusions>
                <exclusion>
                    <groupId>com.fasterxml.jackson.core</groupId>
                    <artifactId>jackson-annotations</artifactId>
                </exclusion>
                <exclusion>
                    <groupId>com.fasterxml.jackson.core</groupId>
                    <artifactId>jackson-core</artifactId>
                </exclusion>
                <exclusion>
                    <groupId>com.fasterxml.jackson.core</groupId>
                    <artifactId>jackson-databind</artifactId>
                </exclusion>
                <exclusion>
                    <groupId>com.fasterxml.jackson.dataformat</groupId>
                    <artifactId>jackson-dataformat-xml</artifactId>
                </exclusion>
                <exclusion>
                    <groupId>com.fasterxml.jackson.datatype</groupId>
                    <artifactId>jackson-datatype-jsr310</artifactId>
                </exclusion>
            </exclusions>
        </dependency>

**Expected behavior**
No error and jackson version should stay as 2.13.3

**Screenshots**

**Setup (please complete the following information):**
 - OS: Windows
 - IDE: Netbeans (oe Eclipse)
 - Library/Libraries: azure-core 1.30.0, tika-app 2.4, jackson-core 2.13.3
 - Java version: 8 
 - App Server/Environment: Standard Java App Project with Maven support
 - Frameworks: -

It is a Dependency version issue in a way - but the code is causing it - cannot be fixed via POM...

**Additional context**

**Information Checklist**
Kindly make sure that you have added all the following information above and checkoff the required fields otherwise we will treat the issuer as an incomplete report
- [x ] Bug Description Added
- [x ] Repro Steps Added
- [x ] Setup information Added

**Comment by alzimmermsft** [comment]
Thanks for filing this issue @AndreNelAltron.

From testing around I was able to resolve this by removing the  `<scope>provided</scope>` from the Jackson dependencies. Could you try the same and let me know if that resolves the issue for you?

**Comment by AndreNelAltron** [comment]
Hi Alan,
Thanks for trying to assist me… and all the other people also 😊…

Although I pull the jar’s from the POM, my project in Netbeans also seems to require me to add the jar libs to build and run it…
so the POM builds fine with Maven…
but when I run the program it rather uses the corresponding jars copied to my lib folder…

So removing the <scope>provided</scope> seems to have no effect by me…

I’ve also been trying to split the tika-app into its components (to avoid the clash between the tika-app and azure jars) and now the okhttp and kotlin jars are giving me a world of problems, with it not seeing the kotlin/collections/AbstractList (more about this futher below…)

… so back to your question…

When I add the lib:
lib/tika-app-2.4.1.jar

to the top of the list of external jars…(see full lib list further below)

I get the error:

connectOffice365MicrosoftGraph()...
ERROR [main] 11:24:32,702 com.azure.core.implementation.jackson.JacksonVersion Version '2.4.1' of package 'jackson-annotations' is not supported (older than earliest supported version - `2.10.0`), please upgrade.
ERROR [main] 11:24:32,708 com.azure.core.implementation.jackson.JacksonVersion Version '2.4.1' of package 'jackson-core' is not supported (older than earliest supported version - `2.10.0`), please upgrade.
ERROR [main] 11:24:32,708 com.azure.core.implementation.jackson.JacksonVersion Version '2.4.1' of package 'jackson-databind' is not supported (older than earliest supported version - `2.10.0`), please upgrade.
INFO  [main] 11:24:32,709 com.azure.core.implementation.jackson.JacksonVersion Package versions: jackson-annotations=2.4.1, jackson-core=2.4.1, jackson-databind=2.4.1, jackson-dataformat-xml=2.12.2, jackson-datatype-jsr310=2.12.2, azure-core=1.30.0, Troubleshooting version conflicts: https://aka.ms/azsdk/java/dependency/troubleshoot
Exception in thread "main" java.lang.NoClassDefFoundError: kotlin/collections/AbstractList
                at java.lang.ClassLoader.defineClass1(Native Method)
                at java.lang.ClassLoader.defineClass(ClassLoader.java:756)
                at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
                at java.net.URLClassLoader.defineClass(URLClassLoader.java:468)
                at java.net.URLClassLoader.access$100(URLClassLoader.java:74)
                at java.net.URLClassLoader$1.run(URLClassLoader.java:369)
                at java.net.URLClassLoader$1.run(URLClassLoader.java:363)
                at java.security.AccessController.doPrivileged(Native Method)
                at java.net.URLClassLoader.findClass(URLClassLoader.java:362)
                at java.lang.ClassLoader.loadClass(ClassLoader.java:418)
                at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:355)
                at java.lang.ClassLoader.loadClass(ClassLoader.java:351)
                at okhttp3.internal.Util.<clinit>(Util.kt:70)
                at okhttp3.internal.concurrent.TaskRunner.<clinit>(TaskRunner.kt:309)
                at okhttp3.ConnectionPool.<init>(ConnectionPool.kt:41)
                at okhttp3.ConnectionPool.<init>(ConnectionPool.kt:47)
                at okhttp3.OkHttpClient$Builder.<init>(OkHttpClient.kt:471)
                at com.microsoft.graph.httpcore.HttpClients.custom(HttpClients.java:28)
                at com.microsoft.graph.httpcore.HttpClients.createDefault(HttpClients.java:44)
                at com.microsoft.graph.core.BaseClient$Builder.getHttpClient(BaseClient.java:180)
                at com.microsoft.graph.core.BaseClient$Builder.getHttpProvider(BaseClient.java:188)
                at com.microsoft.graph.core.BaseClient$Builder.buildClient(BaseClient.java:276)
                at com.microsoft.graph.requests.GraphServiceClient$Builder.buildClient(GraphServiceClient.java:258)
                at main.java.emailtranslator.EmailTranslator.connectOffice365MicrosoftGraph


When I exclude tika-app-2.4.1.jar then
The list of my jars are:

lib/kotlin-runtime-1.2.71.jar
lib/kotlin-stdlib-common-1.7.10.jar
lib/okhttp-4.10.0.jar
lib/okio-jvm-3.2.0.jar
lib\javax.mail-1.6.1.jar
lib\json-simple-1.1.1.jar
lib\sqlite-jdbc-3.23.1.jar
lib/reactive-streams-1.0.4.jar
lib/msal4j-1.13.0.jar
lib/jai-imageio-core-1.4.0.jar
lib/jai-imageio-jpeg2000-1.4.0.jar
lib/javax.servlet-api-4.0.1.jar
lib\aspose-pdf-18.10.jar
lib/openjson-1.0.12.jar
lib/log4j-1.2.17.jar
lib/tika-core-2.4.1.jar
lib/tika-parser-pdf-module-2.4.1.jar
lib/commons-io-2.11.0.jar
lib/slf4j-api-1.7.36.jar
lib/com.springsource.javax.xml.stream-1.0.1.jar
lib/jackson-annotations-2.12.2.jar
lib/jackson-core-2.12.2.jar
lib/jackson-databind-2.12.2.jar
lib/jackson-dataformat-xml-2.12.2.jar
lib/jackson-datatype-jsr310-2.12.2.jar
lib/slf4j-simple-1.7.36.jar
lib/reactor-core-3.4.19.jar
lib/classgraph-4.8.143.jar
lib/azure-core-1.30.0.jar
lib/azure-identity-1.5.3.jar
lib/microsoft-graph-core-2.0.13.jar
lib/microsoft-graph-5.30.0.jar
lib/gson-2.9.0.jar

and here I get the error:

Exception in thread "main" java.lang.NoClassDefFoundError: kotlin/collections/AbstractList
…
                at okhttp3.internal.Util.<clinit>(Util.kt:70)
                at okhttp3.internal.concurrent.TaskRunner.<clinit>(TaskRunner.kt:309)
                at okhttp3.ConnectionPool.<init>(ConnectionPool.kt:41)
                at okhttp3.ConnectionPool.<init>(ConnectionPool.kt:47)
                at okhttp3.OkHttpClient$Builder.<init>(OkHttpClient.kt:471)
                at com.microsoft.graph.httpcore.HttpClients.custom(HttpClients.java:28)
                at com.microsoft.graph.httpcore.HttpClients.createDefault(HttpClients.java:44)
                at com.microsoft.graph.core.BaseClient$Builder.getHttpClient(BaseClient.java:180)
                at com.microsoft.graph.core.BaseClient$Builder.getHttpProvider(BaseClient.java:188)
                at com.microsoft.graph.core.BaseClient$Builder.buildClient(BaseClient.java:276)
                at com.microsoft.graph.requests.GraphServiceClient$Builder.buildClient(GraphServiceClient.java:258)

Which kotlin-stdlib-common-1.7.10.jar should solve but doesn’t… I’m stumped…?

…
I had to change to Jackson 2.12.2 because of an error with 2.13.3 – which moving back to previous version resolved… found an article where they used 2.12.1 to resolve the problem… https://github.com/FasterXML/jackson-dataformat-xml/issues/521

Error:

[main] INFO com.azure.core.implementation.jackson.JacksonVersion - Package versions: jackson-annotations=2.13.3, jackson-core=2.13.3, jackson-databind=2.13.3, jackson-dataformat-xml=2.13.3, jackson-datatype-jsr310=2.13.3, azure-core=1.30.0, Troubleshooting version conflicts: https://aka.ms/azsdk/java/dependency/troubleshoot
…
Exception in thread "main" javax.xml.stream.FactoryConfigurationError: Provider for javax.xml.stream.XMLInputFactory cannot be found
                at javax.xml.stream.FactoryFinder.find(FactoryFinder.java:324)
                at javax.xml.stream.XMLInputFactory.newFactory(XMLInputFactory.java:291)



…
If I remove the 5 Jackson 2.12.2  libs and keep the tika-app.jar I still get the same 1st error mentioned

ERROR [main] 11:42:04,653 com.azure.core.implementation.jackson.JacksonVersion Version '2.4.1' of package 'jackson-annotations' is not supported (older than earliest supported version - `2.10.0`), please upgrade.

**Comment by AndreNelAltron** [comment]
I see that while breaking Tika-App up into jars to include - the kotlin problem (java.lang.NoClassDefFoundError: kotlin/collections/AbstractList) I was getting was because I had left lib/kotlin-stdlib-1.7.10.jar out... it must be used in conjunction with kotlin-stdlib-common-1.7.10.jar

...now I'm on to the next missing dependencies...

**Comment by AndreNelAltron** [comment]
Looks like the next lib I need is: oauth2-oidc-sdk-9.35.jar

**Comment by alzimmermsft** [comment]
Hi @AndreNelAltron were you able to resolve this issue? I did make changes to how `JacksonVersion` determined the versions of Jackson that we're loaded which should hopefully be more resilient to cases like this: https://github.com/Azure/azure-sdk-for-java/pull/29964
