### ISSUE TITLE
Regenerate resourcemanager

### ISSUE THREAD

**Issue by lmolkova** [Azure/azure-sdk-for-java#29991]
`Mono/Flux.subscriberContext` will be removed from reactor 3.5, need to regenerate resourcemanager artifacts that use it

**Comment by lmolkova** [comment]
@weidongxu-microsoft @haolingdong-msft @XiaofeiCao @arthurma1978 can one of you please take a look?

**Comment by lmolkova** [comment]
Also, `Context.putAll` is deprecated and, as a result of regeneration, `subscriberContext(context -> context.putAll((FluxUtil.toReactorContext ...))` should be replaced by 
`contextWrite(Context.of(FluxUtil.toReactorContext ...))`

**Comment by weidongxu-microsoft** [comment]
@lmolkova Thanks for notifying. When do we plan to upgrade to reactor 3.5?

`putAll` in new code should be fine, we are using the `putAll(ContextView other)` overload in codegen, not the deprecated `putAll(Context context)` overload.

@XiaofeiCao Please handle this. I will need to find the commit of SQL as its latest composite-v3 actually having lots of breaking changes.

**Comment by weidongxu-microsoft** [comment]
sql https://github.com/Azure/azure-sdk-for-java/pull/30014
hybrid https://github.com/Azure/azure-sdk-for-java/pull/30015

**Comment by weidongxu-microsoft** [comment]
recoveryservices https://github.com/Azure/azure-sdk-for-java/pull/30021
relay https://github.com/Azure/azure-sdk-for-java/pull/30018
healthbot https://github.com/Azure/azure-sdk-for-java/pull/30017

**Comment by XiaofeiCao** [comment]
search https://github.com/Azure/azure-sdk-for-java/pull/30039

**Comment by weidongxu-microsoft** [comment]
@XiaofeiCao if we've finished it, please ping Liudmila.

**Comment by XiaofeiCao** [comment]
Hi @lmolkova , `Mono/Flux.subscriberContext` and `ReplayProcessor` in resourcemanager have been replaced.

**Comment by weidongxu-microsoft** [comment]
@lmolkova let us know if anything else you need help.

**Comment by lmolkova** [comment]
@weidongxu-microsoft thank you for following up on this! Looks good!
I broke my notifications and didn't see your questions. Reactor 3.5 is expected by the end of 2022
