### ISSUE TITLE
[BUG] SAS tokens are sanitized incorrectly when they start with ?

### ISSUE THREAD

**Issue by fcofdez** [Azure/azure-sdk-for-java#29998]
**Describe the bug**
After introducing https://github.com/Azure/azure-sdk-for-java/pull/20520 SAS query params are sanitized but it seems like the parsing is not taking into account the case where the SAS token has a `?` prefix:
https://github.com/Azure/azure-sdk-for-java/blob/3f31d68eed6fbe11516ca3afe3955c8840a6e974/sdk/storage/azure-storage-common/src/main/java/com/azure/storage/common/implementation/connectionstring/StorageAuthenticationSettings.java#L86-L92

This ends up removing the first query parameter from the SAS token, therefore producing an invalid signature, since the first query parameter is parsed as `?<key>` instead of `<key>`.

**To Reproduce**

Provide a valid SAS signature with `?` as prefix.

**Expected behavior**

**Setup (please complete the following information):**
 - Library/Libraries: `com.azure:azure-storage:12.16.0`

**Information Checklist**
Kindly make sure that you have added all the following information above and checkoff the required fields otherwise we will treat the issuer as an incomplete report
- [X] Bug Description Added
- [X] Repro Steps Added
- [X] Setup information Added

**Comment by joshfree** [comment]
@rickle-msft @kasobol-msft could you please follow up with @fcofdez on this github issue?
