### ISSUE TITLE
[FEATURE REQ] Optimize core IOUtils.transfer for file channels.

### ISSUE THREAD

**Issue by kasobol-msft** [Azure/azure-sdk-for-java#29999]
from https://github.com/Azure/azure-sdk-for-java/pull/29971 .

We should use bulk `FileChannel.transferTo/From` if source and/or destination is a `FileChannel`.

See
https://docs.oracle.com/javase/8/docs/api/java/nio/channels/FileChannel.html#transferFrom-java.nio.channels.ReadableByteChannel-long-long-
https://docs.oracle.com/javase/8/docs/api/java/nio/channels/FileChannel.html#transferTo-long-long-java.nio.channels.WritableByteChannel-

**Comment by g2vinay** [comment]
Resolved via #29971
