### ISSUE TITLE
sharing / blog / sample for scenarios using spring-cloud-azure Azure AD

### ISSUE THREAD

**Issue by chenrujun** [Azure/azure-sdk-for-java#30042]
## Context

**Spring Cloud Azure** team released **spring-cloud-azure-starter-active-directory**, which can help customer to develop a **spring-boot** application protected by **Azure AD**. But many customers and Microsoft colleagues don't know about it.

## Goal

Broadcast **spring-cloud-azure-starter-active-directory** by sharing meeting / blog / sample

## Refs

1. https://web.yammer.com/main/org/microsoft.com/threads/eyJfdHlwZSI6IlRocmVhZCIsImlkIjoiMTgzMzQxOTI4MzQzOTYxNiJ9
2. https://docs.microsoft.com/en-us/azure/active-directory/develop/sample-v2-code

**Comment by stliu** [comment]
this is more like a plan not a feature
