### ISSUE TITLE
Assign a role to a service principle without Azure AD reader permissions

### ISSUE THREAD

**Issue by DenisVoloshin** [Azure/azure-sdk-for-java#30047]
**Question**

I can't assign a role to a service principle without Azure AD reader permissions.
 
Hello, I'm trying to use the following API to assign a role to the service principal using another service principle 
that have required permissions to create a role assignment 

```
RoleAssignment roleAssignment = azureResourceManager.accessManagement().roleAssignments()
                    .define("raName")
                    .forServicePrincipal(sp)
                    .withBuiltInRole(BuiltInRole.CONTRIBUTOR)
                    .withSubscriptionScope(profile.getSubscriptionId())
                    .create();

```
The problem I run into is an exception. I'm getting **Insufficient privileges to complete the operation.**

Investigating the error, I found that to complete this call using SDK. The service principal must also have Azure AD reader permission. Regardless, if I provide the ServicePrincipal object as a param into the **for service principal** method or
```
azureResourceManager.accessManagement().servicePrincipals().getById(spnId)
```

Or use the top service name.

On the other hand, performing the same command using az CLI, my operational service principal, hasn't had Azure AD reader permission.  

```
   az role assignment create --assignee <SP> --role "Storage Blob Data Contributor" --scope  "<SCOPE>"

```
I guess the underline  Java SDK code tries to get principal service details before applying a role assignment. That's why it fails without Azure AD Reader permission. 

Please instruct me if there is a workaround to prevent this error. 

**Setup (please complete the following information if applicable):**
 - OS: iOS
 - IDE: IntelliJ
 - Library/Libraries:  com.azure:azure-core:1.30.0

**Comment by joshfree** [comment]
@weidongxu-microsoft could you follow up with @DenisVoloshin on this github issue?

**Comment by weidongxu-microsoft** [comment]
@DenisVoloshin

Yes, the AAD reader permission is used to convert the service principal ID to object ID.

If you want to do this without the permission, use the `forObjectId` instead of `forServicePrincipal`, and provide the object ID directly (`ServicePrincipal.id` in Java SDK).

You can have the CLI or service principal that having the AAD reader permission to support that object ID. E.g. https://docs.microsoft.com/en-us/azure/healthcare-apis/azure-api-for-fhir/find-identity-object-ids

**Comment by DenisVoloshin** [comment]
Hi @[weidongxu-microsoft](https://github.com/weidongxu-microsoft)
thanks a lot for the quick reply. It works as a good boy now
