### ISSUE TITLE
[FEATURE REQ] Pre-Compute SwaggerMethodParser Values

### ISSUE THREAD

**Issue by kasobol-msft** [Azure/azure-sdk-for-java#30085]
We should refactor SwaggerMethodParser to the point where all values that can be precomputed at construction time are cached in fields.

Continue work on https://github.com/Azure/azure-sdk-for-java/pull/28360

**Comment by kasobol-msft** [comment]
Related https://github.com/Azure/azure-sdk-for-java/pull/30086

**Comment by alzimmermsft** [comment]
Closing as this is complete
