### ISSUE TITLE
[QUERY] Azure Service Bus: Is abandon() called for messages on transaction rollback?

### ISSUE THREAD

**Issue by chrisupb** [Azure/azure-sdk-for-java#30096]
**Query/Question**
Azure Service Bus SpingBoot JMS: Is abandon() called for messages on transaction rollback?

***Why is this not a Bug or a feature Request?***
Because abandon() should be the default behaviour.

**Setup (please complete the following information if applicable):**
 - OS: Linux
 - IDE: IntelliJ
 - Library/Libraries: com.azure.spring:spring-cloud-azure-starter-servicebus-jms:4.2.0
 
 **Information Checklist**
If you follow the official SpringBoot Starter JMS example at https://docs.microsoft.com/en-us/azure/developer/java/spring-framework/configure-spring-boot-starter-java-app-with-azure-service-bus

and implement such a listener
` @JmsListener(destination = "${queue.name}", containerFactory = "jmsListenerContainerFactory")`
`@Transactional`
`public void receiveMessage(String message) {`

   `throw new RuntimeException();`
 ` }`
`} `

abandon() is not called for the message. This has the effect that ASB waits for the server-side message Peek Lock duration to expire and redelivers the message after X min. This is not the expected behaviour. The message should be released immediately.
  
The ServiceBusJmsContainerConfiguration https://github.com/Azure/azure-sdk-for-java/blob/5bc550c9a5de4f8ee93a5b3141500ee34be3850d/sdk/spring/spring-cloud-azure-autoconfigure/src/main/java/com/azure/spring/cloud/autoconfigure/jms/ServiceBusJmsContainerConfiguration.java#L47 
 creates a DefaultJmsListenerContainerFactoryConfigurer  with sessionAcknowledgeMode=null and sessionTransacted=true.

I read https://github.com/Azure/azure-sdk-for-java/issues/26762 but it seems to target CLIENT_ACKNOWLEDGE.

**Comment by yiliuTo** [comment]
@chrisupb thanks for reaching us. When using the @JmsListener, it uses the AbstractMessageListenerContainer and  MessagingMessageListenerAdapter defined by `org.springframework:spring-jms` library which doesn't abandon messages on transaction rollback. 
Besides, our library of `com.azure.spring:spring-cloud-azure-starter-servicebus-jms` doesn't provide any custom listener container or listener currently to execute any message settlement operation. Thus we doesn's support this feature now.

**Comment by chrisupb** [comment]
OK, thank you. So I need to use com.azure:azure-messaging-servicebus library if I want to abandon messages 
`com.azure.messaging.servicebus.ServiceBusReceivedMessageContext.abandon()`
