### ISSUE TITLE
[BUG] NPE when create application insights

### ISSUE THREAD

**Issue by Flanker32** [Azure/azure-sdk-for-java#30116]
**Describe the bug**
We found there may have NullPointerException when create application insights, at `com.azure.resourcemanager.applicationinsights.implementation.ApplicationInsightsComponentImpl.create(ApplicationInsightsComponentImpl.java:205)`

***Exception or Stack Trace***
```
Caused by: java.lang.NullPointerException
	at com.azure.resourcemanager.applicationinsights.implementation.ApplicationInsightsComponentImpl.create(ApplicationInsightsComponentImpl.java:205)
	at com.microsoft.azure.toolkit.lib.applicationinsights.ApplicationInsightDraft.createResourceInAzure(ApplicationInsightDraft.java:73)
	... 16 more
```

**To Reproduce**
```
        final ApplicationInsightsComponent result = applicationInsightsManager.components().define(getName())
            .withRegion(region.getName())
            .withExistingResourceGroup(getResourceGroupName())
            .withKind("web")
            .withApplicationType(ApplicationType.WEB).create();
```

Note, the issue could not be stable reproduced, it runs well in my machine, we just found this issue through telemetry.

***Code Snippet***
Add the code snippet that causes the issue.

**Expected behavior**
Resource should be created successfully or throw exception with detail error message

**Screenshots**

**Setup (please complete the following information):**
 - OS: [e.g. iOS] Windows 10/Linux/Mac
 - IDE: [e.g. IntelliJ] 
 - Library/Libraries: [e.g. com.azure:azure-core:1.16.0 (groupId:artifactId:version)]  com.azure.resourcemanager:azure-resourcemanager-applicationinsights:1.0.0-beta.4
 - Java version: [e.g. 8] 11
 - App Server/Environment: [e.g. Tomcat, WildFly, Azure Function, Apache Spark, Databricks, IDE plugin or anything special]
 - Frameworks: [e.g. Spring Boot, Micronaut, Quarkus, etc] 

If you suspect a dependency version mismatch (e.g. you see `NoClassDefFoundError`, `NoSuchMethodError` or similar), please check out [Troubleshoot dependency version conflict article](https://aka.ms/azsdk/java/dependency/troubleshoot) first. If it doesn't provide solution for the problem, please provide:
- verbose dependency tree (`mvn dependency:tree -Dverbose`)
- exception message, full stack trace, and any available logs

**Additional context**

**Information Checklist**
Kindly make sure that you have added all the following information above and checkoff the required fields otherwise we will treat the issuer as an incomplete report
- [x] Bug Description Added
- [x] Repro Steps Added
- [x] Setup information Added

**Comment by weidongxu-microsoft** [comment]
@XiaofeiCao Please help to investigate.

**Comment by XiaofeiCao** [comment]
@Flanker32 

Sorry for the late response... 

Seems it happens on line `getValue` of the returned `Response<ApplicationInsightsComponentInner>`:
```java
serviceManager
   .serviceClient()
   .getComponents()
   .createOrUpdateWithResponse(resourceGroupName, resourceName, this.innerModel(), Context.NONE)
   .getValue();
```

No idea why the whole `Response` is null. I guess some error did occur but somehow got swallowed in the reactor chain, returning an empty `Mono`. 

Could you provide an http log of the creation process when the NPE throws? You can use the following snippet to enable logging:
```java
ApplicationInsightsManager
    .configure()
    .withLogOptions(new HttpLogOptions().setLogLevel(HttpLogDetailLevel.BODY_AND_HEADERS))
```

The log should contain something like this:
#### request

> com.azure.resourcemanager.applicationinsights.implementation.ComponentsClientImpl$ComponentsService.createOrUpdate - {"az.sdk.message":"HTTP request","method":"PUT"


#### response

> com.azure.resourcemanager.applicationinsights.implementation.ComponentsClientImpl$ComponentsService.createOrUpdate - {"az.sdk.message":"HTTP response","statusCode":



P.S. Any statusCode not 200 in response maybe an issue.

**Comment by weidongxu-microsoft** [comment]
Not sure if this could be the cause.
https://github.com/Azure/azure-sdk-for-java/pull/31742

@Flanker32 Do we have such NPE in recent versions?
