### ISSUE TITLE
[FEATURE REQ]readMany FeedResponse responseHeaders has only 1 headers for request charge

### ISSUE THREAD

**Issue by SMohammed72** [Azure/azure-sdk-for-java#30110]
**Is your feature request related to a problem? Please describe.**

readMany FeedResponse responseHeaders has only 1 headers for request charge. For eg, the getDuration method of feedResponse is null.
readItem CosmosItemResponse has multiple(21) useful responseHeaders such x-ms-request-duration-ms and others.

**Describe the solution you'd like**

Can you please return all the headers for readMany similar to readItem method?

**Comment by SMohammed72** [comment]
Updating this issue as BUG, as the FeedResponse in readMany or query methods is not returning the duration.

**Comment by navba-MSFT** [comment]
Adding Service team to look into this,.

 @kushagraThapar, @TheovanKraay, @pjohari-ms Could you please look into this once you get a chance ?

**Comment by TheovanKraay** [comment]
@navba-MSFT we are working on it. This is part of our upcoming deliverables for the coming Semester (next 3 months).

**Comment by TheovanKraay** [comment]
closing as complete - see PR https://github.com/Azure/azure-sdk-for-java/pull/32290
