### ISSUE TITLE
Azure Data Lake Gen2 - Support for sending request InputStream created from in-memory object

### ISSUE THREAD

**Issue by stephenchartman** [Azure/azure-sdk-for-java#30125]
**Query/Question**
I'm implementing the Azure Data Lake Storage Gen2 Java SDK for a client that has specific requirements to send in-memory objects to their Azure data lake.  Upon reviewing the documentation [here](https://docs.microsoft.com/en-us/azure/storage/blobs/data-lake-storage-directory-file-acl-java) there is no guidance on whether or not it's feasible to create a stream from an in-memory object to send.

The process is triggered after an external integration call - we are attempting to send payloads as a result of the integration processing to the data lake.

Example code - utilizing a JVM language built on Java [reference here](https://gosu-lang.github.io/).
```
//Get payload from external service -- in-memory string
//Create DataLakeServiceClient
//Create DataLakeFileSystemClient
//Create DataLakeDirectoryClient
//Create filename for azure data lake
var requestFileClient : DataLakeFileClient
var requestTargetStream : InputStream
var requestFileSize : long
requestFileClient = directoryClient.getFileClient(filename)
requestTargetStream = new ByteArrayInputStream(requestPayload.getBytes(Charset.forName("UTF-8")))
requestFileSize = requestTargetStream?.readAllBytes().length
requestFileClient.upload(requestTargetStream, requestFileSize)

```

The resulting error is the following when testing in the remote staging environment:
`com.azure.core.exception.UnexpectedLengthException: Request body emitted 0 bytes, less than the expected 22521 bytes.`

Can azure-storage-file-datalake:12.10.1 support a request payload not generated from a file?

***Why is this not a Bug or a feature Request?***
The documentation only refers to uploading streams created from the file system.  The upload method does take a stream as a parameter but the documentation only indicates creating a stream from a java.io.File.

**Setup (please complete the following information if applicable):**
 - OS: Linux   (RedHat RHEL 7.8)
 - IDE: IntelliJ
 - Library/Libraries: com.azure:azure-storage-file-datalake 12.10.1
 
 **Information Checklist**
 Kindly make sure that you have added all the following information above and checkoff the required fields otherwise we will treat the issuer as an incomplete report
- [x] Query Added
- [x] Setup information Added

**Comment by joshfree** [comment]
Hi @stephenchartman thanks for reaching out via this GitHub issue; someone from the `storage sdk` team will follow up shortly

**Comment by rickle-msft** [comment]
@stephenchartman Yes, uploading from an in-memory stream is supported. The error you're seeing is indicating that the stream you passed completed after emitting 0 bytes when the length was specified as ~22kb

**Comment by rickle-msft** [comment]
Closing as I believe this was resolved offline. Please reopen or comment if I am mistaken about that.
