### ISSUE TITLE
[BUG] Make maxSize of StorageFileResource configurable

### ISSUE THREAD

**Issue by saragluna** [Azure/azure-sdk-for-java#30120]
**Is your feature request related to a problem? Please describe.**
When accessing the storage-file resource using `azure-file://some-share/some-file` in Spring, it will create the file if it doesn't exist. 
https://github.com/Azure/azure-sdk-for-java/blob/fd56dd2e4e5d8c037ae52b99d964cb4fe14cc8ee/sdk/spring/spring-cloud-azure-core/src/main/java/com/azure/spring/cloud/core/resource/StorageFileResource.java#L206-L219

But there's one problem with this file creation. It sets the `maxSize` of the file to `1024`, which is pretty small in average cases. This `maxSize` should be configurable. 

**Describe the solution you'd like**
Don't hard code the `1024` in file creation. Make it configurable instead. 

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Information Checklist**
Kindly make sure that you have added all the following information above and checkoff the required fields otherwise we will treat the issuer as an incomplete report
- [x] Description Added
- [x] Expected solution specified

**Comment by Docjones** [comment]
Hello,

are there any plans to address this issue?

**Comment by chenrujun** [comment]
Hi, @Docjones . 
Thanks for reaching out. Now we don't have ETA for this issue.

**Comment by Docjones** [comment]
Okay - thanks for clarifying - just one question: Why is it categorized as a "feature"? 
Our use-case is to store created jsons on a Azure File Storge Share, they are small, but some are bigger as the depicted 1024 bytes. It ends up with some files are ok, and some are throwing an errror. IMHO it should be treated as a bug.

**Comment by chenrujun** [comment]
@Docjones 
Your comment make sense. I changed it to `bug`.
