### ISSUE TITLE
Add OptionModule to JacksonAdapter to support patch operations

### ISSUE THREAD

**Issue by srnagar** [Azure/azure-sdk-for-java#30128]
[OptionModule](https://github.com/Azure/azure-sdk-for-java/blob/main/sdk/core/azure-core/src/main/java/com/azure/core/implementation/jackson/OptionModule.java) is currently [not included in the list of modules](https://github.com/Azure/azure-sdk-for-java/blob/main/sdk/core/azure-core/src/main/java/com/azure/core/implementation/jackson/ObjectMapperFactory.java#L136) that are added by default when creating `JacksonAdapter` instance. `OptionModule` is required for supporting Patch operations in models that use [Option](https://github.com/Azure/azure-sdk-for-java/blob/main/sdk/core/azure-core/src/main/java/com/azure/core/implementation/Option.java) type.

**Comment by Halsifer** [comment]
I'm currently trying to create a model that will be used for merging Azure Search documents. Without this OptionModule being included, it's not being serialized correctly. Is there another type that could be used in the meantime to support this tri-state value for merging search documents? 

Or will I have to pass a custom serializer that registers the OptionModule (as well as figure out a way to init the Iso8601DateDeserializer and access Iso8601DateSerializer) and pass that to the search client in the meantime?
