### ISSUE TITLE
[QUERY] Connect to EventHubs with different namespaces using spring-cloud-azure-starter-stream-eventhubs

### ISSUE THREAD

**Issue by ceremo** [Azure/azure-sdk-for-java#30132]
**Query/Question**
Is it posible to connect to EventHubs with different namespace using `spring-cloud-azure-starter-stream-eventhubs`? It seems that the configuration is defined under the `spring.cloud.azure.eventhub` namespace and only one connection can be defined.

***Why is this not a Bug or a feature Request?***
If it's not posible, it will be great to have it as a feature request.

**Setup (please complete the following information if applicable):**
 - Library/Libraries: spring-cloud-azure-starter-stream-eventhubs

**Comment by yiliuTo** [comment]
@ceremo  thanks for reaching us. You can use multiple binders to connect to different Event Hubs namespaces, here is a [sample](https://github.com/Azure-Samples/azure-spring-boot-samples/tree/spring-cloud-azure_4.3.0/eventhubs/spring-cloud-azure-stream-binder-eventhubs/eventhubs-multibinders).
