### ISSUE TITLE
Do we have any way to copy files/blobs from one storage account to another storage account in different region.

### ISSUE THREAD

**Issue by yashaswi90** [Azure/azure-sdk-for-java#30135]
I have one query like how to copy file share and container from one storage account to another storage account in different region?
Do we have any Azure SDK for this which will help in executing this task?

**Comment by yashaswi90** [comment]
Hi @rickle-msft is that same blobserviceclient.begincopy can we use it for File share, my query is for File share not for Container.

**Comment by rickle-msft** [comment]
It is possible to copy file -> file, file -> blob, blob -> blob, blob -> file. The destination is the target of the client being used to call the api. So some pseudocode would look like: 
```
BlobClient destinationClient = createBlobClient(destinationURL)
destinationClient.beginCopy(sourceUrl)
```

**Comment by yashaswi90** [comment]
In this it is mentioned clearly that it is not possible means complete storage account copy is not possible:-
https://github.com/Azure/azure-sdk-for-java/issues/10288

But Blob Client can be used to copy file →file, blob→ blob to another storage account under same subscription but in different region.

**Comment by rickle-msft** [comment]
@yashaswi90 The issue you linked is requesting a feature that the sdks iterate over an account and transfer data do another account. We will not be adding a feature to do bulk transfer. It is possible to copy a single blob or file to a destination blob or file in all permutations of that transfer. It is up to the user to write logic to determine which data they want to transfer and begin those transfers.

It looks first of all like you are trying to copy a blob. The source you specify is coming from a blob client, so I imagine it is a blob resource at the source. Secondly, you cannot copy an entire share. You can copy a single file

**Comment by yashaswi90** [comment]
@rickle-msft  Thank you for clarifying for file share.
