### ISSUE TITLE
Storage - Blobs Samples Issue

### ISSUE THREAD

**Issue by hongli750210** [Azure/azure-sdk-for-java#30157]
1.
**Section** [link](https://github.com/Azure/azure-sdk-for-java/blob/main/sdk/storage/azure-storage-blob/src/samples/java/com/azure/storage/blob/JavaDocCodeSnippetsHelpers.java#L21):
![image](https://user-images.githubusercontent.com/74638143/181172296-c0b09768-cdad-4090-a538-3fa3f92b3475.png)

**Reason**:
`BlobClient(com.azure.storage.blob.BlobAsyncClient)` has protected access in `com.azure.storage.blob.BlobClient`

**Suggestion**:
Change to `return getContainerClient().getBlobClient(blobName)`

2.
**Section** [link1](https://github.com/Azure/azure-sdk-for-java/blob/main/sdk/storage/azure-storage-blob/src/samples/java/com/azure/storage/blob/JavaDocCodeSnippetsHelpers.java#L10), [link2](https://github.com/Azure/azure-sdk-for-java/blob/main/sdk/storage/azure-storage-blob/src/samples/java/com/azure/storage/blob/JavaDocCodeSnippetsHelpers.java#L14):
![image](https://user-images.githubusercontent.com/74638143/181172611-36de8aaa-9c53-4cb7-ae30-44b59104baf7.png)

**Reason**:
Missing required parameters `endpoint` and `containerName` and `credential`.

**Suggestion**:
Add parameters
```
.endpoint("<YOUR_STORAGE_BLOB_SERVICE_ENDPOINT>")
.containerName("<YOUR_STORAGE_BLOB_CONTAINER_NAME>")
.credential(new DefaultAzureCredentialBuilder().build())
```

3.
**Section** [link1](https://github.com/Azure/azure-sdk-for-java/blob/main/sdk/storage/azure-storage-blob/src/samples/java/com/azure/storage/blob/JavaDocCodeSnippetsHelpers.java#L26), [link2](https://github.com/Azure/azure-sdk-for-java/blob/main/sdk/storage/azure-storage-blob/src/samples/java/com/azure/storage/blob/JavaDocCodeSnippetsHelpers.java#L30):
![image](https://user-images.githubusercontent.com/74638143/181173196-e72fc28a-d0b3-4bb8-9b0f-87cae90d476c.png)

**Reason**:
Missing required parameters `endpoint`  and `credential`.

**Suggestion**:
Change to 
```
.endpoint("<YOUR_STORAGE_BLOB_SERVICE_ENDPOINT>")
.credential(new DefaultAzureCredentialBuilder().build())
```

4.
**Section** [link](https://github.com/Azure/azure-sdk-for-java/blob/main/sdk/storage/azure-storage-blob/src/samples/java/com/azure/storage/blob/BlobContainerAsyncClientJavaDocCodeSnippets.java#L82):
![image](https://user-images.githubusercontent.com/74638143/181173499-83a08e63-40b9-4145-8d82-993d6ee24cb4.png)

**Reason**:
`existsWithResponse(com.azure.core.util.Context)` is not public in `com.azure.storage.blob.BlobContainerAsyncClient`. 

**Suggestion**:
Remove the code snippet for `BlobContainerAsyncClient#existsWithResponse(Context)`

@josefree, @kasobol-msft @kyle-patterson and @rickle-msft for notification.

**Comment by rickle-msft** [comment]
@hongli750210 Are you suggesting these changes because you're seeing build issues? Or for the purposes of doc improvements? These methods are all internal helper methods and these particular docs should build but aren't meant to be run.
