### ISSUE TITLE
[BUG] ARM getLogContent() doesn't return the full log contents.

### ISSUE THREAD

**Issue by smita-mohapatra** [Azure/azure-sdk-for-java#30152]
**Describe the bug**
I am using getLogContent method of ContainerGroups interface to get the complete log of azure container instance and save it before it gets deleted. But It does not fetch me the complete log. It just gives me the last part of the log. It does not have the data of when ACI got started.

***Exception or Stack Trace***
There is no exception. But it does not give the end to end log.

**To Reproduce**
1- Create an ACI
2- let it load the docker image and run for sometime.
3- collect the log by using getLogContent method 
4- Log wont have the loggers got executed very first. Means you will not get end to end log.

***Code Snippet***
@Autowired
	private AzureResourceManager azureResourceManager;

String logContent = azureResourceManager.containerGroups().getLogContent(<resourceGroupName>,
						<containerGroupName>, <containerName>);

**Expected behavior**
I expect end to end log of operations performed inside the azure container instance. not only the last part of the log.

**Screenshots**

**Setup (please complete the following information):**
 - OS: Linux (ubuntu 20.04)
 - IDE: Eclipse
 - Library/Libraries: 
 <dependency>
			<groupId>com.azure.resourcemanager</groupId>
			<artifactId>azure-resourcemanager</artifactId>
			<version>2.14.0</version>
		</dependency>
 - Java version: jdk-13.0.2
 - App Server/Environment: [Deployed in Azure VM - Linux (ubuntu 20.04) ]
 - Frameworks: Spring Boot

**Comment by joshfree** [comment]
@weidongxu-microsoft could you please follow up with @smita-mohapatra?

**Comment by weidongxu-microsoft** [comment]
This seems to be backend behavior, on returning latest log, instead of all history.

@XiaofeiCao to investigate.

**Comment by XiaofeiCao** [comment]
Hi @smita-mohapatra 

Have you tried the overload with `tailLineCount` parameter?

https://github.com/Azure/azure-sdk-for-java/blob/2cd30e97440042b17a94db3438865ed530fb4c08/sdk/resourcemanager/azure-resourcemanager-containerinstance/src/main/java/com/azure/resourcemanager/containerinstance/models/ContainerGroup.java#L154-L162

Pass in `Integer.MAX_VALUE` as second parameter. My test shows it does return more logs than the one without `tailLineCount`. (3000 lines of logs)

If you did and still can't get the full log, we may want to let service team confirm this behavior.
