### ISSUE TITLE
Digital Twins - Core Samples issue

### ISSUE THREAD

**Issue by hongli750210** [Azure/azure-sdk-for-java#30153]
1.
**Section** [link](https://github.com/Azure/azure-sdk-for-java/blob/main/sdk/digitaltwins/azure-digitaltwins-core/src/samples/java/com/azure/digitaltwins/core/DigitalTwinsLifecycleAsyncSample.java#L159): 
![image](https://user-images.githubusercontent.com/74638143/181171866-8751bfa6-86ea-4a71-83ee-06d027a51ee4.png)

**Reason**:
`listIncomingRelationships(java.lang.String, com.azure.core.util.Context)` is not public in `com.azure.digitaltwins.core.DigitalTwinsAsyncClient`. Cannot be accessed from outside package.

**Suggestion**:
Change to `listIncomingRelationships(twinId)`

@josefree, @johngallardo and @sjiherzig for notification.

**Comment by johngallardo** [comment]
Investigating.

**Comment by johngallardo** [comment]
https://github.com/Azure/azure-sdk-for-java/pull/30382
