### ISSUE TITLE
[FEATURE REQ] Burst Capacity support in CosmosDB in Java SDK

### ISSUE THREAD

**Issue by SMohammed72** [Azure/azure-sdk-for-java#30163]
As part of Walmart CosmosDB user of this Java SDK, I would like to request the burst capacity support as listed in the page below.

https://docs.microsoft.com/en-us/azure/cosmos-db/burst-capacity

**Comment by TheovanKraay** [comment]
Closing as old issue - burst capacity is supported for all SDKs.
