### ISSUE TITLE
[BUG] First DLQ message disappears

### ISSUE THREAD

**Issue by KnyGoo** [Azure/azure-sdk-for-java#30191]
**Describe the bug**
When we deadletter messages, our first message dissapears. This seems like a major bug...

***Exception or Stack Trace***
No stack trace

**To Reproduce**
- Make sure there are no messages on DLQ
- Add 10 new messages to queue
- Start my sample code (this code receives 10 messages and will deadletter them all)
=> Only 9 messages are on DLQ

***Code Snippet***
```
ClientSecretCredential clientSecretCredential =
                new ClientSecretCredentialBuilder()
                        .tenantId("...")
                        .clientId("...")
                        .clientSecret("...")
                        .executorService(Executors.newCachedThreadPool())
                        .build();

        ServiceBusProcessorClient processorClient = new ServiceBusClientBuilder()
                .credential("...", clientSecretCredential)
                .transportType(AmqpTransportType.AMQP_WEB_SOCKETS)
                .processor()
                .receiveMode(ServiceBusReceiveMode.PEEK_LOCK)
                .disableAutoComplete()
                .queueName("...")
                .maxConcurrentCalls(1)
                .maxAutoLockRenewDuration(Duration.ofSeconds(10))
                .processMessage(context -> {
                    System.out.printf("Received message from queue: %s%n", context.getMessage().getMessageId());
                    context.deadLetter();
                })
                .processError(context -> {
                })
                .buildProcessorClient();

        System.out.println("Starting the processor");
        processorClient.start();

        TimeUnit.SECONDS.sleep(200);
        System.out.println("Stopping and closing the processor");
        processorClient.close();
```

**Expected behavior**
All messages should be on the DLQ. I expect 10 messages, but got only 9.

**Screenshots**
/

**Setup (please complete the following information):**
 - OS: Windows
 - IDE: IntelliJ
 - Library/Libraries: com.azure:azure-messaging-servicebus:7.10.0
 - Java version: 17
 - App Server/Environment: Tomcat
 - Frameworks: Spring Boot

**Additional context**
/

**Information Checklist**
Kindly make sure that you have added all the following information above and checkoff the required fields otherwise we will treat the issuer as an incomplete report
- [x] Bug Description Added
- [x] Repro Steps Added
- [x] Setup information Added

**Comment by joshfree** [comment]
Hi @KnyGoo thanks for reaching out to us via this GitHub issue.  @ki1729 from the `Service Bus SDK` team will follow up with you shortly.

One quick comment, you mentioned `com.azure:azure-messaging-servicebus:7.10.0` this version is over 1 year old - would you mind trying to upgrade to the latest released and supported version?  Newer versions have performance, reliability, and security updates (https://github.com/Azure/azure-sdk-for-java/blob/main/sdk/servicebus/azure-messaging-servicebus/CHANGELOG.md).

Thanks

**Comment by KnyGoo** [comment]
Hi @joshfree,

7.10.0 is the latest stable release, 7.11.0 is still beta...

**Comment by KnyGoo** [comment]
Hi @joshfree,

Any updates?

**Comment by KnyGoo** [comment]
Hi @joshfree,

Any updates?

**Comment by ki1729** [comment]
Hi @KnyGoo Sorry for the delay in the response here. Thank you for sharing the repro code and setup information. I tried to repro the exact same scenario as the one you described, and I was not successful.
All 10 messages were deadlettered successfully.  For all of them I see the following logs messages
```
Received message from queue: 360dfd17519c4421a4936ce1267b0e17
DEBUG [boundedElastic-2] c.a.m.s.ServiceBusReceiverAsyncClient.performLogging(355) | {"az.sdk.message":"Update started.","lockToken":"982079eb-dde8-4640-96df-2c251fa48bf2","entityPath":"credsTest","sessionId":null,"dispositionStatus":"SUSPENDED"}
DEBUG [reactor-executor-1] c.a.c.a.i.h.ReceiveLinkHandler.performLogging(355) | {"az.sdk.message":"onDelivery.","connectionId":"MF_8c26af_1667356829233","errorCondition":null,"errorDescription":null,"entityPath":"credsTest","linkName":"credsTest_c91631_1667356829295","updatedLinkCredit":0,"remoteCredit":0,"delivery.isPartial":false,"delivery.isSettled":false}
DEBUG [reactor-executor-1] c.a.m.s.i.ServiceBusReactorReceiver.performLogging(355) | {"az.sdk.message":"Received update disposition delivery.","entityPath":"credsTest","linkName":"credsTest_c91631_1667356829295","lockToken":"982079eb-dde8-4640-96df-2c251fa48bf2","deliveryState":"Rejected{error=null}"}
```

All the messages are getting their state updated successfully to `Rejected`. And I can see all 10 of them in the dead letter queue as well.

If this issue is happening for you on every run, (or when it happens) can you please capture the debug logs of the SDK and send them my way? I would love to dig in further and see what's happening.
