### ISSUE TITLE
[Bug] too many pull requests send to Service Bus from spring-cloud-azure-starter-servicebus-jms library

### ISSUE THREAD

**Issue by yiliuTo** [Azure/azure-sdk-for-java#30192]
**Query/Question**
When using the `@JmsListener` API with `spring-cloud-azure-starter-servicebus-jms` library, customers observed there are ongoing and high value of requests of `tryReceive` call sending from the `spring-cloud-azure-starter-servicebus-jms` library to Azure Service Bus even there are no messages in the broker. From the customer's application, the request rate is 250/min.

Here the `tryReceive` call is a request type that is received on the server side, which stands for pull-message requests.

**Customer scenario**

1. Library version and framework:
   - [Maven Repository: org.springframework.boot » spring-boot-starter-parent » 2.7.1 (mvnrepository.com)](https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fmvnrepository.com%2Fartifact%2Forg.springframework.boot%2Fspring-boot-starter-parent%2F2.7.1&data=05%7C01%7Cyiliu6%40microsoft.com%7Caf93c003884040db5f7408da7ffbf92c%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C637963017451527537%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=R8aUw91YH2w7DGpm%2FNG05l0AcAyD5K%2FVbZEB4wsvgVU%3D&reserved=0)
   - [Maven Repository: com.azure.spring » spring-cloud-azure-starter-servicebus-jms » 4.3.0 (mvnrepository.com)](https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fmvnrepository.com%2Fartifact%2Fcom.azure.spring%2Fspring-cloud-azure-starter-servicebus-jms%2F4.3.0&data=05%7C01%7Cyiliu6%40microsoft.com%7Caf93c003884040db5f7408da7ffbf92c%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C637963017451527537%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=kaHiL3Nxux6XjelGV3XUgbDVddIssa1Uj5mQKTuiQpo%3D&reserved=0)
2. API:
   - Using @JmsListener to receive messages from Service Bus topic subscription.
3. Configuration:
    connection-string: Endpoint=xyz;SharedAccessKeyName=test-key-name;SharedAccessKey=key;EntityPath=path
    topic-client-id: topic-client-id
    client-Id: TestConnection
    topic: topicName
    subscription: subscriptionName
    idle-timeout: 20000
    pricing-tier: standard
4. Env
   The application is deployed on AKS with replica number as 2.

***Why is this not a Bug or a feature Request?***
`@JmsListener` API with `spring-cloud-azure-starter-servicebus-jms` by default leverages `DefaultJmsListenerContainer` to pull messages from Service Bus, so to have background pull request might be normal by default. 

But there are still some gaps that why the request number can reach 250/min, and if we can change the volume or the pull-message behavior? We need to investigate them.

**Comment by yiliuTo** [comment]
Customer application information:
1. Library version and framework:
   - [Maven Repository: org.springframework.boot » spring-boot-starter-parent » 2.7.1 (mvnrepository.com)](https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fmvnrepository.com%2Fartifact%2Forg.springframework.boot%2Fspring-boot-starter-parent%2F2.7.1&data=05%7C01%7Cyiliu6%40microsoft.com%7Caf93c003884040db5f7408da7ffbf92c%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C637963017451527537%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=R8aUw91YH2w7DGpm%2FNG05l0AcAyD5K%2FVbZEB4wsvgVU%3D&reserved=0)
   - [Maven Repository: com.azure.spring » spring-cloud-azure-starter-servicebus-jms » 4.3.0 (mvnrepository.com)](https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fmvnrepository.com%2Fartifact%2Fcom.azure.spring%2Fspring-cloud-azure-starter-servicebus-jms%2F4.3.0&data=05%7C01%7Cyiliu6%40microsoft.com%7Caf93c003884040db5f7408da7ffbf92c%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C637963017451527537%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=kaHiL3Nxux6XjelGV3XUgbDVddIssa1Uj5mQKTuiQpo%3D&reserved=0)
2. API:
   - Using @JmsListener to receive messages from Service Bus topic subscription.
3. Configuration:
    connection-string: Endpoint=xyz;SharedAccessKeyName=test-key-name;SharedAccessKey=key;EntityPath=path
    topic-client-id: topic-client-id
    client-Id: TestConnection
    topic: topicName
    subscription: subscriptionName
    idle-timeout: 20000
    pricing-tier: standard
4. Project structure: 
   -  Helm is being used to deploy a container into an AKS.

**Comment by hui1110** [comment]
When using two applications to connect to the Service Bus, the requests are close to 250/min. For each additional application, the requests increase by about 120.

As shown below:

![image](https://user-images.githubusercontent.com/58474919/191648216-9f8a3565-ce52-4a3f-b835-3c3960bf29a5.png)

**Comment by hui1110** [comment]
Add the following properties to the configuration:

```properties
spring.jms.listener.receive-timeout=
```

When timeout < 0 then it should stay open until a message is received. timeout = 0 then it returns a message, if no timeout > 0 is available then it should stay open for the timeout period. Gives a positive timeout value in milliseconds.

**Comment by hui1110** [comment]
Use [arthas ](https://arthas.aliyun.com/doc/quick-start.html)to monitor the number of executions of the method [schedule](https://github.com/apache/qpid-jms/blob/main/qpid-jms-client/src/main/java/org/apache/qpid/jms/provider/amqp/AmqpConsumer.java#L202) which is the same as the number of requests on the Service Bus.

**Comment by stliu** [comment]
- [ ] reproduce issue
- [ ] expected behavior

**Comment by hui1110** [comment]
Use the following environment to try to reproduce the issue.

**Environment 1**
- Spring Boot version: 2.7.3
- Java version: 11
- spring-cloud-azure-starter-servicebus-jms: **4.3.0**
- Windows 11
- Azure Spring Apps

**Project used**: https://github.com/Azure-Samples/azure-spring-boot-samples/tree/spring-cloud-azure_v4.4.1/servicebus/spring-cloud-azure-starter-servicebus-jms/servicebus-jms-topic

**Scenarios**

 Library | Platform 
 -- | --
spring-cloud-azure-starter-servicebus-jms | Azure Spring Apps
spring-cloud-azure-starter-servicebus-jms | Windows 11

**Expect**

The [timeout ](https://github.com/spring-projects/spring-boot/blob/main/spring-boot-project/spring-boot-autoconfigure/src/main/java/org/springframework/boot/autoconfigure/jms/JmsProperties.java#L163)for answering calls defaults to 1 second. View Metrics in Service Bus, the number of requests should be around 60 per minute.

**Check**

- After starting the Spring Boot application in Windows, check the Metrics of Service Bus, around 90. As shown below: 
<img width="892" alt="image" src="https://user-images.githubusercontent.com/58474919/201005139-a85a6c6a-ba4a-4d10-856f-1fba33ff539f.png">

- After deploying the Spring Boot application to Azure Spring Apps, check the Metrics of Service Bus, which is around 120. As shown below:

**Comment by yiliuTo** [comment]
@hui1110 I still have some doubts towards your reproducing information:
1. Since there is "Environment 1", so can I expect other different environments?
2. Please confirm that the library of `spring-cloud-azure-starter-servicebus-jms` you are using are 4.3.0 or 4.4.1.
3. Please confirm that whether you deployed the project to ASA or AKS? I believe that we have decided using AKS for the reproduction.
4. Assuming you used ASA, could you provide the configuration information of your ASA service?
5. For your local test env, please provide information about the number, memory of your CPU.
6. The expected behavior is not clear, what does the timeout mean? Could you provide the complete description. And why will it be related with the number of requests?
7. For the chart of Service Bus metrics, there are multiple metrics you are showing , which one stands for the tryReceive call we are talking about?
8. Assuming you are using ASA, it's ok that you don't provide another chart to show the number since you might not have that env right now. But please delete the uncompleted sentence `As shown below:`.

**Comment by yiliuTo** [comment]
### Cause analysis
`@JmsListener` underlyingly is a [polling listener](https://github.com/spring-projects/spring-framework/blob/v5.3.24/spring-jms/src/main/java/org/springframework/jms/listener/AbstractPollingMessageListenerContainer.java#L45) which is built for repeated polling attempts.

The listener sits on an ongoing loop of polling, each invoking the JMS [MessageConsumer.receive()](https://github.com/javaee/jms-spec/blob/master/jms1.0.1a/src/share/javax/jms/MessageConsumer.java#L134) to poll the local consumer for messages to consume. The concrete message-polling process is decided by several properties including `receiveTimeout`, `prefetchSize` and `receiveLocalOnly`, the process flow is described in the below picture:

![jms-pull](https://user-images.githubusercontent.com/63028776/209067980-b9b24d30-24c9-43ba-a898-93bf4eb02532.jpg)

In the customer's case which is also the default configuration, it is case 2.1 that for each receive() call, it sends pull requests to Service Bus. Therefore, the client keeps sending pull request in a loop. And the frequency is up to the CPU status, performance and how many tasks to be handled, which can influence how fast to run a loop. That's why Yonghui can reproduce the similar number of requests as the customer on Azure, but when running his own local machine, the request number varies.

**Comment by yiliuTo** [comment]
## Solution
For how to deal with the issue, there are several solutions:

### Solution 1. Change to push consumer and local-check only. 

To accomplish it, users can add the following configuration:
First, configure the prefetch number to be non-zero, there are several prefetch properties each controls different Service Bus entities, users should choose ones that applies with their cases:

   ```properties
   spring.jms.servicebus.prefetch.all=<Fallback value for prefetch option in this Service Bus namespace>
   spring.jms.servicebus.prefetch.queue-prefetch=<The number of prefetch for queue.>
   spring.jms.servicebus.prefetch.queue-brower-prefetch=<The number of prefetch for queue browser.>
   spring.jms.servicebus.prefetch.topic-prefetch=<The number of prefetch for topic.>
   spring.jms.servicebus.prefetch.durable-topic-prefetch-=<The number of prefetch for durable topic.>
   ```

   Second, configure the non-locl-check by adding a configuration class for the factory customizer:
   ```java
   @Configuration(proxyBeanMethods = false)
   public class CustomJmsConfiguration {

       @Bean
       ServiceBusJmsConnectionFactoryCustomizer customizer() {
           return factory -> {
               factory.setReceiveLocalOnly(true);
               // Configure the below ReceiveNoWaitLocalOnly instead if you have specified the property 
               // spring.jms.listener.receive-timeout with negative value. Otherwise, configure the above `ReceiveLocalOnly`.
               //factory.setReceiveNoWaitLocalOnly(true);
           };
       }
   }
   ```
   By applying the above configuration, the consumer is now an `Asynchronous Notification` consumer that it doesn't pull messages from the broker, but maintains a target amount of link credit decided by the prefeth.  As Service Bus(sender) pushes messages, the sender’s link-credit decreases and when the sender’s link-credit falls below a threshold, the client will increase the sender’s linkcredit back to the desired target amount.

   So the value of prefetch can affect how fast messages are dispatched to the consumer's local buffer. Users should adjust the value according to their consuming performance and message volumes. Suitable value can speed up the consuming process, while too larget prefeth can cause the locally buffered messages are outdated and be dispatched again. For low message volumes, where each message takes a long time to process, the prefetch should be set to 1. This ensures that a consumer is only processing one message at a time.

### Solution 2. Change the waiting time to extend each pull-blocking time.

This is to reduce the pulling frequency if users choose to use the pull mode still. To accomplish is, users can configure the below property, which is of `java.time.Duration` type and the default value is 1 second.
```properties
spring.jms.listener.receive-timeout=
```
The meaning of the value is 

> Seting the receive-timeout as 0, means the pull blocks infinitely till a message is dispatched.
> Setting the receive-timeout as positive value, means the pull blocks up to timeout amount of time.
> Setting the receive-timeout as negative value, means the pull is a `no-wait receive` , it returns a message immediately or null if none available.

However, this will also extend the time when the main thread is in a block status, which means the container will be less responsive to stop() calls - the container can only stop between receive().

**Comment by yiliuTo** [comment]
Hints about how to read the request metrics in Azure Portal for Service Bus:
1. Difference between `sum` and `count`:
Referring to the [doc](https://learn.microsoft.com/azure/azure-monitor/essentials/metrics-aggregation-explained#aggregation-types), the `sum` aggregation means how many requests were collected in the last interval. While `count` presents how many measurement were capured in the interval. So the sum can be caculated by adding the results of each measurement happened in an interval.

2. What is the aggregation interval?
Service Bus sends data to metrics pipeline at 1 min aggregation. But when you view the metrics in the portal based the total interval you choose the metrics are aggregated to fit in the interval. For example, if you pick 30 days duration then it may have to use daily aggregation to fit the samples in the graph. If you pick 24 hours duration then it may have to pick hourly aggregation. Aggregation window changes automatically based on the duration.
A quick way to figure out the interval with your current chart is to view it as a scatter chart, and the interval between two adjacent records is the actual aggregation interval.

**Comment by yiliuTo** [comment]
Close this issue since both the cause and solution is clear now.
