### ISSUE TITLE
[QUERY] Form Recognizer: Generic error during training when triggered using Java SDK, model trains successfully via form recognizer studio

### ISSUE THREAD

**Issue by mathias-vandencruijce** [Azure/azure-sdk-for-java#30196]
**Query/Question**
I'm having trouble getting the Java SDK for form recognizer to properly trigger training, I keep getting the following error:

`
com.azure.ai.formrecognizer.models.FormRecognizerException: Invalid model created with model Id [modelId], errorCode: [3014], message: Generic error during training.
`

This is the code I'm using to generate the sas and begin training:

`           BlobContainerSasPermission permission = new BlobContainerSasPermission()
                                                        .setReadPermission(true)
                                                        .setWritePermission(true)
                                                        .setExecutePermission(true)
                                                        .setListPermission(true)
                                                        .setAddPermission(true)
                                                        .setCreatePermission(true)
                                                        .setDeletePermission(true)
                                                        .setMovePermission(true)
                                                        .setTagsPermission(true)
                                                        .setDeleteVersionPermission(true);`
           
` BlobServiceSasSignatureValues values = new BlobServiceSasSignatureValues(OffsetDateTime.now().plusDays(1), permission)
                    .setStartTime(OffsetDateTime.now());`

`            String sas = "https://{name}.blob.core.windows.net/{containerName}" + blobContainerClient.generateSas(values);`
 

`SyncPoller<FormRecognizerOperationResult, CustomFormModel> trainingPoller = formTrainingClient.beginTraining(sas, useTrainingLabels, new TrainingOptions().setModelName(modelName), Context.NONE);`

`CustomFormModel customFormModel = trainingPoller.getFinalResult();`

***Why is this not a Bug or a feature Request?***
I assume the implementation of the beginTraining method works judging by the fact that it was released as part of a stable build, I just cannot get it to work, I assume I'm doing something wrong with the SAS URL, but cannot figure out what.

**Setup (please complete the following information if applicable):**
 - OS: Windows
 - IDE: IntelliJ
 - Library/Libraries: 
   - com.azure:azure-ai-formrecognizer:3.1.11
   - com:azure:azure-storage-blob:12.13.0
 
 **Information Checklist**
 Kindly make sure that you have added all the following information above and checkoff the required fields otherwise we will treat the issuer as an incomplete report
- [x] Query Added
- [x] Setup information Added

**Comment by joshfree** [comment]
Hi @mathias-vandencruijce thank you for reaching out to us via this GitHub issue.  @samvaity could you please follow up with @mathias-vandencruijce on this question?

**Comment by samvaity** [comment]
@mathias-vandencruijce Thank you for reaching out. I gave this API a try and couldn't reproduce the error. Could it be related to the specific resource/storage URL you are dealing with (Incorrect/Faulty data) ?
Also, we have noticed that the error "Generic error.." could also be a flaky error from the service.
I would suggest giving it a try again and let us know if the issue persists.

**Comment by mathias-vandencruijce** [comment]
@samvaity Thanks for reaching out and sorry for the late response. The training data itself should not be the problem, considering I can successfully train with the exact same data using the form recognizer studio. As for a faulty URL, I'm not too sure, like I said in my original post, I'm not sure if the method I'm employing to dynamically generate a SAS URL for the FormTrainingClient to use to trigger training is actually generating a correctly formed URL that FormRecognizer can use. From what I can tell from the documentation it should be, yet the issue still persists. Could you confirm whether or not my method of forming a SAS URL for the SDK to use actually works for you?

**Comment by samvaity** [comment]
@mathias-vandencruijce Are you using the same method generated SAS Url in the Form recognizer studio and does it work there?
>Could you confirm whether or not my method of forming a SAS URL for the SDK to use actually works for you?

Could you give me this method and I can try it?

I think as far as the SAS URL generated is of the below format you should be good.
```
https://storagesamples.blob.core.windows.net/sample-container/blob1.txt?se=2019-08-03&sp=rw&sv=2018-11-09&sr=b&skoid=<skoid>&sktid=<sktid>&skt=2019-08-02T2
2%3A32%3A01Z&ske=2019-08-03T00%3A00%3A00Z&sks=b&skv=2018-11-09&sig=<signature>
```

**Comment by mathias-vandencruijce** [comment]
@samvaity This is the code I'm using to generate the SAS and attempt to start training (I assume not all these permissions are needed, but I've temporarily added them for testing purposes)
> ` BlobContainerSasPermission permission = new BlobContainerSasPermission() .setReadPermission(true) .setWritePermission(true) .setExecutePermission(true) .setListPermission(true) .setAddPermission(true) .setCreatePermission(true) .setDeletePermission(true) .setMovePermission(true) .setTagsPermission(true) .setDeleteVersionPermission(true);`
> 
> ` BlobServiceSasSignatureValues values = new BlobServiceSasSignatureValues(OffsetDateTime.now().plusDays(1), permission) .setStartTime(OffsetDateTime.now());`
> 
> ` String sas = "https://{name}.blob.core.windows.net/{containerName}" + blobContainerClient.generateSas(values);`
> 
> `SyncPoller<FormRecognizerOperationResult, CustomFormModel> trainingPoller = formTrainingClient.beginTraining(sas, useTrainingLabels, new TrainingOptions().setModelName(modelName), Context.NONE);`
> 
> `CustomFormModel customFormModel = trainingPoller.getFinalResult();`

**Comment by samvaity** [comment]
@mathias-vandencruijce Could you also share the code for `blobContainerClient` creation that could also affect the generation of the SAS URL.?

**Comment by mathias-vandencruijce** [comment]
@samvaity Below is the code I'm using to create the blobcontainerclient (the containerName variable is a String I get from elsewhere in my code):
`BlobContainerClient blobContainerClient = blobServiceClient.getBlobContainerClient(containerName);`
`if (!blobContainerClient.exists()) {`
`    blobContainerClient = blobServiceClient.createBlobContainer(container);`
`}`

**Comment by samvaity** [comment]
@mathias-vandencruijce I was able to reproduce the error. 
I also get the same results from a REST API call for the generated SAS using the above method.
The generated SAS also doesn't look valid for Form Recognizer studio either:
<img width="230" alt="image" src="https://user-images.githubusercontent.com/16845631/186733866-9f26afdb-ff89-48d2-a707-67168446ba27.png">

So it's definitely an issue the way SAS URL is generated. 
This is more documentation on how to generate the SAS correctly: https://docs.microsoft.com/en-us/rest/api/storageservices/delegate-access-with-shared-access-signature

**Comment by samvaity** [comment]
I also tried the same SAS URL with useTrainingLabels = false, and notice a different error :
```json
"errors": [
            {
                "code": "2012",
                "message": "Unable to list blobs on the Azure blob storage account."
            }
        ]
```
This error suggests the provided SAS URL does not "list" permission enabled.

**Comment by samvaity** [comment]
@mathias-vandencruijce Could you confirm if the issue still exists?

**Comment by mathias-vandencruijce** [comment]
@samvaity Sorry for the late response. I mistakenly thought I'd already closed this issue. I ended up restructuring my project which meant that I could change the way I'm generating the SAS Url's and using them and the blob storage. Now eveything works as intended and I can trigger training successfully, thanks for your help.
