### ISSUE TITLE
Checkstyle + Spotbugs fixes in Storage code

### ISSUE THREAD

**Issue by g2vinay** [Azure/azure-sdk-for-java#3021]

**Comment by sima-zhu** [comment]
All spotbugs are in PR.

**Comment by sima-zhu** [comment]
Spotbugs PR:
common: https://github.com/Azure/azure-sdk-for-java/pull/3284 (Merged)
auth: https://github.com/Azure/azure-sdk-for-java/pull/3329 (Merged)
mgmt: https://github.com/Azure/azure-sdk-for-java/pull/3342 (Review)

**Comment by sima-zhu** [comment]
Waiting for storage merged in their preview branch.

**Comment by sima-zhu** [comment]
Commit 1:
Fixed the spotbugs error. Organize the imports for checkstyle. #3484

Commit 2:
Continue working on Checkstyle.

**Comment by sima-zhu** [comment]
Spotbugs fix in #3507 
Checkstyle fix comes after in another commit.

**Comment by sima-zhu** [comment]
All errors reported by spotbugs and checkstyle will document to issue #3506

**Comment by sima-zhu** [comment]
Code merged in. Resolved the issue.
