### ISSUE TITLE
Getting Microsoft.Azure.WebJobs.Extensions.Storage: Unable to convert trigger to IStorageQueueMessage.

### ISSUE THREAD

**Issue by rshubham** [Azure/azure-sdk-for-java#30218]
**Query/Question**

I'm trying to use @QueueTrigger for testing my Azure Function locally, but while triggering it from

> http://localhost:8080/admin/functions/my-queue-trigger

I'm getting this error:

```
[2022-07-31T15:39:45.203Z] System.Private.CoreLib: Exception while executing function: Functions.my-queue-trigger. Microsoft.Azure.WebJobs.Host: Exception binding parameter 'request'. Microsoft.Azure.WebJobs.Extensions.Storage: Unable to convert trigger to IStorageQueueMessage.
```

Code:

```
@FunctionName("my-queue-trigger")
    public void run(
            @QueueTrigger(
                    name = "request",
                    queueName = "my-queue",
                    connection = "storage-conn-string"
            ) String request,
            final ExecutionContext context) {
        // logic
    }
```

I'm setting storage-conn-string in local.settings.json file as well. Could you please help where I'm going wrong?

***Why is this not a Bug or a feature Request?***
This issue is related to understanding of @QueueTrigger

**Setup (please complete the following information if applicable):**
 - OS: macOS
 - IDE: IntelliJ
 - Library/Libraries: com.microsoft.azure.functions: azure-functions-java-library:2.0.0
 
 **Information Checklist**
 Kindly make sure that you have added all the following information above and checkoff the required fields otherwise we will treat the issuer as an incomplete report
- [. ] Query Added
- [ .] Setup information Added

**Comment by navba-MSFT** [comment]
@rshubham Apologies for the late reply. Thanks for reaching out to us and reporting this issue. We are looking into this issue and we will provide an update.

**Comment by navba-MSFT** [comment]
@rshubham If I create an Azure Function (.NET 6, Functions v4, in-process) like this:

```
public class QueueTriggerExample 
{
    [FunctionName("QueueTriggerExample")]
    public void Run([QueueTrigger("myqueue-items")] string myQueueItem, ILogger log)
    {
        log.LogInformation($"C# Queue trigger function processed: {myQueueItem}");
    }
}
```

I can successfully make an HTTP POST to invoke the function.

```
POST http://localhost:7071/admin/functions/QueueTriggerExample HTTP/1.1 
Content-Type: application/json
```

>{"input": "sample queue data"}

We also have a sample on Github, hopefully it will be helpful for you to compare and figure out what went wrong : 

Queue trigger in-proc function 
[cloud-native-serverless/QueueFunction.cs at main · cloudmelon/cloud-native-serverless (github.com)](https://github.com/cloudmelon/cloud-native-serverless/blob/main/azure-functions/local-af-inproc-queue-keda/QueueFunction.cs)

A C# based message sender built with Queue trigger SDK ( sending 2000 messages to Azure Queue and then triggering the function 
[cloud-native-serverless/Program.cs at main · cloudmelon/cloud-native-serverless (github.com)](https://github.com/cloudmelon/cloud-native-serverless/blob/main/message-sender/MessageSender/Program.cs)

Hope this helps.

**Comment by navba-MSFT** [comment]
@rshubham I hope you had a chance to look at my above comment. The action is currently pending on you to try the suggestion mentioned above. If you need any further assistance on this issue in future, please feel free to reopen this thread. We would be happy to help.
