### ISSUE TITLE
Record/Playback Integration in Storage code

### ISSUE THREAD

**Issue by g2vinay** [Azure/azure-sdk-for-java#3022]
High level Strategy to integrate Record Playback followed in Java Central Repo:
1. Take dependency on following libraries 
<dependency> 
    <groupId>com.microsoft.azure</groupId> 
    <artifactId>azure-mgmt-resources</artifactId> 
    <scope>test</scope> 
</dependency> 
 
<dependency> 
    <groupId>com.microsoft.azure</groupId> 
    <artifactId>azure-mgmt-resources</artifactId> 
    <type>test-jar</type> 
    <scope>test</scope> 
</dependency> 

<dependency> 
    <groupId>com.microsoft.rest</groupId> 
    <artifactId>client-runtime</artifactId> 
</dependency> 
 

<dependency> 
    <groupId>com.microsoft.azure</groupId> 
    <artifactId>azure-client-runtime</artifactId> 
</dependency> 
 

2. Update the Test Base Class 
In the Test Base class where service client is instantiated. In @BeforeMethod, perform Rest client setup based on the test mode: Record/Playback. 

In Record mode, rest client needs to be setup in a way similar to this. You need to pass your custom RestClient to the service client(Keyvault, Storage etc.) 

 interceptorManager = InterceptorManager.create(testName.getMethodName(), testMode); 
  RestClient restClient; 
  ServiceClientCredentials credentials = createTestCredentials(); 
  if (isRecordMode()) { 
           restClient = buildRestClient(new RestClient.Builder().withBaseUrl(<Service/Resource Endpoint URL>) 
      .withSerializerAdapter(new AzureJacksonAdapter()) 
      .withResponseBuilderFactory(new AzureResponseBuilder.Factory()).withCredentials(credentials) 
      .withLogLevel(LogLevel.NONE) 
      .withNetworkInterceptor(new LoggingInterceptor(LogLevel.BODY_AND_HEADERS)) 
      .withNetworkInterceptor(interceptorManager.initInterceptor()) 
      .withInterceptor(new ResourceManagerThrottlingInterceptor())); 
  -- Utilize this Rest Client to instantiate the service client (e.g KeyvaultClient) 
  } else{ 
      //Playback mode 
      restClient = new RestClient.Builder().withBaseUrl("http://localhost:<PORT-CONFIGURED>") 
      .withSerializerAdapter(new AzureJacksonAdapter()) 
      .withResponseBuilderFactory(new AzureResponseBuilder.Factory()).withCredentials(credentials) 
      .withLogLevel(LogLevel.NONE) 
      .withNetworkInterceptor(new LoggingInterceptor(LogLevel.BODY_AND_HEADERS)) 
      .withNetworkInterceptor(interceptorManager.initInterceptor()) 
      .withInterceptor(new ResourceManagerThrottlingInterceptor()).build(); 
  -- Utilize this Rest Client to instantiate the service client (e.g KeyvaultClient) 
  } 

3. In the afterMethod,  
Call, interceptorManager.finalizeInterceptor(); 
-- This step writes the recorded test to a file in record mode, which is used to playback the test later.

**Comment by sima-zhu** [comment]
Successfully ran the live tests for storage.
https://dev.azure.com/azure-sdk/playground/_build/results?buildId=28127

Breakdowns:
1. Add necessary test base for one test case, make it run in playback mode.
2. Run all tests.

**Comment by sima-zhu** [comment]
Proposal is ready:
https://microsoft-my.sharepoint.com/personal/sizhu_microsoft_com/Documents/Proposal_storage_playback.pptm?web=1

**Comment by sima-zhu** [comment]
The recode json files has successfully generated. 26 of 1078 tests failed.
https://dev.azure.com/azure-sdk/playground/_build/results?buildId=33918&view=ms.vss-test-web.build-test-results-tab&runId=1217924&resultId=100349&paneView=debug

Needs to figure out the reason of failing.

**Comment by sima-zhu** [comment]
Put along the failed record tests into the second part. Worked on successful ones. Make playback tests run on the success record tests.

**Comment by sima-zhu** [comment]
Phase 1: Storage API level PR: #3782 
Phase 2: Storage Func tests.
Phase 3 Transfer Manager

**Comment by sima-zhu** [comment]
PR out for all the tests: https://github.com/Azure/azure-sdk-for-java/pull/3793
