### ISSUE TITLE
Queue trying to recover despite active consumer

### ISSUE THREAD

**Issue by anshul733** [Azure/azure-sdk-for-java#30237]
For past few days we saw that, one queue which has schdeduling enabled has got messages piling up and the Azure Kubernetes (AKS )Sprint boot consumer is not able consume all of them. In our AKS consumer app, the log is coming as

"A JMS MessageConsumer has been closed: JmsConsumerInfo: { ID:48d2e6b3-9b29-4fb2-846a-32b7a184e77b:80:1:1, destination = recon.q }"

Setup of JMS message listener invoker failed for destination 'recon.q' - trying to recover. Cause: The Session was closed due to an unrecoverable error.

we are using Spring boot (v2.6.6) JMS consumer, the JMS dependencies listed are as

    
    <dependency>
        <groupId>org.springframework</groupId>
        <artifactId>spring-jms</artifactId>
        <version>5.3.18</version>
        </dependency>
    <dependency>
        <groupId>org.apache.qpid</groupId>
        <artifactId>qpid-jms-client</artifactId>
        <version>1.6.0</version>
        </dependency>
    <dependency>
        <groupId>org.apache.geronimo.specs</groupId>
        <artifactId>geronimo-jms_2.0_spec</artifactId>
        <version>1.0-alpha-2</version>
    </dependency>

**Comment by joshfree** [comment]
Hi @anshul733, @yiliuTo from the `Azure Spring` team will follow up with you shortly.

**Comment by yiliuTo** [comment]
@anshul733 this error looks like the connection/session to Service Bus is broken, Service Bus can close amqp connection/links automatically for some cases, you can refer [here](https://docs.microsoft.com/azure/service-bus-messaging/service-bus-amqp-troubleshoot). Could you provide more information about your application, including which Spring JMS API you are using to consume messages (sample code may be more helpful), do you have any custom configuration properties/code for Spring JMS, and are there other error logs for more information?
