### ISSUE TITLE
[QUERY] EventHubProducerClient.createBatch() throws timeout exception

### ISSUE THREAD

**Issue by Yasara-Y** [Azure/azure-sdk-for-java#30256]
**Query/Question**
I'm following the guide [here](https://docs.microsoft.com/en-us/java/api/overview/azure/messaging-eventhubs-readme?view=azure-java-stable) to create an EventHubProducerClient . When I try creating an EventDataBatch to send my data, I get the below error:

```
Timeout on blocking read for 60000000000 NANOSECONDS java.lang.IllegalStateException: Timeout on blocking read for 60000000000 NANOSECONDS| 
at reactor.core.publisher.BlockingSingleSubscriber.blockingGet(BlockingSingleSubscriber.java:123) ~[reactor-core-3.4.12.jar:3.4.12]| 
at reactor.core.publisher.Mono.block(Mono.java:1731) ~[reactor-core-3.4.12.jar:3.4.12]| 
at com.azure.messaging.eventhubs.EventHubProducerClient.createBatch(EventHubProducerClient.java:128) ~[azure-messaging-eventhubs-5.7.0.jar:?]| 
```

But some batches are created successfully and published to eventhub. Only some events drop when trying to create a batch.

Below is the code snippet used to create eventbatch and send eventdata to azure eventhub.
```

        List<EventData> allEvents = new ArrayList<>();
        allEvents.add(new EventData(jsonString));

        // Create a batch.
        EventDataBatch eventDataBatch = producer.createBatch();     // Note: The Error is triggered here.

        for (EventData eventData : allEvents) {
            // Try to add the event from the array to the batch.
            if (!eventDataBatch.tryAdd(eventData)) {
                // If the batch is full, send it and then create a new batch.
                producer.send(eventDataBatch);
                eventDataBatch = producer.createBatch();
                // Try to add that event that couldn't fit before.
                if (!eventDataBatch.tryAdd(eventData)) {
                    throw new IllegalArgumentException("Event is too large for an empty batch. Max size: "
                            + eventDataBatch.getMaxSizeInBytes());
                }
            }
        }
        // Send the last batch of remaining events.
        if (eventDataBatch.getCount() > 0) {
            producer.send(eventDataBatch);
        }
        if (LOG.isDebugEnabled()) {
            LOG.debug("Published user login event.");
        }
```

Whats the root cause and how to resolve this issue?

**Comment by conniey** [comment]
Can you provide some DEBUG logs? The exception only shows that it was trying to create a batch and timed out.  See: [Filing GitHub issues](https://github.com/Azure/azure-sdk-for-java/blob/main/sdk/eventhubs/azure-messaging-eventhubs/TROUBLESHOOTING.md#filing-github-issues)

**Comment by aaronkorver** [comment]
Since you asked on #8763 our problem was regarding dependencies.  However, I would triple check the network path that it is open from your client to the eventhub.  That is most likely your issue.  You can set debug level for the logging level and see what extra is logged out to help
