### ISSUE TITLE
Support AzureSasCredential in ServiceBusAdministrationClientBuilder

### ISSUE THREAD

**Issue by Satyabhama-Reddy** [Azure/azure-sdk-for-java#30255]
In Service Bus SDK, unlike ServiceBusClientBuilder, ServiceBusAdministrationClientBuilder does not support connecting with AzureSasCredential using the credential method. Is there a plan to add that?

**Comment by joshfree** [comment]
@ki1729 could you please follow up with @Satyabhama-Reddy on their service bus sdk question?

**Comment by ki1729** [comment]
@Satyabhama-Reddy Thanks for reporting this. Yes we are planning to add this in the next release (November 2022).
