### ISSUE TITLE
[BUG] Cosmos Change Feed Processor is Detaching / Stopping Silently

### ISSUE THREAD

**Issue by azizabah** [Azure/azure-sdk-for-java#30261]
**Describe the bug**
We are utilizing the com.azure.cosmos.ChangeFeedProcessor to subscribe to changes in Cosmos. This works great for roughly 5-6 hours.  After that time, the change feed processor silently stops receiving updates from Cosmos.

***Exception or Stack Trace***
No exceptions are raised. The code seems to stop silently.

***Code Snippet***
```
@Service
class CosmosChangeFeedProcessor(
    @Qualifier("azureCosmosAsyncClient") val cosmosClient: CosmosAsyncClient,
    val businessService: ServiceImpl
) {
    companion object {
            private val logger = LoggerFactory.getLogger(this::class.java)
        }

    var isProcessorRunning = AtomicBoolean(false)
    @Value("\${POD_NAME:local}")
    lateinit var podName : String

    fun getChangeFeedProcessor(
        hostName: String?,
        feedContainer: CosmosAsyncContainer?,
        leaseContainer: CosmosAsyncContainer?
    ): ChangeFeedProcessor {
        val cfOptions = ChangeFeedProcessorOptions()
        cfOptions.isStartFromBeginning = false
        cfOptions.leasePrefix = "$podName-" //We want unique leases per running instance in AKS
        return ChangeFeedProcessorBuilder()
            .options(cfOptions)
            .hostName(hostName)
            .feedContainer(feedContainer)
            .leaseContainer(leaseContainer)
            .handleChanges {
                refresh()
            }
            .buildChangeFeedProcessor()
    }

    private fun refresh() {
        businessService.doStuff()
    }

    @EventListener(ApplicationReadyEvent::class)
    fun startChangeFeedProcessor() {
        logger.info("Starting change feed processor.")
        val changeFeedProcessorInstance = getChangeFeedProcessor("ChangeFeed",
            getContainerReference(DATA_CONTAINER_NAME),
            getContainerReference(LEASES_CONTAINER_NAME))
        changeFeedProcessorInstance.start()
            .subscribeOn(Schedulers.boundedElastic())
            .doOnSuccess { isProcessorRunning.set(true) }
            .doOnError { isProcessorRunning.set(false) }
            .subscribe()

        while (!isProcessorRunning.get());
        logger.info("Change feed processor started.")
    }

    fun getContainerReference(containerName: String) : CosmosAsyncContainer {
        val dbLink = cosmosClient.getDatabase(DATABASE_NAME)
        return dbLink.getContainer(containerName)
    }
}
```

I tried creating a SB Health Actuator to reference the isProcessorRunning variable but that continues to return true even when the change feed processor has stopped receiving changes.

**Expected behavior**
I would expect either an exception/error to be thrown that we could utilize the .doOnError() functionality to restart or that the Cosmos Change Processor would not detach.

**Setup (please complete the following information):**
 - Library/Libraries: 
 - Spring Boot 2.6.7
 - com.azure.spring:spring-cloud-azure-starter-data-cosmos
 - com.azure.spring:spring-cloud-azure-dependencies:4.0.0
 - com.azure:azure-cosmos
 - com.azure:azure-sdk-bom:1.1.0
 

- Java version: 11
 - App Server/Environment: [Undertow, AKS]
 - Frameworks: [Spring Boot] 

**Information Checklist**
Kindly make sure that you have added all the following information above and checkoff the required fields otherwise we will treat the issuer as an incomplete report
- [X] Bug Description Added
- [] Repro Steps Added
- [X] Setup information Added

**Comment by kushagraThapar** [comment]
@azizabah - is there any error in the logs? 
do you have info logs enabled on Change Feed processor?
Change feed processor only listens to create and replace / upsert operations, delete and read operations are not included. Please do take a look at these troubleshooting steps - https://docs.microsoft.com/en-us/azure/cosmos-db/sql/change-feed-processor?tabs=java#error-handling-1

it could be stopping because of unhandled error in your code.

**Comment by azizabah** [comment]
> @azizabah - is there any error in the logs? do you have info logs enabled on Change Feed processor? Change feed processor only listens to create and replace / upsert operations, delete and read operations are not included. Please do take a look at these troubleshooting steps - https://docs.microsoft.com/en-us/azure/cosmos-db/sql/change-feed-processor?tabs=java#error-handling-1
> 
> it could be stopping because of unhandled error in your code.

- There are no errors that we can see. Is there a specific error message we should be looking for?
- The processor is failing to see updates / creates. 

As for the unhandled error, if the handleChanges consumer call throws an exception, that would stop the processing? We can wrap that call in a try catch to prevent it from leaking anything to the processor as a first step.

**Comment by azizabah** [comment]
@kushagraThapar . We went ahead and wrapped the call in a try catch. We haven't seen any exceptions being caught in our logs but it appears to have stabilized and has run for two days without detaching now so that must have been the issue. Thanks for the assistance.

**Comment by kushagraThapar** [comment]
@azizabah thanks for the update, feel free to reopen the issue in case you need any further assistance.
