### ISSUE TITLE
[QUERY] App Configuration - Still requires bootstrap properties?

### ISSUE THREAD

**Issue by azizabah** [Azure/azure-sdk-for-java#30260]
**Query/Question**
Does usage of the Azure App Configuration library for Spring Boot still require usage of a bootstrap.yml/bootstrap.properties file? This functionality has been deprecated since Spring Boot 2.4. 
```
Bootstrap, provided by spring-cloud-commons, is no longer enabled by default. If your project requires it, it can be re-enabled by properties or by a new starter.

To re-enable by properties set spring.cloud.bootstrap.enabled=true or spring.config.use-legacy-processing=true. These need to be set as an environment variable, java system property or a command line argument.
The other option is to include the new spring-cloud-starter-bootstrap.
```
https://github.com/spring-cloud/spring-cloud-release/wiki/Spring-Cloud-2020.0-Release-Notes#breaking-changes

***Why is this not a Bug or a feature Request?***
I am trying to understand if we are still required to implement the deprecated/fallback functionality in Spring Boot to read bootstrap properties. It would be preferable if this could be setup as another property source similar to the new setup for Azure Key Vault (com.azure.spring:spring-cloud-azure-starter-keyvault-secrets). 

**Setup (please complete the following information if applicable):**
 - Library/Libraries:
 - Java 11
 - Spring Boot 2.6.7
 - com.azure.spring:azure-spring-cloud-appconfiguration-config-web:2.8.0
 
 **Information Checklist**
 Kindly make sure that you have added all the following information above and checkoff the required fields otherwise we will treat the issuer as an incomplete report
- [X] Query Added
- [X] Setup information Added

**Comment by moarychan** [comment]
Hi @mrm9084 , please take a look.

**Comment by mrm9084** [comment]
@azizabah Are you referring to this https://docs.microsoft.com/en-us/azure/developer/java/spring-framework/configure-spring-boot-starter-java-app-with-azure-key-vault#create-the-app-with-spring-initializr. @saragluna If I understand correctly that library just creates a Key Vault Client that can be used and doesn't integrate with the Spring Config system, where the App Configuration library generates property sources for it.

`spring-cloud-azure-starter-appconfiguration` works like the key vault one listed, but doesn't have any of the features that the other library has.

There is a plan to update to the newer configuration system, but that is in the backlog at the moment. The App Configuration library uses `spring-cloud-starter-bootstrap` which isn't deprecated yet, but is being transitioned away from.

**Comment by saragluna** [comment]
@mrm9084 the Key Vault starter provides two functionalities, one is to auto-configure a KV secret client, and another is to use KV as property sources.

**Comment by azizabah** [comment]
@mrm9084 @saragluna - We are utilizing Key Vault as a property source and it's working great. 

The main question was around whether bootstrap is required or not which it sounds like it is because @mrm9084 mentioned that changing the behavior is still in the backlog. 

Thanks for the information.

**Comment by mrm9084** [comment]
We recently released version 6 which should fix this issue: https://learn.microsoft.com/en-us/azure/azure-app-configuration/howto-convert-to-the-new-spring-boot. If this is still an issue, please create a new issue. Thanks.
