### ISSUE TITLE
mgmt, upgrade service bus api-version to `package-2021-11`

### ISSUE THREAD

**Issue by XiaofeiCao** [Azure/azure-sdk-for-java#30267]
link https://github.com/Azure/azure-sdk-for-java/issues/27617

**Comment by XiaofeiCao** [comment]
specs has changed some resource type from `Resource` to `ProxyResource`, resulting in compile issue in `IndependentChildResourceImpl`:
https://github.com/Azure/azure-sdk-for-java/blob/7255d6cbb39a9a7f3dceddbb29c6ed319b936865/sdk/resourcemanager/azure-resourcemanager-resources/src/main/java/com/azure/resourcemanager/resources/fluentcore/arm/models/implementation/IndependentChildResourceImpl.java#L26-L33

@weidongxu-microsoft Do we need the type bound `Resource` here ? In `IndependentChildResourcesImpl`, it is not enforeced:
https://github.com/Azure/azure-sdk-for-java/blob/ad9d5a4290e60a2cfa94790632f3f45c003248e3/sdk/resourcemanager/azure-resourcemanager-resources/src/main/java/com/azure/resourcemanager/resources/fluentcore/arm/collection/implementation/IndependentChildResourcesImpl.java#L22-L29

**Comment by weidongxu-microsoft** [comment]
You can try remove it, but I imagine it is used somehow (id or name)?

**Comment by weidongxu-microsoft** [comment]
Also mind the note
```
    "note": "Add '@JsonSerialize(using = DurationSerializer.class)' to properties of 'Duration' type of class 'SBTopicInner', 'SBQueueInner', 'SBSubscriptionInner'"
```

**Comment by XiaofeiCao** [comment]
Right, implementation does use these properties. I'll change it back and add an additional note on this.
