### ISSUE TITLE
LinkageError: Package versions: jackson-annotations=2.12.3, jackson-core=2 .12.3, jackson-databind=2.12.3, jackson-dataformat-xml=2.13.3, jackson-datatype-jsr310=2 .11.2, azure-core=1.30.0, Troubleshooting version conflicts: https://aka.ms/azsdk/java/dependency/troubleshoot

### ISSUE THREAD

**Issue by inesessetti** [Azure/azure-sdk-for-java#30280]
Hi,
You can find the dependencies I'm using below

build.sbt :

```
`ThisBuild / version := "0.1"

ThisBuild / scalaVersion := "2.12.12"

lazy val root = (project in file("."))
  .enablePlugins(PackPlugin)
  .settings(
    name := "data-loading",
  )


libraryDependencies ++= Seq(
  "org.apache.spark" %% "spark-core" % "3.2.1",
  "org.apache.spark" %% "spark-sql" % "3.2.1",
  "com.datastax.spark" %% "spark-cassandra-connector" % "3.2.0",
  "com.datastax.spark" %% "spark-cassandra-connector-driver" % "3.2.0",
  "com.datastax.cassandra" % "cassandra-driver-core" % "3.11.2",
  "com.azure" % "azure-storage-file-datalake" % "12.11.0",
  "com.azure" % "azure-storage-common" % "12.17.0"
)
`
```

Please, can you help me with this ? Thank you !

**Comment by joshfree** [comment]
@alzimmermsft could you please follow up with @inesessetti on their Azure SDK for Java question?

**Comment by inesessetti** [comment]
@alzimmermsft @joshfree I found the solution, thanks)

**Comment by dsab123** [comment]
Hey @inesessetti , would you be able to post your solution here? I'm running into the same issue. Thanks!

**Comment by inesessetti** [comment]
Hi
So the solution I found to solve the issue is to see all the dependency
tree imported with the dependency used. I think I've used maven
dependency:tree. Then I had to change the version of some dependencies so
that all the versions of imported dependencies are the same and doesn't
cause any conflicts.

Le mar. 15 nov. 2022 à 23:08, Daniel Sabbagh ***@***.***> a
écrit :
