### ISSUE TITLE
[BUG] AppServicePlan numberOfWebApps and operatingSystem() returns wrong values

### ISSUE THREAD

**Issue by rnaval** [Azure/azure-sdk-for-java#30287]
**Describe the bug**
For an AppServicePlan, calling `numberOfWebApps()` always returns 0.

Also, calling `operatingSystem()` always returns `WINDOWS` even if the OS is Linux.

**To Reproduce**
Steps to reproduce the behavior: call the aforementioned methods and check the values

***Code Snippet***
```
    protected Map<String, String> getAttributes(AppServicePlan resource) {
...
        attributes.put("number_of_web_apps", String.valueOf(resource.numberOfWebApps())); -> Always 0
        attributes.put("operating_system", resource.operatingSystem().name()); -> Always WINDOWS
        return attributes;
    }
```

**Expected behavior**
The above methods should return the correct values (actual number of sites for `numberOfWebApps`, and `Linux` for apps using Linux as their OS)

**Setup (please complete the following information):**
 - OS: macOS 12 Monterey
 - IDE: IntelliJ
 - Library/Libraries: com.microsoft.azure:azure-mgmt-appservice:1.41.4
 - Java version: 11

**Additional context**
Did a bit of tracing, and it seems that this was fixed before in this issue https://github.com/Azure/azure-sdk-for-java/issues/1861

Specifically, by this PR (at least for the operatingSystem issue): https://github.com/Azure/azure-sdk-for-java/pull/1873/files#diff-e852fd3b4bbf68e3ae66dfbc2ecbced2b2c45f493af8c6bacb902db2e18abfeaL75

Current code level does not have this fix - any idea why?

**Comment by joshfree** [comment]
Thanks for reporting this issue, @rnaval. @weidongxu-microsoft could you please follow up?

**Comment by weidongxu-microsoft** [comment]
@rnaval 

com.microsoft.azure:azure-mgmt-appservice:1.41.4 was deprecated

Does the bug exist in https://aka.ms/azsdk/java/mgmt

**Comment by rnaval** [comment]
@weidongxu-microsoft I haven't checked yet - migration to the new SDK is still ongoing. 

As an aside, I thought that the old libraries would be deprecated by March 2023: https://azure.github.io/azure-sdk/releases/deprecated/index.html - as such, will it still receive support until then?

**Comment by weidongxu-microsoft** [comment]
@rnaval 

Old lib was deprecated on March 2022.

Support will continue to 2023, however bug fix or release (after the fix) could be slow.

**Comment by rnaval** [comment]
@weidongxu-microsoft Thanks for the info. We are currently in the process of upgrading to the new library, but we are still supporting applications that rely on the old library until 2023.

I'll let you know if we get the new lib test results.

**Comment by weidongxu-microsoft** [comment]
2.17 works fine.

```java
            var appObj = azure.appServicePlans().getByResourceGroup("rg-weidxu", "ASP-rgweidxu-bf61");
            System.out.println("os: " + appObj.operatingSystem());
            System.out.println("no. of webapps: " + appObj.numberOfWebApps());
```

output
```
os: linux
no. of webapps: 1
```
