### ISSUE TITLE
How to customize this value

### ISSUE THREAD

**Issue by LuyTech** [Azure/azure-sdk-for-java#30288]
I don't want to wait so long time to get the summarization result, need to customize the value.
https://github.com/Azure/azure-sdk-for-java/blob/e77d29a5d71cc37b73b3e1abb1034a65a2130c11/sdk/textanalytics/azure-ai-textanalytics/src/main/java/com/azure/ai/textanalytics/implementation/Utility.java#L156

**Comment by joshfree** [comment]
@samvaity could you follow up with @LuyTech on this?

**Comment by samvaity** [comment]
@LuyTech you should be able to use `setPollInterval()` on the PollerFlux directly to customize the polling interval on the calling API.
