### ISSUE TITLE
[FEATURE REQ] Support single-container access in azure-storage-blob-nio

### ISSUE THREAD

**Issue by jgainerdewar** [Azure/azure-sdk-for-java#30297]
**Is your feature request related to a problem? Please describe.**
We are trying to extend an existing NIO-using software product to run in Azure, including using Blob storage as a backing filesystem. Due to the architecture of our larger environment, our application only has access to a single Blob container, not an entire storage account. As far as we can tell we are unable to use the Azure Blob NIO library at all, since we do not have an account-level SAS token.

**Describe the solution you'd like**
I would like to be able to create an NIO filesystem by passing in a container-level SAS token. This would result in a filesystem that could not perform container-level operations in the storage account.

**Describe alternatives you've considered**
We considered obtaining access to a storage account rather than a container, but due to the limit on number of storage accounts per region per subscription, this doesn't meet our organization's needs. 

**Additional context**

**Information Checklist**
Kindly make sure that you have added all the following information above and checkoff the required fields otherwise we will treat the issuer as an incomplete report
- [x] Description Added
- [x] Expected solution specified

**Comment by rickle-msft** [comment]
@jgainerdewar Thank you for opening this issue! I think this should be possible as we have in the past enabled support for accessing even a single file. If you have a sas token to a container and use that as your authentication method, do you get an error back?

**Comment by jgainerdewar** [comment]
Thanks for the quick response! I saw single-blob access described in the docs as a possible future feature and assumed it wasn't working yet. 

Yes, currently we get a `403` error the says "This request is not authorized to perform this operation." with initial cause "java.io.IOException: There was an error in establishing the existence of container: <containerName>'". The same SAS token works when connecting to the container in the desktop Storage Explorer app, so I believe the token itself is correct. Maybe there's a different permission that needs to be set on the token when creating it?

**Comment by rickle-msft** [comment]
Interesting. So when the FileSystem is being loaded, we try to do a head request, and if there's nothing there, a createContainer. If either of those fail, we'll throw with the exception message you're seeing. Since you're getting an auth failure, I suspect you don't have permissions for one of those actions. You'll need read permission for the head request, and, if you're specifying a container that doesn't already exist, you'll need create permissions to create the container

**Comment by jgainerdewar** [comment]
Alright, we know the container already exists (and in our case we can assume it always will), so we'll look into whether we have permission for the head request. We don't expect to have permission to do things like list the blob containers in the storage account, since we only have access to a single container. My colleague @kraefrei will follow up!

**Comment by kraefrei** [comment]
@rickle-msft following up from last week, I have verified that we are getting this error even with the read (and create) permission are there through a provided BlobContainerSasPermission object. We are working with an existing container, however I also tried requesting a new container that would need to be created for completeness and we observe the same error. Does this error usually indicate an issue with the permissions on the BlobContainerSasPermission object alone or could this indicate that there are other signature values we are missing?

**Comment by rickle-msft** [comment]
Can you share a sample sas token you are using (but redact the signature and the names of any resources)? With that I can make some requests on my end and see what's going on.

**Comment by kraefrei** [comment]
Sure thing! Here is an example: sv=2021-06-08&spr=https&st=2022-08-09T12%3A42%3A38Z&se=2022-08-09T13%3A57%3A38Z&sr=c&sp=racwdl&sig={signature}

**Comment by rickle-msft** [comment]
Hi, @kraefrei. Thank you for providing the sample. I was able to verify the behavior you're seeing. It looks like it's because a service sas can't actually grant permission to read properties on a container, which is required for our validation step. There is a way around this, which is to specify the `AzureStorageSkipInitialContainerCheck` option in your config map. As long as you're confident the container exists, there shouldn't be any issue with skipping the connection check. Please let me know if you have any issues with this

**Comment by kraefrei** [comment]
That worked for us! For our use case we should be able to guarantee that the container exists, so we'll use this work around for now.

**Comment by rickle-msft** [comment]
Glad to hear it! In this case, that option was specifically added to support sas tokens that don't have permissions to perform this check, so it is a supported feature that you should be able to rely on :)
