### ISSUE TITLE
[QUERY] RegionalAuthority support in Azure identity

### ISSUE THREAD

**Issue by leonard520** [Azure/azure-sdk-for-java#30321]
**Query/Question**
RegionalAuthority is a feature in https://github.com/AzureAD/microsoft-authentication-library-for-java
I find it was once supported in 
https://github.com/Azure/azure-sdk-for-java/blob/main/sdk/identity/azure-identity/CHANGELOG.md#140-beta1-2021-09-13
but removed later in 
https://github.com/Azure/azure-sdk-for-java/blob/main/sdk/identity/azure-identity/CHANGELOG.md#140-2021-10-14

Is it due to there once a bug in `microsoft-authentication-library-for-java` side?

However, recently the bug should be fixed in 1.12.0 and the sdk has also raise the version. Is there any plan to add the feature support back?
https://github.com/AzureAD/microsoft-authentication-library-for-java/releases/tag/v1.12.0

***Why is this not a Bug or a feature Request?***
I am wondering if any reason azure identity don't allow to set the regional value?

**Setup (please complete the following information if applicable):**
 - IDE: [e.g. IntelliJ]
 - Library/Libraries: [e.g. com.azure:azure-core:1.16.0 (groupId:artifactId:version)]
 
 **Information Checklist**
 Kindly make sure that you have added all the following information above and checkoff the required fields otherwise we will treat the issuer as an incomplete report
- [x] Query Added
- [ ] Setup information Added

**Comment by joshfree** [comment]
@billwert could you please follow up with @leonard520?  /cc @schaabs

**Comment by leonard520** [comment]
Anybody can help to take a look? Thanks!

**Comment by leonard520** [comment]
Do we have a plan to add the feature back? Without it, we are not able to use regional ESTS. Thanks.

**Comment by billwert** [comment]
We don’t have plans to release the APIs we previously added to specify the ESTS-R region. ESTS-R configuration is only allowed in 1st party applications, and 3rd party applications get errors from the ESTS when they add this configuration, which can be difficult to understand as they contain concepts only familiar to 1st party developers. Because of this we decided not to GA these APIs to avoid confusion for external Azure developers.
