### ISSUE TITLE
[FEATURE REQ] Support Multiple Spring Versions for Spring Cloud Azure ITs

### ISSUE THREAD

**Issue by Netyyyy** [Azure/azure-sdk-for-java#30336]
### Context
Currently, Spring Cloud Azure IT only tests the latest Spring version, make sure to test the version we declared supported

### Goal
Find a reasonable way to support multiple Spring versions

**Comment by saragluna** [comment]
Closed in https://github.com/Azure/azure-sdk-for-java/pull/41170
