### ISSUE TITLE
[FEATURE REQ] Update quick-start doc of Spring Data JDBC with SQL Database to include passwordless connection

### ISSUE THREAD

**Issue by saragluna** [Azure/azure-sdk-for-java#30342]
### Context

The driver of SQL Database has already supported Azure AD authentication, we should update our quickstart doc of [Spring quickstart SQL Database JDBC] to include the passwordless connection method. Since this driver doesn't support `DefautAzureCredential`, we can only mention how to use Managed Identity and service principals. 

There's a template worked out by Alex can be found here:
- https://github.com/MicrosoftDocs/azure-docs-pr/pull/203348#issuecomment-1205727432
- https://github.com/MicrosoftDocs/azure-docs-pr/pull/203348#issuecomment-1203381358

We should demo two connection methods in this doc, one using passwordless connections and one using username/password, using contextual tabs to distinguish them. We should make the credential-free tab as the default/recommended.

### Goal
Update the quick-start doc to include the passwordless part. 

[Spring quickstart SQL Database JDBC]: https://docs.microsoft.com/en-us/azure/developer/java/spring-framework/configure-spring-data-jdbc-with-azure-sql-server

**Comment by saragluna** [comment]
https://github.com/MicrosoftDocs/azure-dev-docs-pr/pull/3511

**Comment by Netyyyy** [comment]
Close this issue since the pr has been closed and the content has merged.
