### ISSUE TITLE
[FEATURE REQ] Update quick-start doc of Spring Kafka to include passwordless connection

### ISSUE THREAD

**Issue by saragluna** [Azure/azure-sdk-for-java#30345]
### Context

We already shipped the quickstart doc of Kafka using credential-free connection, but we need to modify it according to the new template. 

There's a template worked out by Alex can be found here:
- https://github.com/MicrosoftDocs/azure-docs-pr/pull/203348#issuecomment-1205727432
- https://github.com/MicrosoftDocs/azure-docs-pr/pull/203348#issuecomment-1203381358

We should demo two connection methods in this doc, one using passwordless connections and one using username/password, using contextual tabs to distinguish them. We should make the passwordless tab as the default/recommended.

### Goal
Update the quick-start doc to include the passwordless part. 

[Spring quickstart Kafka]: https://docs.microsoft.com/en-us/azure/developer/java/spring-framework/configure-spring-cloud-stream-binder-java-app-kafka-azure-event-hub

**Comment by yiliuTo** [comment]
Close this issue since the pr has been closed and the content has merged.
