### ISSUE TITLE
[FEATURE REQ] Make the Spring CLoud Azure support Spring Boot 3.0

### ISSUE THREAD

**Issue by moarychan** [Azure/azure-sdk-for-java#30356]
### Context
As the Spring Boot 3.0.0.M4 is available at https://start.spring.io/, the Spring Cloud Azure code should be compatible with the milestone version. Do the changes according to the previous sprint of the [spike research](https://github.com/Azure/azure-sdk-for-java/issues/29230).

### Goal
Source code is ready in the main branch to release the Spring Cloud Azure 6.0.0.M1 version, which means the source code is at least verified through the ci, tests, and compatibility-tests pipelines.

**Comment by anbusampath** [comment]
curious to know is there a plan to release Spring Cloud Azure 5.x? because current version is Spring Cloud Azure 4.4.x. Spring Boot 3 compatible marked as Spring Cloud Azure 6.0.0.M1.

**Comment by moarychan** [comment]
@anbusampath , thanks for your attention!

The Spring Cloud Azure 4.x will continue to support the current Spring Boot 2.7.x and later. Currently, we initially discuss skipping version 5.x and using 6.x to support Spring Boot 3, the major version 5 is reserved for the current Spring Cloud Azure 4.x, which may not be used if there are no major changes.

**Comment by moarychan** [comment]
The code is merged to branch https://github.com/Azure/azure-sdk-for-java/tree/feature/spring-cloud-azure-6.x.
