### ISSUE TITLE
[BUG] DataLakeFileClient.uploadFromFile() times out at 60 secs even when duration is specified

### ISSUE THREAD

**Issue by ptownsen** [Azure/azure-sdk-for-java#30406]
**Description**
Attempting to upload large files to Azure Datalake container.  The method uploadFromFile() in the DataLakeFileClient consistently throws exception java.util.concurrent.TimeoutException:  Channel response timed out after 60000 milliseconds.

***Exception or Stack Trace***
```
reactor.core.Exceptions$ReactiveException: java.util.concurrent.TimeoutException: Channel response timed out after 60000 milliseconds.
	at reactor.core.Exceptions.propagate(Exceptions.java:392)
	at reactor.core.publisher.BlockingSingleSubscriber.blockingGet(BlockingSingleSubscriber.java:137)
	at reactor.core.publisher.Mono.block(Mono.java:1731)
	at com.azure.storage.common.implementation.StorageImplUtils.blockWithOptionalTimeout(StorageImplUtils.java:193)
	at com.azure.storage.file.datalake.DataLakeFileClient.uploadFromFile(DataLakeFileClient.java:485)
	at com.litens.etl.datalake.TestUpload.uploadToAzureStorage(TestUpload.java:59)
	at com.litens.etl.datalake.TestUpload.main(TestUpload.java:25)
	Suppressed: java.lang.Exception: #block terminated with an error
		at reactor.core.publisher.BlockingSingleSubscriber.blockingGet(BlockingSingleSubscriber.java:139)

Caused by: java.util.concurrent.TimeoutException: Channel response timed out after 60000 milliseconds.
	at com.azure.core.http.netty.implementation.ResponseTimeoutHandler.responseTimedOut(ResponseTimeoutHandler.java:58)
	at com.azure.core.http.netty.implementation.ResponseTimeoutHandler.lambda$handlerAdded$0(ResponseTimeoutHandler.java:45)
	at io.netty.util.concurrent.PromiseTask.runTask(PromiseTask.java:98)
	at io.netty.util.concurrent.ScheduledFutureTask.run(ScheduledFutureTask.java:153)
	at io.netty.util.concurrent.AbstractEventExecutor.runTask(AbstractEventExecutor.java:174)
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:167)
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:470)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:503)
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997)
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.base/java.lang.Thread.run(Thread.java:833)
```

**To Reproduce**
See sample code below

***Code Snippet***
```
public void uploadToAzureStorage(File file) throws FileNotFoundException
{
    String fileName = file.getName();
    String endPoint = "https://mydatalake.dfs.core.windows.net/datalake-file-system/qsys-data-export/" + fileName;
    String sasToken = "?sv=2021-06-08&ss=abcdefghijklmnopqrstuvwxyz=mysas";
    String fileSystemName = "datalake-file-system";

    DataLakeFileClient fileClient = new DataLakePathClientBuilder()
        .endpoint(endPoint)
        .sasToken(sasToken)
        .fileSystemName(fileSystemName)
        .buildFileClient();
    
    PathHttpHeaders headers = new PathHttpHeaders()
        .setContentMd5("data".getBytes(StandardCharsets.UTF_8))
        .setContentLanguage("en-US")
        .setContentType("binary");
    Long blockSize = 100L * 1024L * 1024L; // 100 MB;
    ParallelTransferOptions parallelTransferOptions = new ParallelTransferOptions().setBlockSizeLong(blockSize);
    Map<String, String> metadata = Collections.singletonMap("metadata", "value"); 
    DataLakeRequestConditions requestConditions = new DataLakeRequestConditions();  
    Duration timeout = Duration.ofMinutes(10);
    
    LocalDateTime start = LocalDateTime.now();
    System.out.println("Start upload: " + start);
    fileClient.uploadFromFile(file.getAbsolutePath(), parallelTransferOptions, headers, metadata, requestConditions, timeout);
    LocalDateTime end = LocalDateTime.now();
    System.out.println("End upload: " + end);
}

```
**Expected behavior**
File should upload to blob storage in the data lake container.  Smaller files make it no problem, but files above 500 MB throw the timeout error.

**Setup (please complete the following information):**
 - OS: Windows 10 20H2
 - IDE: Visual Studio Code 64-bit
 - Library/Libraries: com.azure; azure-storage-file-datalake-12.11.0, com.azure; azure-storage-blob-12.18.0
 - Java version: 11.0.15 64-bit

**Information Checklist**
Kindly make sure that you have added all the following information above and checkoff the required fields otherwise we will treat the issuer as an incomplete report
- [ ] Bug Description Added
- [ ] Repro Steps Added
- [ ] Setup information Added

**Comment by rickle-msft** [comment]
Hi, @ptownsen. Thank you for posting this issue. Is this every time you upload a file of this size? Or only periodically?

**Comment by ptownsen** [comment]
Hi @rickle-msft,
This occurs everytime I upload a large file.

**Comment by rickle-msft** [comment]
@ptownsen Ok. I will try your sample code and see if I can get a repro

**Comment by rickle-msft** [comment]
@ptownsen We spent some time with this this afternoon. We weren't able to get a repro using the sample you provided unfortunately, but it did lead to a follow up question: Do you set HttpClientOptions anywhere in your project or in your environment? 

For some context, when we ran it on a 1GB file, we timed out at 10 minutes as expected, and this timeout comes from the underlying async framework and is specified in nanoseconds and is an IllegalStateException. The exception you're seeing is specified in milliseconds and mentions a network channel. This is why I believe there may be something interfering at the client level rather than just the operation level.

**Comment by ptownsen** [comment]
@rickle-msft  Thanks for testing this on your end.  Per your suggestion, I am trying to address the client timeout issue.  I have updated the sample code to explicitly set the HttpClient read timeout to 300 seconds.  I am still getting the 60 second timeout error.  

```
public void uploadToAzureStorage(File file)
  {
      String fileName = file.getName();
      String endPoint = "https://datalake.dfs.core.windows.net/datalake-file-system/qsys-data-export/" + fileName;
      String sasToken = "?sv=2021-06-08&ss=b&srt=sco&sp=rwdlax&se=.....";
      String fileSystemName = "datalake-file-system";

      HttpClientOptions httpClientOptions = new HttpClientOptions();
      httpClientOptions.setReadTimeout(Duration.ofSeconds(300));

      DataLakeFileClient fileClient = new DataLakePathClientBuilder()
          .clientOptions(httpClientOptions)
          .endpoint(endPoint)
          .sasToken(sasToken)
          .fileSystemName(fileSystemName)
          .buildFileClient();
```
      
reactor.core.Exceptions$ReactiveException: java.util.concurrent.TimeoutException: Channel response timed out after 60000 milliseconds.

**Comment by rickle-msft** [comment]
@ptownsen Sorry can you try setting the response timeout instead of the read timeout? Read timeout specifies how long to wait between receiving individual bytes of the body before timing out. Response timeout specifies how long to wait for the response headers themselves. We think it's the latter that is the problem at the moment. If you want to be safe, you could just up all the values on the client options and then scale them down one at a time from there to find the right one.

**Comment by ptownsen** [comment]
@rickle-msft  Thank you for your help on this.  I have set the responseTimeout to a higher value, and now my large files successfully upload to data lake container without issue.

`httpClientOptions.setResponseTimeout(Duration.ofSeconds(300));`

This definitely solves my issue.  Cheers.

**Comment by rickle-msft** [comment]
Awesome! So glad to hear it! Thanks for your patience working with us!
