### ISSUE TITLE
[AppConfig] Add TROUBLESHOOTING.md file

### ISSUE THREAD

**Issue by mssfang** [Azure/azure-sdk-for-java#30414]
- Add TROUBLESHOOTING.md file for Java [Pefer to get it done before 2022 Sep]
- Drive it to get it done for all 4 languages. [Deadline: Before 2022 October]

**Comment by joshfree** [comment]
Examples:

https://github.com/Azure/azure-sdk-for-java/blob/main/sdk/eventhubs/azure-messaging-eventhubs/TROUBLESHOOTING.md

https://github.com/Azure/azure-sdk-for-java/blob/main/sdk/identity/azure-identity/TROUBLESHOOTING.md

https://github.com/Azure/azure-sdk-for-java/blob/main/sdk/keyvault/TROUBLESHOOTING.md

https://github.com/Azure/azure-sdk-for-java/blob/main/sdk/search/azure-search-documents/TROUBLESHOOTING.md

https://github.com/Azure/azure-sdk-for-java/blob/main/sdk/monitor/azure-monitor-query/TROUBLESHOOTING.md

/cc @samvaity too as fyi

**Comment by mssfang** [comment]
- Consider adding a solution on how to timeout on the client level.
