### ISSUE TITLE
[Feature Request] Update the usage of MySQL in the doc of Azure Spring Apps

### ISSUE THREAD

**Issue by saragluna** [Azure/azure-sdk-for-java#30437]
### Context

With all the changes we made to support credential-free connections:
- https://github.com/Azure/azure-sdk-for-java/issues/29218
- https://github.com/Azure/azure-sdk-for-java/issues/29785
- https://github.com/Azure/azure-sdk-for-java/issues/28685

We should also update docs of Azure Spring Apps using MySQL to ensure they will use credential-free connections.

### Goal 

Update this doc https://docs.microsoft.com/en-us/azure/spring-apps/tutorial-managed-identities-mysql to include credential-free connections.

replace [this doc](https://docs.microsoft.com/en-us/azure/spring-apps/tutorial-managed-identities-mysql) with new tutorial (asir)

**Comment by saragluna** [comment]
Replace the doc https://docs.microsoft.com/en-us/azure/spring-apps/tutorial-managed-identities-mysql with https://learn.microsoft.com/en-us/azure/developer/java/spring-framework/deploy-passwordless-spring-database-app?toc=%2Fazure%2Fdeveloper%2Fintro%2Ftoc.json&bc=%2Fazure%2Fdeveloper%2Fintro%2Fbreadcrumb%2Ftoc.json&tabs=mysql

**Comment by hui1110** [comment]
PR: https://github.com/MicrosoftDocs/azure-docs-pr/pull/213151

**Comment by hui1110** [comment]
PR has been merged, close it now.
