### ISSUE TITLE
[BUG] Key Vault ResourceModifiedException: Status Code 400

### ISSUE THREAD

**Issue by saragluna** [Azure/azure-sdk-for-java#30436]
**Describe the bug**
We ran into this KV exception when running ITs with libs in the `buildFromSource` step. We managed to create a minimal project to reproduce the issue. https://github.com/saragluna/kv-it-issue. 

***Exception or Stack Trace***
```console
Exception in thread "main" com.azure.core.exception.ResourceModifiedException: Status code 400, "{"error":{"code":"BadParameter","message":"Property  has invalid value\r\n"}}"
	at com.azure.core.implementation.http.rest.RestProxyBase.instantiateUnexpectedException(RestProxyBase.java:366)
	at com.azure.core.implementation.http.rest.SyncRestProxy.ensureExpectedStatus(SyncRestProxy.java:121)
	at com.azure.core.implementation.http.rest.SyncRestProxy.handleRestReturnType(SyncRestProxy.java:206)
	at com.azure.core.implementation.http.rest.SyncRestProxy.invoke(SyncRestProxy.java:76)
	at com.azure.core.implementation.http.rest.RestProxyBase.invoke(RestProxyBase.java:110)
	at com.azure.core.http.rest.RestProxy.invoke(RestProxy.java:95)
	at com.sun.proxy.$Proxy3.setSecret(Unknown Source)
	at com.azure.security.keyvault.secrets.implementation.SecretClientImpl.setSecretWithResponse(SecretClientImpl.java:497)
	at com.azure.security.keyvault.secrets.SecretClient.setSecretWithResponse(SecretClient.java:147)
	at com.azure.security.keyvault.secrets.SecretClient.setSecret(SecretClient.java:118)
	at com.example.demo.DemoApplication.main(DemoApplication.java:19)

```

**To Reproduce**
https://github.com/saragluna/kv-it-issue

***Code Snippet***

```java
private static final String NAME = "sample-key";
private static final String VALUE = "sample-value";

SecretClient client = new SecretClientBuilder()
		.vaultUrl("XXX")
		.credential(new DefaultAzureCredentialBuilder().build())
		.buildClient();

client.setSecret(NAME, VALUE);
KeyVaultSecret secret = client.getSecret(NAME);
System.out.println(secret.getValue());
```

**Expected behavior**
The code can work fine.

**Screenshots**
<img width="1699" alt="image" src="https://user-images.githubusercontent.com/31124698/184344332-2071063f-6f7b-463d-827d-03867d626a41.png">

**Setup (please complete the following information):**
 - OS: [MacOS]
 - IDE: [IntelliJ]
 - Library/Libraries: [azure-security-keyvault-secrets:4.5.0-beta.1]
 - Java version: [8] 
 - App Server/Environment: [N/A]
 - Frameworks: [N/A] 

If you suspect a dependency version mismatch (e.g. you see `NoClassDefFoundError`, `NoSuchMethodError` or similar), please check out [Troubleshoot dependency version conflict article](https://aka.ms/azsdk/java/dependency/troubleshoot) first. If it doesn't provide solution for the problem, please provide:
- verbose dependency tree (`mvn dependency:tree -Dverbose`)
- exception message, full stack trace, and any available logs

**Additional context**
N/A

**Information Checklist**
Kindly make sure that you have added all the following information above and checkoff the required fields otherwise we will treat the issuer as an incomplete report
- [x] Bug Description Added
- [x] Repro Steps Added
- [x] Setup information Added

**Comment by stliu** [comment]
does this issue only happen in the latest non-released kv client?

**Comment by saragluna** [comment]
> does this issue only happen in the latest non-released kv client?

Yes, it does.

**Comment by saragluna** [comment]
@vcolin7 could you please take a look at this issue?

**Comment by vcolin7** [comment]
> @vcolin7 could you please take a look at this issue?

Hi @saragluna, it's posible this is related to a change we made to use a separate stack for sync clients, as opposed to using sync-over-async like we used to. We're working on applying a fix in #30512. One question though: does this happen only with sync clients for you? What about async clients?

**Comment by vcolin7** [comment]
@saragluna, @stliu We just merged this fix, would you mind checking if this is still happening for you?

**Comment by saragluna** [comment]
> > @vcolin7 could you please take a look at this issue?
> 
> Hi @saragluna, it's posible this is related to a change we made to use a separate stack for sync clients, as opposed to using sync-over-async like we used to. We're working on applying a fix in #30512. One question though: does this happen only with sync clients for you? What about async clients?

@vcolin7 will try it.

**Comment by saragluna** [comment]
> @saragluna Xiaolu Dai FTE, @stliu Strong Liu FTE We just merged this fix, would you mind checking if this is still happening for you?

@vcolin7, thanks. Will try it now.

**Comment by saragluna** [comment]
@vcolin7, just did some tests. 

Before applying the latest changes, the error only happened to the sync client.

After applying the latest changes, both sync and async clients can work now. 

So I am going to close this issue. Thanks for the help.

**Comment by saragluna** [comment]
@Netyyyy, we can re-enable the ITs now.
