### ISSUE TITLE
Million duplicates from producer(python) made consumer(java) unstable.

### ISSUE THREAD

**Issue by ganesh-vellanki** [Azure/azure-sdk-for-java#30455]
**Query/Question**
Hi everyone, we recently faced an issue with duplicates in event hub. The team responsible for ingesting events accidentally loaded events twice from two automated jobs. After this incident happened, the consumer (eventhubProcessor)  tried to process the events at the same rate down the line but after 50% of ingestion, it came down due to java heap issue exceptions.

We never recovered after that incident. Even though we restarted our consumer 3 hrs later after incident, we couldn't consume messages properly as it did before. Even after 3 days we are processing the same duplicate messages that caused this incident. Every time when we restart a consumer from idle state causes duplicate consumption. Any newly added load to event hub after the incident, is consumed at very slow rate due to pressure from duplicate messages. I am attaching screenshot of our consumption for reference.

Please let me know why this happened & how we can recover from it, this is causing business delays and extended support time/monitoring from team. 

Team & I would be glad to understand the problem & research on solution.

Type of message: json (appox 30KB),
Partitions: 32,
Producer: Python (function app),
Consumer: Java - spring boot application (container app service).

***Why is this not a Bug or a feature Request?***
Gathering information before calling this out.

**Setup (please complete the following information if applicable):**
 - OS: Linux container
 - IDE: Java - intellij
 - Library/Libraries: [jdk:11, azure-messaging-eventhubs: 5.12.2, azure-messaging-eventhubs-checkpointstore-blob: 1.12.1, azure-core-amqp: 2.6.0]
 
 **Information Checklist**
 Kindly make sure that you have added all the following information above and checkoff the required fields otherwise we will treat the issuer as an incomplete report
- [ x] Query Added
- [ x] Setup information Added
<img width="1902" alt="Screenshot 2022-08-13 at 5 55 37 PM" src="https://user-images.githubusercontent.com/11549787/184494122-17dac5ee-ed78-472e-bff7-da8cf555a4b9.png">

**Comment by joshfree** [comment]
Hi @ganesh-vellanki thank you for reaching out to us via this GitHub issue.  Customers with an [Azure support plan](https://azure.microsoft.com/support/options/) can open an [Azure support ticket](https://azure.microsoft.com/support/create-ticket/).  **We recommend this option if your problem requires immediate attention.**

https://github.com/Azure/azure-sdk-for-java/blob/main/SUPPORT.md.

Otherwise, folks from the Azure SDK team will follow up with you via GitHub, shortly.

/cc @Azure/azsdk-sb-java

**Comment by conniey** [comment]
Hey,

Thanks for reporting this issue.  A few questions:
1. Could you provide some logs around the time this occurs? (INFO logs at least, ideally DEBUG)
1. Could you be able to provide a heap dump of your application when it encounters this issue?
1. Repro steps if possible in addition to information about your processor environment. See: [Filing GitHub issues](https://github.com/Azure/azure-sdk-for-java/blob/main/sdk/eventhubs/azure-messaging-eventhubs/TROUBLESHOOTING.md#filing-github-issues)

When the EventProcessorClient claims a partition and begins processing, it starts reading the stream from the checkpoint for that partition (if it exists).  If you know the offset for the duplicate events, one option you can try is to update the checkpoint with that offset manually, so the EventProcessorClient starts reading the stream after those events.
