### ISSUE TITLE
[FEATURE REQ] Spring Data Cosmos supports Spring Boot 3 and Spring Data 3

### ISSUE THREAD

**Issue by moarychan** [Azure/azure-sdk-for-java#30458]
### Context

Problems
The latest Spring Data cosmos is incompatible with Spring Boot 3.0.0 and Spring Data 3.0.0

User scenario 1
Users can not find a Spring Cloud Azure version compatible based on Spring Data 3.0.0.

User scenario 2
Users should check the [documentation to confirm](https://github.com/Azure/azure-sdk-for-java/tree/main/sdk/cosmos/azure-spring-data-cosmos#spring-boot-version-support) which version of Spring Boot matches Spring Data Cosmos, then check the [Spring Cloud Azure version mapping](https://github.com/Azure/azure-sdk-for-java/wiki/Spring-Versions-Mapping) to confirm which version Spring Boot version matches Spring Cloud Azure, because they don't have the same versions for Spring Data Cosmos and Spring Cloud Azure.

### Goal

- Move azure-spring-data-cosmos to ask/spring, and use a unified version in Spring Cloud Azure.
  - Develop build from source integration tests feature in the main branch
  - Enable the build from source integration tests to azure-cosmos and azure-spring-data-cosmos

- Spring Data Cosmos support Spring Data 3.0.0.

- Support Spring Data Cosmos auto-configuration in Spring Cloud Azure autoconfigure.

- Support Spring Data Cosmos AOT.

- Add Spring Data Cosmos samples in [Azure-samples](https://github.com/Azure-Samples/azure-spring-boot-samples) repo.

- Add Spring Data Support doc in the [reference doc](https://learn.microsoft.com/en-us/azure/developer/java/spring-framework/) of Spring Cloud Azure.

**Comment by moarychan** [comment]
https://github.com/Azure/azure-sdk-for-java/issues/29979

**Comment by moarychan** [comment]
Hi @kushagraThapar , we plan to release a milestone Spring Cloud Azure based on Spring Boot 3.0.0 milestone version, please help to take a look!

**Comment by kushagraThapar** [comment]
@moarychan - got it, now we won't be overriding `CrudRepository` APIs. This means in future we will not know of any new APIs that `CrudRepository` adds, which is fine, as long as our customers are okay with it. 

@saragluna - I believe this change can be done by your team, and we can help if needed. I think all we need to do is remove the `@override` annotations from all `CrudRepository` APIs, so that the code compiles. To avoid any breaking changes, we should keep those APIs as it is in `SimpleCosmosRepository` so that our customers can still use them.

**Comment by moarychan** [comment]
Hi @kushagraThapar , thanks for your update.

We plan to modify this in the spring-boot-3 branch and then release a beta version for both Spring Data Cosmos and other Spring Cloud Azure libraries.

**Comment by saragluna** [comment]
> @moarychan Moary Chen (CSI Interfusion Inc) Vendor - got it, now we won't be overriding `CrudRepository` APIs. This means in future we will not know of any new APIs that `CrudRepository` adds, which is fine, as long as our customers are okay with it.
> 
> @saragluna Xiaolu Dai FTE - I believe this change can be done by the developer who is working on spring-boot 3.0.0-M3 release, and we can help if needed. I think all we need to do is remove the `@override` annotations from all `CrudRepository` APIs, so that the code compiles. To avoid any breaking changes, we should keep those APIs as it is in `SimpleCosmosRepository` so that our customers can still use them.

According to https://github.com/spring-projects/spring-data-commons/wiki/Spring-Data-2022.0-(Turing)-Release-Notes-(Preview)#sorting-repositories-no-longer-inherit-from-crud-repositories, we only need to extend the respective CRUD repository explicitly.

**Comment by saragluna** [comment]
https://github.com/Azure/azure-sdk-for-java/pull/31417 to unblock the JDK 17 support.

**Comment by saragluna** [comment]
refer to this for how to support https://github.com/saragluna/azure-sdk-for-java/commit/afcfe9586124e8e2504e044724e4f8c3beacd383.

**Comment by christian-ehmke** [comment]
Dear team. Our current client wants to use Spring Boot 3.X. Currently we are prevented from doing so as no compatible version has been made available yet. Is there a timetable for when a compatible version of the SDK can be made available?

**Comment by saragluna** [comment]
@christian-ehmke I will have an offline discussion with @kushagraThapar and get back to you later.

**Comment by stliu** [comment]
@christian-ehmke yeah, we do plan to support spring data cosmos in Spring Boot 3 in the upcoming time, but unfortunately  it is pretty busy for the team right now, so we're targeting to the end of this year.

I know it is a long time, please vote or reach out our support for any higher priority request, thanks

**Comment by ehp246** [comment]
The end of year is too far out. If Cosmos doesn't go to Spring Boot 3, apps need to either drop Cosmos or drop Boot 3. With other major components like Service Bus and SQL are on Boot 3, I might to have to look at another non-SQL option.

**Comment by CrawX** [comment]
> so we're targeting to the end of this year.

Is there any chance for a small Azure CosmosDB customer to expedite this? Like the previous reply, I don't want to be stuck on Spring Boot 2.x until the end of the year and would be looking into alternatives outside of CosmosDB if there is no way. For reference, Spring Boot 3.0.0 went GA on [24th of November last year](https://spring.io/blog/2022/11/24/spring-boot-3-0-goes-ga).

**Comment by TheovanKraay** [comment]
We have discussed this and re-prioritized. 
We are now targeting H1 this year (by end of June 2023) to support Cosmos DB in Spring Boot 3.

**Comment by ehp246** [comment]
I say that's moving to the right direction. Thanks.

**Comment by nagaraju1692** [comment]
As per the project requirement , I have to migrate spring boot application from Spring boot 2.7.6 to 3.0.0 version.

I have modified the below changes from my existing application.

Changed the java version from java 11 to 17.
I have modified the spring boot starter parent version from 2.7.6 to 3.0.0 version.
I am able to build the application ,While starting the server getting the issue as below.

Issue Description::

APPLICATION FAILED TO START

Description:

Field empRepository in com.example.SpringBootDemo.Service.EmpService required a bean of type 'com.example.SpringBootDemo.repository.EmpRepository' that could not be found.

The injection point has the following annotations:

@org.springframework.beans.factory.annotation.Autowired(required=true)
Action:

Consider defining a bean of type 'com.example.SpringBootDemo.repository.EmpRepository' in your configuration.

Process finished with exit code 1

I am able to replicate this issue , Please find the below repository git hub code.

https://github.com/nagaraju1692/SpringBootDemoCosmosDB

**Comment by Netyyyy** [comment]
> As per the project requirement , I have to migrate spring boot application from Spring boot 2.7.6 to 3.0.0 version.
> 
> I have modified the below changes from my existing application.
> 
> Changed the java version from java 11 to 17. I have modified the spring boot starter parent version from 2.7.6 to 3.0.0 version. I am able to build the application ,While starting the server getting the issue as below.
> 
> Issue Description::
> 
> APPLICATION FAILED TO START
> 
> Description:
> 
> Field empRepository in com.example.SpringBootDemo.Service.EmpService required a bean of type 'com.example.SpringBootDemo.repository.EmpRepository' that could not be found.
> 
> The injection point has the following annotations:
> 
> @org.springframework.beans.factory.annotation.Autowired(required=true) Action:
> 
> Consider defining a bean of type 'com.example.SpringBootDemo.repository.EmpRepository' in your configuration.
> 
> Process finished with exit code 1
> 
> I am able to replicate this issue , Please find the below repository git hub code.
> 
> https://github.com/nagaraju1692/SpringBootDemoCosmosDB

Hi @nagaraju1692, thank you for your issue. I saw you still use `azure-spring-boot-starter-cosmos` which not update anymore, recommend you use `spring-cloud-azure-starter-data-cosmos` instead, here is the [migration guide](https://learn.microsoft.com/en-us/azure/developer/java/spring-framework/migration-guide-for-4.0).

For some reason, spring data cosmos haven't supported Spring Boot 3 yet, you could still use Spring Boot 2.x with `spring-cloud-azure-starter-data-cosmos` latest version 4.7.0.

BTW, Spring data cosmos support for Spring Boot 3 will be released recently, please pay attention to our latest information when it is published.

**Comment by katperi** [comment]
> We have discussed this and re-prioritized. We are now targeting H1 this year (by end of June 2023) to support Cosmos DB in Spring Boot 3.

Is there any update on when CosmosDB will be supported in Spring Boot 3?

**Comment by TheovanKraay** [comment]
@katperi - we are still targeting end of June 2023 to support Spring Boot 3 for Cosmos DB.

**Comment by kushagraThapar** [comment]
@katperi  - the work is currently in progress and will be done soon. Current ETA is June 2023.

**Comment by edgarla** [comment]
Hi guys, it is June 2023!

Do you have any update on this topic?

is it on track?

**Comment by kushagraThapar** [comment]
@edgarla yes, it is on track, will be released in this month's release schedule. will keep you posted once the release is done.

**Comment by christian-ehmke** [comment]
Dear team, when do you plan to release the Spring Boot 3.0 support?

**Comment by kushagraThapar** [comment]
@christian-ehmke - its on-track and still planned to be released for this month end. 
@saragluna can provide the exact timeline of the release.

**Comment by jsanmarco** [comment]
Any update on this? what is the ETA?
Thanks,
Juan

**Comment by saragluna** [comment]
> 

Sorry for the late reploy. We are preparing the release this week. It will be out before the end of this Month.

**Comment by christian-ehmke** [comment]
@kushagraThapar and @saragluna: Are hierarchical partition keys also part of the upcoming release?

**Comment by saragluna** [comment]
The Spring Cloud Azure 5.3.0 has been released.

**Comment by saragluna** [comment]
> @kushagraThapar and @saragluna: Are hierarchical partition keys also part of the upcoming release?

@kushagraThapar could help with this question.

**Comment by christian-ehmke** [comment]
@saragluna: ok cool, but what about "com.azure:azure-spring-data-cosmos"?

**Comment by saragluna** [comment]
Sorry for didn’t clarify it, the spring data cosmos is managed by spring cloud azure now. Its version is 5.3.0 too. Check this bom file https://repo1.maven.org/maven2/com/azure/spring/spring-cloud-azure-dependencies/5.3.0/spring-cloud-azure-dependencies-5.3.0.pom.

**Comment by christian-ehmke** [comment]
@saragluna Thank you so much.
@kushagraThapar can you tell me if "hierarchical partition keys" are available in this release as well. I know this is not release to this issue.

**Comment by TheovanKraay** [comment]
@christian-ehmke support for hierarchical partition keys in Spring Data is not included in this release. It is being worked on currently.

**Comment by christian-ehmke** [comment]
> @christian-ehmke support for hierarchical partition keys in Spring Data is not included in this release. It is being worked on currently.

Thank you for the update! Is there already a release plan/date for this feature?

**Comment by TheovanKraay** [comment]
> > @christian-ehmke support for hierarchical partition keys in Spring Data is not included in this release. It is being worked on currently.
> 
> Thank you for the update! Is there already a release plan/date for this feature?

@christian-ehmke no firm date yet, as hierarchical partition keys is not a concept that is part of the core Spring Data framework. So, it will need some API design (and we are in that phase). But, we are working on it. Is this feature a dependency for your current/future development?

**Comment by kushagraThapar** [comment]
Closing this issue, as spring data cosmos supports spring boot 3 and spring data 3 now, thanks!
