### ISSUE TITLE
NoSuchElementException generated by azure-cosmos-4.32.0.jar and opentelemetry

### ISSUE THREAD

**Issue by alain-marcel** [Azure/azure-sdk-for-java#30459]
**Describe the bug**
GIVEN following context
  SpringBoot : 2.7.2
  SpringCloud: 2021.0.3
  SpringCloudAzure: 4.3.0  =>  package com.azure:azure-cosmos:4.32.0 
  Java ApplicationInsights agent: 3.3.1

WHEN cosmos try to monitor requests

THEN there is NoSuchElementException with io.opentelemetry.javaagent.instrumentation.netty.v4.common.client.NettySslInstrumentationHandler

Notes : 
  - There is no issue if we use  Java ApplicationInsights agent: 3.2.3
  - I think we could reproduce issue with an application not based on spring : it is just a matter of cosmos, opentelemetry and Java ApplicationInsights agent.
     

***Exception or Stack Trace***
[c.a.c.i.d.r.RntbdRequestManager] ERROR Report this azure-cosmos-4.32.0.jar issue to ensure it is addressed:
[ChannelHandlerContext(RntbdRequestManager#0, [id: 0x5ad5ff22, L:/******* - R:cdb-ms-prod-westeurope1-fd80.documents.azure.com/******])]
[com.azure.cosmos.implementation.directconnectivity.rntbd.RntbdRequestManager.reportIssue(RntbdRequestManager.java:957)]
[SslHandshakeCompletionEvent(SUCCESS): : java.util.NoSuchElementException: io.opentelemetry.javaagent.instrumentation.netty.v4.common.client.NettySslInstrumentationHandler
               at io.netty.channel.DefaultChannelPipeline.getContextOrDie(DefaultChannelPipeline.java:1073)
               at io.netty.channel.DefaultChannelPipeline.addAfter(DefaultChannelPipeline.java:302)

**To Reproduce**
The issue arise if  application is started on developer desktop with BootRun when we request a cosmos collection.
The issue arise also if code is executed in an AzureFunction on the cloud.

**Comment by moarychan** [comment]
Hi @alain-marcel  thanks for you reaching out! @backwind1233 , could you help to take a look?

**Comment by backwind1233** [comment]
@kushagraThapar  Could you help to take a look?

**Comment by alain-marcel** [comment]
Some personal remarks about the issue.

I suppose that issue is in azure-cosmos when it tries to load opentelemetry classes.
It throws NoSuchElementException when it searches io.opentelemetry.javaagent.instrumentation.netty.v4.common.client.NettySslInstrumentationHandler in applicationinsights-agent.jar.
The path starts from inst folder in the agent.
The inst folder contains classe files with classdata extension.

But applicationinsights-agent contents seems to contradict this behavior because

- Agent version 3.2.3, that works, under inst there is no folder v4 but "io/opentelemetry/javaagent/instrumentation/netty/v4_0"

- Agent version 3.2.4, that does not work, under inst there is no folder v4 but "io/opentelemetry/javaagent/instrumentation/netty/v4_0"

- Agent version 3.3.1, that does not work, under inst there is the expected file "io/opentelemetry/javaagent/instrumentation/netty/v4/common/client/NettySslInstrumentationHandler.classdata"

                                                                                     

Hope this help.

**Comment by kushagraThapar** [comment]
@alain-marcel - thanks for the context, this should help us investigate this issue. Will look at it soon.

**Comment by trask** [comment]
hi @alain-marcel! @kushagraThapar reached out and I can confirm this is a known issue in Application Insights Java agent, and has been fixed just last week in the upstream OpenTelemetry Java agent: https://github.com/open-telemetry/opentelemetry-java-instrumentation/pull/6469

we are currently planning to release 3.4.0-BETA of Application Insights Java at the end of this week or early next week, which will have this fix. here's the latest Application Insights Java SNAPSHOT build which contains the fix if you'd like to give it a try: https://github.com/microsoft/ApplicationInsights-Java/suites/7898554127/artifacts/335791974

**Comment by trask** [comment]
hi @buptmiao, what version of Application Insights Java agent are you using?

**Comment by buptmiao** [comment]
We are using China Azure app service docker Linux with codeless java application insights agent, so the java agent looks injected by the azure platform, is there a way I can get the version?
