### ISSUE TITLE
How to setup retry?

### ISSUE THREAD

**Issue by loudywen** [Azure/azure-sdk-for-java#30474]
hi when encounter 429 how do I setup retry pollic?

I am using `CosmosAsyncClient` but looks like when 429 encounter, the client just stop.

**Comment by TheovanKraay** [comment]
The default ClientRetryPolicy flow is illustrated [here ](https://github.com/Azure/azure-sdk-for-java/blob/main/sdk/cosmos/azure-cosmos/docs/ClientRetryPolicy.png). Error code and associated retry behaviour is documented [here](https://github.com/Azure/azure-sdk-for-java/blob/main/sdk/cosmos/azure-cosmos/docs/ErrorCodesAndRetries.md).  

As you can see, the client does not just stop when encountering 429. If it appears to stop, it is likely you have reached the default limit of 9 retries (or 30 seconds, whichever comes sooner). You can override these limits in CosmosAsyncClient in the below manner:

```
        ThrottlingRetryOptions retryOptions = new ThrottlingRetryOptions();
        Duration duration = Duration.ofSeconds(60);
        retryOptions.setMaxRetryAttemptsOnThrottledRequests(20);
        retryOptions.setMaxRetryWaitTime(duration);

        //  Create async client
        client = new CosmosClientBuilder()
                .endpoint(AccountSettings.HOST)
                .key(AccountSettings.MASTER_KEY)
                .consistencyLevel(ConsistencyLevel.EVENTUAL)                
                .contentResponseOnWriteEnabled(true)
                .throttlingRetryOptions(retryOptions)
                .buildAsyncClient();
```

**Comment by loudywen** [comment]
@TheovanKraay  thx, it helps a lot. after i updated the max retry attempts on throttled request to bigger number and all works fine now.
