### ISSUE TITLE
[QUERY] Question regarding pagination with database throttling

### ISSUE THREAD

**Issue by loudywen** [Azure/azure-sdk-for-java#30491]
Hi, I have a doubt regarding belows sentence which is mentioned in this [doc](https://docs.microsoft.com/en-us/azure/cosmos-db/sql/sql-query-pagination#understanding-query-executions)
> If you execute the same query multiple times, the number of pages might not be constant. For example, **_if a query is throttled there may be fewer available results per page_**, which means the query will have additional pages. In some cases, it is also possible that your query may return an empty page of results.

How can I simulate this throttling scenario that mention in above sentence? I tried to raise the `429` and from my application I can see that after reach the max retry an exception will throw, also as long as I increase my max retry attempt to higher number and all my requests will pass. **So it is either throw error or retry success and I never see a case that only return partial of the data.**

Why I am worry about this sentence that is because in our use case we will store all the continuation token of each page for the same query to cosmos (we expecting with the same token and same query, we should get the same size(count) of data and same order, ps: let's assume it will not have any new data insert for this query). then later some workers will pick up a token in parallel to perform some business logic and continue the downstream.  We want to make sure that the token and the count of the records that we store for each page should always the same for the workers (same token should get the same sets of records for a page).

With my test, since I set the retry attempt to large number so even `429` happen, I eventually able to insert all the token to cosmos and everytime it has the same set of records and token for each page. Samething for the workers ,when the `429` happen the workers are able to retrieve the correct set of data after retry. So I am not seeing this cases `if a query is throttled there may be fewer available results per page`

If the sentence mentioned in the doc is true. Then I am assuming below cases might happen ( actually we don't want to see them happen :) ):

First. there is no throttling happen during the time we store all those token to cosmos. table looks like this (total records should be 220):
| page | token | size | notes                |
|------|-------|------|----------------------|
| 0    | t0    | 100  |                      |
| 1    | t1    | 20   | end of one partition |
| 2    | null  | 100  | no more page         |

later when multiple workers start picking up the token and throttling happen. Will any workers get less size of data? For example maybe worker 0 picked up token t1 but it only retrieved 8 records ?  You see the issue here right, at the end the workers only processed 208 records out of 220 , missed 12.

Second, throttling happen during the time we store the token and also happen when the workers start working  (total records should be 220)
| page | token | size | notes                |
|------|-------|------|----------------------|
| 0    | t0    | 88|        missed 12              |
| 1    | t1    | 10| missed 10 |
| 2    | t2| 12 |      the missing 12 comes to this page   |
| 3   | t3| 10 |     the missing 10 comes to this page    |
| 4   | null| 100 |      no more page   |

with this case, will the worker again get less records for a particular token? For example maybe worker 0 picked up token t1 but it only retrieved 8 records ?

I can only simulate the 429 throttling in my end, not sure what other throttling scenario I can simulate to achieve the case that mention in the doc.

**Comment by loudywen** [comment]
@kushagraThapar hi, is my assumption that I mentioned in the post correctly or not? Will those two cases happen?

**Comment by TheovanKraay** [comment]
> @kushagraThapar hi, is my assumption that I mentioned in the post correctly or not? Will those two cases happen?

It's possible for those two cases to happen if your provisioned RUs are lower than your overall throughput at a given time. However, since you have increased the retry/wait time to a high number, it is very unlikely to happen. Of course, the higher the retry number/wait time, the more latency you might get in your application. If the integrity of the results (as well as limiting cost) is the most important goal, then leave the RUs low and retry thresholds high. If you need low latency as well, of course you need to increase RUs to be able to cope with the load.

**Comment by loudywen** [comment]
> It's possible for those two cases to happen if your provisioned RUs are lower than your overall throughput at a given time

Hi @TheovanKraay  for this statement I would like to know that how often those cases will happen? Since during my test, when I set to low RU and low retry count, my application always able to catch the 429 exception and I never see the cases of getting less record or empty list.

**Comment by TheovanKraay** [comment]
> > It's possible for those two cases to happen if your provisioned RUs are lower than your overall throughput at a given time
> 
> Hi @TheovanKraay for this statement I would like to know that how often those cases will happen? Since during my test, when I set to low RU and low retry count, my application always able to catch the 429 exception and I never see the cases of getting less record or empty list.

If throughput is such that retries can exceed the maximum count you have set, then these cases are possible. However, if your tests show that this is not happening, and your tests also reflect the maximum throughput you can expect in your live system, then you have set a threshold which makes this virtually impossible, and you can have confidence this will not happen in production.

**Comment by loudywen** [comment]
Thanks again @TheovanKraay .  The reason I am keep asking this question that is because one of the feature of our product will heavily rely on the record count of each page.  And because of the doc doesn't have a detatiled example for those cases and also during our test we are not seeing those at all (we only see during throttling either 429 exception will throw after reached the max retry count or received expect count of record on each page) so we kind of confuse.

**Comment by TheovanKraay** [comment]
> Thanks again @TheovanKraay . The reason I am keep asking this question that is because one of the feature of our product will heavily rely on the record count of each page. And because of the doc doesn't have a detatiled example for those cases and also during our test we are not seeing those at all (we only see during throttling either 429 exception will throw after reached the max retry count or received expect count of record on each page) so we kind of confuse.

Sure, understood. The docs mention it because it is theoretically possible, so we have to expose this for clarity and transparency. But it is unlikely, and especially if you have tested your use case with a throughput which reflects production load.
