### ISSUE TITLE
[QUERY]Why processPartitionClose handler doesn't called when connecting Amqp?

### ISSUE THREAD

**Issue by kohei-kitaura** [Azure/azure-sdk-for-java#30527]
**Query/Question**
Recently, I encountered an Amqp reconnection when consuming from an EventHub topic.

```
[partition-pump-0-127] c.p.i.n.p.a.e.ConsumeEventHubUseDdbCpStore ConsumeEventHubUseDdbCpStore[id=270238a6-7bae-319a-9c83-96655aba53cd] EventProcessorClient is connecting to EventHub. eventHubName:xxxx partitionId:0
[reactor-executor-83] c.a.m.e.i.AmqpReceiveLinkProcessor {"az.sdk.message":"Receive link endpoint states are closed. Requesting another.","linkName":"0_bd5efa_1658980830991","entityPath":"xxxx/ConsumerGroups/consumergroup-xxxx/Partitions/0"}
[reactor-executor-83] c.a.m.e.i.AmqpReceiveLinkProcessor {"az.sdk.message":"Setting next AMQP receive link.","linkName":"0_bd5efa_1658980830991","entityPath":"xxxx/ConsumerGroups/consumergroup-xxxx/Partitions/0"}
[boundedElastic-256] c.a.m.e.i.AmqpReceiveLinkProcessor {"az.sdk.message":"Receive link endpoint states are closed. Requesting another.","linkName":"0_bd5efa_1658980830991","entityPath":"xxxx/ConsumerGroups/consumergroup-xxxx/Partitions/0"}
[reactor-executor-83] c.a.c.amqp.implementation.ReactorSession {"az.sdk.message":"","exception":"Cannot create receive link from a closed session., errorContext[NAMESPACE: xxxx.servicebus.windows.net. ERROR CONTEXT: N/A, PATH: xxxx/ConsumerGroups/consumergroup-xxxx/Partitions/0]","connectionId":"MF_0e96f3_1659090578660","sessionName":"xxxx/ConsumerGroups/consumergroup-xxxx/Partitions/0","entityPath":"xxxx/ConsumerGroups/consumergroup-xxxx/Partitions/0","linkName":"0_bd5efa_1658980830991"}
```
We were using the EventProcessorClient to read.
The EventProcessorClient has processPartitionClose handler and processPartitionInitialization handler set.
At this time, only processPartitionInitialization handler was called.
Why processPartitionClose handler didn't called?
I think both processPartitionClose and processPartitionInitialization handler should be called when reconnecting Amqp.
(Our EventProcessorClient saves the last checkpoint using the processPartitionClose handler.)

**Setup (please complete the following information if applicable):**
 - OS: Linux
 - IDE: Eclipse
 - Library/Libraries: azure-messaging-eventhubs:5.11.1
 
 **Information Checklist**
 Kindly make sure that you have added all the following information above and checkoff the required fields otherwise we will treat the issuer as an incomplete report
- [x] Query Added
- [x] Setup information Added

**Comment by joshfree** [comment]
Hi @kohei-kitaura thank you for reach out to us via this GitHub issue.  Someone from the `Event Hubs SDK` crew will follow up with you shortly.  /cc @Azure/azsdk-sb-java

**Comment by anuchandy** [comment]
The Processor instance is supposed to run until it is explicitly closed or if the partition it was processing was stolen by another processor instance.

When one of the above cases happens, the close handler is invoked with appropriate reason [azure-sdk-for-java/CloseReason.java at main · Azure/azure-sdk-for-java (github.com)](https://github.com/Azure/azure-sdk-for-java/blob/main/sdk/eventhubs/azure-messaging-eventhubs/src/main/java/com/azure/messaging/eventhubs/models/CloseReason.java).  Otherwise, the processor is designed to recover from any transient errors so that the application can continue to receive from the partition.

**Comment by kohei-kitaura** [comment]
Thanks for your anwer, @anuchandy .
So the SDK behavior is that both processPartitionClose and processPartitionInitialization are not always called. I see.

/unresolve
In a case like this, is there any chance to save the last checkpoint?

**Comment by conniey** [comment]
Users would have to keep an internal state of what EventData was last processed.  When the EventProcessorClient recovers from a transient error, it starts reading from [the last EventData sequenceNumber that was pushed downstream](https://github.com/Azure/azure-sdk-for-java/blob/main/sdk/eventhubs/azure-messaging-eventhubs/src/main/java/com/azure/messaging/eventhubs/EventHubPartitionAsyncConsumer.java#L76).  Consequently, the user shouldn't see any difference in behaviour.

**Comment by kohei-kitaura** [comment]
Thanks for your anwer, @conniey .

/unresolve
> When the EventProcessorClient recovers from a transient error, it starts reading from the last EventData sequenceNumber that was pushed downstream. 

In this case, I think it's not true.
The SDK initialized the partition with an old checkpoint and called the processPartitionInitialization handler.
But processPartitionClose handler was not called. As a result, the EventData was duplicated.
Is this a bug? At least it doesn't seem transparent.

**Comment by kohei-kitaura** [comment]
Does anyone have an opinion on this issue?

**Comment by conniey** [comment]
> As a result, the EventData was duplicated.

The guarantee of EventProcessorClient is "at least once". (https://stackoverflow.com/a/33577018/4220757) If we want _only_ once, Service Bus may be the service to go with or consider adding some logic to understand when EventData when duplicated.
