### ISSUE TITLE
[BUG] App Configuration Regression in ClientBuilder

### ISSUE THREAD

**Issue by mrm9084** [Azure/azure-sdk-for-java#30536]
**Describe the bug**
`ConfigurationClientBuilder`'s `buildBlient` method doesn't build unique clients in version 1.3.6

***Exception or Stack Trace***
N/A

**To Reproduce**
Use a ConfigurationClientBuilder to build multiple clients. If the one client fails, it blocks the second client from use.

***Code Snippet***
```java
    public void example() throws InterruptedException {

        System.out.println("Example");

        EnvironmentCredential cred = new EnvironmentCredentialBuilder().build();

        ConfigurationClientBuilder builder = new ConfigurationClientBuilder().credential(cred);

        // Does Not Exist
        builder.endpoint("https://spring-geo-wus.azconfig.io");

        ConfigurationClient client = builder.buildClient();

        // Exists
        builder.endpoint("https://spring-geo-eus.azconfig.io");

        ConfigurationClient client2 = builder.buildClient();

        try {
            request(client);
        } catch (UnknownHostException e) {
            System.out.println("Unknown Host");
        } catch (Exception e) {
            System.out.println("Generic Error");
        }
        
        try {
            request(client2);
        } catch (UnknownHostException e) {
            System.out.println("Unknown Host");
        } catch (Exception e) {
            System.out.println("Generic Error");
        }
    }

    public static void request(ConfigurationClient client) throws UnknownHostException {

        System.out.println(client.getConfigurationSetting("a", "b").getKey());

    }
```

**Expected behavior**
The first client fails as expected after trying 3 times. The second client should succeed, it does in 1.3.5 and earlier. But instead, it fails with a 401.

Note: The second store doesn't retry 3 times like the original store, it seems to share a policy.

**Screenshots**
N/A

**Setup (please complete the following information):**
 - OS: [e.g. iOS] Windows
 - IDE: [e.g. IntelliJ] Eclipse
 - Library/Libraries: com.azure:azure-data-appconfiguration:1.3.6
 - Java version: 17
 - App Server/Environment: Tomcat
 - Frameworks: Spring

**Comment by alzimmermsft** [comment]
@samvaity / @mssfang could you update this line of code to not mutate the builder class level property: https://github.com/Azure/azure-sdk-for-java/blob/main/sdk/appconfiguration/azure-data-appconfiguration/src/main/java/com/azure/data/appconfiguration/ConfigurationClientBuilder.java#L224

**Comment by mrm9084** [comment]
@mssfang

**Comment by mssfang** [comment]
The fix PR: https://github.com/Azure/azure-sdk-for-java/pull/33031
