### ISSUE TITLE
[FEATURE REQ] Support plugin management in get_spring_boot_managed_external_dependencies.py

### ISSUE THREAD

**Issue by yiliuTo** [Azure/azure-sdk-for-java#30549]
### Context
There is a script [get_spring_boot_managed_external_dependencies.py](https://github.com/Azure/azure-sdk-for-java/blob/7bbdafb38c4365b93cbf42286eab76a607caf3c8/sdk/spring/scripts/get_spring_boot_managed_external_dependencies.py) under sdk/spring folder to record all of the external libraries which are managed in the latest supported `org.springframework.boot:spring-boot-dependencies` and  `org.springframework.cloud:spring-cloud-dependencies` version.
Currently, the script only lists the [managed library dependencies](https://github.com/Azure/azure-sdk-for-java/blob/7bbdafb38c4365b93cbf42286eab76a607caf3c8/sdk/spring/scripts/get_spring_boot_managed_external_dependencies.py#L122) while not include plugins, which can cause the miss of plugin compatability with sdk, e.g., in https://github.com/Azure/azure-sdk-for-java/pull/28958, `org.springframework.boot:spring-boot-maven-plugin` is imported, and we should take care of its upgrading in the future.

### Goal
Support both the library and plugin compatability with Spring Boot and Cloud.

**Comment by stliu** [comment]
I'm not quite understand the issue here, is it still valid? 
and what priority do you think @saragluna

**Comment by saragluna** [comment]
The issue was trying to manage versions for the maven pugins, like the following:

https://github.com/Azure/azure-sdk-for-java/blob/90060bae2ccc168bd0f36e8a825f1b87021367ad/eng/versioning/external_dependencies.txt#L275-L298

But this repo may use plugins of different versions from the Spring project, so I think the priority should be 3.
