### ISSUE TITLE
[QUERY] Is BlobContainerClient thread safe to be created as global variable per container in a singleton class

### ISSUE THREAD

**Issue by Jayadeep2308** [Azure/azure-sdk-for-java#30550]
I wanted to check if `BlobContainerClient`  can be assigned as global variable per container in a singleton class.  Also I wanted to check if there are any performance implications like thread starvation & connection starvation etc for using a single instance of BlobContainerClient for uploads and downloads of blob files to a container location.

I see that `BlobContainerClient.getBlobClient` creates a new instance of `BlobClient` everytime. But there is no documentation related to thread safety. 

Please find sample code below.
 
```java
private BlobContainerClient exampleBlobContainerClient;
 
@PostConstruct
    private void setupBlobClient() {
        BlobServiceClient blobServiceClient = new BlobServiceClientBuilder()
                .endpoint(springConfig.getStorageBlobProperties().getEndpoint())
                .credential(new StorageSharedKeyCredential(springConfig.getStorageBlobProperties().getAccountName(), springConfig.getStorageBlobProperties().getAccountKey()))
                .buildClient();
        styleboardServicesBlobContainerClient = blobServiceClient.getBlobContainerClient("example");
        if (!styleboardServicesBlobContainerClient.exists()) {
            logger.error("BLOB container: {} doesn't exists", getContainerName());
            throw new RestApplicationException(ErrorMessage.INTERNAL_SERVER_ERROR, null, RestAPIConstants.INTERNAL_ERROR_MESSAGE);
        }
    }
```

If BlobContainerClient  is not thread safe, I also wanted to check BlobServiceClient  is thread safe be created as global variable in singleton class and create BlobContainerClient at method leve.

 - Library/Libraries: spring-cloud-azure-starter-storage-blob:4.3.0

**Comment by joshfree** [comment]
Hi @Jayadeep2308, someone from the `azure-spring` team will follow up with you shortly.

**Comment by stliu** [comment]
actually, you don't need to create instance of blob client, just inject it as described here https://microsoft.github.io/spring-cloud-azure/current/reference/html/index.html#autoconfigure-azure-sdk-clients

So to answer your question, it is thread safe and Spring Cloud Azure already helps you to maintain it

**Comment by Jayadeep2308** [comment]
Hello @stliu : Thank you very much for your answer. I understand that blob client can be loaded as resource directly into spring components. But in my case, we use storage to upload and download images in the runtime base on different users. 

So I want to be able to download or upload different blob clients into a container/ containers. That's why I wanted move at least creation of BlobContainerClient per container to postconstruct. 

But as I understand from your response, BlobServiceClient and BlobContainerClient are thread safe and can be autowired to singleton spring components.   

Please let me know if mu understanding is wrong.

**Comment by stliu** [comment]
that's correct

I'm closing this one and please reopen it if you still have any questions, thanks for contacting us.
