### ISSUE TITLE
[BUG] Issues when creating CosmosDb async client from a reactor context

### ISSUE THREAD

**Issue by stevenylai** [Azure/azure-sdk-for-java#30568]
**Describe the bug**
Due to company's policy, security team periodically rotates our CosmosDb keys with the updated keys in Azure Key Vault. We need to deal with this changing key in our spring weblfux/reactive application. From the library, once a CosmosAsyncClient is created from master key there is no way to change it so we need to rebuild it from `CosmosClientBuilder`. When `new CosmosClientBuilder().buildAsyncClient()` is invoked from a webflux handler, we got an error from the low level `DocumentClient` when it is trying to 'warm up' with a blocking call.

We can work around this by putting `new CosmosClientBuilder().buildAsyncClient()` to an executor but I think this is a bug because creating an async client from a webflux handler (without using executors) seems like a legitimate use case.

***Exception or Stack Trace***
```
05:25:00.597 INFO  c.a.c.i.RxDocumentClientImpl - Initializing DocumentClient [4] with serviceEndpoint [https://xxxx-cosmosdb-sql-dev.documents.azure.com:443/], connectionPolicy [ConnectionPolicy{httpNetworkRequestTimeout=PT1M, tcpNetworkRequestTimeout=PT5S, connectionMode=DIRECT, maxConnectionPoolSize=1000, idleHttpConnectionTimeout=PT1M, idleTcpConnectionTimeout=PT0S, userAgentSuffix='', throttlingRetryOptions=RetryOptions{maxRetryAttemptsOnThrottledRequests=9, maxRetryWaitTime=PT30S}, endpointDiscoveryEnabled=true, preferredRegions=[Switzerland North], multipleWriteRegionsEnabled=true, proxyType=null, inetSocketProxyAddress=null, readRequestsFallbackEnabled=true, connectTimeout=PT5S, idleTcpEndpointTimeout=PT1H, maxConnectionsPerEndpoint=130, maxRequestsPerConnection=30, tcpConnectionEndpointRediscoveryEnabled=true}], consistencyLevel [Session], directModeProtocol [Tcp]05:25:00.598 ERROR c.a.c.i.RxDocumentClientImpl - unexpected failure in initializing client.
java.lang.RuntimeException: java.lang.IllegalStateException: block()/blockFirst()/blockLast() are blocking, which is not supported in thread reactor-http-epoll-3
        at com.azure.cosmos.implementation.http.ReactorNettyClient.attemptToWarmupHttpClient(ReactorNettyClient.java:118)
        at com.azure.cosmos.implementation.http.ReactorNettyClient.createWithConnectionProvider(ReactorNettyClient.java:98)
        at com.azure.cosmos.implementation.http.HttpClient.createFixed(HttpClient.java:61)
        at com.azure.cosmos.implementation.RxDocumentClientImpl.httpClient(RxDocumentClientImpl.java:617)
        at com.azure.cosmos.implementation.RxDocumentClientImpl.<init>(RxDocumentClientImpl.java:410)
        at com.azure.cosmos.implementation.RxDocumentClientImpl.<init>(RxDocumentClientImpl.java:262)
        at com.azure.cosmos.implementation.RxDocumentClientImpl.<init>(RxDocumentClientImpl.java:230)
        at com.azure.cosmos.implementation.AsyncDocumentClient$Builder.build(AsyncDocumentClient.java:243)
        at com.azure.cosmos.CosmosAsyncClient.<init>(CosmosAsyncClient.java:129)
        at com.azure.cosmos.CosmosClientBuilder.buildAsyncClient(CosmosClientBuilder.java:779)
```

**To Reproduce**
Just run the below code inside a webflux handler to get CosmosAsyncClient and query database. The `getSecret()` using `SecretAsyncClient` is OK but `CosmosClientBuilder.buildAsyncClient()` is not

***Code Snippet***

```java
SecretAsyncClient secretAsyncClient = new SecretClientBuilder().buildAsyncClient()
...
Mono<CosmosAsyncClient> client = secretAsyncClient.getSecret(KEY_NAME).map(
  s -> s.getValue()
).map(
  key -> new CosmosClientBuilder()
                        .endpoint(HOST)
                        .key(key)
                        .buildAsyncClient()
);
return client.flatMap(
   ...
);
```

**Expected behavior**
Exception shouldn't be thrown when  `new CosmosClientBuilder().buildAsyncClient()` is called

**Screenshots**

**Setup (please complete the following information):**
 - OS: Linux
 - IDE: IntelliJ
 - Library/Libraries: com.azure:azure-sdk-bom:1.1.0
 - Java version: 11
 - App Server/Environment: AKS
 - Frameworks: Spring Boot WebFlux 2.6.3

If you suspect a dependency version mismatch (e.g. you see `NoClassDefFoundError`, `NoSuchMethodError` or similar), please check out [Troubleshoot dependency version conflict article](https://aka.ms/azsdk/java/dependency/troubleshoot) first. If it doesn't provide solution for the problem, please provide:
- verbose dependency tree (`mvn dependency:tree -Dverbose`)
- exception message, full stack trace, and any available logs

**Additional context**

**Information Checklist**
Kindly make sure that you have added all the following information above and checkoff the required fields otherwise we will treat the issuer as an incomplete report
- [ x ] Bug Description Added
- [ x ] Repro Steps Added
- [ x ] Setup information Added

**Comment by stliu** [comment]
are you creating a new SecretClient and DocumentClient every time a web handler is called (per request)?

it is common to rotate a key, but I'd suggest you can use the spring cloud azure's secret management and auto configuration feature to do that, all you need to do is restart the app when key is rotated.

**Comment by stevenylai** [comment]
Not on every request since that would be too costly. The current logic is as follows:
1. `SecretAsyncClient` (not `SecretClient`) is created in a constructor only once with authentication set to use managed identity.
2. Upon the first request, we will create `CosmosAsyncClient` with the code segment I showed.
3. Subsequent API calls we will use `SecretAsyncClient` created in step 1 to see if the key is changed. `CosmosAsyncClient` is re-created only when a change in the master key is detected.

I don't think we are notified upon key rotation since this is managed by a different team and we need to go through a small deployment process (submit tickets etc) to restart all the services using CosmosDb. So that's why the step 3 is in place.

I think the issue here is that `new CosmosClientBuilder().buildAsyncClient()` should be expected to work in case we need to rebuild the client in an async client? Alternatively if the library can provide a way to set/change the master key after the async client is built, that would also work.

**Comment by kushagraThapar** [comment]
@stevenylai  - you can use `public CosmosClientBuilder credential(AzureKeyCredential credential)` API of `CosmosClientBuilder` - and update the keys directly through `AzureKeyCredential` class. That way you don't have to create new cosmos clients again and again. That approach is incorrect because that will be costly in terms of performance and memory. 
Its better to just rotate the keys by calling `update` API of `AzureKeyCredential` class.

**Comment by stevenylai** [comment]
OK. I think this should work. Thanks for pointing to `AzureKeyCredential`
