### ISSUE TITLE
[QUERY]Question regarding Pagination page size

### ISSUE THREAD

**Issue by loudywen** [Azure/azure-sdk-for-java#30586]
Hi I have a question regarding the difference between ` Iterable<FeedResponse<Family>>` and `Page<Family`. The former is the native way to loop through all the pages, the later is the `Spring` way.

The page size for each page has huge different between two implementation so I would like to understand what make this difference and which one is the correct one.

Here are the snippet for my test.

This is the native approach and I am able to get **297** pages total and have some pages has the size less than 100 that is because that is the indication of the end of a particular phyical partion I understant that and have no issue with it.
```
          int pageSize = 100;
          
          Iterable<FeedResponse<Family>> feedResponseIterator = container.queryItems(query, queryOptions, Family.class)
                    .iterableByPage(continuationToken, pageSize);
          
          for (FeedResponse<Family> page : feedResponseIterator) {
               // do whatever we want for each page
          }
```

Here is the `Spring` approach. From the [doc](https://github.com/Azure/azure-sdk-for-java/tree/main/sdk/cosmos/azure-spring-data-cosmos#spring-data-custom-query-pageable-and-sorting), it already mentioned:
> Due to this variable number of returned items in every iteration, user should not rely on the totalPageSize, and instead iterating over pageable should be done in this way.

But the pages that return from this implementation is **2088** and lots of pages just has 1 record!
```
         int pageSize = 100;
          int pageNumber = 0;
          String token = null;
          CosmosPageRequest pageRequest = new CosmosPageRequest(0, pageSize, token);

          Page<Family> recoveryRecordResult = this.repository.getRecoveryRecord(pageRequest);
          if (recoveryRecordResult.getContent().size() < 100) {
               log.info("page: {} has size: {} which is less than {}", pageNumber, recoveryRecordResult.getContent().size(), pageSize);
          }

          while (recoveryRecordResult.hasNext()) {
               CosmosPageRequest temp = (CosmosPageRequest) recoveryRecordResult.nextPageable();
               token = temp.getRequestContinuation();
               pageNumber++;
               Pageable nextPageable = recoveryRecordResult.nextPageable();
               recoveryRecordResult = this.repository.getRecoveryRecord(nextPageable);
               if (recoveryRecordResult.getContent().size() < 100) {
                    log.info("page: {} has size: {} which is less than {}", pageNumber, recoveryRecordResult.getContent().size(),
                             pageSize);
               }
          }
```

So you see the issure here? **If I want to show the pagination on the UI (contiunation token will be used) and use the `Spring` implemation, it will have 2088 pages and lots of the page only has 1 record.** 

Why the `Spring` approach has such huge different regarding pagination? And how to resolve it if our dev team insist on use the `Azure-spring-data-cosmos`

**Comment by loudywen** [comment]
This is screenshot for the Spring approach. I would like to know that why after detected the cross partition activity then the pages increased (244 -> 297) and return less record in a page? 

![image](https://user-images.githubusercontent.com/706038/186189128-4d99876f-4cf4-4235-85ff-06e3efb9545f.png)
![image](https://user-images.githubusercontent.com/706038/186189148-6e656d0d-d2a3-44a1-ba54-e25e76463b1d.png)
![image](https://user-images.githubusercontent.com/706038/186189170-a80a5102-5cae-4b1f-a142-dbf8892bd092.png)

**Comment by kushagraThapar** [comment]
@trande4884 - can you please take a look at this, thanks!

**Comment by loudywen** [comment]
One more thing to add, when I use one of the token from those pages that only has 1 record, I am getting 100 record back actully.

**Comment by trande4884** [comment]
@loudywen I am looking into this and trying to understand what is going on with the page sizes, although it is a challenge as I have no test datasets as large as the one you are working with.

I do not understand what you mean when you say using the token from a page with 1 record, you get 100 records back. I am assuming you mean using the request continuation token for a pageable that got 1 record? This will just simply get the next page I believe as every time you call nextPageable() there is not a new token, the same token is used for every page so you can't simply use the token to get page x again.

**Comment by trande4884** [comment]
@loudywen as for the pages going from 244 to 297, can you share the offset, total, ect for page 31 like you did for page 32? Just expand out recoveryRecordResult in that screen shot also.

**Comment by loudywen** [comment]
@trande4884  Thanks for the reply :)

For this  ` I am assuming you mean using the request continuation token for a pageable that got 1 record` . Yes 

For this `This will just simply get the next page I believe as every time you call nextPageable() there is not a new token, the same token is used for every page so you can't simply use the token to get page x again.`.  I believe I checked each page has a new token but it only has 1 record in that page. Then I tried to use that token to see if I will get 1 record back but it is not . I got 100 instead.

Would you please first explain from the screenshot I posted, why the pages incresead from 244 -> 297 after reached the end of the partition? 

Also here is the log I got with Spring code snippet. this just portion of the log, lots of them only has 1 record. 
```
2022-08-22 19:31:49,307 INFO  [restartedMain] com.walmart.intech.armada.api.mystuff.MyDemo simulateCreateRecoveryRecord - page: 2282 has size: 1 which is less than 100 
                 
2022-08-22 19:31:50,379 INFO  [restartedMain] com.walmart.intech.armada.api.mystuff.MyDemo simulateCreateRecoveryRecord - page: 2283 has size: 1 which is less than 100 
                 
2022-08-22 19:31:51,224 INFO  [restartedMain] com.walmart.intech.armada.api.mystuff.MyDemo simulateCreateRecoveryRecord - page: 2284 has size: 1 which is less than 100 
                 
2022-08-22 19:31:52,115 INFO  [restartedMain] com.walmart.intech.armada.api.mystuff.MyDemo simulateCreateRecoveryRecord - page: 2285 has size: 1 which is less than 100 
                 
2022-08-22 19:31:53,126 INFO  [restartedMain] com.walmart.intech.armada.api.mystuff.MyDemo simulateCreateRecoveryRecord - page: 2286 has size: 1 which is less than 100 
                 
2022-08-22 19:31:53,932 INFO  [restartedMain] com.walmart.intech.armada.api.mystuff.MyDemo simulateCreateRecoveryRecord - page: 2287 has size: 1 which is less than 100 
                 
2022-08-22 19:31:54,746 INFO  [restartedMain] com.walmart.intech.armada.api.mystuff.MyDemo simulateCreateRecoveryRecord - page: 2288 has size: 1 which is less than 100 
                 
2022-08-22 19:31:55,549 INFO  [restartedMain] com.walmart.intech.armada.api.mystuff.MyDemo simulateCreateRecoveryRecord - page: 2289 has size: 1 which is less than 100 
                 
2022-08-22 19:31:56,471 INFO  [restartedMain] com.walmart.intech.armada.api.mystuff.MyDemo simulateCreateRecoveryRecord - page: 2290 has size: 1 which is less than 100 
                 
2022-08-22 19:31:57,420 INFO  [restartedMain] com.walmart.intech.armada.api.mystuff.MyDemo simulateCreateRecoveryRecord - page: 2291 has size: 1 which is less than 100 
                 
2022-08-22 19:31:58,330 INFO  [restartedMain] com.walmart.intech.armada.api.mystuff.MyDemo simulateCreateRecoveryRecord - page: 2292 has size: 1 which is less than 100 
                 
2022-08-22 19:31:59,175 INFO  [restartedMain] com.walmart.intech.armada.api.mystuff.MyDemo simulateCreateRecoveryRecord - page: 2293 has size: 1 which is less than 100 
                 
2022-08-22 19:32:00,027 INFO  [restartedMain] com.walmart.intech.armada.api.mystuff.MyDemo simulateCreateRecoveryRecord - page: 2294 has size: 1 which is less than 100 
                 
2022-08-22 19:32:00,913 INFO  [restartedMain] com.walmart.intech.armada.api.mystuff.MyDemo simulateCreateRecoveryRecord - page: 2295 has size: 1 which is less than 100 
                 
2022-08-22 19:32:01,785 INFO  [restartedMain] com.walmart.intech.armada.api.mystuff.MyDemo simulateCreateRecoveryRecord - page: 2296 has size: 1 which is less than 100 
                 
2022-08-22 19:32:02,615 INFO  [restartedMain] com.walmart.intech.armada.api.mystuff.MyDemo simulateCreateRecoveryRecord - page: 2297 has size: 1 which is less than 100 
                 
2022-08-22 19:32:03,459 INFO  [restartedMain] com.walmart.intech.armada.api.mystuff.MyDemo simulateCreateRecoveryRecord - page: 2298 has size: 1 which is less than 100 
                 
2022-08-22 19:32:04,274 INFO  [restartedMain] com.walmart.intech.armada.api.mystuff.MyDemo simulateCreateRecoveryRecord - page: 2299 has size: 1 which is less than 100 
                 
2022-08-22 19:32:05,147 INFO  [restartedMain] com.walmart.intech.armada.api.mystuff.MyDemo simulateCreateRecoveryRecord - page: 2300 has size: 1 which is less than 100 
                 
2022-08-22 19:32:06,015 INFO  [restartedMain] com.walmart.intech.armada.api.mystuff.MyDemo simulateCreateRecoveryRecord - page: 2301 has size: 1 which is less than 100 
                 
2022-08-22 19:32:06,857 INFO  [restartedMain] com.walmart.intech.armada.api.mystuff.MyDemo simulateCreateRecoveryRecord - page: 2302 has size: 1 which is less than 100 
                 
2022-08-22 19:32:07,687 INFO  [restartedMain] com.walmart.intech.armada.api.mystuff.MyDemo simulateCreateRecoveryRecord - page: 2303 has size: 1 which is less than 100 
```

**Comment by loudywen** [comment]
@trande4884  here you go, here is the page from 27 to 33.  the size of each page will just keep decreasing and at the end only 1 record on the page.  Also, the token is **requestContinuation** is different for each page (_plz ignore the token with the blue color that is just a reference_.)

![image](https://user-images.githubusercontent.com/706038/186742253-dd8f8e4b-0173-43b9-86ca-7f9eb15bf0c0.png)
![image](https://user-images.githubusercontent.com/706038/186742279-84c3d298-1002-4a3f-9204-49162856e686.png)
![image](https://user-images.githubusercontent.com/706038/186742299-28057e63-693b-4305-ad25-e27d238312f1.png)
![image](https://user-images.githubusercontent.com/706038/186742308-4a0434aa-e5b2-4c58-9be8-051544e53ef2.png)
![image](https://user-images.githubusercontent.com/706038/186742317-776169ae-2330-4547-adc6-dcc9d7f8728e.png)
![image](https://user-images.githubusercontent.com/706038/186742328-fddf2814-0d06-4b9e-89d6-f8bbed09b426.png)
![image](https://user-images.githubusercontent.com/706038/186742342-12fc269b-398a-46c2-af3c-29c8a43512a3.png)

**Comment by loudywen** [comment]
HI @trande4884 is any update regarding the issue? Since our design is base on the page size thing.

**Comment by trande4884** [comment]
@loudywen I have been investigating this issue and we developed a plan of action today. I will be working on implementation and will link the PR here once I have the code ready.

**Comment by loudywen** [comment]
thanks @trande4884

**Comment by loudywen** [comment]
@trande4884  i got work aroud for the issue here is my code.  Instead of pass the nextPageable to repository, I just explicit define a new `CosmosPageRequest` and use it.


```
  int pageSize = 100;
          int pageNumber = 0;
          int documentCount = 0;
          String token = null;
          
          Instant start = Instant.now();
          try {
               do {
                    
                    CosmosPageRequest pageRequest = new CosmosPageRequest(pageNumber, pageSize, token);
                    
                    Page<AuditTransaction> recoveryRecordResult = this.repository.getRecoveryRecord(pageRequest);
                    if (recoveryRecordResult.getContent().size() < 100) {
                         log.info("page: {} has size: {} which is less than {}", pageNumber, recoveryRecordResult.getContent().size(),
                                   pageSize);
                    }
                    
                    addToRecoveryRecord(recoveryRecordResult, pageNumber, token);
                    documentCount += recoveryRecordResult.getContent().size();
                    token = ((CosmosPageRequest) recoveryRecordResult.nextPageable()).getRequestContinuation();
                    pageNumber++;
                    
               } while (token != null);
               
          }
          catch (Exception ex) {
               log.error("========== Page {} encounter error ==========\n {}", pageNumber, ex.getMessage());
               throw new RuntimeException(ex);
               
          }
```

Also the reason why the size of each page changed after the end of partition, I guess that is because in the CosmosTemplate you are setting the pageSize like this
```

        contentSize = result.size();
        int pageSize;
        if (contentSize < pageable.getPageSize() && contentSize > 0) {
            pageSize = contentSize;
        } else {
            pageSize = pageable.getPageSize();
        }

```

**Comment by trande4884** [comment]
@loudywen yes that is a good work around until we can improve this functionality. You are correct about that block of code being a big part of the issue and I am working on the new solution currently and hope to have it in PR very soon!

**Comment by loudywen** [comment]
@trande4884  I read your Task12Notes.doc. So in the PR will you implement the accepted solution? If yes that would be nice :)
> The root cause is not actually in the total pages calculation, but in the way we handle the end of a partition. If the requested page size is 10 but we only get 7 results on the first partition, we should get results from the next partition to fill out the last 3 results and not simply return the 7 from the first partition.

**Comment by trande4884** [comment]
@loudywen that is correct, you can see the PR linked to this issue now and I am hoping to have it closed out very soon!

**Comment by loudywen** [comment]
@trande4884 what version should I use?

**Comment by trande4884** [comment]
@loudywen It will be in the 3.27 version which is not yet released, you can monitor here for when that release does come out:
https://github.com/Azure/azure-sdk-for-java/blob/main/sdk/cosmos/azure-spring-data-cosmos/CHANGELOG.md#bugs-fixed-1

**Comment by loudywen** [comment]
@trande4884  got it. thx again. by the way just one question when use the azure spring data cosmos where can I set the continuation token size limit? from the native implementation I know where to do it but not the spring

**Comment by trande4884** [comment]
@loudywen can you please open a new issue for this? I believe you are referring to ResponseContinuationTokenLimitInKb which we do not yet have a way to set from Spring. If you open a new bug for this I can work on the implementation so that you can set the property.
