### ISSUE TITLE
Camel Azure Service Bus - How to manually call abandon and complete methods from ServiceBusReceiverAsyncClient and how to do the manual complete when the process is done 

### ISSUE THREAD

**Issue by Venkatesh728** [Azure/azure-sdk-for-java#30610]
#Camel Route Builder class:

@OverRide
public void configure() {
from(azureServicebus(queueName).connectionString(Endpoint).amqpTransportType().disableAutoComplete(true).receiverClient(ServiceBusReceiverAsyncClient)
.to(....)
}

##From the above endpoint,

How to implement the manual acknowledgment of the processed message to the ASB.
How to call abandon or complete when my process has been done.

**Comment by joshfree** [comment]
Hi @Venkatesh728 thanks for posting these questions.  @ZejiaJiang from the Service Bus SDK team will follow up with you shortly.

In the mean time, additional information including samples on how to get started are available here: https://github.com/Azure/azure-sdk-for-java/blob/main/sdk/servicebus/azure-messaging-servicebus/README.md

/cc @Azure/azsdk-sb-java

**Comment by Venkatesh728** [comment]
Hi @joshfree Thanks for sharing the link... Had gone through some of the topics. Will go through the remaining.

**Comment by Venkatesh728** [comment]
Hi @ZejiaJiang ,

I am enabling disableAutoComplete() in the camel exchange endpoint. But couldn't do the manual complete or abandon.Could you please let me know how to do in camel azure service bus through java

**Comment by Venkatesh728** [comment]
Hi @joshfree any update on the above query

**Comment by ZejiaJiang** [comment]
Hi @Venkatesh728 ,

Sorry for delay replying, I'm oof last week, now I'm working on this issue. I haven't used camel before, I'm looking through the documentation.

**Comment by Venkatesh728** [comment]
Hi @ZejiaJiang , no problem could you please revert back as soon as you get solution through it.

**Comment by ZejiaJiang** [comment]
@Venkatesh728 Sure!

**Comment by Venkatesh728** [comment]
@ZejiaJiang I need ServiceBusReceivedMessage instance to make ServiceBusReceiverAsyncClient to call complete(ServiceBusReceivedMessage) method when successfully message has been processed and to call abandon(ServiceBusReceivedMessage) method when some exception occurs.

**Comment by ZejiaJiang** [comment]
@Venkatesh728 

Yeah, I got your point. 

After a quick look in documentation and source code, I didn't find any mothod to customized `ServiceBusReceivedMessage instance`. I know you want to process message after `ServiceBusReceivedMessage instance` receiving messages and base on process message result to call `complete()` or `abandon()`.

For lack of documentation and example, the package `camel` is not provided by microsoft, I need some time to understant how the `camel` works, hence if you need a quick response, create a query PR in `camle` repo may be a better approach.

Currently, I guess maybe in `.to()` method we can do some thing to process the message, I'm going through the `to` documentation. I write some code may help you if you are more familiar with `to`:

```java
ServiceBusReceiverAsyncClient receiver = new ServiceBusClientBuilder()
                .connectionString(CONNECTION_STRING)
                .receiver()
                .queueName(QUEUE_NAME)
                .disableAutoComplete()
                .buildAsyncClient();

        from(azureServicebus("path").receiverAsyncClient(receiver))
                .log("The content is ${body}")
                .to(""); // do something here , use the receiver created below to call complete() or abandon() method.
```

**Comment by ZejiaJiang** [comment]
It may need to use `process()`

here is some code snippet:
```java
ServiceBusReceiverAsyncClient receiver = new ServiceBusClientBuilder()
                .connectionString(CONNECTION_STRING)
                .receiver()
                .queueName(QUEUE_NAME)
                .disableAutoComplete()
                .buildAsyncClient();

        from(azureServicebus("path").receiverAsyncClient(receiver))
                .log("The content is ${body}")
                .process(exchange -> {
                    ServiceBusReceivedMessage message = exchange.getIn().getBody(ServiceBusReceivedMessage.class);
                    //do something.
                    receiver.complete(message);
                });
```

**Comment by Venkatesh728** [comment]
ServiceBusReceivedMessage message = exchange.getIn().getBody(ServiceBusReceivedMessage.class);

It is giving as nullpointer exception

**Comment by ZejiaJiang** [comment]
@Venkatesh728 

Yeah, I read some doc and source code,  try the code locally, still not find how to customized the receiveMessage instance. 

`complete()` and `abandon()` need the origin message to update position and status.

Sorry for that `camel` is not provided by microsoft and lack of doc/sample, and we have no idea how it works, hence you may need to create a query issue in `camel` repo to figure out how to complete message for service bus.

**Comment by Venkatesh728** [comment]
@ZejiaJiang okay can you send me the camel git repo link to post the issue?

**Comment by ZejiaJiang** [comment]
@Venkatesh728 

Here is the camel github repo: https://github.com/apache/camel

I found a related PR: https://github.com/apache/camel/pull/7279 it seems like camel didn't support complete message manually.

I think they create issue in JIRA: https://issues.apache.org/jira/projects/CAMEL/issues/CAMEL-18435?filter=allopenissues you can create a query issue in JIRA

**Comment by Venkatesh728** [comment]
Yes @ZejiaJiang thank you
