### ISSUE TITLE
[Service Bus] Create Troubleshooting Guide

### ISSUE THREAD

**Issue by JoshLove-msft** [Azure/azure-sdk-for-java#30617]
Here is the [template]( https://gist.github.com/JoshLove-msft/4b3ffbc041067602612a2d81fe514a97) that each language can follow to ensure all topics are covered in a consistent way.

As part of this work, we should update relevant exceptions to link out to aka.ms links that point to the corresponding section of the Troubleshooting guide, similar to what we did for [Identity](https://azure.grep.app/search?q=aka.ms&filter%5Brepo%5D%5B0%5D=Azure/azure-sdk-for-net&filter%5Blang%5D%5B0%5D=C%23&filter%5Bpath%5D%5B0%5D=sdk/identity/Azure.Identity/).

**Comment by ki1729** [comment]
Troubleshooting guide for java was added in PR: https://github.com/Azure/azure-sdk-for-java/pull/31987
