### ISSUE TITLE
[Question]How to query logs from Application Insights

### ISSUE THREAD

**Issue by ivywei0125** [Azure/azure-sdk-for-java#30624]
**Question**
How to query logs from Application Insights?
I found that `azure-applicationinsights-query` was Deprecated. We should use `azure-monitor-query` instead.
https://github.com/Azure/azure-sdk-for-java/blob/main/sdk/monitor/azure-monitor-query/migration-guide.md

While using `azure-applicationinsights-query`, I got logs from Application Insights by appID. 
Example code like that:
`ApplicationInsightsDataClient.querys().execute(appId, "traces | where Timegenerated ago(1h)")`

Switch to `azure-monitor-query`, I tried to get logs from Application Insights by appID.
Example code like that:
`logsQueryClient.queryWorkspace(appId, "traces | where Timegenerated ago(1h)", QueryTimeInterval.ALL)`
Then I got the error message said that "workspace not found"

I'm not sure if I use the wrong api or it's not supported to query logs from application insights

***Why is this not a Bug or a feature Request?***

**Setup (please complete the following information if applicable):**
 - OS: [e.g. Windows]
 - IDE: [e.g. IntelliJ]
 - Library/Libraries: [e.g. com.azure:azure-monitor-query:1.0.9 ]
 
 **Information Checklist**
 Kindly make sure that you have added all the following information above and checkoff the required fields otherwise we will treat the issuer as an incomplete report
- [x] Question Added
- [x] Setup information Added

**Comment by joshfree** [comment]
@srnagar can you please follow up with @ivywei0125

**Comment by ivywei0125** [comment]
I have found what I need.
Thanks all~
