### ISSUE TITLE
DefaultSyncPoller::waitForCompletion(Duration timeout) not timing out as expected [BUG]

### ISSUE THREAD

**Issue by noraabiakar** [Azure/azure-sdk-for-java#30648]
**Describe the bug**
[waitForCompletion(Duration timeout)](https://github.com/Azure/azure-sdk-for-java/blob/main/sdk/core/azure-core/src/main/java/com/azure/core/util/polling/SyncPoller.java#L47) does not time out. 

The documentation of the function explains that the timeout param is "the duration to wait for polling completion." which implies that if the poller state is not SUCCESSFULLY_COMPLETED or FAILED within timeout then the `waitForCompletion` call would timeout and throw an exception. However, when this was tested, and when we dug into the code (see [here on line 115](https://github.com/Azure/azure-sdk-for-java/blob/main/sdk/core/azure-core/src/main/java/com/azure/core/util/polling/DefaultSyncPoller.java#L115) and [here](https://projectreactor.io/docs/core/release/api/reactor/core/publisher/Flux.html#timeout-java.time.Duration-)), it looked like the timeout is actually related to the interval between 2 consecutive responses from the poller, and as long as there is any response from the poller within timeout, `waitForCompletion` will not throw.

**To Reproduce**
I have created a small program that should reproduce the issue:

***Code Snippet***
```
package org.example;
import com.azure.core.util.polling.LongRunningOperationStatus;
import com.azure.core.util.polling.PollResponse;
import com.azure.core.util.polling.PollerFlux;
import reactor.core.publisher.Mono;
import java.time.Duration;
import java.time.LocalDateTime;
import java.util.concurrent.TimeoutException;

public class scratch {
    public static void main(String[] args) {
        LocalDateTime timeToReturnFinalResponse = LocalDateTime.now().plus(Duration.ofSeconds(10));
        // Create poller instance
        PollerFlux<String, String> poller = new PollerFlux<>(Duration.ofMillis(100),
                (context) -> Mono.empty(),
                (context) -> {
                    if (LocalDateTime.now().isBefore(timeToReturnFinalResponse)) {
                        System.out.println("Returning intermediate response.");
                        return Mono.just(new PollResponse<>(LongRunningOperationStatus.IN_PROGRESS,
                                "Operation in progress."));
                    } else {
                        System.out.println("Returning final response.");
                        return Mono.just(new PollResponse<>(LongRunningOperationStatus.SUCCESSFULLY_COMPLETED,
                                "Operation completed."));
                    }
                },
                (activationResponse, context) -> Mono.just("FromServer:OperationIsCancelled"),
                (context) -> Mono.just("FromServer:FinalOutput"));
        try {
            var response = poller.getSyncPoller().waitForCompletion(Duration.ofSeconds(5));
            if (response.getStatus().isComplete()) {
                System.out.println("SUCCESSFULLY_COMPLETED.");
            }
            else {
                System.out.println("FAILED.");
            }
        }
        catch (Exception e) {
            if (!(e.getCause() instanceof TimeoutException)) {
                throw e;
            }
            System.out.println("TIMEOUT.");
        }
    }
}
```

**Expected behavior**
Since the `waitForCompletion` call has a timeout of 5 seconds, but the poller will not complete before 10 seconds, we expect that the program will throw an exception that will be caught and print "TIMEOUT" to stdout. Instead, the program always successfully completes printing "SUCCESSFULLY_COMPLETED" to stdout. (To trigger the expected timeout exception, `waitForCompletion` needs to be called with a timeout of less than 100 ms, which is the polling interval of the `PollerFlux`.)

**Setup (please complete the following information):**
 - OS: Windows
 - IDE: IntelliJ
 - Library/Libraries: com.azure:azure-core:1.26.0
 - Java version: 11

**Comment by alzimmermsft** [comment]
Thank you for reporting this @noraabiakar.

We'll be looking into this alongside #32879 to offer better handling for timeouts when dealing with polling. There'll be an update once a pattern is determined.

**Comment by alzimmermsft** [comment]
Hi @noraabiakar, the behavior of this API was changed and documentation made clearer in #38031, which I believe should resolve this issue. The changes will be released later this month.
