### ISSUE TITLE
[Azure Core] Memory leak on netty-buffer

### ISSUE THREAD

**Issue by mssfang** [Azure/azure-sdk-for-java#30666]
There could be a memory leak on netty-buffer.

More detail report from a customer's reported issue reference:
https://stackoverflow.com/questions/73500609/memory-leak-issue-of-the-object-io-netty-buffer-pooledbytebufallocator-from-jar

Local run stats:
com.azure.core.http.netty.NettyAsyncHttpClientTests
Aug 26, 2022 9:44:13 AM io.netty.util.ResourceLeakDetector reportTracedLeak
SEVERE: LEAK: ByteBuf.release() was not called before it's garbage-collected. See https://netty.io/wiki/reference-counted-objects.html for more information.

**Comment by alzimmermsft** [comment]
Fixed PR resolves tests that report `ByteBuf` leaks, further investigation is on-going on whether the test leak and mentioned StackOverflow are the same root issue.
