### ISSUE TITLE
[BUG] Spring Cloud Stream Eventhubs fails trying to store the checkpoint with an AuthorizationPermissionMismatch

### ISSUE THREAD

**Issue by ceremo** [Azure/azure-sdk-for-java#30686]
**Describe the bug**
I've detected a different behaviour between `com.azure.spring:azure-spring-cloud-stream-binder-eventhubs:2.14.0` and  `com.azure.spring:spring-cloud-azure-stream-binder-eventhubs:4.3.0` using the `Service Principal Authentication`, after migrating the properties configuration using the new namespaces, I'm getting a 403 trying to send a message.

I have an application to reproduce the problem, when I'm using a `Connection String`, it works well.

***Exception or Stack Trace***
[log.txt](https://github.com/Azure/azure-sdk-for-java/files/9444888/log.txt)

**To Reproduce**
I've included a sample application, copy of [this](https://github.com/Azure-Samples/azure-spring-boot-samples/tree/spring-cloud-azure_v4.3.0/eventhubs/spring-cloud-azure-stream-binder-eventhubs/eventhubs-binder). First of all, the `application-newversion.yml` has to be filled with the EventHubs configuration using `Service Principal Authentication`, after that, the application can be executed (`mvn spring-boot:run`), the error will be shown.

This sample is configured to use the 4.3.0 version and `Service Principal Authentication`, but it could be modified easily to work with `Connection String` or using the 2.4.0 version, this can be achieved modifying the `pom.xml` to replace `spring-cloud-azure-stream-binder-eventhubs` with `azure-spring-cloud-stream-binder-eventhubs` dependency, and using `spring.profiles.active` property to enable the `oldversion` profile. Only it fails when 4.3.0 version with `Service Principal Authentication` using same credentials.

**Expected behavior**
Same behaviour as 2.4.0 version.

**Comment by moarychan** [comment]
Hi @ceremo , thanks for using Spring Cloud Azure!

You need to assign the build-in roles to your eventhub when using service principal authentication, please refer to the below docs:
https://microsoft.github.io/spring-cloud-azure/4.3.0/reference/html/index.html#authorize-access-with-azure-active-directory 
https://docs.microsoft.com/en-us/azure/role-based-access-control/role-assignments-portal?tabs=current

**Comment by ceremo** [comment]
Thanks @moarychan, adding the `Azure Event Hubs Data Receiver`, `Azure Event Hubs Data Sender` and `Storage Blob Data Owner` roles solves the problem, it seems that using the new version requires also a revision of the assigned roles.

**Comment by ceremo** [comment]
Hi @moarychan, 

I would like to confirm with you if the role modification is normal and part of the migration to the 4.x version. 
Using the 2.4.0 version, the Service Principal role was `Contributor` (defined in the EventHubs and Storage).
Using the 4.3.0 version, we had to include the `Azure Event Hubs Data Receiver`, `Azure Event Hubs Data Sender` and `Storage Blob Data Owner`.

Thxs.

**Comment by yiliuTo** [comment]
Hi @ceremo , yes the role modification is part of the changes in 4.x between 2.x, you can refer to the migration guides for more details: 
- [migration for authentication](https://microsoft.github.io/spring-cloud-azure/current/reference/html/appendix.html#migration-guide-authentication)
- [migration for Spring Cloud Stream Eventhubs](https://microsoft.github.io/spring-cloud-azure/current/reference/html/appendix.html#_from_azure_spring_cloud_stream_binder_eventhubs_to_spring_cloud_azure_stream_binder_eventhubs)

**Comment by yiliuTo** [comment]
Hi @ceremo I will close this issue since my above reply gets acked from you, and feel free to reopen it if you have any other questions.
