### ISSUE TITLE
[FEATURE REQ] Improve the MS doc configuration of credential info to avoid using any secerts

### ISSUE THREAD

**Issue by moarychan** [Azure/azure-sdk-for-java#30701]
### Context
Delete the password configuration since Spring Cloud Azure supports the default credential. This's also reported by MS doc issue: [It is using service principal which is security risk in Azure](https://github.com/MicrosoftDocs/azure-dev-docs/issues/879)

### Goal
Use a simple way to introduce the Spring Cloud Azure usage, it should cover all the Spring Cloud Azure docs in MS doc and lots of readme doc, but the reference doc should introduce client secret usage.

**Comment by stliu** [comment]
https://learn.microsoft.com/en-us/azure/developer/java/spring-framework/configure-spring-boot-starter-java-app-with-cosmos-db should not use `spring.cloud.azure.cosmos.key=replace-your-access-key-here`

**Comment by hui1110** [comment]
Created PR: https://github.com/MicrosoftDocs/azure-dev-docs-pr/pull/3942. The fix for this [issue](https://github.com/MicrosoftDocs/azure-dev-docs/issues/879) is also included in this PR.

**Comment by hui1110** [comment]
PR merged, now close this issue.
