### ISSUE TITLE
 [QUERY] How should application developers handle Batch Submission failures from the Async Client

### ISSUE THREAD

**Issue by atom8899** [Azure/azure-sdk-for-java#30727]
**Query/Question**
How are those leveraging the Spring Cloud Streaming Azure Service Bus Binder supposed to handle Batch Submission Failures? 

https://github.com/Azure/azure-sdk-for-java/blob/30152b0dbd398e8658fb1ae4a5acf230efc6db3a/sdk/servicebus/azure-messaging-servicebus/src/main/java/com/azure/messaging/servicebus/ServiceBusSenderAsyncClient.java#L819

We are regularly encountering this issue every weekend where submissions to ServiceBus fail and messages are dropped. We're capable of alerting on these issues thanks to the logging but we end up dropping messages because we can't react programmatically to the failure. Is there a way to bubble this up? Can I choose to perform the submissions synchronously? 

***Why is this not a Bug or a feature Request?***
It appears that the intended behavior here is to simply log the failure. That may be due to the fact that there is no mechanism to notify the caller that the submission actually failed or the developers chose not to implement it. 

**Setup (please complete the following information if applicable):**
Rather simple setup:
```
spring:
  cloud:
    stream:
      default-binder: servicebus-topic
``` 

Leveraging StreamBridge for submission
 ```
  public boolean publishEvent(Event e, Map<String, Object> additionalHeaders) {
        MessageBuilder<Event> messageBuilder = MessageBuilder.withPayload(e);
        additionalHeaders.get().forEach((key, value) -> messageBuilder.setHeaderIfAbsent(key, value));
        return streamBridge.send(bindingName, messageBuilder.build());
    }
```
 
 **Information Checklist**
Snippet of library versions via our gradle build
```
	id 'org.springframework.boot' version '2.5.6'
	...
	implementation 'org.springframework.boot:spring-boot-starter-web'
	implementation 'org.springframework.cloud:spring-cloud-config-client:3.0.5'
	implementation 'org.springframework.boot:spring-boot-starter-validation:2.5.6'
	implementation 'org.springframework.boot:spring-boot-starter-actuator:2.5.6'
	implementation 'com.azure.spring:azure-spring-cloud-stream-binder-servicebus-topic:2.13.0'
        implementation 'org.springframework.boot:spring-boot-starter-data-jpa:2.5.6'
	implementation 'org.springframework.retry:spring-retry:1.3.1'
	implementation 'org.springdoc:springdoc-openapi-ui:1.6.6'
```

**Comment by yiliuTo** [comment]
Hi @atom8899 you can handle the submission failures with Spring Cloud Stream [Error Channels](https://docs.spring.io/spring-cloud-stream/docs/current/reference/html/spring-cloud-stream.html#polled-errors), which can be enbled by enabling the error channel of your output binding and then register a `ServiceActivator` to handle the failure messages.

**Comment by atom8899** [comment]
Thank you @yiliuTo I will look into implementing this. Do you have any example implementations to share?

**Comment by yiliuTo** [comment]
We have a [sample](https://github.com/Azure-Samples/azure-spring-boot-samples/tree/spring-cloud-azure_v4.3.0/eventhubs/spring-cloud-azure-stream-binder-eventhubs/eventhubs-binder) for producer error channels for Spring Cloud Stream Event Hubs binder but the error channel part also works for Service Bus topic binder:
1. For how to enable the error channel, in that sample we enabled all the producer binding [here](https://github.com/Azure-Samples/azure-spring-boot-samples/blob/73aa6bf3ab90aae42684e634f0df9adf04a825fa/eventhubs/spring-cloud-azure-stream-binder-eventhubs/eventhubs-binder/src/main/resources/application.yaml#L27), you can enable the error channel for a specific output binding via properties of `spring.cloud.stream.bindings.<binding-name>.producer.error-channel-enabled=true`,  refer to [Spring Cloud Stream reference](https://docs.spring.io/spring-cloud-stream/docs/current/reference/html/spring-cloud-stream.html#_producer_properties) for more details.
2. For how to register a `ServiceActivator` for the error channel, our sample shows [here](https://github.com/Azure-Samples/azure-spring-boot-samples/blob/73aa6bf3ab90aae42684e634f0df9adf04a825fa/eventhubs/spring-cloud-azure-stream-binder-eventhubs/eventhubs-binder/src/main/java/com/azure/spring/sample/eventhubs/binder/EventHubBinderApplication.java#L33).
