### ISSUE TITLE
[FEATURE REQ] Bulk Support in Spring Data for Cosmos DB

### ISSUE THREAD

**Issue by TheovanKraay** [Azure/azure-sdk-for-java#30726]
**Is your feature request related to a problem? Please describe.**
Integrate bulk support into cosmos-spring-data

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Information Checklist**
Kindly make sure that you have added all the following information above and checkoff the required fields otherwise we will treat the issuer as an incomplete report
- [ ] Description Added
- [ ] Expected solution specified

**Comment by kushagraThapar** [comment]
This has been implemented.
