### ISSUE TITLE
[BUG] Cosmos ReadItem returns empty item JSONObject

### ISSUE THREAD

**Issue by wposner** [Azure/azure-sdk-for-java#30742]
**Describe the bug**
When using the v4 CosmosDB sync client, calling the .readItem method on a container returns an empty JSONObject

***Exception or Stack Trace***
NA

**To Reproduce**

***Code Snippet***
CosmosClient client=new CosmosClientBuilder()
    			.endpoint(endpoint)
    			.key(key)
    			.connectionSharingAcrossClientsEnabled(true)
    			.consistencyLevel(ConsistencyLevel.EVENTUAL)
    			.buildClient();
CosmosDatabase db=client.GetDatabase(dbName);
CosmosContainer container=db.getContainer(containerName);
CosmosItemResponse<JSONObject> o = container.readItem(id, new PartitionKey (partitionKey), JSONObject.class);
return o.getItem();

**Expected behavior**
o.getItem() returns a JSONObject containing the document retrieved during the point read

**Screenshots**

**Setup (please complete the following information):**
 - OS: MacOS 12.5.1
 - IDE: Eclipse 2022-06 (4.24.0)
 - Library/Libraries: azure-core 1.31.0, azure-cosmos 4.34.0
 - Java version: 18.0.2
 - App Server/Environment: NA--Running as a console application directly within Eclipse
 - Frameworks: NA

**Additional context**

**Information Checklist**
Kindly make sure that you have added all the following information above and checkoff the required fields otherwise we will treat the issuer as an incomplete report
- [x] Bug Description Added
- [x] Repro Steps Added
- [x] Setup information Added

**Comment by kushagraThapar** [comment]
@wposner - is the item present in the database?
Also, are you getting any exceptions?
Please see these samples for more information on how to use the SDK - https://github.com/Azure-Samples/azure-cosmos-java-getting-started

**Comment by wposner** [comment]
> @wposner - is the item present in the database? Also, are you getting any exceptions? Please see these samples for more information on how to use the SDK - https://github.com/Azure-Samples/azure-cosmos-java-getting-started

The item is present in the database and there are no exceptions.  The JSONObect that should be returned is simply null.  This issue also exists after performing and UpdateDocument and also calling getItem().  I've verified my document is updated in the specified container, so again, no exceptions--just a null JSONObject.

**Comment by TheovanKraay** [comment]
@wposner Java V4 SDK does not support [org.json.JSONObject](https://stleary.github.io/JSON-java/org/json/JSONObject.html) directly, but has com.fasterxml.jackson.databind.JsonNode, which you can pass to a JSONObject if you prefer. Like below:

`JSONObject o = new JSONObject(container.readItem(id, new PartitionKey (partitionKey), JsonNode.class).getItem());`

**Comment by wposner** [comment]
@TheovanKraay using your code does not return the document object.  It returns the following:

`{integralNumber=false, double=false, valueNode=false, floatingPointNumber=false, bigInteger=false, nodeType=OBJECT, float=false, textual=false, int=false, long=false, empty=false, pojo=false, missingNode=false, number=false, boolean=false, null=false, array=false, binary=false, short=false, containerNode=true, bigDecimal=false, object=true}`

**Comment by TheovanKraay** [comment]
@wposner sorry, left off `toString()`, this should work:

```java
JSONObject o = new JSONObject(container.readItem(id, new PartitionKey (partitionKey), JsonNode.class).getItem().toString());
```
Can you link which **Java V4 SDK** samples are you referring to? The samples Kushagra linked above are for V4 only, they do not contain `JSONObject.class`. Perhaps you are referring to older samples for V2?

**Comment by TheovanKraay** [comment]
please also refer [here](https://github.com/Azure-Samples/azure-cosmos-java-sql-api-samples) for more extensive Java V4 SDK samples (sync and async).

**Comment by wposner** [comment]
> please also refer [here](https://github.com/Azure-Samples/azure-cosmos-java-sql-api-samples) for more extensive Java V4 SDK samples (sync and async).

Yes...older examples that do return JSON objects use JSONObject.  The new examples do not return anything or they return a custom class.  Most do not return anything.  But I can confirm that getItem().toString() after doing a patchItem using JsonNode as the class type still returns null.

**Comment by kushagraThapar** [comment]
@rinatmini pls take a look at this, thanks!

**Comment by wposner** [comment]
Hi Everyone…

I was able to work around this issue programmatically. I just changed the way I was processing the paging result. The odd thing is that the code consistently worked against one instance of cosmos and consistently did not work against another.

Wayne Posner
702-684-0097
________________________________

**Comment by TheovanKraay** [comment]
I think this item can be closed. We've clarified above that the confusion is caused by old samples (v2) using JSONObject which v4 SDK no longer supports directly. We don't need to update samples, because the samples being referred to are not for latest (v4) SDK. The fact that doing `getItem().toString()` after doing a patchItem using JsonNode as the class type still returns null is an orthogonal issue, for which a separate issue should be created.
