### ISSUE TITLE
[BUG] ObjectMapperHolder destroys Spring autoconfiguration-pattern

### ISSUE THREAD

**Issue by Klaus-BPG-IT** [Azure/azure-sdk-for-java#30741]
**Describe the bug**
Using Spring-Boot you get some Utility-Beans configured automatically depending on the Libraries in your classpath.
For Example the Jackson ObjecMapper class ist configured using properties and dependencies from the classpath and published in the Spring-ApplicationContext to be used by every component of the Spring Application.

Azure-messaging for Spring breaks this Pattern by using the [com.azure.spring.messaging.implementation.converter.ObjectMapperHolder](https://github.com/Azure/azure-sdk-for-java/blob/main/sdk/spring/spring-messaging-azure/src/main/java/com/azure/spring/messaging/implementation/converter/ObjectMapperHolder.java) 

***Exception or Stack Trace***
This Antipattern leads to:
```console
 com.fasterxml.jackson.databind.exc.InvalidDefinitionException: Java 8 date/time type `java.time.LocalDateTime` not supported by default: add Module "com.fasterxml.jackson.datatype:jackson-datatype-jsr310" to enable handling (through reference chain: de.bertelsmann.ols.old.model.partner.DmdParPartner["accedeDate"])
```
for Example

**To Reproduce**
Customize your Jackson-Framework like described in the Spring-Reference Documentation and you will see that this Customisations are noch used by the Azure-Messaging System.

**Expected behavior**
A Library with the Name "spring-messaging-azure" should integrate with teh Spring-Framework and spacially use Spring Configuration-Options.

**Setup (please complete the following information):**
Pom.xml with:
```xml
<parent>
	<groupId>org.springframework.boot</groupId>
	<artifactId>spring-boot-starter-parent</artifactId>
	<version>2.7.1</version>
	<relativePath /> <!-- lookup parent from repository -->
</parent>
<properties>
	<java.version>11</java.version>
	<spring-cloud.version>2021.0.3</spring-cloud.version>
        <jackson.datatype.jsr310.version>2.13.3</jackson.datatype.jsr310.version>
</properties>
<dependencyManagement>
	<dependencies>
		<dependency>
			<groupId>org.springframework.cloud</groupId>
			<artifactId>spring-cloud-dependencies</artifactId>
			<version>${spring-cloud.version}</version>
			<type>pom</type>
			<scope>import</scope>
		</dependency>
		<dependency>
		      <groupId>com.azure.spring</groupId>
		      <artifactId>spring-cloud-azure-dependencies</artifactId>
		      <version>4.3.0</version>
		      <type>pom</type>
		      <scope>import</scope>
		</dependency>
		<dependency>
		      <groupId>com.fasterxml.jackson.datatype</groupId>
		      <artifactId>jackson-datatype-jsr310</artifactId>
		      <version>${jackson.datatype.jsr310.version}</version>
		</dependency>
	</dependencies>
</dependencyManagement>
```

**Comment by yiliuTo** [comment]
@Klaus-BPG-IT thanks for reporting this, we will look into and fix it. Currently for a workaround, since the Message Converter supports to be configured, thus you can provide your own bean of the related message converter, e.g., [EventHubsMessageConverter](https://github.com/Azure/azure-sdk-for-java/blob/fb1c99315a1f681bb1c8f47384c5d36e771da0df/sdk/spring/spring-messaging-azure-eventhubs/src/main/java/com/azure/spring/messaging/eventhubs/support/converter/EventHubsMessageConverter.java#L60), with the qualified ObjectMapper to meet your requests.

**Comment by yiliuTo** [comment]
@Klaus-BPG-IT  Could you share which Spring Cloud Azure library you are using? Then I can provide more detailed solutions for you.

**Comment by stliu** [comment]
I'm wondering how spring boot and other libs handle this case, I think there are other components need some kind of json support and probably require a `ObjectMapper`, how do they handle this, do they create a new one or get one from spring context or something else?

@saragluna we probably should have a design before actually fixing it to make sure the fix is expected and won't introduce any other issues.


- [ ] Design Spec reviewed and signoff

**Comment by Klaus-BPG-IT** [comment]
When i use Spring-Boot i expect that librarys for Spring-Boot use the ObjectMapper from the ApplicationContext or they create a specific ObjectMapper-Bean in the ApplicationContext.
I think the Design-Flaw and what Fix is expexted was described in my first Post.

**Comment by stliu** [comment]
> When i use Spring-Boot i expect that librarys for Spring-Boot use the ObjectMapper from the ApplicationContext or they create a specific ObjectMapper-Bean in the ApplicationContext. I think the Design-Flaw and what Fix is expexted was described in my first Post.

@Klaus-BPG-IT I agree with you, that's the core principal of  IoC

**Comment by Netyyyy** [comment]
Spring Boot uses the default ObjectMapper created by [JacksonAutoConfiguration](https://github.com/spring-projects/spring-boot/blob/d2b1f8eaebc2c5b9346622e933e91b8e531469ce/spring-boot-project/spring-boot-autoconfigure/src/main/java/org/springframework/boot/autoconfigure/jackson/JacksonAutoConfiguration.java#L130), which will be managed by IoC. So we can use the default ObjectMapper to replace the one created by [ObjectMapperHolder](https://github.com/Azure/azure-sdk-for-java/blob/6c75da052a98f9c73468f05809c26bfb8ef1b2f9/sdk/spring/spring-messaging-azure/src/main/java/com/azure/spring/messaging/implementation/converter/ObjectMapperHolder.java#L8). 
And I think AWS also uses this way to get an ObjectMapper in [S3AutoConfiguration](https://github.com/awspring/spring-cloud-aws/blob/6a7eb277a4505215b9266e554b0779f9ba8178e3/spring-cloud-aws-autoconfigure/src/main/java/io/awspring/cloud/autoconfigure/s3/S3AutoConfiguration.java#L130).
