### ISSUE TITLE
[FEATURE REQ] Support passwordless connection for Azure PostgreSQL flexible server in Spring

### ISSUE THREAD

**Issue by backwind1233** [Azure/azure-sdk-for-java#30763]
## Context
`azure-identity-providers-jdbc-postgresql` and `spring-cloud-azure-starter-jdbc-postgresql` can work with single postgresql server, we should make sure they can work with  flexible postgresql server too.

1. Manual test to make sure they can work
2. Create a IT to make sure they can work in pipeline.
3. Test multiple flexible versions.

- `azure-identity-providers-jdbc-postgresql` will be been rename to `azure-identity-extensions` in GA  [#32282](https://github.com/Azure/azure-sdk-for-java/pull/32282).

## Goal

Make sure our released postgresql plugin libraries also support AAD authentication with different postgresql **flexible** server versions.

## Tasks/Plan
- We want to use an integration test to verify that our spring-cloud-azure-starter-jdbc-postgresql can work. Considering testing all PSQL server versions would require lots of efforts, we will only test one PSQL version. 
  - If it's possible we may try to run IT with a random postgresql server, if not easy, we will pin the server version number.	
- We will try to test PSQL flexible server, but if it's not available yet, we will test with single server.

**Comment by saragluna** [comment]
The flexible server public preview has been delayed.

**Comment by stliu** [comment]
manually tested but no IT yet, waiting for PG Flexible to public preview

**Comment by backwind1233** [comment]
This [doc](https://learn.microsoft.com/en-us/azure/developer/java/spring-framework/migrate-postgresql-to-passwordless-connection?tabs=sign-in-azure-cli%2Cspring%2Cservice-connector%2Cassign-role-service-connector) can't work with postgresql flexible server while creating role.
<img width="491" alt="image" src="https://user-images.githubusercontent.com/4465723/204448111-82eb2565-2de5-40ae-abe8-e1cef2c755bc.png">

**Comment by fangjian0423** [comment]
This configuration parameter also not work:

```
todo=> SET aad_validate_oids_in_tenant = off;
ERROR:  unrecognized configuration parameter "aad_validate_oids_in_tenant"
```

**Comment by backwind1233** [comment]
We should test different postgresql versions.

> This configuration parameter also not work:
> 
> ```
> todo=> SET aad_validate_oids_in_tenant = off;
> ERROR:  unrecognized configuration parameter "aad_validate_oids_in_tenant"
> ```

@fangjian0423 Yes, also not work for me, but with service [connector](https://learn.microsoft.com/en-us/azure/service-connector/how-to-integrate-postgres?toc=%2Fazure%2Fdeveloper%2Fintro%2Ftoc.json&bc=%2Fazure%2Fdeveloper%2Fintro%2Fbreadcrumb%2Ftoc.json#java-jdbc-system-assigned-managed-identity), it can work.

**Comment by backwind1233** [comment]
JDBC Postgresql  AAD plugin | Postgresql flexible version | AAD Support Status
-- | -- | --
azure-identity-providers-jdbc-postgresql:1.0.0-beta.1 | 14.4 | passed
azure-identity-providers-jdbc-postgresql:1.0.0-beta.1 | 13.7 | passed
azure-identity-providers-jdbc-postgresql:1.0.0-beta.1 | 12.11 | passed
azure-identity-providers-jdbc-postgresql:1.0.0-beta.1 | 11.16 | passed

**Comment by stliu** [comment]
what's the exactly goal of this issue?

**Comment by backwind1233** [comment]
> what's the exactly goal of this issue?

@stliu  The goal of the issue is:

Make sure our released postgresql plugin library also support AAD authentication with different **postgresql flexible server versions**, so that if a java user using postgresql flexible server(no matter which version) want to use AAD authentication, we can give them a quick-start link and tell them confidently "you can use this feature by our postgresql library."

**Comment by backwind1233** [comment]
> 

@fangjian0423 we should check this doc [Manage Azure AD roles using SQL](https://learn.microsoft.com/en-us/azure/postgresql/flexible-server/how-to-manage-azure-ad-users)

**Comment by backwind1233** [comment]
> > This configuration parameter also not work:
> > ```
> > todo=> SET aad_validate_oids_in_tenant = off;
> > ERROR:  unrecognized configuration parameter "aad_validate_oids_in_tenant"
> > ```
> 
> @fangjian0423 Yes, also not work for me, but with service [connector](https://learn.microsoft.com/en-us/azure/service-connector/how-to-integrate-postgres?toc=%2Fazure%2Fdeveloper%2Fintro%2Ftoc.json&bc=%2Fazure%2Fdeveloper%2Fintro%2Fbreadcrumb%2Ftoc.json#java-jdbc-system-assigned-managed-identity), it can work.

@fangjian0423 we should check this doc [Manage Azure AD roles using SQL](https://learn.microsoft.com/en-us/azure/postgresql/flexible-server/how-to-manage-azure-ad-users).

**Comment by fangjian0423** [comment]
It works good for me, and I created a [todo-java-postgresql-terraform](https://github.com/fangjian0423/todo-java-postgresql-terraform) template that using postgresql flexible server passwordless.

Quick start and migration docs for PostgreSQL flexible server will also update @hui1110

**Comment by fangjian0423** [comment]
> > > This configuration parameter also not work:
> > > ```
> > > todo=> SET aad_validate_oids_in_tenant = off;
> > > ERROR:  unrecognized configuration parameter "aad_validate_oids_in_tenant"
> > > ```
> > 
> > 
> > @fangjian0423 Yes, also not work for me, but with service [connector](https://learn.microsoft.com/en-us/azure/service-connector/how-to-integrate-postgres?toc=%2Fazure%2Fdeveloper%2Fintro%2Ftoc.json&bc=%2Fazure%2Fdeveloper%2Fintro%2Fbreadcrumb%2Ftoc.json#java-jdbc-system-assigned-managed-identity), it can work.
> 
> @fangjian0423 we should check this doc [Manage Azure AD roles using SQL](https://learn.microsoft.com/en-us/azure/postgresql/flexible-server/how-to-manage-azure-ad-users) to use postgresql flexible server.

It works good for me, and I created a [todo-java-postgresql-terraform](https://github.com/fangjian0423/todo-java-postgresql-terraform) template that using postgresql flexible server passwordless.

Quick start and migration docs for PostgreSQL flexible server will also update @hui1110

**Comment by backwind1233** [comment]
Updates

There are few steps to run an IT.
Step1: Provision Azure Resources for integration tests.
Step2: Configure environment variables.
Step3: Run integration tests.

In order to test passwordless feature in postgresql flexible server, in **step1** it's needed to provision an Azure postgresql flexible server with Azure AD Admin enabled.

To enable Azure AD Admin, 
For now, it can be done by 
1. Azure [portal](https://learn.microsoft.com/en-us/azure/postgresql/flexible-server/how-to-manage-azure-ad-users#create-or-delete-azure-ad-administrators-using-azure-portal-or-azure-resource-manager-arm-api).
2. Azure [CLI](https://learn.microsoft.com/en-us/cli/azure/postgres/flexible-server/ad-admin?view=azure-cli-latest) which needs azure-cli:[2.43.0](https://learn.microsoft.com/en-us/cli/azure/release-notes-azure-cli#rdbms).

The Azure AD Admin is not available in arm template for postgresql [flexible server](https://learn.microsoft.com/azure/templates/microsoft.dbforpostgresql/flexibleservers?pivots=deployment-language-arm-template).


We need to use ARM template to provision Azure resource to run IT.
- In ARM template, we can run azure-cli commands, but the highest version of azure-cli supported in ARM templates is 2.42.0, it doesn't contain the function to enable Azure AD Admin.
- The ARM templates of postgesql flexible servers don't support Azure AD Admin yet.

**Comment by backwind1233** [comment]
Draft [commit](https://github.com/Azure/azure-sdk-for-java/commit/8f9096bc0aac5e9e2cf6825f7613b0701c05547a), when Azure ARM templates support Azure CLI:2.43.0, we can create a PR with this [commit](https://github.com/Azure/azure-sdk-for-java/commit/8f9096bc0aac5e9e2cf6825f7613b0701c05547a).

**Comment by jcontti-axa** [comment]
I cannot login using a service principal to flexible server...I got this error:
`ATAL:  Service Principals cannot generate AAD_AUTH_TOKENTYPE_APP_USER tokens for role`
any help?

**Comment by saragluna** [comment]
@chenrujun please help take a look at this.

**Comment by backwind1233** [comment]
> 

@jcontti-axa How did you configure the applications, what's the error stack, could you share more details?

**Comment by jcontti-axa** [comment]
> > 
> 
> Hi @jcontti-axa, thanks for reaching out.
> 
> How did you configure the applications, what's the error stack, could you share more details?

Please reject my previous comment, I was misreading the documentation. thanks!

**Comment by saragluna** [comment]
Closing this issue now, please create a new issue for any further requests.
