### ISSUE TITLE
Make sure azure-identity-providers-jdbc-mysql can work with flexible mysql server

### ISSUE THREAD

**Issue by backwind1233** [Azure/azure-sdk-for-java#30762]
## Context
`azure-identity-providers-jdbc-mysql` can work with single mysql server, we should make sure it can work with flexible mysql server too.

## Goal
- [x] Test passwordless can work with flexible MySQL server.
- [x] Add an IT to get accessToken, connect to DB and exec Query.

Since flexible MySQL service is not GA now, in this PR https://github.com/Azure/azure-sdk-for-java/pull/30982, the IT is used with MySQL single server, when the flexible MySQL service is GA, a new IT with MySQL flexible server will be added.

**Comment by backwind1233** [comment]
Link PR: https://github.com/Azure/azure-sdk-for-java/pull/30982

**Comment by saragluna** [comment]
MySQL flexible server has been GA.

**Comment by saragluna** [comment]
The manual tests have been finished and can work with MySQL flexible server. But it's not easy to enable that on the IT pipeline due to the admin consent thing.

**Comment by saragluna** [comment]
Closing this issue now, switching IT to flexible server will be tracked in https://github.com/Azure/azure-sdk-for-java/issues/31229.
