### ISSUE TITLE
[QUERY] Examples/Samples for patch filter

### ISSUE THREAD

**Issue by 544cl** [Azure/azure-sdk-for-java#30771]
**Query/Question**
Are there samples/examples for using **spark.cosmos.write.patch.filter**. in the [Configuration Reference](https://github.com/Azure/azure-sdk-for-java/blob/main/sdk/cosmos/azure-cosmos-spark_3_2-12/docs/configuration-reference.md#patch-config) i cant find any useful information.

**Setup (please complete the following information if applicable):**
 - App Environment: Azure Synapse
 - Library/Libraries: azure-cosmos-spark_3-2_2-12-4.12.2.jar
 
 **Information Checklist**
 Kindly make sure that you have added all the following information above and checkoff the required fields otherwise we will treat the issuer as an incomplete report
- [x] Query Added
- [x] Setup information Added

**Comment by TheovanKraay** [comment]
Please find documentation for patch here: https://learn.microsoft.com/en-us/azure/cosmos-db/nosql/quickstart-spark?tabs=scala. More samples are here: https://github.com/Azure/azure-sdk-for-java/blob/main/sdk/cosmos/azure-cosmos-spark_3_2-12/Samples/Scala/PatchSample.scala

**Comment by DjilFM** [comment]
Hi, 
I have a question : can we do a predicate based on the incoming data like "where c.date < newData.date".
Thanks in advance.
