### ISSUE TITLE
Terminology Change: Update Terminology in Codes From Credential Free to Passwordless

### ISSUE THREAD

**Issue by backwind1233** [Azure/azure-sdk-for-java#30787]
## Context
The terminology:`Credential free` in our codes and docs need to be changed from `Credential free`  to `Passwordless`.
[`Passwordless`](https://en.wikipedia.org/wiki/Passwordless_authentication) is a more widely used terminology as oppose to `Credential free`.

## Goal
- Update the terminology in **codes**(issues include): comments, parameters, package names, Class names, created issues.

## Reference
Issue: [Update Terminology in Docs ](https://github.com/Azure/azure-sdk-for-java/issues/30877).

**Comment by saragluna** [comment]
Closed in #30788.
