### ISSUE TITLE
Test Passwordless Feature Based on the User’s Usage Scenarios

### ISSUE THREAD

**Issue by backwind1233** [Azure/azure-sdk-for-java#30790]
## Context
We should test the Passwordless feature in a more productive environment from users scenarios.

## Goal
- [x] Users using our libraries with passwordless feature should work as expected in a long run environment.

**Comment by hui1110** [comment]
#### Test environment

- Spring Boot version: 2.7.2 
- Java version: 11
- spring-cloud-azure-starter-jdbc-mysql version: 4.4.0-beta.1
- spring-cloud-azure-starter-jdbc-postgresql: 4.4.0-beta.1

**Test project**: https://github.com/hui1110/passwordless-test-mysql-postgresql

#### Scenarios

Authentication | DB | Library | Platform | PoolSize | QPS
-- | -- | -- | -- | -- | --
MSI | Azure MySQL | spring-cloud-azure-starter-jdbc-mysql | VM/ASA | 20-50 | 10-20
SP | Azure MySQL | spring-cloud-azure-starter-jdbc-mysql | VM/ASA | 20-50 | 10-20
password | Azure MySQL | spring-cloud-azure-starter-jdbc-mysql | VM/ASA | 20-50 | 10-20
MSI | Azure PostgreSQL | spring-cloud-azure-starter-jdbc-postgresql | VM/ASA | 20-50 | 10-20
SP | Azure PostgreSQL | spring-cloud-azure-starter-jdbc-postgresql | VM/ASA | 20-50 | 10-20
password | Azure PostgreSQL | spring-cloud-azure-starter-jdbc-postgresql | VM/ASA | 20-50 | 10-20

#### Plan

For each scenario:

1. Create MySQL/PostgreSQL on Azure, insert test table, and create test more than 1000 records.

2. Create VM/ASA to deploy test projects and configure MSI/SP.

3. Create test projects and add test code.

   - Add spring-boot-starter-data-jpa,spring-boot-starter-web as dependencies.
   - Expose Query endpoints(/query)
   - Set connection_poll_size = (20~50)
   - Log config.
      - Config log level to show log when requesting accessToken.
      - Add info log when DB operation success, and add error log when DB operation fails.
4. Deploy test projects to Test VM/ASA and test.

5. Test

   - Use [wrk](https://github.com/wg/wrk)  to run tests for 24 hours
   - Set concurrent thread = connection_poll_size * (10~30)
6. Check

   - Check the result of wrk.
   - Check the log to make sure getToken success and DB operation success.
   - Check the test table in the database.

**Comment by hui1110** [comment]
This test plan is used to check that the number of times the token is obtained through Azure AD is as expected.

#### Test environment

- Spring Boot version: 2.7.2 
- Java version: 11
- spring-cloud-azure-starter-jdbc-mysql version: 4.4.0-beta.1
- spring-cloud-azure-starter-jdbc-postgresql: 4.4.0-beta.1
- Azure Spring Apps
- Virtual machines

**Test project**: https://github.com/hui1110/passwordless-test-mysql-postgresql

#### Scenarios

Authentication | DB | Library | Platform 
-- | -- | -- | -- 
MSI | Azure MySQL/Azure PostgreSQL | spring-cloud-azure-starter-jdbc-mysql/spring-cloud-azure-starter-jdbc-postgresql | VM/ASA
SP | Azure MySQL/Azure PostgreSQL | spring-cloud-azure-starter-jdbc-mysql/spring-cloud-azure-starter-jdbc-postgresql | VM/ASA

#### Plan

1. Create MySQL/PostgreSQL on Azure, insert test table.

2. Create VM/ASA to deploy test projects and configure MSI/SP.

3. Create test projects and add test code.

   - Add spring-boot-starter-data-jpa,spring-boot-starter-web as dependencies.
   - Expose Query endpoints(/query)
   - Configure the log level to display logs when an accessToken is requested through Azure AD.

4. Deploy test projects to Test VM/ASA and test.

5. Test

   - To run tests with [wrk](https://github.com/wg/wrk), connection requests should have time intervals.

6. Check

   - Whether the number of times to connect to Azure AD to get the token is as expected.

**Comment by hui1110** [comment]
Close it and the test is done.
