### ISSUE TITLE
[FEATURE REQ] Post a release blog for Spring Cloud Azure 6.0.0.beta4

### ISSUE THREAD

**Issue by moarychan** [Azure/azure-sdk-for-java#30794]
### Context
Post a release blog for Spring Cloud Azure 6.0.0.beta4 with highlights.

### Goal
Provide the 6.0.0.beta.4 release notes for a Spring Boot 3 announcement blog.

**Comment by moarychan** [comment]
Spring Cloud Azure 6.0.0-beta.2 release note: https://github.com/Azure/azure-sdk-for-java/releases/spring-cloud-azure_6.0.0-beta.2

**Comment by moarychan** [comment]
Will use this issue to track the release blog for the Spring Cloud Azure 6.0.0-beta.3.

**Comment by chenrujun** [comment]
FYI: 
1. Blog will be displayed here: https://devblogs.microsoft.com/azure-sdk/
2. PR should be created here: https://github.com/Azure/azure-sdk-blog

**Comment by stliu** [comment]
I think one issue https://github.com/Azure/azure-sdk-blog/issues/318 is enough for this task?  and the https://github.com/Azure/azure-sdk-blog/issues/318 is included in our github project https://github.com/orgs/Azure/projects/94/views/1
