### ISSUE TITLE
Go through all Postgres SQL passwordless migration guide/quickstart/tutorial to make sure by following them can work

### ISSUE THREAD

**Issue by saragluna** [Azure/azure-sdk-for-java#30799]
Since most of the passwordless docs are ready, we should follow instructions of each doc to make sure all of them can work correctly. The docs included:

- [x] https://github.com/Azure/azure-sdk-for-java/issues/30347
  PR: https://github.com/MicrosoftDocs/azure-docs-pr/pull/208670
- [x] https://github.com/Azure/azure-sdk-for-java/issues/30341
  PR: https://github.com/MicrosoftDocs/azure-dev-docs-pr/pull/3442
- [x] https://github.com/Azure/azure-sdk-for-java/issues/29783
  PR: https://github.com/MicrosoftDocs/azure-dev-docs-pr/pull/3442
- [x] https://github.com/Azure/azure-sdk-for-java/issues/29782
  PR: https://github.com/MicrosoftDocs/azure-dev-docs-pr/pull/3476
- [x] https://github.com/Azure/azure-sdk-for-java/issues/29781
  PR: https://github.com/MicrosoftDocs/azure-dev-docs-pr/pull/3491

**Comment by hui1110** [comment]
**Quickstart: Use Java and JDBC with Azure Database for PostgreSQL** works fine.

There are the following suggestions:

1. <img width="313" alt="image" src="https://user-images.githubusercontent.com/58474919/196616438-03640d8f-2198-42c2-9eb6-3c416bfe0f87.png">  looks more like a database name，can be replaced with `AZ_DATABASE_SERVER_NAME`
2. It is recommended to add the database name to the environment variable, as in the [migration guide](https://learn.microsoft.com/en-us/azure/developer/java/spring-framework/migrate-postgresql-to-passwordless-connection?tabs=sign-in-azure-cli%2Cjava%2Cservice-connector%2Cservice-connector-identity%2Cassign-role-service-connector#0-prepare-the-working-environment).

**Comment by hui1110** [comment]
**Quickstart: Use Spring Data JPA with Azure Database for PostgreSQL** works fine.

There are the following suggestions:

1. `AZ_DATABASE_NAME` looks more like a database name，can be replaced with `AZ_DATABASE_SERVER_NAME`.
2. It is recommended to add the database name to the environment variable, as in the [migration guide](https://learn.microsoft.com/en-us/azure/developer/java/spring-framework/migrate-postgresql-to-passwordless-connection?tabs=sign-in-azure-cli%2Cjava%2Cservice-connector%2Cservice-connector-identity%2Cassign-role-service-connector#0-prepare-the-working-environment).

**Comment by hui1110** [comment]
[Use Spring Data JDBC with Azure Database for PostgreSQL](https://learn.microsoft.com/en-us/azure/developer/java/spring-framework/configure-spring-data-jdbc-with-azure-postgresql?tabs=passwordless) works fine.

There are the following suggestions:

1. `AZ_DATABASE_NAME` looks more like a database name，can be replaced with `AZ_DATABASE_SERVER_NAME`.
2. It is recommended to add the database name to the environment variable, as in the [migration guide](https://learn.microsoft.com/en-us/azure/developer/java/spring-framework/migrate-postgresql-to-passwordless-connection?tabs=sign-in-azure-cli%2Cjava%2Cservice-connector%2Cservice-connector-identity%2Cassign-role-service-connector#0-prepare-the-working-environment).
3. 
<img width="549" alt="image" src="https://user-images.githubusercontent.com/58474919/196621710-d99fd9eb-a281-4b8c-9fd2-97def31eb2fa.png">

In the above `NOTE`, you can add a link to the 4.5.0-beta.1 version [reference documentation](https://learn.microsoft.com/en-us/azure/developer/java/spring-framework/spring-cloud-azure?tabs=maven#postgresql-support) to quickly find an introduction to passwordless connections.

**Comment by hui1110** [comment]
[Migrate an application to use passwordless connections with Azure Database for PostgreSQL](https://learn.microsoft.com/en-us/azure/developer/java/spring-framework/migrate-postgresql-to-passwordless-connection?tabs=sign-in-azure-cli%2Cspring%2Capp-service%2Capp-service-identity%2Cassign-role-azure-cli) can work, but to fix the following problem.

1. 
<img width="605" alt="image" src="https://user-images.githubusercontent.com/58474919/196904024-88d6c61c-f8ec-4b37-838a-05d78f9a7038.png">

File names should be the same

**Comment by hui1110** [comment]
PostgreSQL support [reference doc](https://learn.microsoft.com/en-us/azure/developer/java/spring-framework/spring-cloud-azure?tabs=maven#postgresql-support) can work.

There are the following suggestions:

1. 
<img width="596" alt="image" src="https://user-images.githubusercontent.com/58474919/196905485-fbe208ff-f266-4b59-b49d-7fdc3a7f1c70.png">

Change the file name to `create_ad_user_sp.sql`

**Comment by hui1110** [comment]
Azure Dev Docs: https://github.com/MicrosoftDocs/azure-dev-docs-pr/pull/3743

Azure Docs: https://github.com/MicrosoftDocs/azure-docs-pr/pull/215396

**Comment by hui1110** [comment]
PR merged, now close this issue.
