### ISSUE TITLE
Release 6.0.0-beta.2 for Spring Boot 3.0

### ISSUE THREAD

**Issue by saragluna** [Azure/azure-sdk-for-java#30798]
### Context
Code is ready to release in branch `feature/spring-cloud-azure-6.x`.

### Goal
Refer to issue https://github.com/Azure/azure-sdk-for-java/issues/28060 to release the Spring Cloud Azure 6.0.0.beta2 for Spring Boot 3.

**Comment by snicoll** [comment]
Can't we add `beta1` on start.spring.io already?

**Comment by mmoayyed** [comment]
Hello. I realize the changeset here only addresses spring-cloud. Is there a similar issue, branch or pull request that might address spring-data?

For reference, https://github.com/Azure/azure-sdk-for-java/blob/main/sdk/cosmos/azure-spring-data-cosmos/pom.xml

**Comment by saragluna** [comment]
@snicoll, the `beta.1` release partially failed because of a pipeline issue, so we are going to release the `beta.2` instead.

**Comment by saragluna** [comment]
> Hello. I realize the changeset here only addresses spring-cloud. Is there a similar issue, branch or pull request that might address spring-data support for Spring Boot v3?
> 
> For reference, https://github.com/Azure/azure-sdk-for-java/blob/main/sdk/cosmos/azure-spring-data-cosmos/pom.xml

Hi @mmoayyed, already tracked in #30761, and this module will be included in the next release, but not in this version.

**Comment by mmoayyed** [comment]
Thank you! I appreciate the update.

**Comment by stliu** [comment]
@moarychan  @saragluna  I move this one and another one into this milestone, and I'm wondering why these two   were left in the previous milestone?

**Comment by moarychan** [comment]
Sorry, I forgot to close this one after the[ 6.0.0-beta.2](https://aka.ms/spring/docs/6.0.0-beta.2) release, closing now.
