### ISSUE TITLE
[FEATURE REQ] Samples & reference doc update for Spring Cloud Azure 6.0.0.beta2

### ISSUE THREAD

**Issue by moarychan** [Azure/azure-sdk-for-java#30792]
### Context
Update samples and reference doc based on Spring Cloud Azure 6.0.0.beta2.

### Goal
- [x] Make all the related samples work fine with Spring Cloud Azure 6.0.0.beta2.
- [x] Make the reference doc 6.0.0.beta2 available.

**Comment by stliu** [comment]
@moarychan what's the status of this one? why it is in pending review status? is there anything specific to be reviewed?

**Comment by moarychan** [comment]
Sorry, I forgot to close this one after the[ 6.0.0-beta.2](https://aka.ms/spring/docs/6.0.0-beta.2) release, closing now.
