### ISSUE TITLE
Go through all MySQL passwordless migration guide/quickstart/tutorial to make sure by following them can work

### ISSUE THREAD

**Issue by saragluna** [Azure/azure-sdk-for-java#30801]
Since most of the passwordless docs are ready, we should follow instructions of each doc to make sure all of them can work correctly. The docs included:

- [x] #30346 
  PR: https://github.com/MicrosoftDocs/azure-docs-pr/pull/208242
- [x] #30340 
  PR: https://github.com/MicrosoftDocs/azure-dev-docs-pr/pull/3434
- [x] #29783
  PR: https://github.com/MicrosoftDocs/azure-dev-docs-pr/pull/3419
- [ ] #29224 
  PR: https://github.com/MicrosoftDocs/azure-dev-docs-pr/pull/3423
- [x] #29221 
  PR: https://github.com/MicrosoftDocs/azure-dev-docs-pr/pull/3463

**Comment by Netyyyy** [comment]
close in:
- https://github.com/MicrosoftDocs/azure-dev-docs-pr/pull/3653
- https://github.com/MicrosoftDocs/azure-dev-docs-pr/pull/3639
- https://github.com/MicrosoftDocs/azure-docs-pr/pull/212473
- https://github.com/MicrosoftDocs/azure-dev-docs-pr/pull/3630
- https://github.com/MicrosoftDocs/azure-dev-docs-pr/pull/3617
- https://github.com/MicrosoftDocs/azure-dev-docs-pr/pull/3607
- https://github.com/MicrosoftDocs/azure-dev-docs-pr/pull/3594
- https://github.com/MicrosoftDocs/azure-docs-pr/pull/211129
- https://github.com/MicrosoftDocs/azure-dev-docs-pr/pull/3564
- https://github.com/hui1110/azure-dev-docs-pr/pull/14
- https://github.com/MicrosoftDocs/azure-dev-docs-pr/pull/3553
- https://github.com/MicrosoftDocs/azure-dev-docs-pr/pull/3548
