### ISSUE TITLE
Investigate common Logger interface

### ISSUE THREAD

**Issue by conniey** [Azure/azure-sdk-for-java#3081]
Can we abstract away having folks use slf4j-api? Is it necessary?

**Comment by conniey** [comment]
https://github.com/Azure/autorest-clientruntime-for-java/issues/557

**Comment by JonathanGiles** [comment]
Perhaps this is now considered a duplicate of #3466? @conniey can you confirm or deny?

**Comment by conniey** [comment]
Yup. It looks like there is a  common serviceLogger now.
