### ISSUE TITLE
[QUERY]How to set continuation token size limit in azure-spring-data-cosmos?

### ISSUE THREAD

**Issue by loudywen** [Azure/azure-sdk-for-java#30840]
Hi, I do know how to set it from the native implemenatnion like below, but not sure how to do it in azure-spring-data-cosmos.
```
         CosmosQueryRequestOptions queryOptions = new CosmosQueryRequestOptions();
          queryOptions.setQueryMetricsEnabled(true);
          // here we tell to set the size of the token
          queryOptions.setResponseContinuationTokenLimitInKb(1);

           CosmosPagedFlux<Family> feedResponses = this.familyContainer.queryItems(q1, queryOptions,
                         Family.class);
```

**Comment by joshfree** [comment]
Hi @loudywen sorry that this issue wasn't on our radar.  It appears our labeling bot did not fire when your issue was created.  @backwind1233 could you please follow up on @loudywen's question?

**Comment by backwind1233** [comment]
Hi @kushagraThapar could you help look into this issue?

**Comment by kushagraThapar** [comment]
@loudywen - you can use application.properties to set it - was added in this release sometime back - https://github.com/Azure/azure-sdk-for-java/blob/main/sdk/cosmos/azure-spring-data-cosmos/CHANGELOG.md#3270-2022-09-15 

This readme also has info on how to set it  https://github.com/Azure/azure-sdk-for-java/blob/main/sdk/cosmos/azure-spring-data-cosmos/README.md#setup-configuration-class
