### ISSUE TITLE
Split `Spring Cloud Azure Reference Doc` into multi pages.

### ISSUE THREAD

**Issue by chenrujun** [Azure/azure-sdk-for-java#30847]
## Context

Link to Spring Cloud Aure reference doc: https://docs.microsoft.com/en-us/azure/developer/java/spring-framework/spring-cloud-azure?tabs=maven

This page is too long. It's hard to get specific section even though there is a TOC in the up-right corner.
![image](https://user-images.githubusercontent.com/13167207/189013237-82e28df5-dc37-434f-8595-20e0111e2939.png)

After scroll down, the TOC will out of visibility. It will be harder to find specific section.
![image](https://user-images.githubusercontent.com/13167207/189013420-f9e0b7fd-61a5-45f5-8d7d-ada5679e44c8.png)
 
## Goal 

Split this page, so getting specific section will be easier.

**Comment by hui1110** [comment]
Created PR: https://github.com/MicrosoftDocs/azure-dev-docs-pr/pull/3994.

**Comment by hui1110** [comment]
PR merged, now close this issue.
