### ISSUE TITLE
Terminology Change: Update Terminology in Docs From Credential Free to Passwordless 

### ISSUE THREAD

**Issue by backwind1233** [Azure/azure-sdk-for-java#30877]
## Context
The terminology:`Credential free` in our codes and docs need to be changed from `Credential free`  to `Passwordless`.
[`Passwordless`](https://en.wikipedia.org/wiki/Passwordless_authentication) is a more widely used terminology as oppose to `Credential free`.

## Goal
- Update the terminology in **docs**: wiki, oneNote doc.

## Reference
Issue: [Update Terminology in Codes](https://github.com/Azure/azure-sdk-for-java/issues/30787)

**Comment by Netyyyy** [comment]
close in these PRs:
- https://github.com/MicrosoftDocs/azure-dev-docs-pr/pull/3618
- https://github.com/MicrosoftDocs/azure-dev-docs-pr/pull/3594
