### ISSUE TITLE
CosmosClient possibility to disable SSL hostnameVerification for testing purpopes

### ISSUE THREAD

**Issue by mrkdrd** [Azure/azure-sdk-for-java#30885]
Currently I am not able to run integration tests using cosmosDb (its emulator + testcontainers to start those), since the emulator is running on a docker container, where its hostname is not inside the certificate.

I already tried setting following property: *-Djdk.internal.httpclient.disableHostnameVerification* but it seems that it does not have any effect.

Following this thread: https://github.com/Azure/azure-cosmos-db-emulator-docker/issues/46 I saw that it is able for the go sdk.

I would like to disable the hostname verification of the client when executing tests so that I can successfully connect to an instance on another host.

**Comment by kushagraThapar** [comment]
@milismsft can you please take a look at this.

**Comment by kushagraThapar** [comment]
@milismsft - can you please take a look at this, thanks!

**Comment by milismsft** [comment]
@mrkdrd if you follow EXATLY the public documentation steps as showed in https://learn.microsoft.com/en-us/azure/cosmos-db/docker-emulator-linux?tabs=sql-api%2Cssl-netstd21#run-the-linux-emulator-on-linux-os, you will notice that the host machine's IP address is actually part of the setup.

Running the Linux version of the public emulator in CI, that is a different issue all together actually, and it highly depends on how you setup your agent pool of machines dedicated to run it. We are working on standardizing that process but we don't have much to share at this moment.

Our Linux version of the Cosmos DB public emulator is primarily intended for local machine usage at this time, where the developer has better control over the exact resources allocated to it.

**Comment by congthuc** [comment]
Hi @milismsft ,

I know that with injecting the host IP address, the host can connect to cosmos db in docker but inject the host IP address into the setting up/dockerize is not a clean way and that prevents the automation process.

It should be a way to disable SSL for test/dev environment.

### In docker local environment
Let's take a simple scenario, I have a java application which connecting to cosmos db.
I write a docker-compose file to automated dockerize the whole solution, the cosmos db must to be built and started first, then following will be my java application.
How can I achieve this goal? When building/starting the cosmos db container, the Java application container is not started yet, how can I know the IP address?

Of course above is just an simple scenarios, on the real project, we have some more components, all should be on the same network in docker. 

There is one thing I'm still not clear that my lcoal Java application (directly run on IDE/ or in docker container) can connect to the Cosmos DB on Azure cloud without any issue regarding SSL !??? Can you help me to clarify this?

And if so, when I deploy my Java app and cosmos db app into Azure cloud, no SSL set up would be required?

cc: @kushagraThapar

**Comment by congthuc** [comment]
for the connecting to Cosmos db on Azure, no SSL configuration needed might because the Cert is already imported to local keystore by default!?

**Comment by cnstevenwang** [comment]
encounter the same issue. It's more firendly for integration testing if it could by pass ssl verification
