### ISSUE TITLE
[QUERY] Copy source authorization from access key

### ISSUE THREAD

**Issue by malthe** [Azure/azure-sdk-for-java#30910]
**Query/Question**

In Put Blob From URL we're able to specify a _copy source authorization_, for example a bearer token based on Azure AD (see #29083).

But it is not clear how we might instead provide a signature derived from an account key, one reason being that the "x-ms-date" header is not known in advance.

***Why is this not a Bug or a feature Request?***

It's unclear at this time whether this is a question/query or a feature request.

**Comment by joshfree** [comment]
Hi @malthe thanks for reaching out to us via this GitHub issue.  @jaschrep-msft could you please follow up?  Thanks

**Comment by ibrahimrabab** [comment]
Hi @malthe ,
Thank you for reaching out. In regards to your question, unfortunately we only support AAD for Put Blob from From Url, so it would not be possible to get the x-ms-date from the shared access key. 

You can find more information [here](https://learn.microsoft.com/en-us/rest/api/storageservices/put-blob-from-url)

Let us know if this helped and if you have any more questions.

Thanks!
