### ISSUE TITLE
azure-data-tables - Javadoc precision 

### ISSUE THREAD

**Issue by qgeffard** [Azure/azure-sdk-for-java#30913]
https://github.com/Azure/azure-sdk-for-java/blob/1f13ef9ae44761a5dc4ffa2c5565971b8aa6be04/sdk/tables/azure-data-tables/src/main/java/com/azure/data/tables/TableAsyncClient.java#L690

"@throws TableServiceException If no TableEntity with the same partition key and row key exists" 

Can you confirm this since the API call is @Put("/{table}(PartitionKey='{partitionkey}', RowKey='{rowKey}')") in case  of updateMode == TableEntityUpdateMode.REPLACE

Seems to be an insert or replace.

**Comment by jairmyree** [comment]
Of course, I'll take a look and see if I can confirm the documentation.

**Comment by jairmyree** [comment]
There does appear to be a discrepancy between the documentation and the functionality of the method call. @qgeffard Thank you for pointing this out to us, we will look into resolving this discrepancy.

**Comment by jairmyree** [comment]
@qgeffard  After some testing, I have concluded that the original documentation was correct. When inserting an entity via REPLACE or MERGE that does not exist, the service will return a 404 status code.

**Comment by qgeffard** [comment]
mb then, thanks for checking
