### ISSUE TITLE
Azure Identity October Release Doc Consistency Review

### ISSUE THREAD

**Issue by joshfree** [Azure/azure-sdk-for-java#30919]
tracking item for README, Samples, TROUBLESHOOT, and Changelog consistency review

**Comment by pvaneck** [comment]
Notable consistency updates:

### README

First, based on changes from the past semester:

- [ ] Add disclaimer about `VisualStudioCodeCredential` in ["Authenticate the Client"](https://github.com/Azure/azure-sdk-for-java/blob/main/sdk/identity/azure-identity/README.md#authenticate-the-client)
    - Other languages have text like:
        ```
        It's a [known issue](https://github.com/Azure/azure-sdk-for-java/issues/27364) that `VisualStudioCodeCredential` doesn't work with [Azure Account extension](https://marketplace.visualstudio.com/items?itemName=ms-vscode.azure-account) versions newer than **0.9.11**. A long-term fix to this problem is in progress. In the meantime, consider [authenticating via the Azure CLI](#authenticate-via-the-azure-cli).
        ```
- [ ] Fix formatting (or remove) the credential disclaimer in the `VisualStudioCodeCredential` row of the ["Authenticating via Development Tools"](https://github.com/Azure/azure-sdk-for-java/blob/main/sdk/identity/azure-identity/README.md#authenticating-via-development-tools) table.

#### General consistency + issues

- [ ] Missing `AzurePowerShellCredential` in the [`Authenticating via Development Tools`(https://github.com/Azure/azure-sdk-for-java/blob/main/sdk/identity/azure-identity/README.md#authenticating-via-development-tools) table.
- [ ] In ["Managed Identity Support"](https://github.com/Azure/azure-sdk-for-java/blob/main/sdk/identity/azure-identity/README.md#managed-identity-support) section"
    - [ ] Change `Azure App Service` to `Azure App Service and Azure Functions`.
- Add an example for "Define a custom authentication flow with the ChainedTokenCredential" in the ["Examples"](https://github.com/Azure/azure-sdk-for-java/blob/main/sdk/identity/azure-identity/README.md#examples) section. Other languages have this example. Example is provided in `AzureIdentityExamples.md` so may be okay?
- [ ] At bottom of ["Credential Classes"](https://github.com/Azure/azure-sdk-for-java/blob/main/sdk/identity/azure-identity/README.md#credential-classes) section, fix "chaining credentials" hyperlink.
- [ ] In the ["Credential Classes"](https://github.com/Azure/azure-sdk-for-java/blob/main/sdk/identity/azure-identity/README.md#credential-classes), all the `configuration` links don't seem to actually exist in the wiki. Should they/the column be removed?
- [ ] Add reference link to `OnBehalfOfCredential` in the ["Credential Classes"](https://github.com/Azure/azure-sdk-for-java/blob/main/sdk/identity/azure-identity/README.md#credential-classes) section:
    - `[On-behalf-of authentication](https://docs.microsoft.com/azure/active-directory/develop/v2-oauth2-on-behalf-of-flow)`
- [ ] Fix markdown hyperlink formatting in ["Next Steps"](https://github.com/Azure/azure-sdk-for-java/blob/main/sdk/identity/azure-identity/README.md#next-steps) section

### TROUBLESHOOTING

- [ ] Update wording in ["Troubleshoot Multi Tenant Authentication Issues"](https://github.com/Azure/azure-sdk-for-java/blob/main/sdk/identity/azure-identity/TROUBLESHOOTING.md#troubleshoot-multi-tenant-authentication-issues)
    - "This error was added as part of ~~functional~~ a breaking change to multi tenant authentication..."
- [ ] Fix two "Enable logging" links in ["Troubleshoot default Azure credential authentication issues"](https://github.com/Azure/azure-sdk-for-java/blob/main/sdk/identity/azure-identity/TROUBLESHOOTING.md#troubleshoot-defaultazurecredential-authentication-issues) section.
    - Also remove `VisualStudioCredential` from the list.
- [ ] Create a **"Troubleshoot `ClientAssertionCredential` Authentication Issues"** section which was added by JS a few months ago.
    - [Reference](https://github.com/Azure/azure-sdk-for-js/blob/main/sdk/identity/identity/TROUBLESHOOTING.md#client-assertion-credential-issues)

**Comment by pvaneck** [comment]
FYI, Reference readme + troubleshooting has been merged: https://github.com/Azure/azure-sdk-for-python/pull/26483 
I have notated the majority of the changes that should be made in the above comment. Let me know if additional assistance is needed.

**Comment by billwert** [comment]
@pvaneck "Also remove VisualStudioCredential from the list." in troubleshooting.md - I assume you meant `VisualStudioCodeCredential`?
