### ISSUE TITLE
[Question] migration to com.azure. from com.microsoft.azure for BatchAccount

### ISSUE THREAD

**Issue by ychulovskyy** [Azure/azure-sdk-for-java#30939]
**Query/Question**
Hi Folks,
I'm migrating from   
**com.microsoft.azure**.management.batch.BatchAccount   
 to   
 **com.azure**.resourcemanager.batch.models.BatchAccount.  
Old version had a field called coreQuota but new version doesn't have it.
Maybe I can find the value in another field?

***Why is this not a Bug or a feature Request?***
A clear explanation of why is this not a bug or a feature request?
It's just a question, no code changes required.

**Setup (please complete the following information if applicable):**
 - OS: N/A
 - IDE: N/A
 - Library/Libraries: azure-resourcemanagement-batch
 
 **Information Checklist**
 Kindly make sure that you have added all the following information above and checkoff the required fields otherwise we will treat the issuer as an incomplete report
- [ X] Query Added
- [ X] Setup information Added

**Comment by joshfree** [comment]
@weidongxu-microsoft could you please help route @ychulovskyy's question related to migrating from Track 1 to Track 2 control plane?

**Comment by weidongxu-microsoft** [comment]
@ychulovskyy 

I think it is [dedicatedCoreQuota](https://github.com/Azure/azure-sdk-for-java/blob/main/sdk/batch/azure-resourcemanager-batch/src/main/java/com/azure/resourcemanager/batch/models/BatchAccount.java#L124)

**Comment by ychulovskyy** [comment]
Thanks @weidongxu-microsoft , I'm closing the issue
