### ISSUE TITLE
Support Georedundancy in azure-core

### ISSUE THREAD

**Issue by alzimmermsft** [Azure/azure-sdk-for-java#30953]
Either through a new policy or as part of configuration in the current `RetryPolicy` enable support for georedundancy. A current example of georedundancy can be found in the azure-storage-blob SDK where their `RequestRetryPolicy` can be configured with a secondary host that certain operations can fall over to if the primary host fails with a retryable status. This new feature will need to support multiple SDKs such as AppConfiguration and Tables, and could possibly be used to unify azure-storage-blob's functionality to enable them to use `RetryPolicy` in azure-core.

**Comment by jairmyree** [comment]
I'll take a look at this.

**Comment by joshfree** [comment]
@jairmyree please take a look.  Talk to @christothes as well who is looking at this for the .NET SDK side of the world.

**Comment by jairmyree** [comment]
Since the request for this feature was dropped for Tables, I want to revisit the conversation of whether this is something that should exist in core or not. @alzimmermsft
