### ISSUE TITLE
[FEATURE REQ]Merge support: include changeFeed start time in the header

### ISSUE THREAD

**Issue by xinlian12** [Azure/azure-sdk-for-java#30963]
**Scenario:**
When a merge happens, the child partition will contain documents ordered by LSN but the _ts / creation time of those documents might not be sequential. So when reading the Change Feed by LSN, you can encounter documents with a lower _ts. This becomes problematic when a user consumes the Change Feed using Start Time because:

The first request sends the desired Start Time.
Backend calculates an LSN and returns to the client
Client uses that LSN moving forward.
Because of the previous merge, potentially can receive documents that happened after the Start Time because they have higher LSN than returned in step 2.
 
This only impacts Change Feed Processor and Change Feed Query/Pull model that are started after a merge happened in a partition, not running ones, because when a Partition is merged we currently apply EPK filtering, and with that filtering, we would not get documents from the other parent Partition that could be out of time.

**Proposed change:**
Modify the Continuation Token produced by the SDK (both for Pull Model and the Lease in CFP) to contain the original desired Start Time. Send this value in all requests even after step 3 on the "If-Modified-Since" header. This requires:
Modifying the SDK code that handles the continuation/lease. The Change Feed Pull continuation needs to "remember" the original StartTime. For the lease, we either include that as a new parameter or use the information in the Change Feed Processor Options (assuming the customer does not change them).
Modifying the SDK code that performs Change Feed requests to send the new header obtained from the current continuation/lease

**Comment by kushagraThapar** [comment]
This is done.
