### ISSUE TITLE
Storage Java SDK spotbugs compile issue

### ISSUE THREAD

**Issue by g2vinay** [Azure/azure-sdk-for-java#3096]
Introduction of Storage SDK in spotbugs reporting module causes collision with storage library being referenced by Event Hubs SDK.

[ERROR] /home/vsts/work/1/s/eventhubs/data-plane/azure-eventhubs-eph/src/main/java/com/microsoft/azure/eventprocessorhost/AzureStorageCheckpointLeaseManager.java:[674,34] reference to StorageException is ambiguous
[ERROR]   both class com.microsoft.azure.storage.blob.StorageException in com.microsoft.azure.storage.blob and class com.microsoft.azure.storage.StorageException in com.microsoft.azure.storage match
[ERROR] -> [Help 1]

Due to this Spotbugs report generation fails.
Consequently, currently Storage is excluded from spotbugs reporting module.
But we need to find a way to make storage SDK a part of spotbugs reporting module.

**Comment by rickle-msft** [comment]
This should be resolved when v11 is merged in as we disambiguated type names to allow loading v8 and v11 in the same project without errors
