### ISSUE TITLE
[BUG] NPE error when using deployments.beginCreateAsync() and withExistingResourceGroup

### ISSUE THREAD

**Issue by xieyz1980** [Azure/azure-sdk-for-java#31064]
**Describe the bug**
We  are migrating to the  Azure SDK new version and there's an NPE error  when we call the  beginCreateAsync method of deployments, the code sample is like as below:
          this.deployments()
                .define("vm7")
                .withExistingResourceGroup(resGroup)
                .withTemplate(armTemplate.template)
                .withParameters(armTemplate.parameters)
                .withMode(INCREMENTAL)
                .beginCreateAsync();

***Exception or Stack Trace***
Caused by: java.lang.NullPointerException: value
	at java.base/java.util.Objects.requireNonNull(Objects.java:246)
	at reactor.core.publisher.MonoJust.<init>(MonoJust.java:35)
	at reactor.core.publisher.Mono.just(Mono.java:719)
	at com.azure.resourcemanager.resources.implementation.DeploymentImpl.beginCreateAsync(DeploymentImpl.java:348)

**To Reproduce**
this.deployments()
                .define("vm7")
                .withExistingResourceGroup(resGroup)
                .withTemplate(armTemplate.template)
                .withParameters(armTemplate.parameters)
                .withMode(INCREMENTAL)
                .beginCreateAsync();

Be sure to use the .withExistingResourceGroup method.

***Code Snippet***
The Creatable<ResourceGroup> creatableResourceGroup in DeploymentImpl.java of Azure SDK will be null, if  using the withExistingResourceGroup method, and the NPE will be thrown in the below method of DeploymentImpl.java :

public Mono<Deployment> beginCreateAsync() {
        return Mono.just(this.creatableResourceGroup).flatMap((resourceGroupCreatable) -> {
            return resourceGroupCreatable != null ? this.creatableResourceGroup.createAsync() : Mono.just(this);

**Expected behavior**
Resource should be deploymented when we use the beginCreateAsync method and withExistingResourceGroup with no NPE errors.

**Screenshots**

**Setup (please complete the following information):**
 - OS: Mac Big Sur
 - IDE: [e.g. IntelliJ]IntelliJ
 - Library/Libraries: [e.g. com.azure:azure-core:1.16.0 (groupId:artifactId:version)] com.azure.resourcemanager:azure-resourcemanager:2.18.0
 - Java version: [e.g. 8] 11
 - App Server/Environment: [e.g. Tomcat, WildFly, Azure Function, Apache Spark, Databricks, IDE plugin or anything special]
 - Frameworks: [e.g. Spring Boot, Micronaut, Quarkus, etc] Spring Boot

If you suspect a dependency version mismatch (e.g. you see `NoClassDefFoundError`, `NoSuchMethodError` or similar), please check out [Troubleshoot dependency version conflict article](https://aka.ms/azsdk/java/dependency/troubleshoot) first. If it doesn't provide solution for the problem, please provide:
- verbose dependency tree (`mvn dependency:tree -Dverbose`)
- exception message, full stack trace, and any available logs

**Additional context**

**Information Checklist**
Kindly make sure that you have added all the following information above and checkoff the required fields otherwise we will treat the issuer as an incomplete report
- [x] Bug Description Added
- [x] Repro Steps Added
- [x] Setup information Added

**Comment by xieyz1980** [comment]
@weidongxu-microsoft  @xseeseesee @ChenTanyi @mitchdenny @JimSuplizio 
 Could you help to take a look at this issue?  I don't see any samples to use beginCreateAsync() and withExistingResourceGroup() methods. 
Thanks.

**Comment by weidongxu-microsoft** [comment]
@XiaofeiCao 

Please schedule the diagnostic/fix in this release of this month.

**Comment by XiaofeiCao** [comment]
Close as 2.19.0 released.
