### ISSUE TITLE
Storage SDK Upload NRF Test Memory Issue Investigation

### ISSUE THREAD

**Issue by g2vinay** [Azure/azure-sdk-for-java#3106]
Running Upload NRF test in TransferManagerTest with 4 buffers of 500 Mb each throws java.lang.OutOfMemoryError. 
Investigate this issue.

Experiment with following solutions:
1. Increase Java Heap space. 
2. Upgrade the VM memory.

**Comment by rickle-msft** [comment]
I believe it is possible to change this test to not require so much memory without any adverse side effects. There's nothing inherently special about 4x500MB. Let me know what your memory requirements are and we can adjust the test to fit that unless you see benefit in scaling up the infrastructure

**Comment by ibrahimrabab** [comment]
Closing this issue since there hasn't been customer engagement for the past couple of years. @g2vinay please feel free to re-open this with additional information if your issue has not been resolved.

Thanks!
