### ISSUE TITLE
[BUG]Improve retry handling if the client is closed

### ISSUE THREAD

**Issue by xinlian12** [Azure/azure-sdk-for-java#31062]
Currently, if we are doing any operations with a closed client, the retry will still keep happening. Request should not be retried if the client has already been closed. 
![image](https://user-images.githubusercontent.com/64233642/191391252-7b621dd0-b7de-47ff-855a-aa8008822eb0.png)

**Comment by kushagraThapar** [comment]
@rinatmini pls take a look at this, thanks!

**Comment by kushagraThapar** [comment]
Assigning to @jeet1995

**Comment by kushagraThapar** [comment]
I believe this has been fixed, but a verification for this will be better. Assigning to @tvaron3
