### ISSUE TITLE
Java V2 runtime - Netty upgrade

### ISSUE THREAD

**Issue by g2vinay** [Azure/azure-sdk-for-java#3107]
Storage Java SDK requires latest version of Netty to ensure compatibility with Java 11.
The SDK uses v2 java runtime. Currently the runtime doesn't have latest netty version as dependency.

Upgrade the V2 runtime with latest Netty.

Required Netty libraries:

       <dependency>
          <groupId>io.netty</groupId>
          <artifactId>netty-all</artifactId>
          <version>4.1.34.Final</version>
        </dependency>

        <dependency>
          <groupId>com.corundumstudio.socketio</groupId>
          <artifactId>netty-socketio</artifactId>
          <version>1.7.13</version>
        </dependency>

**Comment by rhuddleston** [comment]
Looks like 4.1.54.Final is being used now https://github.com/Azure/azure-sdk-for-java/blob/master/sdk/core/azure-core-http-netty/pom.xml

**Comment by g2vinay** [comment]
Closing this as versions have been updated.
