### ISSUE TITLE
[BUG] Spark Cosmos connector does not close its threads

### ISSUE THREAD

**Issue by achistef** [Azure/azure-sdk-for-java#31077]
Hi, 
I have noticed that the cosmos connector does not close the threads that it creates. When the connector is put in a streaming application, those threads are accumulated over time. Eventually, the JVM cannot create any new threads and it crashes with the following exception
`java.io.IOException: java.util.concurrent.ExecutionException: java.lang.OutOfMemoryError: unable to create new native thread` 
I have tested the connector in stream mode and batch mode; the behaviour is the same. 

Here is how you can reproduce the problem for both scenarios (batch & stream).
The following information is the same for both scenarios:
Environment: Databricks 9.1
Library: `azure-cosmos-spark_3-1_2-12` version `4.12.2`

For the batch example:
Databricks job:
```
{
    "settings": {
        "name": "Cosmos Connector Experiment - Batch Mode",
        "email_notifications": {
            "no_alert_for_skipped_runs": false
        },
        "timeout_seconds": 0,
        "max_concurrent_runs": 1,
        "tasks": [
            {
                "task_key": "Cosmos_Connector_Experiment",
                "notebook_task": {
                    "notebook_path": "/point/to/notebook/batchModeNotebook.scala",
                    "source": "WORKSPACE"
                },
                "job_cluster_key": "Shared_job_cluster",
                "libraries": [
                    {
                        "maven": {
                            "coordinates": "com.azure.cosmos.spark:azure-cosmos-spark_3-1_2-12:4.12.2"
                        }
                    }
                ],
                "timeout_seconds": 0,
                "email_notifications": {}
            }
        ],
        "job_clusters": [
            {
                "job_cluster_key": "Shared_job_cluster",
                "new_cluster": {
                    "cluster_name": "",
                    "spark_version": "9.1.x-scala2.12",
                    "azure_attributes": {
                        "first_on_demand": 1,
                        "availability": "ON_DEMAND_AZURE",
                        "spot_bid_max_price": -1
                    },
                    "node_type_id": "Standard_DS3_v2",
                    "enable_elastic_disk": true,
                    "data_security_mode": "LEGACY_SINGLE_USER_STANDARD",
                    "runtime_engine": "STANDARD",
                    "num_workers": 1
                }
            }
        ],
        "format": "MULTI_TASK"
    },
}
```

Notebook code:
```
// Databricks notebook source
import org.apache.spark.sql.functions._
import org.apache.spark.sql.{Dataset, Row}

object DeltaToCosmos {

  def run(): Unit = {
    val cosmosConfig = Map(
      "spark.cosmos.accountEndpoint" -> "https://<fill>.documents.azure.com:443/",
      "spark.cosmos.accountKey" -> "<fill>",
      "spark.cosmos.database" -> "<fill>",
      "spark.cosmos.container" -> "<fill>",
      "spark.cosmos.applicationName" -> "Experiment",
      "spark.cosmos.write.strategy" -> "ItemAppend",
      "spark.cosmos.write.maxRetryCount" -> "10",
      "spark.cosmos.write.bulk.enabled" -> "true")

    spark
      .readStream
      .format("delta")
      .load("<fill>")
      .select("col1", "col2", "col3", "col4", "col5")
      .withColumn("id", concat_ws("|", lit("copy"), col("col1"), col("col2"), col("col3"), col("col4"), col("col5")))
      .writeStream
      .outputMode("append")
      .queryName("experiment")
      .option("checkpointLocation", "<fill>")
      .foreachBatch((batch: Dataset[Row], batchId: Long) =>
        batch
          .write
          .format("cosmos.oltp")
          .options(cosmosConfig)
          .mode(SaveMode.Append)
          .save()
      )
      .start()

  }

}

DeltaToCosmos.run()
```

For the stream example:
Databricks job:
```
{
    "settings": {
        "name": "Cosmos Connector Experiment - Stream Mode",
        "email_notifications": {
            "no_alert_for_skipped_runs": false
        },
        "timeout_seconds": 0,
        "max_concurrent_runs": 1,
        "tasks": [
            {
                "task_key": "Cosmos_Connector_Experiment",
                "notebook_task": {
                    "notebook_path": "/point/to/notebook/streamModeNotebook.scala",
                    "source": "WORKSPACE"
                },
                "job_cluster_key": "Shared_job_cluster",
                "libraries": [
                    {
                        "maven": {
                            "coordinates": "com.azure.cosmos.spark:azure-cosmos-spark_3-1_2-12:4.12.2"
                        }
                    }
                ],
                "timeout_seconds": 0,
                "email_notifications": {}
            }
        ],
        "job_clusters": [
            {
                "job_cluster_key": "Shared_job_cluster",
                "new_cluster": {
                    "cluster_name": "",
                    "spark_version": "9.1.x-scala2.12",
                    "azure_attributes": {
                        "first_on_demand": 1,
                        "availability": "ON_DEMAND_AZURE",
                        "spot_bid_max_price": -1
                    },
                    "node_type_id": "Standard_DS3_v2",
                    "enable_elastic_disk": true,
                    "data_security_mode": "LEGACY_SINGLE_USER_STANDARD",
                    "runtime_engine": "STANDARD",
                    "num_workers": 1
                }
            }
        ],
        "format": "MULTI_TASK"
    }
}
```

Notebook code:
```
// Databricks notebook source
import org.apache.spark.sql.functions._

object DeltaToCosmos {

  def run(): Unit = {    
    val cosmosConfig = Map(
      "spark.cosmos.accountEndpoint" -> "https://<fill>.documents.azure.com:443/",
      "spark.cosmos.accountKey" -> "<fill>",
      "spark.cosmos.database" -> "<fill>",
      "spark.cosmos.container" -> "<fill>",
      "spark.cosmos.applicationName" -> "Experiment",
      "spark.cosmos.write.strategy" -> "ItemAppend",
      "spark.cosmos.write.maxRetryCount" -> "10",
      "spark.cosmos.write.bulk.enabled" -> "true")

    spark
      .readStream
      .format("delta")
      .load("<fill>")
      .select("col1", "col2", "col3", "col4", "col5")
      .withColumn("id", concat_ws("|", col("col1"), col("col2"), col("col3"), col("col4"), col("col5")))
      .writeStream
      .format("cosmos.oltp")
      .queryName("Experiment")
      .option("checkpointLocation", "<fill>")
      .options(cosmosConfig)
      .outputMode("append")
      .start()

  }

}

DeltaToCosmos.run()
```

As you can see, both examples are quite simple. They read data from a delta lake and they push that data into a cosmos container. You will need to fill in any sensitive information (such as endpoints & keys) to run them. 

At first glance, the streams work fine. They work as they should, they read data from the delta lake and store them into the cosmos container. 
Looking at the logs of the job, you will see the aforementioned exception occur periodically, i.e. once per day. 
 The metrics of the jobs show a good picture of what is happening. The following graph shows the total processes of the worker over time:
<img width="908" alt="image-20220831-110551" src="https://user-images.githubusercontent.com/16307498/191509665-e9683b86-39b4-45d6-b3e6-343a6015e09c.png">

You can see that threads are accumulating over time. Eventually, the worker reaches the upper limit for max processes and crashes. A new worker instance is spawned and the cycle continues. The timestamp of the exception matches the timestamp of the worker crash. The end of the graph shows a dangerous outcome of the problem: it is possible that the worker is unable to restart and it stays "stuck" indefinitely. This is why the graph reaches a plateau. At this point, the worker VM needs to be restarted manually.

So far, I have explained that threads accumulate over time but I have not explained why the cosmos connector is responsible for that. I wrote a small piece of code that prints the total number of threads and the name of each thread. I injected that code into the worker VMs. Out of tens of thousands of threads, the majority of them had the prefix `spark-cosmos-db-...`. In case it helps, here's the snippet:
```
import scala.collection.JavaConverters._
val threads = Thread.getAllStackTraces.keySet().asScala.toList
val builder = new StringBuilder
threads.map(t => t.getName).foreach(tuple => builder.append(tuple))
println(s"there are currently ${threads.size} threads ${builder.toString}")
``` 

As an extra sanity check, I removed the connector from the streaming applications. Instead, I used the delta lake connector. As expected, the total threads remain stable over time.

<img width="904" alt="image-20220831-112030" src="https://user-images.githubusercontent.com/16307498/191512843-b763faa1-3e26-45fd-b034-2f1524cabdba.png">

This bug may not be noticeable for short-living applications but it is a big problem for streaming applications that run 24/7.

**Comment by FabianMeiswinkel** [comment]
Thanks - great bug description. I will take a look and get back with investigation result.

**Comment by achistef** [comment]
@FabianMeiswinkel I am looking forward to your results.
Let me know if you need more information, we have both demos running 24/7 in our Databricks environment.

**Comment by FabianMeiswinkel** [comment]
Thanks - what would indeed help would be the output of the following to Spark UI views (if it is easier you could also share them via mail fabianm[AT]microsoft.com)

Thread dump (Spark UI/Executors/Thread Dump - for one of the impacted workers)
Heap histogram (Spark UI/Executors/Heap Histogram - for one of the impacted workers)

The most likely area where threads could "leak" is that there are many Cosmos Client instances (which use connection and buffer pooling for network operations). We use a cache for Cosmos Client instances - where the cache key is the account name of the cosmos account plus a few config entries. The only config entry that I know could accidentally result in many clients being cached would be if the "spark.cosmos.applicationName" config entry has unique values for every streaming batch iteration. But form the code you shared above that doesn't seem to be the case. So, looking at the thread dump and histogram would help to further narrow down where the problem is. I am in parallel trying to repro right now.

**Comment by FabianMeiswinkel** [comment]
@achistef - I think I was able to reproduce the issue you described. Can you confirm that you also see a growing number of threads with the thread name "cosmos-daemon-BulkExecutor-*" in the Thread Dump Spark UI view? (Spark UI/Executors/xxx (some worker)/Thread Dump)?

I am going to start working on a fix for that.

![image](https://user-images.githubusercontent.com/19165014/191558986-77a18c45-35ef-429b-8d58-63b10ad1cf27.png)

**Comment by achistef** [comment]
@FabianMeiswinkel I can confirm that this is what I also see. There are a lot of threads named `cosmos-daemon-BulkExecutor`. I was wrong about the name of the threads in my description, pardon me.

I have just sent you the email you requested with two text files, one for the thread dump and one for the histogram.

**Comment by FabianMeiswinkel** [comment]
@achistef - thank you! I am working on a fix. Worst case hotfix will be available at the end of this month.

**Comment by FabianMeiswinkel** [comment]
Hotfix (in version 4.13.1 - https://repo1.maven.org/maven2/com/azure/cosmos/spark/azure-cosmos-spark_3-1_2-12/4.13.1/azure-cosmos-spark_3-1_2-12-4.13.1.jar) has been released to Maven

**Comment by achistef** [comment]
@FabianMeiswinkel Thank you so much, you've done an amazing job that it is very helpful to us

**Comment by FabianMeiswinkel** [comment]
@achistef - Thanks! You did most of it by putting together the excellent problem description. We will also adjust our long-running release-validation tests. We didn't clearly identify the leak there because the number of micro-batches executed was too low - we are changing the test - so chances are in the future we will identify this kind of leak earlier. So, thanks for the feedback again and please let me know if you hit any other issues in the future.
