### ISSUE TITLE
EventHubs EventData.getProperties() documentation

### ISSUE THREAD

**Issue by richorama** [Azure/azure-sdk-for-java#31095]
**Is your feature request related to a problem? Please describe.**

In the EventHubs client, it is unclear which data types are supported for the properties of EventData class.

https://github.com/Azure/azure-sdk-for-java/blob/main/sdk/eventhubs/azure-messaging-eventhubs/src/main/java/com/azure/messaging/eventhubs/EventData.java#L173-L196

**Describe the solution you'd like**

Could we have an annotation/documentation that describes what data types are supported, as is the case for the .NET client.

https://github.com/Azure/azure-sdk-for-net/blob/main/sdk/eventhub/Azure.Messaging.EventHubs/src/EventData.cs#L214-L260

**Describe alternatives you've considered**

It would be even nicer to have this included in the type system, rather than using a `Map<String, Object>`.

**Additional context**

n/a

**Information Checklist**
Kindly make sure that you have added all the following information above and checkoff the required fields otherwise we will treat the issuer as an incomplete report
- [x] Description Added
- [x] Expected solution specified

**Comment by joshfree** [comment]
@conniey @Azure/azsdk-sb-java could you please follow up with @richorama

**Comment by conniey** [comment]
Ahh, yeah. Ity should be easy enough to add documentation. thanks!

**Comment by conniey** [comment]
The set documented is one supported across other languages. For example, .NET library does not support serializing a map within a map even though proton-j does.

**Comment by bvahdat** [comment]
> The set documented is one supported across other languages. For example, .NET library does not support serializing a map within a map even though proton-j does.

Hi @conniey

The _additional_ types I have asked for [here](https://github.com/Azure/azure-sdk-for-java/pull/31175#issuecomment-1263337119) to be included into the documentation, are indeed supported by this repository with [the corresponding tests I have added](https://github.com/bvahdat/azure-sdk-for-java/commit/78578da1ed9629ed3427480f9cc5e4845c2a252f) to prove it.

So still not clear to me why these types are not listed.

cc: @richorama

**Comment by conniey** [comment]
Hey,

I'm working with our messaging team to add some more clarification around this in our docs.

**Comment by conniey** [comment]
To follow up, as of this current release (azure-messaging-eventhubs 5.15.0), the supported types for `getProperties()` are:

* String
* Symbol
* Integer
* Long
* Short
* Character
* Float
* Double
* Date

Due to the logic in our [EventHubMessageSerializer](https://github.com/Azure/azure-sdk-for-java/blob/main/sdk/eventhubs/azure-messaging-eventhubs/src/main/java/com/azure/messaging/eventhubs/EventHubMessageSerializer.java#L351) when we are figuring out if an EventData fits within a batch.  Any other types will cause an IllegalArgumentException to be thrown.

**Comment by bvahdat** [comment]
> To follow up, as of this current release (azure-messaging-eventhubs 5.15.0), the supported types for `getProperties()` are:
> 
> * String
> * org.apache.qpid.proton.amqp.Symbol
> * Integer
> * Long
> * Short
> * Character
> * Float
> * Double
> * Date
> 
> Due to the logic in our [EventHubMessageSerializer](https://github.com/Azure/azure-sdk-for-java/blob/main/sdk/eventhubs/azure-messaging-eventhubs/src/main/java/com/azure/messaging/eventhubs/EventHubMessageSerializer.java#L351) when we are figuring out if an EventData fits within a batch. Any other types will cause an IllegalArgumentException to be thrown.
> 
> For context, this logic was brought over from our legacy Event Hubs client library as-is ([AmqpUtil.java](https://github.com/Azure/azure-sdk-for-java/blob/main/sdk/eventhubs/microsoft-azure-eventhubs/src/main/java/com/microsoft/azure/eventhubs/impl/AmqpUtil.java#L97)). So other types did not work in that library either.
> 
> Seeing this gap, I'm working on adding support for more types based on the ones in the AMQP protocol that can be mapped to a class in the Java SDK.

Thanks @conniey for the update.

It means you will also follow up for a fix regarding https://github.com/Azure/azure-sdk-for-java/pull/31175, right?

**Comment by conniey** [comment]
> It means you will also follow up for a fix regarding https://github.com/Azure/azure-sdk-for-java/pull/31175, right?

Yes, this is correct. I'll update the documentation and then create another GitHub issue to address this gap.
