### ISSUE TITLE
[BUG] EventHubsBinderRecordModeIT#testSendAndReceiveMessage failed

### ISSUE THREAD

**Issue by chenrujun** [Azure/azure-sdk-for-java#31109]
## Context

https://dev.azure.com/azure-sdk/internal/_build/results?buildId=1868435&view=logs&j=5fe92c1d-3c25-55b7-1c07-fa5c3c25e91d&t=55c333a2-afdf-54d6-1385-c643b91b3f0b&l=953

```log
[ERROR]   EventHubsBinderRecordModeIT.***SendAndReceiveMessage:69 
Expecting value to be true but was false
```

## Goal

Fix the pipeline failure. Make it stable.

## Solution 

1. Investigate how spring-cloud-kafka / rabbitmq are testing the same function. 
2. If spring-cloud-kafka / rabbitmq do not have similar test, check whether **awaitility** can be used in this scenario. Refs: https://www.baeldung.com/awaitility-testing

**Comment by fangjian0423** [comment]
Both Kafka Binder and RabbitMQ Binder have the similar test, refer [KafkaBinderTest](https://github.com/spring-cloud/spring-cloud-stream-binder-kafka/blob/main/spring-cloud-stream-binder-kafka/src/test/java/org/springframework/cloud/stream/binder/kafka/KafkaBinderTests.java#L649) and [RabbitBinderTests](https://github.com/spring-cloud/spring-cloud-stream-binder-rabbit/blob/1e4f5829fe66e7ccba5ceb04e84e117063b66553/spring-cloud-stream-binder-rabbit/src/test/java/org/springframework/cloud/stream/binder/rabbit/RabbitBinderTests.java#L235).

From the test case logs, the message have been send:

`2022-09-22 15:29:29.568  INFO 42031 --- [           main] .a.s.c.i.t.e.b.EventHubsBinderSyncModeIT : Manually sending message 9fb7a101-bdf7-4e70-b7c1-255b599e95ec`

but we don't receive it, maybe there is something wrong in message receive side.

**Comment by fangjian0423** [comment]
Adding `ServiceActivator` to receive the message that send failed can solve this problem:

```java
@ServiceActivator(inputChannel = "errorChannel")
public void receiveProduceErrorMsg(Message sendFailedMsg) {
    LOGGER.info("receive send failed msg: '{}'", sendFailedMsg);
    LATCH.countDown();
}
```

But it will cause another problem: If all test cases send messages failed , we don't cover message receive scenario.

So I think we can add `ServiceActivator` in EventHubsBinderSyncModeIT, EventHubsBinderRecordModeIT, EventHubsBinderManualModeIT and EventHubsBinderBatchModeIT, leave EventHubsBinderConsumeErrorIT to cover message receive scenario. 
In additional, adding EventHubsBinderProduceErrorIT to cover message send error scenario.

**Comment by fangjian0423** [comment]
Close it because PR merged.
