### ISSUE TITLE
Storage - Files Shares Readme issus

### ISSUE THREAD

**Issue by hongli750210** [Azure/azure-sdk-for-java#31138]
1.
Section [link](https://github.com/Azure/azure-sdk-for-java/tree/main/sdk/storage/azure-storage-file-share#create-a-directory)
![image](https://user-images.githubusercontent.com/74638143/192177301-c0726733-bd8b-4ecf-90d9-0914267c6b58.png)

Suggestion:
This link jumps to the wrong place. Update the link to `(#share)`.

@joshfree, @kasobol-msft, @kyle-patterson and @xinlian12 for notification

**Comment by ibrahimrabab** [comment]
Hi @hongli750210 ,

Thank you for bringing attention to this issue, we will have a fix out for this shortly.
