### ISSUE TITLE
Readme Content Verification - need to format readmes to match template doc 

### ISSUE THREAD

**Issue by scbedd** [Azure/azure-sdk-for-java#3113]
The following data-plane items need to be addressed. Validation has failed on the following readme list items.

tl;dr: Readmes should have at least have sections that correspond to the main sections as defined in the [template readme.](https://github.com/scbedd/azure-sdk/blob/master/docs/README-TEMPLATE.md) 

This is what the **tool checks**, but the ideal scenario is the readme is reworked to be somewhat like the [readme example.](https://github.com/scbedd/azure-sdk/blob/master/docs/README-EXAMPLE.md)

For a rundown on what you need to do to resolve these breaking issues ASAP, check out aka.ms/azure-sdk-analyze-failed

## Content Validation Items
12 readmes have at least one missing required section.
- [ ] \README.md is missing headers with patterns:
 * Azure .+ client library Java
 * ^Getting started$
 * ^Key concepts$
 * ^Examples$
 * ^Troubleshooting$
 * ^Next steps$
 * ^Contributing$

(the items below have identical failures as the root readme as well, explicit list omitted for brevity)

- [ ] \applicationinsights\data-plane\README.md
- [ ] \authorization\msi-auth-token-provider-jar\readme.md
- [ ] \batch\data-plane\README.md
- [ ] \eventgrid\data-plane\README.md
- [ ] \eventhubs\data-plane\readme.md
- [ ] \eventhubs\data-plane\azure-eventhubs-eph\Readme.md
- [ ] \keyvault\data-plane\README.md
- [ ] \loganalytics\data-plane\README.md
- [ ] \storage\data-plane\README.md
- [ ] \storage\data-plane\swagger\README.md
- [ ] \core\README.md
- [ ] \servicebus\data-plane\README.md

## Presence Verification Items
Warden detected there to be a missing readme in the below relative locations. These are much squishier than content verification, as there are real reasons for readmes not being present. Getting eyes on what `doc-warden` is ignoring is still good for awareness though. If a readme "missing" below is correct, feel free to remove the exception from the checklist.

- [ ] cognitiveservices/data-plane/language/bingspellcheck
- [ ] cognitiveservices/data-plane/language/luis/authoring
- [ ] cognitiveservices/data-plane/language/luis/runtime
- [ ] cognitiveservices/data-plane/language/textanalytics
- [ ] cognitiveservices/data-plane/search/bingautosuggest
- [ ] cognitiveservices/data-plane/search/bingcustomimagesearch
- [ ] cognitiveservices/data-plane/search/bingcustomsearch
- [ ] cognitiveservices/data-plane/search/bingentitysearch
- [ ] cognitiveservices/data-plane/search/bingimagesearch
- [ ] cognitiveservices/data-plane/search/bingnewssearch
- [ ] cognitiveservices/data-plane/search/bingvideosearch
- [ ] cognitiveservices/data-plane/search/bingvisualsearch
- [ ] cognitiveservices/data-plane/search/bingwebsearch
- [ ] cognitiveservices/data-plane/vision/computervision
- [ ] cognitiveservices/data-plane/vision/contentmoderator
- [ ] cognitiveservices/data-plane/vision/customvision/prediction
- [ ] cognitiveservices/data-plane/vision/customvision/training
- [ ] cognitiveservices/data-plane/vision/faceapi
- [ ] keyvault/data-plane/azure-keyvault
- [ ] keyvault/data-plane/azure-keyvault-core
- [ ] keyvault/data-plane/azure-keyvault-cryptography
- [ ] keyvault/data-plane/azure-keyvault-extensions
- [ ] keyvault/data-plane/azure-keyvault-webkey
- [ ] mediaservices/data-plane
- [ ] core/azure-core
- [ ] common/azure-core-auth
- [ ] common/azure-core-mgmt

**Comment by alzimmermsft** [comment]
Closing this as many of the README references are outdated and point to libraries that aren't being actively maintained. There are only a limited number of maintained libraries that have suppressions but those are for specialty, non-standard SDK scenarios such as framework implementations.
