### ISSUE TITLE
[Cosmos Diagnostics Improvement] Separate RntbdContextNeogiation from ChannelAcquisitionStarted stage

### ISSUE THREAD

**Issue by xinlian12** [Azure/azure-sdk-for-java#31130]
Currently in cosmos diagnostics, the channelAcquisitionStarted stage include the time spent in RntbdContextNeogiation as well, separate them out could give us a better picture of the time spent in each stage

**Comment by kushagraThapar** [comment]
@rinatmini pls take a look at this, thanks!

**Comment by kushagraThapar** [comment]
Assigning to @jeet1995
