### ISSUE TITLE
Migrate/Re-Write Service Bus Performance Tests to use AMQP Perf Framework

### ISSUE THREAD

**Issue by g2vinay** [Azure/azure-sdk-for-java#31195]
We need to add/re-write perf tests for following scenarios of Service Bus in its [track 2 perf module.](https://github.com/Azure/azure-sdk-for-java/tree/main/sdk/servicebus/azure-messaging-servicebus-track2-perf)

- [ ] Receive Messages
    - [ ] Receiver Client - Receive And Lock  
           - [Sample Reference to Use](https://github.com/Azure/azure-sdk-for-java/blob/main/common/perf-test-core/src/main/java/com/azure/perf/test/core/MockBatchReceiverTest.java)
    - [ ] Receiver Client - Receive and Delete
          - [Sample Reference to Use](https://github.com/Azure/azure-sdk-for-java/blob/main/common/perf-test-core/src/main/java/com/azure/perf/test/core/MockBatchReceiverTest.java)
    - [ ] Processor Client
          - [Sample Reference to Use](https://github.com/Azure/azure-sdk-for-java/blob/main/common/perf-test-core/src/main/java/com/azure/perf/test/core/MockEventProcessorTest.java)

**Comment by ZejiaJiang** [comment]
https://github.com/Azure/azure-sdk-for-java/pull/31576
