### ISSUE TITLE
[BUG]Switch to point reads within readMany when the tuple has only 1 item

### ISSUE THREAD

**Issue by xinlian12** [Azure/azure-sdk-for-java#31200]
Currently, internally ReadMany uses query - but when there is only item for a certain partition, from RU perspective, point read consumes less RU compared to query. So the idea here is to switch to use point read when there is only one item for a partitions.

However, when the doc size is much larger - query may perform better than point read, so we should make this behavior as opt-in.

**Comment by kushagraThapar** [comment]
This is done.
