### ISSUE TITLE
[FEATURE REQ] mgmt Lite, know which service is popular, but we not generated for long

### ISSUE THREAD

**Issue by weidongxu-microsoft** [Azure/azure-sdk-for-java#31208]
We had certain way to get "ring" and "traffic" of service e.g. https://funweidxu.azurewebsites.net/api/java-packages

We had BI on RP/service https://msit.powerbi.com/groups/de995b1a-16c1-4cc7-a49b-bc9f90bc6acd/reports/8a8582d5-8fdf-4014-8cf9-4d183c5db2c8/ReportSection

We currently don't know how long Lite package is not released.

We may like to refresh the popular Lite package regularly (once a few months?).

**Comment by XiaofeiCao** [comment]
A few thoughts of the process:
1. Export a report of top request count RPs in PowerBI, in csv form
2. In our release automation, for each RP:
   1. Find service name by RP (Can't find an easy way, needs more investigation)
   2. Get CHANGELOG.md, pom.xml by service name in github.io ({github-prefix}/sdk/{service-name}/azure-resourcemanager-{service-name})
   3. Get release date from CHANGELOG.md, if too long, regenerate and release by the tag from pom.xml
3. Generate release report
4. (Optional) Plug the above process to github actions, set a periodic trigger(once a few months, needs investigation).

PR and release approval should probably be automatic in this case, and we should probably skip stable version SDKs for this automatic regen.

**Comment by weidongxu-microsoft** [comment]
Maybe we can do (1) and see what we are missing.

https://funweidxu.azurewebsites.net/api/java-packages has data from swagger live validation, though traffic is all (not only Java).
