### ISSUE TITLE
[How to consume data from EventHub since the last hasn't consumed one, not the latest new incoming one once the consumer disconnect and reconnect EventHub again]

### ISSUE THREAD

**Issue by wstest123** [Azure/azure-sdk-for-java#31204]
**Query/Question**
We found that once our client disconnect the EventHub server for some minutes and reconnect again. Client can only receive the latest  
new incoming messages. So we missed the messages incoming to EventHub server during the disconnect time.

Could you please help advice how to setup client to consume the messages since the last hasn't consumed one in Event Hub Server?

***Why is this not a Bug or a feature Request?***
Hope to know if the SDK client provide this feature but we don't know how to use it. Hope to confirm it.

**Setup (please complete the following information if applicable):**
**Client version:**
    <dependency>
            <groupId>com.azure</groupId>
            <artifactId>azure-messaging-eventhubs-checkpointstore-blob</artifactId>
           <version>1.12.1</version>
      </dependency>

**Client Code:**

public EventProcessorClient eventProcessorClient(EventHubProperties properties
        , Consumer<EventBatchContext> processEventBatch, Consumer<ErrorContext> processError,Consumer<CloseContext> closePartition) {
    BlobContainerAsyncClient ftcpBlobContainerAsyncClient = new BlobServiceClientBuilder()
            .connectionString(properties.getCheckpointStoreBlobConnectionString())
            .buildAsyncClient()
            .getBlobContainerAsyncClient(properties.getCheckpointStoreBlobContainerName());
    return new EventProcessorClientBuilder()
            .connectionString(properties.getConnectionString(), properties.getEventHubName())
            .processPartitionClose(closePartition)
            .processEventBatch(processEventBatch, 100, Duration.ofSeconds(properties.getMaxWaitTime()))
            .processError(processError)
            .checkpointStore(new BlobCheckpointStore(ftcpBlobContainerAsyncClient))
            .consumerGroup(properties.getConsumerGroup())
            .buildEventProcessorClient();
}

eventProcessorClient.start();

public void processEventBatch(EventBatchContext batchContext) {
    …
}

public void processError(ErrorContext errorContext) {
    log 
}

public void processPartitionClose(CloseContext closeContext) {
    log 
}
 
 **Information Checklist**

**Comment by joshfree** [comment]
@conniey @Azure/azsdk-sb-java could you please follow up with @wstest123

**Comment by conniey** [comment]
1. When are you checkpointing? Could you show your processEventBatch callback?
2. EventProcessorClient starts from the latest point, (end of the stream) if there are no checkpoints that it can find in the CheckpointStore.

**Comment by wstest123** [comment]
@conniey  Thanks so much for your clarify. We will double confirm the checkpoint steps.

**Comment by PalashBangar-TomTom** [comment]
`EventProcessorClient starts from the latest point, (end of the stream) if there are no checkpoints that it can find in the CheckpointStore.`

How to do this ? 

I have followed Microsoft documentation  [https://learn.microsoft.com/en-us/azure/event-hubs/event-hubs-java-get-started-send#receive-events](MS blog)
but facing similar issue raised here - https://github.com/Azure/azure-sdk-for-java/issues/31839

**Comment by conniey** [comment]
> `EventProcessorClient starts from the latest point, (end of the stream) if there are no checkpoints that it can find in the CheckpointStore.`
> 
> How to do this ?

You can pass a map of initial partitions before constructing the client. [EventProcessorClientBuilder.initialPartitionEventPosition(Map)](https://learn.microsoft.com/en-us/java/api/com.azure.messaging.eventhubs.eventprocessorclientbuilder?view=azure-java-stable#com-azure-messaging-eventhubs-eventprocessorclientbuilder-initialpartitioneventposition(java-util-map(java-lang-string-com-azure-messaging-eventhubs-models-eventposition)))
