### ISSUE TITLE
[BUG] RestOperations is not well configured when jwkResolver is null

### ISSUE THREAD

**Issue by damir78** [Azure/azure-sdk-for-java#31218]
Please initialize/configure OAuth2AuthorizedClientManager and its OAuth2AuthorizedClientProvider if jwkResolver is null.

Otherwise the configuration is incomplete and unuseful.

```java
-com.azure.spring.cloud.autoconfigure.aad.implementation.oauth2.OAuth2ClientAuthenticationJwkResolver
implementation -> com.azure.spring.cloud.autoconfigure.aad.implementation.oauth2.AadOAuth2ClientAuthenticationJwkResolver
```

Compare with: https://github.com/spring-projects/spring-security/issues/8882:

```java

...

@Bean  
public OAuth2AccessTokenResponseClient<OAuth2RefreshTokenGrantRequest> refreshTokenTokenResponseClient() {  
   DefaultRefreshTokenTokenResponseClient tokenResponseClient = new DefaultRefreshTokenTokenResponseClient();  
   tokenResponseClient.setRestOperations(oauth2ClientRestOperations());  
   return tokenResponseClient;  
}  
  
@Bean  
public OAuth2AccessTokenResponseClient<OAuth2ClientCredentialsGrantRequest> clientCredentialsTokenResponseClient() {  
   DefaultClientCredentialsTokenResponseClient tokenResponseClient = new DefaultClientCredentialsTokenResponseClient();  
   tokenResponseClient.setRestOperations(oauth2ClientRestOperations());  
   return tokenResponseClient;  
}  
  
@Bean  
public OAuth2AccessTokenResponseClient<OAuth2PasswordGrantRequest> passwordTokenResponseClient() {  
   DefaultPasswordTokenResponseClient tokenResponseClient = new DefaultPasswordTokenResponseClient();  
   tokenResponseClient.setRestOperations(oauth2ClientRestOperations());  
   return tokenResponseClient;  
}  
  
@Bean  
public OAuth2AuthorizedClientManager authorizedClientManager(ClientRegistrationRepository clientRegistrationRepository,  
  OAuth2AuthorizedClientRepository authorizedClientRepository) {  
   OAuth2AuthorizedClientProvider authorizedClientProvider =  
         OAuth2AuthorizedClientProviderBuilder.builder()  
               .authorizationCode()  
               .refreshToken(refreshToken ->  
                     refreshToken.accessTokenResponseClient(refreshTokenTokenResponseClient()))  
               .clientCredentials(clientCredentials ->  
                     clientCredentials.accessTokenResponseClient(clientCredentialsTokenResponseClient()))  
               .password(password ->  
                     password.accessTokenResponseClient(passwordTokenResponseClient()))  
               .build();  
  DefaultOAuth2AuthorizedClientManager authorizedClientManager = new DefaultOAuth2AuthorizedClientManager(  
         clientRegistrationRepository, authorizedClientRepository);  
  authorizedClientManager.setAuthorizedClientProvider(authorizedClientProvider);  
  
 return authorizedClientManager;  
}

...
```

For example, for both cases ( jwkResolver == null and jwkResolver!=null) should be provided the correct default configuration.

<img width="1458" alt="image" src="https://user-images.githubusercontent.com/12588674/193125159-e20efc6c-79b4-4a7a-ab70-8530ef5bdc94.png">
<img width="1221" alt="image" src="https://user-images.githubusercontent.com/12588674/193127746-788ed9d4-60ae-4418-a67d-089154d79d82.png">
<img width="1266" alt="image" src="https://user-images.githubusercontent.com/12588674/193127847-356a9435-83c1-4937-9b2b-51cde6f97033.png">

**Comment by saragluna** [comment]
Thanks @damir78 for reaching out, we will look into it. BTW, seems like you have done the research, so PR is welcome ;). And please expect delayed response for it will be the National Holiday next week.

**Comment by chenrujun** [comment]
Hi, @damir78 .

> Please initialize/configure OAuth2AuthorizedClientManager and its OAuth2AuthorizedClientProvider if jwkResolver is null.
Otherwise the configuration is incomplete and unuseful.

No. In current implementation, `OAuth2AuthorizedClientManager` and its `OAuth2AuthorizedClientProvider` will be well-configured even if `resolver == null`.

![image](https://user-images.githubusercontent.com/13167207/194697668-497913d6-291c-4577-82da-384ff5482137.png)

**Comment by chenrujun** [comment]
Closing in favor of https://github.com/Azure/azure-sdk-for-java/pull/31213

**Comment by chenrujun** [comment]
Reopen this issue because PR is not closed yet.
