### ISSUE TITLE
[BUG] OAuth2 config-> JwtDecoder / NimbusJwtDecoder still uses RestTemplate() instead RestTemplateBuilder

### ISSUE THREAD

**Issue by damir78** [Azure/azure-sdk-for-java#31233]
Important: related issues: Connecting to Azure-AD via proxy #26493 #30456

Short story:  

Add `JwtDecoderFactory` into `AadOAuth2ClientConfiguration` or `AadWebSecurityConfigurerAdapter` with the jwtDecoder that uses RestTemplateBilder.

```java
  /**
   * Creates jwt decoder factory.
   *
   * @return The factor.
   */
  @Bean
  @ConditionalOnMissingBean
  public JwtDecoderFactory<ClientRegistration> createJwtDecoderFactory(JwtDecoder jwtDecoder) {
    return (ClientRegistration context) -> jwtDecoder;
  }
```

Long story:

The created `AuthentifactionProvider (oauth2Login() )` by `AadWebSecurityConfigurerAdapter#configure(HttpSecurity http)` uses the default `JwtDecoder /NimbusJwtDecoder` created by `OAuth2LoginConfigurer<HttpSecurity> oauth2Login()`.
This configurer tries to find  a bean of `JwtDecoderFactory` .

<img width="1444" alt="image" src="https://user-images.githubusercontent.com/12588674/193250384-057d5b4e-5173-4041-99f0-e7ed37a76355.png">

 If no `jwtDecoderFactory` found, then will `OidcAuthorizationCodeAuthenticationProvider` creates  a new `JwtDecoderFactory` that uses default `RestTemplate()`:

<img width="1170" alt="image" src="https://user-images.githubusercontent.com/12588674/193250746-c7e13b65-858b-40cb-8d3a-887f834019a6.png">

<img width="1274" alt="image" src="https://user-images.githubusercontent.com/12588674/193251104-404703ab-0c9c-418a-bda9-4250e6883aa3.png">

After calling `NimbusJwtDecoder buildDecoder() with default RestTemplate()`:

<img width="1467" alt="image" src="https://user-images.githubusercontent.com/12588674/193251609-1baabf02-84d2-40d3-9102-57480fafcb9b.png">

**Comment by joshfree** [comment]
@chenrujun could you please follow up?

**Comment by chenrujun** [comment]
Hi, @damir78 , thanks for reaching out. I'll investigate this issue ASAP.

**Comment by chenrujun** [comment]
Closing in favor of #31347

**Comment by chenrujun** [comment]
Reopen this issue because current plan to fix this issue by a standalone PR.
