### ISSUE TITLE
[BUG]ReplicaStatusList diagnostics improvements

### ISSUE THREAD

**Issue by xinlian12** [Azure/azure-sdk-for-java#31259]
Currently, the replicaStatusList only tracks port + status, it may become confusing during the process of primary replica de-promotion and secondary replica promotion process. 
Maybe also add replica info.

**Comment by kushagraThapar** [comment]
@rinatmini pls take a look at this, thanks!

**Comment by rinatmini** [comment]
discussed with @xinlian12 - not actual anymore
