### ISSUE TITLE
[FEATURE REQ] Support Workload Identity in azure-resourcemanager-containerservice

### ISSUE THREAD

**Issue by rtitle** [Azure/azure-sdk-for-java#31271]
**Is your feature request related to a problem? Please describe.**
I'm using `azure-resourcemanager-containerservice` to create/manage AKS clusters. I would like to use the [Workload Identity](https://learn.microsoft.com/en-us/azure/aks/workload-identity-overview) feature in preview, but it appears the SDK is currently at API version `2022-07-01` which doesn't have support for cluster creation arguments `--enable-oidc-issuer` and `--enable-workload-identity`.

**Describe the solution you'd like**
Bump Microsoft.ContainerService API version to `2022-08-03-preview` in the SDK.

**Describe alternatives you've considered**
I am considering making direct REST calls or using ARM templates to access the functionality from Java, but this is not ideal for my application. (If there are other suggested workarounds please let me know!)

**Information Checklist**
Kindly make sure that you have added all the following information above and checkoff the required fields otherwise we will treat the issuer as an incomplete report
- [x] Description Added
- [x] Expected solution specified

**Comment by joshfree** [comment]
@weidongxu-microsoft could you please help route this?

**Comment by weidongxu-microsoft** [comment]
@rtitle 
Currently AKS SDK release is always on stable api-version.

So far, we hadn't got release for release on "2022-08-03-preview" from backend.

@XiaofeiCao 
Maybe we can first check with AKS backend about when the feature will get to stable api-version.

**Comment by rtitle** [comment]
Thanks for the reply -- please do let me know when AKS workload identity will make it into the stable api.

**Comment by rtitle** [comment]
Just to update: we're currently using https://azure.github.io/aad-pod-identity/docs/ so are not blocked -- but still interested when AKS Workload Identity becomes a stable feature with Java SDK support.

**Comment by XiaofeiCao** [comment]
@rtitle 

They haven't made it to stable yet(no idea when they'll do). 

Though we could release a beta version now. Does it sound good to you?

**Comment by containerpope** [comment]
@XiaofeiCao is there already a beta release with workload identity available?

**Comment by rtitle** [comment]
That would be great if you could release a Java SDK version with AKS Workload Identity available. Let me know and I can test it from my end.

**Comment by XiaofeiCao** [comment]
@containerpope I'm afraid not. We'll release a beta SDK with api-version `2022-11-02-preview`.

@rtitle Got it. Management plane release cycle starts next week. You can expect a version with workload identity then.

**Comment by XiaofeiCao** [comment]
[2.25.0-beta.1](https://central.sonatype.com/artifact/com.azure.resourcemanager/azure-resourcemanager-containerservice/2.25.0-beta.1) with Workload Identity support has released. @rtitle @containerpope

**Comment by rtitle** [comment]
Hi @XiaofeiCao ,

I upgraded to `2.25.0-beta.1` but am having trouble finding the new functionality -- wondering if you could point me in the right direction?

My gradle dependency: 
```
implementation group: 'com.azure.resourcemanager', name: 'azure-resourcemanager-containerservice', version: '2.25.0-beta.1'
```

Similar to the [documentation](https://learn.microsoft.com/en-us/azure/aks/workload-identity-deploy-cluster#create-aks-cluster) I'm trying to create a cluster using the Java SDK with `--enable-oidc-issuer` and `--enable-workload-identity`, and then retrieve the `oidcIssuerProfile.issuerUrl`.

I'm definitely pulling in the new version. Am I missing something (entirely possible)? Thank you.

**Comment by XiaofeiCao** [comment]
Hi @rtitle, the version is OK.

To enable workload identity, you need an extra step:
```java
AzureResourceManger azure = initAzure();

// This is normal step of creating cluster instances:
KubernetesCluster cluster = azureResourceManager.kubernetesClusters()
    .define(clusterName)
    .configure() // necessary configurations
    .create();

// this is extra step to enable workload identity

// this line has to appear before any changes made to innerModel(), due to implementation mechanism
KubernetesCluster.Update update = cluster.update();

// enable 
ManagedClusterSecurityProfile securityProfile = cluster.innerModel().securityProfile();
if (securityProfile == null) {
    securityProfile = new ManagedClusterSecurityProfile();
    cluster.innerModel().withSecurityProfile(securityProfile);
}
securityProfile.withWorkloadIdentity(new ManagedClusterSecurityProfileWorkloadIdentity().withEnabled(true));
cluster.innerModel().withOidcIssuerProfile(new ManagedClusterOidcIssuerProfile().withEnabled(true));

// apply the update
update.apply();
cluster.refresh();
```

Similarly, to disable workload identity:
```java
update = cluster.update();
cluster.innerModel().withSecurityProfile(null);
cluster.innerModel().withOidcIssuerProfile(null);

update.apply();

cluster.refresh();
```

Before the feature goes in to stable version, it has to be done in the above way.
