### ISSUE TITLE
Upgrade Out of Date Linting Tooling

### ISSUE THREAD

**Issue by alzimmermsft** [Azure/azure-sdk-for-java#31275]
Upgrade out of date versions of Checkstyle and Spotbugs to their latest versions.

**Checkstyle**

As of Checkstyle 10.0 it requires Java 11 to run, there is a backport for Java 8 that is actively maintained (https://github.com/rnveach/checkstyle-backport-jre8). Updating Checkstyle configuration to use the Checkstyle project when Java 11+ is used and the backport when Java 8-10 is used.

**Spotbugs**

Upgrading Spotbugs is simply just upgrading and resolving any new warnings produced.

**Comment by JonathanGiles** [comment]
Let's add these two tools to the appropriate profile, and move the existing checkstyle / spotbugs into the java 8 profile.
