### ISSUE TITLE
[BUG] com.azure:azure-storage-file-datalake.12.12.1 library not usable with Spring boot 2.7.3

### ISSUE THREAD

**Issue by vmaroli** [Azure/azure-sdk-for-java#31306]
**Describe the bug**
I am developing a application with  Spring boot 2.7.3 and azure-storage-file-datalake.12.12.1. Compiling the application is failing with error. Look like transitive dependencies are not getting resolved.

> cannot access com.azure.core.client.traits.TokenCredentialTrait class file for com.azure.core.client.traits.TokenCredentialTrait not found

There is also a 

> WARNING The POM for com.azure:azure-storage-file-datalake:jar:12.12.1 is invalid, transitive dependencies (if any) will not be available

***Exception or Stack Trace***
[ERROR] COMPILATION ERROR : 
[INFO] -------------------------------------------------------------
[ERROR] cannot access com.azure.core.client.traits.TokenCredentialTrait
  class file for com.azure.core.client.traits.TokenCredentialTrait not found
[ERROR] cannot access com.azure.core.client.traits.AzureNamedKeyCredentialTrait
  class file for com.azure.core.client.traits.AzureNamedKeyCredentialTrait not found
[INFO] 2 errors 

**To Reproduce**
Steps to reproduce the behavior: Simple application with Springboot 2.7.3 and com.azure:azure-storage-file-datalake.12.12.1 as dependency

***Code Snippet***
```
@Bean
	public DataLakeFileSystemClient getDataLakeFileSystemClient (@Qualifier("adlsg2") Properties properties) {
		return new DataLakeFileSystemClientBuilder()
				.endpoint(properties.getProperty("endpoint"))
				.sasToken(properties.getProperty("sasToken"))
				.fileSystemName(properties.getProperty("fileSystemName"))
				.buildClient();
	}
```

**Expected behavior**
Able compile the run the application

**Screenshots**

**Setup (please complete the following information):**
 - OS: Windows 10
 - IDE: Eclipse
 - Library/Libraries: [[e.g. com.azure:azure-core:1.16.0 (groupId:artifactId:version)]](com.azure:azure-storage-file-datalake.12.12.1)
 - Java version: 11
 - App Server/Environment: Tomcat
 - Frameworks: Spring Boot 2.7.3

If you suspect a dependency version mismatch (e.g. you see `NoClassDefFoundError`, `NoSuchMethodError` or similar), please check out [Troubleshoot dependency version conflict article](https://aka.ms/azsdk/java/dependency/troubleshoot) first. If it doesn't provide solution for the problem, please provide:
- verbose dependency tree (`mvn dependency:tree -Dverbose`)
- exception message, full stack trace, and any available logs

**Additional context**

**Information Checklist**
Kindly make sure that you have added all the following information above and checkoff the required fields otherwise we will treat the issuer as an incomplete report
- [ ] Bug Description Added
- [ ] Repro Steps Added
- [ ] Setup information Added

**Comment by alzimmermsft** [comment]
Thanks for filing this issue @vmaroli.

Do you have any details on what is causing the `azure-storage-file-datalake` POM to be considered invalid? I've also found this [StackOverflow post](https://stackoverflow.com/questions/23581194/the-pom-for-name-is-invalid-transitive-dependencies-if-any-will-not-be-avai) around invalid POMs, could you see if the solution there can help resolve this issue?

**Comment by vmaroli** [comment]
Thanks for the quick response. The [StackOverflow post](https://stackoverflow.com/questions/23581194/the-pom-for-name-is-invalid-transitive-dependencies-if-any-will-not-be-avai) helped me resolving the issue. Problem was that, I had an obsolete parent pom.xml in my local
