### ISSUE TITLE
[FEATURE REQ] SchemaRegistryAsyncClient to allow applications to remove old schema versions 

### ISSUE THREAD

**Issue by stevenylai** [Azure/azure-sdk-for-java#31301]
**Is your feature request related to a problem? Please describe.**
I am using the Kafka API to produce Avro messages with auto-registering schema. After a couple of tests, I got an error saying 
```
com.azure.data.schemaregistry.implementation.model.ErrorException: Status code 403... Cannot create schema .. because no more than 25 schemas is allowed
```
I then looked at `SchemaRegistryAsyncClient`. There is only methods for registering schemas, no API to removing.

**Describe the solution you'd like**
If the application is able to register schemas, it should also have the capability to remove. Otherwise, it's a bit awkward that after a few runs, we need to have some operational work to clean up old schema versions

**Describe alternatives you've considered**
Perhaps if the schema registry can be configured to only keep a specific number of versions (older version will be discarded), it will also be fine

**Additional context**
We are using https://github.com/Azure/azure-schema-registry-for-kafka but I think the issue is general and will happen even if we are using `SchemaRegistryAsyncClient` to manually register schemas

**Information Checklist**
Kindly make sure that you have added all the following information above and checkoff the required fields otherwise we will treat the issuer as an incomplete report
- [x] Description Added
- [x] Expected solution specified

**Comment by joshfree** [comment]
@conniey could you please follow up with @stevenylai

**Comment by conniey** [comment]
We generate our client library from the Schema Registry service's REST APIs. It does not look like they currently support this. https://github.com/Azure/azure-rest-api-specs/blob/main/specification/schemaregistry/data-plane/Microsoft.EventHub/stable/2022-10/schemaregistry.json

**Comment by stevenylai** [comment]
Closing for now since the API doesn't support it and a simple work around can be made by deleting and creating the schema registry.
