### ISSUE TITLE
[FEATURE REQ] Simplify API-review process of Spring autoconfiguration classes   

### ISSUE THREAD

**Issue by yiliuTo** [Azure/azure-sdk-for-java#31328]
## Context
Currently many Spring autoconfiguration classes are `public`, which results in that changes on those public APIs like modifying configuration or bean conditions need to go through the API-review process. While according to Spring Boot's [reference](https://docs.spring.io/spring-boot/docs/current/reference/htmlsingle/#using.auto-configuration.disabling-specific), the auto-configuration classes actually more belong to internal classes. Thus we would like to regard them as internal classes as well and simplify the api-review process as much as possible.

## Goal
Omit the api-review process of autoconfiguration and configuration classes.

## Solutions
- Communicate with SDK team and Eng team if needed to modify the api-review tools to pass the check of public api changes from auto-configuration/configuration classes.
- Otherwise, we can consider to refactor our configuration to change the class access modifiers.

**Comment by saragluna** [comment]
Since the Spring Boot 3 branch has been merged into main, so closing this issue now. #41131
