### ISSUE TITLE
[FEATURE REQ] Publish Troubleshooting guide for Spring Cloud Azure JMS starter

### ISSUE THREAD

**Issue by yiliuTo** [Azure/azure-sdk-for-java#31335]
## Context
Spring Cloud Azure 4.x supports Spring JMS integration with Service Bus via library of [com.azure.spring:spring-cloud-azure-starter-servicebus-jms](https://search.maven.org/search?q=a:spring-cloud-azure-starter-servicebus-jms). While leveraging spring-jms with Service bus compared with Qpid, there are many default choices made by spring bringing in impacts on applications' behavior that are not known to developers. We recevied similar issues from different channels to report the same questions. Thus we would like to publish a troubleshooting guide to record the questions/known issues/workaround to help developers.

## Goal
- Publish a Troubleshooting guide under folder sdk/spring/spring-cloud-azure-starter-servicebus-jms
- Record known issues and workarounds about connections, message consuming modes, acknowledge mode, prefetch.
- Record known feature request.

**Comment by stliu** [comment]
what's the status of this?

**Comment by yiliuTo** [comment]
@stliu the content is ready in the DevOps, and is waiting for @chenrujun to help update it to our MS docs.

**Comment by chenrujun** [comment]
@hui1110  is working on it.

## Content
[Link to content](https://dev.azure.com/SpringOnAzure/Spring%20on%20Azure/_wiki/wikis/spring-integration-private.wiki/425/Troubleshoot-Spring-Cloud-Azure-Service-Bus-JMS-Starter-issues).

## Target TOC
```
Developer Guide 
  Spring JMS Support
    Spring JMS Troubshotting Guide
```
https://learn.microsoft.com/en-us/azure/developer/java/spring-framework/spring-jms-support

> ![image](https://user-images.githubusercontent.com/13167207/218907298-6c432bdd-fb98-43ab-baff-332e13f9f512.png)

**Comment by hui1110** [comment]
PR created: https://github.com/MicrosoftDocs/azure-dev-docs-pr/pull/4186
