### ISSUE TITLE
Creation Date for LoadBalancer/Postgressqlserver/mysqlserver/sqlserver

### ISSUE THREAD

**Issue by sumangithub123** [Azure/azure-sdk-for-java#3133]
SDK does not provide methods for finding the creation date for the below ones
1.Loadbalacer
2.PostGres sql server
3.MySql server
4.Sql Server
 
Below are the Classes that does not provide method/api to find creationDate/time 

com.microsoft.azure.management.network.LoadBalancer 
com.microsoft.azure.management.postgresql.v2017_12_01.Server
com.microsoft.azure.management.mysql.v2017_12_01.Server
com.microsoft.azure.management.sql.SqlServer

        <dependency>
            <groupId>com.microsoft.azure</groupId>
            <artifactId>azure</artifactId>
            <version>1.10.0</version>
          
        </dependency>

        <dependency>
            <groupId>com.microsoft.azure.postgresql.v2017_12_01</groupId>
            <artifactId>azure-mgmt-postgresql</artifactId>
            <version>1.0.0-beta-2</version>
        </dependency>
        <dependency>
            <groupId>com.microsoft.azure.mysql.v2017_12_01</groupId>
            <artifactId>azure-mgmt-mysql</artifactId>
            <version>1.0.0-beta-2</version>
        </dependency>

**Comment by kurtzeborn** [comment]
Thank you for opening this issue! We are routing it to the appropriate team for follow up.

**Comment by praries880** [comment]
@sumangithub123  This will require changing the service's swagger/rest API to return the requested info. 
The SDK is autogenerated using the specifications.

Can you kindly elaborate on the use case?

**Comment by sumangithub123** [comment]
@praries880 ,Using  the creation date ,want to perform cost calculation .

**Comment by rachel-msft** [comment]
@sumangithub123 Thank you for your request. If this is for the purposes of cost calculation you likely need the time at which any updates were made to the pricing options (compute, storage etc). Azure database services for MySQL and PostgreSQL don't have an API for getting this date after the fact, and we currently don't have plans to release such an API.
You can explore using the Azure Activity Log which provides a time log of such events, including create and update.

**Comment by aamalvea** [comment]
@sumangithub123 You can accomplish this for SQL DB by getting the creation date for the master DB on the server. These two will have the same creation date.

**Comment by anavinahar** [comment]
We don't current have this in our plan for LB.
