### ISSUE TITLE
[FEATURE REQ] Publish JDBC passwordless library documentation 

### ISSUE THREAD

**Issue by backwind1233** [Azure/azure-sdk-for-java#31336]
## Context
We have beta released our JDBC passwordless libraries, before GA release, we need to make sure our documentation meets the GA quality.

## Goal
Make our passwordless libraries' readme documents include all the necessary information, easy for uses to understand and use.

## Solution
- Highlight our "token-as-password" key concepts.
- Include typical examples.
- Include all exposed paramters.
- azure-identity-providers-core not included. ?
```

Azure identity * plugin library for Java
- Getting started
    Prerequisites
    Include the package
    Include direct dependency
    Prepare the Azure Database for PostgreSQL
    Prepare the working environment
    Create an Azure Database for PostgreSQL server
    Configure a firewall rule for your PostgreSQL server
    Enable Azure AD-based authentication
- Key concepts
    Azure AD authentication with PostgreSQL
    Architecture
    Authenticating with DefaultAzureCredential
- Examples
    Connect using managed identity
    Connect using service principal
    Cloud Configuration
- JDBC Parameters
- Troubleshooting
- Next steps
- Contributing

```

**Comment by backwind1233** [comment]
Link PR: https://github.com/Azure/azure-sdk-for-java/pull/31380

**Comment by saragluna** [comment]
PR merged
