### ISSUE TITLE
[Epic] Set up the engineering tools to matintain Spring Boot 3 support

### ISSUE THREAD

**Issue by moarychan** [Azure/azure-sdk-for-java#31333]
This is the epic issue to track all issues about engineering tools for Spring Boot 3 support

### Context
Since the release of the Spring Cloud Azure 6.0 beta version, the differences between the `main` branch and `feature/spring-boot-3` will become larger and larger, and they will be adapted based on the same Azure SDKs, so there will be a lot of repetitive work, such as synchronization Non `sdk/spring` code, related PRs are automatically created, etc; any Spring Cloud Azure related PR should consider whether making the changes into the two branches. 

Finally, there should be multiple pipelines to set up or enhance with the engineering team together to reduce the manual work.

### Goal
This epic will target the below sub-goals:
- [ ] #31337
       Prepare the feature spec, development should be after the spec signoff.
- [x] #31338
       Such as the tests pipeline of `azure-cosmos` can trigger the tests pipeline to run the integration tests from the source code of `azure-spring-data-cosmos`.
- [x] #31341

**Comment by stliu** [comment]
closing this epic, use feature to track issues
