### ISSUE TITLE
[FEATURE REQ] Set up a pipeline to sync non-spring code from main branch to feature/spring-boot-3 branch

### ISSUE THREAD

**Issue by moarychan** [Azure/azure-sdk-for-java#31337]
### Context
The two major version branches should use the same Azure SDKs, so the sync work need do every week or more frequently, there will be lots of manual work to do.

### Goal
The sync pipeline can weekly create PR automatically, it should include below requirements:
- Necessary labels, such as `azure-spring`, `Client`
- Clear description for PR.
- One week should only exist one PR opened, which means if the first PR has not been merged, then the second PR creation should be skipped.

**Comment by saragluna** [comment]
Closing this now for Spring Boot 3 branch has been merged back to the main.
