### ISSUE TITLE
[FEATURE REQ] GA release passwordless libraries.

### ISSUE THREAD

**Issue by backwind1233** [Azure/azure-sdk-for-java#31344]
## Context
We have beta released our passwordless libraries, 
- [spring-cloud-azure-starter-jdbc-mysql](https://central.sonatype.dev/artifact/com.azure.spring/spring-cloud-azure-starter-jdbc-mysql/4.5.0-beta.1)
- [spring-cloud-azure-starter-jdbc-postgresql](https://central.sonatype.dev/artifact/com.azure.spring/spring-cloud-azure-starter-jdbc-postgresql/4.5.0-beta.1)
- [azure-identity-providers-* libraries.](https://central.sonatype.dev/artifact/com.azure/azure-identity-providers-core/1.0.0-beta.1)
  - azure-identity-providers-core
  - azure-identity-providers-jdbc-postgresql
  - azure-identity-providers-jdbc-mysql  

this month we need to GA our passwordless libraries, we need to make a concrete date for our GA release and make sure all the GA depedencies should be done before the date.
 

## Goal 
Come to a concrete release date for passwordless GA release and make sure our libraries could be released before this date.

## Solution
List all the related things need to be done before GA.
- azure-identity should be GA released before our release. Follow up with Vinay.
- Our libraries meet the GA qualities.
  - Publish documentation for JDBC providers.
  - Release shaded jars for all JDBC providers.  
  - Support JPMS for all JDBC providers.  
- GA api review should be done before release.
- **Ack**: Will azure-identity-providers-* OOB release or monthly release? Relation with our monthly release?
Check all the items, track and ack the time of these tasks.

**Comment by backwind1233** [comment]
We are depends on azure-identity:1.7.x versions, which will be GA on November.

**Comment by stliu** [comment]
So there is no blocker to release?

I see there are 2 man-days planned for this one, and I'm wondering what to do on that 2days?

doing release? I thought this will be regular project release and we have it tracked elsewhere? Just tying to understand what's left in this issue?

**Comment by stliu** [comment]
release a feature

* perform release ( pipeline, tag , artifacts )
* get non code ready
    * doc
    * sample
    * web site
    * spring initializr
 * make announcement

**Comment by backwind1233** [comment]
[azure-identity-extensions_1.0.0](https://github.com/Azure/azure-sdk-for-java/blob/main/sdk/identity/azure-identity-extensions/CHANGELOG.md#100-2022-12-05) is out.

**Comment by saragluna** [comment]
spring-cloud-azure-starter-jdbc-mysql and spring-cloud-azure-starter-jdbc-postgresql 4.5.0 have been released.

**Comment by stliu** [comment]
so why is this issue still open?

**Comment by backwind1233** [comment]
The non code portion has not been ready yet, like doc, spring initializr.

**Comment by stliu** [comment]
closing to avoid meaningless issue
