### ISSUE TITLE
[QUERY] How to get Region/Location specific Network Security Group (Using Java SDK version 1.36).

### ISSUE THREAD

**Issue by shailendrajain24** [Azure/azure-sdk-for-java#31357]
Sample code:
AzureResourceManager.Authenticated authenticated = AzureResourceManager.authenticate(credential, profile);
AzureResourceManager azure = authenticated.withSubscription(SubscriptionId);

azure.networkSecurityGroups().manager().serviceClient().getNetworkSecurityGroups(). // Not a option to fetch NSG at region level.

**Comment by joshfree** [comment]
@weidongxu-microsoft could you help route this control plane sdk question?

**Comment by weidongxu-microsoft** [comment]
@shailendrajain24 1.xx version is deprecated. https://github.com/Azure/azure-libraries-for-java
However, from your code, you seems not using 1.xx (`AzureResourceManager`)

@XiaofeiCao Do you know if this is supported by network?

**Comment by shailendrajain24** [comment]
No we can have multiple NSG in a single region. Please refer below image/screenshot.

![NSG_IN_SINGLE_REGION](https://user-images.githubusercontent.com/5344678/195046564-c14e4690-2afe-41dc-a3e0-2ebb7d99a8a7.jpg)

**Comment by weidongxu-microsoft** [comment]
So far I didn't see backend API that can filter by region.
https://github.com/Azure/azure-sdk-for-java/blob/main/sdk/resourcemanager/azure-resourcemanager-network/src/main/java/com/azure/resourcemanager/network/fluent/NetworkSecurityGroupsClient.java#L369-L436

**Comment by shailendrajain24** [comment]
@weidongxu-microsoft , In NSG not a method that will contain a filter option as a param.

azureResourceManager.networkSecurityGroups().manager().serviceClient().getNetworkSecurityGroups().list(

**Comment by shailendrajain24** [comment]
@weidongxu-microsoft and @Team, Any chance to look that?

**Comment by weidongxu-microsoft** [comment]
"NetworkSecurityGroupsClient" contains the public API from network backend. If it is not there, it is not there.

You had to try other ways. https://github.com/Azure/azure-sdk-for-java/issues/31357#issuecomment-1275482973

**Comment by shailendrajain24** [comment]
Actually we have bulk size NSG and fetching together is creating a memory issue.

**Comment by weidongxu-microsoft** [comment]
To Network service, is there REST API that can get Network Security Group by region/location ?
