### ISSUE TITLE
[BUG] Making EventHub/ServiceBus IT more stable

### ISSUE THREAD

**Issue by fangjian0423** [Azure/azure-sdk-for-java#31355]
## Context

Pipeline IT jobs always run failed, refer [Jobs in run #20221004.1](https://dev.azure.com/azure-sdk/internal/_build/results?buildId=1894663&view=logs&j=bd0fa7bb-1058-5a0c-66c9-14141ade316d&t=838dd5d3-5206-5ea7-b7c4-de420eeaf38f&l=1084), [Jobs in run #20221007.1](https://dev.azure.com/azure-sdk/internal/_build/results?buildId=1902030&view=logs&j=f74c3361-a165-5082-f7e1-df7b9dd161f7&t=2fac735e-5fb2-5846-0aa2-38e23031b9d3&l=2140) and [Jobs in run #20220929.1](https://dev.azure.com/azure-sdk/internal/_build/results?buildId=1884381&view=logs&j=628b3ae7-b010-5d76-0167-08f9e6f337c2&s=e5e99e16-a0fd-5b2f-a058-e5dd0e13d0fe&t=5bb9b0cf-2b83-5130-973b-79b7a029cac2&l=365).

It seems both IT failed because of the Access control is not active.

```bash
[com.azure.storage](http://com.azure.storage/).blob.models.BlobStorageException: If you are using a StorageSharedKeyCredential, and the server returned an error message that says 'Signature did not match' ..
```

```bash
reactor.core.Exceptions$ErrorCallbackNotImplemented: [com.azure](http://com.azure/).messaging.servicebus.ServiceBusException: Unauthorized access. 'Send' claim(s) are required to perform this operation. Resource: 'sb://***.***/topic1'. TrackingId:3ff7c86d4b574b55b8a2f5ab7653f5ff_G26, SystemTracker:gateway7, Timestamp:2022-10-04T15:28:18
```

```bash
com.azure.messaging.servicebus.ServiceBusException: Unauthorized access. 'Listen' claim(s) are required to perform this operation. Resource: 'sb://***.***/topic1/subscriptions/topicsub'. TrackingId:b416725b32a64130b324c61e81f86f4f_G28, SystemTracker:gateway7, Timestamp:2022-09-29T07:24:16, errorContext[NAMESPACE: ***.***. ERROR CONTEXT: N/A, PATH: topic1/subscriptions/topicSub, REFERENCE_ID: topic1/subscriptions/topicSub_df63ff_1664436255091, LINK_CREDIT: 1]
```

Rerun IT maybe success but I don't think it is the best way. We need investigate why it always run failed.
 

## Goal

Making java-spring-test pipeline jobs more stable.

**Comment by fangjian0423** [comment]
IT added produce error scenario before,  https://github.com/Azure/azure-sdk-for-java/issues/31109

**Comment by fangjian0423** [comment]
## Access control scenarios


1. Event Hubs: Storage ✅, Event Hubs Data ❌

Message produce failed. We can get error message in error MessageChannel and add retry operations:

```java
@ServiceActivator(inputChannel = "errorChannel")
public void processError(Message sendFailedMsg) {
    if(sendFailedMsg.getPayload() instanceof AzureSendFailureException &&
        ((AzureSendFailureException)sendFailedMsg.getPayload()).getCause() instanceof AmqpException) {
        if(((AmqpException)(((AzureSendFailureException)sendFailedMsg.getPayload()).getCause())).getErrorCondition()
            == AmqpErrorCondition.UNAUTHORIZED_ACCESS) {
            // do retry operations
        }
    }
    // do other things
}
```


2. Event Hubs: Storage ❌, Event Hubs Data ✅

**Message produce success by EventHubsTemplate** 😰, but the terminal will display error logs.

So we can't get error message in error MessageChannel and add retry operations.

Message produce success is the correct behavior, perhaps need SDK Team to fix it.


3. Event Hubs: Storage ❌, Event Hubs Data ❌

Similar with scenario 1 and 2.

4. Event Hubs: Storage ✅, Event Hubs Data ✅

Event Hubs cases run successfully.

5. Service Bus: Data ❌

Similar with scenario 1. We can add retry operations.

6. Service Bus: Data ✅

Service Bus cases run successfully.


## Conclusion

Scenario 2 and 3 are the big problem and we can't use common retry operations cover all scenarios.

So now investigate retry configurations to rerun pipeline failed jobs.

**Comment by fangjian0423** [comment]
Josh confirm that there's no lag for the permission to take effect.

Besides, Bill takes a look at the the pipeline log. He found the [token acquisition succeeded](https://dev.azure.com/azure-sdk/internal/_build/results?buildId=1902030&view=logs&j=f74c3361-a165-5082-f7e1-df7b9dd161f7&t=fe99bf22-adac-5443-570b-54ceae744c92&l=124), but it's really strange the permissions issue occur. 

And he gives some advices: some part of the environment isn’t being cleaned up and thus being configured by some other test resource deployment.

**Comment by fangjian0423** [comment]
The assignment role is correct by [run log](https://dev.azure.com/azure-sdk/internal/_build/results?buildId=1902030&view=logs&j=bd0fa7bb-1058-5a0c-66c9-14141ade316d&t=6baad2a2-75df-5e5e-54f2-25fc1a5756b1&l=1008).

Besides, the test resource will be removed at last by [run log](https://dev.azure.com/azure-sdk/internal/_build/results?buildId=1902030&view=logs&j=bd0fa7bb-1058-5a0c-66c9-14141ade316d&t=b843bd35-c9b6-5414-fe00-6b312fb60dcf&l=18).

Other useful information: IT runs begin at 15:27:15 PM, and the test resource deploy successfully at 3:24:10 PM.

**Comment by fangjian0423** [comment]
Now the permissions error occur occasionally. 

After team discussion, we decide to keep watching the pipeline. if the permissions error occur frequently, we will try to fix it.

**Comment by backwind1233** [comment]
**ServicebusIT** runnint test result on **2022-10-21**

*   4/10  passed

*   6/10  failed

| Try    | Link                                                                                                 | status | Failed      IT                                                           |
| ------ | ---------------------------------------------------------------------------------------------------- | ------ | ---------------------------------------------------------------------- |
| try 1  | [link](https://dev.azure.com/azure-sdk/internal/_build/results?buildId=1934892\&view=results "link") | passed |                                                                        |
| try 2  | [link](https://dev.azure.com/azure-sdk/internal/_build/results?buildId=1934934\&view=results "link") | passed |                                                                        |
| try 3  | [link](https://dev.azure.com/azure-sdk/internal/_build/results?buildId=1934931\&view=results "link") | failed | ServiceBusMultiBindersIT&#xA;ServiceBusSingleBinderIT&#xA;&#xA;        |
| try 4  | [link](https://dev.azure.com/azure-sdk/internal/_build/results?buildId=1934938\&view=results "link") | passed |                                                                        |
| try 5  | [link](https://dev.azure.com/azure-sdk/internal/_build/results?buildId=1934952\&view=results "link") | failed | build from source failed, network issue                                |
| try 6  | [link](https://dev.azure.com/azure-sdk/internal/_build/results?buildId=1935027\&view=results "link") | failed | ServiceBusMultiBindersIT&#xA;ServiceBusSingleBinderIT                  |
| try 7  | [link](https://dev.azure.com/azure-sdk/internal/_build/results?buildId=1935028\&view=results "link") | failed | ServiceBusMultiBindersIT                                               |
| try 8  | [link](https://dev.azure.com/azure-sdk/internal/_build/results?buildId=1935029\&view=results "link") | passed |                                                                        |
| try 9  | [link](https://dev.azure.com/azure-sdk/internal/_build/results?buildId=1935031\&view=results "link") | failed | ServiceBusMultiBindersIT&#xA;ServiceBusSingleBinderIT&#xA;ServiceBusIT |
| try 10 | [link](https://dev.azure.com/azure-sdk/internal/_build/results?buildId=1935033\&view=results "link") | failed | ServiceBusMultiBindersIT&#xA;ServiceBusSingleBinderIT&#xA;ServiceBusIT |

**Comment by fangjian0423** [comment]
Some useful informations:

1. Run IT in local, the error log is same with pipeline log if not do role assignment.
`com.azure.messaging.servicebus.ServiceBusException: Unauthorized access. 'Listen' claim(s) are required to perform this operation. Resource: ...`

2. [pipeline log](https://dev.azure.com/azure-sdk/internal/_build/results?buildId=1935033&view=logs&j=891660a1-3140-5071-293d-dfda0e27b976&t=37e3980f-9e52-52e5-73b0-382d4931dcec&l=3919) shows 4 role assignments provisioning status is succeeded(there are 4 Microsoft.Authorization/roleAssignments in test-resources.json).
`Resource Microsoft.Authorization/roleAssignments ... provisioning status is succeeded`

3. Timeline:

 - Service Bus test resource deploy successfully at 03:07:00 PM
 - All integration tests run begin at 03:07:58
 - Service Bus permission error occur at 03:08:05

Suppose there is a lag for permission to take effect.

**Comment by backwind1233** [comment]
> Suppose there is a lag for permission to take effect.
I think @fangjian0423 should be right, 
we can reproduce this behavior in locally.

## Reproduce steps
1. Setup Azure Resources for ServiceBusSingleBinderIT.
  1. create a servicebus namespace.
  2. create a queue named queue1
  3. create a topic named topic1
  4. crete a subscription `topicSub` in `topic1` 
2. Configure application.yml and application-servicebus-binder-single.yml 
3. Assign role to the service principal and run ServiceBusSingleBinderIT immediately.
4. Run ServiceBusSingleBinderIT after 7 minutes.


Even though the assignment is completed, it will take  3~7 minutes to take effect.

**Comment by fangjian0423** [comment]
After update the sequence of IT resources below:

- spring/spring-cloud-azure-integration-tests/test-resources/servicebus
- spring/spring-cloud-azure-integration-tests/test-resources/eventhubs
- spring/spring-cloud-azure-integration-tests/test-resources/appconfiguration
- spring/spring-cloud-azure-integration-tests/test-resources/cosmos
- spring/spring-cloud-azure-integration-tests/test-resources/keyvault
- spring/spring-cloud-azure-integration-tests/test-resources/storage

IT results:

| Link |  Status      | Failed IT | Reason |
| ----------- | ----------- | ----------- | ----------- |
| [try 1 link](https://dev.azure.com/azure-sdk/internal/_build/results?buildId=1945246&view=results)       |  UsGov failed      | StorageQueueIT, StorageBlobIT, EventHubBinderBatchModeIT      | Storage Permission error     |
| [try 2 link](https://dev.azure.com/azure-sdk/internal/_build/results?buildId=1945350&view=results)       |  passed     | /       | Warning: Public Service Bus Resource Deploy failed     |
| [try 3 link](https://dev.azure.com/azure-sdk/internal/_build/results?buildId=1945423&view=results)       |  All failed      |  EventHubsBinderRecordModeIT, EventHubsBinderBatchModeIT  | Public -> EventHubsBinderRecordModeIT failed(seems consumer didn't startup, but no error logs), UsGov -> IT passed, remove test resource error, China -> EventHubs Storage Permission error    |
| [try 4 link](https://dev.azure.com/azure-sdk/internal/_build/results?buildId=1945471)       |  UsGov failed      |  EventHubsBinderBatchModeIT, StorageBlobIT, StorageQueueIT       | Storage Permission error     |
| [try 5 link](https://dev.azure.com/azure-sdk/internal/_build/results?buildId=1945539&view=results)       |   passed    | /       |   Warning: Public remove rest resource error  |
| [try 6 link](https://dev.azure.com/azure-sdk/internal/_build/results?buildId=1945583&view=results)       |   China failed    |   StorageQueueIT      |   Storage Permission error  |
| [try 7 link](https://dev.azure.com/azure-sdk/internal/_build/results?buildId=1945671&view=results)       |   passed    |   /      |   /  |
| [try 8 link](https://dev.azure.com/azure-sdk/internal/_build/results?buildId=1947275&view=results)       |   passed    |   /      |   /  |
| [try 9 link](https://dev.azure.com/azure-sdk/internal/_build/results?buildId=1947374)       |   Public, UsGov failed    |   EventHubsBinderBatchModeIT      |   Public -> App Config Resource Deploy failed, UsGov -> Storage Permission error  |

The effect is not very good, we need try another way.

**Comment by fangjian0423** [comment]
Find something useful in Azure RBAC Troubleshoot:

[Symptom - Role assignment changes are not being detected](https://learn.microsoft.com/en-us/azure/role-based-access-control/troubleshooting?tabs=bicep#symptom---role-assignment-changes-are-not-being-detected)

You recently added or updated a role assignment, but the changes are not being detected. You might see the message Status: 401 (Unauthorized).

**Cause 1**

Azure Resource Manager sometimes caches configurations and data to improve performance. When you assign roles or remove role assignments, it can take up to 30 minutes for changes to take effect.

**Solution 1**

If you are using the Azure portal, Azure PowerShell, or Azure CLI, you can force a refresh of your role assignment changes by signing out and signing in. If you are making role assignment changes with REST API calls, you can force a refresh by refreshing your access token.

If you are add or remove a role assignment at management group scope and the role has DataActions, the access on the data plane might not be updated for several hours. This applies only to management group scope and the data plane.

**Comment by fangjian0423** [comment]
I think there are 3 ways to resolve the problem(or improve IT success rate):

1. Adding `Microsoft.Resources/deploymentScripts` resource

Script content is "start-sleep -Seconds 120", sleep 120s to wait the role assignment effect.

I try 9 rounds after adding `Microsoft.Resources/deploymentScripts` resource, 4 passed and 5 failed (resource deploy issue). Looks good.

pros: easy and not waste resource
cons: Azure China Cloud don't support `Microsoft.Resources/deploymentScripts` resource

2. Adding dummy resource at last. 

Similar with way 1. Using dummy resource replace of sleep script.

I try to put ServiceBus and EventHubs to top2 deploy resource, but EventHubs also sometimes occur storage permission error, refer https://github.com/Azure/azure-sdk-for-java/issues/31355#issuecomment-1286488480. So i think we need adding dummy resource.

pros: easy
cons: Resource waste

3. Don't use Service Principal and Role Assignment, use Connection String.

Refer Azure RBAC Troubleshoot -> [Symptom - Role assignment changes are not being detected](https://learn.microsoft.com/en-us/azure/role-based-access-control/troubleshooting?tabs=bicep#symptom---role-assignment-changes-are-not-being-detected).

pros: will fix it completely.
cons: lots of modifications.

**Comment by fangjian0423** [comment]
Choose adding dummy resource at last.

IT results:

| Link |  Status      | Failed IT | Reason | Dummy Resource Deploy Time Spent(random choose 1 job) | 
| ----------- | ----------- | ----------- | ----------- | ----------- |
| [try 1 link](https://dev.azure.com/azure-sdk/internal/_build/results?buildId=1951739&view=results)       |  Public failed      | EventHubsBinderRecordModeIT     | Consumer didn't startup, but no error log(not permission issue)     | 3m54s | 
| [try 2 link](https://dev.azure.com/azure-sdk/internal/_build/results?buildId=1952169&view=results)       |  China failed     | EventHubsBinderSyncModeIT       | Consumer didn't startup, but no error log(not permission issue) | 2m19s | 
| [try 3 link](https://dev.azure.com/azure-sdk/internal/_build/results?buildId=1954425&view=results)       |  passed     | /       | / | 3m35s | 
| [try 4 link](https://dev.azure.com/azure-sdk/internal/_build/results?buildId=1954451&view=results)       |  China failed     | /       | deploy issue | 2m12s | 
| [try 5 link](https://dev.azure.com/azure-sdk/internal/_build/results?buildId=1954487&view=results)       |  passed     | /       | / | 4m33s | 
| [try 6 link](https://dev.azure.com/azure-sdk/internal/_build/results?buildId=1954622&view=results)       |  passed     | /       | / | 3m48s | 
| [try 7 link](https://dev.azure.com/azure-sdk/internal/_build/results?buildId=1954678&view=results)       |  passed     | /       | / | 3m45s | 
| [try 8 link](https://dev.azure.com/azure-sdk/internal/_build/results?buildId=1954885&view=results)       |  UsGov failed     | /       | deploy issue | 6m63s | 
| [try 9 link](https://dev.azure.com/azure-sdk/internal/_build/results?buildId=1954968&view=results)       |  UsGov failed     | /       | deploy issue | 7m59s | 
| [try 10 link](https://dev.azure.com/azure-sdk/internal/_build/results?buildId=1955103&view=results)       |  passed     | /       | / | 4m36s | 

There is no permission issue, looks good.

**Comment by fangjian0423** [comment]
Closing this issue via adding dummy resource and modify the sequence of deploy resource to improve IT success rate.
