### ISSUE TITLE
[FEATURE REQ] Support Password - Less connection for Azure Redis cache in Spring

### ISSUE THREAD

**Issue by saragluna** [Azure/azure-sdk-for-java#31350]
**Is your feature request related to a problem? Please describe.**
For Spring Cloud Azure 4.x, we started to support passwordless connection to 1st and 3rd party Azure Services. So far, we have provided passwordless connection support to Azure Event Hubs for Kafka, Azure database for MySQL, Azure database for PostgreSQL. Now, we would like to enlarge the scope to Azure Cache for Redis.

**Describe the solution you'd like**
Deliver a feature spec for the passwordless support to Redis with Spring framework.
The feature spec should cover all customer-aware information about our spring Redis support library
- artifact id
- configurable properties
- public API
- other deliverable resources like docs

Scopes:
- Which clients will be included: Jedis, Lettuce, Reddison
- Which Spring Boot version to support: Spring Boot 2, Spring Boot 3 (these two versions have different Lettuce clients)

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Information Checklist**
- [ ] #32028
- [ ] Feature Spec Signoff

**Comment by yiliuTo** [comment]
https://github.com/Azure/azure-sdk-for-java/tree/main/sdk/identity/azure-identity/src/samples/Azure-Cache-For-Redis

**Comment by yiliuTo** [comment]
https://github.com/Azure/azure-sdk-for-java/blob/main/sdk/identity/azure-identity/src/samples/Azure-Cache-For-Redis/Lettuce/Azure-AAD-Authentication-With-Lettuce.md

**Comment by stliu** [comment]
about the scope, I think we should only cover jedis and lettuce, those two are supported by spring-data-redis, https://spring.io/projects/spring-data-redis I don't see it support redission

though Redission has spring support but I think we can consider that later and wait for more customer ask for it

**Comment by backwind1233** [comment]
## Updates

### Functional Updates
- The [PR:Support Redis passwordless connections for Azure Redis Cache in Spring](https://github.com/Azure/azure-sdk-for-java/pull/32794) has been merged into main branch.
- The PR won't be merged into feature/spring-boot3 branch.
- Now it only support Azure Redis passwordless feature with Jedis 3.x and Spring boot 2.x .
  - For Jedis 4.x, [Lettuce](https://mvnrepository.com/artifact/io.lettuce/lettuce-core), we plan to support in Spring Boot 3.x .	

### Non-Functional Updates
We plan to update  Redis passwordless docs, Redis passwordless samples on Feb.

**Comment by backwind1233** [comment]
Closing this issue, due to the [PR ](https://github.com/Azure/azure-sdk-for-java/pull/32794) has been merged to main.

**Comment by backwind1233** [comment]
### Updates
There are breaking changes from the Azure redis server side.

Before:
Client side use username and Azure AD issued token(as the password) to create connections. After connections created, it doesn't matter if the token expires.

After:
Client side use username and Azure AD issued token(as the password) to create connections. 
Client side need send auth command with refreshed token to redis server before the token expires.

**Comment by backwind1233** [comment]
Updates
There will be breaking changes from the Azure redis server side.

Before:
Username for AUTH command is resource name.

After:
Username for AUTH command would be AAD objectId (for example, Service Principal Object Id in case AAD App is used) 
 instead of resource name.
