### ISSUE TITLE
[QUERY] Async client underlying resource utilization

### ISSUE THREAD

**Issue by andrepibo-db** [Azure/azure-sdk-for-java#31364]
**Query/Question**
With regards to resource (threads, memory etc) utilization by Azure async clients (I'm using `DataLakeDirectoryAsyncClient`), could you please help clarifying the following? (I couldn't find an answer on the Azure docs nor the client's implementation). 

1. What resources do the client allocate? For the client to be truly async I suppose it instantiates a thread pool/execution context in order to process the async requests, however there is no documentation available about it. Could you please share details on this topic? 

2. By looking at the documentation and code interfaces I have not identified a way to programatically customize the resource utilization, I might have blindspots though. Is there a way to do it? 

***Why is this not a Bug or a feature Request?***
This is an information/clarification request.

**Setup (please complete the following information if applicable):**
- Library/Libraries: com.azure:azure-storage-file-datalake:12.7.4
 
 **Information Checklist**
 Kindly make sure that you have added all the following information above and checkoff the required fields otherwise we will treat the issuer as an incomplete report
- [x] Query Added
- [x] Setup information Added

**Comment by joshfree** [comment]
@jaschrep-msft could you please take a look (feel free to pull in @alzimmermsft as needed too)
