### ISSUE TITLE
[QUERY] Tune com.azure.messaging.servicebus to not log error level messages on automatically recoverable situations

### ISSUE THREAD

**Issue by jnykopp-dias** [Azure/azure-sdk-for-java#31378]
**Query/Question**

The SDK logs quite verbosely with level "error" even in situations where the SDK's service bus client is able to recover from the apparent error. The SDK `com.microsoft.azure.servicebus` we used earlier (but were told to migrate away from) did not log errors upon recoverable situations.

How should we tune the SDK's logging so that it wouldn't report automatically recoverable errors with error log level?

Can we safely turn off all SDK's logging without missing potentially critical, non-automatically-recoverable errors? (Though then we'd lose debuggability if there are unrecoverable system failures.)

Or could the logging in the SDK be improved in some way to differentiate between truly erroneous situations where e.g. service bus messages are lost, and situations where the SDK eventually is able to recover without problems visible to SDK end user?

Background:

We started recently using `com.azure.messaging.servicebus` version 7.11.0 to connect to Azure Service Bus. The problem we are facing is that the SDK logs quite verbosely with level "error" even in situations where the SDK's service bus client is able to recover from the apparent error.

Some error log messages even originate from reactor-library that this SDK is using, like "Operator called default onErrorDropped" from `reactor.core.publisher.Operators` logger (https://github.com/reactor/reactor-core/blob/cd75a8ea29b1d89fa65ee5599e6fa4a2dc43b4a1/reactor-core/src/main/java/reactor/core/publisher/Operators.java#L636).

Our service's health monitoring is designed based on the assumption that all log messages with level "error" indicate a situation where data has been lost in service bus traffic and a human operator has to manually intervene. Previous SDK `com.microsoft.azure.servicebus` did not log errors when it was able to recover from the error. Due to some other issues (e.g. `com.microsoft.azure.servicebus` not being able to reconnect on the fly when a queue it was connected to was for some reason transferred to another container in the background by Azure cloud infrastructure operators) we were told by Azure Support Engineer to migrate to `com.azure.messaging.servicebus`.

By the way, the documentation at https://learn.microsoft.com/en-us/java/api/overview/azure/messaging-servicebus-readme?view=azure-java-stable#enable-client-logging points to a non-existing Wiki page https://github.com/Azure/azure-sdk-for-java/wiki/Logging-with-Azure-SDK.

Examples of situations where SDK logs an error but seems to recover.

```
{
	"id": "AQAAAYOCA39VqgFoygAAAABBWU9DQTM5NUFBQnFCSnJIcmk2bW9nQUE",
	"content": {
		"timestamp": "2022-09-28T02:53:30.837Z",
		"tags": [
			"source:undefined"
		],
		"host": "redacted",
		"service": "redacted",
		"attributes": {
			"thread_name": "reactor-executor-14",
			"exception": "Cannot create receive link from a closed session., errorContext[NAMESPACE: redacted.servicebus.windows.net. ERROR CONTEXT: N/A, PATH: engine-actions]",
			"connectionId": "MF_18b0fe_1664306084975",
			"level": "ERROR",
			"HOSTNAME": "redacted",
			"host": "redacted",
			"level_value": 40000,
			"logger_name": "com.azure.core.amqp.implementation.ReactorSession",
			"sessionName": "redacted",
			"linkName": "redacted_d9bb94_1664323849044",
			"az": {
				"sdk": {
					"message": ""
				}
			},
			"@version": "1",
			"@timestamp": "2022-09-28T02:53:30.837Z",
			"entityPath": "redacted"
		}
	}
}
```

```
{
	"id": "AQAAAYOCA45Rcc9ozQAAAABBWU9DQTQ2M0FBQl9sdlRhaHFXSFdBQUQ",
	"content": {
		"timestamp": "2022-09-28T02:53:34.673Z",
		"tags": [
			"source:undefined"
		],
		"host": "redacted",
		"service": "redacted",
		"message": "Operator called default onErrorDropped",
		"attributes": {
			"thread_name": "reactor-executor-18",
			"stack_trace": "reactor.core.Exceptions$ErrorCallbackNotImplemented: com.azure.core.amqp.exception.AmqpException: Connection reset, errorContext[NAMESPACE: redacted.servicebus.windows.net. ERROR CONTEXT: N/A]\nCaused by: com.azure.core.amqp.exception.AmqpException: Connection reset, errorContext[NAMESPACE: redacted.servicebus.windows.net. ERROR CONTEXT: N/A]\n\tat com.azure.core.amqp.implementation.ExceptionUtil.toException(ExceptionUtil.java:85)\n\tat com.azure.core.amqp.implementation.handler.ConnectionHandler.notifyErrorContext(ConnectionHandler.java:332)\n\tat com.azure.core.amqp.implementation.handler.ConnectionHandler.onTransportError(ConnectionHandler.java:235)\n\tat org.apache.qpid.proton.engine.BaseHandler.handle(BaseHandler.java:191)\n\tat org.apache.qpid.proton.engine.impl.EventImpl.dispatch(EventImpl.java:108)\n\tat org.apache.qpid.proton.reactor.impl.ReactorImpl.dispatch(ReactorImpl.java:324)\n\tat org.apache.qpid.proton.reactor.impl.ReactorImpl.process(ReactorImpl.java:291)\n\tat com.azure.core.amqp.implementation.ReactorExecutor.run(ReactorExecutor.java:91)\n\tat reactor.core.scheduler.SchedulerTask.call(SchedulerTask.java:68)\n\tat reactor.core.scheduler.SchedulerTask.call(SchedulerTask.java:28)\n\tat java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)\n\tat java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:304)\n\tat java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)\n\tat java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)\n\tat java.base/java.lang.Thread.run(Thread.java:833)\n",
			"service": "redacted",
			"level": "ERROR",
			"HOSTNAME": "redacted",
			"host": "redacted",
			"level_value": 40000,
			"logger_name": "reactor.core.publisher.Operators",
			"@version": "1",
			"@timestamp": "2022-09-28T02:53:34.673Z"
		}
	}
}
```

```
{
	"id": "AQAAAYOB7QJD9gs0WQAAAABBWU9CN1FKbkFBQ1l1NXFyMmtqdkVRQUQ",
	"content": {
		"timestamp": "2022-09-28T02:28:57.027Z",
		"tags": [
			"source:undefined"
		],
		"host": "redacted",
		"service": "redacted",
		"message": "Errors occurred upstream.\nThe service was unable to process the request; please retry the operation. For more information on exception types and proper exception handling, please refer to http://go.microsoft.com/fwlink/?LinkId=761101 TrackingId:54bfae03ab884353807a0739d072c9ec_G56, SystemTracker:gateway7, Timestamp:2022-09-28T02:28:04, errorContext[NAMESPACE: redacted.servicebus.windows.net. ERROR CONTEXT: N/A, PATH: redacted, REFERENCE_ID: redacted_fd5fec_1664324723530, LINK_CREDIT: 1]",
		"attributes": {
			"thread_name": "boundedElastic-65",
			"service": "redacted",
			"level": "ERROR",
			"HOSTNAME": "redacted",
			"host": "redacted",
			"level_value": 40000,
			"logger_name": "com.azure.messaging.servicebus.FluxAutoLockRenew$LockRenewSubscriber",
			"@version": "1",
			"@timestamp": "2022-09-28T02:28:57.027Z"
		}
	}
}
```

***Why is this not a Bug or a feature Request?***

We migrated from the earlier SDK `com.microsoft.azure.servicebus` where the design seemed to avoid logging at "error" level upon connection etc. problems that it was able to automatically resolve.

We are not sure if we should expect the same behavior from this SDK and we don't know if it's possible to tune the SDK's logging to suit our needs. The documentation is a bit lacking in that regard.

If the library doesn't currently allow tuning of logging to suit our needs, then this might be a feature request for improving the logging in the SDK so that it'd be possible to differentiate between truly erroneous situations where data is lost, and situations where the SDK eventually is able to recover without problems visible to SDK end user.

**Setup (please complete the following information if applicable):**
 - OS: AKS pod on Azure cloud Linux
 - IDE: N/A
 - Library/Libraries: com.azure.messaging.servicebus version 7.11.0; logback logging library
 
 **Information Checklist**
 Kindly make sure that you have added all the following information above and checkoff the required fields otherwise we will treat the issuer as an incomplete report
- [x] Query Added
- [x] Setup information Added

**Comment by joshfree** [comment]
@anuchandy @ki1729 could you please follow up?

**Comment by conniey** [comment]
Thanks for the information. Yeah. this is something we need to work on as part of: https://github.com/Azure/azure-sdk-for-java/issues/20836

**Comment by anuchandy** [comment]
Closing this infavor of the tracking issue 20836
