### ISSUE TITLE
[QUERY] Why getVirtualMachines().listByLocation response not contain VirtualMachineInner.instanceView()?

### ISSUE THREAD

**Issue by shailendrajain24** [Azure/azure-sdk-for-java#31382]
**Query/Question**

Azure get Instances/VM via  listByLocation() not returning the mentioned values in response object (InstanceView).

PagedIterable<VirtualMachineInner> virtualMachineInners = azure.virtualMachines().manager().serviceClient().getVirtualMachines().listByLocation("eastus", Context.NONE);

for (VirtualMachineInner inner : virtualMachineInners) {
         System.out.println(inner.instanceView());// Getting null and that will contain some useful primary info like machine power state and extensions.
}

**Comment by weidongxu-microsoft** [comment]
@shailendrajain24 
This is service behavior. I believe the reason is getting instance view of each VM takes extra resource to process. And it is not economical (or take exceedingly long time)  to do this for all 200 in a page.

**Comment by shailendrajain24** [comment]
@weidongxu-microsoft , Is there any way to do it in optimise way.

**Comment by weidongxu-microsoft** [comment]
@shailendrajain24 

You might try ARG https://learn.microsoft.com/en-us/azure/virtual-machines/resource-graph-samples?tabs=azure-cli#count-of-virtual-machines-by-power-state

SDK https://github.com/Azure/azure-sdk-for-java/tree/main/sdk/resourcegraph

**Comment by weidongxu-microsoft** [comment]
https://github.com/Azure-Samples/compute-java-manage-vm-async/issues/3#issuecomment-1202146781

**Comment by nagappan080810** [comment]
Through azure resource graph, can we get all the below  information ? (because we were expecting instance view to get these values..) 

Status like stop/start/deallocate
Address Space
Managed Status
CPU Usage
Extensions
