### ISSUE TITLE
[QUERY] Correlate Network Watcher and Network Security Group

### ISSUE THREAD

**Issue by ihsanhaikalz** [Azure/azure-sdk-for-java#31387]
I would like to get the information of the flow log retention period of network watcher similar to the command 

```
az network watcher flow-log show
	--nsg cc-production-nsg
	--resource-group cloud-shell-storage-westeurope
	--query 'retentionPolicy'
```

However, when I tried to do it in Java I could not directly find the equivalent method and have to iterate the network watchers for the flow log settings. The problem is that it requires to correlate Network watcher with Network Security Group that is unknown to me. Here is the code:
```

 AzureResourceManager azure = AzureResourceManager
                .authenticate(credential, profile)
                .withDefaultSubscription();

        NetworkWatchers networkWatcherService  = azure.networkWatchers();
        NetworkSecurityGroups networkSecurityGroupService = azure.networkSecurityGroups();
        ResourceGroups resourceGroupService = azure.resourceGroups();

        List<ResourceGroup> resourceGroups = resourceGroupService.list().stream().collect(Collectors.toList());

        for(ResourceGroup resourceGroup: resourceGroups){
            List<com.azure.resourcemanager.network.models.NetworkWatcher> networkWatchers = networkWatcherService.listByResourceGroup(resourceGroup.name()).stream().collect(Collectors.toList());
            
            for(com.azure.resourcemanager.network.models.NetworkWatcher nw: networkWatchers){
                nw.getFlowLogSettings(networkSecurityGroupID); //How can I know what is the network security group ID for the following network watcher?
            }
```

**Comment by weidongxu-microsoft** [comment]
@ihsanhaikalz 

I think there is at most one network watcher per region.
https://learn.microsoft.com/en-us/azure/network-watcher/frequently-asked-questions#why-is-only-one-instance-of-network-watcher-allowed-per-region--

Hence one just match the region/location of NSG and NW.

**Comment by ihsanhaikalz** [comment]
@weidongxu-microsoft yes technically you are right, but regardless for non knowing user like me would still require some kind of information what is the actual network watcher's ID in that region to be correlated to the network security group

**Comment by weidongxu-microsoft** [comment]
I would leave it to @XiaofeiCao to decide whether we would add some convenience method to do same to CLI in Java SDK.

@ihsanhaikalz But please understood that the basic role of the mgmt SDK is to provide REST API calls (it is not intended to be a CLI).

**Comment by XiaofeiCao** [comment]
Hi @ihsanhaikalz 

You can use the following code snippet for getting FlowLogSettings:
```java
NetworkSecurityGroup nsg = networkManager.networkSecurityGroups().getById(nsgId);

Optional<NetworkWatcher> nwOptional = networkManager.networkWatchers().list().stream().filter(nw -> nw.region().equals(nsg.region())).findAny();
nwOptional.ifPresent(nw -> {
    FlowLogSettings logSettings = nw.getFlowLogSettings(nsgId);
});
```

We won't provide support for the cli equivalent interface since this is quite straightforward.
