### ISSUE TITLE
[QUERY] Why don't we have option to filter in readAllItems

### ISSUE THREAD

**Issue by brijeshsinghNuance** [Azure/azure-sdk-for-java#31384]
I don't see an option to provide filter option ( where clause) with readAllItems function. There is CosmosQueryRequestOptions but still not able to find any option to provide these filters.

**Comment by kushagraThapar** [comment]
@rinatmini  please take a look at this, thanks!

**Comment by TheovanKraay** [comment]
The [`queryItems`](https://github.com/Azure-Samples/azure-cosmos-java-sql-api-samples/blob/0ead4ca33dac72c223285e1db866c9dc06f5fb47/src/main/java/com/azure/cosmos/examples/documentcrud/async/DocumentCRUDQuickstartAsync.java#L270-L287) method should be used instead, `readAllItems` is just a convenience method so you don't have to write out `select * from c` or `select * from c where partitionKey = 'x'`.
