### ISSUE TITLE
Throw better exceptions than just RestException when an error occurs

### ISSUE THREAD

**Issue by conniey** [Azure/azure-sdk-for-java#3139]
We should throw an exception like "ConfigurationSettingNotFound" or "ConfigurationSettingLockedException" when the service is unable to perform an action. This is more meaningful than having the user deserialise and make sense of the generic RestException.

**Comment by conniey** [comment]
May want to consider throwing unchecked exceptions like RuntimeException and then documenting the behaviour.

**Comment by mayurid** [comment]
@alzimmermsft : For you to review and look into.
//cc: @conniey and @JonathanGiles

**Comment by JonathanGiles** [comment]
I would say that this issue has transformed into #3302, and is blocked on #3229 being implemented also. I would propose that this issue be closed barring objections from @conniey

**Comment by conniey** [comment]
Sounds good. 👍
