### ISSUE TITLE
Why Synchronised send failed without exception? [QUERY]

### ISSUE THREAD

**Issue by jasw** [Azure/azure-sdk-for-java#31397]
**Query/Question**

My use case is simple -- expose an API to send one message to Azure Topics synchronously and report the result (success or failure) back (http 200 if success). 

I have seen the Azure Message Bus client library failed to send the message once (happens very rarely )but did not throw any exception. Is this a bug? 
 
***Why is this not a Bug or a feature Request?***
Not sure if this a bug. I checked the source code, the Synchronised client actually uses Async client internally but I fail to find anyway to register a 'listener' for failures.  I would expect according to the method signature the exceptions are the only way to report failures. 

**Setup (please complete the following information if applicable):**
Library:
 azure-messaging-servicebus 7.4.0
 
Code snippet:
` private ServiceBusSenderClient getSender(String topicCS, String topicName) {

        if(cachedClientByTopic.containsKey(topicName)){
            return cachedClientByTopic.get(topicName);
        }else{
            ServiceBusSenderClient client = new ServiceBusClientBuilder().transportType(AmqpTransportType.AMQP_WEB_SOCKETS)
                    .connectionString(topicCS)
                    .sender()
                    .topicName(topicName)
                    .buildClient();
            cachedClientByTopic.put(topicName, client);
            return client;
        }

    }

    ServiceBusSenderClient sender = messageSender.getSenderWithTopic(eventType);

        try {
            sender.sendMessage(message);
        } catch (Exception e) {
//Expect that if there is no exception then the send is successful
            log.error("error sending message: "+message, e);
            throw new InternalServerErrorException(traceId, e.getMessage());
        }
return Response.ok().build();
`

**Comment by ki1729** [comment]
@jasw You are right, the syncronized client uses exceptions to communicate failure in sending a message. If you want to register a listener, and have more finely controlled behavior, I would recommend using the `ServiceBusSenderAsyncClient`. 

As for the case where you saw the send fail without throwing exception, it would be really helpful to debug this further if you had the logs (in debug level) for the time period.
