### ISSUE TITLE
Remove hardcoded SDK_NAME and SDK_VERSION from ConfigurationClient

### ISSUE THREAD

**Issue by conniey** [Azure/azure-sdk-for-java#3141]
We should be reading the metadata from the JAR file rather than having constants.

Since this is used in the UserAgentPolicy, it should conform to this standard. https://azuresdkspecs.z5.web.core.windows.net/JavaSpec.html#general-telemetry

**Comment by weshaggard** [comment]
@conniey do you know if this is something that is easy to do and if we would be able to do it for GA?

**Comment by conniey** [comment]
@weshaggard To be honest, I'm not sure of the amount of effort it would take to update to use versions from a resource file (or something else). And modify all the other shipping libraries to use this logic.

@JonathanGiles or @anuchandy Do you have any idea of how much work would be involved?

**Comment by weshaggard** [comment]
FWIW a number of the other languages are also including hard-code version strings in the source code so I don't think it is unrealistic to stick with that approach. We just need to be sure to keep them in sync which @JimSuplizio is working on with the versioning tools.
