### ISSUE TITLE
Determine code style strategy for Java

### ISSUE THREAD

**Issue by kurtzeborn** [Azure/azure-sdk-for-java#3142]
This is an investigation task for determining the strategy we will use for code style enforcement in .Net including whether we'll use linting tools and/or code editor plug-ins to enforce them. The architect for Azure SDK on .Net should be consulted.

Once a plan is made, additional issues should be created for implementation.

Other considerations are listed in our team notebook [here](https://microsoft.sharepoint.com/teams/AzureDeveloperExperience/_layouts/OneNote.aspx?id=%2Fteams%2FAzureDeveloperExperience%2FShared%20Documents%2FLanguage%20-%20Java%2FAzure%20SDK%20-%20Language%20-%20Java&wd=target%28SDKs.one%7C1809F821-9CEB-9245-B57B-A3E75FB83065%2FJava%20SDK%20Engineering%20System%20Tools%7C041CAA3A-7B4D-EA44-880D-41333DCD530B%2F%29).  Suggestions include SpotBugs and CheckStyle

**Comment by kurtzeborn** [comment]
I think we're good on this currently (and the OneNote page linked to above that @JonathanGiles created has been modified/removed).  I'm going to go ahead and close this.  @JonathanGiles, please let me know if there's more goals around Java code style enforcement specifically that you'd like to see the Engineering system support that isn't in place already.

**Comment by JonathanGiles** [comment]
I just want to confirm that this is directed at me - the issue description mentions .NET in a few places and so I wonder if this is intended for over there instead?

For Java we are good - CheckStyle and SpotBugs are working well for us.
