### ISSUE TITLE
[BUG] Service bus message processeor fails to recover: Cannot use a proxy when TransportType is not AMQP

### ISSUE THREAD

**Issue by ialexandrov** [Azure/azure-sdk-for-java#31459]
**Describe the bug**
Service Bus client processor fails to recover after network issue when used in environment with HTTPs proxy.

***Exception or Stack Trace***
```
java.lang.IllegalArgumentException: Cannot use a proxy when TransportType is not AMQP.
	at com.azure.messaging.servicebus.ServiceBusClientBuilder.getConnectionOptions(ServiceBusClientBuilder.java:724)
	at com.azure.messaging.servicebus.ServiceBusClientBuilder.getOrCreateConnectionProcessor(ServiceBusClientBuilder.java:685)
	at com.azure.messaging.servicebus.ServiceBusClientBuilder.access$600(ServiceBusClientBuilder.java:186)
	at com.azure.messaging.servicebus.ServiceBusClientBuilder$ServiceBusReceiverClientBuilder.buildAsyncClient(ServiceBusClientBuilder.java:1927)
	at com.azure.messaging.servicebus.ServiceBusClientBuilder$ServiceBusReceiverClientBuilder.buildAsyncClient(ServiceBusClientBuilder.java:1885)
	at com.azure.messaging.servicebus.ServiceBusProcessorClient.restartMessageReceiver(ServiceBusProcessorClient.java:475)
	at com.azure.messaging.servicebus.ServiceBusProcessorClient.lambda$start$0(ServiceBusProcessorClient.java:232)
```

**To Reproduce**
1. Configure https.proxyHost and https.proxyPort JVM properties. (required to obtain access token from AAD)
2. Start processing service bus messages via AMQP - message processing starts successfully
3. Disable network connection for some time and then re-enable it
4. Message processor permanently fails to re-establish the connection with given stack trace

**Expected behavior**
Message processor successfully re-establish connection to queue

**Setup (please complete the following information):**
 - OS: Windows 10
 - IDE: IntelliJ
 - Library/Libraries: azure-messaging-servicebus 7.10.1
 - Java version: 11 
 - App Server/Environment: JUnit
 - Frameworks: Spring, JUnit,

**Comment by anuchandy** [comment]
Hello, thanks for the question. The messaging libraries support only HTTP Proxy, so you will need to use a transport_type that can init broker connect using HTTP through the HTTP proxy. For this, messaging libraries support we-socket.

We can set explicitly the transport type as `AmqpTransportType.AMQP_WEB_SOCKETS` (to override the default `AmqpTransportType.AMQP`). Here is the reference [doc](https://learn.microsoft.com/en-us/java/api/com.azure.messaging.servicebus.servicebusclientbuilder?view=azure-java-stable#com-azure-messaging-servicebus-servicebusclientbuilder-transporttype(com-azure-core-amqp-amqptransporttype))

**Comment by anuchandy** [comment]
I realized that the message in the error is not correct, updating that in this [pr](https://github.com/Azure/azure-sdk-for-java/pull/31570)

**Comment by anuchandy** [comment]
That said, I'm not sure why the library didn't detect the proxy after step1 but only after step3 (in the same JVM run). I've to try repro.

In your setup/env, it looks like only HTTP calls need to go through the proxy, but a direct amqp connection is whitelisted in the firewall. Is my understanding correct?

**Comment by ialexandrov** [comment]
Yes, with use direct connection for AMQP calls, but all HTTPs communication is through the proxy. Therefore the proxy configuration is set in the environment.
The problem really is that the client starts successfully and only fails upon recovery after network outage.

**Comment by anuchandy** [comment]
If the environment is configured to use Proxy Globally, then the expectation from AMQP library is to use this global proxy configuration, but AMQP also requires the application to opt-in to WebSocket to be able to use the proxy. The library indicates that there is this mismatch. If proxy is configured, then WebSocket should be opted in. Alternatively, the proxy can be limited to AD library (by passing ProxyOptions to AD lib) and disable global proxy.
