### ISSUE TITLE
[BUG] Spring Data Cosmos loses date precision with JDK 17

### ISSUE THREAD

**Issue by saragluna** [Azure/azure-sdk-for-java#31492]
**Describe the bug**
While working on #31417, I found the integration test pipeline failed because of [errors](https://dev.azure.com/azure-sdk/internal/_build/results?buildId=1917316&view=logs&j=caa02ea9-2389-5ab0-dd04-e2bf1c48642e&t=2c713f32-d936-5c8d-942a-fcedc5ff7533&l=9726) like: 

<img width="1260" alt="image" src="https://user-images.githubusercontent.com/31124698/195803632-847f7b63-078d-4cda-9613-bb5a8565780f.png">

This kind of error doesn't show when using JDK 11 ([a pipeline example](https://dev.azure.com/azure-sdk/internal/_build/results?buildId=1917185&view=logs&j=caa02ea9-2389-5ab0-dd04-e2bf1c48642e&t=2c713f32-d936-5c8d-942a-fcedc5ff7533&l=14)), and only happens when enables JDK 17 ([an example](https://dev.azure.com/azure-sdk/internal/_build/results?buildId=1917316&view=logs&j=caa02ea9-2389-5ab0-dd04-e2bf1c48642e&t=2c713f32-d936-5c8d-942a-fcedc5ff7533&l=14)). 

After some investigation, I discovered that [JDK 9 increased the precision to microseconds](https://bugs.openjdk.org/browse/JDK-8068730). And [JDK 15 increased the precision to nanoseconds](https://bugs.openjdk.org/browse/JDK-8242504), if the underlying OS supports it.  

1. The issue is when serializing `OffsetDateTime` on a Linux JDK17, the serialized value of this step https://github.com/Azure/azure-sdk-for-java/blob/00efbbe834feb482511fe430869a622b944db7cf/sdk/cosmos/azure-spring-data-cosmos/src/main/java/com/azure/spring/data/cosmos/core/convert/MappingCosmosConverter.java#L133 would be like the following log because the default behavior of `ObjectMapper` will serialize the `OffsetDateTime` as `BigDecimal`

    ```
    15:31:57.269 [main] ERROR c.a.s.d.c.c.c.MappingCosmosConverter - The writeValueAsString of AuditableEntity is {"id":"7b2706f8-42da-4fa5-9b99-28ad1aacdf03","_etag":null,"createdBy":"created-by","createdDate":1665675117.255168968,"lastModifiedBy":"created-by","lastModifiedByDate":1665675117.255168968} 
    ```

    But the following line will try to deserialize the string, 

    https://github.com/Azure/azure-sdk-for-java/blob/00efbbe834feb482511fe430869a622b944db7cf/sdk/cosmos/azure-spring-data-cosmos/src/main/java/com/azure/spring/data/cosmos/core/convert/MappingCosmosConverter.java#L134

    With `ObjectMapper`'s default behavior, this step will deserialize the `BigDecimal` to a float number, which will lose the precision. 
    ```
    15:31:57.269 [main] ERROR c.a.s.d.c.c.c.MappingCosmosConverter - The readTree value of AuditableEntity is {"id":"7b2706f8-42da-4fa5-9b99-28ad1aacdf03","_etag":null,"createdBy":"created-by","createdDate":1.665675117255169E9,"lastModifiedBy":"created-by","lastModifiedByDate":1.665675117255169E9}
    ```

2. But even if tried to modify the deserializing behavior by forcing using `BigDecimal` for float number, as done in https://github.com/Azure/azure-sdk-for-java/compare/d859ff19ecfcb5ad3216d84a1a26e573a9621476..889e848857e6595b55d8463318f6b8256295e2d7, the precision lost still happen when cosmos SDK stores it. 
    ```
    15:31:57.300 [main] ERROR c.a.s.d.c.c.c.MappingCosmosConverter - The response from the Cosmos server is {
      "id" : "7b2706f8-42da-4fa5-9b99-28ad1aacdf03",
      "_etag" : "\"0e00fadc-0000-0600-0000-63482f6d0000\"",
      "createdBy" : "created-by",
      "createdDate" : 1.665675117255169E9,
      "lastModifiedBy" : "created-by",
      "lastModifiedByDate" : 1.665675117255169E9,
      "_rid" : "6eQVAJdY5CMBAAAAAAAAAA==",
      "_self" : "dbs/6eQVAA==/colls/6eQVAJdY5CM=/docs/6eQVAJdY5CMBAAAAAAAAAA==/",
      "_attachments" : "attachments/",
      "_ts" : 1665675117
    }
    ```

3. My temporary solution is to store the `OffsetDateTime` as a string instead of a timestamp, as shown in https://github.com/Azure/azure-sdk-for-java/compare/889e848857e6595b55d8463318f6b8256295e2d7..9f4a0ac21aa9bd526a886c26c664216bcb2cf5f9. 

**To conclude**, the default `MappingCosmosConverter` loses precision. 

***Exception or Stack Trace***

https://dev.azure.com/azure-sdk/internal/_build/results?buildId=1917316&view=logs&j=caa02ea9-2389-5ab0-dd04-e2bf1c48642e&t=2c713f32-d936-5c8d-942a-fcedc5ff7533&l=269
<img width="1314" alt="image" src="https://user-images.githubusercontent.com/31124698/195811354-611de552-d270-49a8-9d45-924a7ef3d842.png">

**To Reproduce**
Run integration tests for Spring Data Cosmos using JDK 17. 

***Code Snippet***
N/A

**Expected behavior**
No precision was lost. 

**Screenshots**
N/A

**Setup (please complete the following information):**
 - OS: [Linux]
 - IDE: [N/A]
 - Library/Libraries: [spring-data-cosmos]
 - Java version: [17] 
 - App Server/Environment: [N/A]
 - Frameworks: [Spring] 

If you suspect a dependency version mismatch (e.g. you see `NoClassDefFoundError`, `NoSuchMethodError` or similar), please check out [Troubleshoot dependency version conflict article](https://aka.ms/azsdk/java/dependency/troubleshoot) first. If it doesn't provide solution for the problem, please provide:
- verbose dependency tree (`mvn dependency:tree -Dverbose`)
- exception message, full stack trace, and any available logs

**Additional context**

**Information Checklist**
Kindly make sure that you have added all the following information above and checkoff the required fields otherwise we will treat the issuer as an incomplete report
- [x] Bug Description Added
- [x] Repro Steps Added
- [x] Setup information Added

**Comment by saragluna** [comment]
@kushagraThapar, please take a look at this issue.

**Comment by kushagraThapar** [comment]
@saragluna thanks for finding the issue and reporting it, great description and explanation, thanks again!

@trande4884 can you please look at this!

**Comment by trande4884** [comment]
@saragluna so is this issue only happening specifically on a Linux machine? The linked pipelines appear to have sense been deleted but I have been unable to reproduce on my machine while using JDK 17.

**Comment by saragluna** [comment]
> @saragluna so is this issue only happening specifically on a Linux machine? The linked pipelines appear to have sense been deleted but I have been unable to reproduce on my machine while using JDK 17.

Yes, it is only happening on a Linux machine.

**Comment by trande4884** [comment]
@saragluna what version of Ubuntu are you running?

Our live testing pipeline uses JDK 17 and Ubuntu 20.04 and all of the tests are passing, here is a pipeline where you can see them all passing (you can look at "Public_Integration/Session_Integration_117"):
https://dev.azure.com/azure-sdk/internal/_build/results?buildId=1987830&view=results

**Comment by saragluna** [comment]
@trande4884 I guess this is because, in this PR https://github.com/Azure/azure-sdk-for-java/pull/31417, I made some changes to the `sdk/cosmos/azure-spring-data-cosmos-test/src/test/java/com/azure/spring/data/cosmos/repository/AuditableConfig.java`.

**Comment by trande4884** [comment]
@saragluna it looks like you added this as a new file, not a modification is that correct? But if this change fixes the issue then why wouldn't we just leave this implementation?

**Comment by saragluna** [comment]
@trande4884 yes, I added a new file. It's only a workaround to make the tests pass. But if users define a POJO in their application (running in Linux), and this POJO contains a field of type `OffsetDateTime`, then they save this POJO using spring-data-cosmos to the DB, and the precision loss will happen.
