### ISSUE TITLE
[BUG] ShareFileRange 'end' field not handled correctly when used with InputStream

### ISSUE THREAD

**Issue by croudet** [Azure/azure-sdk-for-java#31524]
**Describe the bug**
When using ```ShareFileRange``` with ```openInputStream``` method I expect the ```end``` field to be the end of the range:
```java
ShareFileRange shareFileRangeBug = new ShareFileRange(5L, 10L);
byte[] bytes = shareFileClientBug.openInputStream(shareFileRangeBug).readAllBytes();
```
I expect to have 6 bytes, from offset 5 (```start```) to offset 10 (```end```), but I got 10 bytes. So ```end``` is there the count of bytes.

Note I got the correct result with ```ShareFileClient.downloadWithResponse```.

**To Reproduce**
Fetch a ```ShareFileRange``` of a file with ```ShareFileClient.openInputStream``` method.

***Code Snippet***
```java
final ShareFileClient shareFileClientBug = recordingsDirectoryClient.getFileClient("< a file>");
        final ShareFileRange shareFileRangeBug = new ShareFileRange(5L, 10L);
        try {
            ByteArrayOutputStream out = new ByteArrayOutputStream();
            shareFileClientBug.downloadWithResponse(out, new ShareFileDownloadOptions().setRange(shareFileRangeBug), Duration.ofDays(1L), null).getValue();
            System.out.println(out.toByteArray().length);
            byte[] bytes = shareFileClientBug.openInputStream(shareFileRangeBug).readAllBytes();
            System.out.println(bytes.length);
        } catch (IOException e) {
            throw new RuntimeException(e);
        }
```
Output:
```
6
10
```
**Expected behavior**
I expect ```end``` to be an offset

**Setup (please complete the following information):**
 - OS: Windows 10
 - IDE: IntelliJ
 - Library/Libraries: 'com.azure:azure-storage-file-share:12.16.0'
 - Java version :17
 - Frameworks: Spring Boot 

**Information Checklist**
Kindly make sure that you have added all the following information above and checkoff the required fields otherwise we will treat the issuer as an incomplete report
- [x] Bug Description Added
- [x] Repro Steps Added
- [x] Setup information Added

**Comment by ibrahimrabab** [comment]
Hi @croudet 
Thanks for bringing attention to this issue! We'll be putting out a fix for this fairly soon :)
