### ISSUE TITLE
[BUG] AadClientRegistrationRepository#toClientRegistration did not set userInfoUri

### ISSUE THREAD

**Issue by chenrujun** [Azure/azure-sdk-for-java#31546]
### Context

In current [AadClientRegistrationRepository#toClientRegistration ](https://github.com/Azure/azure-sdk-for-java/blob/spring-cloud-azure_4.4.0/sdk/spring/spring-cloud-azure-autoconfigure/src/main/java/com/azure/spring/cloud/autoconfigure/aad/AadClientRegistrationRepository.java#L165-L178) , `userInfoUri` is not set, which caused **OidcUserService#shouldRetrieveUserInfo** always returns false. 

### Problem
**OidcUserService#shouldRetrieveUserInfo** always returns false, it is unexpected behavior.

### Goal

1. Make **userInfoUri** configured and use it to get user information.
2. Confirm proxy setting will work when send http request to **userInfoUri**. **DefaultOAuth2UserService's RestTemplate**. Refs: https://github.com/Azure/azure-sdk-for-java/issues/31347#issuecomment-1282055670

### Useful links

https://learn.microsoft.com/en-us/azure/active-directory/develop/userinfo

**Comment by chenrujun** [comment]
In [spring-boot-autoconfigure](https://github.com/spring-projects/spring-boot/blob/v2.7.4/spring-boot-project/spring-boot-autoconfigure/src/main/java/org/springframework/boot/autoconfigure/security/oauth2/client/OAuth2ClientPropertiesRegistrationAdapter.java#L82), userInfoUri will be got from **issuerUri**

![image](https://user-images.githubusercontent.com/13167207/196393718-78d72539-20ae-4a2d-9399-42ca36e45ced.png)

**Comment by chenrujun** [comment]
Screenshot of quick fix:

![image](https://user-images.githubusercontent.com/13167207/196840296-beb2b707-37e4-4786-843d-250559bba7a7.png)

Need add more unit tests.

**Comment by backwind1233** [comment]
The userInfoUri is used to get OidcUserInfo, and then it will be used to construct OidcUser .

As the java doc of OidcUser says:
```
An OidcUser contains "claims" about the authentication of the End-User.  
The claims are aggregated from the OidcIdToken and the OidcUserInfo (if available).

```

So whether to set userInfoUri, it depends, we need to check whether there are different "claims" in OidcUserInfo rather than in the OidcIdToken, and then make a decision whether to set the value by default, or provide an option to user.

Also, our AadOAuth2UserService#loadUser doesn't use the oidcUser returned by OidcUserService#loadUser.

**Comment by backwind1233** [comment]
We need to make a design(decision) what is expected return in [AadOAuth2UserService#loadUser ](https://github.com/Azure/azure-sdk-for-java/blob/9feff2d9c0dd2815ee99eccfbf00ec4ffade730d/sdk/spring/spring-cloud-azure-autoconfigure/src/main/java/com/azure/spring/cloud/autoconfigure/aad/implementation/webapp/AadOAuth2UserService.java#L111).

**Comment by backwind1233** [comment]
![Image](https://user-images.githubusercontent.com/4465723/206605751-0647e0f4-a59c-45b6-8887-49ee89cc4c17.png)


The [javadoc](https://github.com/Azure/azure-sdk-for-java/blob/9feff2d9c0dd2815ee99eccfbf00ec4ffade730d/sdk/spring/spring-cloud-azure-autoconfigure/src/main/java/com/azure/spring/cloud/autoconfigure/aad/implementation/webapp/AadOAuth2UserService.java#L102) does not match the [implementation](https://github.com/Azure/azure-sdk-for-java/blob/9feff2d9c0dd2815ee99eccfbf00ec4ffade730d/sdk/spring/spring-cloud-azure-autoconfigure/src/main/java/com/azure/spring/cloud/autoconfigure/aad/implementation/webapp/AadOAuth2UserService.java#L111).


1.  No UserInfo Endpoint was set.
2. It does not use the userInfo to build the [result](https://github.com/Azure/azure-sdk-for-java/blob/9feff2d9c0dd2815ee99eccfbf00ec4ffade730d/sdk/spring/spring-cloud-azure-autoconfigure/src/main/java/com/azure/spring/cloud/autoconfigure/aad/implementation/webapp/AadOAuth2UserService.java#L144).

**Comment by backwind1233** [comment]
- The userInfoUri in the [AadClientRegistrationRepository#toClientRegistration ](https://github.com/Azure/azure-sdk-for-java/blob/spring-cloud-azure_4.4.0/sdk/spring/spring-cloud-azure-autoconfigure/src/main/java/com/azure/spring/cloud/autoconfigure/aad/AadClientRegistrationRepository.java?rgh-link-date=2022-10-18T09%3A03%3A53Z#L165-L178) class, which means for applications using our aad starter, when the applications' users login and call AadOAuth2UserService#[loadUser](https://github.com/Azure/azure-sdk-for-java/blob/6eda82e741564aeaae65dfe665798199a3c87a37/sdk/spring/spring-cloud-azure-autoconfigure/src/main/java/com/azure/spring/cloud/autoconfigure/aad/implementation/webapp/AadOAuth2UserService.java#L111-L111)() to load OidcUser, the method call will never obtain the user attributes of the end-user from the UserInfo Endpoint. This means that our Java doc is not correct.
    ![image](https://user-images.githubusercontent.com/4465723/206941106-d887978f-819c-4dcf-b8cc-0a4ee04aefae.png)

- Also in our implementation of the [loadUser](https://github.com/Azure/azure-sdk-for-java/blob/cf9a0d4043d113a777da2c62383d3b5e9d18f882/sdk/spring/spring-cloud-azure-autoconfigure/src/main/java/com/azure/spring/cloud/autoconfigure/aad/implementation/webapp/AadOAuth2UserService.java#L111-L111) method, we actually did not use the userInfo to construct the return information. 

    We build and return a DefaultOidcUser instance by using the below DefaultOidcUser constructor, which will always takes a null value for userInfo .
    ![image](https://user-images.githubusercontent.com/4465723/206941180-76bd2640-6fe3-4d66-8c4e-321a1ab9e702.png)

    This means no matter whether the userInfoUri is set or not, we will never use or return the userInfo. 

    This logic has not changed since the first [commit](https://github.com/microsoft/azure-spring-boot/blob/35228e2cb44b660e16ecfe22779f00ee68a0b61d/azure-spring-boot/src/main/java/com/microsoft/azure/spring/autoconfigure/aad/AADOAuth2UserService.java#L76).



I think we have two options:

1. Keep the logic. 
    - Since we are using the constructor for DefaultOidcUser that does not take userInfo explicitly, and no users have raised an issue, we can keep things as they are, but we need to refactor our code and modify our javadoc to reflect our current logic.  
2. Provide an implementation of the [loadUser](https://github.com/Azure/azure-sdk-for-java/blob/cf9a0d4043d113a777da2c62383d3b5e9d18f882/sdk/spring/spring-cloud-azure-autoconfigure/src/main/java/com/azure/spring/cloud/autoconfigure/aad/implementation/webapp/AadOAuth2UserService.java#L111-L111) method that returns a DefaultOidcUser instance containing userInfo.

I prefer to the second option. 

- From the javadoc of the interface, we can infer that it is expected to obtain the UserInfo from the UserInfo Endpoint and return it.
    - ![image](https://user-images.githubusercontent.com/4465723/206941333-b49063ee-3d84-4374-8a51-a50ce467b9f1.png)

- The Spring official documentation also provides a [sample](https://docs.spring.io/spring-security/reference/servlet/oauth2/login/core.html#oauth2login-completely-override-autoconfiguration) implementation that includes setting the userInfoUri, by default it will return userInfo.
    - ![image](https://user-images.githubusercontent.com/4465723/206941357-b2e23750-1bba-4608-84a6-4c980848d376.png)

What do you think @saragluna ?

**Comment by saragluna** [comment]
IMO, we should figure out the following questions before making a decision:

- What's the API (input/output) of a `OAuth2UserService#loadUser` method
- What's the difference between the API and our current implementation
- What's the difference between the responses from the user info endpoint and what we call from the graph endpoint (our current implementation)?

**Comment by backwind1233** [comment]
<img width="794" alt="image" src="https://user-images.githubusercontent.com/4465723/207022168-ff66252a-5f3c-4c75-a6b0-3cd2e020d07b.png">

**Comment by backwind1233** [comment]
<img width="1500" alt="image" src="https://user-images.githubusercontent.com/4465723/207024232-addfa573-7e38-427c-a1c5-debc50ac5d57.png">

**Comment by backwind1233** [comment]
<img width="1474" alt="image" src="https://user-images.githubusercontent.com/4465723/207026402-bf342ee8-e6d4-4aca-88f6-997c023e2ce1.png">

**Comment by backwind1233** [comment]
<img width="1307" alt="image" src="https://user-images.githubusercontent.com/4465723/207086208-ce422bfc-5fc1-4452-b673-ebb1bb4308c0.png">
