### ISSUE TITLE
[FEATURE REQ] Support multi-tenancy at database level in Cosmos Spring library

### ISSUE THREAD

**Issue by TheovanKraay** [Azure/azure-sdk-for-java#31577]
**Is your feature request related to a problem? Please describe.**
Cosmos DB Spring library does not currently allow dynamic setting of database name, and must be hardcoded in config, to be used at initialisation.

**Describe the solution you'd like**
Ability to specify database name dynamically, similar to support for MongoDB in samples like this: https://github.com/tinmegali/spring-multi-tenant/blob/master/src/main/java/com/tinmegali/springdatamongodbmultitenant/config/data/MultiTenantMongoDbFactory.java

**Describe alternatives you've considered**
The only alternative is to use CosmosTemplate, which is verbose, and does not then allow for the use of Spring native Respository API. 

**Information Checklist**
Kindly make sure that you have added all the following information above and checkoff the required fields otherwise we will treat the issuer as an incomplete report
- [x] Description Added
- [X] Expected solution specified

**Comment by trande4884** [comment]
All of the below is to make sure that customers can use spring data cosmos SDK as it is without needing to change template level code.

They should be able to use JPA repositories and use the SDK normally, with minimal changes through application.properties or through extending CosmosFactory.

1. Multi-Tenancy on Cosmos Db Account level - We dont support this. (We do support it but through multiple templates. - which requires customers to use templates and not repositories)

    Database cost is zero - because throughput can be provisioned at just container level - confirm with Theo ??

    Each tenant is a separate database ->
    WMT -> User, Role, Address (Same containers because of same entity OR reusable entities - allows customer to just have 1 code for their multi-tenant application)
    linkedIn -> User, Role, Address
    BestBuy -> User, Role, Address

    ComsosFactory -> 1:1 mapped to a database.
    MultiTenantCosmosFactory -> 1:N mapping to databases.
    This can be done by updating our templates to take in getDatabaseName() dynamically.

2. Multi-Tenancy on Database level -> (We might already support this) - We do support this. But this is not practical or realistic.

    There is only 1 database. (This is something that MARS company is using -> They have around 80-120 containers - each container for a tenant)

    Each tenant as a separate container -> ??
    WMT entity - for WMT tenant -> WMT is the container here.
    BestBuy entity - for BestBuy tenant -> BestBuy is the container here.
    ...

    Each entity holds storage of json type (no structure) and customers use same container for holding multiple document types.
    Because currently we have entity linked to Container Name, this is already hooked up in our templates.
    With caveat, that one entity is mapped to a single and only single container.

3. Multi-Tenancy on Container level -> (Same entity types for each tenant, but seggregation is on container) - This we already support - might need testing.

    There is only 1 database. (This is something that MARS company is using -> They have around 80-120 containers - each container for a tenant)

    Each tenant has multiple entities as multiple containers.
    WMT -> User, Role and Address -> Manifested as WMT-User, WMT-Role, WMT-Address containers.
    BestBuy -> User, Role and Address -> Manifested as BestBuy-User, BestBuy-Role, BestBuy-Address containers.
    ...

    Map a single Entity to multiple containers. ??? (We don't support this) - Also, I don't think spring-data supports this.
    We do support - dynamic naming of containers through entity - using SpEL - spring expression language.
    In this case, customer hosts multiple applications (per tenant) and specificy container names through SpEL.
    Each application is dedicated to a tenant. For example, WMT application will only have WMT tenant data and traffic. Same for BestBuy, LinkedIn, etc.
    All they need to do is use SPeL for dynamic container name per tenant based, and leverage the same code.
    Deploy same application code, but with different application.properties

4. Multi-Tenancy on Data level -> (1 database, multiple containers, tenancy based on pk) - This we already support - might need testing. Might not even need testing.

This is already supported regardless.

    There is only 1 database.
    Each container is an entity - Role, Address, User, etc.
    Each container has a partition key - based on tenant.
    Role -> String type partition key (tenantPk) - values can be -> WMT, BestBuy, LinkedIn.

**Comment by kushagraThapar** [comment]
https://github.com/kushagraThapar/azure-sdk-for-java/pull/new/spring-data-cosmos-multi-tenancy-container-level
