### ISSUE TITLE
IoT Device Update Readme issue

### ISSUE THREAD

**Issue by hongli750210** [Azure/azure-sdk-for-java#31589]
1.
**Section** [link](https://github.com/Azure/azure-sdk-for-java/tree/main/sdk/deviceupdate/azure-iot-deviceupdate#azure-device-update-for-iot-hub-client-library-for-java) :
![image](https://user-images.githubusercontent.com/74638143/196630007-7f55a097-dca0-4d37-abe2-edd11ac55e59.png)

**Suggestion**: 
The pointing of this link is wrong. 
Change link to `https://github.com/Azure/azure-sdk-for-java/tree/main/sdk/deviceupdate/azure-iot-deviceupdate/src`

@joshfree, @drwill-ms and @dpokluda for notification.

**Comment by weidongxu-microsoft** [comment]
@dpokluda Hi David, would you check the readme link to source? https://github.com/Azure/azure-sdk-for-java/blob/main/sdk/deviceupdate/azure-iot-deviceupdate/README.md

**Comment by drwill-ms** [comment]
I'm not an owner of this code. Perhaps @dpokluda per this [codeowners](https://github.com/Azure/azure-sdk-for-java/blob/main/.github/CODEOWNERS#L99) entry?
