### ISSUE TITLE
Key Vault - Keys Samples issue

### ISSUE THREAD

**Issue by hongli750210** [Azure/azure-sdk-for-java#31588]
1.
**Section** [link1](https://github.com/Azure/azure-sdk-for-java/blob/main/sdk/keyvault/azure-security-keyvault-keys/src/samples/java/com/azure/security/keyvault/keys/KeyClientJavaDocCodeSnippets.java#L97), [link2](https://github.com/Azure/azure-sdk-for-java/blob/main/sdk/keyvault/azure-security-keyvault-keys/src/samples/java/com/azure/security/keyvault/keys/KeyClientJavaDocCodeSnippets.java#L203) :
![image](https://user-images.githubusercontent.com/74638143/196836983-927b44f0-4e36-412e-88c8-b162cd780c75.png)

**Reason:**
com.azure.core.exception.ResourceModifiedException: Status code 400, "{"error":{"code":"BadParameter","message":"Invalid kty value: oct","innererror":{"code":"KeyTypeNotSupported"}}}"

**Suggestion:** 
 Delete the relevant code.

@joshfree, @heaths, @pallavit and @vcolin7 for notification.

**Comment by heaths** [comment]
"oct" and "oct-HSM" is valid for Managed HSM, which is accessible using the `KeyClient`. If you try to use it for Key Vault, 400 BadRequest is expected. Please see https://learn.microsoft.com/azure/key-vault/managed-hsm/overview for more information about Managed HSM.
