### ISSUE TITLE
[BUG] AzureIdentityMysqlAuthenticationPlugin doesn't work with MysqlConnectionPoolDataSource

### ISSUE THREAD

**Issue by saragluna** [Azure/azure-sdk-for-java#31599]
**Describe the bug**
When running the `AzureIdentityMysqlAuthenticationPlugin` with `MysqlConnectionPoolDataSource`, there will be an exception says `java.sql.SQLException: Access denied for user 'user@company.com@'170.170.170.170' (using password: NO)`

***Exception or Stack Trace***
```console
java.sql.SQLException: Access denied for user 'user@company.com@'170.170.170.170' (using password: NO)

	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:129)
	at com.mysql.cj.jdbc.exceptions.SQLExceptionsMapping.translateException(SQLExceptionsMapping.java:122)
	at com.mysql.cj.jdbc.ConnectionImpl.changeUser(ConnectionImpl.java:564)
	at com.mysql.cj.jdbc.ConnectionImpl.resetServerState(ConnectionImpl.java:1791)
	at com.mysql.cj.jdbc.MysqlPooledConnection.getConnection(MysqlPooledConnection.java:129)
	at com.mysql.cj.jdbc.MysqlPooledConnection.getConnection(MysqlPooledConnection.java:109)
```

**To Reproduce**
Add the `azure-identity-provider-jdbc-mysql` and run the following code. 

```
<dependency>
  <groupId>com.azure</groupId>
  <artifactId>azure-identity-providers-jdbc-mysql</artifactId>
  <version>1.0.0-beta.1</version>
</dependency>
```

***Code Snippet***
```java
@Test
public void getServerTimeUmi() throws SQLException {
    MysqlConnectionPoolDataSource ds = new MysqlConnectionPoolDataSource();
    ds.setUrl(
        "jdbc:mysql://xxxx.mysql.database.azure.com/checklist?" +
            "useSSL=true&requireSSL=true" +
            "&defaultAuthenticationPlugin=com.azure.identity.providers.mysql.AzureIdentityMysqlAuthenticationPlugin" +
            "&authenticationPlugins=com.azure.identity.providers.mysql.AzureIdentityMysqlAuthenticationPlugin"
    );
    ds.setUser("user@company.com");
    ds.setConnectTimeout(60000);

    PooledConnection connectionPooled = ds.getPooledConnection();
    if (connectionPooled != null) {
        Connection connection = connectionPooled.getConnection();
        if (connection != null) {
            System.out.println("Successfully connected.");
            System.out.println(connection.isValid(10));
            ResultSet result = connection.prepareStatement("SELECT now() as now").executeQuery();
            if (result.next()) {
                assertNotNull(result.getString("now"));
            }

        }
    }
}
```

**Expected behavior**
No exception. 

**Screenshots**
N/A

**Setup (please complete the following information):**
 - OS: [MacOS]
 - IDE: [IntelliJ]
 - Library/Libraries: [azure-identity-provider-jdbc-mysql]
 - Java version: [8] 
 - App Server/Environment: [e.g. Tomcat, WildFly, Azure Function, Apache Spark, Databricks, IDE plugin or anything special]
 - Frameworks: [e.g. Spring Boot, Micronaut, Quarkus, etc] 

If you suspect a dependency version mismatch (e.g. you see `NoClassDefFoundError`, `NoSuchMethodError` or similar), please check out [Troubleshoot dependency version conflict article](https://aka.ms/azsdk/java/dependency/troubleshoot) first. If it doesn't provide solution for the problem, please provide:
- verbose dependency tree (`mvn dependency:tree -Dverbose`)
- exception message, full stack trace, and any available logs

**Additional context**

**Information Checklist**
Kindly make sure that you have added all the following information above and checkoff the required fields otherwise we will treat the issuer as an incomplete report
- [x] Bug Description Added
- [x] Repro Steps Added
- [x] Setup information Added

**Comment by saragluna** [comment]
Per the stack trace, the error happens in this method: 
```java
@Override
public void resetServerState() throws SQLException {
    if (!this.propertySet.getBooleanProperty(PropertyKey.paranoid).getValue() && (this.session != null)) {
        changeUser(this.user, this.password);
    }
}
```

So I add `paranoid=true` to the jdbc URL and it can work, so the problem is in the changeUser method.

**Comment by saragluna** [comment]
After debugging, the code throw exception at this step 

https://github.com/mysql/mysql-connector-j/blob/27603148f10a5f47467bec7ad26a5ca28da63c72/src/main/protocol-impl/java/com/mysql/cj/protocol/a/NativeAuthenticationProvider.java#L679-L685

**Comment by backwind1233** [comment]
A workaround to address this issue is: you can try to remove the defaultAuthenticationPlugin configuration when using MysqlConnectionPoolDataSource.

```
String url = "jdbc:mysql://{your-database-aacount}.mysql.database.azure.com:3306/{your-db}?sslMode=REQUIRED&serverTimezone=UTC" 
  +  "&authenticationPlugins=com.azure.identity.providers.mysql.AzureIdentityMysqlAuthenticationPlugin";
```

**Comment by saragluna** [comment]
Check this link for more details about the MySQL connection lifecycle: https://dev.mysql.com/doc/dev/mysql-server/latest/page_protocol_connection_lifecycle.html.

**Comment by backwind1233** [comment]
Follow-up:
- [ ] Add an issue in jdbc-driver repo.

**Comment by stliu** [comment]
doc this workaround in the lib doc

**Comment by backwind1233** [comment]
Docs PR about this workaround:
https://github.com/MicrosoftDocs/azure-docs-pr/pull/220693
https://github.com/MicrosoftDocs/azure-dev-docs-pr/pull/3917

**Comment by stliu** [comment]
I think we don't have anything left to do for this bug?

**Comment by backwind1233** [comment]
Yes, waiting for this PR https://github.com/MicrosoftDocs/azure-docs-pr/pull/220693 to be merged.

**Comment by backwind1233** [comment]
> Yes, waiting for this PR [MicrosoftDocs/azure-docs-pr#220693](https://github.com/MicrosoftDocs/azure-docs-pr/pull/220693) to be merged.

Closing this issue, the PR https://github.com/MicrosoftDocs/azure-docs-pr/pull/220693 has been approved.
