### ISSUE TITLE
[FEATURE REQ] Add container upload support to azure-containers-containerregistry

### ISSUE THREAD

**Issue by The-Funk** [Azure/azure-sdk-for-java#31598]
Problem:
I thought I could programmatically push new docker images in Java to ACR.

Solution:
MS Devs add ability to programmatically push new docker image to ACR in Java.

Considered Alternatives:
Manually pushing all of my microservices when I do an environment promotion (everything from Dev moves to Test, including many microservices)
I write a cheap hack to use the command line and az login.

**Additional context**
<artifactId>azure-containers-containerregistry</artifactId> exists already, the ability to upload a new container could be integrated into this package.

**Comment by The-Funk** [comment]
An alternative would be to allow the az cli to do an unattended login via command line when provided credentials. It's easy enough to run powershell or bash scripts from an application and then call docker push. If client-secret credentials (unattended credentials that don't require human interaction) could be exported in a form that the az login command accepts, then the flow could complete outside of the Java program as part of a powershell or bash script and the benefit of the docker push (only pushes changed layers) could be kept.

**Comment by joshfree** [comment]
@lmolkova could you follow up with @The-Funk on this github issue?

**Comment by lmolkova** [comment]
@The-Funk thank you for reporting this!

we're working on some improvements in this area, but you should already be able to do it with [1.1.0-beta.1](https://search.maven.org/artifact/com.azure/azure-containers-containerregistry/1.1.0-beta.1/jar) package - it supports uploading and downloading images and layers. We're going to GA this feature in the next few months. 

Could you please take a look and share the feedback?

**Comment by lmolkova** [comment]
We didn't do a great job documenting full solution yet, here are a few samples you can use to get it going

## Upload 

```java
        String repo = "hello-world";
        String tag = "v42";

        DefaultAzureCredential credential = new DefaultAzureCredentialBuilder().build();
        ContainerRegistryBlobClient blobClient = new ContainerRegistryBlobClientBuilder()
                .endpoint("https://<acr>.azurecr.io")
                .repository(repo)
                .credential(credential)
                .buildClient();

        BinaryData content = BinaryData.fromBytes(new byte[]{1, 2, 3});
        BinaryData configContent = BinaryData.fromString("{}");

        UploadBlobResult contentUploadResult = blobClient.uploadBlob(content);
        UploadBlobResult configUploadResult = blobClient.uploadBlob(configContent);

        OciBlobDescriptor configDescriptor = new OciBlobDescriptor()
                .setMediaType("application/vnd.unknown.config.v1+json")
                .setDigest(configUploadResult.getDigest())
                .setSize(configContent.getLength());

        OciManifest manifest = new OciManifest()
                .setConfig(configDescriptor)
                .setSchemaVersion(2)
                .setLayers(Collections.singletonList(
                        new OciBlobDescriptor()
                            .setDigest(contentUploadResult.getDigest())
                            .setSize(content.getLength())
                            .setMediaType("application/vnd.oci.image.layer.v1.tar")));

        blobClient.uploadManifest(new UploadManifestOptions(manifest)
                .setTag(tag));
```

## Download 

```java
        DefaultAzureCredential credential = new DefaultAzureCredentialBuilder().build();
        String digest = "sha256:afa5372e1de5f426007d148ecb58605125065cdca2f6ef9308af0ff5c43685aa";
        String outDir = "./tmp";

        ContainerRegistryBlobClient blobClient = new ContainerRegistryBlobClientBuilder()
                .endpoint("https://<acr>.azurecr.io")
                .repository(repo)
                .credential(credential)
                .buildClient();

        Files.createDirectories(Paths.get(outDir));

        DownloadManifestResult manifestDownloadResult = blobClient
                .downloadManifest(DownloadManifestOptions.fromTag(digest));

        OciManifest manifest = manifestDownloadResult.getManifest();

        DownloadBlobResult config = blobClient.downloadBlob(manifest.getConfig().getDigest());
        writeFile(config.getContent().toBytes(), outDir + "/config" + config.getDigest().replace(":", "_"));

        for(OciBlobDescriptor layer : manifest.getLayers()) {
            DownloadBlobResult blob = blobClient.downloadBlob(layer.getDigest());

            writeFile(blob.getContent().toBytes(), outDir + "/" + layer.getDigest().replace(":", "_"));
        }

    private static void writeFile(byte[] content, String name) {
        try (FileOutputStream out = new FileOutputStream(name)) {
            out.write(content);
        } catch (Exception e) {
            throw new RuntimeException(e);
        }
    }
```

**Comment by The-Funk** [comment]
@lmolkova sorry I never responded sooner to this! I am testing this out now. Appreciate it! 👍

**Comment by The-Funk** [comment]
Hey @lmolkova I was wondering if I could ask a bit about the upload process with the container registry async client.

It seems I need to upload both the blob and a manifest for each image? docker push is a bit of an enigma to me, I don't really know how it works under the hood, only that I build images, and it pushes them to ACR in layers.

I'm attempting to do this by following the sample code [here, starting at line 31 and ending at 69.](https://github.com/Azure/azure-sdk-for-java/blob/azure-containers-containerregistry_1.1.1/sdk/containerregistry/azure-containers-containerregistry/src/samples/java/com/azure/containers/containerregistry/UploadImageAsync.java)

What to use to generate the binary data is what trips me up.

Since I am using docker desktop, there's no way to directly access my built images directly from Java  (unless I edit the docker in the WSL image to expose it over a port or something so I can use the docker client API, not worth it IMO).

So what I'm doing is calling: `docker save myimage -o myimage.tar.gz`

From there I read in my file and do `BinaryData.fromFile(myimageFile)`

From there I upload the binary data with uploadBlob and this seems to work. When the async function completes, the subscription prints the size of the data in bytes and the SHA digest. However in the Azure Portal the image does not appear in my container registries.

My assumption is, I didn't upload a manifest or something necessary to tell ACR to look for a file with digest X and size Y and tag Z, etc.

Here's my whole code, you'll have to forgive me, I like the Mutiny API, so I wrapped the Flux//Mono returning pieces with that.

```
    public Uni<SetManifestResult> uploadImageToACR() {

        var binData = BinaryData.fromFile(
                Paths.get(registry.getAcrTag() + DOCKER_IMG_GZ_SUFFIX), ACR_UPLOAD_CHUNK_SIZE);

        Flow.Publisher<UploadRegistryBlobResult> monoAsPublisher =
                AdaptersToFlow.publisher(contentClient.uploadBlob(binData));

        return Uni.createFrom()
                .publisher(monoAsPublisher)
                .map(blobResult -> new OciDescriptor()
                        .setMediaType("application/vnd.unknown.config.v1+json")
                        .setDigest(blobResult.getDigest())
                        .setSizeInBytes(blobResult.getSizeInBytes()))
                .map(ociDescriptor -> new OciImageManifest()
                        .setConfiguration(ociDescriptor)
                        .setSchemaVersion(2)
                        .setLayers(Collections.singletonList(
                                new OciDescriptor()
                                        .setDigest(ociDescriptor.getDigest())
                                        .setSizeInBytes(ociDescriptor.getSizeInBytes())
                                        .setMediaType("application/vnd.oci.image.layer.v1.tar"))))
                .chain(ociImageManifest ->
                        Uni.createFrom()
                                .publisher(AdaptersToFlow.publisher(contentClient.setManifest(ociImageManifest, microservice.getServiceVersion()))));
    }
```

**Comment by lmolkova** [comment]
@The-Funk 
I don't see anything obviously wrong with your code.

If I rewrite it to 
```java
  BinaryData configContent = BinaryData.fromString("{}");

  return contentClient.uploadBlob(configContent)
          .flatMap(configUpload ->  {
              var configDescriptor = new OciDescriptor()
                      .setMediaType("application/vnd.unknown.config.v1+json")
                      .setDigest(configUpload.getDigest())
                      .setSizeInBytes(configUpload.getSizeInBytes());

              var layerDescriptor = new OciDescriptor()
                      .setDigest(configUpload.getDigest())
                      .setSizeInBytes(configUpload.getSizeInBytes())
                      .setMediaType("application/vnd.oci.image.layer.v1.tar");

              var manifest = new OciImageManifest()
                      .setConfiguration(configDescriptor)
                      .setSchemaVersion(2)
                      .setLayers(Collections.singletonList(layerDescriptor));

              return contentClient.setManifest(manifest, "foo" + Instant.now().toEpochMilli());
          });
```

It works just fine for me.

There are a couple of suspicions I have:
- the repository does not exist
- the image tag contains unsupported characters (["The tag must be valid ASCII and can contain lowercase and uppercase letters, digits, underscores, periods, and hyphens. It cannot start with a period or hyphen and must be no longer than 128 characters."](https://docs.docker.com/engine/reference/commandline/tag/#description))

Please consider creating an issue, sharing the exact error code and providing SDK logs (or traces) - you can find the details on how to enable them in the [troubleshooting guide](https://github.com/Azure/azure-sdk-for-java/blob/main/sdk/containerregistry/azure-containers-containerregistry/TROUBLESHOOTING.md)
