### ISSUE TITLE
sdk/aot/azure-aot-graalvm-support - cspell found spelling errors in package

### ISSUE THREAD

**Issue by jairmyree** [Azure/azure-sdk-for-java#31607]
Spell check scanning of package at `sdk/aot/azure-aot-graalvm-support` detected spelling errors in the public API surface. This directory is opted out of PR spell checking in PR #31526 to keep PRs unblocked.

## What to do

1. Ensure Node.js is installed (https://nodejs.org/en/download/).
1. Delete the entry in `.vscode/cspell.json`'s `ignorePaths` field. It will look like: `sdk/aot/azure-aot-graalvm-support/**`. You need to do this to enable checking the files.
1. From the root of the repo run spell check using `./eng/common/spelling/Invoke-Cspell.ps1 -ScanGlobs "sdk/aot/azure-aot-graalvm-support/**"`
1. Fix detections according to http://aka.ms/azsdk/engsys/spellcheck use the "False positives" section to fix false positives
1. Check in changes (including the change to `.vscode/cspell.json` where the `ignorePaths` is updated to remove the entry for this service.). You may need to run `git add -f .vscode/cspell.json` to force adding the changes to the file in git.

## Spell checking output

```
./sdk/aot/azure-aot-graalvm-support/README.md:110:10 - Unknown word (Pnative)
```

**Comment by JonathanGiles** [comment]
@jairmyree can you please add `Pnative` to the allow list? It is actually a runtime flag inside a code section, `-Pnative`, and should ideally be ignored.
