### ISSUE TITLE
[BUG] Connection String support of Event Hubs for Kafka cannot work with spring.main.sources configuration in SCS

### ISSUE THREAD

**Issue by yiliuTo** [Azure/azure-sdk-for-java#31664]
**Describe the bug**
Using `com.azure.spring:spring-cloud-azure-starter` to connect Event Hubs for Kafka via connection string with SCS Kafka binder, when configuring `spring.cloud.stream.binders.<kafka-binder-name>.environment.spring.main.sources` with any values, the connection cannot be established.

The cause is that: to support using connection string with EH for Kafka, we use `AzureEventHubsKafkaAutoConfiguration` to modify `KafkaProperties` with the necessary values for connection. Then by default, Kafka binder will regard the application context as its parent and inherit `KafkaProperties` bean to pick up those configurations for binder connection. However, when there is the configuration of `spring.main.sources` for a binder, it will not set the application context as the parent or inherit the necessary beans, which causes our configured connection configuration for EH for Kafka get lost.

***Exception or Stack Trace***
```log
2022-10-21 16:04:55.461  INFO 28104 --- [| adminclient-1] org.apache.kafka.clients.NetworkClient   : [AdminClient clientId=adminclient-1] Node -1 disconnected.
2022-10-21 16:04:55.461  WARN 28104 --- [| adminclient-1] org.apache.kafka.clients.NetworkClient   : [AdminClient clientId=adminclient-1] Connection to node -1 (localhost/127.0.0.1:9092) could not be established. Broker may not be available.
```

**To Reproduce**
Using the [sample](https://github.com/Azure-Samples/azure-spring-boot-samples/tree/spring-cloud-azure_4.3.0/eventhubs/spring-cloud-azure-starter/spring-cloud-azure-sample-eventhubs-kafka) and add a configuration of `spring.cloud.stream.binders.kafka.environment.spring.main.sources` with any configuration class. Startup the application and get see the application keep printing the above logs.

***Code Snippet***
[Related code snippet that causes the issue.](https://github.com/spring-cloud/spring-cloud-stream/blob/98c22b5ff6843d6b367470a73e572c598398c5c1/core/spring-cloud-stream/src/main/java/org/springframework/cloud/stream/binder/DefaultBinderFactory.java#L414)

**Expected behavior**
Connection should be established with the aforementioned configuration.

**Setup (please complete the following information):**
 - Library/Libraries: com.azure.spring:spring-cloud-azure-starter
 - Frameworks: Spring Cloud Stream

**Information Checklist**
Kindly make sure that you have added all the following information above and checkoff the required fields otherwise we will treat the issuer as an incomplete report
- [x] Bug Description Added
- [x] Repro Steps Added
- [x] Setup information Added

**Comment by kswat** [comment]
I am getting the same issue. Scenario: trying to send messages to event hub using kafka , spring cloud stream

**Comment by kswat** [comment]
Fix: add this to properties
sources: com.azure.spring.cloud.autoconfigure.implementation.eventhubs.kafka.AzureEventHubsKafkaAutoConfiguration
from https://github.com/Azure-Samples/azure-spring-boot-samples/blob/main/eventhubs/spring-cloud-azure-starter/spring-cloud-azure-sample-eventhubs-kafka/src/main/resources/application.yaml
