### ISSUE TITLE
[FEATURE REQ] Collect BI data for Kafka passwordless library automatically

### ISSUE THREAD

**Issue by yiliuTo** [Azure/azure-sdk-for-java#31663]
## Context
The passwordless connection support of Event Hubs for Kafka has been beta released from version 4.3.0. 
For the support, we have set our user agents:
- "az-sp-kafka"

Now we need to collect the data of our library of [com.azure.spring:spring-cloud-azure-starter](https://central.sonatype.dev/artifact/com.azure.spring/spring-cloud-azure-starter/4.3.0) according to the user agent.

## Goal
- Setup stuff (lens job, kusto job, BI query, etc) to collect our data usage of Kafka passwordless support library automatically.
- Display the data in BI dashboard.

## Solution
1. Search for our SDK track2 telemetry database to see whether the Event Hubs service data can be collected automatically.
2. If not, ask for the Service and SDK team to see if this can be done by modifying the stream of the telemetry data.
3. Otherwise, we have to load data from Event Hubs service database manually to our telemetry database.

**Comment by backwind1233** [comment]
Closing this, redirect to [ado-private only](https://dev.azure.com/azure-spring-integration/spring-integration-private/_workitems/edit/1314)
