### ISSUE TITLE
Fix Dependencies Missing from DependencyManagement

### ISSUE THREAD

**Issue by bsiegel** [Azure/azure-sdk-for-java#3169]
Based on the report, we seem to have many cases where we have dependencies in use that are not managed by the Parent POM dependencyManagement section. We should resolve these, and then modify the dependency checker tool to emit a nonzero exit code when any inconsistency is detected.

**Comment by kurtzeborn** [comment]
Considering the work that @mitchdenny and @JimSuplizio have done on this, I think this issue is obsolete.

**Comment by JimSuplizio** [comment]
@kurtzeborn @bsiegel @mitchdenny 
Yes, with the centralization of external dependencies and removal/disallowing of dependencyManagement sections in POM files, the dependencies are in a much better state.
