### ISSUE TITLE
Add proxy setting in Gateway mode for the Spark Connector

### ISSUE THREAD

**Issue by sbarnoud** [Azure/azure-sdk-for-java#31693]
Currently, or it is not documented, the Spark Connector doesn't expose configuration properties to use a HTTP proxy in Gateway mode.

Looking here https://github.com/Azure/azure-sdk-for-java/blob/main/sdk/cosmos/azure-cosmos-spark_3_2-12/docs/configuration-reference.md doesn't show any property mapped to the method setProxy of GatewayConnectionConfig

**Comment by TheovanKraay** [comment]
Also raised in issue: https://github.com/Azure/azure-sdk-for-java/issues/28956. We'll consider this in next Semester planning.

**Comment by kushagraThapar** [comment]
@xinlian12 please take a look at this, thanks!
