### ISSUE TITLE
The request is not properly formatted. The parameter 'scope' is duplicated. -> Server Error 400

### ISSUE THREAD

**Issue by ehogeweg** [Azure/azure-sdk-for-java#31733]
I am trying to get [this sample](https://learn.microsoft.com/en-us/azure/developer/java/spring-framework/configure-spring-boot-starter-java-app-with-azure-active-directory) working. 
It is a plain vanilla Spring Initializer project with Spring Web, Azure Active Directory, and OAuth2 Client.
Java 11
tried azure-sdk-for-java 4.4.0 and 6.0.0-beta.2.

Followed all the steps and rebuilt everything twice but I keep running into this same error:

`[invalid_request] AADSTS9000411: The request is not properly formatted. The parameter 'scope' is duplicated. Trace ID: 079ac86a-6c97-40d2-9463-8fe5be1d5800 Correlation ID: 89ae0eaa-f0e4-4a7f-9488-e5da66b40797 Timestamp: 2022-10-26 01:21:31Z
`

And sure enough... the POST DOES contain a lot of duplications:

"<POST https://login.microsoftonline.com/9a389f02-1111-2222-3333-6731502edb22/oauth2/v2.0/token,{grant_type=[authorization_code], code=[0.ATgAAp84mnlg102ca2cxU
    <removed for brevity>
gatk7bcA], redirect_uri=[http://localhost:8080/login/oauth2/code/], scope=[openid profile offline_access https://graph.microsoft.com/User.Read, openid profile offline_access https://graph.microsoft.com/User.Read, openid profile offline_access https://graph.microsoft.com/User.Read, openid profile offline_access https://graph.microsoft.com/User.Read, openid profile offline_access https://graph.microsoft.com/User.Read, openid profile offline_access https://graph.microsoft.com/User.Read, openid profile offline_access https://graph.microsoft.com/User.Read]},[Accept:"application/json;charset=UTF-8", Content-Type:"application/x-www-form-urlencoded;charset=UTF-8", Authorization:"Basic NGI0ODNiODctNWMwNS00ZjQ4LTkyNzItYmZkZmE1MWVmZWMzOjdWczhRJTdFMGVfYUZ3OVNCYk9RUVRxNHdxMGdsTzVHbkxPUGdlT2E3eQ==", x-client-SKU:"az-sp-aad", "az-sp-aad", "az-sp-aad", "az-sp-aad", "az-sp-aad", "az-sp-aad", "az-sp-aad", x-client-VER:"4.4.0", "4.4.0", "4.4.0", "4.4.0", "4.4.0", "4.4.0", "4.4.0", client-request-id:"d65adf28-6f54-405c-b8f7-697ba2eee9a5", "9fd23afb-451f-4dc1-8828-27dd8dffcef0", "4e2d85bb-6e7f-4f5c-bda4-0f57d053db5d", "0b57f544-df33-42bf-9572-54e95c0861e4", "3f4131b5-96e2-4552-a17d-3001c626fc07", "b8f95157-f805-414c-98ff-87cc3ca2bdd4", "5906ca56-fbb6-44c3-a39f-07b3b91b05dc"]>"

Any help is greatly appreciated.

Erwin

**Comment by marccollin** [comment]
I confirm, I get the same result

**Comment by yiliuTo** [comment]
Hi @chenrujun , could you help to take a look?

**Comment by chenrujun** [comment]
Hi, @ehogeweg 

Thanks for reaching out.
This problem is a known issue, and is tracked here: https://github.com/Azure/azure-sdk-for-java/issues/31191
It will be fixed in version **4.4.1**. 
**4.4.1** is planned to be released before **2022-11-01**.

**Comment by ehogeweg** [comment]
Hi, @chenrujun 

Thanks for letting me know. I can confirm that the issue is resolved in 4.5.0-beta.2.
However, now the demo app. throws a NPE after logging in. Should I open a new issue here or in the documentation repo?
