### ISSUE TITLE
Sample potential defects

### ISSUE THREAD

**Issue by chuckz1321** [Azure/azure-sdk-for-java#31744]
https://github.com/Azure/azure-sdk-for-java/blob/7dfecebcdc460bae1c5bf078581b40b3bed187d5/sdk/eventhubs/azure-messaging-eventhubs/src/samples/java/com/azure/messaging/eventhubs/SampleCheckpointStore.java#L84

Maybe we should change it to the code below? 
!partitionOwnershipMap.containsKey(partitionOwnership.getPartitionId())

**Comment by joshfree** [comment]
@conniey please take a look

**Comment by conniey** [comment]
The logic looks correct. From the method documentation,

> If a partition is already claimed by an instance or if the ETag in the request doesn't match the previously stored ETag, then ownership claim is denied.

Comparing eTags is necessary because we want to make sure that the ownerships we're requesting haven't been updated yet.
