### ISSUE TITLE
[FEATURE REQ] Spring Cloud Azure AD should work with non webapp

### ISSUE THREAD

**Issue by moarychan** [Azure/azure-sdk-for-java#31748]
### Context
The current Spring Cloud Azure  AD only works with the Spring Web, the non webapp scenario should be considered too.
If the scenario is valid, then these features should not be mixed and provided to users, they should be combined with user scenarios.

Refer issue: https://github.com/spring-projects/spring-boot/issues/202

### Goal
Provide a way to make the current Spring Security features work in a non webapp environment, also the webapp scenario users also can leverage the features which belong to a non webapp.

**Comment by stliu** [comment]
nice catch
