### ISSUE TITLE
[BUG] there is no parent span that tracks whole timer callback

### ISSUE THREAD

**Issue by rishabhpathakbp** [Azure/azure-sdk-for-java#31769]
[bp-ihub-asb-asb-connector.zip](https://github.com/Azure/azure-sdk-for-java/files/9876078/bp-ihub-asb-asb-connector.zip)

**Comment by lmolkova** [comment]
Created https://issues.apache.org/jira/browse/CAMEL-18661 to track it.

**Comment by lmolkova** [comment]
Closing - Camel issue is fixed in version 3.20.0.
