### ISSUE TITLE
[BUG] runSliceQuery from azure-spring-data-cosmos doesn't return specified number of records in the page size

### ISSUE THREAD

**Issue by hthokur** [Azure/azure-sdk-for-java#31779]
Description:   runSliceQuery from azure-spring-data-cosmos doesn't return specified number of records in the page size. E.g. If size is specified as 1000 it returns only 472 records though there are more records in the cosmos db. 

    public <T> Slice<T> **runSliceQuery**(SqlQuerySpec querySpec, Pageable pageable, Class<?> domainType, Class<T> returnType) {
        String containerName = this.getContainerName(domainType);
        SqlQuerySpec sortedQuerySpec = NativeQueryGenerator.getInstance().generateSortedQuery(querySpec, pageable.getSort());
        return this.sliceQuery(sortedQuerySpec, pageable, pageable.getSort(), returnType, containerName, Optional.empty());
    }

***Exception or Stack Trace***
No exception or stack trace

**To Reproduce**
  1. Create 10000 documents in a cosmos db  2. 
  2. Use runSliceQuery to fetch the records with a high page size, say 1000  3. 
  3. It returns lesser number of records. e.g. in my test it returned only 472 records though there are million records in the db.   4. 
 Note that this is not consistently reproducible. It is found to be working correctly with low page size. i.e. 20

***Code Snippet***
 CosmosPageRequest unsortedPageRequest = CosmosPageRequest.of(
                optionsDto.getPageRequest().getPageNumber(),
                optionsDto.getPageRequest().getPageSize(),
                isNull(optionsDto.getPageRequest().getRequestContinuation()) ? null :
                        optionsDto.getPageRequest().getRequestContinuation(),
                Sort.unsorted()
        );
        return cosmosTemplate.runSliceQuery(
                querySpec, unsortedPageRequest, MyDomainType.class, MyReturnType.class);
    

**Expected behavior**
The interface should return specified number of records in the response. But it is returning less. 

**Screenshots**

**Setup (please complete the following information):**
 - OS: iOs & windows
 - IDE: postman
 - Library/Libraries: azure-spring-data-cosmos:3.13.0
 - Java version: 11
 - App Server/Environment: Tomcat
 - Frameworks: Spring Boot

**Additional context**

**Information Checklist**
Kindly make sure that you have added all the following information above and checkoff the required fields otherwise we will treat the issuer as an incomplete report
- [ ] Bug Description Added
- [ ] Repro Steps Added
- [ ] Setup information Added

**Comment by kushagraThapar** [comment]
@hthokur there have been a lot of new features and bug fixes in latest sprig data cosmos SDK, can you please upgrade to the latest version and try again?

**Comment by hthokur** [comment]
Issue has been resolved after upgrading to latest spring data cosmos SDK.

**Comment by chenrujun** [comment]
@hthokur 
Thanks for the feedback. Closing this issue.

**Comment by mithunbabu-OT** [comment]
Seeing this issue popup again after upgrading to azure-spring-data-cosmos:3.28.1 version. New ticket with details - https://github.com/Azure/azure-sdk-for-java/issues/33618
