### ISSUE TITLE
Unable to execute queries with distinct keyword

### ISSUE THREAD

**Issue by ViswanathVeerappan** [Azure/azure-sdk-for-java#31784]
We are running into a problem while executing a query that has distinct keyword and orders by a field. When the result set fetched during the execution of the query does not match the size limit specified and if we have a continuation token that is not null, we are noticing this issue. 

The continuation token generated for us has an attribute called "lastHash" which is not being accepted as a valid token attribute. Here is the error message reported by the sdk,

`Failed to query items; nested exception is {\"ClassName\":\"BadRequestException\",\"userAgent\":\"azsdk-java-cosmos/4.38.1 MacOSX/10.16 JRE/1.8.0_232\",\"statusCode\":400,\"resourceAddress\":null,\"innerErrorMessage\":\"One of the input values is invalid.: DistinctContinuationToken is malformed. DistinctContinuationToken can not have a 'lastHash', when the query type is not ordered (ex SELECT DISTINCT VALUE c.blah FROM c ORDER BY c.blah).\",\"causeInfo\":null,\"responseHeaders\":\"{}\"}`

The query we were trying to execute,

`SELECT distinct c.originalMessageId, c.messageTimestamp FROM c WHERE c.testFlag = @testFlag AND (@originalMessageId = null OR c.originalMessageId = @originalMessageId) AND ARRAY_CONTAINS(@partitionIds, c.partitionId) AND (c.messageTimestamp between @rangeStart and @rangeEnd) ORDER BY c.messageTimestamp ASC` 

The page number and page size were set using the CosmosPageRequest object. Initially we had it set to 0 and 100 respectively.

https://github.com/Azure/azure-sdk-for-java/blob/main/sdk/cosmos/azure-spring-data-cosmos/src/main/java/com/azure/spring/data/cosmos/core/CosmosTemplate.java#L826

The query we issued was able to fetch only 20 records in the first iteration and along with the following continuation token,

`{"lastHash":"kMmLddiTVKs4TqCdtIm7Uw==","sourceToken":"{\"compositeToken\":\"{\\\"token\\\":\\\"+RID:~NEwdAJ-YNKKtWhsAAABABg==#RT:1#TRC:100#RTD:Svj6cyIw1f7CCts4bwYlBTMxMzMuMTouMzhVMjo7MjU7MzovOjM5WwA=#ISV:2#IEO:65567#QCF:8#FPC:AghtAAAAABkAAHYCAAAAGQAAbQAAAAAZAAAGADEawP/AZW4AAAAAGQAAAgAAQG8AAAAAGQAAAgAAQHAAAAAAGQAAAgAAQHEAAAAAGQAAAgAAQHIAAAAAGQAAAgAAQHMAAAAAGQAAAgAAQHQAAAAAGQAAAgAAQHUAAAAAGQAAAgAAQHYAAAAAGQAAAgAAQHcAAAAAGQAAAgAAQHgAAAAAGQAAAgAAQHkAAAAAGQAAAgAAQHoAAAAAGQAABACBRAEAbgEAAAAZAAAGAIEN/v9wcm8BAAAAGQAAAgAAQHABAAAAGQAAAgAAQHEBAAAAGQAAAgAAQHIBAAAAGQAAAgAAQHMBAAAAGQAAAgAAQHQBAAAAGQAAAgAAQHUBAAAAGQAAAgAAQHYBAAAAGQAAAgAAQHcBAAAAGQAAAgAAQHgBAAAAGQAAAgAAQHkBAAAAGQAAAgAAQHoBAAAAGQAAAgAAQHsBAAAAGQAAAgAAQHwBAAAAGQAAAgAAQH0BAAAAGQAAAgAAQH4BAAAAGQAAAgAAQH8BAAAAGQAAAgAAQIABAAAAGQAAAgAAQIEBAAAAGQAAAgAAQIIBAAAAGQAAAgAAQIMBAAAAGQAAAgAAQIQBAAAAGQAAAgAAQIUBAAAAGQAAAgAAQIYBAAAAGQAAAgAAQIcBAAAAGQAAAgAAQIgBAAAAGQAAAgAAQIkBAAAAGQAAAgAAQIoBAAAAGQAAAgAAQIsBAAAAGQAAAgAAQIwBAAAAGQAAAgAAQI0BAAAAGQAAAgAAQI4BAAAAGQAAAgAAQI8BAAAAGQAAAgAAQJABAAAAGQAAAgAAQJEBAAAAGQAAAgAAQJIBAAAAGQAAAgAAQJMBAAAAGQAAAgAAQJQBAAAAGQAAAgAAQJUBAAAAGQAAAgAAQJYBAAAAGQAAAgAAQJcBAAAAGQAAAgAAQJgBAAAAGQAAAgAAQJkBAAAAGQAAAgAAQJoBAAAAGQAAAgAAQJsBAAAAGQAAAgAAQJwBAAAAGQAAAgAAQJ0BAAAAGQAAAgAAQJ4BAAAAGQAAAgAAQJ8BAAAAGQAAAgAAQKABAAAAGQAAAgAAQKEBAAAAGQAAAgAAQKIBAAAAGQAAAgAAQKMBAAAAGQAAAgAAQKQBAAAAGQAAAgAAQKUBAAAAGQAAAgAAQKYBAAAAGQAAAgAAQKcBAAAAGQAAAgAAQKgBAAAAGQAAAgAAQKkBAAAAGQAAAgAAQKoBAAAAGQAAAgAAQKsBAAAAGQAABAARef8DbwIAAAAZAAAGACE2AMDQSXACAAAAGQAAAgAAQHECAAAAGQAAAgAAQHICAAAAGQAAAgAAQHMCAAAAGQAAAgAAQHQCAAAAGQAAAgAAQHUCAAAAGQAAAgAAQHYCAAAAGQAABAChdB8A\\\",\\\"range\\\":{\\\"min\\\":\\\"05C1B7FFFFFFF0\\\",\\\"max\\\":\\\"05C1BFFFFFFFF0\\\"}}\",\"orderByItems\":[{\"item\":\"2022-09-27T19:14:27.928Z\"}],\"rid\":\"NEwdAJ-YNKI2WhsAAABABg==\",\"inclusive\":true}"}`

Since the continuation token has a property called "lastHash", the next iteration to fetch more records was encountering an exception reported earlier. This is the version of the library we are using,

<dependency>
            <groupId>com.azure</groupId>
            <artifactId>azure-spring-data-cosmos</artifactId>
            <version>3.29.1</version>
</dependency>

**Comment by yiliuTo** [comment]
Hi @kushagraThapar , could you help to look into this issue?

**Comment by kushagraThapar** [comment]
@trande4884 please take a look at this, thanks!

**Comment by trande4884** [comment]
@ViswanathVeerappan it looks like you are trying to use an annotated query when you run into the issue is that correct? Also, I'm assuming since you are saying the first page only gets back 20 results you are expecting to get more back than that with your page size of 100?

**Comment by loudywen** [comment]
@trande4884 yes, we did use the annotated query only. and yes that query has more than 10k results.

**Comment by trande4884** [comment]
@loudywen so you are defining a CosmosPageRequest like below correct?
CosmosPageRequest pageRequest = new CosmosPageRequest(0, 100, null);

When querying for the second page, are you using pageRequest.next() or is an entirely new CosmosPageRequest being created? Also, in your CosmosPageRequest creation are you passing in the Sort parameter or just page number, page size and continuation token?

**Comment by loudywen** [comment]
@trande4884  We just return one page at a time. for next page, client will send us a page number and token. So we don't use pageRequest.next(), it just an entierly new CosmosPageRequest for each page .

Depends on whether the endpoint received the token, if token is null we do 
CosmosPageRequest pageRequest = CosmosPageRequest.of(page, size, null, sort);
else, CosmosPageRequest pageRequest = CosmosPageRequest.of(page, size, token, sort);

the sort just like this Sort sort = Sort.by(Sort.Order.asc("messageTimestamp"));

**Comment by trande4884** [comment]
Thank you for the additional info @loudywen ! So I am trying to reproduce the issue but so far not able, here is my test I have setup so let me know if anything looks different from what you are running:

`@Query(value = "SELECT distinct c.postalCode FROM c WHERE c.city = @city")
    Page<Address> annotatedFindPostalCodeByCityOrdered(@Param("city") String city, Pageable pageable);`

`CosmosPageRequest pageRequest = new CosmosPageRequest(0, 100, null, Sort.by(Sort.Direction.ASC, "postalCode"));
        final Page<Address> resultsAsc = addressRepository.annotatedFindPostalCodeByCityOrdered(TestConstants.CITY, pageRequest);

        CosmosPageRequest pageRequest2 = new CosmosPageRequest(1, 100, token, Sort.by(Sort.Direction.ASC, "postalCode"));
        final Page<Address> resultAsc2 = addressRepository.annotatedFindPostalCodeByCityOrdered(TestConstants.CITY, pageRequest.next());`

I should be seeing the error when executing resultAsc2 correct?

**Comment by loudywen** [comment]
@trande4884  the `resultsAsc ` should seeing error. I think there is a confusion here. if the query result has only 1 page , then no error, if has more than 1 page then you should see error. If you try to set the page size to 1, may be you will see the error

**Comment by ViswanathVeerappan** [comment]
@trande4884 We just want to let you know that we have around 20 physical partitions on our container. We issued a single query with page number = 0 and size = 100. When the query was executed [within this do while block](https://github.com/Azure/azure-sdk-for-java/blob/main/sdk/cosmos/azure-spring-data-cosmos/src/main/java/com/azure/spring/data/cosmos/core/CosmosTemplate.java#L826), the query fetched only 20 records and a continuation token. Since this condition,

`result.size() < pageable.getPageSize() && continuationToken != null` was true, 

(result set(20) < page size(100)) and (continuation token was not null), it went ahead and executed the query again inside the loop updating the page number to 1. We were encountering a problem during this iteration since the query contained an attribute "lastHash".

**Comment by trande4884** [comment]
@loudywen @ViswanathVeerappan thank you for the additional context. Just to be clear is this something that was working in the past and has regressed or is this a new implementation?

**Comment by ViswanathVeerappan** [comment]
@trande4884 This is a new piece of functionality we are trying to implement. Here is a sample data model, 
`[
  {
    "originalMessageId": "a",
    "messageId": "aa",
    "messageTimestamp": "2022-10-15T02:09:54.546Z"
  },
  {
    "originalMessageId": "a",
    "messageId": "bb",
    "messageTimestamp": "2022-10-15T02:09:54.546Z"
  },
  {
    "originalMessageId": "a",
    "messageId": "bb",
    "messageTimestamp": "2022-10-15T02:09:54.546Z"
  },
  {
    "originalMessageId": "a",
    "messageId": "cc",
    "messageTimestamp": "2022-10-15T02:09:54.546Z"
  },
  {
    "originalMessageId": "b",
    "messageId": "dd",
    "messageTimestamp": "2022-10-15T05:15:54.546Z"
  },
  {
    "originalMessageId": "b",
    "messageId": "ff",
    "messageTimestamp": "2022-10-15T05:15:54.546Z"
  },
  {
    "originalMessageId": "c",
    "messageId": "gg",
    "messageTimestamp": "2022-10-15T15:00:00.000Z"
  },
  {
    "originalMessageId": "d",
    "messageId": "hh",
    "messageTimestamp": "2022-10-15T23:59:59.999Z"
  }
]
`

From this we would like to filter out unique originalMessageId and messageTimestamp combination as follows,

`[
  {
    "originalMessageId": "a",
    "messageTimestamp": "2022-10-15T02:09:54.546Z"
  },
  {
    "originalMessageId": "b",
    "messageTimestamp": "2022-10-15T05:15:54.546Z"
  },
  {
    "originalMessageId": "c",
    "messageTimestamp": "2022-10-15T15:00:00.000Z"
  },
  {
    "originalMessageId": "d",
    "messageTimestamp": "2022-10-15T23:59:59.999Z"
  }
]
`
Also, we are looking into finding the total count of this.

**Comment by trande4884** [comment]
@ViswanathVeerappan and @loudywen there are some issues in our implementation that I am working to resolve in this area, as we should not be returning a continuation token back to you with the first page of results. However, you should be able to get things running without my changes. The query above does not support continuation tokens, so you must Simply create your CosmosPageRequest objects with page number and page size and leave the continuation token blank.

This is a DISTINCT query that supports continuation tokens:
- SELECT DISTINCT VALUE c.name FROM c ORDER BY c.name

These are DISTINCT queries that do not support continuation tokens:
- SELECT DISTINCT c.name FROM c ORDER BY c.name
- SELECT DISTINCT VALUE c.name FROM c ORDER BY c.id

In order for continuation tokens to be supported with DISTINCT they must use VALUE and the ORDER BY has to be the same field you are returning. Due to these requirements no DISTINCT query that returns more than one field will support continuation tokens. [More info can be found here.](https://learn.microsoft.com/en-us/azure/cosmos-db/nosql/query/pagination)

**Comment by ViswanathVeerappan** [comment]
@trande4884 Just a follow up question to what was mentioned in the above thread,

Can the queries containing the distinct keyword where a continuation token is expected, have a where clause on some other fields than the field to which the distinct keyword is being applied to?

For example,

`SELECT DISTINCT VALUE c.name FROM c where c.age > 25 and c.city = 'Chicago' ORDER BY c.name `

That was something not clear in the documentation attached. 

For the query we were trying to implement, we could look into implementing some kind of client side filtering that filters out duplicate originalMessageId and messageTimestamp based combination.

We would like to make sure if either of the following queries was supported by the database,

`SELECT count(uniqueCount) as count FROM (SELECT distinct value c.originalMessageId FROM c WHERE c.testFlag = @testFlag AND ARRAY_CONTAINS(@partitionIds, c.partitionId) AND (c.messageTimestamp between @rangeStart and @rangeEnd)) as uniqueCount`

`SELECT count(1) as count FROM (SELECT distinct value c.originalMessageId FROM c WHERE c.testFlag = @testFlag AND ARRAY_CONTAINS(@partitionIds, c.partitionId) AND (c.messageTimestamp between @rangeStart and @rangeEnd))`

Since the client side filtering is being considered as an option, we would atleast need to have a way to reconcile the count of available on the database.

One of the observations noticed while executing the count queries was, it consumed more RUs(close to 90K out of 200K. It gave us a count of 2.3 million from a total 9 million odd records). Also, it took about 40 to 50 seconds to complete the execution. 

Do you have any recommendations or suggestions to reduce the RU consumption and the latency?

**Comment by trande4884** [comment]
The below is an acceptable query for pagination:
`SELECT DISTINCT VALUE c.name FROM c where c.age > 25 and c.city = 'Chicago' ORDER BY c.name`

In regards to the two count queries you posted, you are asking if they are supported but it seems you have already ran them to get the consumed RUs correct? Are you trying to run these as annotated queries?

**Comment by ViswanathVeerappan** [comment]
@trande4884 Yeah, I am trying to run the count queries as annotated queries. Just trying to see if they are supported and in the right usage. Are there any general guidelines or recommendations when it comes to using the queries with count keyword? Just in terms of using the right indexes. Since I'm using a subquery, I'm not able to use any composite indexes and order by clause in the subquery part. In general, wanting to reduce the RU consumption while executing the count queries.

**Comment by trande4884** [comment]
I don't believe you need the subquery, instead of:
`SELECT count(uniqueCount) as count FROM (SELECT distinct value c.originalMessageId FROM c WHERE c.testFlag = @testFlag AND ARRAY_CONTAINS(@partitionIds, c.partitionId) AND (c.messageTimestamp between @rangeStart and @rangeEnd)) as uniqueCount`

You should be able to do something like this:
`SELECT COUNT(distinct value c.originalMessageId) FROM c WHERE c.testFlag = @testFlag AND ARRAY_CONTAINS(@partitionIds, c.partitionId) AND (c.messageTimestamp between @rangeStart and @rangeEnd)`

**Comment by ViswanathVeerappan** [comment]
@trande4884 I could not use distinct and value keywords in the query suggested above. It is throwing me the following syntax error,

{"errors":[{"severity":"Error","location":{"start":13,"end":21},"code":"SC1001","message":"Syntax error, incorrect syntax near 'distinct'."}]}

**Comment by trande4884** [comment]
Ah okay, however since this is a count query that will not be paginated you can just remove the 'VALUE' attribute.

**Comment by ViswanathVeerappan** [comment]
@trande4884 It is not letting me use either distinct or value or both.

SELECT COUNT(distinct value c.originalMessageId) AS uniqueCount FROM c WHERE c.testFlag = @testFlag AND ARRAY_CONTAINS(@partitionIds, c.partitionId) AND (c.messageTimestamp between @rangeStart and @rangeEnd)

SELECT COUNT(distinct c.originalMessageId) AS uniqueCount FROM c WHERE c.testFlag = @testFlag AND ARRAY_CONTAINS(@partitionIds, c.partitionId) AND (c.messageTimestamp between @rangeStart and @rangeEnd)

SELECT COUNT(value c.originalMessageId) AS uniqueCount FROM c WHERE c.testFlag = @testFlag AND ARRAY_CONTAINS(@partitionIds, c.partitionId) AND (c.messageTimestamp between @rangeStart and @rangeEnd)

The above combinations of the query are not working. Only the following query works,

SELECT COUNT(c.originalMessageId) AS uniqueCount FROM c WHERE c.testFlag = @testFlag AND ARRAY_CONTAINS(@partitionIds, c.partitionId) AND (c.messageTimestamp between @rangeStart and @rangeEnd)

**Comment by ViswanathVeerappan** [comment]
@trande4884 thank you for taking a lot at it.
