### ISSUE TITLE
[BUG] SerivceBus Receiver exception: java.lang.IllegalStateException: Cannot add credits to closed link

### ISSUE THREAD

**Issue by vn53h3y** [Azure/azure-sdk-for-java#31793]
**Describe the bug**
Hi, I am using azure-messaging-servicebus-7.9.1

Randomly my project hangs when the exception is thrown, loss the link and never connect again. 

The exception is 

> {"id":"30053968","outerId":"0","type":"reactor.core.Exceptions$ErrorCallbackNotImplemented","message":"java.lang.IllegalStateException: Cannot add credits to closed link: sfo-events/subscriptions/oms-task_4d4a8c_1665483708655","severityLevel":"Error"}
> 
> {"id":"1155017876","outerId":"30053968","type":"java.lang.IllegalStateException","message":"Cannot add credits to closed link: sfo-events/subscriptions/oms-task_4d4a8c_1665483708655","parsedStack":[{"level":0,"method":"com.azure.core.amqp.implementation.ReactorReceiver.addCredits","line":196,"fileName":"ReactorReceiver.java"},{"level":1,"method":"com.azure.messaging.servicebus.implementation.ServiceBusReceiveLinkProcessor.checkAndAddCredits","line":573,"fileName":"ServiceBusReceiveLinkProcessor.java"},{"level":2,"method":"com.azure.messaging.servicebus.implementation.ServiceBusReceiveLinkProcessor.onNext","line":268,"fileName":"ServiceBusReceiveLinkProcessor.java"},{"level":3,"method":"com.azure.messaging.servicebus.implementation.ServiceBusReceiveLinkProcessor.onNext","line":48,"fileName":"ServiceBusReceiveLinkProcessor.java"},{"level":4,"method":"reactor.core.publisher.FluxRepeatPredicate$RepeatPredicateSubscriber.onNext","line":86,"fileName":"FluxRepeatPredicate.java"},{"level":5,"method":"reactor.core.publisher.MonoPeekTerminal$MonoTerminalPeekSubscriber.onNext","line":180,"fileName":"MonoPeekTerminal.java"},{"level":6,"method":"reactor.core.publisher.SerializedSubscriber.onNext","line":99,"fileName":"SerializedSubscriber.java"},{"level":7,"method":"reactor.core.publisher.FluxRetryWhen$RetryWhenMainSubscriber.onNext","line":174,"fileName":"FluxRetryWhen.java"},{"level":8,"method":"reactor.core.publisher.FluxOnErrorResume$ResumeSubscriber.onNext","line":79,"fileName":"FluxOnErrorResume.java"},{"level":9,"method":"reactor.core.publisher.FluxPeekFuseable$PeekFuseableSubscriber.onNext","line":210,"fileName":"FluxPeekFuseable.java"},{"level":10,"method":"reactor.core.publisher.Operators$MonoSubscriber.request","line":1906,"fileName":"Operators.java"},{"level":11,"method":"reactor.core.publisher.FluxPeekFuseable$PeekFuseableSubscriber.request","line":144,"fileName":"FluxPeekFuseable.java"},{"level":12,"method":"reactor.core.publisher.Operators$MultiSubscriptionSubscriber.request","line":2158,"fileName":"Operators.java"},{"level":13,"method":"reactor.core.publisher.Operators$MultiSubscriptionSubscriber.request","line":2158,"fileName":"Operators.java"},{"level":14,"method":"reactor.core.publisher.SerializedSubscriber.request","line":151,"fileName":"SerializedSubscriber.java"},{"level":15,"method":"reactor.core.publisher.MonoPeekTerminal$MonoTerminalPeekSubscriber.request","line":139,"fileName":"MonoPeekTerminal.java"},{"level":16,"method":"reactor.core.publisher.Operators$MultiSubscriptionSubscriber.request","line":2158,"fileName":"Operators.java"},{"level":17,"method":"com.azure.messaging.servicebus.implementation.ServiceBusReceiveLinkProcessor.requestUpstream","line":451,"fileName":"ServiceBusReceiveLinkProcessor.java"},{"level":18,"method":"com.azure.messaging.servicebus.implementation.ServiceBusReceiveLinkProcessor.lambda$onError$7","line":352,"fileName":"ServiceBusReceiveLinkProcessor.java"},{"level":19,"method":"reactor.core.publisher.LambdaMonoSubscriber.onNext","line":171,"fileName":"LambdaMonoSubscriber.java"},{"level":20,"method":"reactor.core.publisher.MonoDelay$MonoDelayRunnable.propagateDelay","line":271,"fileName":"MonoDelay.java"},{"level":21,"method":"reactor.core.publisher.MonoDelay$MonoDelayRunnable.run","line":286,"fileName":"MonoDelay.java"},{"level":22,"method":"reactor.core.scheduler.SchedulerTask.call","line":68,"fileName":"SchedulerTask.java"},{"level":23,"method":"reactor.core.scheduler.SchedulerTask.call","line":28,"fileName":"SchedulerTask.java"},{"level":24,"method":"java.util.concurrent.FutureTask.run","line":266,"fileName":"FutureTask.java"},{"level":25,"method":"java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201","line":180,"fileName":"ScheduledThreadPoolExecutor.java"},{"level":26,"method":"java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run","line":293,"fileName":"ScheduledThreadPoolExecutor.java"},{"level":27,"method":"java.util.concurrent.ThreadPoolExecutor.runWorker","line":1149,"fileName":"ThreadPoolExecutor.java"},{"level":28,"method":"java.util.concurrent.ThreadPoolExecutor$Worker.run","line":624,"fileName":"ThreadPoolExecutor.java"},{"level":29,"method":"java.lang.Thread.run","line":750,"fileName":"Thread.java"}],"severityLevel":"Error"}

I think that it is related with the message 

> {"az.sdk.message":"Transient error occurred.","exception":"The link 'G6:60217897:topic/subscriptions/task_4d4a8c_1665483708655' is force detached. Code: consumer(link3281). Details: AmqpMessageConsumer.IdleTimerExpired: Idle timeout: 00:10:00. TrackingId:7e23e7c70011023400000cd1634543bd_G6_B72, SystemTracker:name-spacet:Topic:topic|task, Timestamp:2022-10-11T17:21:48, errorContext[NAMESPACE: name-space.servicebus.windows.net. ERROR CONTEXT: N/A, PATH: topic/subscriptions/task, REFERENCE_ID: name-space/subscriptions/task_4d4a8c_1665483708655, LINK_CREDIT: 0]","linkName":"n/a","entityPath":"n/a","attempt":1,"retryAfter":4522}

because the last message shows that the link is closed, and the exception is related with a link closed

***Code Snippet***
I see that a recent bug it is related https://github.com/Azure/azure-sdk-for-java/issues/31513, i follow the idea of the code suggest and still the error occur. 

**Setup (please complete the following information):**
 - Java version: 11
 - App Server/Environment: AZURE
 - Frameworks: Spring Boot

**Information Checklist**
Kindly make sure that you have added all the following information above and checkoff the required fields otherwise we will treat the issuer as an incomplete report
- [x] Bug Description Added
- [ ] Repro Steps Added
- [x] Setup information Added

**Comment by anuchandy** [comment]
Hi @vn53h3y, The Service Bus SDK version 7.9.1 is missing a reliability fix, [this ](https://github.com/Azure/azure-sdk-for-java/blob/main/sdk/core/azure-core-amqp/CHANGELOG.md#bugs-fixed-1) one. Could you 

1. Update to the latest SDK version
2. Then double-check three things - 
   -  code is opt-in for [disableAutoComplete](https://github.com/Azure/azure-sdk-for-java/blob/main/sdk/servicebus/azure-messaging-servicebus/src/samples/java/com/azure/messaging/servicebus/ServiceBusProcessorPeekLockReceiveSample.java#L58-L63).
    - code is doing explicit complete and abandon [call](https://github.com/Azure/azure-sdk-for-java/blob/main/sdk/servicebus/azure-messaging-servicebus/src/samples/java/com/azure/messaging/servicebus/ServiceBusProcessorPeekLockReceiveSample.java#L96-L110)
    - code is [handling ](https://github.com/Azure/azure-sdk-for-java/blob/main/sdk/servicebus/azure-messaging-servicebus/src/samples/java/com/azure/messaging/servicebus/ServiceBusProcessorPeekLockReceiveSample.java#L99-L102) exceptions from complete and abandon call, and is **NOT** rethrowing the exception

**Comment by vn53h3y** [comment]
Hi @anuchandy thanks for answer me.

I updated the SDK to its latest version. Respect to your suggestion 2. I am uploading my receiver version, as you can see i meet with your suggestions, any other suggestion to avoid this error.
 
```
package personal;

import com.azure.core.amqp.AmqpRetryMode;
import com.azure.core.amqp.AmqpRetryOptions;
import com.azure.messaging.servicebus.*;
import com.fasterxml.jackson.databind.ObjectMapper;
import personal.ReceiverErrors;
import personal.ServiceBusException;
import java.time.Duration;
import java.util.ArrayList;
import java.util.List;
import java.util.function.Consumer;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.NonNull;
import lombok.extern.slf4j.Slf4j;
import org.apache.commons.lang3.StringUtils;
import org.slf4j.MDC;


@Slf4j
@NoArgsConstructor
public abstract class JsonServiceBusReceiver {


  protected final ObjectMapper mapper = new ObjectMapper();
  private ReceiverConfig receiverConfig;
  private final AmqpRetryOptions retryOptions = new AmqpRetryOptions();

  private final List<ServiceBusProcessorClient> serviceBusProcessorClients = new ArrayList<>();

  @Getter private boolean initialized = false;


  public void initialize(@NonNull final ReceiverConfig receiverConfig) {

    if (!initialized) {
      this.receiverConfig = receiverConfig;

      retryOptions.setMaxRetries(5);
      retryOptions.setTryTimeout(Duration.ofSeconds(15));
      retryOptions.setDelay(Duration.ofSeconds(2));
      retryOptions.setMode(AmqpRetryMode.EXPONENTIAL);

      ServiceBusClientBuilder busClientBuilder =
          new ServiceBusClientBuilder().connectionString(this.receiverConfig.getConnectionString());
      for (int i = 0; i < receiverConfig.getMaxMessagesToRead(); i++) {
        serviceBusProcessorClients.add(buildClient(busClientBuilder));
      }
      serviceBusProcessorClients.forEach(ServiceBusProcessorClient::start);
      this.initialized = true;
    }
  }

  public ServiceBusProcessorClient buildClient(ServiceBusClientBuilder busClientBuilder) {
    return busClientBuilder
        .retryOptions(retryOptions)
        .processor()
        .topicName(this.receiverConfig.getTopicName())
        .subscriptionName(this.receiverConfig.getSubscriptionName())
        .processMessage(processMessage)
        .processError(processError)
        .maxAutoLockRenewDuration(
            Duration.ofSeconds(this.receiverConfig.getMaxAutoLockRenewDuration()))
        .disableAutoComplete()
        .buildProcessorClient();
  }

  @Getter
  Consumer<ServiceBusReceivedMessageContext> processMessage =
      messageContext -> {
        MDC.clear();
        ServiceBusReceivedMessage message = messageContext.getMessage();
        try {
          log.info(
              "Received Message Id: {} Correlation Id: {}",
              message.getMessageId(),
              message.getCorrelationId());
          
		  String jsonMessage = this.mapper.readValue(message.getBody().toBytes(), String.class);
          validateAndProcessJsonMessage(jsonMessage);

          messageContext.complete();
          log.info("Completed Message Id: {}", message.getMessageId());

        } catch (final ServiceBusException busException) {
          log.error(
              "[LOG_ALERT_PAGE] Failed Message Id: {} Unable to process message.",
              message.getMessageId());
          if (ReceiverErrors.PARSE_ERROR.getCode().equals(busException.getCode())) {
            log.error(
                "Failed Message Id: {} Unable to parse message. Abandoning Message",
                message.getMessageId(),
                busException);
            messageContext.abandon();
          } else if (ReceiverErrors.UNABLE_TO_PROCESS.getCode().equals(busException.getCode())) {
            log.error(
                "Failed Message Id: {} Unable to process. Abandoning Message",
                message.getMessageId(),
                busException);
            messageContext.abandon();
          } else {
            log.error(
                "Failed Message Id: {} Unable to process. Dead Lettering Message",
                message.getMessageId(),
                busException);
            messageContext.deadLetter();
          }
        } catch (final Exception exception) {
          log.error(
              "[LOG_ALERT_PAGE] Failed Message Id: {} Unable to process message.",
              message.getMessageId());
          log.error(
              "Failed Message Id: {} Unable to process. Dead Lettering Message",
              message.getMessageId(),
              exception);
          messageContext.deadLetter();
        }
      };

  @Getter
  Consumer<ServiceBusErrorContext> processError =
      errorContext ->
          log.error("Error occurred while receiving message", errorContext.getException());
}

```

**Comment by anuchandy** [comment]
I see now you're explicitly disposition (complete|abandon|deadLetter) which is good. But NOT all dispositions are guarded in a try-catch (point 2.3 in my previous comment). 

Also, I'm not sure how many processor clients you're creating; it is coming from config i.e., config.getMeaxMessagesToRead (). So if it's 1000, then 100 clients read from the "same subscription". i.e., 1000 links in the network. Is it intentional?

**Comment by vn53h3y** [comment]
Hi @anuchandy thanks for answer. Right now, we set getMeaxMessagesToRead  to 5. But we have a little doubt about maxConcurrentCalls ServiceBusClientBuilder property. Can we use maxConcurrentCalls  to define the number of listeners as we are defined using getMeaxMessagesToRead ?

**Comment by liukun-msft** [comment]
Hi @vn53h3y, currently I am working on your issue. Ideally, if this error occurs, the processor client will recreate a new link to reconnect after a few minutes. Can you provide +/-30 minutes debug logs when this issue occurs to help me check it further? I am wondering if there are other errors that cause the link not to reconnect again.

**Comment by anuchandy** [comment]
Closing this infavor of 33204.
