### ISSUE TITLE
Delete all resources matching a regex in a resourceGroup

### ISSUE THREAD

**Issue by naksh9619** [Azure/azure-sdk-for-java#3180]
**Query/Question**
Is there any way to delete the resources matching a regex from a resource group or any way to delete all the resources present inside a resource Group?
The maximum I could find was getting all Vms, Network Interfaces etc separately and then deleting the resources separately matching my regex. Is there any other way to do so?

**Setup**
 - OS Type: Linux/MacOS
 - IDE : IntelliJ
 - Java version: 1.9

**Comment by kurtzeborn** [comment]
Thank you for opening this issue! We are routing it to the appropriate team for follow up.

**Comment by singhania** [comment]
+1

**Comment by yungezz** [comment]
hi @naksh9619 You're using the right approach. SDK doesn't provide regex matching on resource name, it should be in application code. Main consideration is cautious on deletion. will close the issue for now. Feel free to open new issue if any other ask.
