### ISSUE TITLE
Identity e2e tests for running fail in Cloudshell and Azure WebJobs

### ISSUE THREAD

**Issue by v-jiaodi** [Azure/azure-sdk-for-java#31812]
**Describe the issue:**
1.Test the Testing azure-identity in Cloudshell with [instructions ](https://github.com/Azure/azure-sdk/issues/795#issuecomment-559900596)(`Repro steps`) .When run the `mvn test -Dtest=ManagedIdentityCredentialLiveTest#testMSIEndpointWithSystemAssigned* -pl sdk/e2e -f pom.client.xml -Dgpg.skip -am -DfailIfNoTests=false` command, it displays the error :

![image](https://user-images.githubusercontent.com/80496810/198209510-63398977-13ea-4a5d-b98e-1eb2d9486735.png)

2.Test the Testing azure-identity in Azure WebJobs with [instructions ](https://github.com/Azure/azure-sdk/issues/902#issuecomment-584294407)(`Repro steps`) .When run the `mvn clean package -Dpackage-with-dependencies -f sdk\e2e\pom.xml` command, it displays the same error.

**Environment:**
Env: Cloudshell terminal and Azure WebJobs
Package: https://search.maven.org/artifact/com.azure/azure-identity/1.7.0-beta.2/jar
Related issue: https://github.com/Azure/azure-sdk/issues/795 and https://github.com/Azure/azure-sdk/issues/902

**Expected behavior:**
Run test can pass.

@josefree for notification.

**Comment by joshfree** [comment]
@g2vinay please take a look

**Comment by g2vinay** [comment]
@v-jiaodi 

I merged a PR yesterday to unblock the test setup.
Can you run the cloudshell test again from source code on main branch ?
Thank you.

**Comment by v-jiaodi** [comment]
@g2vinay According to the latest  [instructions](https://github.com/Azure/azure-sdk/issues/795#issuecomment-559900596), the test can work normally on Cloudshell and Web Jobs.

**Comment by v-jiaodi** [comment]
I will close it.
