### ISSUE TITLE
Application Properties not set correctly when adding it to the Eventdata

### ISSUE THREAD

**Issue by kkamath30** [Azure/azure-sdk-for-java#31820]
I use the following azure-eventhub-messaging version in my application 
<dependency> 
      <groupId>com.azure</groupId>  
      <artifactId>azure-messaging-eventhubs</artifactId>  
      <version>5.14.0</version> 
</dependency> 

I want to set custom application properties to the Eventdata and when i do that using the following code 
 eventData.getProperties().put("EventType", "xxxx");

The custom properties after validating in the ServicebusExplorer is emtpy. I believe there was a similar issue reported for Python.

Is there a fix for the Java version as well?

**Comment by joshfree** [comment]
@conniey please take a look

**Comment by kkamath30** [comment]
![Application Properties](https://user-images.githubusercontent.com/14940838/200294997-1bef7bf5-03ae-4bf2-9d42-19de9bbb7d2b.PNG)

In addition, what i observed is that when i set the application properties, i get the above error message object is read only and cannot be modified in Service Bus Explorer. The payload data is then copied over from the previous sequence to the current one.

**Comment by conniey** [comment]
Hey. Do you have a sample application/repro for this? I tried adding applicationProperties to my EventData and was able to fetch them back from the service.

**Comment by kkamath30** [comment]
Hi Conniey,
Please find attached a test app project that simulates the issue. Please replace in the App.java file the connection string and eventhubname as per your local configuration. 

Please check the following behaviour

Setting the application properties at Eventdata level leads to following exception in service bus
<15:32:59> Exception: This object is read-only and cannot be modified.
and the other issue is that due to the exception, the payload from previous sequence is copied over to the current sequence.

[octopos_adapter.zip](https://github.com/Azure/azure-sdk-for-java/files/10022751/octopos_adapter.zip)

**Comment by kkamath30** [comment]
Hi Conniey,
After further deep dive, i found out now that application properties are set correctly but somehow the recent versions of Service Bus Explorer complains and marks the properties as read only. I validated with version 3.1.4 Service Bus Explorer and there it works fine.

**Comment by conniey** [comment]
I'm glad you were able to debug the issue.  That may be a bug worth filing into the Servicec Bus Explorer repo. (https://github.com/paolosalvatori/ServiceBusExplorer)

Cheers,
Connie
