### ISSUE TITLE
Java eventhubs SDK not picking all messages from EventHub

### ISSUE THREAD

**Issue by PalashBangar-TomTom** [Azure/azure-sdk-for-java#31839]
**Title:**
Java eventhubs SDK not picking all messages from EventHub, please read below for details information.

**Ask:**
Please suggest the potential solution for the behaviour, observation mentioned blow in details. We had also raised this with Microsoft support as well Tracking id #2210060030000738 but they suggested to talk with SDK team 

**Observation:** 

We have 2 independent microservice applications running on Azure Kubernetes. lets say one application acts as producer which sends the event to eventhubs while other applications acts as consumer which pulls the events from event hub.

We're using "EventProcessorClientBuilder" of Azure Eventhubs sdk to receive events from Eventhubs, but we observed that after running for some duration our consumer application gets ideal and stop picking up the events from eventhubs, the process of pulling the events works fine for certain time only after initialization, but eventually it stops pulling the messages even though there are lots of events inside eventhubs, and consumer microservice is healthy and not doesn't show any exception. 

We've also observed: 
- Generally until the eventhubs getting input messages till that time only consumer are able to pull the messages, once the producer application stops consumer application also stops pulling the message, or gradually down. 

- also we have observed if our consumer application is stopped but producer application has already produced lots of events and then while our consumer application retarted it doesn't pull all the events which were producer by producer while consumer was not active. 

- Also we found that once our client disconnect the EventHub server for some minutes and reconnect again. Client can only receive the latest new incoming messages. So we missed the messages incoming to EventHub server during the disconnect time.

**Exception or Stack Trace**
We don't really get an exception, but we do see some errors in our log coming from event hub. Specifically, we get error logs of the following form:

**Expected behaviour**
We would expect the EventProcessorClientBuilder to continue receiving events forever (until stopped). And if it really needs to stop receiving events then it should somehow inform the rest of the program so it can be manually restarted.

**To Reproduce**
We have followed the Microsoft recommended code present here: [https://learn.microsoft.com/en-us/azure/event-hubs/event-hubs-java-get-started-send#receive-events](url)

**Steps to reproduce the behavior:**
Produce around 1 Million events to event hub, once it completed start your consumer application and check if all 1M events are received 

***Code Snippet***

```java
public Consumer<EventBatchContext> PARTITION_PROCESSOR = eventBatchContext -> {
    if (eventBatchContext.getEvents().isEmpty()) {
        log.warn("Received: Empty list 'eventBatchContext.getEvents()' found");
    } else {
        eventBatchContext.getEvents().parallelStream().forEach(eventData -> {
            if (!Objects.isNull(eventData)) {
                processEventData(eventBatchContext, eventData);
            } else {
                log.warn("Received: Null 'eventData' found");
            }
        });
    }

    eventBatchContext.updateCheckpointAsync();
    log.info("BatchEvent checkpointing done");
};

private void processEventData(EventBatchContext eventBatchContext, EventData eventData) {
    Place[] places;
    try {
        log.info("Received: IN: Batch Event listened, partitionId:{}, offset:{}, sequenceNumber:{}",
            eventBatchContext.getPartitionContext().getPartitionId(), eventData.getOffset(),
            eventData.getSequenceNumber());
        places = objectMapper.readValue(eventData.getBodyAsString(), Place[].class);
        var placesList = Arrays.stream(places).collect(Collectors.toList());

        var unprocessedPlace = redisCacheRepository.filterUnprocessedPlaces(placesList);
        if (CollectionUtils.isNotEmpty(unprocessedPlace)) {
            log.info("Unprocessed Places:{}/{} processing started", unprocessedPlace.size(), placesList.size());
            rpRequestHandler.process(null, unprocessedPlace);
        } else {
            log.info("All Places are already processed, fetch next event message");
        }
    } catch (Exception e) {
        log.error("Exception occurred in processing the eventData");
        e.printStackTrace();
    }
}

public static final Consumer<ErrorContext> ERROR_HANDLER = errorContext -> {
    System.out.printf("Error occurred in partition processor for partition %s, %s.%n",
        errorContext.getPartitionContext().getPartitionId(), errorContext.getThrowable());
};
```

**Screenshots**
![image](https://user-images.githubusercontent.com/95751166/198982297-6072a4c5-1952-4bcf-9e4d-bdfa010b282f.png)

**Setup (please complete the following information):**
 - OS: Ubuntu 18.04.6 LTS
 - IDE: IntelliJ
 - Library/Libraries: 
 - Java version: 14
 - Frameworks: Spring Boot

```bash
**- verbose dependency tree (`mvn dependency:tree -Dverbose`)**

`[INFO] --- maven-dependency-plugin:3.2.0:tree (default-cli) @ rpqc-controller ---
[INFO] com.tomtom.openmaps.conflation:rpqc-controller:jar:1.0.0-SNAPSHOT
[INFO] +- com.tomtom.openmaps.opas:places-internal-model:jar:0.281:compile
[INFO] |  \- com.azure:azure-spring-data-cosmos:jar:3.13.1:compile
[INFO] |     \- com.azure:azure-cosmos:jar:4.20.1:compile
[INFO] +- com.azure:azure-messaging-eventhubs:jar:5.14.0:compile
[INFO] |  \- com.azure:azure-core-amqp:jar:2.7.2:compile
[INFO] +- com.azure:azure-messaging-eventhubs-checkpointstore-blob:jar:1.16.0:compile
[INFO] |  \- com.azure:azure-storage-blob:jar:12.20.0:compile
[INFO] |     +- com.azure:azure-core-http-netty:jar:1.12.6:compile
[INFO] |     +- com.azure:azure-storage-common:jar:12.19.0:compile
[INFO] |     \- com.azure:azure-storage-internal-avro:jar:12.5.0:compile
[INFO] \- com.azure:azure-core:jar:1.32.0:compile
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
----------------------------------------------------------`
```

**Comment by joshfree** [comment]
Hi @PalashBangar-TomTom thank you for filing this detailed github issue.  @conniey will follow up shortly.

/cc @Azure/azsdk-sb-java

**Comment by conniey** [comment]
While I'm setting up and trying to run a repro, can you provide some additional information as listed in [Filing GitHub Issues](https://github.com/Azure/azure-sdk-for-java/blob/main/sdk/eventhubs/azure-messaging-eventhubs/TROUBLESHOOTING.md#filing-github-issues)?  It would make debugging easier if we were provided DEBUG logs +/- 10 minutes when it stops.

**Comment by conniey** [comment]
I tried to reproduce this issue, but my application continues to work after receiving 1 000 000 events.  (I received over 9 million events before I stopped my test.)

So being able to provide the information requested here: https://github.com/Azure/azure-sdk-for-java/issues/31839#issuecomment-1301254755 would help.

**Comment by PalashBangar-TomTom** [comment]
I tried this https://github.com/Azure/azure-sdk-for-java/issues/31839#issuecomment-1301277066
But faced the same issue, however when i tried listening messages using EventContext then it worked as expected:

```
processEvent(PARTITION_PROCESSOR_SINGLE)
 
 
// SINGLE EVENT
public Consumer<EventContext> PARTITION_PROCESSOR_SINGLE = eventContext -> {
  eventContext.updateCheckpoint();
  log.info("Received: EventContext checkpointing done");
  if (!Objects.isNull(eventContext.getEventData())) {
    processEventDataOfSinglePlace(eventContext, eventContext.getEventData());
  } else {
    log.warn("Received: Null 'eventData' found");
  }
};
```

**Comment by conniey** [comment]
I'm glad the single event works for you. I could not reproduce the issue you're seeing though, that's why DEBUG logs where this happens along with your repro code (with the updates) is important for root-cause analysis.
