### ISSUE TITLE
Request to update com.google.guava » guava2

### ISSUE THREAD

**Issue by DenisVoloshin** [Azure/azure-sdk-for-java#31842]
**Describe the bug**
Please update the google.guava » guava2	20.0 to 31.1-jre 
the current version has two vulnerabilities

Thanks

**Comment by jeet1995** [comment]
Hi @DenisVoloshin - we have addressed this request as part of the PR here - [PR 31761](https://github.com/Azure/azure-sdk-for-java/pull/31761) and should be released next week - See [CHANGELOG](https://github.com/Azure/azure-sdk-for-java/blob/main/sdk/cosmos/azure-cosmos/CHANGELOG.md).
