### ISSUE TITLE
[QUERY] How do we create VM with trusted lauch security type

### ISSUE THREAD

**Issue by Prudvidhard** [Azure/azure-sdk-for-java#31860]
**Query/Question**
We need to create VMs with [trusted launch security type](https://learn.microsoft.com/en-us/azure/virtual-machines/trusted-launch-portal?tabs=cli%2Cportal2) but we are not able to find security type option while creating VM. How we specify trusted launch security type?
Our code for creating VM
VirtualMachine vm = azureInstance.virtualMachines().define(newVMName).withRegion(region)
.withExistingResourceGroup(rg).withExistingPrimaryNetworkInterface(nic).withSpecializedWindowsGalleryImageVersion("testImage").withOSDiskStorageAccountType(storageAccountType).withOSDiskName(diskName).withOSDiskSizeInGB(size).withSize(vmSize).create();

***Why is this not a Bug or a feature Request?***
Not sure if SDK has support for trusted launch security type

**Setup (please complete the following information if applicable):**
 - IDE: [e.g. IntelliJ]
 - Library/Libraries: azure-resourcemanager:2.14.0
 
 **Information Checklist**
 Kindly make sure that you have added all the following information above and checkoff the required fields otherwise we will treat the issuer as an incomplete report
- [x] Query Added
- [x] Setup information Added

**Comment by weidongxu-microsoft** [comment]
We probably not having it in convenience API.

@XiaofeiCao would you investigate and support it?

**Comment by XiaofeiCao** [comment]
We don't have it now. Will work on supporting the feature.

**Comment by Prudvidhard** [comment]
Thanks. We also need to create gallery image with trusted launch security type. I didnt find this option as well.
Please let us know by when can we expect support for this feature.

GalleryImageInner image = azureInstance
				.virtualMachines()
				.manager()
				.serviceClient()
				.getGalleryImages()
				.createOrUpdate(
						"resourceGroup",
						galleryName,
						vm.name() + "-image",
						new GalleryImageInner()
								.withLocation(vm.innerModel().location())
								.withOsType(OperatingSystemTypes.WINDOWS)
								.withOsState(OperatingSystemStateTypes.SPECIALIZED)
								.withIdentifier(new GalleryImageIdentifier().withPublisher("workspot").withOffer("windows11").withSku("win11-21h2-pro")));

GalleryImageVersionInner imageVersion = azureInstance.virtualMachines().manager().serviceClient().getGalleryImageVersions().createOrUpdate(
				"resourceGroup",
				galleryName,
				vm.name() + "-image",
				"1.0.0",
				new GalleryImageVersionInner()
						.withLocation(vm.innerModel().location())
						.withPublishingProfile(new GalleryImageVersionPublishingProfile())
						.withStorageProfile(new GalleryImageVersionStorageProfile().withOsDiskImage(new GalleryOSDiskImage().withSource(new GalleryArtifactVersionSource().withUri("Path")))));

**Comment by XiaofeiCao** [comment]
@Prudvidhard 

`serviceClient` level code should already support security type for gallery image. You can set it during creation via:
```java
new GalleryImageInner()
  .withFeatures(List.of(new GalleryImageFeature().withName("SecurityType").withValue("TrustedLaunch")))
  .withHyperVGeneration(HyperVGeneration.V2) // "TrustedLaunch" only support V2
```

For convenience layer support on virtual machine security type option, it should be available on our next SDK version 2.21.0, which will be around 11/25.

**Comment by Prudvidhard** [comment]
Thanks @XiaofeiCao

**Comment by XiaofeiCao** [comment]
Hi @Prudvidhard 

azure-resourcemanager-compute 2.21.0 has been released. 

You can find the sample code for creating Trusted Launch VM from Gallery Image here: https://github.com/Azure/azure-sdk-for-java/blob/main/sdk/resourcemanager/azure-resourcemanager-samples/src/main/java/com/azure/resourcemanager/compute/samples/CreateVirtualMachineWithTrustedLaunchFromGalleryImage.java

**Comment by Prudvidhard** [comment]
@XiaofeiCao Thanks.
