### ISSUE TITLE
[BUG] The unit tests of azure-core-metrics-opentelemetry failed when opentelemetry upgradding to 1.19.0

### ISSUE THREAD

**Issue by moarychan** [Azure/azure-sdk-for-java#31886]
**Describe the bug**
Some unit tests of module `azure-core-metrics-opentelemetry` failed in the ci pipeline.

***Exception or Stack Trace***
The below log is from test class `com.azure.core.metrics.opentelemetry.MetricsTests`
```console
io.opentelemetry.sdk.autoconfigure.spi.ConfigurationException: OTLP gRPC Metrics Exporter enabled but opentelemetry-exporter-otlp not found on classpath. Make sure to add it as a dependency to enable this feature.
```

**To Reproduce**
Upgrade to [opentelemetry](io.opentelemetry:opentelemetry-exporter-otlp) to 1.19.0, io.opentelemetry:opentelemetry-sdk-extension-autoconfigure to 1.19.0-alpha.
Or you can run the tests in branch [feature/spring-boot-3](https://github.com/Azure/azure-sdk-for-java/tree/feature/spring-boot-3)

***Code Snippet***
N/A

**Expected behavior**
Compatible with the opentelemetry to 1.19.0 and 1.19.0-alpha.

**Screenshots**
N/A

**Setup (please complete the following information):**
 - OS: [Windows 11]
 - IDE: [IntelliJ]
 - Library/Libraries: [com.azure:azure-core-amqp:current]
 - Java version: [17] 

**Additional context**
N/A

**Information Checklist**
Kindly make sure that you have added all the following information above and checkoff the required fields otherwise we will treat the issuer as an incomplete report
- [x] Bug Description Added
- [x] Repro Steps Added
- [x] Setup information Added

**Comment by moarychan** [comment]
Found this exception in this PR https://github.com/Azure/azure-sdk-for-java/pull/31808 which is based on Spring Boot 3.0.0-RC1.

**Comment by joshfree** [comment]
@lmolkova could you please take a look

**Comment by lmolkova** [comment]
@moarychan  I tried to repro locally and all tests pass for me in [feature/spring-boot-3](https://github.com/Azure/azure-sdk-for-java/tree/feature/spring-boot-3) branch 
Can you point me to the CI run and check if there were indeed metrics tests?


The error log you see (which I'd love to remove, but didn't get to it yet) does not indicate any issue for tests or users.

**Comment by moarychan** [comment]
Hi @lmolkova , the PR just merged, and the ci log is still available, please see the PR comment https://github.com/Azure/azure-sdk-for-java/pull/31808#issuecomment-1297986728
![image](https://user-images.githubusercontent.com/19926623/199636534-bf641dc3-37ea-4f60-82c6-1075e159d8e0.png)
