### ISSUE TITLE
BlobCheckpointStore import issue with latest version of Java

### ISSUE THREAD

**Issue by kondal99** [Azure/azure-sdk-for-java#31888]
**Query/Question**
EventProcessorClient with BlobCheckpointStore is working fine with Java 1.8 version. When I changed to Java compiler version to Java 9 or later version eclipse, it is showing import package dependency issues. Is BlobCheckpointStore  supports only Java 1.8 or lower versions only?

Package Import Error:
**The type com.azure.messaging.eventhubs.checkpointstore.blob.BlobCheckpointStore is not accessible**

![image](https://user-images.githubusercontent.com/6658690/199440322-8ef0c579-7bb6-462d-a986-2bebf1d8be26.png)
![image](https://user-images.githubusercontent.com/6658690/199440467-f0b372f4-d638-4bbe-b1cf-34eea1d98d10.png)

**Setup :**
 - OS: Windows 10
 - IDE: Eclipse
 - Library/Libraries: 
iot-device-client : 2.1.2
azure-messaging-eventhubs: 5.7.0
azure-eventhubs:  3.3.0
azure-messaging-eventhubs-checkpointstore-blob" 1.6.0
 
 **Information Checklist**
 Kindly make sure that you have added all the following information above and checkoff the required fields otherwise we will treat the issuer as an incomplete report
- [ ] Query Added
- [ ] Setup information Added

**Comment by joshfree** [comment]
@conniey could you please follow up with @kondal99 on their github issue?

**Comment by kondal99** [comment]
@conniey Did you get a chance to look into this issue?

**Comment by conniey** [comment]
Sorry for the delayed response, I'll take a look at this now. We haven't changed the visibility of that class.

**Comment by conniey** [comment]
I tried to repro your issue, but I could not. Do you have a project file or repro I can use?

<img width="796" alt="image" src="https://user-images.githubusercontent.com/10136526/201191349-65ca7df1-e0c4-4fcd-8a3e-6c0c26cb6848.png">

My pom.xml
```xml
<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <groupId>org.example</groupId>
    <artifactId>TestDemo</artifactId>
    <version>1.0-SNAPSHOT</version>

    <properties>
        <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
        <project.reporting.outputEncoding>UTF-8</project.reporting.outputEncoding>
        <maven.compiler.source>11</maven.compiler.source>
        <maven.compiler.target>11</maven.compiler.target>
    </properties>

    <dependencies>
        <dependency>
            <groupId>com.microsoft.azure.sdk.iot</groupId>
            <artifactId>iot-device-client</artifactId>
            <version>2.1.2</version>
        </dependency>
        <dependency>
            <groupId>com.azure</groupId>
            <artifactId>azure-messaging-eventhubs</artifactId>
            <version>5.7.0</version>
        </dependency>
        <dependency>
            <groupId>com.microsoft.azure</groupId>
            <artifactId>azure-eventhubs</artifactId>
            <version>3.3.0</version>
        </dependency>
        <dependency>
            <groupId>com.azure</groupId>
            <artifactId>azure-messaging-eventhubs-checkpointstore-blob</artifactId>
            <version>1.6.0</version>
        </dependency>
    </dependencies>
    <build>
        <plugins>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-jar-plugin</artifactId>
                <version>3.2.0</version>
                <configuration>
                    <archive>
                        <manifest>
                            <addClasspath>true</addClasspath>
                            <mainClass>org.example.Program</mainClass>
                        </manifest>
                    </archive>
                </configuration>
            </plugin>
         </plugins>
    </build>
</project>
```
```

**Comment by kondal99** [comment]
Thanks a lot @conniey, It seems issue with my eclipse IDE and It is working fine with newly installed IDE.
