### ISSUE TITLE
[FEATURE REQ] Post the reference doc for SCA 6.0

### ISSUE THREAD

**Issue by moarychan** [Azure/azure-sdk-for-java#31896]
### Context
The final 6.0 version reference doc for Spring Cloud Azure should be available on the Github io.

### Goal
Provide the latest reference doc for 6.0.0 on the Github io, the address is https://microsoft.github.io/spring-cloud-azure/6.0.0-beta.2/reference/html/index.html.
- Update the New in 6.0 doc
- Update the migration doc from Spring Cloud Azure 4.x to 6.0
- Update code snippets
- Update versions

**Comment by stliu** [comment]
@moarychan please change #31895  for *Spring Cloud Azure 6.0 Release*, and use it for all the related task, no  need to create feature request for each task
