### ISSUE TITLE
[FEATURE REQ] Post the MS doc for SCA 6.0 reference doc

### ISSUE THREAD

**Issue by moarychan** [Azure/azure-sdk-for-java#31894]
### Context
Currently, the reference doc of the MS doc site only links the 4.x version for Spring Cloud Azure.

### Goal
Add a new link for the reference doc 6.0 of Spring Cloud Azure, it should be based on version 4.x and sync the changes to reference doc 6.0 in GitHub io.

**Comment by moarychan** [comment]
Update:

6.0 doc support will be added again when the 3.0 version of TOC goes live.

**Comment by stliu** [comment]
closing to avoid meaningless issue
