### ISSUE TITLE
[FEATURE REQ] Spring Cloud Azure 5.0 Release

### ISSUE THREAD

**Issue by moarychan** [Azure/azure-sdk-for-java#31895]
## Context
Spring Cloud Azure 5.0.0 will be based on Spring Boot 3.0.1 and Spring loud 2022.0.0(will be released on Jan 17 2023).

### Prerequisites
- [x] Hide the configuration classes of Spring Cloud Azure Autoconfigure.
- [x] Upgrade to the GA version for Spring Boot(3.0.1) and Spring Cloud(2022.0.0).
- [x] Remove spring-milestones configuration after upgrading to the GA version.
- [x] Bug bash for existing features in Spring Cloud Azure 5.0.
- [x] Public API review

### Post GA
- [x] Make the Spring Cloud Azure 6.0 available on Spring Initializr
  - Update dependency management logic to meet the Spring Cloud Azure 5.0.
     Keep [all the scenarios of Spring Cloud Azure 4.x](https://github.com/Azure/azure-sdk-for-java/issues/28018) have the same user experiences as Spring Cloud Azure 6.x, but except the dependency with **Sleuth**.
 - [x] Update version of 5.0.0 in [spring.io ](https://spring.io/projects/spring-cloud-azure#learn)

**Comment by stliu** [comment]
#32062 we don't need this one, please merge it into this issue

**Comment by saragluna** [comment]
https://github.com/Azure/azure-sdk-for-java/pull/32616, https://github.com/Azure/azure-sdk-for-java/pull/32597, 
https://github.com/Azure/azure-sdk-for-java/pull/32582,
https://github.com/Azure/azure-sdk-for-java/pull/32549,
https://github.com/Azure/azure-sdk-for-java/pull/32514 reduced the public api scope of Spring Cloud Azure 6.x.

**Comment by moarychan** [comment]
We finally decide [not to skip the major version 5.0](https://github.com/Azure/azure-sdk-for-java/pull/32947), because Spring Boot 2.x will not produce new breaking changes, and Spring Cloud Azure should not produce breaking changes for Spring Boot 2.x support.

**Comment by anbusampath** [comment]
> We finally decided [not to skip the major version 5.0](https://github.com/Azure/azure-sdk-for-java/pull/32947),

Nice move to keep the version number consistent.

**Comment by moarychan** [comment]
Now the Spring Cloud Azure 5.0 is available at start.spring.io.

**Comment by anbusampath** [comment]
will https://microsoft.github.io/spring-cloud-azure/current/reference/html/index.html doc get updated as well?

**Comment by fangjian0423** [comment]
hi @anbusampath , please refer [Spring Cloud Azure developer guide](https://learn.microsoft.com/en-us/azure/developer/java/spring-framework/spring-cloud-azure?tabs=maven). This guide is also available for version 5.0(Though the docs says "This article provides developer guidance for Spring Cloud Azure 4.5.0", we are working on update this).
