### ISSUE TITLE
[FEATURE REQ] Bug bash for existing features in SCA 6.0

### ISSUE THREAD

**Issue by moarychan** [Azure/azure-sdk-for-java#31892]
### Context
Prepare the Spring Cloud Azure 6.0 GA, we need to verify the existing features working in Spring Boot 3.0.0 and Spring Cloud 2022.0.0.

### Goal
Go through the below items:
- MS reference doc for 6.0.0 and sync diffs to Github pages.
-  Other getting started doc.

**Comment by stliu** [comment]
@moarychan please change #31895  for *Spring Cloud Azure 6.0 Release*, and use it for all the related task, no  need to create feature request for each task
