### ISSUE TITLE
[FEATURE REQ] Delivery migration doc for an upgrade from SCA 4.x to SCA 6.0

### ISSUE THREAD

**Issue by moarychan** [Azure/azure-sdk-for-java#31893]
### Context
The final 6.0 version reference doc should provide the migration from Spring Cloud Azure 4.x to Spring Cloud Azure 6.0.

### Goal
Post 6.0 migration doc from Spring Cloud Azure, which the tool `spring-boot-migrator` introduction will be a new part to users.

**Comment by stliu** [comment]
closing in favor of #32178
