### ISSUE TITLE
[FEATURE REQ] Support the tools spring-boot-migrator for SCA 6.0 migration

### ISSUE THREAD

**Issue by moarychan** [Azure/azure-sdk-for-java#31891]
**Is your feature request related to a problem? Please describe.**
Provide the tool handling guide for an upgrade from Spring Cloud Azure 4.x to Spring Cloud Azure 6.0, the tool [spring-boot-migrator](https://github.com/spring-projects-experimental/spring-boot-migrator) will be a good choice, and it will avoid mistakes and save time when the developer upgrades to Spring Boot 3.

**Describe the solution you'd like**
A section to introduce this tool usage in the Spring Cloud Azure migration doc for 6.0, it will upgrade the customer application to Spring Cloud Azure 6.0 without any troubles.

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Information Checklist**
Kindly make sure that you have added all the following information above and checkoff the required fields otherwise we will treat the issuer as an incomplete report
- [x] Description Added
- [x] Expected solution specified

**Comment by stliu** [comment]
I'm not sure what this is for, could you work on this first

- [ ] Feature spec review
- [ ] Feature Spec Signoff

it should cover:

1. what's the problem
2. how to solve the problem / or what we provide to customers to resolve the problem
    * a tool?
    * a doc? what's the title and abstract for the doc?

**Comment by stliu** [comment]
and I'm not confused by this one #31893 which seems to provide a migration doc, but in this one's description, it also saying

> Provide the doc support for an upgrade from Spring Cloud Azure 4.x to Spring Cloud Azure 6.0,

**Comment by moarychan** [comment]
I have updated the description.

Since the tool `spring-boot-migrator` still needs to be improved in upgrading Spring Boot 3 support, we will temporarily not support this migration tool in the 6.0 GA version.

**Comment by stliu** [comment]
closing in favor of #32178
