### ISSUE TITLE
[FEATURE REQ] Add reminder on deprecated and non-source-code Azure Spring GitHub repos for relocation

### ISSUE THREAD

**Issue by yiliuTo** [Azure/azure-sdk-for-java#31908]
## Context
There are multiple GitHub repositories for Spring Cloud Azure libraries including those legacy but deprecated ones, sample repos, doc repos and the active source code repo. Currently we need to collect issues from all those separated repos which is not convenient or efficient.

## Goal
Add reminders for developers when they create issues in legacy repos and sample repos to help developers learn that the repo is not the most proper one to file issues in and relocate to our actual source code repo.

## Solution
There are 3 solutions we can do to add reminders:
1. Add reminders in README.md in each repo
2. Add GitHub actions for reminders
3. Modify the issue template for reminders.

**Comment by saragluna** [comment]
- https://github.com/microsoft/spring-cloud-azure
- https://github.com/microsoft/spring-data-cosmosdb

**Comment by Netyyyy** [comment]
Archived the following repos:
- https://github.com/microsoft/azure-spring-boot
- https://github.com/microsoft/spring-cloud-azure
- https://github.com/microsoft/spring-data-cosmosdb
