### ISSUE TITLE
[FEATURE REQ] Update Spring Cloud Azure release process

### ISSUE THREAD

**Issue by moarychan** [Azure/azure-sdk-for-java#31930]
### Context
The current changelog link can only view the current version, not include the newer version, such as the version 6.0.0-beta.2, the linked page will only show change logs for beta 2 and earlier(4.x), but will not show the beta3, even if the beta3 version has been released, it's not user friendly.

For each release version we assume there's a release blog at https://devblogs.microsoft.com/azure-sdk, it will help our users to find some things added or changed, also should add to Github release, such as https://github.com/Azure/azure-sdk-for-java/releases/spring-cloud-azure_6.0.0-beta.2

### Goal
- Simply the file CHANGELOG.md of each sub-project, and review the title `Features Added`, `Breaking Changes` is still required if we link all change logs to the `sdk/spring/CHANGELOG.md`.
- We should always update the commit id (https://github.com/Azure/azure-sdk-for-java/commit/4f0af481662eebd1703a4082eea9a291b76c1608) to the latest one. Then the link will display all release versions.
- We should add a prefix of `CHANGELOG` to `spring/CHANGELOG` to make it less confusing without opening the link.
- Prepare the release note for the GitHub release and release blog at https://devblogs.microsoft.com/azure-sdk
- Update release wiki.

**Comment by saragluna** [comment]
Closing this now, for the `sdk/spring/CHANGELOG.md` includes all the changes of each version already.
