### ISSUE TITLE
[FEATURE REQ] Release SCA 6.0.0-beta.4

### ISSUE THREAD

**Issue by moarychan** [Azure/azure-sdk-for-java#31938]
### Context
If Spring Boot releases the RC2 and Spring Cloud 2022.0.0-RC2, upgrade to the latest RC version for Spring Cloud Azure 6.0.0-beta4.

### Goal
Release Spring Cloud Azure 6.0.0-beta.4.

**Comment by stliu** [comment]
closing to avoid meaningless issue

**Comment by moarychan** [comment]
Updated to the major version `5`, see more from [Spring Cloud Azure 5.0 Release](https://github.com/Azure/azure-sdk-for-java/issues/31895).
