### ISSUE TITLE
[FEATURE REQ] Create feature spec for Azure SQL Server passwordless connection support 

### ISSUE THREAD

**Issue by backwind1233** [Azure/azure-sdk-for-java#31940]
Things we need to figure out or learn about when defining the feature spec for Azure SQL Server password-less connections:

- What is SQL Server
- How is Spring used with SQL Server
- How is MySQL used passwordless with Spring
  - The feature spec of MySQL passwordless
    - If none, how is MySQL passwordless used with Spring 
    - The API of MySQL passwordless
    - The properties of MySQL passwordless

**Comment by saragluna** [comment]
Close in favor of #30315.
