### ISSUE TITLE
Add test container for UT of MySQL passwordless feature

### ISSUE THREAD

**Issue by backwind1233** [Azure/azure-sdk-for-java#31942]
## Context 
Now we have [PasswordlessMySQLIT](https://github.com/Azure/azure-sdk-for-java/blob/main/sdk/spring/spring-cloud-azure-integration-tests/src/test/java/com/azure/spring/cloud/integration/tests/jdbc/mysql/PasswordlessMySQLIT.java) to test our passwordless feature for Azure MySQL single server, but it can't run on local env and it takes a lot of time to run(> 10mins).

With [Testcontainers](https://www.testcontainers.org/) for java, we can create data access layer integration tests and run the tests locally to ensure our code quality.

## Goal
- Use Testcontainers to mock Azure MySQL single server.
- Add test class to test passwordless feature with Testcontainers.

## Design

- Add test class under test folder in spring-cloud-azure-integration-tests.
- In the test class:
  - Use DefaultAzureCredentialBuilder to build DefaultAzureCredential to get token with scopes "https://ossrdbms-aad.database.windows.net/.default".
  - the scopes vary in different Clouds.("Public,UsGov,China")
  - use the token as the password to initialize the test container with mysql.
  - specify the spring.datasourcce.* properties with the test container url.
  

```
  private DockerImageName dockerImageName = DockerImageName.parse("mysql");

    @Container
    public MySQLContainer mySQLContainer = new MySQLContainer(dockerImageName);

    
    @BeforeEach
    void setUp() {
        DefaultAzureCredential build = new DefaultAzureCredentialBuilder().build();
// the scopes vary in different Clouds
        String password = build.getToken(new TokenRequestContext().addScopes("https://ossrdbms-aad.database.windows.net/.default"))
                .block()
                .getToken();
        mySQLContainer.withUsername("passwordless-test")
                      .withPassword(password);
    }

    @Test
    void testMysqlPassword() {
        // add your 
    }

```

**Comment by backwind1233** [comment]
Our own authentication plugin will generate the packet send to MySql Server, 
but with Testcontainers run as MySql Server, it's not able to recognize this package,
it will throw bad handshake exception.

<img width="923" alt="image" src="https://user-images.githubusercontent.com/4465723/203302648-2078b35c-3623-41ca-8c43-1ba41de50b37.png">

**Comment by saragluna** [comment]
Does this have anything to do with SSL?

**Comment by Netyyyy** [comment]
According to the pipeline results, macOS and windows environment doesn't support test container, So do we continue work on this feature skipping macOS and windows environment tests? @saragluna @backwind1233 
https://dev.azure.com/azure-sdk/internal/_build/results?buildId=2035024&view=logs&j=9b2d956e-2d7d-5748-773c-4213a0cc31b4&t=18c6a9f8-d3e2-5c20-8ffa-39c028cee927&l=89
https://dev.azure.com/azure-sdk/internal/_build/results?buildId=2035024&view=logs&j=5fe92c1d-3c25-55b7-1c07-fa5c3c25e91d&t=55c333a2-afdf-54d6-1385-c643b91b3f0b&l=23
![image](https://user-images.githubusercontent.com/92105726/206061062-f75761a9-5989-49b3-be4e-29cb2a5a44ce.png)
![image](https://user-images.githubusercontent.com/92105726/206061439-8c9a2f49-aee6-430a-9e81-b49992cd10b1.png)

**Comment by eddumelendez** [comment]
Hi, testcontainers has an azure pipeline, see [here](https://github.com/testcontainers/testcontainers-java/blob/main/azure-pipelines.yml). Hope this help.

**Comment by saragluna** [comment]
Can we use something like this https://wesome.org/junit-5-conditional-test-execution-operating-system-conditions for conditional on Windows?

**Comment by Netyyyy** [comment]
https://github.com/Azure/azure-sdk-for-java/pull/32570

**Comment by saragluna** [comment]
There's another issue with using the test container. Our authentication plugin's name is `mysql_clear_password`. However, users created in MySQL container are identified with the `mysql_native_passowrd` plugin.

**Comment by eddumelendez** [comment]
Sorry, not that much experience on this but I wonder if the following url param work [authenticationPlugins](https://dev.mysql.com/doc/connector-j/8.0/en/connector-j-connp-props-authentication.html#cj-conn-prop_authenticationPlugins)

`withUrlParam("authenticationPlugins", "com.mysql.cj.protocol.a.authentication.MysqlClearPasswordPlugin")`

LDAP and PAM are provided by the Enterprise Edition :/

**Comment by saragluna** [comment]
Thanks @eddumelendez, seems like the `withUrlParam` is for constructing the JDBC URL, which is for the client configuration.

**Comment by kiview** [comment]
@saragluna, you said:
>  the compatible server plugin for mysql_clear_password are PAM or LDAP, which I think is not available for MySQL test container.

If this is an enterprise edition feature, what is the issue with using an enterprise edition image together with Testcontainers' `MySQLContainer` and following @eddumelendez's suggestion of using `.withConfigurationOverride("somepath/mysql_conf_override")`?

**Comment by saragluna** [comment]
@kiview I don't think there will be an issue using an enterprise edition image (if we are allowed to use it). I haven't tested that and think it would be an option. PR is welcome if you are interested.

**Comment by kiview** [comment]
@saragluna Unfortunately, I don't think there is a publicly available version of the enterprise edition image, the old image was deprecated: https://hub.docker.com/_/mysql-enterprise-server 

It might be possible to put the regular image into an enterprise mode, however, the [docs](https://dev.mysql.com/doc/mysql-installation-excerpt/8.0/en/docker-mysql-getting-started.html) have the following section:
> For users of MySQL Enterprise Edition: A subscription is required to use the Docker images for MySQL Enterprise Edition. Subscriptions work by a Bring Your Own License model; see [How to Buy MySQL Products and Services](https://www.mysql.com/buy-mysql/) for details.

It is only available from [OCR](https://container-registry.oracle.com/ords/f?p=113:10::::::).

**Comment by saragluna** [comment]
@kiview thanks for the update. Seems like we donn't have a feasible solution here.

**Comment by eddumelendez** [comment]
Hi again, I wonder if [Percona](https://hub.docker.com/_/percona) (build on top of MySQL) can help with this https://docs.percona.com/percona-server/8.0/security/pam_plugin.html

**Comment by eddumelendez** [comment]
forgot to mention that Percona is compatible with `MySQLContainer`

```java
var percona = DockerImageName.parse("percona:8.0.32-24").asCompatibleSubstituteFor("mysql")
MySQLContainer mysql = new MysqlContainer(percona);
```

**Comment by Netyyyy** [comment]
@eddumelendez thanks for updating, we will take it into consideration

**Comment by saragluna** [comment]
Hi @eddumelendez, I guess it's possible. The core point is to create a user in the Percona and this user will be identified by auth_pam. In the plugin we developed, it would auth the user with `mysql_clear_password` plugin. I haven't tried it yet, but if we can set up all these, then it is possible.
