### ISSUE TITLE
Provide reference doc about how to support JPMS for Spring libraries

### ISSUE THREAD

**Issue by saragluna** [Azure/azure-sdk-for-java#31944]
In the `azure-sdk-for-java` repo, we need to support JMPS for newly added modules. Some of them require an explicit `module-info.java`, like SDK libraries; some require only `Automatic Module Name`, like Spring Cloud Azure libraries. 

So we'd better provide an internal reference doc to describe what and how-to enable JPMS. See more in #31140.

**Comment by saragluna** [comment]
https://github.com/spring-projects/spring-framework/issues/18079

**Comment by saragluna** [comment]
Provided in [ADO](https://dev.azure.com/azure-spring-integration/spring-integration-private/_wiki/wikis/spring-integration-private.wiki/360/How-to-support-JPMS-for-Spring-Cloud-Azure-library).

**Comment by saragluna** [comment]
Closing this issue now, @Netyyyy, please help complete the doc while you develop the feature.

**Comment by jabrena** [comment]
Hi @saragluna,

https://dev.azure.com/azure-spring-integration/spring-integration-private/_wiki/wikis/spring-integration-private.wiki/360/How-to-support-JPMS-for-Spring-Cloud-Azure-library

could be public this documentation?

Juan Antonio

**Comment by saragluna** [comment]
> Hi @saragluna Xiaolu Dai FTE,
> 
> https://dev.azure.com/azure-spring-integration/spring-integration-private/_wiki/wikis/spring-integration-private.wiki/360/How-to-support-JPMS-for-Spring-Cloud-Azure-library
> 
> could be public this documentation?
> 
> Juan Antonio

Yes, we've put it here https://github.com/Azure/azure-sdk-for-java/wiki/Support-JPMS-for-Spring-Cloud-Azure-Libraries.
