### ISSUE TITLE
[FEATURE REQ] Collect BI Data for Spring on Azure hub page

### ISSUE THREAD

**Issue by fangjian0423** [Azure/azure-sdk-for-java#31945]
## Context

Spring on Azure page will go live in next couple days, we need collect page view and display it in our BI dashboard, this is the [internal work item link](https://dev.azure.com/azure-spring-integration/spring-integration-private/_workitems/edit/1304/).

Also, we need collect Spring Cloud Azure MS Docs page view data.

## Goal

- Display the page view data in BI dashboard.

## Solution

 - [x] #32295
 - [ ] Integrate page view data to our BI dashboard (P1, now no need to integrate to our BI dashboard)
 - [ ] Discuss with all stakeholders how to display the data (all articles or something else) (P1, no need to discuss now)

**Comment by chenrujun** [comment]
The following query can be used to get the Page View (PV) count

<html>
<body>
<span>Execute in [<a href="https://dataexplorer.azure.com/clusters/cgadatamall.westus/databases/CustomerTouchPoint?query=H4sIAAAAAAAAA1WOTUvDQBCG7/0VQy5NofkEe5Ge1IMHQVB7lWl2bFb2o8xOEiz98d1oWtu5DLzzPg9jSODFO2mfnII1KBQSbSmty7rOqiorV4v7mTmX3gRZrmqfqFQ6t+NpvszulmdTZF5xRxtNwwziHGFoiQl++ccIv0cYtiQDkYP0353nF8UN+MEGWgyQGEJ2udUN++C/JG+8TQDj75cGHjqmQlFPxu+Ji2/ssQh71m5XJJM0dNYi6wNBr4MWzw++c7JWzbjSzV/2rBaw/RnFE+VZEY/RNQSKQgNTw2irBaryBHTel1dWAQAA">Web</a>] [<a href="https://cgadatamall.westus.kusto.windows.net/CustomerTouchPoint?query=H4sIAAAAAAAAA1WOTUvDQBCG7/0VQy5NofkEe5Ge1IMHQVB7lWl2bFb2o8xOEiz98d1oWtu5DLzzPg9jSODFO2mfnII1KBQSbSmty7rOqiorV4v7mTmX3gRZrmqfqFQ6t+NpvszulmdTZF5xRxtNwwziHGFoiQl++ccIv0cYtiQDkYP0353nF8UN+MEGWgyQGEJ2udUN++C/JG+8TQDj75cGHjqmQlFPxu+Ji2/ssQh71m5XJJM0dNYi6wNBr4MWzw++c7JWzbjSzV/2rBaw/RnFE+VZEY/RNQSKQgNTw2irBaryBHTel1dWAQAA&web=0">Desktop</a>]</span> [<a href="https://dataexplorer.azure.com/clusters/cgadatamall.westus/databases/CustomerTouchPoint">cluster('cgadatamall.westus.kusto.windows.net').database('CustomerTouchPoint')</a>]<div style="color: #000000;background-color: #fffffe;font-family: Consolas, 'Courier New', monospace;font-weight: normal;font-size: 14px;line-height: 19px;white-space: pre;"><div><span style="color: #000000;">let MonthEnd = datetime(2022-11-06);</span></div><div><span style="color: #000000;">let MonthStart = datetime_add('month',-5,MonthEnd);</span></div><div><span style="color: #000000;">PageView</span></div><div><span style="color: #000000;">&#160; &#160; | where StartDateTime between (MonthStart..MonthEnd)</span></div><div><span style="color: #000000;">&#160; &#160; | where Url has "learn.microsoft.com" and Url has "azure/developer/java/spring/"</span></div><div><span style="color: #000000;">&#160; &#160; | summarize visitorCount=dcount(VisitorId) by Url</span></div><div><span style="color: #000000;">&#160; &#160; | order by visitorCount desc </span></div><div><span style="color: #000000;">&#160; &#160; | limit 10</span></div><br></div><div><br/><br/><header>Table0</header>

Url | visitorCount
-- | --
https://review.learn.microsoft.com/en-us/azure/developer/java/spring/ | 11
https://learn.microsoft.com/en-us/azure/developer/java/spring/ | 8

</div>
</body>
</html>

**Comment by chenrujun** [comment]
Closing this issue. Let's use [ADO](https://dev.azure.com/azure-spring-integration/spring-integration-private/_workitems/edit/1304/) to track this task.
