### ISSUE TITLE
[FEATURE REQ] Spring Cloud Azure Feature List

### ISSUE THREAD

**Issue by fangjian0423** [Azure/azure-sdk-for-java#31968]
### Context

Spring Cloud Azure has lots of features, but there is no feature list.

### Goal

We need a full list of our existing features, because we expect to derive the following things from the feature list:

- Samples
- Docs
- Tests (UT, IT)

Each feature should have an official name, a description, supported scenarios, and the benefits.

**Comment by fangjian0423** [comment]
Check [the docs](https://dev.azure.com/azure-spring-integration/spring-integration-private/_wiki/wikis/spring-integration-private.wiki/392/Spring-Cloud-Azure-Feature-List) on ADO.

**Comment by fangjian0423** [comment]
Close the issue because docs has been written.

**Comment by saragluna** [comment]
Closing this issue for it's outdated.
