### ISSUE TITLE
[QUERY] How to get all active keys with a given name using the SDK

### ISSUE THREAD

**Issue by vtapadia** [Azure/azure-sdk-for-java#31964]
**Query/Question**
While implementing keys, we are running into an issue and wanted to see if you have a solution for this.
While using keys, we are implementing key rotation and expiry. However, a key could be rotated, but still not expired. In our case, for a highly available service requirement, we want to ensure that the keys which are not expired are also retrievable.

With a specific key version, I know I can use it.
But if I only have the name, how can I retrieve all the currently not expired keys and not just the latest one?

***Why is this not a Bug or a feature Request?***
Not sure, it depends on your answer.

**Setup (please complete the following information if applicable):**
 - OS: N/A
 - IDE: IntelliJ
 - Library/Libraries: com.azure:azure-security-keyvault-keys
 
 **Information Checklist**
 Kindly make sure that you have added all the following information above and checkoff the required fields otherwise we will treat the issuer as an incomplete report
- [ ] Query Added
- [ ] Setup information Added

**Comment by vtapadia** [comment]
Any update on this issue, it is a requirement for us to achieve high availability setup so a solution would be highly appreciated.

**Comment by vcolin7** [comment]
Hi @vtapadia, you can list all versions for a key with [`listPropertiesOfKeyVersions()`](https://github.com/Azure/azure-sdk-for-java/blob/e9b867c8d287c21ae3969643184a2d21d148d7c0/sdk/keyvault/azure-security-keyvault-keys/src/main/java/com/azure/security/keyvault/keys/KeyClient.java#L1432) and then iterate through them to check if a specific version has expired. Here is a code sample on how to achieve this:

Sync
```java
PagedIterable<KeyProperties> keyPropertiesOfVersions =  keyClient.listPropertiesOfKeyVersions("");
        
for (KeyProperties keyProperties : keyPropertiesOfVersions) {
    OffsetDateTime expirationDate = keyProperties.getExpiresOn();
    ...
}
```

Async
```java
keyAsyncClient.listPropertiesOfKeyVersions("")
    .subscribe(keyProperties -> {
        OffsetDateTime expirationDate = keyProperties.getExpiresOn();
        ...
    });
```

Let me know if this works for you or if you have any further questions!

**Comment by vtapadia** [comment]
Thanks, this looks promissing.

We will give a try and see if solves the use case.
I hope this does not provides the key versions which are already purged or expired... or it will return all the keys ?

**Comment by vtapadia** [comment]
Verified, this works as expected. Thanks for sharing.
