### ISSUE TITLE
[Blog] Develop a Spring Integration with Azure Storage Queue application using Azure CLI authentication

### ISSUE THREAD

**Issue by fangjian0423** [Azure/azure-sdk-for-java#31974]
Develop a Spring Integration with Azure Storage Queue application using Azure CLI authentication

**Title** Develop a Spring Integration with Azure Storage Queue application using Azure CLI authentication

**Author** @v-yonghuiye

**Description**

Spring Cloud Azure 4.0 has been released. In version 4.0, it supports multiple authentication methods, such as Environment, Managed Identity, Visual Studio Code, Azure CLI, etc. This blog will introduce how to use Azure CLI authentication to develop a Spring Integration with Azure Storage Queue application.

**Outline**:

Use Azure CLI authentication in a Spring Boot app that supports Spring Integration with Azure Queue Storage

1. What is Azure Queue Storage?
2. Prerequisites
3. Provision Azure resources
4. Authenticate using the Azure CLI
5. Create a Spring Integration with Azure Queue Storage app with Spring Initializr
6. Write the code
7. Run and verify
   - Run the app using Maven
   - Verify this app
8. Conclusion
9. Feedback
10. Resources

**Comment by hui1110** [comment]
Created PR: https://github.com/Azure/azure-sdk-blog/pull/316

**Comment by hui1110** [comment]
Use this [issue ](https://github.com/Azure/azure-sdk-blog/issues/317)to track this issue.
