### ISSUE TITLE
[FEATURE REQ] update azure-messaging-webpubsub to 2022-11-01

### ISSUE THREAD

**Issue by weidongxu-microsoft** [Azure/azure-sdk-for-java#31975]
PR https://github.com/Azure/azure-rest-api-specs/pull/20762

* Updated paths:
    * Added one `/api/hubs/{hub}/connections/{connectionId}/groups`
    * Added one query `group` for `/api/hubs/{hub}/:generateToken`
    * Add an OData syntax `filter` to Send* APIs
    * Add a group constraint pattern `^(?!\\s+$)$`. The pattern does not allow the name only containing whitespaces, the previous swagger does not reflect that, but actually, our service does such a check. So it actually behaves the same as the previous constraint. 

Reference JS impl https://github.com/Azure/azure-sdk-for-js/pull/23635

Targeting before Jan.

**Comment by haolingdong-msft** [comment]
webpubsub 1.2.0 released: https://search.maven.org/artifact/com.azure/azure-messaging-webpubsub/1.2.0/jar
