### ISSUE TITLE
ServiceBusAdministrationClient.getTopicExists does not return false, instead returns an exception ResourceNotFoundException

### ISSUE THREAD

**Issue by andrelemos** [Azure/azure-sdk-for-java#31981]
ServiceBusAdministrationClient administrationClient = new ServiceBusAdministrationClientBuilder().connectionString(this.serviceBusProperty.getUri()).buildClient();

        boolean topicExists = administrationClient.getTopicExists(topicName);

This should return false if the topic doesn't exist and returns an exception

**Comment by joshfree** [comment]
Thank you for filing this github issue, @andrelemos.  Could you please provide more information such as the SDK version number that you're hitting this on?

**Comment by ki1729** [comment]
@andrelemos This is a known issue and should be fixed in the next release that should happen by early next at the latest. 
Fix version should be v7.13

**Comment by ki1729** [comment]
Here is the link to the PR with the fix : https://github.com/Azure/azure-sdk-for-java/pull/31804

**Comment by andrelemos** [comment]
> Thank you for filing this github issue, @andrelemos. Could you please provide more information such as the SDK version number that you're hitting this on?

Version 7.12.1
