### ISSUE TITLE
mgmt, verify netty is still on HTTP/1.1

### ISSUE THREAD

**Issue by weidongxu-microsoft** [Azure/azure-sdk-for-java#31999]
Last time I check it is still HTTP/1.1. I might used fiddler.

If possible, also verify that it uses all the connections in pool, when sends concurrent requests (e.g. lots of GET).

It might be hard to fix the behavior in runtime, via live test or else.

**Comment by XiaofeiCao** [comment]
The netty version that we are using is `1.0.23`. According to official doc, it's still 1.1 by default:
https://projectreactor.io/docs/netty/1.0.23/reference/index.html#_http2_2

All connections in connection pool is used, verified here:
https://github.com/XiaofeiCao/azure-client-example/blob/56840c44187ea9623498485f117aba7ec369380a/src/main/java/com/azure/client/examples/CanUseSingleConnectionPoolAndThreadPoolAcrossAzureClients.java#L89-L92
