### ISSUE TITLE
[FEATURE REQ] Adding retry samples for azure-messaging-servicebus

### ISSUE THREAD

**Issue by takmnagaya** [Azure/azure-sdk-for-java#31994]
**Is your feature request related to a problem? Please describe.**
No, this is just a feature request to azure-messaging-servicebus.

According to the README of azure-messaging-servicebus, AmqpRetryOptions can be used for retry.
But since there are no samples or descriptions of retry, I didn't immediately figure out how I could configure the retry.

>If a transient AMQP exception occurs, the client library retries the operation as many times as the **AmqpRetryOptions** allows. Afterwords, the operation fails and an exception is propagated back to the user.
https://github.com/Azure/azure-sdk-for-java/tree/main/sdk/servicebus/azure-messaging-servicebus#amqp-exception

Finally, I found retryOptions method for ServiceBusClientBuilder.

>Sets the retry options for Service Bus clients. If not specified, the default retry options are used.
https://learn.microsoft.com/en-us/java/api/com.azure.messaging.servicebus.servicebusclientbuilder?view=azure-java-stable#com-azure-messaging-servicebus-servicebusclientbuilder-retryoptions(com-azure-core-amqp-amqpretryoptions)

I think it would be easier for customers to understand if the sample or README has a retry setting method.

**Describe the solution you'd like**
For example, I think it's good to add retryOptions to the following sample code.
When searching a text "retry", we can find the sample to use retryOptions and it will help us how we can configure the retry.

https://github.com/Azure/azure-sdk-for-java/blob/main/sdk/servicebus/azure-messaging-servicebus/src/samples/java/com/azure/messaging/servicebus/SendMessageAsyncSample.java

Here is the sample using retryOptions.
```java
        AmqpRetryOptions retryOptions = new AmqpRetryOptions()
        .setMaxRetries(5)
        .setMaxDelay(Duration.ofSeconds(60))
        .setTryTimeout(Duration.ofSeconds(30))
        .setDelay(Duration.ofSeconds(5));

        // Instantiate a client that will be used to call the service.
        ServiceBusSenderClient sender = new ServiceBusClientBuilder()
            .connectionString(connectionString)
            .retryOptions(retryOptions)
            .sender()
            .queueName(queueName)
            .buildClient();
```

**Describe alternatives you've considered**

**Additional context**

**Information Checklist**
Kindly make sure that you have added all the following information above and checkoff the required fields otherwise we will treat the issuer as an incomplete report
- [x] Description Added
- [x] Expected solution specified

**Comment by joshfree** [comment]
Thanks for filing this issue, @takmnagaya!  @ki1729 could you please follow up?

**Comment by ki1729** [comment]
@takmnagaya Thank you for reporting this issue and for the suggestion on the sample! 
This is something we have already added for the release this month. 
Here is the PR for this change which was merged about a week ago - https://github.com/Azure/azure-sdk-for-java/pull/30805

**Comment by takmnagaya** [comment]
Hello @ki1729 
Thank you for checking this suggestion!
I'm surprised to hear changed were added last week! Great!
