### ISSUE TITLE
mgmt, support/example for global/shared connection pool, for multiple client instances

### ISSUE THREAD

**Issue by weidongxu-microsoft** [Azure/azure-sdk-for-java#32000]
A shared HttpClient should do.

Though I am not sure whether we can set the size of connection pool in netty.

**Comment by XiaofeiCao** [comment]
Connection pool can be configured like this:
https://github.com/XiaofeiCao/azure-client-example/blob/dce22bcc1fdf8e27d1681aa929b20821b6ac306c/src/main/java/com/azure/client/examples/CanUseSingleConnectionPoolAndThreadPoolAcrossAzureClients.java#L50-L63

**Comment by JonathanGiles** [comment]
Mentioning @alzimmermsft, so he can weigh in on this discussion also.

**Comment by alzimmermsft** [comment]
> Connection pool can be configured like this: https://github.com/XiaofeiCao/azure-client-example/blob/7fdbc5a4c4a754ce8a773a1d9d460e82f1fd6ac6/src/main/java/com/azure/client/examples/CanUseSingleConnectionPoolAndThreadPoolAcrossAzureClients.java#L43-L54

This looks good to me, I'd also recommend linking out to the official Reactor Netty documentation for defaults.

https://projectreactor.io/docs/netty/release/reference/#_connection_pool_2

**Comment by XiaofeiCao** [comment]
> This looks good to me, I'd also recommend linking out to the official Reactor Netty documentation for defaults.
> 
> https://projectreactor.io/docs/netty/release/reference/#_connection_pool_2

Thanks Alan, added official docs for defaults for both connection pool and thread pool.
