### ISSUE TITLE
mgmt, support/example for global/shared thread pool, for multiple client instances

### ISSUE THREAD

**Issue by weidongxu-microsoft** [Azure/azure-sdk-for-java#32001]
Default thread pool should be https://projectreactor.io/docs/core/release/api/reactor/core/scheduler/Schedulers.html#boundedElastic--

We might able to control the size of the thread pool via control the DEFAULT_BOUNDED_ELASTIC_SIZE.

Note that thread pool size does not mean connection size, as netty is on async (think of ASYNC and select). https://github.com/Azure/azure-sdk-for-java/issues/32000

**Comment by XiaofeiCao** [comment]
Thread pool can be configured like this:
https://github.com/XiaofeiCao/azure-client-example/blob/dce22bcc1fdf8e27d1681aa929b20821b6ac306c/src/main/java/com/azure/client/examples/CanUseSingleConnectionPoolAndThreadPoolAcrossAzureClients.java#L64-L65

**Comment by weidongxu-microsoft** [comment]
Could you make the meaning clear?

Why `CLIENT_COUNT` in pendingAcquireMaxCount? What's it to do with client?

And which is the thread count in `LoopResources`. How should it be configured? 1, 10, 100?

```java
                        .pendingAcquireMaxCount(CLIENT_COUNT)
                        .maxIdleTime(Duration.ofSeconds(20)) // Configures the maximum time for a connection to stay idle to 20 seconds.
                        .maxLifeTime(Duration.ofSeconds(60)) // Configures the maximum time for a connection to stay alive to 60 seconds.
                        .pendingAcquireTimeout(Duration.ofSeconds(10)) // Configures the maximum time for the pending acquire operation to 60 seconds.
                        .evictInBackground(Duration.ofSeconds(120)) // Every two minutes, the connection pool is regularly checked for connections that are applicable for removal.
                        .metrics(true, () -> customMetricsRegistrar) // Enable pool metrics.
                        .build()))
                // Thread pool configuration.
                .eventLoopGroup(LoopResources.create("http-thread-pool", MAX_CONNECTION_POOL_SIZE, CLIENT_COUNT, true).onClient(false))
```

**Comment by XiaofeiCao** [comment]
Updated.

Yes, it seems client count has nothing to do with pending acquire timeout, since one client can make many concurrent calls at the same time.

**Comment by weidongxu-microsoft** [comment]
You might want to set the HttpClient to DefaultAzureCredentialBuilder as well.

**Comment by XiaofeiCao** [comment]
Didn't realize token acquisition happens on different thread pool. Changed.

**Comment by JonathanGiles** [comment]
Mentioning @alzimmermsft, so he can weigh in on this discussion also.

**Comment by weidongxu-microsoft** [comment]
@XiaofeiCao

Could you check the number?

My feeling is connection pool of 10 and thread pool of 100 does not make sense. I would expect larger connection pool but smaller thread pool for ASYNC in Netty.

**Comment by weidongxu-microsoft** [comment]
> Didn't realize token acquisition happens on different thread pool. Changed.

Actually that thread pool maybe ignorable (we can point it out but I am not sure whether we should control it). I guess it is for MSAL?

**Comment by XiaofeiCao** [comment]
> Actually that thread pool maybe ignorable (we can point it out but I am not sure whether we should control it). I guess it is for MSAL?

Yes, it's for MSAL. I guess it's because it doesn't support reactor methods. Commented it out.
