### ISSUE TITLE
[FEATURE REQ] Improve the description of Spring Cloud Azure JMS configuration properties

### ISSUE THREAD

**Issue by yiliuTo** [Azure/azure-sdk-for-java#32038]
## Context
In our docs of `spring-cloud-azure-starter-servicebus-jms` library, there are some unclear introduction of our exposed properties.

1. We expose some AMQP properties including remote url, username and password to allow configuration. However, those properties actually belong to our underlying implementation for the Qpid client. So to expose them for developers may not be a proper choice. Besides, the property description is too short and ambiguas. So in the current stage, we should update the property description to notice developers that these properties are for our underlying usage of qpid clients, which do not need configuration/customization.
2. In our quickstart, we introduce the `idle-timeout` property as a required property. While the function of this property is not clear for our library, besides, it also has a default value. So we should hide it in our quickstart/sample instead of requiring developers to configure it manually.

## Goal
Update our MS doc/reference doc/quickstart/sample to fix the aforementioned issues.

**Comment by saragluna** [comment]
#32465 #32467 have removed the `remote-url`, `username`, and `password` properties.

**Comment by hui1110** [comment]
Created PR: https://github.com/MicrosoftDocs/azure-dev-docs-pr/pull/4023, https://github.com/Azure-Samples/azure-spring-boot-samples/pull/632, https://github.com/MicrosoftDocs/azure-dev-docs-pr/pull/3997

**Comment by hui1110** [comment]
All PRs are closed, now close it.
