### ISSUE TITLE
Clean up dependencies for live / mock testing for client libraries

### ISSUE THREAD

**Issue by JonathanGiles** [Azure/azure-sdk-for-java#3208]
At present, to enable our live / mock tests, we are using two specific versions of azure-mgmt-resources, as this particular management library provided utility classes for live/mock testing that are helpful. Depending on management libraries within the client libraries for testing feels weird, but even worse is the fact that we depend on two different versions, with one being a snapshot.

What I propose is that we isolate the set of classes we use out of azure-mgmt-resources, and add these as classes in either an azure-common-test module, or else as part of azure-common in src/test.

1. We need an `InterceptorManager`. There are two candidates (and we may bring them both in, for track two and track one, respectively):
    1.1 The 'V3' [InterceptorManager](https://github.com/Azure/azure-sdk-for-java/blob/azconfig/applicationconfig/client/src/test/java/com/microsoft/azure/core/InterceptorManager.java)
    1.2 The 'original' [InterceptorManager](https://github.com/Azure/azure-libraries-for-java/blob/v1.3.0/azure-mgmt-resources/src/test/java/com/microsoft/azure/management/resources/core/InterceptorManager.java)

2. We also require [com.microsoft.azure.management.resources.core.TestBase](https://github.com/Azure/azure-libraries-for-java/blob/v1.3.0/azure-mgmt-resources/src/test/java/com/microsoft/azure/management/resources/core/TestBase.java), or an equivalent.

3. As well as [com.microsoft.azure.management.resources.fluentcore.utils.ResourceManagerThrottlingInterceptor](https://github.com/Azure/azure-libraries-for-java/blob/master/azure-mgmt-resources/src/main/java/com/microsoft/azure/management/resources/fluentcore/utils/ResourceManagerThrottlingInterceptor.java)

4. We should transfer relevant [test classes out of the azconfig directory](https://github.com/Azure/azure-sdk-for-java/tree/azconfig/applicationconfig/client/src/test) into this new location.

The ideal outcome out of this would be to entirely drop out dependency on azure-mgmt-resources, and to resolve the dependency version divergence that we create.

**Comment by mayurid** [comment]
@sima-zhu Please work with @conniey on this and help drive this.
// @JonathanGiles

**Comment by sima-zhu** [comment]
Started from the guideline in the description.
1. InterceptionManager initial change has checked in. Looked into the individual sdk libraries who depend on the interceptionManager. And reorganize the necessary part.
2. TestBase initial change has checked in. Same as above.
3. No ResourceManagerThrottlingInterceptor. Need to implement one in test assets.
4. The step has checked in by Connie. No more work needs to be done for now.

**Comment by JonathanGiles** [comment]
The main goal here is to no longer depend on azure-mgmt-resources in any of our client libraries.

**Comment by sima-zhu** [comment]
I will divide the task into two major parts:
1. Keep each client sdk test code as it is. [PR](https://github.com/Azure/azure-sdk-for-java/pull/3465)
2. For each individual client sdk, remove the dependency on azure-mgmt-resources.

**Comment by sima-zhu** [comment]
Sync with Jonathan, we need to make sdk client tests proceed with v3 test framework. 
Cloesed the PR, and work on KeyVault sdk client tests.

**Comment by sima-zhu** [comment]
https://github.com/Azure/azure-sdk-for-java/pull/3472

**Comment by sima-zhu** [comment]
Finished #1, #2, #4
For #3, currently the use case can basically be covered by reactor API(https://www.javacodegeeks.com/2017/09/testing-time-based-reactor-core-streams-virtual-time.html)

We will implement the interceptor if there is use case we need to build up more stuff on the top of the API. 

Same as the ResourceManagerThrottlingInterceptor, we will add more functionalities when they are necessary in track two.  

I will close the issue for now. Please feel free to reopen if any other issue to address.
