### ISSUE TITLE
[QUERY] Get Azure Virtual Hub Effective Routes via Java SDK

### ISSUE THREAD

**Issue by ShuratCode** [Azure/azure-sdk-for-java#32128]
**Query/Question**
Hi, 
I am trying to fetch the effective routes for Azure Virtual Hub via the SDK.
I am using the Java SDK version 2.10
I saw that in `VirtualHubsClient` there is a method called `getEffectiveVirtualHubRoutes`, but the return value is void.
I have also tried the `getEffectiveVirtualHubRoutesWithResponseAsync` method.
With that method, I could find in the response headers the operation URL (I am using this URL to get the effective routes via REST API), but in the SDK I can't get the effective routes.
Can someone please explain to me what am I missing?

***Why is this not a Bug or a feature Request?***
The methods exist in the SDK, and I do not think the void return value is a bug.

**Setup (please complete the following information if applicable):**
 - OS: Windows, Linux
 - IDE: Intellij
 - Library/Libraries: azure-resourcemanager-network:2.10.0
 
 **Information Checklist**
 Kindly make sure that you have added all the following information above and checkoff the required fields otherwise we will treat the issuer as an incomplete report
- [X] Query Added
- [X] Setup information Added

**Comment by joshfree** [comment]
@weidongxu-microsoft could you please help route this?

**Comment by weidongxu-microsoft** [comment]
@ShuratCode 

This appears to be a problem with service REST API spec https://github.com/Azure/azure-rest-api-specs/blob/main/specification/network/resource-manager/Microsoft.Network/stable/2022-07-01/virtualWan.json#L5900-L5913

The response does not contain either the header or body.

At present, you can call following to get the header, then use the header to get the result.
```java
        String url = azure.networks().manager().serviceClient()
            .getVirtualHubs().getEffectiveVirtualHubRoutesWithResponseAsync(...).block()
            .getHeaders().getValue(...);

        VirtualHubRoute virtualHubRoute = azure.networks().manager().httpPipeline().send(new HttpRequest(HttpMethod.GET, url)).block()
            .getBodyAsBinaryData().toObject(VirtualHubRoute.class);
```

However please note that the API is annotated as a long-running operation, the result might not be ready immediately.

Also you might need to tweak to the code.

---

I will contact service to fix their REST API spec. After their fix and a new SDK, it should be retrieved by the "getEffectiveVirtualHubRoutes" method directly.

**Comment by weidongxu-microsoft** [comment]
To NRP, please fix the REST API spec https://github.com/Azure/azure-rest-api-specs/blob/0c90b40/specification/network/resource-manager/Microsoft.Network/stable/2022-07-01/virtualWan.json#L5900-L5913

There is no response body defined. (the API does not have body, but you had to define it for LRO)

**Comment by ShuratCode** [comment]
Thank you @weidongxu-microsoft 
I have succeeded in doing it with the HTTP pipeline and am using a loop to try and collect the complete response.
