### ISSUE TITLE
[BUG] Application for passwordless connections to Azure Event Hubs for Kafka are not working correctly in AKS

### ISSUE THREAD

**Issue by hui1110** [Azure/azure-sdk-for-java#32123]
**Describe the bug**
According to this [migration guide](https://learn.microsoft.com/en-us/azure/developer/java/spring-framework/migrate-kafka-to-passwordless-connection?tabs=azure-portal%2Csign-in-azure-cli%2Cjava-kafka%2Cservice-connector%2Caks-identity%2Cassign-role-service-connector), migrate from traditional authentication methods to a more secure, password-less connection to Kafka with Azure Event Hubs, and deploy the app to AKS. Here is a screenshot of a related log:

![image](https://user-images.githubusercontent.com/58474919/201304813-a89d64dd-59b8-40d5-87e7-56e246e690ea.png)

***Exception or Stack Trace***
Add the exception log and stack trace if available

**To Reproduce**
According to this [migration guide](https://learn.microsoft.com/en-us/azure/developer/java/spring-framework/migrate-kafka-to-passwordless-connection?tabs=azure-portal%2Csign-in-azure-cli%2Cjava-kafka%2Cservice-connector%2Caks-identity%2Cassign-role-service-connector), migrate from traditional authentication methods to a more secure, password-less connection to Kafka with Azure Event Hubs, and deploy the app to AKS, view application logs

***Code Snippet***
Add the code snippet that causes the issue.

**Expected behavior**
Make a passwordless connection to Kafka using Azure Event Hubs and deploy the app to AKS and the app works.

**Screenshots**

**Content (please complete the following information if possible):**

**Additional context**

**Information Checklist**
Kindly make sure that you have added all the following information above and checkoff the required fields otherwise we will treat the issuer as an incomplete report
- [x] Bug Description Added
- [x] Repro Steps Added
- [x] Setup information Added

**Comment by stliu** [comment]
I don't get this issue report, is it a doc issue?

**Comment by hui1110** [comment]
> I don't get this issue report, is it a doc issue?

It's a documentation issue, according to the migration guide, after deploying the app to AKS, it doesn't work.

**Comment by fangjian0423** [comment]
Assign roles to the managed identity with Azure portal doesn't works.

Assign roles to the managed identity with Azure CLI tab works good.

![image](https://user-images.githubusercontent.com/5254035/206909241-15150eb3-e806-4652-8442-e57146e856f7.png)

**Comment by hui1110** [comment]
Use this [PR](https://github.com/MicrosoftDocs/azure-dev-docs-pr/pull/3955) to add tips.

**Comment by hui1110** [comment]
The fix [PR](https://github.com/MicrosoftDocs/azure-dev-docs-pr/pull/3955) has been merged, now close this issue.
