### ISSUE TITLE
[FEATURE REQ]Merge Support

### ISSUE THREAD

**Issue by xinlian12** [Azure/azure-sdk-for-java#32131]
Using this item to track all the PRs related to Merge support. 

## Table of Contents
[Cosmos feed processor in Azure Cosmos DB](https://learn.microsoft.com/en-us/azure/cosmos-db/nosql/change-feed-processor?tabs=dotnet)

- [ChangeFeedProcessor internal implementation]()
- [Public API]()
- [Migration]()
- [Other Changes]()

## ChangeFeedProcessor internal implementation
Based on the lease version SDK use internally, we have `pkversion` and `epkversion`.
- pkversion lease container
  ```
  {
    "id":"TESTDatabaseAccount.documents.azure.com_RxJava.SDKTest.SharedDatabase_20221115T094259_AQi_e45790f7-e0cc-4697-8bc1-d8a95e792a9c.info"
  }
  ```
  ```
  {
    "id":"TESTDatabaseAccount.documents.azure.com_RxJava.SDKTest.SharedDatabase_20221115T094259_AQi_e45790f7-e0cc-4697-8bc1-d8a95e792a9c..0",
    "LeaseToken":"0",
    "ContinuationToken":"\"11\"",
    "timestamp":"2022-11-15T17:43:34.634427Z",
    "Owner":"ZKNjph"
  }
  ```

- epkversion lease container
  ```
  {
    "id":"TESTDatabaseAccount.documents.azure.com_bf8uAA==_bf8uALgoqxk=.info"
  }
  ```
  ```
  {
    "id":"TESTDatabaseAccount.documents.azure.com_RxJava.azure.com_bf8uAA==_bf8uALgoqxk=..-FF",
    "LeaseToken":"-FF",
    "ContinuationToken":"eyJWIjoxLCJSaWQiOiIvZGJzL1J4SmF2YS5TREtUZXN0LlNoYXJlZERhdGFiYXNlXzIwMjIxMTE1VDA5NTI1NV9LWFAvY29sbHMvOGM2NTNmNzUtOTc1OC00NmExLWJlMzItMjFjMDQwZDIzNDVhIiwiTW9kZSI6IklOQ1JFTUVOVEFMIiwiU3RhcnRGcm9tIjp7IlR5cGUiOiJCRUdJTk5JTkcifSwiQ29udGludWF0aW9uIjp7IlYiOjEsIlJpZCI6Ii9kYnMvUnhKYXZhLlNES1Rlc3QuU2hhcmVkRGF0YWJhc2VfMjAyMjExMTVUMDk1MjU1X0tYUC9jb2xscy84YzY1M2Y3NS05NzU4LTQ2YTEtYmUzMi0yMWMwNDBkMjM0NWEiLCJDb250aW51YXRpb24iOlt7InRva2VuIjoiXCIxMVwiIiwicmFuZ2UiOnsibWluIjoiIiwibWF4IjoiRkYifX1dLCJSYW5nZSI6eyJtaW4iOiIiLCJtYXgiOiJGRiIsImlzTWluSW5jbHVzaXZlIjp0cnVlLCJpc01heEluY2x1c2l2ZSI6ZmFsc2V9fX0=",
    "timestamp":"2022-11-15T17:43:34.634427Z",
    "Owner":"ZKNjph",
    "version":1,
    "feedRange":{
      "Range":{
        "min":"",
        "max":"FF",
        "isMinInclusive":true,
        "isMaxInclusive":false
      }
    }
  }
  ```
`"V":1,"Rid":"/dbs/RxJava.SDKTest.SharedDatabase_20221115T095255_KXP/colls/8c653f75-9758-46a1-be32-21c040d2345a","Mode":"INCREMENTAL","StartFrom":{"Type":"BEGINNING"},"Continuation":{"V":1,"Rid":"/dbs/RxJava.SDKTest.SharedDatabase_20221115T095255_KXP/colls/8c653f75-9758-46a1-be32-21c040d2345a","Continuation":[{"token":"\"11\"","range":{"min":"","max":"FF"}}],"Range":{"min":"","max":"FF","isMinInclusive":true,"isMaxInclusive":false}}}`

Major differences between different lease version includes

  | Lease version                          | id                                        | LeaseToken           | ContinuationToken   | track feedRange   |
  | :------------------------------------- | :---------------------------------------- | :------------------- | :------------------ | :---------------- |
  | PARTITION_KEY_BASED_LEASE  (0)         | databaseId & containerId                  | partitionKeyRangeId  | lsn                 | No                |
  | EPK_RANGE_BASED_LEASE  (1)             | databaseResourceId & containerResourceId  | EpkRange             | ChangeFeedState     | Yes               |

Major differences between different change feed internal implementation version includes

  | ChangeFeed processor internal version  | Lease version                             | ChangeFeedMode                 |
  | :------------------------------------- | :---------------------------------------- | :----------------------------- |
  | pkversion                              | PARTITION_KEY_BASED_LEASE                 | Incremental                    |
  | epkversion                             | EPK_RANGE_BASED_LEASE                     | Incremental & FullFidelity     |

## Public API
- `handleChanges(Consumer<List<JsonNode>> consumer)` : targeted for `incremental` change feed mode, use `pkversion` changeFeedProcessor internally
- `handleAllVersionsAndDeletesChanges(Consumer<List<ChangeFeedProcessorItem>> consumer)` : targeted for `full fidelity` change feed mode, use `epkversion` changeFeedProcessor internally

For merge support, we need to use `EPK_RANGE_BASED_LEASE`
- `handleLatestVersionChanges(Consumer<List<JsonNode>> consumer)` : targeted for `incremental` change feed mode, use `epkversion` changeFeedProcessor internally
- Another proposal: `handleLatestVersionChanges(Consumer<List<ChangeFeedProcessorItem>> consumer)`
[ChangeFeedWireFormatDesign](https://microsoft-my.sharepoint.com/:w:/p/mkolt/EYuEz-aOPydMkbWKCO0ThJUBf_3BeewRp5XV91_Swz7ZaA?wdOrigin=TEAMS-ELECTRON.p2p.bim&wdExp=TEAMS-CONTROL&wdhostclicktime=1668711240969&web=1)
>       Should we use the new change feed wire format version

```
      {
          "id" : "23b9a579-2bd8-4cc4-9441-f457084adb44",
           "mypk" : "23b9a579-2bd8-4cc4-9441-f457084adb44",
          "sgmts" : [ [ 6519456, 1471916863 ], [ 2498434, 1455671440 ] ],
           "_rid" : "+8ZSALEqaM8BAAAAAAAAAA==",
           "_self" : "dbs/+8ZSAA==/colls/+8ZSALEqaM8=/docs/+8ZSALEqaM8BAAAAAAAAAA==/",
           "_etag" : "\"6f02ab2f-0000-0700-0000-637684110000\"",
           "_attachments" : "attachments/",
           "_ts" : 1668711441,
           "_lsn" : 2
    }
   {
          "current" : {
            "id" : "b71bf39a-4f76-4626-bac4-9b3e55a483f2",
            "mypk" : "b71bf39a-4f76-4626-bac4-9b3e55a483f2",
            "sgmts" : [ [ 6519456, 1471916863 ], [ 2498434, 1455671440 ] ],
            "_rid" : "I0pAAJK-nJYBAAAAAAAAAA==",
            "_self" : "dbs/I0pAAA==/colls/I0pAAJK-nJY=/docs/I0pAAJK-nJYBAAAAAAAAAA==/",
            "_etag" : "\"8900a8c7-0000-0700-0000-637684ac0000\"",
            "_attachments" : "attachments/",
            "_ts" : 1668711596
         },
        "metadata" : {
          "lsn" : 2,
          "crts" : 1668711596
        }
   }
```

>     Whether we should introduce more dependency on Jackson library

>     Whether we should keep the format consistent between fullFidelity public API contract

>     How do we coordinate with queryChangeFeed public API

## Migration
When customer onboarded to use the new API, the question would be how we resume the processing based on the previous pk version leases.

> Should we anonymous do the migration? Since there is only databaseId/collectionId being tracked in the lease store, so in case a collection being recreated, we will start from the wrong checkpoint

Two processes matters here
- `Bootstrap` - Initialize the lease store, creating all the leases based on the pkRanges
```mermaid
  graph TD
  A[Initialize] --> B{Is lease store initialized?}
  B -- Yes --> C[Finish]
  B -- No -->  D[Acquire Lock]
  D --> E[Create all lease for pkRanges]
  E --> F[Mark lease store initialized]
  F --> C
```
- `Load balancing` - A change feed processor instance can lose a lease due to many reasons, including lease got stolen by other instances, has not been able to review leases successfully etc.
When an instance lose the ownership of a lease, then it will automatically stop further processing. Same could applies to the lease got deleted.
```mermaid
 graph TD
A[Get all leases from lease store] --> B[CategorizeLeases]
B --> C[Calculate workers count from lease store]
C --> D[Calculate expected leases count for the current worker]
D --> E{Any expired lease?}
E -- Yes --> F[Take expired lease]
F --> G[Finish]
E -- No -->H[Stealing lease]
H --> G
```

Proposed migration change
```mermaid
flowchart TD
A[Initialize] --> B{Is lease store initialized?}
B -- Yes --> C[Finish]
B -- No -->  D[Acquire Lock]
D --> E{Pkversion lease store exists?}
E -- YES -->  F[Get all leases from pkversion lease store]
F --> G[Create epkversion leases from pkversion leases]
G --> H[Delete all pkversion leases]
H --> I[Mark lease store initialized]
I --> C
E -- No --> J[Create all leases for pkranges ]
J --> I
```

Another proposal change:
```mermaid
flowchart TD
A[Initialize] --> B{Is lease store initialized?}
B -- Yes --> C[Finish]
B -- No -->  D[Acquire Lock]
D --> E{Pkversion lease store exists?}
E -- YES -->  F[Mark lease store initialized]
F --> C
E -- No --> G[Create all leases for pkranges ]
G --> F
```
```mermaid
 graph TD
A[Get all leases from epk version lease store] --> B[Get all leases from pk version lease store]
B --> C[CategorizeLeases]
C --> D[Calculate workers count from epk lease store]
D --> E[Calculate expected leases count for the current worker]
E --> F{Any expired lease?}
F -- Yes --> G[Take expired lease]
G --> H[Finish]
F -- No -->I[Stealing lease]
I --> H
```

## Possible future checkpoint
```mermaid
graph TD
A[Initialize] --> B{Is lease store initialized?}
B -- Yes --> C{Is lease store initialized from the same checkpoint}
C -- Yes --> D[Finish]
C -- No --> E[Acquire Lock]
E --> F[Delete all existing leases]
F --> G[Delete store initialization file]
G --> H[Release lease store lock ]
H --> A
B -- No --> I[Acquire Lock]
I --> J{Bootstrap source exists?}
J -- Yes --> K[Create epk version leases from checkpoint]
K --> L[Mark lease store initialized]
L --> M[Release lease store lock]
M --> D
J -- No --> N[Create epk version leases from pkRanges]
N --> L
```

## Other Changes
- [SessionTokenAndQueryPipeline](https://github.com/Azure/azure-sdk-for-java/pull/32078)
- [ChangeFeedFetcher](https://github.com/Azure/azure-sdk-for-java/pull/32097)
- [ChangeFeed startTime](https://github.com/Azure/azure-sdk-for-java/pull/32165)
- [ChangeFeed internal implementation refactor](https://github.com/Azure/azure-sdk-for-java/pull/31428)

**Comment by kushagraThapar** [comment]
This is done.
