### ISSUE TITLE
Help customer easier to find Spring on Azure samples

### ISSUE THREAD

**Issue by chenrujun** [Azure/azure-sdk-for-java#32148]
### Context

Customers have a hard time looking for samples about building Spring application with Azure resources.

### Problem
As a customer: 
1. I don't know whether there is a page that can help me to find required **Spring on Azure** samples. 
2. I may search by search engine like google. But the search result didn't provide best solution. 

### Goal

Help customer easier to find Spring on Azure samples

### Solution

- [ ] 1. List all samples in sample browser.
  - [x] 1.1. List all samples. (Scope: In azure-spring-boot-samples repo)
    - [x]  1.1.1. Requirement: Each sample should have Title and description.
  - [x] 1.2. Select valid samples.
    - [x] 1.2.1. Valid sample criteria.
      - [x] 1.2.1.1. It's runnable.
      - [x] 1.2.1.2. Not include pet clinic.
  - [x] 1.3. Investigate the onboard criteria.
    - [x] 1.3.1. Sample experiment. Investigate the onboard criteria.
    - [x] 1.3.2. Whether support advanced features? Not for now.
  - [ ] 1.4. Onboard all sample candidates.
- [ ] 2. Display top n samples on Spring on Azure hub page. Add link to sample browser.
  - [ ] 2.1. List top 10 samples. 
    - [ ] 2.1.1. Question: How to decide top 10?
  - [ ] 2.2. Decide where to display.
  - [ ] 2.3. Display top n samples on Spring on Azure hub page.
- [ ] 3. Display top n samples on Spring Cloud Azure page. Add link to sample browser.
- [ ] 4. Display top n samples on Spring Guides page. Add link to sample browser.
  - [ ] 4.1. How to add our samples in Spring Guides.

**Comment by backwind1233** [comment]
Do you plan to do this in this milestone?

**Comment by chenrujun** [comment]
> Do you plan to do this in this milestone?

Yes. Already mentioned it in the scrum meeting. And already in the project: https://github.com/orgs/Azure/projects/94/views/36

**Comment by backwind1233** [comment]
great, looking forward

**Comment by chenrujun** [comment]
## Azure Spring Apps samples 



| Link to GitHub sample path | owner | front-matter added | sample displayed well in sample browser |
|---|---|---|---|
| [Example: Loading secrets from Azure Key Vault to PropertySource](https://github.com/Azure-Samples/azure-spring-boot-samples/tree/spring-cloud-azure_4.4.1/keyvault/spring-cloud-azure-starter-keyvault-secrets/property-source) | @chenrujun | :white_check_mark: | :white_check_mark:  |
| [Example: Green Blue deploy in Azure Spring Apps](./to_be_done) | unknown | :x: | :x: |
