### ISSUE TITLE
Redesign the TOC and landing page of MS docs of Spring Cloud Azure

### ISSUE THREAD

**Issue by chenrujun** [Azure/azure-sdk-for-java#32147]
### Context

1. MS docs of Spring Cloud Azure: https://learn.microsoft.com/en-us/azure/developer/java/spring-framework/
2. Overview of landing pages: https://review.learn.microsoft.com/en-us/help/platform/navigation-landing-page-overview?branch=main

### Problem
Current page is confusing.
1. Customer may be confused about the TOC: 
![image](https://user-images.githubusercontent.com/13167207/201812889-c3b5f5dd-be8d-49bd-ba99-2c136dd46084.png)

2. Customer may be confused about the landing page:
![image](https://user-images.githubusercontent.com/13167207/201813055-272ebd0c-6d26-480e-b8b5-781eb8aa4694.png)

### Goal
Update current TOC and landing page. Make them more reasonable, make them scenario based. For example:

 - Getting Started Guides -- Spring Cloud -- Azure Event Hubs
 - Getting Started Guides -- Messaging -- Messaging with Azure Event Hubs
 - Getting started guides -- spring boot -- azure storage 
 - Getting started guides -- storage -- uploading files to azure storage blob

**Comment by stliu** [comment]
## First task:

Improve Toc / Reference

### main tasks

1. split appendix section
2. ignore migration for now
3. correct link

## Reference

Current:
* Spring Cloud Azure reference
* Spring Cloud Azure reference appendix
* Spring Framework --> https://spring.io
* Learn Spring --> https://spring.io/guides
* Spring Boot --> https://spring.io/projects/spring-boot/
* Spring Project References --> https://spring.io/projects

Changed:

* Spring Cloud Azure reference
* Application Properties
	* Common Properties --> https://learn.microsoft.com/en-us/azure/developer/java/spring-framework/spring-cloud-azure-appendix#global-properties
	*  [Azure Active Directory properties](https://learn.microsoft.com/en-us/azure/developer/java/spring-framework/spring-cloud-azure-appendix#azure-active-directory-properties)
	-   [Azure Active Directory B2C properties](https://learn.microsoft.com/en-us/azure/developer/java/spring-framework/spring-cloud-azure-appendix#azure-active-directory-b2c-properties)
	-   [Azure App Configuration properties](https://learn.microsoft.com/en-us/azure/developer/java/spring-framework/spring-cloud-azure-appendix#azure-app-configuration-properties)
	-   [Azure Cosmos DB properties](https://learn.microsoft.com/en-us/azure/developer/java/spring-framework/spring-cloud-azure-appendix#azure-cosmos-db-properties)
	-   [Azure Event Hubs properties](https://learn.microsoft.com/en-us/azure/developer/java/spring-framework/spring-cloud-azure-appendix#azure-event-hubs-properties)
	-   [Azure Key Vault properties](https://learn.microsoft.com/en-us/azure/developer/java/spring-framework/spring-cloud-azure-appendix#azure-key-vault-properties)
	-   [Azure Key Vault Secrets properties](https://learn.microsoft.com/en-us/azure/developer/java/spring-framework/spring-cloud-azure-appendix#azure-key-vault-secrets-properties)
	-   [Azure Key Vault Certificates properties](https://learn.microsoft.com/en-us/azure/developer/java/spring-framework/spring-cloud-azure-appendix#azure-key-vault-certificates-properties)
	-   [Azure Service Bus properties](https://learn.microsoft.com/en-us/azure/developer/java/spring-framework/spring-cloud-azure-appendix#azure-service-bus-properties)
	-   [Azure Service Bus JMS properties](https://learn.microsoft.com/en-us/azure/developer/java/spring-framework/spring-cloud-azure-appendix#azure-service-bus-jms-properties)
	-   [Azure Storage properties](https://learn.microsoft.com/en-us/azure/developer/java/spring-framework/spring-cloud-azure-appendix#azure-storage-properties)
	-   [Azure Storage Blob properties](https://learn.microsoft.com/en-us/azure/developer/java/spring-framework/spring-cloud-azure-appendix#azure-storage-blob-properties)
	-   [Azure Storage File Share properties](https://learn.microsoft.com/en-us/azure/developer/java/spring-framework/spring-cloud-azure-appendix#azure-storage-file-share-properties)
	-   [Azure Storage Queue properties](https://learn.microsoft.com/en-us/azure/developer/java/spring-framework/spring-cloud-azure-appendix#azure-storage-queue-properties)
- Spring Cloud Auzre on Spriong IO --> https://spring.io/projects/spring-cloud-azure
- StackOverflow --> https://stackoverflow.com/questions/tagged/spring-cloud-azure
- GitHub Source Code --> https://github.com/Azure/azure-sdk-for-java/tree/main/sdk/spring
* Spring Guides --> https://spring.io/guides
* Spring Initializr --> https://start.spring.io/
* Spring Projects --> https://spring.io/projects
* Spring Boot --> https://spring.io/projects/spring-boot/
* Spring Framework --> https://spring.io/projects/spring-framework

**Comment by stliu** [comment]
## Improve ToC / Getting started

## Getting Started Guides
* [Overview](https://learn.microsoft.com/en-us/azure/developer/java/spring-framework/spring-boot-starters-for-azure)
	* NOTE: the article title should be change to 'Spring Cloud Azure Overview', keep the content as it is for now.
* Storage
	* [Uploading File to Azure Storage Blob](https://learn.microsoft.com/en-us/azure/developer/java/spring-framework/configure-spring-boot-starter-java-app-with-azure-storage)
		* NOTE: the article title should also be changed to this one from 'How to use the Spring Boot Starter for Azure Storage'
* Security
	* Secret Management
		* [Load secret from Azure KeyVault Secret](https://learn.microsoft.com/en-us/azure/developer/java/spring-framework/configure-spring-boot-starter-java-app-with-azure-key-vault)
			* NOTE: the article title should be changed to this one from 'Tutorial: Read a secret from Azure Key Vault in a Spring Boot application'
	* HTTPS / TLS
		* [Enable HTTPS in Spring Boot with Azure KeyVault Certificates](https://learn.microsoft.com/en-us/azure/developer/java/spring-framework/configure-spring-boot-starter-java-app-with-azure-key-vault-certificates)
	* Authentication and Authorization
		* [Secure REST API using Spring Security 5 and Azure Active Directory](https://learn.microsoft.com/en-us/azure/developer/java/spring-framework/configure-spring-boot-starter-java-app-with-azure-active-directory)
			* NOTE: change the article title to this, also change the first paragraph of this article
				* In this tutorial, you learn how to:
					-   Create a Java application using the Spring Initializr
					-   Configure Azure Active Directory
					-   Secure the application with Spring Boot classes and annotations
					-   Build and test your Java application
				- **NOTE: no one is expecting to learn how to create a spring application using spring initializr from this doc**
				- Just say what is goal of this doc
		* [Enable OIDC login in Spring by Azure Active Directory B2C](https://learn.microsoft.com/en-us/azure/developer/java/spring-framework/configure-spring-boot-starter-java-app-with-azure-active-directory-b2c-oidc)
		* [Azure Active Directory Dev Guide](https://learn.microsoft.com/en-us/azure/developer/java/spring-framework/spring-boot-starter-for-azure-active-directory-developer-guide)
				
* Messaging
	* JMS
		* [Using JMS in Spring to access Azure Service Bus](https://learn.microsoft.com/en-us/azure/developer/java/spring-framework/configure-spring-boot-starter-java-app-with-azure-service-bus)
			* NOTE: also change article title
	* [Spring Cloud Stream with Azure Event Hubs](https://learn.microsoft.com/en-us/azure/developer/java/spring-framework/configure-spring-cloud-stream-binder-java-app-azure-event-hub)
	* [Spring Cloud Stream with Azure Service Bus](https://learn.microsoft.com/en-us/azure/developer/java/spring-framework/configure-spring-cloud-stream-binder-java-app-with-service-bus)
	* [Using Spring Kafka with Azure Event Hubs for Kafka API](https://learn.microsoft.com/en-us/azure/developer/java/spring-framework/configure-spring-cloud-stream-binder-java-app-kafka-azure-event-hub?tabs=passwordless)
	* 
* Database
	* NoSQL - Azure Cosmos DB
		* [Azure Cosmos DB Dev Guide](https://learn.microsoft.com/en-us/azure/developer/java/spring-framework/how-to-guides-spring-data-cosmosdb)
		* [Accessing Data with Azure Cosmos DB NO SQL API](https://learn.microsoft.com/en-us/azure/developer/java/spring-framework/configure-spring-boot-starter-java-app-with-cosmos-db)
		* [Azure Cosmos DB with App Service on Linux](https://learn.microsoft.com/en-us/azure/developer/java/spring-framework/configure-spring-app-with-cosmos-db-on-app-service-linux)
		* [Using Spring Data with Azure Cosmos DB for Apache Cassandra API](https://learn.microsoft.com/en-us/azure/developer/java/spring-framework/configure-spring-data-apache-cassandra-with-cosmos-db)
		* [Using Spring Data with Azure Cosmos DB for MongoDB API](https://learn.microsoft.com/en-us/azure/developer/java/spring-framework/configure-spring-data-mongodb-with-cosmos-db)
	 * JDBC
		 * [JDBC with Azure MySQL](https://learn.microsoft.com/en-us/azure/developer/java/spring-framework/configure-spring-data-jdbc-with-azure-mysql?tabs=passwordless)
		 * [JDBC with Azure PostgreSQL](https://learn.microsoft.com/en-us/azure/developer/java/spring-framework/configure-spring-data-jdbc-with-azure-postgresql?tabs=passwordless)
		 * [JDBC with Azure SQL Server](https://learn.microsoft.com/en-us/azure/developer/java/spring-framework/configure-spring-data-jdbc-with-azure-sql-server)
	 * JPA
		 * NOTE: more the three JPA getting started here
	 * R2DBC
		 * NOTE: more the three R2DBC getting started here
 * Caching
	 * [Using Azure Redis Cache in Spring](https://learn.microsoft.com/en-us/azure/developer/java/spring-framework/configure-spring-boot-initializer-java-app-with-redis-cache)
		 * NOTE: also change the article title
 * Configuration Management
	 * [Externalize configuration properties to Azure App Configuration](https://learn.microsoft.com/en-us/azure/azure-app-configuration/quickstart-java-spring-app?toc=%2Fazure%2Fdeveloper%2Fjava%2Fspring-framework%2Ftoc.json&bc=%2Fazure%2Fdeveloper%2Fjava%2Fspring-framework%2Fbreadcrumb%2Ftoc.json)
	 * [Using Dyanmic Configuration](https://learn.microsoft.com/en-us/azure/azure-app-configuration/enable-dynamic-configuration-java-spring-app?toc=%2Fazure%2Fdeveloper%2Fjava%2Fspring-framework%2Ftoc.json&bc=%2Fazure%2Fdeveloper%2Fjava%2Fspring-framework%2Fbreadcrumb%2Ftoc.json)
	 * [Add Feature Flags](https://learn.microsoft.com/en-us/azure/azure-app-configuration/quickstart-feature-flag-spring-boot?toc=%2Fazure%2Fdeveloper%2Fjava%2Fspring-framework%2Ftoc.json&bc=%2Fazure%2Fdeveloper%2Fjava%2Fspring-framework%2Fbreadcrumb%2Ftoc.json&tabs=windowscommandprompt)
	 * [Use Feature Flags](https://learn.microsoft.com/en-us/azure/azure-app-configuration/use-feature-flags-spring-boot?toc=%2Fazure%2Fdeveloper%2Fjava%2Fspring-framework%2Ftoc.json&bc=%2Fazure%2Fdeveloper%2Fjava%2Fspring-framework%2Fbreadcrumb%2Ftoc.json)
	 * [Use Key Vault References](https://learn.microsoft.com/en-us/azure/azure-app-configuration/use-key-vault-references-spring-boot?toc=%2Fazure%2Fdeveloper%2Fjava%2Fspring-framework%2Ftoc.json&bc=%2Fazure%2Fdeveloper%2Fjava%2Fspring-framework%2Fbreadcrumb%2Ftoc.json)
* Serverless
	* [Spring Cloud Function in Azure](https://learn.microsoft.com/en-us/azure/developer/java/spring-framework/getting-started-with-spring-cloud-function-in-azure)

**Comment by stliu** [comment]
## task improve toc/samples

current
* spring cloud azure samples
* Spring initializr

changed to

* spring cloud azure samples

**Comment by chenrujun** [comment]
## New design of Spring Cloud Azure landing page:

# Note: The number in () is the page view in 2022-12
 - Spring Cloud Azure documentation (1326)
    - Overview
      - Spring Cloud Azure Overview (1072, it's the PV is old page, new page is WIP)
      - Azure for Spring Developers (22)
    - Security
      - Secure REST API Using Spring Security and Azure AD (4455)
      - Spring Security Support (4614)
      - Load a secret from Azure Key Vault (3148)
      - Enable OIDC sign in for Spring with Azure AD B2C (1169)
      - Enable HTTPS in Spring Boot with Azure Key Vault certificates (717)
      - Access a database without passwords in Spring (313)
      - Migrate to use passwordless connections - Azure PostgreSQL (280)
      - Migrate to use passwordless connections = Azure MySQL (124)
      - Migrate to use passwordless connections = Azure SQL Database (123)
    - Storage
      - Upload a file to Azure Storage Blob (2772)
    - Messaging
      - Using JMS to Access Azure Service Bus (2330)
      - Spring Cloud Stream with Azure Event Hubs (1619)
      - Spring Cloud Stream with Azure Service Bus (1059)
      - Use Spring Kafka with Azure Event Hubs for Kafka API (583)
    - Serverless
      - Spring Cloud Function in Azure (1253)
    - Database
      - Accessing data with Azure Cosmos DB NoSQL API (1214)
      - Azure Cosmos DB Dev Guide (1010. This page will be moved into "Developer Guide")
      - Use Spring Data with Azure Cosmos DB for MongoDB API (269)
      - Use Spring Data with Azure Cosmos DB for Apache Cassandra API (73)
      - JDBC with Azure SQL Server (1074)
      - JDBC with Azure PostgreSQL (494)
      - JDBC with Azure MySQL (258)
      - JPA with Azure SQL Database (627)
      - JPA with Azure MySQL (412)
      - JPA with Azure PostgreSQL (232)
      - R2DBC with Azure PostgreSQL (282)
      - R2DBC with Azure SQL Server (243)
      - R2DBC with Azure MySQL (198)
    - Caching
      - Use Azure Redis Cache in Spring (702)
    - Configuration Management
      - Externalize configuration properties to Azure App Configuration (760)
      - Use Key Vault references (543)
      - Use feature flags (440)
      - Add feature flags (245)
      - Use dynamic configuration (142) 
    - Developer Guide (1938, not display this page in new landing page, because we are spliting this page now.)

**Comment by chenrujun** [comment]
- [ ]  Created PR to update landing page: https://github.com/MicrosoftDocs/azure-dev-docs-pr/pull/4022
 - [ ]  PR to update the developer guide directory structure: https://github.com/MicrosoftDocs/azure-dev-docs-pr/pull/3994

**Comment by chenrujun** [comment]
Closing this issue because all related PRs have been merged.
