### ISSUE TITLE
[FEATURE REQ] Add server-side timeout functionality

### ISSUE THREAD

**Issue by ibrahimrabab** [Azure/azure-sdk-for-java#32142]
Java SDK only supports adding timeouts on client side, but not server side. We need to be able to add built-in functionality to be able to pass timeouts on server side as seen in the REST docs,
[https://learn.microsoft.com/en-us/rest/api/storageservices/setting-timeouts-for-blob-service-operations](https://learn.microsoft.com/en-us/rest/api/storageservices/setting-timeouts-for-blob-service-operations)

**Comment by schoag-msft** [comment]
This would be great functionality to have. Can we also document a sample that shows how to inject URI parameters using `HttpPipelinePolicy` overrides for other URI parameters we might not have coverage for on a given REST API call?
