### ISSUE TITLE
[Service Bus Admin Client] Update swagger.json and use latest autorest version to re-generate

### ISSUE THREAD

**Issue by liukun-msft** [Azure/azure-sdk-for-java#32149]
Since swagger.json is missing and we rewrite a new swagger.json based on the old version, some generated contents are not consistent with the current models (about 56 files are modified). we need to keep updating swagger.json. We also need to use the latest autorest version to regenerate.

**Comment by conniey** [comment]
Resolved by https://github.com/Azure/azure-sdk-for-java/pull/34230
