### ISSUE TITLE
Able to restore Azure blob even after number of days in Enable soft delete for blobs passes

### ISSUE THREAD

**Issue by DhavalChauhanTR** [Azure/azure-sdk-for-java#32159]
Hi Team
I am able to restore Azure soft deleted blobs even after number of days set in Enable soft delete for blobs passed.
Below screen shot shows the portal configuration .
![Portal configuration](https://user-images.githubusercontent.com/90746374/201888327-5f6072cc-abbc-4b3d-bc84-1e3ef8c91d64.JPG)

And we are using deleteWithResponse method to delete the blob pls refer the code snippet.
`				Response<Void> deleteResponse = blobClient.deleteWithResponse(DeleteSnapshotsOptionType.INCLUDE,null,null, null);
`

Please let me know if any configuration I am missing.
@gapra-msft @alzimmermsft @kasobol-msft

**Comment by alzimmermsft** [comment]
@ibrahimrabab @jaschrep-msft could you follow up as I know less about the service side configurations and how they effect SDK behaviors

**Comment by ibrahimrabab** [comment]
Hi @DhavalChauhanTR 

Thank you for reaching out. Unfortunately, this seems like an issue with storage retention configuration behaving incorrectly, which is out of our hands. Please file a support ticket against the service via the Azure Portal, and someone on the service side should help.

You can find the support ticket section by going to the **Help + Support** and then clicking **Create new support request**.

Let us know if you have any additional questions.
