### ISSUE TITLE
[BUG]: feedResponseDiagnostics needs to be set for readMany

### ISSUE THREAD

**Issue by jeet1995** [Azure/azure-sdk-for-java#32161]
The `feedResponseDiagnostics` property in the `cosmosDiagnostics` property needs to be set for `FeedResponse` instance returned by the `readMany` API. Due to `feedResponseDiagnostics` not being set, `queryMetricsMap` and `clientSideRequestStatisticsList` (includes `activityId`) are not set as well.

**Comment by FabianMeiswinkel** [comment]
@mkrueger  - please check first whether this is still an issue

**Comment by mkrueger** [comment]
As far as I can see that should've been fixed by this commit:

https://github.com/Azure/azure-sdk-for-java/commit/56804dc104bbf5fe0a641332e0758fe25512d50b

Note: queryMetricsMap and clientSideRequestStatisticsList should be set as well.

Reopen if that is still an issue.
