### ISSUE TITLE
[BUG]Merge:  Change Feed with Start Time

### ISSUE THREAD

**Issue by xinlian12** [Azure/azure-sdk-for-java#32164]
**Scenario:**
When a merge happens, the child partition will contain documents ordered by LSN but the _ts / creation time of those documents might not be sequential. So when reading the Change Feed by LSN, you can encounter documents with a lower _ts. This becomes problematic when a user consumes the Change Feed using Start Time because:

 The first request sends the desired Start Time.
Backend calculates an LSN and returns to the client
Client uses that LSN moving forward.
Because of the previous merge, potentially can receive documents that happened after the Start Time because they have higher LSN than returned in step 2.
 
This only impacts Change Feed Processor and Change Feed Query/Pull model that are started after a merge happened in a partition, not running ones, because when a Partition is merged we currently apply EPK filtering, and with that filtering, we would not get documents from the other parent Partition that could be out of time.

**Design:**
- Modifying the SDK code that performs Change Feed requests to send the new header obtained from the current continuation/lease

**Comment by kushagraThapar** [comment]
This is done.
