### ISSUE TITLE
Passwordless migration guide improvement

### ISSUE THREAD

**Issue by chenrujun** [Azure/azure-sdk-for-java#32185]
### Context

1. I found some problems about current passwordless migration guide.

2. Links about passwordless migration guide. 

    - https://learn.microsoft.com/en-us/azure/storage/common/migrate-azure-credentials
    - https://learn.microsoft.com/en-us/azure/developer/java/spring-framework/migrate-mysql-to-passwordless-connection
    - https://learn.microsoft.com/en-us/azure/developer/java/spring-framework/migrate-postgresql-to-passwordless-connection
    - https://learn.microsoft.com/en-us/azure/developer/java/spring-framework/migrate-kafka-to-passwordless-connection
    - https://learn.microsoft.com/en-us/azure/developer/java/spring-framework/migrate-sql-database-to-passwordless-connection
    - https://learn.microsoft.com/en-us/azure/developer/intro/passwordless-overview

### Problems

1. Same contents appeared in many places. For example: "Assign the managed identity using the Azure portal" appeared in all above links. If someone updated one page, it's error-prone to miss some other places.
2. The migration guide is too long. When a customer is in the middle of the whole doc, it's easy to lose himself. Because:
    - The TOC on the up-right corner will not scroll when customer scrolled the document. 
    - The TOC only has one level, but the document has multiple levels. In the middle of the current document, it's hard to know whether a title is level-2 title or level-3 title.
3. There are different tabs, which may confuse customers.
    - Tab change together not worked. I know that MS docs provide this feature: If one page have multi tabs, after customer chooses value in one tab, all tabs in the same page will choose the same tab value (Here is a [link to a page with this feature works](https://learn.microsoft.com/en-us/azure/storage/common/storage-account-create?toc=%2Fazure%2Fstorage%2Fblobs%2Ftoc.json&tabs=bicep).). This feature is broken in the current migration guide page.
    - Some items in one tab are not brother relationship, put them in one tab window may confuse customers. For example: In tab 5, Service Connector and Azure portal are not brother relationship. Same in Tab 3.

### Goal
Solve above problems.

**Comment by backwind1233** [comment]
Hi @chenrujun Is there a place where I can find all the documentations?

**Comment by chenrujun** [comment]
> Hi @chenrujun Is there a place where I can find all the documentations?

Do you mean this: https://github.com/Azure/azure-sdk-for-java/issues/32185#issuecomment-1317939807

I have listed all links about passwordless in the issue description.

**Comment by backwind1233** [comment]
Yes, I think it's just what I want. Thanks.

**Comment by chenrujun** [comment]
After a meeting with content team (Karl). He will handle these problems.

Here is the meeting note from Karl:

> What we agreed is that, through December, Scott will take a look at the migration articles and look for opportunities to consolidate identical content into include files. Part of this assessment will be to identify complications such as text blocks that are identical except for small differences (such as product names, header numbering, etc.). Then, in January, we will refactor the content using include files.
> 
> Additionally, we’ll assess the content for improvements around header numbering. We tentatively agreed that it would probably be best to number only sections that are procedural in nature, and not number anything that isn’t a clear step in a procedure. Ideally, H2 would not be numbered, and H3 and lower might be numbered. The thinking here is that the numbering of H3/H4/etc. will help distinguish heading levels. If necessary, we can use numbering such as 1.1 etc. We should also look at the numbering that is currently present in some articles and see if that makes things clear. If there is solid precedence, then we can apply similar numbering across the content set. We’ll do that work in January as well.
> 
> After we do a first round of consolidation and header fixes, we can do a usability study (perhaps in February) and determine whether the current structure works for our customers, or whether we should break the content into smaller pieces. Keeping in mind that the articles should be sized so that one article = one task, we can determine what a natural breakdown would look like.

Closing this issue because we do not need to do anything.
