### ISSUE TITLE
[BUG] BatchBlobClient does not delete blob versions

### ISSUE THREAD

**Issue by dk823832** [Azure/azure-sdk-for-java#32186]
**Describe the bug**
Using BatchBlobClient to delete blob versions does not work.

***Exception or Stack Trace***
The error returned is:
<Error><Code>BlobNotFound</Code><Message>The specified blob does not exist.RequestId:39c8943f-901e-0055-528c-f9f1e61e89d2Time:2022-11-16T07:26:12.9477150Z</Message></Error>

**To Reproduce**
See code snippet below. The code uploads a blob and then deletes it. This operations deletes blob's current version however the version that was created by upload operations remains on cloud. It then submits a batch operation to delete the blob version that was created by upload operation. The batch operation fails. Before executing the code it is expected that you fill in the following information in the code:
- accountName: name of the existing storage account with enabled blob versioning
- accountKey: secret key to access the above mentioned storage account
- containerName: name of the existing container created in the storage account mentioned above

***Code Snippet***
```java
String accountName = "";
String accountKey = "";
String containerName = "";.
StorageSharedKeyCredential storageSharedKeyCredential = new StorageSharedKeyCredential(accountName, accountKey);

String endPoint = String.format("https://%s.blob.core.windows.net", accountName);

BlobServiceClient serviceClient = new BlobServiceClientBuilder()
    .endpoint(endPoint)
    .credential(storageSharedKeyCredential)
    .buildClient();

BlobContainerClient containerClient = serviceClient.getBlobContainerClient(containerName);
BlockBlobClient blobClient = containerClient.getBlobClient("batchdel").getBlockBlobClient();
String content = "123456";
BlockBlobItem uploadedBlob = blobClient.upload(new ByteArrayInputStream(content.getBytes()), content.length());
System.out.printf(">>>> uploaded blob version: %s%n", uploadedBlob.getVersionId());

String url = containerClient.getBlobVersionClient(blobClient.getBlobName(), uploadedBlob.getVersionId()).getBlobUrl();
System.out.printf(">>>> url for batch delete: %s%n", url);

// delete the blob so it no longer has current version
blobClient.delete();

List<String> blobUrls = new LinkedList<>();
blobUrls.add(url);

BlobBatchClient blobBatchClient = new BlobBatchClientBuilder(c).buildClient();

try {
    PagedIterable<Response<Void>> responseList = blobBatchClient.deleteBlobs(blobUrls, DeleteSnapshotsOptionType.INCLUDE);
    for (Response<Void> response : responseList) {
        if (response.getStatusCode() >= 200 && response.getStatusCode() < 300) {
            blobUrls.remove(response.getRequest().getUrl().toString());
        }
        else {
            System.err.printf(">>>> request for %s failed with status code %d%n",
                    response.getRequest().getUrl(), response.getStatusCode());
        }
    }
}
catch (BlobBatchStorageException be) {
    System.err.printf(">>>> batch storage exception: %s%n", be.getMessage());
}
catch (Exception e) {
    System.out.printf(">>>> exception: %s%n", ExceptionUtils.getMessage(e));
}
```

**Expected behavior**
It should be possible to delete versioned blobs using BatchBlobClient.

**Screenshots**
N/A.

**Setup (please complete the following information):**
 - OS: Linux
 - IDE:  IntelliJ IDEA
 - Library/Libraries: azure-storage-blob-12.16.1 azure-storage-blob-batch-12.12..2 azure-storage-blob-12.20.0 azure-storage-blob-batch-12.16..0
 - Java version: 8
 - App Server/Environment: N/A
 - Frameworks: N/A

**Additional context**
N/A.

**Comment by joshfree** [comment]
Hi @dk823832 thanks for filing this github issue.  Someone from the Storage team will follow up.

/cc @jaschrep-msft

**Comment by ibrahimrabab** [comment]
Hi @dk823832 

Thanks for reaching out. Unfortunately, blob-batch does not support deletes for versioned blobs, we recommend deleting blob versions via the regular delete API using BlobClientBase. 

Here is more information on versioned blobs and deletes:
[https://learn.microsoft.com/en-us/azure/storage/blobs/versioning-overview#deleting-a-blob-or-version](https://learn.microsoft.com/en-us/azure/storage/blobs/versioning-overview#deleting-a-blob-or-version)

Let us know if you have more questions or need any additional help!
