### ISSUE TITLE
[BUG]: Updating a VMSS with new capacity leads to outdated VM models

### ISSUE THREAD

**Issue by hendrik-schaffer** [Azure/azure-sdk-for-java#32223]
**Describe the bug**
When updating the scaling capacity of a Virtual Machine Scale Set via Azure Java SDK such as 
```java
vmss.update()
           .withCapacity(newCapacity)
           .apply();
```
the other existing VMs of the VMSS are then somehow outdated and the UI shows they do not have the latest VMSS model applied.

![vmss_capacity_update2](https://user-images.githubusercontent.com/67586769/202478713-c26a3556-c136-4c41-99e9-f54e4de9dc55.png)

When however changing the scaling capacity via the UI the VMs of the VMSS still have the latest VMSS model applied. 

![vmss_capacity_update1](https://user-images.githubusercontent.com/67586769/202478654-9d4a547f-9d8c-4f6d-8400-1d0b181c3144.png)

***Exception or Stack Trace***
There are no errors, it simply seems to be a mismatch in behavior between the API and the SDK

**To Reproduce**

***Code Snippet***
see above

**Expected behavior**
I would suggest that simply changing the scaling count should not affect the VMSS model of the VMs itself 

**Screenshots**

**Setup (please complete the following information):**
 - OS: [Windows]
 - IDE: [IntelliJ]
 - Library/Libraries: [e.g. com.azure:azure-resourcemanager:2.20.0]
 - Java version: [LibericaJDK-16] 
 - Frameworks: [Quarkus] 

**Information Checklist**
Kindly make sure that you have added all the following information above and checkoff the required fields otherwise we will treat the issuer as an incomplete report
- [x ] Bug Description Added
- [x ] Repro Steps Added
- [x ] Setup information Added

**Comment by weidongxu-microsoft** [comment]
@XiaofeiCao Would you investigate this?

**Comment by weidongxu-microsoft** [comment]
@hendrik-schaffer It would help if you can let us know the configure of the VMSS (publisher, offer, sku) e.g. "OpenLogic", "CentOS", "8_3"

**Comment by hendrik-schaffer** [comment]
Hello all,

I did some further research and I think the reaon for the different behavior is the following.
When using the above update apply command of the Java SDK, the corresponding PATCH request contains the whole representation of the VMSS as the request body.

Looking at the request body when using the web UI of the Azure Portal, it only sends the part that should be changed, here the SKU section, e.g.

```json
{ "sku": {
        "name": "Standard_DS2_v2",
        "tier": "Standard",
        "capacity": 10
    }
}
```

Can the implementation of the VMSS update command be changed in such a way that the body contains only the sections to be updated? Alternatively, it should at least consider that not all update operations render the VM latestModelApplied value to false.

**Comment by weidongxu-microsoft** [comment]
"latestModelApplied" should be a read-only property so it should not be settable from a PATCH (it should be one calculated by backend).

So there maybe other property that affect the model.

**Comment by hendrik-schaffer** [comment]
Well, yes...as I have written above, I think becaues the update command sends the  full JSON representation of the updated VMSS, this leads to the fact that "latestModelApplied" is then false. 
But I do not know the exact implementation of how this is calculated. 

Anyways, I think it is clear that the update command does at least results into different behavior compared to using the Azure Portal Web UI and therefore I would vote for that it will be fixed

**Comment by XiaofeiCao** [comment]
Thanks @hendrik-schaffer for your detailed explanation of your situation. I'll check if the patch pattern can resolve the altering of the latest model state. 

@weidongxu-microsoft This may be an issue we want to fix. When the vmss's `UpgradePolicy` is set to `Automatic`, all existing VMs in the vmss is likely to be rebooted if the `Latest Model` is `No`. I'll have that checked too.

**Comment by XiaofeiCao** [comment]
Hi @hendrik-schaffer 

It seems that newly created VMs in VMSS with **manual** upgrade policy has outdated model. Tried both SDK and portal, same result. 

After I manually upgrade the model, future capacity change won't affect existing VMs. Please help confirm it is your case.

Though for **automatic** VMSS, it's latest model from the start. Looks like a service bug.

**Comment by hendrik-schaffer** [comment]
Hello @XiaofeiCao ,
yes, we are using the manual upgrade policy. I tried to show it in the screenshots above. If we change the capacity via the SDK, the VMs all have the latest model applied.

However, when trying to change the capacity via the SDK, only the new VMs have the latest model applied, but the existing ones suddenly do not have the latest model applied.

**Comment by XiaofeiCao** [comment]
Hi @hendrik-schaffer 

Could you manually upgrade existing outdated VMs via Portal and again change the capacity via SDK and see if existing VMs are affected?

My point is, the existing VMs are outdated the moment they are created along with the VMSS, either from Portal or SDK (for manual upgrade policy), at least from my experiment.

**Comment by hendrik-schaffer** [comment]
Hello @XiaofeiCao , 
unfortunately, I am still experiencing the same behavior. Even if I manually upgrade the VMs to the latest model, then run the VMSS update withCapacity command via the SDK, it renders the existing VMs as outdated (latestmodel not applied) and only the new VMs have the latest model applied set to true :(

**Comment by XiaofeiCao** [comment]
Hi @hendrik-schaffer 
Alright, that's indeed unfortunate and I couldn't reproduce on my local machine... 
Could you share the code snippet of how you created the VMSS please(or VMSS properties if it's created from Portal and redact sensitive information)?

**Comment by hendrik-schaffer** [comment]
Sure. Please find below the JSON View of our VMSS

```json
{
    "name": "enterpriserunner-vmss-ubuntu-server-int",
    "id": "/subscriptions/SUBSCRIPTION-ID/resourceGroups/RG_REDACTED/providers/Microsoft.Compute/virtualMachineScaleSets/enterpriserunner-vmss-ubuntu-server-int",
    "type": "Microsoft.Compute/virtualMachineScaleSets",
    "location": "westeurope",
    "tags": {
        "createdBy": "Jenkins"
    },
    "identity": {
        "type": "UserAssigned",
        "userAssignedIdentities": {
            "/subscriptions/SUBSCRIPTION-ID/resourceGroups/RG_REDACTED/providers/Microsoft.ManagedIdentity/userAssignedIdentities/githubrunnervms-mi-int": {
                "principalId": "6dda559c-b4c3-4636-a1d3-8d898a55e04a",
                "clientId": "c76c49bd-98d0-430f-a708-9034a43c7824"
            }
        }
    },
    "sku": {
        "name": "Standard_DS2_v2",
        "tier": "Standard",
        "capacity": 3
    },
    "properties": {
        "singlePlacementGroup": true,
        "orchestrationMode": "Uniform",
        "upgradePolicy": {
            "mode": "Manual",
            "rollingUpgradePolicy": {
                "maxBatchInstancePercent": 20,
                "maxUnhealthyInstancePercent": 20,
                "maxUnhealthyUpgradedInstancePercent": 20,
                "pauseTimeBetweenBatches": "PT0S"
            }
        },
        "virtualMachineProfile": {
            "osProfile": {
                "computerNamePrefix": "atcrun",
                "adminUsername": "cloud",
                "linuxConfiguration": {
                    "disablePasswordAuthentication": true,
                    "ssh": {
                        "publicKeys": [
                            {
                                "path": "/home/cloud/.ssh/authorized_keys",
                                "keyData": "ssh-rsa SSH_KEY_REDACCTED"
                            }
                        ]
                    },
                    "provisionVMAgent": true
                },
                "secrets": [],
                "allowExtensionOperations": true,
                "requireGuestProvisionSignal": true
            },
            "storageProfile": {
                "osDisk": {
                    "osType": "Linux",
                    "diffDiskSettings": {
                        "option": "Local",
                        "placement": "CacheDisk"
                    },
                    "createOption": "FromImage",
                    "caching": "ReadOnly",
                    "managedDisk": {
                        "storageAccountType": "Standard_LRS"
                    },
                    "diskSizeGB": 30
                },
                "imageReference": {
                    "id": "/subscriptions/SUBSCRIPTION-ID/resourceGroups/RG_REDACTED/providers/Microsoft.Compute/galleries/atc_images_int/images/enterpriserunner-ubuntu-20.04-gen2-int/versions/3.6.1"
                }
            },
            "networkProfile": {
                "networkInterfaceConfigurations": [
                    {
                        "name": "entercfecNic",
                        "properties": {
                            "primary": true,
                            "enableAcceleratedNetworking": false,
                            "disableTcpStateTracking": false,
                            "dnsSettings": {
                                "dnsServers": []
                            },
                            "enableIPForwarding": false,
                            "ipConfigurations": [
                                {
                                    "name": "entercfecIPConfig",
                                    "properties": {
                                        "subnet": {
                                            "id": "/subscriptions/SUBSCRIPTION-ID/resourceGroups/RG_REDACTED/providers/Microsoft.Network/virtualNetworks/VNET-SPOKE-AMS-0221/subnets/Subnet-1"
                                        },
                                        "privateIPAddressVersion": "IPv4"
                                    }
                                }
                            ]
                        }
                    }
                ]
            },
            "extensionProfile": {
                "extensions": [
                    {
                        "name": "CustomScript",
                        "properties": {
                            "autoUpgradeMinorVersion": true,
                            "publisher": "Microsoft.Azure.Extensions",
                            "type": "CustomScript",
                            "typeHandlerVersion": "2.1"
                        }
                    }
                ]
            }
        },
        "provisioningState": "Succeeded",
        "overprovision": false,
        "doNotRunExtensionsOnOverprovisionedVMs": false,
        "uniqueId": "9af6d670-2987-479e-9c0a-7375d77aa313"
    }
}
```

To update the VMSS via the SDK, we are using the following code snippet:

```java

public VirtualMachineScaleSet getLinuxEnterpriseRunnerVMSS() {
        return getAzureResourceManager().virtualMachineScaleSets()
                .getByResourceGroup(resourceGroup, linuxEnterpriseRunnerVMSSName);
}

protected void scaleUpLinuxRunnerVMSS(VirtualMachineScaleSet vmss) {
        
        // calculate new instance count 
        // [....] 
        vmss.update()
                .withCapacity(newVmInstanceCount)
                .apply();

        LOG.info("Scaled up VMSS {} to {} instances.", vmss.name(), newVmInstanceCount);
}

@Test
void scaleUpLinuxVMSS() {
        VirtualMachineScaleSet targetVMSS = githubRunnerService.getLinuxEnterpriseRunnerVMSS();
        githubRunnerService.scaleUpLinuxRunnerVMSS(targetVMSS);
}

```

**Comment by XiaofeiCao** [comment]
@hendrik-schaffer , sorry for the delay. I tried various combinations derived from your vmss properties, I'm now quite convinced that for vmss with ephemeral OS disks(`virtualMachineProfile.storageProfile.osDisk.diffDiskSettings.option=Local`) will have this out-of-date issue. 

Seems service consider any properties present (or even empty `osDisk: {}`) during ephemeral VMSS update to be a model refresh. 

@weidongxu-microsoft Since generally nothing can be modified to vmss ephemeral osDisks (both [backend](https://learn.microsoft.com/en-us/azure/virtual-machines/ephemeral-os-disks-faq) and in our convenience api), I think we can safely ignore osDisk property when copying innerModel to updateModel?

**Comment by weidongxu-microsoft** [comment]
@XiaofeiCao Yes, if nothing can change, we can ignore it when preparing PATCH. However do comment that in obvious location in code.

**Comment by XiaofeiCao** [comment]
@hendrik-schaffer 2.24.0 released. Let us know if the new version fixed this issue.
