### ISSUE TITLE
[BUG] Warning logs about client properties while using Kafka password-less function

### ISSUE THREAD

**Issue by yiliuTo** [Azure/azure-sdk-for-java#32235]
**Describe the bug**
When using Kafka password-less connection function, there are warning logs of 
```java
2022-09-22 14:50:51.784  WARN 30520 --- [           main] .f.AbstractAzureHttpClientBuilderFactory : The client properties of an http-based client is of type com.azure.spring.cloud.core.properties.client.ClientProperties
```

**To Reproduce**
Follow the [QuickStart](https://learn.microsoft.com/azure/developer/java/spring-framework/configure-spring-cloud-stream-binder-java-app-kafka-azure-event-hub?tabs=passwordless) to build an application and run.

**Expected behavior**
Warning logs should be removed without any breaking changes to users.

**Comment by Netyyyy** [comment]
Now we directly transport service properties with HTTP(SecretClientProperties)/AMQP(ServiceBusClientCommonProperties)/non-http,non-amqp(AzurePasswordlessProperties) protocol to Azure properties, so this still needs to confirm that is there any problems in `Proxy` or `Retry` with the transported `AzureProperties` with different protocols.

**Comment by saragluna** [comment]
The current implementation will only reduce the log level, a temporary workaround. This problem will be fixed when https://github.com/Azure/azure-sdk-for-java/issues/32443 gets resolved.
