### ISSUE TITLE
[BUG] ShareFileClient.exists() produces warning when file doesn't exist

### ISSUE THREAD

**Issue by bosschaert** [Azure/azure-sdk-for-java#32250]
**Describe the bug**

When I call `ShareFileClient.exists()` and the file does not exist I see a warning in the log. The operation seems to work though.

e.g. the following code:
```
ShareDirectoryClient sdcRoot = ... // some Azure File Share directory
ShareFileClient resFC = sdcRoot.getFileClient("some-nonexisting-file.json");
boolean exists = resFC.exists()); // this call produces the warning
```

gives me this warning in the log:
```
[reactor-http-kqueue-1] WARN com.azure.core.util.serializer.SerializerEncoding - 'Content-Type' not found. Returning default encoding: JSON
```

If the file does exist, I don't get the warning.

***Exception or Stack Trace***
I see this warning in the log:

```
[reactor-http-kqueue-1] WARN com.azure.core.util.serializer.SerializerEncoding - 'Content-Type' not found. Returning default encoding: JSON
```

**To Reproduce**

```
ShareDirectoryClient sdcRoot = ... // some Azure File Share directory
ShareFileClient resFC = sdcRoot.getFileClient("some-nonexistent-file.json");
boolean exists = resFC.exists()); // this call produces the warning
```

***Code Snippet***
See above.

**Expected behavior**
The warning should not appear.

**Setup (please complete the following information):**
 - OS: Mac OsX Ventura 13.0.1
 - IDE: vscode
 - Library/Libraries: com.azure:azure-storage-file-share:12.16.1
 - Java version: 11
 - App Server/Environment: plain old Java main class
 - Frameworks: none

**Comment by alzimmermsft** [comment]
Thank you for filing this issue @bosschaert.

Fortunately, this is warning message doesn't indicate an error for this call. This is an issue where a `HEAD` request returns an error and there is an attempt to deserialize the exception response body but there is none. I'll look into have this fixed to not attempt to deserialize an exception body on `HEAD` requests as there should be no response body.
