### ISSUE TITLE
[QUERY] Are Container Probe Definitions missing in the fluent definition of a container instance while creating a container group in the resource manager?

### ISSUE THREAD

**Issue by emrebakkal-tomtom** [Azure/azure-sdk-for-java#32265]
**Query/Question**
While defining a container group to be created using the resource manager, the fluent API calls to define containerProbes (readiness and liveness) seem to be missing. Is this an oversight(on my side or the API side), or a missing feature in the current version?
```
azureResourceManager.containerGroups()
    .define("resourceName")
    .withRegion(region)
    .withExistingResourceGroup("resourceGroup")
    .withLinux()
    .withPrivateImageRegistry(registryName + ".azurecr.io", "username", "password")
    .withoutVolume()
    .defineContainerInstance("instanceName")
        .withImage("imageName")
        .withoutPorts()
        .withCpuCoreCount(1)
        .withMemorySizeInGB(8)
        .withEnvironmentVariables(envVariables)
        .withEnvironmentVariableWithSecuredValue(secureEnvVariables)
        .attach()
    .withRestartPolicy(ContainerGroupRestartPolicy.NEVER)
    .create();
```
The definition is present in the azurerm terraform provider for example:
```
resource "azurerm_container_group" "my-group" {
  name                = "my-container-group"
  location            = var.location
  resource_group_name = var.resource_group_name
  os_type             = "Linux"
  restart_policy      = "Always"
  ip_address_type     = "None"

  image_registry_credential {
    server   = "${var.registryName}.azurecr.io"
    username = "username"
    password = "password"
  }

  container {
    name   = "my_container"
    image  = "${var.registryName}.azurecr.io/my_image:${var.docker_id}"
    cpu    = "1"
    memory = "2"

    environment_variables = {
      VAR = "value"
    }

    secure_environment_variables = {
      MY_KEY = "my_value"
    }

    liveness_probe {
      exec                  = ["/bin/bash", "/myScript.sh"]
      period_seconds        = 30
      failure_threshold     = 2
    }
  }
}
```

***Why is this not a Bug or a feature Request?***
This may become a feature request if the container probe definition is really lacking in the API, and it's not an oversight on my side.

**Setup (please complete the following information if applicable):**
 - Library/Libraries: com.azure.resourcemanager:azure-resourcemanager:2.20.0
 
 **Information Checklist**
- [x] Query Added
- [x] Setup information Added

**Comment by XiaofeiCao** [comment]
Hi @emrebakkal-tomtom 

They are missing features in our SDK (liveness and readiness probes). 

We'll support them in our future releases. (may not be available in 2.21.0, you can expect it in 2.22.0).

**Comment by emrebakkal-tomtom** [comment]
Thank you for the quick response @XiaofeiCao

Should we turn the ticket into a feature request, or is it OK to stay like this?

**Comment by XiaofeiCao** [comment]
No problem. 

> Should we turn the ticket into a feature request, or is it OK to stay like this?

You could do that, but it won't be necessary. You may leave it as is.

**Comment by XiaofeiCao** [comment]
Hi @emrebakkal-tomtom , 2.22.0 has released and it should support liveness and readiness probe now.

**Comment by emrebakkal-tomtom** [comment]
Hello @XiaofeiCao, thank you for the quick follow up. My team and I appreciate it.
We will update to the latest version and start using it :)
