### ISSUE TITLE
[BUG] ServiceBus TimeoutException

### ISSUE THREAD

**Issue by wstest123** [Azure/azure-sdk-for-java#32281]
**Describe the bug**
When sending messages to Service Bus through Azure SDK client, got a lot of timeout error. Could you please help advice the possible reason of the following error? Thanks so much!

***Exception or Stack Trace***
errorContext[NS: potrmcninfsvbus002.servicebus.chinacloudapi.cn, PATH: topic.aftersales-order.aftersales-order-changed, REFERENCE_ID: Sender_36ce6f_7ce188dc06a14eccbfb7ba6b6b1cf705_G3, LINK_CREDIT: 979]

com.microsoft.azure.servicebus.primitives.TimeoutException: Send operation timed out at 2022-11-21T07:22:00.582271Z[Etc/UTC]., errorContext[NS: potrmcninfsvbus002.servicebus.chinacloudapi.cn, PATH: topic.service-record.service-record-changed, REFERENCE_ID: Sender_987647_93fcc203f0154d21948ad298735669c4_G9, LINK_CREDIT: 924] at com.microsoft.azure.servicebus.primitives.CoreMessageSender.throwSenderTimeout(CoreMessageSender.java:862) at com.microsoft.azure.servicebus.primitives.CoreMessageSender.lambda$scheduleSendTimeout$3(CoreMessageSender.java:275) at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515) at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264) at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:304) at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) at java.base/java.lang.Thread.run(Thread.java:829)

**Setup (please complete the following information):**
 Azure SDK version: com.microsoft.azure:azure-servicebus:3.6.4

**Comment by EldertGrootenboer** [comment]
Please upgrade to the latest package, as we have made many enhancements since this package.
If you cannot upgrade, please let us know why to see if we can unblock you.
Also, this seems like something that should be handled through a support request, please open one providing all details, such as repro-steps, and the code which is causing this.
