### ISSUE TITLE
Azure Maps Traffic Sample Issue

### ISSUE THREAD

**Issue by hongli750210** [Azure/azure-sdk-for-java#32299]
1. 
**Section:** [Link1](https://github.com/Azure/azure-sdk-for-java/blob/main/sdk/maps/azure-maps-traffic/src/samples/java/com/azure/maps/traffic/samples/GetTrafficFlowTile.java#L44), [Link2](https://github.com/Azure/azure-sdk-for-java/blob/main/sdk/maps/azure-maps-traffic/src/samples/java/com/azure/maps/traffic/samples/GetTrafficFlowTile.java#L76), [Link3](https://github.com/Azure/azure-sdk-for-java/blob/main/sdk/maps/azure-maps-traffic/src/samples/java/com/azure/maps/traffic/samples/GetTrafficIncidentTile.java#L44), [Link4](https://github.com/Azure/azure-sdk-for-java/blob/main/sdk/maps/azure-maps-traffic/src/samples/java/com/azure/maps/traffic/samples/GetTrafficIncidentTile.java#L77)
![image](https://user-images.githubusercontent.com/74638143/203457201-d1f125ef-d6b1-4731-96a1-411a67608213.png)

**Reason:**
Cannot invoke "com.azure.maps.traffic.models.TileIndex.getX()" because "tileIndex" is null

**Suggestion:**
      Change to 
```
new TrafficFlowTileOptions()
    .setTrafficFlowTileStyle(TrafficFlowTileStyle.RELATIVE_DELAY).setFormat(TileFormat.PNG).setZoom(10)
    .setTileIndex(new TileIndex().setX(1022).setY(680)));
```

2. 
**Section:** [Link1](https://github.com/Azure/azure-sdk-for-java/blob/main/sdk/maps/azure-maps-traffic/src/samples/java/com/azure/maps/traffic/samples/GetTrafficFlowTile.java#L51), [Link2](https://github.com/Azure/azure-sdk-for-java/blob/main/sdk/maps/azure-maps-traffic/src/samples/java/com/azure/maps/traffic/samples/GetTrafficFlowTile.java#L83)
![image](https://user-images.githubusercontent.com/74638143/203457378-f5627858-f9dc-4334-9f8a-3bfd6b70a4a2.png)

**Reason:**
Status code 400, "{"error":{"code":"400 BadRequest","message":"The provided values in (x, y, zoom) do not constitute a valid tile"}}"

**Suggestion:** 
Change to `new TileIndex().setX(1022).setY(680)`

@joshfree, @markweitzel for notification.

**Comment by khmic5** [comment]
Fixed in following PR: https://github.com/Azure/azure-sdk-for-java/pull/32383
