### ISSUE TITLE
Exception hierarchy

### ISSUE THREAD

**Issue by JonathanGiles** [Azure/azure-sdk-for-java#3229]
Python has defined an exception hierarchy in the following form:
```
AzureError
  |- AzureLibraryError
      |- AzureLibraryRequestError
      |- AzureLibraryResponseError
  |- ServiceRequestError
      |- ConnectionTimeoutError
      |- ServiceHttpRequestError
          |- ClientRequestError
              |- ResourceExistsError
              |- ClientAuthenticationError
              |- ResourceModifiedError
          |- ServerError
          |- TooManyRedirectsError
          |- TooManyRetriesError
```

We need to develop a similar exception hierarchy that is idiomatic for Java developers.

**Comment by JonathanGiles** [comment]
Todo:
- [ ] Create a new package in azure-common `com.azure.common.exceptions`
- [ ] We should repurpose the existing `RestException` class into `ServiceRequestException`, and relocate it into this package.
- [ ] We build out the additional exception types and ensure that they are tested, 
- [ ] Another exploration topic - can we introduce a generic type T for the `ServiceRequestException` class to represent the body type? Does this have any value....? Probably not I would imagine.

**Comment by mayurid** [comment]
@sima-zhu : Something for you to look into.

**Comment by sima-zhu** [comment]
Looking.

**Comment by sima-zhu** [comment]
The first round will implement the hierarchy with necessary field.
-Constructor
-Java Doc.

**Comment by JonathanGiles** [comment]
The benefit of this approach is that a developer can simply try / catch on exception types that they are interested in. This would work well if there are only a few cases they care about. If a developer on the other hand wants to handle all types, then this approach becomes messy and would be better implemented with a far smaller set of exception types and an enum to represent the different exception types.

**Comment by sima-zhu** [comment]
Talked the design with @JonathanGiles offline. 
Two options we have for exception handling:
1. Have a exception hierarchy and customer handle the exception individually by their needs.
2. Have a generic exception (e.g. retryable / non-retryable) and use like Enum as error interceptor. In this way, customer can easily handle the exception without further understanding and easy to add new scenarios. 
Currently, we agreed to implement hierarchy first to see if it satisfies developer needs.

**Comment by conniey** [comment]
I think using less exception types would enable developers to easily select the ones they care about and handle them:
```java
try {
   client.send(request);
} catch (ServiceRequestException ex) {
   if (ex.handle(type -> type == Timeout || type == Authorization)) {
     // do something about the types that were handled.
   }
}
```

**Comment by sima-zhu** [comment]
I personally agree with @conniey . Clients have the choice of having specific type of error by having Enum, and handle the exception in their way. If the exception hierarchy is not specific enough, then clients might not able to distinguish two different types of error in one exception unless they can parse the error message. If we want to make the exception specific enough for customer to use, then maintenance work is heavy, meanwhile increase the difficulty of learning exception (especially new one) behavior.

**Comment by sima-zhu** [comment]
https://github.com/Azure/azure-sdk-for-java/pull/3347

**Comment by JonathanGiles** [comment]
For what it is worth, I [ran a poll](https://twitter.com/JonathanGiles/status/1116479404081696768), with the results being largely 50/50. The discussion however sways me towards having a full hierarchy of exception types.

**Comment by sima-zhu** [comment]
Here is the list of Python exception hierarchy
```
AzureError
  |- DecodeError
  |- ServiceRequestError
      |- ConnectError
      |- ServiceHttpRequestError
          |- ReadTimeoutError
          |- HttpRequestError
              |- ClientRequestError
                  |- ResourceExistsError
                  |- ResourceNotFoundError
                  |- ClientAuthenticationError
                  |- ResourceModifiedError
          |- ServerError
          |- TooManyRedirectsError
```

**Comment by JonathanGiles** [comment]
Can you edit your comment above - there are two `ServiceRequestError`

**Comment by sima-zhu** [comment]
The exception hierarchy Java proposed:
```
AzureException (Base)
      |- ServiceResponseError (Error raised when client cannot or error handle the response)
          |- ReadTimeoutError (Server did not send back response within allotted time slot)
          |- DecodeException (Client cannot deserilize the response)
      |- ServiceRequestError (Error raised when client pass error request to server, or service got wrong)
          |- ConnectError (Error raised whtn client has trouble to establish the connection with server.)
          |- HttpRequestError (BaseException with http status code, http protocol specifically)
              |- ResourceExistsError (4xx)
              |- ResourceNotFoundError (412, 404)
              |- ClientAuthenticationError (4xx)
              |- ResourceModifiedError (4xx. 412)
              |- ServerError (5xx, internal server error or server can not serve the request)
              |- TooManyRedirectsError (3xx)
```

**Comment by conniey** [comment]
Could you specify which HTTP status code range(s) would throw ResourceExistsException, ClientAuthenticationException and ResourceModifiedException?

4xx suggests that you can replace the `xx` with any values. So, given a 401, I could throw a ResourceModifiedException, ResourceExistsException. 🤔

**Comment by alzimmermsft** [comment]
Given that the exceptions are not strongly tied to the HTTP status code, given that the SwaggerMethodParser and RestProxy with the UnexpectedResponseExceptionType determine which code throws which exception, I'd leave them out of the hierarchy proposal. I'd list them as a suggestion somewhere else in our documentation though.

Other than that the exception hierarchy looks good to me.

**Comment by JonathanGiles** [comment]
@alzimmermsft I'm not entirely clear on what you're suggesting? Isn't it a good idea to make proposals about the mappings that should be created between the exception and the service client REST methods? This should help to guide you on which exceptions to specify against which methods. Many of these exceptions will not be thrown directly by the service client methods either, but rather the HTTP pipeline, etc, so again, the mapping is useful for whoever goes in to the HTTP pipeline code to plumb these exceptions in.

**Comment by sima-zhu** [comment]
@JonathanGiles I have synced with Alan about his comments. He is actually reminding us the mapping of status code and exception can define in UnexpectedResponseExceptionType. There is no need for exception hierarchy to have the status code field inside of Custom Exception class. 

I have checked in the exception architect. I will close the issue for now. If you have any other requests, please feel free to reopen this issue. 
Thanks!

**Comment by JonathanGiles** [comment]
@sima-zhu @alzimmermsft I still don't understand what is being said here. Can you point to exactly what you want to remove, or is this no longer being removed (as this issue is closed)?
