### ISSUE TITLE
Go through all spring samples to make sure the resources created by them should add same custom tags

### ISSUE THREAD

**Issue by fangjian0423** [Azure/azure-sdk-for-java#32293]
This is [Spring sample list](https://github.com/Azure-Samples/azure-spring-boot-samples).

We should add custom tags by terraform, so we can track how many resources created by spring samples.

Besides, we also should add custom tags when azd template publish.

**Comment by backwind1233** [comment]
@fangjian0423  Could you explain more about this?
I remember we have added several tags by using terraform.

**Comment by fangjian0423** [comment]
I created a [work item](https://dev.azure.com/azure-spring-integration/spring-integration-private/_workitems/edit/1311/) in ADO.

**Comment by fangjian0423** [comment]
Spring Cloud Azure 4.x PR https://github.com/Azure-Samples/azure-spring-boot-samples/pull/601

**Comment by fangjian0423** [comment]
Spring Cloud Azure 6.x PR https://github.com/Azure-Samples/azure-spring-boot-samples/pull/602
