### ISSUE TITLE
Replace throws with Mono.error in Reactive Calls

### ISSUE THREAD

**Issue by alzimmermsft** [Azure/azure-sdk-for-java#32307]
There are many cases in the SDKs where an exception is thrown instead of returned as a `Mono.error` in reactive operations (ex `flatMap`) which may break the contract of the reactive stream. These cases should be cleaned up to use `Mono.error` or `FluxUtil.monoError`, or `Flux.error` and `FluxUtil.fluxError`.

**Comment by weidongxu-microsoft** [comment]
@alzimmermsft 

One case for your advise.

For some internal method, that we know it only used in a Reactor operation. But the method itself is purely sync (non-blocking), except the `Mono.error`.

Here is an instance https://github.com/Azure/azure-sdk-for-java/pull/31755#discussion_r1027451824

It won't be a big deal as method it private. Do we recommend to still make the signature async for the `Mono.error` (I saw some post recommend this), or honor its non-blocking/non-async and make it do a throw, or some other approach like return an invalid object and concatMap a check and Mono.error?
