### ISSUE TITLE
[FEATURE REQ] Explicit set label with "sync-sping-boot3" or "no sync-sping-boot3"

### ISSUE THREAD

**Issue by backwind1233** [Azure/azure-sdk-for-java#32317]
## Context
Now, we develop our features both in [main](https://github.com/Azure/azure-sdk-for-java) branch and [feature/spring-boot-3](https://github.com/Azure/azure-sdk-for-java/tree/feature/spring-boot-3) branch, and this situation will continue for about 1 year.
For any PR which changes codes under the folder sdk/spring, we should create PRs both in main and `feature/spring-boot-3` branch,
but we may lost the rule in mind and forget to create PR in both branches.

## Goal
Make PR creaters explicit set the lables with "sync-sping-boot3" or "no sync-sping-boot3", 
in this way PR creaters should know whether to create PR in both branches or not.

## Solution
1. Create a pipeline and trigger the pipeline when there are code changes under folder sdk/spring.
2. Get all labels of the PR to check lables
3. For the pipeline, if the lables contains "sync-sping-boot3" or "no sync-sping-boot3", return success, otherwise return false.
4. Before merging, both "sync-sping-boot3" and "sync-sping-3-pr-created" are needed;
5. only affects PR with lable "azure-spring".

**Comment by backwind1233** [comment]
Pull Request Labels - Get:
https://learn.microsoft.com/en-us/rest/api/azure/devops/git/pull-request-labels/get?view=azure-devops-rest-7.0

**Comment by backwind1233** [comment]
We should also consider repo: 

- [azure-spring-boot-samples](https://github.com/Azure-Samples/azure-spring-boot-samples)
- [spring-cloud-azure](https://github.com/microsoft/spring-cloud-azure)

**Comment by saragluna** [comment]
Closing this issue now for the spring boot 3 has been on the main branch now.
