### ISSUE TITLE
java spring open lab

### ISSUE THREAD

**Issue by stliu** [Azure/azure-sdk-for-java#32327]
See also: https://github.com/MicrosoftDocs/azure-docs/issues/93940

we've created a java on azure open lab which we will use to drive product adoption for java customers. in this repo https://github.com/MicrosoftLearning/Deploying-and-Running-Java-Applications-in-Azure-Spring-Apps/tree/master/Instructions/Labs we have created code for end-to-end scenarios described in each challenge. please go through the code (expand hints to see the code) to make sure:

1. appropriate libraries are used
2. appropriate versions are used
3. code demonstrates best practices

**Comment by stliu** [comment]
@saragluna please update this issue

**Comment by saragluna** [comment]
PR created:
- [x] https://github.com/MicrosoftLearning/Deploying-and-Running-Java-Applications-in-Azure-Spring-Apps/pull/6
- [x] https://github.com/MicrosoftLearning/Deploying-and-Running-Java-Applications-in-Azure-Spring-Apps/pull/5

**Comment by saragluna** [comment]
Still need to keep updating the lab to the latest Spring Cloud Azure versions and use passwordless for Kafka.

**Comment by saragluna** [comment]
Closing for it's outdated.
