### ISSUE TITLE
[BUG] Should be able to support variable binding name for @EventGridTrigger

### ISSUE THREAD

**Issue by survivant** [Azure/azure-sdk-for-java#32326]
**Describe the bug**
I have a application that will listen for EventGridEvent.  I don't want to "hardcode" the evengridtopic to use.  I want to use %variable% syntax like for other triggers (look at CosmosDBOutput, _

like 
````
@FunctionName("ProcessFileUpload")
    public void ProcessFileUpload(
            @EventGridTrigger(name = "event") String uploadData,
            @CosmosDBOutput(name = "database",
                databaseName = "%DatabaseName%",
                collectionName = "%CollectionName%",
                connectionStringSetting = "CosmosConnectionString") OutputBinding<String> outputItem,
                final ExecutionContext context) {
        context.getLogger().info("Uploaded data: " + uploadData);
        outputItem.setValue(uploadData);
    }
````

Suppose that I want to deploy the same application but they will monitor different Topics , it will be easy to change the value in function.json.  

But now, I'll have to clone the repository and change the name "hardcoded in EventGridTrigger(name="topic1") -> EventGridTrigger(name="topic2").. It doesn't make sense, unless I missed something and there a way to do that.

***Exception or Stack Trace***
[2022-11-24T13:09:14.376Z] The 'blobStorageEventGridTrigger' function is in error: The binding name %EventGridTopic% is invalid. Please assign a valid name to the binding.

***Code Snippet***
here my code
````
@FunctionName("blobStorageEventGridTrigger")
    public void execute(
            @EventGridTrigger(
                    name = "%EventGridTopic%")
            EventSchema content,
            final ExecutionContext context) {
        LOGGER.info("Java Event Grid trigger function executed. EventSchema:[{}]", content);
        handleRequest(content, context);
    }
````

in local.settings.json
````
...
"EventGridTopic": "blobeventtopic",
....
````

if I change to code to 
````
@FunctionName("blobStorageEventGridTrigger")
    public void execute(
            @EventGridTrigger(
                    //name = "%EventGridTopic%")
                    name = "blobeventtopic")
            EventSchema content,
            final ExecutionContext context) {
        LOGGER.info("Java Event Grid trigger function executed. EventSchema:[{}]", content);
        handleRequest(content, context);
    }
````

the application will run
````
Functions:

        blobStorageEventGridTrigger: eventGridTrigger

For detailed output, run func with --verbose flag.
[2022-11-24T13:24:42.794Z] Worker process started and initialized.
[2022-11-24T13:24:47.387Z] Host lock lease acquired by instance ID '000000000000000000000000A69F7E4C'.
````

**Expected behavior**
I expect to be able to set the topic name to listen with configuration using %% syntax

**Setup (please complete the following information):**
 - OS: [Windows 10]
 - IDE: [IntelliJ]
 - Library/Libraries: [e.g. com.azure:azure-core:1.16.0 (groupId:artifactId:version)]
 - Java version: [11] 
 - Frameworks: [Spring Boot] 

**Information Checklist**
Kindly make sure that you have added all the following information above and checkoff the required fields otherwise we will treat the issuer as an incomplete report
- [ X] Bug Description Added
- [ X] Repro Steps Added
- [ X] Setup information Added

**Comment by fangjian0423** [comment]
hi @survivant , I created a new issue in another repository https://github.com/Azure/azure-functions-java-library/issues/194 and close this one. Thanks!

**Comment by kaibocai** [comment]
Hi @survivant , it seems you are missing understanding the name field in those trigger annotations, the name field is not the name for your for example, evenhub name, the thing that bind to your eventhub is the [eventHubName](https://github.com/Azure/azure-functions-java-library/blob/2387b6b1d8d114c919377a6ac66f9fe63f4d31cd/src/main/java/com/microsoft/azure/functions/annotation/EventHubTrigger.java#L62) and [connection](https://github.com/Azure/azure-functions-java-library/blob/2387b6b1d8d114c919377a6ac66f9fe63f4d31cd/src/main/java/com/microsoft/azure/functions/annotation/EventHubTrigger.java#L83), the name field has nothing to do with your outside resource, it is used internally by function runtime. Thanks.

**Comment by survivant** [comment]
I opened the issue because I found out that we can't use variable name for ``@EventGridTrigger`` but are able for ``@EventHubTrigger`` like this example
````
@EventHubTrigger(name = "message",
                eventHubName = "%eventhub%",
                consumerGroup = "%consumergroup%",
                connection = "eventhubconnection",
                cardinality = Cardinality.ONE)
````

suppose that I want to deploy the same application twice.  App1 will listen to ``topic1`` and App2 will listen to ``topic2``
with the same code, I should be able to configure the name of the trigger to listen from a variable.  

App1 : EventGridTopic=topic1
App2 : EventGridTopic=topic2

like this
````
@EventGridTrigger(
                    name = "%EventGridTopic%")
````

**Comment by kaibocai** [comment]
Hi @survivant , sorry I made mistake on the trigger you are trying to use. For EventGridTrigger the `name` field again has noting to do with your event grid, you can try on your local that give the an arbitrary value to the name, I believe it should still works
```
@EventGridTrigger(
                    name = "foo")
```

To bind the function with an event grid please follow this [link](https://learn.microsoft.com/en-us/azure/azure-functions/event-grid-how-tos?tabs=v2%2Cportal#create-a-subscription), seems this is currently the only way to bind your EventGridTrigger function to an event grid. Thanks.
