### ISSUE TITLE
[FEATURE REQ] Enhance Github Action to support update version for both Spring Boot 2 and Spring Boot 3

### ISSUE THREAD

**Issue by Netyyyy** [Azure/azure-sdk-for-java#32337]
### Context
Now we have GitHub action to auto-update the latest Spring-Boot and Spring-Cloud versions, and it only works for Spring-Boot 2.x.x on Azure/main branch.
Since Spring-Boot publishes the 3.0.0 version, we need to support it in our feature/spring-boot-3 branch.

### Goal
Enhance Github Action to support updated version for both Spring Boot 2 and Spring Boot 3

**Comment by Netyyyy** [comment]
https://github.com/Azure/spring-cloud-azure-tools/pull/15

**Comment by saragluna** [comment]
Closing this now for SB3 has been merged back to the main branch. #41131
