### ISSUE TITLE
Spring Cloud Stream Service Bus messaging testing

### ISSUE THREAD

**Issue by SofiaVynnytska12** [Azure/azure-sdk-for-java#32347]
Is there a way of testing the event-driven application, which uses Spring Cloud Streaming and Azure Service Bus as a message broker?

we are using the folowing starter:
<dependency>
      <groupId>com.azure.spring</groupId>
      <artifactId>spring-cloud-azure-stream-binder-servicebus</artifactId>
</dependency>

in the application.properties we have defined the folowing set of configurations:
spring.cloud.function.definition=someFunctions;
spring.cloud.stream.bindings.someName-in-0.destination=consumingDestination;
spring.cloud.stream.bindings.someName-out-0.destination=supplyingDestination;

in the application context all functional beans for consuming and supplying were defined as well;

is there a way of writing Spring Boot Tests to test that the message was consumer and after that correctly processed properly? (e.g. the flow: message consuming from one destination -> processing -> supplying to the other destination)

thanks.

**Comment by backwind1233** [comment]
Hi @SofiaVynnytska12 thanks for reaching out, @yiliuTo could you take care of this?

**Comment by yiliuTo** [comment]
Hi @SofiaVynnytska12 thanks for reaching us. Currently we do not support this yet. And this feature is tracked by https://github.com/Azure/azure-sdk-for-java/issues/23422, which is in our backlog now.
