### ISSUE TITLE
[Query] How to restore deleted file to specified version without enable soft-delete.

### ISSUE THREAD

**Issue by tianshangstar** [Azure/azure-sdk-for-java#32344]
**Query/Question**
We want enable restore API in azure, after investigation we found:

- for undeleted file, it can be retore to target version with `copy` API
- for deleted file, according the document, it need `undelete()` first?  but the `undelete()` api is not available because the soft-delete is not in our plan.

the questions is :
- is there any workaround to restore deleted file to specified version without enable soft-delete?
- if wanna retore deleted file to target version, is enable soft-delete necessary?

***Why is this not a Bug or a feature Request?***

We had notcie that there is an API named `undelete()`, it required soft-delete enabled.
The doubt is that the file and its different version already be stored in OSS, maybe there is some workaround to restore deleted file to a specified verison?

**Setup (please complete the following information if applicable):**
 - OS: N/A
 - IDE: N/A
 - Library/Libraries: com.azure:azure-storage-blob:12.19.0

**Comment by joshfree** [comment]
Hi @tianshangstar! someone from the storage team will follow up on your question shortly.

**Comment by jaschrep-msft** [comment]
Acknowledging. We also notice that the docs are a little unclear and are further investigating an answer.

**Comment by ibrahimrabab** [comment]
Hi @tianshangstar 

Following up on this thread. Based on further investigation, you must have soft-delete enabled in order to use undelete(). For more information, see here:
https://learn.microsoft.com/en-us/rest/api/storageservices/undelete-blob

Please let us know if you have any other questions, thanks!
