### ISSUE TITLE
[FEATURE REQ] Release Spring Cloud AppConfiguration 2.10.0

### ISSUE THREAD

**Issue by Netyyyy** [Azure/azure-sdk-for-java#32340]
### Context
Need a release for Spring Cloud AppConfiguration to catch up with the azure-core and app configuration sdk version to address [some CVEs](https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fcezapata%2Fappconfiguration-sample%23vulnerabilities-found&data=05%7C01%7Cv-muyaofeng%40microsoft.com%7Cff2aab8c7e1843dbb42408daccf2ceda%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C638047640469246420%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=jrrqq7K0yyqwe%2FKDHzQaujWh0aZCxSGxx1kapPDSg8s%3D&reserved=0).

### Goal
Release Spring Cloud AppConfiguration 2.10.0.

**Comment by Netyyyy** [comment]
https://github.com/Azure/azure-sdk-for-java/pull/32305

**Comment by mrm9084** [comment]
@Netyyyy, an update has been released.

**Comment by Netyyyy** [comment]
Published, close it.
