### ISSUE TITLE
[BUG]ReadOperationsShouldDoRegionFailoverOnHighTransitTimeout

### ISSUE THREAD

**Issue by xinlian12** [Azure/azure-sdk-for-java#32350]
**Issue:**
As of today, for read operations with multi-region, if the request has exhausted all retries due to high transit timeout, the request will not retry on the other regions.  We should double check this behavior and alight the implementation in .Net SDK side. (By theory, SDK should also retry on a different region).

**Comment by ealsur** [comment]
My understanding is that once the local retries are exhausted, a 503 should be thrown (these are receive timeouts). The 503 should be taken care of by the Client Retry Policy.
