### ISSUE TITLE
Increase Test Coverage for Azure Search Documents

### ISSUE THREAD

**Issue by g2vinay** [Azure/azure-sdk-for-java#32360]
Azure Search Documents SDK is missing test coverage for:

1. SearchAsyncClient
2. SearchIndexerAsyncClient
3. SearchIndexAsyncClient

This is a blocker for [Sync Stack PR](https://github.com/Azure/azure-sdk-for-java/pull/32286) to go through.

**Comment by alzimmermsft** [comment]
Fixed in #33030
