### ISSUE TITLE
[QUERY] How do we create managed disk with hibernation enabled

### ISSUE THREAD

**Issue by Prudvidhard** [Azure/azure-sdk-for-java#32375]
**Query/Question**
Creating Vm with hibernation capability returned exception saying "The referenced os disk should support hibernation for a VM with hibernation capability".
Azure team said hibernation should be enabled on OS disk, they gave this [link](https://nam10.safelinks.protection.outlook.com/?url=https%3A%2F%2Fdocs.microsoft.com%2Fen-us%2Frest%2Fapi%2Fcompute%2Fdisks%2Fupdate%23update-a-managed-disk-to-add-supportshibernation.&data=05%7C01%7Cprudvidhard%40workspot.com%7C595869b984e44b727b3008dad257f22e%7C163804d0c86646d59e470d00cae5dfe5%7C0%7C0%7C638053572418006102%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=SBWzMesoEU4HlHh8YtzGgdPO7ffc1OvaB6gRXi%2FRBw0%3D&reserved=0).
In SDK, i couldn't find parameter to enable hibernation while creating disk. How do I create disk with hibernation enabled?
Disk osDisk = azureInstance.disks().define(diskName).withRegion(region)
								.withExistingResourceGroup(rg).withWindowsFromVhd(image)
								.withStorageAccountName(vhdStorageAccountName).withSizeInGB(size).withSku(diskSkuType)
								.create();

***Why is this not a Bug or a feature Request?***

**Setup (please complete the following information if applicable):**
 - IDE: [e.g. IntelliJ]
 - Library/Libraries: azure-resourcemanager:2.14.0
 
 **Information Checklist**
 Kindly make sure that you have added all the following information above and checkoff the required fields otherwise we will treat the issuer as an incomplete report
- [x] Query Added
- [x] Setup information Added

**Comment by joshfree** [comment]
@weidongxu-microsoft could you please follow up with @Prudvidhard on their question?

**Comment by weidongxu-microsoft** [comment]
@XiaofeiCao Does disk have option for hibernate?

Code for vendor provider: 
https://github.com/Azure/azure-sdk-for-java/blob/main/sdk/resourcemanager/azure-resourcemanager-compute/src/test/java/com/azure/resourcemanager/compute/VirtualMachineOperationsTests.java#L1199-L1240

**Comment by Prudvidhard** [comment]
This worked for me. After disk created, I updated the disk with hibernation support. Creating VM with hibernation capability succeeded with this disk.

Disk osDisk = azureInstance.disks().define(diskName).withRegion(region)
.withExistingResourceGroup(rg).withWindowsFromVhd(image)
.withStorageAccountName(vhdStorageAccountName).withSizeInGB(size).withSku(diskSkuType)
.create();

Disk.Update osDiskUpdating = osDisk.update();
osDisk.innerModel().withSupportsHibernation(true);
osDisk = osDiskUpdating.apply();

**Comment by weidongxu-microsoft** [comment]
Thanks @Prudvidhard 

@XiaofeiCao Please support it at convenience API.

**Comment by XiaofeiCao** [comment]
OK, will support it in our next release.

**Comment by XiaofeiCao** [comment]
@Prudvidhard 2.22.0 has been released and disk hibernation support has been added.
