### ISSUE TITLE
operationType field missing in changeFeed

### ISSUE THREAD

**Issue by vavasthi** [Azure/azure-sdk-for-java#32388]
If I start a changeFeed with format cosmos.oltp.changefeed, the operationType field is always null.

        spark.readStream()
                .format("cosmos.oltp.changefeed")
                .schema(changeDocumentSchemaRead())

The schema contains the field and the database also contains the field but change feed has the value as null.

**Comment by kushagraThapar** [comment]
@xinlian12 please take a look at this.

**Comment by TheovanKraay** [comment]
Lets revisit this for next semester.

**Comment by kushagraThapar** [comment]
@xinlian12 please take a look at this, thanks!
