### ISSUE TITLE
[BUG] NullPointerException in listing diagnosticSettings by resourceId

### ISSUE THREAD

**Issue by sachinkumar07** [Azure/azure-sdk-for-java#32387]
**Describe the bug**
We are getting NullPointerException in listing diagnosticSettings for a resource.

***Exception or Stack Trace***

java.lang.NullPointerException: null 	at java.util.TreeMap.compare(TreeMap.java:1294) ~[?:1.8.0_342] 	at java.util.TreeMap.put(TreeMap.java:538) ~[?:1.8.0_342] 	at com.azure.resourcemanager.monitor.implementation.DiagnosticSettingImpl.setInner(DiagnosticSettingImpl.java:254) ~[azure-resourcemanager-monitor-2.21.0.jar!/:2.21.0] 	at com.azure.resourcemanager.monitor.implementation.DiagnosticSettingImpl.setInner(DiagnosticSettingImpl.java:24) ~[azure-resourcemanager-monitor-2.21.0.jar!/:2.21.0] 	at com.azure.resourcemanager.resources.fluentcore.model.implementation.IndexableRefreshableWrapperImpl.<init>(IndexableRefreshableWrapperImpl.java:29) ~[azure-resourcemanager-resources-2.21.0.jar!/:2.21.0] 	at com.azure.resourcemanager.resources.fluentcore.model.implementation.CreatableUpdatableImpl.<init>(CreatableUpdatableImpl.java:66) ~[azure-resourcemanager-resources-2.21.0.jar!/:2.21.0] 	at com.azure.resourcemanager.resources.fluentcore.model.implementation.CreatableUpdatableImpl.<init>(CreatableUpdatableImpl.java:55) ~[azure-resourcemanager-resources-2.21.0.jar!/:2.21.0] 	at com.azure.resourcemanager.monitor.implementation.DiagnosticSettingImpl.<init>(DiagnosticSettingImpl.java:39) ~[azure-resourcemanager-monitor-2.21.0.jar!/:2.21.0] 	at com.azure.resourcemanager.monitor.implementation.DiagnosticSettingsImpl.lambda$listByResourceAsync$0(DiagnosticSettingsImpl.java:122) ~[azure-resourcemanager-monitor-2.21.0.jar!/:2.21.0] 	at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193) ~[?:1.8.0_342] 	at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1384) ~[?:1.8.0_342] 	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:482) ~[?:1.8.0_342] 	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:472) ~[?:1.8.0_342] 	at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:708) ~[?:1.8.0_342] 	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[?:1.8.0_342] 	at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:566) ~[?:1.8.0_342] 	at com.azure.resourcemanager.resources.fluentcore.utils.PagedConverter.lambda$mapPagedResponse$6(PagedConverter.java:111) ~[azure-resourcemanager-resources-2.21.0.jar!/:2.21.0] 	at reactor.core.publisher.FluxMap$MapSubscriber.onNext(FluxMap.java:106) ~[reactor-core-3.4.9.jar!/:3.4.9] 	at reactor.core.publisher.FluxTake$TakeSubscriber.onNext(FluxTake.java:128) ~[reactor-core-3.4.9.jar!/:3.4.9] 	at reactor.core.publisher.FluxExpand$ExpandBreathSubscriber.onNext(FluxExpand.java:118) ~[reactor-core-3.4.9.jar!/:3.4.9] 	at reactor.core.publisher.FluxSwitchIfEmpty$SwitchIfEmptySubscriber.onNext(FluxSwitchIfEmpty.java:74) ~[reactor-core-3.4.9.jar!/:3.4.9] 	at reactor.core.publisher.FluxContextWrite$ContextWriteSubscriber.onNext(FluxContextWrite.java:107) ~[reactor-core-3.4.9.jar!/:3.4.9] 	at reactor.core.publisher.FluxMap$MapConditionalSubscriber.onNext(FluxMap.java:220) ~[reactor-core-3.4.9.jar!/:3.4.9] 	at reactor.core.publisher.Operators$MonoSubscriber.complete(Operators.java:1816) ~[reactor-core-3.4.9.jar!/:3.4.9] 	at reactor.core.publisher.MonoFlatMap$FlatMapInner.onNext(MonoFlatMap.java:249) ~[reactor-core-3.4.9.jar!/:3.4.9] 	at reactor.core.publisher.FluxSwitchIfEmpty$SwitchIfEmptySubscriber.onNext(FluxSwitchIfEmpty.java:74) ~[reactor-core-3.4.9.jar!/:3.4.9] 	at reactor.core.publisher.FluxMapFuseable$MapFuseableSubscriber.onNext(FluxMapFuseable.java:127) ~[reactor-core-3.4.9.jar!/:3.4.9] 	at reactor.core.publisher.FluxHandleFuseable$HandleFuseableSubscriber.onNext(FluxHandleFuseable.java:184) ~[reactor-core-3.4.9.jar!/:3.4.9] 	at reactor.core.publisher.Operators$ScalarSubscription.request(Operators.java:2398) ~[reactor-core-3.4.9.jar!/:3.4.9] 	at reactor.core.publisher.FluxHandleFuseable$HandleFuseableSubscriber.request(FluxHandleFuseable.java:250) ~[reactor-core-3.4.9.jar!/:3.4.9] 	at reactor.core.publisher.FluxMapFuseable$MapFuseableSubscriber.request(FluxMapFuseable.java:169) ~[reactor-core-3.4.9.jar!/:3.4.9] 	at reactor.core.publisher.Operators$MultiSubscriptionSubscriber.set(Operators.java:2194) ~[reactor-core-3.4.9.jar!/:3.4.9] 	at reactor.core.publisher.Operators$MultiSubscriptionSubscriber.onSubscribe(Operators.java:2068) ~[reactor-core-3.4.9.jar!/:3.4.9] 	at reactor.core.publisher.FluxMapFuseable$MapFuseableSubscriber.onSubscribe(FluxMapFuseable.java:96) ~[reactor-core-3.4.9.jar!/:3.4.9] 	at reactor.core.publisher.FluxHandleFuseable$HandleFuseableSubscriber.onSubscribe(FluxHandleFuseable.java:154) ~[reactor-core-3.4.9.jar!/:3.4.9] 	at reactor.core.publisher.MonoJust.subscribe(MonoJust.java:55) ~[reactor-core-3.4.9.jar!/:3.4.9] 	at reactor.core.publisher.InternalMonoOperator.subscribe(InternalMonoOperator.java:64) ~[reactor-core-3.4.9.jar!/:3.4.9] 	at reactor.core.publisher.MonoFlatMap$FlatMapMain.onNext(MonoFlatMap.java:157) ~[reactor-core-3.4.9.jar!/:3.4.9] 	at reactor.core.publisher.FluxContextWrite$ContextWriteSubscriber.onNext(FluxContextWrite.java:107) ~[reactor-core-3.4.9.jar!/:3.4.9] 	at reactor.core.publisher.FluxDoOnEach$DoOnEachSubscriber.onNext(FluxDoOnEach.java:173) ~[reactor-core-3.4.9.jar!/:3.4.9] 	at reactor.core.publisher.Operators$MonoSubscriber.complete(Operators.java:1816) ~[reactor-core-3.4.9.jar!/:3.4.9] 	at reactor.core.publisher.MonoFlatMap$FlatMapMain.onNext(MonoFlatMap.java:151) ~[reactor-core-3.4.9.jar!/:3.4.9] 	at reactor.core.publisher.FluxMapFuseable$MapFuseableSubscriber.onNext(FluxMapFuseable.java:127) ~[reactor-core-3.4.9.jar!/:3.4.9] 	at reactor.core.publisher.FluxHide$SuppressFuseableSubscriber.onNext(FluxHide.java:137) ~[reactor-core-3.4.9.jar!/:3.4.9] 	at reactor.core.publisher.FluxMapFuseable$MapFuseableSubscriber.onNext(FluxMapFuseable.java:127) ~[reactor-core-3.4.9.jar!/:3.4.9] 	at reactor.core.publisher.FluxMapFuseable$MapFuseableSubscriber.onNext(FluxMapFuseable.java:127) ~[reactor-core-3.4.9.jar!/:3.4.9] 	at reactor.core.publisher.FluxHide$SuppressFuseableSubscriber.onNext(FluxHide.java:137) ~[reactor-core-3.4.9.jar!/:3.4.9] 	at reactor.core.publisher.FluxMap$MapSubscriber.onNext(FluxMap.java:120) ~[reactor-core-3.4.9.jar!/:3.4.9] 	at reactor.core.publisher.FluxOnErrorResume$ResumeSubscriber.onNext(FluxOnErrorResume.java:79) ~[reactor-core-3.4.9.jar!/:3.4.9] 	at reactor.core.publisher.Operators$MonoSubscriber.complete(Operators.java:1816) ~[reactor-core-3.4.9.jar!/:3.4.9] 	at reactor.core.publisher.MonoFlatMap$FlatMapMain.onNext(MonoFlatMap.java:151) ~[reactor-core-3.4.9.jar!/:3.4.9] 	at reactor.core.publisher.FluxMapFuseable$MapFuseableSubscriber.onNext(FluxMapFuseable.java:127) ~[reactor-core-3.4.9.jar!/:3.4.9] 	at reactor.core.publisher.Operators$MonoSubscriber.complete(Operators.java:1816) ~[reactor-core-3.4.9.jar!/:3.4.9] 	at reactor.core.publisher.MonoFlatMap$FlatMapMain.onNext(MonoFlatMap.java:151) ~[reactor-core-3.4.9.jar!/:3.4.9] 	at reactor.core.publisher.MonoIgnoreThen$ThenIgnoreMain.complete(MonoIgnoreThen.java:284) ~[reactor-core-3.4.9.jar!/:3.4.9] 	at reactor.core.publisher.MonoIgnoreThen$ThenIgnoreMain.onNext(MonoIgnoreThen.java:187) ~[reactor-core-3.4.9.jar!/:3.4.9] 	at reactor.core.publisher.Operators$MonoSubscriber.complete(Operators.java:1816) ~[reactor-core-3.4.9.jar!/:3.4.9] 	at reactor.core.publisher.MonoFlatMap$FlatMapMain.onNext(MonoFlatMap.java:151) ~[reactor-core-3.4.9.jar!/:3.4.9] 	at reactor.core.publisher.MonoCreate$DefaultMonoSink.success(MonoCreate.java:160) ~[reactor-core-3.4.9.jar!/:3.4.9] 	at com.azure.core.http.okhttp.OkHttpAsyncHttpClient$OkHttpCallback.onResponse(OkHttpAsyncHttpClient.java:267) ~[azure-core-http-okhttp-1.11.4.jar!/:1.11.4] 	at okhttp3.internal.connection.RealCall$AsyncCall.run(RealCall.kt:519) ~[okhttp-4.10.0.jar!/:?] 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_342] 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_342] 	at java.lang.Thread.run(Thread.java:750) [?:1.8.0_342] 	Suppressed: java.lang.Exception: #block terminated with an error 		at reactor.core.publisher.BlockingSingleSubscriber.blockingGet(BlockingSingleSubscriber.java:99) ~[reactor-core-3.4.9.jar!/:3.4.9] 		at reactor.core.publisher.Flux.blockLast(Flux.java:2644) ~[reactor-core-3.4.9.jar!/:3.4.9] 		at com.azure.core.util.paging.ContinuablePagedByIteratorBase.requestPage(ContinuablePagedByIteratorBase.java:102) ~[azure-core-1.34.0.jar!/:1.34.0] 		at com.azure.core.util.paging.ContinuablePagedByItemIterable$ContinuablePagedByItemIterator.<init>(ContinuablePagedByItemIterable.java:75) ~[azure-core-1.34.0.jar!/:1.34.0] 		at com.azure.core.util.paging.ContinuablePagedByItemIterable.iterator(ContinuablePagedByItemIterable.java:55) ~[azure-core-1.34.0.jar!/:1.34.0] 		at com.azure.core.util.paging.ContinuablePagedIterable.iterator(ContinuablePagedIterable.java:141) ~[azure-core-1.34.0.jar!/:1.34.0]

**To Reproduce**
Calling SDK methods:
resourceManager.diagnosticSettings().listByResource(resourceId);

***Code Snippet***
AzureResourceManager resourceManager = AzureResourceManager.configure().withHttpClient(httpClient)
.withScope(AzureEnvironment.AZURE).authenticate(tokenCredential, profile)
.withDefaultSubscription();

for (DiagnosticSetting settings : resourceManager.diagnosticSettings().listByResource(resourceId)) {
}

**Expected behavior**
A diagnosticSettings list should be returned.

**Screenshots**

**Setup (please complete the following information):**
OS: Linux
IDE: NA
Library/Libraries: azure-resourcemanager-monitor-2.21.0.jar!/:2.21.0
Java version: 8
App Server/Environment: Tomcat
Frameworks: Spring Boot

If you suspect a dependency version mismatch (e.g. you see `NoClassDefFoundError`, `NoSuchMethodError` or similar), please check out [Troubleshoot dependency version conflict article](https://aka.ms/azsdk/java/dependency/troubleshoot) first. If it doesn't provide solution for the problem, please provide:
- verbose dependency tree (`mvn dependency:tree -Dverbose`)
- exception message, full stack trace, and any available logs

**Additional context**

**Information Checklist**
Kindly make sure that you have added all the following information above and checkoff the required fields otherwise we will treat the issuer as an incomplete report
- [x] Bug Description Added
- [x] Repro Steps Added
- [x] Setup information Added

**Comment by joshfree** [comment]
@weidongxu-microsoft could you please help route this?

**Comment by weidongxu-microsoft** [comment]
Sorry for the late reply.

From the stack, it seems that the `category` of `LogSettings` be null. Checking how this happens. And if it could happen, will add protection.

**Comment by weidongxu-microsoft** [comment]
Fix in https://github.com/Azure/azure-sdk-for-java/pull/33622

Next release will be 2.25.0 in March.
