### ISSUE TITLE
[Perf] Create perf test project for Cosmos

### ISSUE THREAD

**Issue by mikeharder** [Azure/azure-sdk-for-java#32396]
Create a starter perf test project for Cosmos:

1. Copy existing perf test project, say storage-blob
2. Modify perf-resources.bicep to create Cosmos instead of Storage
3. Create test to download a single document from Cosmos

**Comment by kushagraThapar** [comment]
@mikeharder is this still planned to be worked on?

**Comment by mikeharder** [comment]
Not by me. @g2vinay?
