### ISSUE TITLE
[QUERY] Container Registry  ScopeMap and Token management 

### ISSUE THREAD

**Issue by nagendramishr** [Azure/azure-sdk-for-java#32403]
**Query/Question**

Is there roadmap to manage ScopeMap and Tokens in Container Registry?  These are available in the CLI and REST API, but there is not an equivalent option in the JAVA SDK?

https://learn.microsoft.com/en-us/cli/azure/acr/scope-map?view=azure-cli-latest
https://learn.microsoft.com/en-us/cli/azure/acr/token?view=azure-cli-latest

***Why is this not a Bug or a feature Request?***
A clear explanation of why is this not a bug or a feature request?

Customer is looking to manage subscriptions to their container registry in the 20,000 range, and so management capabilities are required programatically.

**Setup (please complete the following information if applicable):**
 - IDE: [e.g. IntelliJ]
 - Library/Libraries: [e.g. com.azure:azure-core:1.16.0 (groupId:artifactId:version)]
 
 **Information Checklist**
 Kindly make sure that you have added all the following information above and checkoff the required fields otherwise we will treat the issuer as an incomplete report
- [ ] Query Added
- [ ] Setup information Added

**Comment by joshfree** [comment]
@lmolkova please take a look

**Comment by XiaofeiCao** [comment]
@nagendramishr `scope-map` and `token` are preview features, which java SDK doesn't support in stable version. We need service to add to their stable version specs before we can support them.

**Comment by weidongxu-microsoft** [comment]
@XiaofeiCao 

Please follow up.

**Comment by XiaofeiCao** [comment]
I saw they added them to latest stable version `2022-12-01` and a [tag](https://github.com/Azure/azure-rest-api-specs/tree/main/specification/containerregistry/resource-manager#tag-package-2022-12) is present, but we haven't got release request for it.

We did got a request for preview: https://github.com/Azure/sdk-release-request/issues/3743. It has the features too. I'll go with this one first.

**Comment by weidongxu-microsoft** [comment]
We may first ask them (maybe just in that preview release request?) about whether 2022-12-01 will be good in Feb.

**Comment by XiaofeiCao** [comment]
@nagendramishr 2.24.0 released with support.

You can find sample code under https://github.com/Azure/azure-sdk-for-java/tree/main/sdk/resourcemanager/azure-resourcemanager/src/samples/java/com/azure/resourcemanager/containerregistry/generated

E.g. 
[ScopeMapsCreateSamples.java](https://github.com/Azure/azure-sdk-for-java/blob/main/sdk/resourcemanager/azure-resourcemanager/src/samples/java/com/azure/resourcemanager/containerregistry/generated/ScopeMapsCreateSamples.java)

[TokensCreateSamples.java](https://github.com/Azure/azure-sdk-for-java/blob/main/sdk/resourcemanager/azure-resourcemanager/src/samples/java/com/azure/resourcemanager/containerregistry/generated/TokensCreateSamples.java)

Future convenience method support in https://github.com/Azure/azure-sdk-for-java/issues/33570.

**Comment by nagendramishr** [comment]
Thank you!
