### ISSUE TITLE
Support for cancellation tokens for synchronous API

### ISSUE THREAD

**Issue by JonathanGiles** [Azure/azure-sdk-for-java#3240]
For the client APIs we are building, we will likely have async and sync APIs. For the async methods, we can support cancellation through unsubscribing from the async publisher. For sync API however we will need to offer a separate mechanism to support cancellation.

In .net this is being implemented by way of a CancellationToken that can be triggered via a separate thread (or timer convenience API that under the hood does this). Due to C# supporting default arguments, this is handled quite nicely there. In Java we do not have equivalent facilities, so we will need to either have an overloaded method for each API that takes a CancellationToken, or we simply put it as a required parameter on all method calls (with null being a valid value). We will need to plumb this down into our http pipeline code such that it has the desired result.

**Comment by anuchandy** [comment]
@JonathanGiles our sync API blocks on async API right?

**Comment by JonathanGiles** [comment]
TBD :-) That would definitely be the simplest approach. One thing I'm not clear on in Reactor is the ability to cancel a blocked async operation from a different thread. I was actually going to put a comment in the issue description (for the async user case), but I deleted it as I didn't want to discuss async blocking as a typical case (for end users). However, now we are talking about the sync implementation, I would love to hear what you know about this topic.

**Comment by jianghaolu** [comment]
Is it more Java to have an execution timeout than some sort of cancellation token? A lot of the Java APIs allow passing in a timeout.

**Comment by JonathanGiles** [comment]
If I were to imagine the most common requirement for cancellation, I would agree that timeout is it. However, I would see a timeout cancellation as a subset of the more generic cancellation token we should offer. In other words, wouldn't it be wiser to have an API such as the following:

```java
public class CancellationToken {
    public void cancel() { ... }
    public boolean isCancelled() { ... }

    public static CancellationToken withTimeout(Duration timeout) { ... }
}
```
This approach enables manual cancellation and time-out based cancellation.

Fwiw, I can totally appreciate the push back on CancellationToken. It is not a concept familiar to Java devs (and it wasn't familiar to me). Please keep pushing back as necessary.

**Comment by anuchandy** [comment]
Users might want to use some dynamic external conditions to decide on cancelling multiple requests on the fly, timeout can be just one of them.

**Comment by anuchandy** [comment]
A dirty way is: 

```java
    class CancellationToken {
        List<Subscription> subscriptions;

        CancellationToken() {
            this.subscriptions = new ArrayList<>();
        }
        
        void add(Subscription subscription) {
            this.subscriptions.add(subscription);
        }
        
        void cancel() {
            this.subscriptions.forEach(s -> s.cancel());
        }
    }
    
    public Foo getFoo(CancellationToken  cancellationToken) {
        return getFooAsync().doOnSubscribe(subscription -> {
            cancellationToken.add(subscription);
            subscription.request(Integer.MAX_VALUE);
        }).block();
    }
    
    public Mono<Foo> getFooAsync() {
        return Mono.empty();
    }
```

We are taking subscription instances from `doOnSubscribe` to outside, which is not a good solution.

**Comment by anuchandy** [comment]
CancellationToken is a subscription container since an instance of it can be used to cancel multiple subscriptions. Related to this: David wrote an entry on subscription container http://akarnokd.blogspot.com/2015/05/operator-concurrency-primitives_19.html

**Comment by JonathanGiles** [comment]
Generally this approach feels like it is on the right path, but I agree we should do better.

**Comment by anuchandy** [comment]
Here you go:

## Sample ServiceClient with Cancellable sync API
```java
class FooClient {
    /**
     * Get a Foo synchronously.
     *
     * @param name name of the Foo
     * @param delay the delay in sec to wait before returning Foo
     * @param token the cancellation token
     * @return the Foo
     * @throws CancellationException upon cancelling this operation
     */
    Foo getFoo(String name, Duration delay, CancellationToken token) {
        return Mono.first(getFooAsync(name, delay), token.cancelMono()).block();
    }

    /**
     * Get a Foo asynchronously. 
     * 
     * @param name name of the Foo
     * @param delay the delay in sec to wait before returning Foo
     * @return the Foo
     */
    Mono<Foo> getFooAsync(String name, Duration delay) {
        return Mono.defer(() -> Mono.delay(delay).then(Mono.just(new Foo(name))));
    }
}

class Foo {
    private String name;

    Foo(String name) {
        this.name = name;
    }

    String name() {
        return this.name;
    }
}
```

## Tests for successful cancellation and unsuccessful cancellation

```java
@Test
public void cancelShouldWin() {
    final long cancelAfterSec = 2;
    final long getFooAfterSec = 5;

    FooClient fooClient = new FooClient();
    //
    CancellationToken token = new CancellationToken();
    //
    final ScheduledThreadPoolExecutor executor = new ScheduledThreadPoolExecutor(4);
    executor.schedule(() -> token.cancel(), cancelAfterSec, TimeUnit.SECONDS);
    //
    //
    CancellationException cancellationException = null;
    try {
        Foo foo1 = fooClient.getFoo("foo1", Duration.ofSeconds(getFooAfterSec), token);
        Assert.assertNotNull(foo1);
    } catch (CancellationException ce) {
        cancellationException = ce;
    }
    // Assert CancellationException is thrown
    Assert.assertNotNull("Excepted CancellationException not thrown" ,cancellationException);
}

@Test
public void cancelShouldIgnored() {
    final long cancelAfterSec = 5;
    final long getFooAfterSec = 2;

    FooClient fooClient = new FooClient();
    //
    CancellationToken token = new CancellationToken();
    //
    final ScheduledThreadPoolExecutor executor = new ScheduledThreadPoolExecutor(4);
    executor.schedule(() -> token.cancel(), cancelAfterSec, TimeUnit.SECONDS);
    //
    //
    CancellationException cancellationException = null;
    try {
        Foo foo1 = fooClient.getFoo("foo1", Duration.ofSeconds(getFooAfterSec), token);
        Assert.assertNotNull(foo1);
    } catch (CancellationException ce) {
        cancellationException = ce;
    }
    // Assert CancellationException is NOT thrown
    Assert.assertNull("UnExcepted CancellationException thrown" ,cancellationException);
}
```

## The CancellationToken, CancellationException types

```java
    /**
     * A CancellationToken capable of cancelling multiple operations.
     */
    static class CancellationToken {
        private SyncWrapper monoSyncWrapper;
        private final Mono<Void> cancelMono;

        /**
         * Creates a CancellationToken.
         */
        CancellationToken() {
            this.cancelMono = Mono.create(sink -> monoSyncWrapper = new SyncWrapper(sink));
        }

        /**
         * A mono that can emits CancellationException upon calling {@link this#cancel()}.
         *
         * @param <T> the type
         * @return cancellation mono
         */
        <T> Mono<T> cancelMono() {
            return this.cancelMono.thenReturn((T) new Object());
        }

        /**
         * Cancel any operation subscribed to {@link this#cancelMono()}.
         */
        void cancel() {
            this.monoSyncWrapper.cancel();
        }

        private class SyncWrapper {
            private final reactor.core.publisher.MonoSink<Void> sync;
            //
            SyncWrapper(reactor.core.publisher.MonoSink<Void> sync) {
                this.sync = sync;
            }

            void cancel() {
                this.sync.error(new CancellationException());
            }
        }
    }

    /**
     * Exception indicating oepration is cancelled.
     */
    static class CancellationException extends RuntimeException {
    }
```

**Comment by anuchandy** [comment]
So above code snippet shows it is technically possible to cancel a sync API derived from async API.

Should we do it? something we need to discuss. This is not idiomatic Java, as you both mentioned the community is familiar with only one way to cancel sync API which is Timeout.

**Comment by JonathanGiles** [comment]
Overall I like this approach. Two things I would like to have explored:

1. It would be nice to abstract the fact that this operates on Mono. I would like to see `cancelMono()` not be part of the public API, because I think it is confusing for users. What I might propose doing is to separate out the concept of cancellation from the implementation. We can wire it together (pretty much as you do above) with an internal util library (e.g:

```java
    Foo getFoo(String name, Duration delay, CancellationToken token) {
        // Move 'first' operator configuration into a 'ReactiveUtils' util class
        return ReactiveUtils.withCancellationToken(getFooAsync(name, delay), token)).block();
    }
```

2. It would be nice to add a convenience API on `CancellationToken` to support timeouts, to make your sample code more succinct. For example, something like `CancellationToken token = CancellationToken.withTimeout(Duration duration)`

Once these are in place I think they should be added into azure-common so that we may build our sync APIs with them in place.

**Comment by JonathanGiles** [comment]
It's hard to determine a good package location for this API. The best place probably is `com.azure.common.util.CancellationToken`, although I don't like having a package with just one class in it (and nor do I like such a generically-named package). @anuchandy Are you going to work on a pull request, or should someone else take this on from here?

**Comment by anuchandy** [comment]
@JonathanGiles did we decide that sync should be implemented by blocking Async?

**Comment by JonathanGiles** [comment]
Not yet. That depends on the http client we decide to use in the sync case, or if we are ok with the implications of sync over async on the http client.

**Comment by anuchandy** [comment]
Ok, I thought CancellationToken is only for sync cases, no? If so  CancellationToken make sense only if sync is over Async. Sync http clients that natively support only timeout won't be able use token unless we run calls in separate threads.

**Comment by JonathanGiles** [comment]
Yep, we are on the same page here. My preference is sync over async, but we need to be careful that we understand the threading implications of this design choice, in terms of overwhelming the async http client. If we can confirm to ourselves this won't be an issue, or that we can configure it such that it won't be, then I think we have everything lined up.

**Comment by jianghaolu** [comment]
> Please keep pushing back as necessary.

We have one person from .NET backgrounds in our UX study who was trying to add `await` keyword to our method when we hinted that the method is async. I can't start to imagine what people will do when they see such a .NET-ish method `Foo getFoo(String name, Duration delay, CancellationToken token)`. 

These are why timeout is a more idiomatic approach to Java developers:
https://projectreactor.io/docs/core/release/api/reactor/core/publisher/Flux.html#blockFirst-java.time.Duration- (using timeout in our code will also make it consistent with Reactor)
https://projectreactor.io/docs/core/release/api/reactor/core/publisher/Flux.html#timeout-java.time.Duration- 
https://github.com/reactor/reactor-netty/blob/master/src/main/java/reactor/netty/resources/ColocatedEventLoopGroup.java#L95
https://github.com/reactor/reactor-netty/blob/master/src/main/java/reactor/netty/tcp/TcpClient.java#L217
https://docs.oracle.com/javase/8/docs/api/index.html?java/util/concurrent/Future.html
...

**Comment by JonathanGiles** [comment]
Timeout is a subset of use cases though. What happens if there is simply some external trigger that may happen that would seek to cancel a sync operation? Once the sync operation is started, this would be impossible?

**Comment by anuchandy** [comment]
Restricting to cancellation based on only timeout can be limiting, agree, but still wondering why community never complained about it. Even the newest/greatest reactor community also decided to go with timeout, even though it was quite easy for them to support cancellation but they didn't (we prototyped it in few hrs). So technically it is possible but should we deviate from well known pattern and introduce it to our customers, I'm not sure. Also for C# world, CancellationToken is well known concept. Most importantly .NET SDK is using CancellationToken for both async and async, which is consistent.

**Comment by jianghaolu** [comment]
In reactor a Subscription is a Cancellation. So users get the Subscription object on subscribe() which they can cancel on. But again, all these bells and whistles are exactly why we are making a sync client separate from the async one.

**Comment by anuchandy** [comment]
`Even the newest/greatest reactor community also decided to go with timeout, even though it was quite easy for them to support cancellation but they didn't` -> I mean reactor's blocking API takes timeout not anything equivalent CancellationToken. Yes, cancellation  of async call is subscription based.

**Comment by JonathanGiles** [comment]
I can appreciate why Reactor, etc do not take a cancellation token - because they are async and the user can easily unsubscribe from a subscription to enable this cancellation. Once you remove the need for a CancellationToken, it flows quite logically to introduce a timeout mechanism as a duration. This means that on-demand and duration-based timeout are both supported in reactor cleanly.

In the case of a synchronous method call that blocks execution, this is not possible as we have no subscription available to us, and duration-based timeout limits us to only one form of cancellation. How do we cancel on-demand, from some external event?

As an aside: I'm not sure if the Reactor `blockFirst(Duration)` (and similar) methods on Flux allow for the subscription to be unsubscribed from in a separate thread whilst blocked? If so, then the Reactor API allows for on-demand and duration-based cancellation too.

I'm not entirely sure what the `Foo getFoo(String name, Duration delay, CancellationToken token)` method `delay` parameter is for in the comment above. If it is related to the timeout, then I wouldn't advocate for having that as an argument into sync methods. We would simply have `Foo getFoo(String name, CancellationToken token)`, where the user could call it with any of the following arguments:

```java
Foo foo = getFoo("Bar") // CancellationToken will probably be in an overload. User will not be able to cancel
Foo foo = getFoo("Bar", null) // user will not be able to cancel
Foo foo = getFoo("Bar", CancellationToken.NONE) // user will not be able to cancel
Foo foo = getFoo("Bar", CancellationToken.withTimeout(Duration.seconds(10))) // Will cancel in 10 seconds

CancellationToken ctx = new CancellationToken();
Foo foo = getFoo("Bar", ctx) // user can cancel on-demand with ctx.cancel()
```

**Comment by jianghaolu** [comment]
```java
CancellationToken ctx = new CancellationToken();
Foo foo = getFoo("Bar", ctx) // user can cancel on-demand with ctx.cancel()
```

> user can cancel on-demand with ctx.cancel()

So the user have to create another thread to cancel it? I thought we are designing for synchronous API?

If a simple threading is allowed for our "synchronous API", I guess we can simply return CompletableFuture as an overload which provides every feature CancellationToken has to offer and is one of the most well-known types in the Java community.

**Comment by JonathanGiles** [comment]
Yes, this is just for sync API and yes, another thread will be required. As I understand it, this is the same approach taken with .net sync APIs. Returning CompletableFuture in a sync API means it isn't a sync API anymore! :-)

**Comment by jianghaolu** [comment]
I'm not a .NET expert, but in my understanding, anything requiring the user to knowingly create or interactive with another thread is in the async territory. My humble opinion is that it's actually easier to work with a CompletableFuture than creating another thread myself to work with a CancellationToken.

**Comment by jianghaolu** [comment]
Can we call it the simple API vs advanced API instead? I think the initial goal for the sync client is to provide beginners with something easier to use so that the cases in the UX studies won't happen again. I don't think they had anything against async per se, but types or patterns that they've never seen as Java developers (like RxJava in their case). 

How many Java developers know RxJava? And how many know CancellationToken? Are we really seeing the real problem here?

**Comment by JonathanGiles** [comment]
I just discussed this further and we might be able to push back on cancellation altogether. Let's table this for now and I'll try to prevent us from needing to go down this path.

**Comment by JonathanGiles** [comment]
I'm going to close this. The spec says cancellation tokens are required for async operations. It says nothing to sync ops.

**Comment by JonathanGiles** [comment]
As discussed offline, I am reopening this issue. Cancellation tokens will be introduced as azure-core API for the sync API case. However, the current thinking is that we will not provide API that directly accepts a cancellation token, instead, we will permit developers to put the cancellation token into the context that all sync methods will provide.
