### ISSUE TITLE
[Discuss] Enable a way to choose between Exponential vs Fixed retry for RetryPolicy

### ISSUE THREAD

**Issue by anuchandy** [Azure/azure-sdk-for-java#3241]
Explore the following operators:

1. https://projectreactor.io/docs/core/release/api/reactor/core/publisher/Mono.html#retry-long-
2. https://projectreactor.io/docs/core/release/api/reactor/core/publisher/Mono.html#retryBackoff-long-java.time.Duration-java.time.Duration-double-

**Comment by mrm9084** [comment]
The App Configuration Service team would be interested in this being implemented. The App Configuration Provider currently has this being added, but when we switch over to using the SDK it would be lost.
