### ISSUE TITLE
[BUG] NullPointerException when returning null value from ManagedClusterInner method

### ISSUE THREAD

**Issue by fernandalaiss** [Azure/azure-sdk-for-java#32445]
**Describe the bug**
The exception happens in the line 223 from KubernetesClusterImpl.java, in the addonProfiles() method return. The Collections.unmodifiableMap() can't receive a null value and the the implementation in its parameter allows a null value.

**Exception or Stack Trace**
```
java.lang.NullPointerException: null

	at java.base/java.util.Collections$UnmodifiableMap.<init>(Collections.java:1446)

	at java.base/java.util.Collections.unmodifiableMap(Collections.java:1433)

	at com.azure.resourcemanager.containerservice.implementation.KubernetesClusterImpl.addonProfiles(KubernetesClusterImpl.java:229)
```

**To Reproduce**
1. By the com.azure.resourcemanager.containerservice.models.KubernetesCluster listed, based on azure [documentation](https://learn.microsoft.com/en-us/rest/api/aks/managed-clusters/list?tabs=Java), we can access the attributes ManagedClusterProperties innerProperties or Map<String, ManagedClusterAddonProfile> addonProfiles with a nullable value;
```
List<KubernetesCluster> kbClusters = azure.kubernetesClusters().list().stream().collect(Collectors.toList());
```

2. Put a breakpoint into KubernetesClusterImpl, line 229, return of the method addonProfile()

3. Perform a kubernetesCluster.addonProfiles()
```
kubernetesClusters.forEach(kubernetesCluster -> kubernetesCluster.addonProfiles());
```

4. Evaluate the expression
```
Collections.unmodifiableMap(this.innerModel().addonProfiles())
```

5. Check the cases where 
- ManagedClusterProperties innerProperties == null
- Map<String, ManagedClusterAddonProfile> addonProfiles == null

**Code Snippet**
KubernetesClusterImpl.java
![image](https://user-images.githubusercontent.com/48069396/205679489-5a7b318b-adf2-44df-bb0e-54e6944bd448.png)

ManagedClusterInner.java
![image](https://user-images.githubusercontent.com/48069396/205679585-0f6c0db1-7a59-4a87-8462-9878305244d3.png)

**Expected behavior**
addonProfiles() need to verify if KubernetesClusterImpl.innerModel().addonProfiles() its null before create a new Collections.unmodifiableMap() with this nullable data.

**Setup**
 - OS: Windows
 - IDE: IntelliJ
 - Library/Libraries: com.azure.resourcemanager:2.17.0
 - Java version: 11
 - App Server/Environment: Intellij
 - Frameworks: Spring 

**Information Checklist**
Kindly make sure that you have added all the following information above and checkoff the required fields otherwise we will treat the issuer as an incomplete report
- [x] Bug Description Added
- [x] Repro Steps Added
- [x] Setup information Added

**Comment by joshfree** [comment]
@weidongxu-microsoft could you please help route this issue? thank you

**Comment by XiaofeiCao** [comment]
Thanks @fernandalaiss , we'll fix this npe in our next release.

**Comment by fernandalaiss** [comment]
@XiaofeiCao In which release will the fix be available?

**Comment by XiaofeiCao** [comment]
Hi @fernandalaiss 

2.22.0 has been released today and the fix is available.
