### ISSUE TITLE
[FEATURE REQ] Spring Cloud Azure Overview Doc

### ISSUE THREAD

**Issue by stliu** [Azure/azure-sdk-for-java#32459]
# Overview doc

## Problem

We don't have an overview doc to answer the question of 'what is Spring Cloud Azure' nor providing the whole picture to customers.

what we currently have are:

* https://learn.microsoft.com/en-us/azure/developer/java/spring-framework/spring-boot-starters-for-azure
* https://spring.io/projects/spring-cloud-azure
* https://learn.microsoft.com/en-us/azure/developer/java/spring-framework/spring-cloud-azure?tabs=maven

## Goal

* Having a Overview doc for Spring Cloud Azure product
* The doc follows [this instruction](https://review.learn.microsoft.com/en-us/help/patterns/level4/article-overview?branch=main) and [template](https://review.learn.microsoft.com/en-us/help/patterns/level4/global-overview-template?branch=main)
* it should has some overview pictures like [this one](https://microsoftapc.sharepoint.com/:p:/t/ManagedservicesforSpringDevelopers/EU6-DCHkk_9Eu0mFVcWL4BsBrSKGj-R1OC6PSHHs08XBLA) page 9
* answer these two questions
	* What is it?
	- What is it used for?

#### ToC of overview doc

According to the guideline from [this](https://review.learn.microsoft.com/en-us/help/patterns/level4/article-overview?branch=main#add-to-your-toc), we should have this overview like this in our product toc.

* Spring Cloud Azure Documentation
* Overview
	* What is Spring Cloud Azure?
	* Compare Azure SDK for Java

**Comment by stliu** [comment]
@chenrujun  let me know if you have any questions.

following up actions
1. Read [this](https://review.learn.microsoft.com/en-us/help/patterns/level4/article-overview?branch=main) and understand what's overview
2. Having a outline of `What is Spring Cloud Azure?` doc


the doc of _Compare Azure SDK for Java_ is not in the same priority, we can just ignore it for now, but I think we should have a doc in the Overview section to answer:

* when should use what
* these two are not exclusive each other

**Comment by stliu** [comment]
@chenrujun just for the record, could you document the goal and agreement about this feature here as we discussed?

**Comment by chenrujun** [comment]
> @chenrujun just for the record, could you document the goal and agreement about this feature here as we discussed?

@stliu 

### Goal:

Publish a new document `Spring Cloud Azure Overview` which can help customer know:
1. What it is?
2. What is used for?

### Agreement:
1. The doc follows [this instruction](https://review.learn.microsoft.com/en-us/help/patterns/level4/article-overview?branch=main) and [template](https://review.learn.microsoft.com/en-us/help/patterns/level4/global-overview-template?branch=main)
2. Give the TOC first.
3. The document should be scenario based. `scenario based` means stand on the customer's view, think about what's the customer's requirement?
4. It's better to give an example like this: Without Spring Cloud Azure, you should ..., With Spring Cloud Azure, it's much easier, you just need ...

**Comment by stliu** [comment]
@chenrujun could you update the discussion conclusion here for each meeting?

**Comment by chenrujun** [comment]
> @chenrujun could you update the discussion conclusion here for each meeting?

Sure.

Here is the conclusion in last meeting:

TOC:
```
# What is Spring Cloud Azure used for 
  ## image
# Benefits of Spring Cloud Azure
# Components of Spring Cloud Azure (delete getting started overview)
# Get Support
```

**Comment by stliu** [comment]
what's the status of this one?

**Comment by chenrujun** [comment]
> what's the status of this one?

@stliu 
PR created: https://github.com/MicrosoftDocs/azure-dev-docs-pr/pull/3972
Waiting for @KarlErickson's review.

**Comment by chenrujun** [comment]
Update:

1. This PR is merged: https://github.com/MicrosoftDocs/azure-dev-docs-pr/pull/3972
2. Here is the link to overview page: https://learn.microsoft.com/en-us/azure/developer/java/spring-framework/spring-cloud-azure-overview
3. Next step: 
3.1. Delete this page:
![image](https://user-images.githubusercontent.com/13167207/215238592-1f61a548-db36-4277-a0ed-987e57060b15.png)
3.2. Sync the content to this page: https://spring.io/projects/spring-cloud-azure
![image](https://user-images.githubusercontent.com/13167207/215238648-a86e0378-dc8a-4647-ac7e-f5a4100bcf91.png)

**Comment by chenrujun** [comment]
Update:

> 3.1. Delete this page:

PR created: https://github.com/MicrosoftDocs/azure-dev-docs-pr/pull/4111

**Comment by chenrujun** [comment]
Update: 
 - [x] https://github.com/MicrosoftDocs/azure-dev-docs-pr/pull/3972
 - [x] https://github.com/MicrosoftDocs/azure-dev-docs-pr/pull/4111
 - [ ] https://spring.io/projects/spring-cloud-azure This page updated, but there are some errors like wrong link. Already ask related person updating it.

**Comment by chenrujun** [comment]
Closing this issue because all tasks have been finished.
