### ISSUE TITLE
[BUG] StorageAccount class infrastructureEncryptionEnabled() always returns false

### ISSUE THREAD

**Issue by gabrielspaulino** [Azure/azure-sdk-for-java#32470]
**Describe the bug**
The return of the method infrastructureEncryptionEnabled() in the line 47 from StorageAccount.class is always false, even when the Storage account in question has infrastructure encryption enabled in Azure.

**To Reproduce**
1. By the com.azure.resourcemanager.storage.models.StorageAccount listed it is possible to access the method infrastructureEncryptionEnabled().
`List<StorageAccount> storageAccounts = azure.storageAccounts().list().stream().collect(Collectors.toList());`
2. Put a breakpoint into StorageAccountImpl class, line 123, in the return of the method infrastructureEncryptionEnabled()
3. Evaluate `this.name()` and `this.encryptionHelper.infrastructureEncryptionEnabled()`
4. Check if infrastructureEncryptionEnabled() return matches the state of the StorageAccount infrastructure encryption in Azure

***Code Snippet***
StorageAccountImpl.class
![image](https://user-images.githubusercontent.com/78971112/205924281-6e4f5376-8fa6-4532-8ba3-995d5fba6cf5.png)

**Expected behavior**
The method infrastructureEncryptionEnabled() should return true when infrastructure encryption is enabled.

**Screenshots**
Storage account in Azure:
![issue azure](https://user-images.githubusercontent.com/78971112/205928875-281b4f65-54f9-4ab6-bd26-2ff2e2ae4f13.png)

infrastructureEncryptionEnabled() method return for the Storage Account above:
![image](https://user-images.githubusercontent.com/78971112/205946181-d57e463a-3d33-44b6-ac31-bbb134aad84d.png)

**Setup (please complete the following information):**
 - OS: Windows
 - IDE: IntelliJ
 - Library/Libraries: com.azure.resourcemanager:2.17.0
 - Java version: 11
 - App Server/Environment: Intellij
 - Frameworks: Spring

**Information Checklist**
Kindly make sure that you have added all the following information above and checkoff the required fields otherwise we will treat the issuer as an incomplete report
- [x] Bug Description Added
- [X] Repro Steps Added
- [X] Setup information Added

**Comment by joshfree** [comment]
@weidongxu-microsoft could you please follow up with @gabrielspaulino on this github issue?

**Comment by weidongxu-microsoft** [comment]
@gabrielspaulino 

Quick question. Does the value from a storage account retrived by `getByResourceGroup` or `getById` correct?

**Comment by gabrielspaulino** [comment]
@weidongxu-microsoft it doesn't either. Always false also

**Comment by weidongxu-microsoft** [comment]
Thanks.

@XiaofeiCao Could you take a look?

**Comment by gabrielspaulino** [comment]
Thanks @XiaofeiCao. Do you have any forecast for when and in which version it will be available?

**Comment by XiaofeiCao** [comment]
@gabrielspaulino It'll be available in 2.23.0 around 1/30.

**Comment by gabrielspaulino** [comment]
Ok, thank you :)
