### ISSUE TITLE
Java SDK  PR's ci shows hundreds of tests pass when there is no test

### ISSUE THREAD

**Issue by dw511214992** [Azure/azure-sdk-for-java#32489]
Example: https://github.com/Azure/azure-sdk-for-java/pull/32462/checks?check_run_id=9908320847

**Comment by dw511214992** [comment]
Hi @alzimmermsft  I still find there are 53 tests passed when there is no test. Could you please check it?
https://github.com/Azure/azure-sdk-for-java/pull/32462/checks?check_run_id=9957837443

**Comment by alzimmermsft** [comment]
> Hi @alzimmermsft I still find there are 53 tests passed when there is no test. Could you please check it? https://github.com/Azure/azure-sdk-for-java/pull/32462/checks?check_run_id=9957837443

That PR will need to pull the latest changes from main in order for the other tests to no longer show in the result

**Comment by dw511214992** [comment]
Hi @alzimmermsft  I have merged the main branch to include the latest change, but still get 53 tests passed.
https://github.com/Azure/azure-sdk-for-java/pull/32462/checks?check_run_id=10028339382

**Comment by alzimmermsft** [comment]
@dw511214992, you made no mistakes, looks like there is one more location where DevOps is getting tests results from (which I haven't figured out where yet). It does look like the pipeline runs have dropped from about 300-350 tests results down to about 50, so most of this has been resolved. I'll try to find where the last few test results are coming from.
