### ISSUE TITLE
[FEATURE REQ] Design a uniform template for Spring getting started docs

### ISSUE THREAD

**Issue by fangjian0423** [Azure/azure-sdk-for-java#32491]
## Problem

There are different ways to create spring project in different Spring getting started docs:

1. some docs use Spring Initializr UI to create a project, and provide a screenshoot. For examples, [Azure Active Directory](https://learn.microsoft.com/en-us/azure/developer/java/spring-framework/configure-spring-boot-starter-java-app-with-azure-active-directory), [Azure Active Directory B2C](https://learn.microsoft.com/en-us/azure/developer/java/spring-framework/configure-spring-boot-starter-java-app-with-azure-active-directory-b2c-oidc) and [Azure Event Hubs](https://learn.microsoft.com/en-us/azure/developer/java/spring-framework/configure-spring-cloud-stream-binder-java-app-azure-event-hub)
2. some docs use Spring Initializr UI to create a project, but don't provide a screenshoot. For example, [Azure Service Bus](https://learn.microsoft.com/en-us/azure/developer/java/spring-framework/configure-spring-cloud-stream-binder-java-app-with-service-bus)
3. some docs use curl command to request Spring Initializr to create a project. For examples, [JPA with Azure PostgreSQL](https://learn.microsoft.com/en-us/azure/developer/java/spring-framework/configure-spring-data-jpa-with-azure-postgresql?tabs=passwordless), [JDBC with Azure PostgreSQL](https://learn.microsoft.com/en-us/azure/developer/java/spring-framework/configure-spring-data-jdbc-with-azure-postgresql?tabs=passwordless)
4. some docs have 2 ways to create project, Create an app without Spring Initializr and Create an app with Spring Initializr. For example, [Azure Key Vault secrets](https://learn.microsoft.com/en-us/azure/developer/java/spring-framework/configure-spring-boot-starter-java-app-with-azure-key-vault#create-an-app-with-spring-initializr)

Some suggestion:

- Screenshoot will be expired. As we know, the UI of Spring Initializr changed several times(we can refer this [blog](https://spring.io/blog/2019/03/05/spring-initializr-new-ui)).  So it's not recommend to use screenshoot.
- The default value of request will change. For example, the default build type is `gradle` now, but earlier time it is `maven`. So it is not recommend to use default parameter value.
- Make sure to select the right dependency in Spring Initializr. For example,  [Azure Cosmos DB Starter](https://learn.microsoft.com/en-us/azure/developer/java/spring-framework/configure-spring-boot-starter-java-app-with-cosmos-db#create-a-spring-boot-application-with-the-spring-initializr) don't select Azure Cosmos DB in Spring Initializr, and need to add the dependency to `pom.xml` manually.

Different and wrong ways to create Spring project will make customer confuse.

## Goal

Design a uniform template for Spring getting started docs.

**Comment by hui1110** [comment]
The initial template is as follows, it may need to be improved.

### Title

Introduction to this article.

- Prerequisites

- Sample application(MySQL/PostgreSQL/SQL Server)

- Prepare the working environment(MySQL/PostgreSQL/SQL Server)

- Provision Azure Resource

   - Create an Azure service(MySQL/PostgreSQL/Key Vault) instance

   - Multiple steps(Different services will have some different steps. Configure firewall, create DB, permission, etc.)


- Create a Spring Boot application

   - Generate the application on the command line(curl) by entering(Can be generated using Spring Initializr):

   - Use the Azure Service starter (**Dependencies that cannot be added in Spring Initializr need to be added manually**).

- Configure the app for your Azure service

   - Code the application

      - Other scenarios

      - Multiple steps

   - Build and test your app

- Deploy to Azure Spring Apps

- Clean up resources

- Next steps


There are some [problems](https://dev.azure.com/azure-spring-integration/spring-integration-private/_wiki/wikis/spring-integration-private.wiki/408/Problems-in-MS-Docs) that need to be confirmed.

**Comment by fangjian0423** [comment]
Could you add some examples for the template? Don't know the meaning of some sections.

- For the `Sample application(MySQL/PostgreSQL/SQL Server)`:

Does it means the sample in https://github.com/Azure-Samples/azure-spring-boot-samples?

- For the `Prepare the working environment(MySQL/PostgreSQL/SQL Server)`:

Does it means we should install the required tools in local?

- For the `Configure the app for your Azure service`:

what does the `Other scenarios` means?

Other suggestions:

- Provision Azure Resource

Use 2 tabs to split CLI and Portal looks good.

- Deploy to Azure Spring Apps

Change it to "Deploy to Azure Hosting Environment", then use 5 tabs:  `Azure Spring Apps`, `Azure App Service`, `AKS`, `Azure Container Apps` and `VM`.

Default tab is `Azure Spring Apps`.

**Comment by hui1110** [comment]
- For the Sample application(MySQL/PostgreSQL/SQL Server)

> Could you add some examples for the template? Don't know the meaning of some sections.
> 
> * For the `Sample application(MySQL/PostgreSQL/SQL Server)`:
> 
> Does it means the sample in https://github.com/Azure-Samples/azure-spring-boot-samples?
> 
> * For the `Prepare the working environment(MySQL/PostgreSQL/SQL Server)`:
> 
> Does it means we should install the required tools in local?
> 
> * For the `Configure the app for your Azure service`:
> 
> what does the `Other scenarios` means?
> 
> Other suggestions:
> 
> * Provision Azure Resource
> 
> Use 2 tabs to split CLI and Portal looks good.
> 
> * Deploy to Azure Spring Apps
> 
> Change it to "Deploy to Azure Hosting Environment", then use 5 tabs: `Azure Spring Apps`, `Azure App Service`, `AKS`, `Azure Container Apps` and `VM`.
> 
> Default tab is `Azure Spring Apps`.

updated.

**Comment by hui1110** [comment]
Will use to change a document to see the effect.
