### ISSUE TITLE
How to make a Spring-extended library support Spring Native?#Moary

### ISSUE THREAD

**Issue by backwind1233** [Azure/azure-sdk-for-java#32537]
Title: How to make a Spring-extended library support Spring Native?

Author: @moarychan

Outline:

1. Brief introduction for Spring Native
2. Solution
   2.1. How Spring Native support its own libraries?
   2.2. Solution
      2.2.1 Embedding configuration files
      2.2.2 Extending spring-native-configuration support
      2.2.3 Each library is implemented independently or as a whole with one library
3 How Spring Cloud Azure support Spring Native?

**Comment by stliu** [comment]
https://github.com/microsoft/spring-cloud-azure/discussions/categories/blog-proposal
