### ISSUE TITLE
How to use Spring Cloud Stream binder for Azure Service Bus Queue by retrieving connection string via ARM

### ISSUE THREAD

**Issue by backwind1233** [Azure/azure-sdk-for-java#32539]
How to use Spring Cloud Stream binder for Azure Service Bus Queue by retrieving connection string via ARM
Title: How to use Spring Cloud Stream binder for Azure Service Bus Queue by retrieving connection string via ARM

Author: @v-muyaofeng

Outline:

1. Brief introduction 
  1.1 library: spring-cloud-azure-stream-binder-servicebus 
  1.2 Service Principal
  1.3 use ARM to get connection-string
2. Sample showing

**Comment by stliu** [comment]
close, this is not following the best practice to build secure application
