### ISSUE TITLE
Build Application With Kotlin and Spring Cloud Azure

### ISSUE THREAD

**Issue by backwind1233** [Azure/azure-sdk-for-java#32540]
Build Application With Kotlin and Spring Cloud Azure
Title: Build Application With Kotlin and Spring Cloud Azure

Author: @backwind1233

Description:

Outline:

Build Application With Kotlin and Spring Cloud Azure
1. Create the Kotlin Application with Spring Initializr
2. Writing Code
	2.1 Secure App With Azure Active Directory
	2.2 Sending and Receiving Messages With Servicebus
	2.3 Retrieve Multiple Secrets from Azure Key Vault
3. Provision Azure Resources
4. Running and Testing

**Comment by stliu** [comment]
let's not use this issue for blog proposal , but this go here https://github.com/microsoft/spring-cloud-azure/discussions/categories/blog-proposal
