### ISSUE TITLE
Develop a Spring Boot Web Application Which Support Login by Microsoft Work or School Account

### ISSUE THREAD

**Issue by backwind1233** [Azure/azure-sdk-for-java#32541]
1. Introduction of Spring Security and Microsoft Work or School Account
2. Develop a Spring Boot Web Application Which Support Login by Microsoft Work or School Account
  2.1. Create Application by Spring Initializer
  2.2. Modify the Application
  2.3. Run Application and Validate Result
3. Reference

**Comment by stliu** [comment]
what's this?

**Comment by stliu** [comment]
and the priority feild is not supposed to be set

**Comment by stliu** [comment]
https://github.com/microsoft/spring-cloud-azure/discussions/categories/blog-proposal
