### ISSUE TITLE
Accessing Graph API from custom AadOAuth2UserService

### ISSUE THREAD

**Issue by martfol** [Azure/azure-sdk-for-java#32567]
**Query/Question**
Hi guys, I'd like to ask you for help with my current issue. We're integrating Azure AD into our spring boot 2.6.8 application and currently we have a task to add a custom property (let's call it "personal number") into the User's SecurityContext after logging in. This value can be only obtained by accessing the UserMe endpoint of the Graph API. Our current approach is that we've created our own _CustomOidcUser_ extending the _DefaultOidcUser_ (to store the new custom property) and our own _CustomAadOAuth2UserService_ (extending the _AadOAuth2UserService_) with overriden _loadUser(OidcUserRequest userRequest)_ method. However we can't figure out how to obtain the OAuth2AuthorizedClient at this point?

**CustomAadOAuth2UserService** 
```
  @Autowired
  private CustomGraphClient customGraphClient;

  @Override
  public OidcUser loadUser(OidcUserRequest userRequest) throws OAuth2AuthenticationException {
    OidcUser oidcUser = super.loadUser(userRequest);
    OAuth2AuthorizedClient graph; // where from?
    return new CustomOidcUser(oidcUser.getAuthorities(), oidcUser.getIdToken(), oidcUser.getUserInfo(),
        customGraphClient.getPersonalNumber(graph));
  }
```

**CustomGraphClient**
```
  private String graphMeEndpoint = "https://graph.microsoft.com/v1.0/me";

  @Autowired
  private WebClient webClient;

  public String getPersonalNumber(OAuth2AuthorizedClient graph) {
    return webClient
        .get()
        .uri(graphMeEndpoint)
        .attributes(oauth2AuthorizedClient(graph))
        .retrieve()
        .bodyToMono(String.class)
        .block();
  }
```

**WebClient**
```
  @Bean
  public WebClient webClient(OAuth2AuthorizedClientManager oAuth2AuthorizedClientManager) {
    ServletOAuth2AuthorizedClientExchangeFilterFunction function =
        new ServletOAuth2AuthorizedClientExchangeFilterFunction(oAuth2AuthorizedClientManager);
    return WebClient.builder()
        .apply(function.oauth2Configuration())
        .build();
  }
```

This setup works, when we resolve the OAuth2AuthorizedClient directly in the controller as a method parameter using _@RegisteredOAuth2AuthorizedClient("graph")_ as suggested in several tutorials. However we don't know how to obtain this object within the _loadUser_ method above. There are several tutorials suggesting using a _AuthorizedClientServiceOAuth2AuthorizedClientManager_ for such purposes, but we haven't found any straightforward example for the use case with Azure AD. Can you please provide any tips, how to solve this? Or maybe if there is any other/easier solution how to access the Graph API from our CustomAadOAuth2UserService.loadUser method to read the custom property and to add it to our CustomOidcUser - please let us know... Any tips/ideas are welcome, go-live is coming soon :-)

PS: I just tested this way of obtaining the OAuth2AuthorizedClient: https://github.com/Azure-Samples/azure-spring-boot-samples/blob/spring-cloud-azure_4.4.1/aad/spring-cloud-azure-starter-active-directory/web-client-access-resource-server/aad-resource-server-obo/src/main/java/com/azure/spring/sample/aad/controller/SampleController.java#L49

... and apparently there still no SecurityContext set at this point of code. So I guess that's why it's not possible to obtain the OAuth2AuthorizedClient - is that right?

***Why is this not a Bug or a feature Request?***
It's apparently neither a bug nor a feature request, but a request for help and more examples in the documentation :-)

**Setup (please complete the following information if applicable):**
 - IDE: IntelliJ 2022.1.4 (Ultimate Edition)
 - Library/Libraries: spring-boot 2.6.8, spring-cloud-azure 4.4.1
 
 **Information Checklist**
 Kindly make sure that you have added all the following information above and checkoff the required fields otherwise we will treat the issuer as an incomplete report
- [x] Query Added
- [x] Setup information Added

**Comment by chenrujun** [comment]
Hi, @martfol . Thanks for reaching out.

## If you want to call Graph API in CustomAadOAuth2UserService 
To access Graph API. You just need an access token. OAuth2AuthorizedClient is not required. For example: `AadOAuth2UserService` already use the access token to get group information. Refs: https://github.com/Azure/azure-sdk-for-java/blob/d41e9d444abfdaf23da77249e9a0308c882eab24/sdk/spring/spring-cloud-azure-autoconfigure/src/main/java/com/azure/spring/cloud/autoconfigure/aad/implementation/webapp/AadOAuth2UserService.java#L126

## Maybe it's not necessary to call Graph API
> currently we have a task to add a custom property (let's call it "personal number") into the User's SecurityContext after logging in.

Which property are you adding? If the property can be added into ID token, it's not necessary to call Graph API. The claims in the ID token will be added into OidcUser.
Refs: https://learn.microsoft.com/en-us/azure/active-directory/develop/active-directory-optional-claims

**Comment by martfol** [comment]
Hi @chenrujun , thanks for your quick reply! You're right, I missed the fact that there is already a _GraphClient_ in the _AadOAuth2UserService_. So I was able to implement my own _CustomGraphClient_ using just the access token based on the example usage of the existing _GraphClient_. So it works now, thanks a lot for your help!
