### ISSUE TITLE
Reading a value from Graph UserMe and adding it as a custom property to the user's SecurityContext

### ISSUE THREAD

**Issue by martfol** [Azure/azure-sdk-for-java#32568]
**Query/Question**
Hi guys, as a follow up of [32567](https://github.com/Azure/azure-sdk-for-java/issues/32567), I'd like to ask a general question, because maybe the technical solution should look totally different than our initial approach mentioned in the previous issue.

After the login, we would like to enrich the security context of a user, who authenticates via Azure AD, by an additional custom property ("personalNumber"). To obtain this value, we need to call the UserMe Graph endpoint (using the credentials of the same user, without having him to log in again) and read it from there.

Is our approach of creating _CustomOidcUser_ extending the _DefaultOidcUser_ (to store the new custom property) and  _CustomAadOAuth2UserService_ (extending the _AadOAuth2UserService_) with overriden _loadUser(OidcUserRequest userRequest)_ correct, or is there a better way to achieve this?

Is there please any sample code dealing with this, or does anyone please have any recommendations how to approach this?

Thanks a lot in advance

***Why is this not a Bug or a feature Request?***
It's neither a bug nor a feature request, but a request for help/advice...

**Setup (please complete the following information if applicable):**
 - IDE: IntelliJ 2022.1.4 (Ultimate Edition)
 - Library/Libraries: spring-boot 2.6.8, spring-cloud-azure 4.4.1
 
 **Information Checklist**
 Kindly make sure that you have added all the following information above and checkoff the required fields otherwise we will treat the issuer as an incomplete report
- [x] Query Added
- [x] Setup information Added

**Comment by chenrujun** [comment]
> Is there please any sample code dealing with this, or does anyone please have any recommendations how to approach this?

Now there is no sample code.

Which property are you adding? If the property can be added into ID token, it's not necessary to call Graph API. The claims in the ID token will be added into OidcUser.
Refs: https://learn.microsoft.com/en-us/azure/active-directory/develop/active-directory-optional-claims

**Comment by martfol** [comment]
Hi @chenrujun , thanks for your reply! Yes, passing the value within the ID token would be the best/easiest solution, however the client's security team didn't let this happen for some internal reason. However your solution using just the access token worked, so let's consider this topic solved. Thanks again for your time!
