### ISSUE TITLE
Authenticate to Azure Key Vault from the app/service running onprem

### ISSUE THREAD

**Issue by zeppelinux** [Azure/azure-sdk-for-java#32577]
It's not clear how to authenticate to Azure Key Vault from the app/service running onprem (for example in onprem Kubernetes Cluster). Is this supported?

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 35f40858-8637-e7db-8803-63fd8d5feeb4
* Version Independent ID: 17e4dc02-dbae-1d6b-ccf1-671b7a73b0f7
* Content: [Azure Identity client library for Java](https://learn.microsoft.com/en-us/java/api/overview/azure/identity-readme?view=azure-java-stable)
* Content Source: [docs-ref-services/latest/identity-readme.md](https://github.com/Azure/azure-docs-sdk-java/blob/master/docs-ref-services/latest/identity-readme.md)
* Service: **identity**
* GitHub Login: @g2vinay
* Microsoft Alias: **vigera**

**Comment by joshfree** [comment]
@vcolin7 please take a look

**Comment by vcolin7** [comment]
Hi @zeppelinux, just to make sure I understand your question correctly, when you say "an app/service running onprem" do you mean not running on the cloud at all? Like completely outside of the Azure Cloud.

**Comment by zeppelinux** [comment]
Hi @vcolin7, yes it runs completely outside of the Azure Cloud. It may be running in the Azure Cloud in the future, but currently it is not (for various reasons).

**Comment by vcolin7** [comment]
Hi @zeppelinux,

You can follow the steps laid out in [this quickstart](https://learn.microsoft.com/azure/key-vault/secrets/quick-create-java?tabs=azure-cli) to authorize your user account access to your Key Vault and run a local application that authenticates using your credentials.

Similarly, you can [create an app registration](https://learn.microsoft.com/azure/active-directory/develop/quickstart-register-app#register-an-application) on Azure and [give it access to your Key Vault](https://learn.microsoft.com/azure/key-vault/general/assign-access-policy?tabs=azure-portal). You will need to provide the credentials for said app registration to the TokenCredential object you provide to your client like this:

```java
TokenCredential credential = new ClientSecretCredential()
    .clientId(<your-app-registration-id>)
    .clientSecret(<your-app-registration-secret>)
    .tenantId(<your-tenant-id>)
    .build();

SecretClient secretClient = new SecretClientBuilder()
    .vaultUrl(<your-keyvault-url>)
    .credential(credential)
    .buildClient();
```

You can create a new secret for your app registration by clicking on Certificates and Secrets in the Manage section on left pane of your app registration on the Azure Portal:

![image](https://user-images.githubusercontent.com/5799331/213610567-44987cc8-8358-455b-a1ac-c3a1a123a3f0.png)

Hope this helps :)

**Comment by zeppelinux** [comment]
Thanks!
Is Azure provider for External Secrets operator (https://external-secrets.io/v0.7.2/provider/azure-key-vault/) supports onprem cluster  deployment?

**Comment by vcolin7** [comment]
This is the first time I hear about this tool. Let me ask around and see if someone on the team is familiar with it :)

In the meantime, I will be closing this issue. Feel free to reopen it or reach out again here if you have any further questions.
