### ISSUE TITLE
[QUERY] `AppendBlobClient.getBlobOutputStream` overwrites or not?

### ISSUE THREAD

**Issue by dennis-benzinger-hybris** [Azure/azure-sdk-for-java#32602]
**Query/Question**
The Javadoc of `AppendBlobClient.getBlobOutputStream` states that in case the BLOB already exists it will be overwritten:
https://github.com/Azure/azure-sdk-for-java/blob/azure-storage-blob_12.20.1/sdk/storage/azure-storage-blob/src/main/java/com/azure/storage/blob/specialized/AppendBlobClient.java#L102-L103

But the implementation looks like the BLOB will be appended to:
https://github.com/Azure/azure-sdk-for-java/blob/azure-storage-blob_12.20.1/sdk/storage/azure-storage-blob/src/main/java/com/azure/storage/blob/specialized/BlobOutputStream.java#L165-L167

Does it overwrite or append?

**Comment by alzimmermsft** [comment]
@ibrahimrabab could you follow up on this question

**Comment by ibrahimrabab** [comment]
Hi @dennis-benzinger-hybris 
Thank you for opening this issue! I tried to reproduce on my end, and yes, although we state in the docs that we overwrite existing data, in the implementation we actually end up appending to the previous data. We will get a fix checked in soon. Thanks again!
