### ISSUE TITLE
[QUESTION] RetryPolicy Timeout vs DataLakeFileClient.existsWithResponse Timeout

### ISSUE THREAD

**Issue by atemsah-incorta** [Azure/azure-sdk-for-java#32621]
**Query/Question**

Assume we have the following method call

```java
DataLakeFileClient.existsWithResponse(Duration.ofSeconds(60), Context.NONE).getValue();
```

failing with `java.lang.IllegalStateException: Timeout on blocking read for 60000000000 NANOSECONDS`

This means the request is timing out on the Mono Publisher blockingGet. I wanted to get some clarity on the timeout values in different areas of the SDK and if mu assumptions on how it works is correct 

Let's say when creating the DataLakeServiceClient we have a RetryPolicy as follows
```java
RequestRetryOptions retryOptions = new RequestRetryOptions(RetryPolicyType.EXPONENTIAL,
                                                                       5,
                                                                       (Duration) null,
                                                                       (Duration) null,
                                                                       (Duration) null,
                                                                       null);
```

Q1. Should the Timeout value given to the `existsWithResponse` method be larger to equal to number of trials * timeout duration to allow underlying http client to do more trials?

Q2. Should we also instead apply timeout values to the RequestRetryOptions?

What's the relation or difference between
1. Timeout given to the underlying HttpClient
2. Timeout given to (DataLake|Blob)ServiceClient through RequestRetryOptions
3. Timeout given to xxxWithResponse method

Scenario I would like to understand.

Assume we define Retry with 3 max retries and 30 seconds timeout and call `existsWithResponse` with timeout of 60.

If HttpClient sends request 1 and doesn't respond in 30 seconds does that mean it will timeout? and then request 2 should run. Id request 2 does respond in 30 seconds and timeouts.

Does that mean request 3 will not be executed because the publisher above from existsWithResponse has hard timeout of 60 seconds?

***Why is this not a Bug or a feature Request?***
This is a question for clarity of already implemented feature and code is assumed to be correct and behaving up to expectation so far.

**Setup (please complete the following information if applicable):**
 - Library/Libraries: [azureDataLakeStoreSdkVersion = '2.2.9', azureKeyvaultCoreVersion = '1.0.0', azureStorageVersion = '7.0.0', azureStorageFileDatalakeVersion = '12.11.0', azureIdentityVersion = '1.5.3']
 
 **Information Checklist**
 Kindly make sure that you have added all the following information above and checkoff the required fields otherwise we will treat the issuer as an incomplete report
- [X] Query Added
- [X] Setup information Added

**Comment by jaschrep-msft** [comment]
Hi @atemsah-incorta

> What's the relation or difference between
>
> 1. Timeout given to the underlying HttpClient
> 2. Timeout given to (DataLake|Blob)ServiceClient through RequestRetryOptions
> 3. Timeout given to xxxWithResponse method

1. This is the timeout you'd think of at the lowest level. If the HttpClient doesn't receive a response after this timeout, it abandons it. While it is generally good practice to have some sort of timeout on an HttpClient to ensure it doesn't sit forever on lost requests, I find it not the most influential in a general retry strategy.
2. These are the settings for the retry policy, implemented through a Reactor timeout. This policy will apply the configured timeout to the rest of the pipeline plus the http roundtrip. A timeout here causes a reactive operation cancellation, a delay, followed by a retry. This is the prime focus of any timeout/retry policy.
3. This is an individual reactive timeout you can give to the entire end-to-end operation, including all retries. This is more useful for adjustment to individual operations. We don't generally expect its usage, but the option has been provided should it be needed.

> If HttpClient sends request 1 and doesn't respond in 30 seconds does that mean it will timeout? and then request 2 should run. Id request 2 does respond in 30 seconds and timeouts.
> 
> Does that mean request 3 will not be executed because the publisher above from existsWithResponse has hard timeout of 60 seconds?

This is correct. Not all timings are perfect in an async environment, and so I imagine a race condition taking place with these numbers that line up exactly, but yes that is the general idea.

**Comment by ibrahimrabab** [comment]
Hi @atemsah-incorta 

Do you have any additional questions? If not, we can go ahead and close this issue. If you have any additional questions, please let us know, thanks!
