### ISSUE TITLE
[FEATURE REQ] Reference architectures to build web applications on Azure

### ISSUE THREAD

**Issue by fangjian0423** [Azure/azure-sdk-for-java#32637]
Provide reference architectures to help spring developers to better build the Spring MVC application on Azure

## References

* [Build web and mobile applications](https://learn.microsoft.com/en-us/azure/architecture/solution-ideas/articles/webapps)
* [Java CI/CD using Jenkins and Azure Web Apps](https://learn.microsoft.com/en-us/azure/architecture/solution-ideas/articles/java-cicd-using-jenkins-and-azure-web-apps)
* [Serverless web application](https://learn.microsoft.com/en-us/azure/architecture/reference-architectures/serverless/web-app)
* [Host a RESTful API with CORS in Azure App Service](https://learn.microsoft.com/en-us/azure/app-service/app-service-web-tutorial-rest-api)

**Comment by stliu** [comment]
@chenrujun why is this **blocked**?

**Comment by chenrujun** [comment]
> @chenrujun why is this **blocked**?

@stliu 
Originally, you told me to forget the task about `reference architecture article`, build Grafana dashboard first. I though they are different task. Now I know it's my misunderstanding. I'll change the status from `blocked` to `In Progress`.

**Comment by saragluna** [comment]
Closing this issue now for the changes have been merged.
