### ISSUE TITLE
Is it possible to query cosmos gremlin graph using gremlin query in case insensitive manner? 

### ISSUE THREAD

**Issue by MangalamPalod** [Azure/azure-sdk-for-java#32642]
Example:
Case 1 :
 'Field': 'ABCD'
Case 2 :
 'Field': 'abcd'

We want to figure out a way to get all the vertices corresponding to both the fields using gremlin query.
Is it possible to use store-procedures or any operation for this use-case?

**Comment by TheovanKraay** [comment]
Closing as this is not the right forum for this question. This repo is azure-sdk-for-java, which contains Java projects for connecting to NoSQL API, not Gremlin.
