### ISSUE TITLE
EncryptedBlobAsyncClient- Upload blob- getting NullPointerException @BlobParallelUploadOptions.getLength

### ISSUE THREAD

**Issue by abhikt48** [Azure/azure-sdk-for-java#32657]
**Describe the bug**
Using the most recent SDK to avoid providing the InputStream length while uploading blob, but getting `NullPointerException `  from `com.azure.storage.blob.specialized.cryptography.EncryptedBlobAsyncClient.uploadWithResponse(EncryptedBlobAsyncClient.java:422)` due to `BlobParallelUploadOptions.getLength(BlobParallelUploadOptions.java:138)` which is a deprecated method.

***Exception or Stack Trace***
```
ERROR 2022-12-20 15:00:39,119 [main] com.azure.storage.blob.specialized.cryptography.EncryptedBlobAsyncClient: null
Exception in thread "main" java.lang.NullPointerException
	at com.azure.storage.blob.options.BlobParallelUploadOptions.getLength(BlobParallelUploadOptions.java:138)
	at com.azure.storage.blob.specialized.cryptography.EncryptedBlobAsyncClient.uploadWithResponse(EncryptedBlobAsyncClient.java:422)
	at com.azure.storage.blob.BlobClient.uploadWithResponse(BlobClient.java:333)
	at com.test.blob.BlobEncryptionTest.main(BlobEncryptionTest.java:57)
	Suppressed: java.lang.Exception: #block terminated with an error
		at reactor.core.publisher.BlockingSingleSubscriber.blockingGet(BlockingSingleSubscriber.java:99)
		at reactor.core.publisher.Mono.block(Mono.java:1707)
		at com.azure.storage.common.implementation.StorageImplUtils.blockWithOptionalTimeout(StorageImplUtils.java:156)
		at com.azure.storage.blob.BlobClient.uploadWithResponse(BlobClient.java:337)
		... 1 more

```

**To Reproduce**
1. Update credentials in [BlobEncryptionTest.java.txt](https://github.com/Azure/azure-sdk-for-java/files/10269612/BlobEncryptionTest.java.txt)
2. Use below-defined dependencies
3. Run class as `Java Application`

***Code Snippet***
1. [BlobEncryptionTest.java.txt](https://github.com/Azure/azure-sdk-for-java/files/10269612/BlobEncryptionTest.java.txt)
4. Used Dependencies
```
<dependency>
	<groupId>com.azure</groupId>
	<artifactId>azure-storage-blob</artifactId>
	<version>12.20.1</version>
</dependency>
<dependency>
	<groupId>com.azure</groupId>
	<artifactId>azure-security-keyvault-keys</artifactId>
	<version>4.5.2</version>
</dependency>
<dependency>
	<groupId>com.azure</groupId>
	<artifactId>azure-identity</artifactId>
	<version>1.7.2</version>
</dependency>
<dependency>
	<groupId>com.azure</groupId>
	<artifactId>azure-storage-blob-cryptography</artifactId>
	<version>12.19.1</version>
</dependency>
```

**Expected behavior**
The upload should be successful.

**Setup (please complete the following information):**
 - OS: Windows 10
 - IDE: Eclipse-based
 - Library/Libraries: refer above
 - Java version: 8

**Comment by alzimmermsft** [comment]
@ibrahimrabab @jaschrep-msft could you take a look at this when you get a chance

**Comment by jaschrep-msft** [comment]
Hmm it looks like the encryption package copies some logic from the main package regarding sync --> async conversions, and never picked up this particular change.

There's currently a refactor of all of this conversion code across the storage libraries which could address this, but there isn't a hard timeline on that at the moment, so it may be best to make a separate fix for this.
