### ISSUE TITLE
[BUG] ServiceBusProcessorClient stops to receive messages

### ISSUE THREAD

**Issue by gmousset** [Azure/azure-sdk-for-java#32677]
**Describe the bug**
Hello, I encounter an issue with ServiceBusProcessorClient that stops to receive messages.
My application subscribes to 5 topics, and after several hours, on one of them, always the same, no longer receive messages. 
I precise that this topic has a lot of more messages than the others (95% of the overall message concerns this topic).

***Exception or Stack Trace***
Just before the end of message reception I have this log:
```
[2022-12-20 23:00:06][WARN ][ReceiveLinkHandler:361] {"az.sdk.message":"Could not emit delivery. DeliveryImpl [_tag=[], _link=org.apache.qpid.proton.engine.impl.ReceiverImpl@2053cc3e, _deliveryState=null, _settled=false, _remoteSettled=true, _remoteDeliveryState=null, _flags=0, _defaultDeliveryState=null, _transportDelivery=org.apache.qpid.proton.engine.impl.TransportDelivery@6eeed0af, _data Size=19969, _complete=true, _updated=true, _done=false]","connectionId":"MF_c43f83_1671553065168","entityPath":"myTopic/subscriptions/mySubscription","linkName":"myTopic/subscriptions/mySubscription_e34dd5_1671553066167","emitResult":"FAIL_OVERFLOW"}
```

***Code Snippet***
ServiceBusProcessorClient creation:

```
// We are listening several topics, one processor is created for each
this.topicClients = this.serviceBusProperties.topics.map { topic ->
            val eventType = ApiEventType.valueOf(topic.key)
            val client = ServiceBusClientBuilder()
                .connectionString(this.serviceBusProperties.connectionString)
                .processor()
                .topicName(topic.value)
                .subscriptionName(this.serviceBusProperties.subscriptionName)
                .receiveMode(ServiceBusReceiveMode.RECEIVE_AND_DELETE)
                .prefetchCount(this.serviceBusProperties.prefetchCount) // prefetch = 100
                .disableAutoComplete()
                .maxConcurrentCalls(this.serviceBusProperties.maxConcurrentCall) // 10 concurrent call
                .processMessage { this.processMessage(it, eventType) }
                .processError { this.processError(it, eventType) }
                .buildProcessorClient()
            return@map eventType to client
        }.toMap()

        this.topicClients.forEach {
            this.logger.info("connecting to topic for event ${it.key}")
            it.value.start()
        }
```

**Setup (please complete the following information):**
 - OS: Linux in Docker container
 - Library/Libraries: com.azure:azure-messaging-servicebus:7.10.1
 - Java version: 17
 - App Server/Environment: Docker + Kubernetes
 - Frameworks: Spring Boot

**Comment by joshfree** [comment]
@anuchandy could you please follow up with @gmousset on this github issue?

**Comment by anuchandy** [comment]
Hi @gmousset I'm sorry for the delay in followingup :(

So, you have 5 processors running in one container, each listening to one topic, Right?.

Could you provide the following additional information -

1. What is the number of cores allocated to the container running these 5 processors?
2. What is the message flow rate on these topics? Could you share the inbound-outbound metric for "each" of the 5 topics for couple of hours?
3. What is the average time the prcocessMessage handler spends processing "each" message? Also, the 95 percentile?

**Comment by anuchandy** [comment]
Closing this as this is inactive for more than 6 months. Feel free to reopen with additional details.
