### ISSUE TITLE
[QUESTION] The right place to perform some action right after the user logs in

### ISSUE THREAD

**Issue by martfol** [Azure/azure-sdk-for-java#32706]
**Query/Question**
Hi guys, I'd like to ask you for an advice. We'd like to perform an action right after the user logs in successfully via Azure AD (update some timestamp in the database). Would it be ok just to extend the _AadOAuth2UserService_ and override the _loadUser_ method? Or would you suggest some other place/way to implement such functionality?

***Why is this not a Bug or a feature Request?***
This is neither a bug, nor a feature request... Just a question :)

**Setup (please complete the following information if applicable):**
 - Library/Libraries: Library/Libraries: spring-boot 2.6.8, spring-cloud-azure 4.4.1
 
 **Information Checklist**
 Kindly make sure that you have added all the following information above and checkoff the required fields otherwise we will treat the issuer as an incomplete report
- [x] Query Added
- [x] Setup information Added

**Comment by chenrujun** [comment]
Hi, @martfol .
Thanks for reaching out.

> Would it be ok just to extend the AadOAuth2UserService and override the loadUser method?

IMU, it's OK to add your own logic in this way. But be careful about the possible exceptions about your new added logic.

> Or would you suggest some other place/way to implement such functionality?

Now I don't know any other places to add this logic. If you find better solution, please share the solution here.

**Comment by stliu** [comment]
@chenrujun  does spring security have such extension point or event publish out

**Comment by chenrujun** [comment]
> @chenrujun does spring security have such extension point or event publish out

@stliu 

I found [this](https://docs.spring.io/spring-security/reference/5.8.0/servlet/authentication/architecture.html#servlet-authentication-abstractprocessingfilter): 
> If authentication is successful, then Success.
> ApplicationEventPublisher publishes an InteractiveAuthenticationSuccessEvent.

Refs:
1. https://docs.spring.io/spring-security/reference/5.8.0/servlet/authentication/architecture.html#servlet-authentication-abstractprocessingfilter
2. https://github.com/spring-projects/spring-security/blob/5.8.0/web/src/main/java/org/springframework/security/web/authentication/AbstractAuthenticationProcessingFilter.java#L331
3. https://stackoverflow.com/questions/41076500/eventlistener-for-authenticationsuccessevent-or-interactiveauthenticationsucces
4. https://docs.spring.io/spring-security/reference/5.8.0/servlet/authentication/events.html

Hi, @martfol ,
I think you can try to add code to listen `InteractiveAuthenticationSuccessEvent` according to above links.

**Comment by martfol** [comment]
Thanks @chenrujun / @stliu  - will try it out and let you know afterwards...

**Comment by martfol** [comment]
The suggestion using InteractiveAuthenticationSuccessEvent works and sure seems more elegant than overriding the _AadOAuth2UserService.loadUser_ method. So I'll use this way :) Thanks again @chenrujun and @stliu for your help!

**Comment by chenrujun** [comment]
@martfol 
Glad to hear that.
Thank you for your feedback.
