### ISSUE TITLE
[BUG] SimpleTokenCache stuck in WIP mode, token not renewed, application stalls

### ISSUE THREAD

**Issue by endreferencz** [Azure/azure-sdk-for-java#32725]
**Describe the bug**
com.azure.core.confidential.SimpleTokenCache wip flag is cleared in doOnTerminate, which is not executed when Mono is cancelled (ex. due to timeout). As a result it gets stuck forever with wip flag set and token is never renewed. All operations are stalled which require a token. Consider using doFinally.

***Exception or Stack Trace***
No stack trace.

**To Reproduce**
It's a concurrency issue, hard to reproduce. In our system it appears once or twice per week under high load.

***Code Snippet***
Check source code of SimpleTokenCache.

**Expected behavior**
SimpleTokenCache wip flag is cleared in every case. SimpleTokenCache should never get into a state to not renew the token.

**Screenshots**
N/A

**Setup (please complete the following information):**
 - OS: Ubuntu
 - IDE: IntelliJ
 - Library/Libraries: com.azure:azure-core:1.34.0
 - Java version: 11
 - App Server/Environment: AKS
 - Frameworks: Spring boot

**Additional context**
N/A

**Comment by alzimmermsft** [comment]
Thanks for filing this @endreferencz. I'll get this changed to use `doFinally` instead of `doOnTerminate` to support scenarios where the reactive stream is cancelled.
