### ISSUE TITLE
[BUG] Refresh RegistryTaskRun throws an Exception

### ISSUE THREAD

**Issue by dvallejo** [Azure/azure-sdk-for-java#32734]
**Describe the bug**
I'm trying to refresh a RegistryTaskRun recovered by the listByRegistry method and an exception is thrown. It seems the RegistryTaskRun is not completed when I retrieve it from listByRegistry method. When I use a RegistryTaskRun obtained from running a new task, the refresh method is working.

***Exception or Stack Trace***
```
java.lang.IllegalArgumentException: Parameter resourceGroupName is required and cannot be null.
  at com.microsoft.azure.management.containerregistry.implementation.RunsInner.getWithServiceResponseAsync(RunsInner.java:406)
  at com.microsoft.azure.management.containerregistry.implementation.RunsInner.getAsync(RunsInner.java:384)
  at com.microsoft.azure.management.containerregistry.implementation.RegistryTaskRunImpl.refreshAsync(RegistryTaskRunImpl.java:368)
```
**To Reproduce**

1. Run a new RegistryTaskRun
2. Save run Id
3. Recover the RegistryTaksRun using the method listByRegistry and the run Id
4. Call the method refresh for this Registry

***Code Snippet***
```scala
    
// manager is my ContainerRegistryManager
val registryTaskRun: RegistryTaskRun = manager.registryTaskRuns().scheduleRun()
  .withExistingRegistry(resourceGroupName, registryName)
  .withPlatform(new PlatformProperties().withOs(OS.LINUX).withArchitecture(Architecture.AMD64))
  .withDockerTaskRunRequest()
  .defineDockerTaskStep()
  .withDockerFilePath(dockerFilePath)
  .withCacheEnabled(true)
  .withPushEnabled(true)
  .withImageNames(List(imageName).asJava)
  .withOverridingArguments(arguments)
  .attach()
  .withSourceLocation(sourceLocation)
  .withTimeout(dockerBuildTimeout)
  .withCpuCount(2)
  .execute()

val runId = registryTaskRun.runId()

val registryTaskRunFromList = manager.registryTaskRuns().listByRegistry(resourceGroupName, registryName)
  .stream()
  .filter(_.runId() == runId)
  .findFirst()
  .get()

//This doesn't work
registryTaskRunFromList.refresh()

//This works
registryTaskRun.refresh()
```

**Expected behavior**
I expect refresh the instance in order to don't repeat the listByRegistry again.

**Screenshots**

**Setup (please complete the following information):**
 - OS: Linux
 - IDE: IntelliJ
 - Library/Libraries: azure-resourcemanager-containerregistry:2.22.0
 - Java version: [e.g. 8] 
 - App Server/Environment: [e.g. Tomcat, WildFly, Azure Function, Apache Spark, Databricks, IDE plugin or anything special]
 - Frameworks: [e.g. Spring Boot, Micronaut, Quarkus, etc] 

If you suspect a dependency version mismatch (e.g. you see `NoClassDefFoundError`, `NoSuchMethodError` or similar), please check out [Troubleshoot dependency version conflict article](https://aka.ms/azsdk/java/dependency/troubleshoot) first. If it doesn't provide solution for the problem, please provide:
- verbose dependency tree (`mvn dependency:tree -Dverbose`)
- exception message, full stack trace, and any available logs

**Additional context**

**Information Checklist**
Kindly make sure that you have added all the following information above and checkoff the required fields otherwise we will treat the issuer as an incomplete report
- [x] Bug Description Added
- [x] Repro Steps Added
- [x] Setup information Added

**Comment by joshfree** [comment]
Thanks for filing this github issue, @dvallejo.  @weidongxu-microsoft could you please follow up?

**Comment by weidongxu-microsoft** [comment]
Sorry for late reply.

Fix in https://github.com/Azure/azure-sdk-for-java/pull/33620

Next release will be 2.25.0 in March.
