### ISSUE TITLE
No class def found error with com/microsoft/aad/msal4j/IHttpClient

### ISSUE THREAD

**Issue by nandinirakas** [Azure/azure-sdk-for-java#32743]
**Describe the bug**
Getting the No class def found error when using AuthorizationCodeCredential for getting list of messages

**Exception or Stack Trace**
java.lang.ClassNotFoundException: com.microsoft.aad.msal4j.IHttpClient not found by wrap_file__home_user_.m2_repository_com_azure_azure-identity_1.7.2_azure-identity-1.7.2.jar

**To Reproduce**
used the following dependencies

com.microsoft.graph
microsoft-graph
5.42.0

com.azure
azure-identity
1.7.2

**Code Snippet**
 final AuthorizationCodeCredential authCodeCredential = new AuthorizationCodeCredentialBuilder()
                .clientId(clientId)
                .clientSecret(clientSecret)
                .authorizationCode(code)
                .redirectUrl(redirectUrl)
                .build();

**Expected behavior**
This should give access token for code generated 

**Setup (please complete the following information):**
OS: Ubuntu
IDE : IntelliJ

**Screenshots**
![image](https://user-images.githubusercontent.com/94599014/210061920-601195ed-6643-4ad7-bfbc-5bc04463fd49.png)

**Dependency tree**
+- com.azure:azure-identity:jar:1.7.2:compile
[INFO] |  +- com.azure:azure-core:jar:1.34.0:compile
[INFO] |  |  \- io.projectreactor:reactor-core:jar:3.4.23:compile
[INFO] |  |     \- org.reactivestreams:reactive-streams:jar:1.0.4:compile
[INFO] |  +- com.azure:azure-core-http-netty:jar:1.12.7:compile
[INFO] |  |  +- io.netty:netty-handler:jar:4.1.82.Final:compile
[INFO] |  |  |  +- io.netty:netty-common:jar:4.1.82.Final:compile
[INFO] |  |  |  +- io.netty:netty-resolver:jar:4.1.82.Final:compile
[INFO] |  |  |  +- io.netty:netty-transport:jar:4.1.82.Final:compile
[INFO] |  |  |  \- io.netty:netty-codec:jar:4.1.82.Final:compile
[INFO] |  |  +- io.netty:netty-handler-proxy:jar:4.1.82.Final:compile
[INFO] |  |  |  \- io.netty:netty-codec-socks:jar:4.1.82.Final:compile
[INFO] |  |  +- io.netty:netty-buffer:jar:4.1.82.Final:compile
[INFO] |  |  +- io.netty:netty-codec-http:jar:4.1.82.Final:compile
[INFO] |  |  +- io.netty:netty-codec-http2:jar:4.1.82.Final:compile
[INFO] |  |  +- io.netty:netty-transport-native-unix-common:jar:4.1.82.Final:compile
[INFO] |  |  +- io.netty:netty-transport-native-epoll:jar:linux-x86_64:4.1.82.Final:compile
[INFO] |  |  |  \- io.netty:netty-transport-classes-epoll:jar:4.1.82.Final:compile
[INFO] |  |  +- io.netty:netty-transport-native-kqueue:jar:osx-x86_64:4.1.82.Final:compile
[INFO] |  |  |  \- io.netty:netty-transport-classes-kqueue:jar:4.1.82.Final:compile
[INFO] |  |  +- io.netty:netty-tcnative-boringssl-static:jar:2.0.54.Final:compile
[INFO] |  |  |  +- io.netty:netty-tcnative-classes:jar:2.0.54.Final:compile
[INFO] |  |  |  +- io.netty:netty-tcnative-boringssl-static:jar:linux-x86_64:2.0.54.Final:compile
[INFO] |  |  |  +- io.netty:netty-tcnative-boringssl-static:jar:linux-aarch_64:2.0.54.Final:compile
[INFO] |  |  |  +- io.netty:netty-tcnative-boringssl-static:jar:osx-x86_64:2.0.54.Final:compile
[INFO] |  |  |  +- io.netty:netty-tcnative-boringssl-static:jar:osx-aarch_64:2.0.54.Final:compile
[INFO] |  |  |  \- io.netty:netty-tcnative-boringssl-static:jar:windows-x86_64:2.0.54.Final:compile
[INFO] |  |  \- io.projectreactor.netty:reactor-netty-http:jar:1.0.23:compile
[INFO] |  |     +- io.netty:netty-resolver-dns:jar:4.1.81.Final:compile
[INFO] |  |     |  \- io.netty:netty-codec-dns:jar:4.1.81.Final:compile
[INFO] |  |     +- io.netty:netty-resolver-dns-native-macos:jar:osx-x86_64:4.1.81.Final:compile
[INFO] |  |     |  \- io.netty:netty-resolver-dns-classes-macos:jar:4.1.81.Final:compile
[INFO] |  |     \- io.projectreactor.netty:reactor-netty-core:jar:1.0.23:compile
[INFO] |  +- com.microsoft.azure:msal4j:jar:1.13.3:compile
[INFO] |  |  +- com.nimbusds:oauth2-oidc-sdk:jar:9.35:compile
[INFO] |  |  |  +- com.github.stephenc.jcip:jcip-annotations:jar:1.0-1:compile
[INFO] |  |  |  +- com.nimbusds:content-type:jar:2.2:compile
[INFO] |  |  |  +- com.nimbusds:lang-tag:jar:1.6:compile
[INFO] |  |  |  \- com.nimbusds:nimbus-jose-jwt:jar:9.22:compile
[INFO] |  |  \- net.minidev:json-smart:jar:2.4.8:compile
[INFO] |  |     \- net.minidev:accessors-smart:jar:2.4.8:compile
[INFO] |  |        \- org.ow2.asm:asm:jar:9.1:compile
[INFO] |  +- com.microsoft.azure:msal4j-persistence-extension:jar:1.1.0:compile
[INFO] |  |  \- net.java.dev.jna:jna:jar:5.5.0:compile
[INFO] |  \- net.java.dev.jna:jna-platform:jar:5.6.0:compile

**Additional context**
I have tried the same code with main method, it works perfectly. But when I run it in bundle it does not works

**Comment by alzimmermsft** [comment]
@g2vinay @billwert

**Comment by billwert** [comment]
hi @nandinirakas! Can you share how you're bundling the app?

**Comment by nandinirakas** [comment]
I created bundle and then build it by using karaf.

**Comment by nandinirakas** [comment]
@billwert I created bundle and then build it by using karaf.

**Comment by billwert** [comment]
@nandinirakas Can you try updating to Azure Identity 1.11.1 and let me know what happens? We've made a lot of change here and I'd like to get an updated view.
