### ISSUE TITLE
[BUG] GraalVM native compilation fails with `instance of Random/SplittableRandom class in the image heap` 

### ISSUE THREAD

**Issue by ppalaga** [Azure/azure-sdk-for-java#32744]
**Describe the bug**
GraalVM native build of a Quarkus application depending on azure-eventhubs or azure-storage-blob fails with 

```
 org.graalvm.compiler.java.BytecodeParser$BytecodeParserError: com.oracle.graal.pointsto.constraints.UnsupportedFeatureException: Detected an instance of Random/SplittableRandom class in the image heap. Instances created during image generation have cached seed values and don't behave as expected.
```

This is caused by the fact that `com.azure.identity.implementation.IdentityClientBase` instantiates `java.util.Random` in its static initializer: https://github.com/Azure/azure-sdk-for-java/blob/5e50849a233a9507f71db01572c3ea5648c55f2f/sdk/identity/azure-identity/src/main/java/com/azure/identity/implementation/IdentityClientBase.java#L83

This issue might be seen as specific to Quarkus, because Quarkus instructs the GraalVM native compiler to initialize all classes at build time (unless configured differently for some specific class). Plain GraalVM's default is to initialize non-Java-SDK classes at runtime, in which case the issue would not occur.

This issue can be worked around by registering `com.azure.identity.implementation.IdentityClientBase` for delayed initializetion at build time using `io.quarkus.deployment.builditem.nativeimage.RuntimeInitializedClassBuildItem`.

I wonder whether -- in order to get rid any workarounds on Quarkus -- the code could be refactored in such a way that the `java.util.Random` constructor is not called from a static initializer.  E.g. it could be instantiated lazily when the field is accessed for the first time.

In case Azure SDK team finds this proposal feasible, then I'd like to note that `IdentityClientBase` has one more similar problem, namely `DEFAULT_WINDOWS_SYSTEM_ROOT = System.getenv("SystemRoot")`. `System.getenv("SystemRoot")` should also be called lazily.

Original report: https://github.com/apache/camel-quarkus/issues/4356

***Exception or Stack Trace***
See above

**To Reproduce**
Put together a simple Quarkus app accessing e.g. Azure Storage and try to compile it with GraalVM 22.3

**Expected behavior**
GraalVM native compilation succeeds.

**Setup (please complete the following information):**
 - OS: Linux
 - IDE: unimportant
 - Library/Libraries: azure-identity 1.7.0+
 - Java version: 11
 - Frameworks: Quarkus, GraalVM

**Comment by ppalaga** [comment]
cc @agoncal

**Comment by srnagar** [comment]
@ppalaga thanks for reporting this issue. I will take a look at this and report my findings here.

**Comment by ppalaga** [comment]
I have created https://github.com/Azure/azure-sdk-for-java/issues/32781
