### ISSUE TITLE
[BUG]Cosmos Spring SDK: Adding flag in CosmosIndexingPolicy annotation to indicate override behavior

### ISSUE THREAD

**Issue by xinlian12** [Azure/azure-sdk-for-java#32770]
Issue:
Currently, if customer has defined CosmosIndexingPolicy annotation, and if the indexing policy is different than the existing ones, SDK will override the existing indexing policy. But few recent customer reported cases shows that it would be good to allow customer to decide whether to override the existing ones based on their requirements. 

Proposed solution:
Introduce a new flag in CosmosIndexingPolicy which allows the customer to decide whether they want to override the existing indexing policy.

**Comment by kushagraThapar** [comment]
@trande4884  - it would also be good to add clear documentation on the `@CosmosIndexingPolicy` annotation - that by using this annotation, it will override the existing indexing policy on the portal. If they are the same, it won't override, but if they are not, then it will override. 

Also, we should may be add a known issues section to our readme, specifying that by using this indexing policy, SDK will take preference and will override the indexing policy specified in the portal. 

Also, then we can also mention the flag that you are going to add as part of this item - that if the flag is set to false - then it won't override.
