### ISSUE TITLE
[BUG] System.getenv("SystemRoot") should be called lazily

### ISSUE THREAD

**Issue by ppalaga** [Azure/azure-sdk-for-java#32781]
**Describe the bug**
Follows up https://github.com/Azure/azure-sdk-for-java/issues/32744 that was recently fixed by @alzimmermsft . 

In addition to not creating a new java.util.Random in static initializes, it would be nice not to read the system environment from static initializes as well. Calls like `DEFAULT_WINDOWS_SYSTEM_ROOT = System.getenv("SystemRoot")` ( see [IdentityClientBase](https://github.com/Azure/azure-sdk-for-java/blob/d183b5e1ba94d4786d290bc2c4357a95fda47b8a/sdk/identity/azure-identity/src/main/java/com/azure/identity/implementation/IdentityClientBase.java#L87) )  should be avoided.

This might be an issue on Quarkus, where the static initializers are only executed at build time. Because of that, the build machine setup can leak to production machines thus causing runtime issues.

**Comment by alzimmermsft** [comment]
Thanks for filing this follow-up issue @ppalaga. Is this a case where all environment variables and system property look ups should be done during runtime instead of during initialization time? Is there a known set of issues that happen with GraalVM/Quarkus that we should review.

**Comment by ppalaga** [comment]
> Is this a case where all environment variables and system property look ups should be done during runtime instead of during initialization time? 

Yes, generally, it is better to read the env at runtime. I'd say exceptions to that rule are rather rare: e.g. if the given lib has some sort of a build time configuration - which Azure SDK most likely does not have.

> Is there a known set of issues that happen with GraalVM/Quarkus that we should review.

I was trying to google for a comprehensive list, but have found only resources that do not look like they were complete:

* https://medium.com/graalvm/understanding-class-initialization-in-graalvm-native-image-generation-d765b7e4d6ed
* https://www.graalvm.org/22.1/reference-manual/native-image/ClassInitialization/

They mention these items:

* start application threads that continue to run in the background of the application,
* load native libraries using java.lang.Runtime.load(String),
* open files or sockets, or
* allocate C memory, e.g., create direct byte buffers using java.nio.ByteBuffer.allocateDirect(int).
