### ISSUE TITLE
ServiceBus using managed indentity has error

### ISSUE THREAD

**Issue by smokshagundam-nlg** [Azure/azure-sdk-for-java#32793]
ASB Transient error occurred while connecting through ManagedIdentity

{"az.sdk.message":"Transient error occurred. Retrying.","exception":"errorContext[NAMESPACE: <<workASBName>>.servicebus.windows.net ERROR CONTEXT: N/A]","entityPath":"N/A","retry":2,"interval_ms":14575}

Use Managed identity Connectivity through App Permissions
---application.properties
    asb:
      connection-string: <<workASBName>>.servicebus.windows.net
---Bean Config
	@Bean ("ServiceBusSenderClientTestQueue")
	public ServiceBusSenderClient serviceBusSenderClient() {
		ManagedIdentityCredential credential = new ManagedIdentityCredentialBuilder().build();
		   return  new ServiceBusClientBuilder()
	    	   .credential(asbConnectionString, credential)
	    	    .sender()
	            .queueName(queueName)
	            .buildClient();	            
	}
---Service Class
                ServiceBusMessage sbs = new ServiceBusMessage(data);
		serviceBusSenderClient.sendMessage(sbs);

As App Permissions were provided with AzureServiceBusSender & AzureServiceBusReceiver Access through IAM(Managed Identity) - expected behaviour is to post messages successfully to ASB Queue.

**Setup (please complete the following information):**
 - OS: AzureSpringApps
 - IDE: Ecllipse
 - Library/Libraries: <dependency>
        <groupId>com.azure.spring</groupId>
        <artifactId>spring-messaging-azure-servicebus</artifactId>
        <version>4.2.0</version>
      </dependency>
 - Java version: 8
 - App Server/Environment: Azure Spring Apps
 - Frameworks: SpringBoot

Please provide information on if am missing some thing here to configure.

Thanks in advance !!

Sudha B M.

@azure-sdk

**Comment by chenrujun** [comment]
Hi, @conniey, @srnagar, @ki1729, @ZejiaJiang.
Anyone help to handle this issue?
(I added you here because you are con contributor of [ServiceBusClientBuilder.java](https://github.com/Azure/azure-sdk-for-java/commits/main/sdk/servicebus/azure-messaging-servicebus/src/main/java/com/azure/messaging/servicebus/ServiceBusClientBuilder.java))

Please assign this issue to yourself if you decided to handle this issue.

**Comment by yiliuTo** [comment]
cc @Azure/azsdk-sb-java

**Comment by smokshagundam-nlg** [comment]
any suggestions please..?

**Comment by ZejiaJiang** [comment]
hi @smokshagundam-nlg 

Sorry for delay reply.  I'm looking at this issue.  And try to repro it.

**Comment by ZejiaJiang** [comment]
hi @smokshagundam-nlg ,

I've tried to repro this issue, but I didn't see this error. I deployed a very simple application only with a send message method. it works well. So do you meet this error every time when you send messages?

Could you please provide more logs? enable DEBUG level log and logs +/- 5minutes when this error occured.

**Comment by stliu** [comment]
@ZejiaJiang could you update the issue title ?
