### ISSUE TITLE
[QUERY] Pagination with cosmos - spring data. How to use the continuation token

### ISSUE THREAD

**Issue by dsrini-open** [Azure/azure-sdk-for-java#32797]
**Query/Question**
How to make the pagination work with continuation token. Seems like the offset or the page is not honored with continuation token. When using continuation token, the records are retrieve from the previous rowid (if I am not wrong). And, the limit / count is honored. 

### Service (Pageable) -
`CosmosPageRequest.of(offset, page, limit, continuationToken, sort)`
or
`CosmosPageRequest.of(page, limit, continuationToken, sort)`

Above code does not work for page different than the previous end Record id. If continuationtoken stopped at row id 2, it starts again from rowid:2, no matter what I provide in offset or page values. 

Also, how to paginate to a before page, when continuation token start at rowid:2, how to move to previous records - 0-2 (with limit 2). 

If, I have to do everything by using @Query, do I have to have a separate query with count for counting the records to find the total count ? 

### Repo - 
`Page<NotesDO> findByPartIdAndOtherIdAndTypeAndTextContaining(String partId, String otherId, String type, String filter, Pageable page);`

***Why is this not a Bug or a feature Request?***
Not sure, how this works. 

**Setup (please complete the following information if applicable):**
 - OS: [macOs]
 - IDE: [Eclipse]
 - Library/Libraries: [ com.azure:azure-spring-data-cosmos:LATEST , com.azure:azure-cosmos:4.39.0]

 **Information Checklist**
 Kindly make sure that you have added all the following information above and checkoff the required fields otherwise we will treat the issuer as an incomplete report

- [x] Query Added
- [x] Setup information Added

**Comment by fangjian0423** [comment]
@kushagraThapar could you please handle this issue?

**Comment by trande4884** [comment]
@dsrini-open can you please provide some sample code of how you are trying to achieve pagination with offset? How are you trying to achieve pagination, via a Template or Repository?

Yes I believe you will have to perform a separate query to get the count. In a repository setup something like one of the following:

`Long countByTitleAndIntValue(String title, int intValue);

@Query(value = "select value count(1) from c where c.title = @title")
long countByQueryWithPrimitive(@Param("title") String title);`

**Comment by dsrini-open** [comment]
@trande4884  - For offset I was trying to use the PageRequest object as below - 
`CosmosPageRequest.of(offset, page, limit, continuationToken, sort)`

I am using the spring data without @Query as my previous example, and it works but the following code does only work from the continuation marker to X limit records (page/offset supplied above is pretty much useless, or not honored). 

`Page<NotesDO> findByPartIdAndOtherIdAndTypeAndTextContaining(String partId, String otherId, String type, String filter, Pageable page);`

Also, with continuationToken method as above - I still see higher RUs - for page 2 of 3 records I see higher RUs (upto a total record count of the container)

**Comment by trande4884** [comment]
For your use of CosmosPageRequest, if you pass in a Continuation Token that will be all that is used to get the next page of results. If you want to use offset and page than do not pass in a continuation token with your CosmosPageRequest.

Here is an example of using offset and then getting the next/previous pages:

```
final Criteria criteria = Criteria.getInstance(CriteriaType.IS_EQUAL, "firstName",
            Collections.singletonList(FIRST_NAME), Part.IgnoreCaseType.NEVER);
        final PageRequest pageRequest = CosmosPageRequest.of(1, 0, PAGE_SIZE_2,
            null, Sort.by(ASC, "id"));
        final CosmosQuery query = new CosmosQuery(criteria).with(pageRequest).with(pageRequest.getSort());
        final Page<PartitionPerson> page = cosmosTemplate.paginationQuery(query, PartitionPerson.class, containerName);
        
        final CosmosQuery query2 = new CosmosQuery(criteria).with(page.nextPageable()).with(page.nextPageable().getSort());
        final Page<PartitionPerson> nextPage = cosmosTemplate.paginationQuery(query2, PartitionPerson.class, containerName);
        
        final CosmosQuery query3 = new CosmosQuery(criteria).with(page.previousPageable()).with(page.previousPageable().getSort());
        final Page<PartitionPerson> prevPage = cosmosTemplate.paginationQuery(query3, PartitionPerson.class, containerName);
```
