### ISSUE TITLE
[BUG]Using the Azure sdk for java to store images in blobs and then download them will produce gray bars.

### ISSUE THREAD

**Issue by ArtistLL123** [Azure/azure-sdk-for-java#32804]
Using the Azure sdk for java to store images in blobs and then download them will produce gray bars.

**Comment by fangjian0423** [comment]
Hi @ArtistLL123 ,

could you share some code or tell us how to reproduce it? Thanks.

**Comment by ArtistLL123** [comment]
import com.azure.storage.blob.BlobServiceClientBuilder;
import com.azure.storage.blob.sas.BlobSasPermission;
import com.azure.storage.blob.sas.BlobServiceSasSignatureValues;
import com.azure.storage.common.StorageSharedKeyCredential;

import java.time.OffsetDateTime;
import java.util.UUID;

public class AzureStorageBlobClient {
    public static void main(String[] args) {
        StorageSharedKeyCredential credential = new StorageSharedKeyCredential("blobtestlmc", "2uJmR5GfK7xzYIif/a6K/EaZwmFeAveUF0RoImmXG/Pspe68Gpgh8T8/rnzQ/NeZqFOb1zrCL0ev+AStHpORlQ==");
        BlobServiceClient blobServiceClient = new BlobServiceClientBuilder().endpoint("https://blobtestlmc.blob.core.chinacloudapi.cn/").credential(credential).buildClient();
        BlobContainerClient blobContainerClient = blobServiceClient.getBlobContainerClient("blob");




        for (int i = 0; i < 10; i++) {
            String uuid = UUID.randomUUID().toString();
            String response = blobContainerClient.getBlobClient("imagetwo/" + uuid + ".jpeg").copyFromUrl("https://thirdwx.qlogo.cn/mmopen/vi_32/DYAIOgq83epZASYWskSmkdyld8bQpsq3OVM3ibuXcx5USB757e3LYNWy75ibgj2lRm5zlAoAqy5GBl8DNibWr6yBw/132");
            System.out.println(uuid + "已生成: " + response);
        }
    }
}

**Comment by zhangyunbo1994** [comment]
Hi @fangjian0423 
Thanks for your support! 
I follow @ArtistLL123 's sample code to reproduce, actually for @ArtistLL123 , he/she upload same pic to blob for ten times, but you can see the 10 pics do not have same file size, please help check:

<img width="1150" alt="image" src="https://user-images.githubusercontent.com/44389598/211343989-7ca5b749-0bfd-44fc-812c-ee8cf79a4df7.png">

**Comment by zhangyunbo1994** [comment]
And I also try to use Azure portal to upload same pic for ten times, but can not reproduce this issue, so I think this issue is from SDK side.

**Comment by alzimmermsft** [comment]
@ibrahimrabab could you look at this?

**Comment by lmolkova** [comment]
@ArtistLL123  could you please [rotate the storage access key](https://learn.microsoft.com/en-us/azure/storage/common/storage-account-keys-manage?tabs=azure-portal) - it seems you accidentally exposed it in the sample.

**Comment by ArtistLL123** [comment]
@lmolkova Thank you for reminding me, I have rotated the storage access key.

**Comment by ibrahimrabab** [comment]
Hi @ArtistLL123 and @zhangyunbo1994 

I tried reproducing the issue using your provided code snippet and source URL and was able to see inconsistent sizes in blobs like you mentioned. 
I then tried to reproduce your code snippet using a different static image URL, and saw the same image size being uploaded (as expected):
<img width="1045" alt="MicrosoftTeams-image (4)" src="https://user-images.githubusercontent.com/88855721/211489458-d1c99b86-2037-4114-b7d5-93edfdcdc4d2.png">

I ran the following powershell script on your copy source URL to see if your image's length was changing or not:
`$url = '[https://thirdwx.qlogo.cn/mmopen/vi_32/DYAIOgq83epZASYWskSmkdyld8bQpsq3OVM3ibuXcx5USB757e3LYNWy75ibgj2lRm5zlAoAqy5GBl8DNibWr6yBw/132'](https://thirdwx.qlogo.cn/mmopen/vi_32/DYAIOgq83epZASYWskSmkdyld8bQpsq3OVM3ibuXcx5USB757e3LYNWy75ibgj2lRm5zlAoAqy5GBl8DNibWr6yBw/132%27) for ($i = 0; $i -lt 10; $i++) {
   $res = wget $url
   Write-Host $res.RawContentLength
}`


result:
4019
4020
4020
4019
4020
4019
4018
4019
4018
4020

This shows the image data at your source URL seems to be changing. Can you confirm whether the image data is static or dynamic? Or if there is another process causing it to be altered while uploading?

Can you also provide the SDK version you're using, as well as request IDs so that we can further investigate on the service side to see if there are any issues with your uploads?

Thanks!

**Comment by zhangyunbo1994** [comment]
Hi @ibrahimrabab thanks for your support!

Here is SDK version we are using:
```
        <dependency>
            <groupId>com.azure</groupId>
            <artifactId>azure-storage-blob</artifactId>
            <version>12.20.1</version>
        </dependency>

        <dependency>
            <groupId>com.azure</groupId>
            <artifactId>azure-sdk-bom</artifactId>
            <version>1.2.8</version>
            <type>pom</type>
            <scope>import</scope>
        </dependency>
```


---
We have some findings:

1. We found jpeg can open by VS code Hex editor, so if we download this image by using curl :  'image'](https://thirdwx.qlogo.cn/mmopen/vi_32/DYAIOgq83epZASYWskSmkdyld8bQpsq3OVM3ibuXcx5USB757e3LYNWy75ibgj2lRm5zlAoAqy5GBl8DNibWr6yBw/132%27) , you can see that no matter how you download it, use the Hex editor to view the pictures, the pictures end with FF D9（FF D9 is an end identifier for jpeg files）.

<img width="731" alt="image" src="https://user-images.githubusercontent.com/44389598/211724687-ddd3a9e2-03fa-4187-a0e6-a085c3dd7c74.png">

2. But if you using copyFromUrl method to copy image to Blob, when you finish copying and uploading the pictures, and then download the uploaded pictures from the blob, you will find that some pictures will be missing FF D9.

<img width="710" alt="image" src="https://user-images.githubusercontent.com/44389598/211725079-33577b2e-298a-48e8-9901-94f19bd64248.png">

3. I found what seemed to be an anomalous problem by scraping network packets. As shown in the screenshot below, it seems that the SDK sent a request, then encountered a 500 exception, and then uploaded successfully after a retry, but the uploaded JPEG file encountered a problem with FF D9. Then I experimented a few times, and the 500 error will be accompanied by the loss of FF D9.
<img width="1464" alt="image" src="https://user-images.githubusercontent.com/44389598/211728109-a2dece89-f1ef-40de-b388-58fb99267bce.png">
You can get request ID in following screenshot:
x-ms-client-request-id: 4d9b136d-7992-45ff-81e7-dcf135a815f4
<img width="1465" alt="image" src="https://user-images.githubusercontent.com/44389598/211728315-b0db730d-431b-44b7-888b-0858f67ae42c.png">
x-ms-request-id: 30bdf5c0-901e-0068-6d7f-251b52000000
x-ms-client-request-id: 4d9b136d-7992-45ff-81e7-dcf135a815f4
<img width="1469" alt="image" src="https://user-images.githubusercontent.com/44389598/211728396-0f728e81-e483-4bd0-a0d7-2e5097664f76.png">
x-ms-client-request-id: 4d9b136d-7992-45ff-81e7-dcf135a815f4
<img width="1470" alt="image" src="https://user-images.githubusercontent.com/44389598/211728470-80a354ba-ba81-4e6e-b18f-3839feede72e.png">

**Comment by zhangyunbo1994** [comment]
Are we using error SDK method? Because I saw another API: https://learn.microsoft.com/en-us/rest/api/storageservices/put-block-list

Should we call Put Blob List again to commit our transaction？ 🤔

**Comment by ibrahimrabab** [comment]
@zhangyunbo1994 
Thank you for providing all the details! Based on the network requests you've posted, this definitely looks like an issue on the server side. Can you file an [Azure Support Ticket](https://learn.microsoft.com/en-us/azure/azure-portal/supportability/how-to-create-azure-support-request#create-a-support-request)? That way we can work alongside the service team to further investigate the loss of data during the upload. Let me know if you need help with this step.

**Comment by zhangyunbo1994** [comment]
Hi @ibrahimrabab 
Thanks for your support, I have opened an IcM ticket for the team, do I need to post the ticket here? Thanks！

**Comment by ibrahimrabab** [comment]
@zhangyunbo1994 
Yes you may go ahead and post the ticket here so we can track it :)

**Comment by zhangyunbo1994** [comment]
Hi @ibrahimrabab here is the ticket ID: 359884397
If you have any questions, please let me know.

**Comment by ibrandes** [comment]
Closed, it was determined in the ICM that the source image was changing.
