### ISSUE TITLE
[QUERY] What's the support policy of Spring Native in Spring Boot 2

### ISSUE THREAD

**Issue by saragluna** [Azure/azure-sdk-for-java#32818]
**Query/Question**
Spring Boot 3 has been GAed, and the Spring Native support has been GAed too. According to the release blog:
"""
_[Support for generating native images with GraalVM](https://docs.spring.io/spring-boot/docs/3.0.0/reference/html/native-image.html#native-image), superseding the experimental Spring Native project_
"""

The Spring Native project has been superseded by Spring Boot 3 Native support. Since the `azure-sdk-for-java` repo also has an `sdk/spring-experimental` folder hosting the source code of Spring Cloud Azure native support for `Spring Native`, see [spring-cloud-azure-native-configuration](https://github.com/Azure/azure-sdk-for-java/tree/main/sdk/spring-experimental/spring-cloud-azure-native-configuration). So what's the support policy of that artifact? Should we still keep the source code? Or should we only maintain the code from the existing tag [spring-cloud-azure-native-configuration_4.0.0-beta.1](https://github.com/Azure/azure-sdk-for-java/releases/tag/spring-cloud-azure-native-configuration_4.0.0-beta.1), see comparing [tag spring-cloud-azure-native-configuration_4.0.0-beta.1 and main](https://github.com/Azure/azure-sdk-for-java/compare/main...spring-cloud-azure-native-configuration_4.0.0-beta.1)?

**NOTE**: Check [this commit](https://github.com/Azure/azure-sdk-for-java/tree/6f7f1003c65cf53875d5709485a844487edf4b68/sdk/spring-experimental/spring-cloud-azure-native-configuration) if the `spring-cloud-azure-native-configuration` gets deleted from the main branch. 

***Why is this not a Bug or a feature Request?***
This issue is to ask for explanation of the support policy. 

 **Information Checklist**
 Kindly make sure that you have added all the following information above and checkoff the required fields otherwise we will treat the issuer as an incomplete report
- [x] Query Added
- [x] Setup information Added

**Comment by saragluna** [comment]
We will follow the way Spring does it, superseding the native support in the [feature/spring-boot-3](https://github.com/Azure/azure-sdk-for-java/tree/feature/spring-boot-3) branch. So we will remove the source code of [spring-cloud-azure-native-configuration](https://github.com/Azure/azure-sdk-for-java/tree/main/sdk/spring-experimental/spring-cloud-azure-native-configuration) from the main branch. We'll use the [tag spring-cloud-azure-native-configuration_4.0.0-beta.1](https://github.com/Azure/azure-sdk-for-java/releases/tag/spring-cloud-azure-native-configuration_4.0.0-beta.1) to manage the potential support need. 

We also need to remove the native stuff from the [azure-spring-boot-samples](https://github.com/Azure-Samples/azure-spring-boot-samples) repo:
- [/spring-native folder](https://github.com/Azure-Samples/azure-spring-boot-samples/tree/main/spring-native).
- Native support of Native in Spring Boot 2 in the [README.md](https://github.com/Azure-Samples/azure-spring-boot-samples).
- Native support of Native in Spring Boot 2 in the [pom.xml](https://github.com/Azure-Samples/azure-spring-boot-samples/blob/main/pom.xml).

**Comment by Netyyyy** [comment]
remove the source code of [spring-cloud-azure-native-configuration](https://github.com/Azure/azure-sdk-for-java/tree/main/sdk/spring-experimental/spring-cloud-azure-native-configuration) from the main branch in https://github.com/Azure/azure-sdk-for-java/pull/32803

**Comment by moarychan** [comment]
The [Spring Native Support](https://learn.microsoft.com/en-us/azure/developer/java/spring-framework/spring-cloud-azure?tabs=maven#spring-native-support) from MS doc should be removed too.

**Comment by hui1110** [comment]
Remove in [388322e](https://github.com/MicrosoftDocs/azure-dev-docs-pr/pull/3994/commits/388322e1b6a37dbb3efc43a3703bfa2c9b9df180).

**Comment by stliu** [comment]
how's this one?

**Comment by saragluna** [comment]
Okay to close now I belive.

**Comment by Netyyyy** [comment]
> Remove in [388322e](https://github.com/MicrosoftDocs/azure-dev-docs-pr/pull/3994/commits/388322e1b6a37dbb3efc43a3703bfa2c9b9df180).

will be closed after this PR was merged

**Comment by Netyyyy** [comment]
All related PRs are merged, so close it.
