### ISSUE TITLE
Programatically adding (SqlRuleFilter based) rules to subscriptions does not work

### ISSUE THREAD

**Issue by LucasReehorst** [Azure/azure-sdk-for-java#32814]
## Actual Behavior
Calling client.createRule(topicName,  getNewRuleName(previousName), subscriptionName, options) on a ServiceBusAdministrationClient results in the logging of a WARN statement like this: 

> Could not find filter name pattern '<(Value)' in <?xml version='1.0' encoding='UTF-8'?><entry xmlns="http://www.w3.org/2005/Atom"><content type="application/xml"><wstxns1:RuleDescription xmlns:wstxns1="http://schemas.microsoft.com/netservices/2010/10/servicebus/connect"><wstxns1:Filter wstxns1:type="SqlFilter"><wstxns1:SqlExpression>[SQL filter]</wstxns1:SqlExpression></wstxns1:Filter><wstxns1:Name>[name]</wstxns1:Name></wstxns1:RuleDescription></content></entry> 

The expected rule is not created. 
I'm using version 1.2.2. of the azure-sdk-bom / 7.9.0 of the azure-messaging-servicebus library. 

If I pause at a breakpoint in the Mono<Response<RuleProperties>> createRuleWithResponse(String topicName, String subscriptionName, String ruleName, CreateRuleOptions ruleOptions, Context context) method in the ServiceBusAdministrationAsyncClient class and execute this code "managementClient.getRules().putWithResponseAsync(topicName, subscriptionName, ruleName, createEntity, null, withTracing).block()" through evaluate expression, the rule is created normally.

## Expected Behavior
1. The rule is added to the specified subscription and no WARN statement appears in the log.

**Comment by jsquire** [comment]
Thank you for your feedback.  Tagging and routing to the team member best able to assist.

**Comment by ki1729** [comment]
@LucasReehorst Can you try this with the one of the latest version of the SDK any version > 7.12.1 ?
We had a bunch of fixes go in prior to this version for the AdminstrationClient

**Comment by LucasReehorst** [comment]
@ki1729 thanks for getting back to me, using a newer version of the SDK indeed resolves this problem for us.
