### ISSUE TITLE
[QUERY] How to configure hierarchical partition keys using spring-data-cosmos

### ISSUE THREAD

**Issue by aggarnik** [Azure/azure-sdk-for-java#32827]
**Query/Question**
I use @PartitionKey to define a logical partition in my model class. I am not able to find any annotations using which I can define hierarchical partition keys in my model class. Is this feature supported by spring-data-cosmos module?

***Why is this not a Bug or a feature Request?***
This is a query regarding a feature supported by azure-sdk.

**Comment by fangjian0423** [comment]
@trande4884 could you please take a look? thanks.

**Comment by kushagraThapar** [comment]
@aggarnik - this is in our backlog and is being developed currently in our Azure Cosmos DB Java V4 SDK. Once it is done and GAed, we plan to build this in Spring Data Cosmos SDK. 
cc @simorenoh

**Comment by TheovanKraay** [comment]
to be review in planning for next semester.

**Comment by kushagraThapar** [comment]
@aggarnik - FYI, this is currently in development - and the PR is out - https://github.com/Azure/azure-sdk-for-java/pull/38365

**Comment by trande4884** [comment]
@aggarnik does the PR above solve your issue? Please let me know if you are still having trouble using hierarchical PK's
