### ISSUE TITLE
[BUG] AD User information returns null

### ISSUE THREAD

**Issue by ihsanhaikalz** [Azure/azure-sdk-for-java#32824]
I tried to retrieve the information of the AD user, particularly the user type but some information returns null when I could see the info on the Portal, such as user type and account enabled.

My code is as follows:

```
  AzureResourceManager azure = AzureResourceManager
                .authenticate(credential, profile)
                .withDefaultSubscription();

        AccessManagement accessManagementService = azure.accessManagement();
        List<ActiveDirectoryUser> users = azure.accessManagement().activeDirectoryUsers().list().stream().collect(Collectors.toList());

 for(ActiveDirectoryUser user : users){
System.out.println(user.id());
      System.out.println(user.name());
            System.out.println(user.innerModel().userType());
            System.out.println(user.innerModel().accountEnabled());


        }
```

**Comment by joshfree** [comment]
@weidongxu-microsoft could you please follow up with @ihsanhaikalz on this issue?

**Comment by weidongxu-microsoft** [comment]
@XiaofeiCao I think that it be similar to a previous one (that additional information requires addition query parameter in GET)?

**Comment by XiaofeiCao** [comment]
@weidongxu-microsoft Yes, it's the same issue [here](https://github.com/Azure/azure-sdk-for-java/issues/30981). 

@ihsanhaikalz `innerModel()` is considered implementation detail (as the name inner implies). We do not expose properties like `userType` and `accountEnabled` in our convenience layer code (ActiveDirectoryUser) and we've not planned to expose them in the near future. 

As a workaround, you can use the serviceClient level code to populate these properties in `innerModel()` described [here](https://github.com/Azure/azure-sdk-for-java/issues/30981#issuecomment-1249042764).

**Comment by ihsanhaikalz** [comment]
@XiaofeiCao is there a reason why you won't expose the information? I believe the information would be necessary, especially for security review.

I could not find the serviceClient level from the link you mentioned before, as I can access the ActiveDirectoryUser only from the Access Management package

**Comment by weidongxu-microsoft** [comment]
@ihsanhaikalz 

We actually recommend the dedicated msgraph lib https://github.com/Azure/azure-sdk-for-java/issues/30981#issuecomment-1248853992 if you focus on AAD.

**Comment by ihsanhaikalz** [comment]
@weidongxu-microsoft i have used that too but it also returns null and I have raised the issue https://github.com/microsoftgraph/msgraph-sdk-java/issues/1313

**Comment by weidongxu-microsoft** [comment]
@ihsanhaikalz see Xiaofei's example https://github.com/Azure/azure-sdk-for-java/issues/30981#issuecomment-1249042764

You will observe that one need to set an array of additional items in "select"
```
  Get7ItemsItem.ID, 
  Get7ItemsItem.MAIL,
  Get7ItemsItem.USER_PRINCIPAL_NAME,
  Get7ItemsItem.DISPLAY_NAME,
  Get7ItemsItem.USER_TYPE,
  Get7ItemsItem.CREATION_TYPE,
  Get7ItemsItem.ACCOUNT_ENABLED,
  Get7ItemsItem.CREATED_DATE_TIME,
  Get7ItemsItem.LAST_PASSWORD_CHANGE_DATE_TIME
```

I believe you need to do similar in msgraph's 
```
        UserCollectionPage users = graphClient.users()
                .buildRequest()
                .get();
```

**Comment by ihsanhaikalz** [comment]
@weidongxu-microsoft the code works, thanks! The msgraph also has the same issue as I raised in this issue, but the beta SDK doesn't have this issue.

This brings me to the question, how do I get the information of the innerModel of other resources? Such as CosmoDB or MySQL Server?

**Comment by weidongxu-microsoft** [comment]
@ihsanhaikalz 

I am not sure which beta SDK without this issue?

The last beta of this SDK uses ADGraph (that gets deprecated) as implementation, so the behavior is definitely not same as MSGraph.

The usual recommendation is to avoid use `innerModel` if possible, our test is mostly on e.g. `ActiveDirectoryUser` and its properties.
`innerModel` provides a fallback when these fails. However these are more susceptible to changes in implementation.

On the other hand, this `null` problem in MSGraph is special, as the underlying service (aka MSGraph) is not actually belong to management-plane/control-plane.
