### ISSUE TITLE
[BUG] SiteConfigInner class methods return null

### ISSUE THREAD

**Issue by gabrielspaulino** [Azure/azure-sdk-for-java#32859]
**Describe the bug**
The return of some methods of SiteConfigInner class are always null and do not match the setting in Azure portal. The methods found in testing that always returns null were minTlsVersion() and ftpsState(), it is possible to have others in the same situation.

**To Reproduce**
1. List the web apps by calling the webApps().list() method from AzureResourceManager or get a web app by its id calling webApps().getById() from the same class
2. For each web app it is possible to access the mentioned methods this way:

`azureResourceManager.webApps().getById("/subscriptions/{subscriptionId}/resourceGroups/{resourceGroupName}/providers/Microsoft.Web/sites/{webAppName}").innerModel().siteConfig().ftpsState()`

`azureResourceManager.webApps().getById("/subscriptions/{subscriptionId}/resourceGroups/{resourceGroupName}/providers/Microsoft.Web/sites/{webAppName}").innerModel().siteConfig().minTlsVersion()`
3. Evaluate the return of these methods and check if they match the current state in Azure portal

***Code Snippet***
SiteConfigInner.class
![image](https://user-images.githubusercontent.com/78971112/211656216-39b0dbcf-a135-4bba-aefb-e6824af4400c.png)
![image](https://user-images.githubusercontent.com/78971112/211656140-b272d299-a49e-467a-8c60-50ddc1db68f4.png)

**Expected behavior**
The method minTlsVersion() should return SupportedTlsVersions.ONE_ZERO or SupportedTlsVersions.ONE_ONE or SupportedTlsVersions.ONE_TWO
The method ftpsState() should return FtpsState.ALL_ALLOWED or FtpsState.FTPS_ONLY or FtpsState.DISABLED

**Screenshots**
Web app configuration in Azure:
![cleancloud-webapp minTlsVersion](https://user-images.githubusercontent.com/78971112/211657544-44c1444c-b4e3-4795-9fb1-13660ab34ab5.png)
![cleancloud-webapp ftps state](https://user-images.githubusercontent.com/78971112/211657550-15f406cb-c954-4abb-a607-0c85ba97936c.png)

minTlsVersion() return of the web app above:
![minTlsVersion null](https://user-images.githubusercontent.com/78971112/211657573-991fa831-3af0-4938-9c05-0f874ed3712b.png)

ftpsState() return of the web app above:
![ftpsState null](https://user-images.githubusercontent.com/78971112/211657598-f5396ee5-df77-4207-9977-6298ce1bb4fe.png)

**Setup (please complete the following information):**
 - OS: Windows 11
 - IDE: IntelliJ
 - Library/Libraries: com.azure.resourcemanager:2.22.0
 - Java version: 11
 - App Server/Environment: Intellij
 - Frameworks: Spring

**Information Checklist**
- [ X ] Bug Description Added
- [ X ] Repro Steps Added
- [ X ] Setup information Added

**Comment by joshfree** [comment]
Thank you for this detailed bug report, @gabrielspaulino.  @weidongxu-microsoft will be able to help route this issue.

**Comment by weidongxu-microsoft** [comment]
@gabrielspaulino

Could you use `azureResourceManager.webApps().getById(...).minTlsVersion()`? Similar for `ftpState()`.

They are not in that `innerModel()` of a site response (they are in `sites/{site}/config/web` response). And please avoid use `innerModel()` if possible.
