### ISSUE TITLE
Starttime on cosmos diagnostics not moving with retries

### ISSUE THREAD

**Issue by simplynaveen20** [Azure/azure-sdk-for-java#32899]
**Describe the bug**
Start Time on retry remains the same in responseStaticsList
Version - 4.39.0

**Screenshots**
![image](https://user-images.githubusercontent.com/43345335/211851190-99d4ca75-5234-4776-af9a-07fba3400470.png)

**Comment by kushagraThapar** [comment]
@aayush3011 please take a look at this, thanks!

**Comment by kushagraThapar** [comment]
@rinatmini pls take a look at this, thanks!

**Comment by rinatmini** [comment]
Fixed in #35705
