### ISSUE TITLE
Create README for AzConfig

### ISSUE THREAD

**Issue by conniey** [Azure/azure-sdk-for-java#3292]
Follow the template here to create our README.
https://github.com/Azure/azure-sdk/blob/master/docs/README-TEMPLATE.md

* Should link to samples

**Comment by JonathanGiles** [comment]
Ideally this would be done indirectly by first updating our template module readme, so that we have a Java variant.

**Comment by mayurid** [comment]
@alzimmermsft : for you to look into for Az config.
//cc: @conniey and @JonathanGiles
