### ISSUE TITLE
Publish documentation for Azconfig

### ISSUE THREAD

**Issue by conniey** [Azure/azure-sdk-for-java#3293]
* Understand how we are going to publish documentation on docs.microsoft.com: https://docs.microsoft.com/en-us/azure/azure-app-configuration/overview
* See how we can link this to the API documentation reference

**Comment by srnagar** [comment]
Is this a release blocker? @conniey @mssfang

**Comment by conniey** [comment]
@srnagar  I think for GA, we'd want be able to lead developers to the correct documentation rather than REST APIs, but I think this is an issue across all our Java client libraries. We don't publish to docs.microsoft.com, which is the landing spot for most customers.

I think someone should be working on this overall effort, and have it released shortly if not immediately at GA.
