### ISSUE TITLE
[QUERY] Get RequestOptions custom headers of  ItemBulkOperation from Bulk operation response

### ISSUE THREAD

**Issue by brijeshsinghNuance** [Azure/azure-sdk-for-java#32961]
Is there a way to access custom options(headers) sent in request using RequestOptions  from CosmosBulkOperationResponse?

**Comment by fangjian0423** [comment]
@kushagraThapar could you please take a look?

**Comment by kushagraThapar** [comment]
@aayush3011  can you please take a look at this issue, thanks!

**Comment by mkrueger** [comment]
CosmosBulkOperationResponse has a method:
`CosmosItemOperation getOperation()`

If that operation is an `ItemBulkOperation` you can access the headers with 

`operation.getRequestOptions().getHeaders()` that gives a `Map<String, String>`.
