### ISSUE TITLE
Plug Autorest.Java testsuite in azure-common testing

### ISSUE THREAD

**Issue by lmazuel** [Azure/azure-sdk-for-java#3296]
In order to correctly test azure-common, the autorest.java testsuite should be pulled and done here

See also:
https://github.com/Azure/azure-sdk-for-python/issues/4773

**Comment by yungezz** [comment]
hi @lmazuel not sure how autorest.java is tested today. Is this still valid ask in Track2 context? If yes we'll need work with engsys team on this.

**Comment by lmazuel** [comment]
I still believe this is valuable, and Python repo is doing it. CC @kurtzeborn

**Comment by kurtzeborn** [comment]
This is the folks that work on autorest (@jianghaolu and/or @srnagar) should integrate.  Please reach out to @JimSuplizio and @mitchdenny if you need guidance or support on the engineering system.

**Comment by srnagar** [comment]
@lmazuel - Autorest Java uses a released version of azure-core and `autorest.java` repo has CI pipelines setup to run the tests. Is this task to not use the released version of core and instead use the current azure-core version from master for autorest?

**Comment by lmazuel** [comment]
Hey @srnagar somehow I see your message now :p. Yes, the idea is that each time you touch azure-core in a PR here, you verify that it doesn't break any autorest tests (since they also rely on azure-core). We do that by cloning autorest.language, and run these tests.
