### ISSUE TITLE
Annotation to specify multiple UnexpectedResponseExceptionType

### ISSUE THREAD

**Issue by anuchandy** [Azure/azure-sdk-for-java#3302]
**Is your feature request related to a problem? Please describe.**
The REST Proxy should be able to throw richer exception depending on the error code returned by service. 

**Describe the solution you'd like**
Define an annotation, that can be used to define multiple exception types and map each exception type to error codes.

An example usage looks like:

~~@UnexpectedResponseExceptionTypes({~~
~~@UnexpectedResponseExceptionTypes.Type(code = {333}, value = Exception333.class),~~
~~@UnexpectedResponseExceptionTypes.Type(code = {345, 346}, value = RestException.class),~~
~~@UnexpectedResponseExceptionTypes.Type(value = ServiceRequestException.class)~~
~~})~~

~~The annotation looks like:~~

~~public @interface UnexpectedResponseExceptionTypes {~~
  ~~public Type[] value();~~

  ~~public @interface Type {~~
      ~~public int[] code() default { };~~
      ~~public Class<?> value();~~
  ~~}~~
~~}~~

The above grouping is needed only in java 7 and below, java 8+ supports repeated annotations. Switching to the experience that @JonathanGiles originally proposed. 

Reference: see this [discussion](https://github.com/Azure/azure-sdk-for-java/pull/3286#discussion_r271552994).

Example usage:

```java
@UnexpectedResponseExceptionType(code = {333}, value = Exception333.class),
@UnexpectedResponseExceptionType(code = {345, 346}, value = RestException.class),
@UnexpectedResponseExceptionType(value = ServiceRequestException.class)
```

Annotation definition:

```java
public @interface UnexpectedResponseExceptionType {
    public Class<?> value();
    public int[] code() default { };
}
```

**Information Checklist**
Kindly make sure that you have added all the following information above and checkoff the required fields otherwise we will treat the issuer as an incomplete report
- [x] Description Added
- [x] Expected solution specified

**Comment by JonathanGiles** [comment]
Why not have multiple annotations (of the same type) on the same method like in my code snippet, rather than a single annotation containing multiple values and the new Type type?

**Comment by anuchandy** [comment]
it's because Java don't allow duplicating annotations.

**Comment by JonathanGiles** [comment]
Yes it does :-) https://docs.oracle.com/javase/tutorial/java/annotations/repeating.html

**Comment by anuchandy** [comment]
You're right, starting from source - 8 or above it is allowed to repeat. With source targeting 7 it gives this error: `java: repeated annotations are not supported in -source 7
  (use -source 8 or higher to enable repeated annotations)`

**Comment by JonathanGiles** [comment]
Let's get repeating! :)

**Comment by anuchandy** [comment]
agree, repeating is easy from code generating point of view as well.

**Comment by JonathanGiles** [comment]
@anuchandy  - is this on your todo list before you go on leave? If not, let me know and we'll get someone else working on this.

**Comment by anuchandy** [comment]
@JonathanGiles it's not on my list because @mayurid want @alzimmermsft to do it, see the old issue https://github.com/Azure/azure-sdk-for-java/issues/3139 you you referred in your previous comment.

**Comment by JonathanGiles** [comment]
@jianghaolu will work on this.
