### ISSUE TITLE
[FEATURE REQ]: Add proactive connection regions and warmed up container information to CosmosDiagnostics

### ISSUE THREAD

**Issue by jeet1995** [Azure/azure-sdk-for-java#33038]
# Purpose

For proactive connection management, an application developer configures the `CosmosClientBuilder` with a `ProactiveContainerInitConfig` instance. The `ProactiveContainerInitConfig` instance encapsulates a list of `CosmosContainerIdentity` and the no. of proactive connection regions. These properties should be recorded in a `CosmosDiagnostics` instance.

**Comment by kushagraThapar** [comment]
This is done.
