### ISSUE TITLE
[BUG] spring-cloud-azure-starter-servicebus-jms:5.0.0 not working

### ISSUE THREAD

**Issue by cslobodan** [Azure/azure-sdk-for-java#33118]
Something is wrong with this dependency new version:
```
<dependency>
    <groupId>com.azure.spring</groupId>
    <artifactId>spring-cloud-azure-starter-servicebus-jms</artifactId>
    <version>5.0.0</version>
</dependency>
```
I get the error that `spring.jms.servicebus.pricing-tier` is not valid even though it is set to 'premium'. After switching back to version 4.5.0 it works as expected.

**Comment by joshfree** [comment]
@yiliuTo could you please follow up on this github issue?

**Comment by fangjian0423** [comment]
hi @cslobodan, could you pls provide some more error logs?

**Comment by yiliuTo** [comment]
Hi @cslobodan , could you provide the complete `pom.xml` information? thanks
