### ISSUE TITLE
[BUG] `DataLakeFileSystemClient.listPaths` results in `NumberFomatException`

### ISSUE THREAD

**Issue by jamesnetherton** [Azure/azure-sdk-for-java#33129]
**Describe the bug**
I am experiencing some strange results with the `DataLakeFileSystemClient`. Our project has a test case which uploads a file, then lists the available files in the file system.

This works fine for me. But a colleague using a different storage account, encounters a `NumberFomatException` in class `com.azure.storage.file.datalake.Transforms` within method [`toPathItem`](https://github.com/Azure/azure-sdk-for-java/blob/main/sdk/storage/azure-storage-file-datalake/src/main/java/com/azure/storage/file/datalake/Transforms.java#L361).

The problem occurs with `Long.parseLong(path.getCreationTime())`. When I test with my storage account, the `getCreationTime` returns a Unix epoch timestamp value, thus the long parsing works as expected. When my colleague tests with a different storage account, the creation time is in the format `Thu, 12 Jan 2023 09:44:37 GMT`, hence the resulting `NumberFomatException` from the attempted `Long.parseLong`.

There is a similar issue reported here:

https://stackoverflow.com/questions/73984493/numberformatexception-azure-blob-listing

***Exception or Stack Trace***

```
Caused by: java.lang.NumberFormatException: For input string: "Thu, 12 Jan 2023 11:56:00 GMT"
    at java.base/java.lang.NumberFormatException.forInputString(NumberFormatException.java:67)
    at java.base/java.lang.Long.parseLong(Long.java:711)
    at java.base/java.lang.Long.parseLong(Long.java:836)
    at com.azure.storage.file.datalake.Transforms.toPathItem(Transforms.java:361)
    at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197)
    at java.base/java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1625)
    at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509)
    at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
    at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:921)
    at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
    at java.base/java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:682)
    at com.azure.storage.file.datalake.DataLakeFileSystemAsyncClient.lambda$listPathsWithOptionalTimeout$3(DataLakeFileSystemAsyncClient.java:748)
```

**To Reproduce**
Reproducing is a bit tricky because the issue seems to be Azure account specific. But there's a basic app here to demonstrate the APIs involved.

https://github.com/jamesnetherton/datalake-demo

**Expected behavior**
`DataLakeFileSystemClient.listPaths()` works as intended. 

**Setup (please complete the following information):**
 - OS: Linux
 - IDE: IntelliJ
 - Library/Libraries: `com.azure:azure-core:jar:1.34.0`, `com.azure:azure-storage-file-datalake:jar:12.13.1`
 - Java version: 11 / 17 Temurin / OpenJDK 

**Information Checklist**
Kindly make sure that you have added all the following information above and checkoff the required fields otherwise we will treat the issuer as an incomplete report
- [X] Bug Description Added
- [X] Repro Steps Added
- [X] Setup information Added

**Comment by alzimmermsft** [comment]
Thank you for filing this @jamesnetherton 

@ibrahimrabab mind looking into this?

**Comment by ibrahimrabab** [comment]
Hi @jamesnetherton 
Thank you for reaching out! Apologies on not being able to respond to this issue sooner.

I tried to reproduce the code snippet you linked above and don't run into any problems. Can you tell us what the key differences are between your storage account and your colleague's? That way I can try to create a test account with the same settings as theirs to see if the issue reproduces.

**Comment by jamesnetherton** [comment]
> Can you tell us what the key differences are between your storage account and your colleague's

@ibrahimrabab That's the problem... I cannot see any obvious difference between the accounts.

JSON response for the `Path` object for my account:
```json
{
  "directory": null,
  "etag": "0x8DB04F6C44CE63D",
  "name": "file3307527010503549",
  "isDirectory": null,
  "lastModified": "Thu, 02 Feb 2023 08:23:30 GMT",
  "contentLength": 22,
  "owner": "$superuser",
  "group": "$superuser",
  "permissions": "rw-r-----",
  "EncryptionScope": null,
  "creationTime": "133197998102803537",
  "expiryTime": "0"
}
```

JSON response for the `Path` object on the other account (see the `creationTime` format):
```json
{
  "directory": null,
  "etag": "0x8DB04F8FEAD743D",
  "name": "file6151042123935881",
  "isDirectory": null,
  "lastModified": "Thu, 02 Feb 2023 08:39:27 GMT",
  "contentLength": 22,
  "owner": null,
  "group": null,
  "permissions": null,
  "EncryptionScope": null,
  "creationTime": "Thu, 02 Feb 2023 08:39:26 GMT",
  "expiryTime": null
}
```

Not sure if this issue is related to permissions because I notice there are differences in the `owner`, `group` & `permissions` fields.

**Comment by ibrahimrabab** [comment]
@jamesnetherton Thank you for sharing this. Would you be able to provide the request IDs for the calls made to `listPaths()` for both storage accounts? We will try to use them to investigate what is happening in the backend server.

**Comment by jamesnetherton** [comment]
@ibrahimrabab I have attached the log output from a working request and a failed request. The request Ids can be extracted from that.

[working-request.txt](https://github.com/Azure/azure-sdk-for-java/files/10578260/working-request.txt)

[failed-request.txt](https://github.com/Azure/azure-sdk-for-java/files/10578261/failed-request.txt)

**Comment by ibrahimrabab** [comment]
@jamesnetherton Thanks for sharing! Also, just to confirm, are both of the storage accounts HNS enabled? Or flat namespace?

**Comment by jamesnetherton** [comment]
> Also, just to confirm, are both of the storage accounts HNS enabled?

It was in the working account, it was not in the other account. Apologies @ibrahimrabab , I completely missed that was the case!

That seems to be the root cause of the problem so I guess we can close this issue.

**Comment by ibrahimrabab** [comment]
Great to know that was the issue! Glad to help :)
