### ISSUE TITLE
[BUG]Wrong param description in VirtualMachine DefinitionStages withSsh

### ISSUE THREAD

**Issue by test-auth631** [Azure/azure-sdk-for-java#33131]
**Describe the bug**
The method withSsh(String publicKey) in WithLinuxRootPasswordOrPublicKeyManagedOrUnmanaged and WithLinuxRootPasswordOrPublicKeyManaged describe param publicKey as an SSH public key in the PEM format.
Using a ssh key with PEM format results in the following error :

***Exception or Stack Trace***
com.azure.resourcemanager.compute.models.ApiErrorException: Status code 400, "{
  "error": {
    "code": "InvalidParameter",
    "message": "The value of parameter linuxConfiguration.ssh.publicKeys.keyData is invalid.",
    "target": "linuxConfiguration.ssh.publicKeys.keyData"
  }
}"

**Expected behavior**
The Azure API documentation asks for a SSH public key in ssh-rsa format (NOT PEM).
see https://learn.microsoft.com/en-us/rest/api/compute/virtual-machines/create-or-update?tabs=HTTP#sshpublickey
Passing a SSH public key with ssh-rsa format to the method solves the issue.
So it seems that the javadoc is incorrect

**Setup (please complete the following information):**
 - OS: Windows10
 - IDE: Eclipse
 - Library/Libraries: com.azure.resourcemanager:azure-resourcemanager:2.19.0
 - Java version: 11
 - App Server/Environment: Tomcat
 - Frameworks: Spring Boot

**Comment by joshfree** [comment]
Thanks for sharing feedback on the docs for this API, @test-auth631.  @weidongxu-microsoft could you please help route this?

**Comment by weidongxu-microsoft** [comment]
@XiaofeiCao 

Please check the javadoc. We should say e.g. "at least 2048-bit and in ssh-rsa format", instead of "pem format".

**Comment by XiaofeiCao** [comment]
2.24.0 released.
