### ISSUE TITLE
Update "Getting Started" tutorial for Spring to use our new client

### ISSUE THREAD

**Issue by conniey** [Azure/azure-sdk-for-java#3314]
One of the quick start tutorials creates a Spring App. We should integrate it with our pipeline and make sure our SDK works with it.

https://docs.microsoft.com/en-us/azure/azure-app-configuration/quickstart-java-spring-app

Related to: #3336. #3336 May need to be done first if it is a dependency of this app.

**Comment by mayurid** [comment]
Something for @alzimmermsft to look into

**Comment by srnagar** [comment]
@conniey - I had created a sprint boot "tutorial" for myself on how to use the new Track 2 SDK. Do you think we can use that as the base and build on it?
https://github.com/srnagar/spring-azure-sdk

cc @JonathanGiles

**Comment by conniey** [comment]
Iirc, there was a team working on Spring Boot integration with our libraries. @alzimmermsft would have more context though

**Comment by mrm9084** [comment]
@conniey @mssfang I am the one working on the App Configuration provider which quick start guide was linked to above. That guide is accurate in its use. We do link to the Java Azure SDK similarly to the other SDKs. See under Reference/Configuration/Java Azure SDK.

**Comment by conniey** [comment]
@mrm9084 Hey. The issue was created to see if we use our azure-data-appconfiguration library in the spring-cloud-starter-azure-appconfiguration-config. So, instead of creating and deserializing your own responses from the rest API, you can use our models.

ie. replace
https://github.com/microsoft/spring-cloud-azure/blob/master/spring-cloud-azure-appconfiguration-config/src/main/java/com/microsoft/azure/spring/cloud/config/domain/KeyValueItem.java
with
https://github.com/Azure/azure-sdk-for-java/blob/master/sdk/appconfiguration/azure-data-appconfiguration/src/main/java/com/azure/data/appconfiguration/models/ConfigurationSetting.java

**Comment by mrm9084** [comment]
@conniey Ah, miss understood. We have already started work on creating a version of the Provider that will use the SDK. We are just waiting on it to become stable and maybe out of GA.
