### ISSUE TITLE
[BUG] The message processing callback unhandled exception block further messaging consuming  - com.azure:azure-messaging-servicebus

### ISSUE THREAD

**Issue by lSeneka** [Azure/azure-sdk-for-java#33152]
**Describe the bug**
Each unexpected exception in **ServiceBusProcessorClient** message processor callback totally blocks the receiving.
Moreover, the message whose processing caused an error is considered settled and disappears from the queue/subscription
and will be lost if the service/thread is stopped.

**To Reproduce**
All steps below are based on the test project which can be gotten by a link [GitHub azure issue project](https://github.com/lSeneka/azure-servicebus-issue)

***Steps***
1) Topic and subscription should be created: e.g. [use the Azure portal to create a Service Bus topic and subscriptions](https://learn.microsoft.com/en-us/azure/service-bus-messaging/service-bus-quickstart-topics-subscriptions-portal)
2) Clone the code from repository. Like an option the next command might be used:
```bash
git clone https://github.com/lSeneka/azure-servicebus-issue.git
```
3) Find a class in project directory 
```
../src/test/groovy/org/seneca/asb/TestConfiguration.groovy
```
4) Fulfill the properties
```groovy
    static def connection = "PLACE HERE CONNECTION STRING"
    static def entityPath = "PLACE HERE ENTITY PATH"
    static def subscription = "PLACE HERE SUB"
```
accordingly to the properties of the entity, created on the first step

5) There are 2 tests placed in **EventProcessorClientPoolSpec**. 
   - ```groovy
     "should put messages to the DLQ in case of any unhandled exception during handling of an event by processor with disabled auto complete"   
     ```
     this test uses **EventProcessorManualCompleteClientPool.java** with disabled autocommit processor client.
   - ```groovy
     "should put messages to the DLQ in case of any unhandled exception during handling of an event by processor with enabled auto complete"   
     ```
     this test uses **EventProcessorAutoCompleteClientPool.java** with disabled autocommit processor client.
       
    Both of these tests do pretty much the same:
    1. Creates a set of invalid messages (3 messages)
    2. Sends these messages to the topic by means of test client sender **ServiceBusTopicSenderClient**
    ```groovy
        client = new ServiceBusClientBuilder()
                .connectionString(connection)
                .sender()
                .topicName(entityPath)
                .buildClient()
    ```
    3. Creates a **processor** and thereby starts reading messages from the subscription.
    4. Check if the count of messages processed by **EventHandlersDispatcher** in **dispatchToHandler** method is equal to the expected size of sent messages.
    5. Then reads all the messages from the DLQ expecting that all sent messages should end up there.
    6. Checks if the subscription is empty by means of test receiver client **ServiceBusTopicReceiverClient**
    ```groovy
        client = new ServiceBusClientBuilder()
                .connectionString(connection)
                .receiver()
                .receiveMode(ServiceBusReceiveMode.RECEIVE_AND_DELETE)
                .topicName(entityPath)
                .subscriptionName(subscription)
                .buildClient()
    ```
    7. Check if DLQ for the subscription is empty by means of test DLQ receiver client **ServiceBusDLQForTopicReceiverClient**

    
>The only difference is that: one of test uses **EventProcessorManualCompleteClientPool** and successfully passes and another uses **EventProcessorAutoCompleteClientPool** and always fails
  

**Used workaround:**:
In order not to block messages consuming **ServiceBusProcessorClient** AutoComplete was disabled. 
```java
        return clientBuilder
                .processor()
                .receiveMode(ServiceBusReceiveMode.PEEK_LOCK)
                .topicName(eventProcessorConfigProps.getEntityPath())
                .subscriptionName(eventProcessorConfigProps.getSubscription())
                .prefetchCount(eventProcessorConfigProps.getPrefetchCount())
                .maxConcurrentCalls(eventProcessorConfigProps.getMaxConcurrentCalls())
                .maxAutoLockRenewDuration(eventProcessorConfigProps.getMaxAutoRenewDuration())
                .processMessage(messageContextConsumer)
                .processError(this::logError)
                .disableAutoComplete()
                .buildProcessorClient();
    }
```
and added **complete** and **abandon** for messages
```java
// consumer used to set up the processor callback for handling messages    
private Consumer<ServiceBusReceivedMessageContext> buildMessageContextConsumer() {
        return messageContext ->
                Try.run(() -> this.dispatcher.dispatchToHandler(messageContext.getMessage()))
                        .onSuccess(unused -> messageContext.complete())
                        .onFailure(throwable -> {
                                    var message = messageContext.getMessage();
                                    log.error("Unhandled exception occurred while processing message [id={}, correlationId={}] for entity-path [{}]. Delivery count {}",
                                            message.getMessageId(),
                                            message.getCorrelationId(),
                                            messageContext.getEntityPath(),
                                            message.getDeliveryCount() + 1,
                                            throwable
                                    );
                                    messageContext.abandon();
                                }
                        );
    }
```

**Expected behavior:**
Each message that processing causes an unexpected exception should be redelivered by means of the Message Broker side and in case of exceeding the message's MaxDeliveryCount this message should end up in DLQ.
The same behavior was in the preceding library  "com.microsoft.azure:azure-servicebus" so it is expected from the new one.

**Setup:**
- OS: Linux/k8s container 
- IDE: IntelliJ IDEA (Community edition) Build #IC-223.8214.52
- Library/Libraries: "com.azure:azure-messaging-servicebus:7.13.0"
- Java version: 17
- Test framework: Spock + groovy/JUnit 5
- Build automation tool: gradle-7.6

**Comment by joshfree** [comment]
@ki1729 could you please follow up on this github issue created by @lSeneka

**Comment by anuchandy** [comment]
The behavior is due to the eager completion of the messages due to thread-hoping. Due to this, the message has already been completed by the time the processor callback throws an error. We have a work item to address this. Meantime, the workaround is to do explicit completion as the above code sample does. Please subscribe to that work item https://github.com/Azure/azure-sdk-for-java/issues/33710 for the progress. I'm closing this as a duplicate.
