### ISSUE TITLE
[BUG] CosmosContainer readAllItems and readMany return no results for nested partitionKey

### ISSUE THREAD

**Issue by dkroehan** [Azure/azure-sdk-for-java#33151]
**Describe the bug**
When using the CosmosDB SDK methods `CosmosContainer#readAllItems` or `ComosContainer#readMany` the returned `CosmosPagedIterable` / `FeedResponse` yields no results if the container is set up with a nested partition key (e.g. **/meta/partitionKey**). If the partition key field is on the top-level (e.g. **/partitionKey**) the same code yields the correct results. 

Tested with com.azure:azure-cosmos:4.28.0  and com.azure:azure-cosmos:4.40.0 

**To Reproduce**

1. Create a container where the partition key is a nested field (e.g. /meta/parititionKey).
2. Insert some documents
3. Try to query them with `CosmosContainer#readAllItems` or `ComosContainer#readMany`
4. The response shows 0 results, although elements are present in the container

***Code Snippet***
Code snippets used to fetch the items:
```
    protected  <T> List<T> findByItemIdentities(CosmosContainer container, List<CosmosItemIdentity> itemIdentities, Class<T> entityClass) {
        FeedResponse<T> response = container.readMany(itemIdentities, entityClass);
        return response.getResults();
    }

    protected  <T> List<T> findAll(CosmosContainer container, PartitionKey partitionKey, Class<T> entityClass) {
        CosmosPagedIterable<T> response = container.readAllItems(partitionKey, entityClass);
        return response.stream().collect(Collectors.toList());
    }
```

**Expected behavior**
Both methods should return the correct results, no matter if the partitionKey is a nested field or not.

**Setup (please complete the following information):**
 - OS: Mac OS
 - IDE: IntelliJ
 - Library/Libraries: com.azure:azure-cosmos:4.40.0 
 - Java version: 11 
 - App Server/Environment: Tomcat
 - Frameworks: Spring Boot

**Information Checklist**
Kindly make sure that you have added all the following information above and checkoff the required fields otherwise we will treat the issuer as an incomplete report
- [x] Bug Description Added
- [x] Repro Steps Added
- [x] Setup information Added

**Comment by kushagraThapar** [comment]
@dkroehan I believe this work is currently in progress. @simorenoh  can you please confirm and take a look at this issue, thanks!

**Comment by kushagraThapar** [comment]
This has been fixed in the latest version of java SDK.
