### ISSUE TITLE
[FEATURE REQ] Get RAM parameter for a VM

### ISSUE THREAD

**Issue by lc-lc0304** [Azure/azure-sdk-for-java#33205]
Hi Team:
https://learn.microsoft.com/zh-cn/rest/api/compute/virtual-machines/list?tabs=HTTP

Whether a RAM parameter can be added to vmsize in response hardwareProfile of this interface
Can we add a RAM parameter to the vmsize in the response hardwareProfile of this interface? Because we call this interface now and find that there is no RAM parameter, this parameter is very important to us. We later found the size api and found that there is RAM parameter, but the returned data is too much, which is not very friendly to our developers, Can we give a filter after the url and a key to get the corresponding value? Please help us!

**Comment by joshfree** [comment]
@weidongxu-microsoft could you please follow up on this `Compute` question

**Comment by lc-lc0304** [comment]
Hi！

I'm glad to receive your reply：
https://learn.microsoft.com/en-us/rest/api/compute/virtual-machines/list-available-sizes?tabs=HTTP
Let me ask whether we consider adding a new api. In the document I sent you, give a filter condition after the url to get the following information by looking up the name, as shown in the figure:
![image](https://user-images.githubusercontent.com/82637043/215967238-84029559-3794-4532-bd73-2dd9f739a294.png)

Thank you!

**Comment by weidongxu-microsoft** [comment]
"list-available-sizes" API lists the candidate size for this particular VM to resize. I am not exactly sure if this is appropriate for your use case (you want the memory size of the VMs from a "list").

What I propose is, first call https://learn.microsoft.com/en-us/rest/api/compute/resource-skus/list once and cache the result.

Then when you list the VMs, query the memory size using this cached sku/size -> memory size map.

**Comment by weidongxu-microsoft** [comment]
If you need a new API by filtering the name, you would need backend support.
