### ISSUE TITLE
[FEATURE REQ] Support passwordless connection for Azure Redis cache in Spring M3 - Support Spring Boot 3 + Lettuce

### ISSUE THREAD

**Issue by backwind1233** [Azure/azure-sdk-for-java#33228]
**Is your feature request related to a problem? Please describe.**
We have supported passwordless connections with Azure Redis Cache in Spring with this https://github.com/Azure/azure-sdk-for-java/issues/31350 and https://github.com/Azure/azure-sdk-for-java/pull/32794.

The supported scopes are: Spring Boot 2.x + jedis 3.8.x.

now we would like to enlarge the scopes in Spring Boot 3.x: **Spring Boot 3.x + lettuce 6.2.1.RELEASE**.
Lettuce introduced [Password Rotation support](https://github.com/lettuce-io/lettuce-core/issues/1774) in  lettuce [6.2.0.RELEASE](https://github.com/lettuce-io/lettuce-core/blob/main/RELEASE-NOTES.md#enhancements).
Unlike the passwordless support design in Spring Boot 2.x with jedis, we could utilize this feature to simplify the design.

**Describe the solution you'd like**
Deliver a design spec for the passwordless support to Redis with Spring framework.

Milestone ETA| Goal| Issue|
-- | --|--
Milestone 1 -- Jan |  Support Spring Boot 2.x + Jedis |  https://github.com/Azure/azure-sdk-for-java/issues/31350 |
Milestone 2 -- April | Connect to multiple Azure Redis servers | https://github.com/Azure/azure-sdk-for-java/issues/33227 |
Milestone 3 -- June 23 | Support Spring Boot 3 + Lettuce | https://github.com/Azure/azure-sdk-for-java/issues/33228|
Milestone 4 -- July 23 | Support Spring Boot 3.1 + Jedis| https://github.com/Azure/azure-sdk-for-java/issues/33229 |
Milestone 5 -- Dec 23 | Support native images|  https://github.com/Azure/azure-sdk-for-java/issues/33230  |

**Comment by saragluna** [comment]
Closing this now for the starter to support passwordless + lettuce in Spring Boot 3 has been released.
