### ISSUE TITLE
How can I get the list of application security groups attached to a Network Interface?

### ISSUE THREAD

**Issue by maheshn99** [Azure/azure-sdk-for-java#33236]
**Query/Question**
I am interested in know the list of application security groups attached to a NIC using the latest Java SDK. I see that the com.azure.resourcemanager.network.models.NetworkInterfaceBase interface has getNetworkSecurityGroup method in it however it does not have getApplicationSecurityGroup(s) method. Can you please advise how can I get the info I need using the latest Azure Java SDK?

***Why is this not a Bug or a feature Request?***
This is a query about capabilities.

 
 **Information Checklist**
 Kindly make sure that you have added all the following information above and checkoff the required fields otherwise we will treat the issuer as an incomplete report
- [X] Query Added
- [X] Setup information Added

**Comment by joshfree** [comment]
@weidongxu-microsoft could you please follow up with @maheshn99 on this question?

**Comment by weidongxu-microsoft** [comment]
@XiaofeiCao 

Let's see if we can/want to provide this convenience API.

**Comment by XiaofeiCao** [comment]
@maheshn99 
For now, you should be able to query ASGs like this:
```java
NetworkInterface nic;
// nic requires same asg set for all ip configurations, so get from primary is sufficient
List<ApplicationSecurityGroup> asgs = nic.primaryIPConfiguration().listAssociatedApplicationSecurityGroups()
```

@weidongxu-microsoft 
I'm not sure if we want to provide this API. 
On the one hand, there's `withApplicationSecurityGroup` on `NetworkInterface`, but to query them we need to go down a level to `primaryIPConfiguration`. Seems `applicationSecurityGroups()` on `NetworkInterface` is more consistent.
On the other, do we need the effort since it's just one level down?

**Comment by maheshn99** [comment]
@XiaofeiCao thank your very much! your suggestion helped me achieve what I wanted. 

I am leaving behind a piece of code here which may help others wanting to find out Per VM Per NIC how many ASGs are attached?

_List <String> networkIfIDs = vm.networkInterfaceIds();	
int numOfNWIntfs = networkIfIDs.size();
for(int i=0; i < numOfNWIntfs ; i++) {
NetworkInterface nif = azureResourceManager.networkInterfaces().getById(networkIfIDs.get(i));
List<ApplicationSecurityGroup> asgList = nif.primaryIPConfiguration().listAssociatedApplicationSecurityGroups();_

**Comment by weidongxu-microsoft** [comment]
> @maheshn99 For now, you should be able to query ASGs like this:
> 
> ```java
> NetworkInterface nic;
> // nic requires same asg set for all ip configurations, so get from primary is sufficient
> List<ApplicationSecurityGroup> asgs = nic.primaryIPConfiguration().listAssociatedApplicationSecurityGroups()
> ```
> 
> @weidongxu-microsoft I'm not sure if we want to provide this API. On the one hand, there's `withApplicationSecurityGroup` on `NetworkInterface`, but to query them we need to go down a level to `primaryIPConfiguration`. Seems `applicationSecurityGroups()` on `NetworkInterface` is more consistent. On the other, do we need the effort since it's just one level down?

Sure. Looks good. If it can already be accessed via IPConfiguration, then we should be good.
