### ISSUE TITLE
NoSuchElementException generated by azure-cosmos-4.39.0 and applicationinsights-agent 3.47.0 jar

### ISSUE THREAD

**Issue by asaxena3079** [Azure/azure-sdk-for-java#33239]
Describe the bug
GIVEN following context
SpringBoot : 2.6.3
SpringCloudAzure: 4.5.0 => package com.azure:azure-cosmos:4.39.0
Java ApplicationInsights agent: 3.4.7

WHEN cosmos try to monitor requests

THEN 
 java.util.NoSuchElementException: io.opentelemetry.javaagent.instrumentation.netty.common.client.NettySslInstrumentationHandler
codb-dva2-es-esgm2sql001-eastus2.documents.azure.com) health check request failed due to:
2023-01-31T06:36:41.648806273Z java.util.NoSuchElementException: io.opentelemetry.javaagent.instrumentation.netty.common.client.NettySslInstrumentationHandler

Notes :
Tried with couple of versions of applicationinsights-agent jar, 3.47.0 and 3.2.3 and getting the same exception.

Exception or Stack Trace
 ERROR [cosmos-rntbd-epoll-3-1] com.azure.cosmos.implementation.directconnectivity.rntbd.RntbdRequestManager - Report this azure-cosmos issue to ensure it is addressed:
2023-01-31T06:36:54.697306685Z [ChannelHandlerContext(RntbdRequestManager#0, [id: 0x71cd3f25, L:/169.254.254.3:35456 - R:codb-dva2-es-esgm2sql001-eastus2.documents.azure.com/*******])]
2023-01-31T06:36:54.697314185Z [com.azure.cosmos.implementation.directconnectivity.rntbd.RntbdRequestManager.reportIssue(RntbdRequestManager.java:960)]
2023-01-31T06:36:54.697319285Z [SslHandshakeCompletionEvent(SUCCESS): : java.util.NoSuchElementException: io.opentelemetry.javaagent.instrumentation.netty.common.client.NettySslInstrumentationHandler

To Reproduce

**Comment by joshfree** [comment]
@trask could you take a look?

**Comment by trask** [comment]
hi @asaxena3079!

this looks like the same issue fixed at https://github.com/open-telemetry/opentelemetry-java-instrumentation/pull/6469, which was included in Application Insights Java 3.4.0 (and later).

I just double-checked, and I'm not able to repro that error with Application Insights Java 3.4.7 using the cosmos sample application: https://github.com/Azure-Samples/azure-cosmos-java-getting-started.git

can you double-check that you are getting this same error with Application Insights Java 3.4.7 and Cosmos SDK 4.39.0? and if you are, can you create a repro that we can use to troubleshoot the issue?

**Comment by asaxena3079** [comment]
@trask 

Below is the dependency tree for my application, if it helps. Meanwhile I will create a repo for troubleshooting

[INFO] 
[INFO] --- maven-dependency-plugin:3.1.2:tree (default-cli) @ esgm2-issuer-communication ---
[INFO] com.msci.esg:esgm2-issuer-communication:jar:0.0.1-SNAPSHOT
[INFO] +- org.springframework.boot:spring-boot-starter-webflux:jar:2.6.3:compile
[INFO] |  +- org.springframework.boot:spring-boot-starter:jar:2.6.3:compile
[INFO] |  |  +- org.springframework.boot:spring-boot:jar:2.6.3:compile
[INFO] |  |  \- jakarta.annotation:jakarta.annotation-api:jar:1.3.5:compile
[INFO] |  +- org.springframework.boot:spring-boot-starter-json:jar:2.6.3:compile
[INFO] |  +- org.springframework.boot:spring-boot-starter-reactor-netty:jar:2.6.3:compile
[INFO] |  +- org.springframework:spring-web:jar:5.3.15:compile
[INFO] |  \- org.springframework:spring-webflux:jar:5.3.15:compile
[INFO] +- io.netty:netty-common:jar:4.1.86.Final:compile
[INFO] +- io.projectreactor.netty:reactor-netty-http:jar:1.1.2:compile
[INFO] |  +- io.netty:netty-codec-http:jar:4.1.73.Final:compile
[INFO] |  |  +- io.netty:netty-buffer:jar:4.1.73.Final:compile
[INFO] |  |  +- io.netty:netty-transport:jar:4.1.73.Final:compile
[INFO] |  |  \- io.netty:netty-codec:jar:4.1.73.Final:compile
[INFO] |  +- io.netty:netty-codec-http2:jar:4.1.73.Final:compile
[INFO] |  +- io.netty:netty-resolver-dns:jar:4.1.73.Final:compile
[INFO] |  |  +- io.netty:netty-resolver:jar:4.1.73.Final:compile
[INFO] |  |  \- io.netty:netty-codec-dns:jar:4.1.73.Final:compile
[INFO] |  +- io.netty:netty-resolver-dns-native-macos:jar:osx-x86_64:4.1.73.Final:compile
[INFO] |  |  \- io.netty:netty-resolver-dns-classes-macos:jar:4.1.73.Final:compile
[INFO] |  \- io.netty:netty-transport-native-epoll:jar:linux-x86_64:4.1.73.Final:compile
[INFO] |     +- io.netty:netty-transport-native-unix-common:jar:4.1.73.Final:compile
[INFO] |     \- io.netty:netty-transport-classes-epoll:jar:4.1.73.Final:compile
[INFO] +- io.projectreactor.netty:reactor-netty-http-brave:jar:1.1.2:compile
[INFO] |  \- io.zipkin.brave:brave-instrumentation-http:jar:5.13.7:compile
[INFO] |     \- io.zipkin.brave:brave:jar:5.13.7:compile
[INFO] |        \- io.zipkin.reporter2:zipkin-reporter-brave:jar:2.16.3:compile
[INFO] |           \- io.zipkin.reporter2:zipkin-reporter:jar:2.16.3:compile
[INFO] |              \- io.zipkin.zipkin2:zipkin:jar:2.23.2:compile
[INFO] +- io.projectreactor.netty:reactor-netty-core:jar:1.1.2:compile
[INFO] |  +- io.netty:netty-handler:jar:4.1.73.Final:compile
[INFO] |  |  \- io.netty:netty-tcnative-classes:jar:2.0.46.Final:compile
[INFO] |  \- io.netty:netty-handler-proxy:jar:4.1.73.Final:compile
[INFO] |     \- io.netty:netty-codec-socks:jar:4.1.73.Final:compile
[INFO] +- io.projectreactor:reactor-core:jar:3.4.24:compile
[INFO] |  \- org.reactivestreams:reactive-streams:jar:1.0.3:compile
[INFO] +- org.springframework.boot:spring-boot-starter-security:jar:2.6.3:compile
[INFO] |  +- org.springframework:spring-aop:jar:5.3.15:compile
[INFO] |  \- org.springframework.security:spring-security-config:jar:5.6.1:compile
[INFO] +- org.springframework.security:spring-security-web:jar:5.6.9:compile
[INFO] +- org.springframework.boot:spring-boot-starter-log4j2:jar:2.6.3:compile
[INFO] |  +- org.apache.logging.log4j:log4j-slf4j-impl:jar:2.17.1:compile
[INFO] |  |  \- org.apache.logging.log4j:log4j-api:jar:2.17.1:compile
[INFO] |  +- org.apache.logging.log4j:log4j-core:jar:2.17.1:compile
[INFO] |  +- org.apache.logging.log4j:log4j-jul:jar:2.17.1:compile
[INFO] |  \- org.slf4j:jul-to-slf4j:jar:1.7.33:compile
[INFO] +- org.springframework.boot:spring-boot-starter-actuator:jar:2.6.3:compile
[INFO] |  +- org.springframework.boot:spring-boot-actuator-autoconfigure:jar:2.6.3:compile
[INFO] |  |  \- org.springframework.boot:spring-boot-actuator:jar:2.6.3:compile
[INFO] |  \- io.micrometer:micrometer-core:jar:1.8.2:compile
[INFO] |     \- org.latencyutils:LatencyUtils:jar:2.0.3:runtime
[INFO] +- org.springframework.boot:spring-boot-starter-test:jar:2.6.3:test
[INFO] |  +- org.springframework.boot:spring-boot-test:jar:2.6.3:test
[INFO] |  +- org.springframework.boot:spring-boot-test-autoconfigure:jar:2.6.3:test
[INFO] |  +- com.jayway.jsonpath:json-path:jar:2.6.0:test
[INFO] |  +- jakarta.xml.bind:jakarta.xml.bind-api:jar:2.3.3:compile
[INFO] |  |  \- jakarta.activation:jakarta.activation-api:jar:1.2.2:compile
[INFO] |  +- org.assertj:assertj-core:jar:3.21.0:compile
[INFO] |  +- org.hamcrest:hamcrest:jar:2.2:test
[INFO] |  +- org.mockito:mockito-core:jar:4.0.0:test
[INFO] |  |  +- net.bytebuddy:byte-buddy:jar:1.11.22:runtime
[INFO] |  |  +- net.bytebuddy:byte-buddy-agent:jar:1.11.22:test
[INFO] |  |  \- org.objenesis:objenesis:jar:3.2:test
[INFO] |  +- org.mockito:mockito-junit-jupiter:jar:4.0.0:test
[INFO] |  +- org.skyscreamer:jsonassert:jar:1.5.0:test
[INFO] |  |  \- com.vaadin.external.google:android-json:jar:0.0.20131108.vaadin1:test
[INFO] |  +- org.springframework:spring-test:jar:5.3.15:test
[INFO] |  \- org.xmlunit:xmlunit-core:jar:2.8.4:test
[INFO] +- io.projectreactor:reactor-test:jar:3.4.14:test
[INFO] +- org.junit.vintage:junit-vintage-engine:jar:5.8.2:test
[INFO] |  +- org.junit.platform:junit-platform-engine:jar:1.8.2:test
[INFO] |  +- junit:junit:jar:4.13.2:test
[INFO] |  |  \- org.hamcrest:hamcrest-core:jar:2.2:test
[INFO] |  \- org.apiguardian:apiguardian-api:jar:1.1.2:test
[INFO] +- org.junit.jupiter:junit-jupiter-api:jar:5.8.2:test
[INFO] |  +- org.opentest4j:opentest4j:jar:1.2.0:test
[INFO] |  \- org.junit.platform:junit-platform-commons:jar:1.8.2:test
[INFO] +- org.junit.jupiter:junit-jupiter-engine:jar:5.8.2:test
[INFO] +- org.junit.platform:junit-platform-launcher:jar:1.8.2:test
[INFO] +- com.fasterxml.jackson.core:jackson-databind:jar:2.13.4.2:compile
[INFO] +- com.networknt:json-schema-validator:jar:1.0.68:compile
[INFO] |  +- org.slf4j:slf4j-api:jar:1.7.33:compile
[INFO] |  \- com.ethlo.time:itu:jar:1.5.1:compile
[INFO] +- org.projectlombok:lombok:jar:1.18.22:compile
[INFO] +- com.google.guava:guava:jar:31.1-jre:compile
[INFO] |  +- com.google.guava:failureaccess:jar:1.0.1:compile
[INFO] |  +- com.google.guava:listenablefuture:jar:9999.0-empty-to-avoid-conflict-with-guava:compile
[INFO] |  +- com.google.code.findbugs:jsr305:jar:3.0.2:compile
[INFO] |  +- org.checkerframework:checker-qual:jar:3.12.0:compile
[INFO] |  +- com.google.errorprone:error_prone_annotations:jar:2.11.0:compile
[INFO] |  \- com.google.j2objc:j2objc-annotations:jar:1.3:compile
[INFO] +- org.apache.commons:commons-lang3:jar:3.12.0:compile
[INFO] +- org.apache.commons:commons-collections4:jar:4.4:compile
[INFO] +- com.azure:azure-spring-data-cosmos:jar:3.19.0:compile
[INFO] |  +- org.springframework:spring-tx:jar:5.3.15:compile
[INFO] |  +- org.springframework.data:spring-data-commons:jar:2.6.1:compile
[INFO] |  +- com.fasterxml.jackson.module:jackson-module-parameter-names:jar:2.13.1:compile
[INFO] |  +- com.fasterxml.jackson.datatype:jackson-datatype-jdk8:jar:2.13.1:compile
[INFO] |  +- org.javatuples:javatuples:jar:1.2:compile
[INFO] |  \- javax.annotation:javax.annotation-api:jar:1.3.2:compile
[INFO] +- org.springframework:spring-context:jar:5.3.19:compile
[INFO] +- org.springframework:spring-beans:jar:5.3.20:compile
[INFO] +- org.springframework:spring-expression:jar:5.3.17:compile
[INFO] +- org.springframework:spring-core:jar:5.3.20:provided
[INFO] |  \- org.springframework:spring-jcl:jar:5.3.15:provided
[INFO] +- org.springdoc:springdoc-openapi-webflux-ui:jar:1.6.6:compile
[INFO] |  +- org.springdoc:springdoc-openapi-webflux-core:jar:1.6.6:compile
[INFO] |  |  \- org.springdoc:springdoc-openapi-common:jar:1.6.6:compile
[INFO] |  |     \- io.swagger.core.v3:swagger-core:jar:2.1.12:compile
[INFO] |  |        +- com.fasterxml.jackson.dataformat:jackson-dataformat-yaml:jar:2.13.1:compile
[INFO] |  |        +- io.swagger.core.v3:swagger-annotations:jar:2.1.12:compile
[INFO] |  |        \- io.swagger.core.v3:swagger-models:jar:2.1.12:compile
[INFO] |  +- org.webjars:swagger-ui:jar:4.5.0:compile
[INFO] |  +- org.webjars:webjars-locator-core:jar:0.48:compile
[INFO] |  \- io.github.classgraph:classgraph:jar:4.8.138:compile
[INFO] +- com.fasterxml.jackson.datatype:jackson-datatype-jsr310:jar:2.13.2:compile
[INFO] +- io.springfox:springfox-spring-webflux:jar:3.0.0:compile
[INFO] |  +- com.fasterxml:classmate:jar:1.5.1:compile
[INFO] |  +- org.springframework.plugin:spring-plugin-core:jar:2.0.0.RELEASE:compile
[INFO] |  +- org.springframework.plugin:spring-plugin-metadata:jar:2.0.0.RELEASE:compile
[INFO] |  +- io.springfox:springfox-spi:jar:3.0.0:runtime
[INFO] |  +- io.springfox:springfox-schema:jar:3.0.0:runtime
[INFO] |  +- io.springfox:springfox-core:jar:3.0.0:runtime
[INFO] |  \- io.springfox:springfox-spring-web:jar:3.0.0:runtime
[INFO] +- org.modelmapper:modelmapper:jar:3.0.0:compile
[INFO] +- com.google.code.gson:gson:jar:2.9.0:compile
[INFO] +- com.microsoft.azure:spring-cloud-azure-appconfiguration-config:jar:1.3.0:compile
[INFO] |  +- org.springframework.boot:spring-boot-autoconfigure-processor:jar:2.6.3:compile
[INFO] |  +- org.springframework.boot:spring-boot-autoconfigure:jar:2.6.3:compile
[INFO] |  +- com.azure:azure-data-appconfiguration:jar:1.3.9:compile
[INFO] |  +- com.azure:azure-security-keyvault-secrets:jar:4.5.2:compile
[INFO] |  +- com.azure:azure-core-http-netty:jar:1.12.7:compile
[INFO] |  |  +- io.netty:netty-transport-native-kqueue:jar:osx-x86_64:4.1.73.Final:compile
[INFO] |  |  |  \- io.netty:netty-transport-classes-kqueue:jar:4.1.73.Final:compile
[INFO] |  |  \- io.netty:netty-tcnative-boringssl-static:jar:2.0.47.Final:compile
[INFO] |  \- org.hibernate.validator:hibernate-validator:jar:6.2.0.Final:compile
[INFO] |     +- jakarta.validation:jakarta.validation-api:jar:2.0.2:compile
[INFO] |     \- org.jboss.logging:jboss-logging:jar:3.4.3.Final:compile
[INFO] +- org.springframework.cloud:spring-cloud-starter-bootstrap:jar:3.1.1:compile
[INFO] |  \- org.springframework.cloud:spring-cloud-starter:jar:3.1.1:compile
[INFO] |     +- org.springframework.cloud:spring-cloud-context:jar:3.1.1:compile
[INFO] |     +- org.springframework.cloud:spring-cloud-commons:jar:3.1.1:compile
[INFO] |     \- org.springframework.security:spring-security-rsa:jar:1.0.10.RELEASE:compile
[INFO] |        \- org.bouncycastle:bcpkix-jdk15on:jar:1.68:compile
[INFO] |           \- org.bouncycastle:bcprov-jdk15on:jar:1.68:compile
[INFO] +- org.springframework.security:spring-security-crypto:jar:5.6.4:provided
[INFO] +- com.fasterxml.jackson.core:jackson-core:jar:2.13.2:compile
[INFO] +- com.fasterxml.jackson.core:jackson-annotations:jar:2.13.2:compile
[INFO] +- com.azure:azure-cosmos:jar:4.39.0:compile
[INFO] |  +- com.azure:azure-core:jar:1.34.0:compile
[INFO] |  |  \- com.fasterxml.jackson.dataformat:jackson-dataformat-xml:jar:2.13.1:compile
[INFO] |  +- com.fasterxml.jackson.module:jackson-module-afterburner:jar:2.13.1:compile
[INFO] |  +- org.hdrhistogram:HdrHistogram:jar:2.1.12:compile
[INFO] |  \- io.dropwizard.metrics:metrics-core:jar:4.2.7:compile
[INFO] +- com.fasterxml.woodstox:woodstox-core:jar:6.4.0:compile
[INFO] |  \- org.codehaus.woodstox:stax2-api:jar:4.2.1:compile
[INFO] +- com.azure:azure-identity:jar:1.4.6:compile
[INFO] |  +- com.microsoft.azure:msal4j:jar:1.11.0:compile
[INFO] |  |  \- com.nimbusds:oauth2-oidc-sdk:jar:9.7:compile
[INFO] |  |     +- com.nimbusds:content-type:jar:2.1:compile
[INFO] |  |     \- com.nimbusds:lang-tag:jar:1.5:compile
[INFO] |  +- com.microsoft.azure:msal4j-persistence-extension:jar:1.1.0:compile
[INFO] |  |  \- net.java.dev.jna:jna:jar:5.5.0:compile
[INFO] |  +- net.java.dev.jna:jna-platform:jar:5.6.0:compile
[INFO] |  \- net.minidev:json-smart:jar:2.4.7:compile
[INFO] |     \- net.minidev:accessors-smart:jar:2.4.7:compile
[INFO] |        \- org.ow2.asm:asm:jar:9.1:compile
[INFO] +- org.apache.httpcomponents:httpclient:jar:4.5.13:compile
[INFO] |  +- org.apache.httpcomponents:httpcore:jar:4.4.15:compile
[INFO] |  \- commons-codec:commons-codec:jar:1.15:compile
[INFO] +- com.auth0:java-jwt:jar:3.19.0:compile
[INFO] +- org.json:json:jar:20220320:compile
[INFO] +- org.springframework.boot:spring-boot-starter-oauth2-resource-server:jar:2.7.0:compile
[INFO] +- org.springframework.security:spring-security-core:jar:5.6.9:compile
[INFO] +- com.msci.esg:esgm2-climatelab-model:jar:75.0.0-SNAPSHOT:compile
[INFO] |  \- org.slf4j:slf4j-nop:jar:1.7.33:compile
[INFO] +- com.msci.esg:esgm2-climatelab-rules:jar:22.0.0-SNAPSHOT:compile
[INFO] |  +- org.kie:kie-ci:jar:8.18.0.Beta:compile
[INFO] |  |  +- org.drools:drools-wiring-api:jar:8.18.0.Beta:compile
[INFO] |  |  +- org.drools:drools-wiring-dynamic:jar:8.18.0.Beta:compile
[INFO] |  |  +- org.drools:drools-serialization-protobuf:jar:8.18.0.Beta:compile
[INFO] |  |  |  \- org.drools:drools-tms:jar:8.18.0.Beta:compile
[INFO] |  |  +- org.kie:kie-api:jar:8.18.0.Beta:compile
[INFO] |  |  +- org.kie:kie-util-maven-support:jar:8.18.0.Beta:compile
[INFO] |  |  +- org.kie:kie-util-maven-integration:jar:8.18.0.Beta:compile
[INFO] |  |  |  +- org.apache.maven:maven-artifact:jar:3.3.9:compile
[INFO] |  |  |  +- org.apache.maven:maven-plugin-api:jar:3.3.9:compile
[INFO] |  |  |  +- org.eclipse.aether:aether-util:jar:1.1.0:compile
[INFO] |  |  |  +- org.eclipse.aether:aether-spi:jar:1.1.0:compile
[INFO] |  |  |  +- org.eclipse.aether:aether-transport-file:jar:1.1.0:compile
[INFO] |  |  |  +- org.eclipse.aether:aether-transport-http:jar:1.1.0:compile
[INFO] |  |  |  +- jakarta.inject:jakarta.inject-api:jar:1.0.3:compile
[INFO] |  |  |  +- jakarta.enterprise:jakarta.enterprise.cdi-api:jar:2.0.2:compile
[INFO] |  |  |  |  +- jakarta.el:jakarta.el-api:jar:3.0.3:compile
[INFO] |  |  |  |  \- jakarta.interceptor:jakarta.interceptor-api:jar:1.2.5:compile
[INFO] |  |  |  |     \- jakarta.ejb:jakarta.ejb-api:jar:3.2.6:compile
[INFO] |  |  |  |        \- jakarta.transaction:jakarta.transaction-api:jar:1.3.3:compile
[INFO] |  |  |  +- org.apache.ant:ant:jar:1.10.11:compile
[INFO] |  |  |  |  \- org.apache.ant:ant-launcher:jar:1.10.11:compile
[INFO] |  |  |  \- com.google.inject:guice:jar:no_aop:4.0:compile
[INFO] |  |  |     \- aopalliance:aopalliance:jar:1.0:compile
[INFO] |  |  +- org.apache.maven:maven-core:jar:3.3.9:compile
[INFO] |  |  |  +- org.apache.maven:maven-repository-metadata:jar:3.3.9:compile
[INFO] |  |  |  +- org.codehaus.plexus:plexus-interpolation:jar:1.21:compile
[INFO] |  |  |  \- org.codehaus.plexus:plexus-component-annotations:jar:1.6:compile
[INFO] |  |  +- org.apache.maven:maven-model:jar:3.3.9:compile
[INFO] |  |  +- org.apache.maven:maven-model-builder:jar:3.3.9:compile
[INFO] |  |  |  \- org.apache.maven:maven-builder-support:jar:3.3.9:compile
[INFO] |  |  +- org.apache.maven:maven-settings:jar:3.3.9:compile
[INFO] |  |  +- org.apache.maven:maven-settings-builder:jar:3.3.9:compile
[INFO] |  |  +- org.apache.maven:maven-compat:jar:3.3.9:compile
[INFO] |  |  +- org.apache.maven:maven-aether-provider:jar:3.3.9:compile
[INFO] |  |  +- org.apache.maven.wagon:wagon-provider-api:jar:3.0.0:compile
[INFO] |  |  +- org.sonatype.plexus:plexus-sec-dispatcher:jar:1.3:compile
[INFO] |  |  +- org.codehaus.plexus:plexus-classworlds:jar:2.6.0:compile
[INFO] |  |  +- org.codehaus.plexus:plexus-utils:jar:3.2.1:compile
[INFO] |  |  +- org.eclipse.aether:aether-api:jar:1.1.0:compile
[INFO] |  |  +- org.eclipse.aether:aether-impl:jar:1.1.0:compile
[INFO] |  |  +- org.eclipse.aether:aether-connector-basic:jar:1.1.0:compile
[INFO] |  |  +- org.eclipse.aether:aether-transport-wagon:jar:1.1.0:compile
[INFO] |  |  +- org.eclipse.sisu:org.eclipse.sisu.plexus:jar:0.3.4:compile
[INFO] |  |  |  +- javax.enterprise:cdi-api:jar:1.0:compile
[INFO] |  |  |  |  +- javax.annotation:jsr250-api:jar:1.0:compile
[INFO] |  |  |  |  \- javax.inject:javax.inject:jar:1:compile
[INFO] |  |  |  \- org.eclipse.sisu:org.eclipse.sisu.inject:jar:0.3.4:compile
[INFO] |  |  +- org.apache.maven.wagon:wagon-http:jar:3.0.0:compile
[INFO] |  |  |  \- org.apache.maven.wagon:wagon-http-shared:jar:3.0.0:compile
[INFO] |  |  +- commons-io:commons-io:jar:2.11.0:compile
[INFO] |  |  +- org.slf4j:jcl-over-slf4j:jar:1.7.33:compile
[INFO] |  |  \- org.sonatype.plexus:plexus-cipher:jar:1.7:compile
[INFO] |  +- org.drools:drools-decisiontables:jar:8.18.0.Beta:compile
[INFO] |  |  +- org.drools:drools-templates:jar:8.18.0.Beta:compile
[INFO] |  |  +- org.apache.poi:poi-ooxml:jar:5.1.0:compile
[INFO] |  |  |  +- org.apache.poi:poi-ooxml-lite:jar:5.1.0:compile
[INFO] |  |  |  +- org.apache.xmlbeans:xmlbeans:jar:5.0.2:compile
[INFO] |  |  |  +- org.apache.commons:commons-compress:jar:1.21:compile
[INFO] |  |  |  \- com.github.virtuald:curvesapi:jar:1.06:compile
[INFO] |  |  \- org.apache.poi:poi:jar:5.1.0:compile
[INFO] |  |     +- org.apache.commons:commons-math3:jar:3.6.1:compile
[INFO] |  |     \- com.zaxxer:SparseBitSet:jar:1.2:compile
[INFO] |  +- org.drools:drools-core:jar:8.18.0.Beta:compile
[INFO] |  |  +- org.kie:kie-util-xml:jar:8.18.0.Beta:compile
[INFO] |  |  \- org.drools:drools-wiring-static:jar:8.18.0.Beta:compile
[INFO] |  +- org.drools:drools-compiler:jar:8.18.0.Beta:compile
[INFO] |  |  +- org.drools:drools-drl-parser:jar:8.18.0.Beta:compile
[INFO] |  |  +- org.drools:drools-drl-extensions:jar:8.18.0.Beta:compile
[INFO] |  |  +- org.drools:drools-drl-ast:jar:8.18.0.Beta:compile
[INFO] |  |  +- org.drools:drools-kiesession:jar:8.18.0.Beta:compile
[INFO] |  |  +- org.kie:kie-memory-compiler:jar:8.18.0.Beta:compile
[INFO] |  |  +- org.drools:drools-ecj:jar:8.18.0.Beta:compile
[INFO] |  |  \- org.antlr:antlr-runtime:jar:3.5.2:compile
[INFO] |  +- org.drools:drools-mvel:jar:8.18.0.Beta:compile
[INFO] |  +- org.kie:kie-internal:jar:8.18.0.Beta:compile
[INFO] |  \- org.mvel:mvel2:jar:2.4.5.Final:compile
[INFO] +- org.springframework.security:spring-security-oauth2-resource-server:jar:5.6.1:compile
[INFO] |  \- org.springframework.security:spring-security-oauth2-core:jar:5.6.1:compile
[INFO] +- org.springframework.security:spring-security-oauth2-jose:jar:5.6.1:compile
[INFO] |  \- com.nimbusds:nimbus-jose-jwt:jar:9.14:compile
[INFO] |     \- com.github.stephenc.jcip:jcip-annotations:jar:1.0-1:compile
[INFO] +- com.msci.entitlement:entitlement-client-spring-boot-starter:jar:1.0.4:compile
[INFO] |  +- com.msci.entitlement:entitlement-client:jar:1.0.4:compile
[INFO] |  |  +- io.projectreactor.netty:reactor-netty:jar:1.0.15:runtime
[INFO] |  |  |  \- io.projectreactor.netty.incubator:reactor-netty-incubator-quic:jar:0.0.4:runtime
[INFO] |  |  |     \- io.netty.incubator:netty-incubator-codec-native-quic:jar:linux-x86_64:0.0.25.Final:runtime
[INFO] |  |  |        \- io.netty.incubator:netty-incubator-codec-classes-quic:jar:0.0.25.Final:runtime
[INFO] |  |  \- org.mapstruct:mapstruct:jar:1.4.2.Final:runtime
[INFO] |  \- org.springframework.boot:spring-boot-starter-validation:jar:2.6.3:runtime
[INFO] |     \- org.apache.tomcat.embed:tomcat-embed-el:jar:9.0.56:runtime
[INFO] +- org.yaml:snakeyaml:jar:1.33:compile
[INFO] +- com.azure:azure-messaging-servicebus:jar:7.5.2:compile
[INFO] |  \- com.azure:azure-core-amqp:jar:2.8.0:compile
[INFO] |     +- com.microsoft.azure:qpid-proton-j-extensions:jar:1.2.4:compile
[INFO] |     \- org.apache.qpid:proton-j:jar:0.33.8:compile
[INFO] +- org.glassfish.web:el-impl:jar:2.2:compile
[INFO] |  \- javax.el:el-api:jar:2.2:compile
[INFO] +- com.msci.esg:esgm2-climatelab-dvjson-extractor:jar:11.0.0-SNAPSHOT:compile
[INFO] \- com.azure.spring:spring-cloud-azure-starter-keyvault-secrets:jar:4.5.0:compile
[INFO]    \- com.azure.spring:spring-cloud-azure-starter:jar:4.5.0:compile
[INFO]       \- com.azure.spring:spring-cloud-azure-autoconfigure:jar:4.5.0:compile
[INFO]          \- com.azure.spring:spring-cloud-azure-service:jar:4.5.0:compile
[INFO]             \- com.azure.spring:spring-cloud-azure-core:jar:4.5.0:compile
[INFO]                \- com.azure:azure-core-management:jar:1.9.0:compile

**Comment by trask** [comment]
hi @asaxena3079! just checking if you've had any luck creating a repro that we can use to troubleshoot the issue? thx
