### ISSUE TITLE
Need tools to ensure we publish full closure of parent POMs

### ISSUE THREAD

**Issue by weshaggard** [Azure/azure-sdk-for-java#3324]
When we release a library project we need to ensure that we are publishing all the dependencies that it pulls in as well, especially the parent POM's. We need to write some tooling to ensure that all the reference parent POM's are already published. We should also consider coming up with a strategy that ensures we always ship parent poms when they have changes.

**Comment by weshaggard** [comment]
cc @JonathanGiles

**Comment by weshaggard** [comment]
We should consider using a command like:
```
mvn dependency:analyze "-Dmaven.repo.local=<local isolated repo>"
```

That will run the analyze command in a local repo so that we don't accidentally depend on stuff installed on the machine but not in the remote repository.

**Comment by weshaggard** [comment]
Issue https://github.com/Azure/azure-sdk-for-java/issues/4003 is tracking a strategy for the parent pom versioning and publishing. This issue is tracking the addition of some tooling to help catch issues we might have with the parent pom but if the version in the repo and on maven are the same we will still not easily catch differences in those packages.

**Comment by JimSuplizio** [comment]
@weshaggard is this issue still necessary? In theory, we should no longer need to be publishing the parent poms, at least for client and data, since the dependencyManagement section was removed and those post-removal versions were published. The last client release didn't require parent pom publishing and, similarly, the last Cosmos release didn't require them to publish their parent pom either.

**Comment by weshaggard** [comment]
It is probably less interesting from parent pom prospective but it still may be interesting from a dependency validation step. The hardest part in verifying that all the project dependencies are already published is the delay in maven publishing, perhaps that can be figured out with our plan to publish to devops feed as well.

**Comment by weshaggard** [comment]
@mitchdenny any thoughts on this issue after our parent pom work gets done?

**Comment by mitchdenny** [comment]
Parent POM restructuring is pretty much done down I think (need to double check all my issues). So if that was a blocker then I guess it is time to start thinking about this :) 

Do we know that Maven Central doesn't block uploads of packages where all its dependencies aren't met? They seem to check for a lot of other conditions. I can't recall whether we've seen this issue in Maven previously.
