### ISSUE TITLE
update java example for managedidentity using azure-identity library and latest dependency versions [FEATURE REQ]

### ISSUE THREAD

**Issue by tristanessquare** [Azure/azure-sdk-for-java#33243]
**Is your feature request related to a problem? Please describe.**
We wanted to use the latest version of the azure-identity library to implement managedidentity authentication over kafka api. The java example included in this repository only shows the approach using the old azure-client-authentication library. When we tried to simply replace the azure-client-authentication with azure-identity, we encountered the following issue:

Requesting a token for scope "https://mynamespace.servicebus.windows.net" failed. After investigating the issue we found out that we had to add "/.default" as suffix to the requested scope.

Another problem we encountered was the usage of the outdated java version 1.7. We would expect to use the latest java and dependency versions.

**Describe the solution you'd like**
We would like to have an example that:

- shows the usage of the azure-identity library
- is working (adds the '/.default' suffix to the requested scope
- has java version and all dependencies updated

**Describe alternatives you've considered**
none

**Additional context**
none

**Information Checklist**
- [x] Description Added
- [x] Expected solution specified

**Comment by joshfree** [comment]
@billwert could you follow up with @tristanessquare on this azure-identity documentation/sample improvement?

**Comment by tristanessquare** [comment]
I think this issue should have been created under https://github.com/Azure/azure-event-hubs-for-kafka. I have already created a PR for this improvement there: https://github.com/Azure/azure-event-hubs-for-kafka/pull/234

Is it possible to move this issue or should I create a new one there and close this issue?

Thank you for your support.

**Comment by billwert** [comment]
hey @tristanessquare! 

Thanks for making the PR. It is probably easiest to just make a new issue over there. Thank you!
