### ISSUE TITLE
[BUG] Update NSG Rule - Unable to Change From ASG to Service Tag Source\Destination

### ISSUE THREAD

**Issue by NatanelY** [Azure/azure-sdk-for-java#33291]
**Describe the bug**
We are using Azure SDK for Java (azure-resourcemanager library), version: 2.20.0.
We are trying Update rule destination from ASG to ServiceTag, getting exception code 400 with the following error message.

***Exception or Stack Trace***
com.azure.core.management.exception.ManagementException: Status code 400, "{
  "error": {
    "code": "SecurityRuleInvalidAddressPrefix",
    "message": "Security rule /subscriptions/”subscription_id”/resourceGroups/CM/providers/Microsoft.Network/networkSecurityGroups/CMvm-nsg/securityRules/Michal TEST has invalid Address prefix. Value provided: Michal TEST2",
    "details": []
  }
}"

**To Reproduce**
Select a rule with ASG in source\ destination and try to replace it with service tag

***Code Snippet***
NetworkSecurityGroup nsg = azure.networkSecurityGroups().getByResourceGroup("CM", "CMvm-nsg");
        
nsg.update()
.updateRule("Michal TEST")
.toAddress("Internet")
.parent()
.apply();

**Expected behavior**
The Application Security Group(ASG) should be replace with Service Tag

**Setup (please complete the following information):**
 - OS: windows\linux
 - IDE: IntelliJ
 - Library/Libraries: com.azure.resourcemanager:azure-resourcemanager:2.20.0com.azure.resourcemanager:azure-resourcemanager-network:2.20.0
 - Java version: 8
 - App Server/Environment: Apache Maven

**Additional context**
We assume the issue cause is;
toAddress method updates the innerModel destination ASGs , but not the destinationAsgs map in NetworkSecurityGroupImpl.
then, when calling parent() method, destinationASGs list is used (still contains the removed ASG), and pushed to the inner model.

**Comment by joshfree** [comment]
@weidongxu-microsoft could you please follow up on this issue with @NatanelY

**Comment by XiaofeiCao** [comment]
Thanks @NatanelY , it's the issue described [here](https://github.com/Azure/azure-sdk-for-java/issues/31070#issuecomment-1260587126). I'll fix it.

**Comment by NatanelY** [comment]
@XiaofeiCao 
do you have an estimation when we can get a new version with this fix included ?

**Comment by XiaofeiCao** [comment]
Hi @NatanelY , it'll be fixed in upcoming 2.24.0 around 2/24.

**Comment by XiaofeiCao** [comment]
@NatanelY 2.24.0 released with the fix.

**Comment by NatanelY** [comment]
@XiaofeiCao 
Thank you very much,
we will install the new version and test if it solve the problem.
