### ISSUE TITLE
BlobClient downloadToFile hangs forever if blob doesn't exist

### ISSUE THREAD

**Issue by ataquedosesquilos** [Azure/azure-sdk-for-java#33294]
**Is your feature request related to a problem? Please describe.**
When executing downToFile from BlobService, if the blob doesn't exist the thread hangs forever, if a dev does an unchecked download it could be very harmful to the server as threads will keep hanging forever

**Describe the solution you'd like**
I would expect an exception to be thrown if the blob doesn't exist or it's locked. 

**Describe alternatives you've considered**
Alternatively you could download an empty file but believe leaving the thread hanging is a very incorrect behaviour.

**Additional context**
none at th emoment

**Comment by joshfree** [comment]
Hi @ataquedosesquilos thanks for reaching out to us via this github issue.  Someone from the Storage SDK team will follow up with you shortly.

/cc @jaschrep-msft

**Comment by ibrahimrabab** [comment]
Hi @ataquedosesquilos 

Thanks for reaching out! When I test the downloadToFile() method with a blob that does not exist, I get the following error immediately,

**Status code 404, "?<?xml version="1.0" encoding="utf-8"?><Error><Code>BlobNotFound</Code><Message>The specified blob does not exist.**

Can you provide a code sample of how exactly you are reproducing the hanging error? Also, did you specify any retry options on the blob client?
