### ISSUE TITLE
[BUG] VirtualMachineScaleSetNicIpConfiguration.innerModel().publicIpAddress().ipAddress() always returns null

### ISSUE THREAD

**Issue by evolkovgit** [Azure/azure-sdk-for-java#33299]
I programmatically (Azure, Java SDK) create Virtual Machine Scale Set ((Linux OS - Ubuntu) with ".withVirtualMachinePublicIp()" option during the creation. It works OK, I can see the instances and their public IP Addresses in the Azure Portal. I can ssh into the instances, etc... However I cannot get the public IP Addresses via Azure Java API, it always returns null. I tried a lot , the below code is just one of the attempts.

**To Reproduce**
Run the below code

***Code Snippet***
 ```
//vmss is a good working recently created instance of
 //com.azure.resourcemanager.compute.models.VirtualMachineScaleSet class

 for (VirtualMachineScaleSetNetworkInterface nis : vmss.listNetworkInterfaces()) 
 {
  String privip=nis.primaryPrivateIP();//works OK
  Map<String, VirtualMachineScaleSetNicIpConfiguration> mp=nis.ipConfigurations();
  for (Object key: mp.keySet()) 
  {
   VirtualMachineScaleSetNicIpConfiguration vip=mp.get(key);
   String priva=vip.privateIpAddress();//works OK
   String pipa=vip.innerModel().publicIpAddress().ipAddress();//allways returns null
   String pss=vip.innerModel().privateIpAddress();//works OK and returns the same as priva above
   System.out.println("PublicIP="+pipa+",PrivateIP="+priva+"="+pss);//Public IP is always null
  }
 }
```

**Expected behavior**
VirtualMachineScaleSetNicIpConfiguration.innerModel().publicIpAddress().ipAddress()  should not return null

**Setup (please complete the following information):**
 - OS: The VirtualMachineScaleSet instances are Ubuntu 18, I run the Java program on Windows 10
 - IDE: Eclipse
 - Library/Libraries: azure-core-1.35.0.jar , azure-resourcemanager-compute-2.23.0.jar, azure-resourcemanager-network-2.23.0.jar,   azure-resourcemanager-*2.23.0.jar
 - Java version: 8
 - App Server/Environment: N/A
 - Frameworks: N/A

**Additional context**
I do not see any other way to get Public IP Address of the instances of VirtualMachineScaleSet . 
If there any other way? Please help!

**Comment by XiaofeiCao** [comment]
Hi @evolkovgit ,

Service backend didn't return field `ipAddress` somehow...

As a workaround(not very neat though), you can do it like this:
```java
AzureResourceManager resourceManager; // your resourcemanager instance
for (VirtualMachineScaleSetNetworkInterface nis : vmss.listNetworkInterfaces()) 
{
 Map<String, VirtualMachineScaleSetNicIpConfiguration> mp=nis.ipConfigurations();
 for (Object key: mp.keySet()) 
 {
  VirtualMachineScaleSetNicIpConfiguration vip=mp.get(key);
  String pipId=vip.innerModel().publicIpAddress().id();//get the id of the publicIpAddress
  GenericResource genericResource = resourceManager.genericResources().getById(pipId); // get publicIpAddress resource
  Map<String, Object> publicIpProperties = (Map<String, Object>) genericResource.properties();
  String pipAddress = (String) publicIpProperties.get("ipAddress"); // the public ip address
 }
}
```

**Comment by evolkovgit** [comment]
Hi @XiaofeiCao

I really appreciate your fast response. I just tried the workaround it and it worked. 
Thank you very much.
Eugene

**Comment by XiaofeiCao** [comment]
You're welcome Eugene. Since Azure Portal is using the same approach, I'll mark the issue as resolved.
