### ISSUE TITLE
Change feed processor retry mechanism on failure not working as expected

### ISSUE THREAD

**Issue by ViswanathVeerappan** [Azure/azure-sdk-for-java#33306]
We are in the process implementing a change feed processor application using the java sql api. We are looking into creating a new container from the feed/ monitored container to optimize our read requirements. The primary container was partitioned to maximize our write requirements and the new container helps us with our read requirements(data loss is not tolerated). 

We are using the azure-cosmos java sdk(version 4.38.1) and ours is a spring boot application. We have questions related to the error handling mechanism mentioned in this [documentation](https://learn.microsoft.com/en-us/azure/cosmos-db/nosql/change-feed-processor?tabs=java#error-handling-1).

Following was our initial implementation,

```
  @Bean
  public ChangeFeedProcessor changeFeedProcessor(CosmosAsyncContainer cosmosMonitoredContainer,
      CosmosAsyncContainer cosmosLeaseContainer, CosmosAsyncContainer materializedViewContainer)
      throws UnknownHostException {
    ChangeFeedProcessorOptions changeFeedProcessorOptions = new ChangeFeedProcessorOptions();
    changeFeedProcessorOptions.setStartFromBeginning(true);
    changeFeedProcessorOptions.setLeasePrefix("txn-materialized-view");

    return new ChangeFeedProcessorBuilder()
        .options(changeFeedProcessorOptions)
        .feedContainer(cosmosMonitoredContainer)
        .leaseContainer(cosmosLeaseContainer)
        .hostName(Inet4Address.getLocalHost().getHostName())
        .handleChanges((List<JsonNode> docs) -> {
          for (JsonNode document : docs) {
            materializedViewContainer.upsertItem(document).subscribe();
          }
        })
        .buildChangeFeedProcessor();
  }
```
Our starter class,

```
import com.azure.cosmos.ChangeFeedProcessor;
import javax.annotation.PostConstruct;
import javax.annotation.PreDestroy;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Component;

@Component
public class ChangeFeedProcessorRunner {
  @Autowired
  private ChangeFeedProcessor changeFeedProcessor;

  @PostConstruct
  public void start() {
    changeFeedProcessor.start()
        .doOnSuccess(a -> System.out.println("Change feed processor started successfully!!!"))
        .subscribe();
  }

  @PreDestroy
  public void stop() {
    changeFeedProcessor.stop().block();
  }
}
```
With this implementation the scheduler thread(worker) just submits the upsert operation to create/ update a record on the materialized view container on separate child threads(parallel). It does not wait for the creation or update activity to be completed.

If we were to encounter any runtime exceptions while persisting the data on the materialized view container, the retry guarantee mentioned in the documentation would not be met, since the scheduler thread is reactive or asynchronous in nature. It would exit the handle changes block as soon as the upsert tasks are all submitted. Also, updating lease container and moving on to the next batch.

_The change feed processor is resilient to user code errors. That means that if your delegate implementation has an unhandled exception (step #4), the thread processing that particular batch of changes will be stopped, and a new thread will be created. The new thread will check which was the latest point in time the lease store has for that range of partition key values, and restart from there, effectively sending the same batch of changes to the delegate. This behavior will continue until your delegate processes the changes correctly and it's the reason the change feed processor has an "at least once" guarantee._

In order to solve this problem, we tried using the following two approaches,

### Approach 1 - Using sequential or serial execution with block() instead of subscribe()

 ```
  @Bean
  public ChangeFeedProcessor changeFeedProcessor(CosmosAsyncContainer cosmosMonitoredContainer,
      CosmosAsyncContainer cosmosLeaseContainer, CosmosAsyncContainer materializedViewContainer)
      throws UnknownHostException {
    ChangeFeedProcessorOptions changeFeedProcessorOptions = new ChangeFeedProcessorOptions();
    changeFeedProcessorOptions.setStartFromBeginning(true);
    changeFeedProcessorOptions.setLeasePrefix("txn-materialized-view");

    return new ChangeFeedProcessorBuilder()
        .options(changeFeedProcessorOptions)
        .feedContainer(cosmosMonitoredContainer)
        .leaseContainer(cosmosLeaseContainer)
        .hostName(Inet4Address.getLocalHost().getHostName())
        .handleChanges((List<JsonNode> docs) -> {
          for (JsonNode document : docs) {
            materializedViewContainer.upsertItem(document).block();
          }
        })
        .buildChangeFeedProcessor();
  }
```

With this implementation the scheduler thread(worker) is blocked until the upsert operation is completed before proceeding to the next items in the list. Hence, this would adhere to the retry guarantee mentioned in the documentation.

But the downside of this approach, it is sequential or serial in terms of the execution. The application's ability to process data in parallel would be hampered leading to a degraded throughput.

### Approach 2 - Using subscribe() but holding the scheduler thread after all the upsert tasks are all submitted

 ```
  @Bean
  public ChangeFeedProcessor changeFeedProcessor(CosmosAsyncContainer cosmosMonitoredContainer,
      CosmosAsyncContainer cosmosLeaseContainer, CosmosAsyncContainer materializedViewContainer)
      throws UnknownHostException {
    ChangeFeedProcessorOptions changeFeedProcessorOptions = new ChangeFeedProcessorOptions();
    changeFeedProcessorOptions.setStartFromBeginning(true);
    changeFeedProcessorOptions.setLeasePrefix("txn-materialized-view");

    return new ChangeFeedProcessorBuilder()
        .options(changeFeedProcessorOptions)
        .feedContainer(cosmosMonitoredContainer)
        .leaseContainer(cosmosLeaseContainer)
        .hostName(Inet4Address.getLocalHost().getHostName())
        .handleChanges((List<JsonNode> docs) -> {
          AtomicInteger successfulUpsert = new AtomicInteger(); // counter to keep track of successful upserts
          AtomicBoolean hasExceptionOccurred = new AtomicBoolean(false); // flag to indicate any runtime exception
          for (JsonNode document : docs) {
            materializedViewContainer.upsertItem(document)
                .doOnNext(a -> successfulUpsert.incrementAndGet())
                .doOnError(throwable -> hasExceptionOccurred.set(true))
                .subscribe();
          } // till this the scheduler runs in an asynchronous fashion

         // holding the scheduler thread until we get to know there were no exceptions and all of them succeeded
          while (docs.size() != successfulUpsert.get()) {
            if (hasExceptionOccurred.get()) {
              // throwing an exception to make the stop the scheduler and retry the same batch on a different thread
              throw new RuntimeException(
                  "Exception occurred while persisting data in materialized view container");
            }
          }
        })
        .buildChangeFeedProcessor();
```

With this approach, we are trying to hold the scheduler(worker) thread forcefully until all the child parallel threads are completed successfully to proceed to the next batch. If we were to encounter any exceptions, we throw a runtime exception which leads to retrying the same batch on a different scheduler thread(satisfying retry guarantee). 

Also, the activity to submit the upsert operation happens in parallel. Once all the upsert operations are submitted, we are making the scheduler thread wait till the status is known.

### Questions

1.  We want to get an idea on the approach to be used to achieve the proper error handling and retry mechanism mentioned in the documentation(Approach 1 VS Approach 2).
2. We also want to get an idea on alternate mechanisms available in the library to signal the retry mechanism upon encountering a failure in the reactive or asynchronous implementation.
3. We want to get your opinion on approach 2 on our way of handling the retry guarantee and ensure we have covered all the cases(data loss cannot be tolerated in our case. We are dependent on the at least once guarantee delivery committed on the documentation).

We also came across this comment in the change feed processor [samples](https://github.com/Azure-Samples/azure-cosmos-java-sql-api-samples/blob/bc0423ce53ed5696908487809c574ba5dbd5e13d/src/main/java/com/azure/cosmos/examples/changefeed/SampleChangeFeedProcessor.java#L112) wherein a time based mechanism was employed. In our case we cannot use that as it cannot be deterministic.

**Comment by ViswanathVeerappan** [comment]
Hello @joshfree, do you have any update on this for us?

**Comment by TheovanKraay** [comment]
Sorry for the late reply. Here are some comments in response to your questions:

1. It is entirely up to you, both approaches appear to satisfy the requirement for per-batch built-in retries in response to change feed processor user code exceptions. Approach 1 is the more typical approach, as latency from serial processing is typically tolerable, and there is already parallelism by virtue of being able to deploy multiple delegates (workers) which will process in parallel across partition ranges. But approach 2 looks fine as well.

2. There are no other effective built-in mechanism for retrying a batch of changes in change feed, but perhaps you want to consider per-request retries for certain types of failure that have been introduced in SDK recently. For example, [retriable writes](https://devblogs.microsoft.com/cosmosdb/latest-nosql-java-ecosystem-updates-2023-q1-q2/#retriable-writes), [end-to-end timeout policy](https://devblogs.microsoft.com/cosmosdb/latest-nosql-java-ecosystem-updates-2023-q1-q2/#end-to-end-timeout-policy). 

3. As above, it is not the typical approach, but if you really need to minimize the replication latency to materialised view, it looks fine.

Lastly, you may want to take a look at the [Materialized views](https://learn.microsoft.com/azure/cosmos-db/nosql/materialized-views?tabs=azure-portal), now a built in feature in Cosmos DB, to see if it meets your need.
