### ISSUE TITLE
Specify  existing virtual networks for existing storage account

### ISSUE THREAD

**Issue by DenisVoloshin** [Azure/azure-sdk-for-java#33308]
**Query/Question**
I am encountering challenges in determining the feasibility of configuring network access for an existing storage account from a specified list of virtual networks, through programmatic means.
As if I were to perform it from the user interface.
![image](https://user-images.githubusercontent.com/20395483/216482265-ecad5c45-ebe2-4845-b00f-9e35cc53853c.png)

Unfortunately, the only API option discovered is withAccessFromSelectedNetworks which is only applicable as a builder step during the creation phase and is not suitable for our needs as our storage has already been established.

I would appreciate any help, reference to documentation, or code sample.

**Setup (please complete the following information if applicable):**
 - IDE: [e.g. IntelliJ]
 - Library/Libraries: [e.g. com.azure:azure-core:1.16.0 (groupId:artifactId:version)]

**Comment by XiaofeiCao** [comment]
@DenisVoloshin , I think you should be able to do it like this?
```java
storageAccount.update()
  .withAccessFromSelectedNetworks()
  .withAccessFromIpAddress("10.0.0.1")
  .withAccessFromIpAddressRange("23.20.0.0/20")
  .apply();

```

**Comment by ibrahimrabab** [comment]
Hi @DenisVoloshin 
Are you facing any issues still? If not we can go ahead and close this issue.
