### ISSUE TITLE
[BUG] Eventhub EventData overwrites Properties

### ISSUE THREAD

**Issue by the-mod** [Azure/azure-sdk-for-java#33327]
When instantiating `EventData` Class without Payload it leads to overwrite the Properties of previously created empty EventData Objects.
Because internal`AmqpAnnotatedMessage` is static in that Case.
See [Codebase](https://github.com/Azure/azure-sdk-for-java/blob/7223d7eae3dc87e65a9c1f0c9597e0c4593045e7/sdk/eventhubs/azure-messaging-eventhubs/src/main/java/com/azure/messaging/eventhubs/EventData.java#L60).

This Test fails:
```
@Test 
void test() { 
  EventData eventData1 = new EventData(); 
  eventData1.getProperties().put("myProperty", "1");   
  
  EventData eventData2 = new EventData();  
  eventData2.getProperties().put("myProperty", "2");  
  
  assertThat(eventData1.getProperties()).containsEntry("myProperty", "1");  
  assertThat(eventData2.getProperties()).containsEntry("myProperty", "2");
 }
```

I would expect the Example will pass, due to two separate `EventData` Instances.

**Setup:**
azure-messaging-eventhubs:5.15.1

**Comment by conniey** [comment]
Thank you for catching that. ><;
