### ISSUE TITLE
[QUERY] How can I know number of vCPUs present on a VM?

### ISSUE THREAD

**Issue by maheshn99** [Azure/azure-sdk-for-java#33330]
**Query/Question**
I need to know the number of vCPUs available on a particular VM.

azureResourceManager.virtualMachines().list() API returns the list of PageIterable VirtualMachines. For each item I get the correct VM Size using this: vm.innerModel().hardwareProfile().vmSize().toString() however when I try to get the vCPUs available using this: vm.innerModel().hardwareProfile().vmSizeProperties().vCpusAvailable(), it fails since vmSizeProperties() is returning null.

Please note that we have 80 plus standalone VMs (not part of VMSS) in our subscription.

***Why is this not a Bug or a feature Request?***
It looks like a bug but I am not sure.

**Setup (please complete the following information if applicable):**
 - OS: Windows 11
 - IDE: Eclipse2022-12 (4.26.0)
 - Library/Libraries: azure-core 1.35.0, com.azure.resourcemanager 2.22.0
 
 **Information Checklist**
 Kindly make sure that you have added all the following information above and checkoff the required fields otherwise we will treat the issuer as an incomplete report
- [ X] Query Added
- [X] Setup information Added

**Comment by joshfree** [comment]
@weidongxu-microsoft could you please assist @maheshn99 with their question?

**Comment by weidongxu-microsoft** [comment]
@maheshn99 

`vmSizeProperties` appears to be another feature not related to vCPU of VM.
https://learn.microsoft.com/en-us/rest/api/compute/virtual-machines/get?tabs=HTTP#hardwareprofile

> Specifies the properties for customizing the size of the virtual machine.

I think you can call
```java
azureResourceManager.computeSkus().listByResourceType(ComputeResourceType.VIRTUALMACHINES);
```
cache the result in Map (vCPU in one item of `sku.capabilities()`, so maybe `sku.name() -> int`).

Then in your list result, query `virtualMachine.size()` (or your vmSize there). Note query via String.

@XiaofeiCao as well

**Comment by maheshn99** [comment]
Thank you very much for your response. I was able to get the info I wanted. Please close this issue.
