### ISSUE TITLE
Update Redis client library for Java code sample to send refreshed token before expiry.

### ISSUE THREAD

**Issue by shpathak-msft** [Azure/azure-sdk-for-java#33345]
**Is your feature request related to a problem? Please describe.**
Azure Cache for Redis team is adding support for AAD-based authentication and would like to request Azure SDK team to help update code samples to account for design change. Here is the list to the previously created Java code samples:
https://aka.ms/redis/aad/sample-code/java-jedis
https://aka.ms/redis/aad/sample-code/java-lettuce
https://aka.ms/redis/aad/sample-code/java-redisson

**Describe the solution you'd like**
Based on recommendations from security team, we have decided to change the AAD integration on the Redis Server side to close an authenticated connection when the AAD token which was used for authentication expires. Since connection closing and recreating is expensive, client libraries can send a new AUTH command with a refreshed token before the expiry of the previous token, and Redis server will not terminate the connection if it receives a refreshed and valid AAD token.

**Describe alternatives you've considered**
Current approach is that Redis server will not care about token expiry once a connection has been authenticated with a valid AAD token.

**Additional context**
This is a follow up request for work originally done in Summer 2022.

**Information Checklist**
Kindly make sure that you have added all the following information above and checkoff the required fields otherwise we will treat the issuer as an incomplete report
- [x] Description Added
- [x] Expected solution specified

**Comment by joshfree** [comment]
@g2vinay @billwert PTAL
