### ISSUE TITLE
Integrate our SDK with Spring Boot Configuration Provider

### ISSUE THREAD

**Issue by conniey** [Azure/azure-sdk-for-java#3336]
The service team has a Spring Boot Configuration Provider that is linked to in the documentation. Can we update this to use our client?
https://github.com/Microsoft/spring-cloud-azure/tree/azure-config/spring-cloud-azure-starters/spring-cloud-starter-azure-config

You can see the link in docs by going to:
1. [docs.microsoft.com](https://docs.microsoft.com/en-us/azure/azure-app-configuration/)
1. Reference -> Java spring configuration provider

Screenshot:
![image.png](https://images.zenhubusercontent.com/5c76e6aba199ab132ebbe34b/79f894d4-20ee-49b4-b979-388b48f7043e)

Related to: #3314

**Comment by mrm9084** [comment]
@mssfang The service team has already started on this. Just waiting on a couple open issues. https://github.com/mrm9084/spring-cloud-azure/tree/switch-to-azure-sdk

**Comment by annelo-msft** [comment]
@mrm9084 - are you waiting on anything from the Azure SDK side?

**Comment by srnagar** [comment]
I don't think this will block GA. Removing the `blocking-release` label. @mssfang please confirm if this is required before GA.

**Comment by annelo-msft** [comment]
This is required before GA.  @AlexGhiondea can confirm.

**Comment by srnagar** [comment]
Should we have the spring integration done for the rest of the track 2 client libraries too before GA?
@annelo-msft

**Comment by annelo-msft** [comment]
@srnagar, my understanding is that @mrm9084 is doing this work.  It is required for their GA.

**Comment by mrm9084** [comment]
@annelo-msft I just talked with some people and there are blockers on your end. We think we will have a version out around the end of the month.

**Comment by annelo-msft** [comment]
Thanks, @mrm9084!  Can you help us understand what the blockers are?

**Comment by mrm9084** [comment]
@annelo-msft Sorry missed the word not. You are good on your end. I have a version with the SDK working, but its old code on preview.2, I am working on updating it to the latest code and to preview.3.

**Comment by annelo-msft** [comment]
Great, thanks @mrm9084!

**Comment by mrm9084** [comment]
@annelo-msft @srnagar A PR has been create for this if you are interested. https://github.com/microsoft/spring-cloud-azure/pull/573

**Comment by srnagar** [comment]
Great, thanks for the update @mrm9084

**Comment by mrm9084** [comment]
@annelo-msft @srnagar The above PR has been pulled into master.

**Comment by annelo-msft** [comment]
Awesome, thanks for the update @mrm9084 !

**Comment by mssfang** [comment]
Closing this issue due to Spring Provider is supported
