### ISSUE TITLE
[BUG] ARM no role definition data actions

### ISSUE THREAD

**Issue by bensagi** [Azure/azure-sdk-for-java#33365]
in com.azure.resourcemanager.authorization.models.Permission
I get the same list for both actions and dataActions:

![image](https://user-images.githubusercontent.com/73578662/217209507-d3be04a4-d06c-4d87-ae6c-c5ccc27d5cc9.png)

data actions should return the list from:
com.azure.resourcemanager.authorization.fluent.models.PermissionInner
dataActions
![image](https://user-images.githubusercontent.com/73578662/217209791-174b857b-6a42-495c-847f-be4d8c023ba0.png)

**Comment by joshfree** [comment]
@weidongxu-microsoft could you please take a look?

**Comment by weidongxu-microsoft** [comment]
Thanks @bensagi
We should be able to fix it in next release (2.24.0 this month)

@XiaofeiCao Could you help?

**Comment by XiaofeiCao** [comment]
Sure, this seems to be a bug in implementation.

**Comment by weidongxu-microsoft** [comment]
2.24.0 fixed it.
