### ISSUE TITLE
Refactor Search Sync Stack Helper methods + Add Sync Stack in SearchIndexingBufferedSender

### ISSUE THREAD

**Issue by g2vinay** [Azure/azure-sdk-for-java#33370]
1. Refactor static helper methods in Async clients of azure-search-documents to Utility methods.
2. Add sync stack to SearchIndexingBufferedSender

**Comment by pallavit** [comment]
@alzimmermsft , @jairmyree Is this something you are planning to do?

**Comment by alzimmermsft** [comment]
Yes, I have a PR open for this but there are a few changes that may need to go into `azure-core` before it can be merged:

https://github.com/Azure/azure-sdk-for-java/pull/36398
