### ISSUE TITLE
[FEATURE REQ] Add cost details report support

### ISSUE THREAD

**Issue by ejf-ibm** [Azure/azure-sdk-for-java#33417]
The cost management SDK currently does not support https://learn.microsoft.com/en-us/rest/api/cost-management/generate-cost-details-report/get-operation-results. It would be great to have this in the SDK. Thanks!

**Comment by joshfree** [comment]
@weidongxu-microsoft could you please follow up with @ejf-ibm on `Cost Management`?

**Comment by weidongxu-microsoft** [comment]
Thanks @ejf-ibm 

That API is on https://github.com/Azure/azure-rest-api-specs/tree/main/specification/cost-management/resource-manager#tag-package-2022-10

We will check whether that api-version is alive (we had seen case that latest is not alive in the past). If it is alive we will schedule a release on 2022-10-01 soon.

**Comment by weidongxu-microsoft** [comment]
See https://github.com/Azure/azure-sdk-for-java/commit/90cb09598ab3a8bb0a3836a2b9f63a92ab999b8f

Note that the cost report seems have some requirement on subscription offer (which my test subscription does not meet).

**Comment by weidongxu-microsoft** [comment]
https://search.maven.org/artifact/com.azure.resourcemanager/azure-resourcemanager-costmanagement/1.0.0-beta.5/jar
