### ISSUE TITLE
[FEATURE REQ]SDK Enhancements

### ISSUE THREAD

**Issue by xinlian12** [Azure/azure-sdk-for-java#33425]
[CosmosSDK-enhancements_MSFT](https://microsofteur-my.sharepoint.com/:w:/g/personal/fabianm_microsoft_com/EYGHutAqlKJMneXJkHxyuyUB4eViZyRGsz4EdgL0hp5grw?e=h0jRcN&ovuser=72f988bf-86f1-41af-91ab-2d7cd011db47%2Cxinlian%40microsoft.com&clickparams=eyJBcHBOYW1lIjoiVGVhbXMtRGVza3RvcCIsIkFwcFZlcnNpb24iOiIyOC8yMzAxMTUwMDkwNyIsIkhhc0ZlZGVyYXRlZFVzZXIiOmZhbHNlfQ%3D%3D)

**Comment by kushagraThapar** [comment]
These are done.
