### ISSUE TITLE
Move AzureConfiguration into common library

### ISSUE THREAD

**Issue by conniey** [Azure/azure-sdk-for-java#3343]
There is a implementation.Utils class somewhere that we can move the logic for getting OS information and the correct UserAgent string for.

- [ ] See if the UserAgentPolicy can get the string by default. Right now the default user agent in that policy is "AutoRest.Java"

**Comment by JonathanGiles** [comment]
@conniey Were you mentioning a specific AzureConfiguration class that exists / existed, or that one should exist? If you meant the latter, we should close this issue as a duplicate of #3476.

**Comment by conniey** [comment]
Oh. This has been fixed already.
