### ISSUE TITLE
Release Azure.Core Library Preview for Java

### ISSUE THREAD

**Issue by conniey** [Azure/azure-sdk-for-java#3344]
- [x] Instrumentation
    - [x] Distributed tracing - #3382
    - [x] Centralised logging - #3326 
- [x] Centralised configuration - #3476
- [x] Authentication / identity - #3605, #3505
- [x] Rename Azure.Common to Azure.Core.
- [x] Clean up
    - [x] Exceptions - #3591 
    - [x] RestProxy - #3594 
    - [x] HttpHeaders - #3607 
    - [x] HttpPipeline - #3608 
    - [x] ContextData - #3609 
    - [x] Implementation leaks - #3610, #3637, #3638 
- [x] Quality
    - [x] Fully JavaDoc'd
    - [x] SpotBugs clean
    - [x] CheckStyle clean

**Comment by joshfree** [comment]
Closing issue given the last remaining associated issue (JavaDoc cleanup) has been addressed
