### ISSUE TITLE
How to handle large amount of data in increments

### ISSUE THREAD

**Issue by roadruuner** [Azure/azure-sdk-for-java#33468]
I was told to post my question in this github.

I am using Spark Structured Streaming with asuze-cosmos-spark_3-1_2-2 % "4.16.0"
I need to cap how much data I can read. Tried setting the following: 
spark.cosmos.changeFeed.itemCountPerTriggerHint = 10 
spark.cosmos.read.maxItem = 10
spark.cosmos.changeFeed.startFrom = "Beginning" 
spark.cosmos.changeFeed.mode = "Incremental"
Using 
val changeFeedDF = spark.readStream .schema(customSchema) .format("cosmos.oltp.changeFeed") .options(readConfig) .load

_This is their response.
  _Hi, itemCountPerTriggerHint will allow you to modify the max. memory/resource consumption per micro batch. it is only a hint because change feed in Cosmos DB will always include at least all documents of a single atomic transaction (all sharing the same LSN - log sequence number, because they were modified in the same atomic transaction). So, you will always get at least the documents for a single atomic transaction per physical partition. But from a memory footprint/resource consumption perspective that should be more than sufficient - because the number of document updates in a transaction is also capped (worst case a single bulk/batch might update around 1-5 thousand documents if they are really very small)
The right repository for the Cosmos Spark Connector for Spark 3.* is this repo. https://github.com/Azure/azure-sdk-for-java
Config details can be located here: https://github.com/Azure/azure-sdk-for-java/blob/main/sdk/cosmos/azure-cosmos-spark_3_2-12/docs/configuration-reference.md__

In my case I have 2.5 million records of history to retrieve and I only have a two hour window per day to work with. So can I stop my job at the end of the window and based on the last saved checkpoint it will continue where it left off next time I run it.

**Comment by FabianMeiswinkel** [comment]
Yes - you can use the Spark Streaming checkpointLocation - once provided Spark streaming will update the offset stored in this location with each MicroBatch. When you start processing after a "break" processing would recontinue at this offset. If the concern is that during business hours change feed processing should not use too many RUs, you could also use client throughput control and specify that the change feed processing job should take no more than x percent of RUs - or you could point the change feed processing job ata remote region (in case you use single master with at least one fail-over region).

**Comment by roadruuner** [comment]
Thanks for the response.
Regarding take no more than x percent of RUs
are these the settings.
"spark.cosmos.throughputControl.enabled" -> "true",
    "spark.cosmos.throughputControl.targetThroughputThreshold" -> "0.95", 

but looks like I have to add these; they are very restrictive on creating other resources.    
    "spark.cosmos.throughputControl.globalControl.database" -> "database-v4", 
    "spark.cosmos.throughputControl.globalControl.container" -> "ThroughputControl"
    "spark.cosmos.throughputControl.name" -> "SourceContainerThroughputControl",

**Comment by FabianMeiswinkel** [comment]
Correct - at least anther container is needed (could be under same account and database) to be used for the metadata the client-throughput control feature will persist.
