### ISSUE TITLE
[FEATURE REQ] Provide native hints for azure-storage-queue

### ISSUE THREAD

**Issue by cschaible** [Azure/azure-sdk-for-java#33509]
**Is your feature request related to a problem? Please describe.**
Hints for GraalVM native compilation of [azure-storage-blob](https://github.com/Azure/azure-sdk-for-java/tree/main/sdk/storage/azure-storage-blob/src/main/resources/META-INF/native-image/com.azure/azure-storage-blob) are already provided.

For [azure-storage-queue](https://github.com/Azure/azure-sdk-for-java/tree/main/sdk/storage/azure-storage-queue/src/main/resources) though, hints are missing. 

**Describe the solution you'd like**
It would be great if the hints/json files could be provided.

The released configuration of azure-storage-blob does neither work automatically on my machine (can be solved by copying the json files, though). I would appreciate if you could check it as well. The following [bug](https://github.com/Azure/azure-sdk-for-java/issues/33328) might be related (i had the same issue).

**Additional context**
Looking at the [reflect-config.json](https://github.com/Azure/azure-sdk-for-java/blob/main/sdk/storage/azure-storage-blob/src/main/resources/META-INF/native-image/com.azure/azure-storage-blob/reflect-config.json) of azure-storage-blob, I'm wondering whether it was created with the tracing-agent or manually?

**Information Checklist**
Kindly make sure that you have added all the following information above and checkoff the required fields otherwise we will treat the issuer as an incomplete report
- [x] Description Added
- [x] Expected solution specified

**Comment by alzimmermsft** [comment]
@srnagar FYI

**Comment by srnagar** [comment]
@cschaible thank you for reporting this issue. We are adding native hints to all Azure SDK for Java libraries in the upcoming releases. `azure-storage-queue` is also in the pipeline for native support. I'll update this issue when we have a release with native hints for this library.

Regarding the logback issue, it's not a direct dependency from the Azure SDK libraries but given how popular this logging library is in the Java ecosystem, we'll include native hints for this in `azure-core` in the next release.
