### ISSUE TITLE
[BUG] NPE when calling listAvailablePrivateIPAddresses with limited AD permissions 

### ISSUE THREAD

**Issue by pradeepg-alkira** [Azure/azure-sdk-for-java#33552]
**Describe the bug**
Seeing NPE while calling listAvailablePrivateIPAddresses with limited permissions 

***Exception or Stack Trace***

```
java.lang.NullPointerException: null
at java.base/java.util.TreeSet.addAll(TreeSet.java:300)
at com.azure.resourcemanager.network.implementation.SubnetImpl.listAvailablePrivateIPAddresses(SubnetImpl.java:275)

```

**To Reproduce**
- Create vnet with some subnet 
- Try to call invoke listAvailablePrivateIPAddresses using credentials with below permissions

                   ```
                    "Microsoft.Network/virtualNetworks/read",
                    "Microsoft.Network/virtualNetworks/write",
                    "Microsoft.Network/virtualNetworks/peer/action",
                    "Microsoft.Network/virtualNetworks/join/action",
                    "Microsoft.Network/virtualNetworks/virtualNetworkPeerings/read",
                    "Microsoft.Network/virtualNetworks/virtualNetworkPeerings/write",
                    "Microsoft.Network/virtualNetworks/virtualNetworkPeerings/delete",
                    "Microsoft.Network/virtualNetworks/subnets/read",
                    "Microsoft.Network/virtualNetworks/subnets/write",
                    "Microsoft.Network/locations/serviceTags/read",
                    "Microsoft.Network/publicIPAddresses/read",
                    "Microsoft.Network/routeTables/read",
                    "Microsoft.Network/routeTables/write",
                    "Microsoft.Network/routeTables/routes/read",
                    "Microsoft.Network/routeTables/routes/write",
                    "Microsoft.Network/routeTables/routes/delete",
                    "Microsoft.Resources/subscriptions/resourceGroups/read",
                    "Microsoft.Network/expressRouteCircuits/read",
                    "Microsoft.Network/expressRouteCircuits/authorizations/read",
                    "Microsoft.Network/expressRouteCircuits/peerings/read",
                    "Microsoft.Network/expressRouteCircuits/peerings/connections/read",
                    "Microsoft.Network/expressRouteCircuits/peerings/peerConnections/read"
```

**Expected behavior**
NPE must be handled and throw the appropriate exception.

**Comment by alzimmermsft** [comment]
Thanks for reporting this @pradeepg-alkira, @weidongxu-microsoft could you get a follow up for this. It appears there needs to be a guard for no available IP addresses on the line mentioned in the exception.

**Comment by weidongxu-microsoft** [comment]
@XiaofeiCao Could you check it?

We might not able to throw exception, if underlying network does not return 4xx upon this case.

I remember some will just return an empty list or empty object. Let's see how backend behave first.


@pradeepg-alkira 

If you have the logging available, please also paste it (with redact if necessary).
https://github.com/Azure/azure-sdk-for-java/tree/main/sdk/resourcemanager#enabling-logging

**Comment by XiaofeiCao** [comment]
If no permission, then response succeeds with code 200 and an empty list body, which get deserialized to an empty Object instead of null(strange):
```json
{
  "value" : [ ]
}
```
as opposed to an authorized request:
```json
{
  "available" : false,
  "availableIPAddresses" : [ "10.17.0.4", "10.17.0.5", "10.17.0.6", "10.17.0.7", "10.17.0.8" ],
  "isPlatformReserved" : true
}
```

In this case, perhaps we should add two checks:
```java
if (ResourceManagerUtils.toPrimitiveBoolean(result.available()) // add availability check
    // add NPE check
    && result.availableIpAddresses() != null) {
    ipAddresses.addAll();
}
```

**Comment by weidongxu-microsoft** [comment]
@XiaofeiCao 
Sure, we should do that. (be careful about the "available", we'd like to be sure about that)

The backend response seems not correct (it looks like a response of List).

**Comment by XiaofeiCao** [comment]
Checked our implementation. `available` is for the ipaddress to be examined, in our case is the first part of CIDR which is always unavailable. (which is not what I thought it meant...)

We should ignore this property.

**Comment by XiaofeiCao** [comment]
This should be fixed in our latest SDK. 
https://search.maven.org/artifact/com.azure.resourcemanager/azure-resourcemanager/2.25.0/jar
