### ISSUE TITLE
[BUG] `azure-core-http-jdk-httpclient` doesn't support Java 11

### ISSUE THREAD

**Issue by dennis-benzinger-hybris** [Azure/azure-sdk-for-java#33575]
`azure-core-http-jdk-httpclient` doesn't support Java 11:
https://github.com/Azure/azure-sdk-for-java/blob/main/sdk/core/azure-core-http-jdk-httpclient/src/main/java/com/azure/core/http/jdk/httpclient/JdkHttpClient.java#L46-L49
even though the documentation says it works with Java 11:
https://github.com/Azure/azure-sdk-for-java/blob/main/sdk/core/azure-core-http-jdk-httpclient/README.md?plain=1#L10

If possible please support Java 11. Otherwise at least fix the documentation.

**Comment by alzimmermsft** [comment]
Thanks for filing this issue @dennis-benzinger-hybris. This is correct that the JDK HttpClient doesn't support Java 11 and that check and exception should be updated to Java 12.

For clarification into why Java 11 isn't supported even though `HttpClient` exists in Java 11. The implementation of the `HttpClient` in Java 11 had a handful of restricted headers where if those headers were set externally to the `HttpClient` when sending a request the `HttpClient` would throw an exception, for the SDKs the `Date` header is the primary issue. The `Date` header is set before making the request as the `Date` of the request is important for some authorization mechanisms such as Storage Shared Key where the `Date` needs to be used to calculate the `Authorization` header value.

This was changed in Java 12 to have a system property where the restricted header list could be overridden, which we do later in our `JdkHttpClient` code.

**Comment by dennis-benzinger-hybris** [comment]
Not what I hoped for but thanks for the explanation.

**Comment by alzimmermsft** [comment]
Closing as there have been documentation updates for this and the library will throw when a version of JDK 11 or lower is used.
