### ISSUE TITLE
Azure KeyVault 1.2.1 Maven dependencies issue, missing artifacts 

### ISSUE THREAD

**Issue by hhanquez** [Azure/azure-sdk-for-java#3360]
Hi,

Dependencies are missing for azure-keyvault version 1.2.1
At least, azure-keyvault-parent and azure-keyvault-complete are missing in repository https://repo.spring.io/libs-release

		<dependency>
			<groupId>com.microsoft.azure</groupId>
			<artifactId>azure-keyvault</artifactId>
			<version>1.2.1</version>
		</dependency>
		<dependency>
			<groupId>com.microsoft.azure</groupId>
			<artifactId>azure-keyvault-cryptography</artifactId>
			<version>1.2.1</version>
		</dependency>
		<dependency>
			<groupId>com.microsoft.azure</groupId>
			<artifactId>azure-keyvault-extensions</artifactId>
			<version>1.2.1</version>
		</dependency>
		<dependency>
			<groupId>com.microsoft.azure</groupId>
			<artifactId>azure-keyvault-core</artifactId>
			<version>1.2.1</version>
		</dependency>
		<dependency>
			<groupId>com.microsoft.azure</groupId>
			<artifactId>azure-keyvault-webkey</artifactId>
			<version>1.2.1</version>
		</dependency>

Best regards,

**Comment by praries880** [comment]
Thank you for opening this issue! We are routing it to the appropriate team for follow up.

**Comment by g2vinay** [comment]
@hhanquez 
We don't ship azure-keyvault-parent anymore for KV Track 1 SDKs.
The latest release version is 1.2.4, you can find them in the maven repo.
@vcolin7 can you confirm the release of azure-keyvault-complete 1.2.4 ?

Also, 
We've shipped next gen KV SDKs, the v4.x azure-security-keyvault-* libraries are the latest supported SDK libraries for KeyVault. We do recommend upgrading to this latest stable, supported release. Packages and more information can be found here:

https://github.com/Azure/azure-sdk-for-java/tree/master/sdk/keyvault/azure-security-keyvault-secrets
https://github.com/Azure/azure-sdk-for-java/blob/master/sdk/keyvault/azure-security-keyvault-keys
https://github.com/Azure/azure-sdk-for-java/tree/master/sdk/keyvault/azure-security-keyvault-certificates

**Comment by vcolin7** [comment]
We released [azure-keyvault-complete 1.2.4](https://search.maven.org/artifact/com.microsoft.azure/azure-keyvault-complete/1.2.4/pom) last week :)
