### ISSUE TITLE
[BUG] ServiceBusAdministrationClient - getSubscriptionExists() throws exception

### ISSUE THREAD

**Issue by florianmack** [Azure/azure-sdk-for-java#33609]
**Describe the bug**
If the function getSubscriptionExists() of the class ServiceBusAdministrationClient is called and the subscription does not exists a ServiceBusManagementErrorException is thrown

***Exception or Stack Trace***
com.azure.messaging.servicebus.administration.implementation.models.ServiceBusManagementErrorException: Status code 404, "<Error><Code>404</Code><Detail>Entity 'poi-retail-developer:Topic:azure-servicebus-test|SUBSCRIPTION_TEST_INVALID' was not found. To know more visit https://aka.ms/sbResourceMgrExceptions.  TrackingId:62414cf5-7e19-484c-8ec1-a8fdc673daa4_B48, SystemTracker:NoSystemTracker, Timestamp:2023-02-20T07:39:01</Detail></Error>"

**To Reproduce**
Just call the function für an non existent subscription on azure servicebus

***Code Snippet***
package com.porscheinformatik.azure;

import com.azure.messaging.servicebus.administration.ServiceBusAdministrationClient;
import com.azure.messaging.servicebus.administration.ServiceBusAdministrationClientBuilder;

public class Main
{
    public static final String CONNECTION_STRING = "Endpoint=sb://poi-retail-developer.servicebus.windows.net/;" +
        "SharedAccessKeyName=MANAGEMENT;SharedAccessKey=XXXXX;

    public static void main(String[] args)
    {
        try
        {
            final ServiceBusAdministrationClient adminClient =
                new ServiceBusAdministrationClientBuilder()
                    .connectionString(CONNECTION_STRING)
                    .buildClient();

            boolean result = adminClient.getSubscriptionExists("azure-servicebus-test", "SUBSCRIPTION_TEST");
            System.out.printf("Subscription exists: %s%n", result);

            result = adminClient.getSubscriptionExists("azure-servicebus-test", "SUBSCRIPTION_TEST_INVALID");
            System.out.printf("Subscription exists: %s%n", result);
        }
        catch (Exception ex)
        {
            System.out.printf("Error while calling getSubscriptionExists(): %s%n", ex);
        }
    }
}

**Expected behavior**
The function should return false instead of throwing an exception

**Screenshots**
![image](https://user-images.githubusercontent.com/33804957/220045446-4eaa50ea-d2ec-4570-9623-f34a21b01b77.png)

**Setup (please complete the following information):**
 - OS: WINDOWS 10
 - IDE: IntelliJ
 - Library/Libraries: azure-messaging-servicebus:7.13.1
 - Java version: 17
 - App Server/Environment: Java consol Application
 - Frameworks: Plain Java

**Information Checklist**
Kindly make sure that you have added all the following information above and checkoff the required fields otherwise we will treat the issuer as an incomplete report
- [ x ] Bug Description Added
- [ x ] Repro Steps Added
- [ x ] Setup information Added

**Comment by ki1729** [comment]
@florianmack Thank you for reporting this bug! This will be fixed in the next release. I'll post updates herewhen it is done

**Comment by phillipmarkwick** [comment]
Hello. Has this been fixed? Still happening in com.azure:azure-messaging-servicebus:7.13.3

**Comment by andrelemos** [comment]
Hey guys, do you have any predictions for this fix?

**Comment by florianmack** [comment]
No it is still not fixed

**Comment by andrelemos** [comment]
@joshfree  Hey guys, do you have any predictions for this fix?

**Comment by Kitsula** [comment]
I've been waiting a long time for the fix.

**Comment by joshfree** [comment]
Adding this to the `Java SDKs Azure AMQP & Messaging` github project under `Customer Asks` to discuss in standup

**Comment by conniey** [comment]
I will take a look at this. :)

**Comment by anuchandy** [comment]
While waiting for the SDK change, this seems to be something the application can handle by catching "com.azure.core.exception.HttpResponseException" and looking for a 404 status code.

**Comment by anuchandy** [comment]
Hi @Kitsula, I meant to check the 404 for `subscriptionExists` call while we look into this, e.g.,

```java
    public static void main(String[] args) {
        ServiceBusAdministrationClient client = new ServiceBusAdministrationClientBuilder()
            .connectionString(System.getenv("CON_STR"))
            .buildClient();

        final String topicName = "topic1";
        final String subscriptionName = "sub1";
        if (!getSubscriptionExists(client, topicName, subscriptionName)) {
            client.createSubscription(topicName, subscriptionName);
        }
    }

    static boolean getSubscriptionExists(ServiceBusAdministrationClient client, String topicName, 
        String subscriptionName) {
        try {
            return client.getSubscriptionExists(topicName, subscriptionName);
        } catch (HttpResponseException hre) {
            if (hre.getResponse().getStatusCode() == 404) {
                return false;
            }
            throw hre;
        }
    }
```

Btw, IMHO, I wouldn't worry about try-catch - considering this is likely not a hot-path, the network call dominates any other cost, any other error status is expected to raise exception.
