### ISSUE TITLE
WebSiteBaseImpl.tags() throws NPE

### ISSUE THREAD

**Issue by ychulovskyy** [Azure/azure-sdk-for-java#33617]
Looks like WebSiteBaseImpl
```
    public Map<String, String> tags() {
        return Collections.unmodifiableMap(innerModel().tags());
    }
```
can throw NullPointerException when innerModel().tags() is null (e.g. there is no tags).

Suggestion: handle null in the same way as it is in ResourceGroupImpl
```
    public Map<String, String> tags() {
        Map<String, String> tags = this.innerModel().tags();
        if (tags == null) {
            tags = new HashMap<>();
        }
        return Collections.unmodifiableMap(tags);
    }
```

**Comment by alzimmermsft** [comment]
Thanks for reporting this @ychulovskyy, @weidongxu-microsoft could you get a follow up for this

**Comment by weidongxu-microsoft** [comment]
@ychulovskyy

Thank you for pointing it out. Will fix soon.
