### ISSUE TITLE
mgmt autocent, fix specs mapping and remove deprecated packages

### ISSUE THREAD

**Issue by XiaofeiCao** [Azure/azure-sdk-for-java#33621]
deprecated packages to be removed:
- [x] azure-resourcemanager-batchai
- [x] azure-resourcemanager-machinelearningservices

**Comment by weidongxu-microsoft** [comment]
loadtestservice as well.

**Comment by XiaofeiCao** [comment]
Deprecated libs fixed in https://github.com/Azure/azure-sdk-for-java/pull/33753

No lib released for containerservicefleet, mapping fix is no need for now.
