### ISSUE TITLE
[FEATURE REQ] Support to Jakarta JMS API 3

### ISSUE THREAD

**Issue by ceremo** [Azure/azure-sdk-for-java#33633]
We want to use the Azure SDK (`spring-cloud-azure-starter-servicebus-jms`) in Spring Boot applications using 3.x versions, and is required to use the Jakarta JMS API in version 3.x. Is there any advance or is planned to support this in short time?

The [Qpid](https://qpid.apache.org/components/jms/index.html) library already supports it.

**Comment by moarychan** [comment]
Hi @ceremo , thanks for using this library!

We have released version [5.0](https://mvnrepository.com/artifact/com.azure.spring/spring-cloud-azure-starter-servicebus-jms/5.0.0) for Jakarta JMS support, please try this version, any questions are welcome!
