### ISSUE TITLE
[BUG] Got 400 error when using DataLakeFileClient in multi-thread

### ISSUE THREAD

**Issue by wstest123** [Azure/azure-sdk-for-java#33632]
**Describe the bug**
When using the following code to upload data to ADLS Gen2 with multi-thread, we always meet  the Status code 400 error.

DataLakeFileClient fileClient = getDataLakeFileClient(getBlockFullPath());
 fileClient.upload(BinaryData.fromString(stringBuilder.toString()), false);

***Exception or Stack Trace***
Status code 400, "{"error":{"code":"InvalidHeaderValue","message":"The value for one of the HTTP headers is not in the correct format.\nRequestId:4ef7b533-701f-0070-603b-40c435000000\nTime:2023-02-14T06:14:40.0664465Z","detail":{"HeaderName":"Content-Length", "HeaderValue":"0"}}}"

**To Reproduce**
Run the following code with multi-thread.

***Code Snippet***
        private void uploadStringData(StringBuilder stringBuilder) {

                for (int i = 1; i < 4; i++) {
                    try {
                        String blobFullPath = getBlockFullPath();
                        DataLakeFileClient fileClient = getDataLakeFileClient(blobFullPath);
                        fileClient.upload(BinaryData.fromString(stringBuilder.toString()), false);
                        LOG.info(" ++++++ Data have uploaded to, in " + i + " times : " + blobFullPath);
                        break;
                    } catch (Exception ex) {
                        LOG.info(" ------ Upload Data get error : " + fileName);
                        LOG.info(ex.getLocalizedMessage());
                        ex.printStackTrace();
                    }
                }
        }

**Expected behavior**
Hope to get the best practice to upload data in multi-threads. 

**Screenshots**

**Setup (please complete the following information):**
        <dependency>
            <groupId>com.azure</groupId>
            <artifactId>azure-storage-file-datalake</artifactId>
            <version>12.13.3</version>
        </dependency>

If you suspect a dependency version mismatch (e.g. you see `NoClassDefFoundError`, `NoSuchMethodError` or similar), please check out [Troubleshoot dependency version conflict article](https://aka.ms/azsdk/java/dependency/troubleshoot) first. If it doesn't provide solution for the problem, please provide:
- verbose dependency tree (`mvn dependency:tree -Dverbose`)
- exception message, full stack trace, and any available logs

**Additional context**

**Comment by alzimmermsft** [comment]
Thanks for filing this @wstest123, @ibrahimrabab could you follow up on this

**Comment by ibrahimrabab** [comment]
Hi @wstest123 
Thanks for reaching out! When I try running your code snippet, I get the following error:
```
trying to upload to: 350df8b72350df8b7f85026409e81c67addbe4e02801
 ++++++ Data have uploaded to, in 1 times : 350df8b72350df8b7f85026409e81c67addbe4e02801
trying to upload to: 350df8b72350df8b7f85026409e81c67addbe4e02801
 ------ Upload Data get error : 350df8b72350df8b7f85026409e81c67addbe4e02801
Status code 409, "{"error":{"code":"PathAlreadyExists","message":"The specified path already exists.\nRequestId:f1c7c8a8-901f-006b-3a2b-475d36000000\nTime:2023-02-23T02:09:32.6473298Z"}}"
com.azure.storage.file.datalake.models.DataLakeStorageException: Status code 409, "{"error":{"code":"PathAlreadyExists","message":"The specified path already exists.\nRequestId:f1c7c8a8-901f-006b-3a2b-475d36000000\nTime:2023-02-23T02:09:32.6473298Z"}}"
```
This makes sense because we specified overwrite as false, thus hitting the 409. In your case though, you are hitting a status code of 400, which is a different error.

I have a couple questions,
1. Are you uploading to a new file every time, or calling upload(BinaryData, boolean) on the existing file client? 

2. Can you confirm if your data is in proper format? 

3. Also, can you try passing "true" for the overwrite value and see what happens?

**Comment by wstest123** [comment]
@ibrahimrabab Thanks so much for your help! Could you please help advice if the DataLakeFileClient is **thread-safe or not**?
Should we use **DataLakeFileAsyncClient**  to replace the DataLakeFileClient when using it in multi-thread? Thanks!

Attached the answer for your questions:
Are you uploading to a new file every time, or calling upload(BinaryData, boolean) on the existing file client?
uploading to a new file
Can you confirm if your data is in proper format?
Yes, because sometimes it is able to upload successfully. Only when I use multi-thread, it caused the error.
Also, can you try passing "true" for the overwrite value and see what happens?

**Comment by ibrahimrabab** [comment]
@wstest123 Yes DataLakeFileClient is thread safe, especially if you follow the guidelines on here:
https://azure.github.io/azure-sdk/java_introduction.html#java-service-client-immutable

I didn't see the response for the last question. Were you able to test by passing "true" for the overwrite value?

Can you please provide a fully reproducible sample (such as a single file that contains a main method where you are calling the code snippet you pasted above), including the implementation details of the method `getBlockFullPath()` and what `fileName` you are using in the catch clause? I want to reproduce your code fully to really understand where things might be going wrong. 

Thanks!
