### ISSUE TITLE
[FEATURE REQ] mgmt, convenience API for keyvault HSM

### ISSUE THREAD

**Issue by weidongxu-microsoft** [Azure/azure-sdk-for-java#33659]
Use case:

- add List/Get API for HSM
- (optional) integrate key retrieval <-- need some investigate whether this can be done by same [azure-security-keyvault-keys](https://github.com/Azure/azure-sdk-for-java/tree/main/sdk/keyvault/azure-security-keyvault-keys)

Note; HSM cost is high, make sure test cases delete the resource.

**Comment by XiaofeiCao** [comment]
Got it. I saw a similar `hsmUri` on `ManagedHsmInner` which resembles `vaultUri` on `VaultInner`. Will check whether that allows for key retrieval.

**Comment by weidongxu-microsoft** [comment]
Note that HSM cost is high.

**Comment by XiaofeiCao** [comment]
@weidongxu-microsoft HSM introduced a new scope `https://managedhsm.azure.net/` which is not included in our `AzureEnvironment`.

Their hsmUri looks like: `https://hsm61569050.managedhsm.azure.net/keys/my-key/create?api-version=7.2`, causing 
>401, "{"error":{"code":"Unauthorized","message":"Found token with aud=https://management.core.windows.net/, but expected aud=https://managedhsm.azure.net

Guess we need to add a `managedHsmDnsSuffix` in `AzureEnvironment`?

**Comment by weidongxu-microsoft** [comment]
Sure, if we need it, we can add it.

**Comment by XiaofeiCao** [comment]
From their [product availability](https://azure.microsoft.com/en-us/explore/global-infrastructure/products-by-region/?products=key-vault&regions=non-regional,usgov-non-regional,us-dod-central,us-dod-east,usgov-arizona,usgov-texas,usgov-virginia,canada-central,canada-east,china-non-regional,china-east,china-east-2,china-east-3,china-north,china-north-2,china-north-3,germany-north,germany-west-central,us-central,us-east,us-east-2,us-north-central,us-south-central,us-west-central,us-west,us-west-2,us-west-3&rar=true):


[usgov](https://management.chinacloudapi.cn/metadata/endpoints?api-version=2023-01-01) is GAed.


[China cloud](https://management.chinacloudapi.cn/metadata/endpoints?api-version=2023-01-01) planned to GA in H2 2023:


Can't connect to Germany, but seems not available in product availability, so we likely not going to add it:
https://management.microsoftazure.de/metadata/endpoints

**Comment by weidongxu-microsoft** [comment]
I think the whole Germany cloud is to be retired.

**Comment by XiaofeiCao** [comment]
Verified example of get HSM instance, key operations including create, get and list:

```java
// get managed HSM instance
ManagedHsmInner hsmInner = keyVaultManager.serviceClient().getManagedHsms().getByResourceGroup("my-resourcegroup", "my-hsm");

// build key client
KeyAsyncClient keyAsyncClient = new KeyClientBuilder()
    .pipeline(keyVaultManager.httpPipeline())
    .vaultUrl(hsmInner.properties().hsmUri())
    .serviceVersion(KeyServiceVersion.V7_2)
    .buildAsyncClient();

// create key
keyAsyncClient.createKey(
    new CreateRsaKeyOptions("my-key")
        .setKeySize(4096)
        .setKeyOperations(
            KeyOperation.values().stream().filter(keyOperation ->
                keyOperation != KeyOperation.IMPORT)
                .toArray(KeyOperation[]::new)));

// get key
KeyVaultKey key = keyAsyncClient.getKey("my-key").block();

// list keys
PagedFlux<KeyProperties> keys = keyAsyncClient.listPropertiesOfKeys();
```

To manipulate keys(create, list, get, etc), one has to have corresponding [permissions](https://learn.microsoft.com/en-us/azure/key-vault/managed-hsm/built-in-roles#permitted-operations), or some local RBAC [built-in roles](https://learn.microsoft.com/en-us/azure/key-vault/managed-hsm/built-in-roles#built-in-roles) like `Managed HSM Crypto User`.

Role assignment using Azure CLI:
https://learn.microsoft.com/en-us/azure/key-vault/managed-hsm/role-management#create-a-new-role-assignment

**Comment by weidongxu-microsoft** [comment]
> From their [product availability](https://azure.microsoft.com/en-us/explore/global-infrastructure/products-by-region/?products=key-vault&regions=non-regional,usgov-non-regional,us-dod-central,us-dod-east,usgov-arizona,usgov-texas,usgov-virginia,canada-central,canada-east,china-non-regional,china-east,china-east-2,china-east-3,china-north,china-north-2,china-north-3,germany-north,germany-west-central,us-central,us-east,us-east-2,us-north-central,us-south-central,us-west-central,us-west,us-west-2,us-west-3&rar=true):
> 
> [usgov](https://management.chinacloudapi.cn/metadata/endpoints?api-version=2023-01-01) is GAed.
> 
> [China cloud](https://management.chinacloudapi.cn/metadata/endpoints?api-version=2023-01-01) planned to GA in H2 2023:
> 
> Can't connect to Germany, but seems not available in product availability, so we likely not going to add it: https://management.microsoftazure.de/metadata/endpoints

Alternative: see if we can use keys.json and secrets.json, see if we can use them to retrieve the keys (instead of data-plane lib).
https://github.com/Azure/azure-rest-api-specs/tree/main/specification/keyvault/resource-manager#tag-package-2022-11

**Comment by XiaofeiCao** [comment]
Seems like their management swagger is for vaults keys only. ManagedHsm keys are not supported.
>  Status code 404, "{"error":{"code":"ParentResourceNotFound","message":"Can not perform requested operation on nested resource. Parent resource 'mhsm00937849' not found."}}"

They are under different resources:

create request url for keys from keys.json(it's under Microsoft.KeyVault/vaults): 
> https://management.azure.com/subscriptions/REDACTED/resourceGroups/javacsmrg55815/providers/Microsoft.KeyVault/vaults/mhsm00937849/keys/mykey67639a8?api-version=2021-10-01

create request for managedHsm(Microsoft.KeyVault/managedHSMs): 
> https://management.azure.com/subscriptions/0b1f6471-1bf0-4dda-aec3-cb9272f09590/resourceGroups/javacsmrg55815/providers/Microsoft.KeyVault/managedHSMs/mhsm00937849?api-version=2021-10-01

And management plane swagger doesn't support necessary operations like delete and import, even for vaults. Guess we'll have to stick with data-plane SDK for now.

**Comment by weidongxu-microsoft** [comment]
Got it. Thanks for the investigation!

**Comment by XiaofeiCao** [comment]
2.26.0 released.
