### ISSUE TITLE
CustomCheckStyle: extension category is missing from Rules section.

### ISSUE THREAD

**Issue by mssfang** [Azure/azure-sdk-for-java#3365]
configure check style rules configuration to be able to show:

extension in Category column

**Comment by JonathanGiles** [comment]
What does this issue mean? Can you provide more context please?

**Comment by mssfang** [comment]
In the CheckStyle error/warning summary section after you open the site (checkstyle-aggregate.html).
The newly generated error by custom checkstyle is not included.  For example, the number of error shows 3 but the summary section only has 1 error shows up.
