### ISSUE TITLE
[FEATURE REQ] Expose receiver Disposition in azure-core-amqp

### ISSUE THREAD

**Issue by conniey** [Azure/azure-sdk-for-java#33682]
Expose support receiver disposition (Accepted, Rejected, Deferred, etc) in azure-core-amqp so users can use it without azure-messaging-servicebus. I.e. exposing disposition API in AMQP core ReceiveLinkHandler and ReactorReciver types.

We want to tackle this requirement via a two-phase apporach.

Phase-1 - We introduce the ReceiverUnsettledDeliveries implementation type in AMQP Core that abstracts the disposition support. The ServiceBus will use this type. An additional goal is to have extensive test coverage for this functionality.

Phase-2 - We will make ReceiverUnsettledDeliveries package private type, and ReceiveLinkHandler will use it underneath to expose the disposition API. The phase-2 has a dependency on https://github.com/Azure/azure-sdk-for-java/issues/33701

Notes: As this work removes the need for one buffering, which exists to support internal decodeDelivery API, the buffering-reduction here simplifies the linked credit stabilization work 30930

**Comment by anuchandy** [comment]
This is the uber work item for a two phased work. The phase-1 (with pr linked) tracked [here ](https://github.com/Azure/azure-sdk-for-java/issues/33651)

**Comment by anuchandy** [comment]
Work completed in https://central.sonatype.com/artifact/com.azure/azure-core-amqp/2.9.0
