### ISSUE TITLE
[Uber work item] Prefetch Reliability

### ISSUE THREAD

**Issue by conniey** [Azure/azure-sdk-for-java#33688]

**Comment by anuchandy** [comment]
This is the uber work item, which depends on the following -

## Amqp-Core

#33700
#33682

## ServiceBus

#30930
#33704
#33705
#33706
#33707

**Comment by anuchandy** [comment]
This is the uber work item, which depends on the following -

## Amqp-Core (must-have)

#33700
#33682

## ServiceBus (must-have)

#30930
#33704
#33705
#33706
#33707

## ServiceBus (nice-to-have)

#33710 (extension of 33707)

**Comment by anuchandy** [comment]
All work items except 33706 are implemented in the PR https://github.com/Azure/azure-sdk-for-java/pull/34854 . The wok-item 33706 (Session feature) is _not_ planned for include in this PR and is treated as a work of its own.

**Comment by anuchandy** [comment]
> All work items except 33706 are implemented in the PR #34854 . The wok-item 33706 (Session feature) is _not_ planned for include in this PR and is treated as a work of its own.

Change of plan: We are addressing the session issue (33706) as well as part of https://github.com/Azure/azure-sdk-for-java/pull/34854

**Comment by anuchandy** [comment]
These work items are being rolled out as incremental updates. The new underlying framework with improvements is called V2-Stack. The latest beta (beta.4) version of Service Bus (and its Core AMQP dependency) includes V2-Stack with these work items incorporated.

To use the beta.4 version, add the following dependency.

```xml
<dependency>
    <groupId>com.azure</groupId>
    <artifactId>azure-messaging-servicebus</artifactId>
    <version>7.15.0-beta.4</version>
</dependency>
```

The beta.4 composes both the previous generation of stack (The stack GA versions are using) and the new V2-Stack. Some of the features by default use V2-Stack, while other features require V2-Stack opt-in. The opt-in or opt-out of a specific Stack (V2 vs previous generation) for a feature is accomplished by providing `com.azure.core.util.Configuration` object at the time of building the Client object.

For example, V2-Stack based Session Receive with ProcessorClient requires opt-in as shown below –

```java
ServiceBusProcessorClient sessionProcessor = new ServiceBusClientBuilder()
        .connectionString(Config.CONNECTION_STRING)
        .configuration(new com.azure.core.util.ConfigurationBuilder()
          .putProperty("com.azure.messaging.servicebus.session.processor.asyncReceive.v2", "true") // 'false' by default, opt-in if enabling V2 is desired.
          .build())
        .sessionProcessor()
        .....
```

The following table lists the client types, corresponding configuration names and indicate if Client is enabled by default in V2-Stack or not. For a client that is not on V2-Stack by default, the example shown above can followed to opt-in.


|  Client Type    | Configuration-Name  | Is on V2-Stack By default? | 
| -------- | ---------------------------- |---------------------------- |
|  Sender and management Client. |  com.azure.messaging.servicebus.sendAndManageRules.v2 |YES |
|  Non-Session Processor and Reactor Receiver Client. |  com.azure.messaging.servicebus.nonSession.asyncReceive.v2 |YES |
|  Non-Session Synchronous Receiver Client. |  com.azure.messaging.servicebus.nonSession.syncReceive.v2 |NO |
|  Session Processor Receiver Client. |  com.azure.messaging.servicebus.session.processor.asyncReceive.v2 |NO |
|  Session Reactor Receiver Client. |  com.azure.messaging.servicebus.session.reactor.asyncReceive.v2 |NO |
|  Session Synchronous Receiver Client. |  com.azure.messaging.servicebus.session.syncReceive.v2 |NO |

**Comment by anuchandy** [comment]
All SB client types have v2 support implemented, closing.
