### ISSUE TITLE
[FEATURE REQ] Enhance build tool report to include method call frequency

### ISSUE THREAD

**Issue by srnagar** [Azure/azure-sdk-for-java#33714]

**Comment by JonathanGiles** [comment]
I believe this is now implemented?

**Comment by srnagar** [comment]
PR opened - https://github.com/Azure/azure-sdk-for-java/pull/33642

**Comment by srnagar** [comment]
Completed in this PR - https://github.com/Azure/azure-sdk-for-java/pull/35495
