### ISSUE TITLE
[BUG] Unit Tests in CosmosTemplateIllegalTest.java Failing

### ISSUE THREAD

**Issue by trande4884** [Azure/azure-sdk-for-java#33729]
**Describe the bug**
In the file CosmosTemplateIllegalTest.java which is in azure-spring-data-cosmos there are two test cases that are failing. Investigate why these are suddenly failing and fix the issue.

**Screenshots**
![image](https://user-images.githubusercontent.com/63077034/221250344-15bc473c-e53f-4e14-91d8-5f08f426df60.png)

**Information Checklist**
Kindly make sure that you have added all the following information above and checkoff the required fields otherwise we will treat the issuer as an incomplete report
- [x] Bug Description Added
- [x] Repro Steps Added
- [ ] Setup information Added

**Comment by kushagraThapar** [comment]
@trande4884 is this still an issue? If not, please close it or we can prioritize it accordingly.

**Comment by trande4884** [comment]
No longer an issue.
