### ISSUE TITLE
Tables: ListEntitiesOptions.setTop() not having affect when used for TableClient.listEntities(ListEntityOptions)

### ISSUE THREAD

**Issue by yuruhimesama** [Azure/azure-sdk-for-java#33737]
The setTop result count limiter isn't...limiting. User error? Something deeper?

```java

***
    private Options() {
        limit = 100;
    }

    public static Options getInstance() {
        return new Options();
    }
***

    Options defaultOptions = Options.getInstance();

    ListEntitiesOptions options = new ListEntitiesOptions();
    options.setTop(defaultOptions.getLimit());
    PagedIterable<TableEntity> entities = tableClient.listEntities(options, Duration.ofMinutes(1),
        Context.NONE);
***
    Assertions.assertEquals(100, results.size());

 org.opentest4j.AssertionFailedError: expected: <100> but was: <105>

```

**Comment by yuruhimesama** [comment]
jarfile version 12.3.7

**Comment by joshfree** [comment]
Hi @yuruhimesama thank you for reaching out to us via this GitHub issue; @jairmyree could you please take a look and follow up with @yuruhimesama?

**Comment by yuruhimesama** [comment]
@jairmyree related to #21202?

**Comment by jairmyree** [comment]
@yuruhimesama Thank you for making us aware of this issue. I will take a look and get back to you shortly.

**Comment by jairmyree** [comment]
Hi @yuruhimesama, I've investigated your concerns and have reached a conclusion:

 According to the documentation for `listEntities`: 

>["If the `top` parameter is set, the maximum number of returned TableEntity **per page** will be limited to that value."](https://learn.microsoft.com/en-us/java/api/com.azure.data.tables.tableclient?view=azure-java-stable#com-azure-data-tables-tableclient-listentities(com-azure-data-tables-models-listentitiesoptions-java-time-duration-com-azure-core-util-context))

When choosing to iterate by page, you will find that each page is limited to the number of entities specified by `top`. All of the entities remain present and are available in the subsequent pages. If you choose to not iterate by page, you will see that all the entities are returned even when the `top` parameter is set.

To "limit" the amount of returned entities, an option that you have is to limit the entities returned to a specific amount per page and then to take the first page.
```java
PagedIterable<TableEntity> entities = tableClient.listEntities(options, Duration.ofMinutes(1), Context.NONE);
Iterator<PagedResponse<TableEntity>> iterator = entities.iterableByPage().iterator();
List list = iterator.next().getValue(); // Placing the first `top` number of entities into a List
```

Thank you for reaching out. I hope this resolves your concerns.
