### ISSUE TITLE
[Stress Test] Move the maven build command to the docker file

### ISSUE THREAD

**Issue by liukun-msft** [Azure/azure-sdk-for-java#33743]
Currently we need to run two commands to deploy the Java stress test: one command to build out the jar file and one command to build docker image and deploy to AKS.

- https://github.com/Azure/azure-sdk-for-java/tree/main/sdk/eventhubs/azure-messaging-eventhubs-stress#deploy-stress-test
- https://github.com/Azure/azure-sdk-for-java/tree/main/sdk/servicebus/azure-messaging-servicebus-stress#deploy-stress-test

We can move the maven build command to the docker file so that we can deploy with one command. This will facilitate the stress test pipeline, which is now being worked on by the Eng team.

Refer to Go Dockerfile:
- https://github.com/Azure/azure-sdk-for-go/blob/main/sdk/messaging/azservicebus/internal/stress/Dockerfile

_**Progress**_
We can do the maven build inside docker file with cache:
```docker
FROM maven:3.8.6-openjdk-11-slim AS maven_build
WORKDIR application
COPY pom.xml ./
COPY src ./src
RUN --mount=type=cache,target=/root/.m2 mvn clean install 

FROM mcr.microsoft.com/openjdk/jdk:11-mariner as extract
WORKDIR application
COPY --from=maven_build application/target/*.jar application.jar
RUN java -Djarmode=layertools -jar application.jar extract
```
Because [checkstyle error 'Execution default of goal org.apache.maven.plugins:maven-checkstyle-plugin:3.1.0:check failed'](https://github.com/Azure/azure-sdk-for-java/blob/main/CONTRIBUTING.md#workaround-for-checkstyle-error), we need to find some way to maven build 'sdk-build-tools' first, and now is blocking at finding a way to copy a project from parent folder in docker file. (I tried to add `-Dcheckstyle.skip` and other skips for maven command, but it doesn't work.)

**Comment by lmolkova** [comment]
this is done
