### ISSUE TITLE
[FEATURE REQ] pluggable transport layer

### ISSUE THREAD

**Issue by jianghaolu** [Azure/azure-sdk-for-java#3375]
**Is your feature request related to a problem? Please describe.**

As discussed by the team & learned from UX studies, we are planning to provide simpler sync SDKs to help our customers get up and running with Azure, on top of the async SDK we already provide. 

There are 2 ways to implement it in Java. We can either synchronize the Netty client today, setting executor count and connection pool size to 1, or use a synchronous client, like `HttpUrlConnection`.

The first approach is simple and straightforward, but in reality, we are not providing the promised *simplicity* through this approach, as users will still struggle with the complicated stack trace and the full threading model in Netty client.

For the second approach, we will need to allow plugging in a different HTTP client, or even more generically, a different transport layer, e.g. mongo Java driver, etc.

**Describe the solution you'd like**
We'd like to generalize our interface [`HttpClient`](https://github.com/Azure/azure-sdk-for-java/blob/master/common/azure-common/src/main/java/com/azure/common/http/HttpClient.java) to allow synchronous HTTP clients, and even other protocols.

Specifically, these are the steps we'll likely take:

1. Remove Netty specific types and uses including wrapping `ByteBuf` in our interface, paired with an adapter for Netty.
2. Remove Reactor-Netty as a required dependency in azure common, but a separate module.
3. Add synchronous methods to all the async functionalities `HttpClient` currently provides. (**Discuss:** maybe 2 classes, `HttpClient` and `AsyncHttpClient`? This provides simplicity in implementing them but complexity in consuming them in the pipeline.)
4. Implement a module parallel to `azure-common-transport-netty`, backed by `HttpUrlConnection`, or `Apache Common Http Client`, implementing the interface in 3.
5. Rename `HttpClient` to be more generic, and implement a transport module for other protocols, like mongo Java driver.

**Describe alternatives you've considered**
Would love to have community input.

**Information Checklist**
Kindly make sure that you have added all the following information above and checkoff the required fields otherwise we will treat the issuer as an incomplete report
- [x] Description Added
- [x] Expected solution specified

**Comment by jianghaolu** [comment]
This task can potentially be broken down into smaller tasks, as it lays foundation for 2 major features: sync client, and support for other protocols.

**Comment by alzimmermsft** [comment]
The work to make the `HttpClient` has been completed.
