### ISSUE TITLE
Storage - Files Data Lake Samples Issue

### ISSUE THREAD

**Issue by hongli750210** [Azure/azure-sdk-for-java#33774]
1.
**Section** [link](https://github.com/Azure/azure-sdk-for-java/blob/main/sdk/storage/azure-storage-file-datalake/src/samples/java/com/azure/storage/file/datalake/FileSystemAsyncClientJavaDocCodeSamples.java#L64)

![image](https://user-images.githubusercontent.com/74638143/221736433-1b511569-b4d5-44e8-93f5-017971beb715.png)

**Reason:**
The method getRootDirectoryAsyncClient() from the type DataLakeFileSystemAsyncClient is not visible.

**Suggestion:**
The source change to `client.getDirectoryAsyncClient("") `.

2.
**Section** [link](https://github.com/Azure/azure-sdk-for-java/blob/main/sdk/storage/azure-storage-file-datalake/src/samples/java/com/azure/storage/file/datalake/FileSystemClientJavaDocCodeSamples.java#L70)

![image](https://user-images.githubusercontent.com/74638143/221736544-0f0865f8-1639-4b3c-9200-848657a22106.png)

**Reason:**
The method getRootDirectoryClient() from the type DataLakeFileSystemClient is not visible.

**Suggestion:**
The source change to  `client.getDirectoryClient("") `.

@joshfree, @kasobol-msft, @kyle-patterson and @alzimmermsft for notification.

**Comment by ibrahimrabab** [comment]
Hi @hongli750210 

Thanks for reaching out. Based on your suggestion, if we change the code snippet for `getRootDirectoryClient()` to `getDirectoryAsyncClient("")` and `getDirectoryClient("")`, then there won't be a proper code snippet that shows users how to use `DataLakeFileSystemAsyncClient.getRootDirectoryAsyncClient()` and `DataLakeFileSystemClient.getRootDirectoryClient()`. 

If you see here:
[https://github.com/Azure/azure-sdk-for-java/blob/main/sdk/storage/azure-storage-file-datalake/src/main/java/com/azure/storage/file/datalake/DataLakeFileSystemAsyncClient.java#L219](https://github.com/Azure/azure-sdk-for-java/blob/main/sdk/storage/azure-storage-file-datalake/src/main/java/com/azure/storage/file/datalake/DataLakeFileSystemAsyncClient.java#L219)

The code snippet is referencing to the method being used. If we change this, this would not be a proper code snippet for the method `getRootDirectoryAsyncClient`.

Let me know if there is anything else we can do about this, or any other suggestions you may have. Thanks!

**Comment by hongli750210** [comment]
@ibrahimrabab 

Currently, the samples are in the path of this package, so there is no issue. 
But when the reference scene is changed to importing the jar package, `DataLakeFileSystemAsyncClient.getRootDirectoryAsyncClient()` and `DataLakeFileSystemClient.getRootDirectoryClient()` are friendly methods, so they cannot be accessed from the outside package, and this samples cannot be compiled.
