### ISSUE TITLE
IoT Device Update Readme Issue

### ISSUE THREAD

**Issue by v-hongli1** [Azure/azure-sdk-for-java#33778]
1.
Section [link](https://github.com/Azure/azure-sdk-for-java/tree/main/sdk/deviceupdate/azure-iot-deviceupdate#azure-device-update-for-iot-hub-client-library-for-java)

![image](https://user-images.githubusercontent.com/74638143/221737920-7abbf67b-7f10-4ca6-9ae3-973e29bd31c6.png)

**Reason:**
The link points to an incorrect page.

**Suggestion:**
Link change to `https://github.com/Azure/azure-sdk-for-java/tree/main/sdk/deviceupdate/azure-iot-deviceupdate/src`.

@joshfree, @dpokluda for notification.

**Comment by v-xuto** [comment]
This issue has been fixed. We will close it.
