### ISSUE TITLE
Azure Cache for Redis: Azure AD with Jedis client library

### ISSUE THREAD

**Issue by ArtistLL123** [Azure/azure-sdk-for-java#33811]
Azure Cache for Redis: Azure AD with Jedis client library
https://github.com/Azure/azure-sdk-for-java/blob/main/sdk/identity/azure-identity/src/samples/Azure-Cache-For-Redis/Jedis/Azure-AAD-Authentication-With-Jedis.md
Can Azure China use this function?

**Comment by joshfree** [comment]
@g2vinay could you please follow up with @ArtistLL123
