### ISSUE TITLE
[QUERY] Compatiblity with Spark 3.2.2-hadoop3.2 and scala 2.12?

### ISSUE THREAD

**Issue by RusabKhan** [Azure/azure-sdk-for-java#33816]
**Query/Question**
I have been trying to connect using your _com.microsoft.azure:azure-cosmosdb-spark_2.4.0_2.11:1.3.5_ but it keeps giving error _java.lang.NoSuchMethodError: 'scala.collection.mutable.ArrayOps scala.Predef$.refArrayOps(java.lang.Object[])_ after a quick google search I came to the conclusion that currently cosmos support spark 2.* versions and not 3. Am I correct? or am I missing something here?

***Why is this not a Bug or a Feature Request?***
Your docs claim an older spark version than what I am using.

**Setup (please complete the following information if applicable):**
 - OS: Ubuntu 18 LTS (WSL)
 - Spark 3.1.2
 - Java 11
 - IDE: VSCode
 - Library/Libraries: [(com.microsoft.azure:azure-cosmosdb-spark_2.4.0_2.11:1.3.5)]
 
 **Information Checklist**
 Kindly make sure that you have added all the following information above and checkoff the required fields otherwise we will treat the issuer as an incomplete report
- [X] Query Added
- [X] Setup information Added

**Comment by FabianMeiswinkel** [comment]
You can find the Spark 3 connector for Cosmos DB in Maven here:
Spark 3.1: https://search.maven.org/artifact/com.azure.cosmos.spark/azure-cosmos-spark_3-1_2-12/4.17.2/jar
Spark 3.2: https://search.maven.org/artifact/com.azure.cosmos.spark/azure-cosmos-spark_3-2_2-12/4.17.2/jar
Spark 3.3: https://search.maven.org/artifact/com.azure.cosmos.spark/azure-cosmos-spark_3-3_2-12/4.17.2/jar

Config reference: https://github.com/Azure/azure-sdk-for-java/blob/main/sdk/cosmos/azure-cosmos-spark_3_2-12/docs/configuration-reference.md
Quickstart: https://github.com/Azure/azure-sdk-for-java/blob/main/sdk/cosmos/azure-cosmos-spark_3_2-12/docs/quick-start.md
Migration from Spark 2 to Spark 3: https://github.com/Azure/azure-sdk-for-java/blob/main/sdk/cosmos/azure-cosmos-spark_3_2-12/docs/migration.md

**Comment by RusabKhan** [comment]
Thanks
