### ISSUE TITLE
[BUG]Adding Jackson-databind 2.14.2 to pom creating error at Pom.xml

### ISSUE THREAD

**Issue by SuryaSP97** [Azure/azure-sdk-for-java#33831]
[](url)**Describe the bug**
 Adding Jackson-databind 2.14.2 to pom creating error at Pom.xml

***Code Snippet***
<dependency>
    <groupId>com.fasterxml.jackson.core</groupId>
    <artifactId>jackson-databind</artifactId>
    <version>2.14.2</version>
</dependency>

**Expected behavior**
Should not create any error at pom xml, so that ObjectMapper to Convert json String -> Hash MAp using Jackson databind.

**Screenshots**
![image](https://user-images.githubusercontent.com/120461715/222354163-565c5014-db25-471e-a25b-b8ae9d86819e.png)

**Setup (please complete the following information):**
 - OS: Windows 10 Pro
 - IDE: Intel(R) Core(TM) i5-8250U CPU @ 1.60GHz   1.80 GHz
 - Java version: [11] 
 - Frameworks: TESTNG

**Comment by alzimmermsft** [comment]
Thanks for filing this issue @SuryaSP97, could you include more details on the exact error being reported? Such as the Azure SDKs being used, object type being deserialized/serialized, and the JSON payload (redacting any potential secrets or PII), this'll help determine the root cause.
