### ISSUE TITLE
[BUG]PartitionIsMigrating Exception is being returned back to customer

### ISSUE THREAD

**Issue by xinlian12** [Azure/azure-sdk-for-java#33843]
In general, SDK should not return PartitionIsMigrating(410 in general) status code back to customer, it should have been wrapped within ServiceUnavailable exceptions instead.

**Comment by kushagraThapar** [comment]
@rinatmini can you please take a look at this, thanks!

**Comment by rinatmini** [comment]
Not actual, isn't reproducible.
