### ISSUE TITLE
[FEATURE REQ] Why is CosmosQueryRequestOptions.setMaxItemCount private ?

### ISSUE THREAD

**Issue by snalli** [Azure/azure-sdk-for-java#33863]
**Is your feature request related to a problem? Please describe.**
I want to request a scan an entire table in small batches and want to setMaxItemCount in CosmosQueryRequestOptions so that I may use the continuationToken to send the same query over and over again and scan the entire table. But setMaxItemCount is private. How do I set the max number of results returned for a query /

**Describe the solution you'd like**
I want to set the max number of items returned by a query, not the max number of pages.

**Describe alternatives you've considered**
SELECT TOP, and OFFSET-LIMIT but these complicate application logic

**Additional context**

**Information Checklist**
Kindly make sure that you have added all the following information above and checkoff the required fields otherwise we will treat the issuer as an incomplete report
- [x] Description Added
- [x] Expected solution specified

**Comment by kushagraThapar** [comment]
@snalli  - you can use `CosmosPagedIterable` or `CosmosPagedFlux` to set page size when retrieving results. page size is the max number of items returned per page of the query. It works similar to how maxItem used to work in older versions of java SDK. 
Here is an example of it - https://github.com/Azure-Samples/azure-cosmos-java-sql-api-samples/tree/main/src/main/java/com/azure/cosmos/examples/queries

**Comment by kushagraThapar** [comment]
@snalli - you can also refer to this document for more information on query pagination as well as how to optimize query performance - https://learn.microsoft.com/en-us/azure/cosmos-db/nosql/performance-tips-query-sdk?tabs=v3&pivots=programming-language-java#tune-the-page-size-1
