### ISSUE TITLE
[FEATURE REQ] Allow to enable FIPS worker nodes using fluent API in AzureResourceManager#kubernetesClusters

### ISSUE THREAD

**Issue by pgalache** [Azure/azure-sdk-for-java#33870]
**Is your feature request related to a problem? Please describe.**

Allow to enable FIPS when defining the AgentPool of nodes, using the fluent api of `AzureResourceManager#kubernetesClusters()`

**Describe the solution you'd like**
When defining a `KubernetesCluster` using the fluent API of `AzureResourceManager#kubernetesClusters()` there is an step where we should define the AgentPool. It has several properties set by `withXXX` style methods (e.g. VirtualMachineSize, AgentPoolMode, etc) but I miss a method to enable FIPS on the worker nodes. I think it should exist as the `ManagedClusterInner` that is used under the hood allows to set it.

**Describe alternatives you've considered**
The other possible approach would be using directly the `ManagedClustersClient`:

````
 ManagedClusterInner managedClusterInner = new ManagedClusterInner();
    managedClusterInner
        .withKubernetesVersion(kubernetesVersion)
        .withServicePrincipalProfile(
            new ManagedClusterServicePrincipalProfile()
                .withClientId(xxxx)
                .withSecret(xxx)
        )
        .withDnsPrefix(xxx)
        .withLinuxProfile(
            new ContainerServiceLinuxProfile()
                .withAdminUsername(xxx)
                .withSsh(
                    new ContainerServiceSshConfiguration()
                        .withPublicKeys(List.of(new ContainerServiceSshPublicKey().withKeyData(xxx)))
                )
        ).withAgentPoolProfiles(List.of(
            new ManagedClusterAgentPoolProfile()
                .withName(AGENT_POOL_NAME)
                .withVmSize(xxx)
                .withOsType(OSType.LINUX)
                .withCount(xxx)
                .withMode(AgentPoolMode.SYSTEM)
                .withEnableFips(true)
            )
        );

 azureResourceManager.kubernetesClusters().manager().serviceClient().getManagedClusters()
        .createOrUpdate(azureRegion.getResourceGroup(), environment.getName(), managedClusterInner);
````

**Additional context**

**Information Checklist**
Kindly make sure that you have added all the following information above and checkoff the required fields otherwise we will treat the issuer as an incomplete report
- [X] Description Added
- [X] Expected solution specified

**Comment by weidongxu-microsoft** [comment]
@XiaofeiCao 

See if we can catch it in March.

**Comment by XiaofeiCao** [comment]
I'll work on it.

**Comment by pgalache** [comment]
Is there any ETA for this?

**Comment by XiaofeiCao** [comment]
@pgalache Should be available in 2.25.0 around mid March.

**Comment by XiaofeiCao** [comment]
Hi @pgalache , 2.25.0 released with FIPS supported.

**Comment by pgalache** [comment]
Great, thanks!

**Comment by pgalache** [comment]
> Hi @pgalache , 2.25.0 released with FIPS supported.

Great. Thanks
