### ISSUE TITLE
[QUERY] Max value for maxAutoLockRenewDuration

### ISSUE THREAD

**Issue by garoplin** [Azure/azure-sdk-for-java#33893]
**Query/Question**
Are there any upper limits for **serviceBusClientBuilder.maxAutoLockRenewDuration()** property? Currently I've setup it to 3h, but I want to know whether it safe to have the value set for any number, let's say 24h. Do you have any recommendations for that?

***Why is this not a Bug or a feature Request?***
The functionality works fine, I just want to ask for proper usage or suggestions.
**Setup (please complete the following information if applicable):**
 - OS: iOS
 - IDE: intelliJ
 - Library/Libraries: azure-messaging-servicebus:7.13.1
 
 **Information Checklist**
 Kindly make sure that you have added all the following information above and checkoff the required fields otherwise we will treat the issuer as an incomplete report
- [x] Query Added
- [x] Setup information Added

**Comment by joshfree** [comment]
@anuchandy could you please follow up with @garoplin on this question?

**Comment by garoplin** [comment]
@anuchandy Any update on that question?

**Comment by anuchandy** [comment]
The lock token renewal is a recurring task on the SDK running on a host. It means the renewal will stop if the host node restarts (e.g., AKS pod) or certain SDK components need to restart. 

All the states associated with the lock token renewal are scoped to the underlying AMQP connection (think of it as a TCP connection). So for some reason, if the connection goes down (e.g., networking disconnect), the state is also lost, so token renewal stops. Underneath, the SDK recovers and resumes receiving on a new connection. By Service Bus design, those old messages (with the lock expired) will be redelivered (if they haven't exhausted the delivery count) on a new connection.

The recommendation I heard from teams helping to build business solutions is - to split the application computation logic into stages where each stage doesn't have to renew for more than a few mins, then checkpointing it to continue to the next stage. This way, the application can sustain transient downtime and doesn't have to repeat the entire computation.

So to answer your question, technically, there is no upper limit, but it has a risk as the transient issue can happen anytime.
