### ISSUE TITLE
Rename azure-common to azure-core

### ISSUE THREAD

**Issue by JonathanGiles** [Azure/azure-sdk-for-java#3393]
The naming used for azure-common is changing. Everything 'common' should now be 'core'. This includes package names, maven coordinates, directory names, etc.

**Comment by sima-zhu** [comment]
Including the mgmt renaming to management.

**Comment by sima-zhu** [comment]
#3349

**Comment by sima-zhu** [comment]
PR #3492

**Comment by sima-zhu** [comment]
Code merge into central repo. Close the issue. Feel free to reopen if anything major not addressed.
