### ISSUE TITLE
Regarding stateless/uninitialized Azure object

### ISSUE THREAD

**Issue by Kalpa2019** [Azure/azure-sdk-for-java#3394]
I am using SDK for monitor purpose, when I get Azure Instance after authentication, I see the whole resources info have been initialized, for example, compute, storage, network, etc.
I was looking something like getting the metric values for a given known resources with the id. I dont want to initialize every kind of resources and get metrics instead only a required known vm or storage details. 
As it is going to be FaaS, I was thinking better to have limited & known & specific executions. get the metrics for a given resource.

***Why is this not a Bug or a feature Request?***
Not sure about the intent here basically comprehensive management driven.

Not sure, whether I have missed anything existing supporting like this usecase. Please let me know if this possible in any ways.

thanks,
Kalpa

**Comment by kurtzeborn** [comment]
Thank you for opening this issue! We are routing it to the appropriate team for follow up.

**Comment by yaohaizh** [comment]
@Kalpa2019 could you provide which SDK that you are using specifically, such as artifact ID, version, etc. so that we can follow up more accurately. Thanks.

**Comment by weidongxu-microsoft** [comment]
@Kalpa2019 

Azure is the convenient class. You don't have to use it. (same to the azure artifact)

If you only need one service, you can do e,.g.
```
ApplicationTokenCredentials credentials = ...
MonitorManager monitorManager = MonitorManager.configure().authenticate(credentials, SUB_ID);
```

And if you only need monitor, you can use such in mvn (similar for gradle)
```
        <dependency>
            <groupId>com.microsoft.azure</groupId>
            <artifactId>azure-mgmt-network</artifactId>
            <version>1.26.0</version>
        </dependency>

        <dependency>
            <groupId>com.microsoft.azure</groupId>
            <artifactId>azure-client-authentication</artifactId>
            <version>1.6.12</version>
        </dependency>
```

If you are using ealier version, you can find authentication dependencies under test dependency of a particular version of https://mvnrepository.com/artifact/com.microsoft.azure/azure-mgmt-monitor

**Comment by yaohaizh** [comment]
Close as no more input from customer.

**Comment by Kalpa2019** [comment]
Thanks, it works.
