### ISSUE TITLE
ClientCertificateCredentialBuilder should not require writing certificate to disk

### ISSUE THREAD

**Issue by TrevorChristman** [Azure/azure-sdk-for-java#33951]
The Java variant of ClientCertificateCredentialBuilder requires clients to provide a path to the desired certificate file.
https://github.com/Azure/azure-sdk-for-java/blob/main/sdk/identity/azure-identity/src/main/java/com/azure/identity/ClientCertificateCredentialBuilder.java#L30

This is frustrating if the certificate is already available in memory by some other mechanism.  ClientCertificateCredentialBuilder actually already has overloads which accepts certificate as an InputStream, but these have not been marked public.

Note that the C# variant of ClientCertificateCredential accepts certificates from memory:  https://github.com/Azure/azure-sdk-for-net/blob/main/sdk/identity/Azure.Identity/src/Credentials/ClientCertificateCredential.cs#L87

**Comment by alzimmermsft** [comment]
@billwert, @g2vinay could you look into this

**Comment by TrevorChristman** [comment]
I'd also like to add that asking me to write the certificate to disk raises security concerns in my product that would be alleviated if my certificate could be stored only in memory at all times.

**Comment by mciancia8** [comment]
It would benefit my team at Microsoft greatly to have the ability to provide an InputStream instead of a file. We run on spark pools and the only way to get the cert is from the key vault, so I would not want to have to save it in a file first.

**Comment by g2vinay** [comment]
Thank you @TrevorChristman and @mciancia8 for raising this request.
I will provide updates as we make progress to add this support back into public API.

**Comment by billwert** [comment]
This has been fixed by #36747
