### ISSUE TITLE
Ingest code samples into JavaDoc from compilable source code

### ISSUE THREAD

**Issue by JonathanGiles** [Azure/azure-sdk-for-java#3396]
Use the [following tool](https://github.com/jtulach/codesnippet4javadoc/) to ingest code samples directly from the samples directory in our client library directories into the generated JavaDoc. Use the `-snippetpath` flag to specify the location of the sample code. Work with the existing client libraries (key vault and application config) to integrate this.

**Comment by srnagar** [comment]
PR https://github.com/Azure/azure-sdk-for-java/pull/3840 resolves this issue.
