### ISSUE TITLE
Cosmos: Avoid relatively expensive ConcurrentDeque.size in RntbdChannelPool for available channels

### ISSUE THREAD

**Issue by FabianMeiswinkel** [Azure/azure-sdk-for-java#33982]
**Describe the bug**
For available channels currently a ConcurrentDeque is used - which has non-constant cost for size - but size property is called for diagnostics (metrics/logging) - would be preferable to either not use concurrent data structure (should be fine, because this is all used on netty io thread - if it needs to stay a thread-safe data structure consider using a List-based Collection.

**Comment by mkrueger** [comment]
Another possible approach would be to track the size manually:

https://github.com/Azure/azure-sdk-for-java/commit/46b8b5e1d21be1b6d8701c3593ceaba40e0c1ea5
