### ISSUE TITLE
Caused by: {"ClassName":"BulkOperationFailedException","userAgent":"azsdk-java-cosmos/4.42.0-snapshot.1 Linux/5.4.0-1100-azure JRE/1.8.0_345","statusCode":413,"resourceAddress":null,"innerErrorMessage":"All retries exhausted for 'UPSERT' bulk operation - statusCode=[413:0] 

### ISSUE THREAD

**Issue by SqlRescuedLokesh** [Azure/azure-sdk-for-java#34008]
We are using the [spark-connector](https://github.com/Azure/azure-sdk-for-java/tree/main/sdk/cosmos/azure-cosmos-spark_3_2-12/Samples/DatabricksLiveContainerMigration) connector to move data from one cosmos db account to another and get this error message

Caused by: {"ClassName":"BulkOperationFailedException","userAgent":"azsdk-java-cosmos/4.42.0-snapshot.1 Linux/5.4.0-1100-azure JRE/1.8.0_345","statusCode":413,"resourceAddress":null,"innerErrorMessage":"All retries exhausted for 'UPSERT' bulk operation - statusCode=[413:0] itemId=[8xxxx]

I am not sure how to reproduce this error.

**Comment by FabianMeiswinkel** [comment]
That means one of the documents you tried to ingest exceeded the maximum size for Cosmos DB documents/items of 2 MB - Status Code 413 means Payload too large

Per-item limitations are documented here: https://learn.microsoft.com/en-us/azure/cosmos-db/concepts-limits#per-item-limits

**Comment by SqlRescuedLokesh** [comment]
Thanks, @FabianMeiswinkel 
could it be controlled by configuring below properties - 

spark.cosmos.read.maxItemCount
spark.cosmos.changeFeed.itemCountPerTriggerHint

**Comment by FabianMeiswinkel** [comment]
My suspicion is that serialization settings are set differently resulting in slightly different/larger json in the target container. This can be avoided by disabling schema inference when reading from the source. Anyway - to investigate we would need full exception details including ActivityId, exception message and callstack and account/database/container info - probably better via a support ticket - assuming you might not want to share that here.

**Comment by FabianMeiswinkel** [comment]
The two configs above can be used to control memory usage on the executors - has nothing to do with the 413 error.

My suspicion above would lead to the spark.cosmos.serialization.inclusionMode config setting.

**Comment by SqlRescuedLokesh** [comment]
Thanks @FabianMeiswinkel it looks like the document was inserted in the source container when the hard limit was not there
