### ISSUE TITLE
Javadocs: Cleanup invalid Javadocs

### ISSUE THREAD

**Issue by alzimmermsft** [Azure/azure-sdk-for-java#3400]
Some of the Javadocs in the track two library are using invalid syntax resulting in Javadoc generation to fail.

https://github.com/Azure/azure-sdk-for-java/blob/master/common/azure-common/src/main/java/com/azure/common/credentials/AsyncServiceClientCredentials.java#L14

https://github.com/Azure/azure-sdk-for-java/blob/master/common/azure-common/src/main/java/com/azure/common/annotations/ReturnValueWireType.java#L19

https://github.com/Azure/azure-sdk-for-java/blob/master/common/azure-common/src/main/java/com/azure/common/http/policy/AsyncCredentialsPolicy.java#L22

**Comment by JonathanGiles** [comment]
We should investigate splitting the javadoc generation between track one and track two, such that track two is set to fail build on warning or error, and that all lint checking is enabled.

**Comment by JonathanGiles** [comment]
Another option is to opt-in to stricter checking in track two pom files (like we do with spotbugs / checkstyle), or opt-out of it in the track one files. I would say opting-out in track one is the better option.

**Comment by alzimmermsft** [comment]
[Javadoc plugin](https://maven.apache.org/plugins/maven-javadoc-plugin/) documentation for reference

**Comment by srnagar** [comment]
Fixed as part of https://github.com/Azure/azure-sdk-for-java/pull/3863
