### ISSUE TITLE
[BUG] Check if we can remove non-codegen dependencies in emitter-package.json

### ISSUE THREAD

**Issue by weidongxu-microsoft** [Azure/azure-sdk-for-java#34024]
https://github.com/Azure/azure-sdk-for-java/blob/main/eng/emitter-package.json

ref https://github.com/Azure/azure-rest-api-specs/blob/main/documentation/cadl-structure-guidelines.md

**Comment by weidongxu-microsoft** [comment]
.net does not have extra dependencies
https://github.com/Azure/azure-sdk-for-net/blob/main/eng/emitter-package.json

python does
https://github.com/Azure/azure-sdk-for-python/blob/main/eng/emitter-package.json

I may need to check with Pan on .net

**Comment by weshaggard** [comment]
We should definitely try to remove the extra dependencies if possible and keep the emitter-package.json scoped to the emitter packages. 

However I do understand there might be some risk for other packages dependencies needed for a spec but my hope is that we can avoid the need for any of those. If you know of specific cases where that might not work I'm interested in learning about them.

**Comment by weshaggard** [comment]
FYI I've also asked python to do this as well see https://github.com/Azure/azure-sdk-for-python/pull/28801#discussion_r1131719932.

**Comment by weidongxu-microsoft** [comment]
Got it. Java will keep it at a minimum for now. If we see any TypeSpec source uses extra dependencies, we will discuss to add them (`cadl-autorest` maybe a candidate).

**Comment by haolingdong-msft** [comment]
https://github.com/Azure/azure-sdk-for-java/pull/34052  -> We removed extra dependencies and keep the typespec-java only in this pr.
