### ISSUE TITLE
Release plan for "azure-sdk-bom" > 1.2.10

### ISSUE THREAD

**Issue by eliasbalasis** [Azure/azure-sdk-for-java#34036]
**Query/Question**
When is the next release of "azure-sdk-bom" expected?
Is there a specific flow or policy?

In relation to #33448 , we are waiting for azure-core:1.37.0 to test the relevant fix, hence our question.

***Why is this not a Bug or a feature Request?***
We are only asking for release details.

**Setup (please complete the following information if applicable):**
 - OS: N/A
 - IDE: N/A
 - Library/Libraries: azure-core:1.37.0
 
 **Information Checklist**
- [ YES ] Query Added
- [ YES ] Setup information Added

**Comment by joshfree** [comment]
Hi @eliasbalasis we release new features, improvements, and bug fixes every month.  This includes a new azure-sdk-bom each month (except generally no release during December).  More information is available below, including the maven central link which will show the March 2023 azure-sdk-bom release after it ships later this month.

https://devblogs.microsoft.com/azure-sdk/azure-sdk-release-march-2023/

https://mvnrepository.com/artifact/com.azure/azure-sdk-bom

**Comment by joshfree** [comment]
I'm going to close this issue now, since I believe the question to be answered.  Please feel free to reactivate it if I misunderstood or if there are any other questions or issues that we can assist with.  Thank you.

**Comment by vcolin7** [comment]
BTW, here's a blog post with a bit more info on the Azure SDK BOM, its release cadence and more: https://devblogs.microsoft.com/azure-sdk/dependency-management-for-java/
