### ISSUE TITLE
Transport Type in Azure Service bus JAVA-SDK AMQP and AMQP WEBSOCKET

### ISSUE THREAD

**Issue by YogeshwarPrajapatiTR** [Azure/azure-sdk-for-java#34051]
Their is no any documentation for JAVA-SDK where can identify which transport Type is better in azure Service bus.
What is Pros and Cons for both Transport type in JAVA-SDK.
Which one is better in particular application?

**Comment by joshfree** [comment]
Thanks for this feedback @YogeshwarPrajapatiTR.  @sandeep-sen could you please follow up on this question and the feedback regarding the documentation?

/cc @Azure/azsdk-sb-java @JonathanGiles as fyi

**Comment by YogeshwarPrajapatiTR** [comment]
is their any update on this?

**Comment by ronniegeraghty** [comment]
Hi @YogeshwarPrajapatiTR, 
Sorry for the long wait for a response. You are right that we currently don't have any documentation going over the Pros and Cons of Service Bus communications over raw TCP or WebSockets. We'll work to rectify this hole in our documentation but in the meantime let me offer some information on the topic here. 

AMQP communications over raw TCP will be faster, but not by a large amount. 

AMQP over WebSockets uses standard HTTP ports which sometimes works better in enterprise environments with port blocks. AMQP over WebSockets is also needed when using a proxy. It will be slightly slower but not by an amount considered impactful for most scenarios.

Please let me know if the explanation above answers your question.

**Comment by ronniegeraghty** [comment]
Hi @YogeshwarPrajapatiTR,
Which option is better will depend on your particular situation. If the faster option is better, then AMQP over raw TCP will be better. Raw TCP is slightly faster than WebSockets. If the application will run behind a firewall, then it may be better to use WebSockets since it uses common ports and will work when using a proxy.
