### ISSUE TITLE
EnableSupportLogging (Allow extraction of all MSAL logs)

### ISSUE THREAD

**Issue by scottaddie** [Azure/azure-sdk-for-java#34072]
**Context:**
When customers encounter bugs in MSAL, the MSAL team needs detailed logs to diagnose the issue. The Azure Identity library doesn't have a provision to extract all these logs. In particular, we need verbose logs with PII information. For context, MSAL exposes 2 knobs for logging:

1. The log verbosity, which is very closely related to Azure SDK’s verbosity, i.e. Verbose, Info, Warning, Error.
2. A PII flag, false by default. Note: For a cheat sheet of what gets logged, see https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/wiki/PII.

The request is to allow app developers using the Azure Identity library to collect Verbose + PII logs from MSAL, on request, which are sometimes needed for supportability. The Azure Identity library exposes some knobs already, but there's no alignment over PII.

**Comment by joshfree** [comment]
Related https://devdiv.visualstudio.com/DevDiv/_workitems/edit/1755813/?triage=true

**Comment by pvaneck** [comment]
Example enabling Pii logging: https://learn.microsoft.com/en-us/azure/active-directory/develop/msal-logging-java#personal-and-organization-information
