### ISSUE TITLE
Ref docs issue Cannot index into a null array. At D:\a_work\1\s\Java\DownloadJavaPackages_v3.ps1:79 char:9

### ISSUE THREAD

**Issue by Menghua1** [Azure/azure-sdk-for-java#34082]
Error:

> [INFO] BUILD FAILURE
> [INFO] ------------------------------------------------------------------------
> [INFO] Total time:  1.793 s
> [INFO] Finished at: 2023-03-17T03:21:15Z
> [INFO] ------------------------------------------------------------------------
> [ERROR] Failed to execute goal org.apache.maven.plugins:maven-dependency-plugin:2.8:copy (default-cli) on project standalone-pom: Unable to find artifact.: Could not find artifact com.azure.tools:azure-sdk-build-tool:jar:sources:1.0.0-beta.1 in maven-repo (https://repo1.maven.org/maven2)
> [ERROR] 
> [ERROR] Try downloading the file manually from the project website.
> [ERROR] 
> [ERROR] Then, install it using the command: 
> [ERROR]     mvn install:install-file -DgroupId=com.azure.tools -DartifactId=azure-sdk-build-tool -Dversion=1.0.0-beta.1 -Dclassifier=sources -Dpackaging=jar -Dfile=/path/to/file
> [ERROR] 
> [ERROR] Alternatively, if you host your own repository you can deploy the file there: 
> [ERROR]     mvn deploy:deploy-file -DgroupId=com.azure.tools -DartifactId=azure-sdk-build-tool -Dversion=1.0.0-beta.1 -Dclassifier=sources -Dpackaging=jar -Dfile=/path/to/file -Durl=[url] -DrepositoryId=[id]
> [ERROR] 
> [ERROR] 
> [ERROR]   com.azure.tools:azure-sdk-build-tool:jar:1.0.0-beta.1
> [ERROR] 
> [ERROR] from the specified remote repositories:
> [ERROR]   maven-repo (https://repo1.maven.org/maven2, releases=true, snapshots=true),
> [ERROR]   azure-sdk-for-java (https://pkgs.dev.azure.com/azure-sdk/public/_packaging/azure-sdk-for-java/maven/v1, releases=true, snapshots=true),
> [ERROR]   maven-cognitiveservices-speech (https://csspeechstorage.blob.core.windows.net/maven/, releases=true, snapshots=true),
> [ERROR]   nexus (https://oss.sonatype.org/content/repositories/snapshots/, releases=true, snapshots=true),
> [ERROR]   central (https://repo.maven.apache.org/maven2, releases=true, snapshots=false)
> [ERROR] -> [Help 1]
> [ERROR] 
> [ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
> [ERROR] Re-run Maven using the -X switch to enable full debug logging.
> [ERROR] 
> [ERROR] For more information about the errors and possible solutions, please read the following articles:
> [ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException
> Cannot index into a null array.
> At D:\a\_work\1\s\Java\DownloadJavaPackages_v3.ps1:79 char:9
>          $SourcesJarDownloadPath = (Get-ChildItem $TempFolder -Filter  ...
>          ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
>     + CategoryInfo          : InvalidOperation: (:) [], ParentContainsErrorRecordException
>     + FullyQualifiedErrorId : NullArray
>  
> ##[error]PowerShell exited with code '1'.

For more details check here:

- https://apidrop.visualstudio.com/Content%20CI/_build/results?buildId=352455&view=results

@danieljurek for notification.

**Comment by danieljurek** [comment]
Closing. This no longer reproduces.
