### ISSUE TITLE
JAVA SDK CODE FOR CDN RULES CREATION

### ISSUE THREAD

**Issue by ajkum001** [Azure/azure-sdk-for-java#34089]
[Hi, One of my Cx provided the Java SDK example for the creating rules in the Azure cdn, He wants it to be added in the Azure CDN doc so that it will be useful to others , please verify and do the needful, thanks.

https://learn.microsoft.com/en-us/java/api/overview/azure/content-delivery-network?view=azure-java-stable

DeliveryRuleRequestSchemeCondition deliveryRulesCondition = new DeliveryRuleRequestSchemeCondition()
                .withParameters(
                        new RequestSchemeMatchConditionParameters()
                                .withMatchValues(
                                        Arrays.asList(RequestSchemeMatchConditionParametersMatchValuesItem.HTTP)));
        deliveryRulesCondition.validate();
 
        UrlRedirectActionParameters deliveryRulesActionParameters = new UrlRedirectActionParameters()
                .withRedirectType(RedirectType.TEMPORARY_REDIRECT).withDestinationProtocol(DestinationProtocol.HTTPS)
                .withCustomHostname("");
        UrlRedirectAction deliveryRulesAction = new UrlRedirectAction().withParameters(deliveryRulesActionParameters);
        deliveryRulesAction.validate();
 
        DeliveryRule cdnRrule = new DeliveryRule()
                .withName("HTTP to HTTPS redirect policy rule")
                .withOrder(1)
                .withConditions(Arrays.asList(deliveryRulesCondition))
                .withActions(Arrays.asList(deliveryRulesAction));
        cdnRrule.validate();
 
        EndpointUpdateParameters endpointUpdateParameters = new EndpointUpdateParameters()
                .withDeliveryPolicy(new EndpointPropertiesUpdateParametersDeliveryPolicy()
                        .withRules(Arrays.asList(cdnRrule))
                        .withDescription("HTTP to HTTPS redirect policy"));
 
        azureResourceManager.cdnProfiles()
                .manager()
                .serviceClient()
                .getEndpoints()
                .update(
                        resourceGroupName,
                        profileName,
                        endpointName,
                        endpointUpdateParameters);
                        
     >>This code also can be found in the last comment of the below doc by the Customer, thank you.
     
     https://learn.microsoft.com/en-us/answers/questions/878599/cdn-java-sdk-creating-rules]

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 5ef3c3de-775c-9746-f862-134b729f8c4c
* Version Independent ID: b5762502-1fd3-a6c8-6409-fd210dfdf068
* Content: [Azure Content Delivery Network SDK for Java](https://learn.microsoft.com/en-us/java/api/overview/azure/content-delivery-network?view=azure-java-stable)
* Content Source: [docs-ref-services/latest/content-delivery-network.md](https://github.com/Azure/azure-docs-sdk-java/blob/master/docs-ref-services/latest/content-delivery-network.md)
* Service: **azure-cdn**
* GitHub Login: @joshfree
* Microsoft Alias: **jfree**

**Comment by XiaofeiCao** [comment]
Thanks @ajkum001, above code snippet works! You may need `cdnProfile.refresh()` after the update to avoid stale model.

@weidongxu-microsoft Do we want to support it in convenience layer and update samples as well?

**Comment by weidongxu-microsoft** [comment]
@XiaofeiCao Yeah, we can schedule that.

Also we may want to remove the old CDN overview page on mslearn, it still point to 1.x lib
https://learn.microsoft.com/en-us/java/api/overview/azure/content-delivery-network?view=azure-java-stable

**Comment by XiaofeiCao** [comment]
2.26.0 released with convenience layer code support.
