### ISSUE TITLE
[FEATURE REQ] Spring Cloud Azure supports native images without adding extra dependencies

### ISSUE THREAD

**Issue by moarychan** [Azure/azure-sdk-for-java#34111]
**Is your feature request related to a problem? Please describe.**
Since [GraalVM support has been announced in the Azure SDK](https://devblogs.microsoft.com/azure-sdk/announcing-graalvm-support-in-azure-sdk-for-java-and-spring-cloud-azure-libraries/), Spring Cloud Azure 5.x needs to improve the existing support method, that is, to abandon the existing support through [additional dependencies](https://github.com/Azure/azure-sdk-for-java/tree/feature/spring-boot-3/sdk/spring/spring-cloud-azure-native-reachability), the goal is to support native images without any source code change.

**Describe the solution you'd like**
Put AOT support in each specific module, which is consistent with Spring's processing method, you can refer to this previous PR https://github.com/Azure/azure-sdk-for-java/pull/32742

**Describe alternatives you've considered**
N/A

**Additional context**
Should be consistent with the declared version, which is implemented in version 5.1.0.

**Information Checklist**
Kindly make sure that you have added all the following information above and checkoff the required fields otherwise we will treat the issuer as an incomplete report
- [x] Description Added
- [x] Expected solution specified

**Comment by chenrujun** [comment]
Closing this issue because related PR has been merged.
