### ISSUE TITLE
Authorized committer failed; but task commit success, data duplication may happen.[BUG]

### ISSUE THREAD

**Issue by gah112** [Azure/azure-sdk-for-java#34144]
**Describe the bug**
When executing a batch write of a Spark dataframe to Cosmos, the following error is occasionally thrown:
`Authorized committer failed; but task commit success, data duplication may happen.`

**To Reproduce**
We are executing a batch write of a Spark dataframe. Prior to writing, we populate both the `id` and `partitionKey` columns.

We have set our write configuration with the following variables:
`spark.cosmos.accountEndpoint` -> our Cosmos URI
`spark.cosmos.database` -> our Cosmos DB name
`spark.cosmos.container` -> our Cosmos container name
`spark.cosmos.preferredRegionLIst` -> the preferred region for our Cosmos service
`spark.cosmos.accountKey` -> our Cosmos account key
`spark.cosmos.write.strategy` -> `"ItemOverwrite"`

**Code Snippet**
`val writeOutput = aggregates.write.format("cosmos.oltp").mode("append").options(writeConfiguration).save()`

**Setup (please complete the following information):**
We are using an Azure Databricks cluster running 11.3LTS with version 4.11.0 of the current Spark Cosmos connector.

**Comment by kushagraThapar** [comment]
@xinlian12  can you please take a look, thanks!

**Comment by gah112** [comment]
We are generating the `id` values. If there is no risk of duplication, how can we resolve the errors?

**Comment by TheovanKraay** [comment]
We need to investigate whether this is actually a problem, and if not adjust the error message. As alluded to above by Fabian, the cases in which this error message are thrown may have been changed by the mentioned underlying Spark change to `OutputCommitCoordinator`. @gah112 did you actually observing duplicates or just concerned about why the error message is being thrown?

**Comment by gah112** [comment]
@TheovanKraay I have not observed any duplicate data. I am concerned with the error message and the follow-up effort it requires for my team.

**Comment by TheovanKraay** [comment]
@gah112 thanks for confirming. We'll review and change the error message as required.

**Comment by DjilFM** [comment]
> We are generating the `id` values. If there is no risk of duplication, how can we resolve the errors?

Hi, do you find any workaround to fix the issue.

**Comment by ibtissamef** [comment]
@TheovanKraay  we have similar error message with Databricks runtime version: 13.3 LTS and azure-cosmos-spark_3-4_2-12:4.22.0 installed.

**Comment by TheovanKraay** [comment]
We will investigate a possible fix. However, currently we can't reproduce the error, and it does not show up in any of our pipeline tests. @DjilFM @ibtissamef @gah112 can you provide a repro, or can you share any more details about your workload that may help us to reproduce this? Thanks.

**Comment by TheovanKraay** [comment]
> > We are generating the `id` values. If there is no risk of duplication, how can we resolve the errors?
> 
> Hi, did you find any workaround to fix the issue.

As Fabian mentioned above already, as long as you have deterministic id values (not some random value), or use a random value like UUID.randomId, have persisted the data frame after generating the id value (and before writing to Cosmos DB) all write strategies are idempotent - so this error would be safe to be retried - that would be the workaround.

**Comment by DjilFM** [comment]
> > > We are generating the `id` values. If there is no risk of duplication, how can we resolve the errors?
> > 
> > 
> > Hi, did you find any workaround to fix the issue.
> 
> As Fabian mentioned above already, as long as you have deterministic id values (not some random value), or use a random value like UUID.randomId, have persisted the data frame after generating the id value (and before writing to Cosmos DB) all write strategies are idempotent - so this error would be safe to be retried - that would be the workaround.

**Comment by DjilFM** [comment]
> > > We are generating the `id` values. If there is no risk of duplication, how can we resolve the errors?
> > 
> > 
> > Hi, did you find any workaround to fix the issue.
> 
> As Fabian mentioned above already, as long as you have deterministic id values (not some random value), or use a random value like UUID.randomId, have persisted the data frame after generating the id value (and before writing to Cosmos DB) all write strategies are idempotent - so this error would be safe to be retried - that would be the workaround.

we have a deterministic id values, but this error can't be ignored it's stop our stream, the error is systemtic even if we retry the job.

**Comment by FabianMeiswinkel** [comment]
@DjilFM - in this case above error is simply a symptom - it indicates that an executor stopped/failed a task. Root cause analysis would need to start at looking why the Task failed - what happened in the executor. Spark UI can help with that investigation.

**Comment by gah112** [comment]
This issue persists - is there a solution? Why has the issue been marked closed?

**Comment by TheovanKraay** [comment]
@gah112 it has been closed because we can't reproduce the reported error, and no steps have been provided to reproduce it, so we can't assist. Also, as Fabian mentioned above, the error you are reporting is a symptom, not necessarily the cause. The error shown indicates a Spark executor stopped/failed a task - that needs to be investigated (by you) looking at why the Task failed - i.e. what happened in the executor (using Spark UI). When you have more evidence that this is an issue with the Spark Connector for Cosmos DB, and steps to reproduce the error, you can create a new issue.

**Comment by gah112** [comment]
@TheovanKraay the Cosmos error is intermittent. We successfully write the same dataset to parquet every time. Databricks provides no access to executor logs for terminated job clusters. We cannot investigate the executor logs.

I've provided several details in my original post. What more information do you need to investigate this error?
