### ISSUE TITLE
[BUG] Add Rule Fail with Exception (SDK)

### ISSUE THREAD

**Issue by NatanelY** [Azure/azure-sdk-for-java#34158]
**Describe the bug**
We are using Azure SDK for Java (azure-resourcemanager library), version: 2.24.0.
While using the SDK to add new rule, we get the following error.
This happened in some scenarios using multiple ASGs that are linked to same Vnet.
In other case one of them is located under a different resource group. 
We also got this error message when adding a new rule without using ASG at all.
We created the same rule manually throw azure portal, the rule was added to NSG and no error message appeared.

***Exception or Stack Trace***
"code": "AllApplicationSecurityGroupsInSecurityRuleMustBeFromSameVnet", 

"message": "Security Rule /subscriptions/"subscription_id"/resourceGroups/CM/providers/Microsoft.Network/networkSecurityGroups/CMvm2-nsg has Application Security Groups (ASGs) from multiple virtual networks (/subscriptions/"subscription_id"/resourceGroups/CM/providers/Microsoft.Network/virtualNetworks/CM-VNET, /subscriptions/"subscription_id"/resourceGroups/CM_QA/providers/Microsoft.Network/virtualNetworks/CM_QA-VNET).
All ASGs on the Security Rule must be from the same virtual network."

**To Reproduce**
As I mentioned it is reproduced occasionally but the scenario that is most common is adding a rule with ASGs linked to the same VM while one of them is located on different resource group.
We created the same rule manually throw azure portal, the rule was added to NSG and no error message appeared.

***Code Snippet***
nsg.update().defineRule(“ruleName”)
.allowInbound()
.withSourceApplicationSecurityGroup(“/subscriptions/"subscription_id"/resourceGroups/CM_QA/providers/Microsoft.Network/applicationSecurityGroups/asg_nva”).fromAnyPort()
.withDestinationApplicationSecurityGroup(“/subscriptions/"subscription_id"/resourceGroups/CM_QA/providers/Microsoft.Network/applicationSecurityGroups/ASG_api”, 
“/subscriptions/"subscription_id"/resourceGroups/CM_QA/providers/Microsoft.Network/applicationSecurityGroups/ASG_web”)
.toAnyPort().withAnyProtocol().withPriority(107)
.attach().apply

**Expected behavior**
a new rule should be added without exception error. 

**Setup (please complete the following information):**
OS: windows\linux
IDE: IntelliJ
Library/Libraries: com.azure.resourcemanager:azure-resourcemanager:2.24.0com.azure.resourcemanager:azure-resourcemanager-network:2.24.0
Java version: 8

we suspect that the problem is related to the SDK because same rules are working properly through Azure portal,
the rule was added to NSG and no error message appeared.

**Comment by NatanelY** [comment]
Hi,
any update regarding this issue ?

**Comment by weidongxu-microsoft** [comment]
@NatanelY 

Is this error message true in your case?
"Security Rule /subscriptions/"subscription_id"/resourceGroups/CM/providers/Microsoft.Network/networkSecurityGroups/CMvm2-nsg has Application Security Groups (ASGs) from multiple virtual networks (/subscriptions/"subscription_id"/resourceGroups/CM/providers/Microsoft.Network/virtualNetworks/CM-VNET, /subscriptions/"subscription_id"/resourceGroups/CM_QA/providers/Microsoft.Network/virtualNetworks/CM_QA-VNET).
All ASGs on the Security Rule must be from the same virtual network."

It seems indeed say that there is 2 different Vnet.

Portal and SDK may use different api-version. 2.24.0 SDK would be the latest 2022-09-01 on Network. Sometimes, a later api-version would have improved validation on backend that try tell error before it get into the system.

**Comment by NatanelY** [comment]
@weidongxu-microsoft 
Hi,
Yes this is the error as I mentioned in the case.
I checked again the following scenarios:

1. I tried to add a new rule to NSG1. 
I used 2 ASGs that linked to VNET1, so that one is source and the other is destination.
VNET1 and NSG1 are under the same resource group.
It was added successfully through SDK.

2. I tried to add a new rule to NSG2. 
I used 2 ASGs that linked to VNET1, so that one is source and the other is destination.
VNET1 and NSG2 are under different resource groups.
this operation failed with the error message.

So I think that there is another dependency that is not documented:
ASGs should be under the same VNET and the VNET should be located under the same resource group with the NSG that we want to implement the rule.

**Comment by weidongxu-microsoft** [comment]
Thanks for the details.

@XiaofeiCao Could you double check in SDK and maybe with backend (if necessary)?
It seems not very reasonable that the setting to NSG get different behavior on whether the VNet in same resource group or not (resource group usually just a logic thing),

**Comment by XiaofeiCao** [comment]
It doesn't make sense to me too. I'll have that checked.

**Comment by NatanelY** [comment]
Hi, thanks for your response.

Our ASGs are under different resource groups.
meaning ASG1 is under rgName2, and linked to Vnet1.

We also encountered weird scenario:
We tried to add a rule to the NSG; with Service tag in source and IP address in destination.
The operation failed and we got same error message as mentioned above.

Maybe the NSG includes rule\s which contain ASGs which doesn't align with the SDK validations, but we would expect to get relevant error when an attempt to add rule doesn't include ASGs.

**Comment by XiaofeiCao** [comment]
Let me try to get this straight. Is this the configuration in your failure case?
| Resource      | Resource Group |
| ----------- | ----------- |
| ASG1      | RG2      |
| ASG2   | RG1        |
| VNET1 | RG1 |
| NSG2 | RG2 |

**Comment by NatanelY** [comment]
correct

**Comment by NatanelY** [comment]
Correct, maybe we tried to do some 

"Portal and SDK may use different api-version."
I have another question regarding this quote, when do you plan to upgrade the portal SDK to 2.24.0?

**Comment by XiaofeiCao** [comment]
Thanks @NatanelY for confirmation,

You can try our newly released 2.26.0. A new Network api-version has been used since 2.25.0.

SDK is released monthly.
