### ISSUE TITLE
[QUERY] When telemetryOptions.userAgentPrefix() is EMPTY User-Agent header comes with leading whitespace which lead to invalid character in header at times

### ISSUE THREAD

**Issue by cksharma11** [Azure/azure-sdk-for-java#34161]
**Query/Question**
```
public TelemetryFactory(TelemetryOptions telemetryOptions) {
        telemetryOptions = telemetryOptions == null ? new TelemetryOptions() : telemetryOptions;
        String userAgentPrefix = telemetryOptions.userAgentPrefix() == null ?
                Constants.EMPTY_STRING : telemetryOptions.userAgentPrefix();
        this.userAgent = userAgentPrefix + ' ' +
                Constants.HeaderConstants.USER_AGENT_PREFIX + '/' + Constants.HeaderConstants.USER_AGENT_VERSION +
                String.format(Locale.ROOT, " (JavaJRE %s; %s %s)",
                        System.getProperty("java.version"),
                        System.getProperty("os.name").replaceAll(" ", ""),
                        System.getProperty("os.version"));
    }
```

I'm getting an error because above method returns a header which has leading whitespace.

Header value - ` Azure-Storage/11.0.0 (JavaJRE 1.8.0_292; MacOSX 10.16)`

And the reason which is possible is because`telemetryOptions.userAgentPrefix();` is EMPTY_STRING

Using the headers the application internally calls netty-http library which leads to error mentioned here - https://github.com/netty/netty/issues/10820#issuecomment-1293380440

***Why is this not a Bug or a feature Request?***

I'm not sure if it's a bug so raising it as a question initially, and if you think it's a bug later maybe I can raise a PR to fix the same.

**Setup (please complete the following information if applicable):**
 - OS: [MacOS]
 - IDE: [IntelliJ]
 - Library/Libraries: 
 
 ```
implementation group: 'com.microsoft.azure', name: 'azure-storage-blob', version: '11.0.0'
implementation group: 'com.microsoft.azure', name: 'azure-storage', version: '8.4.0'
```
 
 **Information Checklist**
 Kindly make sure that you have added all the following information above and checkoff the required fields otherwise we will treat the issuer as an incomplete report
- [-] Query Added
- [-] Setup information Added

**Comment by joshfree** [comment]
@lmolkova @trask could you please take a look?

**Comment by lmolkova** [comment]
Hi @cksharma11 , it seems you're using [deprecated ](https://azure.github.io/azure-sdk/releases/deprecated/index.html#java) Azure Blob Storage library.  Unfortunately, we won't be able to provide a fix for this problem. Please consider [migrating](https://github.com/Azure/azure-sdk-for-java/blob/main/sdk/storage/azure-storage-blob/migrationGuides/V10_V12.md) to v12.
