### ISSUE TITLE
[QUERY] How to properly generate random password for Azure Key Vault Secret value? 

### ISSUE THREAD

**Issue by post-g** [Azure/azure-sdk-for-java#34189]
**Query/Question**
I am trying to create method that will randomly generate a password for an Azure Key Vault Secret value, and was not able to find appropriate Azure libraries to accomplish this. For reference, I have already implemented a similar method for generating a random password for AWS secrets manager secret using the library "GetRandomPasswordRequest". 

I was hoping to see if anyone would have guidance on the above. Also if Azure does not have appropriate libraries, are there some recommended libraries to achieve the goal of randomly generating a password to store in a Key Vault secret. 

Thanks. 

***Why is this not a Bug or a feature Request?***
This is neither of the above, since I am only querying if there exists the libraries to accomplish the goal mentioned. 

**Setup (please complete the following information if applicable):**
 - OS: [Windows]
 - IDE: [IntelliJ]
 
 **Information Checklist**
 Kindly make sure that you have added all the following information above and checkoff the required fields otherwise we will treat the issuer as an incomplete report
- [X] Query Added
- [X] Setup information Added

**Comment by joshfree** [comment]
@vcolin7 could you please follow up on this question from @post-g?

**Comment by vcolin7** [comment]
Hi @post-g, we don't have any specific guidance on randomly generating passwords to be stored as Key Vault secrets, as a secret can basically be any arbitrary string. You can simply generate a given number of random bytes using `SecureRandom` and convert them to a string value. By the way, for sensitive information like a password, I would avoid using the more predictable `Random` [as explained here](https://stackoverflow.com/a/11052736/4967034).
