### ISSUE TITLE
[BUG] azure-identity:1.8.1 is unable to retrieve a ManagedCredential for Azure Function App in Java, where 1.8.0 is able to.

### ISSUE THREAD

**Issue by KjeldSchmidt** [Azure/azure-sdk-for-java#34200]
**Describe the bug**
When using `com.azure:azure-identity` version `1.8.1` deployed in a Function App, then the library is unable to retrieve the Managed identity. The exact same code and infrastructure setup works perfectly fine when using 1.8.0 instead.

***Exception or Stack Trace***
When using version 1.8.1, the credential retrieval attempt simply say:

`Azure Identity => Attempted credential ManagedIdentityCredential is unavailable.`

When using 1.8.0 instead, we can see `Azure Identity => Attempted credential ManagedIdentityCredential returns a token` instead

**To Reproduce**
Unfortunately, I don't have the time to create a minimal example of this behaviour. I recognise that this makes the report incomplete.

***Code Snippet***
```
new SecretClientBuilder()
                            .vaultUrl(<keyVaultUrl>)
                            .credential(new DefaultAzureCredentialBuilder().build())
                            .buildClient();
```

**Expected behavior**
I expect the ManagedIdentityCredential to be retrievable using both 1.8.0 _and_ 1.8.1.

**Setup (please complete the following information):**
 - OS: Linux EP1 Service Plan
 - Library/Libraries: com.azure:azure-identity:1.8.0 / 1.8.1
 - Java version: 11
 - App Server/Environment: Azure Function, Extension Version ~4

**Information Checklist**
Kindly make sure that you have added all the following information above and checkoff the required fields otherwise we will treat the issuer as an incomplete report
- [ ✅ ] Bug Description Added
- [ ❌ ] Repro Steps Added
- [ ✅ ] Setup information Added

**Comment by joshfree** [comment]
Thanks for filing this issue, @KjeldSchmidt.  @g2vinay could you please take a look today / early next week?

/cc @billwert

**Comment by bpossolo** [comment]
I'm experiencing the same thing but from an Azure Web App service.
Managed Identity credential works with azure-identity 1.8.0 but fails on 1.8.1

1.8.0
```
2023-03-25T18:50:00.678246756Z: [INFO]  18:50:00.677 [Thread-7] INFO  c.a.i.ManagedIdentityCredential - Azure Identity => Managed Identity environment: AZURE APP SERVICE MSI/IDENTITY ENDPOINT
2023-03-25T18:50:00.679625819Z: [INFO]  18:50:00.679 [Thread-7] INFO  c.a.i.ManagedIdentityCredential - Azure Identity => getToken() result for scopes [https://storage.azure.com/.default]: SUCCESS
2023-03-25T18:50:00.680017737Z: [INFO]  18:50:00.679 [Thread-7] INFO  c.a.c.i.AccessTokenCache - Acquired a new access token.
```

1.8.1
```
2023-03-25T18:04:55.145674363Z: [INFO]  18:04:55.145 [main] ERROR c.a.i.ManagedIdentityCredential - Azure Identity => ERROR in getToken() call for scopes [https://vault.azure.net/.default]: Managed Identity authentication is not available.
2023-03-25T18:04:55.146744363Z: [INFO]  18:04:55.146 [main] ERROR c.a.c.i.AccessTokenCache - Failed to acquire a new access token.
```

my code
```
@Bean
@Profile("azure")
public TokenCredential credential() {
  return new ManagedIdentityCredentialBuilder().build();
}

@Bean
@Profile("azure")
public SecretClient secretClient() {
  String vaultUrl = env.getProperty("azure.vault.url");
  return new SecretClientBuilder()
    .credential(credential())
    .vaultUrl(vaultUrl)
    .buildClient();
}
```

Semi-Related
I discovered discovered another issue when I upgraded from azure-identity 1.4.6 to latest.
for an app using a system-assigned managed identity, azure-identity 1.4.6 works perfectly fine if a client id is passed to `ManagedIdentityCredentialBuilder` whereas newer versions do not.  
apparently this behavior changed and wasn't noted in the changelog.  
it might be worth calling out that client id **must not** be provided when using a system-assigned managed identity in these newer versions of azure-identity.  
the [official docs here](https://github.com/Azure/azure-sdk-for-java/blob/main/sdk/identity/azure-identity/README.md#authenticate-in-azure-with-managed-identity) only allude to it by saying that client id is only required for user-assigned managed identities.  
alternatively, you could make it very clear programmatically via some sort of `SystemAssignedManagedIdentityCredentialBuilder` vs `UserAssignedManagedIdentityCredentialBuilder`.

**Comment by g2vinay** [comment]
@KjeldSchmidt @bpossolo, this issue has been resolved in v.1.8.2 of azure-identity.
Recommend upgrading to v1.8.2

**Comment by joshfree** [comment]
Closing this issue as this has been resolved in https://mvnrepository.com/artifact/com.azure/azure-identity/1.8.2 and later versions.
