### ISSUE TITLE
missing links in monitor query readme.md

### ISSUE THREAD

**Issue by ciufudean** [Azure/azure-sdk-for-java#34210]
missing links in this text
*You can authenticate with Azure Active Directory using the [Azure Identity library][azure_identity]. Note that regional endpoints do not support AAD authentication. Create a [custom subdomain][custom_subdomain] for your resource in order to use this type of authentication.*

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: afdf0e58-d53e-3e34-d8ec-e992721ec35b
* Version Independent ID: 94cacfe3-3728-78dc-e89c-e15e1a2c7281
* Content: [Azure Monitor Query client library for Java](https://learn.microsoft.com/en-us/java/api/overview/azure/monitor-query-readme?view=azure-java-stable)
* Content Source: [docs-ref-services/latest/monitor-query-readme.md](https://github.com/Azure/azure-docs-sdk-java/blob/master/docs-ref-services/latest/monitor-query-readme.md)
* Service: **monitor**
* GitHub Login: @joshfree
* Microsoft Alias: **jfree**

**Comment by joshfree** [comment]
@srnagar can you please follow up on this issue filed by @ciufudean
