### ISSUE TITLE
[BUG] Azure AppConfiguration: Configuration is not updated dynamically with Spring Boot 3

### ISSUE THREAD

**Issue by MaxKiesel** [Azure/azure-sdk-for-java#34224]
**Describe the bug**
Following this tutorial https://learn.microsoft.com/en-us/azure/azure-app-configuration/enable-dynamic-configuration-java-spring-app, our Spring Boot App (version 2.7.6) was refreshing the configuration context for Azure AppConfiguration regularly. After the upgrade to Spring Boot 3.0.5, the values of the feature toggles in the cloud are only fetched during start up of the server, but there is no regular polling for updates anymore.

***Exception or Stack Trace***
There is no logging of the app configuration at all after the initial "Located property source: [BootstrapPropertySource ..."

**To Reproduce**
Following this tutorial https://learn.microsoft.com/en-us/azure/azure-app-configuration/enable-dynamic-configuration-java-spring-app with a Spring Boot version 3.0.5.

**Expected behavior**
The application should refresh all feature toggles by polling regularly for changes from the cloud.

**Setup (please complete the following information):**
 - Library/Libraries:
   - org.springframework.boot:spring-boot-starter-parent:3.0.5
   - com.azure.spring:azure-spring-cloud-appconfiguration-config-web:2.11.0
   - com.azure.spring:azure-spring-cloud-feature-management:2.10.0
 - Java version: 17

**Comment by chenrujun** [comment]
Hi, @MaxKiesel 
Thanks for reaching out.
Now app configuration related artifacts not supported to be used in Spring Boot 3.
Here is related issue: https://github.com/Azure/azure-sdk-for-java/issues/33758

**Comment by chenrujun** [comment]
Hi, @mrm9084 .
Please confirm that this problem has been fixed before release 5.1.0.

**Comment by mrm9084** [comment]
@MaxKiesel, 5.1.0 has been released. It does have a few breaking changes if you are moving from a 2.x version, not from the 4.x version. If you are updating from 2.x you can reference https://learn.microsoft.com/en-us/azure/azure-app-configuration/howto-convert-to-the-new-spring-boot

**Comment by MaxKiesel** [comment]
Hello everybody,
I upgraded to version 5.1.0 and it is working again.
Thank you very much!
