### ISSUE TITLE
Migrate test recording, for mgmt-plane

### ISSUE THREAD

**Issue by weidongxu-microsoft** [Azure/azure-sdk-for-java#34243]
link https://github.com/Azure/azure-sdk-for-java/issues/33342

We'd need to check if these work
- normal recording
- recording with random name/guid (i.e. they are saved to json, and loaded at playback)
- redact of secret (need to know whether we can still run script to redact it, before e.g. upload to somewhere we no longer control; or we can use TestBase to redact); if now request body is also recorded, we may need to add more redact rules

We may try
1. resources (random name)
2. storage (secret)
3. appservice or ACI/ACR (different kind of secret)

---

We also need to see if we can still batch modify api-version in recorded data, after phase2
We need this e.g. after upgrade resources RP or network RP
https://github.com/Azure/azure-sdk-assets/blob/main/README.md
e.g. upgrade Network would modify more tests https://github.com/Azure/azure-sdk-for-java/issues/34243#issue-1644850586

---

Another question on the "azure-sdk-assets" repo is: how it handles different recording from different branch (e.g. one branch may release a preview api-version, but main on stable)

**Comment by weidongxu-microsoft** [comment]
on redact

So it has gotten better. We now have [TestProxySanitizers](https://github.com/Azure/azure-sdk-for-java/blob/main/sdk/core/azure-core-test/src/main/java/com/azure/core/test/models/TestProxySanitizer.java#L9) to handle the redaction.

A lot of default redaction are already placed here https://github.com/Azure/azure-sdk-for-java/blob/main/sdk/core/azure-core-test/src/main/java/com/azure/core/test/utils/TestProxyUtils.java#L144

 

On top of tha, we can do custom redactions too.

Examples - https://github.com/Azure/azure-sdk-for-java/blob/main/sdk/core/azure-core-test/src/test/java/com/azure/core/test/TestProxyTests.java#L64-L67

**Comment by weidongxu-microsoft** [comment]
Most recording would be under "sdk/resourcemanager".

Very few other places, as mgmt recommend live tests for simpler RP
One of them:
https://github.com/Azure/azure-sdk-for-java/tree/main/sdk/confidentialledger/azure-resourcemanager-confidentialledger/src/test/resources/session-records

**Comment by weidongxu-microsoft** [comment]
You can contact samvaity, if more question.

**Comment by haolingdong-msft** [comment]
Reference links:
issue on test proxy: https://github.com/Azure/azure-sdk-for-java/issues/33342
example pr: https://github.com/Azure/azure-sdk-for-java/pull/33902

**Comment by haolingdong-msft** [comment]
Met issue on connecting to local test proxy server. Question here: https://github.com/Azure/azure-sdk-for-java/issues/33342#issuecomment-1504739305

**Comment by haolingdong-msft** [comment]
Started working on [azure-resourcemanager-resources](https://github.com/Azure/azure-sdk-for-java/tree/main/sdk/resourcemanager/azure-resourcemanager-resources)

**Comment by haolingdong-msft** [comment]
Testproxy migration: https://github.com/Azure/azure-sdk-for-java/wiki/Test-Proxy-Migration
sample pr: https://github.com/Azure/azure-sdk-for-java/pull/35186
resources pr: https://github.com/Azure/azure-sdk-for-java/pull/35476/files

**Comment by haolingdong-msft** [comment]
Todos:
1. try remove TextReplacementPolicy
2. retry-after = 0, make sure long lro can run successfully
3. storage, response body secret sanitize
4. credcheck before push to asset repo.
5. migration for other RPs.
