### ISSUE TITLE
[FEATURE REQ] Add isHierarchicalNamespaceEnabled to Blob client StorageAccountInfo

### ISSUE THREAD

**Issue by dain** [Azure/azure-sdk-for-java#34244]
**Is your feature request related to a problem? Please describe.**

It is critical to know if a storage account has hiearchical namespace enabled as the behavior of APIs like list is quite different (e.g., it returns directory entries as blobs), which could result in errors.  Additionally, if the caller knows that HNS is enabled then they can have alternate code paths for functions like rename.

**Describe the solution you'd like**

Add `isHierarchicalNamespaceEnabled()` to `StorageAccountInfo` class.  This can easily be added as StorageAccountInfo is constructed in `com.azure.storage.blob.BlobServiceAsyncClient#getAccountInfoWithResponse(com.azure.core.util.Context)` which has access to `ServicesGetAccountInfoHeaders` which has the method `isXMsIsHnsEnabled()`.

**Describe alternatives you've considered**

The work around for this is to inspect the response headers directly using something like this:
```java
        Response<StorageAccountInfo> response = blobServiceClient.getAccountInfoWithResponse(null, null);
        boolean hierarchicalNamespaceEnabled = Boolean.parseBoolean(response.getHeaders().get("x-ms-is-hns-enabled").getValue());
```
This code is a much more difficult to use and requires know the exact name of the response header (and proper null handling which I have not done above.

**Comment by dain** [comment]
I can send a PR if you want, but it is like 3 lines of code, so I'm not sure if it is easier for you'all to just change it.

**Comment by ibrahimrabab** [comment]
Hi @dain 
Thank you for reaching out with this feature request! We'll try to get this feature in soon for our next releases.
