### ISSUE TITLE
[BUG] EventHub Error occurred while refreshing token that is not retriable. Not scheduling refresh task

### ISSUE THREAD

**Issue by Uddeshya09** [Azure/azure-sdk-for-java#34250]
**Describe the bug**
Seems that there are issues in the refersh of token into the class com.azure.core.amqp.implementation.ActiveClientTokenManager. This issue is occurring intermittently and after this issue occurs the concerned partition gets detached and consumption from the partition is stopped.

The code is based on:

com.azure
azure-messaging-eventhubs
5.11.1

***Exception or Stack Trace***
{"az.sdk.message":"Error occurred while refreshing token that is not retriable. Not scheduling refresh task. Use ActiveClientTokenManager.authorize() to schedule task again.","exception":"Unable to open send and receive link.","scopes":"amqp://prodomscdpnamespace-alias.servicebus.windows.net/sams-oms-online-events-cdp/ConsumerGroups/elastic-wus/Partitions/4","audience":"amqp://prodomscdpnamespace-alias.servicebus.windows.net/sams-oms-online-events-cdp/ConsumerGroups/elastic-wus/Partitions/4"}

**To Reproduce**

***Code Snippet***
Add the code snippet that causes the issue.

**Expected behavior**
The expected behavior is that the token is refreshed and than is possible to use the same connection without open a new one.

**Comment by joshfree** [comment]
Thanks for filing this issue, @Uddeshya09.  @conniey please take a look

**Comment by conniey** [comment]
1. Do you have a repro for this issue?
2. Else, do you have any informational or debug logs (+/- 5 mins) we can dig into? 
 
The error itself doesn't provide enough information because the internals is like a state machine, so we need to analyse where in the state machine it stops reconnecting.

**Comment by Uddeshya09** [comment]
Hi @conniey , we don't have repro steps for this issue. 
I have shared our pod logs with Mohsin from Microsoft support team, can you please reach out to him for logs. In the meanwhile, I will also inform him to forward the logs to you.

**Comment by khan-mk56** [comment]
[logs-from-wcnp-o2s-ingestion-in-wcnp-o2s-ingestion-7df7678b69-stdzw.zip](https://github.com/Azure/azure-sdk-for-java/files/11146091/logs-from-wcnp-o2s-ingestion-in-wcnp-o2s-ingestion-7df7678b69-stdzw.zip)

@conniey Attached are the info logs.

**Comment by Uddeshya09** [comment]
Hi @conniey , any update on the above issue ?
