### ISSUE TITLE
Container Registry ReadMe Issue

### ISSUE THREAD

**Issue by hongli750210** [Azure/azure-sdk-for-java#34263]
1.
**Section** [link](https://github.com/Azure/azure-sdk-for-java/tree/main/sdk/containerregistry/azure-containers-containerregistry#sync-examples)
![image](https://user-images.githubusercontent.com/74638143/228716058-4ae5cee9-aa10-4f16-99bb-8792409bb0a4.png)

**Suggestion:**
1. Link change to `https://github.com/Azure/azure-sdk-for-java/tree/main/sdk/containerregistry/azure-containers-containerregistry#list-artifact-tags-with-anonymous-access`
2. Link change to `https://github.com/Azure/azure-sdk-for-java/tree/main/sdk/containerregistry/azure-containers-containerregistry#upload`

@joshfree, @Mohit-Chakraborty, @mario-guerra, and @alzimmermsft for notification.

**Comment by mario-guerra** [comment]
Thanks for the suggestions. Changes made:
https://github.com/Azure/azure-sdk-for-java/pull/34273
