### ISSUE TITLE
Provide doc on deprecation of a package

### ISSUE THREAD

**Issue by mario-guerra** [Azure/azure-sdk-for-java#34292]
@joshfree - filing an issue as per our Teams conversation. We need a doc that describes the steps and requirements necessary to mark a package as deprecated on Maven. The doc will be linked in our Deprecation Strategy wiki. Take a look at [this commit](https://github.com/Azure/azure-sdk-for-python/pull/29700) in the Python repo for an example.

The deprecation message should ideally follow these conventions:

For packages with a differently named replacement:
_Please note, this package has been deprecated and will no longer be maintained after <EOLDate>. We encourage you to upgrade to the replacement package, <Replace>, to continue receiving updates. Refer to the migration guide (<ReplaceGuide>) for guidance on upgrading. Refer to our deprecation policy (https://aka.ms/azsdk/support-policies ) for more details._

For packages with the same name:
_Please note, this package has been deprecated and will no longer be maintained after <EOLDate>. We encourage you to upgrade to the latest version to continue receiving updates. Refer to the migration guide (<ReplaceGuilde>) for guidance on upgrading. Refer to our deprecation policy (https://aka.ms/azsdk/support-policies ) for more details._

**Comment by joshfree** [comment]
adding it to the project board

**Comment by joshfree** [comment]
Related: https://github.com/Azure/azure-sdk-for-python/pull/29700

Also standup notes: please prioritize getting at least a PLACEHOLDER committed this week so that @mario-guerra has a doc to link against which won't 404.
