### ISSUE TITLE
Update azure-spring-cloud codeowners entries

### ISSUE THREAD

**Issue by joshfree** [Azure/azure-sdk-for-java#34326]
Tracking issue to update azure-spring-cloud codeowners file entries for 2023

<img width="974" alt="image" src="https://user-images.githubusercontent.com/1302850/229873595-5f157f4d-2bc5-4624-8783-f1e1343a248a.png">

**Comment by chenrujun** [comment]
Problem solved by adding @hui1110 into this team: https://github.com/orgs/Azure/teams/azure-sdk-push-spring/members

> ![image](https://user-images.githubusercontent.com/13167207/230258740-cecb17da-04d0-4c23-a7e0-47404c37262f.png)

Closing this issue.
