### ISSUE TITLE
How can I know if a resource is of hidden type?

### ISSUE THREAD

**Issue by maheshn99** [Azure/azure-sdk-for-java#34337]
I need to know if any of the  resources returned by the API: azureResourceManager.genericResources().list() is of hidden type. Can you please let me know how can I know that? 

Many thanks!

**Comment by weidongxu-microsoft** [comment]
@maheshn99 

Would you elaborate what do you mean by a "hidden type"?

**Comment by maheshn99** [comment]
Hello! Is there any update on this? Please prioritise implementing in the Java API a flag to denote that the resource being returned is of hidden type.

**Comment by weidongxu-microsoft** [comment]
Portal uses a huge ARG query.

Here is what you can do equivalent via Java SDK.

lib: ARG https://learn.microsoft.com/en-us/java/api/overview/azure/resourcemanager-resourcegraph-readme?view=azure-java-stable

code
```java
ResourceGraphManager m1 = ResourceGraphManager.authenticate(
        new DefaultAzureCredentialBuilder().build(),
        new AzureProfile(AzureEnvironment.AZURE));
var subscriptionId1 = "<subscription-id>";
var rgName1 = "<resource-group>";
// load the query, its too big
var query = new Scanner(Main.class.getResourceAsStream("/queryAll.txt"), StandardCharsets.UTF_8)
        .useDelimiter("\\A").next().trim()
        .replace("{rgName}", rgName1);
// query ARG
var ret = m1.resourceProviders().resources(
        new QueryRequest()
                .withSubscriptions(Collections.singletonList(subscriptionId1))
                .withQuery(query));
```

Below is 2 query file:
[queryNoHidden.txt](https://github.com/Azure/azure-sdk-for-java/files/11563706/queryNoHidden.txt)
[queryAll.txt](https://github.com/Azure/azure-sdk-for-java/files/11563705/queryAll.txt)

**Comment by maheshn99** [comment]
Thank you very much! I will give this a try.

**Comment by maheshn99** [comment]
I would like to know how can I get a list of com.azure.resourcemanager.resources.models.GenericResources from the QueryResponse. Can you please throw light on this? 

Many thanks!

**Comment by maheshn99** [comment]
Can you please throw some light on how can I get the list of GenericResources from the variable ret (QueryResponse) ? I need to iterate through each of the resources returned by the query.

Many thanks!

**Comment by weidongxu-microsoft** [comment]
@maheshn99 

I think the recommendation is to stick to ARG for related queries.

In the end of the query, there is `project name,typeDisplayName,locationDisplayName,id,type,kind,location,subscriptionId,resourceGroup,tags,extendedLocation|sort by (tolower(tostring(name))) asc`, which you can modify to return more rich date of the resource.

If you had to query via `GenericResource`, I only know how to query one by one, hence the performance would be pretty bad, if you have lots of resources.

You can try following code to query one item in the response of ARG query (assume `ret` is the response of `argManager.resourceProviders().resources` in the previous comment).

```java
var item1 = (Map<String, String>) ((List) ret.data()).get(0);
var resourceName = (String) item1.get("name");
var resourceId = (String) item1.get("id");
// percentage encode
var encodedResourceName = URLEncoder.encode(resourceName, StandardCharsets.UTF_8)
        .replace("+", "%20");
if (!Objects.equals(resourceName, encodedResourceName)) {
    resourceId = resourceId.replace("/" + resourceName, "/" + encodedResourceName);
}
GenericResource resource = azure.genericResources().getById(resourceId);
```

Note the encoding part is pretty tricky and likely incomplete (Azure resource name should be simple, without space, but some are not).

**Comment by maheshn99** [comment]
Fantastic! I was able to use the projected tags themselves being returned as part of QueryResponse. Truly appreciate your prompt help. Thank you very much. Closing this issue now.
