### ISSUE TITLE
[QUERY] Using azure-storage-blob with version 2.3 of Spring Boot

### ISSUE THREAD

**Issue by ryaneorth** [Azure/azure-sdk-for-java#34371]
**Query/Question**
I have a legacy application that is currently using version 2.3.x of Spring Boot. Updating to use a newer version of Spring Boot is planned, but for a variety of reasons is a fairly large undertaking.

In the meantime, I want to leverage the `azure-storage-blob` dependency in this application, but after testing with different versions of this dependency I always run into the same issue:

```
Exception in thread "main" java.lang.NoClassDefFoundError: reactor/util/context/ContextView
	at com.azure.core.http.policy.HttpPolicyProviders.addAfterRetryPolicies(HttpPolicyProviders.java:52)
	at com.azure.storage.blob.implementation.util.BuilderHelper.buildPipeline(BuilderHelper.java:128)
	at com.azure.storage.blob.BlobServiceClientBuilder.buildAsyncClient(BlobServiceClientBuilder.java:135)
	at com.azure.storage.blob.BlobServiceClientBuilder.buildClient(BlobServiceClientBuilder.java:114)
```

Reviewing the [Spring Version Mapping](https://aka.ms/spring/versions) I see the oldest version of Spring Boot that is referenced is 2.4.x. This maps to the azure-sdk-bom version of 1.1.1, which seems to use version [12.14.4 of azure-storage-blob](https://github.com/Azure/azure-sdk-for-java/blob/ed381e1841c303753f676c3dcd4fd94a6222062d/sdk/boms/azure-sdk-bom/pom.xml#L234)

Is there a version of azure-storage-blob prior to `12.14.4` that is known to be compatible with Spring 2.3.x?

***Why is this not a Bug or a feature Request?***
This is not a bug or a feature request because it is a general question about how to use previous versions of the SDK.

**Setup (please complete the following information if applicable):**
 - OS: macOS Ventura 13.1
 - IDE: IntelliJ
 - Library/Libraries: azure-storage-blob:?
 
 **Information Checklist**
 Kindly make sure that you have added all the following information above and checkoff the required fields otherwise we will treat the issuer as an incomplete report
- [x] Query Added
- [x] Setup information Added

**Comment by alzimmermsft** [comment]
`azure-storage-blob` `12.14.0` is the last version that should have support for Spring 2.3

**Comment by alzimmermsft** [comment]
`azure-storage-blob` `12.10.2` is the last GA version which should support Spring 2.3.x, the last `azure-sdk-bom` supporting it would be `1.0.2`.

**Comment by ryaneorth** [comment]
Great, thanks @alzimmermsft! Do you think it is worth updating the [Spring Version Mapping](https://aka.ms/spring/versions) to include these information?

**Comment by alzimmermsft** [comment]
If you were able to have that version work with Spring Boot 2.3.x I can update the mapping to include this information.

**Comment by ryaneorth** [comment]
Yes I can confirm I was able to get it working.

**Comment by alzimmermsft** [comment]
I've updated the documentation to include which version of `azure-sdk-bom` is the last to offer support for Spring Boot 2.3.x.
