### ISSUE TITLE
playfab-docs/features/analytics/data-warehouse/administration.md

### ISSUE THREAD

**Issue by TonyHCIR** [Azure/azure-sdk-for-java#34379]
playfab-docs/features/analytics/data-warehouse/administration.md

_Originally posted by @TonyHCIR in https://github.com/Vicodex/playfab-docs/pull/1_

**Comment by joshfree** [comment]
Hi @TonyHCIR playfab-docs is not in this repo.  I'm going to close this issue as well.  Feel free to provide more details and/or reactivate if I misunderstood.
