### ISSUE TITLE
where is the .cs file?

### ISSUE THREAD

**Issue by TonyHCIR** [Azure/azure-sdk-for-java#34381]
where is the .cs file?

_Originally posted by @securigy in https://github.com/Azure-Samples/cognitive-services-speech-sdk/pull/1904#issuecomment-1501316426_

_Originally posted by @TonyHCIR in https://github.com/MicrosoftDocs/azure-docs/issues/107898_

**Comment by joshfree** [comment]
Hi @TonyHCIR this is the Azure SDK for Java repo, which is not related to .NET or C#.  If you have any questions about C# and .CS files, please follow up in either the https://github.com/azure/azure-sdk-for-net or the https://github.com/dotnet/runtime github repositories.
