### ISSUE TITLE
[FEATURE REQ] Move all spring related libs to one single service directory

### ISSUE THREAD

**Issue by chenrujun** [Azure/azure-sdk-for-java#34385]
## Context

Now there are some libraries that maintained by `Spring Cloud Azure team`, but not in `sdk/spring` folder:
1. https://github.com/Azure/azure-sdk-for-java/tree/master/sdk/cosmos/azure-spring-data-cosmos 
2. https://github.com/Azure/azure-sdk-for-java/blob/main/sdk/boms/spring-cloud-azure-dependencies
3. https://github.com/Azure/azure-sdk-for-java/tree/master/sdk/keyvault/azure-security-keyvault-jca

## Problem
It's troublesome to maintain the versions and release cycle of these libraries.

## Goal
Make all `Spring Cloud Azure team` maintained libraries in `sdk/spring` folder.

## Steps
 - [x] Move `azure-spring-data-cosmos` into `sdk/spring` folder. Related PR: https://github.com/Azure/azure-sdk-for-java/pull/33905
 - [ ] Move `spring-cloud-azure-dependencies` to `sdk/spring` folder.
 - [ ] Move `azure-security-keyvault-jca` to `sdk/spring` folder.

**Comment by chenrujun** [comment]
Hi, @joshfree 

> Move azure-security-keyvault-jca to sdk/spring folder.

1. I heard from @stliu that you think there is no problem of moving `azure-security-keyvault-jca` to `sdk/spring` folder. Please confirm. 
2. How about `spring-cloud-azure-dependencies`?

**Comment by saragluna** [comment]
Closing this issue now, for we won't relocate the bom and the jca lib in short term.
