### ISSUE TITLE
[BUG] Deleting one message more than has been read

### ISSUE THREAD

**Issue by Ruby-77** [Azure/azure-sdk-for-java#34395]
**Describe the bug**
When a message is read using ServiceBusReceiverClient and there are more messages in the queue than specified by maxMessages parameter of receiveMessages method, next message is removed from the queue when close method of ServiceBusReceiverClient is invoked.

***Code Snippet***
```
try(ServiceBusReceiverClient receiver = new ServiceBusClientBuilder()
        .connectionString(CONNECTION_STRING)
        .sessionReceiver()
        .receiveMode(ServiceBusReceiveMode.RECEIVE_AND_DELETE)
        .queueName(QUEUE_NAME)
        .prefetchCount(0)
        .buildClient()
        .acceptSession(SESSION_ID)
) {
    IterableStream<ServiceBusReceivedMessage> receivedMessages = receiver.receiveMessages(1, MAX_WAIT_TIME_DURATION);
    return receivedMessages.stream().findFirst().orElse(null);
}
```

**Expected behavior**
The number of messages deleted from the queue is equal to the value of parameter maxMessages of receiveMessages method.

**Setup (please complete the following information):**
 - OS: Windows
 - IDE: 
 - Library/Libraries: com.azure:azure-messaging-servicebus:17.13.2
 - Java version: 17
 - App Server/Environment:
 - Frameworks: Spring Boot

**Comment by joshfree** [comment]
@conniey could you please follow up on @Ruby-77's github issue?

**Comment by conniey** [comment]
Thanks for reporting this. We know there are prefetch issues in the Service Bus client library that we are currently fixing (#33688).  For now, a workaround would be to use ServiceBusReceiveMode.PEEK_LOCK and explicitly complete messages (ie. disable auto-complete)

**Comment by Ruby-77** [comment]
@conniey Is this prefetch problem affecting also receiver in PEEK_LOCK mode? Is there created lock on next message when there is invoked close on receiver? And if yes, can this cause memory leaks?

**Comment by conniey** [comment]
Yes, the receiver is affected in PEEK_LOCK mode.  The difference is that lock tokens expire after a period of time, so the next receiver can refetch it.  There aren't any memory leaks associated with this.
