### ISSUE TITLE
[BUG] OOM inside Azure Service Bus sender client due to inproper memory allocation for encoded messages

### ISSUE THREAD

**Issue by somebodykirill** [Azure/azure-sdk-for-java#34426]
**Describe the bug**
On our environments we are constantly getting OutOfMemoryError inside Azure Service Bus SDK. Investigation shows that OOM happens because Azure client, when sending messages, allocates too much unnecessary space in memory. It doesn't matter how many messages are sent or their total size, the sender client always creates a byte array with the maxMessageSize of the link. We are sending events to the queue and this queue has a 'maxMessageSize' setting of 50MB. So, every time when we are trying to send a message(s) even of 10KB total, Azure SDK internals are allocating 50MB for every separate batch we send. Sometimes we can send 30-40 batches in parallel, which results in 2Gb of memory being taken up for nothing.

When we creating a batch, we are using ServiceBusSenderClient.createMessageBatch(CreateMessageBatchOptions options) method with options having maxMessageSize set to 1MB, but despite this the sender client still continues to allocate 50MB for every batch sent. It also ignores ServiceBusMessageBatch.getSizeInBytes() information (which by the way have additional reserved capacity) available in batch objects.

And moreover there is no necessity at all allocating 50MB of memory when sending more than one message. Since, according to the information available from the Azure SB documentation portal (https://learn.microsoft.com/en-us/azure/service-bus-messaging/service-bus-premium-messaging#large-messages-support), batching is not supported for large messages and batch size can be 1MB max, there absolutely no need in allocating byte array with 'maxMessageSize' of the link.

Debugging showed that when sending the batch Azure Service Bus internals inside `com.azure.core.amqp.implementation.ReactorSender` method `public Mono<Void> send(List<Message> messageBatch, DeliveryState deliveryState)` every time create byte arrays that have the same size of 50MB, while having useful data of about 50-70KB. All other contents of byte arrays are zeros.

***Exception or Stack Trace***
`java.lang.OutOfMemoryError.<init>() OutOfMemoryError.java com.azure.core.amqp.implementation.ReactorSender.lambda$send$10(List, DeliveryState, Integer) ReactorSender.java:276 com.azure.core.amqp.implementation.ReactorSender$$Lambda$4712.apply(Object) reactor.core.publisher.MonoFlatMap$FlatMapMain.onNext(Object) MonoFlatMap.java:125 reactor.core.publisher.Operators$ScalarSubscription.request(long) Operators.java:2398 reactor.core.publisher.MonoFlatMap$FlatMapMain.onSubscribe(Subscription) MonoFlatMap.java:110 reactor.core.publisher.MonoJust.subscribe(CoreSubscriber) MonoJust.java:55 reactor.core.publisher.MonoDefer.subscribe(CoreSubscriber) MonoDefer.java:52 reactor.core.publisher.Mono.subscribe(Subscriber) Mono.java:4455 reactor.core.publisher.MonoIgnorePublisher.subscribe(CoreSubscriber) MonoIgnorePublisher.java:57 reactor.core.publisher.MonoFlatMap$FlatMapMain.onNext(Object) MonoFlatMap.java:157 reactor.core.publisher.FluxPeekFuseable$PeekFuseableSubscriber.onNext(Object) FluxPeekFuseable.java:210 reactor.core.publisher.Operators$MonoSubscriber.complete(Object) Operators.java:1816 reactor.core.publisher.MonoFlatMap$FlatMapInner.onNext(Object) MonoFlatMap.java:249 reactor.core.publisher.Operators$MonoSubscriber.complete(Object) Operators.java:1816 reactor.core.publisher.MonoFlatMap$FlatMapInner.onNext(Object) MonoFlatMap.java:249 reactor.core.publisher.FluxMapFuseable$MapFuseableSubscriber.onNext(Object) FluxMapFuseable.java:129 <2 recursive calls> reactor.core.publisher.Operators$ScalarSubscription.request(long) Operators.java:2398 reactor.core.publisher.FluxMapFuseable$MapFuseableSubscriber.request(long) FluxMapFuseable.java:171 <2 recursive calls> reactor.core.publisher.MonoFlatMap$FlatMapInner.onSubscribe(Subscription) MonoFlatMap.java:238 reactor.core.publisher.FluxMapFuseable$MapFuseableSubscriber.onSubscribe(Subscription) FluxMapFuseable.java:96 <2 recursive calls> reactor.core.publisher.MonoJust.subscribe(CoreSubscriber) MonoJust.java:55 reactor.core.publisher.InternalMonoOperator.subscribe(CoreSubscriber) InternalMonoOperator.java:64 reactor.core.publisher.MonoFlatMap$FlatMapMain.onNext(Object) MonoFlatMap.java:157 reactor.core.publisher.FluxMapFuseable$MapFuseableSubscriber.onNext(Object) FluxMapFuseable.java:129 reactor.core.publisher.Operators$MonoSubscriber.complete(Object) Operators.java:1816 reactor.core.publisher.MonoFlatMap$FlatMapInner.onNext(Object) MonoFlatMap.java:249 reactor.core.publisher.MonoIgnoreThen$ThenIgnoreMain.complete(Object) MonoIgnoreThen.java:292 reactor.core.publisher.MonoIgnoreThen$ThenIgnoreMain.onNext(Object) MonoIgnoreThen.java:187 reactor.core.publisher.MonoIgnoreThen$ThenIgnoreMain.subscribeNext() MonoIgnoreThen.java:236 reactor.core.publisher.MonoIgnoreThen$ThenIgnoreMain.onComplete() MonoIgnoreThen.java:203 reactor.core.publisher.SerializedSubscriber.onComplete() SerializedSubscriber.java:146 <2 recursive calls> reactor.core.publisher.FluxTimeout$TimeoutMainSubscriber.onComplete() FluxTimeout.java:234 reactor.core.publisher.MonoNext$NextSubscriber.onComplete() MonoNext.java:102 reactor.core.publisher.MonoNext$NextSubscriber.onNext(Object) MonoNext.java:83 reactor.core.publisher.FluxFilterFuseable$FilterFuseableSubscriber.onNext(Object) FluxFilterFuseable.java:118 reactor.core.publisher.FluxReplay$SizeBoundReplayBuffer.replayNormal(FluxReplay$ReplaySubscription) FluxReplay.java:877 reactor.core.publisher.FluxReplay$SizeBoundReplayBuffer.replay(FluxReplay$ReplaySubscription) FluxReplay.java:965 reactor.core.publisher.FluxReplay$ReplayInner.request(long) FluxReplay.java:1711 reactor.core.publisher.FluxFilterFuseable$FilterFuseableSubscriber.request(long) FluxFilterFuseable.java:191 reactor.core.publisher.MonoNext$NextSubscriber.request(long) MonoNext.java:108 reactor.core.publisher.Operators$MultiSubscriptionSubscriber.request(long) Operators.java:2158 reactor.core.publisher.SerializedSubscriber.request(long) SerializedSubscriber.java:151 <2 recursive calls> reactor.core.publisher.MonoIgnoreThen$ThenIgnoreMain.onSubscribe(Subscription) MonoIgnoreThen.java:134 reactor.core.publisher.SerializedSubscriber.onSubscribe(Subscription) SerializedSubscriber.java:65 <2 recursive calls> reactor.core.publisher.FluxTimeout$TimeoutMainSubscriber.onSubscribe(Subscription) FluxTimeout.java:154 reactor.core.publisher.MonoNext$NextSubscriber.onSubscribe(Subscription) MonoNext.java:70 reactor.core.publisher.FluxFilterFuseable$FilterFuseableSubscriber.onSubscribe(Subscription) FluxFilterFuseable.java:87 reactor.core.publisher.FluxReplay.subscribeOrReturn(CoreSubscriber) FluxReplay.java:1181 reactor.core.publisher.FluxReplay.subscribe(CoreSubscriber) FluxReplay.java:1153 reactor.core.publisher.FluxAutoConnectFuseable.subscribe(CoreSubscriber) FluxAutoConnectFuseable.java:61 reactor.core.publisher.Mono.subscribe(Subscriber) Mono.java:4455 reactor.core.publisher.MonoIgnoreThen$ThenIgnoreMain.subscribeNext() MonoIgnoreThen.java:263 reactor.core.publisher.MonoIgnoreThen.subscribe(CoreSubscriber) MonoIgnoreThen.java:51 reactor.core.publisher.MonoFlatMap$FlatMapMain.onNext(Object) MonoFlatMap.java:157 reactor.core.publisher.FluxMapFuseable$MapFuseableSubscriber.onNext(Object) FluxMapFuseable.java:129 reactor.core.publisher.MonoPeekTerminal$MonoTerminalPeekSubscriber.onNext(Object) MonoPeekTerminal.java:180 reactor.core.publisher.FluxHide$SuppressFuseableSubscriber.onNext(Object) FluxHide.java:137 reactor.core.publisher.MonoIgnoreThen$ThenIgnoreMain.complete(Object) MonoIgnoreThen.java:292 reactor.core.publisher.MonoIgnoreThen$ThenIgnoreMain.onNext(Object) MonoIgnoreThen.java:187 reactor.core.publisher.MonoIgnoreThen$ThenIgnoreMain.subscribeNext() MonoIgnoreThen.java:236 reactor.core.publisher.MonoIgnoreThen$ThenIgnoreMain.onComplete() MonoIgnoreThen.java:203 reactor.core.publisher.SerializedSubscriber.onComplete() SerializedSubscriber.java:146 <2 recursive calls> reactor.core.publisher.FluxTimeout$TimeoutMainSubscriber.onComplete() FluxTimeout.java:234 reactor.core.publisher.MonoNext$NextSubscriber.onComplete() MonoNext.java:102 reactor.core.publisher.MonoNext$NextSubscriber.onNext(Object) MonoNext.java:83 reactor.core.publisher.FluxFilterFuseable$FilterFuseableSubscriber.onNext(Object) FluxFilterFuseable.java:118 reactor.core.publisher.FluxReplay$SizeBoundReplayBuffer.replayNormal(FluxReplay$ReplaySubscription) FluxReplay.java:877 reactor.core.publisher.FluxReplay$SizeBoundReplayBuffer.replay(FluxReplay$ReplaySubscription) FluxReplay.java:965 reactor.core.publisher.FluxReplay$ReplayInner.request(long) FluxReplay.java:1711 reactor.core.publisher.FluxFilterFuseable$FilterFuseableSubscriber.request(long) FluxFilterFuseable.java:191 reactor.core.publisher.MonoNext$NextSubscriber.request(long) MonoNext.java:108 reactor.core.publisher.Operators$MultiSubscriptionSubscriber.request(long) Operators.java:2158 reactor.core.publisher.SerializedSubscriber.request(long) SerializedSubscriber.java:151 <2 recursive calls> reactor.core.publisher.MonoIgnoreThen$ThenIgnoreMain.onSubscribe(Subscription) MonoIgnoreThen.java:134 reactor.core.publisher.SerializedSubscriber.onSubscribe(Subscription) SerializedSubscriber.java:65 <2 recursive calls> reactor.core.publisher.FluxTimeout$TimeoutMainSubscriber.onSubscribe(Subscription) FluxTimeout.java:154 reactor.core.publisher.MonoNext$NextSubscriber.onSubscribe(Subscription) MonoNext.java:70 reactor.core.publisher.FluxFilterFuseable$FilterFuseableSubscriber.onSubscribe(Subscription) FluxFilterFuseable.java:87 reactor.core.publisher.FluxReplay.subscribeOrReturn(CoreSubscriber) FluxReplay.java:1181 reactor.core.publisher.FluxReplay.subscribe(CoreSubscriber) FluxReplay.java:1153 reactor.core.publisher.FluxAutoConnectFuseable.subscribe(CoreSubscriber) FluxAutoConnectFuseable.java:61 reactor.core.publisher.Mono.subscribe(Subscriber) Mono.java:4455 reactor.core.publisher.MonoIgnoreThen$ThenIgnoreMain.subscribeNext() MonoIgnoreThen.java:263 reactor.core.publisher.MonoIgnoreThen.subscribe(CoreSubscriber) MonoIgnoreThen.java:51 reactor.core.publisher.Mono.subscribe(Subscriber) Mono.java:4455 reactor.core.publisher.FluxFlatMap.trySubscribeScalarMap(Publisher, CoreSubscriber, Function, boolean, boolean) FluxFlatMap.java:203 reactor.core.publisher.MonoFlatMap.subscribeOrReturn(CoreSubscriber) MonoFlatMap.java:53 reactor.core.publisher.InternalMonoOperator.subscribe(CoreSubscriber) InternalMonoOperator.java:57 reactor.core.publisher.MonoFlatMap$FlatMapMain.onNext(Object) MonoFlatMap.java:157 reactor.core.publisher.Operators$MonoSubscriber.complete(Object) Operators.java:1816 com.azure.core.amqp.implementation.AmqpChannelProcessor.subscribe(CoreSubscriber) AmqpChannelProcessor.java:264 reactor.core.publisher.InternalMonoOperator.subscribe(CoreSubscriber) InternalMonoOperator.java:64 reactor.core.publisher.FluxRetryWhen$RetryWhenMainSubscriber.resubscribe(Object) FluxRetryWhen.java:216 reactor.core.publisher.FluxRetryWhen$RetryWhenOtherSubscriber.onNext(Object) FluxRetryWhen.java:269 reactor.core.publisher.FluxConcatMap$ConcatMapImmediate.innerNext(Object) FluxConcatMap.java:282 reactor.core.publisher.FluxConcatMap$ConcatMapInner.onNext(Object) FluxConcatMap.java:863 reactor.core.publisher.Operators$MonoSubscriber.complete(Object) Operators.java:1816 reactor.core.publisher.MonoFlatMap$FlatMapInner.onNext(Object) MonoFlatMap.java:249 reactor.core.publisher.MonoIgnoreThen$ThenIgnoreMain.complete(Object) MonoIgnoreThen.java:292 reactor.core.publisher.MonoIgnoreThen$ThenIgnoreMain.onNext(Object) MonoIgnoreThen.java:187 reactor.core.publisher.MonoIgnoreThen$ThenIgnoreMain.subscribeNext() MonoIgnoreThen.java:236 reactor.core.publisher.MonoIgnoreThen.subscribe(CoreSubscriber) MonoIgnoreThen.java:51 reactor.core.publisher.MonoFlatMap$FlatMapMain.onNext(Object) MonoFlatMap.java:157 reactor.core.publisher.MonoIgnoreThen$ThenIgnoreMain.complete(Object) MonoIgnoreThen.java:292 reactor.core.publisher.MonoIgnoreThen$ThenIgnoreMain.onNext(Object) MonoIgnoreThen.java:187 reactor.core.publisher.MonoDelay$MonoDelayRunnable.propagateDelay() MonoDelay.java:271 reactor.core.publisher.MonoDelay$MonoDelayRunnable.run() MonoDelay.java:286 reactor.core.scheduler.SchedulerTask.call() SchedulerTask.java:68 reactor.core.scheduler.SchedulerTask.call() SchedulerTask.java:28 java.util.concurrent.FutureTask.run() FutureTask.java:264 java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run() ScheduledThreadPoolExecutor.java:304 java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor$Worker) ThreadPoolExecutor.java:1128 java.util.concurrent.ThreadPoolExecutor$Worker.run() ThreadPoolExecutor.java:628 java.lang.Thread.run() Thread.java:829 `

**To Reproduce**
1. Set Java max heap size to 1GB
2. Create the queue with the setting of `maxMessageSize` of 100MB in Premium Tier namespace.
3. Create 50 message batches each having 10 messages and total size of 10KB. Optionally, when creating the batches set batch options with `maxMessageSize` = 1MB
4. Send them in parallel threads.
5. Wait for OOM 
or 
just check byte arrays (`bytes` variable inside public `Mono<Void> send(List<Message> messageBatch, DeliveryState deliveryState)` method of `com.azure.core.amqp.implementation.ReactorSender` class) and see that every `bytes` array have size of 104857600 bytes while `byteArrayOffset` is about 10800.

***Code Snippet***
```
public class SendMessageBatchOOM {

    private static final int MAX_MESSAGE_SIZE_KB = 100 * 1024; //100MB
    private static final String CONNECTION_STRING = "";

    public static void main(String[] args) {

        ExecutorService executor = Executors.newFixedThreadPool(20);

        try {
            final ServiceBusAdministrationClient administrationClient = new ServiceBusAdministrationClientBuilder()
                    .connectionString(CONNECTION_STRING)
                    .buildClient();

            String queueName = "a_queue_for_oom_problem";
            if (administrationClient.getQueueExists(queueName)) {
                administrationClient.deleteQueue(queueName);
            }

            CreateQueueOptions createQueueOptions = new CreateQueueOptions()
                    .setMaxMessageSizeInKilobytes(MAX_MESSAGE_SIZE_KB);

            administrationClient.createQueue(queueName, createQueueOptions);

            try (ServiceBusSenderClient senderClient = new ServiceBusClientBuilder()
                    .connectionString(CONNECTION_STRING)
                    .sender()
                    .queueName(queueName)
                    .buildClient()) {

                CreateMessageBatchOptions batchOptions = new CreateMessageBatchOptions()
                        .setMaximumSizeInBytes(1024 * 1024); // 1MB

                List<ServiceBusMessageBatch> batches = createBatches(senderClient, batchOptions, 50);

                List<CompletableFuture<Void>> futures = new ArrayList<>();
                for (ServiceBusMessageBatch batch : batches) {
                    CompletableFuture<Void> future = CompletableFuture.runAsync(() -> senderClient.sendMessages(batch), executor);
                    futures.add(future);
                }

                CompletableFuture.allOf(futures.toArray(new CompletableFuture[]{})).join();
            }
        } catch (Exception e) {
            System.err.println(e.getMessage());
        } finally {
            executor.shutdown();
        }
    }

    private static List<ServiceBusMessageBatch> createBatches(ServiceBusSenderClient senderClient, CreateMessageBatchOptions batchOptions, int numBatches) {
        List<ServiceBusMessageBatch> batches = new ArrayList<>();

        for (int i = 0; i < numBatches; i++) {
            ServiceBusMessageBatch messageBatch = senderClient.createMessageBatch(batchOptions);
            List<ServiceBusMessage> listOfMessages = createMessages(10, 1024);

            for (ServiceBusMessage message : listOfMessages) {
                messageBatch.tryAddMessage(message);
            }

            batches.add(messageBatch);
        }

        return batches;
    }

    private static List<ServiceBusMessage> createMessages(int numOfMessages, int messageSize) {
        List<ServiceBusMessage> messages = new ArrayList<>();
        for (int j = 0; j < numOfMessages; j++) {
            String messageId = UUID.randomUUID().toString();
            int messageIdSize = messageId.getBytes(StandardCharsets.UTF_8).length;
            String messageBody = RandomStringUtils.random(messageSize - messageIdSize, true, false);
            ServiceBusMessage message = new ServiceBusMessage(messageBody)
                    .setMessageId(messageId);
            messages.add(message);
        }

        return messages;
    }
}
```

**Expected behavior**
Sender client allocates only the necessary amount of memory for every batch.
As fast simple solution at least not to allocate more than 1MB when we send more than 1 message, as we under no circumstances cannot send multiple messages exceeding 1MB, because batching is not supported for large messages.

**Screenshots**
Here the example of heap dumps from our production environment having OOM issue
![OOM_1](https://user-images.githubusercontent.com/117357651/231512066-562c9b47-452c-4349-92a9-149cd7fe16bf.png)
![OOM_2](https://user-images.githubusercontent.com/117357651/231512093-f367d045-8a38-410d-8350-6a915011657e.png)
![OOM_3](https://user-images.githubusercontent.com/117357651/231512130-82b958f9-8d8a-43c1-9776-c265ce9b44d8.png)
![OOM_4](https://user-images.githubusercontent.com/117357651/231517319-01778618-84c7-4c1e-abb5-1b629f7d4dfe.png)

As you can see on the first three screenshots each byte array has the same size of 50MB (value of `maxMessageSize` property of the queue), while having useful data of about 50-70KB. All other contents of byte arrays are zeros.

Last screenshot is from the local reproduction of the problem in Intellij IDEA for the queue that has `maxMessageSize` setting of 100MB. You can see a similar picture with 100MB byte array and only 10KB of actual data in it and the rest of data in array are just zeroes needlessly consuming memory.

**Setup (please complete the following information):**
 - Library/Libraries: com.azure:azure-messaging-servicebus:7.13.3
 - Java version: 11

**Comment by joshfree** [comment]
Thank you for the detailed github issue, @somebodykirill.  @anuchandy (/cc @Azure/azsdk-sb-java) will follow up with you shortly.

Please note that if your problem requires immediate attention that we recommend an Azure support ticket: https://github.com/Azure/azure-sdk-for-java/blob/main/SUPPORT.md#azure-support-tickets

**Comment by anuchandy** [comment]
This is completed in the PR https://github.com/Azure/azure-sdk-for-java/pull/34591 and shipped in the May-2023 release.

**Comment by anuchandy** [comment]
Fix is shipped and closing the issue.
