### ISSUE TITLE
[FEATURE REQ] Support asynchronuous calls in `azure-resourcemanager-postgresqlflexibleserver`

### ISSUE THREAD

**Issue by dennis-benzinger-hybris** [Azure/azure-sdk-for-java#34424]
**Is your feature request related to a problem? Please describe.**
The `azure-resourcemanager-postgresqlflexibleserver` supports only synchronous calls.  

**Describe the solution you'd like**
Also support asynchronous calls. 

**Additional context**
The SDKs for other resource types also support async calls.

**Information Checklist**
Kindly make sure that you have added all the following information above and checkoff the required fields otherwise we will treat the issuer as an incomplete report
- [x] Description Added
- [x] Expected solution specified

**Comment by joshfree** [comment]
@weidongxu-microsoft could you please follow up with @dennis-benzinger-hybris on this github issue

**Comment by weidongxu-microsoft** [comment]
@dennis-benzinger-hybris 

Would you give us one sample of "The SDKs for other resource types also support async calls."? We just want to make sure we are on the same page.

We have a scheduled postgresqlflexibleserver lib release this month.

**Comment by dennis-benzinger-hybris** [comment]
> Would you give us one sample of "The SDKs for other resource types also support async calls."? We just want to make sure we are on the same page (aka the Reactor async calls).

For example, the `azure-resourcemanager-privatedns` SDK has a `createAsync()` call.

**Comment by weidongxu-microsoft** [comment]
@dennis-benzinger-hybris 

Our current solution is to expose the async at serviceClient level, e.g.
https://github.com/Azure/azure-sdk-for-java/blob/main/sdk/desktopvirtualization/azure-resourcemanager-desktopvirtualization/src/main/java/com/azure/resourcemanager/desktopvirtualization/fluent/ApplicationsClient.java#L90-L92

So you'd need to call e.g.
```java
manager.serviceClient().getDatabase().createOrUpdate(...)
```

Is it OK for you?

We can enable it in April release.

**Comment by dennis-benzinger-hybris** [comment]
Yes, that would work 👍🏻 .

**Comment by weidongxu-microsoft** [comment]
Sorry, @dennis-benzinger-hybris , this release is not yet out.

We got a release pipeline problem last month, and not yet get solved. Still communicating.
(ironically, the reason is that the package name of azure-resourcemanager-postgresqlflexibleserver is too long for one step...)

**Comment by dennis-benzinger-hybris** [comment]
Can you estimate when the release will happen?

**Comment by weidongxu-microsoft** [comment]
@dennis-benzinger-hybris 

Finally, https://central.sonatype.com/artifact/com.azure.resourcemanager/azure-resourcemanager-postgresqlflexibleserver/1.0.0-beta.6
