### ISSUE TITLE
[BUG] `CrudRepository.save(..)` failed. Got a 404 NotFound

### ISSUE THREAD

**Issue by domainname** [Azure/azure-sdk-for-java#34438]
**Describe the bug**
After we upgrade `azure-spring-data-cosmos` from 3.30.0 to 3.33.0, we ran into this error when invoking `CrudRepository.save(..)` to persist a newly-created entity. See the exception below. So, we had to roll back to 3.30.0, with which the error goes away.

***Exception or Stack Trace***
com.azure.spring.data.cosmos.exception.CosmosAccessException: Failed to upsert item; nested exception is {"ClassName":"CosmosException","userAgent":"azsdk-java-cosmos/4.42.0 Linux/5.4.0-1103-azure JRE/11.0.18","statusCode":404,"resourceAddress":"https://***.documents.azure.com:443/dbs/****/colls/****","error":"{\"code\":\"NotFound\",\"message\":\"Message: {\\\"Errors\\\":[\\\"Resource Not Found. Learn more: https:\\\\/\\\\/aka.ms\\\\/cosmosdb-tsg-not-found\\\"]}\\r\\nActivityId: 6f226245-298e-4975-afab-e5d3e0383c2c, Request URI: /apps/41f52872-9300-4928-b18e-d15ad2e4d29b/services/10a67a68-87f9-490e-bd73-b6c40fa72956/partitions/dd353fe8-219a-4dfa-8cc0-dc67b3686f55/replicas/132839721753710598s, RequestStats: \\r\\nRequestStartTime: 2023-04-10T08:08:41.3365508Z, RequestEndTime: 2023-04-10T08:08:41.3365508Z,  Number of regions attempted:1\\r\\n{\\\"systemHistory\\\":[{\\\"dateUtc\\\":\\\"2023-04-10T08:07:26.0049359Z\\\",\\\"cpu\\\":0.788,\\\"memory\\\":487745112.000,\\\"threadInfo\\\":{\\\"isThreadStarving\\\":\\\"False\\\",\\\"threadWaitIntervalInMs\\\":0.0168,\\\"availableThreads\\\":32763,\\\"minThreads\\\":52,\\\"maxThreads\\\":32767},\\\"numberOfOpenTcpConnection\\\":165},{\\\"dateUtc\\\":\\\"2023-04-10T08:07:36.0051993Z\\\",\\\"cpu\\\":0.336,\\\"memory\\\":487748444.000,\\\"threadInfo\\\":{\\\"isThreadStarving\\\":\\\"False\\\",\\\"threadWaitIntervalInMs\\\":0.0343,\\\"availableThreads\\\":32731,\\\"minThreads\\\":52,\\\"maxThreads\\\":32767},\\\"numberOfOpenTcpConnection\\\":165},{\\\"dateUtc\\\":\\\"2023-04-10T08:07:46.0153962Z\\\",\\\"cpu\\\":0.592,\\\"memory\\\":487743636.000,\\\"threadInfo\\\":{\\\"isThreadStarving\\\":\\\"False\\\",\\\"threadWaitIntervalInMs\\\":0.0115,\\\"availableThreads\\\":32764,\\\"minThreads\\\":52,\\\"maxThreads\\\":32767},\\\"numberOfOpenTcpConnection\\\":165},{\\\"dateUtc\\\":\\\"2023-04-10T08:08:06.0258365Z\\\",\\\"cpu\\\":0.640,\\\"memory\\\":487464420.000,\\\"threadInfo\\\":{\\\"isThreadStarving\\\":\\\"False\\\",\\\"threadWaitIntervalInMs\\\":0.041,\\\"availableThreads\\\":32764,\\\"minThreads\\\":52,\\\"maxThreads\\\":32767},\\\"numberOfOpenTcpConnection\\\":165},{\\\"dateUtc\\\":\\\"2023-04-10T08:08:16.0360005Z\\\",\\\"cpu\\\":0.309,\\\"memory\\\":487699308.000,\\\"threadInfo\\\":{\\\"isThreadStarving\\\":\\\"False\\\",\\\"threadWaitIntervalInMs\\\":0.0253,\\\"availableThreads\\\":32691,\\\"minThreads\\\":52,\\\"maxThreads\\\":32767},\\\"numberOfOpenTcpConnection\\\":165},{\\\"dateUtc\\\":\\\"2023-04-10T08:08:36.0464783Z\\\",\\\"cpu\\\":0.715,\\\"memory\\\":487746952.000,\\\"threadInfo\\\":{\\\"isThreadStarving\\\":\\\"False\\\",\\\"threadWaitIntervalInMs\\\":0.0109,\\\"availableThreads\\\":32740,\\\"minThreads\\\":52,\\\"maxThreads\\\":32767},\\\"numberOfOpenTcpConnection\\\":166}]}\\r\\nRequestStart: 2023-04-10T08:08:41.3365508Z; ResponseTime: 2023-04-10T08:08:41.3365508Z; StoreResult: StorePhysicalAddress: rntbd://10.0.0.49:11000/apps/41f52872-9300-4928-b18e-d15ad2e4d29b/services/10a67a68-87f9-490e-bd73-b6c40fa72956/partitions/dd353fe8-219a-4dfa-8cc0-dc67b3686f55/replicas/132839721753710598s, LSN: 7628, GlobalCommittedLsn: 7628, PartitionKeyRangeId: , IsValid: True, StatusCode: 404, SubStatusCode: 0, RequestCharge: 1, ItemLSN: -1, SessionToken: -1#7628, UsingLocalLSN: False, TransportException: null, BELatencyMs: 0.265, ActivityId: 6f226245-298e-4975-afab-e5d3e0383c2c, RetryAfterInMs: , TransportRequestTimeline: {\\\"requestTimeline\\\":[{\\\"event\\\": \\\"Created\\\", \\\"startTimeUtc\\\": \\\"2023-04-10T08:08:41.3365508Z\\\", \\\"durationInMs\\\": 0.0088},{\\\"event\\\": \\\"ChannelAcquisitionStarted\\\", \\\"startTimeUtc\\\": \\\"2023-04-10T08:08:41.3365596Z\\\", \\\"durationInMs\\\": 0.0022},{\\\"event\\\": \\\"Pipelined\\\", \\\"startTimeUtc\\\": \\\"2023-04-10T08:08:41.3365618Z\\\", \\\"durationInMs\\\": 0.0789},{\\\"event\\\": \\\"Transit Time\\\", \\\"startTimeUtc\\\": \\\"2023-04-10T08:08:41.3366407Z\\\", \\\"durationInMs\\\": 1.3054},{\\\"event\\\": \\\"Received\\\", \\\"startTimeUtc\\\": \\\"2023-04-10T08:08:41.3379461Z\\\", \\\"durationInMs\\\": 0.021},{\\\"event\\\": \\\"Completed\\\", \\\"startTimeUtc\\\": \\\"2023-04-10T08:08:41.3379671Z\\\", \\\"durationInMs\\\": 0}],\\\"serviceEndpointStats\\\":{\\\"inflightRequests\\\":1,\\\"openConnections\\\":1},\\\"connectionStats\\\":{\\\"waitforConnectionInit\\\":\\\"False\\\",\\\"callsPendingReceive\\\":0,\\\"lastSendAttempt\\\":\\\"2023-04-10T08:08:41.3365508Z\\\",\\\"lastSend\\\":\\\"2023-04-10T08:08:41.3365508Z\\\",\\\"lastReceive\\\":\\\"2023-04-10T08:08:41.3365508Z\\\"},\\\"requestSizeInBytes\\\":492,\\\"responseMetadataSizeInBytes\\\":137,\\\"responseBodySizeInBytes\\\":87};\\r\\n ResourceType: Collection, OperationType: Read\\r\\nRequestStart: 2023-04-10T08:08:41.3365508Z; ResponseTime: 2023-04-10T08:08:41.3365508Z; StoreResult: StorePhysicalAddress: rntbd://10.0.0.9:11300/apps/41f52872-9300-4928-b18e-d15ad2e4d29b/services/10a67a68-87f9-490e-bd73-b6c40fa72956/partitions/dd353fe8-219a-4dfa-8cc0-dc67b3686f55/replicas/132772599043365230s, LSN: 7628, GlobalCommittedLsn: 7628, PartitionKeyRangeId: , IsValid: True, StatusCode: 404, SubStatusCode: 0, RequestCharge: 1, ItemLSN: -1, SessionToken: -1#7628, UsingLocalLSN: False, TransportException: null, BELatencyMs: 0.242, ActivityId: 6f226245-298e-4975-afab-e5d3e0383c2c, RetryAfterInMs: , TransportRequestTimeline: {\\\"requestTimeline\\\":[{\\\"event\\\": \\\"Created\\\", \\\"startTimeUtc\\\": \\\"2023-04-10T08:08:41.3365508Z\\\", \\\"durationInMs\\\": 0.0047},{\\\"event\\\": \\\"ChannelAcquisitionStarted\\\", \\\"startTimeUtc\\\": \\\"2023-04-10T08:08:41.3365555Z\\\", \\\"durationInMs\\\": 0.0064},{\\\"event\\\": \\\"Pipelined\\\", \\\"startTimeUtc\\\": \\\"2023-04-10T08:08:41.3365619Z\\\", \\\"durationInMs\\\": 0.0689},{\\\"event\\\": \\\"Transit Time\\\", \\\"startTimeUtc\\\": \\\"2023-04-10T08:08:41.3366308Z\\\", \\\"durationInMs\\\": 0.6315},{\\\"event\\\": \\\"Received\\\", \\\"startTimeUtc\\\": \\\"2023-04-10T08:08:41.3372623Z\\\", \\\"durationInMs\\\": 0.031},{\\\"event\\\": \\\"Completed\\\", \\\"startTimeUtc\\\": \\\"2023-04-10T08:08:41.3372933Z\\\", \\\"durationInMs\\\": 0}],\\\"serviceEndpointStats\\\":{\\\"inflightRequests\\\":1,\\\"openConnections\\\":1},\\\"connectionStats\\\":{\\\"waitforConnectionInit\\\":\\\"False\\\",\\\"callsPendingReceive\\\":0,\\\"lastSendAttempt\\\":\\\"2023-04-10T08:08:38.7865599Z\\\",\\\"lastSend\\\":\\\"2023-04-10T08:08:38.7865599Z\\\",\\\"lastReceive\\\":\\\"2023-04-10T08:08:38.7865599Z\\\"},\\\"requestSizeInBytes\\\":492,\\\"responseMetadataSizeInBytes\\\":137,\\\"responseBodySizeInBytes\\\":87};\\r\\n ResourceType: Collection, OperationType: Read\\r\\n, SDK: Microsoft.Azure.Documents.Common/2.14.0, StatusCode: NotFound\",\"additionalErrorInfo\":null}","innerErrorMessage":"Message: {\"Errors\":[\"Resource Not Found. Learn more: https:\\/\\/aka.ms\\/cosmosdb-tsg-not-found\"]}\r\nActivityId: 6f226245-298e-4975-afab-e5d3e0383c2c, Request URI: /apps/41f52872-9300-4928-b18e-d15ad2e4d29b/services/10a67a68-87f9-490e-bd73-b6c40fa72956/partitions/dd353fe8-219a-4dfa-8cc0-dc67b3686f55/replicas/132839721753710598s, RequestStats: \r\nRequestStartTime: 2023-04-10T08:08:41.3365508Z, RequestEndTime: 2023-04-10T08:08:41.3365508Z,  Number of regions attempted:1\r\n{\"systemHistory\":[{\"dateUtc\":\"2023-04-10T08:07:26.0049359Z\",\"cpu\":0.788,\"memory\":487745112.000,\"threadInfo\":{\"isThreadStarving\":\"False\",\"threadWaitIntervalInMs\":0.0168,\"availableThreads\":32763,\"minThreads\":52,\"maxThreads\":32767},\"numberOfOpenTcpConnection\":165},{\"dateUtc\":\"2023-04-10T08:07:36.0051993Z\",\"cpu\":0.336,\"memory\":487748444.000,\"threadInfo\":{\"isThreadStarving\":\"False\",\"threadWaitIntervalInMs\":0.0343,\"availableThreads\":32731,\"minThreads\":52,\"maxThreads\":32767},\"numberOfOpenTcpConnection\":165},{\"dateUtc\":\"2023-04-10T08:07:46.0153962Z\",\"cpu\":0.592,\"memory\":487743636.000,\"threadInfo\":{\"isThreadStarving\":\"False\",\"threadWaitIntervalInMs\":0.0115,\"availableThreads\":32764,\"minThreads\":52,\"maxThreads\":32767},\"numberOfOpenTcpConnection\":165},{\"dateUtc\":\"2023-04-10T08:08:06.0258365Z\",\"cpu\":0.640,\"memory\":487464420.000,\"threadInfo\":{\"isThreadStarving\":\"False\",\"threadWaitIntervalInMs\":0.041,\"availableThreads\":32764,\"minThreads\":52,\"maxThreads\":32767},\"numberOfOpenTcpConnection\":165},{\"dateUtc\":\"2023-04-10T08:08:16.0360005Z\",\"cpu\":0.309,\"memory\":487699308.000,\"threadInfo\":{\"isThreadStarving\":\"False\",\"threadWaitIntervalInMs\":0.0253,\"availableThreads\":32691,\"minThreads\":52,\"maxThreads\":32767},\"numberOfOpenTcpConnection\":165},{\"dateUtc\":\"2023-04-10T08:08:36.0464783Z\",\"cpu\":0.715,\"memory\":487746952.000,\"threadInfo\":{\"isThreadStarving\":\"False\",\"threadWaitIntervalInMs\":0.0109,\"availableThreads\":32740,\"minThreads\":52,\"maxThreads\":32767},\"numberOfOpenTcpConnection\":166}]}\r\nRequestStart: 2023-04-10T08:08:41.3365508Z; ResponseTime: 2023-04-10T08:08:41.3365508Z; StoreResult: StorePhysicalAddress: rntbd://10.0.0.49:11000/apps/41f52872-9300-4928-b18e-d15ad2e4d29b/services/10a67a68-87f9-490e-bd73-b6c40fa72956/partitions/dd353fe8-219a-4dfa-8cc0-dc67b3686f55/replicas/132839721753710598s, LSN: 7628, GlobalCommittedLsn: 7628, PartitionKeyRangeId: , IsValid: True, StatusCode: 404, SubStatusCode: 0, RequestCharge: 1, ItemLSN: -1, SessionToken: -1#7628, UsingLocalLSN: False, TransportException: null, BELatencyMs: 0.265, ActivityId: 6f226245-298e-4975-afab-e5d3e0383c2c, RetryAfterInMs: , TransportRequestTimeline: {\"requestTimeline\":[{\"event\": \"Created\", \"startTimeUtc\": \"2023-04-10T08:08:41.3365508Z\", \"durationInMs\": 0.0088},{\"event\": \"ChannelAcquisitionStarted\", \"startTimeUtc\": \"2023-04-10T08:08:41.3365596Z\", \"durationInMs\": 0.0022},{\"event\": \"Pipelined\", \"startTimeUtc\": \"2023-04-10T08:08:41.3365618Z\", \"durationInMs\": 0.0789},{\"event\": \"Transit Time\", \"startTimeUtc\": \"2023-04-10T08:08:41.3366407Z\", \"durationInMs\": 1.3054},{\"event\": \"Received\", \"startTimeUtc\": \"2023-04-10T08:08:41.3379461Z\", \"durationInMs\": 0.021},{\"event\": \"Completed\", \"startTimeUtc\": \"2023-04-10T08:08:41.3379671Z\", \"dura...

**To Reproduce**

***Code Snippet***
```java
ourRepository.save(entity);
```

**Expected behavior**

**Screenshots**

**Setup (please complete the following information):**
 - OS: Windows
 - IDE: IntelliJ
 - Library/Libraries: com.azure:azure-spring-data-cosmos:3.33.0
 - Java version: 11
 - App Server/Environment: Tomcat
 - Frameworks: Spring Boot

**Additional context**
N/A

**Information Checklist**
Kindly make sure that you have added all the following information above and checkoff the required fields otherwise we will treat the issuer as an incomplete report
- [ ] Bug Description Added
- [ ] Repro Steps Added
- [ ] Setup information Added

**Comment by domainname** [comment]
@kushagraThapar Let's talk offline.

**Comment by kushagraThapar** [comment]
@trande4884   can you please take a look at this, looks like something changed between 3.30.0 and 3.33.0. @domainname can you please reach out to Trevor for this, thanks!

**Comment by kushagraThapar** [comment]
@trande4884  - FYI, actually this might be related to multi-tenancy support via CosmosFactory. Worth looking into that as well, thanks!

**Comment by trande4884** [comment]
@domainname can you provide the config you are using to build the cosmos client?

**Comment by trande4884** [comment]
So you have a parent class 'Certificate' with two child classes 'KeyVaultCertificate' and 'ContentCertificate'. When you were calling save with a KeyVaultCertificate in the past it was saving simply to the 'Certificate' container. With the new release that includes enhancements to CosmosTemplate to support multi-tenancy the database name is pulled on the fly which is KeyVaultCertificate, which is actually the correct thing for the code to do. Your worked around to this of defining @Container(containerName = "Certificate") on the parent class Certificate is going to be the new way of achieving your end goal. There was actually a bug in CosmosTemplate in the past with the way the database name was set once at the beginning instead of being found on the fly as we do now.

Let me know if you have any questions/issues with this.
