### ISSUE TITLE
[BUG] tsp script, avoid overwrite emitter-output-dir

### ISSUE THREAD

**Issue by weidongxu-microsoft** [Azure/azure-sdk-for-java#34439]
https://github.com/Azure/azure-sdk-for-java/blob/main/eng/scripts/Language-Settings.ps1#L756-L758

Check if we should change it to e.g.
```
--arg="java-sdk-folder=$repositoryRoot"
```

to make sure it works consistently with tspconfig in spec repo.
https://github.com/Azure/azure-rest-api-specs/blob/main/specification/contosowidgetmanager/Contoso.WidgetManager/tspconfig.yaml

**Comment by haolingdong-msft** [comment]
Hi @weshaggard / @weidongxu-microsoft, 

To avoid overwrite `emitter-outoput-dir`, I tried to set `java-sdk-folder`, I tested locally, we can use `--arg java-sdk-folder=C:\\workspace\\azure-sdk-for-java` to generate source code in correct directiory, here `C:\\workspace\\azure-sdk-for-java` is my local java sdk folder. I updated `Language-Settings.ps1` to set the `java-sdk-folder` to my local dir and run the `TypeSpec-Project-Generate.ps1` script (PS: I deleted the `FakedSharedModel` and related improts in main.tsp as we have this [issue](https://github.com/Azure/azure-sdk-tools/issues/5808) to make codegen successfully). Please see below screeshot for more details.

**One problem** is the API [`Get-java-EmitterAdditionalOptions`](https://github.com/Azure/azure-sdk-for-java/blob/main/eng/scripts/Language-Settings.ps1#L756) does not have project root folder (i.e. the java sdk folder) as an input parameter, so I hard coded `--arg java-sdk-folder=C:\\workspace\\azure-sdk-for-java` in my local `Language-Settings.ps1` code. I think we will need to update this API to include another parameter $projectRoot, code in `Language-Settings.ps1` may look like below. @weshaggard @m-nash, what do you think? Could we support this?
```powershell
function Get-java-EmitterAdditionalOptions([string]$projectDirectory, [string]$projectRoot) {
  return "--arg java-sdk-folder=$projectRoot"
}
```

![image](https://user-images.githubusercontent.com/87355844/234463929-63735c6c-480d-4cb1-bab4-c73590839181.png)

**Comment by weidongxu-microsoft** [comment]
Follow-up could depends on whether/how design of `emitter-output-dir` in tspconfig.yaml changes.

If we had a shared script to create/update tsp-location.yaml in SDK repo (for first package, that script can use the path of `emitter-output-dir` to create the tsp-location.yaml on correct folder), and this "Get-java-EmitterAdditionalOptions" can remain unchanged.
Steps could be
1. TypeSpec-Project-TspLocation.ps1 reads the `emitter-output-dir`, resolve it via provided `java-sdk-folder` and the default `service-directory-name`, create or update the tsp-location.yaml at `emitter-output-dir`.
2. TypeSpec-Project-Sync.ps1 checkout the spec repo via tsp-location.yaml.
3. TypeSpec-Project-Generate.ps1 generates the code, with `projectDirectory` be the location of tsp-location.yaml folder (which would be same of the resolved `emitter-output-dir`, guaranteed by step 1).

If there is different design, we may need to handle it differently in Language-Settings.ps1

**Comment by m-nash** [comment]
@weidongxu-microsoft I don't know that we want to avoid this.  @raych1 / @weshaggard we were supposed to discuss how the `project-root` would come in for all scenarios and hopefully avoid any env variables.  I would hold off on this issue until we have clarity in that area.

**Comment by weidongxu-microsoft** [comment]
Sure, we will wait till we had complete design on the sdk automation procedure.

**Comment by haolingdong-msft** [comment]
> @haolingdong-msft if `project-root` == `repo-root` you can find this by running this command `$root = git rev-parse --show-toplevel` inside your function and doing any concatenation that is needed. However this should already be part of the path in the `$projectDirectory` parameter that is passed in.
> 
> You could also find it via a relative path to the running script since that will always be in `{repo-root}/eng`

Thanks Micheal, I will try.

**Comment by weshaggard** [comment]
@raych1 is the one working on a design for how we handle these paths. Some of the ideas are in his PR https://github.com/Azure/azure-rest-api-specs/pull/23768. 

Ray do you have plan for how we to handle this yet?

**Comment by weshaggard** [comment]
@m-nash correct based on @raych1 currently proposal at https://github.com/Azure/azure-rest-api-specs/pull/23875 and https://github.com/Azure/azure-rest-api-specs/pull/23866 we will continue to be setting the emitter-output-dir when calling the emitter in Language-Settings.ps1

**Comment by weidongxu-microsoft** [comment]
OK, then we likely have NOOP on this task.

The tspconfig.yaml no longer have emitter-output-dir in emitter options, and automation with Script will have the `$projectDirectory` points to the location of the project (may be from tsp-location.yaml and ultimately from `project-dir` option in tspconfig.yaml).

**Comment by haolingdong-msft** [comment]
Thanks @weshaggard, @m-nash for the info, we will keep the current code as it is.

**Comment by weshaggard** [comment]
The code that is passing in the emitter-output-path should remain the same but the 2 things that will still need to be updated is the java script will need to start calling @raych1's common wrapper script and the java emitter will need to add support for the `package-dir` property.
