### ISSUE TITLE
[FEATURE REQ] Ability to configure default Tracer/TraceProvider

### ISSUE THREAD

**Issue by Gueorgi** [Azure/azure-sdk-for-java#34442]
**Is your feature request related to a problem? Please describe.**
The default trace provider picks the first class it finds in the class path that is implementing the Trace interface. See https://github.com/Azure/azure-sdk-for-java/blob/bc4a3a25e7dbf93f3ae9612ed17fb84356c7feff/sdk/core/azure-core/src/main/java/com/azure/core/util/tracing/DefaultTracerProvider.java#L31 

This prevents or makes it difficult to control what is being used as Tracer by default since there may be multiple such classes (and some of these one may want to be the default tracer and on another hand some you don't want to be used as such).

One can also try to use TraceProvider class but has similar issue - the first one found will be used and the rest called only if one calls createTracer with right params. Calling create tracer does not work always though - for example one can provide a Tracer to some of the Azure clients via options but not always - for example there is no way to set a custom tracer for Cosmos (looks like there is a method to do so in CosmosClientTelemetryConfig but it is not public).

However in a lot of cases apps may not want or are not able to quickly modify existing code and thus rely on the right tracer being picked up from the class path... but lack good control over that if there are multiple Tracer implementations.

**Describe the solution you'd like**
Introduce an environment variable to provide a preferred Tracer to use - class name may be - if not set or not found in class path do as now - use the first one found.

Do the same may be for TraceProvider load as well - where the first TraceProvider is being used as default.

**Describe alternatives you've considered**
Alternatives:
1. Trying to clear and re-arrange dependencies adding Tracer and TraceProvider classes. Not quite possible in some cases and difficult to do right when possible.
2. Try to create and set TraceProvider and Trace implementation to use with client call (either as option on a call or during the client creation) - not always possible (i.e. Cosmos SDK client has no such public option) or if possible does not allow quick change of the tracer to use without modifying and re-deploying the existing application - something that using an environment variable can address.

**Additional context**

**Information Checklist**
Kindly make sure that you have added all the following information above and checkoff the required fields otherwise we will treat the issuer as an incomplete report
- [X] Description Added
- [X] Expected solution specified

**Comment by Gueorgi** [comment]
@kushagraThapar let me know if this request makes sense

**Comment by lmolkova** [comment]
@Gueorgi  thank you for reporting this. Is your goal with this ask to be able to specify OpenTelemtery provider or to implement your own tracing plugin for Azure SDK?

If you always use OpenTelemetry, then you should be able to configure OpenTelemetry provider with this code:
https://github.com/Azure/azure-sdk-for-java/blob/main/sdk/core/azure-core-tracing-opentelemetry-samples/src/samples/java/com/azure/core/tracing/opentelemetry/samples/TracingJavaDocCodeSnippets.java#L68

We're in process of rolling out support for this for every SDK (not all of them do it yet), but Cosmos got it [recently](https://github.com/Azure/azure-sdk-for-java/blob/main/sdk/cosmos/azure-cosmos/src/main/java/com/azure/cosmos/models/CosmosClientTelemetryConfig.java#L227).

If you're looking into implementing your own tracing plugin, we can definitely support picking the provider based on configuration. If it's your case, would you mind sharing the context: which tracing tool do you want to use? 

So far we've been under impression that no one is interested in writing their own tracing plugins given OTel popularity and were making some design/deprecation decisions based on this assumption.

**Comment by Gueorgi** [comment]
@lmolkova I do want to have the option of a custom tracing plugin - not an open telemetry one. The company I work for has an extensive tracing infrastructure that is not yet compatible with open telemetry. 

But even with setting a trace provider in the OpenTelemetry specific TracingOptions there is actually no guarantee the DefaultTracerProvider will have the right provider class to use - that is first picked up from the classpath - that will honor what's in the OTel TracingOptions (that interface has just the isEnabled() method - nothing to set/get TraceProviders etc). So again based on what's in the classpath one may get their tracer loaded or not. The Cosmos SDK ends up invoking DefaultTracerProvider.createTracer method - the result of that will actually depend on what was loaded in what order from the class path and if they honor tracing options (with more than enabled/disabled) and params. And if your application has to use dependencies on other libraries that may contain their own implementations of Tracer/TracerProvider interfaces you kind of have no control even if configuring all the OTel TracingOptions etc correctly. I think there is a valid case to add a bit more control of what is to be picked up as default provider or default/fallback tracer in case there are multiple of these on the class path.

**Comment by lmolkova** [comment]
@Gueorgi that you for the explanation! It makes sense and we'll add a setting to customize the provider.

We plan, however, to remove deprecated methods and constants in `com.azure.core.util.tracing` package (mostly on `Tracer` class) by the end of 2023.  There are no plans to change anything else.
