### ISSUE TITLE
[QUERY] Latency spike in Direct TCP Mode

### ISSUE THREAD

**Issue by mangeshmandlik1** [Azure/azure-sdk-for-java#34452]
**Query/Question**
We see latency spikes in direct connection mode (p90 is good 50ms, but p99 is ~0.8sec). As per below issue it was fixed in 4.3.0 release. What changes we need to do ? We tried setting setIdleEndpointTimeout and setIdleConnectionTimeout to hours, but still we see this issue.

https://github.com/Azure/azure-sdk-for-java/issues/13246
https://github.com/Azure/azure-sdk-for-java/issues/19750

**Comment by joshfree** [comment]
Hi @mangeshmandlik1 someone from the Cosmos team will follow up shortly.

Please note that if this issue requires immediate attention then we recommend customers file an Azure support ticket: https://github.com/Azure/azure-sdk-for-java/blob/main/SUPPORT.md#azure-support-tickets

**Comment by kushagraThapar** [comment]
@mangeshmandlik1  - replied on your other issue, please see the response there, thanks!
