### ISSUE TITLE
[BUG] CostManagementManager queries do not handle paging

### ISSUE THREAD

**Issue by JulianBichl** [Azure/azure-sdk-for-java#34455]
**Describe the bug**
The current implementation of the CostManagementManager does not allow the use of the paging mechanism when performing queries. However, the Azure API uses a paging mechanism to return a maximum of 1000 entries and then provides a next link to load the next page of cost entries. This limits a query of all cost entries by the SDK to a maximum of 1000 entries. 

**To Reproduce**
Query the detailed costs a larger azure deployment with the CostManagementManager Query-Functionality. The response is limited to 1000 entries and contains a next link, but the sdk isn't capable to use these informations 

**Setup (please complete the following information):**
 - OS: Win 10
 - IDE: IntelliJ 2023.1
 - [Library/Libraries: com.azure.resourcemanager:azure-resourcemanager-costmanagement:jar:1.0.0-beta.4
 - Java 11

**Comment by joshfree** [comment]
Hi @JulianBichl, someone from the Management plane SDK team will follow up with you shortly

**Comment by weidongxu-microsoft** [comment]
@JulianBichl

Could you show which function or which REST API is in question?

What I can find about "query" is this API, but it does not have "x-ms-pageable" and hence SDK will not automatically paging it.
https://github.com/Azure/azure-rest-api-specs/blob/main/specification/cost-management/resource-manager/Microsoft.CostManagement/stable/2022-10-01/costmanagement.json#L950-L959

If this is the API, it would be backend issue.

**Comment by JulianBichl** [comment]
@weidongxu-microsoft 
Thank you for your fast reply :)
The following example uses the query feature from the cost-management
Calling "https://management.azure.com/subscriptions/{tenantId}/providers/Microsoft.CostManagement/query?api-version=2022-10-01"
Body:
`{"type":"ActualCost","dataSet":{"granularity":"None","aggregation":{"totalCost":{"name":"Cost","function":"Sum"},"totalCostUSD":{"name":"CostUSD","function":"Sum"}},"grouping":[{"type":"Dimension","name":"ResourceId"},{"type":"Dimension","name":"ResourceType"},{"type":"Dimension","name":"ResourceLocation"},{"type":"Dimension","name":"ChargeType"},{"type":"Dimension","name":"ResourceGroupName"},{"type":"Dimension","name":"PublisherType"},{"type":"Dimension","name":"ServiceName"},{"type":"Dimension","name":"Meter"}],"include":["Tags"]},"timeframe":"Custom","timePeriod":{"from":"2023-04-01T00:00:00+00:00","to":"2023-04-30T23:59:59+00:00"}}`

This response returns in larger azure environments more than 1k row entries. Therefore, the api returns a "nextLink" Property, that already contains the skip token in its url. But unfortunately the sdk does not allow reinserting this url into the query neither the sdk uses the information for auto paging. Therefore the user is always limited to 1k cost entries with the sdk.

Also the rest api is able to manual select the number of rows per page by using a $top query param. I am not sure if the SDK also supports such functionality.

**Comment by weidongxu-microsoft** [comment]
Thanks @JulianBichl 

I see there is already lots of same issue raised to service:
- https://github.com/Azure/azure-rest-api-specs/issues/23405
- https://github.com/Azure/azure-rest-api-specs/issues/18733
- https://github.com/Azure/azure-rest-api-specs/issues/19150
- https://github.com/Azure/azure-rest-api-specs/issues/22528

Given the situation, my guess is service is not fixing it anytime soon. Let me see if we can do some client hack to handle this...

**Comment by weidongxu-microsoft** [comment]
@JulianBichl 

Here is sample code for walkaround.

It is not great, but depends on your usage, it should get you unblocked.

```java
QueryDefinition queryDefinition = new QueryDefinition()
        .withType(ExportType.USAGE)
        .withTimeframe(TimeframeType.THE_LAST_BILLING_MONTH)
        .withDataset(
                new QueryDataset()
                        .withGranularity(GranularityType.DAILY)
                        .withAggregation(Map.of(
                                "totalCost",
                                new QueryAggregation().withName("PreTaxCost").withFunction(FunctionType.SUM)))
                        .withGrouping(Arrays.asList(
                                new QueryGrouping()
                                        .withType(QueryColumnType.DIMENSION)
                                        .withName("ResourceId"))));
BinaryData queryDefinitionData = BinaryData.fromObject(queryDefinition);
HttpRequest request = new HttpRequest(HttpMethod.POST,
        new URL(AzureEnvironment.AZURE.getResourceManagerEndpoint() + subscriptionId + "/providers/Microsoft.CostManagement/query?api-version=2022-10-01&%24top=100"),
        new HttpHeaders().set(HttpHeaderName.CONTENT_TYPE, "application/json").set(HttpHeaderName.ACCEPT, "application/json"),
        queryDefinitionData);
HttpResponse response = costManagementManager.serviceClient().getHttpPipeline().sendSync(request, Context.NONE);
QueryResultInner queryResult = response.getBodyAsBinaryData().toObject(QueryResultInner.class);

// first check if "nextLink" exists
String nextLink = (String) response.getBodyAsBinaryData().toObject(new TypeReference<Map<String, Object>>() {}).get("nextLink");

request = new HttpRequest(HttpMethod.POST,
        new URL(nextLink),
        new HttpHeaders().set(HttpHeaderName.CONTENT_TYPE, "application/json").set(HttpHeaderName.ACCEPT, "application/json"),
        queryDefinitionData);

// loop if necessary
```

**Comment by weidongxu-microsoft** [comment]
Walkaround provided. I will leave the follow-up on server part to those issues on azure-rest-api-specs.
