### ISSUE TITLE
85 vulnerabilities reported on maven for the SDK

### ISSUE THREAD

**Issue by pchinta** [Azure/azure-sdk-for-java#34478]
**Query/Question**
85 vulnerabilities reported for the SDK on maven..looking for updated package with fixes to vulnerabilities.

***Why is this not a Bug or a feature Request?***
Maven reports that the SDK has 85 vulnerabilites.. do we have updated package fixing the vulnerabilities reported on maven?

**Setup (please complete the following information if applicable):**
https://mvnrepository.com/artifact/com.azure/azure-sdk-all/1.0.0

**Comment by joshfree** [comment]
Hi @pchinta thank you for reaching out to us via this Github issue.  Microsoft takes the security of our software products and services seriously, which includes all source code repositories managed through our GitHub organizations.  Please note that link is from a nearly 4-year-old 1.0.0-SNAPSHOT and newer versions of all libraries exist.


For security issues, we kindly ask that folks do not report security vulnerabilities through public GitHub issues.

Instead, please report them to the Microsoft Security Response Center (MSRC) at https://msrc.microsoft.com/create-report.  If you prefer to submit without logging in, send email to [secure@microsoft.com](mailto:secure@microsoft.com). If possible, encrypt your message with our PGP key; please download it from the [Microsoft Security Response Center PGP Key page](https://www.microsoft.com/msrc/pgp-key-msrc).

More details are available in the SECURITY.md in any of our github repos.
https://github.com/Azure/azure-sdk-for-java/blob/main/SECURITY.md#reporting-security-issues
