### ISSUE TITLE
[BUG] High Scheduling Metrics 

### ISSUE THREAD

**Issue by mangeshmandlik1** [Azure/azure-sdk-for-java#34488]
Requests stucks in wait state for few seconds. Why it has high scheduling metrics ? Our CPU usage is hardly 2% and have high available memory as well.

It sucks while calling  stream().collect()                   
                     .queryItems(querySpec, options, Tenant.class)
                    .stream()
                    .collect(Collectors.toList());

<img width="364" alt="Screenshot 2023-04-17 at 12 10 45 PM" src="https://user-images.githubusercontent.com/49262061/232404957-7e625213-4919-4335-b462-01ff6a2b0ef9.png">

Scheduling Metrics
┌───────────────┬──────────────────┬─────────────┬──────────────┬────────────────────┬─────────────────────┐
│Partition Range│Response Time (ms)│Run Time (ms)│Wait Time (ms)│Turnaround Time (ms)│NUMBER of Preemptions│
├───────────────┼──────────────────┼─────────────┼──────────────┼────────────────────┼─────────────────────┤
│{"min":"","max":"FF"}│ 0│ 1070│ 0│ 1070│ 1│
└───────────────┴──────────────────┴─────────────┴──────────────┴────────────────────┴─────────────────────┘

Also, Why this wait time high for some requests ? How we can reduce it ?

**Comment by mangeshmandlik1** [comment]
@joshfree @kushagraThapar Could you please suggest ?

**Comment by mangeshmandlik1** [comment]
Thanks @joshfree for reverting. Please find below details requested.
Lib: 
            <groupId>com.azure</groupId>
            <artifactId>azure-spring-data-cosmos</artifactId>
version -> 3.33.0
azure-cosmos -> 4.42.0

OS: centos7.7
SpringBootApplication
Ram in MB: 13869
Java: 11

**Comment by kushagraThapar** [comment]
@mangeshmandlik1 - wait time is the time the SDK was waiting for this thread to be picked up by the CPU, are you blocking on netty I/O thread? what is your query code looks like? Are you using sync or async API? How many cores does your CPU have? Because a lot of this depends on the number of CPU cores.

**Comment by mangeshmandlik1** [comment]
@kushagraThapar 
CPU cores: 4
We tried both Sync and Async client. In both cases our threads stuck in wait state for around 5% requests. 
Currently with sync client, below is the query to get data.

```
            CosmosQueryRequestOptions options = new CosmosQueryRequestOptions();
            SqlQuerySpec querySpec = new SqlQuerySpec(FIND_STORES_BY_STORE_NUMBER, new SqlParameter("@storeNumber", storeNumber));
            return storeConfigContainer
                    .queryItems(querySpec, options, StoreConfig.class)
                    .stream()
                    .collect(Collectors.toList());
```

Expected requests: 5 TPS (300 per minute)
CPU cores: 4

**Comment by mangeshmandlik1** [comment]
@kushagraThapar What do you suggest for number of cores so that requests don't stuck in wait state ? Any other improvement areas as well ?

**Comment by kushagraThapar** [comment]
@mangeshmandlik1 - 5% of requests seems to be reasonable if the concurrency is high, however, in your case the concurrency is not too high. However, I do see in your use case, the sync API will block the underlying netty thread until it gets the results. 

So, two improvements we can do: 
1. Increase the number of cores to 8. 
2. Use async Client, and use `publishOn()` operator as mentioned here in the performance section (Use Appropriate Scheduler (Avoid stealing Event loop IO Netty threads)): https://learn.microsoft.com/en-us/azure/cosmos-db/nosql/performance-tips-java-sdk-v4?tabs=api-async#sdk-usage 

Also, the above query should be using query plan cache (once it gets the query plan very first time), so worth checking that in the diagnostics logs - that is should have the queryPlan time as 0.

**Comment by mangeshmandlik1** [comment]
@kushagraThapar we have seen it as blocking for async client readItem as well and below container contains only one partition with only one record.

`                Mono<CosmosItemResponse<Tenant>> itemResponse = tenantAsyncContainer.readItem(String.valueOf(tenantId), new PartitionKey(tenantIdStr), Tenant.class);`
<img width="381" alt="Screenshot 2023-04-18 at 2 45 19 AM" src="https://user-images.githubusercontent.com/49262061/232613562-af7238df-edf6-427c-887b-f39b633f0903.png">

**Comment by kushagraThapar** [comment]
@mangeshmandlik1 - got it, yes, worth blocking with the `publishOn()` API, so that you don't block the netty I/O thread. 

Also, the above picture is straightforward, as it is showing us reactor's blocking call stack. Nothing wrong with that.

**Comment by mangeshmandlik1** [comment]
@kushagraThapar but do you mean it is expected for some request in wait ? As soon we get the result, we want to return it. So even if we use publishOn we still will have similar scenarios where it needs wait to get result. We don't have other parallel task to do.

**Comment by kushagraThapar** [comment]
@mangeshmandlik1 - what I mean is if you use blocking, you will see some threads in waiting state, because they are waiting for the data. But as soon as you get the result, these should be unblocked. 

Using publishOn() will make sure that you are not blocking the internal I/O thread, which then could be leveraged for doing other I/O operations meanwhile.

**Comment by mangeshmandlik1** [comment]
@kushagraThapar Our main concern is our cosmos queries returns result in 2-3ms. Whereas by using cosmos sdk we see few requests stuck in wait for 2-3 seconds which degrades P99.

Now you suggested to use publishOn()

But with publishOn() we don't know how long we should wait for the result. 
We can wait incrementally and check if we got the result. But in cases where query itself returns zero result/records, how long should we wait ?

`                List<Tenant> tenantsList = new ArrayList<>();
                CosmosPagedFlux<Tenant> flux =  tenantAsyncContainer.queryItems(querySpec, Tenant.class);
                flux.publishOn(Schedulers.parallel()).subscribe(response -> {
                    tenantsList.add(response);
                });`

Here I can add wait till tenantsList is not empty. But what if result itself is empty. How long to wait in such cases for response ? 

How we can remove this wait itself from degrading P99.

**Comment by kushagraThapar** [comment]
@mangeshmandlik1 - I think you misunderstood my suggestion. You will still need to call block, in order to get the results. So keep your code as it is, but with publishOn() operator, so that whatever you do after the queryItems API call, you do it on a separate thread and not internal netty I/O thread. 
In addition to this, make sure to use parameterized queries, and did you get a chance to test on 8 core machine?

**Comment by mangeshmandlik1** [comment]
ok.
`            SqlQuerySpec querySpec = new SqlQuerySpec(FIND_STORES_BY_STORE_NUMBER, new SqlParameter("@storeNumber", storeNumber));
            CosmosPagedFlux<StoreConfig> cosmosPagedFlux =  storeConfigAsyncContainer.queryItems(querySpec, StoreConfig.class);
            return cosmosPagedFlux.publishOn(Schedulers.parallel()).collectList().block();`

Still, we were not able to improve P99. We didn't test it with 8 core machine yet.

**Comment by kushagraThapar** [comment]
yeah, the code looks good to me. I still don't understand what could cause intermittent 2-3 seconds delays. Could be GC as well, or is there any other workload running on the client machine at the same time.

**Comment by mangeshmandlik1** [comment]
No we don't have any other workload. And even cpu hardly goes upto 2%. Also it happens with small load as well (1tps).

**Comment by mangeshmandlik1** [comment]
@kushagraThapar if it is GC, what we could check and fix ?

**Comment by kushagraThapar** [comment]
@mangeshmandlik1  - with small TPS, we have usually seen it is connection creation time that causes to degrade the P99, however, in your case, it is the wait time on the query metrics, is that correct?

In case of GC, there are different algorithms that you can try, however, with latest Java SDKs, GC algorithms have been pretty stable. But worth double checking by enabling GC logs to see its metrics. 

However, I am still curious on your 8 core machine testing. How are the results?

**Comment by mangeshmandlik1** [comment]
Yes thats correct, it is the wait time that is degrading P99 (screenshots shared earlier). We tested in macos with 16 cores and the behaviour is same.

**Comment by kushagraThapar** [comment]
@mangeshmandlik1 - one suggestion I have is to try version 4.38.1 of azure-cosmos SDK. We changed some query prefetching logic post that version, so worth checking if that is affecting somehow. 
By the way, which tool are you using to capture these thread information?
