### ISSUE TITLE
Cosmos Diagnostic Provider to honor the telemetry config when telemetry is disabled

### ISSUE THREAD

**Issue by Gueorgi** [Azure/azure-sdk-for-java#34510]
**Is your feature request related to a problem? Please describe.**
The Cosmos Diagnostic provider https://github.com/Azure/azure-sdk-for-java/blob/73b70f8ef665627b23269f5d1b96510c7bb6b0b8/sdk/cosmos/azure-cosmos/src/main/java/com/azure/cosmos/implementation/DiagnosticsProvider.java#L111
can end up creating a tracer that is enabled for tracing even if the CosmosClientTelemetryConfig has TracingOptions set to disable it. (it may get a tracer that ignores the config if passed to it in the createTracer() call, or even if the the tracer returns false for isEnabled, the DiagnosticProvider may end up with DiagnosticsProvider.EnabledNoOpTracer.INSTANCE tracer).

This potentially leads to traces being emitted when these should not - and even if ignored by EnabledNoOpTracer.INSTANCE tracer the code increases the SDK latency. (Looks like the OpenTelemetryCosmosTracer may benefit from few more checks and calls to isRealTracer() to cut some of the flows early).

**Describe the solution you'd like**
DiagnosticProvider should keep a ref to CosmosClientTelemetryConfig and/or the TracingOptions inside and enforce isEnabled() setting from it - not leave it to the tracers loaded from the classpath to do so and also avoid increase in latencies in building traces/events when these traces will be ignored by a default noop or disabled tracer. (i.e. building events or doing transport level tracing).

**Describe alternatives you've considered**
Trying to provide different tracers/providers on the classpath and using 
```
ImplementationBridgeHelpers
                .CosmosClientTelemetryConfigHelper
                .getCosmosClientTelemetryConfigAccessor()
                .setTracer(clientTelemetryConfig, customTracer);
```

**Additional context**

**Information Checklist**
Kindly make sure that you have added all the following information above and checkoff the required fields otherwise we will treat the issuer as an incomplete report
- [ X] Description Added
- [X ] Expected solution specified

**Comment by Gueorgi** [comment]
@FabianMeiswinkel

**Comment by kushagraThapar** [comment]
@Gueorgi - thanks for creating this issue, will investigate it soon and will keep you posted.

**Comment by kushagraThapar** [comment]
@Gueorgi  is this still an issue or can we close it?

**Comment by Gueorgi** [comment]
It has been a while - will need to debug with newest SDK to confirm if it is still an issue or not.

**Comment by kushagraThapar** [comment]
Closing this issue, if the issue still persists, please re-open this or feel free to open a new incident.
