### ISSUE TITLE
[QUERY] Cosmos tracer not cleared from collection types

### ISSUE THREAD

**Issue by Gueorgi** [Azure/azure-sdk-for-java#34513]
**Query/Question**
I have used the following code in Cosmos SDK to set a mock tracer
       ImplementationBridgeHelpers
                .CosmosClientTelemetryConfigHelper
                .getCosmosClientTelemetryConfigAccessor()
                .setTracer(clientTelemetryConfig, customTracer);
                
The code works and the tracer gets called - verified with a call to real DB and container like this:
       try {
            // intentionally trigger an error.
            client.getDatabase("Some_Existing_DB").getContainer("Some_Existing_Container").getScripts()
                    .getStoredProcedure("None_exsiting_sproc").read().block(Duration.ofMillis(5000)).getProperties().getId();
        } catch (CosmosException e) {
        }
 
 However immediately after such a call the tracer looks to be cleared form any field value except for collections.
 I.e. if one has field like this:
 String foo = "Foo";
 
In the tracer, it will be null after the call even if there is no single other assignment of the value for the field but in construction of the tracer. There are no other calls etc - looks the clean up is done by reflection.

However if one has field like:
 private final Map<String, Object> attributes;
 
 The field is not cleared.
 
 Is this expected behaviour? If yes, why? And is there a potential memory leak if the clean up is supposed to remove all fields but leaves collections?
 
***Why is this not a Bug or a feature Request?***
I am not sure why this is happening. I.e. why the tracer fields looks to be nullified via reflection and also why collections are not being cleared.

**Setup (please complete the following information if applicable):**
 - OS: [Mac]
 - IDE: [IntelliJ]
 - Library/Libraries: [Cosmos SDK 4.43.0, azure-core-tracing-opentelemetry 1.0.0-beta.33, opentelemetry-exporter-logging 1.23.0 ]
 
 **Information Checklist**
 Kindly make sure that you have added all the following information above and checkoff the required fields otherwise we will treat the issuer as an incomplete report
- [ X] Query Added
- [X ] Setup information Added

**Comment by Gueorgi** [comment]
@FabianMeiswinkel

**Comment by kushagraThapar** [comment]
@Gueorgi - thanks for creating this issue, will investigate it soon and will keep you posted.

**Comment by TheovanKraay** [comment]
To be considered for next semester planning.

**Comment by kushagraThapar** [comment]
@Gueorgi - I am cleaning up old github issues, if this still persists, please re-open it.
