### ISSUE TITLE
[BUG] EventHubs proxyOptions not respected?

### ISSUE THREAD

**Issue by wstest123** [Azure/azure-sdk-for-java#34533]
**Describe the bug**
When using proxy to send message to eventhubs with Azure SDK Client, we found that some messages are not able to send out and got the following Exceptions. 
![image](https://user-images.githubusercontent.com/108621200/232723942-e7c943e7-5ae3-4731-b0e5-0be612d7dfa0.png)
To troubleshoot this exception, we hope to know more about the following error messge url；
**message:{"az.sdk.message": "Failed to connect to url:'https://vdm2spark001.servicebus.chinacloudapi.cn:8080',proxy host:'10.85.0.241'**
We didn't use 8080 port to connect to EventHub, and our proxy address is ：10.85.0.241:8080 
**Could you please help advice that why the error log shows that the connect url is **https://vdm2spark001.servicebus.chinacloudapi.cn:8080** ？**

***Code Snippet***
ProxyOptions proxyOptions = new ProxyOptions(ProxyAuthenticationType.BASIC,new Proxy(Proxy.Type.HTTP,new InetSocketAddress(host, Integer.parseInt(port))),username,password);

EventHubClientBuilder eventHubClientBuilder = new EventHubClientBuilder();

EventHubProducerClient eventHubProducerClient = eventHubClientBuilder.connectionString(itemsMap.get("sendConnectionString"),eventHubName)
.proxyOptions(proxyOptions)
.transportType(AmqpTransportType.AMQP_WEB_SOCKETS)
.buildProducerClient();

**Expected behavior**

**Screenshots**
![image](https://user-images.githubusercontent.com/108621200/232724053-70f99865-f17c-4f23-b2b0-c99d2fba4d02.png)

![image](https://user-images.githubusercontent.com/108621200/232724237-224fd9c9-6c40-4948-9095-ac1c1e03493b.png)

**Setup (please complete the following information):**
com.azure.azure-messaging-eventhubs  :5.12.1

**Comment by joshfree** [comment]
@conniey could you follow up with @wstest123 on this issue?

**Comment by conniey** [comment]
We pass in the ProxyOptions you set as-is.  However, when we are printing out the error log, we print out the host name part of the InetSocketAddress , which may be misleading for you.

https://github.com/Azure/azure-sdk-for-java/blob/main/sdk/core/azure-core-amqp/src/main/java/com/azure/core/amqp/implementation/handler/WebSocketsProxyConnectionHandler.java#L191
