### ISSUE TITLE
JWT Token validation error while authenticating || Spring Boot 3.0.4

### ISSUE THREAD

**Issue by BariaMithil** [Azure/azure-sdk-for-java#34553]
Hi Team, 

I am facing an error while using Spring cloud Azure for Azure AD in spring boot 3.0.4. The error is mentioned below: 
```console
java.lang.AbstractMethodError: Receiver class com.azure.spring.cloud.autoconfigure.aad.implementation.webapi.validator.AadJwtIssuerValidator does not define or inherit an implementation of the resolved method 'abstract org.springframework.security.oauth2.core.OAuth2TokenValidatorResult validate(org.springframework.security.oauth2.core.OAuth2Token)' of interface org.springframework.security.oauth2.core.OAuth2TokenValidator.
```

The same code is working in spring 2.7.9 and Spring 2.7.10.
This error is occurring when making the PKCE authentication from azure. The Bearer Token is generated but using that Bearer token, the Azure library is throwing the above error while validation. 
Given below are the maven dependencies used: 
```xml
<dependency>
    <groupId>com.azure.spring</groupId>
    <artifactId>azure-spring-boot-starter-active-directory</artifactId>
    <version>4.0.0</version>
</dependency>
------------------------------------------------------------------------------------------
<dependency>
    <groupId>org.springframework.boot</groupId>
    <artifactId>spring-boot-starter-oauth2-client</artifactId>
</dependency>
----------------------------------------------------------------------------------------------
<dependency>
    <groupId>org.springframework.boot</groupId>
    <artifactId>spring-boot-starter-oauth2-resource-server</artifactId>
</dependency>
------------------------------------------------------------------------------------------------
<dependency>
    <groupId>org.springframework.boot</groupId>
    <artifactId>spring-boot-starter-security</artifactId>
</dependency>
--------------------------------------------------------------------
<dependencyManagement>
    <dependencies>**
        <dependency>
            <groupId>com.azure.spring</groupId>
            <artifactId>spring-cloud-azure-dependencies</artifactId>
            <version>${spring-cloud-azure.version}</version>
            <type>pom</type>
            <scope>import</scope>
        </dependency>
    </dependencies>
</dependencyManagement>
----------------------------------------------------------------------------------------------------------
<spring-cloud-azure.version>4.5.0</spring-cloud-azure.version>
```

**Comment by moarychan** [comment]
Hi @BariaMithil , thanks for using our library!

I note you are using `com.azure.spring azure-spring-boot-starter-active-directory:4.0.0`, right? it's not compatible with Spring Boot 3, please try to upgrade to Spring Cloud Azure [5.0](https://mvnrepository.com/artifact/com.azure.spring/spring-cloud-azure-starter-active-directory/5.0.0), and some class package path is different from 4.x, they should be updated simultaneously, see more from [Spring Security Support](https://learn.microsoft.com/en-us/azure/developer/java/spring-framework/spring-security-support?tabs=SpringCloudAzure5x)

**Comment by BariaMithil** [comment]
Hi Chen, Thanks for responding and apologies for the late response. Yes, I have changed the versions for the dependency, and it is now working properly.


Thanks,
Mithil Baria

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by moarychan** [comment]
Closing it since the issue resolved.
