### ISSUE TITLE
[Text Translation] Update samples in md file to use real snippets

### ISSUE THREAD

**Issue by MikeyMCZ** [Azure/azure-sdk-for-java#34560]
Sample code in the README.md file are hard-coded. We should use codesnippet tooling in order to generate samples that are validated during CI process.

Here is an example from App Configuration

https://raw.githubusercontent.com/Azure/azure-sdk-for-java/main/sdk/appconfiguration/azure-data-appconfiguration/README.md

https://github.com/Azure/azure-sdk-for-java/blob/main/sdk/appconfiguration/azure-data-appconfiguration/src/samples/java/com/azure/data/appconfiguration/ReadmeSamples.java

**Comment by alzimmermsft** [comment]
Closing as this was resolved by https://github.com/Azure/azure-sdk-for-java/pull/36346
