### ISSUE TITLE
[FEATURE REQ] Blob NIO API method toRealPath() should give a valid path when called on relative or absolute paths

### ISSUE THREAD

**Issue by kraefrei** [Azure/azure-sdk-for-java#34572]
**Is your feature request related to a problem? Please describe.**
In the NIO implementation of the azure blob filesystem interface, the method `toRealPath()` throws an exception about symbolic links being unsupported, in situations where the path is not a symbolic link.

**Describe the solution you'd like**
[Based on some documentation on the interface](https://docs.oracle.com/javase/7/docs/api/java/nio/file/Path.html#toRealPath(java.nio.file.LinkOption...)) I would expect the method to return an absolute path if the path is not a symbolic link. Given that symbolic links are not possible in Azure Blobs, I wonder if this method should always give the absolute path.

**Describe alternatives you've considered**
Currently we work around this issue by overriding the behavior to give an absolute path for azure blobs

**Information Checklist**
Kindly make sure that you have added all the following information above and checkoff the required fields otherwise we will treat the issuer as an incomplete report
- [x] Description Added
- [x] Expected solution specified

**Comment by ibrahimrabab** [comment]
Hi @kraefrei 
Thanks for reaching out! Can you provide a stack trace for the exception you're seeing, and a code snippet on how you are reproducing this error so that we can investigate this further?

**Comment by ibrahimrabab** [comment]
@kraefrei 
Unfortunately `toRealPath()` and **symbolic links** are unsupported and is documented here as a continued development effort,
https://github.com/Azure/azure-sdk-for-java/blob/main/sdk/storage/azure-storage-blob-nio/README.md#continued-development

As of right now we do not have exact plans on implementing this for the time being. We will update this thread once we figure out plans for implementing this.

Please let us know if you have any additional questions, thanks!
