### ISSUE TITLE
[BUG] Service Bus Session Receiver is not signaling completion when used in rolling-sessions mode.

### ISSUE THREAD

**Issue by anuchandy** [Azure/azure-sdk-for-java#34597]
_Note: This the write-up based on the RCA that @conniey did as part of this [pull request.](https://github.com/Azure/azure-sdk-for-java/pull/34590)_

The ServiceBusSessionReceiver terminates the message pumping if no messages arrive for more than the RetryOptions::TryTimeout period (idle timeout). Such a termination is achieved by using takeUntil+Processor -

```java
Flux<ServiceBusMessageContext> r0 = receiveLink
     .takeUntil(cancelReceiveProcessor)
     ...
```

When such idle timeout elapses, the "cancelReceiveProcessor" is signaled to terminate r0.

This idle timeout based termination is an optional internal feature.

The idle timeout is internally opt-in when using the Low-Level-Receiver attached to a Session. The idle timeout is internally opt-out when using Processor-Receiver attached to multiple Sessions (a.k.a rolling session).

The library decorates the above r0 with the concat operator, and exposes it to the application as below -

```
Flux<ServiceBusMessageContext> r1 = Flux.concat(r0, cancelReceiveProcessor);
```

Here, if the idle timeout is opted-out (which is the case with the rolling session), the "cancelReceiveProcessor" is never signaled, and the r1 may never terminate even after the termination of r0.

**Comment by conniey** [comment]
Fixed in #34590
