### ISSUE TITLE
[BUG] 2 AzureServiceBusJmsProperties Beans found

### ISSUE THREAD

**Issue by LaserEule** [Azure/azure-sdk-for-java#34613]
**Describe the bug**
After upgrading the spring-cloud-azure-starter-servicebus-jms dependency to version 4.7.0 the app doesn't boot anymore because there are 2  AzureServiceBusJmsProperties beans.

***Exception or Stack Trace***

> ***************************
> APPLICATION FAILED TO START
> ***************************
> 
> Description:
> 
> Parameter 0 of method jmsConnectionFactory in com.azure.spring.cloud.autoconfigure.jms.ServiceBusJmsConnectionFactoryConfiguration$SimpleConnectionFactoryConfiguration required a single bean, but 2 were found:
> 	- spring.jms.servicebus-com.azure.spring.cloud.autoconfigure.jms.properties.AzureServiceBusJmsProperties: defined in null
> 	- serviceBusJmsProperties: defined by method 'serviceBusJmsProperties' in class path resource [com/azure/spring/cloud/autoconfigure/jms/ServiceBusJmsAutoConfiguration.class]

**To Reproduce**
Spring Boot App, version 2.7.3
Use spring-cloud-azure-starter-servicebus-jms dependency version 4.7.0
Configure Service Bus properties in yml file: 

> spring:
>   jms:
>     servicebus:
>       pricing-tier: premium
>       connection-string: <connection-string-here>
>       idle-timeout: 300000
>       pool:
>         enabled: false
>     cache:
>       enabled: false

**Expected behavior**
Previously we were using version 4.3.0 of spring-cloud-azure-starter-servicebus-jms and the autoconfiguration worked fine and the app starts. The application should boot with version 4.7.0 too. 

**Setup (please complete the following information):**
 - OS: Mac OS Ventura
 - IDE: Intellij 
 - Library/Libraries: com.azure.spring:spring-cloud-azure-starter-servicebus-jms:4.7.0
 - Java version: 11
 - App Server/Environment: [e.g. Tomcat, WildFly, Azure Function, Apache Spark, Databricks, IDE plugin or anything special]
 - Frameworks: Spring Boot 2.7.3

**Additional context**
Trying to use the new passwordless authentication feature, but the 2 Beans found problem is blocking this.

**Comment by Netyyyy** [comment]
Hi @LaserEule ,
Thank you for reporting this issue.
I didn't reproduce the problem with SpringBoot 2.7.3 and spring-cloud-azure-starter-servicebus-jms:4.7.0.
Please feel free to provide a minimal example or any additional information or context that you think may be helpful. We'll keep you updated on the progress of our review.
Thank you for your contribution to improving our project.
Best regards

**Comment by LaserEule** [comment]
Thanks for the reply! Since you cannot reproduce it, it would seem that there's something I'm doing wrong. I'll create a sample and post it here, as soon as I can.

**Comment by LaserEule** [comment]
After some further investigating (including creating a test project, which then worked) it turns out that I had another class annotated with @EnableConfigurationProperties(AzureServiceBusJmsProperties.class), which shouldn't have had the annotation. This caused the error. Apologies and thanks for your assistance.
