### ISSUE TITLE
mgmt, switch to AAD token for Kudu

### ISSUE THREAD

**Issue by weidongxu-microsoft** [Azure/azure-sdk-for-java#34634]
See email thread for detail.

From chat, will target a patch 2.26.1 in April.

---

We can start with branch https://github.com/Azure/azure-sdk-for-java/tree/mgmt_appservice-kudu-aad-token

commit https://github.com/Azure/azure-sdk-for-java/commit/67385fb9710db9b9ee02f98c3db450020333abb2

**Comment by XiaofeiCao** [comment]
2.26.1 released.
