### ISSUE TITLE
[QUERY]Do you Java sdk support for Entities - List

### ISSUE THREAD

**Issue by an1942023** [Azure/azure-sdk-for-java#34641]
**Query/Question**
Please share mvn/ gradle artifacts for https://learn.microsoft.com/en-us/rest/api/managementgroups/entities/list?tabs=HTTP to consume in Java

***Why is this not a Bug or a feature Request?***
Asking if the feature is already available or not

**Setup (please complete the following information if applicable):**
 - IDE: [e.g. IntelliJ]
 - Library/Libraries: [e.g. com.azure:azure-core:1.16.0 (groupId:artifactId:version)]
 
 **Information Checklist**
 Kindly make sure that you have added all the following information above and checkoff the required fields otherwise we will treat the issuer as an incomplete report
- [ ] Query Added
- [ ] Setup information Added

**Comment by joshfree** [comment]
Hi @an1942023, links to maven artifacts, reference documentation, and samples can be found here: https://azure.github.io/azure-sdk/releases/latest/mgmt/java.html.

**Comment by weidongxu-microsoft** [comment]
@an1942023 

Currently Java did not have it.

We had a request long time ago, but service is not ready to release Java SDK at that time.
https://github.com/Azure/azure-sdk-for-java/issues/25542

Let me see if I can check again.

**Comment by sagaofsilence** [comment]
We badly need the API to list management groups. But it is still missing in the Azure SDK maven jar files.

**Comment by weidongxu-microsoft** [comment]
OK, we got multiple requests for the SDK. I think this be enough reason for us to release a beta.

Here it is
https://central.sonatype.com/artifact/com.azure.resourcemanager/azure-resourcemanager-managementgroups/1.0.0-beta.1
