### ISSUE TITLE
Add manual session/message lock renewals to ServiceBusProcessorClient

### ISSUE THREAD

**Issue by conniey** [Azure/azure-sdk-for-java#34666]
ServiceBusProcessorClient is missing renewSessionLock and renewMessageLock on ServiceBusReceivedMessageContext.  Exists in .NET:
* [RenewSessionLockAsync](https://learn.microsoft.com/dotnet/api/azure.messaging.servicebus.processsessionmessageeventargs.renewsessionlockasync?view=azure-dotnet#azure-messaging-servicebus-processsessionmessageeventargs-renewsessionlockasync(system-threading-cancellationtoken))
* [RenewMessageLockAsync](https://learn.microsoft.com/en-us/dotnet/api/azure.messaging.servicebus.processmessageeventargs.renewmessagelockasync?view=azure-dotnet#azure-messaging-servicebus-processmessageeventargs-renewmessagelockasync(azure-messaging-servicebus-servicebusreceivedmessage-system-threading-cancellationtoken))

**Comment by lmolkova** [comment]
Based on internal discussion:
- it seems manual renewal is necessary when an automatic one does not work
- it might we useful when there is a desire to keep automatic low, but be able to extend lock duration conditionally
- we're not sure if .NET APIs are really used by anyone

So we'll prioritize fixing any issues around auto-renewal (please share the logs if you see one), but will not add a new API at this time.
If you'd like to see manual lock renewal inside `ServiceBusProcessorClient` callback, we want hear from you and learn more about the scenarios :)

**Comment by anuchandy** [comment]
From the discussion, our current stand is to not to expose a new API. Closing this as there is no action pending now.
