### ISSUE TITLE
ADLS Gen2: azure-storage-file-datalake: rename with space in filename

### ISSUE THREAD

**Issue by saransh13090** [Azure/azure-sdk-for-java#34688]
Hi,

When we're using the method **renameWithResponse** present in **DataLakeFileClient** and the source file name has a space in it, we're getting the following error: **The source path for a rename operation does not exist**

Can you please confirm if this is expected behavior and whether if is unique to this API?

Artifact: **azure-storage-file-datalake**
Version: **12.6.0**

`DataLakeFileClient fileClient = getFileClient(fileSystemName, directoryPath, sourceFilePath);
fileClient.renameWithResponse(fileSystemName, targetDirectory, null, null, null, null);`

**Comment by ibrahimrabab** [comment]
Hi @saransh13090 
I tried to run `renameWithResponse()` with my source file name containing a space and used the same version as you (12.6.0) but I do not run into any exceptions. Can you please provide the following details:

- what does `getFileClient()` do? Can you provide a code snippet for this?
- what values are assigned to fileSystemName, targetDirectory, directoryPath, and sourceFilePath? Can you provide a full code snippet of this too?
- What Java version are you using?
- Can you attach a stack trace of the error you are seeing?

Finally, can you try upgrading the version to the newest azure-storage-file-datalake version (12.15.0) and see if your error still appears?

Thanks!
