### ISSUE TITLE
AzureMessagingListenerAutoConfiguration not included in spring.factories of spring-cloud-azure-autoconfigure

### ISSUE THREAD

**Issue by rvervaek** [Azure/azure-sdk-for-java#34690]
The `AzureMessagingListenerAutoConfiguration` class configures a `MessageListenerContainerFactory` when either the `spring-messaging-azure-servicebus` or `spring-messaging-azure-eventhubs` is on the classpath. However the `AzureMessagingListenerAutoConfiguration` class is not defined in the `spring.factories` file under the `org.springframework.boot.autoconfigure.EnableAutoConfiguration` section, causing the class never to get registered by Spring Boot's auto-configuration mechanism. 

Example project showing the problem in a test: 
[AzureMessagingListenerAutoConfiguration-bug.zip](https://github.com/Azure/azure-sdk-for-java/files/11342023/AzureMessagingListenerAutoConfiguration-bug.zip)

**Comment by Netyyyy** [comment]
@rvervaek Thanks for reporting, we will fix it asap.
