### ISSUE TITLE
Health Insights Cancer Profiling ReadMe Issue

### ISSUE THREAD

**Issue by v-hongli1** [Azure/azure-sdk-for-java#34713]
1.
**Section** [link](https://github.com/Azure/azure-sdk-for-java/tree/main/sdk/healthinsights/azure-health-insights-cancerprofiling#azure-cognitive-services-health-insights-cancer-profiling-client-library-for-java)
![image](https://user-images.githubusercontent.com/74638143/235047464-e937dcd6-4cc4-4620-be5f-f4135be732c7.png)

**Reason:**
The page you requested cannot be found.

**Suggestion:**
Change link to `https://review.learn.microsoft.com/azure/cognitive-services/health-decision-support/`

@joshfree for notification.

**Comment by joshfree** [comment]
@samvaity could you help route this

**Comment by samvaity** [comment]
@asaflevi-ms Could you please look into the above issue for Health Insights.

**Comment by asaflevi-ms** [comment]
fixed (https://github.com/Azure/azure-sdk-for-java/commit/ce706cc0cec20e363fb0867058b9edfdae536feb)
