### ISSUE TITLE
[QUERY] Associate a subnet with NAT Gateway using Azure Java SDK

### ISSUE THREAD

**Issue by praneetsharma** [Azure/azure-sdk-for-java#34724]
**Query/Question**
Hi, I am trying to associate an existing NAT gateway with a subnet using Azure Java SDK, but I haven't found a way to do it.

One of the ways I tried doing it is like below but, while the subnet started showing up under NAT gateway, it was not enabled:
```
azure.networks().manager().serviceClient()
            .getNatGateways()
            .getByResourceGroup(resourceGroup, natGateway)
            .subnets()
            .add(subnet);
```

I see another method in SubnetInner to associate NAT Gateway but I am not finding a way to update SubnetInner instance:
`subnetInner.withNatGateway(natGatewayResource)`

***Why is this not a Bug or a feature Request?***
Because I am assuming there might already be a way to achieve it with existing SDK

**Setup (please complete the following information if applicable):**
 - OS: Linux
 - IDE: Eclipse
 - Library/Libraries: Azure-resourcemanager-network 2.25
 
 **Information Checklist**
 Kindly make sure that you have added all the following information above and checkoff the required fields otherwise we will treat the issuer as an incomplete report
- [x] Query Added
- [x] Setup information Added

**Comment by XiaofeiCao** [comment]
Hi @praneetsharma , thanks for your inquiry!

You're right, currently we don't expose convenience method for this. We'll support this feature in our next release.

As a workaround, you can try the following(a bit verbose but should work for your use case):
```java
// get subnet resource
Network vnet = azure.networks().getByResourceGroup(rgName, "vnetName");
Subnet subnet = vnet.subnets().get("subnetName");

// associate subnet to the NAT Gateway
SubnetInner subnetInner = subnet.innerModel();
subnetInner.withNatGateway(new SubResource().withId("natResourceId"));

// update subnet configuration
azure.networks().serviceClient().getSubnets().createOrUpdate(rgName, vnet.name(), subnet.name(), subnetInner);
```

**Comment by praneetsharma** [comment]
Thanks for the workaround, @XiaofeiCao 
I wanted to make minor correction in the code you shared. The last line doesn't seem valid. This is what worked for me:
```
vnet.manager().serviceClient().getSubnets().createOrUpdate(rgName, vnet.name(), subnet.name(), subnetInner);
```
Thanks again for your help.

**Comment by XiaofeiCao** [comment]
Hi @praneetsharma , we've supported in convenience layer in 2.27.0, feel free to have a try:
https://github.com/Azure/azure-sdk-for-java/blob/c4ac34c57273d3b86788ef9a5e96227c1000112c/sdk/resourcemanager/azure-resourcemanager-network/src/test/java/com/azure/resourcemanager/network/NetworkInterfaceOperationsTests.java#L484-L487
