### ISSUE TITLE
[Azure Core] Centralised configuration API for internal client library configuration

### ISSUE THREAD

**Issue by JonathanGiles** [Azure/azure-sdk-for-java#3476]
We need to provide a centralised configuration API for all client libraries to make use of. This configuration API will make it possible for Java client libraries to pull in system settings, environment variables, application configuration files, etc in a consistent and cross-client-library fashion. It also removes the burden of each client library having to implement this individually, and finally, it helps to ensure that we can also have cross-language support for configuration.

This does not need to be a public API, it will only be used by service clients to configure themselves. 

Two useful documents for reference (whilst this issue is being refined):
 - https://github.com/Azure/azure-sdk/pull/330/files
 - https://github.com/Azure/azure-sdk/pull/328/files 

There are a few different things to consider:

**1. Retrieving configurations**
Configurations need to be retrievable from environment variables and run time parameters at minimum, additional locations such at configuration files may be supported in the future. The default order to find configurations should be run time parameters then environment variables, optionally this order may be configured.

- [x] Retrieve configurations from required locations
- [x] Be extensible to support additional configuration locations in the future
- [x] Order of retrieval is configurable, or not required

**2. Build clients using configurations**
Clients should support using configurations during construction but allow for a consumer of the client to override these configurations with code. Sensible defaults should be used when a configuration and consumer setting is not passed. Additionally, clients should be able to take in a configurations object during construction to determine how it is constructed.

- [ ] Use configurations during construction
- [ ] Sensible defaults when a configuration is not set
- [ ] Builders take a configurations object that determines construction

**3. Additional requirements**
- [x] Log a message when a configuration is found in the run time parameters and environment variables
- [x] Determine non-client defaults, such as logging and tracing configurations
- [ ] Update documentation to explain the configurations that each client uses

**Comment by alzimmermsft** [comment]
Section 2, build clients using configurations, will be done on a client by client basis. #3732 will implement that for App Config.
