### ISSUE TITLE
Any plans to support Spring Boot 3.x

### ISSUE THREAD

**Issue by selkarama** [Azure/azure-sdk-for-java#34780]
Hi 

Any plans to support Spring Boot 3.x? 

[https://github.com/Azure/azure-sdk-for-java/blob/12bf4ba761b4ff4fbc1bcc6f683525eced2712fa/sdk/spring/spring-cloud-azure-autoconfigure/src/main/java/com/azure/spring/cloud/autoconfigure/implementation/compatibility/AzureSpringBootVersionVerifier.java#LL31C11-L31C11](https://github.com/Azure/azure-sdk-for-java/blob/12bf4ba761b4ff4fbc1bcc6f683525eced2712fa/sdk/spring/spring-cloud-azure-autoconfigure/src/main/java/com/azure/spring/cloud/autoconfigure/implementation/compatibility/AzureSpringBootVersionVerifier.java#LL31C11-L31C11)

**Comment by blackr1234** [comment]
Spring Boot 3 is already supported, isn't it?

See: https://github.com/Azure/azure-sdk-for-java/wiki/Spring-Versions-Mapping

`AzureSpringBootVersionVerifier` code:
[spring-cloud-azure-dependencies_5.1.0 branch](https://github.com/Azure/azure-sdk-for-java/blob/spring-cloud-azure-dependencies_5.1.0/sdk/spring/spring-cloud-azure-autoconfigure/src/main/java/com/azure/spring/cloud/autoconfigure/implementation/compatibility/AzureSpringBootVersionVerifier.java)

This is the log I get when using Spring Boot `3.0.6`:

> DEBUG c.a.s.c.a.i.c.AzureSpringBootVersionVerifier (AzureSpringBootVersionVerifier.java:92) - The current Spring Boot version matches Spring Cloud Azure accepted version [3.0.x].

**Comment by Netyyyy** [comment]
Hi @selkarama , Thanks for your reporting.
We use Spring Cloud Azure 5.x to support Spring Boot 3. You can use the latest version 5.1.0.

**Comment by Netyyyy** [comment]
> > We are blocked on our App upgrades as we cannot upgrade spring framework without compatible spring data cosmos libraries. Please let us know what is the plan for the upgrades?
> 
> Sorry for the inconvenience caused. We plan to support spring data cosmos recently, maybe this month or next month.

refer https://github.com/Azure/azure-sdk-for-java/issues/30458#issuecomment-1538877730 , Current ETA is June 2023.
