### ISSUE TITLE
XXXXXXXXRepository' that could not be found In Spring boot application (3.0.0Version)

### ISSUE THREAD

**Issue by nagaraju1692** [Azure/azure-sdk-for-java#34829]
As per the project requirement , I have to migrate spring boot application from Spring boot 2.7.6 to 3.0.0 version.

I have modified the below changes from my existing application.

1) Changed the java version from java 11 to 17.
2) I have modified the spring boot starter parent version from 2.7.6 to 3.0.0 version.

I am able to build the application ,While starting the server getting the issue as below.

**Issue Description::**

APPLICATION FAILED TO START

Description:

Field empRepository in com.example.SpringBootDemo.Service.EmpService required a bean of type 'com.example.SpringBootDemo.repository.EmpRepository' that could not be found.

The injection point has the following annotations:
- @org.springframework.beans.factory.annotation.Autowired(required=true)

Action:

Consider defining a bean of type 'com.example.SpringBootDemo.repository.EmpRepository' in your configuration.

Process finished with exit code 1

I am able to replicate this issue , Please find the below repository git hub code.

https://github.com/nagaraju1692/SpringBootDemoCosmosDB

**Comment by Netyyyy** [comment]
Hi @nagaraju1692, thank you for your issue. I saw you still use `azure-spring-boot-starter-cosmos` which not update anymore, recommend you use `spring-cloud-azure-starter-data-cosmos` instead, here is the [migration guide](https://learn.microsoft.com/en-us/azure/developer/java/spring-framework/migration-guide-for-4.0).

For some reason, spring data cosmos haven't supported Spring Boot 3 yet, you could still use Spring Boot 2.x with `spring-cloud-azure-starter-data-cosmos` latest version 4.7.0.

BTW, Spring data cosmos support for Spring Boot 3 will be released recently, please pay attention to our latest information when it is published.

**Comment by nagaraju1692** [comment]
@Netyyy - Thanks for your quick response. Is there any specific target date to release the Spring data cosmos support for Spring Boot 3supported version.

**Comment by Netyyyy** [comment]
Not so sure, maybe this month or next month

**Comment by Netyyyy** [comment]
Hi @nagaraju1692 , Spring Cloud Azure 5.3.0 now supports Spring data cosmos for Spring Boot 3
