### ISSUE TITLE
Not working after upgrading to Azure Stream Binder Service Bus 5.1

### ISSUE THREAD

**Issue by blackr1234** [Azure/azure-sdk-for-java#34825]
## Describe the bug

Consider below minimal sample projects:

|GitHub|Spring Boot|Azure SDK|Test result|
|--|--|--|--|
|[spring-boot-azure-sdk-servicebus-test - spring-boot-2.7-azure-sdk-4.7](https://github.com/blackr1234/spring-boot-azure-sdk-servicebus-test/tree/spring-boot-2.7-azure-sdk-4.7)|2.7.1|4.7.0|✅ OK|
|[spring-boot-azure-sdk-servicebus-test - spring-boot-3.0-azure-sdk-5.0](https://github.com/blackr1234/spring-boot-azure-sdk-servicebus-test/tree/spring-boot-3.0-azure-sdk-5.0)|3.0.5|5.0.0|✅ OK|
|[spring-boot-azure-sdk-servicebus-test - spring-boot-3.0-azure-sdk-5.1](https://github.com/blackr1234/spring-boot-azure-sdk-servicebus-test/tree/spring-boot-3.0-azure-sdk-5.1)|3.0.5|5.1.0|❌ BAD|

**Problem statement:**

After upgrading to Azure Stream Binder Service Bus 5.1, none of the behaviors below works. Nothing happens after the application starts.

Expected behaviors:

- Every second, the application should send a message to the configured ASB topic (the default Spring Cloud Stream supplier behavior).
- The application should be able to receive messages from the configured ASB topic subsciption.

I'm just following the Spring Cloud Azure Service Bus usage documentation (article applies to 4.7.0 and 5.0.0):

https://learn.microsoft.com/en-us/azure/developer/java/spring-framework/spring-cloud-stream-support?tabs=SpringCloudAzure5x#spring-cloud-stream-binder-for-azure-service-bus

According to the changelog, 5.1.0 is compatible with Spring Boot 3.0.5 and Spring Cloud 2022.0.2:

https://github.com/Azure/azure-sdk-for-java/blob/main/sdk/spring/CHANGELOG.md#510-2023-04-26

---

## Exception or Stack Trace

No error. It is just that nothing happens after the application starts (no new log).

---

## To Reproduce

Refer to my GitHub repos. Follow the simple steps in the `README.md` file.

---

## Code Snippet

Refer to my GitHub repos.

---

## Expected behavior

- Every second, the application should send a message to the configured ASB topic (the default Spring Cloud Stream supplier behavior).
- The application should be able to receive messages from the configured ASB topic subsciption.

---

## Screenshots

![](https://i.imgur.com/XnLeud3.png)

![](https://i.imgur.com/KEkYuiz.png)

![](https://i.imgur.com/NxDPnSp.png)

---

## Setup

1. Update application configurations (connection string and messaging entity names) in `src/main/resources/application.yml`.
1. Provision messaging entities in Azure Service Bus.
1. Run the Spring application.

---

## Additional context

N/A.

---

## Information Checklist
Kindly make sure that you have added all the following information above and checkoff the required fields otherwise we will treat the issuer as an incomplete report
- [x] Bug Description Added
- [x] Repro Steps Added
- [x] Setup information Added

**Comment by blackr1234** [comment]
I checked the log again, I think I overlooked an important WARN log:

Source class: `BeanFactoryAwareFunctionRegistry` (from `spring-cloud-function-context 4.0.2`)

> Multiple functional beans were found [consume, supply], thus can't determine default function definition. Please use 'spring.cloud.function.definition' property to explicitly define it.

Then I changed:

```yaml
spring:
  cloud:
    stream:
      function:
        definition: consume;supply
```

To:

```yaml
spring:
  cloud:
    function:
      definition: consume;supply
```

It now works (but I don't understand why).

Below is the version mapping that I observe.

|Azure SDK|Spring Cloud Stream|Spring Cloud Function|
|--|--|--|
|5.0.0|4.0.0|4.0.0|
|5.1.0|4.0.2|4.0.2|

**Comment by blackr1234** [comment]
I did some more testing by explicitly declaring `spring-cloud-stream 4.0.1` to override managed version, but this version does not give that warning and the application behaves normally.

Not sure why this issue only starts happening in Spring Cloud Stream `4.0.2` but not `4.0.0` or `4.0.1` though. I didn't expect such breaking change in a patch version.

So I'm reopening this ticket, hopefully the Azure SDK development team can help take a look and figure out the root cause.

Thanks.

**Comment by Netyyyy** [comment]
Hi @blackr1234 , Thank you for reporting this issue.
Refer to https://github.com/spring-cloud/spring-cloud-stream/issues/2680#issuecomment-1498129630, I think Spring Cloud Stream remove the property `spring.cloud.stream.function.definition`  in 4.2.0 https://github.com/spring-cloud/spring-cloud-stream/commit/98051a0a1e8727f8b41e0614b6ad5c27543ad05f

**Comment by blackr1234** [comment]
@Netyyyy 
Thanks for your prompt reply and the linked issue is very helpful. Glad that it matches my finding as well.

Quoting the conversation in the issue:

> The property `spring.cloud.stream.function.definition` is deprecated and removed. We need to use `spring.cloud.function.definition` instead.

> The `spring.cloud.stream.function.definition` property has been deprecated almost as soon as it has been created.

So, will Microsoft Azure team update the documentation to use the new (or correct) one? 😀

**Comment by Netyyyy** [comment]
> @Netyyyy Thanks for your prompt reply and the linked issue is very helpful. Glad that it matches my finding as well.
> 
> Quoting the conversation in the issue:
> 
> > The property `spring.cloud.stream.function.definition` is deprecated and removed. We need to use `spring.cloud.function.definition` instead.
> 
> > The `spring.cloud.stream.function.definition` property has been deprecated almost as soon as it has been created.
> 
> So, will Microsoft Azure team update the documentation to use the new (or correct) one? 😀

Sure, we will do, Thanks for the reminder
