### ISSUE TITLE
[BUG] UserAgentSuffix value is not getting set

### ISSUE THREAD

**Issue by aavasthy** [Azure/azure-sdk-for-java#34857]
**Describe the bug**
Client using Java SDK 4.19.0 is trying to set userAgentSuffix information on the client-side. However, it just ends up showing them the default userAgent value.
<img width="485" alt="image" src="https://github.com/Azure/azure-sdk-for-java/assets/113193425/94cce58c-9e2d-4beb-bbaa-3183b9ba1ea6">

***Exception or Stack Trace***
No exception

**To Reproduce**
Set userAgentSuffix

 cosmosClient = new CosmosClientBuilder()
                .endpoint(cfg.getEndpoint())
                .key(accountKey)
                .directMode()
                .userAgentSuffix("USER_AGENT_SUFFIX")
                .contentResponseOnWriteEnabled(true)
                .consistencyLevel(cfg.getConsistencyLevel())
                .throttlingRetryOptions(new ThrottlingRetryOptions().setMaxRetryAttemptsOnThrottledRequests(0))
                .buildAsyncClient();

**Expected behavior**
Return the set userAgentSuffix value.

**Setup (please complete the following information):**
 - Java version: 4.19.0 

**Information Checklist**
Kindly make sure that you have added all the following information above and checkoff the required fields otherwise we will treat the issuer as an incomplete report
- [x] Bug Description Added
- [x] Repro Steps Added
- [x] Setup information Added

**Comment by cjdurand12** [comment]
This is occurring with the most recent SDK version as well (4.41.0)

**Comment by kushagraThapar** [comment]
This is done.
