### ISSUE TITLE
Create a set of layered pom files for the root of the repo

### ISSUE THREAD

**Issue by weshaggard** [Azure/azure-sdk-for-java#3485]
There are 3 primary types of libraries in this repo:
1. Management
2. Data-Plane track 1
3. Data-Plane track 2, which we are calling client.

In order to help scope our builds we want to the following pom file structure in the root:

pom.mgmt.xml - Used as the parent pom for management, currently this is the pom.xml in the root.
pom.client.xml - Used for building the track 2 data-plane libraries, aka client libraries
pom.data-plane.xml - Used for building the track 1 data-plane libraries.

pom.xml - Will contain a module reference to each of those 3 pom files.

**Comment by jianghaolu** [comment]
Also verify the issues are addressed in https://github.com/Azure/azure-sdk-for-java/issues/2970.

**Comment by weshaggard** [comment]
resolved with https://github.com/Azure/azure-sdk-for-java/pull/3768.
