### ISSUE TITLE
[BUG] Spring Repository deleteById not working on Cosmos DB

### ISSUE THREAD

**Issue by GustavoOS** [Azure/azure-sdk-for-java#34850]
**Describe the bug**
Delete By Id method fails as if the document was not in the Cosmos DB database.

***Exception or Stack Trace***

> 2023-05-09 13:39:42.471 ERROR 15084 --- [nio-8080-exec-1] o.a.c.c.C.[.[.[/].[dispatcherServlet]    : Servlet.service() for servlet [dispatcherServlet] in context with path [] threw exception [Request processing failed; nested exception is com.azure.spring.data.cosmos.exception.CosmosAccessException: Failed to delete item; nested exception is {"ClassName":"NotFoundException","userAgent":"azsdk-java-cosmos/4.42.0 Windows10/10.0 JRE/17.0.7","statusCode":404,"resourceAddress":"rntbd://127.0.0.1:10253/apps/DocDbApp/services/DocDbServer24/partitions/a4cb4964-38c8-11e6-8106-8cdcd42c33be/replicas/1p/","error":"{\"Errors\":[\"Resource Not Found. Learn more: https://aka.ms/cosmosdb-tsg-not-found\"]}","innerErrorMessage":"[\"Resource Not Found. Learn more: https://aka.ms/cosmosdb-tsg-not-found\"]","causeInfo":null,"responseHeaders":"{x-ms-current-replica-set-size=1, x-ms-last-state-change-utc=Mon, 08 May 2023 15:43:07.963 GMT, x-ms-request-duration-ms=0.277, x-ms-session-token=0:-1#15, lsn=15, x-ms-request-charge=1.24, x-ms-schemaversion=1.15, x-ms-transport-request-id=3, x-ms-number-of-read-regions=0, x-ms-current-write-quorum=1, x-ms-cosmos-quorum-acked-llsn=15, x-ms-quorum-acked-lsn=15, x-ms-activity-id=192bfec5-ee88-11ed-bea1-a141ef3cef8a, x-ms-xp-role=0, x-ms-global-Committed-lsn=-1, x-ms-cosmos-llsn=15, x-ms-serviceversion= version=2.14.0.0}","cosmosDiagnostics":{"userAgent":"azsdk-java-cosmos/4.42.0 Windows10/10.0 JRE/17.0.7","activityId":"192bfec5-ee88-11ed-bea1-a141ef3cef8a","requestLatencyInMs":86,"requestStartTimeUTC":"2023-05-09T16:39:42.361841700Z","requestEndTimeUTC":"2023-05-09T16:39:42.448840700Z","responseStatisticsList":[{"storeResult":{"storePhysicalAddress":"rntbd://127.0.0.1:10253/apps/DocDbApp/services/DocDbServer24/partitions/a4cb4964-38c8-11e6-8106-8cdcd42c33be/replicas/1p/","lsn":15,"globalCommittedLsn":-1,"partitionKeyRangeId":"0","isValid":true,"statusCode":404,"subStatusCode":0,"isGone":false,"isNotFound":true,"isInvalidPartition":false,"isThroughputControlRequestRateTooLarge":false,"requestCharge":1.24,"itemLSN":-1,"sessionToken":"0:-1#15","backendLatencyInMs":0.277,"retryAfterInMs":null,"exceptionMessage":"[\"Resource Not Found. Learn more: https://aka.ms/cosmosdb-tsg-not-found\"]","exceptionResponseHeaders":"{x-ms-current-replica-set-size=1, x-ms-last-state-change-utc=Mon, 08 May 2023 15:43:07.963 GMT, x-ms-request-duration-ms=0.277, x-ms-session-token=0:-1#15, lsn=15, x-ms-request-charge=1.24, x-ms-schemaversion=1.15, x-ms-transport-request-id=3, x-ms-number-of-read-regions=0, x-ms-current-write-quorum=1, x-ms-cosmos-quorum-acked-llsn=15, x-ms-quorum-acked-lsn=15, x-ms-activity-id=192bfec5-ee88-11ed-bea1-a141ef3cef8a, x-ms-xp-role=0, x-ms-global-Committed-lsn=-1, x-ms-cosmos-llsn=15, x-ms-documentdb-partitionkeyrangeid=0, x-ms-serviceversion= version=2.14.0.0}","replicaStatusList":["10253:Unknown"],"transportRequestTimeline":[{"eventName":"created","startTimeUTC":"2023-05-09T16:39:42.421824800Z","durationInMilliSecs":1.0861},{"eventName":"queued","startTimeUTC":"2023-05-09T16:39:42.422910900Z","durationInMilliSecs":0.0},{"eventName":"channelAcquisitionStarted","startTimeUTC":"2023-05-09T16:39:42.422910900Z","durationInMilliSecs":17.9145},{"eventName":"pipelined","startTimeUTC":"2023-05-09T16:39:42.440825400Z","durationInMilliSecs":1.0005},{"eventName":"transitTime","startTimeUTC":"2023-05-09T16:39:42.441825900Z","durationInMilliSecs":0.9985},{"eventName":"decodeTime","startTimeUTC":"2023-05-09T16:39:42.442824400Z","durationInMilliSecs":0.0},{"eventName":"received","startTimeUTC":"2023-05-09T16:39:42.442824400Z","durationInMilliSecs":6.0163},{"eventName":"completed","startTimeUTC":"2023-05-09T16:39:42.448840700Z","durationInMilliSecs":0.0}],"rntbdRequestLengthInBytes":380,"rntbdResponseLengthInBytes":292,"requestPayloadLengthInBytes":0,"responsePayloadLengthInBytes":292,"channelStatistics":{"channelId":"c4ab2be4","channelTaskQueueSize":1,"pendingRequestsCount":0,"lastReadTime":"2023-05-09T16:39:42.440825400Z","waitForConnectionInit":true},"serviceEndpointStatistics":{"availableChannels":0,"acquiredChannels":0,"executorTaskQueueSize":0,"inflightRequests":1,"lastSuccessfulRequestTime":"2023-05-09T16:39:42.422Z","lastRequestTime":"2023-05-09T16:39:42.422Z","createdTime":"2023-05-09T16:39:42.421824800Z","isClosed":false,"cerMetrics":{}}},"requestResponseTimeUTC":"2023-05-09T16:39:42.448840700Z","requestStartTimeUTC":"2023-05-09T16:39:42.361841700Z","requestResourceType":"Document","requestOperationType":"Delete","requestSessionToken":null}],"supplementalResponseStatisticsList":[],"addressResolutionStatistics":{"193378d9-ee88-11ed-bea1-a141ef3cef8a":{"startTimeUTC":"2023-05-09T16:39:42.412868300Z","endTimeUTC":"2023-05-09T16:39:42.417953400Z","targetEndpoint":"https://127.0.0.1:8081/addresses/?$resolveFor=dbs%2Fth5pAA%3D%3D%2Fcolls%2Fth5pAPDgXaI%3D%2Fdocs&$filter=protocol%20eq%20rntbd&$partitionKeyRangeIds=0","exceptionMessage":null,"forceRefresh":false,"forceCollectionRoutingMapRefresh":false,"inflightRequest":false}},"regionsContacted":["south central us"],"retryContext":{"statusAndSubStatusCodes":null,"retryCount":0,"retryLatency":0},"metadataDiagnosticsContext":{"metadataDiagnosticList":[{"metaDataName":"CONTAINER_LOOK_UP","startTimeUTC":"2023-05-09T16:39:42.366843800Z","endTimeUTC":"2023-05-09T16:39:42.372826100Z","durationinMS":5},{"metaDataName":"PARTITION_KEY_RANGE_LOOK_UP","startTimeUTC":"2023-05-09T16:39:42.383842300Z","endTimeUTC":"2023-05-09T16:39:42.407835Z","durationinMS":23},{"metaDataName":"SERVER_ADDRESS_LOOKUP","startTimeUTC":"2023-05-09T16:39:42.412868300Z","endTimeUTC":"2023-05-09T16:39:42.417953400Z","durationinMS":5}]},"serializationDiagnosticsContext":{"serializationDiagnosticsList":null},"gatewayStatistics":null,"systemInformation":{"usedMemory":"68941 KB","availableMemory":"8245939 KB","systemCpuLoad":"(2023-05-09T16:39:24.789800900Z 3,5%), (2023-05-09T16:39:29.788172Z 4,6%), (2023-05-09T16:39:34.790817100Z 4,2%), (2023-05-09T16:39:39.799922800Z 3,4%)","availableProcessors":16},"clientCfgs":{"id":1,"machineId":"uuid:54746d8c-1138-47c4-b2d9-c150957e39dd","connectionMode":"DIRECT","numberOfClients":1,"clientEndpoints":{"https://localhost:8081":1},"connCfg":{"rntbd":"(cto:PT5S, nrto:PT5S, icto:PT0S, ieto:PT1H, mcpe:130, mrpc:30, cer:true)","gw":"(cps:1000, nrto:PT1M, icto:PT1M, p:false)","other":"(ed: true, cs: false, rv: true)"},"consistencyCfg":"(consistency: null, mm: true, prgns: [])","proactiveInit":null}}}] with root cause
> 
> com.azure.cosmos.implementation.NotFoundException: {"innerErrorMessage":"[\"Resource Not Found. Learn more: https://aka.ms/cosmosdb-tsg-not-found\"]","cosmosDiagnostics":{"userAgent":"azsdk-java-cosmos/4.42.0 Windows10/10.0 JRE/17.0.7","activityId":"192bfec5-ee88-11ed-bea1-a141ef3cef8a","requestLatencyInMs":86,"requestStartTimeUTC":"2023-05-09T16:39:42.361841700Z","requestEndTimeUTC":"2023-05-09T16:39:42.448840700Z","responseStatisticsList":[{"storeResult":{"storePhysicalAddress":"rntbd://127.0.0.1:10253/apps/DocDbApp/services/DocDbServer24/partitions/a4cb4964-38c8-11e6-8106-8cdcd42c33be/replicas/1p/","lsn":15,"globalCommittedLsn":-1,"partitionKeyRangeId":"0","isValid":true,"statusCode":404,"subStatusCode":0,"isGone":false,"isNotFound":true,"isInvalidPartition":false,"isThroughputControlRequestRateTooLarge":false,"requestCharge":1.24,"itemLSN":-1,"sessionToken":"0:-1#15","backendLatencyInMs":0.277,"retryAfterInMs":null,"exceptionMessage":"[\"Resource Not Found. Learn more: https://aka.ms/cosmosdb-tsg-not-found\"]","exceptionResponseHeaders":"{x-ms-current-replica-set-size=1, x-ms-last-state-change-utc=Mon, 08 May 2023 15:43:07.963 GMT, x-ms-request-duration-ms=0.277, x-ms-session-token=0:-1#15, lsn=15, x-ms-request-charge=1.24, x-ms-schemaversion=1.15, x-ms-transport-request-id=3, x-ms-number-of-read-regions=0, x-ms-current-write-quorum=1, x-ms-cosmos-quorum-acked-llsn=15, x-ms-quorum-acked-lsn=15, x-ms-activity-id=192bfec5-ee88-11ed-bea1-a141ef3cef8a, x-ms-xp-role=0, x-ms-global-Committed-lsn=-1, x-ms-cosmos-llsn=15, x-ms-documentdb-partitionkeyrangeid=0, x-ms-serviceversion= version=2.14.0.0}","replicaStatusList":["10253:Unknown"],"transportRequestTimeline":[{"eventName":"created","startTimeUTC":"2023-05-09T16:39:42.421824800Z","durationInMilliSecs":1.0861},{"eventName":"queued","startTimeUTC":"2023-05-09T16:39:42.422910900Z","durationInMilliSecs":0.0},{"eventName":"channelAcquisitionStarted","startTimeUTC":"2023-05-09T16:39:42.422910900Z","durationInMilliSecs":17.9145},{"eventName":"pipelined","startTimeUTC":"2023-05-09T16:39:42.440825400Z","durationInMilliSecs":1.0005},{"eventName":"transitTime","startTimeUTC":"2023-05-09T16:39:42.441825900Z","durationInMilliSecs":0.9985},{"eventName":"decodeTime","startTimeUTC":"2023-05-09T16:39:42.442824400Z","durationInMilliSecs":0.0},{"eventName":"received","startTimeUTC":"2023-05-09T16:39:42.442824400Z","durationInMilliSecs":6.0163},{"eventName":"completed","startTimeUTC":"2023-05-09T16:39:42.448840700Z","durationInMilliSecs":0.0}],"rntbdRequestLengthInBytes":380,"rntbdResponseLengthInBytes":292,"requestPayloadLengthInBytes":0,"responsePayloadLengthInBytes":292,"channelStatistics":{"channelId":"c4ab2be4","channelTaskQueueSize":1,"pendingRequestsCount":0,"lastReadTime":"2023-05-09T16:39:42.440825400Z","waitForConnectionInit":true},"serviceEndpointStatistics":{"availableChannels":0,"acquiredChannels":0,"executorTaskQueueSize":0,"inflightRequests":1,"lastSuccessfulRequestTime":"2023-05-09T16:39:42.422Z","lastRequestTime":"2023-05-09T16:39:42.422Z","createdTime":"2023-05-09T16:39:42.421824800Z","isClosed":false,"cerMetrics":{}}},"requestResponseTimeUTC":"2023-05-09T16:39:42.448840700Z","requestStartTimeUTC":"2023-05-09T16:39:42.361841700Z","requestResourceType":"Document","requestOperationType":"Delete","requestSessionToken":null}],"supplementalResponseStatisticsList":[],"addressResolutionStatistics":{"193378d9-ee88-11ed-bea1-a141ef3cef8a":{"startTimeUTC":"2023-05-09T16:39:42.412868300Z","endTimeUTC":"2023-05-09T16:39:42.417953400Z","targetEndpoint":"https://127.0.0.1:8081/addresses/?$resolveFor=dbs%2Fth5pAA%3D%3D%2Fcolls%2Fth5pAPDgXaI%3D%2Fdocs&$filter=protocol%20eq%20rntbd&$partitionKeyRangeIds=0","exceptionMessage":null,"forceRefresh":false,"forceCollectionRoutingMapRefresh":false,"inflightRequest":false}},"regionsContacted":["south central us"],"retryContext":{"statusAndSubStatusCodes":null,"retryCount":0,"retryLatency":0},"metadataDiagnosticsContext":{"metadataDiagnosticList":[{"metaDataName":"CONTAINER_LOOK_UP","startTimeUTC":"2023-05-09T16:39:42.366843800Z","endTimeUTC":"2023-05-09T16:39:42.372826100Z","durationinMS":5},{"metaDataName":"PARTITION_KEY_RANGE_LOOK_UP","startTimeUTC":"2023-05-09T16:39:42.383842300Z","endTimeUTC":"2023-05-09T16:39:42.407835Z","durationinMS":23},{"metaDataName":"SERVER_ADDRESS_LOOKUP","startTimeUTC":"2023-05-09T16:39:42.412868300Z","endTimeUTC":"2023-05-09T16:39:42.417953400Z","durationinMS":5}]},"serializationDiagnosticsContext":{"serializationDiagnosticsList":null},"gatewayStatistics":null,"systemInformation":{"usedMemory":"69175 KB","availableMemory":"8245705 KB","systemCpuLoad":"(2023-05-09T16:39:24.789800900Z 3,5%), (2023-05-09T16:39:29.788172Z 4,6%), (2023-05-09T16:39:34.790817100Z 4,2%), (2023-05-09T16:39:39.799922800Z 3,4%)","availableProcessors":16},"clientCfgs":{"id":1,"machineId":"uuid:54746d8c-1138-47c4-b2d9-c150957e39dd","connectionMode":"DIRECT","numberOfClients":1,"clientEndpoints":{"https://localhost:8081":1},"connCfg":{"rntbd":"(cto:PT5S, nrto:PT5S, icto:PT0S, ieto:PT1H, mcpe:130, mrpc:30, cer:true)","gw":"(cps:1000, nrto:PT1M, icto:PT1M, p:false)","other":"(ed: true, cs: false, rv: true)"},"consistencyCfg":"(consistency: null, mm: true, prgns: [])","proactiveInit":null}}}
> 	at com.azure.cosmos.implementation.directconnectivity.rntbd.RntbdRequestManager.messageReceived(RntbdRequestManager.java:989) ~[azure-cosmos-4.42.0.jar:4.42.0]
> 	at com.azure.cosmos.implementation.directconnectivity.rntbd.RntbdRequestManager.channelRead(RntbdRequestManager.java:207) ~[azure-cosmos-4.42.0.jar:4.42.0]
> 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444) ~[netty-transport-4.1.91.Final.jar:4.1.91.Final]
> 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420) ~[netty-transport-4.1.91.Final.jar:4.1.91.Final]
> 	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412) ~[netty-transport-4.1.91.Final.jar:4.1.91.Final]
> 	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:346) ~[netty-codec-4.1.91.Final.jar:4.1.91.Final]
> 	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:318) ~[netty-codec-4.1.91.Final.jar:4.1.91.Final]
> 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444) ~[netty-transport-4.1.91.Final.jar:4.1.91.Final]
> 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420) ~[netty-transport-4.1.91.Final.jar:4.1.91.Final]
> 	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412) ~[netty-transport-4.1.91.Final.jar:4.1.91.Final]
> 	at io.netty.channel.CombinedChannelDuplexHandler$DelegatingChannelHandlerContext.fireChannelRead(CombinedChannelDuplexHandler.java:436) ~[netty-transport-4.1.91.Final.jar:4.1.91.Final]
> 	at io.netty.channel.CombinedChannelDuplexHandler.channelRead(CombinedChannelDuplexHandler.java:253) ~[netty-transport-4.1.91.Final.jar:4.1.91.Final]
> 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:442) ~[netty-transport-4.1.91.Final.jar:4.1.91.Final]
> 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420) ~[netty-transport-4.1.91.Final.jar:4.1.91.Final]
> 	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412) ~[netty-transport-4.1.91.Final.jar:4.1.91.Final]
> 	at io.netty.handler.timeout.IdleStateHandler.channelRead(IdleStateHandler.java:286) ~[netty-handler-4.1.91.Final.jar:4.1.91.Final]
> 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:442) ~[netty-transport-4.1.91.Final.jar:4.1.91.Final]
> 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420) ~[netty-transport-4.1.91.Final.jar:4.1.91.Final]
> 	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412) ~[netty-transport-4.1.91.Final.jar:4.1.91.Final]
> 	at io.netty.handler.ssl.SslHandler.unwrap(SslHandler.java:1383) ~[netty-handler-4.1.91.Final.jar:4.1.91.Final]
> 	at io.netty.handler.ssl.SslHandler.decodeJdkCompatible(SslHandler.java:1246) ~[netty-handler-4.1.91.Final.jar:4.1.91.Final]
> 	at io.netty.handler.ssl.SslHandler.decode(SslHandler.java:1295) ~[netty-handler-4.1.91.Final.jar:4.1.91.Final]
> 	at io.netty.handler.codec.ByteToMessageDecoder.decodeRemovalReentryProtection(ByteToMessageDecoder.java:529) ~[netty-codec-4.1.91.Final.jar:4.1.91.Final]
> 	at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:468) ~[netty-codec-4.1.91.Final.jar:4.1.91.Final]
> 	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:290) ~[netty-codec-4.1.91.Final.jar:4.1.91.Final]
> 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444) ~[netty-transport-4.1.91.Final.jar:4.1.91.Final]
> 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420) ~[netty-transport-4.1.91.Final.jar:4.1.91.Final]
> 	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412) ~[netty-transport-4.1.91.Final.jar:4.1.91.Final]
> 	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410) ~[netty-transport-4.1.91.Final.jar:4.1.91.Final]
> 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:440) ~[netty-transport-4.1.91.Final.jar:4.1.91.Final]
> 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420) ~[netty-transport-4.1.91.Final.jar:4.1.91.Final]
> 	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919) ~[netty-transport-4.1.91.Final.jar:4.1.91.Final]
> 	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:166) ~[netty-transport-4.1.91.Final.jar:4.1.91.Final]
> 	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:788) ~[netty-transport-4.1.91.Final.jar:4.1.91.Final]
> 	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:724) ~[netty-transport-4.1.91.Final.jar:4.1.91.Final]
> 	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:650) ~[netty-transport-4.1.91.Final.jar:4.1.91.Final]
> 	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:562) ~[netty-transport-4.1.91.Final.jar:4.1.91.Final]
> 	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997) ~[netty-common-4.1.91.Final.jar:4.1.91.Final]
> 	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) ~[netty-common-4.1.91.Final.jar:4.1.91.Final]
> 	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) ~[netty-common-4.1.91.Final.jar:4.1.91.Final]
> 	at java.base/java.lang.Thread.run(Thread.java:833) ~[na:na]

**To Reproduce**
- Create Spring Boot project with Spring Initializr
  - selecting Maven, Java 17, Spring Boot 2.7.X
  - Add dependencies Lombok, Spring Boot DevTools, Azure Cosmos DB and Spring Web
- Add Configuration class in order to connect to CosmosDB
- Create creation and deletion endpoints (CRUD)
- Create resource using creation endpoint
- In delete service, use the repository deleteById method.
- Call delete endpoint using the created id as parameter.

***Code Snippet***
Model
```java
import com.azure.spring.data.cosmos.core.mapping.Container;
import com.azure.spring.data.cosmos.core.mapping.GeneratedValue;
import lombok.Data;
import org.springframework.data.annotation.Id;

@Data
@Container(containerName = "Book", ru = "400")
public class Book {

  @Id
  @GeneratedValue
  private String id;

  private String title;
  private String author;
}
```
Repository
```java
import com.azure.spring.data.cosmos.repository.CosmosRepository;
import org.springframework.stereotype.Repository;

@Repository
public interface BookRepository extends CosmosRepository<Book, String> {

}
```

Service (snippet)
```java
 public void deleteBook(String id) {
    bookRepository.deleteById(id);
  }
```

**Expected behavior**
Expected operation to suceed and resource to be deleted at the db.

**Screenshots**
Resource at the database
![image](https://github.com/Azure/azure-sdk-for-java/assets/15959001/a2b1c647-53de-433e-b0c8-9b79fa33532c)
Valid id
![image](https://github.com/Azure/azure-sdk-for-java/assets/15959001/80ae14e0-6c2a-430d-b586-cdd51bcfaab2)
Failure
![image](https://github.com/Azure/azure-sdk-for-java/assets/15959001/65b20367-37a4-4528-9d94-07b96ce4edff)

**Setup (please complete the following information):**
 - OS: Windows 10
 - IDE: IntelliJ
 - Library/Libraries: com.azure.spring:spring-cloud-azure-starter-data-cosmos:4.7.0
 - Java version: 17
 - App Server/Environment:Tomcat, CosmosDB Emulator 2.14.12.0
 - Frameworks: Spring Boot 2.7.10, Lombok, Spring Web

If you suspect a dependency version mismatch (e.g. you see `NoClassDefFoundError`, `NoSuchMethodError` or similar), please check out [Troubleshoot dependency version conflict article](https://aka.ms/azsdk/java/dependency/troubleshoot) first. If it doesn't provide solution for the problem, please provide:
- verbose dependency tree (`mvn dependency:tree -Dverbose`)
- exception message, full stack trace, and any available logs
NA

**Additional context**
Workaround found: Service (Snippet)
```java
public void deleteBook(String id) {
    var book = bookRepository.findById(id).orElseThrow();
    bookRepository.deleteAll(() -> List.of(book).listIterator());
  }
```

**Information Checklist**
Kindly make sure that you have added all the following information above and checkoff the required fields otherwise we will treat the issuer as an incomplete report
- [X] Bug Description Added
- [X] Repro Steps Added
- [X] Setup information Added

**Comment by kushagraThapar** [comment]
@trande4884 pls take a look, thanks!

**Comment by trande4884** [comment]
@GustavoOS in order to use deleteById(var id) the container can't have a partition key defined. The container you are using has a partition key defined so you would need to use deleteById(var id, PartitionKey pk).
