### ISSUE TITLE
Updating TopicProperties with AuthorizationRules returns 400 Bad request

### ISSUE THREAD

**Issue by haraldk** [Azure/azure-sdk-for-java#34880]
Using `azure-messaging-servicebus:7.13.4`, updating `TopicProperties` with non-empty `AuthorizationRule`s returns `400 Bad request`. This happens regardless if the rule is created in the Azure Portal or attempted created using the Java client. 

In earlier versions (up to `azure-messaging-servicebus:7.13.3`), the same invocation would "work", but silently remove any existing `AuthorizationRule`s existing for the topic. Attempting to create rules from the Java client has no effect in this version.

The exact API method that causes this incorrect behavior is:

     ServiceBusAdministrationClient#updateTopic(TopicProperties)

***Exception or Stack Trace***

Using `azure-messaging-servicebus:7.13.4` causes the following exception:

```
Exception in thread "main" com.azure.messaging.servicebus.administration.implementation.models.ServiceBusManagementErrorException: Status code 400, "<Error><Code>400</Code><Detail>Bad Request. To know more visit https://aka.ms/sbResourceMgrExceptions. . TrackingId:bfe78ab4-0ece-4f7d-8483-d1cab5b2598d_G3, SystemTracker:NoSystemTracker, Timestamp:2023-05-09T11:50:33</Detail></Error>"
	at java.base/java.lang.invoke.MethodHandle.invokeWithArguments(MethodHandle.java:732)
	at com.azure.core.implementation.http.rest.ResponseExceptionConstructorCache.invoke(ResponseExceptionConstructorCache.java:56)
	at com.azure.core.implementation.http.rest.RestProxyBase.instantiateUnexpectedException(RestProxyBase.java:356)
	at com.azure.core.implementation.http.rest.SyncRestProxy.ensureExpectedStatus(SyncRestProxy.java:130)
	at com.azure.core.implementation.http.rest.SyncRestProxy.handleRestReturnType(SyncRestProxy.java:213)
	at com.azure.core.implementation.http.rest.SyncRestProxy.invoke(SyncRestProxy.java:81)
	at com.azure.core.implementation.http.rest.RestProxyBase.invoke(RestProxyBase.java:109)
	at com.azure.core.http.rest.RestProxy.invoke(RestProxy.java:91)
	at jdk.proxy2/jdk.proxy2.$Proxy3.putSync(Unknown Source)
	at com.azure.messaging.servicebus.administration.implementation.EntitiesImpl.putWithResponse(EntitiesImpl.java:355)
	at com.azure.messaging.servicebus.administration.ServiceBusAdministrationClient.updateTopicWithResponse(ServiceBusAdministrationClient.java:1749)
	at com.azure.messaging.servicebus.administration.ServiceBusAdministrationClient.updateTopic(ServiceBusAdministrationClient.java:1706)
	at com.example.Main.main(Main.java:43)
```

(earlier versions of the SDK will not cause exception, but instead silently remove any existing authorization rules).

**To Reproduce**

Using 7.13.4:

1. Compile and run the below code snippet, using a valid connection string
2. See that the code throws the above exception
3. Optional, verify that the topic is created, but doe not have any authorization rule

Using 7.13.3:

1. Compile and run the below code snippet, using a valid connection string
2. See that the code prints "Updated"
3. Verify that the topic is created, but doe not have any authorization rule
4. Optional, create authorization rule in Azure portal/UI, re-run steps 1-3, and verify that the authorization rule is removed

***Code Snippet***

```java
ServiceBusAdministrationClient administrationClient = new ServiceBusAdministrationClientBuilder()
        .connectionString("****")
        .buildClient();

// Get or create topic
String topicName = "test-topic";
TopicProperties topic = administrationClient.getTopicExists(topicName)
                ? administrationClient.getTopic(topicName)
                : administrationClient.createTopic(topicName);

// Print some properties
System.out.println("topic.getName() = " + topic.getName());
System.out.println("topic.getUserMetadata() = " + topic.getUserMetadata());
for (AuthorizationRule authorizationRule : topic.getAuthorizationRules()) {
    System.out.println("topic.getAuthorizationRules() = " + authorizationRule.getKeyName() + ", " + authorizationRule.getClaimType());
}

// Update something to verify the update
topic.setUserMetadata("Updated by Java @" + LocalDateTime.now());

// Add AuthorizationRule if none exists
List<AuthorizationRule> authorizationRules = topic.getAuthorizationRules();
if (authorizationRules.isEmpty()) {
    authorizationRules.add(new SharedAccessAuthorizationRule("java-test", List.of(AccessRights.MANAGE, AccessRights.LISTEN, AccessRights.SEND)));
}

//  * 7.13.3, "Works", BUT does not create new AuthorizationRule and removes existing rules...
//  * 7.13.4 Gives 400 Bad request if any AuthorizationRule exists/is created
//  * 7.14.0-beta.1 (same behavior as 7.13.3, build is older than 7.13.4)
// (Similar code, using the .Net API works as expected)
administrationClient.updateTopic(topic);
System.out.println("Updated");

```

**Expected behavior**

The code sample should print some values, then update the topic with given values, and finally print "Updated", without exceptions and keeping any existing authorization rule or creating a new if none exists.

We have recreated the above Java program in .net, using the .net SDK and verified that the it works as expected. This leads us to believe this is a problem with the Java SDK, and not the Azure APIs.

**Setup (please complete the following information):**

 - OS: Test concluded on MacOS, same behavior is observed in Linux stage and production environments.
 - IDE: IntelliJ with Gradle 8 (but doesn't really matter)
 - Library/Libraries: com.azure:azure-messaging-servicebus:7.13.4 with com.azure:azure-core:1.39.0 (as noted, earlier versions show different behavior, but still broken)
 - Java version: 17 (OpenJDK java 17 2021-09-14 LTS)
 - App Server/Environment: N/A
 - Frameworks: N/A

**Information Checklist**
Kindly make sure that you have added all the following information above and checkoff the required fields otherwise we will treat the issuer as an incomplete report
- [x] Bug Description Added
- [x] Repro Steps Added
- [x] Setup information Added

**Comment by haraldk** [comment]
Full compilable project, using Gradle.
[azure-sb-test.zip](https://github.com/Azure/azure-sdk-for-java/files/11441758/azure-sb-test.zip)

**Comment by haraldk** [comment]
Through the debugger, I can se that the actual HTTP request is a `PUT` to `https://sbn-***.servicebus.windows.net/test-topic?api-version=2021-05` with headers `Content-Length=3336, Content-Type=application/atom+xml, If-Match=*, Accept=application/xml, application/atom+xml` and actual payload below. 

It all looks reasonable to me, and the generic 400 "Bad request" response doesn't give any pointers to what might be "bad" about the request. With a little help, I might have been able to create a PR for this...

Atom/XML payload:

```xml
<?xml version='1.0' encoding='UTF-8'?>
<entry xmlns="http://www.w3.org/2005/Atom">
    <content type="application/xml">
        <wstxns1:TopicDescription xmlns:wstxns1="http://schemas.microsoft.com/netservices/2010/10/servicebus/connect">
            <wstxns1:DefaultMessageTimeToLive>P10675199DT2H48M5.477S</wstxns1:DefaultMessageTimeToLive>
            <wstxns1:MaxSizeInMegabytes>1024</wstxns1:MaxSizeInMegabytes>
            <wstxns1:RequiresDuplicateDetection>false</wstxns1:RequiresDuplicateDetection>
            <wstxns1:DuplicateDetectionHistoryTimeWindow>PT1M</wstxns1:DuplicateDetectionHistoryTimeWindow>
            <wstxns1:EnableBatchedOperations>true</wstxns1:EnableBatchedOperations>
            <wstxns1:SizeInBytes>0</wstxns1:SizeInBytes>
            <wstxns1:FilteringMessagesBeforePublishing>false</wstxns1:FilteringMessagesBeforePublishing>
            <wstxns1:IsAnonymousAccessible>false</wstxns1:IsAnonymousAccessible>
            <wstxns1:AuthorizationRules>
                <wstxns1:AuthorizationRule xmlns:wstxns2="http://www.w3.org/2001/XMLSchema-instance" wstxns2:type="SharedAccessAuthorizationRule">
                    <wstxns1:ClaimType>SharedAccessKey</wstxns1:ClaimType>
                    <wstxns1:ClaimValue>None</wstxns1:ClaimValue>
                    <wstxns1:Rights>
                        <wstxns1:AccessRights>Manage</wstxns1:AccessRights>
                        <wstxns1:AccessRights>Listen</wstxns1:AccessRights>
                        <wstxns1:AccessRights>Send</wstxns1:AccessRights>
                    </wstxns1:Rights>
                    <wstxns1:CreatedTime>2023-05-10T16:16:09.153310900Z</wstxns1:CreatedTime>
                    <wstxns1:ModifiedTime>2023-05-10T16:16:09.153310900Z</wstxns1:ModifiedTime>
                    <wstxns1:KeyName>foo</wstxns1:KeyName>
                    <wstxns1:PrimaryKey>***</wstxns1:PrimaryKey>
                    <wstxns1:SecondaryKey>***</wstxns1:SecondaryKey>
                </wstxns1:AuthorizationRule>
            </wstxns1:AuthorizationRules>
            <wstxns1:Status>Active</wstxns1:Status>
            <wstxns1:CreatedAt>2023-05-10T14:52:02.808893700Z</wstxns1:CreatedAt>
            <wstxns1:UpdatedAt>2023-05-10T16:16:09.166329900Z</wstxns1:UpdatedAt>
            <wstxns1:AccessedAt>0001-01-01T00:00:00Z</wstxns1:AccessedAt>
            <wstxns1:SupportOrdering>false</wstxns1:SupportOrdering>
            <wstxns1:CountDetails>
                <wstxns3:ActiveMessageCount xmlns:wstxns3="http://schemas.microsoft.com/netservices/2011/06/servicebus">0</wstxns3:ActiveMessageCount>
                <wstxns4:DeadLetterMessageCount xmlns:wstxns4="http://schemas.microsoft.com/netservices/2011/06/servicebus">0</wstxns4:DeadLetterMessageCount>
                <wstxns5:ScheduledMessageCount xmlns:wstxns5="http://schemas.microsoft.com/netservices/2011/06/servicebus">0</wstxns5:ScheduledMessageCount>
                <wstxns6:TransferDeadLetterMessageCount xmlns:wstxns6="http://schemas.microsoft.com/netservices/2011/06/servicebus">0</wstxns6:TransferDeadLetterMessageCount>
                <wstxns7:TransferMessageCount xmlns:wstxns7="http://schemas.microsoft.com/netservices/2011/06/servicebus">0</wstxns7:TransferMessageCount>
            </wstxns1:CountDetails>
            <wstxns1:SubscriptionCount>0</wstxns1:SubscriptionCount>
            <wstxns1:AutoDeleteOnIdle>P10675199DT2H48M5.477S</wstxns1:AutoDeleteOnIdle>
            <wstxns1:EnablePartitioning>false</wstxns1:EnablePartitioning>
            <wstxns1:EntityAvailabilityStatus>Available</wstxns1:EntityAvailabilityStatus>
            <wstxns1:EnableSubscriptionPartitioning>false</wstxns1:EnableSubscriptionPartitioning>
            <wstxns1:EnableExpress>false</wstxns1:EnableExpress>
            <wstxns1:UserMetadata>Updated by Java @2023-05-10T18:16:24.400742</wstxns1:UserMetadata>
            <wstxns1:MaxMessageSizeInKilobytes>256</wstxns1:MaxMessageSizeInKilobytes>
        </wstxns1:TopicDescription>
    </content>
</entry>
```

**Comment by haraldk** [comment]
Okay, it seems the issue is *really* a problem the Azure service (server side), that is known and worked around in the SDK, related to name spaces in `AuthorizationRule`... Except not for the topic case.

See the following comment in `ServiceBusManagementSerializer.java`: 

https://github.com/Azure/azure-sdk-for-java/blob/6eef53eff51432a441ba71043539b0b47d7a9da5/sdk/servicebus/azure-messaging-servicebus/src/main/java/com/azure/messaging/servicebus/administration/implementation/ServiceBusManagementSerializer.java#L51-L54

I fixed the issue by adding the `CreateTopicBodyImpl.class` to the list of classes that is tested for, and applying the hack in this case too. Will create a PR.

**Comment by haraldk** [comment]
Hi, I filed this issue along with a PR to fix it (including a test case that will fail without the patch applied) almost 4 weeks ago, but have not received any feedback whatsoever. Is this normal?

**Comment by anuchandy** [comment]
@haraldk, apologize for not following up here :( .. Thank you for debugging and finding the root cause. I looked into the PR you opened and looks great to me!
