### ISSUE TITLE
[QUERY] How to migrate from com.microsoft.azure.datalake.store.* for ADLS Gen1?

### ISSUE THREAD

**Issue by mihaimusat** [Azure/azure-sdk-for-java#34897]
**Query/Question**
Our team is involved in migrating from com.microsoft.azure.datalake.store.* to a new Azure SDK library since this will become deprecated soon. We use both Gen1 and Gen2 datalake, so I was wondering if there is a single maven dependency that we can use to replace the deprecated library. As far as I understood from the docs, we can use `azure-storage-file-datalake ` for ADLS Gen2, but for Gen1 this library wouldn't work. 

***Why is this not a Bug or a feature Request?***
We aim to better understand if Gen1 is deprecated itself (if we need to use only ADLS Gen2 from now on).

**Setup (please complete the following information if applicable):**
 - OS: macOS
 - IDE: IntelliJ
 - Library/Libraries: com.microsoft.azure:azure-data-lake-store-sdk, com.azure:azure-storage-file-datalake
 
 **Information Checklist**
 Kindly make sure that you have added all the following information above and checkoff the required fields otherwise we will treat the issuer as an incomplete report
- [x] Query Added
- [x] Setup information Added

**Comment by ibrahimrabab** [comment]
Hi @mihaimusat 
Thanks for reaching out! I'd recommend upgrading the `azure-storage-file-datalake` dependency to the latest one. Our current latest version is `12.15.0`:
https://github.com/Azure/azure-sdk-for-java/blob/main/sdk/storage/azure-storage-file-datalake/GEN1_GEN2_MAPPING.md

And as for Gen1 to Gen2 migration, this document will be helpful in mapping out the methods used between both Gens,
https://github.com/Azure/azure-sdk-for-java/blob/main/sdk/storage/azure-storage-file-datalake/GEN1_GEN2_MAPPING.md

Let me know if this helps or if you have any additional questions!

**Comment by mihaimusat** [comment]
Hi @ibrahimrabab !
Thanks for your response! I would have one more question: do you know when Gen1 datalake will become officially deprecated? This would help us understand when we need to stop provisioning Gen1 datalakes to our clients and start the migration to Gen2.

**Comment by ibrahimrabab** [comment]
@mihaimusat 
DataLake Gen 1 is planned to be deprecated by June 29, 2024 (listed here: https://github.com/azure-deprecation/dashboard/issues/137).

I will go ahead and close this issue, but please feel free to reach out with any additional questions! 😄
