### ISSUE TITLE
[BUG] Blob batch delete - OperationTimedOut

### ISSUE THREAD

**Issue by rangarnow** [Azure/azure-sdk-for-java#34896]
**Describe the bug**
Hi, I am randomly receiving OperationTimedOut errors from Azure Rest API, when deleting blobs in batches via Azure SDK for Java (more in Setup section below). 
Is there any way to improve the code in order to get rid of such errors? I've seen in the https://learn.microsoft.com/en-us/rest/api/storageservices/blob-batch?tabs=azure-ad that there is a timeout to configure to maximum of 120 seconds. Is this method a way to go to set timeout in rest api, or it's currently impossible and it is just setting timeout programatically without appending that to request?   https://azuresdkartifacts.blob.core.windows.net/azure-sdk-for-java/staging/apidocs/com/azure/storage/blob/batch/BlobBatchClient.html#deleteBlobs(java.util.List,com.azure.storage.blob.models.DeleteSnapshotsOptionType,java.time.Duration,com.azure.core.util.Context).

I would be glad for any of the fixes I could apply to limit such errors. We have retries in place, I would like to know about other things I could improve.

***Exception or Stack Trace***
com.azure.storage.blob.models.BlobStorageException: ﻿<?xml version="1.0" encoding="utf-8"?>
<Error><Code>OperationTimedOut</Code><Message>Operation could not be completed within the specified time.
RequestId:XXX
Time:XXX</Message></Error>

**To Reproduce**
It's random, hard to reproduce

***Code Snippet***
Add the code snippet that causes the issue.

**Expected behavior**
I would expect to delete blobs successfully without an error.

**Screenshots**

**Setup (please complete the following information):**
I am using the following version of library:
```xml
<dependency>
   <groupId>com.azure</groupId>
   <artifactId>azure-storage-blob-batch</artifactId>
   <version>12.16.2</version>
</dependency>
```

If you suspect a dependency version mismatch (e.g. you see `NoClassDefFoundError`, `NoSuchMethodError` or similar), please check out [Troubleshoot dependency version conflict article](https://aka.ms/azsdk/java/dependency/troubleshoot) first. If it doesn't provide solution for the problem, please provide:
- verbose dependency tree (`mvn dependency:tree -Dverbose`)
- exception message, full stack trace, and any available logs

**Additional context**

**Information Checklist**
Kindly make sure that you have added all the following information above and checkoff the required fields otherwise we will treat the issuer as an incomplete report
- [X] Bug Description Added
- [X] Repro Steps Added
- [X] Setup information Added

**Comment by ibrahimrabab** [comment]
Hi @rangarnow 

Thank you for reaching out! Is the timeout you're seeing happening after 120 seconds have elapsed, or does the timeout occur before that?

**Comment by rangarnow** [comment]
hi @ibrahimrabab, I did not override the timeout, so should be 30 seconds by default (which aligns with app insights logs). I just see it can be increased to 120 seconds in REST API, but I am not sure if Java SDK allows for that and if it's the best long term solution.
https://learn.microsoft.com/en-us/rest/api/storageservices/setting-timeouts-for-blob-service-operations.

This basically occurs for the time being for only one from hundred storages. It's very weird as we deleted much bigger files in the past without problems on different storages. Can it be it's reaching out some throughput limit for SA from the other source for example? how to debug that?

**Comment by ibrahimrabab** [comment]
@rangarnow 
In the docs under Exceptions section for Blob Batch operations, it actually states:
**"A Blob Batch request supports a maximum timeout value of 120 seconds. If the operation takes more than the timeout value, any remaining subrequests will fail with a timeout error."**

Just to understand your situation a bit better, are you making multiple batch delete calls on a single storage container, or multiple storage containers? And can you let us know after how long the timeout occurs, after 30 seconds or 120 seconds?

**Comment by ibrahimrabab** [comment]
@rangarnow 
I tried to reproduce this with a mock timeout of delete operations greater than 30 seconds, but no exception was thrown. Can you provide a reproducible code snippet that shows the delete operation timing out, so that we can reproduce it on our end? Thanks!

**Comment by rangarnow** [comment]
@ibrahimrabab, unfortunately the error is random, occurs for some SA's only, the deletion code is quite standard (accepting list of blobs to delete). I do not think that would help. If you do not see anything related to SA for example that would be problematic, we can close this issue, as I do not see any solution we could apply and we have to live with random errors.

**Comment by ibrahimrabab** [comment]
@rangarnow sorry to hear about that :( is there anything particularly different about the failing storage accounts, do they have any different specifications that might cause them to fail over the other storage accounts?

**Comment by ibrahimrabab** [comment]
I will go ahead and close this issue for now, but feel free to follow up on this with any additional questions/details. Thanks!
