### ISSUE TITLE
[FEATURE REQ] Possibility to add network rule when creating container registries

### ISSUE THREAD

**Issue by maroony** [Azure/azure-sdk-for-java#34935]
It is possible to add network rules when creating storage accounts like so:

```java
    azureResourceManager.storageAccounts()
        .define(...)
       ...
        .withAccessFromIpAddress(...)
        .withAccessFromNetworkSubnet(...)
        .create();
```

These  `with*` methods doesn't exists when creating container registries like so:

```java
   azureResourceManager.containerRegistries()
        .define(...)
       ...
        .create();
```

So how can I add such a network rule on container registries? Using the CLI, this could be done:

```bash
az acr network-rule add ... --ip-address ...
az acr network-rule add ... --subnet
````

Used dependency:

```xml
    <dependency>
      <groupId>com.azure.resourcemanager</groupId>
      <artifactId>azure-resourcemanager</artifactId>
      <version>2.26.0</version>
    </dependency>
```

**Comment by weidongxu-microsoft** [comment]
@XiaofeiCao Please take a look and schedule.

**Comment by XiaofeiCao** [comment]
subnet settings has been removed from NetworkRuleSet since api-version 2021-09-01:
https://github.com/Azure/azure-rest-api-specs/pull/16481/commits/580d61018d7f3eabc81763c7eb839e1412b6c89c#diff-7ae122050446c1635e3d863e0cfb6b7628957529044fded5f799d8b73fd208d0L1485-L1493

CLI is using 2021_08_01_PREVIEW which still has this setting, while our SDK is using 2022-12-01 which no longer supports it.

We'll support only ip-address settings instead.

**Comment by XiaofeiCao** [comment]
Hi @maroony , 2.27.0 released with network rules support.
You can refer to the following codesnippet:
```java
Registry registry = registryManager.containerRegistries()
    .define(acrName2)
    .withRegion(Region.US_EAST)
    .withNewResourceGroup(rgName)
    .withPremiumSku()
    .withAccessFromSelectedNetworks()
    .withAccessFromIpAddressRange(cdir)
    .enableDedicatedDataEndpoints()
    .withAccessFromTrustedServices()
    .create();

```

**Comment by maroony** [comment]
I got this error after updating to 2.27.0:

`ERROR NetworkRuleSet: Missing required property defaultAction in model NetworkRuleSet`

Code:

```java
    registry = azureResourceManager.containerRegistries()
        .define(name)
        .withRegion(region)
        .withExistingResourceGroup(rg)
        .withPremiumSku()
        .withRegistryNameAsAdminUser()
        .enableDedicatedDataEndpoints()
        .withAccessFromTrustedServices()
        .withAccessFromIpAddress(ip1)
        .withAccessFromIpAddress(ip2)
        .create();
```

**Comment by XiaofeiCao** [comment]
Hi @maroony , I assume you want to enable public network access and deny any public network access except for the configured ip addresses? 

Then you'll need an extra step to express this default denial behavior(just like in the Portal):
```java
azureResourceManager.containerRegistries()
    .define(name)
    .withAccessFromSelectedNetworks() // specifies that by default access to container registry should be denied from all networks
    .withAccessFromIpAddress(ip1)
    ...
```

**Comment by maroony** [comment]
Thanks for the update. It's working now!
