### ISSUE TITLE
[BUG] ReadMany API fails requests when docs are missing. 

### ISSUE THREAD

**Issue by TheovanKraay** [Azure/azure-sdk-for-java#34939]
For point read scenarios where the document is not found when using ReadMany API for Cosmos DB Java SDK, the 404 bubbles up and fails the readMany request as a whole.

**To Reproduce**
Send a list of id+pks to ReadMany API where at least one of the pks only has one doc in the physical partition.

**Expected behavior**
Return successful result for all docs that are found, swallow 404s for point reads, and have them be reflected in the diagnostics instance for the failing point read's response.

**Additional context**
Customer reported issue.

**Information Checklist**
- [x] Bug Description Added
- [x] Repro Steps Added
- [ ] Setup information Added

**Comment by kushagraThapar** [comment]
This is done, please close it with the fix PRs, thanks!
