### ISSUE TITLE
Regenerate azure-search-documents Targeting 2023-07-preview

### ISSUE THREAD

**Issue by alzimmermsft** [Azure/azure-sdk-for-java#35033]
Update target Swagger files to

- https://raw.githubusercontent.com/Azure/azure-rest-api-specs/e7e775e2f3fe00f25fbd0e7ca0d953e22eef93ff/specification/search/data-plane/Azure.Search/preview/2023-07-01-Preview/searchindex.json
- https://raw.githubusercontent.com/Azure/azure-rest-api-specs/e7e775e2f3fe00f25fbd0e7ca0d953e22eef93ff/specification/search/data-plane/Azure.Search/preview/2023-07-01-Preview/searchservice.json

- [ ] Paging APIs will need to be updated to account for semantic partial response reason and partial response type.
- [ ] Searching will need to be updated to support vector search, the additional answers configuration `threshold`, and semantic handling.
- [ ] `FieldBuilder` will need to be updated to support adding a vector configuration name, similar to what was done for adding support for normalizer configurations.

For `answers` with both `count` and `threshold` each configuration is separated with `,`, giving the following possibilities:

`answers: extractive`
`answers: extractive|count-5`
`answers: extractive|threshold-0.7`
`answers: extractive|count-5,threshold-0.7` (ordering shouldn't matter but let's make sure we're consistent)

**Comment by pallavit** [comment]
@alzimmermsft I am assuming this can be closed.
