### ISSUE TITLE
Spotbugs and checkstyle issues in storage autorest generated codes.

### ISSUE THREAD

**Issue by sima-zhu** [Azure/azure-sdk-for-java#3506]

**Comment by sima-zhu** [comment]
**Spotbugs:**

- EI_EXPOSE_REP: May expose internal representation by returning reference to mutable object
  (Code [example](https://github.com/Azure/azure-sdk-for-java/blob/ddd4d5005b95f8d0cce690646800e75778f1b4a4/storage/data-plane/src/main/java/com/microsoft/azure/storage/blob/models/AppendBlobAppendBlockFromUrlHeaders.java#L131))

- EI_EXPOSE_REP2: May expose internal representation by incorporating reference to mutable object
  (Code [example](https://github.com/Azure/azure-sdk-for-java/blob/fa9dbd81977d2c0d70e277f70c4c91e9bb754046/storage/data-plane/src/main/java/com/microsoft/azure/storage/blob/models/PageBlobUploadPagesHeaders.java#L141))

**Comment by sima-zhu** [comment]
All errors reported by spotbugs and checkstyle will document to issue #3506

**Comment by sima-zhu** [comment]
**Checkstyle**:

- UnusedImports:
java.util.ArrayList
com.fasterxml.jackson.dataformat.xml.annotation.JacksonXmlProperty
com.fasterxml.jackson.core.JsonProcessingException
com.fasterxml.jackson.databind.deser.ResolvableDeserializer
com.fasterxml.jackson.databind.deser.std.StdDeserializer
com.fasterxml.jackson.databind.type.TypeFactory

- AvoidStarImport
[Class Example](https://github.com/Azure/azure-sdk-for-java/blob/ddd4d5005b95f8d0cce690646800e75778f1b4a4/storage/data-plane/src/main/java/com/microsoft/azure/storage/blob/models/CustomHierarchicalListingDeserializer.java#L8)

- RedundantModifier
Redundant 'private' modifier. [Class Example](https://github.com/Azure/azure-sdk-for-java/blob/fa9dbd81977d2c0d70e277f70c4c91e9bb754046/storage/data-plane/src/main/java/com/microsoft/azure/storage/blob/models/AccountKind.java#L34)

- WhitespaceAfter
'typecast' is not followed by whitespace. [Class Example](https://github.com/Azure/azure-sdk-for-java/blob/ddd4d5005b95f8d0cce690646800e75778f1b4a4/storage/data-plane/src/main/java/com/microsoft/azure/storage/blob/models/CustomHierarchicalListingDeserializer.java#L35)

- RightCurly
'}' at column 13 should be on the same line as the next part of a multi-block statement (one that directly contains multiple blocks: if/else-if/else, do/while or try/catch/finally). [Class Example](https://github.com/Azure/azure-sdk-for-java/blob/ddd4d5005b95f8d0cce690646800e75778f1b4a4/storage/data-plane/src/main/java/com/microsoft/azure/storage/blob/models/CustomHierarchicalListingDeserializer.java#L37)

**Comment by joshfree** [comment]
@jianghaolu could you give an update on this issue?

**Comment by sima-zhu** [comment]
It is been updated for a while. We can close this now. Will leave this open to get Jianghao confirmed.

**Comment by sima-zhu** [comment]
No more work need to do for the issue. Close this one. Feel free to open this if anything left.
