### ISSUE TITLE
[BUG] ReactiveException is thrown when executes eventHubProducerAsyncClient.createBatch(options).block()

### ISSUE THREAD

**Issue by fei-shen** [Azure/azure-sdk-for-java#35101]
**Describe the bug**
Our application is getting "reactor.core.Exceptions$ReactiveException: java.lang.InterruptedException" when executes eventHubProducerAsyncClient.createBatch(options).block();

***Exception or Stack Trace***

> reactor.core.Exceptions$ReactiveException: java.lang.InterruptedException
> 	at reactor.core.Exceptions.propagate(Exceptions.java:396)
> 	at reactor.core.publisher.BlockingSingleSubscriber.blockingGet(BlockingSingleSubscriber.java:91)
> 	at reactor.core.publisher.Mono.block(Mono.java:1742)
> 	...
> Caused by: java.lang.InterruptedException
> 	at java.util.concurrent.locks.AbstractQueuedSynchronizer.doAcquireSharedInterruptibly(AbstractQueuedSynchronizer.java:998)
> 	at java.util.concurrent.locks.AbstractQueuedSynchronizer.acquireSharedInterruptibly(AbstractQueuedSynchronizer.java:1304)
> 	at java.util.concurrent.CountDownLatch.await(CountDownLatch.java:231)
> 	at reactor.core.publisher.BlockingSingleSubscriber.blockingGet(BlockingSingleSubscriber.java:87)
> 	... 137 more

**To Reproduce**
Run the code snippet below to reproduce, but it happens sometimes.

***Code Snippet***
`EventHubProducerAsyncClient eventHubProducerAsyncClient = new EventHubClientBuilder().credential(namespace, eventhub, tokenProvider).buildAsyncProducerClient();
CreateBatchOptions options = new CreateBatchOptions()
EventDataBatch currentBatch = eventHubProducerAsyncClient.createBatch(options).block();`

**Expected behavior**
The event hub batch should be returned without exception or exception with more details should be provided

**Screenshots**
n/a

**Setup (please complete the following information):**
 - OS: linux
 - Library/Libraries: both azure-messaging-eventhubs:5.15.1 and azure-messaging-eventhubs:5.12.2
 - Java version: 8

**Additional context**
n/a

**Information Checklist**
Kindly make sure that you have added all the following information above and checkoff the required fields otherwise we will treat the issuer as an incomplete report
- [x] Bug Description Added
- [x] Repro Steps Added
- [x] Setup information Added

**Comment by joshfree** [comment]
@conniey could you please follow up?

**Comment by conniey** [comment]
Apologies for the delay, do you have a code snippet of when you create this batch and how it is used as part of your application?

I am wondering if there are threads being terminated while waiting for this batch to be created.  Since this can't be reproduced consistently, any INFO/DEBUG logs around a minute before this happens would help us understand.
