### ISSUE TITLE
SearchAnalyzer and IndexAnalyzer are overriden?

### ISSUE THREAD

**Issue by nayrban** [Azure/azure-sdk-for-java#35165]
Hello, I was trying to follow this guide [Partial Word Search](https://blog.cloudmaker.ai/azure-search-implementing-partial-word-search-c770cd052f39)

Then when I defined my `@SearchableField` with `searchAnalyzerName `and `indexAnalyzerName` it was just sending the `analyzerName` then I reviewed the code and found that  `searchAnalyzerName `and `indexAnalyzerName` are be setting to `analyzerName`  is that the expected behavior, I dont found any documentation that implies they are exclusive  

https://github.com/Azure/azure-sdk-for-java/blob/67ab72ae6d76988cdb7eae0446d227fe0ca77226/sdk/search/azure-search-documents/src/main/java/com/azure/search/documents/implementation/util/FieldBuilder.java#L343

**Comment by alzimmermsft** [comment]
Thanks for filing this issue @nayrban, this looks to be a bug, I'll get this fixed. This fix will ship as part of our monthly releases next week (around June 5th, 2023), I'll update once it has been released.

**Comment by nayrban** [comment]
Thank you @alzimmermsft
