### ISSUE TITLE
[BUG] Exception message thrown by downloadToFileWithResponse() is null  

### ISSUE THREAD

**Issue by aza547** [Azure/azure-sdk-for-java#35160]
**Describe the bug**
The BlobClient.downloadToFileWithResponse() method throws an exception with a null message if networking is slow. 

***Exception or Stack Trace***
N/A

**To Reproduce**
Apply some bandwith throttling to throttle your network and attempt to download a large file. I used https://github.com/magnific0/wondershaper.

`./wondershaper -a  <network-interface> -d 2000  -u  2000`

***Code Snippet***
Add the code snippet that causes the issue.

```java
BlobClient blobClient = new BlobClientBuilder()
                                                  .credential(managedIdentityCredential)
                                                  .endpoint(blobURI)
                                                  .buildClient();

try
{
  Set<OpenOption> openOptions = new HashSet<>();
  openOptions.add(StandardOpenOption.CREATE);
  openOptions.add(StandardOpenOption.TRUNCATE_EXISTING);
  openOptions.add(StandardOpenOption.READ);
  openOptions.add(StandardOpenOption.WRITE);
  blobClient.downloadToFileWithResponse(filePath, null, null, null, null, false, openOptions, Duration.ofMinutes(15), null);
}

catch (Exception ex)
{
  System.out.println("Error message: " + ex.getMessage());
}
```

**Expected behavior**
An appropriate non-null error string is returned by .getMessage().

**Screenshots**
N/A

**Setup (please complete the following information):**
 - OS: Linux (Centos7)
 - IDE: N/A
 - Library/Libraries: com.azure:azure-core:1.32.0
com.azure:azure-storage-blob:12.19.1
com.azure:azure-identity:1.5.5
com.azure:azure-storage-common:12.18.1
com.azure:azure-storage-internal-avro:12.4.2
com.azure:azure-core-http-netty:1.12.5
 - Java version: 8
 - App Server/Environment: None
 - Frameworks: None
 
If you suspect a dependency version mismatch (e.g. you see `NoClassDefFoundError`, `NoSuchMethodError` or similar), please check out [Troubleshoot dependency version conflict article](https://aka.ms/azsdk/java/dependency/troubleshoot) first. If it doesn't provide solution for the problem, please provide:
- verbose dependency tree (`mvn dependency:tree -Dverbose`)
- exception message, full stack trace, and any available logs

**Additional context**
The request failed in less than 15 mins, not actually clear why it failed due to the null exception message. 

**Information Checklist**
Kindly make sure that you have added all the following information above and checkoff the required fields otherwise we will treat the issuer as an incomplete report
- [x] Bug Description Added
- [x] Repro Steps Added
- [x] Setup information Added

**Comment by srnagar** [comment]
@aza547 Can you also share the stack trace for the exception to help us troubleshoot this? Also, could you please try this with the [latest version of azure-storage-blob](https://mvnrepository.com/artifact/com.azure/azure-storage-blob) and [azure-core-http-netty](https://mvnrepository.com/artifact/com.azure/azure-core-http-netty) and let us know if you are still facing this issue?

```java
BlobClient blobClient = new BlobClientBuilder()
                                                  .credential(managedIdentityCredential)
                                                  .endpoint(blobURI)
                                                  .buildClient();

try
{
  Set<OpenOption> openOptions = new HashSet<>();
  openOptions.add(StandardOpenOption.CREATE);
  openOptions.add(StandardOpenOption.TRUNCATE_EXISTING);
  openOptions.add(StandardOpenOption.READ);
  openOptions.add(StandardOpenOption.WRITE);
  blobClient.downloadToFileWithResponse(filePath, null, null, null, null, false, openOptions, Duration.ofMinutes(15), null);
}

catch (Exception ex)
{
  System.out.println("Error message: " + ex.getMessage());
  ex.printStackTrace(); // add this line
}
```
