### ISSUE TITLE
[FEATURE REQ] ADF needs an equivalent of BulkUpdate (available in spark 2.4 connector) in spark 3.1+ connectors of azure-cosmosdb sdk

### ISSUE THREAD

**Issue by akvmsft** [Azure/azure-sdk-for-java#35187]
**Is your feature request related to a problem? Please describe.**
With azure-cosmosdb sdk completely rewritten for spark 3+ versions, backward compatibility of certain aspects in ADF has taken a major hit. We used BulkUpdate in spark 2.4 connector and would want an equivalent of the same in spark 3+ connectors as well. We did know of 'ItemPatch' write strategy, but it seems to have a limitation of updating at-most 5 fields. We would like you to work on getting rid of this limitation or enabling us to have an equivalent of bulk update through a different path.

**Describe the solution you'd like**
We need an easy way to have the same behavior as BulkUpdate in spark 3+ connectors of cosmosdb.

**Describe alternatives you've considered**
Considered using 'ItemPatch' but it comes with a limitation that cannot be accepted from our side.

**Business Impact**
We are assessing the same and will come back with the numbers soon. We would like you to consider this request on priority.

**Information Checklist**
Kindly make sure that you have added all the following information above and checkoff the required fields otherwise we will treat the issuer as an incomplete report
- [x] Description Added
- [x] Expected solution specified

**Comment by TheovanKraay** [comment]
Hello @akvmsft - the [latest release of Spark Connector](https://github.com/Azure/azure-sdk-for-java/blob/main/sdk/cosmos/azure-cosmos-spark_3-4_2-12/CHANGELOG.md#4210-2023-08-09) has support for ItemBulkUpdate to allow patch with more than 10 columns. Please see PR: https://github.com/Azure/azure-sdk-for-java/pull/35977. Closing issue.

**Comment by kushagraThapar** [comment]
@TheovanKraay why did we re-open this issue? Can it be closed?

**Comment by TheovanKraay** [comment]
> @TheovanKraay why did we re-open this issue? Can it be closed?

Not sure why I re-opened. Closing.
