### ISSUE TITLE
Cannot publish message when disposed (AmqpMessagePublisher.IdleTimerExpired)

### ISSUE THREAD

**Issue by YogeshwarPrajapatiTR** [Azure/azure-sdk-for-java#35193]
In my application every 5 to 10 min for check heartbeat, send message to azure service bus. but i got error every day 5 to 10 times for "can not publish message when disposed".
while senderclient.sendmessage method execute then this error occurred, after that it will reconnect automatically and next message send successfully. but current message is failed due to this error.
please go throw below errors which i got.

library used :     implementation group: 'com.azure', name: 'azure-messaging-servicebus', version: '7.8.0'
Sender client : ServiceBusSenderClient

-------
1)com.azure.core.util.logging.ClientLogger.performLogging:Line 506 - Error sending batch.
connectionId[MF_ac424c_1685317800501] linkName[abc.1681890804404_workflow] Cannot publish message when disposed

2) com.azure.core.util.logging.ClientLogger.performLogging:Line 506 - entityPath[abc.1681890804404_workflow], partitionId[1]: Sending messages timed out.
connectionId[MF_ac424c_1685317800501] linkName[abc.1681890804404_workflow] Cannot publish message when disposed.

3) com.azure.core.util.logging.LoggingEventBuilder.performLogging:Line 358 - {"az.sdk.message":"Local link state is not closed.","connectionId":"MF_ac424c_1685317800501","linkName":"abc.1681890804404_workflow","state":"ACTIVE"}

4) com.azure.core.util.logging.LoggingEventBuilder.performLogging:Line 358 - {"az.sdk.message":"onLinkRemoteClose","connectionId":"MF_ac424c_1685317800501","errorCondition":"amqp:link:detach-forced","errorDescription":"The link 'G4S2:15094466:abc.1681890804404_workflow' is force detached. Code: publisher(link74212). Details: AmqpMessagePublisher.IdleTimerExpired: Idle timeout: 00:10:00."

------
After this errors occurred and message failed to send it will reconnect and next message successfully send in queue.
but what about current message which failed due to this exception.

**Comment by YogeshwarPrajapatiTR** [comment]
From last 1 month in production i got 160 errors for this. what the solution or how can i fix this issue.

**Comment by YogeshwarPrajapatiTR** [comment]
Got 5 to 10 Errors everyday related to this issue

**Comment by YogeshwarPrajapatiTR** [comment]
After 2 week not get any update..

**Comment by jorge-barroso** [comment]
We are also getting this error. The last time this happened was last night at 22:10. We build a commercial application pushing millions of records every hour, and these issues are hindering us. Could we get an answer or some help to avoid these issues from happening? Thank you in advance

**Comment by anuchandy** [comment]
@YogeshwarPrajapatiTR Could you update to the latest version of service bus SDK (the version is 7.8.0 is more than a year old, there are many reliability improvements since then)

**Comment by anuchandy** [comment]
We also improved the retry in Send implementation in this PR https://github.com/Azure/azure-sdk-for-java/pull/36227, where it detects use after disposal and take appropriate action to recover. This is slated for Augest 2023 release.

**Comment by anuchandy** [comment]
The august release is completed [7.14.3](https://repo1.maven.org/maven2/com/azure/azure-messaging-servicebus/7.14.3/). Closing the ticket.
