### ISSUE TITLE
Typo "Azure CosmosDB"→"Azure Cosmos DB"

### ISSUE THREAD

**Issue by hyoshioka0128** [Azure/azure-sdk-for-java#35190]
https://learn.microsoft.com/en-us/java/api/overview/azure/cosmos-readme?view=azure-java-stable
#PingMSFTDocs

![image](https://github.com/Azure/azure-sdk-for-java/assets/40815708/68af2530-c314-4a37-8ac8-229fd8351fd9)

![image](https://github.com/Azure/azure-sdk-for-java/assets/40815708/291c7526-87d8-4bfd-90a2-eefed2cff560)

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 3b81205d-e80c-4521-90ee-bc8741abf3af
* Version Independent ID: c42a4e2a-599d-3876-4c89-8e56199e4690
* Content: [Azure CosmosDB Client Library for Java](https://learn.microsoft.com/en-us/java/api/overview/azure/cosmos-readme?view=azure-java-stable)
* Content Source: [docs-ref-services/latest/cosmos-readme.md](https://github.com/Azure/azure-docs-sdk-java/blob/master/docs-ref-services/latest/cosmos-readme.md)
* Service: **cosmos**
* GitHub Login: @kushagraThapar
* Microsoft Alias: **kuthapar**

**Comment by rinatmini** [comment]
> @rinatmini can you please take a look at this, thanks!

Fixed in the spring data cosmos connector and main cosmos docs
