### ISSUE TITLE
[BUG] Spring Boot Azure Data Cosmos repository has no save(S Entity)

### ISSUE THREAD

**Issue by apoguy** [Azure/azure-sdk-for-java#35191]
**Describe the bug**
ReactiveCosmosRepository<T, K> has no save(S entity).

**Code**
AccessRepository
```java
...
import com.azure.spring.data.cosmos.repository.ReactiveCosmosRepository;

@Repository
public interface AccessRepository extends ReactiveCosmosRepository<Access, String> {
}
```

Service:

```java
@Component
public class Register implements Function<RegisterRequest, Mono<RegisterResponse>> {

    @Autowired
    private AccessRepository accessRepository;

...
```

![image](https://github.com/Azure/azure-sdk-for-java/assets/5913516/69378ff7-a9cf-4b62-b486-f88f9b2572fb)

**Setup (please complete the following information):**
 - OS: macos
 - IDE: IntelliJ
 - Library/Libraries: com.azure.spring:spring-cloud-azure-starter-data-cosmos4.8.0, com.azure.spring:spring-cloud-azure-dependencies:5.1.0 
 - Java version: 17
 - App Server/Environment: Spring Boot Azure Function
 - Frameworks: Spring Boot 3.0.7

**Comment by Netyyyy** [comment]
Hi @apoguy , Thanks for reporting.
Refer to [Which Version of Spring Cloud Azure Should I Use](https://github.com/Azure/azure-sdk-for-java/wiki/Spring-Versions-Mapping#which-version-of-spring-cloud-azure-should-i-use)
Could you try with `com.azure.spring:spring-cloud-azure-starter-data-cosmos:4.8.0`, `com.azure.spring:spring-cloud-azure-dependencies:4.8.0` and `SpringBoot:2.x`.

**Comment by sauravBhasin** [comment]
Hi Team, is this issue resolved, we have long pending upgrades stuck due to this.

**Comment by Netyyyy** [comment]
Hi @sauravBhasin , have you tried with the right compatible versions as I mentioned? Does it work?
