### ISSUE TITLE
[QUERY] How to Configure HTTP Proxy with Key Credential

### ISSUE THREAD

**Issue by xuexiaowengh** [Azure/azure-sdk-for-java#35220]
**Query/Question**
Whether the sdk supports proxy access？and  proxy_endpoint is start with http.
eg: 
 ```java
ArrayList<Header> objects = new ArrayList<>();
objects.add(new Header("host","${real_endpoint}"));
objects.add(new Header("Scheme","https"));

HttpClientOptions httpClientOptions = new HttpClientOptions();
httpClientOptions.setHeaders(objects);

HttpClient httpClient = HttpClient.createDefault(httpClientOptions);

OpenAIClient client = new OpenAIClientBuilder()
    .endpoint("${proxy_endpoint}")
    .credential(new AzureKeyCredential("${credential}"))
    .httpClient(httpClient)
    .buildClient();
```

***Why is this not a Bug or a feature Request?***
i just want to know  whether the sdk supports proxy access
**Setup (please complete the following information if applicable):**
 - OS: linux
 - IDE: IntelliJ
 - Library/Libraries: com.azure:azure-core:1.39.0
 
 **Information Checklist**
When I tested it, an exception was thrown: Key credentials require HTTPS to prevent leaking the key.

- [ ] Query Added
- [ ] Setup information Added

**Comment by alzimmermsft** [comment]
Thanks for asking this question @xuexiaowengh.

A proxy can be configured automatically using a few different mechanisms in most SDKs. The most straightforward and convenient would be checking if the client builder, in your case `OpenAIClientBuilder`, implements the `HttpTrait` interface. Implementing `HttpTrait` means that the builder will have a configuration for `ClientOptions`, and for the case of proxying you'll want to pass the subtype `HttpClientOptions` which has a configuration for `ProxyOptions`. The `ProxyOptions` then gets passed along to the creation of the `HttpClient` that sends requests, the only time this doesn't happen is if the builder gets configured with `HttpClient` or `HttpPipeline` as we defer to those configurations instead of `HttpClientOptions`. Here's an example using your code snippet:

```java
// objects can be removed as this isn't necessary for configuring the proxy.
//ArrayList<Header> objects = new ArrayList<>();
//objects.add(new Header("host","${real_endpoint}"));
//objects.add(new Header("Scheme","https"));

HttpClientOptions httpClientOptions = new HttpClientOptions();

// Replace setHeaders with setProxyOptions
//httpClientOptions.setHeaders(objects);
httpClientOptions.setProxyOptions(new ProxyOptions(ProxyOptions.Type.HTTP, proxyInetSocketAddress));

// You can either use HttpClient.createDefault with HttpClientOptions here.
// Or use OpenAIClientBuilder.clientOptions(httpClientOptions) without passing an HttpClient.
// When a client builder doesn't have an HttpClient configured it will create one using this code, or HttpClient.createDefault()
// if ClientOptions aren't configured.
HttpClient httpClient = HttpClient.createDefault(httpClientOptions);

OpenAIClient client = new OpenAIClientBuilder()
   .endpoint("${proxy_endpoint}")
   .credential(new AzureKeyCredential("${credential}"))
   .httpClient(httpClient)
   .buildClient();
```

**Comment by xuexiaowengh** [comment]
> 
thank for your reply, i have an another confussion, if the ${proxy_endpoint} begins with "http"，i found an exception was thrown. so whether the sdk only supports  that the ${proxy_endpoint} begins with "https".

`private final HttpPipelineSyncPolicy inner = new HttpPipelineSyncPolicy() {
        @Override
        protected void beforeSendingRequest(HttpPipelineCallContext context) {
            if ("http".equals(context.getHttpRequest().getUrl().getProtocol())) {
                throw LOGGER.logExceptionAsError(
                    new IllegalStateException("Key credentials require HTTPS to prevent leaking the key."));
            }

            context.getHttpRequest().setHeader(name, credential.getKey());
        }
    };`

**Comment by alzimmermsft** [comment]
The SDKs support both HTTP and HTTPS proxies, from the look of it though your proxy doesn't appear to be a traditional proxy but more a request forwarder given how the `host` header is the real endpoint being called (which I'm guessing the `proxy_endpoint` uses to send the request on).

What you're seeing with the exception is prevention of sending credentials over unsecure network which we don't allow, though thinking about this if the proxy is HTTP-based they'll be sent over unsecure network but proxying is a finer grain configuration where there is some expectation that the proxy is a proxy server.

**Comment by niander** [comment]
> Thanks for asking this question @xuexiaowengh.
> 
> A proxy can be configured automatically using a few different mechanisms in most SDKs. The most straightforward and convenient would be checking if the client builder, in your case `OpenAIClientBuilder`, implements the `HttpTrait` interface. Implementing `HttpTrait` means that the builder will have a configuration for `ClientOptions`, and for the case of proxying you'll want to pass the subtype `HttpClientOptions` which has a configuration for `ProxyOptions`. The `ProxyOptions` then gets passed along to the creation of the `HttpClient` that sends requests, the only time this doesn't happen is if the builder gets configured with `HttpClient` or `HttpPipeline` as we defer to those configurations instead of `HttpClientOptions`. Here's an example using your code snippet:
> 
> ```java
> // objects can be removed as this isn't necessary for configuring the proxy.
> //ArrayList<Header> objects = new ArrayList<>();
> //objects.add(new Header("host","${real_endpoint}"));
> //objects.add(new Header("Scheme","https"));
> 
> HttpClientOptions httpClientOptions = new HttpClientOptions();
> 
> // Replace setHeaders with setProxyOptions
> //httpClientOptions.setHeaders(objects);
> httpClientOptions.setProxyOptions(new ProxyOptions(ProxyOptions.Type.HTTP, proxyInetSocketAddress));
> 
> // You can either use HttpClient.createDefault with HttpClientOptions here.
> // Or use OpenAIClientBuilder.clientOptions(httpClientOptions) without passing an HttpClient.
> // When a client builder doesn't have an HttpClient configured it will create one using this code, or HttpClient.createDefault()
> // if ClientOptions aren't configured.
> HttpClient httpClient = HttpClient.createDefault(httpClientOptions);
> 
> OpenAIClient client = new OpenAIClientBuilder()
>    .endpoint("${proxy_endpoint}")
>    .credential(new AzureKeyCredential("${credential}"))
>    .httpClient(httpClient)
>    .buildClient();
> ```

@alzimmermsft It seems that by not explicitly creating and setting "httpClient" when using a SDK builder, it wouldn't work. At least it seems true for Azure KeyVault Secrets SDK. The `SecretClientBuilder().buildClient()` will end up calling `HttpPipelineBuilder().httpClient(null)` making `HttpPipelineBuilder` to ask for the default `HttpClient` from the service provider. So, it does not pass along the `ClientOptions` (or `HttpClientOptions`) to the inner http client when the user just wants to use the default ones. Could you verify this is true? If yes, I believe this could be characterized as a bug in the builders.
