### ISSUE TITLE
One ChangeFeed read operation is consuming around 30,000 RUs.

### ISSUE THREAD

**Issue by honey-ramgarhia** [Azure/azure-sdk-for-java#35319]
I have built a structured streaming pipeline using in Databricks using `cosmos.oltp.changeFeed` mode. But the stream won't even start and is stuck at initial batch. So I checked the logs for cosmos DB and found out that `ChangeFeedRead` operations were consuming around 30,000 RUs. How can I inspect or what could be the potential reasons that change feed read operation is consuming 30,000 RUs?

Code
```
checkpoint_location = "/mnt/delta/_checkpoints"

read_cfg = {
  "spark.cosmos.accountEndpoint": cosmos_endpoint,
  "spark.cosmos.accountKey": cosmos_key,
  "spark.cosmos.database": cosmos_db,
  "spark.cosmos.container": cosmos_container,
  "spark.cosmos.read.inferSchema.includeSystemProperties": "true",
  "spark.cosmos.read.inferSchema.enabled": "false",
  "spark.cosmos.changeFeed.startFrom": "Beginning",
  "spark.cosmos.changeFeed.mode": "LatestVersion",
  "spark.cosmos.changeFeed.itemCountPerTriggerHint": "100",
  "spark.cosmos.read.maxItemCount": "100"
}

query = (spark
      .readStream
      .format("cosmos.oltp.changeFeed")
      .options(**read_cfg)
      .load())

stream = (query.writeStream
          .format("delta")
          .outputMode("append")
          .option("checkpointLocation", checkpoint_location)
          .toTable("table"))

```

I have tried executing this stream on cosmos container with manual throughput of 5000 RUs.
And average document size is 8KB.

**Comment by FabianMeiswinkel** [comment]
Without information about the account, database and container in question we can't help you with the specific question. In general the RU charge for change feed requests in the service will depend on number of documents being returned and the size of the documents as well as the Spark partitioning strategy. The default partitioning strategy will create at least one Spark partition/task per Executor CPU. When the available compute power in Spark cluster (way more Executors than physical partition in the Cosmos DB data source) it can be benefitial to change the partitioning strategy to restrictive (creating one Spark partition per physical partition in Cosmos DB and so reducing the level of parallelism). You can do that by setting "spark.cosmos.read.partitioning.strategy" to "Restrictive" - see https://github.com/Azure/azure-sdk-for-java/blob/main/sdk/cosmos/azure-cosmos-spark_3_2-12/docs/configuration-reference.md#partitioning-strategy-config.

If you need further assistance and for understandable reasons don't want to share account name, database and container name here, please reach out to our Support and provide the information there.

**Comment by honey-ramgarhia** [comment]
Thanks @FabianMeiswinkel it worked like a charm!
