### ISSUE TITLE
[BUG] Conflicting netty package between azure-storage-blob and spring-boot-starter-data-redis when calling Azure Redis

### ISSUE THREAD

**Issue by AsmaeFILALI** [Azure/azure-sdk-for-java#35354]
**Describe the bug**
Our application employs spring-boot-starter-data-redis to interact with Azure Redis for Cache via a private link, a setup that functioned perfectly until we incorporated the azure-storage-blob library. Upon introducing this new library, we observed that our Azure Cache for Redis access through the private link ceased functioning. We discovered that a conflict in the netty package between the two libraries was the root cause, with azure-storage-blob relying on an outdated version of the package. The issue was temporarily resolved by excluding netty from azure-storage-blob, which reinstated the function of Azure Cache. However, we aim to use both libraries without resorting to the stopgap solution of exclusion, as it could potentially affect our application's functioning.

***Exception or Stack Trace***
Unable to connect to Redis; nested exception is io.lettuce.core.RedisConnextionException : unable to connect to "rediscachename.redis.cache.windows.net":6380

**To Reproduce**

- Have an app service with java SE 11 runtime and vnet integration to  a vnet "vnetA"
- Have an azure cache for redis with ssl port only and a private link the "vnetA"
- Use the following java code for using Azure Cache for redis (from azure samples) : https://github.com/Azure-Samples/java-on-azure-examples/tree/main/redis/springboot-azureredis
- Add to the pom file the library azure-storage-blob https://mvnrepository.com/artifact/com.azure/azure-storage-blob/12.22.2
- Deploy the code to the app service
- Call the app service with POST /product/add with the payload   {  "id": "4",  "name": "tajine" }
- Call the app service with GET /product/4, It will return 500 with the error : "rediscachename.redis.cache.windows.net :  6380 unable to connect "

***Code Snippet***
Adding the following dependency to pom.xml
com.azure: azure-storage-blob:12.22.2

**Expected behavior**
apps that have the dependency spring-boot-starter-data-redis and calls Azure Cache for Redis via private link continue to work when we add the dependency azure-storage-blob

**Screenshots**

**Setup (please complete the following information):**
 - OS: linux or windows (issue is in both)
 - IDE:  vsCode
 - Library/Libraries:  com.azure:azure-storage-blob:12.22.2 
 - Java version: 11
 - App Server/Environment: Azure App Service with Java web server Java SE (Embedded web server)
 - Frameworks:  Spring Boot

If you suspect a dependency version mismatch (e.g. you see `NoClassDefFoundError`, `NoSuchMethodError` or similar), please check out [Troubleshoot dependency version conflict article](https://aka.ms/azsdk/java/dependency/troubleshoot) first. If it doesn't provide solution for the problem, please provide:

- verbose dependency tree (`mvn dependency:tree -Dverbose`)
com.asmexple:demoredis:jar:0.0.1-SNAPSHOT
 +- org.springframework.boot:spring-boot-starter-data-redis:jar:2.5.12:compile
 |  +- org.springframework.boot:spring-boot-starter:jar:2.5.12:compile
 |  |  +- org.springframework.boot:spring-boot:jar:2.5.12:compile
 |  |  +- org.springframework.boot:spring-boot-autoconfigure:jar:2.5.12:compile
 |  |  +- org.springframework.boot:spring-boot-starter-logging:jar:2.5.12:compile
 |  |  |  +- ch.qos.logback:logback-classic:jar:1.2.11:compile
 |  |  |  |  \- ch.qos.logback:logback-core:jar:1.2.11:compile
 |  |  |  +- org.apache.logging.log4j:log4j-to-slf4j:jar:2.17.2:compile
 |  |  |  |  \- org.apache.logging.log4j:log4j-api:jar:2.17.2:compile
 |  |  |  \- org.slf4j:jul-to-slf4j:jar:1.7.36:compile
 |  |  +- jakarta.annotation:jakarta.annotation-api:jar:1.3.5:compile
 |  |  \- org.yaml:snakeyaml:jar:1.28:compile
 |  +- org.springframework.data:spring-data-redis:jar:2.5.10:compile
 |  |  +- org.springframework.data:spring-data-keyvalue:jar:2.5.10:compile
 |  |  +- org.springframework:spring-tx:jar:5.3.18:compile
 |  |  +- org.springframework:spring-oxm:jar:5.3.18:compile
 |  |  +- org.springframework:spring-aop:jar:5.3.18:compile
 |  |  \- org.slf4j:slf4j-api:jar:1.7.36:compile
 |  \- io.lettuce:lettuce-core:jar:6.1.8.RELEASE:compile
 |     +- io.netty:netty-common:jar:4.1.75.Final:compile
 |     +- io.netty:netty-handler:jar:4.1.75.Final:compile
 |     |  \- io.netty:netty-resolver:jar:4.1.75.Final:compile
 |     +- io.netty:netty-transport:jar:4.1.75.Final:compile
 |     \- io.projectreactor:reactor-core:jar:3.4.16:compile
 |        \- org.reactivestreams:reactive-streams:jar:1.0.3:compile
 +- org.springframework.boot:spring-boot-starter-web:jar:2.5.12:compile
 |  +- org.springframework.boot:spring-boot-starter-json:jar:2.5.12:compile
 |  |  +- com.fasterxml.jackson.core:jackson-databind:jar:2.12.6.1:compile
 |  |  +- com.fasterxml.jackson.datatype:jackson-datatype-jdk8:jar:2.12.6:compile
 |  |  +- com.fasterxml.jackson.datatype:jackson-datatype-jsr310:jar:2.12.6:compile
 |  |  \- com.fasterxml.jackson.module:jackson-module-parameter-names:jar:2.12.6:compile
 |  +- org.springframework.boot:spring-boot-starter-tomcat:jar:2.5.12:compile
 |  |  +- org.apache.tomcat.embed:tomcat-embed-core:jar:9.0.60:compile
 |  |  +- org.apache.tomcat.embed:tomcat-embed-el:jar:9.0.60:compile
 |  |  \- org.apache.tomcat.embed:tomcat-embed-websocket:jar:9.0.60:compile
 |  +- org.springframework:spring-web:jar:5.3.18:compile
 |  |  \- org.springframework:spring-beans:jar:5.3.18:compile
 |  \- org.springframework:spring-webmvc:jar:5.3.18:compile
 |     +- org.springframework:spring-context:jar:5.3.18:compile
 |     \- org.springframework:spring-expression:jar:5.3.18:compile
 +- org.springframework.boot:spring-boot-starter-test:jar:2.5.12:test
 |  +- org.springframework.boot:spring-boot-test:jar:2.5.12:test
 |  +- org.springframework.boot:spring-boot-test-autoconfigure:jar:2.5.12:test
 |  +- com.jayway.jsonpath:json-path:jar:2.5.0:test
 |  |  \- net.minidev:json-smart:jar:2.4.8:test
 |  |     \- net.minidev:accessors-smart:jar:2.4.8:test
 |  |        \- org.ow2.asm:asm:jar:9.1:test
 |  +- jakarta.xml.bind:jakarta.xml.bind-api:jar:2.3.3:compile
 |  |  \- jakarta.activation:jakarta.activation-api:jar:1.2.2:compile
 |  +- org.assertj:assertj-core:jar:3.19.0:test
 |  +- org.hamcrest:hamcrest:jar:2.2:test
 |  +- org.junit.jupiter:junit-jupiter:jar:5.7.2:test
 |  |  +- org.junit.jupiter:junit-jupiter-api:jar:5.7.2:test
 |  |  |  +- org.apiguardian:apiguardian-api:jar:1.1.0:test
 |  |  |  +- org.opentest4j:opentest4j:jar:1.2.0:test
 |  |  |  \- org.junit.platform:junit-platform-commons:jar:1.7.2:test
 |  |  +- org.junit.jupiter:junit-jupiter-params:jar:5.7.2:test
 |  |  \- org.junit.jupiter:junit-jupiter-engine:jar:5.7.2:test
 |  |     \- org.junit.platform:junit-platform-engine:jar:1.7.2:test
 |  +- org.mockito:mockito-core:jar:3.9.0:test
 |  |  +- net.bytebuddy:byte-buddy:jar:1.10.22:compile
 |  |  +- net.bytebuddy:byte-buddy-agent:jar:1.10.22:test
 |  |  \- org.objenesis:objenesis:jar:3.2:test
 |  +- org.mockito:mockito-junit-jupiter:jar:3.9.0:test
 |  +- org.skyscreamer:jsonassert:jar:1.5.0:test
 |  |  \- com.vaadin.external.google:android-json:jar:0.0.20131108.vaadin1:test
 |  +- org.springframework:spring-core:jar:5.3.18:compile
 |  |  \- org.springframework:spring-jcl:jar:5.3.18:compile
 |  +- org.springframework:spring-test:jar:5.3.18:test
 |  \- org.xmlunit:xmlunit-core:jar:2.8.4:test
 +- org.projectlombok:lombok:jar:1.18.22:compile (optional)
 +- com.h2database:h2:jar:1.4.200:runtime
 +- org.springframework.boot:spring-boot-starter-cache:jar:2.5.12:compile
 |  \- org.springframework:spring-context-support:jar:5.3.18:compile
 +- org.springframework.boot:spring-boot-starter-data-jpa:jar:2.5.12:compile
 |  +- org.springframework.boot:spring-boot-starter-aop:jar:2.5.12:compile
 |  |  \- org.aspectj:aspectjweaver:jar:1.9.7:compile
 |  +- org.springframework.boot:spring-boot-starter-jdbc:jar:2.5.12:compile
 |  |  +- com.zaxxer:HikariCP:jar:4.0.3:compile
 |  |  \- org.springframework:spring-jdbc:jar:5.3.18:compile
 |  +- jakarta.transaction:jakarta.transaction-api:jar:1.3.3:compile
 |  +- jakarta.persistence:jakarta.persistence-api:jar:2.2.3:compile
 |  +- org.hibernate:hibernate-core:jar:5.4.33:compile
 |  |  +- org.jboss.logging:jboss-logging:jar:3.4.3.Final:compile
 |  |  +- org.javassist:javassist:jar:3.27.0-GA:compile
 |  |  +- antlr:antlr:jar:2.7.7:compile
 |  |  +- org.jboss:jandex:jar:2.2.3.Final:compile
 |  |  +- com.fasterxml:classmate:jar:1.5.1:compile
 |  |  +- org.dom4j:dom4j:jar:2.1.3:compile
 |  |  +- org.hibernate.common:hibernate-commons-annotations:jar:5.1.2.Final:compile
 |  |  \- org.glassfish.jaxb:jaxb-runtime:jar:2.3.6:compile
 |  |     +- org.glassfish.jaxb:txw2:jar:2.3.6:compile
 |  |     +- com.sun.istack:istack-commons-runtime:jar:3.0.12:compile
 |  |     \- com.sun.activation:jakarta.activation:jar:1.2.2:runtime
 |  +- org.springframework.data:spring-data-jpa:jar:2.5.10:compile
 |  |  +- org.springframework.data:spring-data-commons:jar:2.5.10:compile
 |  |  \- org.springframework:spring-orm:jar:5.3.18:compile
 |  \- org.springframework:spring-aspects:jar:5.3.18:compile
 \- com.azure:azure-storage-blob:jar:12.22.2:compile
    +- com.azure:azure-core:jar:1.39.0:compile
    |  +- com.azure:azure-json:jar:1.0.1:compile
    |  +- com.fasterxml.jackson.core:jackson-annotations:jar:2.12.6:compile
    |  \- com.fasterxml.jackson.core:jackson-core:jar:2.12.6:compile
    +- com.azure:azure-core-http-netty:jar:1.13.3:compile
    |  +- io.netty:netty-handler-proxy:jar:4.1.75.Final:compile
    |  |  \- io.netty:netty-codec-socks:jar:4.1.75.Final:compile
    |  +- io.netty:netty-buffer:jar:4.1.75.Final:compile
    |  +- io.netty:netty-codec:jar:4.1.75.Final:compile
    |  +- io.netty:netty-codec-http:jar:4.1.75.Final:compile
    |  +- io.netty:netty-codec-http2:jar:4.1.75.Final:compile
    |  +- io.netty:netty-transport-native-unix-common:jar:4.1.75.Final:compile
    |  +- io.netty:netty-transport-native-epoll:jar:linux-x86_64:4.1.75.Final:compile
    |  |  \- io.netty:netty-transport-classes-epoll:jar:4.1.75.Final:compile
    |  +- io.netty:netty-transport-native-kqueue:jar:osx-x86_64:4.1.75.Final:compile
    |  |  \- io.netty:netty-transport-classes-kqueue:jar:4.1.75.Final:compile
    |  +- io.netty:netty-tcnative-boringssl-static:jar:2.0.51.Final:compile
    |  |  +- io.netty:netty-tcnative-classes:jar:2.0.51.Final:compile
    |  |  +- io.netty:netty-tcnative-boringssl-static:jar:linux-x86_64:2.0.51.Final:compile
    |  |  +- io.netty:netty-tcnative-boringssl-static:jar:linux-aarch_64:2.0.51.Final:compile
    |  |  +- io.netty:netty-tcnative-boringssl-static:jar:osx-x86_64:2.0.51.Final:compile
    |  |  +- io.netty:netty-tcnative-boringssl-static:jar:osx-aarch_64:2.0.51.Final:compile
    |  |  \- io.netty:netty-tcnative-boringssl-static:jar:windows-x86_64:2.0.51.Final:compile
    |  \- io.projectreactor.netty:reactor-netty-http:jar:1.0.17:compile
    |     +- io.netty:netty-resolver-dns:jar:4.1.75.Final:compile
    |     |  \- io.netty:netty-codec-dns:jar:4.1.75.Final:compile
    |     +- io.netty:netty-resolver-dns-native-macos:jar:osx-x86_64:4.1.75.Final:compile
    |     |  \- io.netty:netty-resolver-dns-classes-macos:jar:4.1.75.Final:compile
    |     \- io.projectreactor.netty:reactor-netty-core:jar:1.0.17:compile
    +- com.azure:azure-storage-common:jar:12.21.1:compile
    +- com.azure:azure-storage-internal-avro:jar:12.7.1:compile
    \- com.fasterxml.jackson.dataformat:jackson-dataformat-xml:jar:2.12.6:compile
       +- com.fasterxml.jackson.module:jackson-module-jaxb-annotations:jar:2.12.6:compile
       +- org.codehaus.woodstox:stax2-api:jar:4.2.1:compile
       \- com.fasterxml.woodstox:woodstox-core:jar:6.2.4:compile
- exception message, full stack trace, and any available logs
Unable to connect to Redis; nested exception is io.lettuce.core.RedisConnextionException : unable to connect to "rediscachename.redis.cache.windows.net":6380
**Additional context**

**Information Checklist**
Kindly make sure that you have added all the following information above and checkoff the required fields otherwise we will treat the issuer as an incomplete report
- [ x ] Bug Description Added
- [ x ] Repro Steps Added
- [ x ] Setup information Added

**Comment by alzimmermsft** [comment]
Thank you for filing this @AsmaeFILALI.

The outdated version of Netty is actually due to the dependencies being used by `spring-boot-starter-data-redis` `2.5.12`. It depends on `lettuce-core` `6.1.8.RELEASE` which in turn depends on the versions of Netty you're seeing resolved, https://mvnrepository.com/artifact/io.lettuce/lettuce-core/6.1.8.RELEASE.

<img width="1180" alt="image" src="https://github.com/Azure/azure-sdk-for-java/assets/48699787/3c652eaf-980f-4dc0-9977-b2e55c9551d7">

The root issue happening is that `azure-storage-blob` `12.22.2` depends on much newer versions of Netty, `4.1.89.Final` for all the non-tcnative dependencies and `2.0.56.Final` for the tcnative dependency.

There are a few possible options to resolve this:

- Override the dependency of `lettuce-core` to a newer version not using as old Netty dependencies.
- Downgrade the version of `azure-storage-blob` to one that aligns more closely with the Netty dependencies used by `lettuce-core` `6.1.8.RELEASE`.
- Upgrade the version of `spring-boot-starter-data-redis` to the latest `2.7.x` version (though this may not work well as that still uses an older version of `lettuce-core` that depends on fairly old Netty dependencies, `4.1.82.Final`).

**Comment by AsmaeFILALI** [comment]
Thanks a lot  for your response @alzimmermsft, for the 3d option, upgrading the spring-boot-starter-data-redis to 2.7.x we already tried that , and as you expected it did not work

**Comment by alzimmermsft** [comment]
That's unfortunate, given that I'd look into upgrading `lettuce-core` to `6.2.4.RELEASE` as that updates the Netty dependencies being used by the library. Or, downgrading `azure-storage-blob` to `12.16.0` would bring down the dependencies used by Storage Blob to be inline with the dependencies being used by `spring-boot-starter-data-redis` `2.5.12`. And one last option would be reordering the dependencies in the `pom.xml` as that will have Maven tiebreak dependency conflicts with the dependencies in `azure-storage-blob` (https://maven.apache.org/guides/introduction/introduction-to-dependency-mechanism.html#transitive-dependencies).

**Comment by lmolkova** [comment]
Hi @AsmaeFILALI,  could you please collect some logs (and traces if you have them enabled) for us? 

Here's how to enable Azure SDK [logging](https://learn.microsoft.com/en-us/azure/developer/java/sdk/logging-overview). `INFO` level should be ok, but if you can, sharing verbose logs would be even better.

If you have [distributed tracing](https://learn.microsoft.com/en-us/azure/developer/java/sdk/tracing) enabled, would you also be able to export collected traces for the relevant operation(s) and share them with us?

Thanks!

**Comment by AsmaeFILALI** [comment]
Thank you @lmolkova and @alzimmermsft  for your response, in fact there is some news : 
During my examination of the logs, I noticed this line: `"[Default DNS servers: [/8.8.8.8:53, /8.8.4.4:53] (Google Public DNS as a fallback {"LoggerName":"io.netty.resolver.dns.DefaultDnsServerAddressStreamProvider","SourceType":"Logger","ThreadName":"main"}]" ` suggesting that the Google DNS is being used. This originates from the DNS resolver within the `io.netty:netty-resolver-dns` library, which is contained within `io.projectreactor.netty:reactor-netty-http`, itself under `com.azure:azure-storage-blob`.

By excluding `io.netty:netty-resolver-dns` from `io.projectreactor.netty:reactor-netty-http` (which is under `com.azure:azure-storage-blob`), the project began working again. I believe the root cause to be the DNS resolver `io.netty:netty-resolver-dns` within `io.projectreactor.netty:reactor-netty-http`. This makes sense given that the error we are experiencing stems from spring-data-redis's failure to resolve the Azure Cache for Redis private link address after adding the `com.azure:azure-storage-blob` library to the project, which sets up a DNS for Netty different from that of Azure. Here is the pom configuration that made it work : 
```xml
	<dependencies>
		<dependency>
			<groupId>com.azure</groupId>
			<artifactId>azure-storage-blob</artifactId>
			<version>12.22.2</version>
			<exclusions>
				<exclusion>
					<groupId>com.azure</groupId>
					<artifactId>azure-core-http-netty</artifactId>
				</exclusion>
			</exclusions>
		</dependency>
		<dependency>
			<groupId>com.azure</groupId>
			<artifactId>azure-core-http-netty</artifactId>
			<version>1.13.3</version>
			<exclusions>
				<exclusion>
					<groupId>io.projectreactor.netty</groupId>
					<artifactId>reactor-netty-http</artifactId>
				</exclusion>
			</exclusions>
		</dependency>
		<dependency>
			<groupId>io.projectreactor.netty</groupId>
			<artifactId>reactor-netty-http</artifactId>
			<version>1.0.32</version>
			<exclusions>
				<exclusion>
					<groupId>io.netty</groupId>
					<artifactId>netty-resolver-dns</artifactId>
				</exclusion>
			</exclusions>
		</dependency>
```
Is there any solution other than exclusion for remediating this behavior  ? thank you a lot  :)

**Comment by alzimmermsft** [comment]
@AsmaeFILALI, it looks like Netty allows for the configuration of the fallback DNS server, added in this change: https://github.com/netty/netty/pull/13065/files. Configuring this should unblock the customer by using the DNS server that works with Private Link.

**Comment by alzimmermsft** [comment]
Another potential solution is using a different HTTP stack provided by the Azure SDKs. The following example is using the OkHttp HTTP stack:

```xml
<dependency>
    <groupId>com.azure</groupId>
    <artifactId>azure-storage-blob</artifactId>
    <version>12.22.2</version>
    <exclusions>
        <exclusion>
	    <groupId>com.azure</groupId>
	    <artifactId>azure-core-http-netty</artifactId>
	</exclusion>
    </exclusions>
</dependency>
<dependency>
    <groupId>com.azure</groupId>
    <artifactId>azure-core-http-okhttp</artifactId>
    <version>1.11.9</version>
</dependency>
```

Note: the `azure-core-http-netty` exclusion will have to be done for every Azure SDK being used in the application.

**Comment by alzimmermsft** [comment]
Lastly, it appears that Spring has documentation on how to use `Configuration` and `Beans` to modify the connection factory. Taking the example on observability (https://github.com/spring-projects/spring-data-redis/blob/main/src/main/asciidoc/reference/observability.adoc) it can be mutated a bit to force the JVM default DNS resolver:

```java
@Configuration
class DnsConfiguration {

    @Bean
    public ClientResources clientResources() {
        return DefaultClientResources.builder()
            .dnsResolver(DnsResolver.jvmDefault())
            .build();
    }

    @Bean
    public LettuceConnectionFactory lettuceConnectionFactory(ClientResources clientResources) {
        LettuceClientConfiguration clientConfig = LettuceClientConfiguration.builder()
            .clientResources(clientResources).build();
        RedisConfiguration redisConfiguration = …;
        return new LettuceConnectionFactory(redisConfiguration, clientConfig);
    }
}
```

**Comment by AsmaeFILALI** [comment]
Appreciate your assistance, @alzimmermsft . I'll put your proposed solution to the test and revert back with my findings. Meanwhile, I wanted to inquire about future azure-storage-blob updates. As it's a sub-library that automatically integrates the DNS resolver, would it be possible for upcoming versions to include the azure DNS resolver configuration by default? This could be a beneficial feature. Thank you again :)

**Comment by AsmaeFILALI** [comment]
Thank you for your reply, @alzimmermsft . The previously suggested solution of integrating the configuration `.dnsResolver(DnsResolver.jvmDefault())` and using the `lettuceconnectionfactory`  didn't bring any changes to the prior behavior. The `io.netty.resolver.dns.DefaultDnsServerAddressStreamProvider` class still fetches an empty list of the default environment DNS servers. This, in turn, defaults to Google's fallback DNS address.

Nonetheless, the problem was successfully addressed when I designated Azure DNS as the fallback DNS. This was achieved by incorporating the `JAVA_OPTS -Dio.netty.resolver.dns.defaultNameServerFallback=168.63.129.16` into the app setting, as you previously recommended

**Comment by alzimmermsft** [comment]
That's great new @AsmaeFILALI that this was able to be resolved. I'll leave the other options in this issue as they make work but just might need further configuration as I only took a quick look into how Spring and Lettuce Core handle configurations, so something may be missing.

I'll go ahead and close this as resolved.
