### ISSUE TITLE
[BUG] azure-identity requiring a snapshot dependency

### ISSUE THREAD

**Issue by EricBuist** [Azure/azure-sdk-for-java#35375]
**Describe the bug**
The com.azure:azure-identity:1.9.0 and 1.9.1 depend on a snapshot artifact  net.minidev:json-smart:jar:2.3-SNAPSHOT that cannot be found anymore. Non-snapshot artifacts should not depend on snapshots.

***Exception or Stack Trace***
Maven fails at downloading the snapshot artifact.
 Could not resolve dependencies for project com.nuance.test:testml:jar:0.0.1: Failed to collect dependencies at com.azure:azure-identity:jar:1.9.1 -> com.microsoft.azure:msal4j:jar:1.13.8 -> com.nimbusds:oauth2-oidc-sdk:jar:10.7.1 -> net.minidev:json-smart:jar:2.3-SNAPSHOT

**To Reproduce**
Create a project depending on the azure-identify artifact and try to mvn package it.

**Expected behavior**
azure-identity artifact should not have any dependency on a snapshot.

**Setup (please complete the following information):**
 - OS: Windows
 - IDE: Visual Studio Code
 - Library/Libraries: azure-identity:1.9.0
 - Java version: 17

**Information Checklist**
Kindly make sure that you have added all the following information above and checkoff the required fields otherwise we will treat the issuer as an incomplete report
- [x] Bug Description Added
- [x] Repro Steps Added
- [x] Setup information Added

**Comment by billwert** [comment]
I'm not able to reproduce this. Spoke to @EricBuist offline and it is likely a local configuration issue he's going to track down. 

Relevant dependency tree from my sample project:
```
[INFO] |  +- com.microsoft.azure:msal4j:jar:1.13.8:compile
[INFO] |  |  +- com.nimbusds:oauth2-oidc-sdk:jar:10.7.1:compile
[INFO] |  |  |  +- com.github.stephenc.jcip:jcip-annotations:jar:1.0-1:compile
[INFO] |  |  |  +- com.nimbusds:content-type:jar:2.2:compile
[INFO] |  |  |  +- com.nimbusds:lang-tag:jar:1.7:compile
[INFO] |  |  |  \- com.nimbusds:nimbus-jose-jwt:jar:9.30.2:compile
[INFO] |  |  \- net.minidev:json-smart:jar:2.4.10:compile
[INFO] |  |     \- net.minidev:accessors-smart:jar:2.4.9:compile
[INFO] |  |        \- org.ow2.asm:asm:jar:9.3:compile
```

Additionally [`oauth2-odic-sdk`](https://central.sonatype.com/artifact/com.nimbusds/oauth2-oidc-sdk/10.7.1/dependencies) doesn't depend on `json-smart` directly, so it's not clear where this dependency is coming from.

**Comment by joshfree** [comment]
@EricBuist could you check https://learn.microsoft.com/en-us/azure/developer/java/sdk/troubleshooting-dependency-version-conflict to see if this helps resolve the issue?  If we have misunderstand anything please feel free to reactivate!

Thanks

**Comment by EricBuist** [comment]
> @EricBuist could you check https://learn.microsoft.com/en-us/azure/developer/java/sdk/troubleshooting-dependency-version-conflict to see if this helps resolve the issue? If we have misunderstand anything please feel free to reactivate!
> 
> Thanks

Hi, the problem still persists and the only workaround is to explicitly import json-assert in our project. More specifically, oauth2-oidc-sdk, transitively imported by azure-identity, breaks the dependency chain by requesting json-smart between 1.3.3 and 2.4.10. Although Maven's documentation tells otherwise, Maven wrongly picks 2.3-SNAPSHOT which is partially deployed on our internal Maven repository. This may be a bug with Maven 3.8, but we cannot upgrade to Maven 3.9 because our library uses Wagon HTTP to download some resources from an internal HTTP server, and that doesn't work anymore with Maven 3.9.
