### ISSUE TITLE
[QUERY] Use floats for openai embeddings?

### ISSUE THREAD

**Issue by zero11-0203** [Azure/azure-sdk-for-java#35397]
**Query/Question**
Use floats for openai embeddings?

Embeddings are usually represented as floats (not sure)?
[azure net SDK uses floats for embeddings](https://github.com/Azure/azure-sdk-for-net/blob/270d175ad30f78e90209ddc91aca75357257eadb/sdk/openai/Azure.AI.OpenAI/src/Generated/EmbeddingItem.cs#L49)

**Comment by joshfree** [comment]
@mssfang could you follow up with @zero11-0203 on their question?

**Comment by mssfang** [comment]
@zero11-0203  Thanks for the reach out. 
Yes. We had a discussion on what type should be for this. .NET uses the `float` type for now but need more proof that is what the OpenAI community uses. If the investigation is done. .NET and Java will align with the same data type for sure. I would expect it will be resolved in the next few weeks.
