### ISSUE TITLE
[QUERY] Leading '?' in SAS tokens

### ISSUE THREAD

**Issue by turcsanyip** [Azure/azure-sdk-for-java#35413]
**Query/Question**
We use Azure SDK for Java to access ADLS and set SAS token via `DataLakeServiceClientBuilder.sasToken()`.
It used to accept leading '?' in the SAS token (I believe it worked even a month ago) but now I get "Signature fields not well formed" error.
Looked into the the API calls, `DataLakeFileSystemClient.createFile()` works but `renameWithResponse()` does not.
Is it a change on the server side? (I did not upgrade client library on my side)
My understanding is that the SAS token is sanitized by the client library and the leading '?' should be removed if specified. However, it seems it does not work now.

**Comment by ibrahimrabab** [comment]
Hi @turcsanyip 
Thanks for reaching out! Did you upgrade the version of Data Lake to the newest version? Can you tell us what version of Data Lake was working for you before you started seeing this error?

**Comment by ibrahimrabab** [comment]
@turcsanyip 
It turns out that the `rename` did not account for sas tokens with leading "?"'s. Thank you for pointing this out! We have the fix merged and hopefully should have this fix as part of our next release.

**Comment by turcsanyip** [comment]
Thanks @ibrahimrabab!
