### ISSUE TITLE
[BUG][IntelliJ] Azure-Identity not using SharedTokenCacheCredential for IntelliJCredential plugin

### ISSUE THREAD

**Issue by werned** [Azure/azure-sdk-for-java#35419]
#### Setup

IntelliJ build version: 2023.1 IC-231.8109.175
OS: Windows 10
JDK: JetBrains s.r.o. 17.0.6
Plugin version: 3.76.1-2023.1

####  Describe the bug

I'm using the Azure Tools for IntelliJ plugin, and I've signed in appropriately via the Tools -> Azure -> Sign in method
When I run my application to access a key vault secret, I receive the following error:

```
[ForkJoinPool.commonPool-worker-1] ERROR com.azure.identity.implementation.IdentityClient - IntelliJ Authentication not available. Please log in with Azure Tools for IntelliJ plugin in the IDE.
IntelliJ Authentication not available. Please log in with Azure Tools for IntelliJ plugin in the IDE.
```

When I debug, I noticed that the file "AuthMethodDetails.json" is not in the expected folder. The expected folder looks like it should be: C:\Users\<USER>\.AzureToolsForIntelliJ but there is no file in that folder.

I've tried using the DefaultAzureCredential but because I currently have an older version of the Azure CLI, a stdout message is failing the JSON parsing of the access token when it attempts to get credentials via the Azure CLI. I'm waiting to get a newer version installed and was hoping to use the IntelliJ Plugin as a workaround.

[wangmingliang-ms](https://github.com/wangmingliang-ms) from azure-tools-for-java suggested that the issue lies with Azure Identity instead as the IntelliJ plugin has already migrated to SharedTokenCacheCredential, and suggested I open a new bug here. [IntelliJ Plug bug](https://github.com/microsoft/azure-tools-for-java/issues/7587) is the original bug I opened.

####  To Reproduce

Download the Azure Toolkit for IntelliJ. Sign in to your Azure Account. Run an application using the IntelliJCredential builder.

#### Exception or Stack Trace

```
[ForkJoinPool.commonPool-worker-1] ERROR com.azure.identity.implementation.IdentityClient - IntelliJ Authentication not available. Please log in with Azure Tools for IntelliJ plugin in the IDE.
IntelliJ Authentication not available. Please log in with Azure Tools for IntelliJ plugin in the IDE.
```

**Comment by alzimmermsft** [comment]
@billwert, @g2vinay could you take a look at this

**Comment by g2vinay** [comment]
@werned can you try the latest azure-identity release, v.1.9.1 and see if the issue still persists. 
we recently released a fix for Windows platform, it might be related to the issue you're facing.

**Comment by g2vinay** [comment]
Let us know if the issue still persists after upgrading azure-identity to latest version.
Closing the issue.
