### ISSUE TITLE
[BUG] WebPubSubServiceAsyncClient: IllegalStateException block()/blockFirst()/blockLast() are blocking, which is not supported in thread reactor-http-nio-5

### ISSUE THREAD

**Issue by camelmann** [Azure/azure-sdk-for-java#35429]
**Describe the bug**
I want to generate an access token to access a web pubsub service, I use the `WebPubSubServiceClientBuilder` to create a client.
When using `WebPubSubServiceAsyncClient` to `getClientAccessToken` the call fails with `IllegalStateException`.

***Exception or Stack Trace***

```
java.lang.IllegalStateException: block()/blockFirst()/blockLast() are blocking, which is not supported in thread reactor-http-nio-5
	at reactor.core.publisher.BlockingSingleSubscriber.blockingGet(BlockingSingleSubscriber.java:83)
	Suppressed: The stacktrace has been enhanced by Reactor, refer to additional information below: 
Assembly trace from producer [reactor.core.publisher.MonoMapFuseable] :
	reactor.core.publisher.Mono.map
	com.azure.messaging.webpubsub.WebPubSubServiceAsyncClient.getClientAccessToken(WebPubSubServiceAsyncClient.java:73)
Error has been observed at the following site(s):
	*______________Mono.map ⇢ at com.azure.messaging.webpubsub.WebPubSubServiceAsyncClient.getClientAccessToken(WebPubSubServiceAsyncClient.java:73)

```

**To Reproduce**

```
var servicePrincipalToken = new ClientSecretCredentialBuilder()
        .tenantId(TENANT_ID)
        .clientId(CLIENT_ID)
        .clientSecret(CLIENT_SECRET)
        .build();

WebPubSubServiceAsyncClient service = new WebPubSubServiceClientBuilder()
        .credential(servicePrincipalToken)
        .endpoint(ENDPOINT)
        .hub(HUB)
        .buildAsyncClient();

var option = new GetClientAccessTokenOptions();

var clientToken = service.getClientAccessToken(option);

```

**Expected behavior**
The token is present.

**Setup (please complete the following information):**
 - OS: win 10
 - IDE: IntelliJ
 - Library/Libraries: `com.azure:azure-messaging-webpubsub:1.2.4` and `com.azure:azure-identity:1.9.0`
 - Java version: 17
 - Frameworks: Spring Boot 3,6

**Information Checklist**
Kindly make sure that you have added all the following information above and checkoff the required fields otherwise we will treat the issuer as an incomplete report
- [x] Bug Description Added
- [x] Repro Steps Added
- [x] Setup information Added

**Comment by joshfree** [comment]
@conniey could you please help get this routed?

**Comment by conniey** [comment]
I could not reproduce this issue in the latest version. It looks to be resolved.
