### ISSUE TITLE
Is it something like:

### ISSUE THREAD

**Issue by screwball22** [Azure/azure-sdk-for-java#35438]
Is it something like:
```bash
fail2ban-regex --out-action 'my-action[prm1="val1",...]' $log $filter
```
Or:
```bash
fail2ban-regex --out-tags $log $filter
```
Could you provide an example, just for better understanding, what do you mean with `supply a function`. E. g. something like the command-line you wish.

_Originally posted by @sebres in https://github.com/fail2ban/fail2ban/issues/2036#issuecomment-361867203_

**Comment by alzimmermsft** [comment]
Closing as this issue it out of context and doesn't appear to be related to Azure SDKs for Java.
