### ISSUE TITLE
Starting a machine, custom script customData does not take effect

### ISSUE THREAD

**Issue by liukaiAs** [Azure/azure-sdk-for-java#35460]
code:

        String resourceId = IdGenerator.createId();
        //virtual network
        Network network = azureResourceManager.networks().getByResourceGroup(azureCreateDto.getResourceGroup(), azureCreateDto.getVirtualNetwork());

        //public ip name
        String publicIpName = PUBLICIP+"-"+resourceId;
        //public ip
        PublicIpAddress publicIPAddress = null;
        try{
             publicIPAddress = azureResourceManager.publicIpAddresses()
                    .define(publicIpName)
                    .withRegion(azureCreateDto.getRegion())
                    .withExistingResourceGroup(azureCreateDto.getResourceGroup())
                    .withDynamicIP()
                    .withTag(TAG_ENV,azureCreateDto.getEnv())
                    .create();
        }catch (ManagementException e) {
            log.error("create publicIPAddress exception by instanceName:{} region:{}",azureCreateDto.getInstanceName(),azureCreateDto.getRegion(),e);
            throw new CustomException(e.getResponse().getStatusCode(), VmCreateMsg.CREATE_PUBLICIPADDRESS_EXCEPTION.msg(),e);
        }

        String networkInterfaceName = NETWORK+"-"+resourceId;
        //network interface
        NetworkInterface networkInterface = null;
        try{
            NetworkInterface.DefinitionStages.WithCreate withCreate = azureResourceManager.networkInterfaces()
                    .define(networkInterfaceName)
                    .withRegion(azureCreateDto.getRegion())
                    .withExistingResourceGroup(azureCreateDto.getResourceGroup())
                    .withExistingPrimaryNetwork(network)
                    .withSubnet(azureCreateDto.getSubnet())
                    .withPrimaryPrivateIPAddressDynamic()
                    .withExistingPrimaryPublicIPAddress(publicIPAddress)
                    .withTag(TAG_ENV,azureCreateDto.getEnv());
            //security group
            if(StringUtils.isNotBlank(azureCreateDto.getSecurityGroup())){
                withCreate.withExistingNetworkSecurityGroup(azureResourceManager.networkSecurityGroups().getByResourceGroup(azureCreateDto.getResourceGroup(),azureCreateDto.getSecurityGroup()));
            }
            networkInterface = withCreate.create();
        }catch (ManagementException e) {
            log.error("create networkInterface exception by instanceName:{} region:{}",azureCreateDto.getInstanceName(),azureCreateDto.getRegion(),e);
            //释放创建的ip资源
            ThreadPoolUtil.ipPool(cpuCores).execute(() -> deletePublicIpAddress(azureCreateDto.getResourceGroup(),resourceId));
            throw new CustomException(e.getResponse().getStatusCode(), VmCreateMsg.CREATE_NETWORKINTERFACE_EXCEPTION.msg(),e);
        }
        Assert.notNull(networkInterface,"create networkInterface exception");
        // vm name
        String vmName = VMNAME+"-"+resourceId;
        // Create the virtual machine
        VirtualMachine.DefinitionStages.WithLinuxCreateManaged withLinuxCreateManaged = azureResourceManager.virtualMachines()
                .define(vmName)
                .withRegion(azureCreateDto.getRegion())
                .withExistingResourceGroup(azureCreateDto.getResourceGroup())
                .withExistingPrimaryNetworkInterface(networkInterface)
                .withSpecializedLinuxCustomImage(azureCreateDto.getImageId());
        withLinuxCreateManaged.withSize(azureCreateDto.getVMSize());
        //增加tag name
        withLinuxCreateManaged.withTag(TAG_NAME,azureCreateDto.getInstanceName());
        //设置tag env
        withLinuxCreateManaged.withTag(TAG_ENV,azureCreateDto.getEnv());
        //设置tag createTime
        withLinuxCreateManaged.withTag(TAG_TIME,String.valueOf(System.currentTimeMillis()));
        String shell = "#!/bin/bash\n" +
                "echo 'Test file from custom data' > /home/operate_sh/testfile.txt";
        String customDataBase64 = Base64.getEncoder().encodeToString(shell.getBytes(StandardCharsets.UTF_8));
        withLinuxCreateManaged.withCustomData(customDataBase64);
        //data disk size
//       if(azureCreateDto.getDataDisk() != 0 && azureCreateDto.getDataDisk() > 0){
//           withLinuxCreateManaged.withOSDiskSizeInGB(azureCreateDto.getDataDisk());
//       }
       log.error("customData:{}",customDataBase64);
       VirtualMachine virtualMachine = null;
       try {
            virtualMachine = withLinuxCreateManaged.create();
       }catch (ManagementException e) {
           log.error("create virtualMachine exception by instanceName:{} region:{}",azureCreateDto.getInstanceName(),azureCreateDto.getRegion(),e);
           ThreadPoolUtil.networkPool(cpuCores).execute(() -> {
               deleteNetworkInterface(azureCreateDto.getResourceGroup(),resourceId);
               deletePublicIpAddress(azureCreateDto.getResourceGroup(),resourceId);
           });
           throw new CustomException(e.getResponse().getStatusCode(), VmCreateMsg.CREATE_VM_EXCEPTION.msg(),e);
       }
       String status = VmStatus.getStatus(virtualMachine.powerState().toString());

This sentence in the above code sets:         withLinuxCreateManaged.withCustomData(customDataBase64);  why is it not executed when starting up

**Comment by weidongxu-microsoft** [comment]
There is test case for custom data
https://github.com/Azure/azure-sdk-for-java/blob/main/sdk/resourcemanager/azure-resourcemanager/src/test/java/com/azure/resourcemanager/TestVirtualMachineCustomData.java

This test is pass.

The difference to customer code is that 
1. it uses ubuntu 16, while customer uses their own image
2. it uses a [cloud config data](https://cloudinit.readthedocs.io/en/latest/explanation/format.html#cloud-config-data), while customer uses a user data script

Can customer check whether the script is copied to either `/var/lib/waagent` or `/var/lib/waagent/CustomData` folder?
https://learn.microsoft.com/azure/virtual-machines/custom-data

**Comment by weidongxu-microsoft** [comment]
@v-hongli1 Please follow up.

**Comment by liukaiAs** [comment]
the folder of scropts not in /var/lib/waagent or /var/lib/waagent/CustomData

**Comment by liukaiAs** [comment]
the problem has been resolved. tks
