### ISSUE TITLE
[BUG] Using stream=true, although the returned data is split, it still waits for the server to complete the processing before returning

### ISSUE THREAD

**Issue by wzglgo** [Azure/azure-sdk-for-java#35464]
I tried to use curl and javasdk to have this effect.
If the interface of openAI is called directly, it is asynchronous

azure
`
curl --location --request POST 'https://aicharacter.openai.azure.com/openai/deployments/xxxxx/chat/completions?api-version=2023-03-15-preview' \
--header 'Content-Type: application/json' \
--header 'api-key: xxxxx' \
--data-raw '{    "model": "gpt-3.5-turbo",
  "messages": [{"role":"user","content":"hello"}],
  "stream":true
}'
`

openAI
`
curl --location --request POST 'https://api.openai.com/v1/chat/completions' \
--header 'Content-Type: application/json' \
--header 'Authorization: Bearer sk-xxxxxxx' \
--data-raw '{
    "model": "gpt-3.5-turbo",
    "messages": [
				  {"role": "user", "content": "hello"}
				],
    "stream": true
  }'
`

**Comment by joshfree** [comment]
Hi @wzglgo thank you for your feedback.  @mssfang could you please follow up?

**Comment by mssfang** [comment]
@wzglgo Thanks for the reach out. 

Are you using async client's [getChatCompletionsStream](https://github.com/Azure/azure-sdk-for-java/blob/main/sdk/openai/azure-ai-openai/src/main/java/com/azure/ai/openai/OpenAIAsyncClient.java#L409)?

If not, please check out below samples
[Azure ChatCompletions](https://github.com/Azure/azure-sdk-for-java/blob/main/sdk/openai/azure-ai-openai/src/samples/java/com/azure/ai/openai/usage/GetChatCompletionsAsyncSample.java)

**Comment by wzglgo** [comment]
Hello, through testing, I finally found that the stream mode of azure does not respond one by one token, but many tokens respond once, which is different from openai, and according to the effect, it is also better for openai, You can run the two curls I sent earlier to compare and you can see the difference intuitively. Thank you @mssfang

**Comment by wzglgo** [comment]
This is not a sdk problem, but azure problem, but I don't know what channel to submit to azure

**Comment by mssfang** [comment]
Unfortunately, I don't have direct contact. @trrwilson Do you know?

**Comment by brunoborges** [comment]
@wzglgo is this still an issue?
