### ISSUE TITLE
[BUG] Can not stream Files that are larger than 250 MB to the Azure Blob storage

### ISSUE THREAD

**Issue by git9999999** [Azure/azure-sdk-for-java#35477]
**Describe the bug**
I have a Rest API that streams file to a client. That client streams the files directly to the Azure Blobstorage. I can not stream Files that are larger than 250MB large. If i try too, the client stuck for ever.
With the same code i can write to the filesystem any size of  files. I attached an example Project with a README.md to reproduce it.

Please note that i had contact with Azurite to check if the problem is there: https://github.com/Azure/Azurite/issues/1998

***Exception or Stack Trace***
No stracktrace Avalible.

**To Reproduce**
see attached file + README.md in the Project
[azure-blobstoreage-large-file-problem.zip](https://github.com/Azure/azure-sdk-for-java/files/11752908/azure-blobstoreage-large-file-problem.zip)

***Code Snippet***
see attached file + README.md in the Project

**Expected behavior**
I can transfer larger files than 250MB

**Screenshots**
- 

**Setup (please complete the following information):**
 - OS: Windows 11
 - IDE: IntelliJ
 - Library/Libraries: maven: azure-blob-storage 12.22.0
 - Java version: 17
 - App Server/Environment: Tomcat
 - Frameworks: Spring Boot 3.0.6

**Information Checklist**
Kindly make sure that you have added all the following information above and checkoff the required fields otherwise we will treat the issuer as an incomplete report
- [x ] Bug Description Added
- [x ] Repro Steps Added
- [x ] Setup information Added

**Comment by alzimmermsft** [comment]
Thank you for filing this @git9999999

Briefly reviewing the application you included there is a lot going on. Have you tried, or been able, to reproduce this error with using the `azure-storage-blob` SDK directly without Spring? This would help scope the issue to being either within the `azure-storage-blob` SDK or within the configuration being used by Spring.

cc @ibrahimrabab

**Comment by git9999999** [comment]
@alzimmermsft 

I need Spring, i must stream the rest call directly to the Blobstorage. That is the hole point i try to achieve.

No worry, it looks maybe complicated, but it is quite simple. If you wish too, i can show you the code in a Teams session :-)

The Problem is right here in the code. I suspect the Outputstream to be the problem `blobClientTarget.getBlockBlobClient().getBlobOutputStream(this.parallelTransferOptions, null, null, null, null)`

```
  @GetMapping(path = "/trigger-download-to-blob/{fileSizeInMb}")
    public void triggerDownloadToBlob(@PathVariable int fileSizeInMb) {
        log.info("triggerDownload");

        var flux = this.webClient
            .get()
            .uri("/serve-file/" + fileSizeInMb)
            .accept(MediaType.APPLICATION_OCTET_STREAM)
            .exchangeToFlux(clientResponse -> clientResponse.body(BodyExtractors.toDataBuffers()));

        var destination = "TestDownloadToAzureBlobStorage" + System.currentTimeMillis() + ".pdf";

        var blobClientTarget = this.containerClient.getBlobClient(destination);

        try (var outputStream = blobClientTarget.getBlockBlobClient().getBlobOutputStream(this.parallelTransferOptions, null, null, null, null)) {
            DataBufferUtils.write(flux, outputStream)
                .map(DataBufferUtils::release)
                .blockLast(Duration.ofHours(22));
            outputStream.flush();
        } catch (IOException e) {
            throw new IllegalStateException(e);
        }

        log.info("!!!!!!!!!!!!!!!!!!!!!!!!!!!!   end download of {}", destination);
    }
```

I am working for a big Company. We have Business Support agreements, maybe help.

**Comment by git9999999** [comment]
Please note that i checked in the code to GitHub https://github.com/git9999999/azure-blob-large-file-upload-problem
so it should be easier to look at it.

**Comment by alzimmermsft** [comment]
Hi @git9999999, I was able to use the repository you've provided and can see the deadlock happening.

I've yet to determine the root cause but I wanted to ask why `BlobClient`, `ContainerClient`, etc are being used instead of the asynchronous clients, `BlobAsyncClient, `ContainerAsyncClient`, etc, given that Spring is returning a reactive payload.

I've submitted this PR which switches download blob to using the asynchronous clients and I don't see a deadlock anymore:

https://github.com/git9999999/azure-blob-large-file-upload-problem/pull/1

**Comment by git9999999** [comment]
@alzimmermsft 
THANKS A LOT!!! This solved my problem :-). 

I my Code I added your Code as new endpoint. So it is easier to spot and document for the next person that has the same problem. 

It would be nice, if there is a way to show the other users that they use the API the wrong way. But i guess this is not possible.

Thanks again, you can close this case.
