### ISSUE TITLE
workload identity credentials misconfigured

### ISSUE THREAD

**Issue by dvoet** [Azure/azure-sdk-for-java#35473]
https://github.com/Azure/azure-sdk-for-java/blob/c6912486806313c9f43c92eca70233fbf81459a1/sdk/identity/azure-identity/src/main/java/com/azure/identity/WorkloadIdentityCredential.java#L89

I think the above line is supposed to use `clientIdInput` instead of `clientId`. As is, I don't think it uses values from the environment leading to misconfiguration.

**Comment by dvoet** [comment]
this did not actually turn out to be a problem in my setup, however it is still looks wrong

**Comment by g2vinay** [comment]
This issue is fixed and released in azure-identity:1.10.0.
