### ISSUE TITLE
[FEATURE REQ] OpenAI API ChatCompletion Function implementation

### ISSUE THREAD

**Issue by bonelli** [Azure/azure-sdk-for-java#35481]
**Is your feature request related to a problem? Please describe.**
No, it is about a new API feature "Function calling" which IMO should be implemented in the Java client as well.

**Describe the solution you'd like**
I want to be able to use the OpenAI API feature for generative chat models called "Function calling".
Read details here: https://openai.com/blog/function-calling-and-other-api-updates

**Describe alternatives you've considered**
An alternative is to use generic REST clients, which is not a serious option.

**Additional context**
None

**Information Checklist**
- [ X] Description Added
- [X ] Expected solution specified

**Comment by mssfang** [comment]
@bonelli Thank you for the reach out.

I will bring this to the internal discussion. Will keep it updated here.

**Comment by fooevr** [comment]
OpenAI functions has been released for a month, Azure also supports version 0613. As an official java SDK, shouldn't it be supported as soon as possible?

**Comment by bonelli** [comment]
Finally I had to use Python instead of Java because of the lack of this feature

**Comment by mssfang** [comment]
@fooevr @bonelli Sorry for the wait. We will release a newer version which includes this feature next week as planned.

**Comment by mssfang** [comment]
https://repo1.maven.org/maven2/com/azure/azure-ai-openai/1.0.0-beta.3/
Good news!
We just released the 1.0.0-beta.3 version.
Please let us know if issues are found.
