### ISSUE TITLE
[BUG] DataLakeFileAsyncClient is randomly uploading empty files and executing the onSuccess callback

### ISSUE THREAD

**Issue by bennydean** [Azure/azure-sdk-for-java#35480]
**Describe the bug**
We have a java process which uploads thousands of JSON events into ADLS using the DataLakeFileAsyncClient. We have a rare scenario where the DataLakeFileAsyncClient is uploading an empty file and not throwing any error.

***Code Snippet***

DataLakeFileAsyncClient fileClient = dlDirectoryClient.getFileAsyncClient(qualifiedFileName);

fileClient.uploadFromFile(file, true)
		.doOnSuccess((response) -> {
			LOGGER.warn("Successfully uploaded file: {}", file);
		})
		.doOnError((exception) -> {
			LOGGER.error("FAILURE DURING ASYNC FILE UPLOAD: {}, {}",
					file,
					ExceptionUtils.getStackTrace(exception));
		}).block();

**Expected behavior**
I would expect the client to either upload a file with data or throw an error.

**Setup (please complete the following information):**
 - OS: Docker Linux image running in K8s
 - Library/Libraries: 
 	<dependency>
			<groupId>com.azure</groupId>
			<artifactId>azure-storage-file-datalake</artifactId>
			<version>12.7.1</version>
		</dependency>

 - Java version: 11
 - App Server/Environment: Tomcat
 - Frameworks: Spring boot

**Additional context**
The issue is impossible to recreate on command. Its a rare issue that is very difficult to troubleshoot since the SDK is not throwing errors. I have added logging to ensure that the file has events in when the upload occurs. I understand that this bug will be hard to help with given the lack of reproduction steps. Any tips or advice for how to better identify the issue will be helpful. If you need additional information please let me know.

On a side note, if you're wondering why I'm using an async client and blocking, its due to the fact that we call this from an async context in a different part of the code but don't want to actually execute in an async manner. The async context in which its called is not the same part of the application where we are experiencing the empty file issue.

**Comment by ibrahimrabab** [comment]
Hi @bennydean 
Thanks for reaching out! This line checks for whether the file size is 0, and throws IllegalArgumentException if that is the case,
https://github.com/Azure/azure-sdk-for-java/blob/main/sdk/storage/azure-storage-file-datalake/src/main/java/com/azure/storage/file/datalake/DataLakeFileAsyncClient.java#L871

I also tried reproducing the code snippet you pasted above and the error gets thrown as expected in the `doOnError` section. Can you paste a stack trace of the code, and log the size of files that are getting uploaded to confirm whether empty files are getting uploaded?

Another thing I noticed is you are using an older version of azure-storage-file-datalake. Can you try upgrading to the recent version to see if this resolves your issue?

**Comment by bennydean** [comment]
Hello @ibrahimrabab , 

I have upgraded to the latest version of all Azure SDKs in our project. The issue is still occurring after the upgrade. 

In regards to logging the file size, I do have the capability to do this however it will be a large effort given there is a lot of process / auditing to deploy production code in our enterprise. Given your findings that the SDK throws an error when uploading an empty file, I am not sure I see much value in doing this. Please let me know your thoughts.

**Comment by ibrahimrabab** [comment]
Hi @bennydean 
Following up on this thread. Is this still an issue you are experiencing?
