### ISSUE TITLE
[OpenAI] Stream API doc improvement

### ISSUE THREAD

**Issue by mssfang** [Azure/azure-sdk-for-java#35487]
https://github.com/Azure/azure-sdk-for-java/issues/35437

Improve streaming API documentation.

"Streamed requests do not include a "usage" field in the response from OpenAI." ==> DON'T add it to JavaDoc but is fine in sample.

Latest updates: 
Note we can't mention the capabilities we don't support in the API JavaDoc but we can add the "not support" feature in the sample. It could be many capabilities we don't support, and we should not list any of them in the JavaDoc, which will not break API Doc consistency.

**Comment by kangzecan** [comment]
收到了，谢谢。
