### ISSUE TITLE
[FEATURE REQ] EventHub EventProcessorClientBuilder.initialPartitionEventPosition overload taking a function

### ISSUE THREAD

**Issue by leviramsey** [Azure/azure-sdk-for-java#35484]
**Is your feature request related to a problem? Please describe.**
I'm integrating a stream processing toolkit with Event Hubs and would like to make it easy for my users to specify that, in the absence of existing checkpoints, they would like to consume from earliest (similar conceptually to Kafka's `auto.offset.reset=earliest`).  With the `EventProcessorClient`, its builder only supports taking a map from partition IDs to starting offsets to be used as a fallback.  Since this is intended to be generic, the actual set of partition IDs isn't known ahead of time, so the only way to set that default policy is to pass a map which for any string key returns the value `EventPosition.earliest()`.  Inspection of the SDK code in this repo indicates that the client never iterates over the map (which in this case is not a good idea: an iteration which behaves like a strict collection would enumerate every possible Unicode string before terminating), so this hack should work, but would depend on this SDK never changing its behavior in that area.

**Describe the solution you'd like**
An overloaded `EventProcessorClient.initialPartitionEventPosition` which takes a `Function<String, EventPosition>`.

**Describe alternatives you've considered**
Alternatively, an explicit ability to set a default fallback position when a partition has no position in the checkpoint store or the passed map of initial positions (viz. the ability to explicitly override the default from `EventPosition.latest()` to `EventPosition.earliest()`

**Comment by yashas224** [comment]
hi @leviramsey 
I too had a similar uses case for my work.
I see this PR being raised requesting for  same feature.
https://github.com/Azure/azure-sdk-for-java/issues/11431

**Comment by joshfree** [comment]
@conniey could you please follow up?

**Comment by conniey** [comment]
Closed as a duplicate ask from #11431
