### ISSUE TITLE
The java doc for the Cosmos Client Builder is erroneous 

### ISSUE THREAD

**Issue by DavideDelVecchio** [Azure/azure-sdk-for-java#35491]
The  Cosmos Java SDK for the class sdk/cosmos/azure-cosmos/src/main/java/com/azure/cosmos/CosmosClientBuilder.java gives the following Building Cosmos Async Client with customizations **example**
 
 CosmosAsyncClient client = new CosmosClientBuilder()
         .endpoint(serviceEndpoint)
         .key(key)
         .directMode(directConnectionConfig, gatewayConnectionConfig)
         .consistencyLevel(ConsistencyLevel.SESSION)
         .connectionSharingAcrossClientsEnabled(true)
         .contentResponseOnWriteEnabled(true)
         .userAgentSuffix("my-application1-client")
         .preferredRegions(Collections.singletonList("West US", "East US"))
         .buildAsyncClient();

When passing the preferredRegions the Collections.singletonList("West US", "East US") can **only accept one element** as per 
https://docs.oracle.com/javase/8/docs/api/java/util/Collections.html#singletonList-T-  like in Collections.singletonList("West US") so two regions must be passed differently

**Comment by FabianMeiswinkel** [comment]
Will include fix here - https://github.com/Azure/azure-sdk-for-java/pull/35501
