### ISSUE TITLE
Java docs CI build fails because of dependency on unreleased azure-core-test

### ISSUE THREAD

**Issue by Menghua1** [Azure/azure-sdk-for-java#35504]
Error:

> [WARNING] The POM for com.azure:azure-core-test:jar:1.19.0-beta.1 is missing, no dependency information available
> [INFO] ------------------------------------------------------------------------
> [INFO] BUILD FAILURE
> [INFO] ------------------------------------------------------------------------
> [INFO] Total time:  0.469 s
> [INFO] Finished at: 2023-06-16T04:27:31Z
> [INFO] ------------------------------------------------------------------------
> [ERROR] Failed to execute goal on project azure-core-amqp: Could not resolve dependencies for project com.azure:azure-core-amqp:jar:2.9.0-beta.2: com.azure:azure-core-test:jar:1.19.0-beta.1 was not found in https://repo1.maven.org/maven2 during a previous attempt. This failure was cached in the local repository and resolution is not reattempted until the update interval of maven-repo has elapsed or updates are forced -> [Help 1]
> [ERROR] 
> [ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
> [ERROR] Re-run Maven using the -X switch to enable full debug logging.
> [ERROR] 
> [ERROR] For more information about the errors and possible solutions, please read the following articles:
> [ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/DependencyResolutionException
> 
> '
> STDERR:
> '
> '
>    at Microsoft.Content.Build.Java2Yaml.ProcessUtility.Execute(String fileName, String commandLineArgs, String cwd, Boolean redirectOutput) in C:\__w\1\s\src\java2yaml\Common\Utility\ProcessUtility.cs:line 49
>    at Microsoft.Content.Build.Java2Yaml.RestoreDependency.<RunAsync>b__7_0() in C:\__w\1\s\src\java2yaml\Steps\RestoreDependency.cs:line 44
>    at System.Threading.Tasks.Task.Execute()
> --- End of stack trace from previous location where exception was thrown ---
>    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
>    at Microsoft.Content.Build.Java2Yaml.StepCollection.<RunAsync>d__4.MoveNext() in C:\__w\1\s\src\java2yaml\Steps\StepCollection.cs:line 41
> --- End of stack trace from previous location where exception was thrown ---
>    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
>    at Microsoft.Content.Build.Java2Yaml.GenerateDocument.<>c__DisplayClass2_0.<<RunAsync>b__0>d.MoveNext() in C:\__w\1\s\src\java2yaml\Steps\GenerateDocument.cs:line 13
> --- End of stack trace from previous location where exception was thrown ---
>    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
>    at Microsoft.Content.Build.Java2Yaml.StepCollection.<RunAsync>d__4.MoveNext() in C:\__w\1\s\src\java2yaml\Steps\StepCollection.cs:line 28
> Failed in 3835192 milliseconds.
> 
> 
> ##[error]PowerShell exited with code '1'.

For more details check here:

- https://apidrop.visualstudio.com/Content%20CI/_build/results?buildId=368421&view=results

@danieljurek for notification.

**Comment by danieljurek** [comment]
I've opened an incident to track resolution. I don't think a dependency scoped to test is necessary for docs build... we'll see if that's the case -- https://portal.microsofticm.com/imp/v3/incidents/details/398213235/home

**Comment by danieljurek** [comment]
@JonathanGiles -- Do we need to publish `com.azure:azure-core-test:jar:1.19.0-beta.1` or is it published periodically by some quirk of our release system/process? 

cc @hallipr

**Comment by JimSuplizio** [comment]
This is no longer an issue. azure-core-test is now released as part of the nightly and official releases.
