### ISSUE TITLE
[BUG] Azure sdk takes too long to report back disk status after attaching

### ISSUE THREAD

**Issue by saupallucidity** [Azure/azure-sdk-for-java#35517]
**Describe the bug**
We are using azure sdk version "com.azure.resourcemanager:azure-resourcemanager:2.20.0" and it takes very long(upwards of 13 minutes) for the disk to be attached to a vm and the correct status to be returned on sdk. Although the disk is attached to vm when checked via the azure portal. This happens intermittently

***Exception or Stack Trace***
                vmInfo.update().withExistingDataDisk(disk).apply();
  
**To Reproduce**
Create a new disk and attach it to an existing vm through sdk. The call above takes too long to be returned. The event on the vm is created within expected limits(a couple of seconds) but the same event doesn't reflect on the disk until after 10+ minutes.

**Expected behavior**

**Screenshots**
![image](https://github.com/Azure/azure-sdk-for-java/assets/135114634/ea4a8cee-d7c0-4c8f-a068-ddda9054a7fd)

![image](https://github.com/Azure/azure-sdk-for-java/assets/135114634/54c8a60d-0d42-4ebd-ab68-6a99635ad835)

**Comment by weidongxu-microsoft** [comment]
@XiaofeiCao Could you take a look? It might be an LRO, but 10+ minutes seems too long.

**Comment by saupallucidity** [comment]
Any updates here?

**Comment by weidongxu-microsoft** [comment]
It is about 34 seconds in my test. It is not super fast, but definitely in minutes.

Would you let us know what's specifical in your case? Code snippet if possible.

```java
            // prepare resources
            var vm1 = azure
                    .virtualMachines()
                    .define(vmName)
                    .withRegion(region)
                    .withNewResourceGroup(rgName)
                    .withNewPrimaryNetwork("10.0.0.0/28")
                    .withPrimaryPrivateIPAddressDynamic()
                    .withoutPrimaryPublicIPAddress()
                    .withPopularLinuxImage(KnownLinuxVirtualMachineImage.UBUNTU_SERVER_18_04_LTS)
                    .withRootUsername("weidxu")
                    .withSsh(sshKey)
                    .withSize(VirtualMachineSizeTypes.STANDARD_B1S)
                    .create();

            var disk1 = azure.disks().define("datadisk1")
                    .withRegion(region)
                    .withExistingResourceGroup(rgName)
                    .withData()
                    .withSizeInGB(10)
                    .create();

            // do the update
            vm1 = azure.virtualMachines().getById(vm1.id());

            long nanoStart = System.nanoTime();

            vm1.update().withExistingDataDisk(disk1).apply();

            long nanoStop = System.nanoTime();

            System.out.println((double) (nanoStop - nanoStart) / 1E9);
```

output
```
34.8285229
```
