### ISSUE TITLE
[FEATURE REQ] mgmt, redact api-version query parameter upon migrate to test proxy

### ISSUE THREAD

**Issue by weidongxu-microsoft** [Azure/azure-sdk-for-java#35527]
**Is your feature request related to a problem? Please describe.**
Redact api-version query parameter, when migrate to test proxy.

Heard from Arthur that .NET already done this for e.g. resources, network, etc.

It would avoid the need of re-record upon an upgrade on dependency. (re-record compute, when network upgrade)

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Information Checklist**
Kindly make sure that you have added all the following information above and checkoff the required fields otherwise we will treat the issuer as an incomplete report
- [x] Description Added
- [ ] Expected solution specified

**Comment by haolingdong-msft** [comment]
Fixed in this pr : https://github.com/Azure/azure-sdk-for-java/pull/35476
