### ISSUE TITLE
[QUERY] Stable Version for azure-storage-blob-changefeed ?

### ISSUE THREAD

**Issue by dvag-joerg-winter** [Azure/azure-sdk-for-java#35538]
**Query/Question**
1) when do you expect this Library to reach a stable (i.e. non-beta) version ?
2) are there plans to retire this service (or the Java library) ?

***Why is this not a Bug or a feature Request?***
The last beta-version was released over 1 year ago.

**Setup (please complete the following information if applicable):**
        <dependency>
            <groupId>com.azure</groupId>
            <artifactId>azure-storage-blob-changefeed</artifactId>
            <version>12.0.0-beta.18</version>
        </dependency>
 
 **Information Checklist**
 Kindly make sure that you have added all the following information above and checkoff the required fields otherwise we will treat the issuer as an incomplete report
- [x] Query Added
- [x] Setup information Added

**Comment by ibrahimrabab** [comment]
Hi @dvag-joerg-winter 
Thanks for reaching out. We currently have no tentative plans for Changefeed to be released as a stable version, nor do we have any plans for retiring this service. We will continue to support with bug fixes and new Changefeed schemas.
