### ISSUE TITLE
[BUG] createTableIfNotExists logs message with info level error when table exists

### ISSUE THREAD

**Issue by knubonrk** [Azure/azure-sdk-for-java#35541]
**Describe the bug**
createTableIfNotExists logs an message with level ERROR when a table exist. The code works fine, but makes tracking the log from this library problematic.

***Exception or Stack Trace***

**To Reproduce**
Use method createTableIfNotExists on an existing table store entry and see that it logs.

***Code Snippet***
tableServiceClient.createTableIfNotExists("foo")

**Expected behavior**
It should create the table and ignore any duplicate table warnings - that is, not log anything, at least not in ERROR level. debug would be preferable.

**Screenshots**
No

**Setup (please complete the following information):**
 - OS: Linux (Not relevant)
 - IDE: Intellij
 - Library/Libraries: com.azure:azure-data-tables:12.3.8+ has this problem. com.azure:azure-data-tables:12.3.7 is fine.
 - Java version: 17
 - App Server/Environment: N/A
 - Frameworks: N/A

If you suspect a dependency version mismatch (e.g. you see `NoClassDefFoundError`, `NoSuchMethodError` or similar), please check out [Troubleshoot dependency version conflict article](https://aka.ms/azsdk/java/dependency/troubleshoot) first. If it doesn't provide solution for the problem, please provide:
- verbose dependency tree (`mvn dependency:tree -Dverbose`)
- exception message, full stack trace, and any available logs

**Additional context**

**Information Checklist**
Kindly make sure that you have added all the following information above and checkoff the required fields otherwise we will treat the issuer as an incomplete report
- [ x ] Bug Description Added
- [ x ] Repro Steps Added
- [ x ] Setup information Added

**Comment by joshfree** [comment]
Thanks for the feedback @knubonrk.  @jairmyree could you please follow up?

**Comment by jairmyree** [comment]
@knubonrk Thank you for reaching out, I will follow up on this shortly.

**Comment by jairmyree** [comment]
@knubonrk Thank you for your report. Our team will look into adjusting the logging in the future. You can track issue [here](https://github.com/Azure/azure-sdk-for-java/issues/36673). Because this is not a bug, I am going to close out this report. If you have any additional concerns, please see our [SUPPORT.md](https://github.com/Azure/azure-sdk-for-java/blob/main/SUPPORT.md) for more information. Thank you very much.
