### ISSUE TITLE
[BUG] Unable to update the keyvault version

### ISSUE THREAD

**Issue by TLeeflang** [Azure/azure-sdk-for-java#35568]
**Describe the bug**
Unable to read keyvault values after upgrading the keyvault version

failing: spring-cloud-azure-starter-keyvault-secrets
Version 4.7.0
 
working: azure-spring-boot-starter-keyvault-secrets
Version 3.14.0

**To Reproduce**
Using Spring boot 2.7.9
And keyvault version 4.7.0

***Code Snippet***
Attached is the (updated) parent pom used in the service
[parent_pom.txt](https://github.com/Azure/azure-sdk-for-java/files/11881869/parent_pom.txt)

**Comment by Netyyyy** [comment]
Hi @TLeeflang , we redesigned module names since 4.0, could you replace `azure-spring-boot-starter-keyvault-secrets` with `spring-cloud-azure-starter-keyvault-secrets`, thanks.

**Comment by TLeeflang** [comment]
Hello @Netyyyy i adjusted the pom per your suggestion but the issue seems to persist.

**Comment by Netyyyy** [comment]
Hi @TLeeflang , refer to https://github.com/Azure/azure-sdk-for-java/wiki/Spring-Versions-Mapping
if you are using Spring Boot 2.x, I suggest you change pom like below, and the `spring-cloud-azure-dependencies` manages all the Spring Cloud Azure libraries, doesn't need to configure `azure.jms.version` or `keyvault.version`.
![image](https://github.com/Azure/azure-sdk-for-java/assets/92105726/aa305a7f-4e0f-4365-9db6-351d13fda100)
