### ISSUE TITLE
[BUG] BlobContainerClient.listBlobsByHierarchy() : BlobItem.getMetadata() returns null for folders, even if they are real blobs

### ISSUE THREAD

**Issue by wheezil** [Azure/azure-sdk-for-java#35580]
**Describe the bug**

While Azure Blob Storage doesn't have "real" folders, there are two conventions for emulating folders:

- Implied by the presence of blobs which have an intermediate path
- Zero-length blobs whose name ends with "/"

When calling BlobContainerClient.listBlobsByHierarchy(), it is expected that first type doesn't have metadata.  But the second type can and should.  However, neither has metadata.

***Exception or Stack Trace***

**To Reproduce**

Save the attached archive to disk
Fill in the abs_* values to access blob storage of your choosing.
Compile and run the main().

***Code Snippet***

See attached archive.  Build with maven.

***Workaround***

Detect that the blob is a "directory" and make additional queries.  This workaround is acceptable but decreases performance:

```
BlobClient blobClient = fileStore.getContainerClient().getBlobClient(UriUtils.escape(item.getName()));
if (blobClient.exists()) {
  // Get the modified time of folders that are real blobs ending with "/", even though it is not returned by the listing
  BlobProperties props = fileStore.getContainerClient().getBlobClient(UriUtils.escape(item.getName())).getProperties();
  long millis = props.getLastModified().toEpochSecond() * 1000L;
} else {
  // It is a pure prefix, no blob exists
}
```

**Expected behavior**

Expected: blob listing for "folder1/" has metadata and listing for "folder2/" does not, because "folder1/" is a real blob.
Actual: Neither folder has metadata.

**Screenshots**

**Setup (please complete the following information):**
 - OS: Windows
 - IDE: IntelliJ
 - Library/Libraries: Azure BOM 1.2.13
 - Java version: OpenJDK 17
 - App Server/Environment: 
 - Frameworks: 

**Additional context**

**Information Checklist**
- [X] Bug Description Added
- [X] Repro Steps Added
- [X] Setup information Added

**Comment by wheezil** [comment]
[scratch3.zip](https://github.com/Azure/azure-sdk-for-java/files/11834736/scratch3.zip)

**Comment by wheezil** [comment]
This relates to https://github.com/Azure/azure-sdk-for-java/issues/20895 but is a more specific case.

**Comment by wheezil** [comment]
I could have sworn this worked as I expected with BOM 1.2.4, but I cannot make that work now with older BOM
 ¯\_(ツ)_/¯

**Comment by alzimmermsft** [comment]
Thanks for filing this @wheezil

Running the sample you gave, inspecting the wire contents the first request without a prefix will return `folder1/` and `folder2/` as `<BlobPrefix>` values and not `<Blob>` values where `<BlobPrefix>` values don't contain any properties and only contain the blob name (`<BlobPrefix><Name>folder1/</Name></BlobPrefix>`). The subsequent listings using the prefixes returned, though in your case they were hardcoded, prefixes that are actual blobs are retuned as `<Blob>...</Blob>` with the actual metadata.

Listing request without prefix:

```xml
<?xml version="1.0" encoding="utf-8"?>
<EnumerationResults ServiceEndpoint="***"
  ContainerName="issue35580">
  <Delimiter>/</Delimiter>
  <Blobs>
    <BlobPrefix>
      <Name>folder1/</Name>
    </BlobPrefix>
    <BlobPrefix>
      <Name>folder2/</Name>
    </BlobPrefix>
  </Blobs>
  <NextMarker />
</EnumerationResults>
```

Listing request for `folder1/` prefix:

```xml
<?xml version="1.0" encoding="utf-8"?>
<EnumerationResults ServiceEndpoint="***"
  ContainerName="issue35580">
  <Prefix>folder1/</Prefix>
  <Delimiter>/</Delimiter>
  <Blobs>
    <Blob>
      <Name>folder1/</Name>
      <Properties>
        ....
      </Properties>
      <Metadata />
      <OrMetadata />
    </Blob>
    <Blob>
      <Name>folder1/subfile1</Name>
      <Properties>
        ...
      </Properties>
      <Metadata />
      <OrMetadata />
    </Blob>
    <BlobPrefix>
      <Name>folder1/subfolder1/</Name>
    </BlobPrefix>
  </Blobs>
  <NextMarker />
</EnumerationResults>
```

**Comment by ibrahimrabab** [comment]
Hi @wheezil 
Is this still an issue you are experiencing?

**Comment by wheezil** [comment]
The problem is unresolved as of Azure SDK BOM 1.2.13
In my Test1.java in scratch.zip, change line 55 to fetch the last-modified 
	System.out.println(item.getName() + ":  " + item.getProperties().getLastModified());
This will throw NPE for blob "folder1/" even though folder1/ is a real blob that I uploaded.

**Comment by ibrahimrabab** [comment]
@wheezil 
Do you want to query all blobs using `listBlobsByHierarchy()` without using a prefix? Because without specifying the prefix, the blobs will be returned as prefix blobs which is by design. By specifying a prefix, you will be able to access the properties and the metadata of the blobs. 
Can see here:
https://learn.microsoft.com/en-us/azure/storage/blobs/storage-blobs-list-java

Also, another reason why metadata appears as null when querying is because metadata has not been set.

If you want to list all blobs, you can try using `listBlobs()`. This will flat list all the blobs and you'll be able to access the BlobItemProperties for each BlobItem.

**Comment by wheezil** [comment]
Hi @ibrahimrabab , sorry I thought I had attached more.  This is the modified program:
```
public static void main(String[] args) throws Exception {
  BlobServiceClientBuilder builder = new BlobServiceClientBuilder();
  builder.connectionString(abs_connection_string);
  var client = builder.buildClient();
  var containerClient = client.getBlobContainerClient(abs_container);

  // Make a pseudo-folder that is a real blob ending with "/"
  String folderName1 = "folder1";
  var folderClient = containerClient.getBlobClient(folderName1 + "/");
  BinaryData data = BinaryData.fromBytes(new byte[0]);
  containerClient.getBlobClient(folderName1 + "/").upload(data, true);
  // Make "sub-folder"
  String subFolderName1 = "subfolder1";
  containerClient.getBlobClient(folderName1 + "/" + subFolderName1 + "/").upload(data, true);
  // Make "sub-file"
  String subFileName1 = "subfile1";
  containerClient.getBlobClient(folderName1 + "/" + subFileName1).upload(data, true);

  // Imply a folder that is a prefix without a blob
  String folderName2 = "folder2";
  // Make "sub-folder"
  String subFolderName2 = "subfolder2";
  containerClient.getBlobClient(folderName2 + "/" + subFolderName2 + "/").upload(data, true);
  // Make "sub-file"
  String subFileName2 = "subfile2";
  containerClient.getBlobClient(folderName2 + "/" + subFileName2).upload(data, true);

  // List the container
  for (String prefix : new String[] {"", folderName1 + "/", folderName2 + "/"}) {
    System.out.println("PREFIX: " + prefix);
    ListBlobsOptions options = new ListBlobsOptions().setPrefix(prefix).setDetails(new BlobListDetails().setRetrieveMetadata(true));
    var iter = containerClient.listBlobsByHierarchy("/", options, Duration.ofSeconds(1000)).iterator();
    while (iter.hasNext()) {
      var item = iter.next();
      var name = item.getName();
      if (name.contains(folderName1) || name.contains(folderName2)) {
        // These are the top-level folders we created
        if (item.isPrefix()) {
          System.out.println(item.getName() + ":  prefix");
        } else {
          System.out.println(item.getName() + ":  " + item.getProperties().getLastModified());
        }
      }
    }
  }
}
```
when run, it produces this output:
```
PREFIX: 
folder1/:  prefix
folder2/:  prefix
PREFIX: folder1/
folder1/:  2023-10-31T00:12:40Z
folder1/subfile1:  2023-10-31T00:12:40Z
folder1/subfolder1:  2023-10-28T18:02:44Z
folder1/subfolder1/:  prefix
PREFIX: folder2/
folder2/subfile2:  2023-10-31T00:12:40Z
folder2/subfolder2/:  prefix
```
You can see that, even when I specify `folder2/` as the prefix, it still returns `folder2/subfolder2/` as a prefix and not a blob.  But there really IS a blob named `folder2/subfolder2/` so why don't I get its metadata?  The idea is that, if I make a folder, I would like to report its creation time, and I would also like to know if it is a real blob or an imputed prefix.  Because if it is a real blob there are things I need to do with it.  For example, to perform a recursive delete, I need to delete the "folder" blob.  But if it is not a real blob I can ignore it.

**Comment by ibrahimrabab** [comment]
@wheezil 
Unfortunately what you're seeing here with folder2/subfolder2/ being labeled as a prefix is by design. Since there is a trailing "/" at the end of the subfolder2 name, the service recognizes this as another hierarchy, treating it as a prefix. More information can be found here:
https://learn.microsoft.com/en-us/rest/api/storageservices/list-blobs?tabs=azure-ad#using-a-delimiter-to-traverse-the-blob-namespace

Apologies for not being able to be of more help on this issue, there isn't much we can do on the client SDK side since this behavior from the service is a bit ambiguous. Let us know if you have any additional questions and we'd be happy to help.
