### ISSUE TITLE
Two copies of MemberNameConverterImpl.java

### ISSUE THREAD

**Issue by dsgrieve** [Azure/azure-sdk-for-java#35585]
**Describe the bug**
```
% find azure-sdk-for-java/sdk/core -type f -name MemberNameConverterImpl.java
azure-sdk-for-java/sdk/core/azure-core/src/main/java/com/azure/core/implementation/jackson/MemberNameConverterImpl.java
azure-sdk-for-java/sdk/core/azure-core-serializer-json-jackson/src/main/java/com/azure/core/serializer/json/jackson/implementation/MemberNameConverterImpl.java
```
```
% diff `find azure-sdk-for-java/sdk/core -type f -name MemberNameConverterImpl.java`
4c4
< package com.azure.core.implementation.jackson;
---
> package com.azure.core.serializer.json.jackson.implementation;
54,56c54,55
<                     LOGGER.atInfo()
<                         .addKeyValue("field", f.getName())
<                         .log("Field is annotated with JsonProperty but isn't accessible to JacksonJsonSerializer.");
---
>                     LOGGER.info("Field {} is annotated with JsonProperty but isn't accessible to "
>                         + "JacksonJsonSerializer.", f.getName());
80,82c79,80
<                     LOGGER.atInfo()
<                         .addKeyValue("method", m.getName())
<                         .log("Method is annotated with either JsonGetter or JsonProperty but isn't accessible  to JacksonJsonSerializer.");
---
>                     LOGGER.info("Method {} is annotated with either JsonGetter or JsonProperty but isn't accessible "
>                         + "to JacksonJsonSerializer.", m.getName());
126c124
<         AnnotatedMethod annotatedMethod = new AnnotatedMethod(annotatedClass, method, null, null);
---
>         AnnotatedMethod annotatedMethod = new AnnotatedMethod(null, method, null, null);
```

**Setup (please complete the following information):**

**Additional context**
 ```
git remote -v
origin	git@github.com:Azure/azure-sdk-for-java.git (fetch)
origin	git@github.com:Azure/azure-sdk-for-java.git (push)
```

Tip is: commit 0c885303930b0ecb623e8de9a6a4e754d99213de (HEAD -> main, origin/main, origin/HEAD)
Last commit to azure-core/src/main/java/com/azure/core/implementation/jackson/MemberNameConverterImpl.java
```
commit a72b4c45a49d44550a71ce4f0958914ac0461f1c
Author: Liudmila Molkova <limolkova@microsoft.com>
Date:   Wed May 3 09:31:32 2023 -0700

    Add jackson 2.15 to dependency test matrix (#34755)
    
    * add jackson 2.15 to test matrix
```
Last commit to sdk/core/azure-core-serializer-json-jackson/src/main/java/com/azure/core/serializer/json/jackson/implementation/MemberNameConverterImpl.java
```
commit 07d70c9852d572e7c0b7f1a2ad7591eb55b380fe
Author: Alan Zimmer <48699787+alzimmermsft@users.noreply.github.com>
Date:   Fri Apr 21 11:30:33 2023 -0400

    Update how XmlMapperFactory is initialized (#34468)
```

Kindly make sure that you have added all the following information above and checkoff the required fields otherwise we will treat the issuer as an incomplete report

- [X] Bug Description Added
- [ ] ~Repro Steps Added~ N/A
- [ ] ~Setup information Added~ N/A

**Comment by alzimmermsft** [comment]
Hi @dsgrieve, thanks for filing this.

Is this causing an issue or just a mention that there are two classes with the same name?

Backstory on this is that we're actively working towards removing usage of Jackson Databind, and just generally Jackson, in our libraries. Eventually this will culminate in the removal of Jackson in azure-core. What you're seeing and reporting here is that azure-core-serializer-json-jackson will continue using Jackson given what the package is, implementations of APIs and SPIs in azure-core with Jackson as the implementation. To help ease this transition azure-core-serializer-json-jackson has had all Jackson-based functionality from azure-core copied into it, with some minor differences here and there based on API mistakes in azure-core's version and based on changes in the Java ecosystem such as the deprecation of SecurityManager.

**Comment by dsgrieve** [comment]
> Is this causing an issue or just a mention that there are two classes with the same name?

I was looking into issue #35584 and the changes for #34755 were brought to my attention. It was then that I noticed there were two copies of this class. If I remember correctly, the code was going through azure-core-serializer-json-jackson, but there was a more recent fix in azure-core.

If azure-core-serializer-json-jackson is the future, then shouldn't Ludimila's changes for #34755 have been applied there?
