### ISSUE TITLE
Strange sentence

### ISSUE THREAD

**Issue by christian-jendeberg-sj** [Azure/azure-sdk-for-java#35587]
The following combination of words, might not be what the author intended.

"You endpoint will be your look as following:"

Otherwise an excellent feature!

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 6e076b19-adfe-0f53-8879-90e6f5fd7ebf
* Version Independent ID: bfb095ce-68c8-a4e6-6fe9-a9c72787ac35
* Content: [Spring Cloud for Azure starter App Configuration client library for Java](https://learn.microsoft.com/en-us/java/api/overview/azure/spring-cloud-starter-appconfiguration-config-readme?view=azure-java-stable)
* Content Source: [docs-ref-services/latest/spring-cloud-starter-appconfiguration-config-readme.md](https://github.com/Azure/azure-docs-sdk-java/blob/master/docs-ref-services/latest/spring-cloud-starter-appconfiguration-config-readme.md)
* Service: **appconfiguration**
* GitHub Login: @mssfang
* Microsoft Alias: **shafang**

**Comment by mssfang** [comment]
@mrm9084 Can you have a look at it?

**Comment by mrm9084** [comment]
Fixed wording, will be updated on the next release.
