### ISSUE TITLE
[QUERY] Unknown status from PollResult has isComplete=true

### ISSUE THREAD

**Issue by weidongxu-microsoft** [Azure/azure-sdk-for-java#35628]
**Query/Question**
https://github.com/Azure/azure-sdk-for-java/blob/main/sdk/core/azure-core/src/main/java/com/azure/core/util/polling/implementation/PollResult.java#L45

Default is `isComplete=true` for unknown status. Is it a bug?

In this setup, sync poller will stop at any unknown status.

This be the cause of https://github.com/Azure/azure-sdk-for-java/pull/35549#discussion_r1242476482 (however I don't know why async appears to work correctly)

***Why is this not a Bug or a feature Request?***
Maybe it is a bug.
A quick test: https://github.com/Azure/azure-sdk-for-java/pull/35627

**Setup (please complete the following information if applicable):**
 - IDE: [e.g. IntelliJ]
 - Library/Libraries: [e.g. com.azure:azure-core:1.16.0 (groupId:artifactId:version)] core 1.40.0
 
 **Information Checklist**
 Kindly make sure that you have added all the following information above and checkoff the required fields otherwise we will treat the issuer as an incomplete report
- [x] Query Added
- [x] Setup information Added

**Comment by weidongxu-microsoft** [comment]
@alzimmermsft

**Comment by weidongxu-microsoft** [comment]
From guideline https://github.com/microsoft/api-guidelines/blob/vNext/azure/ConsiderationsForServiceDesign.md#long-running-operations, only `Succeeded`, `Failed`, `Canceled` regarded as final status (that was the convention of both data-plane and management-plane).

PS: openai got question on a `deleted` status. But that a different story.

**Comment by alzimmermsft** [comment]
@srnagar do you know why this was the case?

@weidongxu-microsoft the linked PR was just moving that into shared implementation as there was now a Sync and Async version of the polling strategy. The logic has been there since the beginning: https://github.com/Azure/azure-sdk-for-java/pull/24597/files#diff-0868daae40ca76190209dce586f5e5543853caea8340094a88197d8498ec3cd3R191

**Comment by srnagar** [comment]
For an unknown status, we should treat it as not complete and `fromString(status, true)` should be updated to `fromString(status, false)` in `PollResult`. We should only complete polling on known terminal states.

**Comment by weidongxu-microsoft** [comment]
Thanks Alan. I see, this is actually from Jianghao's oldest code.

Changing it would be easy (just one line), though I am not sure about the impact.
I think the Strategy is used by a few DPG lib (that having LRO, like deviceupdate and some purview), maybe one TypeSpec lib (healthinsights).
I assume it won't affect handwritten lib (but I could be wrong here; some lib generated with jdt customization may use default LRO).

If we do the change, "test from source" should be able to cover the LRO playback from all of them (if dev has LRO test)?

**Comment by weidongxu-microsoft** [comment]
Attempt a fix https://github.com/Azure/azure-sdk-for-java/issues/35628

**Comment by weidongxu-microsoft** [comment]
azure-verticals-agrifood-farming was impacted by this issue (though not sure if anyone uses the lib).
