### ISSUE TITLE
Application returning 401 when trying to verify user role in Springboot

### ISSUE THREAD

**Issue by yadurai** [Azure/azure-sdk-for-java#35634]
**Query/Question**
We have 2 apps, a Frontend and a Backend. We are sending ID token from frontend to backend and in the backend we are trying to verify the incoming token in our spring boot application and give access to an API only if the token has a particular "Role".  The back end keeps sending 401. We have verified that the token has the required role(decoded using jwt.ms) but the token still fails.
response sent to Frontend: Jwt: Signed JWT rejected: Another algorithm expected, or no matching key(s) found

***Why is this not a Bug or a feature Request?***
Token verification is exiting functionality so it should be working. 

**Setup (please complete the following information if applicable):**
 - Library/Libraries used:
 ```xml
    <dependency>
      <artifactId>azure-spring-boot-starter-active-directory</artifactId>
      <groupId>com.azure.spring</groupId>
    </dependency>
    <dependency>
      <artifactId>spring-boot-starter-oauth2-client</artifactId>
      <groupId>org.springframework.boot</groupId>
    </dependency>
    <dependency>
      <artifactId>spring-boot-starter-oauth2-resource-server</artifactId>
      <groupId>org.springframework.boot</groupId>
    </dependency>
    <dependency>
        <artifactId>azure-spring-boot-bom</artifactId>
        <groupId>com.azure.spring</groupId>
        <scope>import</scope>
        <type>pom</type>
        <version>3.14.0</version>
      </dependency>
```
our config file
```java
@EnableWebSecurity
@EnableGlobalMethodSecurity(prePostEnabled = true)
@Slf4j
@Profile(value = {"default", "development", "production"})
public class WebAppSecurityConfig extends WebSecurityConfigurerAdapter {

  private static final String ALLOWED_API_ROLE = "DDSSFERole";

  @Override
  protected void configure(HttpSecurity http) throws Exception {
    http.authorizeRequests((requests) -> requests
            .antMatchers("/", "/actuator/health").permitAll()
            .antMatchers("/rest-api/ddss", "/rest-api/test/**").permitAll()
            .antMatchers("/camunda/**", "/app/admin/**", "/app/cockpit/**", "/app/tasklist/**")
            .permitAll()
            .antMatchers("/rest-api/**").hasRole(ALLOWED_API_ROLE).anyRequest().authenticated())
        .sessionManagement().sessionCreationPolicy(SessionCreationPolicy.STATELESS)
        .and()
        .oauth2ResourceServer().jwt().jwtAuthenticationConverter(
            new AADJwtBearerTokenAuthenticationConverter("roles", "ROLE_")
        )
    ;
    http.cors().and().csrf().disable();
  }
}
```
 **Information Checklist**
 Kindly make sure that you have added all the following information above and checkoff the required fields otherwise we will treat the issuer as an incomplete report
- [x] Query Added
- [x] Setup information Added

**Comment by Netyyyy** [comment]
Hi @yadurai , sorry for the late reply, please try with this doc: https://learn.microsoft.com/azure/developer/java/spring-framework/spring-security-support?tabs=SpringCloudAzure5x#use-jwt-client-authentication , hope it can help you.

**Comment by saragluna** [comment]
Which Spring Boot version you are using, we have released 4.x of the Spring Cloud Azure AAD starter, and the 3.x is no longer maintained. Check https://aka.ms/spring/versions for more details.

**Comment by rujche** [comment]
Closing this issue because there is no feedback from customer for more than 2 weeks.
