### ISSUE TITLE
[QUERY] - Dead Letter queue message publish and consume with spring boot

### ISSUE THREAD

**Issue by das-devi** [Azure/azure-sdk-for-java#35636]
Hi Team,

I am looking for info on could we publish and consume message to azure bus dead letter queue with artificat **spring-cloud-azure-starter-servicebus-jms** ?.   or with any other spring boot azure libraries ?.

**Comment by Netyyyy** [comment]
Hi @das-devi , you could  try with `spring-cloud-azure-starter-integration-servicebus` library, refer to https://learn.microsoft.com/azure/developer/java/spring-framework/spring-integration-support#service-bus-message-headers
