### ISSUE TITLE
With BOM version - 1.2.13: there's a delay (3 failed connects to login.microsoft.com) before establishing Managed Identity

### ISSUE THREAD

**Issue by ruchibobade** [Azure/azure-sdk-for-java#35637]
Facing an issue in connecting to Azure Blob Storage using Azure JAVA SDK.  We are using Managed Indentity to access from Azure VM.
With BOM version - 1.0.2:
It directly establish the MI connectivity. Able to access the storage without any delay.

With BOM version - 1.2.13:
It first tries to connect to login.microsoft.com (3 times) and then establish the MI connectivity. Able to access the storage but after delay.

**Comment by ruchibobade** [comment]
1. We are tying to connect Azure Blob storage with Azure SDK (Version - 1.2.13) with Managed identity and we identified that SDK is trying to access the URL : (login.microsoftonline.com/40.126.17.132:443, login.microsoftonline.com/40.126.17.132:443,
login.microsoftonline.com/40.126.18.33:443) to connect the Azure Blob and getting connection timeout error.

 

Do we need to Whitelist URL : login.microsoftonline.com?

 

2. If not needed to whitelist, we want to understand why it is trying to attempt this (login.microsoftonline.com) url. Is there configuration to disable this connection attempt.

**Comment by AB-SCT** [comment]
We are facing same issue : I have an additional questions, If my  organization Whitelist the URL : login.microsoftonline.com, will it increase any security risk? Who will won the risk of any malicious access through this open port to one of our important server. 

Is there anyway to avoid and disable this SDK is trying to access the URL : (login.microsoftonline.com) while our code tries to access the Azure blob storage.

**Comment by ibrahimrabab** [comment]
Hi @ruchibobade @AB-SCT 
Thanks for reaching out. This looks like an issue on the Azure-Identity team. I've routed this issue to their side and we should hopefully get more insight into this soon.

**Comment by ruchibobade** [comment]
Hi @ibrahimrabab ,

Please suggest if any updates from Azure-Identity team.

**Comment by AB-SCT** [comment]
Hi @ibrahimrabab, are there any news from the team working on this?

**Comment by ibrahimrabab** [comment]
@g2vinay @billwert can you folks take a look at this?

**Comment by joshfree** [comment]
Hi @ruchibobade sorry for the delay, @g2vinay will follow up with you shortly.

**Comment by g2vinay** [comment]
Hi @ruchibobade 

Thank you for reporting this.

Between BOM version - 1.0.2 and 1.2.13
Managed Identity flow was switched to go through Msal library. 
The instance discovery flow in Msal library could be getting triggered to check if the target authority endpoint is valid or not.
I will work to repro this on my end and get this step disabled within the Identity SDK for Managed Identity flow as it is not required there.

Once my investigation is complete, I will update here with next steps soon.

**Comment by g2vinay** [comment]
A fix to this was released in azure-identity:1.10.0
Upgrade to that version.
Closing this issue.
