### ISSUE TITLE
[FEATURE REQ] mgmt, support container size in convenience API on webapp/functionapp

### ISSUE THREAD

**Issue by weidongxu-microsoft** [Azure/azure-sdk-for-java#35672]
https://github.com/Azure/azure-sdk-for-java/blob/main/sdk/resourcemanager/azure-resourcemanager-appservice/src/main/java/com/azure/resourcemanager/appservice/fluent/models/SiteInner.java#L681-L702

**Comment by XiaofeiCao** [comment]
Does customer asked for webapp as well?

Seems containerSize only applies on function app. Setting containerSize for webapp has no effect according to my test..

**Comment by XiaofeiCao** [comment]
According to service, it's a memory limit indicator
> 1.1.1        Instance Size
The instance size property determines the amount of memory allocated to each instance of the function app, measured in mebibytes. CPU and network bandwidth are allocated proportionally. This is an app level property.
Proposed – reuse existing setting in our schema that is currently unused:
/site/{sitename}/containerSize 

The effect it has on web app is unknown... We may support `withContainerSize` for both, but for web app, we'll not have test on it.

**Comment by weidongxu-microsoft** [comment]
We can double check with Hanxiao on his usage.

**Comment by XiaofeiCao** [comment]
Checked with Hanxiao, he'll use it for function app's preview flex consumption plan. He's fine with the approach.

**Comment by XiaofeiCao** [comment]
2.29.0 released.
