### ISSUE TITLE
[QUERY]When I use Azure's Java SDK for stream data processing, I encounter garbled characters issue with Chinese text. 

### ISSUE THREAD

**Issue by kenlu456852** [Azure/azure-sdk-for-java#35694]
Here is the code:
![1](https://github.com/Azure/azure-sdk-for-java/assets/15831052/573243cd-2bb2-4f97-b5a1-4a5f07a6a701)

and get the result:
![2](https://github.com/Azure/azure-sdk-for-java/assets/15831052/e5c26278-0f26-4afd-878b-e3a022e2e383)

then I try to print response in the OpenAIServerSentEvents.class 
![3](https://github.com/Azure/azure-sdk-for-java/assets/15831052/658a6b54-1a61-4447-a299-220943dd7819)
![4](https://github.com/Azure/azure-sdk-for-java/assets/15831052/e4b77e19-6451-46c9-a4f3-a407d7f9a874)

how to resolve it?

**Comment by alzimmermsft** [comment]
Thanks for filing this @kenlu456852.

This appears to either be the same issue or related to issue #35522.

@mssfang can you confirm if this is related to the issue I mentioned.

**Comment by mssfang** [comment]
@alzimmermsft Yes. It is the same issue. We have a PR to fix it: https://github.com/Azure/azure-sdk-for-java/pull/35641

**Comment by kenlu456852** [comment]
@alzimmermsft @mssfang I got it.Thanks for the reply.

**Comment by liuyu-struggle** [comment]
@mssfang  How is the progress of this issue now，I saw that this PR [#35641 ](https://github.com/Azure/azure-sdk-for-java/pull/35641) has been closed，Do you currently have any other solutions

> @alzimmermsft Yes. It is the same issue. We have a PR to fix it: #35641

**Comment by mssfang** [comment]
@liuyu-struggle The PR is still open and we are trying to merge it into the next release. The release will happen soon in the next week or a week after it.
Currently, after the PR is merged and you can build the SDK locally and use the jar before the next release.
