### ISSUE TITLE
[BUG] Event Grid - No azure-messaging-eventgrid.properties file

### ISSUE THREAD

**Issue by saragluna** [Azure/azure-sdk-for-java#35775]
**Describe the bug**
The User-Agent header set by the Event Grid SDK doesn't show the EG SDK name and version correctly. 

https://github.com/Azure/azure-sdk-for-java/blob/2f92fd5a45f3bacf3c81c420359cec1fe51b1a29/sdk/eventgrid/azure-messaging-eventgrid/src/main/java/com/azure/messaging/eventgrid/EventGridPublisherClientBuilder.java#L74

The `azure-messaging-eventgrid.properties` is missing. 

***Exception or Stack Trace***

The HTTP header looks like:

```console
09:39:25.025 [ForkJoinPool-1-worker-1] INFO  c.a.m.e.i.E.publishEventGridEvents - {"az.sdk.message":"HTTP request","method":"POST","url":"https://sample.somelocation.eventgrid.azure.net/api/eventseventgrid.azure.net/api/events?api-version=REDACTED","tryCount":"1","Date":"REDACTED","Content-Length":"REDACTED","aeg-sas-key":"REDACTED","Content-Type":"REDACTED","x-ms-client-request-id":"REDACTED","User-Agent":"az-sp-eg/4.10.0-b.1 azsdk-java-UnknownName/UnknownVersion (17.0.7; Mac OS X; 13.4.1)","contentLength":188}

```

**To Reproduce**
N/A

***Code Snippet***
N/A

**Expected behavior**
A `azure-messaging-eventgrid.properties` provided just like the `azure-messaging-eventhubs.properties` file.

**Screenshots**
<img width="1409" alt="image" src="https://github.com/Azure/azure-sdk-for-java/assets/31124698/d1320132-05d9-485b-9cf6-2a0a8a39bc20">

**Setup (please complete the following information):**
 - OS: [MacOS]
 - IDE: [IntelliJ]
 - Library/Libraries: [com.azure:azure-messaging-eventgrid:latest]
 - Java version: [17] 
 - App Server/Environment: [N/A]
 - Frameworks: [Spring Boot] 

If you suspect a dependency version mismatch (e.g. you see `NoClassDefFoundError`, `NoSuchMethodError` or similar), please check out [Troubleshoot dependency version conflict article](https://aka.ms/azsdk/java/dependency/troubleshoot) first. If it doesn't provide solution for the problem, please provide:
- verbose dependency tree (`mvn dependency:tree -Dverbose`)
- exception message, full stack trace, and any available logs

**Additional context**

**Information Checklist**
Kindly make sure that you have added all the following information above and checkoff the required fields otherwise we will treat the issuer as an incomplete report
- [x] Bug Description Added
- [x] Repro Steps Added
- [x] Setup information Added

**Comment by joshfree** [comment]
Correcting labeling so this is seen by the right owner
