### ISSUE TITLE
Long running operation is Failed or Cancelled exception occurs when workloads live test

### ISSUE THREAD

**Issue by v-hongli1** [Azure/azure-sdk-for-java#35791]
Issue:
Getting an exception occurrs while live test for workloads service.
![image](https://github.com/Azure/azure-sdk-for-java/assets/74638143/851ee9a6-6f87-4ef7-bb3e-6ae2148c57c4)

For more details log infomation check here:
[workloads-live-test.log](https://github.com/Azure/azure-sdk-for-java/files/11998028/workloads-live-test.log)

relate to [PR#35790](https://github.com/Azure/azure-sdk-for-java/pull/35790)

**Comment by weidongxu-microsoft** [comment]
@v-hongli1 

I think the message is quite clear? Backend find the Managed Resource Group already exists. So you probably should not create it at all.

https://github.com/Azure/azure-sdk-for-java/pull/35790/files#r1259128479
