### ISSUE TITLE
[BUG] Not able to create event hub with compaction using azure-resourcemanager-eventhubs

### ISSUE THREAD

**Issue by satyayella** [Azure/azure-sdk-for-java#35836]
**Describe the bug**:

Customer is trying to use com.azure.resourcemanager.eventhubs.models.EventHubs

https://github.com/Azure/azure-sdk-for-java/tree/main/sdk/resourcemanager/azure-resourcemanager-eventhubs

trying to create a event hub with compaction enabled.

**To Reproduce**

we are not able to create a event hub with compaction enabled using the code samples

***Code Snippet***
This is code snippet to create EventHub from code 

val arm = getArm(deployment.cluster)
            if ( deployment.cluster.clusterCarrier.location == Location.EASTUS2 ) {
                arm.eventHubs()
                    .define(deployment.deploymentTopicName)
                    .withExistingNamespace(
                        deployment.cluster.resourceGroup,
                        getNamespace(deployment.cluster.bootstrapServer)
                    )
                    .withExistingStorageAccountForCapturedData(
                        arm.storageAccounts().getById(EnvironmentHelper.mapToEvhCapture[deployment.cluster.environment])!!,
                        "desp"
                    )
                    .withDataCaptureEnabled()
                    .withDataCaptureSkipEmptyArchives(true)
                    .withDataCaptureFileNameFormat(DATA_CAPTURE_FORMAT)
                    .withPartitionCount(deployment.configuration.partitions.toLong())

                    .withRetentionPeriodInDays(deployment.configuration.messageRetentionDays.toLong())
                    .create()

**Expected behavior**
Able to create a event hub with compaction enabled

**Screenshots**.

**Setup (please complete the following information):**
 - OS: [e.g. iOS] WIndows
 - IDE: [e.g. IntelliJ] InteliJ
 - Library/Libraries: 
 https://search.maven.org/artifact/com.azure.resourcemanager/azure-resourcemanager-eventhubs/2.28.0/jar
https://learn.microsoft.com/en-us/java/api/com.azure.resourcemanager.eventhubs.models.eventhubs?view=azure-java-stable
https://learn.microsoft.com/en-us/java/api/com.azure.resourcemanager.azureresourcemanager?view=azure-java-stable
 - Java version: [e.g. 8]  Java 8
 - App Server/Environment: [e.g. Tomcat, WildFly, Azure Function, Apache Spark, Databricks, IDE plugin or anything special]
 - Frameworks: [e.g. Spring Boot, Micronaut, Quarkus, etc] 

If you suspect a dependency version mismatch (e.g. you see `NoClassDefFoundError`, `NoSuchMethodError` or similar), please check out [Troubleshoot dependency version conflict article](https://aka.ms/azsdk/java/dependency/troubleshoot) first. If it doesn't provide solution for the problem, please provide:
- verbose dependency tree (`mvn dependency:tree -Dverbose`)
- exception message, full stack trace, and any available logs

**Additional context**
Customer want to use arm event hubs and he is not able to create a event hub with compaction

**Information Checklist**
Kindly make sure that you have added all the following information above and checkoff the required fields otherwise we will treat the issuer as an incomplete report
- [ ] Bug Description Added
- [ ] Repro Steps Added
- [ ] Setup information Added

**Comment by weidongxu-microsoft** [comment]
There was a service change https://github.com/Azure/azure-rest-api-specs/pull/24056/files

Before new SDK get released, please use `CleanupPolicyRetentionDescription.fromString("Compact")`.
