### ISSUE TITLE
Does azure-cosmos-spark_3-3_2-12 4.20.0 support Spark 3.3.2 in Databricks runtime 12.2?

### ISSUE THREAD

**Issue by PerFlodinVolvo** [Azure/azure-sdk-for-java#35846]
**Query/Question**
Does azure-cosmos-spark_3-3_2-12 4.20.0 support Spark 3.3.2 in Databricks runtime 12.2?

In the [README.md](https://github.com/Azure/azure-sdk-for-java/blob/main/sdk/cosmos/azure-cosmos-spark_3-3_2-12/README.md#azure-cosmos-spark_3-3_2-12) file, it is stated that only Spark 3.3.0 in Databricks runtime 11.x is supported by the latest azure-cosmos-spark_3-3_2-12 4.20.0.

But in the [Quickstart documentation](https://learn.microsoft.com/en-us/azure/cosmos-db/nosql/quickstart-spark?tabs=python), it says:
> Azure Cosmos DB Spark Connector supports Spark 3.1.x and 3.2.x and 3.3.x.
> Throughout this quick tutorial, we rely on [Azure Databricks Runtime 12.2 with Spark 3.3.2](https://learn.microsoft.com/en-us/azure/databricks/release-notes/runtime/12.2)

Which one is correct?

I have been monitoring the README file for a while, hoping to see that Databricks 12.x gets supported so we can update. Is it the correct place to look for the latest compatibility information?

***Why is this not a Bug or a feature Request?***
I found an inconsistency in the documentation and would like to get clarifying information.
 
**Setup (please complete the following information if applicable):**
 - OS: Databricks runtime 12.2
 - IDE: N/A
 - Library/Libraries: azure-cosmos-spark_3-3_2-12 4.20.0
 
 **Information Checklist**
 Kindly make sure that you have added all the following information above and checkoff the required fields otherwise we will treat the issuer as an incomplete report
- [X] Query Added
- [X] Setup information Added

**Comment by TheovanKraay** [comment]
Spark 3.3.x is correct. At the time of release only 3.3.0 was available but we will support the patch versions. We'll update the readme soon to be consistent.

**Comment by TheovanKraay** [comment]
Yes, the Databricks runtime information is outdated for the Spark 3.4 readme, this will be corrected in next release.

**Comment by PerFlodinVolvo** [comment]
Great! Again thanks for the info!

**Comment by kushagraThapar** [comment]
@TheovanKraay is this done? Can we close this issue?
