### ISSUE TITLE
How to authorize ConfidencialLedger endpoint permissions?

### ISSUE THREAD

**Issue by Jasun0925** [Azure/azure-sdk-for-java#35843]
**Query/Question**

When testing the `ConfidentialLedgerClientSample` code, calling the `createLedgerEntryWithResponse` method reported error 401.
error info: 
> Caught exceptioncom.azure.core.exception.ClientAuthenticationException: Status code 401, "{"error":{"code":"NotAllowed","message":"Not allowed to call POST /app/transactions"}}"

<img width="1555" alt="image" src="https://github.com/Azure/azure-sdk-for-java/assets/20411806/8d9b4318-6511-4009-baf6-2a4c8a6b41bb">

How can I set the API endpoint permissions?

**Comment by joshfree** [comment]
Hi @Jasun0925, the sample authenticates with `DefaultAzureCredential` from the `azure-identity` client library: [ConfidentialLedgerClientSample.java#L26-L29](https://github.com/Azure/azure-sdk-for-java/blob/main/sdk/confidentialledger/azure-security-confidentialledger/src/samples/java/com/azure/security/confidentialledger/ConfidentialLedgerClientSample.java#L26-L29)

You can read more about Azure Identity in the getting started section here: https://github.com/Azure/azure-sdk-for-java/blob/main/sdk/identity/azure-identity/README.md.

Let us know if you have any other questions.

**Comment by Jasun0925** [comment]
@joshfree I will report an error during the IDEA test using Default Azure Credential, as shown in the following figure:
<img width="1648" alt="image" src="https://github.com/Azure/azure-sdk-for-java/assets/20411806/199f6e90-d396-4190-a04d-b36ac0218a52">

**Comment by Jasun0925** [comment]
@joshfree When I set tentId in my local IDEA environment, it was successful. What is the reason for this?
` ConfidentialLedgerCertificateClientBuilder confidentialLedgerCertificateClientbuilder =
          new ConfidentialLedgerCertificateClientBuilder()
              .certificateEndpoint("https://identity.confidential-ledger.core.azure.com")
              .credential(
                  new DefaultAzureCredentialBuilder()
                      .tenantId("063e27f7-7e3f-4e4c-b4e7-ac862694b1b6")
                      .build())
              .httpClient(HttpClient.createDefault());`

Also, what method is used for authorization in the generation environment? Shouldn't it be using `DefaultAzureCredentialBuilder`?

**Comment by Jasun0925** [comment]
I found that no one answered this question and it has been bothering me for a long time. I will continue to create a ticket and hope that someone can answer it
[https://github.com/Azure/azure-sdk-for-java/issues/36177](https://github.com/Azure/azure-sdk-for-java/issues/36177)
