### ISSUE TITLE
Please remove the message "default messager has already been registered"

### ISSUE THREAD

**Issue by enaess** [Azure/azure-sdk-for-java#35855]
In a multi-project build, we have several projects that applies the azure-functions plugin. Unfortunately, it seems like the following snippet 

```java
       try {
            AzureOperationAspect.aspectOf().beforeEnter(var8);
            AzureTaskManager.register(new GradleAzureTaskManager());
            AzureMessager.setDefaultMessager(new GradleAzureMessager(project.getLogger()));
            AzureFunctionsExtension extension = (AzureFunctionsExtension)project.getExtensions().create("azurefunctions", AzureFunctionsExtension.class, new Object[]{project});
            TelemetryAgent.getInstance().initTelemetry("azure-functions-gradle-plugin", (String)StringUtils.firstNonBlank(new String[]{AzureFunctionsPlugin.class.getPackage().getImplementationVersion(), "develop"}), BooleanUtils.isNotFalse(extension.getAllowTelemetry()));
            TelemetryAgent.getInstance().showPrivacyStatement();
```

Runs through the code: 
`AzureMessager.setDefaultMessager(new GradleAzureMessager(project.getLogger()));`

Which checks against a static instance which is already populated in an previous application of the same plugin. This results in the code being executed in AzureMessager.java:

```java
            AzureMessager.getMessager().warning("default messager has already been registered");
```

We'd like that message removed please.

**Comment by joshfree** [comment]
Hi @enaess thanks for reaching out to us.  I believe this issue should be filed in the https://github.com/microsoft/azure-gradle-plugins/issues repo rather than here.  Let me know if I missed anything, and feel free to reactivate the issue if I misunderstood!

**Comment by enaess** [comment]
Yeah, I realized that it doesn't belong to neither of azure-sdk-for-java or azure-gradle-plugins projects, but it belong to azure-maven-plugins. Filed another bug here: https://github.com/microsoft/azure-maven-plugins/issues/2323 and opened a PR for it. 

Thanks for responding!
