### ISSUE TITLE
[Encryption] I need to encrypt a string with private key and decrypt with public key in key vault.

### ISSUE THREAD

**Issue by Hari-Nikesh-R** [Azure/azure-sdk-for-java#35883]
I was working on a Java project and tried connecting to Azure Key Vault. The dependencies I installed are as follows:
```pom
 <dependency>
            <groupId>com.azure</groupId>
            <artifactId>azure-security-keyvault-keys</artifactId>
            <version>4.6.3</version>
 </dependency>
```

I referred to the following link for guidance:
**https://github.com/Azure/azure-sdk-for-java/tree/main/sdk/keyvault/azure-security-keyvault-keys#list-keys**

**My requirement:**
I need to encrypt a string with a private key and decrypt it with a public key stored in the Key Vault.

I managed to obtain the public key using JWK, but I couldn't retrieve the private key. Is there a method or package available to retrieve the private key? Alternatively, do you have any suggestions on how to achieve my requirement?

Could anyone please assist me with this? If you need any further information, please let me know!

**Comment by joshfree** [comment]
Hi @Hari-Nikesh-R, sorry for the late reply here.  @vcolin7 can assist you here and will follow up shortly.

**Comment by vcolin7** [comment]
Hi @Hari-Nikesh-R, you can definitely obtain a key's private component by first setting its `exportable` property to `true` and then use the "release key" operation, however, if all you want to do is use a key stored in your vault to encrypt the contents of a string, you can instead [create a CryptographyClient](https://learn.microsoft.com/en-us/java/api/overview/azure/security-keyvault-keys-readme?view=azure-java-stable#create-cryptography-client) and encrypt your contents as shown [here](https://learn.microsoft.com/en-us/java/api/overview/azure/security-keyvault-keys-readme?view=azure-java-stable#encrypt). This way, you don't need to obtain the key material yourself and can let Key Vault do all the work server-side. We offer support for keys created with the following encryption algorithms:

For asymmetric keys:
- RSA1_5
- RSA_OAEP
- RSA_OAEP_256

For symmetric keys:
- A128CBC
- A192CBC
- A256CBC
- A128CBCPAD
- A192CBCPAD
- A256CBCPAD
- A128CBC-HS256
- A192CBC-HS384
- A256CBC-HS512
- A128GCM
- A192GCM
- A256GCM

Let me know if this serves your use case :)

**Comment by Hari-Nikesh-R** [comment]
Got it, CryptographyClient is working @vcolin7. Thanks a lot.
