### ISSUE TITLE
[BUG] ServiceBus.process span duration is incorrect when using maxConcurrentCalls > 1

### ISSUE THREAD

**Issue by trask** [Azure/azure-sdk-for-java#35916]
**Describe the bug**

ServiceBus.process span duration doesn't include the duration of the processing time when using maxConcurrentCalls != 1

**To Reproduce**

https://github.com/microsoft/ApplicationInsights-Java-Repros/tree/main/issue-2808

**Expected behavior**

The ServiceBus.process span duration should include the duration of the processing time when maxConcurrentCalls > 1

**Screenshots**

**Setup (please complete the following information):**
 - OS: Windows
 - IDE: n/a
 - Library/Libraries: com.azure:azure-messaging-servicebus:7.14.1, com.azure:azure-core-tracing-opentelemetry:1.0.0-beta.37
 - Java version: 8
 - App Server/Environment: n/a
 - Frameworks: Spring Boot

**Information Checklist**
Kindly make sure that you have added all the following information above and checkoff the required fields otherwise we will treat the issuer as an incomplete report
- [x] Bug Description Added
- [x] Repro Steps Added
- [x] Setup information Added

cc @lmolkova

**Comment by lmolkova** [comment]
thank you @trask!

related: https://github.com/Azure/azure-sdk-for-java/issues/35126

**Comment by rangarnow** [comment]
hi @trask @lmolkova, may I know what's the target date for fixing this issue? thanks

**Comment by lmolkova** [comment]
@rangarnow we're currently targeting August beta release which should happen in ~2 weeks.

**Comment by rangarnow** [comment]
@lmolkova thanks, please let me know when new version will be released, so that we could check it out.

**Comment by trask** [comment]
Hi @rangarnow, it looks like the fix made it into [azure-messaging-servicebus_7.14.3](https://github.com/Azure/azure-sdk-for-java/releases/tag/azure-messaging-servicebus_7.14.3)

**Comment by rangarnow** [comment]
hi @trask @lmolkova, please take a look at my comment 2 weeks ago (unanswered) after using latest service bus release. This release is definitely not something we can use in production system:
https://github.com/microsoft/ApplicationInsights-Java/issues/2808#issuecomment-1697233622

**Comment by trask** [comment]
hi @rangarnow, sorry for the delay, I've just followed up on https://github.com/microsoft/ApplicationInsights-Java/issues/2808#issuecomment-1697233622

**Comment by lmolkova** [comment]
@rangarnow I think I know what would be the problem - we fixed it in https://github.com/Azure/azure-sdk-for-java/pull/36367 and it should be released within the next week or so.

Sorry about that and thanks a lot for checking/

**Comment by rangarnow** [comment]
@trask @lmolkova looking forward to test new version :)

**Comment by trask** [comment]
hi @rangarnow, 7.14.4 should have the fix: https://repo1.maven.org/maven2/com/azure/azure-messaging-servicebus/7.14.4/
