### ISSUE TITLE
[BUG]Azure OpenAI client library for Java azure-ai-openai version 1.0.0-beta.2 will have special characters in Chinese.

### ISSUE THREAD

**Issue by zhimzhan** [Azure/azure-sdk-for-java#35928]
**Describe the bug**
[[A clear and concise description of what the bug is.](https://github.com/Azure/azure-sdk-for-java/blob/main/sdk/openai/azure-ai-openai/README.md)](https://github.com/Azure/azure-sdk-for-java/blob/main/sdk/openai/azure-ai-openai/README.md)
Using Azure OpenAI client library for Java version 1.0.0-beta.2 will cause speical characters in Chinese

This is because: 
OpenAI models return text in UTF-8 format, and the number of characters for decoding UTF-8 to Chinese varies from 1 to 4.

During the decoding process, as decoders generally do not automatically determine the stream boundary, it is easy to encounter garbled text when processing continuous input streams (stream mode), as you have mentioned.

In a JavaScript code analogy, consider this line: parser.feed(decoder.decode(chunk, { stream: true }));. The decoder retains the incomplete decoding state so that subsequent calls to the decoder() method can correctly decode characters across input stream boundaries. Without { stream: true }, the decoder does not consider previous or subsequent decoding operations and assumes a complete/independent byte sequence.

Suggest in Java code level, use CharsetDecoder to correctly handle characters across input stream boundaries.

***Exception or Stack Trace***
Add the exception log and stack trace if available

**To Reproduce**
Steps to reproduce the behavior: Azure OpenAI turbo model/ Stream mode/Chinese language

***Code Snippet***
Add the code snippet that causes the issue.
Same issue could be resolved in Java script:
https://github.com/lileihappy123/ChatGPT-Next-Web/commit/a05115da64e36f5f6a66b7699282fa1595bf6bed
Suggest to add follow code in SDK to resolve:

> import java.nio.ByteBuffer;
> import java.nio.CharBuffer;
> import java.nio.charset.CharacterCodingException;
> import java.nio.charset.Charset;
> import java.nio.charset.CharsetDecoder;
> import java.nio.charset.CodingErrorAction;
> 
> 
> public static String decodeByteBuffer(ByteBuffer input, CharsetDecoder decoder) {
>     try {
>         CharBuffer result = decoder.decode(input);
>         return result.toString();
>     } catch (CharacterCodingException e) {
>         e.printStackTrace();
>         return null;
>     }
> }

 

Charset charset = Charset.forName("UTF-8");
CharsetDecoder decoder = charset.newDecoder();
decoder.onMalformedInput(CodingErrorAction.REPLACE);
decoder.onUnmappableCharacter(CodingErrorAction.REPLACE);

String part1 = decodeByteBuffer(input1, decoder);
String part2 = decodeByteBuffer(input2, decoder);
String decodedString = part1 + part2;

**Expected behavior**

**Screenshots**

**Setup (please complete the following information):**
 - OS: [e.g. iOS]Any
 - IDE: [e.g. IntelliJ]Any
 - Library/Libraries: [e.g. com.azure:azure-core:1.16.0 (groupId:artifactId:version)] Java azure-ai-openai version 1.0.0-beta.2
 - Java version: [e.g. 8] any
 - App Server/Environment: [e.g. Tomcat, WildFly, Azure Function, Apache Spark, Databricks, IDE plugin or anything special]any
 - Frameworks: [e.g. Spring Boot, Micronaut, Quarkus, etc] 

If you suspect a dependency version mismatch (e.g. you see `NoClassDefFoundError`, `NoSuchMethodError` or similar), please check out [Troubleshoot dependency version conflict article](https://aka.ms/azsdk/java/dependency/troubleshoot) first. If it doesn't provide solution for the problem, please provide:
- verbose dependency tree (`mvn dependency:tree -Dverbose`)
- exception message, full stack trace, and any available logs

**Additional context**

**Information Checklist**
Kindly make sure that you have added all the following information above and checkoff the required fields otherwise we will treat the issuer as an incomplete report
- [ ] Bug Description Added
- [ ] Repro Steps Added
- [ ] Setup information Added

**Comment by mssfang** [comment]
Hi @zhimzhan Thanks for reaching out to us. Seems it is a similar issue to https://github.com/Azure/azure-sdk-for-java/issues/35694

We will have a newer version coming this week, which includes the fix to the issue.

**Comment by mssfang** [comment]
Updates: 
A newer version has just been released.
https://repo1.maven.org/maven2/com/azure/azure-ai-openai/1.0.0-beta.3/
