### ISSUE TITLE
[Maps Search] Investigate `searchAlongRoute` test failures

### ISSUE THREAD

**Issue by vcolin7** [Azure/azure-sdk-for-java#35979]
`searchAlongRoute` live tests have been failing because the service received no results when it used to return a list with 10 elements. I noticed the service JSON response contains a new parameter: `"geobiasCountry":"US"`, which might explain why the results differ. Still, this either occurred due to a code change in the library or a change on the service side and should be investigated and resolved.

I've disabled the test in question for the time being. They should be re-enabled once the issue is fixed.

**Comment by dubiety** [comment]
We'll investigate this issue soon. Thanks for reporting it.

**Comment by Lakicar95** [comment]
Closing this issue as it relates to V1 live tests. The V1 code has been removed, and the V2 library is now available with working live tests. We recommend using the V2 Search library instead.
