### ISSUE TITLE
[QUERY] Obtaining an access token from AuthorizedClientServiceOAuth2AuthorizedClientManager returns null

### ISSUE THREAD

**Issue by martfol** [Azure/azure-sdk-for-java#35999]
**Query/Question**
Hi guys, I'd like to ask you for help, since we're not able to find out what our exact problem is...

We have two spring boot applications (appA and appB), both serving as web application and resource server. The frontends are already integrated with Azure AD, so the SSO in browser works fine. Since the backends also need to communicate with each other (using just basic auth with a technical user until now), we're trying to switch also the backend authentication to Azure AD as well. However we're currently struggling with obtaining the access token from the AuthorizedClientServiceOAuth2AuthorizedClientManager - it always returns **null** (we need to use this one because we don't always have a request context in the backend process, however we do always have a SecurityContext - either it comes directly from a user frontend interaction or we create it ourselves eg from a jwt token that comes as a kafka message header).

Here's the defintion of our OAuth2AuthorizedClientManager:
```
  @Bean
  public OAuth2AuthorizedClientManager authorizedClientManager
      (ClientRegistrationRepository clients) {
    OAuth2AuthorizedClientService service =
        new InMemoryOAuth2AuthorizedClientService(clients);
    AuthorizedClientServiceOAuth2AuthorizedClientManager manager =
        new AuthorizedClientServiceOAuth2AuthorizedClientManager(clients, service);
    OAuth2AuthorizedClientProvider authorizedClientProvider =
        OAuth2AuthorizedClientProviderBuilder.builder()
            .clientCredentials()
            .build();
    manager.setAuthorizedClientProvider(authorizedClientProvider);
    return manager;
  }
```

Here's the call to obtain a new access token (the SecurityContextHolder contains the correct principal, which is the user logged in in the browser or the user that inititiated the asynchronous kafka reponse); however the "authorize" property is always null after calling the _authorize_ method):
```
  private OAuth2AccessToken getAccessToken() {
    OAuth2AuthorizeRequest request = OAuth2AuthorizeRequest.withClientRegistrationId("appB")
        .principal(SecurityContextHolder.getContext().getAuthentication()).build();
    OAuth2AccessToken accessToken = null;
    OAuth2AuthorizedClient authorize = authorizedClientManager.authorize(request);
    if (authorize != null) {
      accessToken = authorize.getAccessToken();
    }
    return accessToken;
  }
```

The exposed scopes configured in Azure Portal (I cannot personally check the Azure Portal configuration but I was assured that also the corresponding application permissions have been configured as "Delegated"):
```
api://appA/rest
api://appB/rest
```

Properties of appA:
```
spring.cloud.azure.active-directory.enabled=true
spring.cloud.azure.active-directory.profile.tenant-id=${SPRING_CLOUD_AZURE_ACTIVE_DIRECTORY_PROFILE_TENANT_ID}
spring.cloud.azure.active-directory.credential.client-id=${SPRING_CLOUD_AZURE_ACTIVE_DIRECTORY_CREDENTIAL_CLIENT_ID}
spring.cloud.azure.active-directory.credential.client-secret=${SPRING_CLOUD_AZURE_ACTIVE_DIRECTORY_CREDENTIAL_CLIENT_SECRET}
spring.cloud.azure.active-directory.application-type=web_application_and_resource_server
spring.cloud.azure.active-directory.app-id-uri=api://appA
spring.cloud.azure.active-directory.authorization-clients.appB.scopes=api://appB/rest
spring.cloud.azure.active-directory.authorization-clients.appB.authorizationGrantType=azure_delegated
spring.cloud.azure.active-directory.authorization-clients.graph.scopes=https://graph.microsoft.com/User.Read
spring.cloud.azure.active-directory.authorization-clients.graph.authorizationGrantType=azure_delegated
```

Properties of appB:
```
spring.cloud.azure.active-directory.enabled=true
spring.cloud.azure.active-directory.profile.tenant-id=${SPRING_CLOUD_AZURE_ACTIVE_DIRECTORY_PROFILE_TENANT_ID}
spring.cloud.azure.active-directory.credential.client-id=${SPRING_CLOUD_AZURE_ACTIVE_DIRECTORY_CREDENTIAL_CLIENT_ID}
spring.cloud.azure.active-directory.credential.client-secret=${SPRING_CLOUD_AZURE_ACTIVE_DIRECTORY_CREDENTIAL_CLIENT_SECRET}
spring.cloud.azure.active-directory.application-type=web_application_and_resource_server
spring.cloud.azure.active-directory.app-id-uri=api://appB
```

I assume the problem is that the _InMemoryOAuth2AuthorizedClientService.authorizedClients_ collection is empty when _InMemoryOAuth2AuthorizedClientService.loadAuthorizedClient_ gets called. So the the first question probably is, **why is the authorizedClients collection empty**? Are the properties not configured correctly? Or is it a configuration problem in Azure Portal?

I'm generally not sure if I'm injecting the OAuth2AuthorizedClientManager properly or what the problem could be. Should I use maybe some other bean as _OAuth2AuthorizedClientService_ instead of _InMemoryOAuth2AuthorizedClientService_? Does anyone please have an idea? Would highly appreciate any help or assistance, thanks a lot :)

***Why is this not a Bug or a feature Request?***
This is neither a bug, nor a feature request... Just a question :)

**Setup (please complete the following information if applicable):**
 - Library/Libraries: spring-boot 2.7.8, spring-cloud-azure 4.4.1
 
 **Information Checklist**
 Kindly make sure that you have added all the following information above and checkoff the required fields otherwise we will treat the issuer as an incomplete report
- [x] Query Added
- [x] Setup information Added

**Comment by martfol** [comment]
Hi, we have a small update. The first problem was that we were setting apparently a wrong authorizedClientProvider for client credentials, which of course cannot work with azure_delegated authorizationGrantType. Now we are trying to set the _AadAzureDelegatedOAuth2AuthorizedClientProvider_:

```
@Bean
  public OAuth2AuthorizedClientManager authorizedClientManager(
      ClientRegistrationRepository clients,
      OAuth2AuthorizedClientService service,
      OAuth2AuthorizedClientRepository authorizedClients,
      RefreshTokenOAuth2AuthorizedClientProvider refreshTokenProvider) {
    AuthorizedClientServiceOAuth2AuthorizedClientManager manager =
        new AuthorizedClientServiceOAuth2AuthorizedClientManager(clients, service);

    manager.setAuthorizedClientProvider(new AadAzureDelegatedOAuth2AuthorizedClientProvider(refreshTokenProvider, authorizedClients));

    return manager;
  }
```

Now the problem is that the AadAzureDelegatedOAuth2AuthorizedClientProvider fails on the `getHttpServletRequestOrDefault(context)` method saying that the "request cannot be null" (because even _getDefaultHttpServletRequest()_ returns null). As I mentioned, we don't have a request context here. But why is it trying to find one?

**Comment by Netyyyy** [comment]
Hi @martfol  Thank you for reaching out.
We have received your submission and will take it into consideration. We appreciate your input and will review this matter ASAP.
Please feel free to provide any conditional information or context that you think may be helpful. We'll keep you updated on the progress of our review.
Thank you for your contribution to improving our project.

**Comment by martfol** [comment]
Hi @Netyyyy, thanks for your reply! Maybe it would be easier for us to solve the problem, if there were any working code examples of how to use/define the _AuthorizedClientServiceOAuth2AuthorizedClientManager_ in combination with _azure_delegated_ grant type in order to obtain an access token. Is there please something like that documented somewhere? We were unfortunately unable to find such code example online.

**Comment by martfol** [comment]
Hi @Netyyyy / guys , here's our updated situation, I'm asking for help, I still have no clue what is the problem here...

Bean definition:

```
  @Bean
  public OAuth2AuthorizedClientService auth2AuthorizedClientService(
      ClientRegistrationRepository clientRegistrationRepository) {
    return new InMemoryOAuth2AuthorizedClientService(clientRegistrationRepository);
  }

  @Bean
  public OAuth2AuthorizedClientManager authorizedClientManager(
      ClientRegistrationRepository clients,
      OAuth2AuthorizedClientService service,
      RefreshTokenOAuth2AuthorizedClientProvider refreshTokenProvider) {

    AuthorizedClientServiceOAuth2AuthorizedClientManager manager =
        new AuthorizedClientServiceOAuth2AuthorizedClientManager(clients, service);

    OAuth2AuthorizedClientRepository authorizedClients =
        new AuthenticatedPrincipalOAuth2AuthorizedClientRepository(service);

    manager.setAuthorizedClientProvider(
        new AadAzureDelegatedOAuth2AuthorizedClientProvider(refreshTokenProvider, authorizedClients));

    return manager;
  }
```
Obtaining the access token is the same as in my very first comment:
```
  private OAuth2AccessToken getAccessToken() {
    OAuth2AuthorizeRequest request = OAuth2AuthorizeRequest.withClientRegistrationId("appB")
        .principal(SecurityContextHolder.getContext().getAuthentication()).build();
    OAuth2AccessToken accessToken = null;
    OAuth2AuthorizedClient authorize = authorizedClientManager.authorize(request);
    if (authorize != null) {
      accessToken = authorize.getAccessToken();
    }
    return accessToken;
  }
```
Currently it fails on line 142 in AuthorizedClientServiceOAuth2AuthorizedClientManager.authorize:
```
try {
	authorizedClient = this.authorizedClientProvider.authorize(authorizationContext);
}
```
...which calls:

1. `AadAzureDelegatedOAuth2AuthorizedClientProvider.authorize`, then...
2. `AuthenticatedPrincipalOAuth2AuthorizedClientRepository.loadAuthorizedClient`, and here `this.isPrincipalAuthenticated(principal) == true` so it goes to...
3. `InMemoryOAuth2AuthorizedClientService.loadAuthorizedClient` - and here the `authorizedClients` **collection is empty**, so only null can be returned and therefore...
4. `AadAzureDelegatedOAuth2AuthorizedClientProvider.authorize` throws _[client_authorization_required] Authorization required for Client Registration Id: azure_ on line 92.


Apparently we're missing something, because `AuthenticatedPrincipalOAuth2AuthorizedClientRepository.saveAuthorizedClient` gets never called, so no authorizedClients are saved into the `InMemoryOAuth2AuthorizedClientService.authorizedClients` collection . But how/where to implement this? Please help, we are out of ideas :)
