### ISSUE TITLE
[BUG] Vulnerabilities with Azure Key Vault for Java

### ISSUE THREAD

**Issue by cheenamalhotra** [Azure/azure-sdk-for-java#3602]
Azure Key Vault for Java has vulnerabilities with one of its dependencies in v1.2.1:

`com.fasterxml.jackson.core:jackson-databind 2.9.7`

Please find report here: https://dev.azure.com/sqlclientdrivers-ci/mssql-jdbc/_componentGovernance/112445/alert/1439591?typeId=764536

Please upgrade dependent library to 2.9.8

**Comment by kurtzeborn** [comment]
Thanks for bringing this up.  We're already tracking this issue here: https://github.com/Azure/azure-sdk-for-java/issues/2970  No ETA yet.
