### ISSUE TITLE
[BUG]: GetSubscriptionExists throws a 404

### ISSUE THREAD

**Issue by tux4ever** [Azure/azure-sdk-for-java#36050]
**Describe the bug**
The ServiceBusAdministrationClient getSubscriptionExists throws a 404 if the subscription does not exist.

***Exception or Stack Trace***
<pre>
Caused by: com.azure.messaging.servicebus.administration.implementation.models.ServiceBusManagementErrorException: Status code 404, "<Error><Code>404</Code><Detail>Entity 'poi-retail-cd:Topic:test-topic|test-sub1' was not found. To know more visit https://aka.ms/sbResourceMgrExceptions.  TrackingId:84fb37db-98e2-41e5-a4ee-4dff696e2e35_B60, SystemTracker:NoSystemTracker, Timestamp:2023-07-24T06:13:58</Detail></Error>"
</pre>

**To Reproduce**
Call the getSubscriptionExists method in the Admin Client for a valid topic and a subscription which does not exist.

***Code Snippet***
```
final ServiceBusAdministrationClient client =
            new ServiceBusAdministrationClientBuilder()
                .connectionString(String.format("Endpoint=sb://%s/;SharedAccessKeyName=RootManageSharedAccessKey;" +
                    "SharedAccessKey=%s;", serviceBusNamespace, token)).buildClient();

        if (client.getSubscriptionExists(topic, subscription))
        {
            LOGGER.info("Subscription exists.");
        }
```

**Expected behavior**
The method should return true or false in case the subscription does not exist instead of throwing an exception.

**Setup (please complete the following information):**
 - Library/Libraries: com.azure:azure-client-sdk-parent:7.14.1
 - Java version: 17 

If you suspect a dependency version mismatch (e.g. you see `NoClassDefFoundError`, `NoSuchMethodError` or similar), please check out [Troubleshoot dependency version conflict article](https://aka.ms/azsdk/java/dependency/troubleshoot) first. If it doesn't provide solution for the problem, please provide:
- verbose dependency tree (`mvn dependency:tree -Dverbose`)
- exception message, full stack trace, and any available logs

**Additional context**
Problem seems to exist since 7.11. In 7.10 the function works as expected.

**Comment by anuchandy** [comment]
Please refer the thread https://github.com/Azure/azure-sdk-for-java/issues/33609 for the same issue, a temporary workaround is provided while we look into this.
