### ISSUE TITLE
[BUG]Anomalous persisted high lag detected on All Versions/FFCF with no recent traffiic

### ISSUE THREAD

**Issue by jculala** [Azure/azure-sdk-for-java#36061]
**Describe the bug**
CFP pipeline is enabled last 24 hours with no traffic. As of this moment lag is ~5.4K and is further accumulating

***Exception or Stack Trace***
n/a

**To Reproduce**
This is regarding getCurrentState API in Full Fidelity mode.
For testing purpose, we enabled a full fidelity cosmic pipeline app in non-prod and performed below steps.
Created monitored container: Address
Started Cosmic pipeline in Full Fidelity mode.
Triggered few CRUD operations (create, replace, delete..etc)
Noticed Lag went down
Further no traffic
Noticed Lag getting accumulated.
 
Even though there is no data, we are seeing the lag getting accumulated.  Can you please check and share your findings.
Please find the below snapshots and attached logs.

***Code Snippet***

**Expected behavior**
Zero lag.

**Screenshots**

**Setup (please complete the following information):**
Monitored Container: Address
version: 4.37.2-hotfix - Central Repository: com/azure/azure-cosmos/4.37.2-hotfix (maven.org)

**Comment by kushagraThapar** [comment]
@jculala - thanks, ack on this issue, as we dig deeper into any alternatives that we can come up with to reduce this artificial lag.

**Comment by kushagraThapar** [comment]
This has been solved, closing it here.
