### ISSUE TITLE
[openAI] Serialized Storage Context

### ISSUE THREAD

**Issue by liuyu-struggle** [Azure/azure-sdk-for-java#36077]
I want to store the content of each conversation and use it as the context for each conversation.
But I encountered a problem. When I serialized the dialog information into strings, I found that the role information could not be serialized.

Using version： 1.0.0-beta.3
Serialization tool： fastjson 1.2.83

usage：
```
List<ChatMessage> messages = new ArrayList<>();
messages.add(new ChatMessage(ChatRole.SYSTEM, content));
ChatCompletionsOptions chatCompletionsOptions = new ChatCompletionsOptions(messages );

JSON.toJSONString(chatCompletionsOptions)
```
![image](https://github.com/Azure/azure-sdk-for-java/assets/37584392/00e70820-d287-43f3-85f0-52cee2cd9a82)

![image](https://github.com/Azure/azure-sdk-for-java/assets/37584392/281efd50-0b73-4c18-9d86-a27ea809b652)
I don't know how to properly store every conversation information and role right now.
I hope to receive your help.
Thank you!
@mssfang 

The above content comes from translation software

**Comment by mssfang** [comment]
You can try, our built-in method, 
String jsonString = BinaryData.fromObject(chatOptions).toString();

**Comment by liuyu-struggle** [comment]
> @liuyu-struggle 你可以尝试一下，我们自己内置的方法，
> 
> ```
> String jsonString = BinaryData.fromObject(chatOptions).toString();
> // Result: 
> // {"messages":[{"role":"user","content":"hello"}],"max_tokens":512,"temperature":0.1,"top_p":1.0,"logit_bias":{},"n":1,"presence_penalty":0.0,"frequency_penalty":0.0}
> ```

Thank you. 
```
String jsonString = BinaryData.fromObject(chatOptions).toString();
```
Solved my problem!
