### ISSUE TITLE
Incorrect link for Streaming Chat Completions

### ISSUE THREAD

**Issue by pmalarme** [Azure/azure-sdk-for-java#36082]
The link for Streaming Chat Completions is not correct: 'https://dgithub.com/Azure/azure-sdk-for-java/blob/main/sdk/openai/azure-ai-openai/src/samples/java/com/azure/ai/openai/usage/GetChatCompletionsStreamSample.java'. It is dgithub.com instead of github.com.

![image](https://github.com/Azure/azure-sdk-for-java/assets/686568/ece5c7c3-df01-48d2-a5dc-49fd250bcef4)

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 205fdbba-b0b8-4e14-a79a-84cfac9e8682
* Version Independent ID: c193b550-de22-850d-55d3-5b22ec11ad40
* Content: [Azure OpenAI client library for Java](https://learn.microsoft.com/en-us/java/api/overview/azure/ai-openai-readme?view=azure-java-preview#streaming-chat-completions)
* Content Source: [docs-ref-services/preview/ai-openai-readme.md](https://github.com/Azure/azure-docs-sdk-java/blob/master/docs-ref-services/preview/ai-openai-readme.md)
* Service: **openai**
* GitHub Login: @joshfree
* Microsoft Alias: **jfree**

**Comment by mssfang** [comment]
@pmalarme Thank you for finding this. PR created: https://github.com/Azure/azure-sdk-for-java/pull/36084
