### ISSUE TITLE
[BUG] spring-messaging-azure-servicebus when Upgreading spring boot version from 2.7.13 to 3.1.0 Throws a bean not found error

### ISSUE THREAD

**Issue by AsmaeFILALI** [Azure/azure-sdk-for-java#36114]
**Describe the bug**
*spring-messaging-azure-servicebus* when Upgreading spring boot version from 2.7.13 to 3.1.0 Throws an Error, the Same code works well in the spring version 2.7.13, in the documentation the only step for migrating to spring 3.x.x is to use *spring-cloud-azure-dependencies* with the version 5.3.0

***Exception or Stack Trace***
```Application Failed to start, Description: A component required a bean named 'azureServiceBusListenerContainerFactory' that could not be found.```

**To Reproduce**
- Use the code sample from the Documentation for spring messaging with service bus : https://learn.microsoft.com/en-us/azure/developer/java/spring-framework/using-service-bus-in-spring-applications#use-spring-messaging-azure-service-bus
- Upgrade the spring version to 3.1.0 and java version to 17
- For spring-cloud-azure-dependencies use the version : 5.3.0
***Code Snippet***
- relevant dependencies in pom.xml
```xml
	<dependency>
			<groupId>com.azure.spring</groupId>
			<artifactId>spring-cloud-azure-starter</artifactId>
		</dependency>
		<dependency>
			<groupId>com.azure.spring</groupId>
			<artifactId>spring-messaging-azure-servicebus</artifactId>
		</dependency>
	</dependencies>
	<build>
		<plugins>
			<plugin>
				<groupId>org.springframework.boot</groupId>
				<artifactId>spring-boot-maven-plugin</artifactId>
			</plugin>
		</plugins>
	</build>
	<dependencyManagement>
		<dependencies>
			<dependency>
				<groupId>com.azure.spring</groupId>
				<artifactId>spring-cloud-azure-dependencies</artifactId>
				<version>5.3.0</version>
				<type>pom</type>
				<scope>import</scope>
			</dependency>
		</dependencies>
	</dependencyManagement>
</project>
```

- META-INF/spring.factories
```
org.springframework.boot.autoconfigure.EnableAutoConfiguration=\
com.azure.spring.cloud.autoconfigure.messaging.AzureMessagingListenerAutoConfiguration
```

The code is the same as the one instructed in microsoft's documentation : https://learn.microsoft.com/en-us/azure/developer/java/spring-framework/using-service-bus-in-spring-applications#use-spring-messaging-azure-service-bus
**Expected behavior**
That the Application starts and sends/recieves messages from servicebus

**Screenshots**

**Setup (please complete the following information):**
 - OS: windows
 - IDE: vscode
 - Library/Libraries: com.azure.spring:spring-cloud-azure-dependencies:5.3.0 imported in the dependency management
 - Java version: [17] 
 - App Server/Environment: Tomcat embeded in springboot
 - Frameworks:  Spring Boot 3.1.0

If you suspect a dependency version mismatch (e.g. you see `NoClassDefFoundError`, `NoSuchMethodError` or similar), please check out [Troubleshoot dependency version conflict article](https://aka.ms/azsdk/java/dependency/troubleshoot) first. If it doesn't provide solution for the problem, please provide:
- verbose dependency tree (`mvn dependency:tree -Dverbose`)
- exception message, full stack trace, and any available logs

**Additional context**
- Have done a debug for trying to resolve the issue, first thing it looks that AzureMessagingListenerAutoConfiguration package have changed from com.azure.spring.cloud.autoconfigure.messaging to com.azure.spring.cloud.autoconfigure.implementation.messaging
- I have included the  com.azure.spring.cloud.autoconfigure.implementation.messaging.AzureMessagingListenerAutoConfiguration  in the spring.factories file as following 
```
org.springframework.boot.autoconfigure.EnableAutoConfiguration=\
com.azure.spring.cloud.autoconfigure.implementation.messaging.AzureMessagingListenerAutoConfiguration
```
The above steps did not resolve the Issue, I have put a break point in the class `com.azure.spring.cloud.autoconfigure.implementation.messaging.AzureMessagingListenerAutoConfiguration` the debbuger never stops on it while stopping on the other autoconfiguration classes 

**Information Checklist**
Kindly make sure that you have added all the following information above and checkoff the required fields otherwise we will treat the issuer as an incomplete report
- [X] Bug Description Added
- [X] Repro Steps Added
- [X] Setup information Added

**Comment by saragluna** [comment]
Thanks for reaching out, we changed the file location for this configuration, to `com.azure.spring.cloud.autoconfigure.implementation.messaging`. Try the new value to see whether it solves the issue.

**Comment by saragluna** [comment]
And https://github.com/Azure/azure-sdk-for-java/pull/35717 has enabled it automatically, so with next version you won't need configure it by yourself anymore.

**Comment by AsmaeFILALI** [comment]
Thank you for your response @saragluna, 
- including `com.azure.spring.cloud.autoconfigure.implementation.messaging.AzureMessagingListenerAutoConfiguration` did not solve the issue, to investigate more I started the app in a debug mode and put multiple breakpoints on the class `AzureMessagingListenerAutoConfiguration`, the debbuger never stops on it while it stops on the other autoconfiguration classes, that explains the missing bean `azureServiceBusListenerContainerFactory` since it's inithalised in the `AzureMessagingListenerAutoConfiguration` class.
- I have also tried not including any configuration in the spring.factories file to see if it's configured automatically and I get the same result (same error)

**Comment by Netyyyy** [comment]
Hi @AsmaeFILALI , thanks for the reply,
For Spring Boot 3, please make sure you added `com.azure.spring.cloud.autoconfigure.implementation.messaging.AzureMessagingListenerAutoConfiguration` in `META-INF/spring/org.springframework.boot.autoconfigure.AutoConfiguration.imports` instead of `spring.factories`, FYI: https://github.com/spring-projects/spring-boot/wiki/Spring-Boot-3.0-Migration-Guide#auto-configuration-files.

BTW, we will release Spring Cloud Azure 5.4.0 and 4.10.0 recently, in which you needn't add `AzureMessagingListenerAutoConfiguration` manually.

**Comment by AsmaeFILALI** [comment]
Hi @Netyyyy, that worked perfectly, thanks a lot !

**Comment by Netyyyy** [comment]
close for resolved
