### ISSUE TITLE
[QUERY] spring-cloud-azure-starter-stream-servicebus 4.5.0 auto-generating "prefetch" events

### ISSUE THREAD

**Issue by rmolcr** [Azure/azure-sdk-for-java#36128]
**Query/Question**
I've been using `com.azure.spring:spring-cloud-azure-starter-stream-servicebus:4.3.0` for some months now to integrate a Kotlin application with Azure Service Bus, and I am able to produce and consume events from Azure (topic - subscription approach). The implementation is based on: https://learn.microsoft.com/en-us/azure/developer/java/spring-framework/configure-spring-cloud-stream-binder-java-app-with-service-bus?tabs=use-a-service-bus-topic#send-and-receive-messages-from-azure-service-bus

I'm trying to update to `com.azure.spring:spring-cloud-azure-starter-stream-servicebus:4.5.0`, but what I am seeing is that from this version, when the application starts-up the producer starts auto-generating a lot of events like this and sending them to the topic:
```
{"scanAvailable":true,"prefetch":-1}
```

Could anyone kindly point me to any documentation that could help on understanding why is this happening, and also if it could be somehow disabled? As you can imagine, the consumers that I have subscribed to this producer are generating errors as they don't expect this kind of event.

Thanks in advance.

***Why is this not a Bug or a feature Request?***
Library is actually working, but some internal behavior has changed in version 4.5.0.

**Setup (please complete the following information if applicable):**
 - OS: n/a
 - IDE: n/a
 - Library/Libraries: `com.azure.spring:spring-cloud-azure-starter-stream-servicebus:4.5.0`
 
 **Information Checklist**
 Kindly make sure that you have added all the following information above and checkoff the required fields otherwise we will treat the issuer as an incomplete report
- [x] Query Added
- [x] Setup information Added

**Comment by Netyyyy** [comment]
Hi @rmolcr , thanks for reaching out.
could you help provide more information such as a pom file or a minimal project?

**Comment by rmolcr** [comment]
Hi @Netyyyy ,

Sorry for the delay on the response.

I will share a sample `build.gradle.kts` file since this is a private project. I could try to create a public minimal project that replicates the issue if this information is not enough.

Thanks in advance!

```
import org.jetbrains.kotlin.gradle.tasks.KotlinCompile

plugins {
	id("org.springframework.boot") version "2.7.10"
	id("io.spring.dependency-management") version "1.0.15.RELEASE"
	id("io.freefair.lombok") version "6.5.1"
	id("org.flywaydb.flyway") version "9.8.1"
	kotlin("jvm") version "1.6.21"
	kotlin("plugin.spring") version "1.6.21"
	kotlin("plugin.jpa") version "1.6.21"
}

group = "com.myproject"
version = "0.0.1-SNAPSHOT"
java.sourceCompatibility = JavaVersion.VERSION_15

repositories {
	mavenCentral()
}

dependencies {
	implementation("com.azure.spring:spring-cloud-azure-starter-stream-servicebus:4.5.0")
	implementation("com.fasterxml.jackson.module:jackson-module-kotlin")
	implementation("com.google.code.gson:gson")
	implementation("org.flywaydb:flyway-core")
	implementation("org.hibernate:hibernate-core")
	implementation("org.jetbrains.kotlin:kotlin-reflect")
	implementation("org.jetbrains.kotlin:kotlin-stdlib-jdk8")
	implementation("org.jetbrains.kotlin:kotlin-stdlib")
	implementation("org.slf4j:slf4j-api")
	implementation("org.springframework.boot:spring-boot-starter-data-jpa")
	implementation("org.springframework.boot:spring-boot-starter-web")
	implementation("org.springframework.boot:spring-boot-starter-validation")

	runtimeOnly("org.postgresql:postgresql")
}

tasks.withType<KotlinCompile> {
	kotlinOptions {
		freeCompilerArgs = listOf("-Xjsr305=strict")
		jvmTarget = "15"
	}
}

tasks.withType<Test> {
	useJUnitPlatform()
}
```

**Comment by Netyyyy** [comment]
Hi @rmolcr thanks for the reply.
Could you try the latest version `com.azure.spring:spring-cloud-azure-starter-stream-servicebus:4.10.0` and test again?

**Comment by rmolcr** [comment]
Hi @Netyyyy, already tried version `4.10.0` and the behaviour is the same.

Could you point me to any documentation that explains the origin of this kind of event being auto-generated?

Regards

**Comment by Netyyyy** [comment]
Hi @anuchandy , Could you help take a look?
I think it's servicebus sdk has changed some codes, because we don't do anything about that

**Comment by anuchandy** [comment]
Hi @Netyyyy, @rmolcr - this looks very similar to this one https://stackoverflow.com/questions/70846501/spring-reactive-returns-scanavailable-and-prefetch-instead-of-object and https://github.com/spring-projects/spring-boot/issues/30052 where the Spring Boot is including these attributes in the Spring Response value.

**Comment by rmolcr** [comment]
Hi @anuchandy,

Thanks for the references, already saw it and guess could be related.

Unfortunately, I am struggling to understand how the above mentioned issues could relate to the [sample code](https://github.com/rmolcr/azure-servicebus-integration/tree/main/src/main) I previously shared, as we are not using nested `Flux` or using `map`/`flatMap` function while generating the events, we have a very similar implementation as the [Azure sample project](https://github.com/Azure-Samples/azure-spring-boot-samples/tree/main/servicebus/spring-cloud-azure-stream-binder-servicebus/servicebus-topic-binder).

Could you give us some light here or related docs that could help?

thanks in advance

**Comment by anuchandy** [comment]
Hi, I don’t have enough knowledge in the internals of Spring framework to understand how these two fields get auto populated and how to exclude them. I did some online search and couldn’t locate any useful references. We didn’t change any contract of types in "Service Bus SDK public surface", as that would be breaking change. The only thing I found is –  "scanAvailable" and "prefetch" are fields of certain Reactor operators (e.g., implementing Scannable). So likely when Spring serializes, it finds one of the Flux|Mono|Many|* in a place where it should be plain model.

@Netty, when moving from 4.3.0 to 4.5.0 of com.azure.spring:spring-cloud-azure-starter-stream-servicebus, does it change version of underlying org.springframework:* dependencies? 

If so, I wonder if this can be validated by trimming the sample app by removing com.azure.spring:spring-cloud-azure-starter-stream-servicebus, then somehow log the serialized output the org.springframework:* produces (that otherwise gets fed into spring-servicebus). If the output has these fields populated, then this should be some change in org.springframework:*.

**Comment by Netyyyy** [comment]
Sure, thanks for help and we will take a look for it.

**Comment by rmolcr** [comment]
Hi,

We are going to do deeper investigation in our implementation.
I have tested a similar scenario following Azure code samples (Java) and I cannot reproduce the issue, so we need to do further investigations as our codebase is Kotlin based.

Thanks @anuchandy @Netyyyy for your help.

Regards

**Comment by anuchandy** [comment]
Closing this, Roi is going to investigate the application to see if it’s something in the app setup triggering this  (the direct use of the Azure library  with samples works as expected).
