### ISSUE TITLE
Table Samples Issue 

### ISSUE THREAD

**Issue by Menghua1** [Azure/azure-sdk-for-java#36159]
**Section** [link1](https://github.com/Azure/azure-sdk-for-java/blob/main/sdk/tables/azure-data-tables/src/samples/java/com/azure/data/tables/codesnippets/TableServiceClientJavaDocCodeSnippets.java#L167), [link2](https://github.com/Azure/azure-sdk-for-java/blob/main/sdk/tables/azure-data-tables/src/samples/java/com/azure/data/tables/codesnippets/TableServiceClientJavaDocCodeSnippets.java#L184):
![image](https://github.com/Azure/azure-sdk-for-java/assets/111940661/76f2fecd-6bc2-44ef-9ac4-26777e0d7d28)
**Reason**:
	XML specified is not syntactically valid.The IncludeApis and RetentionPolicy parameters of the TableServiceMetrics object are not set .

**Suggestion**:
Update code to
```
TableServiceProperties properties = new TableServiceProperties()
	            .setHourMetrics(new TableServiceMetrics()
	                .setVersion("1.0")
	                .setEnabled(true))
                        .setIncludeApis(true)
	                .setRetentionPolicy(new TableServiceRetentionPolicy()
	                    .setEnabled(true)
	                    .setDaysToRetain(5))
	            .setLogging(new TableServiceLogging()
	                .setAnalyticsVersion("1.0")
	                .setReadLogged(true)
	                .setRetentionPolicy(new TableServiceRetentionPolicy()
	                    .setEnabled(true)
	                    .setDaysToRetain(5)));
```

@sandeep-sen, @josefree, @mario-guerra, @annatisch and @jairmyree for notification.

**Comment by jairmyree** [comment]
Thank you @Menghua1, I will follow up on this.
