### ISSUE TITLE
Monitor Ingestion Samples Issue 

### ISSUE THREAD

**Issue by Menghua1** [Azure/azure-sdk-for-java#36156]
1.
**Section** [link](https://github.com/Azure/azure-sdk-for-java/blob/main/sdk/monitor/azure-monitor-ingestion/src/samples/java/com/azure/monitor/ingestion/ReadmeSamples.java#L122):
![image](https://github.com/Azure/azure-sdk-for-java/assets/111940661/4a57bbb2-8e85-4e75-b1b1-ba166215dbce)
**Reason**:
java.lang.IllegalStateException: endpoint is required to build the client.

**Suggestion**:
	Update code to 
```
LogsIngestionClient logsIngestionClient = new LogsIngestionClientBuilder()
	            .endpoint("<data-collection-endpoint>")
	            .credential(credential)
	            .httpLogOptions(new HttpLogOptions().setLogLevel(HttpLogDetailLevel.BODY_AND_HEADERS))
	            .buildClient();
```
@sandeep-sen, @josefree, @scottaddie and @srnagar for notification.

**Comment by jairmyree** [comment]
Thank you @Menghua1, I will follow up on this.
