### ISSUE TITLE
Identity Samples Issue

### ISSUE THREAD

**Issue by Menghua1** [Azure/azure-sdk-for-java#36155]
1.
**Section** [link](https://github.com/Azure/azure-sdk-for-java/blob/main/sdk/identity/azure-identity/src/samples/java/com/azure/identity/credential/JavaDocCodeSnippets.java#L268):
![image](https://github.com/Azure/azure-sdk-for-java/assets/111940661/5c8cb664-1ae4-4cb4-bb5a-060b1764329d)
**Reason**:
java.lang.IllegalArgumentException: Must provide non-null values for tenantId properties in OnBehalfOfCredentialBuilder.

**Suggestion**:
Update code to 
```
TokenCredential onBehalfOfCredential = new OnBehalfOfCredentialBuilder()
	                .clientId("<app-client-ID>")
	                .clientSecret("<app-Client-Secret>")
	                .tenantId("<app-tenant-ID>")
	                .userAssertion("<user-assertion>")
                        .build();
```

@sandeep-sen, @josefree, @scottaddie, @ctstone and @AikoBB for notification.

**Comment by joshfree** [comment]
Nice catch, thank you @Menghua1.  @billwert could you fix this before the next GA is released?
