### ISSUE TITLE
Service Bus Samples Issue 

### ISSUE THREAD

**Issue by Menghua1** [Azure/azure-sdk-for-java#36158]
1.
**Section**  [link](https://github.com/Azure/azure-sdk-for-java/blob/main/sdk/servicebus/azure-messaging-servicebus/src/samples/java/com/azure/messaging/servicebus/ReadmeSamples.java#L71):
![image](https://github.com/Azure/azure-sdk-for-java/assets/111940661/14163441-8a5c-4020-88a3-ad22ee470d6a)
**Reason**:
'fullyQualifiedNamespace' cannot be an empty string.

**Suggestion**:
Update code to
  ```
              AzureNamedKeyCredential azureNamedKeyCredential =
	                new AzureNamedKeyCredential("<<azure-service-sas-key-name>>", "<<azure-service-sas-key>>");
	        ServiceBusReceiverAsyncClient receiver = new ServiceBusClientBuilder()
	                .credential(azureNamedKeyCredential)
	                .fullyQualifiedNamespace("<<fully-qualified-namespace>>")
	                .receiver()
	                .queueName("<<queue-name>>")
	                .buildAsyncClient();
```

@sandeep-sen, @josefree, @ronniegeraghty, @JoshLove-msft and @anuchandy for notification.

**Comment by joshfree** [comment]
@lmolkova could you assist here given @anuchandy's current bug load.
