### ISSUE TITLE
[FEATURE REQ] mgmt network, change application gateway default size and tier to `BASIC`

### ISSUE THREAD

**Issue by XiaofeiCao** [Azure/azure-sdk-for-java#36215]
Application gateway v1 has been officially deprecated: 
https://learn.microsoft.com/en-us/azure/application-gateway/v1-retirement#retirement-timelines

In fact, we are not able to create v1 instances any more. 

We have default implementation to set skuSize to `STANDARD_SMALL`:
https://github.com/Azure/azure-sdk-for-java/blob/a95f8f0fccc4f1a3310890d36c6cc5f0602479ee/sdk/resourcemanager/azure-resourcemanager-network/src/main/java/com/azure/resourcemanager/network/implementation/ApplicationGatewaysImpl.java#L32-L35

Will change it to `BASIC` when it gets into next stable release version(aka [2023-04-01](https://github.com/Azure/azure-rest-api-specs/blob/4cd95123fb961c68740565a1efcaa5e43bd35802/specification/network/resource-manager/Microsoft.Network/stable/2023-04-01/applicationGateway.json#L1311)).

**Comment by weidongxu-microsoft** [comment]
Which tier would `BASIC` map?

**Comment by XiaofeiCao** [comment]
> Which tier would `BASIC` map?
> 
> Ah, I see, `BASIC`.

Yeah, I believe it's `BASIC`. Will check it in test when we adopt the new api-version.

**Comment by weidongxu-microsoft** [comment]
PR on 2023-04 https://github.com/Azure/azure-sdk-for-java/pull/36242. It gets the `BASIC`.
