### ISSUE TITLE
[QUERY] Azure-monitor-opentelemetry-exporter warning Hit max 100 active concurrent requests

### ISSUE THREAD

**Issue by EvaSRGitHub** [Azure/azure-sdk-for-java#36219]
**Query/Question**
We have java app, where we are using Azure monitor openTelemetry exporter library for Java and we constantly get warnings like this one:
**com.azure.monitor.opentelemetry.exporter.implementation.pipeline.TelemetryItemExporter, source line 179
In the last 5 minutes, the following operation has failed 4877 times (out of 39962): Put export into the background (don't wait for it to return): Hit max 100 active concurrent requests (4877 times)**
And we couldn't understand what cause this problem and how to fix it. 
We had configure the OpenTelemetrySdk Bean as follows:

```
var exporter = new AzureMonitorExporterBuilder()
                .connectionString(exporterConnectionString)
                .buildTraceExporter();
```
 ```
 var tracerProvider = SdkTracerProvider.builder()
                .addSpanProcessor(SimpleSpanProcessor.create(exporter))
                .setSampler(tracingEnabled ? Sampler.alwaysOn() : Sampler.alwaysOff())
                .build();
```
```
  return OpenTelemetrySdk.builder()
                .setTracerProvider(tracerProvider)
                .setPropagators(ContextPropagators.create(W3CTraceContextPropagator.getInstance()))
                .buildAndRegisterGlobal();
```

***Why is this not a Bug or a feature Request?***
I am not sure if this is a bug or not. It seems more like missing or wrong exporter configuration.

**Setup (please complete the following information if applicable):**
 - OS: MacOS, App is using Java 17 and is deployed on K8S in Azure
 - IDE: IntelliJ
 - Library/Libraries: azure-monitor-opentelemetry-exporter - 1.0.0-beta.8; opentelemetry-bom - 1.27.0;
 
 **Information Checklist**
 Kindly make sure that you have added all the following information above and checkoff the required fields otherwise we will treat the issuer as an incomplete report
- [v] Query Added
- [v] Setup information Added

**Comment by joshfree** [comment]
Thank you for reporting this, @EvaSRGitHub.  @lmolkova @trask could you please take a look?

**Comment by trask** [comment]
hi @EvaSRGitHub! can you try using `BatchSpanProcessor` instead of `SimpleSpanProcessor`? I will look into updating our docs as well.

**Comment by EvaSRGitHub** [comment]
hi @trask,
i will try it and let you know a bit later, but we use SimpleSpanProcessor on purpose - we want real time traces.

**Comment by EvaSRGitHub** [comment]
HI @trask 
i switch to Batch processor and it seems this fix the warnings. 
Thank you all for your timely help.

**Comment by didieryemalin** [comment]
Hi @trask ,
So does this mean that SimpleSpanProcessor has a limit of 100 max concurrent requests while BatchSpanProcessor does not have that limit?

**Comment by trask** [comment]
SimpleSpanProcessor sends each span to the Azure Portal (ingestion service) in a separate HTTP request, which is very inefficient beyond simple test scenarios where you are only sending a small handful of spans in total.

The BatchSpanProcessor will send batches every 5 seconds (or sooner).

**Comment by didieryemalin** [comment]
Thanks a lot for the clarification @trask . Much appreciated.
