### ISSUE TITLE
NonAzureOpenAIKeyCredential can not request  v1/chat/completions

### ISSUE THREAD

**Issue by oneanime** [Azure/azure-sdk-for-java#36214]
**Query/Question**
when I use azure java sdk
below is my code

       OpenAIClient client = new OpenAIClientBuilder()
                .credential(new NonAzureOpenAIKeyCredential(token))
                .endpoint("/v1/chat/completions")
                .clientOptions(new HttpClientOptions().setProxyOptions(proxyOptions))
                .buildClient();

below is expection

Exception in thread "main" com.azure.core.exception.ResourceNotFoundException: Status code 404, "{
  "error": {
    "message": "This is a chat model and not supported in the v1/completions endpoint. Did you mean to use v1/chat/completions?",
    "type": "invalid_request_error",
    "param": "model",
    "code": null
  }
}

**Comment by mssfang** [comment]
@oneanime 
For OpenAI API request. You don't need to assign the endpoint. You can just remove it and use `.credential(new NonAzureOpenAIKeyCredential(token))` is sufficient.

**Comment by hanxlinsist** [comment]
It doesn't work for the [sample](https://github.com/Azure/azure-sdk-for-java/blob/main/sdk/openai/azure-ai-openai/src/samples/java/com/azure/ai/openai/auth/ClientCreationWithNonAzureOpenAIKeyCredentialSample.java#L28)

**Comment by mssfang** [comment]
> It doesn't work for the [sample](https://github.com/Azure/azure-sdk-for-java/blob/main/sdk/openai/azure-ai-openai/src/samples/java/com/azure/ai/openai/auth/ClientCreationWithNonAzureOpenAIKeyCredentialSample.java#L28)

Hi @hanxlinsist. What is the error message you get?
