### ISSUE TITLE
[Query] Java createAndInitializeObjectMapper can I override the default ObjectMapper?

### ISSUE THREAD

**Issue by CraftyFella** [Azure/azure-sdk-for-java#36246]
**Question**

I am using kotlin with the `CosmosAsyncClient` and as such many of the data classes I'm using will not deserialize. If I was to use the https://github.com/FasterXML/jackson-module-kotlin module then this wouldn't be an issue. So I'm wondering if there is a way to add additional configuration to the `ObjectMapper` used by the `CosmosAsyncClient`? So that in my case I can add the lines

`objectMapper.registerModule(new KotlinModule());`

***Why is this not a Bug or a feature Request?***
For all I know it might be possible to do this already, so I'll ask a question first then if the answer is NO it's not possible. then I'll submit a feature request with a PR.

**Setup**
 - OS: MacOs
 - IDE: IntelliJ
 - Library/Libraries:  com.azure:azure-cosmos:4.44.0
 
 **Information Checklist**
- [x] Query Added
- [x] Setup information Added

**Comment by kushagraThapar** [comment]
@CraftyFella - this is not possible at the moment, as we don't expose custom serialization to Cosmos DB Java SDK. This is in our backlog, but we don't have any timelines for it yet.
