### ISSUE TITLE
[BUG] RestError: [TokenExpired] Error validating token: 'S2S12086'

### ISSUE THREAD

**Issue by jorgebg90** [Azure/azure-sdk-for-java#36245]
Hello!

We are using Azure SDK for java through an application and suddenly yesterday (after six months of use without any problem) an error raised suddenly:

`Status code 401, \"{\"error\":{\"code\":\"Unauthorized\",\"message\":\"[TokenExpired] Error validating token: 'S2S12086'.\"}}`

There was not any special reason for that error but having a look over the error code we found similar errors (and fixes) for Azure SDK for JS and for Python

Issues

https://github.com/Azure/azure-sdk-for-js/issues/22722
https://github.com/Azure/azure-sdk-for-python/issues/11346

Fix: 

https://github.com/Azure/azure-sdk-for-js/pull/23232

The component that we're using uses azure bom 1.2.12
https://mvnrepository.com/artifact/com.azure/azure-sdk-bom/1.2.12

The question is about if there was a fix related with this issue for Azure SDK for java (in the latest version) or at least to know if it was already reported (I didn't find nothing related with that for Java)

Thanks in advance

**Comment by joshfree** [comment]
Thank you for filing this issue, @jorgebg90 - as well as linking the related JS and Python issues.  @billwert could you please take a look?

**Comment by billwert** [comment]
Hello @jorgebg90! Thank you for the report. Looking at the other issues you linked to and the current `azure-identity` code, I believe we will parse this value correctly. Are you still seeing an issue?

**Comment by jorgebg90** [comment]
Hi @billwert,
I had this issue with a component that uses azure-identity code from Java Azure SDK and researching a bit I found these related bugs. Since that day there were not any problem related with it but I though that it was interesting to have a look about it because it crashed (because if it happened once it could happens again).

Thanks in advance for your time

**Comment by billwert** [comment]
Awesome. I'm going to close this issue as I think it is likely to be resolved. If you ever see it again please let us know!
