### ISSUE TITLE
[BUG] Did not find the authorization API for Azure Confidential Ledger from AAD?

### ISSUE THREAD

**Issue by Jasun0925** [Azure/azure-sdk-for-java#36258]
**Query/Question**
As shown in the following figure, the authorization API for Azure Confidential Ledger was not found in Azure Active Directory. Please tell me the solution using AAD method.

<img width="1172" alt="image" src="https://github.com/Azure/azure-sdk-for-java/assets/20411806/5f94072d-7afe-424d-b41d-8dfc7a4eabfa">

**Comment by joshfree** [comment]
Hi @Jasun0925, this quickstart guide should help: https://learn.microsoft.com/en-us/azure/confidential-ledger/quickstart-portal.

Please let us know if you have specific questions about the SDK.
