### ISSUE TITLE
[BUG]: Evaluate `CosmosItemIdEncodingTest` regression

### ISSUE THREAD

**Issue by jeet1995** [Azure/azure-sdk-for-java#36265]
There are scenarios where an item is read with an id which `CosmosItemIdEncodingTest` expects a `HTTP 401` / `HTTP 400` but is getting a `HTTP 201` for from the routing gateway. Below are the scenarios:

- ID with percentage encoded whitespace.
- ID ending with whitespace.
- ID ending with whitespaces.
- ID with carriage return.
- ID with pound sign.
- ID with percentage encoded special character.
- ID with tab.

**Comment by FabianMeiswinkel** [comment]
Fixed in Gateway
