### ISSUE TITLE
[QUERY] Azure Servicebus: Send messages to the DLQ with Java libraries explicitly

### ISSUE THREAD

**Issue by ojtanner** [Azure/azure-sdk-for-java#36277]
Is it possible to send messages to the DLQ programmatically with the following Java libraries:
- **spring-cloud-azure-stream-binder-servicebus**
- **azure-messaging-servicebus**

I am currently trying to find out how I can enable redelivery of messages in general for transient errors on an application level, but directly send messages to the DLQ for any situation which produces an error that is not retriable, e.g. not deserializable or payload is invalid. In cases such as this, I would like to send the message to the dead-letter queue, since there is no reason to redeliver the message.

In the official documentation for Azure Servicebus DLQs ( https://learn.microsoft.com/en-us/azure/service-bus-messaging/service-bus-dead-letter-queues ) it is mentioned that applications should be able to send messages manually to the DLQ, yet this does not seem to be the case with the **Azure Stream Binder Servicebus** or the **Azure Messaging Servicebus SDK for Java**.

I am trying to create an application that behaves as described in the following scenarios:

**Happy path:**
1. Message is fetched via peek-lock
2. Message is processed successfully
3. Message is completed

**Transient error on application level:**
1. Message is fetched via peek-lock
2. Message is processed and a transient error happens
3. Message is abandoned and redelivered again, incrementing the redelivery count
4. Repeat steps 1-3 until it succeeds or maxDeliveryCount is reached

**Non-transient error on application level:**
1. Message is fetched via peek-lock
2. Message is processed and a non-transient error happens
3. Since there is no point in retrying, we send the message directly to the DLQ

So far i was able to create the setup for both the happy path and transient error. However, i am not able to recreate the behavior for the non-transient error.

In case that this is not possible ( which seems to be the case ), what is the expected way of dealing with situations when we want to retry transient errors on an application level ? Retry everything, including non-transient errors ? We are currently using this approach, but it seems wasteful to abandon and re-deliver erroneous messages which will never succeed anyway.

Thanks for any help you can offer

**Comment by joshfree** [comment]
@anuchandy could you assist @ojtanner with this question on dead letter queues?

**Comment by anuchandy** [comment]
@ojtanner - Are you looking for the dead-letter disposition API? there a couple of way to do it depending on the client type (sync, async, processor)

1. https://learn.microsoft.com/en-us/java/api/com.azure.messaging.servicebus.servicebusreceiverclient?view=azure-java-stable#com-azure-messaging-servicebus-servicebusreceiverclient-deadletter(com-azure-messaging-servicebus-servicebusreceivedmessage)
2. https://learn.microsoft.com/en-us/java/api/com.azure.messaging.servicebus.servicebusreceiverasyncclient?view=azure-java-stable#com-azure-messaging-servicebus-servicebusreceiverasyncclient-deadletter(com-azure-messaging-servicebus-servicebusreceivedmessage)
3. https://learn.microsoft.com/en-us/java/api/com.azure.messaging.servicebus.servicebusreceivedmessagecontext?view=azure-java-stable#com-azure-messaging-servicebus-servicebusreceivedmessagecontext-deadletter()

**Comment by ojtanner** [comment]
Thanks for the swift reply @anuchandy . I will try out the examples you provided.
I took a quick look and this functionality does not seem to be exposed to the Azure Spring Cloud Stream Binder for Servicebus. Are you able to confirm this?

**Comment by Netyyyy** [comment]
> @Netyyyy Muyao Feng (CSI Interfusion Inc) Vendor could you please confirm, if dead-letter API is exposed in Azure Spring Binder?

yes, is this [doc](https://learn.microsoft.com/en-us/azure/developer/java/spring-framework/spring-cloud-stream-support?tabs=SpringCloudAzure4x#handle-error-messages-1) helpful to you?

**Comment by ojtanner** [comment]
> > @Netyyyy Muyao Feng (CSI Interfusion Inc) Vendor could you please confirm, if dead-letter API is exposed in Azure Spring Binder?
> 
> yes, is this [doc](https://learn.microsoft.com/en-us/azure/developer/java/spring-framework/spring-cloud-stream-support?tabs=SpringCloudAzure4x#handle-error-messages-1) helpful to you?

@Netyyyy thanks for your answer. I'm afraid the documentation is somewhat confusing. I was already aware of it before opening this query, but it is not clear for me if we can explicitly dead-letter a message while in the binder error handler. The relevant part in the documentation states: 

> Binder error handler:
> 
> The default binder error handler handles the inbound binding. You use this handler to send failed messages to the dead-letter queue when spring.cloud.stream.servicebus.bindings.<binding-name>.consumer.requeue-rejected is enabled. Otherwise, the failed messages are abandoned. Except for configuring the binding-specific error channel, the binder error handler always takes effect regardless of whether there are other custom error handlers or channels.

Sadly, there is no example of how the dead-letter can be done via the binder error handler. I have experimented with the binder error handler previously, but did not get any useful results.

As of right now, we have set **requeue-rejected** to false in our application, so that failed messages are abandoned and redelivered in case of retriable errors on an application level.

The documentation leads me to believe we implicitly dead-letter messages by setting **requeue-rejected** to true, and this is done automatically by the default binder error handler.

I see problems with this:

1. This would disable the retry mechanism, as far as I understood the documentation, since messages are no longer abandoned and redelivered, but enqueued into the DLQ directly.
2. I would like to be able to tell the stream binder when abandon a message and when to send it to the DLQ. If i understood the documentation correctly, it is either:
2.1. Retry until maxDeliveryCount is exceeded and then DLQ
2.2. Do not retry and send message to DLQ, even if error is retriable

This might just be me misunderstanding the documentation and the library. If we can indeed explicitly dead-letter messages via the binder error handler, could you provide me with an example? Thank you for your time and effort so far

**Comment by Netyyyy** [comment]
Hi @ojtanner , could you help provide an minimal project?
I think `requeue-rejected=true` won't disable the retry mechanism, but once you set `requeue-rejected=false`, the failed message will be abandoned and not be redelivered.

**Comment by ojtanner** [comment]
> Hi @ojtanner , could you help provide an minimal project? I think `requeue-rejected=true` won't disable the retry mechanism, but once you set `requeue-rejected=false`, the failed message will be abandoned and not be redelivered.

Hi @Netyyyy , i can do that. I will try to get back to you as fast as possible, but it may take a day or two. Thank you

**Comment by anuchandy** [comment]
Hello @ojtanner, due to inactivity, I’m closing this. But if you have questions at later point or find a need to validate a minimal code with us (as discussed above), please tag us, we’ll reopen to continue our discussion. Thank you!
