### ISSUE TITLE
[QUERY] Get ACL from a container level for a given storage account?

### ISSUE THREAD

**Issue by arumugam-ramasamy** [Azure/azure-sdk-for-java#36297]
**Query/Question**
Get ACL from a container level for a given storage account - Have been unable to perform using SDK Java as mentioned in 
https://learn.microsoft.com/en-us/azure/storage/blobs/data-lake-storage-acl-java
***Why is this not a Bug or a feature Request?***
A clear explanation of why is this not a bug or a feature request? 
This is not a feature request as we are merely requesting to perform Get ACL for a given container / storage account  as given in the above link using AAD not via Shared Accees Key 

**Setup (please complete the following information if applicable):**
 - OS: [e.g. iOS]. Linux
 - IDE: [e.g. IntelliJ] Intellij
 - Library/Libraries: [e.g. com.azure:azure-core:1.16.0 (groupId:artifactId:version)]
  <dependency>
            <groupId>com.azure</groupId>
            <artifactId>azure-core</artifactId>
            <version>1.41.0</version> 
        </dependency>
        <dependency>
            <groupId>com.azure</groupId>
            <artifactId>azure-core-http-netty</artifactId>
            <version>1.13.5</version> 
        </dependency>
        <dependency>
            <groupId>com.azure</groupId>
            <artifactId>azure-identity</artifactId>
            <version>1.9.2</version>
        </dependency>
     <dependency>
            <groupId>com.azure</groupId>
            <artifactId>azure-storage-blob</artifactId>
            <version>12.23.0</version>
        </dependency>
        <dependency>
            <groupId>com.azure</groupId>
            <artifactId>azure-storage-file-datalake</artifactId>
            <version>12.16.0</version>
        </dependency>
 **Information Checklist**
 Kindly make sure that you have added all the following information above and checkoff the required fields otherwise we will treat the issuer as an incomplete report
- [ ] Query Added
- [ ] Setup information Added

**Comment by joshfree** [comment]
Hi @arumugam-ramasamy, thank you for reaching out to us via this github issue.  Someone from the storage team will follow up shortly!

**Comment by ibrahimrabab** [comment]
Hi @arumugam-ramasamy 
Are you trying to get ACL from a container level while authenticating from AAD for Shared Access Key? Can you provide a code snippet of what you have tried so far and what error you are seeing?
