### ISSUE TITLE
[BUG] Retry count showing 0 in diagnostic log even though the responseStatisticsList shows 1 retry 

### ISSUE THREAD

**Issue by JJ-WM** [Azure/azure-sdk-for-java#36312]
**Describe the bug**
Cosmos diagnostic lots shows retryCount 0 in the retry context even though the responseStatisticsList shows 1 retry.

***Exception or Stack Trace***
Add the exception log and stack trace if available

**To Reproduce**
For a read operation, block connection to one replica, request routing to this replica would get ConnectTimeoutException and retry on another replica.  

**Expected behavior**
Retry count should be 1 in this case.

**Screenshots**

**Setup (please complete the following information):**
Version 4.45.1

**Information Checklist**
Kindly make sure that you have added all the following information above and checkoff the required fields otherwise we will treat the issuer as an incomplete report
- [ ] Bug Description Added
- [ ] Repro Steps Added
- [ ] Setup information Added

**Comment by kushagraThapar** [comment]
@JJ-WM - is this still an issue? If not, can we please close it?
