### ISSUE TITLE
[QUERY] README missign connection string way to connect to storage

### ISSUE THREAD

**Issue by Rajesh-Narayanappa87** [Azure/azure-sdk-for-java#36318]
**Query/Question**
Was going through readme, In my company sas token generation is blocked, I was looking for a way to connect using connectionString. But I could not find it. I was looking in JAVA way to connect to azure.

***Why is this not a Bug or a feature Request?***
It is a README document update.

**Setup (please complete the following information if applicable):**
 - Library/Libraries: [e.g. com.azure:azure-storage-blob:12.23.0]
 
 **Information Checklist**
 Kindly make sure that you have added all the following information above and checkoff the required fields otherwise we will treat the issuer as an incomplete report
- [X] Query Added
- [X] Setup information Added

**Comment by Rajesh-Narayanappa87** [comment]
Documentation link: https://github.com/Azure/azure-sdk-for-java/tree/main/sdk/storage/azure-storage-blob#shared-key-credential

I guess below section needs to be added.

```
 BlobServiceClient blobServiceClient = new BlobServiceClientBuilder().connectionString(<connectionString>)
                .buildClient();
```

**Comment by joshfree** [comment]
@jaschrep-msft could you please assist @Rajesh-Narayanappa87 with their question?

**Comment by jaschrep-msft** [comment]
Hi @Rajesh-Narayanappa87

It's not quite clear to me what you're looking for. Are you asking for code samples in the readme for connection strings?

Also, I think I've been mistagged. This product is currently out of scope for me. @ibrahimrabab can follow up on this.
