### ISSUE TITLE
[BUG] SecurityException when building a native image with spring native and graalvm

### ISSUE THREAD

**Issue by bitbaggi** [Azure/azure-sdk-for-java#36320]
When building a native image with spring native and graalvm, multiple fatal errors occured.

The main error is: 
`Fatal error: java.lang.SecurityException: class "com.azure.spring.cloud.autoconfigure.implementation.compatibility.AzureCompatibilityVerifierAutoConfiguration"'s signer information does not match signer information of other classes in the same package`

But the class which signer information is not correct is cycling between:

- com.azure.spring.cloud.autoconfigure.implementation.compatibility.AzureCompatibilityVerifierAutoConfiguration
- com.azure.spring.cloud.autoconfigure.implementation.messaging.AzureMessagingListenerAutoConfiguration$ServiceBusConfiguration$$SpringCGLIB$$0

**Setup:**
 - OS: MacBook Pro
 - IDE: IntelliJ
 - Library/Libraries: com.azure.spring:spring-cloud-azure-stream-binder-servicebus:5.4.0
 - Java version: 17
 - Frameworks: Spring Boot

**Comment by joshfree** [comment]
Thanks for reaching out to us via this github issue, @bitbaggi - someone from the Spring team will follow up with you shortly.

/cc @srnagar as fyi

**Comment by Netyyyy** [comment]
Hi @bitbaggi .Thank you for reporting this issue. Could you help provide a minimal project.
And We appreciate your input and will review this matter as soon as possible.
Please feel free to provide any additional information or context that you think may be helpful. We'll keep you updated on the progress of our review.
Thank you for your contribution to improving our project.

**Comment by moarychan** [comment]
Hi @bitbaggi , thanks for using Spring Cloud Azure libs!

It's a known issue, please find workarounds from https://github.com/Azure/azure-sdk-for-java/issues/30320#issuecomment-1344445807 , I am going to close this one now.
