### ISSUE TITLE
[BUG] Cognitive Services Data-plane "RecognizeText" method unusable

### ISSUE THREAD

**Issue by lawrencegripper** [Azure/azure-sdk-for-java#3636]
**Describe the bug**
Currently the following endpoint is unusable from the SDK as it doesn't return the required data. 

The `operation-location` header response is required to get the details of the image analysis, this is stated in the methods comment but the method returns `void` so I'm unable to retrieve the field.

```
    /**
     * Recognize Text operation. When you use the Recognize Text interface, the response contains a field
      *  called 'Operation-Location'. The 'Operation-Location' field contains the URL that you must use for
      *  your Get Recognize Text Operation Result operation.
     *
     * @param mode Type of text to recognize. Possible values include: 'Handwritten', 'Printed'.
     * @param url Publicly reachable URL of an image.
     * @throws IllegalArgumentException thrown if parameters fail the validation
     * @throws ComputerVisionErrorException thrown if the request is rejected by server
     * @throws RuntimeException all other wrapped checked exceptions if the request fails to be sent
     */
void recognizeText(String url, TextRecognitionMode mode);
```

https://github.com/Azure/azure-sdk-for-java/blob/master/cognitiveservices/data-plane/vision/computervision/src/main/java/com/microsoft/azure/cognitiveservices/vision/computervision/ComputerVision.java#L798

***Exception or Stack Trace***
NA

**To Reproduce**
NA

***Code Snippet***
NA

**Expected behavior**
The method should return a string with the contents of the `operation-location` header to be passed to this method `GetTextOperationResult` method 

```java
        ComputerVisionClient client = ComputerVisionManager.authenticate("apiKey").withEndpoint("endpoint");
        String operationId = client.computerVision().recognizeTextAsync(inObj.url, TextRecognitionMode.PRINTED).toCompletable().wait();
        TextOperationResult result = client.computerVision().getTextOperationResult(operationId);
```

**Comment by lawrencegripper** [comment]
So I found a convoluted way to work around this issue as follows. 

It would be great to get a fix into the SDK so this workaround isn't needed. Is the SDK auto-gen'd or can I submit a PR?

```java
ComputerVisionClient client = ComputerVisionManager.authenticate(System.getenv("ComputerVisionKey"))
                .withEndpoint(uriBase);

        ServiceResponseWithHeaders<Void, RecognizeTextHeaders> response = ((ComputerVisionImpl) client.computerVision())
                .recognizeTextWithServiceResponseAsync(inObj.url, TextRecognitionMode.PRINTED).toBlocking().first();

        context.getLogger().info("Result url" + response.headers().operationLocation());

        // We get a full URL back and just want the id off the end. 
        //https://uksouth.api.cognitive.microsoft.com/vision/v2.0/textOperations/8428143d-0000-4f7f-b37b-fd8aa98b00000
        String operationId = response.headers().operationLocation().replace(uriBase + "/vision/v2.0/textOperations/", "");

        TextOperationResult result = null;
        while (result == null || result.status() != TextOperationStatusCodes.SUCCEEDED) {
            TimeUnit.SECONDS.sleep(1);

            try {
                result = client.computerVision().getTextOperationResult(operationId);
            } catch (Exception e) {
                context.getLogger().info("Failed getting response " + e.toString());

            }

            context.getLogger().info("Results status" + result.status().toString());
        }
```

**Comment by lawrencegripper** [comment]
Hi, 

Quick nudge around the auto-gen question. Is this automatically generated? If not can I submit a PR to resolve if so is their a guide to fixing the autogen process so I can take a crack at that?

**Comment by lawrencegripper** [comment]
Wanted to check in on this one again? Can you let me know if this is something I can PR a fix for? Just need a bit of guidance and I'm happy to pick this one up.

**Comment by agowdamsft** [comment]
@selvasingh ping!

**Comment by joshfree** [comment]
@moderakh @christopheranderson @kushagraThapar can you please follow up on this very old and unanswered issue?  @lawrencegripper sorry for the delay, the right folks from the Cosmos team are now tagged directly on this issue.

**Comment by christopheranderson** [comment]
@joshfree - this isn't a Cosmos issue, it's cognitive services. Looks like @milismsft owned this, but he left your team, so it likely needs an owner from your group unless some other group has taken ownership over this code base.

https://github.com/Azure/azure-sdk-for-java/blame/2fdc3c4b8f7ca5234e084331e550a3ae18303ebc/sdk/cognitiveservices/ms-azure-cs-computervision/src/main/java/com/microsoft/azure/cognitiveservices/vision/computervision/ComputerVision.java#L798

**Comment by milismsft** [comment]
@joshfree the cognitive services data plane SDKs were autogenerated from Swagger using the Java auto-gen tools.
@lawrencegripper you should be able to submit a PR with the fix but someone from the Azure Java SDK central team should follow up on the Swagger related issue and why the autogenerated method does not capture the intent of the API.

**Comment by joshfree** [comment]
Hey @christopheranderson thanks for the follow up.  Yes, sorry I think I had one too many browser tabs open and tagged Cosmos instead of Cognitive by accident last night.
