### ISSUE TITLE
[FEATURE REQ] SDK Support for OpenAI's Completions Extensions

### ISSUE THREAD

**Issue by mkemmerz** [Azure/azure-sdk-for-java#36360]
**Describe the solution you'd like**
SDK Support for OpenAI Completions Extensions: https://learn.microsoft.com/en-us/azure/ai-services/openai/reference#completions-extensions

Basically everything that the link describes. Support for `dataSources`:
```
    "dataSources": [
        {
            "type": "AzureCognitiveSearch",
            "parameters": {
                "endpoint": "'YOUR_AZURE_COGNITIVE_SEARCH_ENDPOINT'",
                "key": "'YOUR_AZURE_COGNITIVE_SEARCH_KEY'",
                "indexName": "'YOUR_AZURE_COGNITIVE_SEARCH_INDEX_NAME'"
            }
        }
    ]
```

so that we can use additional `AzureCognitiveSearch ` with the Azure OpenAI and this SDK.

I guess this requires to extend https://github.com/Azure/azure-sdk-for-java/blob/main/sdk/openai/azure-ai-openai/src/main/java/com/azure/ai/openai/models/CompletionsOptions.java.

**Comment by mssfang** [comment]
We are planning to support this feature in the next release version which will be around the end of this month at the earliest.

**Comment by mkemmerz** [comment]
> We are planning to support this feature in the next release version which will be around the end of this month at the earliest.

Thanks a lot for the reply. Looking forward to it! 💯

**Comment by mssfang** [comment]
@mkemmerz 
We just released https://repo1.maven.org/maven2/com/azure/azure-ai-openai/1.0.0-beta.4/
See the [sample](https://github.com/Azure/azure-sdk-for-java/blob/main/sdk/openai/azure-ai-openai/src/samples/java/com/azure/ai/openai/ChatCompletionsWithYourData.java) for how to use Bring-Your-Own-Data(BYOD).

**Comment by mkemmerz** [comment]
@mssfang Thank you for letting me know! We will try it out :)

**Comment by mkemmerz** [comment]
Hi @mssfang, the feature works great with the sample! Is this feature already supported for the streaming API as well?
