### ISSUE TITLE
[BUG] : Azure service bus with spring cloud stream - connection definitly lost after multiple reconnection retries

### ISSUE THREAD

**Issue by LaurineLeNet** [Azure/azure-sdk-for-java#36362]
Hi, 

**Context**
We have created a service that use Spring cloud stream to receive messages with azure service bus. It is a simple Function that publish a message on a rabbit queue each time it receive a message on a Service bus subscription.

When no messages are published on Service Bus for a while, the service stop listening to new ones. We need to restart the service in order to make it consumes messages again

***Exception or Stack Trace***
```console
11/08/2023 09:01:37.717
{"az.sdk.message":"onConnectionShutdown. Shutting down.","connectionId":"MF_0922f8_1691666903887","isTransient":false,"isInitiatedByClient":false,"shutdownMessage":"Finished processing pending tasks.","namespace":"sbniaspaeuwgizeh01.servicebus.windows.net"}
11/08/2023 09:01:37.716
{"az.sdk.message":"onConnectionShutdown. Shutting down.","connectionId":"MF_0922f8_1691666903887","isTransient":false,"isInitiatedByClient":false,"shutdownMessage":"connectionId[MF_0922f8_1691666903887] Reactor selectable is disposed.","namespace":"sbniaspaeuwgizeh01.servicebus.windows.net"}
11/08/2023 09:01:37.715
{"az.sdk.message":"Reactor selectable is being disposed.","connectionId":"MF_0922f8_1691666903887"}
11/08/2023 09:01:37.715
{"az.sdk.message":"Processing all pending tasks and closing old reactor.","connectionId":"MF_0922f8_1691666903887"}
11/08/2023 09:01:36.090
{"az.sdk.message":"Reactor selectable is being disposed.","connectionId":"MF_a1bf13_1691644631033"}
11/08/2023 09:01:36.090
{"az.sdk.message":"onConnectionShutdown. Shutting down.","connectionId":"MF_a1bf13_1691644631033","isTransient":false,"isInitiatedByClient":false,"shutdownMessage":"connectionId[MF_a1bf13_1691644631033] Reactor selectable is disposed.","namespace":"sbniaspaeuwgizeh01.servicebus.windows.net"}
11/08/2023 09:01:36.092
{"az.sdk.message":"onConnectionShutdown. Shutting down.","connectionId":"MF_a1bf13_1691644631033","isTransient":false,"isInitiatedByClient":false,"shutdownMessage":"Finished processing pending tasks.","namespace":"sbniaspaeuwgizeh01.servicebus.windows.net"}
11/08/2023 09:01:36.089
{"az.sdk.message":"Processing all pending tasks and closing old reactor.","connectionId":"MF_a1bf13_1691644631033"}
11/08/2023 09:01:33.710
{"az.sdk.message":"Channel is disposed.","connectionId":"MF_0922f8_1691666903887","entityPath":"$cbs"}
11/08/2023 09:01:33.712
{"az.sdk.message":"Closing executor.","connectionId":"MF_0922f8_1691666903887"}
11/08/2023 09:01:33.709
{"az.sdk.message":"Upstream connection publisher was completed. Terminating processor.","connectionId":"MF_0922f8_1691666903887","entityPath":"$cbs"}
11/08/2023 09:01:33.709
{"az.sdk.message":"Receiver link was never active. Closing endpoint states","connectionId":"MF_0922f8_1691666903887","entityPath":"$cbs","linkName":"cbs"}
11/08/2023 09:01:33.708
{"az.sdk.message":"Next AMQP channel received.","connectionId":"MF_0922f8_1691666903887","entityPath":"$cbs","subscriberId":"un_b2bad2_1691744489202"}
11/08/2023 09:01:33.707
{"az.sdk.message":"Sender link was never active. Closing endpoint states.","connectionId":"MF_0922f8_1691666903887","linkName":"cbs","entityPath":"$cbs"}
11/08/2023 09:01:33.707
{"az.sdk.message":"Emitting new response channel.","connectionId":"MF_0922f8_1691666903887","entityPath":"$cbs","linkName":"cbs"}
11/08/2023 09:01:33.707
{"az.sdk.message":"Setting next AMQP channel.","connectionId":"MF_0922f8_1691666903887","entityPath":"$cbs"}
11/08/2023 09:01:33.705
{"az.sdk.message":"Connection not requested, yet. Requesting one.","connectionId":"MF_0922f8_1691666903887","entityPath":"$cbs"}
11/08/2023 09:01:33.705
{"az.sdk.message":"Requesting from upstream.","connectionId":"MF_0922f8_1691666903887","entityPath":"$cbs","tryCount":0}
11/08/2023 09:01:32.080
{"az.sdk.message":"Next AMQP channel received.","connectionId":"MF_a1bf13_1691644631033","entityPath":"$cbs","subscriberId":"un_4e7546_1691744487572"}
11/08/2023 09:01:32.080
{"az.sdk.message":"Upstream connection publisher was completed. Terminating processor.","connectionId":"MF_a1bf13_1691644631033","entityPath":"$cbs"}
11/08/2023 09:01:32.084
{"az.sdk.message":"Closing executor.","connectionId":"MF_a1bf13_1691644631033"}
11/08/2023 09:01:32.082
{"az.sdk.message":"Channel is disposed.","connectionId":"MF_a1bf13_1691644631033","entityPath":"$cbs"}
11/08/2023 09:01:32.081
{"az.sdk.message":"Receiver link was never active. Closing endpoint states","connectionId":"MF_a1bf13_1691644631033","entityPath":"$cbs","linkName":"cbs"}
11/08/2023 09:01:32.079
{"az.sdk.message":"Setting next AMQP channel.","connectionId":"MF_a1bf13_1691644631033","entityPath":"$cbs"}
11/08/2023 09:01:32.079
{"az.sdk.message":"Emitting new response channel.","connectionId":"MF_a1bf13_1691644631033","entityPath":"$cbs","linkName":"cbs"}
11/08/2023 09:01:32.079
{"az.sdk.message":"Sender link was never active. Closing endpoint states.","connectionId":"MF_a1bf13_1691644631033","linkName":"cbs","entityPath":"$cbs"}
11/08/2023 09:01:32.077
{"az.sdk.message":"Requesting from upstream.","connectionId":"MF_a1bf13_1691644631033","entityPath":"$cbs","tryCount":0}
11/08/2023 09:01:32.077
{"az.sdk.message":"Connection not requested, yet. Requesting one.","connectionId":"MF_a1bf13_1691644631033","entityPath":"$cbs"}
11/08/2023 09:01:29.205
{"az.sdk.message":"onSessionFinal.","connectionId":"MF_0922f8_1691666903887","errorCondition":null,"errorDescription":null,"sessionName":"cbs-session"}
11/08/2023 09:01:29.205
{"az.sdk.message":"onConnectionFinal","connectionId":"MF_0922f8_1691666903887","errorCondition":null,"errorDescription":null,"hostName":"sbniaspaeuwgizeh01.servicebus.windows.net"}
11/08/2023 09:01:29.204
{"az.sdk.message":"onLinkFinal","connectionId":"MF_0922f8_1691666903887","linkName":"cbs:sender","entityPath":"$cbs"}
11/08/2023 09:01:29.204
{"az.sdk.message":"onLinkFinal","connectionId":"MF_0922f8_1691666903887","linkName":"cbs:receiver","entityPath":"$cbs"}
11/08/2023 09:01:29.204
{"az.sdk.message":"onSessionFinal.","connectionId":"MF_0922f8_1691666903887","errorCondition":null,"errorDescription":null,"sessionName":"ev-ged/subscriptions/EVP"}
11/08/2023 09:01:29.203
{"az.sdk.message":"Setting next AMQP channel.","entityPath":"N/A"}
11/08/2023 09:01:29.203
{"az.sdk.message":"Connection not requested, yet. Requesting one.","entityPath":"N/A"}
11/08/2023 09:01:29.203
{"az.sdk.message":"Channel is closed. Requesting upstream.","entityPath":"N/A"}
11/08/2023 09:01:29.199
{"az.sdk.message":"Disposing of ReactorConnection.","connectionId":"MF_0922f8_1691666903887","isTransient":false,"isInitiatedByClient":false,"shutdownMessage":"Connection handler closed."}
11/08/2023 09:01:29.198
{"az.sdk.message":"onConnectionLocalClose","connectionId":"MF_0922f8_1691666903887","errorCondition":null,"errorDescription":null,"hostName":"sbniaspaeuwgizeh01.servicebus.windows.net"}
11/08/2023 09:01:29.198
{"az.sdk.message":"onConnectionUnbound","connectionId":"MF_0922f8_1691666903887","hostName":"sbniaspaeuwgizeh01.servicebus.windows.net","state":"CLOSED","remoteState":"CLOSED"}
11/08/2023 09:01:29.198
{"az.sdk.message":"onTransportClosed","connectionId":"MF_0922f8_1691666903887","hostName":"sbniaspaeuwgizeh01.servicebus.windows.net"}
11/08/2023 09:01:29.197
{"az.sdk.message":"onConnectionRemoteClose","connectionId":"MF_0922f8_1691666903887","errorCondition":"amqp:connection:forced","errorDescription":"The connection was inactive for more than the allowed 300000 milliseconds and is closed by container 'LinkTracker'. TrackingId:5dad3b7d55684bfc8fb95174e4a7f98b_G10, SystemTracker:gateway7, Timestamp:2023-08-11T09:01:29","hostName":"sbniaspaeuwgizeh01.servicebus.windows.net"}
11/08/2023 09:01:29.197
{"az.sdk.message":"onSessionRemoteClose","connectionId":"MF_0922f8_1691666903887","errorCondition":null,"errorDescription":null,"sessionName":"cbs-session"}
11/08/2023 09:01:29.197
{"az.sdk.message":"onTransportClosed","connectionId":"MF_0922f8_1691666903887","errorCondition":"n/a","errorDescription":"n/a","hostName":"sbniaspaeuwgizeh01.servicebus.windows.net"}
11/08/2023 09:01:29.197
{"az.sdk.message":"onSessionRemoteClose closing a local session.","connectionId":"MF_0922f8_1691666903887","errorCondition":null,"errorDescription":null,"sessionName":"cbs-session"}
11/08/2023 09:01:29.196
{"az.sdk.message":"onLinkRemoteClose","connectionId":"MF_0922f8_1691666903887","errorCondition":"amqp:connection:forced","errorDescription":"The connection was inactive for more than the allowed 300000 milliseconds and is closed by container 'LinkTracker'. TrackingId:5dad3b7d55684bfc8fb95174e4a7f98b_G10, SystemTracker:gateway7, Timestamp:2023-08-11T09:01:29","linkName":"cbs:receiver","entityPath":"$cbs"}
11/08/2023 09:01:29.196
{"az.sdk.message":"Local link state is not closed.","connectionId":"MF_0922f8_1691666903887","linkName":"cbs:receiver","entityPath":"$cbs","state":"ACTIVE"}
11/08/2023 09:01:29.191
{"az.sdk.message":"Transient error occurred. Retrying.","exception":"The connection was inactive for more than the allowed 300000 milliseconds and is closed by container 'LinkTracker'. TrackingId:5dad3b7d55684bfc8fb95174e4a7f98b_G10, SystemTracker:gateway7, Timestamp:2023-08-11T09:01:29, errorContext[NAMESPACE: sbniaspaeuwgizeh01.servicebus.windows.net. ERROR CONTEXT: N/A, PATH: $cbs, REFERENCE_ID: cbs:sender, LINK_CREDIT: 46]","connectionId":"MF_0922f8_1691666903887","entityPath":"$cbs","tryCount":0,"interval_ms":4511}
11/08/2023 09:01:29.188
{"az.sdk.message":"Error in SendLinkHandler. Disposing unconfirmed sends.","exception":"The connection was inactive for more than the allowed 300000 milliseconds and is closed by container 'LinkTracker'. TrackingId:5dad3b7d55684bfc8fb95174e4a7f98b_G10, SystemTracker:gateway7, Timestamp:2023-08-11T09:01:29, errorContext[NAMESPACE: sbniaspaeuwgizeh01.servicebus.windows.net. ERROR CONTEXT: N/A, PATH: $cbs, REFERENCE_ID: cbs:sender, LINK_CREDIT: 46]","connectionId":"MF_0922f8_1691666903887","linkName":"cbs"}
11/08/2023 09:01:29.188
{"az.sdk.message":"Local link state is not closed.","connectionId":"MF_0922f8_1691666903887","linkName":"cbs:sender","entityPath":"$cbs","state":"ACTIVE"}
11/08/2023 09:01:29.188
{"az.sdk.message":"onLinkRemoteClose","connectionId":"MF_0922f8_1691666903887","errorCondition":"amqp:connection:forced","errorDescription":"The connection was inactive for more than the allowed 300000 milliseconds and is closed by container 'LinkTracker'. TrackingId:5dad3b7d55684bfc8fb95174e4a7f98b_G10, SystemTracker:gateway7, Timestamp:2023-08-11T09:01:29","linkName":"cbs:sender","entityPath":"$cbs"}
```

**Expected behavior**
We can see that it reconnect successfully when the connection was inactive but then it stopped.

**Setup**
 - OS: Linux
 - IDE: IntelliJ
 - Java version: 11
 - Spring 2.XX
 - dependency : 
```xml
 <dependency>
        <groupId>com.azure.spring</groupId>
        <artifactId>spring-cloud-azure-dependencies</artifactId>
        <version>4.5.0</version>
        <type>pom</type>
        <scope>import</scope>
</dependency>
```

**Comment by LaurineLeNet** [comment]
Hi,
The new version is known to solve the problem ?
I have updated the version and I am trying to reproduce :) 
Thank you very much

**Comment by LaurineLeNet** [comment]
Hi, the upgrade seems to have solve the issue.
I have an other problem though. 
We are receiving every minutes a log info of connection closing and new connection generated

Logs : 

19/09/2023 13:48:03.589
{"az.sdk.message":"Creating a new receiver link.","connectionId":"MF_9f8ea3_1695100736343","sessionName":"ev-ged/subscriptions/EVP","linkName":"session-_62f078_1695131283555"}
19/09/2023 13:48:03.588
{"az.sdk.message":"Scheduling refresh token task.","scopes":"amqp://sbniaspaeuwgizeh01.servicebus.windows.net/ev-ged/subscriptions/EVP"}
19/09/2023 13:48:03.555
{"az.sdk.message":"onLinkFinal","connectionId":"MF_9f8ea3_1695100736343","linkName":"session-_461f49_1695131224552","entityPath":"ev-ged/subscriptions/EVP"}
19/09/2023 13:48:03.555
{"az.sdk.message":"Error occurred while getting unnamed session.","exception":"The operation did not complete within the allotted timeout of 00:00:59. The time allotted to this operation may have been a portion of a longer timeout. For more information on exception types and proper exception handling, please refer to https://aka.ms/ServiceBusExceptions . TrackingId:0cd404c1-93c7-4e4c-a0e0-f3ff29cbebf1_B36, SystemTracker:G21:659169081:session-_461f49_1695131224552, Timestamp:2023-09-19T13:48:03 TrackingId:b6c9348c34d24abba0329650de1c447f_G21, SystemTracker:gateway7, Timestamp:2023-09-19T13:48:03, errorContext[NAMESPACE: sbniaspaeuwgizeh01.servicebus.windows.net. ERROR CONTEXT: N/A, PATH: ev-ged/subscriptions/EVP, REFERENCE_ID: session-_461f49_1695131224552, LINK_CREDIT: 0]","entityPath":"ev-ged/subscriptions/EVP","attempt":516}
19/09/2023 13:48:03.555
{"az.sdk.message":"Receiver link was never active. Closing endpoint states","connectionId":"MF_9f8ea3_1695100736343","entityPath":"ev-ged/subscriptions/EVP","linkName":"session-_461f49_1695131224552"}
19/09/2023 13:48:03.554
{"az.sdk.message":"onLinkRemoteOpen","connectionId":"MF_9f8ea3_1695100736343","entityPath":"ev-ged/subscriptions/EVP","linkName":"session-_461f49_1695131224552","action":"waitingForError"}
19/09/2023 13:48:03.554
{"az.sdk.message":"Local link state is not closed.","connectionId":"MF_9f8ea3_1695100736343","linkName":"session-_461f49_1695131224552","entityPath":"ev-ged/subscriptions/EVP","state":"ACTIVE"}
19/09/2023 13:48:03.554
{"az.sdk.message":"Freeing resources due to error.","connectionId":"MF_9f8ea3_1695100736343","entityPath":"ev-ged/subscriptions/EVP","linkName":"session-_461f49_1695131224552"}
19/09/2023 13:48:03.554
{"az.sdk.message":"onLinkRemoteClose","connectionId":"MF_9f8ea3_1695100736343","errorCondition":"com.microsoft:timeout","errorDescription":"The operation did not complete within the allotted timeout of 00:00:59. The time allotted to this operation may have been a portion of a longer timeout. For more information on exception types and proper exception handling, please refer to https://aka.ms/ServiceBusExceptions . TrackingId:0cd404c1-93c7-4e4c-a0e0-f3ff29cbebf1_B36, SystemTracker:G21:659169081:session-_461f49_1695131224552, Timestamp:2023-09-19T13:48:03 TrackingId:b6c9348c34d24abba0329650de1c447f_G21, SystemTracker:gateway7, Timestamp:2023-09-19T13:48:03","linkName":"session-_461f49_1695131224552","entityPath":"ev-ged/subscriptions/EVP"}
19/09/2023 13:47:41.599
{"az.sdk.message":"Creating a new receiver link.","connectionId":"MF_f1dbab_1695127719611","sessionName":"ev-ged/subscriptions/EVP","linkName":"session-_5ac1cb_1695131261566"}
19/09/2023 13:47:41.598
{"az.sdk.message":"Scheduling refresh token task.","scopes":"amqp://sbniaspaeuwgizeh01.servicebus.windows.net/ev-ged/subscriptions/EVP"}
19/09/2023 13:47:41.566
{"az.sdk.message":"Receiver link was never active. Closing endpoint states","connectionId":"MF_f1dbab_1695127719611","entityPath":"ev-ged/subscriptions/EVP","linkName":"session-_ccc84c_1695131202535"}
19/09/2023 13:47:41.566
{"az.sdk.message":"onLinkFinal","connectionId":"MF_f1dbab_1695127719611","linkName":"session-_ccc84c_1695131202535","entityPath":"ev-ged/subscriptions/EVP"}
19/09/2023 13:47:41.565
{"az.sdk.message":"Error occurred while getting unnamed session.","exception":"The operation did not complete within the allotted timeout of 00:00:59. The time allotted to this operation may have been a portion of a longer timeout. For more information on exception types and proper exception handling, please refer to https://aka.ms/ServiceBusExceptions . TrackingId:0cd404c1-93c7-4e4c-a0e0-f3ff29cbebf1_B36, SystemTracker:G56:606069046:session-_ccc84c_1695131202535, Timestamp:2023-09-19T13:47:41 TrackingId:8ccd91086b0f4bcc95f61c22a6611347_G56, SystemTracker:gateway7, Timestamp:2023-09-19T13:47:41, errorContext[NAMESPACE: sbniaspaeuwgizeh01.servicebus.windows.net. ERROR CONTEXT: N/A, PATH: ev-ged/subscriptions/EVP, REFERENCE_ID: session-_ccc84c_1695131202535, LINK_CREDIT: 0]","entityPath":"ev-ged/subscriptions/EVP","attempt":59}
19/09/2023 13:47:41.565
{"az.sdk.message":"Freeing resources due to error.","connectionId":"MF_f1dbab_1695127719611","entityPath":"ev-ged/subscriptions/EVP","linkName":"session-_ccc84c_1695131202535"}
19/09/2023 13:47:04.552
{"az.sdk.message":"Local link state is not closed.","connectionId":"MF_9f8ea3_1695100736343","linkName":"session-_a4c3bc_1695131165599","entityPath":"ev-ged/subscriptions/EVP","state":"ACTIVE"}

**Comment by saragluna** [comment]
Hi @anuchandy and @billwert, could you take a look at this?

**Comment by anuchandy** [comment]
Hello @LaurineLeNet, these sequences of logs are normal, this indicates that the client is attempting to acquire the configured (max-concurrent-sessions) number of sessions, but Broker is responding that it waited for 60 seconds for a new session but couldn’t find any.  The Client will retry in this case, if Broker finds a session within 60 it will respond by opening the session else it will tell the Client the same thing that there is no session, needing client to retry.

**Comment by anuchandy** [comment]
Closing the issue, queries are answered and with the new version connection is stable.
