### ISSUE TITLE
Issues Loading azure-cosmos-spark_3-4_2-12 in Databricks Workbook

### ISSUE THREAD

**Issue by v-arpoup** [Azure/azure-sdk-for-java#36399]
I was able to resolve the issue by following those steps :
https://github.com/Azure/azure-sdk-for-java/blob/main/sdk/cosmos/azure-cosmos-spark_3_2-12/docs/quick-start.md

Hello Team/Community,

I'm currently experiencing an issue with Azure Databricks, where I'm trying to load the azure-cosmos-spark_3-4_2-12 library into my workbook. Despite following the recommended installation and setup procedures, I keep running into loading problems.

Environment Details:

Databricks Runtime Version: 3.2 (includes Apache Spark 3.4.0, Scala 2.12)
Cluster Configuration: Standard_DS3_v2 / single node / 14 GB Memory, 4 Cores / Photon enabled
Cosmos DB SDK Version: azure-cosmos-spark_3-4_2-12
Steps to Reproduce:

Navigate to the Libraries tab in my Databricks cluster.
Install successfully the azure-cosmos-spark_3-4_2-12 via Maven.
Restart the cluster
Upon installation, navigate back to the notebook.
Try to use the library in the workbook.
Observed Behavior: The library is not showing in the libraries panel and when I run the following command  : 
df.write.format("com.microsoft.azure.cosmosdb.spark").options(**cosmos_conf).save()
I'm getting the following error : 
org.apache.spark.SparkClassNotFoundException: [DATA_SOURCE_NOT_FOUND] Failed to find data source: com.microsoft.azure.cosmosdb.spark. Please find packages at `https://spark.apache.org/third-party-projects.html`.

Expected Behavior: I expected the library to be loaded successfully and be able to use its functionalities in my workbook.

Attempts Made to Resolve the Issue:

Restarted the cluster.
Checked for any dependency conflicts.
Verified the Maven coordinates.
I would appreciate any guidance or insights on this matter. Has anyone else faced a similar issue or knows of any potential fixes or workarounds?

Thank you for your time and assistance!

**Comment by FabianMeiswinkel** [comment]
The name of the data source you used is incorrect. The correct value is "cosmos.oltp" - see the following links for some samples for the Cosmos DB Spark connector under Spark 3.*

https://github.com/Azure/azure-sdk-for-java/blob/main/sdk/cosmos/azure-cosmos-spark_3_2-12/docs/quick-start.md#ingesting-data

https://github.com/Azure/azure-sdk-for-java/blob/main/sdk/cosmos/azure-cosmos-spark_3_2-12/Samples/Python/NYC-Taxi-Data/01_Batch.ipynb
