### ISSUE TITLE
Filtering enhancements to DataLakeFileSystemClient.listPaths()

### ISSUE THREAD

**Issue by wheezil** [Azure/azure-sdk-for-java#36406]
**Is your feature request related to a problem? Please describe.**

We are a provider of data integration software, and our customers use it to access Azure Data Lake g2 storage.
We occasionally find that a customer has a container or folder with 100K+ blobs.  When this happens, our user interface for listing blobs cannot enumerate them all in a reasonable time, leading to timeouts or cancelation in the UI.

**Describe the solution you'd like**

In order to support our users ability to browse to the blobs they are seeking, the following enhancements to `DataLakeFileSystemClient.listPaths()` are desired:

- An option to exclude "normal files" and only return "folders"
- An option to filter files by wildcard (glob) or regex

**Describe alternatives you've considered**

I've explored the ADL2 API and not found any options, but perhaps I've missed something.

**Additional context**

**Information Checklist**
Kindly make sure that you have added all the following information above and checkoff the required fields otherwise we will treat the issuer as an incomplete report
- [X ] Description Added
- [X ] Expected solution specified

**Comment by wheezil** [comment]
The "folders only" option is in the ABS [REST API ](https://learn.microsoft.com/en-us/rest/api/storageservices/list-blobs?tabs=azure-ad) `showonly={deleted,files,directories}`.  It is described as "Only for accounts enabled with hierarchical namespace.", which seems like that is ADL2?  But I'm unclear what that means and how that would become available to the ADL2 API.

**Comment by ibrahimrabab** [comment]
Hi @wheezil 
Thank you for reaching out with the feature suggestion! Unfortunately, although showonly is supported on HNS accounts, it is not supported for the Data Lake endpoint.  This is something we can bring up with the service team to get more clarity on this and the possibility of supporting this in the future, but as of now we are unable to support this feature request.

Please feel free to reach out with any additional questions, thank you!
