### ISSUE TITLE
[BUG] Face API library in Maven repository is outdated

### ISSUE THREAD

**Issue by v-jaswel** [Azure/azure-sdk-for-java#3640]
**Describe the bug**
The azure-faceapi-0.0.1-beta.jar and azure-cognitiveservices-faceapi-1.0.0-beta.jar files in the [Maven repository](https://search.maven.org/search?q=azure%20faceapi) are outdated (the latter was uploaded 20180518). As a result, classes like [FaceAPIManager](https://docs.microsoft.com/en-us/java/api/com.microsoft.azure.cognitiveservices.vision.faceapi.faceapimanager?view=azure-java-stable), used to authenticate to the Face service, are not available.
Also, in https://github.com/Azure/azure-sdk-for-java/blob/master/README.md, in the section Cognitive Services/Vision/Face API, the [Sources](https://github.com/Azure/azure-sdk-for-java/tree/master/cognitiveservices/azure-vision) and [Download](https://search.maven.org/search?q=a:azure-faceapi) links are outdated. The former gives me a 404. The latter gives me search results in the Maven repository that only include azure-faceapi-0.0.1-beta.jar.

***Exception or Stack Trace***
```
Test.java:7: error: cannot find symbol
            FaceAPI client = FaceAPIManager.authenticate("westus", "subscriptionKey");
                             ^
  symbol:   variable FaceAPIManager
  location: class Test
1 error
```

**To Reproduce**
1. Save code snippet as Test.java.
1. Download azure-cognitiveservices-faceapi-1.0.0-beta.jar from https://search.maven.org/search?q=azure%20faceapi.
1. Open a command prompt.
1. Run:
    javac Test.java -cp azure-cognitiveservices-faceapi-1.0.0-beta.jar

***Code Snippet***
```java
import com.microsoft.azure.cognitiveservices.vision.faceapi.*;
import com.microsoft.azure.cognitiveservices.vision.faceapi.models.*;

public class Test {
    public static void main(String[] args) {
        try {
            FaceAPI client = FaceAPIManager.authenticate("westus", "subscriptionKey");
// Do something with client
        } catch (Exception e) {
            System.out.println(e.getMessage());
            e.printStackTrace();
        }
    }
}
```

**Expected behavior**
The code compiles.

**Screenshots**
N/A

**Setup (please complete the following information):**
 - OS: Windows 10 Pro 1803
 - IDE: None
 - Version of the Library used: 1.0.0-beta

**Additional context**
I am able to make my code compile by doing the following.
1. Clone/download: https://github.com/Azure/azure-sdk-for-java
1. Install Maven (https://maven.apache.org/).
1. Add C:\Program Files\Maven\bin to your PATH environment variable.
1. At a command prompt or git-bash shell, browse to [download location]\azure-sdk-for-java-master\cognitiveservices\data-plane\vision\faceapi
1. Run:
    mvn package -f ./pom.xml
1. That generates azure-cognitiveservices-faceapi-1.0.2-beta.jar in a folder named "target".
1. Compiling Test.java using this .jar file works as expected.

**Information Checklist**
Kindly make sure that you have added all the following information above and checkoff the required fields otherwise we will treat the issuer as an incomplete report
- [x] Bug Description Added
- [x] Repro Steps Added
- [x] Setup information Added

**Comment by kurtzeborn** [comment]
Thank you for opening this issue! We are routing it to the appropriate team for follow up.

**Comment by joshfree** [comment]
@milismsft @ryogok

**Comment by wilkoetsier** [comment]
@joshfree any updates for this issue?

**Comment by thomasburguiere** [comment]
Still not fixed as of January 2021. Any idea when this is going to be fixed ? Are there any other alternative ways to get the up-to-date sdk ?

Thanks a lot

**Comment by joshfree** [comment]
@samvaity could you please follow up on this issue?

**Comment by samvaity** [comment]
Hello @v-jaswel, you can find the [sources](https://github.com/Azure/azure-sdk-for-java/tree/main/sdk/cognitiveservices/ms-azure-cs-faceapi) and [download here](https://search.maven.org/artifact/com.microsoft.azure.cognitiveservices/azure-cognitiveservices-faceapi/1.0.0-beta/jar).
Do let me know if you are still facing the issue.

cc: @[thomasburguiere](https://github.com/thomasburguiere)

**Comment by RobertoSD22** [comment]
> Hello @v-jaswel, you can find the [sources](https://github.com/Azure/azure-sdk-for-java/tree/main/sdk/cognitiveservices/ms-azure-cs-faceapi) and [download here](https://search.maven.org/artifact/com.microsoft.azure.cognitiveservices/azure-cognitiveservices-faceapi/1.0.0-beta/jar). Do let me know if you are still facing the documentation issue.
> 
> cc: @[thomasburguiere](https://github.com/thomasburguiere)

I go into the mentioned url (https://search.maven.org/artifact/com.microsoft.azure.cognitiveservices/azure-cognitiveservices-faceapi/1.0.0-beta/jar) and download the dependency but the problem still persists, the FaceAPIManager class is still not inside the jar

![Captura de pantalla 2022-04-05 185922](https://user-images.githubusercontent.com/60632992/161870085-01eb5b75-bfa1-466d-8a7f-8288cf393938.jpg)

**Comment by samvaity** [comment]
Hello @RobertoSD22, you are right, the FaceAPIManager class was missing from the previous release. We did release this package again recently and you can find the updated jar here https://mvnrepository.com/artifact/com.microsoft.azure.cognitiveservices/azure-cognitiveservices-faceapi/1.0.1-beta

**Comment by samvaity** [comment]
Hello @RobertoSD22 / @v-jaswel, This seems to be working with the updated jar here https://mvnrepository.com/artifact/com.microsoft.azure.cognitiveservices/azure-cognitiveservices-faceapi/1.0.1-beta

Closing this, do reopen if this is still an issue.
