### ISSUE TITLE
Enhancements to BlobContainerClient.listBlobsByHierarchy()

### ISSUE THREAD

**Issue by wheezil** [Azure/azure-sdk-for-java#36407]
**Is your feature request related to a problem? Please describe.**

We are a provider of data integration software, and our customers use it to access Azure Blob Stroage.
We occasionally find that a customer has a container or folder with 100K+ blobs.  When this happens, our user interface for listing blobs cannot enumerate them all in a reasonable time, leading to timeouts or cancelation in the UI.

**Describe the solution you'd like**

In order to support our users ability to browse to the blobs they are seeking, the following enhancements to `BlobContainerClient.listBlobsByHierarchy()` are desired:

- An option to exclude "normal files" and only return "folders"
- An option to filter files by wildcard (glob) or regex

**Describe alternatives you've considered**

I've explored the ABS API and not found any options, but perhaps I've missed something.

The [REST API ](https://learn.microsoft.com/en-us/rest/api/storageservices/list-blobs?tabs=azure-ad) documents an option `showonly={deleted,files,directories}` but that doesn't seem to be available in the Java API.

**Additional context**

**Information Checklist**
Kindly make sure that you have added all the following information above and checkoff the required fields otherwise we will treat the issuer as an incomplete report
- [X ] Description Added
- [X ] Expected solution specified

**Comment by joshfree** [comment]
@ibrahimrabab could you please follow up

**Comment by ibrahimrabab** [comment]
Hi @wheezil 
Thank you for reaching out with the feature suggestion! After speaking with the SDK team, this isn't something we are able to support at the moment, but we will be in touch with the service team to follow up with them about the possibility of supporting this in the future. 

Thank you again, and please feel free to reach out with any additional questions!
