### ISSUE TITLE
[QUERY] DataLakeDirectoryClient directories listing

### ISSUE THREAD

**Issue by razvanilie** [Azure/azure-sdk-for-java#36408]
**Query/Question**
Hello guys, I have a question regarding the DataLakeDirectoryClient and how the implementation is done for the listPaths() method. 
Looking on the official docs [path/list](https://learn.microsoft.com/en-us/rest/api/storageservices/datalakestoragegen2/path/list#uri-parameters) I was able to see that the directory listing of the filesytem can have a **_continuation_** parameter in case that `the number of paths to be returned exceeds this limit`. I also read that the max result is 5000 items. I have around 7000 directories in my main filesystem and I don't find any parameter in the listPaths method from DataLakeDirectoryClient that would indicate where to put the continuation token or how to receive one. I also was able to see that listPaths() succesfully returns all 7000 directories. Is the continuation done in the back-end on your side or am I missing something since 7000 is greater than the MAX_RESULT specified in the official documentation. 

***Why is this not a Bug or a feature Request?***
It works as I want to but I am afraid that it will not work in the future

**Setup (please complete the following information if applicable):**
 - latest version of SDK
 
 **Information Checklist**
 Kindly make sure that you have added all the following information above and checkoff the required fields otherwise we will treat the issuer as an incomplete report
- [x] Query Added
- [x] Setup information Added

**Comment by alzimmermsft** [comment]
Thanks for asking this question @razvanilie 

By default, handling of continuation tokens is managed by our `PagedIterable` and `PagedFlux` types, so code like `dataLakeDirectoryClient.listPaths().forEach(path -> consumePath(path));` will just work and iterate through all paged responses and therefore list all paths in the ADLS directory. 

But this restricts the finer details of paging and will only list the items in each paged response, so `PagedIterable` and `PagedFlux` offer APIs which allow for greater details of paging to be consumed. For `PagedIterable` there are `streamByPage` and `iterableByPage` APIs and `PagedFlux` there is `byPage` APIs which return the lower level `PagedResponse<T>` which will contain a lower-level view of paging. `PagedResponse` will have the continuation token (`PagedResponse.getContinuationToken`) and the elements of the paged response (`PagedResponse.getValue`), and other HTTP request-response data (status code, headers, the request). You can use these lower-level APIs to capture the continuation token and to resume paging later (though I don't have good information on how long a continuation token is good for). For example:

**Comment by ibrahimrabab** [comment]
Hi @razvanilie 
Is this still an issue you're experiencing?
