### ISSUE TITLE
[BUG] Calling FaceAPIManager.authenticate(String, String) to authenticate does not set Azure region

### ISSUE THREAD

**Issue by v-jaswel** [Azure/azure-sdk-for-java#3641]
**Describe the bug**
Calling the FaceAPIManager.authenticate(String, String) overload to create a Face API client fails to set a private member variable, which later results in thrown exceptions when you call the methods of the Faces interface.

***Exception or Stack Trace***
```
Parameter this.client.azureRegion() is required and cannot be null.
java.lang.IllegalArgumentException: Parameter this.client.azureRegion() is required and cannot be null.
        at com.microsoft.azure.cognitiveservices.vision.faceapi.implementation.FacesImpl.detectWithUrlWithServiceResponseAsync(FacesImpl.java:701)
        at com.microsoft.azure.cognitiveservices.vision.faceapi.implementation.FacesImpl.detectWithUrl(FacesImpl.java:658)
        at FindSimilar.main(FindSimilar.java:64)
```

**To Reproduce**
1. Create a Face API client with FaceAPIManager.authenticate(String, String). Note: to use FaceAPIManager, I am referencing azure-cognitiveservices-faceapi-1.0.2-beta.jar, which I compiled from https://github.com/Azure/azure-sdk-for-java. For more information see: https://github.com/Azure/azure-sdk-for-java/issues/3640.
1. Call a method like Faces.detectWithUrl.
1. An exception is thrown.

***Code Snippet***
```
String subscriptionKey = "<insert key here>";
String faceEndpoint = "https://westus.api.cognitive.microsoft.com";
String imageUrl = "https://www.biography.com/.image/t_share/MTQ1MzAyNzYzOTgxNTE0NTEz/john-f-kennedy---mini-biography.jpg";
FaceAPI client = FaceAPIManager.authenticate(faceEndpoint, subscriptionKey);
List<DetectedFace> detectedFaces = client.faces().detectWithUrl(imageUrl, new DetectWithUrlOptionalParameter().withReturnFaceId(true));
```

**Expected behavior**
Calling the FaceAPIManager.authenticate(String, String) overload to create a Face API client lets me call the methods of the Faces interface without errors.

**Screenshots**
N/A

**Setup (please complete the following information):**
 - OS: Windows 10 Pro 1804
 - IDE: None
 - Version of the Library used: 1.0.2-beta (compiled from downloaded Github repo https://github.com/Azure/azure-sdk-for-java)

**Additional context**
FaceAPIManager.authenticate(String, String) does not set the Azure region, unlike other overrides such as FaceAPIManager.authenticate(AzureRegions, String):
https://github.com/Azure/azure-sdk-for-java/blob/master/cognitiveservices/data-plane/vision/faceapi/src/main/java/com/microsoft/azure/cognitiveservices/vision/faceapi/FaceAPIManager.java#L24
```
public static FaceAPI authenticate(AzureRegions region, String subscriptionKey) {
    return authenticate("https://{AzureRegion}.api.cognitive.microsoft.com/face/v1.0/", subscriptionKey)
        .withAzureRegion(region);
}
```

FaceAPIImpl.withAzureRegion simply sets the azureRegion private member variable that is accessed by FaceAPIImpl.azureRegion.
https://github.com/Azure/azure-sdk-for-java/blob/master/cognitiveservices/data-plane/vision/faceapi/src/main/java/com/microsoft/azure/cognitiveservices/vision/faceapi/implementation/FaceAPIImpl.java#L49
```
public FaceAPIImpl withAzureRegion(AzureRegions azureRegion) {
    this.azureRegion = azureRegion;
    return this;
}
```

However, FaceAPIManager.authenticate(String, String) calls FaceAPIManager.authenticate(String, ServiceClientCredentials), neither of which calls FaceAPIImpl.withAzureRegion. This is probably because AzureRegions is an enum type and baseURL is a string, so they would need to parse the URL or just scan it for known AzureRegions values.
https://github.com/Azure/azure-sdk-for-java/blob/master/cognitiveservices/data-plane/vision/faceapi/src/main/java/com/microsoft/azure/cognitiveservices/vision/faceapi/FaceAPIManager.java#L77
```
public static FaceAPI authenticate(String baseUrl, ServiceClientCredentials credentials) {
    return new FaceAPIImpl(baseUrl, credentials);
}
```

FaceAPIImpl.initialize creates an instance of FacesImpl and passes itself to the constructor.
https://github.com/Azure/azure-sdk-for-java/blob/master/cognitiveservices/data-plane/vision/faceapi/src/main/java/com/microsoft/azure/cognitiveservices/vision/faceapi/implementation/FaceAPIImpl.java#L211
```
protected void initialize() {
// ...
    this.faces = new FacesImpl(restClient().retrofit(), this);
```

The FacesImpl saves the FacesAPIImpl instance.
https://github.com/Azure/azure-sdk-for-java/blob/master/cognitiveservices/data-plane/vision/faceapi/src/main/java/com/microsoft/azure/cognitiveservices/vision/faceapi/implementation/FacesImpl.java#L63
```
public FacesImpl(Retrofit retrofit, FaceAPIImpl client) {
    this.service = retrofit.create(FacesService.class);
    this.client = client;
}
```

FacesImpl's methods, such as detectWithUrlWithServiceResponseAsync, perform the following check, which throws, because FaceAPIImpl.azureRegion was not set.
```
if (this.client.azureRegion() == null) {
    throw new IllegalArgumentException("Parameter this.client.azureRegion() is required and cannot be null.");
}
```

My suggestion re: the fix would be to change FaceAPIManager.authenticate(String, String) and/or FaceAPIManager.authenticate(String, ServiceClientCredentials) to call FaceAPIImpl.withAzureRegion. They'll likely need the parse the base URL or maybe just scan it for known AzureRegions values.

**Information Checklist**
Kindly make sure that you have added all the following information above and checkoff the required fields otherwise we will treat the issuer as an incomplete report
- [x] Bug Description Added
- [x] Repro Steps Added
- [x] Setup information Added

**Comment by kurtzeborn** [comment]
Thank you for opening this issue! We are routing it to the appropriate team for follow up.

**Comment by wiazur** [comment]
Hi @kurtzeborn, do you happen to know the status for this issue? Would like to create a bunch of Face Java code examples, but currently blocked. Thanks much.

**Comment by joshfree** [comment]
@milismsft @ryogok

**Comment by samvaity** [comment]
Hello @[v-jaswel](https://github.com/v-jaswel), 

Can you try using the `withAzureRegion` API along with the `authenticate(String, String)` method?

```java
FaceAPI client = FaceAPIManager.authenticate(faceEndpoint, subscriptionKey).withAzureRegion(AzureRegions.WESTUS2)
```

Let us know if this is still an issue.
