### ISSUE TITLE
[QUERY] How to return custom ChatCompletions on error case in OpenAI SDK?

### ISSUE THREAD

**Issue by mkemmerz** [Azure/azure-sdk-for-java#36416]
**Query/Question**
How do I add an exception handling on the Flux objects of `Flux<ChatCompletions>`? In my case a custom message, similar to the error message in Azure OpenAI Service. I tried to use the `onErrorResume` and `onErrorReturn` methods without luck.

I am happy about any help!

OpenAI has this very nice message that is used if a streamed answer is triggering the content filter:

![image](https://github.com/Azure/azure-sdk-for-java/assets/46575727/3626b7a5-5245-479a-8953-dfd76313908d)

I would also like to add such a message to our use case. Unfortunately I am struggling a bit as all objects are final with private constructors, e.g. ChatCompletions and ChatChoice. Therefore I can't simply create a new `Flux<ChatCompletions>`

**Setup (please complete the following information if applicable):**
 - OS: MAC
 - IDE: IntelliJ 
 - Library/Libraries: Java azure-ai-openai 1.0.0-beta.2
 
```
    Flux<ChatCompletions> chatCompletions = openAiAsyncClient.getChatCompletionsStream(OPEN_AI_DEPLOYMENT_ID, options);
    chatCompletions.takeUntil(chatCompletion -> {
         CompletionsFinishReason reason = chatCompletion.getChoices().get(0).getFinishReason();
         if (reason == null || reason.toString() == null) {
           return false;
         }

         if (reason.toString().equals("content_filter")) {
           System.out.println("Content filter triggered.");
           throw new ContentFilterException();
         }

         return false;
       })
       // The map method throws NullPointer because Message is empty
      .map(chatCompletion -> chatCompletion.getChoices().get(0).getMessage().getContent())
        .onErrorResume(ContentFilterException.class, error -> {
          // Does not work ...
          return Flux.just("Content filter triggered.");
        })
      .subscribe();
```

Is it even the correct approach to throw the exception in the `takeUntil`? I am open to other solutions as well!

**Comment by mssfang** [comment]
Hi @mkemmerz 
You can use `.onErrorMap`  to transform any error.

`.doOnError`  adds behavior triggered when the Flux completes with an error.
