### ISSUE TITLE
Add TSG for IntelliJ Credential and Common Fork Join Pool 

### ISSUE THREAD

**Issue by g2vinay** [Azure/azure-sdk-for-java#36435]
Add TSG for IntelliJ Credential like we have for other credentials in TROUBLESHOOTING.md.
Add TSG for Common Fork Join Pool related issues.

**Comment by joshfree** [comment]
@g2vinay any update on this item?

**Comment by joshfree** [comment]
ping

**Comment by joshfree** [comment]
@g2vinay this has been marked as `in progress` for many months - is this actually being worked on?

Should this instead be moved back to `Backlog` / `Not Started` ?

**Comment by g2vinay** [comment]
Fixed by https://github.com/Azure/azure-sdk-for-java/pull/37521
