### ISSUE TITLE
[BUG] Exception thrown on auth resolution with empty  .AzureToolsForIntelliJ/AuthMethodDetails.json

### ISSUE THREAD

**Issue by tkent** [Azure/azure-sdk-for-java#36432]
**Describe the bug**

When using the `DefaultAzureCredentialBuilder` (just `new DefaultAzureCredentialBuilder().build();`), an exception will be thrown when there is an empty file located at  `~/.AzureToolsForIntelliJ/AuthMethodDetails.json`. Unfortunately, the Azure Toolkit for Rider IDE plugin creates an empty file at the location at launch.

This means that developers using Rider are likely to have exceptions thrown when using the `DefaultAzureCredentialBuilder`.

***Exception or Stack Trace***

```
com.azure.core.exception.ClientAuthenticationException: DefaultAzureCredential authentication failed. ---> IntelliJCredential authentication failed. Error Details: com.fasterxml.jackson.databind.exc.MismatchedInputException: No content to map due to end-of-input
 at [Source: (File); line: 1, column: 0]
Caused by: reactor.core.Exceptions$ReactiveException: com.fasterxml.jackson.databind.exc.MismatchedInputException: No content to map due to end-of-input
 at [Source: (File); line: 1, column: 0]
	Suppressed: java.lang.Exception: #block terminated with an error
Caused by: com.fasterxml.jackson.databind.exc.MismatchedInputException: No content to map due to end-of-input
 at [Source: (File); line: 1, column: 0]
```

**To Reproduce**

Create an empty file at `~/.AzureToolsForIntelliJ/AuthMethodDetails.json` _or_ just launch Rider with the Azure Toolkit for Rider version `3.50.01664-2023.2`

**Example Snippet**

This small kotlin snippet will reproduce the issue

```kotlin
val defaultCredential = DefaultAzureCredentialBuilder().build()
val ctx = with(TokenRequestContext()) {
  scopes = arrayListOf("https://database.windows.net")
  this
}
defaultCredential.getTokenSync(ctx)
```

**Setup (please complete the following information):**
 - OS: OS X 12.6.8
 - IDE: Rider `2023.2` + Azure Toolkit for Rider `3.50.0-1664-2023.2`
 - Library/Libraries: `com.azure:azure-identity:1.9.1`
 - Java version: 11

**Comment by joshfree** [comment]
Thanks for filing this issue, @tkent.  @g2vinay could you please follow up?

/cc @billwert

**Comment by g2vinay** [comment]
@tkent 
Thank you for reporting this issue.
I am investigating it, will follow up with next steps.

**Comment by g2vinay** [comment]
A fix for this is merged via https://github.com/Azure/azure-sdk-for-java/pull/37044
It will be released in beta release this month and GA in Nov 2023 (next month)
