### ISSUE TITLE
[BUG] Exception Multi-lilne data not supported in streaming for Azure OpenAI (beta2 release)

### ISSUE THREAD

**Issue by mkemmerz** [Azure/azure-sdk-for-java#36443]
**Describe the bug**
Sometimes, during the streaming of a chat result, the following error message is thrown:

The issue is happening here: https://github.com/Azure/azure-sdk-for-java/blob/main/sdk/openai/azure-ai-openai/src/main/java/com/azure/ai/openai/implementation/OpenAIServerSentEvents.java#L55

***Exception or Stack Trace***
```
reactor.core.Exceptions$ErrorCallbackNotImplemented: java.lang.UnsupportedOperationException: Multi-line data not supported data: {"id":"chatcmpl-7qDwpN3pUmAHoaH0d7jNMjfBN9r54","object":"chat.completion.chunk","created":1692681027,"model":"gpt-35-turbo","choices":[{"index":0,"finish_reason":null,"delta":{"content":" his"},"content_filter_result":{"error":{"code":"content_filter_error","message":"The contents are not filtered"}}}],"usage":null}
Caused by: java.lang.UnsupportedOperationException: Multi-line data not supported data: {"id":"chatcmpl-7qDwpN3pUmAHoaH0d7jNMjfBN9r54","object":"chat.completion.chunk","created":1692681027,"model":"gpt-35-turbo","choices":[{"index":0,"finish_reason":null,"delta":{"content":" his"},"content_filter_result":{"error":{"code":"content_filter_error","message":"The contents are not filtered"}}}],"usage":null}
	at com.azure.ai.openai.implementation.OpenAIServerSentEvents.lambda$getEvents$0(OpenAIServerSentEvents.java:55)
	at com.azure.core.http.netty.implementation.AzureSdkHandler.channelRead(AzureSdkHandler.java:222) [25 skipped]
```

**To Reproduce**
Sorry, I am not sure how to reproduce it directly. For me it happens irregularly.

***Code Snippet***
Just a regular, streamed request:
```
    ChatCompletionsOptions options = new ChatCompletionsOptions(chatMessages).setStream(true);
    Flux<ChatCompletions> chatCompletions = openAiAsyncClient.getChatCompletionsStream(OPEN_AI_DEPLOYMENT_ID, options);

Spring Controller:
  @RequestMapping(value = "/api/v1/chat/completions", method = RequestMethod.POST, produces = MediaType.TEXT_EVENT_STREAM_VALUE)
  public ResponseEntity<Flux<ChatChoice>> streamChatCompletions(@RequestBody List<ChatMessage> chatMessages) {
 return chatBotService.getStreamChatCompletions(chatMessages);
}
```

The exception is thrown in the middle of the stream, not at the beginning of it.

**Expected behavior**
The buffer should be converted correctly to a string.

**Screenshots**

**Setup (please complete the following information):**
 - OS: MAC
 - IDE: IntelliJ
 - Library/Libraries: Azure SDK OpenAI 1.0.0-beta2
 - Java version: 17 
 - Frameworks: Spring Boot 3.1.2

**Comment by mssfang** [comment]
Hi @mkemmerz 
Please don't use `.setStream(true)`  which will be removed eventually before GA. 
Can you give it a try after removing it.

**Comment by srnagar** [comment]
@mkemmerz Please upgrade to `azure-ai-openai` library [version 1.0.0-beta.3](https://mvnrepository.com/artifact/com.azure/azure-ai-openai/1.0.0-beta.3) as we updated the streaming APIs implementation and this issue should be fixed in this new version. 

If you are still running into this issue after upgrade, please provide the full exception stacktrace and it would be great if you can provide us with a reproducible sample or just the prompt you are using.

**Comment by mkemmerz** [comment]
Thanks @srnagar, looks like the version bump has fixed this error message!
