### ISSUE TITLE
[FEATURE REQ] Query params support in the MetricsBatchQueryClient (start, endTime, filter)

### ISSUE THREAD

**Issue by matvey-mtn** [Azure/azure-sdk-for-java#36457]
**Query/Question**
How to add start/endTime or filter while using new MetricsBatchQueryClient?

Please consider the following snippet (kotlin):
```kotlin
        val metricsQueryBatchClient: MetricsBatchQueryClient = MetricsBatchQueryClientBuilder()
            .endpoint("https://${resource.region().name()}.metrics.monitor.azure.com")
            .credential(clientSecretCredential)
            .buildClient()

        metricsQueryBatchClient
            .queryBatch(
                listOf("{res1}", "{res2}"),
                listOf("{metricName1}", "{metricName2}"),
                "{namespace}"
            )
```

There's no way to pass startTime/endtime to queryBatch() function.
It looks like underlying metrics client `com.azure.monitor.query.implementation.metricsbatch.Metrics` does accept these parameters, why it's not exposed in the MetricsBatchQueryClient?

Is adding query params in the roadmap?
Thanks in advance!

***Why is this not a Bug or a feature Request?***
I am using beta version of the library, so I suppose it will be added as part of GA release.

**Setup (please complete the following information if applicable):**
 - Library/Libraries: com.azure:azure-monitor-query:1.3.0-beta.1
 
 **Information Checklist**
- [x] Query Added
- [x] Setup information Added

**Comment by joshfree** [comment]
@jairmyree could you please follow up

**Comment by matvey-mtn** [comment]
Just to add more context: I am looking for a way of reducing the number of API calls to the Azure Monitor. I want to leverage MetricsBatchQueryClient for that.
However, sometimes I need to query old metrics, and sometimes I want to apply dimension splitting (using filter).
I cannot do that with current Java SDK because parameters mentioned above are not accepted.

**Comment by jairmyree** [comment]
@matvey-mtn Thank you for reaching out. I will consult the team and discuss supporting this feature in a beta release.

**Comment by srnagar** [comment]
@matvey-mtn This feature will be enabled in the next beta release. I will update this issue when it's released (around 2nd week of Sep 2023).

**Comment by matvey-mtn** [comment]
@jairmyree @srnagar this is amazing, thanks!
Do you want me to rename the title to the [FEATURE REQ]?

**Comment by jairmyree** [comment]
@matvey-mtn No worries, I've already updated it.

**Comment by matvey-mtn** [comment]
Hi @jairmyree @srnagar!
Any update or ETA about when to expect the fix?

BR

**Comment by jairmyree** [comment]
@matvey-mtn, sorry about the delayed in the follow-up. Support for this feature was added in the 1.3.0-beta.2 on Sept. 13th, 2023. Here's a link to the changelog: 

https://github.com/Azure/azure-sdk-for-java/blob/azure-monitor-query_1.3.0-beta.2/sdk/monitor/azure-monitor-query/CHANGELOG.md

Once again, sorry about the delayed follow-up.

**Comment by matvey-mtn** [comment]
amazing, thanks @jairmyree 🙏🏻
