### ISSUE TITLE
When using Azure with ManagedIdentityCredential all actions takes much time in comparison to SharedKeyCredential 

### ISSUE THREAD

**Issue by ihudedi** [Azure/azure-sdk-for-java#36477]
Hi,
I am trying to use ManagedIdentityCredential  to connect to azure and perfrom actions like list files or upload files but all actions
takes much time in comparison to using SharedKeyCredential
Can someone let me know if it's a known issue?
Thanks,
Itay

**Comment by billwert** [comment]
Hello @ihudedi! I have a handful of questions.

Can you share a little about your environment? In either case the access token is cached in memory on your client, so calls after the first should be roughly the same. I wouldn't expect the first call to be that meaningfully different either. What version of azure-identity are you using? What is the relative difference?

**Comment by ihudedi** [comment]
Hi @billwert 
azure identity version is 1.4.0
When uploading 1GB -> with SharedKeyCredential  takes ~100sec while in ManagedIdentityCredential  takes ~1000sec
same issue when browsing files in container takes much time.
I expected it should be the same after connect but it takes much time.
Thanks,
Itay

**Comment by ihudedi** [comment]
Hi @billwert 
Any updates regrading this issue?
Thanks,
Itay

**Comment by ihudedi** [comment]
Hi @billwert
I need to understand if using the Managed Identity via java cause this slowness in comparison to other connection methods like SharedKeyCredential
Thanks,
Itay

**Comment by billwert** [comment]
Hello @ihudedi - I will investigate this. Would you please share some repro code?

**Comment by ihudedi** [comment]
Hi @billwert 
 BlobServiceClientBuilder blobServiceClientBuilder = new BlobServiceClientBuilder();
 int azureRequestRetryDelay = mftPropertiesConfig.getIntProperty(PropertyData.azureRequestRetryDelay, AZURE_REQUEST_RETRY_DELAY);
            RequestRetryOptions requestRetryOptions = new RequestRetryOptions(RetryPolicyType.FIXED, azureRequestMaxAttempts, null, Duration.ofMillis(azureRequestRetryDelay), Duration.ofMillis(azureRequestRetryDelay), null);
            blobServiceClientBuilder.retryOptions(requestRetryOptions);
            //setting the endpoint from the account in case the azure endpoint not exist in Additional Params.
            if (StringUtils.isEmpty(azureEndpoint)) {
                azureEndpoint = hostProperties.getAzureEndpoint();
            }
            if (StringUtils.isEmpty(azureEndpoint)) {
                azureEndpoint = String.format(Locale.ROOT, "https://%s.blob.core.windows.net", azureAccountName);
            }
            blobServiceClientBuilder.endpoint(azureEndpoint);
            OkHttpAsyncHttpClientBuilder okHttpAsyncHttpClientBuilder = new OkHttpAsyncHttpClientBuilder();

            int azureReadTimeout = mftPropertiesConfig.getIntProperty(PropertyData.azureReadTimeout, AZURE_READ_TIMEOUT);
            int azureWriteTimeout = mftPropertiesConfig.getIntProperty(PropertyData.azureWriteTimeout, AZURE_WRITE_TIMEOUT);
            int azureResponseTimeout = mftPropertiesConfig.getIntProperty(PropertyData.azureResponseTimeout, AZURE_RESPONSE_TIMEOUT);
            int azureConnectionTimeout = mftPropertiesConfig.getIntProperty(PropertyData.azureConnectionTimeout, AZURE_CONNECTION_TIMEOUT);
            okHttpAsyncHttpClientBuilder.readTimeout(Duration.ofMillis(Long.valueOf(azureReadTimeout)));
            okHttpAsyncHttpClientBuilder.writeTimeout(Duration.ofMillis(Long.valueOf(azureWriteTimeout)));
            okHttpAsyncHttpClientBuilder.connectionTimeout(Duration.ofMillis(Long.valueOf(azureConnectionTimeout)));
            if (isProxySet) {
                //If we need proxy we use httpClient() method to add this need to check the code.
                ProxyOptions proxyOptions = new ProxyOptions(ProxyOptions.Type.HTTP, new InetSocketAddress(proxyHost, proxyPort));
                if (!StringUtils.isEmpty(proxyUserName)) {
                    proxyOptions.setCredentials(proxyUserName, decryptedProxyPassword);
                }
                if (!StringUtils.isEmpty(proxyNonProxyHosts)) {
                    proxyOptions.setNonProxyHosts(proxyNonProxyHosts);
                }
                okHttpAsyncHttpClientBuilder.proxy(proxyOptions);
            }
            HttpClient httpClient = okHttpAsyncHttpClientBuilder.build();
            blobServiceClientBuilder.httpClient(httpClient);
            boolean azureLogHTTPMessages = mftPropertiesConfig.getBooleanProperty(PropertyData.azureLogHTTPMessages);
            if (azureLogHTTPMessages) {
                blobServiceClientBuilder.httpLogOptions(blobServiceClientBuilder.getDefaultHttpLogOptions().setLogLevel(HttpLogDetailLevel.BODY_AND_HEADERS).setPrettyPrintBody(true));
            }
 if (AzureCredentialMethod.MANAGED_IDENTITY_CREDENTIAL.getValue().equals(azureCredentialMethod)) {
                //clientId isn't mandatory - this clientId is the clientId of the User assigned managed identity - for System assigned managed identity this field should be empty.
                blobServiceClientBuilder.credential(new ManagedIdentityCredentialBuilder().httpClient(httpClient).clientId(azureClientId).maxRetry(AZURE_REQUEST_ONLY_ONE_ATTEMPT).build());
            } else if (AzureCredentialMethod.SHARED_KEY_CREDENTIAL.getValue().equals(azureCredentialMethod)) {
                blobServiceClientBuilder.credential(new StorageSharedKeyCredential(azureAccountName, azureAccountAccessKey));

   blobServiceClient = blobServiceClientBuilder.buildClient();

  and with this object I am perfroming list containers/list objects etc
Thanks,
Itay

**Comment by ihudedi** [comment]
Hi @billwert 
Moving to latest release of azure storage blob,azure identity and azure ok http solved this issue
Thanks,
Itay

**Comment by billwert** [comment]
Wonderful! Thanks for letting us know. Please reach out if you have further issues.
