### ISSUE TITLE
[BUG]OpenAIAsyncClient.getChatCompletions.subscribe do not get anything 

### ISSUE THREAD

**Issue by wzglgo** [Azure/azure-sdk-for-java#36476]
<img width="1055" alt="image" src="https://github.com/Azure/azure-sdk-for-java/assets/95947852/b0386dd2-743f-4ed6-a8de-c0ccf5fc8e98">

This code on the graph is not giving me any output. My key is fine, and I can retrieve the data correctly using a non-async method. thx
There is also no output for 'aaaaaa

**Comment by mssfang** [comment]
Hi @wzglgo 

Azure SDK for Java (including OpenAI SDK) uses `project-reactor` as the async non-blocking foundation. 

For your sample, to print out the string `aaaaaaaa`, you can either block it or add a timeout. 

See [sample](https://github.com/Azure/azure-sdk-for-java/blob/main/sdk/openai/azure-ai-openai/src/samples/java/com/azure/ai/openai/usage/GetChatCompletionsAsyncSample.java#L71)

**Comment by wzglgo** [comment]
Yes, I tested it with this example from the beginning, but still there is no output at all, the callback function is not being triggered @mssfang
