### ISSUE TITLE
[QUERY][OpenAI] Is it possible to interrupt streaming chat message in OpenAI SDK?

### ISSUE THREAD

**Issue by Miura-KR** [Azure/azure-sdk-for-java#36492]
**Query/Question**
Is it possible to interrupt the process of getting streaming messages by `OpenAIClient#getChatCompletionsStream` or `OpenAIAsyncClient#getChatCompletionsStream`?

**Setup (please complete the following information if applicable):**
 - OS: Windows
 - IDE: vscode
 - Library/Libraries: Java azure-ai-openai 1.0.0-beta.3
 
 **Information Checklist**
 Kindly make sure that you have added all the following information above and checkoff the required fields otherwise we will treat the issuer as an incomplete report
- [x] Query Added
- [x] Setup information Added

**Comment by mssfang** [comment]
@Miura-KR Are you asking to stop the streaming?

**Comment by Miura-KR** [comment]
@mssfang yes

**Comment by mssfang** [comment]
For Async APIs, you can cancel an ongoing Flux/Mono by using the Disposable object returned by the subscribe() method.

For example, use `.dispose()` to cancel Flux blew.
```java
        List<String> lists = new ArrayList<>();
        for (int i = 0; i < 10000; i++) {
           lists.add("h" + i);
        }
        Disposable disposable = Flux.fromIterable(lists)
                .delayElements(Duration.ofSeconds(1))
                .map(String::toLowerCase)
                .subscribe(System.out::println);

        Thread.sleep(5000); //Sleeping so that some elements in the flux get printed
        disposable.dispose();
```

For Sync APIs, unfortunately, there is no support for cancellation on the `IterableStream` object. But we are considering adding cancellation to it.

**Comment by Miura-KR** [comment]
@mssfang  
Wow, I made it for Async API !
Thank you very much!!
