### ISSUE TITLE
[BUG]The flow returns garbled characters

### ISSUE THREAD

**Issue by yanchuyu** [Azure/azure-sdk-for-java#36495]
When streaming returns, the string returned by the delta.getContent() method appears garbled. Look forward to receiving your reply and answer
![image](https://github.com/Azure/azure-sdk-for-java/assets/80189123/bb57afdf-816d-4437-8fb0-83f3f05e3eb4)

```[tasklist]
### Tasks
```

**Comment by yanchuyu** [comment]
The following apis are used  

chatCompletionsStream
            .stream()
            // Remove .skip(1) when using Non-Azure OpenAI API
            // Note: the first chat completions can be ignored when using Azure OpenAI service which is a known service bug.
            // TODO: remove .skip(1) when service fix the issue.
            .skip(1)
            .forEach(chatCompletions -> {
                ChatMessage delta = chatCompletions.getChoices().get(0).getDelta();
                if (delta.getRole() != null) {
                    System.out.println("Role = " + delta.getRole());
                }
                if (delta.getContent() != null) {
                    System.out.print(delta.getContent());
                }
            });
    }

**Comment by joshfree** [comment]
@mssfang could you please assist @yanchuyu with their question on character encoding

**Comment by mssfang** [comment]
@yanchuyu Thanks for reporting this. 
Which version of OpenAI SDK and model version you are using?

It might be same issue as https://github.com/Azure/azure-sdk-for-java/issues/35694

**Comment by mssfang** [comment]
> com.azure azure-ai-openai 1.0.0-beta.2
> model version is 3.5
> 
> OpenAIClient version is 2023-03-15-preview

Can you try  `azure-ai-openai` `1.0.0-beta.3` or `1.0.0-beta.4`.
This issue should be fixed since `1.0.0-beta.3`
