### ISSUE TITLE
Identity e2e WebJobs tests fail

### ISSUE THREAD

**Issue by joshfree** [Azure/azure-sdk-for-java#36501]
https://github.com/Azure/azure-sdk/issues/902#issuecomment-1569598341
![image](https://github.com/Azure/azure-sdk-for-java/assets/1302850/eae45877-f6ec-4beb-a928-8df3e05dbda8)

**Comment by g2vinay** [comment]
We've automated this testing via Web Apps. Manual testing no longer needed.
