### ISSUE TITLE
Identity e2e tests fail in multi tenant scenario

### ISSUE THREAD

**Issue by joshfree** [Azure/azure-sdk-for-java#36500]
https://github.com/Azure/azure-sdk/issues/1346#issuecomment-1539586942
![image](https://github.com/Azure/azure-sdk-for-java/assets/1302850/e1e8b9fa-f880-42e5-9d46-cc559fd5d2b5)

**Comment by billwert** [comment]
This was not a java specific failure. Dealing with it back in the main issue so the context is still there.
