### ISSUE TITLE
[BUG] Incorrect handle of NextLink URL for resourcemanager.compute.fluent.VirtualMachinesClient with filter of virtualMachineScaleSet

### ISSUE THREAD

**Issue by yumingqiao** [Azure/azure-sdk-for-java#36506]
**Describe the bug**
We are currently using resourcemanager.compute.fluent.VirtualMachinesClient to listinstances. We added a filter for virtualMachineScaleSets using the `$filter` query param, see below:
```
    val filterByVmss =
      s"'virtualMachineScaleSet/id' eq " +
      s"'/subscriptions/${subscriptionID}/resourceGroups/${resourceGroup}" +
      s"/providers/Microsoft.Compute/virtualMachineScaleSets/${vmssName}'"

    val vmInstances = vmClient.listByResourceGroup(
      resourceGroup,
      filterByVmss,
      null,
      Context.NONE
    )
```

When the VM list has more than 50 vms and needs Pagination, the response will include a "NextLink", however the SDK sends the second paging request containing the unescaped characters from the "NextLink", and gets rejected by the server.

Example of unescaped URL (this is the request of the second page, notice the unescaped space character, `' eq '`):
```
{"az.sdk.message":"HTTP request","method":"GET","url":"[https://management.azure.com:443/subscriptions/xxxxxx-xxxx-xxxx-xxxx-xxxxx/resourceGroups/xxxxx/providers/Microsoft.Compute/virtualMachines?api-version=2023-03-01&](https://management.azure.com/subscriptions/xxxxxx-xxxx-xxxx-xxxx-xxxxx/resourceGroups/xxxxx/providers/Microsoft.Compute/virtualMachines?api-version=2023-03-01&)$skiptoken=0408e537-0004-4f45-b0b2-59545b84cb90!/Subscriptions/xxxxxx-xxxx-xxxx-xxxx-xxxxx/ResourceGroups/xxxxx/VMs/C18999B7EF80-HFBE_ADC1368B&$filter='virtualMachineScaleSet/id' eq '/subscriptions/xxxxxx-xxxx-xxxx-xxxx-xxxxx/resourceGroups/xxxxx/providers/Microsoft.Compute/virtualMachineScaleSets/c18999b7ef80-hfbe'"
```
The error from the server is 
```
com.azure.core.exception.HttpResponseException: Status code 400, "<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01//EN""http://www.w3.org/TR/html4/strict.dtd">
<HTML><HEAD><TITLE>Bad Request</TITLE> <META HTTP-EQUIV="Content-Type" Content="text/html; charset=us-ascii"></HEAD> <BODY><h2>Bad Request</h2> <hr><p>HTTP Error 400. The request is badly formed.</p> </BODY></HTML>
```
Ps: the VMSS we use is VMSS flex.

Version:
```
<groupId>com.azure.resourcemanager</groupId>
<artifactId>azure-resourcemanager</artifactId>
<version>2.12.0</version>
```
Thanks

***Exception or Stack Trace***

**To Reproduce**
1. Create a VMSS with more than 50 VMs, say 70, this is to make the pagination happen.
2. Use the VM API to call list by resource group, with the vmss name as the `$filter`.
3. See the first page returned successfully, but the second page fails.

***Code Snippet***
Add the code snippet that causes the issue.

**Expected behavior**

**Screenshots**

**Setup (please complete the following information):**
```
            <groupId>com.azure.resourcemanager</groupId>
            <artifactId>azure-resourcemanager</artifactId>
            <version>2.12.0</version>
```

If you suspect a dependency version mismatch (e.g. you see `NoClassDefFoundError`, `NoSuchMethodError` or similar), please check out [Troubleshoot dependency version conflict article](https://aka.ms/azsdk/java/dependency/troubleshoot) first. If it doesn't provide solution for the problem, please provide:
- verbose dependency tree (`mvn dependency:tree -Dverbose`)
- exception message, full stack trace, and any available logs

**Additional context**

**Information Checklist**
Kindly make sure that you have added all the following information above and checkoff the required fields otherwise we will treat the issuer as an incomplete report
- [ ] Bug Description Added
- [ ] Repro Steps Added
- [ ] Setup information Added

**Comment by yumingqiao** [comment]
We experienced the similar issue in Golang SDK too, and it's fixed: https://github.com/Azure/azure-sdk-for-go/issues/21291

**Comment by joshfree** [comment]
@weidongxu-microsoft could you please take a look

**Comment by weidongxu-microsoft** [comment]
The `nextLink` is opaque, and should be fully encoded in response. CRP should have encoded the space around ` eq `.

**Comment by weidongxu-microsoft** [comment]
@yumingqiao You may also try 2.30.0

2.12.0 was more than 1 year old.

**Comment by yumingqiao** [comment]
@weidongxu-microsoft, both python SDK (Azure CLI uses) and go SDK validates and encodes the nextLink before sending out the request. They work fine.

Python SDK: https://sourcegraph.com/github.com/Azure/azure-sdk-for-python/-/blob/sdk/compute/azure-mgmt-compute/azure/mgmt/compute/v2022_11_01/operations/_operations.py?L16271
Go SDK: https://github.com/Azure/azure-sdk-for-go/blob/0c1dfe5e2c8f27f557e67b39ba8d74618533634d/sdk/azcore/runtime/pager.go#L112

**Comment by weidongxu-microsoft** [comment]
It is clearly documented that `nextLink` should be fully encoded by backend.
https://github.com/microsoft/api-guidelines/blob/vNext/azure/Guidelines.md#collections-include-nextlink-for-more-results

We need to hear from backend first. I don't want to take the risk that SDK accidently encode a parameter twice because a backend error.

**Comment by weidongxu-microsoft** [comment]
e.g. ARM is totally fine

```
  "nextLink" : "https://management.azure.com/subscriptions/faa080af-c1d8-40ad-9cce-e1a450ca5b57/resources?%24filter=resourceType+ne+%27Microsoft.Network%2fvirtualNetworks%27&%24top=5&api-version=2022-09-01&%24skiptoken=###"
```

**Comment by yumingqiao** [comment]
Hi @XiaofeiCao , could you take a look? This bug has caused us to use excessive VM quota, as we have to query all VMs from the resource group and filter by ourselves.

**Comment by yumingqiao** [comment]
@XiaofeiCao sounds good to me, thank you. What's the release ETA of this new method?

**Comment by XiaofeiCao** [comment]
> @XiaofeiCao sounds good to me, thank you. What's the release ETA of this new method?

Sure, next 2.31.0's release is around mid Sep.

**Comment by yumingqiao** [comment]
@XiaofeiCao Thank you for the effort, let me know once it's released.

**Comment by XiaofeiCao** [comment]
@yumingqiao 2.31.0 released with the fix.

**Comment by TravisCragg-MSFT** [comment]
reopening as this is still being worked on

**Comment by yumingqiao** [comment]
Hi @XiaofeiCao @TravisCragg-MSFT , we have switched to use this new API, and it seems working fine for us. Could you let us know what are we still working on in the above comment ^, is there anything we need to concern about? Thanks

**Comment by XiaofeiCao** [comment]
@yumingqiao Afaik, there's no further work scheduled for Java SDK.

@TravisCragg-MSFT Do you mean backend fix? Guess we can close this issue, since backend fix is tracked in another one: https://github.com/Azure/azure-rest-api-specs/issues/25640
