### ISSUE TITLE
Please clarify the fix suggested #30765 is applicable for azure-messaging-servicebus-7.8.0 SDK library

### ISSUE THREAD

**Issue by snarlagi** [Azure/azure-sdk-for-java#36525]
**Query/Question**
A clear and concise ask/query.

For the below comment mentioned by Varenya , can you please clarify if the fix suggested in the ticket is applicable for azure-messaging-servicebus-7.8.0 sdk jar.
https://github.com/Azure/azure-sdk-for-java/issues/30765#issuecomment-1244913476
_**"Need a clarification. Just wanted to know if this retry mechanism is part of azure-messaging-servicebus-7.8.0 as well or is it something implemented later in the latest version i.e 7.10.1"**_

We need the above information to backport the fix changes to application containing **azure-messaging-servicebus-7.8.0.jar** SDK library for a customer.

***Why is this not a Bug or a feature Request?***
A clear explanation of why is this not a bug or a feature request?

We have already have a fix suggested in another ticket. So, just want to have a clarification if the fix is applicable for older version azure-messaging-servicebus sdk jar.

**Setup (please complete the following information if applicable):**
 
OS: Windows
IDE: eclipse
Library/Libraries: [azure-messaging-servicebus]» 7.8.0 and its dependencies

 
 **Information Checklist**
 Kindly make sure that you have added all the following information above and checkoff the required fields otherwise we will treat the issuer as an incomplete report
- [Ticked off] Query Added
- [Ticked off] Setup information Added

**Comment by anuchandy** [comment]
@snarlagi - the logic of using default max-delay of 1 second and adding 4 seconds to min-delay were introduced way before 7.8.0. So, the recommendation is applicable for 7.8.0 version. 

Btw I suggest updating to latest version, since 7.8.0 is around 1.5 years old and there has been many reliability fixes since then.

**Comment by snarlagi** [comment]
Thanks for the confirmation. Please close the ticket.
