### ISSUE TITLE
[FEATURE REQ] Access to Azure Files with Active Directory

### ISSUE THREAD

**Issue by manuelesimi** [Azure/azure-sdk-for-java#36546]
**Is your feature request related to a problem? Please describe.**
I'm using Active Directory to manage authentication and access to my AZ resources. However, it seems that this is not possible with Azure Files. The configuration for this resource requires to use shared keys. I'm not sure if this behavior depends on the SDK or it's a broader constraint.

**Describe the solution you'd like**
I would like that the following class:
```java
com.microsoft.azure.batch.protocol.models.AzureFileShareConfiguration
```
does not require to pass the shared key with the `withAccountKey()`method.
The method should be optional, and if not invoked, the access to Azure Files should be delegated to AD.
Something similar to what is available for Batch accounts - `BatchCredentials` with three implementations, one for the keys (``BatchSharedKeyCredentials``), one for the application (``BatchApplicationTokenCredentials``) and one for the user (``BatchUserTokenCredentials``) - would be ideal.

**Describe alternatives you've considered**
I can use both AD and shared keys, but I'd prefer to be able to use only AD.

**Additional context**
This is the stack trace I get when I do not pass the shared key:
```java
Caused by:
  mountConfiguration.azureFileShareConfiguration.accountKey is required and cannot be null.

java.lang.IllegalArgumentException: mountConfiguration.azureFileShareConfiguration.accountKey is required and cannot be null.
    at com.microsoft.rest.Validator.validateClass(Validator.java:134)
    at com.microsoft.rest.Validator.validate(Validator.java:77)
    at com.microsoft.azure.batch.protocol.implementation.PoolsImpl.addWithServiceResponseAsync(PoolsImpl.java:812)
    at com.microsoft.azure.batch.protocol.implementation.PoolsImpl.add(PoolsImpl.java:758)
    at com.microsoft.azure.batch.PoolOperations.createPool(PoolOperations.java:461)
    at com.microsoft.azure.batch.PoolOperations.createPool(PoolOperations.java:436)
```

**Comment by joshfree** [comment]
@mario-guerra I believe you're working with the Azure Batch folks, could you please assist in routing?

**Comment by mario-guerra** [comment]
I'll check with the Batch team for guidance on how to proceed.

**Comment by mario-guerra** [comment]
Hi @manuelesimi, Azure Files currently only support authentication using storage account keys and does not support Azure Active Directory (AAD) authentication. This is unfortunately a limitation on the service side and is not on the roadmap for future development.

**Comment by manuelesimi** [comment]
Hi @mario-guerra, thanks for your ready investigation and reply.
I understand the issue (and somehow suspected it was inherited from the services). Hopefully this limitation can be remove in the future. I'll continue to use the hybrid authentication as workaround.

Thanks again!
