### ISSUE TITLE
Container Registry Readme Issue

### ISSUE THREAD

**Issue by faynef** [Azure/azure-sdk-for-java#36574]
1.
**Section**[ link](https://github.com/Azure/azure-sdk-for-java/blob/main/sdk/containerregistry/azure-containers-containerregistry/README.md):
<img width="380" alt="image" src="https://github.com/Azure/azure-sdk-for-java/assets/138087452/4bc223d7-3857-40b8-83df-075cecec708b">
**Reason**:
Error 404 after opening the link.

**Suggestion**:
Link change to: `https://central.sonatype.com/artifact/com.azure/azure-containers-containerregistry/1.1.2`.

@sandeep-sen, @joshfree, @mario-guerra, @pallavit and @alzimmermsft to notification.

**Comment by joshfree** [comment]
Thanks @v-xuto -- no need to open up github issues on each one of these individually; @alzimmermsft is fixing all the readme.md links that have changed with this mondo PR here: https://github.com/Azure/azure-sdk-for-java/pull/36637
