### ISSUE TITLE
Cognitive Search Samples Issue

### ISSUE THREAD

**Issue by faynef** [Azure/azure-sdk-for-java#36575]
1.
**Section** [link1](https://github.com/Azure/azure-sdk-for-java/blob/main/sdk/search/azure-search-documents/src/samples/java/com/azure/search/documents/ReadmeSamples.java#L147)：
<img width="249" alt="image" src="https://github.com/Azure/azure-sdk-for-java/assets/138087452/4fb9cbc5-df12-4e3a-ab7e-9fab3f48fefd">
**Reason:**
<img width="667" alt="image" src="https://github.com/Azure/azure-sdk-for-java/assets/138087452/6c4c3670-26c1-4d68-bffd-fa607266de97">
	Running the method pictured above gives an error:  Cannot construct instance of com.xsh.search.documents.ReadmeSamples$Hotel: non-static inner classes like this can only by instantiated using default, no-argument constructor.

**Suggestion：**
Update code to  `public static class Hotel `

2.
**Section** [link](https://github.com/Azure/azure-sdk-for-java/blob/main/sdk/search/azure-search-documents/src/samples/java/com/azure/search/documents/ReadmeSamples.java#L273):
<img width="684" alt="image" src="https://github.com/Azure/azure-sdk-for-java/assets/138087452/7e60dbd9-fd7f-4e4c-ae75-a9c7be060f59">

**Reason**:
com.azure.core.exception.HttpResponseException: Status code 400, "{"error":{"code":"OperationNotAllowed","message":"The request is invalid. Details: index : Found 0 key fields in index 'index'. Each index must have exactly one key field.","details":[{"code":"MissingKeyField","message":"Found 0 key fields in index 'index'. Each index must have exactly one key field. Parameters: index"}]}}"

**Suggestion**:
Update code to
```
List<SearchField> searchFieldList = new ArrayList<>();
searchFieldList.add(new SearchField("hotelId", SearchFieldDataType.STRING)
	                .setKey(true)
	                .setFilterable(true)
	                .setSortable(true));
SEARCH_INDEX_CLIENT.createIndex(new SearchIndex("index1", searchFields).setFields(searchFieldList));

```
3.
**Section** [link](https://github.com/Azure/azure-sdk-for-java/blob/main/sdk/search/azure-search-documents/src/samples/java/com/azure/search/documents/indexes/CreateIndexWithFieldBuilderExample.java#L33):
<img width="714" alt="image" src="https://github.com/Azure/azure-sdk-for-java/assets/138087452/b567e324-4282-4f3f-80f7-773709d84ee5">
**Reason**:
com.azure.core.exception.HttpResponseException: Status code 400, "{"error":{"code":"OperationNotAllowed","message":"The request is invalid. Details: index : Found 0 key fields in index 'index'. Each index must have exactly one key field.","details":[{"code":"MissingKeyField","message":"Found 0 key fields in index 'index'. Each index must have exactly one key field. Parameters: index"}]}}"

**Suggestion**:
Update code to
```
List<SearchField> searchFieldList = new ArrayList<>();
searchFieldList.add(new SearchField("hotelId", SearchFieldDataType.STRING)
	                .setKey(true)
	                .setFilterable(true)
	                .setSortable(true));
SearchIndex newIndex = new SearchIndex(indexName, indexFields)
	                .setFields(searchFieldList);
```
  @sandeep-sen, @joshfree, @achandmsft, @mayurid and @jairmyree to notification.

**Comment by jairmyree** [comment]
I'll work on this

**Comment by pallavit** [comment]
@jairmyree is this still a concern?

**Comment by jairmyree** [comment]
@pallavit This will be addressed in the Search Javadoc update PR

**Comment by jairmyree** [comment]
PR:
https://github.com/Azure/azure-sdk-for-java/pull/38184

**Comment by pallavit** [comment]
Thanks @jairmyree

**Comment by jairmyree** [comment]
Some of the changes might have been missed in the Search Javadoc update PR due to its size. I will re-assess the Samples to ensure adequate changes were made.
