### ISSUE TITLE
[BUG] Cannot invoke 'reactor.core.Disposable$Composite.dispose()' because 'this.subscriptions' is null

### ISSUE THREAD

**Issue by weidongxu-microsoft** [Azure/azure-sdk-for-java#36607]
**Describe the bug**
CX observing the following exception on application insights, since July 24. They've several exceptions like this per day.
![bbb](https://github.com/Azure/azure-sdk-for-java/assets/53292327/0539238d-e69a-4775-9452-d5dcdbe3dc8a)

***Exception or Stack Trace***
Add the exception log and stack trace if available

**To Reproduce**

***Code Snippet***
Add the code snippet that causes the issue.

**Expected behavior**

**Screenshots**

**Setup (please complete the following information):**
 - IDE: [e.g. IntelliJ]
 - Library/Libraries: azure-messaging-eventhubs:5.11.2
 - Java version: 17
 - App Server/Environment: Azure Function
 - Frameworks: [e.g. Spring Boot, Micronaut, Quarkus, etc] 

**Additional context**
CX is using Gradle with plugins and Java 17. 
 
``` 
dependencies {
       implementation "com.azure:azure-messaging-eventhubs:5.11.2"
}
```

Email thread "Cannot invoke 'reactor.core.Disposable$Composite.dispose()' because 'this.subscriptions' is null"

**Information Checklist**
Kindly make sure that you have added all the following information above and checkoff the required fields otherwise we will treat the issuer as an incomplete report
- [x] Bug Description Added
- [ ] Repro Steps Added
- [x] Setup information Added

**Comment by anuchandy** [comment]
Looking into this.

**Comment by anuchandy** [comment]
Closing, addressed in the linked pr.
