### ISSUE TITLE
I always get a null CompletionsUsage object when using the getChatCompletionsStream method of OpenAIClient in Azure SDK for Java.

### ISSUE THREAD

**Issue by WXCMYDEARMELAN** [Azure/azure-sdk-for-java#36605]
I saw the same problem in the issues, 
but I couldn't solve it according to the method mentioned by @mssfang.
I have reproduced this problem again.
 Could you help me solve it
 I would greatly appreciate it
Maven: 1.0.0-beta.2
`  

        OpenAIClient client = new OpenAIClientBuilder()
            .endpoint(endpoint)
            .credential(new AzureKeyCredential(azureOpenaiKey))
            .buildClient();

        List<ChatMessage> chatMessages = new ArrayList<>();
        chatMessages.add(new ChatMessage(ChatRole.USER).setContent("Can you help me?"));
        chatMessages.add(new ChatMessage(ChatRole.ASSISTANT).setContent("Of course, me hearty! What can I do for ye?"));
        chatMessages.add(new ChatMessage(ChatRole.USER).setContent("What's the best way to train a parrot?"));

        IterableStream<ChatCompletions> chatCompletionsStream = client.getChatCompletionsStream(deploymentOrModelId, new ChatCompletionsOptions(chatMessages));

        chatCompletionsStream.forEach(chatCompletions -> {
            for (ChatChoice choice : chatCompletions.getChoices()) {
                ChatMessage message = choice.getDelta();
                if (message != null) {
                    System.out.printf("Index: %d, Chat Role: %s.%n", choice.getIndex(), message.getRole());
                    System.out.println("Message:");
                    System.out.println(message.getContent());
                }
            }

            CompletionsUsage usage = chatCompletions.getUsage();
            if (usage != null) {
                System.out.printf("Usage: number of prompt token is %d, "
                        + "number of completion token is %d, and number of total tokens in request and response is %d.%n",
                    usage.getPromptTokens(), usage.getCompletionTokens(), usage.getTotalTokens());
            }
        });
    `

**Comment by WXCMYDEARMELAN** [comment]
> @WXCMYDEARMELAN is always nullable for Streaming Chat Completion API, which is an expected response. Also, will always be null when you use the [Bring-Your-Own-Data](https://learn.microsoft.com/en-us/azure/ai-services/openai/concepts/use-your-data) feature. You can check out the [sample](https://github.com/Azure/azure-sdk-for-java/blob/main/sdk/openai/azure-ai-openai/src/samples/java/com/azure/ai/openai/usage/GetChatCompletionsStreamSample.java#L32)`CompletionsUsage``CompletionsUsage`
> 
> BTW, I saw you are still using beta.2, We have released beta.4 recently. I would suggest using the latest version which fixes some issues in beta.2.

Thank you for your reply. I have listened to your method and used beta. 4, but I am not sure how to obtain the token for my stream request. Could you please let me know? Thank you very much

**Comment by mssfang** [comment]
> method and used b

Unfortunately, we don't support `token usage` or `tokenization` in the streaming chat completion(non-streaming chat completion has the token usage). We will consider renewing the investment in tokenization.

**Comment by mssfang** [comment]
> > @WXCMYDEARMELAN is always nullable for Streaming Chat Completion API, which is an expected response. Also, will always be null when you use the [Bring-Your-Own-Data](https://learn.microsoft.com/en-us/azure/ai-services/openai/concepts/use-your-data) feature. You can check out the [sample](https://github.com/Azure/azure-sdk-for-java/blob/main/sdk/openai/azure-ai-openai/src/samples/java/com/azure/ai/openai/usage/GetChatCompletionsStreamSample.java#L32)`` CompletionsUsage``CompletionsUsage ``
> > BTW, I saw you are still using beta.2, We have released beta.4 recently. I would suggest using the latest version which fixes some issues in beta.2.
> 
> @mssfang Thank you for your reply. I have listened to your method and used beta. 4, but I am not sure how to obtain the token for Streaming Request. This is not mentioned in the sample you provided Could you please let me know? Thank you very much

Unfortunately, we don't support token usage or tokenization in the streaming chat completion(non-streaming chat completion has the token usage). We will consider renewing the investment in tokenization.

**Comment by yanchuyu** [comment]
How to count tokens when using streaming API

**Comment by hcray** [comment]
I am using beta.6, How get CompletionsUsage use streaming API @mssfang

**Comment by mssfang** [comment]
@yanchuyu You can try out using an external library, [JTokkit](https://jtokkit.knuddels.de/docs/getting-started) for counting tokens. Also use this website for verify the number of tokens calculated from each streaming message: [OpenAI Tokenizer](https://platform.openai.com/tokenizer).

**Comment by mssfang** [comment]
> I am using beta.6, How get CompletionsUsage use streaming API @mssfang

@hcray There is no Completion Usage return from streaming chat completion. A sample of streaming data looks like below:
```

data: {"id":"chatcmpl-8gGa2cTICWaxbcUSzk3GsoKfMxEEk","object":"chat.completion.chunk","created":1705084202,"model":"gpt-3.5-turbo-0613","system_fingerprint":null,"choices":[{"index":0,"delta":{"content":" can"},"logprobs":null,"finish_reason":null}]}

data: {"id":"chatcmpl-8gGa2cTICWaxbcUSzk3GsoKfMxEEk","object":"chat.completion.chunk","created":1705084202,"model":"gpt-3.5-turbo-0613","system_fingerprint":null,"choices":[{"index":0,"delta":{"content":" support"},"logprobs":null,"finish_reason":null}]}

data: {"id":"chatcmpl-8gGa2cTICWaxbcUSzk3GsoKfMxEEk","object":"chat.completion.chunk","created":1705084202,"model":"gpt-3.5-turbo-0613","system_fingerprint":null,"choices":[{"index":0,"delta":{"content":" you"},"logprobs":null,"finish_reason":null}]}

data: {"id":"chatcmpl-8gGa2cTICWaxbcUSzk3GsoKfMxEEk","object":"chat.completion.chunk","created":1705084202,"model":"gpt-3.5-turbo-0613","system_fingerprint":null,"choices":[{"index":0,"delta":{"content":"."},"logprobs":null,"finish_reason":null}]}

data: {"id":"chatcmpl-8gGa2cTICWaxbcUSzk3GsoKfMxEEk","object":"chat.completion.chunk","created":1705084202,"model":"gpt-3.5-turbo-0613","system_fingerprint":null,"choices":[{"index":0,"delta":{},"logprobs":null,"finish_reason":"stop"}]}

data: [DONE]
```

There is no token usage return from the service side. We can only collect the token by self. You can try out using an external library, [JTokkit](https://jtokkit.knuddels.de/docs/getting-started) for counting tokens. Also use this website for verify the number of tokens calculated from each streaming message: [OpenAI Tokenizer](https://platform.openai.com/tokenizer).

**Comment by hcray** [comment]
> > I am using beta.6, How get CompletionsUsage use streaming API @mssfang
> 
> @hcray There is no Completion Usage return from streaming chat completion. A sample of streaming data looks like below:
> 
> ```
> 
> data: {"id":"chatcmpl-8gGa2cTICWaxbcUSzk3GsoKfMxEEk","object":"chat.completion.chunk","created":1705084202,"model":"gpt-3.5-turbo-0613","system_fingerprint":null,"choices":[{"index":0,"delta":{"content":" can"},"logprobs":null,"finish_reason":null}]}
> 
> data: {"id":"chatcmpl-8gGa2cTICWaxbcUSzk3GsoKfMxEEk","object":"chat.completion.chunk","created":1705084202,"model":"gpt-3.5-turbo-0613","system_fingerprint":null,"choices":[{"index":0,"delta":{"content":" support"},"logprobs":null,"finish_reason":null}]}
> 
> data: {"id":"chatcmpl-8gGa2cTICWaxbcUSzk3GsoKfMxEEk","object":"chat.completion.chunk","created":1705084202,"model":"gpt-3.5-turbo-0613","system_fingerprint":null,"choices":[{"index":0,"delta":{"content":" you"},"logprobs":null,"finish_reason":null}]}
> 
> data: {"id":"chatcmpl-8gGa2cTICWaxbcUSzk3GsoKfMxEEk","object":"chat.completion.chunk","created":1705084202,"model":"gpt-3.5-turbo-0613","system_fingerprint":null,"choices":[{"index":0,"delta":{"content":"."},"logprobs":null,"finish_reason":null}]}
> 
> data: {"id":"chatcmpl-8gGa2cTICWaxbcUSzk3GsoKfMxEEk","object":"chat.completion.chunk","created":1705084202,"model":"gpt-3.5-turbo-0613","system_fingerprint":null,"choices":[{"index":0,"delta":{},"logprobs":null,"finish_reason":"stop"}]}
> 
> data: [DONE]
> ```
> 
> There is no token usage return from the service side. We can only collect the token by self. You can try out using an external library, [JTokkit](https://jtokkit.knuddels.de/docs/getting-started) for counting tokens. Also use this website for verify the number of tokens calculated from each streaming message: [OpenAI Tokenizer](https://platform.openai.com/tokenizer).

Thank you for your reply. I will try it
