### ISSUE TITLE
[BUG]VM generation error obtaining image through sdk

### ISSUE THREAD

**Issue by ArtistLL123** [Azure/azure-sdk-for-java#36619]
There was an error in querying the VM generation of the image using Java sdk. As shown in the following figure:
![image](https://github.com/Azure/azure-sdk-for-java/assets/102207891/490aae12-90fd-4923-9de6-0ee54b4188ca)
The SDK returns a parameter of V1, but it is actually V2. Here is the resource JSON view:
![image](https://github.com/Azure/azure-sdk-for-java/assets/102207891/3bba63b0-5f77-477c-85a5-832f77cdfa50)

Please confirm the reason for this phenomenon, thank you.

**Comment by ArtistLL123** [comment]
This issue is very urgent at present. Is there any progress in the investigation?

**Comment by joshfree** [comment]
@weidongxu-microsoft could you please assist?

**Comment by weidongxu-microsoft** [comment]
@XiaofeiCao 

Probably a bug here
```java
    VirtualMachineCustomImageImpl(final String name, ImageInner innerModel, final ComputeManager computeManager) {
        super(name, innerModel, computeManager);
        // set the default value for the hyper-v generation
        this.innerModel().withHyperVGeneration(HyperVGenerationTypes.V1);
    }
```

If it is this simple problem, we should be able to have it in Sept. release.

**Comment by XiaofeiCao** [comment]
@ArtistLL123 2.31.0 released with the fix, feel free to try it out.
