### ISSUE TITLE
Add overload for logging exceptions

### ISSUE THREAD

**Issue by conniey** [Azure/azure-sdk-for-java#3661]
I'm using the ServiceLogger for EventHubs. They log errors a lot, and I find myself changing the code from:

`logger.error("Error Message", ioException);`
to
`logger.asError().log("Error Message: %s", ioException);`

It would be nice to provide an overload for logging `Throwable`.

**Comment by hemanttanwar** [comment]
@conniey  You should be able to use Throwable without specifying format i.e. %s
Thus closing this ticket as no code change is needed.
