### ISSUE TITLE
[QUERY] Is TLS/SSL hostname verification enabled when building HttpClient with NettyAsyncHttpClientBuilder?

### ISSUE THREAD

**Issue by chovyy** [Azure/azure-sdk-for-java#36627]
**Query/Question**
According to https://github.com/netty/netty/issues/9930 and https://github.com/netty/netty/issues/8537, TLS/SSL hostname verification is not enabled by default in native Netty. Is that in issue when building a `HttpClient` with `NettyAsyncHttpClientBuilder` or will host verification be enabled by this builder?

***Why is this not a Bug or a feature Request?***
It might become a Bug if the answer is "no".

**Setup (please complete the following information if applicable):**
 - Library/Libraries: com.azure:azure-core-http-netty
 
 **Information Checklist**
 Kindly make sure that you have added all the following information above and checkoff the required fields otherwise we will treat the issuer as an incomplete report
- [x] Query Added
- [x] Setup information Added

**Comment by melazrak** [comment]
Looks like this has been already answered here

https://github.com/Azure/azure-sdk-for-java/issues/18286#issuecomment-947958978

**Comment by chovyy** [comment]
Thanks a lot, and sorry that I wasn't able to find this myself.
