### ISSUE TITLE
[FEATURE REQ] Allow in CosmosFactory overrideContainerName to pass the original container name

### ISSUE THREAD

**Issue by fernyettheplant** [Azure/azure-sdk-for-java#36632]
**Is your feature request related to a problem? Please describe.**

I'm working at the moment to enable multi-tenancy capabilities to a Java Project with CosmosDB and we were planning to go tenant per container. Our project requires that a single tenant is owner of multiple containers but i have not found yet any example on how to enable it for such nor the capabilities to append the tenant instead of just having a single container per tenant

example, currently the tenant per container works with Spring Data works like this:
|Container Name|
|----------------|
|Tenant01 |
|Tenant02 |

However, we need to be able to do something like this:

|Container Name|
|----------------|
|EventStore-Tenant01 |
|Projection-Tenant01|
|EventStore-Tenant02 |
|Projection-Tenant02|

**Describe the solution you'd like**

I was checking the changes introduced in https://github.com/Azure/azure-sdk-for-java/pull/33400 and one improvement that would solve this problem is to allow the method `overrideContainerName` in `CosmosFactory` to pass the original container name so it can be manipulated where the tenant id can be appended.

An example of the usage would be like this:

```java
public class MultiTenantContainerCosmosFactory extends CosmosFactory {
    private final TenantStorage tenantStorage;

    public MultiTenantContainerCosmosFactory(
            CosmosAsyncClient cosmosAsyncClient, String databaseName, TenantStorage tenantStorage) {
        super(cosmosAsyncClient, databaseName);
        this.tenantStorage = tenantStorage;
    }

    @Override
    public String overrideContainerName(String originalContainerName) {
        String tenantId = tenantStorage.getCurrentTenant();
        if (tenantId != null) {
            this.tenantId = tenantId;
            return String.format("%s-%s", originalContainerName, tenantId);
        } else {
            return originalContainerName;
        }
    }
}
```

**Describe alternatives you've considered**

I was thinking on implement something similar from the ground up using the Azure CosmosDB SDK to allow this but honestly Spring Data solves this issue relatively easy,

**Additional context**

The only issue that i see with this proposition is that it would introduce breaking changes

**Information Checklist**
Kindly make sure that you have added all the following information above and checkoff the required fields otherwise we will treat the issuer as an incomplete report
- [x] Description Added
- [x] Expected solution specified

**Comment by trande4884** [comment]
However to achieve your goal by extending CosmosTemplate and overriding getContainerNameOverride like below, adding "containerName + ".
image
