### ISSUE TITLE
[BUG] Paging query fail

### ISSUE THREAD

**Issue by lynlich** [Azure/azure-sdk-for-java#36630]
**Describe the bug**
With azure-spring-data-cosmos:3.0.0 paging query for a group-by collection, and CosmosDB responsed an error "Invalidquery. Specified parameter name '@' is invalid. Parameter names should be in the format of symbol '@' followed by a valid identifier".
It seems something wrong with "Pagable" that need not @Param annotation.

***Code Snippet***
@Repository
public interface TsrBLockSdkPointRecordRepository extends CosmosRepository<TsrPointRecord,String> {
    @Query("select c.memberId, c.customerId, sum(c.point) as point  from c where c.direction = 100000000 and c.availablePoint>0 and c.invalidTime >= @startTime and c.invalidTime <= @endTime group by c.memberId, c.customerId")
    Page<TsrPointRecord> findRecordsByInvalidTime(@Param("startTime") long startTime, @Param("endTime") long endTime, Pageable pageable);
}

**Setup (please complete the following information):**
 - OS: Windows 11
 - IDE: IntelliJ
 - Library/Libraries: com.azure.azure-spring-data-cosmos:3.0.0

**Information Checklist**
Kindly make sure that you have added all the following information above and checkoff the required fields otherwise we will treat the issuer as an incomplete report
- [ ] Bug Description Added
- [ ] Repro Steps Added
- [ ] Setup information Added

**Comment by Netyyyy** [comment]
@kushagraThapar please take a look

**Comment by kushagraThapar** [comment]
@lynlich - can you please try on the latest version of the spring-data-cosmos library?
