### ISSUE TITLE
Checkstyle fix or suppress discussion thread

### ISSUE THREAD

**Issue by sima-zhu** [Azure/azure-sdk-for-java#3664]
I will list all the remaining checkstyle questions.

**Comment by sima-zhu** [comment]
Sample.java

**EmptyBlock**

**MissingSwitchDefault**

**MethodName**

**ConstantName**

**Comment by sima-zhu** [comment]
EmptyBlock:

- Samples.java: [1](https://github.com/Azure/azure-sdk-for-java/blob/master/storage/data-plane/src/test/java/com/microsoft/azure/storage/Samples.java#L315), [2](https://github.com/Azure/azure-sdk-for-java/blob/master/storage/data-plane/src/test/java/com/microsoft/azure/storage/Samples.java#L506)

**Comment by sima-zhu** [comment]
ConstantName:

- LoggingOptions: [1](https://github.com/Azure/azure-sdk-for-java/blob/4d5c1a84d8bbdfa2dd3103be6f1bb4880b79b4a7/storage/data-plane/src/main/java/com/microsoft/azure/storage/blob/LoggingOptions.java#L14)

MethodName:

-Samples.java: [1](https://github.com/Azure/azure-sdk-for-java/blob/master/storage/data-plane/src/test/java/com/microsoft/azure/storage/Samples.java#L690), [2](https://github.com/Azure/azure-sdk-for-java/blob/master/storage/data-plane/src/test/java/com/microsoft/azure/storage/Samples.java#L870), [3](https://github.com/Azure/azure-sdk-for-java/blob/master/storage/data-plane/src/test/java/com/microsoft/azure/storage/Samples.java#L921), [4](https://github.com/Azure/azure-sdk-for-java/blob/master/storage/data-plane/src/test/java/com/microsoft/azure/storage/Samples.java#L1276), [5](https://github.com/Azure/azure-sdk-for-java/blob/master/storage/data-plane/src/test/java/com/microsoft/azure/storage/Samples.java#L1354), [6](https://github.com/Azure/azure-sdk-for-java/blob/master/storage/data-plane/src/test/java/com/microsoft/azure/storage/Samples.java#L1396)

**Comment by rickle-msft** [comment]
* Empty block: I think it would be ok to add a System.out.println() of whatever value is available in those blocks to satisfy Checkstyle. Be sure to leave the comment that indicates it is just a generic way to process the response

* Switch default: I don't see any harm in adding a default that just throws an IllegalArgumentException

* This is a public constant, so we should suppress it

* These method names aren't actually used in code and are just meant to indicate what the samples are about. It's probably best to change them to satisfy Checkstyle to minimize exclusions.

**Comment by sima-zhu** [comment]
Thanks for all the info. The code got merged in. Closed the issue.
