### ISSUE TITLE
[BUG] Azure SDK appears to silently convert the object name "file." to "file"

### ISSUE THREAD

**Issue by danking** [Azure/azure-sdk-for-java#36674]
**Describe the bug**
When creating an object ending in `.`, the SDK instead creates an object without the `.`

**To Reproduce**
Unless I'm mistaken, the following scala code should not have an assertion failure.
```scala
import com.azure.identity.DefaultAzureCredentialBuilder
import com.azure.storage.blob.BlobServiceClientBuilder
import com.azure.storage.blob.specialized.BlockBlobClient
import scala.collection.JavaConverters._

// You will need to modify these to an account and container you control
val account = "haildevtest"
val container = "test"

val objectName = "folder/file."

val credential = new DefaultAzureCredentialBuilder().build()
val bsc = (new BlobServiceClientBuilder()
    .credential(credential)
    .endpoint(s"https://${account}.blob.core.windows.net")
    .buildClient())
val bcc = bsc.getBlobContainerClient(container)
val bc = bcc.getBlobClient(objectName)
val bbc = bc.getBlockBlobClient
bbc.getBlobOutputStream(true).close() // ensure the object is created

val arr = bcc.listBlobsByHierarchy("folder/").iterator.asScala.toArray
val actualObjectName = arr(0).getName
assert(actualObjectName == objectName, actualObjectName)
```

My build.gradle dependencies look like this:
```groovy
dependencies {
    implementation group: 'com.azure', name: 'azure-storage-blob', version: '12.22.0'
    implementation group: 'com.azure', name: 'azure-core-http-netty', version: '1.13.3'
    implementation group: 'com.azure', name: 'azure-identity', version:'1.8.3'
}
```

**Expected behavior**
I expect to be able to create a blob with the name `file.`.

**Setup (please complete the following information):**
 - OS: macOS 13.5.1 `Darwin wm28c-761 22.6.0 Darwin Kernel Version 22.6.0: Wed Jul  5 22:22:05 PDT 2023; root:xnu-8796.141.3~6/RELEASE_ARM64_T6000 arm64`
 - IDE: None.
 - Library/Libraries: See above gradle snippet.
 - Java version: 1.8.0_352 `OpenJDK Runtime Environment (Temurin)(build 1.8.0_352-b08)`
 - App Server/Environment: None.
 - Frameworks: NOne.

**Information Checklist**
Kindly make sure that you have added all the following information above and checkoff the required fields otherwise we will treat the issuer as an incomplete report
- [x] Bug Description Added
- [x] Repro Steps Added
- [x] Setup information Added

**Comment by alzimmermsft** [comment]
Thank you for asking this question @danking.

Stripping of the trailing dot in file names is a service behavior that is determined based on a request header `x-ms-allow-trailing-dot`, which is false by default (https://learn.microsoft.com/rest/api/storageservices/create-file#request-headers). There is also `x-ms-source-allow-trailing-dot` for copy operations (https://learn.microsoft.com/rest/api/storageservices/copy-file#request-headers).

This functionality was GA'd in more recent versions of `azure-storage-file-share` and is configured by setting `allowTrailingDot`, and `allowSourceTrailingDot` on client builders.

**Comment by danking** [comment]
Thanks for the correction! I’m intensely curious _why_ this is the behavior but I guess I’ll close this issue as “works as intended”. Thanks!
