### ISSUE TITLE
java.lang.IllegalStateException: Client is currently closed. Must open messagingClient before sending.

### ISSUE THREAD

**Issue by vrmupparaju** [Azure/azure-sdk-for-java#36684]
Version Azure java sdk : 'com.microsoft.azure.sdk.iot:iot-service-client:2.1.6'

Below errors were triggering when I try to send messages to cloud

java.lang.IllegalStateException: Client is currently closed. Must open messagingClient before sending.

below is the code

if(!messagingClient.isOpen()) {
                    messagingClient.open();
                    messageToSend.setDeliveryAcknowledgement(DeliveryAcknowledgement.None);
                    messagingClient.sendAsync(deviceId, messageToSend, null, null);
                   
                }

tried with send(deviceId,message) ,same issues occurs

**Comment by anuchandy** [comment]
Hi @vrmupparaju - The library "com.microsoft.azure.sdk.iot:iot-service-client" is not hosted in the azure-sdk-for-java repo. Please open the ticket in the repo https://github.com/Azure/azure-iot-sdk-java, so that correct owners can help you. thanks!
