### ISSUE TITLE
[QUERY] RequestRetryOptions seems did not work at the SpringBoot

### ISSUE THREAD

**Issue by kensinzl** [Azure/azure-sdk-for-java#36689]
**Query/Question**
My app is SpringBoot 3.1.0 and the package is using spring cloud azure.

```
<dependency>
           <groupId>com.azure.spring</groupId>
            <artifactId>spring-cloud-azure-starter-storage-blob</artifactId>
            <version>5.5.0</version>
</dependency>
```

- This Java app uses multiple threads to upload images(jpeg, png) into Azure Blob Storage. Each thread is uploading one image, but I face intermittently upload timeout.
- how to justify when there is a timeout,  I set the timeout as 30 seconds because I think it should not be over 30 seconds to upload a tiny image. Please see my following attached code.
- In order to cushion this timeout issue, I want to use the re-try logic to failover if over 30 seconds

***Why is this not a Bug or a feature Request?***
Now I have already introduced a re-try logic as the following code, but I CAN NOT see the re-try log record when I intentionally make the image upload timeout into a quite small value eg: 10 ms, and the re-try account is 3, but I can not see three-times re-try execution log!

```
    @Bean
    public BlobServiceClient getBlobServiceClient() {
        RequestRetryOptions requestRetryOptions = new RequestRetryOptions(RetryPolicyType.EXPONENTIAL, 3, 1, 10000L, 20000L, null);

        return new BlobServiceClientBuilder().
                retryOptions(requestRetryOptions).
                connectionString("******").buildClient();

    }

    @Async("taskExecutor")
    public CompletableFuture<String> migrateImageToAzureStorage(Image image, BlobContainerClient forecastOrObsContainer, byte[] imageData) {

        String imageAzureBlobName = image.getImageId().toString() + guessFileExtension(imageData);
        try {
            BlobClient blobClient = forecastOrObsContainer.getBlobClient(imageAzureBlobName);

            try (ByteArrayInputStream imageStream = new ByteArrayInputStream(imageData)) {
                blobClient.uploadWithResponse(new BlobParallelUploadOptions(imageStream).setTier(AccessTier.HOT).setRequestConditions(new BlobRequestConditions()),
                        Duration.ofMillis(10ms),
                        Context.NONE);
                LogUtil.info("Uploaded Image "+image.getImageId()+" to Azure Blob Storage HOT Tier as " + blobClient.getBlobUrl());
            }

            image.setObjectStoreUrl(blobClient.getBlobName());

            return CompletableFuture.completedFuture(blobClient.getBlobName());
        } catch (IOException e) {
            LogUtil.error("Failed for closing stream when UPLOAD image "+image.getImageId()+" for Azure as "+imageAzureBlobName, e);
        } catch (IllegalStateException e) {
            LogUtil.error("Timeout for UPLOADING image "+image.getImageId()+" for Azure ", e);
        } catch (Exception e) {
            LogUtil.error("Failed for uploading image "+image.getImageId()+" for Azure ", e);
        }

        // return a failed future
        CompletableFuture<String> failedFuture = new CompletableFuture<>();
        failedFuture.completeExceptionally(new MigrationException("Failed for uploading image "+image.getImageId()+" for Azure "));
        return failedFuture;
    }
```

**Setup (please complete the following information if applicable):**
 - IDE: [e.g. IntelliJ]

 
 **Information Checklist**
 Kindly make sure that you have added all the following information above and checkoff the required fields otherwise we will treat the issuer as an incomplete report
- [x] Query Added
- [x] Setup information Added

**Comment by kensinzl** [comment]
@alzimmermsft 

Thanks for your details explanation. 

I removed the timeout setting from BlobClient and assigned it to the RequestRetryOptions. Now it works and the following is the sudo code, Please have a look.

But may I check with you about several things

- Could you please share some official documents to describe the timeout difference between among BlobClient and RequestRetryOptions?
- I may miss something because I found it hard to catch the azure upload timeout exception after running out of re-try count, eg: what is the particular exception type, so I have to use a crude way to match the exception string which you can see it among my code
- Seems I have to add the HttpLogOptions to let the azure related logs be represented, eg: the following logs
seems I have to fetch out these logs with "az.sdk.message", but I still will miss some part, eg: the second log, in this instance, is there any way I can use to fetch all these logs in one time?

```
{"@timestamp":"2023-09-12T02:24:29.712Z","ecs.version":"1.2.0","log.level":"INFO","message":"{\"az.sdk.message\":\"HTTP request\",\"method\":\"PUT\",\"url\":\"https://host.blob.core.windows.net/forecastimage/1565385274.jpeg\",\"tryCount\":\"3\",\"contentLength\":236608141}","process.thread.name":"parallel-4","log.logger":"com.azure.storage.blob.implementation.BlockBlobsImpl$BlockBlobsService.upload"}

{"@timestamp":"2023-09-12T02:24:33.717Z","ecs.version":"1.2.0","log.level":"WARN","message":"[id: ***********, L:/********:***** - R:host.blob.core.windows.net/********:*****] Last write attempt timed out; force-closing the connection.","process.thread.name":"reactor-http-kqueue-3","log.logger":"io.netty.handler.ssl.SslHandler"}
```

```
    @Bean
    public BlobServiceClient getBlobServiceClient() {
        RequestRetryOptions requestRetryOptions = new RequestRetryOptions(RetryPolicyType.FIXED, retryMaxCount, tryTimeoutInMs/1000, retryDelayInMs, maxRetryDelayInMs, null);

        HttpLogOptions httpLogOptions = new HttpLogOptions().setLogLevel(HttpLogDetailLevel.BASIC);

        BlobServiceClient blobServiceClient =
                new BlobServiceClientBuilder().httpLogOptions(httpLogOptions).retryOptions(requestRetryOptions).connectionString(connectStr).buildClient();

        return blobServiceClient;
    }


    @Async("taskExecutor")
    public CompletableFuture<String> migrateImageToAzureStorage(Image image, BlobContainerClient forecastOrObsContainer, byte[] imageData) {

        String imageAzureBlobName = image.getImageId().toString() + guessFileExtension(imageData);

        // record the size of each image and represent at the log
        double imageSizeInMB = imageData.length / 1024.0 / 1024.0;

        try {
            BlobClient blobClient = forecastOrObsContainer.getBlobClient(imageAzureBlobName);

            try (ByteArrayInputStream imageStream = new ByteArrayInputStream(imageData)) {
                blobClient.uploadWithResponse(new BlobParallelUploadOptions(imageStream).setTier(AccessTier.HOT).setRequestConditions(new BlobRequestConditions()),
                        null,
                        Context.NONE);
                LogUtil.info("Uploaded Image "+image.getImageId()+", Size(MB): " +imageSizeInMB+" to Azure Blob Storage HOT Tier as " + blobClient.getBlobUrl());
            }

            image.setObjectStoreUrl(blobClient.getBlobName());

            return CompletableFuture.completedFuture(blobClient.getBlobName());
        } catch (IOException e) {
            LogUtil.error("Failed for closing stream when UPLOAD image "+image.getImageId()+", Size(MB): " +imageSizeInMB+ " for Azure as "+imageAzureBlobName, e);
        } catch (Exception e) {
            // crude way to check the azure blob upload timeout exception
            if(e.getMessage().contains("Did not observe any item or terminal signal within ")) {
                LogUtil.error("Timeout for UPLOADING image "+image.getImageId()+", Size(MB): " +imageSizeInMB+" for Azure ", e);
            } else {
                LogUtil.error("Exception happened during uploading image "+image.getImageId()+", Size(MB): " +imageSizeInMB+" for Azure ", e);
            }
        }

        // return a failed future
        CompletableFuture<String> failedFuture = new CompletableFuture<>();
        failedFuture.completeExceptionally(new MigrationException("Failed for uploading image "+image.getImageId()+", Size(MB): " +imageSizeInMB+" for Azure "));
        return failedFuture;
    }

```

**Comment by kensinzl** [comment]
@alzimmermsft could you please have a look for the above message when you feel available, thank you so much.

**Comment by alzimmermsft** [comment]
> Could you please share some official documents to describe the timeout difference between among BlobClient and RequestRetryOptions?

This is something that wasn't well documented and I'm working on adding this in a few places. So far, I have a PR opened adding this documentation to `azure-core`'s README: https://github.com/Azure/azure-sdk-for-java/pull/36710/files#diff-b8dc45bc6fad5f70e59b49cda551e56ae6668c49fa0fd026c09b74537b9abed1R161

@ibrahimrabab could you look at porting this documentation to the Storage READMEs as well?
@JonathanGiles where is the best place to put documentation like this in https://learn.microsoft.com/en-us/azure/developer/java/sdk/?

> I may miss something because I found it hard to catch the azure upload timeout exception after running out of re-try count, eg: what is the particular exception type, so I have to use a crude way to match the exception string which you can see it among my code

Thanks for making note of this, looking at this it's a bit tricky and something the SDKs need to clean up. Depending on the timeout that triggered different exceptions will be thrown.

If the timeout happened at the `apiCall(Duration timeout)` level it will throw an `IllegalStateException`. If the timeout happened at the `HttpPipeline` or `HttpClient` layer it will throw a `TimeoutException`.

For the purposes of your application as you removed the usage of the `apiCall(Duration timeout)` I'd check for `TimeoutException`.

@JonathanGiles @srnagar @lmolkova we should do a review on the exceptions thrown in timeout scenarios to make sure they are standardized.

> Seems I have to add the HttpLogOptions to let the azure related logs be represented, eg: the following logs
seems I have to fetch out these logs with "az.sdk.message", but I still will miss some part, eg: the second log, in this instance, is there any way I can use to fetch all these logs in one time?

I don't fully understand the question about fetching all the logs at one time. If you're asking how to fetch all Azure SDK logs I would recommend doing that based on the `log.logger` included in the log and look for `com.azure.*` loggers.

**Comment by JonathanGiles** [comment]
> This is something that wasn't well documented and I'm working on adding this in a few places. So far, I have a PR opened adding this documentation to `azure-core`'s README: https://github.com/Azure/azure-sdk-for-java/pull/36710/files#diff-b8dc45bc6fad5f70e59b49cda551e56ae6668c49fa0fd026c09b74537b9abed1R161
> 
> @ibrahimrabab could you look at porting this documentation to the Storage READMEs as well? @JonathanGiles where is the best place to put documentation like this in https://learn.microsoft.com/en-us/azure/developer/java/sdk/?

I'll ping you this week to discuss Alan - but generally speaking this seems like good content for the troubleshooting push I'm doing over at learn.microsoft.com

> @JonathanGiles @srnagar @lmolkova we should do a review on the exceptions thrown in timeout scenarios to make sure they are standardized.

@alzimmermsft Please file an issue and start the ball rolling on this! Loop us in ASAP.

**Comment by kensinzl** [comment]
@JonathanGiles @alzimmermsft 

Thank you so much for the detailed information and your valuable time.

**Comment by ibrandes** [comment]
Closed, question was answered, and documentation was updated to be clearer.
