### ISSUE TITLE
[BUG] Error deleting Table Entity with empty rowkey

### ISSUE THREAD

**Issue by maheshnapte** [Azure/azure-sdk-for-java#36690]
**Bug Description:**
We are using azure-data-tables-12.3.14 library but getting issue in deleteting table entity with empty rowkey. This was allowed operation in older 8.6.6 library.
As per the document https://learn.microsoft.com/en-us/rest/api/storageservices/Designing-a-Scalable-Partitioning-Strategy-for-Azure-Table-Storage, empty stiring is permited for rowkey and partitionkey.

**Exception:**
2023-09-11 11:46:47.212 ERROR [           main]  com.azure.data.tables.TableClient        [MsgID=] : 'partitionKey' and 'rowKey' cannot be null 

**To Reproduce**
1. Add row in table storage with empty rowkey.
2. try to delete is using the method 
`public Response<Void> deleteEntityWithResponse(TableEntity entity, boolean ifUnchanged, Duration timeout, Context context)` avilable in the library.
3. The exception provided in the Exception section of this bug will be reproduced

***Code Snippet***
    private Response<Void> deleteEntityWithResponse(String partitionKey, String rowKey, String eTag, boolean ifUnchanged,
                                            Duration timeout, Context context) {
        Context contextValue = TableUtils.setContext(context, true);
        OptionalLong timeoutInMillis = TableUtils.setTimeout(timeout);

        String finalETag = ifUnchanged ? eTag : "*";

        if (isNullOrEmpty(partitionKey) || isNullOrEmpty(rowKey)) {
            throw logger.logExceptionAsError(new IllegalArgumentException("'partitionKey' and 'rowKey' cannot be null"));
        }

        Callable<Response<Void>> callable = () -> tablesImplementation.getTables().deleteEntityWithResponse(
            tableName, TableUtils.escapeSingleQuotes(partitionKey), TableUtils.escapeSingleQuotes(rowKey), finalETag, null,
            null, null, contextValue);

        try {
            return timeoutInMillis.isPresent()
                ? THREAD_POOL.submit(callable).get(timeoutInMillis.getAsLong(), TimeUnit.MILLISECONDS)
                : callable.call();
        } catch (Exception ex) {
            Throwable except = mapThrowableToTableServiceException(ex);
            return swallow404Exception(except);
        }
    }
    
**Expected behavior**
The exeption should not be thrown while deleting a row from the azure table storage with empty partitionKey and rowKey
row.
<img width="695" alt="image" src="https://github.com/Azure/azure-sdk-for-java/assets/22556035/cac9ff60-67ac-4c9e-9788-faf13ba74003">

**Setup:**
 - OS: [Windows 11]
 - IDE: [Spring Toool Suite]
 - Library/Libraries: [com.azure:azure-data-tables:12.3.14 (groupId:artifactId:version)]
 - Java version: [17] 
 - App Server/Environment: [Tomcatl]
 - Frameworks: [Spring Boot] 

**Additional context**

**Information Checklist**
Kindly make sure that you have added all the following information above and checkoff the required fields otherwise we will treat the issuer as an incomplete report
- [x] Bug Description Added
- [x] Repro Steps Added
- [x] Setup information Added

**Comment by joshfree** [comment]
@jairmyree could you please follow up with @maheshnapte

**Comment by jairmyree** [comment]
@maheshnapte Thank you for reaching out, I'll take a look at this and respond soon.
