### ISSUE TITLE
[BUG] supportedAggregationTypes field in the MetricDefinition is always null

### ISSUE THREAD

**Issue by matvey-mtn** [Azure/azure-sdk-for-java#36698]
**Describe the bug**
`com.azure.monitor.query.MetricsQueryClient#listMetricDefinitions(java.lang.String)` returns list of `MetricDefinition` objects with supportedAggregationTypes null in each definition

***Exception or Stack Trace***
There's no stack trace or error during execution

**To Reproduce**

```kotlin
val metricsQueryClient = MetricsQueryClientBuilder()
        .credential(clientSecretCredential)
        .buildClient()
        
val metricDefinitions = metricsQueryClient.listMetricDefinitions("resourceName")
        .filter { it.supportedAggregationTypes != null }
        .toList()
    
assertThat(metricDefinitions).isEmpty()
```

***Code Snippet***
Added above 👆🏻 

**Expected behavior**
Metric Definition list API documentation states it should return a list of supported aggregations in response:
https://learn.microsoft.com/en-us/rest/api/monitor/metric-definitions/list?tabs=HTTP

I expect to receive it in mentioned object.

**Screenshots**
I've debugged the code and it looks like internal definition response contains the desired list.
However there is a bug in line 183.

![image](https://github.com/Azure/azure-sdk-for-java/assets/25157189/584e57ec-4ae9-4341-91d9-8ffa5ee69bdb)

You can see the evaluation results under the code in screenshot:
`definition.supportedAggregationTypes.size -> 1`
and `CoreUtils.isNullOrEmpty(definition.getSupportedAggregationTypes()) -> false`

**Setup (please complete the following information):**
 - OS: MacOS
 - IDE: IntelliJ
 - Library/Libraries: `com.azure:azure-monitor-query:1.3.0-beta.1`
 - Java version: 8
 - App Server/Environment: local environment
 - Frameworks: none

**Information Checklist**
Kindly make sure that you have added all the following information above and checkoff the required fields otherwise we will treat the issuer as an incomplete report
- [x] Bug Description Added
- [x] Repro Steps Added
- [x] Setup information Added

**Comment by joshfree** [comment]
@jairmyree PTAL

**Comment by matvey-mtn** [comment]
@jairmyree any updates on this? I've opened a Pull Requests with a fix. I will appreciate your feedback 🙁

**Comment by jairmyree** [comment]
@matvey-mtn Thank you for reaching out. I was out-of-office for a few days, sorry for the delay in response. I'll take a look at the issue and get back to your shortly.

**Comment by jairmyree** [comment]
@matvey-mtn I've assigned myself to your PR and I'll review it soon.

**Comment by jairmyree** [comment]
@matvey-mtn I've reviewed your PR. Please see and review the CLA agreement notice on your PR.
