### ISSUE TITLE
Incorrect usage of external dependency boms?

### ISSUE THREAD

**Issue by MT-Jacobs** [Azure/azure-sdk-for-java#36718]
**Query/Question**
The Azure SDK appears to set (or list) the versions of its netty dependencies line by line in this file:

https://github.com/Azure/azure-sdk-for-java/blob/8b17067ff98eb0a5bbfb7ada8a664d4aa272ff09/sdk/spring/scripts/spring_boot_2.7.14_managed_external_dependencies.txt#L393-L429

rather than by importing the bom and relying on the bom to set the versions.

Is this intentional, or is it possible that the bom is being misused here? Notably, I don't think that `netty-bom` is actually being used elsewhere in the code, it's just a listed item that _might_ be used one day.

By comparison, [here's](https://github.com/micronaut-projects/micronaut-platform/blob/2960dae/gradle/libs.versions.toml#L170) one place in Micronaut where they directly use the junit-bom to set the version of junit dependencies

***Why is this not a Bug or a feature Request?***
This isn't a feature request because I am not asking for changes yet. It's not a bug because if you guys are doing this intentionally, it's..well, not a bug.

**Setup (please complete the following information if applicable):**
N/A
 
 **Information Checklist**
 Kindly make sure that you have added all the following information above and checkoff the required fields otherwise we will treat the issuer as an incomplete report
- [X] Query Added
- [X] Setup information Added - Though N/A

**Comment by Netyyyy** [comment]
Hi @MT-Jacobs , thanks for asking.
This file is to list the versions managed by Spring Boot for updating, not used as a bom.

**Comment by Netyyyy** [comment]
please reopen it if you have any other questions
