### ISSUE TITLE
[Question]: What's causing these Metadata Request spikes?

### ISSUE THREAD

**Issue by fivetran-kevinzhao** [Azure/azure-sdk-for-java#36742]
**Query/Question**
We are seeing the following pattern with regard to Metadata requests hitting the Cosmos instance. Notice huge spikes occurring every 6 hours or so. From our investigation, we don't have any processes running at a 6-hour cadence hitting this Cosmos instance. We are not sure what could be causing these metadata request spikes. So please advice. 

For background, we are using a singleton CosmosClient. The Cosmos instance itself has over 200TB of data in storage. 

![6hourspikes](https://github.com/Azure/azure-sdk-for-java/assets/92001263/c8b5102b-d36e-4aca-be6d-e3ca3c437379)

***Why is this not a Bug or a feature Request?***
This is most likely an intended function within Cosmos where the Metadata requests is being consumed by Cosmos infrastructure itself. I did a test by creating a fresh Cosmos instance with no connection to any applications or clients. There seems to be a steady rate of Metadata requests with occasional spikes despite having 0 clients making any requests to the instance. See following graph:
![image](https://github.com/Azure/azure-sdk-for-java/assets/92001263/09297c87-1362-4d90-9284-37eb32afdf66)

**Setup (please complete the following information if applicable):**
 - OS: Linux
 - IDE: IntelliJ
 - Library/Libraries: Java azure-cosmos:4.39
 
 **Information Checklist**
 Kindly make sure that you have added all the following information above and checkoff the required fields otherwise we will treat the issuer as an incomplete report
- [ ] Query Added
- [x] Setup information Added

**Comment by kushagraThapar** [comment]
@fivetran-kevinzhao - Apologies for the delayed response. 

You are correct, these are internal requests that are used by Cosmos DB infrastructure internally. These requests are proactively checking consistency across accounts and preventing any future issues that could arise. There is some work going on to make them transparent in customer telemetry data as these don't affect your application in any way. Feel free to re-open this issue if you have any further questions.
