### ISSUE TITLE
[FEATURE REQ] azure-resourcemanager-containerinstance Native Support

### ISSUE THREAD

**Issue by JakobStadlhuber** [Azure/azure-sdk-for-java#36755]
**Is your feature request related to a problem? Please describe.**
I am working on building an application with `com.azure.resourcemanager.containerinstance` and am trying to get native support for Spring Native with GraalVM. However, the native compilation requires explicit hints to work properly, and manually adding them is cumbersome.

**Describe the solution you'd like**
It would be immensely helpful if the `com.azure.resourcemanager.containerinstance` had native support for Spring Native with GraalVM out of the box. This would streamline the development process and enable users to more easily compile applications to native images.

**Describe alternatives you've considered**
I tried to use the `@ImportRuntimeHints` and manually added hints for proxies as described in my code snippet below. However, this process is tedious, and I was unsure about how many hints would be needed to cover all use cases.

**Additional context**

```kotlin
ImportRuntimeHints(AzureResourceManagerImpl.Companion::class)
....
companion object: RuntimeHintsRegistrar {
    override fun registerHints(hints: RuntimeHints, classLoader: ClassLoader?) {
        hints.proxies().registerJdkProxy(com.azure.resourcemanager.containerinstance.implementation.ContainerGroupsClientImpl.ContainerGroupsService::class.java)
....        hints.proxies().registerJdkProxy(com.azure.resourcemanager.resources.implementation.FeaturesClientImpl.FeaturesService::class.java)
    }
}
```

**Information Checklist**
- [x] Description Added
- [x] Expected solution specified

**Comment by joshfree** [comment]
@saragluna @weidongxu-microsoft could you please take a look?

**Comment by weidongxu-microsoft** [comment]
Thanks @JakobStadlhuber

As large part of the code is generated, we should be able to also generate the aot.hint. We probably need to have internal discussion first about how many is required (thinking of the other class that might need ReflectionHints, as they are used by Jackson via reflection).

FYI @srnagar

**Comment by JakobStadlhuber** [comment]
> Thanks @JakobStadlhuber
> 
> As large part of the code is generated, we should be able to also generate the aot.hint. We probably need to have internal discussion first about how many is required (thinking of the other class that might need ReflectionHints, as they are used by Jackson via reflection, as well as some Exception class by core).
> 
> And should we generate a graalvm proxy-config.json and reflect-config.json instead.
> 
> FYI @srnagar

sounds amazing, i am looking forward for the update.

**Comment by srnagar** [comment]
@weidongxu-microsoft we have an issue tracking this feature request to generate native image configuration files - 
https://github.com/Azure/azure-sdk-for-java/issues/33690

**Comment by weidongxu-microsoft** [comment]
We probably need configures similar to below, in this containerinstance (and its dependencies like resources lib) as well as azure-core-management lib
https://github.com/Azure/azure-sdk-for-java/blob/main/sdk/keyvault/azure-security-keyvault-keys/src/main/resources/META-INF/native-image/com.azure/azure-security-keyvault-keys/

**Comment by JakobStadlhuber** [comment]
> We probably need configures similar to below, for this containerinstance (and its dependencies like resources lib) as well as azure-core-management lib
> 
> https://github.com/Azure/azure-sdk-for-java/tree/main/sdk/storage/azure-storage-blob/src/main/resources/META-INF/native-image/com.azure/azure-storage-blob

That sounds exactly what we need. I can also confirm that azure-core-management works in native.

**Comment by weidongxu-microsoft** [comment]
We've made a prototype working here https://github.com/Azure/autorest.java/issues/2312#issuecomment-1726801640

It is pretty premilitary. If you need to get unblocked, you are welcome to try the META-INF configure there.

For formal support, these META-INF will be included in the packages like azure-resourcemanager-containerinstance

**Comment by XiaofeiCao** [comment]
Spring verfication in: https://github.com/XiaofeiCao/az-java-sdk-graalvm-spring

/cc @saragluna

**Comment by weidongxu-microsoft** [comment]
- https://github.com/Azure/azure-sdk-for-java/pull/36965
- https://github.com/Azure/azure-sdk-for-java/pull/37195

**Comment by weidongxu-microsoft** [comment]
2.26.0 release in Feb. should have the whole azure-resourcemanager lib supports native-image (azure-resourcemanager-containerinstance should already be good a few releases ago)

Test is good with azure-resourcemanager lib: https://github.com/weidongxu-microsoft/az-java-sdk-graalvm/pull/1
![image](https://github.com/Azure/azure-sdk-for-java/assets/53292327/98fb0565-0bd4-4690-a2a0-57b179f79d28)

However the build takes lots of time, so it probably best to limit the lib to those strictly required.

**Comment by weidongxu-microsoft** [comment]
2.26.0 released
