### ISSUE TITLE
[Question] ServiceBusSessionManager : Error occurred while getting unnamed session.

### ISSUE THREAD

**Issue by rajivroypcc** [Azure/azure-sdk-for-java#36772]
**Describe the bug**
Error receiving messages from ServiceBus using Session Based Queues.
2 exceptions : mentioned below.

***Exception or Stack Trace***
<html>
<body>

ReceiveLinkHandler : {"az.sdk.message":"onLinkRemoteClose","connectionId":"MF_02d4ba_1694724225431","errorCondition":"com.microsoft:timeout","errorDescription":"The operation did not complete within the allotted timeout of 00:00:59. The time allotted to this operation may have been a portion of a longer timeout. For more information on exception types and proper exception handling, please refer to https://aka.ms/ServiceBusExceptions . TrackingId:dd792c54-fcc2-4691-b760-6c09d0649c79_B30, SystemTracker:G27:703208122:session-_9cf776_1694724996554, Timestamp:2023-09-14T20:57:35 TrackingId:5b4a67d3ded6471e832b05536c84ff1c_G27, SystemTracker:gateway7, Timestamp:2023-09-14T20:57:35","linkName":"session-_9cf776_1694724996554","entityPath":"ehi-queue"}

ServiceBusSessionManager : {"az.sdk.message":"Error occurred while getting unnamed session.","exception":"The operation did not complete within the allotted timeout of 00:00:59. The time allotted to this operation may have been a portion of a longer timeout.
--

</body>
</html>

***Code Snippet***

        <dependency>
            <groupId>com.azure</groupId>
            <artifactId>azure-messaging-servicebus</artifactId>
            <version>7.14.3</version>
        </dependency>

    fun sessionReceiverClient(): ServiceBusSessionReceiverAsyncClient {
        return ServiceBusClientBuilder()
            .connectionString(connectionString)
            .retryOptions(AmqpRetryOptions())
            .sessionReceiver()
            .receiveMode(ServiceBusReceiveMode.PEEK_LOCK)
            .queueName(QUEUE_NAME)
            .buildAsyncClient()
    }

        logger.info("Listening for Messages from ServiceBus ")
        val receiverMono = receiverClient.acceptNextSession()
        Flux.usingWhen(receiverMono,
            { receiver: ServiceBusReceiverAsyncClient -> receiver.receiveMessages() }
        ) { receiver: ServiceBusReceiverAsyncClient ->
            Mono.fromRunnable<Any?> { receiver.close() }
        }
            .subscribe({ message: ServiceBusReceivedMessage ->
                // Process message
                logger.info(
                    "Message Received from Service Bus : ${LocalDateTime.now()} ${Thread.currentThread().id}  Session: ${message.sessionId}. Sequence #: ${message.sequenceNumber}. Contents: ${message.body} EnqueuedTime: ${message.enqueuedTime} %n"
                )

**Comment by anuchandy** [comment]
Hello @rajivroypcc, this is not an error that gets propagated to the application, but it’s a log-message. This is the error-message that Service returns if there is no session available in 1 min since the client last asked for a session. In this case, the client repeat the  ask for the session and once the service finds a session is available, the client will return `ServiceBusReceiverAsyncClient` for that session.

**Comment by rajivroypcc** [comment]
/unresolve

Hi @anuchandy thanks I do see that message every minute.
I am seeing this error in log because of which messages are not being processed I guess.
Can you advise ?

`ServiceBusManagerImpl : Error receiving messages from Service Bus com.azure.core.amqp.exception.AmqpException: Session receive link completed without being active
	at com.azure.messaging.servicebus.ServiceBusSessionManager.lambda$getActiveLink$7(ServiceBusSessionManager.java:284)
	at reactor.core.publisher.MonoErrorSupplied.subscribe(MonoErrorSupplied.java:55)
	at reactor.core.publisher.Mono.subscribe(Mono.java:4490)
	at reactor.core.publisher.FluxSwitchIfEmpty$SwitchIfEmptySubscriber.onComplete(FluxSwitchIfEmpty.java:82)
	at reactor.core.publisher.MonoNext$NextSubscriber.onComplete(MonoNext.java:102)
	at reactor.core.publisher.FluxFilter$FilterSubscriber.onComplete(FluxFilter.java:166)
	at reactor.core.publisher.SerializedSubscriber.onComplete(SerializedSubscriber.java:146)
	at reactor.core.publisher.FluxTakeUntilOther$TakeUntilMainSubscriber.onComplete(FluxTakeUntilOther.java:269)
	at reactor.core.publisher.FluxDistinctUntilChanged$DistinctUntilChangedSubscriber.onComplete(FluxDistinctUntilChanged.java:173)
	at reactor.core.publisher.FluxReplay$SizeBoundReplayBuffer.replayNormal(FluxReplay.java:868)
	at reactor.core.publisher.FluxReplay$SizeBoundReplayBuffer.replay(FluxReplay.java:965)
	at reactor.core.publisher.FluxReplay$ReplaySubscriber.onComplete(FluxReplay.java:1372)
	at reactor.core.publisher.FluxPeek$PeekSubscriber.onComplete(FluxPeek.java:260)
	at reactor.core.publisher.FluxPeek$PeekSubscriber.onComplete(FluxPeek.java:260)
	at reactor.core.publisher.FluxMap$MapSubscriber.onComplete(FluxMap.java:144)
	at reactor.core.publisher.FluxDistinctUntilChanged$DistinctUntilChangedSubscriber.onComplete(FluxDistinctUntilChanged.java:173)
	at reactor.core.publisher.FluxReplay$SizeBoundReplayBuffer.replayNormal(FluxReplay.java:868)
	at reactor.core.publisher.FluxReplay$SizeBoundReplayBuffer.replay(FluxReplay.java:965)
	at reactor.core.publisher.ReplayProcessor.tryEmitComplete(ReplayProcessor.java:465)
	at reactor.core.publisher.SinkManySerialized.tryEmitComplete(SinkManySerialized.java:64)
	at reactor.core.publisher.InternalManySink.emitComplete(InternalManySink.java:68)
	at com.azure.core.amqp.implementation.handler.Handler.close(Handler.java:155)
	at com.azure.core.amqp.implementation.handler.LinkHandler.onLinkFinal(LinkHandler.java:84)
	at com.azure.core.amqp.implementation.handler.ReceiveLinkHandler.onLinkFinal(ReceiveLinkHandler.java:237)
	at org.apache.qpid.proton.engine.BaseHandler.handle(BaseHandler.java:182)
	at org.apache.qpid.proton.engine.impl.EventImpl.dispatch(EventImpl.java:108)
	at org.apache.qpid.proton.reactor.impl.ReactorImpl.dispatch(ReactorImpl.java:324)
	at org.apache.qpid.proton.reactor.impl.ReactorImpl.process(ReactorImpl.java:291)
	at com.azure.core.amqp.implementation.ReactorExecutor.run(ReactorExecutor.java:91)
	at reactor.core.scheduler.SchedulerTask.call(SchedulerTask.java:68)
	at reactor.core.scheduler.SchedulerTask.call(SchedulerTask.java:28)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:304)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)`

**Comment by rajivroypcc** [comment]
So, you want me to put this inside a retry block.

Any recommendations regarding how many times should I retry and at what intervals ?

**Comment by rajivroypcc** [comment]
/unresolve

Hi @anuchandy  : we sent 400 messages to service bus. After 238th message it stopped working with this error.
Can you advise on an urgent basis ?

`ServiceBusManagerImpl : Ehi_Message: EHI Error receiving messages from Service Bus com.azure.core.amqp.exception.AmqpException: The service was unable to process the request; please retry the operation. For more information on exception types and proper exception handling, please refer to http://go.microsoft.com/fwlink/?LinkId=761101 TrackingId:7fe0eb1e57944e1d87136cdbb2149b7a_G39, SystemTracker:gateway7, Timestamp:2023-09-21T14:38:08, errorContext[NAMESPACE: ehi-service-bus-qa.servicebus.windows.net. ERROR CONTEXT: N/A, PATH: ehi-perf-queue, REFERENCE_ID: session-_a62306_1695307068422, LINK_CREDIT: 0]
	at com.azure.core.amqp.implementation.ExceptionUtil.toException(ExceptionUtil.java:85)
	at com.azure.core.amqp.implementation.handler.LinkHandler.handleRemoteLinkClosed(LinkHandler.java:124)
	at com.azure.core.amqp.implementation.handler.LinkHandler.onLinkRemoteClose(LinkHandler.java:64)
	at com.azure.core.amqp.implementation.handler.ReceiveLinkHandler.onLinkRemoteClose(ReceiveLinkHandler.java:228)
	at org.apache.qpid.proton.engine.BaseHandler.handle(BaseHandler.java:176)
	at org.apache.qpid.proton.engine.impl.EventImpl.dispatch(EventImpl.java:108)
	at org.apache.qpid.proton.reactor.impl.ReactorImpl.dispatch(ReactorImpl.java:324)
	at org.apache.qpid.proton.reactor.impl.ReactorImpl.process(ReactorImpl.java:291)
	at com.azure.core.amqp.implementation.ReactorExecutor.run(ReactorExecutor.java:91)
	at reactor.core.scheduler.SchedulerTask.call(SchedulerTask.java:68)
	at reactor.core.scheduler.SchedulerTask.call(SchedulerTask.java:28)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:304)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)`

**Comment by anuchandy** [comment]
Hello @rajivroypcc, 

Similar to `acceptSession()`, a termination signal (i.e. error) from `receiveMessages(..)` requires rolling to next session.

Btw I’m unsure if you really want to use the Reactor Client. Unless you’re integrating Reactive session-receive to a Reactor application, I would keep it simple and use the Iterator-based session-receive. This way you don’t have to worry about Reactor concepts such as backpressure, operator chain for retry, picking thread to run etc.

Below is the sample I quickly wrote showing rolling to new session. It uses the iterator-based session-receive. If you really need Reactor API based on receiving, you can apply the concept in this sample by choosing appropriate reactor operators that fit your scenario.

**Comment by anuchandy** [comment]
```java
import com.azure.core.util.logging.ClientLogger;
import io.netty.util.concurrent.DefaultThreadFactory;

import java.time.Duration;
import java.util.HashMap;
import java.util.Objects;
import java.util.concurrent.ExecutorService;
import java.util.concurrent.Executors;
import java.util.concurrent.TimeUnit;
import java.util.function.BiConsumer;

final class RollingSessionsReceiver {
    private static final String QUEUE_NAME_KEY = "QUEUE_NAME";
    private final ClientLogger logger;
    private final BiConsumer<ServiceBusReceivedMessage, ServiceBusReceiverClient> messageConsumer;
    private final Duration maxWaitTime;
    private final ExecutorService executorService;
    private final ServiceBusSessionReceiverClient serviceBusSessionReceiverClient;

    RollingSessionsReceiver(ServiceBusClientBuilder clientBuilder,
                            BiConsumer<ServiceBusReceivedMessage, ServiceBusReceiverClient> messageConsumer,
                            String queueName, Duration maxWaitTime, Duration maxAutoLockRenewal) {
        Objects.requireNonNull(clientBuilder);
        Objects.requireNonNull(messageConsumer);
        Objects.requireNonNull(queueName);

        final HashMap<String, Object> loggingContext = new HashMap<>(1);
        loggingContext.put(QUEUE_NAME_KEY, queueName);
        this.logger = new ClientLogger(RollingSessionsReceiver.class, loggingContext);

        this.messageConsumer = Objects.requireNonNull(messageConsumer);
        // 'messageConsumer' handles each message, e.g,
        //
        //        new BiConsumer<ServiceBusReceivedMessage, ServiceBusReceiverClient>() {
        //            @Override
        //            public void accept(ServiceBusReceivedMessage message, ServiceBusReceiverClient client) {
        //                final boolean success = handleMessage(message);
        //                if (success) {
        //                    try {
        //                        client.complete(message);
        //                    } catch (RuntimeException e) {
        //                        logger.atInfo().log("unable to complete the message.");
        //                    }
        //                } else {
        //                    try {
        //                        client.abandon(message);
        //                    } catch (RuntimeException e) {
        //                        logger.atInfo().log("unable to abandon the message.");
        //                    }
        //                }
        //            }
        //        };

        this.maxWaitTime = maxWaitTime == null ? Duration.ofSeconds(5) : maxWaitTime;
        final Duration maxAutoLockRenewalTime = maxAutoLockRenewal == null ? Duration.ofMinutes(5) : maxAutoLockRenewal;
        this.executorService = Executors.newFixedThreadPool(1, new DefaultThreadFactory(queueName));

        this.serviceBusSessionReceiverClient = clientBuilder.sessionReceiver()
            .queueName(queueName)
            .maxAutoLockRenewDuration(maxAutoLockRenewalTime)
            .disableAutoComplete()
            .buildClient();
    }

    void start() {
        executorService.submit(this::handleSessions);
    }


    void stop() {
        executorService.shutdown();
        try {
            if (!executorService.awaitTermination(60, TimeUnit.SECONDS)) {
                executorService.shutdownNow();
                if (!executorService.awaitTermination(60, TimeUnit.SECONDS)) {
                    logger.atWarning().log("Executor service did not terminate");
                }
            }
        } catch (InterruptedException ex) {
            executorService.shutdownNow();
            Thread.currentThread().interrupt();
        }

        try {
            logger.atInfo().log("stop() called, terminating acquiring sessions.");
            serviceBusSessionReceiverClient.close();
        } catch (Exception e) {
            logger.atWarning().log("Exception on stopping.", e);
        }
    }

    private void handleSessions() {
        while (true) {
            try {
                if (isStopped()) {
                    break;
                }
                final ServiceBusReceiverClient serviceBusReceiverClient = serviceBusSessionReceiverClient.acceptNextSession();
                processSession(serviceBusReceiverClient);
            } catch (Exception e) {
                logger.atWarning().log("Exception when accepting or processing a session. Continuing to accepting next session.", e);
            }
            try {
                // back-off before attempting the next session.
                TimeUnit.SECONDS.sleep(2);
            } catch (InterruptedException e) {}
        }
    }

    private boolean isStopped() {
        return executorService.isShutdown();
    }

    private void processSession(ServiceBusReceiverClient serviceBusReceiverClient) {
        if(serviceBusReceiverClient == null) {
            logger.atWarning().log("acceptNextSession() returned null.");
            return;
        }
        final String sessionId = serviceBusReceiverClient.getSessionId();
        logger.atInfo().log("New session acquired {}", sessionId);

        var terminatingReason = "UNKNOWN";

        while (true) {
            try {
                if (isStopped()) {
                    // stop() method was called.
                    terminatingReason = "STOP_SIGNAL_RECEIVED";
                    break;
                }
                final var messageIterator = serviceBusReceiverClient.receiveMessages(1, maxWaitTime).iterator();
                if (!messageIterator.hasNext()) {
                    // "Optionally" move to new session when NO messages.
                    // If there is no message in the session, try acquiring another session so see it can be processed.
                    terminatingReason = "NO_MESSAGE_IN_SESSION";
                    break;
                }
                messageIterator.forEachRemaining(receivedMessage -> messageConsumer.accept(receivedMessage, serviceBusReceiverClient));
            } catch (RuntimeException e) {
                logger.atWarning().log("Error while receiving and processing messages from session {}", sessionId, e);
                terminatingReason = "EXCEPTION_OCCURRED";
                break;
            }
        }
        logger.atInfo().log("Closing session {} reason {}", sessionId, terminatingReason);
        serviceBusReceiverClient.close();
    }
}

```

**Comment by razum90** [comment]
Hi @anuchandy,

I am getting the same log message in our application, along with loads of other `INFO` logs.

I have followed the implementation guide at https://github.com/Azure/azure-sdk-for-java/blob/main/sdk/servicebus/azure-messaging-servicebus/src/samples/java/com/azure/messaging/servicebus/ServiceBusSessionProcessorSample.java.

Below is my configuration of the processor client:

```java
        this.serviceBusProcessorClient = new ServiceBusClientBuilder()
                .connectionString(connectionString)
                .sessionProcessor()
                .queueName(QUEUE_NAME)
                .maxConcurrentSessions(50)
                .processMessage(this::processMessage)
                .processError(this::processError)
                .buildProcessorClient();
```

Will this client continue to process messages after I receive those logs? Or is there anything I need to do? In my mind, this should be handled internally by your client.

Can I disable those logs somehow if they don't have any impact on my application?

BR

**Comment by razum90** [comment]
While I am here and asking you about sessions @anuchandy, I am wondering what will happen if the replica of my service that is assigned to handle a specific session shuts down? Will the session be assigned to another, running replica in that case? How long would that process take?

**Comment by anuchandy** [comment]
@razum90,

If the replica / pod goes down abruptly, given the client is no longer running, it won’t be able to send the session(s) lock renewal to the broker. This will cause the session-lock on the service to expire, and service will make that session(s) free for others to pick. How long a session will be locked is controlled by the service, it should be a few minutes from what I observed. On the other hand, if replica life lasted enough to close the client successfully, then sessions will be also closed, marking those free on the service side.

Other ProcessorClient running on healthy replica will be able to acquire those free session, provided it is currently handling less that max-concurrent-sessions.

I would suggest limiting max-concurrent-sessions to 20-25 in one replica, and scale horizontally to balance the load across replicas. For general container resource allocation (cpu/memory), please refer to [Containerize your Java applications - Java on Azure | Microsoft Learn](https://learn.microsoft.com/en-us/azure/developer/java/containers/overview), starting with 2-4 cores recommended.

Also, the logs can be ignored given ProcessorClient is designed to recovers from those transient cases.

**Comment by rajivroypcc** [comment]
Hello @anuchandy ,

Is this the correct way to retry ? (SpringRetryTemplate is not retrying the AmqpExceptions)

or can you pls suggest how to add AmqpException retry.

`retryTemplate.execute<Unit, AmqpException> {
	val receiverMono = receiverClient.acceptNextSession()
	Flux.usingWhen(receiverMono,
		{ receiver: ServiceBusReceiverAsyncClient -> receiver.receiveMessages() }
	) { receiver: ServiceBusReceiverAsyncClient ->
		Mono.fromRunnable<Any?> { receiver.close() }
	}
		.subscribe({ message: ServiceBusReceivedMessage ->
			// Process message
			logger.info(
				"Ehi_Message: EHI Message Received from Service Bus : ${LocalDateTime.now()} ${Thread.currentThread().id}  Session: ${message.sessionId}. Sequence #: ${message.sequenceNumber}. Contents: ${message.body} EnqueuedTime: ${message.enqueuedTime} %n"
			)

			)
		}) { error: Throwable ->
			when (error) {
				is AmqpException -> {
					logger.error("Ehi_Message: AmqpException encountered", error)
					throw error
				}
			}
		}
}`

**Comment by rajivroypcc** [comment]
Hello @anuchandy 

Can you provide an example to retry AmqpException ? 

This is not working:

`         Flux.usingWhen(receiverMono,
            { receiver: ServiceBusReceiverAsyncClient -> receiver.receiveMessages() }
        ) { receiver: ServiceBusReceiverAsyncClient ->
            Mono.fromRunnable<Any?> { receiver.close() }
        }
            .retryWhen(Retry.backoff(3, Duration.ofSeconds(5))
                .filter { throwable -> throwable is AmqpException })
            .subscribe({ message: ServiceBusReceivedMessage -> `

**Comment by razum90** [comment]
Thanks @anuchandy,

In the end I rebuilt the event handling to be able to process the events in any order. But good to know for future reference.

BR

**Comment by anuchandy** [comment]
Closing the ticket.

Summary: The recommended preference of using session client is

> ServiceBusProcessorClient > ServiceBusSessionReceiverClient > ServiceBusSessionReceiverAsyncClient

The `ServiceBusSessionProcessorClient` has the simplest APIs and is strongly recommended for the production scenario. The application does not have to worry about transient errors or how to handle them. This Client has proven to work for almost all application use cases, has automatic session rolling, resilience built-in.

`ServiceBusSessionReceiverClient` (aka Low-Level Sync Client) requires additional effort from application to deal with errors, creating new clients on error, and managing executor service. See the previous comment with example code.

`ServiceBusSessionReceiverAsyncClient` (aka Low-Level Async Client) requires all the application effort needed for ServiceBusSessionReceiverClient, plus, application responsibility includes understanding the backpressure of the operators they are applying to and thread hoping. This client is least preferred for production use cases. Typically, this client is used by library writers integrating (async chaining) with Reactor frameworks, and need good understanding of the Reactive programming and impact of operators.
