### ISSUE TITLE
[FEATURE REQ]Cosmos - make CosmosBulkExecutionOptions.setInitialMicroBatchSize public

### ISSUE THREAD

**Issue by FabianMeiswinkel** [Azure/azure-sdk-for-java#36785]
**Is your feature request related to a problem? Please describe.**
Customer wants to avoid throttling even in the beginning of ingestion - to achieve that the automatic tuning of thr micro batch size needs to start from a small batch size and gradually grow vs. what happens right now - start with 100 docs and eventually tune down to smaller batch size. This functionality has been added for the Spark connector already - but the API in the CosmosBulkExecutionOptions is still internal. So, not usable outside of Spark.

**Describe the solution you'd like**
Make this method public - https://github.com/Azure/azure-sdk-for-java/blob/177aca74867d48ea544fbe2663983d5e429e2cac/sdk/cosmos/azure-cosmos/src/main/java/com/azure/cosmos/models/CosmosBulkExecutionOptions.java#L77-L80 

**Describe alternatives you've considered**
n/a

**Additional context**
n/a

**Information Checklist**
Kindly make sure that you have added all the following information above and checkoff the required fields otherwise we will treat the issuer as an incomplete report
- [x] Description Added
- [x] Expected solution specified

**Comment by mkrueger** [comment]
Fixed by https://github.com/Azure/azure-sdk-for-java/pull/36910
