### ISSUE TITLE
Please clarify how to check if the connection string has SEND SAS policy or LISTEN SAS policy or MANAGE SAS policy using azure-messaging-servicebus-7.8.0.jar SDK  library

### ISSUE THREAD

**Issue by snarlagi** [Azure/azure-sdk-for-java#36787]
**Query/Question**
Please clarify how to check if the connection string has SEND SAS policy or LISTEN SAS policy or MANAGE SAS policy using azure-messaging-servicebus-7.8.0.jar SDK  library

We have requirement to connect Azure Service Bus using connection string (Endpoint=sb://<<namespace>>.servicebus.windows.net/;SharedAccessKeyName=devtest;SharedAccessKey=01oz/cVg)
When we try to do test connection to Azure Service Bus Queue we want to check if the provided connection string has required SAS policy for send or receive or manage. 

Particulary for send SAS policy we found that we need to perform sendmessage() operation on senderclient which we don't feel a right strategy to send messages to customer queue. We want an alternative approach to check the  "AuthorizationRule/SharedAccessAuthorizationRule"  for the connection string without sending messages to customer queue/topic for Send SAS policy.

**Code Snippet**

```
//adminclient test code
String connectionString=azp.getConnectionString()+";SharedAccessKeyName="+azp.getSharedAccessKeyName()+";SharedAccessKey="+azp.getSharedAccessKey();
adminClient = new ServiceBusAdministrationClientBuilder().connectionString(connectionString).buildClient();

adminClient.getQueue(azp.getEntityName());

```

```
//receiverclient test code
receiverClient = new ServiceBusClientBuilder() .connectionString(connectionString).receiver().queueName(azp.getEntityName()).buildClient();

receiverClient.peekMessage();


```

```
//senderclient test code

senderClient = new ServiceBusClientBuilder().connectionString(connectionString).sender().queueName(azp.getEntityName()).buildClient();

senderClient.sendMessage(new ServiceBusMessage("BW AMQP plugin test connection message. please ignore it"));


```

***Why is this not a Bug or a feature Request?***
A clear explanation of why is this not a bug or a feature request?
I have explained my query as functionality is working but I don't find a right strategy to find out the SAS policy applied for the connection string particularly for SEND SAS policy without sending messages to customer queue

**Setup (please complete the following information if applicable):**
 - OS: Windows
 - IDE: Eclipse
 - Library/Libraries: azure-messaging-servicebus-7.8.0.jar and it's dependencies.
 
 **Information Checklist**
 Kindly make sure that you have added all the following information above and checkoff the required fields otherwise we will treat the issuer as an incomplete report
- [*] Query Added
- [*] Setup information Added

**Comment by anuchandy** [comment]
If you’re using SAS, you will need Manage claim enabled for the SAS in order list the AuthorizationRules and AccessRights. This is a service restriction.

**Comment by snarlagi** [comment]
Hi @anuchandy ,

`Particulary for send SAS policy we found that we need to perform sendmessage() operation on senderclient which we don't feel a right strategy to send messages to customer queue. We want an alternative approach to check the with any method for the connection string without sending messages to customer queue/topic for Send SAS policy.`

Thanks for your reply.

**Our UseCase:** 

**So, we have to perform test connection with connection string having for Listen/Send policy access key name and access key.
Can you please suggest which type of methods can be used for connection string having Listen/Send Policy  without affecting customer queue/topic messages delivery count/ loss of message**

**Comment by EldertGrootenboer** [comment]
@snarlagi It is indeed only possible to test the connection for send permissions by sending a message to the entity. That said, as soon as a token with this permission is added on your entity, you can be sure that any client with that token will be able to send messages, so we would recommend into looking into options to check if the token is indeed set correctly, instead of sending a message. Moreover, you can [monitor for authentication issues](https://learn.microsoft.com/en-us/azure/service-bus-messaging/monitor-service-bus-reference#metric-dimensions), which will help identify mis-configured tokens / entities.

**Comment by anuchandy** [comment]
Closing the ticket, questions are answered.
