### ISSUE TITLE
[QUERY] Will the bulk executor in the latest SDK roll back transaction if exception happen?

### ISSUE THREAD

**Issue by loudywen** [Azure/azure-sdk-for-java#36803]
Hi I am reading this https://learn.microsoft.com/en-us/azure/cosmos-db/nosql/how-to-migrate-from-bulk-executor-library-java and I want to know that is the bulk executor will roll back all the transaction if there is exception?

**Comment by kushagraThapar** [comment]
@loudywen - apologies for the delayed response, somehow missed this github issue. 
Bulk executor will not roll back the transaction if there is an exception, it will just return the response and then you can read the response to see which record had the exception. 

What you might be looking for is Transactional batch feature, which is different. You can read more about it here: https://learn.microsoft.com/en-us/azure/cosmos-db/nosql/transactional-batch?tabs=java
