### ISSUE TITLE
[BUG] Calling FaceAPI.PersonGroups.create with null CreatePersonGroupsOptionalParameter argument results in HTTP 400

### ISSUE THREAD

**Issue by v-jaswel** [Azure/azure-sdk-for-java#3681]
**Describe the bug**
[PersonGroups.create](https://github.com/Azure/azure-sdk-for-java/blob/master/cognitiveservices/data-plane/vision/faceapi/src/main/java/com/microsoft/azure/cognitiveservices/vision/faceapi/implementation/PersonGroupsImpl.java#L108) can be called with a null value for the CreatePersonGroupsOptionalParameter argument. [createWithServiceResponseAsync](https://github.com/Azure/azure-sdk-for-java/blob/master/cognitiveservices/data-plane/vision/faceapi/src/main/java/com/microsoft/azure/cognitiveservices/vision/faceapi/implementation/PersonGroupsImpl.java#L150) then converts the null argument into null values for the **name** and **userData** parameters that are sent to the service.
However, **name** is not optional when calling [Person Group - Create](https://westus.dev.cognitive.microsoft.com/docs/services/563879b61984550e40cbbe8d/operations/563879b61984550f30395244/console). 
Therefore, you must create a CreatePersonGroupsOptionalParameter object with the **name** field set and pass it to PersonGroups.create or you will get a 400 response.

***Exception or Stack Trace***
Status code 400, {"error":{"code":"BadArgument","message":"Request body is invalid."}}

**To Reproduce**
Note: to use FaceAPIManager, I am referencing azure-cognitiveservices-faceapi-1.0.2-beta.jar, which I compiled from https://github.com/Azure/azure-sdk-for-java. For more information see: #3640.

***Code Snippet***
```
import com.microsoft.azure.cognitiveservices.vision.faceapi.*;
import com.microsoft.azure.cognitiveservices.vision.faceapi.models.*;

public class Test {
    public static void main(String[] args) {
        try {
            AzureRegions region = AzureRegions.WESTUS;
            FaceAPI client = FaceAPIManager.authenticate(region, "INSERT API KEY HERE");
            personGroupCreate(client);
        } catch (Exception e) {
            System.out.println(e.getMessage());
            e.printStackTrace();
        }
    }

    public static void personGroupCreate(FaceAPI client) {
        final String PERSON_GROUP_ID = "INSERT PERSON GROUP ID HERE";
        try {
            client.personGroups().create(PERSON_GROUP_ID, null);
            System.out.println("Person group created");
        } catch (Exception e) {
            System.out.println(e.getMessage());
        }
    }
}
```

**Expected behavior**
Output: Person group created

**Screenshots**
N/A

**Setup (please complete the following information):**
 - OS: Win 10 Pro 1803
 - IDE: None
 - Version of the Library used: azure-cognitiveservices-faceapi-1.0.2-beta.jar

**Additional context**
To call the PersonGroup.create method correctly:
```
CreatePersonGroupsOptionalParameter param = new CreatePersonGroupsOptionalParameter ().withName ("name");
client.personGroups().create(PERSON_GROUP_ID, param);
```

**Information Checklist**
Kindly make sure that you have added all the following information above and checkoff the required fields otherwise we will treat the issuer as an incomplete report
- [x] Bug Description Added
- [x] Repro Steps Added
- [x] Setup information Added

**Comment by kurtzeborn** [comment]
Thank you for opening this issue! We are routing it to the appropriate team for follow up.

**Comment by wiazur** [comment]
Has this issue been corrected in the new Java SDK? I know that one is unreleased still. The one I am testing with is **azure-cognitiveservices-faceapi-1.0.2-beta**, and this issue is still there. Thanks.
@dfulcer @kurtzeborn

**Comment by joshfree** [comment]
@milismsft @ryogok
