### ISSUE TITLE
[BUG] Unable to update forwardDeadLetteredMessagesTo with ServiceBusAdministrationClient

### ISSUE THREAD

**Issue by alexciouca** [Azure/azure-sdk-for-java#36811]
**Describe the bug**
I am trying to set forwardDeadLetteredMessagesTo on an already existing Entity via an update request, but it seems the call is ignored (see screenshot).

***Exception or Stack Trace***
No exception is thrown.

**To Reproduce**
- create DLQ entity
- create entity
- build an update call to set forwardDeadLetteredMessagesTo
- update entity

Same steps have been tested with both ServiceBusAdministrationClient and ServiceBusAdministrationAsyncClient.

***Code Snippet***
```
administrationClient.createQueue("test.entity.dlq");
final QueueProperties queueProperties = administrationClient.createQueue("test.entity");
queueProperties.setDeadLetteringOnMessageExpiration(true);
queueProperties.setForwardDeadLetteredMessagesTo("test.entity.dlq");
administrationClient.updateQueue(queueProperties);
```

**Expected behavior**
forwardDeadLetteredMessagesTo is being updated when an update call is made.

**Screenshots**
![image](https://github.com/Azure/azure-sdk-for-java/assets/57758844/f4425909-6cfa-4701-99eb-a2aed4e976af)

**Setup (please complete the following information):**
 - OS:  Linux 5.15.0-1041-azure amd64
 - Library/Libraries: com.azure:azure-messaging-servicebus:7.14.3
 - Java version: 17
 - Frameworks: Spring Boot

**Information Checklist**
Kindly make sure that you have added all the following information above and checkoff the required fields otherwise we will treat the issuer as an incomplete report
- [x] Bug Description Added
- [x] Repro Steps Added
- [x] Setup information Added

**Comment by alexciouca** [comment]
Hello @anuchandy would you have any news on this?

**Comment by anuchandy** [comment]
Hi @alexciouca, I was able to repro this and I’m following up with the service team to get some clarification on the format of the payload that SDK is sending.

**Comment by anuchandy** [comment]
This is addressed in the pr https://github.com/Azure/azure-sdk-for-java/pull/37353. Thanks, Alex, for reporting, closing the issue.
