### ISSUE TITLE
[Key Vault] Raise useful error when `KeyReleasePolicy` is incorrectly created

### ISSUE THREAD

**Issue by pallavit** [Azure/azure-sdk-for-java#36863]
The `KeyReleasePolicy` model expects an `encoded_policy` parameter as bytes. If a string is passed instead, no error is raised -- but when the created policy is provided to a `create_key` request, the service returns an error suggesting that the policy was never provided (see https://github.com/Azure/azure-sdk-for-python/issues/29945):
```
azure.core.exceptions.HttpResponseError: (BadParameter) AKV.SKR.1004: Exportable keys must have release policy.
```

This doesn't make the cause of the failure obvious at all. Though input validation is generally avoided, we should raise an error when a string is provided to the `KeyReleasePolicy` constructor so that users have an easier way to identify the problem.

**Comment by vcolin7** [comment]
Java expects a `KeyReleasePolicy`'s value to be of type `BinaryData`, so we don't need to add any client-side validation avoiding it being a `String` when provided by a user.
