### ISSUE TITLE
[QUERY] Possibility to define name for the node resource group for AKS

### ISSUE THREAD

**Issue by sergiygetlin** [Azure/azure-sdk-for-java#36866]
**Query/Question**
Is it possible to set name for the node resource group for AKS? Seems nodeResourceGroup available only internally.
So, for instance I want to do following:
`azureResourceManager().kubernetesClusters().define(aksName)... .withNodeResourceGroup(name).create()`

If it's not possible now, any plans to implement it in future?

**Setup (please complete the following information if applicable):**
 - IDE: [e.g. IntelliJ]
 - Library: com.azure.resourcemanager:azure-resourcemanager-containerservice:2.30.0

**Comment by weidongxu-microsoft** [comment]
see if we can catch it on 2.31.0 release

**Comment by weidongxu-microsoft** [comment]
2.31.0 released
