### ISSUE TITLE
[QUERY] Is it possible to handle multiple app registrations for one Spring Boot app?

### ISSUE THREAD

**Issue by ObakeFilter** [Azure/azure-sdk-for-java#36884]
**Query/Question**
Hello everyone, I have a Spring Boot app that expose an API which I would like to protect in a manner similar to the [one described over here](https://learn.microsoft.com/en-us/azure/developer/java/spring-framework/spring-boot-starter-for-azure-active-directory-developer-guide?tabs=SpringCloudAzure5x#protect-a-resource-serverapi), problem is, I would like to provide access to users from two different Azure apps (both reside in the same tenant, there are two different sets of client-id, app-id and client secret), I couldn't find any info online on wheter it's even doable. Can you please suggest a way it can be done?

**Comment by moarychan** [comment]
Hi @ObakeFilter , we do not have such scenario verification, but according to the source code you can try to support multiple audience verification by customizing bean `JwtDecoder`.

Please refer to [AadResourceServerConfiguration#jwtDecoder](https://github.com/Azure/azure-sdk-for-java/blob/a379507f9feeb1c0c04f9959d9ff20be4690ddcc/sdk/spring/spring-cloud-azure-autoconfigure/src/main/java/com/azure/spring/cloud/autoconfigure/aad/configuration/AadResourceServerConfiguration.java#L66)
```java
@Bean
public JwtDecoder jwtDecoder(AadAuthenticationProperties aadAuthenticationProperties) {
    AadAuthorizationServerEndpoints identityEndpoints = new AadAuthorizationServerEndpoints(
        aadAuthenticationProperties.getProfile().getEnvironment().getActiveDirectoryEndpoint(), aadAuthenticationProperties.getProfile().getTenantId());
    NimbusJwtDecoder nimbusJwtDecoder = NimbusJwtDecoder
            .withJwkSetUri(identityEndpoints.getJwkSetEndpoint())
            .restOperations(createRestTemplate(restTemplateBuilder))
            .build();
    List<OAuth2TokenValidator<Jwt>> validators = createDefaultValidator(aadAuthenticationProperties);
    nimbusJwtDecoder.setJwtValidator(new DelegatingOAuth2TokenValidator<>(validators));
    return nimbusJwtDecoder;
}

public List<OAuth2TokenValidator<Jwt>> createDefaultValidator(AadAuthenticationProperties aadAuthenticationProperties) {
    List<OAuth2TokenValidator<Jwt>> validators = new ArrayList<>();
    List<String> validAudiences = new ArrayList<>();
    if (StringUtils.hasText(aadAuthenticationProperties.getAppIdUri())) {
        validAudiences.add(aadAuthenticationProperties.getAppIdUri());
    }
    if (StringUtils.hasText(aadAuthenticationProperties.getCredential().getClientId())) {
        validAudiences.add(aadAuthenticationProperties.getCredential().getClientId());
    }

    // add your second group client-id and app-id-url to the validAudiences
    
    if (!validAudiences.isEmpty()) {
        validators.add(new JwtClaimValidator<List<String>>(AadJwtClaimNames.AUD, validAudiences::containsAll));
    }
    validators.add(new AadJwtIssuerValidator());
    validators.add(new JwtTimestampValidator());
    return validators;
}
```
