### ISSUE TITLE
[BUG] Could not retrieve vm by vmId(uuid) instead of resource id.

### ISSUE THREAD

**Issue by zlishaojiez** [Azure/azure-sdk-for-java#36954]
**Describe the bug**
There is no method that can retrieve the VM by vmId (uuid)

**Comment by XiaofeiCao** [comment]
@zlishaojiez I'm afraid there's no REST API for this method.

I suggest that you try [Azure Resource Graph SDK](https://learn.microsoft.com/en-us/azure/governance/resource-graph/first-query-java) to achieve this. Usage is something like: 
```java
// construct manager
ResourceGraphManager manager = ResourceGraphManager.authenticate(new DefaultAzureCredentialBuilder().build(), new AzureProfile(AzureEnvironment.AZURE));

// query
String strQuery = "Resources\n" +
            "| where type =~ 'microsoft.compute/virtualmachines' and properties.vmId = '{your_vm_id}'";
QueryRequest queryRequest = new QueryRequest()
     .withSubscriptions(subscriptionIds)
     .withQuery(strQuery);

// get response
QueryResponse response = manager.resourceProviders().resources(queryRequest);
```

Sample queries for VMs: https://learn.microsoft.com/en-us/azure/virtual-machines/resource-graph-samples

**Comment by zlishaojiez** [comment]
@XiaofeiCao 
Got it, thanks.
