### ISSUE TITLE
API research for long-running operations

### ISSUE THREAD

**Issue by JonathanGiles** [Azure/azure-sdk-for-java#3695]
We need to offer API that simplifies the task of executing long running operations against Azure. There is currently a [draft spec proposal](https://github.com/Azure/azure-sdk/pull/370/files) being discussed and reviewed. The ask of each language team is to provide at least a draft API proposal for how this will be fully implemented for the week starting May 26.

We should also review the existing polling code that exists in azure-core-management.

This issue therefore tracks this requirement in the first instance.

**Comment by alzimmermsft** [comment]
Quick review of the polling code that already exist and how it aligns with the proposal.

**Querying the current operation state**
All querying of the current operation state is reactive, sending status requests to the service.

**Requesting an asynchronous notification when the operation has completed**
Only Azure Core Management has the ability to receive a notification when the operation has completed.

**Cancelling the operation if cancellation is supported by the service**
There is no built in mechanism to cancel the polling operation.

**Serializing the operation such that another process can pick up polling**
Polling strategy implements Serializable which should allow for the polling to be portable.

**Triggering a poll operation manually (automatic polling must be disabled)**
Polling is automatically added to requests that allow for polling.

**Comment by alzimmermsft** [comment]
Though there are requirements missing in the current implementation I do believe it would be best to begin porting the polling logic from Azure Core Management into Azure Core, clean up the interface, add rich documentation, and make it generally available.

**Comment by hemanttanwar** [comment]
@bterlson  Question  on "5. serializing the operation such that another process can pick up polling". 
Since We are adding callback functions  which poller will call when A.  polling complete and B. cancel the polling.
Does serializing requirement apply call back functions . In other words, should these callback functional needs to be serialized, deserialized back into poller object and resume polling ?

**Comment by bterlson** [comment]
No, we should not need to serialize callbacks. The serialization is to enable easy passing of the serialized state to another VM (for example). I think it's something like a tuple of [StartOperationUrl, UpdateUrl, state]?

**Comment by JonathanGiles** [comment]
Thanks @bterlson for clarifying. Our initial design approach was very simplistic - have a Poller type that would be provided lambda expressions for doing a single poll, and to cancel the long running operation. The Poller, being instantiated by the client library, would know what to do using the API native to it. This means the Poller is relatively simplistic, calling the appropriate callbacks, and receiving them in a standard PollerResponse format (formatted by the client library within the lambda expression). This feels pretty decent, but it falls apart when including the serialization requirement in our consideration - because we aren't operating at the [startOperationUrl, UpdateUrl, state] level, and moving between the two levels might be troublesome. There are options we can explore, so this is just an FYI in case you've got anything you'd like to add.

**Comment by JonathanGiles** [comment]
If we stick to this design, I think we could still have a working approach, it just requires extra plumbing to enable serialization and deserialization. In the case of serialization, we can have the client library enable this inside the Poller by providing a callback that returns a `SerializedPoller` type, that contains appropriate fields such as `operationName`, `clientLibraryName`, `lastKnownPollerState`, as well as a `deserialize()` method that returns a `Poller` instance again.

To deserialize is a little more complex, and will lean on the Java service provide interface approach again. We will introduce an internal API called `PollerDeserializer` that client libraries can provide deserializers for. When a `SerializedPoller` requests deserialization, it calls into this API, and this API in turn checks if any client library will be able to handle the given `SerializedPoller`. Should one accept it, they can create a new `Poller` instance using the standard callback approach.

Whilst this sounds like a lot of work, the act of creating and deserializing Pollers inside a client library could quite easily be centralized into one place, lessening duplication of code.

**Comment by JonathanGiles** [comment]
Serialization has been punted from the V1 of LRO, from my understanding. Here is a gist outlining the current thinking for Java: https://gist.github.com/JonathanGiles/2a2cef537781fc7bd9ee1858097a03d0
