### ISSUE TITLE
[QUERY] Data factory list pipeline api does not have 'state' and 'onInactiveMarkAs' properties on Activity

### ISSUE THREAD

**Issue by violarodrigues-dataworld** [Azure/azure-sdk-for-java#36962]
**Query/Question**
The properties [ActivityOnInactiveMarkAs](https://learn.microsoft.com/en-us/rest/api/datafactory/pipelines/list-by-factory?tabs=HTTP#activityoninactivemarkas) and [ActivityState](https://learn.microsoft.com/en-us/rest/api/datafactory/pipelines/list-by-factory?tabs=HTTP#activityoninactivemarkas) mentioned in the api documentation for data factory are not available in the SDK. I went through the repo but didn't find it. Am I missing something? 

***Why is this not a Bug or a feature Request?***
It's just a query at this moment.

**Setup (please complete the following information if applicable):**
 - Library/Libraries: com.azure.resourcemanager:azure-resourcemanager-datafactory:1.0.0-beta.22
 
 **Information Checklist**
 Kindly make sure that you have added all the following information above and checkoff the required fields otherwise we will treat the issuer as an incomplete report
- [X] Query Added
- [X] Setup information Added

**Comment by weidongxu-microsoft** [comment]
The spec is added about 3 months ago. The last SDK release is earlier than that.

Planning a new SDK release with latest spec.

**Comment by weidongxu-microsoft** [comment]
1.0.0-beta.23 released
https://central.sonatype.com/artifact/com.azure.resourcemanager/azure-resourcemanager-datafactory/1.0.0-beta.23

**Comment by violarodrigues-dataworld** [comment]
Thank you for the quick turnaround. When will this be GA'ed?

**Comment by weidongxu-microsoft** [comment]
The OpenAPI 2.0 spec of the datafactory service appears not stable at present (there is still lots of breaking changes in recent releases https://github.com/Azure/azure-sdk-for-java/blob/main/sdk/datafactory/azure-resourcemanager-datafactory/CHANGELOG.md)

Hence we may not able to have it GAed soon. If you or your corporation has specific requirement on the dependency libs, please let us know. We might need to sync with PM as well.

**Comment by violarodrigues-dataworld** [comment]
We are using datafactory module and were hoping it would reach GA soon. We primarily use the list and get APIs in the library.
