### ISSUE TITLE
Key Vault - Keys Samples Issue

### ISSUE THREAD

**Issue by faynef** [Azure/azure-sdk-for-java#36966]
**1.**

**Section** [link1](https://github.com/Azure/azure-sdk-for-java/blob/azure-security-keyvault-keys_4.7.1/sdk/keyvault/azure-security-keyvault-keys/src/samples/java/com/azure/security/keyvault/keys/cryptography/CryptographyClientJavaDocCodeSnippets.java#L212), [link2](https://github.com/Azure/azure-sdk-for-java/blob/azure-security-keyvault-keys_4.7.1/sdk/keyvault/azure-security-keyvault-keys/src/samples/java/com/azure/security/keyvault/keys/cryptography/CryptographyClientJavaDocCodeSnippets.java#L227), [link3](https://github.com/Azure/azure-sdk-for-java/blob/azure-security-keyvault-keys_4.7.1/sdk/keyvault/azure-security-keyvault-keys/src/samples/java/com/azure/security/keyvault/keys/cryptography/CryptographyClientJavaDocCodeSnippets.java#L330), [link4](https://github.com/Azure/azure-sdk-for-java/blob/azure-security-keyvault-keys_4.7.1/sdk/keyvault/azure-security-keyvault-keys/src/samples/java/com/azure/security/keyvault/keys/cryptography/CryptographyClientJavaDocCodeSnippets.java#L342):
<img width="720" alt="image" src="https://github.com/Azure/azure-sdk-for-java/assets/138087452/50113ace-6733-43a4-8703-2ce0d8b7ee83">
<img width="754" alt="image" src="https://github.com/Azure/azure-sdk-for-java/assets/138087452/20e52928-57b0-4226-ae6b-4c4ca557a84c">
**Reason**:
Invalid signature.

**Suggestion**:

1. Update to `signResult.getSignature()`.
2. Update to `signResponse.getSignature()`.
3. Update to `signResult.getSignature()`.
4. Update to `signingResult.getSignature()`.

**2.**

**Section** [link1](https://github.com/Azure/azure-sdk-for-java/blob/azure-security-keyvault-keys_4.7.1/sdk/keyvault/azure-security-keyvault-keys/src/samples/java/com/azure/security/keyvault/keys/cryptography/CryptographyClientJavaDocCodeSnippets.java#L311), [link2](https://github.com/Azure/azure-sdk-for-java/blob/azure-security-keyvault-keys_4.7.1/sdk/keyvault/azure-security-keyvault-keys/src/samples/java/com/azure/security/keyvault/keys/cryptography/CryptographyClientJavaDocCodeSnippets.java#L321), [link3](https://github.com/Azure/azure-sdk-for-java/blob/azure-security-keyvault-keys_4.7.1/sdk/keyvault/azure-security-keyvault-keys/src/samples/java/com/azure/security/keyvault/keys/cryptography/CryptographyClientJavaDocCodeSnippets.java#L333), [link4](https://github.com/Azure/azure-sdk-for-java/blob/azure-security-keyvault-keys_4.7.1/sdk/keyvault/azure-security-keyvault-keys/src/samples/java/com/azure/security/keyvault/keys/cryptography/CryptographyClientJavaDocCodeSnippets.java#L345):
<img width="800" alt="image" src="https://github.com/Azure/azure-sdk-for-java/assets/138087452/701623f4-9d15-49fd-8fe3-2ce941958dfc">
**Reason**:
Invalid length of value: 100 bytes. ES256 requires 32 bytes, encoded with base64url.

**Suggestion**:
Update `byte[100]` to `byte[32]`.
 
@sandeep-sen , @joshfree , @backwind1233 , @mario-guerra and @heaths to notification.

**Comment by vcolin7** [comment]
I'll correct this before the end of the week :)
