### ISSUE TITLE
[BUG] ServiceBusReceiverAsyncClient.complete() does not increment delivery count

### ISSUE THREAD

**Issue by ingmarkellner** [Azure/azure-sdk-for-java#36977]
**Describe the bug**
I have defined a topic + subscription in Azure ServiceBus with the properties
* Max delivery count: 1
* Message time to live: 14 days
* Auto-delete after idle for: 14 days
* Message lock duration: 1 min

When I trigger message sending via the Service Bus Explorer web UI, my receiver gets the message.
But with .disableAutoComplete() being configured and programmatically completing the message with ServiceBusReceiverAsyncClient.complete(message), the message delivery count in the web UI does not increase and the message appears in the Dead-letter queue.

With auto-complete enabled, the expected behavior is observed: Message gets immediately removed from the subscription in the Service Bus Explorer and does not appear in dead-letter queue.

***Code Snippet***
Following shows a Spring component that creates the receiver with auto-complete disabled and programmatically completing the message (connection properties are omitted).

```
@RequiredArgsConstructor
@Component
public class MessageReceiver implements ApplicationListener<ApplicationStartedEvent> {  
  
  private ServiceBusReceiverAsyncClient receiver;
  private Disposable subscription;

  void connect() {
    final AmqpRetryOptions retryOptions = new AmqpRetryOptions();
    retryOptions.setMaxRetries(5);
    retryOptions.setDelay(Duration.ofSeconds(1));

    receiver = new ServiceBusClientBuilder()
        .retryOptions(retryOptions)
        .connectionString(connectionString)
        .receiver()
        .topicName(topicName)
        .subscriptionName(subscriptionName)
        //default is that processed messages are removed from the queue
        .disableAutoComplete()
        .buildAsyncClient();

    log.info("Creating subscription...");
    this.subscription = receiver.receiveMessages().subscribe(this::processMessage, this::processError, this::finished);
    log.info("Listening for messages...");
  }

  private void processMessage(final ServiceBusReceivedMessage message) {
    try {
	  // some business logic for processing the message...
      receiver.complete(message);
    } catch (Exception ex) {
      log.error("Failed to process message: " + message.getBody(), ex);
      receiver.abandon(message);
    }
  }

   private void processError(final Throwable throwable) {
    if (Exceptions.isRetryExhausted(throwable.getCause())) {
      log.error("No more retries...");
      return;
    }
    log.error("Failed to processes incoming message.", throwable);
  }

  private void finished() {
    log.info("Finished processing messages.");
  }

  @PreDestroy
  public void disconnect() {
    if (subscription != null) {
      subscription.dispose();
    }
    if (receiver != null) {
      receiver.close();
    }
    log.info("Stopped receiving messages.");
  }

  @Override
  public void onApplicationEvent(final ApplicationStartedEvent event) {
    try {
      log.info("Connecting to service bus...");
      connect();
    } catch (Throwable t) {
      log.error("Failed to initialize connection to Azure Service Bus.", t);
      throw t;
    }
  }
}
```

**Expected behavior**
After calling ServiceBusReceiverAsyncClient.complete(message), the delivery count in Service Bus Explorer should be increased and message must not appear in Dead-letter queue.

**Setup (please complete the following information):**
 - OS: [Windows 10 Enterprise ]
 - IDE: [IntelliJ]
 - Library/Libraries: azure-messaging-servicebus:7.14.4
 - Java version: 11 
 - Frameworks: Spring Boot

**Additional context**
Seems like the problem is similar to https://github.com/Azure/azure-sdk-for-java/issues/19248

Properties of message in dead-letter queue:
![image](https://github.com/Azure/azure-sdk-for-java/assets/3921099/f2122410-0ba7-4152-a8a0-868abe86df98)

**Information Checklist**
Kindly make sure that you have added all the following information above and checkoff the required fields otherwise we will treat the issuer as an incomplete report
- [x] Bug Description Added
- [x] Repro Steps Added
- [x] Setup information Added

**Comment by anuchandy** [comment]
Hello @ingmarkellner,

The ServiceBusReceiverAsyncClient.complete(message) returns a Reactor Mono, representing the complete work that will run only when subscribed. In the sample application, there is no continuation of Reactor chain from the complete () call, so no network call.

The ServiceBusReceiverAsyncClient is Low-Level Client, which we don’t recommend from Production scenarios. For production scenarios, the Higher-Level Client, ServiceBusProcessorClient is strongly recommended. The ServiceBusProcessorClient has simpler APIs and has additional resilience built-in into it. Please see this sample https://github.com/Azure/azure-sdk-for-java/blob/main/sdk/servicebus/azure-messaging-servicebus/src/samples/java/com/azure/messaging/servicebus/ServiceBusProcessorPeekLockReceiveSample.java

**Comment by ingmarkellner** [comment]
Hello @anuchandy,

thanks for the quick reply. 
I reworked the code to use ServiceBusProcessorClient and it works as expected!
I very much appreciate your support!

**Comment by ingmarkellner** [comment]
Hello @anuchandy,

thanks for the quick reply.
I reworked the code to use ServiceBusProcessorClient and it works as expected!
I very much appreciate your support!
