### ISSUE TITLE
unable to connect keyvault using workload identity using JAVA sdk

### ISSUE THREAD

**Issue by suresh-chinnasamy** [Azure/azure-sdk-for-java#36976]
Unable to get token using managedidentity authentication which is a wrapper enabled for workload identity as per microsoft support case confirmation

Looking for solution using AD workload identity in AKS cluster to connect to azure key vault instance to retrieve the secrets using Azure Java SDK based client library and its mangedcredentialbuilder() class.

06:53:19.070 [Thread-4] ERROR com.azure.identity.ManagedIdentityCredential - Azure Identity => ERROR in getToken() call for scopes [https://vault.azure.net/.default]: Managed Identity authentication is not available.
06:53:19.074 [Thread-4] ERROR com.azure.core.implementation.AccessTokenCache - Failed to acquire a new access token.
06:53:49.279 [Thread-5] ERROR com.azure.identity.ManagedIdentityCredential - Azure Identity => ERROR in getToken() call for scopes [https://vault.azure.net/.default]: Managed Identity authentication is not available.
06:53:49.280 [Thread-5] ERROR com.azure.core.implementation.AccessTokenCache - Failed to acquire a new access token.

**Comment by g2vinay** [comment]
@suresh-chinnasamy 

Thank you for reporting this.
From your description, it comes across that you are looking to use Workload Identity, but are using Managed Identity credential.

I'd recommend using `WorkloadIdentityCredential` via `WorkloadIdentityCredentialBuilder` class.
