### ISSUE TITLE
[OpenAI] Support random generated boundary value of `multipart/form-data` in TestProxy

### ISSUE THREAD

**Issue by mssfang** [Azure/azure-sdk-for-java#36982]
Currently, we [hard-coded ](https://github.com/Azure/azure-sdk-for-java/blob/main/sdk/openai/azure-ai-openai/src/main/java/com/azure/ai/openai/implementation/MultipartDataHelper.java#L58 )the `boundary` value of `multipart/form-data`.  

Session [recorded JSON](https://github.com/Azure/azure-sdk-assets/blob/java/openai/azure-ai-openai_2290060af1/java/sdk/openai/azure-ai-openai/src/test/resources/session-records/NonAzureOpenAISyncClientTest.testGetAudioTranslationTextPlain%5B1%5D.json#L10
) File.

We should support the randomly generated boundary and it should pass the test when running tests in PLAYBACK mode.

Investigate and see if we can support it in TestProxy. Might be worth taking a look at how Azure Core supports it.

**Comment by alzimmermsft** [comment]
This should be solvable using `TestResourceNamer.randomUuid()`.

https://github.com/Azure/azure-sdk-for-java/blob/main/sdk/core/azure-core-test/src/main/java/com/azure/core/test/utils/TestResourceNamer.java#L132

**Comment by mssfang** [comment]
Thanks @alzimmermsft. Will give it a try.
