### ISSUE TITLE
[BUG] Unnecessary WARN floods our logs when checking for an absent blob

### ISSUE THREAD

**Issue by snalli** [Azure/azure-sdk-for-java#37117]
**Describe the bug**
When we call getProperties on an absent blob, the http response does not have content-type.
The serializerEncoding complains of the missing content-type and this floods our logs. 
We cannot turn off WARN so this must be fixed on the azure-sdk side.

***Exception or Stack Trace***
Add the exception log and stack trace if available
```
2023/10/10 07:59:40.079 WARN [SerializerEncoding] [reactor-http-epoll-2] [ambry-vcr] [] 'Content-Type' not found. Returning default encoding: JSON
2023/10/10 07:59:40.079 ERROR [AzureCloudDestinationSync] [VcrReplicaThread-Intra-0-ei4] [ambry-vcr] [] Failed to get blob properties for (ambry-ei-1037/AAYQAwCLAAIAAQAAAAAAAAQN1bT-AAP7TRaeusluyYE8Fw) from Azure blob storage due to Status code 404, (BlobNotFound)
```

**To Reproduce**
Simply call getProperties on an absent blob like so

```
      return azureStorageClient.getBlobContainerClient(containerName).getBlobClient(blobFilePath).getProperties();\
```

***Code Snippet***
Add the code snippet that causes the issue.

```
    /**
     * Determines the serializer encoding to use based on the Content-Type header.
     *
     * @param headers the headers to check the encoding for.
     * @return the serializer encoding to use for the body. {@link #JSON} if there is no Content-Type header or an
     * unrecognized Content-Type encoding is returned.
     */
    public static SerializerEncoding fromHeaders(HttpHeaders headers) {
        final String mimeContentType = HttpHeadersHelper.getValueNoKeyFormatting(headers, "content-type");
        if (mimeContentType == null || mimeContentType.isEmpty()) {
            LOGGER.warning("'{}' not found. Returning default encoding: {}", CONTENT_TYPE, DEFAULT_ENCODING);
            return DEFAULT_ENCODING;
        }
```

**Expected behavior**

No WARNINGS !

**Screenshots**

**Setup (please complete the following information):**
 - OS: [e.g. iOS] CentOS 7
 - IDE: [e.g. IntelliJ]
 - Library/Libraries: [e.g. com.azure:azure-core:1.16.0 (groupId:artifactId:version)] azure-core-1.34.0.jar
 - Java version: [e.g. 8] JDK 11
 - App Server/Environment: [e.g. Tomcat, WildFly, Azure Function, Apache Spark, Databricks, IDE plugin or anything special]
 - Frameworks: [e.g. Spring Boot, Micronaut, Quarkus, etc] 

If you suspect a dependency version mismatch (e.g. you see `NoClassDefFoundError`, `NoSuchMethodError` or similar), please check out [Troubleshoot dependency version conflict article](https://aka.ms/azsdk/java/dependency/troubleshoot) first. If it doesn't provide solution for the problem, please provide:
- verbose dependency tree (`mvn dependency:tree -Dverbose`)
- exception message, full stack trace, and any available logs

**Additional context**

Similar ticket (not from me) https://github.com/Azure/Azurite/issues/2157

**Information Checklist**
Kindly make sure that you have added all the following information above and checkoff the required fields otherwise we will treat the issuer as an incomplete report
- [x ] Bug Description Added
- [ x] Repro Steps Added
- [ x] Setup information Added

**Comment by alzimmermsft** [comment]
Thank you for filing this issue @snalli.

This should be fixed in a recent change ([PR #37055](https://github.com/Azure/azure-sdk-for-java/pull/37055)) and should be available in an upcoming release of the Storage libraries.

**Comment by joshfree** [comment]
@alzimmermsft i noticed the PR above doesn't update a CHANGELOG - it would be worth adding 1-line about this so it's more discoverable.

**Comment by alzimmermsft** [comment]
A Storage release should be done in the next week or so. In the meantime, another option, if you have access to the logging configurations, is excluding `com.azure.core.util.serializer.SerializerEncoding` from being able to log.

**Comment by snalli** [comment]
@alzimmermsft is there are new release of the storage sdk ?

**Comment by snalli** [comment]
@alzimmermsft is there are new release of the storage sdk ?

**Comment by alzimmermsft** [comment]
A new version of the Storage libraries shipped last night:

https://central.sonatype.com/artifact/com.azure/azure-storage-blob/12.24.1/dependencies
