### ISSUE TITLE
Is there any option to set Metadata for BlobAsyncClient delete methods?

### ISSUE THREAD

**Issue by kirankumar994** [Azure/azure-sdk-for-java#37115]
I am trying to delete a blob in a container. For that, I would like to set a field called deletedBy in the blob Metadata so that I would know who is deleting the blob. 

I am able to set the metadata and then delete the blob, but it creates two different versions for both metadata and deleting which I don't want to. Either I want to set metadata and delete in a single call or setting metadata in options and use them in any of the delete methods which is also not available as of I know. 

I did the same for uploading a blob. I've set metadata in BlobParallelUploadOptions and upload the blob which works fine. I want the similar way to delete the blob. Providing a code snippet how I do upload a blob. 

BlobParallelUploadOptions options = new BlobParallelUploadOptions(BinaryData.fromBytes(data))
                            .setMetadata(document.getMetadata());
                    return blobAsyncClient.uploadWithResponse(options);

**Comment by alzimmermsft** [comment]
Thank you for asking this question @kirankumar994.

Unfortunately setting metadata while deleting a blob isn't possible as this isn't supported by the REST API for deleting a blob, https://learn.microsoft.com/rest/api/storageservices/delete-blob. And what you're seeing with uploading a blob the REST API does support setting metadata during the uploading process, https://learn.microsoft.com/rest/api/storageservices/put-blob.

fyi @ibrahimrabab

**Comment by ibrahimrabab** [comment]
Hi @kirankumar994 

Thanks for reaching out! Like @alzimmermsft mentioned, setting metadata while deleting a blob isn't supported by the REST API. Something you can try is calling `blobClient.setMetadata(Map<String, String> metadata)`,

`
        BlobContainerClient containerClient = blobServiceClient.getBlobContainerClient("issue37115");
        containerClient.createIfNotExists();
        BlobClient blobClient = containerClient.getBlobClient("test");
        Map<String, String> metadata = new HashMap<>();
        metadata.put("key1", "value1");
        byte[] bytes = getRandomByteArray(1024 * 1024);
        BlobParallelUploadOptions options = new BlobParallelUploadOptions(BinaryData.fromBytes(bytes))
            .setMetadata(metadata);
        System.out.println("uploading");
        blobClient.uploadWithResponse(options, null, null);

        metadata.put("deletedBy", "accountName");
        System.out.println("setting metadata");
        blobClient.setMetadata(metadata);

        System.out.println("deleting");
        blobClient.delete();
`

This way you can set the metadata before calling `delete()`. But one thing to note is that once you delete the blob, you cannot retrieve the properties of the blob unless you undelete it (which is only available for soft delete accounts). So, viewing metadata of a deleted blob may not be possible. 

Let us know if this helps!

**Comment by kirankumar994** [comment]
Hi Rabab Ibrahim,

Thank you for your response. What I meant was I want to set metadata in the
options while deleting the blob, so that it won't create a new
version again if I set metadata using blobClient.setMetadata(). I have
already tried with that, but I am not expecting that to be the case here.
For example, I can set metadata in the BlobCopyFromUrlOptions for cloning
the blob using blobClient.copyFromUrlWithResponse. I still have this open
issue in my bucket. Please let me know if there is any alternate solution
to achieve this case. Again, I do not want to create a new version just by
setting the metadata for the blob.

Thank you,
Kiran K

**Comment by ibrahimrabab** [comment]
@kirankumar994 
Unfortunately, this behavior is just not supported by the SDK service. You cannot set the metadata on a blob while deleting, and once the blob is deleted it is not possible to view its properties unless you have soft -delete enabled and undelete the blob.

Apologies if we could not help you resolve this, but please feel free to reach out with any additional questions.
