### ISSUE TITLE
[BUG] autorest --latest --use=@autorest/java@latest sdk/<service>/<module>/swagger/readme.md

### ISSUE THREAD

**Issue by wuweiran** [Azure/azure-sdk-for-java#37135]
Are you sure this command line in [wiki](https://github.com/Azure/azure-sdk-for-java/wiki/Protocol-Methods-Quickstart-with-AutoRest) is not `autorest --java --use=@autorest/java@latest sdk/<service>/<module>/swagger/readme.md`??

**Comment by srnagar** [comment]
Fixed the wiki. Thank you for reporting the issue.
