### ISSUE TITLE
[BUG] JsonParseException when fetching UserDelegationKey

### ISSUE THREAD

**Issue by noviceamateur** [Azure/azure-sdk-for-java#37157]
**Describe the bug**
BlobServiceClient.getUserDelegationKey throws an exception . It looks like the SDK is expecting a JSON but Azure Storage is returning XML response.

***Exception or Stack Trace***
`" com.fasterxml.jackson.core.JsonParseException: Unexpected character ('<' (code 60)): expected a valid value (JSON String, Number, Array, Object or token 'null', 'true' or 'false')
at [Source: (byte[])"﻿<?xml version="1.0" encoding="utf-8"?><UserDelegationKey><SignedOid>644f3e8d-51c6-4652-a23c-44e2b3ebe9c3</SignedOid><SignedTid>fa7b1b5a-7b34-4387-94ae-d2c178decee1</SignedTid><SignedStart>2023-10-10T10:11:44Z</SignedStart><SignedExpiry>2023-10-13T10:16:44Z</SignedExpiry><SignedService>b</SignedService><SignedVersion>2023-08-03</SignedVersion><Value>xxx</Value></UserDelegationKey>"`

StackTrace ->
`
:"com.azure.core.exception.HttpResponseException: Deserialization Failed.","stacktrace":"com.azure.core.exception.HttpResponseException: Deserialization Failed.\n\tat c.a.c.i.s.HttpResponseBodyDecoder.decodeByteArray(HttpResponseBodyDecoder.java:88)\n\tat c.a.c.i.s.HttpResponseDecoder$HttpDecodedResponse.getDecodedBody(HttpResponseDecoder.java:93)\n\tat r.c.p.Mono.lambda$mapNotNull$28(Mono.java:3464)\n\tat r.c.p.FluxHandle$HandleSubscriber.onNext(FluxHandle.java:110)\n\tat r.c.p.Operators$ScalarSubscription.request(Operators.java:2400)\n\tat r.c.p.FluxHandle$HandleSubscriber.request(FluxHandle.java:269)\n\tat r.c.p.FluxMap$MapSubscriber.request(FluxMap.java:164)\n\tat r.c.p.Operators$MultiSubscriptionSubscriber.set(Operators.java:2196)\n\tat r.c.p.Operators$MultiSubscriptionSubscriber.onSubscribe(Operators.java:2070)\n\tat r.c.p.FluxMap$MapSubscriber.onSubscribe(FluxMap.java:92)\n\tat r.c.p.FluxHandle$HandleSubscriber.onSubscribe(FluxHandle.java:87)\n\tat r.c.p.MonoJust.subscribe(MonoJust.java:55)\n\tat r.c.p.MonoDefer.subscribe(MonoDefer.java:52)\n\tat r.c.p.InternalMonoOperator.subscribe(InternalMonoOperator.java:64)\n\tat r.c.p.MonoFlatMap$FlatMapMain.onNext(MonoFlatMap.java:157)\n\tat r.c.p.Operators$MonoSubscriber.complete(Operators.java:1839)\n\tat r.c.p.MonoFlatMap$FlatMapMain.onNext(MonoFlatMap.java:151)\n\tat r.c.p.FluxMapFuseable$MapFuseableSubscriber.onNext(FluxMapFuseable.java:129)\n\tat r.c.p.FluxHide$SuppressFuseableSubscriber.onNext(FluxHide.java:137)\n\tat r.c.p.FluxMapFuseable$MapFuseableSubscriber.onNext(FluxMapFuseable.java:129)\n\tat r.c.p.FluxHide$SuppressFuseableSubscriber.onNext(FluxHide.java:137)\n\tat r.c.p.FluxOnErrorResume$ResumeSubscriber.onNext(FluxOnErrorResume.java:79)\n\tat r.c.p.Operators$MonoSubscriber.complete(Operators.java:1839)\n\tat r.c.p.MonoFlatMap$FlatMapMain.onNext(MonoFlatMap.java:151)\n\tat r.c.p.Operators$MonoSubscriber.complete(Operators.java:1839)\n\tat r.c.p.MonoFlatMap$FlatMapMain.onNext(MonoFlatMap.java:151)\n\tat r.c.p.MonoIgnoreThen$ThenIgnoreMain.complete(MonoIgnoreThen.java:292)\n\tat r.c.p.MonoIgnoreThen$ThenIgnoreMain.onNext(MonoIgnoreThen.java:187)\n\tat r.c.p.FluxMapFuseable$MapFuseableSubscriber.onNext(FluxMapFuseable.java:129)\n\tat r.c.p.Operators$MonoSubscriber.complete(Operators.java:1839)\n\tat r.c.p.MonoFlatMap$FlatMapMain.onNext(MonoFlatMap.java:151)\n\tat r.c.p.SerializedSubscriber.onNext(SerializedSubscriber.java:99)\n\tat r.c.p.FluxRetryWhen$RetryWhenMainSubscriber.onNext(FluxRetryWhen.java:174)\n\tat r.c.p.FluxOnErrorResume$ResumeSubscriber.onNext(FluxOnErrorResume.java:79)\n\tat r.c.p.Operators$MonoInnerProducerBase.complete(Operators.java:2666)\n\tat r.c.p.MonoSingle$SingleSubscriber.onComplete(MonoSingle.java:180)\n\tat r.c.p.MonoFlatMapMany$FlatMapManyInner.onComplete(MonoFlatMapMany.java:260)\n\tat r.c.p.FluxMap$MapSubscriber.onComplete(FluxMap.java:144)\n\tat r.c.p.FluxDoFinally$DoFinallySubscriber.onComplete(FluxDoFinally.java:128)\n\tat r.c.p.FluxMapFuseable$MapFuseableSubscriber.onComplete(FluxMapFuseable.java:152)\n\tat r.c.p.Operators$MonoSubscriber.complete(Operators.java:1840)\n\tat r.c.p.MonoCollect$CollectSubscriber.onComplete(MonoCollect.java:160)\n\tat r.c.p.FluxHandle$HandleSubscriber.onComplete(FluxHandle.java:220)\n\tat r.c.p.FluxMap$MapConditionalSubscriber.onComplete(FluxMap.java:275)\n\tat r.n.c.FluxReceive.onInboundComplete(FluxReceive.java:400)\n\tat r.n.c.ChannelOperations.onInboundComplete(ChannelOperations.java:419)\n\tat r.n.c.ChannelOperations.terminate(ChannelOperations.java:473)\n\tat r.n.h.c.HttpClientOperations.onInboundNext(HttpClientOperations.java:703)\n\tat r.n.c.ChannelOperationsHandler.channelRead(ChannelOperationsHandler.java:93)\n\tat i.n.c.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)\n\tat i.n.c.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)\n\tat i.n.c.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)\n\tat i.n.c.CombinedChannelDuplexHandler$DelegatingChannelHandlerContext.fireChannelRead(CombinedChannelDuplexHandler.java:436)\n\tat i.n.h.c.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:336)\n\tat i.n.h.c.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:308)\n\tat i.n.c.CombinedChannelDuplexHandler.channelRead(CombinedChannelDuplexHandler.java:251)\n\tat i.n.c.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)\n\tat i.n.c.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)\n\tat i.n.c.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)\n\tat i.n.h.s.SslHandler.unwrap(SslHandler.java:1373)\n\tat i.n.h.s.SslHandler.decodeJdkCompatible(SslHandler.java:1236)\n\tat i.n.h.s.SslHandler.decode(SslHandler.java:1285)\n\tat i.n.h.c.ByteToMessageDecoder.decodeRemovalReentryProtection(ByteToMessageDecoder.java:519)\n\tat i.n.h.c.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:458)\n\tat i.n.h.c.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:280)\n\tat i.n.c.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)\n\tat i.n.c.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)\n\tat i.n.c.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)\n\tat i.n.c.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410)\n\tat i.n.c.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)\n\tat i.n.c.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)\n\tat i.n.c.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919)\n\tat i.n.c.k.AbstractKQueueStreamChannel$KQueueStreamUnsafe.readReady(AbstractKQueueStreamChannel.java:544)\n\tat i.n.c.k.AbstractKQueueChannel$AbstractKQueueUnsafe.readReady(AbstractKQueueChannel.java:383)\n\tat i.n.c.k.KQueueEventLoop.processReady(KQueueEventLoop.java:213)\n\tat i.n.c.k.KQueueEventLoop.run(KQueueEventLoop.java:291)\n\tat i.n.u.c.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997)\n\tat i.n.u.i.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)\n\tat i.n.u.c.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)\n\tat j.l.Thread.run(Thread.java:829)\n\tSuppressed: java.lang.Exception: #block terminated with an error\n\t\tat reactor.core.publisher.BlockingSingleSubscriber.blockingGet(BlockingSingleSubscriber.java:99)\n\t\tat reactor.core.publisher.Mono.block(Mono.java:1742)\n\t\tat com.azure.storage.common.implementation.StorageImplUtils.blockWithOptionalTimeout(StorageImplUtils.java:147)\n\t\tat com.azure.storage.blob.BlobServiceClient.getUserDelegationKeyWithResponse(BlobServiceClient.java:597)\n\t\tat com.azure.storage.blob.BlobServiceClient.getUserDelegationKey(BlobServiceClient.java:569)\n\t\tat com.adobe.acp.blobstore.azure.AzureBlobStore.createUserDelegationKey(AzureBlobStore.java:447)\n\t\tat com.adobe.acp.blobstore.azure.AzureBlobStore.generateSharedAccessSignature(AzureBlobStore.java:366)\n\t\tat com.adobe.acp.blobstore.azure.AzureBlobStore.initiateLegacyBlockUpload(AzureBlobStore.java:156)\n\t\tat com.adobe.acp.blobstore.azure.AzureBlobStore.initiateLegacyBlockUpload(AzureBlobStore.java:89)\n\t\tat com.adobe.acp.operation.blocktransfer.AbstractInitiateBlockUploadOperation.runLegacy(AbstractInitiateBlockUploadOperation.java:276)\n\t\tat com.adobe.acp.operation.blocktransfer.AbstractInitiateBlockUploadOperation.run(AbstractInitiateBlockUploadOperation.java:114)\n\t\tat com.adobe.acp.api.ACPAbstractResourceAPI.initiateBlockUpload(ACPAbstractResourceAPI.java:2460)\n\t\tat com.adobe.acp.api.ACPAbstractResourceAPI.processLegacyBlockUploadRequest(ACPAbstractResourceAPI.java:2549)\n\t\tat com.adobe.acp.api.ACPLegacyBlockTransferPathAPI.legacyBlockUpload(ACPLegacyBlockTransferPathAPI.java:126)\n\t\tat java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)\n\t\tat java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)\n\t\tat java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)\n\t\tat java.base/java.lang.reflect.Metho","exception_status_code":"NONE","message":"An unexpected error occurred: Deserialization Failed."}
`

**To Reproduce**

***Code Snippet***
`    
String endpoint = String.format(Locale.ROOT, "https://%s.blob.core.windows.net", "<storage account name>");

    BlobServiceClient blobServiceClient = new BlobServiceClientBuilder().endpoint(endpoint).credential(new DefaultAzureCredentialBuilder().build()).buildClient();

    OffsetDateTime keyStart = OffsetDateTime.now();

    OffsetDateTime keyExpiry = OffsetDateTime.now().plusDays(7);

    UserDelegationKey userDelegationKey = blobServiceClient.getUserDelegationKey(keyStart, keyExpiry);

    BlobContainerSasPermission blobContainerSas = new BlobContainerSasPermission();

    blobContainerSas.setReadPermission(true);

    BlobServiceSasSignatureValues blobServiceSasSignatureValues = new BlobServiceSasSignatureValues(keyExpiry,blobContainerSas);

    BlobContainerClient blobContainerClient=blobServiceClient.getBlobContainerClient("<container name>");

    if (!blobContainerClient.exists())
      blobContainerClient.create();

    String sas = blobContainerClient.generateUserDelegationSas(blobServiceSasSignatureValues, userDelegationKey);
`

Using these dependencies ->
`        <dependency>
            <groupId>com.azure</groupId>
            <artifactId>azure-identity</artifactId>
            <version>1.4.6</version>
        </dependency>
        <dependency>
            <groupId>com.azure</groupId>
            <artifactId>azure-storage-blob</artifactId>
            <version>12.24.0</version>
        </dependency>
        <dependency>
            <groupId>com.azure</groupId>
            <artifactId>azure-core</artifactId>
            <version>1.42.0</version>
        </dependency>`

Using Azure Service Principal for authentication.

**Expected behavior**
There should not be any error in getting the UserDelegationKey object.

**Screenshots**

**Setup (please complete the following information):**
 - OS: [e.g. iOS] - MacOS
 - IDE: [e.g. IntelliJ] - IntelliJ
 - Library/Libraries: [e.g. com.azure:azure-core:1.16.0 (groupId:artifactId:version)]
 - Java version: [e.g. 8]  - 8
 - App Server/Environment: [e.g. Tomcat, WildFly, Azure Function, Apache Spark, Databricks, IDE plugin or anything special]
 - Frameworks: [e.g. Spring Boot, Micronaut, Quarkus, etc] 

If you suspect a dependency version mismatch (e.g. you see `NoClassDefFoundError`, `NoSuchMethodError` or similar), please check out [Troubleshoot dependency version conflict article](https://aka.ms/azsdk/java/dependency/troubleshoot) first. If it doesn't provide solution for the problem, please provide:
- verbose dependency tree (`mvn dependency:tree -Dverbose`)
- exception message, full stack trace, and any available logs

**Additional context**

**Information Checklist**
Kindly make sure that you have added all the following information above and checkoff the required fields otherwise we will treat the issuer as an incomplete report
- [x] Bug Description Added
- [x] Repro Steps Added
- [x] Setup information Added

**Comment by alzimmermsft** [comment]
Thanks for filing this issue @noviceamateur.

Looking at the versions you're using, there is a lot of skew between them. Could you update them to align their dependencies and see if the issue can still be reproduced?

```xml
<dependency>
  <groupId>com.azure</groupId>
  <artifactId>azure-identity</artifactId>
  <version>1.10.1</version> 
</dependency> 
<dependency>
  <groupId>com.azure</groupId>
  <artifactId>azure-storage-blob</artifactId>
  <version>12.24.0</version>
</dependency>
<dependency>
  <groupId>com.azure</groupId>
  <artifactId>azure-core</artifactId>
  <version>1.43.0</version>
</dependency>
```

**Comment by noviceamateur** [comment]
Updating to these versions fixed the issue
