### ISSUE TITLE
[BUG] Service Bus receiving of messages throws exceptions when using sessionProcessor with maxConcurrentSessions > 50 

### ISSUE THREAD

**Issue by Maxeh** [Azure/azure-sdk-for-java#37160]
**Describe the bug**
When using a sessionProcessor with maxConcurrentSessions with a value > 50 the processing throws InterruptedExceptions and other ServiceBusExceptions when complete() is called. With a value < 50 the processing works, but is way too slow for our use case.

The configuration looks like this:

```
final ServiceBusProcessorClient receiver = new ServiceBusClientBuilder()
          .credential(namespace, new ClientSecretCredentialBuilder()
                .tenantId(tenantId)
                .clientId(clientId)
                .clientSecret(clientSecret)
                .build())
          .sessionProcessor()
          .disableAutoComplete()
          .receiveMode(ServiceBusReceiveMode.PEEK_LOCK)
          .topicName(topicName)
          .prefetchCount(0)
          .maxConcurrentCalls(1)
          .maxConcurrentSessions(80)
          .sessionIdleTimeout(Duration.ofSeconds(10))
          .subscriptionName(subscriptionName)
          .processError(this::processError)
          .processMessage(this::processMessage)
          .buildProcessorClient();
receiver.start();
```

Might be related to: https://github.com/Azure/azure-sdk-for-java/issues/37158

**To Reproduce**
Use the code above to create a ServiceBusProcessorClient, try to receive 1000 messages all with a *different* sessionId. Processing will stop in between and InterruptedExceptions are thrown when complete() is called.

You can use the following code to create 1000 messages with 1000 different sessionIds:

```
@Test
public void sendMessages() {
  final ServiceBusClientBuilder.ServiceBusSenderClientBuilder serviceBusSenderClientBuilder =
      new ServiceBusClientBuilder()
        .credential(NAMESPACE, new ClientSecretCredentialBuilder()
            .tenantId(TENANT_ID)
            .clientId(CLIENT_ID)
            .clientSecret(CLIENT_SECRET)
            .build())
        .sender()
        .topicName(TOPIC);

  try (final ServiceBusSenderClient sender = serviceBusSenderClientBuilder.buildClient()) {
    for (int i = 0; i < 1000; i++) {
      final String sessionId = UUID.randomUUID().toString();
      for (int e = 0; e < 1; e++) {
        final ServiceBusMessage serviceBusMessage = new ServiceBusMessage(getServiceBusMessage());
        serviceBusMessage.setMessageId(UUID.randomUUID().toString());
        serviceBusMessage.setSessionId(sessionId);
        sender.sendMessage(serviceBusMessage);
        log.info("Message with messageId {} sent successfully.", serviceBusMessage.getMessageId());
      }
    }
  }
}
```
**Expected behavior**
Processing should work without interruptions and exceptions.

**Setup (please complete the following information):**
 - OS: Mac
 - IDE: IntelliJ
 - Library/Libraries: 'com.azure:azure-messaging-servicebus:7.14.4'
 - Java version: 17
 - App Server/Environment: Tomcat
 - Frameworks: Spring Boot

**Information Checklist**
Kindly make sure that you have added all the following information above and checkoff the required fields otherwise we will treat the issuer as an incomplete report
- [x] Bug Description Added
- [x] Repro Steps Added
- [x] Setup information Added

**Comment by joshfree** [comment]
@anuchandy could you follow up with @Maxeh

**Comment by anuchandy** [comment]
Following upon this https://github.com/Azure/azure-sdk-for-java/issues/37158 first, so we don’t duplicate the effort / communication.

**Comment by anuchandy** [comment]
Refer [this ](https://github.com/Azure/azure-sdk-for-java/issues/37158#issuecomment-1765053122) comment, the underlying cause is the same. 

As mentioned in that comment, this is addressed in the on-going work related to Prefetch reliability. I’ve tested this use case also using the working PR https://github.com/Azure/azure-sdk-for-java/pull/34854 and it works as expected. I’ll keep this issue open to track 34854.

The only feedback I’ve is – limit the maxConcurrentSessions to 25-30 in one ProcessorClient instance, then either scale by spinning more ProcessorClient instances where each instance is created from separate builder instance, Or scale horizontally across multiple nodes (each nodes hosts ProcessorClient instance.)

**Comment by anuchandy** [comment]
Refer [this ](https://github.com/Azure/azure-sdk-for-java/issues/37158#issuecomment-1765053122) comment, the underlying cause is the same. 

As mentioned in that comment, this is addressed in the on-going work related to Prefetch reliability. I’ve tested this use case also using the working PR https://github.com/Azure/azure-sdk-for-java/pull/34854 and it works as expected. I’ll keep this issue open to track 34854.

The only feedback I’ve is – limit the maxConcurrentSessions to 25-30 in one ProcessorClient instance, then scale horizontally across multiple nodes.

**Comment by anuchandy** [comment]
Update on the prefetch reliability work mentioned in the above comment.

We've shipped new session processor (a.k.a. V2 session processor) as beta 7.15.0-beta.5, this addresses InterruptedException and ServiceBusException that were happening in 7.14.*. The steps to use V2 session processor -

### Add 7.15.0-beta.5 dependency

```xml
<dependency>
    <groupId>com.azure</groupId>
    <artifactId>azure-messaging-servicebus</artifactId>
    <version>7.15.0-beta.5</version>
</dependency>
```

### Opt-in for new session processor (V2) functionality 

```java
private static final String V2_SESSION_PROCESSOR_CONFIGURATION_KEY = "com.azure.messaging.servicebus.session.processor.asyncReceive.v2";
ServiceBusProcessorClient processor = new ServiceBusClientBuilder()
        .fullyQualifiedNamespace(Config.FULLY_QUALIFIED_NAMESPACE)
        .credential(Config.CREDENTIAL)
        .configuration(new com.azure.core.util.ConfigurationBuilder()
          .putProperty(V2_SESSION_PROCESSOR_CONFIGURATION_KEY, "true") // 'false' by default, so opt-in to enable V2.
          .build())
        .sessionProcessor()
        .topicName(Config.TOPIC)
        .subscriptionName(Config.SUBSCRIPTION)
        .disableAutoComplete()
        .processMessage(processMessage)
        .processError(processError)
        .maxAutoLockRenewDuration(Duration.ofMinutes(5))
        .receiveMode(ServiceBusReceiveMode.PEEK_LOCK)
        .subQueue(SubQueue.NONE)
        .maxConcurrentSessions(50)
        .maxConcurrentCalls(1)
        .prefetchCount(0)
        .sessionIdleTimeout(Duration.ofMinutes(1))
        .buildProcessorClient();
```

**Comment by JRiggenbach** [comment]
This appears to be the fix we've been waiting for as well.  Any ETA on when will 7.15.0 move out of beta?

**Comment by anuchandy** [comment]
Resolving this. Refer https://learn.microsoft.com/en-us/azure/developer/java/sdk/troubleshooting-messaging-service-bus-overview#upgrade-to-715x for details about version 7.15.x and how to opting-in new session rework.
