### ISSUE TITLE
[QUERY] When to replace io.netty:netty-handler

### ISSUE THREAD

**Issue by mikexie1992** [Azure/azure-sdk-for-java#37161]
### Library name and version

Azure Service Bus 7.14.3

### Query/Question

New CVEs with netty project are reported by community and then our project is blocked by our security review. I want to ask when you will replace io.netty:netty-handler? Could you give me any feedbacks?

### Environment

prod

**Comment by NipunaRanasinghe** [comment]
We are having a similar issue and blocked until we get a SDK version having the new netty version. Appreciate a prompt resolution for this.

**Comment by jairmyree** [comment]
@NipunaRanasinghe @mikexie1992 Thank you for reaching out. I'll begin working on a resolution immediately and will inform you when the issue has been resolved.

**Comment by jairmyree** [comment]
@NipunaRanasinghe @mikexie1992 Please see this comment:
https://github.com/Azure/azure-sdk-for-java/issues/37152#issuecomment-1759921522
To reiterate it, we do not use Netty directly but rather use it through Reactor Netty which has hostname verification enabled by default. Therefore, our SDK is not vulnerable to the CVE. Please share this information with your team and see if the alert can be dismissed.
