### ISSUE TITLE
Ref docs issue

### ISSUE THREAD

**Issue by Menghua1** [Azure/azure-sdk-for-java#37178]
Error:

> Traceback (most recent call last):
>   File "D:\a\_work\1\s\target_repo\update_toc.py", line 6, in <module>
>     import yaml
> ModuleNotFoundError: No module named 'yaml'
> ##[error]The process 'C:\hostedtoolcache\windows\Python\3.10.11\x64\python.exe' failed with exit code 1

- https://apidrop.visualstudio.com/Content%20CI/_build/results?buildId=391326&view=results

@danieljurek for notification.

**Comment by danieljurek** [comment]
Closing. This was a transient error.
