### ISSUE TITLE
[FEATURE REQ]Add custom metrics (for example for RU consumption) in Cosmso DB Spark connector

### ISSUE THREAD

**Issue by FabianMeiswinkel** [Azure/azure-sdk-for-java#37172]
https://github.com/apache/spark/pull/31476
https://github.com/apache/spark/pull/33239
https://github.com/apache/spark/pull/31451
https://github.com/apache/spark/pull/37205
https://github.com/apache/spark/blob/7663fdfa3e84d7231784c39e4d3445e6f2f079fd/sql/catalyst/src/main/java/org/apache/spark/sql/connector/read/Scan.java#L112-L127

https://github.com/apache/spark/blob/7663fdfa3e84d7231784c39e4d3445e6f2f079fd/sql/catalyst/src/main/java/org/apache/spark/sql/connector/write/Write.java#L67-L73

https://github.com/apache/spark/pull/31451/files#diff-85995a3a595fa6c7b2d134cfa17c25a698924398ff85105da49a0f1a714b92df

**Comment by FabianMeiswinkel** [comment]
Supported in Spark 3.2 and above

**Comment by kushagraThapar** [comment]
Closing this. If it is still valid, please re-open this.
