### ISSUE TITLE
[BUG] metricsQueryClient.listMetricNamespaces returns partial list of namespaces

### ISSUE THREAD

**Issue by shevah** [Azure/azure-sdk-for-java#37216]
**Describe the bug**
I am trying to list all possible namespaces of a given resource. I have tried multiple ways and all return a partial list of available namespaces while from the Azure Monitor Metrics UI I can see all possible namespaces.

**To Reproduce**
here is a minimal program returns a partial namespace list containing only:`microsoft.storage/storageaccount` while misses `microsoft.storage/storageaccount/blobservices` and others

```kotlin
val tenantId = "XXXX"
val clientId = "XXXX"
val clientSecret = "XXX"

val clientSecretCredential: ClientSecretCredential = ClientSecretCredentialBuilder()
    .clientId(clientId)
    .clientSecret(clientSecret)
    .tenantId(tenantId)
    .build()

val metricsQueryClient = MetricsQueryClientBuilder()
    .credential(clientSecretCredential)
    .buildClient()

val id = "/subscriptions/XXXXX/resourceGroups/XXXX/providers/Microsoft.Storage/storageAccounts/storageaccount"
println(metricsQueryClient.listMetricNamespaces(id, null).toList().size)
// == 1 and contains only microsoft.storage/storageaccount and missing for example microsoft.storage/storageaccount/blobservices
```

**Expected behavior**
Should return a list of 5 objects containing all possible namespaces for metric of a storage account.

**Screenshots**
In azure web portal we can see the possible namespaces: 
![image](https://github.com/Azure/azure-sdk-for-java/assets/6569628/58bacd10-721b-4431-80a9-bed9b3247adc)

**Setup (please complete the following information):**
 - OS: MacOs 14.0
 - IDE: IntelliJ 2023.2.3
 - Library/Libraries: 
```
    implementation("com.azure.resourcemanager:azure-resourcemanager:2.31.0")
    implementation("com.azure:azure-identity:1.10.3")
    implementation("com.azure:azure-monitor-query:1.3.0-beta.2")
```
 - Java version: 11

**Comment by joshfree** [comment]
@srnagar could you please take a look?

/cc @jairmyree

**Comment by srnagar** [comment]
@shevah this is the expected result for the provided resource URI in the codesnippet provided above. Note that blob services, file services and other namespaces are under a different resource URI. After the storage account name in the resource URI, adding `/blobServices/default` lists the blob namespace and similarly, adding `fileServices/default` lists the file namespace.


See the sample below:

```java
MetricsQueryClient metricsQueryClient = new MetricsQueryClientBuilder()
    .credential(tokenCredential)
    .buildClient();

PagedIterable<MetricNamespace> storageAccountNamespaces = metricsQueryClient
    .listMetricNamespaces("/subscriptions/xxxxxx/resourceGroups/xxxxxx/providers/Microsoft.Storage/storageAccounts/xxxxxx", OffsetDateTime.now());
storageAccountNamespaces.forEach(storageAccountNamespace -> {
    System.out.println("Storage account namespace: " + storageAccountNamespace.getName());
});

PagedIterable<MetricNamespace> blobServiceNamespaces = metricsQueryClient
    .listMetricNamespaces("/subscriptions/xxxxxx/resourceGroups/xxxxxx/providers/Microsoft.Storage/storageAccounts/xxxxxx/blobServices/default", OffsetDateTime.now());
blobServiceNamespaces.forEach(blobServiceNamespace -> {
    System.out.println("Blob service namespace: " + blobServiceNamespace.getName());
});

PagedIterable<MetricNamespace> fileServiceNamespaces = metricsQueryClient
    .listMetricNamespaces("/subscriptions/xxxxxx/resourceGroups/xxxxxx/providers/Microsoft.Storage/storageAccounts/xxxxxx/fileServices/default", OffsetDateTime.now());
fileServiceNamespaces.forEach(fileServiceNamespace -> {
    System.out.println("File service namespace: " + fileServiceNamespace.getName());
});        
```

The output of this code is:

```
Storage account namespace: microsoft.storage-storageaccounts
Blob service namespace: microsoft.storage-storageaccounts-blobservices
File service namespace: microsoft.storage-storageaccounts-fileservices

```

**Comment by srnagar** [comment]
@shevah The web portal makes multiple requests to list all namespaces related to a storage account that includes blob services, file services etc. As shown in my code sample above, by making multiple calls to the `listMetricNamespaces` API with all storage resource URIs, we can get all namespaces.

In the screenshot below, I inspected the browser's network traffic and you can see several calls to `batch?api-version...`. These requests get all the metrics namespaces and definitions. Also, I've highlighted the resourceId, namespace and the name of the metric for Blob services. You can notice that this `resourceId` has `/blobServices/default` as the suffix to the storage account's resourceId.

![image](https://github.com/Azure/azure-sdk-for-java/assets/51379715/72ebea03-b730-4978-9961-c1e8f7df9c23)

**Comment by shevah** [comment]
Thank you for the response. The question is how do know what namespaces to fetch? 
My application lists all resources in a given resource group, and for each resource, it fetches all the available metrics. 
`AzureResourceManager` returns the following resource ids: `/subscriptions/XXXXX/resourceGroups/XXXX/providers/Microsoft.Storage/storageAccounts/storageaccount` from this  I would like to get all available namespaces. Storage account is just one example, I assume other resources have multiple namespaces as well.

So in an ideal situation, I would like to get the full list of available namespaces for a given resource, is there such API? if not, how would I know apriori for what namespaces to look for a given resource ID? Lastly, my goal is to fetch all available metrics from all namespaces for a given resource Id
