### ISSUE TITLE
Harden the HTTPS authority host check to explicitly check for https and disallow everything else

### ISSUE THREAD

**Issue by ahsonkhan** [Azure/azure-sdk-for-java#37236]
The Java check needs to be hardened. Unlike the other language SDKs, which check that the scheme string is exactly HTTPS and fails otherwise, the Java check only confirms that it is "not HTTP" (and assumes anything else is "HTTPS"). That, along with the fact that the setter doesn't do any checking, there could be a way for a malformed authority host url to get through.

Comparing to other languages, this check: https://github.com/Azure/azure-sdk-for-java/blob/0fbfd34590988f9bb78f9898e875366d17b5641d/sdk/core/azure-core/src/main/java/com/azure/core/http/policy/BearerTokenAuthenticationPolicy.java#L93-L95

Should be something like the following (unless we have other non-HTTP supported schemes beyond HTTPS in Java): `if (!context.getHttpRequest().getUrl().getProtocol().equals("https")`

Introduced in this PR (the intent of which I gather is to only allow HTTPS): https://github.com/Azure/azure-sdk-for-java/pull/6543

cc @joshfree, @billwert

**Comment by Vijay-948** [comment]
Issue #37236 - Hardening the HTTPS Authority Host Check

Hello,

I wanted to express my support for the proposed change to harden the HTTPS authority host check in the Java SDK for Azure. It's crucial to ensure secure communication, and explicitly checking for "https" in the URL protocol.

**Comment by alzimmermsft** [comment]
Thanks for filing this @ahsonkhan!

@Vijay-948, if you want to create a PR with that change, we'd be more than happy to review it.

**Comment by Vijay-948** [comment]
Sure I make a PR

**Comment by Vijay-948** [comment]
I'm sorry to hear that you're facing difficulties with creating a pull request (PR) due to file path length issues. It seems like this problem is occurring at the file system level, and it's not something that can be directly resolved through a PR.

**Comment by Vijay-948** [comment]
I'm sorry to hear that I'm facing difficulties with creating a pull request (PR) due to file path length issues. It seems like this problem is occurring at the file system level(file name is too long).
