### ISSUE TITLE
[ANDROID] Android error in Servicebus

### ISSUE THREAD

**Issue by zjack8** [Azure/azure-sdk-for-java#37287]
It's caused by the LockContainer class and appears to be directly used by three ServiceBus classes including ServiceBusReceiverAsyncClient.java and ServiceBusSessionReceiver.java. 

Stack trace:
```
java.lang.NoSuchMethodError: No virtual method keySet()Ljava/util/concurrent/ConcurrentHashMap$KeySetView; in class Ljava/util/concurrent/ConcurrentHashMap; or its super classes (declaration of 'java.util.concurrent.ConcurrentHashMap' appears in /system/framework/core-oj.jar)
at com.azure.messaging.servicebus.implementation.LockContainer.close(LockContainer.java:125)
at com.azure.messaging.servicebus.ServiceBusReceiverAsyncClient.close(ServiceBusReceiverAsyncClient.java:1345)
at com.azure.messaging.servicebus.ServiceBusProcessorClient.close(ServiceBusProcessorClient.java:294)
```

Issue occurs when closing the client in Android API 26.
`receiver.close();`

Further testing indicates that this issue does not occur in Android API 30 and 34.
According to [Android Documentation](https://developer.android.com/reference/java/util/concurrent/ConcurrentHashMap.KeySetView), ConcurrentHashMap.KeySetView was added in API 24, so this error should not be expected.

**Comment by IanZYYap** [comment]
The error occurred while running Service Bus's PeekMessageAsyncSample in Android. The KeySetView method is also used twice in Event Hubs' EventHubBufferedProducerAsyncClient.

**Comment by joshfree** [comment]
@anuchandy can you please follow up
