### ISSUE TITLE
Will we be getting a new version thats compatible with Spring Boot 3.2.0

### ISSUE THREAD

**Issue by dmarsh26** [Azure/azure-sdk-for-java#37284]
We have a version verifier that we now have to turn off with the release of Spring Boot 3.2.0.

-Dspring.cloud.azure.compatibility-verifier.enabled=false

Otherwise our app will not start and we get ERROR:

2023-10-21 11:56:33 ERROR 28 [restartedMain] o.s.b.d.LoggingFailureAnalysisReporter -

Your project setup is incompatible with our requirements due to following reasons:
- Spring Boot [3.2.0-RC1] is not compatible with this Spring Cloud Azure version.

The docs here do not mention Spring Boot 3.2.0 support, but I suspect this will change?
https://github.com/Azure/azure-sdk-for-java/wiki/Spring-Versions-Mapping

thanks
David

**Comment by Netyyyy** [comment]
Hi @dmarsh26 , thanks for reaching out.
We will upgrade when Spring Boot 3.2.0 GA is released.

For now, configuring `-Dspring.cloud.azure.compatibility-verifier.enabled=false` is a workflow if nothing breaks your project.

**Comment by git9999999** [comment]
I think the correct property is
```
spring  
  cloud:
    compatibility-verifier:
      enabled: false 
```

My 50 cents:
@juliojgd from a user perspective, it would be cool when you release 5.7.1 that is compatible. For me, the other solution means i have to update 10 yaml files and make my self a reminder to remove that later again.

**Comment by Netyyyy** [comment]
> I think the correct property is
> 
> ```
> spring  
>   cloud:
>     compatibility-verifier:
>       enabled: false 
> ```
> 
> The other path did not work for me.
> 
> My 50 cents: @juliojgd from a user perspective, it would be cool when you release 5.7.1 that is compatible. For me, the other solution means i have to update 10 yaml files and make my self a reminder to remove that later again.

Use 5.7.0 doesn't need this property

**Comment by Saljack** [comment]
> I think the correct property is
> 
> ```
> spring  
>   cloud:
>     compatibility-verifier:
>       enabled: false 
> ```
> 
> The other path did not work for me.
@git9999999 
This disable verified for the whole Spring Cloud. You need Spring Cloud 2023.0.0 for Spring Boot 3.2 but this version is not release yet (it will be release this or next weak). Meanwhile you can try Spring Cloud 2023.0.0-RC1. It works good (at least in my case). I am definitely not going to wait for Azure to finally add official support for Spring Boot 3.2. The last time it took a quarter of a year.

**Comment by anbusampath** [comment]
Maven: https://repo1.maven.org/maven2/com/azure/spring/spring-cloud-azure-dependencies/5.8.0/

https://github.com/Azure/azure-sdk-for-java/blob/spring-cloud-azure_5.8.0/sdk/spring/CHANGELOG.md#580-2023-12-14

**Comment by Netyyyy** [comment]
Spring Cloud Azure 5.8.0 supports Spring Boot 3.2 now
