### ISSUE TITLE
Cognitive Search API updates based on review

### ISSUE THREAD

**Issue by alzimmermsft** [Azure/azure-sdk-for-java#37317]
- [ ] From the vector algorithm configuration subtypes drop VectorSearch in the name
  - [ ] ExhaustiveKnnVectorSearchAlgorithmConfiguration -> ExhaustiveKnnAlgorithmConfiguration
  - [ ] HnswVectorSearchAlgorithmConfiguration -> HnswAlgorithmConfiguration
- [ ] In PiiDetectionSkill rename the maskingCharacter property to mask
- [ ] In PiiDetectionSkill investigate creating an exstensible enum for categories, also looks like the name is PiiCategories think about just using categories
- [ ] SearchField.vectorSearchProfile -> SearchField.vectorSearchProfileName, need to do the same for the field builder attribute/annotation
- [ ] Make fieldName required in SemanticField (will follow-up with service if this should be required as well)
- [ ] SemanticSettings -> SemanticSearch (match VectorSearch)
- [ ] VectorSearchProfile.algorithm -> VectorSearchProfile.algorithmConfigurationName
- [ ] AnswerResult and CaptionResult have setters exposed for additional properties
- [ ] Combine vector search options into VectorSearchOptions, semantic search options into SemanticSearchOptions
Create type QueryAnswer with AnswerType (QueryAnswerType), count, and threshold, create type QueryCaption with CaptionType (QueryCaptionType) and highlightEnabled
- [ ] Make RawVectorQuery.vector required
- [ ] Rename VectorQuery to VectorizableQuery and RawVectorQuery to VectorQuery
- [ ] Rename SemanticPartialReasponseReason to SemanticErrorReason, SemanticErrorHandling to SemanticErrorMode, and SemanticPartialReasponseType to SemanticSearchResultsType
- [ ] Hide VectorSearchAlgorithmKind anf VectorQueryKind from the public API

**Comment by pallavit** [comment]
@alzimmermsft is this still valid?

**Comment by alzimmermsft** [comment]
Closing as this work was done
