### ISSUE TITLE
[BUG] Blob Storage Authentication *Fails Silently*

### ISSUE THREAD

**Issue by irevans** [Azure/azure-sdk-for-java#37335]
**Describe the bug**
I am using the azure-storage-blob sdk to upload files to blob storage. I am using the BlockBlobClient.getBlobOutputStream method to retrieve an output stream. I then write bytes to this stream and then close the stream. 

When closing the stream I have observed authentication failures in the logs (in my case a 403 because my sas token had expired), however these authentication issues do not cause any exceptions. From my perspective everything seems to have worked fine. This is really bad as I'm oblivious to the underlying issue. As I'm sure you can appreciate this makes the SDK unusable as I cannot release code to production if it can fail silently.

***Exception or Stack Trace***
There is no exception (thats the problem). However I can see clearly that there was an authentication issue when closing the stream:

2023-10-24T09:27:11.957+01:00 DEBUG 16060 --- [ctor-http-nio-1] r.n.http.client.HttpClientOperations     : [f9103e78-1, L:/10.41.16.109:51752 - R:saaddocumentmanagement.blob.core.windows.net/20.60.166.129:443] Received response (auto-read:false) : RESPONSE(decodeResult: success, version: HTTP/1.1)
HTTP/1.1 403 Server failed to authenticate the request. Make sure the value of Authorization header is formed correctly including the signature.
Content-Length: <filtered>
Content-Type: <filtered>
Server: <filtered>
x-ms-request-id: <filtered>
x-ms-error-code: <filtered>
Date: <filtered>
X-SYMC-Transaction-UUID: <filtered>
Connection: <filtered>

**To Reproduce**
See the following code snippet, it will not fail even if you provide an expired sas token.

***Code Snippet***
final BlockBlobClient blockBlobClient = getBlockBlobClient(container, blobName);
    
try (BlobOutputStream outputStream = blockBlobClient.getBlobOutputStream(options)) {
  // stream the data from input to output streams.
  copy(inputStream, outputStream, blobStorageProperties.getDocumentReadBufferSizeInBytes());
}

@Bean
public BlobServiceClientBuilder blobServiceClientBuilder(
    BlobStorageProperties properties, ActiveDirectoryProperties activeDirectoryProperties) {
  return new BlobServiceClientBuilder()
      .endpoint(properties.getEndpoint())
      .sasToken(sas);
}

@Bean
public BlobServiceClient blobServiceClient(BlobServiceClientBuilder blobServiceClientBuilder) {
  return blobServiceClientBuilder.buildClient();
}

**Expected behavior**
There must be an exception. The SDK currently gives the impression that everything worked fine.

**Screenshots**

**Setup (please complete the following information):**
 - OS: Windows 10 Enterprise
 - IDE: IntelliJ
 - Library/Libraries:  azure-storage-blob, azure-sdk-bom 1.2.17
 - Java version: 17
 - App Server/Environment:
 - Frameworks: Spring Boot

**Comment by joshfree** [comment]
@ibrahimrabab could you please follow up

**Comment by ibrahimrabab** [comment]
Hi @irevans 

Thanks for reaching out! So for this case, even though no error is thrown when writing to the stream, the data only gets uploaded to the blob when calling `outputStream.close()`. And since the authentication error is thrown when calling `.close()`, the blob will never get uploaded. This behavior is by design and not a silent failure, so even if you try writing to the stream with an invalid sas token, the data will not get uploaded since the authentication error will be thrown. 

Let me know if this helps or if you have any further questions!

**Comment by irevans** [comment]
I agree that the blob content does not get uploaded. But the issue is that as as client of the sdk you are unaware that the blob was not uploaded, you are unaware there was an authentication issue. 

The sdk behaves identically in a success and error scenario, that clearly cannot be considered good design.

It is critical that as a client of the sdk that you know if items have been uploaded to blob storage or not, otherwise its really not fit for purpose. In what situation do you think a client doesn't care if the upload was successful or not?

**Comment by ibrahimrabab** [comment]
@irevans 

Apologies, I may not be understanding your issue. Is the problem that the exception does not get thrown at all when you write to the stream and call `.close()`? Because when I test this on my end with an expired sas token, as soon as I call `.close()`, I get an authentication exception thrown.

**Comment by irevans** [comment]
That's correct, when I call .close no exception is thrown to my app. I can see an exception in the logs but .close returns with no exception.

**Comment by ibrahimrabab** [comment]
@irevans 
Is there anywhere in your application that is catching this exception? Can you try reproducing this issue without using Spring? It could be that Spring might be affecting the exception from being thrown. Errors should be thrown immediately; I've reproduced this multiple times and there is no silent failure happening.

**Comment by irevans** [comment]
You are right, when I extract the code to a stand alone application I see the close operation throwing an exception. I must have done something dull in my spring setup.

I think you can close this issue. Thanks for spending the time to investigate this fully. It's appreciated.
