### ISSUE TITLE
[QUERY] This request is not authorized to perform this operation.

### ISSUE THREAD

**Issue by wanhuhou** [Azure/azure-sdk-for-java#37372]
**Query/Question**
A clear and concise ask/query.
aways This request is not authorized to perform this operation.

  ClientSecretCredential credential = new ClientSecretCredentialBuilder()
                .clientId(clientID)
                .clientSecret(clientSecret)
                .tenantId(tenantID)
                .build();
        BlobServiceClient blobServiceClient = new BlobServiceClientBuilder()
                .endpoint(containerEndpoint)
                .credential(credential)
                .buildClient();
        BlobContainerClient blobContainerClient = blobServiceClient.createBlobContainer("hehe");
        blobContainerClient.createIfNotExists();

***Why is this not a Bug or a feature Request?***
A clear explanation of why is this not a bug or a feature request?

Exception in thread "main" com.azure.storage.blob.models.BlobStorageException: If you are using a StorageSharedKeyCredential, and the server returned an error message that says 'Signature did not match', you can compare the string to sign with the one generated by the SDK. To log the string to sign, pass in the context key value pair 'Azure-Storage-Log-String-To-Sign': true to the appropriate method call.
If you are using a SAS token, and the server returned an error message that says 'Signature did not match', you can compare the string to sign with the one generated by the SDK. To log the string to sign, pass in the context key value pair 'Azure-Storage-Log-String-To-Sign': true to the appropriate generateSas method call.
Please remember to disable 'Azure-Storage-Log-String-To-Sign' before going to production as this string can potentially contain PII.
Status code 403, "﻿<?xml version="1.0" encoding="utf-8"?><Error><Code>AuthorizationFailure</Code><Message>This request is not authorized to perform this operation.

**Setup (please complete the following information if applicable):**
 - IDE: [e.g. IntelliJ]
 - Library/Libraries: [e.g. com.azure:azure-core:1.16.0 (groupId:artifactId:version)]
 
 **Information Checklist**
 Kindly make sure that you have added all the following information above and checkoff the required fields otherwise we will treat the issuer as an incomplete report
- [ ] Query Added
- [ ] Setup information Added

**Comment by joshfree** [comment]
@ibrahimrabab could you follow up

**Comment by qiaoshiling** [comment]
We're a team, and this is our latest code, but we're having the same problem。
Status code 403 ，“AuthorizationFailure”

Whether the IP address is whitelisted or the time zone is faulty？


EnvironmentConfiguration globalConfiguration = EnvironmentConfiguration.getGlobalConfiguration();

        globalConfiguration.put(Configuration.PROPERTY_AZURE_CLIENT_ID, clientID);
        globalConfiguration.put(Configuration.PROPERTY_AZURE_CLIENT_SECRET, clientSecret);
        globalConfiguration.put(Configuration.PROPERTY_AZURE_TENANT_ID, tenantID);

        globalConfiguration.put(Configuration.PROPERTY_AZURE_LOG_LEVEL, "debug");
        globalConfiguration.put(Configuration.PROPERTY_AZURE_HTTP_LOG_DETAIL_LEVEL, "debug");



        /*
         * Create a storage client using the Azure Identity credentials.
         */
        BlobServiceClient storageClient = new BlobServiceClientBuilder()
                .endpoint(containerEndpoint)
                .credential(new DefaultAzureCredentialBuilder().build())
                .buildClient();


        BlobContainerClient blobContainerClient = storageClient.getBlobContainerClient("output");
        PagedIterable<BlobItem> blobItems = blobContainerClient.listBlobs();
        for (BlobItem blobItem : blobItems) {
            System.out.println("================="+blobItem.getName());
        }

**Comment by ibrahimrabab** [comment]
Hi @qiaoshiling 
Can you confirm whether you have appropriate access rights for the Storage account you are using? I was able to authenticate just fine using the SecretClientBuilder, so it may be that you might be missing some access rights such as Container Creation.

Please refer to this documentation:
https://learn.microsoft.com/en-us/azure/storage/blobs/assign-azure-role-data-access?tabs=portal

Let us know if this helps!
