### ISSUE TITLE
[BUG] Unnecessary humongous object allocation in batch collectors

### ISSUE THREAD

**Issue by andris-rauda** [Azure/azure-sdk-for-java#37412]
**Describe the bug**
There are several similar classes in azure-sdk-for-java:
 * EventDataBatch in eventhubs/azure-messaging-eventhubs
 * EventDataBatchImpl in eventhubs/microsoft-azure-eventhubs
 * ServiceBusMessageBatch in servicebus/azure-messaging-servicebus
They all are allocating byte arrays in their constructors:
 `this.eventBytes = new byte[maxMessageSize];`
In our case maxMessageSize happens to be 1MB. When running JVM with G1GC and 1GB heap G1HeapRegionSize is by default also 1MB making these arrays [humongous objects](https://docs.oracle.com/javase/9/gctuning/garbage-first-garbage-collector.htm#JSGCT-GUID-D74F3CC7-CC9F-45B5-B03D-510AEEAC2DAC) and potentially affecting performance by requiring additional work on GC part.

After inspecting the code it is appears, that these byte arrays are only used to calculate size of eventData and are completely unnecessary.

***Exception or Stack Trace***
No stack trace

**To Reproduce**
Add following test to EventDataBatchTest and run "Profile 'EventDataBatchTest' with 'IntelliJ Profiler'"
```
    /**
     * Proves, that with maxSize of 1MB (which seems to be 
     * <a href="https://learn.microsoft.com/en-us/azure/event-hubs/event-hubs-quotas"></a>default for standard / premium tiers</a>)
     * 1000 invocations allocate over 1GB of memory (for example, when invoked with IntelliJProfiler). 
     */
    @RepeatedTest(1000)
    public void withBigMaxMessageLength() {
        final int maxSize = ClientConstants.MAX_MESSAGE_LENGTH_BYTES * 4;
        final EventDataBatch batch = new EventDataBatch(maxSize, null, PARTITION_KEY,
            null, DEFAULT_INSTRUMENTATION);
        final EventData within = new EventData(new byte[1024]);

        Assertions.assertEquals(maxSize, batch.getMaxSizeInBytes());
        Assertions.assertTrue(maxSize > batch.getSizeInBytes());
        Assertions.assertTrue(batch.tryAdd(within));
        Assertions.assertEquals(1, batch.getCount());
    }
```
Then inspect results - show Memory Allocations

***Code Snippet***
constructor:
 `this.eventBytes = new byte[maxMessageSize];`

getSize():
  `int eventSize = amqpMessage.encode(this.eventBytes, 0, maxMessageSize);`

**Expected behavior**
No large array allocation in these classes, which could be achieved by using DroppingWritableBuffer instead:
` int eventSize = amqpMessage.encode(new DroppingWritableBuffer());`

It doesn't throw BufferOverflowException, so try ... catch block in tryAdd method would also need to be replaced with simple if statement.

**Screenshots**
Profiling unittest using IntelliJ Profiler:
![image](https://github.com/Azure/azure-sdk-for-java/assets/5433945/b9e3c139-c62a-4aca-b9b0-8047f0bb2141)

Profiling humongous_obj_allocation using async-profiler:
![humongous](https://github.com/Azure/azure-sdk-for-java/assets/5433945/1c489a69-1883-47fb-a5e0-7ae72a49dca8)

**Setup (please complete the following information):**
 - OS: Windows/Linux
 - IDE: IntelliJ IDEA 2022.2.1 (Ultimate Edition)
 - Library/Libraries: com.azure:azure-messaging-eventhubs:5.15.5, com.azure:azure-messaging-servicebus:7.13.4
 - Java version: 11
 - App Server/Environment: AKS
 - Frameworks: Spring Boot

**Additional context**

**Information Checklist**
Kindly make sure that you have added all the following information above and checkoff the required fields otherwise we will treat the issuer as an incomplete report
- [X] Bug Description Added
- [X] Repro Steps Added
- [X]  Setup information Added

**Comment by alzimmermsft** [comment]
Thank you for filing this @andris-rauda and the PR you've submitted!

@conniey and @anuchandy can you review this.
