### ISSUE TITLE
[QUERY] stateless pagination with java sdk 

### ISSUE THREAD

**Issue by sauravBhasin** [Azure/azure-sdk-for-java#37418]
**Query/Question**
How to properly implement rest based pagination with limited results per request.

***Why is this not a Bug or a feature Request?***
I am able to get the pagination to work with continuation token but i want to implement a rest based approach to provide users to fetch the data. I limit the number of results per http call to 500 and stream over 4 lakh records. 
The problem with continuation token is after returning 500 results(the original query will return all 4 lakhs returns as it is a select * query) split over pages of size 500(controller by maxPageSize property in cosmos request options). If i close the iterator and restart the query using the continuation token by sending another call to the cosmosContainer.queryItems() method along with the continuationToken.This leads to astronomical RU's consumption compared to if i dont close the iterator and fetch all the items but doing this leads to having to send over 4 lakh records in a single http response.

Query is **Select * from <Container>**
The container has data in only two logical/physical partitions

**Setup (please complete the following information if applicable):**
 - IDE: [e.g. IntelliJ]
 - Library/Libraries: [e.g. com.azure:azure-core:1.16.0 (groupId:artifactId:version)]
com.azure:azure-spring-data-cosmos:3.7.0
 
 **Information Checklist**
 Kindly make sure that you have added all the following information above and checkoff the required fields otherwise we will treat the issuer as an incomplete report
- [ ] Query Added
- [ ] Setup information Added

**Comment by kushagraThapar** [comment]
@trande4884 can you please take a look at this, thanks!

**Comment by trande4884** [comment]
@sauravBhasin can you please share how you are achieving pagination? With CosmosTemplate, query annotations, ect.? Thanks!

**Comment by kushagraThapar** [comment]
@sauravBhasin can you please answer the above question, thanks!
