### ISSUE TITLE
[BUG] Index metrics does not work starting from Cosmos DB JAVA SDK version 4.49.0

### ISSUE THREAD

**Issue by yanfang-ma** [Azure/azure-sdk-for-java#37426]
**Describe the bug**
We tested below sample code (https://learn.microsoft.com/en-us/azure/cosmos-db/nosql/index-metrics?tabs=java-sync) but we are not able to get the diagnostics starting from version 4.49.0.
![image](https://github.com/Azure/azure-sdk-for-java/assets/87124151/21cad11f-784d-4912-b1bc-02041fe5589f)

***Exception or Stack Trace***
Java SDK 4.49.0  got below exception
diagnostics: {"error":"com.fasterxml.jackson.databind.exc.InvalidDefinitionException:
 No serializer found for class com.azure.cosmos.implementation.**IndexUtilizationInfo** and no properties discovered to create BeanSerializer 
 (to avoid exception, disable SerializationFeature.FAIL_ON_EMPTY_BEANS) 
(through reference chain: com.azure.cosmos.implementation.FeedResponseDiagnostics[\"queryMetricsMap\"]
->java.util.concurrent.ConcurrentHashMap[\"{\"min\":\"\",\"max\":\"FF\"},pkrId:0\"]
->com.azure.cosmos.implementation.**QueryMetrics[\"indexUtilizationInfo\"]**)"}

 JAVA SDK 4.51.0+ got below exception:
diagnostics:{"error":"com.fasterxml.jackson.databind.exc.InvalidDefinitionException: 
No serializer found for class com.azure.cosmos.implementation.**SingleIndexUtilizationEntity** and no properties discovered to create BeanSerializer 
(to avoid exception, disable SerializationFeature.FAIL_ON_EMPTY_BEANS)
 (through reference chain: com.azure.cosmos.implementation.FeedResponseDiagnostics[\"queryMetricsMap\"]
 ->java.util.concurrent.ConcurrentHashMap[\"{\"min\":\"\",\"max\":\"1FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF\"},pkrId:0\"]
 ->com.azure.cosmos.implementation.**QueryMetrics[\"indexUtilizationInfo\"]**
 ->com.azure.cosmos.implementation.**IndexUtilizationInfo[\"UtilizedSingleIndexes\"]**->java.util.ArrayList[0])"}

**To Reproduce**
Run above sample code

***Code Snippet***
see above

**Expected behavior**

Should be able to see the diagnostics with index metrics.

**Screenshots**

**Setup (please complete the following information):**
 - OS: Windows
 - IDE: Eclipse
 - Library/Libraries: azure-cosmos
 - Java version: 14
 - App Server/Environment: N/A

If you suspect a dependency version mismatch (e.g. you see `NoClassDefFoundError`, `NoSuchMethodError` or similar), please check out [Troubleshoot dependency version conflict article](https://aka.ms/azsdk/java/dependency/troubleshoot) first. If it doesn't provide solution for the problem, please provide:
- verbose dependency tree (`mvn dependency:tree -Dverbose`)
- exception message, full stack trace, and any available logs

**Additional context**

**Information Checklist**
Kindly make sure that you have added all the following information above and checkoff the required fields otherwise we will treat the issuer as an incomplete report
- [x] Bug Description Added
- [x] Repro Steps Added
- [x] Setup information Added

**Comment by yanfang-ma** [comment]
@kushagraThapar

**Comment by kushagraThapar** [comment]
Thanks @yanfang-ma for creating this issue, I can repro it, will provide a fix in the upcoming November release.
