### ISSUE TITLE
Key Vault - Certificates Samples Issue

### ISSUE THREAD

**Issue by faynef** [Azure/azure-sdk-for-java#37423]
1.

**Section** [link1](https://github.com/Azure/azure-sdk-for-java/blob/500f2684bd3b6d93fdf3c0cc5b62858123261071/sdk/keyvault/azure-security-keyvault-certificates/src/samples/java/com/azure/security/keyvault/certificates/CertificateClientJavaDocCodeSnippets.java#L315), [link2](https://github.com/Azure/azure-sdk-for-java/blob/main/sdk/keyvault/azure-security-keyvault-certificates/src/samples/java/com/azure/security/keyvault/certificates/CertificateClientJavaDocCodeSnippets.java#L322): 
![image](https://github.com/Azure/azure-sdk-for-java/assets/138087452/58273b0a-f61f-4f4d-a209-ebe21edabe3e)

**Reason**: 
Parameter description error.

**Suggestion**: 
Update `certificateName` to `issuerName`.

@backwind1233 , @sandeep-sen , @joshfree , @mario-guerra and @heaths to notification.

**Comment by eNeRGy164** [comment]
I was in the process of fixing this when I discovered it had already been assigned to @vcolin7.
I hope this doesn't cause any inconvenience.
