### ISSUE TITLE
[QUERY] How to get metadata on VM.

### ISSUE THREAD

**Issue by superDoss** [Azure/azure-sdk-for-java#3742]
Hi all

I'm starting to work with Azure java api and trying to build monitoring dashboard for our company. For that i should try to find the metadata over VM's that are inside a VMScaleSet.

The metadata i should find is:
 1. Start date of the VM
 2. PowerState of the VM.
 3. PrimaryPrivateIp
 4. Name

And i should be able to filter based on tags in the scale set.

Is there any api that can give me all of that in a formal way? cause now I can't find any good solution for the problem.

**Comment by kurtzeborn** [comment]
Thank you for opening this issue! We are routing it to the appropriate team for follow up.

**Comment by yaohaizh** [comment]
@superDoss you can take a look at this file https://github.com/Azure/azure-libraries-for-java/blob/master/azure-mgmt-compute/src/test/java/com/microsoft/azure/management/compute/VirtualMachineScaleSetOperationsTests.java to see whether it fits your requirement.

**Comment by ChenTanyi** [comment]
@superDoss It is a long time after your query. Hopefully you have already solved your problem. 

Here is an example to get data 2, 3, 4. I can't find a way to get 1 from portal and rest API, if you find way to get it from other tools please tell me.

```java
             final File credFile = new File(System.getenv("AZURE_AUTH_LOCATION"));
             ApplicationTokenCredentials credentials = ApplicationTokenCredentials.fromFile(credFile);
            Azure azure = Azure.authenticate(credentials).withDefaultSubscription();

            VirtualMachineScaleSet vmss = azure.virtualMachineScaleSets().getByResourceGroup(rgName, vmssName);
            List<SubnetInner> subnets = new ArrayList<>();

            vmss.networkProfile().networkInterfaceConfigurations().forEach(
                networkConfiguration -> networkConfiguration.ipConfigurations().forEach(ipConfiguration -> {
                    try {
                        ResourceId subnetId = ResourceId.fromString(ipConfiguration.subnet().id());
                        SubnetInner subnet = azure.networks().manager().inner().subnets()
                                .get(subnetId.resourceGroupName(), subnetId.parent().name(), subnetId.name(), "ipConfigurations");
                        subnets.add(subnet);
                    } catch (Exception e) {
                        e.printStackTrace();
                    }
            })); // you could also use azure.networks() instead of subnet if you like

            vmss.virtualMachines().list().forEach(vm -> {
                System.out.printf("- %s\n", vm.name());
                System.out.printf("  %s\n", vm.powerState());
                subnets.forEach(subnet -> subnet.ipConfigurations().forEach(ipConfiguration ->
                    vm.inner().networkProfile().networkInterfaces().forEach(networkInterface -> {
                        if (ipConfiguration.id().contains(networkInterface.id())) {
                            System.out.printf("  %s\n", ipConfiguration.privateIPAddress());
                        }
                    })));
            });
```
If you don't know how to do auth, you could see [AUTH.md](https://github.com/Azure/azure-libraries-for-java/blob/master/AUTH.md)

If you still have problem, feel free to reopen it. Thanks!
