### ISSUE TITLE
[QUERY] General API design for multipart/form-data with file upload

### ISSUE THREAD

**Issue by weidongxu-microsoft** [Azure/azure-sdk-for-java#37488]
PR https://github.com/Azure/autorest.java/pull/2421

**Query/Question**

Context, codegen is designing generating code for REST API with "multipart/form-data".

Here we consider case of "multipart/form-data" with file upload.

In current OpenAI SDK, we had `filename` at [API parameter](https://github.com/Azure/azure-sdk-for-java/blob/1f21d93cbd0f70810b247acdb17ef9d509d05540/sdk/openai/azure-ai-openai/src/main/java/com/azure/ai/openai/OpenAIClient.java#L971-L975).

And model would have [`byte[] file;`](https://github.com/Azure/azure-sdk-for-java/blob/1f21d93cbd0f70810b247acdb17ef9d509d05540/sdk/openai/azure-ai-openai/src/main/java/com/azure/ai/openai/models/AudioTranscriptionOptions.java#L16-L22).

Wondering whether it be better to have
```java
java.nio.file.Path file;
```
in AudioTranscriptionOptions.java. Then, it would contain both filename and file content.

Also `byte[]` may not work well, if the file is huge (GB or above).

***Why is this not a Bug or a feature Request?***
Design discussion. Also OpenAI is beta.

**Setup (please complete the following information if applicable):**
 - IDE: [e.g. IntelliJ]
 - Library/Libraries: [e.g. com.azure:azure-core:1.16.0 (groupId:artifactId:version)]
 
 **Information Checklist**
 Kindly make sure that you have added all the following information above and checkoff the required fields otherwise we will treat the issuer as an incomplete report
- [x] Query Added
- [ ] Setup information Added

**Comment by jpalvarezl** [comment]
To provide more context for the discussion:

 - `filename` is used as a requirement of the [multipart/form spec](https://www.rfc-editor.org/rfc/rfc7578#section-4)we don't think there is a server side validation of whether the value is correct, but the value needs to be present. 
 - Regarding the type of `file` within the model, we believe that `byte[]` is the best representation, because we also need to maintain compatibility with the non-Azure OpenAI API surface ([ref](https://platform.openai.com/docs/api-reference/audio/createTranscription)). 
 - For the sake of future proofing, `byte[]` represents a type that would be the most versatile to handle file types of any kind and maybe any situation (for instance, eventual need for real time audio transcription. Admittedly, there are other API challenges for such a scenario)
 
My opinions: I do agree, we should provide a convenience method for users to handle files. Where we can accept the `Path` as either a `java.nio.file.Path` or `String` and handle to opening logic for them. But I think that this should come in the form of custom code added at the SDK level and not as something coming from a lower layers in the code generation process or as part of the request class model.

**Comment by mssfang** [comment]
We can use `BinaryData` to represent the file content instead of `byte[]`,  so the customer can do `BinaryData.fromBytes(byte[] data)`. We can remove the convenience API since the `fileName` can be retrieved from the `Path` class by `path.getFileName();`. So BinaryData covers `byte[]`, `File`, `Path` cases.

**Comment by weidongxu-microsoft** [comment]
If we know it is a file, `BinaryData` would likely better than `byte[]` (for an upload via `application/octet-stream` content-type, the API takes `BinaryData`).

`byte[]` does not support streaming. So, if we really have a 20GB file to upload, `byte[]` likely won't work. (however, our current multipart implementation is also not that advanced to support streaming -- impl can be delayed, but we probably should choose a type that is future-proof)

But, yes, the filename can be left for API customization. For the code generated by codegen, it may just put `file.data` if not provided otherwise.

**Comment by weidongxu-microsoft** [comment]
RFC about `filename` when `application/octet-stream` (though keep an eye on whether any are obsoleted)

https://datatracker.ietf.org/doc/html/rfc7578#section-4.2

https://datatracker.ietf.org/doc/html/rfc2183#section-2.3

If using `BinaryData` in payload class, we may either add another filename property (optional) in class, or put filename in method parameter (optional as well?).

**Comment by weidongxu-microsoft** [comment]
Another question is streaming for `BinaryData`.

E.g. the request may contain 2 files, with a few other fields. For the `BinaryData` to REST call, codegen need to "concat" these files without actually read them out.

**Comment by weidongxu-microsoft** [comment]
Discussed with Srikanta, current plan is to have `BinaryData file` in model class, and an optional `String fileName` in the model class as well.

**Comment by weidongxu-microsoft** [comment]
current `MultipartFormDataHelper` via InputStream

<details>
  <summary>code</summary>
```java
// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.

package com.payload.multipart.implementation;

import com.azure.core.http.HttpHeaderName;
import com.azure.core.http.rest.RequestOptions;
import com.azure.core.util.BinaryData;

import java.io.ByteArrayInputStream;
import java.io.InputStream;
import java.io.SequenceInputStream;
import java.nio.charset.Charset;
import java.nio.charset.StandardCharsets;
import java.util.UUID;

// DO NOT modify this helper class

public final class MultipartFormDataHelper {
    /**
     * Line separator for the multipart HTTP request.
     */
    private static final String CRLF = "\r\n";

    /**
     * Value to be used as part of the divider for the multipart requests.
     */
    private final String boundary;

    /**
     * The actual part separator in the request. This is obtained by prepending "--" to the "boundary".
     */
    private final String partSeparator;

    /**
     * The marker for the ending of a multipart request. This is obtained by post-pending "--" to the "partSeparator".
     */
    private final String endMarker;

    /**
     * Charset used for encoding the multipart HTTP request.
     */
    private final Charset encoderCharset = StandardCharsets.UTF_8;

    private InputStream requestDataStream = new ByteArrayInputStream(new byte[0]);
    private long requestLength = 0;

    private BinaryData requestBody;

    /**
     * Default constructor used in the code. The boundary is a random value.
     */
    public MultipartFormDataHelper() {
        this(UUID.randomUUID().toString().substring(0, 16));
    }

    private MultipartFormDataHelper(String boundary) {
        this.boundary = boundary;
        partSeparator = "--" + boundary;
        endMarker = partSeparator + "--";
    }

    /**
     * Get the request options for multipart form data.
     *
     * @param requestOptions The request options.
     * @return The request options.
     */
    public RequestOptions getRequestOptions(RequestOptions requestOptions) {
        if (requestOptions == null) {
            requestOptions = new RequestOptions();
        }
        requestOptions
                .setHeader(HttpHeaderName.CONTENT_TYPE, "multipart/form-data; boundary=" + this.boundary)
                .setHeader(HttpHeaderName.CONTENT_LENGTH, String.valueOf(requestLength));
        return requestOptions;
    }

    public BinaryData getRequestBody() {
        if (requestBody == null) {
            requestBody = BinaryData.fromStream(requestDataStream, requestLength);
        }
        return requestBody;
    }

    // text/plain
    /**
     * This method formats a text/plain field for a multipart HTTP request and returns its byte[] representation.
     *
     * @param fieldName the field name
     * @param value the value of the text/plain field
     */
    public void serializeField(String fieldName, String value) {
        String serialized = partSeparator
                + CRLF + "Content-Disposition: form-data; name=\""
                + fieldName + "\"" + CRLF + CRLF
                + value
                + CRLF;
        byte[] data = serialized.getBytes(encoderCharset);
        requestLength += data.length;
        requestDataStream = new SequenceInputStream(requestDataStream, new ByteArrayInputStream(data));
    }

    // application/octet-stream
    public void serializeField(String fieldName, BinaryData file, String filename) {
        // Multipart preamble
        String fileFieldPreamble = partSeparator
                + CRLF + "Content-Disposition: form-data; name=\"" + fieldName
                + "\"; filename=\"" + filename + "\""
                + CRLF + "Content-Type: application/octet-stream" + CRLF + CRLF;
        byte[] data = fileFieldPreamble.getBytes(encoderCharset);
        requestLength += data.length;
        requestDataStream = new SequenceInputStream(requestDataStream, new ByteArrayInputStream(data));

        // Writing the file into the request as a byte stream
        requestLength += file.getLength();
        requestDataStream = new SequenceInputStream(requestDataStream, file.toStream());

        // CRLF
        data = CRLF.getBytes(encoderCharset);
        requestLength += data.length;
        requestDataStream = new SequenceInputStream(requestDataStream, new ByteArrayInputStream(data));
    }

    public void end() {
        byte[] data = endMarker.getBytes(encoderCharset);
        requestLength += data.length;
        requestDataStream = new SequenceInputStream(requestDataStream, new ByteArrayInputStream(data));
    }

    // TODO application/json
}
```
</details>

**Comment by weidongxu-microsoft** [comment]
Updated design at https://github.com/Azure/azure-sdk-for-java/issues/38408
