### ISSUE TITLE
[QUERY] How to get shared images across tenants in Java using SDK?

### ISSUE THREAD

**Issue by xieyz1980** [Azure/azure-sdk-for-java#37509]
**Query/Question**
Need to use images between tenants using shared image galleries, as described in [here](https://docs.microsoft.com/en-us/azure/virtual-machines/linux/share-images-across-tenants) using the java SDK. But I can't get the shared image galleries using provided methods like "azure.galleryImages().listByGallery(String s,String s1)". The method can just list the own image galleries not shared image galleries.
I want to know if or not the SDK currently supports getting shared galleries images across tenants? If not,  how can I do that? Is there any REST API that can do this? Thanks.

***Why is this not a Bug or a feature Request?***
CLI can do this.

**Setup (please complete the following information if applicable):**
 - OS: macos
 - IDE: e.g. IntelliJ
 - Library/Libraries: <com.microsoft.azure.version>1.41.3</com.microsoft.azure.version>

**Comment by xieyz1980** [comment]
I also tried the API [Shared Gallery Images - Get ](https://learn.microsoft.com/en-us/rest/api/compute/shared-gallery-images/get?view=rest-compute-2022-03-03&tabs=Java), it can't get shared gallery image by the other subscription.

**Comment by joshfree** [comment]
@weidongxu-microsoft could you please follow up here?

**Comment by weidongxu-microsoft** [comment]
@xieyz1980 

I think you have to use another client instance to list/query resources in a different subscription.

When creating the instance, you can set `AzureProfile` with a different tenantId/subscriptionId.
https://github.com/Azure/azure-sdk-for-java/blob/main/sdk/core/azure-core-management/src/main/java/com/azure/core/management/profile/AzureProfile.java

Note: for http connection pool, you may want to shared the underlying `HttpClient`, to have all instances shared a single connection pool.
https://github.com/Azure/azure-sdk-for-java/blob/main/sdk/resourcemanager/azure-resourcemanager/src/samples/java/com/azure/resourcemanager/ThreadPoolGuideSamples.java#L65
