### ISSUE TITLE
JavaDoc review and improvements for azure core public API

### ISSUE THREAD

**Issue by JonathanGiles** [Azure/azure-sdk-for-java#3752]
We need to review all public API in Azure core to ensure it is high-quality, fully implemented, clearly-explained, and meeting our high expectations for JavaDoc in Azure Java SDK.

**Comment by joshfree** [comment]
@anuchandy could you help load balance this one?

**Comment by anuchandy** [comment]
@josefree I will also take a look from my side.

**Comment by joshfree** [comment]
Closing issue given #5653 #5735 shipped in the November update
