### ISSUE TITLE
[QUERY] what happens when SyncPoller.waitUntil times out?

### ISSUE THREAD

**Issue by lmsurpre** [Azure/azure-sdk-for-java#37529]
**Query/Question**
What happens when SyncPoller.waitUntil times out?

There are two variants of this method documented:
1. [with Duration](https://azuresdkdocs.blob.core.windows.net/$web/java/azure-core/latest/com/azure/core/util/polling/SyncPoller.html#waitUntil(java.time.Duration,com.azure.core.util.polling.LongRunningOperationStatus))
2. [without Duration](https://azuresdkdocs.blob.core.windows.net/$web/java/azure-core/latest/com/azure/core/util/polling/SyncPoller.html#waitUntil(com.azure.core.util.polling.LongRunningOperationStatus))

Interestingly, way back in azure-core 1.2.0 it was documented to throw TimeoutException, but that was removed from the javadoc in 1.3.0.

Does the flavor with a Duration still throw that?
Does the flavor without a Duration **never** time out?

***Why is this not a Bug or a feature Request?***
It may be a feature request (or at least a doc update) depending on the answer...

**Setup (please complete the following information if applicable):**
 - IDE: [e.g. IntelliJ]
 - Library/Libraries: com.azure:azure-core (since 1.3.0)
 
 **Information Checklist**
 Kindly make sure that you have added all the following information above and checkoff the required fields otherwise we will treat the issuer as an incomplete report
- [x] Query Added
- [x] Setup information Added

**Comment by joshfree** [comment]
@alzimmermsft
