### ISSUE TITLE
[OpenAI] Support for vector search for Azure Cognitive Search

### ISSUE THREAD

**Issue by mkemmerz** [Azure/azure-sdk-for-java#37537]
**Describe the solution you'd like**
The Java SDK for OpenAI should offer a configuration setting to enable vector search on top of the currently supported keyword search.

Probably the [AzureCognitiveSearchChatExtensionConfiguration](https://github.com/Azure/azure-sdk-for-java/blob/main/sdk/openai/azure-ai-openai/src/main/java/com/azure/ai/openai/models/AzureCognitiveSearchChatExtensionConfiguration.java) should support this.

The vector / hybrid search has examples here: https://github.com/Azure/azure-sdk-for-java/blob/main/sdk/search/azure-search-documents/src/samples/java/com/azure/search/documents/VectorSearchExample.java

Those are quite complex to use though. An easy integration into the OpenAI would be really great.

**Describe alternatives you've considered**
Calling the OpenAI API directly, without the usage of the SDK.

**Additional context**
The search type ("Suchtyp") can be configured on Azure's Cognitive Search field as "Hybrid (Vector + Keyword)":

<img width="813" alt="image" src="https://github.com/Azure/azure-sdk-for-java/assets/46575727/308fc436-646a-475c-a02d-9ad9ee56dc54">

**Comment by joshfree** [comment]
@mssfang PTAL

**Comment by mssfang** [comment]
@mkemmerz You can find a sample in our repo that shows how to use Azure Search extension in the OpenAI SDK.

https://github.com/Azure/azure-sdk-for-java/blob/main/sdk/openai/azure-ai-openai/src/samples/java/com/azure/ai/openai/ChatCompletionsWithYourData.java#L59

**Comment by mkemmerz** [comment]
Thanks for the support!
