### ISSUE TITLE
[FEATURE REQ] Add the 'seed' parameter to the chat completion options class

### ISSUE THREAD

**Issue by aditya-qapitol** [Azure/azure-sdk-for-java#37535]
**Is your feature request related to a problem? Please describe.**
With the release of the GPT-4-turbo a new `'seed'` parameter is available in the API schema which I need to be able to call when creating the request using the `ChatCompletionOptions` class.

**Describe the solution you'd like**
A field/property in the `ChatCompletionOptions` class.

**Describe alternatives you've considered**
None

**Additional context**
None

**Information Checklist**
Kindly make sure that you have added all the following information above and checkoff the required fields otherwise we will treat the issuer as an incomplete report
- [x] Description Added
- [x] Expected solution specified

**Comment by joshfree** [comment]
@mssfang

**Comment by mssfang** [comment]
@aditya-qapitol We will add this support in the next coming SDK version, and expect to have it released in a week. Will keep you posted once it is released.

**Comment by aditya-qapitol** [comment]
@mssfang Thank you for the update.

**Comment by mssfang** [comment]
https://repo1.maven.org/maven2/com/azure/azure-ai-openai/1.0.0-beta.6/

We just released a new version of OpenAI SDK for Java. You can set the seed value in ChatCompletionsOptions 
```java
  // Use a fixed integer to generate consistent outputs.
  ChatCompletionsOptions chatCompletionsOptions = new ChatCompletionsOptions(chatMessages)
      .setSeed(123L);
```

**Comment by aditya-qapitol** [comment]
@mssfang Now I'm able to access the 'seed' parameter in the Beta 6 version. Thanks again.
