### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by minnieshi** [Azure/azure-sdk-for-java#37536]
**Describe the bug**
using azure-sdk-bom being 1.2.10,  list blob storage (by page, and with option of showing deleted ones) does not show deleted items

***Exception or Stack Trace***
Add the exception log and stack trace if available

**To Reproduce**
azure-sdk-bom = 1.2.10

***Code Snippet***
```
  def listBlobsFlatWithOptions(
      blobContainerClient: BlobContainerClient,
      isFullLoad: Boolean,
      sinceDate: Option[OffsetDateTime],
      untilDateRightExclusive: Option[OffsetDateTime],
      blobPrefix: Option[String] = None
  ) = {

    val details: BlobListDetails = new BlobListDetails()
      .setRetrieveMetadata(true)
      .setRetrieveDeletedBlobs(true)
      .setRetrieveDeletedBlobsWithVersions(true)

    val maxPerPage: Int = 3000 // default: is 5000 items
    val options = new ListBlobsOptions()
      .setMaxResultsPerPage(maxPerPage)
      .setPrefix(blobPrefix.getOrElse(""))
      .setDetails(details)

    val streamsOfBlob = blobContainerClient
      .listBlobs(options, null)
      .stream
      .filter { blob =>
        val modifiedTime        = blob.getProperties.getLastModified
        val blobDeletedDateTime = blob.getProperties.getDeletedTime
        val blobIsDeleted       = blob.isDeleted
        isFullLoad || (
          modifiedTime.isAfter(sinceDate.get) && modifiedTime.isBefore(untilDateRightExclusive.get) ||
            blobIsDeleted && blobDeletedDateTime.isAfter(sinceDate.get) && blobDeletedDateTime.isBefore(untilDateRightExclusive.get)
        )
      } 

    val result: stream.Stream[AssetMetadata] = for {
      blob <- streamsOfBlob
    } yield {
      val urlWithCdn               = getUrl(blobContainerClient, blob).replace("blob.core.windows", "azureedge")
      val blobName                 = blob.getName
      val blobLastModifiedDatetime = blob.getProperties.getLastModified
      val blobIsDeleted            = blob.isDeleted
      val bobDeletedDateTime       = blob.getProperties.getDeletedTime
      //          itemId: note: delay getting original product_id to core layer logic; reason: to Landing is pure metadata"
      AssetMetadata(
        name = blobName,
        urlWithCdn = urlWithCdn,
        isDeleted = blobIsDeleted,
        lastModified = blobLastModifiedDatetime,
        bobDeletedDateTime
      )
    }
    result
  }
```

**Expected behavior**
show deleted blobs

**Screenshots**

**Setup (please complete the following information):**
 - IDE: [e.g. IntelliJ]
 - Library/Libraries: [e.g. com.azure:azure-core:1.16.0 (groupId:artifactId:version)]
 - Java version: [e.g. 8] 
 - App Server/Environment: [e.g. Tomcat, WildFly, Azure Function, Apache Spark, Databricks, IDE plugin or anything special]
 - Frameworks: [e.g. Spring Boot, Micronaut, Quarkus, etc] 

If you suspect a dependency version mismatch (e.g. you see `NoClassDefFoundError`, `NoSuchMethodError` or similar), please check out [Troubleshoot dependency version conflict article](https://aka.ms/azsdk/java/dependency/troubleshoot) first. If it doesn't provide solution for the problem, please provide:
- verbose dependency tree (`mvn dependency:tree -Dverbose`)
- exception message, full stack trace, and any available logs

**Additional context**

**Information Checklist**
Kindly make sure that you have added all the following information above and checkoff the required fields otherwise we will treat the issuer as an incomplete report
- [x] Bug Description Added
- [x] Repro Steps Added
- [x] Setup information Added

**Comment by minnieshi** [comment]
the code snippet is in scala

**Comment by minnieshi** [comment]
Q: does one must have soft delete enabled to list the deleted blob?
I know my code used to work, but i can not prove whether at the time, the soft delete was accidently (not ware of it) enabled.

**Comment by ibrahimrabab** [comment]
Hi @minnieshi 
In order to view deleted blobs, the storage account you are using must have soft delete for blobs enabled. Can you confirm if this is enabled and try to list the deleted blobs again?

**Comment by minnieshi** [comment]
Worked as guessed and suggested
