### ISSUE TITLE
Remove HTTP annotations from `com.generic.core.annotations`

### ISSUE THREAD

**Issue by vcolin7** [Azure/azure-sdk-for-java#37576]
Move them to `com.generic.core.http.annotations` and evaluate if it's preferable to reduce the amount of annotations in favor of having a `HttpRequestInformation` with members like `method` and `path`, as suggested [here](https://apiview.dev/Assemblies/Review/ad330c0d401e45adb0fde58ac674c3cb#aa3c4e9d37c543c1bd3e1f187b9aaa72).
```[tasklist]
### Tasks
- [x] Move HTTP-specific annotations to the `http.annotations` package
- [x] Reduce the amount of annotations in favor of using `HttpRequestInformation` and `HttpResponseInformation`
```

**Comment by vcolin7** [comment]
We've moved the annotations to the aforementioned package. All that remains is refactoring code to use `HttpRequestInformation`.

**Comment by vcolin7** [comment]
Should we get rid of `HeaderCollection`? It's Azure Core counterpart is only used in Storage at the moment and only works when deserializing headers to specific classes, which I don't think we want to do from the get go? That would also mean we need to remove `ObjectSerializer.deserialize(Headers, Type)`. What do you think @JonathanGiles, @srnagar, @lmolkova?

**Comment by vcolin7** [comment]
On a related note, we don't have anything that acts like a "header delimiter" annotation as we had previously discussed. I don't think we should add it until later.

**Comment by srnagar** [comment]
Yes, we don't need to eagerly add HeaderCollection until it's required.
