### ISSUE TITLE
Evaluate simplifying `HttpException` hierarchy

### ISSUE THREAD

**Issue by vcolin7** [Azure/azure-sdk-for-java#37578]
From [here](https://apiview.dev/Assemblies/Review/ad330c0d401e45adb0fde58ac674c3cb#87dd7dc103c04648924c64c16f3ced37):

> There's a part of me that would argue to simplify our exception hierarchy to just HttpResponseException and HttpRequestException. I would introduce an HttpExceptionType ExpandableStringEnum with values for RESOURCE_EXISTS, etc. I would then move these two exception types and the enum into the appropriate *.http.* package.

**Comment by samvaity** [comment]
Duplicate #37567
