### ISSUE TITLE
[QUERY] Priority for virtual Machine

### ISSUE THREAD

**Issue by superDoss** [Azure/azure-sdk-for-java#3758]
What is the easiest way to fetch Priority of virtual machine using java api?

**Comment by kurtzeborn** [comment]
Thank you for opening this issue! We are routing it to the appropriate team for follow up.

**Comment by yaohaizh** [comment]
@superDoss  something you can refer here: https://github.com/Azure/azure-libraries-for-java/blob/d8683bc4e8cb84f2c4a919ec5451c161e37d4296/azure-mgmt-compute/src/test/java/com/microsoft/azure/management/compute/VirtualMachineOperationsTests.java#L198

**Comment by yaohaizh** [comment]
Close as the feature is implemented.
