### ISSUE TITLE
[BUG] Cannot Copy a blob from one path to another and Restore a deleted blob. Soft deleted enabled in my account. 

### ISSUE THREAD

**Issue by kirankumar994** [Azure/azure-sdk-for-java#37625]
**Describe the bug**
I am facing two issues. One is with copying a blob from one to another path within the same container. And the other issue is with restoring a deleted blob when using container SAS token credetials. I have enabled soft delete option in my storage account. Please find the exception I am getting below when I am trying copy and restore. Also the please look at my code snippet of both methods. 

The strange part I observed is, when I keep my container access in blob or container level, they both seems working fine without any exceptions. Only, I am getting the below exception when the container is in private level. And the other part I am able to delete, add tags without exceptions even if the container is private level. Please let me know if I am missing anything here. I am happy to share more details if you need anything. 

***Exception or Stack Trace***
Status code 401, "﻿<?xml version="1.0" encoding="utf-8"?><Error><Code>CannotVerifyCopySource</Code><Message>Server failed to authenticate the request. Please refer to the information in the www-authenticate header.
RequestId:74bb6c09-901e-0074-5b8c-15d40e000000
Time:2023-11-12T17:22:14.9629004Z</Message></Error>"

com.azure.storage.blob.models.BlobStorageException: Status code 401, "﻿<?xml version="1.0" encoding="utf-8"?><Error><Code>CannotVerifyCopySource</Code><Message>Server failed to authenticate the request. Please refer to the information in the www-authenticate header.
RequestId:74bb6c09-901e-0074-5b8c-15d40e000000
Time:2023-11-12T17:22:14.9629004Z</Message></Error>"

***Code Snippet***
Restore blob:
   @Override
    public Mono<Document> restoreDocument(Document document) {
        if (LOG.isDebugEnabled()) LOG.debug("restoreDocument: Restoring the document ===>" + document);

        BlobContainerAsyncClient blobContainerAsyncClient = blobServiceAsyncClient.getBlobContainerAsyncClient(document.getDocumentLibraryId());
        BlobAsyncClient blobAsyncClient = blobContainerAsyncClient.getBlobAsyncClient(document.getDocumentName());

        ListBlobsOptions options = new ListBlobsOptions()
                .setPrefix(document.getDocumentName())
                .setDetails(new BlobListDetails()
                        .setRetrieveDeletedBlobs(true)
                        .setRetrieveVersions(true));

        return blobContainerAsyncClient
                .listBlobs(options)
                .switchIfEmpty(Mono.error(new RepositoryException(MessageCodes.DMS121, MessageCodes.DOCUMENT_PARAM)))
                .map(BlobItem::getVersionId)
                .sort(Comparator.reverseOrder())
                .next()
                .flatMap(version -> {
                    BlobAsyncClient blob = blobContainerAsyncClient.getBlobVersionAsyncClient(document.getDocumentName(), version);
                    return blob.getTags()
                            .flatMap(tags -> { // Get tags from the deleted blob version
                                BlobCopyFromUrlOptions copyOptions = new BlobCopyFromUrlOptions(blob.getBlobUrl())
                                        .setMetadata(document.getMetadata())
                                        .setTags(tags);
                                return blobAsyncClient.copyFromUrlWithResponse(copyOptions);
                            });
                })
                .then(Mono.just(document))
                .onErrorResume(BlobStorageException.class, this::handleBlobStorageException);
    }
    
    Copy blob:
    
     @Override
    public Mono<Document> cloneDocument(Document document) {
        if (LOG.isDebugEnabled()) LOG.debug("cloneDocument: Copying the document to the requested destination ===>" + document);

        BlobContainerAsyncClient blobContainerAsyncClient = blobServiceAsyncClient.getBlobContainerAsyncClient(document.getDocumentLibraryId());
        BlobAsyncClient sourceBlob = blobContainerAsyncClient.getBlobAsyncClient(document.getDocumentName());

        BlobAsyncClient destBlob = blobContainerAsyncClient
                .getBlobAsyncClient(document.getFilePath() + "/" + document.getDocumentName());
        destBlob.setMetadata(null);

        return sourceBlob.getTags()
                .flatMap(sourceTags -> { // Get tags from the source blob
                    BlobBeginCopyOptions copyOptions = new BlobBeginCopyOptions(sourceBlob.getBlobUrl())
                            .setMetadata(document.getMetadata())
                            .setTags(sourceTags);
                    return destBlob.beginCopy(copyOptions)
                            .then(Mono.just(document));
                })
                .onErrorResume(BlobStorageException.class, this::handleBlobStorageException);
    }

**Expected behavior**
The blob should be copied without any exceptions. And the deleted blob also should be restored without any exceptions.

**Comment by alzimmermsft** [comment]
@ibrahimrabab or @ibrandes could you take a look at this issue

**Comment by ibrahimrabab** [comment]
Hi @kirankumar994 
Thanks for reaching out! Looks like the issue you're seeing has to do with permissions. Can you ensure that you have the correct SAS permissions as listed in this documentation:
For copying: https://learn.microsoft.com/en-us/rest/api/storageservices/copy-blob?tabs=microsoft-entra-id#permissions
For undelete: https://learn.microsoft.com/en-us/rest/api/storageservices/undelete-blob?tabs=microsoft-entra-id#permissions

Can you let me know if after adding the necessary permissions are you able to copy the blob and undelete the blob? If you still run into issues, please list out all the permissions you are trying to add. 

Also had another question, when you say "private level", what do you mean by this? Do you mean having the "Allow Blob anonymous access" enabled/disabled?

**Comment by kirankumar994** [comment]
Hi @ibrahimrabab , 
Thank you for your response. I am using container Sas Token to build ServiceAsyncClient with the BlobServiceClientBuilder(). Please find the code snippet below how I created a Bean and using the blobServiceAsyncClient across the application to build blobContainerAsyncClient and blobAsyncClient for the container and blob operations. 

    // Building a ServiceClient
    @Bean
    public BlobServiceAsyncClient blobServiceAsyncClient() {
        
        BlobServiceAsyncClient blobServiceAsyncClient  =  new BlobServiceClientBuilder()
                .endpoint(endPointUrl)
                .sasToken(sasToken)
                .buildAsyncClient();

        return blobServiceAsyncClient;
    }
    
    // Building ContainerClient and BlobClient
    
    BlobContainerAsyncClient blobContainerAsyncClient = 
                                                           blobServiceAsyncClient.getBlobContainerAsyncClient(document.getDocumentLibraryId());
                                                           
    BlobAsyncClient sourceBlob = blobContainerAsyncClient.getBlobAsyncClient(document.getDocumentName());
    
    I think I am adding necessary permissions to build the serviceClient as I am trying to copy the blob within the same storage account. Or, should I create blob level Sas token to the sourceBlob? Please let me know what I am missing here. 
    
    To the other question, I meant disabling Container and Blob anonymous access. That means, my containers are in private access, because I don't to keep them with anonymous access for accessing the blob urls publicly. Hope I answered your question. Looking forward to your response. 
    
    Thank you

**Comment by ibrahimrabab** [comment]
@kirankumar994 how are you generating your SAS token? You may be missing certain permissions when generating the sas token. Since you are trying to perform copy and restore operations, you will need to enable multiple permissions like so:
![image](https://github.com/Azure/azure-sdk-for-java/assets/88855721/059fe212-1f0b-405b-a20b-4dd88090f093)

Can you try adding enabling multiple (such as read, write, delete) permissions and see if you're able to copy and restore?
