### ISSUE TITLE
[QUERY] Is it possible to index Blob index tags in Azure search?

### ISSUE THREAD

**Issue by kirankumar994** [Azure/azure-sdk-for-java#37658]
**Query/Question**
I have some blobs tagged with specific key value pairs in my container. What I am trying to do is, indexing the blob content, blob custom metadata along with it tags. I am able to search the content by keyphrase and metadata values by defining metadata key as fieldnames in my index. I tried the same with tags as well by defining tags key as field names, but seems like tags are not getting indexed as a part of azure search. Is there anything I am missing here or indexing blob tags not supported by Azure itself? 

***Why is this not a Bug or a feature Request?***
A clear explanation of why is this not a bug or a feature request?

**Setup (please complete the following information if applicable):**
 - IDE: [e.g. IntelliJ]
 - Library/Libraries: [e.g. com.azure:azure-core:1.16.0 (groupId:artifactId:version)]
 
 **Information Checklist**
 Kindly make sure that you have added all the following information above and checkoff the required fields otherwise we will treat the issuer as an incomplete report
- [ ] Query Added
- [ ] Setup information Added

**Comment by alzimmermsft** [comment]
Thank you for asking this question @kirankumar994.

Based on Azure Cognitive Search's documentation for Storage Blob data sources it appears that tags aren't supported at this time:

https://learn.microsoft.com/azure/search/search-howto-indexing-azure-blob-storage#indexing-blob-metadata

It is mentioned at the very bottom of the section, right before the "Define the data source" section.
