### ISSUE TITLE
[Can i read full blob content via blobclient.openInputstream() or only till 4194304 bytes]

### ISSUE THREAD

**Issue by prashantharshi** [Azure/azure-sdk-for-java#37709]
I have a use case where i need to ingest a large file present in the Azure blob to one of my service
The service expects a multipart upload where i need to provide an Inputstream and contentRange
Size of the file in azure blob is 300 MB and i am trying to do a multi part/chunked upload by calling one of my service to ingest this file (in chunks of 100 MB)

The code i am using 

InputStream bis = blobClient.openInputStream(); 
for (long chunk = 0; chunk < chunks ; chunk++) {
                 try (BoundedInputStream bis = new BoundedInputStream(inputStream, thisChunkSize);) {
                    bis.setPropagateClose(false);
                    response = service.uploadFilepart(....params, content_range, bis);
                } 
}

The issue i am facing is that remote server is responding with 408 (ie client not sending bytes and hence server chose to shut the connection) , so i am wondering if downstream service is not able to read the content range (0 to 100MB) from the inputStream that was passed ?....Is it because the default implementation of openInputStream only creates a buffer of 4.1 MB , and after which we again need to open a stream to read the rest part ?
Because when i changed the implementation  to

BlobInputStreamOptions options = new BlobInputStreamOptions()
                            .setBlockSize(BLOCK_DOWNLOAD_CHUNK_SIZE);   //size as 100 MB
InputStream bis = blobClient.openInputStream(options);

i was able to do two chunks upload of 50 MB each ...

So does it mean we need to openTheInputStream to the limit of file size in order to read the full file gracefully ?

**Comment by prashantharshi** [comment]
+ @gapra-msft @rickle-msft

**Comment by gapra-msft** [comment]
@ibrahimrabab @ibrandes

**Comment by ibrahimrabab** [comment]
Hi @prashantharshi 
I'm trying to reproduce your code snippet but it's not in a working state. Can you provide me a full code snippet that I can reproduce locally, and can you also provide a full stack trace of the error logs you're seeing? Thanks!
