### ISSUE TITLE
[QUERY] compatible versions of the classes com.azure.cosmos.implementation.http.HttpClient and reactor.netty.resources.ConnectionProvider

### ISSUE THREAD

**Issue by Helene-byte** [Azure/azure-sdk-for-java#37726]
**Query/Question**
A clear and concise ask/query. Could you help me to fix dependency issues? Please, run com.chtrembl.petstore.order.repository.Swagger2SpringBoot from 
https://github.com/Helene-byte/cloudx-java-azure-dev/tree/cosmos/petstore/petstoreorderservice to see the error 

***Why is this not a Bug or a feature Request?***
A clear explanation of why is this not a bug or a feature request?
my knowledge is limited thus would like to raise a question

**Setup (please complete the following information if applicable):**
 - OS: [e.g. iOS] iOS
 - IDE: [e.g. IntelliJ]IntelliJ
 - Library/Libraries: [e.g. com.azure:azure-core:1.16.0 (groupId:artifactId:version)] https://github.com/Helene-byte/cloudx-java-azure-dev/blob/cosmos/petstore/petstoreorderservice/pom.xml
 
 **Information Checklist**
 Kindly make sure that you have added all the following information above and checkoff the required fields otherwise we will treat the issuer as an incomplete report
- [ ] Query Added
- [ x] Setup information Added

**Comment by joshfree** [comment]
Hi @Helene-byte thanks for reaching out.  Someone from the `Cosmos` team will follow up with you shortly.

Please note that there's documentation here on troubleshooting dependency conflicts: https://learn.microsoft.com/en-us/azure/developer/java/sdk/troubleshooting-dependency-version-conflict.

/cc @kushagraThapar

**Comment by kushagraThapar** [comment]
@Helene-byte to solve any dependency issues regarding this, you will need to use the compatible versions of azure-cosmos and azure-core, which you can refer from here - https://mvnrepository.com/artifact/com.azure/azure-cosmos
If you navigate to any of the azure-cosmos version, it will show you which version of azure-core and which version of azure-core-http-netty to use. azure-core and azure-core-http-netty will automatically bring reactor-core and reactor-netty versions. This should fix your issue. 

If not, please feel free to reopen this.
