### ISSUE TITLE
[FEATURE REQ] Need support for updating MinimumTLSversion of EventHubnamespace using azure-resourcemanager-eventhubs

### ISSUE THREAD

**Issue by Amitchauhangit** [Azure/azure-sdk-for-java#37721]
**Is your feature request related to a problem? Please describe.**
We wanted to update MinTLSversion in Azure EventHub Namespace resource (https://learn.microsoft.com/en-us/azure/event-hubs/transport-layer-security-configure-minimum-version) using EventHub MGMT Java SDK.

**Describe the solution you'd like**
As the MinTLSVersion property for EventHub Namespace create or update is available in REST API (not documented but property is functional) : 

curl --location --request PUT 'https://management.azure.com/subscriptions/<SUB-ID>/resourceGroups/<ResourGroup-Name>/providers/Microsoft.EventHub/namespaces/<EventHubNamespace>?api-version=2023-01-01-preview' \
--header 'Authorization: Bearer-token' \
--header 'Content-Type: application/json' \
--data '{
    "location":"eastus",  //required param
    "properties": {
    "zoneRedundant": true,  //required param
    **"minimumTlsVersion": "1.2"**
      }
}'

So we need support for the same property in EventHubInner class of "azure.resourcemanager.eventhubs.fluent.models".

**Describe alternatives you've considered**
Apart from Azure Portal, we can use Java HTTPClient to make request above to RESTAPI (mimicking Az Portal). 

**Information Checklist**
Kindly make sure that you have added all the following information above and checkoff the required fields otherwise we will treat the issuer as an incomplete report
- [+] Description Added
- [+] Expected solution specified

**Comment by weidongxu-microsoft** [comment]
`minimumTlsVersion` appears added in 2023-01-01-preview
https://learn.microsoft.com/rest/api/eventhub/namespaces/create-or-update?view=rest-eventhub-2023-01-01-preview&tabs=HTTP

Java had not released for this preview api-version. Plan a 2.23.0-beta.1 eventhubs SDK

**Comment by weidongxu-microsoft** [comment]
@XiaofeiCao Could you notify Hong to work on it early next week?

premium SDK, preview release, release on release branch.

**Comment by v-hongli1** [comment]
https://central.sonatype.com/artifact/com.azure.resourcemanager/azure-resourcemanager-eventhubs/2.33.0-beta.1

**Comment by weidongxu-microsoft** [comment]
@v-hongli1 

Could you try if `minimumTlsVersion` can be set in https://github.com/Azure/azure-sdk-for-java/blob/azure-resourcemanager-eventhubs_2.33.0-beta.1/sdk/resourcemanager/azure-resourcemanager/src/samples/java/com/azure/resourcemanager/eventhubs/generated/NamespacesCreateOrUpdateSamples.java#L36-L59 ?

No need to have a sample or test, just trial and check if this works.

**Comment by v-hongli1** [comment]
@weidongxu-microsoft  
The `minimumTlsVersion` can be set and working.

**Comment by weidongxu-microsoft** [comment]
see it on 2024-01-01 https://learn.microsoft.com/en-us/rest/api/eventhub/namespaces/create-or-update?view=rest-eventhub-2024-01-01&viewFallbackFrom=rest-eventhub-2023-01-01-preview&tabs=HTTP

wait for SDK release request from eventhubs service for a GA SDK release

**Comment by Amitchauhangit** [comment]
/unresolve 
@weidongxu-microsoft EventHub team has released a stable api-version 2024-01-01 with minTLS version param.

https://learn.microsoft.com/en-us/rest/api/eventhub/namespaces/create-or-update?view=rest-eventhub-2024-01-01&tabs=HTTP

**Comment by Amitchauhangit** [comment]
@weidongxu-microsoft Is there any request you received from EventHub service SDK realease?

**Comment by weidongxu-microsoft** [comment]
No, not yet.

I am emailing SDK PM to see if we can get info from service about whether they are ready.

**Comment by schaudhari6254888** [comment]
> @weidongxu-microsoft The `minimumTlsVersion` can be set and working.

Hey @v-hongli1 , that means SDK version 2.33.0-beta.1 is supported MinTls version, right? (Just confirming)
so we can suggest to use this version to avoid all confusion.
Thank you!

**Comment by schaudhari6254888** [comment]
> see it on the new 2024-01-01 https://learn.microsoft.com/en-us/rest/api/eventhub/namespaces/create-or-update?view=rest-eventhub-2024-01-01&tabs=HTTP
> 
> wait for SDK release request from eventhubs service for a GA SDK release

Hey @weidongxu-microsoft , the MinTls is supported from long back. Api version is NOT live Which is present in 2024-01-01. min tls should have been there even before.

**Comment by XiaofeiCao** [comment]
@schaudhari6254888 

Yes 2.33.0-beta.1 supported MinTls. 

MinTls is not present in previous stable version: https://learn.microsoft.com/en-us/rest/api/eventhub/namespaces/create-or-update?view=rest-eventhub-2021-11-01&tabs=HTTP

**Comment by weidongxu-microsoft** [comment]
Thank you @schaudhari6254888

@Amitchauhangit As mentioned in https://github.com/Azure/azure-sdk-for-java/issues/37721#issuecomment-1897919505, 2024-01-01 is not yet live, so SDK cannot release for that.

Please still use 2.33.0-beta.1 before we get notice from service about 2024-01-01 go live.

**Comment by weidongxu-microsoft** [comment]
@v-hongli1 

Please add support for `zoneRedundant` and `minimumTlsVersion` to `EventHubNamespace` interface.

Plan be July.

PS, I will try add a directive to change the name for this kind of value in `TlsVersion`.
```
    public static final TlsVersion ONE_ZERO = fromString("1.0");
```

We'd like it be called e.g. `TLS1_0`.

**Comment by XiaofeiCao** [comment]
The feature has been supported in 2.41.0:
https://github.com/Azure/azure-sdk-for-java/blob/main/sdk/resourcemanager/azure-resourcemanager-eventhubs/src/test/java/com/azure/resourcemanager/eventhubs/EventHubTests.java#L606-L649
