### ISSUE TITLE
[BUG] `BlobServiceAsyncClient`  gets initialized and works fine with a wrong storage account key.

### ISSUE THREAD

**Issue by rohit2395** [Azure/azure-sdk-for-java#37733]
**Describe the bug**

`BlobServiceAsyncClient`  gets initialized and works fine with a wrong storage account key.

***Exception or Stack Trace***
Add the exception log and stack trace if available

**To Reproduce**
1. Let's say you have the azure storage account key - XXXXXXXXXXXXXXXXA==
2. Just change the last character of the  key  - XXXXXXXXXXXXXXXXB==
3. The client is successfully initialized and works fine. All the blob operations are also working.

***Code Snippet***
Add the code snippet that causes the issue.

**Expected behavior**
The `BlobServiceAsyncClient` should not work if initialized with the wrong storage account key as per the steps mentioned in the steps to reproduce

**Screenshots**

**Setup (please complete the following information):**
 - OS: MacOs Sonoma
 - IDE: IntelliJ
 - Library/Libraries: com.azure:azure-storage-blob:12.17.1
 - Java version: 17
 - App Server/Environment: NA
 - Frameworks: NA

If you suspect a dependency version mismatch (e.g. you see `NoClassDefFoundError`, `NoSuchMethodError` or similar), please check out [Troubleshoot dependency version conflict article](https://aka.ms/azsdk/java/dependency/troubleshoot) first. If it doesn't provide solution for the problem, please provide:
- verbose dependency tree (`mvn dependency:tree -Dverbose`)
- exception message, full stack trace, and any available logs

**Additional context**

**Information Checklist**
Kindly make sure that you have added all the following information above and checkoff the required fields otherwise we will treat the issuer as an incomplete report
- [x] Bug Description Added
- [x] Repro Steps Added
- [x] Setup information Added

**Comment by ibrahimrabab** [comment]
Hi @rohit2395 
I've tested this out and this operation will not succeed if the shared key does not match the appropriate storage account. If the shared key does not match the storage account, it will immediately throw a 403 error code. Can you please double check if you are setting up the client properly? Feel free to share the code snippet you are using to set up the BlobServiceAsyncClient.
