### ISSUE TITLE
[BUG] core, in RetryPolicy.attemptSync, delayDuration is not used

### ISSUE THREAD

**Issue by weidongxu-microsoft** [Azure/azure-sdk-for-java#37799]
**Describe the bug**

code, `attemptSync` in azure-core: https://github.com/Azure/azure-sdk-for-java/blob/775e676/sdk/core/azure-core/src/main/java/com/azure/core/http/policy/RetryPolicy.java#L188-L199

Here, the `delayDuration` is calculated and logged, but never actually used.

***Exception or Stack Trace***
Add the exception log and stack trace if available

**To Reproduce**

***Code Snippet***
Add the code snippet that causes the issue.

**Expected behavior**

**Screenshots**

**Setup (please complete the following information):**
 - IDE: [e.g. IntelliJ]
 - Library/Libraries: com.azure:azure-core:1.45.0
 - Java version: [e.g. 8] 
 - App Server/Environment: [e.g. Tomcat, WildFly, Azure Function, Apache Spark, Databricks, IDE plugin or anything special]
 - Frameworks: [e.g. Spring Boot, Micronaut, Quarkus, etc] 

If you suspect a dependency version mismatch (e.g. you see `NoClassDefFoundError`, `NoSuchMethodError` or similar), please check out [Troubleshoot dependency version conflict article](https://aka.ms/azsdk/java/dependency/troubleshoot) first. If it doesn't provide solution for the problem, please provide:
- verbose dependency tree (`mvn dependency:tree -Dverbose`)
- exception message, full stack trace, and any available logs

**Additional context**

**Information Checklist**
Kindly make sure that you have added all the following information above and checkoff the required fields otherwise we will treat the issuer as an incomplete report
- [ ] Bug Description Added
- [ ] Repro Steps Added
- [ ] Setup information Added

**Comment by alzimmermsft** [comment]
This was fixed by https://github.com/Azure/azure-sdk-for-java/pull/37788
