### ISSUE TITLE
[FEATURE REQ] Make AccessTokenCache refresh offset configurable

### ISSUE THREAD

**Issue by MichalKoziorowski-TomTom** [Azure/azure-sdk-for-java#37798]
**Is your feature request related to a problem? Please describe.**

In https://github.com/Azure/azure-sdk-for-java/blob/main/sdk/core/azure-core/src/main/java/com/azure/core/implementation/AccessTokenCache.java#L59 I see that REFRESH_OFFSET is hardcoded to 5 minutes. I would like to have this configurable to avoid any possibilities of outage caused by temporary problems in refreshing mechanism for instance taking more than 5 minutes. If I have a token valid for 24 hours, I would like to be able to start refreshing it 3 or 12 or in the middle of validity time. 

**Describe the solution you'd like**
I would like to have this value configurable per token or per percentage of validity, so that I would be able to start refreshing when 50% of validity time passed. 

**Information Checklist**
Kindly make sure that you have added all the following information above and checkoff the required fields otherwise we will treat the issuer as an incomplete report
- [x] Description Added
- [x] Expected solution specified

**Comment by joshfree** [comment]
@g2vinay could you please follow up?

**Comment by g2vinay** [comment]
We've pushed a change where longer lived tokens for MI scenario, will refresh at half the validity time.
and for other scenarios, if Azure STS, returns a refresh_in value back as part of response, we will honour it.

Further, AccessToken now accets a refreshAt value, which you can pass in, to make it refresh at a specific time.
Use the latest Azure Identity and Azure Core libraries to use this feature.
