### ISSUE TITLE
Cosmos DB Encryption Samples Issue

### ISSUE THREAD

**Issue by faynef** [Azure/azure-sdk-for-java#37809]
1.

**Section:** [link](https://github.com/Azure/azure-sdk-for-java/blob/main/sdk/cosmos/azure-cosmos-encryption/src/samples/java/com/azure/cosmos/encryption/ReadmeSamples.java#L130).
<img width="400" alt="image" src="https://github.com/Azure/azure-sdk-for-java/assets/138087452/e9a1a207-2158-43b1-bbc2-07c472d2f0ba">

**Reason:** 
![image](https://github.com/Azure/azure-sdk-for-java/assets/138087452/9685fd06-2b09-4c52-94b5-2d6e610f59ae)
Run createItem() shows: Failed to serialize the object into json.

**Suggestion:**
	Add code in class `Pojo`
```
String getSensitiveString() {
        return sensitiveString;
	}
```

@sandeep-sen , @joshfree , @kyle-patterson , @KrzysztofCwalina and @aayush3011 to notification.

**Comment by v-xuto** [comment]
PR https://github.com/Azure/azure-sdk-for-java/pull/38575 has been merged, we will close this issue.
