### ISSUE TITLE
[BUG]Issue connecting ACS to Cognitive Services - Cognitive Services Authentication error. 

### ISSUE THREAD

**Issue by JohnMelody** [Azure/azure-sdk-for-java#37812]
Similar issue to https://github.com/Azure/azure-sdk-for-net/issues/38573

I have an issue with the Call Automation OpenAI_Sample in Java. I have simply downloaded the sample and built it and deployed it as a Spring Application in my Azure environment.

### Library Name and version.
Azure.Communication.CallAutomation 1.1.0 ( I updated the library - the download had a beta version(1.1.0-beta.1) initially but had the same issue with that)

### Problem Description
I am getting a 401 with Subcode 8565 but unlike the above referenced issue the voice name is set to "en-US-NancyNeural".

I have connected my ACS resource to my Cognitive Services resource as outlined in the documentation and it appears to be connected in ACS.

When the incoming call arrives I get the following error:
`023-11-24T12:27:25.042Z  INFO 1 --- [nio-8080-exec-7] c.c.callautomation.ProgramSample         : Call connected performing recognize for Call Connection ID: 411f3300-c0e2-4530-a4f1-a7e0d95e88ab 2023-11-24T12:27:25.637Z ERROR 1 --- [nio-8080-exec-9] c.c.callautomation.ProgramSample         : Received failed event: Action failed due to a Cognitive Services authentication error. Please check your authorization input and ensure it is correct.`

### Expected Behaviour
Plays a TTS message using my cognitive services resource into the call and runs a recognition on the response

### Additional Information
The application.yml file has the following:
`connectionstring: <ENTER YOUR ACS CONNECTION STRING> 
basecallbackuri: <ENTER YOUR DEV TUNNEL BASE URL> 
cognitiveServicesUrl: <ENTER YOUR COGNITIVE SERVICE URL> 
azureOpenAiServiceKey: <ENTER YOUR COGNITIVE SERVICE VAULT KEY> 
azureOpenAiServiceEndpoint: <ENTER YOUR COGNITIVE SERVICE URL> 
openAiModelName: <ENTER YOUR OPENAI MODEL NAME>`

There is no mention of the Cognitive Service "Key" - only the URL. It mentions a "Cognitive Service Vault Key" but that appears to be associated with the openai service key. I have added my cognitive services key to the "cognitiveServicesUrl"  using the ?key= notation on the url but that makes no difference either. 

If I go into speech studio and try out speech recognition and tts using the cognitive resource used above everything works as expected.

### **Setup (please complete the following information):**
 - OS: Azure Spring 
 - IDE: Eclipse
 - Library/Libraries: As per the OpenAI call automation example except for the one I upgraded to the latest version. 
 - Java version: 17
 - App Server/Environment: Azure Spring Container
 - Frameworks: Spring Boot
### 
**Additional context**

**Comment by joshfree** [comment]
@juntuchen-msft @cochi2 could you please assist?

**Comment by JohnMelody** [comment]
I sorted this out myself. The problem was the fact that I had created a Speech Services resource, since the first part of the sample deals with text to speech and speech to text. However, it looks like you need to create a "Multi Service Azure Cognitive Service". Once I did this and connected this to my ACS the sample works.

**Comment by mssfang** [comment]
@JohnMelody Glad you sorted it out. Is there anything we can help from here on?

**Comment by JohnMelody** [comment]
No thank you. This is working fine for me now. This can be closed.
