### ISSUE TITLE
[BUG] Usage of ResourceManager with multiple subscriptions not possible

### ISSUE THREAD

**Issue by roudee** [Azure/azure-sdk-for-java#37811]
**Describe the bug**
We are using the Azure SDK to manage Azure resources in different subscriptions. So far it works as we need but there is a huge blocker for us. The problem is to use the one ResourceManager with different subscriptions. Our current workaround is to create for each subscription a new ResourceManager BUT that only works if all resources in one request to Azure API are from the same subscription. 

For example:

- Create Virtual Machine in **Subscription A** with an Image from SharedImageGallery which is also in **Subscription A** works.
- Create Virtual Machine in **Subscription A** with an Image from SharedImageGallery which is in **Subscription B** leads to error 404 (Resource not found in **Subscription A**). Heres the problem. Even if the ResourceId of the image is completely correct and the permissions are there, the ResourceManager will automatically replace the SubscriptionId in the ResourceId with the one of the ResourceManager. This way the ResourceId is changed so that the requested resource is not available. The same call with Azure CLI works without any problems with the same identity.

***Exception or Stack Trace***
`Failed to create virtual machine with exception: Status code 404, "{"error":{"code":"ResourceGroupNotFound","message":"Resource group 'rg-example' could not be found."}}"`

**To Reproduce**
Look in Bug description

***Code Snippet***
`AzureProfile profile = new AzureProfile(AzureEnvironment.AZURE);
ClientSecretCredential credential = new ClientSecretCredentialBuilder()
.clientId(clientId)
.clientSecret(clientSecret)
.tenantId(tenantId)
.authorityHost(profile.getEnvironment()
.getActiveDirectoryEndpoint()).build();`

` azure = AzureResourceManager
.configure()
.withLogLevel(HttpLogDetailLevel.NONE)
.authenticate(credential, profile)
.withSubscription("A");`

`azure.virtualMachines()
.define("name")
.withRegion("region")
.withExistingResourceGroup("rg-example")
.withExistingPrimaryNetworkInterface(networkInterface)            
.withGeneralizedWindowsGalleryImageVersion("/subscriptions/B/resourceGroups/rg_gallery/providers/Microsoft.Compute/galleries/example_gallery/images/example-image/versions/0.0.1")
.withAdminUsername(vmDto.getUserName())
.withAdminPassword(vmDto.getPassword())
.withComputerName(vmDto.getComputerName())
.withOSDiskStorageAccountType(StorageAccountTypes.fromString(vmDto.getStorageType()))
.withOSDiskSizeInGB(vmDto.getStorageCapacity())
.withSize(vmDto.getSkuName())
.withSystemAssignedManagedServiceIdentity();`

**Expected behavior**
Virtual Machine creation should just work as with Azure CLI

**Comment by weidongxu-microsoft** [comment]
See https://learn.microsoft.com/azure/azure-resource-manager/management/authenticate-multi-tenant

For SDK, provide the token from 2nd subscription via `AzureResourceManager.configure().withAuxiliaryCredential(...)` (it basically adding the `x-ms-authorization-auxiliary` header of 2nd subscription for you)

**Comment by roudee** [comment]
@weidongxu-microsoft for now it seems to work, at least for this use case. thanks!
