### ISSUE TITLE
[BUG] spring-cloud-azure-feature-management provides a logging implementation

### ISSUE THREAD

**Issue by yanivnahoum** [Azure/azure-sdk-for-java#37814]
**Describe the bug**
For some reason, `com.azure.spring:spring-cloud-azure-feature-management` 5.x (but not 4.x) brings in `org.springframework.boot:spring-boot-starter-log4j2`. This causes slf4j to detect multiple bindings, which requires all consumers using the default logging provider (logback) to exclude it. Could you please remove it (as this is a library, not an application) or at least mark it as an optional dependency?

**Expected behavior**
The library shall not provide a logging implementation, only the api.

**Setup (please complete the following information):**
 - OS: macOS Ventura
 - IDE: Intellij
 - Library/Libraries: `com.azure.spring:spring-cloud-azure-feature-management` 5.x
 - Java version: 17
 - Frameworks: Spring Boot 2.7.x / 3.1.x

**Additional context**
```
./mvnw dependency:3.6.0:tree -Dincludes=org.apache.logging.log4j:log4j-slf4j2-impl

[INFO] \- com.azure.spring:spring-cloud-azure-starter-appconfiguration-config:jar:5.7.0:compile
[INFO]    \- com.azure.spring:spring-cloud-azure-feature-management-web:jar:5.7.0:compile
[INFO]       \- com.azure.spring:spring-cloud-azure-feature-management:jar:5.7.0:compile
[INFO]          \- org.springframework.boot:spring-boot-starter-log4j2:jar:3.1.6:compile
[INFO]             \- org.apache.logging.log4j:log4j-slf4j2-impl:jar:2.20.0:compile
```

**Information Checklist**
Kindly make sure that you have added all the following information above and checkoff the required fields otherwise we will treat the issuer as an incomplete report
- [x] Bug Description Added
- [x] Repro Steps Added
- [x] Setup information Added

**Comment by Netyyyy** [comment]
@mrm9084 please take a look

**Comment by rujche** [comment]
Closing this issue because related PR has been merged.
