### ISSUE TITLE
dall-e 3 support

### ISSUE THREAD

**Issue by ryangsun** [Azure/azure-sdk-for-java#37826]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Information Checklist**
Kindly make sure that you have added all the following information above and checkoff the required fields otherwise we will treat the issuer as an incomplete report
- [ ] Description Added
- [ ] Expected solution specified

**Comment by joshfree** [comment]
@mssfang PTAL

**Comment by mssfang** [comment]
Hi @ryangsun  We will support the dall-e 3 in the coming SDK version. Will keep you posted. ETA: within a week or two.

**Comment by mssfang** [comment]
A new version beta.6 is out: https://repo1.maven.org/maven2/com/azure/azure-ai-openai/1.0.0-beta.6/

Dall-e 3 is supported in this new version.

**Comment by ryangsun** [comment]
> A new version beta.6 is out: https://repo1.maven.org/maven2/com/azure/azure-ai-openai/1.0.0-beta.6/
> 
> Dall-e 3 is supported in this new version.

thank you very match!!!
