### ISSUE TITLE
Add more `StreamResponse` features and QoL improvements

### ISSUE THREAD

**Issue by vcolin7** [Azure/azure-sdk-for-java#37845]
Add support for checking if the value of a `StreamResponse` is replayable, has been consumed, needs caching, chunking and other QoL additions. Consider scenarios like server sent events, messaging scenarios, or streaming of files.

Also, (per @lmolkova) investigate if using `InputStream` in all cases is the best approach for streaming responses:

- Sync and async.
- Replayable and not replayable. Asking SDKs to implement replayability over streams is a lot.
- Huge and tiny contents (streams are not super-cool with longer than max int sizes, also sometimes you know the content is small and buffering is desired).
- Serialization to/from objects - how friendly is it?

/cc @alzimmermsft

**Comment by vcolin7** [comment]
We moved away from using `StreamResponse` in favor of `Response<InputStream>` for the time being. However, we currently don't have a way of closing an `HttpResponse` like we used to.

**Comment by alzimmermsft** [comment]
`StreamResponse` was dropped as a concept and `BinaryData` was made extensible and the specific data type back `BinaryData` implementations were exposed. A few new APIs were added to make working with `BinaryData` cleaner when it came to the request - response workflows.
