### ISSUE TITLE
[BUG] AutoPR is not merging now

### ISSUE THREAD

**Issue by toothache** [Azure/azure-sdk-for-java#3785]
**Describe the bug**
The java sdk for azure should be auto generated from the swagger file in [azure-rest-api-spec](https://github.com/Azure/azure-rest-api-specs). Every time there's a swagger change, there will be PR automatically created for updating corresponding SDK. It works pretty fine for other languages like Python, Go, and Ruby. But it doesn't work for Java. For example, we have recent changes for CognitiveService Vision SDK. And there's PR created for updating Java SDK, but it failed at some checks and can not be merged.
https://github.com/Azure/azure-sdk-for-java/pull/3739

Besides, the commit history of vision SDK in this repo shows that it hasn't been updated for 10 months.
https://github.com/Azure/azure-sdk-for-java/commits/master/cognitiveservices/data-plane/vision/computervision

***Exception or Stack Trace***
Add the exception log and stack trace if available

**To Reproduce**

***Code Snippet***
Add the code snippet that causes the issue.

**Expected behavior**

**Screenshots**

**Setup (please complete the following information):**
 - IDE : [e.g. IntelliJ]
 - Version of the Library used

**Additional context**

**Information Checklist**
Kindly make sure that you have added all the following information above and checkoff the required fields otherwise we will treat the issuer as an incomplete report
- [x] Bug Description Added
- [ ] Repro Steps Added
- [ ] Setup information Added

**Comment by kurtzeborn** [comment]
CC: @salameer, @sergey-shandar

**Comment by sergey-shandar** [comment]
@daschult

**Comment by daschult** [comment]
Hi @toothache. I'm sorry to hear that our current automation isn't working well for you. We're currently in the process of making large changes to the automation between the specification repository and our various SDK repositories. These changes should drastically help in your scenario. These changes should be done in the next month (June 2019).

**Comment by toothache** [comment]
Hi, @sergey-shandar  @daschult . Has this issue been resolved? We got some related issues which is caused by the outdated vision sdk. The sdk under `cognitiveservices` folder hasn't been updated for almost a year. Can it be updated automatically or we should create PR for it?

[https://github.com/Azure/azure-sdk-for-java/issues/3636](#3636)
[https://github.com/Azure/azure-sdk-for-java/issues/3759](#3759 )

**Comment by yungezz** [comment]
hi @toothache SDK automation from azure-rest-api-specs has upgraded to v2. The current behavior is that every PR is azure-rest-api-specs repo will create a auto PR in this repo with merged status. SDK release owner could open the PR and do corresponding release action. Is this still a problem for you? and original PRs in description are data plane, not mgmt.

**Comment by yungezz** [comment]
@toothache I'll close the issue for now, since autoPR is created as closed today. feel free to open new issue if any other feedback, thanks.
