### ISSUE TITLE
Broken link for azure-mgmt-keyvault Github

### ISSUE THREAD

**Issue by joshzev** [Azure/azure-sdk-for-java#37851]
![image](https://github.com/Azure/azure-sdk-for-java/assets/125611223/d090dffb-385e-4d06-bd48-d97208f65fe1)
![image](https://github.com/Azure/azure-sdk-for-java/assets/125611223/10d4f00b-c849-4e06-9efd-5fe24e8b6a84)

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 4b7ff7dc-28e8-246e-65ab-55ed9397845c
* Version Independent ID: 40879875-3240-017a-75e6-d18996a6295a
* Content: [Azure Key Vault SDK for Java](https://learn.microsoft.com/en-us/java/api/overview/azure/key-vault?view=azure-java-stable)
* Content Source: [docs-ref-services/latest/key-vault.md](https://github.com/Azure/azure-docs-sdk-java/blob/master/docs-ref-services/latest/key-vault.md)
* Service: **keyvault**
* GitHub Login: @azure-sdk
* Microsoft Alias: **azsdkdocs**

**Comment by weidongxu-microsoft** [comment]
Thanks Josh. Let me see if I can update the doc. It appears pointing to old lib.

**Comment by weidongxu-microsoft** [comment]
docs-sdk-java PR merged and check that doc page updated.
