### ISSUE TITLE
[BUG] Create a Service Bus Subscription with a default Rule

### ISSUE THREAD

**Issue by brunomace** [Azure/azure-sdk-for-java#37856]
**Describe the bug**
When creating a new Subscription with a first Rule, the Rule isn't taken into account a the default Rule is created.
The method called is `ServiceBusAdministrationClient. createSubscription(String topicName, String subscriptionName, String ruleName, CreateSubscriptionOptions subscriptionOptions, CreateRuleOptions ruleOptions)`.
It works if I create a new Subscription, then create the Rule, then delete the default Rule. But the Subscription can collect other messages (see this issue: https://github.com/Azure/azure-sdk-for-java/issues/29885).
The HTTP payload seems correct, it contains all the rule informations. So the problem is maybe on the server side.

***Exception or Stack Trace***
No error or exception is raised.

**To Reproduce**
Execute the code snippet.

***Code Snippet***
```
ServiceBusAdministrationClient asbClient = getClientViaConnectionString();
String topicName = "distribution.commun";
String subscriptionName = "test-" + System.currentTimeMillis();
CreateSubscriptionOptions subOpts = new CreateSubscriptionOptions();
String defaultRuleName = "document-recu";
CorrelationRuleFilter ruleFilter = new CorrelationRuleFilter();
ruleFilter.setLabel("1.1.evenement.document.recu");
CreateRuleOptions defaultRuleOpts = new CreateRuleOptions() //
		.setFilter(ruleFilter) //
		.setAction(new EmptyRuleAction());
// Create the Subscription with a default Rule
asbClient.createSubscription(topicName, subscriptionName, defaultRuleName, subOpts, defaultRuleOpts);
// Check
Collection<RuleProperties> rules = asbClient.listRules(topicName, subscriptionName).stream().toList();
if (rules.size() != 1) {
	System.err.println("" + rules);
	System.exit(1);
}
RuleProperties rule = rules.iterator().next();
if (!rule.getName().equals(defaultRuleName)) {
	// Will fail here
	System.err.println("" + rule.getName());
	System.exit(1);
}
```

**Expected behavior**
The default Rule isn't created, the specified Rule is created.

**Setup:**
 - Library/Libraries: com.azure:azure-messaging-servicebus:7.14.6 (the latest version available)
 - Java version: 17

**Information Checklist**
Kindly make sure that you have added all the following information above and checkoff the required fields otherwise we will treat the issuer as an incomplete report
- [X] Bug Description Added
- [X] Repro Steps Added
- [X] Setup information Added

**Comment by brunomace** [comment]
Apparently there is no [unit test](https://github.com/Azure/azure-sdk-for-java/tree/azure-messaging-servicebus_7.14.6/sdk/servicebus/azure-messaging-servicebus/src/test/java/com/azure/messaging/servicebus/administration) for this method.

**Comment by anuchandy** [comment]
Root cause: The generated model used the name "RuleDescription" to serialize the rule instead of "DefaultRuleDescription". This requires some analysis in the code generator.
