### ISSUE TITLE
Support for replacing a policy of a certain type in HTTP pipeline

### ISSUE THREAD

**Issue by srnagar** [Azure/azure-sdk-for-java#37864]
For future investigation:

Should we have a getPolicyName() method here to allow for replacing a policy in a default pipeline? This can be a default method where the names are just uuids.

Default pipeline created by the generator:

Policy Name -> Policy instance

Retry -> RetryPolicy
Authentication -> BearerTokenAuthenticationPolicy
Redirect -> RedirectPolicy
Logging -> HttpLoggingPolicy

Convenience layer/customer can replace one or more policies above without having to recreate the whole pipeline. Here we use the getPolicyName() method to find if it already exists in the default pipeline and should be replaced.

Retry -> RetryPolicy
Authentication -> MyCustomAuthPolicy
Redirect -> MyCustomRedirectPolicy
Logging -> HttpLoggingPolicy

**Comment by JonathanGiles** [comment]
My proposal is to start by not generating any addPolicy APIs, and then consider a more comprehensive API in future releases. For example, one option might be: https://gist.github.com/JonathanGiles/90ebc2be0ac27523d4df9bbbdc7d1d86

If we agree on this, the action item would be to ask @srnagar to not generate addPolicy methods on builders for now.

**Comment by JonathanGiles** [comment]
Closing this in favour of an uber method over in [#39841](https://github.com/Azure/azure-sdk-for-java/issues/39841)
