### ISSUE TITLE
Set VirtualMachine UserData via Compute ResourceManager

### ISSUE THREAD

**Issue by realjenius** [Azure/azure-sdk-for-java#37861]
**Is your feature request related to a problem? Please describe.**
My team uses specialized images and would like to specify the `userData` (not `customData`) on the VirtualMachine when creating the virtual machine, but are unable to as it cannot be specified in the fluent API for `com.azure.resourcemanager.compute.models.VirtualMachine`.

Additionally, while `VirtualMachineInner` has `userData` as a configurable parameter, it does not appear to be copied to the `VirtualMachineUpdateInner` when performing an update, which means this can't be set during an update either.

**Describe the solution you'd like**
It would be nice for the `userData` to be configurable via the Fluent create API as well as via the update API, similar to `.withCustomData(...)` but instead `.withUserData(...)`.

**Describe alternatives you've considered**
Forking the library or using lower level ARM libraries with the client.

**Additional context**
None.

**Information Checklist**
Kindly make sure that you have added all the following information above and checkoff the required fields otherwise we will treat the issuer as an incomplete report
- [x] Description Added
- [x] Expected solution specified

**Comment by XiaofeiCao** [comment]
fixed in 2.34.0
