### ISSUE TITLE
[BUG] Reactor Netty sets default port based on PORT environment variable

### ISSUE THREAD

**Issue by jellyyesir** [Azure/azure-sdk-for-java#37904]
![error](https://github.com/Azure/azure-sdk-for-java/assets/147461106/c105ee75-38ee-43eb-a814-186fbb6b3b8a)

OS window10 ,window server 2016

run bat script

@echo OFF

@SET FILE_NAME=javaprg.war
@SET PORT=8080

@SET PORT=:%PORT%
@SET RESULT_PID=""
@SET START_PATH=%~dp0
@SET FILE_PATH=%START_PATH%%FILE_NAME%

for /f "tokens=5 delims= " %%a IN ('netstat -ano ^| findstr %PORT% ^|  find "LISTEN" ') do set RESULT_PID=%%a

IF %RESULT_PID%=="" (
java -jar -server -Djava.awt.headless=true -Xms128m -Xmx512m -Duser.timezone=GMT+09:00 %FILE_PATH%
) ELSE (
echo %PORT% RUNNING
)

![error2](https://github.com/Azure/azure-sdk-for-java/assets/147461106/f5717230-0e02-49b8-929b-6e1f3a8f50ad)

WINDOW ENV IN BAT SHARE 

![injar](https://github.com/Azure/azure-sdk-for-java/assets/147461106/3766d771-0702-489a-8100-b1f53e43b247)

change bat script PORT -> TEMP_PORT

not error

**Comment by alzimmermsft** [comment]
Hi @jellyyesir, this appears to be [Reactor Netty code](https://github.com/reactor/reactor-netty) which is doing this which we cannot change.
