### ISSUE TITLE
[Question] Spring data cosmos excute so slowly

### ISSUE THREAD

**Issue by winter1215** [Azure/azure-sdk-for-java#37921]
**Query/Question**
when I what to excute some query statement,I found it is so slow.but this is just simple statement like `findById()`,and the amount of data in the database is also small.

**Setup (please complete the following information if applicable):**
- SpringBoot version: 2.7.6
- SDK version: 4.11.0
  <groupId>com.azure.spring</groupId>
  <artifactId>spring-cloud-azure-starter-data-cosmos</artifactId>
  <version>4.11.0</version>
 
**code example**
```java
        long t1 = System.currentTimeMillis();
        School school = cosmosTemplate.findById("xxx", School.class);
        long t2 = System.currentTimeMillis();
        System.out.println(t2 - t1);

// out
951ms
```
more infomation about query metrics, it says : "totalQueryExecutionTime":"PT0.00101S"
**plese help me check out it, why this SDK takes so much time,while totalQueryExecutionTime is small**

**Comment by winter1215** [comment]
@archerzz could you help me have a look at it? I want to know if it's normal.

**Comment by XiaofeiCao** [comment]
@winter1215 Total roundtrip time is not determined solely by the data size that you are querying. It may depend on you local network latency or even local code warmup time.

I'll route this to `azure-spring-data-cosmos` team. @FabianMeiswinkel Could you help take a look?

**Comment by winter1215** [comment]
@XiaofeiCao Thanks for your time. Actually, I called the same api interface, and the first time it takes me about 3 times as long as other time after it. But other api interfaces or calls after a period of time often become very slow again.

**Comment by winter1215** [comment]
Truly grateful for your help!
