### ISSUE TITLE
Add support for configuring custom-endpoint-address values in application.properties for service bus

### ISSUE THREAD

**Issue by mohyeid** [Azure/azure-sdk-for-java#37930]
AzureServiceBusProperties today does not extend provided values for custom-endpoint-address values. 

**Describe the solution you'd like**
I need to be able to pass custom-endpoint-address values in general, for producer, consumer and processor. It need to be respected across all the layers. It used to be supported in event bus, but not in service bus. This is for spring cloud stream auto configurations. 

**Describe alternatives you've considered**
I was able to provide a customizer that worked with producer & consumer, but yet not finding a way to do so for the processor. It will be great if all of this can be done via configurations. 

**Additional context**
[Add any other context or screenshots about the feature request here.](https://github.com/Azure/azure-sdk-for-java/blob/2b020724483dbb745531c113d78c4d900fcb52e4/sdk/spring/spring-cloud-azure-autoconfigure/src/main/java/com/azure/spring/cloud/autoconfigure/implementation/servicebus/properties/AzureServiceBusProperties.java#L26) 

**Information Checklist**
Kindly make sure that you have added all the following information above and checkoff the required fields otherwise we will treat the issuer as an incomplete report
- [x ] Description Added
- [ x] Expected solution specified

**Comment by Netyyyy** [comment]
@mohyeid , thanks for reporting.
We have received your submission and will take it into consideration. We appreciate your input and will review this matter as soon as possible.
Please feel free to provide any additional information or context that you think may be helpful. We'll keep you updated on the progress of our review.
Thank you for your contribution to improving our project.

**Comment by Netyyyy** [comment]
@mohyeid thanks for reporting.
We have received your submission and will take it into consideration. We appreciate your input and will review this matter as soon as possible.
Please feel free to provide any additional information or context that you think may be helpful. We'll keep you updated on the progress of our review.
Thank you for your contribution to improving our project.

**Comment by moarychan** [comment]
@mohyeid thanks for your reporting, PR is drafted, will ship out in the next release this month!

**Comment by moarychan** [comment]
Now it's available.
