### ISSUE TITLE
[BUG] NativeIoException from BlobContainerClient

### ISSUE THREAD

**Issue by razum90** [Azure/azure-sdk-for-java#37964]
**Describe the bug**
After dependency upgrades we are observing `NativeIoException` happening.

The following upgrades were done:

- Bump com.azure:azure-sdk-bom from 1.2.17 to 1.2.18
- Bump com.azure.spring:spring-cloud-azure-dependencies from 5.5.0 to 5.7.0

We are using `BlobContainerClient` from your SDK.

```
<dependency>
  <groupId>com.azure</groupId>
  <artifactId>azure-storage-blob</artifactId>
</dependency>
```

Building it up like so:

```
this.blobContainerClient = new BlobServiceClientBuilder()
                .endpoint(String.format("https://%s.blob.core.windows.net/", azureStorageAccountName))
                .credential(new DefaultAzureCredentialBuilder().build())
                .buildClient()
                .getBlobContainerClient(CONTAINER_NAME);
```

***Exception or Stack Trace***
```
io.netty.channel.unix.Errors$NativeIoException: recvAddress(..) failed: Connection reset by peer
```

```
[dcc5e686-5, L:/xx.xx.xx.xxx:52806 - R:psgwtestsa.blob.core.windows.net/xx.xxx.xxx.x:443] The connection observed an error, the request cannot be retried as the headers/body were sent
```

**Expected behavior**
These error logs not to happen. They started happening after the dependency upgrades mentioned above.

**Setup (please complete the following information):**
- Spring Boot 3.1.4
- azure-storage-blob 12.24.1
- Java 17
- Docker image: eclipse-temurin:17-jdk-alpine

**Additional context**
This error did not happen before the upgrade.

**Information Checklist**
Kindly make sure that you have added all the following information above and checkoff the required fields otherwise we will treat the issuer as an incomplete report
- [x] Bug Description Added
- [x] Repro Steps Added
- [x] Setup information Added

**Comment by alzimmermsft** [comment]
Thanks for filing this issue @razum90.

Does the `NativeIOException` happen consistently or is this something that happens randomly?

**Comment by razum90** [comment]
@alzimmermsft It seems to be quite random. The usage of `BlobContainerClient` sometimes works without any exception, while in other cases we do get the exception.

One example case I observed, we are getting the exception thrown, then ~4 seconds later the call using `BlobContainerClient` succeeds.

**Comment by razum90** [comment]
@alzimmermsft, hi and sorry for the late response. All right, i was just thinking if the upgrade of your SDK was related since we have not seen this error before. But it could of course be related to something else.

If you have investigated and concluded that it is not related I will trust you.

Thanks for looking into it, as you say after retrying it works. You can close it from my perspective.

BR
