### ISSUE TITLE
[BUG] Spring Data Cosmos Query doesn't apply Sort parameter correctly when using non-space-character whitespace

### ISSUE THREAD

**Issue by petercooperjr-spls** [Azure/azure-sdk-for-java#37966]
**Describe the bug**
When creating a Spring Data repository to use Cosmos, if creating a query with the `@Query` parameter but using newlines between statements instead of just spaces, which has a Sort parameter to allow for the caller to dynamically set the sort order, the constructed query is incorrect causing a Cosmos error.

***Exception or Stack Trace***
```
2023-12-07T11:38:30.564-05:00 DEBUG 14364 --- [project] [ctor-http-nio-8] c.a.c.implementation.SqlQuerySpecLogger  : select *
from collection
where collection.field = @val
 ORDER BY collection
where.otherfield ASC

com.azure.spring.data.cosmos.exception.CosmosAccessException: Failed to find items
	at com.azure.spring.data.cosmos.exception.CosmosExceptionUtils.exceptionHandler(CosmosExceptionUtils.java:38) ~[azure-spring-data-cosmos-5.7.0.jar:5.7.0]
	Suppressed: [CIRCULAR REFERENCE: com.azure.cosmos.CosmosException: {"innerErrorMessage":"{\"code\":\"BadRequest\",\"message\":\"One of the input values is invalid.\\r\\nActivityId: 1b6f9e4c-706c-45b2-8b77-f59ae22dce1b, Windows/10.0.17763 cosmos-netstandard-sdk/3.18.0\"}, StatusCode: BadRequest","cosmosDiagnostics":{"userAgent":"azsdk-java-cosmos/4.52.0 Windows11/10.0 JRE/17.0.9 az-sd-cos/@project.version@az-sp-cos/5.7.0",
```

**To Reproduce**

1. Attempt to call the query with a sort specified

***Code Snippet***
Example of code that doesn't work:
```
@Query("""
select *
from collection
where collection.field = @val
""")
Flux<Entity> findByField(final String val, final Sort sort);
```

But rearranging so that the "where" is on the same line as the "from" *does* work:
```
@Query("""
select *
from collection where
collection.field = @val
""")
Flux<Entity> findByField(final String val, final Sort sort);
```

**Expected behavior**
Any sort of whitespace should be treated the same, so it shouldn't break if using a newline after the collection name instead of a space.

**Setup (please complete the following information):**
 - OS: Windows 11 Enterprise 22H2 build 22621.2792
 - IDE: IntelliJ IDEA 2022.1.4 Ultimate
 - Library/Libraries: com.azure.spring:spring-cloud-azure-starter-data-cosmos:5.7.0
 - Java version: 17.0.9
 - Frameworks: Spring Boot 3.2.0

**Additional context**
I think the bug is here:
https://github.com/Azure/azure-sdk-for-java/blob/main/sdk/spring/azure-spring-data-cosmos/src/main/java/com/azure/spring/data/cosmos/core/generator/NativeQueryGenerator.java#L51
Where it uses a regular expression accepting any sort of whitespace after the collection name, but then does an `indexOf(" ")` which assumes that the whitespace after the collection name is an actual space character.

**Information Checklist**
Kindly make sure that you have added all the following information above and checkoff the required fields otherwise we will treat the issuer as an incomplete report
- [X] Bug Description Added
- [X] Repro Steps Added
- [X] Setup information Added

**Comment by joshfree** [comment]
@kushagraThapar could you please help route this?

**Comment by kushagraThapar** [comment]
@trande4884 can you please take a look at this, thanks!

**Comment by trande4884** [comment]
@petercooperjr-spls I am able to reproduce your issue, and I actually have problems with both of the examples you have above with new lines. I will work on a solution for this bug shortly!

**Comment by petercooperjr-spls** [comment]
It's possible I did something slightly different in my attempt to anonymize my actual collection and field names. In any event, I do have a workaround of just having more of the query on the same line, so this isn't particularly urgent. It's just one of those annoying things that should probably get fixed.

Thank you very much!
