### ISSUE TITLE
java ref docs build failure

### ISSUE THREAD

**Issue by faynef** [Azure/azure-sdk-for-java#37987]
Error:
 

> error: package org.apache.http.ssl does not exist  public interface TrustStrategy extends org.apache.http.ssl.TrustStrategy {                                                            ^  D:\a\_work\1\s\target_repo\src\docs-ref-autogen\azure-security-keyvault-jca\src\main\java\azure\security\keyvault\jca\implementation\shaded\org\apache\http\impl\client\HttpAuthenticator.java:42: error: package org.apache.http.impl.auth does not exist  public class HttpAuthenticator extends org.apache.http.impl.auth.HttpAuthenticator {   
            
For more details check here:

- https://apidrop.visualstudio.com/Content%20CI/_build/results?buildId=401879&view=results                                   

@danieljurek for notification.

**Comment by joshfree** [comment]
@vcolin7 can you work with @danieljurek as appropriate here
