### ISSUE TITLE
[BUG] ReactiveCosmosRepository.saveAll() no longer save item

### ISSUE THREAD

**Issue by yatw** [Azure/azure-sdk-for-java#38006]
**Describe the bug**
I am using the saveAll() method from ReactiveCosmosRepository to save a list of data into Cosmos DB
This work fine in azure-spring-data-cosmos-5.5.0. Recently I upgrade to azure-spring-data-cosmos-5.7.0. Now saveAll() no longer generate the id to the item being saved and I checked in DB nothing is saved.

Please help me understand what changed in the version to cause the behavior change. Thank you.

***Exception or Stack Trace***
no exception

***Code Snippet***
```
buildingScenarioRepo.saveAll(buildingScenarios).blockLast();
```
buildingScenarios is the list of noSQL document I am saving. 
buildingScenarioRepo is an interface extending ReactiveCosmosRepository 

**Screenshots**
using debugger to check the list of buildingScenarios right after the saveAll() operation, id is generated
<img width="1123" alt="withId" src="https://github.com/Azure/azure-sdk-for-java/assets/19565177/5cddae6d-4290-4f84-843e-ad67637731d0">

In azure-spring-data-cosmos-5.7.0, id is missing
<img width="1055" alt="noid" src="https://github.com/Azure/azure-sdk-for-java/assets/19565177/2e59aa0e-27f4-4479-98b4-9f12b22c6f51">

**To Reproduce**
1. Call saveAll()

**Setup (please complete the following information):**
 - OS: macOS
 - IDE: IntelliJ
 - Library/Libraries: 
 - Java version: 17
 - App Server/Environment: - 
     - azure-spring-data-cosmos:5.7.0 from azure.spring:spring-cloud-azure-starter-data-cosmos:5.7.0
     - spring-data-jpa:3.1.5
 - Frameworks: Spring Boot

**Additional context**
I am aware saveAll() is a method in ReactiveCrudRepository from spring-data-jpa:3.1.5

**Information Checklist**
Kindly make sure that you have added all the following information above and checkoff the required fields otherwise we will treat the issuer as an incomplete report
- [x] Bug Description Added
- [x] Repro Steps Added
- [x] Setup information Added

**Comment by petercooperjr-spls** [comment]
I think I may be running into this too; might the problem be that the `@GeneratedValue` on the entity isn't being set and it's trying to bulk-load to the database with a null id?

I do see this error in the log:
`2023-12-13T03:18:38.747Z ERROR 1 --- [ded-elastic-283] c.a.c.implementation.batch.BulkExecutor  : HandleTransactionalBatchOperationResult - Fail, PKRange 10, Response Status Code 400, Operation Status Code 400, ItemOperation[Type: UPSERT, PK: ["3471/2023-12-13"], id: null], Context: BulkExecutor-4382[n/a] Thread[Name: bulk-executor-bounded-elastic-283,Group: main, isDaemon: true, Id: 5264]`

I'm trying a downgrade to spring-cloud-azure-starter-data-cosmos 5.6.0 for now.

**Comment by Netyyyy** [comment]
@kushagraThapar , please help take a look

**Comment by yatw** [comment]
Hi any update? I want to double check if this is a bug on Azure side or Spring side.

**Comment by kushagraThapar** [comment]
@yatw - this has been fixed - and should be released by the end of this month.

**Comment by kushagraThapar** [comment]
This is the PR that fixes this issue - https://github.com/Azure/azure-sdk-for-java/pull/38356

**Comment by kostsamko** [comment]
Hello @kushagraThapar Thank you for the fix! When this planned to be released and in which spring version?

**Comment by kushagraThapar** [comment]
@kostsamko - we are working on the release and it should be out soon. You can find the bug fixed here - https://github.com/Azure/azure-sdk-for-java/blob/main/sdk/spring/azure-spring-data-cosmos/CHANGELOG.md#3420-beta1-unreleased
