### ISSUE TITLE
JavaDoc and Readme for Queue Clients

### ISSUE THREAD

**Issue by alzimmermsft** [Azure/azure-sdk-for-java#3800]
Add JavaDocs and readme for the queue clients

**Comment by sima-zhu** [comment]
Breakdowns:

Queue:
Javadoc
Readme
Message:
Javadoc
Readme
MessageId:
Javadoc
Readme

**Comment by sima-zhu** [comment]
Repo: https://github.com/Azure/azure-sdk-for-java/tree/storage-proto
Resource: https://docs.microsoft.com/en-us/rest/api/storageservices/queue-service-rest-api
Reference: AzConfig, Keyvault.

**Comment by sima-zhu** [comment]
Generic Readme:
Links:
[source_code]: 
[package]:
[api_documentation]:
[AzStorage_docs]: 
[jdk]: https://docs.microsoft.com/en-us/java/azure/java-supported-jdk-runtime?view=azure-java-stable
[maven]: https://maven.apache.org/
[azure_subscription]: https://azure.microsoft.com/en-us/free/
[app_config_store]: ? (Inside of app config readme, apply to storage?)
[rest_api]: https://github.com/Azure/AppConfiguration#rest-api-reference
[storage_rest]:  (Inside of app config readme, apply to storage?)

**Comment by sima-zhu** [comment]
https://gist.github.com/sima-zhu/c0c43d2441e9c71eaf8095098aa29bcf

**Comment by sima-zhu** [comment]
Readme for queue service and queue.
https://github.com/Azure/azure-sdk-for-java/pull/3848
