### ISSUE TITLE
azure-core-http-vertx uses Netty scheduler which causes GraalVM native image builds to fail

### ISSUE THREAD

**Issue by The-Funk** [Azure/azure-sdk-for-java#38012]
https://github.com/Azure/azure-sdk-for-java/blob/23ee5152b1bafe998492855eb0ecd24db3268ad4/sdk/core/azure-core-http-vertx/src/main/java/com/azure/core/http/vertx/VertxAsyncHttpClient.java#L34C29-L34C38

Here's the exact line.

This class should ideally use the vert.x timer instead of the Netty scheduler, in order to solve this build time issue with GraalVM.

**Comment by alzimmermsft** [comment]
Thanks for filing this issue @The-Funk.

We'll get this fixed to provide better support for GraalVM native images. Is there any documentation that recommends the Vert.x timer usage that could be included in the fix for future reference?

**Comment by The-Funk** [comment]
@alzimmermsft I don't necessarily have docs for it but I'm coming from a Quarkus development background, and I can tell you from experience that Netty doesn't play nicely with GraalVM. 

[This is a chat I was having with one of the Quarkus developers over on their Zulip chat.](https://quarkusio.zulipchat.com/#narrow/stream/187030-users/topic/Native.20Image.20Compilation.20Error.20io.2Enetty.2Econcurrent.2E.2E.2E.2E)

It should be noted that prior to replacing the Netty Http implementation with the Vert.x Http implementation there were many more errors in the compilation process (too many to count,, I spent a few days trying)

[Here is my minimal reproducer using Quarkus](https://github.com/The-Funk/broken-native-image-reproducer)

If you attempt a native image build with that project above it will fail with the error mentioned in the Zulip chat.

The error implicates the Netty scheduler.

**Comment by The-Funk** [comment]
Thank you @alzimmermsft !
