### ISSUE TITLE
Storage Auto REST Issues

### ISSUE THREAD

**Issue by alzimmermsft** [Azure/azure-sdk-for-java#3805]
Service interfaces are missing the Service annotation

ServiceClient.createSerializerAdapter no longer exists and is being called

Add queueName and messageId name to API interfaces that have parameterized relative paths

**Comment by sima-zhu** [comment]
DirectoryImp:
Service interfaces are missing the Service annotation
ServiceClient.createSerializerAdapter no longer exists and is being called
Add shareName and directoryName to API interfaces that have parameterized relative paths

FileImpl:
Service interfaces are missing the Service annotation
ServiceClient.createSerializerAdapter no longer exists and is being called
Add shareName, directoryName and fileName to API interfaces that have parameterized relative paths
