### ISSUE TITLE
Incorrect parsing of json to AnalyzeResult Class in Forms Recognizer

### ISSUE THREAD

**Issue by ajaymanagaon** [Azure/azure-sdk-for-java#38086]
The json data output from FormsRecognizer and the AnalyzeResult do not match. Sometimes its incorrect parsing. Sometimes an array is missing. 

***Exception or Stack Trace***
No Exception Produced

**To Reproduce**
Take a little complex form and compare the json output of the FormsRecognizer Studio along with AnalyzeResult result. They don't seem to match. Tried with 2-3 different forms.

***Code Snippet***
AnalyzeDocumentOperation operation = client.AnalyzeDocument(WaitUntil.Completed, modelId, fileStream);
AnalyzeResult result = operation.Value;

**Comment by joshfree** [comment]
@samvaity this old issue seems to have fallen through the cracks; can you please verify and close

**Comment by samvaity** [comment]
[ajaymanagaon](https://github.com/ajaymanagaon) Thank you for reporting. 
Are the forms being supplied of some specific type?

I just tried the compared the analyze results for [this form](https://github.com/Azure/azure-sdk-for-java/blob/main/sdk/formrecognizer/azure-ai-formrecognizer/src/test/resources/sample_files/Test/contoso_allInOne_multipage_receipt.pdf) and the results from Studio and SDK are the same.

Please confirm if there is a specific type I need to try to reproduce the error.
