### ISSUE TITLE
When I use “openAIAsyncClient.getChatCompletionsStream”  to get the stream, how do I cancel this chatCompletionsOptions?

### ISSUE THREAD

**Issue by Conanxy** [Azure/azure-sdk-for-java#38087]
**Query/Question**
When I use “openAIAsyncClient.getChatCompletionsStream”  to get the stream, how do I cancel this chatCompletionsOptions?
If I cancel this chatCompletionsOptions successfully, will the token also stop at the same time?

**Setup (please complete the following information if applicable):**
 - IDE:  IntelliJ
 - Library/Libraries: azure-ai-openai.version 1.0.0-beta.5

```[tasklist]
### Tasks
```

**Comment by joshfree** [comment]
@mssfang PTAL

**Comment by mssfang** [comment]
Hi @Conanxy. You can cancel the async chat completion streaming by calling [Disposable](https://github.com/reactor/reactor-core/blob/main/reactor-core/src/main/java/reactor/core/Disposable.java#L36)'s method, `dispose()` which will cancel the task or resource we created at `openAIAsyncClient.getChatCompletionsStream`.  If the cancellation executed successfully, the SSE connection will be closed, and no further data will be proceeded. It will be up to service side to define if the token generation is stop at the same time. 

I did an experience by using fiddler to monitor the payload.

We can confirm that by calling disposable.dispose() will successfully cancel the connection. The connection established and then closed successfully.
<img width="155" alt="image" src="https://github.com/Azure/azure-sdk-for-java/assets/45607042/7a4b5b45-22a9-4458-bdcd-f645b990c945">

FWIW, up to date,
max token is 4096 for model gpt-3.5-turbo-1106
```
    "message": "max_tokens is too large: 5000. This model supports at most **4096** completion tokens, whereas you provided 5000.",
```
max token is 8192 for model gpt-4,
```
    "message": "This model's maximum context length is 8192 tokens. However, you requested 9039 tokens (39 in the messages, 9000 in the completion). Please reduce the length of the messages or completion.",
```

What I observed it is either successfully get the full response or connection closed/cancelled successfully.
Hope it helps.
