### ISSUE TITLE
azure gpt stream is very slow

### ISSUE THREAD

**Issue by ZuoYouLai** [Azure/azure-sdk-for-java#38092]
The response of azure gpt stream is very slow and cannot be as smooth as opeanai's chagpt.
I have applied to pass the filtering of sensitive words, but the effect is still very poor;

specific parameters:
topP = 0.95
temperature = 0.75
stream = true

**Comment by joshfree** [comment]
@mssfang can you please follow up with @ZuoYouLai for more details?  @ZuoYouLai if there are more specific details you can share that would be helpful.

**Comment by mssfang** [comment]
@ZuoYouLai Thank you for contacting us. Can you provide a sample that I can reproduce it?
