### ISSUE TITLE
Re-evaluate options classes and consider redefining client builder APIs

### ISSUE THREAD

**Issue by vcolin7** [Azure/azure-sdk-for-java#38095]
Currently, we have some configuration classes that are tied to specific policies like `HttpLogOptions` for `HttpLoggingPolicy` and `RetryOptions` + `RetryStrategy` for `RetryPolicy`.  We should re-evaluate how much of those APIs should be kept or can be moved to other places like builders.

More context [here](https://apiview.dev/Assemblies/Review/9d608137eb4c4695b0792223a484b7d7#9eb2396e7d33469a83e7701b4faf1134) and [here](https://apiview.dev/Assemblies/Review/9d608137eb4c4695b0792223a484b7d7#aab863de4436426882b863384b20dc1b).
```[tasklist]
### Tasks
- [x] Simplify Retry Policy
```

**Comment by samvaity** [comment]
We want to continue using the options approach in order to preserve the fluid nature of builder apis and modify any existing policy.
Whereas use `addPolicy`  API to a completely new policy

**Comment by samvaity** [comment]
We want to continue using the options approach in order to preserve the fluid nature of builder api. And later on, possibly have an `addPolicy` api completely add a new policy whereas `.policyoptions` is an API to modify the policy.
