### ISSUE TITLE
I use the Azure OpenAI GPT-3.5-turbo service, and when using functions or tools, it shows 'Unrecognized request argument supplied: XXX.

### ISSUE THREAD

**Issue by Conanxy** [Azure/azure-sdk-for-java#38115]
**Query/Question**
"I use the Azure OpenAI GPT-3.5-turbo service, and when calling functions and tools, it shows 'Unrecognized request argument supplied: XXX.'"

pom：
```xml
<dependency>
            <groupId>com.azure</groupId>
            <artifactId>azure-ai-openai</artifactId>
            <version>1.0.0-beta.6</version>
        </dependency>
```

mycode:
```java
OpenAIAsyncClient client = new OpenAIClientBuilder()
                .endpoint(endpoint)
                .credential(new AzureKeyCredential(azureOpenaiKey))
                .serviceVersion(OpenAIServiceVersion.V2023_12_01_PREVIEW)
                .buildAsyncClient();

        List<ChatRequestMessage> chatMessages = Arrays.asList(
                new ChatRequestSystemMessage("You are a helpful assistant."),
                new ChatRequestUserMessage("What sort of clothing should I wear today in Berlin?")
        );
        ChatCompletionsToolDefinition toolDefinition = new ChatCompletionsFunctionToolDefinition(
                getFutureTemperatureFunctionDefinition());

        ChatCompletionsOptions chatCompletionsOptions = new ChatCompletionsOptions(chatMessages);
        chatCompletionsOptions.setTools(Arrays.asList(toolDefinition));
```

error:
```json
There was an error getting chat completions.com.azure.core.exception.ResourceNotFoundException: Status code 404, "{
  "error": {
    "message": "Unrecognized request argument supplied: tools",
    "type": "invalid_request_error",
    "param": null,
    "code": null
  }
}
"
```

**Setup (please complete the following information if applicable):**
 - IDE: [ IntelliJ]

**Comment by joshfree** [comment]
@mssfang can you follow up with @Conanxy please

**Comment by mssfang** [comment]
@Conanxy Are you using model version are you using, `gpt-3.5-turbo-1106`?

**Comment by tofuyang** [comment]
> @Conanxy Are you using model version, `gpt-3.5-turbo-1106`?

yes，

**Comment by tofuyang** [comment]
@mssfang Yes, I'm using `gpt-3.5-turbo-1106`

**Comment by mssfang** [comment]
@tofuyang @Conanxy 
I tried both Azure and Non-Azure OpenAI credential but can't reproduce the error and no failure.
I use this [sample](https://github.com/Azure/azure-sdk-for-java/blob/main/sdk/openai/azure-ai-openai/src/samples/java/com/azure/ai/openai/usage/GetChatCompletionsToolCallAsyncSample.java#L52).

Azure resource region: Sweden Central (which has model version 1106 available)

  - Model name: gpt-35-turbo; model version: 1106 or 0613 (older version also works)
  - Model name: gpt-4; model version: 1106-preview also works.
  
Can you give more information or try to work with above samples.

**Comment by feffe81** [comment]
I also have the same issue today. Can you reopen the issue?

**Comment by feffe81** [comment]
I have the same issue today using Semantic Kernel with C#

**Comment by mssfang** [comment]
> I have the same issue today using Semantic Kernel with C#

Hi @feffe81 Thanks for providing one more data point.
It could relate to the [deprecation of `functions` and `functionCall` ](https://learn.microsoft.com/en-au/azure/ai-services/openai/how-to/function-calling?tabs=python#using-function-in-the-chat-completions-api-deprecated) and [doc ](https://platform.openai.com/docs/api-reference/chat/create#chat-create-function_call) in OpenAI
And Semantic Kernel doesn't upgrade to use the [latest `tools` API](https://platform.openai.com/docs/api-reference/chat/create#chat-create-tools)

FWIW, I reran the [sample](https://github.com/Azure/azure-sdk-for-java/blob/main/sdk/openai/azure-ai-openai/src/samples/java/com/azure/ai/openai/usage/GetChatCompletionsToolCallAsyncSample.java#L52) in Java, and it works fine.
