### ISSUE TITLE
[QUERY] ERROR: Channel read timed out after 60000 milliseconds.

### ISSUE THREAD

**Issue by Conanxy** [Azure/azure-sdk-for-java#38133]
**Query/Question**
i am using the Azure Openai Api in java, `1.0.0-beta.5`
```java
new OpenAIClientBuilder()
                        .httpClient(getHttpClient("openai-4-turbo-connection-pool"))
                        .endpoint(END_POINT_4_TURBO_1106)
                        .credential(new AzureKeyCredential(API_KEY_4_TURBO_1106))
                        .buildClient()

private HttpClient getHttpClient(String connectionPoolName) {
        ConnectionProvider connectionProvider = ConnectionProvider.builder(connectionPoolName)
                .maxConnections(500)
                .pendingAcquireMaxCount(-1)
                .maxIdleTime(Duration.ofMinutes(30))
                .build();

        return new NettyAsyncHttpClientBuilder()
                .connectTimeout(Duration.ofMinutes(2))
                .responseTimeout(Duration.ofMinutes(3))
                .connectionProvider(connectionProvider)
                .build();
    }

ChatCompletionsOptions chatCompletionsOptions = new ChatCompletionsOptions(chatMessages)
                    .setStream(true)
                    .setMaxTokens(4000)
                    .setFunctions(funtions)
                    .setFunctionCall(FunctionCallConfig.AUTO);

 openAIAsyncClient.getChatCompletionsStream(MODAL_4_TURBO, chatCompletionsOptions)
                    .skip(1)
                    .doFinally(signalType -> latch.countDown())
                    .subscribe(webSocketCustomChatSubscriber);
```

I found that every time I call the api related to chatCompletions, if the context of charMessage is very long, it will lead to the this situation. `java.util.concurrent.TimeoutException: Channel read timed out after 60000 milliseconds.`

And I don’t know why there is a 60s timeout, because I set `connectTimeout(Duration.ofMinutes(2)) and` `responseTimeout(Duration.ofMinutes(3)) when` I created the HttpClient object.

**Comment by alzimmermsft** [comment]
Thanks for asking this question @Conanxy.

One `NettyAsyncHttpClientBuilder` there is another timeout `readTimeout` which controls how much time can elapse once a response has begun to be read (after headers are received) before the response reading is considered timed out.

This goes over the general HTTP time outs in more detail: https://github.com/Azure/azure-sdk-for-java/blob/main/sdk/core/azure-core/README.md#http-timeouts
