### ISSUE TITLE
Centralise version management

### ISSUE THREAD

**Issue by JonathanGiles** [Azure/azure-sdk-for-java#3815]
Because of the hierarchy of parent poms in Java, it will become a frequent requirement to upgrade all dependencies of a parent to a newer version. Similarly, our readme documentation, scattered among the monorepo, will frequently need updating to refer to the latest version of a particular library. A few months back I introduced tooling to the engineering systems team that exists to centralise the versioning into a single 'versions.txt' file, and that upon every run will update all pom.xml files, as well as all readme.md files, to ensure the correct version is represented. I don't believe an issue was filed at the time, so I am doing it now so that this requirement can be tracked.

We are getting to the point where such tooling will be extremely useful.

// cc @kurtzeborn @weshaggard

**Comment by mitchdenny** [comment]
Touching on this again. @weshaggard and I where discussing this and I think that if we are going to go down this route we should eliminate the version properties for dependencies in the parent POMs and pull them into the child modules (assuming we use the tooling which streamlines updating versions).

The benefit of this is that the parent POM would become largely static from a versioning perspective.

**Comment by kurtzeborn** [comment]
Once we address this issue, #4003 may become obsolete and should be closed.
