### ISSUE TITLE
[QUERY] SDK raises RequestRateTooLargeException but there is no HTTP 429 from CosmosDB insight

### ISSUE THREAD

**Issue by stevenylai** [Azure/azure-sdk-for-java#38153]
**Query/Question**
A clear and concise ask/query.

I was asked by my teammates about a recent CosmosDB throttling error in our preprod environment but as from the troubleshooting link http://aka.ms/cosmosdb-error-429, we couldn't find any 429 status code to start with. The screen (with DB account name partially masked):
![cosmos-app-insight](https://github.com/Azure/azure-sdk-for-java/assets/2912161/c33e9960-0a4f-49e1-a68d-993063a6f63b)

![cosmos-log-analytics](https://github.com/Azure/azure-sdk-for-java/assets/2912161/10492bab-62d2-40a6-87f9-985e654a0fe8)

We haven't updated sdk for the recent couple of months but from the log, [the class](https://github.com/Azure/azure-sdk-for-java/blob/main/sdk/cosmos/azure-cosmos/src/main/java/com/azure/cosmos/implementation/throughputControl/ThroughputRequestThrottler.java#L121-L123) where the error is thrown is also there for some time. We do have local throughput control of 5k RU enabled with code roughly as follows:
```java
            var control = new ThroughputControlGroupConfigBuilder()
                    .groupName("BatchCalculators")
                    .targetThroughput(5000)
                    .defaultControlGroup(true)
                    .build();
            container.enableLocalThroughputControlGroup(control);
```

We also have some very simple rate limiting using fixed window so that if a particular batch update is using too much request, the client will wait for a bit before issuing the next batch.

I also noticed that our code for updating docs are as follows (inside `processOneRequest` function, it calls `CosmosAsyncContainer.executeBulkOperations()` and reduce the results into one single tuple of `totalRequestUsed` and `all operations are successful`):
```java
            batch -> processOneRequest(batch)
                        .onErrorResume(e -> {
                            log.error("[CosmosDB] Error during processing update queue", e);
                            return Mono.just(false);
                        })
```
But when `RequestRateTooLargeException` was thrown, I didn't seem to find the above error log in our AKS.

I'd like to check:
1. Confirm it is indeed possible for the sdk to throw `RequestRateTooLargeException` even when there is no 429 from the server side (I thought the whole point for local throughput control is to delay some requests to avoid getting throttled by server and not to throw exceptions. If so, perhaps then the doc should be updated?)
2. If it is possible to use the above `onErrorResume` to retry the operations with backoff according to `x-ms-retry-after-ms` given that our error log inside `onErrorResume` didn't appear?

Here is the log analytics from AKS (also with DB account name partially masked): [aks-log-analytics.csv](https://github.com/Azure/azure-sdk-for-java/files/13748797/aks-log-analytics.csv)

***Why is this not a Bug or a feature Request?***
A clear explanation of why is this not a bug or a feature request?

I am not sure if throwing `RequestRateTooLargeException` even when there is no 429 from the server side is intended behavior. Also there is a question about how to implement retrial logic.

**Setup (please complete the following information if applicable):**
 - OS: Docker / Linux
 - IDE: IntelliJ
 - Library/Libraries: azure-sdk-bom:1.2.12 
 
 **Information Checklist**
 Kindly make sure that you have added all the following information above and checkoff the required fields otherwise we will treat the issuer as an incomplete report
- [ x ] Query Added
- [ x ] Setup information Added

**Comment by stevenylai** [comment]
@TheovanKraay Thanks. It's clear to me now.

I was thinking perhaps it would be nice to update a bit on: http://aka.ms/cosmosdb-error-429 which pops up whenever there is a `RequestTooLargeException`. The link seems to talk about how to conduct investigation when there are server side HTTP 429 errors. Just add one sentence / side note would be sufficient to mention what you said such that `RequestTooLargeException` could also arise from SDK itself if throughput control is in place and the threshold is set to be lower than what's provisioned.

**Comment by TheovanKraay** [comment]
> @TheovanKraay Thanks. It's clear to me now.
> 
> I was thinking perhaps it would be nice to update a bit on: http://aka.ms/cosmosdb-error-429 which pops up whenever there is a `RequestTooLargeException`. The link seems to talk about how to conduct investigation when there are server side HTTP 429 errors. Just add one sentence / side note would be sufficient to mention what you said such that `RequestTooLargeException` could also arise from SDK itself if throughput control is in place and the threshold is set to be lower than what's provisioned.

That's good feedback, thank you. We'll incorporate into docs.
