### ISSUE TITLE
[BUG] [`azure-storage-blob`] `NullPointerException` when calling any methods of `BlobItem` if it's a "prefix" blob item

### ISSUE THREAD

**Issue by wangmingliang-ms** [Azure/azure-sdk-for-java#38168]
**Describe the bug**
`NullPointerException` when calling any methods of `BlobItem` if it's a "prefix" blob item

***Exception or Stack Trace***
Add the exception log and stack trace if available

```
java.lang.NullPointerException: Cannot invoke "com.azure.storage.blob.implementation.models.BlobItemPropertiesInternal.getCreationTime()" because "this.internalProperties" is null
        at com.azure.storage.blob.models.BlobItemProperties.getCreationTime(BlobItemProperties.java:61)
```

**To Reproduce**
get a `BlobItem` instance of a "prefix" blob item, then call any of its methods, e.g. `getCreationTime()`, `getProperties()`.
 
***Code Snippet***
Add the code snippet that causes the issue.
```java
BlobItem item = ...
System.out.println(item.getCreationTime())
```

**Expected behavior**
No exception or remove this method for "prefix" BlobItem.

**Screenshots**

**Setup (please complete the following information):**
 - IDE: [e.g. IntelliJ]
 - Library/Libraries: [e.g. com.azure:azure-core:1.16.0 (groupId:artifactId:version)]
 - Java version: [e.g. 8] 
 - App Server/Environment: [e.g. Tomcat, WildFly, Azure Function, Apache Spark, Databricks, IDE plugin or anything special]
 - Frameworks: [e.g. Spring Boot, Micronaut, Quarkus, etc] 

If you suspect a dependency version mismatch (e.g. you see `NoClassDefFoundError`, `NoSuchMethodError` or similar), please check out [Troubleshoot dependency version conflict article](https://aka.ms/azsdk/java/dependency/troubleshoot) first. If it doesn't provide solution for the problem, please provide:
- verbose dependency tree (`mvn dependency:tree -Dverbose`)
- exception message, full stack trace, and any available logs

**Additional context**

**Information Checklist**
Kindly make sure that you have added all the following information above and checkoff the required fields otherwise we will treat the issuer as an incomplete report
- [x] Bug Description Added
- [x] Repro Steps Added
- [x] Setup information Added

```[tasklist]
### Tasks
```

**Comment by ibrahimrabab** [comment]
Hi @wangmingliang-ms 
An easy workaround for this is to check if the BlobItem is a prefix (by using BlobItem.isPrefix()), and if not, then you can continue making the calls to inspect getProperties(), getCreationTime(), etc.

For example:

``BlobItem item = ...``

``if (!item.isPrefix()) {
  BlobItemProperties properties = item.getProperties();
  System.out.println(properties.getCreationTime());
}
``
