### ISSUE TITLE
[FEATURE REQ] Make Azure OpenAI `ChatRequestUserMessage.getContent()` public

### ISSUE THREAD

**Issue by jnunderwood** [Azure/azure-sdk-for-java#38169]
**Is your feature request related to a problem? Please describe.**

There are significant changes in the latest 1.0.0-beta.6 release of **Azure OpenAI** with regards to `ChatMessage`. It has been split into various other types, like `ChatResponseMessage` and `ChatRequestUserMessage`. I had been relying on the `ChatMessage.getContent()` method. However, that method is now **private** in `ChatRequestUserMessage`.

**Describe the solution you'd like**

Please make the `ChatRequestUserMessage.getContent()` **public**, just like the `getContent()` methods of other `ChatRequestMessage` subclasses (e.g., `ChatRequestSystemMessage`).

**Describe alternatives you've considered**

I am not sure how to proceed as long the `getContent()` method is private.

**Additional context**

I am really only using the `getContent()` method to count tokens. I count all the tokens in a prompt; if there are too many tokens, I trim one or more _user_ messages from the prompt before sending the request. I am able to get the content and count tokens for non-user messages since the `getContent()` method is public for those chat message types.

Thank you for considering my request.

**Comment by arnold-winkk** [comment]
+1 to that request.

For the same reason it is currently not possible to have the conversation history as a list of `ChatRequestMessage` and then retrieving the content on all elements (or serializing the list to JSON).

In the Azure SDK for .NET this was addressed with [#40710](https://github.com/Azure/azure-sdk-for-net/pull/40710). Is a similar approach possible here?

**Comment by alessiobertazzo88** [comment]
+1

I've the same issue after the upgrade to 1.0.0-beta.6 release of Azure OpenAI.

**Comment by mssfang** [comment]
@jnunderwood @arnold-winkk @alessiobertazzo88 
Sorry for the late reply. I was focusing on the development of Open AI - Assistant first beta in the past and closing to get it out soon.

Yeah. We can promote this request to be prioritized and should be in the next release of beta.7 in the near future (maybe next couple of weeks)

**Comment by mssfang** [comment]
Beta.7 is released: https://repo1.maven.org/maven2/com/azure/azure-ai-openai/1.0.0-beta.7/

**Comment by jnunderwood** [comment]
I have successfully upgraded to the latest beta. Thanks!
