### ISSUE TITLE
[QUERY]How do I use openai's gpt-3.5-1106 jsonmode?

### ISSUE THREAD

**Issue by cangxu** [Azure/azure-sdk-for-java#38176]
**Query/Question**
When I tried to call the gpt service of Microsoft Cloud opeai, I found that I could not use the jsonmode function of the model.in python, I just need to pass response_format={"type" to the large model: "json_object"}, so what do I do with that in java？

***Why is this not a Bug or a feature Request?***
A clear explanation of why is this not a bug or a feature request?
It's not a bug, I just don't know how to use this feature.Could you please give me a sample code？
**Setup (please complete the following information if applicable):**
 - OS: [windows]
 - IDE: [idea]
 - Library/Libraries: [com.azure:azure-core:1.16.0 ]
 
 **Information Checklist**
 Kindly make sure that you have added all the following information above and checkoff the required fields otherwise we will treat the issuer as an incomplete report
- [ √] Query Added
- [ ] Setup information Added

```[tasklist]
### Tasks
```

**Comment by joshfree** [comment]
@mssfang can you please follow up with @cangxu?

**Comment by mssfang** [comment]
@cangxu You can try code sample below to get the response in JSON format in java by `.setResponseFormat(new ChatCompletionsJsonResponseFormat())`.

```java
        List<ChatRequestMessage> chatMessages = new ArrayList<>();
        chatMessages.add(new ChatRequestSystemMessage("You are a helpful assistant designed to output JSON."));
        chatMessages.add(new ChatRequestUserMessage("Who won the world series in 2020?"));

        ChatCompletions chatCompletions = client.getChatCompletions("gpt-3.5-turbo-1106",
                new ChatCompletionsOptions(chatMessages).setResponseFormat(new ChatCompletionsJsonResponseFormat()));

        System.out.printf("Model ID=%s is created at %s.%n", chatCompletions.getId(), chatCompletions.getCreatedAt());
        for (ChatChoice choice : chatCompletions.getChoices()) {
            ChatResponseMessage message = choice.getMessage();
            System.out.printf("Index: %d, Chat Role: %s.%n", choice.getIndex(), message.getRole());
            System.out.println("Message:");
            System.out.println(message.getContent());
        }
```


```
Model ID=chatcmpl-8d3ABJWpzEQTYSgBVFg4lAdI8WNa7 is created at 2024-01-03T21:34:03Z.
Index: 0, Chat Role: assistant.
Message:
{
  "winner": "Los Angeles Dodgers"
}
```
