### ISSUE TITLE
[BUG] OkHttpAsyncHttpClient class calls a function that doesn't exist.

### ISSUE THREAD

**Issue by MesserOr** [Azure/azure-sdk-for-java#38172]
**Describe the bug**
In the `azure-core-http-okhttp`  in the class `OkHttpAsyncHttpClient` there is the following code:

```
    private static final byte[] EMPTY_BODY = new byte[0];
    private static final RequestBody EMPTY_REQUEST_BODY = RequestBody.create(EMPTY_BODY);
```

RequestBody is a class in okhttp3 (version 1.11.16), which doesn't have a `.create()` function that takes the `byte[0]` argument (I checked and it looks like no version does)
This bug prevents anyone from calling the builder in `OkHttpAsyncHttpClientBuilder`, which makes it so you can't authenticate (and use) the sdk through a proxy. 

There is no dependency mismatch. These are the dependencies in your main branch (specified below).

***Exception or Stack Trace***
Exception in thread "runAzureDiscovery" java.lang.NoSuchMethodError: 'okhttp3.RequestBody okhttp3.RequestBody.create(byte[])'
	at com.azure.core.http.okhttp.OkHttpAsyncHttpClient.<clinit>(OkHttpAsyncHttpClient.java:52)
	at com.azure.core.http.okhttp.OkHttpAsyncHttpClientBuilder.build(OkHttpAsyncHttpClientBuilder.java:324)

**To Reproduce**
Just try to call the `build()` method in `OkHttpAsyncHttpClient` to reproduce the behavior.

***Code Snippet***
```
    private static final byte[] EMPTY_BODY = new byte[0];
    private static final RequestBody EMPTY_REQUEST_BODY = RequestBody.create(EMPTY_BODY);
```

**Expected behavior**
EMPTY_BODY should hold an empty request body for use in the package.

**Setup**
 - OS: Windows
 - IDE: Eclipse
 - Library/Libraries: azure-core-http-okhttp_1.11.16 (found in main branch), azure-sdk-bom_1.2.19 (latest and also found in main), okhttp_4.12.0 (found in the changelog and pom file of the azure-core-http-okhttp)
 - Java version: 11
 - App Server/Environment: Tomcat9 Server
 - Frameworks: No framework

**Comment by alzimmermsft** [comment]
Thanks for filing this @MesserOr. Based on the APIs in OkHttp 4.12 it appears this static method should exist:

https://github.com/square/okhttp/blob/parent-4.12.0/okhttp/src/main/kotlin/okhttp3/RequestBody.kt#L140

If OkHttp 4.12 isn't the final version being resolved that could be the issue. Looking at OkHttp 3.x it doesn't appear that this method exists:

https://github.com/square/okhttp/blob/parent-3.14.9/okhttp/src/main/java/okhttp3/RequestBody.java#L132
