### ISSUE TITLE
[BUG] Issue deserializing a ChatRequestUserMessage object

### ISSUE THREAD

**Issue by arnold-winkk** [Azure/azure-sdk-for-java#38183]
**Describe the bug**
In my Spring Boot application I am trying to deserialize a list of ChatRequestMessages. It works for messages with role "system" or "assistant" without problem getting deserialized into ChatRequestSystemMessage and ChatRequestAssistantMessage respectively using a JSON string like this:
```
[
    {
        "role": "system",
        "content": "test"
    }
]
```

However, it doesn't work for role "user", where I used the following JSON string:
```
[
    {
        "role": "user",
        "content": "how are you"
    }
]
```

It seems to not be able to deserialize the string into a ChatRequestUserMessage and I get the following exception.

***Exception or Stack Trace***
```
{
    "timestamp": "2023-12-29T20:17:48.997+00:00",
    "status": 400,
    "error": "Bad Request",
    "exception": "org.springframework.http.converter.HttpMessageNotReadableException",
    "message": "JSON parse error: Cannot deserialize value of type `[Lcom.azure.ai.openai.models.ChatMessageContentItem;` from Object value (token `JsonToken.FIELD_NAME`)",
    "path": "/chat"
}
```

I then also tried the following JSON string with a ChatMessageContentItem but I get the same exception.
```
[
    {
        "role": "user",
        "content": [
            {
                "type": "text",
                "text": "how are you"
            }
        ]
    }
]
```

***Code Snippet***
I just use a spring boot controller like so:
```
@PutMapping(produces = ["text/event-stream"])
    fun startChat(
        @RequestBody messages: List<ChatRequestMessage>
    ): Flux<ChatCompletions> {
        // logic
    }
```

I didn't change anything regarding the Spring Boot Jackson configuration.

**Expected behavior**
I expected the ChatRequestUserMessage constructor with string content to be used for deserialization. 

**Setup (please complete the following information):**
 - OS: macOS
 - IDE: IntelliJ IDEA
 - Library/Libraries: com.azure:azure-ai-openai:1.0.0-beta.6
 - Java version: 21
 - Frameworks: Spring Boot 3.2.0

I used Postman for the http requests.

Thanks in advance for any help!

**Comment by joshfree** [comment]
@mssfang PTAL

**Comment by tzolov** [comment]
I believe I've stumbled on the same issue:
```
java.lang.RuntimeException: com.fasterxml.jackson.databind.exc.MismatchedInputException: Cannot deserialize value of type `[Lcom.azure.ai.openai.models.ChatMessageContentItem;` from Object value (token `JsonToken.FIELD_NAME`)
 at [Source: (String)"{"max_tokens":200,"messages":[{"role":"user","content":{"length":584,"replayable":true},"name":null}],"model":"gpt-35-turbo"}";
 ```
 
Using: `com.azure:azure-ai-openai:1.0.0-beta.6`

**Comment by mssfang** [comment]
Sorry for the late reply. @arnold-winkk @tzolov 
Can you provide a short sample that I can reproduce the error?

**Comment by tzolov** [comment]
@mssfang,  this should be enough to reproduce it:

```java
var mapper = new ObjectMapper();

ChatRequestMessage azureChatMessage = new ChatRequestUserMessage("Hello World");

var json = mapper.writerWithDefaultPrettyPrinter().writeValueAsString(azureChatMessage);

System.out.println(json);

ChatRequestMessage azureChatMessage2 = mapper.readValue(json, ChatRequestMessage.class);
```

output:

```
{
  "role" : "user",
  "content" : {
    "length" : 11,
    "replayable" : true
  },
  "name" : null
}
Exception in thread "main" com.fasterxml.jackson.databind.exc.MismatchedInputException: Cannot deserialize value of type `[Lcom.azure.ai.openai.models.ChatMessageContentItem;` from Object value (token `JsonToken.FIELD_NAME`)
 at [Source: (String)"{
  "role" : "user",
  "content" : {
    "length" : 11,
    "replayable" : true
  },
  "name" : null
}"; line: 3, column: 3]
....
```

**Comment by mssfang** [comment]
> @mssfang, this should be enough to reproduce it:
> 
> ```java
> var mapper = new ObjectMapper();
> 
> ChatRequestMessage azureChatMessage = new ChatRequestUserMessage("Hello World");
> 
> var json = mapper.writerWithDefaultPrettyPrinter().writeValueAsString(azureChatMessage);
> 
> System.out.println(json);
> 
> ChatRequestMessage azureChatMessage2 = mapper.readValue(json, ChatRequestMessage.class);
> ```
> 
> output:
> 
> ```
> {
>   "role" : "user",
>   "content" : {
>     "length" : 11,
>     "replayable" : true
>   },
>   "name" : null
> }
> Exception in thread "main" com.fasterxml.jackson.databind.exc.MismatchedInputException: Cannot deserialize value of type `[Lcom.azure.ai.openai.models.ChatMessageContentItem;` from Object value (token `JsonToken.FIELD_NAME`)
>  at [Source: (String)"{
>   "role" : "user",
>   "content" : {
>     "length" : 11,
>     "replayable" : true
>   },
>   "name" : null
> }"; line: 3, column: 3]
> ....
> ```

I would suggest to use `[BinaryData](https://github.com/Azure/azure-sdk-for-java/blob/main/sdk/core/azure-core/src/main/java/com/azure/core/util/BinaryData.java#L45)` to serialize and deserialize the models we have.
```java
ChatRequestMessage azureChatMessage = new ChatRequestUserMessage("Hello World");
String json =  BinaryData.fromObject(azureChatMessage).toString();
System.out.println(json);
ChatRequestMessage azureChatMessage2 = BinaryData.fromString(json).toObject(ChatRequestMessage.class);
```

**Comment by paalpri** [comment]
I am experiencing the same issues. We are using the spring boot auto serialization when the user sends a object to the controller, just like @arnold-winkk displayed in his original post. But we are getting serialization errors on the ChatRequestUserMessage as its not attempting to use its String constructur, but the Item constructor ( Which should only be used for arrays of image_url or text types). Now this means we must do a workaround and create our own input types and then recreate the ChatRequestUserMessage from our custom items later. Would be great if we could just fix the ChatRequestUserMessage string constructor so it uses the right constructors at the right time, which seems to be the issue here.

**Comment by tzolov** [comment]
@mssfang 
>I would suggest to use [BinaryData](https://github.com/Azure/azure-sdk-for-java/blob/main/sdk/core/azure-core/src/main/java/com/azure/core/util/BinaryData.java#L45) to serialize and deserialize the models we have.
Thanks for letting me know about BinaryData. 
Unfortunately It won't work for use cases that aim to support a wider set of models and APIs.

**Comment by ajgreenwell** [comment]
Same issue as OP

**Comment by mssfang** [comment]
Beta.7 is released: https://repo1.maven.org/maven2/com/azure/azure-ai-openai/1.0.0-beta.7/
