### ISSUE TITLE
Azure-core with mongodb on Quarkus can not be build in native

### ISSUE THREAD

**Issue by JiriOndrusek** [Azure/azure-sdk-for-java#38186]
**Describe the bug**
Presence of  `--report-unsupported-elements-at-runtime` and `-H:+ReportUnsupportedElementsAtRuntime` in native-image.properties causes native compilation failure when mongodb is present.

This is the same error which was fixed on aws in https://github.com/aws/aws-sdk-java-v2/pull/2368

***Exception or Stack Trace***

```
Caused by: java.lang.ClassNotFoundException: jnr.unixsocket.UnixSocket
	at java.base/java.net.URLClassLoader.findClass(URLClassLoader.java:445)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:587)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:520)
	... 13 more
```

**To Reproduce**
Reproducer: https://github.com/JiriOndrusek/azure-mongodb-native-failure-reproducer
Execute `./mvnw package -Dnative` to simulate the error.

(Project is created automatically by https://code.quarkus.io/?e=mongodb-client&e=org.apache.camel.quarkus%3Acamel-quarkus-azure-storage-queue without any change)

Reproducer contains `com.azure:azure-core:jar:1.44.1`, but the issue is present also on main branch, see https://github.com/Azure/azure-sdk-for-java/blob/main/sdk/core/azure-core/src/main/resources/META-INF/native-image/com.azure/azure-core/native-image.properties#L2-L4.

**Expected behavior**
There should be no error during the native build.

**Setup (please complete the following information):**
Should not matter. 
 - OS: Linux
 - Library/Libraries: [e.g. com.azure:azure-core:1.16.0 (groupId:artifactId:version)]
 - Java version: Temurin-17.0.9+9 (build 17.0.9+9), GRAALVM 22.3.2 JDK 17.0.7+8-LTS-jvmci-22.3-b15
 - Frameworks: Quarkus

**Information Checklist**
Kindly make sure that you have added all the following information above and checkoff the required fields otherwise we will treat the issuer as an incomplete report
- [x] Bug Description Added
- [x] Repro Steps Added
- [x] Setup information Added

**Comment by srnagar** [comment]
Thank you @JiriOndrusek for reporting and creating the PR to fix the issue.
