### ISSUE TITLE
[QUERY]|Using shared images across tenants.

### ISSUE THREAD

**Issue by darc1** [Azure/azure-sdk-for-java#3819]
**Query/Question**
I want to use images between tenants using shared image galleries, as described in [here](https://docs.microsoft.com/en-us/azure/virtual-machines/linux/share-images-across-tenants) using the java sdk, both there is no documentation as to how authentication to 2 different tenants can be done.

***Why is this not a Bug or a feature Request?***
This can be done using the azure cli, and rest api. I already have a shared image created and the app registration setup, I'm missing on how to deploy the image to a different tenant. These are the steps using the cli:
```
az account clear
az login --service-principal -u '<app ID>' -p '<Secret>' --tenant '<tenant 1 ID>'
az account get-access-token

az login --service-principal -u '<app ID>' -p '<Secret>' --tenant '<tenant 2 ID>'
az account get-access-token

az vm create \
  --resource-group myResourceGroup \
  --name myVM \
  --image "/subscriptions/<Tenant 1 subscription>/resourceGroups/<Resource group>/providers/Microsoft.Compute/galleries/<Gallery>/images/<Image definition>/versions/<version>" \
  --admin-username azureuser \
  --generate-ssh-keys
```

**Setup (please complete the following information if applicable):**
 - OS: ubuntu
 - IDE : intelliJ
 - Version of the Library used : 1.22.0

**Comment by kurtzeborn** [comment]
Thank you for opening this issue! We are routing it to the appropriate team for follow up.

**Comment by darc1** [comment]
Thanks, after digging into the Rest Api, if there is a way to set the x-ms-authorization-auxiliary header for the create vm request, it should work.

**Comment by paulojohnj** [comment]
Out of curiosity @darc1 were you able to list resources that you have shared access to? or only launch the vm in this specific context. As in could the authenticated session allow for the listening of all image galleries you have access to:

azure.imageGalleries().list() returning both your own gallery and the one that you were given shared access to

**Comment by mjconnection** [comment]
@darc1  -  Thanks for posting your question.  It appears that you have resolved your own issue.  Please let us know if there is anything else that you need.

**Comment by ADanciulescu** [comment]
+1 for Darc1's workaround worked for me. Are there any plans to support a more official solution to the multi-tenant authentication or is this the intended long-term method?

Also note, the token expires after an hour as the login is not done using service principal so I had to periodically refresh the token by running

```
client.headers().replaceHeader("x-ms-authorization-auxiliary", newToken);
```

**Comment by jianghaolu** [comment]
We will attempt a more elegant solution via https://github.com/Azure/azure-sdk-for-java/issues/6040.

**Comment by joshfree** [comment]
Tagging @yaohaizh since this is management plane.  @yaohaizh could you share more of the management plane SDK plans for migrating to newer track-2 azure-identity for picking up newer identity support / capabilities for folks who are finding this bug post online and looking for more information?

**Comment by weidongxu-microsoft** [comment]
Java supports this (yaohao did the first implementation about 2 years ago https://github.com/Azure/azure-libraries-for-java/pull/884)
```
            AzureResourceManager azureResourceManager = AzureResourceManager
                .configure()
                .withAuxiliaryCredential(anotherTokenCredential)
                .authenticate(credential, profile)
                .withDefaultSubscription();

```
alternatively this can be a list of `TokenCredential`.

There is a few bug fix and improvements afterwards, and same logic is in now in `azure-resourcemanager` as well.
