### ISSUE TITLE
[QUERY] b2c oauth flow Spring Boot integration missing parameter in authorizationRequestUri 

### ISSUE THREAD

**Issue by christianmenz** [Azure/azure-sdk-for-java#38235]
**Query/Question**
When configuring a Spring Boot application to use Azure AD B2C, the constructed authorizationRequestUri doesn't work:
_The_ resource you are looking for has been removed, had its name changed, or is temporarily unavailable.

When comparing with user flow endpoint provided in the Azure portal, one difference I can spot is the "p" parameter that identifies the user flow. 

When I add &p=B2C_1_myflow to the URL, it works fine.

Question: which part of the configuration should add this parameter or is this parameter not required?  I did try to debug it and there was nothing obvious  in the method buildAuthorizationRequestUri()

***Why is this not a Bug or a feature Request?***
I assume it is a configuration problem. 

**Setup (please complete the following information if applicable):**
 - OS: Windows
 - IDE: IntelliJ
 - Library/Libraries: spring-cloud-azure-starter-active-directory-b2c:5.7.0 (and 5.8.0)
 
 **Information Checklist**
 Kindly make sure that you have added all the following information above and checkoff the required fields otherwise we will treat the issuer as an incomplete report
- [x] Query Added
- [x] Setup information Added

**Comment by christianmenz** [comment]
I think I found the issue. The way http security is configured changed in Spring-Boot. My own configuration was not take into account. Nevertheless, some autoconfiguration kicked in and left me with a half working solution: it used almost a correct request uri.

**Comment by Netyyyy** [comment]
Hi @christianmenz , we'll auto-add the parameter here: https://github.com/Azure/azure-sdk-for-java/blob/1ea1c25dbb85cdc2273542e04a4d5ab48440fec4/sdk/spring/spring-cloud-azure-autoconfigure/src/main/java/com/azure/spring/cloud/autoconfigure/implementation/aadb2c/configuration/AadB2cOAuth2ClientConfiguration.java#L93

**Comment by christianmenz** [comment]
Thank you very much.
