### ISSUE TITLE
Effiecient way to upload from a stream without specifying length

### ISSUE THREAD

**Issue by dhatri308** [Azure/azure-sdk-for-java#38239]
**Query/Question**
Hello. We are looking for an efficient way to upload data rom an inputSteam when content length is unknown.
Is this feature implemented already ? If yes, could you please provide sample code. Thanks!

**Comment by ibrahimrabab** [comment]
Hi @dhatri308 
You may use:
[BlobClient.upload(InputStream)](https://github.com/Azure/azure-sdk-for-java/blob/main/sdk/storage/azure-storage-blob/src/main/java/com/azure/storage/blob/BlobClient.java#L189)

[BlobClient.upload(InputStream, boolean)](https://github.com/Azure/azure-sdk-for-java/blob/main/sdk/storage/azure-storage-blob/src/main/java/com/azure/storage/blob/BlobClient.java#L218)

and 

[BlobClient.uploadWithResponse(BlobParallelUploadOptions, Duration, Context)](https://github.com/Azure/azure-sdk-for-java/blob/main/sdk/storage/azure-storage-blob/src/main/java/com/azure/storage/blob/BlobClient.java#L330)

These all don't require you to pass in a length for the input stream.
