### ISSUE TITLE
[FEATURE REQ]support OpenAI assistant api

### ISSUE THREAD

**Issue by oneanime** [Azure/azure-sdk-for-java#38234]
dose this SDK support OpenAI assistant api？

**Comment by joshfree** [comment]
@mssfang please follow up

**Comment by mssfang** [comment]
@oneanime `azure-ai-openai` SDK doesn't support assistant API. We are creating a new sibling package, `azure-ai-openai-assistant` SDK to support assistant API. ETA for the first preview will be soon TBD. Hopefully, will be next month.

**Comment by mssfang** [comment]
@oneanime We just released the first beta of OpenAI SDK for java for Assistant:

First beta is released. https://repo1.maven.org/maven2/com/azure/azure-ai-openai-assistants/
