### ISSUE TITLE
Finalize the Tracing Story and Implementation in Azure Core

### ISSUE THREAD

**Issue by alzimmermsft** [Azure/azure-sdk-for-java#3823]
For tracing to be ready for GA there are some gaps that need to be closed.

- [ ] Configuration for what is being traced (Disabled, wire tracing, wire and long running operation tracing, all)
- [ ] Investigate merging Tracer and TracerProxy
- [ ] Have tracing methods for wire tracing that mirror service level tracing
- [ ] Investigate tracing for non-HTTP (AMQP, MQTT)
- [ ] Enhance attributing metadata to spans

**Comment by joshfree** [comment]
@samvaity PTAL

**Comment by samvaity** [comment]
Tracing Implementation with OpenTelemetry is now in place with support for both HTTP and AMQP SDK libraries.
