### ISSUE TITLE
[QUERY] Cosmos DB Spring Data - Timeout/retry configuration (using gateway mode)

### ISSUE THREAD

**Issue by simplyanything** [Azure/azure-sdk-for-java#38241]
**Query/Question**
I'm looking for a way to configure the timeout for any Cosmos DB call (**_gateway mode_**). Did I overlook something [in the documentation](https://learn.microsoft.com/en-us/azure/developer/java/spring-framework/configuration-properties-azure-cosmos-db)? Is it appropriate to use `spring.cloud.azure.cosmos.throttling-retry-options.max-retry-wait-time` in this case? What type of exception would this throw, a `CosmosAcccessException`?
E.g., whenever a database call (specifically `findById`/`deleteById`/`save`),  takes longer than 3 seconds, kill it. I'm also looking for a way to set a limit for retrying any operation (e.g., if it can't connect to cosmos more than 3 times, kill it).

For retry, I do see the `spring.cloud.azure.cosmos.throttling-retry-options.max-retry-attempts-on-throttled-requests` property, which is described as: 

> Maximum number of retries in the case where the request fails because the service has applied rate limiting on the client.

But what does a failed request entail specifically here? A server/network error? 

***Why is this not a Bug or a feature Request?***
I believe I may have overlooked something, as this operation would be essential in order to not overload our application server (e.g., if the `findById` operation takes longer than 3 seconds, kill it). If it is not implemented, please feel free to change this query to a feature request instead.

**Setup (please complete the following information if applicable):**
 - Library/Libraries: `com:azure.spring:spring-cloud-azure-dependencies:5.8.0` (specifically the `com.azure:azure-spring-data-cosmos:5.8.0` library)
 
 **Information Checklist**
 Kindly make sure that you have added all the following information above and checkoff the required fields otherwise we will treat the issuer as an incomplete report
- [X] Query Added
- [X] Setup information Added

**Comment by Netyyyy** [comment]
@kushagraThapar please help take a look, thanks
