### ISSUE TITLE
[BUG] Invalid User-Agent Header

### ISSUE THREAD

**Issue by mathewc** [Azure/azure-sdk-for-java#3825]
This SDK is sending invalid User-Agent headers to Azure App Service during Azure Functions management operations. This results in errors on our end when our control plane attempts to parse the header. Example value:

```
Azure-SDK-For-Java/null OS:Linux/3.10.0-862.el7.x86_64 MacAddressHash:f89558411131dddff59562d984c5c1e534542cd82a8672e6dcdbe365ea0b3963 Java:1.8.0_202 (WebSiteManagementClient, 2018-02-01)
```

The `OS:Linux` is the invalid value. .NET http libraries will throw validation errors on this:

```
System.FormatException: The format of value 'OS:Linux/3.10.0-862.el7.x86_64 MacAddressHash:f89558411131dddff59562d984c5c1e534542cd82a8672e6dcdbe365ea0b3963 Java:1.8.0_202 (WebSiteManagementClient, 2018-02-01)' is invalid.
   at System.Net.Http.Headers.HttpHeaderParser.ParseValue(String value, Object storeValue, Int32& index)
   at System.Net.Http.Headers.HttpHeaders.ParseAndAddValue(String name, HeaderStoreItemInfo info, String value)
   at System.Net.Http.Headers.HttpHeaders.Add(String name, String value)
```

**Comment by yaohaizh** [comment]
@weidongxu-microsoft Could you help take a look at this issue? Thanks.

**Comment by weidongxu-microsoft** [comment]
There seems to be no objection in RFC7230 on colon in header field.
https://www.greenbytes.de/tech/webdav/rfc7230.html#field.components

It is possible to change the format, but the collection/metric side might get impacted.
