### ISSUE TITLE
Remove `JavadocSafeJavaBuildVersion` from the base `ci.yml` template once all libraries support Java 21 Javadoc generation

### ISSUE THREAD

**Issue by vcolin7** [Azure/azure-sdk-for-java#38267]
And add a way for libraries that need it to use an earlier Java version for this step.

So far, we have very few libraries supporting Java 21-style Javadocs, so we'll keep the baseline on Java 17 and add exceptions for Java 21-ready libs.

**Comment by alzimmermsft** [comment]
Closing as this was removed by having libraries with Javadoc errors in Java 18+ skip failing the build on Javadoc errors.
