### ISSUE TITLE
Perf analysis to compare the default implementation with other options and identify the best one.

### ISSUE THREAD

**Issue by samvaity** [Azure/azure-sdk-for-java#38278]

**Comment by lmolkova** [comment]
Based on basic perf testing results, HUC (default HttpClient) has results comparable to okhttp and azure-core http clients

![image](https://github.com/Azure/azure-sdk-for-java/assets/2347409/ab101eba-86e7-4449-88a9-37823a78d874)

these results are for simple GET requests with no additional headers and tiny response body (12 bytes).

There are more gaps/testing necessary to optimize HUC implementation:
- connection pooling for PATCH requests https://github.com/Azure/azure-sdk-for-java/issues/38242
- bigger content and body streaming


Given that HUC does not introduce any dependencies and the rest is optimizable and an implementation detail, we can use HUC as a default client.

We can keep this issue open to track other work on perf testing for  PATCH/content/resiliency

**Comment by alzimmermsft** [comment]
![image](https://github.com/Azure/azure-sdk-for-java/assets/48699787/13f50422-18a9-43cd-8e5d-916ef1a233d9)
