### ISSUE TITLE
MsalClientException exception thrown when token not found in cache

### ISSUE THREAD

**Issue by y0geshdev** [Azure/azure-sdk-for-java#38300]
**Describe the bug**
When a token is not found in the in-memory cache then Azure identity log it as an MSAL exception.
The log level is a bit misleading if there is a cache miss. A warning level log might be better suited than an error log.

Or is it that I am missing something to configure it properly to avoid `ERROR` level log on cache miss?

***Exception or Stack Trace***
12:40:39.710 [ForkJoinPool.commonPool-worker-1] DEBUG c.m.a.m.ConfidentialClientApplication - [Correlation ID: f1f20e6d-42d7-4b54-baa8-7f74934320e0] Execution of class com.microsoft.aad.msal4j.AcquireTokenSilentSupplier failed.
```
com.microsoft.aad.msal4j.MsalClientException: Token not found in the cache
	at com.microsoft.aad.msal4j.AcquireTokenSilentSupplier.execute(AcquireTokenSilentSupplier.java:75)
	at com.microsoft.aad.msal4j.AuthenticationResultSupplier.get(AuthenticationResultSupplier.java:69)
	at com.microsoft.aad.msal4j.AuthenticationResultSupplier.get(AuthenticationResultSupplier.java:18)
	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1768)
	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.exec(CompletableFuture.java:1760)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165)
        ...
```

**To Reproduce**
 - Added code snippet to reproduce

***Code Snippet***
Add the code snippet that causes the issue.
```
                // create a clientCertificateCredential
                ClientCertificateCredential clientCertificateCredential = new ClientCertificateCredentialBuilder()
                        .tenantId(<Tenant_Id>)
                        .clientId(<Client_Id>)
                        .pemCertificate(<Certificate_Path>)
                        .sendCertificateChain(true)
                        .additionallyAllowedTenants("*")
                        .build();

                // create SecretClient using above credentials
                SecretClient client = new SecretClientBuilder()
                        .vaultUrl(<Vault_Url>)
                        .credential(clientCertificateCredential)
                        .buildClient();

                // get KV secret
                KeyVaultSecret spClientIdKvSecret;
                try {
                    spClientIdKvSecret = client.getSecret(<SECRET_NAME>);
                } catch (Exception ex) {
                    log.error("Unable to fetch service principal client ID secret from customer {} KV. Exception: {}",
                            destConfig.getAkvUrl(), getStackTrace(httpEx));
                    throw new ConfigurationException(format("Unable to fetch service principal client ID secret from customer %s KV.", destConfig.getAkvUrl()), httpEx);
                }
```

**Expected behavior**
Logging cache miss at a warning level might be better than logging it at error level.

**Screenshots**
NA

**Setup (please complete the following information):**
- OS: Windows 11
- IDE: IntelliJ
- Library/Libraries: com.azure:azure-identity:1.8.2
- Java version: 8
- App Server/Environment: JVM
- Frameworks: NA

**Additional context**
NA

**Information Checklist**
Kindly make sure that you have added all the following information above and checkoff the required fields otherwise we will treat the issuer as an incomplete report
- [x] Bug Description Added
- [x] Repro Steps Added
- [x] Setup information Added

**Comment by joshfree** [comment]
Thanks for filing this issue, @y0geshdev.  @billwert could you please take a look?

/cc @g2vinay

**Comment by y0geshdev** [comment]
@billwert Thanks for looking into this.
I would appreciate if you can guide me on this one.

**Comment by billwert** [comment]
Thanks for teh report @y0geshdev. We should have a fix for this in our next public release.
