### ISSUE TITLE
[FEATURE REQ] Assing user-managed identity to StorageAccount via Java SDK

### ISSUE THREAD

**Issue by roterabe** [Azure/azure-sdk-for-java#38308]
It would seem that storage accounts can only be assigned to system-managed identities. This is a limitation that I've only found in the SDK.

```
StorageAccount newStorageAccount = azureResourceManager.storageAccounts().define(storageAccountName)
                    .withRegion(Region.EUROPE_WEST)
                    .withNewResourceGroup(rgName)
                    .withSystemAssignedManagedServiceIdentity()
                    .disableBlobPublicAccess()
                    .create();
```

It would be ideal to be able to assign a user-managed identity.

**Additional context**
Here is a question I had a while ago for some additional context: [Git Question](https://github.com/Azure/azure-sdk-for-java/discussions/37452#discussioncomment-7850935)

**Information Checklist**
Kindly make sure that you have added all the following information above and checkoff the required fields otherwise we will treat the issuer as an incomplete report
- [x] Description Added
- [x] Expected solution specified

**Comment by weidongxu-microsoft** [comment]
Should be solved via https://github.com/Azure/azure-sdk-for-java/issues/38208

Expect release before end of Jan.

**Comment by weidongxu-microsoft** [comment]
2.25.0 released with this feature in convenience API.
