### ISSUE TITLE
Getting java.lang.NoClassDefFoundError: reactor/netty/transport/ClientTransport at java.base/java.lang.ClassLoader.defineClass1(Native Method)

### ISSUE THREAD

**Issue by jachthuis** [Azure/azure-sdk-for-java#38321]
Hi, I am developing a jar file using Maven for retrieving credentials from Azure Key vault but i keep getting an error for java class def not found for httpclient.
java.lang.NoClassDefFoundError: reactor/netty/transport/ClientTransport
	at java.base/java.lang.ClassLoader.defineClass1(Native Method)

I am new to this and have tried a few versions of dependencies and still no success. 
This is how the code section looks like which is generating the error:
ClientCertificateCredential clientCertificateCredential = new ClientCertificateCredentialBuilder()
			.tenantId(TenantID)
			.clientId(ClientID)
			.pfxCertificate(CertificatePath, CertificatePassword)
			.build();
			
			SecretClient secretClient = new SecretClientBuilder()
				.vaultUrl(keyVaultUrl)
				.credential(clientCertificateCredential)
				.buildClient();

Pom dependencies look like this:

		<dependency>
			<groupId>com.azure</groupId>
    		<artifactId>azure-identity</artifactId>
   			<version>1.7.0</version>
		</dependency>
		
		<dependency>
			<groupId>com.azure</groupId>
    		<artifactId>azure-security-keyvault-secrets</artifactId>
   			<version>4.2.3</version>
		</dependency>
		
		
		<dependency>
            <groupId>io.projectreactor</groupId>
            <artifactId>reactor-core</artifactId>
            <version>3.4.10</version>
        </dependency>

        <dependency>
            <groupId>io.projectreactor.netty</groupId>
            <artifactId>reactor-netty</artifactId>
            <version>1.0.11</version>
        </dependency>
 
Thanks

**Comment by joshfree** [comment]
Hi @jachthuis thanks for reaching out to us on GitHub.

In general it is simplest to reference the Azure SDK for Java BOM file for dependency management: https://github.com/Azure/azure-sdk-for-java/wiki/BOM-Guidelines#using-the-bom

If you prefer to reference dependencies directly instead, please check out the troubleshooting dependency version conflict links below:

- https://github.com/Azure/azure-sdk-for-java/wiki/Frequently-Asked-Questions#im-getting-a-nosuchmethoderror-or-noclassdeffounderror
- https://learn.microsoft.com/en-us/azure/developer/java/sdk/troubleshooting-dependency-version-conflict

If these articles don't provide a solution for the problem, please provide the verbose dependency tree (`mvn dependency:tree -Dverbose`) and we can help dig into it further.

Thanks

**Comment by jachthuis** [comment]
Hi @joshfree , thanks for the response. I used the bom and updated the jar. Still getting the same.
This is what i have in my pom file now:
`<dependencyManagement>
		<dependencies>
			<dependency>
				<groupId>com.azure</groupId>
				<artifactId>azure-sdk-bom</artifactId>
				<version>1.2.0</version>
				<type>pom</type>
				<scope>import</scope>
			</dependency>
		</dependencies>
	</dependencyManagement>
`

The error changed slightly:
`java.lang.NoClassDefFoundError: reactor/netty/transport/ClientTransport at com.azure.core.http.netty.NettyAsyncHttpClientBuilder.build(NettyAsyncHttpClientBuilder.java:141) at com.azure.core.http.netty.NettyAsyncHttpClientProvider.createInstance(NettyAsyncHttpClientProvider.java:19) at com.azure.core.implementation.http.HttpClientProviders.createInstance(HttpClientProviders.java:67) at com.azure.core.http.HttpClient.createDefault(HttpClient.java:50) at com.azure.core.http.HttpClient.createDefault(HttpClient.java:40) at com.azure.core.http.HttpPipelineBuilder.build(HttpPipelineBuilder.java:73) at com.azure.security.keyvault.secrets.SecretClientBuilder.buildAsyncClient(SecretClientBuilder.java:225) at com.azure.security.keyvault.secrets.SecretClientBuilder.buildClient(SecretClientBuilder.java:147)`

This is the dependency tree:
` azure-credential-resolver:azure-credential-resolver:jar:0.0.1-SNAPSHOT
[INFO] +- org.apache.commons:commons-lang3:jar:3.12.0:compile
[INFO] +- com.azure:azure-identity:jar:1.4.6:compile
[INFO] |  +- com.azure:azure-core:jar:1.26.0:compile
[INFO] |  |  +- com.fasterxml.jackson.core:jackson-annotations:jar:2.13.1:compile
[INFO] |  |  +- com.fasterxml.jackson.core:jackson-core:jar:2.13.1:compile
[INFO] |  |  +- com.fasterxml.jackson.core:jackson-databind:jar:2.13.1:compile
[INFO] |  |  |  +- (com.fasterxml.jackson.core:jackson-annotations:jar:2.13.1:compile - omitted for duplicate)
[INFO] |  |  |  \- (com.fasterxml.jackson.core:jackson-core:jar:2.13.1:compile - omitted for duplicate)
[INFO] |  |  +- com.fasterxml.jackson.datatype:jackson-datatype-jsr310:jar:2.13.1:compile
[INFO] |  |  |  +- (com.fasterxml.jackson.core:jackson-annotations:jar:2.13.1:compile - omitted for duplicate)
[INFO] |  |  |  +- (com.fasterxml.jackson.core:jackson-core:jar:2.13.1:compile - omitted for duplicate)
[INFO] |  |  |  \- (com.fasterxml.jackson.core:jackson-databind:jar:2.13.1:compile - omitted for duplicate)
[INFO] |  |  +- com.fasterxml.jackson.dataformat:jackson-dataformat-xml:jar:2.13.1:compile
[INFO] |  |  |  +- (com.fasterxml.jackson.core:jackson-core:jar:2.13.1:compile - omitted for duplicate)
[INFO] |  |  |  +- (com.fasterxml.jackson.core:jackson-annotations:jar:2.13.1:compile - omitted for duplicate)
[INFO] |  |  |  +- (com.fasterxml.jackson.core:jackson-databind:jar:2.13.1:compile - omitted for duplicate)
[INFO] |  |  |  +- org.codehaus.woodstox:stax2-api:jar:4.2.1:compile
[INFO] |  |  |  \- com.fasterxml.woodstox:woodstox-core:jar:6.2.7:compile
[INFO] |  |  |     \- (org.codehaus.woodstox:stax2-api:jar:4.2.1:compile - omitted for duplicate)
[INFO] |  |  +- org.slf4j:slf4j-api:jar:1.7.33:compile
[INFO] |  |  +- io.projectreactor:reactor-core:jar:3.4.14:compile
[INFO] |  |  |  \- (org.reactivestreams:reactive-streams:jar:1.0.3:compile - omitted for conflict with 1.0.0)
[INFO] |  |  \- io.netty:netty-tcnative-boringssl-static:jar:2.0.47.Final:compile
[INFO] |  |     \- io.netty:netty-tcnative-classes:jar:2.0.47.Final:compile
[INFO] |  +- com.azure:azure-core-http-netty:jar:1.11.8:compile
[INFO] |  |  +- (com.azure:azure-core:jar:1.26.0:compile - omitted for duplicate)
[INFO] |  |  +- io.netty:netty-handler:jar:4.1.73.Final:compile
[INFO] |  |  |  +- io.netty:netty-common:jar:4.1.73.Final:compile
[INFO] |  |  |  +- io.netty:netty-resolver:jar:4.1.73.Final:compile
[INFO] |  |  |  |  \- (io.netty:netty-common:jar:4.1.73.Final:compile - omitted for duplicate)
[INFO] |  |  |  +- (io.netty:netty-buffer:jar:4.1.73.Final:compile - omitted for duplicate)
[INFO] |  |  |  +- io.netty:netty-transport:jar:4.1.73.Final:compile
[INFO] |  |  |  |  +- (io.netty:netty-common:jar:4.1.73.Final:compile - omitted for duplicate)
[INFO] |  |  |  |  +- (io.netty:netty-buffer:jar:4.1.73.Final:compile - omitted for duplicate)
[INFO] |  |  |  |  \- (io.netty:netty-resolver:jar:4.1.73.Final:compile - omitted for duplicate)
[INFO] |  |  |  +- io.netty:netty-codec:jar:4.1.73.Final:compile
[INFO] |  |  |  |  +- (io.netty:netty-common:jar:4.1.73.Final:compile - omitted for duplicate)
[INFO] |  |  |  |  +- (io.netty:netty-buffer:jar:4.1.73.Final:compile - omitted for duplicate)
[INFO] |  |  |  |  \- (io.netty:netty-transport:jar:4.1.73.Final:compile - omitted for duplicate)
[INFO] |  |  |  \- (io.netty:netty-tcnative-classes:jar:2.0.46.Final:compile - omitted for conflict with 2.0.47.Final)
[INFO] |  |  +- io.netty:netty-handler-proxy:jar:4.1.73.Final:compile
[INFO] |  |  |  +- (io.netty:netty-common:jar:4.1.73.Final:compile - omitted for duplicate)
[INFO] |  |  |  +- (io.netty:netty-buffer:jar:4.1.73.Final:compile - omitted for duplicate)
[INFO] |  |  |  +- (io.netty:netty-transport:jar:4.1.73.Final:compile - omitted for duplicate)
[INFO] |  |  |  +- (io.netty:netty-codec:jar:4.1.73.Final:compile - omitted for duplicate)
[INFO] |  |  |  +- io.netty:netty-codec-socks:jar:4.1.73.Final:compile
[INFO] |  |  |  |  +- (io.netty:netty-common:jar:4.1.73.Final:compile - omitted for duplicate)
[INFO] |  |  |  |  +- (io.netty:netty-buffer:jar:4.1.73.Final:compile - omitted for duplicate)
[INFO] |  |  |  |  +- (io.netty:netty-transport:jar:4.1.73.Final:compile - omitted for duplicate)
[INFO] |  |  |  |  \- (io.netty:netty-codec:jar:4.1.73.Final:compile - omitted for duplicate)
[INFO] |  |  |  \- (io.netty:netty-codec-http:jar:4.1.73.Final:compile - omitted for duplicate)
[INFO] |  |  +- io.netty:netty-buffer:jar:4.1.73.Final:compile
[INFO] |  |  |  \- (io.netty:netty-common:jar:4.1.73.Final:compile - omitted for duplicate)
[INFO] |  |  +- io.netty:netty-codec-http:jar:4.1.73.Final:compile
[INFO] |  |  |  +- (io.netty:netty-common:jar:4.1.73.Final:compile - omitted for duplicate)
[INFO] |  |  |  +- (io.netty:netty-buffer:jar:4.1.73.Final:compile - omitted for duplicate)
[INFO] |  |  |  +- (io.netty:netty-transport:jar:4.1.73.Final:compile - omitted for duplicate)
[INFO] |  |  |  +- (io.netty:netty-codec:jar:4.1.73.Final:compile - omitted for duplicate)
[INFO] |  |  |  \- (io.netty:netty-handler:jar:4.1.73.Final:compile - omitted for duplicate)
[INFO] |  |  +- io.netty:netty-codec-http2:jar:4.1.73.Final:compile
[INFO] |  |  |  +- (io.netty:netty-common:jar:4.1.73.Final:compile - omitted for duplicate)
[INFO] |  |  |  +- (io.netty:netty-buffer:jar:4.1.73.Final:compile - omitted for duplicate)
[INFO] |  |  |  +- (io.netty:netty-transport:jar:4.1.73.Final:compile - omitted for duplicate)
[INFO] |  |  |  +- (io.netty:netty-codec:jar:4.1.73.Final:compile - omitted for duplicate)
[INFO] |  |  |  +- (io.netty:netty-handler:jar:4.1.73.Final:compile - omitted for duplicate)
[INFO] |  |  |  \- (io.netty:netty-codec-http:jar:4.1.73.Final:compile - omitted for duplicate)
[INFO] |  |  +- io.netty:netty-transport-native-unix-common:jar:4.1.73.Final:compile
[INFO] |  |  |  +- (io.netty:netty-common:jar:4.1.73.Final:compile - omitted for duplicate)
[INFO] |  |  |  +- (io.netty:netty-buffer:jar:4.1.73.Final:compile - omitted for duplicate)
[INFO] |  |  |  \- (io.netty:netty-transport:jar:4.1.73.Final:compile - omitted for duplicate)
[INFO] |  |  +- io.netty:netty-transport-native-epoll:jar:linux-x86_64:4.1.73.Final:compile
[INFO] |  |  |  +- (io.netty:netty-common:jar:4.1.73.Final:compile - omitted for duplicate)
[INFO] |  |  |  +- (io.netty:netty-buffer:jar:4.1.73.Final:compile - omitted for duplicate)
[INFO] |  |  |  +- (io.netty:netty-transport:jar:4.1.73.Final:compile - omitted for duplicate)
[INFO] |  |  |  +- (io.netty:netty-transport-native-unix-common:jar:4.1.73.Final:compile - omitted for duplicate)
[INFO] |  |  |  \- io.netty:netty-transport-classes-epoll:jar:4.1.73.Final:compile
[INFO] |  |  |     +- (io.netty:netty-common:jar:4.1.73.Final:compile - omitted for duplicate)
[INFO] |  |  |     +- (io.netty:netty-buffer:jar:4.1.73.Final:compile - omitted for duplicate)
[INFO] |  |  |     +- (io.netty:netty-transport:jar:4.1.73.Final:compile - omitted for duplicate)
[INFO] |  |  |     \- (io.netty:netty-transport-native-unix-common:jar:4.1.73.Final:compile - omitted for duplicate)
[INFO] |  |  +- io.netty:netty-transport-native-kqueue:jar:osx-x86_64:4.1.73.Final:compile
[INFO] |  |  |  +- (io.netty:netty-common:jar:4.1.73.Final:compile - omitted for duplicate)
[INFO] |  |  |  +- (io.netty:netty-buffer:jar:4.1.73.Final:compile - omitted for duplicate)
[INFO] |  |  |  +- (io.netty:netty-transport:jar:4.1.73.Final:compile - omitted for duplicate)
[INFO] |  |  |  +- (io.netty:netty-transport-native-unix-common:jar:4.1.73.Final:compile - omitted for duplicate)
[INFO] |  |  |  \- io.netty:netty-transport-classes-kqueue:jar:4.1.73.Final:compile
[INFO] |  |  |     +- (io.netty:netty-common:jar:4.1.73.Final:compile - omitted for duplicate)
[INFO] |  |  |     +- (io.netty:netty-buffer:jar:4.1.73.Final:compile - omitted for duplicate)
[INFO] |  |  |     +- (io.netty:netty-transport:jar:4.1.73.Final:compile - omitted for duplicate)
[INFO] |  |  |     \- (io.netty:netty-transport-native-unix-common:jar:4.1.73.Final:compile - omitted for duplicate)
[INFO] |  |  \- io.projectreactor.netty:reactor-netty-http:jar:1.0.15:compile
[INFO] |  |     +- (io.netty:netty-codec-http:jar:4.1.72.Final:compile - omitted for conflict with 4.1.73.Final)
[INFO] |  |     +- (io.netty:netty-codec-http2:jar:4.1.72.Final:compile - omitted for conflict with 4.1.73.Final)
[INFO] |  |     +- io.netty:netty-resolver-dns:jar:4.1.72.Final:compile
[INFO] |  |     |  +- (io.netty:netty-common:jar:4.1.72.Final:compile - omitted for conflict with 4.1.73.Final)
[INFO] |  |     |  +- (io.netty:netty-buffer:jar:4.1.72.Final:compile - omitted for conflict with 4.1.73.Final)
[INFO] |  |     |  +- (io.netty:netty-resolver:jar:4.1.72.Final:compile - omitted for conflict with 4.1.73.Final)
[INFO] |  |     |  +- (io.netty:netty-transport:jar:4.1.72.Final:compile - omitted for conflict with 4.1.73.Final)
[INFO] |  |     |  +- (io.netty:netty-codec:jar:4.1.72.Final:compile - omitted for conflict with 4.1.73.Final)
[INFO] |  |     |  +- io.netty:netty-codec-dns:jar:4.1.72.Final:compile
[INFO] |  |     |  |  +- (io.netty:netty-common:jar:4.1.72.Final:compile - omitted for conflict with 4.1.73.Final)
[INFO] |  |     |  |  +- (io.netty:netty-buffer:jar:4.1.72.Final:compile - omitted for conflict with 4.1.73.Final)
[INFO] |  |     |  |  +- (io.netty:netty-transport:jar:4.1.72.Final:compile - omitted for conflict with 4.1.73.Final)
[INFO] |  |     |  |  \- (io.netty:netty-codec:jar:4.1.72.Final:compile - omitted for conflict with 4.1.73.Final)
[INFO] |  |     |  \- (io.netty:netty-handler:jar:4.1.72.Final:compile - omitted for conflict with 4.1.73.Final)
[INFO] |  |     +- io.netty:netty-resolver-dns-native-macos:jar:osx-x86_64:4.1.72.Final:compile
[INFO] |  |     |  \- io.netty:netty-resolver-dns-classes-macos:jar:4.1.72.Final:compile
[INFO] |  |     |     +- (io.netty:netty-common:jar:4.1.72.Final:compile - omitted for conflict with 4.1.73.Final)
[INFO] |  |     |     +- (io.netty:netty-resolver-dns:jar:4.1.72.Final:compile - omitted for duplicate)
[INFO] |  |     |     \- (io.netty:netty-transport-native-unix-common:jar:4.1.72.Final:compile - omitted for conflict with 4.1.73.Final)
[INFO] |  |     +- (io.netty:netty-transport-native-epoll:jar:linux-x86_64:4.1.72.Final:compile - omitted for conflict with 4.1.73.Final)
[INFO] |  |     +- io.projectreactor.netty:reactor-netty-core:jar:1.0.15:compile
[INFO] |  |     |  +- (io.netty:netty-handler:jar:4.1.72.Final:compile - omitted for conflict with 4.1.73.Final)
[INFO] |  |     |  +- (io.netty:netty-handler-proxy:jar:4.1.72.Final:compile - omitted for conflict with 4.1.73.Final)
[INFO] |  |     |  +- (io.netty:netty-resolver-dns:jar:4.1.72.Final:compile - omitted for duplicate)
[INFO] |  |     |  +- (io.netty:netty-resolver-dns-native-macos:jar:osx-x86_64:4.1.72.Final:compile - omitted for duplicate)
[INFO] |  |     |  +- (io.netty:netty-transport-native-epoll:jar:linux-x86_64:4.1.72.Final:compile - omitted for conflict with 4.1.73.Final)
[INFO] |  |     |  \- (io.projectreactor:reactor-core:jar:3.4.14:compile - omitted for duplicate)
[INFO] |  |     \- (io.projectreactor:reactor-core:jar:3.4.14:compile - omitted for duplicate)
[INFO] |  +- com.microsoft.azure:msal4j:jar:1.11.0:compile
[INFO] |  |  +- com.nimbusds:oauth2-oidc-sdk:jar:9.7:compile
[INFO] |  |  |  +- com.github.stephenc.jcip:jcip-annotations:jar:1.0-1:compile
[INFO] |  |  |  +- com.nimbusds:content-type:jar:2.1:compile
[INFO] |  |  |  +- (net.minidev:json-smart:jar:2.4.7:compile - omitted for duplicate)
[INFO] |  |  |  +- com.nimbusds:lang-tag:jar:1.5:compile
[INFO] |  |  |  \- com.nimbusds:nimbus-jose-jwt:jar:9.9.3:compile
[INFO] |  |  |     \- (com.github.stephenc.jcip:jcip-annotations:jar:1.0-1:compile - omitted for duplicate)
[INFO] |  |  +- (org.slf4j:slf4j-api:jar:1.7.28:compile - omitted for conflict with 1.7.33)
[INFO] |  |  \- (com.fasterxml.jackson.core:jackson-databind:jar:2.12.1:compile - omitted for conflict with 2.13.1)
[INFO] |  +- com.microsoft.azure:msal4j-persistence-extension:jar:1.1.0:compile
[INFO] |  |  +- (com.microsoft.azure:msal4j:jar:1.4.0:compile - omitted for conflict with 1.11.0)
[INFO] |  |  +- net.java.dev.jna:jna:jar:5.5.0:compile
[INFO] |  |  +- (net.java.dev.jna:jna-platform:jar:5.5.0:compile - omitted for conflict with 5.6.0)
[INFO] |  |  \- (org.slf4j:slf4j-api:jar:1.7.7:compile - omitted for conflict with 1.7.33)
[INFO] |  +- net.java.dev.jna:jna-platform:jar:5.6.0:compile
[INFO] |  |  \- (net.java.dev.jna:jna:jar:5.6.0:compile - omitted for conflict with 5.5.0)
[INFO] |  \- net.minidev:json-smart:jar:2.4.7:compile
[INFO] |     \- net.minidev:accessors-smart:jar:2.4.7:compile
[INFO] |        \- org.ow2.asm:asm:jar:9.1:compile
[INFO] +- com.azure:azure-security-keyvault-secrets:jar:4.3.8:compile
[INFO] |  +- (com.azure:azure-core:jar:1.26.0:compile - omitted for duplicate)
[INFO] |  \- (com.azure:azure-core-http-netty:jar:1.11.8:compile - omitted for duplicate)
[INFO] +- org.json:json:jar:20180130:compile
[INFO] +- org.apache.clerezza.ext:org.json.simple:jar:0.4:compile
[INFO] |  \- com.googlecode.json-simple:json-simple:jar:1.1:compile
[INFO] +- org.reactivestreams:reactive-streams:jar:1.0.0:compile
[INFO] +- com.snc:mid:jar:19.0.0.0-SNAPSHOT:system
[INFO] +- com.snc:commons-glide:jar:19.0.0.0-SNAPSHOT:system
[INFO] +- com.snc:commons-core-automation:jar:19.0.0.0-SNAPSHOT:system
[INFO] +- com.snc:snc-automation-api:jar:19.0.0.0-SNAPSHOT:system
[INFO] +- com.google.guava:guava:jar:2.8.2:system
[INFO] \- com.google.code.gson:gson:jar:2.8.2:system
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  17.384 s
[INFO] Finished at: 2024-01-17T14:34:52Z`

**Comment by jachthuis** [comment]
Attaching the dependency info as a file.
[DependencyTree.txt](https://github.com/Azure/azure-sdk-for-java/files/13964884/DependencyTree.txt)

**Comment by jachthuis** [comment]
I have been able to resolve it by excluding `azure-core-http-netty` on all of the `com.azure` dependencies and then added the `azure-core-http-okhttp` artifact. I am able to connect to the vault now.

**Comment by joshfree** [comment]
> I have been able to resolve it by excluding azure-core-http-netty on all of the com.azure dependencies and then added the azure-core-http-okhttp artifact. I am able to connect to the vault now.

@alzimmermsft could you take a look at the debug details @jachthuis shared above?

**Comment by alzimmermsft** [comment]
Thanks for including the dependency tree @jachthuis. From that, nothing jumps out to me as explicitly being a problem. For this application, is this being ran in a hosted environment such as Azure Functions, Jetty, Tomcat, etc where the environment may have conflicting dependencies?

**Comment by jachthuis** [comment]
Hi @alzimmermsft , the jar file is being run from a Servicenow mid server which in itself is a java application and hosts a lot of dependency jar files in its library. There were netty jars in it, but it provides an option to upload external jars and enforce to take those from a separate path which i had done. But it may be a possibility. But, shouldnt it give some other error in that case ? like in between it was giving me version mismatch error for jackson jars which made me realize i can override the lib path of the application.

**Comment by alzimmermsft** [comment]
That is a good request to add more logging for when there is a conflict in Netty dependencies @jachthuis . We'll take a look into that and I'll reply back once we have something to share, it may be a bit more complicated than Jackson though as Netty has some native dependencies and I don't know if it stamps in the JAR version like Jackson does with their `VERSION` constant.
