### ISSUE TITLE
[FEATURE REQ] Implement TokenCredentialBuilder

### ISSUE THREAD

**Issue by o-shevchenko** [Azure/azure-sdk-for-java#38320]
**Is your feature request related to a problem? Please describe.**
I have a `token` string and I would like to create `TokenCredential` from it.
The proposed solution from the library is implementing a functional interface directly:
```kotlin
TokenCredential {
        Mono.just(AccessToken(token, OffsetDateTime.parse(tokenExpiresAt)))
    }
```
The problem is that we have to add Project Reactor to our dependencies. And we would like to avoid it.

**Describe the solution you'd like**
It will be good to utilize some builder to be consistent with other methods (e.g. `ClientSecretCredentialBuilder`).
The solution is adding `TokenCredentialBuilder` that we can import without importing Reactor directly. That can hide implementation details from client code. 
 `TokenCredentialBuilder` should just provide methods to set the token:
 ```kotlin
 val token: TokenCredential = TokenCredentialBuilder()
        .token(token)
        .expiresAt(expiresAt)
        .build()
 ```
 
 A similar request is described here: https://github.com/Azure/azure-sdk-for-java/issues/7480 .
 We don't need a TokenCredential we just need a convenient API that can encapsulate implementation details and don't force using Reactor lib in our services just to invoke `Mono.just(AccessToken(token, OffsetDateTime.parse(tokenExpiresAt)))` once.

**Comment by joshfree** [comment]
@billwert could you please follow up with @o-shevchenko

**Comment by o-shevchenko** [comment]
Any thoughts on that?

**Comment by billwert** [comment]
Hello @o-shevchenko!

This isn't a feature we would add to the SDK. This is a fairly niche scenario. In addition, this sort of credential would not support many of the features our credentials support such as caching and renewal. 

If you need this functionality and don't want to take a widespread dependency on Reactor, you could wrap this into its own library and use it from there, perhaps?

**Comment by billwert** [comment]
> Could you explain it? I'm not sure why the current implementation for `TokenCredential` requires Reactor.

Reactor is our chosen concurrency strategy across the SDK. Thus, we need a Reactor based method for getting a token from a `TokenCredential`. It's an artifact of history that the Reactor method is the one requiring an implementation, and is not something we can change now.


> Do you mind if we contribute such a builder to this repo?

We would not take this PR. We do not believe a `TokenCredential` implementation that simply returns a static token is appropriate for the SDK. It is an anti-pattern to have a credential with no logic for observing timeouts and performing refreshes.
