### ISSUE TITLE
LinkedHashMap cannot be cast to class DocumentField - Document Intelligence Java sdk

### ISSUE THREAD

**Issue by bjamin5** [Azure/azure-sdk-for-java#38326]
**Describe the bug**
When parsing results from the document intellligence Java sdk (using prebuilt w2 model) the Employer & Employee DocumentField objects contain maps of type Map<String, DocumentType> but when you call getValueAsMap(), you are returned a LinkedHashMap instead. The function definition for getValueAsMap() is defined to return a Map<String, DocumentField>.

***Exception or Stack Trace***
Exception:
java.lang.ClassCastException: class java.util.LinkedHashMap cannot be cast to class com.azure.ai.formrecognizer.documentanalysis.models.DocumentField (java.util.LinkedHashMap is in module java.base of loader 'bootstrap';

***Code Snippet***
```
import com.azure.ai.formrecognizer.documentanalysis.models.AnalyzeResult;import com.azure.ai.formrecognizer.documentanalysis.models.AnalyzedDocument;import com.azure.ai.formrecognizer.documentanalysis.models.DocumentField;import com.azure.ai.formrecognizer.documentanalysis.models.DocumentFieldType;

// Submit an image of a w2 

// Get results back
AnalyzeResult results= analyzeDocumentPoller.getFinalResult().getDocuments().get(0);
Map<String, DocumentField> taxFields = results.getFields();

DocumentField employerField = taxFields.get("Employer");

// PROBLEM LINES
Map<String, DocumentField> employerDataFieldMap = employerField.getValueAsMap();

// Error thrown here from this line not returning a DocumentField like it should
DocumentField employerNameObj = employerDataFieldMap.get("Name");
```

**Expected behavior**
employerDataFieldMap should contain objects of class  DocumentField for the values.

**Screenshots**
![image](https://github.com/Azure/azure-sdk-for-java/assets/55118829/d40fcc9d-86c1-4e5f-bdc6-87374c6d802c)

**Setup (please complete the following information):**

 - Library/Libraries: "com.azure:azure-ai-formrecognizer:4.1.0"
 - Java version: 17
 - App Server/Environment: Tomcat

**Additional context**

Here is a workaround:
Map<String, Object> employerDataFieldMap = (Map<String, Object>)employerField.getValue();
Object employerNameMap = employerDataFieldMap.get("Name");
Map<String, Object> nameMap = (Map<String, Object>) employerNameMap;
String name = (String) nameMap.get("value");

**Information Checklist**
Kindly make sure that you have added all the following information above and checkoff the required fields otherwise we will treat the issuer as an incomplete report
- [x] Bug Description Added
- [x] Repro Steps Added
- [x] Setup information Added

**Comment by joshfree** [comment]
@samvaity PTAL

**Comment by bjamin5** [comment]
I realized that in my code I actually serialize the AnalyzeResult Object to a jsonString with Jaxson and then later on I convert it back to an AnalyzeResult object to then parse. In order to convert it back to an AnalyzeResult class I had to include Fail on Unknown properties because it kept having an exception saying it couldn't find the 'handwritten' variable or something. Unfortunetly I can't seem to recreate that error that orginally prompted me to add the deserialization ignore config. When deserializing the object with FAIL_ON_UNKOWN_PROPERTIES I get the bug with .getValueAsMap() not returning a map of DocumentField objects.

```
ObjectMapper objectMapper = new ObjectMapper();
objectMapper.configure(DeserializationFeature.FAIL_ON_UNKNOWN_PROPERTIES, false);
AnalyzeResult analyzeTaxResult = new AnalyzeResult();
analyzeTaxResult = objectMapper.readValue(responseBody, AnalyzeResult.class);
```

**Comment by bjamin5** [comment]
Okay I've been able to recreate the error. When you submit a document that has handwritten text on it the response is different. 
This is the exception I get for this line:

```
AnalyzeResult analyzeDocumentResult = analyzeDocumentPoller.getFinalResult();

List<AnalyzedDocument> analyzedDocuments = analyzeDocumentResult.getDocuments();

ObjectMapper objectMapper = new ObjectMapper();

String jsonResult = objectMapper.writeValueAsString(analyzeDocumentResult);

//	Commeted out - > objectMapper.configure(DeserializationFeature.FAIL_ON_UNKNOWN_PROPERTIES, false);
AnalyzeResult analyzeTaxResult = new AnalyzeResult();

Error ->	analyzeTaxResult = objectMapper.readValue(jsonResult, AnalyzeResult.class);
```

Exception:
com.fasterxml.jackson.databind.exc.UnrecognizedPropertyException: Unrecognized field "handwritten" (class com.azure.ai.formrecognizer.documentanalysis.models.DocumentStyle), not marked as ignorable (8 known properties: "fontStyle", "color", "backgroundColor", "fontWeight", "spans", "confidence", "isHandwritten", "similarFontFamily"])
 at [Source: (StringReader); line: 1, column: 55221] (through reference chain: com.azure.ai.formrecognizer.documentanalysis.models.AnalyzeResult["styles"]->java.util.ArrayList[0]->com.azure.ai.formrecognizer.documentanalysis.models.DocumentStyle["handwritten"])

**Comment by bjamin5** [comment]
Here is the difference in the serialized JSON
With Handwritten text

```

"keyValuePairs": null,
  "styles": [
    {
      "spans": [
        {
          "offset": 0,
          "length": 1
        }
      ],
      "confidence": 0.9,
      "similarFontFamily": null,
      "fontStyle": null,
      "fontWeight": null,
      "color": null,
      "backgroundColor": null,
      "handwritten": true
    },
    {
      "spans": [
        {
          "offset": 830,
          "length": 1
        }
      ],
      "confidence": 0.1,
      "similarFontFamily": null,
      "fontStyle": null,
      "fontWeight": null,
      "color": null,
      "backgroundColor": null,
      "handwritten": true
    }
  ],
  "documents": [
    {
      "docType": "tax.us.w2",
```

Without handwritten text
```
"keyValuePairs": null,
  "styles": null,
  "documents": [
    {
      "docType": "tax.us.w2",
      "boundingRegions": [

```

**Comment by samvaity** [comment]
Hi @bjamin5, thank you for the references. Could you help me understand if the problem is with the deserialization of data when styles is not null?

**Comment by bjamin5** [comment]
@samvaity Yes that is the problem. The original problem I encountered was due to trying work arounds for this bug.

**Comment by bjamin5** [comment]
I attempted to parse the Json and set the value for the "styles" key to be null manually and Jaxson still didn't succeed in converting it back to an AnalyzeResult class object. This leads me to believe there may be something else affecting Jaxsons ability to parse. This was over a week ago so I don't have the specific error.

**Comment by samvaity** [comment]
@bjamin5 Can you confirm if this is still the case?

**Comment by samvaity** [comment]
Thank you for reporting, feel free to reopen the issue if the bug still exists.
