### ISSUE TITLE
[QUERY] What is the best (cheapest) way to check if a BlockBlob already exists in a container?

### ISSUE THREAD

**Issue by kagkarlsson** [Azure/azure-sdk-for-java#3834]
**Query/Question**
What is the best (cheapest) way to check if a BlockBlob already exists in a container?

***Why is this not a Bug or a feature Request?***
Usage-question I have found no documentation or examples for.

**Setup (please complete the following information if applicable):**
 - Version: 11.0.0

**Comment by kurtzeborn** [comment]
Thank you for opening this issue! We are routing it to the appropriate team for follow up.

**Comment by rickle-msft** [comment]
@kagkarlsson Sorry for the delay. The best way to do this is to make a getProperties call and handle a 404 if it doesn't exist. Please let us know if you have any further questions or concerns. A few thoughts to consider:

- Depending on your application architecture, you should be a little wary of using exists as the result is immediately invalid. In distributed systems, there is no guarantee that the resource wasn't deleted/created immediately after this call by some other role. 
- While this sort of thing is not available in v11, we will be adding convenience methods to v12, the preview for which is out now if you'd like to try it.
- We are generally recommending that customers either stay on v8 if they are comfortable there or be prepared to upgrade to v12 once it goes GA. There were some stability issues when v11 went to scale that are resolved in v12, but the upgrade also does come with a bit of a facelift that will slightly modify the api surface. I just wanted to give you a heads up on that as well.

**Comment by kagkarlsson** [comment]
Ok, thanks. 

Are there artifacts in maven central for the preview or do I build it myself?

**Comment by rickle-msft** [comment]
There's an [artifact](https://search.maven.org/artifact/com.azure/azure-storage-blob/12.0.0-preview.1/jar) on maven central. If you give it a go, we'd love to hear what you think!

**Comment by zhusijia26** [comment]
Close the issue since answer provided. Please reopen if there is still question.

**Comment by kagkarlsson** [comment]
@rickle-msft Is [this](https://github.com/Azure/azure-sdk-for-java/tree/master/sdk/storage/azure-storage-blob) the documentation reflecting the facelift?   

(Btw, the link here 404s: https://github.com/Azure/azure-storage-java )

**Comment by kagkarlsson** [comment]
Trying out the preview client some now. 

Am I supposed to use the async client if the data I upload is of unknown length? cc @rickle-msft

**Comment by kagkarlsson** [comment]
Will `12.0.0-preview.2` also be made available? Would like to use the `new DefaultAzureCredential()` to get a node managed identity.

```BlobServiceClient storageClient = new BlobServiceClientBuilder()
                .endpoint(endpoint)
                .credential(new DefaultAzureCredential())
                .buildClient();```

cc @rickle-msft

**Comment by rickle-msft** [comment]
@kagkarlsson. Yes, that is the location of the new source. Thank you for mentioning the 404; the structure of this repo has changed a bit since we updated that README, so I'll go fix that. 

Perhaps this sounds meaningless, but the async client is for async operations. It'll support a completely different paradigm, and in most cases you'll still need to know the length of your data. If you are working in a sync environment and don't know the length of your data, we recommend working with a BlobOutputStream, which you can open using the BlockBlobClient. 

Preview 2 will be released today.

**Comment by kagkarlsson** [comment]
@rickle-msft 
Thanks! I did not see the `BlobOutputStream`, this is what I needed.

Eagerly awaiting Preview 2 then :)

**Comment by rickle-msft** [comment]
Preview 2 is out now!

**Comment by kagkarlsson** [comment]
Hmm I had assume the release would make it in sync with documentation, but I still cannot do this: 

```
BlobServiceClient storageClient = BlobServiceClient.storageClientBuilder()
        .endpoint(endpoint)
        .credential(new DefaultAzureCredential())
        .buildClient();
```

How do I currently setup my storage-client to get credentials via NodeManagedIdentities?
@rickle-msft

**Comment by kagkarlsson** [comment]
I think I found my way. 

When do you think 12.0.0 will be released @rickle-msft ?

**Comment by rickle-msft** [comment]
"I had assume the release would make it in sync with documentation" is there documentation you've found that doesn't match the SDK? If so, we'd like to update it.

I can't give a guaranteed date, but we are on a schedule to release at least one preview per month until we GA. I think the hope is that preview 4 (October ) will be a release candidate, and we'll GA a couple weeks after that. Depending on customer adoption/feedback that may change a bit

**Comment by kagkarlsson** [comment]
Yes, the documentation here has some minor errors: 
https://github.com/Azure/azure-sdk-for-java/tree/master/sdk/storage/azure-storage-blob#authenticate-with-azureidentity

**Comment by kagkarlsson** [comment]
Ok, thanks for the rough roadmap. I think I have to look at v8 then, because we are looking at production in October and not sure I want to depend on a preview-version

**Comment by rickle-msft** [comment]
@kagkarlsson Which version of the preview are you using? And when you say you can't use the code you shared, is that because it doesn't compile or it throws an error or doesn't behave as expected? Thanks for your help in this. 

Totally understandable. We will be on deck to help you upgrade should that ever be of interest to you and we will also be providing some resources in the repo to ease that process.
