### ISSUE TITLE
[QUERY] design discusson for multipart with filename and content-type

### ISSUE THREAD

**Issue by weidongxu-microsoft** [Azure/azure-sdk-for-java#38408]
[DocumentTranslation TypeSpec](https://github.com/Azure/azure-rest-api-specs/blob/main/specification/translation/Azure.AI.DocumentTranslation/main.tsp#L62-L66)

This multipart/form-date request involve 1 `document` file, 0 or more `glossary` files.

All of them must have a stream (file or other source) (required).
All of them can have a filename (optional).
All of them must have a content-type (required): `text/csv` or `text/tsv`.

PS: previous guide https://github.com/Azure/azure-sdk-for-java/issues/37488 (but it does not involve the choice of content-type)

**Comment by vikaspalaskar** [comment]
Here is list of current document content type supported by API.

1. "text/csv"
2. "text/html"
3. "text/x-markdown"
4. "text/markdown"
5. "text/plain"
6. "message/rfc822"
7. "application/x-mimearchive"
8. "multipart/related"
9. "application/vnd.openxmlformats-officedocument"
10. "application/vnd.openxmlformats-officedocument.presentationml.presentation"
11. "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet"
12. "application/vnd.openxmlformats-officedocument.wordprocessingml.document"
13. "application/vnd.ms-outlook"
14. "text/tab-separated-values"
15. "application/xliff+xml"

**Comment by weidongxu-microsoft** [comment]
Java would have class corresponding to `document` and `glossary ` -- `DocumentFileDetails` and `GlossaryFileDetails`.

They would have ctor with `BinaryData`, setter (optional) for `filename` and `contentType`. As default, `contentType` be `application/octet-stream` if not provided by user. For DocumentTranslation, it could be customized to what they require e.g. `text/plain`.

The multipart class would use `DocumentFileDetails` and `GlossaryFileDetails`, instead of mere `BinaryData`.

**Comment by weidongxu-microsoft** [comment]
Customer set's it here
https://github.com/Azure/autorest.java/blob/18f5f64682ec91bb3440027af50393b671d24764/typespec-tests/src/main/java/com/cadl/multipart/models/FormData.java#L136-L140

`##FileDetails`
https://github.com/Azure/autorest.java/blob/18f5f64682ec91bb3440027af50393b671d24764/typespec-tests/src/main/java/com/cadl/multipart/models/FileDetails.java

**Comment by weidongxu-microsoft** [comment]
0.13.1 released

sample PR https://github.com/Azure/azure-sdk-for-java/pull/38506/
(I am not sure whether the namespace is reviewed)
