### ISSUE TITLE
azure powerbi

### ISSUE THREAD

**Issue by Saritha2022** [Azure/azure-sdk-for-java#38427]
### Type of issue

Typo

### Description

[Enter feedback here]

### Page URL

https://learn.microsoft.com/en-us/java/api/overview/azure/power-bi-dedicated?view=azure-java-archive&viewFallbackFrom=azure-java-stable

### Content source URL

https://github.com/Azure/azure-docs-sdk-java/blob/master/docs-ref-services/archive/power-bi-dedicated.md

### Document Version Independent Id

64524bf5-7557-03a5-1ac0-a1ee171bc0ce

### Article author

@azure-sdk

### Metadata

* ID: e23de303-b57c-84c9-77d8-a5ef22b8cca2 
* Service: **powerbidedicated**

**Comment by joshfree** [comment]
@danieljurek could you take a quick peak?

**Comment by danieljurek** [comment]
Looks like this page was created by some automation in the past though it doesn't link to anything. I'll delete it so it becomes directed to the `preview` moniker where there is content - https://learn.microsoft.com/en-us/java/api/overview/azure/power-bi-dedicated?view=azure-java-preview

**Comment by danieljurek** [comment]
This is remvoed. Will be published in next live publish.
