### ISSUE TITLE
Long response times to send messages simultaneously with multiple ServiceBusSenderAsyncClient

### ISSUE THREAD

**Issue by filiphultgren** [Azure/azure-sdk-for-java#38430]
**Query/Question**
We have spring boot (reactor) applications that have servicebus connections to multiple queues. In each spring boot application instance, there are 2 instances of ServiceBusSenderAsyncClient that are connected to separate queues.

When sending one message to each queue simultaneously:

```
Mono.zip(serviceBusSenderAsyncClient1.sendMessage(myMessage), serviceBusSenderAsyncClient2.sendMessage(myMessage)) 
```
We see a weird behaviour that the first message takes the normal time to send (10-20ms). But the second send message operations takes 15-60 seconds to send. In average about 25 seconds. This case happens inconsistent throughout the day. But we see this behaviour about 10 times during one day. In context, there are about 100,000 messages sent during each day.

<img width="989" alt="servicebus-behaviour" src="https://github.com/Azure/azure-sdk-for-java/assets/31345536/7daad031-98d9-4985-8f2b-08f1142dce04">

Are there any limits on sending multiple messages simultaneously to different queues from one spring boot application? It seems that the other send message operations in the same sequence gets locked up. It's difficult to analyse this issue why this is happening. My gut feeling thinks that something happens in amqp/socket network layer in the spring boot application that one gets through, the rest gets locked and waits for a network retry (?).

We are using premium service bus.

***Why is this not a Bug or a feature Request?***
It might not be a bug if there are limitations on having multiple sender instances in one spring boot application.

**Setup (please complete the following information if applicable):**
 - OS: Docker eclipse-temurin:17-jdk
  - Library/Libraries: 
 com.azure:azure-messaging-servicebus:7.15.0
 org.springframework.boot:spring-boot-starter-parent:3.1.5
 
 **Information Checklist**
 Kindly make sure that you have added all the following information above and checkoff the required fields otherwise we will treat the issuer as an incomplete report
- [x] Query Added
- [x] Setup information Added

**Comment by joshfree** [comment]
@anuchandy could you please follow up with @filiphultgren

**Comment by filiphultgren** [comment]
Hi again, 
After some investigation it was discovered that this was due to low memory in a AKS node that made the node unavailable (memorypressure, diskpressure, pidpressure), freezing all pending operations for the pods within the node during that time.
