### ISSUE TITLE
[BUG] @Transient doesn't work in azure-spring-data-cosmos

### ISSUE THREAD

**Issue by Blackbaud-JasonBodnar** [Azure/azure-sdk-for-java#38449]
**Describe the bug**
Fields marked with `@Transient` should not be persisted when saving an entity.

**To Reproduce**

1. Create an entity. Annotate a field with `@Transient` (either `javax.persistence` or `org.springframework.data.annotation`).
2. Save it to the db.

***Code Snippet***

```
@Transient
private String base64EncodedImage;
```

**Expected behavior**
`base64EncodedImage` would not be saved in the db when the entity is saved.

**Setup (please complete the following information):**
 - OS: Linux
 - Library/Libraries: com.azure:azure-spring-data-cosmos:3.18.0
 - Java version: 11
 - Frameworks: Spring Boot

** Additional context**
We're pretty behind on our version of azure-spring-data-cosmos so please let me know if this has been fixed in newer versions.

**Information Checklist**
Kindly make sure that you have added all the following information above and checkoff the required fields otherwise we will treat the issuer as an incomplete report
- [x] Bug Description Added
- [x] Repro Steps Added
- [x] Setup information Added

**Comment by joshfree** [comment]
Hi @Blackbaud-JasonBodnar thanks for reaching out to us via this GitHub issue; someone from the `Cosmos` team will follow up shortly.

**Comment by kushagraThapar** [comment]
@Blackbaud-JasonBodnar thanks for raising this issue. It is not a bug, rather a feature which is not supported by spring-data-cosmos. We will put it in our backlog and will prioritize it. 
@TheovanKraay can you please take a look at this?

**Comment by kushagraThapar** [comment]
@trande4884 - FYI, for your visibility.

**Comment by TheovanKraay** [comment]
Support for `@Transient` was added in version 3.46.0 and 5.13.0, see PR https://github.com/Azure/azure-sdk-for-java/pull/39760 and https://github.com/Azure/azure-sdk-for-java/pull/40401.
