### ISSUE TITLE
[BUG] Creating blob client with "Account" SAS token fails on: Signature doesn't match.

### ISSUE THREAD

**Issue by HassanBadir** [Azure/azure-sdk-for-java#38467]
**Describe the bug**
I have a blob on azure storage that i want to download.

SAS tokens have 3 levels (service, container, blob), for our reasons we create Account\Service SAS token (meaning storage level), instead of specific blob SAS.
then we connect the blob URL to the SAS and send it to our product which downloads it.

this worked fine as long as we worked with python and simple "wget" downloaded the file.

Now moving this code to java, using blob Client ... we are facing this error, it creates a blobClient .. but on the download it fails on the error "Authentication Failed", "Signature doesn't match".

I have done my investigation, and found these couple findings: 
1- as you see in the code snippet, we create the blobClient with the full URL and that fails for me, if i separate them and the same SAS token seprately it works fine.

```
override fun build(blobUrl: String): BlobClientWrapper {
        val blobClientBuilder = AzureBlobClientBuilder().endpoint(blobUrl).**sasToken(sasToken)**

        return BlobClientWrapper(
            blobClient = blobClientBuilder.buildClient()
        )
    }
```
**Note:** it doesn't fail on creating the client ... but on the download.

2- i found this also: https://stackoverflow.com/questions/25038429/azure-shared-access-signature-signature-did-not-match , i tried adjusting it to "service" token didn't really work, just though i mention it to you.

generally i can adjust the code to work with separate token, but it would be really helpful if i can still use the full url instead, and why it's failing.

***Exception or Stack Trace***

com.azure.storage.blob.models.BlobStorageException: If you are using a StorageSharedKeyCredential, and the server returned an error message that says 'Signature did not match', you can compare the string to sign with the one generated by the SDK. To log the string to sign, pass in the context key value pair 'Azure-Storage-Log-String-To-Sign': true to the appropriate method call.
If you are using a SAS token, and the server returned an error message that says 'Signature did not match', you can compare the string to sign with the one generated by the SDK. To log the string to sign, pass in the context key value pair 'Azure-Storage-Log-String-To-Sign': true to the appropriate generateSas method call.
Please remember to disable 'Azure-Storage-Log-String-To-Sign' before going to production as this string can potentially contain PII.
Status code 403, "﻿<?xml version="1.0" encoding="utf-8"?><Error><Code>AuthenticationFailed</Code><Message>Server failed to authenticate the request. Make sure the value of Authorization header is formed correctly including the signature.
RequestId:84cf8d7d-701e-006b-64a9-4ee952000000
Time:2024-01-24T09:40:58.5458562Z</Message><AuthenticationErrorDetail>Signature fields not well formed.</AuthenticationErrorDetail></Error>"

**To Reproduce**

1- Create Account SAS token meaning on "Storage" level.
SAS token have 3 levels (service, container, blob) 

get a blob url on that storage and simply concat the account SAS to its ending.
 and create blobClient and try to download.

***Code Snippet***
```
override fun build(blobUrl: String): BlobClientWrapper {
        val blobClientBuilder = AzureBlobClientBuilder().endpoint(blobUrl)

        return BlobClientWrapper(
            blobClient = blobClientBuilder.buildClient()
        )
    }
```

```
blobClient.downloadToFileWithResponse(
                partFile.absolutePath,
                BlobRange(rangeStart),
                parallelTransferOptions,
                null,
                null,
                false,
                setOf(
                    StandardOpenOption.CREATE,
                    StandardOpenOption.READ,
                    StandardOpenOption.WRITE,
                    StandardOpenOption.TRUNCATE_EXISTING
                ),
                null,
                null
            )
```

**Expected behavior**
downloads the blob.

**Setup (please complete the following information):**
 - OS: windows ( not sure it's relevant )
 - IDE: IntelliJ
 - Library/Libraries: com.azure:azure-storage-blob:2.24.1 
 - Kotlin version: 1.7.0
 - Java version: 17

**Information Checklist**
Kindly make sure that you have added all the following information above and checkoff the required fields otherwise we will treat the issuer as an incomplete report
- [X] Bug Description Added
- [X] Repro Steps Added
- [X] Setup information Added

**Comment by joshfree** [comment]
@ibrahimrabab could you please take a look?

**Comment by ibrahimrabab** [comment]
Hi @HassanBadir 
Thanks for reaching out! Can you please provide the full endpoint URL with the SAS signature redacted? When I tried to reproduce this, it required me to enable permissions on service, container, and blob. Can you confirm that you are able to call download with only permission on the service level?

**Comment by HassanBadir** [comment]
Hey,

maybe i was misunderstood..

i create SAS on the Storage level, with permissions to "Object" in order to be able to download blobs.

meaning on storage i go to:
![image](https://github.com/Azure/azure-sdk-for-java/assets/37299319/0647bbcf-9b26-4e5f-9cd6-25c5863273db)

then create this SAS:
![image](https://github.com/Azure/azure-sdk-for-java/assets/37299319/47dc30ab-0d2f-4396-9d4e-efcd29f097e9)

and with this i can't create blobClient directly .. i must split the SAS from the blob, and pass them separately  as mentioned above:

```
  val blobClientBuilder = AzureBlobClientBuilder().endpoint(blobUrl).**sasToken(sasToken)**
```

**Comment by ibrahimrabab** [comment]
Hi @HassanBadir 
Apologies on not responding back on this earlier. I tested out the sas token generation as you did above, and the download calls work just fine for me only using `.endpoint()`. One thing I noticed in your code snippets is that you do not set `.containerName()` and `.blobName()` on the client builder. Are you doing that? If not, can you please set the container name and the blob name on the builder and try to make the download call again?

You should do the following:
BlobClientBuilder builder = new BlobClientBuilder()
            .endpoint("https://<accountname>.blob.core.windows.net/?sv=<sastoken>")
            .containerName("<containerName>")
            .blobName("<blobname>");
            
And after building the BlobClientBuilder, try making the download calls again. Let us know if it works! If not, we can further investigate.

**Comment by ibrandes** [comment]
Closed, no feedback was given after we provided our solution. Please re-open if the issue persists.
