### ISSUE TITLE
[FEATURE REQ] Ability to create Container Registry with zone redundancy

### ISSUE THREAD

**Issue by Brhett** [Azure/azure-sdk-for-java#38488]
**Is your feature request related to a problem? Please describe.**
We are trying to automate creating container registries with zone redundancy.  Currently, only `RegistryInner` can be leveraged to configure zone redundancy on creating a new container registry. But we don't want to expose `RegistryInner` to outside.

**Describe the solution you'd like**
What about adding an API in the `Registry.DefinitionState`? e.g.
```java
return containerRegistryManager.containerRegistries()
            .define(registryResourceName)
            .withRegion(Region.fromName(regionName))
            .withExistingResourceGroup(projectResourceGroupName)
            .withPremiumSku()
            .withRegistryNameAsAdminUser()
            .withZoneRedundancy()
            .disablePublicNetworkAccess()
            .createAsync();
```

**Describe alternatives you've considered**
Replicating the request as a simple HTTP request has been considered and is quite complex with all the headers. We discussed it was best if it came from the SDK.

**Additional context**
N/A

**Information Checklist**
Kindly make sure that you have added all the following information above and checkoff the required fields otherwise we will treat the issuer as an incomplete report
- [x] Description Added
- [x] Expected solution specified

**Comment by joshfree** [comment]
@lmolkova could you follow up?

**Comment by lmolkova** [comment]
@weidongxu-microsoft @XiaofeiCao could you please take a look (since it's related to the management client)

**Comment by weidongxu-microsoft** [comment]
fixed via https://github.com/Azure/azure-sdk-for-java/pull/38588
