### ISSUE TITLE
Do I need to close ServiceBusSenderClient instance after using

### ISSUE THREAD

**Issue by kensinzl** [Azure/azure-sdk-for-java#38487]
**Query/Question**
I am using `ServiceBusSenderClient` instance to send the message into the Azure Bus Service Queue.

1. After sending the message, do I need to close to the instance of `ServiceBusSenderClient`, eg: ServiceBusSenderClient.close(), if so, why? because I find there seems no need to close the `QueueClient` instance after sending a message to Queue Storage.

2. If I need to close the instance of `ServiceBusSenderClient`, how can I reopen it for the next usage?

3. Also ServiceBusSenderClient does not support returning the message ID after sending like what the `QueueClient` has

**Comment by anuchandy** [comment]
The ServiceBusSenderClient object is reusable, on which application can call send() API multiple times.
It is recommended to close the client as part of the application shutdown.

Storage Queue and service bus are services uses different protocols and has different use cases. 

https://learn.microsoft.com/en-us/azure/service-bus-messaging/service-bus-azure-and-service-bus-queues-compared-contrasted

There is no id available when sending to service bus, but only while receiving.

**Comment by kensinzl** [comment]
@anuchandy 

Thank you so much for your explanation.

just double confirm

- I used the ServiceBusSenderClient instance as an injection
- create a simple function which uses the above ServiceBusSenderClient instance to send the message, 
eg: sudo code

```
@Inject ServiceBusSenderClient instance;


public void sendMessageToAzure(String meg) {
    instance.sendMessage(meg);
    instance.close();
}
```

- so do you mean whenever hit the `sendMessageToAzure` I need to close the instance, but the ServiceBusSenderClient instance is reusable, I have no necessary to re-open it after close?

**Comment by anuchandy** [comment]
Hi @kensinzl, once you `close` an instance of `ServiceBusSenderClient`, you won't be able to use it further (i.e., you can't call `send` on the closed instance). What I meant earlier was, you can have a Sender instance in application’s global scope, but it should be closed when the application gets shutdown.
