### ISSUE TITLE
Random Block ID issue in Storage playback

### ISSUE THREAD

**Issue by sima-zhu** [Azure/azure-sdk-for-java#3849]
There are several tests () in TransferManagerTest failed in playback mode, because it appends a random block id in URL in src code. When playback, the URL with random id did not match any of in the json records. That's why it failed.

**Comment by sima-zhu** [comment]
Failed tests are now ignored in playback/record mode and only run in live mode.

**TransferManagerTest:**

- Upload single shot size

- Download file options

- Upload NRF (8 tests)

- Upload NRF chunked source (3 tests)

- Upload NRF headers (2 tests)

- Upload NRF metadata (2 tests)

- Upload NRF AC (6 tests)

- Upload NRF AC fail (5 tests)

- Upload NRF network error

**Comment by sima-zhu** [comment]
One solution we currently have is to have two playback clients: one deal with the random block id, one with the normal request.

**Comment by sima-zhu** [comment]
Just got updates from Harsha from JS. He said they have similar thing which ignored in their playback and record.

**Comment by kurtzeborn** [comment]
This only applies to v11 which we're not actively developing any more.
