### ISSUE TITLE
Tests failed in live mode

### ISSUE THREAD

**Issue by sima-zhu** [Azure/azure-sdk-for-java#3850]
Investigation in progress. 
The tests are not stable right now.

**Comment by sima-zhu** [comment]
https://dev.azure.com/azure-sdk/playground/_build/results?buildId=45590

The live tests are all passed.

The failure cannot reproduce every time. Will observe some time for now. 

The original codes have tests failure as well. 
https://dev.azure.com/azure-sdk/internal/_build/results?buildId=44662

**Comment by sima-zhu** [comment]
Tests:

- one failed test
https://dev.azure.com/azure-sdk/playground/_build/results?buildId=45809&view=ms.vss-test-web.build-test-results-tab

**Comment by sima-zhu** [comment]
https://dev.azure.com/azure-sdk/internal/_build/results?buildId=49416&view=ms.vss-test-web.build-test-results-tab&runId=1393628&resultId=100487&paneView=debug

**Comment by alzimmermsft** [comment]
All enabled tests are working in live mode in the track 2 SDK, closing this issue.
