### ISSUE TITLE
Azure SDK for Java: SupportTickets interface

### ISSUE THREAD

**Issue by TaijuYamashita** [Azure/azure-sdk-for-java#38523]
**Query/Question**
Since last year, I have been using the SupportTickets interface of Azure SDK for Java. Around the beginning of December 2023, I was able to obtain support ticket information using the following method. However, this year, errors have started to occur. What can be done to resolve this issue?

--code--
resourceID=/SUBSCRIPTIONS/[subscriptionID]/PROVIDERS/MICROSOFT.SUPPORT/SUPPORTTICKETS/[supportTicketsID] 
SupportTicketDetails details = manager.supportTickets().getById(resourceID);

--error--
Please check this file.
[エラーログ.log](https://github.com/Azure/azure-sdk-for-java/files/14079750/default.log)

**Setup (please complete the following information if applicable):**
java: java 11
library: com.azure.resourcemanager: 1.0.0-beta.2

 **Information Checklist**
 Kindly make sure that you have added all the following information above and checkoff the required fields otherwise we will treat the issuer as an incomplete report
- [x] Query Added
- [x] Setup information Added

**Comment by joshfree** [comment]
Hi @TaijuYamashita someone from the `resourcemanager` team will follow up shortly.

/cc @weidongxu-microsoft

**Comment by weidongxu-microsoft** [comment]
@TaijuYamashita 

Is this the Java package you use?
https://github.com/Azure/azure-sdk-for-java/tree/main/sdk/support/azure-resourcemanager-support#adding-the-package-to-your-product

Is the version 1.0.0-beta.2?

From the log you attached, it is the backend respond the 404
```
{"error":{"code":"ResourceNotFound","message":"Resource name 2312250060001913 does not exist","details":[]}}
```

We will need to involve backend to track this issue (and the SDK version would give us the api-version of the backend, [1.0.0-beta.2 is 2020-04-01](https://github.com/Azure/azure-sdk-for-java/blob/main/sdk/support/azure-resourcemanager-support/CHANGELOG.md#100-beta2-2023-01-19)).

**Comment by TaijuYamashita** [comment]
Thank you for commenting.

>Is this the Java package you use?
https://github.com/Azure/azure-sdk-for-java/tree/main/sdk/support/azure-resourcemanager-support#adding-the-package-to-your-product
Yes, it is.

>Is the version 1.0.0-beta.2?
Yes, it is.

>From the log you attached, it is the backend respond the 404
I know that the 404 means Resource not found.
Is there a mistake in the set of resource ID?
`resourceID=/SUBSCRIPTIONS/[subscriptionID]/PROVIDERS/MICROSOFT.SUPPORT/SUPPORTTICKETS/[supportTicketsID]`

**Comment by weidongxu-microsoft** [comment]
I think you can just call

`SupportTicketDetails details = manager.supportTickets().get(supportTicketsID);`

There is no need to make the resourceID.

---

Is it possible for you to check this same `[supportTicketsID]` via other means? E.g. Azure CLI

It would help to double confirm, whether it is something wrong in SDK (e.g. ID not correct), or backend (the resource is really not there).

BTW, is this `[supportTicketsID]` newly created? I've heard about some small delay on the resource create and resource retrieval due to backend, but that should typically in range of seconds.

**Comment by TaijuYamashita** [comment]
@weidongxu-microsoft 
thank you for your prompt response.

>There is no need to make the resourceID.

I see, but this documents say the id is resource id.(below)

> [SupportTicketDetails](https://azuresdkdocs.blob.core.windows.net/$web/java/azure-resourcemanager-support/1.0.0-beta.3/com/azure/resourcemanager/support/models/SupportTicketDetails.html) getById([String](https://docs.oracle.com/javase/8/docs/api/java/lang/String.html) id)
Get ticket details for an Azure subscription. Support ticket data is available for 18 months after ticket creation. If a ticket was created more than 18 months ago, a request for data might cause an error.
Parameters:
id - the resource ID.

[https://azuresdkdocs.blob.core.windows.net/$web/java/azure-resourcemanager-support/1.0.0-beta.3/com/azure/resourcemanager/support/models/SupportTickets.html#getById(java.lang.String)](url)

>Is it possible for you to check this same [supportTicketsID] via other means? E.g. Azure CLI

I checked support ticket and it exists.

**Comment by weidongxu-microsoft** [comment]
Yeah, they should be equivalent, just `get` takes the resource name, and `getById` takes the full resource ID.
https://azuresdkdocs.blob.core.windows.net/$web/java/azure-resourcemanager-support/1.0.0-beta.3/com/azure/resourcemanager/support/models/SupportTickets.html#get(java.lang.String)

The underly REST API is the same `/subscriptions/{subscriptionId}/providers/Microsoft.Support/supportTickets/{supportTicketName}`. So the response message says about `supportTicketName`, because this be one of the two path parameter REST API sends (and `subscriptionId` is unlikely to be wrong).

---

However, "2312250060001913" seems to be the SupportTicketId, not the SupportTicketName. Would it work if you call `get([SupportTicketName])`, where `[SupportTicketName]` be the string `c1840axxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxa5b101`?

---

Or whether this works?

```
            List<SupportTicketDetails> list = manager.supportTickets().list().stream()
                    .filter(ticket -> "2312250060001913".equals(ticket.supportTicketId()))
                    .collect(Collectors.toList());
```

**Comment by TaijuYamashita** [comment]
@weidongxu-microsoft 
>Yeah, they should be equivalent, just get takes the resource name, and getById takes the full resource ID.

I understand.

>The underly REST API is the same /subscriptions/{subscriptionId}/providers/Microsoft.Support/supportTickets/{supportTicketName}.

Checking Azure Portal's Activety Log, I thought resourceID is constructed as follows:
`resourceID = /subscriptions/{subscriptionId}/providers/Microsoft.Support/supportTickets/{supportTicketID}.`
But getById method worked successfully when I chenge {supportTicketID} to {supportTicketName}
`resourceID = /subscriptions/{subscriptionId}/providers/Microsoft.Support/supportTickets/{supportTicketName}.`

So I understand regardless of which method is used, supportTicketName is required.

By the way, It seems that the support ticket's name is the same as it's support ticket's ID until early December 2023, 
but from around the end of December 2023, it became defferrent.

**Comment by weidongxu-microsoft** [comment]
> So I understand regardless of which method is used, supportTicketName is required.

Yes, correct. The resourceID is constructed via resource name (`name` property of the resource), which is `supportTicketName` in this case.
https://github.com/Azure/azure-rest-api-specs/blob/main/specification/support/resource-manager/Microsoft.Support/stable/2020-04-01/support.json#L1022-L1026

> By the way, It seems that the support ticket's name is the same as it's support ticket's ID until early December 2023, but from around the end of December 2023, it became defferrent.

I see. So this likely explains why your API call works in 2023 but suddenly not work today.

**Comment by weidongxu-microsoft** [comment]
If you check portal, you should see the resourceID is not via `{supportTicketID}` (at present)

![image](https://github.com/Azure/azure-sdk-for-java/assets/53292327/5f91875f-3ac9-4d36-ae1c-b1887191afcf)

**Comment by TaijuYamashita** [comment]
@weidongxu-microsoft 
I understand what the problem is and what should be done to improve it.

I really appreciate all your support despite my poor English.
Thank you.
