### ISSUE TITLE
 Null filepath and URL in Azure OpenAI Response using chatCompletions

### ISSUE THREAD

**Issue by hind214875** [Azure/azure-sdk-for-java#38548]
**Describe the bug**
When querying Azure OpenAI with Cognitive Search integration, the expected filepath and URL within the citation responses are returning as null. The fieldsMapping configuration is intended to map a downloadable flag to the filepathField. However, despite this configuration, the response does not contain the expected values.

***Exception or Stack Trace***
![image](https://github.com/Azure/azure-sdk-for-java/assets/73963513/7024e065-9eb2-4094-9823-0f2e9e660c53)

**To Reproduce**
1.
![1](https://github.com/Azure/azure-sdk-for-java/assets/73963513/911d74dc-c31b-464a-94e3-7fde6ca4d82c)
2.
![2](https://github.com/Azure/azure-sdk-for-java/assets/73963513/370f3293-7b86-45b2-b328-9c7c937b1047)
3.
![33](https://github.com/Azure/azure-sdk-for-java/assets/73963513/b6c7d72d-90b1-4dcc-8a99-6d87e708682b)
4.Configure Azure OpenAI with Cognitive Search integration using the following fieldsMapping:
![3](https://github.com/Azure/azure-sdk-for-java/assets/73963513/d401c268-4f6a-48dc-8466-14d69ce683d1)
5.Perform a query against the Azure OpenAI service.
6.Inspect the citation response, observing that filepath and URL are null.

***Code Snippet***
![code](https://github.com/Azure/azure-sdk-for-java/assets/73963513/ac323a67-90e6-4047-a50f-804afcec42bb)

**Expected behavior**
The response from Azure OpenAI when using Cognitive Search should populate the filepath and URL fields, filePath true or false depende Downloadable and url the link of the document:

![image](https://github.com/Azure/azure-sdk-for-java/assets/73963513/98b7efae-8189-43a6-975e-e617f228f32e)

**Setup (please complete the following information):**
 - OS: Windows 10
 - IDE: IntelliJ IDEA 
 - Library/Libraries:com.azure:azure-ai-openai:1.0.0-beta.6
 - Java version: jdk "17.0.8"
 - Frameworks: Spring Boot

**Additional context**
- The issue persists regardless of the query used.
- All other response fields are populating as expected, only filepath and URL are affected.
- The configuration for fieldsMapping was expected to map these fields accordingly.

**Information Checklist**

- [ ] Bug Description Added
- [ ] Repro Steps Added
- [ ] Setup information Added

**Comment by joshfree** [comment]
Thanks for sharing this beta feedback @hind214875  -- @mssfang can you please follow up?

**Comment by mssfang** [comment]
Thank you for reporting this issue. @hind214875 
Can you try update pom dependency as below?

<dependencies>
   <dependency>
     <groupId>com.azure</groupId>
     <artifactId>azure-ai-openai</artifactId>
     <version>1.0.0-beta.6</version>
   </dependency>

   <dependency>
     <groupId>com.azure</groupId>
     <artifactId>azure-search-documents</artifactId>
     <version>11.6.0-beta.7</version>
     <exclusions>
         <exclusion>
             <groupId>com.azure</groupId>
             <artifactId>azure-core-serializer-json-jackson</artifactId>
         </exclusion>
     </exclusions>
   </dependency>
 </dependencies>

**Comment by hind214875** [comment]
Hi [mssfang](https://github.com/mssfang)! 
Thank you for your reply, but unfortunately it is still not working.

**Comment by mssfang** [comment]
> Hi [mssfang](https://github.com/mssfang)! Thank you for your reply, but unfortunately it is still not working.

Thanks for the try out. Is possible we can have a sample code that can reproduce this issue?

**Comment by mssfang** [comment]
Is possible we can have a sample code from your side that can use to reproduce the issue? 

> Hi [mssfang](https://github.com/mssfang)! Thank you for your reply, but unfortunately it is still not working.

**Comment by hind214875** [comment]
Hi [mssfang](https://github.com/mssfang)!

Sorry for the late replay, I actually tested yesterday again and this time it works i didn't change anything so i don't really know why it works now. Thank you for your help :)

**Comment by mssfang** [comment]
@hind214875 Glad to see that works. BTW, we have a new beta, [beta.7](https://mvnrepository.com/artifact/com.azure/azure-ai-openai) released that includes some breaking change and new features Text-to-Speech.
