### ISSUE TITLE
Azure blob storage filter blobs by its properties

### ISSUE THREAD

**Issue by ViswanathVeerappan** [Azure/azure-sdk-for-java#38579]
We have a use case where we are interested in filtering the blobs by its properties. Our use case is to pick up blobs for processing by its lease state say for example Available or Expired. If there were any blobs matching this criteria, we would assign it to a worker. We would like to get an idea, if this was even possible with the existing versions of the Java client library. 

FYI, The following are the library details used in my application,

com.azure azure-storage-blob 12.16.1 com.azure azure-core 1.28.0

Thanks,

Viswanath V

**Comment by joshfree** [comment]
Hi @ViswanathVeerappan someone from the `Storage` team will follow up with you shortly.  Thanks

**Comment by ViswanathVeerappan** [comment]
HI @joshfree, Just wanted to do a follow up on this? Are there any updates for me on this?

Thanks,

Viswanath V

**Comment by ibrahimrabab** [comment]
Hi @ViswanathVeerappan 
You can call BlobClient.getProperties() which will return all the properties for the given blob,
`BlobProperties properties = blobClient.getProperties();`
and from there you can do:
`LeaseStateType leaseType = properties.getLeaseState();`
This will return the type of lease on the blob. 
Here are the types of Leases:
https://github.com/Azure/azure-sdk-for-java/blob/main/sdk/storage/azure-storage-blob/src/main/java/com/azure/storage/blob/models/LeaseStateType.java

Let us know if this helped!

**Comment by ViswanathVeerappan** [comment]
Hi @ibrahimrabab, Our use case was to lookup or filter the blobs available by a specific property(for example, lease state). We were not looking to get the properties associated with a blob.

Currently, the library supports a couple of options out of the box,

1. listBlobs() => gives a paginated response of the blobs available in a container
2. findBlobsByTags() => gives a paginated response of the blobs available in a container based on the indexed tags mentioned in the query

Similar to the findBlobsByTags functionality, we are looking to see if there is an option to get a paginated response of the blobs in a container by its properties specifically lease state.

Thanks,

Viswanath V

**Comment by ibrahimrabab** [comment]
@ViswanathVeerappan 
Unfortunately, the only way to see a blob's lease state is by calling into its properties and checking for the lease state property. The SDK currently does not support an API that can only grab blobs based on the lease state. 

Please let us know if you have any more questions!
