### ISSUE TITLE
BlobStorageException.getErrroCode returns null

### ISSUE THREAD

**Issue by liuchang0520** [Azure/azure-sdk-for-java#38646]
**Describe the bug**
Caller was crashed when receiving a null returned value from `BlobStorageException.getErrroCode`.

**Expected behavior**
The caller expects `BlobStorageException.getErrroCode` returns a non-null `BlobErrorCode`.

**Version**
azureStorageBlob - com.azure:azure-storage-blob:12.12.0.

**Comment by alzimmermsft** [comment]
Thank you for filing this @liuchang0520.

Is it possible to include a stack trace or reproduction of this issue?

FYI @ibrahimrabab @ibrandes

**Comment by ibrahimrabab** [comment]
Hi @liuchang0520 
Please provide a code snippet of how you are producing this issue, as well as a stack error trace so that we can determine the issue you are seeing. Thanks!

**Comment by liuchang0520** [comment]
Thanks @ibrahimrabab @alzimmermsft . Please take a look at the attached stack trace. I've removed the upstream stack from our internal components.

`java.lang.NullPointerException: Cannot invoke "com.azure.storage.blob.models.BlobErrorCode.equals(Object)" because the return value of "com.azure.storage.blob.models.BlobStorageException.getErrorCode()" is null`. 

From our side, we might need to fix the logic to be `Object.equals(BlobErrorCode)`. Meanwhile I think `BlobStorageException.getErrorCode()` should not return null value.

**Comment by ibrahimrabab** [comment]
@liuchang0520 
It's hard to tell why this issue is occurring without seeing a code snippet of how you are producing this error. Can you post a code snippet showing us the reproducible behavior?

**Comment by liuchang0520** [comment]
@ibrahimrabab The following is the code snippet.
```
          try {
                   ......
            } catch (BlobStorageException be) {
                if (be.getErrorCode().equals(BlobErrorCode.BLOB_NOT_FOUND))
                    .........
                }
            }
```

**Comment by ibrahimrabab** [comment]
@liuchang0520 
Can you show us what operations you are doing within the try block?

**Comment by liuchang0520** [comment]
@ibrahimrabab Sorry for the confusion.
We are doing `com.azure.storage.blob.BlobClient.delete()`  inside the try block

**Comment by ibrahimrabab** [comment]
@liuchang0520 
You are using an old version of azure blob storage which may be the issue. Can you try upgrading your version to at least 12.19.0? That way you can also leverage BlobClient.deleteIfExists(), which deletes a blob only if it exists and will not throw an exception.
