### ISSUE TITLE
[FEATURE REQ] implement custom timeout in the msi auth token helper

### ISSUE THREAD

**Issue by praries880** [Azure/azure-sdk-for-java#3864]
Add functionality similar to https://github.com/Azure/msrestazure-for-python/pull/131/files in :
https://github.com/Azure/azure-sdk-for-java/tree/master/authorization/msi-auth-token-provider-jar

**Comment by arluca** [comment]
@praries880 : Thanks for getting this going! Is there an ETA for when this will be released?

**Comment by yaohaizh** [comment]
@ChenTanyi  Could you help take a look at this issue?  @arluca Could you be more specific about the requirement here since @praries880 currently is not working the azure SDK. Any context would be helpful.
