### ISSUE TITLE
[BUG] Spring Cloud Azure 5.9.0 update requires JDK 21

### ISSUE THREAD

**Issue by nagyesta** [Azure/azure-sdk-for-java#38661]
**Describe the bug**
Updating to Spring Cloud Azure 5.9.0 caused build failure complaining about the class version. I wasn't able to find any information about the JDK 21 requirement in the release so I assume this is not intentional. Please kindly let me know in case I missed something! Thank you!

***Exception or Stack Trace***
```
    Caused by: java.lang.UnsupportedClassVersionError: com/azure/spring/cloud/autoconfigure/implementation/context/AzureGlobalConfigurationEnvironmentPostProcessor has been compiled by a more recent version of the Java Runtime (class file version 65.0), this version of the Java Runtime only recognizes class file versions up to 61.0
    	at java.base/java.lang.ClassLoader.defineClass1(Native Method)
    	at java.base/java.lang.ClassLoader.defineClass(ClassLoader.java:1017)
    	at java.base/java.security.SecureClassLoader.defineClass(SecureClassLoader.java:150)
```

**To Reproduce**
1. Check out https://github.com/nagyesta/lowkey-vault-example/commit/f14417508a6cb433636455f9b115c21fa89e59d7
2. Build using JDK 17
3. Observe errors

***Code Snippet***
N/A

**Expected behavior**
The project is working with JDK 17

**Screenshots**
N/A

**Setup (please complete the following information):**
 - OS: any
 - IDE: any
 - Library/Libraries: 
   - "com.azure.spring:spring-cloud-azure-starter-keyvault-secrets:5.9.0"
   - "com.azure.spring:spring-cloud-azure-starter-keyvault:5.9.0"
 - Java version: 17 (below 21)
 - App Server/Environment: any
 - Frameworks: Spring Boot

**Additional context**
Affects this PR: https://github.com/nagyesta/lowkey-vault-example/pull/274

**Information Checklist**
Kindly make sure that you have added all the following information above and checkoff the required fields otherwise we will treat the issuer as an incomplete report
- [x] Bug Description Added
- [x] Repro Steps Added
- [x] Setup information Added

**Comment by OleksandrShkurat** [comment]
Meanwhile, Microsoft Azure Functions do not support Java 21 :)

**Comment by joshfree** [comment]
@saragluna @vcolin7 could you please investigate this apparent regression (requiring JDK 21 to run)?

**Comment by vcolin7** [comment]
Yes, I'm looking into this.

**Comment by saragluna** [comment]
Sorry for the inconvenience, we will release a hotfix ASAP.

**Comment by Netyyyy** [comment]
Spring Cloud Azure 5.9.1 now is released

**Comment by OleksandrShkurat** [comment]
Looks like 5.9.1 works well. Thank you
