### ISSUE TITLE
Simplify client builder pattern

### ISSUE THREAD

**Issue by JonathanGiles** [Azure/azure-sdk-for-java#3871]
**Important**: This is a change that can happen *after* the first preview release. It does **not** need to happen before then. Please don't stress :-) Also, please don't start working on this until a more formal 'go-ahead' is given - let's take a short while to discuss this and reach consensus.

Today the Java spec says for each service client we should have a service client builder. In the case of the application configuration client, this means we have `ConfigurationClient` and `ConfigurationClientBuilder` for sync clients, and `ConfigurationAsyncClient` and `ConfigurationAsyncClientBuilder` for async clients. This made sense back when we thought we would have differences in our http pipeline for sync and async. More recently however we have reassured ourselves that implementing the sync API using sync-over-async is not the performance concern we thought it was, and therefore the need for separate http pipelines is no longer considered important. This is made abundantly clear if one were to inspect the `ConfigurationClientBuilder`, which simply defers all logic to an internal instance of the `ConfigurationAsyncClientBuilder`.

To simplify the lives of our users, and also lessen the amount of code we own, I propose that we do the following:

1. We change our client classes to remove the `builder()` methods.
2. We only have one builder for sync and async client. In the case of `ConfigurationClient` / `ConfigurationAsyncClient`, we would simply have a `ConfigurationClientBuilder`.
3. We introduce a public no-args constructor for the `ConfigurationClientBuilder` class, rather than a public static `builder()` method.
4. We have a `buildClient()` terminal method for returning a sync client, and a `buildAsyncClient()` terminal method for returning an async client (instances of `ConfigurationClient` and `ConfigurationAsyncClient`, respectively).

Before these changes, the general pattern would have been:

```java
ConfigurationClient syncClient = ConfigurationClient.builder()
    .endpoint(…)
    .build();
ConfigurationAsyncClient asyncClient = ConfigurationAsyncClient.builder()
    .endpoint(…)
    .build();
```

After these changes, the general pattern will change to be:

```java
ConfigurationClient syncClient = new ConfigurationClientBuilder()
    .endpoint(…)
    .buildClient();
ConfigurationAsyncClient asyncClient = new ConfigurationClientBuilder()
    .endpoint(…)
    .buildAsyncClient();  // note the buildAsyncClient for the async client
```

- [x] AppConfiguration
- [ ] EventHubs
- [ ] Identity
- [ ] KeyVault
- [x] Storage
  - [x] Blob
  - [x] File
  - [x] Queue

// cc @mayurid @joshfree

**Comment by rickle-msft** [comment]
This makes sense to me.

**Comment by JonathanGiles** [comment]
@hemanttanwar will be taking lead on this work - keep an eye out for pull requests from him. If you have any feedback / suggestions, please eagerly provide them to him (and me) ASAP.

**Comment by hemanttanwar** [comment]
appconfig, keyvault PR :  https://github.com/Azure/azure-sdk-for-java/pull/4220

**Comment by joshfree** [comment]
@hemanttanwar PTAL

**Comment by hemanttanwar** [comment]
@alzimmermsft   This is an old issue. And  few months ago, we were waiting on storage team to implement this.
 
Looking at current code base, this looks like complete.
Want to make sure you are also onboard with closing this issue ?

**Comment by alzimmermsft** [comment]
This has been completed in the Storage clients and their builders.
