### ISSUE TITLE
[BUG] Additional delay in requests when specifying RequestRetryOptions.tryTimeout for QueueServiceClient

### ISSUE THREAD

**Issue by dennyac** [Azure/azure-sdk-for-java#38722]
**Describe the bug**
Since azure-storage-queue version 12.18.0 ([PR - Queues Sync Stack Integration](https://github.com/Azure/azure-sdk-for-java/pull/35031)), we are noticing elevated latencies when interacting with Azure Queues. On deeper investigation, we noticed that there is a delay equivalent to the specified RequestRetryOptions.tryTimeout duration when using the synchronous client. In [RequestRetryPolicy](https://github.com/Azure/azure-sdk-for-java/blob/main/sdk/storage/azure-storage-common/src/main/java/com/azure/storage/common/policy/RequestRetryPolicy.java), after making the synchronous http request, a Thread.sleep() is issued with the tryTimeout duration over [here](https://github.com/Azure/azure-sdk-for-java/blob/main/sdk/storage/azure-storage-common/src/main/java/com/azure/storage/common/policy/RequestRetryPolicy.java#L263) (On the async path we call Mono.timeout() which should be fine). So, for the synchronous client, if we set a tryTimeout of 2s, we wait for 2s after making the synchronous http request.

This [PR](https://github.com/Azure/azure-sdk-for-java/pull/38724) should fix the issue

***Exception or Stack Trace***
NA

**To Reproduce**
Run the following code using azure-storage-queue version 12.18.0 - 
```
RequestRetryOptions requestRetryOptions =
        new RequestRetryOptions(RetryPolicyType.EXPONENTIAL, 5, Duration.ofSeconds(5),
            Duration.ofSeconds(1), Duration.ofSeconds(5), null);

    QueueServiceClient queueServiceClient = new QueueServiceClientBuilder()
        .connectionString(CONN_STRING)
        .retryOptions(requestRetryOptions).buildClient();

    // Each of these requests should take approx 5 seconds (RequestRetryOptions.tryTimeout value)
    QueueClient client = queueServiceClient.createQueue("test-queue");
    client.sendMessage("test Message");
    client.receiveMessages(1);
```

***Code Snippet***

https://github.com/Azure/azure-sdk-for-java/blob/main/sdk/storage/azure-storage-common/src/main/java/com/azure/storage/common/policy/RequestRetryPolicy.java#L263

**Expected behavior**
Should wrap the synchronous http call with a timeout

**Screenshots**

**Setup (please complete the following information):**
 - OS: macOS Sonoma
 - IDE: IntelliJ
 - Library/Libraries: com.azure:azure-storage-queue:12.18.0, com.azure:azure-storage-common:12.22.0
 - Java version: 11
 - App Server/Environment: Jetty
 - Frameworks: Dropwizard

If you suspect a dependency version mismatch (e.g. you see `NoClassDefFoundError`, `NoSuchMethodError` or similar), please check out [Troubleshoot dependency version conflict article](https://aka.ms/azsdk/java/dependency/troubleshoot) first. If it doesn't provide solution for the problem, please provide:
- verbose dependency tree (`mvn dependency:tree -Dverbose`)
- exception message, full stack trace, and any available logs

**Additional context**

**Information Checklist**
Kindly make sure that you have added all the following information above and checkoff the required fields otherwise we will treat the issuer as an incomplete report
- [x] Bug Description Added
- [x] Repro Steps Added
- [x] Setup information Added

**Comment by dennyac** [comment]
This https://github.com/Azure/azure-sdk-for-java/pull/38724 should fix the issue

**Comment by ibrahimrabab** [comment]
https://github.com/Azure/azure-sdk-for-java/pull/38724
PR has been merged.
