### ISSUE TITLE
[BUG] Aggregate javadocs not updated

### ISSUE THREAD

**Issue by srnagar** [Azure/azure-sdk-for-java#3874]
**Describe the bug**
Azure SDK Javadocs hosted at https://azuresdkartifacts.blob.core.windows.net/azure-sdk-for-java/staging/apidocs/index.html are not updated since 4th June. 

***Exception or Stack Trace***
Add the exception log and stack trace if available
N/A

**To Reproduce**
Go the above link and view the page source. The page was generated on `Tue Jun 04 10:18:40 UTC 2019`. Note that yesterday's updated javadocs are generated and every client library's apidocs is accessible under a different URL:

For e.g. Key Vault: https://azuresdkartifacts.blob.core.windows.net/azure-sdk-for-java/staging/azure-keyvault-keys/apidocs/index.html
Azure core: https://azuresdkartifacts.blob.core.windows.net/azure-sdk-for-java/staging/azure-core/apidocs/index.html

***Code Snippet***
Add the code snippet that causes the issue.
N/A

**Expected behavior**
Latest javadocs should be generated and uploaded to the original apidocs link after each release.

**Screenshots**
![image](https://user-images.githubusercontent.com/51379715/59295073-aae90a80-8c37-11e9-8a04-7d818923ea02.png)

**Setup (please complete the following information):**
 - OS: Any
 - IDE : N/A
 - Version of the Library used: N/A

**Additional context**

**Information Checklist**
Kindly make sure that you have added all the following information above and checkoff the required fields otherwise we will treat the issuer as an incomplete report
- [x] Bug Description Added
- [x] Repro Steps Added
- [ ] Setup information Added

**Comment by JonathanGiles** [comment]
I've found the issue. Working on PR now.

**Comment by srnagar** [comment]
Javadocs are updated as expected - https://azuresdkartifacts.blob.core.windows.net/azure-sdk-for-java/staging/apidocs/index.html

Fixed with PR - https://github.com/Azure/azure-sdk-for-java/pull/3893
