### ISSUE TITLE
Predefined environment variables for credentials

### ISSUE THREAD

**Issue by dhatri308** [Azure/azure-sdk-for-java#38762]
Hi, 
I would like to know if there are any predefined environment variables that we can use to configure credentials.
For example, aws sdk for java has AWS_ACCESS_KEY_ID, AWS_SECRET_ACCESS_KEY, and AWS_SESSION_TOKEN.
Thanks.

**Comment by joshfree** [comment]
@billwert could you help @dhatri308 with their question?

**Comment by billwert** [comment]
Hello @dhatri308! You can find our reference for environment variables [here](https://learn.microsoft.com/en-us/java/api/overview/azure/identity-readme?view=azure-java-stable#environment-variables). These are useful when using the [`EnvironmentCredential`](https://learn.microsoft.com/en-us/java/api/com.azure.identity.environmentcredential?view=azure-java-stable). That credential is part of the credential chain in [`DefaultAzureCredential`](https://learn.microsoft.com/en-us/java/api/com.azure.identity.defaultazurecredential?view=azure-java-stable) which may also be useful to you.

Please let me know if you have other questions.
