### ISSUE TITLE
[QUESTION][COSMOS][SPARK] Support Spark version 3.5

### ISSUE THREAD

**Issue by leoeareis** [Azure/azure-sdk-for-java#38795]
**Question**
Do you have any plan or schedule to support Spark version 3.5 in azure-cosmos-spark sdk?

I'm raising this question because we are planning to update our data processing application to use Databricks version 14 and this version of Databricks require Spark 3.5, that isn't support by azure-cosmos-spark sdk.

Thanks!

**Comment by joshfree** [comment]
Hi @leoeareis someone from the `Cosmos` team will follow up with you shortly

**Comment by FabianMeiswinkel** [comment]
Hi @leoeareis, the Databricks LTS for Spark 3.5 has been published on Feb. 1st. We usually try to add support within 4-8 weeks after LTS has been published. So sometime in March we will definitely have support for Spark 3.5 as well.

**Comment by leoeareis** [comment]
Perfect! Thanks @FabianMeiswinkel, we will wait to go ahead with our updates.

**Comment by leoeareis** [comment]
Hi @FabianMeiswinkel, do you have any updates about that?

**Comment by kushagraThapar** [comment]
@leoeareis this is currently in development and will be shipped sometime by April end. Apologies for the delay.

**Comment by leoeareis** [comment]
Good to know @kushagraThapar , thanks for the update!

**Comment by leoeareis** [comment]
Thanks for the library update @kushagraThapar @FabianMeiswinkel. I will close this issue :+1:
