### ISSUE TITLE
Storage Track 2 ongoing issues

### ISSUE THREAD

**Issue by jianghaolu** [Azure/azure-sdk-for-java#3879]
## Core
- [ ] eTag property has quotes after deserialization

## AutoRest
- [x] AutoRest still generates withers in some models

## Storage sdk
- [x] sync upload has incorrect ByteBuffer handling (fix drafted)

**Comment by sima-zhu** [comment]
ErrorCode:
There is no CONTAINER_ALREADY_EXISTS

ContainerClient:
Can not redefine the httpPipeline

**Comment by sima-zhu** [comment]
One feedback:
I cannot check response status from create and delete API.

**Comment by jianghaolu** [comment]
> 
> 
> One feedback:
> I cannot check response status from create and delete API.

This is known and for now we skip those checks.
