### ISSUE TITLE
[FEATURE REQ] DeleteOptions on Public Ip Address

### ISSUE THREAD

**Issue by jloisel** [Azure/azure-sdk-for-java#38806]
It's currently not possible to set DeleteOptions on a public ip address through the SDK, when creating it:

```java
    final PublicIpAddress.DefinitionStages.WithCreate publicIp = publicIps
      .define(name)
      .withRegion(region)
      .withExistingResourceGroup(resourceGroup)
      .withoutLeafDomainLabel()
      .withoutReverseFqdn()
      .withSku(STANDARD)
      .withDynamicIP();
```

Would be useful to have it (as disk / network interfaces on a VM), to allow deleting the public ip automatically when the vm is deleted. As of now, we need to do this manually which is cumbersome.

**Comment by joshfree** [comment]
Thanks for filing this request, @jloisel.  @weidongxu-microsoft could you help triage this

**Comment by weidongxu-microsoft** [comment]
@XiaofeiCao Do we know whether network RP behave correctly on this (delete IP address when delete VM)?

We can have Hong try it.

**Comment by XiaofeiCao** [comment]
According to my knowledge, deleteOption is only effective on `NetworkInterface`'s `PublicIpAddress` property, not `PublicIpAddress` or `VirtualMachine` itself.
@v-hongli1 Would you help try whether deleteOption works on `PublicIpAddress`?

**Comment by v-hongli1** [comment]
@XiaofeiCao 
1. I tried to fix the `azure-resourcemanager-network` interface and tested it and found that the `backend` does not support the `deleteOption` parameter and does not return the default settings.
The test result following as:
[PublicIPAccessTests.testCreateIPAccessWithDeleteOptionDelete.json](https://github.com/Azure/azure-sdk-for-java/files/14327901/PublicIPAccessTests.testCreateIPAccessWithDeleteOptionDelete.json)
2. now the `deleteOption` is also not supported on the portal.

**Comment by XiaofeiCao** [comment]
@v-hongli1 Got it. The deleteOption may not be visible in the `PublicIpAddress`'s properties, but it may **ACTUALLY** take effect.
Would you help confirm whether this deleteOption takes effect when deleting the VM that it attaches to(though if I remembered correctly, it does not)?

**Comment by v-hongli1** [comment]
@XiaofeiCao 
Regardless of whether `.withPrimaryNetworkInterfaceDeleteOptions(DeleteOptions.DELETE)` needs to be loaded when creating a virtual machine, `Public IP Address` will not be removed when the VM is removed.

**Comment by weidongxu-microsoft** [comment]
It is in `PublicIpAddress` https://github.com/Azure/azure-sdk-for-java/blob/main/sdk/resourcemanager/azure-resourcemanager-network/src/main/java/com/azure/resourcemanager/network/fluent/models/PublicIpAddressInner.java#L497-L499

But it does not have effect, then it may not be supported yet (or have bug in backend).

Could you try this on portal and see if this deletes IpAddress when delete VM?

![image](https://github.com/Azure/azure-sdk-for-java/assets/53292327/f8172b88-84fb-4710-98f8-8bffab66b263)

If yes, check the resource create by Portal.

**Comment by weidongxu-microsoft** [comment]
@XiaofeiCao Do you aware any other option that may help user delete the IpAdress with the VM?

**Comment by XiaofeiCao** [comment]
My experience is that the PublicIpAddress deleteOption is in `NetworkInterface` resource. 

There's also a potential backend bug: If `PublicIpAddress` deleteOption is not set when first attached to `NetworkInterface`(whether using RP's API or deployment template), it'll always be null, regardless of future updates(luckily Databricks has set deleteOption in their create deployment template)... Our SDK didn't set this property, so even update won't work. 

For above reason, I'm afraid for now we'll have to wait for the feature to be added.

**Comment by XiaofeiCao** [comment]
@jloisel Due to service implementation limitation, the deleteOption should be set on the NetworkInterface that the PublicIpAddress is attached to. 
Here's how to set PublicIpAddress delete option in NetworkInterface with latest 2.40.0 SDK:
```java
// create nic with PublicIpAddress delete option
NetworkInterface nic = networkManager.networkInterfaces()
  .define(generateRandomResourceName("nic-", 15))
  .xx()
  .withNewPrimaryPublicIPAddress()
  .withPrimaryPublicIPAddressDeleteOptions(DeleteOptions.DELETE) // set primary publicIpAddress deleteOptions
  .create();

// update delete option
nic.update()
  .withPrimaryPublicIPAddressDeleteOptions(DeleteOptions.DELETE)
  .apply();
```
