### ISSUE TITLE
Publish JavaDocs from nightly build to github.io

### ISSUE THREAD

**Issue by kurtzeborn** [Azure/azure-sdk-for-java#3881]
Once @srnagar is able to fix the JavaDocs issues (tracked in this issue: https://github.com/Azure/azure-sdk-for-java/issues/3874) we should make the following updates to the pipeline:
- Publish the JavaDocs artifacts to github.io like we do for Python already
- Update the java pipelines to fail if JavaDocs are not generated

**Comment by JonathanGiles** [comment]
When this is done, please update the JavaDoc link in this HTML file: https://github.com/Azure/azure-sdk-for-java/blob/master/eng/code-quality-reports/src/main/resources/index.html
