### ISSUE TITLE
In ContainerServiceManager, are some operations missing on KubernetesClusters?

### ISSUE THREAD

**Issue by agateaux** [Azure/azure-sdk-for-java#38836]
**Query/Question**
I'm wondering if I use correctly the KubernetesClusters resource.

```
var clusters = ContainerServiceManager
				.authenticate(clustersClientConfig.credential(), clustersClientConfig.azureProfile())
				.kubernetesClusters();
```

1st question
When defining a cluster (interface `KubernetesCluster` and class `KubernetesClustersImpl`)

```
var cluster = kubernetesClusters.define(name)
				.withRegion(region)
				.withExistingResourceGroup(resourceGroupName)
				.withVersion(version)
				.withSystemAssignedManagedServiceIdentity()
				.withDnsPrefix(name.toLowerCase())
				.withTags(tags);
```

I don't see any `withSku`. Is there a way to define the SKU like in `ManagedClusterInner` line 96?

2nd question:
When updating an existing cluster, there is no way to upgrade the kubernetes version, in:

```
kubernetesCluster.update()
                                .withoutAgentPool(agentPool)
				.applyAsync();
```

We should have a `withNewKubernetesVersion`, am I wrong?

***Why is this not a Bug or a feature Request?***
I don't know for now, maybe it's a feature request, or a better documentation.

**Setup (please complete the following information if applicable):**
 - OS: Linux Ubuntu
 - IDE: Eclipse
 - Library/Libraries: com.azure.resourcemanager:azure-resourcemanager-containerservice:2.35.0
 
 **Information Checklist**
 Kindly make sure that you have added all the following information above and checkoff the required fields otherwise we will treat the issuer as an incomplete report
- [x] Query Added
- [x] Setup information Added

**Comment by joshfree** [comment]
@weidongxu-microsoft could you follow up with @agateaux

**Comment by weidongxu-microsoft** [comment]
@agateaux Thanks for the report. This part of the code is handwritten. Hence, sometimes it lags behind what backend offers.

We will add the way to set SKU, as well as e.g. `withKubernetesVersion` to set/update version.

**Comment by agateaux** [comment]
Thanks.
For the creation, the definition stage already supports the 'withVersion', to specify the Kubernetes version.
That's just for the update, the update stage doesn't offer this feature.

**Comment by XiaofeiCao** [comment]
PR merged: https://github.com/Azure/azure-sdk-for-java/pull/39110

2.37.0 will be around mid March.

**Comment by agateaux** [comment]
Thank you

**Comment by XiaofeiCao** [comment]
@agateaux 2.37.0 released. Let us know if it works for you.
