### ISSUE TITLE
[BUG] mgmt storage, exception when `withExistingUserAssignedManagedServiceIdentity` and `withEncryptionKeyFromKeyVault` are both present

### ISSUE THREAD

**Issue by XiaofeiCao** [Azure/azure-sdk-for-java#38854]
### 1. `withExistingUserAssignedManagedServiceIdentity` + `withEncryptionKeyFromKeyVault` = error
code: 

```java
this.client.storageAccounts().getById(storageAccountId)
.update()
.withEncryptionKeyFromKeyVault(vaultUri, keyName, keyVersion)
.withExistingUserAssignedManagedServiceIdentity(managedIdentity)
.apply();

```

Exception message: 
```
Missing pre-requisites to enable EncryptionAtRest/Customer Managed Key for this storage account
```

Reason: Extra user assigned identity config is required for `withEncryptionKeyFromKeyVault` for user-assigned identity.
```json
"encryption": {
      "services": { "blob": { "enabled": true }, "file": { "enabled": true } },
      "keySource": "Microsoft.Keyvault",
      "keyvaultproperties": {
        "keyname": "key1",
        "keyvaulturi": "https://test2024022102.vault.azure.net",
        "keyversion": ""
      },
      "identity": { // extra config needed
        "userAssignedIdentity": "/subscriptions/REDACTED/resourceGroups/rg-xiaofei/providers/Microsoft.ManagedIdentity/userAssignedIdentities/test-storage-account-msi"
      }
    }
```

### 2. We can't update user-assigned identity for CMK encryption using user-assigned identity.
code:

```java
// This storage account is CMK encryption set in Azure Portal.
StorageAccount storageAccount = storageManager.storageAccounts().getByResourceGroup();

// Below code throws exception complaining "Too many identities specified for this resource."
storageAccount.update()
    .withUserAssignedManagedIdentity(identity)
    .apply();
           
```

Reason: ~~Unsure yet.~~ Portal can successfully update. Checked the request payload, found nothing significantly different..
Well, turns out that there do exist a difference. The `id` property from `msiManager.identities().getByResourceGroup` and Portal are
* /subscriptions/REDACTED/resourcegroups/rg-xiaofei/providers/Microsoft.ManagedIdentity/userAssignedIdentities/test-storage-account-msi (msiManager)
* /subscriptions/REDACTED/resourceGroups/rg-xiaofei/providers/Microsoft.ManagedIdentity/userAssignedIdentities/test-storage-account-msi (Portal)

Notice the `resourceGroup` vs `resourcegroup`... Backend considered these are two different user-assigned identities, thus `TooManyIdentities` exception. We can solve this by adding an override `withExistingUserAssignedManagedServiceIdentity(identityId)` to let user pass in identityId directly.

**Comment by XiaofeiCao** [comment]
We may need to support the full MMK and CMK use cases.
<img width="518" alt="Screenshot 2024-02-22 at 2 34 51 PM" src="https://github.com/Azure/azure-sdk-for-java/assets/92354331/4edca30c-077e-45c0-bb9d-ddf958ff793e">


### Use cases
#### 1. Create storage account with CMK
```java
StorageAccount storageAccount = storageManager
            .storageAccounts()
            .define(saName)
            .withRegion(Region.US_EAST)
            .withExistingResourceGroup(rgName)
            .withExistingUserAssignedManagedServiceIdentity(defaultIdentity)
            .withEncryptionFromKeyVault(vaultUri, key, version)
            .create();
```

#### 2. Update existing storage account from MMK to CMK
```java
StorageAccount storageAccount = storageManager
            .storageAccounts()
            .define(saName)
            .withRegion(Region.US_EAST)
            .withExistingResourceGroup(rgName)
            .create();

storageAccount.update()
            .withExistingUserAssignedManagedServiceIdentity(defaultIdentity)
            .withEncryptionFromKeyVault(vaultUri, key, version)
            .apply();
```

#### 3. Update existing storage account's CMK
##### 3.1 From system-assigned to user-assigned, and vice-versa. After the update, StorageAccount's identity type will be SYSTEM_AND_USER_ASSIGNED.
```java
StorageAccount storageAccount = storageManager
            .storageAccounts()
            .define(saName)
            .withRegion(Region.US_EAST)
            .withExistingResourceGroup(rgName)
            .withSystemAssignedManagedServiceIdentity()
            .withEncryptionFromKeyVault(vaultUri, key, version)
            .create();

// from system-assigned to user-assigned
storageAccount.update()
            .withEncryptionFromKeyVault(vaultUri, key, version)
            .withExistingUserAssignedManagedServiceIdentity(identity)
            .apply();

// from user-assigned to system-assigned(I'm not able to find a way to express this using existing interfaces)
storageAccount.update()
            .withEncryptionFromKeyVault(vaultUri, key, version)
            .withSystemAssignedManagedServiceIdentity() // maybe we do something in `withSystemAssignedManagedServiceIdentity`?
            .apply();
```
##### 3.2 From one user-assigned to another user-assigned. Also, this one's tricky.
```java
StorageAccount storageAccount = storageManager
            .storageAccounts()
            .define(saName)
            .withRegion(Region.US_EAST)
            .withExistingResourceGroup(rgName)
            .withEncryptionFromKeyVault(vaultUri, key, version)
            .withExistingUserAssignedManagedServiceIdentity(identity1)
            .create();

storageAccount.update()
            .withEncryptionFromKeyVault(vaultUri, key, version)
            .withExistingUserAssignedManagedServiceIdentity(identity2) // maybe we do something in `withExistingUserAssignedManagedServiceIdentity`?
            .apply();
```

#### 4. From CMK to MMK. Currently we can't do this.
```java
StorageAccount storageAccount = storageManager
            .storageAccounts()
            .define(saName)
            .withRegion(Region.US_EAST)
            .withExistingResourceGroup(rgName)
            .withEncryptionFromKeyVault(vaultUri, key, version)
            .withExistingUserAssignedManagedServiceIdentity(identity1)
            .create();

storageAccount.update()
            .withEncryptionFromStorage() // MMK
            .apply();
```

**Comment by weidongxu-microsoft** [comment]
LGTM

We do want user explicitly put the `identity` or `identity id` when setting the encryption.

question:
- does storage account only allow 1 user-assigned managed identity? (on 3.2, I didn't see a withoutUserAssigned)
- `withEncryptionFromStorage` would be the default to storage account, correct?

**Comment by weidongxu-microsoft** [comment]
The casing on the ID seems to be a backend bug to me...

**Comment by XiaofeiCao** [comment]
> does storage account only allow 1 user-assigned managed identity? (on 3.2, I didn't see a withoutUserAssigned)

Yeah, seems so. Updated the use case. Portal and CLI automatically does the `without` for user if it detects the user-assigned identity has changed. We'll probably not do this, in case they allow somehow.

> withEncryptionFromStorage would be the default to storage account (it always encrypted), correct?

Correct.

I'll let them know the case-sensitive case.

**Comment by weidongxu-microsoft** [comment]
Agree. We'd better have user explicitly do the "without".
