### ISSUE TITLE
[FEATURE REQ] Support `withFreeTier`, `withStandardTier` and `withPremiumTier` for aks. 

### ISSUE THREAD

**Issue by XiaofeiCao** [Azure/azure-sdk-for-java#38881]
issue: https://github.com/Azure/azure-sdk-for-java/issues/38836

### 1. `withFreeTier`, `withStandardTier` and `withPremiumTier`, both create and update
docs: https://learn.microsoft.com/en-us/azure/aks/free-standard-pricing-tiers

Note: For premium tier, there's a `supportPlan` property(or `k8s-support-plan` in CLI). For premium, it's `AKSLongTermSupport `, while for other tiers, it's `KubernetesOfficial `. If they are tied together, we can set the value for user in `withXXTier` implementation.

### 2. `withVersion`, both create and update
https://github.com/Azure/azure-sdk-for-java/blob/bcdd2d3eb121f03a5e0d4ae0ed32d0bc646f4b3d/sdk/resourcemanager/azure-resourcemanager-containerservice/src/main/java/com/azure/resourcemanager/containerservice/fluent/models/ManagedClusterInner.java#L237

**Comment by agateaux** [comment]
Regarding the kubernetes version, as mentioned in my question ticket, if I may:
For the creation, the definition stage already supports the 'withVersion', to specify the Kubernetes version.
That's just for the update, the update stage doesn't offer this feature.

**Comment by weidongxu-microsoft** [comment]
2.37.0 released
