### ISSUE TITLE
Core - Plugin - Tracing OpenTelemetry Plugin Readme Issues

### ISSUE THREAD

**Issue by faynef** [Azure/azure-sdk-for-java#38905]
1.

**Section** [link](https://github.com/Azure/azure-sdk-for-java/blob/main/sdk/core/azure-core-tracing-opentelemetry/README.md#synchronous-clients): 
![image](https://github.com/Azure/azure-sdk-for-java/assets/138087452/5b0d9135-ec18-493e-9f88-51e0f9970d17)

**Reason:** Comments have extra spaces.

**Suggestion:** Remove extra spaces between `some` and `work`.

2.

**Section** [link1](https://github.com/Azure/azure-sdk-for-java/blob/main/sdk/core/azure-core-tracing-opentelemetry/README.md#using-the-plugin-package-with-amqp-client-libraries), [link2](https://github.com/Azure/azure-sdk-for-java/blob/main/sdk/core/azure-core-tracing-opentelemetry/README.md#samples):
![image](https://github.com/Azure/azure-sdk-for-java/assets/138087452/b977f27e-68d4-4fcf-b343-50e2c1d38ffb)
![image](https://github.com/Azure/azure-sdk-for-java/assets/138087452/f2e97424-8641-48e2-b9a5-a9aa52835632)

**Reason:** Link display error.

**Suggestion:** In the above two places add links: https://github.com/Azure/azure-sdk-for-java/blob/main/sdk/eventhubs/azure-messaging-eventhubs/src/samples/java/com/azure/messaging/eventhubs/PublishEventsTracingWithCustomContextSample.java.

@sandeep-sen , @joshfree and @alzimmermsft for notification.

**Comment by lmolkova** [comment]
fixed in #39559
