### ISSUE TITLE
[BUG] getMetadata returns only nulls

### ISSUE THREAD

**Issue by MichaelVonB** [Azure/azure-sdk-for-java#38913]
**Describe the bug**
We upload blob with metaData and query them later. However the metadata always return null even tough I can see them in the azure portal.

***Exception or Stack Trace***
n/a

**To Reproduce**
see code below

***Code Snippet***
```
BlobParallelUploadOptions options =
            new BlobParallelUploadOptions(byteArrayInputStream)
                .setRequestConditions(new BlobRequestConditions().setIfNoneMatch(Constants.HeaderConstants.ETAG_WILDCARD)) // sets overwrite files to false
                .setMetadata(Map.of("foo", "bar"))
                .setHeaders(jsonHeaders);

blobClient.uploadWithResponse(options, null, Context.NONE);
```

and query them later on essentially like this
```
BlobContainerClient blobContainerClient = blobServiceClient.getBlobContainerClient("my-blob-container-client");
List<Map<String, String>> metaDataList = blobContainerClient.listBlobs().stream()
            .map(BlobItem::getMetadata)
            .toList();
```
But this will be a List of nulls. However I can see in the azure portal that the meta data is filled.
This works but I would expect the other solution to work aswell
```
List<Map<String, String>> metaDataListFull = blobContainerClient.listBlobs().stream()
            .map(it -> blobContainerClient.getBlobClient(it.getName()))
            .map(it -> it.getProperties().getMetadata())
            .toList();
```
Add the code snippet that causes the issue.

**Expected behavior**
I would expect BlobItem::getMetadata to return the metadata and not null.

**Screenshots**
n/a

**Setup (please complete the following information):**
 - OS: macOS / OpenShift
 - IDE: IntelliJ / -
 - Library/Libraries: azure-storage-blob-12.25.1
 - Java version 17
 - App Server/Environment: Tomcat
 - Frameworks:Spring Boot

**Comment by alzimmermsft** [comment]
Thanks for filing this issue @MichaelVonB.

I believe you're running into this problem as there aren't any includes set in the `listBlobs` call. This document goes over the REST API details on how to include additional information in the response `BlobItem`:

https://learn.microsoft.com/rest/api/storageservices/list-blobs?tabs=microsoft-entra-id#metadata-in-the-response

And here is an example of the updated Java code:

```java
BlobContainerClient blobContainerClient = blobServiceClient.getBlobContainerClient("my-blob-container-client");
List<Map<String, String>> metaDataList = blobContainerClient.listBlobs(new ListBlobsOptions().setDetails(new BlobListDetails().setRetrieveMetadata(true)), null).stream()
            .map(BlobItem::getMetadata)
            .toList();
```

And here is a test we run that validates the behavior:

https://github.com/Azure/azure-sdk-for-java/blob/main/sdk/storage/azure-storage-blob/src/test/java/com/azure/storage/blob/ContainerApiTests.java#L819

**Comment by MichaelVonB** [comment]
Thank you for your quick supply. This fixed the issue. My bad i missed this. 
For local development we are using azurite and there metadata are always populated regardless of ListBlobsOptions so we never searched in that direction.
