### ISSUE TITLE
[Event Hubs] Rename `Retry` to `RetryPolicy`

### ISSUE THREAD

**Issue by conniey** [Azure/azure-sdk-for-java#3894]
Rename "Retry" to "RetryPolicy"

**Comment by JonathanGiles** [comment]
Is there an equivalent class in .NET? What is their naming choice?

**Comment by conniey** [comment]
.NET has their Retry named "Retry". We'll defer this conversation until later.
https://github.com/Azure/azure-sdk-for-net/blob/master/sdk/eventhub/Azure.Messaging.EventHubs/src/Retry.cs
