### ISSUE TITLE
How to know the number of tokens returned when calling the GPT-35 streaming chat interface?

### ISSUE THREAD

**Issue by zhuanshenlikai** [Azure/azure-sdk-for-java#39061]
When using the non-streaming interface, I can obtain the number of tokens returned from 'chatCompletions.getUsage().getTotalTokens()'. However, how can I determine the number of tokens returned when using the streaming interface?,the code is below:

![image](https://github.com/Azure/azure-sdk-for-java/assets/12570095/4955761f-a134-4cb2-8330-ad8452cfa034)

Is there an API available to query token-related operations? Can you assist me with that? Thank you.

**Comment by joshfree** [comment]
@mssfang could you please assist @zhuanshenlikai with their question?

**Comment by mssfang** [comment]
@zhuanshenlikai We don't support token computation for streaming API in OpenAI SDK. To compute tokens, you can use the external tokenizer library for Java:

For cl100k_base and p50k_base encodings:
Java:
[jtokkit](https://github.com/knuddelsgmbh/jtokkit)

For r50k_base (gpt2) encodings, tokenizers are available in many languages.
Java:
[gpt2-tokenizer-java](https://github.com/hyunwoongko/gpt2-tokenizer-java)
