### ISSUE TITLE
[FEATURE REQ] Improve documentation for max-concurrent-calls property

### ISSUE THREAD

**Issue by brunomace** [Azure/azure-sdk-for-java#39084]
**Is your feature request related to a problem? Please describe.**
The documentation for the `spring.cloud.stream.servicebus.bindings.binding-name.consumer.max-concurrent-calls` property should mention that it is _by session_ and not global (of course when sessions are enabled).
Besides this property is renamed to `concurrencyPerSession`:
https://github.com/Azure/azure-sdk-for-java/blob/azure-messaging-servicebus_7.15.0/sdk/servicebus/azure-messaging-servicebus/src/main/java/com/azure/messaging/servicebus/ServiceBusProcessorClient.java#L237

**Setup**
* Library/Libraries: `com.azure.spring:spring-cloud-azure-dependencies:5.10.0` with `com.azure:azure-messaging-servicebus:7.15.0`
* v2 enabled

**Describe the solution you'd like**
Update the documentation: 
https://learn.microsoft.com/en-us/azure/developer/java/spring-framework/spring-cloud-stream-support?tabs=SpringCloudAzure4x#consumer-properties-1
Update the Javadoc:
https://github.com/Azure/azure-sdk-for-java/blob/azure-messaging-servicebus_7.15.0/sdk/servicebus/azure-messaging-servicebus/src/main/java/com/azure/messaging/servicebus/ServiceBusClientBuilder.java#L1724

**Comment by joshfree** [comment]
Thanks for filing this doc issue, @brunomace 

/cc @Azure/azsdk-sb-java as fyi

**Comment by Netyyyy** [comment]
Hi @brunomace ,Thank you for reporting this issue. We have received your submission and will take a look. We appreciate your input and will review this matter as soon as possible.
Please feel free to provide any additional information or context that you think may be helpful. We'll keep you updated on the progress of our review.

**Comment by saragluna** [comment]
Thank you, @brunomace. However, does it appear that the renaming only affects the scope of local variables? If that’s the case, we may not modify the properties immediately, but we will update the documentation in the meantime.
