### ISSUE TITLE
[BUG] sessionIdleTimeout property is missing in the Spring Cloud binder

### ISSUE THREAD

**Issue by brunomace** [Azure/azure-sdk-for-java#39083]
**Describe the bug**
There is no way to set the `sessionIdleTimeout` property via Spring Cloud Stream.

**Expected behavior**
It is not possible to set session idle timeout duration, so the application can't switch to another session if no message is received after some time.

**Setup**
 - Library/Libraries: `com.azure.spring:spring-cloud-azure-dependencies:5.10.0` with `com.azure:azure-messaging-servicebus:7.15.0`
 - Java version: `17`
 - Frameworks: `Spring Boot 3.2.2`, `Spring Cloud 2023.0.0`

**Additional context**
It seems to be mismatch between Spring and Azure libraries.
The `sessionIdleTimeout` property exists in the `azure-messaging-servicebus` library (defaut to `null`):
https://github.com/Azure/azure-sdk-for-java/blob/azure-messaging-servicebus_7.15.0/sdk/servicebus/azure-messaging-servicebus/src/main/java/com/azure/messaging/servicebus/ServiceBusClientBuilder.java#L1814
But this property is missing in the Spring properties:
https://github.com/Azure/azure-sdk-for-java/blob/spring-cloud-azure-service_5.10.0/sdk/spring/spring-cloud-azure-service/src/main/java/com/azure/spring/cloud/service/implementation/servicebus/properties/ServiceBusProcessorClientProperties.java
And so is not passed from Spring to Azure:
https://github.com/Azure/azure-sdk-for-java/blob/spring-cloud-azure-service_5.10.0/sdk/spring/spring-cloud-azure-service/src/main/java/com/azure/spring/cloud/service/implementation/servicebus/factory/ServiceBusProcessorClientBuilderFactory.java#L86

**Comment by Netyyyy** [comment]
Hi @brunomace , Thank you for reporting this issue. We have received your submission and will take a look. We appreciate your input and will review this matter as soon as possible.
Please feel free to provide any additional information or context that you think may be helpful. We'll keep you updated on the progress of our review.

**Comment by moarychan** [comment]
Now you can add a customizer bean (`AzureServiceClientBuilderCustomizer<ServiceBusClientBuilder.ServiceBusProcessorClientBuilder>`) to custom the unsupported properties in Spring Cloud Azure side.

**Comment by Netyyyy** [comment]
Hi @brunomace , although we support to customizer ClientBuilder, but the `sessionIdleTimeout` property you point is not for public:  
https://github.com/Azure/azure-sdk-for-java/blob/955c32246c2dc063eac062a16f1d668d1a077a23/sdk/servicebus/azure-messaging-servicebus/src/main/java/com/azure/messaging/servicebus/ServiceBusClientBuilder.java#L1859-L1863

Hi @anuchandy , are there any plans to make this method public for user customization?

**Comment by Netyyyy** [comment]
Customize `AzureServiceClientBuilderCustomizer<ServiceBusClientBuilder.ServiceBusSessionProcessorClientBuilder>` is good to go
