### ISSUE TITLE
[QUERY] Is there a reactive alternative to `new DefaultAzureCredentialBuilder().build()`

### ISSUE THREAD

**Issue by dougnob** [Azure/azure-sdk-for-java#39126]
**Query/Question**
Is there a reactive alternative to `DefaultAzureCredentialBuilder#build`?

**Context**
We have a REST API developed with spring-webflux using the Azure identity library. `DefaultAzureCrendentialBuilder#build` is blocking, we were hoping for an asynchronous non-blocking alternative.

**Setup**
 - Libraries: 
   - org.springframework:spring-webflux:6.1.4
   - com.azure:azure-identity:1.10.4

**Comment by dougnob** [comment]
thanks for your reply @anuchandy

**Comment by anuchandy** [comment]
sure, closing this.
