### ISSUE TITLE
[BUG] OpenAI completions can not be streamed in some cases

### ISSUE THREAD

**Issue by simon-meer** [Azure/azure-sdk-for-java#39128]
**Describe the bug**
When using the `vision-preview` model with the async stack, the response is not streamed and is instead buffered and received all at once.
The reason for this is that unlike the other models, it returns a `Content-Type: text/event-stream; charset=utf-8`, which causes issues with the following lines:

https://github.com/Azure/azure-sdk-for-java/blob/f592742e24b740cd9a815d676e28054170a1aaae/sdk/core/azure-core/src/main/java/com/azure/core/implementation/http/rest/AsyncRestProxy.java#L44

https://github.com/Azure/azure-sdk-for-java/blob/f592742e24b740cd9a815d676e28054170a1aaae/sdk/core/azure-core/src/main/java/com/azure/core/implementation/http/rest/AsyncRestProxy.java#L207-L213

The code only checks for an exact match and does not take into account the charset.

**To Reproduce**
(Disclaimer: I didn't test this code, but you can easily verify the issue by looking at the code snippet above.)

```java
// Proxy options
OpenAIClient client = new OpenAIClientBuilder()
    .credential(new AzureKeyCredential("{key}"))
    .endpoint("{endpoint-with-vision-preview}")
    .buildAsyncClient();

List<ChatRequestMessage> chatMessages = new ArrayList<>();
chatMessages.add(new ChatRequestSystemMessage("You are a helpful assistant. You will talk like a pirate."));
chatMessages.add(new ChatRequestUserMessage("Can you help me?"));
chatMessages.add(new ChatRequestAssistantMessage("Of course, me hearty! What can I do for ye?"));
chatMessages.add(new ChatRequestUserMessage("What's the best way to train a parrot?"));

IterableStream<ChatCompletions> chatCompletionsStream = client.getChatCompletionsStream("{deploymentOrModelName}",
    new ChatCompletionsOptions(chatMessages));

chatCompletionsStream
    .stream()
    .forEach(chatCompletions -> {
        ChatResponseMessage delta = chatCompletions.getChoices().get(0).getDelta();
        if (delta.getRole() != null) {
            System.out.println("Role = " + delta.getRole());
        }
        if (delta.getContent() != null) {
            System.out.print(delta.getContent());
        }
    });
```

**Expected behavior**
Responses should stream when using `getChatCompletionsStream()`.

**Setup (please complete the following information):**
 - OS: MacOS
 - IDE: IntelliJ
 - Library/Libraries: azure-ai-openai:1.0.0-beta.7
 - Java version: 17
 - App Server/Environment: Netty

**Workaround**
For anyone else who comes across this issue, a possible workaround is to simply rewrite the content type with a custom policy:

```kotlin
OpenAIClientBuilder()
  .credential(AzureKeyCredential(model.apiKey))
  .endpoint(model.endpoint)
  .addPolicy { _, next ->
      next.process().map { response ->
          if (response.headers.getValue(HttpHeaderName.CONTENT_TYPE).startsWith("text/event-stream;")) {
              response.headers.set(HttpHeaderName.CONTENT_TYPE, "text/event-stream")
          }
          response
      }
  }
  .buildAsyncClient()
```

**Information Checklist**
Kindly make sure that you have added all the following information above and checkoff the required fields otherwise we will treat the issuer as an incomplete report
- [x] Bug Description Added
- [x] Repro Steps Added
- [x] Setup information Added

**Comment by joshfree** [comment]
@mssfang please take a look

**Comment by mssfang** [comment]
@simon-meer Thank you for report this to us. A bugfix [PR](https://github.com/Azure/azure-sdk-for-java/pull/39204) created for this bug. We release Azure Core monthly, so the next release of Core will be in the early of April.

**Comment by mssfang** [comment]
@simon-meer beta.8 which includes the bugfix is out on the maven site now:
https://repo1.maven.org/maven2/com/azure/azure-ai-openai/1.0.0-beta.8/
