### ISSUE TITLE
java.lang.NoClassDefFoundError: Could not initialize class com.azure.identity.implementation.IdentityClient

### ISSUE THREAD

**Issue by Arefaat18** [Azure/azure-sdk-for-java#39120]
I am getting this error while executing this line of code 

```
final ClientSecretCredential credential = new ClientSecretCredentialBuilder()
                .clientId(CLIENT_ID).tenantId(TENANT_ID).clientSecret(CLIENT_SECRET)
                .build();
```
In debugging the error it works correctly until this function in IdentityClientBuilder class
```
public IdentityClient build() {
        return new IdentityClient(this.tenantId, this.clientId, this.clientSecret, this.certificatePath, this.clientAssertionPath, this.resourceId, this.clientAssertionSupplier, this.certificate, this.certificatePassword, this.sharedTokenCacheCred, this.clientAssertionTimeout, this.identityClientOptions);
    }
```
where it throws this error

`java.lang.NoClassDefFoundError: Could not initialize class com.azure.identity.implementation.IdentityClient`

I am working in a SAP Commerce Cloud 2211 project with azure-identity-1.11.2.jar , azure-core-1.46.0.jar
Due to a bug in SAP Commerce I can't download the jars using Maven, so I am working with the downloaded jars.

Thank you for your help.

**Comment by joshfree** [comment]
Hi @Arefaat18 it sounds like there's a dependency conflict in the application.  Here's our troubleshooting guide on how to resolve this: https://learn.microsoft.com/en-us/azure/developer/java/sdk/troubleshooting-dependency-version-conflict
