### ISSUE TITLE
Ref docs issue

### ISSUE THREAD

**Issue by faynef** [Azure/azure-sdk-for-java#39135]
Error:

> bad class file: D:\a\_work\1\s\target_repo\src\docs-ref-autogen\azure-spring-data-cosmos\dependency\spring-data-commons-3.2.3.jar(/org/springframework/data/util/TypeInformation.class)      class file has wrong version 61.0, should be 55.0      Please remove or make sure it appears in the correct subdirectory of the classpath. error: cannot access TypeInformation  import org.springframework.data.util.TypeInformation;    

> ##[error]The process 'C:\hostedtoolcache\windows\Python\3.10.11\x64\python.exe' failed with exit code 1

- https://apidrop.visualstudio.com/Content%20CI/_build/results?buildId=417132&view=results

@danieljurek for notification.

**Comment by danieljurek** [comment]
This is fixed.
