### ISSUE TITLE
[QUERY] Will the BatchAccounts be supported in the AzureResourceManager?

### ISSUE THREAD

**Issue by arballesteros** [Azure/azure-sdk-for-java#39151]
**Query/Question:**
I am currently migrating to AzureResourceManager and noticed that BatchAccounts is no longer accessible and in fact, it is currently commented out in the [source](https://github.com/Azure/azure-sdk-for-java/blob/80c668f4e953bfeaea7af5454cb509d7121221c9/sdk/resourcemanager/azure-resourcemanager/src/main/java/com/azure/resourcemanager/AzureResourceManager.java#L704).

1. I would just like to know if BatchAccounts will be supported in AzureResourceManager in the future?
2. Should I just use com.azure.resourcemanager:azure-resourcemanager-batch:1.1.0-beta.3 to access the BatchAccounts?

**Setup:**

 Library/Libraries: 
 - com.azure.resourcemanager:azure-resourcemanager:2.36.0
 - com.azure.resourcemanager:azure-resourcemanager-batch:1.1.0-beta.3
 
 
 **Information Checklist:**
- [X] Query Added
- [X] Setup information Added

**Comment by weidongxu-microsoft** [comment]
@arballesteros 

Yes, you should use com.azure.resourcemanager:azure-resourcemanager-batch for BatchAccounts.

You can use the stable release of 1.0.0 of azure-resourcemanager-batch

If you need to use new feature of it in later api-versions, let us know.

**Comment by arballesteros** [comment]
@weidongxu-microsoft

Thanks for your reply.
I will try to use the azure-resourcemanager-batch:1.0.0.
