### ISSUE TITLE
[BUG] no convenience API to set PublicNetworkAccess in Vault

### ISSUE THREAD

**Issue by promangallego** [Azure/azure-sdk-for-java#39192]
**Describe the bug**
azure sdk for java does not offer diable PublicNetworkAccess for keyvaults

***Exception or Stack Trace***
import com.azure.identity.DefaultAzureCredential;import com.azure.resourcemanager.AzureResourceManager;import com.azure.resourcemanager.keyvault.models.Vault;import com.azure.resourcemanager.keyvault.models.VaultCreateOrUpdateParameters;import com.azure.resourcemanager.keyvault.models.VaultProperties;import com.azure.resourcemanager.resources.fluentcore.arm.Region;import com.azure.resourcemanager.resources.fluentcore.utils.ResourceManagerUtils;
public class CreateKeyVaultExample {
    public static void main(String[] args) {
        String subscriptionId = "<your-subscription-id>";
        String resourceGroupName = "<your-resource-group-name>";
        String keyVaultName = "<your-key-vault-name>";

        // Authenticate using DefaultAzureCredentialAzureResourceManager azureResourceManager = AzureResourceManager.configure()
                .withLogLevel(HttpLogDetailLevel.BASIC)                .authenticate(new DefaultAzureCredential())
                .withDefaultSubscription();

        // Create a new Key VaultVault vault = azureResourceManager.keyVaults().define(keyVaultName)
                .withRegion(Region.US_WEST)
                .withNewResourceGroup(resourceGroupName)
                .withEmptyAccessPolicy()
                .create();

        System.out.println("Key Vault created: " + vault.vaultUri());
    }
}
**To Reproduce**
When coding with to the SDK properties there is no .withPublicNetworkAccess to set to False
It creates it with PublicNetworkAccess enabled

***Code Snippet***
See above

**Expected behavior**
To be able to disable publicNetwokAccess

**Screenshots**

**Setup (please complete the following information):**
 - OS: [Mac]
 - IDE: [IntelliJ]
 - Library/Libraries: [azure-resource-manager-keyvault 2.36.0]
 - Java version: coreto 21
 - App Server/Environment: [openshift]
 - Frameworks: Spring Boot] 

If you suspect a dependency version mismatch (e.g. you see `NoClassDefFoundError`, `NoSuchMethodError` or similar), please check out [Troubleshoot dependency version conflict article](https://aka.ms/azsdk/java/dependency/troubleshoot) first. If it doesn't provide solution for the problem, please provide:
- verbose dependency tree (`mvn dependency:tree -Dverbose`)
- exception message, full stack trace, and any available logs

**Additional context**

**Information Checklist**
Kindly make sure that you have added all the following information above and checkoff the required fields otherwise we will treat the issuer as an incomplete report
- [ ] Bug Description Added
- [ ] Repro Steps Added
- [ ] Setup information Added

**Comment by weidongxu-microsoft** [comment]
PR https://github.com/Azure/azure-sdk-for-java/pull/39309

Should be included in next 2.37.0 release, scheduled before end of March.
