### ISSUE TITLE
[QUERY] Azure-Identity uses deprecated libraries

### ISSUE THREAD

**Issue by arballesteros** [Azure/azure-sdk-for-java#39214]
**Query/Question:**

I am using IntelliJ and I am receiving deprecated Azure SDK library notifications for the following Azure-Identity dependencies:
- com.microsoft.azure/msal4j-persistence-extension
- com.microsoft.azure/msal4j

I would just like to know if Azure-Identity will remove these deprecated dependencies in the future?
Or should I refrain from using Azure-Identity library?

**Setup:**
 - OS: Windows
 - IDE: IntelliJ IDEA 2023.2 (Ultimate Edition)
 - Library/Libraries: com.azure/azure-identity:1.11.3
 
 **Information Checklist:**
- [X] Query Added
- [X] Setup information Added

**Comment by billwert** [comment]
Hello! Neither of these libraries should be deprecated in Identity 1.11.3. You can safely continue to use Identity with these versions. The version of `msal4j` currently used is a couple behind, but we will roll that forward in next month's release. Can you share more about what component in IntelliJ is giving you this warning? In a demo project just now I am not seeing a warning about these libraries, and I'd love to see what you're seeing so I can track down what's going on.

**Comment by arballesteros** [comment]
This warning can be seen in the Notifications window of IntelliJ IDEA 2023.2 as shown in the image below.

![image](https://github.com/Azure/azure-sdk-for-java/assets/141611622/9974a392-9a11-4dfa-82e9-f71987cb92b2)

**Comment by billwert** [comment]
Thanks! I've reached out to the team that owns the IntelliJ tooling to see how we can improve this.
