### ISSUE TITLE
[BUG] Recent versions no longer set audit data when saving multiple entities with partition keys

### ISSUE THREAD

**Issue by Blackbaud-JasonBodnar** [Azure/azure-sdk-for-java#39226]
**Describe the bug**
There seems to be a regression between 3.18 and 3.42. I believe it also exists in the latest 5.x version.

In 3.18, SimpleCosmosRepository.saveAll():

```
public <S extends T> Iterable<S> saveAll(Iterable<S> entities) {
        Assert.notNull(entities, "Iterable entities should not be null");

        final List<S> savedEntities = new ArrayList<>();
        entities.forEach(entity -> {
            final S savedEntity = this.save(entity);
            savedEntities.add(savedEntity);
        });

        return savedEntities;
    }
```
By calling save() on each entity of the Iterable passed, any auditing information was filled in (ie, @CreatedBy, @LastModifiedBy, etc).

But in 3.48:

```
public <S extends T> Iterable<S> saveAll(Iterable<S> entities) {
        Assert.notNull(entities, "Iterable entities should not be null");

        if (information.getPartitionKeyFieldName() != null) {
            return operation.insertAll(this.information, entities);
        } else {
            final List<S> savedEntities = new ArrayList<>();
            entities.forEach(entity -> {
                final S savedEntity = this.save(entity);
                savedEntities.add(savedEntity);
            });

            return savedEntities;
        }
    }
```
If there's a partition key, operation.insertAll(this.information, entities) does not add auditing information.

**To Reproduce**
See https://github.com/Blackbaud-JasonBodnar/cosmos-sql-bug/blob/v5.x/src/test/groovy/com/example/cosmossqlbug/TestEntityRepositorySpec.groovy#L28

***Code Snippet***
```
public <S extends T> Iterable<S> saveAll(Iterable<S> entities) {
        Assert.notNull(entities, "Iterable entities should not be null");

        if (information.getPartitionKeyFieldName() != null) {
            return operation.insertAll(this.information, entities);
        } else {
            final List<S> savedEntities = new ArrayList<>();
            entities.forEach(entity -> {
                final S savedEntity = this.save(entity);
                savedEntities.add(savedEntity);
            });

            return savedEntities;
        }
    }
```

**Expected behavior**
Any annotated fields will be populated with audit data.

**Setup (please complete the following information):**
 - Library/Libraries: com.azure:azure-spring-data-cosmos:3.42.0
 - Java version: 17
 - Frameworks: Springboot

**Additional context**

Originally reported when trying to find a solution for https://github.com/Azure/azure-sdk-for-java/issues/38691 but it should be its own bug.

**Information Checklist**
Kindly make sure that you have added all the following information above and checkoff the required fields otherwise we will treat the issuer as an incomplete report
- [x] Bug Description Added
- [x] Repro Steps Added
- [x] Setup information Added

**Comment by kushagraThapar** [comment]
thanks @Blackbaud-JasonBodnar for creating this issue. @trande4884 can you please work on it? Seems like related to our bulk implementation for saveAll(). 
Similar issue might be happening for deleteAll() and findAll as well if we have bulk implementations for those as well.

**Comment by Blackbaud-JasonBodnar** [comment]
@kushagraThapar , @trande4884 : Any updates on this bug?
