### ISSUE TITLE
[Event Hubs] Replace constant strings with resource strings

### ISSUE THREAD

**Issue by conniey** [Azure/azure-sdk-for-java#3923]
Replace all the user strings (ie. error strings) with resource strings that can possibly be globalised later.

**Comment by mclay** [comment]
please assign me this task and let me know which modules are affected from this

**Comment by JonathanGiles** [comment]
@conniey Can you please give @mclay the details so he may own this task. Thanks!

**Comment by conniey** [comment]
@mclay Hey! Thanks for offering to take a look at this. :D The modules affected by this issue are: [azure-messaging-eventhubs](https://github.com/Azure/azure-sdk-for-java/tree/master/sdk/eventhubs/azure-messaging-eventhubs) and [azure-messaging-eventhubs-checkpointstore-blob](https://github.com/Azure/azure-sdk-for-java/tree/master/sdk/eventhubs/azure-messaging-eventhubs-checkpointstore-blob).

I was hoping to have something like Key Vault where they have a [`*.properties` file](https://github.com/Azure/azure-sdk-for-java/tree/master/sdk/keyvault/azure-security-keyvault-secrets/src/main/resources) in their resource folder with user-facing messages in it that we could point to in our code base. 

I am open to other suggestions if you've seen it done in the wild in other ways.

**Comment by mclay** [comment]
@conniey could you please reopen this one because i have to also replace the constant string values in azure-messaging-eventhubs-checkpointstore-blob.

**Comment by conniey** [comment]
@mclay Thanks for letting me know. I forgot about that module. :(

**Comment by mclay** [comment]
hi @conniey, i finished the remaining module and it's ready for review
