### ISSUE TITLE
Broken links, stale references to Azure AD instead of Entra, and wrong Auth guidance

### ISSUE THREAD

**Issue by srnagar** [Azure/azure-sdk-for-java#39237]
Reporting three (3) issues

- [x] The Java libraries, drivers, and Spring modules page instructs users to install MSAL for Authentication. This should change to point users to Azure Identity SDK.
- [x] the link to Microsoft Entra Spring Boot Starter is broken
- [x] References to Azure AD and Azure Active Directory need to be changed to Microsoft Entra ID (/cc @scottaddie)

Originally reported here - https://github.com/MicrosoftDocs/azure-dev-docs/issues/1314

**Comment by billwert** [comment]
The original issue link is gone as far as I can tell. @scottaddie do you know how we can get back what data was in that issue?

**Comment by scottaddie** [comment]
@billwert Issues have been disabled in that repo, so there's no easy way to recover it. The issue is for https://learn.microsoft.com/azure/developer/java/sdk/libraries-drivers-modules. I've addressed items 2 and 3 already.

**Comment by billwert** [comment]
Ah, now I understand. Thanks for the pointer.

Looks like we need to rewrite some samples too. I was looking through issues and hoped this was a quick fix. Alas.

**Comment by billwert** [comment]
Identity doesn't have the flow in the MSAL docs here. I did update the doc to a more recent version of their samples.
