### ISSUE TITLE
[Event Hubs] Add logging of SDK exceptions that are thrown.

### ISSUE THREAD

**Issue by conniey** [Azure/azure-sdk-for-java#3924]
> We should spec up better what to do in situations like this, as this won't be automatically logged. We should probably have an API that throws an exception through the service logger API. 

Consider how to log exceptions that are thrown so that they can be logged.
https://github.com/Azure/azure-sdk-for-java/pull/3917#discussion_r294006934

**Comment by JonathanGiles** [comment]
This issue is being addressed in PR #4191
