### ISSUE TITLE
Incorrect return type for getTracingOptions() documented

### ISSUE THREAD

**Issue by nawazish-couchbase** [Azure/azure-sdk-for-java#39294]
### Type of issue

Typo

### Description

[Enter feedback here]
The return type of `com.azure.core.util.ClientOptions.getTracingOptions()` documents that the return type is `com.azure.core.util.MetricOptions` whilst it should be `com.azure.core.util.TracingOptions`. 

This typo is present all over the document like in the `Method Summary` section also.

### Page URL

https://learn.microsoft.com/en-us/java/api/com.azure.core.util.clientoptions?view=azure-java-stable

### Content source URL

https://github.com/Azure/azure-docs-sdk-java/blob/master/docs-ref-autogen/com.azure.core.util.ClientOptions.yml

### Document Version Independent Id

ff4c8bde-1f8b-5adf-e3a5-8920caeed34e

### Article author

@rloutlaw

### Metadata

* ID: e83a12a1-549a-a64f-58dd-83459d4df0cf 
* Service: **azure**

**Comment by nawazish-couchbase** [comment]
Hi people,

Is there anything pending/required from my end?

**Comment by lmolkova** [comment]
@nawazish-couchbase thanks a lot for reporting this! Nothing is required - I'll fix the issue.
