### ISSUE TITLE
[LRO] Support for additional operation states

### ISSUE THREAD

**Issue by JonathanGiles** [Azure/azure-sdk-for-java#3930]
Currently we have an OperationStatus enum with a few states. To support a wider range of long-running operations, we should support additional states. One possible approach to support this is to introduce an `OTHER` OperationStatus, and then to provide a `getOtherStatus()` method on the `PollResponse`. This will allow certain services to provide custom status information, most probably as a String type, that can be provided to the user.

**Comment by hemanttanwar** [comment]
started working on it

**Comment by hemanttanwar** [comment]
PR : https://github.com/Azure/azure-sdk-for-java/pull/4091
