### ISSUE TITLE
[LRO] Support blocking for intermediate states, rather than final state

### ISSUE THREAD

**Issue by JonathanGiles** [Azure/azure-sdk-for-java#3931]
Some users of long-running operations do not need to block until the final state - in some cases they just want to block long enough to ensure that the polling request has started, for example. We should introduce new API that lets them block until a poll response is received representing a particular state has been entered. Given #3930, this may be an `OperationStatus` state, or it may be a `String` 'other' state.

**Comment by hemanttanwar** [comment]
New PR for this work :  https://github.com/Azure/azure-sdk-for-java/pull/4091
