### ISSUE TITLE
[FEATURE REQ] Support `dimensions` EmbeddingOptions in OpenAI API

### ISSUE THREAD

**Issue by thai-op** [Azure/azure-sdk-for-java#39336]
**Is your feature request related to a problem? Please describe.**
The OpenAPI Spec stated support for the option, so the client library should also support it. https://github.com/Azure/azure-rest-api-specs/blob/5cbd7c23897da22f52da4f02534b2819abe9f761/specification/cognitiveservices/data-plane/AzureOpenAI/inference/preview/2024-03-01-preview/inference.json#L421

**Describe the solution you'd like**
Add the feature.

**Describe alternatives you've considered**
Add the feature.

**Information Checklist**
Kindly make sure that you have added all the following information above and checkoff the required fields otherwise we will treat the issuer as an incomplete report
- [ x] Description Added
- [ x] Expected solution specified

**Comment by mssfang** [comment]
Hi @thai-op We are working on adding this feature to the next version. ETA will be next few weeks.
https://github.com/Azure/azure-sdk-for-java/pull/39296/files#diff-b477cd2968cae4b347314275298a5f5c2f49926f547869eba6060b0874adb43dR8

**Comment by mssfang** [comment]
@thai-op Beta.8 is out on the maven site now:
https://repo1.maven.org/maven2/com/azure/azure-ai-openai/1.0.0-beta.8/

**Comment by thai-op** [comment]
Thank you! @mssfang
