### ISSUE TITLE
[QUERY] ServiceBusSenderClient Thread safe?

### ISSUE THREAD

**Issue by StargateSGx1** [Azure/azure-sdk-for-java#39333]
**Query/Question**
Can i create a ServiceBusSenderClient as singleton in a web application? Is this Thread safe?

```
@Bean
@Scope(value = "singleton")
public ServiceBusSenderClient createSenderClient() {
  return new ServiceBusClientBuilder()
      .connectionString(connectionString)
      .sender()
      .queueName(„queueName“)
      .buildClient();
} 
```

**Comment by anuchandy** [comment]
Hello @StargateSGx1, yes, a sender instance is thread safe. 

If there is only one web app instance deployed and if that is expecting high traffic, you may want to consider pool of sender instances, where each sender instance is built a separate builder instance (i.e., not a shared builder instance). I suggest starting with one sender instance and considering pooling if that one instance identified as a bottleneck.

**Comment by anuchandy** [comment]
Closing this, clarified the query and recommendation provided.
