### ISSUE TITLE
[BUG] azure-storage-blob library with azure-core-http-okhttp client prevents application from termination for 60 seconds.

### ISSUE THREAD

**Issue by if-of** [Azure/azure-sdk-for-java#39349]
**Describe the bug**
azure-storage-blob library with azure-core-http-okhttp client prevents application from finishing for 60 seconds.

**To Reproduce**
Execute the provided code snippet. Instead of instantly terminating after printing 'File uploaded successfully', it holds for a 60-second delay before concluding execution.

***Code Snippet***
build.gradle
```
plugins {
    id 'java'
    id 'org.springframework.boot' version '3.2.3'
}

apply plugin: 'io.spring.dependency-management'

group = 'org.example'
version = '1.0-SNAPSHOT'

repositories {
    mavenCentral()
}

dependencies {
    implementation('org.springframework.boot:spring-boot-starter')

    implementation("com.azure:azure-identity:1.11.2") {
        exclude module: "azure-core-http-netty"
    }
    implementation("com.azure:azure-storage-blob:12.25.1") {
        exclude module: 'azure-core-http-netty'
    }
    implementation("com.azure:azure-core-http-okhttp:1.11.18")

    testImplementation platform('org.junit:junit-bom:5.9.1')
    testImplementation 'org.junit.jupiter:junit-jupiter'
}

test {
    useJUnitPlatform()
}
```
application code:
```
import java.io.ByteArrayInputStream;
import java.nio.charset.StandardCharsets;
import java.util.UUID;

import com.azure.core.credential.TokenCredential;
import com.azure.identity.ClientSecretCredentialBuilder;
import com.azure.storage.blob.BlobServiceClientBuilder;
import org.springframework.boot.CommandLineRunner;
import org.springframework.boot.SpringApplication;
import org.springframework.boot.autoconfigure.SpringBootApplication;

@SpringBootApplication
public class AzureBlobApp implements CommandLineRunner {

    public static void main(String[] args) {
        SpringApplication.run(AzureBlobApp.class, args);
    }

    @Override
    public void run(String... args) {
        var client = new BlobServiceClientBuilder().endpoint(System.getenv("BLOB_ENDPOINT"))
            .credential(getClientSecretTokenCredential())
            .buildClient();

        var containerClient = client.getBlobContainerClient(System.getenv("CONTAINER_NAME"));

        var blobClient = containerClient.getBlobClient("test_do/" + UUID.randomUUID());
        blobClient.upload(new ByteArrayInputStream("Hello, Azure!".getBytes(StandardCharsets.UTF_8)));
        System.out.println("\nFile uploaded successfully");
    }

    protected TokenCredential getClientSecretTokenCredential() {
        return new ClientSecretCredentialBuilder()
            .tenantId(System.getenv("TENANT_ID"))
            .clientId(System.getenv("CLIENT_ID"))
            .clientSecret(System.getenv("CLIENT_SECRET"))
            .build();
    }

}
```

**Expected behavior**
Blob client will not block application from finishing

**Screenshots**
possible thread that cause waiting
![image](https://github.com/Azure/azure-sdk-for-java/assets/47608281/7e568bd0-e540-4347-81b5-d4fb0b8c6d0b)

**Setup (please complete the following information):**
 - OS: Windows 10 / alpine:3.18.6 docker image
 - IDE: IntelliJ / -
 - Library/Libraries: see code snippet
 - Java version: 17
 - App Server/Environment: -
 - Frameworks: Spring Boot

**Information Checklist**
Kindly make sure that you have added all the following information above and checkoff the required fields otherwise we will treat the issuer as an incomplete report
- [X] Bug Description Added
- [X] Repro Steps Added
- [X] Setup information Added

**Comment by alzimmermsft** [comment]
Thank you for filing this question @if-of.

Did some investigation, this appears to be the default behavior of OkHttp's `Dispatcher` class, which in turn by default we don't modify when OkHttp is being used leaving that configuration to the application to handle.

Looking at `Dispatcher` it uses a `ThreadFactory` that creates non-daemon threads for the `ExecutorService` backing the `Dispatcher` (https://github.com/square/okhttp/blob/master/okhttp/src/main/kotlin/okhttp3/Dispatcher.kt#L103, https://github.com/square/okhttp/blob/master/okhttp/src/main/kotlin/okhttp3/internal/-UtilJvm.kt#L65).

The good news, our OkHttp HttpClient builder allows for configuration of the `Dispatcher` being used. So, a simple work around could be supplying your own `Dispatcher` that doesn't use daemon threads, therefore prevents the `Dispatcher` from preventing JVM shutdown while the threads time out in the `ExecutorService`.

https://github.com/Azure/azure-sdk-for-java/blob/main/sdk/core/azure-core-http-okhttp/src/main/java/com/azure/core/http/okhttp/OkHttpAsyncHttpClientBuilder.java#L298

**Comment by if-of** [comment]
Thank you, @alzimmermsft. Your workaround effectively solved my issue, eliminating the 60-second wait time.

P.S: It's quite unfortunate that this isn't the default behavior. However, considering the simplicity of the fix, it's not much of an inconvenience.
