### ISSUE TITLE
[QUERY] EventProcessorClient stops to consume from partitions intermittently

### ISSUE THREAD

**Issue by psaisandeep** [Azure/azure-sdk-for-java#39367]
**Query/Question**
We consume from EventHub using EventProcessorClient and occasionally some partitions stop consuming. We have two consumers reading the same data, but from different EventHubs, however this happens to one of them more frequently than the other.

We get an WARN log from `com.azure.messaging.eventhubs.PartitionPumpManager`:
```
{"az.sdk.message":"Error receiving events from partition.","exception":"The service was unable to process the request; please retry the operation. For more information on exception types and proper exception handling, please refer to http://go.microsoft.com/fwlink/?LinkId=761101 TrackingId:547342625a3d4b298ec9daec8204099c_G8S1, SystemTracker:gateway5, Timestamp:2024-03-22T02:26:45, errorContext[NAMESPACE: <<SERVICE_BUS_NAME_HIDDEN>>.servicebus.windows.net. ERROR CONTEXT: N/A, PATH: eh94313962a7/ConsumerGroups/$default/Partitions/0, REFERENCE_ID: 0_b8a111_1710818784908, LINK_CREDIT: 300]","partitionId":"0"}
```
followed by Error log from `reactor.core.publisher.Operators`: `Operator called default onErrorDropped`
```
com.azure.core.amqp.exception.AmqpException: The service was unable to process the request; << Same exception message as above >>
```
followed by a call to `.processError()` with the same error

I want to understand why this is happening and more importantly how to recover from it without a manual restart.

***Why is this not a Bug or a feature Request?***
More information is needed before determining if it is a bug.

**Setup (please complete the following information if applicable):**
 - Library/Libraries: `com.azure:azure-messaging-eventhubs:5.18.1`
 - Client setup:
```scala
    val eventProcessorClient: EventProcessorClient = new EventProcessorClientBuilder()
      .consumerGroup(EventHubClientBuilder.DEFAULT_CONSUMER_GROUP_NAME)
      .connectionString(connectionString)
      .processEventBatch(
        processEventBatch(_),
        MAX_BATCH_SIZE,
        MAX_BATCH_WAIT_DURATION,
      )
      .processError(errorContext => {
        logger.error("Error occurred while processing events.", errorContext.getThrowable)
      })
      .checkpointStore(new CustomCheckpointStore())    // Custom implementation using Spanner Db
      .buildEventProcessorClient()
```
 
 **Information Checklist**
 Kindly make sure that you have added all the following information above and checkoff the required fields otherwise we will treat the issuer as an incomplete report
- [x] Query Added
- [x] Setup information Added

**Comment by anuchandy** [comment]
Hi @psaisandeep, The error from the service (sent over the partition-connection/link) is transient, when this happens, the EventProcessorClient instance will lose the ownership of that specific partition. Each EventProcessorClient instance has a background load-balancer running at regular intervals, which is responsible for acquiring the ownership of such orphaned partitions, so receive from those partitions resumes. 

The load-balancers (across multiple EventProcessorClient instances for one Event Hubs) use the common/shared checkpoint store to monitor, negotiate and balance the ownership of partitions. The load-balancer(s) rely on the centralized checkpoint store for this. It could be that the ownership loss was not detected, preventing ownership acquisition. I noticed a custom checkpoint store is used here, can we test with the official default [blob checkpoint store](https://central.sonatype.com/artifact/com.azure/azure-messaging-eventhubs-checkpointstore-blob) (with one of the Event Hubs) to see if this is nothing specific to custom implementation or its backing store/db.?

Additionally, you can capture [SDK logs](https://learn.microsoft.com/en-us/azure/developer/java/sdk/troubleshooting-messaging-event-hubs-overview ) (-10/+10minutes) when the issue occurs, which should provide us more insight (specific to SDK but not custom store implementation)

**Comment by psaisandeep** [comment]
@anuchandy Thanks for the response. My understanding of the load-balancer strategy is inline with your response. What is the load-balancer frequency to reclaim the ownership of lost partition? A few weeks ago when this issue went unnoticed, the partitions were not reclaimed until after 5 days. I only use a single EventProcessorClient instance to read from an EventHub, if that is relevant.

The custom checkpoint store implementation is based off of the blob implementation, but since I am not using Azure infrastructure (the event hub is managed by a different producer), I can't change to use it.

**Comment by anuchandy** [comment]
By default, the load balancer is scheduled to run every 30 seconds. 

The high core utilization and memory pressure can stall the timer thread that is supposed to trigger load-balancer. The generally recommended Partitions: Core ratio is 1.5 partitions for each core.

It is hard to pinpoint without additional SDK logs around the incident (as mentioned in the earlier comment). The custom checkpoint is another factor – it’s logic or connectivity to backing store or store's idempotency guarantee (equivalent to E-Tag in azure blob).

**Comment by psaisandeep** [comment]
Here are the logs from the service from before and after the recent incident: [azure-sdk-FSR-extract-2024-03-26T00 07 15.817Z.csv](https://github.com/Azure/azure-sdk-for-java/files/14750804/azure-sdk-FSR-extract-2024-03-26T00.07.15.817Z.csv)

One interesting thing I noticed was that the `CheckpointStore.listOwnership()` method was called only once when the service was restarted followed by one successful ownership claim for each partition. Afterwards, I see a lot of `Attempting to claim ownership of partition` logs, but no successful claims (i.e. rejected due to mismatches of eTag). I am looking at the code for [PartitionBasedLoadBalancer](https://github.com/Azure/azure-sdk-for-java/blob/main/sdk/eventhubs/azure-messaging-eventhubs/src/main/java/com/azure/messaging/eventhubs/PartitionBasedLoadBalancer.java) and based on what you mentioned, I should be seeing a `CheckpointStore.listOwnership()` call every 30s i.e. upon each invoke of `loadBalance()`, but not happening. Any idea what is going on?

**Comment by psaisandeep** [comment]
Just an update - After realizing that there were no logs suggesting the first load balancer invocation ever finished, I came to the conclusion that this is going in an infinite loop. I changed the load balancing strategy to Balanced now. This has a gradual ownership claim (takes 16mins to fully claim the 32 partitions that I have at the default frequency of once in 30s), but each invocation to load balance finishes fast and I can see the ownership updates regularly (newer and renewal claims). I am going to keep an eye to see if an AMQPException occurs again, but I now have confidence that the lost connection will be reconnected automatically.

**Comment by anuchandy** [comment]
Hello @psaisandeep, is everything okay now, are the partitions reestablishing their connections?

**Comment by psaisandeep** [comment]
Hi - yes, we see a reliable connection from client. I see similar error logs `Operator called default onErrorDropped` occasionally after the change to Balanced load strategy and the client immediately re-establishing a new link.

We can close this thread as resolved, but I am still not sure why the load balancer was going on an infinite loop in Greedy strategy even after taking ownership of all partitions.

**Comment by anuchandy** [comment]
Thank you for the update, glad to hear it's solved your scenario. I’ve created a work item to verify greedy with official checkpoint store.
