### ISSUE TITLE
Introduce a PagedFlux type to support pagination

### ISSUE THREAD

**Issue by JonathanGiles** [Azure/azure-sdk-for-java#3937]
Refer to the [exploratory changes in my repo](https://github.com/Azure/azure-sdk-for-java/compare/master...JonathanGiles:pagedFlux?expand=1).

We need to offer improved pagination APIs. At present our pagination is transparent - users simply receive a Flux<T>, and we transparently unroll the paged responses and put them into a Flux stream.

Rather than this, we should **consider** introducing a `PagedFlux` type. By default (as shown in the repo link above), the user will still be able to work with the common case of Flux<T>, but by calling `byPage()`, the user will be able to get a `Flux<PagedResponse<T>>` and iterate per page, rather than per item.

**Comment by srnagar** [comment]
Done - https://github.com/Azure/azure-sdk-for-java/pull/4045
