### ISSUE TITLE
[FEATURE REQ] In ContainerServiceManager,  on KubernetesClusters creation, network profile definition: add dataplane and plugin mode

### ISSUE THREAD

**Issue by agateaux** [Azure/azure-sdk-for-java#39427]
**Is your feature request related to a problem? Please describe.**
Unlike other SDK or Terraform, if I want to use Cilium CNI, I can't select the dataplane 'cilium' and plugin mode 'overlay'.

**Describe the solution you'd like**
In the `defineNetworkProfile`, add 2 functions: `withNetworkDataplane`, and `withNetworkPluginMode`.

**Describe alternatives you've considered**
None

**Additional context**
These operations exist on update, as you can use `withNetworkProfile`, and a `ContainerServiceNetworkProfile` contains these operations.

**Information Checklist**
Kindly make sure that you have added all the following information above and checkoff the required fields otherwise we will treat the issuer as an incomplete report
- [x] Description Added
- [x] Expected solution specified

**Comment by joshfree** [comment]
Thanks for reaching out to us via this github issue, @agateaux.  @weidongxu-microsoft could you help route this feature request?

**Comment by weidongxu-microsoft** [comment]
@v-hongli1 

Please add config stages
- networkPluginMode
- networkPolicy
- networkMode
- networkDataplane

All is optional stages. Let's target 2.38.0 in April.
