### ISSUE TITLE
Cosmos DB Sample Issue

### ISSUE THREAD

**Issue by faynef** [Azure/azure-sdk-for-java#39447]
1.

**Section** [link](https://github.com/Azure/azure-sdk-for-java/blob/main/sdk/cosmos/azure-cosmos/src/samples/java/com/azure/cosmos/ReadmeSamples.java#L615):

![image](https://github.com/Azure/azure-sdk-for-java/assets/138087452/d2def217-aac4-4ac3-bdcd-f2c88a574832)

**Reason**: 
Run method [replaceItemAsyncSample()](https://github.com/Azure/azure-sdk-for-java/blob/main/sdk/cosmos/azure-cosmos/src/samples/java/com/azure/cosmos/AsyncContainerCodeSnippets.java#L182) show: java.lang.IllegalArgumentException: Can't serialize the object into the json string.

**Suggestion**:
Add code:
```
        public String getEmail() { return email; }
        public String getName() { return name; }
        public String getDeparture() { return departure; }
        public String getDestination() { return destination; }
````

@sandeep-sen , @joshfree , @kyle-patterson , @KrzysztofCwalina and @aayush3011 for notification.

**Comment by faynef** [comment]
After testing we found that you did not add the `public` modifier to the update code and the issue was not fixed.@tvaron3

**Comment by tvaron3** [comment]
> After testing we found that you did not add the `public` modifier to the update code and the issue was not fixed.@tvaron3

Just merged in the change.
