### ISSUE TITLE
[OpenAI-Assistant] Add Server Sent Events (SSE) support

### ISSUE THREAD

**Issue by mssfang** [Azure/azure-sdk-for-java#39462]
Reference:

https://platform.openai.com/docs/api-reference/assistants-streaming

**Comment by jpalvarezl** [comment]
For more context, the PR introducing the changes in the spec required to support this feature are coming from this [here](https://github.com/Azure/azure-sdk-for-java/pull/38742)

**Comment by gloriousknight** [comment]
Hello, I am currently using the assistant feature in Azure, and I noticed that stream functionality is not supported in the 2024-02-15-preview version. I have been following your team's development work for a while now. Is there an estimated release date for the [assistants-streaming](https://platform.openai.com/docs/api-reference/assistants-streaming) function?

**Comment by jpalvarezl** [comment]
Hello @gloriousknight currently is hard to give you a specific date, but we are hoping no later than end of May. This is currently in progress and there are a few moving pieces that need to align first.
