### ISSUE TITLE
[OpenAI] Enable stream-style-serialization Inference

### ISSUE THREAD

**Issue by mssfang** [Azure/azure-sdk-for-java#39464]
- OpenAI Inference:

We [disable stream-style-serialization](https://github.com/Azure/azure-rest-api-specs/blob/main/specification/cognitiveservices/OpenAI.Inference/tspconfig.yaml#L35) because
we still have [customization with Jackson](https://github.com/Azure/azure-sdk-for-java/blob/main/sdk/openai/azure-ai-openai/customization/src/main/java/ChatCompletionsToolCallCustomizations.java#L25) or bug in emitter/core that not able to do this at present.

Other PR reference: https://github.com/Azure/azure-sdk-for-java/pull/39287

- OpenAI Assistant:
WIP: https://github.com/Azure/azure-sdk-for-java/issues/38725#issuecomment-2019464594

**Comment by jpalvarezl** [comment]
I updated the title of the issue just to reflect that this is specific to the Inference SDK :)
