### ISSUE TITLE
[BUG]@CreatedDate annotated field is not being saved through saveAll()

### ISSUE THREAD

**Issue by sayantani1206** [Azure/azure-sdk-for-java#39562]
**Describe the bug**
@CreatedDate[imported from org.springframework.data.annotation] annotated field in EntityObject is not getting saved when trying to save multiple data through saveAll() of SimpleCosmosRepository.java, while save() is working fine with this annotation. 
Reason Suspected: markAuditedIfConfigured() is responsible for Date/Time insertion in Cosmos DB -- which is being used in save(). In saveAll(), its not there which is causing this. What we need to do to resolve this using saveAll()?

***Exception or Stack Trace***
No exception. @CreatedDate/@ModifiedDate annotated fields are not getting saved in DB

**To Reproduce**
Annotate any date in Entity object with said annotations or annotation from org.springframework.data. Try to save bulk data with saveAll()

***Code Snippet***
Add the code snippet that causes the issue.
  public <S extends T, T> Iterable<S> insertAll(CosmosEntityInformation<T, ?> information, Iterable<S> entities) {
        Assert.notNull(entities, "entities to be inserted should not be null");
        String containerName = information.getContainerName();
        Class<T> domainType = information.getJavaType();
        List<CosmosItemOperation> cosmosItemOperations = new ArrayList();
        entities.forEach((entity) -> {
            this.generateIdIfNullAndAutoGenerationEnabled(entity, domainType);
            JsonNode originalItem = this.mappingCosmosConverter.writeJsonNode(entity);
            PartitionKey partitionKey = new PartitionKey(information.getPartitionKeyFieldValue(entity));
            CosmosBulkItemRequestOptions options = new CosmosBulkItemRequestOptions();
            this.applyBulkVersioning(domainType, originalItem, options);
            cosmosItemOperations.add(CosmosBulkOperations.getUpsertItemOperation(originalItem, partitionKey, options));
        });

**Expected behavior**
I wanted it saveAll should behave like save() with springData annotated field as well

**Screenshots**
for insertAll()
<img width="674" alt="image" src="https://github.com/Azure/azure-sdk-for-java/assets/166130469/6e4eb394-399e-4e5b-a5a1-2a72c9d0593c">
For insert() -> highlighted which is responsible to save the springData annotated field(@CreatedDate)
<img width="650" alt="image" src="https://github.com/Azure/azure-sdk-for-java/assets/166130469/768e9c3a-7fa6-45f6-8c98-14bdc4051c6e">

**Setup (please complete the following information):**
 - OS: any OS
 - IDE: Intellij
 - Library/Libraries: [e.g. com.azure:azure-core:1.16.0 (groupId:artifactId:version)]
 - Java version:8 or above 
 - App Server/Environment: [e.g. Tomcat, WildFly, Azure Function, Apache Spark, Databricks, IDE plugin or anything special]
 - Frameworks: Spring Boot/GRPC

If you suspect a dependency version mismatch (e.g. you see `NoClassDefFoundError`, `NoSuchMethodError` or similar), please check out [Troubleshoot dependency version conflict article](https://aka.ms/azsdk/java/dependency/troubleshoot) first. If it doesn't provide solution for the problem, please provide:
- verbose dependency tree (`mvn dependency:tree -Dverbose`)
- exception message, full stack trace, and any available logs

**Additional context**

**Information Checklist**
Kindly make sure that you have added all the following information above and checkoff the required fields otherwise we will treat the issuer as an incomplete report
- [ ] Bug Description Added
- [ ] Repro Steps Added
- [ ] Setup information Added

**Comment by kushagraThapar** [comment]
@sayantani1206 - thanks for creating this issue, its currently being worked on and is in development. @trande4884 please provide further updates once the PR is out.
