### ISSUE TITLE
[BUG] azure-core-http-netty 1.14.2 contains wrong netty.version property

### ISSUE THREAD

**Issue by blackr1234** [Azure/azure-sdk-for-java#39583]
# Issue description

Netty utility class is expecting an older version of Netty dependencies in `azure-core-http-netty 1.14.2`.

Check this POM file in the public Maven repo:

[azure-core-http-netty-1.14.2.pom](https://repo1.maven.org/maven2/com/azure/azure-core-http-netty/1.14.2/azure-core-http-netty-1.14.2.pom)

We can see that there are different version numbers of Netty:

- `4.1.101.Final` (the `netty.version` project property)
- `4.1.108.Final` (all individual Netty dependency versions)

Now, compare with the previous version:

[azure-core-http-netty-1.14.1.pom](https://repo1.maven.org/maven2/com/azure/azure-core-http-netty/1.14.1/azure-core-http-netty-1.14.1.pom)

We can see that it only contains a single version number, i.e. `4.1.101.Final`.

---

# Impact

It is causing the `azure-core-http-netty.properties` file to contain wrong Netty version.

- Expected: `4.1.108.Final`
- Actual: `4.1.101.Final`

This value, if I guess right, is populated with the `netty.version` Maven property.

See: [azure-core-http-netty.properties (`1.14.2`)](https://github.com/Azure/azure-sdk-for-java/blob/azure-core-http-netty_1.14.2/sdk/core/azure-core-http-netty/src/main/resources/azure-core-http-netty.properties)

---

# Exception or error

There is one `WARN` level log:

> The following Netty dependencies have versions that do not match the versions specified in the azure-core-http-netty pom.xml file. This may result in unexpected behavior. If your application runs without issue this message can be ignored, otherwise please update the Netty dependencies to match the versions specified in the pom.xml file. Versions found in runtime: 'io.netty:netty-common' version: 4.1.108.Final (expected: 4.1.101.Final),'io.netty:netty-handler' version: 4.1.108.Final (expected: 4.1.101.Final),'io.netty:netty-handler-proxy' version: 4.1.108.Final (expected: 4.1.101.Final),'io.netty:netty-buffer' version: 4.1.108.Final (expected: 4.1.101.Final),'io.netty:netty-codec' version: 4.1.108.Final (expected: 4.1.101.Final),'io.netty:netty-codec-http' version: 4.1.108.Final (expected: 4.1.101.Final),'io.netty:netty-codec-http2' version: 4.1.108.Final (expected: 4.1.101.Final),'io.netty:netty-transport-native-unix-common' version: 4.1.108.Final (expected: 4.1.101.Final),'io.netty:netty-transport-native-epoll' version: 4.1.108.Final (expected: 4.1.101.Final),'io.netty:netty-transport-native-kqueue' version: 4.1.108.Final (expected: 4.1.101.Final)

**Comment by alzimmermsft** [comment]
Thanks for filing this issue @blackr1234.

Yes, looks like this was a mistake in the latest release. Good news is, this isn't a functional issue, bad news is that this is likely annoying and a red herring.

Will have a PR out soon fixing this

**Comment by blackr1234** [comment]
Hi @alzimmermsft ,

Thanks for fixing it.
Is there a release date for a new version of this library (or the whole Azure SDK for Java) that you or your team could share?
Thanks!

**Comment by alzimmermsft** [comment]
Hi @blackr1234, given this is just an invalid validation which doesn't affect the runtime of the application we are planning to release this in May as part of our regular release schedule. While azure-core-http-netty will always log on startup / loading of the class due to this, it'll still report the correct versions being used, it just won't report the correct versions the SDKs are expecting.

I'll follow-up here once again when there is a new version of azure-core-http-netty that contains this fix.
