### ISSUE TITLE
Discuss get_token() per-request pipeline setting behavior across languages

### ISSUE THREAD

**Issue by xiangyan99** [Azure/azure-sdk-for-java#39596]
While we were migrating Python MI to using msal, we found Python msal did not support per-request setting and this was their design.

Per the discussion, seems like it is not for Python msal only. Let's discuss the behavior across all languages and then we can decide how we want to request the support from msal libraries.

**Comment by alzimmermsft** [comment]
@billwert @g2vinay I'm assigning this to you as it appears to be an Identity ask, may be something that needs external tracking as well

**Comment by billwert** [comment]
Instead of bringing this to other languages for now, we have decided to hold it back on Python with the move to MI in MSAL. If there is customer feedback we will revisit. @xiangyan99
