### ISSUE TITLE
[FEATURE REQ] Enhancement for RetryStrategy

### ISSUE THREAD

**Issue by waynewang1989** [Azure/azure-sdk-for-java#39646]
**Is your feature request related to a problem? Please describe.**
Currently , the [RetryStrategy](https://github.com/Azure/azure-sdk-for-java/blob/main/sdk/core/azure-core/src/main/java/com/azure/core/http/policy/RetryStrategy.java) can only do calculateRetryDelay within the context. There's no way for a more detailed retry strategy configuration setup. Think of the following scenario:
1. I want to do fixed delay and retry on response code 429, maximum retry count is 60 times. 
2. For other should retry scenarios, keeps the default strategy.

**Describe the solution you'd like**
A more fine-grained RetryStrategy configuration interface.

**Describe alternatives you've considered**
1. Adding or updating current interface of RetryStrategy to support it.
2. Adding a new impl of the existing RetryStrategy and when RetryPolicy uses RetryStrategy, check if the configured RetryStrategy is the new one. If not, use the default impl.

**Additional context**
NA

**Information Checklist**
Kindly make sure that you have added all the following information above and checkoff the required fields otherwise we will treat the issuer as an incomplete report
- [x] Description Added
- [x] Expected solution specified

**Comment by alzimmermsft** [comment]
Thank you for filing this feature request @waynewang1989.

Would an API such as `RetryStrategy.calculateRetryDelay(RequestRetryConditions)` be sufficient to allow your use case?
