### ISSUE TITLE
Add `URL getURL()` method on clients

### ISSUE THREAD

**Issue by jianghaolu** [Azure/azure-sdk-for-java#3966]

**Comment by JonathanGiles** [comment]
If we plan to introduce, e.g. `BlobClientBuilder.blobUrl(..)` API, we should consider two things:

1. Making the `BlobClient.getUrl` method have the same name, e.g. `getBlobUrl()`
2. The lack of symmetry between `BlobClientBuilder.blobUrl(String)` and `URL getBlobUrl()`
