### ISSUE TITLE
[BUG] Processor client error handler not called when ASB subscription is deleted

### ISSUE THREAD

**Issue by blackr1234** [Azure/azure-sdk-for-java#39669]
# How to reproduce

1. Create a `ServiceBusProcessorClient` object with `processError(Consumer<ServiceBusErrorContext>)` that will print an error with the error context object in the console log.
2. Start the program.
3. Delete the ASB subscription on Azure Portal or by SDK API.
4. Observe console log and check if a log message is printed.

---

# Sample code

```java
public class MainSubscribe {
    public static final String conn = "Endpoint=sb://xxx";
    public static final String topic = "an-existing-topic";
    public static final String sub = "an-existing-subscription";

    public static void main(String[] args) {
        ServiceBusProcessorClient client = new ServiceBusClientBuilder()
                .connectionString(conn)
                .processor()
                .topicName(topic)
                .subscriptionName(sub)
                .processMessage(e -> {
                    System.out.println("message: " + e.getMessage().getBody().toString());
                })
                .processError(e -> {
                    System.err.println("error: " + e);
                })
                .disableAutoComplete()
                .buildProcessorClient();

        client.start();
    }
}
```

---

# Behaviors

Expected:

- Execute my error handler logic which will print the error context object in console log when I delete the subscription.
- It will retry connection for a few times (or infinite times) without exiting the program.
- If we recreate the subscription while the program is still running, it recovers and is ready to receive messages.

Actual:

- Does not execute my error handler logic, so my error log is not printed in console log when I delete the subscription.
- Retry does not happen and the program simply exits.

---

# Maven dependencies

- Parent POM: `spring-boot-starter-parent` at `3.1.2`
- Dependency managements
  - `spring-cloud-azure-dependencies` (test with `5.9.1` and `5.8.0`)
- Dependencies
  - `spring-cloud-azure-stream-binder-servicebus` (managed version)

---

# SDK version details

- Problematic versions: `5.9.1` and above, including `5.11.0`
  - Not sure about `5.9.0` as it requires Java 21 due to a bug and I'm on 17.
- Working version: `5.8.0` and below

**Comment by blackr1234** [comment]
Updated post with dependency information and detailed descriptions of the expected and actual behaviors.

**Comment by anuchandy** [comment]
Hello @blackr1234, 

I was testing this, and as you observed the error is not propagated but unlike your case, the ServiceBusProcessorClient kept retried and connected to the entity as soon as I re-created the entity, then it resumed pumping messages.

I think your application setup is running into this https://github.com/Azure/azure-sdk-for-java/issues/30170

So the point here is – the start() call will start the asynchronous message pumping using demon-threads. If the main/application (non-demon) thread exits for any reason, then the demon-threads pumping the messages will be killed by the JVM. 

This is likely the case you’re running into. The easiest way to check this is by using a simple Java console application,
1.	with the code you shared.
2.	Put a sleep(10min) after the client.start()
3.	Now delete the entity (queue, subscription), in the logs you will see retry happening.
4.	Recreate the entity from portal (before the sleep(10min) expires), you should see the processor connecting to the entity.

**Comment by blackr1234** [comment]
@anuchandy 

Actually what I reported happens to a Spring Boot Starter Web application running in AKS as well. The app (in JVM) keeps running but the error handler doesn't get called.

I think you misunderstood the whole point. I expect both the error handler to get called and the retry to happen.

After adding a `Thread.sleep`, yes it does keep running printing some logs and when I recreate the subscription manually, it stops printing logs.
However, my error handler function doesn't get called.

In my use case, I am relying on the error handler to recreate the subscription when the subscription gets deleted, in version `5.8.0` and below, it will give me an error context with `ServiceBusFailureReason.MESSAGING_ENTITY_NOT_FOUND`. In `5.9.1` and above, my error handler function doesn't get called.

I don't see this change mentioned in the changelog. Do you mind telling me if it is mentioned anywhere in docs, and how my program can know if the subscription is missing or deleted?

Thanks.

**Comment by anuchandy** [comment]
I see. Okay, my first focus was on reported observation where _program exit without retry_, so wanted to debug if the Processor was stopping it's "reconnect attempts" (here after entity deletion). Since Spring has a non-demon + always running parent thread, Processor’s internal reconnect attempts should not stop.

Thank you for the additional context around the application specific dependency on error inspection, it clarifies the end-to-end use case. I'll compare Processor's behavior in 5.8.0 versus 5.9.1 and get back.

**Comment by anuchandy** [comment]
Hello @blackr1234, I looked into this, and the dropping of error notification is now addressed in https://github.com/Azure/azure-sdk-for-java/pull/39723. Thank you for reporting this.
