### ISSUE TITLE
[BUG] Service Bus Listen claim error on second instance 

### ISSUE THREAD

**Issue by Tordu5** [Azure/azure-sdk-for-java#39677]
**Describe the bug**
When using two Azure Spring App instances, one does not receive any list claims for a subscription. This happens after an update of the azure libs. After the reroll to the old versions both instancen are connecting and consuming from the subscription

***Exception or Stack Trace***

>   { 
>     logger: com.azure.core.amqp.implementation.MessageFlux
>     message: {
>       az.sdk.message: MessageFlux reached a terminal error-state, signaling it downstream.
>       connectionId: MF_9c24e9_1712856787476
>       entityPath: xxx-topic/subscriptions/xxx-subscription
>       exception: Unauthorized access. 'Listen' claim(s) are required to perform this operation. Resource: 'sb://xxx-namespace-prod.servicebus.windows.net/xxx-topic/subscriptions/xxx-subscription'. TrackingId:fefe38a7bddb4454a96f64b95ebfb790_G8, SystemTracker:gateway5, Timestamp:2024-04-11T17:33:07, errorContext[NAMESPACE: xxx-namespace-prod.servicebus.windows.net. ERROR CONTEXT: N/A, PATH: xxx-topic/subscriptions/xxx-subscription, REFERENCE_ID: xxx-topic/subscriptions/xxx-subscription_8e4d9a_1712856787476, LINK_CREDIT: 0]
>       linkName: xxx-topic/subscriptions/xxx-subscription_8e4d9a_1712856787476
>       messageFlux: mf_f49078_1712856787476
>     }
>     severity: WARN
>     thread: receiverPump-2
>   }

**To Reproduce**
When i deploy two instances on the Spring Plattform 

***Code Snippet***
private final TokenCredential credential = new DefaultAzureCredentialBuilder().build();

        ServiceBusProcessorClient processorClient = new ServiceBusClientBuilder()
            .fullyQualifiedNamespace(this.fullyQualifiedNamespace)
            .credential(this.credential)
            .processor()
            .maxConcurrentCalls(amountConcurrentMessages)
            .topicName(topicName)
            .subscriptionName(subscriptionName)
            .processMessage(processMessageCallback)
            .processError(processErrorCallback)
            .buildProcessorClient();

        processorClient.start();

**Expected behavior**
Both instances should connect and consume from the subscription

**Setup (please complete the following information):**
 - IDE: [e.g. IntelliJ]
 - Library/Libraries: 
    implementation 'com.azure:azure-core:1.48.0'
    implementation 'com.azure:azure-messaging-servicebus:7.15.2' 
    implementation 'com.azure:azure-identity:1.11.4'
 - Java version: 11
 - App Server/Environment: [e.g. Azure Spring App (Spring Boot 2), Azure Service Bus (Topics and queues), Postgres single server] 

**Additional context**
We updated the libs
    implementation 'com.azure:azure-core:1.48.0'  **1.25.0 -> 1.48.0**
    implementation 'com.azure:azure-messaging-servicebus:7.15.2' **7.6.0 -> 7.15.2**
    implementation 'com.azure:azure-identity:1.11.4' **1.5.2 -> 1.11.4**

The App is created with terraform and the role "Azure Service Bus Data Owner" is added. Its a premium instance of the Service bus and the Plattform and the Service Bus Message Unit are in the same resource group. 

With the old versions a send claims error behavior occured from time to time and stayed for couple minutes. We hoped to fix that problem with the update of the version but now we see the listen claim error on the second instance. A reroll to the old version fixed that behavior

**Comment by anuchandy** [comment]
Hello @Tordu5, From the Service Bus SDK side, it treats the credential obtained from the configured source as an opaque value and uses it to authorize. This is an error coming from the Service when it detects that the presented token is missing claims (listen) needed to read the message. If this happens intermittently while the application is running, it seems there is a period during which the current credentials get invalid (some transition process, e.g., credential rotation). So, it is unlikely that this is related to a specific Service Bus SDK version but it’s more of the environment/host running the application.

**Comment by anuchandy** [comment]
Provided potential reasons for service to return this error. At the moment there is no investigation pending on the SDK side.
