### ISSUE TITLE
[QUERY] Private DNS integration for Azure Private Endpoint

### ISSUE THREAD

**Issue by SvenScheurer** [Azure/azure-sdk-for-java#39711]
**Query/Question**
I've encountered an issue while working with the Java SDK for Azure. It appears the SDK does not support creating **PrivateEndpoint(Inner)** with **Private DNS integration** - I've only found an option to set a `customDnsConfigs`.
Based on the provided documentation, private DNS zone configurations automatically generate only if you use the recommended naming scheme (`privatelink.postgres.database.azure.com`). My code duly creates a DNS zone with the proper name, however, it isn't automatically configured in the PE.
Is there a workaround to integrate the private DNS zone through the SDK? Using custom DNS seems a bit tedious compared to the out-of-the-box Private DNS integration offered via the Azure portal, which would also work with the DNS zone I've created.

I'm pretty much using the exact code posted in https://github.com/Azure/azure-sdk-for-java/issues/12646#issuecomment-664796886

***Why is this not a Bug or a Feature Request?***
I believe this is not a bug because the SDK is functioning as described in the documentation. Instead, it seems to be an area that lacks certain functionality. I'm not requesting this as a new feature but am inquiring if there is an existing way to achieve what I need.

**Setup (please complete the following information if applicable):**
Library/Libraries: com.azure.resourcemanager:azure-resourcemanager:2.37.0

 **Information Checklist**
 Kindly make sure that you have added all the following information above and checkoff the required fields otherwise we will treat the issuer as an incomplete report
- [x] Query Added
- [x] Setup information Added

**Comment by XiaofeiCao** [comment]
@SvenScheurer The [code](https://github.com/Azure/azure-sdk-for-java/issues/12646#issuecomment-664796886) you shared is our old Track1 lib.

The one you are using is new Track2 lib. Would you try the following sample code(replace the `resourceId` and `subResource` with your private DNS resource)?
https://github.com/Azure/azure-sdk-for-java/blob/3622186404feb2b2d2dceb2dfacf7e9ed590997a/sdk/resourcemanager/azure-resourcemanager-samples/src/main/java/com/azure/resourcemanager/network/samples/ManagePrivateLink.java#L123-L132

**Comment by SvenScheurer** [comment]
Thanks @XiaofeiCao for your input. 
I forgot to mention that I want to create the Private Endpoint for my **Azure PostgreSQL Flexible Server instance**(which is GA since end Q1 2024 -> https://techcommunity.microsoft.com/t5/azure-database-for-postgresql/private-link-based-networking-is-now-generally-available-in/ba-p/4088711). I've attached a screenshot of the configuration in the Azure portal 
for reference where this is configurable.

<img width="712" alt="Screenshot 2024-04-15 at 4 26 06 PM" src="https://github.com/Azure/azure-sdk-for-java/assets/21037725/0832b714-b02d-4417-8a11-7b88821fbedb">

Currently, my `PrivateLinkServiceConnection` points to the PostgreSQL server.
With the Track2 lib you've mentioned, I don't see a `PrivateLinkSubResourceName` that corresponds to either PG Flexible Server or the Private DNS resource. 
Not sure if I understood, but replacing the Blob `resourceId` and `subResource` wouldn't quite work in this case, would it?
Maybe you can help me understand what I'd need to do?

**Comment by XiaofeiCao** [comment]
@SvenScheurer 
Got it. `subResource` seems not included in our SDK. You could try
```java
// https://learn.microsoft.com/en-us/azure/private-link/private-endpoint-dns#databases-1
.withSubResource(PrivateLinkSubResourceName.fromString("postgresqlServer"))
```

Yeah, there's extra work to do to integrate with Private DNS Zone.
Steps are similar with the sample code.
1. Define your Virtual Network https://github.com/Azure/azure-sdk-for-java/blob/3622186404feb2b2d2dceb2dfacf7e9ed590997a/sdk/resourcemanager/azure-resourcemanager-samples/src/main/java/com/azure/resourcemanager/network/samples/ManagePrivateLink.java#L112-L120
2. Define PrivateEndpoint https://github.com/Azure/azure-sdk-for-java/blob/3622186404feb2b2d2dceb2dfacf7e9ed590997a/sdk/resourcemanager/azure-resourcemanager-samples/src/main/java/com/azure/resourcemanager/network/samples/ManagePrivateLink.java#L124-L132
3. Get private Ip https://github.com/Azure/azure-sdk-for-java/blob/3622186404feb2b2d2dceb2dfacf7e9ed590997a/sdk/resourcemanager/azure-resourcemanager-samples/src/main/java/com/azure/resourcemanager/network/samples/ManagePrivateLink.java#L137
4. Get domain name for your Postgresql instance(This one is using another lib azure-resourcemanager-postgresqlflexibleserver, let us know if you need assistance on that) https://github.com/Azure/azure-sdk-for-java/blob/7a209fcdae407575da8e88cffcca0def41586e17/sdk/postgresqlflexibleserver/azure-resourcemanager-postgresqlflexibleserver/src/main/java/com/azure/resourcemanager/postgresqlflexibleserver/models/Server.java#L116
5. Create(Integrate with) Private DNS Zone https://github.com/Azure/azure-sdk-for-java/blob/3622186404feb2b2d2dceb2dfacf7e9ed590997a/sdk/resourcemanager/azure-resourcemanager-samples/src/main/java/com/azure/resourcemanager/network/samples/ManagePrivateLink.java#L189-L200

**Comment by SvenScheurer** [comment]
I've now changed my code accordingly, where I first create my PG Flexible Server instance.
Afterward, I create the Private Endpoint, place it in my subnet, and link it to the PG service.
Creating the PrivateDnsZone works fine, however, from the endpoint, I still cannot see the DNS configuration being populated.
<img width="1162" alt="Screenshot 2024-04-16 at 4 32 29 PM" src="https://github.com/Azure/azure-sdk-for-java/assets/21037725/77f93cd6-62b1-47ee-a8f6-ff479b0025a3">
<img width="1189" alt="Screenshot 2024-04-16 at 4 32 51 PM" src="https://github.com/Azure/azure-sdk-for-java/assets/21037725/ff2609d7-550e-4362-9c90-8ace1c41ba99">

What am I missing? It looks like everything is implemented as you have described, but I'm still facing connectivity issues from one VM in the same subnet when trying to access the PE.

**Comment by SvenScheurer** [comment]
Thanks @XiaofeiCao
That worked for me.
