### ISSUE TITLE
[FEATURE REQ] Azure Keyvault JAR Signer missing Intermediate Cert Chain

### ISSUE THREAD

**Issue by wpabon123** [Azure/azure-sdk-for-java#39715]
I'm using KeyVault jarsigner provider version 2.8.1. The signing works fine but when I verify the JAR file, I get the error that the chain trust cannot be verified. The code signing cert was created by DigiCert. That cert has the full chain of trust so no idea why the jarsigner is not capturing the whole chain of trust.

This is the error message I receive:
"This jar contains entries whose certificate chain is not validated."

Sounds to me this could be an issue associated with the JAVA versions used but not sure.

**Comment by ThatCheck** [comment]
Same here

@wpabon123 Are you able to solve the problem ?

**Comment by joshfree** [comment]
@vcolin7 please follow up with @wpabon123 and @ThatCheck on this github issue; thank you

**Comment by vcolin7** [comment]
Adding @saragluna from the team that owns this package (`com.azure:azure-security-keyvault-jca:2.8.1`). Xiaolu, is there any way customers could sync the chain to verify so all certs are in the local keystore?

@wpabon123 Are you not able to get the lower-level certificate out of the Key Vault or are you not allowed to by the new requirements you mentioned?

**Comment by saragluna** [comment]
Yes, the cert chain valiation is missing from the library, we could add that.

**Comment by KJW812** [comment]
Did you find an anser for this?  I am finding the same issue using a DigiCert code signing request that is stored in Azure Key Vault.  I converted the p7b to base64 as per the Azure requirement which should have preserved the cert chain.  However, when I sign a JAR file using jarsigner it only has the code signing cert in the signer when I verify.  This is causing Oracle EBS to treat JARs as unsigned as the SignerCA is DigiCert on the users desktops, not my OU

**Comment by rujche** [comment]
FYI: This issue will be solved by this PR: https://github.com/Azure/azure-sdk-for-java/pull/41303
