### ISSUE TITLE
Read metadata of multiple files stored in a directory using azure data lake client in java

### ISSUE THREAD

**Issue by jagriti92m** [Azure/azure-sdk-for-java#39732]
**Query/Question**
Hi,
How can we read metadata of multiple files stored in a directory in a single call using the Azure Data Lake client in Java?
Currently, I am making two different calls, one to get the data lake file client dataLakeFileSystemClient.getFileClient(filePath) and second to get Path properties  dataLakeFileClient.readToFile(fileName, true) to  extract metadata.

**Setup (please complete the following information if applicable):**
 - OS: macOS
 - IDE: IntelliJ
 - Library/Libraries: azure-storage-file-datalake
 
 **Information Checklist**
 Kindly make sure that you have added all the following information above and checkoff the required fields otherwise we will treat the issuer as an incomplete report
- [x] Query Added
- [x] Setup information Added

Thanks,
Jagriti

**Comment by ibrahimrabab** [comment]
Hi @jagriti92m 
You need to grab the DataLakeFileClient in order to read from the file and grab the properties. Both calls are necessary in order to read the metadata of the file. 

Let us know if you have any other questions!

**Comment by jagriti92m** [comment]
Hi @ibrahimrabab,

Is there a method to retrieve metadata for multiple files stored in a directory using the DataLakeFileClient in Java with just one single call. I need to continuously read metadata for a specified list of files. Is there a way to minimise the number of calls made to retrieve this metadata when using the DataLakeFileClient in Java?

Thanks,
Jagriti

**Comment by ibrahimrabab** [comment]
Hi @jagriti92m 
As of right now the only way to retrieve the metadata for each file is to either read the file (either through readToFile() or read()) or call getProperties().getMetadata(). You can try doing DataLakeFileSystemClient.listPaths() which will return you all the files and directories under the file system, but in order to obtain each item's metadata you must make a call to getProperties() or read the file.
