### ISSUE TITLE
[FEATURE REQ] Support overriding the endpoint for NonAzureOpenAIClientService

### ISSUE THREAD

**Issue by viswanathk** [Azure/azure-sdk-for-java#39742]
**Is your feature request related to a problem? Please describe.**
The current OpenAI API is used by multiple providers, and Azure SDK is the only "official" Java SDK that supports this API. However, the endpoint is hardcoded in this [file](https://github.com/Azure/azure-sdk-for-java/blob/main/sdk/openai/azure-ai-openai/src/main/java/com/azure/ai/openai/implementation/NonAzureOpenAIClientImpl.java#L849) limiting it's usefulness to be used with other providers.

**Describe the solution you'd like**
Allow the client to override the endpoint along with other attributes when constructing the `NonAzureOpenAIClientImpl` object so it can be used internally within companies (if there's an internal gateway that proxies that request), or use this with other providers.

**Describe alternatives you've considered**
The other option would be for another implementation of the API in java, which is completely needless.

**Additional context**
NA

**Information Checklist**
Kindly make sure that you have added all the following information above and checkoff the required fields otherwise we will treat the issuer as an incomplete report
- [x] Description Added
- [x] Expected solution specified

**Comment by alzimmermsft** [comment]
@mssfang could you follow-up

**Comment by mssfang** [comment]
@viswanathk Recently we get this feature ask and waiting to see if we should support it in the SDK. Will keep you updated.

https://github.com/Azure/azure-sdk-for-java/pull/39659

**Comment by viswanathk** [comment]
@mssfang any timeline for this? :)

**Comment by mssfang** [comment]
Unfortunately, we will not support non-OpenAI models in this SDK, azure-ai-openai as per our partnership with OpenAI.
The most major models are available as first-class Azure Host Endpoints, such as Llama2, Cohere and Mistra, via Azure MaaS ([Azure AI Studio Model Catalog](https://learn.microsoft.com/en-us/azure/ai-studio/how-to/model-catalog)). They can also host most Hugging Face models or your own models in the future via Azure MaaP(AML) in the future. We will provide an ("OpenAI like") Model Inference API spec for completions to MaaS in the near future.

Worth to mention here that this SDK support [proxy feature](https://github.com/Azure/azure-sdk-for-java/blob/main/sdk/openai/azure-ai-openai/src/samples/java/com/azure/ai/openai/OpenAIProxySample.java) in case someone not aware it.
