### ISSUE TITLE
[QUERY] Is there a way to set config for CosmosClientBuilder

### ISSUE THREAD

**Issue by VivekVinushanth** [Azure/azure-sdk-for-java#39785]
**Query/Question**
Is there a way to set CosmosClientBuilder with COSMOS.UNAVAILABLE_LOCATIONS_EXPIRATION_TIME_IN_SECONDS config so that it can be consumed at GlobalEndpointManager. 

***Why is this not a Bug or a feature Request?***
A clear explanation of why is this not a bug or a feature request?

**Setup (please complete the following information if applicable):**
 - IDE: [e.g. IntelliJ]
 - Library/Libraries: [e.g. com.azure:azure-core:1.16.0 (groupId:artifactId:version)]
 
 **Information Checklist**
 Kindly make sure that you have added all the following information above and checkoff the required fields otherwise we will treat the issuer as an incomplete report
- [x] Query Added
- [ ] Setup information Added

**Comment by TheovanKraay** [comment]
These variables cannot be set in CosmosClientBuilder, but can be set as system properties in JVM. E.g.:

`mvn exec:java -DCOSMOS.UNAVAILABLE_LOCATIONS_EXPIRATION_TIME_IN_SECONDS=320 -Dexec.mainClass="com.azure.cosmos.examples.crudquickstart.async.SampleCRUDQuickstartAsync" -DACCOUNT_HOST=your account hostname -DACCOUNT_KEY=your account master key`

**Comment by VivekVinushanth** [comment]
It works. Thanks
