### ISSUE TITLE
[QUERY] Getting BlockCountExceedsLimit error code from blob storage. 

### ISSUE THREAD

**Issue by kirankumar994** [Azure/azure-sdk-for-java#39896]
**Query/Question**
I am trying to upload large files using the below code. However, I am getting an exception with error code of BlockCountExceedsLimit and sometimes BlockListTooLong error code. Here is the code. I know, when I upload a file which is > 50 it is exceeding 50K blocks as each block is staging with 1024 bytes by default with the below code. I would need your help to increase the block size of each chunk from the filepart. 

`public Mono<Document> handleFileUpload(Mono<FilePart> file,
                                           Document document,
                                           Map<String, String> tags,
                                           Map<String, String> metadata) {

        BlobContainerAsyncClient blobContainerAsyncClient = blobServiceAsyncClient.getBlobContainerAsyncClient(
                document.getDocumentLibraryId()
        );

        BlobAsyncClient blobAsyncClient = blobContainerAsyncClient.getBlobAsyncClient(
                buildDocumentName(document)
        );

        BlockBlobAsyncClient blockBlobAsyncClient = blobAsyncClient.getBlockBlobAsyncClient();

        return file.flatMapMany(FilePart::content)
                .flatMapSequential(dataBuffer -> {

                    // Convert DataBuffer to ByteBuffer
                    ByteBuffer byteBuffer = dataBuffer.asByteBuffer();
                    // Generate random UID for each block (for each chunk)
                    // Staging each chunk as a block on azure
                    String blockID = Base64.getEncoder()
                            .encodeToString(UUID.randomUUID().toString().getBytes(StandardCharsets.UTF_8));

                    return blockBlobAsyncClient.stageBlock(blockID, BinaryData.fromByteBuffer(byteBuffer))
                            .thenReturn(blockID);

                })
                .collectList() // Collect all sequential blocks to commit (Preparing the whole blob)
                .flatMap(blockIds -> blockBlobAsyncClient.commitBlockListWithResponse(
                                new BlockBlobCommitBlockListOptions(blockIds)
                                        .setMetadata(metadata)
                                        .setTags(tags)
                        ) // Commits the blob with all blocks (smaller chunks)
                )
                .then(Mono.just(document));
    }`

The exception I am getting is
com.azure.storage.blob.models.BlobStorageException: Status code 409, "﻿<?xml version="1.0" encoding="utf-8"?><Error><Code>BlockCountExceedsLimit</Code><Message>The uncommitted block count cannot exceed the maximum limit of 100,000 blocks.
RequestId:8eebd8b7-501e-00f7-2e39-9666ad000000
Time:2024-04-24T11:19:01.4805998Z</Message></Error>"

**Comment by kirankumar994** [comment]
"/unresolve".

Hi @alzimmermsft ,

Could you please me how to increase filepart.content() to make larger chunks to return ByteBuffer larger than 1024 bytes with the above code? I have tried to increase, but it always emits 1024 bytes.  Thank you so much in advance.

**Comment by alzimmermsft** [comment]
Unfortunately, I'm unable to provide a way to increase the output of `FilePart.content()` as that isn't part of SDK and I have no knowledge of how it works.

**Comment by kirankumar994** [comment]
Okay, Thank you for your response @alzimmermsft .
