### ISSUE TITLE
[Query] Issue with running spring boot application on azure spring apps with key vault configuration. Using Service principal auth.

### ISSUE THREAD

**Issue by kirankumar994** [Azure/azure-sdk-for-java#39916]
![Screenshot from 2024-04-26 10-52-32](https://github.com/Azure/azure-sdk-for-java/assets/19862708/b7880690-8330-48d7-9d21-2b9f2617539c)
I have a spring boot application, using key vault to store my mongodb credentials. I am using service principal authentication to connect with azure key vault. The application is currently running on local env after log in with az login service principal. But, when I am trying to deploy it on azure spring cloud, I am getting the below exception

I am using the below dependency 
<dependency>
            <groupId>com.azure.spring</groupId>
            <artifactId>spring-cloud-azure-starter-keyvault</artifactId>
            <version>5.11.0</version>
        </dependency>

java.lang.IllegalStateException: Failed to configure KeyVault property source

`
@Value("${spring.cloud.azure.keyvault.secret.property-sources[0].endpoint}")
    private String keyVaultEndpoint;

    @Value("${azure.keyvault.client-id}")
    private String clientId;

    @Value("${azure.keyvault.client-key}")
    private String clientSecret;

    @Value("${azure.keyvault.tenant-id}")
    private String tenantId;
    
    @Bean
    public SecretClient createSecretClient() {

        ClientSecretCredential clientSecretCredential = new ClientSecretCredentialBuilder()
                .clientId(clientId)
                .clientSecret(clientSecret)
                .tenantId(tenantId)
                .build();

        // Azure SDK client builders accept the credential as a parameter.
        return new SecretClientBuilder()
                .vaultUrl(keyVaultEndpoint)
                .credential(clientSecretCredential)
                .buildClient();
    }`
    
    This is the Bean I kept in my mongodb config class. I am using the same service principal to deploy from local. And, it is getting deployed as well, but the application failed to start due to above exception. I tried with managed identity as well but no luck. I wanted to use service principal to connect with azure key vault as well. Please help me where am I doing wrong. 

***Why is this not a Bug or a feature Request?***
A clear explanation of why is this not a bug or a feature request?

**Setup (please complete the following information if applicable):**
 - IDE: [e.g. IntelliJ]
 - Library/Libraries: [e.g. com.azure:azure-core:1.16.0 (groupId:artifactId:version)]
 
 **Information Checklist**
 Kindly make sure that you have added all the following information above and checkoff the required fields otherwise we will treat the issuer as an incomplete report
- [ ] Query Added
- [ ] Setup information Added

**Comment by kirankumar994** [comment]
Hi all, 
I have been waiting for the response here. Thank you so much in advance.

**Comment by saragluna** [comment]
See https://learn.microsoft.com/en-us/azure/developer/java/spring-framework/secret-management#basic-usage and https://learn.microsoft.com/en-us/azure/developer/java/spring-framework/authentication#authenticate-with-microsoft-entra-id
