### ISSUE TITLE
[BUG] Not able to assign display name for sender email address in Communication Email

### ISSUE THREAD

**Issue by Saurav-S-Purushothaman** [Azure/azure-sdk-for-java#39910]
**Describe the bug**
I am trying to change the display name of the sender email address. The user part of the sender email address is DoNotReply. I want to change that. Is that possible? If it is not possible to set the display name using sdk, what is the alternative to achieve this?

I tried setting the .setSenderAddress of EmailMessage as below. Both cases gives me the same error. :
- `"\"MyDisplayName \"<DoNotReply@example.com>"`
- `"Username <DoNotReply@example.com>"`

But `<DoNotReply@example.com>` is valid and its display name is DoNotReply. It sends email without any error

***Exception or Stack Trace***
```
Status code 400, "{"error":{"code":"BadRequest","message":"Request body validation error. See property 'senderAddress'","target":null,"details":null,"innererror":null}}
```

**Expected behavior**
Feedback:
It would be much better if the setSenderAddress is expecting an EmailAddress class instead of String so that we can set the display name.
Ref - https://learn.microsoft.com/en-us/java/api/com.azure.communication.email.models.emailmessage?view=azure-java-stable#com-azure-communication-email-models-emailmessage-setsenderaddress(java-lang-string)

**Comment by alzimmermsft** [comment]
@acsdevx-msft as there isn't a CODEOWNER for email

**Comment by joshfree** [comment]
@vcolin7 same request, follow up with communication team offline to get a positive handoff, and update the CODEOWNER entry appropriately

**Comment by Saurav-S-Purushothaman** [comment]
@joshfree @vcolin7 Following up on these issues. Any progress? 
Can I expect anything in the near future? If not, could you guys guide me to any links or document for a work around to make this work? ( I wasn't able to find anything myself )

**Comment by vcolin7** [comment]
Hi @yogeshmo, could you look into this when you get a chance? Thanks!

**Comment by Florzl** [comment]
Having the same issue any updates?

**Comment by yogeshmo** [comment]
Hi @Saurav-S-Purushothaman and @Florzl,

The sender address (and the corresponding display name) need to be configured on your Email Communication Services Domain resource. Once these addresses are configured, they can be used to send an email by providing the sender address to the SDK.

Here is our documentation on how the sender addresses can be configured. 
[https://learn.microsoft.com/en-us/azure/communication-services/quickstarts/email/add-multiple-senders?pivots=platform-azp](https://learn.microsoft.com/en-us/azure/communication-services/quickstarts/email/add-multiple-senders?pivots=platform-azp)
