### ISSUE TITLE
[FEATURE REQ] Communicataion Email : Allow setting attachment content disposition as inline

### ISSUE THREAD

**Issue by Saurav-S-Purushothaman** [Azure/azure-sdk-for-java#39927]
**Is your feature request related to a problem? Please describe.**
When using the EmailAttachment from the @azure/communication-email, we can attach files to the email by initialising this class with the following properties. 
 
1. name (String)
2. contentType (String)
3. content (BinaryData)

While this woks for general attachments (like documents, etc), this class is quite limited if we want to use the attachments to display images inside our email.

To be able to send emails while avoiding loading external images (which are blocked by default in most email clients), it is a common pattern these days to add an image as attachment and display it using its content ID (eg:  `<img src="cid:logo" alt="Company"/>`)

For this to work, the Content-Disposition header should be set as inline, instead of the now default attachment. (eg: Content-Disposition: inline; filename="logo.png"; size=16864;)

And the Content-Id also seems to be randomly generated by Azure (eg. Content-Id: <961cf742-4ea9-445e-96e4-58e256928715>), which makes it impossible to properly reference the image by its own ID from the email body template.

**Describe the solution you'd like**
Would be really helpful to allow this properties/headers to be set when adding the attachment, by expanding the current EmailAttachment class.

This was an already asked [request](https://github.com/Azure/azure-sdk-for-js/issues/25604). Just want to make sure that this is extended for azure-java-sdk

**Information Checklist**
Kindly make sure that you have added all the following information above and checkoff the required fields otherwise we will treat the issuer as an incomplete report
- [x] Description Added
- [x] Expected solution specified

**Comment by kushagraThapar** [comment]
@joshfree looks like this got assigned to the wrong team, can you please route it correctly, thanks!

**Comment by alzimmermsft** [comment]
@acsdevx-msft as there isn't a CODEOWNER for email

**Comment by joshfree** [comment]
@vcolin7 can you work with the communication team to get this routed properly and to get the CODEOWNER entry fixed this week?

**Comment by Saurav-S-Purushothaman** [comment]
@joshfree I wanted to follow up on this. Could you please let me know if we can expect this feature to be implemented soon, or if it might not be included in the near future?

If this feature is not going to be implemented, could you please direct me to any resources or guides on the best way to add images in the HTML body of an email to be sent via Azure Communication Servie? As far as I have tried, I could not find any docs. 

Thanks!

**Comment by vcolin7** [comment]
Hey @Saurav-S-Purushothaman, sorry for the late reply.

@yogeshmo would you mind taking a look? Thanks!

**Comment by Saurav-S-Purushothaman** [comment]
@vcolin7 No problem!

**Comment by Saurav-S-Purushothaman** [comment]
@joshfree I am sorry to nag you. It's been a while this issue has been raised. Any sort of feedback is greatly appreciated. I would like to know whether this is going to be implemented or totally disregarded which is fine in either case.

**Comment by yogeshmo** [comment]
Hi @Saurav-S-Purushothaman,

We now support sending Inline attachments using the Azure Communication Email SDKs. Please follow the instructions in this documentation.

[https://learn.microsoft.com/en-us/azure/communication-services/quickstarts/email/send-email-advanced/send-email-with-inline-attachments?tabs=connection-string&pivots=programming-language-java](https://learn.microsoft.com/en-us/azure/communication-services/quickstarts/email/send-email-advanced/send-email-with-inline-attachments?tabs=connection-string&pivots=programming-language-java)
