### ISSUE TITLE
[BUG] Region class missing "Israel Central" region which is supported azure geographic region

### ISSUE THREAD

**Issue by NeetuJoshi** [Azure/azure-sdk-for-java#39932]
**Describe the bug**
We are using com.azure:azure-core-management:1.13.0 latest library but its missing ISRAEL CENTRAL region.

**To Reproduce**
We can check here https://learn.microsoft.com/en-us/java/api/com.azure.core.management.region?view=azure-java-stable

**Expected behavior**
Region class should have ISRAEL CENTRAL region as that is supported region.
https://azure.microsoft.com/en-us/explore/global-infrastructure/geographies/#geographies

**Comment by joshfree** [comment]
Flagging this as a `feature-request` to add the missing enum value

**Comment by weidongxu-microsoft** [comment]
@XiaofeiCao Please update core-management.
