### ISSUE TITLE
Where is Javadoc for Azure Java Libraries

### ISSUE THREAD

**Issue by CaymanTurtleBeach** [Azure/azure-sdk-for-java#39948]
### Type of issue

Missing information

### Description

Why does Microsoft persist in not making links to Javadoc style documentation for Azure Java SDKs **PROMINENT** - especially when its own format style often omits key elements.

To wit: (from https://learn.microsoft.com/en-us/java/api/com.azure.data.tables.tableserviceclient?view=azure-java-stable#com-azure-data-tables-tableserviceclient-createtable(java-lang-string)

**Method Details**

```
Create Table
createTable
public TableClient createTable(String tableName)

Creates a table within the Tables service.

Code Samples

Creates a table. Prints out the details of the created table.

Java

Copy
TableClient tableClient = tableServiceClient.createTable("myTable");

 System.out.printf("Table with name '%s' was created.", tableClient.getTableName());
Parameters:

tableName - The name of the table to create.
Returns:

A [TableClient](https://learn.microsoft.com/en-us/java/api/com.azure.data.tables.tableclient?view=azure-java-stable) for the created table.

```
**NOT A WORD ABOUT THE EXCEPTION THAT IS THROWN IF A TABLE WITH THE NAME tableName ALREADY EXISTS.**

Where is Javadoc??? Java developers should not have to search for Javadoc and slog through all the cruft returned just to get documentation that is correct and formatted consistent with virtually all significant public Java libraries.

### Page URL

https://learn.microsoft.com/en-us/java/api/overview/azure/data-tables-readme?view=azure-java-stable

### Content source URL

https://github.com/Azure/azure-docs-sdk-java/blob/master/docs-ref-services/latest/data-tables-readme.md

### Document Version Independent Id

c2ca723f-f9ca-302a-6a30-9426fdb8b0cc

### Article author

@azure-sdk

### Metadata

* ID: a618277f-b2f6-1c9d-551c-14e0adea3738 
* Service: **tables**

**Comment by jairmyree** [comment]
Thank you for reaching out. I will look into your issue and respond shortly.

**Comment by jairmyree** [comment]
@CaymanTurtleBeach There is a known issue with the learn.microsoft.com documentation where the exceptions are not being documented. For more accurate documentation, I would suggest that you use the Javadocs that come bundled with each release of our libraries: [link to maven](https://mvnrepository.com/artifact/com.azure/azure-data-tables/12.4.0). They can be directly downloaded from maven and viewed within your browser or viewed within an IDE capable of downloading and displaying dependency Javadocs such as Intellij.
