### ISSUE TITLE
[BUG] Page link not found in Logging in Azure SDK wiki

### ISSUE THREAD

**Issue by sophiaso** [Azure/azure-sdk-for-java#39941]
**Describe the bug**
In the wiki page [Logging in Azure SDK](https://github.com/Azure/azure-sdk-for-java/wiki/Logging-in-Azure-SDK#setting-an-httplogdetaillevel), the link for [HttpLogOptions](https://github.com/java/api/com.azure.core.http.policy.httplogoptions?view=azure-java-stable) and [HttpLogDetailLevel](https://github.com/java/api/com.azure.core.http.policy.httplogdetaillevel?view=azure-java-stable) redirects to not found pages.

***Exception or Stack Trace***
N/A

**To Reproduce**
Go to wiki page [Logging in Azure SDK](https://github.com/Azure/azure-sdk-for-java/wiki/Logging-in-Azure-SDK#setting-an-httplogdetaillevel).

***Code Snippet***
N/A

**Expected behavior**
The links redirect to valid pages.

**Screenshots**
![image](https://github.com/Azure/azure-sdk-for-java/assets/3401820/89dec5de-16b7-45d9-ad3f-3f0e3444678a)

![image](https://github.com/Azure/azure-sdk-for-java/assets/3401820/7c33076b-7c28-44b3-9881-d6f459a403a8)

**Setup (please complete the following information):**
 - IDE: [e.g. IntelliJ]
 - Library/Libraries: [e.g. com.azure:azure-core:1.16.0 (groupId:artifactId:version)]
 - Java version: [e.g. 8] 
 - App Server/Environment: [e.g. Tomcat, WildFly, Azure Function, Apache Spark, Databricks, IDE plugin or anything special]
 - Frameworks: [e.g. Spring Boot, Micronaut, Quarkus, etc] 

If you suspect a dependency version mismatch (e.g. you see `NoClassDefFoundError`, `NoSuchMethodError` or similar), please check out [Troubleshoot dependency version conflict article](https://aka.ms/azsdk/java/dependency/troubleshoot) first. If it doesn't provide solution for the problem, please provide:
- verbose dependency tree (`mvn dependency:tree -Dverbose`)
- exception message, full stack trace, and any available logs

**Additional context**

**Information Checklist**
Kindly make sure that you have added all the following information above and checkoff the required fields otherwise we will treat the issuer as an incomplete report
- [x] Bug Description Added
- [x] Repro Steps Added
- [ ] Setup information Added

**Comment by alzimmermsft** [comment]
Thanks for reporting this @sophiaso, I've fixed the links
