### ISSUE TITLE
Investigate interactions between retry and redirect policies

### ISSUE THREAD

**Issue by alzimmermsft** [Azure/azure-sdk-for-java#39958]
- [ ] Retry policy and redirect policy both have retry and redirect counts which means the number of request made could be the multiplication of those values. Investigate if they should share some common count tracking to reduce the potential for request "explosions".
- [ ] Redirect policy is currently marked as `PER_RETRY`, it likely should be `PER_CALL`. This prevents issues on making many more requests if there is a transient network error mid redirection as RedirectPolicy is stateless and would lose information on the hops it has made.
- [ ] Redirect policy may need some form of backoff

**Comment by JonathanGiles** [comment]
Moved this into [#39841](https://github.com/Azure/azure-sdk-for-java/issues/39841)
