### ISSUE TITLE
Reactor core version upgrade

### ISSUE THREAD

**Issue by Itsimranbasha** [Azure/azure-sdk-for-java#39954]
Currently i am using a Azure-Storage-Queue dependency in my java project which brings transitive dependency of reactor core with version 3.3.1.RELEASE which is a very legacy version.

The issue is i am not trying to implementing EventHubs using azure-messaging-eventhubs which needs atleast 3.4.0 version.
Due to this i am getting version conflicts and i am not able to implement eventhubs in my code.

java.lang.NoSuchMethodError: 'reactor.core.publisher.Mono reactor.core.publisher.Mono.retry(java.util.function.Predicate)'
	at reactor.netty.http.client.HttpClientConnect$MonoHttpConnect.subscribe(HttpClientConnect.java:321)
	at reactor.core.publisher.Mono.subscribe(Mono.java:3987)
	at reactor.core.publisher.FluxFlatMap.trySubscribeScalarMap(FluxFlatMap.java:199)
	at reactor.core.publisher.MonoFlatMap.subscribeOrReturn(MonoFlatMap.java:53)
	at reactor.core.publisher.InternalMonoOperator.subscribe(InternalMonoOperator.java:57)
	at reactor.core.publisher.MonoDelaySubscription.accept(MonoDelaySubscription.java:52)
	at reactor.core.publisher.MonoDelaySubscription.accept(MonoDelaySubscription.java:33)
	at reactor.core.publisher.FluxDelaySubscription$DelaySubscriptionOtherSubscriber.onNext(FluxDelaySubscription.java:130)
	at reactor.core.publisher.MonoDelay$MonoDelayRunnable.run(MonoDelay.java:119)
	at reactor.core.scheduler.SchedulerTask.call(SchedulerTask.java:68)
	at reactor.core.scheduler.SchedulerTask.call(SchedulerTask.java:28)
	at java.base/java.util.concurrent.FutureTask.run(Unknown Source)
	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)
	
I am getting these error

**Comment by anuchandy** [comment]
Hello @Itsimranbasha, the queue library using reactor-core:3.3.x-RELEASE are around ~3-year-old. If we use a recent version of azure-storage-queue  & azure-messaging-eventhubs then this conflict shouldn’t happen. For instance, both latest azure-messaging-eventhubs:5.18.3 and azure-storage-queue:12.20.4 that uses azure-core:1.48.0 transitively brings reactor-core:3.4.36.

**Comment by Itsimranbasha** [comment]
@anuchandy i tried using the latest version of azure-storage-queue:12.20.4 as well, but it also transitively brings reactor-core version of 3.3.1.RELEASE only.

**Comment by anuchandy** [comment]
Hello @Itsimranbasha, could you try the `mvn dependency:tree` to see the actual package pulling ` 3.3.1.RELEASE`?.

To confirm, I added the following queue and eventhubs dependencies to a "brand-new console application" and enumerated the dependency tree (`mvn dependency:tree`)

```
<dependency>
  <groupId>com.azure</groupId>
  <artifactId>azure-storage-queue</artifactId>
  <version>12.20.4</version>
</dependency>
<dependency>
  <groupId>com.azure</groupId>
  <artifactId>azure-messaging-eventhubs</artifactId>
  <version>5.18.3</version>
</dependency>
```

And reactor-core3.4.36 is resolved, which is declared as the reactor-core version for above of queue and eventhubs versions.

```
[INFO] com.repro.a39954:repro-a39954:jar:1.0-SNAPSHOT
[INFO] +- com.azure:azure-storage-queue:jar:12.20.4:compile
[INFO] |  +- com.azure:azure-core:jar:1.48.0:compile
[INFO] |  |  +- com.azure:azure-json:jar:1.1.0:compile
[INFO] |  |  +- com.azure:azure-xml:jar:1.0.0:compile
[INFO] |  |  +- com.fasterxml.jackson.core:jackson-annotations:jar:2.13.5:compile
[INFO] |  |  +- com.fasterxml.jackson.core:jackson-core:jar:2.13.5:compile
[INFO] |  |  +- com.fasterxml.jackson.core:jackson-databind:jar:2.13.5:compile
[INFO] |  |  +- com.fasterxml.jackson.datatype:jackson-datatype-jsr310:jar:2.13.5:compile
[INFO] |  |  \- io.projectreactor:reactor-core:jar:3.4.36:compile <========================================
[INFO] |  |     \- org.reactivestreams:reactive-streams:jar:1.0.4:compile
[INFO] |  +- com.azure:azure-core-http-netty:jar:1.14.2:compile
[INFO] |  |  +- io.netty:netty-handler:jar:4.1.108.Final:compile
[INFO] |  |  |  +- io.netty:netty-resolver:jar:4.1.108.Final:compile
[INFO] |  |  |  \- io.netty:netty-transport:jar:4.1.108.Final:compile
[INFO] |  |  +- io.netty:netty-handler-proxy:jar:4.1.108.Final:compile
[INFO] |  |  |  \- io.netty:netty-codec-socks:jar:4.1.108.Final:compile
[INFO] |  |  +- io.netty:netty-buffer:jar:4.1.108.Final:compile
[INFO] |  |  +- io.netty:netty-codec:jar:4.1.108.Final:compile
[INFO] |  |  +- io.netty:netty-codec-http:jar:4.1.108.Final:compile
[INFO] |  |  +- io.netty:netty-codec-http2:jar:4.1.108.Final:compile
[INFO] |  |  +- io.netty:netty-transport-native-unix-common:jar:4.1.108.Final:compile
[INFO] |  |  +- io.netty:netty-transport-native-epoll:jar:linux-x86_64:4.1.108.Final:compile
[INFO] |  |  |  \- io.netty:netty-transport-classes-epoll:jar:4.1.108.Final:compile
[INFO] |  |  +- io.netty:netty-transport-native-kqueue:jar:osx-x86_64:4.1.108.Final:compile
[INFO] |  |  |  \- io.netty:netty-transport-classes-kqueue:jar:4.1.108.Final:compile
[INFO] |  |  +- io.netty:netty-tcnative-boringssl-static:jar:2.0.65.Final:compile
[INFO] |  |  |  +- ...
[INFO] |  |  +- io.projectreactor.netty:reactor-netty-http:jar:1.0.43:compile
[INFO] |  |  |  +- io.netty:netty-resolver-dns:jar:4.1.107.Final:compile
[INFO] |  |  |  |  \- io.netty:netty-codec-dns:jar:4.1.107.Final:compile
[INFO] |  |  |  +- io.netty:netty-resolver-dns-native-macos:jar:osx-x86_64:4.1.107.Final:compile
[INFO] |  |  |  |  \- io.netty:netty-resolver-dns-classes-macos:jar:4.1.107.Final:compile
[INFO] |  |  |  \- io.projectreactor.netty:reactor-netty-core:jar:1.0.43:compile
[INFO] |  |  \- io.netty:netty-common:jar:4.1.108.Final:compile
[INFO] |  +- com.azure:azure-storage-common:jar:12.24.4:compile
[INFO] |  \- com.fasterxml.jackson.dataformat:jackson-dataformat-xml:jar:2.13.5:compile
[INFO] |     +- org.codehaus.woodstox:stax2-api:jar:4.2.1:compile
[INFO] |     \- com.fasterxml.woodstox:woodstox-core:jar:6.4.0:compile
[INFO] +- com.azure:azure-messaging-eventhubs:jar:5.18.3:compile
[INFO] |  \- com.azure:azure-core-amqp:jar:2.9.3:compile
[INFO] |     +- com.microsoft.azure:qpid-proton-j-extensions:jar:1.2.4:compile
[INFO] |     \- org.apache.qpid:proton-j:jar:0.34.1:compile
....
....

**Comment by Itsimranbasha** [comment]
sorry @anuchandy i think i mislead u in a way. Already the implementation of the azure-storage-queue(12.5.2 with reactor-core 3.3.1.RELEASE version) is running in our code from a long time and now recently i added this azure-messaging-eventhubs implementation(5.15.0 version with reactor-core 3.4.0 version).

Now the maven is resolving the final reactor core version as 3.4.0 with which the newly implemented eventhubs code is running fine but the older code of storage queue which is using some methods of reactor-core 3.3.1.RELEASE is not running and throwing this error as looks like the following method is deprecated from 3.4.0 and later versions of reactor-core.

java.lang.NoSuchMethodError: 'reactor.core.publisher.Mono reactor.core.publisher.Mono.retry(java.util.function.Predicate)'
at reactor.netty.http.client.HttpClientConnect$MonoHttpConnect.subscribe(HttpClientConnect.java:321)
at reactor.core.publisher.Mono.subscribe(Mono.java:3987)
at reactor.core.publisher.FluxFlatMap.trySubscribeScalarMap(FluxFlatMap.java:199)
at reactor.core.publisher.MonoFlatMap.subscribeOrReturn(MonoFlatMap.java:53)
at reactor.core.publisher.InternalMonoOperator.subscribe(InternalMonoOperator.java:57)
at reactor.core.publisher.MonoDelaySubscription.accept(MonoDelaySubscription.java:52)
at reactor.core.publisher.MonoDelaySubscription.accept(MonoDelaySubscription.java:33)
at reactor.core.publisher.FluxDelaySubscription$DelaySubscriptionOtherSubscriber.onNext(FluxDelaySubscription.java:130)
at reactor.core.publisher.MonoDelay$MonoDelayRunnable.run(MonoDelay.java:119)
at reactor.core.scheduler.SchedulerTask.call(SchedulerTask.java:68)
at reactor.core.scheduler.SchedulerTask.call(SchedulerTask.java:28)
at java.base/java.util.concurrent.FutureTask.run(Unknown Source)
at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(Unknown Source)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
at java.base/java.lang.Thread.run(Unknown Source)

**Comment by Itsimranbasha** [comment]
So even if i upgrade the version of azure-storage-queue to latest versions, it will still be not able to find those methods and throw the same error. Do i need to update my storage-queue code such that it only includes 3.4.0 reactor-core versions methods?

**Comment by anuchandy** [comment]
Yes, in your application pom file, you will need to use the versions (of EventHub, Queues and any other) such they all declare reactor-core:3.4.0 as their dependency, so there are no longer any dependency conflicts. If the application itself is explicitly using any APIs not available in reactor-core:3.4.0 then app code needs to be updated to use equivalent/alternate APIs in 3.4.0.

**Comment by anuchandy** [comment]
Between, you may also delegate the version resolution to [azure SDK BOM](https://github.com/Azure/azure-sdk-for-java/tree/main/sdk/boms/azure-sdk-bom), this avoids the need for application to align azure SDK versions manually in the POM file.

The [last comment](https://github.com/Azure/azure-sdk-for-java/issues/39954#issuecomment-2087538185) still applies, i.e., if there are other non-Azure dependencies that resolve to 3.3.1.RELEASE, then their version needs to align manually, also if the app is using 3.3.1.RELEASE APIs in the code it needs to be updated to use equivalent/alternate APIs in 3.4.0.

**Comment by anuchandy** [comment]
Closing - recommendations provided to resolve both the azure SDK specific and general dependency conflicts in Java.

**Comment by Itsimranbasha** [comment]
[http-nio-9443-exec-1] ERROR correlationId=26c6836d-867c-4b42-b91b-d78b8e105ad3 c.a.c.h.netty.NettyAsyncHttpClient.performLogging - java.nio.channels.ClosedChannelException

 [http-nio-9443-exec-1] ERROR correlationId=26c6836d-867c-4b42-b91b-d78b8e105ad3 c.a.s.c.policy.RequestRetryPolicy.performLogging - java.nio.channels.ClosedChannelException
 
[http-nio-9443-exec-1] ERROR correlationId=26c6836d-867c-4b42-b91b-d78b8e105ad3 c.a.s.c.i.StorageImplUtils.performLogging - java.nio.channels.ClosedChannelException

i am just updating the azure-storage queue version and after resolving all the conflicts i am now getting this error. azure-storage-version used is 12.20.4

**Comment by Itsimranbasha** [comment]
HI @anuchandy, I downgraded the version of azure-messaging-eventhubs to a 5.3.1 which transitively uses the reactor core vesion of 3.3.x which is in line with the azure-storage-queue's reactor vesion. After doing so i got the both functionalites working without any conflicts and exceptions. 
Thanks for the help all along.
