### ISSUE TITLE
Cosmos DB Encryption Sample Issue

### ISSUE THREAD

**Issue by faynef** [Azure/azure-sdk-for-java#39969]
**Section** [link](https://github.com/Azure/azure-sdk-for-java/blob/main/sdk/cosmos/azure-cosmos-encryption/src/samples/java/com/azure/cosmos/encryption/ReadmeSamples.java#L139-L145):
![image](https://github.com/Azure/azure-sdk-for-java/assets/138087452/19fab5a3-9193-412d-9047-dfa3567815e0)

**Reason**: 
![image](https://github.com/Azure/azure-sdk-for-java/assets/138087452/d19d5929-9982-4aca-aa54-ce670b8ae1ff)
![image](https://github.com/Azure/azure-sdk-for-java/assets/138087452/fc7aa511-ae75-4223-91ec-7dbb721b72b5)
Failed to serialize the object into json.

**Suggestion**:
	Update code to:
```
public String getId () {
	            return id;
	        }
public String getSensitiveString() {
	            return sensitiveString;
	   }
```

@sandeep-sen , @joshfree , @kyle-patterson , @KrzysztofCwalina and @aayush3011 for notification.

**Comment by kushagraThapar** [comment]
@tvaron3 please take a look at this, thanks!

**Comment by v-xuto** [comment]
Close it. This issue has been fixed by PR https://github.com/Azure/azure-sdk-for-java/pull/40356.
