### ISSUE TITLE
Cosmos DB Readme Issue

### ISSUE THREAD

**Issue by faynef** [Azure/azure-sdk-for-java#39970]
**Section** [link1](https://github.com/Azure/azure-sdk-for-java/tree/main/sdk/cosmos/azure-cosmos#azure-cosmos-db-client-library-for-java), [link2](https://github.com/Azure/azure-sdk-for-java/tree/main/sdk/cosmos/azure-cosmos#crud-operation-on-items), [link3](https://github.com/Azure/azure-sdk-for-java/tree/main/sdk/cosmos/azure-cosmos#next-steps):
![image](https://github.com/Azure/azure-sdk-for-java/assets/138087452/67248a9b-c09a-4c08-a2b8-ba39bf6f2b6a)
![image](https://github.com/Azure/azure-sdk-for-java/assets/138087452/0a812007-2317-440b-984c-8296f60ddb9b)
![image](https://github.com/Azure/azure-sdk-for-java/assets/138087452/a34d4381-dc33-4b75-80bf-da4d073519ef)

**Reason**: Link error.

**Suggestion**:
Change all links from 1,2,3 to: "https://github.com/Azure/azure-sdk-for-java/tree/main/sdk/cosmos/azure-cosmos/src/samples/java/com/azure/cosmos".

@sandeep-sen , @joshfree , @kyle-patterson , @KrzysztofCwalina and @aayush3011 for notification.

**Comment by kushagraThapar** [comment]
@tvaron3 please take a look at this, thanks!

**Comment by tvaron3** [comment]
@faynef This is intended. All of those links go to our sample repo that have several samples. The link you suggested to change it to is only to our code snippet examples.

**Comment by faynef** [comment]
OK, we'll close this issue.
