### ISSUE TITLE
Unexpected character ('<' (code 60))

### ISSUE THREAD

**Issue by jsarrelli** [Azure/azure-sdk-for-java#40001]
Hi team, 
I'm getting tons of the following errors, but I can't trace where they come from.  I don't see any other error so I believe this is an internal one that is handled or resolved behind the scenes.

***Exception or Stack Trace***
```Unexpected character ('<' (code 60)): expected a valid value (JSON String, Number (or 'NaN'/'INF'/'+INF'), Array, Object or token 'null', 'true' or 'false') at [Source: (byte[])"<!DOCTYPE html PUBLIC '-//W3C//DTD XHTML 1.0 Transitional//EN' 'http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd'><html xmlns='http://www.w3.org/1999/xhtml'><head><meta content='text/html; charset=utf-8' http-equiv='content-type'/><style type='text/css'>body {font-family:Arial; margin-left:40px; }img  { border:0 none; }#content { margin-left: auto; margin-right: auto }#message h2 { font-size: 20px; font-weight: normal; color: #000000; margin: 34px 0px 0px 0px }#message p  { font-size: 13p"[truncated 488 bytes]; line: 1, column: 2]```

Logger Name: com.azure.core.implementation.MethodHandleReflectiveInvoker

Versions:
```
  val azureSdk                      = "com.azure.resourcemanager" % "azure-resourcemanager"                  % "2.38.0"
  // Single Services Managers
  val azureAppServiceSdk            = "com.azure.resourcemanager" % "azure-resourcemanager-appservice"       % "2.38.0"
  val azureSearchServiceSdk         = "com.azure.resourcemanager" % "azure-resourcemanager-search"           % "2.38.0"
  val azureRecoveryServiceSdk       = "com.azure.resourcemanager" % "azure-resourcemanager-recoveryservices" % "1.2.0"
  val azureRecoveryServiceBackupSdk =
    "com.azure.resourcemanager" % "azure-resourcemanager-recoveryservicesbackup" % "1.2.0"
  val azureResourceHealthSdk               = "com.azure.resourcemanager" % "azure-resourcemanager-resourcehealth" % "1.0.0"
  val azureRecoveryServicesSiteRecoverySdk =
    "com.azure.resourcemanager" % "azure-resourcemanager-recoveryservicessiterecovery" % "1.1.0"
```

**Comment by weidongxu-microsoft** [comment]
This seems to be similar problem with this issue https://github.com/Azure/azure-sdk-for-java/issues/40081

Would you enable logging to let us at least see which API is having this problem?
https://github.com/Azure/azure-sdk-for-java/issues/40081#issuecomment-2105624214
