### ISSUE TITLE
[BUG] ReactiveCosmosTemplate existsById does not work as intended

### ISSUE THREAD

**Issue by NetsCreationLab** [Azure/azure-sdk-for-java#40019]
**Describe the bug**
The implementation for `existsById` in `com.azure.spring.data.cosmos.core.ReactiveCosmosTemplate` indicates that a `Mono` emitting `true` if the element exists, or `false` if the element does not exist. However, the implementation checks if the result emitted by `findById` is `null`, which cannot happen, as an empty `Mono` is returned by `findById` in case no element is found.

***Exception or Stack Trace***
N/A

**To Reproduce**
Use `existsById` to look for an element that does not exist, and observe that an empty `Mono` is returned in place of a `Mono` emitting `false`.

***Code Snippet***

```
    /**
     * Exists
     *
     * @param id the id
     * @param domainType the entity class
     * @param containerName the container name
     * @return Mono with a boolean or error
     */
    public Mono<Boolean> existsById(Object id, Class<?> domainType, String containerName) {
        return findById(containerName, id, domainType)
            .flatMap(o -> Mono.just(o != null));
    }
```

**Expected behavior**
Returned `Mono` should emit `true` if the element is present and `false` if the element is not present.

**Screenshots**

**Setup (please complete the following information):**
 - OS: N/A
 - IDE: IntelliJ
 - Library/Libraries: com.azure.spring:spring-cloud-azure-starter-data-cosmos:4.10.0
 - Java version: N/A
 - App Server/Environment: N/A
 - Frameworks: Spring Boot 

**Additional context**
https://github.com/reactive-streams/reactive-streams-jvm#user-content-2.13
https://stackoverflow.com/questions/69461051/why-cant-a-mono-hold-a-null

**Information Checklist**
Kindly make sure that you have added all the following information above and checkoff the required fields otherwise we will treat the issuer as an incomplete report
- [x] Bug Description Added
- [x] Repro Steps Added
- [x] Setup information Added

**Comment by NetsCreationLab** [comment]
```
    /**
     * Exists
     *
     * @param id the id
     * @param domainType the entity class
     * @param containerName the container name
     * @return Mono with a boolean or error
     */
    public Mono<Boolean> existsById(Object id, Class<?> domainType, String containerName) {
        return findById(containerName, id, domainType)
            .map(ignored -> true)
            .switchIfEmpty(Mono.just(false));
    }
```

Would be a working implementation.

**Comment by kushagraThapar** [comment]
@NetsCreationLab - Thanks for reporting this issue, its a bug and I have pushed a fix for this - https://github.com/Azure/azure-sdk-for-java/pull/40022 
Please review, thanks!
