### ISSUE TITLE
[BUG] Java service bus: ServiceBusAdministrationClient.createSubscription does not create a rule when rule is included as a parameter

### ISSUE THREAD

**Issue by Gray-M-Williams** [Azure/azure-sdk-for-java#40024]
**Describe the bug**
We are trying to use the ServiceBusAdministrationClient to create subscriptions with custom pre-defined rules. However, when calling the `createSubscription` method and including a custom rule as a parameter, the client does not create the rule we specified and just attaches the $Default 1=1 SQL Rule Filter every time.

**To Reproduce**
1. Create a new subscription using the method 
```
ServiceBusAdministrationClient.createSubscription(String topicName, String subscriptionName, String ruleName,
        CreateSubscriptionOptions subscriptionOptions,
        CreateRuleOptions ruleOptions)
```
and include a custom-defined rule for the parameter `CreateRuleOptions ruleOptions`. Check the subscription in the Service Bus and confirm that the desired rule was not created, and rather a rule called `$Default` with filter 1=1 was created instead.

***Code Snippet***
Add the code snippet that causes the issue.
```
ServiceBusAdministrationClient adminClient = new ServiceBusAdministrationClientBuilder()
                .connectionString(connectionString)
                .buildClient();
adminClient.createSubscription(liveFeedTopic, storeTopicName, "store-filter",
                    new CreateSubscriptionOptions().setForwardTo(storeTopicName),
                    new CreateRuleOptions(new SqlRuleFilter("storeId LIKE '2708%'")));
```

**Expected behavior**
A new subscription is created with a rule called `store-filter` with the above SQL expression.

**Setup (please complete the following information):**
 - OS: MacOS
 - IDE: Intellij
 - Library/Libraries: com.azure:azure-sdk-bom:1.2.23
 - Java version: 17
 - Frameworks: Spring Boot

**Information Checklist**
Kindly make sure that you have added all the following information above and checkoff the required fields otherwise we will treat the issuer as an incomplete report
- [x] Bug Description Added
- [x] Repro Steps Added
- [x] Setup information Added

**Comment by Gray-M-Williams** [comment]
Thank you for looking into this and making a code change! Will this go out with the next release?

**Comment by lmolkova** [comment]
Thanks for reporting this @Gray-M-Williams! yes, it should be released sometime in June/
