### ISSUE TITLE
Strategy and versioning and release parent pom's

### ISSUE THREAD

**Issue by weshaggard** [Azure/azure-sdk-for-java#4003]
Today we have a set of parent pom's:
1) https://github.com/Azure/azure-sdk-for-java/blob/master/parent/pom.xml
2) https://github.com/Azure/azure-sdk-for-java/blob/master/pom.client.xml
3) https://github.com/Azure/azure-sdk-for-java/blob/master/pom.data.xml
4) https://github.com/Azure/azure-sdk-for-java/blob/master/pom.management.xml

plus some libraries have library specific parent poms (ex: keyvault https://github.com/Azure/azure-sdk-for-java/blob/master/keyvault/data-plane/pom.xml).

Today people make changes to these parents often but we never really version or publish these files. We need to figure out a strategy for when we version and when we publish these pom files.

cc @JonathanGiles @jianghaolu

**Comment by kurtzeborn** [comment]
When we tackle the dev build versioning problem in the java repo (#3815) this will probably become a non-issue.

**Comment by mitchdenny** [comment]
The parent POM restructuring work that we do here:

https://github.com/Azure/azure-sdk-for-java/pull/6424

... will make parent POMs just like any other module. Then when we flick back to using the PowerShell script to publish artifacts it should be able to publish the parent POMs. That will be done as part of this work setting up the Android EngSys.

https://github.com/Azure/azure-sdk-for-android/issues/149

So I think that is the strategy. 

In addition the work that @JimSuplizio has done around versioning has reduced the chances that we'll need to publish parent POMs.

**Comment by mitchdenny** [comment]
Note I closed this because it was a strategy question, if someone thinks the above plan won't work then we can reopen it ;)
