### ISSUE TITLE
[QUERY] using 1106 0125 models which support parallel function calling. 

### ISSUE THREAD

**Issue by sravanthi-tl** [Azure/azure-sdk-for-java#40039]
OpenAIServiceVersion  seems to be an enum with few models. 
Is there a way  1106 0125 models which have support for parallel function calling can be used.
These version enum constants are not present.

Class in query: https://github.com/Azure/azure-sdk-for-java/blob/main/sdk/openai/azure-ai-openai/src/main/java/com/azure/ai/openai/OpenAIServiceVersion.java

Models in request : https://techcommunity.microsoft.com/t5/ai-azure-ai-services-blog/azure-openai-service-launches-gpt-4-turbo-and-gpt-3-5-turbo-1106/ba-p/3985962

Model availability in region: https://learn.microsoft.com/en-gb/azure/ai-services/openai/concepts/models

**Comment by joshfree** [comment]
@mssfang could you please follow up?

**Comment by mssfang** [comment]
Hi @sravanthi-tl 
As I know, Azure OpenAI supports those listed versions at current stage.
https://github.com/Azure/azure-rest-api-specs/blob/main/specification/cognitiveservices/OpenAI.Inference/main.tsp#L43

And the service retires older versions described in https://learn.microsoft.com/en-us/azure/ai-services/openai/api-version-deprecation

I think you may be confused at between `model version` and the `service API version`
The enum values in `OpenAIServiceVersion` is the `service API version` but `gpt-4-turbo` and `gpt-3.5-turbo-1106` is the `model version`.

You can request with request model version in service API version (depends on the model version available and service API version supported).
