### ISSUE TITLE
[FEATURE REQ] [Key Vault] Add configuration flag to delegate all cryptographic operations to service

### ISSUE THREAD

**Issue by vcolin7** [Azure/azure-sdk-for-java#40036]
**Is your feature request related to a problem? Please describe.**
From @sfc-gh-bschmidt:

> [The `CryptographyClient`] doesn't allow us to configure [it] to not even try retrieving the local key. Using a version without support for completely disabling the local key retrieval would cause the following regressions for us:
> 
> - We're using the key vault library to access a large number of customer managed keys. The cryptography clients are very short-lived. Trying the retrieval of the local key even once per client instance will introduce significant additional overhead and latency.
> 
> - For each client creation with a customer managed key, customers will suddenly start seeing a denied Get operation in their access logs.

**Describe the solution you'd like**
> [...] add support for configuring `CryptographyClientBuilder` to disable the local client completely

**Information Checklist**
Kindly make sure that you have added all the following information above and checkoff the required fields otherwise we will treat the issuer as an incomplete report
- [X] Description Added
- [X] Expected solution specified

**Comment by vcolin7** [comment]
@sfc-gh-bschmidt we recently released a new version of the Keys library ([4.9.0-beta.1](https://search.maven.org/artifact/com.azure/azure-security-keyvault-keys/4.9.0-beta.1/jar)) that allows for delegating all cryptographic operations to the service. You can enable this by calling `disableKeyCaching()` when building a new client.

Let me know how this works out for you, or if you have any questions or concerns :)

**Comment by sfc-gh-bschmidt** [comment]
Great to see this, thanks @vcolin7! I'll keep you updated on our upgrade to the new version.
