### ISSUE TITLE
[BUG] Etag Value return null if etag attribute is annotated with `@Version`  and `@JsonProperty("_etag")` in container class. || Spring Boot || ReactiveCosmosRepository

### ISSUE THREAD

**Issue by SanjayDasTezpur** [Azure/azure-sdk-for-java#40038]
**Describe the bug**
Etag Value return null if etag attribute is annotated with `@Version`  and `@JsonProperty("_etag")` in container class. || Spring Boot || ReactiveCosmosRepository

***Exception or Stack Trace***
No Exception , But Etag becomes null. which create problem  (412 precondition exception) in further update operation , as etag is null.

**To Reproduce**
1. Create a Entity Class [say Person, annotated with `@Container`]. 
2. add a attribute [member variable] with name `etag`, and annotate this with `@Version  @JsonProperty("_etag")` , `@Version` is used to enable concurrency . [If invalid etag is passed while updating it should throw an exception, i.e. pre condition exception]
3. Now create a Repository interface of Spring Boot , either `ReactiveCosmosRepository<Person, String>` or `CosmosRepository<Person, String>`.
4. Now from any Service or Controller Class try to execute `repository.save(person)`  , record will be saved in database, but the returned saved person object will have `etag` as null.

- Now, If I remove just `@Version` annotation and keep `@JsonProperty("_etag")` , then I get the correct etag , but I have to compromise concurrency, which is not permissible in our system.
- Second,  If I remove just  `@JsonProperty("_etag")`  annotation and keep `@Version`, then concurreny control works fine, and also recieve correct etag. **But the problem here is , we use stored procedure to update the record , to achieve optimistic  transaction, so in the database, in the document a new attribute gets created with name `etag` along with `_etag`. `etag` holds the last etag value, where as `_etag` has the latest value.** 

***Code Snippet***
**Person.Java**
```
@Data
@Container(containerName = "person")
public class Person {
    @Id
    private String id;

    @PartitionKey
    private String lastName;

    private String firstName;

    private String email;

    @Version
    @JsonProperty("_etag")
    private String etag;

    @JsonProperty("_self")
    private String self;
}
```
**PersonRepository.java**
```
@Repository
public interface PersonRepository extends ReactiveCosmosRepository<Person, String> {
}
```
**PersonService.java**
```
@Service
@RequiredArgsConstructor
public class PersonService {

    private final PersonRepository personRepository;
    private final PersonUpdator personUpdator;

    public Mono<Person> save(Person person) {
        return personRepository.save(person);
    }

    public Mono<Person> get(String id) {
        return personRepository.findById(id);
    }

    public Person update(Person person) {
        personUpdator.executeStoredProcForUpdatePerson(person, person.getLastName());
    }
}
```
**PersonController.java**
```

@RestController
@RequiredArgsConstructor
public class FlexiHierarchyController {

    private final PersonService personService;

    @PostMapping("/person")
    public Mono<Person> personSave(@RequestBody Person person){
       return personService.save(person);
    }
    @GetMapping("/person")
    public Mono<Person> personGet(@RequestParam String id){
        return personService.get(id);
    }

    @PutMapping("/person")
    public Person personUpdate(@RequestBody Person person){
        return personService.update(person);
    }

}

```

**updatePerson.js** -> Cosmos DB Stored Proce
```javascript

function updatePerson(personToUpdate){
    var context = getContext();
    var collection = getContext().getCollection();
    var doc = personToUpdate;

    // Some other tasks. 1.2.3....
    //replace ENTITY patch document
    var isAccepted1 = collection.replaceDocument(doc._self, doc, {etag: doc._etag},
                 function (err, documentCreated) {  
                  if (err) throw new Error('Error while updating Person document' + err.message);  
                    context.getResponse().setBody(documentCreated)  
            });  

    if(!isAccepted || !isAccepted1) throw new Error('Error while updating Person document');

}
```

**PersonUpdator.java**
```
public String executeStoredProcForUpdatePerson(Object personTobeUpdated, String partitionKey) throws Exception {
       
        CosmosStoredProcedureRequestOptions options = new CosmosStoredProcedureRequestOptions();
        options.setPartitionKey(new PartitionKey(partitionKey));
        List<Object> params = Arrays.asList(new ObjectMapper().writeValueAsString(personTobeUpdated));
        CosmosStoredProcedureResponse executeResponse = container.getScripts()
                .getStoredProcedure(updatePerson)
                .execute(params, options);
        return executeResponse.getResponseAsString();
    }
```

**pom.xml**
 ```xml
    <parent>
        <groupId>org.springframework.boot</groupId>
        <artifactId>spring-boot-starter-parent</artifactId>
        <version>3.2.5</version>
        <relativePath/> <!-- lookup parent from repository -->
    </parent>
    <properties>
        <java.version>17</java.version>
        <spring-cloud-azure.version>5.11.0</spring-cloud-azure.version>
    </properties>
    <dependencyManagement>
        <dependencies>
            <dependency>
                <groupId>com.azure.spring</groupId>
                <artifactId>spring-cloud-azure-dependencies</artifactId>
                <version>${spring-cloud-azure.version}</version>
                <type>pom</type>
                <scope>import</scope>
            </dependency>
        </dependencies>
    </dependencyManagement>
    <dependencies>
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-actuator</artifactId>
        </dependency>
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-web</artifactId>
        </dependency>
        <dependency>
            <groupId>com.azure.spring</groupId>
            <artifactId>spring-cloud-azure-starter-data-cosmos</artifactId>
        </dependency>
    </dependencies>
```

**Expected behavior**
Two Things :
1. Putting annotation `@JsonProperty("_etag")` on etag attribute should not make etag as null.
2. If  etag is annotated with `@Version` , then updating a record via stored proc should not create an `etag` attribute in the document .

**Screenshots**
![image](https://github.com/Azure/azure-sdk-for-java/assets/22274113/8a52a0fb-dabe-4c97-933d-9f7e259a62f5)

**Setup (please complete the following information):**
 - OS: Mac Os
 - IDE: IntelliJ Ultimate
 - Library/Libraries: <spring-cloud-azure.version> 5.11.0 </spring-cloud-azure.version> , Please chcek above pom.xml to
 - Java version: 17
 - App Server/Environment: Sping Boot Default Tomcat
 - Frameworks: Spring Boot

**Information Checklist**
Kindly make sure that you have added all the following information above and checkoff the required fields otherwise we will treat the issuer as an incomplete report
- [x] Bug Description Added
- [x] Repro Steps Added
- [x] Setup information Added

**Comment by kushagraThapar** [comment]
@trande4884 can you please take a look at this issue, thanks!

**Comment by SanjayDasTezpur** [comment]
Hi @trande4884 @kushagraThapar any update on this ??

**Comment by kushagraThapar** [comment]
@SanjayDasTezpur - apologies for the delay, this is currently under investigation and we will provide an update soon on it.

**Comment by trande4884** [comment]
@SanjayDasTezpur so the issue here is that you are not going to use specifically @Version with @JsonProperty("_etag") specifically. The reason is that @Version already maps to "_etag" in the backend, no matter what the field name is if it is tagged @Version it will be mapped to "_etag"; this is causing issues when @Version and @JsonProperty both try to do the same mapping. Is there any reason you can't simply name the field "_etag" instead of "etag"? There is nothing blocking this as you can see in some of our [test cases here](https://github.com/Azure/azure-sdk-for-java/blob/c435ac68ce9f8d2f817813cdb17c2fb698c2dcda/sdk/spring/azure-spring-data-cosmos/src/samples/java/com/azure/spring/data/cosmos/MyItem.java#L10).

**Comment by trande4884** [comment]
Closing issue
