### ISSUE TITLE
Error: building account: could not acquire access token to parse claims: running Azure CLI: exit status 2: ERROR: az: error: unrecognized arguments: --scope https://graph.microsoft.com/.default │ usage: az [-h] [--verbose] [--debug] │           [--output {json,jsonc,table,tsv,yaml,none}] [--query JMESPATH] │           {account} ...

### ISSUE THREAD

**Issue by wail-senna** [Azure/azure-sdk-for-java#40041]
**Describe the bug**
i'm working with terraform and azure cloud, after i run the commandes "terraform init" and "az login" everything goes well, but when i run "terraform plan" i get this error :
############################################################################################
Error: building account: could not acquire access token to parse claims: running Azure CLI: exit status 2: ERROR: az: error: unrecognized arguments: --scope https://graph.microsoft.com/.default
│ usage: az [-h] [--verbose] [--debug]
│           [--output {json,jsonc,table,tsv,yaml,none}] [--query JMESPATH]
│           {account} ...
############################################################################################
i verified the account login with "az account show" and "az account get-access-token --output json --resource https://management.core.windows.net" and everything seems correct, i don't know where is the problem

**Comment by joshfree** [comment]
Hi @wail-senna this is a GitHub repo for Java SDK questions, feedback, and feature requests.  At first glance, this question doesn't appear related to Java client libraries for Azure.  Please apologize if I misunderstood.  Based on what was shared, I'd recommend checking out the resources listed in https://github.com/Azure/azure-sdk-for-java/blob/main/SUPPORT.md for getting general purpose support from Azure which isn't related to Java SDKs.
