### ISSUE TITLE
[QUERY] Issue with running spring boot application on azure spring apps with key vault configuration by using service principal identity

### ISSUE THREAD

**Issue by kirankumar994** [Azure/azure-sdk-for-java#40044]
**Query/Question**
I have a spring boot application, using key vault to store my mongodb credentials. I am using service principal authentication to connect with azure key vault. The application is currently running on local env with the below code attached after log in with az login service principal. But, when I am trying to deploy it on azure spring cloud, I am getting the below exception

java.lang.IllegalStateException: Failed to configure KeyVault property source

This is the Bean I kept in my mongodb config class. I am using the same service principal to deploy from local. And, it is getting deployed as well, but the application failed to start due to above exception. I tried with managed identity as well but no luck. I wanted to use service principal to connect with azure key vault as well. Here is the screenshot of the same service principal to the key vault.

![Screenshot from 2024-04-26 10-52-32](https://github.com/Azure/azure-sdk-for-java/assets/19862708/825498f0-a03a-4216-9a27-4d736d5b3d93)

```java
@Value("${azure.keyvault.client-id}")
private String clientId;

@Value("${azure.keyvault.client-key}")
private String clientSecret;

@Value("${azure.keyvault.tenant-id}")
private String tenantId;

@Value("${spring.cloud.azure.keyvault.secret.property-sources[0].endpoint}")
private String keyVaultEndpoint;

@Bean
public SecretClient createSecretClient() {

    ClientSecretCredential clientSecretCredential = new ClientSecretCredentialBuilder()
            .clientId(clientId)
            .clientSecret(clientSecret)
            .tenantId(tenantId)
            .build();

    // Azure SDK client builders accept the credential as a parameter.
    return new SecretClientBuilder()
            .vaultUrl(keyVaultEndpoint)
            .credential(clientSecretCredential)
            .buildClient();
}
```

 Here is the dependency I am using in my spring boot application. 

<dependency>
    <groupId>com.azure.spring</groupId>
    <artifactId>spring-cloud-azure-starter-keyvault</artifactId>
    <version>5.11.0</version>
</dependency>
 
 **Information Checklist**
 Kindly make sure that you have added all the following information above and checkoff the required fields otherwise we will treat the issuer as an incomplete report
- [ ] Query Added
- [ ] Setup information Added

**Comment by saragluna** [comment]
@kirankumar994 are you using the `com.azure.spring spring-cloud-azure-starter-keyvault` to retrieve the kv property source, instead of using the kv secret client and get the secret by yourself?

**Comment by kirankumar994** [comment]
Hi @saragluna , here is the dependency I am using.        
 
`<dependency>
            <groupId>com.azure.spring</groupId>
            <artifactId>spring-cloud-azure-starter-keyvault</artifactId>
            <version>5.11.0</version>
        </dependency>`

**Comment by saragluna** [comment]
Hi @kirankumar994, what do you mean by `The application is up and runnin after I login with az login service principal`? 

What's the properties you set on Azure Spring Apps, I guess that the KV property source is enabled, but without any credential to connect to the KV client in the property source. The bean you defined in the following code is a different client object from the KV client newed in the KV property source.

```java
return new SecretClientBuilder()
            .vaultUrl(keyVaultEndpoint)
            .credential(clientSecretCredential)
            .buildClient();
```
