### ISSUE TITLE
[QUERY]how to use dall-e-2 in 1.0.0-beta.8?

### ISSUE THREAD

**Issue by fengsuxing** [Azure/azure-sdk-for-java#40043]
**Query/Question**
how to use dall-e-2 in 1.0.0-beta.8?

i want to use dall-e-2 .but  client.getImageGenerations(deploymentOrModelName, imageGenerationOptions) doesnot support dall-e-2 ,how to solve this?

**Comment by joshfree** [comment]
@mssfang PTAL

**Comment by fengsuxing** [comment]
any solutions?

**Comment by mssfang** [comment]
Hi, @fengsuxing Sorry to replay it late. I just get back from my vocation. 
We do support DALL-E ("dall-e-2" or "dall-e-2") in the SDK.  Wondering which region of Azure source you are using?

**Comment by fengsuxing** [comment]
@mssfang in 1.0.0-beta.8, client.getImageGenerations(deploymentOrModelName, imageGenerationOptions)  doesnot support "dall-e-2".if you think it supports,please give me an example on how to Call  getImageGenerations using dall-e-2?

**Comment by mssfang** [comment]
@fengsuxing You can try to use this [sample](https://github.com/Azure/azure-sdk-for-java/blob/main/sdk/openai/azure-ai-openai/src/samples/java/com/azure/ai/openai/usage/GetImagesSample.java#L23) in the repo

```
 OpenAIClient client = new OpenAIClientBuilder()
      .credential(new KeyCredential("your-openai-key-here"))
      .buildClient();
```

For Azure Resource, you can create DALL-E-3(dall-2 is in preview)
https://learn.microsoft.com/en-us/azure/ai-services/openai/concepts/models#dall-e-models
