### ISSUE TITLE
[QUERY] How to get total count of blobs size in a container?

### ISSUE THREAD

**Issue by kirankumar994** [Azure/azure-sdk-for-java#40089]
Hi, 

I have a requirement to get the sum of all blobs size for each container. I know I can calculate the size by listing all blobs and summing up all of them to get the container size, but that is too complex on the code level as each blob can have lot of versions and soft deleted blobs within the container etc. I would like to know if there is any way, where in i can just make one api call per container to get the total size of the container (sum of all blobs size)? 

Thanks in advance.

**Comment by ibrahimrabab** [comment]
Hi @kirankumar994 
There isn't an API available today that you can use to get a total count of all blobs in the container. You can specify whether you want to include deleted blobs or versioned blobs when calling listBlobs(ListBlobsOptions, String, Duration). Please take a look at ListBlobsOptions and BlobListDetails, 

https://github.com/Azure/azure-sdk-for-java/blob/main/sdk/storage/azure-storage-blob/src/main/java/com/azure/storage/blob/models/ListBlobsOptions.java

https://github.com/Azure/azure-sdk-for-java/blob/main/sdk/storage/azure-storage-blob/src/main/java/com/azure/storage/blob/models/BlobListDetails.java

Let me know if this helps or if you have any further questions!
