### ISSUE TITLE
[BUG] no azure-spring-data-cosmos 3.45.0 find in Maven

### ISSUE THREAD

**Issue by Teale001** [Azure/azure-sdk-for-java#40080]
https://mvnrepository.com/artifact/com.azure/azure-spring-data-cosmos

**Comment by alzimmermsft** [comment]
HI @Teale001, this is available: https://repo1.maven.org/maven2/com/azure/azure-spring-data-cosmos/3.45.0/

https://central.sonatype.com/artifact/com.azure/azure-spring-data-cosmos/3.45.0/overview

mvnrepository just hasn't updated its indices.
