### ISSUE TITLE
[QUERY] How to catch the networking error while use the azure-stream-binder SDK

### ISSUE THREAD

**Issue by yunbozhang-msft** [Azure/azure-sdk-for-java#40091]
**Question**
We are using SDK: com.azure.spring:spring-cloud-azure-stream-binder-eventhubs
Team, do you know how to catch the networking error while use this SDK?

![image](https://github.com/Azure/azure-sdk-for-java/assets/44389598/6756a46b-bb50-48c5-a1bd-ca4a70d4c64b)
When we process the message in the consume method, we have successfully received the message, but if there is a problem with the network before that, we do not consume the message, or it causes a retry. Do you know how to handle this network anomaly?

***Why is this not a Bug or a feature Request?***
I do not know how to catch networking error.

**Setup (please complete the following information if applicable):**
 - OS: [e.g. iOS] NA
 - IDE: [e.g. IntelliJ] NA
 - Library/Libraries: [e.g. com.azure:azure-core:1.16.0 (groupId:artifactId:version)] com.azure.spring:spring-cloud-azure-stream-binder-eventhubs
 
 **Information Checklist**
 Kindly make sure that you have added all the following information above and checkoff the required fields otherwise we will treat the issuer as an incomplete report
- [x] Query Added
- [ ] Setup information Added

**Comment by saragluna** [comment]
I any error is thrown from this consumer, you could use this approach to listen to the error channel, https://github.com/Azure-Samples/azure-spring-boot-samples/blob/17291f4816b2cf833bd6dbadbde48eb652bfb8c9/eventhubs/spring-cloud-azure-stream-binder-eventhubs/eventhubs-binder/src/main/java/com/azure/spring/sample/eventhubs/binder/EventHubBinderApplication.java#L25-L36.

Or you could refer to this doc https://docs.spring.io/spring-cloud-stream/reference/spring-cloud-stream/overview-error-handling.html for Spring Cloud Stream error handling.

**Comment by yunbozhang-msft** [comment]
Thank you @saragluna
