### ISSUE TITLE
openai: Unrecognized request argument supplied:stream_options

### ISSUE THREAD

**Issue by 115341chenzehao** [Azure/azure-sdk-for-java#40198]
Version
0.6.8

Bug
1.When I upgraded from version 0.6.6 to 0.6.8, I encountered the following error message when using OpenAI:
![stream_option](https://github.com/Azure/azure-sdk-for-java/assets/61967670/cd4a108e-f0ec-4a04-b504-5595dac6ff06)

2.Upon comparing version 0.6.6 with 0.6.8, it was found that in the OpenAI 'llm.py' there was additional handling for 'stream_option'. After commenting this out and repackaging, OpenAI could be used normally again.
![clipbord_1715829297465](https://github.com/Azure/azure-sdk-for-java/assets/61967670/92f7a4bd-841d-4ecf-b596-87bf027870fb)

Additional questions
1."After installing 'mysql-connector-python', does Dify's 'code execution' support connecting to a database?"
![Uploading image.png…]()

**Comment by 115341chenzehao** [comment]
sorry

**Comment by alzimmermsft** [comment]
Closing as this isn't the right repository for this issue
