### ISSUE TITLE
[BUG] other AI provider doesn't work with NonAzureOpenAI 

### ISSUE THREAD

**Issue by junan-trustarc** [Azure/azure-sdk-for-java#40195]
**Describe the bug**
I am trying to use multiple AI providers using this SDK since payload is same, 
1. Azure OpenAI
2. Open AI
3. Perplexity AI

However, there is hard coded value **OPEN_AI_ENDPOINT** for nonAzureOpenAi and can't modify, so that only Azure OpenAI and OpenAi are working and doesn't work with other AI provider such as Perplexity AI even though payload of request, response is same.

**To Reproduce**
set endpoint = "https://api.perplexity.ai/"

***Code Snippet***
![image](https://github.com/Azure/azure-sdk-for-java/assets/134445960/889501cd-01e7-430e-84b9-54abc9c88087)
![image](https://github.com/Azure/azure-sdk-for-java/assets/134445960/433297b5-76d0-4d7b-b7fc-84078e56eed1)
![image](https://github.com/Azure/azure-sdk-for-java/assets/134445960/db921d98-7fa4-46d8-9c98-f14bc6f7f39f)

**Expected behavior**
Need to able to modify OPEN_AI_ENDPOINT (maybe rename to generic like nonAzureAiEndpoint) while creating OpenAIAsyncClient using OpenAIClientBuilder so that this will support for all other AI providers.

**Information Checklist**
Kindly make sure that you have added all the following information above and checkoff the required fields otherwise we will treat the issuer as an incomplete report
- [v] Bug Description Added
- [v] Repro Steps Added
- [v] Setup information Added

**Comment by mssfang** [comment]
Hi @junan-trustarc 

Unfortunately, we will not support non-OpenAI models in this SDK, azure-ai-openai as per our partnership with OpenAI.
The most major models are available as first-class Azure Host Endpoints, such as Llama2, Cohere and Mistra, via Azure MaaS ([Azure AI Studio Model Catalog](https://learn.microsoft.com/en-us/azure/ai-studio/how-to/model-catalog)). They can also host most Hugging Face models or your own models in the future via Azure MaaP(AML) in the future. We will provide an ("OpenAI like") Model Inference API spec for completions to MaaS in the near future.

Worth to mention here that this SDK supports [proxy feature](https://github.com/Azure/azure-sdk-for-java/blob/main/sdk/openai/azure-ai-openai/src/samples/java/com/azure/ai/openai/OpenAIProxySample.java) in case someone not aware of it.
