### ISSUE TITLE
customer request to add support for SAS token for service bus

### ISSUE THREAD

**Issue by gcheng** [Azure/azure-sdk-for-java#402]
http://stackoverflow.com/questions/17625137/using-sas-to-access-azure-service-bus-with-java

**Comment by AntonioGa** [comment]
Hi, I cannot find ServiceBusConfiguration method that supports shared access signature.
I'm using:
<dependency>
            <groupId>com.microsoft.azure</groupId>
            <artifactId>azure-servicebus</artifactId>
            <version>0.9.7</version>
</dependency>
