### ISSUE TITLE
[resource manager] Refactor resourcemanager tests to work with latest TestProxy 

### ISSUE THREAD

**Issue by samvaity** [Azure/azure-sdk-for-java#40209]
To address the timeout issues with ResourceManager tests when using the latest Test Proxy, the tests are [being marked as `LiveOnly`](https://github.com/Azure/azure-sdk-for-java/pull/39935) The central sanitization process on the recordings may be causing the timeouts. 

Need to figure out what central sanitizers should be disabled or refactoring the tests to make it compatible with the sanitization process, ensuring they can run without the need for live-only conditions. This will likely involve adjusting the test setup, and the data validation steps within the tests.

**Comment by scbedd** [comment]
Tag me in @weidongxu-microsoft with questions. I have reason to believe that something in the upstream sanitizers is messing with the batching of azure-core on java side, so requests aren't flowing as quickly as they should be.

We saw that with .NET, due to the sanitizer `AZSDK3448`

**Comment by weidongxu-microsoft** [comment]
resourcemanager sanitizer mostly at here
https://github.com/Azure/azure-sdk-for-java/blob/main/sdk/resourcemanager/azure-resourcemanager-test/src/main/java/com/azure/resourcemanager/test/ResourceManagerTestProxyTestBase.java#L439-L480

a few module would add a few more, e.g.
https://github.com/Azure/azure-sdk-for-java/blob/main/sdk/resourcemanager/azure-resourcemanager-containerregistry/src/test/java/com/azure/resourcemanager/containerregistry/RegistryTest.java#L28-L33

**Comment by weidongxu-microsoft** [comment]
We are actually fine with `@liveOnly`.

If we upgrade api-version of a service, we generally require dev to re-run them as LIVE, as there is no promise that backend does not have behavior change (that can only be figured out when run LIVE).
