### ISSUE TITLE
[FEATURE REQ] Add support for managed identities in azure-storage-file-share

### ISSUE THREAD

**Issue by mehradn7** [Azure/azure-sdk-for-java#40233]
**Is your feature request related to a problem? Please describe.**

Spring Cloud Azure does not support authentication with managed identities for Azure Storage File Share (based on [4.0 release notes](https://learn.microsoft.com/en-us/azure/developer/java/spring-framework/developer-guide-overview?tabs=maven#whats-new-in-40-since-310x) and [Microsoft docs](https://learn.microsoft.com/en-us/azure/developer/java/spring-framework/authentication#authorize-access-with-microsoft-entra-id)).

**Describe the solution you'd like**

Support managed identity authentication for Azure Storage File Share (similarly to Azure Blob Storage which currently supports it).

Thanks.

**Information Checklist**
Kindly make sure that you have added all the following information above and checkoff the required fields otherwise we will treat the issuer as an incomplete report
- [X] Description Added
- [X] Expected solution specified

**Comment by ibrahimrabab** [comment]
Hi @mehradn7 
Currently only Azure Blobs and Azure DataLake are supported with managed identities,
https://learn.microsoft.com/en-us/entra/identity/managed-identities-azure-resources/services-id-authentication-support

To request support for file shares, please reach out to the Managed Identity team. Hope this helps!
