### ISSUE TITLE
Legacy flag for the Java SDK

### ISSUE THREAD

**Issue by kaushal02** [Azure/azure-sdk-for-java#40237]
### Type of issue

Outdated article

### Description

Doc page says Legacy in the heading, what does that mean? Is the source code not maintained anymore? Azure SDK for Java seem to be well maintained, and the particular library (Azure API Management) was last released in 2022-08. 

### Page URL

https://learn.microsoft.com/en-us/java/api/overview/azure/api-management?view=azure-java-archive

### Content source URL

https://github.com/Azure/azure-docs-sdk-java/blob/master/docs-ref-services/archive/api-management.md

### Document Version Independent Id

b83a0d17-760b-87dd-c3cd-0bc7f5f3dee2

### Article author

@azure-sdk

### Metadata

* ID: ddb9ee15-68ca-e832-f83b-398aaae535df 
* Service: **apimanagement**

**Comment by joshfree** [comment]
@sandeep-sen @weidongxu-microsoft  could you please take a look?

**Comment by weidongxu-microsoft** [comment]
It seems to be done by the learn site?

I can switch to this same "legacy", by changing the "Version" dropdown
https://learn.microsoft.com/en-us/java/api/overview/azure/compute?view=azure-java-stable
![image](https://github.com/Azure/azure-sdk-for-java/assets/53292327/6f9043c6-f7e7-44e6-a63e-ce9751b2856e)
to
https://learn.microsoft.com/en-us/java/api/overview/azure/compute?view=azure-java-archive
