### ISSUE TITLE
[BUG] Class AppServiceMSICredentials doesn't provide a way to pass clientID to call the local MSI endpoint. It includes a class but no options are available.  

### ISSUE THREAD

**Issue by kaushalp** [Azure/azure-sdk-for-java#4024]
**Describe the bug**
Class AppServiceMSICredentials doesn't provide a way to pass clientID to call the local MSI endpoint. It includes a class but no options are available. 

**To Reproduce**
Just try using the Azure SDK for Java and try to use the AppServiceMSICredentials class and you will see an error right away. 

***Code Snippet***
Here is the link to the code on GitHub: https://github.com/Azure/autorest-clientruntime-for-java/blob/master/azure-client-authentication/src/main/java/com/microsoft/azure/credentials/AppServiceMSICredentials.java

**Expected behavior**
The class AppServiceMSICredentials does not include a definition for passing a clientID of the User-Assigned MSI.
This is a necessary parameter when working with User Assigned MSI. See [this  ](https://docs.microsoft.com/en-us/azure/app-service/overview-managed-identity#using-the-rest-protocol )

**Screenshots**
This works when the MSI endpoint called explicitly using curl in Kudu. We need a way for the clientid to be passed via Java SDK
![image](https://user-images.githubusercontent.com/4186691/59871424-69014800-934c-11e9-92cc-bdfeb8a1b539.png)

**Setup (please complete the following information):**
 - OS: Azure App Services (Windows)
 - IDE : VS Code
 - Recent version

**Additional context**
Currently using the Java SDK to call the MSI endpoint results in a 400 bad request as it doesn't include the clientid in the query string. 

We probably something like add something like this to the class definition?

```
    public AppServiceMSICredentials withClientId(String clientId) {
        this.clientId = clientId;
        this.objectId = null;
        this.identityId = null;
        return this;
    }
```

**Information Checklist**
Kindly make sure that you have added all the following information above and checkoff the required fields otherwise we will treat the issuer as an incomplete report
- [x] Bug Description Added
- [x] Repro Steps Added
- [x] Setup information Added

**Comment by praries880** [comment]
This issue just got fixed over in the clientruntime for java repo : https://github.com/Azure/autorest-clientruntime-for-java/pull/622
