### ISSUE TITLE
[FEATURE REQ] [OpenAI Client] Feature parity with official Python client (and also fully support vLLM)

### ISSUE THREAD

**Issue by br3no** [Azure/azure-sdk-for-java#40304]
**Is your feature request related to a problem? Please describe.**
This is a bit of a stretch, but I'll give it a shot:

I'm using [vLLM](https://github.com/vllm-project/vllm) to host LLMs on premises. vLLM exposes an OpenAI compatible API and can be interacted with using the regular OpenAI Python client. 

vLLM supports guided decoding features that go beyond what OpenAI can do. You can e.g. define EBNF grammars your output must conform to and vLLM (through e.g. [Outlines](https://github.com/outlines-dev/outlines)) will enforce it.

Although these features don't exist in the OpenAI API, the official OpenAI Python client allows one to pass on an `extra_body` (`extra_header` and `extra_query` as well) when creating the completion (c.f. https://github.com/openai/openai-python/blob/5a89126ad208c58b9e1dbd1fbdb698e4c00f7d8e/src/openai/resources/chat/completions.py#L74). The `extra_body` will be added to the call. This makes the OpenAI Python client perfectly suitable to be used as a fully functional vLLM client.

Unfortunately, there is no Java client for the OpenAI API that exposes the same functionality.

**Describe the solution you'd like**
Being the best supported Java Client for OpenAI out there, I'd love to be able to use the Azure OpenAI client to interact with vLLM and be able to use all guided generation functionalities vLLM has to offer.

The only thing missing is the support for the `extra_body` parameter in the completion objects. This is what I'd like to add to the client.

I'd be happy to contribute this functionality, if the maintainers give me a signal that this change has a shot of being merged.

I'd understand if the answer is negative, since this is not a vLLM client project.

On the other hand, the official OpenAI Python client is the canonical source of truth and the Java client currently diverges from it in this regard. Also, vLLM is the most used open source LLM runtime engine out there, and in the spirit of open source, it would be really nice, if the Azure OpenAI client could support this use-case as well.

**Describe alternatives you've considered**
I could fork this repository or even write my own client. But I'd really rather not.

**Additional context**
-

**Information Checklist**
Kindly make sure that you have added all the following information above and checkoff the required fields otherwise we will treat the issuer as an incomplete report
- [x] Description Added
- [x] Expected solution specified

**Comment by manzke** [comment]
👍

**Comment by mssfang** [comment]
Hi @br3no  
Unfortunately, we will not support non-OpenAI models in this SDK, azure-ai-openai as per our partnership with OpenAI.
The most major models are available as first-class Azure Host Endpoints, such as Llama2, Cohere and Mistra, via Azure MaaS ([Azure AI Studio Model Catalog](https://learn.microsoft.com/en-us/azure/ai-studio/how-to/model-catalog)).
