### ISSUE TITLE
[FEATURE REQ] Add @ServiceConnection support for CosmosDB, EventHub and Azurite

### ISSUE THREAD

**Issue by eddumelendez** [Azure/azure-sdk-for-java#40329]
**Is your feature request related to a problem? Please describe.**
Spring Boot 3.1.0 introduced `ConnectionDetails`. You can read more about it [this blog post](https://spring.io/blog/2023/06/19/spring-boot-31-connectiondetails-abstraction/). There's integration for both Testcontainers and Docker Compose where Spring Boot is able to source the details of the connection.

I can contribute with this feature.

**Describe the solution you'd like**
Add support for `ConnectionDetails`, then `@ServiceConnection` would work for CosmosDB, EventHub and Azurite emulators.

```java
@Container
@ServiceConnection
private static final GenericContainer<?> azurite = new GenericContainer<>(
			"mcr.microsoft.com/azure-storage/azurite:latest")
		.withExposedPorts(10000);
```

**Describe alternatives you've considered**
Keep using `DynamicPropertySource` to register the connection details manually.

```java
@DynamicPropertySource
static void properties(DynamicPropertyRegistry registry) {
	var azuriteHost = azurite.getHost();
	var azuriteBlobMappedPort = azurite.getMappedPort(AZURE_STORAGE_BLOB_PORT);
	var connectionString = "DefaultEndpointsProtocol=http;AccountName=devstoreaccount1;AccountKey=Eby8vdM02xNOcqFlqUwJPLlmEtlCDXJ1OUzFT50uSRZ6IFsuFq2UVErCz4I6tq/K1SZFPTOtr/KBHBeksoGMGw==;BlobEndpoint=http://%s:%d/devstoreaccount1;"
		.formatted(azuriteHost, azuriteBlobMappedPort);
	registry.add("spring.cloud.azure.storage.blob.connection-string", () -> connectionString);
}
```

**Additional context**

**Information Checklist**
Kindly make sure that you have added all the following information above and checkoff the required fields otherwise we will treat the issuer as an incomplete report
- [x] Description Added
- [x] Expected solution specified

**Comment by saragluna** [comment]
@eddumelendez, thanks for bringing this up, it would be great if you could contribute with this feature.

**Comment by eddumelendez** [comment]
@saragluna thanks for the quick response. I've submitted #40388 supporting Cosmos, Storage Blob and Storage Queue. Looks like eventhubs emulator is not supported by the SDK yet but will keep an eye and update it once it is supported.

**Comment by saragluna** [comment]
@eddumelendez, looks great, thanks!

**Comment by rujche** [comment]
FYI: About the test failure, I create a issue in spring-boot repo: https://github.com/spring-projects/spring-boot/issues/41100

And for current PR, I'll fix this test failure by a workaround.
