### ISSUE TITLE
Cannot configure the try timeout on @ServiceBusListener

### ISSUE THREAD

**Issue by nikoladjuran** [Azure/azure-sdk-for-java#40412]
There isn't currently a configuration that works for setting the try timeout when using the `@ServiceBusListener` approach. Because of the implementation linked below, the ServiceBusClientBuilder gets instantiated without any configuration taken into consideration and a default retry policy is used(Try timeout = 1 min).

https://github.com/Azure/azure-sdk-for-java/blob/33c277163a89fd4abcd146dd11d3bf145fb7970f/sdk/spring/spring-messaging-azure-servicebus/src/main/java/com/azure/spring/messaging/servicebus/core/DefaultServiceBusNamespaceProcessorFactory.java#L178

This should probably be configurable as it's constantly logging exceptions every 1 min if there is no traffic
`The operation did not complete within the allotted timeout of 00:00:59. The time allotted to this operation may have been a portion of a longer timeout. For more information on exception types and proper exception handling, please refer to https://aka.ms/ServiceBusExceptions`

Either that or think about changing the log level to debug.

**Comment by anuchandy** [comment]
Hello, this log shows that there is no new session found in the last one minute. Unfortunately, the wait timeout for session availability is not adjustable, the Service Bus broker has a fixed 1 minute, and client cannot change it.
