### ISSUE TITLE
Cosmos DB Sample Issue

### ISSUE THREAD

**Issue by faynef** [Azure/azure-sdk-for-java#40423]
**Section** [link](https://github.com/Azure/azure-sdk-for-java/blob/main/sdk/cosmos/azure-cosmos/src/samples/java/com/azure/cosmos/ComputedPropertiesCodeSnippet.java#L50):
![image](https://github.com/Azure/azure-sdk-for-java/assets/138087452/89c26ebf-e19a-4cfa-9098-9aead21d192e)

**Reason**: 
Not set computed properties.

**Suggestion**:
Add code `
containerProperties.setComputedProperties(computedProperties);
`

@sandeep-sen , @joshfree , @kyle-patterson , @KrzysztofCwalina and @aayush3011 for notification.

**Comment by Menghua1** [comment]
PR https://github.com/Azure/azure-sdk-for-java/pull/40431 has fixed this issue, I will close this issue.
