### ISSUE TITLE
Digital Twins Readme Issue

### ISSUE THREAD

**Issue by faynef** [Azure/azure-sdk-for-java#40421]
**Section** [link](https://github.com/Azure/azure-sdk-for-java/tree/main/sdk/digitaltwins/azure-digitaltwins-core#azure-iot-digital-twins-client-library-for-java):
![image](https://github.com/Azure/azure-sdk-for-java/assets/138087452/5a9a0b3b-87ca-43c2-9d98-2eda0b76636e)

**Reason**:
The link address is inaccurate.

**Suggestion**:
Update link to: https://github.com/Azure/azure-sdk-for-java/tree/main/sdk/digitaltwins/azure-digitaltwins-core/src

@sandeep-sen , @joshfree , @johngallardo and @Aashish93-stack  for notification.

**Comment by Menghua1** [comment]
According to the [comments](https://github.com/Azure/azure-sdk-for-java/issues/40422#issuecomment-2168666953), this is not an issue, I will close this issue.
