### ISSUE TITLE
Azure Blob Storage Checkpoint Store Readme Issue

### ISSUE THREAD

**Issue by faynef** [Azure/azure-sdk-for-java#40422]
**Section** [link](https://github.com/Azure/azure-sdk-for-java/tree/main/sdk/eventhubs/azure-messaging-eventhubs-checkpointstore-blob):
![image](https://github.com/Azure/azure-sdk-for-java/assets/138087452/3e84a4ae-7bd9-4008-b8e6-fbae75590ea0)

**Reason**:
The link address is inaccurate.

**Suggestion**:
Update link to: https://github.com/Azure/azure-sdk-for-java/tree/main/sdk/eventhubs/azure-messaging-eventhubs-checkpointstore-blob/src

@sandeep-sen , @joshfree , @ronniegeraghty , @ellismg and @antkmsft  for  notification.

**Comment by lmolkova** [comment]
The link accurately points to https://github.com/Azure/azure-sdk-for-java/blob/main/sdk/eventhubs/azure-messaging-eventhubs-checkpointstore-blob which is a root folder for all the code (including pom.xml, readme, changelog).

We use the same pattern for all other libraries.
