### ISSUE TITLE
[QUERY] list blobs in a container, recursive option

### ISSUE THREAD

**Issue by itishaniyeh** [Azure/azure-sdk-for-java#40523]
**Query/Question**
We are developing an application on top of Azure Blob Storage APIs.
our requirements for one of the features are to list the existing blobs in a specific container and path by supporting the following options:
1. pagination
2. directory, file, and ... filtration
3. recursive listing or non-recursive

we tried two different options from the SDK:
- DataLakeFileSystemClient.listPaths(): which supports 1 and 3 but not 2
- BlobContainerClient.listBlobsByHierarchy(): which supports 1 and 2 but not 3

*also filtering out files or directories after getting them from the blob storage in the code would adversely affect the pagination.

in addition, we tried
The [List Blobs API ](https://learn.microsoft.com/en-us/rest/api/storageservices/list-blobs?tabs=azure-ad)documents showonly={deleted,files,directories} option cannot be found in the `ListBlobsOptions` SDK.

***Why is this not a Bug or a feature Request?***
not a bug, could you please help with how to achieve this goal?

**Setup (please complete the following information if applicable):**
 - Library: com.azure:azure-storage-file-datalake:12.14.1
 
 **Information Checklist**
- [x] Query Added
- [x] Setup information Added

**Comment by itishaniyeh** [comment]
based on this doc: https://learn.microsoft.com/en-us/azure/storage/blobs/storage-blobs-list-javascript#use-a-hierarchical-listing
using `/` as the delimiter option can do a hierarchical listing
still all features are not implemented in the SDK so just call https://learn.microsoft.com/en-us/rest/api/storageservices/list-blobs?tabs=microsoft-entra-id API

**Comment by ibrahimrabab** [comment]
Hi @itishaniyeh 
Thank you for reaching out! As of right now, ListBlobs with the option of filtering on files vs. directories isn't supported. If you want to retrieve only files or only directories, you would need to call listBlobs/listPaths and then perform filtering which like you mentioned, can affect the pagination. 
You can also try the following:
https://learn.microsoft.com/en-us/azure/storage/blobs/storage-blobs-list-java#use-a-hierarchical-listing

**Comment by itishaniyeh** [comment]
Thank you @ibrahimrabab
