### ISSUE TITLE
OOM error caused by AzureMonitorLogRecordExporter

### ISSUE THREAD

**Issue by rafalp88** [Azure/azure-sdk-for-java#40546]
Below line cause OOM error. When DEBUG level is on, there will be some kind of recursive invocation. 
LogRecords logging causes more log entries which causes sending more and more LogRecords.
  
https://github.com/Azure/azure-sdk-for-java/blob/174041384dd09ac1bb23a07655f4a966af7c777a/sdk/monitor/azure-monitor-opentelemetry-exporter/src/main/java/com/azure/monitor/opentelemetry/exporter/AzureMonitorLogRecordExporter.java#L57

**Comment by lmolkova** [comment]
@rafalp88 

Thank you for reporting this!
As a mitigation step,  could you please disable verbose logs from `com.azure.monitor.opentelemetry.exporter`? If you haven't done it already ?

@heyams @trask could you please take a look? 

it seems exporter logs with `ClientLogger` from core which, when such debug logs are enabled, produces enormous amount of logs.

We might need to figure out how to disable all logs from the exporter http pipeline completely or prevent the exporter from consuming its own logs in some other way. LMK if you need any help with `ClientLogger`.
