### ISSUE TITLE
[BUG] Not getting addressPrefix from Subnet object

### ISSUE THREAD

**Issue by amandeepsp** [Azure/azure-sdk-for-java#40562]
**Describe the bug**
Hi, when querying subnets CIDRs from Azure's Java SDK v2.21.0, I am not getting `addressPrefix` field form the management APIs. 

This is happening for following subnets in regions regions = eastus, westus, this particular resource group also has subnets in other regions where I am getting `addressPrefix` correctly. Subnet cidrs are displayed correctly on Azure Portal.

***Exception or Stack Trace***
NA

**To Reproduce**
NA

***Code Snippet***
I am using the following code snippet to get addressPrefix.
 
```java
final String cidr = currentSubnet.innerModel()
                        .addressPrefix();
```
 
Where currentSubnet is of the type `com.azure.resourcemanager.network.models.Subnet`, which is extracted from the snippet below
 
```java
Map<String, com.azure.resourcemanager.network.models.Subnet> subnets = client.networks().getByResourceGroup(<resource-group-name>, <vnet-name>)
                    .subnets()
```

**Expected behavior**
`addressPrefix` should be present and not null.

**Screenshots**
NA

**Setup (please complete the following information):**
 - OS: RHEL8
 - Library/Libraries: azure-resourcemanager-network-2.21.0.jar
 - Java version: 8
 - App Server/Environment: Apache Karaf
 - Frameworks: Apache CXF

**Additional context**
Corresponding Azure Support ticket - 2406040030006534

**Information Checklist**
Kindly make sure that you have added all the following information above and checkoff the required fields otherwise we will treat the issuer as an incomplete report
- [x] Bug Description Added
- [x] Repro Steps Added
- [x] Setup information Added

**Comment by weidongxu-microsoft** [comment]
@amandeepsp 

There is `addressPrefixes` in the `SubnetInner`. For some resource config, it could be there.

**Comment by amandeepsp** [comment]
Yes, I am able to use `addressPrefix` but its value is `null` in some regions, while it is present in some regions. I can see the actual cidrs in Azure Portal correctly for all regions.

**Comment by weidongxu-microsoft** [comment]
I mean `addressPrefixes`, plural.

**Comment by amandeepsp** [comment]
@weidongxu-microsoft  Do you mean to say that if there are multiple cidrs, the `addressPrefix` is null, but the `addressPrefixes` will be non-null?

**Comment by weidongxu-microsoft** [comment]
Yes, I think this is the logic in backend / REST API.

**Comment by amandeepsp** [comment]
I will try the `addressPrefix` / `addressPrefixes` fields, they will hopefully work. In meantime closing this issue.
