### ISSUE TITLE
[FEATURE REQ] Add live test for azure-resourcemanager-scvmm

### ISSUE THREAD

**Issue by XiaofeiCao** [Azure/azure-sdk-for-java#40651]
https://github.com/Azure/azure-sdk-for-java/tree/main/sdk/scvmm/azure-resourcemanager-scvmm

context, we will be GA it this month, with TypeSpec and azure-json

Please check if we can add a simple LIVE for this service, if it is fine to create their resource.

**Comment by v-hongli1** [comment]
The `scvmm` service must be supported by the front-end service `Kubernetes cluster with Azure Ar`c, but `Kubernetes cluster with Azure Arc` can only be created by script. This way of creating front-end services is not suitable for use in live test. So it is recommended that the service does not add any live test cases.

**Comment by XiaofeiCao** [comment]
Thanks, closing the request.
