### ISSUE TITLE
[QUERY] 升级azure sdk到1.0.0-beta.9 中文问答回复异常

### ISSUE THREAD

**Issue by StrugglingPig** [Azure/azure-sdk-for-java#40653]
**Query/Question**
model:gpt-4o
Model ID=chatcmpl-9b0VJxZZKVVdVz6ZxzObH7FVqOqY8
openAIServiceVersion: V2024_05_01_PREVIEW("2024-05-01-preview")

中文内容：介绍一下马云 
中文base64 : {"messages":[{"content":"5LuL57uN5LiA5LiL6ams5LqR","role":"user"}],"temperature":0.0}
英文：tell about Jack Ma
英文base64：{"messages":[{"content":"dGVsbCBhYm91dCBKYWNrIE1h","role":"user"}],"temperature":0.0}

***Why is this not a Bug or a feature Request?***
问题：感觉中文base64无法识别一样

中文返回内容：
  ”“”
你好！看起来你输入了一些中文字符，但它们可能没有正确显示或是乱码。如果你有任何问题或需要帮助，请告诉我，我会尽力帮你解答。
  “”“
英文返回内容：
  “”“
  Jack Ma, whose full name is Ma Yun, is a Chinese entrepreneur, philanthropist, and the co-founder of Alibaba Group, one of the world's largest e-commerce and technology conglomerates. Born on September 10, 1964, in Hangzhou, Zhejiang Province, China, Jack Ma is known for his inspirational rags-to-riches story and his role in transforming the e-commerce landscape in China and globally.

### Early Life and Education
- **Background**: Jack Ma grew up in a modest family. His parents were traditional musicians and storytellers.
- **Education**: He faced numerous rejections in his early life, including failing the college entrance exam twice. Eventually, he graduated with a bachelor's degree in English from Hangzhou Normal University in 1988.

### Career Beginnings
- **Early Jobs**: Before founding Alibaba, Ma worked as an English teacher and later started a translation business. His first encounter with the internet in the mid-1990s during a trip to the United States sparked his interest in the potential of the web.

### Founding Alibaba
- **Alibaba Group**: In 1999, Jack Ma co-founded Alibaba Group with 17 friends in his apartment. The company started as a B2B marketplace aimed at connecting Chinese manufacturers with overseas buyers.
- **Growth**: Under Ma's leadership, Alibaba expanded into various sectors, including online retail (Taobao, Tmall), cloud computing (Alibaba Cloud), digital payments (Alipay), and more.

### Achievements and Impact
- **IPO**: In 2014, Alibaba's initial public offering (IPO) on the New York Stock Exchange raised $25 billion, the largest IPO in history at that time.
- **Philanthropy**: Jack Ma has been involved in various philanthropic efforts, particularly in education, environmental conservation, and public health. He founded the Jack Ma Foundation in 2014 to support these causes.

### Retirement and Later Activities
- **Retirement**: Jack Ma stepped down as Alibaba's executive chairman in September 2019, handing over the reins to Daniel Zhang. He stated his intention to focus more on philanthropy and education.
- **Public Appearances**: Despite stepping down, Ma remains a prominent figure in the business world and often speaks at international forums and conferences.

### Challenges and Controversies
- **Regulatory Scrutiny**: In recent years, Alibaba and Jack Ma have faced increased scrutiny from Chinese regulators, particularly concerning antitrust issues and financial practices. This has led to significant changes in the company's operations and strategy.

Jack Ma's journey from a humble background to becoming one of the most influential business leaders in the world is a testament to his vision, resilience, and entrepreneurial spirit. His story continues to inspire many aspiring entrepreneurs globally.
  ”“”

**Setup (please complete the following information if applicable):**
 - IDE: [e.g. IntelliJ]
 - Library/Libraries: [e.g. com.azure:azure-core:1.49.1 (groupId:artifactId:version)]
 
 **Information Checklist**
 Kindly make sure that you have added all the following information above and checkoff the required fields otherwise we will treat the issuer as an incomplete report
- [ ] Query Added
- [ ] Setup information Added

**Comment by joshfree** [comment]
@mssfang could you please assist @StrugglingPig with this question?

**Comment by mssfang** [comment]
Yeah. this is a recently reported bug. There is a WIP PR to fix it. https://github.com/Azure/azure-sdk-for-java/pull/40687
