### ISSUE TITLE
[BUG] AcquireTokenSilentSupplier failed: Token not found in the cache

### ISSUE THREAD

**Issue by krysiuda** [Azure/azure-sdk-for-java#40654]
**Describe the bug**
Between msal4j versions 1.14.0 and 1.15.0 logging for AuthenticationErrorCode.CACHE_MISS has changed. I believe the change was accidental, resulting in additional (and potentially misleading) WARN messages being log.

***Exception or Stack Trace***
Our production system is logging "Execution of class com.microsoft.aad.msal4j.AcquireTokenSilentSupplier failed: Token not found in the cache" on "com.microsoft.aad.msal4j.ConfidentialClientApplication" logger (severity: WARN) every hour.

**Expected behavior**
Since cache miss simply triggers retrieval of a new token, I would expect this event (cache miss) to be logged with low severity. Preferably DEBUG level.

**Setup (please complete the following information):**
 - OS: linux
 - IDE: IntelliJ
 - Library/Libraries: msal4j-1.15.0-sources.jar
 - Java version: openjdk-21
 - App Server/Environment: N/A
 - Frameworks: N/A 

**Additional context**
in msal4j-1.14.0 AuthenticationResultSupplier there was:
```
            if (exception.errorCode() != null && exception.errorCode().equalsIgnoreCase(AuthenticationErrorCode.CACHE_MISS)) {
                clientApplication.log.debug(logMessage, ex);
                return;
            }
            ...
            clientApplication.log.error(logMessage, ex);
```
logging CACHE_MISS on DEBUG level instead of ERROR.

in msal4j-1.15.0, there is only:
```
                clientApplication.log.warn(
                        LogHelper.createMessage(
                                String.format("Execution of %s failed: %s", this.getClass(), ex.getMessage()),
                                msalRequest.headers().getHeaderCorrelationIdValue()));
```
logging cache misses always on WARN level.

**Comment by joshfree** [comment]
Hi @krysiuda, msal4j development and issue tracking happens in a separate git repo, here: https://github.com/AzureAD/microsoft-authentication-library-for-java.

I'll copy the issue over on your behalf and resolve this issue here as closed.

**Comment by joshfree** [comment]
Closing issue.  New issue created here: https://github.com/AzureAD/microsoft-authentication-library-for-java/issues/833
