### ISSUE TITLE
Azure.Identity logging level should control the underlying log level of MSAL

### ISSUE THREAD

**Issue by christothes** [Azure/azure-sdk-for-java#40664]
Please validate whether this is an issue for this language.

See https://github.com/Azure/azure-sdk-for-net/issues/44613 for .NET details

**Comment by billwert** [comment]
The structure of logging we and MSAL use (slf4j) isn't compatible with us modifying their logging configuration at runtime like this. Users will have to configure both Azure SDK logging and MSAL logging separately.
