### ISSUE TITLE
[QUERY] Do we need to show "AZURE_COSMOS_DISABLE_NON_STREAMING_ORDER_BY" in the logs

### ISSUE THREAD

**Issue by yanfang-ma** [Azure/azure-sdk-for-java#40709]
**Query/Question**

We can see below logs when using azure-cosmos 4.61.1
Jun 19, 2024 3:37:50 PM com.azure.cosmos.implementation.Configs getAzureCosmosNonStreamingOrderByDisabled
INFO: AZURE_COSMOS_DISABLE_NON_STREAMING_ORDER_BY property is: null
Jun 19, 2024 3:37:50 PM com.azure.cosmos.implementation.Configs getAzureCosmosNonStreamingOrderByDisabled
INFO: AZURE_COSMOS_DISABLE_NON_STREAMING_ORDER_BY env variable is: null

Do we need to show "AZURE_COSMOS_DISABLE_NON_STREAMING_ORDER_BY" in the logs?

***Why is this not a Bug or a feature Request?***
I'm not sure if "AZURE_COSMOS_DISABLE_NON_STREAMING_ORDER_BY" need to be shown in the logs. If not, we need to update the code to remove it. 
https://github.com/Azure/azure-sdk-for-java/blob/34800a496de78f0f384698f031a17f7e0b2e35de/sdk/cosmos/azure-cosmos/src/main/java/com/azure/cosmos/implementation/Configs.java#L511

**Setup (please complete the following information if applicable):**
 - OS: Windows
 - IDE: Any
 - Library/Libraries: azure-cosmos:4.61.1
 
 **Information Checklist**
 Kindly make sure that you have added all the following information above and checkoff the required fields otherwise we will treat the issuer as an incomplete report
- [ ] Query Added
- [ ] Setup information Added

**Comment by alexfandos** [comment]
We are experiencing the same issue. It floods our logs. Does this also happen in 4.61.0? We will downgrade till this is fixed.

**Comment by FabianMeiswinkel** [comment]
This has been fixed in 4.62.0 - released on 2024-07-02.
