### ISSUE TITLE
Migration directions from old azure-storage

### ISSUE THREAD

**Issue by josebarroszeiss** [Azure/azure-sdk-for-java#40713]
**Query/Question**
How to migrate from the old com.microsoft.azure:azure-storage

***Why is this not a Bug or a feature Request?***
My project use the old library, but when we upgraded to the new library many classes aren't to be found example:

import com.microsoft.azure.storage.table.TableServiceEntity;
import com.microsoft.azure.storage.AccessCondition;
import com.microsoft.azure.storage.StorageException;
import com.microsoft.azure.storage.blob.CloudBlobContainer;
import com.microsoft.azure.storage.blob.CloudBlockBlob;
import com.microsoft.azure.storage.table.CloudTable;
import com.microsoft.azure.storage.table.TableOperation;
import com.microsoft.azure.storage.table.TableResult;
import com.microsoft.azure.storage.StorageException;
import com.microsoft.azure.storage.blob.CloudBlobContainer;
import com.microsoft.azure.storage.table.CloudTable;
import com.microsoft.azure.storage.CloudStorageAccount;
import com.microsoft.azure.storage.StorageException;
import com.microsoft.azure.storage.blob.CloudBlobClient;
import com.microsoft.azure.storage.blob.CloudBlobContainer;
import com.microsoft.azure.storage.table.CloudTableClient;
import com.microsoft.azure.storage.StorageException;
import com.microsoft.azure.storage.table.CloudTable;
import com.microsoft.azure.storage.table.TableOperation;

**Setup (please complete the following information if applicable):**
 - OS Win11
 - IDE:  IntelliJ
 - Library/Libraries: latest version com.azure:azure-storage-blob 12.26.1
 
 **Information Checklist**
 Kindly make sure that you have added all the following information above and checkoff the required fields otherwise we will treat the issuer as an incomplete report
- [ x ] Query Added
- [ x ] Setup information Added

We dont undrestand what to do, our project works well but due to several security vulnerabilities, we must update this old storage account library for the new one, unfortunately there's no way to do that without proper directions

**Comment by ibrahimrabab** [comment]
Hi @josebarroszeiss 
Which version are you trying to upgrade from? The following guides will be helpful to follow:
https://github.com/Azure/azure-sdk-for-java/blob/main/sdk/storage/azure-storage-blob/migrationGuides/V8_V12.md
https://github.com/Azure/azure-sdk-for-java/blob/main/sdk/storage/azure-storage-blob/migrationGuides/V10_V12.md
Let us know if this helps!
