### ISSUE TITLE
[BUG] ChatRequestUserMessage content is binaryData

### ISSUE THREAD

**Issue by BorangaziyevA** [Azure/azure-sdk-for-java#40730]
There is a bug where ChatRequestSystemMessage.content is a String, while ChatRequestUserMessage.content is binaryData. Due to this, OpenAI cannot decode text in UTF-8 when sending ChatRequestUserMessage with russian or kazakh languages.

**Response from OpenAi:**
I am sorry, but I cannot recognize your message. Please describe your question in Russian or Kazakh so that I can help you.

**To Reproduce**
Give non-English text in ChatRequestUserMessage to OpenAi

**Expected behavior**
I expected both ChatRequestSystemMessage and ChatRequestUserMessage contents to be interpreted as String, allowing OpenAI to correctly process text in Russian or Kazakh.

**Code Snippet:**
```
        chatMessages.add(new ChatRequestSystemMessage("You're an assistant who helps answer user questions. Decode the user's message. The user writes questions in Russian or Kazakh, answer in the language in which the user wrote. "));
        chatMessages.add(new ChatRequestUserMessage("Как у тебя дела?"));
```

**Setup:**
OS: macOS
IDE: IntelliJ
Library/Libraries: azure-ai-openai:1.0.0-beta.9
Java version: 17
App Server/Environment: Tomcat
Frameworks: Spring Boot 3.2.0

If you suspect a dependency version mismatch (e.g. you see `NoClassDefFoundError`, `NoSuchMethodError` or similar), please check out [Troubleshoot dependency version conflict article](https://aka.ms/azsdk/java/dependency/troubleshoot) first. If it doesn't provide solution for the problem, please provide:
- verbose dependency tree (`mvn dependency:tree -Dverbose`)
- exception message, full stack trace, and any available logs

**Information Checklist**
Kindly make sure that you have added all the following information above and checkoff the required fields otherwise we will treat the issuer as an incomplete report

- [x]  Bug Description Added
- [x]  Repro Steps Added
- [x]  Setup information Added

**Comment by mssfang** [comment]
@BorangaziyevA Can you upgrade the version to beta.10 and try out?
We have a fix for this issue.
