### ISSUE TITLE
[FEATURE REQ] add a LIVE test for oracledatabase

### ISSUE THREAD

**Issue by weidongxu-microsoft** [Azure/azure-sdk-for-java#40745]
Context: they'd GA this month

PS: have your test class `extends TestProxyTestBase` (not TestBase)

**Comment by weidongxu-microsoft** [comment]
Please have 2 PR.

1st with just a single resource, as usual.
2nd with improved hero scenario as e.g. https://github.com/Azure/azure-sdk-for-java/blob/main/sdk/datafactory/azure-resourcemanager-datafactory/src/test/java/com/azure/resourcemanager/datafactory/DataFactoryTests.java

**Comment by v-hongli1** [comment]
@weidongxu-microsoft 
The `Oracle Database@Azure` is a paid SaaS service and a required basic service for `OracleDatabase`. Therefore, it is not recommended to add any live test cases to `OracleDatabase`.
