### ISSUE TITLE
Factory method 'openAIClient' threw exception; nested exception is java.lang.NoClassDefFoundError: reactor/util/Loggers

### ISSUE THREAD

**Issue by ZuoyX** [Azure/azure-sdk-for-java#40778]
### Type of issue

Code doesn't work

### Description

When I init OpenAIClient with @Bean, it failed: Factory method 'openAIClient' threw exception; nested exception is java.lang.NoClassDefFoundError: reactor/util/Loggers
This is my code:
    @Bean
    public OpenAIClient openAIClient() {
        return new OpenAIClientBuilder()
                .endpoint(endpoint)
                .credential(new AzureKeyCredential(azureOpenaiKey))
                .buildClient();
    }

My spring boot version is 1.5.22.RELEASE. 

This is my dependency:
[INFO]    +- com.azure:azure-ai-openai:jar:1.0.0-beta.9:compile
[INFO]    |  +- com.azure:azure-core:jar:1.49.1:compile
[INFO]    |  |  +- com.azure:azure-json:jar:1.1.0:compile
[INFO]    |  |  +- com.azure:azure-xml:jar:1.0.0:compile
[INFO]    |  |  \- io.projectreactor:reactor-core:jar:2.0.8.RELEASE:compile
[INFO]    |  \- com.azure:azure-core-http-netty:jar:1.15.1:compile
[INFO]    |     +- io.netty:netty-handler-proxy:jar:4.1.110.Final:compile
[INFO]    |     |  \- io.netty:netty-codec-socks:jar:4.1.110.Final:compile
[INFO]    |     +- io.netty:netty-buffer:jar:4.1.110.Final:compile
[INFO]    |     +- io.netty:netty-codec:jar:4.1.110.Final:compile
[INFO]    |     +- io.netty:netty-codec-http2:jar:4.1.110.Final:compile
[INFO]    |     +- io.netty:netty-transport-native-unix-common:jar:4.1.110.Final:compile
[INFO]    |     +- io.netty:netty-transport-native-epoll:jar:linux-x86_64:4.1.110.Final:compile
[INFO]    |     |  \- io.netty:netty-transport-classes-epoll:jar:4.1.110.Final:compile
[INFO]    |     +- io.netty:netty-transport-native-kqueue:jar:osx-x86_64:4.1.110.Final:compile
[INFO]    |     |  \- io.netty:netty-transport-classes-kqueue:jar:4.1.110.Final:compile
[INFO]    |     +- io.netty:netty-tcnative-boringssl-static:jar:2.0.65.Final:compile
[INFO]    |     |  +- io.netty:netty-tcnative-classes:jar:2.0.65.Final:compile
[INFO]    |     |  +- io.netty:netty-tcnative-boringssl-static:jar:linux-x86_64:2.0.65.Final:compile
[INFO]    |     |  +- io.netty:netty-tcnative-boringssl-static:jar:linux-aarch_64:2.0.65.Final:compile
[INFO]    |     |  +- io.netty:netty-tcnative-boringssl-static:jar:osx-x86_64:2.0.65.Final:compile
[INFO]    |     |  +- io.netty:netty-tcnative-boringssl-static:jar:osx-aarch_64:2.0.65.Final:compile
[INFO]    |     |  \- io.netty:netty-tcnative-boringssl-static:jar:windows-x86_64:2.0.65.Final:compile
[INFO]    |     +- io.projectreactor.netty:reactor-netty-http:jar:1.0.45:compile
[INFO]    |     |  +- io.netty:netty-resolver-dns:jar:4.1.109.Final:compile
[INFO]    |     |  |  \- io.netty:netty-codec-dns:jar:4.1.109.Final:compile
[INFO]    |     |  +- io.netty:netty-resolver-dns-native-macos:jar:osx-x86_64:4.1.109.Final:compile
[INFO]    |     |  |  \- io.netty:netty-resolver-dns-classes-macos:jar:4.1.109.Final:compile
[INFO]    |     |  \- io.projectreactor.netty:reactor-netty-core:jar:1.0.45:compile
[INFO]    |     \- io.netty:netty-common:jar:4.1.110.Final:compile

[Enter feedback here]

### Page URL

https://learn.microsoft.com/en-us/java/api/com.azure.ai.openai?view=azure-java-preview

### Content source URL

https://github.com/Azure/azure-docs-sdk-java/blob/master/preview/docs-ref-autogen/com.azure.ai.openai.yml

### Document Version Independent Id

adaa0a35-de15-5fff-e7b4-45f05d63d389

### Article author

@rloutlaw

### Metadata

* ID: e37863fa-8e51-d3b6-2f96-1cf6115dfcea

**Comment by alzimmermsft** [comment]
Hi @ZuoyX, this is a dependency issue in your application. The Azure SDKs for Java only support `reactor-core` versions 3.4.0+ and based on your dependency tree it is being resolved to `2.0.8.RELEASE` (which looks to be getting resolved by the version of Spring you're using). Getting the application to resolve to a version of `reactor-core` 3.4.0+ will resolve this issue.
