### ISSUE TITLE
[BUG] The response `The requested URI does not represent any resource on the server.` is not helpful when the blob name is `null`

### ISSUE THREAD

**Issue by prabinpaudel-mfc** [Azure/azure-sdk-for-java#40926]
**Describe the bug**
The response `The requested URI does not represent any resource on the server.` is not helpful when the blob name is `null`

***Exception or Stack Trace***
Servlet.service() for servlet [dispatcherServlet] in context with path [] threw exception [Request processing failed: com.azure.storage.blob.models.BlobStorageException: Status code 400, "﻿<?xml version="1.0" encoding="utf-8"?><Error><Code>InvalidUri</Code><Message>The requested URI does not represent any resource on the server.

**To Reproduce**
Pass the blob name as null
 BlobClient blobClient = blobContainerClient.getBlobClient(null);

***Code Snippet***
 BlobClient blobClient = blobContainerClient.getBlobClient(null);

**Expected behavior**
The blob name is null

**Screenshots**

**Setup (please complete the following information):**
 - IDE: [e.g. IntelliJ]
 - Library/Libraries: [e.g. com.azure:azure-core:1.16.0 (groupId:artifactId:version)]
 - Java version: [e.g. 8] 
 - App Server/Environment: [e.g. Tomcat, WildFly, Azure Function, Apache Spark, Databricks, IDE plugin or anything special]
 - Frameworks: [e.g. Spring Boot, Micronaut, Quarkus, etc] 

If you suspect a dependency version mismatch (e.g. you see `NoClassDefFoundError`, `NoSuchMethodError` or similar), please check out [Troubleshoot dependency version conflict article](https://aka.ms/azsdk/java/dependency/troubleshoot) first. If it doesn't provide solution for the problem, please provide:
- verbose dependency tree (`mvn dependency:tree -Dverbose`)
- exception message, full stack trace, and any available logs

**Additional context**

**Information Checklist**
Kindly make sure that you have added all the following information above and checkoff the required fields otherwise we will treat the issuer as an incomplete report
- [ ] Bug Description Added
- [ ] Repro Steps Added
- [ ] Setup information Added

**Comment by joshfree** [comment]
Thanks for the feedback, @prabinpaudel-mfc  - someone from the `Storage` team will follow up
