### ISSUE TITLE
[FEATURE REQ] Cosmos DB - Allow configuring end-to-end operation timeout via configuration property (gateway mode)

### ISSUE THREAD

**Issue by simplyanything** [Azure/azure-sdk-for-java#40937]
**Is your feature request related to a problem? Please describe.**
Cosmos DB currently allows you to configure the end-to-end operation timeout (for standard gateway) by [customising the cosmos client](https://github.com/Azure/azure-sdk-for-java/blob/main/sdk/spring/azure-spring-data-cosmos/README.md#customizing-configuration) ([using this configuration specifically](https://azuresdkdocs.blob.core.windows.net/$web/java/azure-cosmos/latest/com/azure/cosmos/CosmosClientBuilder.html#endToEndOperationLatencyPolicyConfig(com.azure.cosmos.CosmosEndToEndOperationLatencyPolicyConfig))).
This is a bit verbose for users who don't need to customise the configuration heavily and only need to configure the end-to-end timeout.

**Describe the solution you'd like**
[This](https://learn.microsoft.com/en-us/azure/developer/java/spring-framework/configuration-properties-azure-cosmos-db) list provides some properties, but lacks the (in my opinion) important end-to-end timeout configuration.
It would be nice to configure the end-to-end timeout (for standard gateway mode) through application properties. E.g., provide `spring.cloud.azure.cosmos.endToEndOperationTimeout` which can override the default setting.  

Thank you for the consideration.

**Describe alternatives you've considered**
Customising the Cosmos Client.

**Information Checklist**
Kindly make sure that you have added all the following information above and checkoff the required fields otherwise we will treat the issuer as an incomplete report
- [X] Description Added
- [X] Expected solution specified

**Comment by kushagraThapar** [comment]
@moarychan - we can achieve this by supporting the end-to-end timeout functionality in azure spring cosmos starters. When are we planning to onboard this new feature to our azure spring cosmos starters?

**Comment by kushagraThapar** [comment]
@saragluna can you please take a look at this, this should be achievable with the latest version of spring data cosmos or Java SDK directly

**Comment by saragluna** [comment]
Hi @simplyanything, if you are using the `spring-cloud-azure-starter-data-cosmos`, you can configure via providing a customizer:

```java
@Configuration
public class CosmosConfiguration {

    @Bean
    public AzureServiceClientBuilderCustomizer<CosmosClientBuilder> cosmosClientCustomizer() {
        return builder -> {
            GatewayConnectionConfig gatewayConnectionConfig = new GatewayConnectionConfig();
            gatewayConnectionConfig.setIdleConnectionTimeout(Duration.ofMinutes(5));
            builder.gatewayMode(gatewayConnectionConfig);
        };
    }
    
}
```

Let me know whether this could work, and we could expose the properties later.

**Comment by simplyanything** [comment]
Hi @saragluna, thanks for your comment!

Please correct me if I'm wrong, `getIdleConnectionTimeout` only involves connections and not individual requests? In other words, if I see have an upsert request to Cosmos that takes longer than 10 seconds, I want to kill it earlier (5 seconds), but this configuration would not allow me to do so.
I thought that 

`gatewayConnectionConfig.setNetworkRequestsTimeout(Duration networkRequestTimeout)`

would have been an option, but I see that we can't set it below the `MIN_NETWORK_REQUEST_TIMEOUT` which is currently 60 seconds:

https://github.com/Azure/azure-sdk-for-java/blob/2b40a533a7fe0c8ee7a912f64e046de14b939d4e/sdk/cosmos/azure-cosmos/src/main/java/com/azure/cosmos/GatewayConnectionConfig.java#L65 

Also, when we use this builder,  should we have to configure TTL, max request units, and the consistency level again in order to not use the defaults? An end-to-end timeout application property would really be convenient. 

Thanks.

**Comment by kushagraThapar** [comment]
@simplyanything - you need to use the end-to-end timeout policy as defined here - https://github.com/Azure/azure-sdk-for-java/blob/main/sdk/cosmos/azure-cosmos/src/main/java/com/azure/cosmos/CosmosClientBuilder.java#L889
You can use it the way @saragluna explained above.

**Comment by kushagraThapar** [comment]
@simplyanything that's correct, you only need to set the changes that are different than the default values. Regarding end-to-end timeout, you only need to set that value and don't have to change any of the direct or gateway connection configs.
Let me know if you have any more questions.
