### ISSUE TITLE
[QUERY]: How to use ROPC flow with this sdk

### ISSUE THREAD

**Issue by vishal-bihani** [Azure/azure-sdk-for-java#40939]
**Query/Question**
I want to use [ROPC flow](https://learn.microsoft.com/en-us/entra/identity-platform/v2-oauth-ropc) in our application. I don't seem to find any Credentials class for this purpose.

**Setup (please complete the following information if applicable):**
 - Library: com.azure:azure-identity:1.13.0
 
 **Information Checklist**
 Kindly make sure that you have added all the following information above and checkoff the required fields otherwise we will treat the issuer as an incomplete report
- [x] Query Added
- [x] Setup information Added

**Comment by joshfree** [comment]
Hi @vishal-bihani Microsoft recommends you do not use the ROPC flow. In most scenarios, more secure alternatives are available and recommended. This flow requires a very high degree of trust in the application, and carries risks that are not present in other flows. You should only use this flow when other more secure flows aren't viable.

With that said, if you must use ROPC flow then you'll need to use the lower level MSAL4j library in place of azure-identity - https://github.com/AzureAD/microsoft-authentication-library-for-java
