### ISSUE TITLE
[FEATURE REQ] Support latest non-preview version (2024-02-01)

### ISSUE THREAD

**Issue by dji** [Azure/azure-sdk-for-java#40954]
**Is your feature request related to a problem? Please describe.**
Preview API Versions are [only supported for a few months, starting July 1 2024](https://learn.microsoft.com/en-us/azure/ai-services/openai/api-version-deprecation).
 
However, this library does not appear to support the latest non-preview version, `2024-02-01`.

**Describe the solution you'd like**
Support for all GA versions going forwards, right now specifically `2024-02-01`

**Describe alternatives you've considered**
I don't have available dev time to update to new preview versions every 3 months. I don't need bleeding edge features but I do minimally need function/tool calling (available from `2023-07-01-preview`, which is being sunsetted).  One non-ideal alternative would be to use version `2023-10-01-preview` but this is also not supported by this library, and it is unclear how long Azure intends to keep it alive.

**Additional context**
Hopefully I'm just missing something and this support does exist already!

**Information Checklist**
Kindly make sure that you have added all the following information above and checkoff the required fields otherwise we will treat the issuer as an incomplete report
- [x] Description Added
- [x] Expected solution specified

**Comment by joshfree** [comment]
@mssfang PTAL

**Comment by mssfang** [comment]
Hi, @dji 

Regarding to the missing GA version, 2024-02-01, yes, we do miss to add this version in our TypeSpec definition. And I opened the PR to address it. https://github.com/Azure/azure-rest-api-specs/pull/29424

You can use the latest preview version of our SDK to have function/tool calling feature.
[Sample: Stream tool calling](https://github.com/Azure/azure-sdk-for-java/blob/main/sdk/openai/azure-ai-openai/src/samples/java/com/azure/ai/openai/StreamingToolCall.java)

[Sample: function calling](https://github.com/Azure/azure-sdk-for-java/blob/main/sdk/openai/azure-ai-openai/src/samples/java/com/azure/ai/openai/ChatCompletionsFunctionCall.java)

**Comment by dji** [comment]
@mssfang Thanks, I will start the build using the latest preview version but good to know the GA version will be supported shortly.  Do you have a ballpark idea when that change would ship? (Don't need an exact date, just wanted to know if I should expect days, weeks, or months)

**Comment by mssfang** [comment]
> @mssfang Thanks, I will start the build using the latest preview version but good to know the GA version will be supported shortly. Do you have a ballpark idea when that change would ship? (Don't need an exact date, just wanted to know if I should expect days, weeks, or months)

It could go out late of July or earlier of August.

BTW, we have a newer stable Service API version just available recently, which is 2024-06-01.

**Comment by dji** [comment]
@mssfang Any news on the next release?

**Comment by mssfang** [comment]
@dji Yeah. We are close to completing the service API version 2024-07-01-preview. In the next SDK release, we will include the new service API versions: `2024-02-01`, `2024-06-01`, and `2024-07-01-preview`.

**Comment by mssfang** [comment]
@dji 
a new `azure-ai-openai` SDK version [1.0.0-beta.11](https://repo1.maven.org/maven2/com/azure/azure-ai-openai/1.0.0-beta.11/) is released now. It includes [2024-02-01, 2024-06-01, and 2024-07-01-preview](https://github.com/Azure/azure-sdk-for-java/blob/main/sdk/openai/azure-ai-openai/src/main/java/com/azure/ai/openai/OpenAIServiceVersion.java#L36-L66).
