### ISSUE TITLE
[BUG]  The POM for com.microsoft.azure:azure-storage-blob:jar:11.0.1 is invalid (missing versions in parent POM)

### ISSUE THREAD

**Issue by adnklauser** [Azure/azure-sdk-for-java#4097]
**Describe the bug**
The POM for `azure-storage-blob` and its parent POM, ( [azure-client-sdk-parent:1.0.0](https://search.maven.org/artifact/com.azure/azure-client-sdk-parent/1.0.0/pom) ) together do not define all version numbers. As a result, Maven cannot download transitive dependencies, like `com.microsoft.rest.v2:client-runtime:jar`

***Exception or Stack Trace***
```
[WARNING] The POM for com.microsoft.azure:azure-storage-blob:jar:11.0.1 is invalid, transitive dependencies (if any) will not be available: 4 problems were encountered while building the effective model for com.microsoft.azure:azure-storage-blob:11.0.1
[ERROR] 'dependencies.dependency.version' for com.microsoft.rest.v2:client-runtime:jar is missing. @
[ERROR] 'dependencies.dependency.version' for org.spockframework:spock-core:jar is missing. @
[ERROR] 'dependencies.dependency.version' for cglib:cglib-nodep:jar is missing. @
[ERROR] 'dependencies.dependency.version' for uk.org.lidalia:slf4j-test:jar is missing. @
```

**To Reproduce**
Reference `azure-storage-blob` in a Maven project pom.xml
```
<dependency>
  <groupId>com.microsoft.azure</groupId>
  <artifactId>azure-storage-blob</artifactId>
  <version>11.0.1</version>
</dependency>
```
Run `mvn install -X`

***Code Snippet***
Pass `-X` to maven to see the detailed error message that generates the output above.
```
mvn install -X
```

**Expected behavior**
Maven can successfully resolve all transitive dependencies of `azure-storage-blob`. Versions should either be specified in the `azure-storage-blob` POM or in one of its parent POMs.

**Setup (please complete the following information):**
 - OS: Windows 10.0.17134 
 - Maven: 3.5.2
 - Java: 1.8.0_201

**Information Checklist**
- [x] Bug Description Added
- [x] Repro Steps Added
- [x] Setup information Added

**Comment by loarabia** [comment]
Thanks for reporting this. We'll look into the packages.

CC:  @jianghaolu, @JonathanGiles

**Comment by joshfree** [comment]
@jianghaolu PTAL for Preview 2?

@adnklauser thanks for reporting this issue with the POM

**Comment by rickle-msft** [comment]
@adnklauser. Thank you for posting this. We are aware of this bug, and it is the result of forgetting to ship an updated version of the parent pom as you mention. 

As it stands, we are not planning to release a new version of v11, and we recommend pinning the transitive dependencies in your pom directly for using this version. Long term, we recommend you either stick with v8 or anticipate the GA release of v12 which will address a lot of the problems found in v11. If you have further questions or concerns about that, we are happy to work with you on it.

**Comment by rickle-msft** [comment]
For the record, v12 will be in a different package (com.azure instead of com.microsoft.azure), so you should never hit this problem when loading v8 and v12 together.

**Comment by joshfree** [comment]
Closing issue based on @rickle-msft 's response above.  @adnklauser feel free to reactivate the issue if this did not fully resolve your concern or we misunderstood the issue.  Thanks

**Comment by mgingios** [comment]
Hello,  We are affected, too.  I cannot find any tentative release date for v12 of the SDK.  Any ideas? It will help with our planning...

**Comment by rickle-msft** [comment]
Hi, @mgingios. We have released the [preview of v12](https://search.maven.org/artifact/com.azure/azure-storage-blob/12.0.0-preview.1/jar) if that's what you're looking for. If you're asking about a GA date, we don't have a tentative date just yet, but we should have at least one more preview out by mid August. Are there certain features that you need to be stable before you start your development? That may help us prioritize our work.

**Comment by mgingios** [comment]
Hi @rickle-msft, Actually, this issue is the only bump in our progress...  Our release date is in September, so we will probably need to try the pre-12 releases.  Thank you for the information, Rick.

**Comment by sijucm** [comment]
Is the groupId com.microsoft.azure or com.azure. It is amazing the ability to create confusion.
