### ISSUE TITLE
[FEATURE REQ] OneDeploy for Flex consumption SKU

### ISSUE THREAD

**Issue by weidongxu-microsoft** [Azure/azure-sdk-for-java#40987]
To support function app deployment on new Flex consumption SKU, there needs to be an update to existing OneDeploy in Java SDK. 

1.	Detect if the app is on flex consumption. If cannot detect, then may be add a parameter where user can specify SKU.
2.	If Flex consumption, then 
  a.	Pass 2 API parameters: RemoteBuild = false and deployer = JavaSDK. API example:
`/api/publish?RemoteBuild=false&deployer=JavaSDK`
  b.	Skip any other parameters and logic performed for existing SKUs
3.	If not flex consumption, then continue with existing logic.

**Comment by XiaofeiCao** [comment]
Azure CLI implementation from @Flanker32 :
https://github.com/Azure/azure-cli/blob/dev/src/azure-cli/azure/cli/command_modules/appservice/custom.py#L720

**Comment by weidongxu-microsoft** [comment]
Thanks Xiaofei. Appears they really don't need the `type` query param.
