### ISSUE TITLE
[BUG] flooding with "POST /v2.1/track" dependencies

### ISSUE THREAD

**Issue by hungchu0912** [Azure/azure-sdk-for-java#41040]
**Setup**
 - Library/Libraries: azure-monitor-opentelemetry-exporter-1.0.0-beta.21
 - Java version: 21
 - App Server/Environment: Netty
 - Frameworks: Quarkus

Recently we are trying to start our new services with Quarkus native stack, everything is good so far but when comes to Application Insights integration, we do not use agent and using sdk instead, and in our dependencies tables we notice there are tons of "POST /v2.1/track" records - this does not happens when we using Application Insight agent with other stack (Springboot, helidon,...). This dramatically increasing the size and cost of our AI services

![image](https://github.com/Azure/azure-sdk-for-java/assets/40167578/84eccf69-7a56-45ae-8e6d-f452c23ffdd7)

**Additional context**
Dependencies that are using in our pom.xml

         <dependency>
             <groupId>io.quarkiverse.opentelemetry.exporter</groupId>
             <artifactId>quarkus-opentelemetry-exporter-azure</artifactId>
             <version>3.8.3.0</version>
         </dependency>
         <dependency>
             <groupId>io.opentelemetry</groupId>
             <artifactId>opentelemetry-api</artifactId>
             <version>1.39.0</version>
         </dependency>

**Comment by joshfree** [comment]
@lmolkova @trask could you please follow up?

**Comment by lmolkova** [comment]
Thanks for reporting this @hungchu0912 ! 

I think it belongs in https://github.com/quarkiverse/quarkus-opentelemetry-exporter, @jeanbisutti could you please confirm and take a look? 

Thanks!

**Comment by hungchu0912** [comment]
For more information, a single service running inside aks cluster with several pods resulting ~70k dependencies for this, from debugging we saw that this is from [Statsbeat ](https://learn.microsoft.com/en-us/azure/azure-monitor/app/statsbeat?tabs=eu-java%2Cjava), unluckily we cannot find any work-around solution so we have to turn off Application Insights instance for cost saving and waiting for the fix before enable it again

**Comment by jeanbisutti** [comment]
@hungchu0912  Thank you for reporting the issue, and sorry for the inconvenience. I have reproduced the problem, and a fix is in progress. I will keep you updated.

**Comment by jeanbisutti** [comment]
@hungchu0912 A new version of `quarkus-opentelemetry-exporter-azure` has just been released. It contains a fix about this issue. Could you please bump `quarkus-opentelemetry-exporter-azure` to 3.8.3.1 and check that everything is working fine?

**Comment by hungchu0912** [comment]
Thanks @jeanbisutti for your support, we applied the fix and now the issue is gone
