### ISSUE TITLE
[BUG] azure-ai-openai - BinaryData.toObject doesn't convert tools in 1.0.0-beta.10

### ISSUE THREAD

**Issue by junan-trustarc** [Azure/azure-sdk-for-java#41058]
**Describe the bug**
Tools are not converted properly when binaryData.toObject(ChatCompletions.class) is executed.

**To Reproduce**
execute below code snippet on unit test

***Code Snippet***
```
    @Test
    void testToObject() {
        BinaryData binaryData = BinaryData.fromString("""
            {"id":"chatcmpl-9iwfyNA6EWXX6onktvGTmPbdbzxe4","choices":[{"message":{"role":"assistant","toolCalls":[{"id":"call_62JuwiMnVsS1QyYubIfskKhB","type":"function","function":{"name":"SearchBrowser","arguments":"{\\"queries\\":[\\"Tesla stock price\\"]}"}}]},"index":0,"finishReason":"tool_calls"}],"usage":{"completionTokens":17,"promptTokens":124,"totalTokens":141},"createdAt":"2024-07-09T04:23:30Z","systemFingerprint":"fp_ce0793330f","model":"gpt-4o-2024-05-13"}
            """);

        ChatCompletions chatCompletions = binaryData.toObject(ChatCompletions.class);

        assertNotNull(chatCompletions.getChoices().get(0).getMessage().getToolCalls());
    }
```

**Expected behavior**
tools should be bonded properly when binaryData.toObject(ChatCompletions.class); is happened.

**Screenshots**
![image](https://github.com/Azure/azure-sdk-for-java/assets/134445960/e1f85f56-614f-4b47-a8c9-5e814af95408)

**Setup (please complete the following information):**
 - OS: Window 11
 - IDE: IntelliJ
 - Library/Libraries: com.azure:azure-core:1.49.1 and 1.0.0-beta.10
 - Java version: Java 21
 - App Server/Environment: IDE
 - Frameworks: Spring Boot

**Information Checklist**
Kindly make sure that you have added all the following information above and checkoff the required fields otherwise we will treat the issuer as an incomplete report
- [o] Bug Description Added
- [o] Repro Steps Added
- [o] Setup information Added

**Comment by mssfang** [comment]
Hi @junan-trustarc 

You should use "tool_calls" instead of "toolCalls" from the String provided.

```java

BinaryData binaryData = BinaryData.fromString("""
    {"id":"chatcmpl-9iwfyNA6EWXX6onktvGTmPbdbzxe4","choices":[{"message":{"role":"assistant","tool_calls":[{"id":"call_62JuwiMnVsS1QyYubIfskKhB","type":"function","function":{"name":"SearchBrowser","arguments":"{\\"queries\\":[\\"Tesla stock price\\"]}"}}]},"index":0,"finishReason":"tool_calls"}],"usage":{"completionTokens":17,"promptTokens":124,"totalTokens":141},"createdAt":"2024-07-09T04:23:30Z","systemFingerprint":"fp_ce0793330f","model":"gpt-4o-2024-05-13"}
    """);

```

**Comment by junan-trustarc** [comment]
> Hi @junan-trustarc
> 
> You should use "tool_calls" instead of "toolCalls" from the String provided.
> 
> ```java
> BinaryData binaryData = BinaryData.fromString("""
>     {"id":"chatcmpl-9iwfyNA6EWXX6onktvGTmPbdbzxe4","choices":[{"message":{"role":"assistant","tool_calls":[{"id":"call_62JuwiMnVsS1QyYubIfskKhB","type":"function","function":{"name":"SearchBrowser","arguments":"{\\"queries\\":[\\"Tesla stock price\\"]}"}}]},"index":0,"finishReason":"tool_calls"}],"usage":{"completionTokens":17,"promptTokens":124,"totalTokens":141},"createdAt":"2024-07-09T04:23:30Z","systemFingerprint":"fp_ce0793330f","model":"gpt-4o-2024-05-13"}
>     """);
> ```

Hi @mssfang  thanks for the reply.
I found original issue.
When ChatCompletions converted to Json(like return ChatCompletions on endpoint)

It uses snake case "tool_calls" from 1.0.0-beta.8
however it returns "toolCalls" from 1.0.0-beta.10

Could you check? other properties also should return as snake case as well.

from 1.0.0-beta.8
```{
  "id": "chatcmpl-9jaa8sBFo3OvHk8zYFgnv1eP4HM0I",
  "created": "2024-07-10T23:00:08Z",
  "choices": [
    {
      "index": 0,
      "finish_reason": "tool_calls",
      "message": {
        "role": "assistant",
        "tool_calls": [
          {
            "id": "call_yTnnrknJXXh289fAU9mqhiTj",
            "function": {
              "name": "get_current_weather",
              "arguments": "{\"location\":\"New York, NY\"}"
            },
            "type": "function"
          }
        ]
      }
    }
  ],
  "usage": {
    "completion_tokens": 18,
    "prompt_tokens": 86,
    "total_tokens": 104
  },
  "system_fingerprint": "fp_dd932ca5d1"
}
```

from 1.0.0-beta.10
```
{
  "id": "chatcmpl-9jaYBykyLL8iK7bIce8efpq13BUNy",
  "choices": [
    {
      "message": {
        "role": "assistant",
        "toolCalls": [
          {
            "id": "call_dnGT89wf3TPkhIFoqLE0vgff",
            "type": "function",
            "function": {
              "name": "get_current_weather",
              "arguments": "{\"location\":\"New York, NY\"}"
            }
          }
        ]
      },
      "index": 0,
      "finishReason": "tool_calls"
    }
  ],
  "usage": {
    "completionTokens": 18,
    "promptTokens": 86,
    "totalTokens": 104
  },
  "createdAt": "2024-07-10T22:58:07Z",
  "systemFingerprint": "fp_d33f7b429e",
  "model": "gpt-4o-2024-05-13"
}
```

**Comment by mssfang** [comment]
@junan-trustarc 
I have checked and it works fine from my side. It is still response `tool_call`.  I use [GetChatCompletionsToolCallSample](https://github.com/Azure/azure-sdk-for-java/blob/main/sdk/openai/azure-ai-openai/src/samples/java/com/azure/ai/openai/usage/GetChatCompletionsToolCallSample.java) to verify it.


I also tested with different model, gpt-3 and gpt-4o. Both responses are expected.

**Comment by junan-trustarc** [comment]
@mssfang 

I am talking about when ChatCompletions serialized on endpoint.
example,

```
@PostMapping(value = "/chat/completions-test")
    public ChatCompletions getChatCompletionsTest() {
        OpenAIClient client = new OpenAIClientBuilder()
            .credential(new AzureKeyCredential("{key}"))
            .buildClient();
        List<ChatRequestMessage> chatMessages = Arrays.asList(
            new ChatRequestSystemMessage("You are a helpful assistant."),
            new ChatRequestUserMessage("What sort of clothing should I wear today in Berlin?")
        );
        ChatCompletionsToolDefinition toolDefinition = new ChatCompletionsFunctionToolDefinition(
            getFutureTemperatureFunctionDefinition()); // get from your sample code

        ChatCompletionsOptions chatCompletionsOptions = new ChatCompletionsOptions(chatMessages);
        chatCompletionsOptions.setTools(Arrays.asList(toolDefinition));

        return client.getChatCompletions("gpt-4o", chatCompletionsOptions);
    }
```
 
It returns camel case on beta-10, previously snake case on beta-8, that is why doesn't work any more.
reason being I am creating wrapper endpoint and using our sdk to connect with this wrapper endpoint. so response should be same as what original returns which previous version was fine.

```
{
  "id": "chatcmpl-9jbJOKBxmy3x5zsYq275uyH5MhgcX",
  "choices": [
    {
      "message": {
        "role": "assistant",
        "toolCalls": [
          {
            "id": "call_yVFnX1vqnGNoviBtF8uKjq9U",
            "type": "function",
            "function": {
              "name": "FutureTemperature",
              "arguments": "{\"location_name\":\"Berlin\",\"date\":\"2023-10-05\"}"
            }
          }
        ]
      },
      "index": 0,
      "finishReason": "tool_calls"
    }
  ],
  "usage": {
    "completionTokens": 24,
    "promptTokens": 117,
    "totalTokens": 141
  },
  "createdAt": "2024-07-10T23:46:54Z",
  "systemFingerprint": "fp_dd932ca5d1",
  "model": "gpt-4o-2024-05-13"
}
```

**Comment by mssfang** [comment]
@junan-trustarc I tried to create a new spring boot application with POST method. And I still getting the correct response.
![image](https://github.com/user-attachments/assets/d13cbab7-16b3-4ce4-be9f-44b80fac8f65)
![image](https://github.com/user-attachments/assets/6a43f3b0-1a23-4846-9cf0-890c4177dbc8)

```
    @PostMapping("/testPost")
    public String postMethod() {
        System.out.println("Testing post mapping");
        ChatCompletions res = getChatCompletion();
        String string = BinaryData.fromObject(res).toString();
        System.out.println(string);
        return string;
    }
```

```
    public ChatCompletions getChatCompletion() {
        String azureOpenaiKey = Configuration.getGlobalConfiguration().get("AZURE_OPENAI_KEY");
        String endpoint = Configuration.getGlobalConfiguration().get("AZURE_OPENAI_ENDPOINT");

        OpenAIClient client = new OpenAIClientBuilder()
                .endpoint(endpoint)
                .credential(new AzureKeyCredential(azureOpenaiKey))
                .buildClient();
        List<ChatRequestMessage> chatMessages = Arrays.asList(
                new ChatRequestSystemMessage("You are a helpful assistant."),
                new ChatRequestUserMessage("What sort of clothing should I wear today in Berlin?")
        );
        ChatCompletionsToolDefinition toolDefinition = new ChatCompletionsFunctionToolDefinition(
                getFutureTemperatureFunctionDefinition()); // get from your sample code

        ChatCompletionsOptions chatCompletionsOptions = new ChatCompletionsOptions(chatMessages);
        chatCompletionsOptions.setTools(Arrays.asList(toolDefinition));

        ChatCompletions chatCompletions = client.getChatCompletions("gpt-4o", chatCompletionsOptions);

        System.out.println("Chat Completions tool call size: " + chatCompletions.getChoices().get(0).getMessage().getToolCalls().size());

        return chatCompletions;
    }
```

**Comment by junan-trustarc** [comment]
Hi @mssfang 

try to return "ChatCompletions" instead of String

```
 @PostMapping("/testPost")
    public ChatCompletions postMethod() {
        System.out.println("Testing post mapping");
        return getChatCompletion();
    }
```

**Comment by mssfang** [comment]
@junan-trustarc 
I am still getting the correct value. 

PS C:\work\azure-sdk-for-java> curl -X POST  http://localhost:8080/testPost     
{"id":"chatcmpl-9kEHeSGPlUGuPiPVZbQpDTVNRPiIB","choices":[{"message":{"role":"assistant","content":null,"toolCalls":[{"id":"call_OULl8XUIFnfHUiq7Z1ka31z9","type":"function","function":{"name":"FutureTemperature","arguments":"{\"location_name\":\"Berlin\"}"}}],"functionCall":null,"context":null},"index":0,"finishReason":"**_tool_calls_**","delta":null,"contentFilterResults":{"sexual":null,"violence":null,"hate":null,"selfHarm":null,"profanity":null,"customBlocklists":null,"error":null,"protectedMaterialText":null,"protectedMaterialCode":null},"finishDetails":null,"enhancements":null,"logprobs":null}],"usage":{"completionTokens":15,"promptTokens":117,"totalTokens":132},"createdAt":"2024-07-12T17:23:42Z","promptFilterResults":[{"promptIndex":0,"contentFilterResults":{"sexual":{"severity":"safe","filtered":false},"violence":{"severity":"safe","filtered":false},"hate":{"severity":"safe","filtered":false},"selfHarm":{"severity":"safe","filtered":false},"profanity":null,"customBlocklists":null,"error":null,"jailbreak":null,"indirectAttack":null}}],"systemFingerprint":"fp_abc28019ad","model":"gpt-4o-2024-05-13"}

**Comment by mssfang** [comment]
@junan-trustarc 

it is because we replaced `jackson-databind` dependency by `azure-json` for using stream style serialization since beta.9.

The SDK still response with correct value as `tool_calls`. One more evidence that I can find is from fiddle request.
![image](https://github.com/user-attachments/assets/a453400f-9040-40e5-a063-8b138660de65)

You can either call toJson()/fromJson() for your own serialization/de-serializaton.

Or using  `BinaryData.fromObject(chatCompletion).toString()` to get the JSON value or         `BinaryData.fromString(chatCompletionInString).toObject(ChatCompletions.class)` for the ChatCompletion Object.

**Comment by junan-trustarc** [comment]
@mssfang

It is returning camelCase on property if you return ChatCompletions object on endpoint, I don't want to return String or BinaryData here, 
Think about on swagger point of view, we need to show well documented properties instead of showing none.
It was working on beta.8 and this is break changes on beta.9 or 10.

I verified again with new project between beta.8 and beta.10. it is different result as I explained above.

Please check with exactly with below code between beta.8 and beta.10.

```
@PostMapping("/testPost")
    public ChatCompletions postMethod() {
        return getChatCompletion();
    }

    public ChatCompletions getChatCompletion() {
        String azureOpenaiKey = "{key}";
        OpenAIClient client = new OpenAIClientBuilder()
            .endpoint("{endpoint}")
            .credential(new AzureKeyCredential(azureOpenaiKey))
            .buildClient();
        List<ChatRequestMessage> chatMessages = Arrays.asList(
            new ChatRequestSystemMessage("You are a helpful assistant."),
            new ChatRequestUserMessage("What sort of clothing should I wear today in Berlin?")
        );
        ChatCompletionsToolDefinition toolDefinition = new ChatCompletionsFunctionToolDefinition(
            getFutureTemperatureFunctionDefinition()); // get from your sample code

        ChatCompletionsOptions chatCompletionsOptions = new ChatCompletionsOptions(chatMessages);
        chatCompletionsOptions.setTools(Arrays.asList(toolDefinition));

        ChatCompletions chatCompletions = client.getChatCompletions("gpt-4o", chatCompletionsOptions);

        System.out.println("Chat Completions tool call size: " + chatCompletions.getChoices().get(0).getMessage().getToolCalls().size());

        return chatCompletions;
    }

    private static FunctionDefinition getFutureTemperatureFunctionDefinition() {
        FunctionDefinition functionDefinition = new FunctionDefinition("FutureTemperature");
        functionDefinition.setDescription("Get the future temperature for a given location and date.");
        FutureTemperatureParameters parameters = new FutureTemperatureParameters();
        functionDefinition.setParameters(BinaryData.fromObject(parameters));
        return functionDefinition;
    }

    private static class FutureTemperatureParameters {
        @JsonProperty(value = "type")
        private String type = "object";

        @JsonProperty(value = "properties")
        private FutureTemperatureProperties properties = new FutureTemperatureProperties();
    }

    private static class FutureTemperatureProperties {
        @JsonProperty(value = "unit")
        StringField unit = new StringField("Temperature unit. Can be either Celsius or Fahrenheit. Defaults to Celsius.");
        @JsonProperty(value = "location_name")
        StringField locationName = new StringField("The name of the location to get the future temperature for.");
        @JsonProperty(value = "date")
        StringField date = new StringField("The date to get the future temperature for. The format is YYYY-MM-DD.");
    }

    private static class StringField {
        @JsonProperty(value = "type")
        private final String type = "string";

        @JsonProperty(value = "description")
        private String description;

        @JsonCreator
        StringField(@JsonProperty(value = "description") String description) {
            this.description = description;
        }
    }
```

```
        <dependency>
            <groupId>com.azure</groupId>
            <artifactId>azure-ai-openai</artifactId>
            <version>1.0.0-beta.8</version> // or 10
        </dependency>
```

**Comment by mssfang** [comment]
@junan-trustarc 
The returned object, `ChatCompletion` is not returning camelCase, As explained above, the SDK returns correctly. The reason you see camelCase is because Spring uses `jackson-databind` but `azure-ai-openai` no longer depends on it as we migrate to use `azure-json`.

**Comment by junan-trustarc** [comment]
@mssfang um... so from my project point of view, how to use azure-json for specific endpoint??
I can't just switch to azure-json for entire endpoints right?
any idea?

**Comment by junan-trustarc** [comment]
It is a different behavior between beta.8 and 9 but seems like make sense to return camel case by default since it is java default behavior.

I created custom annotation to return for specific endpoints.

```
@Configuration
@ControllerAdvice
@AllArgsConstructor
public class AzureJsonConfig implements ResponseBodyAdvice<Object> {
    @Override
    public boolean supports(MethodParameter returnType, Class<? extends HttpMessageConverter<?>> converterType) {
        return returnType.getContainingClass().isAnnotationPresent(UseAzureJson.class);
    }

    @Override
    public Object beforeBodyWrite(Object body, MethodParameter returnType, MediaType selectedContentType, Class<? extends HttpMessageConverter<?>> selectedConverterType,
        ServerHttpRequest request, ServerHttpResponse response) {
        if (body == null) {
            return null;
        }

        try {
            if (returnType.getParameterType().isAssignableFrom(String.class)) {
                return body;
            }

            return BinaryData.fromObject(body).toObject(JsonNode.class);
        } catch (Exception e) {
            e.printStackTrace();
            return body;
        }
    }
}
```

```
@Target({ElementType.TYPE, ElementType.METHOD})
@Retention(RetentionPolicy.RUNTIME)
public @interface UseAzureJson {
}
```

```
@RestController
@RequestMapping(value = "/open-ai")
@UseAzureJson
public class OpenAiController {
 ...
}
```

I will close the ticket
