### ISSUE TITLE
[Question] How to implement batch message receiving in the Java version of the Event Hub SDK?

### ISSUE THREAD

**Issue by zorc** [Azure/azure-sdk-for-java#41062]
**Query/Question**
How to implement batch message receiving in the Java version of the Event Hub SDK? To improve the performance of message reception and database insertion, we need to implement batch retrieval of a certain number of messages from Event Hub, and then saving the checkpoint. For example, fetching 20 messages in one session, inserting them into a database in one transaction, and then saving the checkpoint. We found a .NET version source code example but couldn't locate similar examples or relevant information for the Java version. Could you please advise if there are Java implementation examples available? Thank you very much!

Here is a .NET version source code example，however, we cannot find the PluggableCheckpointStoreEventProcessor in the Java SDK.：
[Processing Events in Batches](https://github.com/Azure/azure-sdk-for-net/blob/main/sdk/eventhub/Azure.Messaging.EventHubs.Processor/samples/Sample07_BatchProcessing.md)

**Comment by anuchandy** [comment]
Hi @zorc, the sample showing how to receive events as batches can be found [here]( https://github.com/Azure/azure-sdk-for-java/blob/main/sdk/eventhubs/azure-messaging-eventhubs/src/samples/java/com/azure/messaging/eventhubs/EventProcessorClientCheckpointing.java). This sample uses an in-memory checkpoint store. The Event Hubs also offer Azure Blob Storage Checkpoint store, if you which to use it, the sample can be found [here]( https://github.com/Azure/azure-sdk-for-java/blob/main/sdk/eventhubs/azure-messaging-eventhubs-checkpointstore-blob/src/samples/java/com/azure/messaging/eventhubs/checkpointstore/blob/EventProcessorBlobCheckpointStoreSample.java).

**Comment by anuchandy** [comment]
Hi @zorc, the sample showing how to receive events as batches can be found [here]( https://github.com/Azure/azure-sdk-for-java/blob/main/sdk/eventhubs/azure-messaging-eventhubs/src/samples/java/com/azure/messaging/eventhubs/EventProcessorClientCheckpointing.java). This sample uses an in-memory checkpoint store. The Event Hub SDK also offer Azure Blob Storage Checkpoint store, if you wish to use it, the sample can be found [here]( https://github.com/Azure/azure-sdk-for-java/blob/main/sdk/eventhubs/azure-messaging-eventhubs-checkpointstore-blob/src/samples/java/com/azure/messaging/eventhubs/checkpointstore/blob/EventProcessorBlobCheckpointStoreSample.java).

**Comment by zorc** [comment]
> Hi @zorc, the sample showing how to receive events as batches can be found [here](https://github.com/Azure/azure-sdk-for-java/blob/main/sdk/eventhubs/azure-messaging-eventhubs/src/samples/java/com/azure/messaging/eventhubs/EventProcessorClientCheckpointing.java). This sample uses an in-memory checkpoint store. The Event Hub SDK also offer Azure Blob Storage Checkpoint store, if you wish to use it, the sample can be found [here](https://github.com/Azure/azure-sdk-for-java/blob/main/sdk/eventhubs/azure-messaging-eventhubs-checkpointstore-blob/src/samples/java/com/azure/messaging/eventhubs/checkpointstore/blob/EventProcessorBlobCheckpointStoreSample.java).

Thank you so much!

**Comment by zorc** [comment]
> Hi @zorc, the sample showing how to receive events as batches can be found [here](https://github.com/Azure/azure-sdk-for-java/blob/main/sdk/eventhubs/azure-messaging-eventhubs/src/samples/java/com/azure/messaging/eventhubs/EventProcessorClientCheckpointing.java). This sample uses an in-memory checkpoint store. The Event Hub SDK also offer Azure Blob Storage Checkpoint store, if you wish to use it, the sample can be found [here](https://github.com/Azure/azure-sdk-for-java/blob/main/sdk/eventhubs/azure-messaging-eventhubs-checkpointstore-blob/src/samples/java/com/azure/messaging/eventhubs/checkpointstore/blob/EventProcessorBlobCheckpointStoreSample.java).

Thank you so much!
