### ISSUE TITLE
[Identity] AzurePipelinesCredential parameterless constructor and add to DAC 

### ISSUE THREAD

**Issue by KarishmaGhiya** [Azure/azure-sdk-for-java#41129]
- Investigate a way to make the constructor of the credential AzurePipelinesCredential parameterless. This needs to be discussed with the service team so that it would work for all scenarios and tasks
- Add this credential to DAC once parameterless constructor is supported.

**Comment by g2vinay** [comment]
AzurePipelinesCredential shipped, closing this.
