### ISSUE TITLE
DocumentIntelligence 1099r Prebuilt Tax Model box 14 value contains unparsed currency amount

### ISSUE THREAD

**Issue by bjamin5** [Azure/azure-sdk-for-java#41217]
**Describe the bug**
When using the Prebuilt 1099r Tax Document Intelligence model (Api Version 2024-02-29 Preview) box 14 returns the value as a String with the $ sign included in the value while the other fields have some post processing to extract the value from the string. Basically It returns me a string with the '$' when it should return me an number without the $. See the example pictures below.  

**To Reproduce**
Using the Document Inteligence studio or via sdk upload the sample 1099r provided in the DI studio. 
Api Version 2024-02-29 Preview
Prebuilt Us Tax 1099
Model 1099-R

**Expected behavior**
Box 14 should return me a Value that's of type number (Double) not a string since all of the other boxes on the form return a number in the 'value' key-value pair.  Just this box doesn't remove the '$' from the amount and it returns it to me a string instead of a double. Proper behavior is that of box 16, 17, or 19 where the value is the parsed number from the content. Not a big deal to compensate but consistency would be nice. 

**Screenshots**
**Current Wrong Behavior**
![image](https://github.com/user-attachments/assets/f6847d87-ea96-4f91-afb2-43d624dc2c2e)
Should be {'Content': '$123,000', 'Value': 123000}

**Expected Behavior**
![image](https://github.com/user-attachments/assets/a92332c1-436b-4740-9148-c872a05431e4)

I'm using the Java SDK version: com.azure:azure-ai-documentintelligence:1.0.0-beta.3
To replicate the problem I used the Document Intelligence studio and the default sample 1099-R.

**Comment by bjamin5** [comment]
In addition to the previous problem it appears that even with an empty box, boxes 14 and 17 return the '$' symbol as the value when it should return nothing. 
![image](https://github.com/user-attachments/assets/c7791721-7188-41b9-94a5-bdcc15c838d7)

**Comment by joshfree** [comment]
@samvaity

**Comment by samvaity** [comment]
@bjamin5 Thank you for reporting this.
I can confirm I am seeing the same results.

@bojunehsu Could you look into this, seems like the service is returning inconsistent results for similar data extraction.
