### ISSUE TITLE
[FEATURE REQ] com.azure.json.JsonWriter.writeMapField write null value to the Map field

### ISSUE THREAD

**Issue by heyams** [Azure/azure-sdk-for-java#41269]
Here is an example of auto-generated `toJson` method in one of our data models by using the autorest tool:

```java
    /**
     * {@inheritDoc}
     */
    @Override
    public JsonWriter toJson(JsonWriter jsonWriter) throws IOException {
        jsonWriter.writeStartObject();
        jsonWriter.writeStringField("name", this.name);
        jsonWriter.writeStringField("time",
            this.time == null ? null : DateTimeFormatter.ISO_OFFSET_DATE_TIME.format(this.time));
        jsonWriter.writeNumberField("ver", this.version);
        jsonWriter.writeNumberField("sampleRate", this.sampleRate);
        jsonWriter.writeStringField("seq", this.sequence);
        jsonWriter.writeStringField("iKey", this.instrumentationKey);
        jsonWriter.writeMapField("tags", this.tags, (writer, element) -> writer.writeString(element)); // this line will write attribute with null value
        jsonWriter.writeJsonField("data", this.data);
        return jsonWriter.writeEndObject();
    }
```

`jsonWriter.writeMapField("tags", this.tags, (writer, element) -> writer.writeString(element)); ` will write attributes with null values. 
For azure-monitor-opentelemetry-exporter, we don't want to produce attributes with null values in the json payload. The main reason is because of cost, our customers are paying for the payload. 

This would require a workaround for now. Instead of calling `jsonWriter.writeMapField`, this is what i used and recommended by @alzimmermsft  

```java
public static <T> void writeMap(Map<String, T> map, String fieldName, JsonWriter jsonWriter, Consumer<T> writeValueCallback) throws IOException {
        if (map == null) {
            return;
        }
        jsonWriter.writeFieldName(fieldName);
        jsonWriter.writeStartObject();
        for (Map.Entry<String, T> entry : map.entrySet()) {
            T value = entry.getValue();
            if (value == null) {
                continue;
            }
            jsonWriter.writeFieldName(entry.getKey());
            writeValueCallback.accept(entry.getValue());
        }
        jsonWriter.writeEndObject();
    }
```

I've tested it and it worked. This requires modification each time we use autorest tool to update data models. Ideally, if azure-json can handle this by default, it will be super helpful. 

cc @trask @alzimmermsft

**Comment by joshfree** [comment]
@alzimmermsft

**Comment by alzimmermsft** [comment]
This has been fixed with the new release of `azure-json` which provides new APIs for better managing `writeArray` and `writeMap` helpers in `JsonWriter`.

`JsonWriter.writeMapField(String fieldName, Map<String, T> map, WriteValueCallback<JsonWriter, T> callback)` will now always write a JSON `null` when the value of the map entry is null. There is a new overload with an additional parameter `boolean skipNullValues` which will skip serializing the map key-value pair into a JSON fieldname-value when the value is null.
