### ISSUE TITLE
Container Sas simple sample

### ISSUE THREAD

**Issue by ohadbitt** [Azure/azure-sdk-for-java#4127]
Took a lot of time to figure out how to use a container sas I already have. 
Please add this (doesn't need to be scala of course):
 ```scala
def uploadBySasFromStream(outStream: OutputStream) = {
   val urlsas = new URL("https://<account>.blob.core.windows.net/<container>/<blobName>?st=2019-06-26T14%3A59%3A03Z&se=2019-06-27T14%3A59%3A03Z&sp=rwdl&sv=2018-03-28&sr=c&sig=secretsecretsecretsecretsecretsecretsecret%3D")
    val blobURLsas: BlockBlobURL = new BlockBlobURL(urlsas,StorageURL.createPipeline(new AnonymousCredentials(), new PipelineOptions()))
    blobURLsas.upload(Flowable.just(ByteBuffer.wrap(outStream.toByteArray)),length).blockingGet()
}
```

**Comment by loarabia** [comment]
@ohadbitt would you by any chance be willing to make a pull request to the the readme to add this? https://github.com/Azure/azure-sdk-for-java/tree/master/storage/data-plane

**Comment by rickle-msft** [comment]
The original post is using an older, deprecated version of the sdk that has since been replaced. We do have examples on how to build clients using a sas token in the new readmes.
