### ISSUE TITLE
List AKS Nodes on KubernetesClusters interface

### ISSUE THREAD

**Issue by jsarrelli** [Azure/azure-sdk-for-java#41285]
Using the JAVA SDK we have the KubernetesClusters interface which allows to list the cluster and agent pools, but its not possible to list the nodes inside those agent pools. 
Also, it would be nice to have the agent pool ID, at the moment it only provides the name
Im using 
` "com.azure.resourcemanager" % "azure-resourcemanager" % "2.38.0",`

Example:
```

import akka.NotUsed
import akka.stream.scaladsl.Source
import com.azure.resourcemanager.containerservice.models.{KubernetesCluster, KubernetesClusterAgentPool, KubernetesClusters}

import scala.jdk.CollectionConverters.CollectionHasAsScala

case class AksClient(underlying: KubernetesClusters) {
  val listClusters: Source[KubernetesCluster, NotUsed] = Source.fromPublisher(underlying.listAsync())
  val listAgentPools: Source[KubernetesClusterAgentPool, NotUsed] = Source.fromPublisher(underlying.listAsync()).mapConcat(_.agentPools().values().asScala.toList)
  val listNnodes = agentPools.map(_.nodes)
}
```

**Comment by weidongxu-microsoft** [comment]
SDK uses ARM REST API for AKS features (those on https://management.azure.com). So far, I didn't see the REST API for listing the nodes. (here is for list agent pools https://learn.microsoft.com/rest/api/aks/agent-pools/list?view=rest-aks-2024-02-01)

I've seen Azure CLI having features about the nodes https://learn.microsoft.com/en-us/cli/azure/aks/nodepool?view=azure-cli-latest#az_aks_nodepool_list
but I think it uses `kubectl` or some other tool to communicate with the cluster.

I could be wrong. Let me know if you see the API to list nodes on https://management.azure.com
