### ISSUE TITLE
[BUG] Blob storage using older version of Jackson that is vulnerable to Denial of Service

### ISSUE THREAD

**Issue by jcrichlake** [Azure/azure-sdk-for-java#41330]
**Describe the bug**
Blob storage is using an older version of the Jackson library that is vulnerable to DoS attacks.  Currently a version of 2.15.0-rc1 or higher is needed

Link to the issue https://security.snyk.io/vuln/SNYK-JAVA-COMFASTERXMLJACKSONCORE-7569538

**Comment by jcrichlake** [comment]
Any feedback on this? It's been a few days

**Comment by ibrahimrabab** [comment]
Hi @jcrichlake 
Thank you for reaching out with this issue! We've updated our Jackson dependencies here:
https://github.com/Azure/azure-sdk-for-java/pull/41306

So this issue should be taken care of by our next release :)
