### ISSUE TITLE
Fix azure-developer-loadtesting sdk sample

### ISSUE THREAD

**Issue by faynef** [Azure/azure-sdk-for-java#41411]
1.

**Section** [link](https://github.com/Azure/azure-sdk-for-java/blob/main/sdk/loadtesting/azure-developer-loadtesting/src/samples/java/com/azure/developer/loadtesting/ReadmeSamples.java#L118):
![image](https://github.com/user-attachments/assets/b74f1849-d11d-41c3-a6f7-10c9e9d284c5)

**Reason:**
`uploadTestFileWithResponse(java.lang.String, java.lang.String, com.azure.core.util.BinaryData, com.azure.core.http.rest.RequestOptions)` is not public in `com.azure.developer.loadtesting.LoadTestAdministrationClient`. Cannot be accessed from outside package

**Suggestion:**
Change the access permission of the `uploadTestFileWithResponse(java.lang.String, java.lang.String, com.azure.core.util.BinaryData, com.azure.core.http.rest.RequestOptions)` method in the `com.azure.developer.loadtesting.LoadTestAdministrationClient` class to public, or delete this test code.

@sandeep-sen , @joshfree and @Harshan01 for notification.

**Comment by joshfree** [comment]
@Harshan01 @prativen PTAL

**Comment by joshfree** [comment]
@Harshan01 it seems the .github/CODEOWNERS entry for /sdk/loadtesting also needs to be updated.  Could you do so at the same time please?
