### ISSUE TITLE
[BUG] Gateway Mode Create Tests are failing. No Retries Happening

### ISSUE THREAD

**Issue by Vrinda2311** [Azure/azure-sdk-for-java#41429]
**Describe the bug**
In the gateway connection mode, for create operations, after injecting READ_SESSION_NOT_AVAILABLE, retries rae supposed to happen in cross region with "AvailabilityStrategy" but that is not happening with sdk version 4.63. Request are timing out under just 10ms, without any cross region retries. Working fine with 4.62.

***Exception or Stack Trace***
{
  "innerErrorMessage": null,
  "cosmosDiagnostics": {
    "userAgent": "azsdk-java-cosmos/4.63.0 MacOSX/14.5 JRE/17.0.7 fault_injection_test_multi_master_gateway_mode-azsdk-java-cosmos/4.63.0 MacOSX/14.5 JRE/17.0.7:East US 2",
    "activityId": "1e1201fa-a086-40f2-a3d8-1e23cc85604a",
    "requestLatencyInMs": 1,
    "requestStartTimeUTC": "2024-08-01T16:54:57.417177Z",
    "requestEndTimeUTC": "2024-08-01T16:54:57.418321Z",
    "responseStatisticsList": [],
    "supplementalResponseStatisticsList": [],
    "addressResolutionStatistics": {},
    "regionsContacted": [
      "east us 2"
    ],
    "retryContext": {
      "statusAndSubStatusCodes": [
        [
          404,
          1002
        ],
        [
          404,
          1002
        ]
      ],
      "retryCount": 2,
      "retryLatency": 0
    },
    "metadataDiagnosticsContext": {
      "metadataDiagnosticList": null
    },
    "serializationDiagnosticsContext": {
      "serializationDiagnosticsList": null
    },
    "gatewayStatisticsList": [
      {
        "sessionToken": "1:1#1#1=1#1=1",
        "operationType": "Read",
        "resourceType": "DocumentCollection",
        "statusCode": 404,
        "subStatusCode": 1002,
        "requestCharge": 0,
        "requestTimeline": [
          {
            "eventName": "connectionAcquired",
            "startTimeUTC": "2024-08-01T16:54:57.417437Z",
            "durationInMilliSecs": 0.132
          },
          {
            "eventName": "connectionConfigured",
            "startTimeUTC": null,
            "durationInMilliSecs": 0
          },
          {
            "eventName": "requestSent",
            "startTimeUTC": null,
            "durationInMilliSecs": 0
          },
          {
            "eventName": "transitTime",
            "startTimeUTC": null,
            "durationInMilliSecs": 0
          },
          {
            "eventName": "received",
            "startTimeUTC": null,
            "durationInMilliSecs": 0
          }
        ],
        "partitionKeyRangeId": null,
        "responsePayloadSizeInBytes": 0,
        "exceptionResponseHeaders": "{x-ms-session-token=1:1#1#1=1#1=1, x-ms-cosmos-llsn=0, x-ms-activity-id=c0845733-e648-48ac-b102-f0d451cb7b32, x-ms-substatus=1002}",
        "faultInjectionRuleId": "READ_SESSION_NOT_AVAILABLE_LOCAL_REGION_1722531297416",
        "locationToLocationSpecificHealthContext": {
          "v": null
        }
      },
      {
        "sessionToken": "1:1#1#1=1#1=1",
        "operationType": "Read",
        "resourceType": "DocumentCollection",
        "statusCode": 404,
        "subStatusCode": 1002,
        "requestCharge": 0,
        "requestTimeline": [
          {
            "eventName": "connectionAcquired",
            "startTimeUTC": "2024-08-01T16:54:57.418159Z",
            "durationInMilliSecs": 0.146
          },
          {
            "eventName": "connectionConfigured",
            "startTimeUTC": null,
            "durationInMilliSecs": 0
          },
          {
            "eventName": "requestSent",
            "startTimeUTC": null,
            "durationInMilliSecs": 0
          },
          {
            "eventName": "transitTime",
            "startTimeUTC": null,
            "durationInMilliSecs": 0
          },
          {
            "eventName": "received",
            "startTimeUTC": null,
            "durationInMilliSecs": 0
          }
        ],
        "partitionKeyRangeId": null,
        "responsePayloadSizeInBytes": 0,
        "exceptionResponseHeaders": "{x-ms-session-token=1:1#1#1=1#1=1, x-ms-cosmos-llsn=0, x-ms-activity-id=1e1201fa-a086-40f2-a3d8-1e23cc85604a, x-ms-substatus=1002}",
        "faultInjectionRuleId": "READ_SESSION_NOT_AVAILABLE_LOCAL_REGION_1722531297416",
        "locationToLocationSpecificHealthContext": {
          "v": null
        }
      }
    ],
    "samplingRateSnapshot": 1,
    "bloomFilterInsertionCountSnapshot": 0,
    "systemInformation": {
      "usedMemory": "139224 KB",
      "availableMemory": "8249384 KB",
      "systemCpuLoad": "(2024-08-01T16:54:46.975321Z 72.4%), (2024-08-01T16:54:50.238302Z 74.9%), (2024-08-01T16:54:53.201402Z 43.8%), (2024-08-01T16:54:55.311892Z 44.2%)",
      "availableProcessors": 10
    },
    "clientCfgs": {
      "id": 4,
      "machineId": "uuid:c92b6482-3369-47de-9e3b-d246bfc62798",
      "connectionMode": "GATEWAY",
      "numberOfClients": 1,
      "excrgns": "[]",
      "clientEndpoints": {
        "https://cosmos-sdk-dev-stage-cosmos.documents.azure.com:443/": 4
      },
      "connCfg": {
        "rntbd": null,
        "gw": "(cps:1000, nrto:PT1M, icto:PT1M, p:false)",
        "other": "(ed: true, cs: false, rv: true)"
      },
      "consistencyCfg": "(consistency: Session, mm: true, prgns: [eastus2,southcentralus,westus2])",
      "proactiveInitCfg": "",
      "e2ePolicyCfg": "{e2eto=PT2S, as={threshold=PT0.5S, step=PT0.1S}}",
      "sessionRetryCfg": "(rsh:LOCAL_REGION_PREFERRED, minrrt:PT0.5S, maxrrc:1)",
      "regionScopedSessionCfg": "(rssc: true, expins: 5000000, ffprate: 0.001)",
      "partitionLevelCircuitBreakerCfg": "(cb: false, type: CONSECUTIVE_EXCEPTION_COUNT_BASED, rexcntt: 10, wexcntt: 5)"
    }
  }
}
Add the exception log and stack trace if available

**To Reproduce**

***Code Snippet***
{
    FeatureTestResult ts = new FeatureTestResult();
    WorkLoadConfig wc =
        CosmosDriverConfig.createBaseMultiMasterWorkloadConfig(
            new ArrayList<>(Collections.singletonList(localRegion)),
            "2000ms",
            1000,
            "READ_SESSION_NOT_AVAILABLE",
            "READ_SESSION_NOT_AVAILABLE_LOCAL_REGION",
            null,
            4,
            true,
            ConnectionMode.GATEWAY);
    ((CosmosDriverConfig) wc.getDriverConfigsDTO()).setEndToEndOperationTimeout("2s");
    ((CosmosDriverConfig) wc.getDriverConfigsDTO()).setLocalRegionPreferred(false);
    Properties props = CosmosDriverConfig.getMergedProperties(wc);
    props.setProperty(CosmosConfigConstants.MASTER_KEY, CosmosDBUtil.getMultiMaster());

    CosmosAsyncClient client = CosmosUtil.buildClient(props);
    CosmosAsyncContainer container = client.getDatabase(database).getContainer(collection);
    CosmosDao cosmosDao = new CosmosDao();
    cosmosDao.setClient(client);
    cosmosDao.setContainer(container);
    cosmosDao.setUuIdcache(uuidcache);

    List<FaultInjectionConfig> faultInjectionList = wc.getFaultInjectionList();
    UUID uuid = UUID.randomUUID();
    BaseCosmosDO d = new BaseCosmosDO(uuid, "benchmark test");
    d.setContent("this is a test");

    for (int i = 0; i < faultInjectionList.size(); i++) {
      faultInjectionList.get(i).getInjectionRequest().setPartitionKey(d.getId().toString());
      faultInjectionList
          .get(i)
          .getInjectionRequest()
          .setConnectionType(ConnectionMode.GATEWAY.name());
      FaultInjectionUtil.injectFault(cosmosDao, faultInjectionList.get(i).getInjectionRequest());
    }

    ThresholdBasedAvailabilityStrategy availabilityStrategy =
        CosmosFeatureTestUtil.createEagerThresholdBasedAvailabilityStrategy();
    CosmosItemRequestOptions options =
        CosmosFeatureTestUtil.createCosmosItemRequestOptionsWithAvailabilityStrategy(
            Duration.ofSeconds(2), availabilityStrategy);
    options.setNonIdempotentWriteRetryPolicy(true, true);

    CosmosResponse res = cosmosDao.createForUnitTest(d, options, false);
    CosmosDiagnostics cd = res.getCosmosDiagnostics();

    log.info(
        "testCreate_404_1002_FirstRegionOnly_LocalPreferred_EagerAvailabilityStrategy_WithRetries Status code="
            + cd.getDiagnosticsContext().getStatusCode());
    if (cd.getDiagnosticsContext().getStatusCode() == 201
        && cd.getDiagnosticsContext().getSubStatusCode() == 0
        && cd.getDiagnosticsContext().getContactedRegionNames().size() > 1) {
      ts.setStatus(TestStatus.Success);
    } else {
      ts.setStatus(TestStatus.Failed);
      ts.addMessage(
          "Expected status code is 201 and actual is "
              + cd.getDiagnosticsContext().getStatusCode());
      ts.addMessage(
          "Expected sub-status code is 0 and actual is "
              + cd.getDiagnosticsContext().getSubStatusCode());
      ts.addMessage(
          "Expected contacted regions are 3 and actual are "
              + cd.getDiagnosticsContext().getContactedRegionNames().size());
      ts.addMessage(
          "Expected cosmos diagnostics logs size are 3 and actual are "
              + cd.getDiagnosticsContext().getDiagnostics().size());
    }
    Map<String, Instant> hashmap = FaultInjectionUtil.getMapOfRegionAndRequestStartTime(cd);
    System.out.println("HashMap=" + hashmap);
    CosmosFeatureTestUtil.getAvailabilityStrategyTestResult(
        hashmap,
        50,
        30,
        ((CosmosDriverConfig) wc.getDriverConfigsDTO()).getPreferredRegions(),
        700,
        ts);
    client.close();
    return ts;
  }

**Expected behavior**
Should have retries in remote region and give sucess.

**Screenshots**

**Setup (please complete the following information):**
 - IDE: [e.g. IntelliJ]
 - Library/Libraries: [e.g. com.azure:azure-core:1.16.0 (groupId:artifactId:version)]
 - Java version: [e.g. 8] 
 - App Server/Environment: [e.g. Tomcat, WildFly, Azure Function, Apache Spark, Databricks, IDE plugin or anything special]
 - Frameworks: [e.g. Spring Boot, Micronaut, Quarkus, etc] 

If you suspect a dependency version mismatch (e.g. you see `NoClassDefFoundError`, `NoSuchMethodError` or similar), please check out [Troubleshoot dependency version conflict article](https://aka.ms/azsdk/java/dependency/troubleshoot) first. If it doesn't provide solution for the problem, please provide:
- verbose dependency tree (`mvn dependency:tree -Dverbose`)
- exception message, full stack trace, and any available logs

**Additional context**

**Information Checklist**
Kindly make sure that you have added all the following information above and checkoff the required fields otherwise we will treat the issuer as an incomplete report
- [ ] Bug Description Added
- [ ] Repro Steps Added
- [ ] Setup information Added

**Comment by joshfree** [comment]
@kushagraThapar please help route as appropriate

**Comment by kushagraThapar** [comment]
Thanks @Vrinda2311 for creating this issue, we are actively working on these fixes.
