### ISSUE TITLE
CosmosDB - The request did not complete due to a high rate of metadata requests

### ISSUE THREAD

**Issue by Blackbaud-JasonBodnar** [Azure/azure-sdk-for-java#41468]
**Query/Question**
How can you delete multiple databases using Cosmos Java SDK without getting an error about a high rate of metadata requests?

We accidentally created 400+ databases with (slightly) random names in our Cosmos NOSQL account. I've written code to data from each of these databases (if present) to the real database it should be in and then to delete the database with the random name.

```
databaseIds.forEach(id -> {
  CosmosAsyncDatabase database = cosmosClient.getDatabase(id);
  Set<CompletedEmailJobEntity> completedEmailJobEntities = getCompletedJobsFromDatabase(database);
  if (addJobsToRealDatabase(completedEmailJobEntities) == false) {
    deleteDatabase(database);
  }
});

private Set<CompletedEmailJobEntity> getCompletedJobsFromDatabase(CosmosAsyncDatabase database) {
  CosmosAsyncContainer container = database.getContainer(CompletedEmailJobEntity.COLLECTION_NAME);
  return container.queryItems("SELECT * FROM c", new CosmosQueryRequestOptions(), CompletedEmailJobEntity.class).toStream().collect(Collectors.toSet());
}

private boolean addJobsToRealDatabase(Set<CompletedEmailJobEntity> completedEmailJobEntities) {
  AtomicBoolean hadFailedSaves = new AtomicBoolean(false);
  completedEmailJobEntities.forEach(entity -> {
    try {
      completedEmailJobRepository.save(entity);
    } catch (Exception e) {
      hadFailedSaves.set(true);
    }
  });
  return hadFailedSaves.get();
}

private void deleteDatabase(CosmosAsyncDatabase database) {
   CosmosDatabaseResponse response = database.delete().block();
   if (isNotSuccessfulResponse(response)) {
      log.debug("Could not delete {}: {}", database.getId(), response);
   } else {
     log.debug("Successfully deleted {}", database.getId());
   }
}
```

The code is able to run completely on one database, copying any data found and then it copies data found for the next database but when it tries to delete that one we get an error:

```
com.azure.cosmos.CosmosException: {"innerErrorMessage":"Message: {\"Errors\":[\"The request did not complete due to a high rate of metadata requests. Increasing request units will have no impact and is not recommended. Please retry the request. https:\\/\\/aka.ms\\/CosmosDB\\/sql\\/errors\\/metadata-429\"]} ...
```

The page in the error says to 1) perform operations at a lower rate, 2) use static cosmos client instances or 3) cache the names of databases and containers.

I'm using a static cosmos client instance and I'm passing the names of the databases to delete to the code externally. There are no calls to read or query databases.

Is performing the deletes at a lower rate really the only option?

***Why is this not a Bug or a feature Request?***
Surely there must be a way to delete a bunch of databases in a short period time?

**Setup (please complete the following information if applicable):**
 - OS: Linux
 - Library/Libraries: azure-cosmos:4:58.0, azure-spring-data-cosmos:5.12.0
 
 **Information Checklist**
 Kindly make sure that you have added all the following information above and checkoff the required fields otherwise we will treat the issuer as an incomplete report
- [ X ] Query Added
- [ X ] Setup information Added

**Comment by kushagraThapar** [comment]
@Blackbaud-JasonBodnar I am investigating this issue, will provide an update soon here.

**Comment by Blackbaud-JasonBodnar** [comment]
@kushagraThapar : Thank you. I've found a work around. I've wrapped the call to delete the database in a Spring `RetryTemplate` with a 1 minute exponential backoff. When the call fails the first time it always succeeds the next time after the one minute delay.

**Comment by joshfree** [comment]
Updating title to make this more discoverable in search results for others.

**Comment by jeet1995** [comment]
Hey @Blackbaud-JasonBodnar - glad you found a workaround. `ThrottlingRetryOptions` would have been a good candidate but since this is a use case to delete several 100s of databases it doesn't align with a production workload and therefore wouldn't make sense to special case. The other thought would be to perform a copy of the data to the relevant containers in the relevant databases and delete the randomly created databases after - so placing a delay between database call becomes a non-issue.
