### ISSUE TITLE
[FEATURE REQ] Change OpenAIAsyncClient to be compatible with other Open AI compatible GPTs such as Ollama

### ISSUE THREAD

**Issue by berdachuk** [Azure/azure-sdk-for-java#41518]
**Is your feature request related to a problem? Please describe.**
Currently, in the NonAzureOpenAIClientImpl, the hardcoded OPEN_AI_ENDPOINT is "https://api.openai.com/v1".
So it is not possible to use OpenAIAsyncClient with other Open AI-compatible GPTs like Ollama.

**Describe the solution you'd like**
It would be useful to create a customizable client version to work with different providers.

**Describe alternatives you've considered**
Add possibility to use OpenAIAsyncClient with other Open AI-compatible GPTs like Ollama for remote and local testing (required "https" also have to be removed for local setup).

**Information Checklist**

- [x] Description Added
- [x] Expected solution specified

**Comment by mssfang** [comment]
@berdachuk 
Unfortunately, we will not support non-OpenAI models in this SDK, azure-ai-openai as per our partnership with OpenAI.
The most major models are available as first-class Azure Host Endpoints, such as Llama2, Cohere and Mistra, via Azure MaaS ([Azure AI Studio Model Catalog](https://learn.microsoft.com/en-us/azure/ai-studio/how-to/model-catalog)).
