### ISSUE TITLE
[BUG] Cannot provision VMs with Ultra SSD disk

### ISSUE THREAD

**Issue by skennic** [Azure/azure-sdk-for-java#41529]
**Describe the bug**
When creating a virtual machine with an ultra ssd disk attached an error occurs that "StorageAccountType UltraSSD_LRS can be used only when additionalCapabilities.ultraSSDEnabled is set."
However, this flag cannot be set in the virtual machine class of the java sdk.
I only found the AdditionalCapabilities class, but it can only be used with the VirtualMachineInner class.

***Exception or Stack Trace***
```
com.azure.resourcemanager.compute.models.ApiErrorException: Status code 400, "{
  "error": {
    "code": "InvalidParameter",
    "message": "StorageAccountType UltraSSD_LRS can be used only when additionalCapabilities.ultraSSDEnabled is set.",
    "target": "managedDisk.storageAccountType"
  }
```

**To Reproduce**
Create a virtual machine with an ultra ssd disk via the azure resourcemanager in java.

***Code Snippet***
```Java
var dataDisk = azureResourceManager.disks().define("data_disk")
                        .withRegion(Region.EUROPE_WEST)
                        .withExistingResourceGroup(resourceGroup)
                        .withData()
                        .withSizeInGB(100)
                        .withSku(DiskSkuTypes.ULTRA_SSD_LRS)
                        .create();

var vm =  azureResourceManager.virtualMachines()
                .define("vm_with_ultra_ssd")
                .withRegion(resourceGroup.regionName())
                .withExistingResourceGroup(resourceGroup)
                .withExistingPrimaryNetworkInterface(nic)
                .withGeneralizedWindowsGalleryImageVersion(vmDefinition.galleryImage())
                .withAdminUsername(credentials.getUsername())
                .withAdminPassword(credentials.getPassword());
                .withExistingDataDisk(dataDisk);
                .withSize(vmDefinition.sku())
                .create();
```

**Expected behavior**

- Either set the flag `additionalCapabilities.ultraSSDEnabled` to true if it is not possible to set it in the SDK or
- provide a method on the VirtualMachine class to set the capability like
  `.withAdditionalCapabilities(new AdditionalCapabilities().withUltraSSDEnabled(true))` or
  `.enableUltraSSDDisk()` (similiar to how it is possible to enable hibernation via `.enableHibernation()`)

**Screenshots**
n/a

**Setup (please complete the following information):**
 - IDE: IntelliJ
 - Library/Libraries: com.azure.resourcemanager:azure-resourcemanager:2.41.0 (groupId:artifactId:version)
 - Java version: 21 
 - App Server/Environment: Tomcat
 - Frameworks: Spring Boot

**Additional context**

**Information Checklist**
Kindly make sure that you have added all the following information above and checkoff the required fields otherwise we will treat the issuer as an incomplete report
- [X] Bug Description Added
- [X] Repro Steps Added
- [X] Setup information Added

**Comment by weidongxu-microsoft** [comment]
Plan to add a `enableUltraSsd()` on `VirtualMachine` in next release.

**Comment by weidongxu-microsoft** [comment]
Currently there is lots of requirement on enabling the ultra SSD.

1. availability zone
2. ES/DS v3 sku https://azure.microsoft.com/en-us/blog/announcing-ultra-ssd-the-next-generation-of-azure-disks-technology-preview/
3. disk cache is NONE
