### ISSUE TITLE
[QUERY] Confirm behavior of Azure-AsyncOperation for PATCH/PUT with final-state-via set

### ISSUE THREAD

**Issue by jhendrixMSFT** [Azure/azure-sdk-for-java#41546]
Pollers in some languages assume that for `Azure-AsyncOperation` LROs initiated with a `PATCH`/`PUT` that the "final get" is made against the originating URL and not the value specified in the `final-state-via` setting.

Can you please confirm if Java pollers have the same behavior?

This potentially impacts the [arm-resourcemanager-quota](https://github.com/Azure/azure-sdk-for-java/tree/main/sdk/quota/azure-resourcemanager-quota) SDK as the latest preview version contains an `Azure-AsyncOperation` LRO initiated with a `PUT` that also sets the `final-state-via` to `Location`.

**Comment by weidongxu-microsoft** [comment]
Java SDK does not use `final-state-via` at all.

For a PUT/PATCH, the final result is always the original URL of the PUT/PATCH.

Reason is that PUT/PATCH in REST is to create/update a resource, and the URL is that the resource is.

**Comment by jhendrixMSFT** [comment]
Per discussion, `final-state-via` is for `POST` only. The docs have been updated, see https://github.com/Azure/autorest/pull/5004.
