### ISSUE TITLE
[BUG] Typo in doc for azure-cosmos-spark: ServicePrinciple not ServicePrincipal

### ISSUE THREAD

**Issue by stevenylai** [Azure/azure-sdk-for-java#41541]
**Describe the bug**
As titled, the documentation azure-cosmos-spark has a typo. For example https://github.com/Azure/azure-sdk-for-java/blob/main/sdk/cosmos/azure-cosmos-spark_3_2-12/docs/configuration-reference.md 

***Exception or Stack Trace***
RuntimeException: Invalid configuration for spark.cosmos.auth.type:ServicePrincipal. Config description: There are two auth types are supported currently: 'MasterKey' (...), 'ServicePrinciple' (...)

**To Reproduce**
Happened when we set `spark.cosmos.auth.type=ServicePrincipal` as in the doc

***Code Snippet***
```python
spark.conf.set("spark.sql.catalog.cosmosCatlog.spark.cosmos.auth.type", "ServicePrincipal")
```

**Expected behavior**
Documentation should be updated to reflect the correct value instead of letting user to set the wrong value and figuring out the correct one from a stack trace.

**Screenshots**

**Setup (please complete the following information):**
 - OS: Linux
 - IDE: Databricks Workspace
 - Library/Libraries: azure-cosmos-spark_3-1_2-12-4.33.0.jar
 - Java version: 8
 - App Server/Environment: Databricks
 - Frameworks: Spark

If you suspect a dependency version mismatch (e.g. you see `NoClassDefFoundError`, `NoSuchMethodError` or similar), please check out [Troubleshoot dependency version conflict article](https://aka.ms/azsdk/java/dependency/troubleshoot) first. If it doesn't provide solution for the problem, please provide:
- verbose dependency tree (`mvn dependency:tree -Dverbose`)
- exception message, full stack trace, and any available logs

**Additional context**
N/A

**Information Checklist**
Kindly make sure that you have added all the following information above and checkoff the required fields otherwise we will treat the issuer as an incomplete report
- [ x ] Bug Description Added
- [ x ] Repro Steps Added
- [ x ] Setup information Added

**Comment by kushagraThapar** [comment]
@xinlian12 can you please take a look at this, thanks!

**Comment by xinlian12** [comment]
The doc has been updated.

**Comment by stevenylai** [comment]
Sorry, which doc has been updated? If I search 'CosmosDB spark connector configuration', the first one I get is https://learn.microsoft.com/en-us/azure/cosmos-db/nosql/tutorial-spark-connector?pivots=programming-language-python and under `Configuration parameter reference`, it still takes me to the `configuration-reference.md` in the repo where it says `ServicePrincipal` all over the place.
