### ISSUE TITLE
com.azure.azure-storage-blob does not produce logs

### ISSUE THREAD

**Issue by Ivan-Nikitin-MSI** [Azure/azure-sdk-for-java#41551]
**Query/Question**
Enabling logs for `com.azure.azure-storage-blob` via `logback.xml` in a spring boot project does not result in any logs.

Logs enabled via:

```
<logger name="com.azure.azure-storage-blob" level="TRACE" />
```

***Why is this not a Bug or a feature Request?***
Possibly wrong logging configuration on user end.

**Setup (please complete the following information if applicable):**
 - Library/Libraries: `{ group = 'com.azure', name = 'azure-storage-blob', version = '12.27.0' }`
 - Springboot application
 - Trace level logs enabled via `logback.xml`
 - Logs sent to and inspected via Kibana instance
 
 **Information Checklist**
 Kindly make sure that you have added all the following information above and checkoff the required fields otherwise we will treat the issuer as an incomplete report
- [x] Query Added
- [x] Setup information Added

**Comment by Ivan-Nikitin-MSI** [comment]
Hi,
Thanks for your reply!

I have edited the `logback.xml` to be as follows:

```
    <logger name="com.azure.storage.blob.BlobClient" level="TRACE" />
    <logger name="com.azure.storage.blob.BlobServiceClient" level="TRACE" />
    <logger name="com.azure.storage.blob.BlobContainerClient" level="TRACE" />
    <logger name="com.azure.storage.blob.specialized.BlockBlobClient" level="TRACE" />
    <logger name="com.azure.storage.blob.specialized.BlobOutputStream" level="TRACE" />
    ```
    
However, I am still not seeing any log entries for any of these classes. I believe this is now set up according to the docs. Could you advise?

Thanks again for your help!

**Comment by alzimmermsft** [comment]
Thanks for the update @Ivan-Nikitin-MSI.

After doing a review of those classes, they don't have many log statements, and they only happen in a few failure cases. It's possible these code paths aren't being exercised. `BlobServiceClient` and `BlobContainerClient` don't log anything and between `BlobClient`, `BlockBlobClient`, and `BlobOutputStream` there are nine possible locations a log statement could happen.

I did a test with the following logback.xml configuration and did have logging happening:

```xml
<?xml version="1.0" encoding="UTF-8"?>
<configuration>
  <appender name="STDOUT" class="ch.qos.logback.core.ConsoleAppender">
    <layout class="ch.qos.logback.classic.PatternLayout">
      <Pattern>
        %black(%d{ISO8601}) %highlight(%-5level) [%blue(%t)] %blue(%logger{100}): %msg%n%throwable
      </Pattern>
    </layout>
  </appender>

  <root level="OFF">
    <appender-ref ref="STDOUT" />
  </root>

  <logger name="com.azure.storage.blob" level="TRACE" />
  <logger name="com.azure.core" level="TRACE" />
</configuration>
```

A lot of the logging generated by the SDKs happens in the `com.azure.core` package.
