### ISSUE TITLE
@ServiceBusListener lock renewal works wired

### ISSUE THREAD

**Issue by kensinzl** [Azure/azure-sdk-for-java#41560]
**Query/Question**
I have two consumers to monitor one Azure Service Bus Queue whose default ServiceBusReceiveMode is PeekLock.

I know the maximum message lock duration of the Azure Service Bus Queue is 5 minutes.

Now if one message's processing time is 16 minutes,

I thought it should be

- Consumer1 picked up this message at 1:00, and at the same time, Consumer2 cant see the message.
- At 1:05, Consumer1 should renew the lock to continue, and Consumer2 should still not see the message.
- Repeatly at 1:10, Consumer1 continue to renew, and Consumer2 should not see.
- Repeatly at 1:15, Consumer1 continue to renew, and Consumer2 should not see.
- Finally, at 1:16, the Consumer finished the message and then deleted it from the queue.

But my local works wired like the following

- Consumer1 picked up this message at 1:00, and at the same time, Consumer2 cant see the message.
- At 1:05, Consumer1 should renew the lock to continue, and Consumer2 should still not see the message.
- At 1:10, Consumer1 did not print the renew log and continue BUT Consumer2 picked the message up!
- Then at 1:16, Consumer1 showed "Cannot process the disposition request to set the state as 'Accepted{}' for the delivery with delivery tag (id) '***********. Reason: Unable to look up the delivery for the delivery tag as the link is closed." error message

I am using @ServiceBusListener(destination = "${queue_name}") **Spring Messaging Azure Service Bus** within SpringBoot and I referred it from https://learn.microsoft.com/en-us/azure/developer/java/spring-framework/spring-messaging-support

Thanks for the reading.

**Comment by anuchandy** [comment]
Hi @kensinzl, the default lock renewal duration is 5 minutes. The azure-messaging-servicebus has a task running to renew the lock before it expires, and the task by default runs for 5 minutes then this task is disposed.  This explains why you observe a single renewal at around the 5-minute mark and no subsequent renewals.

If the application takes 16 minutes to process a message, you should set up the lock renewal task to run for a duration that exceeds 16 minutes. 

When using ServiceBusProcessorClient in azure-messaging-servicebus library, we can configure the lock renewal task duration using `maxAutoLockRenewDuration(Duration.ofMinutes(17))` API in the builder. More details on maxautolockrenewduration API can be found [here](https://learn.microsoft.com/en-us/java/api/com.azure.messaging.servicebus.servicebusclientbuilder.servicebusreceiverclientbuilder?view=azure-java-stable#com-azure-messaging-servicebus-servicebusclientbuilder-servicebusreceiverclientbuilder-maxautolockrenewduration(java-time-duration))

If you’re using Spring library (i.e., not azure-messaging-servicebus directly), then lock duration can be set through the Spring configuration property `spring.cloud.azure.servicebus.consumer.max-auto-lock-renew-duration`. More details on Service Bus Spring configuration can be found [here](https://learn.microsoft.com/en-us/azure/developer/java/spring-framework/configuration-properties-azure-service-bus)

The common application usage patterns that lead to lock-lost error can be found [here](https://learn.microsoft.com/en-us/azure/developer/java/sdk/troubleshooting-messaging-service-bus-overview#message-or-session-lock-is-lost)

**Comment by kensinzl** [comment]
@anuchandy 

Thank you so much for the response.

```
If the application takes 16 minutes to process a message, you should set up the lock renewal task to run for a duration that exceeds 16 minutes.

When using ServiceBusProcessorClient in azure-messaging-servicebus library, we can configure the lock renewal task duration using maxAutoLockRenewDuration(Duration.ofMinutes(17)) API in the builder. More details on maxautolockrenewduration API can be found [here](https://learn.microsoft.com/en-us/java/api/com.azure.messaging.servicebus.servicebusclientbuilder.servicebusreceiverclientbuilder?view=azure-java-stable#com-azure-messaging-servicebus-servicebusclientbuilder-servicebusreceiverclientbuilder-maxautolockrenewduration(java-time-duration))
```
=> **Now I tried the following way, then can work which can overwrite the Azure Portal max 5 mins**
```
    @Bean
    public PropertiesSupplier<ConsumerIdentifier, ProcessorProperties> propertiesSupplier() {
        return key -> {
            ProcessorProperties processorProperties = new ProcessorProperties();
           processorProperties.setMaxAutoLockRenewDuration(Duration.ofMinutes(17));
            return processorProperties;
        };
    }
```

`If you’re using Spring library (i.e., not azure-messaging-servicebus directly), then lock duration can be set through the Spring configuration property spring.cloud.azure.servicebus.consumer.max-auto-lock-renew-duration. More details on Service Bus Spring configuration can be found [here](https://learn.microsoft.com/en-us/azure/developer/java/spring-framework/configuration-properties-azure-service-bus)`
=> **I tried this, but it does not work. I means if I configure 17 mins, but still 5 mins**

`The common application usage patterns that lead to lock-lost error can be found [here](https://learn.microsoft.com/en-us/azure/developer/java/sdk/troubleshooting-messaging-service-bus-overview#message-or-session-lock-is-lost)`
=> **After reading, I think I should use Receive_And_Delete mode**

Once again, thanks so much.

**Comment by anuchandy** [comment]
Using PeekLock vs ReceiveAndDelete depends on the application use case. I suggest referring documentation https://learn.microsoft.com/en-us/azure/service-bus-messaging/message-transfers-locks-settlement#settling-receive-operations if not already. 

Now that the original question is answered and we're able to override the renewal duration, I'll go ahead and close this. thanks!
