### ISSUE TITLE
[BUG] A message spends one minute in a servicebus queue

### ISSUE THREAD

**Issue by gataricd** [Azure/azure-sdk-for-java#41578]
**Describe the bug**
It happens from time to time that some message stays in a servicebus queue exactly one minute before it is consumed. We don't see any obvious reason for this. It might be related to timeouts. Is there any explanation for this?

***Exception or Stack Trace***
There is no exception or stack trace available.

**To Reproduce**
I was not able to reproduce this bug locally. It happens only during the application usage in an AKS.

***Code Snippet***
The code used for service bus to configure it:
```
val processorClient: ServiceBusProcessorClient = ServiceBusClientBuilder()
            .credential(serviceBusFullyQualifiedName, DefaultAzureCredentialBuilder().build())
            .processor()
            .queueName(queueName)
            .processMessage(handler)
            .processError { context -> processError(context) }
            .maxConcurrentCalls(10)
            .disableAutoComplete()
            .maxAutoLockRenewDuration(Duration.ZERO)
            .prefetchCount(0)
            .buildProcessorClient()
processorClient.start()
```

**Expected behavior**
I expected a message to be consumed within a second.

**Screenshots**
<img width="1355" alt="Bildschirmfoto 2024-08-21 um 10 23 05" src="https://github.com/user-attachments/assets/b980d2e2-4e16-4a03-8c70-eae928302308">

**Setup (please complete the following information):**
 - OS: Linux
 - Library/Libraries: com.azure:azure-messaging-servicebus:7.17.1
 - Java version: 21
 - App Server/Environment: AKS
 - Frameworks: Sprint Boot

**Comment by gataricd** [comment]
It was in the end not related to the service bus.

**Comment by anuchandy** [comment]
Hi @gataricd, happy to hear you fixed the issue. 

Was it related to CPU/memory limits or thread-pool sizes in pods? If you believe others might face similar problems, appreciate it if you could leave a brief comment. If it was just an application or monitoring glitch or error, feel free to disregard this request. Thanks!
