### ISSUE TITLE
[FEATURE REQ] [OpenAI] Need to add new properties for structured output

### ISSUE THREAD

**Issue by junan-trustarc** [Azure/azure-sdk-for-java#41655]
**Is your feature request related to a problem? Please describe.**
Open AI introduced Structured Output in early August, I was waiting for this update in azure openai SDK but I don't see any updates yet.
https://openai.com/index/introducing-structured-outputs-in-the-api/

**Describe the solution you'd like**
need to add new properties based on above new feature.

**Describe alternatives you've considered**
Another suggestion, maybe we can pass some kind of additional JSON or MAP separately so that we can pass some properties which is not in OptionClass until waiting for SDK to be updated.

**Information Checklist**
Kindly make sure that you have added all the following information above and checkoff the required fields otherwise we will treat the issuer as an incomplete report
- [O] Description Added
- [O] Expected solution specified

**Comment by mssfang** [comment]
@junan-trustarc Thank you for reaching out to us.
The `azure-ai-openai` SDK supports both Azure OpenAI and OpenAI services. Azure OpenAI service is working on support the structured output feature and we (as SDK team) are waiting to have a finalized REST API spec for Azure OpenAI service. As I know, current ETA to support the "structured output" feature is in a new service API version, 2024-09-01-preview.

**Comment by langchain4j** [comment]
Hi @mssfang, any news regarding structured outputs? Thanks!

**Comment by mssfang** [comment]
@langchain4j We are trying to get it out next few days.

**Comment by javiergarciapleo** [comment]
@mssfang any update on the changes?

**Comment by mssfang** [comment]
https://repo1.maven.org/maven2/com/azure/azure-ai-openai/1.0.0-beta.12/

A new beta version 12 is out now which includes the structure outputs feature in service API version 2024-08-01-preview
