### ISSUE TITLE
[FEATURE REQ] Jdbc connection with mfa

### ISSUE THREAD

**Issue by pertinjur** [Azure/azure-sdk-for-java#41668]
We need jdbc connection string with authentication type as MFA for one of the server.
we are unable to read data using SQL account due to view level security.

Jdbc connection with mfa - TrackingID#2407290040013489

```[tasklist]
### Tasks
```

**Comment by joshfree** [comment]
Hi @pertinjur could you share more details on the Azure SDK that you're using and the code that is not working for you?

If this is urgent, you may wish to file an Azure support ticket : https://github.com/Azure/azure-sdk-for-java/blob/main/SUPPORT.md#azure-support-tickets
