### ISSUE TITLE
Potential security vulnerability with 12.14 azure-storage-blob package reported.

### ISSUE THREAD

**Issue by VigneshB-Microsoft** [Azure/azure-sdk-for-java#41692]
Potential security vulnerability with 12.14 azure-storage-blob package reported. More details will be added below.

**Comment by kyleknap** [comment]
Per our [security policy](https://github.com/Azure/azure-sdk-for-java/blob/main/SECURITY.md), please do not report security vulnerabilities through public GitHub issues. Follow the instructions in the policy instead.
