### ISSUE TITLE
pom.management.xml does not generate aggregated javadocs

### ISSUE THREAD

**Issue by scbedd** [Azure/azure-sdk-for-java#4171]
**Repro in powershell:**
`mvn -DskipTests '-Dgpg.skip=true' '-Dinclude-non-shipping-modules' site:site -f pom.management.xml`

**Expected behavior:**
We expect `<repo root>/target/site/apiDocs ` folder to be generated with the maven site.

Instead, we get the maven site, but no api docs generated.

Srikanta did confirm that is this somewhat expected:

```
[2:10 AM] Srikanta Nagaraja
    when you run the above command you should see javadocs at <path-to-repo>/profiles/2018-03-01-hybrid/azure/target/apidocs/index.html
​[2:11 AM] Srikanta Nagaraja
    pom.management.xml has just one module and the javadoc is not setup properly to generate reporting at the root level. Instead, it generates the docs at the module level.
```

However, when I look in that location, it's just the maven site again. Still no refdocs.

![image](https://user-images.githubusercontent.com/45376673/60304138-6030e900-98ed-11e9-9186-814104942d4c.png)

**Comment by kurtzeborn** [comment]
@zikalino, This is an issue with management plane reference docs generation in Java.  Who in Shanghai is working on this currently.  Could you assign this to the appropriate person for follow up.

CC: @yaohaizh

**Comment by yaohaizh** [comment]
Hi @iscai-msft , do you know the issue here by any change? Thanks a lot

**Comment by alzimmermsft** [comment]
Given that this POM doesn't exist anymore, and hasn't for a while, I'm going to close this
