### ISSUE TITLE
[BUG] Spark streaming job consuming Cosmos CDC could stuck at `planInputPartitions`

### ISSUE THREAD

**Issue by sunchao** [Azure/azure-sdk-for-java#41727]
**Describe the bug**
Internally we have a pretty big Cosmos table. When we are trying to use a Spark 3.5 streaming job to consume the change feed stream from it, the job is stuck at `planInputPartitions` for a very long time, like 20+ minutes. Looking at the stacktrace, most of the time it is busy deserializing JSON.

***Exception or Stack Trace***
```
app//azure_cosmos_spark.com.fasterxml.jackson.databind.deser.std.BaseNodeDeserializer._deserializeContainerNoRecursion(JsonNodeDeserializer.java:539)
app//azure_cosmos_spark.com.fasterxml.jackson.databind.deser.std.JsonNodeDeserializer.deserialize(JsonNodeDeserializer.java:100)
app//azure_cosmos_spark.com.fasterxml.jackson.databind.deser.std.JsonNodeDeserializer.deserialize(JsonNodeDeserializer.java:25)
app//azure_cosmos_spark.com.fasterxml.jackson.databind.deser.DefaultDeserializationContext.readRootValue(DefaultDeserializationContext.java:323)
app//azure_cosmos_spark.com.fasterxml.jackson.databind.ObjectMapper._readValue(ObjectMapper.java:4801)
app//azure_cosmos_spark.com.fasterxml.jackson.databind.ObjectMapper.readTree(ObjectMapper.java:3084)
app//azure_cosmos_spark.com.azure.cosmos.implementation.changefeed.common.ChangeFeedStateDeserializer.deserialize(ChangeFeedStateDeserializer.java:39)
app//azure_cosmos_spark.com.azure.cosmos.implementation.changefeed.common.ChangeFeedStateDeserializer.deserialize(ChangeFeedStateDeserializer.java:22)
app//azure_cosmos_spark.com.fasterxml.jackson.databind.deser.DefaultDeserializationContext.readRootValue(DefaultDeserializationContext.java:323)
app//azure_cosmos_spark.com.fasterxml.jackson.databind.ObjectMapper._readMapAndClose(ObjectMapper.java:4825)
app//azure_cosmos_spark.com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:3772)
app//azure_cosmos_spark.com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:3740)
app//azure_cosmos_spark.com.azure.cosmos.implementation.changefeed.common.ChangeFeedState.fromString(ChangeFeedState.java:65)
app//azure_cosmos_spark.com.azure.cosmos.implementation.SparkBridgeImplementationInternal$.extractChangeFeedStateForRange(SparkBridgeImplementationInternal.scala:179)
app//com.azure.cosmos.spark.ChangeFeedMicroBatchStream.$anonfun$planInputPartitions$7(ChangeFeedMicroBatchStream.scala:107)
app//com.azure.cosmos.spark.ChangeFeedMicroBatchStream$$Lambda$4051/0x00007f3e1168d600.apply(Unknown Source)
app//scala.collection.TraversableLike.$anonfun$map$1(TraversableLike.scala:286)
app//scala.collection.TraversableLike$$Lambda$135/0x00007f3e101ff358.apply(Unknown Source)
app//scala.collection.IndexedSeqOptimized.foreach(IndexedSeqOptimized.scala:36)
app//scala.collection.IndexedSeqOptimized.foreach$(IndexedSeqOptimized.scala:33)
app//scala.collection.mutable.ArrayOps$ofRef.foreach(ArrayOps.scala:198)
app//scala.collection.TraversableLike.map(TraversableLike.scala:286)
app//scala.collection.TraversableLike.map$(TraversableLike.scala:279)
app//scala.collection.mutable.ArrayOps$ofRef.map(ArrayOps.scala:198)
app//com.azure.cosmos.spark.ChangeFeedMicroBatchStream.planInputPartitions(ChangeFeedMicroBatchStream.scala:104)
```

**To Reproduce**

***Code Snippet***

It is something like:
```python
df_change_feed = (
  spark
  .readStream
  .format("cosmos.oltp.changeFeed")
  .options(**cosmos_change_feed_config)
  .load()
)

query = (
  df_change_feed.writeStream.format("delta")
  .outputMode("append")
  .option("checkpointLocation", "<checkpoint-loc>")
  .start("<output-loc>")
)
```
 
**Expected behavior**
The `planInputPartitions` should be relatively fast.

**Screenshots**

**Setup (please complete the following information):**
 - IDE: [e.g. IntelliJ]
 - Library/Libraries: [e.g. com.azure:azure-core:1.16.0 (groupId:artifactId:version)]
 - Java version: [e.g. 8] 
 - App Server/Environment: [e.g. Tomcat, WildFly, Azure Function, Apache Spark, Databricks, IDE plugin or anything special]
 - Frameworks: [e.g. Spring Boot, Micronaut, Quarkus, etc] 

If you suspect a dependency version mismatch (e.g. you see `NoClassDefFoundError`, `NoSuchMethodError` or similar), please check out [Troubleshoot dependency version conflict article](https://aka.ms/azsdk/java/dependency/troubleshoot) first. If it doesn't provide solution for the problem, please provide:
- verbose dependency tree (`mvn dependency:tree -Dverbose`)
- exception message, full stack trace, and any available logs

**Additional context**

**Information Checklist**
Kindly make sure that you have added all the following information above and checkoff the required fields otherwise we will treat the issuer as an incomplete report
- [ ] Bug Description Added
- [ ] Repro Steps Added
- [ ] Setup information Added

**Comment by kushagraThapar** [comment]
@sunchao the azure-core version you have mentioned is pretty old (2021), I am curious what's the spark connector version you are using? Are you on the latest version?

**Comment by sunchao** [comment]
Thanks for the quick response @kushagraThapar ! Yes I'm using the latest 4.33.1 Spark connector: https://mvnrepository.com/artifact/com.azure.cosmos.spark/azure-cosmos-spark_3-5_2-12/4.33.1.

**Comment by kushagraThapar** [comment]
Would it be possible to provide the executor logs? How are you identifying the time based on the stack trace?

**Comment by zshao9** [comment]
@kushagraThapar can we take a look at the latest code in azure-core regarding the stacktrace above?  I wonder if that piece of code has been updated or is still the same as 2021.

**Comment by zshao9** [comment]
Also as a matter of fact, fasterxml.jackson is very slow.  There are a lot of faster options.  I wonder if we can make the JSON parser pluggable in the Azure SDK code so that we can use our more efficient solution when and if needed (For example, https://github.com/simdjson/simdjson-java )

**Comment by kushagraThapar** [comment]
@zshao9 I wonder why we think the stacktrace is coming from azure-core? and not azure-cosmos-spark connector?

**Comment by sunchao** [comment]
> Would it be possible to provide the executor logs? How are you identifying the time based on the stack trace?

@kushagraThapar this is from the Spark driver actually, and there is no log when it is stuck at `planInputPartitions`. I identified this via "poor-man's profiling": keep refreshing the Spark UI driver "Thread Dump" page and it almost always shows the JSON deserialization code path in the stacktrace.

**Comment by sunchao** [comment]
@kushagraThapar let me know if you have more insights on this issue, thanks. cc @FabianMeiswinkel too.

**Comment by kushagraThapar** [comment]
@sunchao we are investigating this actively and will provide an update soon!

**Comment by kushagraThapar** [comment]
@zshao9 the serializer is customizable in latest versions of azure-cosmos SDK. We discussed this internally, and to proceed and investigate this better, we will need to access the spark driver + executor logs. It will be best to proceed on this through an Azure support case instead of github issue so we can protect your privacy from logs point of view.

I will close this issue here, feel free to reach out to our support team and we will engage through that channel.
