### ISSUE TITLE
ServiceBusReceiverAsyncClient Keep forever opened without errors

### ISSUE THREAD

**Issue by josebarros2025** [Azure/azure-sdk-for-java#41828]
**Query/Question**
Our prod env experiences annyoing errors like bellow, reading the specification, I see they are supposing the app must close the receiver, which doesnt make sense since a Spring boot application doesnt have an end, it always should be listening to new messages.

`reactor.core.Exceptions$ErrorCallbackNotImplemented: com.azure.core.amqp.exception.AmqpException: onSessionRemoteClose connectionId[xxxxx], entityName[xxxx] condition[Error{condition=amqp:connection:forced, description='The connection was closed by container 'xxxx' because it did not have any active links in the past 300000 milliseconds. TrackingId:xxxx, SystemTracker:gateway10, Timestamp:2024-09-12T10:02:53', info=null}], errorContext[NAMESPACE: sb-shop-dev-in-01.servicebus.windows.net. ERROR CONTEXT: N/A, PATH: QUEUE_NAME]`

***Why is this not a Bug or a feature Request?***
A clear explanation of why is this not a bug or a feature request?
The official docs won't provide real world examples on how to use the service bus client for applications like that.

**Setup (please complete the following information if applicable):**
 - OS: Any/ALL
 - IDE:  IntelliJ / NA
 - Library/Libraries: com.azure:azure-messaging-servicebus:7.17.0
 
 **Information Checklist**
 Kindly make sure that you have added all the following information above and checkoff the required fields otherwise we will treat the issuer as an incomplete report
- [X ] Query Added
- [X ] Setup information Added

**Comment by anuchandy** [comment]
Hi @josebarros2025, we've updated the library avoid this error log in this [pull request](https://github.com/Azure/azure-sdk-for-java/pull/41641). I see your related comment in the [issue](https://github.com/Azure/azure-sdk-for-java/issues/41736), the discussed NPE as a result of session disconnect is also addressed via this [pull request](https://github.com/Azure/azure-sdk-for-java/pull/39107).  Both of these changes are slated for September release which should happen in 1-2 weeks.

**Comment by anuchandy** [comment]
Hello @josebarros2025, it looks like you’re closely monitoring a similar issue, 41736: https://github.com/Azure/azure-sdk-for-java/issues/41736#issuecomment-2382478328. Based on your comment, it appears you'll need to wait for the spring-cloud-azure-starter release. 

I notice you've switched from `ServiceBusReceiverAsyncClient` to `ServiceBusProcessorClient`, which I wanted to originally suggest. The use of `ServiceBusReceiverAsyncClient` is generally discouraged considering the complexity it brings to the application - https://github.com/Azure/azure-sdk-for-java/blob/main/sdk/servicebus/azure-messaging-servicebus/README.md#when-to-use-servicebusprocessorclient

**Comment by anuchandy** [comment]
Hi @josebarros2025, based on your comment in the other thread, it appears you have managed to resolve the conflicts in Spring and could set the versions - service bus at 7.14.4, azure-core-amqp at 2.9.9, and azure-core at 1.52.0.
 
Copying your solution here as a reference for anyone who encounters it.

```xml
<azure.servicebus.version>7.17.4</azure.servicebus.version>

<dependency>
            <groupId>com.azure.spring</groupId>
            <artifactId>spring-cloud-azure-starter</artifactId>
            <version>${azure.version}</version>
            <exclusions>
                <exclusion>
                    <groupId>com.azure</groupId>
                    <artifactId>azure-core</artifactId>
                </exclusion>
                <exclusion>
                    <groupId>com.azure</groupId>
                    <artifactId>azure-core-amqp</artifactId>
                </exclusion>
            </exclusions>
        </dependency>
        <dependency>
            <groupId>com.azure</groupId>
            <artifactId>azure-core</artifactId>
            <version>1.52.0</version>
            <scope>compile</scope>
        </dependency>
        <dependency>
            <groupId>com.azure</groupId>
            <artifactId>azure-core-amqp</artifactId>
            <version>2.9.9</version>
            <scope>compile</scope>
        </dependency>
```

I’ll go ahead and close this. Thanks!
