### ISSUE TITLE
[BUG]Azure Blob storage api is throwing BlobNotFound exception in file delete method.

### ISSUE THREAD

**Issue by amokhalg** [Azure/azure-sdk-for-java#41834]
**Describe the bug**
We have a Azure Synapse connector use polybase structure which uses Azure Blob storage to stage data. In one of customer's environment they are getting **BlobNotFound** exception intermittently while deleting those staged files. We have raised a ticket to Microsoft about this and in they checked the telemetry in which we found that there are 2 delete requests sent for same resource, first is succeed and 2nd failed with this exception. There is no retry logic applied in our code for this, and we are unable to identify from where this 2nd request got generated, we can see in telemetry that there is different correlationId but the request header is same. We are looping on staged directory we are not calling the delete again on same resource.
There might be a possibility that network is creating a 2nd request since previous request didn't send the response  due to delay. One common observation is that 2nd request always triggered between 10-12 seconds after first request is sent.
We are using **azure-storage-blob-12.21.0.jar** api.

***Exception or Stack Trace***
There is no whole stack trace just below exception we got.
**Status code 404, <?xml version="1.0" encoding="utf-8"?><Error><Code>BlobNotFound</Code><Message>The specified blob does not exist.**

**To Reproduce**
The error is intermittent we have no direct way to reproduce it, we are running a ETL mapping in Informatica's IDMC.
This is happening when we are done with the Polybase execution and cleaning up the staged data in Azure Blob Storage. 

***Code Snippet***
This Azure SDK's internal code not our application code which is deleing the file. Our application code is just calling this api.

```java
String connectionString = "BlobEndpoint=https://<ACCOUNT_NAME>.blob.core.windows.net;DefaultEndpointsProtocol=https;AccountName=<ACCOUNT_NAME>;AccountKey=<ACCOUNT_KEY>";
HttpClient httpClient = getHttpClient();
BlobServiceClientBuilder builder = new BlobServiceClientBuilder();
builder.httpClient(httpClient);
BlobServiceClient serviceClient = builder.connectionString(connectionString).buildClient();
BlobContainerClient containerClient = serviceClient.getBlobContainerClient(containerName);
for (BlobItem blob : containerClient.listBlobs(option, null)) {
	BlobClient blobClient = containerClient.getBlobClient(blob.getName());
	blobClient.deleteWithResponse(DeleteSnapshotsOptionType.INCLUDE, null, null, null);
}
```

**Expected behavior**
Expectation here is that file must be deleted without any issue.

**Screenshots**
Telemetry shared by Microsoft support.
![DeleteIssue](https://github.com/user-attachments/assets/9c07ee60-b109-40e8-b715-cdc59c72a313)

**Comment by skbmithur** [comment]
Any update on this. At least we would like to know there is any default retry implemented in storage blob SDK? Then we can override and delay retry so that 2nd delete call may not trigger.

**Comment by ibrandes** [comment]
Hi @skbmithur and @amokhalg,

Please use this method, [deleteIfExistsWithResponse](https://github.com/Azure/azure-sdk-for-java/blob/main/sdk/storage/azure-storage-blob/src/main/java/com/azure/storage/blob/specialized/BlobClientBase.java#L1377), instead. If the issue persists, please let us know. 

Thanks,
Isabelle
