### ISSUE TITLE
Support unreleased versions in Spring compatibility-tests pipeline

### ISSUE THREAD

**Issue by anuchandy** [Azure/azure-sdk-for-java#41870]
The Spring compatibility-tests pipeline does not support unreleased versions. This is needed if some of the Azure libraries that Spring uses go through changes, and we want to validate those changes works correctly for Spring use cases before release.

Here is an example of [PR](https://github.com/Azure/azure-sdk-for-java/pull/41845) that was failing when trying to run our Spring tests with unreleased versions of Service bus and Event Hubs.

Supporting unreleased requires copying existing logic for the `From Source pipeline runs` where it looks for unreleased dependencies.

Hi @saragluna, could you please help to triage?

**Comment by saragluna** [comment]
@anuchandy thanks for bringing this up. If we enable this logic in our compatibility-tests, does it mean some jobs will still fail (the ones using the released versions), but the ones using the unreleased version will pass?

**Comment by anuchandy** [comment]
Hi @saragluna, thanks for taking a look. The change simply allows our Spring tests to run using SB/EH/Core/* in _main_ when instructed to do so by annotating with `unreleased_com.azure`. Once those are released, the spring poms will get updated to refer the same from maven. If we don't have any potential change to test, the dependencies will continue to be referenced from Maven as they are currently.

**Comment by saragluna** [comment]
@anuchandy, okay got it. We will add one entry for it in our compatibility tests.

**Comment by Netyyyy** [comment]
Fixed in https://github.com/Azure/azure-sdk-for-java/pull/42025
