### ISSUE TITLE
Create a CosmosClient fails, because of the usage of deprecated field of jackson.core in Utils.java

### ISSUE THREAD

**Issue by srasp** [Azure/azure-sdk-for-java#41884]
**Describe the bug**
I have included azure-cosmos 4.63.3 into my project and wanted to create a simple Cosmos Client.
It fails, because it references as dependency jackson.core 2.17.2, where JsonParser.Feature.ALLOW_TRAILING_COMMA as been deprecated since 2.10.0. This results in a NoSuchFieldError exception thrown in com.azure.cosmos.implementation.Utils, because mentioned field is used in line 113.

***Exception or Stack Trace***
Caused by: java.lang.NoSuchFieldError: ALLOW_TRAILING_COMMA
	at com.azure.cosmos.implementation.Utils.createAndInitializeObjectMapper(Utils.java:113)
	at com.azure.cosmos.implementation.Utils.<clinit>(Utils.java:74)
	at com.azure.cosmos.implementation.CosmosMicrometerMetricsConfig.toJson(CosmosMicrometerMetricsConfig.java:47)
	at com.azure.cosmos.implementation.Configs.<clinit>(Configs.java:218)
	at com.azure.cosmos.CosmosClientBuilder.<init>(CosmosClientBuilder.java:120)
	at com.custom.azure.CosmosDBUpdater.init(CosmosDBUpdater.java:17)
	... 49 more

**To Reproduce**
Try to create a simple Cosmos Client, this will throw the exception
client = new CosmosClientBuilder()
			    .endpoint(serviceEndpoint)
			    .key(key)
			    .buildClient();

***Code Snippet***
`private static ObjectMapper createAndInitializeObjectMapper(boolean allowDuplicateProperties) {
        ObjectMapper objectMapper = new ObjectMapper();
        objectMapper.configure(DeserializationFeature.FAIL_ON_UNKNOWN_PROPERTIES, false);
        objectMapper.configure(JsonParser.Feature.ALLOW_SINGLE_QUOTES, true);
        objectMapper.configure(JsonParser.Feature.ALLOW_TRAILING_COMMA, true);
        if (!allowDuplicateProperties) {
            objectMapper.configure(JsonParser.Feature.STRICT_DUPLICATE_DETECTION, true);
        }
        objectMapper.configure(DeserializationFeature.ACCEPT_FLOAT_AS_INT, false);
        tryToLoadJacksonPerformanceLibrary(objectMapper);
        objectMapper.registerModule(new JavaTimeModule());
        return objectMapper;
}`

**Expected behavior**
No exception

**Setup (please complete the following information):**
 - IDE: eclipse
 - Library/Libraries: com.azure:azure-core:4.63.3
 - Java version: 8 
 - App Server/Environment: IDE

**Information Checklist**
Kindly make sure that you have added all the following information above and checkoff the required fields otherwise we will treat the issuer as an incomplete report
- [x] Bug Description Added
- [x] Repro Steps Added
- [x] Setup information Added

**Comment by srasp** [comment]
@kushagraThapar Thank you for the hint and sorry for making noise where its wrong. You are right an older version of jackson library (2.2.2) gets loaded prior to mine. Try to find a workaround.
Thanks again!

**Comment by srasp** [comment]
Issue is caused by an older version of jackson library loaded prior to the necessary one in the local application.

**Comment by kushagraThapar** [comment]
@srasp - no worries, glad we found the issue :)
