### ISSUE TITLE
Do Azure SDK for Java  support ReceiveAndDelete mode in the Azure client builder for Receiver Client to receive messages from Sessions based Queues/Topics.

### ISSUE THREAD

**Issue by snarlagi-tibco** [Azure/azure-sdk-for-java#41881]
**Query/Question**
**Do Azure SDK for Java  support ReceiveAndDelete mode in the Azure client builder for Receiver Client to receive messages from Sessions based Queues/Topics.**

***Why is this not a Bug or a feature Request?***
A clear explanation of why is this not a bug or a feature request?
**We are not sure if it is a bug . But from the microsoft documentation we are not clear if ReceiveAndDelete mode applicable for Azure Client Receiver in Java to receive messages from Sessions based Queues/Topics.
From the ticket https://github.com/Azure/azure-sdk-for-js/issues/1019 , ReceiveAndDelete mode with Sessions Queues/Topics is supported in azure-sdk-for-js (JavaScript SDK) .

I need clarity if  azure-sdk-for-java SDK  as well supports ReceiveAndDelete mode with both Sessions Queues/Topics  and not Non-Sessions Queues/Topics   **

**Setup (please complete the following information if applicable):**
 - IDE: [e.g. IntelliJ]
 - Library/Libraries: [e.g. com.azure:azure-core:1.16.0 (groupId:artifactId:version)]
 - 
 - **I'm using azure-messaging-servicebus-7.13.2. jar , azure-core-1.35.0**
 
 **Information Checklist**
 Kindly make sure that you have added all the following information above and checkoff the required fields otherwise we will treat the issuer as an incomplete report
- [* ] Query Added
- [* ] Setup information Added

**Comment by anuchandy** [comment]
Closing given the question is answered.
