### ISSUE TITLE
service bus configuration configureWithConnectionString has an extra parameter configuration

### ISSUE THREAD

**Issue by gcheng** [Azure/azure-sdk-for-java#419]
With connection string, it doesn't make sense to allow a configuration to be passed as an input parameter. 

```
public static Configuration configureWithConnectionString(String profile, Configuration configuration,
    String connectionString) 
```

it just need profile and connectionString, two parameters should be enough.

**Comment by solvingJ** [comment]
Sorry to be late, but why is this obsolete?
