### ISSUE TITLE
[QUERY] Can we trigger a WebJob from another WebJob using Azure SDK for Java?

### ISSUE THREAD

**Issue by isuruwarn** [Azure/azure-sdk-for-java#4195]
**Query/Question**
Is it possible to trigger a WebJob from another WebJob, using the Azure SDK for Java (without having to make HTTP calls to the WebJobs REST API)?

***Why is this not a Bug or a feature Request?***
A clear explanation of why is this not a bug or a feature request?

**Setup (please complete the following information if applicable):**
 - OS: MacOS, Windows, Linux
 - IDE : Eclipse,. IntelliJ
 - Version of the Library used: -
 
 **Information Checklist**
- [x] Query Added
- [x] Setup information Added

**Comment by mozehgir** [comment]
@isuruwarn - thanks for your question. We have routed your issue to the App Services team to answer your question.

**Comment by yungezz** [comment]
hi @weidongxu-microsoft is this doable now? does service support it?

**Comment by weidongxu-microsoft** [comment]
kudu api should able to trigger it.

https://github.com/projectkudu/kudu/wiki/WebJobs-API#invoke-a-triggered-job
