### ISSUE TITLE
Message acknowledgement process taking long time

### ISSUE THREAD

**Issue by yogisinha** [Azure/azure-sdk-for-java#41967]
**Query/Question**
We use the java sdk to consume the messages from Azure service bus. We use the async client. We are seeing issue in msg acks which is resulting in re-deliveries of messages.

1. When we read the messages, we complete each message passing the transaction context and store the Mono returned in a list. 
2. Later when we store those message in our own system (we need to store them for business requirements), we finally execute those Mono refs and do the commitTransaction on the receiver object.
3. The recent problem we are facing is that executing those Mono refs and final commitTransaction step is taking long time and we are not able to close the client because we have a timeout for that whole operation. So here we don't know which operation between  **a.** executing those Monos and **b.** commitTransaction  is taking long. Or both are contributing to the slowness. I don't know if earlier occurrences of not being able to close the clients and presence of lot of msgs read but not acked properly is exacerbating the situation and due to which msg acks are taking longer and longer.
5. Before this issue we faced some java OutOfMemory errors and msgs were not acks properly, clients were not closed properly. 
6. Is that backlog of msgs read but not acked properly can be causing this ?  Do we need to set retry options, any changes in lock renewal duration settings, upgrading to new version of library ? Can we ask our vendor to check on something, if yes what should we ask ? 

Please help if you have any guidance in this situation

Creating the async client

```
        this.asyncReceiver = new ServiceBusClientBuilder()
                .configuration(connectionOptions.getConfiguration())
                .connectionString(connectionOptions.getConnectionString())
                .receiver()
                .topicName(connectionOptions.getTopicName())
                .subscriptionName(connectionOptions.getSubscriptionName())
                .prefetchCount(connectionOptions.getPrefetchCount())
                //In this mode, received message is not deleted from the queue or subscription,
                // instead it is temporarily locked to the receiver, making it invisible to other receivers.
                // Then the service waits for one of the three events
                .receiveMode(ServiceBusReceiveMode.PEEK_LOCK)
                .disableAutoComplete()
                .buildAsyncClient();

        this.transactionContext = asyncReceiver.createTransaction().block();

```

We acquire the messages and complete each message as we receive them, and store the Mono in a list

```
public void acquire() throws InterruptedException {

        asyncReceiver.receiveMessages()
                .subscribe(new BaseSubscriber<ServiceBusReceivedMessage>() {
                    @Override
                    protected void hookOnSubscribe(Subscription subscription) {
                        log.info("Activating subscription");
                        SubscriptionMessages.this.subscription = subscription;
                        request(requestCount);
                    }

                    @Override
                    protected void hookOnNext(ServiceBusReceivedMessage message) {
                        serviceBusReceivedMessages.add(message);
                        if (timer.hasExpired())
                            return;

                        timer.incrementConsumptionCount();
                        messageAcks.add(asyncReceiver.complete(message, new CompleteOptions().setTransactionContext(transactionContext)));
                        if (timer.requireNextBatchOfMessages(requestCount)) {
                            log.info("*** Requesting next {} msgs...", requestCount);
                            request(requestCount);
                        }
                    }

                    @Override
                    protected void hookOnError(Throwable throwable) {
                        acquisitionError.set(throwable);
                    }
                });

}
```

Finally in a separate method we commit the transaction

```
    public void acknowledge() throws MessageAcknowledgementException {

        final long maxAckWaitTime = connectionOptions.getMaxAckWaitTime();

        CountDownLatch completionLatch = new CountDownLatch(1);
        Mono.when(messageAcks)  // this the messageAcks list where we store the Mono returned by complete call in acquire method above.
                .then(this.asyncReceiver.commitTransaction(this.transactionContext))
                .subscribe(
                        data -> log.info("Data: {}", data), // onNext
                        err -> log.error("Error: ", err),  // onError
                        () -> { // onComplete
                            log.info("Completed!");
                            log.info("Closing Async client...");
                            asyncReceiver.close();
                            log.info("Async client closed.");
                            completionLatch.countDown();
                        }
                );

       // We wait for above process for some time. above Mono.when process runs in separate thread
        try {
            completionLatch.await(maxAckWaitTime, TimeUnit.SECONDS);
        } catch (InterruptedException e) {
            throw new RuntimeException(e);
        }

    }
```

Volume

***Why is this not a Bug or a feature Request?***
We are facing this issue recently and as I explained above it was working fine before and only recently we are seeing the issue.

**Setup (please complete the following information if applicable):**
 - OS: Linux, Kubernetes

 - Library/Libraries: 

```
        <dependency>
            <groupId>com.azure</groupId>
            <artifactId>azure-core</artifactId>
            <version>1.35.0</version>
        </dependency>
        <dependency>
            <groupId>com.azure</groupId>
            <artifactId>azure-messaging-servicebus</artifactId>
            <version>7.13.1</version>
        </dependency>
        <dependency>
            <groupId>io.projectreactor</groupId>
            <artifactId>reactor-core</artifactId>
            <version>3.4.7</version>
        </dependency>
```
 
 **Information Checklist**
 Kindly make sure that you have added all the following information above and checkoff the required fields otherwise we will treat the issuer as an incomplete report
- [ ] Query Added
- [ ] Setup information Added

**Comment by joshfree** [comment]
@anuchandy could you please follow up with @yogisinha

**Comment by yogisinha** [comment]
@joshfree 

We see this error frequently when we try to complete the messages. 


```
workload 1727364743994 ERROR parallel-1 ServiceBusReactorReceiver p:|f:|c:|s: - {"az.sdk.message":"Update disposition request timed out., errorContext[NAMESPACE: coretex-integration-penske.servicebus.windows.net. ERROR CONTEXT: N/A, PATH: events-stream-medline/subscriptions/events, REFERENCE_ID: events-stream-medline/subscriptions/events_075387_1727364623656, LINK_CREDIT: 0]","exception":"Update disposition request timed out., errorContext[NAMESPACE: coretex-integration-penske.servicebus.windows.net. ERROR CONTEXT: N/A, PATH: events-stream-medline/subscriptions/events, REFERENCE_ID: events-stream-medline/subscriptions/events_075387_1727364623656, LINK_CREDIT: 0]","entityPath":"events-stream-medline/subscriptions/events","linkName":"events-stream-medline/subscriptions/events_075387_1727364623656"}  
workload 1727364743994 ERROR parallel-1 ServiceBusReactorReceiver p:|f:|c:|s: - {"az.sdk.message":"Update disposition request timed out., errorContext[NAMESPACE: coretex-integration-penske.servicebus.windows.net. ERROR CONTEXT: N/A, PATH: events-stream-medline/subscriptions/events, REFERENCE_ID: events-stream-medline/subscriptions/events_075387_1727364623656, LINK_CREDIT: 0]","exception":"Update disposition request timed out., errorContext[NAMESPACE: coretex-integration-penske.servicebus.windows.net. ERROR CONTEXT: N/A, PATH: events-stream-medline/subscriptions/events, REFERENCE_ID: events-stream-medline/subscriptions/events_075387_1727364623656, LINK_CREDIT: 0]","entityPath":"events-stream-medline/subscriptions/events","linkName":"events-stream-medline/subscriptions/events_075387_1727364623656"}  
workload 1727364743994 ERROR parallel-1 ServiceBusReactorReceiver p:|f:|c:|s: - {"az.sdk.message":"Update disposition request timed out., errorContext[NAMESPACE: coretex-integration-penske.servicebus.windows.net. ERROR CONTEXT: N/A, PATH: events-stream-medline/subscriptions/events, REFERENCE_ID: events-stream-medline/subscriptions/events_075387_1727364623656, LINK_CREDIT: 0]","exception":"Update disposition request timed out., errorContext[NAMESPACE: coretex-integration-penske.servicebus.windows.net. ERROR CONTEXT: N/A, PATH: events-stream-medline/subscriptions/events, REFERENCE_ID: events-stream-medline/subscriptions/events_075387_1727364623656, LINK_CREDIT: 0]","entityPath":"events-stream-medline/subscriptions/events","linkName":"events-stream-medline/subscriptions/events_075387_1727364623656"}  
workload 1727364743994 ERROR parallel-1 ServiceBusReactorReceiver p:|f:|c:|s: - {"az.sdk.message":"Update disposition request timed out., errorContext[NAMESPACE: coretex-integration-penske.servicebus.windows.net. ERROR CONTEXT: N/A, PATH: events-stream-medline/subscriptions/events, REFERENCE_ID: events-stream-medline/subscriptions/events_075387_1727364623656, LINK_CREDIT: 0]","exception":"Update disposition request timed out., errorContext[NAMESPACE: coretex-integration-penske.servicebus.windows.net. ERROR CONTEXT: N/A, PATH: events-stream-medline/subscriptions/events, REFERENCE_ID: events-stream-medline/subscriptions/events_075387_1727364623656, LINK_CREDIT: 0]","entityPath":"events-stream-medline/subscriptions/events","linkName":"events-stream-medline/subscriptions/events_075387_1727364623656"}  
```

In the library its happening in `cleanupWorkItems()` method in `ServiceBusReactorReceiver `class. This should get triggered on a interval of 1 minute which is `retryTimeout `from `AmqpRetryOptions`. We don't set it so it should default to 1 minute. This scheduling is happening in ServiceBusReactorReceiver constrructor :

```
public ServiceBusReactorReceiver(............) {
   this.subscription = Flux.interval(timeout).subscribe(i -> cleanupWorkItems());
}

```

But we see the above error in like 15-20 secs after we create our client object.  **Its happening too soon.** 
The javadoc for the error says that it can happen due to network or infrastructure delays. I don't understand why its triggering before 1 minute. 

Weird thing is there is logic to test timed out (**value.hasTimedout()**) updates in `cleanupWorkItems()`

```
    private void cleanupWorkItems() {
        if (pendingUpdates.isEmpty()) {
            return;
        }

        logger.verbose("Cleaning timed out update work tasks.");
        pendingUpdates.forEach((key, value) -> {
            if (value == null || !value.hasTimedout()) {
                return;
            }

            pendingUpdates.remove(key);
            final Throwable error = value.getLastException() != null
                ? value.getLastException()
                : new AmqpException(true, AmqpErrorCondition.TIMEOUT_ERROR, "Update disposition request timed out.",
                handler.getErrorContext(receiver));

            completeWorkItem(key, null, value.getSink(), error);
        });
    }
```

Do you suggest trying the completion of like fewer amt of messages, like 5-10 msgs in one cycle and watching the behavior ? 
 Shall I set a retryOptions of more than 1 min when trying to create the client ?

**Comment by anuchandy** [comment]
Hi @yogisinha, thanks for reaching out, and also for providing additional information.

Regarding your findings about `cleanupWorkItems()`, terminating complete calls was a bug in older versions, which was fixed sometime early 2023.  Also, since then, the library has undergone several releases, resolving numerous reliability issues, including an overhaul of the internal engine known as v2 engine.

Could you please upgrade to the latest version 7.17.4 and let us know if it improves the experience? 

## Update to 7.17.4 dependency

```xml
<dependency>
    <groupId>com.azure</groupId>
    <artifactId>azure-messaging-servicebus</artifactId>
    <version>7.17.4</version>
</dependency>
```
 
## Update the ServiceBusClientBuilder for "com.azure.core.amqp.cache"
When building the client use the configuration ("com.azure.core.amqp.cache"), as shown below. (Between, need for this configuration is temporary and relaxed in upcoming releases).
 
```java
new ServiceBusClientBuilder()
.connectionString(CONNECTION_STRING)
.configuration(new ConfigurationBuilder()
       .putProperty("com.azure.core.amqp.cache", "true")
       .build())
.receiver()..
```

## Ensure right transitive dependencies 

Make sure the transitive dependencies (azure-core-amqp, azure-core) are resolved to expected versions, 2.9.9 and 1.52.0 respectively. If it resolves to any version older than these core versions, then it's likely a dependency conflict in the app.

```
mvn dependency:tree
```

```
[INFO] ...
[INFO] +- com.azure:azure-messaging-servicebus:jar:7.17.4:compile
[INFO] |  +- com.azure:azure-core:jar:1.52.0:compile                               <----- azure-core:1.52.0
[INFO] |  |  +- ..
[INFO] |  |  \- ...
[INFO] |  \- com.azure:azure-core-amqp:jar:2.9.9:compile                           <----- azure-core-amqp:2.9.9
[INFO] |     +- com.microsoft.azure:qpid-proton-j-extensions:jar:1.2.5:compile
[INFO] |     \- org.apache.qpid:proton-j:jar:0.34.1:compile
```

**Comment by yogisinha** [comment]
Great. Thanks for quick help. I will try these changes.

**Comment by yogisinha** [comment]
Hi @anuchandy,
While trying to resolve the above issue we were setting reactor.schedulers.defaultBoundedElasticSize property through VM option. This is used by Schedulers.boundedElastic() . As I was reading the service bus docs, each message runs its own lock renewal task so we thought that may be VM does not have enough threads. By default, if you don't set this property, reactor uses 10 * Runtime.getRuntime().availableProcessors() as maximum size for the global boundedElastic() Scheduler. This comes out to be 40 as Runtime.getRuntime().availableProcessors() returns 4.

So for the changes you suggested, shall we keep that property because our goal is to read 1500-2000 msgs per minute from our service bus topic.

**Comment by anuchandy** [comment]
Hello @yogisinha, 

1.	For lock renewals, the library uses `Schedulers.parallel()`. These renewals occur regularly at set intervals. The number of threads in `Schedulers.parallel()` is equal to the cores in the machine, this scheduler is utilized solely to initiate the timer, and the actual renewal broker call (call to Service Bus) is handled by Connection IO-Thread. I.e., all recurring renewal requests are handled by a single IO Thread.
2.	It’s a good idea to reduce the number of recurring tasks in `Schedulers.parallel()` and broker calls. One change we could make to avoid overhead associated with timers/broker calls is, complete the message early. To avoid complexity, we could simply use `block()` -  `client.complete(message, new CompleteOptions().setTransactionContext(transactionContext)).block();`. There is no need to delay the completion until the end as the operations are scoped within a TransacationContext, and `complete` should be a quick operation so used `block`.
3.	Due to the broker end restriction (beyond the client's control), a transaction must be committed within 120 seconds of being opened. Attempts to commit after this 120-second window will result in a broker error.
4.	I would also set the `retryOptions( AmqpRetryOptions().setTryTimeout(Duration.ofSeconds(180))` in the builder, a value greater than the broker-imposed transaction timeout.
5.	The time that broker takes to commit the transaction is very likely related to the number of outstanding operations to be committed, I don’t have insight into broker internals. I would suggest limiting operations count (start with ~15-20) within the transaction scope, doing some trial runs to pick a number. Per broker documentation we can’t have more than 100 operations in a transaction.

**Comment by yogisinha** [comment]
Hi @anuchandy .
I did not understand the operation limit of 100 in a transaction in point 5.  So If I read like 1000-2000 msgs and do a early complete as you suggested in point 2, the commit transaction later won't succeed ? Please clarify your point 5. 

Does number of msg completions associated to a transaction affect the final commit transaction time proportionately Or commit transaction is independent of number of msg completions ?

And thanks for tip on prefetch count.

**Comment by anuchandy** [comment]
Hi @yogisinha, let me correct it point 5, it's the number of messages that can be sent (i.e. send operations) in a transaction is limited to 100, as per documentation. There doesn't appear to be any documented limit for other types of operations.

Regarding the question on the correlation between the number of operations and commit time, I don't see anything as documented by the Service Bus service team. From what I've gathered, it shouldn't impact premium tier, though there might be some impact for standard tier.

**Comment by yogisinha** [comment]
Hi @anuchandy ,
The changes suggested by you worked. Thanks a lot for your help. You can close this issue now.

**Comment by anuchandy** [comment]
Glad to hear this is resolved, closing the issue.
