### ISSUE TITLE
Run checkstyle in the normal build phase

### ISSUE THREAD

**Issue by billwert** [Azure/azure-sdk-for-java#42009]
In our pipelines we run `checkstyle` as a separate build step. https://github.com/Azure/azure-sdk-for-java/blob/95c5d04e7efc800ad56a7985c5a176ba4e14297a/eng/pipelines/templates/steps/run-and-validate-linting.yml#L47-L52

This doesn't take advantage of the fact that we add samples sources to the list of test sources. https://github.com/Azure/azure-sdk-for-java/blob/c948408cf37320162cf6fcaeb38e687f215a7dde/sdk/parents/azure-sdk-parent/pom.xml#L102-L113

Unfortunately we can't rig invoking `build-helper-maven-plugin` from `checkstyle:check`, so we must just add it to our normal build phase instead.

This is likely to cause some noise, so it needs to be done in stages to avoid pipeline storms.

**Comment by alzimmermsft** [comment]
Should be fixed by #42801
