### ISSUE TITLE
[FEATURE REQ] CosmosDB Spark connector support for Databricks runtime 15.*

### ISSUE THREAD

**Issue by cmollgaard** [Azure/azure-sdk-for-java#42186]
**Is your feature request related to a problem? Please describe.**
I would like the Cosmosdb connector to support Databricks runtime 15.4.
Currently only 14.* looks to be supported, but as 15 is running the same Spark version, I do not see why it's not reported as a supported runtime.

**Describe the solution you'd like**
I would like whatever changes made that would allow the 15.* to use the cosmos connector

**Describe alternatives you've considered**
Use without official support I guess?

**Additional context**
It's using the same Spark version and have been published for quite a while.
I have not seen any official mentions in the issues, so I suspect you guys are just not aware that there is a new version?

**Information Checklist**
Kindly make sure that you have added all the following information above and checkoff the required fields otherwise we will treat the issuer as an incomplete report
- [x] Description Added
- [x] Expected solution specified

**Comment by TheovanKraay** [comment]
@cmollgaard yes, you should be ok with Databricks runtime 15.4. We will update supported versions in readme shortly.

**Comment by kushagraThapar** [comment]
@cmollgaard this has been updated in our readme, thanks to @TheovanKraay
