### ISSUE TITLE
[FEATURE REQ] AadResourceServerConfiguration using deprecated function

### ISSUE THREAD

**Issue by chetan-galgali** [Azure/azure-sdk-for-java#42271]
**Is your feature request related to a problem? Please describe.**
Changes requesting to: com.azure.spring.cloud.autoconfigure.implementation.aad.configuration.AadResourceServerConfiguration.defaultAadResourceServerFilterChain
 http.apply(aadResourceServer());
**apply** is a deprecated function and will be removed in version 7

**Describe the solution you'd like**
apply function should be replaced using "**with**" function - per documentation from Spring Security

**Describe alternatives you've considered**
If "with" function is not applicable, any other method, that is not deprecated will work as well.

**Additional context**
Nothing

**Information Checklist**
Kindly make sure that you have added all the following information above and checkoff the required fields otherwise we will treat the issuer as an incomplete report
- [Y ] Description Added
- [ Y] Expected solution specified

**Comment by moarychan** [comment]
Closing it in favor of https://github.com/Azure/azure-sdk-for-java/issues/41302
