### ISSUE TITLE
[BUG] Unable to publish to Kafka topics with new Spring Cloud Azure 5.17.0 Version

### ISSUE THREAD

**Issue by breckenenneking** [Azure/azure-sdk-for-java#42275]
**Describe the bug**
Whenever I attempt to publish to a kafka topic after upgrading to Spring Cloud Azure version 5.17.0, the data will no longer be published to the Kafka topic.

***Exception or Stack Trace***
Unfortunately, I am unable to find any relevant error logs

**Expected behavior**
I expect to be able to publish to and consume from kafka topics.

**Comment by saragluna** [comment]
Could you help provide your configuration and pom file?

**Comment by moarychan** [comment]
Hi @breckenenneking , please help provide more details about your scenario, better to provide a minimal project to reproducer.
