### ISSUE TITLE
[QUERY] Is it possible to set DnsNameLabelReusePolicy/autoGeneratedDomainNameLabelScope during creation of a new ContainerGroup?

### ISSUE THREAD

**Issue by solar-planit** [Azure/azure-sdk-for-java#42341]
**Query/Question**
Is it possibe to explicitly set a value for the member autoGeneratedDomainNameLabelScope of [IpAddress](https://learn.microsoft.com/en-us/java/api/com.azure.resourcemanager.containerinstance.models.ipaddress) during the creation of a ContainerGroup when using the fluent creation style shown below?
If this currently isn't possible, what would be feasible workarounds in the context of the usage of Java?

```
  ContainerGroup containerGroup = azureResourceManager.containerGroups().define(aciName)
      .withRegion(Region.US_WEST)
      .withNewResourceGroup(rgName)
      .withLinux()
      .withPublicImageRegistryOnly()
      .withoutVolume()
      .defineContainerInstance(aciName + "-1")
          .withImage(containerImageName1)
          .withExternalTcpPort(80)
          .withCpuCoreCount(.5)
          .withMemorySizeInGB(0.8)
          .attach()
      .defineContainerInstance(aciName + "-2")
          .withImage(containerImageName2)
          .withoutPorts()
          .withCpuCoreCount(.5)
          .withMemorySizeInGB(0.8)
          .attach()
      .withRestartPolicy(ContainerGroupRestartPolicy.NEVER)
      .withDnsPrefix(aciName)
      .create();
```
(Source: https://github.com/Azure-Samples/aci-java-create-container-groups/blob/master/src/main/java/com/azure/resourcemanager/containerinstance/samples/ManageContainerInstanceWithMultipleContainerImages.java#L45C1-L65C27)

***Why is this not a Bug or a feature Request?***
Depending on the answer or simple workarounds, a feature request might result from this.

**Setup (please complete the following information if applicable):**
 - Library/Libraries: com.azure.resourcemanager:azure-resourcemanager:2.43.0
 
 **Information Checklist**
 Kindly make sure that you have added all the following information above and checkoff the required fields otherwise we will treat the issuer as an incomplete report
- [x] Query Added
- [x] Setup information Added

**Comment by weidongxu-microsoft** [comment]
Can you add the support for specifying `autoGeneratedDomainNameLabelScope` in convenience API?
