### ISSUE TITLE
Error message in the body of BrokeredMessage

### ISSUE THREAD

**Issue by ikoblik** [Azure/azure-sdk-for-java#424]
## Context

We're using Azure SKD version 0.4.6 to read from and post messages to service bus queues. We always use PeekLock read strategy. In terms of volume we process somewhere around 20 messages per second or less.
## What happens

Rather infrequently we receive BrokeredMessages that contain a Service Bus error string in the body of the message (i.e. BrokeredMessage.gotBody()). So far we saw 2 different errors in the message body:

```
<Error><Code>500</Code><Detail>The server was unable to process the request; please retry the operation. 
If the problem persists, please contact your Service Bus administrator and provide the tracking id..
TrackingId:00012cd4-255d-46ea-9cf2-9d37019d76d1_G26,TimeStamp:4/24/2014 10:23:32 AM</Detail></Error>
```

and

```
<Error><Code>500</Code><Detail>Error during communication with Service Bus. 
Check the connection information, then retry..
TrackingId:D369ac70-9be4-4f9a-b7bb-e1dfc73a5f8f_G28,TimeStamp:4/24/2014 11:17:02 AM</Detail></Error>
```

We detect these errors because we pass messages in the Protobuffer format, but it might be an issue for some clients who pass raw text data.
## What we expect

We expect from the SDK to raise a ServiceException. At a first glance, it seems that the SDK fails to detect errors coming form ServiceBus and passes them as a normal respons to its clients.

**Comment by ljhljh235** [comment]
@ikoblik We are closing this issue assuming the bug is already fixed in the new release. Please feel free to let us know if it still repros.

**Comment by venkat22** [comment]
This issue got reintroduced back in 0.7 version of the SDK. Please reopen  this issue again until it get resolved again.

**Comment by martinsawicki** [comment]
the service bus is not in this repo anymore, so if this is still an issue, it should go there:
https://github.com/azure/azure-service-bus-java
