### ISSUE TITLE
java.lang.NoClassDefFoundError: Could not initialize class com.azure.identity.implementation.RegionalAuthority

### ISSUE THREAD

**Issue by navjot3019** [Azure/azure-sdk-for-java#42439]
Being from a testing background, I am novice to developer's area of libraries/classes/methods so requesting your patience :)

**Describe the bug**
We are in process of writing load testing scripts (using JMeter). As part of this project, we need to store our test login credentials in Azure key vault so that these scripts can read credentials from vault. To achieve this, we have written a piece of code in JSR223 preprocessor using Groovy language. But its throwing below error:

ERROR o.a.j.JMeter: Uncaught exception in thread Thread\[\]
**java.lang.NoClassDefFoundError: Could not initialize class com.azure.identity.implementation.RegionalAuthority
at com.azure.identity.implementation.IdentityClientOptions**.\<init\>  (IdentityClientOptions.java:99) \~\[azure-identity-1.13.3.jar:1.13.3\]
at com.azure.identity.CredentialBuilderBase.\<init\>(CredentialBuilderBase.java:47) \~\[azure-   identity-1.13.3.jar:1.13.3\]
at com.azure.identity.DefaultAzureCredentialBuilder.\<init\>(DefaultAzureCredentialBuilder.java:77) \~\[azure-identity-1.13.3.jar:1.13.3\]
.....
**Caused by: java.lang.ExceptionInInitializerError: Exception java.lang.BootstrapMethodError: java.lang.SecurityException: class "com.azure.core.implementation.ReflectiveInvoker"'s signer information does not match signer information of other classes in the same package** \[in thread "Login-Logout 1-1"\]
at com.azure.core.util.ExpandableStringEnum.fromString(ExpandableStringEnum.java:70) \~\[azure-core-1.53.0.jar:1.53.0\]
at com.azure.identity.implementation.RegionalAuthority.fromString(RegionalAuthority.java:287) \~\[azure-identity-1.13.3.jar:1.13.3\]`
..
..

**Code Snippet in JMeter Preprocessor**

![Image](https://github.com/user-attachments/assets/6d32f38e-fb76-4303-9e20-67026799cdb5)

**Expected behavior**
Calling DefaultAzureCredential.build() should succeed

**Runtime Environment** - JMeter version : 5.6.3, Java version: 17, OS: Windows

**Comment by alzimmermsft** [comment]
Thanks for filing this issue @navjot3019, this seems similar to https://github.com/Azure/azure-sdk-for-java/issues/30320 which was also an issue with signer information. Let me know if any of the possible solutions from that issue help you.

**Comment by navjot3019** [comment]
Thanks @alzimmermsft for your quick response. I went through mentioned thread,  although error message seems same but unfortunately it looks like altogether a different setup. My issue is being observed in JMeter and i don't have any build tools like MAVEN etc.

**Comment by alzimmermsft** [comment]
> Hi [@alzimmermsft](https://github.com/alzimmermsft) - i have fixed the issue by using ManagedIdentityCredentialBuilder() instead of DefaultAzureCredentialBuilder(). Thanks for your response and support :)

Glad to hear a resolution was found for this issue! Hopefully this information will help others in the future, thanks for including it @navjot3019
