### ISSUE TITLE
[BUG] Unsupported parameter 'max_tokens' with o1-mini and o1-preview

### ISSUE THREAD

**Issue by JackMatthewRimmer** [Azure/azure-sdk-for-java#42490]
**Describe the bug**
When calling either o1-mini or o1-preview we can only set maxTokens on the ChatCompletionsOptions object however upon calling the model this error is returned

```
Status code 400, "{ "error": { "message": "Unsupported parameter: 'max_tokens' is not supported with this model. Use 'max_completion_tokens' instead.", "type": "invalid_request_error", "param": "max_tokens", "code": "unsupported_parameter" } }"
```

**To Reproduce**
Set maxTokens when calling o1-mini or o1-preview

***Code Snippet***
```
            .setMaxTokens(config.maxTokens())
```

**Information Checklist**
Kindly make sure that you have added all the following information above and checkoff the required fields otherwise we will treat the issuer as an incomplete report
- [X] Bug Description Added
- [X] Repro Steps Added
- [X] Setup information Added

**Comment by TheovanKraay** [comment]
I believe this is an issue related to Azure OpenAI Java API and not Java SDK for Cosmos DB? @JackMatthewRimmer I think your issue has been tagged incorrectly - can you please help clarify with more context on how you are making this call (i.e. provide a full code snippet, reference the client library you are using, etc)?

**Comment by alzimmermsft** [comment]
Thanks for reporting this @JackMatthewRimmer, @mssfang and @jpalvarezl could you follow-up on this.

**Comment by mssfang** [comment]
@JackMatthewRimmer 
`maxTokens` is not available in `o1-preview` and `p1-mini` models. We haven't added the support for max_completion_tokens yet. But it will be in the next service API version, 2024-09-01-preview.

Will keep you posted when we release next SDK version (ETA, before end of year).
