### ISSUE TITLE
Double confirm If  can use spring-cloud-azure version5.x in springboot2 project

### ISSUE THREAD

**Issue by battlefield007** [Azure/azure-sdk-for-java#42505]
Hi Team,
**Background:**
our springboot2 project need upgrade spring from 5.x to spring6.1, 
we are trying only upgrade spring, not upgrade springboot to 3.x which default spring version is 6.x.

**Question:**
ref
https://github.com/Azure/azure-sdk-for-java/wiki/Spring-Versions-Mapping#which-version-of-spring-cloud-azure-should-i-use
seems boot2 can not use spring-cloud-azure version5.x,
So want double confirm If  can use spring-cloud-azure version5.x in springboot2 project? 
If can, what step show we do.

Thanks

**Comment by saragluna** [comment]
No, you cannot use Spring Cloud Azure 5.x together with Spring Boot 2.x, it incompatible.

**Comment by battlefield007** [comment]
thanks
