### ISSUE TITLE
[BUG] OutOfMemoryError when calling beginAnalyzeDocumentFromUrl with a large file

### ISSUE THREAD

**Issue by sdehandt** [Azure/azure-sdk-for-java#42535]
**Describe the bug**
Document Intelligence's AnalyzeResult takes up a huge amount of memory, especially when a document contains a lot of lines on a page. For a 105MB pdf page, more than 12 GB memory is needed.

**To Reproduce**

***Code Snippet***
```
client.beginAnalyzeDocumentFromUrl("prebuilt-read", uri)
                .last()
                .flatMap(this::checkResponseSuccess)
                .map(this::processOperation);

private DocumentIntelligenceResult processOperation(AnalyzeResult analyzeResult) {
    // huge peak in memory when this point is reached
}
```

**Expected behavior**
A test with the .NET version shows that the result can be returned in around 350MB of memory, not >12 GB

**Screenshots**
Memory consumption
![Image](https://github.com/user-attachments/assets/e8715c68-c21d-4bb9-b13e-ea4f551fad32)

**Additional context**
In `com.azure.ai.formrecognizer.documentanalysis.implementation.util.Transforms`, the `toAnalyzeResultOperation` is the likely cause of this issue. The following code (line 149-162 in v4.1.11)  is inside a stream loop over all the document pages: 

```
         DocumentPageHelper.setLines(documentPage, innerDocumentPage.getLines() == null ? null : (List)innerDocumentPage.getLines().stream().map((innerDocumentLine) -> {
                DocumentLine documentLine = new DocumentLine();
                DocumentLineHelper.setBoundingPolygon(documentLine, toPolygonPoints(innerDocumentLine.getPolygon()));
                DocumentLineHelper.setContent(documentLine, innerDocumentLine.getContent());
                DocumentLineHelper.setSpans(documentLine, toDocumentSpans(innerDocumentLine.getSpans()));
                DocumentLineHelper.setPageWords(documentLine, toDocumentWords(innerDocumentPage)); // <<<<<<<<<<<<<<<
                return documentLine;
            }).collect(Collectors.toList()));

            DocumentPageHelper.setWords(documentPage, toDocumentWords(innerDocumentPage));
```

The line marked with `//<<<<` creates a list of PageWords based on the document, but does this for every line in the page instead of just once for each page. Moving the call  `toDocumentWords(innerDocumentPage)` outside if the stream code and storing it in a local variable, should solve this issue.

### Memory structure
![Image](https://github.com/user-attachments/assets/ec223305-65d6-4399-8af3-14702948a41c)
Here you can clearly see that for each line on a page, a copy of the same list of PageWords is being created, taking up a lot of unnecessary memory

**Comment by alzimmermsft** [comment]
Thanks for filing this @sdehandt, this appears to be similar (probably the same) to #42511.

@samvaity I'm going to assign this to you as you're already looking at that other issue.
