### ISSUE TITLE
[FEATURE REQ] Add `beginAnalyzeDocument` method with `RequestOptions` parameter returning `PollerFlux<AnalyzeResultOperation, AnalyzeResult>`

### ISSUE THREAD

**Issue by f-teruhisa** [Azure/azure-sdk-for-java#42602]
**Is your feature request related to a problem? Please describe.**
It is inconvenient that the `beginAnalyzeDocument` method in `DocumentIntelligenceClient` does not accept `RequestOptions` as a parameter while returning a `PollerFlux<AnalyzeResultOperation, AnalyzeResult>`.

Currently, the method only supports a version that returns a `BinaryData` type, which does not provide direct access to the analysis result needed for the Document Intelligence Layout Model.

https://github.com/Azure/azure-sdk-for-java/blob/862517e7ec39fd6acda3dd196b213725db0a96c9/sdk/documentintelligence/azure-ai-documentintelligence/src/main/java/com/azure/ai/documentintelligence/DocumentIntelligenceClient.java#L104-L108

**Is your feature request related to a problem? Please describe.**
The current `beginAnalyzeDocument` method in `DocumentIntelligenceClient` is somewhat redundant as it requires passing multiple `null` values or unnecessary parameters when they are not needed. 

```java
SyncPoller <AnalyzeResultOperation, AnalyzeResultOperation> analyzeLayoutPoller =
      client.beginAnalyzeDocument(modelId,
          null,
          null,
          null,
          null,
          null,
          null,
          new AnalyzeDocumentRequest().setUrlSource(documentUrl));
```

ref: https://learn.microsoft.com/ja-jp/azure/ai-services/document-intelligence/quickstarts/get-started-sdks-rest-api?view=doc-intel-4.0.0&pivots=programming-language-java#layout-model

This makes the method calls verbose and less intuitive. 

By adding a version of `beginAnalyzeDocument` that accepts a `RequestOptions` parameter and returns `PollerFlux<AnalyzeResultOperation, AnalyzeResult>`, it would streamline the process, allowing developers to pass only the necessary configuration without the need for excessive `null` parameters.

**Describe the solution you'd like**
I would like to see a new `beginAnalyzeDocument` method added that accepts `RequestOptions` as a parameter and returns `PollerFlux<AnalyzeResultOperation, AnalyzeResult>`. 

This new method would be an addition rather than a change to the existing methods, allowing developers to choose the most appropriate version based on their needs while keeping the existing methods unchanged.

**Describe alternatives you've considered**
Another alternative could be creating an overloaded method internally that simply maps the existing method to accept `RequestOptions`.

**Additional context**
The `DocumentIntelligenceAsyncClient` class has the same issue.

https://github.com/Azure/azure-sdk-for-java/blob/862517e7ec39fd6acda3dd196b213725db0a96c9/sdk/documentintelligence/azure-ai-documentintelligence/src/main/java/com/azure/ai/documentintelligence/DocumentIntelligenceAsyncClient.java#L106-L110

**Information Checklist**
Kindly make sure that you have added all the following information above and checkoff the required fields otherwise we will treat the issuer as an incomplete report
- [x] Description Added
- [x] Expected solution specified

**Comment by samvaity** [comment]
@f-teruhisa Thanks for reporting.

You could directly use the `BinaryData.to(Class<T> clazz)` API to convert the BinaryData result type from the `beginAnalyzeDocument(String modelId, RequestOptions requestOptions) {}` in the following way.

```java
 AnalyzeResult analyzeLayoutResult = analyzeLayoutPoller.getFinalResult().toObject(AnalyzeResult.class);
```

Let me know if this helps.
