### ISSUE TITLE
[BUG] Azure ServiceBus memory leak (due to potential use of deprecated AmqpChannelProcessor)

### ISSUE THREAD

**Issue by gataricd** [Azure/azure-sdk-for-java#42717]
**Describe the bug**
The number of `ServiceBusReactorAmqpConnection` instances is rising until there is no more memory on the heap. When the app is started the number of instances is 44, because we use 44 queues, but with time it rises to above 500 and eventually we get OutOfMemoryError. The heap size is limited to around 500 MB.
When the OutOfMemoryError happens, all the ServiceBusReactorAmqpConnection have sessionMap set to 0. This lead us to conclusion that garbage collector is not cleaning these connections that are not being used.
We have never had similar problem before and it happens during normal load.

***Exception or Stack Trace***
The following exceptions might be relevant to the problem:
```
reactor.core.Exceptions$ErrorCallbackNotImplemented: java.lang.NullPointerException: Cannot invoke "java.util.List.add(Object)" because "this._sessions" is null
Caused by: java.lang.NullPointerException: Cannot invoke "java.util.List.add(Object)" because "this._sessions" is null
	at org.apache.qpid.proton.engine.impl.ConnectionImpl.session(ConnectionImpl.java:91)
	at org.apache.qpid.proton.engine.impl.ConnectionImpl.session(ConnectionImpl.java:39)
```
and 
```
com.azure.core.amqp.exception.AmqpException: onSessionRemoteClose connectionId[MF_1e9f94_1730303967974], entityName[mdk-mnp-command-queue] condition[Error{condition=amqp:connection:forced, description='The connection was closed by container 'ce030eed2af746d4a84caa602d8b170a_G0' because it did not have any active links in the past 300000 milliseconds. TrackingId:ce030eed2af746d4a84caa602d8b170a_G0, SystemTracker:gateway5, Timestamp:2024-10-30T16:24:05', info=null}], errorContext[NAMESPACE: mdk-westeurope-eu-e-servicebus.servicebus.windows.net. ERROR CONTEXT: N/A, PATH: some-queue]
	at com.azure.core.amqp.implementation.ExceptionUtil.toException(ExceptionUtil.java:90)
	at com.azure.core.amqp.implementation.handler.SessionHandler.onSessionRemoteClose(SessionHandler.java:139)
```
These exceptions started ocurring when we switched from 7.17.1 to 7.17.3.

**To Reproduce**
There are no special steps to reproduce. 

***Code Snippet***
The following code is executed for every queue:
```
val processorClient: ServiceBusProcessorClient = ServiceBusClientBuilder()
            .credential(serviceBusFullyQualifiedName, DefaultAzureCredentialBuilder().build())
            .processor()
            .queueName(queueName)
            .processMessage(handler)
            .processError { context -> processError(context) }
            .maxConcurrentCalls(10)
            .disableAutoComplete()
            .maxAutoLockRenewDuration(Duration.ZERO)
            .prefetchCount(0)
            .buildProcessorClient()
processorClient.start()
```

**Expected behavior**
The memory consumption of the service bus library shouldn't raise to the point that cause OutOfMemoryError.

**Setup (please complete the following information):**
    OS: Linux
    Library/Libraries: com.azure:azure-messaging-servicebus:7.17.3
    Java version: 21
    App Server/Environment: AKS
    Frameworks: Sprint Boot

**Comment by anuchandy** [comment]
Hello @gataricd, this is resolved recently, you can find more details here https://github.com/Azure/azure-sdk-for-java/issues/41865 

Note that you will still see the session disconnect/reconnect logs (which is expected) but the new version should address the NullPointerException.
 
## Update to 7.17.5 dependency

```xml
<dependency>
    <groupId>com.azure</groupId>
    <artifactId>azure-messaging-servicebus</artifactId>
    <version>7.17.5</version>
</dependency>
```
 
## Update the ServiceBusClientBuilder for "com.azure.core.amqp.cache"
When building any client (ServiceBusProcessorClient, ServiceBusReceiverClient, ServiceBusSenderClient etc..) use the configuration ("com.azure.core.amqp.cache"), as shown below. Make sure this configuration is selected for all the places where the application creates a new `ServiceBusClientBuilder` -
 

```java

new ServiceBusClientBuilder()
            .connectionString(queueProperties.connectionString())
                     .configuration(new ConfigurationBuilder()
                         .putProperty("com.azure.core.amqp.cache", "true")
                         .build())
            .processor()
            .queueName(queueName)
            .processMessage(handler)
            .processError { context -> processError(context) }
            .maxConcurrentCalls(10)
            .disableAutoComplete()
            .maxAutoLockRenewDuration(Duration.ZERO)
            .prefetchCount(0)
            .buildProcessorClient()

```

Choosing this configuration is important to resolve the problem - ` java.lang.NullPointerException: Cannot invoke "java.util.List.add(Object)" because "this._sessions" is null` 

## Ensure right transitive dependencies 

Make sure the transitive dependencies (azure-core-amqp, azure-core) are resolved to expected versions.

```
mvn dependency:tree
```

```
[INFO] ...
[INFO] +- com.azure:azure-messaging-servicebus:jar:7.17.5:compile
[INFO] |  +- com.azure:azure-core:jar:1.53.0:compile
[INFO] |  |  +- ..
[INFO] |  |  \- ...
[INFO] |  \- com.azure:azure-core-amqp:jar:2.9.10:compile
[INFO] |     +- com.microsoft.azure:qpid-proton-j-extensions:jar:1.2.5:compile
[INFO] |     \- org.apache.qpid:proton-j:jar:0.34.1:compile
```


Note: In the upcoming version the need for opt-in "com.azure.core.amqp.cache" will be removed

**Comment by gataricd** [comment]
/unresolve
@anuchandy thanks for the answer, unfortunately the proposed changes didn't resolve the problem. We are still getting:
`java.lang.NullPointerException: Cannot invoke "java.util.List.add(Object)" because "this._sessions" is null `
after updating to `7.17.5` and setting `com.azure.core.amqp.cache` to `true`.

**Comment by anuchandy** [comment]
Hello @gataricd, thanks for trying it. Could you share -20/+20 minutes of [DEBUG](https://learn.microsoft.com/en-us/azure/developer/java/sdk/troubleshooting-messaging-service-bus-overview#enable-and-configure-logging) logs around this NullPointerException.

**Comment by AndreasPetersen** [comment]
Hi, we are seeing the same issue with 7.17.5.

We can provide the requested logs, but not here. Should we create a support case and upload the logs through that?

**Comment by AndreasPetersen** [comment]
> Hi, we are seeing the same issue with 7.17.5.
> 
> We can provide the requested logs, but not here. Should we create a support case and upload the logs through that?

My apologies, we didn't read @anuchandy description thoroughly enough initially. After adding 

> Update the ServiceBusClientBuilder for "com.azure.core.amqp.cache"

as described, we are not longer seeing the issue.

**Comment by anuchandy** [comment]
Closing as there is support case for it. Currently, it appears that the opt-in may not be configured in some builders or is not recognized at runtime for the SDK to detect hence library continues to use deprecated AmqpChannelProcessor. If the case conclusion differs from this, I will update here.
