### ISSUE TITLE
[FEATURE REQ] Spring Cloud Azure to support Springboot 3.4

### ISSUE THREAD

**Issue by HaruhiSuzumiyah** [Azure/azure-sdk-for-java#42759]
**Is your feature request related to a problem? Please describe.**
Currently Springboot 3.4 is in RC-1 and isn't supported by Spring Cloud Azure 5.17.1 due to `AzureTokenCredentialAutoConfiguration` using a deprecated method that was removed in Springboot 3.4: `org.springframework.boot.task.TaskExecutorBuilder`.

**Describe the solution you'd like**
Use `ThreadPoolTaskExecutorBuilder` so it works with Springboot 3.4. (And any other things that are required that I didn't uncover in my admittedly surface level overview of the issue)

**Describe alternatives you've considered**
Mostly just stay with 3.3.5 but I want to use the ecs logging features in 3.4 XD

**Additional context**

**Information Checklist**
Kindly make sure that you have added all the following information above and checkoff the required fields otherwise we will treat the issuer as an incomplete report
- [ x ] Description Added
- [ x ] Expected solution specified

**Comment by HaruhiSuzumiyah** [comment]
made a pr to fix that one line
https://github.com/Azure/azure-sdk-for-java/pull/42760

**Comment by Netyyyy** [comment]
close for pr merged
