### ISSUE TITLE
[FEATURE REQ] sdk automation breaking change detection, output generateOutput.json even when exception occurs

### ISSUE THREAD

**Issue by XiaofeiCao** [Azure/azure-sdk-for-java#42829]
https://github.com/Azure/azure-rest-api-specs/pull/31435/checks?check_run_id=32563739549
![Image](https://github.com/user-attachments/assets/d8d414b3-ea54-4a57-b65b-fe41c6c2be03)

When SDK bug happen, we should still output generateOutput.json, 

Priority might be low, as this only happens when SDK has bug... It's not very helpful to service.

**Comment by joshfree** [comment]
Related PR: https://github.com/Azure/azure-sdk-for-java/pull/42799
