### ISSUE TITLE
[BUG] Azure Key Vault Secrets docs points to wrong maven package

### ISSUE THREAD

**Issue by Guilhermeslucas** [Azure/azure-sdk-for-java#4284]
**Describe the bug**
When you try to follow the instructions from this [link](https://github.com/Azure/azure-sdk-for-java/tree/master/keyvault/client/secrets), adding the package to you dependencies and trying to import this afterwards doesn't work. It says it's not possible to resolve the dependencies.

***Exception or Stack Trace***
The message we get trying to run gradle for installing dependencies is:
```
Unable to resolve com.azure.security:azure-keyvault-secrets:1.0.0-preview.1
```

**To Reproduce**
Put the dependency line in you ```build.gradle``` file and try to download the dependencies:
```
implementation 'com.azure.security:azure-keyvault-secrets:1.0.0-preview.1'
```

***Code Snippet***
dependencies {
    implementation 'com.azure.security:azure-keyvault-secrets:1.0.0-preview.1'
}

**Expected behavior**
I expected to add the dependency in my ```build.gradle``` file and get all the dependencies without friction.

**Screenshots**
![image](https://user-images.githubusercontent.com/9682164/60677924-3cbfee00-9e59-11e9-9aa9-91d3ac0b56a8.png)

![image](https://user-images.githubusercontent.com/9682164/60677944-4c3f3700-9e59-11e9-85c0-476c3bce853d.png)

**Setup (please complete the following information):**
 - OS: Windows
 - IDE : IntelliJ
 - azure-keyvault-secrets : 1.0.0-preview.1

**Additional context**
I don't know if I need to add something before. The docs are not showing me how should I do that.

**Information Checklist**
Kindly make sure that you have added all the following information above and checkoff the required fields otherwise we will treat the issuer as an incomplete report
- [x] Bug Description Added
- [x] Repro Steps Added
- [x] Setup information Added

**Comment by aman-iitj** [comment]
@Guilhermeslucas 
```
        <dependency>
            <groupId>com.azure</groupId>
            <artifactId>azure-keyvault-secrets</artifactId>
            <version>4.0.0-preview.1</version>
        </dependency>
```

this works for me.

**Comment by Guilhermeslucas** [comment]
Awesome, @aman-iitj . This really works. I'll open a PR updating the docs with that!

**Comment by maggiepint** [comment]
Thanks! Routing to the appropriate people for follow up.

cc: @schaabs @joshfree @JonathanGiles

**Comment by JonathanGiles** [comment]
Thanks for the feedback. @g2vinay will update the text.

**Comment by g2vinay** [comment]
Thanks for pointing this out.
I've updated the README with the correct version.
This issue is now fixed.
