### ISSUE TITLE
[BUG] PerCallTimeoutCall causing OOM

### ISSUE THREAD

**Issue by arikogan** [Azure/azure-sdk-for-java#42871]
**Describe the bug**
The PR [40017](https://github.com/Azure/azure-sdk-for-java/pull/40017) introduced the class [PerCallTimeoutCall](https://github.com/Azure/azure-sdk-for-java/blob/main/sdk/core/azure-core-http-okhttp/src/main/java/com/azure/core/http/okhttp/implementation/PerCallTimeoutCall.java).
This class holds a static Timer with strong references to every call it processes.
When uploading a blob in blocks, each block is a call that gets added to the Timer, not released quickly enough and causing the Timer to hold all calls in memory without the garbage collector being able to free them. This causes the system to deplete its memory.

See [BlobClient](https://github.com/Azure/azure-sdk-for-java/blob/main/sdk/storage/azure-storage-blob/src/main/java/com/azure/storage/blob/BlobClient.java#L389)
```
public Response<BlockBlobItem> uploadWithResponse(BlobParallelUploadOptions options, Duration timeout,
        Context context) {
```

***Exception or Stack Trace***
![Image](https://github.com/user-attachments/assets/327a0d84-a910-4cf7-825b-c61840ee5e1f)

**To Reproduce**
Set up any project using the Azure Java SDK and upload binaries at moderate pace using the method [BlobClient.uploadWithResponse](https://github.com/Azure/azure-sdk-for-java/blob/main/sdk/storage/azure-storage-blob/src/main/java/com/azure/storage/blob/BlobClient.java#L389)

***Code Snippet***
See [PerCallTimeoutCall](https://github.com/Azure/azure-sdk-for-java/blob/main/sdk/core/azure-core-http-okhttp/src/main/java/com/azure/core/http/okhttp/implementation/PerCallTimeoutCall.java#L47)
```
private static final Timer TIMER = new Timer("azure-okhttp-response-timeout-tracker", true);

...

public void beginPerCallTimeout(Call call) {
        if (perCallTimeout > 0) {
            TimerTask currentTimeout = new PerCallTimerTask(this, call);

            TIMER.schedule(currentTimeout, perCallTimeout);
            TimerTask existing = CURRENT_TIMEOUT_UPDATER.getAndSet(this, currentTimeout);
            if (existing != null) {
                existing.cancel();
            }
        }
    }
```

**Expected behavior**
The system shouldn't run out of memory.

**Screenshots**
![Image](https://github.com/user-attachments/assets/2b995564-ca02-47f6-a1bd-b10f27c8d133)

**Setup (please complete the following information):**
 - OS: Any
 - IDE: Any
 - Library/Libraries: com.azure:azure-core:1.51.0, com.azure:azure-core-http-okhttp:1.12.2 (the behavior was introduced in [com.azure:azure-core-http-okhttp:1.12.0](https://github.com/Azure/azure-sdk-for-java/releases/tag/azure-core-http-okhttp_1.12.0))
 - Java version: 17
 - App Server/Environment: Tomcat
 - Frameworks: Any

If you suspect a dependency version mismatch (e.g. you see `NoClassDefFoundError`, `NoSuchMethodError` or similar), please check out [Troubleshoot dependency version conflict article](https://aka.ms/azsdk/java/dependency/troubleshoot) first. If it doesn't provide solution for the problem, please provide:
- verbose dependency tree (`mvn dependency:tree -Dverbose`)
- exception message, full stack trace, and any available logs

**Additional context**

**Information Checklist**
Kindly make sure that you have added all the following information above and checkoff the required fields otherwise we will treat the issuer as an incomplete report
- [x] Bug Description Added
- [x] Repro Steps Added
- [x] Setup information Added

**Comment by alzimmermsft** [comment]
Thanks for filing this issue @arikogan, I'll follow-up on this shortly after I look into this more.

**Comment by alzimmermsft** [comment]
@arikogan, for a quick check to make sure this isn't an issue where the network isn't uploading quick enough, could you construct an OkHttp-based `HttpClient` instance using

```java
HttpClient httpClient = new OkHttpAsyncHttpClientBuilder()
    .responseTimeout(Duration.ZERO)
    .build();
```

This will disable the usage of the `Timer` to track actively running requests to ensure they response within an appropriate time limit.

**Comment by arikogan** [comment]
Hi @alzimmermsft , thanks for the reply.
So that's exactly our current mitigation mechanism. We've set the environment variable `AZURE_REQUEST_RESPONSE_TIMEOUT` to `0` to disable the new functionality.
And now for not relying on the party in charge of deploying the code to set the environment variable properly, we are disabling the mechanism through code:

```java
private static void disablePerCallTimeoutCall(BlobServiceClientBuilder builder) {
        Configuration configuration =
                new ConfigurationBuilder().putProperty(PROPERTY_AZURE_REQUEST_RESPONSE_TIMEOUT, "0").build();
        builder.configuration(configuration); // Not necessary but added for clarity
}
```

Not ideal but lucky we were able to disable through the environment variable.
The default timeout is 60 seconds. On a system running quite a few operations, the chunks are uploaded faster than that but the static Timer doesn't allow the GC to reclaim that memory.

**Comment by alzimmermsft** [comment]
Glad to hear the workaround has prevented this @arikogan.

I've also had a chance to review this code path more deeply and have realized the mistake I've made with the implementation. I didn't realize that `TimerTask.cancel()` doesn't remove that task from the queue within `Timer`.

I've filed this PR which should resolve this problem: https://github.com/Azure/azure-sdk-for-java/pull/42887
