### ISSUE TITLE
[FEATURE REQ] Introduce WithCapacityReservation DefinitionStage into the VirtualMachine model

### ISSUE THREAD

**Issue by jonatlee** [Azure/azure-sdk-for-java#42884]
**Is your feature request related to a problem? Please describe.**
We are trying to create/update an instance VM with an attached capacity reservation in the Azure Java SDK. We are currently using the [DefinitionStages within the VirtualMachine model to create/update instance VMs](https://azuresdkdocs.blob.core.windows.net/$web/java/azure-resourcemanager-compute/2.13.0/com/azure/resourcemanager/compute/models/VirtualMachine.DefinitionStages.html), but could not find anything in the docs or the code about a `WithCapacityReservation` stage that would allow you to attach a capacity reservation to the instance VM creation request. 

The only way I could find how to do this was this example [here](https://github.com/Azure/azure-sdk-for-java/blob/ab2fdccc08946c9571424558700fce253118f4da/sdk/resourcemanager/azure-resourcemanager/src/samples/java/com/azure/resourcemanager/compute/generated/VirtualMachinesCreateOrUpdateSamples.java#L322). Doing it this way would require re-writing how instance VMs are created/updated and which is pretty painful since there is a chance that the existing logic may not be ported over correctly. Additionally, this would require maintaining two separate ways of creating/updating instance VMs, which from a maintainability standpoint is not ideal. 

**Describe the solution you'd like**
A `WithCapacityReservation` definition stage is introduced into the `DefinitionStages` for a `VirtualMachine`, suitable for creation and updating

**Describe alternatives you've considered**
For creation, we are looking into the possibility of casting a `VirtualMachine.DefinitionStages.WithCreate` to a `(HasInnerModel<VirtualMachineInner>)`, obtaining the `VirtualMachineInner` with `.innerModel()` and then attaching the CapacityReservation that way. 

**Additional context**

**Information Checklist**
Kindly make sure that you have added all the following information above and checkoff the required fields otherwise we will treat the issuer as an incomplete report
- [x] Description Added
- [x] Expected solution specified

**Comment by weidongxu-microsoft** [comment]
@v-hongli1 

Can you add `withCapacityReservation(String capacityReservationGroupsId)` API to create/update flow?

**Comment by v-hongli1** [comment]
@weidongxu-microsoft  @XiaofeiCao 
The Capacity Reservation group must contain a Capacity Reservation with a matching VM size and zone(s) (if zonal) when a virtual machine references it, but I cannot create a Capacity Reservation group available on the Azure portal, so disabled the Capacity Reservation related test cases. Is this OK ?

**Comment by weidongxu-microsoft** [comment]
Yes, you can disable the test.

The code should be simple, hopefully we can be sure the code works without actually run it...

**Comment by v-hongli1** [comment]
@jonatlee 
When creating a virtual machine scale set on the Azure portal, you can also set the Capacity Reservation configurations. Do I also need to add `withCapacityReservation(String capacityReservationGroupsId)` in the `VirtualMachineScaleSet` model ?

**Comment by jonatlee** [comment]
> [@jonatlee](https://github.com/jonatlee) When creating a virtual machine scale set on the Azure portal, you can also set the Capacity Reservation configurations. Do I also need to add `CapacityReservation` support in the `VirtualMachineScaleSet` model ?

No, just adding support for the `VirtualMachine` model should suffice for our use case.

**Comment by jonatlee** [comment]
@v-hongli1 I saw that https://github.com/Azure/azure-sdk-for-java/pull/42914 was merged, thanks for getting to it so quick! Do you know when the next release for the sdk will be / when that change will be made available?

**Comment by weidongxu-microsoft** [comment]
It should be about early next week. @XiaofeiCao

**Comment by weidongxu-microsoft** [comment]
2.45.0 released
