### ISSUE TITLE
[BUG] Still use connection string auth even if the connection string property is set as empty string

### ISSUE THREAD

**Issue by haoozhang** [Azure/azure-sdk-for-java#42880]
**Describe the bug**
Even if the connection string property is set as empty, the application still tries to auth via connection string.

The application is a simple spring cloud stream + kafka, refering to the sample project https://github.com/Azure-Samples/azure-spring-boot-samples/tree/main/eventhubs/spring-cloud-azure-starter/spring-cloud-azure-sample-eventhubs-kafka.

In the application.yaml, when we specify the auth as follows, we want to use managed identity auth, instead of connection string (we leave it empty), but the application still try to use connection string for auth, causing it cannot startup.
```yml
spring:
  cloud:
        azure:
          eventhubs:
            credential:
              managed-identity-enabled: true
              client-id:  XXX
          connection-string:  # empty string
```

***Exception or Stack Trace***

In the following file, when the property is set as empty, it should not enter the method. but now it will execute this method even if empty.

```java
public class AzureEventHubsKafkaAutoConfiguration {

    private static final Logger LOGGER = LoggerFactory.getLogger(AzureEventHubsKafkaAutoConfiguration.class);

    @Bean
    @ConditionalOnProperty("spring.cloud.azure.eventhubs.connection-string")
    @ConditionalOnMissingBean(value = AzureServiceType.EventHubs.class, parameterizedContainer = ServiceConnectionStringProvider.class)
    StaticConnectionStringProvider<AzureServiceType.EventHubs> eventHubsKafkaConnectionString(Environment environment) {
        String connectionString = environment.getProperty("spring.cloud.azure.eventhubs.connection-string");

        try {
            new EventHubsConnectionString(connectionString);
        } catch (Exception e) {
            LOGGER.error("A valid Event Hubs connection string must be provided");
            throw e;
        }

        return new StaticConnectionStringProvider<>(AzureServiceType.EVENT_HUBS, connectionString);
    }
```

**To Reproduce**

1. Clone the sample project.
2. As described above, specify the application properties and then run.

***Code Snippet***
Add the code snippet that causes the issue.

**Expected behavior**

When setting connection string as empty, it should auto-use MI configuration for auth.

**Screenshots**

**Setup (please complete the following information):**
 - OS: [e.g. iOS] Windows 11
 - IDE: [e.g. IntelliJ]: IDEA
 - Library/Libraries: spring-boot-starter-web 3.3.5, spring-cloud-starter-stream-kafka 4.1.3, spring-cloud-azure-starter 5.18.0
 - Java version: [e.g. 8] 17
 - App Server/Environment: Tomcat
 - Frameworks:  Spring Boot
 
If you suspect a dependency version mismatch (e.g. you see `NoClassDefFoundError`, `NoSuchMethodError` or similar), please check out [Troubleshoot dependency version conflict article](https://aka.ms/azsdk/java/dependency/troubleshoot) first. If it doesn't provide solution for the problem, please provide:
- verbose dependency tree (`mvn dependency:tree -Dverbose`)
- exception message, full stack trace, and any available logs

**Additional context**

**Information Checklist**
Kindly make sure that you have added all the following information above and checkoff the required fields otherwise we will treat the issuer as an incomplete report
- [x] Bug Description Added
- [x] Repro Steps Added
- [x] Setup information Added

**Comment by rujche** [comment]
FYI: More information about environment variable used in Spring Boot can be found here: https://github.com/azure-javaee/azure-dev/wiki/Knowledge-Sharing#2-sometimes-the-environment-variable-not-take-effect-in-spring-boot-application

**Comment by moarychan** [comment]
> Another problem is that for `spring-cloud-starter-stream-kafka`, `SPRING_CLOUD_AZURE_EVENTHUBS_CONNECTIONSTRING` not work, `SPRING_CLOUD_AZURE_EVENTHUBS_CONNECTION_STRING` works.
> 
> But for `spring-cloud-azure-stream-binder-eventhubs`, `SPRING_CLOUD_AZURE_EVENTHUBS_CONNECTIONSTRING` works well. This behavior will make customer confused.

The behavior is not expected, I opened an issue on SCS side, see more from https://github.com/spring-cloud/spring-cloud-stream/issues/3039

**Comment by rujche** [comment]
This problem also exists in Service Bus.
Here is related code:

https://github.com/Azure/azure-sdk-for-java/blob/e9953c173e4d6176d7b1853595a88726ab8033a2/sdk/spring/spring-cloud-azure-autoconfigure/src/main/java/com/azure/spring/cloud/autoconfigure/implementation/servicebus/AzureServiceBusClientBuilderConfiguration.java#L53-L59

I'll reopen this issue.

Hi, @moarychan
Could you please help to fix it?
