### ISSUE TITLE
Add Mock Test Case To Verify CAE Support In Mgmt SDK

### ISSUE THREAD

**Issue by archerzz** [Azure/azure-sdk-for-java#42935]
## Description

On par with #41984, we need to add a mock test case to verify mgmt SDK can support CAE.

**Comment by weidongxu-microsoft** [comment]
Bill's PR may already had the mock test https://github.com/Azure/azure-sdk-for-java/pull/42471/files#diff-cbf0d7b60d50ccaf9e280da797115914609b96cf6e252e5192682bd775439316

@XiaofeiCao Could you double check?
