### ISSUE TITLE
status handling of createDataDisk

### ISSUE THREAD

**Issue by hinemos** [Azure/azure-sdk-for-java#430]
A problem as occurred in
createDataDisk Method of VirtualMachineDiskOperationsImpl Class in microsoft-azure-api-management-compute-0.5.0.jar

When I have used the method described above to process "create disk" operation, a status code "202(Accepted)" has been returned. 
As far as I read the specification of this API, the correct return code seems to be "201(Created)".

The SDK side process Exceptions when this status code is other than "201", and when this exception processing occurs, the SDK side tries to process the response, which is in XML format.
This Exception processing fails when status code "202" is returned, because status code "202" does not return any XML format response.

URL:http://msdn.microsoft.com/ja-jp/library/azure/jj157199.aspx

com.microsoft.windowsazure.management.compute.VirtualMachineDiskOperationsImpl.java
in microsoft-azure-api-management-compute-0.5.0.jar
is the corresponding part of the source code. 

The processing which is causing an error, is in line 427.
Here, when status is not "Created", it is processed as an error.
Therefor when status is "Accepted", it is processed as an error.

However, regarding of the specifications, the API of Azure returns status code "201(Created)" when processing ends normally.
Therefor it seems that SDK is processing the return code correctly.

URL:http://msdn.microsoft.com/ja-jp/library/azure/jj157199.aspx

It seemed that there might also be a possibility of Azure returning a wrong status code.

**Comment by singhkay** [comment]
@hinemos Are you still running into this issue?

**Comment by ljhljh235** [comment]
@hinemos Hi we assume this no longer repros for you. Please feel free to let us know if you still run into it.
