### ISSUE TITLE
[BUG] AAD issue with CosmosDB after upgrading azure-sdk-bom:1.2.29 / spring-boot-starter-parent:3.3.5

### ISSUE THREAD

**Issue by stevenylai** [Azure/azure-sdk-for-java#43010]
**Describe the bug**
We see an authentication in our CosmosDB client issue after performing the upgrade as titled recently. After downgrading the versions, the issues went away. Also, BTW, in the release page: https://github.com/Azure/azure-sdk-for-java/blob/main/sdk/spring/CHANGELOG.md it used to mention the spring versions tested against a particular azure-sdk-bom version but since `5.17.1 (2024-10-11)` that information is no longer available? Where can we find such information in the future. For us, we just want to stick to the latest SDK and also upgrade our spring according to what you have tested.

***Exception or Stack Trace***
The error message is saying
```
Provided AAD token is intended for [https://xxxx-cosmosdb-sql-nch-dev.documents.azure.com/]. This database account accepts token intended for [https://xxxx-cosmosdb-sql-nch-dev.documents.azure.com, https://xxxx-cosmosdb-sql-nch-dev.sql.cosmos.azure.com, https://xxxx-cosmosdb-sql-nch-dev.sqlx.cosmos.azure.com, https://cosmos.azure.com]
```

The error only happens when we deploy our service into AKS and is using managed identity. It doesn't happen when we are testing locally with a service principle account instead.

**To Reproduce**
Steps to reproduce the behavior. We used the code below along with recently upgraded:
- azure-sdk-bom:1.2.29
- spring-boot-starter-parent:3.3.5

 After downgrading the versions back to:
- azure-sdk-bom:1.2.28
- spring-boot-starter-parent:3.3.4

The issue disappeared, We also note that for both versions the `TokenRequestContext` seems to be the same for both version:
- scopes: [https://xxxx-cosmosdb-sql-nch-dev.documents.azure.com/.default]
- caeEnabled: false
- tenantId: null
- claims: null

***Code Snippet***
We use the following code to create the database client:

```java
client = CosmosClientBuilder()
  .endpoint(uri)
  .credential(tokenCredential)
  .perferredRegions(List.of("Swizerland North"))
  .consistencyLevel(ConsistencyLevel.BOUNDED_STALENSS)
  .userAgentSuffix(...)
  .directMode()
  .buildAsyncClient();
```

`tokenCredential` is obtained as:

```java
tokenCredential = isRunningLocal(env) ?
  new ClientSecretCredentialBuilder()
          .tenantId(xxx)
          .clientId(xxx)
          .clientSecret(xxx)
          .build() :
  new ManagedIdentityCredentialBuilder()
          .clientId(xxx)
          .build()
```

**Expected behavior**
No exception should be thrown and our application should query / update the database correctly

**Screenshots**

**Setup (please complete the following information):**
 - OS: Linux (containerized)
 - IDE: IntelliJ
 - Library/Libraries: azure-sdk-bom:1.2.29 
 - Java version: 21
 - App Server/Environment: Embedded netty server
 - Frameworks: spring-boot-starter-parent:3.3.5

If you suspect a dependency version mismatch (e.g. you see `NoClassDefFoundError`, `NoSuchMethodError` or similar), please check out [Troubleshoot dependency version conflict article](https://aka.ms/azsdk/java/dependency/troubleshoot) first. If it doesn't provide solution for the problem, please provide:
- verbose dependency tree (`mvn dependency:tree -Dverbose`)
- exception message, full stack trace, and any available logs

**Additional context**

**Information Checklist**
Kindly make sure that you have added all the following information above and checkoff the required fields otherwise we will treat the issuer as an incomplete report
- [ x ] Bug Description Added
- [ x ] Repro Steps Added
- [ x ] Setup information Added

**Comment by stevenylai** [comment]
For the question about `azure-sdk-bom` version compatibility with spring, I guess we can look up the mapping here: https://github.com/Azure/azure-sdk-for-java/wiki/Spring-Versions-Mapping

**Comment by FabianMeiswinkel** [comment]
This issue happens most likely due to a problem in the azure-cosmos-identity version you are using. Version 1.14.2 has the hotfix for it - see https://github.com/Azure/azure-sdk-for-java/blob/main/sdk/identity/azure-identity/CHANGELOG.md#1142-2024-11-15
