### ISSUE TITLE
[QUERY]  Pagination PageSize Issues with iterableByPage

### ISSUE THREAD

**Issue by Chen-hao-Huang** [Azure/azure-sdk-for-java#43020]
**Query/Question**
I'm trying to implement the pagination with iterableByPage or streamByPage for listing ResourceSkus but still getting all the objects in one page. Is there a way to tell if i'm missing anything in the implementation or is the server not honoring the page size?

`

      int pageSize = 500;
      log.info("pagedResponse filter:",filter);

      var pagedResponse = getAzureComputeManagerClient(request.getSubscriptionId()).virtualMachines().manager()
          .serviceClient()
          .getResourceSkus()
          .list(filter, includeExtendedLocations, com.azure.core.util.Context.NONE).iterableByPage(pageSize);

      PagedResponse<ResourceSkuInner> page = pagedResponse.iterator().next();
      page.getElements()
          .forEach(s -> resourceSkus.add(AzureComputeManagerTransforms.transformResourceSkusToProto(s)));
      String nextToken = page.getContinuationToken();
      log.info("nextToken", nextToken);

      log.info("List Resource Skus: {} resource skus found in subscription", resourceSkus.size());
`

***Why is this not a Bug or a feature Request?***
Not clear if it's the server or my implementation.

**Setup (please complete the following information if applicable):**
 - OS: ubuntu
 - IDE: vs code
 - Library/Libraries:        <groupId>com.azure.resourcemanager</groupId>
      <artifactId>azure-resourcemanager-compute</artifactId>
      <version>2.42.0</version>

**Comment by weidongxu-microsoft** [comment]
@Chen-hao-Huang 

The `pageSize` in `iterableByPage` is a hint for SDK.
```
    /**
     * Retrieve the {@link Iterable}, one page at a time, with each page containing {@code preferredPageSize} items.
     * <p>
     * It will provide same {@link Iterable} of T values from starting if called multiple times.
     *
     * @param preferredPageSize the preferred page size, service may or may not honor the page size preference hence
     * client MUST be prepared to handle pages with different page size.
     * @return {@link Iterable} of a pages
     */
    public Iterable<P> iterableByPage(int preferredPageSize) {
```

It only works when service accept a e.g. `maxpagesize` query parameter in its REST API. Unfortunately this query parameter does not exist on most ARM endpoints (include this one).
https://learn.microsoft.com/rest/api/compute/resource-skus/list?view=rest-compute-2024-07-01&tabs=HTTP

Therefore, the `pageSize` here to SDK is not appliable to this endpoint, and the backend just returns a page, with size of their choice.

**Comment by Chen-hao-Huang** [comment]
Is there a way to find out what the default pageSize is for this endpoint (or any other endpoints)? if there is any?

**Comment by weidongxu-microsoft** [comment]
I don't think there is a way to find the default pageSize.

Even if we tested out the current pageSize, there is no guarantee the backend would stick with this value and not change it overnight.

**Comment by Chen-hao-Huang** [comment]
Okay... thank you!

**Comment by weidongxu-microsoft** [comment]
For ARM resources, there is an alternative of Azure resource graph
https://github.com/Azure/azure-sdk-for-java/blob/main/sdk/resourcegraph/azure-resourcemanager-resourcegraph/src/test/java/com/azure/resourcemanager/resourcegraph/ResourceGraphTests.java#L36-L37

However, I've tried for "Microsoft.Compute/skus", it appears not an ARM resource, and not work on above query. (probably because it is more information than resource)
