### ISSUE TITLE
[BUG] The latest azure-search-documents preview java SDK libs are broken

### ISSUE THREAD

**Issue by Zubastick** [Azure/azure-sdk-for-java#43027]
**Describe the bug**
In the latest azure-search-documents java sdk libs starting from version 11.8.0-beta.1 speller is broken. It is not possible to set:

`
searchOptions.setSpeller(QuerySpellerType.LEXICON);
`
`
searchOptions.setQueryLanguage(queryLanguage);
 `

**To Reproduce**
Use azure-search-documents preview releases starting from 11.8.0-beta.1 and try to set speller LEXICON and query language

**Comment by alzimmermsft** [comment]
Thanks for reporting this @Zubastick, I've filed #43028 to resolve this problem.

**Comment by alzimmermsft** [comment]
@Zubastick, a new release of `azure-search-documents` has been made available
