### ISSUE TITLE
`azure-data-appconfiguration` Sample Issue

### ISSUE THREAD

**Issue by NanaXiong00** [Azure/azure-sdk-for-java#43137]
1.
**Section** [link1](https://github.com/Azure/azure-sdk-for-java/blob/main/sdk/appconfiguration/azure-data-appconfiguration/src/samples/java/com/azure/data/appconfiguration/ReadmeSamples.java#L377), [link2](https://github.com/Azure/azure-sdk-for-java/blob/main/sdk/appconfiguration/azure-data-appconfiguration/src/samples/java/com/azure/data/appconfiguration/ReadmeSamples.java#L389):
![Image](https://github.com/user-attachments/assets/cefebebc-2754-44cd-8dc7-b724d2c4d9dc)

**Reason:**
java.lang.NullPointerException: 'tokenCredential' and 'connectionString' both can not be null. Set one authentication before creating client.

**Suggestion:**
Add code:
```
.connectionString(connectionString)
```

@sandeep-sen, @joshfree,  @AngelosP, @jsquire and @YalinLi0312 for notification.

**Comment by mssfang** [comment]
@NanaXiong00 FYI, the purpose of this sample is to display the focused code snippet in the README. The line you refer to is excluded from the displayed sample and is only for passing the compilation. 

Open a PR: https://github.com/Azure/azure-sdk-for-java/pull/43183
