### ISSUE TITLE
[BUG] KafkaPropertiesBeanPostProcessor using a removed method in springboot 3.4

### ISSUE THREAD

**Issue by shalabi** [Azure/azure-sdk-for-java#43142]
**Describe the bug**
When starting up the server with spring boot 3.4:
```
api-server-1  | ***************************
api-server-1  | APPLICATION FAILED TO START
api-server-1  | ***************************
api-server-1  | 
api-server-1  | Description:
api-server-1  | 
api-server-1  | An attempt was made to call a method that does not exist. The attempt was made from the following location:
api-server-1  | 
api-server-1  |     com.azure.spring.cloud.autoconfigure.implementation.kafka.KafkaPropertiesBeanPostProcessor.getMergedProducerProperties(KafkaPropertiesBeanPostProcessor.java:23)
api-server-1  | 
api-server-1  | The following method did not exist:
api-server-1  | 
api-server-1  |     'java.util.Map org.springframework.boot.autoconfigure.kafka.KafkaProperties.buildProducerProperties()'
api-server-1  | 
api-server-1  | The calling method's class, com.azure.spring.cloud.autoconfigure.implementation.kafka.KafkaPropertiesBeanPostProcessor, was loaded from the following location:
api-server-1  | 
api-server-1  |     jar:nested:/app/app.jar/!BOOT-INF/lib/spring-cloud-azure-autoconfigure-5.18.0.jar!/com/azure/spring/cloud/autoconfigure/implementation/kafka/KafkaPropertiesBeanPostProcessor.class
api-server-1  | 
api-server-1  | The called method's class, org.springframework.boot.autoconfigure.kafka.KafkaProperties, is available from the following locations:
api-server-1  | 
api-server-1  |     jar:nested:/app/app.jar/!BOOT-INF/lib/spring-boot-autoconfigure-3.4.0.jar!/org/springframework/boot/autoconfigure/kafka/KafkaProperties.class
api-server-1  | 
api-server-1  | The called method's class hierarchy was loaded from the following locations:
api-server-1  | 
api-server-1  |     org.springframework.boot.autoconfigure.kafka.KafkaProperties: jar:nested:/app/app.jar/!BOOT-INF/lib/spring-boot-autoconfigure-3.4.0.jar!/
api-server-1  | 
api-server-1  | 
api-server-1  | Action:
api-server-1  | 
api-server-1  | Correct the classpath of your application so that it contains compatible versions of the classes com.azure.spring.cloud.autoconfigure.implementation.kafka.KafkaPropertiesBeanPostProcessor and org.springframework.boot.autoconfigure.kafka.KafkaProperties
api-server-1  | 
api-server-1 exited with code 1
```

***Exception or Stack Trace***
Problem is now has an argument and no zero argument method
```
class KafkaPropertiesBeanPostProcessor extends AbstractKafkaPropertiesBeanPostProcessor<KafkaProperties> {

 @SuppressWarnings("removal")
    @Override
    protected Map<String, Object> getMergedProducerProperties(KafkaProperties properties) {
        return properties.buildProducerProperties();
    }
}
```

**To Reproduce**

use spring 3.4.0

***Code Snippet***
Add the code snippet that causes the issue.

**Expected behavior**

**Screenshots**

**Setup (please complete the following information):**
 - IDE: [e.g. IntelliJ]
 - Library/Libraries: [e.g. com.azure:azure-core:1.16.0 (groupId:artifactId:version)]
 - Java version: [e.g. 8] 
 - App Server/Environment: [e.g. Tomcat, WildFly, Azure Function, Apache Spark, Databricks, IDE plugin or anything special]
 - Frameworks: [e.g. Spring Boot, Micronaut, Quarkus, etc] 

If you suspect a dependency version mismatch (e.g. you see `NoClassDefFoundError`, `NoSuchMethodError` or similar), please check out [Troubleshoot dependency version conflict article](https://aka.ms/azsdk/java/dependency/troubleshoot) first. If it doesn't provide solution for the problem, please provide:
- verbose dependency tree (`mvn dependency:tree -Dverbose`)
- exception message, full stack trace, and any available logs

**Additional context**

**Information Checklist**
Kindly make sure that you have added all the following information above and checkoff the required fields otherwise we will treat the issuer as an incomplete report
- [x] Bug Description Added
- [x] Repro Steps Added
- [x] Setup information Added

**Comment by saragluna** [comment]
Thanks for reaching out, we have fixed this issue, and please wait for our next release. @moarychan fyi.

**Comment by moarychan** [comment]
Fixed in https://github.com/Azure/azure-sdk-for-java/pull/43098
