### ISSUE TITLE
OpenAIServiceVersion is not compiling while using com.azure:azure-ai-openai:1.0.0-beta.12

### ISSUE THREAD

**Issue by dakmehul** [Azure/azure-sdk-for-java#43179]
I am upgrading com.azure:azure-ai-openai from "1.0.0-beta.7" to "1.0.0-beta.12". While doing that code is not compiling due to  OpenAIServiceVersion class. Can we please fix ASAP?

**Comment by alzimmermsft** [comment]
Thanks for filing this issue @dakmehul, could you go into more detail on what broke?

@mssfang could you follow-up once there is more information about this issue.

**Comment by mssfang** [comment]
@dakmehul What is the error message you are getting when compiling the source code?
