### ISSUE TITLE
Add Default Logging and Redactions of Logs

### ISSUE THREAD

**Issue by alzimmermsft** [Azure/azure-sdk-for-java#4328]
Add a default, always-on, logger and enhance logging to redact sensitive information (secrets, passwords, etc) from the logs.

**Comment by amishra-dev** [comment]
In addition to redacting, we also must implement that if a task is running for more than 2 seconds we write the CPU/Memory (Disk and network if we can) into the default log.

**Comment by joshfree** [comment]
@samvaity could you please drive this to resolution for Preview 5?

**Comment by rickle-msft** [comment]
I'm not sure if I've shared this elsewhere, but we'd really like to get the items discussed in #5130 included in whichever PR related to logs comes out next

**Comment by rickle-msft** [comment]
Another customer request is to log which retry number we are on. See [here](https://github.com/Azure/azure-sdk-for-java/issues/5180#issuecomment-540740721)

**Comment by JonathanGiles** [comment]
@samvaity Can this issue be closed (for redaction), with the follow-up requests filed in new issues that are not considered release blocking?

**Comment by samvaity** [comment]
Closing this as the redaction of sensitive information from logs is already merged in https://github.com/Azure/azure-sdk-for-java/pull/5688

New issues filed for the other two logging improvements: #5773, #5774
