### ISSUE TITLE
Flakey test: ReactorNettyClientTests.testConcurrentRequests

### ISSUE THREAD

**Issue by mitchdenny** [Azure/azure-sdk-for-java#4357]
We are experiencing some flakey tests in the Java build pipeline. The following retained build shows the issue:

https://dev.azure.com/azure-sdk/public/_build/results?buildId=64773&view=logs&j=8d81b87e-4d26-5175-d51a-680d334119d9

The error is:

```
[ERROR] Failures: |  
-- | --
  | [ERROR]   ReactorNettyClientTests.testConcurrentRequests expectation "expectNext(1100000000)" failed (expected: onNext(1100000000); actual: onError(reactor.netty.http.client.HttpClientOperations$PrematureCloseException: Connection prematurely closed BEFORE response))
```

This can happen on macOS and Linux but I haven't observed it on Windows (but that could just be lucky). It can mappen on either the LTS or Java 8 builds so that doesn't appear to be a factor. It is happening often enough that it is starting to slow down PR times.

**Comment by alzimmermsft** [comment]
This was resolved in #18911
