### ISSUE TITLE
[Event Hubs] Design Event Processor Host

### ISSUE THREAD

**Issue by conniey** [Azure/azure-sdk-for-java#4371]
* Propose a new API design for Event Processor Host
* Figure out if EPH should live in its own package or get coupled into the existing azure-eventhubs package
  * If we bundle it into azure-eventhubs, should it be like SLF4J where people can specify implementation packages in the classpath and at runtime, we load it up?

**Comment by srnagar** [comment]
https://github.com/Azure/azure-sdk-for-java/pull/4582
