### ISSUE TITLE
What's the plan for supporting Storage Tables in the new Azure Storage Java Client Library (v11)?

### ISSUE THREAD

**Issue by mkargar** [Azure/azure-sdk-for-java#4387]
Looking at [this](https://github.com/Azure/azure-sdk-for-java/tree/master/storage/data-plane) seems that there's no support for [Storage Tables](https://azure.microsoft.com/en-us/services/storage/tables/) in the new client library. Is there any plans to support Tables in the the new Storage SDK architecture ?

**Comment by praries880** [comment]
Thank you for opening this issue! We are routing it to the appropriate team for follow up.

**Comment by rickle-msft** [comment]
Hi, @mkargar. There is no plans to support Tables in the Storage SDKs. This service has been moved to the CosmosDB, so you will have to check with them about their plans for an SDK.
