### ISSUE TITLE
ScheduledEnqueueTimeUtc not working in java api

### ISSUE THREAD

**Issue by jensrohloff** [Azure/azure-sdk-for-java#440]
the ScheduledEnqueueTimeUtc isn't working. as default jackson formats the date to epoch timestamp. azure requires it to be RFC2616 (http://msdn.microsoft.com/en-us/library/azure/hh780742.aspx) 
For example, “Sun, 06 Nov 1994 08:49:37 GMT”. It is required to set the timezone to GMT as well.

mapper = new ObjectMapper();
SimpleDateFormat simpleDateFormat = new SimpleDateFormat("EEE, dd MMM yyyy HH:mm:ss zzz");
simpleDateFormat.setTimeZone(TimeZone.getTimeZone("GMT"));
mapper.setDateFormat(simpleDateFormat);

the BrokerPropertiesMapper.java should use te dateFormat for both methods.

**Comment by AssafAvailo** [comment]
Hey any workarounds can be done ?

**Comment by jensrohloff** [comment]
AssafAvailo , you need a fork if it hasn't been fixed yet.
