### ISSUE TITLE
is there any way to set hostname of VirtualMachine through SDK.I am able to set the computer name.But not the hostname.Please suggest

### ISSUE THREAD

**Issue by sumangit789** [Azure/azure-sdk-for-java#4409]
We are using Azure Java SDK.
I want to set the hostname while creating the Virtual Machien 
is there any way to set hostname of VirtualMachine through SDK.
I am able to set the computer name.But not the hostname.
Please suggest

**Comment by kurtzeborn** [comment]
Thank you for opening this issue!  I'm not sure how to answer this question, so I'm routing to the appropriate team who I think can.

**Comment by Drewm3** [comment]
@sumangit789, could you elaborate on what you mean between "compute name" and "hostname"? I normally think of these as the same thing. Were you possibly meaning one of these to be the name of the server as seen by the guest OS and the other one being the name of the VM resource within Azure Resource Manager? 

If yes, then the name in Azure Resource Manager cannot be changed. The name in the guest OS can be changed using the tools appropriate for the specific OS running.

**Comment by Drewm3** [comment]
@sumangit789, I am going to close this for now since we have not heard back from you. Please open a new issue if this is still a problem.
