### ISSUE TITLE
Service Bus Session Support

### ISSUE THREAD

**Issue by pizerg** [Azure/azure-sdk-for-java#441]
Right now I think it's not possible to receive a message on a queue that uses Session filtering only by one SessionId as we can do in C# with the following code:

MessageSession receiver = null;
receiver = queueClient.AcceptMessageSession(msg.ReplyToSessionId);
BrokeredMessage receivedMessage = receiver.Receive(TimeSpan.FromSeconds(timeout));

Are there any plans to include this feature in the java SDK ?

**Comment by BillAtPros** [comment]
+1 for SessionID Support. This is critical for handling message groups or large message which require splitting.

**Comment by martinsawicki** [comment]
the service bus is not in this repo anymore, so if this is still an issue, it should go there:
https://github.com/azure/azure-service-bus-java
