### ISSUE TITLE
Poor performance on ServiceBus client creation

### ISSUE THREAD

**Issue by pizerg** [Azure/azure-sdk-for-java#442]
When executing the following code:

---

Configuration config = ServiceBusConfiguration.configureWithWrapAuthentication(_namespace, _issuer, _issuerKey, _serviceRootUri, _wrapRootUri);
ServiceBusContract contract = ServiceBusService.create(config);

---

It usually takes more than 1 minute (and sometimes even more) to complete the .create(config) instruction on not powerful devices such as Raspberry Pi or other embedded systems. This code is usually called once during initialization but it's slow performance makes testing really painful.

I'm not really sure but I think ServiceLoader is the one to blame here and I don't really know why it's used instead other newer and much faster alternatives (ServiceLoader also causes OSGi issues as it relies on the ClassLoader)

**Comment by martinsawicki** [comment]
the service bus is not in this repo anymore, so if this is still an issue, it should go there:
https://github.com/azure/azure-service-bus-java
