### ISSUE TITLE
Remove hard-coded version numbers from client libraries

### ISSUE THREAD

**Issue by conniey** [Azure/azure-sdk-for-java#4426]
SDK version numbers and names are currently hardcoded in Client libraries. 
* Application Configuration #3141 
* Event Hubs https://github.com/Azure/azure-sdk-for-java/pull/4416#discussion_r303285252
...

Provide a general way to get these values.
https://azuresdkspecs.z5.web.core.windows.net/JavaSpec.html#general-telemetry

**Comment by sima-zhu** [comment]
Remove Eventhub hard-coded versioning needs one more action item: Move versioning stuff from amqp to eventhub package.
Issue filed: https://github.com/Azure/azure-sdk-for-java/issues/6582

Will close this one and track issue over this after the code check in.
