### ISSUE TITLE
Research Migrating Storage Tests

### ISSUE THREAD

**Issue by alzimmermsft** [Azure/azure-sdk-for-java#4444]
Research migrating the Storage Blob tests from using Groovy and Spock to Java and JUnit

**Comment by JonathanGiles** [comment]
I've ported azure-core to junit 5 to get a sense of the difficulty in moving to this. It isn't difficult - it took me about 30 minutes to do azure-core (and subprojects). I think moving to JUnit 5 is a good first step. From there we can explore parameterised tests either through built-in annotations such as [CsvSource](https://junit.org/junit5/docs/current/user-guide/#writing-tests-parameterized-tests-sources-CsvSource), or else external plugins to JUnit, such as [Spockito](https://github.com/tools4j/spockito).

**Comment by JonathanGiles** [comment]
Draft PR was published here: #4455.

**Comment by JonathanGiles** [comment]
I've provided sample code for a simple case of test parameterisation [here](https://github.com/Azure/azure-sdk-for-java/pull/4455#issuecomment-512570559)
