### ISSUE TITLE
[ArchBoard] Rename dequeueMessages to getMessages

### ISSUE THREAD

**Issue by sima-zhu** [Azure/azure-sdk-for-java#4457]

**Comment by tg-msft** [comment]
The proposal is to change `DequeueMessages` to `GetMessages` or possibly `ReceiveMessages` (which aligns more with EventHubs)?

Would there be a similar change from `EnqueueMessage` to `AddMessage`?

**Comment by sima-zhu** [comment]
@rickle-msft 
Xstore team suggested a more general strategy for all get/set APIs
(e.g. enqueue/dequeue, get/setProperties, get/setAccessPolicies)

**Comment by rakshith91** [comment]
Note: This is called as recieve_messages in Python.

**Comment by HarshaNalluru** [comment]
In JS, I'm inclined to go with some variant of "receive messages" instead of "dequeue" similar to servicebus and eventhubs.

**Comment by kurtzeborn** [comment]
The naming in the REST endpoint is "getMessages" so that aligns with this suggestion.  XStore team agrees with using getMessages instead of dequeueMessages.

Concern: it might be confusing/unexpected to developers that this makes a REST call if it's named getMessages (which they might assume is only accessing local data).

@JonathanGiles, what do you think about this?

**Comment by JonathanGiles** [comment]
The Java team is trending towards a naming convention where local operations drop any prefix, e.g. 'get', 'is', 'set' will not be present. Remote operations on the service client class would be the only place where prefixes would be used, and they would continue to be named as appropriate for the operation - in this case 'getMessages'. Even if we don't make this change, the proposal to use 'get' for a remote operation is fine with me.

**Comment by rickle-msft** [comment]
I'm fine with get/set for remote operations if local operations don't have a prefix (which is a change from what Storage currently has iirc). 

If local operations do also use get/set, then piggy-backing on what Scott mentioned, my concern with remote operations sharing get/set with local operations is that until now, our remote operations returned Response<T> whereas now many of them return just T. So previously it should have been clear based on the return type wether getX was remote or local, but with just T, it really only furthers the confusion.

**Comment by alzimmermsft** [comment]
@tg-msft @rickle-msft @rakshith91 @HarshaNalluru 

Have we reached an agreement on whether we want to move forward with this renaming? Otherwise I propose we close on this issue.

**Comment by tg-msft** [comment]
We're about to start the next major round of API reviews.  Let's all add this suggestion in the QueueClient APIs and let everyone hash it out there.

**Comment by sima-zhu** [comment]
Working on it.
