### ISSUE TITLE
Change the messageText and messageId order for updateMessage

### ISSUE THREAD

**Issue by sima-zhu** [Azure/azure-sdk-for-java#4458]
Proposed order: messageId, popReceipt, messageText, visibilityTimeout
See what the other languages are doing, if it is consistent talk with them and discussing this change

**Comment by tg-msft** [comment]
In .NET we have

```C#
public virtual async Task<Response<UpdatedMessage>> UpdateMessageAsync(
    string messageText,
    string messageId,
    string popReceipt,
    TimeSpan visibilityTimeout = default,
    CancellationToken cancellationToken = default)
```

which puts `messageText` first to match `EnqueueMessage`.

I have no problem making this change if other languages would like to.

**Comment by rakshith91** [comment]
In Python, we have 
`
def update_message(self, message, visibility_timeout=None, pop_receipt=None,
                       content=None, timeout=None, **kwargs):
`
It can also be used to update the contents of the message.

**Comment by HarshaNalluru** [comment]
JS
```typescript

// * @memberof MessageIdClient

  public async update(
    popReceipt: string,
    message: string,
    visibilityTimeout?: number,
    options: MessageIdUpdateOptions = {}
  ): Promise<Models.MessageIdUpdateResponse> 
```

**Comment by kurtzeborn** [comment]
XStore team agrees that we should have the same order of parameters on these.  The slight preference is towards this ordering: messageText, popReceipt, visibilityTimeout, options.  This seems to order them by most used to least used.

**Comment by JonathanGiles** [comment]
When I raised this with Sima, it was related to my preference that method arguments flow from arguments that identify the object to perform the operation on, and then to follow that with the values to provide to the object. In this way, it reads out as "update messageID / popReceipt to have a messageText as specified". Currently it reads "update to messageText on messageID / popReceipt", which feels back to front. I have a very weak opinion on this though.

**Comment by alzimmermsft** [comment]
Closing this as Java is consistent with .NET
