### ISSUE TITLE
DOC: Media Serivces 'Getting Started' Points to .NET SDK

### ISSUE THREAD

**Issue by sedouard** [Azure/azure-sdk-for-java#446]
Not directly a bug on the sdk library -- but someone should know:

Create a new media service - Select Java in the getting started dialog. The java code sample appears however the 'Download the SDK' link points to the nuget package: http://www.nuget.org/packages/windowsazure.mediaservices.

This is clearly not the intended sdk for java.

**Comment by martinsawicki** [comment]
obsolete. Also, Media SDK is not part of this repo anymore.
