### ISSUE TITLE
Veracode (CWE ID 611)

### ISSUE THREAD

**Issue by mariolavoro85** [Azure/azure-sdk-for-java#4466]
## Actual Behavior
Veracode Scan failed, reason: Improper Restriction of XML External Entity (CWE ID 611)

Azure DevOps pipeline task: Veracode Upload and Scan

References: 
[CWE](https://cwe.mitre.org/data/definitions/611.html) 
[OWASP](https://github.com/OWASP/CheatSheetSeries/blob/master/cheatsheets/XML_External_Entity_Prevention_Cheat_Sheet.md) 
[WASC](https://webappsec.pbworks.com/XML-External-Entities)

Files with issue:

com/microsoft/azure/servicebus/management/

RuleDescriptionSerializer.java
ManagementClientAsync.java
TopicRuntimeInfoSerializer.java
SubscriptionDescriptionSerializer.java
NamespaceInfoSerializer.java
SubscriptionRuntimeInfoSerializer.java
QueueDescriptionSerializer.java
TopicDescriptionSerializer.java
SubscriptionDescriptionSerializer.java
QueueDescriptionSerializer.java
QueueRuntimeInfoSerializer.java
TopicDescriptionSerializer.java
RuleDescriptionSerializer.java

## Expected Behavior
Veracode Scan success.

## Versions  
- Release: [2.0.0](https://github.com/Azure/azure-service-bus-java/releases/tag/2.0.0)

### Note:
This library is required to use the Azure Service-Bus product, without the Veracode validation, our product cannot go in the production environment.

Library **azure-servicebus** : [Maven repository](https://mvnrepository.com/artifact/com.microsoft.azure/azure-servicebus/2.0.0)

**Comment by jfggdl** [comment]
@nemakam, would you please look into this potential security vulnerability?

**Comment by jfggdl** [comment]
@mariolavoro85, we have added this issue to our backlog. Please check on this issue periodically if you need the status of this issue.
