### ISSUE TITLE
[QUERY] should azure endpoint (Azure) be cached?

### ISSUE THREAD

**Issue by vihanp** [Azure/azure-sdk-for-java#4486]
**Query/Question**
In my service that is managing Azure resources on behalf of it's user, I'm obtaining azure endpoint like this:

```
Azure azure = Azure.configure()
                .withLogLevel(logLevel)
                .authenticate(credentials)
                .withSubscription(subscriptionId);
```
We estimate to have like 100 accounts with different creds/subscription id.

Can/should this Azure instance be cached in between calls  and what's correct cache evict strategy (how long should one authenticated Azure client be cached)? I assume it is safe to share same Azure authenticated instance between threads...

Or is it premature-optimization attempt on my side and Azure class is fine to instantiate in each service call that want to access Azure?

**Comment by kurtzeborn** [comment]
You appear to be using the fluent libraries, so I'm moving this to the appropriate repo.

**Comment by kurtzeborn** [comment]
Issue moved to [Azure/azure-libraries-for-java #788](https://github.com/Azure/azure-libraries-for-java/issues/788) via [**ZenHub**](https://www.zenhub.com/)
