### ISSUE TITLE
[BUG] New version of SDK did not using Maven relocation for changed Maven coordinates

### ISSUE THREAD

**Issue by mnriem** [Azure/azure-sdk-for-java#4490]
**Describe the bug**
New version of SDK did not using Maven relocation for changed Maven coordinates

**Expected behavior**
For a user of the previous version of the SDK it is unclear the newer version of the SDK has been relocated. Maven supplies a mechanism to do so, see https://maven.apache.org/guides/mini/guide-relocation.html 

Please perform the steps in the guide mentioned above so users get a relocation message

**Comment by loarabia** [comment]
Hi @mnriem Can you say explicitly which version you're referring to and which SDK? We have a number of libraries both in preview and released and I want to make sure I understand the request here.

**Comment by mnriem** [comment]
Hi @loarabia,

I used the following dependency for the new Cosmos SDK

```
<dependency>
  <groupId>com.microsoft.azure</groupId>
  <artifactId>azure-cosmos</artifactId>
  <version>3.0.0</version>
  <scope>compile</scope>
</dependency>
```

And it was previously available using:

```
<dependency>
    <groupId>com.microsoft.azure</groupId>
    <artifactId>azure-cosmosdb</artifactId>
    <version>3.0.0-beta-3</version>
</dependency>
```

And no relocation was used there.

To facilitate relocation one should release an additional POM file at the old coordinates as follows:

```
<project>
  <modelVersion>4.0.0</modelVersion>
  <groupId>com.microsoft.azure</groupId>
  <artifactId>azure-cosmosdb</artifactId>
  <version>3.0.0</version>
  <distributionManagement>
    <relocation>
      <groupId>com.microsoft.azure</groupId>
      <artifactId>azure-cosmos</artifactId>
    </relocation>
  </distributionManagement>
</project>
```

If any other new SDK has been released with a new groupId or artifactId it would suffer from the same problem. If this gets fixed folks get warned automatically. Note once you have done the relocation for this 3.0.0 version the next version after that obviously would not need the relocation.

**Comment by loarabia** [comment]
Thanks @mnriem  for the update. I've tagged this so the right part of the team should take a look.
