### ISSUE TITLE
mvn compile has error

### ISSUE THREAD

**Issue by mikehsieh97** [Azure/azure-sdk-for-java#450]
I am getting the following issue when I use 'mvn compile'

[INFO] Microsoft Azure SDK for Management ................ FAILURE [  6.972 s]
[INFO] Microsoft Azure SDK for Website Management ........ SKIPPED
[INFO] Microsoft Azure SDK for Storage Management ........ SKIPPED
[INFO] Microsoft Azure SDK for SQL Management ............ SKIPPED
[INFO] Microsoft Azure Core Test Client API .............. SKIPPED
[INFO] Microsoft Azure SDK for Compute Management ........ SKIPPED
[INFO] Microsoft Azure SDK for Media Services Management . SKIPPED
[INFO] Microsoft Azure SDK for Scheduler Management ...... SKIPPED
[INFO] Microsoft Azure SDK for Network Management. ....... SKIPPED
[INFO] Microsoft Azure SDK for Media Services ............ SKIPPED
[INFO] Microsoft Azure SDK for Service Bus ............... SKIPPED
[INFO] Microsoft Azure SDK for Service Runtime ........... SKIPPED
[INFO] Microsoft Azure SDK tracing logger utility ........ SKIPPED
[INFO] Microsoft Azure SDK ............................... SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 01:39 min
[INFO] Finished at: 2014-12-11T12:17:41-05:00
[INFO] Final Memory: 13M/41M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal on project azure-management: Could not resolve dependencies for project com.microsoft.azure:azure-management:
jar:0.7.0: Could not find artifact com.microsoft.azure:azure-core:jar:tests:0.7.0 in central (http://repo.maven.apache.org/maven2) -> [Help
1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/DependencyResolutionException
[ERROR]
[ERROR] After correcting the problems, you can resume the build with the command
[ERROR]   mvn <goals> -rf :azure-management

**Comment by markcowl** [comment]
This should be fixed in the dev branch please reopen if you see a recurrence
