### ISSUE TITLE
[API] Storage APIs have a couple places where we do not allow the customer to pass a transactional md5

### ISSUE THREAD

**Issue by rickle-msft** [Azure/azure-sdk-for-java#4508]
~Investigate Java's ability to support a custom polynomial for CRC.~ May fall back to MD5 if this is not possible. ~Needs arch board guidance for checksums~

**Comment by rickle-msft** [comment]
service feature

**Comment by kurtzeborn** [comment]
@rickle-msft could you provide the details here for the questions you have for the arch board and @JonathanGiles can chime with his opinion and clarify whether this even needs to be reviewed by the entire arch board.

**Comment by rickle-msft** [comment]
@JonathanGiles 
The question about CRC specifically is that the Storage implementation uses a custom polynomial that we are not sure we can support in Java. Either it's not doable without using JNI, which is really bad, or it gives no appreciable benefit over MD5, which defeats the purpose. I imagine Jonathan can resolve this independently.

The question that needs more formal guidance is on how we expose checksumming across the SDK. We completely omitted it in v11, but in v8, we had full support for it in a variety of scenarios. We exposed it as an optional parameter that could be attached to certain transactions and would be validated by the service upon receiving data (this is different from setting the Content MD5 property on the blob, which doesn't get validated at all). We also could calculate the MD5 on uploads and downloads and either set it with the final put call or check it against the received contentMD5 header after all the data had been streamed. These were fairly complicated operations that had considerations in the way of usability and performance. It's not clear to us whether we should pass options, accept a flag, provide a stand alone stream-wrapper that the customer should create themselves, etc.

**Comment by kurtzeborn** [comment]
Decision was made in xstore sync meeting previously to just use MD5 for Java here.

**Comment by jaschrep-msft** [comment]
Closing. MD5 is a settable field.

**Comment by rickle-msft** [comment]
I noticed there are a couple places where we do not allow the customer to pass a transactional md5

**Comment by joshfree** [comment]
Updating title to reflect the work that's actually being tracked with this issue

**Comment by joshfree** [comment]
Fixed by https://github.com/Azure/azure-sdk-for-java/pull/5947

**Comment by joshfree** [comment]
Closing now that #5947 has been merged.
