### ISSUE TITLE
Refine the return value of API. Rewrite the manual crafted object, e.g. DirectoryInfo etc

### ISSUE THREAD

**Issue by sima-zhu** [Azure/azure-sdk-for-java#4522]
Queue and File
E.g. 
**create** return Mono of Void
**delete**
**getProperties**

**Comment by sima-zhu** [comment]
**createSnapshot**
We will either return a snapshotId or return client to get the snapshot

**Comment by kurtzeborn** [comment]
@sima-zhu can you clarify what is wanted with this issue.

**Comment by sima-zhu** [comment]
This one has already addressed by context PR. Min overload return T, and Max overload return Resposne<T>.
We can close this for now.
