### ISSUE TITLE
Return URL instead of string in swagger

### ISSUE THREAD

**Issue by sima-zhu** [Azure/azure-sdk-for-java#4523]

**Comment by kurtzeborn** [comment]
@alzimmermsft, you were suspicious this may not be fixable.  Please take a look.

**Comment by alzimmermsft** [comment]
Swagger doesn't support URL in an intuitive way and would require changes to the core generator. Given that we have already added convenience methods/functionality to handle the conversion of URLs in the clients I think it is safe to close this issue as can't/won't be done.
