### ISSUE TITLE
Parent client <-> Child client

### ISSUE THREAD

**Issue by sima-zhu** [Azure/azure-sdk-for-java#4524]
Currently in queue and file, we are only able to get child client from parent. E.g. ShareClient.getDirClient

We are lack of ShareClient.getFileServiceClient.

We need to provide a round trip ticket.
@rickle-msft @jaschrep-msft @alzimmermsft

**Comment by kurtzeborn** [comment]
@alzimmermsft, you were suspicious this wasn't necessary.  Please take a look.

**Comment by alzimmermsft** [comment]
Closing this as we plan to remove this client traversal from Blobs and Files runs into some issues around how to traverse up from a file or directory client as they could have different parents based on the file/directory structure.
