### ISSUE TITLE
 Refine the return value of forceCloseHandles API

### ISSUE THREAD

**Issue by sima-zhu** [Azure/azure-sdk-for-java#4525]
We return Iterable currently which might not make sense to customer. Think about to return how many handles actually closed.

Need two APIs:
1. with handleId as arg
1. without args for forceCloseAll

**Comment by sima-zhu** [comment]
@alzimmermsft

**Comment by kurtzeborn** [comment]
@alzimmermsft, you were saying the only useful data the REST api returns is integers.  Take a look and if that's correct, there's not much we can do here, so it should be closed.

**Comment by alzimmermsft** [comment]
The return type of the methods have been changed to `PagedFlux<Integer>` and `PagedIterable<Integer>` which is correct based on the API documentation. The API will need to be updated to include better overloads.

**Comment by vhvb1989** [comment]
No need to add a new API overload for `closeAll()` since this method can take an asterisk ('*') as a wildcard string to specify all handles and that is documented in JavaDoc

**Comment by vhvb1989** [comment]
Updating issue to add support to API to use x-ms-recursive header
