### ISSUE TITLE
Remove getProperties call for share file download to file

### ISSUE THREAD

**Issue by sima-zhu** [Azure/azure-sdk-for-java#4527]

**Comment by rickle-msft** [comment]
Of particular note, there should not be a get properties call before downloads are made. Refer to v11 for more details.

**Comment by kurtzeborn** [comment]
Removing @rickle-msft since he's headed on vacation for 3 weeks.

**Comment by sima-zhu** [comment]
It is already been addressed by different PRs. Alan has another one regarding inputstream and outputstream. Will follow up on that one.

**Comment by rickle-msft** [comment]
@sima-zhu

**Comment by rickle-msft** [comment]
We should also be sure to incorporate the data integrity fixes we added to blobs.

**Comment by ibrahimrabab** [comment]
Closing this issue since we are unable to extract all information for ShareFileProperties through the downloadWithResponse call (such as FileSmbProperties). Returning any null values can result in breaking behavior for the user. Closing as cannot be done.
