### ISSUE TITLE
Rename Queue and File service client.

### ISSUE THREAD

**Issue by sima-zhu** [Azure/azure-sdk-for-java#4532]

**Comment by sima-zhu** [comment]
Leave FileServiceProperties as it is for first PR as it asked swagger change

**Comment by tg-msft** [comment]
.NET currently has `BlobServiceClient`/`QueueServiceClient`/`FileServiceClient`.  We discussed `BlobStorageClient` a long time ago and back then `BlobServiceClient` was preferred.  I don't feel strongly and can move to whatever the Storage team prefers.

**Comment by HarshaNalluru** [comment]
Just like the .NET, JS names are `BlobServiceClient`/`QueueServiceClient`/`FileServiceClient` currently.
Need to discuss this with storage JS team and know their opinions.

**Comment by kurtzeborn** [comment]
XStore team's preference is to do another preview using the `*ServiceClient` naming convention and see if there is even one comment about this being confusing.  If there is we'll revisit.
