### ISSUE TITLE
Add tracing support for Identity

### ISSUE THREAD

**Issue by samvaity** [Azure/azure-sdk-for-java#4548]
Add tracing context to Identity package
Add T with Response "overload in sync and async Identity package.

**Comment by samvaity** [comment]
Blocked by Identity package work to update with pluggable Http pipeline.

**Comment by joshfree** [comment]
Blocked by https://github.com/Azure/azure-sdk-for-java/issues/5284

**Comment by joshfree** [comment]
Linking to MSAL4j work item (https://github.com/AzureAD/microsoft-authentication-library-for-java/issues/115) that unblocks Azure.Identity (#5284) which in turn unblocks this issue, and finally Azure Monitor:

**Comment by joshfree** [comment]
With the February 2020 release, this work in azure-identity is now unblocked

**Comment by joshfree** [comment]
@g2vinay can you please sync up with @samvaity to get up to speed on this work item and then work to make sure that at least an initial bare bones tracing PR for azure-identity makes it into the April release?

**Comment by g2vinay** [comment]
@joshfree , this was shipped in march release.
Closing this issue now.
