### ISSUE TITLE
General feedback of the SDK

### ISSUE THREAD

**Issue by dimitrovvlado** [Azure/azure-sdk-for-java#455]
Hi All,

I've been using the SDK version 0.6.0 for a couple of weeks now and found some weird design decisions which I've decided to share. In general, I am happy with the SDK, and the way functionalities are separated in several .jar files. But there are several things that are really annoying:

-> Here's the code example of what a connection configuration would look like:

ManagementConfiguration.configure(new URI(uri), subscriptionId, keyStoreLocation, keyStorePassword, KeyStoreType.jks);

If I am a system administrator, providing some keystore location would be a great idea. But as a developer, who holds his configuration (certificate) either in DB or in some other resource in the network, I need to create a local file every time I need to establish a  connection. This is simply not acceptable in a distributed environment and provides overhead instead of simplicity.

-> If I want to list all available locations, by using the ManagementClient, the java code that I need to write is 

managementClient.getLocationsOperations().list(). 

What I find extremely odd is that I need to handle IOException, ParserConfigurationException and SAXException. Why do I need to handle all of those? Even if I put a retry logic, I'll end up with the same exception - for instance SAXException. Even throwing an IOException here is questionable, because if the SDK is being used as part of a larger system (this is my case), there would be a more generic way to deal with IO errors. IMO throwing a RuntimeException is sufficient.

-> Here's the code for retrieving all affinity groups:

managementClient.getAffinityGroupsOperations().list().getAffinityGroups() 

which returns a list of AffinityGroup objects. However, if I want to get a single group by name, the code would look like this

managementClient.getAffinityGroupsOperations().get({someId})

and it will NOT return a single AffinityGroup object, but rather some other object (response) which holds the same information as the AffinityGroup, but is totally a different class. Can you imagine the overhead if some dev wants to perform some data structure operations by using for example a Comparator?

-> I could not find a way to setup a proxy. Using system properties is not the right way to go, because if a dev (me for instance :) ) wants to have a couple of connections in the same process with different proxy servers (one for each subscription), I will not be able to do it. 

Once again - I find the azure SDK a good library  and hope to see it evolve in the future.

Regards,
Vladimir

**Comment by markcowl** [comment]
@dimitrovvlado Thanks for the feedback, we will look at your suggestions in detail

**Comment by dimitrovvlado** [comment]
It seems, that the only way to setup a proxy to the http client is through system properties. On the other hand, the client implementations (e.g. WebSiteManagementClientImpl) take HttpClientBuilder as an argument. Is there a recommended way to set the proxy settings to that builder?
I tried injecting some settings through reflection, but this seems to break the library. In this case, is there a recommended approach on manually instantiating the WebSiteManagementClientImpl?

**Comment by jianghaolu** [comment]
@dimitrovvlado
Hi Vladimir,

I'm cleaning up some of the old issues and I came across. In today's library it's easy to set up proxy through `Azure.configure().withProxy(new java.net.Proxy(...))`. Please feel free to take a look.

With that being said, we are only offering ARM resources, storage, compute, network, key vault, redis cache with the upcoming release end of this month. Web app service is scheduled to be released by end of the year. 

Also, we are throwing unchecked exceptions for all operations. IOExceptions are wrapped in RuntimeException, and CloudExeption is unchecked now.

Please feel free to try it out in the master branch.

Azure Service Management, a.k.a. the 0.9.x version of the Azure SDK for Java, is in maintenance mode. I'm closing this issue as we won't address these issues in 0.9 branch. Please reopen if there's a blocking issue for you in 0.9 or you have anything you would like to add for master branch.

Thanks!
Jianghao
