### ISSUE TITLE
Support Azure AD authentication tokens

### ISSUE THREAD

**Issue by avranju** [Azure/azure-sdk-for-java#456]
Currently, the Azure SDK has direct support only for certificate based authentication. There is a hacky workaround to make it work with Azure AD access tokens but it's not very straightforward. Here's an example:

```java
private static Configuration getConfiguration(@NotNull String subscriptionId) throws SAXException, ParserConfigurationException, XPathExpressionException, IOException {
        SubscriptionInfo subscriptionInfo = getSubscriptionInfoFromToken(subscriptionId);
        ClassLoader old = Thread.currentThread().getContextClassLoader();
        Thread.currentThread().setContextClassLoader(AzureSDKHelper.class.getClassLoader());

        try {
            // create a default configuration object
            Configuration configuration = ManagementConfiguration.configure(
                    URI.create(subscriptionInfo.managementURI),
                    subscriptionId, null, null, KeyStoreType.pkcs12);

            // replace the credential provider with a custom one that does nothing
            configuration.setProperty(
                    ManagementConfiguration.SUBSCRIPTION_CLOUD_CREDENTIALS,
                    new EmptyCloudCredentials(subscriptionId));

            // remove the SSL connection factory in case one was added; this is needed
            // in the case when the user switches from subscription based auth to A/D
            // sign-in because in that scenario the CertificateCloudCredentials class
            // would have added an SSL connection factory object to the configuration
            // object which would then be used when making the SSL call to the Azure
            // service management API. This tells us that the configuration object is
            // reused across calls to ManagementConfiguration.configure. The SSL connection
            // factory object so configured will attempt to use certificate based auth
            // which will fail since we don't have a certificate handy when using A/D auth.
            configuration.getProperties().remove(ApacheConfigurationProperties.PROPERTY_SSL_CONNECTION_SOCKET_FACTORY);

            return configuration;
        } finally {
            Thread.currentThread().setContextClassLoader(old);
        }
    }
```

`EmptyCloudCredentials` looks like this:

```java
public class EmptyCloudCredentials extends SubscriptionCloudCredentials {
    private final String subscriptionId;

    public EmptyCloudCredentials(String subscriptionId) {
        this.subscriptionId = subscriptionId;
    }

    @Override
    public String getSubscriptionId() {
        return subscriptionId;
    }

    @Override
    public <T> void applyConfig(String profile, Map<String, Object> properties) {
        // all of our logic is in the AuthTokenRequestFilter and the AzureSDKManagerADAuthDecorator
        // classes; this is a "token" cloud credentials implementation (pun intended).
    }
}
```

When creating a client object we supply a request filter object like so:

```java
ComputeManagementClient client = ComputeManagementService.create(configuration);
return client.withRequestFilterFirst(new AuthTokenRequestFilter(subscriptionId));
```

Where `AuthTokenRequestFilter` looks like this:

```java
public class AuthTokenRequestFilter implements ServiceRequestFilter {
    private String subscriptionId;

    public AuthTokenRequestFilter(String subscriptionId) {
        this.subscriptionId = subscriptionId;
    }

    @Override
    public void filter(ServiceRequestContext request) {
        // acquire an Azure A/D access token somehow
        AuthenticationResult token = getTokenSomehow();

        // set access token
        request.setHeader(AzureRestAPIHelper.AUTHORIZATION_HEADER, "Bearer " + token.getAccessToken());
    }
}
```

All this works but as you can tell this is a bit hacky and relies on internal implementation details of the SDK. Direct support for A/D access tokens would be nice!

**Comment by amarzavery** [comment]
@avranju -  We will fix this in a future release.

**Comment by dadoonet** [comment]
@avranju Any chance you could share the full code? It sounds like what I'm looking for. Best!

**Comment by avranju** [comment]
@dadoonet In order for this to work today we first need issue #458 to be addressed. I have a fix addressed in my fork in this commit: https://github.com/avranju/azure-sdk-for-java/commit/0fa83ae864b55151453dd3fb99352493bb17a9e1. So you'll need to pull in that first and build the Azure SDK jars. This fixes an issue with the way the SDK handles request and response filters when it makes REST calls to Azure.

After that we can do what's described above. If you'd like to see a working implementation you can take a look at the source for the [IntelliJ/Android Studio plugin](https://github.com/MSOpenTech/msopentech-tools-for-intellij) we're working on. Specifically, the relevant bits are available [here](https://github.com/MSOpenTech/msopentech-tools-for-intellij/tree/dev/src/android/com/microsoftopentechnologies/intellij/helpers/azure/sdk).

You'll want to take a look at the following in roughly the order given below:

1. [`AzureSDKHelper.getConfigurationFromAuthToken`](https://github.com/MSOpenTech/msopentech-tools-for-intellij/blob/dev/src/android/com/microsoftopentechnologies/intellij/helpers/azure/sdk/AzureSDKHelper.java#L152)
2. [`AzureSDKHelper.getComputeManagementClient`](https://github.com/MSOpenTech/msopentech-tools-for-intellij/blob/dev/src/android/com/microsoftopentechnologies/intellij/helpers/azure/sdk/AzureSDKHelper.java#L60)
3. [`AuthTokenRequestFilter`](https://github.com/MSOpenTech/msopentech-tools-for-intellij/blob/dev/src/android/com/microsoftopentechnologies/intellij/helpers/azure/sdk/AuthTokenRequestFilter.java)
4. [`EmptyCloudCredentials`](https://github.com/MSOpenTech/msopentech-tools-for-intellij/blob/dev/src/android/com/microsoftopentechnologies/intellij/helpers/azure/sdk/EmptyCloudCredentials.java)

As @amarzavery mentions, there is a plan to address this directly in the SDK. If you need this today however, the above steps should fairly well.

**Comment by hovsepm** [comment]
This is done in PR https://github.com/Azure/azure-sdk-for-java-pr/pull/993 . We have a test which shows the usage - https://github.com/Azure/azure-sdk-for-java-pr/blob/dev/management-resources/src/test/java/com/microsoft/azure/management/resources/ResourceGroupOperationsTest.java 

Will be shipped in the next release.

**Comment by avranju** [comment]
Thanks @hovsepm. CC @martinsawicki, @beatriceoltean

**Comment by dadoonet** [comment]
@hovsepm I think the link to PR 993 is incorrect or correspond to a private repo.
Any chance you could link here to the public informations? Can't find this test class in the public repo.
