### ISSUE TITLE
Upload OpenSSH compatible Public Key to a Virtual Machine Deployment

### ISSUE THREAD

**Issue by danielestevez** [Azure/azure-sdk-for-java#461]
Right now to enable SSH access to a Virtual Machine, you need to upload a x509 certificate through ServiceCertificateCreateParameters but only .CER and .PFX are supported.

However the new Azure Portal allows you to upload only the SSH public key and Azure will do a conversion and upload the certificate to the Cloud Service containing this virtual machine.

Will the API or SDK will support uploading these SSH Keys directly? What is the new portal doing in-the-shadows to convert SSH key to certificate and upload it? In which format?

**Comment by martinsawicki** [comment]
pls try the latest version of the Azure SDK to create VMs programmatically.
