### ISSUE TITLE
Hostname verification fails behind a corporate proxy when connecting to Azure Service Bus with AMQP Web Sockets

### ISSUE THREAD

**Issue by ChristianSchenk711** [Azure/azure-sdk-for-java#4610]
## Actual Behavior

Note: I actually reported that before in (https://github.com/Azure/azure-service-bus-java/issues/377) and was redirected here for issues with version 2.0.0. The response claims it's not a bug, but I feel the statement was "It's not a bug in 1.2.x because we don't do AMQP.".

- I'm using com.microsoft.azure:azure-servicebus:2.0.0 behind a company proxy with TransportType set to AMQP_WEB_SOCKETS
- I'm getting a hostname verification exception: the exception is just a "GeneralSSLProblem" but when I debug into it I can see that the client expects the server to have the name of the proxy, which leads to a hostname verification problem.
- I can use the switch `-Dcom.microsoft.azure.servicebus.ssl.verifymode=verifyCertificateOnly` to make it work.

## Analysis 

I tracked that down to the class `com.microsoft.azure.servicebus.amqp.ConnectionHandler` which initializes the SslPeerDetails like that
```
SslPeerDetails peerDetails = Proton.sslPeerDetails(this.getOutboundSocketHostName(), this.getOutboundSocketPort());
```

Since the OutboundSocketHostName is the name of my proxy, that seems to be the root cause of my troubles. I changed the value in the debugger to the proper service bus address, and that worked.

I also noticed that in version 1.2.x (master1 branch of the old repository), the code is different: here it uses `this.messagingFactory.getHostName()` which seems the proper solution for me.

## Reproduction

I assume you would be able to reproduce that, when setting up your own local proxy and trying to connect to Azure Service Bus using AMQP_WEB_SOCKETS.

## Versions  
- OS platform and version:  2.0.0 on Windows (Oracle Java SE 1.8)

**Comment by loarabia** [comment]
Hi @ChristianSchenk711 , thanks for reporting this. CCing @ramya-rao-a to help route this further.

**Comment by joshfree** [comment]
tagging @yvgopal @nemakam to follow up on the customer-reported issue based on the CODEOWNERS file.  @yvgopal it looks like you already commented on https://github.com/Azure/azure-service-bus-java/issues/377

**Comment by yvgopal** [comment]
I have already commented about this issue on the thread [https://github.com/Azure/azure-service-bus-java/issues/377](https://github.com/Azure/azure-service-bus-java/issues/377). It is not a bug. You got it working with the appropriate flag, to be used specifically in cases like yours.
Verifying only the certificate, disregarding the name of the host presenting the certificate, is vulnerable to man in the middle attack.

**Comment by ChristianSchenk711** [comment]
So if I use a company proxy, I have to use the flag `verifyCertificateOnly` and then I'm vulnerable to man-in-the-middle attacks. So if this doesn't work, what is the way to securely connect to the Service Bus if I am behind a company proxy?

**Comment by yvgopal** [comment]
Honestly I don't have an answer. I don't know how it is done. But I think your company proxy should accept the certificate from service bus and present its own certificate to the client. I am no authority on this. If you have a suggestion, I will happily consider it.
