### ISSUE TITLE
Monitoring REST Client implementation (Feature Request)

### ISSUE THREAD

**Issue by danielestevez** [Azure/azure-sdk-for-java#463]
Reading this post https://convective.wordpress.com/2014/06/22/using-azure-monitoring-service-with-azure-virtual-machines/ we discovered there is a Monitoring REST API for Azure but it's not yet documented.

Is this planned to be done for the Java SDK? I checked it's available for .NET (https://github.com/Azure/azure-sdk-for-net) so a translation would be possible.

Is this documented anywhere so we could access to it and maybe contribute this feature to the Java SDK?

**Comment by matt-gibbs** [comment]
This is planned. Coming soon.

**Comment by danielestevez** [comment]
Thanks @matt-gibbs 
Any estimation when should we expect this feature? Next 0.8.0?
