### ISSUE TITLE
[compute] support compute management auth without certificate or authentication

### ISSUE THREAD

**Issue by dadoonet** [Azure/azure-sdk-for-java#464]
Heya,

I wonder if it's possible to access Management API without any certificate or authentication when calling Management API from a VM running inside Azure platform?

Thanks!

**Comment by dadoonet** [comment]
See also #456

**Comment by matt-gibbs** [comment]
Token support is planned. But VMs inside Azure will still need to authenticate for the particular subscription being managed.

**Comment by dadoonet** [comment]
Thanks @matt-gibbs. Any idea when it should be available on Azure and then in Azure Java SDK?
