### ISSUE TITLE
VirtualMachineRoleSize does not contain all available flavors

### ISSUE THREAD

**Issue by domdom82** [Azure/azure-sdk-for-java#467]
com.microsoft.windowsazure.management.compute.models.VirtualMachineRoleSize 

This class is used when deploying a new VM to Azure.
However it does only provide a small subset of the VM flavors actually available in the Azure portal.

Is this by design? Are the other flavors going to be added?

**Comment by markcowl** [comment]
@domdom82 thanks for the feedback, passing on to the appropriate service team

**Comment by vglafirov** [comment]
Any update on this issue? We are looking forward to use DS* nodes, but we kind of stuck on this issue now.

**Comment by devigned** [comment]
This should be available in the next update to the sdk. I can't comment on the exact date, but it's nearing release.

**Comment by bueti** [comment]
Hi @devigned, any update on the release date?

**Comment by devigned** [comment]
Yes. We are preparing the release. We still have some house keeping going on in the dev branch, but the preview bits are available there. We should get a push out to mvn later this week.

**Comment by bueti** [comment]
I see that there is a new release out (0.8.0) but ``VirtualMachineRoleSize.java`` still doesn't contain any D, or DS-Series VM types.
When can we expect this functionality?

**Comment by devigned** [comment]
That is a bug. There should be support for D and DS series vms. 

Thank you for reporting the issue.

**Comment by devigned** [comment]
We'll get this corrected this week.

**Comment by ljhljh235** [comment]
@huangpf Hi Pengfei, in https://github.com/Azure/azure-sdk-for-java/blob/master/resource-management/azure-mgmt-compute/src/main/java/com/microsoft/azure/management/compute/models/VirtualMachineSizeTypes.java (this is generated from the latest specs), I see Gs but not Ds. Do you know if we have any plans to include them?

**Comment by huangpf** [comment]
@ljhljh235 Hi Jianghao, this is the enum helper class which is probably not up to date, but it should not be blocking the users from specifying any strings. And yes, I think we would need to add missing supported size strings here.

**Comment by ljhljh235** [comment]
@huangpf I agree this shouldn't be a blocking issue. Thanks!

**Comment by martinsawicki** [comment]
obsolete - pls refer to the latest version of the Azure Management LIbraries for Java.
