### ISSUE TITLE
VirtualMachineGetResponse and Role do not return VM status

### ISSUE THREAD

**Issue by domdom82** [Azure/azure-sdk-for-java#468]
In the portal there seems to be a VM status that is independent from the deployment status.
Deployment could be "running" while VM is still "starting".
In the SDK I did not find any way to determine the status of a VM retrieved via 
```
ComputeManagementClient.getVirtualMachinesOperations().get(serviceName, deploymentName, virtualMachineName)
```
nor via
```
DeploymentGetResponse.getRoles() searching for a PersistentVM role
```
The only status I could find was the Deployment.getStatus() which returns only the deployment's status, not the VM status.

**Comment by danielestevez** [comment]
You'd need to obtain DeploymentGetResponse.getRoleInstances() and search the list for your VM and and -> RoleInstance.getPowerState() 

https://github.com/Azure/azure-sdk-for-java/blob/master/management-compute/src/main/java/com/microsoft/windowsazure/management/compute/models/RoleInstancePowerState.java

**Comment by domdom82** [comment]
Thanks.
How is RoleInstance.getPowerState() related to RoleInstance.getInstanceStatus() ?

Javadoc is pretty slim there ;-)

**Comment by danielestevez** [comment]
You might check InstanceStatus and PowerState meaning here:

https://msdn.microsoft.com/en-us/library/azure/ee460804.aspx

**Comment by domdom82** [comment]
Thanks a lot! Closing this one...
