### ISSUE TITLE
VirtualMachineRoleSize, role size  A8 is actually A7

### ISSUE THREAD

**Issue by dimitrovvlado** [Azure/azure-sdk-for-java#469]
com.microsoft.windowsazure.management.compute.models.VirtualMachineRoleSize: line 46

> public static final String A8 = "A7";

should be A8 = "A8". Not sure if there's a difference, but it looks like a typo.

**Comment by devigned** [comment]
Currently, it's "A8"

see: https://github.com/Azure/azure-sdk-for-java/blob/master/management-compute/src/main/java/com/microsoft/windowsazure/management/compute/models/VirtualMachineRoleSize.java#L46
