### ISSUE TITLE
Trying to upload a blob but recieve error

### ISSUE THREAD

**Issue by JeremyT991** [Azure/azure-sdk-for-java#470]
I have been trying to upload an image from an android application to widows azure and I have configured a storage for blobs. However when I try to run the code it gives me the following error:  W/System.err﹕ com.microsoft.azure.storage.StorageException: Server failed to authenticate the request. Make sure the value of Authorization header is formed correctly including the signature.

I followed the posted tutorials online and am able to successfully connect to the SQL database and store information. I also am aware that for the blob storage i have a different access key, in fact it gives me the choice of two keys one primary and one secondary.

my code is as follows: (which is from the tutorial) but the error is created on the createifnotexist line.

 // Retrieve storage account from connection-string.
                CloudStorageAccount storageAccount = CloudStorageAccount.parse(storageConnectionString);

                // Create the blob client.
                CloudBlobClient blobClient = storageAccount.createCloudBlobClient();

                // Get a reference to a container.
                // The container name must be lower case
                CloudBlobContainer container = blobClient.getContainerReference("mycontainer");

                // Create the container if it does not exist.
                container.createIfNotExists();
My connection string is:

public static final String storageConnectionString =
            "DefaultEndpointsProtocol=http;" +
                    "AccountName=pocketappraiser;" +
                    "AccountKey=nIHpihEU3C8NnziSCMzaUCm7hp5iXrzk5NIgDOvwk6dDUTjrR4coHf5XHxifG9d/N4gxEsroiW1ydoHaYp/Ijg==";

**Comment by emgerner-msft** [comment]
It looks like you're using the [Java](https://github.com/Azure/azure-storage-java) Storage library rather than the [Android](https://github.com/Azure/azure-storage-android) Storage library. If you take a look at the GitHub landing page for the Android Storage library there should be directions for using it in your project as well as samples.
