### ISSUE TITLE
Add Code Style Settings to Contributing.md File

### ISSUE THREAD

**Issue by alzimmermsft** [Azure/azure-sdk-for-java#4715]
We are developing our SDKs in an open source environment and are actively encouraging the community to provide contributions to the code base. Our PRs are gated with code linting rules, we should help make contributing to the code base easier by providing our community a standard code style configuration file.

**Comment by hemanttanwar** [comment]
We will define Code style which can be imported in Intellij.

**Comment by Foldfish** [comment]
Hi, is help still wanted on this issue?

**Comment by alzimmermsft** [comment]
Fixed by #38799
