### ISSUE TITLE
mvn compile doesn't work on master

### ISSUE THREAD

**Issue by voytoo** [Azure/azure-sdk-for-java#472]
mvn compile doesn't work on master

a lot of errors like:

[INFO] -------------------------------------------------------------
[ERROR] COMPILATION ERROR : 
[INFO] -------------------------------------------------------------
[ERROR] /work/azure/azure-sdk-for-java/core/src/main/java/com/microsoft/windowsazure/core/pipeline/apache/HttpRequestInterceptorAdapter.java:[21,23] cannot find symbol
  symbol:   class HttpRequest
  location: package org.apache.http
[ERROR] /work/azure/azure-sdk-for-java/core/src/main/java/com/microsoft/windowsazure/core/pipeline/apache/HttpRequestInterceptorAdapter.java:[22,23] cannot find symbol

mvn --version
Apache Maven 3.0.5 (r01de14724cdef164cd33c7c8c2fe155faf9602da; 2013-02-19 14:51:28+0100)
Maven home: /Volumes/Macintosh HD/Users/mvojtek/apps/apache-maven-3.0.5
Java version: 1.8.0_20, vendor: Oracle Corporation
Java home: /Library/Java/JavaVirtualMachines/jdk1.8.0_20.jdk/Contents/Home/jre
Default locale: en_US, platform encoding: UTF-8
OS name: "mac os x", version: "10.10.3", arch: "x86_64", family: "mac"

I was able to fix this issue by providing explicit version to httpclient dependency for several modules (like management)

<dependency>
      <groupId>org.apache.httpcomponents</groupId>
      <artifactId>httpclient</artifactId>
      <version>4.3.1</version>
    </dependency>

There is version specified in parent pom, but it looks like this version is not in use and submodules try to get latest httpclient (4.4.x), which has incompatible changes.

**Comment by ogail** [comment]
@voytoo we can't repro this. Here are machine info
```bash
SdkPro:azure-sdk-for-java-master mattgibbs$ mvn -v
Apache Maven 3.3.1 (cab6659f9874fa96462afef40fcf6bc033d58c1c; 2015-03-13T13:10:27-07:00)
Maven home: /Users/mattgibbs/Downloads/apache-maven-3.3.1
Java version: 1.8.0_45, vendor: Oracle Corporation
Java home: /Library/Java/JavaVirtualMachines/jdk1.8.0_45.jdk/Contents/Home/jre
Default locale: en_US, platform encoding: UTF-8
OS name: "mac os x", version: "10.9.2", arch: "x86_64", family: "mac"
```

Probably update Maven?

**Comment by voytoo** [comment]
This is probably not problem of maven. Works for me on linux with following maven:

Apache Maven 3.0.5
Maven home: /usr/share/maven
Java version: 1.7.0_76, vendor: Oracle Corporation
Java home: /usr/lib/jvm/java-7-oracle/jre
Default locale: en_US, platform encoding: UTF-8
OS name: "linux", version: "3.13.0-32-generic", arch: "amd64", family: "unix"

**Comment by devigned** [comment]
Apache Maven 3.3.1 (cab6659f9874fa96462afef40fcf6bc033d58c1c; 2015-03-13T13:10:27-07:00)
Maven home: /usr/local/Cellar/maven/3.3.1/libexec
Java version: 1.8.0_45, vendor: Oracle Corporation
Java home: /Library/Java/JavaVirtualMachines/jdk1.8.0_45.jdk/Contents/Home/jre
Default locale: en_US, platform encoding: UTF-8
OS name: "mac os x", version: "10.10.3", arch: "x86_64", family: "mac"

builds for me.

**Comment by voytoo** [comment]
It is probably environment specific on my mac. Don't work on my mac either with 3.3.1

Apache Maven 3.3.1 (cab6659f9874fa96462afef40fcf6bc033d58c1c; 2015-03-13T21:10:27+01:00)
Maven home: /fake/azure/apache-maven-3.3.1
Java version: 1.7.0_67, vendor: Oracle Corporation
Java home: /Library/Java/JavaVirtualMachines/jdk1.7.0_67.jdk/Contents/Home/jre
Default locale: en_US, platform encoding: UTF-8
OS name: "mac os x", version: "10.10.3", arch: "x86_64", family: "mac"
