### ISSUE TITLE
Service bus API doesn't provide a method to fetch multiple messages from the queue .

### ISSUE THREAD

**Issue by arbarik** [Azure/azure-sdk-for-java#473]
We are using ServiceBus to integrate few of our cloud services. But Service bus API doesn't provide to fetch more than one message at once. Each call returns me one message, Which is very inefficient.

**Comment by collinsauve** [comment]
+1

**Comment by martinsawicki** [comment]
the service bus client library is not in this repo anymore, so if this is still an issue, it should go there:
https://github.com/azure/azure-service-bus-java
