### ISSUE TITLE
Incomplete BrokerProperties DTO

### ISSUE THREAD

**Issue by collinsauve** [Azure/azure-sdk-for-java#475]
The BrokerProperties DTO is missing several properties.  I specifically need the `EnqueuedTimeUtc`; I've created this [pull request](https://github.com/Azure/azure-sdk-for-java/pull/474) to add it.

Additionally the [link to the spec here](https://github.com/collinsauve/azure-sdk-for-java/blob/155cb3a0a5f2c48ad37c37cd8c59d932089d8b8c/serviceBus/src/main/java/com/microsoft/windowsazure/services/servicebus/implementation/BrokerProperties.java#L26) is dead.

**Comment by martinsawicki** [comment]
the service bus client library is not in this repo anymore, so if this is still an issue, it should go there:
https://github.com/azure/azure-service-bus-java
