### ISSUE TITLE
Poosible memory leak in receive subscription message

### ISSUE THREAD

**Issue by frank-montyne** [Azure/azure-sdk-for-java#477]
Hi,

I'm using the following code to read a message from the service bus:
...
private ReceiveMessageOptions messageOptions;
...
this.messageOptions = ReceiveMessageOptions.DEFAULT;
this.messageOptions.setReceiveMode(ReceiveMode.PEEK_LOCK);
...
public ItemMessage getNextMessage(String subscriptionName, String topicName) throws Exception {
        ReceiveSubscriptionMessageResult result = azureServiceBusClient.getService().receiveSubscriptionMessage(topicName, 
subscriptionName, messageOptions);
        BrokeredMessage message = result.getValue();
        if (message == null) return null;
        // Message received, continue.
        StringBuilder jsonMessageBuilder = new StringBuilder();
        byte[] buffer = new byte[MAX_BUFFER_SIZE];
        int bytesRead = message.getBody().read(buffer);
        while (bytesRead != -1) {
            jsonMessageBuilder.append(new String(buffer, 0, bytesRead, Encoding.UTF8));
            bytesRead = message.getBody().read(buffer);
        }
        azureServiceBusClient.getService().deleteMessage(message);
        return ItemMessage.fromJson(jsonMessageBuilder.toString());
    }

After a few million messages I get an out of memory error in my java application. I have similar code to makes use of an MQTT broker and keeps on working without any out of memory errors.

Is there something wrong with my code? The getNextMessage() function has never thrown another exception, that I can see in the logs. I know the code should be a bit more robust by putting a try/catch block around the StringBuilder part of the code and releasing the message in case of an exception but that is not the issue since I never got an exception in that part.

Best regards,
Frank

**Comment by martinsawicki** [comment]
the service bus client library is not in this repo anymore, so if this is still an issue, it should go there:
https://github.com/azure/azure-service-bus-java
