### ISSUE TITLE
Are azure-media-0.7.0.jar, azure-serviceruntime-0.7.0.jar and azure-tracing-util-0.7.0.jar available for download from maven repository ?

### ISSUE THREAD

**Issue by pednekarprajakta** [Azure/azure-sdk-for-java#478]
Are azure-media-0.7.0.jar, azure-serviceruntime-0.7.0.jar and azure-tracing-util-0.7.0.jar available for download from maven repository ?
I found only 0.6.0 version JARs are available at maven for above three JARs.
Could you guide me on this ?

**Comment by matt-gibbs** [comment]
No, 0.6.0 is the latest version of media, serviceruntime and tracing.
