### ISSUE TITLE
Unable the share the same instance of HttpClient accros multiple instances of ComputeManagementClient

### ISSUE THREAD

**Issue by kcheick** [Azure/azure-sdk-for-java#480]
Because of the this [bug](https://github.com/Azure/azure-sdk-for-java/issues/479) i tried to reuse the http client created by default and share it accross multiple instances of ComputeManagementClient and it also failed. this time because the properties are being modified. Is this expected ?

```C#
var cmc1 = new ComputeManagementClient( credentials);
var r = cmc1.Deployments.GetByNameAsync(serviceName,serviceName).Result;
cmc2 = new ComputeManagementClient( credentials,cmc1.HttpClient);
```

the exception being thrown :
```
This instance has already started one or more requests. Properties can only be modified before sending the first request.
```

**Comment by matt-gibbs** [comment]
Correct. The constructor configures the HttpClient pipeline.  Taking the HttpClient from one instance and passing it to the constructor of another instance is not supported.
By the way, this is C# code. Issues should go to https://github.com/azure/azure-sdk-for-net
