### ISSUE TITLE
Research Return Type for Non-Paged Lists

### ISSUE THREAD

**Issue by alzimmermsft** [Azure/azure-sdk-for-java#4814]
Research the correct return type for non-paged list return types.

The return type don't cleanly fit into PagedFlux as that return type is meant for paged responses, it also doesn't cleanly fit into Flux as the guideline calls out as that misses the requirement of having access to the HTTP response data (headers, status code, etc). The last option is using Mono but there is a choice of either using `Mono<Response<List>>` or `Mono<Response<Flux>>`.

**Comment by JonathanGiles** [comment]
This is resolved now, I believe.
