### ISSUE TITLE
Unable to get Resource Extension References from Java API

### ISSUE THREAD

**Issue by pker** [Azure/azure-sdk-for-java#482]
The Azure Java management API for Resource Extension References is throwing an exception when used for the Chef extension. PFA exception details.

![exception](https://cloud.githubusercontent.com/assets/11184734/8256557/6ef532d6-166d-11e5-88f7-2adb80253ac4.jpg)

**Comment by devigned** [comment]
@kundanap just tagging for follow up

**Comment by martinsawicki** [comment]
obsolete - pls use the latest version of the Azure Management Libraries for Java
