### ISSUE TITLE
Missing ContentKeyType.EnvelopeEncryption

### ISSUE THREAD

**Issue by jkeys089** [Azure/azure-sdk-for-java#483]
There is no `com.microsoft.windowsazure.services.media.models.ContentKeyType.EnvelopeEncryption` counterpart for [ContentKeyType.EnvelopeEncryption](https://msdn.microsoft.com/en-us/library/microsoft.windowsazure.mediaservices.client.contentkeytype(v=azure.10).aspx).

The `EnvelopeEncryption` type is used when creating [HLS content keys](https://msdn.microsoft.com/en-us/library/azure/dn783457.aspx#create_content_key).

**Comment by jkeys089** [comment]
It may also be worth mentioning the `EnvelopeEncryption` type is listed in the [REST API docs](https://msdn.microsoft.com/en-us/library/azure/hh974309.aspx#create_a_contentkey) as well.

**Comment by markcowl** [comment]
@jkeys089 Thank you for the report, routing to the approp[riate team

**Comment by rnrneverdies** [comment]
This was fixed in this commit: https://github.com/Azure/azure-sdk-for-java/commit/17224e12cac8bde10f82ea39a3019c8b27ad7a40

**Comment by jianghaolu** [comment]
Closing as we haven't heard back from you. We assume this is no longer an issue for you. Please reopen if necessary.

Thanks for reporting issues to Azure SDK for Java.
Jianghao
