### ISSUE TITLE
Upgrade to Jersey2?

### ISSUE THREAD

**Issue by lanxx019** [Azure/azure-sdk-for-java#484]
Any plan on upgrade the Jersey 1 client dependency to Jersey2?

**Comment by markcowl** [comment]
@lanxx019 We are in process of refactoring the runtime, and if we continue to use jersey, we will use jersey2.  Closing this for now.

**Comment by phavelar** [comment]
so, it's December 2018 , how is the process of refactoring the runtime going ?
Need Jersey 2.x as this implementation its not compatible with latest Dropwizard or anything Jersey 2.x 
re-open?
