### ISSUE TITLE
Remove swagger from repo

### ISSUE THREAD

**Issue by rickle-msft** [Azure/azure-sdk-for-java#4841]
The swagger for this project should never be checked in along side the code.

**Comment by joshfree** [comment]
@jianghaolu can you PTAL for the next milestone?

**Comment by JonathanGiles** [comment]
I am told that these files will be moved soon to azure-rest-api-specs.

**Comment by JonathanGiles** [comment]
Yes - I understand. I was just wanting to get documented in here that they are moving 'soon'. We should maybe investigate having a GitHub check that prevents swagger files being checked in?
