### ISSUE TITLE
ServiceBus Track2 - Create QueueClientBuilder class 

### ISSUE THREAD

**Issue by hemanttanwar** [Azure/azure-sdk-for-java#4844]
Create QueueClientBuilder class, which allows construction of QueueClient. 

Rationale: 
1. Since we are following Java Guidelines specified in `https://azure.github.io/azure-sdk/java_design.html` for track 
2.Most of Java SDK Client uses ClientBuilder to create a Client.

References: 
Track 1 : com.microsoft.azure.servicebus.primitives.ConnectionStringBuilder

**Comment by conniey** [comment]
Fixed as part of #4506
