### ISSUE TITLE
Add Create and Delete Blob to ContainerClient

### ISSUE THREAD

**Issue by alzimmermsft** [Azure/azure-sdk-for-java#4845]
Unlike BlobServiceClient which has the ability to create and delete ContainerClients, next step in the service hierarchy, ContainerClient doesn't have the ability to create and delete blobs. For create the ContainerClient will create a block blob, documentation will indicate this to the consumer of the SDK.

**Comment by kurtzeborn** [comment]
This represents further deviation from what other languages are supporting (.Net in particular).  We're trying to align API surface area right now, so this isn't the right direction to go.
