### ISSUE TITLE
ServiceBus Track2 - Create QueueClient class 

### ISSUE THREAD

**Issue by hemanttanwar** [Azure/azure-sdk-for-java#4847]
Create QueueClient class, which has API to create MessageSender  and MessageReceiver .

API to consider
1. createSender : returns MessageSender instance which allows  to send messages as specified in Issue #4851
2. createReceiver : returns MessageReceiver instance which allows  to receicve messages
3. peek : peeking into message in read only mode. : For reference how it is implemented in JavaScript here https://docs.microsoft.com/en-us/javascript/api/%40azure/service-bus/queueclient?view=azure-node-latest#peekbysequencenumber-long--undefined---number-
4. getDeadLetterQueuePath : For reference how it is implemented in JavaScript here https://docs.microsoft.com/en-us/javascript/api/%40azure/service-bus/queueclient?view=azure-node-latest#getdeadletterqueuepath-string-

References:
Track 1 : com.microsoft.azure.servicebus.QueueClient

**Comment by conniey** [comment]
Fixed as part of #4506
