### ISSUE TITLE
ServiceBus Track2 - Create MessageSender class

### ISSUE THREAD

**Issue by hemanttanwar** [Azure/azure-sdk-for-java#4851]
Create MessageSender  class, which allows to send single message and batch messages.

API to consider
1. send : Sync API
2. sendBatch : Sync API
3. scheduleMessage : Sync API
4. cancelScheduledMessage : Sync API

References:
Track 1 : com.microsoft.azure.servicebus.MessageSender

**Comment by conniey** [comment]
Fixed as part of #4506
