### ISSUE TITLE
ServiceBus Track2 - Create MessageReceiver class

### ISSUE THREAD

**Issue by hemanttanwar** [Azure/azure-sdk-for-java#4856]
Create MessageReceiver class, which allows to send single message and batch messages.
API to consider
1. receiveDeferredMessage (sequenceNumber ) :  . This is Sync API.
2. receiveDeferredMessage (sequenceNumbers[] ) : This is Sync API.
3. registerMessageHandler
4. renewMessageLock  : This is Sync API. 
5. getMessageIterator() : Look at this is it make sense for Java . Reference  https://docs.microsoft.com/en-us/javascript/api/%40azure/service-bus/receiver?view=azure-node-latest#getmessageiterator--

Note: sequenceNumber  is `message identifier`

References:
Track 1 : com.microsoft.azure.servicebus.MessageReceiver

**Comment by conniey** [comment]
Fixed as part of #4506
