### ISSUE TITLE
Async methods consume executor threads while idle

### ISSUE THREAD

**Issue by clarkbreyman** [Azure/azure-sdk-for-java#486]
A quick review of the async methods seems to indicate that they just wrap the synchronous method in an executor and return the future. This results in the method requiring an executor thread for every outstanding request even if the request is waiting on I/O. This is similar to https://java.net/jira/browse/JERSEY-2058, Jersey seems to have addressed this problem via https://github.com/AsyncHttpClient/async-http-client.

**Comment by devigned** [comment]
We are rewriting the core of the java sdk and should have a much better solution to this in the next major release.

**Comment by jianghaolu** [comment]
Hi @clarkbreyman 
We just released 1.0.0-beta2 this past week and please feel free to give it a try. We have moved the async model onto the queue-based callbacks provided by Square OkHttp.

We are still looking into possibilities of moving onto Observable-based async.

**Comment by clarkbreyman-yammer** [comment]
Thanks for the ping - I'll take a look.

**Comment by jianghaolu** [comment]
In latest master we already implemented Observable-based async with RxJava. Please feel free to take a look. 
Closing as this specific issue is not relevant anymore.
