### ISSUE TITLE
Reasonable Default for MaximumExecutionTimeInMs

### ISSUE THREAD

**Issue by skearns64** [Azure/azure-sdk-for-java#487]
By default, it appears that there is no default set for MaximumExecutionTimeInMs.

In practice, some calls appear to never get a response from Azure, which results in the client hanging forever with default settings. 

A default setting here, even if it were rather high, would make this library safer for clients to use. Most users won't know it isn't safe to use the library without setting this value, because you only see it as an issue when Azure drops a request, which doesn't appear to be often, but does happen.

**Comment by ppf2** [comment]
+1

**Comment by markcowl** [comment]
@skearns64 Thank you for the report.  Assigning appropriately for resolution.

**Comment by ppf2** [comment]
@markcowl Can you provide an update on this? :)

**Comment by jianghaolu** [comment]
We are rewriting the core of the java sdk and should have a much better solution to this in the next major release.

**Comment by skearns64** [comment]
Thanks for the update, looking forward to the new version!

**Comment by jianghaolu** [comment]
Closing as resolved. JFYI, the development work of new SDK generation tool can be tracked in https://github.com/azure/autorest/tree/dev
