### ISSUE TITLE
Refactor AesCbcHmacSha2 class

### ISSUE THREAD

**Issue by g2vinay** [Azure/azure-sdk-for-java#4870]
Remove duplication of getAlgoParameters method and ensure it doesn't cause spotbugs problem.

**Comment by mclay** [comment]
please assign me this Task i will fix it

**Comment by joshfree** [comment]
Thanks @mclay - I've assigned the issue to you.  Please note the date we're aiming to commit this by in the [[2019] December](https://github.com/Azure/azure-sdk-for-java/milestone/62) milestone is actually November 22.

**Comment by joshfree** [comment]
Closing issue now that #6353 has been merged
