### ISSUE TITLE
[BUG] Missing Links in Cosmos

### ISSUE THREAD

**Issue by Intern426** [Azure/azure-sdk-for-java#4871]
**Describe the bug**
Some links in the README for Cosmos can't be found.

***Exception***
Example: in Cosmos under the README (https://github.com/Azure/azure-sdk-for-java/tree/master/sdk/cosmos), the link to the HelloWorldExample.java doesn't work
https://github.com/Azure/azure-sdk-for-java/blob/master/sdk/cosmos/examples/src/main/java/com/azure/data/cosmos/examples/HelloWorldExample.java

***Snippet***
Other link
Cosmos README:
-  Examples - https://github.com/Azure/azure-sdk-for-java/blob/master/sdk/cosmos/examples/src/test/java/com/microsoft/azure/cosmosdb/rx/examples
- Can't seem to find the API documentation: https://github.com/Azure/azure-sdk-for-java/tree/master/sdk/cosmos#api-documentation as well as the Usage Code Sample 
- Guide for Prod doesn't jump to Guide for Production

**Comment by shurd** [comment]
Hi @Intern426, thank you for raising this issue. It looks like code was restructured 17 days ago and some of the links were broken. @g2vinay can you update the README based on your restructuring?

The HelloWorldExample link has already been corrected. The [Examples](https://github.com/Azure/azure-sdk-for-java/blob/master/sdk/cosmos/microsoft-azure-cosmos-examples/src/test/java/com/azure/data/cosmos/rx/examples) have been moved.

The README was updated part of [this commit](https://github.com/Azure/azure-sdk-for-java/commit/07ded65656fcdb1bc78b51821f1007d72ce90b28#diff-f1b870d9ab15d3ff5b849672b4bc044f) and the new table of contents does not reflect the document.

**Comment by g2vinay** [comment]
Thank you for pointing this out.
I'll work with the Cosmos team and get the README links fixed.

**Comment by shurd** [comment]
@g2vinay It looks like the example link is still broken in the README. (https://github.com/Azure/azure-sdk-for-java/blame/master/sdk/cosmos/README.md#L79). It should redirect to: https://github.com/Azure/azure-sdk-for-java/tree/master/sdk/cosmos/microsoft-azure-cosmos-examples/src/test/java/com/azure/data/cosmos/rx/examples

**Comment by kushagraThapar** [comment]
@Intern426 - After the restructuring, this is the correct readme - https://github.com/Azure/azure-sdk-for-java/tree/master/sdk/cosmos/azure-cosmos
Please let us know if any of the links in this readme is not working.

**Comment by kushagraThapar** [comment]
@Intern426 - I am closing this issue, feel free to open if the issue still persists.
