### ISSUE TITLE
[BUG] uploadToBlobAsync hangs with log message "Automatic Reconnect Successful"

### ISSUE THREAD

**Issue by tianhai-liu** [Azure/azure-sdk-for-java#4887]
**Describe the bug**
When uploading a zip file (<=3 MB) using the `DeviceClient.uploadToBlobAsync` method, the uploading process hangs (at least no invoke of `IotHubEventCallback.execute` in 2 hours after starting the uploading process) and the Azure internal logger keeps printing following messages periodically:

> FINE: null: Check schedule at 1,564,727,590,274
> FINE: Dev01: checkForActivity entered
> FINE: Dev01: ping needed. keepAlive=230,000 lastOutboundActivity=1,564,727,360,306 lastInboundActivity=1,564,727,361,053
> FINE: Dev01: key=Ping message=PINGREQ
> FINE: Dev01: key=Ping token=org.eclipse.paho.client.mqttv3.MqttToken@6f8439c4
> FINE: Dev01: notifying queueLock holders
> FINE: Dev01: Schedule next ping at 230,000
> FINE: Dev01: new work or ping arrived
> FINE: Dev01: network send key=Ping msg=PINGREQ
> FINE: Dev01: sent bytes count=2
> FINE: null: Sent PINGREQ
> FINE: Dev01: key=Ping
> FINE: Dev01: > key=Ping
> FINE: Dev01: ping sent. pingOutstanding: 1
> FINE: Dev01: wait for new work or for space in the inflight window
> FINE: Dev01: received bytes count=1
> FINE: null: Automatic Reconnect Successful: PINGRESP msgId 0
> FINE: Dev01: received key=0 message=PINGRESP msgId 0
> FINE: Dev01: >key=Ping response=PINGRESP msgId 0 excep=null
> FINE: Dev01: >key=Ping response=PINGRESP msgId 0 excep=null
> FINE: Dev01: keyPing, msg=PINGRESP msgId 0, excep=null
> FINE: Dev01: new workAvailable. key=Ping
> FINE: Dev01: key=Ping
> FINE: Dev01: ping response received. pingOutstanding: 0
> FINE: Dev01: network read message
> FINE: Dev01: callback and notify for key=Ping
> FINE: Dev01: received key=0 token=org.eclipse.paho.client.mqttv3.MqttToken@6f8439c4 message=PINGRESP msgId 0
> FINE: Dev01: >key=Ping response=PINGRESP msgId 0 excep=null
> FINE: Dev01: notify spaceAvailable
> FINE: Dev01: wait for workAvailable
>
> FINE: null: Check schedule at 1,564,727,820,471
> FINE: Dev01: checkForActivity entered
> FINE: Dev01: ping needed. keepAlive=230,000 lastOutboundActivity=1,564,727,590,361 lastInboundActivity=1,564,727,591,115
> FINE: Dev01: key=Ping message=PINGREQ
> FINE: Dev01: key=Ping token=org.eclipse.paho.client.mqttv3.MqttToken@1ebdbab
> FINE: Dev01: notifying queueLock holders
> FINE: Dev01: Schedule next ping at 230,000
> FINE: Dev01: new work or ping arrived
> FINE: Dev01: network send key=Ping msg=PINGREQ
> FINE: Dev01: sent bytes count=2
> FINE: null: Sent PINGREQ
> FINE: Dev01: key=Ping
> FINE: Dev01: > key=Ping
> FINE: Dev01: ping sent. pingOutstanding: 1
> FINE: Dev01: wait for new work or for space in the inflight window
> FINE: Dev01: received bytes count=1
> FINE: null: Automatic Reconnect Successful: PINGRESP msgId 0
> FINE: Dev01: received key=0 message=PINGRESP msgId 0
> FINE: Dev01: >key=Ping response=PINGRESP msgId 0 excep=null
> FINE: Dev01: >key=Ping response=PINGRESP msgId 0 excep=null
> FINE: Dev01: keyPing, msg=PINGRESP msgId 0, excep=null
> FINE: Dev01: new workAvailable. key=Ping
> FINE: Dev01: key=Ping
> FINE: Dev01: ping response received. pingOutstanding: 0
> FINE: Dev01: network read message
> FINE: Dev01: callback and notify for key=Ping
> FINE: Dev01: received key=0 token=org.eclipse.paho.client.mqttv3.MqttToken@1ebdbab message=PINGRESP msgId 0
> FINE: Dev01: >key=Ping response=PINGRESP msgId 0 excep=null
> FINE: Dev01: notify spaceAvailable
> FINE: Dev01: wait for workAvailable

***Exception or Stack Trace***
No exception or stack trace

**To Reproduce**
Hard to reproduce, the file uploading works well in 2~4 days, and suddenly does not work. It happened several times, but I have no clue how to reproduce it with a simple problem.

***Code Snippet***
```
while (true) {
    if (FileUploadStatusCallback is not invoked) 
        wait;

    File file = fetchNextFileToUpload();
    if (client == null) client = new DeviceClient(connectString, MQTT);
    client.open();
    client.setOperationTimeout(300000);
    client.uploadToBlobAsync(..., new IotHubEventCallback(...), file);
}
```

**Expected behavior**
`BlobEventCallBack.execute` shall be invoked if timeouts.

**Setup (please complete the following information):**
 - OS: linux
 - Version of the Library used: 1.17.5

**Comment by tianhai-aicas** [comment]
Do you have any update? Is it my miss-using of Azure client or a possible bug? Thanks!

**Comment by jlian** [comment]
Hello, would you mind posting this over at https://github.com/Azure/azure-iot-sdk-java/issues instead?
