### ISSUE TITLE
[Cosmos] Sync/Async Client cleanup

### ISSUE THREAD

**Issue by christopheranderson** [Azure/azure-sdk-for-java#4907]
# Summary

Cosmos GA'd V3 with `CosmosClient` being non-blocking/Async methods. The Track 2 requirements dictate that this should be the blocking/Sync methods. We've agreed to a compromise where both clients are labels sync and async, and we'll deprecate the `CosmosClient` class and avoid using it in samples/etc.

- Async guidelines section: https://azure.github.io/azure-sdk/java_design.html#async-api
    - "✅ DO offer an async service client named <ServiceName>AsyncClient. More than one service client may be offered for a single service."
- Sync guidelines section: https://azure.github.io/azure-sdk/java_design.html#async-api
    - "✅ DO offer a sync service client named <ServiceName>Client. More than one service client may be offered for a single service."

## Work

- Sync (Being addressed in https://github.com/Azure/azure-sdk-for-java/pull/4757)
    - [x] Add Sync API using `CosmosSyncClient` and `<Resource>Sync` pattern
    - [x] Add `buildSyncClient` to builder
- Async
    - [x] Add `CosmosAsyncClient` as clone of `CosmosClient`
    - [x] Add `buildAsyncClient` to builder
- Cleanup
    - [ ] Deprecate `CosmosClient`
    - [ ] Deprecate `CosmosClientBuilder#build()`
    - [ ] Once we can take Azure.Core dependency, we need to add annotations

**Comment by mbhaskar** [comment]
V4 follows track2 guidelines, so these need not be done on V3
