### ISSUE TITLE
Add getName for the resource like blob/container/file

### ISSUE THREAD

**Issue by sima-zhu** [Azure/azure-sdk-for-java#4916]
Xstore team requests us to add a getName() API for resource name.
It will provide rich information for logging and debugging.

Better to have convenience feature of getting the parent as well.

**Comment by tg-msft** [comment]
What will `getName()` return?  The blob's name on a `BlobClient`?  Would we want a way to get access to the container name as well?  For .NET [we've got a work item](https://github.com/Azure/azure-sdk-for-net/issues/6885) to make our various UriBuilders public so customers can get access to any part of this info.  Does that satisfy the same need?

**Comment by rakshith91** [comment]
We don't really need this in python, although it's not a bad thing to have either.
`BlobClient.blob_name` will return the name Similarly for others too.

**Comment by kurtzeborn** [comment]
After discussing with xstore team, we think the best route is to expose `getname()` on blobs as well as `getContainerName()` (and probably `getName()` on containers).  This provides the ability to walk up and down the hierarchy.  

The reason the "ContainerName" pattern is more interesting than "ParentName" is to accommodate ADLS scenarios which will be exposed through the same APIs.

**Comment by annatisch** [comment]
As @rakshith91 mentions above - for Python we publicly expose all the path components on each of the clients as properties, for example:
```python
BlobServiceClient.primary_hostname
BlobServiceClient.secondary_hostname
ContainerClient.container_name
BlobClient.container_name
BlobClient.blob_name
BlobClient.snapshot
```

**Comment by jeremymeng** [comment]
JS has https://github.com/Azure/azure-sdk-for-js/issues/5007 tracking this.
