### ISSUE TITLE
Add standard annotations for Azure Storage libraries.

### ISSUE THREAD

**Issue by srnagar** [Azure/azure-sdk-for-java#4949]
New annotations were introduced in preview 2 version of `azure-core`. Update storage libraries to use these annotations.

**Comment by amishra-dev** [comment]
@srnagar can you please send us more details on what these annotation are? email them to me.

**Comment by rickle-msft** [comment]
This would be adding the annotations in BlobLeaseClient to the other clients

**Comment by srnagar** [comment]
Looks like the required annotations were added to Storage clients. Closing this issue.
