### ISSUE TITLE
Checkstyle rule for missing `package-info.java` in non-implementation packages.

### ISSUE THREAD

**Issue by srnagar** [Azure/azure-sdk-for-java#4953]
Enable built-in checkstyle rule to detect missing package-info.java class in non-`implementation` packages.

```
<!-- Checks that a package-info.java file exists for each package. -->
<!-- See http://checkstyle.sf.net/config_javadoc.html#JavadocPackage -->
<module name="JavadocPackage"/>
```

**Comment by vhvb1989** [comment]
not in implementation or Samples or Tests right? 
Or only non-implementation? @JonathanGiles

**Comment by JonathanGiles** [comment]
> not in implementation or Samples or Tests right?
> Or only non-implementation?

Correct, only public API

**Comment by vhvb1989** [comment]
Rule merged
