### ISSUE TITLE
Introduce pre-commit script to run all checkstyle, spotbugs and javadoc rules.

### ISSUE THREAD

**Issue by srnagar** [Azure/azure-sdk-for-java#4959]

**Comment by kurtzeborn** [comment]
@srnagar We already have all of these things in CI and PR validation.  Given that, it sounds like what you're suggesting here is a script of some sort that Java devs can run before issuing a PR.

**Comment by JonathanGiles** [comment]
Correct - this is for developers to run so that we can all simply have a `./validate.sh` call that devs can know to run before submitting a PR. At present there is too much mental overhead to know what to call and to retain confidence that all appropriate checks are being performed.
