### ISSUE TITLE
Explore using parallel maven build to speed up CI builds

### ISSUE THREAD

**Issue by srnagar** [Azure/azure-sdk-for-java#4975]
Explore maven option `-T` that will parallelize the build and reduce the CI pipeline build time. Finding the right argument to pass to `-T` might be the tricky part.

https://cwiki.apache.org/confluence/display/MAVEN/Parallel+builds+in+Maven+3

**Comment by JonathanGiles** [comment]
// cc @mitchdenny

**Comment by mitchdenny** [comment]
I think that ```-T 1C``` looks like the correct option since it will not over commit based on the number of cores on the VM (since that varies between environments).

**Comment by JonathanGiles** [comment]
It's possible 1C is correct, but I would like to see if 1.5C or 2C is even better. We will investigate and see. As Srikanta notes, the work is mostly I/O bound, so CPU cores will be sitting idle and we might benefit from multiple threads per core.

**Comment by JonathanGiles** [comment]
I tried this at https://github.com/Azure/azure-sdk-for-java/pull/4983, but there was no discernible difference. I may have made a mistake (please double-check @srnagar), but I think we should just close this issue.

**Comment by kurtzeborn** [comment]
Closing this issue based on Jonathan's comments above.
