### ISSUE TITLE
PagedIterable - should it take a continuation token for the *ByPage methods?

### ISSUE THREAD

**Issue by JonathanGiles** [Azure/azure-sdk-for-java#4989]
Like in PagedFlux, should we have a continuation token API for the two byPage methods?

**Comment by rickle-msft** [comment]
Is there a reason why we shouldn't?

**Comment by JonathanGiles** [comment]
No, it should be done - but I prefer to phrase my issues as questions so people don't take what I say as gospel :-)

**Comment by JonathanGiles** [comment]
This appears to have already been implemented in #4803.
