### ISSUE TITLE
Enhance the Handling of HttpPipelinePolicy in Builders

### ISSUE THREAD

**Issue by alzimmermsft** [Azure/azure-sdk-for-java#4999]
Currently, the builders allow for HttpPipelinePolicies to be set but once they are there isn't a way to make sure no duplicates were added or that the policies will be triggered in the correct order. Additionally, in our client builders if a consumer isn't using a custom HttpPipeline the builder will add in default policies and any customer passed policies will trigger after the RetryPolicy.

This causes our builders to be black boxes when it comes to the handling of policies and makes it much more difficult to help the customer do the right configuration rather than accidentally doing the wrong configuration.

Possible Solutions

Add a scoring system to our pipeline policies that determines which order they are applied in the pipeline. Use this scoring to also help deduplicate the policies added where the customer passed policy takes precedent.

In either Azure Core or on the individual builder add helper method that will return a list of policies that are automatically applied by the builder and when policies are passed by the customer we only use those. Additionally into this the builder could maintain two sets of policies to add, those before retry and those after retry.

**Comment by sima-zhu** [comment]
**AppConfiguration**
UserAgentPolicy
RequestIdPolicy
AddHeadersPolicy
AddDatePolicy
SomeAuthPolicy
RetryPolicy
CustomerizedPolicy

**Comment by sima-zhu** [comment]
**KeyVault Certificate**
UserAgentPolicy
RetryPolicy
KeyVaultCredentialPolicy
CustomerizedPolicy
HttpLoggingPolicy

**Comment by sima-zhu** [comment]
**KeyVault Keys**
UserAgentPolicy
RetryPolicy
KeyVaultCredentialPolicy
...CostomerizedPolicy
HttpLoggingPolicy

**Comment by sima-zhu** [comment]
**KeyVault Secrets**
UserAgentPolicy
RetryPolicy
KeyVaultCredentialPolicy
...CostomerizedPolicy
HttpLoggingPolicy

**Comment by sima-zhu** [comment]
**Storage Blob**
UserAgentPolicy
RequestIdPolicy
AddDatePolicy
credentialPolicy
RequestRetryPolicy
...CostomerizedPolicy
ResponseValidationPolicy
HttpLoggingPolicy
ScrubEtagPolicy

**Comment by sima-zhu** [comment]
Here is how AWS define the order:
[Aws default execution order](https://github.com/aws/aws-sdk-java-v2/blob/1b4dead0b4006571770357d28121bce3b89a4a06/core/sdk-core/src/main/java/software/amazon/awssdk/core/interceptor/ClasspathInterceptorChainFactory.java#L57)

**Comment by sima-zhu** [comment]
Option 1:
Define the order and load policy in the right order. The option of the policy need to inject after having the list.

**Comment by sima-zhu** [comment]
Option 2:
Define the order and sort them out based on the order after having the pipeline.

**Comment by sima-zhu** [comment]
Option 3:
Do verification based on the specific order. Verify on duplication as well.

**Comment by alzimmermsft** [comment]
Closing as this likely won't be done. If that sentiment changes in the future this will be re-opened.
