### ISSUE TITLE
BlobItem/BlobMetadata Swagger Generation Issue

### ISSUE THREAD

**Issue by alzimmermsft** [Azure/azure-sdk-for-java#5000]
BlobItem is now using the BlobMetadata class for its Metadata property but the BlobMetadata generation is expecting the XML tags "Encrypted" and "additionalProperties". Nothing in the REST specification mentions XML tags of "additionalProperties".

This should be investigated further to determine the correct generation.

**Comment by kurtzeborn** [comment]
@alzimmermsft, you were suspicious this would require a swagger change or might be a swagger generation issue.

**Comment by alzimmermsft** [comment]
After talking with @jianghaolu we deemed this is a generation issue and will be removing this from the Storage Epic.

**Comment by alzimmermsft** [comment]
Closing as this has been resolved.
