### ISSUE TITLE
Cosmos CFP: remove dependency on child thread providing exception result

### ISSUE THREAD

**Issue by milismsft** [Azure/azure-sdk-for-java#5015]
In PartitionProcessor as well as PartitionSupervisor we rely on the child thread to set any exception that might be raised and the parent constantly monitoring the child for such exception. This could be changed to use Reactor's Mono.error() calls but there's an open question about the timings between the exception happening and the parent reacting to it which requires some extensive testing on the side.

**Comment by kushagraThapar** [comment]
@milismsft - is this still a valid issue or can we close it ?
