### ISSUE TITLE
Possible final fields with default accessors needs to be reviewed and updated

### ISSUE THREAD

**Issue by vhvb1989** [Azure/azure-sdk-for-java#5030]
# Checkstyle rule:
Fields should be 'final' when:
- Initialized and never reassigned in constructor or other methods.
- Only assigned in constructor and no other method. 

Next cases below has one of this rules and fields are not final because they have `default` access to enable direct assignation from same package classes.

Please review each case and decide if this `default` access is required or if it can be changed to `private` and then adding a `default access` method in the class to have that field updated (encapsulate fields).

Each file is currently suppressed. Please remove checkstyle suppress after updating the file

# Reference info:
_Originally posted by @conniey in https://github.com/Azure/azure-sdk-for-java/pull/5009/files_

# Cases

1 KeyCreateOptions.java  (KV)
2 LocalKeyCryptographyClient.java (KV)

**Comment by joshfree** [comment]
Editing bug to split apart KV and Identity work separately

**Comment by vcolin7** [comment]
As a note, `KeyCreateOptions` was renamed to [`CreateKeyOptions`](https://github.com/Azure/azure-sdk-for-java/blob/master/sdk/keyvault/azure-security-keyvault-keys/src/main/java/com/azure/security/keyvault/keys/models/CreateKeyOptions.java).

**Comment by vcolin7** [comment]
Created a PR (#13323) to address this.
