### ISSUE TITLE
[BUG] AzConfig Revisions Range Returns 416 Status Code

### ISSUE THREAD

**Issue by mrm9084** [Azure/azure-sdk-for-java#5041]
When calling ConfigurationAsyncClient.listSettingRevions with a Range value set in the SettingSelector throws an uncaught error:
```
com.azure.core.exception.HttpResponseException: Status code 416, (empty body)
```
when trying with a range(0,0). Other Range values result in the same error or no return.

Code Used:
```
SettingSelector settingSelector = new SettingSelector().keys(watchedKeyNames).labels(store.getLabels())
                .range(new Range(0, 0));
PagedFlux<ConfigurationSetting> settings = client.listSettingRevisions(settingSelector);
pagedResponses = page.collectList().block();
```

**Comment by JonathanGiles** [comment]
@alzimmermsft Can you please take a look?

**Comment by mrm9084** [comment]
I was taking another look at it, and it might not be range that is causing the issue, but the label value being used didn't exist in the store being searched. I added the label and now the search worked. I verified by searching for another label that didn't exist and I received similar results.

**Comment by alzimmermsft** [comment]
> 
> 
> I was taking another look at it, and it might not be range that is causing the issue, but the label value being used didn't exist in the store being searched. I added the label and now the search worked. I verified by searching for another label that didn't exist and I received similar results.

This would align with getting a 416 response which is returned when the listing couldn't satisfy the range requested.

**Comment by JonathanGiles** [comment]
@alzimmermsft Can we improve the error message here to provide more useful guidance?

**Comment by mrm9084** [comment]
@JonathanGiles The HttpResponseException: Status code 416, (empty body), doesn't really point to the issue. What I would be expecting is something closer to an invalid input exception. Or at least the message saying "Expected n results, found none." That way it points to the expected range being the issue.

**Comment by JonathanGiles** [comment]
We are in agreement here. @alzimmermsft will look into improving the messaging.

**Comment by alzimmermsft** [comment]
@mssfang This is enhancing the message returned when this exception occurs.

**Comment by srnagar** [comment]
I spoke to @JonathanGiles about this and concluded this to be a non-blocking issue for the GA release. We can look into fixing this post-GA.

**Comment by mssfang** [comment]
As we discussed offline. This issue will no longer an issue. The Range object will need to be removed and using Paging to retrieve the latest revision. Each page will have 100 items at most.
