### ISSUE TITLE
Batch insert support based on async sdk

### ISSUE THREAD

**Issue by chetanmeh** [Azure/azure-sdk-for-java#5049]
CosmosDB provides a [bulk insert][1] support and has a [java sdk][2] which seems to be using the [sync sdk][3]. 

Is there any way to use similar approach with async sdk to do some sort of batch insert? In our case we need to insert lots of immutable docs (which are generated based on incoming events from kafka) and with current approach of 1 write call per document we are hitting pool limits. 

We see 2 options

1. Use a queued writer and then do inserts with a controlled degree of parallel writes
2. Use the bulk import logic which uses a [stored procedure][4] under the hood.

Any suggestion on which approach to use? If Azure/azure-cosmosdb-java#2 then any sample to use similar approach with async sdk

[1]: https://docs.microsoft.com/en-us/azure/cosmos-db/bulk-executor-overview
[2]: https://docs.microsoft.com/en-us/azure/cosmos-db/bulk-executor-java
[3]: https://github.com/Azure/azure-documentdb-java
[4]: https://chapsas.com/how-the-cosmosdb-bulk-executor-works-under-the-hood/

**Comment by christopheranderson** [comment]
We're working on a new bulk based on the V3 SDK.

@David-Noble-at-work - once we create work items for Batch/Bulk, please link to this issue.

**Comment by David-Noble-at-work** [comment]
The batch and bulk API work has just begun. Please track our progress by keeping an eye on this issue:
* #6712, [FEATURE] Batch and Bulk API for Java SDK v4.1
