### ISSUE TITLE
A clean build using IntelliJ 14 on OS X fails with a number of auto generated Service Bus classes not created

### ISSUE THREAD

**Issue by jmspring** [Azure/azure-sdk-for-java#505]
Steps to repro:
1. Check out azure-java-sdk
2. Change to dev branch
3. Import project into Intellij 14
4. Build project

The following failures below occur.  This can be gotten around by running a "mvn package" from the cli to force the generation of the classes.

The errors:

/Users/jims/mnt/azuregit/java-hackfest/foo/azure-sdk-for-java/services/azure-servicebus/src/main/java/com/microsoft/windowsazure/services/servicebus/models/QueueInfo.java
Error:(23, 69) java: cannot find symbol
  symbol:   class Content
  location: package com.microsoft.windowsazure.services.servicebus.implementation
Error:(24, 69) java: cannot find symbol
  symbol:   class EntityAvailabilityStatus
  location: package com.microsoft.windowsazure.services.servicebus.implementation
Error:(25, 69) java: cannot find symbol
  symbol:   class EntityStatus
  location: package com.microsoft.windowsazure.services.servicebus.implementation
Error:(26, 69) java: cannot find symbol
  symbol:   class Entry
  location: package com.microsoft.windowsazure.services.servicebus.implementation
Error:(28, 69) java: cannot find symbol
  symbol:   class MessageCountDetails
  location: package com.microsoft.windowsazure.services.servicebus.implementation
Error:(29, 69) java: cannot find symbol
  symbol:   class PartitioningPolicy
  location: package com.microsoft.windowsazure.services.servicebus.implementation
Error:(30, 69) java: cannot find symbol
  symbol:   class QueueDescription
  location: package com.microsoft.windowsazure.services.servicebus.implementation
Error:(35, 43) java: cannot find symbol
  symbol: class QueueDescription
Error:(54, 22) java: cannot find symbol
  symbol:   class Entry
  location: class com.microsoft.windowsazure.services.servicebus.models.QueueInfo
Error:(442, 12) java: cannot find symbol
  symbol:   class EntityStatus
  location: class com.microsoft.windowsazure.services.servicebus.models.QueueInfo
Error:(454, 32) java: cannot find symbol
  symbol:   class EntityStatus
  location: class com.microsoft.windowsazure.services.servicebus.models.QueueInfo
Error:(465, 12) java: cannot find symbol
  symbol:   class EntityAvailabilityStatus
  location: class com.microsoft.windowsazure.services.servicebus.models.QueueInfo
Error:(478, 13) java: cannot find symbol
  symbol:   class EntityAvailabilityStatus
  location: class com.microsoft.windowsazure.services.servicebus.models.QueueInfo
Error:(561, 12) java: cannot find symbol
  symbol:   class PartitioningPolicy
  location: class com.microsoft.windowsazure.services.servicebus.models.QueueInfo
Error:(574, 44) java: cannot find symbol
  symbol:   class PartitioningPolicy
  location: class com.microsoft.windowsazure.services.servicebus.models.QueueInfo
Error:(608, 12) java: cannot find symbol
  symbol:   class MessageCountDetails
  location: class com.microsoft.windowsazure.services.servicebus.models.QueueInfo
Error:(41, 19) java: cannot find symbol
  symbol:   class Entry
  location: class com.microsoft.windowsazure.services.servicebus.models.QueueInfo
Error:(41, 32) java: cannot find symbol
  symbol:   class QueueDescription
  location: class com.microsoft.windowsazure.services.servicebus.models.QueueInfo
Error:(42, 35) java: cannot find symbol
  symbol:   class Content
  location: class com.microsoft.windowsazure.services.servicebus.models.QueueInfo
/Users/jims/mnt/azuregit/java-hackfest/foo/azure-sdk-for-java/services/azure-servicebus/src/main/java/com/microsoft/windowsazure/services/servicebus/implementation/EntryModel.java
Error:(18, 13) java: cannot find symbol
  symbol:   class Entry
  location: class com.microsoft.windowsazure.services.servicebus.implementation.EntryModel<T>
Error:(21, 23) java: cannot find symbol
  symbol:   class Entry
  location: class com.microsoft.windowsazure.services.servicebus.implementation.EntryModel<T>
Error:(26, 12) java: cannot find symbol
  symbol:   class Entry
  location: class com.microsoft.windowsazure.services.servicebus.implementation.EntryModel<T>
Error:(30, 26) java: cannot find symbol
  symbol:   class Entry
  location: class com.microsoft.windowsazure.services.servicebus.implementation.EntryModel<T>
/Users/jims/mnt/azuregit/java-hackfest/foo/azure-sdk-for-java/services/azure-servicebus/src/main/java/com/microsoft/windowsazure/services/servicebus/models/TopicInfo.java
Error:(23, 69) java: cannot find symbol
  symbol:   class Content
  location: package com.microsoft.windowsazure.services.servicebus.implementation
Error:(24, 69) java: cannot find symbol
  symbol:   class EntityAvailabilityStatus
  location: package com.microsoft.windowsazure.services.servicebus.implementation
Error:(25, 69) java: cannot find symbol
  symbol:   class EntityStatus
  location: package com.microsoft.windowsazure.services.servicebus.implementation
Error:(26, 69) java: cannot find symbol
  symbol:   class Entry
  location: package com.microsoft.windowsazure.services.servicebus.implementation
Error:(28, 69) java: cannot find symbol
  symbol:   class MessageCountDetails
  location: package com.microsoft.windowsazure.services.servicebus.implementation
Error:(29, 69) java: cannot find symbol
  symbol:   class PartitioningPolicy
  location: package com.microsoft.windowsazure.services.servicebus.implementation
Error:(30, 69) java: cannot find symbol
  symbol:   class TopicDescription
  location: package com.microsoft.windowsazure.services.servicebus.implementation
Error:(35, 43) java: cannot find symbol
  symbol: class TopicDescription
Error:(54, 22) java: cannot find symbol
  symbol:   class Entry
  location: class com.microsoft.windowsazure.services.servicebus.models.TopicInfo
Error:(300, 32) java: cannot find symbol
  symbol:   class EntityStatus
  location: class com.microsoft.windowsazure.services.servicebus.models.TopicInfo
Error:(311, 12) java: cannot find symbol
  symbol:   class EntityStatus
  location: class com.microsoft.windowsazure.services.servicebus.models.TopicInfo
Error:(460, 12) java: cannot find symbol
  symbol:   class MessageCountDetails
  location: class com.microsoft.windowsazure.services.servicebus.models.TopicInfo
Error:(497, 44) java: cannot find symbol
  symbol:   class PartitioningPolicy
  location: class com.microsoft.windowsazure.services.servicebus.models.TopicInfo
Error:(508, 12) java: cannot find symbol
  symbol:   class PartitioningPolicy
  location: class com.microsoft.windowsazure.services.servicebus.models.TopicInfo
Error:(522, 13) java: cannot find symbol
  symbol:   class EntityAvailabilityStatus
  location: class com.microsoft.windowsazure.services.servicebus.models.TopicInfo
Error:(533, 12) java: cannot find symbol
  symbol:   class EntityAvailabilityStatus
  location: class com.microsoft.windowsazure.services.servicebus.models.TopicInfo
Error:(40, 19) java: cannot find symbol
  symbol:   class Entry
  location: class com.microsoft.windowsazure.services.servicebus.models.TopicInfo
Error:(40, 32) java: cannot find symbol
  symbol:   class TopicDescription
  location: class com.microsoft.windowsazure.services.servicebus.models.TopicInfo
Error:(41, 35) java: cannot find symbol
  symbol:   class Content
  location: class com.microsoft.windowsazure.services.servicebus.models.TopicInfo
/Users/jims/mnt/azuregit/java-hackfest/foo/azure-sdk-for-java/services/azure-servicebus/src/main/java/com/microsoft/windowsazure/services/servicebus/models/SubscriptionInfo.java
Error:(22, 69) java: cannot find symbol
  symbol:   class Content
  location: package com.microsoft.windowsazure.services.servicebus.implementation
Error:(23, 69) java: cannot find symbol
  symbol:   class EntityAvailabilityStatus
  location: package com.microsoft.windowsazure.services.servicebus.implementation
Error:(24, 69) java: cannot find symbol
  symbol:   class EntityStatus
  location: package com.microsoft.windowsazure.services.servicebus.implementation
Error:(25, 69) java: cannot find symbol
  symbol:   class Entry
  location: package com.microsoft.windowsazure.services.servicebus.implementation
Error:(27, 69) java: cannot find symbol
  symbol:   class MessageCountDetails
  location: package com.microsoft.windowsazure.services.servicebus.implementation
Error:(28, 69) java: cannot find symbol
  symbol:   class RuleDescription
  location: package com.microsoft.windowsazure.services.servicebus.implementation
Error:(29, 69) java: cannot find symbol
  symbol:   class SubscriptionDescription
  location: package com.microsoft.windowsazure.services.servicebus.implementation
Error:(34, 50) java: cannot find symbol
  symbol: class SubscriptionDescription
Error:(53, 29) java: cannot find symbol
  symbol:   class Entry
  location: class com.microsoft.windowsazure.services.servicebus.models.SubscriptionInfo
Error:(230, 12) java: cannot find symbol
  symbol:   class RuleDescription
  location: class com.microsoft.windowsazure.services.servicebus.models.SubscriptionInfo
Error:(244, 55) java: cannot find symbol
  symbol:   class RuleDescription
  location: class com.microsoft.windowsazure.services.servicebus.models.SubscriptionInfo
Error:(329, 39) java: cannot find symbol
  symbol:   class EntityStatus
  location: class com.microsoft.windowsazure.services.servicebus.models.SubscriptionInfo
Error:(340, 12) java: cannot find symbol
  symbol:   class EntityStatus
  location: class com.microsoft.windowsazure.services.servicebus.models.SubscriptionInfo
Error:(466, 13) java: cannot find symbol
  symbol:   class EntityAvailabilityStatus
  location: class com.microsoft.windowsazure.services.servicebus.models.SubscriptionInfo
Error:(477, 12) java: cannot find symbol
  symbol:   class EntityAvailabilityStatus
  location: class com.microsoft.windowsazure.services.servicebus.models.SubscriptionInfo
Error:(487, 12) java: cannot find symbol
  symbol:   class MessageCountDetails
  location: class com.microsoft.windowsazure.services.servicebus.models.SubscriptionInfo
Error:(40, 19) java: cannot find symbol
  symbol:   class Entry
  location: class com.microsoft.windowsazure.services.servicebus.models.SubscriptionInfo
Error:(40, 32) java: cannot find symbol
  symbol:   class SubscriptionDescription
  location: class com.microsoft.windowsazure.services.servicebus.models.SubscriptionInfo
Error:(41, 35) java: cannot find symbol
  symbol:   class Content
  location: class com.microsoft.windowsazure.services.servicebus.models.SubscriptionInfo
/Users/jims/mnt/azuregit/java-hackfest/foo/azure-sdk-for-java/services/azure-servicebus/src/main/java/com/microsoft/windowsazure/services/servicebus/models/RuleInfo.java
Error:(21, 69) java: cannot find symbol
  symbol:   class Content
  location: package com.microsoft.windowsazure.services.servicebus.implementation
Error:(22, 69) java: cannot find symbol
  symbol:   class CorrelationFilter
  location: package com.microsoft.windowsazure.services.servicebus.implementation
Error:(23, 69) java: cannot find symbol
  symbol:   class EmptyRuleAction
  location: package com.microsoft.windowsazure.services.servicebus.implementation
Error:(24, 69) java: cannot find symbol
  symbol:   class Entry
  location: package com.microsoft.windowsazure.services.servicebus.implementation
Error:(26, 69) java: cannot find symbol
  symbol:   class FalseFilter
  location: package com.microsoft.windowsazure.services.servicebus.implementation
Error:(27, 69) java: cannot find symbol
  symbol:   class Filter
  location: package com.microsoft.windowsazure.services.servicebus.implementation
Error:(28, 69) java: cannot find symbol
  symbol:   class RuleAction
  location: package com.microsoft.windowsazure.services.servicebus.implementation
Error:(29, 69) java: cannot find symbol
  symbol:   class RuleDescription
  location: package com.microsoft.windowsazure.services.servicebus.implementation
Error:(30, 69) java: cannot find symbol
  symbol:   class SqlFilter
  location: package com.microsoft.windowsazure.services.servicebus.implementation
Error:(31, 69) java: cannot find symbol
  symbol:   class SqlRuleAction
  location: package com.microsoft.windowsazure.services.servicebus.implementation
Error:(32, 69) java: cannot find symbol
  symbol:   class TrueFilter
  location: package com.microsoft.windowsazure.services.servicebus.implementation
Error:(37, 42) java: cannot find symbol
  symbol: class RuleDescription
Error:(57, 21) java: cannot find symbol
  symbol:   class Entry
  location: class com.microsoft.windowsazure.services.servicebus.models.RuleInfo
Error:(105, 12) java: cannot find symbol
  symbol:   class Filter
  location: class com.microsoft.windowsazure.services.servicebus.models.RuleInfo
Error:(118, 31) java: cannot find symbol
  symbol:   class Filter
  location: class com.microsoft.windowsazure.services.servicebus.models.RuleInfo
Error:(128, 12) java: cannot find symbol
  symbol:   class RuleAction
  location: class com.microsoft.windowsazure.services.servicebus.models.RuleInfo
Error:(141, 31) java: cannot find symbol
  symbol:   class RuleAction
  location: class com.microsoft.windowsazure.services.servicebus.models.RuleInfo
Error:(43, 19) java: cannot find symbol
  symbol:   class Entry
  location: class com.microsoft.windowsazure.services.servicebus.models.RuleInfo
Error:(43, 32) java: cannot find symbol
  symbol:   class RuleDescription
  location: class com.microsoft.windowsazure.services.servicebus.models.RuleInfo
Error:(44, 35) java: cannot find symbol
  symbol:   class Content
  location: class com.microsoft.windowsazure.services.servicebus.models.RuleInfo
Error:(154, 9) java: cannot find symbol
  symbol:   class CorrelationFilter
  location: class com.microsoft.windowsazure.services.servicebus.models.RuleInfo
Error:(154, 40) java: cannot find symbol
  symbol:   class CorrelationFilter
  location: class com.microsoft.windowsazure.services.servicebus.models.RuleInfo
Error:(167, 9) java: cannot find symbol
  symbol:   class SqlFilter
  location: class com.microsoft.windowsazure.services.servicebus.models.RuleInfo
Error:(167, 32) java: cannot find symbol
  symbol:   class SqlFilter
  location: class com.microsoft.windowsazure.services.servicebus.models.RuleInfo
Error:(179, 9) java: cannot find symbol
  symbol:   class TrueFilter
  location: class com.microsoft.windowsazure.services.servicebus.models.RuleInfo
Error:(179, 33) java: cannot find symbol
  symbol:   class TrueFilter
  location: class com.microsoft.windowsazure.services.servicebus.models.RuleInfo
Error:(191, 9) java: cannot find symbol
  symbol:   class FalseFilter
  location: class com.microsoft.windowsazure.services.servicebus.models.RuleInfo
Error:(191, 34) java: cannot find symbol
  symbol:   class FalseFilter
  location: class com.microsoft.windowsazure.services.servicebus.models.RuleInfo
Error:(203, 9) java: cannot find symbol
  symbol:   class EmptyRuleAction
  location: class com.microsoft.windowsazure.services.servicebus.models.RuleInfo
Error:(203, 38) java: cannot find symbol
  symbol:   class EmptyRuleAction
  location: class com.microsoft.windowsazure.services.servicebus.models.RuleInfo
Error:(215, 9) java: cannot find symbol
  symbol:   class SqlRuleAction
  location: class com.microsoft.windowsazure.services.servicebus.models.RuleInfo
Error:(215, 36) java: cannot find symbol
  symbol:   class SqlRuleAction
  location: class com.microsoft.windowsazure.services.servicebus.models.RuleInfo
/Users/jims/mnt/azuregit/java-hackfest/foo/azure-sdk-for-java/services/azure-servicebus/src/main/java/com/microsoft/windowsazure/services/servicebus/implementation/EntryModelProvider.java
Error:(54, 27) java: cannot find symbol
  symbol:   class Entry
  location: class com.microsoft.windowsazure.services.servicebus.implementation.EntryModelProvider
Error:(55, 17) java: cannot find symbol
  symbol:   class Entry
  location: class com.microsoft.windowsazure.services.servicebus.implementation.EntryModelProvider
Error:(55, 30) java: cannot find symbol
  symbol:   class Entry
  location: class com.microsoft.windowsazure.services.servicebus.implementation.EntryModelProvider
Error:(57, 9) java: cannot find symbol
  symbol:   class Entry
  location: class com.microsoft.windowsazure.services.servicebus.implementation.EntryModelProvider
Error:(57, 39) java: cannot find symbol
  symbol:   class Entry
  location: class com.microsoft.windowsazure.services.servicebus.implementation.EntryModelProvider
Error:(57, 52) java: cannot find symbol
  symbol:   class Entry
  location: class com.microsoft.windowsazure.services.servicebus.implementation.EntryModelProvider
Error:(63, 40) java: cannot find symbol
  symbol:   class Entry
  location: class com.microsoft.windowsazure.services.servicebus.implementation.EntryModelProvider

**Comment by martinsawicki** [comment]
the service bus client library is not in this repo anymore, so if this is still an issue, it should go there:
https://github.com/azure/azure-service-bus-java
