### ISSUE TITLE
Review Checkstyle and SpotBugs Exclusions

### ISSUE THREAD

**Issue by alzimmermsft** [Azure/azure-sdk-for-java#5059]
Should take the time to review the Checkstyles and SpotBugs exclusions we have configured to see what is still relevant and ensure that our exclusions are suppressing actual issues.

**Comment by kurtzeborn** [comment]
Relabeling "Client" because this is something the libraries teams really has the expertise to make correct decisions for.

**Comment by alzimmermsft** [comment]
Closing as a review of these have been done and are periodically cleaned and updated.
