### ISSUE TITLE
Management libraries should be included in DependencyManagement

### ISSUE THREAD

**Issue by bsiegel** [Azure/azure-sdk-for-java#5062]
The client libraries currently manage their dependency versions via dependencyManagement in the parent POM. The management libraries should also share the same dependencyManagement section so that dependency versions are consistent across management & client libraries. The dependency checker should then analyze both sets of libraries.

**Comment by yaohaizh** [comment]
@bsiegel, we already have the same dependencyManagement to the ./parent/pom.xml for management plane, so is there any additional work item that management plane need handle? Thanks.

**Comment by bsiegel** [comment]
Hey @yaohaizh, the issue we have with dependencyManagement is that it doesn't enforce anything - individual libraries are free to override what's there with their own dependency versions. Next steps would be to run the dependency analyzer on the management plane libraries and get a report of anywhere they deviate from the dependencyManagement section.

**Comment by yaohaizh** [comment]
Close the issue as it is fixed on https://github.com/Azure/azure-sdk-for-java/pull/5879
