### ISSUE TITLE
[BUG] Missing Link Key Vault Secrets

### ISSUE THREAD

**Issue by Intern426** [Azure/azure-sdk-for-java#5081]
**Describe the bug**
Azure Key Vault Secrets README is missing a link to the Azure Identity client library README

***Exception or Stack Trace***
https://github.com/Azure/azure-sdk-for-java/tree/master/identity/client
(Page not found)

**To Reproduce**
1. Go to the Key Vault secrets README: (https://github.com/Azure/azure-sdk-for-java/tree/master/sdk/keyvault/azure-keyvault-secrets)
2. Select "azure-identity" link under "Authenticate the client." (https://github.com/Azure/azure-sdk-for-java/tree/master/identity/client)

**Comment by g2vinay** [comment]
Thank you for bringing this up.
I will fix this issue soon and update here.

**Comment by joshfree** [comment]
@hemanttanwar can you please ensure this is addressed with the November update README changes you're working on?

**Comment by g2vinay** [comment]
I've fixed this issue.
