### ISSUE TITLE
Update cosmos tag link for release notes

### ISSUE THREAD

**Issue by sima-zhu** [Azure/azure-sdk-for-java#5082]
All doc links in release notes have switched to tag link. Cosmos does not have the release tag. We need to update the document once it has it.

Examples in release note:
https://azure.github.io/azure-sdk/posts/java-preview1/

Please check links in other clients.

**Comment by kushagraThapar** [comment]
@sima-zhu Do we still need to do this ?
The example link is not working for me.

**Comment by kushagraThapar** [comment]
@sima-zhu any updates on this ?
Do we still need this to be fixed or is it working correctly now ?

**Comment by kushagraThapar** [comment]
Closing this because of in-activity, please re-open if this still needs to be acted upon.
