### ISSUE TITLE
Test record missing response for VM extension delete request

### ISSUE THREAD

**Issue by xindzhan** [Azure/azure-sdk-for-java#509]
In (https://github.com/Azure/azure-sdk-for-java/blob/master/resource-management/azure-mgmt-utility/src/test/java/com/microsoft/azure/utility/compute/VMExtensionTests.java#L76) the response is not recorded somehow and the playback will fail.

**Comment by jianghaolu** [comment]
The recording framework is deprecated. We don't have a recording framework in master today. Will implement a completely new one if necessary.
