### ISSUE TITLE
Determine return type for non-paginated listing operations

### ISSUE THREAD

**Issue by jaschrep-msft** [Azure/azure-sdk-for-java#5097]
Paginated listing items return `PagedFlux<T>`. We need to decide if single-request listing operations should return a `PagedFlux<T>` that will only ever fetch one page, or if they should return `Mono<List<T>>` (or `Mono<SomeTypeWithAListInIt>` depending on the specific API).

**Comment by JonathanGiles** [comment]
`PagedFlux<T>` is more user-friendly, in my opinion. I would improve PagedFlux to have a more appropriate constructor so you are not forced to pass in null for the follow-up page arg. I would also improve PagedFlux to clearly document that it may be used in cases where there is only a single page of results. If you agree, we can work to make this so. Thanks.

**Comment by jaschrep-msft** [comment]
Issues exist for the resolution of these discussions.
