### ISSUE TITLE
Support for x-ms-activity-id

### ISSUE THREAD

**Issue by akalfas** [Azure/azure-sdk-for-java#5099]
Given the rest API spec [1] I would have expected easy ways to set the x-ms-activity-id request header that is echoed back in the response. This is possible for calls that use `RequestOptions` via the `setHeader` however for methods using `FeedOptions` or `ChangeFeedOptions` this is not available. 
 
What would be the proper way to set this debugging information in the SDK for the cases highlighted above ?

[1] https://docs.microsoft.com/en-us/rest/api/cosmos-db/common-cosmosdb-rest-response-headers

**Comment by akalfas** [comment]
> I'd like to ask, why do you want to set the activity id yourself? For correlation purposes?

Indeed - this is the reason why I was asking.

> The trick with FeedResponse is that it often aggregates results multiple calls (and thus multipile activity ids), so a single activity id isn't sufficient.

I agree that for perfect pinpointing a single identifier is not enough. Some more advanced mechanisms is needed to achieve this. 

> If so, we're working on OpenCensus/OpenTelemetry support which is a better way to get correlation in a distributed tracing sense.

Is this something that I can look at? Perhaps some preview? Would like to understand how is this going to play out for us.

**Comment by kushagraThapar** [comment]
@akalfas Just wanted to reach out and understand what is it that you still need or were you able to find a workaround ?

**Comment by akalfas** [comment]
@kushagraThapar - sounds to me that the issue is going to be fixed in v4. If that's the case - I'll wait to see where this is heading, the original issue was reported against the v2.x SDK
