### ISSUE TITLE
Azure Java SDK v12's downloadToFile() throws an exception when saving to a file.

### ISSUE THREAD

**Issue by mgingios** [Azure/azure-sdk-for-java#5100]
**Describe the bug**
When I attempt to download a blob from Azure Blob Storage and save it to a file in a directory that I own, an exception is thrown: "java.nio.file.NoSuchFileException: /home/michael/Downloads/animage.jpg".

***Exception or Stack Trace***
Add the exception log and stack trace if available

**To Reproduce**
Use the method that I've included in this posting and pass in a valid uri to a blob.

***Code Snippet***
```
        /**
         * Method downloadBlobToFile reactively streams the contents of a blob from the URI to a new file.
         * @param uri URI is the URI to the blob in Azure Blob Storage.
         */
        fun downloadBlobToFile(uri: URI, path: String) {

            var startTime = 0L
            val fileCounter = AtomicInteger(0)

            // Get the Blob Service client, so we can use it to access blobs, containers, etc.
            BlobServiceClientBuilder()
                // Container URL
                .endpoint(kEndpoint)
                .credential(
                    SharedKeyCredential(
                        kAccountName,
                        kAccountKey
                    )
                )
                .buildAsyncClient()

                // Get the container client so we can work with our container and its blobs.
                .getContainerAsyncClient(kContainerName)

                // Get the block blob client so we can access individual blobs and include the path
                // within the container as part of the filename.
                .getBlockBlobAsyncClient(kBlobName)
                .downloadToFile(path)
                .doOnSubscribe {
                    logger.info("Subscription made to AzureBlobStorageService and requesting '$uri'.")
                    startTime = System.currentTimeMillis()
                }
                .doOnSuccess {
                    val elapsedTime = System.currentTimeMillis() - startTime
                    logger.info("Successfully downloaded '$uri''in $elapsedTime ms from Azure Blob Services.")
                }
                .doOnError {
                    logger.error("Failed to download the blob '$uri'.", it)
                }

                .subscribe()
        }
```

**Expected behavior**
I expected that the blob would be downloaded to a file.

**Screenshots**

**Setup (please complete the following information):**
 - OS: [e.g. iOS] Ubuntu 18.10
 - IDE : [e.g. IntelliJ] IntelliJ Ultimate 2019.2.1
 - Version of the Library used: com.azure:azure-storage-blob:12.0.0-preview.2"

**Additional context**
I can provide a simple project so you can debug this issue.

**Information Checklist**
Kindly make sure that you have added all the following information above and checkoff the required fields otherwise we will treat the issuer as an incomplete report
- [X] Bug Description Added
- [X] Repro Steps Added
- [X] Setup information Added

**Comment by JonathanGiles** [comment]
@alzimmermsft Can you please take a look and assign to the appropriate person for review? My expectation would be that if the file does not exist, but can be created, that it is done so for the end user.
