### ISSUE TITLE
VM Sizes Missing

### ISSUE THREAD

**Issue by devigned** [Azure/azure-sdk-for-java#511]
there is a new release out (0.8.0) but VirtualMachineRoleSize.java still doesn't contain any D, or DS-Series VM types.

/via @bueti

**Comment by bueti** [comment]
>We'll get this corrected this week.

Any news? I don't see a new release in maven central nor here on github.

**Comment by siriusk-MSFT** [comment]
SDK does support these sizes. There is a known gap that DS sizes are not in SizeTypes class, however, you can directly pass in the string like `context.setVirtualMachineSizeType("Standard_DS2")`and it will work.

**Comment by jianghaolu** [comment]
I assume by passing a string this issue is resolved or worked around. Please reopen if needed.
