### ISSUE TITLE
[FEATURE REQ] App Configuration API Versioning

### ISSUE THREAD

**Issue by mrm9084** [Azure/azure-sdk-for-java#5114]
Explicit API Versioning is being added to App Configuration, all request MUST provide explicit API Version as part of the query string parameter.

Example
```
https://example.azconfig.io/kv?api-version=1.0
```
To maintain backward compatibility and avoid breaking changes, all requests that don't provide explicit `api-version` are grounded to version 1.0. They will not be automatically rolled to a newer version in the future.

**Comment by alzimmermsft** [comment]
@mssfang This will require changing the Java SDK from using the hand-written interface layer to the Swagger generated layer.

**Comment by anuchandy** [comment]
@vcolin7 

This PR https://github.com/Azure/azure-sdk-for-java/pull/5782 enables user to specify the api-version for various track2 SDKs and by default it uses the latest version. 

In the above PR, the AzConfig builder is updated to take service version param or default to latest (V1.0) https://github.com/Azure/azure-sdk-for-java/blob/63175789ef146f4f62b8b01320e7154bc8914f78/sdk/appconfiguration/azure-data-appconfiguration/src/main/java/com/azure/data/appconfiguration/ConfigurationClientBuilder.java#L146

But we're not sending it over the wire, the last part is sending this API version to service when calling service methods.

Fix is add following query parameter:
```
QueryParam("api-version") apiVersion
```

to each method in `ConfigurationService` e.g.: 

https://github.com/Azure/azure-sdk-for-java/blob/master/sdk/appconfiguration/azure-data-appconfiguration/src/main/java/com/azure/data/appconfiguration/ConfigurationService.java#L47

then when calling method in `ConfigurationService` from `ConfigurationAsyncClient`, specify the api-version  https://github.com/Azure/azure-sdk-for-java/blob/5a607c4fb25815b5b8000befd50a39aad61cde77/sdk/appconfiguration/azure-data-appconfiguration/src/main/java/com/azure/data/appconfiguration/ConfigurationAsyncClient.java#L161

**Comment by joshfree** [comment]
Removing `blocking-release` and moving this to after Preview 5.

/cc @AlexGhiondea as FYI
