### ISSUE TITLE
[QUERY] How to use Proxy with V12 sdk for blob storage?

### ISSUE THREAD

**Issue by vmaheshw** [Azure/azure-sdk-for-java#5117]
**Query/Question**
How to pass Proxy information in new sdk blob storage?

***Why is this not a Bug or a feature Request?***
I'm hoping this to be present since it was present in V10.5.

This is how I setup proxy with V10.5
PipelineOptions po = new PipelineOptions();
HttpClientConfiguration configuration = new HttpClientConfiguration(
       new Proxy(Proxy.Type.HTTP, new InetSocketAddress(ProxyHost, ProxyPort))); 
po.withClient(HttpClient.createDefault(configuration));

**Setup (please complete the following information if applicable):**
 - OS: [e.g. iOS] iOS
 - IDE : [e.g. IntelliJ] Intellij
 - Version of the Library used: V12
 
 **Information Checklist**
 Kindly make sure that you have added all the following information above and checkoff the required fields otherwise we will treat the issuer as an incomplete report
- [x] Query Added
- [x] Setup information Added

**Comment by vmaheshw** [comment]
@rickle-msft  This option is deprecated in azure-core-1.0.0-preview.4 coming as part of azure-storage-blob-12.0.0-preview.3.jar.

**Comment by alzimmermsft** [comment]
Hi @vmaheshw, 

During the last release of Azure Core and the Storage SDK we made the `HTTPClient` pluggable and released two plugin packages ([Azure Core Http Netty](https://search.maven.org/artifact/com.azure/azure-core-http-netty/1.0.0-preview.4/jar) and [Azure Core Http OkHttp](https://search.maven.org/artifact/com.azure/azure-core-http-okhttp/1.0.0-preview.4/jar)), our recommendation is to use the Netty implementation.

Using the Netty plugin add this dependency to your project
```xml
<dependency>
  <groupId>com.azure</groupId>
  <artifactId>azure-core-http-netty</artifactId>
  <version>1.0.0-preview.4</version>
</dependency>
```

And this is how you would create the same client that @rickle-msft mentioned above using the Netty plugin.
```java
HttpClient client = new NettyAsyncHttpClientBuilder()
    .proxy(new ProxyOptions(ProxyOptions.Type.HTTP, new InetSocketAddress("localhost", 8888)))
    .build();
```

And for the OkHttp plugin
```xml
<dependency>
  <groupId>com.azure</groupId>
  <artifactId>azure-core-http-okhttp</artifactId>
  <version>1.0.0-preview.4</version>
</dependency>
```

```java
HttpClient client = new OkHttpAsyncHttpClientBuilder()
    .proxy(new Proxy(Proxy.Type.HTTP, new InetSocketAddress("localhost", 8888)))
    .build();
```

If you have any additional questions on the new pattern please let me know.

**Comment by kurtzeborn** [comment]
@vmaheshw, it looks like this is sorted out now.  Feel free to re-open if you have further questions on this.

**Comment by timaar** [comment]
> ```java
> HttpClient client = new NettyAsyncHttpClientBuilder()
>     .proxy(new ProxyOptions(ProxyOptions.Type.HTTP, new InetSocketAddress("localhost", 8888)))
>     .build();
> ```

At the moment preview 4 the proxy on the httpclient has been removed 

I guess you need to to something like this now:

Configuration config = new Configuration();
            config.put(Configuration.PROPERTY_HTTPS_PROXY, "myproxyserver:8080");

...

            BlobContainerClient blobContainerClient = new BlobContainerClientBuilder()
                    .endpoint(azureSasUrl)
                    .containerName(azureContainerName)
                    .configuration(config)
                    .httpClient(client)
                    .buildClient();
