### ISSUE TITLE
Code does not compile - QueueDescription

### ISSUE THREAD

**Issue by erickbp** [Azure/azure-sdk-for-java#512]
Hi,

The code does not compile. Is that expected? one of the issues is that the class QueueDescription does not exist.

Any idea what I am doing wrong?

Thanks

**Comment by devigned** [comment]
hmm... that looks like the service bus pom and a few classes were deleted. Perhaps there was a bad merge along the way.

@ljhljh235 I dropped back to the 0.7.0 tag and both media and service bus have pom and full Azure Service Management implementations. Something must have gotten messed up at some point in 0.8.0 release.

**Comment by devigned** [comment]
@erickbp the code compiles under maven, but if you add all the source to eclipse or something else that isn't configured to use our poms, then you'd run into this issue. For the time being, if you can, use `mvn clean verify`.

**Comment by ljhljh235** [comment]
@erickbp Are you seeing the same errors described in https://github.com/Azure/azure-sdk-for-java/issues/505?

**Comment by erickbp** [comment]
@devigned Thanks
@ljhljh235 I haven't tried IntelliJ 14. I think I see something similar if I try to open the source code directly into Eclipse.

**Comment by erickbp** [comment]
@devigned when run "mvn clean verify" I get a failure at Microsoft Azure SDK Core Test Helpers

Log : https://onedrive.live.com/redir?resid=8C9AD83EBE369265!12592&authkey=!ADGNFfONEb2nymw&ithint=file%2ctxt

**Comment by ljhljh235** [comment]
@erickbp That error means you already have a JVM instance running. Could you double check on that?

That known issue applies to both IntelliJ and Eclipse. For now you will have to build on your command line and then both IntelliJ and Eclipse will understand it well.

**Comment by erickbp** [comment]
@ljhljh235 You are right, I had a JVM instance running.
Does this Azure Java SDK work in Android? It works fine for me in a Java application but I cannot make it work in an Android application.
Thanks

**Comment by ljhljh235** [comment]
@erickbp We have a repo https://github.com/azure/azure-sdk-for-android for Android but it's extremely old. It's great if what you need is in there but if not we are in the process of rewriting the whole Java SDK and the new one will be supported on Android.

**Comment by erickbp** [comment]
@ljhljh235 thank you! can you please check the link? I get 404

**Comment by ljhljh235** [comment]
Ahh I just realized it's a private repository. That means at that time we didn't even decide to let it go public! Then we would have to wait until the new SDK comes out.

**Comment by devigned** [comment]
@erickbp can you provide a repro for how you are trying to compile and the errors you are receiving?

**Comment by erickbp** [comment]
@devigned "mvn clean verify" was not 100% successful in 2 different PCs I tried.
PC 1:
- I had an Android VM ( KitKat ) running
- Java SDK 1.8
- Windows 10 Enterprise, 

PC 2:
- Java SDK 1.7
- Windows 10 Pro

In both PC "mvn compile" worked fine, only "mvn clean verify" didn't work.

Thanks

**Comment by devigned** [comment]
Please provide the error output from the mvn clean verify.

**Comment by erickbp** [comment]
It is in the link above. or do you refer to a different error log?

**Comment by martinsawicki** [comment]
the service bus client library is not in this repo anymore, so if this is still an issue, it should go there:
https://github.com/azure/azure-service-bus-java
