### ISSUE TITLE
ARM resouces client doesn't support query on resource group name prefix?

### ISSUE THREAD

**Issue by xindzhan** [Azure/azure-sdk-for-java#513]
In [ARM client](https://github.com/Azure/azure-sdk-for-java/blob/dev/resource-management/azure-mgmt-resources/src/main/java/com/microsoft/azure/management/resources/ResourceGroupOperations.java)
there seems to be no way to query against partial name or prefix of resource group?

**Comment by jianghaolu** [comment]
I don't think this functionality is provided in SDK? I know it's available in PowerShell but I believe a client-side manual filtering was implemented.
