### ISSUE TITLE
[BUG] Not able to see any Logs from SDK Storage Blob

### ISSUE THREAD

**Issue by vmaheshw** [Azure/azure-sdk-for-java#5130]
**Describe the bug**
I want to see the logs for http request, retry number and http response with total time (any delay). I used the following api, but I'm not able see any logs.
   BlobServiceClient storageClient = new BlobServiceClientBuilder().endpoint(endpoint).credential(credential).httpLogDetailLevel(HttpLogDetailLevel.BODY_AND_HEADERS).buildClient();

***Exception or Stack Trace***

**To Reproduce**
Current git Master and add this line in BasicExamples.java
***Code Snippet***
Add the code snippet that causes the issue.

**Expected behavior**

**Screenshots**

**Setup (please complete the following information):**
 - OS: [e.g. iOS] iOS
 - IDE : [e.g. IntelliJ] Intellij
 - Version of the Library used: Latest git

**Additional context**

**Information Checklist**
Kindly make sure that you have added all the following information above and checkoff the required fields otherwise we will treat the issuer as an incomplete report
- [x] Bug Description Added
- [x] Repro Steps Added
- [x] Setup information Added

**Comment by rickle-msft** [comment]
@JonathanGiles could you also comment on whether we'd be able to bring forward some of the v11 functionality like logging slow requests as a warning?

**Comment by JonathanGiles** [comment]
Definitely. Open to PRs to enable this.

**Comment by vmaheshw** [comment]
System.setProperty(BaseConfigurations.AZURE_LOG_LEVEL, "1");

@rickle-msft This is how I'm able to see the logs. Is this the only way?

**Comment by rickle-msft** [comment]
That is one of the ways currently. @alzimmermsft suggested that there is one other option and can hopefully share it here. I also gather that there are plans to revamp that interface. Logging comes from the core SDK instead of Storage specifically, so I'll have to rely on Alan for more details.

**Comment by alzimmermsft** [comment]
@vmaheshw There are two ways to set the logging level, either setting a property or using an environment variable. Both will check for `BaseConfigurations.AZURE_LOG_LEVEL` and the property takes precedence over the environment variable. Is the concern around this on the value that needs to be set or the default logging level?

**Comment by kurtzeborn** [comment]
Logs can be enabled via the two methods mentioned above.  @vmaheshw please re-open this issue if you have further needs or requests regarding this.

**Comment by vmaheshw** [comment]
@rickle-msft : Any update on the feature to got WARN for slow requests and customize the timer as discussed above. This was present in V10.5

**Comment by rickle-msft** [comment]
Logging is handled in Azure Core, so I can't say for certain, but from what I'm seeing, it looks like it'll be included in preview 5 (next month) as the goal for preview 4 has been to get as many of the api breaks finished as possible so they are out of the way earlier rather than later
