### ISSUE TITLE
[Feature] Support TokenCredential in AppConfiguration

### ISSUE THREAD

**Issue by alzimmermsft** [Azure/azure-sdk-for-java#5131]
Right now AppConfiguration only supports a custom credential type, support for TokenCredential needs to be added to support MSI, AAD, and other token authorization types.

**Comment by alzimmermsft** [comment]
@mssfang This is pending resolution based on talks we have with the service team.

**Comment by srnagar** [comment]
Is this a blocking issue for GA? Can this be added as new feature post-GA?
@mssfang @alzimmermsft

**Comment by joshfree** [comment]
Discussed offline not blocking release
