### ISSUE TITLE
Dependency checker takes a long time to generate reports for Release pipelines

### ISSUE THREAD

**Issue by bsiegel** [Azure/azure-sdk-for-java#5134]
The dependency checker takes ~45 minutes to generate a report in the Release pipeline. The issue seems to be with the shrinkwrap-resolver library trying to resolve the dependencies from the wrong location. Looking at the logs, it attempts to locate non-snapshot dependencies from the Snapshot repository. It then hangs for tens of minutes before trying to resolve another set of dependencies.  When run during the Build pipeline, it doesn't do this.

Strangely it does eventually succeed at generating a report.

Following up from #4905.

**Comment by kurtzeborn** [comment]
This was addressed (maybe "swept under the rug" would be better here) by moving it into the Agregate Reports pipeline and out of the inner dev loop path.
