### ISSUE TITLE
Usage of static logger instance in public static methods at CertificateUtil.java

### ISSUE THREAD

**Issue by mssfang** [Azure/azure-sdk-for-java#5137]
The public static method use static logger. But GoodLoggerCheck won't allow static logger.

https://github.com/Azure/azure-sdk-for-java/blob/master/sdk/identity/azure-identity/src/main/java/com/azure/identity/implementation/util/CertificateUtil.java#L27

**Comment by JonathanGiles** [comment]
Please update this issue with a fully-qualified reference to the bad file.

**Comment by alzimmermsft** [comment]
Closing as the guideline is changing around static loggers. https://github.com/Azure/azure-sdk/pull/1155
