### ISSUE TITLE
[Event Hubs] EventHubConsumer occasionally fails to consume all messages

### ISSUE THREAD

**Issue by mikeharder** [Azure/azure-sdk-for-java#5157]
When running a perf tests which attempts to consume 1M messages (spread across 32 partitions), the perf test occasionally gets stuck at less than 1M messages.  I don't have more information at  this time.  The perf test will need to be updated with more logging to understand what's getting stuck.

https://github.com/mikeharder/EventHubsPerf/blob/master/java/eventhubsconsumeperf/src/main/java/com/microsoft/eventhubsconsumeperf/App.java

**Comment by conniey** [comment]
Setting AZURE_LOG_LEVEL = 3 will also show warnings and AZURE_LOG_LEVEL = 4 will show errors.
