### ISSUE TITLE
Fix Blob SAS User Delegation Tests to work in playback mode

### ISSUE THREAD

**Issue by gapra-msft** [Azure/azure-sdk-for-java#5167]
Blob SAS user delegation tests currently set to ignore. They work in record mode. Work needs to be done to figure out why they don't work in playback mode.

**Comment by sima-zhu** [comment]
Root cause:
For user delegate key, we use skoid for signature. The field did not capture by our record test framework. Needs to change in azure-core-test for long run,

Delete json files for short term plan.

**Comment by sima-zhu** [comment]
If the skoid does not count as secret, then we only need some changes in tests.

**Comment by sima-zhu** [comment]
Close as the playback working right now
