### ISSUE TITLE
Enable Checkstyle Rules in IntelliJ Checkstyle Plugin

### ISSUE THREAD

**Issue by alzimmermsft** [Azure/azure-sdk-for-java#5168]
IntelliJ has a plugin that will run Checkstyle rules in the IDE. This works great for Checkstyle configurations that don't use custom rules, we should investigate enabling this to work with our rules.

**Comment by saragluna** [comment]
Any update on this? Need the plugin to work with this repo's checkstyle rules.

**Comment by chenrujun** [comment]
Could you please provide a xml file just like [intellij-java-google-style.xml](https://github.com/google/styleguide/blob/gh-pages/intellij-java-google-style.xml) ?

**Comment by alzimmermsft** [comment]
This isn't an automatic fix to this issue but a guide which will allow for live Checkstyles and SpotBugs to run in IntelliJ.

**Enabling SpotBugs**

- [ ] Install the plugin.

![image](https://user-images.githubusercontent.com/48699787/88987462-d3dcbc80-d28a-11ea-8660-36c56a83e651.png)

- [ ] Add our SpotBugs excludes in the configuration.

![image](https://user-images.githubusercontent.com/48699787/88987480-e7882300-d28a-11ea-8862-07899a567981.png)


**Enabling Checkstyle**

- [ ] Install the plugin.

![image](https://user-images.githubusercontent.com/48699787/88987514-02f32e00-d28b-11ea-898a-a60c1a525049.png)

- [ ] Add code-quality-reports as a library.

![image](https://user-images.githubusercontent.com/48699787/88987541-1a321b80-d28b-11ea-9086-88810543dc1a.png)

- [ ] Configure Checkstyle and our suppressions.

![image](https://user-images.githubusercontent.com/48699787/88987552-26b67400-d28b-11ea-8d8a-50de65264568.png)


The Checkstyle plugin may lock the custom Checkstyles JAR for deletion with may cause `mvn clean` to fail.
