### ISSUE TITLE
PostShutdownAction enums should be case sensitive

### ISSUE THREAD

**Issue by nclemeur** [Azure/azure-sdk-for-java#521]
The refactoring of

com.microsoft.windowsazure.management.compute.models.PostShutdownAction

to use uppercase enums is breaking the requests to shutdown virtual machines. The enum names should be Stopped, StoppedDeallocated or the toString method overriden.

**Comment by falbrech-hsdg** [comment]
+1, also just ran into this issue. Shows how well this library is tested, as the one and only parameter of the shutdown operation is not even tested...

**Comment by ljhljh235** [comment]
Thanks for pointing this out guys.

We updated all the tests to use the upper case names during refactoring and did not consider how "breaking" it would be. That's a mistake and will be fixed this coming week.

**Comment by jianghaolu** [comment]
This is fixed in the latest release.
