### ISSUE TITLE
[BUG] Log4j.properties file in root jar file - azure-servicebus

### ISSUE THREAD

**Issue by spylightadmin** [Azure/azure-sdk-for-java#5220]
**Describe the bug**
Log4j.properties file exists in the root jar file

**To Reproduce**
Include the jar file in an existing project

**Expected behavior**
No file should exist

**Setup (please complete the following information):**
 - Version of the Library used: azure-servicebus:3.0.0

**Additional context**
When adding a dependency to the servicebus jar our full project logging configuration is broken because this log4j.properties, we can not just remove this file or we should create a new uber jar with an exclude filter (Maven Shade Plugin)

**Comment by jfggdl** [comment]
@spylightadmin, thank you for reporting this issue. We will review our jar package and mitigate any packaging problems.

**Comment by jfggdl** [comment]
@spylightadmin, Thanks for reporting this bug. We acknowledge that we have a packaging problem. We are working to release a new version that will solve your problem.

**Comment by nemakam** [comment]
Fixed in #5463.
Also, follow up issue - #5307
