### ISSUE TITLE
Add use of PagedFlux and PagedIterable to non-paged listing APIs (blob-package)

### ISSUE THREAD

**Issue by jaschrep-msft** [Azure/azure-sdk-for-java#5226]
It is a java guideline that any listing API uses PagedIterable or PagedFlux as its return type, even if the listing operation is guaranteed to only need one call.

When the initial conversion work to use these two classes was done, there was misinformation saying that was not the case.

So now there are several APIs that return T or Mono<T> where T is some class with a list and some other info in it (e.g. BlockList)

So we'd go from Mono<BlockList> to PagedFlux<BlockItem> (or whatever the actual type inside the list is)

Or Mono<Response<BlockList>> to PagedFlux<BlockItem>

**Comment by JonathanGiles** [comment]
There does not appear to be a good solution to going from Mono<BlockList> into a PagedFlux, due to the fact BlockList (and other similar types) often represent multiple lists or contain additional useful information. Flattening the result into a single PagedFlux might not be intuitive either. This might be a place where storage does not follow spec.

**Comment by vhvb1989** [comment]
Current BlockList and PageList contains 2 types of lists that we don't want to merge as one only PagedFlux

BlockList -> committedBlocks / uncommittedBlocks
PageList -> pageRange / clearRange

From teams conversation:
Anu:
> If we merge "committed" and "un-committed" Blocks to a single List,  when user iterate through this merged List how can he distinguish between these two types? it seems same type "Block" is used to represent both and there is no flag in this type. Here over wire service enables user to differentiate two set by giving them as two list, but SDK user loses this info due to the merge. PagedFlux/PagedList is for a stream of values of same shape, I wonder it is the right type to represents this method return value.

Srikanta:
> there are two scenarios:
> One type (BlockList) contains two lists with same type but functionally contains different data. Can be merged technically but shouldn't be as it's not functionally the same content and user can't differentiate.
> Other type (PageList) contains two lists with different types. Cannot be merged into  a single stream (Flux) as the types are different.

> So, neither of these should be merged into a single flux

**Comment by vhvb1989** [comment]
@jaschrep-msft are you OK with closing this issue as we are keeping current approach?
