### ISSUE TITLE
Better Values for Log Level

### ISSUE THREAD

**Issue by alzimmermsft** [Azure/azure-sdk-for-java#5237]
Currently, to set the logging level a customer needs to set AZURE_LOG_LEVEL to a numeric value that correlates to the logging level, for ease of understanding we should also allow string values to be used such as `WARN` or `WARNING` (possible multiple per log level). This will help make it easier to understand what configuration level is being used without having to jump into the `ClientLogger`.

**Comment by sima-zhu** [comment]
It is been merged into master. Closed the issue.
