### ISSUE TITLE
Storage Progress Reporting

### ISSUE THREAD

**Issue by rickle-msft** [Azure/azure-sdk-for-java#5243]
Code looks to be already ported from v11. It needs to be tied into bulk upload/download methods

The only work should be in any methods with parallel transfer (upload from file, download to file, and buffered upload).
	
No work needs to be done for the basic upload/download methods
	
ParallelTransferOptions should accept an IProgressReporter. 
In each of the necessary methods, the work should be to instantiate a mutex and an atomicLong before the parallel operation begins and then on each data stream (e.g. a chunk from a file), call ProgressReporter.addParallelProgressReporting and pass in these two values along with the IProgressReporter.
	
Most of this is already done in buffered upload but is commented out. 
Examples of what this should look like for the file transfer operations can be found in the TransferManager type in v11 (microsoft.azure package)
	
Tests for this should also exist in the v11 test suite and should be able to be translated pretty directly to track 2 (v12)

**Comment by kurtzeborn** [comment]
@vhvb1989, talk to @alzimmermsft if you have questions about how to get started on this one.
