### ISSUE TITLE
com.microsoft.windowsazure.exception.ServiceException: null

### ISSUE THREAD

**Issue by paksv** [Azure/azure-sdk-for-java#525]
at com.microsoft.windowsazure.exception.ServiceException.createFromJson(ServiceException.java:296)
	at com.microsoft.azure.management.compute.VirtualMachineOperationsImpl.listAll(VirtualMachineOperationsImpl.java:7278)
	at com.AzureTestNew.listVMs(AzureTestNew.java:56)

In fact, httpResponse.getStatusLine().getStatusCode() returns 403 (2 lines above createFromJson). 

The response is actually an xml, not Json:
```xml
<Error xmlns="http://schemas.microsoft.com/windowsazure" xmlns:i="http://www.w3.org/2001/XMLSchema-instance"><Code>ForbiddenError</Code><Message>The server failed to authenticate the request. Verify that the certificate is valid and is associated with this subscription.</Message></Error>
```

**Comment by paksv** [comment]
In addition, IOException thrown is completely ignored leaving no chance to know what is happening here without having a source code or Intellij Idea :)

**Comment by devigned** [comment]
Looks like you are mixing Azure Resource Management (v2 apis) and Service Management (v1 apis) in the above stack. Service Management returns xml while ARM returns json. Could you provide the code sample (including the imports) and we can get this sorted out?

**Comment by mayurid** [comment]
@paksv : Since we haven't heard back from you we hope that the issue is resolved for you.
Please reopen if you still see this.

**Comment by adi06** [comment]
Hi

I have cloned the latest repo and tried to run the below sample file at azure-sample module
com.microsoft.azure.samples.compute.CreateVMExample

The configuration for ResourceManagementClient is the below

ManagementConfiguration.configure(new URI(baseUri), subscriptionId, keyStoreLocation, keyStorePassword, KeyStoreType.jks);

I am getting 403 as response code..

Regards
Aditya
