### ISSUE TITLE
Improve Netty connection pooling support

### ISSUE THREAD

**Issue by JonathanGiles** [Azure/azure-sdk-for-java#5265]
1) Change the default connection pooling configuration so that we don’t allow for an unbounded number of connections.
2) Improve our recently-added Netty builder APIs to let users configure their connection pooling, to either set fixed, elastic, or custom connection pools.

**Comment by JonathanGiles** [comment]
If I recall correctly, this issue can be closed. @jianghaolu Please do so if there is nothing that needs o be done here.

**Comment by anuchandy** [comment]
This is done in the PR https://github.com/Azure/azure-sdk-for-java/pull/5836, the builder accept `reactor.netty.resources.ConnectionProvider` that can be fixed/elastic/newConnection or a custom provider.
