### ISSUE TITLE
Consider moving EventProcessor to the root namespace

### ISSUE THREAD

**Issue by AlexGhiondea** [Azure/azure-sdk-for-java#5271]
The EventProcessor is the main way for people to interact with Event Hubs. It should be easy to find and putting it in the root namespace might help with that.

**Comment by hemanttanwar** [comment]
Spoke to @jsquire , @AlexGhiondea  and @srnagar  : This is not an issue any more. In past this class was part of separate module and was difficult to find but as of  today this class is in right module and package.
Thus closing it.
