### ISSUE TITLE
[BUG] PageBlobUploadPagesFromURLHeaders missing field encryptionKeySha256

### ISSUE THREAD

**Issue by jaschrep-msft** [Azure/azure-sdk-for-java#5286]
Auto-generated class `azure.storage.blob.models.PageBlobUploadPagesFromURLHeaders` has no field/getter `encryptionKeySha256` for header `x-ms-encryption-key-sha256`, even though the service returns the header when using a customer provided key.

Access to this in the generated class is necessary, as `azure.storage.blob.models.PageBlobItem`, a handcrafted model class, exposes this field, and sets it on most of its constructors. But since this generated class doesn't expose this, the handcrafted class can't expose it in this particular method call.

**Comment by jaschrep-msft** [comment]
In a similar vein, `azure.storage.blob.models.AppendBlobAppendBlockFromUrlHeaders` contains the `encryptionKeySha256` but NOT the `isRequestServerEncrypted` field.

**Comment by kurtzeborn** [comment]
@alzimmermsft, you were thinking this was a swagger issue.
