### ISSUE TITLE
CPK source headers not supported for Copy Blob

### ISSUE THREAD

**Issue by jaschrep-msft** [Azure/azure-sdk-for-java#5289]

**Comment by kurtzeborn** [comment]
@alzimmermsft, you were thinking this is a swagger issue.

**Comment by alzimmermsft** [comment]
Should this be a service request as the Copy Blob documentation doesn't state that it takes CPK headers.

https://docs.microsoft.com/en-us/rest/api/storageservices/copy-blob

**Comment by alzimmermsft** [comment]
Closing this issue as the Copy Blob REST APIs don't take CPK and we internalize CPK through our builders so it isn't an issue that these APIs don't take it.
