### ISSUE TITLE
[BUG] Core Playback does not parse/record body for GetPermission. 

### ISSUE THREAD

**Issue by gapra-msft** [Azure/azure-sdk-for-java#5298]
The GetPermission Storage API https://docs.microsoft.com/en-us/rest/api/storageservices/get-permission does not return a content-type header indicating JSON so the permission does not get deserialized and stored in playback files.

**Comment by sima-zhu** [comment]
The change has pushed into master. Closed the issue. Please feel free to reopen if trigger any other issues.
