### ISSUE TITLE
Evaluate the need for VoidResponse

### ISSUE THREAD

**Issue by srnagar** [Azure/azure-sdk-for-java#5300]
Do we need a special type for `VoidResponse` instead of just using `Response<Void>` as return type in public APIs?

**Comment by JonathanGiles** [comment]
We should remove `VoidResponse` and change all API to instead return `Response<Void>`.

**Comment by samvaity** [comment]
Duplicate here - https://github.com/Azure/azure-sdk-for-java/issues/5465
