### ISSUE TITLE
Investigate Connection Pool Reuse

### ISSUE THREAD

**Issue by alzimmermsft** [Azure/azure-sdk-for-java#5305]
When using Fiddler it appears there is a new CONNECT tunneling request made each time a new request is sent. This adds performance overhead which should be investigated in fixing/improving.

**Comment by alzimmermsft** [comment]
@jianghaolu Would this have been resolved by updated to Reactor Netty 0.9.0?

**Comment by jianghaolu** [comment]
This is by design - this is how HTTPS traffic gets through a proxy: https://en.wikipedia.org/wiki/HTTP_tunnel

**Comment by jianghaolu** [comment]
About reusing though, reactor-netty 0.9.0 does change the default pool to a fixed size.

**Comment by alzimmermsft** [comment]
Closing as this is expected behavior.
