### ISSUE TITLE
[BUG] Service Bus 3.0.0 transitively depends on log4j, breaks client logging

### ISSUE THREAD

**Issue by jordanjennings** [Azure/azure-sdk-for-java#5307]
**Describe the bug**
The service bus 3.0.0 library has a compile time dependency on slf4j-log4j, which breaks client logging.

From https://search.maven.org/artifact/com.microsoft.azure/azure-servicebus/3.0.0/jar:
```
    <dependency>
      <groupId>org.slf4j</groupId>
      <artifactId>slf4j-log4j12</artifactId>
    </dependency>
```

***Exception or Stack Trace***
Error log at startup:
```
SLF4J: Class path contains multiple SLF4J bindings.
SLF4J: Found binding in [jar:file:/Users/jjennings/.gradle/caches/modules-2/files-2.1/org.slf4j/slf4j-log4j12/1.7.0/8837262ff98225a81608b8c11aea642d9449228b/slf4j-log4j12-1.7.0.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: Found binding in [jar:file:/Users/jjennings/.gradle/caches/modules-2/files-2.1/ch.qos.logback/logback-classic/1.2.3/7c4f3c474fb2c041d8028740440937705ebb473a/logback-classic-1.2.3.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: See http://www.slf4j.org/codes.html#multiple_bindings for an explanation.
SLF4J: Actual binding is of type [org.slf4j.impl.Log4jLoggerFactory]
```

**To Reproduce**
Use service bus 3.0.0 with any logging implementation other than log4j (like logback).

***Code Snippet***
No code, only dependencies

**Expected behavior**
Library does not transitively depend on a logging implementation, only the SLF4J API.

**Screenshots**
N/A

**Setup (please complete the following information):**
 - OS: macOS
 - IDE : IntelliJ
 - Version of the Library used: 3.0.0

**Additional context**
This is closely related to #5220 , although it's a separate fix needed.

**Information Checklist**
Kindly make sure that you have added all the following information above and checkoff the required fields otherwise we will treat the issuer as an incomplete report
- [x] Bug Description Added
- [x] Repro Steps Added
- [x] Setup information Added

**Comment by jordanjennings** [comment]
This issue still has not been fixed as of 3.1.1, even though the related #5220 appears to have been fixed in 3.1.0.

**Comment by nemakam** [comment]
@jordanjennings , the latest package https://mvnrepository.com/artifact/com.microsoft.azure/azure-servicebus/3.1.1 doesn't have the log4j file. Could you check and confirm again?

**Comment by lilyjma** [comment]
@jordanjennings--Hi Jordan, I was wondering if you'd be willing to share with us your experience working with this library. We're committed to improving our SDK, GitHub support process, and documentation. Your feedback would be extremely helpful to us, so please let me know if we can hop on a quick call to discuss it. Thanks!

**Comment by jordanjennings** [comment]
@lilyjma happy to provide feedback to help, let me know your contact info and I'll reach out to coordinate timing

**Comment by lilyjma** [comment]
Thanks so much @jordanjennings! My email is jiayma@microsoft.com.
