### ISSUE TITLE
Porting guides for blob

### ISSUE THREAD

**Issue by sima-zhu** [Azure/azure-sdk-for-java#5313]

**Comment by joshfree** [comment]
Let's try to finish the porting guides for the December update.

**Comment by joshfree** [comment]
@sima-zhu can you please give an update on the 3 porting guides?  Are these on track for Friday?

**Comment by sima-zhu** [comment]
The initial version has checked in. 
We can close the issue for now. Any more enhancement work is handled by storage team.
