### ISSUE TITLE
Investigate OOM for maven builds

### ISSUE THREAD

**Issue by srnagar** [Azure/azure-sdk-for-java#5324]
Maven CI pipeline builds are failing due to OOM errors. Investigate the root cause of this issue.

https://dev.azure.com/azure-sdk/internal/_build/results?buildId=106707&view=logs&s=6884a131-87da-5381-61f3-d7acc3b91d76&j=b78b2312-96d2-579e-3173-f597ed388512

**Comment by JonathanGiles** [comment]
@srnagar Is this fully resolved now?

**Comment by srnagar** [comment]
After Mitch increased the [maven heap size](https://github.com/Azure/azure-sdk-for-java/commit/b9369679a44b9e8a98326a2d26fb116acec834fd#diff-5ba8efd1ae435b46b881f4e22bc977e4), we haven't noticed this issue. I guess that was the fix. Will close this issue.
