### ISSUE TITLE
Release Event Hubs Track 2 Library Preview 4 for Java

### ISSUE THREAD

**Issue by ramya-rao-a** [Azure/azure-sdk-for-java#5330]
For general summary & goal, please see: [Release Event Hub Track 2 Library (#442)](https://github.com/Azure/azure-sdk/issues/442) 

The work items linked to this issue herein represent the tasks needed to produce the 4th preview for the "track two" Event Hubs client library.

**Comment by conniey** [comment]
An existing epic exists already. https://github.com/Azure/azure-sdk-for-java/issues/5223
