### ISSUE TITLE
Client navigation story

### ISSUE THREAD

**Issue by jaschrep-msft** [Azure/azure-sdk-for-java#5333]
**Scenario:**
once you have a client to a resource with its fully built pipeline (containing credentials and any other custom work), how do you "navigate" the resources to get a client to a new resource without having to reconfigure the pipeline as you wanted it?

**Current considered approach:**
All clients implement a `Client` interface, with basic methods like `getPipeline` and `getURL` that are already implemented on each client. Builders can be initialized with a `Client` to contain the custom pipeline and url. All that needs to be done is to set the new resource path (e.g. set a new blob name, keeping the container name from previous client) and build.

**Comment by kurtzeborn** [comment]
@alzimmermsft and I chatted about this and we wanted to get @JonathanGiles's thoughts on this.
