### ISSUE TITLE
Update Contributing.md file with build instructions

### ISSUE THREAD

**Issue by weshaggard** [Azure/azure-sdk-for-java#5343]
Looks like we are using the wiki for building instructions can we instead move those to the contributing.md in the repo. That will make it more consistent with other repos and more importantly will enable the instructions to version with the source so we have a hope of being able to build the repo at various points in source history. 

@JonathanGiles @srnagar

cc @JimSuplizio @mitchdenny

**Comment by joshfree** [comment]
This has been resolved with https://github.com/Azure/azure-sdk-for-java/blob/master/CONTRIBUTING.md#building-and-testing
