### ISSUE TITLE
Error getting ARM deployment paramters

### ISSUE THREAD

**Issue by yaronyagoda** [Azure/azure-sdk-for-java#535]
When you use the Java SDK to get the deployment parameters they come out as null even though using the Rest API directly I can see them.
I started debugging the code and I got to:
com.microsoft.azure.management.resources.DeploymentOperationsImpl

Line 1009

JsonNode parametersValue = propertiesValue.get("parameters");
                        if (parametersValue != null && parametersValue instanceof NullNode == false) {
                            String parametersInstance;
                            parametersInstance = parametersValue.getTextValue();
                            propertiesInstance.setParameters(parametersInstance);
                        }

textValue is null since the value is not a string but a Json Object
Need to fix that
Thanks and I would love to help
Yaron

**Comment by devigned** [comment]
@yaronyagoda thank you. If you are interested in helping, we are working on the next rev of the code generator for these libraries over in the [autorest repo](http://github.com/azure/autorest). You can use the dev branch to generate this portion of the Azure Java SDK via [Azure Swagger Specs](https://github.com/Azure/azure-rest-api-specs/blob/master/arm-resources/resources/2014-04-01-preview/swagger/resources.json). 

This work is still in progress and we haven't begun generating this Repo with autorest, but we should start soon (we still have some polish to put on the generator). If you want to see some changes in the generator, we'd love the feedback or the pull requests.

**Comment by jianghaolu** [comment]
This should be fixed in 1.0.0-beta1 & 1.0.0-beta2. Please verify.
