### ISSUE TITLE
Update build pipeline badge 

### ISSUE THREAD

**Issue by danieljurek** [Azure/azure-sdk-for-java#5351]
Need to update the URL so this points to a more recent source of status data: 

![image.png](https://images.zenhubusercontent.com/5cae2419b80bfc09f2e974f5/1be01b75-76d6-49b4-b007-6be8149e213b)

**Comment by kurtzeborn** [comment]
What does it point to now?

**Comment by danieljurek** [comment]
Today it points to https://dev.azure.com/azure-sdk/public/_build?definitionId=17

With unified pipelines (where we don't have a single client build) it might make sense to use multiple badges

| Service | Status | 
| ------- | -------  |
| App Config | [![Build Status](https://dev.azure.com/azure-sdk/internal/_apis/build/status/java/java%20-%20appconfiguration?branchName=master)](https://dev.azure.com/azure-sdk/internal/_build/latest?definitionId=704&branchName=master) |
| Batch | [![Build Status](https://dev.azure.com/azure-sdk/internal/_apis/build/status/java/java%20-%20batch?branchName=master)](https://dev.azure.com/azure-sdk/internal/_build/latest?definitionId=732&branchName=master) |

Since the pipeline is internal, however, the results will only be viewable to those with permissions. Clicking on the badge today will take an unauthenticated user to an authentication experience.

**Comment by JimSuplizio** [comment]
@danieljurek @kurtzeborn @weshaggard @joshfree 
I'm closing this out, there's really nothing to do here. Wes replace this pipeline badge with packages back as part of [PR 6672](https://github.com/Azure/azure-sdk-for-java/pull/6672) which links to the [latest releases](https://azure.github.io/azure-sdk/releases/latest/java.html) page. NET, JS and pyton have had similar changes but the only language with a pipelines badge is Python which is core only and not representative.
