### ISSUE TITLE
[Arch] Unify Async Exception and Error Channels - Methods that return a Publisher (Mono or Flux) should not throw exceptions

### ISSUE THREAD

**Issue by srnagar** [Azure/azure-sdk-for-java#5360]
Async APIs that return Mono or Flux return errors as well as throw exceptions. Ideally, we should only use the `Publisher`'s error channel to return errors to the users. So, users will only have to handle errors in a reactive idiomatic way. Currently, user code will have to handle exceptions as well as error channels.

For e.g. in KeyAsyncClient, we have this method:

```java
public Mono<Key> createRsaKey(RsaKeyCreateOptions rsaKeyCreateOptions) {
        return createRsaKeyWithResponse(rsaKeyCreateOptions).flatMap(FluxUtil::toMono);
}
```

Users will have to do something like this to write defensive code for calling this method:

```java
try {
   keyAsyncClient.createRsaKey(null /* for demo */)
   .subscribe(
         this::handleResponse,
         this::handleError);
} catch (Exception ex) {
   handleError(ex);
}
```

**Comment by joshfree** [comment]
@srnagar can you please drive this to resolution for Preview 5?

**Comment by srnagar** [comment]
PR for `ConfigurationAsyncClient` is out - https://github.com/Azure/azure-sdk-for-java/pull/5837

**Comment by srnagar** [comment]
PR for KV clients - https://github.com/Azure/azure-sdk-for-java/pull/5858
PR for Certificates client - https://github.com/Azure/azure-sdk-for-java/pull/5847

**Comment by srnagar** [comment]
PR for storage clients - https://github.com/Azure/azure-sdk-for-java/pull/5870
