### ISSUE TITLE
[FEATURE REQ][Cosmos]Expose current of Change Feed Processor (isStarted/getStatus)

### ISSUE THREAD

**Issue by christopheranderson** [Azure/azure-sdk-for-java#5361]
We should be able to see whether the ChangeFeedProcessor is started or stopped.

getStatus is most useful. Sugar method for isStarted might be convenient.

**Comment by kushagraThapar** [comment]
@milismsft Do we have a plan for this ?

**Comment by milismsft** [comment]
@kushagraThapar It should be fairly easy to expose such a method like "isStarted()" since we already have a property that keeps track of the overall state.

**Comment by kushagraThapar** [comment]
> @kushagraThapar It should be fairly easy to expose such a method like "isStarted()" since we already have a property that keeps track of the overall state.

Do we plan to do this in this upcoming 3.4.1 release ?

**Comment by kushagraThapar** [comment]
@milismsft , looks like we lost the conversation on this one ?
Can you please update the timeline for this ?
