### ISSUE TITLE
Re-parenting of cognitive services parent POM to track 1 parent inadvertently caused the groupId to change from com.microsoft.azure.cognitiveservices to com.azure

### ISSUE THREAD

**Issue by JimSuplizio** [Azure/azure-sdk-for-java#5364]
Re-parenting of cognitive services parent POM to track 1 parent inadvertently caused the groupId to change from com.microsoft.azure.cognitiveservices to com.azure. The original PR that changed this https://github.com/Azure/azure-sdk-for-java/pull/5202. I believe this work is going to be adding groupIds to the individual POM files to set the group instead of allowing them to inherit the parent's groupId. The complete list of POM files can be found in the original PR link.

**Comment by weshaggard** [comment]
Looking at some packaging stuff it seems like this is still an issue. @mitchdenny Do you know if we explicitly decided to not move these packages back to their original groupId? As opposed to com.azure?

**Comment by mitchdenny** [comment]
No I think it was just a mistake. If we want to override then we should just just set them back to ```com.microsoft.azure``` in the child packages.

**Comment by weshaggard** [comment]
Yes I suggest that we reset these back.

**Comment by mitchdenny** [comment]
Was fixed here: https://github.com/Azure/azure-sdk-for-java/pull/5366

**Comment by weshaggard** [comment]
Cool yeah I did a little exercise to double check and I didn't find any other packages with the wrong groupid.
