### ISSUE TITLE
Missing Locations listing API for ARM

### ISSUE THREAD

**Issue by martinsawicki** [Azure/azure-sdk-for-java#537]
Two problems:
1) there currently is no API for listing the supported Azure locations (for a given subscription), using the format that is accepted as input params to the various "create" functions (i.e. "westus" instead of "West US"
2) since those functions require these non-human friendly versions of the location names ("westus" instead of "West US") there should also be a way to list the user-friendly names, and map them to the supported values. Or, simply have the "create" APIs accept the human-readable location names too

**Comment by jianghaolu** [comment]
- Is there existing APIs that return locations on a subscription basis?
- Same for human friendly versions of location names. However, if there isn't one for this, we might be able to add this in the utilities package.

**Comment by devigned** [comment]
@martinsawicki 
1. ARM team is aware and adding these updates to their swagger documents. When we gen the next rev of these libs, the api should be there.
2. That would be a great pull request.

**Comment by jianghaolu** [comment]
Addressed in 1.0.0-beta2.
