### ISSUE TITLE
com.azure.storage.blob.BlobClient.download(OutputStream stream) returns exception java.lang.UnsupportedOperationException

### ISSUE THREAD

**Issue by jaschrep-msft** [Azure/azure-sdk-for-java#5386]

**Comment by jaschrep-msft** [comment]
This bug was filed from an ICM. This is a bug on our side and will be fixed for GA.

**Comment by alzimmermsft** [comment]
This happens when `ByteBuffer` streamed from the underlying `Flux` has a null `hb`, which is non-null only for heap buffers.

**Comment by alzimmermsft** [comment]
@vhvb1989 Role this into your PR that is adding additional tests.
