### ISSUE TITLE
[QUERY] ServiceBus - Transactions

### ISSUE THREAD

**Issue by esciullo** [Azure/azure-sdk-for-java#5404]
**Query/Question**
Are Transactions supported using Java sdk ?
I find example only for C# sdk https://github.com/Azure/azure-service-bus/blob/master/samples/DotNet/Microsoft.ServiceBus.Messaging/AtomicTransactions/readme.md

***Why is this not a Bug or a feature Request?***
Because i'm not sure if it is a missing feature.

**Setup (please complete the following information if applicable):**
 - OS: Windows10
 - IDE : Eclipse
 - Version of the Library used
```xml
<groupId>com.microsoft.azure</groupId>
<artifactId>azure-servicebus</artifactId>
<version>1.2.8</version>
```

**Comment by axisc** [comment]
@esciullo 

Thanks for raising this. We'll add a proper example to this soon.

Here are some resources to unblock you in the meantime.

[TransactionContext](https://github.com/Azure/azure-sdk-for-java/blob/573a77c3cf904738e305ac9ba4926159b9b5b940/sdk/servicebus/microsoft-azure-servicebus/src/main/java/com/microsoft/azure/servicebus/TransactionContext.java) class in the Java SDK.

[Queue Tests](https://github.com/Azure/azure-sdk-for-java/blob/573a77c3cf904738e305ac9ba4926159b9b5b940/sdk/servicebus/microsoft-azure-servicebus/src/test/java/com/microsoft/azure/servicebus/QueueSendReceiveTests.java#L38) leveraging the the Transaction Context.

Let us know if you have questions relating to this documentation.

**Comment by esciullo** [comment]
Thanks @axisc, I really appreciate it.

**Comment by jfggdl** [comment]
@esciullo, Thanks for reporting this issue. Please let us know if you have additional questions and we can reopen this issue.
