### ISSUE TITLE
Investigate Reactor's Exceptions.unwrap

### ISSUE THREAD

**Issue by alzimmermsft** [Azure/azure-sdk-for-java#5408]
In many places we bubble-up exceptions through Reactor using `Exceptions.propagate`, Reactor offers [Exceptions.unwrap](https://projectreactor.io/docs/core/release/api/reactor/core/Exceptions.html#unwrap-java.lang.Throwable-) which should unwrap the exceptions bubbled up through the stream to what was thrown.

This could help us remove all the exception stack trace information that is mostly/entirely Reactor and help make it easier to debug issues that happen.

**Comment by srnagar** [comment]
@alzimmermsft Ideally, Exceptions.unwrap() should be called by user code when handling exceptions as that's where it's most useful. Doing it within the SDK might not be as useful because one client library might call another client library which ends up wrapping the exception again.

Thoughts?

**Comment by alzimmermsft** [comment]
> 
> 
> @alzimmermsft Ideally, Exceptions.unwrap() should be called by user code when handling exceptions as that's where it's most useful. Doing it within the SDK might not be as useful because one client library might call another client library which ends up wrapping the exception again.
> 
> Thoughts?

Makes sense to me, no need to unwrap the exception to make logging cleaner within the SDK only to have Reactor to re-wrap it to return it to the user. Instead we should add this into general troubleshooting documentation on ways to extract a root cause from the bubbled up exception.
