### ISSUE TITLE
Investigate a Better Return Type for Blob Download

### ISSUE THREAD

**Issue by alzimmermsft** [Azure/azure-sdk-for-java#5409]
Currently, the download method returns `Mono<Flux<ByteBuffer>>` to handle allowing the response to return once the headers and initial portion of the download stream returns and to delay reading of the body stream until requested. While the return type is technically correct it is daunting for someone newer to reactive coding and we should simplify this into a class that better handles this complexity in its internal implementation.

An option for this is using `DownloadAsyncResponse` (might want to rename it) in the non-maximal and maximal overloads (which partially goes against the API pattern).

**Comment by JonathanGiles** [comment]
Any update on this? Want to arrange a meeting to discuss options?

**Comment by sima-zhu** [comment]
https://github.com/Azure/azure-sdk-for-java/pull/5613
