### ISSUE TITLE
Generate Individual Package Documentation in CI Builds - Java

### ISSUE THREAD

**Issue by scbedd** [Azure/azure-sdk-for-java#5423]
### Intent and Context
We currently generate documentation as a single unit holistic `doc site`. We need to extend this capability to generate doc sites at the _per package_ level. 

Eventually, our unified pipelines will publish these artifacts to a blob storage static web hosting container, but first we need to generate them.

Expected output at the end of this: 

1. An additional DevOps `build artifact` that includes a static site for _each package generated in the current CI_. 
2. For the generated html, the readme of the source package _should be the landing page_. 
3. Any "relative links" within the readme should be updated so that they function properly when rendered on `github.io`

The methodology driving this will be unique per language, and I leave it up to the implementor how we make it happen.

#### Example 
 [Java core CI](https://dev.azure.com/azure-sdk/public/_build?definitionId=639&_a=summary) should contain a doc site for each of the following packages:

 * `azure-core`
 * `azure-core-amqp`
 * `azure-core-http-netty`
 * `azure-core-http-okhttp`
 * `azure-core-management`
 * `azure-core-test`

**Comment by JimSuplizio** [comment]
I'm going to close this out. Work was done to add the readme to the landing page and update the doc index. The PRs for those were
https://github.com/Azure/azure-sdk-for-java/pull/6006
https://github.com/Azure/azure-sdk-for-java/pull/6144
There were other tooling changes submitted by others in other PRs (some work was a combined effort that spanned all 4 languages, not just Java).
