### ISSUE TITLE
Fix special exports for implementation packages in module-info of azure-core 

### ISSUE THREAD

**Issue by srnagar** [Azure/azure-sdk-for-java#5426]
`module-info.java` of azure-core module exports implementation packages to other client libraries. 

Ideally, each client library module should only rely on the public packages that other modules expose. This requires refactoring to properly encapsulate implementation details in azure core from being exposed to outside libraries. 

Fixed by #6080

**Comment by JonathanGiles** [comment]
#6080 is merged, so this issue can be closed.
