### ISSUE TITLE
Set Container default TTL via CosmosSDK v3

### ISSUE THREAD

**Issue by dkroehan** [Azure/azure-sdk-for-java#5445]
In the CosmosSDK v2 it was possible to set the default TimeToLive when creating a new DocumentCollection, by using: _DocumentCollection#setDefaultTimeToLive_

I couldn't find a possibility how to do that with the new CosmosSDK v3.

**Comment by shurd** [comment]
Hi @dkroehan thank you for opening this issue. Looking through the V3 code, it does not look like you can currently set the default TTL when creating a container. Based on the implementation of the [.NET v3 SDK](https://docs.microsoft.com/en-us/azure/cosmos-db/how-to-time-to-live#dotnet-enable-withexpiry), the property would likely be in the "CosmosContainerProperties.java" class. @christopheranderson would know more about this issue.

**Comment by kushagraThapar** [comment]
This API has been exposed in all SDK versions now.
