### ISSUE TITLE
Consumer EventData does not work if system time isn't UTC

### ISSUE THREAD

**Issue by srnagar** [Azure/azure-sdk-for-java#5448]
Link : https://github.com/Azure/azure-sdk-for-net/blob/master/sdk/eventhub/Azure.Messaging.EventHubs/README.md#consume-events-using-an-event-processor

Code snippet:
![image](https://user-images.githubusercontent.com/51379715/65345240-a2856180-db8e-11e9-9a4e-f8c14ed28577.png)

Error Details : Will throw an exception while perform this code.
![image](https://user-images.githubusercontent.com/51379715/65345257-a913d900-db8e-11e9-8417-f1dac4f64b18.png)
Consumes Event data failed while system time is not UTC time, it works if set the system time as UTC.

**Comment by conniey** [comment]
@jsquire This is a .NET issue.

**Comment by jsquire** [comment]
> @jsquire This is a .NET issue.

Yes.  We're tracking it and are reaching out for additional context and repro steps.
