### ISSUE TITLE
Failed to create new container

### ISSUE THREAD

**Issue by LirazRom** [Azure/azure-sdk-for-java#545]
I have followed the instructions in the tutorial and i get exception of authorization

com.microsoft.azure.storage.StorageException: Server failed to authenticate the request. Make sure the value of Authorization header is formed correctly including the signature.

my code is
val storageConnectionString = "DefaultEndpointsProtocol=https;AccountName=liraztest25saccount;AccountKey=AKchMNfHLQJHoVilkDsHY1kXSEEOa8wigEy6N/83ZVQhFNk2TZpwHpQHdxIAr/5E+3JM650gQGAkM64gMzO7UA==;"
    val storageAccount: CloudStorageAccount = CloudStorageAccount.parse(storageConnectionString);
    val blobClient: CloudBlobClient = storageAccount.createCloudBlobClient();
    val container: CloudBlobContainer = blobClient.getContainerReference("imagesvhd");
    container.createIfNotExists()

**Comment by devigned** [comment]
@LirazRom please don't security sensitive items.
