### ISSUE TITLE
azure-core-amqp: Stop exposing implementation classes to Event Hubs

### ISSUE THREAD

**Issue by conniey** [Azure/azure-sdk-for-java#5478]
In modules-info.java, we are exporting proton-j implementation classes. We should remove that and replace it with an abstraction so we can exchange the underlying implementation class without breaking Event Hubs.
```[tasklist]
### Tasks
- [ ] https://github.com/Azure/azure-sdk-for-java/issues/33683
```

**Comment by ramya-rao-a** [comment]
@conniey What is the latest on this? Can we update the milestone here based on whether or not we plan to take this up this semester?
