### ISSUE TITLE
Many empy fields when retrieving PublishProfile (Service Management - WebSites)

### ISSUE THREAD

**Issue by leotilli** [Azure/azure-sdk-for-java#548]
When trying to retrieve Publish Profile information for WebSites, using the Service Management API, many of the fields are not getting populated.

Looking at the getPublishProfile method in WebSiteOperationsImpl, it's calling getAttributeNodeNS with empty quotes as the namespace, but it's not finding anything. The documentation for org.w3c.dom.Element specifies that a null value shouId be used when no namespace is wanted.

[WebSiteOperationsImpl L4481 v0.90](https://github.com/Azure/azure-sdk-for-java/blob/v0.9.0/service-management/azure-svc-mgmt-websites/src/main/java/com/microsoft/windowsazure/management/websites/WebSiteOperationsImpl.java#L4481)

The line mentioned above it's just one example, there are many other invocations with namespace being an empty string instead of null, in the same method.

**Comment by jianghaolu** [comment]
Hi @leotilli @wjobin 
I see you have a fix in the commit, please feel free to send a pull request to `0.9` branch.
As `0.9` version of the library gradually going away, we will only make need-based fixes. There's no plan to search across the board and fix it everywhere.
