### ISSUE TITLE
[BUG] App Configuration live tests fail with 429

### ISSUE THREAD

**Issue by conniey** [Azure/azure-sdk-for-java#5482]
Application Configuration tests fail with 429 consistently.
* Its possible that we are not cleaning up the settings after each test and it is hitting the service many times.
* We could a retry policy to these that takes into account 429.
* Figure out how to hit the service less but cover the same scenarios.

https://dev.azure.com/azure-sdk/internal/_build/results?buildId=116309&view=logs&j=3f0b3bd8-2d88-59b8-ec21-d9a54670d8fb

**Comment by srnagar** [comment]
Is this a release blocker? @conniey and @mssfang

**Comment by conniey** [comment]
@srnagar I think so, we should understand if our Retry policy is not working properly.

**Comment by anuchandy** [comment]
@srnagar wanted to rule out a case here - just check the http header that azConfig is using to communicate `retry-after` delay. The default RetryPolicy in azure-core looks for standard `retry-after-ms` http header, if azconfig uses a different header for this e.g. `x-ms-retry-after-ms` then core ignore it and uses default delay. In such cases client may make ToManyRequests.

**Comment by srnagar** [comment]
@anuchandy The AppConfig response uses the standard `retry-after-ms` header to return the retry delay.

```
DefaultHttpResponse(decodeResult: success, version: HTTP/1.1)
HTTP/1.1 429 Too Many Requests
Server: openresty/1.15.8.1
Date: Fri, 18 Oct 2019 21:50:22 GMT
Content-Type: application/vnd.microsoft.azconfig.kv+json; charset=utf-8
Transfer-Encoding: chunked
Connection: keep-alive
retry-after-ms: 20
x-ms-request-id: 2062dcc1-d49c-4d2b-96a3-3889f54f8bb7
x-ms-client-request-id: 724bd7b6-d1f4-4c61-abad-8be1081e2a07
x-ms-correlation-request-id: 2062dcc1-d49c-4d2b-96a3-3889f54f8bb7
Access-Control-Allow-Origin: *
Access-Control-Allow-Credentials: true
Access-Control-Allow-Methods: GET, PUT, POST, DELETE, PATCH, OPTIONS
Access-Control-Allow-Headers: DNT, X-CustomHeader, Keep-Alive, User-Agent, X-Requested-With, If-Modified-Since, Cache-Control, Content-Type, Authorization, x-ms-client-request-id, x-ms-content-sha256, x-ms-date, host, Accept, Accept-Datetime, Date, If-Match, If-None-Match, Sync-Token, x-ms-return-client-request-id, ETag, Last-Modified, Link, Memento-Datetime, x-ms-retry-after, x-ms-request-id, WWW-Authenticate
Access-Control-Expose-Headers: DNT, X-CustomHeader, Keep-Alive, User-Agent, X-Requested-With, If-Modified-Since, Cache-Control, Content-Type, Authorization, x-ms-client-request-id, x-ms-content-sha256, x-ms-date, host, Accept, Accept-Datetime, Date, If-Match, If-None-Match, Sync-Token, x-ms-return-client-request-id, ETag, Last-Modified, Link, Memento-Datetime, x-ms-retry-after, x-ms-request-id, WWW-Authenticate
Strict-Transport-Security: max-age=15724800; includeSubDomains
```
