### ISSUE TITLE
Parallel Download Options - BREAKING CHANGE

### ISSUE THREAD

**Issue by gapra-msft** [Azure/azure-sdk-for-java#5489]

**Comment by jaschrep-msft** [comment]
API signatures between sync and async are not consistent. One provides a block size and one does not.

I believe both signatures should instead provide a new ParallelDownloadOptions/ParallelUploadOptions type containing the knobs that we wish to expose for tweaking the "from file" operations. Every knob should have a default value.

**Comment by kurtzeborn** [comment]
@gapra-msft, as you implement this, please consult with @seanmcc-msft on how this is done in the .Net library.  If there are idiomatic reasons why parallel upload/download in java should be different, that's fine, but if not, let's be consistent.
