### ISSUE TITLE
Authorization Failure

### ISSUE THREAD

**Issue by vsmart** [Azure/azure-sdk-for-java#550]
Hi, 
I'm trying to authorize my application towards the API using the StorageAccountExample (see https://github.com/Azure/azure-sdk-for-java/blob/master/azure-mgmt-samples/src/main/java/com/microsoft/azure/samples/storage/StorageAccountExample.java#L418) 

I created an application on the Azure Portal and assigned all available permissions for `Windows Azure Service Management API` and `Windows Azure Active Directory`.  

Then I try to use the example code to read / create storage accounts and get this exception: 

```com.microsoft.windowsazure.exception.ServiceException: AuthorizationFailed: The client '<client>' with object id '<client>' does not have authorization to perform action 'Microsoft.Storage/storageAccounts/read' over scope '/subscriptions/<subscription-id>.```

Could someone point me in the right direction - do I need set permissions elsewhere? What could be a possible cause for the exception?

**Comment by devigned** [comment]
Sounds like the account you are using to access doesn't have role based authority to access the resource you are trying to access within that subscription. I would verify the account you are using has the proper permissions in the azure portal.

Go to https://portal.azure.com and navigate to subscriptions. Select your subscription you are using for this example, and ensure the user / app account you are using is in (either individually or as part of a group) the subscription's users blade. If the app / user is not there, please add it and make it a contributor, reader or the permission group you deem fit.

**Comment by vsmart** [comment]
Hi @devigned 

you are totally right - our issue was that we were missing the correct role to read/write. We ended up creating them through the cli and got this to work. Thanks for letting me know where to find these on the UI as well :) 

Thank you!
Franziska

**Comment by devigned** [comment]
Awesome! Glad to hear. Happy coding!
