### ISSUE TITLE
Need help or AuthorizationRules support for Service Bus

### ISSUE THREAD

**Issue by xuantuan58** [Azure/azure-sdk-for-java#551]
Ref: https://github.com/Azure/azure-sdk-for-java/issues/235
Does the latest implementation for Service Bus Queue still left the AuthorizationRules not implemented?
Or someone can help with generating Shared Access Policies (SAP) for Service Bus Queue and Shared Access Signature (SAS) base on SAP?

**Comment by devigned** [comment]
@djrosanova thoughts on this?

**Comment by paullang** [comment]
@jianghaolu do you have an idea when this can add this to the Java SDK?
Or is there a lower level REST API for this that we can access instead?

**Comment by alvadb** [comment]
the service bus client library is not in this repo anymore, so if this is still an issue, it should go there:
https://github.com/azure/azure-service-bus-java
