### ISSUE TITLE
azure-identity requires java.desktop to open browser window

### ISSUE THREAD

**Issue by JonathanGiles** [Azure/azure-sdk-for-java#5510]
It would be much better if we did't need to have a dependency on java.desktop to open a browser window. This won't always necessarily work either - e.g. having this dependency might prevent identity from working on mobile platforms. We should consider having a pluggable system or other approach to not force a java.desktop dependency directly on azure-identity.

**Comment by jianghaolu** [comment]
InteractiveBrowserCredential is only intended to work on desktops. 

For mobile msal4android should have all the UI designed already in their aar. No need to extend this class for mobile platforms.

**Comment by JonathanGiles** [comment]
Right, but the flow-on effect of having `InteractiveBrowserCredential` in azure-identity is that it makes the module heavier for all use cases. Headless servers deployments would need to bring in java.desktop, even though the `InteractiveBrowserCredential` API is not used.

**Comment by jianghaolu** [comment]
`java.awt.Desktop` seems to be built-in in JDK 8. Are you suggesting it's removed in a future JDK release? If so - what's our alternative? We can make it a provided dependency in that case.

**Comment by JonathanGiles** [comment]
My proposal would be to remove the module dependency on java.desktop, and to introduce the following code into azure-identity to open urls:

```java
private static void openUrl(String url) throws IOException {
    Runtime rt = Runtime.getRuntime();

    String os = System.getProperty("os.name").toLowerCase();
    if (os.contains("win")) {
        rt.exec("rundll32 url.dll,FileProtocolHandler " + url);
    } else if (os.contains("mac")) {
        rt.exec("open " + url);
    } else if (os.contains("nix") || os.contains("nux")) {
        rt.exec("xdg-open " + url);
    }
}
```

**Comment by JonathanGiles** [comment]
Be sure to log to client logger if none of the if/else conditional branches works and we fall through to the else.
