### ISSUE TITLE
CosmosClient does not support AutomaticIdGeneration in createDocument as option

### ISSUE THREAD

**Issue by amanganiello90** [Azure/azure-sdk-for-java#5512]
**Query/Question**
Related to [Spring data issue](https://github.com/microsoft/spring-data-cosmosdb/issues/428),
The **CosmosClient** does not allow to set AutomaticIdGeneration option because the [createItem](https://github.com/Azure/azure-sdk-for-java/blob/f62cc68f90f562df4565dc1ee185d4e0567feebc/sdk/cosmos/microsoft-azure-cosmos/src/main/java/com/azure/data/cosmos/CosmosContainer.java#L190) method uses **true** value to disable it, even if the [AsyncDocumentClient](https://github.com/Azure/azure-sdk-for-java/blob/f62cc68f90f562df4565dc1ee185d4e0567feebc/sdk/cosmos/microsoft-azure-cosmos/src/main/java/com/azure/data/cosmos/internal/AsyncDocumentClient.java#L463) has the opportunity to set value.

***Why is this not a Bug or a feature Request?***
It could be a implementation chooice for many reasons, but the server database side allows to autogenerate ID and also the AsyncDocument, the question is WHY give limits to the **CosmosClient** (then also to the **Spring data cosmos**)

**Setup**
 - Version of the Library used: azure-cosmos 3.3.0
 
 **Information Checklist**
- [x] Query Added
- [x] Setup information Added

**Comment by shurd** [comment]
Hi @amanganiello90 thank you for opening this issue. @christopheranderson will be able to help you with this question.

**Comment by kirankumarkolli** [comment]
With auto ID generation, application is not in control/aware of generated ID. Lots of times this lead to ambiguity later and resulted in in-efficient query paths to read the data. 

With new SDK's its an intended API change that's. Application can simply work-around through creating UUID/GUID equivalent and use it.
