### ISSUE TITLE
Change AppendBlob.appendBlock to use OutputStream

### ISSUE THREAD

**Issue by alzimmermsft** [Azure/azure-sdk-for-java#5516]
Data is being written to the service, not read from it so OutputStream is the more correct object.

Centralizing and making more permanent our discussions on when to use OutputStream vs InputStream, possibly supporting overloads for both, in download and upload methods.

Blobs is using OutputStream as a parameter to download the data to and InputStream for the uploading methods. The question is whether these should be inverted, inverting them would make sense as BlobOutputStream is used in upload scenarios and BlobInputStream is used in download scenarios.

Another solution is choosing what we believe is the correct stream type in these methods and adding a ByteBuffer overload as they are agnostic on the data direction.

**Comment by vhvb1989** [comment]
from last @rickle-msft comment, I believe we are not doing this change...

```
I think inverting them actually doesn’t make sense for the exact reason you specify. As it is currently setup, a customer can mix and match their preferred method of data flow with their desired operation. If they want to read data into memory from a blob, they can open an input stream, but if they want data to be directly written to another destination besides memory, they can pass in an output stream to the download. Likewise for upload operations. If we invert the parameters on upload/download, we restrict the customer’s options on how they can get data where they want it by saying they can only use outputstreams on upload and only inputstreams on download. 

As for accepting a byteBuffer, while some apis like java’s files accept byte arrays/buffers, I don’t think that makes sense in this case. It means the customer has to hold all of their data in memory before they can call the api, whereas if we use streams, while there is some buffering in the conversion to flux, etc. it is (hopefully) not the case that everything gets buffered at once. Ideally, buffering should only happen on each read, which means there should be less memory pressure as buffers are released after being sent.  
```

**Comment by vhvb1989** [comment]
@alzimmermsft , do we want to close this issue?

**Comment by alzimmermsft** [comment]
Let's close on the issue for now but keep the code around in case we want to implement this in the future.
