### ISSUE TITLE
Use consistent naming for methods/parameters.

### ISSUE THREAD

**Issue by conniey** [Azure/azure-sdk-for-java#5530]
There are several places where we inconsistently name things. Should update code to be consistent.
* Use `username` instead of `userName`
* Use Http, Url, etc, rather than HTTP, URL, etc
  * Create Checkstyle rule for this.
  * Example is: shouldLogURL -> shouldLogUrl

**Comment by chrischild** [comment]
Can I work on this?

**Comment by conniey** [comment]
@chrischild Yes. :) This is up for grabs.

**Comment by JonathanGiles** [comment]
@chrischild Thanks for offering - we appreciate your eagerness to work with us! :-)

**Comment by chrischild** [comment]
Are there any allowed values? XML, JSON, etc.

Also how deep are you wanting to look? Classes, methods, variables?

**Comment by JonathanGiles** [comment]
I would love to see a CheckStyle rule (along the lines of the others we have in our /eng directory), but I would be inclined to simply blacklist certain words, rather than use any particular heuristic. I would blacklist, e.g. URL, HTTP, etc. We only care about public API - class names, method names, and field names (where public).

**Comment by JonathanGiles** [comment]
It looks like this issue was partially resolved through #5544.

**Comment by chrischild** [comment]
Cheers, I'll take a look.

**Comment by chrischild** [comment]
I'm ready to do a PR but git is behaving oddly. After forking and pulling the repo, git is saying that every single file has been changed. I found a few things online to try and fix it but no luck so far.

**Comment by Tanis-02** [comment]
Do you still need help with this issue?

**Comment by chrischild** [comment]
I've been waiting for a review for 2weeks now. There is a PR that has had a
review but after that I haven't heard anything. Sorry I'd mention who but
I'm on my phone right now.
