### ISSUE TITLE
Native Event Processor Host support

### ISSUE THREAD

**Issue by dcieslak19973** [Azure/azure-sdk-for-java#554]
A Java implementation of: https://msdn.microsoft.com/en-us/library/microsoft.servicebus.messaging.eventprocessorhost(v=azure.95).aspx

**Comment by devigned** [comment]
@djrosanova thoughts?

**Comment by jtaubensee** [comment]
This has been released here: https://github.com/Azure/azure-event-hubs/tree/master/java/azure-eventhubs-eph

**Comment by martinsawicki** [comment]
the service bus client library is not in this repo anymore, so if this is still an issue, it should go there:
https://github.com/azure/azure-service-bus-java
