### ISSUE TITLE
Documentation on how to generate the model classes

### ISSUE THREAD

**Issue by vbossica** [Azure/azure-sdk-for-java#555]
The classes in the models package are generated according to the prominent:

    // Warning: This code was generated by a tool.
    // 
    // Changes to this file may cause incorrect behavior and will be lost if the
    // code is regenerated.

But I couldn't find any documentation describing how to generate these classes.  This would be required for contributing brand new features, not already supported with the current classes.

**Comment by devigned** [comment]
**Bad news:** You are correct. The code that's in the repo right now was generated with a non-public code generator. 

**Good news:** We are nearing completion of our open source java code generator, which you can find [here, in the autorest repo](https://github.com/Azure/autorest/tree/dev/AutoRest/Generators/Java). The entire flow of the code generation process will be open sourced and as transparent as possible going forward.

If you have any input for the new code generator, please contribute via issues or pull requests to the autorest repo.
