### ISSUE TITLE
Management POM files need to update their version of azure-sdk-parent 

### ISSUE THREAD

**Issue by JimSuplizio** [Azure/azure-sdk-for-java#5561]
Right now pom.management.xml and pom.xml (both in the root of the depot) both declare com.azure:azure-sdk-parent as their parents however the version is 1.1.0 and we're currently at 1.4.0.  Unfortunately, this also requires com.microsoft.azure:azure-arm-parent (from pom.management.xml) and com.azure:azure-sdk-all (from pom.xml) to have their versions ticked up as well these versions will cascade through the tree to individual poms.

**Comment by kurtzeborn** [comment]
@yaohaizh, who is the correct person on the Managment Plane team to look into this?

**Comment by yaohaizh** [comment]
Hi @kurtzeborn I'll take the Java management plane issue. You can always assign to me firstly.

**Comment by yaohaizh** [comment]
Close the issue as it was fixed on https://github.com/Azure/azure-sdk-for-java/pull/5879
