### ISSUE TITLE
pom.data.xml needs to update its version of azure-sdk-parent

### ISSUE THREAD

**Issue by JimSuplizio** [Azure/azure-sdk-for-java#5562]
The azure-sdk-parent was updated to 1.5.0 and the version of the azure-sdk-parent is still at 1.3.0. Unfortunately, this will also require the version of azure-sdk-data to also get ticked up which is going to cascade through the poms that it's parenting.

**Comment by joshfree** [comment]
@JimSuplizio is this the issue that you wanted someone from the Java team to pick up?

**Comment by JimSuplizio** [comment]
@joshfree yes please.

**Comment by JimSuplizio** [comment]
This was fixed as part of the [PR to centralize version management for external dependencies](https://github.com/Azure/azure-sdk-for-java/pull/6434)
