### ISSUE TITLE
[Resilience features using Resilience4J for Azure Event Hubs]

### ISSUE THREAD

**Issue by mohanr** [Azure/azure-sdk-for-java#5580]
**Is your feature request related to a problem? Please describe.**
I looked at the previous GA release of Azure Event Hub code and found that the framework has support for internal retry policies. The policies are not too advanced.

**Describe the solution you'd like**

I think Features supported by Resilience4J can be plugged into the SDK. As I understand this
fault-tolerant library's functional paradigm might be different than Azure Event Hub's coding
styles.

**Additional context**
Is the framework going to be designed with a pluggable architecture in mind ? How do I
use Resilience4J with Azure Event Hubs ?

Even though I looked at only the Event Hubs code there may be other places where resilience will be required.

**Comment by JonathanGiles** [comment]
Hi @mohanr, thanks for your enquiry. At present there are no plans to support Resilience4J. If you could identify the ways in which you would like to see integration through a pluggable architecture (or otherwise), I am always very keen to discuss these ideas further!

**Comment by joshfree** [comment]
Closing out this old issue as there's been no follow up since September.  Feel free to reactivate or provide additional comments.  Thanks

**Comment by deepankarmalhan** [comment]
Not OP but we're planning on decorating our call to an Event Hub through `EventHubProducerClient` and `EventHubProducerAsyncClient ` (depending on if we want to make a synchronous or async call). Is there any plans for adding the [circuit breaker functionality](https://resilience4j.readme.io/docs/circuitbreaker) in these producers?
