### ISSUE TITLE
ServiceBus Track2  API Review -EventData

### ISSUE THREAD

**Issue by hemanttanwar** [Azure/azure-sdk-for-java#5584]

**Comment by hemanttanwar** [comment]
Reference Reference https://apiview.azurewebsites.net/Assemblies/Review/5df407a05bd74cd1a485bd46a55600a3

Delete 
 
conniey 
 
Why "EventData"? ServiceBus deserializes AMQP messages into their "IMessage".
 
 
hemanttanwar 
 
I will have servicebus specific Message class. I was waiting that if you made EventData generic class when we port common amqp code from eventhub into coreamqp and as part of that also port EventData. I also do not want to take everything from track1 IMessage. Thus I will create servicebus specific Message class and slowly build it as we add more features over time in track2.

**Comment by conniey** [comment]
Closed in favour of #4506
