### ISSUE TITLE
ServiceBus Track2 AsyncReceiver  receiveDeferredMessage(Iterable<Long>

### ISSUE THREAD

**Issue by hemanttanwar** [Azure/azure-sdk-for-java#5586]
Reference : https://apiview.azurewebsites.net/Assemblies/Review/5df407a05bd74cd1a485bd46a55600a3

JonathanGiles 
What is the use case for a user to call this method? How would they get the Iterable<Long> of sequence numbers to pass into this?

**Comment by conniey** [comment]
Closed in favour of #4506
