### ISSUE TITLE
 Service Bus track2  AsyncReceiver  Duration 

### ISSUE THREAD

**Issue by hemanttanwar** [Azure/azure-sdk-for-java#5587]
Reference : https://apiview.azurewebsites.net/Assemblies/Review/5df407a05bd74cd1a485bd46a55600a3

 public Flux<EventData> receiveMessages(int maxMessageCount, Duration timeout) {}

Jonathan
        
We should consider dropping the Duration here, as it should be achievable using the existing Flux API, but please confirm.

**Comment by conniey** [comment]
Closed in favour of #4506
