### ISSUE TITLE
SB Track 2 - AsyncSender  SenderOptions 

### ISSUE THREAD

**Issue by hemanttanwar** [Azure/azure-sdk-for-java#5589]
Reference : https://apiview.azurewebsites.net/Assemblies/Review/5df407a05bd74cd1a485bd46a55600a3 

conniey 
 
What sort of "SenderOptions" are there?
 
 
hemanttanwar 
 
At present SenderOptions contains RetryOptions and partitionId . As we add more features which provide more metadata for sending, they would go in SenderOptions. It is similar to how JS have designed API.

**Comment by conniey** [comment]
Closed in favour of #4506
