### ISSUE TITLE
SB track2 -  QueueAsyncClient   createReceiver

### ISSUE THREAD

**Issue by hemanttanwar** [Azure/azure-sdk-for-java#5591]
public AsyncReceiver createReceiver(ReceiveMode receiveMode, SessionReceiverOptions sessionReceiverOptions) {}

                
 
 
conniey 
 
SessionReceiverOptions? Why not AsyncReceiverOptions to match the name of this class?

**Comment by conniey** [comment]
Closed in favour of #4506
