### ISSUE TITLE
Review Hand Crafted Model Properties

### ISSUE THREAD

**Issue by alzimmermsft** [Azure/azure-sdk-for-java#5594]
Some properties use the Object based primitive when they are optionally returned by the service, these should be reviewed if we are able to use true primitives.

**Comment by vhvb1989** [comment]
<table style="width: 100%;">
    <tbody>
      <tr>
        <td style="width: 25%;">Class</td>
        <td style="width: 25%;">Property</td>
        <td style="width: 25%;">Summary</td>
        <td style="width: 25%;">Result</td>
      </tr>
      <tr>
        <td style="width: 25%;">BlockBlobItem</td>
        <td style="width: 25%;">isServerEncrypted</td>
        <td style="width: 25%;">populated by `generatedHeaders.isServerEncrypted()` with Boolean. It can hold a null value</td>
        <td style="width: 25%;">Cannot be updated to primitive</td>
      </tr>
      <tr>
        <td style="width: 25%;">BlockBlobItem</td>
        <td style="width: 25%;">isServerEncrypted</td>
        <td style="width: 25%;">populated by `generatedHeaders.isServerEncrypted()` with Boolean. It can hold a null value</td>
        <td style="width: 25%;">Cannot be updated to primitive</td>
      </tr>
    </tbody>
  </table>

**Comment by vhvb1989** [comment]
Reviewed all model´s properties and no changes from `Boolean` to `boolean` are required.

Introducing one side chance for a potencial NPE thou.
