### ISSUE TITLE
SB Track 2 Sender  cancelScheduledMessage 

### ISSUE THREAD

**Issue by hemanttanwar** [Azure/azure-sdk-for-java#5601]
public void cancelScheduledMessage(Iterable<Long> sequenceNumbers) {}
 
conniey 
1 day ago
Why not Long... over Iterable<Long>? creating an Iterable, just to pass here is cumbersome, sometimes. Then the first overload could be removed.

**Comment by conniey** [comment]
Closed in favour of #4506
