### ISSUE TITLE
Investigate getHttpPipeline in Storage Clients

### ISSUE THREAD

**Issue by alzimmermsft** [Azure/azure-sdk-for-java#5603]
Many of the storage clients have `getHttpPipeline` methods that return the pipeline the client is using. Investigate whether this is required in the public API.

**Comment by vhvb1989** [comment]
this is a util method that can be used to create a new client and re-use other client´s pipeline.
It is currently on client base classes

**Comment by alzimmermsft** [comment]
The `getHttpPipeline` method makes it easier to move around the Azure Blob client hierarchy, for now this should be kept until there is an easier way to move the hierarchy.
