### ISSUE TITLE
Update getPageRanges, getPageRangesDiff, and listBlobs to PagedFlux and PagedIterable

### ISSUE THREAD

**Issue by alzimmermsft** [Azure/azure-sdk-for-java#5604]

**Comment by vhvb1989** [comment]
updating `getPageRangesDiffWithResponse`

**Comment by vhvb1989** [comment]
See comment: https://github.com/Azure/azure-sdk-for-java/issues/5226#issuecomment-539201417

@Alan, do we want to close this issue with the same reason as #5226 ?
