### ISSUE TITLE
Use BlobRange and PageRange Consistently in PageClient

### ISSUE THREAD

**Issue by alzimmermsft** [Azure/azure-sdk-for-java#5606]
Some APIs take BlobRange and others take PageRange, we should make these consistent.

**Comment by sima-zhu** [comment]
Based on the checking, only pageBlob is using the pageRange for put range API, which is necessary for the operation.

GetPageRange API accept range without end setup, which means PageRange does not apply in this case, as pageRange must specify the end. Use BlobRange is the right choice. 

There is nothing needs to change for the issue. Close it.
