### ISSUE TITLE
Do not release module azure-core-management  from azure-core

### ISSUE THREAD

**Issue by hemanttanwar** [Azure/azure-sdk-for-java#5640]
Do not release module azure-core-management  from azure-core

Jonathan's comment

 I just want to make sure that management is not released, so if the release pipeline doc is the right place to add that check, that's good with me.

**Comment by hemanttanwar** [comment]
PR:   https://github.com/Azure/azure-sdk-for-java/pull/5641/

**Comment by mitchdenny** [comment]
All good @hemanttanwar  and I have discussed - the linked PR can be merged, and I'll close this issue for now.
