### ISSUE TITLE
Investigate if storage methods taking URL input should change to taking String url input 

### ISSUE THREAD

**Issue by samvaity** [Azure/azure-sdk-for-java#5656]
Currently, both the .NET and Java team are using URL type input for methods like `copyFromUrlWithResponse` and such. 
Investigate if they should be taking  String input instead.

**Comment by conniey** [comment]
FRom our java spec: https://azure.github.io/azure-sdk/java_design.html#java-api-url
>  DO NOT create API that exposes the java.net.URL API. This API is difficult to work with, and more frequently gets in the users way rather than provide any real assistance. Instead, use the String type to represent the URL. When it is necessary to parse this String into a URL, and if it fails to be parsed (throwing a checked MalformedURLException), catch this internally and throw an unchecked IllegalArgumentException instead.

**Comment by alzimmermsft** [comment]
Based on our guidelines the methods that take a URL will be changed to take a String.
