### ISSUE TITLE
Include error message when checking for null using Objects.requireNonNull()

### ISSUE THREAD

**Issue by srnagar** [Azure/azure-sdk-for-java#5657]
When we check for null params using `Objects.requireNonNull(param)`, add an error message to indicate which param is not expected to be null to provide sufficient information to the user to fix the issue. (Not all users have stacktrace logging enabled to know which param cause the NPE)

Sample error:
`Objects.requireNonNull(param, "param cannot be null");`

**Comment by sakshivij** [comment]
Hello, I am new to open source and have been reading about the project for some time now. I feel confident enough and would like to contribute to this project. If any one is not working on it, can I take up the issue?

**Comment by JonathanGiles** [comment]
@sakshivij You are more than welcome to work with us on this improvement - we would love to take your contributions to make our offering better for everyone! Thank you for offering.

**Comment by srnagar** [comment]
@sakshivij Yes, you are welcome to work on this issue. Please feel free to assign this issue to yourself to let others know that you are looking into it!

Thanks for offering to contribute!

**Comment by alexbaeza** [comment]
^ Hi guys, I've gone ahead and created a PR that should improve the errors.
