### ISSUE TITLE
Complete EventHubs AMQP API Review changes for Preview 4

### ISSUE THREAD

**Issue by joshfree** [Azure/azure-sdk-for-java#5661]
See feedback in review @ https://apiview.azurewebsites.net/Assemblies/Review/ea6699da-def6-48a8-a6fd-67623435a698

@hemanttanwar PTAL for Friday

/cc @conniey as FYI

**Comment by hemanttanwar** [comment]
PR : https://github.com/Azure/azure-sdk-for-java/pull/5672

**Comment by hemanttanwar** [comment]
complete
