### ISSUE TITLE
[API review] Auto-gen code for file

### ISSUE THREAD

**Issue by sima-zhu** [Azure/azure-sdk-for-java#5677]
- [x] Rename FileHTTPHeader -> FileHttpHeaders

- [x] In FileHTTPHeader, the API has pattern of getFile*(), however, in FileProperties, it is get*(), do we want to align those? Drop the File from getter and setter?

- [x] Is it necessary to name this as Ntfs to inform the user of the file system format? Can this just be FileAttributes?

- [x] Can user set the last modified time? Isn't it set in the service when the user updates something? `ShareProperties`

- [x] In `Range`, since end is optional, should this return Long instead of long?

- [x] FileProperty is not used anywhere and we have a hand craft FileProperties. Do we still need the FileProperty?

**Comment by rickle-msft** [comment]
- Sounds good
- I think this is a swagger question
- I think this is useful to disambiguate with azure file properties, etc. Otherwise it becomes unclear why we have FileAttributes and FileProperties
- User can't set the LMT on the service. ShareProperties is auto-gen, so we can't fix that as easily.
- I am seeing that FileRange.end() does return Long. Is there a different Range object I'm getting it confused with?
- I'm seeing it is used in FileRef and FileItem?

**Comment by sima-zhu** [comment]
*Regarding: Rename FileHTTPHeader -> FileHttpHeaders"

The model `FileHTTPHeaders` is generated using [x-ms-parameter-grouping](https://github.com/Azure/azure-rest-api-specs/blob/cd1d536ec32f6413d9f660e3fe5c4d62ea6cb3f9/specification/storage/data-plane/Microsoft.FileStorage/preview/2019-02-02/file.json#L4123) attribute in File swagger. 

The word HTTP in FileHttpHeaders acronym and based on Java guideline it should be Http. I don’t see same guideline in other languages, so it’s better to add this in File swagger transformation layer for Java not in public swagger.

Action item for Java SDK is: Identify the transformation syntax to rename x-ms-parameter-grouping attribute.

**Comment by sima-zhu** [comment]
*Regarding: In FileHTTPHeader, the API has pattern of getFile\*(), however, in FileProperties, it is get\*(), do we want to align those? Drop the File from getter and setter?*

As Rick mentioned this is a swagger question, the getter and setter names are generated by prepending get and set in-front of each properties in FileHTTPHeaders model, today in swagger properties of FileHTTPHeaders has the word “file” in it. If we agree on removing the “file” from getters and setters then we need to remove the same word from [swagger](https://github.com/Azure/azure-rest-api-specs/blob/cd1d536ec32f6413d9f660e3fe5c4d62ea6cb3f9/specification/storage/data-plane/Microsoft.FileStorage/preview/2019-02-02/file.json#L4116).

**Comment by sima-zhu** [comment]
*Regarding: In Range, since end is optional, should this return Long instead of long?*

**Comment by sima-zhu** [comment]
*Regarding: FileProperty is not used anywhere and we have a hand craft FileProperties. Do we still need the FileProperty?*

**Comment by anuchandy** [comment]
We're close to closing this issue, the last pending item under discussion is removing/keeping the word `file` in `FileHttpHeader` model. https://github.com/Azure/azure-sdk-for-java/issues/5677#issuecomment-540785823

\\\cc @joshfree

**Comment by anuchandy** [comment]
All work items are addressed, issue can be closed.
