### ISSUE TITLE
Java Repo doesn't follow Azure SDK team directory structure

### ISSUE THREAD

**Issue by joshfree** [Azure/azure-sdk-for-java#5682]
Related https://github.com/Azure/azure-sdk-for-java/issues/2847

The azure/azure-sdk-for-java repo has a large number of management plane SDKs in the top level directory.  These all need to be moved under sdk/ with their supporting build pipeline, auto-pr-bot, and CODEOWNERS entries updated accordingly.

I believe Java is the last repo which is yet to be updated to match this directory structure convention under the azure/azure-sdk-for-* repos.

**Comment by joshfree** [comment]
cc: @weshaggard @kurtzeborn @mitchdenny @JimSuplizio

**Comment by weshaggard** [comment]
FYI this is something that @weidongxu-microsoft is working on in https://github.com/Azure/azure-sdk-for-java/pull/5378

**Comment by weidongxu-microsoft** [comment]
github will respond with 502 Gateway Error if I make a huge PR with all the changes. I will have to break it up to smaller ones, starting from https://github.com/Azure/azure-sdk-for-java/pull/6332

**Comment by weidongxu-microsoft** [comment]
There is "data-plane" inside "eventhubs". So this folder under project root is not cleaned.

**Comment by weidongxu-microsoft** [comment]
PR on SDK and PR on swagger spec is all merged.

PR on autorest.java is yet to merge, but since now mgmt SDK is at same level under project root as before, relativePath of pom.xml no longer need to be changed, so this PR is no longer mandatory for this issue.
