### ISSUE TITLE
[ArchBoard] Update Azure.Core Preview 5 with changes suggested in API Review

### ISSUE THREAD

**Issue by joshfree** [Azure/azure-sdk-for-java#5686]
Tracking Issue for Java team API review feedback updates requested for Azure.Core Preview 4

**Comment by joshfree** [comment]
https://apiview.azurewebsites.net/Assemblies/Review/c23df3d5311a45518b39b74e39d6f295

**Comment by samvaity** [comment]
Closed by https://github.com/Azure/azure-sdk-for-java/pull/5827
