### ISSUE TITLE
[ArchBoard] Update Azure.Identity Preview 5 with changes suggested in API Review

### ISSUE THREAD

**Issue by joshfree** [Azure/azure-sdk-for-java#5687]
Tracking issue for updating Azure.Identity Preview 4 based on Java team API review feedback

/cc @schaabs as FYI

**Comment by hemanttanwar** [comment]
@joshfree  Can we always put a link to API Review ? Making sure that we look at right API review

**Comment by joshfree** [comment]
https://apiview.azurewebsites.net/Assemblies/Review/5c748c0a690e4ddbb3fb344850a4ede0

**Comment by JonathanGiles** [comment]
There is also https://apiview.azurewebsites.net/Assemblies/Review/2a23558e091248958cbfd49125e58cb7

**Comment by hemanttanwar** [comment]
I am going to take of this  API  review as well now. I will create  new PR

**Comment by hemanttanwar** [comment]
PR :  https://github.com/Azure/azure-sdk-for-java/pull/5833

**Comment by jianghaolu** [comment]
PR is merged.
