### ISSUE TITLE
Java SDK 1.0.0: IllegalAccessError exception while ResourceManagementClientImpl initialization

### ISSUE THREAD

**Issue by dtretyakov** [Azure/azure-sdk-for-java#569]
When using ARM sample and sdk 1.0.0 in the runtime I got the following exception:
```java
java.lang.IllegalAccessError
	at com.microsoft.azure.management.resources.ResourceManagementClientImpl.initialize(ResourceManagementClientImpl.java:261)
	at com.microsoft.azure.management.resources.ResourceManagementClientImpl.<init>(ResourceManagementClientImpl.java:233)
	at com.microsoft.azure.management.resources.ResourceManagementClientImpl.<init>(ResourceManagementClientImpl.java:220)
	at ArmTest.testConnection(ArmTest.java:41)
...
```
Here was used binaries from the http://adxsnapshots.azurewebsites.net/ maven repository.

Dependencies were resolved as follows:
![image](https://cloud.githubusercontent.com/assets/1025927/11836366/5c4b4a06-a3eb-11e5-8a71-36ef3dc8778f.png)

What am I doing wrong?

**Comment by jianghaolu** [comment]
@dtretyakov 

For `IllegalAccessError`:
>Normally, this error is caught by the compiler; this error can only occur at run time if the definition of a class has incompatibly changed.

Looks like the line this exception is thrown is inside azure-client-runtime. Can you try clearing the maven cache and rebuilding your library? (which should get a fresh azure-client-runtime package)

**Comment by dtretyakov** [comment]
Got it, in the commit 22311c665d51062e6cb2e7f302dfdd5dc45cd455 it has been fixed.

Before that in the ResourceManagementClientImpl class was following initialization:
``` java
private void initialize() {
    // ...
    this.retrofitBuilder = this.retrofitBuilder.baseUrl(this.baseUri);
}
```
where this.retrofitBuilder declared as final and it causes `IllegalAccessError`.

It was replaced in the 22311c665d51062e6cb2e7f302dfdd5dc45cd455 as follows:
``` java
private void initialize() {
    // ...
    this.retrofitBuilder.baseUrl(baseUri);
}
```

Could you rebuild snapshots with a recent changes?

Affected package in maven repo: com.microsoft.azure:azure-mgmt-resources:1.0.0-SNAPSHOT

**Comment by jianghaolu** [comment]
Yes. The repository will be updated by end of week.
