### ISSUE TITLE
[ArchBoard] Merge auto-generated and exposed models in Storage

### ISSUE THREAD

**Issue by conniey** [Azure/azure-sdk-for-java#5699]
There are autogenerated model classes from the storage REST APIs that have the same name as the models exposed in the client library. These are confusing because customers may not know which ones to use. (They don't live in the .implementation package.)

This also results in a spotbugs issue that we've had to suppressed for a few of them.
> [ERROR] Confusing to have methods com.azure.storage.blob.BlobContainerProperties.getETag() and com.azure.storage.blob.models.BlobContainerProperties.getEtag() [com.azure.storage.blob.BlobContainerProperties] At BlobContainerProperties.java:[line 50] NM_CONFUSING

Example:
* https://github.com/Azure/azure-sdk-for-java/blob/master/sdk/storage/azure-storage-blob/src/main/java/com/azure/storage/blob/BlobContainerProperties.java#L49
* https://github.com/Azure/azure-sdk-for-java/blob/master/sdk/storage/azure-storage-blob/src/main/java/com/azure/storage/blob/models/BlobContainerProperties.java#L100

**Comment by joshfree** [comment]
@sima-zhu can you please drive this to resolution for Preview 5?
