### ISSUE TITLE
Support Deploying Classic Resources Types through Resource Manager API

### ISSUE THREAD

**Issue by zfeng-cliqr** [Azure/azure-sdk-for-java#573]
The SDK should support deploy classic resource types such as ClassicCompute/VirtualMachines and ClassicCompute/DomainNames. 

Through the resource manager api, we can deploy these resources to a specific resource group, which is not possible through the service management API.

**Comment by jianghaolu** [comment]
Hi @zfeng-cliqr 

The way ClassicCompute/VirtualMachines works is based on Generic Resource operations in PowerShell today. In order to do so, you will need to register ClassicCompute Resource Provider and then use the Generic Resource Operations under ResourceManagementClient to get the resource. You can find the method to create one [here](https://github.com/Azure/azure-sdk-for-java/blob/autorest/azure-mgmt-resources/src/main/java/com/microsoft/azure/management/resources/ResourcesOperationsImpl.java#L387). 

AFAIK the ARM compute client does not support Classic VM operations. The behaviors are consistent across languages. @huangpf @markcowl Please correct me if I'm wrong.

Thanks,
Jianghao

**Comment by huangpf** [comment]
Correct. Since the ARM client is generated from ARM specification, unless it's possible to combine it with the 'ClassicCompute' one, I don't think we can have both in the new client.

**Comment by huangpf** [comment]
@zfeng-cliqr Why not having both clients in the project?

**Comment by zfeng-cliqr** [comment]
@jianghaolu Thanks very much for the information.

I understand the compute client does not support ClassicCompute Resource type since the compute client is designed to work for the new Compute Resource Type. 

Through the resource management client, I can create/delete a classicCompute resource, but there are several issues.

1. The definition of ClassicCompute is not clear. Namely the value I should pass through the properties field of a resource. As described here, https://github.com/Azure/azure-resource-manager-schemas/issues/6  If I want to create ClassicCompute Resource, I can guess based on the UI requests but that's unstable and easy to break.

2. Not sure how to Restart/Deallocate VM through resource management client. For UI, operation is done through https://classiccompute-stamp1.ext.azure.com/compute/api/ClassicCompute, which is undocumented. 

@huangpf  Do you mean including both service management client and ARM client?

The problem is that the service management client does not allow me to deploy a vm to a specific resource group. I didn't find a way to deploy a classic vm to a specific resource group through service management client.

Thanks!

**Comment by huangpf** [comment]
First of all, this doesn't look like a officially supported scenario, even though Portal (or some other clients) may build some bridges between the old and new stacks, i.e. ASM vs. ARM. And the ultimate goal is to migrate all old resources over to the new one.

But, I do see that for every ASM service created by the Portal, there will be a side-by-side resource group with the same name being created, e.g.
```
ServiceName             : hpftestvm0104b
...
ExtendedProperties      : {[ResourceGroup, hpftestvm0104b], [ResourceLocation, Central US]}
```

Then from there you can create VMs in the ASM side and query on the ARM side. Does this somehow help your user case?

**Comment by zfeng-cliqr** [comment]
@huangpf  @jianghaolu  Thanks very much for the reply. 

I understand I can query classic virtual machines through the ARM api. And I actually want to manage both new and classic VMs through the ARM api since the classic api is using different authentication method (cannot be authenticated through tenant id, client id and client key).

But I found that I can authenticate using the token I get from ARM api to access  https://classiccompute-stamp1.ext.azure.com, to perform restart, stop, start of classic virtual machines. 

So two questions:

1. I understand this is undocumented. But will this be allowed and will this be supported in the future?

2. If not, what is the suggested way to manage classic types of VMs ?  The old api is using either keystore file, or authenticated through login.windows.net manually then redirect back. Which are not the same as the ARM authentication method. 
    What will be the solution if I don't want to maintain two sets of authentication credentials?

**Comment by huangpf** [comment]
+@sauryadas for triage.

**Comment by huangpf** [comment]
@jianghaolu Could you please help assign the issue to our PM @sauryadas for further triage? Thanks.

**Comment by jianghaolu** [comment]
Hi @huangpf  We are not using TFS any more. Tracking the issues here is fine for me.

**Comment by huangpf** [comment]
Hi @jianghaolu, Yes, I actually mean assigning it here. I was not able to assign the issue to @sauryadas. Maybe I don't have that control. Could you please help? Thanks~

**Comment by sauryadas** [comment]
@zfeng-cliqr Thanks for the feedback. We recommend that you manage ARM and ASM types separately . Both are fundamentally different from each other and we recommend everyone to move to the ARM model. We have no plan to support both with one set of API.

**Comment by jianghaolu** [comment]
No action to take.
As a side note, I found a tutorial on how to migrate classic VMs to ARM VMs: https://azure.microsoft.com/en-us/documentation/articles/virtual-machines-windows-ps-migration-classic-resource-manager/. JFYI if this is an option for you.
