### ISSUE TITLE
[BUG] SDK ignores AZURE_CLOUD environment variable

### ISSUE THREAD

**Issue by alexandrospanagiotidis** [Azure/azure-sdk-for-java#5741]
**Describe the bug**
We are trying to use an Azure Key Vault in Azure China but it seems that it always connects to Azure global. I found the environment variable `AZURE_CLOUD` (via `com.azure.core.util.configuration.BaseConfigurations`) but it does not seem to have any effect.

***Exception or Stack Trace***
None.

**To Reproduce**
1. Set environment variable `AZURE_CLOUD` to `AZURE_CLOUD_CHINA`
2. Use `SecretAsyncClient` to fetch a secret
3. Bearer token used is `WWW-Authenticate:Bearer authorization="https://login.windows.net/TENANT_ID", resource="https://vault.azure.net"` but should be something like `...chinacloudapi.cn` or anything ending in `.cn`

***Code Snippet***
None.

**Expected behavior**
I am not really sure how this should work, as I did not find any documentation on how to change the Azure cloud instance. I expected that setting `AZURE_CLOUD` to something would at least break my app, but it just boots up and connects to global Azure. I tried different values, too, e.g., `AZURE_CLOUD_CHINA`, `AZURE_CHINA`, `AzureChinaCloud`, and `AzureChina`.

**Screenshots**
None.

**Setup (please complete the following information):**
 - OS: macOS
 - IDE : IntelliJ
 - OpenJDK 11
- com.azure.azure-identity 1.0.0-preview.3
- com.azure.azure-keyvault-secrets 4.0.0-preview.3
- com.azure.azure-core-http-okhttp 1.0.0-preview.4
- com.squareup.okhttp3.okhttp 4.1.0

**Additional context**
None.

**Information Checklist**
Kindly make sure that you have added all the following information above and checkoff the required fields otherwise we will treat the issuer as an incomplete report
- [X] Bug Description Added
- [X] Repro Steps Added
- [X] Setup information Added

**Comment by maggiepint** [comment]
Thanks for the feedback. Routing to appropriate team. @schaabs

**Comment by jianghaolu** [comment]
We are not supporting AZURE_CLOUD for our initial GA release but will add soon afterwards. For now you can authenticate to other clouds by setting the authorityURL for the environment: 
```java
CloudSecretCredential cred = new CloudSecretCredential()
    .authorityHost("https://login.chinacloudapi.cn/")
    ...
```
(https://github.com/Azure/azure-sdk-for-java/blob/master/sdk/identity/azure-identity/src/main/java/com/azure/identity/AadCredentialBuilderBase.java#L20)

**Comment by alexandrospanagiotidis** [comment]
I just checked again and it seems no code changes are necessary for the SDK to connect to the right AAD. In other words, the SDK (same versions as in the initial report) already get a token from `login.chinacloudapi.cn`. I guess something has changed server-side :)

I will keep your suggestion in mind, if this issue pops up again. Thanks!
