### ISSUE TITLE
[FEATURE REQ][COSMOS] Expose the Feed Processor Lag as part of API

### ISSUE THREAD

**Issue by chetanmeh** [Azure/azure-sdk-for-java#5744]
**Is your feature request related to a problem? Please describe.**

Need access to the lag per partition for the ChangeFeedProcessor worker (similar to [GetEstimatedRemainingWorkPerPartitionAsync][1]) for tracking purpose.

**Describe the solution you'd like**

Make the `com.azure.data.cosmos.internal.changefeed.ChangeFeedObserver` public along with `ChangeFeedObserverContext` and expose the lag stats in the context class

**Describe alternatives you've considered**

Currently I am relying on implementation details via logic similar to [.net RemainingWorkEstimator][2] in my [implementation][3] where I need to case the builder to `ChangeFeedProcessorBuilderImpl` and then register a custom `observerFactory`

**Additional context**

Such a feature is supported by .Net implementation for change feed processor

**Information Checklist**
Kindly make sure that you have added all the following information above and checkoff the required fields otherwise we will treat the issuer as an incomplete report
- [x] Description Added
- [x] Expected solution specified

[1]: https://docs.microsoft.com/en-us/dotnet/api/microsoft.azure.documents.changefeedprocessor.partitionmanagement.iremainingworkestimator.getestimatedremainingworkperpartitionasync?view=azure-dotnet
[2]: https://github.com/Azure/azure-documentdb-changefeedprocessor-dotnet/blob/c29ea796fd6e1f8907bc5b75c4736ed1b30baedb/src/DocumentDB.ChangeFeedProcessor/PartitionManagement/RemainingWorkEstimator.cs
[3]: https://github.com/chetanmeh/incubator-openwhisk/blob/cache-invalidator-v3/core/cosmosdb/cache-invalidator/src/main/scala/org/apache/openwhisk/core/database/cosmosdb/cache/WhiskChangeEventObserver.scala#L66

**Comment by chetanmeh** [comment]
In addition please also expose the full `ChangeFeedObserver` which enables returning `Mono`

```
Mono<Void> processChanges(ChangeFeedObserverContext context, List<CosmosItemProperties> docs)
```

This would allow us to chain the `Future` returned from downstream processing of feed (in our case a write to Kafka) and avoid adding an arbitrary `Await` call to force waiting for actual downstream processing to complete.

See [here][1] for an example usage which currently rely on implementation details

```scala
private object ObserverBridge extends com.azure.data.cosmos.internal.changefeed.ChangeFeedObserver {
    override def open(context: ChangeFeedObserverContext): Unit = {}
    override def close(context: ChangeFeedObserverContext, reason: ChangeFeedObserverCloseReason): Unit = {}
    override def processChanges(context: ChangeFeedObserverContext,
                                docs: util.List[CosmosItemProperties]): Mono[Void] = {
      val f = observer.process(context, docs.asScala.toList).map(_ => null).toJava.toCompletableFuture
      Mono.fromFuture(f)
    }
  }
```

[1]: https://github.com/chetanmeh/incubator-openwhisk/blob/b20ce4f5efdce1ec8cce213ff6cdcd7c902ece67/core/cosmosdb/cache-invalidator/src/main/scala/org/apache/openwhisk/core/database/cosmosdb/cache/ChangeFeedConsumer.scala#L98

**Comment by kushagraThapar** [comment]
@milismsft , any updates on this ?

**Comment by milismsft** [comment]
Started coding this feature request; this feature will be rolled out as part of the 4.x version of the Cosmos SDK to start with and will return an estimate for each lease document and current assigned host/worker thread.
