### ISSUE TITLE
[ArchBoard] Standardize SAS Token Generation across .NET, Java, Python, and JS Azure Storage SDKs

### ISSUE THREAD

**Issue by alzimmermsft** [Azure/azure-sdk-for-java#5745]
Currently, SAS token generation has different stories for each language and it needs to be standardized.

**Comment by conniey** [comment]
The equivalent classes I found that generate these SAS query parameters. These names are all so different.

| Java | .NET | Python | JS |
|---|---|---|---|
|[BlobServiceSasSignatureValues](https://github.com/Azure/azure-sdk-for-java/blob/master/sdk/storage/azure-storage-blob/src/main/java/com/azure/storage/blob/specialized/BlobServiceSasSignatureValues.java)|[BlobSasBuilder](https://github.com/Azure/azure-sdk-for-net/blob/master/sdk/storage/Azure.Storage.Blobs/src/Sas/BlobSasBuilder.cs)| [IAccountSASSignatureValues](https://github.com/Azure/azure-sdk-for-js/blob/aae438914e8868cea16b906f2125df36a3e9b85b/sdk/storage/storage-blob/src/IAccountSASSignatureValues.ts#L109) | |
