### ISSUE TITLE
Maven error when updating to Azure SDK for Java v0.9.1 release

### ISSUE THREAD

**Issue by mconverti** [Azure/azure-sdk-for-java#575]
@jianghaolu 

For example, when I try to install the *azure-media* package v0.9.1 by updating my pom.xml file:

```
<dependency>
    <groupId>com.microsoft.azure</groupId>
    <artifactId>azure-media</artifactId>
    <version>0.9.1</version>
</dependency>
```

I receive the following Maven dependency error:

> org.eclipse.aether.resolution.ArtifactDescriptorException: Failed to read artifact descriptor for com.microsoft.azure:azure-media:jar:0.9.1

If I try a previous version (v0.9.0) everything works as expected.

**Comment by mconverti** [comment]
The problem seems to be the missing *com.microsoft.azure:azure-bom:pom:0.9.1* package.

> org.eclipse.aether.transfer.ArtifactNotFoundException: Could not find artifact com.microsoft.azure:azure-bom:pom:0.9.1 in central (https://repo.maven.apache.org/maven2)

**Comment by jianghaolu** [comment]
From maven I see them all published: http://search.maven.org/#artifactdetails%7Ccom.microsoft.azure%7Cazure-media%7C0.9.1%7Cjar. Will give it a try.

**Comment by jianghaolu** [comment]
Ah you are right, azure-bom wasn't published successfully.  Publishing it now you should get that in 24 hours. But if you don't use azure-bom but use azure-media directly this issue shouldn't appear?

**Comment by mconverti** [comment]
Thanks @jianghaolu 

I'm just adding the *azure-media* package as a dependency in my pom.xml file and it seems that *azure-bom* is one of its dependencies. Not just how to skip that.

Regards,
Mariano

**Comment by jianghaolu** [comment]
@mconverti 

Just want to let you azure-bom:0.9.1 is already live. I was able to reproduce and now the issue is gone. Please let me know if you find other issues. Thanks for reporting this so quickly!

**Comment by mconverti** [comment]
@jianghaolu Great! It is also working in my Maven project.

Thanks for the quick turnaround!
