### ISSUE TITLE
Simplify the logic of inputstream to bytebuffer, and move the helper to FluxUtils

### ISSUE THREAD

**Issue by sima-zhu** [Azure/azure-sdk-for-java#5754]
Follow up: https://github.com/Azure/azure-sdk-for-java/pull/5716

**Comment by joshfree** [comment]
@sima-zhu can you explain why this is blocking Preview 5?

**Comment by joshfree** [comment]
Removing from blocking-release for now; please re-add if this is a must-have API breaking change or another critical bug blocking a mainline scenario

**Comment by sima-zhu** [comment]
This is not a blocking release change. Thanks for taking action.

**Comment by alzimmermsft** [comment]
Closing this in favor of #9716 as the issues are the same but that has more discussion.
