### ISSUE TITLE
[QUERY] Copy blob from existing location to new location

### ISSUE THREAD

**Issue by david-nguyen** [Azure/azure-sdk-for-java#5755]
**Query/Question**
Is there a method to perform a copy operation existing in blob storage to another location? It appears that there is not a function that does so.

http://azure.github.io/azure-sdk-for-java/track2reports/index.html

https://docs.microsoft.com/en-us/rest/api/storageservices/copy-blob

***Why is this not a Bug or a Feature Request?***
This appears to be a basic feature that exists in the blob storage library on Azure Functions.

As a reference, the REST API docs lists the operation I would like:

https://docs.microsoft.com/en-us/rest/api/storageservices/copy-blob

Looking at the Java Docs it doesn't appear there is anything similar to the REST API or the Blob library on azure functions `StartCopyAsync`

Or is the copy from url method smart enough to switch context?

For more information, I'm trying to move files quickly but I noticed that Databricks DBFS move is taking longer for larger filer - my hunch is it isn't performing a native azure blob move.

**Comment by alzimmermsft** [comment]
Hi @david-nguyen,

In the Java SDK the `copyFromUrl` API correlates to [Copy Blob from URL](https://docs.microsoft.com/en-us/rest/api/storageservices/copy-blob-from-url) and `startCopyFromUrl` correlates to [Copy Blob](https://docs.microsoft.com/en-us/rest/api/storageservices/copy-blob). We will update the method names and documentation to make this clearer.

@conniey given that you are currently working in this area could you please update this?
