### ISSUE TITLE
[ArchBoard] Support for API / service version specifier in client builder API

### ISSUE THREAD

**Issue by JonathanGiles** [Azure/azure-sdk-for-java#5760]
At present we do not follow spec in our APIs, in that a service / API version can not be set by the user optionally. We should compare with the other languages to ensure we are meeting expectations.

**Comment by joshfree** [comment]
Discussed offline - we will add this in the next wave

**Comment by JonathanGiles** [comment]
Further discussion offline - we will do that this in the next 1.5 weeks after all.

**Comment by JonathanGiles** [comment]
@pakrym What is the name of the enum you use in .NET? Have you considered it being different per client library? E.g. KeyVaultKeyServiceVersion, StorageBlobServiceVersion, etc?

**Comment by pakrym** [comment]
`ServiceVersion`, it's nested inside client-specific option classes https://github.com/Azure/azure-sdk-for-net/blob/master/sdk/keyvault/Azure.Security.KeyVault.Secrets/src/SecretClientOptions.cs#L32 so we didn't do differnt names.

**Comment by pakrym** [comment]
I don't think we've spent a lot of time considering nested vs not-nested enums, honestly.

**Comment by srnagar** [comment]
Every Azure service has its own version of APIs that it supports. Java client libraries should be able to interact with multiple service APIs. 

Users should be able to create a client for any Azure service by specifying the service API version that they want to use. The client should interact with the Azure service using that specific API version.

This allows users to stick to a specific API version and if a newer service API is available that can potentially add/remove features, users are not impacted by that.

One way to do this is by having an enumerated list of all service API versions a client library supports and the user can optionally provide one of the enumerated service versions to the client builder to create the client. A client created with a specific service version will use the request/response protocol mapped to that version.


For e.g.
AppConfig Service has two API versions - v1, v2

AppConfig client library will define an enum:

```java
public enum ServiceVersion {
 V1,
 V2
}

public class ConfigurationClientBuilder {
   ...
   public ConfigurationClientBuilder serviceVersion(ServiceVersion version) {
     this.version = version;
     return this;
   }

   public ConfigurationClient buildClient() {
      // build client with provided version 
      return configurationClient;
   }
}
```


```java
public static void main(String[] args) {
    ConfigurationClient client = new ConfigurationClientBuilder()
                                                  .serviceVersion(ServiceVersion.V2)
                                                  .credentials(credentials)
                                                  .buildClient();
    client.addSetting(...); // this should use V2 service API

    ConfigurationClient client = new ConfigurationClientBuilder()
                                                  .serviceVersion(ServiceVersion.V1)
                                                  .credentials(credentials)
                                                  .buildClient();
    client.addSetting(...); // this should use V1 service API

   ConfigurationClient client = new ConfigurationClientBuilder()
                                                  .credentials(credentials)
                                                  .buildClient();
    client.addSetting(...); // this should use V2 as the latest version is V2
}
```

**Comment by anuchandy** [comment]
Could these feature cause customers to run into issues? For example api-v1 has a primitive enum with { A, B } and in new version service updated it to {A, B, C}, now an SDK working fine with api-v1 will throws deserialization error when it try to process C.

**Comment by srnagar** [comment]
A released SDK can only work with already released service APIs. New service APIs will need a new SDK release. Hope that answers your question. 

In the above example, 
sdk-v1 supports service-api-v1 and can see only {A, B}.
sdk-v2 supports both service-api-v1 and service-api-v2. 

If a customer uses sdk-v2 to build a v1 client, then the sdk should use service-api-v1 and hence should only see {A, B} and not {A, B, C}. The service should respect the requested API version and only return a response that is defined in V1.

**Comment by anuchandy** [comment]
thanks @srnagar,  so each new version of SDK is backward compatible with older SDK version. 

So if v1 service has a schema 

```
Foo {
  A: {
    xx: val1
  },

  B: {
    yy: val2
  }
}
```

Then v1 SDK has a class like:

```java
Class Foo {
  A a;
  B b;
}

class A {
  String xx;
} 

class B {
  String yy;
} 
```

in v2 if service change schema to below by removing BB and merging BB.yy to A,

```
Foo {
  A: {
    xx: val1
    yy: val2
  }
}
```

then do we we map it like below:

```java
 Class Foo {
  A a;
  B b;
}

class A {
  String xx;
  String yy;
} 

class B {
  String yy;
} 
```

And keep the model B and it reference as it is for backward compact?

**Comment by anuchandy** [comment]
thinking a bit more on this, there are couple of ways to map schema changes to models. lets discuss when we really start supporting it. thanks!

**Comment by srnagar** [comment]
@anuchandy yeah, there are a few different ways to do this. The above approach will result in version 1 users seeing class A with both `xx` and `yy`.

Another approach for example could be, version 2 of the SDK could have two java packages `com.azure.foo.models.v1;` and `com.azure.foo.models.v2` containing schema for respective versions.  In the above example, `class B` exists only in `com.azure.foo.models.v1` package and not in `com.azure.foo.models.v2`. `class A` and `class Foo` exists in both. In this version, there's a lot of duplication.

We have to standardize how we want to support versioning.

Version 1:
```java
package com.azure.foo.models.v1;
Class Foo {
  A a;
  B b;
}

class A {
  String xx;
} 

class B {
  String yy;
} 
```

Version 2:
```java
package com.azure.foo.models.v2;

Class Foo {
  A a;
  B b;
}

class A {
  String xx;
} 

class B {
  String yy;
} 
```

```java
package com.azure.foo.v2;
Class Foo {
  A a;
  B b;
}

class A {
  String xx;
  String yy;
} 
```

**Comment by anuchandy** [comment]
@srnagar thanks! the size of per service SDK after couple of releases is also a factor. We can also think of each service version having it's own package then we'll have a role-up package that pulls these version specific packages and exposes entry points.

**Comment by anuchandy** [comment]
The idea is - there is 1:1 mapping between SDK version and service version, i.e. 

```
sdk_version1 = service_version1
```

```
sdk_version2 = service_version2
```

and 

``` 
sdk_version2 != service_version1 + service_version 2
```
Then there is this roll up package which take dependency on sdk_version1 and sdk_version2.
This roll up package expose a way to reach builders in each for the sdk version it depends on:

e.g. 

Get builder for v1 SDK:

```java
storage.v1.BlobClientBuilder builder 
    = storageRollup.getBlobClientBuilder(ServiceVersion.V1);
```

Get builder for v2 SDK:

```java
storage.v2.BlobClientBuilder builder 
    = storageRollup.getBlobClientBuilder(ServiceVersion.V2);
```

Where the signature of `storageRollup.getBlobClientBuilder` is - 

```java
<T> T getBlobClientBuilder(Class<T> class);
```

and the input to this method is is: 
```java
class ServiceVersion {
    public Class<storage.v1.BlobClientBuilder> V1;
    pbulic Class<storage.v2.BlobClientBuilder> V2;
}
```

**Comment by anuchandy** [comment]
An issue we need to be careful  here is - Conflict in transitive dependencies. 

It’s possible that, `v1SDK` depends on `reactor-core-v1` and `v2SDK` on `reactor-core-v2`. 

1. We need to ensure `reactor-core-v2` is back-compact with `reactor-core-v1`, if so rollup package has to override reactor-core in it’s own POM with latest version. 
2. If not back-compact i.e. reactor-core breaking it’s API surface across versions, then its going to be hard. The breaking changes which does not break API surface (e.g. bug fixes in `reactor-core-v2` for example) can be handled by releasing a minor version update of v1SDK.

Regardless, 2 is true even with "composite SDK approach" (V2 SDK for V1 and V2) where models are duplicated or merged, it’s just that wrapping around the breaking changes in dependencies goes into "composite SDK".

This is true for all dependencies in the dependency tree.

**Comment by anuchandy** [comment]
Copying Ashish's comment here:
https://github.com/Azure/azure-sdk-for-java/pull/5782#issuecomment-541838718
```
"The decision is that while we are not major reving the SDK, 
we will try and keep our changes backward compatible. 
Once we major rev, we will clear the list of supported apis and start over."
```

As long as a new service version is back-compact with previous service version then we accommodate the changes in SDK through minor version update, when there is a new version of service that is not back-combat then it's a major version bump for SDK with new set of supported enums.
