### ISSUE TITLE
Auto-gen layer for queue

### ISSUE THREAD

**Issue by sima-zhu** [Azure/azure-sdk-for-java#5761]
- [x] `StorageServiceStats` No need for the class. Return the properties directly.

- [x] `public StorageServiceProperties setLogging(Logging logging) {}` make this clearer to users so that they don't confuse this with our client-side logging (which I did the first time I saw this API).

- [x] `QueueMessage` is never used, put it in implementation.

- [ ] `public QueueItem setName(String name) {}` e.g. setQueueName or whatever it represents.

- [x] `public Boolean isIncludeAPIs() {}` Boolean -> boolean

**Comment by anuchandy** [comment]
*Regarding: `StorageServiceStats` No need for the class. Return the properties directly.*

>> Update: Oct/17:
Discussion on the same model: https://github.com/Azure/azure-sdk-for-java/issues/5671#issuecomment-540765353. This model has been renamed to `QueueStorageServiceStats` [ref](https://github.com/Azure/azure-sdk-for-java/blob/82232d6198b1d7ffebe18fde6a260382707c1be7/sdk/storage/azure-storage-queue/src/main/java/com/azure/storage/queue/models/QueueServiceStatistics.java#L16). No more action item on this.

**Comment by anuchandy** [comment]
*Regarding: public StorageServiceProperties setLogging(Logging logging) {} make this clearer to users so that they don't confuse this with our client-side logging (which I did the first time I saw this API).*

>> Update: Oct/17: Discussion on the same topic https://github.com/Azure/azure-sdk-for-java/issues/5671#issuecomment-540763227. Resolved in the PR #5868

**Comment by anuchandy** [comment]
*Regarding: QueueMessage is never used, put it in implementation.*

>> Update: Oct/17: Discussion on the same topic https://github.com/Azure/azure-sdk-for-java/issues/5671#issuecomment-540738773. Resolved in the [PR](https://github.com/Azure/azure-sdk-for-java/pull/5776).

**Comment by anuchandy** [comment]
*public QueueItem setName(String name) {} e.g. setQueueName or whatever it represents.*

Update: Oct/17: need to follow up

**Comment by anuchandy** [comment]
*`public Boolean isIncludeAPIs() {}` Boolean -> boolean*

>> Update: Oct/17: Discussion on the same topic https://github.com/Azure/azure-sdk-for-java/issues/5671#issuecomment-540716995. There is no action on this.

**Comment by alzimmermsft** [comment]
Last remaining changes will be rolled into a final PR that will be doing a Swagger transform renaming.
