### ISSUE TITLE
[BUG] Size missing in Storage StageBlock Response

### ISSUE THREAD

**Issue by vmaheshw** [Azure/azure-sdk-for-java#5768]
**Describe the bug**
@rickle-msft @alzimmermsft 
1. The log message is displaying unknown-length body. The length was getting calculated correctly with V10.5.
2019/09/30 18:22:11.923 INFO [stageBlock] [reactor-http-epoll-17] [-] [] <-- 201 https://<StorageAccount>.blob.core.windows.net/<ContainerName>/<BlobName>?blockid=<BlockId>&comp=block (777 ms, unknown-length body)

2. What is 777ms in this case? End-To-End latency?

***Exception or Stack Trace***
Add the exception log and stack trace if available

**To Reproduce**

***Code Snippet***
Add the code snippet that causes the issue.

**Expected behavior**

**Screenshots**

**Setup (please complete the following information):**
 - IDE : [e.g. IntelliJ]
 - Version of the Library used

**Additional context**

**Information Checklist**
Kindly make sure that you have added all the following information above and checkoff the required fields otherwise we will treat the issuer as an incomplete report
- [x] Bug Description Added
- [x] Repro Steps Added
- [x] Setup information Added

**Comment by alzimmermsft** [comment]
Hi @vmaheshw, 

Unknown-length is returned when the response doesn't contain the `Content-Length` header, do you have the response headers available?

The 777ms is the latency between the request being sent and a response returning from the service.

Best Regards,
Alan

**Comment by alzimmermsft** [comment]
Plan to address the Unknown-length issue is updating the logging policy to log a message for outbound (request) request size and inbound (response) sizes.

**Comment by alzimmermsft** [comment]
@samvaity do you mind looking into this issue while doing your other work on logging?

**Comment by alzimmermsft** [comment]
PR #6614 added request body size logging. https://github.com/Azure/azure-sdk-for-java/pull/6614/files#diff-1bf1978289f15f56cf8db11581def1a9R130
