### ISSUE TITLE
[API] Changes from UX studies and API reviews

### ISSUE THREAD

**Issue by heaths** [Azure/azure-sdk-for-java#5772]
@heaths commented on [Thu Oct 10 2019](https://github.com/Azure/azure-sdk-for-net/issues/8035)

We have a separate table of proposed/required changes we're keeping cross-language internally.

**Comment by joshfree** [comment]
@g2vinay PTAL

**Comment by joshfree** [comment]
@g2vinay can you please add a link to the PR when ready
