### ISSUE TITLE
Add WARN logs for slow requests

### ISSUE THREAD

**Issue by samvaity** [Azure/azure-sdk-for-java#5773]
Reference: https://github.com/Azure/azure-sdk-for-java/issues/5130

**Comment by ifeoluwaokunoren** [comment]
@samvaity - do you mind providing more information on what is needed from the Azure Resource Manager(ARM) team, especially since the issue you referenced in the description is Closed.

**Comment by ifeoluwaokunoren** [comment]
Issue referenced is closed. I'd close this issue as well, please open a new one, and provide more information on what is needed from the Azure Resource Manager (ARM) team.
