### ISSUE TITLE
[Layering] Need for ProxyAuthenticationPolicy 

### ISSUE THREAD

**Issue by anuchandy** [Azure/azure-sdk-for-java#5779]
Today azure-core has [ProxyAuthenticationPolicy](https://github.com/Azure/azure-sdk-for-java/blob/master/sdk/core/azure-core/src/main/java/com/azure/core/http/policy/ProxyAuthenticationPolicy.java) type, I felt that we can remove this type for GA since HttpClients already have a way to specify proxy. In addition to that HttpClient support different type of proxies Http/Socks[4/5]. Socks[4/5] cannot support through ProxyAuthenticationPolicy, it is only for Http. 

@JonathanGiles if you think this can be removed then I can open PR, which also enables any configuration to be specified on httpClientBuilders, which open more proxy configuration.

**Comment by JonathanGiles** [comment]
Yes, please remove it as it is unused as of now. We can always re-introduce it in the future. Thank you for tidying up.

**Comment by JonathanGiles** [comment]
You might want to consider which other policies are currently unused and whether they should be removed for now. You might also want to consider moving these into a sample, so that we can point users to it if they want to know how to do it.

**Comment by joshfree** [comment]
Unless this is already in PR, please barcheck this with adpship before starting any work.  This feels like something we can live with, given the strong desire to lock down churn in Azure.Core and Azure.Identity this week.

/cc @Petermarcu

**Comment by anuchandy** [comment]
Addressed in the PR https://github.com/Azure/azure-sdk-for-java/issues/5779

**Comment by joshfree** [comment]
Closing issue as the PR has been merged.
