### ISSUE TITLE
[ArchBoard] Review the forceCloseHandles API

### ISSUE THREAD

**Issue by alzimmermsft** [Azure/azure-sdk-for-java#5786]
This API is interesting as it uses paged responses but is closer to a long running operation based on the service implementation. The API should be reviewed to be converted to a specialized LRO and potentially having different API methods for a single handle closure (won't be LRO) and a many handle closue (may be LRO).

**Comment by alzimmermsft** [comment]
Based on ArchBoard discussions there will be two APIs for this REST endpoint:

- forceCloseHanlde(String handleId)
- forceCloseHandles(boolean? recursive)

**Comment by joshfree** [comment]
@conniey could you help load balance this issue?

**Comment by conniey** [comment]
Sounds good.
