### ISSUE TITLE
[BUG]Missing 'Brand Detection' property from ImageAnalysis class

### ISSUE THREAD

**Issue by wiazur** [Azure/azure-sdk-for-java#5796]
**Describe the bug**
Missing 'Brand Detection" property from ImageAnalysis class

The Java SDK seems to be missing a property in the ImageAnalysis class that is present in other languages SDKs for the Computer Vision service.

C# has a 'Brands' property:
https://docs.microsoft.com/en-us/dotnet/api/microsoft.azure.cognitiveservices.vision.computervision.models.imageanalysis?view=azure-dotnet

JavaScript has a 'brands' property:
https://docs.microsoft.com/en-us/javascript/api/azure-cognitiveservices-computervision/imageanalysis?view=azure-node-latest

Python has a 'brands' property:
https://docs.microsoft.com/en-us/python/api/azure-cognitiveservices-vision-computervision/azure.cognitiveservices.vision.computervision.models.imageanalysis?view=azure-python

Thanks.

**Comment by ChrisHMSFT** [comment]
Hey Winona,

Thanks for reporting -- we are investigating updating the SDK and will respond back shortly with an update

Thanks,
Chris

**Comment by wiazur** [comment]
The brand detection property from the Computer Vision SDK ImageAnalysis class has been included in the new SDK 1.1.0-preview.1 version. It is not yet released in Maven, so once it gets released, the samples will be updated.
