### ISSUE TITLE
[BUG]Missing Batch Read File API call in SDK

### ISSUE THREAD

**Issue by wiazur** [Azure/azure-sdk-for-java#5802]
In the Computer Vision API testing console online, I see the Batch Read File call, and it works nicely. But this is only for REST, any idea when the Batch Read File will be available in the Java SDK?

https://westus.dev.cognitive.microsoft.com/docs/services/5adf991815e1060e6355ad44/operations/2afb498089f74080d7ef85eb

Thanks.

**Comment by ChrisHMSFT** [comment]
Hi Winona,

Thanks for reporting. We are investigating and will respond back shortly with an update

thanks!
Chris
