### ISSUE TITLE
Override HttpHeaders toString

### ISSUE THREAD

**Issue by alzimmermsft** [Azure/azure-sdk-for-java#5807]
`HttpHeaders` uses the default `toString` method which ends up printing `content-length:Content-Length=7`. Override the `toString` method to print a coma delimited `HttpHeader.toString` list, this should result in `Content-Length=7,...`.

**Comment by thiyagu-7** [comment]
I would like to take this up

**Comment by JonathanGiles** [comment]
There are now two pull requests for this issue - #5855 and #5861. I like the implementation in #5855, but I would like to see some test cases like in #5861. @nebrass and / or @dollyd can you unify on one PR? Thanks!

**Comment by nebrass** [comment]
@JonathanGiles I added a test case to #5855

**Comment by kuldeepsingh-dhillon** [comment]
I can take this up if this is still available.

**Comment by JonathanGiles** [comment]
This issue is now resolved thanks to #5855. It will be merged in a few weeks.

**Comment by joshfree** [comment]
Assigning to @JonathanGiles to close once PR #5855 is merged
