### ISSUE TITLE
hardcoded DNS

### ISSUE THREAD

**Issue by wy4515** [Azure/azure-sdk-for-java#581]
in azure/utility/NetworkHelper.java, the DNS server is hard coded to be **'10.1.1.1'**. This might cause the vm not be able to route internet.

It might be a good idea to dynamically assign a DNS to the machine.

**Comment by jianghaolu** [comment]
@xindzhan

**Comment by xindzhan** [comment]
The idea for most helper is that it creates a simple default template while any component like VNET can be customized or replaced in the main context object and I would use this as the current workaround.
Meanwhile I completely agree that these hardcode setting shall be replace with better dynamic setting and maybe we can create a list of items like this to be included in the work for autorest migration?

**Comment by jianghaolu** [comment]
Yeah, we need a better story here. We can provide an uber overload, or a configuration, or some other ways to support both dynamic setting and default setting with simplicity.
I'm sure we will revisit this part in the work of migration.

Closing as there is a workaround for now.

**Comment by Brian-McG** [comment]
Hi, I am unable to launch an instance with any VNET DNS other than 10.1.1.1, what am I missing here:
```java
        ArrayList<String> dnsServers = new ArrayList<>();
        dnsServers.add("8.8.8.8");
        DhcpOptions dhcpOptions = new DhcpOptions();
        dhcpOptions.setDnsServers(dnsServers);
        virtualNetwork.setDhcpOptions(dhcpOptions);
        context.setVirtualNetwork(virtualNetwork);

        try {
            ComputeHelper.createOrUpdateResourceGroup(resourceManagementClient, context);
            NetworkHelper.createVirtualNetwork(networkResourceProviderClient, context);
        } catch (Exception e) {
            ...
        }
```

**Comment by xindzhan** [comment]
Hi Brian did you get exception from the sdk or does the VM instance failed after request sent? I think the default we use is "8.8.8.8".

**Comment by Brian-McG** [comment]
No, it would just start up with a dns of 10.1.1.1 still.
I managed to solve the issue by using my own createVirtualNetwork method, this is because the createVirtualNetwork method in the SDK sets it to 10.1.1.1 as this issue describes.
[NetworkHelper.java](https://github.com/Azure/azure-sdk-for-java/blob/master/resource-management/azure-mgmt-utility/src/main/java/com/microsoft/azure/utility/NetworkHelper.java)
