### ISSUE TITLE
Drop commons codec dependency in KV

### ISSUE THREAD

**Issue by g2vinay** [Azure/azure-sdk-for-java#5810]

**Comment by joshfree** [comment]
@g2vinay can you provide more details why the dependency could not be removed in a future release?  This doesn't sound blocking-release based on the title.

**Comment by joshfree** [comment]
Removing 'blocking-release' label

**Comment by JonathanGiles** [comment]
@g2vinay I'd really like to see this dependency removed ASAP. Can you give a status update on this please? Thanks!

**Comment by JonathanGiles** [comment]
I believe this can be closed now.

**Comment by g2vinay** [comment]
Yep, This change was completed and shipped in December.
