### ISSUE TITLE
Add Code Samples for Common Scenarios

### ISSUE THREAD

**Issue by alzimmermsft** [Azure/azure-sdk-for-java#5814]
Add code samples in the README and sample files that run through basic common scenarios such as the following:

- [ ] Create if not exists
- [ ] Listing containers or blobs and creating clients from the listings
- [ ] Upload if not exists
- [ ] Overwrite if exists

**Comment by rickle-msft** [comment]
- [ ] Downloading to a file
- [ ] Setting a proxy 
- [ ] Working with BlobStreams
- [ ] Generating/setting a sas

**Comment by rickle-msft** [comment]
Also, just for tracking, ensure we have these scenarios covered in v8<->v12 as well
