### ISSUE TITLE
[BUG Swagger] apply x-ms-client-name for eTag in storage swagger

### ISSUE THREAD

**Issue by anuchandy** [Azure/azure-sdk-for-java#5815]
The etag property in various models in storage should be camel cased, this can be done using x-ms-client-name. Without such customization, in generated models the acronym is presented as "etag", based on guidelines it should be "eTag".

**Comment by anuchandy** [comment]
Also once swagger is merged, remove etag naming from storage transformation readme specific to java.

**Comment by anuchandy** [comment]
PR to swagger opened here: https://github.com/Azure/azure-rest-api-specs/pull/7549

**Comment by alzimmermsft** [comment]
Issue has been fixed by Swagger transforms in other PRs.
