### ISSUE TITLE
Use singular naming convention for package names in client libraries

### ISSUE THREAD

**Issue by samvaity** [Azure/azure-sdk-for-java#5819]
Reference: https://apiview.azurewebsites.net/Assemblies/Review/0957665bd5d54c2394199d291898e05c#com.azure.core.credentials.AccessToken

>We have models, entities, keys, eventhubs and credentials. Maybe keys and eventhubs are exceptions to this rule as they are service names, but should we rename the others to use singular names as well?

**Comment by joshfree** [comment]
Let's won't-fix this for Preview 5 and leave the package names as-is for the release.

/cc @JonathanGiles @Petermarcu as fyi on triaging
