### ISSUE TITLE
[Performance] Update default block size based on blob size

### ISSUE THREAD

**Issue by rickle-msft** [Azure/azure-sdk-for-java#5822]
In uploadFromFile, (and any upload methods where we know the length), we should change the default blockSize to 8MB if the total blob size is over 100MB. If we don't know the blob size, we should leave the default as 4MB. This will help trigger some service optimizations in some cases. 

This is blocking releases because it breaks the results of getBlockList. Since we change the block size, we change how many blocks are needed to stage an entire blob, and this will change the results of doing a getBlockList on the same data uploaded before and after this change.

**Comment by joshfree** [comment]
@rickle-msft can you please drive this?
