### ISSUE TITLE
Support IP-Style URLs (enables Azurite)

### ISSUE THREAD

**Issue by rickle-msft** [Azure/azure-sdk-for-java#5823]
Azurite uses a special URL format that we have to support. More investigation is needed but details will be posted here.

**Comment by alzimmermsft** [comment]
I believe this is an implementation detail that could be handled next week

**Comment by rickle-msft** [comment]
I agree. This was actually supported in v10. Not sure how it got missed in the port, but it should only be additive. See [this PR](https://github.com/Azure/azure-storage-java/pull/415) for reference.

**Comment by joshfree** [comment]
cc: @JeffreyRichter

**Comment by alzimmermsft** [comment]
@JeffreyRichter  and I discussed this and what is needed to be done to fix the issue. At this time the endpoint parsing would fail in these cases.
