### ISSUE TITLE
[ArchBoard] Poller API: Investigate cancellation operation signature

### ISSUE THREAD

**Issue by conniey** [Azure/azure-sdk-for-java#5824]
The Poller API's cancellation operation takes a consumer that passes in itself. There are cancellation operations dependent on the last `PollResponse<T>`. There is no public API to expose the last response though.

__Questions/Options__
1. Should the cancellation operation be updated to pass `Consumer<PollResponse<T>>` rather than `Poller<T>`?
1. Should we create a getter on `Poller<T>` that returns the last polled response?
1. Should we update the cancellation operation to expose a `BiConsumer<Poller<T>, PollResponse<T>>`?
1. Leave as-is.

__Current constructor__
```java
public Poller(
    Duration pollInterval, 
    Function<PollResponse<T>, Mono<PollResponse<T>>> pollOperation,
    Supplier<Mono<T>> activationOperation, 
    Consumer<Poller<T>> cancelOperation) {
```

### Example
Azure Storage's [Copy Blob from Url](https://docs.microsoft.com/en-us/rest/api/storageservices/copy-blob-from-url) call returns a unique copy ID when a long running copy operation is started . This copy id is needed to cancel a pending copy operation.  There's no way to fetch that from the current cancellation signature.

My code currently looks like this where I set an `AtomicReference<String>` with the copy ID for that long running operation. And then have to fetch it to cancel.

#### Current implementation
```java
public Poller<BlobCopyOperation> beginCopyFromUrl(....) {
    final AtomicReference<String> copyId = new AtomicReference<>();

    return new Poller<>(Duration.ofSeconds(1),
        response -> onPoll(response),
        () -> onStart(sourceUrl, copyId),
        unused -> {
            final String copyIdentifier = copyId.get();

            if (!ImplUtils.isNullOrEmpty(copyIdentifier)) {
                logger.info("Cancelling copy operation for copy: {}", copyIdentifier);

                Utility.blockWithOptionalTimeout(abortCopyFromURL(copyIdentifier), null);
            }
        });
}

private Mono<BlobCopyOperation> onStart(URL sourceUrl, AtomicReference<String> copyIdReference) {
    return azureBlobStorage.blobs().startCopyFromURLWithRestResponseAsync(sourceUrl)
        .map(response -> {
            final BlobStartCopyFromURLHeaders headers = response.getDeserializedHeaders();
            copyIdReference.set(headers.getCopyId());

            return new BlobCopyOperation(headers.getCopyId(), getBlobUrl(), sourceUrl.toString(),
                headers.getCopyStatus(), headers.getErrorCode());
        });
}
```

#### If option 1 is used
```java
public Poller<BlobCopyOperation> beginCopyFromUrl(....) {
    return new Poller<>(Duration.ofSeconds(1),
        response -> onPoll(response),
        () -> onStart(sourceUrl),
        lastResponse -> {
            BlobCopyOperation operation = lastResponse.getValue();
            if (!ImplUtils.isNullOrEmpty(operation.getCopyId())) {
                logger.info("Cancelling copy operation for copy: {}", copyIdentifier);

                Utility.blockWithOptionalTimeout(abortCopyFromURL(copyIdentifier), null);
            }
        });
}

private Mono<BlobCopyOperation> onStart(URL sourceUrl) {
    return azureBlobStorage.blobs().startCopyFromURLWithRestResponseAsync(sourceUrl)
        .map(response -> {
            final BlobStartCopyFromURLHeaders headers = response.getDeserializedHeaders();
            return new BlobCopyOperation(headers.getCopyId(), getBlobUrl(), sourceUrl.toString(),
                headers.getCopyStatus(), headers.getErrorCode());
        });
}
```

**Comment by JonathanGiles** [comment]
FYI - there exists this PR from @g2vinay: https://github.com/Azure/azure-sdk-for-java/pull/5820

**Comment by JonathanGiles** [comment]
I would go with 2, and at the same time, improve the `hasCompleted()` method to be public and to use the change we discussed via email on the `OperationStatus` type. I would probably rename it to `isComplete()` or similar?

**Comment by joshfree** [comment]
Adding [ArchBoard] label to better track architect-requested API breaking changes

**Comment by hemanttanwar** [comment]
Spoke to Vinay, He have good handle on this one . There will be PR soon.
