### ISSUE TITLE
Missing StorageEvent equivalent functionality in v12 

### ISSUE THREAD

**Issue by sima-zhu** [Azure/azure-sdk-for-java#5828]
Suggestion path from customer:

1.	The equivalent StorageEvent functionality is added to the SDK v12.
2.	The bug in SDK v8 for Content-Disposition header is fixed and released.
3.	There is a disconnect about the capabilities of SDK v12 and it is possible to do what is needed with StorageEvents.

**Comment by sima-zhu** [comment]
Low priority as this has not been previewed and does not take in track 2.

**Comment by rickle-msft** [comment]
For context, StorageEvent was an object passed into callback methods at various points of v8's ExecutionEngine. It had the connection object, request result, and operation context. I am fairly confident that the customer's ask, and any workflow's related to this type, can be supported via a policy. The customer just has to create a policy to process the outgoing request/incoming response as they see fit and add it to their pipeline.

**Comment by rickle-msft** [comment]
In light of this customer ask, perhaps it would be a good idea to include some more thorough samples on creating a pipeline policy and including it in a client.

**Comment by amishra-dev** [comment]
@rickle-msft let talk about this tomorrow.

**Comment by amishra-dev** [comment]
spoken offline, as Rick say's we will add a sample that shows how to do this in track2.
