### ISSUE TITLE
Respect HTTP proxy system properties

### ISSUE THREAD

**Issue by mikeharder** [Azure/azure-sdk-for-java#5832]
I think our Java SDKs should support the HTTP/HTTPS proxy system properties, as defined at https://docs.oracle.com/javase/8/docs/technotes/guides/net/proxies.html.  This includes `http.proxyHost` and `http.proxyPort`, along with the corresponding HTTPS properties (if they can be supported).  I believe these properties are ignored by Netty, so our SDK would need to read the properties and pass them along to Netty.

**Comment by mikeharder** [comment]
These properties do seem to be respected by the v8 Java Storage SDK (`com.microsoft.azure.azure-storage@8.4.0`).

**Comment by joshfree** [comment]
Related Proxy work items that could be tackled at the same time

- https://github.com/Azure/azure-sdk-for-java/issues/6109
- https://github.com/Azure/azure-sdk-for-java/issues/5725
- https://github.com/Azure/azure-sdk-for-java/issues/5372

**Comment by joshfree** [comment]
@alzimmermsft can you PTAL since you're already working on better proxy support?

**Comment by alzimmermsft** [comment]
Resolved in PR #7593
