### ISSUE TITLE
[ArchBoard] Azure-Storage-queue  API Review 

### ISSUE THREAD

**Issue by hemanttanwar** [Azure/azure-sdk-for-java#5835]
Complete API  from following .
https://apiview.azurewebsites.net/Assemblies/Review/5f8f08d0908247158f30b451a91f252e

**Comment by sima-zhu** [comment]
- [ ] IpRange -> SasIpRange -> move to sas package

- [ ] dequeueMessage -> getMessage

- [ ] QueueSasPermission hadRead..->hasRead

- [ ] QueueServiceSasQueryParameters use full name

- [ ] DequeuedMessage get/setTimeNextVisible() -> get/setNextTimeVisible() 

- [ ] Move SharedKeyCredential to root package

- [ ] public AccountSasPermission setAddPermission(boolean hadAddPermission) {}

- [ ] public AccountSasPermission setListPermission(boolean hadListPermission) {}

- [ ] public AccountSasQueryParameters(Map<String, String[]> queryParamsMap, boolean removeSASParametersFromMap)

- [ ] public AccountSasResourceType setObject(boolean object) {} // better doc

- [ ] BaseSasQueryParameters getQueryParameter(Map<String, String[]> parameters, String name, Boolean remove, Function<String, T> converter) Boolean -> boolean

- [ ] SR review and remove

- [ ] SharedKeyCredential->StorageSharedKeyCredential

- [ ] SharedKeyCredentialPolicy -> StorageSharedKeyCredentialPolicy hidding from public?

- [ ] RequestRetryOptions getter and setter

**Comment by sima-zhu** [comment]
dequeueMessage -> getMessage
https://github.com/Azure/azure-sdk-for-java/pull/5857

**Comment by sima-zhu** [comment]
IpRange->SasIpRange:
https://github.com/Azure/azure-sdk-for-java/pull/5863

**Comment by sima-zhu** [comment]
RequestRetryOptions getter
https://github.com/Azure/azure-sdk-for-java/pull/5867

**Comment by anuchandy** [comment]
For reference: linking to another set of Queue API feedbacks https://github.com/Azure/azure-sdk-for-java/issues/5671. All work items in this issue are addressed.

**Comment by sima-zhu** [comment]
DequeueMessage rename:

https://github.com/Azure/azure-sdk-for-java/pull/5876/

**Comment by sima-zhu** [comment]
Rename ShareKeyCredential and its policy
https://github.com/Azure/azure-sdk-for-java/pull/5899
