### ISSUE TITLE
Support custom application id in user agent  telemetry policy

### ISSUE THREAD

**Issue by srnagar** [Azure/azure-sdk-for-java#5842]
Support custom applicationId that users can set in user agent, as per new guidelines for `UserAgentPolicy` defined here - https://github.com/Azure/azure-sdk/pull/614/files

Include length check for user-provided applicationId and verify no spaces are included in the appId.

**Comment by srnagar** [comment]
@JonathanGiles @joshfree - is this blocking release or can it wait until after GA?

**Comment by JonathanGiles** [comment]
It can wait until the next release IMHO.

**Comment by joshfree** [comment]
@samvaity could you assist with this for the December SDK update?
