### ISSUE TITLE
[QUERY] how to upload a large file to blob?

### ISSUE THREAD

**Issue by SHIELD7** [Azure/azure-sdk-for-java#5875]
I current using the latest sdk 12.0.0-preview.4
how can I upload a very large file to azure ,like 1Gb large. if I fail upload a file how can I resume from break point.
I try to use code like blow ,of course,after a long time waiting I fail.
`            blobClient.uploadFromFile(file.getPath());
`

**Comment by rickle-msft** [comment]
This should be all you need to upload a file. Can you please share how long you are waiting and what error you are seeing upon failure? 

I notice you have left another comment asking about using the async client. It's not clear here whether you are using the sync or async client, but if you are using the async client, you should note that you have to subscribe to the operation in order for it to start doing work. Simply calling uploadFromFile on the async client will not begin the transfer.
