### ISSUE TITLE
Update Netty Client Event Loop Group default selection

### ISSUE THREAD

**Issue by g2vinay** [Azure/azure-sdk-for-java#5877]
Fir Windows -> NioEventLoopGroup should be default..
For Linux -> EpollEventLoopGroup should be default
For Mac -> Kqueue EventLoopGroup (Investigate performance gain before implementing)

**Comment by alzimmermsft** [comment]
Netty may do this implicitly based on the OS specific modules that are included.

**Comment by alzimmermsft** [comment]
Netty handles this implicitly if the native module is on the classpath (which we now have for `azure-core-http-netty`).
