### ISSUE TITLE
[API] Add Simple Upload Overload That Takes an Overwrite Flag

### ISSUE THREAD

**Issue by alzimmermsft** [Azure/azure-sdk-for-java#5881]
Add an upload overload that takes an additional `overwrite` flag and when the flag is set to false pass an HTTP conditional of `If-None-Match=*` to prevent the current blob from being overwritten.

**Comment by joshfree** [comment]
@alzimmermsft is this for cross language consistency?

**Comment by alzimmermsft** [comment]
This is for consistency across languages and determining the default semantics for uploading.

@tg-msft is doing the investigation, this issue is the work item (if required) to comply with the results of the investigation.

**Comment by joshfree** [comment]
@tg-msft is this actionable at this point?

**Comment by tg-msft** [comment]
We're doing it in .NET.  It's just an overload of `Upload` that takes `bool overwrite` which if `false` (the default) will automatically set the correct `IfNoneMatch = *` access conditions.  Should be three lines of code.

**Comment by joshfree** [comment]
From our recent UX study

> none of these participants thought that BlobClient.upload should not overwrite existing content in a blob. They all said that they expected this to overwrite and not to throw an exception. When asked to explain why they thought that the default behaviour should be that it overwrites, some suggested that this is consistent with how other Java SDKs work such as FileWriter/PrintWriter. While it is indeed the case that FileWriter/PrintWriter will overwrite file content by default, the same is true for StreamWriter in .Net.

**Comment by amishra-dev** [comment]
@joshfree that is an interesting perspective, but think of the user experience when you blow away their 1TB blob with say a 1 byte one :) or am I reading this comment incorrectly (sorry not great with double negation)
