### ISSUE TITLE
Remove Interval property from DeviceCodeChallenge

### ISSUE THREAD

**Issue by schaabs** [Azure/azure-sdk-for-java#5886]

**Comment by joshfree** [comment]
@schaabs as part of the review, it might be easier to open up 1 single bug with a checklist of changes requested

**Comment by schaabs** [comment]
@joshfree That's fine if we want to consolidate there were only a few so I didn't know if it made sense to track them separately

**Comment by jianghaolu** [comment]
Fixes merged.
