### ISSUE TITLE
Configurable maxSingleShotSize for uploadFileToBlockBlob

### ISSUE THREAD

**Issue by rickle-msft** [Azure/azure-sdk-for-java#5887]
This value should be added as a parameter to uploadFile, either in the method signature or in ParallelTransferOptions. It can default to the maxUploadSize of 256MB. The reason for this parameter is allowing customers to configure streaming vs transaction costs. Breaking larger files into chunks can possibily parallelize and therefore speedup transfer, but it can consume more resources and requires more requests, which may be undesirable in certain environments. Therefore, the customer should be able to configure when they want to upload an entire file all at once if the size is permitted by the service.

**Comment by alzimmermsft** [comment]
Similar issue is #6097
