### ISSUE TITLE
White list default http headers for logging

### ISSUE THREAD

**Issue by JonathanGiles** [Azure/azure-sdk-for-java#5890]
Refer to the headers added [here](https://github.com/Azure/azure-sdk-for-net/pull/8166), we need to white list the same set for Java logging.

Fixed by #5893

**Comment by joshfree** [comment]
We should get this snuck in ahead of GA

https://github.com/Azure/azure-sdk-for-net/pull/8166/files

**Comment by joshfree** [comment]
(tagging as blocking-release for Preview 5 solely for bug tracking on the query; not that I would actually block Preview 5 for this change if it doesn't make it in time)

**Comment by samvaity** [comment]
Closed in #5893
