### ISSUE TITLE
AzureRM is still preview?

### ISSUE THREAD

**Issue by ssuriya** [Azure/azure-sdk-for-java#590]
We are planning for our own product release which depends on Azure SDK.

When will the AzureRM preview version be ended? 

I can't find the preview keyword in new Azure portal, is that only Azure Java SDK is alone in preview or everything related to AzureRM is still in preview? When is the stable release without preview?

Thanks & Regards,
-Sakthi

**Comment by jianghaolu** [comment]
On the API level, each individual service team has their own agenda on when to release the ARM APIs as non-preview releases. You can tell that by looking at the api-version property on the clients, e.g., the [resource management client](https://github.com/Azure/azure-sdk-for-java/blob/autorest/azure-mgmt-resources/src/main/java/com/microsoft/azure/management/resources/ResourceManagementClientImpl.java#L281).

The SDK team also has our agenda for each SDK library to trim the '-preview', considering the libraries are relatively newly generated from AutoRest. On the Java side, we are looking at couple months' consolidation before we release a '1.0.0' without any suffixes. 

+ @mayurid @devigned

**Comment by jianghaolu** [comment]
No action to take.
