### ISSUE TITLE
Simplify handling of service version enum (and other properties) in storage builders

### ISSUE THREAD

**Issue by JonathanGiles** [Azure/azure-sdk-for-java#5906]
Currently there exists a somewhat convoluted way of passing builder parameters into a service client such as the Blob client, wherein the properties are actually passed to an internal client and then retrieved from that. Unfortunately, in some cases, this requires additional parsing or enum -> string -> enum conversion which poses risks and may introduce bugs. It would be better to pass the parameters directly into the top-level client, such that these risks may be avoided entirely. This will also allow for the removal of some public API related to parsing these strings, and changing the `getServiceVersion()` methods to properly return the enum, rather than the String value.

**Comment by alzimmermsft** [comment]
Fixed #5914
