### ISSUE TITLE
[API] Rename Files to Files Shares for November Preview Release

### ISSUE THREAD

**Issue by JonathanGiles** [Azure/azure-sdk-for-java#5909]
Changes required:
 * Rename directory: `/sdk/storage/azure-storage-file` to `/sdk/storage/azure-storage-file-share`
 * New package name: `com.azure.storage.file.share` to `com.azure.storage.file.share`
 * Update build system, checkstyle, coverage, spotbugs, etc config to ensure correct location is used

Still TBD:
 * Client naming pattern.

**Comment by joshfree** [comment]
@sima-zhu can you fix this late-breaking package and API change for Preview 5 ahead of any other File bugs?

**Comment by sima-zhu** [comment]
Working on rename directory and package name

**Comment by sima-zhu** [comment]
The changes got merged. Closed the issue.
