### ISSUE TITLE
Add Create and Delete Blob from ContainerClient

### ISSUE THREAD

**Issue by alzimmermsft** [Azure/azure-sdk-for-java#5921]
One of the API guidelines for hierarchical services is to be able to create and delete resources of the level below the current client, `BlobContainerClient` is missing a create and delete blob operation.

This is an additive change and can be done with a lower priority, along with that there are some design choices that need to be made for the create operation as this will need to support Append, Block, and Page blobs.

**Comment by gapra-msft** [comment]
Closing this. Decision was made not to do this since there are multiple kinds of blobs and it would result in an explosion of create methods.

We can re-consider if a customer ask comes in.
