### ISSUE TITLE
Azure Core - Poller  - Block / Block Until [State Checks missing]

### ISSUE THREAD

**Issue by g2vinay** [Azure/azure-sdk-for-java#5923]
Block - check if the poller has not already competed before blocking.
Block Until - check poller is not already in the target status and is not already completed.

in azure-core/util/polling/Poller.java

**Comment by joshfree** [comment]
Related https://github.com/Azure/azure-sdk-for-java/issues/5809 and https://github.com/Azure/azure-sdk-for-java/issues/5805

**Comment by joshfree** [comment]
@anuchandy could you please coordinate with @g2vinay on the related Poller reliability issues #5805 #5809 #5923

**Comment by anuchandy** [comment]
@joshfree - I'm reviewing the current implementation of poller, left some observations here - https://github.com/Azure/azure-sdk-for-java/pull/5932#pullrequestreview-304279959, still looking into the code.

**Comment by anuchandy** [comment]
We're working updating Poller implementation, this issue is related to multi-casting and not applicable in the new design.
