### ISSUE TITLE
Use Swagger Transforms to Match API Spec

### ISSUE THREAD

**Issue by alzimmermsft** [Azure/azure-sdk-for-java#5925]
There is going to be another round of API reviews to find where the codegen classes are not inline with the naming guidelines, this issue is meant to track all found instances.

**Comment by hemanttanwar** [comment]
https://app.zenhub.com/workspaces/azure-sdk-team-5bdca72c4b5806bc2bf0aab2/issues/azure/azure-sdk-for-java/5928
