### ISSUE TITLE
Batch send and receive message API

### ISSUE THREAD

**Issue by dipakdeb** [Azure/azure-sdk-for-java#593]
Hi, can you please let me know when you plan to provide batch message send and receive API in Java like the one is there in C#  ?

This is the API I see avaialble in C# - https://msdn.microsoft.com/en-us/library/microsoft.servicebus.messaging.topicclient.sendbatch.aspx

Thanks

**Comment by jianghaolu** [comment]
@djrosanova can you give some insights to @dipakdeb?

Thanks!

**Comment by collinsauve** [comment]
Almost a year now, can someone provide any more details?

**Comment by martinsawicki** [comment]
the service bus client library is not in this repo anymore, so if this is still an issue, it should go there:
https://github.com/azure/azure-service-bus-java
