### ISSUE TITLE
Docstrings and Package READMEs for {Storage, KeyVault, AppConfig, EventHubs} should be updated before the November release

### ISSUE THREAD

**Issue by kaerm** [Azure/azure-sdk-for-java#5935]
*Before the release* we need to make sure that all of the docstrings are finalized and updated before the package is released as this is the version that will be publicly available in documentation. Refer to teams for more detailed guidance 
- [ ] READMEs per package done and tested
- [ ] Docstrings per package updated

**Comment by joshfree** [comment]
@hemanttanwar could you help coordinate this and make the appropriate updates for the core common libraries?

**Comment by joshfree** [comment]
Related https://github.com/Azure/azure-sdk-for-java/issues/5950

**Comment by JonathanGiles** [comment]
As part of this please generate a full set of javadocs and review that all classes look adequately documented, with code samples, explanatory text, and links to other class files. If any code snippets are referenced but not properly imported, please ensure these are rectified.

**Comment by hemanttanwar** [comment]
https://github.com/Azure/azure-sdk-for-java/pull/5991

**Comment by Petermarcu** [comment]
Where are we on this one?

**Comment by joshfree** [comment]
@hemanttanwar can you share an update?

**Comment by joshfree** [comment]
This issue is tracking updating 

1. the root README.md (change October to November), 
2. the Identity readme,
3. and creating the samples/README.md; 

ETA end of today

**Comment by joshfree** [comment]
Related https://github.com/Azure/azure-sdk-for-java/pull/6057

**Comment by joshfree** [comment]
Removing `Azure.Core` as Azure.Core and Azure.Identity doc updates are now merged.

Upstack components are still in progress for EOD today.

**Comment by hemanttanwar** [comment]
completed
