### ISSUE TITLE
Address two community gaps

### ISSUE THREAD

**Issue by Petermarcu** [Azure/azure-sdk-for-java#5936]
https://github.com/Azure/azure-sdk-for-java/community

- [ ] Code of Conduct
- [ ] PR Template

**Comment by kurtzeborn** [comment]
I removed the "EngSys" label because the engineering system team directly owns the contributing.md for each of the repos, but beyond that, these additional items should be owned by the owners of each repo.

**Comment by joshfree** [comment]
@mssfang can you please take a look?

**Comment by mssfang** [comment]
Sure.
