### ISSUE TITLE
Create service level readmes

### ISSUE THREAD

**Issue by kaerm** [Azure/azure-sdk-for-java#5937]
Update the service level and add READMEs (such as [this one](https://github.com/Azure/azure-sdk-for-java/tree/master/sdk/storage)) to help directing people to the right package in the repo. Make sure to describe all of the packages and signal which one should be used for what

**Comment by joshfree** [comment]
cc: @hemanttanwar @JimSuplizio as FYI

**Comment by kaerm** [comment]
ping @hemanttanwar

**Comment by joshfree** [comment]
Moving this to the January milestone.

**Comment by hemanttanwar** [comment]
https://github.com/Azure/azure-sdk-for-java/pull/6444

**Comment by hemanttanwar** [comment]
Complete  PR Closed https://github.com/Azure/azure-sdk-for-java/pull/6444
