### ISSUE TITLE
Finish Cleaning Batchings Internal Implementation

### ISSUE THREAD

**Issue by alzimmermsft** [Azure/azure-sdk-for-java#5942]
`urlPath = urlPath + "?" + urlQuery;` -> `urlPath += "?" + urlQuery;`

Add documentation for the response parsing to explain what is happening and why.

**Comment by amishra-dev** [comment]
@alzimmermsft are we claiming that batch implementation is not clean?

**Comment by alzimmermsft** [comment]
This issue is more about cleaning up internal calls and some enhancement to internal documentation.

**Comment by alzimmermsft** [comment]
Fixed by #7290
