### ISSUE TITLE
RetryPolicy should support custom retry headers for different Azure services 

### ISSUE THREAD

**Issue by srnagar** [Azure/azure-sdk-for-java#5945]
Currently, RetryPolicy uses `retry-after-ms` to determine the delay duration. However, different Azure services return the delay duration in different response headers. 
So, we should look into supporting different headers for delay duration.

For e.g. AppConfig uses `retry-after-ms` while CosmosDB uses `x-ms-retry-after-ms`.

RetryPolicy should also allow a customized list of HTTP status codes that are retryable. 
https://azure.github.io/azure-sdk/general_azurecore.html#retry-policy

**Comment by hemanttanwar** [comment]
PR :  https://github.com/Azure/azure-sdk-for-java/pull/6196
