### ISSUE TITLE
Update samples for each package

### ISSUE THREAD

**Issue by kaerm** [Azure/azure-sdk-for-java#5950]
Update samples for each package that we are releasing. Follow the guidelines about 
- [x]  Creating a /samples directory
- [x]  Adding a readme for the /samples directory
- [x]  Adding metadata to the samples for indexing
- [ ]  Including more advanced scenarios

**Comment by joshfree** [comment]
@hemanttanwar can you work with @kaerm and own driving this consistency push for the Java SDKs shipping with the November SDK release

**Comment by kaerm** [comment]
ping @hemanttanwar

**Comment by hemanttanwar** [comment]
Following are complete 
  Creating a /samples directory 
  Adding a readme for the /samples directory

**Comment by hemanttanwar** [comment]
@kaerm  Added metadata also  PR  https://github.com/Azure/azure-sdk-for-java/pull/7395

Is this done, adding advance samples is ongoing process, not sure we can complete in one go.

**Comment by kaerm** [comment]
Makes sense, once that is merged we can close this

**Comment by hemanttanwar** [comment]
closing
