### ISSUE TITLE
Visibility on protected fields/methods in Azure Storage

### ISSUE THREAD

**Issue by conniey** [Azure/azure-sdk-for-java#5962]
## Issues
- [ ] Looking at the JavaDocs, BlobAsyncClientBase has protected fields which also have publicly visible getters.  We could reduce the public surface area by making these private.
  * Although we make use of azureBlobStorage in inheriting classes, it feels better to encapsulate this using a getter rather than having direct access to the field.
- [ ] There are some methods that exist only to support cross-package support and we don't expect end users to use this (ie. [getServiceVersion()](https://github.com/Azure/azure-sdk-for-java/blob/master/sdk/storage/azure-storage-blob/src/main/java/com/azure/storage/blob/BlobContainerAsyncClient.java#L182)). These should be removed from public API.
   - Alan may be able to help you look through the API list exposed in Storage and see what needs to be removed.

## Possible solutions
* Jonathan mentioned in the JDK, they have a helper pattern we may be able to leverage to avoid leaking implementation classes. For example, they have [NodeHelper.java](https://github.com/teamfx/openjfx-9-dev-rt/blob/master/modules/javafx.graphics/src/main/java/com/sun/javafx/scene/NodeHelper.java) which allows them to access fields/methods in [Node.java](https://github.com/teamfx/openjfx-9-dev-rt/blob/master/modules/javafx.graphics/src/main/java/javafx/scene/Node.java#L411) for implementation purposes, but they don't want to expose it as public API.
* There is probably some way to pass in dependent variables/classes via dependency injection when creating the object so we don't have to have a getter on them.

![image](https://user-images.githubusercontent.com/10136526/67236463-25a00e80-f3fe-11e9-8827-9a7cfdf3617f.png)

Related to #5517 

/cc @alzimmermsft @JonathanGiles @hemanttanwar

**Comment by JonathanGiles** [comment]
This API also needs to be moved: https://github.com/Azure/azure-sdk-for-java/pull/5911#discussion_r337286386

**Comment by sima-zhu** [comment]
Working on this.

**Comment by conniey** [comment]
Do we expect users to call this? I was reading it in the java docs and couldn't understand why we need this in public view.

```java
    /**
     * Resource Supplier for UploadFile
     *
     * @param filePath The path for the file
     * @return {@code AsynchronousFileChannel}
     * @throws UncheckedIOException an input output exception.
     */
    protected AsynchronousFileChannel uploadFileResourceSupplier(String filePath) {}
```

**Comment by joshfree** [comment]
@amishra-dev I'm assigning this over to you to triage

**Comment by rickle-msft** [comment]
Unfortunately this wasn't brought in before GA and would be a breaking change now.
