### ISSUE TITLE
Move ParallelTransferOptions and ProgressReceiver into Storage Common

### ISSUE THREAD

**Issue by alzimmermsft** [Azure/azure-sdk-for-java#5966]
Move `ParallelTransferOptions` and `ProgressReceiver` into Storage Common as both are applicable to Storage Files when parallelization is added to it and progress reporting could be added to uploading methods.

**Comment by amishra-dev** [comment]
@alzimmermsft why?

**Comment by alzimmermsft** [comment]
Talking with @tg-msft and @JonathanGiles separately about these classes are applicable to both Blobs and Files and instead of duplicating the classes we should make them part of the common library for Storage.

**Comment by amishra-dev** [comment]
@alzimmermsft Lets do it in the future to stop breaking Gauri since this has no obvious immediate advantage

**Comment by alzimmermsft** [comment]
Closing this as this has been GA'd, API will not change.
