### ISSUE TITLE
[API] Storage: Method parameters should take Iterable over List

### ISSUE THREAD

**Issue by conniey** [Azure/azure-sdk-for-java#5968]
There are methods in Azure Storage that take a `List<T>` as method parameter rather than `Iterable<T>` or varargs. (Whichever makes the most sense from user perspective.)
For example: `BlockBlobClient.commitBlockList(List<String> base64BlockIds)` could be:
* `BlockBlobClient.commitBlockList(String... base64BlockIds)`
* One or two items, could be varargs? or if it is a set of items they may want to use later, Iterable.

**Comment by alzimmermsft** [comment]
A few APIs would become more difficult to use if they were switched to varargs or `Iterable`. Given that, and wanting to keep consistent with the generic types being used across the Storage SDKs, we will continue using `List`.
