### ISSUE TITLE
WebSite createOrUpdate not working - parameter properties has an invalid value

### ISSUE THREAD

**Issue by s-rusev** [Azure/azure-sdk-for-java#597]
Here is sample code for createOrUpdate of website which always returns "The parameter properties has an invalid value"

AzureWebSiteCreateOrUpdateParameters parameters = new AzureWebSiteCreateOrUpdateParameters();
AzureWebSiteBase web = new AzureWebSiteBase();

//web.name = "some-name";
//web.id = "/subscriptions/12345678-1234-5678-b694-8c110a417603/resourceGroups/resource-group-name/providers/Microsoft.Web/sites/some-name";

//this is required
web.location = "West Europe";

//web.type = 'Microsoft.Web/sites';

//properties 
//var props = new AzureWebSiteBaseProperties();
//props.serverFarm = "ServicePlan";
//web.properties = props;
//parameters.properties = properties;

//this is required
parameters.webSite = web;

websiteClient.getWebSitesOperations().createOrUpdate("resource-group-name", "some-name", null, parameters);

Result is:
{"Code":"BadRequest","Message":"The parameter properties has an invalid value.","Target":null,"Details":[{"Message":"The parameter properties has an invalid value."},{"Code":"BadRequest"},{"ErrorEntity":{"Code":"BadRequest","Message":"The parameter properties has an invalid value.","ExtendedCode":"51008","MessageTemplate":"The parameter {0} has an invalid value.","Parameters":["properties"],"InnerErrors":null}}],"Innererror":null}

Expected result - created web site.

**Comment by jianghaolu** [comment]
The `properties` on `WebSiteBase` is now required.

Here is a sample creating a website in ARM: https://github.com/Azure/azure-sdk-for-java/blob/master/resource-management/azure-mgmt-websites/src/test/java/com/microsoft/azure/management/websites/WebsiteOperationsTest.java#L66.

Thanks.

**Comment by bora89** [comment]
Guys where is the documentation on the `properties`? More that a year had passed, the link that you gave is 404 now. We have the same error, do not know how to deal with it: ![](http://joxi.ru/DrlXdnH459J5rP?d=1)

**Comment by yukfang** [comment]
Using Postman to do App Settings update:

Request:
PUT https://management.azure.com/subscriptions/856f5867-xxxx-4244-aba6-fcf296bd90e8/resourceGroups/xxxx/providers/Microsoft.Web/sites/xxx/config/web?api-version=2016-08-01

Content-Type: application/json
Authorization: Bearer xxxxTokenxxxxxx

Body:
{
    "alwaysOn" : true
}

Response: 400 BadRequest
{
    "Code": "BadRequest",
    "Message": "The parameter properties has an invalid value.",
    "Target": null,
    "Details": [
        {
            "Message": "The parameter properties has an invalid value."
        },
        {
            "Code": "BadRequest"
        },
        {
            "ErrorEntity": {
                "ExtendedCode": "51008",
                "MessageTemplate": "The parameter {0} has an invalid value.",
                "Parameters": [
                    "properties"
                ],
                "Code": "BadRequest",
                "Message": "The parameter properties has an invalid value."
            }
        }
    ],
    "Innererror": null
}


Any idea on how to resolve it?

**Comment by codenesium** [comment]
In case anyone else gets here from google to create an app using the REST API you have to add the properties element with a blank array even though it's not marked as required.

`{
	location: "centralus",
        properties: {}
}`

This is pretty dumb since the first thing most people will try is to create an application and there is no way to know why this is broken from the API tester at [](https://docs.microsoft.com/en-us/rest/api/appservice/webapps/createorupdate)

I found the solution at [](https://github.com/Azure/azure-sdk-for-python/issues/749)
