### ISSUE TITLE
Blocks Preview 5 ADLS: Missing API - PagedIterable map function to return a PagedIterable 

### ISSUE THREAD

**Issue by gapra-msft** [Azure/azure-sdk-for-java#5971]
Related to issue #5825
Storage needs a way to go from a PagedIterable of A to a PagedIterable of C to implement DataLake features.

Some datalake APIs (that are a separate namespace from blobs) call directly into blob APIs (ex: listBlobContainers) that returns a PagedIterable of BlobContainerItems.

To make the namespace for a user consistent, we need to be able to return a PagedIterable of SomeOtherItem.

For example,
```
    public PagedIterable<FileSystemItem> listFileSystems(ListFileSystemsOptions options, Duration timeout) {
        return blobServiceClient.listBlobContainers(Transforms.toListBlobContainersOptions(options), timeout).to(blobContainerItem -> Transforms.toFileSystemItem(blobContainerItem));
    }
```

**Comment by joshfree** [comment]
@srnagar will own investigating this, similar to #5825
