### ISSUE TITLE
Storage: Modules support missing in azure-storage-file-datalake

### ISSUE THREAD

**Issue by conniey** [Azure/azure-sdk-for-java#5973]
Modules support for JDK 9+ should be added. (ie. module-info.java)

**Comment by alzimmermsft** [comment]
@gapra-msft Should this issue be associated to and fix by the datalake PR?

**Comment by gapra-msft** [comment]
@alzimmermsft  Will put a PR out for this soon

**Comment by alzimmermsft** [comment]
@gapra-msft I believe you've done this, so this issue can be closed.
