### ISSUE TITLE
[BUG] StorageStudy report

### ISSUE THREAD

**Issue by helayoty** [Azure/azure-sdk-for-java#5976]
**Describe the bug**

I've joint the SDK Team in a one-day hack and I've completed the Storage study and would like to share the result with the team.

***Exception or Stack Trace***

All study went very well except a few comments that I'll state them below:

- task1: 
   - Documentation (different preview versions) was the reason I took that time to finish
    - Function name doesn't describe the functionality well

- task3c:
    - What is the need for this test in storage study?
    - Why don't we have a method to return and display the specific byte directly?

- task4:
   -  The sample [here](https://github.com/Azure/azure-sdk-for-java/blob/99fee6293ddc45b4666dba4fdba16fd697157e75/sdk/storage/azure-storage-blob/src/samples/java/com/azure/storage/blob/BasicExample.java)  , line 62  has getBlobContainerClient taking a container name + time. why?

- task6: 
    - It wasn't clear if I need to use block async to upload or just copy URL

**To Reproduce**
NA

***Code Snippet***

Here is the link to StorageStudy [class](https://gist.github.com/helayoty/a5a91829a038ef078f9e784004609af8#file-storagestudy-java) as well as the [pom](https://gist.github.com/helayoty/a5a91829a038ef078f9e784004609af8#file-pom-xml) file

**Expected behavior**

Everything went as expected 

**Screenshots**
NA

**Setup (please complete the following information):**
 - OS: [Windows 10]
 - IDE : [IntelliJ]
 - Version of the Library used: 12.0.0-preview.4

**Additional context**
NA

**Information Checklist**
Kindly make sure that you have added all the following information above and checkoff the required fields otherwise we will treat the issuer as an incomplete report
- [X ] Bug Description Added
- [ ] Repro Steps Added
- [ ] Setup information Added

**Comment by maggiepint** [comment]
Hey Heba! Thanks for all the work you put into this. @alzimmermsft - Heba walked our user studies for us at the last open source hacakthon and has some points of feedback that I think should probably be broken into multiple work items. Do you want to handle this or would you like my help?

**Comment by gapra-msft** [comment]
Closing due to GAing the libraries.
