### ISSUE TITLE
How to fetch all the available Azure VM Images/templates details? Some virtualMachineVMImage are missing

### ISSUE THREAD

**Issue by ssuriya** [Azure/azure-sdk-for-java#598]
Hi,

I'm using the below code (computeManagementClient.getVirtualMachineVMImagesOperations().list())  to fetch all the VM Images, but I can't find few images in the response, for example no images of Ubuntu is fetched. Am i missing something or is it a bug?

```
Configuration config = ManagementConfiguration.configure(new URI(uri), subscriptionId, keyStoreLocation, keyStorePassword, KeyStoreType.pkcs12);

ComputeManagementClient computeManagementClient = ComputeManagementService.create(config);

VirtualMachineVMImageListResponse virtualMachineImageListResponse = computeManagementClient.getVirtualMachineVMImagesOperations().list();
if(virtualMachineImageListResponse.getStatusCode() != 200){
     	System.out.println("Bad status code returned for the requrest");
      	return;
}

ArrayList<VirtualMachineVMImageListResponse.VirtualMachineVMImage> virtualMachineVMImagelist = virtualMachineImageListResponse.getVMImages();
for (VirtualMachineVMImageListResponse.VirtualMachineVMImage virtualMachineVMImage : virtualMachineVMImagelist)              
{
       	System.out.println(virtualMachineVMImage.getName());
       	System.out.println("\t" + virtualMachineVMImage.getOSDiskConfiguration().getName());
       	System.out.println("\t" + virtualMachineVMImage.getImageFamily());
       	System.out.println("\t" + virtualMachineVMImage.getLabel());
}
```

Thanks & Regards,
-Sakthi

**Comment by ssuriya** [comment]
I can see all the VM images with Get-AzureVMImage cmdlet. but not through the below REST API either

`https://management.core.windows.net/<subscription-id>/services/vmimages`

are there any other alternate APIs?

**Comment by jianghaolu** [comment]
If you add `-Debug` to the PowerShell command `Get-AzureVMImages` you will find out that the cmdlet is essentially calling 2 APIs
`https://management.core.windows.net/<subscription-id>/services/images` and
`https://management.core.windows.net/<subscription-id>/services/vmimages`
and returning the joined list.

In the case of Java, that would be
`computeClient.getVirtualMachineOSImagesOperations().list()` joined with
`computeClient.getVirtualMachineVMImagesOperations().list().

Thanks.

**Comment by ssuriya** [comment]
Thanks!
alternatively I was monitoring with Fiddler tool.

Cheers.
