### ISSUE TITLE
VM createOrUpdate does not work.

### ISSUE THREAD

**Issue by m-moris** [Azure/azure-sdk-for-java#600]
I'm facing a critical problem in Java SDK 0.9.3.

For example, I'm changing vm size, I got a exception and following message.

> com.microsoft.windowsazure.exception.ServiceException: InvalidRequestContent: The request content was invalid and could not be deserialized: 'Could not find member 'resources' on object of type 'ResourceDefinition'. Path 'resources', line 1, position 1834.'.

And example code.
```
VirtualMachine vm = client.getVirtualMachinesOperations().get(rg, vmName)).getVirtualMachine();
vm.getHardwareProfile().setVirtualMachineSize("Standard_A3");
client.getVirtualMachinesOperations().createOrUpdate(rg, vm);
```

**Comment by jianghaolu** [comment]
The `Extensions` property is read-only.
Call `vm.setExtensions(null)` before calling `createOrUpdate` should resolve the problem.

Thanks.

**Comment by m-moris** [comment]
Thank you for your great information. 
I tried this workaround and I could change the VM size! 

But, I did not change my Java programs, and I suddenly got the exception. 
Were there any change API in a few weeks ago?

**Comment by jianghaolu** [comment]
ARM compute in the `master` branch has not been updated for a while. It looks like a server-side reinforcement.

@xindzhan Do you know if this is expected? I personally feel like `createOrUpdate()` should accept the result from `get()`.

**Comment by m-moris** [comment]
Hi @jianghaolu 

This workaround is a little bit difficult for those who do not know.
Do you have any plan to change the SDK about this problem? 

Ex)
 - Extension property don't ouput to JSON in `createOrupdate` 
 - If Extensions is not NULL, raise exception.

**Comment by xindzhan** [comment]
@mahthi

**Comment by jianghaolu** [comment]
Yes, I'll implement something similar to https://github.com/Azure/autorest/blob/master/ClientRuntimes/CSharp/Microsoft.Rest.ClientRuntime/Serialization/ReadOnlyJsonContractResolver.cs. 

@xindzhan, looks like this is actually more common than I expect:

> A nice thing to do if you choose this option would be to send back a 200 (OK) with the actual updated entity in the response, so that clients can clearly see that the read-only fields were not updated.
>
>There are certainly some people who think the other way - that it should be an error to attempt to update a read-only portion of a resource. There is some justification for this, primarily on the basis that you would definitely return an error if the entire resource was read-only and the user tried to update it. It definitely goes against the robustness principle, but you might consider it to be more "self-documenting" for users of your API.

(from http://programmers.stackexchange.com/questions/208271/how-should-a-rest-api-handle-put-requests-to-partially-modifiable-resources)

**Comment by m-moris** [comment]
Thank you, I expect the SDK will be fixed ASAP!!

BTW, I may have misunderstood it. The VM might don't have extensions. So it look like working properly. But the VM is already removed, I cannot confirm :<
