### ISSUE TITLE
App Configuration - List revision with invalid range tests failing

### ISSUE THREAD

**Issue by srnagar** [Azure/azure-sdk-for-java#6008]
Investigate why list revision with invalid range test is failing. Currently, this test is ignored.

https://github.com/Azure/azure-sdk-for-java/blob/master/sdk/appconfiguration/azure-data-appconfiguration/src/test/java/com/azure/data/appconfiguration/ConfigurationClientTestBase.java#L375

**Comment by mssfang** [comment]
Range will be remove from SDK. So it will no longer be an issue
