### ISSUE TITLE
Issues with obtaining APIM schemas

### ISSUE THREAD

**Issue by d2baker** [Azure/azure-sdk-for-java#6026]
![azure-apim-api-export-options](https://user-images.githubusercontent.com/55718609/67506781-8a4bab00-f642-11e9-9488-cc443937a6e8.PNG)

In the Azure portal in APIM API -> Exports, there are a few listed options to get different schema representations, (A) OpenAPI v2 json (Swagger), (B) OpenAPI v3 yaml, (C) OpenAPI v3 json, (D) WADL, (E) WSDL
So when I select each of these options, I am able to download the expected representation as a file.
I assume this is presented as a Media-Type in something similar to application/octet-stream, so it's a matter of saving the response as a file.
I would expect the same options would be available within the Azure SDK, directly returning the representations for each of the cases.
So there is one path using apiManagementManager.inner().apiExports().get(resourceGroupName, serviceName, apiId, format).
This returns links for A,B,D but not for C. 
Also this is inefficient as it returns a link to download the schemas, so an additional call needs to be made to download the schema. I would like to get the representation directly.
In debugging, the call accepts the REST API formats, swagger, openapi, openapi+json, and wadl -  if I put those values into an ExportFormat it never returns anything because the returned content does not get unmarshalled / translated to an ApiExportResultInner instance as it only accepts links from the internal response, and not the underlying schema representation. So although it makes a successful call internally and returns the content, it is never returned to the user. So the current path using apiExports is incomplete, and inefficient.

As an alternative I chose apiManagementManager.inner().apiSchemas().get(resourceGroupName, serviceName, apiId, schemaId).
This again is awkward, as I have no idea what the schemaId would be. So I turned to  apiSchemas().listByApi path to get the guid name of the schemas that are available and then have to make another call to see what is returned by using the guid name. In my case, it only came back with one entry, and when I used that as a schemaId in the apiSchemas().get() call, the response content was some sort of proprietary Microsoft media type (application/vnd.ms-azure-apim.swagger.definitions+json). I did not see any of the expected representations listed in the Azure portal UI... 

So what path would I need to use, directly preferably, to get the schema representations?
The apiExports path at best was incomplete and inefficient, and the apiSchemas path did not satisfy my expectations at all.

**Comment by yungezz** [comment]
add @weidongxu-microsoft to have a look.
