### ISSUE TITLE
[Storage] uploadFromFile() small blobs: throughput regression between v8 and v12

### ISSUE THREAD

**Issue by amishra-dev** [Azure/azure-sdk-for-java#6028]
**Describe the bug**
Email thread about perf from Mike

10 KB | 32 | UploadFromFile | 3668 | 875 | 24%
-- | -- | -- | -- | -- | --

**Expected behavior**
atleast within 90% of track 1 since 10kb blobs are majority of the blobs uploaded

This can be a shared investigation between Rick/James and Mike
@joshfree @pemari-msft  fyi

**Comment by mikeharder** [comment]
This also applies to the async UploadFromFile (which is expected since sync just wraps the async codepath).
