### ISSUE TITLE
Reuse connection for each receive call connection to Service Bus

### ISSUE THREAD

**Issue by elekesa** [Azure/azure-sdk-for-java#603]
Currently Java SDK creates a new HTTP connection to the Service Bus for each receive call.
This is causing high latency in receiving time, when using the same partition id.

Could we implement to reuse the HTTP connection for all receive calls?

Thanks.

**Comment by alvadb** [comment]
the service bus client library is not in this repo anymore, so if this is still an issue, it should go there:
https://github.com/azure/azure-service-bus-java
