### ISSUE TITLE
ReliableDownloadOptions has incorrect method names

### ISSUE THREAD

**Issue by JonathanGiles** [Azure/azure-sdk-for-java#6032]
Missing the 'set' / 'get' prefixes here: https://github.com/Azure/azure-sdk-for-java/blob/master/sdk/storage/azure-storage-blob/src/main/java/com/azure/storage/blob/models/ReliableDownloadOptions.java

**Comment by Petermarcu** [comment]
Why isn't the download method reliable?

**Comment by JonathanGiles** [comment]
:-) I made the same bad joke...

**Comment by JonathanGiles** [comment]
I'm fixing now, btw.

**Comment by Petermarcu** [comment]
Fixing Download to be reliable?
