### ISSUE TITLE
Cosmos emulator script cleanup

### ISSUE THREAD

**Issue by danieljurek** [Azure/azure-sdk-for-java#6034]
Use the cosmos emulator script available at: https://github.com/Azure/azure-sdk-tools/blob/master/eng/pipelines/templates/steps/cosmos-emulator.yml

(see example at: https://github.com/Azure/azure-sdk-for-python/blob/master/eng/pipelines/templates/stages/cosmos-sdk-client.yml#L31)

**Comment by weshaggard** [comment]
@mitchdenny I believe you completed this work correct?

**Comment by alzimmermsft** [comment]
Given that this has moved into `eng/common` I'm going to close this issue as this is no longer managed by the Azure SDK for Java repo.
