### ISSUE TITLE
Redesign the Poller

### ISSUE THREAD

**Issue by anuchandy** [Azure/azure-sdk-for-java#6036]
While doing testing of Poller in various services, we encountered couples of reliability issues with the current implementation. See following - 

https://github.com/Azure/azure-sdk-for-java/issues/5923
https://github.com/Azure/azure-sdk-for-java/issues/5809
https://github.com/Azure/azure-sdk-for-java/issues/5805

We are reworking poller to split the sync and async behavior and at the sometime ensuring that all features described in the generic Poller design guidelines are enabled and followed. We're also killing the multi-casting features which are not used in majority of the customer scenarios, but customers can still enable it by simply using a standard reactor operator.

**Comment by anuchandy** [comment]
The draft is in progress https://github.com/Azure/azure-sdk-for-java/pull/5987 and close to completion, planning to get it in by early tomorrow (FridayOct/25) Each SDK owners (using poller) will be helping testing specialized implementation of Poller in the context of their service.

**Comment by anuchandy** [comment]
The work is done, PR is ready to merge - https://github.com/Azure/azure-sdk-for-java/pull/5987

**Comment by joshfree** [comment]
Closing issue as the PR has been merged.
