### ISSUE TITLE
Missing library level README.md files

### ISSUE THREAD

**Issue by JimSuplizio** [Azure/azure-sdk-for-java#6047]
As part of the versioned documentation work I'm adding the contents of the README.md to the overview page which is the landing page for a given library (ex. https://azuresdkdocs.blob.core.windows.net/$web/java/azure-core/1.0.0-preview.7/index.html). There were a number of libraries that don't have library level README.md files. To be clear, this doesn't affect doc creation it's just that having a Description, Getting Started, the Maven dependency POM snippet, Additional Documentation, Contributing, etc. on the landing page for a given library is pretty convenient for a developer.

Client
1.	com.azure:azure-core-management;1.0.0-preview.7;1.0.0-preview.7
2.	com.azure:azure-storage-common;12.0.0-preview.5;12.0.0-preview.5
3.	com.azure:azure-storage-queue-cryptography;12.0.0-preview.5;12.0.0-preview.5
 
Data
1.	com.microsoft.azure.cognitiveservices:azure-cognitiveservices-spellcheck;1.1.0-preview.1;1.1.0-preview.1
2.	com.microsoft.azure.cognitiveservices:azure-cognitiveservices-textanalytics;1.1.0-preview.1;1.1.0-preview.1
3.	com.microsoft.azure.cognitiveservices:azure-cognitiveservices-luis-runtime;1.1.0-preview.1;1.1.0-preview.1
4.	com.microsoft.azure.cognitiveservices:azure-cognitiveservices-luis-authoring;1.1.0-preview.1;1.1.0-preview.1
5.	com.microsoft.azure.cognitiveservices:azure-cognitiveservices-autosuggest;1.1.0-preview.1;1.1.0-preview.1
6.	com.microsoft.azure.cognitiveservices:azure-cognitiveservices-customimagesearch;1.1.0-preview.1;1.1.0-preview.1
7.	com.microsoft.azure.cognitiveservices:azure-cognitiveservices-customsearch;1.1.0-preview.1;1.1.0-preview.1
8.	com.microsoft.azure.cognitiveservices:azure-cognitiveservices-entitysearch;1.1.0-preview.1;1.1.0-preview.1
9.	com.microsoft.azure.cognitiveservices:azure-cognitiveservices-imagesearch;1.1.0-preview.1;1.1.0-preview.1
10.	com.microsoft.azure.cognitiveservices:azure-cognitiveservices-inkrecognizer;1.0.0-preview.1;1.0.0-preview.1
11.	com.microsoft.azure.cognitiveservices:azure-cognitiveservices-newssearch;1.1.0-preview.1;1.1.0-preview.1
12.	com.microsoft.azure.cognitiveservices:azure-cognitiveservices-videosearch;1.1.0-preview.1;1.1.0-preview.1
13.	com.microsoft.azure.cognitiveservices:azure-cognitiveservices-visualsearch;1.1.0-preview.1;1.1.0-preview.1
14.	com.microsoft.azure.cognitiveservices:azure-cognitiveservices-websearch;1.1.0-preview.1;1.1.0-preview.1
15.	com.microsoft.azure.cognitiveservices:azure-cognitiveservices-computervision;1.1.0-preview.1;1.1.0-preview.1
16.	com.microsoft.azure.cognitiveservices:azure-cognitiveservices-contentmoderator;1.1.0-preview.1;1.1.0-preview.1
17.	com.microsoft.azure.cognitiveservices:azure-cognitiveservices-customvision-prediction;1.1.0-preview.3;1.1.0-preview.3
18.	com.microsoft.azure.cognitiveservices:azure-cognitiveservices-customvision-training;1.1.0-preview.3;1.1.0-preview.3
19.	com.microsoft.azure.cognitiveservices:azure-cognitiveservices-faceapi;1.1.0-preview.1;1.1.0-preview.1
There's a README.md at the root level of the azure-sdk-for-java\sdk\cosmos directory but only azure-cosmos-examples has one sitting next to its pom
20.	com.microsoft.azure:azure-cosmos;3.3.1;3.4.0
21.	com.microsoft.azure:azure-cosmos-benchmark;3.3.1;3.4.0
22.	com.microsoft.azure:azure-cosmos-examples;3.3.1;3.4.0
23.	com.microsoft.azure:azure-eventhubs;3.1.0;3.1.0
24.	com.microsoft.azure:azure-eventhubs-extensions;3.1.0;3.1.0
There's a README.md at the root level azure-sdk-for-java\sdk\keyvault which is a bit odd since it looks to be data specific and there are subdirectories for both client/data tracks
25.	com.microsoft.azure:azure-keyvault;1.2.3;1.2.3
26.	com.microsoft.azure:azure-keyvault-complete;1.2.3;1.2.3
27.	com.microsoft.azure:azure-keyvault-core;1.2.3;1.2.3
28.	com.microsoft.azure:azure-keyvault-cryptography;1.2.2;1.2.3
29.	com.microsoft.azure:azure-keyvault-extensions;1.2.3;1.2.3
30.	com.microsoft.azure:azure-keyvault-test;1.2.3;1.2.3
31.	com.microsoft.azure:azure-keyvault-webkey;1.2.3;1.2.3
There's a readme at root level for azure-sdk-for-java\sdk\servicebus
32.	com.microsoft.azure:azure-servicebus;3.1.1;3.1.1
33.	com.microsoft.azure:azure-media;1.0.0-preview.1;1.0.0-preview.1

**Comment by hemanttanwar** [comment]
I have added these missing README.
https://github.com/Azure/azure-sdk-for-java/pull/6444
Please confirm before I close this, if  anything else is pending ? @JimSuplizio

**Comment by kaerm** [comment]
@hemanttanwar I think this is about specific library READMEs rather than the service level ones. @JimSuplizio can probably confirm

**Comment by hemanttanwar** [comment]
@JimSuplizio @kaerm 
I am wondering , Do we also need to write README for track1 `com.microsoft.azure**`  ?  One example from list above `com.microsoft.azure.cognitiveservices:azure-cognitiveservices-spellcheck;`  

Since our team managing track 2 .

**Comment by kaerm** [comment]
Yea, these should've been autogenerated not written by us. I am not entirely sure why they're missing

**Comment by joshfree** [comment]
Closing old issue
