### ISSUE TITLE
Run security checks on internal pipeline

### ISSUE THREAD

**Issue by srnagar** [Azure/azure-sdk-for-java#6055]
We would like to periodically run security checks to identify vulnerabilities reported for any of the dependencies used in Java SDK. I manually ran the maven command below to identify a couple of libraries that were reported. One of them had a newer version that fixed it and the other was a false positive. So, for now, we have no known issues but we’d like to automate this process. is it possible to have this run in an internal pipeline daily and flag issues? Please let me know if you need additional details.
 
Maven command:
`mvn dependency-check:check -f pom.client.xml`
 
Maven plugin:

```xml
<plugin>
  <groupId>org.owasp</groupId>
  <artifactId>dependency-check-maven</artifactId>
  <version>5.2.2</version>
  <executions>
       <execution>
             <goals>
                  <goal>check</goal>
             </goals>
       </execution>
  </executions>
</plugin>
```

**Comment by mitchdenny** [comment]
Pick this one up from Jim.

**Comment by JimSuplizio** [comment]
/CC @joshfree @kurtzeborn @weshaggard @mitchdenny 

@srnagar I think this tool would need more experimentation/investigation by the Java team and a decision would need to be made, after that, of whether or not to pursue things further. I've played around with it for a couple of hours this morning and just the command line above isn't enough. 
- This tool generates reports and it seems that they'd need to get published somewhere private. While using the dependency-check:aggregate would cause output to be in the logs, it's not nearly as useful as the report which would at least show the chain that would bring a problematic dependency in if it's not direct dependency.
- There's some kind of weird analyzer dependency and the setup is more than just what's listed above. Every time the tool runs, it seems to be trying to invoke the a dotnet analyzer tool and spits out the following error:
`[ERROR] ----------------------------------------------------
[ERROR] .NET Assembly Analyzer could not be initialized and at least one 'exe' or 'dll' was scanned. The 'dotnet' executable could not be found on the path; either disable the Assembly Analyzer or configure the path dotnet core.
[ERROR] ----------------------------------------------------`
- This tool comes with a usage warning at the top of its documentation that states "It is important to understand that the first time this task is executed it may take 20 minutes or more as it downloads and processes the data from the National Vulnerability Database (NVD) hosted by NIST: https://nvd.nist.gov" Being that every run in our build system is technically a "first time" if we were going to add this it would end up being added in aggregate pipeline that we're going to be creating. 

My $.02 here is that, overall, I'm not convinced that this tool is entirely necessary. We already have a governance tool which is running as part of the Analyze step in the internal pipelines (the display name is **Component Detection**). From our conversation, apparently this tool had missed a vulnerability in the past however I think we would be better served to give them input/file issues so they can improve the internal MS tool, one which we do not have to own or maintain and that also needs to get run anyways.

Right now I'm going to remove @mitchdenny and myself from the assignees and add client to the labels.

**Comment by alzimmermsft** [comment]
There is a nightly run which performs this task for the entirety of the repository now.
