### ISSUE TITLE
Unable to fetch 1.0 snapshots from adxsnapshots.azurewebsites.net

### ISSUE THREAD

**Issue by dtretyakov** [Azure/azure-sdk-for-java#606]
It looks that http://adxsnapshots.azurewebsites.net/ was updated and it causes compilation errors like this:
```
> Could not find com.microsoft.azure:azure-mgmt-compute:1.0.0-SNAPSHOT.
  Searched in the following locations:
      http://adxsnapshots.azurewebsites.net/com/microsoft/azure/azure-mgmt-compute/1.0.0-SNAPSHOT/maven-metadata.xml
      http://adxsnapshots.azurewebsites.net/com/microsoft/azure/azure-mgmt-compute/1.0.0-SNAPSHOT/azure-mgmt-compute-1.0.0-SNAPSHOT.pom
      http://adxsnapshots.azurewebsites.net/com/microsoft/azure/azure-mgmt-compute/1.0.0-SNAPSHOT/azure-mgmt-compute-1.0.0-SNAPSHOT.jar
```

Could you please update [README.md](https://github.com/Azure/azure-sdk-for-java/blob/autorest/README.md) page in the branch `autorest` to reflect current `http://adxsnapshots.azurewebsites.net/repo` maven repository url?

**Comment by jianghaolu** [comment]
Hi @dtretyakov  Sorry for the unplanned outage, it should be fixed by now (without /repo). 

BTW, as 1.0.0-beta1 has been release, you should be able to get it from maven central. I'll update the README soon.
