### ISSUE TITLE
[Docs] Azure.Identity Conceptual Topic Docs (with language-specific code samples)

### ISSUE THREAD

**Issue by joshfree** [Azure/azure-sdk-for-java#6062]
This is a tracking item to finish writing Conceptual Documentation for Identity before the November SDK update.

This is something @ellismg began last week, but it needs to be expanded with language-specific code samples as well.

/cc: @schaabs

**Comment by joshfree** [comment]
Per offline discussion, this conceptual docs will be PR'd to all 4 repos and each language-specific package owner will fill-in the language-specific portion in the markdown / docs

**Comment by joshfree** [comment]
@ellismg can you please give an update on the conceptual doc for Identity?

**Comment by joshfree** [comment]
Moving this to the January milestone. /cc @ellismg

**Comment by joshfree** [comment]
@jianghaolu is there any remaining open work tracked by this issue or can it now be closed since you've done a bunch of doc work earlier this semester?

**Comment by jianghaolu** [comment]
We can continue to use this to track the updates needed for 1.1.0 release.

**Comment by joshfree** [comment]
@jianghaolu now that the August 2020 release is out, what work remains here?

**Comment by g2vinay** [comment]
closing this as the docs are up to date.
