### ISSUE TITLE
get NPE while getting Queue Info

### ISSUE THREAD

**Issue by boly38** [Azure/azure-sdk-for-java#607]
Hi all,
 I'm trying to get Azure Queue message count and I got NullPointerException.

version used:

```
    <groupId>com.microsoft.azure</groupId>
   <artifactId>azure-servicebus</artifactId>
    <version>0.9.3</version>
```

my code is 

```
 GetQueueResult queueRez = service.getQueue(physMgtQueue);
            if (queueRez != null && queueRez.getValue() != null) {
                QueueInfo queueInfo = queueRez.getValue();
                Long messageCount = queueInfo.getMessageCount();
        log.info("queue has {} messages", messageCount);
            }
```

Error logs

```
java.lang.NullPointerException
    at com.microsoft.windowsazure.services.servicebus.models.QueueInfo.getMessageCount(QueueInfo.java:374)
```

related integration test (your side): `ServiceBusIntegrationTest::getQueueMessageCountDetails()`

delta from my case: queue is not created
- QueueInfo:: model attribute is null

Maybe instead of NPE, It could be better to have an exception ("queue doesn't exist" or similar).

regards

**Comment by boly38** [comment]
update my use case: in fact the queue is missing :)

**Comment by boly38** [comment]
In addition, seems like from client point of view, the better way to check if a queue exist or not is the following code:

```
            GetQueueResult queueRez = service.getQueue(myQueueName);
            QueueInfo queueInfo = queueRez != null ? queueRez.getValue() : null;
            boolean myQueueIsHere = (queueInfo.getModel() != null);

```

Let me know if there is a shortest way. Thks

**Comment by jianghaolu** [comment]
The service bus client library is moved to https://github.com/Azure/azure-service-bus-java. If this is still an issue, please file it there. Thanks!
