### ISSUE TITLE
Leaked Connection warning from OkHttp3

### ISSUE THREAD

**Issue by scotmoor** [Azure/azure-sdk-for-java#608]
Using Azure SDK for Java 1.0 from http://adxsnapshots.azurewebsites.net

We're seeing the following warning show up in our output log after moving to the Azure SDK 1.0:

2016-03-03 14:57:06.973  WARN 10848 --- [ ConnectionPool] okhttp3.OkHttpClient                     : A connection to https://management.azure.com/ was leaked. Did you forget to close a response body?

I've attached a file with the output captured after setting the HttpLoggingInterceptor.Level to BODY.

[OkHttp3_output.txt](https://github.com/Azure/azure-sdk-for-java/files/157842/OkHttp3_output.txt)

**Comment by martinsawicki** [comment]
obsolete - we'll most likely be moving away from OkHttp in the near future
