### ISSUE TITLE
Cannot defer a message using the Azure Service Bus QueueClient Java API

### ISSUE THREAD

**Issue by richard-hunt** [Azure/azure-sdk-for-java#6081]
I'm working with an auto-wired QueueClient instance in a Spring Boot application, taking advantage of azure-servicebus-spring-boot-starter and am trying to figure out how I can defer a message.  I can see that MessageReciever exposes defer() operations but these are not exposed by QueueClient (the methods exist but are not public, and have been commented out of the IMessageAndSessionPump interface). 

What is the reasoning behind not exposing defer() and what are my options?  Can I safely invoke defer() on an independently constructed MessageReceiver instance using the lock token from a message received by my QueueClient instance?  Or do I need to move away from QueueClient completely if I want to take advantage of message deferral?

Thanks in advance!

**Comment by jfggdl** [comment]
@richard-hunt, thank you for creating this issue. @axisc is working on providing you with an answer.

**Comment by axisc** [comment]
@richard-hunt 

To leverage message deferral, you must use MessageReceiver. The QueueClient (and subscriptionClient) is meant to setup a messagehandler.

Additionally, you can receive deferred messages only with the MessageReceiver, so we wanted to make sure that the functionality is baked into MessageReceiver and not QueueClient.

**Comment by richard-hunt** [comment]
OK, thanks for the feedback, I'll look into setting up a MessageReceiver instance instead of a QueueClient.
