### ISSUE TITLE
[Storage] Add API BlobClient.upload(InputStream, length)

### ISSUE THREAD

**Issue by mikeharder** [Azure/azure-sdk-for-java#6089]
Track 1 provides the following API which automatically switches between single-put and stage-block upload based on the length:

```java
CloudBlockBlob.upload(InputStream, long length)
```

For customers migrating from Track 1 to Track 2, I think we should provide a synchronous API as similar as possible.  Currently in Track 2, there is no way to synchronously upload a stream of arbitrary size with good performance for small blobs.  The only option is `BlockBlobClient.getBlobOutputStream()`, which is both more complicated to use and has poor performance for small blobs.

The implementation can simply call into the existing sync APIs:

```java
public void BlobClient.upload(InputStream inputStream, long length) {
    BlockBlobClient blockBlobClient = this.getBlockBlobClient();
    if (length < singlePutMaximum) {
        return blockBlobClient.upload(inputStream, length);
    }
    else {
        BlobOutputStream blobOutputStream = blockBlobClient.getBlobOutputStream();
        inputStream.transferTo(blobOutputStream);
        blobOutputStream.close();
    }
}
```

Related: https://github.com/Azure/azure-sdk-for-java/issues/5275

CC: @rickle-msft

**Comment by rickle-msft** [comment]
I agree that this would make migration easier and more intuitive. I'm ok with this addition.
