### ISSUE TITLE
Java November 2019 Release Notes should be reviewed and updated

### ISSUE THREAD

**Issue by joshfree** [Azure/azure-sdk-for-java#6093]
The Java November release notes need to be spot checked and updated https://github.com/Azure/azure-sdk/blob/master/releases/2019-11/2019-11-java.md

1) File -> File.Share rename
2) AppConfig should be marked preview
3) The opening paragraph says this is a preview release when it should just be "November 2019 SDK Update"

**Comment by joshfree** [comment]
Related https://github.com/Azure/azure-sdk/commit/3d3077f50e86553aa2f89e818bb79387e9b7ff24#diff-cc6bd9f1dffce09c988c5a343ce592b0

**Comment by srnagar** [comment]
- Changelog contains changes done in the previous preview.
- Changelog does not include azure-core, azure-identity, appconfig
- Table at the top doesn't look right:
   - titles are all lowercase
   - tags should include a few more relevant tags (java is too generic)
   - sidebar column has releases_sidebar (should this be hyperlink?)
   - repository and permalink are not hyperlinked
- The maven dependency section has a whole bunch of dependencies specified without calling out which Azure service they map to (although readers can guess from the artifact id).
- `Needs help` section has "tutorials/samples" link that doesn't have relevant documentation for this release.

**Comment by hemanttanwar** [comment]
https://github.com/Azure/azure-sdk/commit/c689f7c2712f353488dcd4ebbd6b5ee88c74aee4

**Comment by joshfree** [comment]
@hemanttanwar are there any remaining follow ups captured here that you haven't fixed at this point?

**Comment by hemanttanwar** [comment]
https://github.com/Azure/azure-sdk-for-java/pull/6444
