### ISSUE TITLE
Support for Digest authenticated proxy

### ISSUE THREAD

**Issue by srnagar** [Azure/azure-sdk-for-java#6109]
azure-core does not support digest authenticated proxy. This may additionally require changes in azure-identity.

Related customer-reported issue - https://github.com/Azure/azure-sdk-for-java/issues/5372

**Comment by joshfree** [comment]
Moving this to the January milestone

**Comment by alzimmermsft** [comment]
**Current State of Authenticate Support**
_In regards to Basic and Digest authenticate_

The two HTTP client implementations which we release, based on OkHttp and Reactor Netty, only have support for Basic Authenticate challenges. This is deeply integrated into the construction of the HTTP client when passed `ProxyOptions` which contain a username and password used to fulfill the challenge.

OkHttp and Reactor Netty do not have native support for Digest Authenticate challenges.

**Proposal**

**1. Implement Digest Handling in Netty and OkHttp HTTP Clients**

This would allow for a tighter coupling of HTTP client and handling authentication challenges, with respect to Basic and Digest. This may allow for some optimization where Azure Core doesn't need to handle deserialization before a response to the challenge is made, additionally these HTTP clients already accept `ProxyOptions` which contains all the information needed to handle both Basic and Digest challenges resulting in no major changes to our API. This has the downside of potential code duplication or the creation of a new helper class which handles Basic and Digest authentication challenges.

There is a few questions around this direction which need to be answered.

- Does Reactor Netty have an interface which handles dealing with authenticate challenges, OkHttp has an interface for this which is already implemented to handle Basic.
- Does the response for successful authentication flow through this code path? RFC 7616 indicates that a server may respond with a `Authentication-Info` header which may include a new nonce to use upon subsequent authenticate challenges.

**2. Implement HttpPipelinePolicies to Handle Authenticate Challenges**

This would allow for a generic implementation that would support any HTTP client implementation being used, including non-Netty or non-OkHttp implementations. It has a downside that the response needs to be deserialized by Azure Core before a response to a challenge can be made. Unlike option 1 this does have the ability to snoop the response from the challenge and may attempt to retrieve a `Authentication-Info` header to handle subsequent challenges properly.

**Comment by alzimmermsft** [comment]
@amishra-dev What are the exact requirements for digest authentication support? I have a rough implementation completed which I am trying to hook into our `HttpClient` implementations, there are a few pain points around supporting the `-sess` based algorithms mentioned in RFC 2617 and 7616 as they require passing the complete HTTP entity (entity headers plus request body) into the digest.

**Comment by amishra-dev** [comment]
@alzimmermsft I have a setup that I can share with you to test. we just used squid proxy and enabled digest auth in that. I will forward you the mail where the customer lists what they need.
