### ISSUE TITLE
[BUG] queryItems falsely returns an empty response

### ISSUE THREAD

**Issue by f-paulus** [Azure/azure-sdk-for-java#6115]
**Describe the bug**
Often, when calling 'CosmosContainer#queryItems', we falsely get an empty result.

These are properties of the `FeedResponse` that we assume as a prerequisite for this to happen:
- cross-partition query
- max-item count is set
- The query contains a date range: `SELECT * FROM c WHERE ((c.metaData.dateA BETWEEN "2019-10-25T00:00:00.000Z" AND "2019-10-30T00:00:00.000Z") OR (c.metaData.dateB BETWEEN "2019-10-25T00:00:00.000Z" AND "2019-10-30T00:00:00.000Z")) AND [...]`

The result is often empty for our DB instance when it shouldn't. The continuation-token is set in the resulting feed response, but using it for the next query does again return an empty result list.

Another problematic aspect of the queries that give an empty result: Their request charge is disproportionately high. They cost around 4300-6000 RU per query. The queries that give to the expected (non-empty) result, cost 45-105 RU. This values are true if the container is configured with 2000RU/s.
When increasing the throughput of the container to 4000RU/s, the queries that give an empty result use up to 12000 RU. The queries that give the expected result, still cost their 45-105RU.

As a side note:
When executing the same queries in the Data-Explorer of the Azure-Portal, we see an interesting behavior:
None of the queries lead to an empty result. BUT: Exactly the queries that lead to an empty result when executed by the SDK do lead to a very long response time (>=40 seconds) when being executed in the Azure-Portal. The queries that give the expected result when executed using the SDK lead to a normal response time (<1 second) when being executed in the Azure-Portal.
This behavior experienced the Azure-Portal leads to the assumption, that the problem is in the Cosmos DB itself (and not in the SDK).

**To Reproduce**
We can reproduce the bug on our instance by doing the following:
Execute the query with the SDK and start with a small date range of one day, which usually leads to the expected result. The value that is set as max-item count does not change the behavior, whether it is 10 or 2000.
Now increase the date range of the query day by day. We experience, that the described behavior occurs after querying for a range of 3 to 5 days.

The time range of one day will lead to the query result of 15000-20000 items, independently of the exact date. That means that querying for a time span of 3 days should lead to a result set of 45000-60000 items. The container contains ~1500000 items in total.

**Expected behavior**
We expect, that the result is not empty if we know that the set of items matching the query is definitely not.

**Setup:**
 - OS: This happens when the service that does the query runs locally and when it runs in Azure.
 - IDE : IntelliJ when run locally
 - SDK v3.3.1, but is also reproducible in 2.x

**Comment by kirankumarkolli** [comment]
@f-paulus with empty results are you seeing a non-null continuation token? 
Application is expected to drain results till returned continuation token is null. Its still valid scenarios that empty results with a continuation token are returned.

**Comment by kirankumarkolli** [comment]
@f-paulus the amount work to-be done (=> RU's) to drain the results in same irrespective of done inside SDK or outside. Doing these inside SDK will make the API semantic simpler and straight. @mbhaskar please add a work-item to track it. 

For high RU's are typically result of poor index usage. QueryMetrics will give insights, please take a look at QueryMetrics.

**Comment by f-paulus** [comment]
@kirankumarkolli Thank you for the answer. I compared the query metrics for the the two queries for which I added the logs in my last comment. For the second query, we can see, that the time is spent mainly in `documentLoadTimeInMs`. Also `indexUtilizationRatio` is `0.00`.

This is an excerpt of our indexing policy:
```
{
    "indexingMode": "consistent",
    "automatic": true,
    "includedPaths": [
        {
            "path": "/*"
        }
    ],
    "excludedPaths": [
        ...
    ]
}
```
Does this look good to you? I did cut out the excluded paths since they should not interfere with the two date fields, for which indexing seems to be problematic.

We think, that this should automatically match the specification in the documentation about querying dates:
https://docs.microsoft.com/de-de/azure/cosmos-db/working-with-dates#indexing-datetimes-for-range-queries
Is this assumption correct?

**Comment by kirankumarkolli** [comment]
@f-paulus `indexUtilizationRatio` is `0.00` implies its SCAN which is expensive. 
Can you please share the full IndexingPolicy including full expansion of `excludedPaths'.

**Comment by kushagraThapar** [comment]
@f-paulus : We imported the query plan changes from older SDK to V3 and released it as part of this version: https://github.com/Azure/azure-sdk-for-java/releases/tag/azure-cosmos_3.4.0

Can you please verify the issue still exists on v3.4.0 ??

**Comment by kirankumarkolli** [comment]
Resolving the issue. Please re-active with a repro using latest SDK version..
