### ISSUE TITLE
Codesnippets with class references that aren't imports in the file they're being pulled into fail the javadoc build

### ISSUE THREAD

**Issue by JimSuplizio** [Azure/azure-sdk-for-java#6116]
We pull in a lot of samples using @codesnippet tags (codesnippet is an javadoc doclet that allows us to pull in real world samples directly from our sample code). For all intents and purposes, these code snippets still follow the same behavioral rules as @see or @link tags and one of the big gotchas using those is any class references need to be imports in the code, itself. For the most part this wouldn’t really be that big of a deal as one could simply add a code reference and the appropriate dependency to the POM file. In the case of the Keyvault codesnippets they’re using classes from azure-identity which, unfortunately, cannot be a direct dependency of any of our shipping libraries as doing so would lock that library into depending on a specific version of msal4j which would defeat the entire reason we have identity abstractions in core.

The easiest way to reproduce this is to remove the core and identity project references from the keyvault's service pom file, https://github.com/Azure/azure-sdk-for-java/blob/d779cb8d0c926d1914db139340d4fe585395a756/sdk/keyvault/pom.service.xml#L41, and then try to build keyvault. The java will build just fine but the javadoc build will fail with a number of errors similar to the following:
sdk\keyvault\azure-security-keyvault-secrets\src\main\java\com\azure\security\keyvault\secrets\SecretAsyncClient.java:56: warning - Tag @link: reference not found: com.azure.identity.DefaultAzureCredentialBuilder

**Comment by joshfree** [comment]
@g2vinay could you please own cleaning this up for KV and all other track 2 packages fro the December update?

**Comment by JonathanGiles** [comment]
The issue is that the codesnippet doclet tries to be smart and mark the included code with `@link` tags so that it can be more useful for end users. My preferred approach would be to augment the tool on GitHub (https://github.com/jtulach/codesnippet4javadoc) and to add in a configuration option to universally disable these links. It'll make the code less useful, but that isn't the primary motivation for using this doclet in the first place.

**Comment by g2vinay** [comment]
@srnagar , is working on this.

**Comment by srnagar** [comment]
I have a PR out for this - https://github.com/jtulach/codesnippet4javadoc/pull/18
