### ISSUE TITLE
Core - HttpClientBuilders fail when running Analyze step. 

### ISSUE THREAD

**Issue by gapra-msft** [Azure/azure-sdk-for-java#6121]
When I run the Run Spotbugs aggregate step locally on my machine, it gives back JavaDoc warnings 

 C:\azure-sdk-for-java\sdk\core\azure-core-http-netty\src\main\java\com\azure\core\http\netty\NettyAsyncHttpClientBuilder.java:115: warning - Tag @link: reference not found: com.azure.core.implementation.serializer.jsonwrapper.api.Type[WARNING] C:\azure-sdk-for-java\sdk\core\azure-core-http-okhttp\src\main\java\com\azure\core\http\okhttp\OkHttpAsyncHttpClientBuilder.java:141: warning - Tag @link: reference not found: com.azure.core.implementation.serializer.jsonwrapper.api.Type

**Comment by alzimmermsft** [comment]
Running the pipeline steps from a clean Maven state (deleted the .m2 cache) was unable to reproduce this issue, I'm wondering if the Maven cache had a stale JAR file.

Closing this issue for now, but if it happens again please re-open it or create a new issue.
