### ISSUE TITLE
[QUERY] What is the proper way to copy a blob to a new location (Azure Storage Blob)

### ISSUE THREAD

**Issue by david-nguyen** [Azure/azure-sdk-for-java#6122]
**Query/Question**
After guessing/testing I'm able to get my blob copy operation working however it seems unintuitive. I'm wondering what is the proper way to copy a blob to a new location?

For example my sample code:

    val destinationBlobClient = new BlobClientBuilder()
        .endpoint("https://***.blob.core.windows.net/")
        .sasToken(sasToken)
        .containerName(storageContainer)
        .blobName("move/test.csv")
        .buildClient()

    val sourceBlobClient = new BlobClientBuilder()
        .endpoint("https://***.blob.core.windows.net/")
        .sasToken(sasToken)
        .containerName(storageContainer)
        .blobName("source/test.csv")
        .buildClient()
 
     destinationBlobClient .startCopyFromURL(new URL(sourceBlobClient .getBlobUrl + sasToken))

If I don't include the SAS token I receive a 404 error. Is there something I'm missing/wrong when I perform a copy operation so it is aware of the other blob client credentials?

What if I pass credentials using an access key? I still need to provide a SAS token to the URL?

It really doesn't help that the readme/auto-generated docs do not align with the maven repos.

OS: Windows 10
IDE : IntelliJ IDEA
Version of the Library used: 12.0.0-preview.4

**Comment by gapra-msft** [comment]
Hi @david-nguyen, 

Thank you for your question. Could you please provide the following information so I can get a better understanding of the problem you are seeing?

 - OS: [e.g. iOS]
 - IDE : [e.g. IntelliJ]
 - Version of the Library used

Also, I did want to bring to your attention that we happened to have just GA'd the Azure Storage Blob library and have refactored the method you are mentioning in this query.

**Comment by david-nguyen** [comment]
Thanks I've updated the original issue with the information you requested.

**Comment by gapra-msft** [comment]
Hi @david-nguyen Thank you for the additional information. 
[Here](https://docs.microsoft.com/en-us/rest/api/storageservices/copy-blob) is some possibly helpful documentation for the copy blob operation. 
To summarize, if the source and destination blob are in the same account, you can authorize using a SharedKey. If the blobs are in a different account, then you do either need to either attach a sas or allow public access to the source

**Comment by david-nguyen** [comment]
@gapra-msft and how is that accomplished with the java library using a shared key? I can't figure out how shared key would be passed through from the source blob client since the only input from start copy is a url.

**Comment by gapra-msft** [comment]
You should be able to authenticate the destination blob using a SharedKeyCredential using the .credential() method.

**Comment by rickle-msft** [comment]
@david-nguyen To add to what was already said, if your blobs are in the same account and you wish to authenticate with a shared key, you only have to set the shared key on the destination. In this case, no extra authentication (i.e. no passing of credentials) is necessary for the source. 

The authentication options for each blob are as follows:

- Destination
    - SharedKey- set a SharedKey on the client object
    - Sas- attach a sas token to the url (most easily done through the .sasToken() on the builder)
    - Public access- set the container access policy to allow public access to blobs
- Source
    - SharedKey- If blobs are in the same account, the destination's SharedKey can be implicityly applied to the source. No credentials need to be attached to the source in this case
    - Sas- Same as above
    - Public access- same as above.

**Comment by david-nguyen** [comment]
@gapra-msft @rickle-msft  thanks for the help, there seems to be an issue with running the commands on databricks which has made the situation confusing. I was able to get the copy command working properly on my local machine. On databricks, anytime I attempted to do anything with the blob the command would just hang. Thanks you.

**Comment by rickle-msft** [comment]
We are happy to hear you were able to make it work! I am going to close this issue as I believe the question has been addressed. If you need further support, please feel free to reopen the issue or post a new one.
