### ISSUE TITLE
Remove site:site site:stage From PR Validation

### ISSUE THREAD

**Issue by alzimmermsft** [Azure/azure-sdk-for-java#6128]
Look into replacing this step with modular versions of the step.

- Checkstyle linting
- SpotBugs linting
- Javadoc generation

This step is a common failure but it takes upwards of 20-30 minutes to run and generally when it fails there is no explanation of why it failed just what failed (ex. 10 checkstyle errors). This not only slows down PR validation but slows down the development cycle.

**Comment by JonathanGiles** [comment]
On my machine, I ran the following commands (preceded by a `mvn clean` first), and got the following timings. The table doesn't include the additional flags I used in all cases: `-f pom.client.xml -DskipTests -Dgpg.skip`

| Command                                                                                                               | Timing      |
|------------------------------------------------------------------------- |-----------|
| `site:site site:stage`                                                                                             | 9m 25s     |
| `spotbugs:check`                                                                                                | 5.716s        |
| `checkstyle:checkstyle-aggregate`                                                                 | 60s             |
| `javadoc:aggregate`                                                                                           | 49.922s     |
| `spotbugs:check checkstyle:checkstyle-aggregate javadoc:aggregate` | 1m 56s       |
