### ISSUE TITLE
[BUG] Can not run dev tests with Azurite

### ISSUE THREAD

**Issue by synox** [Azure/azure-sdk-for-java#6140]
**Describe the bug**
Can not use Azurite for local development because the request urls are constructed in the wrong way. 

***Exception or Stack Trace***
local: 
```
Exception in thread "main" com.azure.storage.blob.models.BlobStorageException: Status code 400, (empty body)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:490)
```

azurite: 
```
172.17.0.1 - - [01/Nov/2019:16:05:52 +0000] "GET /mycontainer?restype=container HTTP/1.1" 400 -

info: BlobStorageContextMiddleware: RequestMethod=GET RequestURL=http://127.0.0.1/mycontainer?restype=container RequestHeaders:{"host":"127.0.0.1:10000","accept":"*/*","date":"Fri, 01 Nov 2019 16:05:52 GMT","authorization":"SharedKey devstoreaccount1:RPl/IHhGATnQupcOZ2wI6JmI1CJpmnmCp/XY49Amx5M=","x-ms-version":"2019-02-02","x-ms-client-request-id":"c3b4c250-e4cb-4534-8856-e9928acf07f8","user-agent":"azsdk-java-azure-storage-blob/12.0.0 11.0.4; Mac OS X 10.15","content-length":"0"} ClientIP=172.17.0.1 Protocol=http HTTPVersion=1.1
info: BlobStorageContextMiddleware: Account=mycontainer Container=undefined Blob=
verbose: DispatchMiddleware: Dispatching request...
error: DispatchMiddleware: Incoming URL doesn't match any of swagger defined request patterns.
```

**To Reproduce**
```
docker run -p 10000:10000 mcr.microsoft.com/azure-storage/azurite azurite-blob  -l /data --blobHost 0.0.0.0 -d debug.log
```
pom.xml: 
```
<dependency>
            <groupId>com.azure</groupId>
            <artifactId>azure-storage-blob</artifactId>
            <version>12.0.0</version>
        </dependency>
```
(`azure-storage-blob` was built locally (commit `bbf1cbd`))

***Code Snippet***
```
import com.azure.storage.blob.BlobContainerClient;
import com.azure.storage.blob.BlobServiceClientBuilder;

public class LocalAzurite {
    public static void main(String[] args) throws NoSuchFieldException {

        BlobContainerClient container = new BlobServiceClientBuilder()
                .connectionString("UseDevelopmentStorage=true;")
                .buildClient()
                .getBlobContainerClient("mycontainer");

        if (!container.exists()) container.create();

        System.out.println("exists: " + container.exists());
        System.out.println(container.getBlobClient("myblob").getBlobUrl());
    }
}
```

**Expected behavior**
To create the blob without error. 

**Setup (please complete the following information):**
 - OS:  macOS 10.15, Oracle JDK 11
 - IDE : IntelliJ
 - Version of the Library used: current master branch (commit `bbf1cbd`)

**Additional context**
For Azurite to work the urls have to be in the format: 
    ```http://127.0.0.1:10000/<account-name>/<resource-path>```

But the produced url is 
    http://127.0.0.1:10000/mycontainer
instead of 
    http://127.0.0.1:10000/devstoreaccount1/mycontainer

I noticed there is support for the emulator: StorageConnectionString#create:  https://github.com/Azure/azure-sdk-for-java/blob/master/sdk/storage/azure-storage-common/src/main/java/com/azure/storage/common/implementation/connectionstring/StorageConnectionString.java#L106

However the endpoint is later shortened, so that the account-name is not in the path any more: 
SpecializedBlobClientBuilder#getUrl:  https://github.com/Azure/azure-sdk-for-java/blob/master/sdk/storage/azure-storage-blob/src/main/java/com/azure/storage/blob/specialized/SpecializedBlobClientBuilder.java#L213

1. Is there support to use Azurite with `azure-storage-blob`?
2. How can they be used together?

**Comment by rickle-msft** [comment]
Hi, @synox. Thank you for reporting this and for taking time to point out where the problem originates. We will work on this and get back to you soon about the status of our fix.
