### ISSUE TITLE
Write more static analysis checks for APIView

### ISSUE THREAD

**Issue by JonathanGiles** [Azure/azure-sdk-for-java#6150]
I have previously submitted some [static analysis checks into APIView](https://github.com/Azure/azure-sdk-tools/commit/0a462c5bc9352b0fb78849e6445b4b1c95b6bcd9), but there are more that can be written, such as:

 - [x]  No upper case words (e.g. URL, HTTP, XML, JSON, SAS, CPK, API, etc)
 - [ ] Banned types in API: `Date`, `Calendar`, `URL` (mostly)
 - [x] Bad prefixes (e.g. `isHas`, maybe `setHas`)

**Service clients (classes with @ServiceClient annotation):**
 - [ ] No public or protected constructors.
 - [ ] No public static 'builder' method.
 - [ ] No setter methods to mutate local state of client (easier enforced by ensuring all local state is final).
 - [ ] No checked exceptions on API.
 - [ ] Should be named *AsyncClient or *Client.
 - [ ] Return types should be standard:
   - [ ] Async: PagedFlux or Mono if a non-'withResponse' 
   - [ ] Async: PagedFlux or Mono<Response> if a 'withResponse'
   - [ ] All methods annotated with @ServiceMethod that return a Response (or Mono<Response>) must have their method name end with 'withResponse'. If the service method does not return a Response or Mono<Response>, it must not end with 'withResponse'.
   - [ ] All methods starting with 'begin' should return a Poller. All methods returning Poller must start with 'begin'.

**All public API:**
 - [ ] No 'Async' suffix on methods
 - [ ] Must have a 'withResponse' overload on client methods
 - [ ] Context should be passed in as an argument to all public methods annotated with @ServiceMethod that return Response<T> in sync clients.

**Misc:**
  - [ ] Classes implementing ServiceVersion must have 'public static KeyServiceVersion getLatest()'
  - [ ] Classes that implement TokenCredential should be in an implementation package.

**Comment by mssfang** [comment]
I will do it.
