### ISSUE TITLE
Autorest: unable to receive VM InstanceView

### ISSUE THREAD

**Issue by dtretyakov** [Azure/azure-sdk-for-java#618]
Currently autogenerated [VirtualMachinesOperationsImpl](https://github.com/Azure/azure-sdk-for-java/blob/autorest/azure-mgmt-compute/src/main/java/com/microsoft/azure/management/compute/VirtualMachinesOperationsImpl.java) does not provide method to receive InstanceView model for VM which is available via following API:
```
https://resources.azure.com/subscriptions/{sid}/resourceGroups/{gid}/providers/Microsoft.Compute/virtualMachines/{vmId}/InstanceView
```

**Comment by m-moris** [comment]
+1
I'm facing same problem in Java and Python SDK.
https://github.com/Azure/azure-sdk-for-python/issues/548

**Comment by m-moris** [comment]
Hi @dtretyakov 

I got the answer from python issue. I think that this problem is the same.
I've tried using expand parameter and got instance view information.

```
 ServiceCall async = client.getVirtualMachinesOperations().getAsync(rg, rs, "instanceview", serviceCallback);
```

Thanks.

**Comment by dtretyakov** [comment]
@m-moris, thanks for pointing me.
