### ISSUE TITLE
Add Capabilities to Modify the User-Agent Header More Easily

### ISSUE THREAD

**Issue by alzimmermsft** [Azure/azure-sdk-for-java#6197]
The current implementation of the `UserAgentPolicy` checks the `HttpRequest` for an existing `User-Agent` header. If the existing header is present it will perform simple verification that the header isn't the same as the default User-Agent header, if it is it'll just use the current header otherwise it will prepend the stored User-Agent header to the current header. This implementation makes it difficult to modify the applied header in a dynamic way without needing to build a custom `HttpPipeline` or `HttpPipelinePolicy`.

When applying the `UserAgentPolicy` it has access to the user passed `Context`, we should leverage this to allow the user to pass specific context values which will mutate the `User-Agent` header.

Proposition is adding two keys which the `UserAgentPolicy` will attemp to find, `Custom-User-Agent` and `Additional-User-Agent`. If the custom user agent is found this will overwrite any value the policy would apply and the current User-Agent header, if additional user agent is found this will be appended to the user agent the policy would apply, and if neither are found the user agent will simply be the user agent the policy would apply.

**Current Logic**
- Retrieve current User-Agent header
- If header doesn't exist or begins with the SDK User-Agent indicator
  - Set the User-Agent to the value stored in the policy
- Otherwise
  - Prepend the value stored in the policy to the current User-Agent

**Proposed Logic**
- Check the passed context for values using keys `Custom-User-Agnet` and `Additional-User-Agent`
- If `Custom-User-Agent` is found use it as the `User-Agent`
- If `Additional-User-Agent` is found append it to the value stored in the policy
- Otherwise use the value stored in the policy

**Comment by JonathanGiles** [comment]
Works for me! +1
