### ISSUE TITLE
Service Bus SharedAccessSignature?

### ISSUE THREAD

**Issue by asebak** [Azure/azure-sdk-for-java#620]
```
  Configuration config =
                ServiceBusConfiguration.configureWithSASAuthentication(
                        URL,
                        "RootManageSharedAccessKey",
                        token,
                        ".servicebus.windows.net"
                );
```

In the ServiceBusConfiguration is it a shared access key or shared access signature that gets passed in.  I am passing a shared access signature to it but I keep getting authentication issues.  I am just curious if behind the scenes does it creates an SAS token with a shared access key?  If someone can please clarify this.  I am interested in passing a shared access signature.

**Comment by jianghaolu** [comment]
I believe they are SAS key based authentications.

@hovsepm I remember you working on this back then? Can you help clarify?

**Comment by martinsawicki** [comment]
the service bus client library is not in this repo anymore, so if this is still an issue, it should go there:
https://github.com/azure/azure-service-bus-java
