### ISSUE TITLE
[Storage] Deprecate SAS public constructors that take a long list of params

### ISSUE THREAD

**Issue by srnagar** [Azure/azure-sdk-for-java#6204]
SAS SignatureValues and QueryParameters classes in Storage Blobs and DataLake modules take a long list of constructor args (currently 12 params) that should be deprecated as these types provide fluent APIs.

https://github.com/Azure/azure-sdk-for-java/blob/master/sdk/storage/azure-storage-blob/src/main/java/com/azure/storage/blob/sas/BlobServiceSasSignatureValues.java#L133

https://github.com/Azure/azure-sdk-for-java/blob/master/sdk/storage/azure-storage-file-datalake/src/main/java/com/azure/storage/file/datalake/sas/DataLakeServiceSasSignatureValues.java#L130

https://github.com/Azure/azure-sdk-for-java/blob/master/sdk/storage/azure-storage-blob/src/main/java/com/azure/storage/blob/sas/BlobServiceSasQueryParameters.java#L105

**Comment by rickle-msft** [comment]
Hi, @srnagar. Thanks for pointing this out. We are planning to update how customers interact with Sas soon and will take this into consideration when we pick up that work.

**Comment by raj2103** [comment]
Hi @rickle-msft - I had a related question. Is there a plan to support SAS creation through the `BlobClient` class in v12 as there was in the preview?

**Comment by rickle-msft** [comment]
@raj-sh Thank you for your patience. I apologize that I am just seeing this now. A `generateSas` method has already been added to the blob client, and we are working to add this to other services as well. We hope both of these additions will be included in 12.2.0

**Comment by rickle-msft** [comment]
#6409 is the open PR for blobs. It should be merged once the conflicts with master are resolved.

**Comment by alzimmermsft** [comment]
These have been deprecated in #6409, closing issue.
