### ISSUE TITLE
[BUG] Azure HTTP Netty has a compile time dependency on azure-core-test

### ISSUE THREAD

**Issue by chetanmeh** [Azure/azure-sdk-for-java#6207]
**Describe the bug**

`azure-core-http-netty` has a compile time dependency on a test module `azure-core-test` which pulls in test related jars in production assembly

https://github.com/Azure/azure-sdk-for-java/blob/990ca20e351df56215d0c01a909e9aa3d4d12f95/sdk/core/azure-core-http-netty/pom.xml#L86-L90

**Expected behavior**
There should be no dependency on a test jar

**Screenshots**

<img width="599" alt="image" src="https://user-images.githubusercontent.com/664531/68399043-c4b55c00-019b-11ea-870a-87fedbe8026d.png">

**Setup (please complete the following information):**
 - `com.azure:azure-storage-blob:12.0.0`

**Information Checklist**
Kindly make sure that you have added all the following information above and checkoff the required fields otherwise we will treat the issuer as an incomplete report
- [x] Bug Description Added
- [ ] Repro Steps Added
- [x] Setup information Added

**Comment by joshfree** [comment]
Thanks for reporting this issue @chetanmeh.  @anuchandy can you please take a look?
