### ISSUE TITLE
[QUERY] Creating a Blob container with an ImmutabilityPolicy

### ISSUE THREAD

**Issue by alberto-alvarado-m** [Azure/azure-sdk-for-java#6209]
**Query/Question**
How do I create a Blob container with an ImmutabilityPolicy using the Azure Java SDK? There is no documentation regarding Immutable storage with the Java SDK.

***Why is this not a Bug or a feature Request?***
Some classes are there related to immutable storage, but there is no documentation. 

**Setup (please complete the following information if applicable):**
 - OS: Windows 10
 - IDE : IntelliJ IDEA
 - azure-mgmt-storage 1.27.2

**Comment by yaohaizh** [comment]
@xccc-msft  could you provide some guideline here? Thanks.

**Comment by xccc-msft** [comment]
@alberto-alvarado-m As per the REST APIs provided by storage resource provider side, there are only [BlobContainer_Create](https://docs.microsoft.com/en-us/rest/api/storagerp/blobcontainers/create) and [ImmutabilityPolicy_CreateOrUpdate](https://docs.microsoft.com/en-us/rest/api/storagerp/blobcontainers/createorupdateimmutabilitypolicy).

For your query, you will need to separate into below two steps when creating a blob container with immutability policy.
- First, create blob container
```java
storageManager.blobContainers().defineContainer(“containerName”)
                                <more required/desired configuration>
                                .create();
```
- Second, create immutability policy and associate it with existing blob container created before
```java
storageManager.blobContainers().defineImmutabilityPolicy(“policyName”)
                                .withExistingContainer(“resourceGroupName”, “accountName”, “containerName”)
                                <more required/desired configuration>
                                .create()
```
The `withExistingContainer` will help operate the association. Thanks.

**Comment by alberto-alvarado-m** [comment]
Thanks, that's what I was looking for.

**Comment by alberto-alvarado-m** [comment]
> @alberto-alvarado-m As per the REST APIs provided by storage resource provider side, there are only [BlobContainer_Create](https://docs.microsoft.com/en-us/rest/api/storagerp/blobcontainers/create) and [ImmutabilityPolicy_CreateOrUpdate](https://docs.microsoft.com/en-us/rest/api/storagerp/blobcontainers/createorupdateimmutabilitypolicy).
> 
> For your query, you will need to separate into below two steps when creating a blob container with immutability policy.
> 
> * First, create blob container
> 
> ```java
> storageManager.blobContainers().defineContainer(“containerName”)
>                                 <more required/desired configuration>
>                                 .create();
> ```
> 
> * Second, create immutability policy and associate it with existing blob container created before
> 
> ```java
> storageManager.blobContainers().defineImmutabilityPolicy(“policyName”)
>                                 .withExistingContainer(“resourceGroupName”, “accountName”, “containerName”)
>                                 <more required/desired configuration>
>                                 .create()
> ```
> 
> The `withExistingContainer` will help operate the association. Thanks.

Thanks, I did manage to be able to create a Blob container and its immutability policy with the examples you've provided. 

Is it possible to lock the immutability policy and retrieve the immutability policy from a container with the Azure Java SDK?
