### ISSUE TITLE
Update Contributing.md build environment instructions

### ISSUE THREAD

**Issue by joshfree** [Azure/azure-sdk-for-java#6216]
Tracking issue to improve the contributing.md

> The `sdk-build-tools` doesn't get released to Maven, to install it you'll need to have the [eng](https://github.com/Azure/azure-sdk-for-java/tree/master/eng) folder copied locally and install `eng/code-quality-reports/pom.xml`. This should unblock you on this issue, please let us know if you run into additional issues and we'll be happy to help.
> 
> _Originally posted by @alzimmermsft in https://github.com/Azure/azure-sdk-for-java/issues/6181#issuecomment-551218225_

**Comment by karianna** [comment]
@joshfree  I'm happy to PR a doc change here but is that the right solution?  Is there perhaps some Maven foo that could be applied to pull this in automatically?

**Comment by joshfree** [comment]
> @joshfree I'm happy to PR a doc change here but is that the right solution? Is there perhaps some Maven foo that could be applied to pull this in automatically?

Yes, updating the build to eliminate manual steps is the preferred choice.  @mitchdenny can comment more here on buildtools. 

In the interim, I’m trying to get people in the habit of documenting existing tribal knowledge in the contributing guide, developer guide, and user wiki.
