### ISSUE TITLE
[Azure-core ] Requirement Gathering- Customizing azure-core Http Policy

### ISSUE THREAD

**Issue by hemanttanwar** [Azure/azure-sdk-for-java#6217]
Various Azure client library need to have many variations in creating HttpPolicy. Current implementation is lacking and does not support these variations. 
This is an attempt to look into future and see is this scalable system to support variations in http policies. 

## What are current  known requirement to customize policies ?
  List of requirement which we know of today.

  1. Generate request ID and add it to request with different HttpHeaders.
       https://github.com/Azure/azure-sdk-for-java/pull/6214/files 
     • "x-ms-client-request-id
     • "client-request-id
  2. Retry-delay header name in RetryPolicy : https://github.com/Azure/azure-sdk-for-java/pull/6196
  3. Allow customers set the header : https://github.com/Azure/azure-sdk-for-java/issues/6171
     • "x-ms-client-request-id"
     • "x-ms-correlation-request-id"
     • "correlation-context"
 4. Storage wants to change endpoint uri during retry.
  

We need to look at Azure Core http policies and current client libraries is doing their own thing due to missing capabilities and weigh that against the likelihood of it being common.

## Possible Solutions:
List possible solutions.

### Option 1 
RetryPolicy(Function<> handlerCustomImplementation): Each policy can take in a function provided by Client to override its functionality completely. 

### Option 2 
Take Custom Options in each Http Policy to customize. 
for example:  RetryPolicy(RetryPolicyCustomOptions options)

These options can very a lot for example

             boolean values : Example  generate request id?
             Map of Key ,value : add  something in header.
             List of names : response retry-delay header  name.

**Comment by itye-msft** [comment]
Based on Azure Search docs (https://docs.microsoft.com/en-us/rest/api/searchservice/common-http-request-and-response-headers-used-in-azure-search) and Swagger spec, Search uses `client-request-id` and `return-client-request-id`. 
Basically the service ignores the "x-ms-client-request-id". If a user wants to turn on tracing it's not possible unless a new header is added.
Hopefully done internally by default with the option to change that later.

**Comment by hemanttanwar** [comment]
Here are few suggestions ..

Option 1 : 
   Use Options to collect variations in several Policies. This is already done in storage 
`
	public final class RequestRetryPolicy implements HttpPipelinePolicy {
		public RequestRetryPolicy(RequestRetryOptions requestRetryOptions) () { ... }
	}
 `    
Option 2 : Use Supplier Functional interface to completely overwrite HttpRequest. This interface will be user-provided in cases where existing implementation is in-sufficient.

We are leaning towards Option 1, As it provides sufficient generic extensible interface. We can extent Options approach for future needs.

Option 2 seems more drastic and we do not see need as of now. Once time is ripe for Option 2, it will be additive change. 

**No Need to change:**
	DateHeaderPolicy RFC113 ,  ISO8601
	BearerTokenAuthenticationPolicy
	HttpLoggingPolicy
	TimeoutPolicy
	
**Ignore for now**
	CookiePolicy

**Update following with new design**
	1. HostPolicy
	2. RequestIdPolicy
	3. May be combine 1. PortPolicy , 2. ProtocolPolicy , 3. HostPolicy into "EndpointPolicy" ? And also handle  "Geo fail over "
	4. RetryPolicy -> Strategy, response header 
	5. UserAgentPolicy

**Comment by itye-msft** [comment]
Thanks!
As the Java SDK developer for the search service,
as long as the solution will allow us to:
1. Add the RequestIdPolicy internally, to make it a default when creating a new request, and-
2. Change/Set/Override the RequestIdPolicy by the user,

than it sounds great to me.
Let me know how can I help.

Kind regards,
Itye

**Comment by hemanttanwar** [comment]
Combining Multiple issues to bring discussion at one place 

@anuchandy  comment 

The `RetryPolicy` is an asynchronous loop. The factors that control the loop behavior (when to break, time to wait before retry, max number of iterations) are externalized to `RetryStrategy` type. 

The `RetryStrategy` expose `shouldRetry(HttpResponse)` and `calculateRetryDelay(int retryAttempts)` which controls the async retry loop in `RetryPolicy`. 

While `shouldRetry` can use the current `HttpResponse` to dynamically decide whether to retry or not, the `calculateRetryDelay` has only static data available those provided at the time of creating the `Strategy` | `RetryPolicy`. 

It would be nice if `calculateRetryDelay` also has access to `HttpResponse`. This enables users to customize the existing implementations of `RetryStrategy`. 

A use case is - The AzConfig library requires looking a custom header to decide the retry-delay. There could be more cases, where users want to look at other headers (in request/response) to make a decision. 

The proposal is have a default method `RetryStrategy::calculateRetryDelay(HttpResponse httpResponse, int retryAttempts)`, By default is it invokes `calculateRetryDelay(int retryAttempts)` impl of specific `RetryStrategy` implementation.

```java
public interface RetryStrategy {
    …..

    default Duration Duration calculateRetryDelay(HttpResponse httpResponse, int retryAttempts) {
        return calculateRetryDelay(retryAttempts);
    }

    Duration calculateRetryDelay(int retryAttempts);
}

```

AzConfig can override this default impl like:

```java
RetryPolicy DEFAULT_RETRY_POLICY = new RetryPolicy(new ExponentialBackoff() {
    @Override
    public  Duration calculateRetryDelay(HttpResponse httpResponse, int retryAttempts)) {
        String delay = httpResponse.getHeaderValue("retry-after-ms");
        return delay != null ?  Duration.ofMillis(Long.parseLong(delay)) : calculateRetryDelay(retryAttempts);
    }
});
```

The only parameter that `RetryPolicy` takes is `RetryStrategy`. 

This keeps `RetryPolicy` generic while all the decisions are offloaded to `RetryStrategy`. 

Though proposal is generic, we can have specialization of it to solve the issue we discussed here: #5945.
Also if we offload all the controlling factors of async-retry-loop to RetryStrategy impl then we can simplify the ctr of RetryPolicy, all it take is RetryStrategy .

**Comment by hemanttanwar** [comment]
Soo I will open a draft PR with suggested changes by @anuchandy .

**Comment by hemanttanwar** [comment]
@JonathanGiles  @conniey  @anuchandy @srnagar @alzimmermsft 

I am creating this PR for discussing and collaborating our design. I have considered  inputs given above. Lets continue to discuss in PR and come to a final design

https://github.com/Azure/azure-sdk-for-java/pull/6400

**Comment by hemanttanwar** [comment]
Design options to override response header name
Option 3 :
User can override retry **header name** in RetryPolicy constructor. This is then passed on to RetryStrategy.  
`
RetryPolicy.java
  public RetryPolicy(String retryAfterHeader, ChronoUnit retryAfterTimeUnit)

RetryStrategy.java   // Add following new functions .. 
default String getRetryAfterHeader() 
default ChronoUnit getRetryAfterTimeUnit()
default Duration calculateRetryDelay(HttpResponse httpResponse, int retryAttempts)
`

Option 4 :
Minimal change and allow
User can override retry **header name** in RetryPolicy constructor. This is then passed on to RetryStrategy.  

`
RetryPolicy.java
  private final String retryAfterHeader;
  private final String retryAfterTimeUnit;
  public RetryPolicy(String retryAfterHeader, ChronoUnit retryAfterTimeUnit)

RetryStrategy.java
No Change
`

**Comment by hemanttanwar** [comment]
Based on Jonathon's suggestion https://teams.microsoft.com/l/message/19:5e673e41085f4a7eaaf20823b85b2b53@thread.skype/1574279428860?tenantId=72f988bf-86f1-41af-91ab-2d7cd011db47&groupId=3e17dcb0-4257-4a30-b843-77f47f1d4121&parentMessageId=1574110651478&teamName=Azure%20SDK&channelName=Language%20-%20Java%20%F0%9F%A6%83&createdTime=1574279428860

I will work on `Option 4` .

**Comment by hemanttanwar** [comment]
Overwrite Http Header in RequestIdPolicy

Client need to provide/overwrite request id 

-Search team need to overwrite
`x-ms-client-request-id` /  `client-request-id` 

-- App config need to provide following two id.
`x-ms-client-request-id ` and `x-ms-correlation-request-id`

Here are some of the options
**RequestIdPolicy-Option-A**
```java 
    `RequestIdPolicy(Supplier<HttpHeaders> requestIdSupplier)`  : The client can provide both the headers in same policy  since they are related  to RequestID
```
**RequestIdPolicy-Option-B**
```java
     `RequestIdPolicy(Supplier<HttpHeader> requestIdSupplier)`  : The client can provide **RequestID** the header in same policy  since they are related  to RequestID

**Create new Policy**  for setting correlation id
    CorelationIdPolicy.java
```

Option B is more cleaner. I like this option .

**Comment by hemanttanwar** [comment]
PR Closed https://github.com/Azure/azure-sdk-for-java/pull/6602
This issue complete now.
