### ISSUE TITLE
Update azure-storage-java to point customers to 12.0.0 instead of 12.0.0-preview.2

### ISSUE THREAD

**Issue by joshfree** [Azure/azure-sdk-for-java#6222]
The Readme.md at https://github.com/azure/azure-storage-java points people to “v12.0.0-Preview2” and says "GA will be soon".

This is the landing page customers currently see when they go to docs.microsoft.com -> Azure -> Java -> Storage (you can go to this page https://docs.microsoft.com/en-us/azure/java/?view=azure-java-stable and then type Storage in the search box, it will also take you to https://github.com/azure/azure-storage-java)

1. The azure-storage-java readme needs to be updated (/cc @rickle-msft @amishra-dev) 
2. the docs.microsoft.com site needs to be updated to point users to a more relevant landing page  - such as https://github.com/Azure/azure-sdk-for-java/blob/azure-storage-blob_12.0.0/sdk/storage/azure-storage-blob/README.md (/cc @kaerm)

**Comment by kaerm** [comment]
both are done
