### ISSUE TITLE
[FEATURE REQ][storage] BlobServiceSasSignatureValues requires credentials to be passed in instead of reusing the existing ones of a blob client.

### ISSUE THREAD

**Issue by alexander-riss** [Azure/azure-sdk-for-java#6235]
**Is your feature request related to a problem? Please describe.**
BlobServiceSasSignatureValues requires credentials to be passed in instead of reusing the existing ones of a blob client.
The < v12 workflow did allow a blob to create a signature via:
blog.generateSAS(...)
where the blob could be configured at a different part of the application and the business logic did not need any access to secret keys.
the v12 solution no longer allows for this separation of concerns and requires a dedicated
builder.generate(credentials)

**Describe the solution you'd like**
add a method to the blobClient to create a fully configured (authenticated) BlobServiceSasSignatureValues object instead e.g.
blob.configureBlogServiceSasSignatureValues()

**Information Checklist**
Kindly make sure that you have added all the following information above and checkoff the required fields otherwise we will treat the issuer as an incomplete report
- [x] Description Added
- [x] Expected solution specified

**Comment by gapra-msft** [comment]
Hi @alexander-riss, 

Thank you for your feature request. Improving the discoverability of SAS is something we are currently investigating and we will take this into consideration.

**Comment by alexander-riss** [comment]
looks like this was implemented with 12.3.0 - so this issue can be closed. Thanks for getting this addressed
