### ISSUE TITLE
[BUG] All requests are delayed when using RequestRetryOptions

### ISSUE THREAD

**Issue by synox** [Azure/azure-sdk-for-java#6238]
**Describe the bug**
When using RequestRetryOptions on the BlobServiceClient, also successful requests are delayed by `retryDelayInMs`. I would expect successful requests to return immediately. 

***Exception or Stack Trace***
Output of sample code: 
```
started https://xxx.blob.core.windows.net/container1?restype=container
done after 17140 ms
started https://xxx.blob.core.windows.net/container1/blob3?blockid=xxx%3d%3d&comp=block
done after 15183 ms
```

**To Reproduce**
Run the code snippet. Using current master branch. 

***Code Snippet***
```java
String CONN = "DefaultEndpointsProtocol=https;AccountName=......==;EndpointSuffix=core.windows.net";

int maxTries = 1;
long retryDelayInMs = 15_000L;

BlobContainerClient blobContainerClient = new BlobServiceClientBuilder()
        .connectionString(CONN)
        .retryOptions(new RequestRetryOptions(RetryPolicyType.FIXED, maxTries, 20, retryDelayInMs, retryDelayInMs, null))
        .addPolicy((context, next) -> {
                    long start = System.currentTimeMillis();
                    System.out.println("started " + context.getHttpRequest().getUrl());
                    return next.process()
                            .doFinally(e -> System.out.println("done after " + (System.currentTimeMillis() - start) + " ms"));
                }
        )
        .buildClient()
        .getBlobContainerClient("container1");

blobContainerClient.exists();


BlockBlobClient blob1 = blobContainerClient.getBlobClient("blob3").getBlockBlobClient();
blob1.getBlobOutputStream().write("hello world".getBytes());
```

pom.xml: 
```
<dependency>
            <groupId>com.azure</groupId>
            <artifactId>azure-storage-blob</artifactId>
            <version>12.1.0-preview.1</version>
        </dependency>
```
(`azure-storage-blob` was built locally (commit `a08d971a493efb06777f4b9572cb836f61412185`))

**Expected behavior**
There should be a delay after errors, but only if `maxTries>1`. 
There should be no delay if `maxTries=1` for errors.  
There should be no delay on success. 

log output when RequestRetryOptions is not used:
```
started https://xxx.blob.core.windows.net/container1?restype=container
done after 1378 ms
started https://xxx.blob.core.windows.net/container1/blob3?blockid=xxx%3d%3d&comp=block
done after 144 ms
```

**Setup (please complete the following information):**
 - OS: macOS
 - IDE : IntelliJ
 - Version of the Library used: current master branch (commit `a08d971a493efb06777f4b9572cb836f61412185`)

**Additional context**

**Workaround**
* do not use RequestRetryOptions. (we need retry)
* use com.azure.storage.common.policy.RetryPolicyType#EXPONENTIAL with a very small `retryDelayInMs` (we want linear backoff)

**Comment by rickle-msft** [comment]
@synox Thanks for pointing this out. It looks like you're right that we incorrectly apply the fixed timeout to the first try. I will work on getting a pull request out for this. In the meantime, I think you can work around this by using exponential retries and setting your retry delay and max retry delay to be the same value.
