### ISSUE TITLE
Investigate AMQP Connection Timeouts on Linux

### ISSUE THREAD

**Issue by srnagar** [Azure/azure-sdk-for-java#6239]
[From Teams message from Jesse] The Service Bus team is introducing a change to force an idle timeout on AMQP connections due to platform differences.   On Linux, the connection does not transition states in the manner that it does on other platforms and ends up "hung" in some cases.
 
It has been recommended that this change be applied to Event Hubs as well.   .NET and Java were mentioned in conversation. 

https://github.com/Azure/azure-sdk-for-net/pull/7944

**Comment by conniey** [comment]
We've added an idle timeout configuration to proton-j.
