### ISSUE TITLE
Error getting Network Security Groups which has space char in the name

### ISSUE THREAD

**Issue by ssuriya** [Azure/azure-sdk-for-java#624]
Azure supports both space and '+' chars in the NetworkSecurityGroup name.

When NSG is requested with below API: space is encoded into '+' incorrectly and Resource not found exception is thrown.

> Caused by: com.microsoft.windowsazure.exception.ServiceException: ResourceNotFound: The Network Security Group Test+Space does not exist.
> 	at com.microsoft.windowsazure.exception.ServiceException.createFromXml(ServiceException.java:208)
> 	at com.microsoft.windowsazure.management.network.NetworkSecurityGroupOperationsImpl.get(NetworkSecurityGroupOperationsImpl.java:2593)

As a workaround, in my client code, before calling the NetworkSecurityGroupOperationsImpl.get(), we are converting the Space char as "%20".

**Comment by jianghaolu** [comment]
Looks like it doesn't? 
![image](https://cloud.githubusercontent.com/assets/2320445/16536002/648ae67a-3fa1-11e6-9d2a-6d2dc42d4b94.png)

**Comment by jianghaolu** [comment]
Conclusion: Azure **doesn't** support neither space nor '+' chars in the NetworkSecurityGroup name.
