### ISSUE TITLE
Provide ability to reverse lookup, such as VM to resource Group, nic to VM etc.

### ISSUE THREAD

**Issue by netwmr01** [Azure/azure-sdk-for-java#626]
It would make programming much easier if look up could be bi-directional.

If I have a VM instance, I would like to know to which resource Group it belongs.

**Comment by jianghaolu** [comment]
For now there is no API doing this.

A workaround would be looking at the `id` field of the resource. For example, a VM with id `/subscriptions/ffa52f27-be12-4cad-b1ea-c2c241b6cceb/resourceGroups/ecvm1458942251239RG/providers/Microsoft.Compute/virtualMachines/ecvm1458942251239` would say its in resource group `ecvm1458942251239RG`.
