### ISSUE TITLE
[BUG] Azure key vault Incompatible Key and Signing Algorithm Exception

### ISSUE THREAD

**Issue by magooster** [Azure/azure-sdk-for-java#6262]
**Describe the bug**
Signing a hash with signature algorithm JsonWebKeySignatureAlgorithm.ES256K throws a  KeyVaultErrorException

***Exception or Stack Trace***
 Exception: KeyVaultErrorException: Status code 400, {"error":{"code":"BadParameter","message":"Key and signing algorithm are incompatible. Key https://<vault>.vault.azure.net/keys/<key name>/<key version> uses curve 'SECP256K1', and algorithm 'ES256K' can only be used with curve 'P-256K'."}}

**To Reproduce**
Create a key with the following request
CreateKeyRequest request = new CreateKeyRequest.Builder(
                <key vault uri>,
                <name>,
                JsonWebKeyType.EC)
                .withKeySize(256)
                .withKeyOperations(Arrays.asList(JsonWebKeyOperation.VERIFY))
                .withCurve(JsonWebKeyCurveName.P_256K)
                .build();

***Code Snippet***

sign(<key vault uri>, < key name>, "", JsonWebKeySignatureAlgorithm.ES256K, hash);

**Expected behavior**
The sign operation should return a KeyOperationResult

**Screenshots**
N/A

**Setup (please complete the following information):**
 - OS: MacOS
 - IDE : IntelliJ
 - Version of the Library used : 1.2.1

**Additional context**
Using the following, new JsonWebKeySignatureAlgorithm("ECDSA256"), in place of JsonWebKeySignatureAlgorithm.ES256K works...

**Information Checklist**
- [ x] Bug Description Added
- [ x] Repro Steps Added
- [ x] Setup information Added

**Comment by magooster** [comment]
Code snippet should be
sign(<key vault uri>, < key name>, "", JsonWebKeySignatureAlgorithm.ES256K, hash);

**Comment by joshfree** [comment]
Thanks for reporting this issue @magooster. @g2vinay PTAL

**Comment by g2vinay** [comment]
Investigating this issue, 
will update the results here.

**Comment by magooster** [comment]
Have this issue also in azure-security-keyvault-keys 4.1.0 for EC keys created through Azure Portal - where the Elliptic Curve Name is SECP256K1 , this in incompatible with signing algorithm  SignatureAlgorithm.ES256K 

A key created via the Java sdk as follows is ok...

CreateEcKeyOptions createEcKeyOptions = new CreateEcKeyOptions("alice")
                    .setCurveName(KeyCurveName.P_256K);
KeyVaultKey ecKey = keyClient.createEcKey(createEcKeyOptions);

**Comment by g2vinay** [comment]
@magooster 
Thank you for the update.
We've filed an issue with the KV service team to Change EC key elliptic curve name from "SECP256k1" to "P-256K"  on Portal.
will keep you updated, as the fix for it progresses and becomes available on the portal.

**Comment by vcolin7** [comment]
The latest Azure Portal now shows `P-256K` as signing algorithm option instead of `SECP256k1` when creating a Key Vault key.
