### ISSUE TITLE
User agent header exceeds allowed limit on multiple Retries applied.

### ISSUE THREAD

**Issue by samvaity** [Azure/azure-sdk-for-java#6269]
Retry policy keeps on appending to existing User Agent header causing it to exceed the header allowed limit.

Ref: 
` If the header policy is incorrectly applied after a retry policy the customer could run into an issue where the User-Agent header eventually exceeds the allowed limit for a header.`
https://github.com/Azure/azure-sdk-for-java/pull/6249#discussion_r344401938

**Comment by alzimmermsft** [comment]
Will roll this into the change for #6197
