### ISSUE TITLE
[BUG] CosmosSyncScripts null pointer exception in azure-cosmos 3.3.1

### ISSUE THREAD

**Issue by allenhumphreys** [Azure/azure-sdk-for-java#6281]
**Describe the bug**
When using `CosmosSyncClient` to execute a stored procedure, I'm receiving a null pointer exception from the SDK.

- It looks like the conversion from the underlying asynchronous response to the synchronous response should be doing a null check on `storedProcedure()` but it isn't.
https://github.com/Azure/azure-sdk-for-java/blob/a04464988bd564be418329b6b729971f9f0a7705/sdk/cosmos/microsoft-azure-cosmos/src/main/java/com/azure/data/cosmos/sync/CosmosSyncScripts.java#L298

- `CosmosStoredProcedureResponse` clearly documents that `storedProcedure()` can be `null`:  
https://github.com/Azure/azure-sdk-for-java/blob/a04464988bd564be418329b6b729971f9f0a7705/sdk/cosmos/microsoft-azure-cosmos/src/main/java/com/azure/data/cosmos/CosmosStoredProcedureResponse.java#L37

**Comment by kaerm** [comment]
@allenhumphreys thank you for reporting this - we will look into this //cc: @annatisch

**Comment by kushagraThapar** [comment]
This issue has been fixed on all SDK versions. Closing it
