### ISSUE TITLE
Storage client does not support blob names that look like they are encoded

### ISSUE THREAD

**Issue by rickle-msft** [Azure/azure-sdk-for-java#6284]
It is impossible to create a blob with the name %20, for example. The sdk will decode this to ' ' then reencode it to %20, which the service will again decode to ' '. I should be able to create a blob with the name %20 that is encoded to %2520 over the wire and then decoded and stored again as %20. 

It may be the best option is to just document this edge case or perhaps we shouldn't be modifying the blob name at all and we should let the customer handle it or perhaps we should try to detect this somehow and do the right thing.

**Comment by gapra-msft** [comment]
Check to see if this is still an issue

**Comment by gapra-msft** [comment]
Resolution - add docs to pass in url encoded version of blob name
