### ISSUE TITLE
Redesign query API to return  FeedResponse<T> instead of FeedResponse<Document>

### ISSUE THREAD

**Issue by mbhaskar** [Azure/azure-sdk-for-java#6296]
The current query API is tightly couple with document, we want to redesign this API to return FeedResponse<T> instead of FeedResponse<Document> for optimization and enable lazy deserialization

**Comment by kirankumarkolli** [comment]
@mbhaskar do we need a separate issues to track JsonSerializable removal?

**Comment by mbhaskar** [comment]
> @mbhaskar do we need a separate issues to track JsonSerializable removal?

I thought of handling these together, but it would make sense to add a different item. #6325

**Comment by mbhaskar** [comment]
This is completed.
https://github.com/Azure/azure-sdk-for-java/pull/6464
