### ISSUE TITLE
VirtualMachineScaleSetVMsOperations.list doesn't accept a valid OData string for filter parameter

### ISSUE THREAD

**Issue by scotmoor** [Azure/azure-sdk-for-java#630]
Using Beta1

When making call to the list operation of the VMScaleSetVMsOperations the third parameter expects an instance of a VirtualMachineScaleSetVM object, however when you pass in the a valid instance (i.e., location value is set), you get the following exception:

com.microsoft.azure.CloudException: Invalid status code 400: The value '{"location":"eastus"}' of parameter '$filter' is not allowed. Allowed values are 'properties/latestModelApplied eq true, properties/latestModelApplied eq false'.

The only way to get around this is to pass 'null'

**Comment by anuchandy** [comment]
This is a bug in the generated code and we will get it fixed. 

Type of filter should be "string" but in the generated code it's a complex type : https://github.com/Azure/azure-sdk-for-java/blob/autorest/azure-mgmt-compute/src/main/java/com/microsoft/azure/management/compute/VirtualMachineScaleSetVMsOperations.java#L263

**Comment by jianghaolu** [comment]
This is fixed in `master`.
