### ISSUE TITLE
Add a way to update shared access key

### ISSUE THREAD

**Issue by conniey** [Azure/azure-sdk-for-java#6304]
This is a post GA task to allow users to update the shared access key.
```
class SharedAccessKeyCredential {
   public void UpdateSharedAccessKey(string sharedAccessKeyName, string sharedAccessKey);
}
```

**Comment by alzimmermsft** [comment]
[AzureKeyCredential](https://github.com/Azure/azure-sdk-for-java/blob/master/sdk/core/azure-core/src/main/java/com/azure/core/credential/AzureKeyCredential.java) and [AzureNamedKeyCredential](https://github.com/Azure/azure-sdk-for-java/blob/master/sdk/core/azure-core/src/main/java/com/azure/core/credential/AzureNamedKeyCredential.java) cover this scenario.
