### ISSUE TITLE
Create Gitter community channel for azure-sdk-for-java repo

### ISSUE THREAD

**Issue by joshfree** [Azure/azure-sdk-for-java#6314]
Someone with appropriate permissions to https://github.com/Azure, please click the following buttons, after signing in to gitter.im:

1. go to https://gitter.im/home#createroom
2. Community select `Azure`
3. Room add `azure-sdk-for-java`

Thanks

**Comment by kurtzeborn** [comment]
Yeah, this appears to require Azure org (on GitHub) admin rights so @jeffwilcox is the right person to ask.

**Comment by joshfree** [comment]
Closing as community gitter channels have been created for each of the azure/azure-sdk-for-[language] repos.
