### ISSUE TITLE
README Code Changes

### ISSUE THREAD

**Issue by gapra-msft** [Azure/azure-sdk-for-java#6322]
**Is your feature request related to a problem? Please describe.**
Currently when major refactors occur there is no good way to know that the README has also been updated correctly. 

**Describe the solution you'd like**
Create a READMECodSamples.java in Samples and add all the Samples in the README there. When there are compile issues, we will notice and we can update it there as well as in the README.

**Describe alternatives you've considered**
Determine a way to just automate this somehow? Are there .md tools that can help us just go and get the code snippet from a file?

**Information Checklist**
Kindly make sure that you have added all the following information above and checkoff the required fields otherwise we will treat the issuer as an incomplete report
- [X ] Description Added
- [X ] Expected solution specified

**Comment by gapra-msft** [comment]
Integrate with embed me

**Comment by alzimmermsft** [comment]
Closing this issue as the SDKs now use `embedme` which handles copying a code range into a README, this tool will also fail build if the expected README doesn't match the README in the PR.
