### ISSUE TITLE
No com.microsoft.windowsazure.services.blob.BlobContract#createBlobSnapshot(String, String, CreateBlobSnapshotOptions) Method Implementation.

### ISSUE THREAD

**Issue by grantfei** [Azure/azure-sdk-for-java#633]
I have tried to use the azure API recently and found that there is no method to createSnapshot in BlobContract. This is one of important interface for the Blob service. I would had thought the Java API were consistent to the open REST API document.

**Comment by jianghaolu** [comment]
Hi @grantfei, is this what you are looking for?
https://github.com/Azure/azure-storage-java/blob/d108c110ea042df5c898a461007b91818fa98f15/microsoft-azure-storage/src/com/microsoft/azure/storage/blob/CloudBlob.java#L752

**Comment by grantfei** [comment]
hi @jianghaolu, yes. I just want to use minimal dependency rather than import another lib.
I think it's easy to add these API to the existing package.
Also if it can provide these API and it will be wonderful.
Thank.

**Comment by jianghaolu** [comment]
I think that is the only storage library we are offering today.

If you are talking about having all the libraries living in one repository - we might, eventually, but there is no guarantee.

**Comment by jianghaolu** [comment]
No action to take.
