### ISSUE TITLE
Remove duplicate cancel method from CertificateClient

### ISSUE THREAD

**Issue by heaths** [Azure/azure-sdk-for-java#6349]
Since the LRO for CertificateOperation already has a `cancel` method, please remove it from `CertificateClient` for QA. If we hear feedback it's not as discoverable we can always add it back later.

**Comment by heaths** [comment]
Was this done or not (not tied to a PR)?

**Comment by g2vinay** [comment]
Yeah, this was done as part of this PR:
https://github.com/Azure/azure-sdk-for-java/pull/6309/files#diff-e893e8c436eef93e3b0d93d24f0620a2L1719

But, I believe, later  it was added back too in mid december Certs API changes, from consistency API review feedback.
