### ISSUE TITLE
Accept multiple types of Subject Alternative Names

### ISSUE THREAD

**Issue by heaths** [Azure/azure-sdk-for-java#6356]
Since posting multiple types of subject alternative names are possible for CertificatePolicy, change the SubjectAlternativeNames model (or property structure) as follows:

```
class SubjectAlternativeNames {
    dnsNames: string[];
    emails: string[];
    userPrincipalNames: string[]
}
```

Additionally, in a language-idiomatic way, try to ensure that 1 or both of subject and/or subjectAlternativeNames are specified; otherwise, pass to the service as-is and let it validate and return an error response.

**Comment by heaths** [comment]
Was this done or not (not tied to a PR)?

**Comment by g2vinay** [comment]
Yes, this was done as part of this PR:
https://github.com/Azure/azure-sdk-for-java/pull/6309/files#diff-68e6b5d18696982929640983f972479fR35
