### ISSUE TITLE
Status of Azure SDK Java - version 1.0.0

### ISSUE THREAD

**Issue by ankurvsoni** [Azure/azure-sdk-for-java#637]
Hi,

I am interested in using 1.0.0 version of Azure SDK for Java but am little unclear of the status of the project. Can you help answering following questions:

- Is 1.0.0 version production ready?
- When is the official 1.0 version planned to release?
- What is the latest recommended version of Azure SDK for Java?

Regards,
Ankur Soni.

**Comment by jianghaolu** [comment]
Hi @ankurvsoni 

It's not stable. Or production ready.

We don't have a date for official 1.0 yet. We hope it will stabilize by end of summer. We are bringing radical changes so before it goes out we want it well tested. At the same time, we are still maintaining the 0.9 releases.

I would recommend using 1.0.0-beta1. It will be a lot smoother to move on to beta2 and the official one from there.

**Comment by ankurvsoni** [comment]
Thanks for the response. I am already using 1.0.0-beta1 but wanted to make sure that transitions to the official version will be smooth.

**Comment by jianghaolu** [comment]
@ankurvsoni 
The dependencies we use will be the same in the official one. There will be usage differences, including added fluent interfaces, and helper methods to authenticate, etc. You will need to change your code to make it work, but in a good way.

**Comment by ankurvsoni** [comment]
Thanks! Is there a way to make suggestions?  For example, currently, pagination support doesn't seem consistent or doesn't seem to have a nice interface to get a page of result and then request for next page.

**Comment by jianghaolu** [comment]
Yes you can file issues right in this repo. When we target that as a REST API issue we will then file an issue for you in https://github.com/azure/azure-rest-api-specs.

Alternatively, you can file an issue there yourself too. When you find a REST API issue you can always post it directly there. That repository is the nutshell of all [OpenAPI definitions](https://github.com/OAI/OpenAPI-Specification/blob/master/versions/2.0.md) of Azure services.
