### ISSUE TITLE
Failed to delete newworkinterface and availabilityset while return code is 204 and ComputeOperationStatus is Succeeded

### ISSUE THREAD

**Issue by netwmr01** [Azure/azure-sdk-for-java#638]
the following code is use to delete the availabilityset and networkinterface
OperationResponse result = computeManagementClient.getAvailabilitySetsOperations().delete(resourceGroup, vm.getAvailabilitySetReference().toString());

result = networkResourceProviderClient.getNetworkInterfacesOperations().beginDelete(resourceGroup, vm.getNetworkProfile().getNetworkInterfaces().toString());

**Comment by anuchandy** [comment]
@netwmr01 Which SDK are you using ? http://mvnrepository.com/artifact/com.microsoft.azure/azure-bom
"1.0.0-beta1" OR "0.9.x"

**Comment by anuchandy** [comment]
Looks like you are using 0.9.3.

**Comment by anuchandy** [comment]
The method "vm.getAvailbiltiySetReference()" returns the complete resource URI for the availabiltiySet 
e.g. "/subscriptions/{subscriptionId}/resourceGroups/SAMPLE1/providers/Microsoft.Compute/availabilitySets/{availability-set-name}"

The "computeManagementClient.getAvailabilitySetsOperations().delete" expect name of the availabiltiySet as the second argument not the full URI.

**Comment by netwmr01** [comment]
What is an easy way to get availability-set-name through VM? 

    On Tuesday, April 5, 2016 1:46 PM, Anu Thomas Chandy <notifications@github.com> wrote:
 

 The method "vm.getAvailbiltiySetReference()" returns the complete resource URI for the availabiltiySet 
e.g. "/subscriptions/{subscriptionId}/resourceGroups/SAMPLE1/providers/Microsoft.Compute/availabilitySets/{availability-set-name}"The "computeManagementClient.getAvailabilitySetsOperations().delete" expect name of the availabiltiySet as the second argument not the full URI. Can you try this?Regarding the SDK issue of not throwing error is something we will investigate.—

**Comment by anuchandy** [comment]
vm.getAvailbiltiySetReference() gives you the URI. Currently only option I see is to extract the last segment (which is availability set name) from this URI.

**Comment by netwmr01** [comment]
reopen the issue for SDK team to investigate the status code

**Comment by jianghaolu** [comment]
204 is a valid delete response code. Attaching the resource provider spec:
> Delete Resource (DELETE)
The API flow should be to:
1.	Respond to the initial DELETE request with a 202 Accepted;
2.	The response headers MUST include a Location header that points to a URL where the ongoing operation can be monitored;
3.	Optional: The response headers may include an Azure-AsyncOperation header pointing to an Operation resource (as described below).
4.	If a provisioningState field is used for the resource, it MUST transition to a non-terminal state like “Deleting”;
5.	If the DELETE completes successfully, the URL that was returned in the Location header MUST now return a 200 OK or 204 NoContent to indicate success and the resource MUST disappear.

**Comment by netwmr01** [comment]
@jianghaolu @anuchandy however the resource **didn't** disappear.

**Comment by jianghaolu** [comment]
That sounds like a server side issue. The server should not return 204 if the resource isn't successfully deleted. Please turn on logging and attach the traffic log so that we can forward to the service team.
