### ISSUE TITLE
[FEATURE REQ] Support setting AccessTier when using BlockBlobClient.getBlobOutputStream()

### ISSUE THREAD

**Issue by rvervaek** [Azure/azure-sdk-for-java#6391]
When I use the BlockBlobClient.getBlobOutputStream() method to upload data it is not possible to set the AccessTier for the blob. 

Provide an overloaded method getBlobOutputStream() that has a parameter AccessTier, that will write the data to the blob using the provided AccessTier.

**Comment by rickle-msft** [comment]
@rvervaek Thank you for pointing out this oversight. We will schedule some work to add an overload that accepts accessTier, metadata, and blob http headers.

**Comment by rickle-msft** [comment]
I am going to close this issue as the fix has been merged.
