### ISSUE TITLE
Remove snapshot dependency on azure-mgmt-resources test jar

### ISSUE THREAD

**Issue by jianghaolu** [Azure/azure-sdk-for-java#6411]
https://github.com/Azure/azure-sdk-for-java/blob/master/parent/pom.xml#L149 depends on a snapshot release of azure-mgmt-resources test jar. 

We couldn't release it because it seems like the partner release pipeline will strip out any test jar before uploading to Maven. 

We need to support it and release an official version of https://github.com/Azure/azure-libraries-for-java/tree/master/azure-mgmt-resources/src/test and update the SNAPSHOT dependency.

**Comment by mitchdenny** [comment]
I think @JimSuplizio might have cleaned this up, I can't see this dependency referenced anywhere in the root parent anymore.

**Comment by JimSuplizio** [comment]
> I think @JimSuplizio might have cleaned this up, I can't see this dependency referenced anywhere in the root parent anymore.

So it's not in the root pom anymore but there are still several pom files that use this dependency. It's a test only dependency.
sdk\batch\microsoft-azure-batch\pom.xml
sdk\keyvault\microsoft-azure-keyvault\pom.xml
sdk\keyvault\microsoft-azure-keyvault-extensions\pom.xml
sdk\keyvault\microsoft-azure-keyvault-test\pom.xml
