### ISSUE TITLE
encryptAsync thread never exits

### ISSUE THREAD

**Issue by waggyza** [Azure/azure-sdk-for-java#642]
When calling:
`Future<KeyOperationResult> result = vc.encryptAsync(keyIdentifier, JsonWebKeyEncryptionAlgorithm.RSAOAEP, byteText);`

The one thread created never exists even after the result is returned from 
`KeyOperationResult keyoperationResult = result.get();`
and the main thread has ended

**Comment by jianghaolu** [comment]
@pomortaz

**Comment by martinsawicki** [comment]
the KeyVault client library is not in this repo anymore, so if this is still an issue, it should go there:
https://github.com/azure/azure-keyvault-java
