### ISSUE TITLE
Support map of event positions for multi-partition receive 

### ISSUE THREAD

**Issue by srnagar** [Azure/azure-sdk-for-java#6420]
We don't have support for multi-partition receive in sync client. In async client, receive from multiple partitions takes a single event position that will be used for all partitions. 

One of the proposals from the arch board review was to consider supporting a map of event positions for each partition. With this approach, sync can support multi-partition receive and async receive will provide more control to the user.

**Comment by conniey** [comment]
This is a python feature we don't need.
