### ISSUE TITLE
When will the official new Java SDK be released?

### ISSUE THREAD

**Issue by grantfei** [Azure/azure-sdk-for-java#643]
I am developing a project which is planning to use the new Resource Management API.
I wonder how can I download all the new jar files and when will official ones be available.
Thanks.

**Comment by grantfei** [comment]
How can I get all the Azure jars and the third part jars?

**Comment by anuchandy** [comment]
Related issue: https://github.com/Azure/azure-sdk-for-java/issues/637

**Comment by jianghaolu** [comment]
You can use the beta1 release in maven today. However, be noticed that it's not stable and is going to change in the upcoming beta2 (end of June) and stable release (~late summer).

We don't have shaded jars at this moment yet. But they will be provided in a later release.
