### ISSUE TITLE
Maven Beta1 Exception in thread "main" java.lang.RuntimeException: Service or property not registered:  com.microsoft.azure.management.compute.ComputeManagementClient interface  

### ISSUE THREAD

**Issue by grantfei** [Azure/azure-sdk-for-java#645]
I have just downloaded SDK by adding a maven project.
however, when I tested, I caught the following error. Please help me. 

ResourceManagementClient resourceManagementClient = ResourceManagementService.create(config);
		ResourceGroupGetResult resouceGroupGetResult = resourceManagementClient.getResourceGroupsOperations().get(resourceGroupName);
		 
		ComputeManagementClient computeManagementClient = config.create(ComputeManagementClient.class);
		ServiceResponse<VirtualMachine> serviceResponse = computeManagementClient.getVirtualMachinesOperations()
				.get(resourceGroupName, vmName2, null);

Exception in thread "main" java.lang.RuntimeException: Service or property not registered:  com.microsoft.azure.management.compute.ComputeManagementClient interface com.microsoft.azure.management.compute.ComputeManagementClient
	at com.microsoft.windowsazure.core.DefaultBuilder.build(DefaultBuilder.java:198)

**Comment by anuchandy** [comment]
@grantfei possibly the issue is "Azure Core Resource Providers" are not registered for your subscription. To register the providers please follow below steps:

1. Install Windows Azure PowerShell [ https://azure.microsoft.com/en-us/documentation/articles/powershell-install-configure/ ]
2 Run the following Azure PowerShell commands:
      a. Login-AzureRmAccount
      b. Register-AzureRmResourceProvider -ProviderNamespace Microsoft.Compute
          Register-AzureRmResourceProvider -ProviderNamespace Microsoft.Storage
          Register-AzureRmResourceProvider -ProviderNamespace Microsoft.Network

**Comment by anuchandy** [comment]
Ok, there are similar issues reported and resolved here:

http://stackoverflow.com/questions/26073178/service-or-property-not-registered-error

https://github.com/Azure/azure-sdk-for-java/issues/465

**Comment by grantfei** [comment]
@anuchandy  thank you for your kind answer. I have tried your second way, but it failed.
It seems that the API in Beta1 is not proficient enough. At that time, there is no uniform API.
I have just found a workaround and used the underlying method.
But now I are frustrated about using different paradigm to use the SDK,
I hope I can use the mature and official API soon, which can ensure stability and high development   efficiency.

---------------------------------------------------------------------------
String tokenString = 
				AuthHelper.getAccessTokenFromServicePrincipalCredentials(parameters.get(ManagementConfiguration.URI),
						parameters.get("arm.aad.url"), parameters.get("arm.tenant"), parameters.get("arm.clientid"),
						parameters.get("arm.clientkey")).getAccessToken();
		TokenCredentials token = new TokenCredentials(null, tokenString);
		NetworkManagementClientImpl networkResourceProviderClient = new NetworkManagementClientImpl(parameters.get(arm_url), token);
		networkResourceProviderClient.setSubscriptionId(parameters.get(ManagementConfiguration.SUBSCRIPTION_ID));
		List<NetworkSecurityGroup> networkSGroup = networkResourceProviderClient.getNetworkSecurityGroupsOperations().list(resourceGroupName).getBody();

---------------------------------------------------------------------------

**Comment by jianghaolu** [comment]
@grantfei Glad you found a workaround. If you run into this again we are happy to file this issue to the service teams for you.

Yes the use of 1.0 will be significantly changed. But we believe the change is in a good way.

The new SDK infrastructure is experimented and prototyped here: https://github.com/microsoft/azure-shortcuts-java. And the active development work is happening right here in this repo in `master` branch. Please feel free to try (not production yet) and yell if you'd like to :)
