### ISSUE TITLE
Wiki - Tracing

### ISSUE THREAD

**Issue by joshfree** [Azure/azure-sdk-for-java#6454]
The Tracing section of the Java repo wiki is currently empty.

https://github.com/Azure/azure-sdk-for-java/wiki/Tracing

Tracing should be documented, similar to the existing Logging section https://github.com/Azure/azure-sdk-for-java/wiki/Logging-with-Azure-SDK

**Comment by samvaity** [comment]
Tracing wiki has been updated.
