### ISSUE TITLE
Wiki - Long Running Operations

### ISSUE THREAD

**Issue by joshfree** [Azure/azure-sdk-for-java#6455]
The Long Running Operations section of the Java repo wiki is currently empty.

https://github.com/Azure/azure-sdk-for-java/wiki/Long-running-operations

LRO conceptual topic should be completed similar to the topic of pagination https://github.com/Azure/azure-sdk-for-java/wiki/Pagination-and-Iteration

**Comment by JonathanGiles** [comment]
We now have https://docs.microsoft.com/en-nz/azure/developer/java/sdk/lro
