### ISSUE TITLE
Removing implementation classes from BridgeInternal  in CosmosSDK 

### ISSUE THREAD

**Issue by simplynaveen20** [Azure/azure-sdk-for-java#6466]
**Describe the bug**
Currently cosmos sdk uses BridgeInternal class to access non public members from one package to other. Due to which some of the implementation package classes got exposed as public api.

**Expected behavior**
We should not have internal implementation class in public api.

Example - [here](https://github.com/Azure/azure-sdk-for-java/blob/c43b7415cd89a84ba3daa2fad15c09a1387f9469/sdk/cosmos/azure-cosmos/src/main/java/com/azure/cosmos/BridgeInternal.java#L49)

**Comment by kushagraThapar** [comment]
This is done, as we have marked all the BridgeInternal classes as implementation only.
