### ISSUE TITLE
Increase Unit Test Coverage for Azure Core AMQP

### ISSUE THREAD

**Issue by alzimmermsft** [Azure/azure-sdk-for-java#6484]
Add additional unit tests to get closer to 90% coverage.

https://azuresdkartifacts.blob.core.windows.net/azure-sdk-for-java/test-coverage/azure-core-amqp/index.html#dn-c

**Comment by balajimurugesan2016** [comment]
Can I take up this issue?

**Comment by alzimmermsft** [comment]
@balajimurugesan2016, we would be more than happy for your contribution. 😃

I've assigned you to the issue.
