### ISSUE TITLE
What should be in the autorest branch? Particularly go-forward set of sources

### ISSUE THREAD

**Issue by selvasingh** [Azure/azure-sdk-for-java#649]
Today, many sub directories are missing in the autorest branch. Please indicate what sources will be in the 'autorest' branch or 1.0 version of the release and what sources will NOT be in the 'autorest' branch ASAP

**Comment by jianghaolu** [comment]
Per discussion, `autorest` is `master` now. 
ARM packages will live in new `master` and ASM will live in 0.9. servicebus, media, key vault, service runtime will go to their own repos.

**Comment by jianghaolu** [comment]
No action to take.
