### ISSUE TITLE
[FEATURE REQUEST] Add listing overload to accept continuation token

### ISSUE THREAD

**Issue by SukruthKS** [Azure/azure-sdk-for-java#6513]
**Query/Question**
I'm upgrading the storage SDK in my application from v8 to v12. In v8, there is a list blobs API which accepts a continuation token and gets the next page of blobs. However, in v12, I could not find a similar API and either I need to always get the first page of blobs and use the response iterable to list using the continuation token (as shown below) or preserve the response object to avoid listing the first page every time. Is there a better way? With the first approach, I'm making unnecessary requests and with the second one, I cannot preserve state and resume processing of blobs from where I left off or continue processing on a different machine. 

```
PagedIterable<BlobItem> response = containerClient.listBlobs();
Iterable<PagedResponse<BlobItem>> desiredPage = response.iterableByPage(continuationToken);
```

***Why is this not a Bug or a feature Request?***
NA

**Setup (please complete the following information if applicable):**
 - OS: Linux
 - IDE : IntelliJ
 - Version of the Library used: 12.0.0
 
 **Information Checklist**
 Kindly make sure that you have added all the following information above and checkoff the required fields otherwise we will treat the issuer as an incomplete report
- [x] Query Added
- [x] Setup information Added

**Comment by rickle-msft** [comment]
Hi, @SukruthKS. Thank you for posting this. The first option you posted is actually the recommended approach, and it shouldn't require you to get the first page. I've investigated the behavior of this operation, and it looks like there is a bug that causes some duplicate requests with the same token (though this does not cause duplicate results in your listing), but it will not require you to restart from the beginning. I am working with the team that owns this PagedIterable type to get a fix out for this. 

Additionally, given that what you shared is the recommended approach, it sounds like you would prefer a more clear means of specifying a continuation token? Would expect there to be a list overload that accepts this token?

**Comment by SukruthKS** [comment]
Thanks @rickle-msft for promptly looking into this! So if I just run the below statement, it does not actually send a request to get the first page until I invoke `nextI()` on the iterable?

```
PagedIterable<BlobItem> response = containerClient.listBlobs();
```

> Additionally, given that what you shared is the recommended approach, it sounds like you would prefer a more clear means of specifying a continuation token? Would expect there to be a list overload that accepts this token?
Either a list overload or using `ListBlobsOptions` would be preferable. It was not intuitive for me to arrive at the recommended approach. I first had to look through all the available list overloads and their parameters and then search the return type to see if there was an option to specify it. Given that there is a REST API to list blobs with the next marker, a more direct approach would be nice.

**Comment by rickle-msft** [comment]
Sure thing! And that is correct with some nuance about calling `next()`. The [reactor docs](https://projectreactor.io/docs/core/release/api/reactor/core/publisher/Flux.html#toIterable--) for how we create this iterable seem to be a bit misleading. While they say it is lazy, we are noticing that it only seems to be lazy insofar as waiting to call next to start, and after that it will eagerly fetch until the end of the stream, which means this iterable will try to eagerly list all your blobs, and that will be a problem. This is being tracked in #6518, and we are discussing a different implementation that will also lazy fetch as well as lazily subscribe. 

I also hear what you're saying about the overload to accept the continuation token rather than passing it into the return type. With your permission, I'd like to rename this issue to track adding the overload and allow #6518 to track the iterator behavior.

**Comment by SukruthKS** [comment]
> While they say it is lazy, we are noticing that it only seems to be lazy insofar as waiting to call next to start, and after that it will eagerly fetch until the end of the stream, which means this iterable will try to eagerly list all your blobs, and that will be a problem. This is being tracked in #6518, and we are discussing a different implementation that will also lazy fetch as well as lazily subscribe.

Good that you caught this! It was definitely going to be an issue for us as some of the containers we list can contain a very large number of blobs.


> I also hear what you're saying about the overload to accept the continuation token rather than passing it into the return type. With your permission, I'd like to rename this issue to track adding the overload and allow #6518 to track the iterator behavior.

Sure, please go ahead.

**Comment by rickle-msft** [comment]
We caught it while looking into the behavior as a part of this thread, so thanks for starting easy on us :)

I'm not sure this will make into the next release, but I will prioritize investigating this overload and stay on top of the eager iterator behavior and keep you updated.
