### ISSUE TITLE
[Storage] Storage clients incorrectly construct scope for BearerTokenAuthenticationPolicy

### ISSUE THREAD

**Issue by schaabs** [Azure/azure-sdk-for-java#6517]
This issue impacts all storage clients which support authenticating with `TokenCredential`. In `BuilderHelper` and in `QueueClientBuilder` when the `BearerTokenAuthenticationPolicy` is constructed the user specified endpoint host is used to construct the scope. 

https://github.com/Azure/azure-sdk-for-java/blob/6592e0b09d7de040b5927e1ce7dabddb4b0c7946/sdk/storage/azure-storage-blob/src/main/java/com/azure/storage/blob/implementation/util/BuilderHelper.java#L74-L75

https://github.com/Azure/azure-sdk-for-java/blob/6592e0b09d7de040b5927e1ce7dabddb4b0c7946/sdk/storage/azure-storage-queue/src/main/java/com/azure/storage/queue/QueueClientBuilder.java#L145-L146

This scope will be incorrect and authentication will fail if the user passes a vanity url to the client. These should instead define well known values for scopes such as "https://storage.azure.com/.default".

**Comment by rickle-msft** [comment]
Thanks, @schaabs, for finding this. We'll add this to our backlog and work on getting this fix in.

**Comment by gapra-msft** [comment]
TODO: Double check this is fixed

**Comment by gapra-msft** [comment]
Hi @schaabs 

I don't know too much about bearer token scopes so I wanted to clarify the fix with you, are you saying we should just default to using the scope "https://storage.azure.com/.default" no matter what endpoint the user passes in?

**Comment by joshfree** [comment]
Do we have the same bug in https://github.com/Azure/azure-sdk-for-java/blob/master/sdk/appconfiguration/azure-data-appconfiguration/src/main/java/com/azure/data/appconfiguration/ConfigurationClientBuilder.java#L195

/cc @mssfang

**Comment by mssfang** [comment]
@schaabs Do you know what score value I can use for AppConfig? such as "https://appconfiguration.azconfig.io/.default", but it doesn't work?

**Comment by mssfang** [comment]
@joshfree  As discussed offline in a meeting with @schaabs , service team and rest of language developers. There is no changes needed in current version of AppConfig SDK. AppConfig service will still use the Custom Scope in AAD. It is service specified.
