### ISSUE TITLE
[BUG] PagedIterable.iterableByPage(token) processes listing operations eagerly

### ISSUE THREAD

**Issue by rickle-msft** [Azure/azure-sdk-for-java#6518]
**Describe the bug**
Calling pagedIterable.iterableByPage(token) results in a network call to fetch the next page using the given token. Calling .iterator().next() on this iterable results in an identical network call. 

I believe it's because the iterableByPage(token) method eagerly calls the nextPageFunction.apply() instead of storing the token and waiting for a call to next. 

**Code Snippet**
```
        int NUM_BLOBS = 10
        int PAGE_SIZE = 6
        for (int i = 0; i < NUM_BLOBS; i++) {
            PageBlobClient bc = cc.getBlobClient(generateBlobName()).getPageBlobClient()
            bc.create(512)
        }

        PagedIterable<BlobItem> pagedIterable = cc.listBlobs(new ListBlobsOptions().setMaxResultsPerPage(PAGE_SIZE), null)
        PagedResponse pagedSyncResponse1 = pagedIterable.iterableByPage().iterator().next()
        PagedIterable<BlobItem> pagedIterable2 = cc.listBlobs(new ListBlobsOptions().setMaxResultsPerPage(PAGE_SIZE), null)
        PagedIterable byPageFromToken = pagedIterable2.iterableByPage(pagedSyncResponse1.getContinuationToken())
        def pageAfterToken = byPageFromToken.iterator().next()
```

**Expected behavior**
Only two list calls should be made here, one for each of the lines that has .iterator().next(). Instead, there is a third network call coming from the line that calls iterableByPage(token), and it is identical to the request on the next line.

**Comment by rickle-msft** [comment]
I've tested this further, and I am seeing that each call to next on the paged iterable is making two service calls instead of 1. It also seems that requests are being made eagerly.

**Comment by rickle-msft** [comment]
It seems that the number of requests is actually correct and the apparent doubles were caused by the first iterator continuing to eagerly process the list.

**Comment by alzimmermsft** [comment]
@anuchandy could you verify whether the new `PagedFlux`/`PagedIterable` enhancements have resolved this issue?

**Comment by alzimmermsft** [comment]
PR #6465 should have resolved this issue.
