### ISSUE TITLE
[FEATURE REQ] TokenCredential implementation for bearer token

### ISSUE THREAD

**Issue by gapra-msft** [Azure/azure-sdk-for-java#6525]
This feature request comes from a customer query linked here https://github.com/Azure/azure-sdk-for-java/issues/6509

**Is your feature request related to a problem? Please describe.**
Currently there is no implementation of TokenCredential that simply accepts an existing bearer token. 

**Describe the solution you'd like**
An implementation of TokenCredential that accepts an existing bearers token.

**Information Checklist**
Kindly make sure that you have added all the following information above and checkoff the required fields otherwise we will treat the issuer as an incomplete report
- [x] Description Added
- [x] Expected solution specified

**Comment by SukruthKS** [comment]
@gapra-msft what is the ETA on this?

**Comment by gapra-msft** [comment]
Hi @SukruthKS I'll follow up with the identity team and make sure it's on their radar.

**Comment by jianghaolu** [comment]
Hi @SukruthKS 
I'm the dev working on the authentication/identity. I'd like to understand the issue from you a little more.
1. Is this currently blocking for you guys?
2. We designed `TokenCredential` to be a functional interface: https://github.com/Azure/azure-sdk-for-java/blob/master/sdk/core/azure-core/src/main/java/com/azure/core/credential/TokenCredential.java. If you have a token already, you can simply use it like `BlobServiceClient = new BlobServiceClientBuilder().credential(request -> Mono.just(myAccessToken))`. Do you think this will meet your need?

If not I'm happy to hear about your specific scenario!

**Comment by SukruthKS** [comment]
Hi @jianghaolu,

> 1. Is this currently blocking for you guys?

Yes, it is currently blocking. I cannot use the v12 SDK until this is sorted out.

>2. We designed TokenCredential to be a functional interface: https://github.com/Azure/azure-sdk-for-java/blob/master/sdk/core/azure-core/src/main/java/com/azure/core/credential/TokenCredential.java. If you have a token already, you can simply use it like BlobServiceClient = new BlobServiceClientBuilder().credential(request -> Mono.just(myAccessToken)). Do you think this will meet your need?

I was not aware not that an existing token could be passed like this and this should mitigate my issue (I will try it out later). It would be nice if I don't have to bring in async framework artifacts like `Mono` into my application, I'm using the sync version of the storage SDK.

I was also looking into an existing implementation of TokenCredential - `ClientSecretCredential.java`. It doesn't seem to cache the token and goes to AAD for every request so that would add lot more calls. Is there an implementation that caches the token after fetching?

**Comment by jianghaolu** [comment]
@SukruthKS 
Thanks for the quick response. I understand your concern now. I've opened an issue at https://github.com/Azure/azure-sdk-for-java/issues/7480 to track this.

For ClientSecretCredential - we simply call the msal4j library to get a token and I'm surprised to know that they don't cache the token (they cache it for some other operations). I'll investigate and open an issue accordingly.

**Comment by SukruthKS** [comment]
Thanks @jianghaolu !

> For ClientSecretCredential - we simply call the msal4j library to get a token and I'm surprised to know that they don't cache the token (they cache it for some other operations). I'll investigate and open an issue accordingly.

I only briefly looked into the code to figure out if it's caching and I could be wrong about it. Please let me know what you find.

**Comment by jianghaolu** [comment]
Closing this as this feature is rejected from https://github.com/Azure/azure-sdk-for-java/issues/7480
