### ISSUE TITLE
SharedTokenCacheCredential should allow users to specify the tenant in addition to username

### ISSUE THREAD

**Issue by jianghaolu** [Azure/azure-sdk-for-java#6535]
Currently we only filter the shared token cache by userame, however in many cases this is not enough to distinguish the account to use. Callers should also be able to specify a tenantId as well to distinguish when their username is a guest user in multiple tenants.

See .NET issue: https://github.com/Azure/azure-sdk-for-net/issues/8689

**Comment by g2vinay** [comment]
This has been added in the latest beta release.
