### ISSUE TITLE
Onboard December releases on docs.microsoft.com

### ISSUE THREAD

**Issue by kaerm** [Azure/azure-sdk-for-java#6549]
- [ ] Onboard the following packages on docs.microsoft.com (all except legacy in com.azure)
**Latest:**
azure-core 1.1.0
azure-identity 1.0.1
azure-storage-file-share 12.0.0
azure-storage-common 12.0.0
azure-storage-blob 12.1.0
azure-storage-queue 12.1.0
azure-storage-blob-cryptography 12.0.0
azure-storage-blob-batch 12.0.0
azure-keyvault-keys 4.0.0
azure-keyvault-secrets 4.0.0
**Preview:**
azure-keyvault-certificates P 4.0.0-preview.6
azure-storage-file-datalake 12.0.0-preview.6
azure-messaging-eventhubs 5.0.0-preview.6
azure-messaging-eventhubs-checkpointstore-blob 1.0.0-preview.4
azure-data-appconfiguration 1.0.0-preview.7
azure-cosmos 4.0.0-preview.1
**Legacy:**
_com.microsoft.azure_ azure-storage 8.4.0

- [ ] Remove following packages from preview:
azure-storage-file-share 12.0.0-preview.5
azure-storage-file  12.0.0-preview.4

@joshfree  to confirm version numbers

**Comment by scbedd** [comment]
Diffed against the latest released tags. Updated list: 


**Latest**

- [ ] azure-core 1.1.0
- [ ] azure-identity 1.0.1
- [ ] azure-storage-file-share 12.0.0
- [ ] azure-storage-common 12.0.0
- [ ] azure-storage-blob 12.1.0
- [ ] azure-storage-queue 12.1.0
- [ ] azure-storage-blob-cryptography 12.1.0
- [ ] azure-storage-blob-batch 12.1.0
- [ ] azure-keyvault-keys 4.0.1
- [ ] azure-keyvault-secrets 4.0.1

**Preview**

- [ ] azure-keyvault-certificates P 4.0.0-preview.6
- [ ] azure-storage-file-datalake 12.0.0-preview.6
- [ ] azure-messaging-eventhubs 5.0.0-preview.6
- [ ] azure-messaging-eventhubs-checkpointstore-blob 1.0.0-preview.4
- [ ] azure-data-appconfiguration 1.0.0-preview.7
- [ ] azure-cosmos 4.0.0-preview.1
- [ ] azure-core-tracing-opencensus 1.0.0-beta.5

**Comment by scbedd** [comment]
I do not have access to azure-java-reference, but will work up the PR and ping Robert for access.

**Comment by scbedd** [comment]
[PR](https://github.com/MicrosoftDocs/azure-java-reference/pull/1/files)

**Comment by scbedd** [comment]
Updated [smoke test](https://github.com/MicrosoftDocs/azure-java-reference/pull/6/files) PR.
