### ISSUE TITLE
azure-storage-blob unit tests cannot be compiled under JDK 17

### ISSUE THREAD

**Issue by JonathanGiles** [Azure/azure-sdk-for-java#6551]
Because the unit tests for azure-storage-blob are written in Groovy, they introduce a non-standard toolchain into the build system. This results in a build failure under JDK 17 with the following terminal output:

```shell
[INFO] --- maven-compiler-plugin:3.8.1:testCompile (default-testCompile) @ azure-storage-blob ---
[INFO] Changes detected - recompiling the module!
[INFO] Using Groovy-Eclipse compiler to compile both Java and Groovy files
[INFO] release 11 is not found in the system
```

This is visible when executing a build with the following command: `mvn -f pom.client.xml clean package -DskipTests`.

The expected outcome is that the azure-storage-blob unit tests will compile under any version of the JDK, from JDK 8 up to the latest release.

**Comment by mclay** [comment]
please assign me this issue

**Comment by leoger** [comment]
> This is visible when executing a build with the following command: `mvn -f pom.client.xml clean package -DskipTests`.

I have an alternate repro to report since I don't see any file named `pom.client.xml` in the repo. ( And `git log --diff-filter=D --summary | grep -e 'delete.*pom.client'` shows me that there has only been one such file deleted but it was in `keyvault`, not `azure-storage-blob`.)

```
# optional 
SKIP_STUFF="-Dcheckstyle.skip -Dgpg.skip -Dmaven.javadoc.skip -Drevapi.skip -DskipSpringITs -DskipTests -Dspotbugs.skip"

# the core of the repro
mvn -X install -f pom.xml -pl :azure-storage-blob $SKIP_STUFF
```

**Comment by leoger** [comment]
For reference, here is one of the lines in the Groovy Eclipse compiler that is emitting the error we see:

https://github.com/groovy/groovy-eclipse/blob/25675391e1a5e9af708e1dd2c785ae420a83c645/jdt-patch/e410/org.eclipse.jdt.core/batch/org/eclipse/jdt/internal/compiler/batch/ClasspathJep247.java#L127

**Comment by mikeharder** [comment]
@kasobol-msft: Can someone please take a look and see how easy this is to fix?  It is blocking our adoption of JDK 17 LTS.

@JonathanGiles reported the following:

> I see things progress if I pull forward the dependency versions of groovy-eclipse-compiler and groovy-eclipse-batch, but it then results in test compilation failures (15 warnings on my machine). For the record, I went to these versions: `groovy-eclipse-compiler: 3.7.0` and `groovy-eclipse-batch: 3.0.8-01`

**Comment by kasobol-msft** [comment]
This has been addressed in 
https://github.com/Azure/azure-sdk-for-java/pull/24471
https://github.com/Azure/azure-sdk-for-java/pull/24477

![image](https://user-images.githubusercontent.com/61715331/135658326-4ec6511a-7964-4a15-a487-1b2f1158dc69.png)
