### ISSUE TITLE
Server Exception while creating VM with VMExtension

### ISSUE THREAD

**Issue by netwmr01** [Azure/azure-sdk-for-java#657]
Error is the following:
statusCode:BadRequest serviceRequestId: statusMessage:{"error":{"code":"InvalidRequestContent","message":"The request content was invalid and could not be deserialized: 'Could not find member 'resources' on object of type 'ResourceDefinition'. Path 'resources', line 1, position 2179.'."}}

Code to create the vme and setting it to vm.
VirtualMachineExtension vme = new VirtualMachineExtension();
    vme.setName("prepare");
    ClassLoader classLoader = getClassLoader();
    String result= IOUtils.toString(classLoader.getResourceAsStream("prepare-disks.json"));
    
    vme.setLocation(context.getLocation());
    vme.setPublisher("Microsoft.OSTCExtensions");
    vme.setExtensionType("CustomScriptForLinux");
    vme.setTypeHandlerVersion("1.2");
    vme.setSettings(result);

ArrayList<VirtualMachineExtension> extensions = new ArrayList<VirtualMachineExtension>(1);
extensions.add(createCustomizedScript(role, context));
vm.setExtensions(extensions);

**Comment by anuchandy** [comment]
By looking at the source code xplat cli tool, it looks like they do this via two steps

1. Create VM - https://github.com/Azure/azure-xplat-cli/blob/master/lib/commands/arm/vm/vmClient._js#L1156
2. Set Extension - https://github.com/Azure/azure-xplat-cli/blob/master/lib/commands/arm/vm/vmClient._js#L1159

let me check with /loop compute team to confirm this can be done in one step

**Comment by anuchandy** [comment]
Ok same issue is reported here: https://github.com/Azure/azure-sdk-for-java/issues/600

At least in 0.9.3 you need to set extension using separate API call.

**Comment by netwmr01** [comment]
Ok, thanks.

**Comment by jianghaolu** [comment]
Closing as resolved.
