### ISSUE TITLE
Convert sdk/cosmos and sdk/cosmosdb

### ISSUE THREAD

**Issue by mitchdenny** [Azure/azure-sdk-for-java#6573]
In the Java repo we have ```sdk/cosmos``` and ```sdk/cosmosdb``` with management plane and data plane being split between them. We need to get these converged as it is out of step with the overall repo structure.

**Comment by mitchdenny** [comment]
@weidongxu-microsoft and @joshfree how can we get this done. It is kinda messy having both folders under ```sdk/```. Which is the correct string, and will we need to coordinate this across the branches that are being used for active development?

**Comment by weidongxu-microsoft** [comment]
@mitchdenny If they are same we can easily move mgmt. Let me know if you want cosmosdb merged into cosmos folder (python got cosmos I assume this is the one).

**Comment by kushagraThapar** [comment]
@mitchdenny can we close this now ?
