### ISSUE TITLE
[BUG] Dead link to API documentation

### ISSUE THREAD

**Issue by pelithne** [Azure/azure-sdk-for-java#6577]
This issue describes a fault in the readme file of the service bus SDK (in https://github.com/Azure/azure-sdk-for-java/tree/master/sdk/servicebus)

The link to API documentation is dead. This link: https://docs.microsoft.com/en-us/java/api/overview/azure/servicebus/clientlibrary

**Comment by joshfree** [comment]
Thanks for reporting this @pelithne.

**Comment by joshfree** [comment]
Related https://github.com/Azure/azure-sdk/issues/735

**Comment by kusiroll** [comment]
@joshfree how can I help with this?

**Comment by jongio** [comment]
Closing this as I can't find that link referenced anywhere.  Please reopen if you do.
