### ISSUE TITLE
Event Hub library version is declared in AMQP package

### ISSUE THREAD

**Issue by srnagar** [Azure/azure-sdk-for-java#6582]
Move the library version constant to Event Hubs library. It's currently in AMQP library.

https://github.com/Azure/azure-sdk-for-java/blob/master/sdk/core/azure-core-amqp/src/main/java/com/azure/core/amqp/implementation/ClientConstants.java#L10

**Comment by sima-zhu** [comment]
One more action item for the issue is to remove hard-coded version as described in https://github.com/Azure/azure-sdk-for-java/pull/6557
