### ISSUE TITLE
[BUG] Scrubbing in storage logging

### ISSUE THREAD

**Issue by SukruthKS** [Azure/azure-sdk-for-java#6585]
**Describe the bug**
Few issues I found related to log redaction logic in storage SDK:

- SAS token signature is not scrubbed when logging the request URL. Example:
```
[main] INFO com.azure.storage.blob.implementation.ServicesImpl$ServicesService.getProperties - --> GET https://images.blob.core.windows.net?restype=service&comp=properties&sv=2019-02-02&ss=bf&srt=sco&sp=rla&se=2019-11-27T16:03:21Z&st=2019-11-27T08:03:21Z&spr=https&sig=NZX%2FZH7GFSPgmb7j62GldqDEW%2BINoFKlAC4euoxM1Xc%3D
```

- Some of the useful headers are not included in the default whitelist of headers that are not scrubbed. Any reason?
```
x-ms-version:REDACTED
x-ms-error-code:REDACTED
x-ms-request-id:REDACTED
```

***Exception or Stack Trace***
NA

**To Reproduce**
Add an slf4j logger like `org.slf4j:slf4j-simple` to the project and try the below code:
```
String endpoint = "https://images.blob.core.windows.net/";

BlobServiceClient client = BlobServiceClientBuilder()
            .endpoint(endpoint)
            .sasToken("sv=2019-02-02&ss=bf&srt=sco&sp=rla&se=2019-11-27T16:03:21Z&st=2019-11-27T08:03:21Z&spr=https&sig=NZX%2FZH7GFSPgmb7j62GldqDEW%2BINoFKlAC4euoxM1Xc%3D")
            .httpLogOptions(new HttpLogOptions().setLogLevel(HttpLogDetailLevel.BODY_AND_HEADERS))
            .configuration(Configuration.getGlobalConfiguration().put("AZURE_LOG_LEVEL", "1"))
            .buildClient();

BlobServiceProperties properties = client.getProperties();
```

***Code Snippet***
Added above

**Expected behavior**
- SAS token signature should be scrubbed when logging the request URL
- Good to include useful headers like `x-ms-error-code`, `x-ms-request-id`, `x-ms-version` etc in the default list of headers that are not scrubbed.

**Screenshots**
NA

**Setup (please complete the following information):**
 - OS: Linux
 - IDE : IntelliJ
 - Version of the Library used: 12.0.0

**Additional context**

**Information Checklist**
Kindly make sure that you have added all the following information above and checkoff the required fields otherwise we will treat the issuer as an incomplete report
- [x] Bug Description Added
- [x] Repro Steps Added
- [x] Setup information Added

**Comment by rickle-msft** [comment]
Hi, @SukruthKS. Thank you for your patience through the holiday break. Logging is centralized in Azure Core, so I am tagging some folks from that team who will best be able to answer your questions and update the logging as needed. @alzimmermsft @joshfree

**Comment by rickle-msft** [comment]
Quick update. It looks like #6522 should address the concern about logging the sas signature. As I understand it, that went out with 1.1.0 of azure last week. We haven't yet released a new version of Storage that depends on it, but that should be coming this week. If you need, you can pin version 1.1.0 of azure core to pull in the fix early; it should be a non breaking release, so I think Storage should work fine with it.

**Comment by alzimmermsft** [comment]
Hello @SukruthKS,

For the header redaction issue, `HttpLogOptions` has two sets which determine which query parameters and HTTP headers should be logged. Within Azure Storage Blobs each builder should have a method named `getDefaultHttpLogOptions` which will return an `HttpLogOptions` instance with these values set to what we believe are safe for logging. This would be the revised codesnippet to enable many of the REDACTED headers to be logged:

```java
String endpoint = "https://images.blob.core.windows.net/";

BlobServiceClient client = BlobServiceClientBuilder()
    .endpoint(endpoint)
    .sasToken("sv=2019-02-02&ss=bf&srt=sco&sp=rla&se=2019-11-27T16:03:21Z&st=2019-11-27T08:03:21Z&spr=https&sig=NZX%2FZH7GFSPgmb7j62GldqDEW%2BINoFKlAC4euoxM1Xc%3D")
    .httpLogOptions(BlobServiceClientBuilder.getDefaultHttpLogOptions().setLogLevel(HttpLogDetailLevel.BODY_AND_HEADERS))
    .configuration(Configuration.getGlobalConfiguration().put("AZURE_LOG_LEVEL", "1"))
    .buildClient();

BlobServiceProperties properties = client.getProperties();
```

**Comment by SukruthKS** [comment]
Thanks @rickle-msft and @alzimmermsft !
