### ISSUE TITLE
[QUERY] Details of failures with Azure Storage Batch API

### ISSUE THREAD

**Issue by SukruthKS** [Azure/azure-sdk-for-java#6589]
**Query/Question**
Batch SDK throws a `BlobBatchStorageException` when any of the requests in the batch fail and the exception contains a list of `BlobStorageException`s corresponding to each of the failed requests. Is there a way to know which blob a particular `BlobStorageException` corresponds to? 

***Why is this not a Bug or a feature Request?***
NA

**Setup (please complete the following information if applicable):**
 - OS: Linux
 - IDE : IntelliJ
 - Version of the Library used: 12.0.0
 
 **Information Checklist**
 Kindly make sure that you have added all the following information above and checkoff the required fields otherwise we will treat the issuer as an incomplete report
- [x] Query Added
- [x] Setup information Added

**Comment by SukruthKS** [comment]
Hi @rickle-msft could you please take a look at this one when you get a chance?

**Comment by rickle-msft** [comment]
@SukruthKS Sorry for the delay on this and thank you for bumping it as it must have slipped through our triage. `BlobStorageException` should have a `getResponse()` method which in turn has a getter for its associated request object. The request object should have all the information you need to identify the blob in the url. I realize that's quite a few levels of indirection, though. Is there a particular way in which you'd like to have that information presented? Is the name sufficient? Or are you looking for a reference to the full client object used to create the request?

**Comment by SukruthKS** [comment]
Thanks @rickle-msft ! The blob URL should be sufficient for my needs. I can use the `BlobUrlParts` utility class to extract snapshot, blob name etc. As you mentioned, it's a few levels of indirection but at least the information is present :)

**Comment by rickle-msft** [comment]
Sounds good! I'm going to close this issue since it sounds like your question has been resolved, but if that workflow becomes cumbersome or otherwise insufficient, please feel free to reopen it and we can improve it at that time.
