### ISSUE TITLE
unable to create NetworkSecurityGroup using api

### ISSUE THREAD

**Issue by netwmr01** [Azure/azure-sdk-for-java#659]
code sample is below:
```java
NetworkSecurityGroup nsg = new NetworkSecurityGroup();
      nsg.setName("testnsg");
      nsg.setLocation(context.getLocation());
      SecurityRule sr= new SecurityRule();
      sr.setPriority(100);
      sr.setProtocol("*");
      sr.setSourceAddressPrefix("*");
      sr.setSourcePortRange("*");
      sr.setAccess("Allow");
      sr.setDirection("Inbound");
      sr.setDestinationAddressPrefix("*");
      sr.setDestinationPortRange("*");
      ArrayList<SecurityRule> srs = new ArrayList<SecurityRule>();
      srs.add(sr);
      
      nsg.setSecurityRules(srs);
      networkResourceProviderClient.getNetworkSecurityGroupsOperations().createOrUpdate(resourceGroupName, nsg
          .getName(), nsg);

```

server return 
PROPERTIES 
statusCode:BadRequest serviceRequestId:b9c90aed-1e3d-4708-ae5b-f9dc03560d62 statusMessage:{"error":{"code":"InvalidRequestFormat","message":"Cannot parse the request.","details":[]}} responseBody:{"error":{"code":"InvalidRequestFormat","message":"Cannot parse the request.","details":[]}}

**Comment by netwmr01** [comment]
looks like * was remove from the string.

**Comment by anuchandy** [comment]
In the request payload security group section appear as 

"securityGroup: [ { properties: { "name": ... , ... }, ..]]"

I think it should be: 

"securityGroup: [ { { "name": ... , ...}, ...]"

will confirm whether this is a bug in SDK.

**Comment by anuchandy** [comment]
@netwmr01 you have to specify a name for the rule 

sr.setName("nsgrule1");

@jianghaolu fyi this is not a SDK issue, so no need to patch it.

**Comment by netwmr01** [comment]
@anuchandy @jianghaolu without rule, the NSG creation will still failed. so user have to create a rule? but base on rest api and portal, user don't need to creat rules for NSG to be created.

**Comment by anuchandy** [comment]
I just tried creating nsg without rule as below and it worked

```
NetworkResourceProviderClient networkResourceProviderClient = NetworkResourceProviderService.create(config);

        NetworkSecurityGroup newNsg = new NetworkSecurityGroup();
        newNsg.setName("nsg3");
        newNsg.setLocation("eastus");
        networkResourceProviderClient.getNetworkSecurityGroupsOperations().createOrUpdate("nsggrp", "nsg3", newNsg);

```

sever payload:

{"properties":{"securityRules":[],"defaultSecurityRules":[]},"name":"nsg3","location":"eastus","tags":{}}

**Comment by netwmr01** [comment]
@anuchandy @jianghaolu 
It will fail when you attach to a nic and creat vm. on 0.9.3

**Comment by anuchandy** [comment]
Can you share full repro code?

**Comment by netwmr01** [comment]
@anuchandy @jianghaolu 

NetworkSecurityGroup nsg = new NetworkSecurityGroup();
      nsg.setName(nsgName);
      nsg.setLocation(context.getLocation());
      networkResourceProviderClient.getNetworkSecurityGroupsOperations().createOrUpdate(resourceGroupName, nsg.getName(), nsg);
      NetworkHelper.createVirtualNetwork(networkResourceProviderClient, context);
      /*
      * some context setting in between
      * */
      computeManagementClient.getVirtualMachinesOperations()
          .beginCreatingOrUpdating(
              context.getResourceGroupName(),
              context.getVMInput()
          );



You will find the following ERROR:
com.microsoft.windowsazure.exception.ServiceException: InvalidRequestFormat: Cannot parse the request.

**Comment by anuchandy** [comment]
@netwmr01 thanks.. you mentioned that "It will fail when you attach to a nic and creat vm". In the above repo sample I don't see where exactly we are setting the NSG to VM/NIC. Am i missing something?

**Comment by netwmr01** [comment]
@anuchandy That is in additional context setting

// Currently sdk created NSG will fail. Update NIC to use existing NSG is fine.
    ResourceId id = new ResourceId();
    id.setId(nsg.getId());
    context.getNetworkInterface().setNetworkSecurityGroup(id);
    networkResourceProviderClient.getNetworkInterfacesOperations().createOrUpdate(context.getResourceGroupName(),
        context.getNetworkInterfaceName(), context.getNetworkInterface());

**Comment by anuchandy** [comment]
@netwmr01 please see below working code:

```java

            NetworkResourceProviderClient networkClient = createNetworkClient();

            // Create NSG
            //
            NetworkSecurityGroup nsg = new NetworkSecurityGroup();
            nsg.setName("nsg2");
            nsg.setLocation("eastus");

            SecurityRule rule = new SecurityRule();
            rule.setName("rule1");
            rule.setPriority(100);
            rule.setProtocol("*");
            rule.setSourceAddressPrefix("*");
            rule.setSourcePortRange("*");
            rule.setAccess("Allow");
            rule.setDirection("Inbound");
            rule.setDestinationAddressPrefix("*");
            rule.setDestinationPortRange("*");

            ArrayList<SecurityRule> rules = new ArrayList<>();
            rules.add(rule);
            nsg.setSecurityRules(rules);
            networkClient.getNetworkSecurityGroupsOperations().createOrUpdate("nsggrp", "nsg2", nsg);

            // Create virtual network
            //
            VirtualNetwork vnet = new VirtualNetwork();
            vnet.setName("vnet1");
            vnet.setLocation("eastus");

            AddressSpace addressSpace = new AddressSpace();
            ArrayList<String> addressPrefixes = new ArrayList<>();
            addressPrefixes.add("10.0.0.0/24");
            addressSpace.setAddressPrefixes(addressPrefixes);
            vnet.setAddressSpace(addressSpace);

            Subnet subnet = new Subnet();
            subnet.setName("subnet1");
            subnet.setAddressPrefix("10.0.0.0/24");
            ArrayList<Subnet> subnets = new ArrayList<>();
            subnets.add(subnet);
            vnet.setSubnets(subnets);

            networkClient.getVirtualNetworksOperations().createOrUpdate("nsggrp", "vnet1", vnet);

            // Gets the subnet
            Subnet s = networkClient.getSubnetsOperations().get("nsggrp", "vnet1", "subnet1").getSubnet();
            ResourceId subnetResourceId = new ResourceId();
            subnetResourceId.setId(s.getId());

            // Gets the NSG
            NetworkSecurityGroup n = networkClient.getNetworkSecurityGroupsOperations().get("nsggrp", "nsg2").getNetworkSecurityGroup();
            ResourceId nsgResourceId = new ResourceId();
            nsgResourceId.setId(n.getId());

            // Create network interface
            //
            NetworkInterface nic = new NetworkInterface();
            nic.setName("nic1");
            nic.setLocation("eastus");

            NetworkInterfaceIpConfiguration nicIPConfig = new NetworkInterfaceIpConfiguration();
            nicIPConfig.setName("Nic-IP-config");
            nicIPConfig.setSubnet(subnetResourceId);

            ArrayList<NetworkInterfaceIpConfiguration> nicIPConfigs = new ArrayList<>();
            nicIPConfigs.add(nicIPConfig);

            nic.setIpConfigurations(nicIPConfigs);
            nic.setNetworkSecurityGroup(nsgResourceId);

            networkClient.getNetworkInterfacesOperations().createOrUpdate("nsggrp", "nic1", nic);

```

**Comment by jianghaolu** [comment]
No action to take at this moment. 
With 1.0.0-beta2 released, this should be simplified. A sample can be found here: https://github.com/Azure-Samples/network-java-manage-network-security-group/blob/master/src/main/java/com/microsoft/azure/management/network/samples/ManageNetworkSecurityGroup.java. 

@selvasingh 
> @anuchandy @jianghaolu without rule, the NSG creation will still failed. so user have to create a rule? but base on rest api and portal, user don't need to creat rules for NSG to be created.

A valid scenario to be added.

**Comment by burnsjw83** [comment]
@jianghaolu this sample is absolutely not simplified.  Think of this case:
I want to write an application to deploy resources, including the network, NSG and rules contained in the NSG.  The newer syntax removes any possibility of me being able to write methods to add security rules that are not VERY strictly defined.
There is no method to add ACCESS, beyond "allowInbound, denyInbound, allowOutbound, denyOutbound".  There's no way for me to pass in the Access type without calling those methods from code... this means if I want to be able to have a rule created dynamically, I have to have every possible combination (allow inbound with all ports, allow inbound with a specific inbound port, with a specific destination port, allow inbound with a specific destination port but any source port... etc)  This ends up being A VERY LARGE number of methods, with a very complicated control structure to determine which method to call.
Why is there no way to create a rule, pass it a variable that is the access type, a variable that is the direction, a variable that is the source port (which must be string to allow it to be a single port, a range, or * for any), a variable that is destination port, a variable that is protocol?
It appears there used to be, and now the usage is extremely broken.  I'm not sure I will be able to meet my needs with this SDK now...
