### ISSUE TITLE
[QUERY] Log what DefaultAzureCredential picks up (managed identity or env vars)

### ISSUE THREAD

**Issue by snobu** [Azure/azure-sdk-for-java#6591]
Is there a way to tell what type of credentials (env vars/managed identity) is [`DefaultAzureCredential`](https://github.com/Azure/azure-sdk-for-java/blob/master/sdk/identity/azure-identity/src/main/java/com/azure/identity/DefaultAzureCredential.java) using?

I would like to log something along these lines:

```
[Info] Using Managed Identity to acquire an access token.
```

or

```
[Info] Using Environment Variables (service principal) to acquire an access token.
```

after calling

```java
DefaultAzureCredential credential = new DefaultAzureCredentialBuilder().build();
```

**Comment by jongio** [comment]
See https://github.com/Azure/azure-sdk-for-net/issues/8948 for example of how to get this with AzureEventSourceListener. I will get a sample in Java soon.

**Comment by snobu** [comment]
I'm unable to find `AzureEventSourceListener` type in the Java SDK. A sample would be highly appreciated!

**Comment by jongio** [comment]
Sorry for the delay @snobu I'm still looking into this.  (Java is not my primary language, so reaching out to some folks)

**Comment by snobu** [comment]
No worries, Jon. I believe this would be a good addition to the SDK samples once out. I'm thinking debug sessions primarily (_Learning in production_ sessions).

**Comment by jianghaolu** [comment]
Just a quick update we are having a cross-language overhaul for our logging mechanisms including addressing this need. I'll update here when a PR is open and community review is welcomed.

**Comment by snobu** [comment]
Sounds great! Appreciate the update.

**Comment by jianghaolu** [comment]
this feature has been merged in https://github.com/Azure/azure-sdk-for-java/pull/12268
