### ISSUE TITLE
[SDK 1.0.0-beta1] VirtualMachineScaleSetVMsOperations.list constantly returns 429 http status code

### ISSUE THREAD

**Issue by scotmoor** [Azure/azure-sdk-for-java#660]
When making the following 'list' operation call, a _very_ high percentage return with a HTTP status code of 429 - Too many requests

The call:
**VirtualMachineScaleSetVMsOperations.list(<resourceGroupName>, <serverGroupName>, null, null, "instanceView"). body**

We call the 'list' operation for several different resources (load balancers, scale sets, etc.) in addition to the VirtualMachineScaleSetVM resource but this is the only one where we see this issue. It's also the only resource where our 'list' call specifies a value for the "expand" parameter, which we need to do so we can get the InstanceView properties. While It doesn't happen on every single call,  a rough guess would be that it happens ~80% of the time and it can even happen on the very first 'list' call we make for this resource

**Comment by martinsawicki** [comment]
@milismsft - you're solving this in v1.2

**Comment by milismsft** [comment]
PR sent (https://github.com/Azure/azure-sdk-for-java/pull/1842)

**Comment by martinsawicki** [comment]
addressed in v1.2
