### ISSUE TITLE
[BUG] UserAgent policy seems violating from telemetry guideline 

### ISSUE THREAD

**Issue by anuchandy** [Azure/azure-sdk-for-java#6620]
This [guideline](https://azure.github.io/azure-sdk/general_azurecore.html#telemetry-policy) defines "[<application_id> ]azsdk-<sdk_language>-<package_name>/<package_version> <platform_info>" as telemetry and this [table](https://azure.github.io/azure-sdk/general_azurecore.html#azurecore-config-envvars-system-list) says AZURE_TELEMETRY_DISABLED is for controlling collection of this telemetry. If we follow this then `UserAgentPolicy` should not be activated at all if AZURE_TELEMETRY_DISABLED is set to true. It seems today AZURE_TELEMETRY_DISABLED controls only platform_info part of telemetry. 

We want to confirm whether it's a bug in Java  UserAgentPolicy implementation or error in guideline.

**Comment by anuchandy** [comment]
@JonathanGiles @adrianhall could you please chime in to double guideline is correct here?

**Comment by JonathanGiles** [comment]
My expectation would be that if AZURE_TELEMETRY_DISABLED is set to false in the environment, that there would be no telemetry at all included in the User Agent policy. @adrianhall might interpret the requirements differently though.

**Comment by adrianhall** [comment]
It's a great comment to have a discussion about within the arch board.  @anuchandy - please file an arch board issue on azure/azure-sdk.

This isn't my addition (and its of marginal value since the user can override the user-agent).  But we should discuss.

**Comment by sima-zhu** [comment]
Here is the issue created in arch board.
https://github.com/Azure/azure-sdk/issues/819

**Comment by sima-zhu** [comment]
No longer working on Java related issue. Thanks!

**Comment by anuchandy** [comment]
The parent arch board ticket is no longer active. Closing.
