### ISSUE TITLE
[BUG] Setting CORS policies on Azure storage account

### ISSUE THREAD

**Issue by SukruthKS** [Azure/azure-sdk-for-java#6627]
**Describe the bug**
When setting a new CORS rule on the storage account using the SDK, if any of the properties like ExposedHeaders, MaxAgeInSeconds etc are not specified or set to null, the SDK skips those elements in the request body XML and the server sends back an error message saying the XML is not syntactically valid. 

***Exception or Stack Trace***
Request body sent when `ExposedHeaders` property was not specified in the CORS rule:

```
INFO com.azure.storage.blob.implementation.ServicesImpl$ServicesService.setProperties - 913-byte body:%n<?xml version='1.0' encoding='UTF-8'?><StorageServiceProperties><Logging><Version>1.0</Version><Delete>false</Delete><Read>false</Read><Write>false</Write><RetentionPolicy><Enabled>false</Enabled></RetentionPolicy></Logging><HourMetrics><Version>1.0</Version><Enabled>true</Enabled><RetentionPolicy><Enabled>true</Enabled><Days>7</Days></RetentionPolicy><IncludeAPIs>true</IncludeAPIs></HourMetrics><MinuteMetrics><Version>1.0</Version><Enabled>false</Enabled><RetentionPolicy><Enabled>false</Enabled></RetentionPolicy></MinuteMetrics><Cors><CorsRule><AllowedOrigins>snowflakecomputing.com</AllowedOrigins><AllowedMethods>GET,HEAD</AllowedMethods><AllowedHeaders>x-ms-version</AllowedHeaders><MaxAgeInSeconds>60</MaxAgeInSeconds></CorsRule></Cors><DeleteRetentionPolicy><Enabled>true</Enabled><Days>1</Days></DeleteRetentionPolicy><StaticWebsite><Enabled>false</Enabled></StaticWebsite></StorageServiceProperties>
```

Error from the server:

```
<?xml version="1.0" encoding="utf-8"?>
<Error>
  <Code>InvalidXmlDocument</Code>
  <Message>XML specified is not syntactically valid. RequestId:7772028a-401e-005a-6d44-aa80b6000000 Time:2019-12-04T01:44:21.6326037Z</Message>
  <LineNumber>0</LineNumber>
  <LinePosition>0</LinePosition>
  <Reason />
</Error>
```

**To Reproduce**
```
BlobServiceProperties serviceProperties = blobServiceClient.getProperties();

BlobCorsRule rule = new BlobCorsRule();
rule.setAllowedOrigins("microsoft.com");
rule.setMaxAgeInSeconds(60);
rule.setAllowedMethods("GET");
rule.setAllowedHeaders("x-ms-version");

serviceProperties.setCors(Collections.singletonList(rule));

blobServiceClient.setProperties(serviceProperties);
```

***Code Snippet***
Added above.

**Expected behavior**
SDK should include all CORS rule elements in the request body even if they are empty or unspecified.

**Screenshots**
NA

**Setup (please complete the following information):**
 - OS: Linux
 - IDE : IntelliJ
 - Version of the Library used: 12.0.0

**Additional context**
-

**Information Checklist**
Kindly make sure that you have added all the following information above and checkoff the required fields otherwise we will treat the issuer as an incomplete report
- [x] Bug Description Added
- [x] Repro Steps Added
- [x] Setup information Added

**Comment by rickle-msft** [comment]
Hi, @SukruthKS. Thank you for reporting this. For a potential temporary work around, can you try setting the values you don't care about to an empty string and see if that serializes in the way we expect.

**Comment by SukruthKS** [comment]
Hey @rickle-msft I'm already rolling with that temporary work around by setting them to empty strings :)

**Comment by rickle-msft** [comment]
Perfect! It's good to know that'll work, and we'll get that cleaned up as soon as we can.
