### ISSUE TITLE
Monitoring API support through the SDK

### ISSUE THREAD

**Issue by gadagip** [Azure/azure-sdk-for-java#663]
I looked all over the SDK and the REST API spec, but there is no monitoring support. More specifically, I was looking at obtaining the Basic Metrics through REST or java sdk. I understand there is a .NET Monitoring API, but is there any plan of adding that to java-sdk?

**Comment by jianghaolu** [comment]
Hi @gadagip 

We are still waiting for an OpenAPI spec from them. Once that is available we will get a Java SDK available pretty soon.

**Comment by jianghaolu** [comment]
Closing as nothing we can do at this moment.

**Comment by mJaiswal** [comment]
Hi @gadagip 

Approximately by when do you think the Monitoring support and/or obtaining Basic Metrics through this Java SDK will be available ?

**Comment by jianghaolu** [comment]
Hi @mJaiswal you can request the specs (used to generate SDK) in this repo: https://github.com/Azure/azure-rest-api-specs

**Comment by gadagip** [comment]
@mJaiswal It'll be a question for the producers of the SDK, not the consumers.

**Comment by ImranBijapuri** [comment]
Is there any development on this to obtain Metrics (https://github.com/Azure/azure-sdk-for-java). And would be really grateful if there were any code samples to refer to .

**Comment by jatins** [comment]
@jianghaolu Do we have a Java sdk for monitoring apis available now?
