### ISSUE TITLE
[BUG] Azure storage v10 SDK Async get requests do not complete

### ISSUE THREAD

**Issue by jduo** [Azure/azure-sdk-for-java#6640]
**Describe the bug**
When there is high concurrency, asynchronous range downloads on a file taking longer than a 160 seconds do not receive a response, even after several hours. We saw this with 1MB data ranges.

***Exception or Stack Trace***

**To Reproduce**
Disable retries and timeouts on the SDK and issue a large number of concurrent requests on various ranges of the same file. The file should be a few hundred MB,

***Code Snippet***

**Expected behavior**
Requests should eventually fail or report rate limit errors.

**Screenshots**

**Setup (please complete the following information):**
 - OS: macOS and Linux
 - IDE : IntelliJ
 - Version of the Library used: v10.4

**Additional context**
We are using a build of the SDK where we generated a DataLake G2 client.
This is a repost of this issue: https://github.com/Azure/azure-storage-java/issues/514

**Information Checklist**
Kindly make sure that you have added all the following information above and checkoff the required fields otherwise we will treat the issuer as an incomplete report
- [x] Bug Description Added
- [x] Repro Steps Added
- [x] Setup information Added

**Comment by rickle-msft** [comment]
Hi, @jduo. I apologize for missing your issue on the other repo. 

We are aware of the performance and scalability issues in v10. Unfortunately, we are not planning to add any improvements or fixes to the v10/11 architecture. If you'd like to know more about this decision, I will point you [here](https://github.com/Azure/azure-storage-java/blob/master/V12%20Upgrade%20Story.md) where we do our best to explain our reasoning.

We realize this leaves some customers in a difficult position and are sensitive to the requirements of those projects. As such, we are happy to help you move off of v10/11 in any way that we can. Please let us know how we can support you, and we will work to make this transition as smooth as possible.

**Comment by rickle-msft** [comment]
I am going to close this issue as I believe it has been addressed and there has been no customer follow up.

Please feel free to reopen the issue or otherwise continue to engage if you need more support.
