### ISSUE TITLE
Daily release packages for track 1 are not being versioned correctly

### ISSUE THREAD

**Issue by mitchdenny** [Azure/azure-sdk-for-java#6648]
In this feed:
https://dev.azure.com/azure-sdk/public/_packaging?_a=feed&feed=azure-sdk-for-java

Any track 1 libraries aren't being versioned correctly. We need to fix it, burn the feed and recreate it so that only dev package versions end up in there.

![image](https://user-images.githubusercontent.com/513398/70194102-791faf00-1755-11ea-8270-2ac64c00ef90.png)

**Comment by mitchdenny** [comment]
... otherwise this will cause dependency resolution issues.

**Comment by mitchdenny** [comment]
This is now working correctly due to some changes in versioning scripts that @JimSuplizio made I think.

**Comment by JimSuplizio** [comment]
> This is now working correctly due to some changes in versioning scripts that @JimSuplizio made I think.

It looks like the only things that weren't were the cosmos track 1 libraries which was from something that you'd fixed yesterday. cognitive services, batch, application insights etc all seem to be correctly versioned in the dev feed.
