### ISSUE TITLE
1.0 Merge "models" subpackage into the same package as the "collections" classes

### ISSUE THREAD

**Issue by martinsawicki** [Azure/azure-sdk-for-java#665]
Both on the "implementation" side and the interface side --- the "collections" and individual "models" should live in the same subpackage. No need for a separate models subpackage -- this gets in the way of hiding IMPL constructors (all IMPL constructors should be no more visible than package-internal --- avoid public impl constructors!)

**Comment by jianghaolu** [comment]
Done.
