### ISSUE TITLE
[QUERY] [Azure-core] Response<T> cannot access to the raw http response body. 

### ISSUE THREAD

**Issue by yaohaizh** [Azure/azure-sdk-for-java#6656]
**Query/Question**

According to https://azure.github.io/azure-sdk/java_design.html#java-response-logical-entity, the response<T> should include body. 

My question, the *body* here means raw body string or entity type? Because when deserialize the body to an entity object may lost some information of the original body values. 

This is situation I met when adopting this PR: https://github.com/Azure/azure-sdk-for-java/pull/6303.  Status information lost after the activation phase. Thus, the downstream flux method cannot handle the provisioning status correctly.

**Comment by anuchandy** [comment]
Raw-Body (byte stream) vs Entity-Type depends on the type of `T` in `Response<T>`. If the return type of service interface method is - `Response<Flux<ByteBuffer>>` then it is Raw-body, if it is `Response<Foo>` then the internal raw http content will drained and be deserialized to `Foo`.

I'm adding tests to the above PR to cover various ARM LRO cases, it should show how the LRO method in "private" service interface should look like and how activationFunction should wrap it. My initial thought is to have "private"  service interface LRO methods to return  `Response<Flux<ByteBuffer>>` then read it from activation Function.

**Comment by anuchandy** [comment]
This is resolved and tests are added. Closing.
