### ISSUE TITLE
Investigate why EventHubs live tests are consistently failing

### ISSUE THREAD

**Issue by JimSuplizio** [Azure/azure-sdk-for-java#6664]
The build summary for EventHubs live tests can be found here: https://dev.azure.com/azure-sdk/internal/_build?definitionId=689&_a=summary. There hasn't been a passing live test run for the past month.

**Comment by srnagar** [comment]
EventHubs test pipelines are failing because Storage live tests run before running EventHubs tests and storage live tests are failing. 

@sima-zhu is working on fixing storage live tests - https://github.com/Azure/azure-sdk-for-java/pull/6677

**Comment by conniey** [comment]
It looks like there was one successful run where there was no time out from Storage tests.
https://dev.azure.com/azure-sdk/internal/_build/results?buildId=206521&view=logs&j=3f0b3bd8-2d88-59b8-ec21-d9a54670d8fb&t=d461725e-ef03-51a5-7040-91cc48a61aa8&l=1506
