### ISSUE TITLE
Investigate Storage live tests failures

### ISSUE THREAD

**Issue by JimSuplizio** [Azure/azure-sdk-for-java#6667]
The build summary for Storage live tests can be found here: https://dev.azure.com/azure-sdk/internal/_build?definitionId=505&_a=summary. In the past month this pipeline has had far more failing runs than passing.

**Comment by alzimmermsft** [comment]
@rickle-msft @sima-zhu has been working on #6566 if you want to collaborate or review the changes.

**Comment by rickle-msft** [comment]
@alzimmermsft @sima-zhu @JimSuplizio I approved #6566

**Comment by alzimmermsft** [comment]
Closing this issue as Storage live tests are consistently passing, and if they're not they are fixed quickly.
