### ISSUE TITLE
Change Default Logging Level

### ISSUE THREAD

**Issue by alzimmermsft** [Azure/azure-sdk-for-java#6674]
Currently `ClientLogger` and `HttpLogOptions` default to a `NONE` logging level which results in nothing being logged by default. Disabled logging leads to a poor chance of getting information on why an error occurred while running the application.

Instead we should offer and use a more appropriate logging level by default. `ClientLogger` should default to using the `WARNING` log level as this will support logs written to the `WARNING` and `ERROR` levels which are used for logging exceptions. `HttpLogOptions` should default to using `BASIC` which will log request URLs and response statuses codes which will offer a good overview on the flow of an application before it hit an error state.

**Comment by JonathanGiles** [comment]
This sounds reasonable to me. You should test this out to ensure it isn't too verbose, and of course, as we discussed previously - lets make sure the logging section of the wiki gives good detail about the configuration options we make available.

**Comment by alzimmermsft** [comment]
@sima-zhu given that you're working on logging improvements do you have bandwidth to take this on as well?

**Comment by sima-zhu** [comment]
Considered the last decision we took is to default to None if nothing set, could you clarify if we still want the feature? @alzimmermsft

**Comment by sima-zhu** [comment]
I do not quite get the necessities of the feature. We are sdk libraries. Is it better to turn off logging unless it is needed, like JDK and Reactor? I think it is a little bit annoying if we log out something by default. Also, logging out BASIC does not help in most of the cases. 

@alzimmermsft @JonathanGiles @srnagar

**Comment by alzimmermsft** [comment]
Closing this issue as it would be a semantics breaking change.
