### ISSUE TITLE
How do I get all assets from azure media service

### ISSUE THREAD

**Issue by kennethinsnow** [Azure/azure-sdk-for-java#669]
One query returns a maximum of 1000 items. how do i get the rest of them? Does java sdk provides a way to skip like this php program?
https://blogs.msdn.microsoft.com/randomnumber/2015/11/05/listing-more-than-1000-assets-with-the-php-sdk-for-azure-media-services/
My code:
`MediaContract mediaService = MediaService.create(MediaConfiguration.configureWithOAuthAuthentication(
                    mediaServiceUri, oAuthUri, AMSAccountName, AMSAccountKey, scope));`
`List<AssetInfo> info = mediaService.list(Asset.list());`
Thanks,

**Comment by kennethinsnow** [comment]
Here is my own solution after getting some help from stackoverflow

```
        List<AssetInfo> allAssets = new ArrayList<>();
        int skip = 0;
        while (true) {
            List<AssetInfo> curAssets = mediaService.list(getAllAssetPage(skip));
            if (curAssets.size() > 0) {
                allAssets.addAll(curAssets);
                if (curAssets.size() == 1000) {
                    System.out.println(String.format("Got %d assets.", allAssets.size()));
                    skip += 1000;
                } else {
                    break;
                }
            } else {
                break;
            }
        }
        private static DefaultListOperation<AssetInfo> getAllAssetPage(int skip) {
            return new DefaultListOperation<AssetInfo>("Assets",
            new GenericType<ListResult<AssetInfo>>() {
            }).setSkip(skip);
        }
```

**Comment by jianghaolu** [comment]
Hi @kennethinsnow 

Thanks for sharing your solution!
