### ISSUE TITLE
How to use azure-java-sdk update/add Network Interface IP Address ??

### ISSUE THREAD

**Issue by onlineie** [Azure/azure-sdk-for-java#6704]
# How to use azure-java-sdk update/add Network Interface IP Address ??

```java
//I want to add second private address, or even a third or fourth address for the network interface
//But the following code doesn't seem to work
//When I called ni.update (). Apply (); there was no error, but when I went to the Azure portal to check, didn't add a new address for my network interface.

VirtualMachine linuxVM = azure.virtualMachines().getById("/subscriptions/*******-*****-***-******/resourceGroups/sampleVmResourceGroup/providers/Microsoft.Compute/virtualMachines/testLinuxVM");
NetworkInterface ni = linuxVM.getPrimaryNetworkInterface();
ni.update().defineSecondaryIPConfiguration("test")
      .withExistingNetwork(ni.primaryIPConfiguration().getNetwork())
       .withSubnet(ni.primaryIPConfiguration().subnetName())
       .withPrivateIPAddressDynamic();

ni.update().apply();
```  

So, what should I do?

**Comment by KalyanChanumolu-MSFT** [comment]
@onlineie Could you check [this ](https://github.com/Azure/azure-libraries-for-java/blob/master/azure-mgmt-network/src/test/java/com/microsoft/azure/management/network/NetworkInterfaceOperationsTests.java#L57)test and see it helps.

 ```java
         networkManager.networkInterfaces().define(nicNames[1])
                    .withRegion(Region.US_EAST)
                    .withNewResourceGroup(RG_NAME)
                    .withExistingPrimaryNetwork(network)
                    .withSubnet("subnet1")
                    .withPrimaryPrivateIPAddressDynamic()
                    .defineSecondaryIPConfiguration("nicip2")
                        .withExistingNetwork(network)
                        .withSubnet("subnet1")
                        .withPrivateIPAddressDynamic()
                        .attach(),
```

```java
            nics[0].update()
                .defineSecondaryIPConfiguration("nicip2")
                .withExistingNetwork(network)
                .withSubnet("subnet1")
                .withPrivateIPAddressDynamic()
                .attach()
                .applyAsync(),

```

A lot of the scenarios are covered in the tests.

**Comment by onlineie** [comment]
> @onlineie Could you check [this ](https://github.com/Azure/azure-libraries-for-java/blob/master/azure-mgmt-network/src/test/java/com/microsoft/azure/management/network/NetworkInterfaceOperationsTests.java#L57)test and see it helps.
> 
> ```java
>         networkManager.networkInterfaces().define(nicNames[1])
>                    .withRegion(Region.US_EAST)
>                    .withNewResourceGroup(RG_NAME)
>                    .withExistingPrimaryNetwork(network)
>                    .withSubnet("subnet1")
>                    .withPrimaryPrivateIPAddressDynamic()
>                    .defineSecondaryIPConfiguration("nicip2")
>                        .withExistingNetwork(network)
>                        .withSubnet("subnet1")
>                        .withPrivateIPAddressDynamic()
>                        .attach(),
> ```
> 
> ```java
>             nics[0].update()
>                 .defineSecondaryIPConfiguration("nicip2")
>                 .withExistingNetwork(network)
>                 .withSubnet("subnet1")
>                 .withPrivateIPAddressDynamic()
>                 .attach()
>                 .applyAsync(),
> ```
> 
> A lot of the scenarios are covered in the tests.

Got it. This is correct, thanks very much for your help

**Comment by yaohaizh** [comment]
@KalyanChanumolu-MSFT thanks for helping this. 

Close the issue as it has been addressed.
