### ISSUE TITLE
Undocumented Behavior in ServiceBusContract

### ISSUE THREAD

**Issue by fribeiro1** [Azure/azure-sdk-for-java#671]
The "receivedMessage" method still works if you pass a topic name alone (e.g: "SampleTopic") instead of a topic name followed by a subscription name (e.g: "SampleTopic/subscriptions/SampleSubscription") but the documentation doesn't specify which messages are returned.

**Comment by fribeiro1** [comment]
Any updates?

**Comment by alvadb** [comment]
the service bus client library is not in this repo anymore, so if this is still an issue, it should go there:
https://github.com/azure/azure-service-bus-java
