### ISSUE TITLE
[FEATURE] Batch and Bulk API for Java SDK v4.1

### ISSUE THREAD

**Issue by David-Noble-at-work** [Azure/azure-sdk-for-java#6712]

**Comment by David-Noble-at-work** [comment]
Tasks:
- Batch and Bulk API : Design document + compilable examples
   Examples will illustrate the developer experience. The design document will:
   - outline the underlying object model and
   - describe the sequence of messages and interactions that occur between client components and the server
- Bulk read end-to-end
  Goals: 
  - Make one bulk point-read example work end-to-end.
  - Update [azure-cosmos-serialization](https://github.com/microsoft/HybridRow) library as required to support point write operations.
  The code will be prototype quality, not production ready. It will not be merged into master or feature/cosmos/v4.
- Batch write end-to-end
  Goals: 
  - Make one batch (not bulk) point-write example work end-to-end.
  - Update [azure-cosmos-serialization](https://github.com/microsoft/HybridRow) library as required to support point write operations.
  The code will be prototype quality, not production ready. It will not be merged into master or feature/cosmos/v4. We are not covering bulk in this iteration because hybrid row write operations are untested.
- Bulk write end-to-end
  Goals:
  - Make one bulk point-write example work end-to-end.
  - Refine batch and bulk API to improve code quality.
  - Refine [azure-cosmos-serialization](https://github.com/microsoft/HybridRow) library to improve code quality.
  The code will not be production ready. It will not be merged into master or feature/cosmos/v4.
- Add unit/integration tests and benchmarks
  At the end of this iteration the code will be merged into master or feature/cosmos/v4.

**Comment by kushagraThapar** [comment]
This is done.
