### ISSUE TITLE
[FEATURE REQ]-API Key support for ServiceClientCredentials

### ISSUE THREAD

**Issue by cnuernber** [Azure/azure-sdk-for-java#6714]
It took me quite a while to google around and find the answer to this so if anyone is using the java SDK and wants to use, for example, the api-key with the applicationinsights rest api:

The feature request is please provide samples for using api-keys with all of the azure services that support generating api keys and provide curl examples for them.

Clojure example:
```clojure
(defn create-data-client
  [api-key]
  (ApplicationInsightsDataClientImpl.
   (reify
     ServiceClientCredentials
     (applyCredentialsFilter [this client-builder]
       (.addInterceptor
        client-builder
        (reify Interceptor
          (intercept [item chain]
            (let [builder (doto (.newBuilder (.request chain))
                            (.addHeader "X-Api-Key" api-key))]
              (.proceed chain (.build builder))))))))))
```

**Comment by yungezz** [comment]
put in backlog now

**Comment by weidongxu-microsoft** [comment]
On track2, one can use `AddHeadersPolicy`.
https://github.com/Azure/azure-sdk-for-java/blob/main/sdk/core/azure-core/src/main/java/com/azure/core/http/policy/AddHeadersPolicy.java
