### ISSUE TITLE
[Design Discussion] Fix naming inconsistencies across languages

### ISSUE THREAD

**Issue by samvaity** [Azure/azure-sdk-for-java#6716]
Fix model and method naming inconsistencies across languages.

**Comment by samvaity** [comment]
@mssfang should we close this one?

**Comment by mssfang** [comment]
Yes. We already done it.

**Comment by mssfang** [comment]
Can we close this issue?

**Comment by samvaity** [comment]
As discussed, this still needs to be open to address the model name inconsistencies - preview 2.

**Comment by mssfang** [comment]
This issue can be closed. TA feature crew have discussed and been naming consistency now.
