### ISSUE TITLE
[FEATURE] Batch and Bulk API : Iteration 1 : Design document + compilable examples

### ISSUE THREAD

**Issue by David-Noble-at-work** [Azure/azure-sdk-for-java#6718]
This is iteration 1 of epic #6712, Batch and Bulk API for Java SDK v4.1.

#### Goals:
Examples will illustrate the developer experience. The design document will:
- outline the underlying object model and
- describe the sequence of messages and interactions that occur between client components and the server.

Review sign-off is required to proceed with the remaining iterations.

**Comment by kushagraThapar** [comment]
This is done.
