### ISSUE TITLE
[FEATURE] Batch and Bulk API : Iteration 2 : Bulk read end-to-end

### ISSUE THREAD

**Issue by David-Noble-at-work** [Azure/azure-sdk-for-java#6719]
This is iteration 2 of epic #6712, Batch and Bulk API for Java SDK v4.1.

#### Goals:
- Make one bulk point-read example work end-to-end.
- Update [azure-cosmos-serialization](https://github.com/microsoft/HybridRow) library as required to support point read operations.

The code will be prototype quality, not production ready. It will not be merged into master or feature/cosmos/v4.

**Comment by kushagraThapar** [comment]
This is done.
