### ISSUE TITLE
get(resourceGroupName, accountName) method to retrieve a storage account

### ISSUE THREAD

**Issue by thchuong-x2011** [Azure/azure-sdk-for-java#672]
I notice that the `StorageAccountsOperations` doest not have a method to simply retrieve a storage account in a resource group while the method exists for other common resources like `VirtualMachinesOperations` or `NetworkInterfacesOperations`. It would be helpful to have such a method instead of listing all accounts in the group and searching for the account.
Regards

**Comment by jianghaolu** [comment]
Hi @thchuong-x2011 

There should be! As a matter of fact, they are already available in 1.0.0-beta1. And all versions from this point on.

**Comment by thchuong-x2011** [comment]
Thanks @jianghaolu
