### ISSUE TITLE
[FEATURE] Batch and Bulk API : Iteration 3 : Batch write end-to-end

### ISSUE THREAD

**Issue by David-Noble-at-work** [Azure/azure-sdk-for-java#6720]
This is iteration 3 of epic #6712, Batch and Bulk API for Java SDK v4.1.

### Goals:
- Make one batch (not bulk) point-write example work end-to-end.
- Update [azure-cosmos-serialization](https://github.com/microsoft/HybridRow) library as required to support point write operations.

The code will be prototype quality, not production ready. It will not be merged into master or feature/cosmos/v4. We are not covering bulk in this iteration because hybrid row write operations are untested.

**Comment by kushagraThapar** [comment]
This is done.
