### ISSUE TITLE
[FEATURE] Batch and Bulk API : Iteration 4 : Bulk write end-to-end

### ISSUE THREAD

**Issue by David-Noble-at-work** [Azure/azure-sdk-for-java#6721]
This is iteration 4 of epic #6712, Batch and Bulk API for Java SDK v4.1.

#### Goals:
- Make one bulk point-write example work end-to-end.
- Refine batch and bulk API to improve code quality.
- Refine [azure-cosmos-serialization](https://github.com/microsoft/HybridRow) library to improve code quality.

The code will not be production ready. It will not be merged into master or feature/cosmos/v4.

**Comment by kushagraThapar** [comment]
This is done.
