### ISSUE TITLE
[FEATURE] Batch and Bulk API : Iteration 5 : Complete feature work

### ISSUE THREAD

**Issue by David-Noble-at-work** [Azure/azure-sdk-for-java#6722]
This is iteration 5 of epic #6712, Batch and Bulk API for Java SDK v4.1.

#### Goals:

This is a code quality iteration. The code will be updated for correctness and maintainability. Unit tests, Integration tests, and benchmarks will be added. 

At the end of this iteration:

- The feature will be merged into master or feature/cosmos/v4. 
- An update to  [azure-cosmos-serialization](https://github.com/microsoft/HybridRow) will be published to the maven repository.

Performance, reliability, and scalability work will remain.

**Comment by kushagraThapar** [comment]
This is done.
