### ISSUE TITLE
[Feature] Fix ServiceClientCheck checkstyle errors

### ISSUE THREAD

**Issue by mssfang** [Azure/azure-sdk-for-java#6728]
Remove below suppressions(azure-sdk-for-java\eng\code-quality-reports\src\main\resources\checkstyle\checkstyle-suppressions.xml) 
and then fix the checkstyles errors that it generates:

```java
  <!-- Suppress these checks until CI pipeline setup -->
  <suppress checks="com.azure.tools.checkstyle.checks.ServiceClientCheck" files=".*[/\\]textanalytics[/\\].*"/>
```

**Comment by samvaity** [comment]
`<suppress checks="MissingJavadocMethod" files=".*[/\\]textanalytics[/\\].*"/>`
was handled in #7162

**Comment by mssfang** [comment]
Closing this issue. Leave the suppression as it is. All languages stay with "detect***", "recognize***", "analyze***" as prefix of method name.
