### ISSUE TITLE
SQL Database Management Library?

### ISSUE THREAD

**Issue by m-moris** [Azure/azure-sdk-for-java#673]
I'm looking for the SQL Database Management Library v1.0.0.
So far as I know, v0.9.3 is available, but v1.0.0 is not available yet. 
Do you have any plan to release SQL Database Library?

**Comment by jianghaolu** [comment]
SQL DB won't be in the first wave of released Java SDK.

If you really want to taste 1.0.0-beta1 of SQL (!quality is not guaranteed!), you can build one with AutoRest and their specs. The spec is here: https://github.com/Azure/azure-rest-api-specs/blob/master/arm-sql/2015-05-01/swagger/sql.json. And the AutoRest used for 1.0.0-beta1 (and some minor fixes included after that) is here: https://github.com/Azure/autorest/tree/java-1.0.0-beta1.

**Comment by jianghaolu** [comment]
Whoops, it will be in the first wave. So yeah we will have a beta build by end of June.

**Comment by martinsawicki** [comment]
not sure about June, as there are at least 2-3 phases to ring0 -- but we'll shoot for it by end of summer.,
