### ISSUE TITLE
Conflict with Jersey 1.13

### ISSUE THREAD

**Issue by JackMorris42** [Azure/azure-sdk-for-java#674]
The project depends on `jersey-core` 1.13 which provides in implementation of `javax.ws.rs.core.Application`.
This conflicts with the one I use (it comes from `javax.ws.rs-api` 2.0).

Could you at least upgrade to jersey 1.19 which no more directly includes this class? I would be able to solve the conflict by excluding the `jsr311-api` artifact.

Thanks

**Comment by jianghaolu** [comment]
If you are using maven or Gradle, you can specify 1.19 in your project's dependency management.

**Comment by jianghaolu** [comment]
Maintaining 0.9 branch is not on the priority list. Please feel free to send a PR with the updated Jersey version. 
No action to take.

**Comment by amilbourne** [comment]
We also hit this problem.
I have created PR #985 to fix this problem.

**Comment by JackMorris42** [comment]
Thanks @amilbourne for the PR.
