### ISSUE TITLE
[QUERY] How best to use the `apimanagement` portion of this sdk

### ISSUE THREAD

**Issue by harold** [Azure/azure-sdk-for-java#6742]
**Query/Question**
Hi, thanks for this lib, having something higher-level to use than the raw REST API seems great.

I am wondering how best to use the `apimanagement` portion of this sdk.

Is the main entry point to construct an `ApiManagementManager`?

If so, from where do I get an `AzureTokenCredentials`? (per: https://github.com/Azure/azure-sdk-for-java/blob/master/sdk/apimanagement/mgmt-v2019_01_01/src/main/java/com/microsoft/azure/management/apimanagement/v2019_01_01/implementation/ApiManagementManager.java#L163)

Or, a `RestClient`? (per: https://github.com/Azure/azure-sdk-for-java/blob/master/sdk/apimanagement/mgmt-v2019_01_01/src/main/java/com/microsoft/azure/management/apimanagement/v2019_01_01/implementation/ApiManagementManager.java#L178)

I imagine this stuff is documented somewhere, but I haven't found it, so a pointer to relevant documentation would be great.

In the mean time, I have found a workaround, constructing an `ApiManagementClientImpl` out of a `TokenCredentials` I was able to make out of a SaS token I made on the portal inside our APIM resource. However, this doesn't feel quite right, because I am operating exclusively on objects (inner/impl) from inside the `implementation` folder and not touching any of the higher-level interfaces outside that directory.

***Why is this not a Bug or a feature Request?***
Things are working, but the best usage is merely unclear.

**Setup (please complete the following information if applicable):**
 - OS: Ubuntu
 - IDE : Emacs
 - Version of the Library used:
```
com.microsoft.azure.apimanagement.v2019_01_01/azure-mgmt-apimanagement "1.0.0-beta-1"
```
 
 **Information Checklist**
 Kindly make sure that you have added all the following information above and checkoff the required fields otherwise we will treat the issuer as an incomplete report
- [x] Query Added
- [x] Setup information Added

**Comment by yaohaizh** [comment]
@harold you can take a look at this link for how to construct the AzureTokenCredentials: https://github.com/Azure/azure-libraries-for-java/blob/master/AUTH.md#using-applicationtokencredentials

**Comment by yaohaizh** [comment]
@horold I'll close this issue. Feel free to re-open the issue if you have more concerns. Thanks.

**Comment by harold** [comment]
Thanks, that is a very helpful link. I appreciate that.

I will look into the service principal method.

Take care.
