### ISSUE TITLE
[FEATURE REQ] ADLS: Missing API - PagedIterable onErrorMap function to return a PagedIterable 

### ISSUE THREAD

**Issue by gapra-msft** [Azure/azure-sdk-for-java#6751]
**Is your feature request related to a problem? Please describe.**
Related to https://github.com/Azure/azure-sdk-for-java/issues/5971 and https://github.com/Azure/azure-sdk-for-java/issues/6750
we need a way to map the error from a BlobStorageException to a DataLakeStorageException in PagedIterable

**Describe the solution you'd like**
Some datalake APIs (that are a separate namespace from blobs) call directly into blob APIs (ex: listBlobContainers) that returns a PagedIterable of BlobContainerItems and on error return a BlobStorageException

To make the namespace for a user consistent, we need to be able to return a DataLakeStorageException if a BlobStorageException is propogated.

**Additional context**

    public PagedIterable<FileSystemItem> listFileSystems(ListFileSystemsOptions options, Duration timeout) {
        return blobServiceClient.listBlobContainers(Transforms.toListBlobContainersOptions(options), timeout).onErrorMap(ex -> DataLakeImplUtils.transformBlobStorageException(ex)).mapPage(blobContainerItem -> Transforms.toFileSystemItem(blobContainerItem));
    }

**Information Checklist**
Kindly make sure that you have added all the following information above and checkoff the required fields otherwise we will treat the issuer as an incomplete report
- [X] Description Added
- [X] Expected solution specified

**Comment by alzimmermsft** [comment]
Adding @anuchandy given his current work may resolve this issue.

**Comment by alzimmermsft** [comment]
This should be resolved by #6465 and will be available in an upcoming release of Azure Core.
