### ISSUE TITLE
Versions in README.md files were not updated with the released versions

### ISSUE THREAD

**Issue by JimSuplizio** [Azure/azure-sdk-for-java#6764]
sdk\core\azure-core\README.md
Still has 1.0.0 in dependency snippet and should be 1.1.0

sdk\core\azure-core-amqp\README.md
Still has 1.0.0-preview.7 in dependency snippet and should be 1.0.0-beta.8

sdk\core\azure-core-http-netty\README.md
Still has 1.0.0 in dependency snippet and should be 1.1.0 

sdk\appconfiguration\azure-data-appconfiguration\README.md
Still has 1.0.0-preview.6 in dependency snippet and should be 1.0.0-beta.7
azure-core-http-netty version in snippet is 1.0.0 and should be 1.1.0

sdk\identity\azure-identity\README.md
Still has 1.0.0 in dependency snippet and should be 1.0.1

sdk\eventhubs\azure-messaging-eventhubs\README.md
Still has 5.0.0-preview.5 in dependency snippet and should be 5.0.0-beta.6
dependency snippet for azure-identity still references 1.0.0 and should be 1.0.1

sdk\eventhubs\azure-messaging-eventhubs-checkpointstore-blob\README.md
Still has 1.0.0-preview.3 in dependency snippet and should be 1.0.0-beta.4

sdk\keyvault\azure-security-keyvault-certificates\README.md
Still has 4.0.0-preview.5 in dependency snippet (multiple places) and should be 4.0.0-beta.6

It's worth noting that these should be updated _before_ shipping as the README.md file for a given library is converted to html and added to the documentation's landing page.

**Comment by joshfree** [comment]
@hemanttanwar can you follow up and get the READMEs into a consistent state _before_ the January release and work with @JimSuplizio to make sure these get consistenly updated before each future release?  What was done for the November GA was a special one-off due to customer confusion.  Now that the READMEs have a blurb on how to find GA/supported bits, we should go back to moving the README versions in lock step with the releases.

**Comment by hemanttanwar** [comment]
@joshfree What is guide line on folliwng options 

**Option 1** : Changing the README.md to point to future release version, 2 weeks before January release 
Pro : We will not miss this step.
Con : 1.A customer look at README.md in git repo, they are going to find a version which is not yet released.
       2. The future version version might change as we reach near to release based on we are doing major or minor changes.

**Option 2** : Changing the README.md to point to future release version, 1 day before January release
Con: Risk of missing this step. We can have checklist to mitigate this risk.

My opinion is for `Option 2` but I may not be right person to know all the facts.

People who engage with customers can guide us making a decision between two .

**Comment by hemanttanwar** [comment]
Based on email thread discussion on this topic, We are deciding to go with `Option 1` .

Changing the README.md to point to future release version before code complete, which is 1-2 weeks before monthly release

**Comment by joshfree** [comment]
Option 1 + ensuring the readmes have a small blurb at the top to point customers to where to find the latest released stable/bits.

**Comment by JonathanGiles** [comment]
I'm opinionated on this topic too. When we have a docs page that represents our planned approach, would you mind sharing a link with me? Thanks!

**Comment by hemanttanwar** [comment]
@JonathanGiles  I will document our approach in OneNote->AzureSDKJava space and share with everyone.

**Comment by hemanttanwar** [comment]
This documented here 
https://microsoft.sharepoint.com/:o:/t/AzureDeveloperExperience/EpAZJfKcBeZIj_UsM2gKMLABlvunu_aganHLi7XQ7Rov7Q?e=zGRpzD

**Comment by hemanttanwar** [comment]
Closing
