### ISSUE TITLE
Make the storage live tests green over 90%

### ISSUE THREAD

**Issue by sima-zhu** [Azure/azure-sdk-for-java#6769]
Storage failure:
![image](https://user-images.githubusercontent.com/48036328/70662163-8be52880-1c1a-11ea-8269-e3c11ad6a063.png)

**Comment by joshfree** [comment]
@sima-zhu could you add links to logs?

**Comment by alzimmermsft** [comment]
Closing this as Storage live tests are passing at a much higher rate.
