### ISSUE TITLE
[QUERY] What is the status of msi-auth-token-provider?

### ISSUE THREAD

**Issue by jordanjennings** [Azure/azure-sdk-for-java#6800]
**Query/Question**
I stumbled across the msi-auth-token-provider while looking for a simple way to get managed identity credentials for an application, and it looks pretty good (no dependencies, caching built in, simple API). However I see it has had two beta releases over the last year and really no other activity. What's the status of this library? I also see that there's an alternative azure-identity library that can be used for pretty much the same thing, but that library has tons of dependencies, uses reactor, makes two HTTP calls for every token retrieval, doesn't cache the response, and has a less convenient API.

Is msi-auth-token-provider supported for simple, non-reactive use cases? Will it ever get a final release? What's the direction and thinking here?

***Why is this not a Bug or a feature Request?***
I'm not asking for new features or reporting any bug, I just want to know the status and direction for this library.

**Setup (please complete the following information if applicable):**
 - OS: macOS, Ubuntu
 - IDE : IntelliJ 2019.3
 - Version of the Library used: 1.0.0-Beta-2
 
 **Information Checklist**
 Kindly make sure that you have added all the following information above and checkoff the required fields otherwise we will treat the issuer as an incomplete report
- [x] Query Added
- [x] Setup information Added

**Comment by jordanjennings** [comment]
Thanks for the response. I will open separate issues for azure-identity to request enhancements for its  MSI auth token capabilities to match what msi-auth-token-provider offers.

**Comment by jianghaolu** [comment]
Great. Thanks!

**Comment by jianghaolu** [comment]
We're actually planning to deprecate this library. azure-identity will be the single authentication library to go from now on. 
Please open issues for azure-identity if you find it less than ideal for your need.

**Comment by jordanjennings** [comment]
Thanks for circling back to confirm. I have not yet opened any issues requesting improvements, but I will once I have time to dig back into this. Thanks again!
