### ISSUE TITLE
[FEATURE REQ] Topic subscription - unregister and reregister a messageHandler

### ISSUE THREAD

**Issue by piyushnayak** [Azure/azure-sdk-for-java#6843]
Is there a way to make changes to an existing messageHandler to a subscription. Perhaps unregister and reregister a messageHandler.
We don’t see any corresponding method available in the Java SDK. Ref. 
https://github.com/Azure/azure-sdk-for-java/blob/master/sdk/servicebus/microsoft-azure-servicebus/src/main/java/com/microsoft/azure/servicebus/SubscriptionClient.java

But there’s a similar request that is closed in the .net servicebus SDK.
Ref. https://github.com/Azure/azure-sdk-for-net/pull/6360/files

**Comment by Luyunmt** [comment]
The package  [azureidentitiy1.0.3](https://github.com/Azure/azure-sdk-for-java/releases/tag/azure-identity_1.0.3) fix the issue

**Comment by hemanttanwar** [comment]
@piyushnayak  Thanks for reporting this. We will analyze it and report back.

**Comment by yvgopal** [comment]
There is no method to unregister a session handler or message handler in Java SDK. I personally never felt it was necessary. The same can be achieved with closing the existing client and creating a new one. I still cannot see why we should add that feature. It is not present in our full framework .net SDK either.

**Comment by piyushnayak** [comment]
> There is no method to unregister a session handler or message handler in Java SDK. I personally never felt it was necessary. The same can be achieved with closing the existing client and creating a new one. I still cannot see why we should add that feature. It is not present in our full framework .net SDK either.

looks like it's there in .net SDK. Ref. https://github.com/Azure/azure-sdk-for-net/pull/6360/files

**Comment by Petermarcu** [comment]
@srnagar is this fixed in the version the Java team is working on?

**Comment by srnagar** [comment]
@piyushnayak In the new version of Service Bus SDK, we use [Project Reactor]() for receiving messages which allows you to unsubscribe.

This is still in beta but will soon be generally available.
```xml
<!-- https://mvnrepository.com/artifact/com.azure/azure-messaging-servicebus -->
<dependency>
    <groupId>com.azure</groupId>
    <artifactId>azure-messaging-servicebus</artifactId>
    <version>7.0.0-beta.5</version>
</dependency>
```

Could you please try this out and let us know if it worked for you?

You can find a sample on how to do this here:
https://github.com/Azure/azure-sdk-for-java/blob/master/sdk/servicebus/azure-messaging-servicebus/src/samples/java/com/azure/messaging/servicebus/ReceiveMessageAsyncSample.java#L42-L71

**Comment by yvgopal** [comment]
That PR you are linking for .net core SDK is not merged.

**Comment by jongio** [comment]
@piyushnayak - Please see this comment from @yvgopal for explanation on why this was closed.  Thank you, Jon

> There is no method to unregister a session handler or message handler in Java SDK. I personally never felt it was necessary. The same can be achieved with closing the existing client and creating a new one. I still cannot see why we should add that feature. It is not present in our full framework .net SDK either.
