### ISSUE TITLE
Onboard January releases on docs.microsoft.com

### ISSUE THREAD

**Issue by kaerm** [Azure/azure-sdk-for-java#6853]
- [ ] Onboard the following packages on docs.microsoft.com (all except legacy in com.azure)
**Latest:**
azure-keyvault-certificates 4.0.0
azure-storage-file-datalake 12.0.0
azure-messaging-eventhubs 5.0.0
azure-messaging-eventhubs-checkpointstore-blob 1.0.0
azure-data-appconfiguration 1.0.0
**Preview:**
azure-ai-textanalytics 1.0.0-beta1
azure-cosmos 4.0.0
**Legacy:**
azure-eventhubs 3.0.2

- [ ] Remove following packages from preview:
azure-keyvault-certificates 4.0.0-preview.6
azure-storage-file-datalake 12.0.0-preview.6
azure-messaging-eventhubs 5.0.0-preview.6
azure-messaging-eventhubs-checkpointstore-blob 1.0.0-preview.4
azure-data-appconfiguration 1.0.0-preview.7

- [ ] Update GA versions if they are not pulling from latest for:
azure-core 1.1.0
azure-identity 1.0.1
azure-storage-file-share 12.0.0
azure-storage-common 12.0.0
azure-storage-blob 12.1.0
azure-storage-queue 12.1.0
azure-storage-blob-cryptography 12.0.0
azure-storage-blob-batch 12.0.0
azure-keyvault-keys 4.0.0
azure-keyvault-secrets 4.0.0

@joshfree  to confirm version numbers

**Comment by rajadilipkolli** [comment]
When will the GA gets released?

**Comment by kaerm** [comment]
Which one are you curious about @rajadilipkolli ?

**Comment by rajadilipkolli** [comment]
@kaerm , I am interested azure-messaging-eventhubs and azure-messaging-eventhubs-checkpointstore-blob

**Comment by kaerm** [comment]
Got it, @ramya-rao-a is there any ETA on GA Eventhubs for Java?

@rajadilipkolli I am not 100% sure here what you mean about unreleased - latest in our understanding means GA. This particular library should be coming out soon as GA but in the meantime you can try using its last preview version which shouldn't be too different. Otherwise, there is an older version that is currently GA but it will be soon switching to the new version so if you haven't used it yet it's probably worth the wait.

You will find the documentation for the preview [here](http://azure.github.io/azure-sdk-for-java/eventhubs.html)
and a couple of other pointers [here](https://azure.github.io/azure-sdk/releases/latest/#java-packages)

**Comment by rajadilipkolli** [comment]
@kaerm , Documentation says I can use azure-messaging-eventhubs 5.0.1 , where as this version is not available in Maven Central, only preview version is available. 
When I say GA is it should be available in maven central without preview. Documentation says to use 5.0.1 which means I think 5.0.0 should be available to use and can be downloaded from maven central, hence I have about unreleased versions

**Comment by kaerm** [comment]
Got it, thanks. That is correct - this particular library is still unreleased as a GA. 

Can you point me to the documentation that tells you to use 5.0.1?

**Comment by rajadilipkolli** [comment]
[ here](https://github.com/Azure/azure-sdk-for-java/tree/master/sdk/eventhubs/azure-messaging-eventhubs#adding-the-package-to-your-product) it is.

**Comment by kaerm** [comment]
Thanks @rajadilipkolli for sending that. To address your original question I double checked and the new library should be available in the next couple of days.

Adding @maggiepint to look into the docs versioning story

**Comment by conniey** [comment]
Hey. You can try out our daily builds at:
https://dev.azure.com/azure-sdk/public/_packaging?_a=feed&feed=azure-sdk-for-java
