### ISSUE TITLE
Support storage live tests running on multiple platforms.

### ISSUE THREAD

**Issue by sima-zhu** [Azure/azure-sdk-for-java#6873]
**Summary:**
Currently, Storage live tests do not support multiple platform running all together, there would be a race condition of operations on the same resources. 

**Proposals:**
1. Make the pipeline running sequentially instead of parallel. 
1. (**Optimal**) Clean up the specific resource which create in tests instead of prefix.

**Comment by alzimmermsft** [comment]
Closing this issue as each test run generates its own resources so we don't need to worry about race conditions. Storage live tests run safely on 6 concurrent runs at this time and is capable of support additional concurrent runs.
