### ISSUE TITLE
Resolve AppConfiguration Test Failures

### ISSUE THREAD

**Issue by alzimmermsft** [Azure/azure-sdk-for-java#6880]
Starting on 12/12/19 Azure AppConfiguration live tests have been consistently failing. The MacOS test runs are failing consistently will deserialization issues and there are occasional failures in Linux and Windows which appear to be more transient.

**Comment by mssfang** [comment]
Issues fixed at https://github.com/Azure/azure-sdk-for-java/pull/7837
