### ISSUE TITLE
Provide paged result access for resources other than VirtualMachine and ResourceGroup

### ISSUE THREAD

**Issue by thchuong-x2011** [Azure/azure-sdk-for-java#689]
The `OperationResponse` class provides the function `getNextLink()` to retrieve the next result page if the number of results exceeds a certain threshold. It works for `VirtualMachineOperations` and `ResourceGroupOperations` as these class has the function `listNext()`. However I don't see this function or its equivalent for other kinds of resources (e.g. `NetworkSecurityGroup`, `VirtualNetwork`). Could you please verify and fix it?
Thanks.
Chuong

**Comment by anuchandy** [comment]
This is available in 1.0.0-beta1,  `NetworkSecurityGroup::listNext()` https://github.com/Azure/azure-sdk-for-java/blob/1.0.0-beta1/azure-mgmt-network/src/main/java/com/microsoft/azure/management/network/NetworkSecurityGroupsOperationsImpl.java#L800

**Comment by jianghaolu** [comment]
In general, if there isn't a next link, it means the max capacity for this type of resource is small enough for one page to handle.
If Rest API does return a next link but the SDK fails to provide one, please do file a bug.
Thanks!
