### ISSUE TITLE
[FEATURE REQ] ContinuablePageFlux::byPage(C continuationToken, int pageSize)

### ISSUE THREAD

**Issue by moderakh** [Azure/azure-sdk-for-java#6917]
When paginating query results, the notion of continuation token and page-size specify the page boundaries. So we need support for configuring both page-size and continuation token in the `ContinuablePageFlux::byPage(.)`

please add the following method:
``ContinuablePageFlux::byPage(C continuationToken, int pageSize)``

This is an ask by CosmosDB SDK and we discussed with Jonathan and Anu offline.

**Comment by JonathanGiles** [comment]
This is being worked on in PR #6465

**Comment by alzimmermsft** [comment]
Closing this issue as the mentioned PR (#6465) has been merged and released.
