### ISSUE TITLE
[FEATURE REQ] support performant way of (not) logging in ClientLogger

### ISSUE THREAD

**Issue by moderakh** [Azure/azure-sdk-for-java#6918]
For fastest way of (not) logging, please add support for
* `clientLogger.isDebugEnabled()`
* `clientLogger.isTraceEnabled()`
* and similar other levels.

(similar to what slf4j provides: http://www.slf4j.org/faq.html#logging_performance)

ask from cosmosdb sdk. discussed offline with Jonathan

**Comment by JonathanGiles** [comment]
Being worked on in #6886.
