### ISSUE TITLE
[FEATURE REQ] static ClientLogger for short-lived objects

### ISSUE THREAD

**Issue by moderakh** [Azure/azure-sdk-for-java#6919]
Please provide a way of doing static ClientLogger instantiation to avoid paying the cost of instantiation and gc for short lived object (similar to what slf4j provides: http://www.slf4j.org/faq.html#declared_static)

ask by CosmosDB SDK, discussed offline with Jonathan

**Comment by JonathanGiles** [comment]
Clarifying question: in the short-lived objects that will have logging included, how often is logging performed - is it common or is it only in exceptional circumstances? I would be interested in any benchmarks you might have around this so that we can recreate the issue and see what options exist.

**Comment by sima-zhu** [comment]
This is Java specific tasks. Please reassign to someone related. Thanks! :)

**Comment by JonathanGiles** [comment]
static logger has been allowed for some time now, so closing this issue.
