### ISSUE TITLE
[FEATURE REQ] Please modify the check-style rules to allow throwing exceptions directly

### ISSUE THREAD

**Issue by moderakh** [Azure/azure-sdk-for-java#6920]
Please modify the check-style rules to allow throwing exceptions directly
without using clientLogger.logAndThrow(Exception).

ask from CosmosDB SDK
Discussed with Jonathan offline.

**context**
IMO, enforcing this as a checkstyle rule mixes the concept of exception handling with the notion of logging, there are a couple of issues:

Let's say, outerFunc and innerFunc are methods in the SDK:
1-1) If outerFunc calls innerFunc and innerFunc throws an exception using clientLogger.logAndThrow, but outerFunc catches the exception and gracefully handles it, then the exception doesn't have to necessarily be logged. This should be up to the engineer to decide if the exception has to be logged or not. using logger.logAndThrow enforces all exceptions to be logged.

1-2) If outerFunc calls innerFunc and innerFunc throws exception e1 using clientLogger.logAndThrow then outerFunc catches e1, but fails to gracefully handle e1 and hence after attempting to handle it, wrap it and re-throw it as e2 using clientLogger.logAndThrow new Exception(e1) , then the stacktarce of e1 will be logged twice once by clientLogger.logAndThrow in innerFunc and once as the root cause of e2 in outerFunc. This will result in a very crowded log files with repeated exception stacktrace.

1-3) If an exception is meant to be thrown internally and internally getting caught and handled (happy case) then enforcing this results in every exception to be logged (which will go to the log file and may require DISK IO access). Logging to file is expensive. We have certain exception thrown in our code which are handled internally and will never reach to the end user surface, and we don't want them to be logged. (this will cause performance degradation for us)

**Comment by JonathanGiles** [comment]
@moderakh For now suppress the checkstyle issues you encounter for this rule, noting in the suppression this bug report and we can return to it subsequently.

**Comment by sima-zhu** [comment]
@moderakh 

We have a way to temporarily suppress specific checkstyle in checkstyle-suppression.xml.
Do you have any extra ask?

**Comment by sima-zhu** [comment]
No longer working on Java specific issues. Please reassign to someone related. Thanks!: )

**Comment by srnagar** [comment]
Since we have a way to suppress checkstyles, we'll not update the checkstyle rule as we want to enforce logging the exception. If any part of the code requires throwing without logging, then a checkstyle can be suppressed. Closing this issue.
