### ISSUE TITLE
[FEATURE REQ] suppress check-style for implementation nampespace

### ISSUE THREAD

**Issue by moderakh** [Azure/azure-sdk-for-java#6921]
Please modify the check-style rules to suppress check-style for implementation namespace.

ask from cosmosdb sdk.
Discussed offline with Jonathan.

**Comment by JonathanGiles** [comment]
This wasn't quite what was discussed - what I said was that the cosmos team will need to make amendments to the checkstyle-suppressions.xml file to suppress issues reported in the cosmos implementation package namespace. You are welcome to make these changes via pull request.

**Comment by moderakh** [comment]
Thanks @JonathanGiles assigning this to Bhaskar as he is working on checkstyle and suppressing warnings.

**Comment by alzimmermsft** [comment]
@mbhaskar is this issue able to be closed as there is a way to suppress Checkstyles, if needed, within an implementation package.

**Comment by mbhaskar** [comment]
checkstyle supression for implementation packages has been done
