### ISSUE TITLE
[FEATURE REQ] suppress check-style rules for tests (specifically method naming)

### ISSUE THREAD

**Issue by moderakh** [Azure/azure-sdk-for-java#6922]
it is a common convention for advanced tests to have a naming like

`testName_assumption_expection()`

currently this is not allowed by the check-style rules. Please allow
https://dzone.com/articles/7-popular-unit-test-naming

ask from cosmosdb sdk.
discussed offline with Jonathan

**Comment by joshfree** [comment]
@sima-zhu could you please investigate?

**Comment by JonathanGiles** [comment]
This is same as #6921 - cosmos should make changes that they need to the checkstyle-suppressions.xml file to specifically ignore their test case naming.

**Comment by moderakh** [comment]
@mbhaskar is looking at check-style and suppressing the errors for test. @mbhaskar  please use this for tracking it.

**Comment by sima-zhu** [comment]
@moderakh Feel free to ping me if you need anything from SDK team.

**Comment by sima-zhu** [comment]
No longer a part of Java team. Please reassign to someone related. Thanks! ;)

**Comment by alzimmermsft** [comment]
@kushagraThapar, closing this as there is a configuration for this now.

```xml
<includeTestSourceDirectory>${checkstyle.includeTestSourceDirectory}</includeTestSourceDirectory>
```

It appears I also updated `azure-cosmos` to use this in [PR 26266](https://github.com/Azure/azure-sdk-for-java/pull/26266/files#diff-bc8f09796a080321d2c498da53b88c8654c40caf60481021bb949e1631720a60R64)
