### ISSUE TITLE
[BUG] New version storage library block Spring integration starter

### ISSUE THREAD

**Issue by jialindai** [Azure/azure-sdk-for-java#6923]
**Describe the bug**
In existing Spring boot starter for storage, following classes are injected into Spring context:
- com.microsoft.azure.storage.blob.ServiceURL
- com.microsoft.azure.storage.blob.ContainerURL

These classes are removed from latest version.

**Expected behavior**
These classes are kept so there is no breaking changes in Spring starter.

**Setup (please complete the following information):**
 - Version of the Library used: Azure Spring boot 2.2.x, 2.1.x, 2.0.x
- Project repo: https://github.com/microsoft/azure-spring-boot

**Information Checklist**
Kindly make sure that you have added all the following information above and checkoff the required fields otherwise we will treat the issuer as an incomplete report
- [x] Bug Description Added
- [ ] Repro Steps Added
- [ ] Setup information Added

**Comment by alzimmermsft** [comment]
Hi @jialindai,

From V11 to V12 of the Azure Blob Storage SDK `ServiceURL` was replaced by `BlobServiceAsyncClient` and `BlobServiceClient` and `ContainerURL` was replaced by `BlobContainerAsyncClient` and `BlobContainerClient`. I don't believe there are any plans to re-introduce the `URL` appended clients as they have replacements in the new SDKs.

@rickle-msft FYI

**Comment by jialindai** [comment]
Thanks for the information, we will see how to proceed based on this. Probably a deprecate process is needed.
