### ISSUE TITLE
Tweak how logging works to be more intuitive and accessible

### ISSUE THREAD

**Issue by JonathanGiles** [Azure/azure-sdk-for-java#6931]
Today, we don't log if there is no environment variable set, even if the user has provided slf4j configuration. We should shift to the following:

* If an slf4j configuration is present (most probably simply detected by the presence of a logger implementation), we will always use that and ignore the environment variable entirely.
* If no slf4j configuration is present, and if the environment variable is set between 1 and 4, we will log to sysout, syserr, or the standard Java logging APIs.

​This means that developers who have not deployed their apps with an slf4j implementation included can enable logging to console by setting the environment variable and restarting. Developers who want to be more nuanced can provide an slf4j implementation and associated configuration, and do whatever they want. The main benefit of this approach is to avoid the need for the user to enable the environment variable, and provide an slf4j implementation, to get any logging.

**Comment by JonathanGiles** [comment]
To work out which slf4j impl is being used, something like this might help: https://stackoverflow.com/questions/10505418/how-to-find-which-library-slf4j-has-bound-itself-to

**Comment by sima-zhu** [comment]
Implementation is done. Passed out the test senarios.
1. SLF4J binding exists, and log level setup. Our code returns log level from SLF4J binding.
1. SLF4J binding exists, and no log level setup. Our code returns default log level from SLF4J binding.
1. SLF4J binding does not exist, env log level exists. Our code returns log level from env variables.
1. SLF4J binding does not exist, env log level does not exist (invalid). Our code disable the log.

**Comment by sima-zhu** [comment]
The change has been merged [6b2c11e](https://github.com/Azure/azure-sdk-for-java/commit/6b2c11e270b06326a718a0026459e04e092f341f), the change will show up for the next release. 

Please refer the logging [wiki[(https://github.com/Azure/azure-sdk-for-java/wiki/Logging-with-Azure-SDK) for usage.
