### ISSUE TITLE
azure-storage-file-share tests use statically named resources

### ISSUE THREAD

**Issue by rickle-msft** [Azure/azure-sdk-for-java#6933]
See the DirectoryAsyncAPITests:"Create file" for an example. These should be changed to dynamically generated names to prevent collisions in test runs.

**Comment by alzimmermsft** [comment]
@rickle-msft could you verify if all of these have been resolved? I changed a few in the past to fix flaky live tests that hit race conditions due to the static naming.

**Comment by rickle-msft** [comment]
There are still a few places like in DirectoryAPI."Delete file" for example

**Comment by gapra-msft** [comment]
@kasobol-msft wondering if you were able to get rid of all the static resource names in your recent efforts? Can we close this?

**Comment by kasobol-msft** [comment]
not all, but all that matter.
