### ISSUE TITLE
Remove secrets for deprecated static resources from Key Vault

### ISSUE THREAD

**Issue by danieljurek** [Azure/azure-sdk-for-java#6936]
Now that we're no longer using static test resources, this issue is tracking removal of those test resources and their respecitive secrets in the AzureSDK-TestsSecrets2 KeyVault.  Unfortunately, we can't just delete this KeyVault as it still has service principal secrets that are needed to authenticate the tests.

**Comment by kurtzeborn** [comment]
Most of these we have taken care of.  @benbp is going to do a push to grab the rest of these during MQ this fall.
