### ISSUE TITLE
[QUERY] From Which version onwards the SDK support SAS token Authentication

### ISSUE THREAD

**Issue by manjudr** [Azure/azure-sdk-for-java#6944]
**Query/Question**
From Which version onwards the azure storage SDK supports the SAS token authentication 

***Why is this not a Bug or a feature Request?***
NA
 **Information Checklist**
 Kindly make sure that you have added all the following information above and checkoff the required fields otherwise we will treat the issuer as an incomplete report
- [x] Query Added
- [ ] Setup information Added

**Comment by manjudr** [comment]
Currently, I'm using version azure storage 4. Will this supports for the SAS token authentication?

```
<dependency>
    <groupId>com.microsoft.azure</groupId>
    <artifactId>azure-storage</artifactId>
    <version>4.0.0</version>
</dependency>
```

**Comment by rickle-msft** [comment]
@manjudr From what I'm seeing, 4.0.0 does support sas generation and authentication. If this answers your only question, please close the issue. Feel free to post a follow up if you have one.

**Comment by manjudr** [comment]
@rickle-msft  Thanks for your update.
May I know from which version onwards  Azure SAS authentication is supported?

**Comment by rickle-msft** [comment]
I'm pretty sure it's been supported since version 1
