### ISSUE TITLE
[Doc] Use code injection tool to include code samples from compilable Java code in readme.

### ISSUE THREAD

**Issue by mssfang** [Azure/azure-sdk-for-java#6961]
To have a ReadmeSamples java file to maintain the codesnippet of readme file. So that make sure the readme codesnippet section is compilable.

E.x.,
comment to run: npx embedme sdk/*/azure-core*/README.md
and file to take a look at 
./src/samples/java/com/azure/core/http/netty/ReadmeSamples.java

**Comment by samvaity** [comment]
Resolved in #7118
