### ISSUE TITLE
[Test] Improve the test code coverage of Text Analytics Tests

### ISSUE THREAD

**Issue by mssfang** [Azure/azure-sdk-for-java#6967]
this issue is related to [Test] Too many helper methods in the tests. Refactor the test framework. #6966

But focus on test coverage.

**Comment by samvaity** [comment]
Closing this as the test coverage for text analytics is above the expected test coverage expected threshold - https://azuresdkartifacts.blob.core.windows.net/azure-sdk-for-java/test-coverage/azure-ai-textanalytics/index.html#dn-c
