### ISSUE TITLE
Fluent flow in VM::OSDisk

### ISSUE THREAD

**Issue by anuchandy** [Azure/azure-sdk-for-java#697]
This is a thread for discussing design of `withImage`,  `defineOSDisk` variants and `withExistingOSDisk` that needs to be enabled in VM fluent definition flow. 

The `withImage`  variants allows basic user to easily declare the image to be used for the VM's OS Disk (with default configuration) 

The `defineOSDisk` variants allows user to declare the image along with OS disk configuration, such as caching, size, encryption settings etc..

The `withExistingOSDisk` allows user to attach an existing OS Disk VHD for the VM.

![office lens 20160510-144554](https://cloud.githubusercontent.com/assets/2320445/15163605/3ba32cce-16be-11e6-8b88-6018c39d684c.jpg)

```java
withImage(ImageReference imageReference);
withLatestImage(String publisher, String offer, String sku);
withKnownImage(KnownVirtualMachineImage knownImage);
withUserImage(String containerName, String vhdName);

fromImage(ImageReference imageReference);
fromLatestImage(String publisher, String offer, String sku);
fromKnownImage(KnownVirtualMachineImage knownImage);
fromUserImage(String containerName, String vhdName);

withExistingOSDisk(String containerName, String vhdName, OperatingSystemTypes osType);

defineOSDisk(String name);
storeVhdAt(String containerName, String vhdName);
DefinitionWithDataDisk attach();
```

**Comment by jianghaolu** [comment]
![grammar](https://cloud.githubusercontent.com/assets/2320445/15255997/15feb730-18f4-11e6-9c2c-d6977499bd22.png)

**Comment by anuchandy** [comment]
@jianghaolu can you put the EBNF notation for the same?

**Comment by jianghaolu** [comment]
```
Grammar ::= ( 
  ('withNewStorageAccount' | 'withExistingStorageAccount')
  (('withImage(reference)' | 'withImage(url)' | 'withLatestImage' | 'withKnownImage') 
   ('withLinuxOS' 'withRootUsername' 
     (('withSsh(key)' | 'withSsh(list)') ('withPassword' | 'withoutPassword') | 
     'withoutSsh' 'withPassword') | 
    'withWindowsOS'
      (('defineConfiguration' 'enableVMAgent'? 'enableAutoUpdate'? 'withTimeZone'? 'withWinRM'? 'apply')?
      'withAdminUserName' 'withPassword'))
  ) | ('withWindowsImage' | 'withLinuxImage'))
```

**Comment by anuchandy** [comment]
Thanks Jianghaolu.

For others who are reading this discussion: Above is Extended Backus-Naur Form (EBNF) notation representing the context and method chains in fluent API for VM OSDisk and OSProfile. The Railroad diagram  is generated using http://www.bottlecaps.de/rr/ui.

**Comment by jianghaolu** [comment]
From the graph, it may makes more sense to move the admin/password setup for Windows before the configurations as they are the required parameters.

**Comment by anuchandy** [comment]
Yes, in general we follow the pattern of keep "optionals parameters" after all "required parameters".

But in this case - was thinking that "configuration" is specific to "Windows OS" [autoupdate, winrm] and keeping it close to "WithWindowsOS()" provide better redability than placing it after "withAdminPassword". "withAdminPassword" is applicable for both Windows and Linux. 

Do you have any specific reason for this suggestion other than the problem of breaking the pattern?

```java
azure.virtualmachines().define("vm-name")
     .withRegion("region")
     .withNewResourceGroup("rg1")
     .withImage("WinServer", , ,)
     .withWindowsOS()
     .defineConfiguration()
        .disableVMAgent()
        .withWinRMListeners(lst)
        .apply()
     .withAdminUserName(uname)
     .withAdminPassword(pwd)
     .withNetwork("10.1.1.1/24")
     .withPublicIP(dns-name)
     .create();
```

v/s

```
azure.virtualmachines().define("vm-name")
     .withRegion("region")
     .withNewResourceGroup("rg1")
     .withImage("WinServer", , ,)
     .withWindowsOS()
     .withAdminUserName(uname)
     .withAdminPassword(pwd)
     .defineConfiguration()
        .disableVMAgent()
        .withWinRMListeners(lst)
        .apply()
     .withNetwork("10.1.1.1/24")
     .withPublicIP(dns-name)
     .create();
```

Also, @selvasingh recommended to use "set()" instead of "apply()", that make sense because we are already using "apply()" in "Updatble" chain. 

Instead of "disableVMAgent", we can use "withoutVMAgent" - The name "disableVMAgent()" gives an impression that - VM agent is installed by default but user want to disable it. In reality, if this flag is false Azure won't install VM Agent.

**Comment by jianghaolu** [comment]
I don't feel strongly towards either of the options. But I personally like `apply()` as it's the word showing on the buttons in [Windows setting dialogs](https://www.google.com/search?q=windows+95+settings+window&newwindow=1&biw=1280&bih=660&source=lnms&tbm=isch&sa=X&ved=0ahUKEwjsx7LnltjMAhWGo5QKHXXJDLwQ_AUIBigB#newwindow=1&tbm=isch&q=windows+95+ok+cancel+apply) for 20 years :)
We can change existing `.apply()` to `.update()` in light of the move from `.provision()` to `.create()`.

**Comment by anuchandy** [comment]
Ok, we can decide on placement of config options later.

Agree, so for top-level resources renames are `provision() -> create()`, `apply() -> update()`

For optional child complex type which we start with 'defineXXXXX()' can be end with `apply() OR set()` (e.g. `defineConfiguration` in the above diagram)

Below is the diagram showing different approach we discussed to set the intermediate complex optionals.

![grammar](https://cloud.githubusercontent.com/assets/1471612/15265121/f026af16-1931-11e6-9c9d-b366f4721ead.png)

**Comment by anuchandy** [comment]
Another way of doing this is, move admin settings for Windows before the optional configurations as below:

![grammar](https://cloud.githubusercontent.com/assets/1471612/15297017/e4d7b502-1b4c-11e6-8a05-47fc0b14b3bd.png)

**Comment by anuchandy** [comment]
***DefinitionWithOptionalStorageAccount***

![definitionwithoptionalstorageaccount](https://cloud.githubusercontent.com/assets/1471612/15306040/1f444758-1b7c-11e6-8c5c-b1403aa5decf.png)

```
DefinitionWithOptionalStorageAccount
         ::= ( 'withNewStorageAccount(name)' | 'withNewStorageAccount(StorageCreatable)' | 'withExistingStorageAccount(name)' )?
```

***DefinitionWithMarketPlaceImage***

![definitionwithmarketplaceimage](https://cloud.githubusercontent.com/assets/1471612/15306039/1f43b4f0-1b7c-11e6-88cd-db9ad25ead8b.png)

```
DefinitionWithMarketPlaceImage
         ::= 'withMarketPlaceImage()' ( 'popular(imageEnum)' | 'latest(p, o, s)' | 'version(p, o, s, v)' )
```

***DefinitionLinuxCreatable***

![definitionlinuxcreatable](https://cloud.githubusercontent.com/assets/1471612/15306041/1f4fb4e4-1b7c-11e6-873f-23161d3c592c.png)

```
DefinitionLinuxCreatable
         ::= 'withRootUserName(uname)' 'withSSH(key)'* 'withPassword'?
```

***DefinitionWindowsCreatable***

![definitionwindowscreatable](https://cloud.githubusercontent.com/assets/1471612/15306037/1f42cffe-1b7c-11e6-915c-aa012006c178.png)

```
DefinitionWindowsCreatable
         ::= 'withAdminUserName(uname)' ( 'withTimeZone(zone)' | 'withoutVMAgent()' | 'disableAutoUpdate()' | 'withWinRM(listener)' )* 'withPassword'?
```

***DefinitionVMCreatable***

![definitionvmcreatable](https://cloud.githubusercontent.com/assets/1471612/15306038/1f435294-1b7c-11e6-88a0-8e8f9c0ed8bc.png)

```
DefinitionVMCreatable
         ::= DefinitionWithOptionalStorageAccount ( ( DefinitionWithMarketPlaceImage | 'withStoredImage(url)' ) ( 'withWindows()' DefinitionWindowsCreatable | 'withLinux()' DefinitionLinuxCreatable ) | 'withOSDisk(url, osType)' ) 'create()'
```

**Comment by jianghaolu** [comment]
Beta2 released.
