### ISSUE TITLE
Investigate if Text Analytics Pii endpoints should take encrypted text input

### ISSUE THREAD

**Issue by samvaity** [Azure/azure-sdk-for-java#6979]
Investigate if Text Analytics Pii endpoints should not take plain input text.

**Comment by samvaity** [comment]
@assafi This was something that came up in our code change review from the team. Do we know if we should be expecting encrypted texts from user since Pii might have some sensitive information and we are currently expecting the user to provide that in plain text?

**Comment by assafi** [comment]
We already have encryption in transit using HTTPS. 
If TA to support additional encryption it would require a much larger setup (e.g. customers will need to provision and manage keys, upload and manage data, etc). 
Anyway, this has gone through a threat model review and was approved.

**Comment by samvaity** [comment]
Removed logging for Pii #7162
