### ISSUE TITLE
vm createOrUpdate not working

### ISSUE THREAD

**Issue by MSSedusch** [Azure/azure-sdk-for-java#698]
When I try to e.g. add a data disk to a vm I get an error that the createoption for the os disk is required and cannot be null. When I try to set the createoption of the os disk to DiskCreateOptionTypes.EMPTY I get "error":{"code":"PropertyChangeNotAllowed","target":"osDisk.createOption","message":"Changing property 'osDisk.createOption' is not allowed."}

The issue seems to be that the DataDisk.createOption and OSDisk.createOption do not get filled on retrieval of a virtual machine. I changed the field to a string and adapted the setter and getter method which seems to work

**Comment by selvasingh** [comment]
https://github.com/Azure/azure-rest-api-specs/issues/275

**Comment by MSSedusch** [comment]
Not sure if that issue is related to mine. In my case, the createOption is not getting filled when I get() a virtual machine. When I try to update the VM, I get " is required and cannot be null " because the field was not set on get()

**Comment by jianghaolu** [comment]
This is fixed in beta2. Please verify.
