### ISSUE TITLE
[BUG] [EventHubs Track 2] Checkpoint should use exclusive not inclusive offset

### ISSUE THREAD

**Issue by ellismg** [Azure/azure-sdk-for-java#6982]
This is the Java version of https://github.com/Azure/azure-sdk-for-net/issues/9158, since the Java Client suffers from the same issue.

Also - Unlike .NET (Which does not support resuming from a SequenceNumber from a checkpoint) the Java Client will use the sequence number if provided in the Checkpoint object when resuming (if the offset is null).  In this case we also use an inclusive instead of exclusive EventPosition which should mean that the same event is processed when resuming.

https://github.com/Azure/azure-sdk-for-java/blob/71ff41aadf370ceb72e420e0db3113279fd8b0bd/sdk/eventhubs/azure-messaging-eventhubs/src/main/java/com/azure/messaging/eventhubs/PartitionPumpManager.java#L123-L130

Note that the fix for https://github.com/Azure/azure-sdk-for-net/issues/9158 of just adding one to the offset fails in cases where no new events have been published, so we shouldn't blindly copy that logic.

**Comment by srnagar** [comment]
Fixed in https://github.com/Azure/azure-sdk-for-java/pull/6986. Default event position for offset and sequence numbers are now exclusive.
