### ISSUE TITLE
Pagination with 1.0.0-beta1 SDK

### ISSUE THREAD

**Issue by ankurvsoni** [Azure/azure-sdk-for-java#700]
Any suggestions on how to do pagination with ListOperationCallback? I want to:

- Request a page of VMs.
- Do some processing.
- Then request another page.

Right now, the SDK doesn't expose the nextLink to do a next page call.

**Comment by jianghaolu** [comment]
Here is a wiki showing some basic usage of `ListOperationCallback`: https://github.com/Azure/azure-sdk-for-java/wiki/ListOperationCallback. Please let us know if you have further questions!

**Comment by ankurvsoni** [comment]
Yes. I have seen this wiki. But this kind of pagination is not useful.

The client cannot control pagination apart from the example you have. In the example you have, how do you get the next page once the pagination is stop in progress method? Also, if you really have a very long list, you might run into out of memory since you are just accumulating all the data, thus rendering pagination useless.

Also, there is no way to specify how many records are part of a page.

**Comment by jianghaolu** [comment]
The client is supposed to handle data in `progress()` before making the decision to continue or stop. I guess you are looking for a way to continue even if you returned a `STOP` previously. For now maybe you can work around by placing a latch before the return decision in the process() method.

I'm aware of the drawback that this eventually loads up everything. We haven't done much to fix this in the async world. The sync list() in the master branch today returns a lazy list which you can just get the first page and call listNext() on your own.

**Comment by ankurvsoni** [comment]
If you had exposed nextPageLink, then the clients can use the other signatures like:

public ServiceCall listNextAsync(final String nextPageLink, final ServiceCall serviceCall, final ListOperationCallback<VirtualMachine> serviceCallback);

Switch to master branch is not an option, since I am already using the beta branch.

**Comment by jianghaolu** [comment]
That could be an option.

BTW, the old master branch is in 0.9 now. The currently master branch will be the 1.0.0-beta2.

**Comment by ankurvsoni** [comment]
>> BTW, the old master branch is in 0.9 now. The currently master branch will be the 1.0.0-beta2.
Sorry. I didn't get this. Currently, on master I don't see the async code, indicating that it is still on old SDK. Also in maven central I don't see 1.0.0-beta2.

**Comment by jianghaolu** [comment]
We are still doing rapid development in `master` if that's what you are concerned. We've adopted the branching model that dev goes into master and releases are tagged. In a month it will look more like a complete product.
It *will* be the 1.0.0-beta2.

**Comment by ankurvsoni** [comment]
Ok. For now I'll continue using 1.0.0-beta1. Once 1.0.0-beta2 is released, I can try and upgrade. Till then I'll try to workaround the pagination limitation.
