### ISSUE TITLE
[QUERY] How to get the List a blobs from the directory  using SAS Token

### ISSUE THREAD

**Issue by manjudr** [Azure/azure-sdk-for-java#7029]
Let's say I have a container called "Test-Container" and inside that, I have created a directory called "reports".
**Test-Container** - Container
**reports** - Directory
**test-report.json** - file inside the directory.

How to get the list items which are available in the reports directory?

```
BlobServiceClient blobServiceClient = new BlobServiceClientBuilder()
                .endpoint("https://test.blob.core.windows.net")
                .sasToken(yourSasToken)
                .buildClient();
BlobContainerClient  containerClient = blobServiceClient.getBlobContainerClient("Test-container");

System.out.println("List the blob items inside the container");
        for (BlobItem temp : containerClient.listBlobs()) {
            System.out.println(temp.getName());
        }
```
Currently refering this doc: https://github.com/Azure/azure-sdk-for-java/blob/azure-storage-blob_12.0.0/sdk/storage/azure-storage-blob/README.md

**Comment by Luyunmt** [comment]
change containerClient.listBlobs() to
![image](https://user-images.githubusercontent.com/53427149/71438219-c88f4480-272f-11ea-8de2-7ca3d49dd68b.png)

**Comment by Luyunmt** [comment]
@jongio

**Comment by Luyunmt** [comment]
Hi @manjudr  ,
How is this issue going? Feel free to let us know if further help is needed.

**Comment by rickle-msft** [comment]
I am going to close this issue as I believe it has been addressed and there has been no customer follow up.

Please feel free to reopen the issue or otherwise continue to engage if you need more support.
