### ISSUE TITLE
[BUG] Package azure-ai-textanalytics version 1.0.0-beta.1 should be self sufficient

### ISSUE THREAD

**Issue by tasharm-0412** [Azure/azure-sdk-for-java#7057]
Actual  
The package mentioned in the bug description is not enough to invoke TA API's, the user is expected the add following dependencies to include HttpClient and some other utilities.
```xml
  <dependencies>
	  <dependency>
	    <groupId>com.azure</groupId>
	    <artifactId>azure-ai-textanalytics</artifactId>
	    <version>1.0.0-beta.1</version>
	</dependency>
	<dependency>
	    <groupId>com.azure</groupId>
	    <artifactId>azure-core</artifactId>
    	<version>1.1.0</version>
	</dependency>
	<dependency>
	    <groupId>com.azure</groupId>
	    <artifactId>azure-core-http-netty</artifactId>
	    <version>1.1.0</version>
	</dependency>
</dependencies>
```

Expected :
The package should be self sufficient and should pull all its dependencies when included in the project.

**Comment by samvaity** [comment]
@tasharm-0412 This is only because it is a private preview and we are trying to add this package locally. Once it is a public preview it would no longer be required to add the transitive dependencies.

**Comment by mssfang** [comment]
![test](https://user-images.githubusercontent.com/45607042/71597530-69974a00-2af8-11ea-843a-ebb2d7d3a1d6.PNG)

After removed `azure-core` and `azure-core-http-netty` from my local .m2 repository. And then created a new maven project with only `azure-ai-textanalytics`, I can still get the `azure-core` and `azure-core-http-netty` automatically imported. Is this still an opening issue?

```
 <dependency>
            <groupId>com.azure</groupId>
            <artifactId>azure-ai-textanalytics</artifactId>
            <version>1.0.0-beta.1</version>
        </dependency>
```

**Comment by samvaity** [comment]
@tasharm-0412 could you give it a try reimporting the package using the pom file and not mention the core and netty dependencies as @mssfang described above. 
Let us know if that still doesn't work for you.

**Comment by tasharm-0412** [comment]
@samvaity  I tried this again, and facing the same issue.

POM file :
```xml
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
  <modelVersion>4.0.0</modelVersion>
  <groupId>test</groupId>
  <artifactId>temp</artifactId>
  <version>0.0.1-SNAPSHOT</version>
  <name>tarun</name>
  <dependencies>
  <dependency>
	    <groupId>com.azure</groupId>
	    <artifactId>azure-ai-textanalytics</artifactId>
	    <version>1.0.0-beta.1</version>
	</dependency>
</dependencies>
</project>
```
Error
```code
Exception in thread "main" java.lang.NoClassDefFoundError: com/azure/core/http/policy/HttpPipelinePolicy
	at sample.authenticateClient(sample.java:35)
	at sample.main(sample.java:24)
Caused by: java.lang.ClassNotFoundException: com.azure.core.http.policy.HttpPipelinePolicy
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:602)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:178)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:521)
	... 2 more
```

**Comment by tasharm-0412** [comment]
The issue was solved after a series of miscellaneous steps. This should not arise after the package is published public-ally. Closing this bug.

**Comment by samvaity** [comment]
For the internal released library to work locally the user should have to import all the packages into the local .m2 folder i.e sources.jar, .jar and the pom file and no further steps are required.
