### ISSUE TITLE
[BUG] Pii should be renamed to PII

### ISSUE THREAD

**Issue by tasharm-0412** [Azure/azure-sdk-for-java#7059]
Since PII is a acronym it should be in upper-case

Actual :
RecognizePiiEntitiesResult, recognizePiiEntities etc

Expected 
RecognizePIIEntitiesResult, recognizePIIEntities etc

**Comment by samvaity** [comment]
Java guidelines specifies not to use uppercase acronyms, here - https://azure.github.io/azure-sdk/java_design.html#naming-patterns.

We might have to further investigate if we want to replace Pii with Personally identifiable information to match the guidelines completely.

**Comment by samvaity** [comment]
Another suggestion, for this naming, could be `PersonalInformationEntity` but again it would be inconsistent naming across method and result type.  
So sticking to `Pii` as it is the standard and well-known acronym for this kind of information.
