### ISSUE TITLE
[BUG] Links are broken in the text-analytics java samples page 

### ISSUE THREAD

**Issue by tasharm-0412** [Azure/azure-sdk-for-java#7060]
All the links in the page : https://github.com/Azure/azure-sdk-for-java/tree/master/sdk/textanalytics/azure-ai-textanalytics/src/samples end up in the 404.

Expected : The links should open the examples files

**Comment by samvaity** [comment]
Fixed in https://github.com/Azure/azure-sdk-for-java/pull/7019
