### ISSUE TITLE
[BUG] Fix Nightly tests for Text Analytics

### ISSUE THREAD

**Issue by samvaity** [Azure/azure-sdk-for-java#7069]
Live tests failing on pipeline for Text Analytics.
ref - https://dev.azure.com/azure-sdk/internal/_build/results?buildId=221404&view=logs&j=4d5db6ce-0b7f-527e-b115-2367ee6e1fef&t=b7d16dfc-4abf-5ff2-eaa7-e82f3df2ef1b

**Comment by mssfang** [comment]
added this manually triggered live test pipeline for future reference: https://dev.azure.com/azure-sdk/internal/_build/results?buildId=234892&view=logs&j=4d5db6ce-0b7f-527e-b115-2367ee6e1fef&t=b7d16dfc-4abf-5ff2-eaa7-e82f3df2ef1b

**Comment by mssfang** [comment]
Turned out the endpoint value is wrong. But we still need to change
 `AZURE_TEXT_ANALYTICS_ENDPOINT: $(java-azure-textanalytics-sdk-endpoint)`
 to
`AZURE_TEXT_ANALYTICS_ENDPOINT: $(java-textanalytics-sdk-endpoint)`

**Comment by samvaity** [comment]
@assafi 
Unexpected Service behavior.
Initially for input texts: 
```java
Arrays.asList(
        "I had a wonderful trip to Seattle last week.",
        "I work at Microsoft.");
```
The service responded with 1 identified linked entities for each of the texts, [recording](https://github.com/Azure/azure-sdk-for-java/blob/master/sdk/textanalytics/azure-ai-textanalytics/src/test/resources/session-records/recognizeLinkedEntitiesForBatchInput.json#L20) but now it is returning only 0 linked entities for the same input text of `I work at Microsoft.`[here](https://dev.azure.com/azure-sdk/internal/_build/results?buildId=246582&view=logs&j=4d5db6ce-0b7f-527e-b115-2367ee6e1fef&t=b7d16dfc-4abf-5ff2-eaa7-e82f3df2ef1b&l=996). 

Is this expected/known?

**Comment by assafi** [comment]
@samvaity Yes, this is a known regression in the model. We're working on a fix with the DS team.

**Comment by maririos** [comment]
@mssfang could you try again?
Looks like latest version includes the change. 

Running your input in .NET, I get:
```
{
    "documents": [
        {
            "id": "0",
            "entities": [
                {
                    "name": "Seattle",
                    "matches": [
                        {
                            "text": "Seattle",
                            "offset": 26,
                            "length": 7,
                            "score": 0.15046201222847677
                        }
                    ],
                    "language": "en",
                    "id": "Seattle",
                    "url": "https://en.wikipedia.org/wiki/Seattle",
                    "dataSource": "Wikipedia"
                }
            ]
        },
        {
            "id": "1",
            "entities": [
                {
                    "name": "Microsoft",
                    "matches": [
                        {
                            "text": "Microsoft",
                            "offset": 10,
                            "length": 9,
                            "score": 0.18693659716732069
                        }
                    ],
                    "language": "en",
                    "id": "Microsoft",
                    "url": "https://en.wikipedia.org/wiki/Microsoft",
                    "dataSource": "Wikipedia"
                }
            ]
        }
    ],
    "errors": [],
    "modelVersion": "2020-02-01"
}
```

**Comment by mssfang** [comment]
I get the same output.

**Comment by maririos** [comment]
Great! so, is there any work remaining here? or can we close

**Comment by samvaity** [comment]
@maririos This [PR](https://github.com/Azure/azure-sdk-for-java/pull/8881) should be able to close this issue

**Comment by samvaity** [comment]
Closed in https://github.com/Azure/azure-sdk-for-java/pull/8881
