### ISSUE TITLE
[BUG] While using the Microsoft Azure SDK For Event Hubs » 3.0.2 in jdk 13 getting a ResolutionException due to Split Package Issue

### ISSUE THREAD

**Issue by venkin84** [Azure/azure-sdk-for-java#7071]
**Describe the bug**
While using the dependency Microsoft Azure SDK For Event Hubs » 3.0.2 in jdk 13 getting a java.lang.module.ResolutionException. It seems like a split package issue is happening with both azure.client.authentication and azure.client.runtime modules exporting the package com.microsoft.azure.credentials to module proton.j. The same code if not modularised and used in jdk 8 it works fine.

***Exception or Stack Trace***
/Library/Java/JavaVirtualMachines/jdk-13.0.1.jdk/Contents/Home/bin/java "-javaagent:/Applications/IntelliJ IDEA.app/Contents/lib/idea_rt.jar=54345:/Applications/IntelliJ IDEA.app/Contents/bin" -Dfile.encoding=UTF-8 -p /Users/venkin84/ws_java/library/msgProcessors/azure/eventhub/target/classes:/Users/venkin84/ws_java/library/msgProcessors/azure/eventhub/sender/target/classes:/Users/venkin84/.m2/repository/com/microsoft/azure/azure-eventhubs/3.0.2/azure-eventhubs-3.0.2.jar:/Users/venkin84/.m2/repository/org/apache/qpid/proton-j/0.31.0/proton-j-0.31.0.jar:/Users/venkin84/.m2/repository/com/microsoft/azure/qpid-proton-j-extensions/1.2.0/qpid-proton-j-extensions-1.2.0.jar:/Users/venkin84/.m2/repository/org/slf4j/slf4j-api/1.7.6/slf4j-api-1.7.6.jar:/Users/venkin84/.m2/repository/com/microsoft/azure/azure-client-authentication/1.6.12/azure-client-authentication-1.6.12.jar:/Users/venkin84/.m2/repository/com/microsoft/azure/azure-client-runtime/1.6.12/azure-client-runtime-1.6.12.jar:/Users/venkin84/.m2/repository/com/microsoft/rest/client-runtime/1.6.12/client-runtime-1.6.12.jar:/Users/venkin84/.m2/repository/com/google/guava/guava/20.0/guava-20.0.jar:/Users/venkin84/.m2/repository/com/squareup/retrofit2/retrofit/2.5.0/retrofit-2.5.0.jar:/Users/venkin84/.m2/repository/com/squareup/okhttp3/okhttp/3.12.2/okhttp-3.12.2.jar:/Users/venkin84/.m2/repository/com/squareup/okio/okio/1.15.0/okio-1.15.0.jar:/Users/venkin84/.m2/repository/com/squareup/okhttp3/logging-interceptor/3.12.2/logging-interceptor-3.12.2.jar:/Users/venkin84/.m2/repository/com/squareup/okhttp3/okhttp-urlconnection/3.12.2/okhttp-urlconnection-3.12.2.jar:/Users/venkin84/.m2/repository/com/squareup/retrofit2/converter-jackson/2.5.0/converter-jackson-2.5.0.jar:/Users/venkin84/.m2/repository/com/fasterxml/jackson/datatype/jackson-datatype-joda/2.9.8/jackson-datatype-joda-2.9.8.jar:/Users/venkin84/.m2/repository/joda-time/joda-time/2.7/joda-time-2.7.jar:/Users/venkin84/.m2/repository/io/reactivex/rxjava/1.3.8/rxjava-1.3.8.jar:/Users/venkin84/.m2/repository/com/squareup/retrofit2/adapter-rxjava/2.4.0/adapter-rxjava-2.4.0.jar:/Users/venkin84/.m2/repository/commons-codec/commons-codec/1.11/commons-codec-1.11.jar:/Users/venkin84/.m2/repository/com/microsoft/azure/adal4j/1.6.2/adal4j-1.6.2.jar:/Users/venkin84/.m2/repository/com/nimbusds/oauth2-oidc-sdk/5.64.4/oauth2-oidc-sdk-5.64.4.jar:/Users/venkin84/.m2/repository/com/sun/mail/javax.mail/1.6.1/javax.mail-1.6.1.jar:/Users/venkin84/.m2/repository/javax/activation/activation/1.1/activation-1.1.jar:/Users/venkin84/.m2/repository/com/nimbusds/lang-tag/1.4.4/lang-tag-1.4.4.jar:/Users/venkin84/.m2/repository/com/google/code/gson/gson/2.8.0/gson-2.8.0.jar:/Users/venkin84/.m2/repository/org/apache/commons/commons-lang3/3.5/commons-lang3-3.5.jar:/Users/venkin84/.m2/repository/com/microsoft/azure/azure-annotations/1.7.0/azure-annotations-1.7.0.jar:/Users/venkin84/.m2/repository/com/nimbusds/nimbus-jose-jwt/6.0.1/nimbus-jose-jwt-6.0.1.jar:/Users/venkin84/.m2/repository/com/github/stephenc/jcip/jcip-annotations/1.0-1/jcip-annotations-1.0-1.jar:/Users/venkin84/.m2/repository/net/minidev/json-smart/2.3/json-smart-2.3.jar:/Users/venkin84/.m2/repository/net/minidev/accessors-smart/1.2/accessors-smart-1.2.jar:/Users/venkin84/.m2/repository/org/ow2/asm/asm/5.0.4/asm-5.0.4.jar:/Users/venkin84/.m2/repository/com/fasterxml/jackson/core/jackson-databind/2.10.1/jackson-databind-2.10.1.jar:/Users/venkin84/.m2/repository/com/fasterxml/jackson/core/jackson-annotations/2.10.1/jackson-annotations-2.10.1.jar:/Users/venkin84/.m2/repository/com/fasterxml/jackson/core/jackson-core/2.10.1/jackson-core-2.10.1.jar -m eventhub/com.venkin84.lib.App
Error occurred during initialization of boot layer
java.lang.module.ResolutionException: Modules azure.client.authentication and azure.client.runtime export package com.microsoft.azure.credentials to module proton.j

Process finished with exit code 1

**To Reproduce**

***Code Snippet***
Add the code snippet that causes the issue.

**Expected behavior**

**Screenshots**

**Setup (please complete the following information):**
 - OS: macOS Catalina
 - IDE : IntelliJ
 - Version of the Library used Microsoft Azure SDK For Event Hubs » 3.0.2

**Additional context**

**Information Checklist**
Kindly make sure that you have added all the following information above and checkoff the required fields otherwise we will treat the issuer as an incomplete report
- [ ] Bug Description Added
- [ ] Repro Steps Added
- [ ] Setup information Added

**Comment by maggiepint** [comment]
Thanks for the feedback! We are routing this to the appropriate team for follow-up. cc @jfggdl

**Comment by JamesBirdsall** [comment]
This client only supports Java 8. There is a new, redesigned Event Hubs client coming out soon which is intended to be the way forward for new projects and offers support for newer versions of Java. Azure-eventhubs and associated packages are in legacy mode at this point: we will be maintaining them for some time yet, but the focus will be on supporting existing projects and users.

**Comment by venkin84** [comment]
Thanks James. Any ETA for the same?

**Comment by JamesBirdsall** [comment]
Sorry about the delay in responding -- I was expecting to be able to tell you that it was released. We're still working through some final stuff, but current expectation is that it should be out next week.
