### ISSUE TITLE
Parameter error while deploying ARM template using java SDK 1.0.0-beta1 release.

### ISSUE THREAD

**Issue by amitarali** [Azure/azure-sdk-for-java#708]
Getting below error while deploying ARM template. Please advise. 

Exception :com.microsoft.azure.CloudException: 400 is not a valid polling status code: The request content was invalid and could not be deserialized: 'Error converting value "{"adminUsername":{"value":"azureuser"},"dnsLabelPrefix":{"value":"aademo"},"vmSize":{"value":"Standard_D1"},"adminPassword":{"value":"azAdm1n"}}" to type 'System.Collections.Generic.Dictionary`2[System.String,Microsoft.WindowsAzure.ResourceStack.Frontdoor.Data.Definitions.DeploymentParameterDefinition]'. Path 'properties.parameters', line 1, position 363.'.

Below is the code snippet

        String resourceGroupName = "aaTestRG";
        String location = "westus";
	         //Create Resource Group
        ResourceGroup rGroup = new ResourceGroup();
        rGroup.setLocation(location);
        
        ServiceResponse<ResourceGroup> response = null;
        if (armClient.getResourceGroupsOperations().checkExistence(resourceGroupName).getBody()) {
            response = armClient.getResourceGroupsOperations().createOrUpdate(resourceGroupName, rGroup);
        }
        
        while (!armClient.getResourceGroupsOperations().checkExistence(resourceGroupName).getBody()) {
            Thread.sleep(5000);
        }

        String TEMPLATE_URI = "https://raw.githubusercontent.com/Azure/azure-quickstart-templates/master/multichain-on-ubuntu/azuredeploy.json";
        String TEMPLATE_VER = "1.0.0.0";

        Map<String, ParameterValue> parameters = new HashMap<String, ParameterValue>();
        parameters.put("dnsLabelPrefix", new ParameterValue("aademo"));
        parameters.put("adminUsername", new ParameterValue("azureuser"));
        parameters.put("adminPassword", new ParameterValue("azAdm1n"));
        parameters.put("vmSize", new ParameterValue("Standard_D1"));

        final String parametersJson = new Gson().toJson(parameters);
      
        DeploymentProperties deploymentProperties = new DeploymentProperties();
        deploymentProperties.setMode(DeploymentMode.INCREMENTAL);
        TemplateLink templateLink = new TemplateLink();
        templateLink.setUri(TEMPLATE_URI);
        templateLink.setContentVersion(TEMPLATE_VER);
        deploymentProperties.setTemplateLink(templateLink);
        deploymentProperties.setParameters(parametersJson);

        Deployment deployment = new Deployment();
        deployment.setProperties(deploymentProperties);
        
        ServiceResponse<DeploymentExtended> deployResponse = armClient.getDeploymentsOperations().createOrUpdate(resourceGroupName, "aaDeployment", deployment);
        
        if (!deployResponse.getResponse().isSuccess()) {
            String errMsg = "Error while deplying template " + TEMPLATE_URI + ". Deployment Result: " + deployResponse.getResponse().message();
            System.out.println("Error :" + deployResponse.getResponse().message());

            throw new CloudException(errMsg);
        }

**Comment by jianghaolu** [comment]
Hi @amitarali 
Your call
```java
deploymentProperties.setParameters(parametersJson);
```
is incorrect. The `setParameters` accepts an object instead of a string. So you don't need to serialize it on your own.

**Comment by amitarali** [comment]
i tried passing object as well but got some different error. Below changes solved my issue, just added getter setter and made class as public.

Earlier i defined ParameterValue  class as,
	private static class ParameterValue {
		String value;
		ParameterValue(String value) {this.value = value;}
	}

Changed to ::

public static class ParameterValue {    	
	String value;
      public ParameterValue(String value) { this.value = value; }
      public void setValue(String value){this.value = value;}
      public String getValue(){ return value; }
}

**Comment by amitarali** [comment]
Actually i also changed below call to pass object instead String. Anyway thanks Jiang for the response
deploymentProperties.setParameters(parametersJson);
