### ISSUE TITLE
Update all links in root README.md with January 2020 release tags

### ISSUE THREAD

**Issue by joshfree** [Azure/azure-sdk-for-java#7101]
Tracking issue to update all links embedded in the root repo README.md next week after release tags have been created.

Related: https://github.com/Azure/azure-sdk-for-java/pull/7098

/cc @hemanttanwar @JimSuplizio

**Comment by hemanttanwar** [comment]
I spoke to @weshaggard  and  he suggested not to keep links to libraries in this READM. Instead of  link to Appropriate release.
https://azure.github.io/azure-sdk/releases/2020-01/java.html
It avoids replication of links and reduce chance of error in future.
I will do it after azure-core release.

**Comment by hemanttanwar** [comment]
PR https://github.com/Azure/azure-sdk-for-java/pull/7236

**Comment by hemanttanwar** [comment]
The PR is closed, sdk/README.md links for SDK should be resolved now.
