### ISSUE TITLE
[BUG] com.microsoft.azure.CloudException: The Resource 'Microsoft.Compute/disks/disk-mydisk' under resource group 'myresourcegroup' was not found.

### ISSUE THREAD

**Issue by apole** [Azure/azure-sdk-for-java#7103]
VM is deleted, its disk and NIC are deleted.
After deletion of the VM, creation is started with the same name. 
Creation of disk throws following exception, but when checked on Azure Portal, disk is actually created fine.
SDK version:  1.14

***Exception or Stack Trace***
Jan 03 09:22:54  Caused by: com.microsoft.azure.CloudException: The Resource 'Microsoft.Compute/disks/disk-mydisk' under resource group 'myresourcegroup' was not found.: The Resource 'Microsoft.Compute/disks/disk-mydisk' under resource group 'myresourcegroup' was not found. 
Jan 03 09:22:54 at com.microsoft.azure.AzureClient.createExceptionFromResponse(AzureClient.java:740) 
Jan 03 09:22:54 at com.microsoft.azure.AzureClient.access$100(AzureClient.java:33) 
Jan 03 09:22:54 at com.microsoft.azure.AzureClient$24.call(AzureClient.java:716) 
Jan 03 09:22:54 at com.microsoft.azure.AzureClient$24.call(AzureClient.java:713) 
Jan 03 09:22:54 at rx.internal.operators.OnSubscribeMap$MapSubscriber.onNext(OnSubscribeMap.java:69) 
Jan 03 09:22:54 at retrofit2.adapter.rxjava.CallArbiter.deliverResponse(CallArbiter.java:120) 
Jan 03 09:22:54 at retrofit2.adapter.rxjava.CallArbiter.emitResponse(CallArbiter.java:102) 
Jan 03 09:22:54 at retrofit2.adapter.rxjava.CallExecuteOnSubscribe.call(CallExecuteOnSubscribe.java:46) 
Jan 03 09:22:54 at retrofit2.adapter.rxjava.CallExecuteOnSubscribe.call(CallExecuteOnSubscribe.java:24) 
Jan 03 09:22:54 at rx.Observable.unsafeSubscribe(Observable.java:10327) 
Jan 03 09:22:54 at rx.internal.operators.OnSubscribeMap.call(OnSubscribeMap.java:48) 
Jan 03 09:22:54 at rx.internal.operators.OnSubscribeMap.call(OnSubscribeMap.java:33) 
Jan 03 09:22:54 at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:48) 

**To Reproduce**

***Code Snippet***
osDisk = azureInstance.disks().define(diskName).withRegion(region)
						.withExistingResourceGroup(rg).withWindowsFromVhd(image)
						.withSizeInGB(size).withSku(diskSkuType)
						.create();

**Expected behavior**
Disk creation should succeed.  This issue is mostly seen during deletion and immediate re-creation sequence.
The resource not found in the group error is thrown at various stages, sometimes disk creation goes thru but VM creation fails with the similar error description. When checked from portal, VM is actually created fine .

**Screenshots**

**Setup (please complete the following information):**
 - OS: Windows
 - IDE : [e.g. IntelliJ]
 - Java SDK: 1.14

**Additional context**

**Information Checklist**
Kindly make sure that you have added all the following information above and checkoff the required fields otherwise we will treat the issuer as an incomplete report
- [-] Bug Description Added
- [ -] Repro Steps Added
- [- ] Setup information Added

**Comment by yaohaizh** [comment]
@apole  I tested on version 1.29.0 and didn't reproduce this issue. The version of the SDK that you used were quite out of date. Could you help try the same code snippet on the latest SDK? Thanks.

**Comment by apole** [comment]
Thank for the response. It takes few re-tries, to reproduce it.  We started seeing this in our production recently. We do want to upgrade to the latest SDK, but may not happen that quickly. So trying out how to mitigate.

In my trials, deallocating VM before delete and adding some wait (about 20 secs) seems to reduce the chances of this error happening.

**Comment by yaohaizh** [comment]
The issue should be service side issue since it happened intermittently. However, the 1.14.0 version is quite out of date(around 2015-06-15). 
Would suggest to upgrade the API. However, would let the service team to take a look.

**Comment by apole** [comment]
I opened ticket with MS first, but they asked me to open a ticket here.  Their reasoning is,  on Azure Portal VM is created properly, so it must be SDK which is returning the error. 

I am going to give this reference in that ticket now. Please report it to Service team on your side as well.

**Comment by Drewm3** [comment]
I do not believe this is a backend error if the VM is actually created. @apole, could you provide the details that you see in the activity log for the VM that is created when this issue occurs. If the result from the create VM (PUT API) is success, then this issue is in the client side code of the SDK instead of the backend APIs.

**Comment by Drewm3** [comment]
Closing this issue due to no response. I'll reopen this if we have more details from @apole on the issue.
