### ISSUE TITLE
Remove hardcoded SDK versions and library names from Track 1 .java files.

### ISSUE THREAD

**Issue by conniey** [Azure/azure-sdk-for-java#7106]
Track 1 libraries contains hard-coded version numbers in .java files that need to be removed and use a JAR manifest instead.
The offending files can be found here: [$\eng\versioning\version_data_java_files.txt](https://github.com/Azure/azure-sdk-for-java/blob/master/eng/versioning/version_data_java_files.txt)

**Comment by kurtzeborn** [comment]
@conniey, this appears to be an issue you created to split off the work from https://github.com/Azure/azure-sdk-for-java/issues/3141.  I'm relabeling this "Client" since I don't think your intention is that the engsys team do this work.  Correct me if I'm misunderstanding.
