### ISSUE TITLE
Dispose of newly created Schedulers

### ISSUE THREAD

**Issue by conniey** [Azure/azure-sdk-for-java#7143]
There are some schedulers that are created in tests that are not disposed of. When we create new schedulers, we are responsible for disposing of them. Check the code base for other ones to ensure they are disposed of. 

Here are a few:
* $\sdk\identity\azure-identity\src\main\java\com\azure\identity\implementation\IdentityClient.java
* $\sdk\core\azure-core-http-netty\src\test\java\com\azure\core\http\netty\implementation\NettyFluxTests.java
* com/azure/core/http/okhttp/OkHttpClientTests.java

**Comment by mclay** [comment]
please assign me this issue

**Comment by conniey** [comment]
Thanks @mclay  :D

**Comment by alzimmermsft** [comment]
Closing as the Netty and OkHttp `HttpClient` now use the constant global `Schedulers` for testing (`Schedulers.boundedElastic`) and `IdentityClient` has no references to `Scheduler` anymore.
