### ISSUE TITLE
[KeyVault] Use embedme to inject code snippets in README

### ISSUE THREAD

**Issue by srnagar** [Azure/azure-sdk-for-java#7154]
READMEs are the first point of interaction for users looking to use our SDKs. It contains several useful code snippets for users to get started quickly. It is important to keep these code samples correct at all times. However, when code is modified README gets outdated and hard to figure out which README is referencing the modified piece of code.

Use https://github.com/zakhenry/embedme to embed code snippets from compilable Java files.

### Code snippets in README

Samples in all `README.md` files should use compilable code to ensure they are updated when source code is updated. To do so, we use [a utility tool](https://github.com/zakhenry/embedme) to embed source code from Java files into README markdown files. Steps to add code snippets in README using the tool:
- [Download](https://nodejs.org/en/download/) and install NodeJS 
- Create `ReadmeSamples.java` file in src/samples/java/<main-package> for which README.md should be updated
- Add all the code snippets in the above Java file that should be included in README.md
- Now, in README.md, add the `embedme` tag as shown below (the sample shows inserting code from line number 10 to 20)
~~~text
<!-- embedme path/to/ReadmeSamples.java#L10-L20 -->
```java
```
~~~
- To embed code using the tool, run the following command
```shell
npx embedme path/to/README.md
```
- Verify the README.md file to confirm the samples are inserted as expected

**Comment by mclay** [comment]
please assign me this issue

**Comment by vcolin7** [comment]
Thanks for the interest in this issue @mclay! It's assigned it to you :)

**Comment by samvaity** [comment]
Should we close this issue @vcolin7 ?

**Comment by vcolin7** [comment]
@samvaity no, we haven't added code snippets to our Key Vault READMEs. I think this is something we can leave for MQ.
