### ISSUE TITLE
JSR203 NIO FileSystemProvider?

### ISSUE THREAD

**Issue by ryan-williams** [Azure/azure-sdk-for-java#7158]
Has one been implemented for Azure storage? Just wondering, thanks!

**Comment by rickle-msft** [comment]
Quick update: This package is in master and is actively moving towards preview. You can see the progress [here](https://github.com/Azure/azure-sdk-for-java/tree/master/sdk/storage/azure-storage-blob-nio). The latest PR is [here](https://github.com/Azure/azure-sdk-for-java/pull/8121) and includes support for creating directories.

There is also a design doc posted in the root of that project if anyone has an interest in reading that to understand the approach we are taking. As development continues, javadocs on the public methods will also be an important source for understanding more details of the design.

**Comment by SHarrySeldon** [comment]
Hi! Is there any updates on this feature?

**Comment by rickle-msft** [comment]
@SHarrySeldon Yes! We are hoping to preview in the next month or two. You can see the current state of the project [here](https://github.com/Azure/azure-sdk-for-java/tree/master/sdk/storage/azure-storage-blob-nio). The next planned items are adding support for InputStream and OutputStream. 

If you have any scenarios that are particularly interesting to you or are interested in installing and trying out what's available, we would be happy to have your input.

**Comment by rickle-msft** [comment]
Hello, everyone!

I am very happy to announce that we have officially released the first preview of Azure Storage Blob NIO. The package info is
```
<groupId>com.azure</groupId>
  <artifactId>azure-storage-blob-nio</artifactId>
  <version>12.0.0-beta.2</version>
```
and you should be able to import it into your projects now. 

Thank you all for your patience, and please let us know if you have any feedback; we look forward to hearing from you! I am going to close this particular issue as we have released now, but please do feel free to open new issues or feature requests as you have them.

@SHarrySeldon @ryan-williams @pditommaso @fstrozzi @stewartadam @landro @nalinigans

**Comment by pditommaso** [comment]
Nice! Is beta.2 expected to be avail/public? [Can only see beta.1](https://search.maven.org/search?q=storage-blob-nio).

**Comment by rickle-msft** [comment]
Sorry. Beta.1 is the version we just shipped. My comment was wrong (I accidentally pulled from the pom after we did our version increment).

**Comment by pditommaso** [comment]
Ok, no pb.
