### ISSUE TITLE
Require resources in challenge-based authentication to use HTTPS

### ISSUE THREAD

**Issue by heaths** [Azure/azure-sdk-for-java#7238]

**Comment by alzimmermsft** [comment]
@g2vinay has this been done? I know there were some changes in Identity to require HTTPS to be used when using AAD tokens.

**Comment by heaths** [comment]
Also, while you're in there, check to make sure you don't have a similar problem as Azure/azure-sdk-for-net#9737, for which I have a PR out on at Azure/azure-sdk-for-net#10673.

**Comment by g2vinay** [comment]
This change has been done and released.
