### ISSUE TITLE
Add Unit tests for RequestTimeline, RequestRecord.stage, and RequestRecord.takeSnapshot

### ISSUE THREAD

**Issue by David-Noble-at-work** [Azure/azure-sdk-for-java#7250]
When this issue is resolved we'll have RntbdTransportClient unit test to ensure that:

- Cancellations from reactor result in request cancellations.
  verifyRequestCancellations
- CosmosClientException results are correct.
  verifyRequestExceptions
- Request stage transitions operate as expected.
  verifyRequestStages
- Request timelines make sense.
  verifyRequestTimelines

**Comment by kushagraThapar** [comment]
@xinlian12  - can you please close this issue if it is already done ?

**Comment by kushagraThapar** [comment]
This is done in `RntbdTransportClientTest`
