### ISSUE TITLE
API to fetch template parameters?

### ISSUE THREAD

**Issue by amit-dali** [Azure/azure-sdk-for-java#727]
Is there any API to fetch template parameters based on template url ? AWS has API which returns template parameters based on template url & few other AWS specific inputs.

**Comment by jianghaolu** [comment]
@amit-dali  We don't have such an API. Is there a scenario you are running into that is blocked by this?

**Comment by amit-dali** [comment]
@jianghaolu Case is - I need to populate/show template parameters with the details based on the input ARM template URL provided by end user.

**Comment by jianghaolu** [comment]
I see. It seems like you are looking for a template parser that can understand what parameters it needs from the users. We don't have such a tool but it shouldn't be too hard to code something to read in the template file and look into the "parameters" tree?

**Comment by amit-dali** [comment]
@jianghaolu - No issues in writing template parsing code at client side/calling code. Issue is if in future there is change in template format (without backward compatibility), then calling/client code has to be updated. To avoid such a case central/common public API is better option, so calling/client code will not have any impact due to change in the template format.

**Comment by amit-dali** [comment]
Cloud you please provide me API name or java docs or any example ?

**Comment by jianghaolu** [comment]
I've requested the feature for you.

**Comment by amit-dali** [comment]
not required for now
