### ISSUE TITLE
Aggregate quality/engineering reports

### ISSUE THREAD

**Issue by mitchdenny** [Azure/azure-sdk-for-java#7271]
I've created this issue to start a conversation about our strategy around aggregate reporting requirements in the Java repo. My understanding is that the aggregate reports allow the team to get a 30,000ft view of potential quality issues across all track 2 libraries in the repository, and that there is a strong view that we want to retain this capability.

At the same time we've been doing work from the engineering systems perspective to try and make the pipeline for each set of artifacts as independent as possible so that an issue in one part of the code base doesn't break the build and release capability across all pipelines. We've also been wanting to do some structural work to move our parent POMs into the ```sdk/parents``` folder.

As I've been working on this PR I've come up against issues where aggregate reporting, and the need to have modules referenced in parent POMs is at odds with independent pipelines.

https://github.com/Azure/azure-sdk-for-java/pull/6424

It looks like Alan is already doing some work to make it possible to execute spot bugs against the ```pom.service.xml``` aggregators which is complimentary to the PR I am working on above:

https://github.com/Azure/azure-sdk-for-java/pull/6661

What I would like to get out of raising this issue is consensus on:

1. Moving away from ```pom.client.xml``` or any parent POMs having module references, and making them pure parents.
2. Allowing any analysis steps like spotbugs, checkstyle, revapi etc to be run directly against the module (e.g. ```sdk/core/azure-core/pom.xml```) or the aggregator POM (e.g. ```sdk/core/pom.service.xml```).
3. Favor execution of these now more narrowly scoped goals as part of the standard workflow so that developers get feedback on their dev boxes with low effort.

BUT ... the above moves us away from an aggregate reporting capability. And I want to have our cake and eat it too. My proposal is that we have a special pipeline whose purpose is to reference all our modules and execute the aggregate steps that are desired. This would then publish those aggregate reports wherever they need to go, similar to what java - client has done in the past.

The individual pipelines should still produce reports scoped to what they build and ship, but they probably wouldn't publish them anywhere (although they could be run locally and pulled from the pipeline aritfacts).

I feel like we are halfway there now with the work that Alan has been doing and I see that we have some issues in the repo already that are pushing that direction. I just wanted to see if this is something that we can state as an explicit goal.

/cc @JonathanGiles @JimSuplizio @conniey @alzimmermsft @weshaggard

**Comment by alzimmermsft** [comment]
Option #2 is already realized where the analysis steps, such as Spotbugs and Checkstyles, are being ran against the aggregator POM (`pom.service.xml`), with the exception of Azure Core which uses `pom.client.xml` given modifying it effects all modules. 

I believe we're in a good state with regards to this where running analysis against `pom.client.xml` could perform an aggregate across the entirety of track 2 SDKs but PR validation uses the aggregators where the individual client SDKs use inherited analysis configurations from `pom.client.xml`.

**Comment by mitchdenny** [comment]
What I'm thinking is that we would modify ```sdk/core/pom.service.xml``` to include a link to all modules so it in effect becomes the master module list and will always run on changes to ```eng/``` and changes to ```sdk/core/```. And then we can use it of aggregate reports as well.

**Comment by mitchdenny** [comment]
Update on this. We ended up with a separate pipeline for aggregate reports. There is still an issue that is being debugged but that should be sorted out soon.

**Comment by mitchdenny** [comment]
We also added some guidelines which mention what kind of things should go in unified pipelines:

https://azure.github.io/azure-sdk/policies_pipelines.html

Specifically calling out aggregate reports as something that should be in a separate special purpose pipeline since they are repo wide.

**Comment by JimSuplizio** [comment]
@mitchdenny one of the things we should consider add to the aggregate report would be skip variables for the larger pieces. Just a suggestion.
