### ISSUE TITLE
HttpLoggingPolicy check log level from canLogAtLevel instead of env.

### ISSUE THREAD

**Issue by sima-zhu** [Azure/azure-sdk-for-java#7315]
**Summary** 
ClientLogger is currently reading loglevel from either slf4j binding or env.
`HttpLoggingPolicy` is still use env variable to determine whether log or now.

**Current Implementation**
```
        int numericLogLevel = LoggingUtil.getEnvironmentLoggingLevel().getLogLevel();

        if (shouldLoggingBeSkipped(numericLogLevel)) {
            return Mono.empty();
        }
```
**Expect changes**
```
        if (clientLogger.canLogAtLevel(LogLevel.INFOMATIONAL)) {
            return Mono.empty();
        }
```

**Comment by alzimmermsft** [comment]
It appears that `HttpLoggingPolicy` only uses the logging level supported by the `ClientLogger` now, closing this issue. Feel free to associate the fix PR to this issue.
