### ISSUE TITLE
Issues with Key Vault Client and getSecretAsync

### ISSUE THREAD

**Issue by rreilly70** [Azure/azure-sdk-for-java#733]
I am trying to pull a secret from Key Vault using KeyVaultClient.getSecretAsync() method.  I am able to get the secret but the thread created when the getSecretAsync() method is called does not close once completed.  Is there something I am missing?

**Comment by jianghaolu** [comment]
Hi @rreilly70 
Our async methods in 0.9.x clients return you a `Future` object so we can't shutdown the executor service in our code. You can call `client.getExecutorService().shutdown()` in your `finally` block or after `futureObject.get()` returns.

**Comment by rreilly70** [comment]
Hi @jianghaolu 

I followed your advice and was able to get an immediate shutdown.  In order to get at the `client.getExecutorService().shutdown()` method I needed to do a cast.  It's not real pretty but does work.  Does this look like the best approach to you?
`Future<Secret> result = vc.getSecretAsync(keyIdentifier);`
`String secretValue = result.get().getValue();`
`((ServiceClient<KeyVaultClient>)vc.getServiceClient()).getExecutorService().shutdown();`

**Comment by jianghaolu** [comment]
This piece of code works for me:
```java
Future<Secret> result = keyVaultClient.getSecretAsync(secretId.getBaseIdentifier());
try {
    result.get();
} catch (ExecutionException e) {
    ServiceException cause = (ServiceException) e.getCause();
    Assert.assertNotNull(cause.getError());
    Assert.assertEquals("SecretNotFound", cause.getError().getCode());
} finally {
    keyVaultClient.getServiceClient().getExecutorService().shutdown();
}
```

**Comment by rreilly70** [comment]
Thanks. Much cleaner than mine.  Works Great.  Thanks again!

**Comment by jianghaolu** [comment]
You're welcome.
