### ISSUE TITLE
cosmos ci should use the archetype-sdk-client.yml template instead of archetype-sdk-tests.yml 

### ISSUE THREAD

**Issue by danieljurek** [Azure/azure-sdk-for-java#7339]
This will require that the `archetype-sdk-client.yml` be split or refactored to allow for the type of test job combinations in the `cosmos-sdk-client.yml`. 

We should keep the internal live test yml and ci yml concerns separated in the event that we build assumptions into the archtetype yml files (as we did with dynamic resource allocation)

**Comment by kurtzeborn** [comment]
Some of this is done.  There are some special snowflakes lingering.  We're comfortable with where we're at.  When it becomes a problem, we react and migrate the problems.
