### ISSUE TITLE
Implement the rest APIs of DefaultLogger

### ISSUE THREAD

**Issue by sima-zhu** [Azure/azure-sdk-for-java#7341]
**Summary:**
ClientLogger is providing logging strategy to public use. We have a DefaultLogger which is used when client logger is not able to find SLF4J binding.

The DefaultLogger is an impl of SLF4J. There are bunch of APIs are inherited from SLF4J logger but not implemented yet.

**Task:**
Fill in the implementation of the DefaultLogger APIs.
1. For API is*Enabled() (e.g. `isDebugEnabled()`), we can check env variable to determine whether log is able to print.
1. For APIs related to trace, it is a low priority speaking to others.

**Comment by fdmcneill2019** [comment]
Question: Is there already a class DefaultLogger or does it need to be entirely created? If so, will it need to be similar to the implementation of ClientLogger?

**Comment by srnagar** [comment]
@fdmcneill2019 Thank you for your interest in this issue. @sima-zhu has worked through the implementation and there's an open PR for this - #7298 

Please feel free to look for other open issues that might interest you.

**Comment by JonathanGiles** [comment]
This will be done in #7298.
