### ISSUE TITLE
[FEATURE REQ] Add request timeline to HttpClient and HttpTransportClient

### ISSUE THREAD

**Issue by David-Noble-at-work** [Azure/azure-sdk-for-java#7342]
See PR#7227. Consider renaming `HttpClient` as `HttpGatewayClient`.

**Comment by fdmcneill2019** [comment]
Is this issue taken?

**Comment by kushagraThapar** [comment]
@fdmcneill2019 Not yet, this is currently in backlog, and will be updated when we pick this.

**Comment by David-Noble-at-work** [comment]
Completed by @simplynaveen20
