### ISSUE TITLE
ForbiddenError while resourcegroup creation using java SDK 1.0.0-beta1 release.

### ISSUE THREAD

**Issue by amitarali** [Azure/azure-sdk-for-java#735]
Getting below error while resourcegroup creation. 

com.fasterxml.jackson.core.JsonParseException: Unexpected character ('<' (code 60)): expected a valid value (number, String, array, object, 'true', 'false' or 'null')
 at [Source: <Error xmlns="http://schemas.microsoft.com/windowsazure" xmlns:i="http://www.w3.org/2001/XMLSchema-instance"><Code>ForbiddenError</Code><Message>The server failed to authenticate the request. Verify that the certificate is valid and is associated with this subscription.</Message></Error>; line: 1, column: 2]

 Below is the code snippet

```
ApplicationTokenCredentials appTokenCreds = new ApplicationTokenCredentials(clientId, tenantId, clientSecret,  AzureEnvironment.AZURE);
 String baseURL = "https://management.core.windows.net/";
 ResourceManagementClient armClient = new ResourceManagementClientImpl(baseURL, appTokenCreds);
 armClient.setSubscriptionId(subscriptionId);
 String location = "North Europe";
 //Create Resource Group
ResourceGroup rGroup = new ResourceGroup();
rGroup.setLocation(location);
ServiceResponse<ResourceGroup> response = armClient.getResourceGroupsOperations().createOrUpdate("testRG", rGroup);
```

But if i change below line and pass only ApplicationTokenCredentials, resource group creation works.

`ResourceManagementClient` armClient = new ResourceManagementClientImpl(appTokenCreds);`

  What is the way to set baseURL in ResourceManagementClient?

**Comment by anuchandy** [comment]
@amitarali  The base URI should be "https://management.azure.com"

**Comment by amitarali** [comment]
Yes, it works. Thanks!!

To integrate with Microsoft Azure Government,  do we only need to change this URI? or anything else also need to be taken care?

**Comment by amitarali** [comment]
And what is the URI for Microsoft Azure Government?

**Comment by amitarali** [comment]
**@anuchandy**  do you any idea on below queries?

To integrate with Microsoft Azure Government, do we only need to change this URI? or anything else also need to be taken care?
And what is the URI for Microsoft Azure Government?

**Comment by amitarali** [comment]
I see just two options for AzureEnvironment. Is there anything similar for Azure US government subscription. 
AzureEnvironment.AZURE
AzureEnvironment.AZURE_CHINA

**Comment by anuchandy** [comment]
The resource management endpoint for US Govt is https://management.usgovcloudapi.net

**Comment by anuchandy** [comment]
The environment is not yet defined for US Govt in SDK, but here is the various endpoint related to US Govt that you can use explicitly.

```
    portalUrl: 'https://manage.windowsazure.us',
    publishingProfileUrl: 'https://manage.windowsazure.us/publishsettings/index',
    managementEndpointUrl: 'https://management.core.usgovcloudapi.net',
    resourceManagerEndpointUrl: 'https://management.usgovcloudapi.net',
    sqlManagementEndpointUrl: 'https://management.core.usgovcloudapi.net:8443/',
    sqlServerHostnameSuffix: '.database.usgovcloudapi.net',
    galleryEndpointUrl: 'https://gallery.usgovcloudapi.net/',
    activeDirectoryEndpointUrl: 'https://login.microsoftonline.com',
    activeDirectoryResourceId: 'https://management.core.usgovcloudapi.net/',
    activeDirectoryGraphResourceId: 'https://graph.windows.net/',
    activeDirectoryGraphApiVersion: '2013-04-05',
    storageEndpointSuffix: '.core.usgovcloudapi.net',
```

**Comment by amitarali** [comment]
So currently is it not possible to provision to Azure US govt using SDK? until SDK supports environment for US govt?
OR
Will below code work to support provisioning to AZURE US Govt

 String baseURL = "https://management.usgovcloudapi.net";
 ResourceManagementClient armClient = new ResourceManagementClientImpl(baseURL, appTokenCreds);
 armClient.setSubscriptionId(subscriptionId);
 String location = "North Europe";
 //Create Resource Group
ResourceGroup rGroup = new ResourceGroup();
rGroup.setLocation(location);
ServiceResponse<ResourceGroup> response = armClient.getResourceGroupsOperations().createOrUpdate("testRG", rGroup);

**Comment by jianghaolu** [comment]
`AzureEnvironment` is an extendable enum. You are allowed to create your own environment by
```java
AzureEnvironment govt = new AzureEnvironment(
            "https://login.microsoftonline.com",
            "https://management.core.usgovcloudapi.net/",
            true,
            "https://management.usgovcloudapi.net/")

**Comment by amitarali** [comment]
Thanks for the reply. With beta2 , i can see other environments as well.

**Comment by amitarali** [comment]
My azure client application is on a server with no internet connection, is the list of below URIs need to be allowed for this server? Am i missing anything?

Management Portal	manage.windowsazure.com
General	*.windows.net
Core	*.core.windows.net
Compute	*.cloudapp.net
Blob Storage	*.blob.core.windows.net
Queue Storage	*.queue.core.windows.net
Table Storage	*.table.core.windows.net
Service Management	management.core.windows.net
SQL Database	*.database.windows.net
ARM Load balanced Endpoint	 https://management.windows.net
activeDirectoryEndpointUrl: 'https://login.microsoftonline.com

**Comment by jianghaolu** [comment]
I think this is a good list. Please let us know if any request fails.

**Comment by martinsawicki** [comment]
fixed
