### ISSUE TITLE
[Storage] Test: Replace long sleeps with polling

### ISSUE THREAD

**Issue by mikeharder** [Azure/azure-sdk-for-java#7353]
When possible, tests should use polling with short sleeps instead of a single long sleep.  Polling with short sleeps is better because tests run as quickly as possible, yet still have the flexibility to wait as long as necessary for things to reach the desired state.  A single long sleep is worse because if it's too long it wastes time, and if it's too short it's unreliable.

**Comment by alzimmermsft** [comment]
Closing this as the tests now run in parallel which reduces the amount of time wasted due to thread sleeping.
