### ISSUE TITLE
What is going on with the Azure Table SDK?

### ISSUE THREAD

**Issue by maltalex** [Azure/azure-sdk-for-java#7361]
Hi

I'm wondering what are the plans for the SDK for Azure Tables.

The Table SDK has been part of the Azure Storage SDK, but that SDK dropped the support for Tables in 2018, with the release of version 10. Azure Tables are now supported only by the "Legacy" version 8 (https://github.com/azure/azure-storage-java/tree/legacy-master) and when asked, the storage sdk developer said that the responsibility for Azure Tables moved to the cosmosdb team (https://github.com/Azure/azure-storage-java/issues/393). And now I see that the cosmosdb repo moved here (https://github.com/Azure/azure-cosmosdb-java/issues/251). However, I still don't see any new releases.

So where does that leave the Table SDK? Is it going to stay on the legacy branch? Is a different team going to start releasing new versions? Are there actually new versions somewhere which I didn't find? How long will the legacy version 8 will be supported? I'd like to know what the plan is.

**Comment by rickle-msft** [comment]
Hi, @maltalex. I can answer a few of your questions. v8 will continue to live on the legacy branch of the azure-storage-java repo. We do not plan to add any more features to it, though we may add any security fixes that are critical. I am not sure what the future of the tables sdk looks like as that work has been transferred from our team. 

@joshfree do you know what the status of track 2 cosmos sdks are?

**Comment by maltalex** [comment]
@rickle-msft Thank you for the input and for your work on the storage sdk.

**Comment by maltalex** [comment]
@joshfree I'm assigned to answer my own question?

**Comment by Petermarcu** [comment]
@maltalex fresh off the presses. We're going to be working on a new library that will be backed by the Azure Storage Tables service. Lots of design and planning to do still but we hope to have something to preview by the summer.

**Comment by maltalex** [comment]
@Petermarcu Thanks for the response.

Just to clarify, by "**backed** by the Azure Storage Tables" do you mean a library for working with the Table API or something more high level? I feel like the abstraction layer is fine in the current SDK, but the performance isn't great since everything is synchronous. 

Anyway, I'm happy to hear there's something's on the roadmap.

**Comment by Petermarcu** [comment]
Still designing but I expect it will be at a similar level as the current one with probably some access to lower level. We will also be providing async api's per our guidelines.

**Comment by Petermarcu** [comment]
Stay tuned for announcements in coming months. I'm going to go ahead and resolve this issue.

**Comment by maltalex** [comment]
@Petermarcu 
Hi, any updates on a new Java SDK version?

**Comment by Petermarcu** [comment]
Work started on this a couple weeks ago. It's a fairly decent size library and we're hoping to preview something sometime in June or so.

**Comment by maltalex** [comment]
Great, thanks.

**Comment by bsiegel** [comment]
Just wanted to provide a quick update - you can track our work towards our first preview release of the new Azure Tables library in issue #13730.

Related-to: #14084
