### ISSUE TITLE
Is this the right way SharedAccessSignature ?

### ISSUE THREAD

**Issue by raintears** [Azure/azure-sdk-for-java#738]
Hi,

I tried the following and It uploads the file i want to my container even though the permissions is set to read only. 

```
SharedAccessBlobPolicy policy = new SharedAccessBlobPolicy();
policy.setPermissions(EnumSet.of(SharedAccessBlobPermissions.READ));
BlobContainerPermissions permissions  = new BlobContainerPermissions();
permissions.setPublicAccess(BlobContainerPublicAccessType.OFF);
permissions.getSharedAccessPolicies().put("default", policy);
container.uploadPermissions(permissions);
CloudBlockBlob blob = container.getBlockBlobReference("test");
blob.upload ...
```

anyone knows what's wrong with the SAS ? Did i miss out anything?

**Comment by hello-azure** [comment]
CloudBlobClient blobClient = account.createCloudBlobClient();
	            CloudBlobContainer container = blobClient.getContainerReference("container1");
	            container.createIfNotExists();
	            SharedAccessBlobPolicy policy = new SharedAccessBlobPolicy();
	            GregorianCalendar calendar =
	             new GregorianCalendar(TimeZone.getTimeZone("UTC"));
	            calendar.setTime(new Date());

	            policy.setSharedAccessStartTime(calendar.getTime());
	            calendar.add(Calendar.HOUR, 1);
	            policy.setSharedAccessExpiryTime(calendar.getTime());
	            policy.setPermissions(EnumSet.of(SharedAccessBlobPermissions.READ,
	               SharedAccessBlobPermissions.WRITE, SharedAccessBlobPermissions.DELETE,
	               SharedAccessBlobPermissions.LIST));
	            BlobContainerPermissions containerPermissions =
	             new BlobContainerPermissions();
	            containerPermissions.setPublicAccess(BlobContainerPublicAccessType.OFF);
	            container.uploadPermissions(containerPermissions);
	            String sas = container.generateSharedAccessSignature(policy,null);
	            System.out.println("The basic shared access signature :");
		      System.out.println(sas);

**Comment by raintears** [comment]
I'm having a storage exception with this message. the Server failed to authenticate the request. make sure the value of Authorization header is formed correctly including the signature.

**Comment by hello-azure** [comment]
Global Azure? China Azure? Can you share your code?

**Comment by raintears** [comment]
This is the code im using.

```
CloudStorageAccount account = new CloudStorageAccount(new StorageCredentialsAccountAndKey(a, k));
client = account.createCloudBlobClient();
container = client.getContainerReference(name);
container.createIfNotExists();
SharedAccessBlobPolicy policy = new SharedAccessBlobPolicy();
policy.setPermissions(EnumSet.of(SharedAccessBlobPermissions.READ));
BlobContainerPermissions permissions  = new BlobContainerPermissions();
permissions.setPublicAccess(BlobContainerPublicAccessType.OFF);
permissions.getSharedAccessPolicies().put("default", policy);
container.uploadPermissions(permissions);
CloudBlockBlob blob = container.getBlockBlobReference("test");
blob.uploadFromByteArray(....);
```

**Comment by hello-azure** [comment]
From the error, it looks like some incorrect operation in create credential, maybe youcan see the following code(test connect to china azure, if you do not set the endpoint, the default behavior will point to global auzre endpoint, so you need to clearly know your storage account and endpoint):
StorageCredentials credentials = new StorageCredentialsAccountAndKey("test", 
				"xxxxx
		
		URI blobEndpoint = URI
				.create("https://test.blob.core.chinacloudapi.cn/");
		URI queueEndpoint = URI
				.create("https://test.queue.core.chinacloudapi.cn/");
		URI tableEndpoint = URI
				.create("https://test.table.core.chinacloudapi.cn/");
		
		

	
		CloudStorageAccount storageAccount = new CloudStorageAccount(credentials,
				blobEndpoint, queueEndpoint, tableEndpoint);
		
		 TrustManager[] trustAllCerts = new TrustManager[] { new X509TrustManager() {
			public X509Certificate[] getAcceptedIssuers() {
				return null;
			}

	        public void checkClientTrusted(X509Certificate[] certs,String authType) {
			}
             public void checkServerTrusted(X509Certificate[] certs,String authType) {}
			} };
			SSLContext sc = SSLContext.getInstance("TLS");
			sc.init(null, trustAllCerts, new SecureRandom());
            HttpsURLConnection.setDefaultSSLSocketFactory(sc.getSocketFactory());

**Comment by martinsawicki** [comment]
Storage SDK issues should go to the correct repo: http://GitHub.com/Azure/azure-storage-java
