### ISSUE TITLE
Some analyze steps are running for data in spite of the verification being client only

### ISSUE THREAD

**Issue by JimSuplizio** [Azure/azure-sdk-for-java#7400]
In the Analyze step of the CI pipelines there are a couple of steps that are being done when a CI is manually triggered for a release.
1. The 'Generate Maven project site, including JavaDocs, SpotBugs, and CheckStyle reports' step only ever runs on mavenPomFile: pom.client.xml and should be excluded for data track libraries. Once the changes I'm making to the client/data ci.yml/ci.data.yml get checked in, a condition of eq('${{ parameters.SDKType }}', 'client') could be added to limit this to client builds.
2. Both 'Download dependency checker' and 'Analyze dependencies' are also only valid for client libraries because of the [dependencies.json](https://github.com/Azure/azure-sdk-for-java/blob/master/dependencies.json) file in our repro that it runs against. @JonathanGiles should we be running the dependency checker on more than just client? It seems that with data, and eventually management, being in our repo that we should probably at least be able to run it against more than just client. That would also require the [dependencies reports](https://azuresdkartifacts.blob.core.windows.net/azure-sdk-for-java/staging/dependencies.html) being updated to accommodate multiple tracks as well.

**Comment by mitchdenny** [comment]
Thanks for raising this Jim. I was thinking about the difference we have between data, client and management build types a few days ago myself. One of the things that I had in the back of my head when I setup the current ```archetype-sdk-[thing]``` pattern was that we would have archetypes of each different kind of build.

So perhaps we should start heading that direction now and have ```archetype-sdk-client.yml```, ```archetype-sdk-data.yml``` and ```archetype-sdk-management.yml``` and then any common elements are pulled out into separate template fragments so we can avoid duplication.

Then ... we simply omit track 2 only things in the ```archetype-sdk-data.yml``` templates.

**Comment by mitchdenny** [comment]
We would actually want to apply this pattern across all repos. But it bites especially on java :)
