### ISSUE TITLE
Can't download Azure NotificationHub SDK 

### ISSUE THREAD

**Issue by AlexJuca** [Azure/azure-sdk-for-java#7419]
Is the Azure NotificationHub SDK missing from maven central?
I have multiple spring projects using this SDK and all projects fail to download the dependency.

I get the following error while trying to download the dependency:

```Unable to resolve all dependencies for: co.ao.metalogger:metalogger:0.0.1-SNAPSHOT. Falling back to non-transitive mode for initial artifact resolution.
[WARNING] The POM for com.windowsazure:Notification-Hubs-java-sdk:jar:0.0.5 is missing, no dependency information available
```

Can anyone help me understand why I can not download this dependency?

**Comment by JonathanGiles** [comment]
Hi @AlexJuca - you might have more luck asking this question over in this GitHub repo: https://github.com/Azure/azure-notificationhubs-java-backend

I note that they released 0.1.0 back in September 2019, so you may want to consider that also. Here is some more info I found: https://bintray.com/microsoftazuremobile/SDK/Notification-Hubs-Java-Backend-SDK

I'll close this issue for now, but please reopen if you fail to get support - thanks for using Azure SDKs for Java!
