### ISSUE TITLE
[Design] Framework for creating azure resource dependencies [with possible parallelization in future]

### ISSUE THREAD

**Issue by anuchandy** [Azure/azure-sdk-for-java#743]
The fluent SDK allows defining a `Creatable` resource by composing a set of `Creatable` resources that it depends on. Below is an example showing such a definition for VM `Creatable`.

```java
ResourceGroup.Creatable rg1 = resourceGroups()
    .define("rg1")
    .withRegion(Region.EastUS);

ResourceGroup.Creatable rg2 = resourceGroups()
    .define("rg2")
    .withRegion(Region.EastUS);

PublicIP.Creatable pip1 = publicIPs()
    .define("pip1")
    .withRegion(Region.EastUS)
    .withResourceGroup(rg1)
    .<other_parameters_to_get_a_Creatable>

NetworkInterface.Creatable nic1 = networkInterfaces()
   .define("nic1")
   .withRegion(Region.EastUS)
   .withResourceGroup(rg1)
   .<other_parameters_to_get_a_Creatable>
   .withPublicIP(pip1)
   
StorageAccount.Creatable stg1 = storageAccounts()
    .define("stg1")
    .withRegion(Region.EastUS)
    .withResourceGroup(rg2)

VirtualMachine.Creatable vm1 = virtualMachines()
    .define("vm1")
    .withRegion(Region.EastUS)
    .withResourceGroup(rg1)
    .withNetworkInterface(nic1)
    .<other_parameters_to_get_a_Creatable>
    .withStorageAccount(stg1)
```

The above composition result in below DAG.

![dag](https://cloud.githubusercontent.com/assets/1471612/15660179/7c9a4468-268d-11e6-93ed-5d5d4eb0f2e5.png)

From the DAG, it's clear that in what order we need to create the resources. 

Also `Creatables` with the same `Order` can be created in parallel.

![time](https://cloud.githubusercontent.com/assets/1471612/15660187/862425b2-268d-11e6-89ed-fadd0e1fcc05.png)

We want to build a framework for this in the fluent SDK. Mostly we will do parallel creation later releases, but building this framework will help adpoting async support quickly.

**Comment by jianghaolu** [comment]
Beta2 released.
