### ISSUE TITLE
azure-messaging-eventhubs:5.0.1 not found in Maven Repository

### ISSUE THREAD

**Issue by yaoyiyao** [Azure/azure-sdk-for-java#7434]
I tried to use the latest azure-sdk-for-java, but found there are several dependencies not found in maven repository. 
When searching in maven repo, the latest version of this is 5.0.0-beta.6, however, what I expect is 5.0.1.

**Comment by srnagar** [comment]
@yaoyiyao `azure-messaging-eventhubs` 5.0.1 is yet to be released to Maven. The latest version in Maven Central is 5.0.0-beta.6 as you rightly pointed out. Version 5.0.1 will be released soon and I'll update this issue when it's released.

**Comment by boybundit** [comment]
@srnagar Do you have estimated timeline for the release? According to the [release note](https://azure.github.io/azure-sdk/releases/2020-01/java.html), it should have been already released as part of January 2020 GA release.
