### ISSUE TITLE
[Event Hubs] Migration guide improvements

### ISSUE THREAD

**Issue by ramya-rao-a** [Azure/azure-sdk-for-java#7436]
The[ migration guide for Event Hubs](https://github.com/Azure/azure-sdk-for-java/blob/master/sdk/eventhubs/azure-messaging-eventhubs/migration-guide.md) can use the below improvements

- Update title to reflect the package names. We are doing this across all languages based on feedback from the doc review. One suggestion: is`Guide to migrate from old-pkg-name-here to new-pkg-name-here`
- In the introduction add a section describing why one should migrate from the older version to the newer one. Perhaps a link to the guidelines and general benefits.

**Comment by joshfree** [comment]
Moving to the April milestone as part of closing out old past due milestones
