### ISSUE TITLE
azure-keyvault doesnt work behind proxy version 0.9.3 

### ISSUE THREAD

**Issue by amarpandharpure** [Azure/azure-sdk-for-java#747]
I am trying to use azure key vault java client to encrypt & decrypt the data. From my office network which have proxy to connect to internet the calls to azure key vault erros with connection timeout.

I have tested from home network which doesn't have any proxy works fine.
The rest api also doesnt work behind the proxy.

When calling the encryptAsync i get
org.apache.http.conn.HttpHostConnectException:  Connect to mykeyvault.vault.azure.net:443 [mykeyvault.vault.azure.net/137.116.120.244] failed: Connection timed out: connect

Though the .net version of keyvault client works fine behind proxy.

Thanks
Amar.

**Comment by martinsawicki** [comment]
the KeyVault client library is not in this repo anymore, so if this is still an issue, it should go there:
https://github.com/azure/azure-keyvault-java
