### ISSUE TITLE
[FEATURE REQ]

### ISSUE THREAD

**Issue by ovidiu10** [Azure/azure-sdk-for-java#7477]
Hi

can we have a PublicIPPrefix include in main Java SDK 
I use beta package 

        <groupId>com.microsoft.azure.network.v2019_09_01</groupId>
        <artifactId>azure-mgmt-network</artifactId>
        <version>1.0.0-beta-1</version>

https://github.com/ovidiu10/Azure/blob/master/java/otprivatedns/src/main/java/ca/otmdft/sample/otpublicprefix.java 

thanks

**Comment by yaohaizh** [comment]
@ovidiu10, what's the meaning of main Java SDK here? You mean https://github.com/Azure/azure-libraries-for-java/ here?

**Comment by ovidiu10** [comment]
correct @yaohaizh

**Comment by yaohaizh** [comment]
Fixed on 1.31.

**Comment by ovidiu10** [comment]
thank you
