### ISSUE TITLE
Plug in the Java perf framework to central master

### ISSUE THREAD

**Issue by g2vinay** [Azure/azure-sdk-for-java#7496]
1. Wire the framework to master build (place it in sdk/core/azure-core-test-perf)
2. Fix checksyle issues
3. Fix spotbugs issues
3. Add javadocs to the framework,
4. Comply with track 2 java guidelines.

**Comment by alzimmermsft** [comment]
@g2vinay I believe this is include in the module list of `pom.client.xml`, would that be considered plugged into master?

**Comment by g2vinay** [comment]
@alzimmermsft , 
yes the changes have been merged.
This issue can be closed.
