### ISSUE TITLE
[QUERY] Get ETag & Last-Modified while using BlobInputStream

### ISSUE THREAD

**Issue by michalmela** [Azure/azure-sdk-for-java#7497]
**Query/Question**
In `azure-storage-blob` API, is there a concise way to download a file through a `BlobInputStream` while also getting the blob's ETag & Last-Modified header values?

To elaborate:
As the storage APIs are HTTP at heart, it makes sense to use integration patterns typical for HTTP clients in Java.

On one hand, it is convenient to have a properly buffered input stream to read the data from, like what we can get from `com.azure.storage.blob.specialized.BlobClientBase#openInputStream(com.azure.storage.blob.models.BlobRange, com.azure.storage.blob.models.BlobRequestConditions)`.

On the other, one may want to repeatedly store the blob's ETag and Last-Modified response header values to use them in the subsequent requests (in the `If-Modified-Since` and `If-None-Match` request headers), like what we can get from `com.azure.storage.blob.specialized.BlobClientBase#downloadWithResponse`.

However, I cannot see how a developer can make use of both of those features using a single API. Using a `BlobInputStream`, I can't see how I can access the response headers. Using `downloadWithResponse` I need to manage the stream buffering myself, by either building my own version of `BlobInputStream` or buffering in a huge array in-memory through `ByteArrayOutputStream` / `ByteArrayInputStream`. Additionally, this API throws a `com.azure.storage.blob.models.BlobStorageException` in the case of a `304 Not Modified` response.

***Why is this not a Bug or a feature Request?***
This may well become a feature request (perhaps not only for the blob storage but any other, and perhaps not only for the caching headers) but at this point for me it may just be my lack of knowledge of the API or my lack of understanding of an intentional Azure client design decision.

**Setup (please complete the following information if applicable):**
 - com.azure:azure.storage.blob:12.2.0
 
 **Information Checklist**
 Kindly make sure that you have added all the following information above and checkoff the required fields otherwise we will treat the issuer as an incomplete report
- [x] Query Added
- [x] Setup information Added

**Comment by gapra-msft** [comment]
Thanks @michalmela for your question. 

You're right in that there is no way to access the response headers using BlobInputStream. We could add that feature by providing an object on the BlobInputStreamthat holds the required headers and is available on close of the BlobInputStream. Would that satisfy your use case?

Also, it's a little unclear to me what you mean by 

> Additionally, this API throws a com.azure.storage.blob.models.BlobStorageException in the case of a 304 Not Modified response.

Is this just an issue with using `downloadWithResponse ` and buffering yourself?

**Comment by michalmela** [comment]
Thank you @gapra-msft ! Should I create a new "Feature Request" github issue or can this one be relabeled etc. to make it be considered as a feature request?

> We could add that feature by providing an object on the BlobInputStreamthat holds the required headers and is available on close of the BlobInputStream. Would that satisfy your use case?

Extending the `BlobInputStream` would indeed be great. Best, however, if it would be possible to read the headers before closing the stream, at least in my use case. They need to be read from the response before starting to read the response body (i.e. opening the input stream).

> Also, it's a little unclear to me what you mean by
> > Additionally, this API throws a com.azure.storage.blob.models.BlobStorageException in the case of a 304 Not Modified response.

I was not sure if it was worth mentioning but it was a bit surprising to discover that hitting the HTTP cache (receiving 304 Not Modified) was resulting in an exception. It wouldn't be uncommon or wrong to hit the cache more often than not, therefore not really an _exceptional_ case. So at the moment it made me wonder if I am using the right API in the right way for the particular use-case. But it may be a conscious design decision to use exceptions for the flow control, no problem.

> Is this just an issue with using downloadWithResponse and buffering yourself?

Basically, yes.

**Comment by gapra-msft** [comment]
@michalmela No need to add a feature request. 

Could you provide a sample of what you'd expect this surface to look like? I'm having a little trouble understanding your scenario.
