### ISSUE TITLE
[FEATURE REQ] Service Bus: IMessageAndSessionPump visibility

### ISSUE THREAD

**Issue by ryan-murphy-sc** [Azure/azure-sdk-for-java#7536]
**Is your feature request related to a problem? Please describe.**
I am writing common code for receiving from queues and topics. I create either QueueClient or SubscriptionClient. From there I use the `registerMessageHandler` method from the `IMessageAndSessionPump` interface. However, this interface is package private, so I cannot code to the interface and instead need to duplicate some logic and methods to take both class types.

**Describe the solution you'd like**
Would like IMessageAndSessionPump to be public.

**Describe alternatives you've considered**
-

**Additional context**
-

**Information Checklist**
- [x] Description Added
- [x] Expected solution specified

Thanks
Ryan

**Comment by joshfree** [comment]
Hi @ryan-murphy-sc - than you for feedback on the Service Bus SDK.  @hemanttanwar is working on the next major version of the Service Bus SDK and I've assigned the issue to him to follow up.

**Comment by ryan-murphy-sc** [comment]
Hi. Just following up on this so it doesn't get closed by a bot. I'd still really love to have this interface with public visibility in the current sdk version (not next major). I'd be happy to submit a PR if it sounds reasonable.

**Comment by nemakam** [comment]
@ryan-murphy-sc , we will add this to the backlog. Meanwhile, if you are blocked on this, please feel free to raise a PR with the change and we can take it forward from there.

@yvgopal , any thoughts?

**Comment by axisc** [comment]
Thanks for submitting the PR @ryan-murphy-sc. I'll close this issue for now and the fix will be published when the SDK version is updated.
