### ISSUE TITLE
[FEATURE REQ] Need expose buildUserAgent in UserAgentPolicy

### ISSUE THREAD

**Issue by ChenTanyi** [Azure/azure-sdk-for-java#7549]
**Is your feature request related to a problem? Please describe.**
In Fluent Java, we use a rest client for all package. Thus, we need to set different user agent in different request. https://github.com/Azure/azure-libraries-for-java/blob/vnext/azure-mgmt-resources/src/main/java/com/azure/management/UserAgentPolicy.java#L90
In order not to new a policy per request or pass the whole user agent parameter every time, we'd like to ask for expose the [buildUserAgent](https://github.com/Azure/azure-sdk-for-java/blob/master/sdk/core/azure-core/src/main/java/com/azure/core/http/policy/UserAgentPolicy.java#L137) function to protected or public.

**Describe the solution you'd like**
Solution as above.

**Describe alternatives you've considered**

**Additional context**

**Information Checklist**
Kindly make sure that you have added all the following information above and checkoff the required fields otherwise we will treat the issuer as an incomplete report
- [x] Description Added
- [x] Expected solution specified

**Comment by JonathanGiles** [comment]
Assigning to @alzimmermsft for review.

**Comment by srnagar** [comment]
Fixed in #12456
