### ISSUE TITLE
[FEATURE REQ] PollerFlux will always do the polling loop

### ISSUE THREAD

**Issue by yaohaizh** [Azure/azure-sdk-for-java#7570]
**Describe the bug**

For `PollerFlux`, the `activationOperation` will return `Mono<T>`, but not `Mono<PollResponse<T>>`. 

And in some ARM long-running operation cases, it will directly return 200 during the first REST calling. However, in currently implementation, the code will do the polling loop anyway which is delay with some default interval. We should support this scenario. 
```java
        this.oneTimeActivationMono
            .flatMapMany(ignored -> pollingLoop())
            .subscribe(actual);
```

**Comment by anuchandy** [comment]
@yaohaizh is the polling stage make a request over wire? or it apply delay and immediately return?

**Comment by anuchandy** [comment]
Ok, I think there is no extra REST call but delay is applied. ARM poller simply emits the last response (the LRO init response) without making a n/w call.

**Comment by anuchandy** [comment]
In PollerFlux, there is activation Function (a.k.a LRO init Function) and poll Function.

```java
Function<PollingContext<T>, Mono<T>> lroInitFunction
Function<PollingContext<T>, Mono<PollResponse<T>>> pollFunction
```

PollerFlux emits a stream of `PollResponse<T>`, which is created by:

```java
Mono<T> m1 = lroInitFunction();
PollResponse<T> r1 
    = new PollResponse(LongRunningOperationStatus.NOT_STARTED,  m1.get());
return r1 + Loop { Mono<PollResponse<T>> m2 =  pollFunction(); return m2.get(); }
```

PollerFlux is creating the first `PollResponse` with `LongRunningOperationStatus.NOT_STARTED`.

The case we encountered in ARM polling i.e. `lroInitFunction` init and completes the lro is something we should consider, unnecessary call to `pollFunction` should be avoid. 

As Yaohai pointed we can handle this if `lroInitFunction` has the same signature as `pollFunction`:

`Function<PollingContext<T>, Mono<PollResponse<T>>> lroInitFunction`. 

with this, we could skip the polling loop. Changing signature is breaking, so what’s your thoughts on adding a `PollerFlux::create` Factory method? (then update the ctr when we do mjaor version bump)

Any other better way to handling this use case?

@JonathanGiles @srnagar @hemanttanwar thoughts?

**Comment by hemanttanwar** [comment]
Just for documentation what we spoke at our desk.
Option 3 : activationOperation.apply() Returns  Mono<PollResponse<T>> instead of Mono<T>
                 Con : since we do not want to break current interface. The drawback would be inconvenience to user Since We would wrap this into another PollResponse<> .  Also this is a problem for .map() API

So Option 1,  factory method is becoming current candidate to implement.

**Comment by yaohaizh** [comment]
Prefer the option 1 since it will keep the user code easy to migrate if we want to make breaking changes in major release.

**Comment by anuchandy** [comment]
thanks all for the input. PR with option-1: https://github.com/Azure/azure-sdk-for-java/pull/7599

**Comment by anuchandy** [comment]
PR with this feature is merged, hence closing.
