### ISSUE TITLE
azure-storage-blob-nio has no module reference in sdk/storage/pom.service.xml and is also missing it's artifact entry in sdk/storage/ci.yml

### ISSUE THREAD

**Issue by JimSuplizio** [Azure/azure-sdk-for-java#7580]
The module reference missing from the pom.service.xml file means that this module isn't being scanned for checkstyle or javadoc as part of the storage pipeline build. Because there is a module reference in pom.client.xml it is getting scanned as part of the core pipeline build and there are [errors causing core to fail](https://dev.azure.com/azure-sdk/internal/_build/results?buildId=239700&view=logs&j=b70e5e73-bbb6-5567-0939-8415943fadb9&t=b5f103f3-7317-514c-e60c-6e19642365f6) due to recent additions to the NIO library.

My recommendation is to get a PR submitted that comments out the NIO module first, so people's PRs don't fail and then add it back as part of the fix for this issue.

**Comment by rickle-msft** [comment]
I believe this was fixed a while ago.
