### ISSUE TITLE
No rollback support if incremental deployment fails.

### ISSUE THREAD

**Issue by amitarali** [Azure/azure-sdk-for-java#759]
We have a usecase where if an incremental deployment fails then that deployment should be rolled-back to take the resource group to old state.

The ARM java SDK has delete deployment API which will delete the specified deployment but it will not really rollback the deployment i.e. the resources added or modified by the recent deployment remain in Resource Group.

What is the way to achieve this use case with ARM SDK?

**Comment by amitarali** [comment]
Any idea on this?

**Comment by jianghaolu** [comment]
Deployment rollback is currently not supported. Deleting the deployment only removes the “template deployment history” record. If you want to clean up the resources, you will have to delete the resource group.

**Comment by amitarali** [comment]
Thanks jianghaolu for the response.

But deleting resourcegroup will delete all the resources provisioned in deployment 1 and deployment 2. My requirement is to just rollback or delete the resources created as part of deployment 2 and keep resources intact of deployment 1.

**Comment by amitarali** [comment]
is this something we can achieve with tags etc?

**Comment by martinsawicki** [comment]
an approach to recovering from a partly failed provisioning process can be followed based on this test in the latest Azure Management LIbraries for Java: https://github.com/Azure/azure-sdk-for-java/blob/master/azure-mgmt-compute/src/test/java/com/microsoft/azure/management/compute/VirtualMachineRelatedResourcesDeletionTests.java
