### ISSUE TITLE
Move dependency reports to aggregate-reporting pipeline

### ISSUE THREAD

**Issue by mitchdenny** [Azure/azure-sdk-for-java#7592]
Currently we apply a tag to pipeline runs which is then picked up by a release pipeline to publish dependency reports. With the move to push aggregate reporting operations onto a separate pipeline we will need to replumb this dependency reporting mechanism to work off the ```java - aggregate-reports``` pipeline.

**Comment by mitchdenny** [comment]
This work has now been performed, however I am worried that I haven't closed the loop on something. What is the process that takes the report outputs from the pipeline artifact and uploads them to Azure storage where we browse the reports from.

@weshaggard @bsiegel @JonathanGiles

**Comment by weshaggard** [comment]
That happens in a release pipeline. Have a look at https://dev.azure.com/azure-sdk/internal/_release?view=all&_a=releases&definitionId=20. We need to move that to the aggregate pipeline now. We should also remove the scheduled build tags which were used to trigger those release pipelines.

**Comment by mitchdenny** [comment]
Moved, and updated the pipeline.

**Comment by weshaggard** [comment]
FYI: I renamed the pipeline to match the new input pipeline.

Looks like the pipeline is missing artifacts so it is failing. 

Also shouldn't the plan be to remove that release pipeline and add it as part of the unified-pipeline that we included for the aggregate?

**Comment by mitchdenny** [comment]
Good point, we don't need a separate release pipeline anymore. I'll take a look.

**Comment by mitchdenny** [comment]
Pipeline is up and running again (still using the release pipeline to publish). Consolidating into a single pipeline is the next step.

**Comment by weshaggard** [comment]
> Consolidating into a single pipeline is the next step. 

is there another issues for that or did you do that work already? @chidozieononiwu was trying to do something similar for .NET and I wanted to try and be as consistent as possible.

**Comment by mitchdenny** [comment]
Misdragged as I was triaging my board.

**Comment by mitchdenny** [comment]
Still need to add those steps to get rid of the release pipeline. We are still at status quo.

**Comment by mitchdenny** [comment]
I don't think this is an issue anymore?
