### ISSUE TITLE
[BUG] Distributed tracing: EventHubs send span is sent per try (should be one per user call)

### ISSUE THREAD

**Issue by lmolkova** [Azure/azure-sdk-for-java#7597]
**Describe the bug**
EventHubs  "send" span [is created per each try](https://github.com/Azure/azure-sdk-for-java/blob/master/sdk/eventhubs/azure-messaging-eventhubs/src/main/java/com/azure/messaging/eventhubs/EventHubProducerAsyncClient.java#L425). 

***Exception or Stack Trace***
N/A

**To Reproduce**
Configure tracing and use EventHub. When Send call is retried, two spans are created.

***Code Snippet***
N/A

**Expected behavior**
However it is a convenience layer span. One span should correspond to one public API call and wrap all retried done under it (we use this approach for e.g. storage). If we'll ever decide to instrument AMQP level, we can start tracing retries with child spans.

Python, .NET, and JS instrument public API call (not each try).

**Screenshots**

**Setup (please complete the following information):**
 - OS: any
 - IDE : any
 - Version of the Library used: azure-messaging-eventhubs 5.0.1

**Additional context**

**Information Checklist**
Kindly make sure that you have added all the following information above and checkoff the required fields otherwise we will treat the issuer as an incomplete report
- [x] Bug Description Added
- [ ] Repro Steps Added
- [x] Setup information Added

**Comment by joshfree** [comment]
setting milestone to February
