### ISSUE TITLE
rename .list(resourceGroup) as .listByGroup(resourceGroup)

### ISSUE THREAD

**Issue by martinsawicki** [Azure/azure-sdk-for-java#760]
recent discussion with the language leads confirmed the expectation that method overloads are expected to have the same semantics, and if the semantics are different then a different name should be used.

In this case, we use `.list()` to list all resources under all resource groups. 
Since that returns output that is different from `.list(String resourceGroupName)`, the latter should be named differently: `.listByGroup()`  (or perhaps `.listByResourceGroup()`, though I'm not a fan of the longer naming..).
This will also then be consistent with other uses of `listBy*`, e.g. `.listByLocation(...)`, etc.

The case where using the same name is justified is when the method overloads all result in the same output, they just take the arguments in different formats. For example, this usage is correct:
* `.listByGroup(String resourceGroupName)`
* `.listByGroup(ResourceGroup resourceGroup)`

**Comment by jianghaolu** [comment]
Is "Group" ever a marketed name? We might have to use resource group as it's the official name.

**Comment by martinsawicki** [comment]
i guess, but I'm just trying to keep it short where I can, thinking this is not a marketing pamphlet - the goal is to make it easier to type. Note the new CLI is going down the path of "az" and "network", not the marketing names either... I'm inclined to think usability trumps marketing in such scenario, so I've been trying to push the envelope on these. On the other hand, I know there is the potential consfusion with NSGs. So i'm kinda torn on this one,..

**Comment by jianghaolu** [comment]
`az` is code name btw

**Comment by martinsawicki** [comment]
from what I can tell, az will stick - I saw the big boss pretty much ok'ing it the other day at the demo review...
