### ISSUE TITLE
Model DataDisk as child resource of VirtualMachine

### ISSUE THREAD

**Issue by martinsawicki** [Azure/azure-sdk-for-java#763]
- including the defineDataDisk flow impl
- .dataDisks() collection on VM
- and shortcut .withDataDisk(size)

(see Subnet as an example)

**Comment by anuchandy** [comment]
Addressed this in the PR - https://github.com/Azure/azure-sdk-for-java/pull/761

**Comment by jianghaolu** [comment]
Beta2 released.
