### ISSUE TITLE
Move dependencies.json and jetty.xml from Root of the Repository

### ISSUE THREAD

**Issue by alzimmermsft** [Azure/azure-sdk-for-java#7634]
Move `dependencies.json` and `jetty.xml` from the root of the repository into another location, such as underneath `eng` which is a more appropriate location.

**Comment by alzimmermsft** [comment]
@mitchdenny I'm handing this off to you as it appears you have a PR resolving this and will be looking into this more for the POM restructuring.

**Comment by mitchdenny** [comment]
Sounds good. I think that there is only a small number of libraries that require this jetty configuration. My plan is to duplicate this confirmation in each of the modules so that its isolated. No point polluting the parent POM with this.
