### ISSUE TITLE
NetworkInterface#isPrimary() should instead be properly modeled as VirtualMachine#primaryNetworkInterface()

### ISSUE THREAD

**Issue by martinsawicki** [Azure/azure-sdk-for-java#764]
and Define can still be as implemented:
.withExistingPrimaryNetworkInterface()/.withNew*

**Comment by anuchandy** [comment]
implemented https://github.com/Azure/azure-sdk-for-java/blob/21a30a8ceae90439e9b4a44d4aedb7ff6cefb34c/azure-mgmt-compute/src/main/java/com/microsoft/azure/management/compute/VirtualMachine.java#L181

**Comment by martinsawicki** [comment]
great! just off the top of my head, I recall we had a similar situation on IPconfigs in the auto-gen'd SDK -- how the "isprimary" flag lives on the ipconfig instead of the NIC where it really belongs (as NIC.primaryIpConfiguration). You know what I mean?  Are we good there already?
