### ISSUE TITLE
[BUG] Async v12 uploadFromFile method failed to call subscribe()  on completion of file upload.

### ISSUE THREAD

**Issue by VIJAY-SUBRAMANIAM** [Azure/azure-sdk-for-java#7649]
API failed to call subscribe() method on completion of file upload. I tested with a very small text file with one word. File successfully uploaded to Azure storage, but completion message not printed.
subscribe() is an asynchronous call, So added blocking calls like Thread.sleep() or System.in.Read() to keep the application alive until the operation completes.

blobAsyncClient.uploadFromFile(sampleFile.toPath().toString(), true)
.doOnError(throwable -> System.err.printf("Failed to upload from file %s%n", throwable.getMessage()))
.subscribe(success -> System.out.printf("Upload file succeeded"));

System.in.read()

version v12 (12.3.0) and Java 11 Corretto

Has anyone noticed a similar issue?

Thanks,
Vijay--

**Comment by JonathanGiles** [comment]
Your observation is correct - your application will exit before the callback is called, because it is an async method call. You will need to block appropriately to prevent this, if necessary.
