### ISSUE TITLE
How to deal with collections of references to top level resources, for example AvailabilitySet#virtualMachines()

### ISSUE THREAD

**Issue by martinsawicki** [Azure/azure-sdk-for-java#765]
perhaps we could enhance the .refresh() logic which i think we already get for free on all the wrappers -- so that we could create an empty wrapper with just the resource ID, and then call refresh before returning it to the caller --- instead of the more complex Loader impl.

**Comment by martinsawicki** [comment]
per discussion, for now, we'll just return ids of the references as strings, appropriately named, for example: NIC.subnetId(), etc.

**Comment by jianghaolu** [comment]
Beta2 released.

**Comment by martinsawicki** [comment]
reopening for the next release as we may need a better story than listiing ids.

**Comment by martinsawicki** [comment]
the pattern we're converging on is:
Set<String> AvailabilitySet#virtualMachineIds()
List<VirtualMachine> getVirtualMachines()
