### ISSUE TITLE
[BUG] azure-storage-queue 12.3.0 was not released alongside all other azure-storage-* libs.

### ISSUE THREAD

**Issue by nadav-lavy-exa** [Azure/azure-sdk-for-java#7659]
**Describe the bug**
The release of maven package azure-storage-queue 12.3.0 did not follow the other azure-storage-* packages.
https://mvnrepository.com/artifact/com.azure/azure-storage-queue should have 12.3.0.

So as a user of all these packages there is now inconsistency and I cannot use the latest 12.3.0 for the others

***Exception or Stack Trace***
no.

**To Reproduce**
nothing. devops issue

***Code Snippet***
no.

**Expected behavior**
azure-storage-queue 12.3.0 should be available in maven
https://mvnrepository.com/artifact/com.azure/azure-storage-queue

**Screenshots**
no

**Setup (please complete the following information):**
 - IDE : [e.g. IntelliJ]
 - Version of the Library used

**Additional context**

**Information Checklist**
Kindly make sure that you have added all the following information above and checkoff the required fields otherwise we will treat the issuer as an incomplete report
- [V] Bug Description Added
- [V] Repro Steps Added
- [V] Setup information Added

**Comment by gapra-msft** [comment]
Hi @nadav-lavy-exa 

azure-storage-queue 12.3.0 was intentionally not released since there were no additions made to the library since 12.2.0

Could you elaborate on how this is a problem? Are the common parent dependencies (ex: azure-storage-common) being pulled incorrectly?

**Comment by nadav-lavy-exa** [comment]
When we use a library that have multiple packages, it usually keeps alignment of all their versions on each release, so users of these packages don't need to figure out the support/dependency matrix of each version. 
for example, at some point a change to azure-storage-commons will be made such that the other packages would have to have a certain version of their own to work with it.
this aligns with the dependency manager's use, in our case maven, as we define one property, azure-storage-version, set it to something, 12.3.0, and all its packages use this variable.
makes sense?

**Comment by gapra-msft** [comment]
@nadav-lavy-exa 

As you can see [here](https://github.com/Azure/azure-sdk/blob/master/docs/policies/releases.md#package-versioning), we make every effort possible to follow the [SemVer](https://semver.org/) guidelines for versioning. Unfortunately, this means that we only tick up the minor version if we add new APIs or features to the library. 

As a solution, I would recommend you specify versions per library. I apologize for any inconvenience.

**Comment by nadav-lavy-exa** [comment]
perhaps an example would help me explain why I think this strategy can cause a confusion to users - 

suppose you now make a change to both commons and queue, and new queue depends on this new commons,
you'd now release common 12.4.0 and queue 12.3.0.
now a new user comes along and wants to use the queue and storage.
they'd need to know not use commons 12.3.0 and queue 12.3.0. this is confusing.
now add the same for storage, say who'd advanced to 12.5.0 by now, and users might not have any idea what commons version should match which queue/storage.

just my two cents.
for me personally, I will now not upgrade to 12.3.0 just so I keep my dependencies aligned at 12.2.0.

in any case - the you for your prompt responses!

**Comment by amishra-dev** [comment]
Hi @nadav-lavy-exa, 
Thanks for trying out our latest SDK. Thanks for your valuable feedback. I will take your feedback back to the team and look at process improvements for this. 
Do let us know if you have any thing else to share about the SDK (API shape, developer experience et al). 

Thanks

**Comment by JonathanGiles** [comment]
Very shortly we will be releasing a BOM for our Azure client libraries for Java. At this point, managing the versioning of each dependency will no longer be required, as users will instead be encouraged to use the BOM to manage all dependencies. This will help to alleviate your concerns around manually managing dependencies. You can follow this issue at #7280.
