### ISSUE TITLE
.provisioningState() should perhaps be exposed on a base interface instead

### ISSUE THREAD

**Issue by martinsawicki** [Azure/azure-sdk-for-java#767]
and since different resources return different enums, we'll need to see if we can use it as a generic param to that base interface

**Comment by jianghaolu** [comment]
Beta2 released. Did we do this?

**Comment by martinsawicki** [comment]
no, we'll need to figure this out next

**Comment by anuchandy** [comment]
Ref: https://github.com/Azure/azure-sdk-for-java/issues/1036#issuecomment-334615048

**Comment by praries880** [comment]
@anuchandy is this issue fixed now?

**Comment by Petermarcu** [comment]
@anuchandy @jianghaolu do you know if this got completed? I see it was picked up in a milestone back in Jan?
