### ISSUE TITLE
[SBTrack 2] Prototype Public API for Sender Queue Client 

### ISSUE THREAD

**Issue by hemanttanwar** [Azure/azure-sdk-for-java#7697]
Design public API for SenderQueueClient for  Febuary 2020 Milestone.

Febuary 2020 Milestone Objective: 

1. Sender client (everything below is already implemented in EventHubProducerClient) 
  A. constructor overloads  
  B. connection string, queue/topic name, options 
  C. namespace, queue/topic name, credential, options 
  D. Options to constructors to support everything from EH like retry policy, web sockets, proxy etc. 
        Readonly properties  
        Fully qualified namespace 
        EntityName 
    **Methods** 
          Create a batch of messages (mimic the EventData from Event Hubs for now) 
          Send the batch 

More on `Febuary 2020 Milestone Objective` :  https://microsoft.sharepoint.com/:o:/t/AzureDeveloperExperience/Eh6vsEGjjYhNspabYWw-e2sBYvmt-LPd7T2nRWf1C34xJQ?e=HY5kCX

**Comment by conniey** [comment]
Fixed as part of #4506
