### ISSUE TITLE
What to name for long running methods?

### ISSUE THREAD

**Issue by jianghaolu** [Azure/azure-sdk-for-java#772]
Today, a long running create method has 4 variants:

- **create()** synchronously create a resource and wait until it's fully provisioned
- **beginCreate()** synchronously create a resource but does not wait until it's provisioned
- **createAsync(callback)** asynchronously create a resource and callback is called when the resource is fully provisioned
- **beginCreateAsync(callback)** asynchronously create a resource and callback is called when the resource creation request is submitted but not yet fully provisioned

We need better naming for these 4 methods. Or possibly eliminate one.

**Comment by pomortaz** [comment]
I think in the Java community, naming methods with callback as *Async is not common.
It is perhaps replicated from C# naming style, which may not suite Java.
I would vote for create() and create(callback).

**Comment by martinsawicki** [comment]
for non-blocking calls, I like beginCreate style of API for two reasons:
a) no multithreading needed (no callbacks, no thread waits, etc)
b) you can get a bunch of these kicked off in one place, then do some client-side logic, then check back on these in the same thread using the operation ID when needed. 
So it still has the perf and interactivity advantages of parallelism, but the parallelism is only implemented on the server side. Clientside can be all synchronous and thus easier to deal with.
(Note some modern languages: Node.js in particular (and arguably PowerShell) are single threaded. This makes server-side usage of the API easier too.)

**Comment by jianghaolu** [comment]
No action to take.
