### ISSUE TITLE
[BUG] Storage Blob downloadToFile response reports wrong blob size

### ISSUE THREAD

**Issue by ryan-murphy-sc** [Azure/azure-sdk-for-java#7766]
**Describe the bug**
I am using BlobAsyncClient downloadToFile. In the response handler which receives BlobProperties, blobProperties.getBlobSize() returns the content length of the first range, rather than the full blob size.

***Exception or Stack Trace***
N/A

**To Reproduce**
Upload a file greater than 4MB and use downloadFile. Check blob size on the returned blob properties. 

***Code Snippet***
https://github.com/ryan-murphy-sc/azure-blob-storage-download-test

**Expected behavior**
BlobProperties.getBlobSize() returns the total blob size.

**Screenshots**
-

**Setup (please complete the following information):**
 - OS: macOS (but probably any)
 - IDE : IntelliJ (but probably any)
 - azure-storage-blob 12.3.0

**Additional context**
- getProperties() returns the correct size. 
- The `Content-Range` header includes the correct size.

```
DEBUG reactor.netty.http.client.HttpClientOperations - [id: 0xa948bc9f, L:/10.3.3.26:52777 - R:***.blob.core.windows.net/52.239.189.4:443] Received response (auto-read:false) : [Content-Length=4194304, Content-Type=application/octet-stream, Content-Range=bytes 0-4194303/9226119, Last-Modified=Tue, 28 Jan 2020 14:59:45 GMT, Accept-Ranges=bytes, ....]
```

**Information Checklist**
Kindly make sure that you have added all the following information above and checkoff the required fields otherwise we will treat the issuer as an incomplete report
- [x] Bug Description Added
- [x] Repro Steps Added
- [x] Setup information Added

**Comment by gapra-msft** [comment]
Hi @ryan-murphy-sc 

As per the [REST Spec](https://docs.microsoft.com/en-us/rest/api/storageservices/get-blob), it looks like download does not return the length of the length of the blob, and instead returns the length of the body requested, so we are unable to return the blob size.

However, you're right that populating the blob size property does seem a little misleading. Thank you for bringing this to our attention. We will schedule some time to figure out a fix for this so we can present the data in a less ambiguous way.

**Comment by rickle-msft** [comment]
@ryan-murphy-sc An extra thought to hopefully ensure you're not blocked in the meantime: You can access the size of the blob either as a property on the file once it's downloaded, or through the content-range header, which on partial downloads is of the format "start-end/totalSize". (See the [REST API](https://docs.microsoft.com/en-us/rest/api/storageservices/get-blob) for more details).

**Comment by ryan-murphy-sc** [comment]
Thanks @gapra-msft and @rickle-msft . I took the approach of reading the size of the file once it's downloaded, so I'm not blocked by this.

**Comment by rickle-msft** [comment]
It should be a one line change. When we build the blobProperties, instead of just passing content-length, we should check if content-range is null. If not, we can just call extractBlobLength on it (already written). If it is null, pass content length because that means we downloaded the whole blob.
