### ISSUE TITLE
[Live-Test] Listing tests has issue relate to reactor-netty. 

### ISSUE THREAD

**Issue by mssfang** [Azure/azure-sdk-for-java#7771]
Open-source library react-netty has an issue on the aggregate response from the different chunk.

Disabled tests list:

- listRevisionsWithPagination()
- listRevisionsWithPaginationAndRepeatStream()
- listRevisionsWithPaginationAndRepeatIterator()
- listConfigurationSettingsWithPagination()

**Comment by joshfree** [comment]
/@anuchandy @mssfang can you please link to the issue on react-netty

**Comment by joshfree** [comment]
Adding `tracking-external-issue`.  Let's use this bug to track updating our dependency and then reenabling these tests.

**Comment by anuchandy** [comment]
Opened a PR with fix: https://github.com/Azure/azure-sdk-for-java/pull/7837

**Comment by anuchandy** [comment]
@joshfree just to share the result of investigation - we thought this was a reactor::aggregate issue initially but turned out to a problem in azure-core. Removing "tracking-external-issue" tag and adding "azure.core".

**Comment by anuchandy** [comment]
PR #7837 with fix is merged.
