### ISSUE TITLE
Include live tests in JaCoCo code coverage aggregate report

### ISSUE THREAD

**Issue by srnagar** [Azure/azure-sdk-for-java#7800]
JaCoCo aggregate code coverage report only runs tests that can be run in PLAYBACK mode. However, there are several tests that run only in LIVE mode and we don't get coverage report for this. 

Enable running LIVE tests to generate the aggregate code coverage report which includes all tests.

**Comment by mitchdenny** [comment]
After a quick chat with @srnagar I realized that this will require a bit more template surgery if we want to avoid a whole bunch of copy paste between templates. If we are going to do that then there are a few other template tidy up things that I'd like to do at the same time so I said I would take this one.

**Comment by JonathanGiles** [comment]
Thanks @mitchdenny. Do you have a rough timeframe in mind for this?

**Comment by mitchdenny** [comment]
I don't yet. I need to take a closer look at how the live tests are structured before I can give a reasonable estimate on timelines. I'll aim to give you some idea early next week on time-frames.

**Comment by mitchdenny** [comment]
After some thinking about this yesterday I've decided to first get code coverage publishing per unified pipeline. This will give us the overview on a per pipeline basis. The goal is to get this for the aggregate all up as well, but this would be a good first step.

**Comment by JonathanGiles** [comment]
Is there any update on this? Really keen to get live tests included in our coverage report. Thanks!

**Comment by weshaggard** [comment]
@mitchdenny has there been any movement to get the coverage reports in the unified pipelines?

**Comment by mitchdenny** [comment]
Once we get the POM restructuring merged we can come back to this.

**Comment by mitchdenny** [comment]
This is being addressed in this PR #10220
