### ISSUE TITLE
[BUG] Cosmos Direct TCP | An excessive number of request timeouts occur when netty-tcnative is in use

### ISSUE THREAD

**Issue by David-Noble-at-work** [Azure/azure-sdk-for-java#7829]
When netty-tcnative is in use we sometimes see a large number of request timeouts and this degrades performance by around 50% with the default timeout interval: 65 seconds.

**Comment by moderakh** [comment]
azure-core 1.2 has dependency on tcnative:
https://mvnrepository.com/artifact/com.azure/azure-core/1.2.0

**Comment by xinlian12** [comment]
Code merged.
