### ISSUE TITLE
Service Bus: AcceptSession from entity 'AF424C24' will be retried after 'PT1M'.

### ISSUE THREAD

**Issue by axhwk** [Azure/azure-sdk-for-java#7841]
I have an issue when using Service Bus with a session enabled queue. When there is no message / session on the queue the receiver (QueueClient) times out after around one minute and then waits for one minute before a retry happens. This introduces a delay in the message delivery.

I see the following log message occur:
MessageAndSessionPump ? : AcceptSession from entity 'AF424C24' will be retried after 'PT1M'.
This occurs in: com.microsoft.azure.servicebus.MessageAndSessionPump#acceptSessionAndPumpMessages

**Expected Behavior**
from my point of view is that the receiver would without one minute delay wait for new incoming messages again. 

By looking in the code i think that the timeout is not properly handled, if no session is available nothing should be done, but it actually triggers the second block for the OperationCancelledException which introduces the delay.
```
                    // Timeout exception means no session available.. it is expected so no need to notify client
                    if (!(acceptSessionEx instanceof TimeoutException)) {
                        TRACE_LOGGER.info("Accepting a session from entity '{}' failed.", this.entityPath, acceptSessionEx);
                        this.notifyExceptionToSessionHandler(acceptSessionEx, ExceptionPhase.ACCEPTSESSION);
                    }
                    if (!(acceptSessionEx instanceof OperationCancelledException)) {
                        // don't retry if OperationCancelled by service.. may be entity itself is deleted
                        // In case of any other exception, sleep and retry
                        TRACE_LOGGER.debug("AcceptSession from entity '{}' will be retried after '{}'.", this.entityPath, SLEEP_DURATION_ON_ACCEPT_SESSION_EXCEPTION);
                        Timer.schedule(() -> {
                            MessageAndSessionPump.this.acceptSessionAndPumpMessages();
                        }, SLEEP_DURATION_ON_ACCEPT_SESSION_EXCEPTION, TimerType.OneTimeRun);
                    }
```
Im using java 11 with sdk 3.1.4, but it occured also on 2.0.0

**Comment by joshfree** [comment]
Thanks for reporting this issue @axhwk.  @yvgopal, @hemanttanwar can you please take a look?

**Comment by yvgopal** [comment]
It is the same issue reported at https://github.com/Azure/azure-service-bus-java/issues/394
I have already responded to the issue and kept it on hold. Please check my comments there and respond to that issue. I am closing this as duplicate.
