### ISSUE TITLE
Unable to get started

### ISSUE THREAD

**Issue by lvh** [Azure/azure-sdk-for-java#786]
The README specifies Sonatype Snapshots repo, but doesn't specify the group id or artifact id to use. I tried to find them myself, but [the repo doesn't contain any relevant artifacts][sonatype-snapshots].

The [Getting Started wiki document][wiki-gs] provides a different set of snapshots, e.g.: [snapshots][snapshots], however, the recommended URL is over HTTP and there doesn't appear to be a different trust rooting/code signing mechanism in place. These appear to be snapshots of 1.0.0 around March 2016.

The [Overview wiki document][wiki-overview] provided a great overview of the difference between the different Azure artifacts. Fortunately, these artifacts appear to be available on Maven Central; like the above snapshot server, it appears to have 1.0.0-x versions, specifically 1.0.0-beta, released 02-Mar-2016. However, these ostensibly similar versions appear to provide drastically different APIs: for example, the [ARM usage section in the README][readme-arm] suggests that you can do:

```java
ResourceManagementClient client = new ResourceManagementClientImpl(
    new ApplicationTokenCredentials("client-id", "tenant-id", "secret", null) // see Authentication
);
```

... a ctor whose existence is confirmed by the [javadoc][rsrcmgmtctor]. The [Getting Started doc][wiki-gs] claims you can do:

```java
ComputeManagementClient client;

// Default environment, no credentials
client = new ComputeManagementClientImpl();
```

... again confirmed by the [javadoc][computemgmtctor]. Except neither of these ctors is available in 1.0.0-beta that got shipped to Maven Central! From that Javadoc (no direct link since I couldn't find a place that it was hosted):

-----
`ComputeManagementClientImpl(org.apache.http.impl.client.HttpClientBuilder httpBuilder, ExecutorService executorService)`
Initializes a new instance of the ComputeManagementClientImpl class.
`ComputeManagementClientImpl(org.apache.http.impl.client.HttpClientBuilder httpBuilder, ExecutorService executorService, SubscriptionCloudCredentials credentials)`
Initializes a new instance of the ComputeManagementClientImpl class.
`ComputeManagementClientImpl(org.apache.http.impl.client.HttpClientBuilder httpBuilder, ExecutorService executorService, SubscriptionCloudCredentials credentials, URI baseUri)`
Initializes a new instance of the ComputeManagementClientImpl class.
`ComputeManagementClientImpl(org.apache.http.impl.client.HttpClientBuilder httpBuilder, ExecutorService executorService, SubscriptionCloudCredentials credentials, URI baseUri, String apiVersion, int longRunningOperationInitialTimeout, int longRunningOperationRetryTimeout)`
Initializes a new instance of the ComputeManagementClientImpl class.

-----

Similarly, the `ResourceManagementClientImpl` has totally different ctors in that version.

Could you please clarify the distinction between these repos? Is the current Microsoft-recommended way to interact with Azure to download snapshots off of ADX? Are the versions on Maven Central not supposed to work? Is this wiki the official documentation for using these SDKs?

[sonatype-snapshots]: https://oss.sonatype.org/content/repositories/snapshots/com/microsoft/azure/
[wiki-gs]: https://github.com/Azure/azure-sdk-for-java/wiki/Getting-Started#installation
[snapshots]: http://adxsnapshots.azurewebsites.net
[wiki-overview]: https://github.com/Azure/azure-sdk-for-java/wiki/Azure-SDK-for-Java-Features
[readme-arm]: https://github.com/Azure/azure-sdk-for-java#azure-resource-manager-arm-usage
[rsrcmgmtctor]: https://azure.github.io/azure-sdk-for-java/com/microsoft/azure/management/resources/ResourceManagementClientImpl.html#constructor.detail
[computemgmtctor]: https://azure.github.io/azure-sdk-for-java/com/microsoft/azure/management/compute/ComputeManagementClientImpl.html#constructor.detail

**Comment by jianghaolu** [comment]
Hi @lvh,
Sorry for the confusions around the README and javadocs. We were busy developing for beta2 and there could be some mismatches from one place to another.
The good news is that we just shipped beta2. Please refer to the latest README for samples, how to download, etc. Thanks!

**Comment by jianghaolu** [comment]
Closing as no action to take. Beta2 should not require anything in snapshots.
