### ISSUE TITLE
[QUERY] How to resolve javax.net.ssl.SSLException: handshake timed out

### ISSUE THREAD

**Issue by rajadilipkolli** [Azure/azure-sdk-for-java#7900]
**Query/Question**
Receiving handshake time out Exception when using `azure-messaging-eventhubs-checkpointstore-blob` to checkpoint the eventHub. How to resolve this?

Code is integrated with Spring Boot version 2.1.11 and it is deployed in OpenShift 3.11
Below is the error
`{"timestamp":"2020-02-02T09:15:19,427+0000","project":"dummyservice","log_level":"WARN","thread":"reactor-http-epoll-2","class_name":"reactor.util.Loggers$Slf4JLogger","line_number":"299","message":"[id: 0xa0f8e1a6, L:/10.74.29.164:46426 - R:dummystorage.blob.core.windows.net/x.x.x.x:443] The connection observed an error","stack_trace":"javax.net.ssl.SSLException: handshake timed out\n\tat io.netty.handler.ssl.SslHandler$5.run(SslHandler.java:2011)\n\tat io.netty.util.concurrent.PromiseTask.runTask(PromiseTask.java:98)\n\tat io.netty.util.concurrent.ScheduledFutureTask.run(ScheduledFutureTask.java:150)\n\tat io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:163)\n\tat io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:510)\n","status":"","duration_millis":"","application_tier":"","action":"","trace_id":""}`

***Why is this not a Bug or a feature Request?***
I feel this is a Question because it is conveying as HandShake Exception instead of any other exception.

**Setup (please complete the following information if applicable):**
 - OpenShift : 3.11
 - Version of the Library used : 1.0.0-beta.4
 
 **Information Checklist**
 Kindly make sure that you have added all the following information above and checkoff the required fields otherwise we will treat the issuer as an incomplete report
- [ x] Query Added
- [ x] Setup information Added

**Comment by JonathanGiles** [comment]
Assigning to @srnagar and @conniey to investigate. Thanks for the report!

**Comment by srnagar** [comment]
@rajadilipkolli - could you please let us know how you are creating the container client? It would be great if you could provide a reproducible code sample for us to investigate further.

**Comment by rajadilipkolli** [comment]
We are using eph 3.0.2 and it is working as expected with the storage connection being made using sas, Now when I tried to connect using the latest 5.0.x we are receiving the above reported error. With the sample provided by Microsoft We face this issue. 

Note:: we are behind corporate proxy.

**Comment by conniey** [comment]
We rewrote Event Hubs using the new API guidelines. Subsequently, the approach used in 3.0.2 may not be the same approach to use when configuring the HTTP client.

In your BlobContainerClientBuilder, you may have to set the httpClient with a proxy for the requests to be passed through there.

https://github.com/Azure/azure-sdk-for-java/wiki/HTTP-clients#configuring-http-clients

**Comment by rajadilipkolli** [comment]
Hi @conniey , I have configured AsyncHttpClient, still facing the same issue.

**Comment by srnagar** [comment]
@rajadilipkolli Here's a sample for configuring your proxy:

```java
ProxyOptions proxyOptions = new ProxyOptions(ProxyOptions.Type.HTTP,
  new InetSocketAddress(HOST_NAME, PORT));

HttpClient httpClient = new NettyAsyncHttpClientBuilder()
  .setProxy(proxyOptions)
  .build();

ContainerAsyncClient containerAsyncClient = new ContainerClientBuilder()
  .endpoint(endpoint)
  .connectionString(STORAGE_CONNECTION_STRING)
  .containerName(CONTAINER_NAME)
  .httpClient(httpClient)
  .buildAsyncClient(); 
```

If you are still facing issues, it would be great if you could provide a code sample that can help us reproduce this error.

**Comment by srnagar** [comment]
@rajadilipkolli were you able to get this to work?

**Comment by srnagar** [comment]
Closing this issue as there is no update. Please feel free to reopen if you are still having an issue using proxy.
