### ISSUE TITLE
[FEATURE REQ] Netty Asnyc client EventLoop group does not need to be specific

### ISSUE THREAD

**Issue by Dav1dde** [Azure/azure-sdk-for-java#7910]
**Is your feature request related to a problem? Please describe.**

The `nioEventLoopGroup` method in `com.azure.core.http.netty.NettyAsyncHttpClientBuilder` does not have to be of type `io.netty.channel.nio.NioEventLoopGroup`, all that actually is required is the interface `io.netty.channel.EventLoopGroup`.

This creates a problem when trying to share event loop resources with e.g. an existing Netty Server running the application. E.g. Spring Webflux only exposes an `EventLoopGroup` interface.

**Describe the solution you'd like**
Only require the `EventLoopGroup` interface.

**Describe alternatives you've considered**
There are no alternatives.

**Additional context**
[Currently](https://github.com/Azure/azure-sdk-for-java/blob/master/sdk/core/azure-core-http-netty/src/main/java/com/azure/core/http/netty/NettyAsyncHttpClient.java#L102) the event loop group is only used for `tcpClient.runOn(eventLoopGroup)`, `tcpClient` already accepts a `EventLoopGroup`.

For comparison: [the AWS client](https://sdk.amazonaws.com/java/api/latest/software/amazon/awssdk/http/nio/netty/SdkEventLoopGroup.html#create-io.netty.channel.EventLoopGroup-io.netty.channel.ChannelFactory-)

**Information Checklist**
Kindly make sure that you have added all the following information above and checkoff the required fields otherwise we will treat the issuer as an incomplete report
- [X] Description Added
- [X] Expected solution specified

**Comment by JonathanGiles** [comment]
Thank you for using the Azure SDK for Java and leaving this feedback. I am asking @anuchandy, @alzimmermsft, and @g2vinay to take a closer look at this issue and get back to you.

**Comment by Dav1dde** [comment]
I don't mind fixing this myself in a PR, but there are actually a few things to consider or ways to implement it:

* just change `NioEventLoopGroup` to `EventLoopGroup`
* breaking change: rename `nioEventLoopGroup` to `eventLoopGroup`
* add a new method `eventLoopGroup` and deprecate `nioEventLoopGroup`

All valid options imo, let me know if I can help and what solution you prefer.

For all the people having my problem right now:

```java
        var loopResources = reactorClientResourceFactory.getLoopResources();
        var eventLoopGroup = loopResources.onClient(LoopResources.DEFAULT_NATIVE);

        var client = new NettyAsyncHttpClientBuilder()
            .connectionProvider(reactorClientResourceFactory.getConnectionProvider())
            // for some reason azure requires an NioEventLoopGroup here,
            // see -> https://github.com/Azure/azure-sdk-for-java/issues/7910
            // Could wrap it in a BullshitEventLoopGroup using Lombok's @Delegate ...
            // decided to go the reflection route below.
            // .nioEventLoopGroup(new BullshitEventLoopGroup(eventLoopGroup))
            .build();

        var f = ReflectionUtils.findField(client.getClass(), "nettyClient");
        Assert.notNull(f, "nettyClient field cannot be null");
        ReflectionUtils.makeAccessible(f);
        var nettyClient = (reactor.netty.http.client.HttpClient) ReflectionUtils.getField(f, client);
        Assert.notNull(nettyClient, "netty http client cannot be null");
        // existing settings may be lost here
        nettyClient = nettyClient.tcpConfiguration(c -> c.runOn(eventLoopGroup));
        ReflectionUtils.setField(f, client, nettyClient);
```

I found a few ways of handling it:

1) via Reflection and replacing the fully built client, this may lead to some issues where e.g. proxy settings get lost (not tested)
2) Using Lomboks `@Delegate` (or doing it by hand) and inheriting from `NioEventLoopGroup` and forwarding every method to another `EventLoopGroup`, which is probably a very bad idea... Could also use a proxy instead, but doesn't make it any better.
3) Force spring to create an `NioEventLoopGroup`, this relies on passing `false` to `onClient` and unwrapping the `EventLoopGroup` returned from it multiple times until you reach the actual `NioEventLoopGroup`. For me this relies too much on implementation details to do.

For now I went with 1) (unfortunately not the only reflection hack I have right now) until there is an upstream fix.

**Comment by JonathanGiles** [comment]
We will be taking your third approach - deprecate and introduce new builder. This was discussed last week by the Java team and will be introduced in the coming weeks.

**Comment by JonathanGiles** [comment]
btw - if you want to offer a PR please let us know and we will leave it to you!

**Comment by Dav1dde** [comment]
I would like to do it, but I have to figure out the CLA situation first, I am not sure if I am currently legally allowed to sign it, I think it's fine but I'd like to be sure.
