### ISSUE TITLE
[Azure-Core-Bugs]: HttpLoggingPolicyTests  failed when set AZURE_LOG_LEVEL=3 in test.yml file in AzConfig

### ISSUE THREAD

**Issue by mssfang** [Azure/azure-sdk-for-java#7919]
- HttpLoggingPolicyTests  failed when set AZURE_LOG_LEVEL=3 in test.yml file in AzConfig
- Failed pipeline for nightly live test: https://dev.azure.com/azure-sdk/internal/_build/results?buildId=249952&view=results

**Comment by sima-zhu** [comment]
This is expected, as the logging tests reads AZURE_LOG_LEVEL from system setting first then from test setup method.

**Comment by alzimmermsft** [comment]
@mssfang is this issue still on-going?

**Comment by mssfang** [comment]
By removed the AZURE_LOG_LEVEL=3 will resolve the failure. 

I noticed that before last Wednesday, AZURE_LOG_LEVEL=3 still is one reason to cause TA live tests to fail so I removed it. It is after I released TA beta 3, which using the latest Azure Core version 1.3.0. So I think the set AZURE_LOG_LEVEL = 3 will still cause problem.

**Comment by alzimmermsft** [comment]
Closing this issue as there was a fix to the `HttpLoggingPolicyTests` in PR #9194.
