### ISSUE TITLE
Maven distribution relocation for Track-2 GAs

### ISSUE THREAD

**Issue by joshfree** [Azure/azure-sdk-for-java#7968]
For each GA'd Track-2 project, setup a relocation notification for the move from (Track-1) `com.microsoft.azure` to `com.azure` (Track-2 / next major release)

example:
https://mvnrepository.com/artifact/org.codehaus.jackson/jackson-mrbean

![](https://user-images.githubusercontent.com/8507223/37667627-5834495a-2c5a-11e8-8ee1-4a277f9dbf4c.png)

cc: @JimSuplizio @JonathanGiles

**Comment by JonathanGiles** [comment]
Maven relocation guide: https://maven.apache.org/guides/mini/guide-relocation.html

**Comment by alzimmermsft** [comment]
This will require adding this configuration to the Track 1 POM files:

```xml
<distributionManagement>
  <relocation>
    <groupId>com.azure</groupId>
    <artifactId>{artifact}</artifactId>
    <message>{messaging}</message>
  </relocation>
</distributionManagement>
```

The messaging should be fairly consistent across the POM files, and it would be nice to be consistent across languages. .NET is using this format in Nuget:

```
This library has been replaced by the following new Azure SDKs. You can read about the new Azure SDKs at https://aka.ms/azsdkvalueprop.
The latest libraries to interact with the Azure <Service> service are:

_list of replacement packages_
```

@AlexGhiondea @joshfree
