### ISSUE TITLE
PublicIp: if none of the dns settings child properties are set then DNSSettings property must set to null

### ISSUE THREAD

**Issue by anuchandy** [Azure/azure-sdk-for-java#798]
We are initializing PublicIp::DNSSettings property to an empty instance, all the DNSSettings child properties are optional, if we don't set any of this optional parameter and try to PUT PIP payload with empty DNSSettngs object then server throws error. Server is expecting this property to be null in this case :(

**Comment by martinsawicki** [comment]
checked in: 
https://github.com/Azure/azure-sdk-for-java/pull/799/commits/89725a4672ec924cd3c95c08d771bbb586d2841c
