### ISSUE TITLE
Analyze dependencies task in the java - aggregate-reports is failing

### ISSUE THREAD

**Issue by JimSuplizio** [Azure/azure-sdk-for-java#7987]
The latest java - aggregate-reports pipeline builds are failing with the following error. Since the java - aggregate-reports pipeline is not run as part of any PR I'm going to recommend running the following command to verify changes.
**/azp run java - aggregate-reports**

[ERROR] Failed to execute goal org.apache.maven.plugins:maven-javadoc-plugin:2.9.1:jar (attach-javadocs) on project dependencyChecker-core: MavenReportException: Error while creating archive: 
[ERROR] Exit code: 1 - javadoc: error - The code being documented uses modules but the packages defined in http://docs.oracle.com/javase/7/docs/api/ are in the unnamed module.
[ERROR] /home/vsts/work/1/s/DependencyChecker/core/src/main/java/net/jonathangiles/tool/maven/dependencies/model/Dependency.java:74: warning: no @return
[ERROR]     public boolean isProblemDependency() {
[ERROR]                    ^
[ERROR] /home/vsts/work/1/s/DependencyChecker/core/src/main/java/net/jonathangiles/tool/maven/dependencies/report/Reporter.java:16: warning: no @return
[ERROR]     String getName();
[ERROR]            ^
[ERROR] /home/vsts/work/1/s/DependencyChecker/core/src/main/java/net/jonathangiles/tool/maven/dependencies/report/Reporter.java:22: warning: no @param for projects
[ERROR]     void report(List<Project> projects, List<Dependency> problems, Collection<DependencyManagement> dependencyManagement, File outDir, String outFileName);
[ERROR]          ^
[ERROR] /home/vsts/work/1/s/DependencyChecker/core/src/main/java/net/jonathangiles/tool/maven/dependencies/report/Reporter.java:22: warning: no @param for problems
[ERROR]     void report(List<Project> projects, List<Dependency> problems, Collection<DependencyManagement> dependencyManagement, File outDir, String outFileName);
[ERROR]          ^
[ERROR] /home/vsts/work/1/s/DependencyChecker/core/src/main/java/net/jonathangiles/tool/maven/dependencies/report/Reporter.java:22: warning: no @param for dependencyManagement
[ERROR]     void report(List<Project> projects, List<Dependency> problems, Collection<DependencyManagement> dependencyManagement, File outDir, String outFileName);
[ERROR]          ^
[ERROR] /home/vsts/work/1/s/DependencyChecker/core/src/main/java/net/jonathangiles/tool/maven/dependencies/report/Reporter.java:22: warning: no @param for outDir
[ERROR]     void report(List<Project> projects, List<Dependency> problems, Collection<DependencyManagement> dependencyManagement, File outDir, String outFileName);
[ERROR]          ^
[ERROR] /home/vsts/work/1/s/DependencyChecker/core/src/main/java/net/jonathangiles/tool/maven/dependencies/report/Reporter.java:22: warning: no @param for outFileName
[ERROR]     void report(List<Project> projects, List<Dependency> problems, Collection<DependencyManagement> dependencyManagement, File outDir, String outFileName);
[ERROR]          ^
[ERROR] 
[ERROR] Command line was: /usr/lib/jvm/zulu-11-azure-amd64/bin/javadoc @options @packages
[ERROR] 
[ERROR] Refer to the generated Javadoc files in '/home/vsts/work/1/s/DependencyChecker/core/target/apidocs' dir.
[ERROR] 
[ERROR] -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.

**Comment by JonathanGiles** [comment]
Fixed in #7962
