### ISSUE TITLE
Invalid First XML Character 0xEF

### ISSUE THREAD

**Issue by alzimmermsft** [Azure/azure-sdk-for-java#7990]
An invalid XML character 0xEF exception is being thrown from Blob Batch, the XML chunk that contains this character doesn't get parsed as XML at the point the exception is thrown. Find the root location what the XML is being parsed in Azure Core.

**Comment by danieljurek** [comment]
Smoke tests have also encountered this in Windows environments -- https://dev.azure.com/azure-sdk/internal/_build/results?buildId=271402&view=logs&j=9d5db22d-3d98-5076-6ada-6891876c8311&t=5f0ec4c1-b78a-58e4-2905-0008c2d0ba42&l=236

**Comment by alzimmermsft** [comment]
@anuchandy and @srnagar, based on this being found outside of the scope I found it in I am going to revive the associated PR that was closed and take a deeper dive into find the root issue.

**Comment by alzimmermsft** [comment]
Fixed by #8687
