### ISSUE TITLE
[BUG] `getBlobUrl` blob path is URL encoded

### ISSUE THREAD

**Issue by Dav1dde** [Azure/azure-sdk-for-java#8001]
**Describe the bug**

`BlobAsyncClientBase#getBlobUrl()` returns the URL URL-encoded

***Code Snippet***

```java
System.out.println(this.client.getBlobAsyncClient("test/bar/baz.jpg").getBlobUrl())
```

Gives:
```
https://account.blob.core.windows.net/container/test%2Fbar%2Fbaz.jpg
```

The path separators `/` can't be encoded otherwise the blob is not accessible.

**Expected behavior**

You get an URL that actually works and can be used to retrieve/manipulate the blob.

**Screenshots**

![image](https://user-images.githubusercontent.com/255721/73952023-c4de0880-48fe-11ea-8a44-432da5732391.png)

**Setup (please complete the following information):**
 - OS: Archlinux
 - IDE : IntelliJ
 - Version of the Library used: 12.3.0

**Information Checklist**
Kindly make sure that you have added all the following information above and checkoff the required fields otherwise we will treat the issuer as an incomplete report
- [X] Bug Description Added
- [X] Repro Steps Added
- [X] Setup information Added

**Comment by rickle-msft** [comment]
Hi, @Dav1dde. Can you please clarify what you mean when you say the blob is accessible. The service interprets %2F as '/', and I've confirmed that using a similarly formatted URL, I am able to retrieve a blob both through a browser and via the client. If there's another means of access you are using that is not working, I would be happy to explore that further.

**Comment by Dav1dde** [comment]
@rickle-msft see the code I linked in #7997 - you can even use the example to reproduce it.

Upload a file to an Azure blob container with a `/` in the name (basically upload it into a folder), then try to access it with:

```java
        return this.webClient.get()
            .uri(this.azureClient.getBlobAsyncClient(filename).getBlobUrl())
            .exchange()
            .flatMapMany(c -> c.body(BodyExtractors.toDataBuffers()))
            .map(DataBuffer::asByteBuffer);
```

It will 404, replacing the url with:

```java
        var url = UriComponentsBuilder.fromHttpUrl(this.client.getBlobContainerUrl())
            .path("/" + filename)
            .toUriString();
```

Succesfully downloads the file. Also can be reproduced easily with any browser, just open the URL returned by `this.azureClient.getBlobAsyncClient("test/foo/bar.jpg").getBlobUrl()` and it will 404, opening `this.client.getBlobContainerUrl() + "/test/foo/bar.jpg"` with your browser (or any client, curl, Java, w/e) works.

**Comment by Dav1dde** [comment]
@rickle-msft actually I am wrong, it does work in a browser, the problem is that the spring client url-encodes the already url-encoded string (as coming from Blob-Url).

Should I close that or is there any point in turning this into a feature request?

**Comment by Dav1dde** [comment]
I'll just close it, the returned URL works, it's a bit inconvenient but it works.
