### ISSUE TITLE
Can't invoke downloadPageRanges(long offset, Long length) 

### ISSUE THREAD

**Issue by hello-azure** [Azure/azure-sdk-for-java#801]
In java doc(http://azure.github.io/azure-sdk-for-java/), we can find the api definition:

**List<PageRange> downloadPageRanges(long offset, Long length) 
Returns a collection of page ranges and their starting and ending byte offsets.
 
List<PageRange> downloadPageRanges(long offset, Long length, AccessCondition accessCondition, BlobRequestOptions options, OperationContext opContext) 
Returns a collection of page ranges and their starting and ending byte offsets using the specified request options and operation context.** 

However, we can't find the api after import com.microsoft.azure.storage.blob.CloudPageBlob, we also test in other client environment, we only can use the following apis:

**ArrayList<PageRange> downloadPageRanges() 
Returns a collection of page ranges and their starting and ending byte offsets.
 
ArrayList<PageRange> downloadPageRanges(AccessCondition accessCondition, BlobRequestOptions options, OperationContext opContext) 
Returns a collection of page ranges and their starting and ending byte offsets using the specified request options and operation context.** 

Please help check, thanks.

**Comment by hello-azure** [comment]
Any update? Please confirm the issue, thanks.

**Comment by hello-azure** [comment]
Please confirm the issue, thanks.

**Comment by jianghaolu** [comment]
Which version of azure-storage are you using? I can see it here: https://github.com/Azure/azure-storage-java/blob/master/microsoft-azure-storage/src/com/microsoft/azure/storage/blob/CloudPageBlob.java#L461.

**Comment by jianghaolu** [comment]
Haven't heard from you. I assume you've found a way out :) Please reopen if not.
