### ISSUE TITLE
[BUG] Storage Library v8.3 does not remove padding when decrypting contents when downloading a blob with CloudBlockBlob.openInputStream()

### ISSUE THREAD

**Issue by andresc-snowflake** [Azure/azure-sdk-for-java#8012]
**Describe the bug**
In the storage library v8.3, downloading and decrypting a blob that was client-side encrypted with the storage library fails when using CloudBlockBlob.openInputStream(). This fails because it does not remove the padding added during the client-side encryption when decrypting the blob contents. This causes an IOException to be thrown since the MD5 integrity check fails. If the content MD5 validation is disabled, you can see the resulting byte array has the additional nul bytes from the padding added during encryption.
This bug is specific to downloads using CloudBlockBlob.openInputStream(). In the below code snippet I compare the behavior to that of CloudBlockBlob.download().

**To Reproduce**
Run the code snippet below to reproduce the behavior being described.

***Code Snippet***
```    String endpoint = "blob.core.windows.net";
    String storageAccount = "<your storage account>";
    String containerName = "<your container name>";
    String blobName = "<your blob name>";
    String sasToken =  "<your sas token>";
    
    // build client to talk to storage
    URI storageEndpoint = new URI(
        "https",
        storageAccount + "." + endpoint + "/",
        null,
        null);
    StorageCredentials azCreds = new StorageCredentialsSharedAccessSignature(sasToken);
    CloudBlobClient blobClient = new CloudBlobClient(storageEndpoint, azCreds);

    // get blob reference
    CloudBlobContainer container = blobClient.getContainerReference(containerName);
    CloudBlockBlob blockBlob = container.getBlockBlobReference(blobName);

    // set up upload with client side encryption
    BlobRequestOptions options = new BlobRequestOptions();
    SymmetricKey symmetricKey = new SymmetricKey();
    BlobEncryptionPolicy encPolicy = new BlobEncryptionPolicy(symmetricKey, null);
    options.setEncryptionPolicy(encPolicy);
    byte[] contents = "Hello World".getBytes();
    ByteArrayInputStream is = new ByteArrayInputStream(contents);

    // upload blob
    blockBlob.upload(is, contents.length, null, options, null);

    // download same blob two different ways
    // expect this to succeed
    ByteArrayOutputStream outputStream = new ByteArrayOutputStream();
    blockBlob.download(outputStream, null, options, null);
    byte[] downloadResult = outputStream.toByteArray();

    // expect this to fail with IOException with an integrity check error message
    byte[] openInputStreamResult = null;
    try {
      InputStream inputStream = blockBlob.openInputStream(null, options, null);
      openInputStreamResult = inputStream.readAllBytes();
    }
    catch (Exception ex)
    {
      System.out.println("Download failed with Ex: " + ex.toString());
    }

    // disable MD5 check to see downloaded contents
    options.setDisableContentMD5Validation(true);
    InputStream inputStream = blockBlob.openInputStream(null, options, null);
    openInputStreamResult = inputStream.readAllBytes();

    // downloaded contents should be equal, but aren't
    System.out.println("Contents equal: " + Arrays.equals(downloadResult, openInputStreamResult));
    System.out.println("downloadResult: " + new String(downloadResult));
    System.out.println("openInputStreamResult: " + new String(openInputStreamResult));
    System.out.println("downloadResult length: " + downloadResult.length);
    System.out.println("openInputStreamResult length: " + openInputStreamResult.length);
```

**Expected behavior**
I expect that the padding added by the client side encryption would be stripped during decryption as it is with CloudBlockBlob.download() and that no IOException would be thrown.

**Setup (please complete the following information):**
 - OS: CentOS7
 - IDE : IntelliJ
 - Version of the Library used: Storage library used is v8.3.0. Keyvault Library used is v1.0.0.

**Information Checklist**
Kindly make sure that you have added all the following information above and checkoff the required fields otherwise we will treat the issuer as an incomplete report
- [x] Bug Description Added
- [x] Repro Steps Added
- [x] Setup information Added

**Comment by amishra-dev** [comment]
@gapra-msft Gauri, can you please look at this at your earliest availability.

**Comment by rickle-msft** [comment]
@andresc-snowflake I've investigated this and have found what I believe to be the root cause. I'm checking with my team to see if there was an intentional reason for having the stream behavior operate this way before taking any further steps. I'll follow up here soon when I have more information.

**Comment by amishra-dev** [comment]
@rickle-msft bringing this back to the top of your inbox

**Comment by rickle-msft** [comment]
This issue was resolved and the fix released back in Feb
