### ISSUE TITLE
Avoid references to raw types in generics

### ISSUE THREAD

**Issue by martinsawicki** [Azure/azure-sdk-for-java#802]
We have a few places where we reference raw types when referring to generics. This is not a best practice. We get compiler warning from that too. It'd be great to:
a) add a checkstyle rule to disallow raw type references
b) refactor the offending code as appropriate

**Comment by jianghaolu** [comment]
Do you have an example?

**Comment by anuchandy** [comment]
@martinsawicki you mean below warning?
```
---
[WARNING] /VirtualMachineImpl.java:[523,25] defineNewDataDisk(java.lang.String) in com.microsoft.azure.management.compute.implementation.VirtualMachineImpl implements defineNewDataDisk(java.lang.String) in com.microsoft.azure.management.compute.VirtualMachine.Update

return type requires unchecked conversion from com.microsoft.azure.management.compute.implementation.DataDiskImpl to com.microsoft.azure.management.compute.DataDisk.DefinitionAttachNewDataDisk<com.microsoft.azure.management.compute.VirtualMachine.Update>

----

[WARNING] /VirtualMachineImpl.java:[523,25] defineNewDataDisk(java.lang.String) in com.microsoft.azure.management.compute.implementation.VirtualMachineImpl implements defineNewDataDisk(java.lang.String) in com.microsoft.azure.management.compute.VirtualMachine.DefinitionWithDataDisk

return type requires unchecked conversion from com.microsoft.azure.management.compute.implementation.DataDiskImpl to com.microsoft.azure.management.compute.DataDisk.DefinitionAttachNewDataDisk<com.microsoft.azure.management.compute.VirtualMachine.DefinitionCreatable>
----
```

**Comment by martinsawicki** [comment]
current violations include:
* `DataDiskImpl`
* `NicIpConfigurationImpl`
* `CreatableImpl`

**Comment by martinsawicki** [comment]
basically, if a type is generic (Foo<T>) then we should not reference it as Foo.

**Comment by martinsawicki** [comment]
GitHub markup got in the way:
basically, if a type is generic (&lt;Foo&gt;) then we should not reference it as Foo.

**Comment by martinsawicki** [comment]
crap, again:
basically, if a type is generic (Foo&lt;T&gt;) then we should not reference it as Foo.

**Comment by martinsawicki** [comment]
I have a way to deal with it, but need to play with it more

**Comment by jianghaolu** [comment]
@martinsawicki How did it go?

**Comment by martinsawicki** [comment]
it's a tracking issue - some issues were resolved, but more remains as we work on the APIs

**Comment by praries880** [comment]
@anuchandy Do you have more context on the issue? as to what remains to be done?

**Comment by joshfree** [comment]
@jianghaolu can you please track this with your management plane code generator work?

Also making sure this isn't lost:
> a) add a checkstyle rule to disallow raw type references

**Comment by jianghaolu** [comment]
Moved to https://github.com/Azure/autorest.java/issues/664
