### ISSUE TITLE
Component Vulnerabilties in Microsoft Azure SDK for Service Bus [BUG]

### ISSUE THREAD

**Issue by xaviersenac** [Azure/azure-sdk-for-java#8022]
**Describe the bug**

Azure Service Bus SDK for java contains a large number of dependencies with vulnerabilities : 

async-http-client-netty-utils-2.10.4.jar | cpe:2.3:a:asynchttpclient_project:async-http-client:2.10.4:*:*:*:*:*:*:*cpe:2.3:a:netty:netty:2.10.4:*:*:*:*:*:*:* | pkg:maven/org.asynchttpclient/async-http-client-netty-utils@2.10.4 | HIGH | 5 | Highest | 25
-- | -- | -- | -- | -- | -- | --
netty-transport-4.1.42.Final.jar | cpe:2.3:a:netty:netty:4.1.42:*:*:*:*:*:*:* | pkg:maven/io.netty/netty-transport@4.1.42.Final | MEDIUM | 2 | Highest | 31
netty-reactive-streams-2.0.3.jar | cpe:2.3:a:netty:netty:2.0.3:*:*:*:*:*:*:* | pkg:maven/com.typesafe.netty/netty-reactive-streams@2.0.3 | HIGH | 5 | Highest | 29
guava-20.0.jar | cpe:2.3:a:google:guava:20.0:*:*:*:*:*:*:* | pkg:maven/com.google.guava/guava@20.0 | MEDIUM | 1 | Highest | 24
jackson-databind-2.9.4.jar | cpe:2.3:a:fasterxml:jackson:2.9.4:*:*:*:*:*:*:*cpe:2.3:a:fasterxml:jackson-databind:2.9.4:*:*:*:*:*:*:* | pkg:maven/com.fasterxml.jackson.core/jackson-databind@2.9.4 | CRITICAL | 24 | Highest | 41

(extract from report generated by OWASP Dependency Check on version 3.1.4 of the service bus SDK)

**Comment by joshfree** [comment]
Thanks for sending the OWASP Dependency Check tool run @xaviersenac.  @yvgopal @hemanttanwar can you please update the package dependencies?

/cc @conniey @anuchandy @alzimmermsft

**Comment by yvgopal** [comment]
@joshfree @hemanttanwar There are 3 libraries showing vulnerabilities. One came from Async-http-client external dependency and I just raised a PR fixing it. The other two vulnerable dependencies are coming from azure-client-runtime library. The latest version of this library also has the same dependencies and it needs to be fixed. Could you take care of that library or assign it to the person(s) responsible for maintaining it?

**Comment by conniey** [comment]
@yvgopal I'm looking into fixing these issues in: https://github.com/Azure/autorest-clientruntime-for-java as well as a tool that will incorporate these findings.

**Comment by lilyjma** [comment]
Hi @xaviersenac, I was wondering if you'd be willing to share with us your experience working with this library so far. We're committed to improving our SDK, GitHub support process, and documentation. Your feedback would be extremely helpful to us, so please let me know if you'd be interested in hopping on a quick call to discuss it. Thanks!

**Comment by conniey** [comment]
Released as: https://search.maven.org/artifact/com.microsoft.azure/azure-servicebus/3.2.0-beta.1/jar
