### ISSUE TITLE
[FEATURE REQ] Cosmos SDK | Update RequestTimeline to include labels for both event and event duration

### ISSUE THREAD

**Issue by David-Noble-at-work** [Azure/azure-sdk-for-java#8034]
Adding meaningful names to duration fields would be useful to Cosmos SDK developers and end users in two ways:

* Communicating the meaning of duration and
* Labeling charts and graphs with event time on the x axis and duration on the y axis.

#### Example:

The `sent` event follows message encoding and occurs once it is confirmed that the message is on the wire. The duration of the `sent` event is the time that it takes for a round-trip to the server to complete and the next event occurs: `received`. The time between these two events--`sent` and `received`-- is the transitTime. 

Something like this JSON is what we should produce--perhaps word-smithed and simplified for brevity:
```
{
  "event": {
    "name": "sent", 
    "time": "<time-stamp>"
  }, 
  "interval": { 
    "name": "transitTime", 
    "duration": <microseconds> 
  }
}
```
I've discussed this with Naveen and Mo. We agreed that this work should be done on another PR. I've logged this issue to track the work which I will assign to myself for now.

**Comment by simplynaveen20** [comment]
A thought - this is use for debugging user latency issue , in that case duration name transit is more relevant that the actual event name sent . Also it will be hard to come up with two different names (x axis and y axis) for all events in rntbd and http and can create more confusion . Lets do it as we learn ?

**Comment by kushagraThapar** [comment]
This is done.
