### ISSUE TITLE
Investigate option to have our own pool buffers in azure-core-netty

### ISSUE THREAD

**Issue by srnagar** [Azure/azure-sdk-for-java#8051]
Due to recently [reported storage data corruption issue](https://github.com/Azure/azure-sdk-for-java/issues/7997), one option is to explore the possibility of having our own buffer pools when using `azure-core-http-netty`. 

Even with our own pooling, we still need a way for consumers to let us know that they are done with the pooled byte buffer. Netty does this via ref-count and the user is responsible for calling the retain() / release() pair.

While this is explicit in Netty, it is implicit in reactor-netty, i.e. reactor-netty assumes that once the onNext returns the buffer just emitted is ready to be claimed. The current issue is evidence that we cannot go this implicit route, with explicit, user-managed ref-count goes wrong then it can lead us to OOM.

Perhaps in `azure-core-http-netty` we could provide a way for customers to let us know that their use case requires deep-copy. Only customers know what type of Netty ByteBufAllocator is configured - it can be a pooled direct buffer, pooled heap buffer, or unpooled heap buffer. If it is pooled (Direct or Heap) and the customer use-case involves aggregation, then they can opt-in for deep-copy.

In the distant future when breaking changes are being considered, further exploration could be made towards considering the use of the Netty ByteBuf type as our byte abstraction, instead of the Java-standard ByteBuffer type. This could be used instead of building our own buffer pooling functionality.

**Comment by anuchandy** [comment]
Netty ByteBuf as individual module: https://mvnrepository.com/artifact/io.netty/netty-buffer/4.1.45.Final (size ~270 KB)

**Comment by alzimmermsft** [comment]
Closing this issue as https://github.com/Azure/azure-sdk-for-java/issues/8053 would be a better long-term target in resolving the number of buffers that need to be retained in memory at any given time.
