### ISSUE TITLE
Investigate retaining buffers during subscription lifetime

### ISSUE THREAD

**Issue by srnagar** [Azure/azure-sdk-for-java#8053]
This is an investigation task related to [this storage issue](https://github.com/Azure/azure-sdk-for-java/issues/7997). 

We may choose to offer an API where the user may opt-in for byte buffer retention. This gives the user more control and the ability to choose performance over memory. In this mode, we would retain the byte buffer from the time the subscription starts until the subscription is disposed. In this case, there is no deep copy and no heavy GC pressure, and the HttpClient will manage the list of byte buffer references and release them upon unsubscription.

**Comment by anuchandy** [comment]
I mean something like this when proposed the retain strategy: https://github.com/Azure/azure-sdk-for-java/compare/master...anuchandy:retain-buf?expand=1

**Comment by anuchandy** [comment]
When thinking a little more on this strategy, I see a gap - this is good for individual block download, I.e. all the chunks in a block is retained until the block download is unsubscribed. The problem raise - when multiple blocks downloaded via merge/flatmap, the merge operator won’t hold the subscriptions open on all individual block download for its entire life time.

**Comment by alzimmermsft** [comment]
As a first pass investigation for this issue it may be worthwhile only supporting Java 9+ in testing and using [Java's Cleaner](https://docs.oracle.com/javase/9/docs/api/java/lang/ref/Cleaner.html#:~:text=java.lang.ref.Cleaner%20public%20final%20class%20Cleaner%20extends%20Object%20Cleaner,notified%20that%20the%20object%20has%20become%20phantom%20reachable.) functionality

**Comment by alzimmermsft** [comment]
From further investigations there isn't a great way to handle this given that the `ByteBuf` could be backed by direct memory, meaning it won't be GC'd until absolutely necessary and retaining too many will exhaust the direct memory the JVM can use. Closing as won't be done.
