### ISSUE TITLE
How to get OS images

### ISSUE THREAD

**Issue by li-yh** [Azure/azure-sdk-for-java#810]
In the interface of ComputeManagementClient, I see getVirtualMachineImagesOperations which can be used to get VM images. However, I didn't see getVirtualMachineOSImageOperations, whereas, in C# sdk, we have this.

Therefore, the question is, how can we list OS images?

**Comment by anuchandy** [comment]
@li-yh virtualMachineOSImage related methods are available only in older version of Azure - ASM (Azure Service Management) https://github.com/Azure/azure-sdk-for-java/blob/0.9/service-management/azure-svc-mgmt-compute/src/main/java/com/microsoft/windowsazure/management/compute/VirtualMachineOSImageOperations.java

In the newer ARM based Azure REST, there is no OSImage operations. see the ARM spec here https://github.com/Azure/azure-rest-api-specs/blob/master/arm-compute/2016-03-30/swagger/compute.json

AFAIK listing OSImages is deprecated in ARM.

cc @singhkay

**Comment by jianghaolu** [comment]
No action to take.
