### ISSUE TITLE
Adding custom http-header does not work

### ISSUE THREAD

**Issue by javageek79** [Azure/azure-sdk-for-java#8103]
I've configured an Event Grid Topic to use Cloudevent format. Setting an apropriate header with `CustomHeadersInterceptor` does not work as it don't have any effect when calling `client.publishEventsAsync()` as it results in a `415 - Invalid Content Type`.

```
  TopicCredentials topicCredentials = new TopicCredentials(key);
  CustomHeadersInterceptor headersInterceptor = new CustomHeadersInterceptor().addHeader(HttpHeaders.CONTENT_TYPE, "application/cloudevents+json");
  RestClient restClient = new RestClient.Builder()
                    .withBaseUrl(eventGridEndpoint)
                    .withLogLevel(LogLevel.BODY_AND_HEADERS)
                    .withInterceptor(headersInterceptor)
                    .withCredentials(topicCredentials)
                    .withResponseBuilderFactory(new AzureResponseBuilder.Factory())
                    .withSerializerAdapter(new JacksonAdapter())
                    .build();
  EventGridClient client = new EventGridClientImpl(restClient);```

**Comment by yungezz** [comment]
hi @xccc-msft could you pls have a look?

**Comment by xccc-msft** [comment]
@javageek79 Could you please share more details on the SDK name and version you are using? According to the issue you described, we might need help from service end. I would add label of `Service Attention` here so service team can help check. Meanwhile you can try [`application/cloudevents+json; charset=utf-8`](https://docs.microsoft.com/en-us/azure/event-grid/cloud-event-schema#sample-event-using-cloudevents-schema). Thanks.

**Comment by ahamad-MS** [comment]
Hello @javageek79 .. thanks for reporting this issue. this is a known issue where Event Grid Data Plane (Event Pubishing) SDKs of various languages are not supporting cloud event 1.0 yet. We are in the process of adding this support with initial ETA of early to mid Oct for Java SDK and earlier for other SDKs. Sorry for any inconvenience this might cause. thanks.

**Comment by jfggdl** [comment]
@javageek79, we have released a preview version of our SDKs with support for Cloud Events 1.0. Please try again with this new version and let us know. Here is the link to the announcement and a wealth of information: https://devblogs.microsoft.com/azure-sdk/event-grid-client-libraries/. This is the link to all the SDK packages. Just look for Event Grid: https://azure.github.io/azure-sdk/.
