### ISSUE TITLE
smoke tests found possible breaks in KV for Windows and Linux

### ISSUE THREAD

**Issue by danieljurek** [Azure/azure-sdk-for-java#8109]
Linux says:
> Max retries 3 times exceeded. Error Details: Platform is not supported 

Windows says: 
> Max retries 3 times exceeded. Error Details: IO Exception in creating the WindowsDPAPICacheProtector

Internal execution logs: https://dev.azure.com/azure-sdk/internal/_build/results?buildId=258403&view=logs&j=f3570516-c8fe-5ce9-92b2-b737df25d5ea

**Comment by joshfree** [comment]
@g2vinay PTAL

**Comment by g2vinay** [comment]
Yeah, this issue is because of SharedTokenCacheCredentiall not handling exception properly and causing failure in DefaultAzureCredential when used in Linux and Windows 2019.
The fix will be merged to master soon..

**Comment by g2vinay** [comment]
This issue is fixed now, as part of this PR (merged):
https://github.com/Azure/azure-sdk-for-java/pull/8328
