### ISSUE TITLE
CONTRIBUTING.md's developer guide contains a build command that doesn't work

### ISSUE THREAD

**Issue by JimSuplizio** [Azure/azure-sdk-for-java#8110]
The easiest way to set this up:
1. Remove the local repository (%USERPROFILE%\.m2)
2. Run the command to build and test from [CONTRIBUTING.md](https://github.com/Azure/azure-sdk-for-java/blob/master/CONTRIBUTING.md#building-and-testing) **mvn -f pom.client.xml -Dgpg.skip -DskipTests clean install**
The command will fail on the verify's **check** goal with the following:
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-checkstyle-plugin:3.1.0:check (default) on project azure-client-sdk-parent: Execution default of goal org.apache.maven.plugins:maven-checkstyle-plugin:3.1.0:check failed: Plugin org.apache.maven.plugins:maven-checkstyle-plugin:3.1.0 or one of its dependencies could not be resolved: Could not find artifact com.azure:sdk-build-tools:jar:1.0.0 in ossrh (https://oss.sonatype.org/content/repositories/snapshots/) -> [Help 1]
_Note: This doesn't fail if we're running package instead of install._

Internally, we can run mvn install -f eng/code-quality-reports/pom.xml to install the build tools jar but it's unclear if someone external could successfully run this same command if we should recommend this at all.

**Comment by joshfree** [comment]
@sima-zhu could you help get contributing.md back into a consistent state?  I believe devs have made updates to the java wiki, but forgot to update contributing.md as well.  If the java wiki is going to be the source of truth for the build getting started instructions then one solution is to remove the stale content from contributing.md and include a direct link to the wiki instructions.

**Comment by sima-zhu** [comment]
Will work on the error in the issue and scan through whether the entire document is up to date.

**Comment by sima-zhu** [comment]
Closed the issue. Fixed the command. Scanned through the doc and checked every links. They all look good.
