### ISSUE TITLE
[BUG]Harcoded Region in Endpoint in CustomVisionTrainingManager

### ISSUE THREAD

**Issue by pkreborn06** [Azure/azure-sdk-for-java#8126]
I need to understand why the region in the endpoint is been hardcoded...

public static CustomVisionTrainingClient authenticate(String apiKey) {
        return authenticate("https://southcentralus.api.cognitive.microsoft.com/customvision/v2.1/Training/", apiKey);
  }

Issue :
While creating a project with different region in-spite of generating the keys we will get Access Denied error.

**Comment by joshfree** [comment]
@milismsft @ryogok @jianghaolu can you please follow up?

https://github.com/Azure/azure-sdk-for-java/blame/d2cf1859ef09c3874190770a3332e1491fb3d6d0/sdk/cognitiveservices/ms-azure-cs-customvision-training/src/main/java/com/microsoft/azure/cognitiveservices/vision/customvision/training/CustomVisionTrainingManager.java#L25

**Comment by Luyunmt** [comment]
There is a overload authenticate method which accepts both URL and apikey , can you try that method?

**Comment by Luyunmt** [comment]
Hi,@pkreborn06
How is this issue going? Feel free to let us know if further help is needed.

**Comment by tzhanl** [comment]
We are going to close this issue because we haven’t heard from you in a few days, but please re-open it if the issue still persists.
