### ISSUE TITLE
API document not available

### ISSUE THREAD

**Issue by abhikt48** [Azure/azure-sdk-for-java#8130]
Hi Team,

Defined API document not available. Could you please check

URL - https://docs.microsoft.com/en-us/java/api/overview/azure/servicebus/clientlibrary

Regards,
Abhishek Kumar

**Comment by joshfree** [comment]
Hi @abhikt48, @yvgopal will follow up, but in the mean time you can find service bus quick start guides in all languages, including java, at https://docs.microsoft.com/en-us/azure/service-bus-messaging/

**Comment by ramya-rao-a** [comment]
Hey @abhikt48 

Can you please share where you found this link?

I do see the "client library" linked, but as a section under parent page. See https://docs.microsoft.com/en-us/java/api/overview/azure/servicebus#client-library

**Comment by ramya-rao-a** [comment]
@spelluru Do you know where https://docs.microsoft.com/en-us/java/api/overview/azure/servicebus/clientlibrary might be linked from?

**Comment by spelluru** [comment]
@ramya-rao-a  - It's not linked from any of the articles in the folder: https://github.com/MicrosoftDocs/azure-docs/tree/master/articles/service-bus-messaging. 

@abhikt48 - could you let us know if you are using a direct link to this page or tried to navigate to this page from another page? Thanks

**Comment by abhikt48** [comment]
@ramya-rao-a  i am sorry not remember exact location now.  i think I found this on Git ServiceBus location.
