### ISSUE TITLE
[Followup]Make RangeFacetResult/ValueFacetResult strongly-typed

### ISSUE THREAD

**Issue by AlexGhiondea** [Azure/azure-sdk-for-java#8142]

**Comment by sima-zhu** [comment]
close https://github.com/Azure/azure-sdk-for-java/pull/8273

**Comment by sima-zhu** [comment]
The PR is currently in progress. Bruce is asking to have APIs for customer to use. This might need extra efforts on swagger. Will follow up.

**Comment by sima-zhu** [comment]
Need more function available to customer. Will address this in Preview 2
