### ISSUE TITLE
[InProgress]Increase test coverage

### ISSUE THREAD

**Issue by AlexGhiondea** [Azure/azure-sdk-for-java#8143]
3 pinning tests missing from DocumentConverterTests
- CanReadArraysOfMixedTypes
- EmptyArraysReadAsObjectArrays
- ArraysWithOnlyNullsReadAsStringArrays

Missing test cases in LookupTests
- GetDynamicDocumentCannotAlwaysDetermineCorrectType
- CanGetDocumentWithBase64EncodedKey
- RoundTrippingDateTimeOffsetNormalizesToUtc

Ensure that x-ms-return-client-request-id works as intended

**Comment by alzimmermsft** [comment]
Closed via #8274
