### ISSUE TITLE
[Auto-gen bug]Ensure extensible enums are used where needed

### ISSUE THREAD

**Issue by AlexGhiondea** [Azure/azure-sdk-for-java#8146]
Extensible enum-related
- Analyzer properties of Field should be of type AnalyzerName
- CustomAnalyzer properties need to be extensible enums instead of String

**Comment by sima-zhu** [comment]
Swagger changes

**Comment by sima-zhu** [comment]
* Analyzer properties of Field should be of type AnalyzerName
It is a swagger change. @brjohnstmsft I think your swagger change can address this.

**Comment by sima-zhu** [comment]
Involve @jianghaolu for the code-gen issue.

**Comment by sima-zhu** [comment]
* CustomAnalyzer properties need to be extensible enums instead of String
Class needs to change from 
```
    @JsonProperty(value = "tokenizer", required = true)
    private String tokenizer;
    
    @JsonProperty(value = "tokenFilters")
    private List<String> tokenFilters;
    
    @JsonProperty(value = "charFilters")
    private List<String> charFilters;
```

to 

```
    @JsonProperty(value = "tokenizer", required = true)
    private TokenizerName tokenizer;
    
    @JsonProperty(value = "tokenFilters")
    private List<TokenFilterName> tokenFilters;
    
    @JsonProperty(value = "charFilters")
    private List<CharFilterName> charFilters;
```

Swagger def:
[Link](https://github.com/Azure/azure-rest-api-specs/blob/master/specification/search/data-plane/Microsoft.Azure.Search.Service/stable/2019-05-06/searchservice.json#L1432)

**Comment by sima-zhu** [comment]
The changes have merged into master
