### ISSUE TITLE
[InProgress]Address API Feedback

### ISSUE THREAD

**Issue by AlexGhiondea** [Azure/azure-sdk-for-java#8149]
**TODO:**
**Done:**
- ~~FacetResult.java property is "documents" when it can reasonably be left as "additionalProperties".~~
- ~~Rename IndexBatchImpl -> IndexBatchBase~~
- ~~Try making SuggestRequest and AutocompleteRequest package-scope (will have to make a lot of generated classes package-scope too probably)~~
- ~~Move to azure-core 1.3.0 and use ContinuablePagedFluxCore instead of PagedFluxBase~~
- ~~GeoPoint shouldn't expose coordinates directly~~
- ~~Review naming of DataSources static methods for API guidelines compliance~~
- ~~getDocumentCount() should return long, not Long~~
- ~~SearchDocumentsResult - getNextPageParameters and getNextLink should be package-scope. So should SearchRequest (if possible).~~
- ~~The document property of SearchResult and SuggestResult should not be mutable. Probably the result of an over-broad regex rule.~~
- ~~Singular names for IndexBatch methods -- apparently intentional, need to check with API review board if they should be plural.~~

**Comment by sima-zhu** [comment]
* Autocomplete -> AutoComplete (Auto-gen)

**Comment by sima-zhu** [comment]
Auto-gen code issue:
1. `Mono<SimpleResponse<Void>>` -> ` Mono<Response<Void>> delete`
1. `final String apiVersion = "2019-05-06";` should removed this.client.getApiVersion()
1.` VisualFeature` there are several addition.
1. `ImageAnalysisSkill` addition
1.` ImageAnalysisSkillLanguage` addition
1. `SearchMode` enum is not the same.
1. `TextSplitMode` and `TextTranslationSkillLanguage` are being deleted.

**Comment by brjohnstmsft** [comment]
@sima-zhu Please do not change names unless there is a compelling reason to do so. `Skillset` is the correct casing as it is all one word (see [here](https://github.com/Azure/azure-sdk-for-net/blob/master/sdk/search/Microsoft.Azure.Search.Service/src/Generated/Models/Skillset.cs)), as is [Autocomplete](https://github.com/Azure/azure-sdk-for-net/blob/2d4097a23917c4a35ca75bc2dda1c16761b4170b/sdk/search/Microsoft.Azure.Search.Data/src/Customizations/Documents/DocumentsOperationsExtensions.cs#L67).

Regarding the other changes, once my [Swagger PR](https://github.com/Azure/azure-rest-api-specs/pull/8552) is merged, there may be some changes there. `VisualFeature` in particular is supposed to be deprecated sometime before the end of this week and should not ship in Preview 1.

**Comment by sima-zhu** [comment]
`Document` is not generated, so `SearchResult` and `SuggestionResult` cannot import properly

**Comment by sima-zhu** [comment]
Done with the API changes in this issue.
