### ISSUE TITLE
[Verification]Add support for distributed tracing

### ISSUE THREAD

**Issue by AlexGhiondea** [Azure/azure-sdk-for-java#8151]

**Comment by joshfree** [comment]
The work here is to spot check and verify tracing in the Search SDK.  Run some scenarios, open the tracing output in Zipkin, verify sufficient tracing calls, with well-named start/end span calls that properly match method names to aid in CSS and end-user diagnosing issues.

**Comment by sima-zhu** [comment]
Verify this via Zipkin:
Here is Json:
```
span: SpanData{traceId=TraceId{traceId=9f29929aeac533053e84e70c61f8bf77}, spanId=SpanId{spanId=37b3c3df00067cf9}, traceFlags=TraceFlags{sampled=true}, tracestate=Tracestate{entries=[]}, parentSpanId=SpanId{spanId=0000000000000000}, resource=Resource{labels={}}, instrumentationLibraryInfo=InstrumentationLibraryInfo{name=Azure-OpenTelemetry, version=null}, name=SearchServiceRestClientIndexes.delete, kind=INTERNAL, startEpochNanos=1582936187423004800, attributes={}, timedEvents=[], links=[], status=Status{canonicalCode=OK, description=null}, endEpochNanos=1582936188212066300, hasRemoteParent=false}
```
![image](https://user-images.githubusercontent.com/48036328/75597619-5b5ba080-5a4b-11ea-81b3-dd3cd9d74561.png)

**Comment by sima-zhu** [comment]
Close the issue. Feel free to reopen if any other questions.
