### ISSUE TITLE
Internal code clean-up

### ISSUE THREAD

**Issue by AlexGhiondea** [Azure/azure-sdk-for-java#8159]
- SearchIndexAsyncClient.searchNextPage is munging top and skip -- should use the payload as-is instead
  - SearchPagedResponse -- consider removing skip == null check, but maybe when we change the paging implementation
- Remove the special case for client-request-id from SearchIndexClientBuilder
- Remove extra try/catch blocks in async clients
- Ensure the right level of Logging

**Comment by alzimmermsft** [comment]
- Extra try/catch blocks have been removed in PR #8274 
- The search next page will be cleaned up in PR #8303

**Comment by alzimmermsft** [comment]
For now the `SearchIndexClientBuilder` will continue to use `client-request-id` as the header being set in `RequestIdPolicy` to match the header that would be set if a customer passes a `RequestOptions` with a set `UUID`. Issue #8502 will track whether this needs to change before GA if the generated layer switches to another request ID header such as `x-ms-client-request-id`.

**Comment by brjohnstmsft** [comment]
@alzimmermsft FYI the service will accept either `client-request-id` or `x-ms-client-request-id`, and they both have the same effect. It's `x-ms-return-client-request-id` that we don't (yet) support.

**Comment by alzimmermsft** [comment]
@brjohnstmsft I opened PR #8648 to address the issue of the builder setting `x-ms-return-client-request-id` instead of `return-client-request-id`. I am going to leave issue #8502 open as we'll want to make sure the client request ID setting is consistent between the options available to the user.

**Comment by brjohnstmsft** [comment]
@alzimmermsft Regarding issue #8502, I guess I'm unclear on why they can't both be `x-ms-client-request-id` today.

**Comment by alzimmermsft** [comment]
@brjohnstmsft #8502 could be resolved now to using `x-ms-client-request-id` via a swagger transform so that `RequestOptions` sets that value. I don't know if we would want to propagate that to the official swagger.

**Comment by alzimmermsft** [comment]
Closing this issue as all tasks are complete

**Comment by brjohnstmsft** [comment]
@alzimmermsft Got it, I forgot the header name was in the Swagger. I'll update it.
