### ISSUE TITLE
[BUG] No azure-search 1.0.0-beta.2 available for maven

### ISSUE THREAD

**Issue by igor-bakhtoiarov-8451** [Azure/azure-sdk-for-java#8184]
**Describe the bug**
I am trying to use Azure Search library with azure-keyvault-secrets-spring-boot-starter and azure-identity libraries in the same project.
Unfortunately azure-search 1.0.0-beta.1 has old dependencies from azure.core.* and I am getting ClassNotFoundException.
The azure-search 1.0.0-beta.2 resolves my problems (I packaged it locally and installed into local maven repo), but it's not available in a maven public repo.
Could someone push the azure-search 1.0.0-beta.2 to the maven repo.

**To Reproduce**
Add the following dependency to pom.xml
<groupId>com.azure</groupId>
<artifactId>azure-search</artifactId>
<version>1.0.0-beta.2</version>

**Expected behavior**
Maven should resolve the dependency correctly.

**Screenshots**

**Setup (please complete the following information):**
 - OS: macos
 - IDE : IntelliJ
 - Version of the Library used : 1.0.0-beta.2

**Comment by brjohnstmsft** [comment]
@igor-bakhtoiarov-8451 The azure-search library for Java is still under development and will be undergoing some API changes over the next few months. Stay tuned for official announcements of the next version's availability in the coming weeks.

**Comment by joshfree** [comment]
Hi @igor-bakhtoiarov-8451. Updates on the azure-search library will be made via the Azure SDK team's techcommunity monthly blog posts and also via the AzureSDK twitter account:

Example:

https://twitter.com/AzureSdk/status/1229856571020083200
https://techcommunity.microsoft.com/t5/azure-sdk/february-2020-unified-sdk-release/ba-p/1174661

As @brjohnstmsft mentioned, please stay tuned.

/cc @alzimmermsft @sima-zhu @AlexGhiondea

**Comment by joshfree** [comment]
Related https://github.com/Azure/azure-sdk-for-java/issues/8133

**Comment by alzimmermsft** [comment]
@igor-bakhtoiarov-8451 A newer version of Azure Search has been shipped! The newer package is under the same group and artifact IDs but the version is `11.0.0-beta.1`, it is the subsequent release of `1.0.0-beta.1`. https://search.maven.org/artifact/com.azure/azure-search

**Comment by igor-bakhtoiarov-8451** [comment]
Thanks, I saw that just yesterday. I will plan to upgrade the version and check it.

**Comment by alzimmermsft** [comment]
Hi @igor-bakhtoiarov-8451 was the latest release able to resolve this issue?

**Comment by alzimmermsft** [comment]
Just wanted to follow-up to understand if this issue is still an active problem @igor-bakhtoiarov-8451

**Comment by joshfree** [comment]
I'm closing this issue now that the latest azure-search preview is released.  @igor-bakhtoiarov-8451 please feel free to provide more comments or reactivate if there's any issues or concerns.  Thanks again.

**Comment by igor-bakhtoiarov-8451** [comment]
Finally the update azure-search to 11.0.0-beta.1 happened for me. It was a pain to update all the dependencies, because everything tied to azure-core. So you have to make sure all other azure dependencies uses the same version of azure shared libraries.
