### ISSUE TITLE
Exception in thread "main" com.azure.core.exception.ResourceModifiedException: Status code 403, "{"error":{"code":"Forbidden","message":"Access denied. Caller was not found on any access policy.\r\nCaller[BUG]

### ISSUE THREAD

**Issue by sachinp9192** [Azure/azure-sdk-for-java#8229]
**Describe the bug**

Exception in thread "main" com.azure.core.exception.ResourceModifiedException: Status code 403, "{"error":{"code":"Forbidden","message":"Access denied. Caller was not found on any access policy.\r\nCaller
***Exception or Stack Trace***
Add the exception log and stack trace if available
Exception in thread "main" com.azure.core.exception.ResourceModifiedException: Status code 403, "{"error":{"code":"Forbidden","message":"Access denied. Caller was not found on any access policy.\r\nCaller
**To Reproduce**
Exception in thread "main" com.azure.core.exception.ResourceModifiedException: Status code 403, "{"error":{"code":"Forbidden","message":"Access denied. Caller was not found on any access policy.\r\nCaller
***Code Snippet***
Add the code snippet that causes the issue.

**Expected behavior**

**Screenshots**

**Setup (please complete the following information):**
 - IDE : [e.g. IntelliJ]
 - Version of the Library used

**Additional context**

**Information Checklist**
Kindly make sure that you have added all the following information above and checkoff the required fields otherwise we will treat the issuer as an incomplete report
- [ ] Bug Description Added
- [ ] Repro Steps Added
- [ ] Setup information Added

**Comment by sachinp9192** [comment]
There is no proper documentation for it. I have already given access to this specific tenat id

**Comment by JonathanGiles** [comment]
@sachinp9192 There is not enough information in this bug report to enable us to help you. Please can you provide additional information about what library you are using, what you are trying to achieve, sample code if you can share it, etc. Barring this additional information we will need to close this bug report as it is currently incomplete.

**Comment by sachinp9192** [comment]
@JonathanGiles :- sorry for the inconvenience, actually i have solved it by giving access policy with key-vault.

**Comment by JonathanGiles** [comment]
Glad you solved the issue. Question: Did you manage to find appropriate documentation or did you work it out for yourself? If you found documentation, what prevented you from finding it initially (was it in a non-obvious location, etc)? Thanks.
