### ISSUE TITLE
[BUG] PollerFlux will always delay polling

### ISSUE THREAD

**Issue by yaohaizh** [Azure/azure-sdk-for-java#8235]
The defaultInterval cannot be 0 or negative on PollerFlux.java. This will make the polling operation take at least 1 seconds, which make the test case unnecessary waiting.  Should allow immediate polling in the PollerFlux.

**Comment by joshfree** [comment]
@anuchandy could you please take a look?

**Comment by srnagar** [comment]
@yaohaizh PollerFlux takes a `Duration` as the polling interval. So, you can provide a smaller duration like `Duration.ofMillis(10)` to reduce the polling interval to 10 millis to speed up the test cases. Also, if you are using `StepVerifier`, you can also use `withVirtualTime` to use a virtual clock to not wait for 10 seconds.

https://projectreactor.io/docs/test/release/api/reactor/test/StepVerifier.html#withVirtualTime-java.util.function.Supplier-

**Comment by yaohaizh** [comment]
@srnagar thanks for the information.
