### ISSUE TITLE
Is there any configuration to do throttling for concurrent blob downloads?[QUERY]

### ISSUE THREAD

**Issue by yamasaLine** [Azure/azure-sdk-for-java#8245]
## Query/Question
Hi SDK team, our project is using Azure blob as file storage, and we will store plenty of zip files, about size of  around 50M. 
As some background from my expriements, I know the blob SDK is backed by reactor netty, and if I issue concurrent downloads for the 50M files, netty will consume pretty direct memory, **causing memory fault once exceeded the JVM direct memory limit**. This is not what we want.
So I wonder if I have no mean to bypass the netty direct memory limitation(ideal way would be the socket bytes streamed to local file directly without help of memory), **is there any configuration or parameter to do throttling ?** Like, 
+ I know the direct memory limit and blob file size, I can guess the concurrent download requests upper limit.
+ I can set the configuration with the guessing limit.
+ When the limit reaches, following downloads will be waiting or just fail directly.

To be some supplement, `BlobClient.downloadWithResponse()` will be called concurrently in my case.

## Why is this not a Bug or a feature Request?
I don't know whether the direct memory outage should be one bug or not, but I am not sure whether the throttling config exists or not, this is one question rather than FR.

## Setup (please complete the following information if applicable):**
 - OS: Windows 10 pro, 1809 build
 - IDE : IntelliJ 2019.3
 - Version of the Library used: 12.0.0

**Comment by rickle-msft** [comment]
Hi, @yamasaLine. Thank you for posting your question. The method `downloadWithResponse` issues only a single request and uses no parallelism. Therefore, the Storage SDK cannot offer much help in the way of coordinating/throttling in scenarios when you are doing multiple concurrent downloads and you'll have to implement some logic to manage your resource consumption on top of that. 

That said, memory allocation happens further down in Azure Core and even Reactor-Netty. @alzimmermsft can you please comment on whether there are setting which may be toggled at either of these layers for safer memory usage?

**Comment by joshfree** [comment]
@anuchandy can you please follow up on the reactor-netty toggle specific portion of this question and ensure any toggles also get documented in the [java repo's wiki](https://github.com/azure/azure-sdk-for-java/wiki)?

**Comment by anuchandy** [comment]
@yamasaLine - we can control the concurrency using [flatmap](https://projectreactor.io/docs/core/release/api/reactor/core/publisher/Flux.html#flatMap-java.util.function.Function-int-) operator.

```java
 // build the ContainerClient
final BlobContainerAsyncClient containerAsyncClient = ...
// a list containing name of all blobs to download.
final List<String> blobNames = ...
// the local directory to store the downloaded blobs (zip files).
final String localDirPath = "D:\\myFiles\\"; 
// the maximum number of blobs to download in flight.
final int concurrentFileCount = 10;
final DownloadRetryOptions options = new DownloadRetryOptions().setMaxRetryRequests(5);
//
Flux.fromIterable(blobNames)
    .flatMap(blobName -> {
        return containerAsyncClient.getBlobAsyncClient(blobName)
            .downloadToFileWithResponse(localDirPath + blobName,
                null,
                null,
                options,
                null,
                false);
    }, concurrentFileCount);
```

**Comment by anuchandy** [comment]
The idea here is - the flatmap operator read 10 blob names from the list and start 10 downloads. As soon as one or more, say 3, download out of 10 finishes, it read next 3 blob names from list and start 3 downloads. This way, at any moment there is only 10 or less downloads in progress.

If you're looking for disabling/minimizing Netty direct memory and switch to heap, following netty options can be used:

```
export JAVA_OPTS="$JAVA_OPTS -Dio.netty.allocator.type=unpooled"
export JAVA_OPTS="$JAVA_OPTS -Dio.netty.noPreferDirect=true"
export JAVA_OPTS="$JAVA_OPTS -Dio.netty.recycler.maxCapacity.default=0"
export JAVA_OPTS="$JAVA_OPTS -Dio.netty.recycler.maxCapacity=0"
export JAVA_OPTS="$JAVA_OPTS -Dio.netty.maxDirectMemory=0"
export JAVA_OPTS="$JAVA_OPTS -Dio.netty.leakDetectionLevel=advanced"
```

**Comment by yamasaLine** [comment]
@anuchandy thanks for your reply! I could understand the idea(though I'm pretty new to reactor java), but the real scenario is something a bit different. 
Our service is one microservice and accept unpredictable blob downloading requests simultaneously, so 

- It's not the case that I could know how many concurrent downloads will be acting. 
- Also it's not acceptable to wait multiple reqs to form one fixed size batch(like 10 as your example) and then doing downloads, it will have latency impacts.

Seems one way for me is to do queue waiting to control the memory consumption by myself's implementation. 
BWT, is there any method in `BlobClient` originally designed to do simultaneous downloading, which could be better than multiple threads calling `downloadWithResponse()`? Thanks.

**Comment by rickle-msft** [comment]
@yamasaLine I think Anu's proposed implementation should still work for your case. The [Reactor docs](https://projectreactor.io/docs/core/release/api/reactor/core/publisher/Flux.html#flatMap-java.util.function.Function-int-) indicate that the concurrency parameter is a _max_ concurrency, so your download jobs will still trigger as they arrive, but there will be no more than 10 happening at a time. If there are more than 10 outstanding operations, they will be queued. You therefore also don't need to know how beforehand how many downloads you'll need to do. Again, the parameter is just the most you'd like happening at any given moment. 

To address your second question, there's nothing in the SDK that coordinates work across resources. Each client targets exactly one resource, so any higher level jobs (e.g. downloading a whole virtual directory) needs to be coordinated by the user. If the job is particularly large, we generally start to suggest that customers to consider using azcopy for those transfers as it is a tool specifically designed for those kinds of jobs.

**Comment by rickle-msft** [comment]
I am going to close this issue as I believe all parts of the question have been addressed and it has been inactive for a while. Please feel free to reopen if there are more questions.
