### ISSUE TITLE
[BUG] azure-messaging-eventhubs complains about missing OperationStatus class

### ISSUE THREAD

**Issue by cykl** [Azure/azure-sdk-for-java#8268]
**Describe the bug**

azure-messaging-eventhubs 5.0.2  warns about missing OperationStatus class. This warning was also present in previous releases and doesn't seems to prevent good execution.

***Exception or Stack Trace***

```
2020-02-18 16:31:32,552 WARN  com.azure.core.implementation.serializer.HttpResponseBodyDecoder [] - Failed to find class 'com.azure.core.management.implementation.OperationStatus'.
```
 
**To Reproduce**

My test case is based on  ClientEventProcessor with following dependencies:

```xml
        <dependency>
            <groupId>com.azure</groupId>
            <artifactId>azure-messaging-eventhubs</artifactId>
            <version>5.0.2</version>
        </dependency>
        <dependency>
            <groupId>com.azure</groupId>
            <artifactId>azure-messaging-eventhubs-checkpointstore-blob</artifactId>
            <version>1.0.2</version>
        </dependency>
```

I think any application will reproduce the issue.

**Expected behavior**

Being spammed by warnings is annoying, issue should be fixed or warning disabled. Adding `com.azure:azure-core-management` to dependencies seems to fix the issue. I had expect one of those two behaviours:

 - azure-messaging-eventhubs declares all of its required dependencies.
 - optional dependency should be optional and not trigger warnings.

**Additional context**

**Comment by joshfree** [comment]
Thanks for reporting this issue @cykl.  @srnagar will follow up soon.

/cc @conniey

**Comment by conniey** [comment]
This is warning probably from using azure-identity because it pulls in RestProxy. It was fixed in this:
https://github.com/Azure/azure-sdk-for-java/pull/7840

**Comment by srnagar** [comment]
The warning was added in anticipation of types that will be added for management libraries. Since this is not yet supported, PR #7840 removes this warning.

When Event Hubs updates azure-core dependency to the next GA release, this warning will be removed.
