### ISSUE TITLE
Support SharedTokenCacheCredential on Mac and IntelliJ

### ISSUE THREAD

**Issue by jyotsnaravikumar** [Azure/azure-sdk-for-java#8269]
**Describe the bug**

Local development does not work without explicitly setting DefaultAzureCredentials.

Error:
Max retries 3 times exceeded. Error Details: Tried EnvironmentCredential, ManagedIdentityCredential, SharedTokenCacheCredential but failed to acquire a token for any of them. Please verify the environment for either of them and see more details in the causes below.
 
SharedTokenCacheCredential is not getting created on mac/intellij?
 
Docs referred:
https://azure.github.io/azure-sdk/releases/2019-09-17/java.html
Added new credential type SharedTokenCacheCredential, allowing authenticating to Azure Active Directory if you are logged in Visual Studio 2019 (currently supported on Windows only).
​
https://github.com/Azure/azure-sdk-for-java/tree/master/sdk/identity/azure-identity
 
https://docs.microsoft.com/en-us/azure/key-vault/quick-create-java#set-environmental-variables

Max retries 3 times exceeded. Error Details: Tried EnvironmentCredential, ManagedIdentityCredential, SharedTokenCacheCredential but failed to acquire a token for any of them. Please verify the environment for either of them and see more details in the causes below.

***Exception or Stack Trace***
Add the exception log and stack trace if available
Error:
Max retries 3 times exceeded. Error Details: Tried EnvironmentCredential, ManagedIdentityCredential, SharedTokenCacheCredential but failed to acquire a token for any of them. Please verify the environment for either of them and see more details in the causes below.
 

**To Reproduce**

***Code Snippet***
Add the code snippet that causes the issue.
 public SecretClient getSecretClient(){
        try {
            String keyVaultName = environment.getProperty("KeyVaultName");
            String kvUri = "https://" + keyVaultName + ".vault.azure.net";

            logger.info("key vault name" + keyVaultName + " and kv uri " + kvUri);

            secretClient = new SecretClientBuilder()
                    .vaultUrl(kvUri)
                    .credential(new DefaultAzureCredentialBuilder().build())
                    .buildClient();
        }catch(Exception ex){
            logger.error("Unable to get handle to secret client " + ex.getMessage());
        }
        return secretClient;

    }

**Expected behavior**
Have seen the DefaultCredentials/SharedTokenCacheCredentials work smoothly on windows.
Would like to see same experience on mac/linux

**Screenshots**

**Setup (please complete the following information):**
 - OS: mac
 - IDE : IntelliJ
 - Version of the Library used:
   <dependency>
      <groupId>com.azure</groupId>
      <artifactId>azure-identity</artifactId>
      <version>1.0.1</version>
    </dependency>

    <dependency>
      <groupId>com.azure</groupId>
      <artifactId>azure-security-keyvault-secrets</artifactId>
      <version>4.1.0</version>
    </dependency>

**Comment by joshfree** [comment]
Thanks for reporting this issue when taking a working dev-time scenario from Windows to Mac @jyotsnaravikumar.  @g2vinay can you please follow up?

/cc @jianghaolu @schaabs

**Comment by jianghaolu** [comment]
SharedTokenCache is not working on Mac yet. There's no plan to support IntelliJ either though that sounds like a good idea to support.

**Comment by jianghaolu** [comment]
Your best solution for local development now is either `InteractiveBrowserCredential` if your dev environment allows a browser pop-up. Or you could create a service principal using Azure CLI through `az ad sp create-for-rbac --sdk-auth` and use `ClientSecretCredential` or `EnvironmentCredential`.

**Comment by jongio** [comment]
@jyotsnaravikumar - I know your request here was for VS, but I wanted to let you know that we released a preview of AZ CLI support to DefaultAzureCredential, which you can find here.

If you run `az login`, then use the preview DefaultAzureCredential, you will automatically be authenticated with Azure.

https://search.maven.org/artifact/com.azure/azure-identity/1.1.0-beta.1/jar

Please try it out and let us know if you have any feedback.

(The original issue can still remain open as it also discusses adding support to IDEs)

**Comment by sitase** [comment]
I tried the 1.1.0-beta.2. I consistently get that the process doesn't exit.

```
Caused by: java.lang.RuntimeException: Tried EnvironmentCredential, ManagedIdentityCredential, SharedTokenCacheCredential, AzureCliCredential but failed to acquire a token for any of them. Please verify the environment for either of them and see more details in the causes below.
        at com.azure.identity.ChainedTokenCredential.lambda$getToken$3(ChainedTokenCredential.java:51)
        at reactor.core.publisher.MonoDefer.subscribe(MonoDefer.java:44)
        ... 65 more
Caused by: java.lang.IllegalThreadStateException: process hasn't exited
        at java.base/java.lang.ProcessImpl.exitValue(ProcessImpl.java:522)
        at com.azure.identity.implementation.IdentityClient.authenticateWithAzureCli(IdentityClient.java:209)
        at com.azure.identity.AzureCliCredential.getToken(AzureCliCredential.java:35)
        at com.azure.identity.ChainedTokenCredential.lambda$getToken$1(ChainedTokenCredential.java:40)
        at reactor.core.publisher.FluxFlatMap$FlatMapMain.onNext(FluxFlatMap.java:378)
        at reactor.core.publisher.FluxIterable$IterableSubscription.slowPath(FluxIterable.java:243)
        ... 57 more
```

This on OSX 10.15 19A583 and openjdk 11.0.5.

**Comment by jongio** [comment]
Thanks @sitase - I created a new issue for that error.  Thank you for trying it out.

**Comment by g2vinay** [comment]
Thanks @sitase  for trying it out.

It would be helpful if you could execute the following command and share the output of the 2nd command:
1. az login
2. az account get-access-token --output json --resource https://vault.azure.net

Do REDACT the token/tenant/subscription value.

**Comment by g2vinay** [comment]
@sitase 

We fixed the issue in 1.1.0-beta.3 April release.
Please try it out and let us know, if you run into any issues.

**Comment by vcolin7** [comment]
You can also use `DefaultAzureCredential` by following @jianghaolu's suggestion of creating a service principal. For details about how to do this refer to [this documentation](https://docs.microsoft.com/en-us/java/api/overview/azure/security-keyvault-keys-readme?view=azure-java-stable#authenticate-the-client).

**Comment by vcolin7** [comment]
Changed this from a *bug* in KeyVault to *feature request* for Identity, as suggested by @joshfree in a conversation we had.

**Comment by jianghaolu** [comment]
Hi @jyotsnaravikumar 

In the latest preview 1.1.0-beta.6 you can use DefaultAzureCredential to login with the account in Azure Toolkit for IntelliJ. If you are looking for the stable release, it's coming in August in version 1.1.0.

JFYI, shared token cache is a Microsoft proprietary concept shared across tools like Visual Studio, Azure SDKs, etc. It's probably not what you are looking for here.

**Comment by vcolin7** [comment]
This means you should now be able do something like this:
```java
SecretClient secretClient = new SecretClientBuilder()
    .vaultUrl("<key-vault-uri>")
    .credential(new DefaultAzureCredentialBuilder().build())
    .buildClient();
```
on IntelliJ and have it work. However, if you **specifically** want to use `SharedTokenCacheCredential` you probably want to use something like Visual Studio.

**Comment by vcolin7** [comment]
You can find more details on how to use different types of credentials [here](https://devblogs.microsoft.com/azure-sdk/azure-sdk-release-may-2020/).
