### ISSUE TITLE
Finalize on `getPreferredLocations()` API 

### ISSUE THREAD

**Issue by kushagraThapar** [Azure/azure-sdk-for-java#8271]
Currently we have the public API : `getPreferredLocations()` in `ConnectionPolicy.java` 
We need to finalize if we should have this API as part of public surface / or not.

**Comment by kushagraThapar** [comment]
@kirankumarkolli @moderakh Tracking this API decision here.

**Comment by kushagraThapar** [comment]
.Net API has `ApplicationRegion`  setting.

**Comment by kushagraThapar** [comment]
`ApplicationRegion` is a separate API altogether which will be discussed later. Here in this issue, we are just discussing on a rename. 
Replace this API name with - `get/setApplicationPreferredRegion()`

**Comment by xinlian12** [comment]
Fixed and checked in master.
