### ISSUE TITLE
VMCreateGuide sample failed to create resource group

### ISSUE THREAD

**Issue by smartmaster** [Azure/azure-sdk-for-java#828]
SDK version: v1.0.0-beta1+fixes  
Debug screenshot attached
![000-vmcreateguide-failed-to-create-recource-group](https://cloud.githubusercontent.com/assets/5144190/16110111/b73eb410-33de-11e6-9918-c4c29843b073.png)

**Comment by jianghaolu** [comment]
When it prompts you for subscription, you need to type in the number in front the subscription, in this case, 1.

**Comment by smartmaster** [comment]
I have made slight change for the sample NOT to interactively input the subscription, i.e. I have already selected the correct subscription programmatically.

the issue is "VMCreateGuide sample failed to create resource group", the line of code failed at "resourceManagementClient.getResourceGroupsOperations().createOrUpdate(resourceGroupName, resourceGroupParameters);"

BTW, I downloaded the source code v1.0.0-beta1+fixes and built SDK from the source, and use jdk1.8.0_92.

thanks and look forward to your reply.

**Comment by jianghaolu** [comment]
Hi @smartmaster 

Can you try turning on logging and attach the logs? And, how often does this reproduce on your side? Like every time, or every few times?
To turn on logging, you need
```java
OkHttpClient.Builder clientBuilder = new OkHttpClient.Builder()
                .addInterceptor(new HttpLoggingInterceptor().setLevel(HttpLoggingInterceptor.Level.BODY));
ResourceManagementClient resourceClient = new ResourceManagementClientImpl("http://management.azure.com", clientBuilder, new Retrofit.Builder());
```

The magic happening underneath `createOrUpdate()` is that we do a `PUT` request first, and then keep `GET`ting from a polling endpoint. When the polling endpoint tells us that the resource groups is fully provisioned, we do a `GET` on the resource ID to get the object. With that being said, there can be a delay between the "fully provisioned" state and the "gettable" state. I'm considering adding a retry handler specifically for this delay since I was able to reproduce this in VM creation as well, but not as frequently.

**Comment by smartmaster** [comment]
hi @jianghaolu ,
thanks for your detailed explanation. the issue can be reproduced every time, I will turn on log and share with you some while later.

regards,

**Comment by smartmaster** [comment]
hi @jianghaolu ,

I have added the log and found that
1. to get resource group, 
ResourceGroup resgroup = resourceManagementClient.getResourceGroupsOperations().get(resourceGroupName).getBody();

HTTP traffic logs are printed, and "HTTP Get" returned "200 OK"
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
--> GET https://management.azure.com/subscriptions/7315bf64-0ed9-46d8-b4e6-1a6082194d22/resourcegroups/hbbu-res-group?api-version=2015-11-01 http/1.1
accept-language: en-US
--> END GET
<-- 200 OK https://management.azure.com/subscriptions/7315bf64-0ed9-46d8-b4e6-1a6082194d22/resourcegroups/hbbu-res-group?api-version=2015-11-01 (552ms)
Cache-Control: no-cache
Pragma: no-cache
Content-Type: application/json; charset=utf-8
Expires: -1
Vary: Accept-Encoding
x-ms-ratelimit-remaining-subscription-reads: 14976
x-ms-request-id: 3dac0900-4f72-4e52-843b-547b6cf6dd98
x-ms-correlation-request-id: 3dac0900-4f72-4e52-843b-547b6cf6dd98
x-ms-routing-request-id: EASTASIA:20160622T081242Z:3dac0900-4f72-4e52-843b-547b6cf6dd98
Strict-Transport-Security: max-age=31536000; includeSubDomains
Date: Wed, 22 Jun 2016 08:12:42 GMT
OkHttp-Sent-Millis: 1466583162310
OkHttp-Received-Millis: 1466583162579

{"id":"/subscriptions/7315bf64-0ed9-46d8-b4e6-1a6082194d22/resourceGroups/hbbu-res-group","name":"hbbu-res-group","location":"eastus","properties":{"provisioningState":"Succeeded"}}
<-- END HTTP (181-byte body)
id=/subscriptions/7315bf64-0ed9-46d8-b4e6-1a6082194d22/resourceGroups/hbbu-res-group, name=hbbu-res-group, location=eastus
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

2. to create Or Updateresource group, resourceManagementClient.getResourceGroupsOperations().createOrUpdate(resourceGroupName, resourceGroupParameters);

- no HTTP traffic logs are printed, and exception was thrown as below. 

~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
VMCreateGuide [Java Application]	
	com.azure.sonmi01.VMCreateGuide at localhost:4083	
		Thread [main] (Suspended (exception NoSuchMethodError))	
			TypeToken$TypeCollector<K>.sortKeysByValue(Map<K,V>, Comparator<? super V>) line: 1165	
			TypeToken$TypeCollector$3(TypeToken$TypeCollector<K>).collectTypes(Iterable<? extends K>) line: 1129	
			TypeToken$TypeCollector$3.collectTypes(Iterable<? extends K>) line: 1114	
			TypeToken$ClassSet.rawTypes() line: 664	
			Validator.validate(Object) line: 59	
			ResourceGroupsOperationsImpl.createOrUpdate(String, ResourceGroup) line: 375	
			VMCreateGuide.main(String[]) line: 208	
		Daemon Thread [Okio Watchdog] (Running)	
	D:\Java\jdk1.8.0_92\bin\javaw.exe (2016年6月22日 下午4:11:25)	
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~


it seems only client side code has something wrong, can you help out?

**Comment by martinsawicki** [comment]
Thanks for the investigation. What I would recommend though is not spend too much time on beta1 right now, as beta2 will come out at the end of June or so and will be radically different/simpler than anything that has come out before. Resource Groups, VM creation, NICs, VNets, PIPs, NSGs, STorage Accounts, Availability sets and Deployments are in beta2 --- these are all the pieces of functionality needed to create a simple, standalone VMs with basic networking, or deploy ARM templates. (not other areas). This is what's being worked on in the master branch right now. Coverage for other area, like the rest of networking, websites, etc will light up in the new model over the next few months.

**Comment by smartmaster** [comment]
hi @martinsawicki,
thanks for your update, I am looking forward to beta 2.
of course if it is an issue that can be quickly figured out, please give some advice; if not, i will wait and try beta 2.

regards.

**Comment by smartmaster** [comment]
hi @martinsawicki ,
when will the formal version 1.0.0 be released? 
will there be some breaking changes that make program written using beta version cannot work or even build?
will Java SDK try to align with the C# SDK as much as possible?

it will be great in case to share roadmap.

regards,

**Comment by jianghaolu** [comment]
We just released the beta2 version today. You can take a look at the sample of creating a VM here: https://github.com/Azure-Samples/compute-java-manage-vm/blob/master/src/main/java/com/microsoft/azure/management/compute/samples/ManageVirtualMachine.java.

**Comment by jianghaolu** [comment]
To answer your question:
> when will the formal version 1.0.0 be released? 
@selvasingh would be the right person to answer. For now I do not know since we are making some of the most radical changes to the SDK landscape since 0.6.
> will there be some breaking changes that make program written using beta version cannot work or even build?
Yes. But not to scare you, I think breaking changes from a really-hard-to-use previous version is a good thing. Let's be honest, 0.9 and even 1.0.0-beta1 has big usability issues. Hopefully you can see how we are addressing them in the sample I gave you above.
> will Java SDK try to align with the C# SDK as much as possible?
No. We share some technologies (e.g. AutoRest) and design philosophies but from bottom up Java SDK will be fairly different from the .NET SDK.

**Comment by smartmaster** [comment]
@jianghaolu ,
thank you very much for the update. Hope JAVA SDK gains my confidence.

I will close the beta1 issue for now.

regards.
