### ISSUE TITLE
should we use cached *Manager instances?

### ISSUE THREAD

**Issue by martinsawicki** [Azure/azure-sdk-for-java#829]
I noticed our current `*Manager` impls (e.g. `ComputeManager`), when they reference dependencies on other `*Manager`s, they create their own new instances of them. So for example, `Azure` rollup object instantiates references to all the `*Manager`s, including `ComputeManager` and `NetworkManager` explicitly. But then, `ComputeManager` instantiates a new reference to `NetworkManager` for its own needs. These are two different `NetworkManager` instances. 

Something feels fishy to me in this approach. I'm wondering if this should be changed so that each `Manager` becomes a singleton. That way, `ComputeManager` and `Azure` would both reference the same instance of `NetworkManager`. Any concerns about that?

**Comment by martinsawicki** [comment]
specifically, I'm thinking perhaps we could make `.authenticate()` get an already provided instance of the Manager, *if and only if* that instance was instantiated using the same restClient and subscription ID. Otherwise, it would replace the singleton with a new authenticated `*Manager` based on the new inputs.

Now, if two different places are instantiating the same `*Manager` but with different credentials, each still succeeds it's just that one will have a `*Manager` authenticated against whatever credentials it used, and the other will have its own instance with whatever credentials it used. 

So it wouldn't be exactly a singleton pattern - you can still have multiple instances as long as they are authenticated differently. I've changed the suibject of the issue to reflect that. It's more like a caching pattern, where only if you use the same creds as before, you get the same instance. Otherwise you get a new instance.

**Comment by martinsawicki** [comment]
and actually, the caching could perhaps be done only based on the subscriptionID, not the restClient?
(something still feels fishy to me in this though...)

**Comment by jianghaolu** [comment]
Also, you don't need any individual clients if you already created a roll-up client.

**Comment by Ahmad-Mahagna** [comment]
There are several ways to approach that if I understood you well.
In my point of view, we should use dependency injection pattern (setter injection) to instantiates *Manager with appropriate dependencies *Managers.

**Comment by praries880** [comment]
@jianghaolu Is this issue fixed? it has been referenced In a lot of commits.

**Comment by Petermarcu** [comment]
@joshfree @JonathanGiles can we confirm whether we need this issue open is this designed and alleviated in track 2?

**Comment by JonathanGiles** [comment]
Shifting assignee to @weidongxu-microsoft for review and potential closure w.r.t track two management plane libraries.

**Comment by weidongxu-microsoft** [comment]
Emm, still a valid question. Though very light-weighted (it shares the single HttpPipeline) and immutable (at least in expectation), `*Manager` still contains some `*Client`.

@xccc-msft @ChenTanyi for ideas.

**Comment by weidongxu-microsoft** [comment]
Current mgmt SDK appears stable so far, will close the issue unless we see the necessity to refactor.
