### ISSUE TITLE
[Azure Service Bus Queue Client do not mark messages to be completed]

### ISSUE THREAD

**Issue by ahmads-kainos** [Azure/azure-sdk-for-java#8338]
When messages have been received by the Azure Service Bus Client and after processing they are marked completed then they still are present in the queue and count on Azure dashboard for the session-handled queue does not go down.

The system does not throw any exceptions.

**To Reproduce**
1- Use the session aware Azure Service Bus queue.
2- Send messages to Azure Service Bus queue with various sessionsIds.
3- Receive the messages trough a queue client onMeassageAsync
4- After processing mark them completedAsync.

***Code Snippet***
```
private void registerSessionHandler(IQueueClient queueClient, ExecutorService executorService, String matchId)
      throws Exception {
    queueClient.registerSessionHandler(new ISessionHandler() {
      @Override
      public CompletableFuture<Void> onMessageAsync(IMessageSession iMessageSession,
          IMessage message) {
        logger.info("Message received");
        String messageId = message.getMessageId();

        if(matchId.equalsIgnoreCase(messageId)){
          return queueClient.completeAsync(message.getLockToken());
        }else{
          return queueClient.completeAsync(null);
        }
      }

      @Override
      public CompletableFuture<Void> OnCloseSessionAsync(IMessageSession iMessageSession) {
        return iMessageSession.renewSessionLockAsync();
      }

      @Override
      public void notifyException(Throwable throwable, ExceptionPhase exceptionPhase) {
        System.out.println("Exception " + exceptionPhase + "-" + throwable.getMessage());
      }
    }, new SessionHandlerOptions(3, false, Duration.ofMinutes(1)) ,executorService);
  }
```
It will be expected that those messages which have been marked completed should not be present in the queue anymore. Also the count on dashboard for the particular queue should go down as well.

**Setup (please complete the following information):**
 - OS: [ iOS]
 - IDE : [IntelliJ]
 - Version of the Library used for azure-spring-boot-bom, azure-servicebus-spring-boot-starter, azure-spring-boot-starter is 2.2.2.

**Comment by joshfree** [comment]
Thanks for reporting this issue @ahmads-kainos.  @yvgopal @hemanttanwar please take a look.

**Comment by yvgopal** [comment]
Same errors as explained in #8339 and #8340
