### ISSUE TITLE
[Azure Service Bus Queue Client for Session enabled queue do not receive messages in a loop]

### ISSUE THREAD

**Issue by ahmads-kainos** [Azure/azure-sdk-for-java#8339]
When messages have been received by the Azure Service Bus Client it stops consuming messages after it has consumed number of messages defined in the maxConcurrentSessions of SessionHandlerOption.

The system does not throw any exceptions.

**To Reproduce**
1- Use the session aware Azure Service Bus queue.
2- Send messages to Azure Service Bus queue with various sessionsIds.
3- Receive the messages trough a queue client onMeassageAsync
4- no more messages are received than the maxConcurrentSessions defined.

***Code Snippet***
```
private void registerSessionHandler(IQueueClient queueClient, ExecutorService executorService, String matchId)
      throws Exception {
    queueClient.registerSessionHandler(new ISessionHandler() {
      @Override
      public CompletableFuture<Void> onMessageAsync(IMessageSession iMessageSession,
          IMessage message) {
        logger.info("Message received");
        String messageId = message.getMessageId();

        if(matchId.equalsIgnoreCase(messageId)){
          return queueClient.completeAsync(message.getLockToken());
        }else{
          return queueClient.completeAsync(null);
        }
      }

      @Override
      public CompletableFuture<Void> OnCloseSessionAsync(IMessageSession iMessageSession) {
        return iMessageSession.renewSessionLockAsync();
      }

      @Override
      public void notifyException(Throwable throwable, ExceptionPhase exceptionPhase) {
        System.out.println("Exception " + exceptionPhase + "-" + throwable.getMessage());
      }
    }, new SessionHandlerOptions(3, false, Duration.ofMinutes(1)) ,executorService);
  }
```
It will be expected that all the messages in the queue will be received.

**Setup (please complete the following information):**
 - OS: [ iOS]
 - IDE : [IntelliJ]
 - Version of the Library used for azure-spring-boot-bom, azure-servicebus-spring-boot-starter, azure-spring-boot-starter is 2.2.2.

**Comment by joshfree** [comment]
Thanks for reporting this issue @ahmads-kainos.  @yvgopal @hemanttanwar please take a look.

**Comment by yvgopal** [comment]
You are not calling completeAsync on the session. I have detailed what is wrong with that code in #8340. Make that correction and it should work just fine. Also you should not use `renewSessionLock` in `onCloseSessionAsync` . Please read the documentation and go through the samples at [https://github.com/Azure/azure-service-bus/tree/master/samples/Java](https://github.com/Azure/azure-service-bus/tree/master/samples/Java)
