### ISSUE TITLE
Text Analytics Readme description of Sentiment analysis is reflecting v2 and not v3.

### ISSUE THREAD

**Issue by maririos** [Azure/azure-sdk-for-java#8347]
The sentence 
```
Scores closer to 1 indicate positive sentiment, while scores closer to 0 indicate negative sentiment. 
``` 
is no longer correct.

Either remove or change according to product documentation [here ](https://docs.microsoft.com/en-us/azure/cognitive-services/text-analytics/how-tos/text-analytics-how-to-sentiment-analysis?tabs=version-3#sentiment-scoring)

cc: @mssfang

**Comment by maririos** [comment]
@mssfang do you think we can include this change for P3?

**Comment by mssfang** [comment]
@maririos  Yes, it can be included in the P3.
