### ISSUE TITLE
Error setting up forwardTo on a subscription: BR0012The specified value is in an invalid format.

### ISSUE THREAD

**Issue by GideonLeGrange** [Azure/azure-sdk-for-java#8350]
**Describe the bug**

I think I have found a bug when setting up an auto-forward from one topic to another. When I create a `SubscriptionDescription` and use `setForwardTo()` to set the name of a forward topic, it raises the following error when calling `createSubscription()` on `ManagementClient`:

`java.lang.IllegalArgumentException: BR0012The specified value is in an invalid format`

***Exception or Stack Trace***

```
Exception in thread "main" com.microsoft.azure.servicebus.primitives.ServiceBusException: java.lang.IllegalArgumentException: BR0012The specified value is in an invalid format.
Parameter name: ForwardTo. TrackingId:0a9fee77-f78b-419b-baa0-ff4ba177c852_G4, SystemTracker:fivenines-test:Topic:input, Timestamp:2020-02-20T19:26:11
	at com.microsoft.azure.servicebus.management.ManagementClientAsync.validateHttpResponse(ManagementClientAsync.java:1117)
	at com.microsoft.azure.servicebus.management.ManagementClientAsync.lambda$sendManagementHttpRequestAsync$21(ManagementClientAsync.java:1053)
	at java.base/java.util.concurrent.CompletableFuture.uniHandle(CompletableFuture.java:930)
	at java.base/java.util.concurrent.CompletableFuture$UniHandle.tryFire(CompletableFuture.java:907)
	at java.base/java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:478)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)

```

**To Reproduce**

* Have two topics set up called `input` and `output`
* Create a new subscription on `input` called `subs` and use `setForwardTo("output")` to set it to forward to `output`

***Code Snippet***
Add the code snippet that causes the issue.

```java

import com.microsoft.azure.servicebus.management.ManagementClient;
import com.microsoft.azure.servicebus.management.SubscriptionDescription;
import com.microsoft.azure.servicebus.management.TopicDescription;
import com.microsoft.azure.servicebus.primitives.ConnectionStringBuilder;
import com.microsoft.azure.servicebus.primitives.ServiceBusException;


public class Test {
   private static final String MY_CONNECTION_STRING = ""; // fill in yours

    public static void main(String...args) throws ServiceBusException, InterruptedException {

        ManagementClient client = new ManagementClient(new ConnectionStringBuilder(MY_CONNECTION_STRING));
        TopicDescription input = client.getTopic("input");
        TopicDescription output = client.getTopic("output");

        SubscriptionDescription sub = new SubscriptionDescription(input.getPath(), "subs");
        sub.setForwardTo(output.getPath());
        sub = client.createSubscription(sub);
    }

}
```

**Expected behavior**

I expect it to set up a subscription called `subs` on topic `input` that has a forward-to pointing to topic `output`, and not raise an exception  

**Setup (please complete the following information):**
 - OS: MacOS 13.0.5
 - IDE : IntelliJ 2019.03
 - Library versions 3.1.1 and 3.1.4 

**Information Checklist**
Kindly make sure that you have added all the following information above and checkoff the required fields otherwise we will treat the issuer as an incomplete report
- [x] Bug Description Added
- [x] Repro Steps Added
- [x] Setup information Added

**Comment by joshfree** [comment]
Thanks for reporting this issue in the Track1 Service Bus SDK for Java @GideonLeGrange.

@yvgopal @hemanttanwar can you please follow up?

**Comment by yvgopal** [comment]
I am investigating this.

**Comment by pesua** [comment]
Hello
Are there any news? I'm blocked by this issue too.
