### ISSUE TITLE
New Azure Key Vault release to mitigate dependency vulnerabilities 

### ISSUE THREAD

**Issue by ulvii** [Azure/azure-sdk-for-java#8355]
Hi team,

There is a high severity vulnerability in com.microsoft.azure:azure-keyvault, because the dependencies  of the 1.2.2 version of the library still use com.fasterxml.jackson.core:jackson-databind:2.9.9.

azure-keyvault-cryptography and azure-keyvault-webkey are the libraries that directly use the vulnerable jackson-databind:2.9.9.

We are requesting new releases that mitigate these issues. It would also be a good idea to update all the dependencies of the libraries to their latest version.

**Comment by ulvii** [comment]
#2970, #3602, #3915.

**Comment by conniey** [comment]
Released as: https://search.maven.org/artifact/com.microsoft.azure/azure-keyvault/1.2.3/jar
