### ISSUE TITLE
Sync APIs should support HTTP request cancellation

### ISSUE THREAD

**Issue by srnagar** [Azure/azure-sdk-for-java#8357]
During the Azure Core HTTP pipeline tech talk, there was a proposal to add the ability to cancel a HTTP request from sync clients. For users of Async clients, a request can be canceled by unsubscribing from the publisher to cancel the request but sync APIs don't have the ability to cancel a request.

**Comment by anuchandy** [comment]
Closing this one, we're not going to implement this for sync API.
