### ISSUE TITLE
UserTokenCredentials does not do a proper lifetime management of executors.

### ISSUE THREAD

**Issue by apogrebnyak** [Azure/azure-sdk-for-java#836]
Look at method acquireAccessToken, on line 136 it creates a newSingleThreadExecutor and never shuts it down.

Over time, this can lead to resource leak.

https://github.com/Azure/azure-sdk-for-java/blob/603802dd9aad440a101437fb98eb82bb625e1b84/runtimes/azure-client-authentication/src/main/java/com/microsoft/azure/credentials/UserTokenCredentials.java

**Comment by jianghaolu** [comment]
Good catch! We've fixed in beta3: https://github.com/Azure/autorest-clientruntime-for-java/blob/v1.0.0-beta3/azure-client-authentication/src/main/java/com/microsoft/azure/credentials/UserTokenCredentials.java.

Thanks.
