### ISSUE TITLE
[QUERY] Unsupported check for File/Directory/Blob existence

### ISSUE THREAD

**Issue by yenhanshih** [Azure/azure-sdk-for-java#8381]
**Query/Question**
In the v8 version of Azure Storage SDK, it seems like you're able to check for a File/Directory/Blob for existence via the exist() method. However in the v12 library, it looks like there is nothing that supports it. I've read somewhere that using the getProperties() is the correct way to check for existence, but all it does is throw a 404. This makes it difficult to implement recursive creation of directories and files and implementing overwrite logic without try catching 404s.

***Why is this not a Bug or a feature Request?***
I might be missing something about the design principles for the new SDK as to why this may have not been considered for implementation in the v12 version of the SDK.

**Setup (please complete the following information if applicable):**
 - OS: Windows 10
 - IDE : IntelliJ
 - Version of the Library used: azure-storage-file-share v12.2.0
 
 **Information Checklist**
- [x] Query Added
- [x] Setup information Added

**Comment by gapra-msft** [comment]
Hi @yenhanshih 

We do support exists in azure-storage-blob and azure-storage-file-datalake, so it does not go against any of our design principles. It just looks like we haven't come around to adding it for  azure-storage-file-share. 

I've marked your issue as a feature request and we will schedule some time to get this feature in.

**Comment by saragluna** [comment]
Hi @gapra-msft 

I need these check methods too. I saw the changes have been merged to the master branch and when will there be a release for the azure-storage-file-share?

**Comment by rickle-msft** [comment]
@saragluna We are planning a release for this week. Shares should be getting upgraded to 12.4.0

**Comment by saragluna** [comment]
@rickle-msft 

Glad to know that. Is there a daily build with which I could try these methods before the release?

**Comment by rickle-msft** [comment]
@mikeharder I think was working on something like this? Mike, can you please comment if we have daily builds going and how to access them?

**Comment by mikeharder** [comment]
@saragluna, @rickle-msft: We do have nightly builds of Java packages, instructions here:

https://github.com/Azure/azure-sdk-for-java/blob/master/CONTRIBUTING.md#nightly-package-builds
