### ISSUE TITLE
Dependency Upgrade to fix CVE Vulnerabilities

### ISSUE THREAD

**Issue by raghuvaran** [Azure/azure-sdk-for-java#8440]
Currently the following dependency has 12 CVE vulnerabilities and there is a latest version [1.7.2](https://mvnrepository.com/artifact/com.microsoft.azure/azure-client-authentication/1.7.2) of it that fixes these issues. Please bump up the version.

```xml
<dependency>
      <groupId>com.microsoft.azure</groupId>
      <artifactId>azure-client-authentication</artifactId>
      <version>1.7.0</version>
</dependency>
```

**Comment by joshfree** [comment]
@conniey @hemanttanwar @yvgopal PTAL

**Comment by conniey** [comment]
@alzimmermsft is updating this as part of: https://github.com/Azure/azure-sdk-for-java/issues/8270

**Comment by conniey** [comment]
Thanks for working on this! I was able to upgrade and consolidate multiple dependencies. :)
