### ISSUE TITLE
Use dynamic resource provisioning for live tests (test-resources.json)

### ISSUE THREAD

**Issue by danieljurek** [Azure/azure-sdk-for-java#8470]
Live tests can be run with greater parallelization by having the pipelines automatically provision and de-provision Cosmos DB accounts per-test-execution. Use the `test-resources.json` file to accomplish this. 

Instructions for creating test-resources.json ARM templates: https://dev.azure.com/azure-sdk/internal/_wiki/wikis/internal.wiki/48/Create-a-new-Live-Test-pipeline?anchor=test-resources.json

**Comment by kushagraThapar** [comment]
@moderakh we are tracking CI improvement here - specifically - running them in parallel - by provisioning cosmosdb resources on the fly. 
Please provide any helpful information if you have (which I know you do ;) )

**Comment by moderakh** [comment]
We run SDK tests against different CosmosDB accounts with different set of configuration.

The requirements are:
1. the provisioned cosmosdb endpoints and DevOops CI agent pool have to be collocated in the same azure region.
2. there are a few different cosmosdb accounts configuration.
3. our tests are written in a parametrized way, the accounts credentials and other accounts config can be passed to the test at runtime.

I had a set of azure cli command that I used a while back for account provisioning. The following is not a complete/uptodate list. Just so you can get a sense of how accounts can be created at runtime for our CIs:

```
#Session Single Region
az cosmosdb create -g java-azure-cosmosdb -n session-singleregion-java --default-consistency-level Session --locations centralus=0

#Session Multi Region
az cosmosdb create -g java-azure-cosmosdb -n session-multiregion-java --default-consistency-level Session --locations centralus=0 northcentralus=1

#Strong Single Region
az cosmosdb create -g java-azure-cosmosdb -n strong-singleregion-java --default-consistency-level Strong --locations centralus=0

#Strong Multi Region
az cosmosdb create -g java-azure-cosmosdb -n strong-multiregion1-java --default-consistency-level Strong --locations centralus=0 northcentralus=1
az cosmosdb create -g java-azure-cosmosdb -n strong-multiregion2-java --default-consistency-level Strong --locations centralus=1 northcentralus=0

#Multi Master Multi Region
az cosmosdb create -g java-azure-cosmosdb -n multimaster-multiregion-java --default-consistency-level Session --locations centralus=0 northcentralus=1  --enable-multiple-write-locations true

#Multi Master Single Region
az cosmosdb create -g java-azure-cosmosdb -n multimaster-singleregion-java --default-consistency-level Session --locations centralus=0 --enable-multiple-write-locations true
```

**Comment by danieljurek** [comment]
MacOS agents do not not map directly to Azure regions. Mac agents are hosted within the US -- https://docs.microsoft.com/en-us/azure/devops/organizations/security/data-location?view=azure-devops#mac-builds

**Comment by moderakh** [comment]
@danieljurek can we use Linux agent? no specific reason here to use macos. 

And given the above piece of info we should move to a agent pool which support collocation. @kushagraThapar

**Comment by kushagraThapar** [comment]
This is done.
