### ISSUE TITLE
[QUERY] Trying to find the LUN value for each VM type

### ISSUE THREAD

**Issue by TheGreatHegazi** [Azure/azure-sdk-for-java#8478]
**Query/Question**
A clear and concise ask/query.
I am currently trying to validate whether the LUN that the user of my application put is a valid one. 
In the documents around the azure api, it mentions that the LUN ranges are specific to VM sizes. 
I was unable to find it in the capabilities of the VM that is exposed by the cache. 
<img width="806" alt="Screen Shot 2020-02-25 at 4 08 28 PM" src="https://user-images.githubusercontent.com/35641875/75288076-92327c00-57e9-11ea-88b7-31dc7a79fa12.png">
Is there a way I can validate the LUN value that is inputed by the user? 

***Why is this not a Bug or a feature Request?***
A clear explanation of why is this not a bug or a feature request?
because it might be exposed somewhere else in the api that I did not look at.

**Setup (please complete the following information if applicable):**
 - OS: Mac OSX
 - IDE :  IntelliJ
 - Version of the Library used (1.31.0)
 
 **Information Checklist**
 Kindly make sure that you have added all the following information above and checkoff the required fields otherwise we will treat the issuer as an incomplete report
- [👍 ] Query Added
- [ 👍] Setup information Added

**Comment by yaohaizh** [comment]
@TheGreatHegazi which SDK are you using?

**Comment by TheGreatHegazi** [comment]
This is currently the maven dependency that I am using. 

![image](https://user-images.githubusercontent.com/35641875/75356543-159dad00-587e-11ea-8569-d99677eedf7c.png)

Sorry for the confusion.

**Comment by yaohaizh** [comment]
@TheGreatHegazi I don't find any of our class named `ComputeSkuCacheFactory` on our lib. Does you wrap any of the classes?

**Comment by TheGreatHegazi** [comment]
@yaohaizh - Yes they are wrappers around Azure SDK objects. The objective is to find the right range of LUN numbers that can be used for attaching disks for specific machine types.
 
The given screenshot is an example of trying to find this info inside an instance of the ` com.microsoft.azure.management.compute.ComputeSku`'s capabilities

On the microsoft documentation for the disk attach it says that the range of LUN is specific to each machine type not actually from 0-399 as stated by the UI when attempting to attach a disk on the azure portal. 

Is there a way somehow within the SDK object where we can get the correct range ?

**Comment by yungezz** [comment]
hi @xccc-msft could you pls help to follow up on this issue? thanks

**Comment by xccc-msft** [comment]
@TheGreatHegazi Will the `MaxDataDiskCount` help on this? I just add label of `Service Attention` so the service team would help answer your question. Thanks.

**Comment by Vaibhav-Agar** [comment]
@TheGreatHegazi the LUN can only be between 0 & 63 as the max number of data disk any Azure VM supports today is 63. So, as @xccc-msft recommended earlier. You can use the MaxDataDiskCount property to see the values of LUN that are acceptable for that VM size. Closing the issue now.
