### ISSUE TITLE
[QUERY]  azure-keyvault 1.x vs azure-security-keyvault-* 4.x

### ISSUE THREAD

**Issue by magooster** [Azure/azure-sdk-for-java#8493]
**Query/Question**
There seems to be multiple Java  client libraries for accessing keys within an Azure Key Vault, whilst I have previously been using azure-keyvault the new examples seem to direct users to the azure-security-keyvault-* libraries. Is azure-keyvault going to be deprecated in favour of the newer libraries?
Should projects being using the latter going forwards? IMHO: They're not equivalent at this point, which might be by design.

***Why is this not a Bug or a feature Request?***
General question on usage of the libraries.

**Setup (please complete the following information if applicable):**
 N/A
 
 **Information Checklist**
 Kindly make sure that you have added all the following information above and checkoff the required fields otherwise we will treat the issuer as an incomplete report
- [ x] Query Added
- [ x] Setup information Added

**Comment by joshfree** [comment]
Thanks for posting the question @magooster.  Yes, the v4.x azure-security-keyvault-* libraries are the latest supported SDK libraries for KeyVault.  We do recommend upgrading to this latest stable, supported release.  More information can be found  here https://techcommunity.microsoft.com/t5/azure-sdk/february-2020-unified-sdk-release/ba-p/1174661 and also on the AzureSDK twitter feed here https://twitter.com/AzureSdk/status/1229856571020083200.

We have a work item to publish relocation POMs to Maven to make the upgrade path more clear.  https://github.com/Azure/azure-sdk-for-java/issues/7968

@g2vinay can you please follow up with more details on track2?

**Comment by g2vinay** [comment]
@magooster 
Thank you for your query and actively trying out our 4.x KV libraries, really appreciate the effort for identifying potential issues in our Track 2 SDKs.

Yes, 4.x azure-security-keyvault-libraries are the ones which we recommend going forward.
4.x azure-security-keyvault-libraries are part of our Track 2 SDKs, which are completely redesigned to offer better and friendly user experience to our developers.
It supports pluggable HTTP clients , runs on a re-designed java runtime and offers better performance compared to older Track 1 SDKs.

Let us know, if you've any more questions.
