### ISSUE TITLE
[BUG] Missing SqlElasticPoolBasicEDTUs value for 300 DTUs

### ISSUE THREAD

**Issue by renutz** [Azure/azure-sdk-for-java#8494]
**Describe the bug**
According to the Azure portal it is possible to configure a Basic SQL Server Pool with 300 DTUs

**To Reproduce**
On https://github.com/Azure/azure-libraries-for-java/blob/master/azure-mgmt-sql/src/main/java/com/microsoft/azure/management/sql/SqlElasticPoolBasicEDTUs.java there is no ENUM for eDTU_300

**Comment by joshfree** [comment]
Thanks for posting the question @renutz.  The right folks from the Management Plane SDK team will follow up shortly.

/cc @milismsft

**Comment by yaohaizh** [comment]
@renutz because the current version of Java SDK for SQL fixed on API version for composite v1 for some historical reason.  

We will fix this issue on track 2 SDK.

**Comment by yaohaizh** [comment]
These are defined value for DTU resource limits: https://docs.microsoft.com/en-us/azure/sql-database/sql-database-dtu-resource-limits-elastic-pools
