### ISSUE TITLE
[QUERY] How to update a SKU of a SQL Server Pool?

### ISSUE THREAD

**Issue by renutz** [Azure/azure-sdk-for-java#8495]
**Query/Question**
I think the API is missing the capability to update a SQL Server Pool between DTU tiers. Skus: Basic, Standard, Premium.

***Why is this not a Bug or a feature Request?***
The documentation of updating a SQL Server Pool is clear about the possibility on changing between tiers (Basic, Standard and Premium) on the DTU model.

https://docs.microsoft.com/en-us/rest/api/sql/elasticpools/update

On the NodeJS SDK the functionality is available:

https://docs.microsoft.com/en-us/cli/azure/sql/elastic-pool?view=azure-cli-latest#az-sql-elastic-pool-update

--edition --tier -e
The edition component of the sku. Allowed values include: Basic, Standard, Premium, GeneralPurpose, BusinessCritical.

**Comment by joshfree** [comment]
Thanks for posting the issue @renutz. @milismsft can you please follow up?

**Comment by yaohaizh** [comment]
@renutz because the current version of Java SDK for SQL fixed on API version for composite v1 for some historical reason.  

We will fix this issue on track 2 SDK.
