### ISSUE TITLE
[QUERY] Is there a way I can disable logs from the AuthenticationAuthority class

### ISSUE THREAD

**Issue by Shabirmean** [Azure/azure-sdk-for-java#8501]
**Query/Question**
I am consuming the Azure SDK for a project I am working on. However, I have set the LogLevel in the Azure controller to **NONE**.
```java
Azure.configure().withLogLevel(LogLevel.NONE).authenticate(credentials);
```
But still get a bunch of a logs from the class `c.m.a.adal4j.AuthenticationAuthority`
```
2020-02-26 15:41:46,991 [pool-1-thread-37] INFO  c.m.a.adal4j.AuthenticationAuthority - [Correlation ID: 72e7c78f-67b6-4a95-b164-9f366cc5db91] Instance discovery was successful
```

I want to know how can I block these logs.

***Why is this not a Bug or a feature Request?***
- Because I am not sure if there is some way in Azure already that enables me to do this and its just that I am unaware of it.

**Setup (please complete the following information if applicable):**
 - OS: MacOS
 - IDE : IntelliJ
 - 1.31.0
 
 **Information Checklist**
- [ ✅ ] Query Added
- [ ✅ ] Setup information Added

**Comment by joshfree** [comment]
Thanks for the question @Shabirmean. @yaohaizh can you please follow up? 

/cc @jianghaolu for any historical context on adal4j

**Comment by yaohaizh** [comment]
@jianghaolu does the adal4j log separate from the SDK logging? Can we control from the client runtime authentication side? Thanks

**Comment by Shabirmean** [comment]
Hi,

Is there any updates on this?

**Comment by weidongxu-microsoft** [comment]
This is not SDK feature. It only depends on the logging SDK and its config.

E.g. for slf4j simple, one can change log level
```
System.setProperty(org.slf4j.impl.SimpleLogger.DEFAULT_LOG_LEVEL_KEY, "WARN");
```

**Comment by FireDrunk** [comment]
My solution for this issue was:
```logging.level.com.microsoft.aad.adal4j.AuthenticationAuthority=WARN```
in `application.properties`
