### ISSUE TITLE
shouldn't VMSizes be a full fledged collection?

### ISSUE THREAD

**Issue by martinsawicki** [Azure/azure-sdk-for-java#856]
Right now, the only way to get to virtual machine sizes is via 
`VirtualMachines.listAvailableSizesByRegion(region)`. 
if `VirtualMachineSizes` were a full fledged collection, it could be visible as `VirtualMachines#sizes()`, and the typical collection things would apply to it:
* `virtualMachines.sizes().listByRegion(Region)`
* `virtualMachines.sizes().getByName(Name)`
etc.  Especially the `get` part is interesting, since a `VMSize` has interesting info on it.
Also, this opens up possibilities to offer other alternatives to listBy* and getBy* as they become available in the API.

**Comment by martinsawicki** [comment]
submitted a PR for doing that: https://github.com/Azure/azure-sdk-for-java/pull/857
Now that we have WrappersImpl, things like that are easy and quite elegant to achieve.
I think we can do the same with a few other similar lists (Publishers, etc)

**Comment by jianghaolu** [comment]
Done.
