### ISSUE TITLE
[Design] make virtualMachineImages().listByRegion(regionName) lazy

### ISSUE THREAD

**Issue by anuchandy** [Azure/azure-sdk-for-java#860]
virtualMachineImages().listByRegion(regionName) method call took around 14 minutes to return, in my subscription the list contains around 2400 images. This will be a bad user experience.

Improvement:

We can improve this by extending PagedList idea, i.e. virtualMachineImages().listByRegion(regionName) should return a PagedList immediately. Once user starts iterating though the list then we need to lazy load the images.

This involves lazy loading offers, skus and images.

**Comment by martinsawicki** [comment]
yes, I think that'd be great. Perhaps we can simply create a subclass of PagedList for this specific purpose (VirtualMachineImagesPagedList?) that does this?   What do you think would be a good level to fetch the images?  Perhaps there is some number we can play with, like 25 images at a time, and then snap to the nearest publisher (so it could be a more than 25 for a given call), but that way the paged list could track the progress internally by publisher (i.e. next page link would represent the next publisher to fetch)?

**Comment by anuchandy** [comment]
yes, exactly,  I do have a prototype. As you mentioned it basically track the progress internally, not just for publishers but also for offers and skus as well. We made it generic so that this can be reused in future, I don't have a good name for this class, currently named as `ChildListFlattener`, it takes a lazy paged list of parents and provide a flattened view of its children as lazy paged list. We can use composition and flatten children in any level (publisher -> offer -> sku -> images)

Some other use of this class are:

1.consider a resource provider that doesn't have server support for list (`listAll`) but only listByGroup, in this case we can use this class to enable `list` i.e. lazy load the resource groups and then lazy load resources in each of it.

2. Currently listing image is only supported via virtualMachineImages().listByRegion(regionName), with this class we could support that in publisher level and offer level (images in more granular level)

i will send the PR soon.

**Comment by anuchandy** [comment]
To answer your question regarding the good level of fetching.. We could completely depends on server.. i.e. load the first page of publishers, as user iterates load first page of offers from first publisher, first page of skus from first offer then first page of images in first sku page and so on...

**Comment by anuchandy** [comment]
![imageslist1-3](https://cloud.githubusercontent.com/assets/1471612/16179134/fe9b1c60-3611-11e6-93af-dd3efdaa1863.gif)

**Comment by martinsawicki** [comment]
interesting!

**Comment by martinsawicki** [comment]
we just gotta be careful not to make it to chatty either. We probably shouldn't fetch the next link with only one item. That's why I was suggesting having some sort of minimum to fetch, and then snap to some natural boundary. We could then tweak the minimum (or have it user-controlled through some config param). Thoughts?

**Comment by anuchandy** [comment]
Yes, agree with you, current implementation is chatty, let me try to improve this as you suggested.

**Comment by anuchandy** [comment]
Discussed this further and came to a conclusion that minimum fetch is not really saving time due to the way API is designed. Implementation has been merged hence closing.
