### ISSUE TITLE
CosmosSkip: Enable maven-compiler-plugin on Cosmos SDK v4

### ISSUE THREAD

**Issue by kushagraThapar** [Azure/azure-sdk-for-java#8616]
Currently maven-compiler-plugin is skipped on Cosmos SDK v4, need to enable this back

      <plugin>
        <groupId>org.apache.maven.plugins</groupId>
        <artifactId>maven-compiler-plugin</artifactId>
        <version>3.8.1</version> 
        <configuration>
          <source>1.8</source>
          <target>1.8</target>
          <failOnWarning>false</failOnWarning>
        </configuration>
      </plugin>

**Comment by JonathanGiles** [comment]
This should be done prior to GA so that we can remove all compiler warnings.

**Comment by kushagraThapar** [comment]
This has been done, closing it.
