### ISSUE TITLE
[BUG] Table not formatted correctly in docs

### ISSUE THREAD

**Issue by jongio** [Azure/azure-sdk-for-java#8624]
Here: https://azuresdkdocs.blob.core.windows.net/$web/java/azure-identity/1.1.0-beta.1/index.html

|credential class|identity|configuration |-|-|- |DefaultAzureCredential|service principal or managed identity|none for managed identity; environment variables for service principal |ManagedIdentityCredential|managed identity|ManagedIdentityCredentialBuilder |EnvironmentCredential|service principal|environment variables |ClientSecretCredential|service principal|ClientSecretCredentialBuilder |ClientCertificateCredential|service principal|ClientCertificateCredentialBuilder |DeviceCodeCredential|user account|DeviceCodeCredentialBuilder |InteractiveBrowserCredential|user account|InteractiveBrowserCredentialBuilder |UsernamePasswordCredential|user account|UsernamePasswordCredentialBuilder

![image](https://user-images.githubusercontent.com/2163001/75611124-86d29f80-5acc-11ea-96f9-6cb7038bfc29.png)

Should be like this:
https://github.com/Azure/azure-sdk-for-java/blob/master/sdk/identity/azure-identity/README.md#creating-a-service-principal-with-the-azure-cli

![image](https://user-images.githubusercontent.com/2163001/75611126-8b975380-5acc-11ea-9215-e1eef68f8235.png)

**Comment by drewwmercer** [comment]
Is this still up for grabs?

**Comment by jongio** [comment]
Yes, this is still an issue.

**Comment by JonathanGiles** [comment]
The issue here is that markdown is not support in JavaDoc - it should be converted to using HTML tables.

**Comment by jain-shivangi** [comment]
Can someone please review my path - https://github.com/Azure/azure-sdk-for-java/pull/12351
This is my first open source contrbution :)
