### ISSUE TITLE
[BUG] Sample references keys.model.Key; doesn't compile.

### ISSUE THREAD

**Issue by jongio** [Azure/azure-sdk-for-java#8625]
Here: 
https://github.com/Azure/azure-sdk-for-java/tree/master/sdk/keyvault/azure-security-keyvault-keys#create-a-key

Uses:
`import com.azure.security.keyvault.keys.models.Key;`

The above pom.xml, includes

```xml
<dependency>
    <groupId>com.azure</groupId>
    <artifactId>azure-security-keyvault-keys</artifactId>
    <version>4.2.0-beta.1</version>
</dependency>
```

Error in VS Code
![image](https://user-images.githubusercontent.com/2163001/75612070-2a27b280-5ad5-11ea-8aa7-ed3f90a160cc.png)

I had to add the following to get it to run:

```java
import com.azure.identity.DefaultAzureCredentialBuilder;
import com.azure.security.keyvault.keys.KeyClientBuilder;
import com.azure.security.keyvault.keys.models.*;
import com.azure.security.keyvault.keys.KeyClient;
import java.time.OffsetDateTime;
```

**Comment by vcolin7** [comment]
Fixed by #10113 :)
