### ISSUE TITLE
[FEATURE REQ] Support setAuthorityHost with CredentialBuilderBase

### ISSUE THREAD

**Issue by jongio** [Azure/azure-sdk-for-java#8626]
Right now, it doesn't look like you can call setAuthorityHost with DefaultAzureCredentialBuilder:
https://github.com/Azure/azure-sdk-for-java/blob/master/sdk/identity/azure-identity/src/main/java/com/azure/identity/DefaultAzureCredentialBuilder.java

Which implements CredentialBuilderBase

CredentialBuilderBase doesn't expose setAuthorityHost
https://github.com/Azure/azure-sdk-for-java/blob/master/sdk/identity/azure-identity/src/main/java/com/azure/identity/CredentialBuilderBase.java

EnvironmentCredentialBuilder does expose setAuthorityHost

https://github.com/Azure/azure-sdk-for-java/blob/master/sdk/identity/azure-identity/src/main/java/com/azure/identity/EnvironmentCredentialBuilder.java

I recommend implementing this at the CredentialBuilderBase level.

Because ManagedIdentityCredential and other credential classes need this as well

https://github.com/Azure/azure-sdk-for-java/blob/master/sdk/identity/azure-identity/src/main/java/com/azure/identity/ManagedIdentityCredentialBuilder.java

> ! This is currently blocking use of DefaultAzureCredentialBuilder with other clouds, such as Azure Government.

**Comment by jongio** [comment]
Workaround using reflection:

```java
IdentityClientOptions options = new IdentityClientOptions().setAuthorityHost("https://login.microsoftonline.us/");
DefaultAzureCredentialBuilder cred = new DefaultAzureCredentialBuilder();
Field identityClientOptions = cred.getClass().getSuperclass().getDeclaredField("identityClientOptions");
identityClientOptions.setAccessible(true);
identityClientOptions.set(cred, options);

KeyClient keyClient = new KeyClientBuilder().vaultUrl(dotenv.get("AZURE_KEYVAULT_URL"))
                .credential(cred.build()).buildClient();
```


Or use EnvironmentCredentialBuilder instead of DefaultAzureCredentialBuilder
```java
 KeyClient keyClient = new KeyClientBuilder().vaultUrl(dotenv.get("AZURE_KEYVAULT_URL"))
  .credential(new EnvironmentCredentialBuilder().authorityHost("https://login.microsoftonline.us/").build()).buildClient();
```

**Comment by g2vinay** [comment]
This Issue was resolved in this PR: https://github.com/Azure/azure-sdk-for-java/pull/8765
The authorityHost setter was added to DefaultAzureCredentialBuilder.
MI credential doesn't consume authHost, so that's still excluded.
