### ISSUE TITLE
Clarify REAME for Azure Storage Blob client

### ISSUE THREAD

**Issue by devoto13** [Azure/azure-sdk-for-java#8628]
**Query/Question**

Please add a description of what people are supposed to put in `<your-storage-account-url>` mentioned multiple times in [Azure Storage Blob client README](https://github.com/Azure/azure-sdk-for-java/tree/master/sdk/storage/azure-storage-blob).

It is mentioned multiple times throughout the example, but the value people expected to put there is never described. Found it in the [migration guide](https://github.com/Azure/azure-sdk-for-java/blob/master/sdk/storage/azure-storage-blob/migrationGuides/V8_V12.md) and it is absolutely not obvious, so would be good to add a section on where to get it, similar to how access token is described.

***Why is this not a Bug or a feature Request?***
It is a documentation improvement request, not a bug or a feature for the library itself.

**Setup (please complete the following information if applicable):**
Not applicable.
 
 **Information Checklist**
 Kindly make sure that you have added all the following information above and checkoff the required fields otherwise we will treat the issuer as an incomplete report
- [x] Query Added
- [x] Setup information Added

**Comment by gapra-msft** [comment]
Hi @devoto13 

Thanks for the suggestion, we'll take some time and clarify the documentation provided in the READMEs.
