### ISSUE TITLE
Add Client-Request-Id Transform

### ISSUE THREAD

**Issue by alzimmermsft** [Azure/azure-sdk-for-java#8678]
Currently, the interface layer generates with a `@HeaderParam("client-request-id") UUID clientRequestId` parameter in all service methods. Swagger transforms should be added so this generates with a header name of `x-ms-client-request-id`. This change should happen in tandem with #8502 where the `RequestIdPolicy` should be updated to set `x-ms-client-request-id` as well.

**Comment by sima-zhu** [comment]
Swagger will change the HeadParam. Need to change corresponding field in builder or related classes.

**Comment by sima-zhu** [comment]
It has already been addressed from swagger.
