### ISSUE TITLE
Add Accept Header Swagger Transform

### ISSUE THREAD

**Issue by alzimmermsft** [Azure/azure-sdk-for-java#8680]
Currently, the `Document` APIs will use the default `Accept` header used by the service (`application/json;odata.metadata=minimal`). The `Document` interface should be updated to add an `Accept` header into each request, it should use the value `application/json;odata.metadata=none`. No APIs in the client layer should expose this configuration and it should always default to `application/json;odata.metadata=none`.

**Comment by sima-zhu** [comment]
Addressed the issue after adopting search swagger.
