### ISSUE TITLE
Update Build Matrix NOT to use Variable Named OSName

### ISSUE THREAD

**Issue by scbedd** [Azure/azure-sdk-for-java#8684]
![image](https://user-images.githubusercontent.com/45376673/75817492-06ba6d00-5d4c-11ea-88d7-02ef79d53bc7.png)

Clean it up!

**Comment by weshaggard** [comment]
Duplicate of https://github.com/Azure/azure-sdk-tools/issues/364

**Comment by scbedd** [comment]
Closing as duplicate.
