### ISSUE TITLE
Support sending multipart/form-data in RestProxy

### ISSUE THREAD

**Issue by jianghaolu** [Azure/azure-sdk-for-java#8702]
- Add a `@PartParam` and parse it in SwaggerMethodParser
- Send multipart/form-data in RestProxy

**Comment by alzimmermsft** [comment]
@jianghaolu do you have any specific service scenarios this could be tested against to verify correctness?

**Comment by jianghaolu** [comment]
Most cognitive services accept multipart/form-data as input, e.g.: https://github.com/Azure/azure-rest-api-specs/blob/2e7ca21a5ad6f749e5bd453580f1c31c1d99b4e6/specification/cognitiveservices/data-plane/ComputerVision/stable/v1.0/ComputerVision.json#L563.

**Comment by alzimmermsft** [comment]
The implementation of `multipart/form-data` should follow the specification laid out in [RFC 7578](https://tools.ietf.org/html/rfc7578). Based on initial review of the specification the following options should exist on `@PartParam`:

| Option Name | Required | Default (if not required) | Explanation |
| --------------- | ---------- | -------------------------- | ------------- |
| Name | Yes | N/A | Name of the form field, configures `name` in the part `Content-Disposition` header |
| Filename | No | None | Name of a file included in the form, configures `filename` in the part `Content-Disposition` header |
| ContentType | No | `text/plain` | The `Content-Type` of the part, if the part is a file this will default to `application/octet-stream` |

**Comment by weidongxu-microsoft** [comment]
loadtesting uses multipart, and they plan a GA soon (expect Nov.)
https://github.com/Azure/azure-sdk-for-java/pull/30706

At present they uses a helper method to use `setHeader` and `setBody` to provide a solution (the case when streaming is not necessary?).
https://github.com/Azure/azure-sdk-for-java/pull/30706/files#diff-5b7425837268825f2f8d2712d0ce73ade89309dc7ec407d2c9a45708525af0f9
And provide a hand-written method in Client to use this helper.

Let us know your opinion.

**Comment by weidongxu-microsoft** [comment]
We may need an update on it. OpenAI would use multipart/form-data in mid Sept. for transcription from video to text
