### ISSUE TITLE
Add Support for Additional Response Content-Types

### ISSUE THREAD

**Issue by alzimmermsft** [Azure/azure-sdk-for-java#8708]
Currently, Azure Core expects that the `Content-Type` of a response is either `json` or `xml`. There are additional `Content-Type`s that need to be supported such as plain text, images, and additional forms of `json` or `xml` that aren't currently supported.

**Comment by alzimmermsft** [comment]
Azure Search uses `text/plain`

**Comment by lmazuel** [comment]
AppConfig could use `application/vnd.microsoft.appconfig.kv.v1+json` if that helps

**Comment by lmazuel** [comment]
If that could helps, some notes on what Python is doing:
- When you call the pipeline, you pass a parameter to say if you want the pipeline to "pre-deserialize" the body (`stream=True/False`):
  - If you pass `stream=True`, pipeline doesn't touch the body and give you back an open socket on the HTTP connection (e.g. download blob). Content-Type is ignored.
  - If you do pass `stream=False`, this means load the body in memory, and use the Content-Type to do a first pass:
    - If regexp match JSON, create the JSON object
    - Else if XML, create a XML tree
    - Else if text/*, decode the body and return the string
    - Else fail for content-type impossible to handle

**Comment by weidongxu-microsoft** [comment]
mgmt-plane got response as application/json 99.9%.

automation has a text/powershell.
https://github.com/Azure/azure-rest-api-specs/blob/master/specification/automation/resource-manager/Microsoft.Automation/stable/2018-06-30/runbook.json#L54-L91

I think at present modelerfour will parse this as binary, so we are still safe.

**Comment by alzimmermsft** [comment]
This issue may be broken out into smaller children issues per `Content-Type` needing support.
