### ISSUE TITLE
[SB Track2] Support retry configurability on clients 

### ISSUE THREAD

**Issue by hemanttanwar** [Azure/azure-sdk-for-java#8713]
Support retry configurability on clients like we did in Event Hubs. Since we are starting with EH code base, we should have lot of this already.

Ensure we have following 

1. User can configure retry via API
2. In case of AMQP connection/link error the retry is implemented as configured.
3. Test for this feature are implemented

Related ticket : https://github.com/Azure/azure-sdk-for-python/issues/4265

**Comment by conniey** [comment]
Verified this works in tests.
