### ISSUE TITLE
[BUG] Async Event Hubs Producer cannot create an Event batch to send data

### ISSUE THREAD

**Issue by deepankarmalhan** [Azure/azure-sdk-for-java#8763]
**Describe the bug**

I'm following the guide [here](https://github.com/Azure/azure-sdk-for-java/tree/master/sdk/eventhubs/azure-messaging-eventhubs#create-an-event-hub-producer-and-publish-events) to create an `EventHubProducerAsyncClient` -- which is different than the `EventHubProducerCluent` used in the documentation. When I try creating an `EventDataBatch` to send my data, I get the error: 

![Screen Shot 2020-03-05 at 11 50 36 AM](https://user-images.githubusercontent.com/8868461/76004597-b53ee900-5ed7-11ea-9177-c046a9d36c39.png)

Looking more into the error it seems that `EventHubProducerClient` is a wrapper on top of `EventHubProducerAsyncClient` and it uses the library `Mono` to convert the `Mono` object returned from `EventHubProducerAsycClient.createBatch()` to `EventDataBatch`. **But if I try to `createBatch()` directly from the Async Producer Client I'm unable to cast it into an `EventDataBatch`**.

***Exception or Stack Trace***

`.../test-event-hub-producer/src/main/java/EventHubProducerMain.java:[18,60] incompatible types: reactor.core.publisher.Mono<com.azure.messaging.eventhubs.EventDataBatch> cannot be converted to com.azure.messaging.eventhubs.EventDataBatch`

**To Reproduce**

- Create an `EventHubProducerAsyncClient` with the proper connection string and Event Hubs name. More info [here](https://github.com/Azure/azure-sdk-for-java/tree/master/sdk/eventhubs/azure-messaging-eventhubs#create-an-event-hub-producer-and-publish-events).
- Try to create an `EventDataBatch` to add `EventData` objects to the batch. Get the error in the screenshot above.

***Code Snippet***

```        
EventHubProducerAsyncClient eventHubProducer = new EventHubClientBuilder().connectionString(connectionString, eventHubName).buildAsyncProducerClient();
EventDataBatch batch = eventHubProducer.createBatch();
```
**Expected behavior**

`eventHubProducer.createBatch()` should return `EventDataBatch` type or another compatible type which can be casted into `EventDataBatch`.

**Screenshots**

![Screen Shot 2020-03-05 at 11 50 36 AM](https://user-images.githubusercontent.com/8868461/76004597-b53ee900-5ed7-11ea-9177-c046a9d36c39.png)

**Setup (please complete the following information):**

 - OS: macOS X
 - IDE : IntelliJ
 - Version of the Library used: 5.0.2

**Additional context**

I'm using the following dependency in my `pom.xml`:
```
        <dependency>
            <groupId>com.azure</groupId>
            <artifactId>azure-messaging-eventhubs</artifactId>
            <version>5.0.2</version>
        </dependency>
```

**Information Checklist**

Kindly make sure that you have added all the following information above and checkoff the required fields otherwise we will treat the issuer as an incomplete report
- [x] Bug Description Added
- [x] Repro Steps Added
- [x] Setup information Added

**Comment by deepankarmalhan** [comment]
For more info, if you go to the `EventHubProducerAsynClient` Java docs on the left side [here](https://azuresdkdocs.blob.core.windows.net/$web/java/azure-messaging-eventhubs/5.0.2/index.html), you'll see that the java docs contain the `EventHubProducerClient` example even in the async client class. The only place where I've found documentation for the async client is in this [migration guide](https://github.com/Azure/azure-sdk-for-java/blob/master/sdk/eventhubs/azure-messaging-eventhubs/migration-guide.md#migrating-code-from-eventhubclient-to-eventhubproducerasyncclient-for-sending-events-using-automatic-routing) where the async client is used in the **in V5** section.

**Comment by deepankarmalhan** [comment]
So my question is: 
- Is it intentional that `EventHubProducerAsyncClient` returns `Mono<Void>` and that we should be using the reactor library along with this one?
- Can the java docs be properly updated for `EventHubProducerAsyncClient` using the migration guide I linked above? Even that example uses Reactor to block the `Mono` object so it still technically is a synchronous example.

**Comment by srnagar** [comment]
@deepankarmalhan Thanks for reaching out. If you are using `EventHubProducerAsyncClient`, `createBatch()` will return a `Mono<EventDataBatch>` and this is expected as this is an async client and you have to use the reactor library here. 

The javadoc on `EventHubProducerAsyncClient` has sync client codesnippet which is incorrect. It should contain codesnippet for async client. Thanks for reporting this issue. We'll update the javadoc.

The migration guide uses blocking `get()` in v3 and `block()` in v5 which is not idiomatic. We'll update the migration guide too.

Also, you can find some samples for [using the async client here.](https://github.com/Azure/azure-sdk-for-java/blob/master/sdk/eventhubs/azure-messaging-eventhubs/src/samples/java/com/azure/messaging/eventhubs/EventHubProducerAsyncClientJavaDocCodeSamples.java#L18)

**Comment by deepankarmalhan** [comment]
Thank you so much! Feel free to close this issue whenever you want!

**Comment by deepankarmalhan** [comment]
Actually I have a quick question, I'm trying to create following sample application:
```
public static void main(String... args) {
        // Initialize the producer
        EventHubProducerAsyncClient eventHubProducer = new EventHubClientBuilder()
                .connectionString(System.getenv("EVENT_HUB_CONN_STRING"), System.getenv("EVENT_HUB_NAME"))
                .buildAsyncProducerClient();

        // Create a batch and add a sample log to it
        eventHubProducer.createBatch().flatMap(batch -> {
            batch.tryAdd(new EventData("test-event-hub-producer"));
            batch.tryAdd(new EventData("test-event-hub-producer-02"));

            return eventHubProducer.send(batch);
        }).subscribe(unused -> {}, 
         error -> System.err.println("Couldn't send logs, there's an error: " + error.getStackTrace()), 
         () -> {
            System.out.println("Send complete!");
            // Close the connection
            eventHubProducer.close();
        });
    }
```

I tried putting the `eventHubProducer.close()` outside of the batch but it obviously doesn't wait for the async things to complete before closing the producer. Even if I put it inside the scope JVM registers the async event but the main method finishes and the application exits before it even has a chance to run the async event. Any thoughts on how to make it wait other than putting a timer after the async method?

**Comment by srnagar** [comment]
You could do something like this with a CountDownLatch. You can create a CountDownLatch with count 1 and count it down when the connection is closed. Await at the end to not terminate the process until the countdown is done.

```java
public static void main(String... args) {
        // Initialize the producer
        EventHubProducerAsyncClient eventHubProducer = new EventHubClientBuilder()
                .connectionString(System.getenv("EVENT_HUB_CONN_STRING"), System.getenv("EVENT_HUB_NAME"))
                .buildAsyncProducerClient();

         CountDownLatch countDownLatch = new CountDownLatch(1);
        // Create a batch and add a sample log to it
        eventHubProducer.createBatch().flatMap(batch -> {
            batch.tryAdd(new EventData("test-event-hub-producer"));
            batch.tryAdd(new EventData("test-event-hub-producer-02"));

            return eventHubProducer.send(batch);
        }).subscribe(unused -> {}, 
         error -> System.err.println("Couldn't send logs, there's an error: " + error.getStackTrace()), 
         () -> {
            System.out.println("Send complete!");
            // Close the connection
            eventHubProducer.close();
           // Count down the latch to complete the process
           countDownLatch.countDown();
        });
        countDownLatch.await(); // or await with a timeout like countDownLatch.await(timeout);
    }
```

**Comment by deepankarmalhan** [comment]
Update: Got the above code snippet to work but I keep timing out while trying to send logs. I've double checked firewall settings and policies in Azure and outside and nothing should be blocking the connection. I've tried using connection string from event hubs namespace and event hub instance itself. Have you ever encountered `createBatch()` timing out? I see uptick in requests but no messages go to the Event Hub instance. I'm running application locally, might that be it?

**Comment by aaronkorver** [comment]
@deepankarmalhan I am experiencing the timeout as well.  It doesn't seem to matter if it is the sync or the async producer (I've tried them both).

This is with version 5.0.2 of the SDK

**Comment by deepankarmalhan** [comment]
@srnagar would you be able to shed light on the question above?

**Comment by srnagar** [comment]
@deepankarmalhan Could you please provide the stacktrace for timeout errors? Also, are you using proxy?

**Comment by deepankarmalhan** [comment]
No proxy, we tried connecting to Event Hubs namespace through our corporate network and outside of it and it's the same exact timeout:
```
Exception in thread "main" java.lang.IllegalStateException: Timeout on blocking read for 60000 MILLISECONDS
	at reactor.core.publisher.BlockingSingleSubscriber.blockingGet(BlockingSingleSubscriber.java:110)
	at reactor.core.publisher.Mono.block(Mono.java:1185)
	at com.azure.messaging.eventhubs.EventHubProducerClient.createBatch(EventHubProducerClient.java:127)
```

I believe @aaronkorver also tried connecting through our corporate network and outside (general internet) with and without websockets and still it timed out with the above stack trace for all 4 scenarios.

**Comment by srnagar** [comment]
Thanks for providing the details. I will look into this issue and let you know.

**Comment by aaronkorver** [comment]
```

**Comment by srnagar** [comment]
@aaronkorver Thanks for the logs and code sample. The logs were super helpful in investigating this issue!

I ran the same code with my event hub instance and it worked fine using azure-messaging-eventhubs 5.0.2 version (see log below). 

However, from your logs, I noticed that the reactor-core version that was included in your classpath was 3.1.0-RELEASE but azure-messaging-eventhubs 5.0.2 depends on version 3.3.0-RELEASE of reactor-core.

So, I tested with older reactor-core version and sure enough, I was able to reproduce the timeout error. So, it seems like an issue where the older version of reactor-core is not compatible. 

Is it possible for you to upgrade to version 3.3.0-RELEASE version of reactor-core?

```
2020-03-11 23:12:43,356 INFO  [main] org.samples.azure.eventhubs.EventProducerSync: Created a new EventHubProducerClient!
2020-03-11 23:12:44,038 INFO  [main] org.samples.azure.eventhubs.EventProducerSync: Event Hub created at:  <REDACTED>
2020-03-11 23:12:44,038 INFO  [main] org.samples.azure.eventhubs.EventProducerSync: srnagar-hub has this partition ID: 0
2020-03-11 23:12:44,038 INFO  [main] org.samples.azure.eventhubs.EventProducerSync: srnagar-hub has this partition ID: 1
2020-03-11 23:12:44,038 INFO  [main] org.samples.azure.eventhubs.EventProducerSync: srnagar-hub has this partition ID: 2
2020-03-11 23:12:44,039 INFO  [main] org.samples.azure.eventhubs.EventProducerSync: srnagar-hub has this partition ID: 3
2020-03-11 23:12:44,039 INFO  [main] org.samples.azure.eventhubs.EventProducerSync: srnagar-hub has this partition ID: 4
2020-03-11 23:12:44,079 INFO  [main] org.samples.azure.eventhubs.EventProducerSync: Event Hub name is: srnagar-hub
2020-03-11 23:12:44,079 INFO  [main] org.samples.azure.eventhubs.EventProducerSync: Is Partition empty: false
2020-03-11 23:12:44,079 INFO  [main] org.samples.azure.eventhubs.EventProducerSync: Creating a new batch...
2020-03-11 23:12:44,268 INFO  [main] org.samples.azure.eventhubs.EventProducerSync: Done!
2020-03-11 23:12:44,340 INFO  [main] org.samples.azure.eventhubs.EventProducerSync: Successfully sent a batch of events
2020-03-11 23:12:44,361 INFO  [main] org.samples.azure.eventhubs.EventProducerSync: Closed producer client
```

**Comment by deepankarmalhan** [comment]
Confirmed! I've tried with both a synchronous producer and an async one and both of them work through websockets if we take out the `reactor-core` dependency from our pom file. It's highly unusual though because I was using:
```
...
<dependencyManagement>
   <dependencies>
      <dependency>
         <groupId>io.projectreactor</groupId>
         <artifactId>reactor-bom</artifactId>
         <version>Bismuth-RELEASE</version>
         <type>pom</type>
         <scope>import</scope>
      </dependency>
   </dependencies>
</dependencyManagement>
...
<dependency>
   <groupId>io.projectreactor</groupId>
   <artifactId>reactor-core</artifactId>
 </dependency>
```
in the pom file so my assumption was that we were using the latest version. Thank you for catching that version, I personally would've never caught it! I don't think this is a bug per se but I don't know if you want to add this a FAQ section or somewhere in the repo.

**Comment by deepankarmalhan** [comment]
For our issue though, it's fixed so thank you for both your helps @aaronkorver and @srnagar!

**Comment by srnagar** [comment]
@deepankarmalhan Thanks for the confirmation! I would not have figured this out either and was having trouble reproducing it until I looked closely at the logs @aaronkorver sent me which had all the versions used. 

I will check if this can be included in our documentation somewhere. 

Resolving this issue.

**Comment by Yasara-Y** [comment]
Hi @srnagar @aaronkorver ,
I am experiencing the same error when trying to create an event batch to send data and the error trace is as follows.

```
Timeout on blocking read for 60000000000 NANOSECONDS java.lang.IllegalStateException: Timeout on blocking read for 60000000000 NANOSECONDS| 
at reactor.core.publisher.BlockingSingleSubscriber.blockingGet(BlockingSingleSubscriber.java:123) ~[reactor-core-3.4.12.jar:3.4.12]| 
at reactor.core.publisher.Mono.block(Mono.java:1731) ~[reactor-core-3.4.12.jar:3.4.12]| 
at com.azure.messaging.eventhubs.EventHubProducerClient.createBatch(EventHubProducerClient.java:128) ~[azure-messaging-eventhubs-5.7.0.jar:?]| 
```
But some batches are created successfully and published to eventhub. Only some events drop when trying to create a batch. 
Can you please shed some light on how to resolve this issue?
