### ISSUE TITLE
Configurable connection/read/write timeouts for NettyAsyncHttpClient

### ISSUE THREAD

**Issue by dtkahuk** [Azure/azure-sdk-for-java#8802]
There is not a possibility to configure connection/read/write timeouts for NettyAsyncHttpClient created via NettyAsyncHttpClientBuilder

**Comment by joshfree** [comment]
Thanks for filing this feature request @dtkahuk. @alzimmermsft please take a look for a future monthly update of azure-core. 

/cc @JonathanGiles

**Comment by JonathanGiles** [comment]
+ @anuchandy

**Comment by anuchandy** [comment]
The `ConnectionTimeout` can be configured in the "reactor-netty HttpClient" and provided to "azure-core HttpClient".

```java
reactor.netty.http.client.HttpClient baseClient = HttpClient.create();
baseClient = baseClient.tcpConfiguration(tcpClient -> {
    return tcpClient.bootstrap(new Function<Bootstrap, Bootstrap>() {
        @Override
        public Bootstrap apply(Bootstrap bootstrap) {
            return bootstrap.option(ChannelOption.CONNECT_TIMEOUT_MILLIS, 
                (int) TimeUnit.MINUTES.toMillis(5L));
        }
    });
});

com.azure.core.http.HttpClient httpClient = new NettyAsyncHttpClientBuilder(baseClient)
    .build();
```
Any bootstrap properties can be set with the above approach.

When it comes to socket `ReadTimeout`, netty has a bootstrap property for that:

```java
bootstrap.option(ChannelOption.SO_TIMEOUT, (int) TimeUnit.MINUTES.toMillis(1L));
```

This setting is not applicable for NIO based socket read operation. It applied for OIO based transport.

The recommendation here is to apply the reactor `timeout()` operator. More details on a similar [topic](https://github.com/reactor/reactor-netty/issues/26).

`WriteTimeout` is something we need to explore, a quick search didn't reveal a netty setting for that.

**Comment by dtkahuk** [comment]
@anuchandy Thank you for advice. But the last stable version of 'azure-storage-blob' 12.4.0 uses 'azure-core-http-netty' version 1.3.0 where we can't  create custom tcpConfiguration via HttpClient - in NettyAsyncHttpClient it will be rewritten. 
It looks like it will be possible to set any timeouts via HttpClient for 1.4.0 version of 'azure-core-http-netty' which are used in 12.5.0-beta version of 'azure-storage-blob':
```            
 httpReactorClient.tcpConfiguration(tcpConfig -> { 
    tcpConfig.configure()
             .option(ChannelOption.CONNECT_TIMEOUT_MILLIS, 30);  
    tcpConfig.doOnConnected(
                     connection -> connection.onReadIdle(30L, () -> connection.channel().close())
    );
    return tcpConfig;
 });
```
Thank you - we will wait 12.5.0 release of 'azure-storage-blob' to use such approach for flexible  timeout configuration.

**Comment by alzimmermsft** [comment]
Hi @dtkahuk the release of `azure-storage-blob` `12.5.0` has happened, mind testing that out and reporting back whether it fixed your issue.

**Comment by anuchandy** [comment]
@dtkahuk - did you get a chance to validate this with the version Alan pointed?

**Comment by dtkahuk** [comment]
@anuchandy. We use the new version of 'azure-storage-blob' library - it allows us to configure timeouts.
Thank you for your help.

**Comment by alzimmermsft** [comment]
Closing this issue as it appears to be resolved.
