### ISSUE TITLE
[QUERY] Unsupported filename method

### ISSUE THREAD

**Issue by saragluna** [Azure/azure-sdk-for-java#8863]
**Query/Question**
Is there a way to retrieve the filename via the ShareFileClient? Only the share's name could be queried for now.

***Why is this not a Bug or a feature Request?***
I'm migrating the storage client to v12.0 and I found this method missing.

**Setup (please complete the following information if applicable):**
 - OS: Mac OS
 - IDE : IntelliJ
 - Version of the Library used: azure-storage-file-share v12.2.0
 
 **Information Checklist**
 Kindly make sure that you have added all the following information above and checkoff the required fields otherwise we will treat the issuer as an incomplete report
- [x] Query Added
- [x] Setup information Added

**Comment by rickle-msft** [comment]
Hi, @saragluna thank you for your question! You should be able to use `getFilePath` to achieve the same purpose. If this doesn't suit your needs, please let us know, and we can go from there.

**Comment by saragluna** [comment]
@rickle-msft 

Thanks for your answer! Is the return value of `getFilePath ()` the same as the filename, or should I process it further?

**Comment by rickle-msft** [comment]
If the url is `<endpoint>/<filesystem>/<filePath>` it'll be that whole third component. So if you want just the name of the file rather than path within the filesystem, you probably want to do like a `.split().last()` (pseudocode) sort of operation on it.

**Comment by rickle-msft** [comment]
I am going to close this issue as I believe the question has been answered and there has been no follow up. Please feel free to reopen it if you have further questions.
