### ISSUE TITLE
Remove org.unitils:unitils-core dependency

### ISSUE THREAD

**Issue by conniey** [Azure/azure-sdk-for-java#8874]
org.unitils is an old library that is used to test for equality in Azure Search models. This project hasn't had a release in 3 years. Can we replace this with either code or something that is maintained?

This will allow us to remove the following dependencies:
* org.unitils:unitils-core;3.4.6
  * commons-collections:commons-collections:3.2.2
  * ognl:ognl:3.0.12

**Comment by sima-zhu** [comment]
PR is merged. Closed it
