### ISSUE TITLE
Set AMQP's azure-core dependency back to the current version of core after release

### ISSUE THREAD

**Issue by JimSuplizio** [Azure/azure-sdk-for-java#8880]
Core released on 3/6 with the exception of azure-core-amqp which has a fix in progress. While libraries built within the same pipeline should always be using the current version of those libraries, an exception needs to be made here for amqp in order for it to be released this week. After AMQP is released the azure-core dependency tag needs to be updated to reference the current version of core.
from:
`    <dependency>
      <groupId>com.azure</groupId>
      <artifactId>azure-core</artifactId>
      <version>1.3.0</version> 
    </dependency>
`
to:
`    <dependency>
      <groupId>com.azure</groupId>
      <artifactId>azure-core</artifactId>
      <version>1.3.0</version> 
    </dependency>
`

**Comment by conniey** [comment]
Fixed in #9808
