### ISSUE TITLE
CosmosSkip: Remove unapproved dependencies

### ISSUE THREAD

**Issue by JonathanGiles** [Azure/azure-sdk-for-java#8888]
There are a number of [dependencies in the cosmos library](https://github.com/Azure/azure-sdk-for-java/blob/master/sdk/cosmos/azure-cosmos/pom.xml#L165) that need to be considered for removal, or have a valid justification for their need made. These include the apache commons libraries and Guava, but consideration should be given to all dependencies.

Furthermore, dependencies on non-standard versions (i.e. with 'cosmos_' names in the version tag) need to be reconciled.

**Comment by kushagraThapar** [comment]
This is done, closing it.
