### ISSUE TITLE
[BUG] public Mono<DatabaseAccount> readDatabaseAccount() fails always

### ISSUE THREAD

**Issue by anfeldma-ms** [Azure/azure-sdk-for-java#8900]
**Describe the bug**
I am submitting this bug on behalf of a user who is developing a tool for interacting with Azure Cosmos DB SQP API. He is helping us to derisk the Java SDK v4 before it is released, by using the public preview.2 artifact for his development. I have attached the PDF with all of his feedback, including his bug report.

[Cosmos DB Java Driver 4.X Feedback.pdf](https://github.com/Azure/azure-sdk-for-java/files/4313166/Cosmos.DB.Java.Driver.4.X.Feedback.pdf)

The bug is that every call to client.readDatabaseAccount().block() from the async client fails. He did not test the sync client because his application is async.

***Exception or Stack Trace***
Please see the attached PDF, specifically section 6.1 ("failed with Unauthorized Exception...") and the section at the very end titled "Reading DatabaseAccount from the async client". I will paste the stack trace here:
 
Suppressed: java.lang.Exception: 
at reactor.core.publisher.BlockingSingleSubscriber.blockingGet(BlockingSingleSubscriber.java:99) at reactor.core.publisher.Mono.block(Mono.java:1663) 
at com.azure.cosmos.sample.async.AsyncMain.getStartedDemo(AsyncMain.java:89) at com.azure.cosmos.sample.async.AsyncMain.main(AsyncMain.java:56) 
Cosmos getStarted failed with UnauthorizedException{error={"Errors":["The MAC signature found in the HTTP request is not the same as the computed signature. Server used following string to sign - 'get\n/\n\nmon, 24 feb 2020 12:46:37 gmt\n\n'"]}, resourceAddress='null', statusCode=401, message=["​The MAC signature found in the HTTP request is not the same as the computed signature.​ Server used following string to sign - 'get\n/\n\nmon, 24 feb 2020 12:46:37 gmt\n\n'"], {"requestLatency":10404,"requestStartTime":"24 Feb 2020 12:46:37.366","requestEndTime":"24 Feb 2020 12:46:47.770","connectionMode":"DIRECT","responseStatisticsList":[{"storeResult":{"storePhysi calAddress":null,"lsn":29,"globalCommittedLsn":29,"partitionKeyRangeId":"","isValid":true,"status Code":401,"subStatusCode":0,"isGone":false,"isNotFound":false,"isInvalidPartition":false,"reque stCharge":0.0,"itemLSN":-1,"sessionToken":"-1#29","exception":"[\"The MAC signature found in the HTTP request is not the same as the computed signature. Server used following string to sign - 'get\\n/\\n\\nmon, 24 feb 2020 12:46:37 gmt\\n\\n'\"]","transportRequestTimeline":null},"requestResponseTime":"24 Feb 2020 12:46:47.769","requestResourceType":"DatabaseAccount","requestOperationType":"Read"},{"st oreResult":{"storePhysicalAddress":null,"lsn":29,"globalCommittedLsn":29,"partitionKeyRangeId ":"","isValid":true,"statusCode":401,"subStatusCode":0,"isGone":false,"isNotFound":false,"isInval idPartition":false,"requestCharge":0.0,"itemLSN":-1,"sessionToken":"-1#29","exception":"[\"The MAC signature found in the HTTP request is not the same as the computed signature. Server used following string to sign - 'get\\n/\\n\\nmon, 24 feb 2020 12:46:37 gmt\\n\\n'\"]","transportRequestTimeline":null},"requestResponseTime":"24 Feb 2020 12:46:47.770","requestResourceType":"DatabaseAccount","requestOperationType":"Read"}],"su pplementalResponseStatisticsList":[],"addressResolutionStatistics":{"b22811a6-5703-11ea-bfb46386c6e0f8de":{"startTime":"24 Feb 2020 12:46:37.371","endTime":"24 Feb 2020 12:46:37.559","targetEndpoint":"https://cosmic-alpha-westeurope.documents.azure.com:443/ad dresses/?$resolveFor=dbs&$filter=protocol%20eq%20rntbd"}},"regionsContacted":[],"retryConte xt":{"retryCount":0,"statusAndSubStatusCodes":null,"retryLatency":0},"gatewayStatistics":null,"sy stemInformation":{"usedMemory":"91135 KB","availableMemory":"4039681 KB","processCpuLoad":"13.021267375579185 %","systemCpuLoad":"63.376659093253 %"}}, causeInfo=null, responseHeaders={x-ms-last-state-change-utc=Thu, 13 Feb 2020 16:58:59.042 GMT, x-ms-xp-role=2, x-ms-global-Committed-lsn=29, x-ms-session-token=0:-1#29, lsn=29, x-ms-request-charge=0.0, x-ms-cosmos-llsn=29, x-ms-schemaversion=1.9, x-ms-transport-request-id=2, x-ms-number-of-read-regions=0, x-ms-serviceversion= version=2.9.0.0, x-ms-activity-id=b226d925-5703-11ea-bfb4-6386c6e0f8de}, requestHeaders=null} Closing the client 
 
 

**To Reproduce**
* Create an async client instance
* Call client.readDatabaseAccount().block();

***Code Snippet***
client.readDatabaseAccount().block();

**Expected behavior**
The user expected client.readDatabaseAccount().block() to return a DatabaseAccount instance with database account information.

**Screenshots**
N/A

**Setup (please complete the following information):**
 - OS: Unsure
 - IDE : Unsure
 - Java SDK v4 preview.2
 - I (anfeldma-ms) reproduced this bug on my Windows machine with Intellij IDEA

**Additional context**
N/A

**Information Checklist**
Kindly make sure that you have added all the following information above and checkoff the required fields otherwise we will treat the issuer as an incomplete report
- [x] Bug Description Added
- [x] Repro Steps Added
- [x] Setup information Added

**Comment by kushagraThapar** [comment]
This is no longer a valid issue, as the API is not public anymore after GA.
