### ISSUE TITLE
Permissions should be removed as a public type in favour of CosmosPermissionProperties

### ISSUE THREAD

**Issue by moderakh** [Azure/azure-sdk-for-java#8904]
there are two public types for permissions in v4:

https://github.com/Azure/azure-sdk-for-java/blob/master/sdk/cosmos/azure-cosmos/src/main/java/com/azure/cosmos/models/CosmosPermissionProperties.java

https://github.com/Azure/azure-sdk-for-java/blob/master/sdk/cosmos/azure-cosmos/src/main/java/com/azure/cosmos/models/Permission.java

Permission is reference from https://github.com/Azure/azure-sdk-for-java/blob/master/sdk/cosmos/azure-cosmos/src/main/java/com/azure/cosmos/CosmosClientBuilder.java#L228-L231

Permission should become non-public type and we should move to CosmosPermisisonProperties in the public surface area before v4 GA.

**Comment by mbhaskar** [comment]
Also, enable getResourcePartitionKey() method in CosmosPermissionProperties

**Comment by kushagraThapar** [comment]
This is done, closing now.
