### ISSUE TITLE
Add IndexingParameteres Helper Class

### ISSUE THREAD

**Issue by alzimmermsft** [Azure/azure-sdk-for-java#8908]
Add a helper class for `IndexingParameters` that adds convenience methods for setting its configuration, such as file name extensions and file contents. This is a port of [IndexingParametersExtensions](https://github.com/Azure/azure-sdk-for-net/blob/master/sdk/search/Microsoft.Azure.Search.Service/src/Customizations/Indexers/Models/IndexingParametersExtensions.cs).

**Comment by sima-zhu** [comment]
Move to preview 5 as it is an addition changes.

**Comment by alzimmermsft** [comment]
This issue may be fixed when #13881 is resolved.
