### ISSUE TITLE
Inconsistent behaviour with genericResources().getById(id)

### ISSUE THREAD

**Issue by galitharun** [Azure/azure-sdk-for-java#8935]
getById(id) from genericResources() throws NullPointerException for resources which no longer exist in Azure, is this expected behaviour? We are using azure sdk version 1.31.1 and have tried this for several resources like virtualMachines and storageAccounts.

**Comment by joshfree** [comment]
@galitharun thanks for reporting this issue.  An expert from the Management Plane SDK team will follow up with you shortly.

/cc @yaohaizh

**Comment by yaohaizh** [comment]
@xccc-msft  //cc @yungezz

**Comment by xccc-msft** [comment]
@galitharun  Could you please share the exception trace?

**Comment by galitharun** [comment]
@xccc-msft  there is no stack trace visible from azure sdk, the call is simply resulting in a NullPointerException

**Comment by xccc-msft** [comment]
@galitharun You could review [the fix of NPE](https://github.com/Azure/azure-libraries-for-java/pull/1098/files). We plan to release on March 20th, which target at our next new version.

**Comment by galitharun** [comment]
@xccc-msft  thank you.
