### ISSUE TITLE
CLI Credentials for All Platforms

### ISSUE THREAD

**Issue by jofultz** [Azure/azure-sdk-for-java#8961]
As a developer I'd like to be able to create and use a CLI credential regardless of OS, IDE, or language so that I may have a secure, consistent, low-friction developer experience when developing for Azure.

A related bug is filed here: https://msazure.visualstudio.com/Unified%20Platform%20KPIs/_workitems/edit/6395777 

**Describe the solution you'd like**
- Ability to create CLI credential in all languages and OSs
- Ability to create and use discrete credential types 

Using the older SDK we use this logic to choose and create the desired credential:

>         if(_environmentFlag.equals(USE_MSI)) {
>             _credentials = new MSICredentials(AzureEnvironment.AZURE);
>         } else if (_environmentFlag.equals(USE_CLI)) {
>             try{
>                 _credentials = AzureCliCredentials.create();
>             }
>             catch (IOException ex){
>                 _logger.error(ex.getMessage());
>                 throw(ex);
>             }
>         } else {...}

We'd like to be able to something similar using the latest SDK.

**Describe alternatives you've considered**

**Additional context**

**Comment by jongio** [comment]
@jofultz - 

Do you need to instantiate an AzureCliCredential object on its own or is having it be part of DefaultAzureCredential enough?

**Comment by jofultz** [comment]
My preference is to instantiate it directly and use it as there is no confusion about what's in play then from a security perspective.  A livable work around is to have it in the DefaultAzureCredential and be able to disable parts of the chain so that only one credential at a time is active.

**Comment by jongio** [comment]
The latest previews/beta make AzureCliCredential a public type.  Please see https://aka.ms/azsdk/releases for links to all the latest packages.
