### ISSUE TITLE
Reduce RevAPI Runs in PR Validation

### ISSUE THREAD

**Issue by alzimmermsft** [Azure/azure-sdk-for-java#8978]
RevAPI runs in every pipeline which duplicates the validation unnecessarily, instead it could be ran three times. Reduce the RevAPI runs to these cases:

- Validating that using source code dependencies work.
- Validating that using Maven dependencies work. Run this on Java 8 and LTS.

**Comment by kurtzeborn** [comment]
Switching label to "Client" from "EngSys" to reflect who's doing the work for this issue.  We're happy to help with any engineering system related questions.  @mitchdenny and @JimSuplizio are your primary Java contacts.

**Comment by alzimmermsft** [comment]
Closing as this issue has been mitigated, RevApi only runs during the linting pipeline now.
