### ISSUE TITLE
Can we accept Creatable<Foo> in .withNewFoo(...) withers?

### ISSUE THREAD

**Issue by martinsawicki** [Azure/azure-sdk-for-java#902]
It may be better than having a dependency on a specific WithCreate interface. One reason is clarity. Another would be the .withNewFoo() withers should probably not have access to changing anything on the creatable definition.

**Comment by anuchandy** [comment]
PR addressing this: https://github.com/Azure/azure-sdk-for-java/pull/905

**Comment by martinsawicki** [comment]
done, we just need to stick to it
