### ISSUE TITLE
We should not be using camel casing rules in comments/javadocs when referring to acronyms

### ISSUE THREAD

**Issue by martinsawicki** [Azure/azure-sdk-for-java#903]
A comment or Javadoc is just English text, so the acronym naming recommendations that otherwise apply to code (Dns instead of DNS, etc) should not be followed there.
Instead it should be just the way it is named: DNS, ID, FQDN, IP, MAC, etc.
It'd be good to do a scrub across the board.

**Comment by martinsawicki** [comment]
fixed in beta2 with global replace in PR: https://github.com/Azure/azure-sdk-for-java/pull/901

It'd be good to have some sort of a checkstyle rule though -- looking for these patterns in comments and Javadocs (case sensitive) " Ip ", " Dns ", " Fqdn " at least.

**Comment by jianghaolu** [comment]
This will be overwritten by auto-generation if we auto-generate the interfaces. The correct solution is to fix in Swagger specs.
