### ISSUE TITLE
[Cosmos v4] evaluate possible NPE in GoneAndRetryWithRetryPolicy when accessing request

### ISSUE THREAD

**Issue by anuchandy** [Azure/azure-sdk-for-java#9039]
https://github.com/Azure/azure-sdk-for-java/blob/3e9b51beb5f5bc96f3e262445f256cea11108b8b/sdk/cosmos/azure-cosmos/src/main/java/com/azure/cosmos/implementation/directconnectivity/GoneAndRetryWithRetryPolicy.java#L157

The code access request already without any null check then another null check later seems confusing.

**Comment by kushagraThapar** [comment]
This is fixed now.
