### ISSUE TITLE
[Cosmos v4] evaluate possible chance of NPE

### ISSUE THREAD

**Issue by anuchandy** [Azure/azure-sdk-for-java#9041]
Null check is done here https://github.com/Azure/azure-sdk-for-java/blob/3e9b51beb5f5bc96f3e262445f256cea11108b8b/sdk/cosmos/azure-cosmos/src/main/java/com/azure/cosmos/implementation/RxGatewayStoreModel.java#L268 before accessing members of `ReactorNettyRequestRecord`, but missing in https://github.com/Azure/azure-sdk-for-java/blob/3e9b51beb5f5bc96f3e262445f256cea11108b8b/sdk/cosmos/azure-cosmos/src/main/java/com/azure/cosmos/implementation/RxGatewayStoreModel.java#L282

**Comment by kushagraThapar** [comment]
This is done now.
