### ISSUE TITLE
[Cosmos v4] CompilerWarning: implement hashCode

### ISSUE THREAD

**Issue by anuchandy** [Azure/azure-sdk-for-java#9046]
The `PartitionKeyInternal`, `VectorSessionToken` and `ResourceId` missing a correct `hashcode()` implementation.

**Comment by kushagraThapar** [comment]
We cannot change the hashcode logic as it will affect some of the business logic at this point. Worth picking this up in v5 of Java SDK.

**Comment by kushagraThapar** [comment]
Closing this issue as it is not related to V4 Java SDK.
