### ISSUE TITLE
[Cosmos v4] Spotbug: evaluate  DM_BOXED_PRIMITIVE_FOR_PARSING

### ISSUE THREAD

**Issue by anuchandy** [Azure/azure-sdk-for-java#9048]
https://github.com/Azure/azure-sdk-for-java/blob/c880a2cbeac8cdf2ef8b58b797b35620d703475c/sdk/cosmos/azure-cosmos/src/main/java/com/azure/cosmos/models/ModelBridgeInternal.java#L250 Unboxing `Long` here to `long` without a default could lead to error.

**Comment by xinlian12** [comment]
This issue has been fixed.
