### ISSUE TITLE
[Cosmos v4] evaluate the business logic in RntbdClientChannelPool that never runs

### ISSUE THREAD

**Issue by anuchandy** [Azure/azure-sdk-for-java#9050]
Here:

https://github.com/Azure/azure-sdk-for-java/blob/c880a2cbeac8cdf2ef8b58b797b35620d703475c/sdk/cosmos/azure-cosmos/src/main/java/com/azure/cosmos/implementation/directconnectivity/rntbd/RntbdClientChannelPool.java#L113

The code is like below, which assigns null to a local var, then check local var is null (which is always null) then do some actions, this code may be a bug.

```java
        final AcquisitionTimeoutAction acquisitionTimeoutAction = null;
        final long acquisitionTimeoutNanos = -1L;

        if (acquisitionTimeoutAction == null) {

            this.acquisitionTimeoutNanos = -1L;
            this.acquisitionTimeoutTask = null;

        } else {

            this.acquisitionTimeoutNanos = acquisitionTimeoutNanos;

            switch (acquisitionTimeoutAction) {
                case FAIL:
```

**Comment by kushagraThapar** [comment]
Fixed in a PR.

**Comment by kushagraThapar** [comment]
https://github.com/Azure/azure-sdk-for-java/pull/10616

**Comment by kushagraThapar** [comment]
This is done.
