### ISSUE TITLE
Fix PartitionKey.None.toString() throws an exception

### ISSUE THREAD

**Issue by FredGao-new** [Azure/azure-sdk-for-java#9053]
#8499 

PartitionKey.None.toString() throws an exception: 

Java: 11 

Jackson: 2.10.1 

azure-cosmos 3.6.0 

        @Test 
        void testPartitionKeyNoneToString() { 
            com.azure.data.cosmos.PartitionKey.None.toString(); 
        } 

 

 

The exception happened in the following code: 
https://github.com/Azure/azure-sdk-for-java/blob/660bc29a3a268988e515a3889dec7c2b7c3a2e86/sdk/cosmos/azure-cosmos/src/main/java/com/azure/cosmos/implementation/routing/PartitionKeyInternal.java#L246 

 

 

 

partitionKey.getComponents() return null in the "for" loop. 

 
Is it ok to add a null check for partitionKey.getComponents before the for loop? 

@jongio

**Comment by kushagraThapar** [comment]
@mbhaskar - Please take a look at this.

**Comment by kushagraThapar** [comment]
This has been fixed on v4 SDK.

**Comment by jongio** [comment]
@tzhanl - Please verify fixed.

**Comment by tzhanl** [comment]
Verified fixed in azure.cosmos 4.1.0. Close issue.
