### ISSUE TITLE
[Cosmos v4] Cleanup: RemainingWorkEstimatorImpl is dead-code 

### ISSUE THREAD

**Issue by anuchandy** [Azure/azure-sdk-for-java#9075]
The type [RemainingWorkEstimatorImpl ](https://github.com/Azure/azure-sdk-for-java/blob/master/sdk/cosmos/azure-cosmos/src/main/java/com/azure/cosmos/implementation/changefeed/implementation/RemainingWorkEstimatorImpl.java) is not used anywhere. This type was revealed when spot bug reported `URF_UNREAD_FIELD` for this class.

**Comment by kushagraThapar** [comment]
@milismsft  - can we remove this dead code or is it necessary to keep it ?
Whatever may be the reason, we can close this issue. Please update it. Thanks.

**Comment by milismsft** [comment]
yes, we can remove it (and the interface).
