### ISSUE TITLE
[Cosmos v4] StoreClientFactory ignores user provided timeout

### ISSUE THREAD

**Issue by anuchandy** [Azure/azure-sdk-for-java#9076]
The following time out in impl class - 
https://github.com/Azure/azure-sdk-for-java/blob/d888e8aa057d9675e357fde0dff2e68654b9fc0d/sdk/cosmos/azure-cosmos/src/main/java/com/azure/cosmos/implementation/directconnectivity/StoreClientFactory.java#L36

is coming from the public config

https://github.com/Azure/azure-sdk-for-java/blob/d888e8aa057d9675e357fde0dff2e68654b9fc0d/sdk/cosmos/azure-cosmos/src/main/java/com/azure/cosmos/ConnectionPolicy.java#L68

but is ignored in impl.

**Comment by anuchandy** [comment]
Additionally, StoreClientFactory.java ignores the following configs:

maxConcurrentConnectionOpenRequests
enableTransportClientSharing

**Comment by kushagraThapar** [comment]
Will work on this.

**Comment by kushagraThapar** [comment]
This is done.
