### ISSUE TITLE
[Cosmos v4] correlatedActivityId is yet to be handled 

### ISSUE THREAD

**Issue by anuchandy** [Azure/azure-sdk-for-java#9077]
This correlation id:

https://github.com/Azure/azure-sdk-for-java/blob/d888e8aa057d9675e357fde0dff2e68654b9fc0d/sdk/cosmos/azure-cosmos/src/main/java/com/azure/cosmos/implementation/query/PipelinedDocumentQueryExecutionContext.java#L27

that get set from here https://github.com/Azure/azure-sdk-for-java/blob/d888e8aa057d9675e357fde0dff2e68654b9fc0d/sdk/cosmos/azure-cosmos/src/main/java/com/azure/cosmos/implementation/RxDocumentClientImpl.java#L546

is yet to be handled.

**Comment by kushagraThapar** [comment]
We should get rid of `correlatedActivityId` as it is not being used. 
@moderakh  thoughts ?

**Comment by moderakh** [comment]
the new diagnostics info and tracing should replace it.
Kill it!

**Comment by xinlian12** [comment]
Does not exists in SDK anymore.
