### ISSUE TITLE
[Cosmos v4] evaluate adding Json serialization annotations for properties

### ISSUE THREAD

**Issue by anuchandy** [Azure/azure-sdk-for-java#9082]
Few properties of ServiceItemLease type is good to have explicit Jackson annotation for serialization, it is today assumes all properties are serializable, which result in the violation of the naming convention:
https://github.com/Azure/azure-sdk-for-java/blob/5dd0c40303aaf85aac4e7cf36b64a0ab1fe62437/sdk/cosmos/azure-cosmos/src/main/java/com/azure/cosmos/implementation/changefeed/ServiceItemLease.java#L28

Also, evaluate the properties of LocationCache$LocationUnavailabilityInfo:

https://github.com/Azure/azure-sdk-for-java/blob/5dd0c40303aaf85aac4e7cf36b64a0ab1fe62437/sdk/cosmos/azure-cosmos/src/main/java/com/azure/cosmos/implementation/routing/LocationCache.java#L502

This as well:

https://github.com/Azure/azure-sdk-for-java/blob/5dd0c40303aaf85aac4e7cf36b64a0ab1fe62437/sdk/cosmos/azure-cosmos/src/main/java/com/azure/cosmos/implementation/RxDocumentServiceRequest.java#L61

**Comment by xinlian12** [comment]
PR has merged.
