### ISSUE TITLE
[Cosmos v4] consider using entrySet() instead of keySet() 

### ISSUE THREAD

**Issue by anuchandy** [Azure/azure-sdk-for-java#9084]
Code like below, where we enumerate keys and then retrieve the value for each key

```java
for(String key: queryMetricsMap.keySet()) {
    BridgeInternal.putQueryMetricsIntoMap(frp, key, queryMetricsMap.get(key));
}
```

can be replaced with efficient `entrySet` api.

```java
for(Map.Entry<String, QueryMetrics> entry: queryMetricsMap.entrySet()) {
    BridgeInternal.putQueryMetricsIntoMap(frp, entry.getKey(), entry.getValue());
}
```

Evaluate the following instances of the above case:

https://github.com/Azure/azure-sdk-for-java/blob/d58fa9c68c021172a9e55d3a7e46bfe45dec0547/sdk/cosmos/azure-cosmos/src/main/java/com/azure/cosmos/implementation/query/AggregateDocumentQueryExecutionContext.java#L108

https://github.com/Azure/azure-sdk-for-java/blob/d58fa9c68c021172a9e55d3a7e46bfe45dec0547/sdk/cosmos/azure-cosmos/src/main/java/com/azure/cosmos/implementation/query/OrderByDocumentQueryExecutionContext.java#L442

https://github.com/Azure/azure-sdk-for-java/blob/d58fa9c68c021172a9e55d3a7e46bfe45dec0547/sdk/cosmos/azure-cosmos/src/main/java/com/azure/cosmos/implementation/query/ParallelDocumentQueryExecutionContextBase.java#L72

https://github.com/Azure/azure-sdk-for-java/blob/d58fa9c68c021172a9e55d3a7e46bfe45dec0547/sdk/cosmos/azure-cosmos/src/main/java/com/azure/cosmos/implementation/query/ParallelDocumentQueryExecutionContextBase.java#L161

https://github.com/Azure/azure-sdk-for-java/blob/d58fa9c68c021172a9e55d3a7e46bfe45dec0547/sdk/cosmos/azure-cosmos/src/main/java/com/azure/cosmos/implementation/ResourceTokenAuthorizationHelper.java#L169

**Comment by DanielBenniah** [comment]
@kushagraThapar This issue has been solved. I went through all instances cited in this issue, all of them now use entry set.

There are a few more instances where this change can be made. Please let me know if I can go ahead and modify them.

[https://github.com/Azure/azure-sdk-for-java/blob/e0edb751a2c6a5203b373a7756c9482f1a837edd/sdk/cosmos/azure-cosmos/src/main/java/com/azure/cosmos/implementation/query/AggregateDocumentQueryExecutionContext.java#L90](url) 

[https://github.com/Azure/azure-sdk-for-java/blob/e0edb751a2c6a5203b373a7756c9482f1a837edd/sdk/cosmos/azure-cosmos/src/main/java/com/azure/cosmos/implementation/query/OrderByUtils.java#L72](url)

[https://github.com/Azure/azure-sdk-for-java/blob/e0edb751a2c6a5203b373a7756c9482f1a837edd/sdk/mediaservices/microsoft-azure-media/src/test/java/com/microsoft/windowsazure/services/scenarios/MediaServiceWrapper.java#L146](url)

[https://github.com/Azure/azure-sdk-for-java/blob/e0edb751a2c6a5203b373a7756c9482f1a837edd/sdk/mediaservices/microsoft-azure-media/src/test/java/com/microsoft/windowsazure/services/scenarios/MediaServiceWrapper.java#L398](url)

[https://github.com/Azure/azure-sdk-for-java/blob/e0edb751a2c6a5203b373a7756c9482f1a837edd/sdk/core/azure-core/src/main/java/com/azure/core/http/rest/RestProxy.java#L274](url)

**Comment by kushagraThapar** [comment]
> @kushagraThapar This issue has been solved. I went through all instances cited in this issue, all of them now use entry set.
> 
> There are a few more instances where this change can be made. Please let me know if I can go ahead and modify them.
> 
> [https://github.com/Azure/azure-sdk-for-java/blob/e0edb751a2c6a5203b373a7756c9482f1a837edd/sdk/cosmos/azure-cosmos/src/main/java/com/azure/cosmos/implementation/query/AggregateDocumentQueryExecutionContext.java#L90](url)
> 
> [https://github.com/Azure/azure-sdk-for-java/blob/e0edb751a2c6a5203b373a7756c9482f1a837edd/sdk/cosmos/azure-cosmos/src/main/java/com/azure/cosmos/implementation/query/OrderByUtils.java#L72](url)
> 
> [https://github.com/Azure/azure-sdk-for-java/blob/e0edb751a2c6a5203b373a7756c9482f1a837edd/sdk/mediaservices/microsoft-azure-media/src/test/java/com/microsoft/windowsazure/services/scenarios/MediaServiceWrapper.java#L146](url)
> 
> [https://github.com/Azure/azure-sdk-for-java/blob/e0edb751a2c6a5203b373a7756c9482f1a837edd/sdk/mediaservices/microsoft-azure-media/src/test/java/com/microsoft/windowsazure/services/scenarios/MediaServiceWrapper.java#L398](url)
> 
> [https://github.com/Azure/azure-sdk-for-java/blob/e0edb751a2c6a5203b373a7756c9482f1a837edd/sdk/core/azure-core/src/main/java/com/azure/core/http/rest/RestProxy.java#L274](url)

@DanielBenniah I checked the cosmos files, and based on the logic, I don't think we need to update those two files - `AggregateDocumentQueryExecutionContext.java` and `OrderByUtils.java` - as they are trying to do something different than to iterate over a map using key set. 
Other files you mentioned in the issue are not cosmos related. 
So I think we can just close this issue. 

@anuchandy confirming with you before I close this ?

**Comment by kushagraThapar** [comment]
This is done.
