### ISSUE TITLE
[Cosmos V4] evaluate the correctness of volatile variable increment 

### ISSUE THREAD

**Issue by anuchandy** [Azure/azure-sdk-for-java#9087]
Volatile member variables are incremented. These increments don't guarantee atomicity for "read|increment|update". Double-check whether these increments are intended to be called from multiple threads if yes then switching to AtomicInteger is safe if no concurrency involved then volatile could be removed.

https://github.com/Azure/azure-sdk-for-java/blob/591d77d6260d9da8a148d1f1ffda2372c4a06143/sdk/cosmos/azure-cosmos/src/main/java/com/azure/cosmos/implementation/RetryPolicyWithDiagnostics.java#L54

https://github.com/Azure/azure-sdk-for-java/blob/591d77d6260d9da8a148d1f1ffda2372c4a06143/sdk/cosmos/azure-cosmos/src/main/java/com/azure/cosmos/implementation/changefeed/implementation/AutoCheckpointer.java#L64

https://github.com/Azure/azure-sdk-for-java/blob/591d77d6260d9da8a148d1f1ffda2372c4a06143/sdk/cosmos/azure-cosmos/src/main/java/com/azure/cosmos/implementation/query/DefaultDocumentQueryExecutionContext.java#L153

**Comment by anuchandy** [comment]
Ref: https://errorprone.info/bugpattern/NonAtomicVolatileUpdate

**Comment by kushagraThapar** [comment]
Working on this.
