### ISSUE TITLE
[Cosmos v4] evaluate PZLA_PREFER_ZERO_LENGTH_ARRAYS

### ISSUE THREAD

**Issue by anuchandy** [Azure/azure-sdk-for-java#9089]
Following 4 methods:

1. getResourcePathArray(..)

https://github.com/Azure/azure-sdk-for-java/blob/1300def7a6c810eb0b9f3a9fe175316e7f4f98f7/sdk/cosmos/azure-cosmos/src/main/java/com/azure/cosmos/implementation/PathsHelper.java#L745

2. toByteArray(..)

https://github.com/Azure/azure-sdk-for-java/blob/1300def7a6c810eb0b9f3a9fe175316e7f4f98f7/sdk/cosmos/azure-cosmos/src/main/java/com/azure/cosmos/implementation/RxDocumentServiceRequest.java#L1035

3. getUTF8BytesOrNull(..)

https://github.com/Azure/azure-sdk-for-java/blob/f770d24d9a41923298c86cbaf422241501086f1c/sdk/cosmos/azure-cosmos/src/main/java/com/azure/cosmos/implementation/Utils.java#L71
returns `null` in specific cases, evaluate that this design choice intentional instead of returning an empty array.

4. toByteArray(..)

https://github.com/Azure/azure-sdk-for-java/blob/f770d24d9a41923298c86cbaf422241501086f1c/sdk/cosmos/azure-cosmos/src/main/java/com/azure/cosmos/implementation/directconnectivity/rntbd/RntbdResponse.java#L313

**Comment by kushagraThapar** [comment]
Reviewed all of them and the downstream code is handling the null array.
