### ISSUE TITLE
[Cosmos v4] evaluate URF_UNREAD_PUBLIC_OR_PROTECTED_FIELD

### ISSUE THREAD

**Issue by anuchandy** [Azure/azure-sdk-for-java#9090]
Following non-private member variables are declared and initialized but never used.

https://github.com/Azure/azure-sdk-for-java/blob/f770d24d9a41923298c86cbaf422241501086f1c/sdk/cosmos/azure-cosmos/src/main/java/com/azure/cosmos/implementation/query/ParallelDocumentQueryExecutionContextBase.java#L69

https://github.com/Azure/azure-sdk-for-java/blob/f770d24d9a41923298c86cbaf422241501086f1c/sdk/cosmos/azure-cosmos/src/main/java/com/azure/cosmos/implementation/query/ParallelDocumentQueryExecutionContextBase.java#L57

https://github.com/Azure/azure-sdk-for-java/blob/f770d24d9a41923298c86cbaf422241501086f1c/sdk/cosmos/azure-cosmos/src/main/java/com/azure/cosmos/implementation/directconnectivity/ServiceConfig.java#L8

https://github.com/Azure/azure-sdk-for-java/blob/f770d24d9a41923298c86cbaf422241501086f1c/sdk/cosmos/azure-cosmos/src/main/java/com/azure/cosmos/implementation/directconnectivity/ServiceConfig.java#L9

https://github.com/Azure/azure-sdk-for-java/blob/f770d24d9a41923298c86cbaf422241501086f1c/sdk/cosmos/azure-cosmos/src/main/java/com/azure/cosmos/implementation/QueryMetrics.java#L22

**Comment by xinlian12** [comment]
PR has merged.
