### ISSUE TITLE
[Cosmos v4] Possible dropping of QueryMetrics 

### ISSUE THREAD

**Issue by anuchandy** [Azure/azure-sdk-for-java#9092]
The add method in [QueryMetrics](https://github.com/Azure/azure-sdk-for-java/blob/master/sdk/cosmos/azure-cosmos/src/main/java/com/azure/cosmos/implementation/QueryMetrics.java) is  shown below:

It creates a new `QueryMetrics` instance which contains items in the current `QueryMetrics` (on which `add` is called) and given list of QueryMetrics (`queryMetricsArgs`) i.e. this method is not mutating the object on which `add()` is called:

```java
public QueryMetrics add(QueryMetrics... queryMetricsArgs) {
    ArrayList<QueryMetrics> queryMetricsList = new ArrayList<QueryMetrics>();
    for (QueryMetrics queryMetrics : queryMetricsArgs) {
        queryMetricsList.add(queryMetrics);
    }
    queryMetricsList.add(this);
    return QueryMetrics.createFromCollection(queryMetricsList);
}
```

OrderUtils.java::[apply](https://github.com/Azure/azure-sdk-for-java/blob/1300def7a6c810eb0b9f3a9fe175316e7f4f98f7/sdk/cosmos/azure-cosmos/src/main/java/com/azure/cosmos/implementation/query/OrderByUtils.java#L70)() method uses this method as:

```java
queryMetricsMap.get(key).add(qm);
```

Note that there is a `QueryMetrics` object in `queryMetricsMap` identified by `key`, on which it calls add() but this call has no effect given return value is ignored.

Similar use of `add` can be found here as well:

https://github.com/Azure/azure-sdk-for-java/blob/1300def7a6c810eb0b9f3a9fe175316e7f4f98f7/sdk/cosmos/azure-cosmos/src/main/java/com/azure/cosmos/implementation/query/AggregateDocumentQueryExecutionContext.java#L92

**Comment by kushagraThapar** [comment]
Working on this.
