### ISSUE TITLE
[Cosmos v4] evaluate value computation in AsyncCache

### ISSUE THREAD

**Issue by anuchandy** [Azure/azure-sdk-for-java#9094]
Evaluate [this](https://github.com/Azure/azure-sdk-for-java/blob/1300def7a6c810eb0b9f3a9fe175316e7f4f98f7/sdk/cosmos/azure-cosmos/src/main/java/com/azure/cosmos/implementation/caches/AsyncCache.java#L94) code in AsyncCache type.

Logic here looks like:

```java
getAsync(TKey key,..) {
   //....
   if (initialLazyValue != null) {
    // ..
      return ..
   } else {
     // `initialLazyValue` will be `null` in this block.
     // `values` is a `ConcurrentHashMap`.
     AsyncLazy<TValue> resultAsyncLazy = values.merge(key, 
       asyncLazy,
       // Remapping function
       (lazyValue1, lazyValu2) -> lazyValue1 == initialLazyValue ? lazyValu2 : lazyValue1);
     return ..  
   }
}
```

1. `values` is a ConcurrentHashMap.
2. If `key` exists then remapping function will be called.
3. Existing values in ConcurrentHashMap is guaranteed to be `non-null.`

Here "lazyValue1 == initialLazyValue" is eqvalent to "non-null == null" so it is always "FALSE"

So the remapping function.

```java
(lazyValue1, lazyValu2) -> lazyValue1 == initialLazyValue ? lazyValu2 : lazyValue1);
```

is equlvalent to:

```java
(lazyValue1, lazyValu2) -> lazyValue1);
```

**Comment by kushagraThapar** [comment]
Will work on this.

**Comment by xinlian12** [comment]
no, the code needs to remain the way it is in case of race condition.
