### ISSUE TITLE
[Cosmos v4] Evaluate declared but unused member variables

### ISSUE THREAD

**Issue by anuchandy** [Azure/azure-sdk-for-java#9095]
Following class member variables are declared but never used:

https://github.com/Azure/azure-sdk-for-java/blob/1300def7a6c810eb0b9f3a9fe175316e7f4f98f7/sdk/cosmos/azure-cosmos/src/main/java/com/azure/cosmos/implementation/RxDocumentServiceRequest.java#L44

https://github.com/Azure/azure-sdk-for-java/blob/1300def7a6c810eb0b9f3a9fe175316e7f4f98f7/sdk/cosmos/azure-cosmos/src/main/java/com/azure/cosmos/implementation/directconnectivity/AddressResolver.java#L325

https://github.com/Azure/azure-sdk-for-java/blob/1300def7a6c810eb0b9f3a9fe175316e7f4f98f7/sdk/cosmos/azure-cosmos/src/main/java/com/azure/cosmos/implementation/directconnectivity/GlobalAddressResolver.java#L44

https://github.com/Azure/azure-sdk-for-java/blob/1300def7a6c810eb0b9f3a9fe175316e7f4f98f7/sdk/cosmos/azure-cosmos/src/main/java/com/azure/cosmos/implementation/directconnectivity/GlobalAddressResolver.java#L45

**Comment by xinlian12** [comment]
private volatile String resourceFullName;  -> Does not use in SDK anymore
private GatewayAddressCache gatewayAddressCache;   -> Does not use in SDK anymore
private AddressResolver addressResolver;  -> Does not use in SDK anymore

**Comment by xinlian12** [comment]
PR has merged.
