### ISSUE TITLE
[Cosmos v4] Possible cleanup: code duplication in switch cases

### ISSUE THREAD

**Issue by anuchandy** [Azure/azure-sdk-for-java#9097]
#### Duplciation_1

The switch case 
https://github.com/Azure/azure-sdk-for-java/blob/650ab28c669cf2132129abfd4da79007ae8f9e1a/sdk/cosmos/azure-cosmos/src/main/java/com/azure/cosmos/implementation/directconnectivity/ConsistencyReader.java#L213 and https://github.com/Azure/azure-sdk-for-java/blob/650ab28c669cf2132129abfd4da79007ae8f9e1a/sdk/cosmos/azure-cosmos/src/main/java/com/azure/cosmos/implementation/directconnectivity/ConsistencyReader.java#L217

has the same code.

#### Duplication_2

The switch case

https://github.com/Azure/azure-sdk-for-java/blob/650ab28c669cf2132129abfd4da79007ae8f9e1a/sdk/cosmos/azure-cosmos/src/main/java/com/azure/cosmos/implementation/directconnectivity/HttpTransportClient.java#L281

and 

https://github.com/Azure/azure-sdk-for-java/blob/650ab28c669cf2132129abfd4da79007ae8f9e1a/sdk/cosmos/azure-cosmos/src/main/java/com/azure/cosmos/implementation/directconnectivity/HttpTransportClient.java#L289

has the same code.

**Comment by xinlian12** [comment]
Duplicate 2 is not correct statement as they are using different method internally.

**Comment by xinlian12** [comment]
PR has merged.
