### ISSUE TITLE
[Cosmos v4] String comparison using == or != operators

### ISSUE THREAD

**Issue by anuchandy** [Azure/azure-sdk-for-java#9098]
== or != on string does reference comaprsions, consider using equality methods instead.
https://github.com/Azure/azure-sdk-for-java/blob/650ab28c669cf2132129abfd4da79007ae8f9e1a/sdk/cosmos/azure-cosmos/src/main/java/com/azure/cosmos/implementation/directconnectivity/AddressResolver.java#L516

**Comment by DanielBenniah** [comment]
@kushagraThapar Since the PR has been merged, can you close this issue, please?

**Comment by kushagraThapar** [comment]
Yes, sure. This is done. Thanks @DanielBenniah
