### ISSUE TITLE
[Cosmos v4] Sending a header to service that was never set

### ISSUE THREAD

**Issue by anuchandy** [Azure/azure-sdk-for-java#9099]
HttpTransportClient send `entityId` header:

https://github.com/Azure/azure-sdk-for-java/blob/650ab28c669cf2132129abfd4da79007ae8f9e1a/sdk/cosmos/azure-cosmos/src/main/java/com/azure/cosmos/implementation/directconnectivity/HttpTransportClient.java#L410

but this header value `entityId` is never set, which is declared in 

https://github.com/Azure/azure-sdk-for-java/blob/650ab28c669cf2132129abfd4da79007ae8f9e1a/sdk/cosmos/azure-cosmos/src/main/java/com/azure/cosmos/implementation/RxDocumentServiceRequest.java#L64

**Comment by kushagraThapar** [comment]
We can get rid of it I believe. Not worth sending null value (as entityId is string - which is null by default) . 
@moderakh  - thoughts ?

**Comment by kushagraThapar** [comment]
On reevaluating this, it is okay to keep sending it null for now.
