### ISSUE TITLE
[Cosmos v4] passing disallowed null value to reactor chain

### ISSUE THREAD

**Issue by anuchandy** [Azure/azure-sdk-for-java#9100]
The following code can result in `Mono.error(null)`, which will cause the reactor to throw NPE.
https://github.com/Azure/azure-sdk-for-java/blob/650ab28c669cf2132129abfd4da79007ae8f9e1a/sdk/cosmos/azure-cosmos/src/main/java/com/azure/cosmos/implementation/caches/RxPartitionKeyRangeCache.java#L152

**Comment by xinlian12** [comment]
PR has merged.
