### ISSUE TITLE
[Cosmos v4] Possible null passed to HttpUtils.urlEncode(token)

### ISSUE THREAD

**Issue by anuchandy** [Azure/azure-sdk-for-java#9101]
the token could be null based on the logic in this method, if so then we're passing null for URL.

https://github.com/Azure/azure-sdk-for-java/blob/650ab28c669cf2132129abfd4da79007ae8f9e1a/sdk/cosmos/azure-cosmos/src/main/java/com/azure/cosmos/implementation/directconnectivity/GatewayAddressCache.java#L292

**Comment by kushagraThapar** [comment]
This logic has been updated, so that token will never be null.
