### ISSUE TITLE
[Cosmos v4] Evaluate bitwise and operator and greater than operator 

### ISSUE THREAD

**Issue by anuchandy** [Azure/azure-sdk-for-java#9105]
https://github.com/Azure/azure-sdk-for-java/blob/650ab28c669cf2132129abfd4da79007ae8f9e1a/sdk/cosmos/azure-cosmos/src/main/java/com/azure/cosmos/implementation/ResourceId.java#L173

Since 128 is +ve value, the above code will work, but the recommendation is 
to use '!= 0' instead of '> 0'.

```java
((flag & COLLECTION_BIT_POS) > 0)
```
Using bit arithmetic and then comparing with the greater than the operator can lead to unexpected results, depending on the value of COLLECTION_BIT_POS. If COLLECTION_BIT_POS is a negative number, this is a candidate for a bug. Even when COLLECTION_BIT_POS is not negative, it is good practice to use '!= 0' instead of '> 0'.

**Comment by xinlian12** [comment]
PR has merged.
