### ISSUE TITLE
[Cosmos v4] Evaluate instanceof usage that always return true

### ISSUE THREAD

**Issue by anuchandy** [Azure/azure-sdk-for-java#9106]
In the below [code](https://github.com/Azure/azure-sdk-for-java/blob/650ab28c669cf2132129abfd4da79007ae8f9e1a/sdk/cosmos/azure-cosmos/src/main/java/com/azure/cosmos/implementation/PathsHelper.java#L57), `resourceType` is of `Resource`

```java
public static String generatePathForNameBased(Resource resourceType, 
String resourceOwnerFullName, 
String resourceName) {

   // ...
   } else if (resourceType instanceof Resource) {
        // just generic Resource type.
        return null;
   }
}
```

This instanceof test will always return true. Though this is safe, make sure it isn't an indication of some misunderstanding or some other logic error.

**Comment by xinlian12** [comment]
Validated the logic.
