### ISSUE TITLE
[Cosmos v4] Possible unsafe lazy initialization

### ISSUE THREAD

**Issue by anuchandy** [Azure/azure-sdk-for-java#9107]
Below [code](https://github.com/Azure/azure-sdk-for-java/blob/650ab28c669cf2132129abfd4da79007ae8f9e1a/sdk/cosmos/azure-cosmos/src/main/java/com/azure/cosmos/ConnectionPolicy.java#L56)

```java
    private static ConnectionPolicy defaultPolicy = null;

    public static ConnectionPolicy getDefaultPolicy() {
        if (ConnectionPolicy.defaultPolicy == null) {
            ConnectionPolicy.defaultPolicy = new ConnectionPolicy();
        }
        return ConnectionPolicy.defaultPolicy;
    }
```

If above lazy initialization is done for performance reasons then the safest solution is usually to declare the enclosing method `synchronized`. Otherwise, avoid lazy initialization and initialize static fields using static initializers. 

In this case, `new ConnectionPolicy()` doesn't look like a costly operation, maybe static initializers should be sufficient here.

**Comment by kushagraThapar** [comment]
Working on this.

**Comment by xinlian12** [comment]
It has been changed into return a new ConnectionPolicy for each call.
