### ISSUE TITLE
[Cosmos v4] evaluate negation of Comparator::compare return value

### ISSUE THREAD

**Issue by anuchandy** [Azure/azure-sdk-for-java#9109]
This following [code](https://github.com/Azure/azure-sdk-for-java/blob/650ab28c669cf2132129abfd4da79007ae8f9e1a/sdk/cosmos/azure-cosmos/src/main/java/com/azure/cosmos/implementation/query/orderbyquery/OrderbyRowComparer.java#L65)

```java
int cmp = ItemComparator.getInstance()
    .compare(result1.get(i).getItem(), result2.get(i).getItem());
if (cmp != 0) {
    switch (this.sortOrders.get(i)) {
    case Ascending:
        return cmp;
    case Descending:
        return -cmp;
    }
}
```

has spotbug error "RV_NEGATING_RESULT_OF_COMPARETO", please evaluate.

##### RV: Negating the result of compareTo()/compare() (RV_NEGATING_RESULT_OF_COMPARETO)

This code negatives the return value of a compareTo or compare method. This is a questionable or bad programming practice, since if the return value is Integer.MIN_VALUE, negating the return value won't negate the sign of the result. You can achieve the same intended result by reversing the order of the operands rather than by negating the results.

**Comment by DanielBenniah** [comment]
@kushagraThapar Can you close this issue, please.

**Comment by kushagraThapar** [comment]
@DanielBenniah  sure, thanks for letting me know. 
Closing this as the PR is merged.
