### ISSUE TITLE
[Cosmos v4] evaluate the unboxing of Boolean to boolean

### ISSUE THREAD

**Issue by anuchandy** [Azure/azure-sdk-for-java#9110]
The below JsonSerializable::[getBoolean](https://github.com/Azure/azure-sdk-for-java/blob/650ab28c669cf2132129abfd4da79007ae8f9e1a/sdk/cosmos/azure-cosmos/src/main/java/com/azure/cosmos/models/JsonSerializable.java#L262)

```java
public Boolean getBoolean(String propertyName) {
    if (this.has(propertyName) && this.propertyBag.hasNonNull(propertyName)) {
        return this.propertyBag.get(propertyName).asBoolean();
    } else {
        return null;
    }
}
```

return Nullable Boolean. This Boolean is unboxed to primitive boolean in the following methods. Check if it is safe to do the implicit conversion in below specific cases. if not then see we can do a null check and default to true|false.

https://github.com/Azure/azure-sdk-for-java/blob/650ab28c669cf2132129abfd4da79007ae8f9e1a/sdk/cosmos/azure-cosmos/src/main/java/com/azure/cosmos/implementation/directconnectivity/Address.java#L43

https://github.com/Azure/azure-sdk-for-java/blob/650ab28c669cf2132129abfd4da79007ae8f9e1a/sdk/cosmos/azure-cosmos/src/main/java/com/azure/cosmos/implementation/query/OrderByContinuationToken.java#L114

https://github.com/Azure/azure-sdk-for-java/blob/650ab28c669cf2132129abfd4da79007ae8f9e1a/sdk/cosmos/azure-cosmos/src/main/java/com/azure/cosmos/implementation/query/QueryInfo.java#L86

https://github.com/Azure/azure-sdk-for-java/blob/650ab28c669cf2132129abfd4da79007ae8f9e1a/sdk/cosmos/azure-cosmos/src/main/java/com/azure/cosmos/implementation/routing/Range.java#L111

https://github.com/Azure/azure-sdk-for-java/blob/650ab28c669cf2132129abfd4da79007ae8f9e1a/sdk/cosmos/azure-cosmos/src/main/java/com/azure/cosmos/implementation/routing/Range.java#L102

**Comment by kushagraThapar** [comment]
This has been fixed now, closing it.

**Comment by moderakh** [comment]
thank you @DanielBenniah for your contribution.
