### ISSUE TITLE
Re-Enable Consistently Failing Live Tests

### ISSUE THREAD

**Issue by alzimmermsft** [Azure/azure-sdk-for-java#9128]
Re-enable tests that were disabled in PR #9127 due to their consistent failures.

**Comment by joshfree** [comment]
@amishra-dev can you please track this work item on the Storage backlog?

**Comment by amishra-dev** [comment]
The failures were related to ARM templates for CPK and error in premium accounts. We should get the templates working for these tests working with Vincent's team.

**Comment by alzimmermsft** [comment]
Closing as these tests have been re-enabled
