### ISSUE TITLE
CosmosAsyncItemResponse::getRequestCharge() fails on international systems

### ISSUE THREAD

**Issue by tomekapc** [Azure/azure-sdk-for-java#9136]
**Describe the bug**
getRequestCharge() will fail on systems where a "," is used as a decimal separator.

***Exception or Stack Trace***
java.lang.NumberFormatException: For input string: "3,64"

**To Reproduce**
Set your locale to German and run this example code: [SampleCRUDQuickstartAsync.java](https://github.com/Azure-Samples/azure-cosmos-java-sql-api-samples/blob/master/src/main/java/com/azure/cosmos/examples/crudquickstart/async/SampleCRUDQuickstartAsync.java)
The method createFamilies() will fail.

**Setup (please complete the following information):**
 - OS: Windows
 - Java SDK v4 preview.2

**Additional context**
The machine used in this test has German locale defined and uses a "," as a decimal separator.

The source of this issue seems to be in the implementation of populatePartitionedQueryMetrics in DocumentProducer.java
[in this line here](https://github.com/Azure/azure-sdk-for-java/blob/2c32ea66cefeec207d9c88d5bff79961fc6e5cef/sdk/cosmos/azure-cosmos/src/main/java/com/azure/cosmos/implementation/query/DocumentProducer.java#L68)

The current locale will be used to produce the string and on some systems a "," will be used as a decimal separator. The locale won't be used by Double.parseDouble() (actually, why is the locale ignored by Double..?) when parsing the string which in the end leads to the NumberFormatException mentioned above.

Possible fix
1. set the locale and enforce a "." as a decimal separator:
String.format(Locale.US, "%f", floatValue)
or
2. don't use Double.parseDouble() and use NumberFormat etc. instead (?)

**Information Checklist**
Kindly make sure that you have added all the following information above and checkoff the required fields otherwise we will treat the issuer as an incomplete report
- [x] Bug Description Added
- [x] Repro Steps Added
- [x] Setup information Added

**Comment by joshfree** [comment]
Thanks for reporting this issue with the v4 preview 2 build of Cosmos @tomekapc.  Someone from the Cosmos team will follow up shortly.

/cc @kushagraThapar @anuchandy

**Comment by kushagraThapar** [comment]
@tomekapc I will pick it up in next release. Thanks for reporting this.

**Comment by jongio** [comment]
@kushagraThapar - Do you have an update on this? It is currently 155 days old.  Thanks, Jon

**Comment by kushagraThapar** [comment]
@jongio - apologies on delayed response, we couldn't pick this. 

@tomekapc - I looked at the code you have mentioned above, and I can't see the Double.parseDouble, we are using String.format, which internally uses the formatter with default Locale.

**Comment by jongio** [comment]
@kushagraThapar - Are you suggesting that they need to add Double.parseDouble?

**Comment by kushagraThapar** [comment]
@jongio  - we are investigating this issue. 

@mbhaskar - can you please provide an update with your investigation?

**Comment by mbhaskar** [comment]
@jongio Thanks for your patience. I am able to reproduce the issue, will prioritize this in the future release and update you once ready.

**Comment by pkonyves** [comment]
What is the workaround? I am trying with 4.3.2-beta.2 on a hungarian local windows machine.
When I debug `QueryMetricUtils#parseDelimitedString` I see the input:

```
totalExecutionTimeInMs=1.20;queryCompileTimeInMs=0.14;queryLogicalPlanBuildTimeInMs=0.05;queryPhysicalPlanBuildTimeInMs=0.10;queryOptimizationTimeInMs=0.01;VMExecutionTimeInMs=0.59;indexLookupTimeInMs=0.43;documentLoadTimeInMs=0.08;systemFunctionExecuteTimeInMs=0.02;userFunctionExecuteTimeInMs=0.00;retrievedDocumentCount=10;retrievedDocumentSize=4955;outputDocumentCount=10;outputDocumentSize=5014;writeOutputTimeInMs=0.02;indexUtilizationRatio=1.00;requestCharge=3,35
```

I even don't understand how this can be that only the `requestCharge` is comma delimited...
Is the locale sent to the HTTP Request by the SDK, and the API respond with localization enabled?

**Comment by pkonyves** [comment]
Workaround:
Use `Locale.setDefault(Locale.ENGLISH);` in you application.
