### ISSUE TITLE
GalleryImage and GalleryImageVersion tagged with @Beta in latest azure sdk

### ISSUE THREAD

**Issue by bhavyaSharma-appD** [Azure/azure-sdk-for-java#9150]
I am using methods of classes GalleryImage and GalleryImageVersion in my project. But, I see these classes have @Beta annotation added and java doc of @Beta mentions this:
/**
 * Indicates functionality that is in preview and as such is subject to change in non-backwards compatible ways in future releases,
 * including removal, regardless of any compatibility expectations set by the containing library version.
 */

I am using the latest library version https://mvnrepository.com/artifact/com.microsoft.azure/azure/1.31.1.

I have the below questions:
1. What are the plans to update this class in future releases and removal of @Beta tag?
2. What are the challenges in using these classes in latest azure SDK library?

**Comment by joshfree** [comment]
Thanks for posting this question @bhavyaSharma-appD. @yaohaizh can you please follow up?

**Comment by yungezz** [comment]
hi @xccc-msft could you pls have a look? thanks.

**Comment by xccc-msft** [comment]
@anuchandy Would you please share some info about why we set the @Beta annotation at that moment, is it some concern from service side for the preview functionality or from SDK side?

**Comment by bhavyaSharma-appD** [comment]
Hi @xccc-msft @anuchandy Any update on this?

**Comment by xccc-msft** [comment]
@bhavyaSharma-appD I just checked with @anuchandy for the background how we determine to add Beta annotation in the library. It seems we add `@Beta` for those preview features, which are defined via preview api versions, provided by service providers.

And for your questions, I checked with @yungezz that we don't have plan to change the APIs with Beta tags as no changes for those preview features from resource providers. But at the same time, we might not remove the `@Beta` as it help track the preview features, which are not placed in the swagger files of stable versions. 

So you should be good to use our library. Thanks.

**Comment by bhavyaSharma-appD** [comment]
@xccc-msft Could you please explain what do you mean by preview api versions and preview features?

**Comment by xccc-msft** [comment]
@bhavyaSharma-appD Not sure if you can access [the swagger of Azure REST APIs](https://github.com/Azure/azure-rest-api-specs/tree/master/specification). For each spec, the service team will put two folders, one is named `stable`, the other is `preview`. Inside the folder, there are APIs defined by swagger docs.

**Comment by bhavyaSharma-appD** [comment]
@xccc-msft I can access these but not sure which is relevant to our usecase. Could you please point me to the one related to our usecase?
Also, do you know why these apis related to shared image are not placed in the swagger files of stable versions?

**Comment by xccc-msft** [comment]
@bhavyaSharma-appD This should be the swagger related to [shared image](https://github.com/Azure/azure-rest-api-specs/blob/master/specification/compute/resource-manager/Microsoft.Compute/stable/2019-07-01/gallery.json).

**Comment by bhavyaSharma-appD** [comment]
Thanks @xccc-msft . Waiting for your response on second question "Also, do you know why these apis related to shared image are not placed in the swagger files of stable versions?"

**Comment by xccc-msft** [comment]
@bhavyaSharma-appD Yes, now shared image is under stable folder. I don't have much historical info about this. Normally the `@beta` is used when feature is in preview. As I mentioned before, we have no plan to change these APIs so you should be good to use our library. Thanks.

**Comment by xccc-msft** [comment]
The annotations have been removed via [Azure/azure-libraries-for-java#1188](https://github.com/Azure/azure-libraries-for-java/pull/1188).
The changes are available in [v1.34.0](https://github.com/Azure/azure-libraries-for-java/releases/tag/v1.34.0).
