### ISSUE TITLE
[BUG]com.azure.identity.AzureCliCredential is not public

### ISSUE THREAD

**Issue by sitase** [Azure/azure-sdk-for-java#9162]
**Describe the bug**
com.azure.identity.AzureCliCredential is not public
***Exception or Stack Trace***
N/A
**To Reproduce**
N/A
***Code Snippet***
N/A
**Expected behavior**
AzureCliCredential should be public (as well as its builder) just like the other types of credentials. This is necessary for making bespoke credential discovery strategies.
**Screenshots**
N/A
**Setup (please complete the following information):**
  - Version of the Library used
1.1.0-beta.2
**Additional context**

**Information Checklist**
Kindly make sure that you have added all the following information above and checkoff the required fields otherwise we will treat the issuer as an incomplete report
- [x] Bug Description Added
- [x] Repro Steps Added
- [x] Setup information Added

**Comment by joshfree** [comment]
Thanks for filing this issue on the 1.1.0-beta.2 release of azure-identity @sitase, we appreciate the feedback.  @g2vinay can you please investigate?

**Comment by g2vinay** [comment]
@sitase 
Thank you for reporting this issue.
We are currently working on the final design of AzureCliCredential before making it public.
Currently, it is available via DefaultAzureCredential only.
Adding @schaabs to add more details.

**Comment by jongio** [comment]
AzureCliCredential is now public in beta5
https://azuresdkdocs.blob.core.windows.net/$web/java/azure-identity/1.1.0-beta.5/index.html
https://search.maven.org/artifact/com.azure/azure-identity/1.1.0-beta.5/jar
