### ISSUE TITLE
Upload From File Reporter Tests Consistently Fail

### ISSUE THREAD

**Issue by alzimmermsft** [Azure/azure-sdk-for-java#9189]
Beginning on 03/18 the `Upload from file reporter` tests in Blobs are failing with an unexpected reporting count. These don't appear to be flaky tests as the count returned vs expected is identical across all 6 test runs.

https://dev.azure.com/azure-sdk/internal/_build/results?buildId=312439&view=ms.vss-test-web.build-test-results-tab&runId=9642130&resultId=101680&paneView=debug

**Comment by alzimmermsft** [comment]
@gapra-msft it appears this is still disabled, could we see if this is resolved?

**Comment by gapra-msft** [comment]
Yeah we can see if my recent PR helps this issue.

**Comment by gapra-msft** [comment]
Just linking the PR https://github.com/Azure/azure-sdk-for-java/pull/20964/files
