### ISSUE TITLE
[BUG] Interminent and recurring JsonParseException 

### ISSUE THREAD

**Issue by erzads** [Azure/azure-sdk-for-java#9238]
**Describe the bug**
Often when using the sdk or even plain http requests to fetch information from azure, an unexpected response is given. 
The response looks like html code, rather then JSON. 

***Exception or Stack Trace***
`java.lang.RuntimeException: com.fasterxml.jackson.core.JsonParseException: Unexpected character ('<' (code 60)): expected a valid value (number, String, array, object, 'true', 'false' or 'null')
 at [Source: (String)"<!doctype html>
<html>
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <title>Symantec CloudSOC™</title>
    <meta name="robots" content="noindex, nofollow" />
    <meta name="description" content="">
    <meta http-equiv="Content-Security-Policy" content="default-src * data: blob:;script-src *.elastica.net *.elastica-inc.com *.nr-data.net *.newrelic.com 'unsafe-inline' 'unsafe-eval' blob: data: 'self';style-src data: blob: 'unsafe-inline'"[truncated 1533 chars]; line: 1, column: 2]

	at rx.exceptions.Exceptions.propagate(Exceptions.java:57)
	at rx.observables.BlockingObservable.forEach(BlockingObservable.java:139) `

**To Reproduce**
I am not sure but to me, I just need to execute any sdk list operation. 

***Code Snippet***
azure.virtualMachines().listByResouceGroup
And many others.

**Expected behavior**
Every response should be a valid json. 

**Setup (please complete the following information):**
 - OS: windows
 - IDE : intelliJ
 - Version of the Library used 1.31.1

**Information Checklist**
Kindly make sure that you have added all the following information above and checkoff the required fields otherwise we will treat the issuer as an incomplete report
- [ x] Bug Description Added
- [ x] Repro Steps Added
- [x ] Setup information Added

**Comment by joshfree** [comment]
Thanks for posting this issue @erzads.  @yaohaizh can you please follow up?

**Comment by yungezz** [comment]
hi @xccc-msft could you pls help to have a look? thanks.

**Comment by xccc-msft** [comment]
@erzads I cannot reproduce this. Would you share more info about exception tracing or request/response you are getting?
