### ISSUE TITLE
Review ClientLogger Usage

### ISSUE THREAD

**Issue by alzimmermsft** [Azure/azure-sdk-for-java#9332]
Review uses of `ClientLogger` and in cases where the class is expected to be short lived and instantiated many times look into making the logger `static`.

**Comment by alzimmermsft** [comment]
Closing as this is being done on a per-need basis

**Comment by cgtz** [comment]
Hi @alzimmermsft, we found quite a few non-static ClientLogger instances in classes that are instantiated on every blob download. When using log4j2, where the instantiation of non static loggers can be rather expensive on certain jvm versions, this can take a significant % of cpu time.

For example, when one is downloading/uploading a single blob they would go through the following sequence:
1. Create ContainerClient for desired container
2. Create BlobClient/BlobAsyncClient for desired blob name
3. (Maybe create BlockBlobClient for usage of specific block blob apis)

All of these classes and their builders seem to have non static ClientLoggers. Could we make them static? Are there even any cases where the ClientLogger cannot be static?

Alternatively, do you have suggestions on how to use the blob storage SDK in a way that creates fewer short lived objects?
