### ISSUE TITLE
PatternAnalyzer and PatternTokenizer should accept an array of RegexFlags

### ISSUE THREAD

**Issue by heaths** [Azure/azure-sdk-for-java#9333]
Because it's expected that multiple `RegexFlags` may be used in `PatternAnalyzer` and `PatternTokenizer`, the `flags` property should be an array of `RegexFlags` that de/serialize as a |-delimited string.

**Comment by heaths** [comment]
Why was this closed? Did you fix it with a PR? Please link them.

**Comment by sima-zhu** [comment]
https://github.com/Azure/azure-sdk-for-java/commit/55d9fa87fac5052b6012dcce1b5d972d952dec22

**Comment by sima-zhu** [comment]
https://github.com/Azure/azure-sdk-for-java/pull/9203
