### ISSUE TITLE
What are the azure best practices for different sets of resources that are deployed together to deliver a complete customer facing service

### ISSUE THREAD

**Issue by amitarali** [Azure/azure-sdk-for-java#936]
In the solution we are building,  we have some confusion on which structures to map to Azure Resource group. We have structures like resourceset and ServiceOfferingInstance. A ServiceOfferingInstance is the complete application or a service requested by an user. A ServiceOfferingInstance contains one or more ResourceSet and each ResourceSet can have one or more VMs of same type. E.g. in a ServiceOfferingInstance, one ResourceSet represents presentation tier and other ResourceSet represents data tier.

Could you please advise on below queries.

If we have different set of resources in a ServiceOfferingInstance, are there Azure Functions/activities that expect to work against resources groups rather than individual resources or arbitrary identified resources?
What are the azure best practices for different sets of resources that are deployed together to deliver a complete customer facing service? Should this all be in one Resource Group or multiple resource groups for different sets of resources e.g. presentation tier, data tier etc.?

**Comment by martinsawicki** [comment]
Azure Resource Groups are meant to group resources that have the same lifecycle - i.e. they can be deleted together. It's up to the user what other purpose the grouping can be used for.
