### ISSUE TITLE
Enable Spotbugs check on All Track 2 SDK Samples and test code files.

### ISSUE THREAD

**Issue by g2vinay** [Azure/azure-sdk-for-java#9360]
Spotbugs check does not run on Track 2 Samples and Test code files currently.
Enable it in sdk/parents/azure-client-sdk-parent/pom.xml,  set this flag to true. : [ClickHere](https://github.com/Azure/azure-sdk-for-java/blob/bb07d3cdf421bfb821b974c16ffaa797b4473770/sdk/parents/azure-client-sdk-parent/pom.xml#L197) 
Fix the spotgubs issues in all the track 2 SDKs samples and test code files.

- [ ] `azure-search-documents` (#14755)

**Comment by conniey** [comment]
That would be nice. :) Where do I enable it when pom.client.xml does not exist?

**Comment by g2vinay** [comment]
> That would be nice. :) Where do I enable it when pom.client.xml does not exist?

That's a good point. :)
We need to update the sdk/parents/azure-client-sdk-parent/pom.xml
Specifically, set this flag to true. : [Click Here](https://github.com/Azure/azure-sdk-for-java/blob/bb07d3cdf421bfb821b974c16ffaa797b4473770/sdk/parents/azure-client-sdk-parent/pom.xml#L197)

**Comment by joshfree** [comment]
@g2vinay could you complete this enhancement for azure-identity ahead of its August GA?

**Comment by ki1729** [comment]
Unassigning myself form the issue, ServiceBus has spotbugs enabled, and no open issues reported from spotbugs
