### ISSUE TITLE
How to fetch VirtualNetworkGateway related to specific VirtualNetwork

### ISSUE THREAD

**Issue by shaikezam** [Azure/azure-sdk-for-java#9396]
**Query/Question**
Hi,
How can I to fetch VirtualNetworkGateway related to specific VirtualNetwork?
I can use `Azure.networks()` for fetching the VirtualNetworks and `Azure.virtualNetworkGateways()` for fetching VirtualNetworkGateways.

But how I can fetch VirtualNetworkGateway that created from specific VirtualNetwork?

Thanks,

Shai
![Untitled](https://user-images.githubusercontent.com/16984302/77331680-bd958180-6d29-11ea-85ec-476011a5c5f4.png)

**Comment by joshfree** [comment]
@yaohaizh can you please follow up on the question posted by @shaikezam?  Thanks

**Comment by yungezz** [comment]
HI @xccc-msft could you pls have a look? thanks.

**Comment by xccc-msft** [comment]
@shaikezam It seems there is no direct way to list virtual network gateways by virtual network. But you could be able to list all virtual network gateways (by resource group if it works for you), and verify if the gateway subnet belong to specific virtual network.
Please check below sample code if it helps.
```java
        String specificVirtualNetworkId = "ID of your virtual network";
        PagedList<VirtualNetworkGateway> virtualNetworkGateways = networkManager.virtualNetworkGateways().list();
        for (VirtualNetworkGateway virtualNetworkGateway : virtualNetworkGateways){
            for (VirtualNetworkGatewayIPConfiguration ipConfiguration : virtualNetworkGateway.ipConfigurations()) {
                String virtualNetworkId = ResourceUtils.parentResourceIdFromResourceId(ipConfiguration.getSubnet().inner().id());
                if (specificVirtualNetworkId.equals(virtualNetworkId)) {
                    //Do actions
                }
            }
        }
```

**Comment by shaikezam** [comment]
Hi @xccc-msft thanks for replay
What about:

> ((VirtualNetworkGatewayImpl) virtualNetworkGateway).defaultIPConfiguration().networkId()

For fetching the VirtualNetworkGateway's  network ID?

**Comment by xccc-msft** [comment]
@shaikezam Yes, you can use `networkId()`. It helps parse network ID from subnet ID internally. Please ignore previous sample I provided. I was checking the request/response for this part but I didn't notice it's already got derived inside the SDK.

**Comment by xccc-msft** [comment]
@shaikezam If it works for you please feel free to close this.
