### ISSUE TITLE
VM .withExistingPIP, .withExistingPrimaryNetwork, .withExistingNIC and other withExisting* should also accept a string resource ID

### ISSUE THREAD

**Issue by martinsawicki** [Azure/azure-sdk-for-java#940]
otherwise, the dev is forced to do a .get() on those resources before being able to supply them to the VM creation, but they shouldn't have to, they might have the list already persisted somewhere as resource IDs

**Comment by anuchandy** [comment]
agree, do we need to make explicit that we are accepting Id not name? i.e. `withExistingPrimaryNetworkById(String id)` ? the reason is, in case of resource group `WithExistingResourceGroup` we take name not id. In case of choosing subnet from an existing vnet we accept name.

**Comment by martinsawicki** [comment]
in case like there though, there is no other ID-accepting wither overload, so I think brevity is ok. Overloads make sense when the semantics are exactly the same --adding by ID and adding by reference has exactly the same semantics, so I think expecting an overload here would make more sense. Also, we'd make sure to name the input parameter "resourceId".

Resource groups are exceptional with multiple ways -- only resource groups are like that, so I wouldn't worry about consistency concerns with resource groups so much.

**Comment by yungezz** [comment]
hi @weidongxu-microsoft does fluent today support resource  id?

**Comment by weidongxu-microsoft** [comment]
No, not today's SDK.

Generally speaking this area is not very clear. On the root for these resources, service only need the id. However in swagger spec, it is not so clear, it might say "string", or "SubResource" (which is just an resource id wrapped), or a complete resource like "VirtualNetwork" (but still only id is needed).

Agree we should provide alternative overload to take id as "string" or "SubResource".

**Comment by yungezz** [comment]
thanks @weidongxu-microsoft could this be done at fluent gen layer? in Python, there's is_valid_resource_id and parse_resource_id methods from runtime, az cli will leverage those methods to determine whether input string is a valid resource id or string for name.

**Comment by weidongxu-microsoft** [comment]
For most, generated code is correct, and is definitely using SubResource if swagger specify so. And some heuristic stage would generate SubResource even if swagger gives concrete object e.g. "VirtualNetwork" (this is not enabled since it conflict with current code migrated from track1, and it can sometimes be wrong since it is heuristic).

I assume this is on Fluent premium? Part of it is a choice by manual written code to take e.g. `Network` object so it being clear and object-oriented (that this resource is Network), at the cost of performance.

**Comment by weidongxu-microsoft** [comment]
Please help investigate whether we should provide these overloads.
