### ISSUE TITLE
[BUG] exception when using okhttp based httpclient with Azure Key Vault

### ISSUE THREAD

**Issue by magooster** [Azure/azure-sdk-for-java#9403]
**Describe the bug**
When using okhttp httpclient with Azure key vault an exception is thrown when getting a key

***Exception or Stack Trace***
Exception in thread "main" java.lang.NoSuchMethodError: 'com.azure.core.http.ProxyOptions com.azure.core.http.ProxyOptions.fromConfiguration(com.azure.core.util.Configuration)'
	at com.azure.core.http.okhttp.OkHttpAsyncHttpClientBuilder.build(OkHttpAsyncHttpClientBuilder.java:203)
	at com.azure.core.http.okhttp.implementation.OkHttpClientProvider.createInstance(OkHttpClientProvider.java:14)
	at com.azure.core.implementation.http.HttpClientProviders.createInstance(HttpClientProviders.java:36)
	at com.azure.core.http.HttpClient.createDefault(HttpClient.java:27)
	at com.azure.core.http.HttpPipelineBuilder.build(HttpPipelineBuilder.java:61)
	at com.azure.security.keyvault.keys.KeyClientBuilder.buildAsyncClient(KeyClientBuilder.java:159)
	at com.azure.security.keyvault.keys.KeyClientBuilder.buildClient(KeyClientBuilder.java:103)
	at net.iaminnovative.App.main(App.java:102)

**To Reproduce**
Exclude netty httpclient and use okhttp

<dependency>
      <groupId>com.azure</groupId>
      <artifactId>azure-security-keyvault-keys</artifactId>
      <version>4.1.0</version>
      <exclusions>
        <exclusion>
          <groupId>com.azure</groupId>
          <artifactId>azure-core-http-netty</artifactId>
        </exclusion>
      </exclusions>
    </dependency>
    <dependency>
      <groupId>com.azure</groupId>
      <artifactId>azure-core-http-okhttp</artifactId>
      <version>1.2.0</version>
    </dependency>

***Code Snippet***

DefaultAzureCredential credential = new DefaultAzureCredentialBuilder().build();
KeyClient keyClient = new KeyClientBuilder()
                    .vaultUrl("<vaultname>")
                    .credential(credential)
                    .buildClient();

**Expected behavior**
key is retrieved from the vault

**Setup (please complete the following information):**
 - OS: MacOSX
 - IDE : Intellij
 - Version of the Library used: Azure key vault keys 4.1.0, Azure Core 1.2

**Additional context**
The following works 

HttpClient httpClient = new OkHttpAsyncHttpClientBuilder().configuration(Configuration.NONE).build();

DefaultAzureCredential credential = new DefaultAzureCredentialBuilder().build();

            KeyClient keyClient = new KeyClientBuilder()
                    .vaultUrl("vaultname")
                    .credential(credential)
                    .httpClient(httpClient)
                    .buildClient();

**Information Checklist**
Kindly make sure that you have added all the following information above and checkoff the required fields otherwise we will treat the issuer as an incomplete report
- [ x] Bug Description Added
- [ x] Repro Steps Added
- [ x] Setup information Added

**Comment by joshfree** [comment]
Thanks for reporting this @magooster.  @g2vinay can you please follow up?

**Comment by johnjanthony** [comment]
I am receiving the same error, using the NettyAsyncHttpClientBuilder:
`com/azure/storage/file/datalake/DataLakeServiceClientBuilder.buildClient:java.lang.NoSuchMethodError: com.azure.core.http.ProxyOptions.fromConfiguration(Lcom/azure/core/util/Configuration;)Lcom/azure/core/http/ProxyOptions;
    com.azure.core.http.netty.NettyAsyncHttpClientBuilder.build(NettyAsyncHttpClientBuilder.java:93)
    com.azure.core.http.netty.implementation.ReactorNettyClientProvider.createInstance(ReactorNettyClientProvider.java:14)
    com.azure.core.implementation.http.HttpClientProviders.createInstance(HttpClientProviders.java:36)
    com.azure.core.http.HttpClient.createDefault(HttpClient.java:27)
    com.azure.core.http.HttpPipelineBuilder.build(HttpPipelineBuilder.java:61)
    com.azure.storage.file.datalake.implementation.util.BuilderHelper.buildPipeline(BuilderHelper.java:107)
    com.azure.storage.file.datalake.DataLakeServiceClientBuilder.buildAsyncClient(DataLakeServiceClientBuilder.java:92)
    com.azure.storage.file.datalake.DataLakeServiceClientBuilder.buildClient(DataLakeServiceClientBuilder.java:78)`

**Comment by srnagar** [comment]
@magooster and @johnjanthony This is generally due to version incompatibility of some of the dependencies in the application.

Have you tried the instructions [in this wiki](https://github.com/Azure/azure-sdk-for-java/wiki/Frequently-Asked-Questions#im-getting-a-nosuchmethoderror-or-noclassdeffounderror)

**Comment by gapra-msft** [comment]
Hi @johnjanthony 

What version of azure-storage-file-datalake and azure-core-http-netty are you using?

**Comment by johnjanthony** [comment]
azure-core: 1.2.0
azure-storage-file-datalake: 12.0.1 
And I'm not specifically targeting azure-core-http-netty. Here's my **mvn dependency:tree**

[INFO] --- maven-dependency-plugin:2.8:tree (default-cli) @ rpdm-azure ---
[INFO] redpoint:rpdm-azure:jar:9.0.1-SNAPSHOT
[INFO] +- com.azure:azure-core:jar:1.2.0:compile
[INFO] |  +- com.fasterxml.jackson.datatype:jackson-datatype-jsr310:jar:2.10.0:compile
[INFO] |  |  +- com.fasterxml.jackson.core:jackson-annotations:jar:2.10.0:compile
[INFO] |  |  +- com.fasterxml.jackson.core:jackson-core:jar:2.10.0:compile
[INFO] |  |  \- com.fasterxml.jackson.core:jackson-databind:jar:2.10.0:compile
[INFO] |  +- com.fasterxml.jackson.dataformat:jackson-dataformat-xml:jar:2.10.0:compile
[INFO] |  |  +- com.fasterxml.jackson.module:jackson-module-jaxb-annotations:jar:2.10.0:compile
[INFO] |  |  |  +- jakarta.xml.bind:jakarta.xml.bind-api:jar:2.3.2:compile
[INFO] |  |  |  \- jakarta.activation:jakarta.activation-api:jar:1.2.1:compile
[INFO] |  |  +- org.codehaus.woodstox:stax2-api:jar:4.2:compile
[INFO] |  |  \- com.fasterxml.woodstox:woodstox-core:jar:6.0.1:compile
[INFO] |  +- org.slf4j:slf4j-api:jar:1.7.28:compile
[INFO] |  +- io.projectreactor:reactor-core:jar:3.3.0.RELEASE:compile
[INFO] |  |  \- org.reactivestreams:reactive-streams:jar:1.0.3:compile
[INFO] |  \- io.netty:netty-tcnative-boringssl-static:jar:2.0.26.Final:compile
[INFO] +- com.azure:azure-storage-file-datalake:jar:12.0.1:compile
[INFO] |  \- com.azure:azure-storage-blob:jar:12.5.0:compile
[INFO] |     \- com.azure:azure-storage-common:jar:12.5.0:compile
[INFO] |        \- com.azure:azure-core-http-netty:jar:1.4.0:compile
[INFO] |           +- io.netty:netty-handler:jar:4.1.44.Final:compile
[INFO] |           |  +- io.netty:netty-common:jar:4.1.44.Final:compile
[INFO] |           |  +- io.netty:netty-transport:jar:4.1.44.Final:compile
[INFO] |           |  |  \- io.netty:netty-resolver:jar:4.1.44.Final:compile
[INFO] |           |  \- io.netty:netty-codec:jar:4.1.44.Final:compile
[INFO] |           +- io.netty:netty-handler-proxy:jar:4.1.44.Final:compile
[INFO] |           |  \- io.netty:netty-codec-socks:jar:4.1.44.Final:compile
[INFO] |           +- io.netty:netty-buffer:jar:4.1.44.Final:compile
[INFO] |           +- io.netty:netty-codec-http:jar:4.1.44.Final:compile
[INFO] |           +- io.netty:netty-codec-http2:jar:4.1.44.Final:compile
[INFO] |           +- io.netty:netty-transport-native-unix-common:jar:4.1.44.Final:compile
[INFO] |           +- io.netty:netty-transport-native-epoll:jar:linux-x86_64:4.1.44.Final:compile
[INFO] |           \- io.projectreactor.netty:reactor-netty:jar:0.9.4.RELEASE:compile
[INFO] +- junit:junit:jar:4.11:compile
[INFO] |  \- org.hamcrest:hamcrest-core:jar:1.3:compile
[INFO] +- log4j:log4j:jar:1.2.17:compile
[INFO] +- commons-logging:commons-logging:jar:1.2:compile
[INFO] +- commons-io:commons-io:jar:2.4:compile
[INFO] \- commons-codec:commons-codec:jar:1.9:compile

**Comment by magooster** [comment]
Seems azure-security-keyvault-keys 4.1.0 only works with azure-core-http-okhttp 1.1.0 or earlier

I had used the same version as azure core (1.2.0) initially....

**Comment by magooster** [comment]
Using the default netty httpclient works with azure-security-keyvault-keys 4.1.0, azure-core 1.2.0 with azure-core-http-netty 1.2.0

**Comment by magooster** [comment]
azure-core-http-netty 1.4.0 gives the error - so check your dependencies...

**Comment by johnjanthony** [comment]
I've confirmed upgrading azure-core to 1.3.0 resolves my issue. Thank you -

**Comment by g2vinay** [comment]
@magooster
azure-security-keyvault-keys 4.1.0 is compatible with azure-core 1.2.0,  azure-core-http-netty 1.3.0 or earlier and azure-core-http-okhttp 1.1.0 or earlier.

if you would like to use  azure-core 1.3.0,  azure-core-http-netty 1.4.0 or azure-core-http-okhttp 1.2.0, then please upgrade to  azure-security-keyvault-keys 4.1.1
https://search.maven.org/artifact/com.azure/azure-security-keyvault-keys/4.1.1/jar
