### ISSUE TITLE
[FEATURE REQ] Move azure-libraries-for-java/vnext to azure-sdk-for-java

### ISSUE THREAD

**Issue by weidongxu-microsoft** [Azure/azure-sdk-for-java#9451]
Source repo: https://github.com/Azure/azure-libraries-for-java/tree/vnext

Target repo: https://github.com/Azure/azure-sdk-for-java

Initial plan https://github.com/weidongxu-microsoft/work-notes/blob/master/java-mgmt-sdk-migration-plan.md

---

> From: Peter Marcu 
> Hey, this is something that fell off the radar with all the shifts in teams but right now we have two places where Java libraries come from. We’ve been working to unify everything into https://github.com/Azure/azure-sdk-for-java but many of the management fluent libraries are still in https://github.com/Azure/azure-libraries-for-java. It would be good to come up with a plan to finish the alignment. I was just reviewing a bunch of bugs and customers are filing issues in the wrong places because they don’t know which repo to use. From their perspective, what are the azure libraries for java vs the azure sdk for java?

---

@mitchdenny @joshfree 

If we can agree on the folder structure, and on POM structure in principle, I would like to get files into folders in a single day (since our team is actively developing on the SDK on daily bases, so I would try to avoid having code in 2 places at same time).

If any advice, you can comment in the issue, or comment in Channel.

After initial file gets merged, we would set-up CI to do simple checks (compile and test).

Full restructuring could take one or more weeks, to make POM and code and CI pipeline conform to the standard on azure-sdk-for-java repository.

This [vnext](https://github.com/Azure/azure-libraries-for-java/tree/vnext) branch is latest Fluent management SDK developed using Azure Core.

The [master](https://github.com/Azure/azure-libraries-for-java) branch is legacy Fluent management SDK still in use. We might need to move it to azure-sdk-for-java as well (but not now). If you have suggestion (e.g. do we need to reserve a folder name for it?) please also advice.

cc @yungezz @ChenTanyi @xccc-msft @nickzhums

**Comment by mitchdenny** [comment]
We are going through a similar exercise now with Spring. Where we landed there was that the libraries would go into a ```sdk/spring``` directory, but longer term would split out into the service directory that most closely match the libraries they are using.

For this I suspect that there is a strong association with the underlying management libraries? That being the case perhaps the fluent variant of the library should build with its existing management library sibling (and live in that service directory?).

It might be a good opportunity to bring the management plane and the data plane SDK build systems even closer together? Still separate pipelines, but otherwise all part of the same POM hierarchy.

I would probably avoid bringing the legacy stuff we we can avoid it since it will complicate the servicing, unless the module names are completely different.

**Comment by Petermarcu** [comment]
If it makes sense to everyone, just doing it for the new wave on the new code generators would make sense to me. For context, I believe there is no management plane API for Java that we ship, its really the Fluent codegen that is the management plane library. Right?

**Comment by yungezz** [comment]
hi @mitchdenny we're trying to move fluent mgmt lib into sdk/<service_name>/mgmt folder as @weidongxu-microsoft  shared here https://github.com/weidongxu-microsoft/work-notes/blob/master/java-mgmt-sdk-migration-plan.md#folder-structure.
@Petermarcu yes we plan to move new Track2 now. this repo contains non-fluent mgmt packages which is purely from Track1 generator, such as https://github.com/Azure/azure-sdk-for-java/tree/master/sdk/authorization/mgmt-v2018_09_01_preview. No change on that part so far. convert them to Track2 is on our roadmap.

**Comment by Petermarcu** [comment]
Right, so fluent == mgmt for Java :)

**Comment by weidongxu-microsoft** [comment]
@mitchdenny 
I think this is the same directory structure we expect, that libraries moves to where it associates most. 

And we do expect to integrate it into the build system (though it might take more time, first stage we want to have it work as stand-alone so developers could still coding).

E.g., [azure-mgmt-compute](https://github.com/Azure/azure-libraries-for-java/tree/vnext/azure-mgmt-compute) is basically generated code (which is somehow similar to code generated in [mgmt-v2019_11_01](https://github.com/Azure/azure-sdk-for-java/tree/master/sdk/compute/mgmt-v2019_11_01)) + manually written code + tests + some dependencies to e.g. azure-mgmt-resources.

And we target to put it into `sdk/compute/mgmt`, which is what the library associated with, and is the expected service directory.

One notable thing about the different to existing auto-generated mgmt lib e.g. mgmt-v2019_11_01, is that for easy of use, these libraries got more interconnected dependencies.

For example, to make a compute resource, user is almost inevitably need to create a network resource (virtual network, subnet, NIC, etc.), and optional storage resource. Hence `sdk/compute/mgmt` (as we target) would have dependency on `sdk/network/mgmt` and `sdk/storage/mgmt`, as well as on `sdk/resources/mgmt`.

This might (or might not) affect a bit on the build system.

This dependencies is the norm since its first day, so we likely will not going to change it here.

And there is 2 outliers here. Though above libraries (compute, network, storage, etc.) can be used by itself, we provide an `azure` module to wrap them (just add all of them as dependencies) and provide more code as convenience. Also there is a `azure-sample` module to give lots of sample to user (one of the most valuable feature of the SDK).

For these 2 we do not have any existing directory, so the propose is to put them to `sdk/management`, as well as some other misc files.

**Comment by weidongxu-microsoft** [comment]
OK. I probably start it tomorrow.

**Comment by weidongxu-microsoft** [comment]
I've done a PR for trial run. Let me know your feedback. It is not meant to be the final result. We want to do it step by step, without blocking development.

**Comment by Petermarcu** [comment]
@weidongxu-microsoft Those dependencies should be fine.

**Comment by mitchdenny** [comment]
Adding comments to the PR.

**Comment by weidongxu-microsoft** [comment]
Added CI https://dev.azure.com/azure-sdk/public/_build?definitionId=1642&_a=summary

Project "public", name "java - fluent mgmt - ci.mgmt", folder "\fluentJava"

For now it only do compile and test.

Currently team is working to onboard checkstyle (re-use current configure for client).

**Comment by weidongxu-microsoft** [comment]
checkstyle done.

Working on spotbugs.

**Comment by yungezz** [comment]
code move done. close the issue now.
