### ISSUE TITLE
[BUG] NPE in azure-storage-file-datalake-12.0.1

### ISSUE THREAD

**Issue by ylemoigne** [Azure/azure-sdk-for-java#9461]
**Describe the bug**
NPE in azure-storage-file-datalake-12.0.1

***Exception or Stack Trace***

```
Caused by: java.lang.NullPointerException: text
	at java.base/java.util.Objects.requireNonNull(Objects.java:246) ~[na:na]
	at java.base/java.time.format.DateTimeFormatter.parse(DateTimeFormatter.java:1945) ~[na:na]
	at java.base/java.time.OffsetDateTime.parse(OffsetDateTime.java:402) ~[na:na]
	at com.azure.storage.file.datalake.Transforms.toPathItem(Transforms.java:258) ~[azure-storage-file-datalake-12.0.1.jar:na]
```

**To Reproduce**
List recursivly a datalake.

To be more specific, the `path.getLastModified()` return a null date which go to NPE while formatting at `com.azure.storage.file.datalake.Transforms.toPathItem(Transforms.java:258)`.

**Setup (please complete the following information):**
Bug in version 12.0.1

**Additional context**

**Information Checklist**
Kindly make sure that you have added all the following information above and checkoff the required fields otherwise we will treat the issuer as an incomplete report
- [x] Bug Description Added
- [x] Repro Steps Added
- [x] Setup information Added

**Comment by rickle-msft** [comment]
@ylemoigne Thank you for reporting this. @gapra-msft I think this is a known bug in the service, right? That it doesn't return the LMT when listing?

**Comment by gapra-msft** [comment]
Hi @ylemoigne 

Thank you for reporting this issue. I've created a PR to add a null check before parsing out the date.

You can expect this fix in an upcoming release.

Thanks
