### ISSUE TITLE
Cosmos emulator download script with retry

### ISSUE THREAD

**Issue by mitchdenny** [Azure/azure-sdk-for-java#9473]
We are experiencing some reliability issues with the download of the Cosmos emulator from the edge CDN. It will occasionally fail resulting in the build failing. To help add more resiliency we should improve the script to add retry logic.

Rather than add more complex loops to the YAML file we should instead extract out the existing download logic and put it into a script and then create another YAML file which wraps the script. Because we download the emulator across all platforms we should place this script, and the YAML file in the ```azure-sdk-tools``` repository common directory. But initially we can develop and debug it in the Java repo.

**Comment by chidozieononiwu** [comment]
@kushagraThapar @moderakh Is this still an issue? Have there been any recent failures? If so can you point to them, otherwise can we close this.

**Comment by kushagraThapar** [comment]
@chidozieononiwu This happens every now and then, but definitely less frequent than it used to happen back in the day (last year when we filed this issue). Did we add any retries or is it just better networking now ?
