### ISSUE TITLE
[FEATURE REQ] CosmosError should offer a getter for error messages 

### ISSUE THREAD

**Issue by tomekapc** [Azure/azure-sdk-for-java#9518]
**Is your feature request related to a problem? Please describe.**
[CosmosError.java](https://github.com/Azure/azure-sdk-for-java/blob/1de5c6901a4d6106df6c3eed6260984e248891e0/sdk/cosmos/azure-cosmos/src/main/java/com/azure/cosmos/models/CosmosError.java) should offer a way of accesing the `Error` property from the propertyBag.

Currently, when a `ConflictException` is thrown, one can't access the human readable error message. The only way to get there is to use toString() and to extract it from there. The information is available in the propertyBag but there is no getter for the array of `Errors`

**Describe the solution you'd like**
a new method like:
`public List<String>/Set<String> getErrors() { ... }`
accessing the propertyBag and extracting all entries from the `Errors` array.

**Additional context**
Cosmos DB
Java SDK v4 preview.2

**Information Checklist**
Kindly make sure that you have added all the following information above and checkoff the required fields otherwise we will treat the issuer as an incomplete report
- [x] Description Added
- [x] Expected solution specified

**Comment by tomekapc** [comment]
I discovered a better workaround:
`ArrayNode errorsNode = (ArrayNode) cce.getError().get("Errors");`
where `cce` is the `CosmosClientException`

Still - having a dedicated method `getErrors` would make it discoverable.

**Comment by joshfree** [comment]
Thanks for filing this issue @tomekapc.  @kushagraThapar or someone from the Cosmos team will follow up with you.

**Comment by kushagraThapar** [comment]
@simplynaveen20 will take a look at this shortly. Thanks for reporting this.

**Comment by kushagraThapar** [comment]
CosmosError is no longer a public class, instead use CosmosException which has the getters for message and exception details.
