### ISSUE TITLE
consider VirtualMachines#create(Creatable<VirtualMachine>...vms) to expose a simple way to parallelize the creation of multiple VMs

### ISSUE THREAD

**Issue by martinsawicki** [Azure/azure-sdk-for-java#952]
since the creation of VMs is particularly slow, creating multiple ones in a serial fashion is even worse. Advanced programmers will set up multithreading and async themselves, but to lower the barrier of entry and/or enable quick and dirty parallelization of VM creation, we could expose a `create()` method on the `VirtualMachines` collection container itself which would take an array of `Creatable<VirtualMachine>` and invoke the creation of these in parallel behind the scenes.

**Comment by anuchandy** [comment]
Some initial thoughts on the implementation side w.r.t sharing of `Creatable` dependencies between `Creatable` VMs.

We might want to consider the container (VirtualMachines) as a resource i.e. the one that inherits from `CreatableImpl` and implements `CreatableImpl::createResource` with NOP.

This way when we when we call `addCreatableDependency` multiple times with parameter as `creatable` VM, the DAG will be created in a way that  shares the dependencies between the VMs, that will ensure we call `createOrUpdate` only once per dependency.

This is just a thought ..

**Comment by martinsawicki** [comment]
thanks for explaining the logic in VM#withNewPIP. Now corrected with another checkin.

**Comment by martinsawicki** [comment]
done
