### ISSUE TITLE
[FEATURE REQ] Investigate way to handle additional parameters in model constructors.

### ISSUE THREAD

**Issue by kasobol-msft** [Azure/azure-sdk-for-java#9530]
This is follow up from https://github.com/Azure/azure-sdk-for-java/pull/9283 . 

Every time server side returns new piece of data we're adding properties to models. That results in necessity of adding new constructor(s) that capture new parameters and leaving old constructors in place for backwards compatibility. We should figure out a way how can we avoid multiplying constructors.

**Comment by gapra-msft** [comment]
I think this can be resolved by exposing an interface with getters on the public API and hiding the actual implementation of the type in the implementation package. See how blob changefeed exposes BlobChangefeedEvent and BlobChangefeedEventData

**Comment by kasobol-msft** [comment]
Yeah, I think this is the answer, hide implementation behind interface.

**Comment by alzimmermsft** [comment]
Closing this as resolved as there are patterns in place for evolving constructors to use the implementation interface pattern to allow the number of class properties to grow without needing to add new constructors each time.
