### ISSUE TITLE
[QUERY]

### ISSUE THREAD

**Issue by PK2702** [Azure/azure-sdk-for-java#9554]
**Query/Question**
A clear and concise ask/query.

***Why is this not a Bug or a feature Request?***
A clear explanation of why is this not a bug or a feature request?

**Setup (please complete the following information if applicable):**
 - IDE : [e.g. IntelliJ]
 - Version of the Library used
 
 **Information Checklist**
 Kindly make sure that you have added all the following information above and checkoff the required fields otherwise we will treat the issuer as an incomplete report
- [ ] Query Added
- [ ] Setup information Added

**Comment by rickle-msft** [comment]
This looks to have been accidentally submitted as there is no content. Closing.
