### ISSUE TITLE
`wrapList()` should be a static helper method

### ISSUE THREAD

**Issue by jianghaolu** [Azure/azure-sdk-for-java#956]
Currently the use of `wrapList()` is limited to collections. As an `impl` developer, I need `wrapList()` in models for listing child resources.

**Comment by martinsawicki** [comment]
i wonder how is the new need different from how we handled Network#subnets, or NSG#rules?

**Comment by jianghaolu** [comment]
They are properties on the parent model. The new need is an action that returns a list of child resources.

**Comment by praries880** [comment]
@jianghaolu has this issue been fixed?

**Comment by joshfree** [comment]
Closing old issue from 2016.
