### ISSUE TITLE
AzureConfigurableImpl.withMaxIdleConnections unused parameter

### ISSUE THREAD

**Issue by masarlabs** [Azure/azure-sdk-for-java#958]
Hello,
I think that in
https://github.com/Azure/azure-sdk-for-java/blob/457ac0079909991cba39e13f3ad878096208d030/azure-mgmt-resources/src/main/java/com/microsoft/azure/management/resources/fluentcore/arm/implementation/AzureConfigurableImpl.java

 public T withMaxIdleConnections(int maxIdleConnections) {
        this.restClientBuilder = restClientBuilder.withMaxIdleConnections(5);
        return (T) this;
    }

should be

 public T withMaxIdleConnections(int maxIdleConnections) {
        this.restClientBuilder = restClientBuilder.withMaxIdleConnections(maxIdleConnections);
        return (T) this;
    }

change '5' with 'maxIdleConnections'

**Comment by jianghaolu** [comment]
Good catch! Assigned my self.

**Comment by jianghaolu** [comment]
Fixed and released with beta3.
