### ISSUE TITLE
Ensure Date Header and Credential Policies Are After Retry

### ISSUE THREAD

**Issue by alzimmermsft** [Azure/azure-sdk-for-java#9608]
Recently an issue was fixed in the Storage client builders where the date and credential policies were added before retry, this resulted in a scenario where the date header wasn't being updated for the retry request. The credential policy may not need to be strictly after the retry policy, only in scenarios where it consumes the Date header or is time sensitive. Please validate the following service client builders and ensure they are applying these policies after the retry.

- [x] AppConfiguration @mssfang 
- [ ] Cosmos @kushagraThapar 
- [x] Form Recognizer @samvaity 
- [x] KeyVault @vcolin7 @g2vinay 
- [x] Search @sima-zhu 
- [x] Text Analytics @mssfang

**Comment by mssfang** [comment]
I saw that Storage Blob's BuilderHelper class is still having `AddDatePolicy` and `credentialPolicy` before addBeforeRetryPolicies(). Do i misunderstood it?

**Comment by alzimmermsft** [comment]
@mssfang the PR for Storage is still open, https://github.com/Azure/azure-sdk-for-java/pull/9529.

**Comment by sima-zhu** [comment]
Search has merged the fix.

**Comment by g2vinay** [comment]
@vcolin7 can you take a look for KV ?

**Comment by vcolin7** [comment]
No problem.

**Comment by vcolin7** [comment]
KeyVault clients don't include an AddDatePolicy since a Date header is not used by the services. Also, the credential policy is added to the pipeline after the RetryPolicy, so is seems this problem will not be present for us.

**Comment by alzimmermsft** [comment]
Closing as fixed.
