### ISSUE TITLE
Code-Snippets should exist in-place in source

### ISSUE THREAD

**Issue by scbedd** [Azure/azure-sdk-for-java#9612]
This is connected to PR #9330. Specifically, that PR updates CI to always replace the code-snippets _on the fly_ during the build. 

As a team, we would rather **not** exist in a world where CI is changing code just prior to release. While it may work short-term, I can forsee a situation where this bites us HARD. (package isn't checked appropriately, we ship weirdly broken code)

1. Test the Code Samples
2. Code Samples exist in place, so CI can avoid changing package code

Still investigating how we can make this happen.

**Comment by alzimmermsft** [comment]
Closing this as usage of `codesnippet-maven-plugin` resolves this issue.
