### ISSUE TITLE
[QUERY] Unable to set CosmosDB container properties via the 4.0.1-beta.1 Java SDK.

### ISSUE THREAD

**Issue by mattbalgeman** [Azure/azure-sdk-for-java#9644]
**Query/Question**
I'm attempting to update the default TTL and/or indexing policy on a container in Cosmos DB using the 4.0.1-beta.1 Java SDK.  I'm able to create the container correctly with those fields set appropriately, but when I use the same CosmosContainerProperties object to attempt to update those setting via the CosmosAsyncContainer.replace() method, I get an exception "java.lang.IllegalArgumentException: Entity with the specified id does not exist in the system."

I've been unable to find any documentation on how this should be done using the 4.0.1-beta.1 Java SDK, so I'm not sure if I'm heading in the wrong direction or if this method should be doing what I think it's supposed to do.

***Why is this not a Bug or a feature Request?***
This might be a Bug, but I'm unsure if it's an issue with the SDK or if I'm misunderstanding the usage of the API due to lack of example for this specific functionality.

**Setup (please complete the following information if applicable):**
 - OS: Windows 10
 - IDE : IntelliJ
 - Version of the Library used: 4.0.1-beta.1 Java SDK
 
 **Information Checklist**
 Kindly make sure that you have added all the following information above and checkoff the required fields otherwise we will treat the issuer as an incomplete report
- [X] Query Added
- [X] Setup information Added

**Comment by joshfree** [comment]
@mattbalgeman thanks for trying out the cosmos 4.0.1-beta.1 Java SDK and providing us some feedback.  @kushagraThapar could you follow up with @mattbalgeman please?

**Comment by kushagraThapar** [comment]
@mattbalgeman - Seems like you are hitting an issue not with container replace as that can be done simply in this way: 
```
Mono<CosmosAsyncContainerResponse> replacedContainer = container.replace(cosmosContainerProperties, new CosmosContainerRequestOptions());
```
What consistency are you on ?
Are you replacing the collection right after creating it ?
Can you please share the code snippet and exception stack trace ?

**Comment by mattbalgeman** [comment]
**What consistency are you on?**
I can reproduce this with the Default indexing policy: {"automatic":true,"indexingMode":"Consistent"}

**Are you replacing the collection right after creating it ?**
I'm doing the replacement right after createContainerIfNotExists().  I'm doing this so when I update the indexing policy, it will be updated to the new policy.  This problem occurs both when the collection is created and when it already exists.

**Can you please share the code snippet and exception stack trace ?**
Logs/Stack Trace:
```
2020-04-09 13:18:03.613 ERROR --- [a94de13b43]-1-6] c.a.c.i.ClientRetryPolicy                : locationEndpoint is null because ClientRetryPolicy::onBeforeRequest(.) is not invoked, probably request creation failed due to invalid options, serialization setting, etc.
2020-04-09 13:18:03.615 ERROR --- [a94de13b43]-1-6] i.RenameCollectionAwareClientRetryPolicy : onBeforeSendRequest is not invoked, encountered failure due to request being null
java.lang.IllegalArgumentException: Entity with the specified id does not exist in the system.
	at com.azure.cosmos.implementation.RxDocumentServiceRequest.<init>(RxDocumentServiceRequest.java:192)
	at com.azure.cosmos.implementation.RxDocumentServiceRequest.<init>(RxDocumentServiceRequest.java:220)
	at com.azure.cosmos.implementation.RxDocumentServiceRequest.<init>(RxDocumentServiceRequest.java:262)
	at com.azure.cosmos.implementation.RxDocumentServiceRequest.create(RxDocumentServiceRequest.java:378)
	at com.azure.cosmos.implementation.RxDocumentClientImpl.replaceCollectionInternal(RxDocumentClientImpl.java:628)
	at com.azure.cosmos.implementation.RxDocumentClientImpl.lambda$replaceCollection$9(RxDocumentClientImpl.java:612)
	at com.azure.cosmos.implementation.ObservableHelper.lambda$inlineIfPossibleAsObs$1(ObservableHelper.java:44)
	at com.azure.cosmos.implementation.BackoffRetryUtility.lambda$executeRetry$0(BackoffRetryUtility.java:34)
	at reactor.core.publisher.MonoDefer.subscribe(MonoDefer.java:44)
	at reactor.core.publisher.FluxRetryWhen.subscribe(FluxRetryWhen.java:79)
	at reactor.core.publisher.MonoRetryWhen.subscribeOrReturn(MonoRetryWhen.java:46)
	at reactor.core.publisher.Mono.subscribe(Mono.java:4195)
	at reactor.core.publisher.Mono.block(Mono.java:1665)
	at com.[SNIP].Service.setupContainer([SNIP]Service.java:395)
[SNIP]
	at java.lang.Thread.run(Thread.java:748)
2020-04-09 13:18:09.660 ERROR --- [a94de13b43]-1-6] c.m.l.h.s.d.UnitLocationStorageService   : setupContainer(): Unable to update properties for container UnitLocation in database Test-CQ-Customer. e: Entity with the specified id does not exist in the system.
```
Code Snippet:
```
    private CosmosAsyncContainer setupContainer(CosmosAsyncDatabase database, CosmosContainerProperties containerProperties) {
        logger.info("setupContainer(): Create container " + containerProperties.getId() + " if not exists.");
        AtomicReference<CosmosAsyncContainer> container = new AtomicReference<>();

        Mono<CosmosAsyncContainerResponse> containerIfNotExists = database.createContainerIfNotExists(containerProperties);
        containerIfNotExists.flatMap(containerResponse -> {
            container.set(containerResponse.getContainer());
            logger.info("setupContainer(): Container " + container.get().getId() + " exists/created in " + database.getId());
            return Mono.empty();
        }).onErrorResume((exception) -> {
            logger.error("setupContainer(): Unable to create container " + containerProperties.getId() +
                    " in database " + database.getId() +
                    ". e: " + exception.getLocalizedMessage());
            container.set(null);
            return Mono.empty();
        }).block();


        // TODO: https://dev.azure.com/msi-cie/Location-Service/_workitems/edit/56553
        Mono<CosmosAsyncContainerResponse> propertiesReplace = container.get().replace(containerProperties, new CosmosContainerRequestOptions());
        propertiesReplace.flatMap(containerResponse -> {
            logger.info("setupContainer(): Container " + container.get().getId() + " in " + database.getId() +
                    "has been updated with it's new properties.");
            return Mono.empty();
        }).onErrorResume((exception) -> {
            logger.error("setupContainer(): Unable to update properties for container " + containerProperties.getId() +
                    " in database " + database.getId() +
                    ". e: " + exception.getLocalizedMessage());
            return Mono.empty();
        }).block();

        return container.get();
    }
```

**Comment by kushagraThapar** [comment]
@mattbalgeman  - thanks for sharing more details. I actually meant consistency level of the database (Strong, Session, Eventual, etc). Since you mentioned this is also happening on collections that are already present, seems like a bug to me. 
I will try to reproduce it on a stand alone application and will update you.

**Comment by anfeldma-ms** [comment]
FYI we reproduced this error on our side with Eventual consistency. I have shared the code with Kushagra and the investigation will continue.

**Comment by kushagraThapar** [comment]
@mattbalgeman We confirm this is a bug, will fix this soon. Stay tuned :)

**Comment by mattbalgeman** [comment]
I'm not sure if you care at this point, but we're using the default consistency which, based on the Default consistency pane, appears to be Session.

Thanks for the update all.

**Comment by anfeldma-ms** [comment]
@mattbalgeman thanks for the info. We see this with both Eventual and Session so that appears not to have an impact.

**Comment by kushagraThapar** [comment]
@mattbalgeman - this is not a bug, I was able to replace the collection. We were missing one small piece .. cosmosContainerProperties - need to be updated as well, after container creation, as cosmosdb sets important properties from backend when returning the response. 
Here is how it should be used : 
```
Mono<CosmosAsyncContainerResponse> containerIfNotExists = database.createContainerIfNotExists(containerProperties, 400);

        //  Create container with 400 RU/s
        CosmosAsyncContainerResponse cosmosContainerResponse = containerIfNotExists.block();
        container = cosmosContainerResponse.getContainer();
        //  </CreateContainerIfNotExists>

        //Modify existing container - MAKE SURE TO GET LATEST PROPERTIES FROM RESPONSE
        containerProperties = cosmosContainerResponse.getProperties();
        Mono<CosmosAsyncContainerResponse> propertiesReplace = container.replace(containerProperties, new CosmosContainerRequestOptions());
```

**Comment by mattbalgeman** [comment]
Howdy all,  Just wanted to circle back and let you know that this solved the issue for me.  Thanks for the support.  Much appreciated.
