### ISSUE TITLE
expose NIC#effectiveNetworkSecurityGroups()

### ISSUE THREAD

**Issue by martinsawicki** [Azure/azure-sdk-for-java#965]
new feature in Networking

**Comment by iscai-msft** [comment]
It appears that we currently [support this](https://github.com/Azure/azure-sdk-for-java/blob/36972c462fa891e61549c22e0a481ca3b1adac59/network/resource-manager/v2018_08_01/src/main/java/com/microsoft/azure/management/network/v2018_08_01/NetworkInterface.java#L75) at this time. Closing this now.
