### ISSUE TITLE
Broken link for "Simply authenticate" on https://github.com/Azure/azure-sdk-for-java/tree/0.9[BUG]

### ISSUE THREAD

**Issue by Sagar2366** [Azure/azure-sdk-for-java#9656]
Please check and update link for simply authenticate on this page : 
https://github.com/Azure/azure-sdk-for-java/tree/0.9

**Comment by joshfree** [comment]
Thanks for reporting the broken link in the readme.md @Sagar2366.  @yaohaizh could you please follow up?

**Comment by yungezz** [comment]
hi @Sagar2366 are you looking for guide to authenticate with Azure Resource Manmager?

**Comment by Sagar2366** [comment]
@yungezz ,yes it would be great if you help me in that. Also I am looking for way to create aks cluster using java sdk.

**Comment by yungezz** [comment]
HI @xccc-msft could you pls help here with some guide/example code? thanks.

**Comment by xccc-msft** [comment]
@Sagar2366 Can you please check if [this link](https://github.com/Azure/azure-libraries-for-java/blob/master/azure-samples/src/main/java/com/microsoft/azure/management/containerservice/samples/ManageContainerServiceWithKubernetesOrchestrator.java) helps?

**Comment by Sagar2366** [comment]
Yes sure. Thanks @xccc-msft and @yungezz. I will try and get back to you. Is thee any other way to reach out to you for help - community forum or email ? Or is it fine to discuss this issue here on GitHub ?

**Comment by xccc-msft** [comment]
@Sagar2366 You can also open issue within the repo from the link I just shared if you have questions for the sample. For the branch named 0.9 here, I think it's legacy branch so no one maintenance it anymore. I would suggest to close this one.
BTW what's the SDK version you are using now?

**Comment by Sagar2366** [comment]
I am using SDK version 1.1.0

Is it latest version?
Sure, I'll close this issue and create new I'm case if I find any problem.

Thanks for your help.

**Comment by xccc-msft** [comment]
@Sagar2366 Can you share the artifact ID? It looks you are not using mgmt SDK for Java.

**Comment by Sagar2366** [comment]
I followed this document from Microsoft Azure site -
https://docs.microsoft.com/en-us/azure/virtual-machines/windows/java

which installed all the libraries required for my project using maven.

When you asked me azure sdk, I thought it is dependency as following
details :

GroupId : com.microsoft.azure
ArtifactId : azure
Version : 1.1.0

Please correct me if I am wrong.

**Comment by xccc-msft** [comment]
@Sagar2366 It's mgmt SDK for Java. You should be good to check if any [sample](https://github.com/Azure/azure-libraries-for-java/tree/master/azure-samples/src/main/java/com/microsoft/azure/management) there works for you. The only thing is that our latest version is 1.32.1 now, which is quite different from 1.1.0. I would suggest to upgrade the SDK version in your project first so you can find more supported features.

**Comment by Sagar2366** [comment]
Ok Sure.

**Comment by Sagar2366** [comment]
One more question - How can I create SSH private key and public key ? I
want to use SSHShell and Utils classes to create ssh keys but they are not
included into azure sdk.
Is there any other way to achieve that?

**Comment by xccc-msft** [comment]
@Sagar2366 Are you looking for [sample like this](https://github.com/Azure/azure-libraries-for-java/blob/master/azure-samples/src/main/java/com/microsoft/azure/management/samples/SSHShell.java)? You can find example such as in [DockerUtils](https://github.com/Azure/azure-libraries-for-java/blob/master/azure-samples/src/main/java/com/microsoft/azure/management/samples/DockerUtils.java#L252), [ManageManagedDisks](https://github.com/Azure/azure-libraries-for-java/blob/master/azure-samples/src/main/java/com/microsoft/azure/management/compute/samples/ManageManagedDisks.java#L455)

**Comment by Sagar2366** [comment]
Yes, but do I need to copy entire SSHShell class to access it's methods
because it is not present in Azure SDK ?

I want to access it to follow steps given in the azure sdk to create aks
cluster.

**Comment by xccc-msft** [comment]
@Sagar2366 Yes, you can copy this and modify as per your project requirement. Azure SDK will provide the kit of classes for Azure service connection. But for SSHShell, it's just a class to help render sample scenarios. You can either copy this or create new one based on your requirement if you want to follow the sample steps.

**Comment by weidongxu-microsoft** [comment]
Latest mgmt SDK (e.g. 2.6.0) have feature on service to generate an SSH key pair for you. (I am not sure about the cost)

```
            azure.virtualMachines().manager().serviceClient().getSshPublicKeys().create("rg", "name", new SshPublicKeyResourceInner().withLocation(""));
            SshPublicKeyGenerateKeyPairResultInner keyPairResult = azure.virtualMachines().manager().serviceClient().getSshPublicKeys().generateKeyPair("rg", "name");
```
