### ISSUE TITLE
[Cosmos] Remove unused classes that were added from shaded libraries

### ISSUE THREAD

**Issue by srnagar** [Azure/azure-sdk-for-java#9705]
Remove classes that are not used in:
[guava25 package](https://github.com/Azure/azure-sdk-for-java/tree/master/sdk/cosmos/azure-cosmos/src/main/java/com/azure/cosmos/implementation/guava25)
[guava27 package](https://github.com/Azure/azure-sdk-for-java/tree/master/sdk/cosmos/azure-cosmos/src/main/java/com/azure/cosmos/implementation/guava27)
[apachecommons package](https://github.com/Azure/azure-sdk-for-java/tree/master/sdk/cosmos/azure-cosmos/src/main/java/com/azure/cosmos/implementation/apachecommons)

**Comment by anuchandy** [comment]
@srnagar - a lot of the types are referenced indirectly (via inheritances, composition, utility) by the few types that the cosmos directly use. I removed many classes that were not referenced at all, but yes many methods in shaded types can be removed but need to ensure that won't cause any break.

**Comment by joshfree** [comment]
Adding missing `cosmos` and `client` label so this will show up in the Cosmos' team radar now.

**Comment by kushagraThapar** [comment]
Went over the classes in these packages, and currently all of them are being used. Will circle back on this once we are at cusp of developing next major version of Java SDK for Cosmos DB.
