### ISSUE TITLE
Add utility method to convert incoming stream to Flux<ByteBuffer> 

### ISSUE THREAD

**Issue by samvaity** [Azure/azure-sdk-for-java#9716]
Add utility methods into Azure Core to support the conversion of the incoming input stream to `Flux<ByteBuffer>`

**Comment by anuchandy** [comment]
@samvaity in case it help, I wrote one something similar for okhttp https://github.com/Azure/azure-sdk-for-java/blob/04f5f53a5b1b5b26b3a8b521b15d25b6403a1bfe/sdk/core/azure-core-http-okhttp/src/main/java/com/azure/core/http/okhttp/OkHttpAsyncHttpClient.java#L305

You still need to take care of closing the stream, see the caller part of this method.

**Comment by srnagar** [comment]
Since this is required in multiple places, I suggest we move the utility method @anuchandy mentioned to azure-core utils.

@samvaity, @mssfang and @anuchandy

**Comment by anuchandy** [comment]
@alzimmermsft when we enable this in azure-core, maybe its good not updating OkHttpClient to use it. 
Though okio exposes the response stream as InputStream, it's a special stream with internal housekeeping to ensure it's methods (read, close) are not called concurrently. I remember running into a rare concurrency edge-case when canceling resulting Flux. Unfortunately, no idea how it can be addressed without incurring locks, so keeping OkHttpClient as it is may save some effort later.
