### ISSUE TITLE
AKS cluster creation is failing with Azure SDK

### ISSUE THREAD

**Issue by Sagar2366** [Azure/azure-sdk-for-java#9748]
I am using Azure SDK - 1.30.0 as suggested in this discussion : https://github.com/Azure/azure-sdk-for-java/issues/9656#issuecomment-606425420

For trial purpose I am using free subscription and I am trying to create an aks cluster with the examples provided in samples  at here : https://github.com/Azure/azure-libraries-for-java/blob/master/azure-samples/src/main/java/com/microsoft/azure/management/containerservice/samples/ManageContainerServiceWithKubernetesOrchestrator.java

AKS cluster creation from portal is successful with FREE subscription but it is throwing error when I provide same location and vm type.

Error : 
An error has occurred in subscription xyz, resourceGroup: aks-rsg1 request: Provisioning of resource(s) for container service aks-aks-1 in resource group aks-rsg1 failed. Message: {
  "code": "InvalidTemplateDeployment",
  "message": "Provisioning of resource(s) for container service aks-aks-1 in resource group aks-rsg1 failed. Message: The template deployment failed with error: 'The resource with id: '/subscriptions/xyz/resourceGroups/aks-rsg1/providers/Microsoft.Compute/virtualMachines/k8s-master-39895793-0' failed validation with message: 'The requested size for resource '/subscriptions/xyz/resourceGroups/aks-rsg1/providers/Microsoft.Compute/virtualMachines/k8s-master-39895793-0' is currently not available in location 'westus' zones '' for subscription xyz'. Please try another size or deploy to a different location or zones. See https://aka.ms/azureskunotavailable for details.'.'.. Details: "
 }. Details: 

Any help would be highly appreciated, thanks.

**Comment by joshfree** [comment]
@xccc-msft could you please follow up?

**Comment by xccc-msft** [comment]
@Sagar2366 This messaged is returned by server end. Can you please try with different location/vm size?

**Comment by Jen7714** [comment]
Please try again and/or try with a different location. Closing for now as that should be resolved.
