### ISSUE TITLE
Invalid header value when using sdk to connect

### ISSUE THREAD

**Issue by raintears** [Azure/azure-sdk-for-java#976]
Hi I was trying to connect to my azure storage using my own account and key but somehow it states the error: **The value for one of the HTTP headers is not in the correct format.** 

Here's my code

```
CloudStorageAccount acc = new CloudStorageAccount(new StorageCredentialsAccountAndKey(accountName, key));
CloudBlobClient client = acc.createCloudBlobClient();
CloudBlobContainer container = client.getContainerReference(containerName);
container.createIfNotExists();
```

it has been working for some time but today it suddenly stops working when the code reaches the container.createIfNotExists(); and I'm really not sure what I got to do since it has been working for me last time?

Please help!!

**Comment by jianghaolu** [comment]
Hi @raintears 
I'm terribly sorry for replying late - we were actively developing the next iteration of the management libraries. If you can file your issue in this repo: https://github.com/azure/azure-storage-java, there will be storage experts who can answer you question.
