### ISSUE TITLE
How do we set timeout for azure operations executed using ResourceManagementClient  (azure beta1)

### ISSUE THREAD

**Issue by nihalnaik25** [Azure/azure-sdk-for-java#977]
How do we set timeout for azure operations executed using ResourceManagementClient  (azure beta1)

Description : We have seen that operations such as getProvidersOperations().list etc. hang forever due to some environmental issues

Query : Is there a way to set some timeout for ResourceManagementClient such that if any operations takes more than a specified time, it throws timeout exception

Thanks in Advance

**Comment by jianghaolu** [comment]
Please refer to https://github.com/Azure/azure-sdk-for-java/wiki/Client-configuration for how to set timeouts on the client. Note the documentation only works for beta2 and beta3.
