### ISSUE TITLE
[FEATURE REQ] eventhubs: Be able to specify a hostname to connect to other than the namespace's FQDN.

### ISSUE THREAD

**Issue by favoretti** [Azure/azure-sdk-for-java#9788]
In a case where you need to use custom DNS name for a private EventHub endpoint and do not have the ability to setup up DNS forwarding from on-premise to Azure DNS you need to split the Endpoint namespace name from the actual hostname to connect to.

Ideally something like a connection string parameter `customHostName`, where you could specify a host to connect to.

To give an example. Host `myprivateeventhub.servicebus.windows.net` resolves within Azure VNET to `192.168.0.1` (private ip), outside resolves to `35.21.22.45` (public ip). Once you connect to it from on-prem via an ExpressRoute - if you don't have DNS forwarding on-prem it will resolve in a public IP, and you'll go over the internet rather than ER. If you then create a split-horizon DNS zone, say `privateendpoints.company.com` and add an entry there `myprivateeventhub.privateendpoints.company.com` pointing to `192.168.0.1` - you can circumvent the problem of not being able to forward DNS. If you change that in Endpoint connection string now - lib will assume that the namespace name is also your custom FQDN and that, obviously, won't work.

**Comment by favoretti** [comment]
I have an attempt on implementing this, but as soon as I override hostname for Reactor connections hell breaks loose. CBS channels works ok, as soon as second link is opened remoteTarget is empty for whatever reason:

```
2395 [single-1] INFO com.azure.core.amqp.implementation.handler.SendLinkHandler  - onLinkRemoteOpen connectionId[MF_4c08cd_1585852723279], linkName[my-link-name], remoteTarget[null], remoteSource[null], action[waitingForError]
```

ReactorSender fails on `getEndpointStates()`.

**Comment by favoretti** [comment]
And I had an implementation that actually works here: https://github.com/Azure/azure-event-hubs-java/pull/465, before I figured out that repo was abandoned :)

**Comment by samuelkoppes** [comment]
We have accepted this ask into our internal backlog, and we will evaluate addressing it during the first half of 2021. Thank you for sharing this idea!

**Comment by ramya-rao-a** [comment]
Related design discussion: https://github.com/Azure/azure-sdk/issues/1367
