### ISSUE TITLE
HDInsight management plane sdk should expose setters for clientId and principalId

### ISSUE THREAD

**Issue by jesinity** [Azure/azure-sdk-for-java#9871]
**Describe the bug**
The following class
https://docs.microsoft.com/en-us/java/api/com.microsoft.azure.management.hdinsight.v2018_06_01_preview.clusteridentityuserassignedidentitiesvalue?view=azure-java-stable

should provide a way to set `clientId` and `principalId`, but there is no way whatshoever.
Something should be changed in the codegen to make it possible, as these properties need to be provided on the client side.

**Comment by joshfree** [comment]
Thanks for filing this issue on HDInsight management plane SDK @jesinity.  @yungezz can you please assist?

**Comment by yungezz** [comment]
hi @xccc-msft could you pls help to have a look? thanks

**Comment by xccc-msft** [comment]
@jesinity The `clientId` and `principalId` are set as [read-only properties](https://github.com/Azure/azure-rest-api-specs/blob/master/specification/hdinsight/resource-manager/Microsoft.HDInsight/stable/2018-06-01-preview/cluster.json#L1373-L1389) in swagger. I just add Service Attention label so service team would help look into it.

**Comment by aim-for-better** [comment]
We are investigating whether this is a reasonable feature request. It will take some time.

**Comment by aim-for-better** [comment]
@jesinity Could you please explain why you need to set the clientId and principalId ?
And could you please introduce more about your scenario?   This should be readonly because it returned from backend.

**Comment by aim-for-better** [comment]
Hi @jesinity , we are waiting for your reply.

**Comment by aim-for-better** [comment]
This is by design, because this is only returned from backend side. We hope customer can give more details so that we can help the customer and check whether there is a scenario that it is must exposed but there is no response from customer.

Just close it. If customer still have such issue please reopen it.
