### ISSUE TITLE
Recording policy should scrub account name before recording

### ISSUE THREAD

**Issue by rickle-msft** [Azure/azure-sdk-for-java#9879]
The host is ignored anyway, and it would be good if we weren't publishing our account names on github.

**Comment by joshfree** [comment]
@sima-zhu could you please assist?

**Comment by sima-zhu** [comment]
@joshfree Will take it.

**Comment by sima-zhu** [comment]
Will address the issue into two parts:
1. Make changes on RecordNetworkPolicy
1. Re-record each client library.

**Comment by sima-zhu** [comment]
1. Start working on azure-storage-blob.

**Comment by alzimmermsft** [comment]
Fixed in #10023

**Comment by vhvb1989** [comment]
@alzimmermsft , for a service like Key Vault, the account name will be found also in the response payload.  A Key Vault key/secret/cert is a URL containing the host name.  
So, in those cases, the account name is still exposed.

**Comment by alzimmermsft** [comment]
@vhvb1989 there is a separate architecture for SDKs to apply their own, custom, redaction logic based on the SDKs domain.
