### ISSUE TITLE
VirtualMachineScaleSetsInner.createOrUpdate VMSS name validation required 

### ISSUE THREAD

**Issue by johnmanaloto** [Azure/azure-sdk-for-java#988]
Deploying a VM Scale Set with a long name (ex. 50 characters) using VirtualMachineScaleSetsInner.createOrUpdate results in situational failures (ex. failure to acquire lease on disk/already in use, NAT rule already in use) due to resource ids being truncated. Validation should be performed in accordance with VM Scale Set naming requirements and limitations.

**Comment by anuchandy** [comment]
@alpon (Alp Onalan) from compute service team to triage this.

**Comment by martinsawicki** [comment]
(not actionable on the SDK side alone)
