### ISSUE TITLE
Add Performance tests for Service Bus champion scenarios

### ISSUE THREAD

**Issue by joshfree** [Azure/azure-sdk-for-java#9919]
Tracking issue to create performance tests for Track 2 Service Bus champion scenarios

## Work
- [ ] Identify benchmarking data
- [ ] Setup performance test environment
- [ ] Write test cases for performance test
- [ ] Execute performance test and capture results

/cc @g2vinay

**Comment by hemanttanwar** [comment]
https://microsoft.sharepoint.com/teams/AzureDeveloperExperience/_layouts/OneNote.aspx?id=%2Fteams%2FAzureDeveloperExperience%2FShared%20Documents%2FService%20-%20Service%20Bus%2FAzure%20SDK%20-%20Service%20-%20Service%20Bus&wd=target%28Design.one%7C14D18AA9-3941-CF4D-B2FA-4B211AC30733%2FThroughput%20Test%7CA1B1A28E-DA08-4197-91A9-2F43333D8EFB%2F%29
onenote:https://microsoft.sharepoint.com/teams/AzureDeveloperExperience/Shared%20Documents/Service%20-%20Service%20Bus/Azure%20SDK%20-%20Service%20-%20Service%20Bus/Design.one#Throughput%20Test&section-id={14D18AA9-3941-CF4D-B2FA-4B211AC30733}&page-id={A1B1A28E-DA08-4197-91A9-2F43333D8EFB}&end
