### ISSUE TITLE
SB Track2 Create Production like Sample to settle message using receiver and  message 

### ISSUE THREAD

**Issue by hemanttanwar** [Azure/azure-sdk-for-java#9928]
create production like  Sample for settle the message in a separate class using receiver and  received message, show this to service team and see if that current API is acceptable.

Looked into following option but was not liked for many architectural reasons.

Mono<ServiceBusMessageContext> receive();

receive(receivedMessage-> {
receivedMessage.accept();
})

**Comment by ramya-rao-a** [comment]
Can we update the sample in https://github.com/richardpark-msft/azure-sdk-for-java/blob/4b1a7a2a9632fad36ecc3384d84b63af8068ba78/sdk/servicebus/azure-messaging-servicebus/src/samples/java/com/azure/messaging/servicebus/ServiceBusProcessorSample.java to include a comment that shows how to complete a message? That should be enough right? Or are we thinking of sample to settle messages when using sync client?

**Comment by anuchandy** [comment]
The sample is updated to include the comment as recommended by Ramya. Here is the [reference](https://github.com/Azure/azure-sdk-for-java/blob/main/sdk/servicebus/azure-messaging-servicebus/src/samples/java/com/azure/messaging/servicebus/ServiceBusProcessorSample.java#L82-L85).
