### ISSUE TITLE
Getting generic resource by ID ignores provider type - returns wrong object

### ISSUE THREAD

**Issue by grnadav** [Azure/azure-sdk-for-java#998]
Hello

When getting a generic resource by Id, it ignores the provider and uses only resource group name and object name, thus when there are 2 (or more) objects with same name (but different provider type) the wrong object is returned (first result?)

Issue is at:
https://github.com/Azure/azure-sdk-for-java/blame/master/azure-mgmt-resources/src/main/java/com/microsoft/azure/management/resources/fluentcore/arm/collection/implementation/GroupableResourcesImpl.java#L52

**Comment by martinsawicki** [comment]
good catch. 
[notes to self] GenericResources should not be extending the SupportsGettingByGroup interface. Instead, maybe just expose their own getByGroup which takes provider type as a 3rd param.

**Comment by martinsawicki** [comment]
PR with the fix created: https://github.com/Azure/azure-sdk-for-java/pull/1003

**Comment by martinsawicki** [comment]
fix merged into master.
`GenericResources@getByGroup()` has been removed.
A new `GenericResources@get()` overload has been added to identify a recourse using its resource group, name, provider namespace and resource type.
